### ISSUE TITLE
Project setup did not work

### ISSUE THREAD

**Issue by Eduard20CR** [dotnet/maui#19706] opened 2024-01-05 07:07 UTC
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'MauiApp' could not be found (are you missing a using directive or an assembly reference?)	MyFirstApp (net8.0-ios), MyFirstApp (net8.0-maccatalyst), MyFirstApp (net8.0-windows10.0.19041.0)	D:\01_WORK\01_SCARUS_DEV\03_PROYECTOS_TEST\2023\35_NET_GUI\MyFirstApp\MyFirstApp\MauiProgram.cs	5	Active

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0103	The name 'MauiApp' does not exist in the current context	MyFirstApp (net8.0-ios), MyFirstApp (net8.0-maccatalyst), MyFirstApp (net8.0-windows10.0.19041.0)	D:\01_WORK\01_SCARUS_DEV\03_PROYECTOS_TEST\2023\35_NET_GUI\MyFirstApp\MyFirstApp\MauiProgram.cs	7	Active

Severity	Code	Description	Project	File	Line	Suppression State
Error	XA1018	Specified AndroidManifest file does not exist: D:\01_WORK\01_SCARUS_DEV\03_PROYECTOS_TEST\2023\35_NET_GUI\MyFirstApp\MyFirstApp\AndroidManifest.xml.	MyFirstApp	C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.43\tools\Xamarin.Android.Common.targets	596

**Comment by jfversluis** [comment] 2024-03-27 08:57
Duplicate of https://github.com/dotnet/maui/issues/21406

**Closed by jfversluis** 2024-03-27 08:57 UTC
Labels: area/setup 🪄, tutorials
