### ISSUE TITLE
ScrollView does not recompute scroll size when content is being modified programmatically.

### ISSUE THREAD

**Issue by daryle2000** [dotnet/maui#18207] opened 2023-10-20 22:06 UTC
### Description

When adding elements to scrollview and modifying the number of elements like removing some, ScrollView does not recompute its scroll size. Example if I add 200 items to a VerticalStackLayout which is inside ScrollView, then I scroll to the 100th item and press a button which clears the content of the VerticalStackLayout and refresh the content with only 3 items, ScrollView would display blank. The blank ScrollView mean that I'm still having the same size of content, scrolled to same Y location. This only happen in iOS, android displays pretty well.

### Steps to Reproduce

1. Create MAUI app using .NET 8.0 preview rc.2
2. Remove all labels and images unrelated to the test
3. Add a ScrollView with VerticalStackLayout as content
4. On start of MainPage.xaml.cs, fill the the VerticalStackLayout of 200 Labels.
5. Add a button outside the ScrollView that will Clear the VerticalStackLayout of its children then add 3 more. The purpose of clearing and adding is to check if ScrollView would recompute its view when updating its content.
6. Run the app and scroll to the 100th item.
7. Tap on the button.
8. Please see the attached sample application

[Net80Test.zip](https://github.com/dotnet/maui/files/13058911/Net80Test.zip)

### Version with bug

8.0.0-rc.2.9373

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS

### Did you find any workaround?

A little bit. Dispose the current instance of the ScrollView and create another but won't work if inside a RefreshView.

**Comment by XamlTest** [comment] 2023-10-24 03:30
Verified this on Visual Studio Enterprise 17.8.0 Preview 4.0(8.0.0-rc.2.9373). Repro on iOS 16.4, not repro on Windows 11 and Android 14.0-API34 with below Project:
[Net80Test.zip](https://github.com/dotnet/maui/files/13110427/Net80Test.zip)

![Scroll](https://github.com/dotnet/maui/assets/97647558/6540c20b-c959-4478-b68b-824bf64baf28)

**Comment by mattleibow** [comment] 2023-10-24 22:07
Duplicate of https://github.com/dotnet/maui/issues/15374

**Comment by daryle2000** [comment] 2023-10-25 14:49
I only experience it on iOS. Android works fine. Lazy Loading is impossible with this issue.
Thanks for the help guys  :)

**Comment by ISSPRO-Eng** [comment] 2023-10-26 16:08
I am also experiencing this issue. Any fix yet? @daryle2000

**Comment by daryle2000** [comment] 2023-10-27 22:44
> I am also experiencing this issue. Any fix yet? @daryle2000

Nope. I hope in rc3. I'm stucked with my Lazy Loading page with RefreshView.

**Comment by ISSPRO-Eng** [comment] 2023-10-30 13:41
@daryle2000 I found this hot fix that works for myself.


            Microsoft.Maui.Handlers.ScrollViewHandler.Mapper.AppendToMapping(nameof(IScrollView.ContentSize), (h, v) =>
			{
#if IOS
				var contentSize = h.VirtualView.ContentSize;

                if (contentSize.IsZero)
					return;

				UIKit.UIScrollView uiScrollView = h.PlatformView;
				var container = uiScrollView.Subviews.FirstOrDefault(x => x.Tag == 0x845fed);			

				if (container != null && container.Bounds.Height != contentSize.Height)
				{
					container.Bounds = new CoreGraphics.CGRect(
						container.Bounds.X,
						container.Bounds.Y, 
						contentSize.Width, 
						contentSize.Height);

					(h.VirtualView as IView).InvalidateMeasure();
				}
            });

I added this into a customer Helper Class and call it from MauiProgram.cs.

**Comment by daryle2000** [comment] 2023-10-30 18:01
@ISSPRO-Eng 
I tried that before but did not work for me. 
Thanks :)

**Comment by e1T** [comment] 2023-11-14 11:59
@ISSPRO-Eng For some reason setting the container bounds doesn't work for me, but if I replace the code within the if statement to this it does work:
```
			if (container != null && container.Bounds.Height != contentSize.Height)
			{
                               (h.VirtualView as IView).Arrange(new Rect(
                                   container.Bounds.X,
                                   container.Bounds.Y,
                                   contentSize.Width, 
                                   contentSize.Height));
                               (h.VirtualView as IView).InvalidateMeasure();
                         }
```

**Comment by WdeBruin** [comment] 2023-11-16 15:30
![image](https://github.com/dotnet/maui/assets/18569131/01e7de6f-5590-4418-9a98-800932a13ac5)

My guess is that the fix should go here, in the MAUI solution. We probably do need to do something in MapContentSize for iOS.
But I didn't check yet if there are unittests that we can add, to fix this in a test driven way.

**Comment by WdeBruin** [comment] 2023-11-22 10:41
8.0.3 fixed it. Issue can be closed.

Tested on Mac with 8.0.3 with the provided sample application. 
Checked releasenotes: https://github.com/dotnet/maui/releases
A few bullets regarding viewport calculations with iOS Scrollview, that explains it.

**Closed** 2024-03-19 09:58 UTC
Labels: t/bug, area/layout 🔲, platform/iOS 🍎, s/verified, s/triaged, s/try-latest-version, migration-compatibility, layout-scrollview
