### ISSUE TITLE
Application.Current.RequestedThemeChanged event only raises once

### ISSUE THREAD

**Issue by Hottemax** [dotnet/maui#15350] opened 2023-05-31 08:50 UTC
### Description

#8236 Is closed, marked as fixed and can not be commented on.

However, this is still present in the current MAUI version that ships with current Visual Studio versions (17.6.2 as well as 17.7.0 Preview 1).

### Steps to Reproduce

[Reproduction repository](https://github.com/Hottemax/MauiApp1.RequestedThemeChangeRepro) is attached.

1. Create a File > New .NET MAUI App
2. Modify App.xaml.cs like so:

```cs
namespace MauiApp1;

public partial class App : Application
{
	public App()
	{
		RequestedThemeChanged += (s, a) => ConfigureTheme(a.RequestedTheme);
		InitializeComponent();
		MainPage = new AppShell();
	}

	private void ConfigureTheme(AppTheme requestedTheme)
	{
		// Breakpoint set on this line will only be hit exactly ONCE (the first time the system theme changes)
		UserAppTheme = requestedTheme;
	}
}
```

3. Start application > Repeat 2x: Switch light-to-dark mode or vice versa
4. Theme change only happens once, breakpoint indicating event was raised will only be hit once

It would be interesting to know why this was marked as completed/resolved by #11200, since it obviously was not.
In the MR, there seems to be no UnitTest checking that the event is raised successfully repeatedly.

### Link to public reproduction project repository

https://github.com/Hottemax/MauiApp1.RequestedThemeChangeRepro

### Version with bug

7.0.86

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android API 33

**Comment by drasticactions** [comment] 2023-06-19 05:20
This is complex, but for the code you wrote, the correct behavior is happening... but there are other bugs. I'll try to explain.

https://github.com/dotnet/maui/blob/68f968eba61b2809fc0e9b01a275266a80946951/src/Controls/src/Core/Application.cs#L234-L239

When you change the theme, either by the system theme or by changing the "UserAppTheme", this code is invoked. It looks to "RequestedTheme" to see if the theme has changed.

https://github.com/dotnet/maui/blob/68f968eba61b2809fc0e9b01a275266a80946951/src/Controls/src/Core/Application.cs#L186-L189

The first time you run it, since you didn't set the theme yourself, it looks at the platform theme. Since that's different now, it fires the event. So far so good.

https://github.com/Hottemax/MauiApp1.RequestedThemeChangeRepro/blob/67c86a2201b26275d2cb214518385cd27f83e395/App.xaml.cs#L15

But when it hits your code, you are setting the "UserAppTheme" to the color. "UserAppTheme" is a application specific setting, like for if you have a toggle switch within your application for setting Light/Dark mode outside of the system settings. By setting it yourself, you tell MAUI, "I will now handle app theme changes myself." 

This means that every time you change the system settings, the above MAUI code will be checking the 'UserAppTheme", which will be the last value you just set it to. So the "Theme" event will never fire again, because you haven't set it yourself. This is the correct behavior and what should be happening...

But I think you're doing this at all because if you _don't_ set the UserAppTheme, then the Android app doesn't update its current theme, and _that's_ the actual bug. It should be updated based on system platform changes, and it's not. You shouldn't have to do it yourself unless you have handled "UserAppTheme."

So I believe the code written in the PR you linked to is correct and working as intended. The problem is that the application theme is not updating when the system theme changes.

@jsuarezruiz @mattleibow Does that sound right?

**Comment by Hottemax** [comment] 2023-06-19 07:45
@drasticactions Thanks for taking the time to reply in such great detail, thank you!

So in summary, in my use case I don't want to provide a way in my app to toggle light/dark mode.
**I just want my app to react when it is changed outside the app (system settings).** I think this is what "AppTheme.Unspecified" is supposed to model?

**How do I achieve that?**

I guess [this user is also confused how to reach this goal](https://github.com/dotnet/maui/issues/10310#issuecomment-1296197095). Because without attaching an event handler, the app does not react to system changes at all...

**Comment by drasticactions** [comment] 2023-06-19 07:47
@Hottemax I've filed a new bug for your issue, https://github.com/dotnet/maui/issues/15723

In short, you shouldn't need to handle any event. Your application should automatically switch themes whenever the system theme changes. That it's not doing that is a bug.

**Comment by samhouts** [comment] 2023-08-04 22:41
Duplicate of #8236

**Closed by samhouts** 2023-08-04 22:41 UTC
Labels: t/bug, area/theme
