### ISSUE TITLE
Can not change the vertical and horizontal if the MauiSplashScreen

### ISSUE THREAD

**Issue by mcguu** [dotnet/maui#4684] opened 2022-02-15 05:38 UTC
### Description

If I set a image to maui splash screen it will set itselft and I can not change it to LayoutOptions.Vertical or LayoutOptions.Center or others.

### Public API Changes

Image.VerticalOptions.

### Intended Use-Case

To set the maui splash screen to display correctly.

**Comment by Redth** [comment] 2022-02-15 15:45
Can you please post some screenshots, and ideally a small project which reproduces the issue?

Also, are you suggesting the image is _not_ centered and you want it to be? Or that it is and you don't want it to be?

**Comment by mcguu** [comment] 2022-02-17 03:11
yes I am suggesting the image is not centered it is a image which may be 100px * 200px I want it be centered.

@Redth

**Comment by mcguu** [comment] 2022-02-22 06:21
[medical.zip](https://github.com/dotnet/maui/files/8114061/medical.zip)

here is a repo

**Comment by Mephisztoe** [comment] 2022-02-23 09:38
Can we please talk about how this feature even works? Because there is no real documentation about it. WHen creating a SplashScreen using XCode for iOS, I need to keep the dimensions of the device in mind so that there might be different storyboards for different screen layouts. ALso, I can design these screens in a very individual way. 

Using MauiSplashScreen with a scalable vector image seems promising, but how does it work? Some samples suggest to take the AppIcon. WHen I do this, the icon gets scaled so that it is actually larger than the display itself.

Also, on iOS, the SplashScreen is not shown at all, or the app crashes right away.
On Android, it does not look as expected. 
On WinUI there is also no SplashScreen.

**Comment by wenwen60** [comment] 2022-03-01 02:45
Reproduce on windows using VS2022(17.2.0 Preview 2.0), attach repro sample
[medical.zip](https://github.com/dotnet/maui/files/8158406/medical.zip).

**Comment by mattleibow** [comment] 2022-08-31 03:50
Duplicate of #5676

**Closed by mattleibow** 2022-08-31 03:50 UTC
Labels: proposal/open, area/single project ☝️, s/verified, s/needs-attention
