### ISSUE TITLE
MAUI Razor Component CSS not compiling on iOS local device (iPhone)

### ISSUE THREAD

**Issue by PBTests** [dotnet/maui#9723] opened 2022-08-28 17:19 UTC
**What's the issue?**

Boilerplate .NET MAUI Blazor application does not deploy to iOS physical device correctly. 

The Blazor component CSS appears to not compile, meaning the navigation does not render correctly.

### **Everything renders as expected on the iOS Simulator, Android**, etc...

Latest XCode / VSMac / VS2022 / VS2022-pre / Workloads / Blabla

Tried everything

Seriously... 

Can anyone help?

**Steps to reproduce...**

1. Create a new MAUI Blazor application (VS22/22p)
2. Debug on paired Mac to specified Local Device (iOS 15.5) (effectively deploying to physical device)
3. Result: No classic blazor purple coloured navigation style due to lack of component CSS rendering  

**Screenshot**

![image](https://user-images.githubusercontent.com/56082224/185001233-100248d7-d180-436a-b5da-6ab3fe0b6e74.png)

_Originally posted by @PBTests in https://github.com/dotnet/maui/discussions/9475_

**Comment by BlaineM-SeriouslyRAD** [comment] 2022-08-28 22:17
Duplicate of #7468

**Comment by TanayParikh** [comment] 2022-08-29 16:42
Closing as duplicate.

**Closed by TanayParikh** 2022-08-29 16:42 UTC
Labels: area/blazor 🕸️, platform/iOS 🍎
