### ISSUE TITLE
[iOS, .NET 9.0 Preview 7] Border size changes are animated on iOS

### ISSUE THREAD

**Issue by janne-hmp** [dotnet/maui#24287] opened 2024-08-16 19:45 UTC
### Description

When changing the size of a Border on iOS, it undesirably animates to the new size. This is especially problematic when there is a Border that is invisible and supposed to be adjusted to a new size before being made visible. It seems impossible to make it change size instantaneously like the other controls such as Frame that it is replacing. Probably the same as #15363 but the issue persists in .NET 9.0 Preview 7

### Steps to Reproduce

1. Create a Border control in your UI on iOS
2. Change its size
3. The Border adjusts slowly to the new size in an animated fashion

### Version with bug

9.0.0-preview.7.24407.4

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 17.5.1

### Did you find any workaround?

https://github.com/dotnet/maui/issues/18204#issuecomment-1900122924

**Comment by PureWeen** [comment] 2024-08-16 19:59
Duplicate of #24104

**Closed by PureWeen** 2024-08-16 19:59 UTC
Labels: t/bug
