### ISSUE TITLE
[Android]:  CollectionView header template is not rendered

### ISSUE THREAD

**Issue by Strypper** [dotnet/maui#14603] opened 2023-04-16 19:45 UTC
### Description

I'm so frustrated by this issue. CollectionView header template does render the `Frame` inside the DataTemplate, but nothing is visible in the frame, the image below is the original UI that have the header rendered just fine 
![image](https://user-images.githubusercontent.com/32596308/232336043-79d8c17a-da79-4172-ba47-e13fccc8fc7c.png)
**Now it's behave like this** 

![WikiPage Header Bug](https://user-images.githubusercontent.com/32596308/232338129-d55141af-1320-480e-8bdb-8b1dcaeed7ed.gif)

I'm unable to track what change in my code but here is the full implementation
## Xaml Page
```xml
<?xml version="1.0" encoding="utf-8" ?>
<app:BasePage
    x:Class="PetaverseMAUI.WikiPage"
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:app="clr-namespace:PetaverseMAUI"
    xmlns:toolkit="http://schemas.microsoft.com/dotnet/2022/maui/toolkit"
    x:DataType="app:WikiPageViewModel"
    SizeChanged="BasePage_SizeChanged">
    <Shell.SearchHandler>
        <app:WikiSearchHandler
            BreedList="{x:Binding Species}"
            ClearIcon="{x:StaticResource Clear24Icon}"
            Placeholder="Explore the animal world"
            QueryIcon="{x:StaticResource SearchIcon}"
            SelectBreedList="BreedHandler_SelectBreedList"
            ShowsResults="True">
            <app:WikiSearchHandler.ItemTemplate>
                <DataTemplate x:DataType="app:BreedCardModel">
                    <Grid
                        Margin="5"
                        ColumnDefinitions="40,Auto"
                        RowDefinitions="Auto">
                        <Image
                            HeightRequest="50"
                            Source="{x:Binding BreedImageUrl}"
                            WidthRequest="35" />
                        <Label
                            Grid.Column="1"
                            FontSize="18"
                            HorizontalTextAlignment="Center"
                            Text="{x:Binding BreedName}"
                            VerticalTextAlignment="Center" />
                    </Grid>
                </DataTemplate>
            </app:WikiSearchHandler.ItemTemplate>
        </app:WikiSearchHandler>
    </Shell.SearchHandler>

    <app:BasePage.ToolbarItems>
        <ToolbarItem IconImageSource="{x:StaticResource WikiScanCameraIcon}" />
    </app:BasePage.ToolbarItems>

    <app:BasePage.Resources>

        <DataTemplate x:Key="SpeciesCollectionViewHeaderTemplate" x:DataType="app:WikiPageViewModel">

            <Frame Margin="{app:EdgeInsets All={x:Static app:Dimensions.SpacingMd}}" HasShadow="True">
                <Grid ColumnDefinitions="*, auto">
                    <VerticalStackLayout Spacing="{x:Static app:Dimensions.SpacingSm}">
                        <Label Style="{x:Static app:Styles.Heading3}" Text="Species" />
                        <HorizontalStackLayout
                            BindableLayout.ItemTemplate="{x:StaticResource SpeciesPivotItemTemplate}"
                            BindableLayout.ItemsSource="{x:Binding Species}"
                            RadioButtonGroup.GroupName="SelectedItem"
                            RadioButtonGroup.SelectedValue="{x:Binding SelectedSpecies,
                                                                       Mode=TwoWay}"
                            Spacing="{x:Static app:Dimensions.SpacingSm}" />
                        <Label Style="{x:Static app:Styles.Heading4}" Text="Filter" />
                        <HorizontalStackLayout Spacing="{x:Static app:Dimensions.SpacingSm}">
                            <Picker Title="Size" />
                            <Picker Title="Coat" />
                            <Picker Title="Shedding" />
                            <Picker Title="Energy" />
                        </HorizontalStackLayout>
                    </VerticalStackLayout>

                    <Frame
                        Grid.Column="1"
                        BackgroundColor="{x:StaticResource Primary}"
                        HasShadow="True"
                        HorizontalOptions="End"
                        IsVisible="{x:Binding IsSpeciesFrameInfoVisible}">
                        <Label
                            LineBreakMode="WordWrap"
                            MaximumWidthRequest="280"
                            Text="Your cat is cute – you know it, and they know it. With such a large community of feline enthusiasts online, comes a long list of cute cate quotes only cat lovers will understand. We’ve gathered 30 of the cutest cat quotes perfect to put on your personalized home decor – a practical and stylish solution that will help you to integrate your love for cats in your home décor that doesn’t scream “crazy cat lady”"
                            TextColor="White" />
                    </Frame>
                </Grid>
            </Frame>
        </DataTemplate>

        <DataTemplate x:Key="SpeciesCollectionViewItemTemplate" x:DataType="app:BreedCardModel">
            <app:BreedCardContentView Margin="{app:EdgeInsets All={x:Static app:Dimensions.SpacingMd}}" ComponentData="{x:Binding}" />
        </DataTemplate>

        <DataTemplate x:Key="SpeciesCollectionViewFooterTemplate" x:DataType="app:WikiPageViewModel" />

        <GridItemsLayout
            x:Key="BreedLayout"
            Orientation="Vertical"
            Span="{x:Binding Span}" />

    </app:BasePage.Resources>

    <RefreshView Command="{x:Binding RefreshCommand}" IsRefreshing="{x:Binding IsBusy}">
        <CollectionView
            Footer="{x:Binding}"
            FooterTemplate="{x:StaticResource SpeciesCollectionViewFooterTemplate}"
            Header="{x:Binding}"
            HeaderTemplate="{x:StaticResource SpeciesCollectionViewHeaderTemplate}"
            ItemTemplate="{x:StaticResource SpeciesCollectionViewItemTemplate}"
            ItemsLayout="{x:StaticResource BreedLayout}"
            ItemsSource="{x:Binding SelectedSpecies.BreedCards}" />
    </RefreshView>
</app:BasePage>
```

## Code behind
```cs
namespace PetaverseMAUI;

public partial class WikiPage
{
    private WikiPageViewModel viewModel;
    public WikiPage(WikiPageViewModel vm)
    {
        InitializeComponent();

        BindingContext = viewModel = vm;
    }

    #region [Event Handler]
    private void BasePage_SizeChanged(object sender, EventArgs e)
    {
        if (Window.Width < 500)
        {
            if (viewModel is not null)
            {
                viewModel.Span = 1;
                viewModel.IsSpeciesFrameInfoVisible = false;
                return;
            }
        }
        else if (Window.Width < 900)
        {
            if (viewModel is not null)
            {
                viewModel.Span = 2;
                viewModel.IsSpeciesFrameInfoVisible = true;
                return;
            }
        }
        else if (Window.Width < 2000)
        {
            if (viewModel is not null)
            {
                viewModel.Span = 3;
                viewModel.IsSpeciesFrameInfoVisible = true;
                return;
            }
        }
    }

    private void BreedHandler_SelectBreedList(BreedCardModel breed)
    {
        //PetsCollectionView.ScrollTo(pet, animate: true);
        viewModel.NavigateToBreedDetailCommand.Execute(breed);
    }
    #endregion
}
```

## Viewmodel
```cs
namespace PetaverseMAUI;

public partial class WikiPageViewModel : NavigationAwareBaseViewModel
{
    #region [Services]
    private readonly IWikiService wikiService;
    #endregion

    #region [CTor]
    public WikiPageViewModel(
        IWikiService wikiService,
        IAppNavigator appNavigator) : base(appNavigator)
    {
        this.wikiService = wikiService;
    }
    #endregion

    #region [Properties]
    [ObservableProperty]
    bool isBusy;

    [ObservableProperty]
    bool isSpeciesFrameInfoVisible;

    [ObservableProperty]
    SpeciesPivotModel selectedSpecies;

    [ObservableProperty]
    ObservableCollection<SpeciesPivotModel> species;

    [ObservableProperty]
    ObservableCollection<BreedCardModel> fakeBreedCards;

    [ObservableProperty]
    int span = 1;
    #endregion

    #region [Overrides]
    protected async override void OnInit(IDictionary<string, object> query)
    {
        base.OnInit(query);
    }

    public override async Task OnAppearingAsync()
    {
        await base.OnAppearingAsync();

        LoadDataAsync().FireAndForget();
    }
    #endregion

    #region [RelayCommands]
    [RelayCommand]
    private void Refresh() => LoadDataAsync().ContinueWith(x => IsBusy = false)
                                             .FireAndForget();

    [RelayCommand]
    private void NavigateToBreedDetail(BreedCardModel breedCardModel)
                        => AppNavigator.NavigateAsync(AppRoutes.Wiki, args: breedCardModel);
    #endregion

    #region [Methods]
    private async Task LoadDataAsync()
    {
        if (IsBusy) return;

        IsBusy = true;

        if (Species == null)
        {
            Species = new ObservableCollection<SpeciesPivotModel>();
        }

        Species.Clear();

        var items = await wikiService.GetAllSpecies();

        foreach (var item in items)
        {
            Species.Add(item);
        }

        SelectedSpecies = Species.FirstOrDefault();

        IsBusy = false;
    }
    #endregion
}

```

### Steps to Reproduce

Above

### Link to public reproduction project repository

This is NDA 

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

All android

### Did you find any workaround?

No

### Relevant log output

```shell
None
```

**Comment by drasticactions** [comment] 2023-04-17 05:54
Duplicate of https://github.com/dotnet/maui/issues/14603. 

I updated that issue to reflect that it's happening on multiple platforms, I believe for similar reasons.

**Comment by Strypper** [comment] 2023-04-17 09:16
> Duplicate of #14603.
> 
> I updated that issue to reflect that it's happening on multiple platforms, I believe for similar reasons.

Duplicate of #14557

**Comment by samhouts** [comment] 2023-07-17 20:00
Duplicate of #14557

**Closed** 2024-06-07 23:52 UTC
Labels: t/bug, platform/android 🤖, area-controls-collectionview
