### ISSUE TITLE
Publish Device Runners

### ISSUE THREAD

**Issue by dansiegel** [dotnet/maui#8779] opened 2022-07-16 00:13 UTC
### Description

Testing Maui apps should be made easier. The Maui repo already has device runners for running unit tests. It would be in the best interest of the community to publish these runners so that 3rd party libraries and apps can easily begin testing with these runners. 

### Public API Changes

No actual api changes are needed. We simply need the runners packaged and published with each release. As these runners make use of xharness it would also be helpful to have the xharness cli tool published to NuGet. 

### Intended Use-Case

Test 3rd party libraries and app code

**Comment by premun** [comment] 2022-07-19 08:40
Publishing the CLI might be problematic thanks to the fact it includes mlaunch (and adb not sure that is a problem).

@rolfbjarne thoughts?
cc @tkapin

**Comment by rolfbjarne** [comment] 2022-08-17 14:45
mlaunch is an internal tool, and should not be called directly by customers.

If you want to expose xharness, having in mind that mlaunch is basically unsupported and that you'll have to update your code to handle any breaking changes in mlaunch, that should be fine with us.

**Comment by samhouts** [comment] 2023-07-26 20:35
Duplicate of #11236

**Closed by samhouts** 2023-07-26 20:35 UTC
Labels: proposal/open, partner, area/testing
