### ISSUE TITLE
Pasting long text into the Editor not possible on iOS

### ISSUE THREAD

**Issue by CayasSoftware** [dotnet/maui#23831] opened 2024-07-25 14:52 UTC
### Description

The Editor control behaves differently on iOS than on Android if MaxLength is set and a text is to be inserted into the control beyond this limit via copy-paste.

The difference is that in Android the text is cut off according to the MaxLength. On iOS, on the other hand, the change is not made by copying and pasting.

According to my analysis so far, the problem lies in[ ITextInputExtensions.cs](https://github.com/dotnet/maui/blob/d54c8fa8c257a54d9a87f9a576a963a8dd0e6a8c/src/Core/src/Core/Extensions/ITextInputExtensions.cs#L7). There it is only returned for iOS whether the text would fit into the MaxLength. For Android, on the other hand, the text is simply updated via UpdateText and truncated if necessary.

### Steps to Reproduce

1. Create a MAUI app
2. Add an Editor like <Editor MaxLength="200" />
3. Create a 220 character long text and copy that into your clipboard
4. Start the app and past the copied text into the Editor control.

### Version with bug

9.0.0-preview.6.24327.7

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS all

**Comment by kubaflo** [comment] 2024-07-28 15:24
Duplicate of https://github.com/dotnet/maui/issues/17783

**Closed by kubaflo** 2024-07-28 15:24 UTC
Labels: t/bug
