### ISSUE TITLE
[Android] Receives the scrolled notification after some delay in horizontal scrolling

### ISSUE THREAD

**Issue by ashok-kuvaraja** [dotnet/maui#5187] opened 2022-03-10 11:21 UTC
### Description

I have prepared a simple sample and written a custom grid to arrange a label based on the scroll view's `ScrollX` position. I have written a custom scroll view handler to achieve horizontal scrolling since the scrolled event did not work for horizontal orientation. The label is rendered to the screen after some delay when I fling a scroll view. But, If I do smooth scrolling, it layout properly. 

Seems the scroll view is moved based on the user scrolling interactions but the scroll views scrolled event is triggered after some delay from that. I guess this is the reason for happening the delay. So, When I fling a scroll view, the label is layout to the corresponding position after showing a blank screen little time.

Due to this issue,  I am facing a layouting issue in the virtualization concept in my application. Please review and fix the bug or gimme any workaround to resolve this issue.

### Steps to Reproduce

1. Run the below sample.
2. Do fling in the horizontal direction

**Sample:** 
[ScrollingDemo.zip](https://github.com/dotnet/maui/files/8222856/ScrollingDemo.zip)

### Demo

https://user-images.githubusercontent.com/60499432/157650505-e1f8002c-9b19-4e90-84bb-aa16ab8e6e6f.mp4

### Version with bug

Preview 12

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Ensured in Android 7.1.1

### Did you find any workaround?

No

**Comment by jfversluis** [comment] 2022-03-10 12:23
Maybe related to or even duplicate of #5090

**Comment by ashok-kuvaraja** [comment] 2022-03-10 13:32
Hi @jfversluis,

Thanks for your rapid response,
 
As you mentioned, the horizontal scrolling is also not working. But, we achieved this through the workaround (Get the HorizontalScrollView's instance and invoke its scrollChange event and pass it to the virtual view's offset). Now, the horizontal scrolling is working on our side through the workaround. 

```c#
public partial class CustomScrollViewHandler : Microsoft.Maui.Handlers.ScrollViewHandler
    {
        private HorizontalScrollView nativeHorizontalScrollView;

        protected override MauiScrollView CreateNativeView()
        {
            var nativeScrollView = base.CreateNativeView();
            nativeScrollView.ChildViewAdded += this.MauiScrollView_ChildViewAdded;
            return nativeScrollView;
        }

        private void MauiScrollView_ChildViewAdded(object? sender, ViewGroup.ChildViewAddedEventArgs e)
        {
            if (e.Child is HorizontalScrollView && e.Child != this.nativeHorizontalScrollView)
            {
                this.nativeHorizontalScrollView = (HorizontalScrollView)e.Child;
                this.nativeHorizontalScrollView.ScrollChange += this.HorizontalScrollView_ScrollChange;
            }
        }

        private void HorizontalScrollView_ScrollChange(object? sender, ScrollChangeEventArgs e)
        {
            this.VirtualView.HorizontalOffset = Microsoft.Maui.Platform.ContextExtensions.FromPixels(this.Context, e.ScrollX);
        }
    }
```

In our case, the delay has happened in layouting a label while doing a fling in the scroll view. I guess the issue will be resolved if both scroll view's content scrolling and the `scrolled` event invoking will happen simultaneously.

Regards,
Ashok K

**Comment by Amir-Care** [comment] 2022-03-11 01:44
Verified repro with Version 17.2.0 Preview 2.0 [32208.484.main] on Android 11

**Comment by ashok-kuvaraja** [comment] 2022-03-17 07:00
Hi, Any further update on this?

**Comment by jfversluis** [comment] 2022-03-17 08:09
@ashok-kuvaraja not yet, we'll get to it!

**Comment by ashok-kuvaraja** [comment] 2022-03-29 04:50
Hi Team, Any further update on this?

**Comment by jfversluis** [comment] 2022-03-29 07:45
If there is you will see it here. Not need to ask :)

**Comment by Zhanglirong-Winnie** [comment] 2023-05-06 10:08
Verified this issue with Visual Studio Enterprise 17.6.0 Preview 5.0. Not repro on Android Platform.
Repro project: [ScrollingDemo.zip](https://github.com/dotnet/maui/files/11412034/ScrollingDemo.zip)
![Scrolled](https://user-images.githubusercontent.com/77434865/236617853-d19b961c-979e-4d8c-ba7b-a5869b798f82.gif)

**Closed** 2023-05-13 13:01 UTC
Labels: t/bug, area/layout 🔲, platform/android 🤖, s/triaged, s/try-latest-version
