### ISSUE TITLE
Cascading memory leak when StrokeShape is set on Border control on iOS

### ISSUE THREAD

**Issue by AdamEssenmacher** [dotnet/maui#20121] opened 2024-01-23 19:59 UTC
### Description

Setting the `StrokeShape` property on a Border control in iOS results in the control and its containing page to leak.

Page-level leaks are serious, as they prevent child elements from being collected as well.

### Steps to Reproduce

1) Push a page that contains a Border with its StrokeShape property set
2) Pop the page
3) Force GC runs
4) Observe the page is never collected

### Link to public reproduction project repository

https://github.com/AdamEssenmacher/iOSBorderLeak.Maui

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 17.2

**Comment by AdamEssenmacher** [comment] 2024-01-25 09:19
Would the area/perf label be appropriate here as well? This issue causes entire pages (and possibly nav stacks) not to be GC'ed, which causes noticeable performance degradation once the app starts needing swap space, and ultimately leading to forced app termination.

**Comment by jsuarezruiz** [comment] 2024-04-08 09:06
Thanks for the details and the sample Adam. Cannot reproduce in main branch, could you try with the latest nightly package?
![border-leak-issue](https://github.com/dotnet/maui/assets/6755973/635e7379-32bd-40e8-82b3-24eabff5e943)

**Comment by jsuarezruiz** [comment] 2024-04-08 13:57
Could have been fixed by https://github.com/dotnet/maui/pull/21151

**Comment by AdamEssenmacher** [comment] 2024-04-09 15:21
@jsuarezruiz I just confirmed this appears to be fixed in `8.0.40-nightly.10455`

**Comment by jonathanpeppers** [comment] 2024-04-09 17:04
Thanks! Fix was:
* https://github.com/dotnet/maui/pull/21151

**Closed by jonathanpeppers** 2024-04-09 17:04 UTC
Labels: t/bug, area/drawing ✏️, platform/iOS 🍎, area/perf 🏎️, partner/cat 😻, memory-leak 💦
