### ISSUE TITLE
[Android] Editor not displaying text correctly

### ISSUE THREAD

**Issue by ivan-todorov-progress** [dotnet/maui#9002] opened 2022-07-26 09:30 UTC
### Description

The `Editor` component does not display its text correctly on Android. Just place an `Editor` in a `VerticalStackLatout` and try to enter some text in it:

```xml
<VerticalStackLayout Margin="10" Spacing="10">
    <Label Text="Enter some text" />
    <Editor HeightRequest="300" BackgroundColor="LightGray" />
</VerticalStackLayout>
```

I have set the `BackgroundColor` property of the `Editor` in the above XAML to demonstrate that the component is sized correctly, but the text is displayed incorrectly.

The following screenshot shows how the `Editor` looks on Android after entering some text:

![image](https://user-images.githubusercontent.com/98032058/180970891-c4b232f9-c9b5-45f2-b4c9-91dd8ca0967d.png)

For reference, here is how the same `Editor` looks on iOS after entering some text:

![image](https://user-images.githubusercontent.com/98032058/180971954-6958e44b-e11f-4922-9d73-674d49fe5fb7.png)

Similar thing happens when the `Editor` is initialized with some text, but the text is shorter than the available horizontal space. For instance, if I initialize the `Editor` like this:

```xml
<Editor Text="Some text" HeightRequest="300" BackgroundColor="LightGray" />
```

Then when I try to enter some text, the newly entered text just wraps to the width of the initial text:

![image](https://user-images.githubusercontent.com/98032058/180973026-e4735e4c-8516-45bf-a236-9ff41614573b.png)

### Steps to Reproduce

1. Run the attached sample project on Android
2. Try to enter some text in the Editor component

[TestApp.zip](https://github.com/dotnet/maui/files/9188502/TestApp.zip)

### Version with bug

6.0.408 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

N/A

**Comment by ivan-todorov-progress** [comment] 2022-07-26 09:32
After some digging, I have found several similar issues, but they describe slightly different scenarios, so I decided to log this as a separate bug report.

https://github.com/dotnet/maui/issues/8313
https://github.com/dotnet/maui/issues/8232
https://github.com/dotnet/maui/issues/7810

**Comment by jfversluis** [comment] 2022-07-28 18:28
Duplicate of #8232

**Closed by jfversluis** 2022-07-28 18:28 UTC
Labels: t/bug, partner, area/controls 🎮, s/needs-verification
