### ISSUE TITLE
[Bug] [Mac Catalyst] Device.RuntimePlatform is set to Device.iOS

### ISSUE THREAD

**Issue by drasticactions** [dotnet/maui#2675] opened 2021-09-23 20:37 UTC
<img width="671" alt="スクリーンショット 2021-09-23 午後4 34 10" src="https://user-images.githubusercontent.com/898335/134580071-85e50cd0-b745-4fe6-b01a-5ca37921a4f1.png">

### Description

If you use `Microsoft.Maui.Controls.Device.RuntimePlatform` to detect which platform your app is being run on, it will be iOS even though this is a Mac Catalyst app.

**Comment by jamesmontemagno** [comment] 2021-09-24 05:44
We had some conversation about this. previously -> https://github.com/xamarin/Essentials/issues/1700

There are 2 situations... 1.) mac catalyst 2.) iOS app on a mac

**Comment by jfversluis** [comment] 2021-10-05 18:35
Related to #2423

**Comment by v-longmin** [comment] 2022-03-03 06:26
Thank you so much for your bug report! Unfortunately, we cannot reproduce your issue with the information above, could you provide a sample project and screenshots or more details that we can reproduce your issue? That should greatly speed up the process, thanks!

**Comment by jfversluis** [comment] 2022-03-03 09:12
This one is fixed by #3763

**Closed by jfversluis** 2022-03-03 09:12 UTC
Labels: t/bug, area/desktop 🖥️, s/triaged, s/needs-repro
