### ISSUE TITLE
MAUI Template not found when new solution is created

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#8905] opened 2022-07-21 20:30 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/MAUI-Template-Lost/10096972)._

---
MAUI can no longer be selected from the New Solution template.

![スクリーンショット 2022-07-16 14.22.37.png](https://aka.ms/dc/image?name=B781e8ddf27a346be9afe772ecd8ddcee637935461789483556_%E3%82%B9%E3%82%AF%E3%83%AA%E3%83%BC%E3%83%B3%E3%82%B7%E3%83%A7%E3%83%83%E3%83%88_2022-07-16_14.22.37.png&tid=781e8ddf27a346be9afe772ecd8ddcee637935461789483556)

---
#### Satoshi Nakamura on 7/15/2022, 11:11 PM: 

(private comment, text removed)
#### Feedback Bot on 7/17/2022, 08:07 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by samhouts** [comment] 2022-07-21 20:56
Duplicate of #8076

**Closed by samhouts** 2022-07-21 20:56 UTC
Labels: s/needs-verification
