### ISSUE TITLE
Navigation not working on Windows

### ISSUE THREAD

**Issue by 99067718** [dotnet/maui#10241] opened 2022-09-21 14:54 UTC
### Description

Navigation seemed to stop working since last update on Windows when used like this 
Shell.Current.GoToAsync("//AboutPage", GoToViewAnimation);

This only occurs on windows as far as I know.
and it also occurs when you get it from a flyout menu, but I don't know how to replicate that.

(I checked if the buttons were still working by making animations play, and it seems like the code just skips over the navigation part)

### Steps to Reproduce

Create a button that serves as a navigation button, and use the Shell.Current.GoToAsync( ); method to navigate.
and make sure its in a grid (sometimes a stacklayout).
For some reason this only happens with specific pages.
I don't really understand the exact logic behind the bug since its always different every time the application restarts.
(some pages permanently get glitched)

### Link to public reproduction project repository

Link: https://github.com/99067718/DummyApp

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10: 10.0.19043 Build 19043

### Did you find any workaround?

No

### Relevant log output

```shell
No log output, the navigation will just get skipped.
```

**Comment by 99067718** [comment] 2022-09-22 07:27
I have added the repository link: https://github.com/99067718/DummyApp
it acts even weirder now, I don't know whats going on.

**Comment by PureWeen** [comment] 2022-10-17 14:44
Duplicate of #10524

**Closed by PureWeen** 2022-10-17 14:44 UTC
Labels: t/bug, platform/windows 🪟, area/navigation 🧭, area/shell 🐢
