### ISSUE TITLE
[Android] Text Clipping Issue in Entry with Long Strings

### ISSUE THREAD

**Issue by HariharanChokkalingam** [dotnet/maui#23774] opened 2024-07-23 12:44 UTC
### Description

When the text string has many characters, the text gets clipped when IsReadOnly is set to true, and we cannot view the first part of the text. Is there any possibility to view the text from the beginning?

https://github.com/user-attachments/assets/1e4d7a54-bf1d-4630-a81a-0375d8d5c489

### Steps to Reproduce

Obtain the sample from the below repository
Replicate the issue as did like in the above video.

### Link to public reproduction project repository

https://github.com/HariharanChokkalingam/EntryIssue

### Version with bug

8.0.70 SR7

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Did you find any workaround?

No

### Relevant log output

```shell
No Response.
```

**Comment by mattleibow** [comment] 2024-07-23 22:48
Potentially a duplicate of https://github.com/dotnet/maui/issues/23054

**Comment by jfversluis** [comment] 2024-11-22 17:01
Duplicat of #23054

**Comment by jfversluis** [comment] 2024-11-22 17:02
In addition: I think you can take the code from #25554 if you really want to implement this yourself, but I don't think we should go against the default behavior here.

**Closed by jfversluis** 2024-11-22 17:01 UTC
Labels: t/bug, platform/android 🤖, area-controls-entry
