### ISSUE TITLE
Get native Window handle from control

### ISSUE THREAD

**Issue by srikrishnancgvak28** [dotnet/maui#11718] opened 2022-11-29 06:09 UTC
WinForms with C#
The C# code below shows how to retrieve the window handle (HWND) for a WinForms form object. This example uses the [NativeWindow.Handle](https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.nativewindow.handle) property.
C#
// Form1.cs
private void button1_Click(object sender, EventArgs e)
{
    var hWnd = this.Handle;
}
Like that how to get the Native window Handle of the Control in MAUI.
[(https://github.com/dotnet/maui/issues/6843)]

**Comment by rachelkang** [comment] 2022-11-29 19:17
Duplicate of https://github.com/dotnet/maui/issues/6843

**Closed by rachelkang** 2022-11-29 19:17 UTC
Labels: s/question ?
