### ISSUE TITLE
The program '[4884] MyFirstMauiApp.exe' has exited with code 2147942405 (0x80070005).

### ISSUE THREAD

**Issue by mohitsoam** [dotnet/maui#13276] opened 2023-02-11 19:16 UTC
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

-------------------------
'MyFirstMauiApp.exe' (CoreCLR: DefaultDomain): Loaded 'C:\Users\mohit\source\repos\MyFirstMauiApp\MyFirstMauiApp\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\System.Private.CoreLib.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MyFirstMauiApp.exe' (CoreCLR: clrhost): Loaded 'C:\Users\mohit\source\repos\MyFirstMauiApp\MyFirstMauiApp\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\MyFirstMauiApp.dll'. Symbols loaded.
'MyFirstMauiApp.exe' (CoreCLR: clrhost): Loaded 'C:\Users\mohit\source\repos\MyFirstMauiApp\MyFirstMauiApp\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\System.Runtime.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MyFirstMauiApp.exe' (CoreCLR: clrhost): Loaded 'C:\Users\mohit\source\repos\MyFirstMauiApp\MyFirstMauiApp\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\Microsoft.Windows.ApplicationModel.WindowsAppRuntime.Projection.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MyFirstMauiApp.exe' (CoreCLR: clrhost): Loaded 'C:\Users\mohit\source\repos\MyFirstMauiApp\MyFirstMauiApp\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\System.Runtime.InteropServices.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MyFirstMauiApp.exe' (CoreCLR: clrhost): Loaded 'C:\Users\mohit\source\repos\MyFirstMauiApp\MyFirstMauiApp\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\WinRT.Runtime.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MyFirstMauiApp.exe' (CoreCLR: clrhost): Loaded 'C:\Users\mohit\source\repos\MyFirstMauiApp\MyFirstMauiApp\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\System.Collections.Concurrent.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MyFirstMauiApp.exe' (CoreCLR: clrhost): Loaded 'C:\Users\mohit\source\repos\MyFirstMauiApp\MyFirstMauiApp\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\System.Collections.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MyFirstMauiApp.exe' (CoreCLR: clrhost): Loaded 'C:\Users\mohit\source\repos\MyFirstMauiApp\MyFirstMauiApp\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\System.Threading.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MyFirstMauiApp.exe' (CoreCLR: clrhost): Loaded 'C:\Users\mohit\source\repos\MyFirstMauiApp\MyFirstMauiApp\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\System.Runtime.CompilerServices.Unsafe.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MyFirstMauiApp.exe' (CoreCLR: clrhost): Loaded 'C:\Users\mohit\source\repos\MyFirstMauiApp\MyFirstMauiApp\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\System.Private.Uri.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MyFirstMauiApp.exe' (CoreCLR: clrhost): Loaded 'C:\Users\mohit\source\repos\MyFirstMauiApp\MyFirstMauiApp\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\System.ObjectModel.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MyFirstMauiApp.exe' (CoreCLR: clrhost): Loaded 'C:\Users\mohit\source\repos\MyFirstMauiApp\MyFirstMauiApp\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\System.ComponentModel.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MyFirstMauiApp.exe' (CoreCLR: clrhost): Loaded 'C:\Users\mohit\source\repos\MyFirstMauiApp\MyFirstMauiApp\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\System.Numerics.Vectors.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
The program '[4884] MyFirstMauiApp.exe' has exited with code 2147942405 (0x80070005).

**Comment by holecekp** [comment] 2023-02-11 19:41
It could be the same issue as https://github.com/dotnet/maui/issues/12080. You can try one of the workarouds in that issue.

**Comment by mattleibow** [comment] 2023-02-12 11:39
Duplicate of https://github.com/dotnet/maui/issues/12080

**Closed by mattleibow** 2023-02-12 11:39 UTC
