### ISSUE TITLE
XmlnsDefinitionAttribute and CS0246 The type or namespace name could not be found

### ISSUE THREAD

**Issue by SchreinerK** [dotnet/maui#8158] opened 2022-06-19 06:13 UTC
### Description

If I crate a library, assigning the namespace with a XmlnsDefinitionAttribute and use the lib, the type will not be resolved.
>error CS0246: The type or namespace name 'MauiLib1' could not be found (are you missing a using directive or an assembly reference?)

### Steps to Reproduce

[use complete project](https://github.com/SchreinerK/Issue20220619_2_Maui_XmlnsDefinitionAttribute)

-or-

1. Create a new MAUI app
2. Add new MAUI library (MauiLib1)
3. modify Class1
    - derive from `Label`
    - add `[assembly: XmlnsDefinition("http://MauiLib1", "MauiLib1")]`
4. reference MauiLib1 project to the app
5. modify MainPage.xaml
    - add `xmlns:my="http://MauiLib1"`
    - add `<my:Class1/>`
6. Build

MainPage.xaml.cs(1,7,1,15): error CS0246: The type or namespace name 'MauiLib1' could not be found (are you missing a using directive or an assembly reference?)

with using `xmlns:my="clr-namespace:MauiLib1;assembly=MauiLib1"` there is no error, so it must be the resolving over the XmlnsDefinition.

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Windows10.0.19041.0

**Comment by StephaneDelcroix** [comment] 2022-06-20 08:13
You need a strong code reference from the consuming app to your lib, like `MauiLib.Init()` (even if Init() is a no-op). 

Make sure you document this to the consumers of your lib.

We're working on lifting that requirement, but it takes some work

Duplicate of #7503

**Comment by StephaneDelcroix** [comment] 2022-06-20 08:14
Duplicate of #7503

**Closed by StephaneDelcroix** 2022-06-20 08:13 UTC
Labels: t/bug, s/needs-verification
