### ISSUE TITLE
[Bug] iOS Border with RoundedRectangle StrokeShape doesn't clip content

### ISSUE THREAD

**Issue by InquisitorJax** [dotnet/maui#12414] opened 2023-01-04 21:33 UTC
### Description

The iOS Border control isn't clipping the contents when specifying a Rounded Border
iOS
![image](https://user-images.githubusercontent.com/1822976/210653048-a8f436aa-bb88-496e-8ef0-1f1401b40024.png)

Android
![image](https://user-images.githubusercontent.com/1822976/210650840-fe359e59-a5f6-4bf9-9b3c-4117a57cf1da.png)

### Steps to Reproduce

1. Create File | New MAUI app
2. add the following XAML to the main page
3. `
			<Border Padding="0"
			        HeightRequest="60"
			        StrokeShape="RoundRectangle 30"
			        WidthRequest="60">
				<Grid BackgroundColor="Red" />
			</Border>`

using a Frame with CornerRadius instead of Border seems to have the same bug :(

Sample code can be found on MainPage.xaml of linked repo

### Link to public reproduction project repository

https://github.com/InquisitorJax/MAUI-Controls

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

tested iOS 14 - 16

### Did you find any workaround?

nope

**Comment by rachelkang** [comment] 2023-01-05 19:16
Duplicate of #10724

**Closed by rachelkang** 2023-01-05 19:16 UTC
Labels: t/bug
