### ISSUE TITLE
Collectionview with entry box flickering on data entry and keyboard closure shows the last page 

### ISSUE THREAD

**Issue by liveinvarun** [dotnet/maui#13871] opened 2023-03-13 13:55 UTC
### Description

When we have a entry inside a collection view and the last item that is shown in screen  has the focus - after keyboard opens up the input field entry makes collectionview continously up down -kind of flickering on the control.
This happens especially in android and if we do multiple attempts then the collection view and the page height is reduced and the keyboard when hidden shows the back or previous view. Similar kind of issue has been reported on android and was closed now this is new issue which effects the collectionview to fial completely.

### Steps to Reproduce

In the main page navigation to the dummy view has been made using a button 
the navigation 

https://github.com/liveinvarun/MauiRepo

https://user-images.githubusercontent.com/8180770/224722290-ab3f8f4d-828c-40fb-a072-82b29bf2838a.mov

### Link to public reproduction project repository

https://github.com/liveinvarun/MauiRepo

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11 and up

### Did you find any workaround?

No workaround as there are some issue which were reported earlier and closed. This particualarly happen when the we use ModalPage and the navigationpage doesnt have this issue.

https://github.com/dotnet/maui/issues/10978
this issue was previously reported.

**Comment by PureWeen** [comment] 2023-03-13 16:19
![2023-03-13_11-17-49](https://user-images.githubusercontent.com/5375137/224762408-f9e4566a-8b5e-423a-a203-cb54c07ef72f.gif)

This should be resolved by the next SR

I have a workaround [here](https://github.com/PureWeen/ShanedlerSamples) if you want to try that for now. 

https://github.com/PureWeen/ShanedlerSamples/blob/main/ShanedlerSamples/Library/Common/NotifyingContentViewGroup.Android.cs

**Closed by PureWeen** 2023-03-13 16:19 UTC
Labels: t/bug, platform/android 🤖, area/collectionview 📃, area/controls 🎮, keyboard

**Comment by liveinvarun** [comment] 2023-03-13 17:42
@PureWeen  Thanks for the reply that solves the issue.
Any idea when will this be part of build - expected release date?

**Comment by samhouts** [comment] 2023-05-12 19:40
Duplicate of #10978
