### ISSUE TITLE
Run Maui MSI on window server 2019 not working

### ISSUE THREAD

**Issue by danies8** [dotnet/maui#14482] opened 2023-04-09 08:50 UTC
### Description

I deployed Maui app as shown in https://docs.microsoft.com/en-us/dotnet/maui/windows/deployment/overview
Run this on new server 2019 with Desktop Experience installed in it.
and is not working.

### Steps to Reproduce

Steps to Reproduce
Publish Maui app.
Run on server 2019
Nothing happened.

### Link to public reproduction project repository

..

### Version with bug

6.0.312

### Last version that worked well

6.0.312

### Affected platforms

Windows

### Affected platform versions

...

### Did you find any workaround?

No

### Relevant log output

```shell
No
```

**Comment by jfversluis** [comment] 2023-04-11 09:21
Duplicate of #8830

**Closed by jfversluis** 2023-04-11 09:21 UTC
Labels: t/bug, area/setup 🪄
