### ISSUE TITLE
[Crash] [iOS] - Opening search in WebView in iOS crashes app

### ISSUE THREAD

**Issue by Take-A-Byte** [dotnet/maui#22426] opened 2024-05-15 12:58 UTC
### Description

I have created a [simple MAUI app](https://github.com/Take-A-Byte/MAUIWebViewCrash/blob/main/ReadMe.md) to reproduce the crash.

# Environment

- It can be a MAUI app or MAUI Hybrid app
- Run the app on iOS 17.4 (I used a simulator)

# Steps to create the app

1. Create a standard MAUI app in VS Code
2. Delete the content of MainPage.xaml
3. Add WebView to the MainPage with a source (e.g. https://learn.microsoft.com/en-us/dotnet/maui/user-interface/controls/blazorwebview?view=net-maui-8.0)

# Behavior

- **Expected** - Search box opens
- **Actual** - App crashes

# Note

- The app works fine on older iOS Simulator.
- If you want you can replace the website with any other website with search functionality and still the app crashes.
- I tried creating a native iOS app in XCode with `WKWebView` as well as `UIWebView` and everything works fine.

### Steps to Reproduce

# Creating new app

- Create a MAUI app with WebView or Hybrid MAUI app with WebView
- Source website should contain a search button that opens up search box
- Run app on iOS/iPad Simulator **17.4**
- Click on search button

# Using the sample app

- Run app on iOS/iPad Simulator **17.4**
- Click on search button

### Link to public reproduction project repository

https://github.com/Take-A-Byte/MAUIWebViewCrash/blob/main/ReadMe.md

### Version with bug

8.0.7 SR2

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 17.4

**Comment by PureWeen** [comment] 2024-05-15 16:30
Duplicate of #21057

**Closed by PureWeen** 2024-05-15 16:30 UTC
Labels: t/bug, area-controls-webview
