### ISSUE TITLE
Entry ReturnType Prop

### ISSUE THREAD

**Issue by Kremed** [dotnet/maui#5321] opened 2022-03-15 22:27 UTC
### Description

**When you use the ReturnType property and set the value to "Done Or Next" nothing happens for the keyboard
This happens on Android, I haven't tried it on IOS and WinUi**

### Steps to Reproduce

1.Create a New .Net MAUI App
2. Add Entry   `<Entry ReturnType="Done" />` Or  `<Entry ReturnType="Next" />`
3. The value of the ReturnType you have already specified will appear in the lower part of the keyboard
4. Once you press the button to go to the next Entry Control, nothing happens at all

### Version with bug

Preview 13 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 10 API 29

**Comment by Amir-Care** [comment] 2022-03-16 02:03
Verified repro with Version 17.2.0 Preview 2.0 [32208.484.main].
Sample project: [#5321.zip](https://github.com/dotnet/maui/files/8258354/5321.zip)

**Comment by HobDev** [comment] 2022-03-16 04:30
Duplicate of #3380 and #4781

**Closed** 2022-03-16 04:57 UTC
Labels: t/bug, s/verified
