### ISSUE TITLE
[MAUI] Recipe splash screen logo missing on iOS

### ISSUE THREAD

**Issue by jaosnz-rep** [dotnet/maui#17925] opened 2023-10-10 09:22 UTC
### Description

Recipe splash screen logo missing

### Steps to Reproduce

1.Deploy https://github.com/rachelkang/recipeSearch to iOS simulator or device.
2.Validate the launch screen

Expected results:
![image](https://github.com/dotnet/maui/assets/82628041/83175c76-47a7-45f7-b88c-f8d03929a742)

Actual result:
Recipe splash screen logo missing
![image](https://github.com/dotnet/maui/assets/82628041/d93c64a9-65d2-4af5-8a0a-bb47a54e57c2)

### Link to public reproduction project repository

https://github.com/rachelkang/recipeSearch

### Version with bug

Microsoft.Maui.Controls 8.0.0-nightly.9331+sha.6aac924e89-azdo.8456294
.NET SDK: 8.0.100-rc.1.23463.5

### Is this a regression from previous behavior?

Not a regression, The issue also repro on 8.0.0-rc.1.9171

### Affected platforms

iOS

**Comment by jaosnz-rep** [comment] 2023-10-10 09:24
Note: The issue of simulator showing black splash screen can be solved through the following workaround, reference https://github.com/xamarin/xamarin-macios/issues/18469
Add the following to the csproj:

```
<PropertyGroup>
    <EnableCodeSigning>true</EnableCodeSigning>
    <CodesignRequireProvisioningProfile>true</CodesignRequireProvisioningProfile>
    <DisableCodesignVerification>true</DisableCodesignVerification>
</PropertyGroup>
```

**Comment by mattleibow** [comment] 2023-10-11 14:39
Duplicate of https://github.com/xamarin/xamarin-macios/issues/18469

**Closed** 2023-10-11 14:44 UTC
Labels: t/bug, platform/iOS 🍎, csi-new
