### ISSUE TITLE
Mouse gets ignored after writing into a contenteditable element (MAUI Blazor)

### ISSUE THREAD

**Issue by dady8889** [dotnet/maui#12589] opened 2023-01-12 00:47 UTC
### Description

Moving the mouse at the same time as writing into a `contenteditable` element (such as div) causes all subsequent mouse events to get ignored (click, hover, ...).

(Moved from https://github.com/MicrosoftEdge/WebView2Feedback/issues/3118)

### Steps to Reproduce

- Create a new MAUI Blazor project for .NET 7
- Add the following code into any page
```razor
<div style="border: 1px solid black;" contenteditable="true">
    @text
</div>

<hr />

<button style="height: 2rem; width: 100%">Click Me</button>

@code {
    string text = "write something here and move mouse at the same time";
}
```
- Try writing into the editable text area and moving the mouse at the exact same time
- After finishing writing, try clicking on the button

Expected behaviour:
- Button is successfully clicked

Actual behaviour:
- It is not possible to click anything on the webpage

### Link to public reproduction project repository

https://github.com/dady8889/MauiBlazorContenteditBug

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Windows SDK 10.0.19041.0

**Comment by javiercn** [comment] 2023-01-12 15:31
@dady8889 thanks for contacting us.

Does this happen on a regular WebView without Blazor being involved?

**Comment by dady8889** [comment] 2023-01-12 18:22
> @dady8889 thanks for contacting us.
> 
> Does this happen on a regular WebView without Blazor being involved?

Yes. I have edited the repro as follows:
```xaml
<!--
    <BlazorWebView x:Name="blazorWebView" HostPage="wwwroot/index.html">
        <BlazorWebView.RootComponents>
            <RootComponent Selector="#app" ComponentType="{x:Type local:Main}" />
        </BlazorWebView.RootComponents>
    </BlazorWebView>-->

    <WebView>
        <WebView.Source>
            <HtmlWebViewSource>
                <HtmlWebViewSource.Html>
                    <![CDATA[
                <HTML>
                <BODY>
                <H1>.NET MAUI</H1>
                <P>Welcome to WebView.</P>
                    
                    <div style="border: 1px solid black;" contenteditable="true">
                    write something here and move mouse at the same time
                    </div>
                    <hr />

                    <button style="height: 2rem; width: 100%">Click Me</button>
                </BODY>
                </HTML>
                ]]>
                </HtmlWebViewSource.Html>
            </HtmlWebViewSource>
        </WebView.Source>
    </WebView>
```

**Comment by dady8889** [comment] 2023-01-12 18:54
I tested it on another Windows 11 PC with the same version of SDK and it doesn't work there too. I also noticed that it's happening to normal text inputs, not only contenteditable elements.

**Comment by mkArtakMSFT** [comment] 2023-01-17 17:42
@Eilon this seems to be either a webview or a browser itself. Can you please check and route as necessary? Thanks!

**Comment by Eilon** [comment] 2023-01-23 19:21
Indeed, this is a duplicate of https://github.com/MicrosoftEdge/WebView2Feedback/issues/3003.

**Closed by Eilon** 2023-01-23 19:21 UTC
Labels: t/bug, area/blazor 🕸️, s/needs-attention
