### ISSUE TITLE
Close, minimize, and maximize don't work

### ISSUE THREAD

**Issue by hamedhajiloo** [dotnet/maui#10089] opened 2022-09-13 09:27 UTC
### Description

I try to close, minimize and maximize my project window but it won't happen!
I tested this problem with my project and with the first simple MAUI app template, as well as with the [WeatherTwentyOne ](https://github.com/dotnet/maui-samples/tree/main/6.0/Apps/WeatherTwentyOne) project.

![image](https://user-images.githubusercontent.com/45947371/189851030-a03132f9-5c21-4b7d-8f6b-c9d48df75aac.png)

### Steps to Reproduce

1. Create a new Blazor.Maui project.
2. Run the project on Windows
3. Try to close the window.

What happened?

### Link to public reproduction project repository

https://github.com/dotnet/maui-samples/tree/main/6.0/Apps/WeatherTwentyOne

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 11. 21H2

**Comment by hamedhajiloo** [comment] 2022-09-14 18:36
> @hamedhajiloo are you setting the FlowDirection to a `RightLeft` in your app? or are you using an RTL language for your system language? There's currently a bug with WinUI and the RTL behavior.
> 
> if you hover the mouse over the top left corner of the window to those buttons highlight?

Yes my system is RTL

**Comment by hartez** [comment] 2022-09-15 18:55
Duplicate of #7751

**Comment by hartez** [comment] 2022-09-15 18:55
Duplicate of #7751

**Closed by hartez** 2022-09-15 18:55 UTC
Labels: t/bug, platform/windows 🪟, area/desktop 🖥️, s/needs-attention
