### ISSUE TITLE
Issue with .NET MAUI Microsoft.Maui.Controls 9.0 Update. Error (CS0246)

### ISSUE THREAD

**Issue by tecomunico** [dotnet/maui#25835] opened 2024-11-13 15:40 UTC
### Description

Hi everyone,

I am experiencing an issue after updating Microsoft.Extensions.Logging.Debug, Microsoft.Maui.Controls, Microsoft.Maui.Controls.Compatibility, etc., from version 8.0.93 to 9.0. The error specifically appears in the AppDelegate class for iOS. The line causing the problem is:

`public class AppDelegate : MauiUIApplicationDelegate`

The error message I am receiving is:

`Platforms/iOS/AppDelegate.cs(28,28): Error CS0246: The type or namespace name 'MauiUIApplicationDelegate' could not be found (are you missing a using directive or an assembly reference?) (CS0246)`

I have tried troubleshooting this issue on different machines, but the problem persists across all of them. I even created a completely new MAUI project, and the error still appears immediately after updating to version 9.0. It seems like the update is causing this problem, and I cannot proceed with iOS builds because of it.

Has anyone found a solution or workaround for this? Any help would be greatly appreciated, as this is really blocking our progress.

Thanks in advance!

### Version with bug

9.0.0 GA

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.100 SR10

### Affected platforms

iOS

### Affected platform versions

iOS 15 Pro Max 17.0 Visual Studio for Mac 17.6.14 (build 413)

### Relevant log output

```shell

```

**Comment by dzebas** [comment] 2024-11-14 01:16
I've similar issue, but different errors:

Error CS0234 : The type or namespace name 'Compatibility' does not exist in the namespace 'Microsoft.Maui.Controls.Handlers' (are you missing an assembly reference?)

Error CS0234 : The type or namespace name 'iOS' does not exist in the namespace 'Microsoft.Maui.Controls.Compatibility.Platform' (are you missing an assembly reference?)

Reverting Maui controls back to 8.0.93 fixes the issue. 

Is there a workaround?

**Comment by Zhanglirong-Winnie** [comment] 2024-11-14 04:55
Hi, @tecomunico 
Microsoft.Maui.Controls and Microsoft.Maui.Controls.Compatibility rely on the .NET 9 SDK. You need to install the .NET 9 SDK and the corresponding .NET 9 MAUI Workload on your machine.
[Download .NET 9.0 (Linux, macOS, and Windows) (microsoft.com)](https://dotnet.microsoft.com/en-us/download/dotnet/9.0).
Please try to see if this solves your problem and give us feedback. We look forward to your reply.

**Comment by Barry-Theunissen** [comment] 2024-11-16 05:46
It does NOT solve the problem!!!  TEST TEST TEST Microsoft, before you release something, FFS!

**Comment by Barry-Theunissen** [comment] 2024-11-16 05:54
It does NOT solve the problem. TEST TEST TEST Microsoft, before you release something!!  FFS...again and again this sort of sh_t happens!

**Comment by tecomunico** [comment] 2024-11-16 12:33
Complete Waste

**Comment by jfversluis** [comment] 2024-11-18 11:53
Could you please provide the output for `dotnet --info` and `dotnet workload list`?

I did see this error myself too and it happens because something is not aligned. You need to indeed have the .NET 9 SDK GA version. Make sure to run `dotnet workload restore` to install the matching workload for it and then make sure that you're building your .NET MAUI app against .NET 9 by updating the target frameworks in your project and updating any global.json file you might have.

For reference, here are mine:

`dotnet --info`

![Image](https://github.com/user-attachments/assets/68d36040-0ee5-4ae4-81fb-4b3e89b8584e)

`dotnet workload list`

![Image](https://github.com/user-attachments/assets/4f156990-cd2d-4051-acf0-5de107e1117f)

Then using version 9.0.10 of the NuGet package works fine for me!

@Barry-Theunissen I understand your frustration, but your comment is not super helpful or nice. Try to keep it constructive and moving forward. Thanks!

**Comment by Barry-Theunissen** [comment] 2024-11-18 14:30
Here is my output from your questions - it does not work for me : 

![Image](https://github.com/user-attachments/assets/a8c76bd6-7f1a-4d10-8fde-49041b3fbfc0)
![Image](https://github.com/user-attachments/assets/d7f99ea2-6d25-48e7-b072-da14a9697013)

I am keep it ..."constructive" Jerald!  You say you "understand" my frustration and that of others...and then you basically tell me to "wind my neck in". Makes no sense, my friend...apologies if you are offended, but it makes no sense when the actual offence is precious time wasted by Microsoft of developers like me....because of MS lack of testing....

Furthermore, I have now been waiting literally months, for a proper answer to an email I previously for from you around UX testing in MAUI and Appium...no proper and decent documentation with examples...is that ever going to happen at all Jerald, or does MS consider that something "too irrelevant" to them?

**Comment by mattleibow** [comment] 2024-11-18 17:24
Did you also update the TFMs? The .NET 9 NuGet packages only work on net9.0-* TFMs. I have seen a few issues recently on this where the new nugets stopped working but most folks just forgot that the TFMs need to update as well.

**Comment by Barry-Theunissen** [comment] 2024-11-19 15:49
Updating of the TFMs in the .csproj files worked....would have been helpful if this was clearly explained or done automatically when upgrading VS to latest and updating the NuGets to latest...all working now....seems .NET 9 has made an Android MAUI app somewhat faster now too...or is this just my imagination? Problem solved, once the TFMs were updated in the .csproj files...can close the ticket now I reckon - thanks for the suggestion of updating the TFMs as well @mattleibow !

**Comment by mattleibow** [comment] 2024-11-20 12:57
@Barry-Theunissen thanks for that feedback! We will get right on that! In fact, I am working on that now!

**Comment by mattleibow** [comment] 2024-11-20 12:57
Duplicate of https://github.com/dotnet/maui/issues/25970

**Closed by mattleibow** 2024-11-20 12:57 UTC
Labels: platform/iOS 🍎, area-setup, s/needs-attention, potential-regression

**Comment by Barry-Theunissen** [comment] 2024-11-20 15:01
@mattleibow thank you ever so much for your attention to this matter...it is now just the remaining issue of not being able to rebuild and deploy more than once to Android on .NET 9 because the locks are not released on the files by MSBuild...you have to restart VS each time or destroy the previous MSBuild processes each time before a new build and deploy to the Android emulator. Interestingly, this is not a problem when deploying to a physical Android device though - if that helps!

**Comment by mattleibow** [comment] 2024-11-21 07:01
@Barry-Theunissen can you create a new issue for that and say which files are locked?

We may have to get the android track to have a look.

**Comment by Barry-Theunissen** [comment] 2024-11-21 07:13
They already looking at it : https://github.com/dotnet/android/pull/9531#pullrequestreview-2448027411

**Comment by mattleibow** [comment] 2024-11-21 07:53
Great, I see it was approved too!

**Comment by Barry-Theunissen** [comment] 2024-11-21 09:26
Well I think it had to be...currently, with that situation...every MAUI app developer with .NET 9 has been seriously retarded and disabled...almost to the mount where .NET 9 is an absolute "no go"!
