### ISSUE TITLE
Not all controls responding to UserAppTheme Dark

### ISSUE THREAD

**Issue by rogerbriggen** [dotnet/maui#6932] opened 2022-05-08 08:35 UTC
### Description

On Windows and Android (ios I did not test) the background color of ContentPages is set when the first time accessed, after that it is not updated anymore even if you change the style. Other items do change the style like Switch or Button

before opened page (background still light, font changed)
![only text color changed_not_background](https://user-images.githubusercontent.com/46163208/167288254-0885012f-b380-4eb1-b403-a1e53b0b2c73.png)

newer before opened page (both changed). Also see the tabbar not working correctly (text color wrong)
![NewPage_both_changed](https://user-images.githubusercontent.com/46163208/167288258-9b7a7589-28ce-4615-a694-f3ef7674e525.png)

### Steps to Reproduce

1. Get project from https://github.com/rogerbriggen/Maui_sHell/tree/ShellErrors_RC2 or use the attached file 
[Maui_sHell-ShellErrors_RC2.zip](https://github.com/dotnet/maui/files/8646626/Maui_sHell-ShellErrors_RC2.zip)

2. Compile and run for windows
3. Start up the project and open dummy 1 (but not other pages)
4. Go back to the main page and change to dark mode
5. Notice that the main page did not change its background color but the Switch and Button did
6. Open dummy 2 -> Background is dark
7. Open dummy 1 -> Backround is still light but text changed it color

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, Android

### Affected platform versions

Windows 10 21H1

### Did you find any workaround?

No

**Comment by XamlTest** [comment] 2022-05-09 02:18
Verified this issue with Visual Studio Enterprise 17.3.0 Preview 1.0 [32427.455.main]. Repro on Windows and Android with above project.

**Comment by Redth** [comment] 2022-05-09 14:10
@mattleibow is this fixed by the recent background PR(s)?

**Comment by shimingsg** [comment] 2022-05-10 06:47
I just verified with VS 17.3.0 Preview 2.0 [32509.430.main], 

1. Start up the project and open dummy 1 (but not other pages)
2. Go back to the main page and change to dark mode
3. Notice that the main page did not change its background color but the Switch and Button did
**the backgroud color of switch is not right, when mouse point moved away, the background color gets back to the color when LightTheme.**
4. Open dummy 2 -> Background is dark 
**Yes**
5. Open dummy 1 -> Backround is still light but text changed it color
**the selected tab font color is changed**
![image](https://user-images.githubusercontent.com/20982341/167565113-ef342f76-72b5-41d6-b33c-c3662b526346.png)

you could refer to this gif:
![6932](https://user-images.githubusercontent.com/20982341/167565201-8469bdd8-8bd7-48ca-8499-eea66d4a349b.gif)

**Comment by samhouts** [comment] 2022-05-12 00:59
Yep, I see the same thing as @shimingsg  on 6.0.300-rc.4.5760. BackgroundColor is changing fine, but not all controls are responding. This is not actually the ContentPage BackgroundColor being changed but the UserAppTheme being changed.

**Comment by samhouts** [comment] 2022-05-12 01:07
Duplicate of #6596

**Closed by samhouts** 2022-05-12 01:07 UTC
Labels: t/bug, area/controls 🎮, s/verified, s/triaged
