### ISSUE TITLE
UnFocus does not work on Entries inside CollectionView.

### ISSUE THREAD

**Issue by pulmuone** [dotnet/maui#19032] opened 2023-11-26 04:59 UTC
### Description

UnFocus does not work on Entries inside CollectionView.

https://github.com/dotnet/maui/assets/42885949/fa376c81-9470-49b2-b500-4e6ee9816daa

### Link to public reproduction project repository

https://github.com/pulmuone/BarcodeScanner4Maui3

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI, Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Android

**Comment by PureWeen** [comment] 2023-11-27 15:44
Duplicate of https://github.com/dotnet/maui/issues/11881

https://github.com/dotnet/maui/issues/18854#issuecomment-1817143651

**Closed by PureWeen** 2023-11-27 15:44 UTC
Labels: t/bug, platform/android 🤖, area/collectionview 📃, control-entry

**Comment by pulmuone** [comment] 2023-11-27 23:33
> Duplicate of #11881
> 
> [#18854 (comment)](https://github.com/dotnet/maui/issues/18854#issuecomment-1817143651)

There was no problem in Xamarin, but this bug only occurs in Maui.

**Comment by samhouts** [comment] 2024-05-17 01:17
Duplicate of #11881
