### ISSUE TITLE
[Android] Runtime Property Update is not working for InputTransparent

### ISSUE THREAD

**Issue by bhuvan94** [dotnet/maui#7682] opened 2022-06-02 07:46 UTC
### Description

In Android, When updating the Layout InputTransparent property at runtime it is not working.

### Steps to Reproduce

1. Run the attached sample . [MauiApp7.zip](https://github.com/dotnet/maui/files/8821748/MauiApp7.zip)
2. Click Update InputTransparent button. 
3. Now click entry or button, you can able to click it

### Version with bug

6.0 (current)

### Last version that worked well

Release Candidate 3 (current)

### Affected platforms

Android

### Affected platform versions

Android 11

### Did you find any workaround?

None

**Comment by kristinx0211** [comment] 2022-06-09 09:53
verified repro on android, when ` InputTransparent=true` , it still allows the user to give input.

**Comment by hartez** [comment] 2022-06-09 16:40
Sounds like this might be the same issue as #7948.

**Comment by samhouts** [comment] 2022-08-31 17:02
Duplicate of #9069

**Closed by samhouts** 2022-08-31 17:02 UTC
Labels: t/bug, area/layout 🔲, s/verified
