### ISSUE TITLE
Cannot deploy windows when referencing net6 and ApplicationDisplayVersion < 1.0

### ISSUE THREAD

**Issue by janduldhardt** [dotnet/maui#10953] opened 2022-10-27 07:38 UTC
### Description

When targeting net6.0 in the MAUI project and setting ApplicationDisplayVersion less than 1.0 then then deployment for Windows is not working and throws the error:

> Severity	Code	Description	Project	File	Line	Suppression State
Error	NETSDK1005	Assets file 'C:\Users\JanDu\source\repos\BugSample\BugSample\obj\project.assets.json' doesn't have a target for 'net6.0-windows10.0.19041.0'. Ensure that restore has run and that you have included 'net6.0-windows10.0.19041.0' in the TargetFrameworks for your project.	BugSample	C:\Program Files\dotnet\sdk\6.0.402\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets	267	

At the same time if we do not reference net6.0 then it works (only referencing ios, android, windows) but then unit testing is not possible.

Here is a video:
Just if I change the version to 0.1 from 1.0 the solution doesn't build anymore and restoring nuget packages fails.

https://gifyu.com/image/SEsbg

My whole team encounters this issue, both with Visual Studio 2022 and Preview.

### Steps to Reproduce

1. Create new Maui project
2. Add targetFramework net6.0
3. Set ApplicationDisplayVersion to 0.1
4. Run

### Link to public reproduction project repository

https://github.com/janduldhardt/issue-1425176615

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

windows10.0.19041.0

### Did you find any workaround?

Set version to 1.0 and above

### Relevant log output

```shell
NETSDK1005	Assets file 'C:\Users\JanDu\source\repos\BugSample\BugSample\obj\project.assets.json' doesn't have a target for 'net6.0-windows10.0.19041.0'. Ensure that restore has run and that you have included 'net6.0-windows10.0.19041.0' in the TargetFrameworks for your project.	BugSample	C:\Program Files\dotnet\sdk\6.0.402\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets	267
```

**Comment by jfversluis** [comment] 2022-10-27 11:01
I'm not sure if the `ApplicationDisplayVersion` matter much in this case. It seems that the refences simply haven't restored yet as indicated by the error message. 

Could you try right clicking on your solution node and choose "Restore NuGet Packages", wait for that to complete and then try again?

Else, please add a reproduction project as requested. I have just tried to reproduce here locally and it works fine for me.

**Comment by janduldhardt** [comment] 2022-10-28 09:29
@jfversluis I added a sample repository + a video that shows the problem.
When v1.0 dotnet restore and restoring nugets works perfectly fine. If I then set the version to 0.1 and rebuild the project it stops working. 
I could reproduce your case, that if I restore the nugets with v1.0 and then just change to v0.1 then I can also start the application but as soon as any kind of restoring happens it fails.

**Comment by Jinjinov** [comment] 2023-01-14 17:58
If I set `ApplicationDisplayVersion` to `1.0.1` and delete `bin` and `obj` folders it fails with 
```
Error	NETSDK1005	Assets file '\obj\project.assets.json' doesn't have a target for 'net7.0-windows10.0.19041.0'. 
Ensure that restore has run and that you have included 'net7.0-windows10.0.19041.0' in the TargetFrameworks for your project.	
C:\Program Files\dotnet\sdk\7.0.102\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets	267	
```
If I delete `bin` and `obj` folders again and set `ApplicationDisplayVersion` back to `1.0` it works again.

**Comment by juanmalm** [comment] 2023-03-27 07:56
Same issue here

**Comment by homeyf** [comment] 2023-05-30 06:57
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 1.0. Can repro on windows platform with above project.
https://github.com/janduldhardt/issue-1425176615
![image](https://github.com/dotnet/maui/assets/82450723/abd3dedb-5abd-4604-9874-c3dfe2ed03d2)
![image](https://github.com/dotnet/maui/assets/82450723/08bc5cd3-1627-4528-ade8-47b048fb493e)

**Comment by toniReady** [comment] 2023-09-23 10:22
Same problem here, MAUI blazor net7.

When publish win app, no problem con android publish.

**Comment by jfversluis** [comment] 2024-10-02 07:58
Can't reproduce anymore with .NET 8 latest stable version. Closing this one, thanks everyone!

**Closed by jfversluis** 2024-10-02 07:58 UTC
Labels: t/bug, area-single-project, platform/windows 🪟, s/verified, s/triaged, s/needs-attention
