### ISSUE TITLE
Missing icon [Bug] 

### ISSUE THREAD

**Issue by jirisykora83** [dotnet/maui#1803] opened 2021-07-25 08:25 UTC
### Description

Android app missing icon.

### Steps to Reproduce

1. Create default project for MAUI Blazor (I believe same apply to just MAUI project)
2. Deploy to emulator

### Basic Information

- Version with issue: 6 preview
- IDE:
- Platform Target Frameworks: 
  - Android: Emulator API 28

### Screenshots

![image](https://user-images.githubusercontent.com/7279825/126892724-b9214170-9bde-452e-8924-9be29a67e01b.png)

**Comment by jirisykora83** [comment] 2021-07-26 09:25
Also try David Weather App https://github.com/davidortinau/WeatherTwentyOne with same result.

![image](https://user-images.githubusercontent.com/7279825/126966234-6da6f92d-8755-434e-89da-f0934b95bdc1.png)

**Comment by jsuarezruiz** [comment] 2021-11-05 10:57
Tried with Preview 11 and the icons appear. Could you try it?. I am going to close the issue, but feel free to let me know if find anything and we can reopen it. Thanks for the feedback!

**Closed by jsuarezruiz** 2021-11-05 10:57 UTC
Labels: t/bug, platform/android 🤖

**Comment by mattleibow** [comment] 2024-06-26 16:36
Duplicate of https://github.com/dotnet/maui/issues/23178
