### ISSUE TITLE
Changing ImageSource in MAUI app causes flicker on Windows

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#6962] opened 2022-05-09 18:15 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Changing-ImageSource-in-MAUI-app-causes-/10022074)._

---
[severity:It's more difficult to complete my work]
When changing the ImageSource property of an Image in a MAUI app the image should seamlessly change to the new image. In the Android version of the app this occurs as expected. In the Windows version the image flashes or flickers as though the old image is disappearing before the new image appears. I.e. it is as though the rectangle is being repainted twice, once with no image and then with the new image immediately after, whereas on Android the rectangle is simply repainted once with the new image.

I've attached screen capture videos of this occurring in the release version of an app published to Windows and to an Android emulator.

This was produced by taking the default MAUI app project and making the following changes:

1. To MainPage.xaml add the following to the Image view:
                    x:Name="imageContent"

2. In MainPage.xaml.cs change the OnCounterClicked handler to:

```
        private void OnCounterClicked(object sender, EventArgs e)
        {
            count++;
            CounterLabel.Text = $"Current count: {count}";

            SemanticScreenReader.Announce(CounterLabel.Text);

            if(count % 2 == 0)
            {
                imageContent.Source = "dotnet_bot.png";
            }
            else
            {
                imageContent.Source = "dotnet_bot_reddot.png";
            }
        }

```

3. Slightly alter the original dotnet_bot.svg image (I added a red dot) and save it as an image resource called dotnet_bot_reddot.svg.

Run it and you should see the flicker as shown in the video unless it is a peculiarity to my hardware (though I have tested it on another machine with the same results). 

The app I'm currently working on involves a considerable amount of image switching and this makes the Windows version look pretty terrible. While the Windows version of the app will be a small portion of the target audience it will not be insignificant and, in addition, it is far easier to test new code in the windows app rather than repeatedly deploying to emulators and this problem makes that very difficult, particularly when dealing with graphic manipulation code.

---
#### Feedback Bot on 4/24/2022, 05:29 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by kristinx0211** [comment] 2022-05-17 09:25
@Stephen Martin, I don't repro this issue, I create a circle as an image resource called dotnet_bot_reddot.svg. you_ can see my repro project, let me know if I miss something.
[MauiApp16.zip](https://github.com/dotnet/maui/files/8707017/MauiApp16.zip)
https://user-images.githubusercontent.com/99457000/168777784-3f2bad9d-0f12-47fc-877d-50ea23ba4054.mp4

**Comment by LordBenjamin** [comment] 2022-05-19 16:49
I can reproduce by using a pair of 3840x2160 bitmap images rather than the dotnet bot. Because the image data is not loaded until `Image.Source` is set (I assume, given it's backed by a `Func<Stream>`, there is a flicker while the image is loaded that becomes more pronounced as the image size increases.

In my particular case, I am trying to render the content of a Windows `SoftwareBitmapSource` from a webcam, which unfortunately seems to require encoding a bitmap and then loading via `ImageSource.FromStream()` - there is noticeable delay between displaying each frame.

Either the `Image` element should continue to display the old image until the new image has been fully loaded, or there needs to be a way to "preload" an `ImageSource` so that we can ensure the data has been loaded before swapping `Image.Source` to the next frame.

**Comment by smartin-asprosys** [comment] 2022-05-24 16:09
@kristinx0211 I tried your repro project and I still see the flicker as the images change. In this case though it is much harder to notice. I suspect that is due to the images being very different, I imagine that when the images are very similar as in my sample the brain tries to stitch them into a continuous motion which makes the flicker more obvious whereas when they are very different your brain considers them distinct images and the transition is, at least partially, ignored.  

It's interesting that if you slow down the video you uploaded, to one quarter speed, the first couple of times you switch to the dotnet_bot image the screen does go blank before it shows the image but the switch the other way doesn't seem to show any flicker. Then after a few clicks the flicker seems to disappear as though there is some caching going on.

This was tested, as was my own sample, on a laptop with Intel 530 graphics and on one with Intel 630 graphics. Neither are great shakes in the processing department but they are very common still. I asked my designer to test my sample on a much higher end setup and she couldn't see any flicker at first but when the room she was in was darkened it was very slightly visible. Then when she switched out the images for much larger ones it progressively became more visible. This seems to support @LordBenjamin's experience that it is caused somewhere in the loading and initial processing of the image. It becomes more visible as the image is increased in size or as the graphics capabilities of the machine are reduced.

At the moment I have gotten around this problem by loading multiple Images and switching them out by switching their IsVisible property values. The switch is seamless with no flicker with any image I've tried. In @LordBenjamin's  case this might also work: rather than switching ImageSources they can cycle through a stack of Images using their ZIndex or IsVisible properties while switching the ImageSource of the hidden one (or the one at the end of the stack) thereby pre-loading its image before it is made visible.

**Comment by smartin-asprosys** [comment] 2022-05-25 14:06
@kristinx0211 If you step through your video, frame by frame, for the first few clicks you'll notice that in the frame immediately after the click, the caption for number of clicks is updated and the image is blank. But in the second frame after the click the new image has been added. This only lasts a few clicks and from then on the new image is updated in the same frame as the caption. This is what causes the flicker.

In my video of the same phenomenon in a windows app the one frame delay between the erasure of the old image and the painting of the new image is pretty consistent all the way through. Since I am switching images that are almost identical the white flash is quite evident.

**Comment by mattleibow** [comment] 2022-05-25 17:10
This should be fixed by https://github.com/dotnet/maui/pull/7348

**Closed** 2022-05-25 17:11 UTC
Labels: t/bug, platform/windows 🪟, area/image :framed_picture:, s/verified
