### ISSUE TITLE
ApplicationVersion parameter to dotnet build no longer works

### ISSUE THREAD

**Issue by ckrutsinger** [dotnet/maui#14524] opened 2023-04-12 01:49 UTC
### Description

`dotnet build -f net7.0-android --configuration Release -v normal --output D:\a\1\a -p:ApplicationVersion=163 -p:ApplicationDisplayVersion=1.0.163 
`
The resulting AAB file has version 1 and display version 1.0 (which is what is in the csproj file), so the command parameters were not used.

This occurred in our Azure pipeline `DotNetCoreCLI@2`task.

```
2023-04-12T00:42:51.7415393Z ==============================================================================
2023-04-12T00:42:51.7415540Z Task         : .NET Core
2023-04-12T00:42:51.7415620Z Description  : Build, test, package, or publish a dotnet application, or run a custom dotnet command
2023-04-12T00:42:51.7415748Z Version      : 2.217.0
2023-04-12T00:42:51.7415811Z Author       : Microsoft Corporation
2023-04-12T00:42:51.7415884Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/build/dotnet-core-cli
2023-04-12T00:42:51.7415996Z ==============================================================================
```

### Steps to Reproduce

1. Create a new Maui app.
2. In the csproj you should have the default `<ApplicationDisplayVersion>1.0</ApplicationDisplayVersion><ApplicationVersion>1</ApplicationVersion>` values
3. From command line, `dotnet build -f net7.0-android --configuration Release -v normal --output <some file path> -p:ApplicationVersion=163 -p:ApplicationDisplayVersion=1.0.163`

Resulting AAB file will use the 1 and 1.0 values instead of the 'p:ApplicationVersion=163 -p:ApplicationDisplayVersion=1.0.163' parameter values.

### Link to public reproduction project repository

any project

### Version with bug

7.0 (current)

### Last version that worked well

6.0.312

### Affected platforms

Android

### Affected platform versions

not applicable

### Did you find any workaround?

Yes, use a task to set version code in Android manifest.
```
- task: android-manifest-version@1
  displayName: 'Set Android version numbers'
  inputs: 
    sourcePath: 'src/$(projectName)/$(projectName)/Platforms/Android/AndroidManifest.xml'
    versionCodeOption: 'buildid'
    versionCode: $(pipelineBuildNumber)
    versionName: $(pipelineVersionNumber)
    printFile: true
```

**Comment by ckrutsinger** [comment] 2023-04-12 13:10
FYI - ApplicationVersion has to be incremented to upload to Google Play, so this is a significant impediment. Manually updating the csproj file before running the Azure Pipeline is burdensome.

**Comment by jsuarezruiz** [comment] 2023-04-12 18:20
Could you attach a binlog?

**Comment by ckrutsinger** [comment] 2023-04-18 14:26
binlog provided. is there anything else I can do to get this issue resolved?

**Comment by ckrutsinger** [comment] 2023-04-19 22:10
Found a workaround and updated my issue.

**Comment by danielchalmers** [comment] 2023-04-29 00:18
Doesn't work on 8.0.100-preview.3.23178.7 either

**Comment by danielchalmers** [comment] 2023-05-01 18:20
I saw a similar issue #11139 was closed by [xamarin/xamarin-android#7795](https://github.com/xamarin/xamarin-android/pull/7795) but we're still having problems with versioning on the current SDK (#12859 #14528 #14524) - do you know why this could be happening? @dellis1972

Really impacts [GitVersioning](https://github.com/dotnet/Nerdbank.GitVersioning/pull/848).

**Comment by rlennoxmemoro** [comment] 2023-09-27 22:46
Not sure, but part of this appears to be the issue supposedly fixed in [PR 7795](https://github.com/xamarin/xamarin-android/pull/7795).  However, this fix is incorrect because it uses the application version for the android version code.

The android version code needs to be numeric.  An application version of 1.2.0 will not work and leads to an error on build.

The fix should instead use the <AndroidVersionCode> from the csproj, not the <ApplicationVersion>.

**Comment by dellis1972** [comment] 2023-09-28 11:35
I'm trying to find the documentation. But the MSBuild property `ApplicationVersion` has been standardized with the advent of Maui. 

`ApplicationVersion` = `AndroidVersionCode`
`ApplicationDisplayVersion` = `AndroidVersion`

So `ApplicationVersion` should be a numeric and this will work on all platforms. 
`ApplicationDisplayVersion` can be `1.0` or what ever it needs to be.

@jonathanpeppers  can you remember where we documented this change? I can't seem to find it.

**Comment by rlennoxmemoro** [comment] 2023-09-28 13:18
> I'm trying to find the documentation. But the MSBuild property `ApplicationVersion` has been standardized with the advent of Maui.
> 
> `ApplicationVersion` = `AndroidVersionCode` `ApplicationDisplayVersion` = `AndroidVersion`
> 
> So `ApplicationVersion` should be a numeric and this will work on all platforms. `ApplicationDisplayVersion` can be `1.0` or what ever it needs to be.
> 
> @jonathanpeppers can you remember where we documented this change? I can't seem to find it.

Thank you for the information. I retract my statement!

**Comment by jonathanpeppers** [comment] 2023-09-28 13:34
Sorry, I missed this comment, it's probably this doc:

* https://github.com/xamarin/xamarin-android/blob/main/Documentation/guides/OneDotNetSingleProject.md

**Comment by dellis1972** [comment] 2023-09-28 13:42
@jonathanpeppers I think we might need to update this documentation https://github.com/xamarin/xamarin-android/blob/main/Documentation/guides/building-apps/build-properties.md#applicationversion. 
and https://github.com/xamarin/xamarin-android/blob/main/Documentation/guides/building-apps/build-properties.md#androidversioncode. 

Both of these would probably confus people in the new .net system.

**Comment by mattleibow** [comment] 2023-11-01 19:39
Is this an issue still? I just tested in .NET 8 RC 2 and the provided command line is working as expected.

**Comment by ksoftllc** [comment] 2023-11-01 20:34
@mattleibow Our build tools are configured for .NET 7 and I cannot test with .NET 8. Feel free to close this if you have confirmed the fix.

**Comment by mattleibow** [comment] 2023-11-03 20:51
Is this still happening in .NET 7?  Maybe our projects differ so I can't repro it.

**Comment by ksoftllc** [comment] 2023-11-07 16:13
@mattleibow  I am still seeing it on 7.0.92

**Comment by mattleibow** [comment] 2023-11-08 00:06
@bsloehr can you attach a binlog?

https://github.com/xamarin/xamarin-macios/wiki/Diagnosis

**Closed** 2023-11-16 01:02 UTC
Labels: t/bug, area/tooling ⚙️, s/needs-info, s/no-recent-activity
