### ISSUE TITLE
[Enhancement] Built in controls

### ISSUE THREAD

**Issue by luismts** [dotnet/maui#93] opened 2020-05-22 21:49 UTC
# Summary

Within the Xamarin Forms ecosystem (community and third party companies), we have an immense amount of controls and control variations. It would be great to include controls like:

- Camera view
- Calendar
- PDF Viewer
- PopUp Page
- Charts or Gauges
- Segmented control
- Etc...

On the other hand, it would be nice to have some general functionalities integrated like

- Autocomplete View
- Rating
- Parallax View
- Treemap
- Segmented Control
- Etc..

And some built-in animations for controls and pages would be loved by the community

- Page Transitions
- Specific Controls Animations
- Visual (like Cupertino or another one)
- Etc..

Some outstanding features like

- Print
- Offline character recognition
- Digital signature
- Etc...

There are many things that can be integrated for ease of use for the entire community. There are some solutions for these controls out there, but sometimes they need a push and I think this is the best way because we will make the framework as it is much more mature in relation to what it can encompass.

**Comment by irantutors** [comment] 2020-05-22 22:11
Duplicate of #76

**Comment by charlesroddie** [comment] 2020-05-23 20:55
@KurdCsharper not a duplicate as that post is about "desires for things in general", while this is a desire for something specific!

**Comment by charlesroddie** [comment] 2020-05-23 21:06
There are some tradeoffs here.

By being in separate packages, some of these controls can:
1. Be changed more easily. It's very hard to change things in the Xamarin.Forms repo and we don't yet know that MAUI will be better. E.g. Rg.Plugins.Popup is already decent and it's unclear that creating a new one in MAUI will be better.
2. Support other .Net UI systems in addition to MAUI. E.g. charts or pdf could be done using platform-independent renderers so they can be used by MAUI projects and also by UWP, WPF, MAUI.iOS/Android, Blazor projects.

That said, things that involve a lot of user interaction and use of native controls would be good candidates: Camera, Calendar, Autocomplete

Print and OCR aren't controls so I would create a separate issue for these. And transitions.

**Comment by davidortinau** [comment] 2020-05-28 04:13
Camera we have a PR for but it was failing some tests. And I think we might be waiting for the new Google AndroidX version.

Print - https://github.com/xamarin/Essentials/issues/718

PopUp is something we should have worked on later this year if things go as planned.

SegmentedControl - Hussain has a work in progress for https://github.com/xamarin/Xamarin.Forms/issues/6904 though perhaps we considering using TabView from @jsuarezruiz as an xplat solution.

AppBar offers a parallax type of scroll and is coming, but more fine support for parallax is perhaps a scroll view enhancement. How might a Parallax control look if it were standalone? Akin to the Expander?

Page Transitions are coming with Segues. It was on the Xamarin.Forms roadmap and will be moved here.

Controls I don't expect we will do and which have great vendor support:
* Calendar
* PDF Viewer
* Charts and Graphs and Gauges
* Digital signature

Could you explain more what you see for these?
* Treemap
* Rating 
* Specific control animations

If we put/accepted some of these controls into a community toolkit, would that be useful?

What is preventing you (anyone) from using existing controls available from vendors or open source offerings today?

**Closed** 2020-09-14 20:32 UTC
Labels: proposal-open
