### ISSUE TITLE
Error on archiving .net7.0 for android with target platform ARM32: "Invalid option 'ARM32' for /platform; must be anycpu, x86, Itanium, arm, arm64"

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#15691] opened 2023-06-16 00:14 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Error-on-archiving-net70-for-android-w/10391872)._

---
Error on archiving apk using .net 7.0 for android with “Target platform” ARM32  
Error message says “Invalid option ‘ARM32’ for /platform; must be anycpu, x86, Itanium, arm, arm64”  
Latest visual studio 2022 17.6.2

I tried editing the project file manually and setting the value to “ARM” instead of “ARM32” and it archived but produced 3 MB apk that crashes on open.

---
#### Feedback Bot on 6/14/2023, 08:08 PM: 

(private comment, text removed)
#### Nina Chen [MSFT] on 6/14/2023, 11:39 PM: 

(private comment, text removed)
#### Feedback Bot on 6/14/2023, 11:40 PM: 

(private comment, text removed)
#### Feedback Bot on 6/15/2023, 10:28 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by MSLukeWest** [comment] 2023-06-16 00:20
The repro steps for this are pretty simple:

1) New MAUI app
2) Switch platform from AnyCPU to ARM32
3) Build

Result: Build Error

APPX0504	Unsupported $(Platform) property value 'ARM32'.    .nuget\packages\microsoft.windowsappsdk\1.3.230502000\buildTransitive\Microsoft.Build.Msix.Packaging.targets	1648

This is a MAUI SDK bug, the error comes from the WinAppSdk targets, but it's because they don't handle "ARM32" as a platform, just "ARM".  We should probably transform ARM32 to ARM before passing it to their targets.

I confirmed that this reproes on both .NET 7.0 / WinAppSDK 1.2 and .NET 8.0 / WinAppSDK 1.3.  I've included binlogs for both in the attached zip.  

[MAUI_Arm32_Failure.zip](https://github.com/dotnet/maui/files/11764165/MAUI_Arm32_Failure.zip)

**Comment by mosammo** [comment] 2023-06-22 15:59
This is a showstopper for some projects and the fix should be very easy and quick. please give it priority.

**Comment by MSLukeWest** [comment] 2023-06-26 19:27
@jsuarezruiz I see you added the Android tag based on the title, but this bug actually blocks building arm32 for all platforms.  Please help route as appropriate for .NET 8.  cc @mattleibow

**Comment by mosammo** [comment] 2023-07-10 18:20
Finally found a workaround: in android project properties "platform target" select "ARM64" (not ARM32) then edit the project file manually and change the "RuntimeIdentifiers" tag as follows:
`<RuntimeIdentifiers>android-arm;</RuntimeIdentifiers>`
This will result in an apk that targets ARM32 without ARM64 assemblies.
https://github.com/xamarin/xamarin-android/issues/8168#issuecomment-1629443944

**Comment by dellis1972** [comment] 2023-07-11 10:10
@mosammo the `PlatformTarget` can be left as `AnyCPU`. There is not need to change it to `ARM64`.

**Comment by mattleibow** [comment] 2023-11-08 00:19
I believe it is not a workaround to set the RuntimeIdentifiers, it is the correct way. Platform is no longer the correct way to change the platform (yeah I know) in .NET 6+.

Closing this as Platform is obsolete, RuntimeIdentifier is the new way. This can also be seen with the CLI args, there is no way to provide platform easily, but there is `-r` for Runtime Identifiers.

**Closed by mattleibow** 2023-11-08 00:19 UTC
Labels: t/bug, platform/android 🤖, area/tooling ⚙️, partner/android
