### ISSUE TITLE
MAUI Incorrect Theme when Resuming iOS App

### ISSUE THREAD

**Issue by dinisvieira** [dotnet/maui#20384] opened 2024-02-06 13:06 UTC
### Description

Maui is using `Light Theme` instead of `Dark Theme` on iOS when resuming App (for example after "sharing a link" to a browser) when the OS is set to use Dark Theme (and the app was showing Dark Theme before resuming.
`Application.Current.RequestedTheme` is also returning the incorrect theme in these scenarios on `App.OnResume`.

### Steps to Reproduce

PS: It's sometimes needed to repeat Share process to reproduce the bug.

#### Steps to Reproduce with the reproduction repo:
1. Run App on iOS Device with the OS Theme set to Dark
2. Click on the Button and Share using a Browser
3. Go Back to App
4. Repeat from step 2 (until the App is showing Light Theme)

#### Result:
App shows Light Theme instead of Dark

#### Expected:
App should always use Dark Theme (which is the one used and requested by the OS)

### Link to public reproduction project repository

https://github.com/dinisvieira/maui-os-dark-theme-bug/tree/main

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 17.3 (possibly others)

### Did you find any workaround?

No workarounds that wouldn't have some drawback. `Application.Current.RequestedTheme` is also returning the incorrect theme.

**Comment by drasticactions** [comment] 2024-02-06 14:59
Duplicate of https://github.com/dotnet/maui/issues/19614

**Closed by drasticactions** 2024-02-06 14:59 UTC
Labels: t/bug
