### ISSUE TITLE
TapGestureRecognizer not respecting the NumberOfTapsRequired property

### ISSUE THREAD

**Issue by williambuchanan2** [dotnet/maui#13189] opened 2023-02-08 07:45 UTC
### Description

When NumberOfTapsRequired is set to 2 the event/command is fired, but when set to 3 or more the event does not fire.

### Steps to Reproduce

1. In the Xaml for a ContentPage, add a ScrollView.
2. On the scroll view add a TapGestureRecognizer.
3. Set the NumberOfTapsRequired to 3.

Run - notice it doesn't fire the event.

4. Set NumberOfTapsRequired to 2.

Run - notice the event fires.

        <ScrollView VerticalOptions="Fill" >
            <ScrollView.GestureRecognizers>
                <TapGestureRecognizer  Command="{Binding SelectEnvironmentPressedCommand}"
                              NumberOfTapsRequired="3" />
            </ScrollView.GestureRecognizers>

According to the documentation, it can only recognise double clicks in Windows, but this was Android.

### Link to public reproduction project repository

?

### Version with bug

6.0.312

### Last version that worked well

6.0.312

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

net7.0-Android

### Did you find any workaround?

No

**Comment by jfversluis** [comment] 2023-02-08 08:46
I think this has been this was since forever, also on Forms. I think Android simply doesn't understand more than a double tap.

A workaround would be to just keep the number of taps to 1 and implement a counter when triggered of your own.

**Comment by williambuchanan2** [comment] 2023-02-08 09:18
Thanks @jfversluis  - that's a good idea for a workaround.

**Comment by hartez** [comment] 2023-08-07 15:06
Duplicate of #11434

**Closed by hartez** 2023-08-07 15:06 UTC
Labels: proposal/open, platform/android 🤖, area/gestures
