### ISSUE TITLE
DisplayActionSheet still not working on Windows

### ISSUE THREAD

**Issue by DennisWelu** [dotnet/maui#14829] opened 2023-04-28 14:23 UTC
### Description

Displaying an action sheet on Windows from a Modal page does not work. When attempted, it just changes to show a blank page with nothing the user can do.

(The details are essentially the same as for this closed issue: https://github.com/dotnet/maui/issues/14098.)

### Steps to Reproduce

1. Open a modal window e.g. `Navigation.PushModalAsync(new NavigationPage(new ModalRootPage()));`
2. Add a button with a click handler in the modal page that displays an action sheet e.g. 

```
	async void OnDisplayActionSheetClicked(object sender, EventArgs e)
	{
		var action = await DisplayActionSheet("ActionSheet: Send to?", "Cancel", null, "Email", "Twitter", "Facebook");
		Debug.WriteLine("Action: " + action);
	}
```

### Link to public reproduction project repository

https://github.com/DennisWelu/MauiBugWindows-DisplayActionSheet

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows SDK 10.0.19041.0, maybe others

### Did you find any workaround?

No

**Comment by gerneio** [comment] 2023-06-08 21:37
Identical issue using latest MAUI workloads:

```cmd
> dotnet workload list

Installed Workload Id      Manifest Version       Installation Source
---------------------------------------------------------------------
android                    33.0.46/7.0.100        VS 17.6.33723.286
maui-ios                   7.0.86/7.0.100         VS 17.6.33723.286
maui-windows               7.0.86/7.0.100         VS 17.6.33723.286
wasm-tools                 7.0.5/7.0.100          VS 17.6.33723.286
maui-maccatalyst           7.0.86/7.0.100         VS 17.6.33723.286
maccatalyst                16.4.7060/7.0.100      VS 17.6.33723.286
ios                        16.4.7060/7.0.100      VS 17.6.33723.286
maui-android               7.0.86/7.0.100         VS 17.6.33723.286
```

Quick work around that worked for me was to use `App.Current.MainPage.DisplayActionSheet`. Also, please note that both `DisplayAlert` and `DisplayPromptAsync` worked from within my modal content page, just not `DisplayActionSheet`.

**Comment by XamlTest** [comment] 2023-07-05 07:21
Verified this on Visual Studio Enterprise 17.7.0 Preview 2.0. Repro on Windows 11, not repro on Android 13.0-API33 and iOS 16.4 with below Project:
[14829.zip](https://github.com/dotnet/maui/files/11954967/14829.zip)

![BlankPage](https://github.com/dotnet/maui/assets/97647558/674eae04-013e-4580-9cfc-3252b065661c)

**Comment by rneeft** [comment] 2023-08-17 19:42
Not sure If I should raise a new bug for this but when I use the following code a model dialog is working... 

```csharp
public partial class OverviewByPositionPage : ContentPage
{
    ....
    private async void OnJumpGroupButtonClick(object sender, TappedEventArgs e)
    {
        var result = await DisplayActionSheet("Jump to group", "Cancel", null, groups);
    }
}
```

However on Windows the dialog is very tiny, since there is enough screen available
![image](https://github.com/dotnet/maui/assets/16198068/6998be52-f69f-4c0b-a74c-c81e22670140)

Whereas the Android version shows the the dialog nearly full screen:
![image](https://github.com/dotnet/maui/assets/16198068/78e7b013-2070-46fa-9de6-025192d1e299)

**Comment by Raystorm7** [comment] 2023-09-21 15:27
Any news about a workaround or a solution?
Thank you.

**Comment by DennisWelu** [comment] 2023-09-21 15:29
@Raystorm7 I've got nothing "good" for a workaround.

**Comment by HakamFostok** [comment] 2023-10-08 15:44
YES, The title is very correct, `DisplayActionSheet STILL NOT working` <br/>
Just one request, please, do not close this bug quickly and mark it as closed before you make sure 100% percent it is fixed.
I am using .NET 7, and obsessed with updating to the latest versions, but the problem still exists, believe me.

**Comment by Raystorm7** [comment] 2023-11-23 10:00
I can confirm that the problem still exists in .NET 8. 

I think this is a base feature that should be fixed ASAP., or maybe I'm wrong and that's only the 5 of us we're using DisplayActionSheet on Windows?

**Comment by jmeyerworms** [comment] 2023-12-27 15:54
any news ?

**Comment by Brosten** [comment] 2024-01-19 06:54
And still exist in SR1 (8.0.6) :(
Hope to see a fix rather soon...

**Comment by Legends** [comment] 2024-02-04 12:04
> And still exist in SR1 (8.0.6) :( Hope to see a fix rather soon...

Live debugging on windows => didn't work
Live debugging on local android device=> works!
Live debugging on windows => works!

Very strange.

Sometimes things dont work during lkive debugging, but work when deployed for example.

Like yesterday for example, i wanted to open an issue for another issue which occured only on android during live debugging.
Then I coincidentally deployed the app to my phone and then it was working.

So, things are still very unstable.
Waiting for .NET 9.0, oct 2024.

**Comment by MitchBomcanhao** [comment] 2024-03-13 15:34
the action sheet is still displayed too small on windows.

**Comment by MitchBomcanhao** [comment] 2024-03-15 17:01
by adding this style to the windows project app.xaml file, the action sheet dialog is actually resizing itself to fit the content, instead of having the hardcoded size that was included in the most recent commits.
this is a subset of the standard style for a flyoutpresenter, and other than removing a few (seemingly) unnecessary things, I've only made changes to a few properties, namely max height, max width, and some alignments. Also added a minWidth to make the content less claustrophobic.

Hope this is useful to someone - if it is fundamentally flawed somehow, I haven't noticed. Only tried this on Windows 10 and it seems to work ok.


```
            <Style x:Key="MauiFlyoutPresenterStyle" TargetType="FlyoutPresenter">
                <Setter Property="MaxHeight" Value="{x:Null}" />
                <Setter Property="MaxWidth" Value="{x:Null}" />
                <Setter Property="Template">
                    <Setter.Value>
                        <ControlTemplate TargetType="FlyoutPresenter">
                            <Border MinWidth="350"
                                    Padding="{ThemeResource FlyoutBorderThemePadding}"
                                    HorizontalAlignment="Center"
                                    VerticalAlignment="Center"
                                    contract7NotPresent:CornerRadius="{ThemeResource OverlayCornerRadius}"
                                    contract7Present:BackgroundSizing="OuterBorderEdge"
                                    contract7Present:CornerRadius="{TemplateBinding CornerRadius}"
                                    Background="{TemplateBinding Background}"
                                    BorderBrush="{TemplateBinding BorderBrush}"
                                    BorderThickness="{TemplateBinding BorderThickness}">
                                <ScrollViewer x:Name="ScrollViewer"
                                              AutomationProperties.AccessibilityView="Raw"
                                              HorizontalScrollBarVisibility="{TemplateBinding ScrollViewer.HorizontalScrollBarVisibility}"
                                              HorizontalScrollMode="{TemplateBinding ScrollViewer.HorizontalScrollMode}"
                                              VerticalScrollBarVisibility="{TemplateBinding ScrollViewer.VerticalScrollBarVisibility}"
                                              VerticalScrollMode="{TemplateBinding ScrollViewer.VerticalScrollMode}"
                                              ZoomMode="{TemplateBinding ScrollViewer.ZoomMode}">
                                    <ContentPresenter Margin="{TemplateBinding Padding}"
                                                      HorizontalAlignment="Stretch"
                                                      VerticalAlignment="Top"
                                                      Content="{TemplateBinding Content}"
                                                      ContentTemplate="{TemplateBinding ContentTemplate}"
                                                      ContentTransitions="{TemplateBinding ContentTransitions}" />
                                </ScrollViewer>
                            </Border>
                        </ControlTemplate>
                    </Setter.Value>
                </Setter>
            </Style>
```

**Closed** 2024-03-27 22:15 UTC
Labels: t/bug, platform/windows 🪟, area/controls 🎮, s/verified, control-dialogalert, s/triaged
