### ISSUE TITLE
Checkboxes Have a Default Right Margin of 100

### ISSUE THREAD

**Issue by openbots-ff** [dotnet/maui#6160] opened 2022-04-16 15:51 UTC
### Description

Checkboxes with margins of 0 are rendered with a default right margin of 100.

### Steps to Reproduce

1. Create a new Maui app
2. Add a checkbox:

`<Grid ColumnDefinitions="Auto, Auto">
                <CheckBox Grid.Column="0" Background = "red"></CheckBox>
                <CheckBox Grid.Column="1" Background = "yellow"></CheckBox>
            </Grid>`

![image](https://user-images.githubusercontent.com/51149926/163681560-4b153563-4c01-4173-8b2f-3e5467e05ad7.png)
![image](https://user-images.githubusercontent.com/51149926/163681460-38e21f1b-5510-489b-b00f-d1ba4c02cb67.png)

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Preview 14

### Affected platforms

Android, Windows

### Affected platform versions

windows SDK 10.0.19041, Android 11

### Did you find any workaround?

Setting the Margin to "0, 0, -100, 0" renders the way a margin of "0" should.

**Comment by pekspro** [comment] 2022-04-16 17:12
I was just going to report this myself :-)

I think the issue is related to `MinimumWidthRequest` property. Setting this to 1 makes it better.

**Comment by kristinx0211** [comment] 2022-04-18 01:23
verified repro, on windows also the background color can not be shown, see:
![image](https://user-images.githubusercontent.com/99457000/163740179-9b25d90a-d159-41f5-bb29-86b0588a67cd.png)
on Android:
![image](https://user-images.githubusercontent.com/99457000/163740311-794bd57f-f3ae-4a3e-8567-a49234256383.png)

**Comment by christophbrunner** [comment] 2022-05-03 13:27
Duplicate of #4693

**Closed** 2022-05-25 17:09 UTC
Labels: t/bug, area/controls 🎮, s/verified
