### ISSUE TITLE
Set Page-Title in OnAppearing with async call

### ISSUE THREAD

**Issue by christophbrunner** [dotnet/maui#5419] opened 2022-03-18 13:06 UTC
### Description

If the shell /page title is set after an async method-call in OnAppearing, it is not displayed on the first call / appearing.

```dotnet
public MainPage()
{
    InitializeComponent();
    Title = "Set on Constructor";
}

protected override async void OnAppearing()
{
    base.OnAppearing();
    string title = await GetTitle(); //Something seems to be going wrong here
    Title = title;
}

private async Task<string> GetTitle()
{
    await Task.Delay(1000);
    //get data form API
    return "Set on OnAppearing (Not working on first 'OnAppearing')";
}
```

**First display of MainPage**
![image](https://user-images.githubusercontent.com/1324374/159006579-55ba2b00-7df0-40f1-b2d9-6d7b08c36a79.png)

 **All further display of MainPage**
![image](https://user-images.githubusercontent.com/1324374/159006613-3a721a94-f4aa-418b-b005-f8de790158d8.png)

Without an async call, the result is as expected.

```dotnet
protected override void OnAppearing()
{
    base.OnAppearing();
    string title = GetTitle();
    Title = title;
}
```

### Steps to Reproduce

1. Run the repro project. [MauiApp-ShellTitle.zip](https://github.com/dotnet/maui/files/8304609/MauiApp-ShellTitle.zip)
Click on both Shell pages several times.

“Page 1 (Not Working)” has on the first “OnAppearing” not the correct / expected
 title

### Version with bug

Preview 14 (current)

### Last version that worked well

Preview 13

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Windows 21H2 (OSBuild 22000.556)

### Did you find any workaround?

Remove async

**Comment by kristinx0211** [comment] 2022-03-21 07:09
@christophbrunner not repro this issue with the above project. please see the video, if it is your expected result?
https://user-images.githubusercontent.com/99457000/159217701-dcea6725-1dba-4a0d-9fc8-54aa787abf4c.mp4
vs version: 17.2.0 Preview 2.0 [32301.586.main]
framework (net6.0-windows 10.0.19041)

**Comment by Mephisztoe** [comment] 2022-03-29 09:32
I can confirm that issue and while I was experiencing the same behaviour, I couldn't quite explain its root cause yet. Thank you, @christophbrunner for detailing this out.

**Comment by PureWeen** [comment] 2022-03-30 14:29
This appears to be fixed on RC1.

**Closed by PureWeen** 2022-03-30 14:29 UTC
Labels: t/bug, area/shell 🐢, s/verified, s/needs-attention
