### ISSUE TITLE
EntityFrameworkCore install errors

### ISSUE THREAD

**Issue by AdnanZafar0005** [dotnet/maui#7436] opened 2022-05-24 08:29 UTC
Hi, I'm trying to install EF Core 6 as well as preview but it failed to build. Following error occurs.
Payload contains two or more files with the same destination path
![Screenshot (129)](https://user-images.githubusercontent.com/45895341/169986524-8fb3c0f1-0773-4ef3-8f69-29bbe69e76a0.png)

**Comment by janseris** [comment] 2022-05-24 08:58
You are installing EF Core 7

**Comment by AdnanZafar0005** [comment] 2022-05-24 09:03
Yes, I tried using EF Core 7 and 6 as well both does not work.

**Comment by janseris** [comment] 2022-05-24 12:20
Isn't it related to Newtonsoft.Json? There is System.Text.Json which replaces it. Do you need to use Newtonsoft.Json?

**Comment by janseris** [comment] 2022-05-24 12:23
Isn't the error related to Newtonsoft.Json? The build is looking for 9.0.0 while you have 13.0, don't you have it duplicated in package references? System.Text.Json replaces Newtonsoft.Json btw.

**Comment by Eilon** [comment] 2022-05-24 17:18
@AdnanZafar0005 can you please post a repro project to a GitHub repo so that we can take a look?

**Comment by emorell96** [comment] 2022-05-24 23:27
@Eilon wouldn't EF Core have trouble working in AOT mode in iOS? It was my understanding that EF Core needs the JIT compiler to function properly, but iOS apps need to be AOT compiled before being published.

**Comment by Eilon** [comment] 2022-05-25 16:16
@emorell96 as far as I know it works, and there's even a doc on it for working with Xamarin.iOS (which is used in .NET MAUI iOS projects as well): https://docs.microsoft.com/ef/core/get-started/xamarin

But, I haven't tried it.

**Comment by Eilon** [comment] 2022-05-25 18:07
Tagging @ajcvickers @bricelam as FYI, or in case you have any thoughts on any of this. As far as I can tell this doesn't repro (and I don't see why it would), but we don't have exact repro steps yet either.

**Comment by bricelam** [comment] 2022-05-25 21:40
Duplicate of https://github.com/microsoft/WindowsAppSDK/issues/2237

**Comment by Eilon** [comment] 2022-05-25 22:42
Thanks, @bricelam , looks like that issue also describes some workarounds.

**Closed by Eilon** 2022-05-25 22:42 UTC
Labels: s/needs-attention
