### ISSUE TITLE
Maui Hybrid App stuck on  "Loading..." in release mode on Android.

### ISSUE THREAD

**Issue by rad765** [dotnet/maui#16313] opened 2023-07-23 19:56 UTC
### Description

MAUI Hybrid App stuck on first "Loading" in release mode on Android, even in Out of the box app.
Compile in Debug mode and the program runs fine.

Using 
Visual studio 17.7 Preview 4 and 
.Net 8 preview 6

### Steps to Reproduce

1: create a new Maui Hybrid project in Visual studio (version 17.7.0 - Previev 4 and .Net 8 Preview 6)
2: compile in release mode, and run on either Android. Either physical device or Emulater.

### Link to public reproduction project repository

None

### Version with bug

7.0.49

### Last version that worked well

6.0

### Affected platforms

Android

### Affected platform versions

Emulator (Pixel 5) + Android V. 13 plus one older version

**Comment by MackinnonBuck** [comment] 2023-08-21 22:14
Looks like a dupe of https://github.com/aspnet/AspNetCore-ManualTests/issues/1934.

@grendello Are you able to look into this?

**Comment by SliemBeji-FBC** [comment] 2023-08-28 08:10
> 

The link is invaild. Could you update it?

**Comment by MackinnonBuck** [comment] 2023-08-28 22:11
@SliemBeji-FBC The link is not invalid - it's a private repository 🙂

**Comment by MackinnonBuck** [comment] 2023-09-06 18:45
Looks like this bug no longer exists as of .NET 8.0 RC1. @grendello, do you know if there was a deliberate fix for this?

**Comment by grendello** [comment] 2023-09-06 19:42
@MackinnonBuck there was no fix as such. We disabled code that caused it ([marshal methods](https://github.com/xamarin/xamarin-android/blob/dda99cd50de732c5bdfe59533bbaf414c676c0a8/Documentation/guides/internals/JavaJNI_Interop.md)) and we're going to work on it for NET9.  The current suspicions are that either marshal methods trigger a race condition somewhere (as they make portions of the runtime java interop code much faster), or that there's a subtle runtime bug lurking somewhere.

**Closed** 2023-09-06 21:07 UTC
Labels: t/bug, platform/android 🤖, area/blazor 🕸️
