### ISSUE TITLE
Android - Soft Keyboard - AdjustPan - Page does not un-pan when keyboard is closed

### ISSUE THREAD

**Issue by shadowfoxish** [dotnet/maui#12793] opened 2023-01-19 19:57 UTC
### Description

Since upgrading to Maui 7, I've been having a lot of issues with Entry inputs and the Android soft keyboard. The keyboard is very broken right now and there are numerous bug reports for it, but this I have not been able to find a report for yet. (Wont go away when you press the checkmark, wont focus on the next control, UPPERCASE transforms make text input backwards, etc. Those are not what I'm reporting however.)

Basically, I have a modal page that has a bunch of Entry controls on it, and when I focus one of the lower ones, as desired, the window pans up so the Entry is above the keyboard. However, when I press the device back button to hide the keyboard (so I can use my on-screen buttons), the view does not un-pan. If I tap an Entry higher on screen then it comes back to normal, but this is burdensome and whack UX. You can also see it flicker, like it's trying to re-render but not working or something.

https://user-images.githubusercontent.com/12143535/213544161-cc276123-2e76-430c-a89a-4de087cd131e.mp4

Am I doing something wrong with the design of this screen or is this a bug?

Here is the XAML for this screen
```xaml
<?xml version="1.0" encoding="utf-8" ?>
<vmSource:PageBase x:Class="InventoryFoxApp.Pages.QuantityBinModal" x:TypeArguments="vmSource:QuantityBinModalViewModel" xmlns="http://schemas.microsoft.com/dotnet/2021/maui" xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml" xmlns:fox="clr-namespace:InventoryFoxApp.Plumbing" xmlns:vmSource="clr-namespace:InventoryFoxApp.Pages" xmlns:svcModel="clr-namespace:InventoryFoxApp.ServiceModels" x:DataType="vmSource:QuantityBinModalViewModel">
	<ContentPage.Resources>
		<fox:DefaultValueConverter x:Key="DefaultValueConverter"></fox:DefaultValueConverter>
	</ContentPage.Resources>
	<ContentPage.Content>
		<Grid Margin="10,4">
			<Grid.RowDefinitions>
				<RowDefinition Height="80"></RowDefinition>
				<!-- Pic and Header -->
				<RowDefinition Height="20"></RowDefinition>
				<!-- Label -->
				<RowDefinition Height="50"></RowDefinition>
				<!-- Quantity Input -->
				<RowDefinition Height="100"></RowDefinition>
				<!-- Calculator -->
				<RowDefinition Height="4"></RowDefinition>
				<!-- Div -->
				<RowDefinition Height="25"></RowDefinition>
				<!-- Label -->
				<RowDefinition Height="50"></RowDefinition>
				<!-- Cart/Shelf Entry -->
				<RowDefinition Height="50"></RowDefinition>
				<!-- Buttons -->
			</Grid.RowDefinitions>
			<Grid Grid.Row="0" RowDefinitions="*,*" ColumnDefinitions="75,*">
				<Image Grid.Row="0" Grid.Column="0" Grid.RowSpan="2" Source="{Binding Path=ImageUrl, Converter={StaticResource Key=DefaultValueConverter},ConverterParameter='logo'}" HeightRequest="75" WidthRequest="75" Aspect="AspectFit" HorizontalOptions="StartAndExpand" VerticalOptions="StartAndExpand" />
				<Label Grid.Row="0" Grid.Column="1" Text="Receive How Many?" FontSize="Large"></Label>
				<Label Grid.Row="1" Grid.Column="1" Text="{Binding Path=ItemId}"></Label>
			</Grid>
			<Label Grid.Row="1" Text="Input or Calc Qty (optional)"></Label>
			<StackLayout Grid.Row="2" Orientation="Horizontal">
				<Entry Text="{Binding Path=Quantity}" Placeholder="Quantity (optional)" Keyboard="Numeric" CursorPosition="1" HorizontalOptions="FillAndExpand" />
				<Label Text="{Binding Path=UnitOfMeasure, StringFormat='/{0}'}" VerticalTextAlignment="Center" FontSize="Medium" />
			</StackLayout>
			<Grid Grid.Row="3">
				<Grid.RowDefinitions>
					<RowDefinition Height="*"></RowDefinition>
					<RowDefinition Height="20"></RowDefinition>
					<RowDefinition Height="*"></RowDefinition>
				</Grid.RowDefinitions>
				<Grid.ColumnDefinitions>
					<ColumnDefinition Width="75"></ColumnDefinition>
					<ColumnDefinition Width="*"></ColumnDefinition>
				</Grid.ColumnDefinitions>
				<Label Grid.Row="0" Grid.Column="0" Text="Case Qty" VerticalOptions="Center"></Label>
				<Entry Grid.Row="0" Grid.Column="1" Text="{Binding Path=CaseQuantity}" HorizontalOptions="FillAndExpand" HorizontalTextAlignment="Center" Keyboard="Numeric"></Entry>
				<Label Grid.Row="1" Grid.Column="1" Text="×" HorizontalOptions="Center"></Label>
				<Label Grid.Row="2" Grid.Column="0" Text="Num Cases" VerticalOptions="Center" />
				<Entry Grid.Row="2" Grid.Column="1" Text="{Binding Path=NumCases}" HorizontalOptions="FillAndExpand" HorizontalTextAlignment="Center" Keyboard="Numeric"></Entry>
			</Grid>
			<fox:PrettyDivider Grid.Row="4" HeightRequest="2" />
			<Label Grid.Row="5" Text="Scan cart shelf to receive"></Label>
			<Entry Grid.Row="6" Text="{Binding Path=Bin}" Placeholder="VCart">
				<Entry.Keyboard>
					<Keyboard x:FactoryMethod="Create">
						<x:Arguments>
							<KeyboardFlags>CapitalizeCharacter</KeyboardFlags>
						</x:Arguments>
					</Keyboard>
				</Entry.Keyboard>
			</Entry>
			<Grid Grid.Row="7" ColumnDefinitions="*,*">
				<Button Grid.Column="0" Text="Ok" Command="{Binding Path=OkCommand}"></Button>
				<Button Grid.Column="1" Text="Cancel" Command="{Binding Path=CancelCommand}"></Button>
			</Grid>
		</Grid>
	</ContentPage.Content>
</vmSource:PageBase>
```

MainActivity.cs attribute
```cs
[Activity(Theme = "@style/Maui.SplashTheme", MainLauncher = true, ConfigurationChanges = ConfigChanges.ScreenSize | ConfigChanges.Orientation | ConfigChanges.UiMode | ConfigChanges.ScreenLayout | ConfigChanges.SmallestScreenSize)]
```

MainApplication.cs Application attribute
```cs
[Application(UsesCleartextTraffic = true)]
```

Android Manifest
```xml
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android">
	<application android:icon="@mipmap/appicon" android:roundIcon="@mipmap/appicon_round" android:supportsRtl="true" android:windowSoftInputMode="adjustPan"></application>
	<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
	<uses-permission android:name="android.permission.INTERNET" />
	<uses-permission android:name="android.permission.CAMERA" />
	<uses-permission android:name="android.permission.VIBRATE" />
</manifest>
```
_Just to note, I also tried this with stateHidden|adjustResize, and it had identical behavior_

The view model just has normal INotifyPropertyChanged properties, like this
```cs
		private decimal quantity;
		public decimal Quantity
		{
			get {
				return quantity;
			}
			set {
				quantity = value;
				NotifyPropertyChanged(nameof(Quantity));
			}
		}

```

### Steps to Reproduce

Push a Modal onto the navigation stack with screen content that is long enough to need to Pan.
Tap an entry on the bottom of the page, and watch the top part of the screen disappear or move incorrectly. It cannot be scrolled back by the user, who could potentially get stuck.

### Link to public reproduction project repository

n/a

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other - Xamarin.Forms 5

### Affected platforms

Android

### Affected platform versions

Tested on Android 9.0, API 28

### Did you find any workaround?

Short of re-designing the screen, no.

**Comment by mattleibow** [comment] 2023-01-23 15:24
Duplicate of #12406

**Closed by mattleibow** 2023-01-23 15:25 UTC
Labels: t/bug, platform/android 🤖, s/needs-repro
