### ISSUE TITLE
MAUI DisplayAlert not modal on Android 10

### ISSUE THREAD

**Issue by FrantisekPregis** [dotnet/maui#15671] opened 2023-06-15 09:20 UTC
### Description

DisplayAlert can be dismissed by tapping outside of the alert window on Android 10, e.g.:

bool answer = await DisplayAlert("Question?", "Would you like to play a game", "Yes", "No");

In this case tapping outside the alert returns "No."

But the documentation (https://learn.microsoft.com/en-gb/dotnet/maui/user-interface/pop-ups) explicitly states that the behaviour should be modal. It behaves in a modal way on Windows 10.

Maybe this is a feature, but it would be great to have a non-dismissable option in the function, so important prompts have to be answered with one of the buttons. Same goes for DisplayActionSheet.

František

### Public API Changes

[DisplayAlert(String, String, String, String, FlowDirection, CanBeDissmissedByTappingOutside)]

[DisplayActionSheet(String, String, String, String[], CanBeDissmissedByTappingOutside)]

### Intended Use-Case

I would like to get an explicit answer from the user, by pressing one of the options. Tapping outside is analogical to Cancel, but the function returns only true or false. The user may not realise that by tapping outside she picked one of the options.

In case of DisplayActionSheet this can be handled, but I have to redisplay the pop up if a bad option is given by tapping outside. A non dismissable option would lead to more elegant behavior.

**Comment by MV10** [comment] 2023-08-16 18:37
I haven't checked `DisplayAlert` but `DisplayActionSheet` returns `null` which can lead to unexpected failures versus the documented behavior.

**Comment by mattleibow** [comment] 2023-11-30 00:07
Duplicate of https://github.com/dotnet/docs-maui/issues/1924

**Closed by mattleibow** 2023-11-30 00:07 UTC
Labels: proposal/open, area/controls 🎮, control-dialogalert
