### ISSUE TITLE
Pairing to Mac fails in 17.7.6 with 404 error while downloading 7.0.403-servicing.23520.24.

### ISSUE THREAD

**Issue by jayhayman-hdd** [dotnet/maui#18352] opened 2023-10-25 15:41 UTC
### Description

After updating to 17.7.6 (Windows), pairing to macOS now fails with a 404 on `--install-dir /Users/USERNAME/Library/Caches/Xamarin/XMA/SDKs/dotnet --version 7.0.403-servicing.23520.24 --architecture Arm64 --no-path`.

Final error is: Could not install dotnet SDK '7.0.403-servicing.23520.24'. Details: dotnet_install: Error: Could not find `.NET Core SDK` with version = 7.0.403-servicing.23520.24

### Steps to Reproduce

Upgrade to 17.7.6.
Try and pair to Mac.

### Version with bug

7.0.96

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.49

### Affected platforms

macOS

### Affected platform versions

Windows + macOS

### Did you find any workaround?

Not yet...

### Relevant log output

```shell
Checking host configuration for connecting to 'Jay’s iMac'...
Checking SSH configuration...
Initializing environment...
Checking available disk space...
Checking if Rosetta is installed...
Checking Mono installation...
Checking host configuration for connecting to 'Jay’s iMac'...
Host 'Jay’s iMac' is configured correctly
Starting connection to 'Jay’s iMac'...
Checking Broker 17.7.0.223 installation...
Starting Broker 17.7.0.223 in port 57732...
Broker 17.7.0.223 started successfully
Starting connection to 'Jay’s iMac'...
SSH connection to 'Jay’s iMac' has been established...
Starting registered Agents: IDB 17.7.0.223...
Starting IDB 17.7.0.223...
Checking IDB 17.7.0.223 installation...
Starting IDB 17.7.0.223 in port 57732...
IDB 17.7.0.223 started successfully
IDB 17.7.0.223 started
Starting registered Agents: ...
The Agents have been started successfully
Performing server validations against 'Jay’s iMac'...
Installing dotnet SDK '7.0.403-servicing.23520.24'...
Downloading dotnet-install script...
Using dotnet install script '/Users/USERNAME/Library/Caches/Xamarin/XMA/SDKs/dotnet/scripts/dotnet-install.sh'...
--install-dir /Users/USERNAME/Library/Caches/Xamarin/XMA/SDKs/dotnet --version 7.0.403-servicing.23520.24 --architecture Arm64 --no-path
dotnet-install: Attempting to download using primary link https://dotnetcli.azureedge.net/dotnet/Sdk/7.0.403-servicing.23520.24/dotnet-sdk-7.0.403-servicing.23520.24-osx-arm64.tar.gz
curl: (22) The requested URL returned error: 404
dotnet-install: The resource at primary link 'https://dotnetcli.azureedge.net/dotnet/Sdk/7.0.403-servicing.23520.24/dotnet-sdk-7.0.403-servicing.23520.24-osx-arm64.tar.gz' is not available.
dotnet-install: Attempting to download using legacy link https://dotnetcli.azureedge.net/dotnet/Sdk/7.0.403-servicing.23520.24/dotnet-dev-osx-arm64.7.0.403-servicing.23520.24.tar.gz
curl: (22) The requested URL returned error: 404
dotnet-install: The resource at legacy link 'https://dotnetcli.azureedge.net/dotnet/Sdk/7.0.403-servicing.23520.24/dotnet-dev-osx-arm64.7.0.403-servicing.23520.24.tar.gz' is not available.
dotnet-install: Attempting to download using primary link https://dotnetbuilds.azureedge.net/public/Sdk/7.0.403-servicing.23520.24/dotnet-sdk-7.0.403-servicing.23520.24-osx-arm64.tar.gz
curl: (22) The requested URL returned error: 404
dotnet-install: The resource at primary link 'https://dotnetbuilds.azureedge.net/public/Sdk/7.0.403-servicing.23520.24/dotnet-sdk-7.0.403-servicing.23520.24-osx-arm64.tar.gz' is not available.
dotnet-install: Attempting to download using legacy link https://dotnetbuilds.azureedge.net/public/Sdk/7.0.403-servicing.23520.24/dotnet-dev-osx-arm64.7.0.403-servicing.23520.24.tar.gz
curl: (22) The requested URL returned error: 404
dotnet-install: The resource at legacy link 'https://dotnetbuilds.azureedge.net/public/Sdk/7.0.403-servicing.23520.24/dotnet-dev-osx-arm64.7.0.403-servicing.23520.24.tar.gz' is not available.
Could not install dotnet SDK '7.0.403-servicing.23520.24'. Details: dotnet_install: Error: Could not find `.NET Core SDK` with version = 7.0.403-servicing.23520.24
```

**Comment by mnottbohm** [comment] 2023-10-25 17:00
I have the same problem.

**Comment by VToegel** [comment] 2023-10-25 17:21
Yep, me too. Net servicing pack is missing in the blob store ->404 error.
That's these small annoying errors with Maui after every update..

But fortunately it's getting better.

**Comment by emaf** [comment] 2023-10-25 19:59
Dupe of https://github.com/dotnet/install-scripts/issues/407.

**Closed by emaf** 2023-10-25 19:59 UTC
Labels: t/bug, area/tooling ⚙️, s/move-to-vs-feedback
