### ISSUE TITLE
Hot Restart (iOS) doesn't succeed with local device

### ISSUE THREAD

**Issue by FelipeCostaGualberto** [dotnet/maui#7384] opened 2022-05-20 21:57 UTC
### Description

Hi, I'm using latest VS22 preview (17.3.0 Preview 1.0). When I try to launch a default new solution in my iPad, the **Hot Restart** window gives me the message `There was an error while trying to automatically provision the project, please check the logs` (where are those logs?).
This happens with:
-MAUI Blazor Apps
-MAUI Apps
-Xamarin Apps
-in fact, every project that tries to run in iOS.
A couple of months ago, I didn't have this problem.

I also have Visual Studio (not preview) in the same machine and it runs iOS Xamarin projects normally in my iPad. So, it is not an issue with my iPad Air 3rd gen. 15.4.1.

I wonder if this problem is not MAUI specific, but broader, because it also affects Xamarin projects.

### Steps to Reproduce

Create a new MAUI Blazor App, or MAUI App or Xamarin Mobile App, select `Local iOS Device >> (You Device)` and run.

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Release Candidate 1

### Affected platforms

iOS

### Affected platform versions

iOS 15.4.1

**Comment by ltemimi** [comment] 2022-05-21 15:31
I have had that issue since preview 14 I am stuck and unable to use IOS.

**Comment by FelipeCostaGualberto** [comment] 2022-05-21 21:03
> I have had that issue since preview 14 I am stuck and unable to use IOS.

I have a Mac, it works with iOS simulator, tough. This affects only local devices.

**Comment by jfversluis** [comment] 2022-05-23 08:10
Duplicate of #6123

**Closed by jfversluis** 2022-05-23 08:10 UTC
Labels: t/bug, s/needs-verification
