### ISSUE TITLE
The RealParent on XXX has been Garbage Collected

### ISSUE THREAD

**Issue by mmiller-d8** [dotnet/maui#23691] opened 2024-07-18 18:32 UTC
### Description

On Maui for iOS, I've started getting an exception thrown on a physical device.  The error text is:

The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui

This is happening in a couple of different places.  One is directly on a page and the other is in a ContentView.  One occurrence is with RoundRectangle.  The other is with an image in an Image control.

Today is the first time I've seen the error, but I haven't run it on a physical device for a few weeks.  I do believe that I've upgraded Maui.Controls and maybe even .net since then.

I'm not noticing any adverse effects in the app yet, but this is being logged to Sentry.  As best I can tell, the error is being thrown from ElementTemplate.CreateContent

### Steps to Reproduce

I really don't know how to reproduce it.  I just have markup on a page.  I'm not seeing this on the simulator.

### Version with bug

8.0.70 SR7

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.40 SR5

### Affected platforms

I was *not* able test on other platforms

### Affected platform versions

iOS 17

**Comment by mmiller-d8** [comment] 2024-07-18 18:35
These do not look like they are the same issue as the AI suggestions.

**Comment by PureWeen** [comment] 2024-07-19 00:40
Duplicate of #23050

@mmiller-d8 can you just post some snippets of your XAML where you think this is happening to the issue I've linked above?

**Closed by PureWeen** 2024-07-19 00:40 UTC
Labels: t/bug
