### ISSUE TITLE
Breakpoints do not work when debugging configuration other than Debug

### ISSUE THREAD

**Issue by jump32** [dotnet/maui#20132] opened 2024-01-24 14:08 UTC
### Description

When building a configuration named other than 'Debug' breakpoints no longer appear to work. This is despite the fact that the configuration should be a debug configuration.

Additional notes:

Despite the use of VS Code in the repo steps below, we see similar behaviour in Rider. Suggesting that the IDE is not the source of the issue.

### Steps to Reproduce

1. Download example repo project.
2. Open is VS Code
3. Debug the 'Debug' configuration on an iOS simulator
4. Set a breakpoint on MainPage.xaml.cs - OnCounterClicked
5. Click on the 'Click Me' button in the app and observe the breakpoint being hit

Then:

6. Change the configuration to 'Broken'
7. Debug the app again
8. App will run
9. Click on the 'Click Me' button but the breakpoint no longer gets triggered

### Link to public reproduction project repository

https://github.com/jump32/maui-app-debug-issue/tree/main

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

VS Code with latest Dev Kit extensions. Xcode 15.1.0, iOS 17.2 on iPhone simulator

### Did you find any workaround?

None found so far.

**Comment by jump32** [comment] 2024-01-24 17:22
There appears to be a workaround to this issue. The workaround is to add a specific property to the configuration in a property group.
`<PropertyGroup Condition=" '$(Configuration)' == 'Broken' ">
        <_BundlerDebug>true</_BundlerDebug>
    </PropertyGroup>`

Referencing this link for the workaround:
https://developercommunity.visualstudio.com/t/Can-not-deploy-iOS-simulator-build-in-al/10327626?q=Show+html+generated+in+build+pipeline+on+Dashboard

This is however, just a workaround, and should ultimately be fixed in either MAUI or .NET

**Comment by GalaxiaGuy** [comment] 2024-01-26 12:32
I am now getting similar behavior on that sample app if I try Android (I just changed the .csproj to have `<TargetFrameworks>net8.0-ios;net8.0-android</TargetFrameworks>`.

In `Debug`, it launches and hits breakpoints, in `Broken` it launches, but does not breakpoints.

`<_BundlerDebug>true</_BundlerDebug>` has no effect.

**Comment by GalaxiaGuy** [comment] 2024-01-26 18:50
Although I accept this may not be the correct repo to find a fix, I don't think it is a problem with Visual Studio. Neither Visual Studio nor Visual Studio for Mac were used, just VS Code and Rider.

After searching for `_BundlerDebug`, I would guess the Xamarin iOS repo might be the actual source based on:

https://github.com/xamarin/xamarin-macios/blob/c548f80a4da49917cacbb42000af964860af44b1/msbuild/Xamarin.Shared/Xamarin.Shared.props#L229

https://github.com/xamarin/xamarin-macios/blob/c548f80a4da49917cacbb42000af964860af44b1/dotnet/targets/Xamarin.Shared.Sdk.targets#L108

**Comment by AllenD-MSFT** [comment] 2024-01-30 17:22
We've looked into the code in our MAUI DevKit extension and found the root cause there. I suspect that other tools may also have similar issues with configuration handling. Likely Rider has a similar bug that MAUI DevKit has.

**Comment by AllenD-MSFT** [comment] 2024-03-04 17:48
FYI: This issue has been fixed in MAUI DevKit (.NET MAUI Extension for VS Code). I'm leaving the issue open since there are indications that this problem is also occurring with other tools which may be indicative of a problem deeper in the tech stack, but may also simply be duplicate bugs in other tools.

**Closed** 2024-04-22 17:17 UTC
Labels: t/bug, area/tooling ⚙️, platform/iOS 🍎, s/move-to-vs-feedback, migration-compatibility
