### ISSUE TITLE
Empty View not showing

### ISSUE THREAD

**Issue by 99067718** [dotnet/maui#10146] opened 2022-09-15 14:58 UTC
### Description

My empty view is not showing on android, but it is on windows.
Is there a way to make it visible on both?

Android view:
![image](https://user-images.githubusercontent.com/89968831/190436801-b65bf7da-96a1-4718-8cb6-d82e4e3c0e9f.png)

Windows view:
![image](https://user-images.githubusercontent.com/89968831/190437067-ddf6179c-601c-402a-8834-8fa3d0994f31.png)

They are supposed to both be the same, but it doesn't look like its happening

Code:
![image](https://user-images.githubusercontent.com/89968831/190437342-4bdf29bc-58d6-4fa9-a717-b27df6635e21.png)

### Steps to Reproduce

I don't know, sorry

### Link to public reproduction project repository

Sorry, I'm not allowed to share this repository

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 11 (Samsung galaxy A52 S)

### Did you find any workaround?

No

### Relevant log output

```shell
There is no log output, It just doesn't show up.
```

**Comment by hartez** [comment] 2022-09-15 18:52
Duplicate of #8934

**Closed by hartez** 2022-09-15 18:52 UTC
Labels: t/bug, platform/android 🤖, area/collectionview 📃

**Comment by 99067718** [comment] 2022-09-16 07:22
> Duplicate of #8934

This isn't a duplicate, the other person has the <Collectionview.header> bug.
that's not what's happening in my case since I don't have that implemented into it.
