### ISSUE TITLE
[UITest] AutomationId not being set in Shell Tabbar

### ISSUE THREAD

**Issue by bcaceiro** [dotnet/maui#19328] opened 2023-12-11 06:34 UTC
### Description

With a Shell App, I am writing UITests, with NUnit + Appium ( per documentation), however, using Shell Tabbar I cannot navigate to each tab using AutomationId

Example:

```
<Shell x:Class="XXX.XXX.XXXl"
       xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
       xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
       Title="Test"
       Shell.FlyoutBehavior="Disabled">

    <TabBar>
        <Tab Title="Home">
            <Tab.Icon>
                <FontImageSource FontFamily="FARegular" Glyph="{x:Static styles:IconHelper.House}" />
            </Tab.Icon>
            <ShellContent Title="Home"
                          ContentTemplate="{DataTemplate pages:HomePage}"
                          Route="HomePage" />
        </Tab>

        <Tab Title="Orders" AutomationId="OrdersTabBtn">
            <Tab.Icon>
                <FontImageSource FontFamily="FARegular" Glyph="{x:Static styles:IconHelper.CartShopping}" />
            </Tab.Icon>
            <ShellContent Title="Orders"
                          AutomationId="OrdersTabBtn2"
                          ContentTemplate="{DataTemplate pageOrder:MyOrdersPage}"
                          Route="MyOrders" />
        </Tab>

    </TabBar>


</Shell>
```

It seems that it is setting the Title and not the AutomationId ( however I cannot find the element even by Title)

### Steps to Reproduce

1. New dotnet maui App, with Shell
2. Set up an AutomationId to a TabBar page
3. UI Test -> find AutomationId from TabBar and try to click, it cannot find the correct element

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android API 33

### Did you find any workaround?

No workaround - I tried finding element by Title and it does not work.

Haven't tried in iOS yet.

**Comment by bcaceiro** [comment] 2023-12-11 06:38
More info: I found this: https://github.com/xamarin/Xamarin.Forms/issues/1529

From Xamarin.Forms days -seems like the same issue?

My question for the Team, in your UI Tests how to you test Shell? ( Tabs, and perhaps Flyouts?)

**Comment by PureWeen** [comment] 2023-12-12 19:22
Duplicate of #3996

With Xamarin.UITest we used the Text of the tabs to switch between them. Currently all our shell tests run as on device tests not using appium.

**Closed by PureWeen** 2023-12-12 19:22 UTC
Labels: t/bug, area/shell 🐢, area/testing, legacy-ui-test

**Comment by bcaceiro** [comment] 2023-12-12 19:34
@PureWeen so there is no way atm I can use UItesting with automationids and appium?
