### ISSUE TITLE
.Maui Static Web Asset Build issue

### ISSUE THREAD

**Issue by tripiod8** [dotnet/maui#10106] opened 2022-09-14 01:46 UTC
### Description

Severity	Code	Description	Project	File	Line	Suppression State
Error		Manifest file at 'obj\Debug\net6.0-android\android-x86\staticwebassets.build.json' not found.	MauiApp3	C:\Program Files\dotnet\sdk\6.0.401\Sdks\Microsoft.NET.Sdk.Razor\targets\Microsoft.NET.Sdk.Razor.StaticWebAssets.targets	680	

I am struggling to get the Android application working. My Windows form will build but I receive the above error for arm, arm-64, and x86-64 as well. I just hit create project and try running right after with no changes.

My android SDK should be correctly matching. I have the 31.2.1 Android emulator and Android 11.0 (API 30) O.S. The emulator I create is the Pixel 5 11.0 Android.

### Steps to Reproduce

Create new project
Run Android

### Link to public reproduction project repository

./

### Version with bug

6.0.400

### Last version that worked well

6.0.400

### Affected platforms

Android

### Affected platform versions

Android 11.0 (API 30)

**Comment by samhouts** [comment] 2022-09-15 00:48
Duplicate of #10102

**Closed by samhouts** 2022-09-15 00:48 UTC
Labels: t/bug, platform/android 🤖, area/blazor 🕸️
