### ISSUE TITLE
iOS hot reload not working

### ISSUE THREAD

**Issue by borrmann** [dotnet/maui#18498] opened 2023-11-03 09:09 UTC
### Description

Currently I can't use Hot Reload at all for iOS development. 
Without 

```
<MtouchLink>SdkOnly</MtouchLink>
<MtouchExtraArgs>$(MtouchExtraArgs) --weak-framework=NewsstandKit</MtouchExtraArgs>
```

The app crashes at startup.
Without 
```
<MtouchLink>None</MtouchLink>
```
Hot Reload is not supported.

### Steps to Reproduce

1. Try hot reload on an iOS project

### Link to public reproduction project repository

*

### Version with bug

7.0.96

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

any iOS

### Did you find any workaround?

No

**Comment by PureWeen** [comment] 2023-11-03 15:10
@drasticactions @chabiss  thoughts?

**Comment by drasticactions** [comment] 2023-11-03 15:59
The linker setting is specially called out in the documentation:

https://learn.microsoft.com/en-us/dotnet/maui/xaml/hot-reload?tabs=vswin

"Then, on iOS in your build settings, check that the Linker is set to "Don't Link"."

That is necessary, as the linker being off and the Mono Interpreter being on are required for XAML / C# Hot Reload to work correctly. That has been the case since Xamarin.Forms and hasn't changed.

**Comment by borrmann** [comment] 2023-11-03 17:23
@drasticactions sorry, I edited the report as I accidentally put  `<MtouchLink>SdkOnly</MtouchLink>` in both lines although it should have been don't link in the second case.

Don't Link currently does not work, because then NewsstandKit is referenced and causes the App to crash on Startup.

**Comment by drasticactions** [comment] 2023-11-03 17:34
Hot Reload requires that the linker is off. It not working if you turn it on is expected behavior. If you can’t turn it off because of other issues, then you can’t use hot reload.

**Comment by borrmann** [comment] 2023-11-04 00:51
@drasticactions well yes exactly, this is why I reported hot reload is currently not supported on iOS. Maybe the choice of the title was a bit unclear.

Anyways, I believe this will be fixed with https://github.com/dotnet/maui/releases/tag/8.0.0-rc.2.9511 as the new Xamarin iOS packages are referenced that allow Xcode 15 support and should fix the newsstand issues according to the xamarin iOS repo.

Will this also work on .NET 7?

**Comment by drasticactions** [comment] 2023-11-04 02:28
> @drasticactions well yes exactly, this is why I reported hot reload is currently not supported on iOS. Maybe the choice of the title was a bit unclear.

Hot Reload not working on iOS with the Linker on is not a bug, it's a known limitation. It's documented and shown in UI. That something else is causing you to need to set the linker on is unfortunate, but this isn't an issue with Hot Reload that can be solved.

As for Xcode 15 / Newsstand stuff in general and what gets fixed where, I don't know. @dalexsoto do you know where Xcode updates are landing?

I'm closing this issue as there is nothing to address with Hot Reload specifically.

**Closed by drasticactions** 2023-11-04 02:28 UTC
Labels: t/bug, platform/iOS 🍎, Area: UI\Runtime\Hot Reload
