### ISSUE TITLE
Using `Tab` in a `FlyoutItem` cuts off underlying `ContentPage`

### ISSUE THREAD

**Issue by AndreasReitberger** [dotnet/maui#9381] opened 2022-08-12 14:53 UTC
### Description

In my `AppShell` I'm using a `Tab` child for a `FlyoutItem`.
However this cuts off the `ContentPage` which is nested in the tabs.

```xaml
<!-- Dashboard -->
    <FlyoutItem
        Title="{x:Static localization:Strings.Dashboard}"
        >
        <FlyoutItem.Icon>
            <FontImageSource
                FontFamily="{StaticResource MaterialDesignIcons}"
                Glyph="{StaticResource MaterialDesign_ViewDashboardOutline}"
                Color="{DynamicResource PrimaryColor}"
                Size="{StaticResource DefaultIconSize}"
                />
        </FlyoutItem.Icon>
        <Tab
            Title="{x:Static localization:Strings.Dashboard}"
            Route="Dashboard"
            >
            <ShellContent 
                Title="{x:Static localization:Strings.Dashboard}" 
                ContentTemplate="{DataTemplate views:DashboardPage}"
                Route="DashboardPage"
                >
                <ShellContent.Icon>
                    <FontImageSource
                    FontFamily="{StaticResource MaterialDesignIcons}"
                    Glyph="{StaticResource MaterialDesign_ViewDashboardOutline}"
                    Color="{DynamicResource PrimaryColor}"
                    Size="{StaticResource DefaultIconSize}"
                    />
                </ShellContent.Icon>
            </ShellContent>
            <ShellContent 
                Title="{x:Static localization:Strings.HeadlineMacros}" 
                ContentTemplate="{DataTemplate views:QuickCommandsPage}"
                Route="QuickCommandsPage"
                >
                <ShellContent.Icon>
                    <FontImageSource
                    FontFamily="{StaticResource MaterialDesignIcons}"
                    Glyph="{StaticResource MaterialDesign_Send}"
                    Color="{DynamicResource PrimaryColor}"
                    Size="{StaticResource DefaultIconSize}"
                    />
                </ShellContent.Icon>
            </ShellContent>
        </Tab>
    </FlyoutItem>
```
I marked the area yellow in the screenshot below.

![image](https://user-images.githubusercontent.com/2952443/184381341-67afb9a6-1c22-402a-8dbf-ea7a96c59de6.png)

### Steps to Reproduce

1. Create an `Shell` MAUI application and add a `Tab` child to a `FlyoutItem`
2. Add some content to the page
3. See the cut off on top of the page.

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, I was *not* able test on other platforms

### Affected platform versions

iOS 15.5

**Comment by Hottemax** [comment] 2023-02-07 07:35
Seeing the same on iOS. It is fine on Android.

**Comment by pjcollins** [comment] 2023-08-14 17:43
I'm resolving this as a duplicate of https://github.com/dotnet/maui/issues/8778.

**Closed by pjcollins** 2023-08-14 17:43 UTC
Labels: t/bug, area/layout 🔲

**Comment by samhouts** [comment] 2023-08-16 17:06
Duplicate of #8778
