### ISSUE TITLE
[Bug] Cursor Position wrong in Entry field when using IValueConverter

### ISSUE THREAD

**Issue by devonuto** [dotnet/maui#6948] opened 2022-05-09 12:07 UTC
### Description

I have a page created with a number of entry fields which are formatted as either dollars, or percentages. When editing the value, once the new string has been formatted and returned to the field, the caret switches to the front of the entry field, making it unusable. See repo/gif at end

Same ivalueconverter method works in Xamarin.

### Steps to Reproduce

1. Add Entry field to page
2. Bind entry field to value and converter
3. Alter the value in the entry field

See https://github.com/devonuto/MauiBugs/tree/master/FormattingBug

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

net6.0-android 32

### Did you find any workaround?

Tried using this workaround on text changed event, but didn't work

    private void Entry_TextChanged(object sender, TextChangedEventArgs e)
    {
        var entry = sender as Entry;
        entry.CursorPosition = entry.Text.Length;
    }

### Relevant log output

![qemu-system-x86_64_6iH86GbTfO](https://user-images.githubusercontent.com/3507808/167406775-fc2cdd52-9e53-4133-864f-300c2a77e294.gif)

**Comment by Redth** [comment] 2022-05-09 14:09
@SotoiGhost is this related to the other issues / PR's you've been looking at?

**Comment by SotoiGhost** [comment] 2022-05-09 16:02
@Redth Yes, seems to be the same issue I'm looking at. Closing this as duplicate of #6916

**Closed by SotoiGhost** 2022-05-09 16:02 UTC
Labels: t/bug, area/controls 🎮, control-entry, s/needs-verification
