### ISSUE TITLE
BackButtonBehavior IconOverride does not work on Windows

### ISSUE THREAD

**Issue by cdavidyoung** [dotnet/maui#13107] opened 2023-02-03 14:33 UTC
### Description

This works on Android but not on Windows.  If you run this app and select the Bodies tab and then select one of the bodies like Earth, it navigates to a new page.  On Android the back button changes to a comet.  On Windows the back button is the standard back arrow.

https://github.com/MicrosoftDocs/mslearn-dotnetmaui-create-multi-page-apps

I have verified that the other properties of BackButtonBehavior like Command work fine on both platforms.

### Steps to Reproduce

See Description

### Link to public reproduction project repository

https://github.com/MicrosoftDocs/mslearn-dotnetmaui-create-multi-page-apps

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

net6.0-windows10.0.19041.0

### Did you find any workaround?

No.  I tried different combinations of icon types and Buid Action.  MauiImage works in this project on Android.

### Relevant log output

```shell
PS C:\Users\charl> dotnet workload list

Installed Workload Id      Manifest Version       Installation Source
---------------------------------------------------------------------
maui                       7.0.59/7.0.100         SDK 7.0.100
runtimes-windows           7.0.2/7.0.100          VS 17.5.33103.201
maui-windows               7.0.59/7.0.100         VS 17.5.33103.201
maui-maccatalyst           7.0.59/7.0.100         VS 17.5.33103.201
maccatalyst                16.2.1007/7.0.100      VS 17.5.33103.201
maui-ios                   7.0.59/7.0.100         VS 17.5.33103.201
ios                        16.2.1007/7.0.100      VS 17.5.33103.201
maui-android               7.0.59/7.0.100         VS 17.5.33103.201
android                    33.0.26/7.0.100        VS 17.5.33103.201
```

**Comment by jfversluis** [comment] 2023-02-03 15:01
Duplicate of #1625

**Closed by jfversluis** 2023-02-03 15:01 UTC
Labels: t/bug
