### ISSUE TITLE
[regression/8.0.0-preview.1.7762] Placeholder text issues MacCatalyst & iOS

### ISSUE THREAD

**Issue by SamuelJames101** [dotnet/maui#16656] opened 2023-08-10 07:09 UTC
### Description

If you look at the screen shot you'll see the placeholder text is cut off, miss aligned and has different font size to normal text. I see there is a fix for incorrect size (https://github.com/dotnet/maui/issues/15750) but not sure about the other bits.

Place holder (Should say "I am a place holder") :
![Screenshot 2023-08-09 at 14 27 54](https://github.com/dotnet/maui/assets/44027336/2c22b0ad-8f55-4182-89cc-b2623f5c91b6)

Normal text:
![Screenshot 2023-08-09 at 14 28 05](https://github.com/dotnet/maui/assets/44027336/8c362adc-dc3f-4d87-aea1-b45092705bc9)

Repo: 
(Repo was created for a separate bug but you still can see the issue in it)

### Steps to Reproduce

1. Create an editor
2. Add place holder text

Expected result
Place holder is aligned, has the same font size as the entered text and is not cut off.

Actual result
Can't make out the first letter off the place holder, its higher and smaller than the entered text.

### Link to public reproduction project repository

https://github.com/SamuelJames101/EditorAndEntryBugNet8

### Version with bug

[8.0.0-preview.1.7762](https://github.com/dotnet/maui/releases/tag/8.0.0-preview.1.7762)

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.92

### Affected platforms

iOS, macOS

**Comment by AnnYang01** [comment] 2023-08-22 06:46
Verified this on Visual Studio Enterprise 17.8.0 Preview 1.0 using below Project (.NET 8.0), This issue repro on iOS 16.4, not repro in Android 13.0-API33 and Windows 11 .
[MauiApp8.zip](https://github.com/dotnet/maui/files/12405594/MauiApp8.zip)
iOS 16.4
![image](https://github.com/dotnet/maui/assets/131441429/1a9cc9d0-6f81-4f0b-8bf4-b164a25853f1)
Android 13.0-API33
![image](https://github.com/dotnet/maui/assets/131441429/856dbd8d-b042-4e73-b64d-6b30c17fb16c)
Windows 11
![image](https://github.com/dotnet/maui/assets/131441429/645d26a8-a782-4d8b-9ccf-8c77725dcd14)

**Comment by samhouts** [comment] 2023-08-28 17:00
Duplicate of #16916

**Comment by samhouts** [comment] 2023-09-06 00:11
Hi Sam here....

Verified that this is a regression in 8.0.0-preview.1.7762. Does not repro in 7.0.92.

https://github.com/dotnet/maui/compare/7.0.92...8.0.0-preview.1.7762

**Comment by samhouts** [comment] 2023-09-06 00:20
Looks sus https://github.com/dotnet/maui/pull/13140

**Comment by jfversluis** [comment] 2023-09-19 10:48
Hello Sams! But especially @SamuelJames101 are you able to test the latest version? Because I have a bit of trouble reproducing this, but truth be told, also with the preview1 version that you mention. Would you be able to retest this on your side?

**Comment by jsuarezruiz** [comment] 2023-09-25 09:37
I have done a quick test with the current net8 branch (upcoming rc2) and cannot reproduce it.
<img width="548" alt="Captura de pantalla 2023-09-25 a las 11 36 06" src="https://github.com/dotnet/maui/assets/6755973/7b1be0a8-9db3-4168-ab45-eeda14f6d5f0">

**Comment by SamuelJames101** [comment] 2023-09-26 14:47
I can no longer see the issue on iOS RC-1.
I can't test on mac as I am getting "The application has not been built" since updating to rc-1

**Comment by jfversluis** [comment] 2023-09-27 12:57
> The application has not been built

This sounds like you need some deleting of obj/bin folders and doing some rebuilding and is at least not related to this issue. Closing this one for now, thanks!

**Closed by jfversluis** 2023-09-27 12:57 UTC
Labels: t/bug, platform/macOS 🍏, platform/iOS 🍎, area/controls 🎮, s/verified, control-entry, s/triaged, s/needs-attention, i/regression, control-editor
