### ISSUE TITLE
Selecting all the text on a entry for iOS causes crash

### ISSUE THREAD

**Issue by RonnyRos** [dotnet/maui#10228] opened 2022-09-20 21:35 UTC
### Description

Selecting all the text on a entry causes crash on iOS 16, but not previous versions.
You select all by long pressing.

### Steps to Reproduce

Use a iPhone 14 Pro simulator.
Use VS For Mac Preview with .NET 7 RC 1.
Create a new MAUI app template adding a simple Entry with random text into the existing demo page with the dotnet bot.
Highlight the text / try to select all text. 

### Exception output

Objective-C exception thrown.  Name: NSInvalidArgumentException Reason: -[<_UIObscurableTextContentStorage: 0x6000033602d0> offsetFromLocation:toLocation:] received invalid locations 0 (null)
Native stack trace:
	0   CoreFoundation                      0x00007ff800427378 __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007ff80004dbaf objc_exception_throw + 48
	2   CoreFoundation                      0x00007ff800427256 -[NSException initWithCoder:] + 0
	3   UIFoundation                        0x00007ff8045e9608 -[NSTextContentStorage offsetFromLocation:toLocation:] + 287
	4   UIKitCore                           0x0000000114953434 -[_UITextKit2LayoutController offsetFromPosition:toPosition:] + 234
	5   UIKitCore                           0x0000000115384b18 -[UITextInputController offsetFromPosition:toPosition:] + 85
	6   UIKitCore                           0x0000000115353de9 -[UIFieldEditor offsetFromPosition:toPosition:] + 93
	7   UIKitCore                           0x000000011536f6bc -[UITextField offsetFromPosition:toPosition:] + 93
	8   libxamarin-dotnet-debug.dylib       0x000000010231f50c xamarin_dyn_objc_msgSendSuper + 220
	9   ???                                 0x00000001182adca7 0x0 + 4700429479
	10  libmonosgen-2.0.dylib               0x0000000102ae5c4a ves_pinvoke_method + 474
	11  libmonosgen-2.0.dylib               0x0000000102ad8aa9 interp_exec_method + 3737
	12  libmonosgen-2.0.dylib               0x0000000102ad6253 interp_runtime_invoke + 259
	13  libmonosgen-2.0.dylib               0x00000001028fb0a8 mono_runtime_invoke_checked + 136
	14  libmonosgen-2.0.dylib               0x00000001028fed1e mono_runtime_invoke + 142
	15  libxamarin-dotnet-debug.dylib       0x0000000102316600 xamarin_invoke_trampoline + 6320
	16  libxamarin-dotnet-debug.dylib       0x000000010231e089 xamarin_arch_trampoline + 105
	17  libxamarin-dotnet-debug.dylib       0x000000010231f26e xamarin_x86_64_common_trampoline + 118
	18  UIKitCore                           0x000000011531ddd1 -[UITextSelection commit] + 243
	19  UIKitCore                           0x0000000114e03364 -[_UIKeyboardTextSelectionController setSelectedTextRange:] + 269
	20  UIKitCore                           0x0000000114e0555f -[_UIKeyboardTextSelectionController selectPositionAtPoint:granularity:completionHandler:] + 649
	21  UIKitCore                           0x00000001152e29f8 -[UITextSelectionInteraction tappedToPositionCursorWithGesture:atPoint:granularity:completionHandler:] + 312
	22  UIKitCore                           0x00000001152e2793 -[UITextSelectionInteraction _checkForRepeatedTap:gestureLocationOut:] + 1277
	23  UIKitCore                           0x00000001152e3235 -[UITextSelectionInteraction _handleMultiTapGesture:] + 1123
	24  UIKitCore                           0x0000000114fa1abf -[UIApplication sendAction:to:from:forEvent:] + 95
	25  UIKitCore                           0x00000001148d95f6 -[UITextMultiTapRecognizer onStateUpdate:] + 169
	26  UIKitCore                           0x00000001149a9d0e -[UIGestureRecognizerTarget _sendActionWithGestureRecognizer:] + 72
	27  UIKitCore                           0x00000001149b36e0 _UIGestureRecognizerSendTargetActions + 100
	28  UIKitCore                           0x00000001149b04fe _UIGestureRecognizerSendActions + 303
	29  UIKitCore                           0x00000001149af8ba -[UIGestureRecognizer _updateGestureForActiveEvents] + 633
	30  UIKitCore                           0x000000011499e508 _UIGestureEnvironmentUpdate + 3840
	31  UIKitCore                           0x000000011499d1ae -[UIGestureEnvironment _updateForEvent:window:] + 844
	32  UIKitCore                           0x0000000114fe8d53 -[UIWindow sendEvent:] + 5282
	33  UIKitCore                           0x0000000114fbc526 -[UIApplication sendEvent:] + 898
	34  UIKitCore                           0x0000000115063444 __dispatchPreprocessedEventFromEventQueue + 9383
	35  UIKitCore                           0x0000000115065b61 __processEventQueue + 8355
	36  UIKitCore                           0x000000011505bfc4 __eventFetcherSourceCallback + 272
	37  CoreFoundation                      0x00007ff800386ebd __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	38  CoreFoundation                      0x00007ff800386dfc __CFRunLoopDoSource0 + 157
	39  CoreFoundation                      0x00007ff8003865f9 __CFRunLoopDoSources0 + 212
	40  CoreFoundation                      0x00007ff800380db3 __CFRunLoopRun + 927
	41  CoreFoundation                      0x00007ff800380637 CFRunLoopRunSpecific + 560
	42  GraphicsServices                    0x00007ff809c0f28a GSEventRunModal + 139
	43  UIKitCore                           0x0000000114f9b425 -[UIApplication _run] + 994
	44  UIKitCore                           0x0000000114fa0301 UIApplicationMain + 123
	45  libmonosgen-2.0.dylib               0x0000000102ae6de0 do_icall + 288
	46  libmonosgen-2.0.dylib               0x0000000102ae5923 do_icall_wrapper + 291
	47  libmonosgen-2.0.dylib               0x0000000102ad8980 interp_exec_method + 3440
	48  libmonosgen-2.0.dylib               0x0000000102ad6253 interp_runtime_invoke + 259
	49  libmonosgen-2.0.dylib               0x00000001028fb0a8 mono_runtime_invoke_checked + 136
	50  libmonosgen-2.0.dylib               0x00000001029030bc do_exec_main_checked + 92
	51  libmonosgen-2.0.dylib               0x0000000102a32132 mono_jit_exec + 354
	52  libxamarin-dotnet-debug.dylib       0x000000010231dee7 xamarin_main + 1927
	53  testapp5                            0x0000000101877064 main + 52
	54  dyld                                0x0000000101fb72bf start_sim + 10
	55  ???                                 0x0000000103d7c52e 0x0 + 4359439662

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 16

**Comment by RonnyRos** [comment] 2022-09-20 21:43
Seems related to this one:
https://github.com/xamarin/xamarin-macios/issues/15677

**Comment by mattleibow** [comment] 2022-09-30 14:25
Duplicate of #10194

**Closed by mattleibow** 2022-09-30 14:25 UTC
Labels: t/bug, platform/iOS 🍎, area/controls 🎮, high, partner/macios
