### ISSUE TITLE
System.Reflection.TargetInvocationException - NaN is not a valid value for width

### ISSUE THREAD

**Issue by mjfara** [dotnet/maui#6168] opened 2022-04-17 03:27 UTC
### Description

Getting the following exception in a Windows App, when adding AdaptiveTriggers to Shell:

System.Reflection.TargetInvocationException - NaN is not a valid value for width

### Steps to Reproduce

1. Add AdaptiveTriggers to Shell
![image](https://user-images.githubusercontent.com/7797049/163698901-4a868a42-3350-453d-89f6-4f5c2265f794.png)

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows SDK 10.0.19041

**Comment by kristinx0211** [comment] 2022-04-18 05:17
verified repro on windows.
`'MauiApp2.exe' (CoreCLR: DefaultDomain): Loaded 'D:\main\MauiApp2\MauiApp2\bin\Debug\net6.0-windows10.0.19041.0\win10-x64\AppX\System.Private.CoreLib.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MauiApp2.exe' (CoreCLR: clrhost): Loaded 'D:\main\MauiApp2\MauiApp2\bin\Debug\net6.0-windows10.0.19041.0\win10-x64\AppX\MauiApp2.dll'. Symbols loaded.
'MauiApp2.exe' (CoreCLR: clrhost): Loaded 'D:\main\MauiApp2\MauiApp2\bin\Debug\net6.0-windows10.0.19041.0\win10-x64\AppX\System.Runtime.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MauiApp2.exe' (CoreCLR: clrhost): Loaded 'D:\main\MauiApp2\MauiApp2\bin\Debug\net6.0-windows10.0.19041.0\win10-x64\AppX\WinRT.Runtime.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MauiApp2.exe' (CoreCLR: clrhost): Loaded 'D:\main\MauiApp2\MauiApp2\bin\Debug\net6.0-windows10.0.19041.0\win10-x64\AppX\System.Runtime.InteropServices.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MauiApp2.exe' (CoreCLR: clrhost): Loaded 'D:\main\MauiApp2\MauiApp2\bin\Debug\net6.0-windows10.0.19041.0\win10-x64\AppX\System.Collections.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MauiApp2.exe' (CoreCLR: clrhost): Loaded 'D:\main\MauiApp2\MauiApp2\bin\Debug\net6.0-windows10.0.19041.0\win10-x64\AppX\System.Collections.Concurrent.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MauiApp2.exe' (CoreCLR: clrhost): Loaded 'D:\main\MauiApp2\MauiApp2\bin\Debug\net6.0-windows10.0.19041.0\win10-x64\AppX\System.Threading.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MauiApp2.exe' (CoreCLR: clrhost): Loaded 'D:\main\MauiApp2\MauiApp2\bin\Debug\net6.0-windows10.0.19041.0\win10-x64\AppX\Microsoft.WinUI.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MauiApp2.exe' (CoreCLR: clrhost): Loaded 'D:\main\MauiApp2\MauiApp2\bin\Debug\net6.0-windows10.0.19041.0\win10-x64\AppX\System.Runtime.CompilerServices.Unsafe.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MauiApp2.exe' (CoreCLR: clrhost): Loaded 'D:\main\MauiApp2\MauiApp2\bin\Debug\net6.0-windows10.0.19041.0\win10-x64\AppX\System.Private.Uri.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MauiApp2.exe' (CoreCLR: clrhost): Loaded 'D:\main\MauiApp2\MauiApp2\bin\Debug\net6.0-windows10.0.19041.0\win10-x64\AppX\System.ObjectModel.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MauiApp2.exe' (CoreCLR: clrhost): Loaded 'D:\main\MauiApp2\MauiApp2\bin\Debug\net6.0-windows10.0.19041.0\win10-x64\AppX\System.ComponentModel.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MauiApp2.exe' (CoreCLR: clrhost): Loaded 'D:\main\MauiApp2\MauiApp2\bin\Debug\net6.0-windows10.0.19041.0\win10-x64\AppX\System.Numerics.Vectors.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MauiApp2.exe' (CoreCLR: clrhost): Loaded 'D:\main\MauiApp2\MauiApp2\bin\Debug\net6.0-windows10.0.19041.0\win10-x64\AppX\System.Security.Cryptography.Algorithms.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MauiApp2.exe' (CoreCLR: clrhost): Loaded 'D:\main\MauiApp2\MauiApp2\bin\Debug\net6.0-windows10.0.19041.0\win10-x64\AppX\System.Security.Cryptography.Primitives.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MauiApp2.exe' (CoreCLR: clrhost): Loaded 'D:\main\MauiApp2\MauiApp2\bin\Debug\net6.0-windows10.0.19041.0\win10-x64\AppX\System.Security.Cryptography.Csp.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MauiApp2.exe' (CoreCLR: clrhost): Loaded 'D:\main\MauiApp2\MauiApp2\bin\Debug\net6.0-windows10.0.19041.0\win10-x64\AppX\System.Linq.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MauiApp2.exe' (CoreCLR: clrhost): Loaded 'D:\main\MauiApp2\MauiApp2\bin\Debug\net6.0-windows10.0.19041.0\win10-x64\AppX\System.Memory.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MauiApp2.exe' (CoreCLR: clrhost): Loaded 'D:\main\MauiApp2\MauiApp2\bin\Debug\net6.0-windows10.0.19041.0\win10-x64\AppX\Microsoft.InteractiveExperiences.Projection.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MauiApp2.exe' (CoreCLR: clrhost): Loaded 'D:\main\MauiApp2\MauiApp2\bin\Debug\net6.0-windows10.0.19041.0\win10-x64\AppX\Microsoft.Maui.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MauiApp2.exe' (CoreCLR: clrhost): Loaded 'D:\main\MauiApp2\MauiApp2\bin\Debug\net6.0-windows10.0.19041.0\win10-x64\AppX\Microsoft.Windows.SDK.NET.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MauiApp2.exe' (CoreCLR: clrhost): Loaded 'D:\main\MauiApp2\MauiApp2\bin\Debug\net6.0-windows10.0.19041.0\win10-x64\AppX\Microsoft.Maui.Controls.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MauiApp2.exe' (CoreCLR: clrhost): Loaded 'D:\main\MauiApp2\MauiApp2\bin\Debug\net6.0-windows10.0.19041.0\win10-x64\AppX\Microsoft.Extensions.DependencyInjection.Abstractions.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MauiApp2.exe' (CoreCLR: clrhost): Loaded 'D:\main\MauiApp2\MauiApp2\bin\Debug\net6.0-windows10.0.19041.0\win10-x64\AppX\Microsoft.Maui.Essentials.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MauiApp2.exe' (CoreCLR: clrhost): Loaded 'D:\main\MauiApp2\MauiApp2\bin\Debug\net6.0-windows10.0.19041.0\win10-x64\AppX\Microsoft.Maui.Controls.Xaml.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MauiApp2.exe' (CoreCLR: clrhost): Loaded 'D:\main\MauiApp2\MauiApp2\bin\Debug\net6.0-windows10.0.19041.0\win10-x64\AppX\Microsoft.Extensions.Configuration.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MauiApp2.exe' (CoreCLR: clrhost): Loaded 'D:\main\MauiApp2\MauiApp2\bin\Debug\net6.0-windows10.0.19041.0\win10-x64\AppX\netstandard.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MauiApp2.exe' (CoreCLR: clrhost): Loaded 'D:\main\MauiApp2\MauiApp2\bin\Debug\net6.0-windows10.0.19041.0\win10-x64\AppX\Microsoft.Extensions.Configuration.Abstractions.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MauiApp2.exe' (CoreCLR: clrhost): Loaded 'D:\main\MauiApp2\MauiApp2\bin\Debug\net6.0-windows10.0.19041.0\win10-x64\AppX\Microsoft.Extensions.Primitives.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MauiApp2.exe' (CoreCLR: clrhost): Loaded 'D:\main\MauiApp2\MauiApp2\bin\Debug\net6.0-windows10.0.19041.0\win10-x64\AppX\System.Xml.ReaderWriter.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MauiApp2.exe' (CoreCLR: clrhost): Loaded 'D:\main\MauiApp2\MauiApp2\bin\Debug\net6.0-windows10.0.19041.0\win10-x64\AppX\System.Private.Xml.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MauiApp2.exe' (CoreCLR: clrhost): Loaded 'D:\main\MauiApp2\MauiApp2\bin\Debug\net6.0-windows10.0.19041.0\win10-x64\AppX\Microsoft.Maui.Graphics.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MauiApp2.exe' (CoreCLR: clrhost): Loaded 'D:\main\MauiApp2\MauiApp2\bin\Debug\net6.0-windows10.0.19041.0\win10-x64\AppX\Microsoft.Extensions.Logging.Abstractions.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MauiApp2.exe' (CoreCLR: clrhost): Loaded 'D:\main\MauiApp2\MauiApp2\bin\Debug\net6.0-windows10.0.19041.0\win10-x64\AppX\System.ComponentModel.TypeConverter.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MauiApp2.exe' (CoreCLR: clrhost): Loaded 'D:\main\MauiApp2\MauiApp2\bin\Debug\net6.0-windows10.0.19041.0\win10-x64\AppX\Microsoft.Maui.Graphics.Win2D.WinUI.Desktop.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MauiApp2.exe' (CoreCLR: clrhost): Loaded 'D:\main\MauiApp2\MauiApp2\bin\Debug\net6.0-windows10.0.19041.0\win10-x64\AppX\Microsoft.Extensions.DependencyInjection.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MauiApp2.exe' (CoreCLR: clrhost): Loaded 'D:\main\MauiApp2\MauiApp2\bin\Debug\net6.0-windows10.0.19041.0\win10-x64\AppX\System.Diagnostics.Tracing.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MauiApp2.exe' (CoreCLR: clrhost): Loaded 'D:\main\MauiApp2\MauiApp2\bin\Debug\net6.0-windows10.0.19041.0\win10-x64\AppX\System.Threading.ThreadPool.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MauiApp2.exe' (CoreCLR: clrhost): Loaded 'D:\main\MauiApp2\MauiApp2\bin\Debug\net6.0-windows10.0.19041.0\win10-x64\AppX\System.Linq.Expressions.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MauiApp2.exe' (CoreCLR: clrhost): Loaded 'D:\main\MauiApp2\MauiApp2\bin\Debug\net6.0-windows10.0.19041.0\win10-x64\AppX\System.Reflection.Emit.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MauiApp2.exe' (CoreCLR: clrhost): Loaded 'Snippets'. 
'MauiApp2.exe' (CoreCLR: clrhost): Loaded 'D:\main\MauiApp2\MauiApp2\bin\Debug\net6.0-windows10.0.19041.0\win10-x64\AppX\Microsoft.Maui.Controls.Compatibility.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MauiApp2.exe' (CoreCLR: clrhost): Loaded 'D:\main\MauiApp2\MauiApp2\bin\Debug\net6.0-windows10.0.19041.0\win10-x64\AppX\System.Reflection.Emit.Lightweight.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MauiApp2.exe' (CoreCLR: clrhost): Loaded 'D:\main\MauiApp2\MauiApp2\bin\Debug\net6.0-windows10.0.19041.0\win10-x64\AppX\System.Reflection.Emit.ILGeneration.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MauiApp2.exe' (CoreCLR: clrhost): Loaded 'D:\main\MauiApp2\MauiApp2\bin\Debug\net6.0-windows10.0.19041.0\win10-x64\AppX\System.Reflection.Primitives.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MauiApp2.exe' (CoreCLR: clrhost): Loaded 'D:\main\MauiApp2\MauiApp2\bin\Debug\net6.0-windows10.0.19041.0\win10-x64\AppX\System.Runtime.Loader.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Exception thrown: 'System.Reflection.TargetInvocationException' in System.Private.CoreLib.dll
An exception of type 'System.Reflection.TargetInvocationException' occurred in System.Private.CoreLib.dll but was not handled in user code
Exception has been thrown by the target of an invocation.

Extracted embedded document "D:\main\MauiApp2\MauiApp2\Microsoft.Maui.Controls.SourceGen\Microsoft.Maui.Controls.SourceGen.CodeBehindGenerator\AppShell.xaml.sg.cs" to "C:\Users\XIEPIN~1\AppData\Local\Temp\.vsdbgsrc\DB4DC087802ADA998B48D22ED9A28CA9E10256D0\AppShell.xaml.sg.cs"
'MauiApp2.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\Microsoft Visual Studio\2022\Preview\common7\ide\PrivateAssemblies\Runtime\Microsoft.VisualStudio.Debugger.Runtime.NetCoreApp.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
`

**Comment by StephaneDelcroix** [comment] 2022-04-22 08:15
this is a layout issue, not a xaml parsing one

**Comment by hartez** [comment] 2022-04-22 23:50
This is a duplicate of #5946. See [this comment](https://github.com/dotnet/maui/issues/5946#issuecomment-1106585975) for the cause.

**Closed** 2022-04-26 13:39 UTC
Labels: t/bug, s/duplicate 2️⃣, area/essentials 🍞, s/verified
