### ISSUE TITLE
Reproducible Crash iOS AOT GlobalizationNative_LoadICUData

### ISSUE THREAD

**Issue by usertoroot** [dotnet/maui#20197] opened 2024-01-27 17:03 UTC
### Description

I am not sure if it should be on runtime or here so this is posted on both (see https://github.com/dotnet/runtime/issues/97599).

iOS app crashes instantly when `SayHello` is called. I have isolated it to the `.ToString()` call on the double object.

MacOS: Sonoma 14.2.1
iOS Swift Deployment Target: 15.2
Xcode: 15.2
Dotnet 8.0.101
o maui-ios 8.0.3/8.0.100
o maui 8.0.3/8.0.100
o mobile-librarybuilder 8.0.1/8.0.100

Here is the stack trace.

![image](https://github.com/dotnet/runtime/assets/129423944/dd34f23d-43eb-473c-a92b-a1f39aeb01df)

Desired behavior:
1. It should not crash
2. The interpreter should not be used when disabled

### Steps to Reproduce

On the C# side

`Program.cs`
```C#
using System;
using System.Runtime.InteropServices;

namespace ManagedProject
{
    unsafe class Program
    {
        [UnmanagedCallersOnly(EntryPoint = nameof(SayHello))]
        public static int SayHello(int a, int b)
        {
            //return ThisFunctionWorks(a, b);
            return (int)ThisFunctionCrashes(a, b);
        }

        public static int ThisFunctionWorks(int a, int b)
        {
            Console.WriteLine($"sum1({a}, {b})");
            return a + b;
        }

        public static double ThisFunctionCrashes(double a, double b)
        {
            Console.WriteLine($"sum2({a}, {b})"); //<- crash on this line (due to .ToString)
            return (double)(a + b);
        }

        public static void Main(string[] args)
        {

        }
    }
}
```

`ManagedProject.csproj`
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>    
    <SelfContained>True</SelfContained>
    <NativeLib>Shared</NativeLib>
    <RunAOTCompilation>True</RunAOTCompilation>
    <ForceFullAOT>True</ForceFullAOT>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <UseInterpreter>False</UseInterpreter>
    <StaticICULinking>True</StaticICULinking>
    <MtouchLink>None</MtouchLink>
  </PropertyGroup>

  <ItemGroup>
    <!-- Preserves the UnmanagedCallersOnly method -->
    <TrimmerRootDescriptor Include="$(MSBuildThisFileDirectory)ILLink.Descriptor.xml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Globalization" Version="4.3.0" />
  </ItemGroup>
</Project>
```

`ILLink.Descriptor.xml`
```xml
<linker>
  <assembly fullname="ManagedProject">
    <type fullname="ManagedProject.Program">
      <method name="SayHello" />
    </type>
  </assembly>
</linker>
```

On the Swift side just a empty SwiftUI project with the following ContentView

```swift
import SwiftUI
import Pan

struct ContentView: View {
    var body: some View {
        VStack {
            Image(systemName: "globe")
                .imageScale(.large)
                .foregroundStyle(.tint)
            Text("Hello, world!")

        }
        .padding()
        .onAppear(perform: {
            let c = SayHello(1, 2)
            print("test \(c)")
        })
    }
}

#Preview {
    ContentView()
}
```

And bridging header `Cs-Bridging-Header.h`
```c
#ifndef Cs_Bridging_Header_h
#define Cs_Bridging_Header_h
int SayHello(int a, int b);
#endif
```

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

**Comment by jkotas** [comment] 2024-01-27 23:35
Duplicate of https://github.com/dotnet/runtime/issues/97599

**Closed** 2024-01-29 11:53 UTC
Labels: t/bug, platform/iOS 🍎
