### ISSUE TITLE
Numeric Keyboard not working with DisplayPromptAsync

### ISSUE THREAD

**Issue by WebGoose** [dotnet/maui#7470] opened 2022-05-25 12:47 UTC
### Description

When you specify Keyboard.Numeric as the keyboard for a Prompt it doesn't work. No characters are displayed in the prompt box and when it closes the value returned is empty. 

If you don't specify numeric keyboard and just use the normal keyboard, it works perfectly 

[NumericKeyboardBug.zip](https://github.com/dotnet/maui/files/8770894/NumericKeyboardBug.zip)

### Steps to Reproduce

use DisplayPromptAsync and specify Keyboard.Numeric as the keyboard parameter. 

See attached sample app -> Click the button for the prompt to appear.

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

### Did you find any workaround?

No. I had to use the normal keyboard for numeric values

**Comment by jsuarezruiz** [comment] 2022-05-25 14:22
Tested on current main branch and cannot reproduce it.

![issue-7470](https://user-images.githubusercontent.com/6755973/170284974-215f42e6-6b95-437b-81e9-34ee32c36611.gif)

Could you try again with GA version?

**Comment by WebGoose** [comment] 2022-05-26 06:44
I think I am actually on the GA version? Is this correct?
![image](https://user-images.githubusercontent.com/5024960/170432909-a2683f0f-318c-49a7-b399-6221b3565e1d.png)

Tested again this morning and still not working.

**Comment by WebGoose** [comment] 2022-05-26 06:53
It works on an emulator but not on my phone (Samsung A31)

**Comment by WebGoose** [comment] 2022-05-30 07:30
Any update / moving this into verified?

**Comment by WebGoose** [comment] 2022-06-03 12:54
@jsuarezruiz Any update on this? I have confirmed with others that this doesn't work on physical device (emulator works fine)

**Comment by jsuarezruiz** [comment] 2022-06-07 10:10
> @jsuarezruiz Any update on this? I have confirmed with others that this doesn't work on physical device (emulator works fine)

I have tested on Poco F2 Pro and it works correctly, I am afraid that it is something particular to take into account with Samsung devices.

**Comment by infrasoft2007** [comment] 2022-07-27 09:30
I have a same problem with a Android 12 Realme GT Master Edition and Visual Studio 17.3.0 Preview 4.0.

**Comment by Archomeda** [comment] 2022-08-07 00:34
I just came across this issue on my Samsung S21 FE where it's also not working. VS 17.3.0 Preview 4.0 here as well

**Comment by marcmognol** [comment] 2022-08-08 13:27
Hi, I do have the same issue with Zebra TC52 device with Android 11.
Keyboard.Telephone is working
Keyboard.Numeric is not working.

**Comment by marcmognol** [comment] 2022-08-23 18:09
Hi,
I notice that this bug is related to culture:
In english, numeric keyboard works.
In french, it doesn't work.

Hope this bug will be fixed soon as it is a blocking point.

**Comment by marcmognol** [comment] 2022-09-12 08:59
Hi,

@jsuarezruiz is it possible to priorize this one in a next servicing release ?

I am trying to upgrade my Xamarin project into MAUI but this one is blocking.

- It is a regression compared to Xamarin
- Based on my knowledge, it is linked to Culture (see my previous comment)

Thank you very much and I am available if you need further informations about this one.

**Comment by aiscrim** [comment] 2022-10-17 13:36
I have the same issue and can confirm what @marcmognol is saying: using the emulator on my pc, which is in English, the numeric keyboard works fine. But on the phone that I'm using for my tests, which is in Spanish, the numeric keyboard appears but tapping any key won't add the numbers to the prompt input. I've tried to set the phone language to English and in that case it works just fine.

**Comment by marcmognol** [comment] 2022-12-13 20:01
Hi,

Any news about this issue?
I just checked with MAUI v7.0.52 and problem still persists.

Thanks

Marc

**Comment by mattleibow** [comment] 2022-12-14 08:22
Duplicate of #11865

**Comment by mattleibow** [comment] 2022-12-14 08:24
Marking this one as a duplicate just because it is older and I confirmed on the other one. It also has a nicer repro.

Marking as a duplicate also makes sure that the scoring/ranking system considers all the comments here and raises that priority.

**Closed** 2022-12-14 08:24 UTC
Labels: t/bug, platform/android 🤖, area/controls 🎮, s/verified

**Comment by marcmognol** [comment] 2022-12-14 18:06
> Marking this one as a duplicate just because it is older and I confirmed on the other one. It also has a nicer repro.
> 
> Marking as a duplicate also makes sure that the scoring/ranking system considers all the comments here and raises that priority. 

Hmmm ok! But please pay attention that the keyboard is working fine in English but not in an other OS language.

Because the issue you mentioned is a little bit different.

This issue is happening in both Release and Debug mode.

Thanks for your support
