### ISSUE TITLE
[iOS] Setting Shell.TabBarIsVisible="False" in navigation page causes content from other pages to display under ShellTab

### ISSUE THREAD

**Issue by iCode5ometimes** [dotnet/maui#22548] opened 2024-05-21 11:49 UTC
### Description

On iOS, when setting Shell.TabBarIsVisible="False" on a ContentPage, breaks the content for other pages. It will be displayed under the ShellTabs.

### Steps to Reproduce

1. Create a new MAUI app.
2. Add a TabBar for the App.
3. Add 3 pages to the app.
4. Add a button on each page to navigate from one page to another.
5. On 2nd page, to see the bug, place an element at the bottom of the page. In the example given, I placed a grid with a different colour.
6. On the last page only, set Shell.TabBarIsVisible="False" in the xaml.
7. Run the app on iOS.
8. Go  from 1st page to the 2nd page.
9. Go from 2nd page to 3rd page where Shell.TabBarIsVisible="False".
10. Go back to 2nd page.

Expected result: the grid or element at the bottom of the 2nd page should be displayed properly.
Actual result: the element at the bottom of the page is displayed under the shell tabs.

https://github.com/dotnet/maui/assets/52663603/8b7265b1-0614-48e9-aaec-fada13c45eb3

### Link to public reproduction project repository

https://github.com/iCode5ometimes/ShellTabBug

### Version with bug

8.0.7 SR2

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 17.2

### Did you find any workaround?

No workaround found

**Comment by PureWeen** [comment] 2024-05-21 18:22
Duplicate of #17390

Workaround here
https://github.com/dotnet/maui/issues/17390#issuecomment-1806046322

**Closed by PureWeen** 2024-05-21 18:22 UTC
Labels: t/bug
