### ISSUE TITLE
0x80070005

### ISSUE THREAD

**Issue by SchneFre** [dotnet/maui#25109] opened 2024-10-06 05:46 UTC
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/run
Operating System: windows

Whenever I run the MAUI app i get the following error on the Windows Machine:
"Das Programm [13060] wurde mit Code 2147942405 (0x80070005) beendet." which translates to:
The program ended with Code 2147942405 (0x80070005) 

According to ChatGPT this means that Access was Denied.
I tried runnning Visual Studio as Admin.
I tried reinstalling Visual Studio 2022.

Im using the newest version of Windows 11 Pro (last checked for updates: 06. Okt. 2024).

Using the android emulator the App starts

**Comment by jfversluis** [comment] 2024-10-06 21:19
Duplicate of #12080

**Comment by jfversluis** [comment] 2024-10-06 21:20
Thanks for your interest in .NET MAUI! Sorry you hit a snag here. The errors coming from WinUI can be a bit cryptic, I closed this one as a duplicate issue. The linked issue described in a lot of detail what might be going on including some ways to fix it. Hope that helps!

Thanks!

**Closed by jfversluis** 2024-10-06 21:19 UTC
Labels: platform/windows 🪟, tutorials
