### ISSUE TITLE
Frame-Switch element with shadow

### ISSUE THREAD

**Issue by Lifehack25** [dotnet/maui#23800] opened 2024-07-24 11:45 UTC
### Description

When doing a frame which is a switch element and put on Frame.Shadow, the GestureRecognizer stops working, So that I can not click the frame to toggle the switch.. 

### Steps to Reproduce

Example:            

<Frame x:Name="MainFrame"
                   Padding="5" 
                   BorderColor="Gray" 
                   CornerRadius="15" 
                   WidthRequest="170" 
                   HeightRequest="70"
                   Margin="0,0,5,0"
                   HasShadow="True">
                <Frame.Shadow>
                    <Shadow Brush="Gold"
                            Offset="0,0"
                            Radius="50"
                            Opacity="1.0" />
                </Frame.Shadow>
                <Frame.Style>
                    <Style TargetType="Frame">
                        <Setter Property="BackgroundColor" Value="DarkGray" />
                        <Style.Triggers>
                            <DataTrigger TargetType="Frame" Binding="{Binding IsToggled}" Value="True">
                                <Setter Property="BackgroundColor" Value="White" />
                            </DataTrigger>
                        </Style.Triggers>
                    </Style>
                </Frame.Style>

### Version with bug

9.0.0-preview.6.24327.7

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android emulator

### Did you find any workaround?

no

**Comment by jfversluis** [comment] 2024-07-31 10:29
You probably want to use a `Border` as also mentioned in #22518. Additionally, `Frame` will be [deprecated](https://github.com/dotnet/maui/pull/23184) and going away. So all the more reason :)

**Comment by jfversluis** [comment] 2024-07-31 10:29
Duplicate of #22518

**Closed by jfversluis** 2024-07-31 10:29 UTC
Labels: t/bug, platform/android 🤖, s/triaged
