### ISSUE TITLE
The command interface for buttons - Command.ChangeCanExecute()

### ISSUE THREAD

**Issue by akhegr** [dotnet/maui#9419] opened 2022-08-14 19:22 UTC
The method call Command.ChangeCanExecute() is explained in the introduced in the guide for buttons in MAUI - link is shown below.
https://docs.microsoft.com/en-us/dotnet/maui/user-interface/controls/button#use-the-command-interface

When you use the code right above the title "Press and release the button".
```C#
MultiplyBy2Command = new Command(
                execute: () =>
                {
                    Number *= 2;
                    ((Command)MultiplyBy2Command).ChangeCanExecute();
                    ((Command)DivideBy2Command).ChangeCanExecute();
                },
                canExecute: () => Number < Math.Pow(2, 10));

            DivideBy2Command = new Command(
                execute: () =>
                {
                    Number /= 2;
                    ((Command)MultiplyBy2Command).ChangeCanExecute();
                    ((Command)DivideBy2Command).ChangeCanExecute();
                },
                canExecute: () => Number > Math.Pow(2, -10));
```

The app is in Windows showing a fine blue button, that changes color from blue to gray, when it reaches the limit.
When you leave the limit again, the button do not change the color, but it is again clickable.

If you reach, the upper limit, and afterwards the lower limit, both buttons are gray, as shown on the picture below.
![image](https://user-images.githubusercontent.com/10374847/184551664-3eead06c-62f7-4902-affe-624f4cf14219.png)

**Comment by jfversluis** [comment] 2022-08-17 08:21
Thanks for the report @akhegr I am not really clear though on what the issue here. Could you maybe elaborate a bit more about what you expect to see and what you're actually seeing? 

Do I understand correctly that the button shows as disabled but it actually isn't disabled? Can you reproduce this outside of this sample code in the docs as well? On which platforms do you see this?

**Comment by akhegr** [comment] 2022-08-18 18:11
From start, both of the buttons are blue and clickable.
When I continuously click on the "Multiply by 2" button, until I reach the limit, the button change color to gray as expected, and is deactivated.
Afterwards, I clicked on the "Divide by 2" button, and the Multiply button is now clickable, but the color do not change.

When you continuously click on the "Divide by 2" button, until it reach its limit, it changes color too, but it neither change back to original color, when it is clickable again.

Furthermore, today, I have updated to the latest released version of Visual Studio, and I am no longer able to run the same project, without making changes.

The project is based on the section "Use the command interface" on the earlier referred page about Buttons in MAUI.

**Comment by Spilchuk** [comment] 2023-03-09 03:04
Also observing this same issue with near identical, just simpler with a toggle. Is there an expected timeline for this fix?

![Toggle](https://user-images.githubusercontent.com/127368829/223905671-9ed95304-cd30-483b-8753-727f686f93e9.gif)

**Comment by Spilchuk** [comment] 2023-03-11 02:58
Because of this, I kind of gave up on having 2 buttons enable and disable each other. Instead, I combined them but now while in one of those states, I just strictly stick with enabling and disabling one, not both.

![Retry1](https://user-images.githubusercontent.com/127368829/224461115-5b1882ac-e703-4e31-a5d8-0bb2a2e92bee.gif)

Here's a snippet of (effectively) the code here:

![image](https://user-images.githubusercontent.com/127368829/224461402-ef158c35-8019-4a8b-ab91-1f126c6f42c4.png)

**Comment by japarson** [comment] 2023-08-31 20:03
> Also observing this same issue with near identical, just simpler with a toggle. Is there an expected timeline for this fix?
> 
> ![Toggle](https://user-images.githubusercontent.com/127368829/223905671-9ed95304-cd30-483b-8753-727f686f93e9.gif) [ ](https://user-images.githubusercontent.com/127368829/223905671-9ed95304-cd30-483b-8753-727f686f93e9.gif) ![Toggle](https://user-images.githubusercontent.com/127368829/223905671-9ed95304-cd30-483b-8753-727f686f93e9.gif) [ ](https://user-images.githubusercontent.com/127368829/223905671-9ed95304-cd30-483b-8753-727f686f93e9.gif)

Can you try to reproduce this issue with the latest version of .NET 8?

**Comment by mattleibow** [comment] 2023-11-01 18:05
This is now fixed in .NET 8 and probably was fixed in https://github.com/dotnet/maui/pull/12488

**Closed by mattleibow** 2023-11-01 18:05 UTC
Labels: t/bug, platform/windows 🪟, area/controls 🎮, control-button, s/needs-attention
