### ISSUE TITLE
The Comma Seperator is disabled on the Samsung Numeric keyboard.

### ISSUE THREAD

**Issue by PrithisIyyappan** [dotnet/maui#22761] opened 2024-05-31 15:43 UTC
### Description

On Samsung devices with Android versions less than 12.0, the comma separator is disabled on the numeric keyboard.

The culture of my device is French "fr-FR", I can't find any way to enter the comma in the entry which uses the numeric keyboard.

Please find the image of the Samsung numeric keyboard below.

![image](https://github.com/dotnet/maui/assets/127313202/501c437e-37f0-48b7-80b5-16d799a7cee5)

### Steps to Reproduce

1. Create a sample with an Entry whose keyboard property is set to numeric.
2. Run the sample on a Samsung device whose Android version must not be greater than 12.
3. You will find the comma operator is disabled.

### Version with bug

8.0.40 SR5

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 12

**Comment by activa** [comment] 2024-05-31 17:05
This has been an issue since the early days of Xamarin Forms. It's only happening on Samsung devices for languages that use "," as the decimal separator. 
We've been trying to find a workaround for a long time, but never found one. In the end, the only thing that we could do was show the regular keyboard instead of the numeric keyboard when the device is a Samsung device:

```
var keyboard = DeviceInfo.Manufacturer.Equals("Samsung", StringComparison.OrdinalIgnoreCase) ? Keyboard.Text : Keyboard.Numeric;
```

**Comment by drasticactions** [comment] 2024-06-03 07:35
I don't think this is a MAUI issue,

https://github.com/flutter/flutter/issues/61175

Going through this history (which includes them referencing original Xamarin.Forms issues on the subject, which also couldn't be fixed... probably because there's nothing in Forms that could be fixed.), it seems specific to Samsung devices and affects any UI framework building on top of it, including building on top of Android directly without any abstraction.

If you build an Android app (in .NET, Java, whatever) without a UI abstraction like MAUI, and implement an numeric input field, if it doesn't let you input the comma, then I think that would show the issue isn't one that could be "fixed" in MAUI. 

@jonathanpeppers What do you think?

**Comment by emilsteen** [comment] 2024-06-05 07:32
As said, this is an issue with older Samsung devices. 
A workaround is to install an alternative keyboard on these devices. I got the numeric keyboard to work by installing Swiftkey on Galaxy S7 (Android 8). And a customer with this issue got it to work by doing a system update on Galaxy S21 (probably from API 33 to API 34).
Galaxy S5 has a keyboard that works with non-dot decimals, but you have to tripple-click the decimal button to get it to work.

**Comment by jfversluis** [comment] 2024-06-21 11:51
I think we've established this is unfortunately out of our control and since its not actionable, I'm closing this here.

**Closed by jfversluis** 2024-06-21 11:51 UTC
Labels: t/bug, platform/android 🤖, area-controls-entry, s/triaged

**Comment by Redth** [comment] 2024-06-21 19:33
Just to confirm, I tried a plain old java android project in android studio, with a samsung device running Android 8.0, and I do see the same behaviour here.  As mentioned here and in linked issues, this appears to be a Samsung limitation and there's not a MAUI specific fix involved here.

One option would be to set the keyboard type to just normal text and handle validating the input yourself.
