### ISSUE TITLE
It is not possible to unfocus an Entry and HideSoftInputOnTapped closes soft keyboard but does not remove focus from Entry

### ISSUE THREAD

**Issue by hansmbakker** [dotnet/maui#21053] opened 2024-03-06 14:01 UTC
### Description

In general it seems not possible to unfocus an `Entry` by using the `tab` key on windows or by clicking somewhere in the page on Windows or by tapping somewhere on the page after adding `HideSoftInputOnTapped="True"` to my `ContentPage`s.
The latter only makes the soft keyboard close when I tap outside an `Entry`.

Actual behavior: the `Entry` stays focused after pressing `tab` / tapping outside the `Entry`. The `Entry` keeps displaying a cursor and it keeps the `Focused` visual state.

Expected behavior: the `Entry` loses focus after pressing `tab` / tapping outside the `Entry`. It removes the cursor and it returns to the `Normal` visual state.

### Steps to Reproduce

1. Create a new MAUI project
2. Replace the main page with an empty page, or empty the main page
3. Add an `Entry` and optionally give it some Focused visual state styling to make the issue more visible
4. Add  `HideSoftInputOnTapped="True"` to the `ContentPage`
5. Run the app
6. Select the `Entry` if needed by tapping / clicking on it
7. Try tapping / clicking outside the `Entry` or try pressing `tab`
8. See that the `Entry` keeps focused

### Link to public reproduction project repository

https://github.com/hansmbakker/bugrepro-no-unfocus

### Version with bug

8.0.7 SR2

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows

### Did you find any workaround?

No

**Comment by maexsp** [comment] 2024-03-14 10:52
Hi. 

Experienced the same problem on Android (iOS works already well out of the box). You can solve this to unfocus and commit the value on an Entry on touch ouside by checking the coordinates within the screen. Works also when the app is in split-mode or popup-window-mode! Most people try to use Android API GetGlobalVisibleRect(outRect) but in MAUI that seems not to work at all. Always returns 0,0,0,0 rect.

BR,
Markus

Put this into the MAUI Android MainActivity.cs
`        public override bool DispatchTouchEvent(MotionEvent? e)
        {
            if (e!.Action == MotionEventActions.Down)
            {
                var focusedElement = CurrentFocus;
                if (focusedElement is EditText editText)
                {
                    var editTextLocation = new int[2];
                    editText.GetLocationOnScreen(editTextLocation);

                    var clearTextButtonWidth = 100; // syncfusion clear button at the end of the control
                    var editTextRect = new Rect(editTextLocation[0], editTextLocation[1], editText.Width + clearTextButtonWidth, editText.Height);
                    //var editTextRect = editText.GetGlobalVisibleRect(editTextRect);  //not working in MAUI, always returns 0,0,0,0
                    var touchPosX = (int)e.RawX;
                    var touchPosY = (int)e.RawY;
                    if (!editTextRect.Contains(touchPosX, touchPosY))
                    {
                        editText.ClearFocus();
                        var inputService = GetSystemService(Context.InputMethodService) as InputMethodManager;
                        inputService?.HideSoftInputFromWindow(editText.WindowToken, 0);
                    }
                }
            }
            return base.DispatchTouchEvent(e);
        }`

**Comment by XamlTest** [comment] 2024-04-08 07:23
Verified this on VS 17.10.0 Preview 2.0(8.0.14). Repro on Windows 11, Android 14.0-API34, MacCatalyst, not repro on iOS 17.2 with below Project:
[21053.zip](https://github.com/dotnet/maui/files/14902214/21053.zip)

**Comment by MrFrawsty** [comment] 2024-04-13 13:58
@maexsp This worked beautifully. Thank you.

**Comment by LeoLamego** [comment] 2024-04-20 16:35
Funcionou muito bem!

**Comment by PauchardThomas** [comment] 2024-04-23 09:57
Same problem !

**Comment by tharindup** [comment] 2024-05-03 12:53
@maexsp works like a charm. Thank you!
Apparently, the compatibility elements call HideSoftInputFromWindow when un-focusing.     https://github.com/dotnet/maui/blob/222ca3ca088d199ff22adde8ca3ae82d9dba0b35/src/Core/src/Platform/Android/ViewExtensions.cs#L713
Although Maui controls backed by EditText show the soft input when focusing, but never hides it when the Element is unfocusing. 
See https://github.com/dotnet/maui/blob/222ca3ca088d199ff22adde8ca3ae82d9dba0b35/src/Core/src/Platform/Android/TextViewExtensions.cs#L128-L138

**Comment by letscodewithkalyan** [comment] 2024-05-08 10:24
https://github.com/dotnet/maui/issues/11881
https://github.com/dotnet/maui/issues/18854
https://github.com/dotnet/maui/issues/19062
https://github.com/dotnet/maui/issues/19032
https://github.com/dotnet/maui/issues/15681

This issues are related same, when we click outside of entry, it is not unfocusing and even also not firing, 
Still MAUI team not fixing this issue. Simply closing all issues.
This issue also will closed with proper solution from MAUI Team
Issue happen on latest Android 14 devices as well.

**Comment by samhouts** [comment] 2024-05-17 01:22
Hi! We understand that this was a behavior change from Xamarin.Forms, but it was an intentional one. We do not consider this to be a bug.

Please see this comment from Rachel on #11881. 

> Hi All,
> 
> In developing .NET MAUI, we learned that it is not possible on earlier versions of Android to unfocus an entry. Some control _must_ always be focused. In Xamarin.Forms, this was approached by setting focus on the page layout; unfortunately, this approach created major accessibility issues. For these reasons, .NET MAUI no longer allows for this behavior by default.
> 
> If this antipattern can be avoided, we highly recommend using a different approach. If it cannot be avoided, we'd love to learn more about your scenario so that we can better understand your development needs! That being said, we do understand the needs from a migration compatibility standpoint, so for those scenarios, there is a [new property that was introduced in .NET 8](https://github.com/dotnet/maui/pull/16530). Using `HideSoftInputOnTapped` should do the trick.

.NET MAUI aims to be as accessible as possible with little interaction from developers, so we will not revert this behavior. Thank you for understanding.

**Comment by samhouts** [comment] 2024-05-17 01:22
Duplicate of #11881

**Closed by samhouts** 2024-05-17 01:22 UTC
Labels: t/bug, platform/android 🤖, partner/cat 😻, s/verified, area-controls-entry, s/triaged, migration-compatibility, area-keyboard
