### ISSUE TITLE
Usability: Too much documentation shown in Visual Studio for Button Type

### ISSUE THREAD

**Issue by srqdev** [dotnet/maui#8163] opened 2022-06-19 14:27 UTC
### Description

So I was changing a BindableProperty typeof statement from button to a new custombutton type. 

`public static readonly BindableProperty ValidValuesProperty =
			BindableProperty.Create(nameof(ValidValues), typeof(List<int>), typeof(Button));`

When I hovered over the Button to next do right click, select and then replace, my screen was blotted out by the help documentation for the button class. It makes it a little difficult to use and is definitely a nuisance.
![2022-06-19](https://user-images.githubusercontent.com/11214013/174485614-17f68145-2ab8-4197-80cd-b0c6044bde95.png)
 

### Steps to Reproduce

1. Open any app with a button declaration in the code.
2. Hover over button.

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Visual Studio 2022 Preview

**Comment by jfversluis** [comment] 2022-06-20 10:16
Is there ever a thing as too much documentation? 😜 You're totally right. We still need to complete our work on the API docs, we're tracking that in #3960 where the long API descriptions is also already mentioned. Closing this one to not duplicate too much.

**Closed by jfversluis** 2022-06-20 10:16 UTC
Labels: t/bug, s/needs-verification

**Comment by samhouts** [comment] 2022-08-22 23:24
Duplicate of #3960
