### ISSUE TITLE
ListView-nested VerticalStackLayout does not resize/expand to reveal unhidden children (IsVisible=true)

### ISSUE THREAD

**Issue by greatoceansoftware** [dotnet/maui#6448] opened 2022-04-23 17:31 UTC
### Description

Running the reproduction project demonstrates that the VerticalStackLayout properly contracts when bound children are hidden (IsVisible is set to false). However, it does not reciprocally expand when bound items are unhidden (IsVisible is set to true) when the layout is nested in a ListView.

Reproduction project is [here](https://github.com/greatoceansoftware/ListView-Nested-VerticalStackLayout-Resizing).

### Steps to Reproduce

1. Build and run the project as Windows Machine.
2. Two views of the same underlying hierachical data structure/source (Phase-> Goals-> Activities) are shown.
3. Click the Declutter switch (ON). The first activity (Activity 1) in the underlying data structure will be hidden.
4. Click the Declutter switch again (OFF). The VerticalStackLayout on the left will properly expand to reveal the hidden Activity.
5. The ListView-nested VerticalStackLayout on the right does not expand (for each goal) to show all five Activities (Activity 5 is clipped for each Goal).
6. Use the Reset button to reset to initial state for testing.

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Windows 10.0.19044 Build 19044

### Did you find any workaround?

No

**Comment by XamlTest** [comment] 2022-04-24 01:25
Verified this issue with Visual Studio Enterprise 17.3.0 Preview 1.0 [32414.199.main]. Repro on Windows with above project.

**Comment by Redth** [comment] 2022-05-03 16:15
Tried a few things including calling ForceUpdateSize() on the ViewCell when the bindable layout changes, but that didn't help.

Basically if you resize the window it all updates correctly.  It seems as though the nested bindable vertical stack layout is not propagating the measure/arrange invalidation when its size changes due to the visibility of its views changing.

**Comment by kristinx0211** [comment] 2022-05-09 06:13
still an issue on windows with 17.3.0 Preview 2.0 [32507.29.main].

**Comment by samhouts** [comment] 2022-05-11 22:22
Still reproduces on 6.0.300-rc.4.5760, too.

**Comment by hartez** [comment] 2022-06-09 22:53
Running this with the latest on main, after setting Declutter back to Off, Activity 5 is now visible in each goal on the right. Might be fixed in SR1, definitely fixed for SR2.

**Closed by hartez** 2022-06-09 22:53 UTC
Labels: t/bug, area/layout 🔲, p/1, s/verified, s/triaged

**Comment by greatoceansoftware** [comment] 2022-06-10 01:24
Thanks!
