### ISSUE TITLE
The Shadow is not offset to the negative side of the X coordinate on the Android platform.

### ISSUE THREAD

**Issue by Arunachalam3641** [dotnet/maui#22422] opened 2024-05-15 10:52 UTC
### Description

The Shadow is not offset to the negative side of the X coordinate on the Android platform. This issue is not reproduced on Windows, iOS, and Mac platforms.  I have attached the results of each platform and sample repository.

Sample repository - https://github.com/Arunachalam3641/ShadowSample

- Android

![image](https://github.com/dotnet/maui/assets/102668599/13126359-ea49-436a-90a9-10a93ef80c4e)

- Windows

![image](https://github.com/dotnet/maui/assets/102668599/485c4a57-dc6d-4ce6-a29e-a8dd339fbc2a)

- Mac

![image](https://github.com/dotnet/maui/assets/102668599/7984ea64-78ac-40e3-acaa-7698665a5672)

- iOS

![image](https://github.com/dotnet/maui/assets/102668599/52dc2184-665a-410e-95bf-181148f41c2b)

### Steps to Reproduce

1. Run the sample on the Android platform.
2. Shadow didn't appear on the negative side of the X coordinate.

Expected result:
The shadow should appear on the negative side of the X coordinate.

### Link to public reproduction project repository

https://github.com/Arunachalam3641/ShadowSample

### Version with bug

8.0.6 SR1

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

**Comment by mattleibow** [comment] 2024-05-15 18:25
Duplicate of https://github.com/dotnet/maui/issues/9539

**Closed by mattleibow** 2024-05-15 18:25 UTC
Labels: t/bug, platform/android 🤖
