### ISSUE TITLE
Wrong XAML error messages using Hot Reload

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#13050] opened 2023-02-01 13:42 UTC
### Description

Creating styles on the fly using Hot Reload results in incorrect  XAML errors messages (sometimes). Indicates that the style does not exist, although it does.

![issue-xaml](https://user-images.githubusercontent.com/6755973/216058418-8c8cdbbb-d670-48bb-b3bc-a142be64d8c0.gif)

### Steps to Reproduce

1. Download or sync https://github.com/jsuarezruiz/netmaui-movies-app-challenge
2. Remove any Border Style.
3. Create it again and assign it using Hot Reload.

### Link to public reproduction project repository

https://github.com/jsuarezruiz/netmaui-movies-app-challenge

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 13

> VS bug [#1760670](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1760670)

**Comment by jsuarezruiz** [comment] 2023-03-07 13:18
Can still reproduce this issue with the latest current version with this sample https://github.com/jsuarezruiz/netmaui-skateboard-ecommerce-app-challenge

![xaml-errors](https://user-images.githubusercontent.com/6755973/223433529-198e5cf1-3ecd-49ea-8ef4-4b3ed36b6f28.PNG)

Reopened the issue.

**Comment by spadapet** [comment] 2023-05-03 23:00
@jsuarezruiz, thanks for the sample projects, I tried both of them in Visual Studio 2022 version 17.5.5 and I couldn't reproduce the bug. Maybe it's been fixed. Can you try to reproduce the bug again? I debugged on both Windows and Android emulator.

I start with:

* ![image](https://user-images.githubusercontent.com/2523431/236068461-00fd6dc4-4d69-45f3-abee-e1e0ee9a2264.png)

Then delete the Image.Style:

* ![image](https://user-images.githubusercontent.com/2523431/236068550-5ca361e4-edc6-4b80-a88e-574a821b7aa9.png)

Then add back the Image.Style:

* ![image](https://user-images.githubusercontent.com/2523431/236068662-5269855c-e344-4eee-ab89-c91a768a86c9.png)

I didn't get a style resource error when bringing back any style.

I'll close this issue, but if you can still reproduce it in 17.5.5 or newer, let me know and reactivate. Thanks!

**Closed by spadapet** 2023-05-03 23:00 UTC
Labels: t/bug, area/tooling ⚙️, s/move-to-vs-feedback, partner/hot-reload-xaml, Area: UI\Runtime\Hot Reload
