### ISSUE TITLE
iOS: svg images only bit color, any toolbar image doesn't resize

### ISSUE THREAD

**Issue by SergTomcat** [dotnet/maui#15728] opened 2023-06-19 12:45 UTC
### Description

On **iOS**, SVG files are interpreted only as bit color after coversion:

<img width="264" alt="image" src="https://github.com/dotnet/maui/assets/24654961/f97a0789-a798-4373-9023-b0de76cb3b92">

at the same time, **Android:**
<img width="254" alt="image" src="https://github.com/dotnet/maui/assets/24654961/13add29a-4c7d-4ca9-a4f1-01d3811171d6">

Also even png images on toolbar is not properly sized (see Shell bottom bar on both pictures)

### Steps to Reproduce

A) For bit color bug:
1. Have any ContentPage
2. Add SVG MauiImage into resourses (e.g. "myicon.svg" )
3. Add

```
<ContentPage.ToolbarItems>
		<ToolbarItem IconImageSource="myicon"/>
</ContentPage.ToolbarItems>
```

into ContentPage from step 1.

B) For size bug:
1. Add PNG MauiImage into resourses (e.g. "monkey.png" )
2. Use it in Shell, Toolbar, etc.
```

<FlyoutItem Route="animals"
                FlyoutDisplayOptions="AsMultipleItems">
<ShellContent Route="monkeys"
                      Style="{StaticResource MonkeysShell}"
                      Title="Monkeys"
                      Icon="monkey.png"
                      Shell.TabBarIsVisible="True"
                      ContentTemplate="{DataTemplate views:MonkeysPage}" />
....
</FlyoutItem>
```

### Link to public reproduction project repository

https://github.com/SergTomcat/MAUI_Bug_Demo

### Version with bug

7.0.86

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 16.4

### Did you find any workaround?

For bad resizing: use 28x28 pics (which is bad, because on different devices you need different sizes, as before you had to create sets of icons @1x, @2x, @3x, etc)

No workaround for bit-color conversion.

**Comment by Eilon** [comment] 2023-06-21 16:45
I vaguely recall that this is simply how iOS works and that those types of icons are always monochrome.

**Comment by XamlTest** [comment] 2023-07-25 06:32
Verified this on Visual Studio Enterprise 17.7.0 Preview 4.0. Repro on iOS 16.4 .NET 8, not repro on Android 13.0-API33 with below Project:
[Xaminals.zip](https://github.com/dotnet/maui/files/12157818/Xaminals.zip)

**Comment by mattleibow** [comment] 2023-11-08 00:47
This has 2 issues:
1. color: this is not supported on iOS. The OS always uses the alpha/transparency and a foreground color
2. size: iOS does not resize and in fact you need to set `BaseSize="x,x"` in the csproj. See also https://github.com/dotnet/maui/issues/11984

**Comment by mattleibow** [comment] 2023-11-08 00:47
Duplicate of https://github.com/dotnet/maui/issues/11984

**Closed by mattleibow** 2023-11-08 00:47 UTC
Labels: t/bug, area/shell 🐢, s/verified, s/triaged
