### ISSUE TITLE
MAUI - CollectionView Pre Select Item background color not change on windows

### ISSUE THREAD

**Issue by Nicole0121** [dotnet/maui#15666] opened 2023-06-15 06:55 UTC
### Description

If we set the `SelectedItem` for CollectionView before loading the page and also set the selected backgroundcolor , the collectionview will not render the background color for the `SelectedItem` for the CollectionView on window, but it works properly on android. 

### Steps to Reproduce

1.download the official sample here : https://github.com/dotnet/maui-samples/tree/main/7.0/UserInterface/Views/CollectionViewDemos
2.Add the following code to  [VerticalListSinglePreSelectionPage.xaml](https://github.com/dotnet/maui-samples/blob/main/7.0/UserInterface/Views/CollectionViewDemos/CollectionViewDemos/Views/Selection/VerticalListSinglePreSelectionPage.xaml)

         <ContentPage.Resources>
        <Style TargetType="Grid">
            <Setter Property="VisualStateManager.VisualStateGroups">
                <VisualStateGroupList>
                    <VisualStateGroup x:Name="CommonStates">
                        <VisualState x:Name="Normal" />
                        <VisualState x:Name="Selected">
                            <VisualState.Setters>
                                <Setter Property="BackgroundColor" 
                                        Value="LightSkyBlue" />
                            </VisualState.Setters>
                        </VisualState>
                    </VisualStateGroup>
                </VisualStateGroupList>
            </Setter>
        </Style>
    </ContentPage.Resources>

Then the whole code will like this:

```
<?xml version="1.0" encoding="UTF-8"?> 
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml" 
             x:Class="CollectionViewDemos.Views.VerticalListSinglePreSelectionPage"
             Title="Vertical list (single pre-selection)">

    <ContentPage.Resources>
        <Style TargetType="Grid">
            <Setter Property="VisualStateManager.VisualStateGroups">
                <VisualStateGroupList>
                    <VisualStateGroup x:Name="CommonStates">
                        <VisualState x:Name="Normal" />
                        <VisualState x:Name="Selected">
                            <VisualState.Setters>
                                <Setter Property="BackgroundColor" 
                                        Value="LightSkyBlue" />
                            </VisualState.Setters>
                        </VisualState>
                    </VisualStateGroup>
                </VisualStateGroupList>
            </Setter>
        </Style>
    </ContentPage.Resources>
    <StackLayout Margin="20">
        <Label Text="{Binding SelectedMonkeyMessage}" />
        <CollectionView ItemsSource="{Binding Monkeys}"
                        SelectionMode="Single"
                        SelectedItem="{Binding SelectedMonkey}"
                        SelectionChangedCommand="{Binding MonkeySelectionChangedCommand}">
            <CollectionView.ItemTemplate>
                <DataTemplate>
                    <Grid Padding="10">
                        <Grid.RowDefinitions>
                            <RowDefinition Height="Auto" />
                            <RowDefinition Height="Auto" />
                        </Grid.RowDefinitions>
                        <Grid.ColumnDefinitions>
                            <ColumnDefinition Width="Auto" />
                            <ColumnDefinition Width="Auto" />
                        </Grid.ColumnDefinitions>
                        <Image Grid.RowSpan="2" 
                               Source="{Binding ImageUrl}" 
                               Aspect="AspectFill"
                               HeightRequest="60" 
                               WidthRequest="60" />
                        <Label Grid.Column="1" 
                               Text="{Binding Name}" 
                               FontAttributes="Bold" />
                        <Label Grid.Row="1"
                               Grid.Column="1" 
                               Text="{Binding Location}"
                               FontAttributes="Italic" 
                               VerticalOptions="End" />
                    </Grid>
                </DataTemplate>
            </CollectionView.ItemTemplate>
        </CollectionView>
    </StackLayout>
</ContentPage>
```

and modify method `MonkeySelectionChanged` in class [MonkeysViewModel.cs](https://github.com/dotnet/maui-samples/blob/main/7.0/UserInterface/Views/CollectionViewDemos/CollectionViewDemos/ViewModels/MonkeysViewModel.cs)

           void MonkeySelectionChanged() 
        {
            if (SelectedMonkey != null) {

                SelectedMonkeyMessage = $"Selection {selectionCount}: {SelectedMonkey.Name}";
                OnPropertyChanged("SelectedMonkeyMessage");
                selectionCount++;
            }

3.deploy the app to windows device and observe the bug.

 We will find that the `SelectedItem` is showing on the top of page `VerticalListSinglePreSelectionPage`,but the `BackgroundColor` is not changed on windows machine.  But on android device, it all works properly.

### Link to public reproduction project repository

https://github.com/dotnet/maui-samples/tree/main/7.0/UserInterface/Views/CollectionViewDemos

### Version with bug

7.0.49

### Last version that worked well

6.0

### Affected platforms

Windows

### Affected platform versions

windows

**Comment by cgtholdingsllc1** [comment] 2023-07-09 23:24
The following code works perfectly for **Android** but not for **iOS**.
`
<CollectionView ItemsSource="{Binding Dates}"
                ItemSizingStrategy="MeasureAllItems"
                VerticalScrollBarVisibility="Always"
                SelectionMode="Single"
                HeightRequest="{OnIdiom Tablet=325, Default=125}"
                Margin="20,0,0,0"
                VerticalOptions="Start">
    <CollectionView.ItemsLayout>
        <GridItemsLayout Orientation="Horizontal"
                         Span="{OnIdiom Default=1, Tablet=2}"
                         HorizontalItemSpacing="5" />
    </CollectionView.ItemsLayout>
    <CollectionView.ItemTemplate>
        <DataTemplate x:DataType="local:AppointmentDateDto">

            <Border Padding="10"
                    StrokeThickness="2"
                    StrokeShape="RoundRectangle 10"
                    HorizontalOptions="Fill"
                    MinimumWidthRequest="100"
                    Margin="0,0,10,0">
                <VisualStateManager.VisualStateGroups>
                    <VisualStateGroup x:Name="CommonStates">
                        <VisualState x:Name="Normal">
                            <VisualState.Setters>
                                <Setter Property="BackgroundColor"
                                        Value="Transparent" />
                                <Setter Property="Stroke"
                                        Value="Silver" />
                            </VisualState.Setters>
                        </VisualState>
                        <VisualState x:Name="Selected">
                            <VisualState.Setters>
                                <Setter Property="BackgroundColor"
                                        Value="{StaticResource BrandColor}" />
                                <Setter Property="Stroke"
                                        Value="{StaticResource BrandColor}" />
                                <Setter TargetName="lblDayWeek"
                                        Property="Label.TextColor"
                                        Value="White" />
                                <Setter TargetName="lblDay"
                                        Property="Label.TextColor"
                                        Value="White" />
                                <Setter TargetName="lblMonth"
                                        Property="Label.TextColor"
                                        Value="White" />
                            </VisualState.Setters>
                        </VisualState>
                    </VisualStateGroup>
                </VisualStateManager.VisualStateGroups>

                <Grid RowDefinitions="Auto,*,Auto">
                    <Label Grid.Row="0"
                           x:Name="lblDayWeek"
                           Text="{Binding DayOfWeek}"
                           HorizontalOptions="Center"
                           VerticalOptions="Start"
                           FontFamily="Roboto" />
                    <Label Grid.Row="1"
                           x:Name="lblDay"
                           Text="{Binding Day}"
                           HorizontalOptions="Center"
                           VerticalOptions="Center"
                           FontFamily="RobotoBold"
                           FontSize="40" />
                    <Label Grid.Row="2"
                           x:Name="lblMonth"
                           Text="{Binding Month}"
                           HorizontalOptions="Center"
                           VerticalOptions="End"
                           FontFamily="Roboto"
                           FontSize="Subtitle" />
                </Grid>
            </Border>

        </DataTemplate>
    </CollectionView.ItemTemplate>
</CollectionView>
`

**Comment by criss02-cs** [comment] 2024-01-07 17:25
same issue

**Comment by PureWeen** [comment] 2024-01-22 15:46
Duplicate of #18933

**Closed by PureWeen** 2024-01-22 15:46 UTC
Labels: t/bug, platform/windows 🪟, area/collectionview 📃
