### ISSUE TITLE
App fails to inject INavigationRootManager when using PushModalAsync

### ISSUE THREAD

**Issue by LucasC-Extreme-IT** [dotnet/maui#25833] opened 2024-11-13 14:45 UTC
### Description

After using the MAUI app for a certain period of time (periods ranging from a few hours to a week and a half based on the tests conducted), the program throws an exception due to an internal dependency injection issue (No service for type 'Microsoft.Maui.Platform.NavigationRootManager' has been registered.).

Our MauiProgram.cs CreateMAUI APP method: 

```cs

           MauiAppBuilder builder = MauiApp.CreateBuilder();
            builder.Logging.ClearProviders();
            builder.Logging.AddNLog();

            builder
                .UseMauiApp<App>()
                .ConfigureFonts(fonts =>
                {
                    fonts.AddFont("OpenSans-Regular.ttf", "OpenSansRegular");
                    fonts.AddFont("OpenSans-Semibold.ttf", "OpenSansSemibold");
                    fonts.AddFont("cour.ttf", "Courier New");
                });

            SetupSerilog();
            builder.Logging.AddSerilog(dispose: true);
            LogManager.Setup().RegisterMauiLog()
                .LoadConfiguration(c => c.ForLogger(NLog.LogLevel.Info).WriteToMauiLog())
                .GetCurrentClassLogger();` 
#If WINDOWS
             builder.ConfigureLifecycleEvents(events =>
            {
                events.AddWindows(windowsLifecycleBuilder =>
                {
                    windowsLifecycleBuilder.OnWindowCreated(window =>
                    {
                        window.ExtendsContentIntoTitleBar = false;
                        window.Closed += (sender, eventArgs) =>
                        {
                            MainPageUtil.CloseApp();
                        };
                        nint handle = WinRT.Interop.WindowNative.GetWindowHandle(window);
                        Microsoft.UI.WindowId id = Microsoft.UI.Win32Interop.GetWindowIdFromWindow(handle);
                        Microsoft.UI.Windowing.AppWindow appWindow = Microsoft.UI.Windowing.AppWindow.GetFromWindowId(id);
                        switch (appWindow.Presenter)
                        {
                            case Microsoft.UI.Windowing.OverlappedPresenter overlappedPresenter:

                                overlappedPresenter.SetBorderAndTitleBar(false, false);
                                overlappedPresenter.IsMaximizable = false;
                                overlappedPresenter.IsMinimizable = false;

                                overlappedPresenter.Maximize();
                                break;
                        }
                    });
                });
            });
```

The error is thrown at random while calling the "PushModalAsync" method on INavigation,  

Example // on MainPage:  

```cs
         MainThread.BeginInvokeOnMainThread(async () =>
         {
                    var modalNav = new FormModal(message);
                    await this.Navigation.PushModalAsync(modalNav);
         }
```

Sometimes we can run the PushModalAsync method for weeks before seeing the error, sometimes it happens in two hours.

**About the App:** 

The application is designed to collect data from the production line in real time, which implies constant activity and the need to maintain stability over long periods of operation.

**Notes**

The computer's resources are healthy at the time of the error. There is no indication of resource shortages, neither in terms of CPU nor memory.
 This happens more often in computers with W10. 
 We don't have a Shell. 
The page is not running on a NavigationPage. Our app start looks like this: 
```cs
        public App(IServiceProvider provider)
        {
            this.InitializeComponent();
            this.MainPage = new MainPage();
        }
```

### Steps to Reproduce

It is difficult to reproduce because the error occurs when the application has been running for a considerable amount of time.

On a PC with a 13th-generation i7 processor, the bug was impossible for me to reproduce. The error occurs on a computer with a 7th-generation i7 processor and 16GB RAM.

You can try

1. Create a new MAUI App 
2. Do a simple set up like in the description. 
3. Create 1 modal or two , and call PushModalAsync until the exception is thrown. 

### Version with bug

8.0.83 SR8.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Affected platforms

Windows

### Affected platform versions

windows10.0.19041.0

### Relevant log output

```shell
No service for type 'Microsoft.Maui.Platform.NavigationRootManager' has been registered. Stacktrace:   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType) Frame:GetRequiredService at offset 18622385 in file:line:column <filename unknown>:0:0
One or more errors occurred. (No service for type 'Microsoft.Maui.Platform.NavigationRootManager' has been registered.) Stacktrace:   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions) Frame:ThrowIfExceptional at offset 54 in file:line:column <filename unknown>:0:0
```

**Comment by jfversluis** [comment] 2024-11-22 12:34
Duplicate of #25961

**Comment by jfversluis** [comment] 2024-11-22 12:35
I know this one is older, but I see the other one has a bit more detail and a request to try the latest version, on .NET 9 and let us know if this then still occurs.

Thanks!

**Closed by jfversluis** 2024-11-22 12:34 UTC
Labels: t/bug, platform/windows 🪟, area-navigation, s/triaged

**Comment by LucasC-Extreme-IT** [comment] 2024-11-26 10:05
Hi,

We tried the update to MAUI9 with NET9 and that didn't solved our issue. 

Thanks!
