### ISSUE TITLE
FYI:  17.3 (Prev-3) Maui Installation Requires "ASP.Net & web development"

### ISSUE THREAD

**Issue by CodeChaser** [dotnet/maui#8717] opened 2022-07-13 17:34 UTC
### Description

During compile of a new dummy test project
ERROR:  *MauiApp1\obj\project.assets.json' not found*  with **no** additional info

### Steps to Reproduce

Steps to reproduce
=============
My goal was to keep the side-by-side assemblies to a minimum since I already had VS2022 17.2.6 installed.  
- Downloaded 17.3 Preview 3..  
- Made a point to only install "MAUI" no problems
- Created a new "MAUI App" project keeping everything simple n default
- After project loaded noticed the "triangles" on the Packages
   - Tried to chase down in Nuget with no success
- Compile error *MauiApp1\obj\project.assets.json' not found*  with **no** additional info

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

I was *not* able test on other platforms

### Affected platform versions

VS2022 17.3 prev 3

### Did you find any workaround?

During installation 
Besides .Net Maui also include ASP.Net web dev

Clicked on one of the errors and got I believe was a build file script...  
- Noticed a reference to ASP.Net
- Launched the VS2022 Installer and added "ASP.Net & web development" to this installation.

That did the trick, upon reloading the **MauiApp1** dummy project the packages were now found.  
App worked in both Windows, then got Android working as well.

**Comment by CodeChaser** [comment] 2022-07-13 19:15
I had only selected .Net MAUI as I was not planning to use Blazor.

I chose no other install options, normally I would install multiple features

Once I put on ASP.Net it worked, not sure if I am just lucky, meaning the only one with the issue 😉

Tom

**Comment by adegeo** [comment] 2022-07-13 22:53
I do think there is something going on here. I just upgraded to preview 3 and opened a previously created project. It wouldn't compile and constantly complained about missing target frameworks from the assets.json file. I tried deleting the obj/bin folders but even that didn't work. Once I did a `dotnet restore` on the project via the command line (even visual studio clean/rebuild wasn't working) it finally would compile.

**Comment by CodeChaser** [comment] 2022-07-13 23:04
It may not be a MAUI issue.  There may be a common "prod" library that has picked up some type of init challenge which is impacting the compiled triggered *dotnet restore*.

After spending maybe an hour browsing MAUI I then jumped back to Prod VS2022 (17.2.6)  

Here my focus was building a Blazor-wasm PWA app and see how much had changed since my heavy focus about 2 years ago.

I got the same exact "error" and to use the *dotnet restore*, it happens every time you create a new project.

Since you have been able to reproduce, I will open up another bug from Prod VS2022 (17.2.6) explaining the Blazor challenge.

**Comment by jfversluis** [comment] 2022-07-14 12:37
@maddymontaquila were you looking into this?

**Comment by CodeChaser** [comment] 2022-07-14 15:07
I just ran a quick test on a separate system which DID not have the 17.3 Preview installed.  
- I started to notice that it seemed like almost every project had the same issue, even got one from Github. 

On the non-previewed installed system

I did not encounter the need to use "dotnet retore"  

It appears my 17.2.6 installation was impacted by the 17.3 prev 3 installation.  No problem, side-by-side installations are risky due to common files.

Based on this one test, the 17.3 may have some issue.

**Comment by francoistanguay** [comment] 2022-07-14 15:18
FWIW, and maybe unrelated to this issue directly but with 17.3P3, solutions what ran fine with 17.3P2 now complain that the macos workload isn't found. Our uno-check (fork of maui-check( detects as-if it was installed even though it apparently isn't. If we force-install the workload, all is back to normal. We're still investigating but thought I'd share.

**Comment by CodeChaser** [comment] 2022-07-14 15:26
May I suggest we change the title of this bug to see if there are other related issues in 17.3P3 ?

Although I can, I did not want to cause any concerns by doing that.

Let me know if I am the only who can change the title, otherwise suggestion:  17.3 Preview-3 Requires "dotnet restore" to compile some projects

**Comment by maddymontaquila** [comment] 2022-07-14 16:47
This is super weird. Can you re-file this bug on Help > Report a Problem in VS too so the visual studio side can track it?? I'm asking around internally!

**Comment by CodeChaser** [comment] 2022-07-14 17:00
Here is the link from the "Send Feedback" to the Developer Community for Visual Studio.  I had notified the team as well.
[Reported in Dev Community](https://developercommunity.visualstudio.com/t/New-Blazor-wasm-PWA-VS2022-1726-proj/10094766?entry=problem&ref=native&refTime=1657817886930&refUserId=f3661d00-7f9b-6484-9326-b0af01e9bdbe)

**Comment by maddymontaquila** [comment] 2022-07-14 17:02
Thanks Tom! The .NET team is talking about it in tactics right now so we
can hunt it down.

**Comment by danroth27** [comment] 2022-08-08 03:46
Just to clarify: The VS "ASP.NET and web development" workload is *not* required to build .NET MAUI Blazor apps. The ".NET Multi-platform App UI development" workload should have everything you need to build .NET MAUI Blazor apps. 

I have confirmed that with a clean install of VS 17.3 Preview 6 with just the .NET MAUI workload that both the .NET MAUI and .NET MAUI Blazor project templates build cleanly. There may be other side-by-side or upgrade installation issues that might be causing problems, but we should get separate issues created for those with detailed steps to reproduce the problem. 

@maddymontaquila  Since the originally reported issue can no longer be reproduced, I recommend closing this issue.

**Closed** 2022-08-12 11:28 UTC
Labels: t/bug, area/setup 🪄
