### ISSUE TITLE
"Unable to load DLL 'Microsoft.Graphics.Canvas.Text.dll'" debugging MAUI app on Windows Machine

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#3167] opened 2021-10-28 20:17 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Unable-to-load-DLL-MicrosoftGraphics/1564046)._

---
[severity:It bothers me. A fix would be nice]
! [image.png] (https://aka.ms/dc/image?name=B0ada3060510b4fa6a7e37da4ac6a6dbc637708487753181366_20211026-083934-image.png&tid=0ada3060510b4fa6a7e37da4ac6a6dbc637708487753181366)

---
#### Ken Annable on 10/26/2021, 05:50 AM: 

<p>Correction, ProcessExplorer doesn’t show the DLL in the exception as loaded.</p>

#### Feedback Bot on 10/26/2021, 06:45 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by kla50** [comment] 2021-10-30 12:52
After some more debugging this seems to be something with machine setup.  I created a Windows 10 Pro 21H1 19043.1320 Hyper-V VM with all updates, installed VS Community 2022 Preview 7, setup for MAUI development, and ran same test in this VM.  In this case the exception does not occur.  However, I'm currently at a loss on how to correct the problem on the host computer.

**Comment by kla50** [comment] 2021-11-01 11:04
I uninstalled Visual Studio Community 2022 and all SDKs, Frameworks, and Runtimes using the "Apps"->"Apps & features" view in Settings.  Then I manually cleaned up directories in "Program Files", "Program Files (x86)", "ProgramData", "Users\[myusername]".  Next I run DiskCleanup, rebooted, and then reinstalled Visual Studio Community 2022 Preview 7.  Something in this process corrected the problem and now I can debug a MAUI app without the exception occurring at app startup.

**Comment by kla50** [comment] 2021-11-19 18:19
I think I've determined how to recreate this behavior.  I'm now running on a Windows 11 machine using VS Community 2022 17.1 Preview 1.1.  If , in Settings->Debugging->General, I check "Enable Just My Code" and uncheck "Enable .NET Framework source stepping" the DLL load exception doesn't occur.  However, when a uncheck "Enable Just My Code" and check "Enable .NET Framework source stepping" the DLL load exception does occur.

**Comment by IndianaGary** [comment] 2022-01-30 00:19
I have encountered exactly this problem while trying to debug some custom drawing software that uses SkiaSharp. As noted by @kla50, turning on "Just My Code" eliminates it, however; to debug may application, I need that turned OFF so that I can get a detailed stack trace. Turning it on does not work for me.

**Comment by casterle** [comment] 2022-02-17 03:46
On Win11 x64, I just updated VS 2022 Community Preview to 17.2.0. 

Since I've never been able to get a Maui program running on Windows, I thought I'd give it a try. I created a new project and built it without problems.  I was able to run the Android project (which I've been able to do before) but still can't get the Windows project to run due to a missing DLL, 'Microsoft.Graphics.Canvas.Text.dll'. 

In fact, such a file does not exist on my computer. Anywhere. I can find copies of 'Microsoft.Graphics.Canvas..dll' in 19 locations, and 'Microsoft.Graphics.Canvas.Interop.dll' in 6. But nothing else that starts with 'Microsoft.Graphics.Canvas.'. 

What do I have to install to get these DLLs?

**Comment by andyabarnard** [comment] 2022-02-19 19:13
It seems to be trying to find DLLs from WinUI.  If you follow the instructions [here](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/set-up-your-development-environment?tabs=vs-2022-17-1-a%2Cvs-2022-17-1-b), that seems to fix _some_ of the issue, but not all of it.

As far as I can tell, this specific DLL causes no problems when it fails to load.  However, I was getting additional DLL not found errors - those being Microsoft.Graphics.Canvas.UI.Xaml.dll and Microsoft.Graphics.Canvas.UI.dll - that were fixed by installing WinUI3.  I no longer get those two DLL errors, although it still can't find Microsoft.Graphics.Canvas.Text.dll, which is confusing because that namespace is also part of WinUI3.

It seems that as long as your program is just trying and failing to load this one specific DLL, you can safely ignore the exception.  It's annoying to have exceptions you can't do anything about, but that's the nature of previews I suppose.

**Comment by kla50** [comment] 2022-02-20 15:46
I've been able to work around this issue by opening the Debug > Windows > Exception Settings window and unchecking the System.DllNotFoundException and System.IO.FileNotFoundException under the "Command Language Runtime Exceptions" node.  I tried just adding a condition to only break when module name didn't equal Microsoft.Graphics.Canvas.Text.dll, but couldn't get it to work.  So, I just disabled for all files.  Not ideal, but it works for me.

**Comment by wenwen60** [comment] 2022-03-16 02:36
Thank you so much for your bug report! Unfortunately, we cannot reproduce your issue with the information above, I can't view your screenshots. Could you provide a sample project/screenshots or more details that we can reproduce your issue? That should greatly speed up the process, thanks!

**Comment by Redth** [comment] 2022-03-23 16:09
Fixed in newer preview release.

**Closed by Redth** 2022-03-23 16:09 UTC
Labels: t/bug, area/setup 🪄, s/no-recent-activity, s/needs-repro
