### ISSUE TITLE
Shell Navigation in OnAppearing Causes Fault on Windows

### ISSUE THREAD

**Issue by david-maw** [dotnet/maui#12313] opened 2022-12-28 01:22 UTC
### Description

I wanted to show a one-time page so made it first in a shell and then navigated to the "real" first page when it was done (or not needed). Navigation when it was done worked fine, but immediate navigation when it was not needed caused a fault in WinRT 

### Steps to Reproduce

1. Build the project and run it on Windows, the first time it will run correctly, and you'll see a timed "One Time" page, then a timed "Startup" page and finally switch to a UI which allows user interaction.
2. Run it again, this (and subsequent) times it will detect it has run before and try to navigate straight to the Startup page from the "One Time" page. This will fault in WinRT code and if you are running with native debug enabled you'll see messages like this:

```
Exception thrown: 'System.InvalidOperationException' in Microsoft.Maui.Controls.dll
Exception thrown at 0x00007FFDEC00CD29 (KernelBase.dll) in MultiPage.exe: WinRT originate error - 0x80131509 : 'Pending Navigations still processing'.
onecore\com\combase\winrt\error\restrictederror.cpp(1016)\combase.dll!00007FFDED935A43: (caller: 00007FFDED8FCA9D) ReturnHr(1) tid(d574) 8007007E The specified module could not be found.
Exception thrown at 0x00007FFDEC00CD29 (KernelBase.dll) in MultiPage.exe: WinRT originate error - 0x80131509 : 'A failure occurred in Application::OnLaunched, the application is unable to start.'.

``` 

It works fine on Android but the same failure occurs whether .NET 6 or 7 is used on Windows.

### Link to public reproduction project repository

https://github.com/david-maw/MultiPage-OneTimePage.git

### Version with bug

6.0.486

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Windows 10

### Did you find any workaround?

Yes, calling `await Task.Delay(1)` before navigating away from the One Time use page makes the symptom go away.

**Comment by PureWeen** [comment] 2023-01-11 19:31
Duplicate of #6653

**Closed by PureWeen** 2023-01-11 19:31 UTC
Labels: t/bug, area/navigation 🧭, area/shell 🐢
