### ISSUE TITLE
Android Crash ImageSource Glyph

### ISSUE THREAD

**Issue by eshalisa** [dotnet/maui#26156] opened 2024-11-27 13:00 UTC
### Description

This is a duplicate of #25113 but that conversation is locked and this needs to be revisited as it is happening often for our android users.

Android app crashes (always) on app resume/re-activate when FontImageSource Glyph is used.

[AndroidRuntime] java.lang.IllegalArgumentException: You cannot start a load for a destroyed activity

### Steps to Reproduce

Create new MAUI App
Add button (add fonts)
<Button Background="{StaticResource Primary}">
    <Button.ImageSource>
        <FontImageSource Glyph="&#x2b;" FontFamily="fa-regular" Size="25" />
    </Button.ImageSource>
</Button>
Click Android back button - to minimize the app
Restart the app
Observe crash

### Version with bug

8.0.91 SR9.1

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Affected platforms

Android

### Affected platform versions

Android 14

### Relevant log output

```shell

```

**Comment by jfversluis** [comment] 2024-11-27 13:16
Duplicate of #12513

**Closed by jfversluis** 2024-11-27 13:16 UTC
Labels: t/bug

**Comment by eshalisa** [comment] 2024-11-27 13:23
Is there an updated on https://github.com/dotnet/maui/issues/12513?
