### ISSUE TITLE
.Net maui blazor app does not work in some phones

### ISSUE THREAD

**Issue by zedweb** [dotnet/maui#10388] opened 2022-09-29 11:01 UTC
### Description

I have created a new simple .Net maui blazor app project with no extras (no any nuget package or even a single line of code). when i run the project in random android phones that works in some phones but not works in other phones( I have tested in different brands and different Android version phones).
in this video you can see after 108 times of tapping on "Click me" button, my app stops working and the menu button or "click me" button does not work.
some times it stops working after 3 times tapping on buttons and this number is randomly.

https://user-images.githubusercontent.com/95431650/193013959-5fdaac9a-dd6c-4aea-afca-9defc63861de.mp4

### Steps to Reproduce

1. Just create a new .Net maui blazor app and run in my android phone. It was working 15 days ago but after that i noticed maui blazor app works in some android phones correctly but not works on other phones

### Link to public reproduction project repository

https://try.mudblazor.com/snippet

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11 ,12 , 13 - I didnt test in lower version

**Comment by Eilon** [comment] 2022-09-29 17:04
Hi @zedweb , this appears to be a duplicate of https://github.com/dotnet/maui/issues/9882#issuecomment-1248713048, which was a bug that was recently fixed in the Android WebView. Please check for WebView updates on your Android system, and that should resolve this.

If you're still experiencing an issue, please let us know the exact Android WebView version on the affected devices (you can find this in the installed components list in the device settings).

**Closed by Eilon** 2022-09-29 17:04 UTC
Labels: t/bug, s/duplicate 2️⃣, area/blazor 🕸️

**Comment by zedweb** [comment] 2022-09-29 18:56
@Eilon 

> Hi @zedweb , this appears to be a duplicate of [#9882 (comment)](https://github.com/dotnet/maui/issues/9882#issuecomment-1248713048), which was a bug that was recently fixed in the Android WebView. Please check for WebView updates on your Android system, and that should resolve this.
> 
> If you're still experiencing an issue, please let us know the exact Android WebView version on the affected devices (you can find this in the installed components list in the device settings).

Thank you very very much.My problem was solved by updating my android web view.
