### ISSUE TITLE
[iOS] CollectionView:  Color for SelectedItem of CollectionView not set when SelectedItem is assigned in ViewModel

### ISSUE THREAD

**Issue by MAUIoxo** [dotnet/maui#20030] opened 2024-01-20 19:11 UTC
### Description

I have a `CollectionView` with a `ItemTemplate` that has a `VisualStateManager` to define a Color when an Item of the `CollectionView` is selected:

```xaml
<VisualStateManager.VisualStateGroups>
    <VisualStateGroup x:Name="CommonStates">
        <VisualState x:Name="Normal">
            <VisualState.Setters>
                <Setter Property="BackgroundColor" Value="Transparent" />
            </VisualState.Setters>
        </VisualState>
        <VisualState x:Name="Selected">
            <VisualState.Setters>
                <Setter Property="BackgroundColor" Value="{StaticResource LightOrange2}" />
            </VisualState.Setters>
        </VisualState>
    </VisualStateGroup>
</VisualStateManager.VisualStateGroups>
```

When I select one of the items in the `CollectionView` the item shows the right Color as specified in the section
```xaml
...
<VisualState x:Name="Selected">

</VisualState>
...
```

The `CollectionView` has a Binding` for the `SelectedItem`:
```xaml
<CollectionView x:Name="PopupCollectionView" ItemsSource="{Binding GroupedSavedStoreItems, Mode=TwoWay}" IsGrouped="True" SelectionMode="Single" SelectedItem="{Binding SelectedSavedStore, Mode=TwoWay}" Margin="20">
```

The `CollectionView` is displayed in a custom `toolkit:Popup` from the CommunityToolkit within a custom Picker Control. When this is opened the `CustomPopupContentPage` containing this above `CollectionView` is displayed.

In the ViewModel the first item of the list should be the `SelectedItem` and is therefore assigned in the ViewModel correspondingly.

On **Android** it looks fine and the `SelectedItem` has the right Color when opened:

![grafik](https://github.com/dotnet/maui/assets/140683727/fb036601-76a6-4a98-9db4-4c762578eb2f)

<br/>

On **iOS** though the Color for a selected item is not applied:

![grafik](https://github.com/dotnet/maui/assets/140683727/d7e4f5dd-6f1c-4e4f-991e-f7e01fcc9239)

But, when I search a Store in the above `SearchBar` an type "A" for instance, the Color is correctly applied:

![grafik](https://github.com/dotnet/maui/assets/140683727/9519b1df-a2d5-4a15-beb3-ec22c9b606ed)

<br/>

The `SelectedSavedStore` which is bound to the `CollectionView` is an `ObservableProperty` and the corresponding `GroupedSavedStoreItems` which is the bound Collection is also a `ObservableProperty` and are set in the corresponding  `CustomPopupViewModel` as can be found in the provided example project:

```cs
[ObservableProperty]
public ObservableRangeCollection<GroupedSavedStoreItemList> groupedSavedStoreItems;

[ObservableProperty]
public SavedStore selectedSavedStore;
```
<br/>

The `SelectSavedStore` is set in Method `SelectSavedStoreByName` in the `CustomPopupViewModel` as follows:

```cs
private async Task SelectSavedStoreByName(string savedStoreName)
{
    if (string.IsNullOrWhiteSpace(savedStoreName))
    {
        await SelectSavedStoreByIndex(0);
        return;
    }

    SavedStore foundSavedStore = GroupedSavedStoreItems.SelectMany(list => list).FirstOrDefault(savedStore => savedStore.Name == savedStoreName);

    SelectedSavedStore = foundSavedStore;

    await Task.CompletedTask;
}
```

### Steps to Reproduce

1. Run the Attached Example Program on **Android**
2. Click on the "Down Arrow" to open the CustomPopup

![grafik](https://github.com/dotnet/maui/assets/140683727/ea4f0469-1280-42e2-9388-4015f75a1a8e)

3. See that the selected item (`SelectedSavedStore` from the ViewModel) has the right Color
4. Run the App on **iOS** and do the same steps as above
5. See that the select item (`SelectedSavedStore`from the ViewModel) does not have a Color set which is wrong
6. Type "A" in the above `SearchBar` of the `CustomPopup` and see that the Color is now applied

![grafik](https://github.com/dotnet/maui/assets/140683727/9519b1df-a2d5-4a15-beb3-ec22c9b606ed)

### Link to public reproduction project repository

[SelectedItemColorNotSet_20030](https://github.com/MAUIoxo/SelectedItemColorNotSet_20030)

### Version with bug

8.0.6-nightly.9880

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 16.2

### Did you find any workaround?

Unfortunately not so far :(

**Comment by PureWeen** [comment] 2024-01-22 15:43
> Yes, this used to work in .NET MAUI

What version of MAUI did this used to work in?

**Comment by PureWeen** [comment] 2024-01-22 15:48
Duplicate of #18933

**Closed by PureWeen** 2024-01-22 15:48 UTC
Labels: t/bug, platform/iOS 🍎, s/needs-info, area/collectionview 📃
