### ISSUE TITLE
Google Play: "This app is no longer compatible with your device..." .NET 9.0

### ISSUE THREAD

**Issue by minhiclick** [dotnet/maui#26354] opened 2024-12-04 06:32 UTC
### Description

My app uses .NET 9.0, after publishing to Google Play, some devices cannot install it. Google Play reports the error "This app is no longer compatible with your device...". Galaxy A02s phone (armx64), Android 14 operating system. Previously, this phone installed the app with .NET 8.0 and it worked normally.

### Version with bug

9.0.10 SR1

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.100 SR10

### Affected platforms

Android

### Relevant log output

```shell

```

**Comment by Ying-6** [comment] 2024-12-04 06:44
Could you provide a sample project for us to investigate it further? Looking forward to your reply!

**Comment by jfversluis** [comment] 2024-12-04 07:32
Duplicate of #26301

**Closed by jfversluis** 2024-12-04 07:32 UTC
Labels: t/bug
