### ISSUE TITLE
Add Marker Clustering to .NET MAUI Maps

### ISSUE THREAD

**Issue by digidoc1010** [dotnet/maui#15550] opened 2023-06-09 13:31 UTC
### Description

It would be helpful to have Marker Clustering capabilities in MAUI Maps. iOS Maps
automatically limits the number of markers displayed and then reveals more upon zooming in. Android, however, displays all of the Markers presented to it. For maps with a lot of markers, this causes the app on Android to crash. I have attached screenshots of the exact same dataset presented in iOS and Android. 

<img width="480" alt="Screenshot 2023-06-09 at 8 12 32 AM" src="https://github.com/dotnet/maui/assets/103452113/fdac7e09-63bf-4ce0-afdf-edae88f7e13f">
<img width="437" alt="Screenshot 2023-06-09 at 8 11 23 AM" src="https://github.com/dotnet/maui/assets/103452113/7eb3e4b6-f6cd-4e46-a666-dc7f711a6785">

### Public API Changes

```XAML
<maps:Map MarkerClustering="True"/>
```

### Intended Use-Case

In my app, I display events at the state level and each state has numerous events causing the app to crash on Android. I would like to be able to cluster markers to produce something similar to the screenshot below.

<img width="253" alt="Screenshot 2023-06-09 at 10 06 01 AM" src="https://github.com/dotnet/maui/assets/103452113/83c4546f-caa2-429c-b606-f0e333a8c7c9">

**Comment by smitha-cgi** [comment] 2023-06-12 22:48
This is a duplicate of [11811](https://github.com/dotnet/maui/issues/11811)

**Comment by PureWeen** [comment] 2023-06-13 18:28
Duplicate of #15564

**Closed by PureWeen** 2023-06-13 18:28 UTC
Labels: proposal/open, area/Maps🗺
