### ISSUE TITLE
Publish MAUI Project with project reference To Class library produces errors.

### ISSUE THREAD

**Issue by danies8** [dotnet/maui#6717] opened 2022-05-01 08:26 UTC
### Description

Publish MAUI Project with project reference To Class library produces errors.

### Steps to Reproduce

1.Create Maui Project.
2.Add Class library A.
3.Add Class library B.
4. Add project reference from MAUI projects for two class librariles.
5. Publish according to this documents:
https://docs.microsoft.com/en-us/dotnet/maui/windows/deployment/overview
6. I used this commands:
`New-SelfSignedCertificate -Type Custom -Subject "CN=Dani" -KeyUsage DigitalSignature -FriendlyName "My temp dev cert" -CertStoreLocation "Cert:\CurrentUser\My" -TextExtension @("2.5.29.37={text}1.3.6.1.5.5.7.3.3", "2.5.29.19={text}")
Get-ChildItem "Cert:\CurrentUser\My" | Format-Table Subject, FriendlyName, Thumbprint
msbuild  /restore /t:Publish /p:TargetFramework=net6.0-windows10.0.19041 /p:configuration=release /p:GenerateAppxPackageOnBuild=true /p:AppxPackageSigningEnabled=true /p:PackageCertificateThumbprint="44CF7D6F1FD0B7CF538085CBEA22A1B0ACDBB541" 
`
7.Get error in build phase, please see Relevant log output

### Version with bug

Release Candidate 1

### Last version that worked well

Release Candidate 1

### Affected platforms

Windows

### Affected platform versions

...

### Did you find any workaround?

No

### Relevant log output

```shell
"C:\Users\danis\Desktop\AutomationClient\AutomationClient.MAUI\AutomationClient.MAUI.csproj" (Restore target) (1) ->
(Restore target) ->
  C:\Users\danis\Desktop\AutomationClient\AutomationClient.MAUI\AutomationClient.MAUI.csproj : error NU1201: Project AutomationClient.Shared is not compatible with net6.0-android31.0 (.NETCoreApp,Version=v6.0). Pro
ject AutomationClient.Shared supports: net6.0-windows10.0.19041 (.NETCoreApp,Version=v6.0)
  C:\Users\danis\Desktop\AutomationClient\AutomationClient.MAUI\AutomationClient.MAUI.csproj : error NU1201: Project AutomationClient.Shared is not compatible with net6.0-ios15.4 (.NETCoreApp,Version=v6.0). Project
 AutomationClient.Shared supports: net6.0-windows10.0.19041 (.NETCoreApp,Version=v6.0)
  C:\Users\danis\Desktop\AutomationClient\AutomationClient.MAUI\AutomationClient.MAUI.csproj : error NU1201: Project AutomationClient.Shared is not compatible with net6.0-maccatalyst15.4 (.NETCoreApp,Version=v6.0).
 Project AutomationClient.Shared supports: net6.0-windows10.0.19041 (.NETCoreApp,Version=v6.0)
  C:\Users\danis\Desktop\AutomationClient\AutomationClient.MAUI\AutomationClient.MAUI.csproj : error NU1201: Project AutomationClient.Shared is not compatible with net6.0-android31.0 (.NETCoreApp,Version=v6.0) / wi
n10-x64. Project AutomationClient.Shared supports: net6.0-windows10.0.19041 (.NETCoreApp,Version=v6.0)
  C:\Users\danis\Desktop\AutomationClient\AutomationClient.MAUI\AutomationClient.MAUI.csproj : error NU1201: Project AutomationClient.Shared is not compatible with net6.0-ios15.4 (.NETCoreApp,Version=v6.0) / win10-
x64. Project AutomationClient.Shared supports: net6.0-windows10.0.19041 (.NETCoreApp,Version=v6.0)
  C:\Users\danis\Desktop\AutomationClient\AutomationClient.MAUI\AutomationClient.MAUI.csproj : error NU1201: Project AutomationClient.Shared is not compatible with net6.0-maccatalyst15.4 (.NETCoreApp,Version=v6.0)
/ win10-x64. Project AutomationClient.Shared supports: net6.0-windows10.0.19041 (.NETCoreApp,Version=v6.0)

    0 Warning(s)
    6 Error(s)
```

**Comment by Redth** [comment] 2022-05-02 13:32
@mattleibow is this a matter of setting some msbuild properties?

@jfversluis maybe you have some input here too?

**Comment by jfversluis** [comment] 2022-05-02 13:38
Looks like a duplicate of #5833

**Comment by danies8** [comment] 2022-05-02 14:23
Reproduce also in VS Version 17.2.0 Preview 5.0,

**Comment by danies8** [comment] 2022-05-02 14:44
When I add this to csproj of class library: <TargetFramework Condition="'$(BuildWindowsOnly)' == 'true'">net6.0-windows10.0.19041</TargetFramework>
and comment <TargetFrameworks>net6.0-android;net6.0-ios;net6.0-maccatalyst</TargetFrameworks>on MAU project csproj file.
and -p:BuildWindowsOnly=true to build command it work.
But you to fix it :))

**Comment by Dbquity** [comment] 2022-05-04 14:59
FYI, with earlier previews, I was able to work around this issue by creating nuget packages for the .NET 6 assemblies and letting the MAUI project refer to those packages rather than using project references.

With VS Community 2022  - preview version 17.2.0 Preview 6.0, I get the below error
```
C:\Program Files\dotnet\sdk\6.0.300-preview.22204.3\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(267,5):
error NETSDK1005: Assets file 'C:\...\obj\project.assets.json' doesn't have a target for 'net6.0-windows10.0.19041'.
Ensure that restore has run and that you have included 'net6.0-windows10.0.19041' in the TargetFrameworks for your project.
```

**Comment by mattleibow** [comment] 2022-05-05 09:43
Duplicate of #4139 
I was able to repro the error with the CLI of:

```
dotnet publish -f net6.0-windows10.0.19041 -c Release
```

But all is well with the extra .0:

```
dotnet publish -f net6.0-windows10.0.19041.0 -c Release
```

**Closed by mattleibow** 2022-05-05 09:43 UTC
Labels: t/bug, p/2, area/publishing 🏁, s/needs-verification

**Comment by jfversluis** [comment] 2022-05-05 10:02
Added a note about the sln publishing to the docs: https://github.com/dotnet/docs-maui/pull/508

**Comment by Dbquity** [comment] 2022-05-05 10:05
@mattleibow a quick test on my devbox shows that the present issue (#6717) with project references to .NET 6 class libraries still exist in MAUI RC2 / VS 2022 17.2 Preview 6 - did you mean to close this issue?

**Comment by mattleibow** [comment] 2022-05-05 10:07
@Dbquity  can you attach a binlog? Maybe our projects don't quite match... or a repro case so I can test.

**Comment by Dbquity** [comment] 2022-05-05 10:15
@mattleibow Quick reply is the repro, I created earlier at https://github.com/Dbquity/MauiApp1 it's .csproj files are of cause out-of-date by bow, but the issue reproes by a dependency chain similar to this (which is what I have in my Dbquity solution):
  MauiApp --> MauiLib --> .NET6Lib
The present issue suggests that even
  MauiApp --> .NET6Lib
fails.

**Comment by Dbquity** [comment] 2022-05-05 10:34
> @Dbquity can you attach a binlog? Maybe our projects don't quite match... or a repro case so I can test.

@mattleibow created as simple repro here: https://github.com/Dbquity/Repro6717

**Comment by mattleibow** [comment] 2022-05-05 10:35
Thanks! Looking now and will try find the issue and reopen if it is a bug or reply here with anything that is dodgy.

**Comment by mattleibow** [comment] 2022-05-05 10:50
OK, so some interesting news and this feels like either a bug or a limitation of msbuild.

If you switch to dotnet build you get an error about TFMs, but this is easilt fixed by adding a .0 to the end of the windows TFM:

```
dotnet build MauiApp1 /p:TargetFramework=net6.0-windows10.0.19041
```

However, for msbuild, it appears the single command of `msbuild /restore` throws off the part with the TFM. If you do it in 2 steps then it works:

```
msbuild /t:restore MauiApp1
msbuild MauiApp1 /p:TargetFramework=net6.0-windows10.0.19041.0
```

I think the fact that you specify a TFM during the restore somehow throws of the restore process. This can be repro-ed with _just_ the restore target:

```
msbuild /t:restore MauiApp1 /p:TargetFramework=net6.0-windows10.0.19041.0
```

However, there is another workaround for this and it is probably due to the fact that the CLI arguments OVERWRITE the properties in the csproj. This is to change the singular `<TargetFramework>` in the class library to the plural version `<TargetFrameworks>`.

As a result, the CLI argument of `/p:TargetFramework=net6.0-windows10.0.19041.0` no longer OVERWRITES the property but instructs the build to SELECT the best matching TFM.

**Comment by Dbquity** [comment] 2022-05-05 10:54
@mattleibow Thanks for the explanation! Now I can ditch my hefty workaround of going via nuget packages for my 10ish .NET 6 class libraries :-)

**Comment by Dbquity** [comment] 2022-05-05 11:06
@davidbritch @jfversluis Maybe Matt's point about splitting out the restore step when you have dependencies on .NET 6 class libraries warrants a mention in the documentation at https://github.com/dotnet/docs-maui/issues/352

**Comment by jfversluis** [comment] 2022-05-05 11:15
We'll be looking forward to you PR @Dbquity 😝

**Comment by Dbquity** [comment] 2022-05-05 11:17
@jfversluis that smells like work - I'll PO (pull out) instead ;-)

**Comment by Dbquity** [comment] 2022-05-06 06:55
@jfversluis 
Jokes aside, since the subtlety of handling .NET 6 class library project references only pertains to ```msbuild``` and MAUI is using ```dotnet publish```, I guess a PR on the docs would be less relevant.
If you think otherwise, let me know, and I'll be happy to do my first github PR as an exercise :-)

**Comment by danies8** [comment] 2022-05-09 12:28
So the publish will be like this document ? (
Publish the MAUI project using this link: https://docs.microsoft.com/en-us/dotnet/maui/windows/deployment/overview
)

**Comment by mattleibow** [comment] 2022-05-09 13:17
That is correct.

**Comment by danies8** [comment] 2022-05-09 13:52
Great:) in which version I can see this fix ?

**Comment by mattleibow** [comment] 2022-05-09 15:16
@danies8 fix? The fix is to either use dotnet build or to use 2 separate restore and then publish commands. Unless I am misreading your question?

https://github.com/dotnet/maui/issues/6717#issuecomment-1118415277

**Comment by danies8** [comment] 2022-05-11 07:33
1. I used Version 17.2.0 Preview 5.0.
2. I used this document:https://docs.microsoft.com/en-us/dotnet/maui/windows/deployment/overview
3. In last phase I used dotnet build and get this error:
`dotnet build /restore /t:Publish /p:TargetFramework=net6.0-windows10.0.19041.0 /p:configuration=release /p:GenerateAppxPackageOnBuild=true /p:AppxPackageSigningEnabled=true /p:PackageCertificateThumbprint="5F1A782863655040EC3AE2E0C2132A1A04AC6618`"

```
C:\Users\danis\Desktop\11_05_2022_unc client check\AutomationClient\AutomationClient.MAUI\AutomationClient.MAUI.csproj : error NU1201: Project AutomationClient.Shared is not compatible with net6.0-android31.0 (.NET
CoreApp,Version=v6.0). Project AutomationClient.Shared supports: net6.0-windows10.0.19041 (.NETCoreApp,Version=v6.0)
C:\Users\danis\Desktop\11_05_2022_unc client check\AutomationClient\AutomationClient.MAUI\AutomationClient.MAUI.csproj : error NU1201: Project AutomationClient.Shared is not compatible with net6.0-ios15.4 (.NETCore
App,Version=v6.0). Project AutomationClient.Shared supports: net6.0-windows10.0.19041 (.NETCoreApp,Version=v6.0)
C:\Users\danis\Desktop\11_05_2022_unc client check\AutomationClient\AutomationClient.MAUI\AutomationClient.MAUI.csproj : error NU1201: Project AutomationClient.Shared is not compatible with net6.0-maccatalyst15.4 (
.NETCoreApp,Version=v6.0). Project AutomationClient.Shared supports: net6.0-windows10.0.19041 (.NETCoreApp,Version=v6.0)
C:\Users\danis\Desktop\11_05_2022_unc client check\AutomationClient\AutomationClient.MAUI\AutomationClient.MAUI.csproj : error NU1201: Project AutomationClient.Shared is not compatible with net6.0-android31.0 (.NET
CoreApp,Version=v6.0) / win10-x64. Project AutomationClient.Shared supports: net6.0-windows10.0.19041 (.NETCoreApp,Version=v6.0)
C:\Users\danis\Desktop\11_05_2022_unc client check\AutomationClient\AutomationClient.MAUI\AutomationClient.MAUI.csproj : error NU1201: Project AutomationClient.Shared is not compatible with net6.0-ios15.4 (.NETCore
App,Version=v6.0) / win10-x64. Project AutomationClient.Shared supports: net6.0-windows10.0.19041 (.NETCoreApp,Version=v6.0)
C:\Users\danis\Desktop\11_05_2022_unc client check\AutomationClient\AutomationClient.MAUI\AutomationClient.MAUI.csproj : error NU1201: Project AutomationClient.Shared is not compatible with net6.0-maccatalyst15.4 (
.NETCoreApp,Version=v6.0) / win10-x64. Project AutomationClient.Shared supports: net6.0-windows10.0.19041 (.NETCoreApp,Version=v6.0)
    0 Warning(s)
    6 Error(s)
```
4. I tried also 2 separate restore and then publish commands
 and I got these errors:
```
PS C:\Users\danis\Desktop\11_05_2022_unc client check\AutomationClient\AutomationClient.MAUI> msbuild /t:restore AutomationClient.MAUI
Microsoft (R) Build Engine version 17.2.0+41abc5629 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1009: Project file does not exist.
Switch: AutomationClient.MAUI
PS C:\Users\danis\Desktop\11_05_2022_unc client check\AutomationClient\AutomationClient.MAUI>

```

**Comment by danies8** [comment] 2022-05-11 07:45
Update when I use 4 -2 separate restore and then publish commands it works-:) 
Need to add .csproj
msbuild /t:restore AutomationClient.MAUI.csproj

**Comment by danies8** [comment] 2022-05-11 08:39
Another issue:
On window server 2012 R2 the MSIX is not open ?
