### ISSUE TITLE
[iOS/Android] Setting Background to null will not update rendering (for example Label.Background = null after it was set to Yellow stays Yellow)

### ISSUE THREAD

**Issue by spadapet** [dotnet/maui#24725] opened 2024-09-11 22:31 UTC
### Description

In iOS and Android, when Background was set to null, the platform element's Background was not changed at all (except for Layouts). This should apply to any elements, such as Labels.

### Steps to Reproduce

1. Open MAUI repo and solution that contains the Sandbox project in VS 2022 latest version:
    * ![image](https://github.com/user-attachments/assets/c83a45bb-feab-454f-a73c-a3f773a74a79)
2. Set target to Android
3. F5 to build and debug
4. Open `MainPage.xaml` in the Sandbox project
5. Type this Label:
    * `<Label Text="Foo" Background="Yellow" />`
6. Notice that the app has the yellow label:
    * ![image](https://github.com/user-attachments/assets/1d8d3213-4c9d-490b-a668-ad98e8566702)
7. Delete the Background property:
    * `<Label Text="Foo" />`

**RESULT:**
The Label is still Yellow in the app (XAML Hot Reload does remove the property value)

**EXPECT:**
Not Yellow anymore

### Link to public reproduction project repository

https://github.com/dotnet/maui

### Version with bug

9.0.0-rc.1.24453.9

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Did you find any workaround?

You can set a Transparent background brush instead of null. But a fix is still needed for XAML Hot Reload to work properly.

**Comment by spadapet** [comment] 2024-09-11 22:35
Yeah, the AI bot found a dupe:
#22914

**Comment by mattleibow** [comment] 2024-09-13 08:12
Duplicate of https://github.com/dotnet/maui/issues/22914

**Closed by mattleibow** 2024-09-13 08:12 UTC
Labels: t/bug, platform/android 🤖, platform/iOS 🍎, area-controls-label, partner/hot-reload-xaml, partner/hot-reload-xaml-full-page-fixed
