### ISSUE TITLE
Unable to change color of BackButton icon in Shell

### ISSUE THREAD

**Issue by Sebosek** [dotnet/maui#11127] opened 2022-11-06 10:46 UTC
### Description

One can set Shell.ForegroundColor but the color is not applied to the back button icon.

```
<Style TargetType="Shell" ApplyToDerivedTypes="True">
    <Setter Property="Shell.BackgroundColor" Value="{AppThemeBinding Light={StaticResource Secondary}, Dark={StaticResource Gray950}}" />
    <Setter Property="Shell.TitleColor" Value="{AppThemeBinding Light={StaticResource Primary}, Dark={StaticResource White}}" />
</Style>
```

With the following color settings
```
<Color x:Key="Primary">#625C40</Color>
<Color x:Key="Secondary">#FCF7E3</Color>
<Color x:Key="Base">#FEFCF6</Color>
```

Results into the following, see the white color of the back button icon.

![image](https://user-images.githubusercontent.com/372542/200166346-381550ad-e186-48bc-a193-c11ea5bdfe10.png)

### Steps to Reproduce

STR:
1. Create an MAUI app
2. Add a page, and set the title of that page
3. Register the new page in shell and make it accessible from the app (via button, for example)
4. Change "TitleColor" style for the shell (Resources/Styles/Styles.xaml) to any color different from white.
5. Launch the app on Android and open the new page, the title color is changed, but the back icon color is white.

Expected behavior:

5. The back icon color is the same as title color

### Link to public reproduction project repository

https://github.com/Sebosek/MAUI.IconColorBug

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

### Did you find any workaround?

No

**Comment by PirasathLuxchumykanthan** [comment] 2022-11-06 11:09
are you dumb maui have bigger problem and you choice to write about  "color of BackButton"

**Comment by copang** [comment] 2023-02-14 09:42
I'm having this problem too, I thought BackButton would change color according to title when I change Shell.TitleColor. Hope this problem will be fixed soon, because in my app the background color of the navigation bar is white and the color of the BackButton is always white.

**Comment by vhugogarcia** [comment] 2023-06-09 19:15
@Sebosek Sebastian, thanks for reporting this issue. I can confirm this issue is still happening, however, I'm facing it with the hamburger menu. Did you find a workaround this issue?

**Comment by Sebosek** [comment] 2023-06-09 20:35
@vhugogarcia kind of... Decided to rewrite my app in React Native 🤣

**Comment by wd-mutasim** [comment] 2023-07-01 02:36
Thanks @vhugogarcia , but it did not work for me. 

I replaced the default icon as a workaround.

`<ContentPage ...>    
    <Shell.BackButtonBehavior>
        <BackButtonBehavior IconOverride="back.png" />   
    </Shell.BackButtonBehavior>
    ...
</ContentPage>`

**Comment by jinxinjuan** [comment] 2023-07-14 07:12
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 2.0. Not repro on Android platform with sample project. 
[MAUI.IconColorBug](https://github.com/Sebosek/MAUI.IconColorBug)

**Comment by drasticactions** [comment] 2024-02-14 11:21
Based on https://github.com/dotnet/maui/issues/20569, I tried out that repro project and a new template project in .NET 8 against Main and you still, as far as I can tell, not change the background color in Shell without that workaround above. It's very much broken (or at least, not implemented). 

@PureWeen Do you know if this was addressed?

**Closed** 2024-02-21 13:01 UTC
Labels: t/bug, platform/android 🤖, area/shell 🐢, s/triaged, s/try-latest-version

**Comment by smalgin** [comment] 2024-02-23 04:12
Not addressed

**Comment by alessandrocaliaro** [comment] 2024-02-27 09:38
I have not understand... this is closed... but have been solved?

**Comment by smalgin** [comment] 2024-02-27 23:08
Update - I edited styles.xml and it fixed the thing for me. In fact, it worked for Shell and for Navigation page both.
Snippet of my code.

`   <Style TargetType="Shell" ApplyToDerivedTypes="True">
       <Setter Property="Shell.BackgroundColor" Value="{AppThemeBinding Light={StaticResource White}, Dark={StaticResource OffBlack}}" />
       <Setter Property="Shell.ForegroundColor" Value="{OnPlatform WinUI={StaticResource Primary}, Default={StaticResource White}}" />
       <Setter Property="Shell.TitleColor" Value="{AppThemeBinding Light={StaticResource Black}, Dark={StaticResource SecondaryDarkText}}" />
       <Setter Property="Shell.DisabledColor" Value="{AppThemeBinding Light={StaticResource Gray200}, Dark={StaticResource Gray950}}" />
       <Setter Property="Shell.UnselectedColor" Value="{AppThemeBinding Light={StaticResource Gray200}, Dark={StaticResource Gray200}}" />
       <Setter Property="Shell.BackgroundColor" Value="{AppThemeBinding Light={StaticResource Primary}, Dark={StaticResource Gray200}}" />
       <Setter Property="Shell.NavBarHasShadow" Value="False" />
       
       <Setter Property="Shell.TabBarBackgroundColor" Value="{AppThemeBinding Light={StaticResource White}, Dark={StaticResource Black}}" />
       <Setter Property="Shell.TabBarForegroundColor" Value="{AppThemeBinding Light={StaticResource Primary}, Dark={StaticResource White}}" />
       <Setter Property="Shell.TabBarTitleColor" Value="{AppThemeBinding Light={StaticResource Black}, Dark={StaticResource White}}" />
       <Setter Property="Shell.TabBarUnselectedColor" Value="{AppThemeBinding Light={StaticResource Gray400}, Dark={StaticResource Gray200}}" />
   </Style>

   <Style TargetType="NavigationPage">
       <Setter Property="BarBackgroundColor" Value="{AppThemeBinding Light={StaticResource NavigationPrimary}, Dark={StaticResource OffBlack}}" />
       <Setter Property="BarTextColor" Value="{AppThemeBinding Light={StaticResource White}, Dark={StaticResource White}}" />
       <Setter Property="IconColor" Value="{AppThemeBinding Light={StaticResource GreenButtonText}, Dark={StaticResource Magenta}}" />
   </Style>

   <Style TargetType="TabbedPage">
       <Setter Property="BarBackgroundColor" Value="{AppThemeBinding Light={StaticResource White}, Dark={StaticResource Gray950}}" />
       <Setter Property="BarTextColor" Value="{AppThemeBinding Light={StaticResource Magenta}, Dark={StaticResource White}}" />
       <Setter Property="UnselectedTabColor" Value="{AppThemeBinding Light={StaticResource Gray200}, Dark={StaticResource Gray950}}" />
       <Setter Property="SelectedTabColor" Value="{AppThemeBinding Light={StaticResource Gray950}, Dark={StaticResource Gray200}}" />
   </Style>
`
