### ISSUE TITLE
Maui Library Project is Creatable, but Not Loadable

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#4023] opened 2022-01-10 17:54 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Maui-Library-Project-is-Creatable-but-N/1586941)._

---
[regression] [worked-in:Version 17..preview]
I have created a Git Resposity and i have created within the folders a, MAUI Library project, the Creating and Saving and Comitting was goood. But if i Restart Visualstudio 2022 newest version,  this Project was not as compatible recognized and because this not loaded, if i opened the  Project Folder from it

---
#### Feedback Bot on 11/17/2021, 02:21 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Jorge Arturo Aviles on 11/17/2021, 07:56 PM: 

<p>Hi, I have the same problem too, I created a project but its appears as incompatible…</p>
<p>😦</p>
<p><img src="https://aka.ms/dc/image?name=B74945c0021364e0bb5f8e4c8c3c65ee0637728045201643957_20211117-215518-maui2022.PNG&amp;tid=74945c0021364e0bb5f8e4c8c3c65ee0637728045201643957" alt="maui2022.PNG"></p>

---
### Original Solutions
(no solutions)

**Comment by jfversluis** [comment] 2022-01-10 19:26
Duplicate of #4025

**Closed by jfversluis** 2022-01-10 19:26 UTC
