### ISSUE TITLE
android's Switch is wrong working

### ISSUE THREAD

**Issue by yiszza** [dotnet/maui#4368] opened 2022-01-28 02:57 UTC
### Description

if i tap switch change state, It looks right, but if i use code change switch state, It looks wrong

### Steps to Reproduce

![image](https://user-images.githubusercontent.com/42995476/151479404-0f8892da-5f10-4381-805c-f0acaf84f9ef.png)

https://user-images.githubusercontent.com/42995476/151479458-28a69df4-0bac-47f6-9a0c-583186b7c3bc.mp4

### Version with bug

Preview 12 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

android 11

**Comment by jfversluis** [comment] 2022-01-28 11:04
Thanks for the report @yiszza seems this is a duplicate of #4085 and already fixed with #4134

Be on the lookout for the next preview release! Thanks!

**Closed by jfversluis** 2022-01-28 11:05 UTC
Labels: t/bug, area/controls 🎮

**Comment by ChuckVanzant** [comment] 2022-01-29 22:21
I'm seeing the same problem in Windows whether changing the Switch IsToggled property directly in a button callback or via a bound property value change. Looking forward to the next preview to see if the problem is fixed for the bound property.
![Capture](https://user-images.githubusercontent.com/12755346/151679352-2a55d67e-672d-4e08-9d36-ac89dcf4d9c1.JPG)

**Comment by yiszza** [comment] 2022-02-16 03:49
@jfversluis @jsuarezruiz No tests?

https://user-images.githubusercontent.com/42995476/154192688-bbb2b5e4-72e1-45e1-96bf-4f97b66f219f.mp4
