### ISSUE TITLE
FlexLayout exception

### ISSUE THREAD

**Issue by SchreinerK** [dotnet/maui#7824] opened 2022-06-07 16:59 UTC
### Description

Using FlexLayout throws LayoutCycleException: A cycle occurred while laying out the GUI.  
But in the test project I get 
COMException (0x80070490): Element nicht gefunden. (0x80070490) 
 
OS: Windows ERR, Android OK, Mac not tested.
Microsoft Visual Studio 17.3.0 Preview 1.1

_Actually I only wanted a "StackLayout" with LastItemFill = true like the WPF DockPanel, which I unfortunately did not find in MAUI._

### Steps to Reproduce

[test project](https://github.com/SchreinerK/Issue220607-1-Maui-FlexLayout-Exception)
\- or - 
1) Create a new MAUI app and replace the MainPage content with:
```XAML
    <VerticalStackLayout>
        <FlexLayout AlignItems="Center" Direction="Row">
            <Label Text="Label" FlexLayout.Basis="Auto" FlexLayout.Order="-1" />
            <Slider Value="0.5" FlexLayout.Grow="1"/>
        </FlexLayout>
    </VerticalStackLayout>
```
2) Start the app with "Windows  Machine"
3) the app holds with an exception in App.g.i.cs

2b) start the app with "Pixel 5 Emulator"
3b) the app works as expected

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Microsoft Windows [Version 10.0.19044.1706]

### Did you find any workaround?

Workarround to get the expected layout
```XAML
<Grid>
    <Grid.ColumnDefinitions>
        <ColumnDefinition Width="Auto"/>
        <ColumnDefinition Width="*"/>
    </Grid.ColumnDefinitions>
    <Label Text="Label" Grid.Column="0"/>
    <Grid Background="Gray" Grid.Column="1"/>
</Grid>
```

**Comment by Lucasvor** [comment] 2022-06-08 01:20
I'm having the same error using DataTemplate and Selector

**Comment by kristinx0211** [comment] 2022-06-08 02:19
verified repro on windows with above repro project, on android works ok.

**Comment by jsuarezruiz** [comment] 2022-06-09 09:25
You have a DockLayout here https://github.com/jsuarezruiz/MauiPane

**Comment by jfversluis** [comment] 2022-07-06 14:55
Can't reproduce anymore on our current codebase so this should be fixed in an upcoming service release. Thanks!

**Closed by jfversluis** 2022-07-06 14:55 UTC
Labels: t/bug, area/layout 🔲, fatal, s/verified
