### ISSUE TITLE
Inputs on WPF Blazor Web View Control Not showing right click

### ISSUE THREAD

**Issue by musictopia2** [dotnet/maui#11398] opened 2022-11-16 02:01 UTC
### Description

When I use any input or textareas, then if somebody right clicks on windows, nothing happens.
Tried the same thing with blazor server side and it worked fine.
This means its a problem with the webview control for blazor.
Most likely will affect the maui windows version as well.

### Steps to Reproduce

1.  Type something in the input box
2. Try to right click.  Nothing will happen.

Do same thing for the textarea.

Most likely this will happen with the maui control as well.

### Link to public reproduction project repository

https://github.com/musictopia2/NoRightClickOnInputsOrTextAreaSample

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows

### Did you find any workaround?

Blazor webassembly and server side does not have the issue.
Any blazor native apps has no workaround unfortunately.

**Comment by musictopia2** [comment] 2022-11-24 13:47
How do I use the vanilla webview.  I only know about the blazorwebview.  If you can give me a link to the link that just uses a vanilla webview, I can create a sample and see what happens.

**Comment by javiercn** [comment] 2022-11-24 13:49
@musictopia2 Instantiate the webview control and render an HTML document instead. You can see more details https://learn.microsoft.com/en-us/dotnet/maui/user-interface/controls/webview?view=net-maui-7.0

**Comment by musictopia2** [comment] 2022-11-28 14:14
The sample did not really help because at first, it said that webview was not even installed.  I tried installing it and following the sample but could not even get that sample to work.

**Comment by Eilon** [comment] 2022-11-28 23:45
I confirmed that this repros as-is with Blazor Hybrid WPF.

**Comment by Eilon** [comment] 2022-11-28 23:54
And it seems to happen in Blazor Hybrid WinForms too....

**Comment by Eilon** [comment] 2022-11-28 23:55
But it does not repro in a WebView WinForms app. So perhaps some setting that Blazor Hybrid sets is affecting this...

**Comment by Eilon** [comment] 2022-11-28 23:58
Oh boy, it appears that setting `CoreWebView2.Settings.AreDefaultContextMenusEnabled = false` is what causes this:

https://github.com/dotnet/maui/blob/main/src/BlazorWebView/src/SharedSource/WebView2WebViewManager.cs#LL379C4-L379C73

My vague historical recollection is that that setting affects only the "web browser" type of menus with options for navigation, printing, etc.:

<img width="181" alt="image" src="https://user-images.githubusercontent.com/202643/204405562-658cba3e-97e3-41be-94a6-ee9b5c577799.png">

But it seems it affects _all_ context menus!

**Comment by Eilon** [comment] 2022-11-29 01:12
I figured out how to make it work but I'd say it's not a great solution. Ideally there would be an option `WebView2.CoreWebView2.Settings.AreWebSpecificContextMenuOptionsEnabled = false` to disable only the "web" specific items.

Here's how to customize which context menus are enabled in the app:

1. Start with the original repro app at https://github.com/musictopia2/NoRightClickOnInputsOrTextAreaSample
2. Change `Index.razor` to have a valid `<textarea>` tag because it cannot be self-closing. Not sure how much this affects the repro but it can break Blazor. It should be: `<textarea rows="5"></textarea>`
3. Set `e.WebView.CoreWebView2.Settings.AreDefaultContextMenusEnabled = true;` to generally make context menus be enabled in the BlazorWebView
4. Handle the `WebView.CoreWebView2.ContextMenuRequested` event to customize when the context menu is shown and what items are in it. This event lets you check what type of item is being clicked on and lets you edit the context menu items.

To see the full code, I created a PR to the original repro app here: https://github.com/musictopia2/NoRightClickOnInputsOrTextAreaSample/pull/1

Note that it's up to each app to decide which menu items it wants or where, so the PR I showed has the general pattern, but could need to be customized depending on the app's specific needs.

**Comment by Eilon** [comment] 2022-11-29 01:13
For more _context_ on how to handle the `WebView.CoreWebView2.ContextMenuRequested` event, check out:

1. This spec: https://github.com/MicrosoftEdge/WebView2Feedback/blob/main/specs/ContextMenuRequested.md
2. The docs: https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.contextmenurequested?view=webview2-dotnet-1.0.1418.22

**Comment by Zhanglirong-Winnie** [comment] 2023-08-21 03:04
Verified this issue with Visual Studio Enterprise 17.8.0 Preview 1.0(.NET8). Not repro on windows platform with sample project.
[NoRightClickOnInputs.zip](https://github.com/dotnet/maui/files/12391021/NoRightClickOnInputs.zip)
![Screenshot 2023-08-21 110235](https://github.com/dotnet/maui/assets/77434865/e8350b73-20bd-42bf-8436-0336a16c623a)

**Closed** 2023-08-28 13:01 UTC
Labels: t/bug, area/blazor 🕸️, feature-blazor-windesktop, s/triaged, s/try-latest-version
