### ISSUE TITLE
Freezing App when Navigating Between Tabs with BlazorWebView in Maui Blazor App

### ISSUE THREAD

**Issue by alzubitariq** [dotnet/maui#22344] opened 2024-05-11 14:33 UTC
### Description

Two Tabs: an AppShell page that contains two tabs named "page1" and "page2". These tabs likely represent different sections or functionalities within the app.

Navigation from Page1 to Another Page: When navigate from "page1" to another page, presumably using some kind of navigation mechanism like a button click or a navigation service.

BlazorWebView Content: The page you navigate to from "page1" contains a BlazorWebView component.

Tab Switching: After navigating to the page containing the BlazorWebView, you switch tabs from  "page1" back to "page2"  and then "page2" back to "page1".

App Freeze: At this point, when you switch back to "page1" after previously navigating away from it, the app freezes. This means that the app becomes unresponsive and does not react to user input or continue executing code.

### Steps to Reproduce

Create new maui blazor app 

### Link to public reproduction project repository

https://github.com/alzubitariq/MauiBlazorNavigationIssue

### Version with bug

8.0.21 SR4.1

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android

### Did you find any workaround?

No

### Relevant log output

```shell
[RtgSched] resetRtgSchedHandle failed enable:1
[OnBackInvokedCallback] OnBackInvokedCallback is not enabled for the application.
[OnBackInvokedCallback] Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
```

**Comment by alzubitariq** [comment] 2024-05-12 14:39
@Eilon Could you please take a look

**Comment by Zhanglirong-Winnie** [comment] 2024-05-13 03:03
Verified this issue with Visual Studio 17.10 Preview 7.0 (8.0.21). Can repro on android platform with sample project.

**Comment by Eilon** [comment] 2024-05-15 23:30
Duplicate of the root cause of #20678.

**Closed by Eilon** 2024-05-15 23:30 UTC
Labels: t/bug, platform/android 🤖, area-navigation, area-blazor, s/verified, s/triaged
