### ISSUE TITLE
[MacOSX][Label] Label won't display text in italic

### ISSUE THREAD

**Issue by ZeProgFactory** [dotnet/maui#15912] opened 2023-06-28 14:20 UTC
### Description

Changing the `FontAttributes` to Italic of a `Label` won't change the output on `MacOSX`.

### Steps to Reproduce

1) Generate a basic Maui App with VisualStudio
2) Change `Label` on the MainPage:
```
            <Label
                Text="Hello, World!"
                SemanticProperties.HeadingLevel="Level1"
                FontAttributes="Italic"
                FontSize="32"
                HorizontalOptions="Center" />
```

### Link to public reproduction project repository

https://github.com/ZeProgFactory/MacOSX-Entry-Invisible-cursor

### Version with bug

7.0.49

### Last version that worked well

Unknown/Other

### Affected platforms

macOS, I was *not* able test on other platforms

### Affected platform versions

OSX Ventura 13.4.1

**Comment by ZeProgFactory** [comment] 2023-06-29 08:27
Windows is not concerned by this issue.

**Comment by drasticactions** [comment] 2023-06-30 07:43
@ZeProgFactory It can display labels in italic. The issue is the default fonts and values provided by MAUI.

<img width="658" alt="スクリーンショット 2023-06-30 16 35 48" src="https://github.com/dotnet/maui/assets/898335/af6aedd2-229f-4ae5-a3a9-06b781e76577">

The default `Styles.xaml` forces the FontFamily on Labels to be "OpenSans-Regular." This is the "Regular" font version; it does not include Italics. The underlying Windows and Android platform controls can "fake" it by default (Although it is not the true OpenSans-Italic), UIKit (iOS, Catalyst) does not. Most likely, the fix would be to force the platform controls for UIKit to use whatever values the user has set, even if the font itself doesn't support it. Just including `OpenSans-Italic` would not be enough, since the FontFamily in the Styles.xaml still references OpenSans-Regular.

If you comment out the default OpenSans fonts, it can render with Italics.

<img width="1023" alt="スクリーンショット 2023-06-30 16 21 54" src="https://github.com/dotnet/maui/assets/898335/e572c92f-1307-476f-b38c-d89b45820f7b">

If you want to work around it for now, either remove the default OpenSans fonts from your MauiProgram.cs, or add the missing OpenSans-Italic ttf and set the FontFamily to that font.

@jsuarezruiz @mattleibow I'm not sure who the font expert is here for this, any ideas for what to do about this?

**Comment by Nymu5** [comment] 2023-07-09 20:53
I cannot check it right now, but it should also work if you set the font to the default font by adding an empty attribute like `FontFamily=""`

**Comment by ZeProgFactory** [comment] 2023-07-10 02:00
> I cannot check it right now, but it should also work if you set the font to the default font by adding an empty attribute like `FontFamily=""`

@Nymu5 Good workaround,
Thanks

**Comment by mattleibow** [comment] 2023-11-07 20:33
Duplicate of https://github.com/dotnet/maui/issues/1018

**Closed by mattleibow** 2023-11-07 20:33 UTC
Labels: t/bug, platform/macOS 🍏, area/controls 🎮
