### ISSUE TITLE
[iOS] Image in StackLayout in Shell.FlyoutHeader is not visible

### ISSUE THREAD

**Issue by ThatJammyDodger** [dotnet/maui#12892] opened 2023-01-24 20:55 UTC
### Description

If there is an image within a StackLayout within a Shell.FlyoutHeader element, the image does not appear and then just leaves a gaping empty space. The image does load if not in a StackLayout. It works in a Grid view though.

![image](https://user-images.githubusercontent.com/91419873/214414407-3c784068-6dec-4c17-b082-8eea183a77c7.png)

### Steps to Reproduce

1. Clone the GitHub repo with the reproduction here: https://github.com/ThatJammyDodger/iOS-Header-StackLayoutImage.
2. Run the app on an iOS simulator or physical device.
3. Open the flyout menu and observe.

### Link to public reproduction project repository

https://github.com/ThatJammyDodger/iOS-Header-StackLayoutImage

### Version with bug

6.0.312

### Last version that worked well

6.0.312

### Affected platforms

iOS, I was *not* able test on other platforms

### Affected platform versions

iOS 15, probably also MacCatalyst but was unable to test.

### Did you find any workaround?

No workaround found.

**Comment by PureWeen** [comment] 2023-01-25 20:04
Duplicate of #11679

**Closed by PureWeen** 2023-01-25 20:04 UTC
Labels: t/bug, area/layout 🔲, area/shell 🐢, area/controls 🎮, control-image

**Comment by ThatJammyDodger** [comment] 2023-01-25 20:21
I don't think that this is a duplicate of the other issue. The problem here is that the image does not render at all but the space is there as if the image is removed from stack layout the amount of empty space decreases. Even if the image renders, e.g. by placing it in a grid or on its own, the empty space as the other issue says, is still there.
