### ISSUE TITLE
Blazor Hybrid - Android - Keyboard covers UI despite having resize soft keyboard setting

### ISSUE THREAD

**Issue by caliberdigitalllc** [dotnet/maui#24573] opened 2024-09-02 21:20 UTC
### Description

I followed another thread or two talking about this issue, but I'm not sure they were specific to Blazor Hybrid.

I added:

```
using Microsoft.Maui.Controls.PlatformConfiguration.AndroidSpecific;
using Application = Microsoft.Maui.Controls.Application;

namespace AbMobileMaui {
    public partial class App : Application {
        public App() {
            InitializeComponent();

            MainPage = new MainPage();

            Current.On<Microsoft.Maui.Controls.PlatformConfiguration.Android>().UseWindowSoftInputModeAdjust(WindowSoftInputModeAdjust.Resize);

        }
    }
}
```

but despite that, the keyboard overlays my UI instead of the UI sliding up or resizing.

### Steps to Reproduce

- Created a new maui blazor hybrid app
- Added UI elements
- Ran on android
- Tapped on input box, keyboard overlays the inputs and UI elements.

This does not occur on iOS - iOS slides the whole app up to allow the keyboard and part of the UI to show up.

### Version with bug

9.0.0-preview.7.24407.4

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android

### Did you find any workaround?

no

**Comment by caliberdigitalllc** [comment] 2024-09-02 21:21
before and after keyboard visible attached.

![image](https://github.com/user-attachments/assets/862e0eae-695c-4935-9a10-d68809be38ea)
![image](https://github.com/user-attachments/assets/51abf82e-6250-4c35-a918-d0c7d2dcb8ae)

**Comment by caliberdigitalllc** [comment] 2024-09-02 21:40
One other update - I tried this on both my existing app (above) and a brand new 9p7 boilerplate blazor hybrid app where all I did was this in home.razor:

`@page "/"

<h1>Hello, world!</h1>

<p>Welcome to your new app.</p>

<div class="container mt-4">
    @for (int i = 1; i <= 10; i++)
    {
        <div class="row mb-3">
            <div class="col">
                <input type="text" class="form-control" placeholder="Enter text here">
            </div>
        </div>
    }
</div>
`

and this in app.xaml.cs:
`using Microsoft.Maui.Controls.PlatformConfiguration.AndroidSpecific;
using Application = Microsoft.Maui.Controls.Application;

namespace MauiApp2 {
    public partial class App : Application {
        public App() {
            InitializeComponent();

            Current.On<Microsoft.Maui.Controls.PlatformConfiguration.Android>().UseWindowSoftInputModeAdjust(WindowSoftInputModeAdjust.Resize);
        }

        protected override Window CreateWindow(IActivationState? activationState) {
            return new Window(new MainPage());
        }
    }
}
`

And if you tap in one of the last text boxes you can easily see the issue reproduce, even in a brand new barebones maui android app.

**Comment by QianaJiao** [comment] 2024-09-03 09:52
There is a similar issue https://github.com/dotnet/maui/issues/18964
My result is a little different from yours.  If I add  ` Current.On<Microsoft.Maui.Controls.PlatformConfiguration.Android>().UseWindowSoftInputModeAdjust(WindowSoftInputModeAdjust.Resize);` UI will not be overlapped.
![Animation](https://github.com/user-attachments/assets/903db0eb-8d2e-482a-99ad-771cd85bedd2)

Would you mind try it again? If you are still repro, could you share me the Android emulator API?

**Comment by jfversluis** [comment] 2024-09-03 10:54
Duplicate of #18964

**Comment by jfversluis** [comment] 2024-09-03 10:55
Please add your findings to the linked issue. That will make it easier to have all the information in one place and also that will surface the issue as potentially higher priority if more people interact with 1 issue instead of many describing the same thing.

**Closed by jfversluis** 2024-09-03 10:54 UTC
Labels: t/bug, platform/android 🤖, s/triaged

**Comment by caliberdigitalllc** [comment] 2024-09-08 21:52
> Please add your findings to the linked issue. That will make it easier to have all the information in one place and also that will surface the issue as potentially higher priority if more people interact with 1 issue instead of many describing the same thing.

I copied my latest findings to that other thread.

**Comment by caliberdigitalllc** [comment] 2024-09-08 22:36
> There is a similar issue #18964 My result is a little different from yours.  If I add  ` Current.On<Microsoft.Maui.Controls.PlatformConfiguration.Android>().UseWindowSoftInputModeAdjust(WindowSoftInputModeAdjust.Resize);` UI will not be overlapped. ![Animation](https://private-user-images.githubusercontent.com/91244512/363931048-903db0eb-8d2e-482a-99ad-771cd85bedd2.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4MzUyNDIsIm5iZiI6MTcyNTgzNDk0MiwicGF0aCI6Ii85MTI0NDUxMi8zNjM5MzEwNDgtOTAzZGIwZWItOGQyZS00ODJhLTk5YWQtNzcxY2Q4NWJlZGQyLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA4VDIyMzU0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4MzdlYmE0ZGE4ZjU1NWE4ZTMzZTNmNGIzMmI4YTEwMjk4YTRiMDRmNzA0ZjM5MTEyZDIxZDU0MzRhMGU0OTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2o8bHyeI7P8_bFa54GIrP6SHGvsmU_LDZ-YRnEYDnSs) [ ](https://private-user-images.githubusercontent.com/91244512/363931048-903db0eb-8d2e-482a-99ad-771cd85bedd2.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4MzUyNDIsIm5iZiI6MTcyNTgzNDk0MiwicGF0aCI6Ii85MTI0NDUxMi8zNjM5MzEwNDgtOTAzZGIwZWItOGQyZS00ODJhLTk5YWQtNzcxY2Q4NWJlZGQyLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA4VDIyMzU0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4MzdlYmE0ZGE4ZjU1NWE4ZTMzZTNmNGIzMmI4YTEwMjk4YTRiMDRmNzA0ZjM5MTEyZDIxZDU0MzRhMGU0OTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2o8bHyeI7P8_bFa54GIrP6SHGvsmU_LDZ-YRnEYDnSs) ![Animation](https://private-user-images.githubusercontent.com/91244512/363931048-903db0eb-8d2e-482a-99ad-771cd85bedd2.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4MzUyNDIsIm5iZiI6MTcyNTgzNDk0MiwicGF0aCI6Ii85MTI0NDUxMi8zNjM5MzEwNDgtOTAzZGIwZWItOGQyZS00ODJhLTk5YWQtNzcxY2Q4NWJlZGQyLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA4VDIyMzU0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4MzdlYmE0ZGE4ZjU1NWE4ZTMzZTNmNGIzMmI4YTEwMjk4YTRiMDRmNzA0ZjM5MTEyZDIxZDU0MzRhMGU0OTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2o8bHyeI7P8_bFa54GIrP6SHGvsmU_LDZ-YRnEYDnSs) [ ](https://private-user-images.githubusercontent.com/91244512/363931048-903db0eb-8d2e-482a-99ad-771cd85bedd2.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4MzUyNDIsIm5iZiI6MTcyNTgzNDk0MiwicGF0aCI6Ii85MTI0NDUxMi8zNjM5MzEwNDgtOTAzZGIwZWItOGQyZS00ODJhLTk5YWQtNzcxY2Q4NWJlZGQyLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA4VDIyMzU0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4MzdlYmE0ZGE4ZjU1NWE4ZTMzZTNmNGIzMmI4YTEwMjk4YTRiMDRmNzA0ZjM5MTEyZDIxZDU0MzRhMGU0OTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2o8bHyeI7P8_bFa54GIrP6SHGvsmU_LDZ-YRnEYDnSs)
> 
> Would you mind try it again? If you are still repro, could you share me the Android emulator API?

I added the feedback in the other thread - that code didn't fix it for me on API level 35. Let's chat over there in the other thread though.
