### ISSUE TITLE
Not able select Listview items some times in MAUI for Windows

### ISSUE THREAD

**Issue by deviprasadclaritysoft** [dotnet/maui#19422] opened 2023-12-14 13:13 UTC
### Description

We found a strange behavior with ListView some times as we are not able to select some ListView items and those are getting background color as gray as shown in the below Image.

![image](https://github.com/dotnet/maui/assets/142251552/f479caae-495c-4798-abc2-1bd5e32e6696)

We are binding Simple ListView and Popping up on a button click, and the strange behavior is it is not happening every time.
If any one encounter with the same problem please let us the workaround for the same.

### Steps to Reproduce

Create a Simple MAUI application, create a popup window with list of items and populate when clicks on a button.

### Version with bug

8.0.3

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

8.0.3

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Windows SDK 10.19045

**Comment by jfversluis** [comment] 2023-12-14 13:21
Without any relevant code or reproduction project it's pretty much impossible to diagnose what might be going on here.

**Comment by deviprasadclaritysoft** [comment] 2023-12-14 13:23
@jfversluis Yes understood my if I provide the sample project where also we not able to replicate the issue every time, it's a strange actually.

**Comment by jfversluis** [comment] 2023-12-14 13:25
That is also part of producing a repro sample. Trying to lift the pieces from your code that cause the issue and see what changes might impact this behavior. A lot of times people then uncover things themselves that might be going wrong instead of it being a bug in the .NET MAUI SDK. Please let us know if you have something relevant to share in this regard.

Thanks!

**Comment by Vroomer** [comment] 2023-12-14 18:43
There was an issue with 1st item of CollectionView not being selectable. I don't know if it was fixed in .NET 8 GA, but it's definitely not present in latest nightly builds. Maybe that's the issue you are experiencing.

**Comment by jeremy-visionaid** [comment] 2023-12-19 04:10
I have a similar issue with CollectionView which also affects ListView. Maybe they're the same root cause:
https://github.com/molesmoke/MauiTestApp/tree/collectionview-selection

Unfortunately, my trivial repro shows up multiple different failures. When SelectedItem is set in code-behind....

On Android: The ListView SelectedItem is not highlighted
On iOS: CollectionView and ListView SelectedItem are not highlighted
On Windows: CollectionView and ListView SelectedItem are not highlighted

It gets worse though.... if the SelectionMode is set to Multiple, and you try to highlight multiple items with UpdateSelectedItems, then on iOS, the items aren't displayed at all!!! 😱

**Comment by deviprasadclaritysoft** [comment] 2023-12-19 06:15
Hi @jeremy-visionaid 

Are you able to reproduce the same issue what I am facing in the repo what you have attached.

**Comment by jeremy-visionaid** [comment] 2023-12-19 07:46
@deviprasadclaritysoft I'm not totally sure if it's the same or not - you'd have to tell me. But you're welcome to clone the repo and let us know! Basically, I'm seeing that the selection isn't correctly rendered, maybe try inspecting the SelectionChanged event and see if the SelectedItem/SelectedItems value matches what you expect. If they are then there's a reasonable chance that they have the same cause. Otherwise I'll create a new issue.

**Comment by Vroomer** [comment] 2023-12-27 00:10
@jeremy-visionaid There are already reported issues regarding programatically selecting items: https://github.com/dotnet/maui/issues/18933, https://github.com/dotnet/maui/issues/15718, https://github.com/dotnet/maui/issues/15967

**Comment by jeremy-visionaid** [comment] 2023-12-28 19:56
@Vroomer Yup, found them just before I opened a new issue, thanks!

**Comment by Zhanglirong-Winnie** [comment] 2024-04-29 09:04
I found a lot of related sample projects, verified this issue with Visual Studio 17.10 Preview 5 (8.0.21). Not repro on windows platform.

**Closed** 2024-05-06 11:56 UTC
Labels: t/bug, platform/windows 🪟, area/ListView, s/triaged, s/needs-attention, s/try-latest-version
