### ISSUE TITLE
maui blazor app crashes on iphone device just by adding builder.Services.AddSingleton<IConnectivity>(Connectivity.Current) to MauiProgram.cs

### ISSUE THREAD

**Issue by myndfire** [dotnet/maui#7952] opened 2022-06-11 21:29 UTC
### Description

Build Setup: Macbook Air(M1, 2020) Version 12.3.1

VsCode:Version: 1.67.2 (Universal) MacOS

Dotnet: 6.0.300

Created a new Maui App: dotnet new maui-blazor

Created Archive from Command line:
dotnet publish MyMauiBlazorApp.csproj -f:net6.0-ios -c:Release /p:ServerAddress=x.x.x.x /p:ServerUser=james /p:TcpPort=58181 /p:ArchiveOnBuild=true /p:_DotNetRootRemoteDirectory=/Users/james/Library/Caches/Xamarin/XMA/SDKs/dotnet/ /p:EnableAssemblyILStripping=false /p:ServerPassword=supersecretpwd

Did all ceremonies for publishing to App Store (app,cert,profile)

Published app with Transporter and Test flight

Download and Ran app. 
All Good and app works normally

---- Then ------
Added to iOS/Info.plist:

    <key>MinimumOSVersion</key>
    <string>14.2</string>
    <key>NSAppTransportSecurity</key>
    <dict>
        <key>NSAllowsArbitraryLoads</key>
        <true/>
    </dict> 

Added to MauiProgram.cs
builder.Services.AddSingleton<IConnectivity>(Connectivity.Current);

Ran thru the same process as before to build .ipa and published to app store

----- CRASHES ------
Splash Screen appears for a brief time on Iphone 12 Max Pro, then crashes. 

However, the same code ran successfully locally on my build macbook: dotnet build -t:Run -c:Release -f net6.0-maccatalyst MyMauiBlazorApp.csproj

Any help would be appreciated.

### Steps to Reproduce

Create a new Maui App: dotnet new maui-blazor

Added to iOS/Info.plist:

    <key>MinimumOSVersion</key>
    <string>14.2</string>
    <key>NSAppTransportSecurity</key>
    <dict>
        <key>NSAllowsArbitraryLoads</key>
        <true/>
    </dict> 

Added to MauiProgram.cs
builder.Services.AddSingleton<IConnectivity>(Connectivity.Current);

Deploy to Iphone using Transporter/TestFlight

Try starting the app.

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

Iphone 12 Max Pro, version 15.5

### Did you find any workaround?

I wish..

**Comment by jfversluis** [comment] 2022-06-13 11:45
Duplicate of #7945

**Closed by jfversluis** 2022-06-13 11:45 UTC
Labels: t/bug, s/needs-verification
