### ISSUE TITLE
CollectionView items are overlapping when loaded on Windows

### ISSUE THREAD

**Issue by Schinwinkwinsky** [dotnet/maui#8179] opened 2022-06-20 17:38 UTC
### Description

Hello, everybody. 

I'm developing a simple app to try .Net Maui and its first page has a CollectionView. It shows some info get from an API. But when the app is running on Windows the CollectionView items are overlapping when loaded.

![image](https://user-images.githubusercontent.com/13337108/174653382-f4337b52-0421-4337-b656-da0e6cd7c2e6.png)

When resize the window, the items are shown properly.

![image](https://user-images.githubusercontent.com/13337108/174653552-108cb851-7164-4618-ae43-b54ceedc254e.png)

### Steps to Reproduce

1. Go to https://github.com/Schinwinkwinsky/Pokedex and download the solution.
2. Run the solution on Windows.
3. Note that CollectionView items are overlapping.
4. Resize the window and see the items properly.

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10 19044.1766

**Comment by kristinx0211** [comment] 2022-07-01 09:08
verified repro on windows with above repro project.

**Comment by jpreece6** [comment] 2023-01-19 11:26
Any progress on this issue? Having the exact same problem on 7.0.52 Windows 10 19044.2364 where items in a collection view overlap and resizing the window positions the controls correctly

**Comment by Zhanglirong-Winnie** [comment] 2023-05-15 02:01
Verified this issue with Visual Studio Enterprise 17.6.0 Preview 7.0. Not repro on Windows platform with above project.
[Pokedex-master.zip](https://github.com/dotnet/maui/files/11473588/Pokedex-master.zip)
![Screenshot 2023-05-15 095641](https://github.com/dotnet/maui/assets/77434865/e7c70fb1-68db-42eb-bf2a-1bc0d37740af)

**Comment by Schinwinkwinsky** [comment] 2023-05-15 12:35
I'll try to update the project.

**Comment by samhouts** [comment] 2023-08-04 15:02
Duplicate of #10398

**Closed by samhouts** 2023-08-04 15:02 UTC
Labels: t/bug, area/collectionview 📃, s/triaged, s/try-latest-version
