### ISSUE TITLE
'IsEnable' property is not working with trigger in Button control

### ISSUE THREAD

**Issue by GSBarikParoksya** [dotnet/maui#21148] opened 2024-03-12 13:01 UTC
### Description

MAUI version 8.0
.Net version 8.0

IsEnable property is not working with trigger in Button Control in MAUI

### Steps to Reproduce

<Button Grid.Row="5" Text="Hello" Background="Red" Clicked="Button_Clicked" >
              <Button.Triggers>
                            <DataTrigger TargetType="Button" Binding="{Binding Source={x:ReferencepasswordEntry},Path=Text.Length}" Value="0">
                                <Setter Property="IsEnabled" Value="False" />
                            </DataTrigger>
                        </Button.Triggers>
        </Button>

### Version with bug

Unknown/Other

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, I was *not* able test on other platforms

**Comment by jfversluis** [comment] 2024-03-12 16:28
I'm very sorry but without any code, logs or specific version numbers whatsoever it's impossible to diagnose what potentially might be going on here. Because of that, I am closing this one for now.

If you still think this is potentially an issue in the .NET MAUI codebase, please open a new issue and provide is with all the requested details. Ideally a [reproduction sample](https://github.com/dotnet/maui/blob/main/.github/repro.md).

Thanks!

**Closed by jfversluis** 2024-03-12 16:28 UTC
Labels: t/bug

**Comment by GSBarikParoksya** [comment] 2024-03-13 04:57
<Button Grid.Row="5" Text="Hello" Background="Red" Clicked="Button_Clicked" >
              <Button.Triggers>
                            <DataTrigger TargetType="Button" Binding="{Binding Source={x:Reference passwordEntry},Path=Text.Length}" Value="0">
                                <Setter Property="IsEnabled" Value="False" />
                            </DataTrigger>
                        </Button.Triggers>
        </Button>

**Comment by GSBarikParoksya** [comment] 2024-03-13 04:58
`
<Button Grid.Row="5" Text="Hello" Background="Red" Clicked="Button_Clicked" >
              <Button.Triggers>
                            <DataTrigger TargetType="Button" Binding="{Binding Source={x:Reference passwordEntry},Path=Text.Length}" Value="0">
                                <Setter Property="IsEnabled" Value="False" />
                            </DataTrigger>
                        </Button.Triggers>

        </Button>
`

**Comment by GSBarikParoksya** [comment] 2024-03-13 04:58
`<Button Grid.Row="5" Text="Hello" Background="Red" Clicked="Button_Clicked" >
              <Button.Triggers>
                            <DataTrigger TargetType="Button" Binding="{Binding Source={x:Reference passwordEntry},Path=Text.Length}" Value="0">
                                <Setter Property="IsEnabled" Value="False" />
                            </DataTrigger>
                        </Button.Triggers>

        </Button>`

**Comment by GSBarikParoksya** [comment] 2024-03-13 04:59
<Button Grid.Row="5" Text="Hello" Background="Red" Clicked="Button_Clicked" >
              <Button.Triggers>
                            <DataTrigger TargetType="Button" Binding="{Binding Source={x:Reference passwordEntry},Path=Text.Length}" Value="0">
                                <Setter Property="IsEnabled" Value="False" />
                            </DataTrigger>
                        </Button.Triggers>

        </Button>
