### ISSUE TITLE
iOS - CollectionView inside of RefreshView does not size correctly

### ISSUE THREAD

**Issue by jamesmontemagno** [dotnet/maui#7315] opened 2022-05-19 01:15 UTC
### Description

Pull down - https://github.com/dotnet-presentations/dotnet-maui-workshop and run Finish project folder on iOS.

Notice that it is spanning of the page and overlapping the buttons.

### Steps to Reproduce

Pull down - https://github.com/dotnet-presentations/dotnet-maui-workshop and run Finish project folder on iOS.

Notice that it is spanning of the page and overlapping the buttons.

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS All

### Did you find any workaround?

Remove refresh view

**Comment by Hackmodford** [comment] 2022-06-07 18:44
I think I just ran into this issue?
The text in the the collectionview's emptyView is supposed to be centered.

<img width="438" alt="image" src="https://user-images.githubusercontent.com/326668/172458679-bd490386-d3a3-467c-9b4a-8797b6601caf.png">

**Comment by yairp03** [comment] 2022-06-15 10:29
Any workaround without removing the RefreshView?

**Comment by imsam67** [comment] 2022-07-20 22:38
Happening to me as well. I guess the only workaround is to place a button somewhere that allows user to refresh.

**Comment by yairp03** [comment] 2022-07-21 09:51
This issue is still labeled sr2... can someone please notice and update it please?

**Comment by RonnyRos** [comment] 2022-07-22 09:27
Seems like milestones are completed and released, but issues are left. What happends to the issues that are left? When will they be fixed?

**Comment by hunsra** [comment] 2022-07-27 16:10
Similar issue here, plus using a BoxView in the CollectionView.ItemTemplate causes the items to be stretched vertically whenever the RefreshView is pulled up or down.  Repro:  [https://github.com/hunsra/CVinRV](https://github.com/hunsra/CVinRV).  I'm using VS Windows 17.3.0 Preview 5 with the following workloads:

```
Installed Workload Ids      Manifest Version      Installation Source
--------------------------------------------------------------------------------
maccatalyst                 15.4.442/6.0.400      SDK 6.0.400, VS 17.3.32721.290
maui-android                6.0.424/6.0.400       SDK 6.0.400, VS 17.3.32721.290
runtimes-windows            6.0.7/6.0.300         VS 17.3.32721.290
maui-windows                6.0.424/6.0.400       VS 17.3.32721.290
maui-maccatalyst            6.0.424/6.0.400       VS 17.3.32721.290
maui-ios                    6.0.424/6.0.400       VS 17.3.32721.290
ios                         15.4.430/6.0.400      VS 17.3.32721.290
android                     32.0.447/6.0.400      VS 17.3.32721.290
```

**Comment by brminnick** [comment] 2022-09-05 22:38
On iOS, it appears that .NET MAUI lays out the `RefreshView` based on the device's width, even when the device is in Portrait. In the video below, we can see the `RefreshView` `ActivityIndicator` is partially offscreen on the right.

When the user rotates the device from Portrait to Landscape, the `RefreshView` indicator is centered properly, in approximately the same position on the page. In the video below, after rotating from Portrait to Landscape, the `RefreshView` `ActivityIndicator` is centered on the screen in approximately the same location (eg the x-y coordinates of the `ActivityIndicator` are the same as when it was in Portrait).

When the user then rotates back from Landscape to Portrait, the `RefreshView` ActivityIndicator` is properly centered on the screen.

![ScreenFlow](https://user-images.githubusercontent.com/13558917/188517784-44d515cd-4c7a-458f-8ada-6239ba3598d4.gif)

**Comment by yairp03** [comment] 2022-09-05 22:40
@brminnick thank you for clarifying this

**Comment by NonameMissingNo** [comment] 2022-09-05 22:42
Can you try if a workaround like this would work?
![image](https://user-images.githubusercontent.com/40233496/188518022-59bb1ef9-380f-4d38-8233-a4328ad990df.png)

#if IOS
                        list.WidthRequest = App.Current.Windows[0].Page.Width;
#endif

(Where list is obviously the name of the refreshview in this case)

**Comment by brminnick** [comment] 2022-09-05 22:58
I confirmed that setting `RefreshView.WidthRequest` and `RefreshView.MaximumWidthRequest` does not fix the problem.

Neither of the following work-arounds fix the issue. In both scenarios, the `RefreshView` `ActivityIndicator` appears in the same location.

### Scenario 1 Set `RefreshView.WidthRequest`
Does not work
```cs
WidthRequest = DeviceDisplay.MainDisplayInfo.Width / DeviceDisplay.MainDisplayInfo.Density
```

### Scenario 2: Set `RefreshView.MaximumWidthRequest`
Does not work
```cs
MaximumWidthRequest = DeviceDisplay.MainDisplayInfo.Width / DeviceDisplay.MainDisplayInfo.Density
```

**Comment by SophisticatedConsulting** [comment] 2022-09-10 14:09
Also have this issue... multiple distortions to a CollectionView inside a RefreshView:
1. With 1 item in the CollectionView, the item indents so only half of the item (a Border) is visible
2. With multiple items, 2 items are shown on the same line (the second only just visible on the edge of the display)
3. When all items displayed, the Margin on the right hand side is not applied (the item goes off the edge of the display)

**Comment by jpett** [comment] 2022-09-21 09:38
I think I found a workaround for now (on 6.0.400):
- Create a custom control (I named it ```ListContainer```) derived from ```ContentView```
- Create a ControlTemplate, placing the ```RefreshView``` inside
- Inside the ```RefreshView``` place a ContentPresenter

```xml
<ControlTemplate x:Key="ListContainerTemplate">
    <RefreshView IsRefreshing="{TemplateBinding IsRefreshing}" Command="{TemplateBinding RefreshDataCommand}">
        <ContentPresenter></ContentPresenter>
    </RefreshView>
</ControlTemplate>
```

If you now use ```ListContainer``` instead of the ```RefreshView``` the content seems to be sized correctly.

```xml
<custom:ListContainer RefreshDataCommand="{Binding RefreshData}" IsRefreshing="{Binding IsRefreshing}">
  <CollectionView .../>
</custom:ListContainer>
```

**Comment by hunsra** [comment] 2022-10-11 15:31
@jpett how did you associate the template with the control?

**Comment by imsam67** [comment] 2022-10-11 15:44
Any chance this is one of the "quality improvements" that made it into the .NET 7 version of MAUI?

I think this is a pretty important issue and am surprised that we still have to use workarounds to have this fundamental functionality in our apps.

**Comment by samirgcofficial** [comment] 2022-10-20 04:28
Any updates on this issue ? Till today ?

**Comment by samirgcofficial** [comment] 2022-10-20 07:26
Finally found out the solution which works for me. 
<Refreshview>
<Grid>
<CollectionView>
</CollectionView> 
</Grid>
</RefreshView> 

Enjoy :)

**Comment by 7702244** [comment] 2022-10-20 08:34
> Finally found out the solution which works for me.
> `<RefreshView> <Grid><CollectionView></CollectionView></Grid></RefreshView>`
> Enjoy :)

Thank you for the elegant and quick solution! It's surprising that Microsoft has not been able to fix this bug for several releases.

**Comment by SophisticatedConsulting** [comment] 2022-11-05 17:04
The workaround suggested by @samirgcofficial works for iOS and does not affect Android but it completely messes up the WinUI layout (worse than the original iOS issue).
Please can this be prioritised?

**Comment by imsam67** [comment] 2022-11-18 17:32
This solution actually no longer works due to the fact that when `CollectionView` is used with `RefreshView`, the whole app now freezes. This was not the case before I switched to .NET 7.

**Comment by jamesmontemagno** [comment] 2022-11-19 00:40
Try -> `<RefreshView><ContentView><CollectionView/></ContentView></RefreshView>`

**Comment by imsam67** [comment] 2022-11-19 16:55
@jamesmontemagno Thank you for trying but this approach only addresses the layout issue. There's still a problem with freezing. Interestingly, when I did this, the whole app doesn't freeze but looks like the refresh operation or at least the activity indicator seems stuck -- see image below. This screenshot is about a minute after I refreshed the `CollectionView` and the indicator is still frozen i.e. not spinning. I am, however, able to go to other tabs/pages and app seems to function OK. Just not the `CollectionView` with `RefreshView`.
![ScreenShot](https://user-images.githubusercontent.com/15844030/202862365-04088c32-4ee7-42b4-a58a-5c985ec4c365.jpg)

**Comment by hartez** [comment] 2022-12-08 20:28
This is fixed in the upcoming service release.

**Closed by hartez** 2022-12-08 20:28 UTC
Labels: t/bug, p/1, area/collectionview 📃, s/verified, s/triaged

**Comment by dan-SLT** [comment] 2022-12-30 16:35
> Finally found out the solution which works for me. `<RefreshView> <Grid><CollectionView></CollectionView></Grid></RefreshView>` Enjoy :)

Thank you!! This works.

**Comment by Syed-RI** [comment] 2023-01-04 11:53
> This is fixed in the upcoming service release.

Which version? @hartez

**Comment by richard-einfinity** [comment] 2023-01-29 00:35
This still appears to be an issue in Maui 7.0.58 @hartez

**Comment by jdunaway** [comment] 2023-02-07 01:03
This is still an issue for me with 17.4.4.

**Comment by DDHSchmidt** [comment] 2023-03-01 14:22
Can confirm this is still an issue with 7.0.59.
Since I see no linked PullRequest I wonder what was the base for closing this Issue?

**Comment by jbfranklin** [comment] 2023-03-02 06:35
It is still broken in 7.0.59 please reopen this bug. The workaround to wrap it around the grid breaks all other platforms.

**Comment by FM1973** [comment] 2023-03-29 16:47
@hartez 
Please, please make the fix available for .net 7 and don´t provide it just for .net 8 and backport it.
There are people who want to release their apps now and not in autumn 2023.
Thanks for your hard work!!! Really!!!

**Comment by justcivah** [comment] 2023-03-29 16:54
When can we (finally) expect a fix for this bug?

**Comment by bmclane** [comment] 2023-04-01 15:39
https://github.com/dotnet/maui/pull/14302

**Comment by fgiacomelli** [comment] 2023-04-27 08:51
still present and solved with @samirgcofficial workaround

**Comment by rmarinho** [comment] 2023-04-28 11:29
@fgiacomelli  this fix wasn't release yet, should be in the next net8 preview4

**Comment by imsam67** [comment] 2023-04-28 12:41
So, this issue won't be addressed for those of us who will target .net 7 until .net 8 is officially released in November?

**Comment by rmarinho** [comment] 2023-04-28 14:52
It's marked as suggested to backport, but we didn't reach to talk about this one yet.

**Comment by FM1973** [comment] 2023-04-28 15:02
@rmarinho 
This bug exists almost a year like some other major bugs.
Please start solving problems users have right now, instead of implementing fixes for a framework version which will be available for production in a couple of months.

**Comment by Hackmodford** [comment] 2023-04-28 17:03
This bug is the reason I don’t have confidence in .Net MAUI
