### ISSUE TITLE
[Android]RTL flow direction not working in Button

### ISSUE THREAD

**Issue by jeya-kasipandi** [dotnet/maui#4742] opened 2022-02-17 06:57 UTC
### Description

When setting Flow direction to RightToLeft to the button  added parent and the button not changed based on flow direction in Android.

### Steps to Reproduce

1. Run the attached sample
[RTLSample.zip](https://github.com/dotnet/maui/files/8086249/RTLSample.zip)

2. See the below output. Button not aligned based on the RTL flow direction. Labels are aligned based on the RTL flow direction.

![Screenshot_1645080851](https://user-images.githubusercontent.com/92785406/154421724-4be409a5-a815-4360-86ca-660e8bb8a05c.png)

### Version with bug

Preview 13 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

### Did you find any workaround?

NO

**Comment by XamlTest** [comment] 2022-02-25 11:11
Reproduced on Android(OS: Android 12.0-API31).
Repro Project: [4742-RTLFlowDirection.zip](https://github.com/dotnet/maui/files/8140646/4742-RTLFlowDirection.zip)

**Comment by buyaa-n** [comment] 2022-03-07 21:07
I am working on this issue

**Comment by buyaa-n** [comment] 2022-03-16 17:41
The issue in the description caused by the `HorizontalOptions` value of `Fill` which is fixed by https://github.com/dotnet/maui/pull/5251. There is another issue happening on windows will be fixed by https://github.com/dotnet/maui/pull/5205

**Closed** 2022-03-17 22:21 UTC
Labels: t/bug, 💡good first issue, platform/android 🤖, area/controls 🎮, area/localization, s/verified, control-button, s/triaged
