### ISSUE TITLE
Hot Reload Problem : Read out of bounds

### ISSUE THREAD

**Issue by sezercik** [dotnet/maui#9363] opened 2022-08-11 21:47 UTC
### Description

I use Visual Studio 17.3. First time  I used .NET MAUI BLAZORAPP yesterday and everythings worked well but today I get some errors.

### Steps to Reproduce

1. Create a File -> New .NET MAUI BLAZOR APP
2. Added one page, added some blazor code in page and edited NavMenu for page 
3. Hot Reload worked for step two
4. After one day, I Opened project again
5. I got an error 'You can't started components bane with lowercase characters' two same error
6. Ex. test.razor, I changed components to Test.razor, one error gone one still here
7. I deleted Test.razor file from pages folder and added new one called Testing.razor and edited NavMenu 
8. Projects work, I changed some codes on Testing.razor and clicked on Hot Reload button
9. Hot Reload not worked, nothing changed and i don't get any error
10. I restarted Visual Studio and tested Hot Reload again but I get an error 'Severity	Code	Description	Project	File	Line	Suppression State
Error	ENC1002	Cannot apply changes -- unexpected error: 'Read out of bounds.'			1	Active'
11. I restarted my computer and tried again but still get same error.

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Windows SDK 10.0.19041.0

### Relevant log output

```shell
Severity	Code	Description	Project	File	Line	Suppression State
Error	ENC1002	Cannot apply changes -- unexpected error: 'Read out of bounds.'			1	Active
```

**Comment by TanayParikh** [comment] 2022-08-11 23:01
Hey @sezercik, thanks for contacting us. Are you able to provide a minimal, public, github repository which reproduces this issue?

**Comment by sezercik** [comment] 2022-08-11 23:06
@TanayParikh Of course but I will make you wait a bit

**Comment by sezercik** [comment] 2022-08-11 23:16
> Hey @sezercik, thanks for contacting us. Are you able to provide a minimal, public, github repository which reproduces this issue?

https://github.com/sezercik/.NET-MAUI-Blazor-APP

**Comment by TanayParikh** [comment] 2022-08-12 03:44
Thanks @sezercik. 

> Error ENC1002 Cannot apply changes -- unexpected error: 'Read out of bounds.' 1 Active'

@tmat is this potentially a known issue?

**Comment by jbienzms** [comment] 2022-11-06 01:03
Came here to +1 this bug. The ENC1002 error only seems to occur after a change has been made to a .razor file. For context, my .razor file exists in a non-default folder. It does have an @page directive, but it's initially loaded via BlazorWebView.RootComponents.

This issue seems very similar to [4989](https://github.com/dotnet/maui/issues/4989). That issue was marked as closed, but some users reported it as not fixed before msftbot locked the thread.

**Comment by Eilon** [comment] 2023-01-20 19:38
@mcumming - can you take a look at this?

**Comment by Neutrino-Sunset** [comment] 2023-02-11 21:46
I'm getting this constantly.

I find a starter Maui Blazor project works until I create a razor file with a partial class, e.g `Test.razor` and `Test.razor.cs`. Once I've done that hot reload never works on the partial class or any other razor file I create thereafter, but bizarrely hot reload continues to work on the files that were in the startup project when it was orginally created.

It's a real nightmare as these Maui apps take so long to load that having to reload them every time you make a single UI change is just an appalling workflow.

**Comment by Neutrino-Sunset** [comment] 2023-02-12 13:25
After having this working when not using a code behine file for a while, it did then stop working completely despite the exact same code working in another project. Cleaning the project and rebuilding then got it working again.

**Comment by euo** [comment] 2023-02-20 03:49
I've just encountered the same issue for VS 2022 ver 17.4.4. 
It's a Web Api project, .NET 6.

Cleaning the solution, closing VS, restarting the machine were not solving the problem.

**Comment by Neutrino-Sunset** [comment] 2023-02-20 08:59
Same here. Even after cleaning the project and restarting, it worked for a bit then broke again.

**Comment by derekcripps** [comment] 2023-02-22 14:08
I am experiencing the same issue with both VS 2022 17.6 Preview 1 and VS 2022 17.5

**Comment by areeb64** [comment] 2023-04-09 22:18
I am facing the same issue on Visual Studio 2022 17.5.3, Not only in the razor file even if I change something in my controllers or just hit Ctrl + S to save the document, it pops up with multiple windows on top of each other, it consists of two options "Edit, Close" which I have to click multiple times to get rid of all the error windows. 
**ENC1002 Cannot apply changes -- unexpected error: 'Read out of bounds'**

**Comment by tmat** [comment] 2023-04-10 16:08
@areeb64 

To help us determine the root cause of the issue, please provide step-by-step instructions how to reproduce it (please file a separate issue or https://learn.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2022).
Alternatively, you can also collect and share detailed logs like so:

1) Run the following commands from Developer Command Prompt for Visual Studio:

```
**********************************************************************
** Visual Studio 2022 Developer Command Prompt
** Copyright (c) 2022 Microsoft Corporation
**********************************************************************

C:\Program Files\Microsoft Visual Studio\2022\Preview> set Microsoft_CodeAnalysis_EditAndContinue_LogDir=%temp%\HotReloadLog
C:\Program Files\Microsoft Visual Studio\2022\Preview> devenv
```

2) Zip the directory `%temp%\HotReloadLog` and attach it to a github issue (public) or VS Feedback (private)

**Comment by kado** [comment] 2023-05-29 16:27
Got same error with a .NET 7 MAUI Blazor App. Microsoft Visual Studio Community 2022 (64-bit) 17.6.0.  

Error List: Error ENC1002 Cannot apply changes -- unexpected error: 'Read out of bounds.' 1 Active'
Hot reload output: Invalid changes were found. Please refer to the Error List window to fix those issues.


Hot reload started to work again after a clean build (Build > Clean ProjectName).

**Comment by homeyf** [comment] 2023-09-25 07:28
Verified this issue with Visual Studio Enterprise 17.8.0 Preview 2.0. Not repro on windows platform with sample project.
https://github.com/sezercik/.NET-MAUI-Blazor-APP

**Comment by Vizzey** [comment] 2023-09-30 10:24
> Got same error with a .NET 7 MAUI Blazor App. Microsoft Visual Studio Community 2022 (64-bit) 17.6.0.
> 
> Error List: Error ENC1002 Cannot apply changes -- unexpected error: 'Read out of bounds.' 1 Active' Hot reload output: Invalid changes were found. Please refer to the Error List window to fix those issues.
> 
> Hot reload started to work again after a clean build (Build > Clean ProjectName).

Problem still exists on 30.09.2023 at the latest VS 17.7.4 version

Only cleaning build forces it to dissapear

**Closed** 2023-10-07 13:01 UTC
Labels: t/bug, area/tooling ⚙️, p/1, s/triaged, s/try-latest-version

**Comment by BirkOFH** [comment] 2023-10-24 03:18
Problem still exists on 24.10.2023 at the latest VS 17.7.5 version

Only cleaning build forces it to dissapear
