### ISSUE TITLE
Border with URL source does not render correctly

### ISSUE THREAD

**Issue by mcumming** [dotnet/maui#12400] opened 2023-01-03 20:48 UTC
### Description

When using this fragment:
```xaml
<Border StrokeShape="RoundRectangle 15,15,15,15" Padding="0" Margin="0,0,0,0" BackgroundColor="#667788" >
    <Image Source="https://img-s-msn-com.akamaized.net/tenant/amp/entityid/AA15VZhC.img?w=768&amp;h=513&amp;m=6" Aspect="AspectFill" HeightRequest="55" HorizontalOptions="Center" VerticalOptions="Center" />
</Border>
```
The first time the app is run the image will not be displayed and you will only get a grey filled border:
![image](https://user-images.githubusercontent.com/757221/210437120-fd6eeadc-d347-431b-a401-4c316385043b.png)

The subsequent times the app is run, the image displays but ignores the `Border` clipping for the rounded corners:
![image](https://user-images.githubusercontent.com/757221/210436985-cfcc444b-9207-4e2d-bab0-41bba80480b9.png)

### Steps to Reproduce

1. Create a File -> New -> .Net MAUI App
2. Add the following code to the MainPage.Xaml file
```xaml
<Border StrokeShape="RoundRectangle 15,15,15,15" Padding="0" Margin="0,0,0,0" BackgroundColor="#667788" >
    <Image Source="https://img-s-msn-com.akamaized.net/tenant/amp/entityid/AA15VZhC.img?w=768&amp;h=513&amp;m=6" Aspect="AspectFill" HeightRequest="55" HorizontalOptions="Center" VerticalOptions="Center" />
</Border>
```
3. Run the App on an iOS device
4. Stop, then run the app on an iOS device

Expected outcome:
The image is displayed within the rounded Border with clipping on the all runs of the app

Actual outcome:
The first run, only the rounded Border is displayed
On subsequent runs, only the image is displayed (appears to ignore the Border)

### Link to public reproduction project repository

https://github.com/mcumming/.NET-MAUI-Border

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 16.1

### Did you find any workaround?

No

**Comment by rachelkang** [comment] 2023-01-04 19:15
Duplicate of #10724

**Closed by rachelkang** 2023-01-04 19:15 UTC
Labels: t/bug, platform/iOS 🍎, area/image :framed_picture:, area/controls 🎮, control-border
