### ISSUE TITLE
Add support for appsettings.json

### ISSUE THREAD

**Issue by dannyBies** [dotnet/maui#3446] opened 2021-11-18 13:59 UTC
### Description

I would like to have support for `appsettings.json` so I can use settings configured in this file in my MAUI app. 

When this is implemented, adding an `appsettings.json` file to your MAUI project will automatically load the configuration inside it.

I'm using the following code to workaround this issue.
```
var builder = MauiApp.CreateBuilder();
            builder
                .RegisterBlazorMauiWebView()
                .UseMauiApp<App>()
                .ConfigureFonts(fonts =>
                {
                    fonts.AddFont("OpenSans-Regular.ttf", "OpenSansRegular");
                })
                .Host
                .ConfigureAppConfiguration((app, config) =>
                {
                    var assembly = typeof(App).GetTypeInfo().Assembly;
                    config.AddJsonFile(new EmbeddedFileProvider(assembly), "appsettings.json", optional: false, false);
                });
```

### Public API Changes

I believe no public API changes are necessary 

### Intended Use-Case

Currently I'm trying to get my Blazor WebAssembly app to work in .NET MAUI. To make this possible I've created a Razor Class Library that contains all the shared components. In this project I also setup my dependency container which needs access to settings I have configured in an `appsettings.json` file.

In my Blazor WebAssembly app a call to `WebAssemblyHostBuilder.CreateDefault(args);` will automatically load the neccessary `appsettings.json` files. It would be great if the same can be done for `MauiApp.CreateBuilder();`

**Comment by hflexgrig** [comment] 2021-12-23 12:17
Created PR for this https://github.com/dotnet/maui/pull/3844

**Comment by Dreamescaper** [comment] 2021-12-29 15:11
IMHO, that's not a workaround, but a perfectly valid solution.

(you can use `typeof(App).Assembly` directly though).

**Comment by hflexgrig** [comment] 2021-12-29 15:49
@Dreamescaper I created another PR using embedded resources, but little different approach, also with workaround for unittests. 

https://github.com/dotnet/maui/pull/3872

**Comment by jfversluis** [comment] 2022-06-15 11:50
Duplicate of #4408

**Closed by jfversluis** 2022-06-15 11:50 UTC
Labels: proposal/open, area/hosting 🧩
