### ISSUE TITLE
VS 17.3.4 Breaks Android build with - Manifest file at 'obj\Debug\net6.0-android\android-arm\staticwebassets.build.json' not found

### ISSUE THREAD

**Issue by jordanwilcox** [dotnet/maui#10102] opened 2022-09-13 22:19 UTC
### Description

Since updating to VS 17.3.4 I can't build any MAUI Android projects on my machine.

I have verified this on two devices running VS - before updating to VS 17.3.4 it was building ok - post update to 17.3.4 the build errors show for android.

I am unable to verify if this affects iOS but the build errors seem to point only at android.

This is happening on `dotnet --version` 6.0.401

### Steps to Reproduce

1. Update to VS 17.3.4
2. Create a brand new MAUI project (I used MAUI blazor for testing)
3. Attempt a build
4. Fails

### Link to public reproduction project repository

https://github.com/jordanwilcox/maui-build-error-android-17.3.4

### Version with bug

SDK 6.0.401

### Last version that worked well

SDK 6.0.400

### Affected platforms

Android

### Affected platform versions

All android platforms

### Did you find any workaround?

[Workaround found by @cupsos by changing global.json in solution to sdk version 6.0.400](https://github.com/dotnet/maui/issues/10102#issuecomment-1246388109)

### Relevant log output

```shell
1>C:\Program Files\dotnet\sdk\6.0.401\Sdks\Microsoft.NET.Sdk.Razor\targets\Microsoft.NET.Sdk.Razor.StaticWebAssets.targets(680,7): error : Manifest file at 'obj\Debug\net6.0-android\android-arm\staticwebassets.build.json' not found.
1>C:\Program Files\dotnet\sdk\6.0.401\Sdks\Microsoft.NET.Sdk.Razor\targets\Microsoft.NET.Sdk.Razor.StaticWebAssets.targets(680,7): error : Manifest file at 'obj\Debug\net6.0-android\android-x86\staticwebassets.build.json' not found.
1>Done building project "MauiApp1.csproj" -- FAILED.
1>C:\Program Files\dotnet\sdk\6.0.401\Sdks\Microsoft.NET.Sdk.Razor\targets\Microsoft.NET.Sdk.Razor.StaticWebAssets.targets(680,7): error : Manifest file at 'obj\Debug\net6.0-android\android-x64\staticwebassets.build.json' not found.
1>Done building project "MauiApp1.csproj" -- FAILED.
1>C:\Program Files\dotnet\sdk\6.0.401\Sdks\Microsoft.NET.Sdk.Razor\targets\Microsoft.NET.Sdk.Razor.StaticWebAssets.targets(680,7): error : Manifest file at 'obj\Debug\net6.0-android\android-arm64\staticwebassets.build.json' not found.
1>Done building project "MauiApp1.csproj" -- FAILED.
```

**Comment by peter-bozovic** [comment] 2022-09-14 07:02
Same issue here :(

**Comment by GioviQ** [comment] 2022-09-14 07:23
Closing VS, deleting bin and obj folder works for the first build, then the error appears again

**Comment by cupsos** [comment] 2022-09-14 07:58
I'm on the same boat.

If you want to use VS 17.3.4 with MAUI now, try this.

1. Install SDK [6.0.400](https://dotnet.microsoft.com/en-us/download/dotnet/6.0)
2. Specify SDK version as `6.0.400` at [global.json](https://docs.microsoft.com/en-us/dotnet/core/tools/global-json)

```json
{
    "sdk": {
        "version": "6.0.400"
    }
}
```

Maybe SDK issue?

**Comment by jessestr** [comment] 2022-09-14 10:50
Same issue. Uninstalled 17.3.4 and installed 17.3.2 again and now it's totally bricked.

**Comment by GioviQ** [comment] 2022-09-14 11:34
But SDK has been correctly updated from Visual Studio. No need to do separete setup
![Immagine 2022-09-14 133225](https://user-images.githubusercontent.com/7103057/190142929-1daf6a8c-83cf-449b-bf8c-04d1acc69505.png)

**Comment by hamedhajiloo** [comment] 2022-09-14 12:15
Same issue! :/

**Comment by stimm4711** [comment] 2022-09-14 12:23
Having this issue, too...

**Comment by mhrastegari** [comment] 2022-09-14 12:51
same here :(

**Comment by ltemimi** [comment] 2022-09-14 14:55
same here rolling back to previous version this crazy

**Comment by stimm4711** [comment] 2022-09-14 15:04
> I'm on the same boat.
> 
> If you want to use VS 17.3.4 with MAUI now, try this.
> 
> 1. Install SDK [6.0.400](https://dotnet.microsoft.com/en-us/download/dotnet/6.0)
> 2. Specify SDK version as `6.0.400` at [global.json](https://docs.microsoft.com/en-us/dotnet/core/tools/global-json)
> 
> ```json
> {
>     "sdk": {
>         "version": "6.0.400"
>     }
> }
> ```
> 
> Maybe SDK issue?

Helped me! Just needed to add the global.json in the solution folder to use the SDK version 6.0.400. Thanks.

**Comment by jordanwilcox** [comment] 2022-09-14 16:00
> I'm on the same boat.
> 
> If you want to use VS 17.3.4 with MAUI now, try this.
> 
> 1. Install SDK [6.0.400](https://dotnet.microsoft.com/en-us/download/dotnet/6.0)
> 2. Specify SDK version as `6.0.400` at [global.json](https://docs.microsoft.com/en-us/dotnet/core/tools/global-json)
> 
> ```json
> {
>     "sdk": {
>         "version": "6.0.400"
>     }
> }
> ```
> 
> Maybe SDK issue?

Thank you this works for me too, I have updated the main ticket with this workaround to help others. 😊

**Comment by GreatIdeaz** [comment] 2022-09-14 19:38
It's already 6.0.401 :) if you follow the link !

**Comment by danfer** [comment] 2022-09-14 20:40
> It's already 6.0.401 :) if you follow the link !

Yeah, can't find 6.0.400, hope it gets fixed soon

**Comment by danfer** [comment] 2022-09-14 20:51
Ok guys, for the meantime, I was able to make it to work, just did a search for file staticwebassets.build.json and find it at folder net6.0-android, so just copied it at folders where building was breaking and now it is working, cheers.

**Comment by Haichen-Dong** [comment] 2022-09-14 21:02
It works. Thank you.

**Comment by binkycs** [comment] 2022-09-15 01:45
> Ok guys, for the meantime, I was able to make it to work, just did a search for file staticwebassets.build.json and found it at folder net6.0-android, so just copied it at folders where building was breaking and now it is working, cheers.

I found the 6.0.400 SDK at a different website third-party but it still did not work for me. This workaround did, however.

Here's the link to the third-party site in case someone gets any use out of it: https://versionsof.net/core/6.0/6.0.8/

**Comment by dsuny** [comment] 2022-09-15 06:38
obj\Debug\net6.0-android\staticwebassets.build.json
Copy
obj\Debug\net6.0-android\android-arm64\staticwebassets.build.json

**Comment by TrabacchinLuigi** [comment] 2022-09-15 08:36
tried both the sdk and the file copy one, still if complains about missing dependencies now

**Comment by hamedhajiloo** [comment] 2022-09-15 10:33
The problem still remains!

What is this ridiculous game? No one from Microsoft has replied, please answer :/

**Comment by matheusjulio96** [comment] 2022-09-15 17:09
Same issue here

**Comment by MargaritaLoseva** [comment] 2022-09-15 19:39
The same issue

**Comment by KieranDevvs** [comment] 2022-09-15 23:08
Same issue here.

**Comment by isaac-borrero** [comment] 2022-09-15 23:58
Same issue here.

**Comment by xiangnanscu** [comment] 2022-09-16 00:09
Same issue here

**Comment by l3bel** [comment] 2022-09-16 02:13
**Updating Solution's Nuget Packages** is the only thing that worked for me.
Note: I was getting that Android error when trying to build for iOS Simulator!?

**Comment by transnity** [comment] 2022-09-16 06:11
this work for me, download & install sdk 6.0.400 
https://download.visualstudio.microsoft.com/download/pr/9a1d2e89-d785-4493-aaf3-73864627a1ea/245bdfaa9c46b87acfb2afbd10ecb0d0/dotnet-sdk-6.0.400-win-x64.exe

rename sdk 6.0.401 in C:\Program Files\dotnet\sdk
![Screenshot_164](https://user-images.githubusercontent.com/62492925/190568422-bb9f5fc9-12c1-4b99-87ea-775fa90db660.png)

**Comment by TrabacchinLuigi** [comment] 2022-09-16 06:38
Updated nuget packages still won't work.
Seem to me that it's related to project dependencies or MAUI + Blazor.
i managed to build a MAUI project that is not MAUI + Blazor and don't have references to other projects even without Global.json modifications.
(i can see the line `You are using a preview version of .NET` so probably it's using `7.0.100-preview.7` which is the latest preview available in my machine)

**Comment by HarryLobster** [comment] 2022-09-16 13:18
> ```json
> {
>     "sdk": {
>         "version": "6.0.400"
>     }
> }
> ```

Thanks, that fixed it for me !

**Comment by HarryLobster** [comment] 2022-09-16 13:18
> this work for me, download & install sdk 6.0.400 https://download.visualstudio.microsoft.com/download/pr/9a1d2e89-d785-4493-aaf3-73864627a1ea/245bdfaa9c46b87acfb2afbd10ecb0d0/dotnet-sdk-6.0.400-win-x64.exe
> 
> rename sdk 6.0.401 in C:\Program Files\dotnet\sdk ![Screenshot_164](https://user-images.githubusercontent.com/62492925/190568422-bb9f5fc9-12c1-4b99-87ea-775fa90db660.png)

Thanks, that fixed it for me !

**Comment by acxsasx** [comment] 2022-09-16 13:49
Same issue.  Trying to be productive with Maui/Blazor is tedious.

**Comment by KieranDevvs** [comment] 2022-09-16 14:50
> 

Give it two years, all new MS products are sketchy at the start, look at .NET core for example.

**Comment by david-palladino** [comment] 2022-09-16 15:03
I'm also having trouble, this issue prevents me from compiling my .NET Maui apps in the latest Visual Studio release for Windows, version 17.3.4.

**Comment by isaac-borrero** [comment] 2022-09-16 15:06
The 'dotnet-sdk-6.0.400-win-x64.exe)' solution listed above does not work for me, unfortunately. I was really hoping to have this fixed, since I am dead in the water until I can compile my solution.

**Comment by isaac-borrero** [comment] 2022-09-16 15:16
The above 'dotnet-sdk-6.0.400-win-x64.exe' workaround solved the problem for me! Thanks @transnity .  Your help is much appreciated!

**Comment by GreatIdeaz** [comment] 2022-09-16 15:27
Worked for me also 😊 Thanks for the help everyone!

**Comment by samhouts** [comment] 2022-09-16 16:38
Thank you everyone for reporting the issue! We're also tracking this at https://developercommunity.visualstudio.com/t/Build-failed-with-error-Manifest-file-a/10144594. This will be resolved very soon!

**Comment by xiangnanscu** [comment] 2022-09-18 15:54
@samhouts hello. I follow your advice and run `dotnet workload update` and can't create maui blazor project anymore (no template), what should do I do?

**Comment by dsuny** [comment] 2022-09-18 23:58
> https://developercommunity.visualstudio.com/t/Build-failed-with-error-Manifest-file-a/10144594

dotnet workload restore

^^*

**Comment by xiangnanscu** [comment] 2022-09-19 01:17
@dsuny you'r the best!

**Comment by xiangnanscu** [comment] 2022-09-19 01:17
@dsuny you'r the best!

**Comment by sumo2394** [comment] 2022-09-19 15:48
> obj\Debug\net6.0-android\staticwebassets.build.json Copy obj\Debug\net6.0-android\android-arm64\staticwebassets.build.json

Right now I guess this is the best workaround till Microsoft provides with a solution. 
Thanks

**Comment by KieranDevvs** [comment] 2022-09-19 16:24
> Right now I guess this is the best workaround till Microsoft provides with a solution.
Thanks

No the advised workaround is to run `dotnet workload restore` in the project directory.

**Comment by ryanjshaw** [comment] 2022-09-19 22:46
> > https://developercommunity.visualstudio.com/t/Build-failed-with-error-Manifest-file-a/10144594
> 
> dotnet workload restore

For those who deleted the failing project and so can't perform a `dotnet workload restore`, try `dotnet workload install maui` instead.

**Comment by PaulSorauer-IPG** [comment] 2022-09-20 03:59
> this work for me, download & install sdk 6.0.400 https://download.visualstudio.microsoft.com/download/pr/9a1d2e89-d785-4493-aaf3-73864627a1ea/245bdfaa9c46b87acfb2afbd10ecb0d0/dotnet-sdk-6.0.400-win-x64.exe
> 
> rename sdk 6.0.401 in C:\Program Files\dotnet\sdk ![Screenshot_164](https://user-images.githubusercontent.com/62492925/190568422-bb9f5fc9-12c1-4b99-87ea-775fa90db660.png)

Also worked for me. Thanks @transnity

**Comment by OskrLrba** [comment] 2022-09-20 11:05
@transnity , thank you very much, That's worked!

**Comment by tb-mtg** [comment] 2022-09-21 00:46
A temporary fix that worked for  me is added below to the .csproj file:

```
  <Target Name="TempFixBeforeBuild" BeforeTargets="BeforeBuild">
    <Copy SourceFiles="$(ProjectDir)obj\Release\net6.0-android\staticwebassets.build.json" DestinationFiles="$(ProjectDir)obj\Release\net6.0-android\android-arm\staticwebassets.build.json" />
    <Copy SourceFiles="$(ProjectDir)obj\Release\net6.0-android\staticwebassets.build.json" DestinationFiles="$(ProjectDir)obj\Release\net6.0-android\android-arm64\staticwebassets.build.json" />
    <Copy SourceFiles="$(ProjectDir)obj\Release\net6.0-android\staticwebassets.build.json" DestinationFiles="$(ProjectDir)obj\Release\net6.0-android\android-x64\staticwebassets.build.json" />
    <Copy SourceFiles="$(ProjectDir)obj\Release\net6.0-android\staticwebassets.build.json" DestinationFiles="$(ProjectDir)obj\Release\net6.0-android\android-x86\staticwebassets.build.json" />
  </Target>
```

**Comment by vallgrenerik** [comment] 2022-09-21 06:08
Has anyone tried the new VS update? 17.4.0 Preview 2.1 released September 20th

**Comment by stallprobbe** [comment] 2022-09-21 07:11
Try it just now, it works :-)

**Comment by tibitoth** [comment] 2022-09-21 10:55
Azure DevOps CI pipelines are starting to fail now

**Comment by sake402** [comment] 2022-09-21 16:30
Don't really understand why every MS tool update must break something. I updated hoping something else will be fixed, but something else got broken.

Reverting back.

**Comment by arsalanhub** [comment] 2022-09-22 10:55
> Same issue. Uninstalled 17.3.4 and installed 17.3.2 again and now it's totally bricked. Reinstalled 17.3.4, same errors again as @jordanwilcox stated in initial post.
> 
> Tried to install the 6.0.400 SDK and put it in the global.json but doesn't work.
> 
> **Global.json was in the wrong directory for some reason. Works again now with 6.0.400**
> 
> Also seems like it's rebuilding everytime you deploy to a local Android device. Takes ages to test things. Edit: fast deploy was automatically disabled after the update...

Where can I find Global.json file? Also you said Global.json was in wrong directory. Can you tell me what should be location of Global.json?

**Comment by liebki** [comment] 2022-09-22 12:56
Here you go, it's a file you need to create in the project/solution.
https://learn.microsoft.com/en-us/dotnet/core/tools/global-json
https://alessio.franceschelli.me/posts/dotnet/should-i-use-global-json/


> > Same issue. Uninstalled 17.3.4 and installed 17.3.2 again and now it's totally bricked. Reinstalled 17.3.4, same errors again as @jordanwilcox stated in initial post.
> > Tried to install the 6.0.400 SDK and put it in the global.json but doesn't work.
> > **Global.json was in the wrong directory for some reason. Works again now with 6.0.400**
> > Also seems like it's rebuilding everytime you deploy to a local Android device. Takes ages to test things. Edit: fast deploy was automatically disabled after the update...
> 
> Where can I find Global.json file? Also you said Global.json was in wrong directory. Can you tell me what should be location of Global.json?

**Comment by danroth27** [comment] 2022-09-23 00:25
> @samhouts hello. I follow your advice and run `dotnet workload update` and can't create maui blazor project anymore (no template), what should do I do?

@xiangnanscu There appears to be an issue with `dotnet workload update` when .NET MAUI was installed using VS. Instead, run `dotnet workload install maui` to bring back the templates and get the latest .NET MAUI bits that fix this issue. Note that this will only install .NET MAUI for the active .NET SDK. You can switch the active .NET SDK by creating a global.json file with the desired .NET SDK version.

**Comment by danroth27** [comment] 2022-09-23 21:08
@xiangnanscu I believe `dotnet workload restore` basically does a `dotnet workload install` for the workloads it detects a project needs.

**Comment by alexdbkim** [comment] 2022-09-24 04:42
@tb-mtg your workaround resolved this issue! Thank you. I modified little bit on you suggestion to support both Debug build and Release build.

`
  <Target Name="TempFixBeforeBuild" BeforeTargets="PreBuildEvent" >
    <Copy SourceFiles="$(ProjectDir)obj\$(Configuration)\net6.0-android\staticwebassets.build.json" DestinationFiles="$(ProjectDir)obj\$(Configuration)\net6.0-android\android-arm\staticwebassets.build.json" />
    <Copy SourceFiles="$(ProjectDir)obj\$(Configuration)\net6.0-android\staticwebassets.build.json" DestinationFiles="$(ProjectDir)obj\$(Configuration)\net6.0-android\android-arm64\staticwebassets.build.json" />
    <Copy SourceFiles="$(ProjectDir)obj\$(Configuration)\net6.0-android\staticwebassets.build.json" DestinationFiles="$(ProjectDir)obj\$(Configuration)\net6.0-android\android-x64\staticwebassets.build.json" />
    <Copy SourceFiles="$(ProjectDir)obj\$(Configuration)\net6.0-android\staticwebassets.build.json" DestinationFiles="$(ProjectDir)obj\$(Configuration)\net6.0-android\android-x86\staticwebassets.build.json" />
  </Target>
`

**Comment by danroth27** [comment] 2022-09-26 15:22
@alexdbkim Did you try running `dotnet workload install maui` to get the latest .NET MAUI servicing release, which should have a fix for this issue?

**Comment by tb-mtg** [comment] 2022-09-27 03:16
Thanks @alexdbkim - I think doing the `workload install maui` has fixed my issue.

**Comment by shugaoye** [comment] 2022-09-27 05:38
> <Target Name="TempFixBeforeBuild" BeforeTargets="PreBuildEvent" >
>     <Copy SourceFiles="$(ProjectDir)obj\$(Configuration)\net6.0-android\staticwebassets.build.json" DestinationFiles="$(ProjectDir)obj\$(Configuration)\net6.0-android\android-arm\staticwebassets.build.json" />
>     <Copy SourceFiles="$(ProjectDir)obj\$(Configuration)\net6.0-android\staticwebassets.build.json" DestinationFiles="$(ProjectDir)obj\$(Configuration)\net6.0-android\android-arm64\staticwebassets.build.json" />
>     <Copy SourceFiles="$(ProjectDir)obj\$(Configuration)\net6.0-android\staticwebassets.build.json" DestinationFiles="$(ProjectDir)obj\$(Configuration)\net6.0-android\android-x64\staticwebassets.build.json" />
>     <Copy SourceFiles="$(ProjectDir)obj\$(Configuration)\net6.0-android\staticwebassets.build.json" DestinationFiles="$(ProjectDir)obj\$(Configuration)\net6.0-android\android-x86\staticwebassets.build.json" />
>   </Target>

I have the same issue and use the above workaround temporarily.

**Comment by alexdbkim** [comment] 2022-09-27 06:06
@danroth27 @tb-mtg Yes I can confirm the suggested commend fixed the issue. I can build without the temporary workaround now.

FIX:
`dotnet workload install maui`

**Comment by stallprobbe** [comment] 2022-09-28 06:45
Can't make a release even in the latest preview, Maui is a big joke, works at a start-up company, wonder if it's a playhouse :-(
Xamarin:forms worked anyway, Maui really sucks

**Comment by PaulSorauer-IPG** [comment] 2022-09-28 11:34
> Can't make a release even in the latest preview, Maui is a big joke, wonder if it's a playhouse on Microsoft :-( Xamarin:forms worked anyway, Maui really sucks

@stallprobbe Prolly trolling on purpose, but just in case you're not.... Do you understand the meaning of preview?

**Comment by TrabacchinLuigi** [comment] 2022-09-28 11:59
Obviusly he does, he meant not realeaser nor preview was succesfull if delivering a release build.
BTW: this is a free open source project if things don' suit you you can always A: go back to xamarin B: make a pull request.
Complaining here will only make me unsubscribe from this thread.

**Comment by stallprobbe** [comment] 2022-09-28 12:23
> Prolly trolling on purpose, but just in case you're not.... Do you understand the meaning of preview?

I pay big money for my licence of visual studio 2022, after update nothing work, shall it be so?

**Comment by stallprobbe** [comment] 2022-09-28 12:29
> > Prolly trolling on purpose, but just in case you're not.... Do you understand the meaning of preview?
> 
> I pay big money for my licence of visual studio 2022, after update nothing work, shall it be so?

Not use previews, but need to change to a preview to not stop my work, but I can not do a release build either in standard or the preview!

**Comment by OskrLrba** [comment] 2022-09-28 12:34
I have just updated to VS 17.3.5. It seems it's ok but yesterday I run **dotnet workload install maui** as @danroth suggested so I don't know if this new version fixes this issue. Have you tested it?

**Comment by GreatIdeaz** [comment] 2022-09-28 12:34
VS dropped a new release 17.3.5 yesterday that fixed the problem for me!

Tony Nicholls
705 543 1312
________________________________

**Comment by GreatIdeaz** [comment] 2022-09-28 12:45
It works fine for me, the other solutions posted didn't help.

Bad that the 17.3.4 sucked for MAUI.

Good that the VS team turned around a fix in 17.3.5 so quickly.

Just wish we had a simple revert mechanism in VS. For now, I'll be testing new VS versions in a spare dev environment before they are widely adopted by my team.

Thank you to VS/MAUI teams for your wonderful technology! I really love what you are doing and how fast you are iterating even if we do hit these occasional bumps.

Tony Nicholls
705 543 1312
________________________________

**Comment by KieranDevvs** [comment] 2022-09-28 14:22
This is confirmed to be fixed in 17.3.5, can this issue be closed?

**Comment by GreatIdeaz** [comment] 2022-09-28 16:36
Works for me so I have no problem with you closing the ticket 😊

**Comment by samhouts** [comment] 2022-09-28 17:05
Thank you everyone for your patience! Please update to 17.3.5 if you haven't already. This is now resolved!

**Closed by samhouts** 2022-09-28 17:05 UTC
Labels: t/bug, platform/android 🤖, area/tooling ⚙️, area/blazor 🕸️, p/0
