### ISSUE TITLE
Get C# Stack trace of MAUI iOS without using any CrashAnalytics

### ISSUE THREAD

**Issue by mkshiblu** [dotnet/maui#26414] opened 2024-12-05 21:23 UTC
### Description

Currently, whenever a crash happens on MAUI iOS on a release build in AppStoreConnect / TestFlight, we get a crash report in the format of .IPS file. When I click on the "Open in XCode" button, it opens the report, auto / manual symbolicates if this was the originating MAC. However, I cannot see the C# stack trace. After the symbolication using the .dSYM file, only the native swift stack track is shown. This is the default behavior I observed on a new Blank MAUI application.

Expected: We want to see the C# Stacktrace without using any CrashAnalytics if possible.

### Public API Changes

I assume it would be a property in the .csproj file.

### Intended Use-Case

Since, AppCenter is retiring, the only other viable option for us was to use FIrebase. However, their privacy policy does not comply with our app's policy. So we could not use that. So far there are no free and privacy compliant options for use.

Will there be any migration of AppCenter CrashAnalytics?

**Comment by drasticactions** [comment] 2024-12-06 05:31
I believe C# Exceptions are marshaled as part of [.NET iOS SDK](https://github.com/xamarin/xamarin-macios), this is independent of the MAUI UI framework. As far as I understand it, this behavior for TestFlight crashes is correct: You're going to get the native exception, and you would need to handle .NET exceptions if you want to get the those exceptions.

@rolfbjarne Is my understanding correct? Do you know the best path for this user?

**Comment by rolfbjarne** [comment] 2024-12-06 10:02
@mkshiblu can you share an example of a partially symbolicated crash report + how you triggered the crash?

**Comment by mkshiblu** [comment] 2024-12-06 21:46
@rolfbjarne Sure, Blank MAUI App -> Counter ButtonClick Hanlder -> Throw NRE. On the published app, click on the button to generate a crash.

![Image](https://github.com/user-attachments/assets/46673b0f-2f3d-4e7b-8da3-a4c3155f9cf6)

**Contents of the crashlog.crash**


Incident Identifier: 7D16DA50-E215-4845-9753-D604EEF49B0C
Distributor ID:      com.apple.TestFlight
Hardware Model:      iPhone12,8
Process:             Mobile_App [2235]
Path:                /private/var/containers/Bundle/Application/2DC05F61-87A0-4E3B-A381-64B3020AF5C7/Mobile_App.app/Mobile_App
Identifier:          com.xxx.mobile.qa
Version:             4.18.4 (4.18.4)
AppStoreTools:       16B39
AppVariant:          1:iPhone12,8:18
Beta:                YES
Code Type:           ARM-64 (Native)
Role:                Foreground
Parent Process:      launchd [1]
Coalition:           com.xxx.mobile.qa [1548]

Date/Time:           2024-11-28 13:01:24.2692 -0700
Launch Time:         2024-11-28 13:01:15.6774 -0700
OS Version:          iPhone OS 18.1.1 (22B91)
Release Type:        User
Baseband Version:    6.00.00
Report Version:      104

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Termination Reason: SIGNAL 6 Abort trap: 6
Terminating Process: Mobile_App [2235]

Triggered by Thread:  0


Thread 0 name:
Thread 0 name:
Thread 0 Crashed:
0   libsystem_kernel.dylib        	0x00000001df5a51d4 __pthread_kill + 8
1   libsystem_pthread.dylib       	0x00000002176daef8 pthread_kill + 268 (pthread.c:1721)
2   libsystem_c.dylib             	0x0000000196f97ad8 abort + 128 (abort.c:122)
3   Mobile_App                    	0x00000001041223e8 sigabrt_signal_handler.cold.1 + 48 (mini-posix.c:226)
4   Mobile_App                    	0x00000001040ad798 sigabrt_signal_handler + 196 (mini-posix.c:224)
5   libsystem_platform.dylib      	0x0000000217510afc _sigtramp + 56 (sigtramp.c:116)
6   libsystem_pthread.dylib       	0x00000002176daef8 pthread_kill + 268 (pthread.c:1721)
7   libsystem_c.dylib             	0x0000000196f97ad8 abort + 128 (abort.c:122)
8   Mobile_App                    	0x0000000103e3fc30 xamarin_unhandled_exception_handler + 60 (runtime.m:1133)
9   Mobile_App                    	0x0000000103fe952c mono_invoke_unhandled_exception_hook + 156 (exception.c:1219)
10  Mobile_App                    	0x0000000104083f34 mono_jit_exec_internal + 56 (driver.c:1374)
11  Mobile_App                    	0x0000000104083f34 mono_jit_exec + 396 (driver.c:1314)
12  Mobile_App                    	0x0000000103e4818c xamarin_main + 972 (monotouch-main.m:495)
13  Mobile_App                    	0x00000001040ec3d8 main + 64 (main.arm64.mm:180)
14  dyld                          	0x00000001b4bc6ec8 start + 2724 (dyldMain.cpp:1334)

Thread 1 name:
Thread 1:
0   libsystem_kernel.dylib        	0x00000001df59ff90 __psynch_cvwait + 8
1   libsystem_pthread.dylib       	0x00000002176d6a50 _pthread_cond_wait + 1204 (pthread_cond.c:862)
2   Mobile_App                    	0x0000000103fc435c mono_os_cond_wait + 8 (mono-os-mutex.h:219)
3   Mobile_App                    	0x0000000103fc435c get_work + 228 (sgen-thread-pool.c:164)
4   Mobile_App                    	0x0000000103fc435c thread_func + 440 (sgen-thread-pool.c:195)
5   libsystem_pthread.dylib       	0x00000002176d937c _pthread_start + 136 (pthread.c:931)
6   libsystem_pthread.dylib       	0x00000002176d4494 thread_start + 8

Thread 2 name:
Thread 2:
0   libsystem_kernel.dylib        	0x00000001df59a604 semaphore_wait_trap + 8
1   Mobile_App                    	0x000000010405f2f0 mono_os_sem_wait + 12 (mono-os-semaphore.h:85)
2   Mobile_App                    	0x000000010405f2f0 mono_coop_sem_wait + 32 (mono-coop-semaphore.h:41)
3   Mobile_App                    	0x000000010405f2f0 finalizer_thread + 328 (gc.c:891)
4   Mobile_App                    	0x000000010403cae0 start_wrapper_internal + 284 (threads.c:1202)
5   Mobile_App                    	0x000000010403cae0 start_wrapper + 352 (threads.c:1271)
6   libsystem_pthread.dylib       	0x00000002176d937c _pthread_start + 136 (pthread.c:931)
7   libsystem_pthread.dylib       	0x00000002176d4494 thread_start + 8

Thread 3:
0   libsystem_pthread.dylib       	0x00000002176d4480 start_wqthread + 0

Thread 4:
0   libsystem_pthread.dylib       	0x00000002176d4480 start_wqthread + 0

Thread 5 name:
Thread 5:
0   libsystem_kernel.dylib        	0x00000001df59a688 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	0x00000001df59dd98 mach_msg2_internal + 80 (mach_msg.c:201)
2   libsystem_kernel.dylib        	0x00000001df59dcb0 mach_msg_overwrite + 424 (mach_msg.c:0)
3   libsystem_kernel.dylib        	0x00000001df59dafc mach_msg + 24 (mach_msg.c:323)
4   CoreFoundation                	0x000000018f1d9a84 __CFRunLoopServiceMachPort + 160 (CFRunLoop.c:2637)
5   CoreFoundation                	0x000000018f1d9130 __CFRunLoopRun + 1212 (CFRunLoop.c:3021)
6   CoreFoundation                	0x000000018f1d8830 CFRunLoopRunSpecific + 588 (CFRunLoop.c:3434)
7   Foundation                    	0x000000018de80500 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 212 (NSRunLoop.m:373)
8   Foundation                    	0x000000018de80350 -[NSRunLoop(NSRunLoop) runUntilDate:] + 64 (NSRunLoop.m:420)
9   UIKitCore                     	0x0000000191d52358 -[UIEventFetcher threadMain] + 420 (UIEventFetcher.m:1241)
10  Foundation                    	0x000000018de916c8 __NSThread__start__ + 724 (NSThread.m:991)
11  libsystem_pthread.dylib       	0x00000002176d937c _pthread_start + 136 (pthread.c:931)
12  libsystem_pthread.dylib       	0x00000002176d4494 thread_start + 8

Thread 6:
0   libsystem_pthread.dylib       	0x00000002176d4480 start_wqthread + 0


Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000000   x1: 0x0000000000000000   x2: 0x0000000000000000   x3: 0x0000000000000000
    x4: 0xffffffff96dcb974   x5: 0x0000000000000008   x6: 0x000000016d4b2d80   x7: 0x000000016d4b2470
    x8: 0xa226479759a52144   x9: 0xa2264796ab5e2084  x10: 0x00000000000003ff  x11: 0x000000016d4b24e0
   x12: 0x0000000000000000  x13: 0x000000010386754c  x14: 0x00000001a87ec2e8  x15: 0x00000001a87ec3e4
   x16: 0x0000000000000148  x17: 0x00000001f2fb01c0  x18: 0x0000000000000000  x19: 0x0000000000000006
   x20: 0x0000000000000103  x21: 0x00000001f2fb02a0  x22: 0x00000001085a3000  x23: 0x0000000000000001
   x24: 0x0000000303d959e0  x25: 0x0000000000000000  x26: 0x0000000000000000  x27: 0x000000016d4b3c99
   x28: 0x0000000302486e60   fp: 0x000000016d4b2d90   lr: 0x00000002176daef8
    sp: 0x000000016d4b2d70   pc: 0x00000001df5a51d4 cpsr: 0x40000000
   esr: 0x56000080  Address size fault


Binary Images:
        0x10294c000 -         0x1042a3fff Mobile_App arm64  <4806843f1e1337bc952eeb6c889413cd> /private/var/containers/Bundle/Application/2DC05F61-87A0-4E3B-A381-64B3020AF5C7/Mobile_App.app/Mobile_App
        0x10a454000 -         0x10a45ffff libobjc-trampolines.dylib arm64e  <35a44678195b39c2bdd7072893564b45> /private/preboot/Cryptexes/OS/usr/lib/libobjc-trampolines.dylib
        0x18ddc9000 -         0x18ead6fff Foundation arm64e  <6d0212cc3b9e32c9be2072989ce3acb8> /System/Library/Frameworks/Foundation.framework/Foundation
        0x18f186000 -         0x18f6c8fff CoreFoundation arm64e  <1532d3d89b3b3f2fb35f55a20ddf411b> /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation
        0x19196c000 -         0x19383ffff UIKitCore arm64e  <575e5140fa6a37c2b00ba4eacedfda53> /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
        0x196f20000 -         0x196f9fff3 libsystem_c.dylib arm64e  <0150f750db0a3f54b23ad21c55af8824> /usr/lib/system/libsystem_c.dylib
        0x1a8791000 -         0x1a8863fff FrontBoardServices arm64e  <d627737b3c6c3308a90cad705542c2b3> /System/Library/PrivateFrameworks/FrontBoardServices.framework/FrontBoardServices
        0x1b4b93000 -         0x1b4c1699f dyld arm64e  <3060d36a16ce3c3a92583881459f5714> /usr/lib/dyld
        0x1df599000 -         0x1df5d2ff3 libsystem_kernel.dylib arm64e  <b9618c71c0cb31b6825f92a4737c890e> /usr/lib/system/libsystem_kernel.dylib
        0x21750f000 -         0x217516fe3 libsystem_platform.dylib arm64e  <5079e5e035253d538ff03e297a22fc4f> /usr/lib/system/libsystem_platform.dylib
        0x2176d3000 -         0x2176dfff3 libsystem_pthread.dylib arm64e  <3ca98e388eee3c269862c5f66aad93c0> /usr/lib/system/libsystem_pthread.dylib

EOF

**Comment by jfversluis** [comment] 2024-12-09 11:31
@rolfbjarne FYI

**Comment by rolfbjarne** [comment] 2024-12-09 19:17
This is a rather complicated case, because this is what happens:

1. The exception is thrown in managed code, and the runtime looks for an exception handler.
2. Since managed code was called from native code, there is code to catch the managed exception further up the stack (where execution transition from native to managed code). This code catches the managed exception and converts it into an Objective-C exception (and throws that).
3. Even further up the stack there's a from managed to native code, and the opposite happens: the Objective-C exception is converted back into a managed exception.
4. This back and forth between managed and native code can happen a few times as we unwind the stack, but eventually we reach the top of the stack and realize that the original exception was essentially unhandled, and the process aborts.

The problem is that the original stack is gone at this point, so what the crash report reflects is the stack at the very end of the process, when the process is aborted.

Ideally we'd be able to add information to the crash report (we could add the original stack trace for instance), but unfortunately Apple doesn't provide any official API to do this.

My recommendation would be to implement your own telemetry for unhandled managed exceptions. This shouldn't be altogether difficult:

1. Add an event handler to the [AppDomain.UnhandledException](https://learn.microsoft.com/en-us/dotnet/api/system.appdomain.unhandledexception) event.
2. Collect the stack trace, and save it to a file on disk.
3. Upon next time the app starts up, look for any stored files, and upload them to your own servers.

Note, you may want to add event handlers to a few more events:

1. [ObjCRuntime.Runtime.MarshalManagedException](https://learn.microsoft.com/en-us/dotnet/api/objcruntime.runtime.marshalmanagedexception) (see https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/platform/exception-marshaling.md for more information about this event).
1. [AppDomain.FirstChanceException](https://learn.microsoft.com/en-us/dotnet/api/system.appdomain.firstchanceexception?view=net-8.0) - this one may produce a lot of noise though, depending on your app.

**Comment by jfversluis** [comment] 2024-12-11 08:23
So from what I understand there isn't much we can do here right now. And if anything, this should happen on the .NET for iOS repo. So closing this for now here, please connect otherwise if you want to continue the conversation further. Thanks all!

**Closed by jfversluis** 2024-12-11 08:23 UTC
Labels: proposal/open

**Comment by mkshiblu** [comment] 2024-12-11 22:39
Thanks for the clarification, I think this cleared a lot of confusion from my side.
