### ISSUE TITLE
MAUI new solution config failing to launch android build

### ISSUE THREAD

**Issue by Nick-Hughes-github** [dotnet/maui#21300] opened 2024-03-19 10:27 UTC
I have created a 'New Solution Configuration' from the 'Configuration Manager' and copied settings from the 'Release' build config. WinUI, macOS and iOS all work with this new build configuration. However, Android compiles and builds but fails to deploy, crashing when attempting to launch the app. I have identified the creation of a 'New Solution Configuration' as the issue as the 'Release' config (out the box) works yet my custom 'CIBuild' config does not.

**Comment by PureWeen** [comment] 2024-03-19 19:15
Duplicate of #20211

**Closed by PureWeen** 2024-03-19 19:15 UTC
Labels: tutorials
