### ISSUE TITLE
Border on iOS redraws with 1 frame lag, creating lag before drawn 1 frame after other elements

### ISSUE THREAD

**Issue by jonmdev** [dotnet/maui#23688] opened 2024-07-18 17:10 UTC
### Description

As was discussed here there was a problem where borders are being drawn with square elements or wrong colors on their first frames:

https://github.com/dotnet/maui/issues/23070

I am unable to text the fix as I was told to use 8.0.80-ci.net8.24367.6, but this does not work (Gives me a bunch of errors and won't build.). ie.

```
<ItemGroup>
	<PackageReference Include="Microsoft.Maui.Controls" Version="8.0.80-ci.net8.24367.6" />
	<PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="8.0.80-ci.net8.24367.6" />
	<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="8.0.0" />
</ItemGroup>
```

In any case, one can see from the "fix" that a lag persists. This is most visible with the black Hello where we see it appear one frame before the Border behind it:

![349679784-65c2d060-929c-4d8d-8e1b-1b9761d99fbd](https://github.com/user-attachments/assets/f0000561-148b-49dd-b2a5-e1da3c7c716e)

Any final fix would be appreciated @albyrock87 

### Version with bug

8.0.70 SR7

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

**Comment by Zhanglirong-Winnie** [comment] 2024-07-19 09:33
This issue has been verified using Visual Studio 17.11.0 Preview 4.0(8.0.70&8.0.80-ci.net8.24367.6). Can repro on iOS platform.

**Comment by thisisthekap** [comment] 2024-07-30 10:10
@albyrock87 @jonmdev Are there any news on how to do a workaround or a fix?

**Comment by albyrock87** [comment] 2024-07-30 12:21
@thisisthekap I spent a good amount of time trying to fix this, and it appears it's very hard to fix as probably there is a huge problem with the rendering workflow.

**Comment by thisisthekap** [comment] 2024-07-31 08:35
@dalexsoto Anything you might be able to help with?

**Comment by albyrock87** [comment] 2024-08-21 18:47
May you all verify if my PR now fixes everything and don't produces additional glitches on your applications?
Packages here:
https://dev.azure.com/xamarin/6fd3d886-57a5-4e31-8db7-52a1b47c07a8/_apis/build/builds/122164/artifacts?artifactName=nuget&api-version=7.1&%24format=zip

**Comment by albilaga** [comment] 2024-08-24 14:56
@albyrock87 this is working now. Great works. Thank you. Is it possible to include it just in handler? or we do need custom maui build?

**Comment by albyrock87** [comment] 2024-08-24 15:32
@albilaga it is not possible unfortunately, but it is probably going to be included in the next SR.

To temporary fix the animation only (not the 1 frame lag) you can override the arrange method of the handler and wrap the base method execution into a CATransaction with animation length set to 0.

**Comment by PureWeen** [comment] 2024-09-03 21:07
Duplicate of #21643

**Closed by PureWeen** 2024-09-03 21:07 UTC
Labels: t/bug, platform/iOS 🍎, s/verified, area-controls-border, s/triaged
