### ISSUE TITLE
Carousel View doesn't update its hierachy tree on Windows with Loop set to False

### ISSUE THREAD

**Issue by elTRexx** [dotnet/maui#9457] opened 2022-08-16 12:02 UTC
### Description

Hi, I still testing MAUI, especially how Carousel view work lately.
I'm facing several discrepancy between android and Windows behavior. 
For example my issue here is that using a simple Carousel View binded with an Observable Collection property, and setting its Loop parameter to False make the display of the carousel items not updating while adding new items to the binded Observable Collection at runtime (via an UI Button). Though it work either on Android or when setting Loop back to True.

I noted that the CarouselView on the hierarchy tree in Visual Studio didn't update too (still with 1 item, the one I'm adding at construction Time)

### Steps to Reproduce

Get the full project [here](https://github.com/elTRexx/MauiCarousel/tree/master/MauiCarousel)
Try with or without Loop="False" parameter on MainPage.xaml and/or switching back and forth from Windows Machine to Android device.

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows SDK 10.0.19401.0

**Comment by elTRexx** [comment] 2022-08-16 22:55
To add some more info, I found that using Loop="True" parameter make the hierarchy tree pre-populate 25 items (Label in my case). Analyzing how it work while running the application on Windows Machine, I deduce it use some kind of pooling mechanism, because the 25 pre loaded item just update their Text value. Then I Add more item than 25 to see if the pooling would increase as I would have guessed, but they use another clever mechanism to dynamically pool only on the on screen viewed carousel item !
Doesn't solve any point here, But better understanding may help. Maybe something prevent the pooling to increase in some, bugged here, way of optimization ?

**Comment by elTRexx** [comment] 2022-08-16 23:10
Ok another testing show that hard setting the Binded Observable Collection Property, `CarouselItems` here, to a whole new Observable Collection object each time I add an object (using a temporary `List<>` in the `Button_Clicked()` method) kinda "work".
I say kinda because the carousel's items on hierarchy tree grow exponentially this way ...

**Comment by homeyf** [comment] 2023-07-03 06:02
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 2.0. Can repro on Windows platform with sample project.
[here](https://github.com/elTRexx/MauiCarousel/tree/master/MauiCarousel)
![image](https://github.com/dotnet/maui/assets/82450723/7d66771a-389e-46dc-8837-6c032930fbba)

**Comment by samhouts** [comment] 2023-08-17 23:15
Duplicate of #12850

**Closed by samhouts** 2023-08-17 23:15 UTC
Labels: t/bug, area/collectionview 📃, s/verified, s/triaged
