### ISSUE TITLE
Shell page doesn't work on ios emulator

### ISSUE THREAD

**Issue by nevse** [dotnet/maui#5625] opened 2022-03-29 06:48 UTC
### Description

It is impossible to use the shell page on an ios emulator. It renders nothing on ios.
<img width="859" alt="image" src="https://user-images.githubusercontent.com/1169410/160549003-8d31354b-984e-40af-bedb-d2081da397d0.png">

### Steps to Reproduce

You can find example at https://github.com/nevse/Maui-Tests-ShellVsIOS

1. Create maui app `dotnet new maui`
2. Change mainpage from content page to Shell
3. add 2 any pages
4. insert xaml in main page
```
<Shell xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="ShellExmaple.MainPage"
             xmlns:local="clr-namespace:ShellExmaple"
             BackgroundColor="{DynamicResource SecondaryColor}">

    <Tab Title="About">
        <ShellContent ContentTemplate="{DataTemplate local:AboutPage}" />
    </Tab>
    <Tab Title ="About2" >
        <ShellContent ContentTemplate="{DataTemplate local:AboutPage2}" />
    </Tab>
</Shell>
```

5. Run app `dotnet build -t:Run -f:net6.0-ios`

after that you should see page content but you don't see it.

### Version with bug

Preview 14 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

ios 15

### Did you find any workaround?

I can't find any workaround at all

**Comment by jfversluis** [comment] 2022-03-29 08:37
Duplicate of #5550

**Comment by jfversluis** [comment] 2022-03-29 08:37
This is fixed and should be better for next preview, thanks!

**Closed by jfversluis** 2022-03-29 08:37 UTC
Labels: t/bug, s/needs-verification
