### ISSUE TITLE
The remote iOS simulator hangs with black screen 

### ISSUE THREAD

**Issue by HobDev** [dotnet/maui#5787] opened 2022-04-04 06:05 UTC
### Description

The remote iOS simulator hangs with black screen. The issue will replicate with any project. The remote iOS simulator shows but hangs and no interaction with it is possible. Whereas the local simulator in Mac works fine with same project. 

### Steps to Reproduce

Run any maui project from Windows with "Remote Simulator to Windows" enabled. 

### Version with bug

Preview 14 (current)

### Last version that worked well

Preview 13

### Affected platforms

iOS

### Affected platform versions

iOS 15

### Did you find any workaround?

Uncheck "Remote Simulator to Windows" and run the project directly on Mac.

**Comment by Mephisztoe** [comment] 2022-04-04 08:17
Is this possibly a duplicate of both https://github.com/dotnet/maui/issues/5549 and https://github.com/dotnet/maui/issues/5786?

**Comment by HobDev** [comment] 2022-04-04 09:04
#5549  and #5786 are same. But this one (#5787) is different. This bug is about the remote iOS Simulator on Windows.

**Comment by jfversluis** [comment] 2022-04-04 11:51
This is a known issue with Visual Studio right now, reported and updates will come in here: https://developercommunity.visualstudio.com/t/Visual-Studio-2022-1711-iOS-simulator/1695537?space=8&q=IOS+remote+simulator&stateGroup=active

**Closed by jfversluis** 2022-04-04 11:51 UTC
Labels: t/bug, area/tooling ⚙️, platform/iOS 🍎, s/needs-verification
