### ISSUE TITLE
.net 9 maui Shell.Current.GotoAsync("..") app crash with debugger is attached exception on windows when back from a page that implements map control

### ISSUE THREAD

**Issue by MahmoudAlEssawi** [dotnet/maui#26289] opened 2024-11-30 05:09 UTC
### Description

After upgrading to .net 9
 and CommunityToolkit.Maui.Maps nuget to 2.0.4

when navigating back from a page that implements a map control 

this happens on windows only

#if DEBUG && !DISABLE_XAML_GENERATED_BREAK_ON_UNHANDLED_EXCEPTION
            UnhandledException += (sender, e) =>
            {
                if (global::System.Diagnostics.Debugger.IsAttached) global::System.Diagnostics.Debugger.Break();
            };
#endif

### Steps to Reproduce

setup the CommunityToolkit.Maui.Maps nuget version: 2.0.4

Create a page.

add map control,

run on Windows machine

try navigating to this page then navigate back.

### Version with bug

9.0.10 SR1

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

8.0.91 SR9.1

### Affected platforms

Windows

### Affected platform versions

Windows 11

### Did you find any workaround?

No

### Relevant log output

```shell

```

**Comment by FaithfulDev** [comment] 2024-11-30 12:03
Link to public reproduction project repository:
https://github.com/FaithfulDev/MapGoBackBugMinimal

I'm getting this exception:

```
PlatformView cannot be null here

at Microsoft.Maui.Handlers.ViewHandler`2.get_PlatformView()
at CommunityToolkit.Maui.Maps.Handlers.MapHandlerWindows.DisconnectHandler(FrameworkElement platformView)
at Microsoft.Maui.Handlers.ViewHandler`2.OnDisconnectHandler(FrameworkElement platformView)
at Microsoft.Maui.Handlers.ViewHandler.OnDisconnectHandler(Object platformView)
at Microsoft.Maui.Handlers.ElementHandler.DisconnectHandler(Object platformView)
at Microsoft.Maui.Handlers.ElementHandler.Microsoft.Maui.IElementHandler.DisconnectHandler()
at Microsoft.Maui.ViewExtensions.DisconnectHandlers(IView view)
at Microsoft.Maui.Controls.Page.<SendNavigatedFrom>b__111_0()
at Microsoft.Maui.Platform.FrameworkElementExtensions.<>c__DisplayClass11_0.<OnUnloaded>b__2(Object _, RoutedEventArgs __)
at WinRT._EventSource_global__Microsoft_UI_Xaml_RoutedEventHandler.EventState.<GetEventInvoke>b__1_0(Object sender, RoutedEventArgs e)
at ABI.Microsoft.UI.Xaml.RoutedEventHandler.Do_Abi_Invoke(IntPtr thisPtr, IntPtr sender, IntPtr e)
```

Is this your exception as well?

**Comment by FaithfulDev** [comment] 2024-11-30 12:17
It's probably better for you to ask in the Community Toolkit Maui project for help:
https://github.com/CommunityToolkit/Maui

**Comment by MahmoudAlEssawi** [comment] 2024-12-01 07:22
> Link to public reproduction project repository: https://github.com/FaithfulDev/MapGoBackBugMinimal
> 
> I'm getting this exception:
> 
> ```
> PlatformView cannot be null here
> 
> at Microsoft.Maui.Handlers.ViewHandler`2.get_PlatformView()
> at CommunityToolkit.Maui.Maps.Handlers.MapHandlerWindows.DisconnectHandler(FrameworkElement platformView)
> at Microsoft.Maui.Handlers.ViewHandler`2.OnDisconnectHandler(FrameworkElement platformView)
> at Microsoft.Maui.Handlers.ViewHandler.OnDisconnectHandler(Object platformView)
> at Microsoft.Maui.Handlers.ElementHandler.DisconnectHandler(Object platformView)
> at Microsoft.Maui.Handlers.ElementHandler.Microsoft.Maui.IElementHandler.DisconnectHandler()
> at Microsoft.Maui.ViewExtensions.DisconnectHandlers(IView view)
> at Microsoft.Maui.Controls.Page.<SendNavigatedFrom>b__111_0()
> at Microsoft.Maui.Platform.FrameworkElementExtensions.<>c__DisplayClass11_0.<OnUnloaded>b__2(Object _, RoutedEventArgs __)
> at WinRT._EventSource_global__Microsoft_UI_Xaml_RoutedEventHandler.EventState.<GetEventInvoke>b__1_0(Object sender, RoutedEventArgs e)
> at ABI.Microsoft.UI.Xaml.RoutedEventHandler.Do_Abi_Invoke(IntPtr thisPtr, IntPtr sender, IntPtr e)
> ```
> 
> Is this your exception as well?

Visual studio doesn't generate any log report for the exception. just crash with debugger is attached

**Comment by FaithfulDev** [comment] 2024-12-01 09:29
> Visual studio doesn't generate any log report for the exception. just crash with debugger is attached

When your debbuger stops at `System.Diagnostics.Debugger.Break();` in the `UnhandledException` event handler, you can inspect the event args `e` to see the exception that was unhandled.

**Comment by MahmoudAlEssawi** [comment] 2024-12-02 04:57
Thanks for your help:

Yes the error is the same as you get:

PlatformView cannot be null here

at Microsoft.Maui.Handlers.ViewHandler`2.get_PlatformView()
at CommunityToolkit.Maui.Maps.Handlers.MapHandlerWindows.DisconnectHandler(FrameworkElement platformView)
at Microsoft.Maui.Handlers.ViewHandler`2.OnDisconnectHandler(FrameworkElement platformView)
at Microsoft.Maui.Handlers.ViewHandler.OnDisconnectHandler(Object platformView)
at Microsoft.Maui.Handlers.ElementHandler.DisconnectHandler(Object platformView)
at Microsoft.Maui.Handlers.ElementHandler.Microsoft.Maui.IElementHandler.DisconnectHandler()
at Microsoft.Maui.ViewExtensions.DisconnectHandlers(IView view)
at Microsoft.Maui.Controls.Page.<SendNavigatedFrom>b__111_0()
at Microsoft.Maui.Platform.FrameworkElementExtensions.<>c__DisplayClass11_0.<OnUnloaded>b__2(Object _, RoutedEventArgs __)
at WinRT._EventSource_global__Microsoft_UI_Xaml_RoutedEventHandler.EventState.<GetEventInvoke>b__1_0(Object sender, RoutedEventArgs e)
at ABI.Microsoft.UI.Xaml.RoutedEventHandler.Do_Abi_Invoke(IntPtr thisPtr, IntPtr sender, IntPtr e)

**Comment by MahmoudAlEssawi** [comment] 2024-12-02 05:07
I created an issue in the community toolkit as it related to it.
[#2366](https://github.com/CommunityToolkit/Maui/issues/2366#issue-2710511880)

**Comment by kevinxufei** [comment] 2024-12-02 08:14
I can repro this issue at Windows platform on the latest 17.13 Preview 1(9.0.0 & 9.0.100),but it works fine on 8.0.91 & 8.0.100.

**Comment by tj-devel709** [comment] 2024-12-02 21:10
Thanks for creating this issue. Since there is an issue created in the Maui Community Toolkit above, I will close this one here. If this is not resolved with the Maui Community Toolkit, feel free to reopen this issue or create a new one and link this issue there.

**Closed by tj-devel709** 2024-12-02 21:10 UTC
Labels: t/bug, platform/windows 🪟, s/verified, s/triaged, i/regression
