### ISSUE TITLE
[Templates] ContentPage item template uses obsolete API

### ISSUE THREAD

**Issue by davidbritch** [dotnet/maui#4533] opened 2022-02-07 08:51 UTC
### Description

The [ContentPage](https://github.com/dotnet/maui/blob/main/src/Templates/src/templates/maui-contentpage-xaml/NewPage1.xaml) item template uses *AndExpand layout options. All the *AndExpand APIs are obsolete in MAUI and so this should be removed from the template.

**Comment by v-longmin** [comment] 2022-03-03 01:59
Thank you so much for your bug report! Unfortunately, we cannot reproduce your issue with the information above, could you provide a sample project and screenshots or more details that we can reproduce your issue? That should greatly speed up the process, thanks!

**Comment by kristinx0211** [comment] 2022-03-03 08:15
Repro on 17.2.0 Preview 2.0 [32208.456.main]. repro sample:
[#4533.zip](https://github.com/dotnet/maui/files/8176048/4533.zip)

**Comment by davidbritch** [comment] 2022-03-03 08:16
Looks like @jsuarezruiz has now fixed this issue - https://github.com/dotnet/maui/blob/main/src/Templates/src/templates/maui-contentpage-xaml/NewPage1.xaml

**Comment by jfversluis** [comment] 2022-03-04 09:36
Fixed in #4535

**Closed by jfversluis** 2022-03-04 09:36 UTC
Labels: t/bug, area/templates 📄, high, s/verified, s/triaged, s/needs-attention
