### ISSUE TITLE
Can not run project in MacOS

### ISSUE THREAD

**Issue by Kerwin1202** [dotnet/maui#9568] opened 2022-08-21 15:27 UTC
### Description

I Can not run my first MAUI project in my MacOS (m1 12.5.1)
Visual Studio 2022 17.4 build 715

I tried looking up some youtube tutorials and found that the steps are not any different, 
but I can't get it to work as well as they do. (Visual Studio 2022 GUI)

BTW: I can run it fine with command like `dotnet build -t:Run -f net6.0-ios `

![image](https://user-images.githubusercontent.com/16319833/185798291-d796a54b-a640-4abf-b774-77b075c4e261.png)

### Steps to Reproduce

1. Create a File > New .NET MAUI App
2. Edit Project File > remove .net-6.0-android
![image](https://user-images.githubusercontent.com/16319833/185798489-76757144-2cb4-4e69-b7b0-0959cd122441.png)
3. Run project 

Expected outcome: Run project successfully

Actual outcome:  get a error
![image](https://user-images.githubusercontent.com/16319833/185798500-6db7f578-512d-4f00-ac0c-cc549286a3cc.png)

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, macOS

### Affected platform versions

Mac Or IOS

**Comment by JuQiang** [comment] 2022-08-22 01:51
Looks like it's a simple project, so check your project property: Build-General-Code Generation-Output type, make sure it's a "Executable" instead of "Library"

**Comment by Kerwin1202** [comment] 2022-08-22 02:33
> Looks like it's a simple project, so check your project property: Build-General-Code Generation-Output type, make sure it's a "Executable" instead of "Library"

 The default is "Executable" is the same prompt, so I tried to change to "Library" but still

<img width="1123" alt="image" src="https://user-images.githubusercontent.com/16319833/185827187-19c82c87-2d1f-48da-93e8-e631b31a492e.png">

**Comment by jfversluis** [comment] 2022-08-22 10:33
Duplicate of #8894

**Closed by jfversluis** 2022-08-22 10:33 UTC
Labels: t/bug, platform/macOS 🍏, area/tooling ⚙️
