### ISSUE TITLE
Automatic font scaling does not work

### ISSUE THREAD

**Issue by Qythyx** [dotnet/maui#14260] opened 2023-03-29 11:47 UTC
### Description

Automatic font scaling does not work, mostly. In the default sample MAUI app, only the page title changes size dynamically if you change the system font scaling setting. All other fonts remain at their initial size. Note, if you quite the app, then change the system font size, then start the app again it will show the adjust font size. The problem is that it won't change dynamically while the app is running.

I tested this on iOS and Android and the problem exists in both. Note, you can easily test this in the iOS simulator using the `Increase Preferred Text Size` shortcut of Alt Command + or -.

This is a regression and used to work in Xamarin.

### Steps to Reproduce

1. Create a new MAUI app
2. Run it
3. Change the system font size setting
4. Switch back to the app and notice the font size did not change

### Link to public reproduction project repository

n/a

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

all

### Did you find any workaround?

No

### Relevant log output

```shell
n/a
```

**Comment by rachelkang** [comment] 2023-03-29 18:13
Duplicate of https://github.com/dotnet/maui/issues/1824

Please feel free to add more thoughts and a repro in that thread, so we can investigate further. I tested recently on Android and wasn't able to reproduce this issue there, so am particularly curious what set of controls/layouts you may be using and what your app may look like there. Thanks!

**Closed by rachelkang** 2023-03-29 18:13 UTC
Labels: t/bug, area/fonts 🅰️

**Comment by samhouts** [comment] 2023-05-03 23:55
Duplicate of #1824
