### ISSUE TITLE
ContentPage.OnAppearing is not getting called when going back from Content page of type Modal page

### ISSUE THREAD

**Issue by muffadal53** [dotnet/maui#13668] opened 2023-03-03 06:50 UTC
### Description

ContentPage.OnAppearing is not getting called when going back from Content page of type Modal page.

### Steps to Reproduce

Download solution here

https://github.com/muffadal53/MAUIOnAppearingModalBug.git

Run solution

On MainPage, click on button "Open Second Page" to go the Parent Page

Alert message is displayed with text "OnAppearing of Parent Page".

From ParentPage, click on "Open Modal" button to open Content page which is made Modal using "Shell.PresentationMode="Modal" in xaml.

Alert message is displayed with text "OnDisappearing of Parent Page".

On modal page, click on "Cross" button image.

On Parent page should display alert "OnAppearing of Parent Page" but it is not displayed --> This is Not OK

### Link to public reproduction project repository

https://github.com/muffadal53/MAUIOnAppearingModalBug.git

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

Android 11, iOS 16

### Did you find any workaround?

N/A

**Comment by rachelkang** [comment] 2023-03-06 15:32
@PureWeen thoughts on this one?

**Comment by rachelkang** [comment] 2023-03-06 15:36
Duplicate of https://github.com/dotnet/maui/issues/8513

This has been fixed by https://github.com/dotnet/maui/pull/13177 and you will see the fix in the next upcoming release!

**Closed by rachelkang** 2023-03-06 15:36 UTC
Labels: t/bug, area/navigation 🧭, area/controls 🎮, area/modal, control-pages

**Comment by muffadal53** [comment] 2023-03-06 15:58
@rachelkang So as I understand this fix will be part of .Net 8 release. Is my understanding right?
