### ISSUE TITLE
NotifyCanExecuteChanged event doesn't set correct button color on Windows

### ISSUE THREAD

**Issue by symbiogenesis** [dotnet/maui#12222] opened 2022-12-20 04:48 UTC
### Description

The CanExecute functionality is supposed to enable and disable buttons, but on Windows it doesn't work as expected.

Works fine on Android.

### Steps to Reproduce

1. Run the minimal example

2. Add record.

3. Clear the records.

4. Add another record.

The clear button is not visibly enabled the second time, although the button is actually enabled.

### Link to public reproduction project repository

https://github.com/symbiogenesis/WindowsCanExecute

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

I see it with net7.0-windows10.0.22621.0

### Did you find any workaround?

No

**Comment by rgray000** [comment] 2022-12-21 04:29
I had the same issue and I found that using await Task.Delay(25) in the pressed event/command before changing the bound property made it work. If I had to guess, it has something to do with the change in style occurring simultaneously with the click event. Hope this works for you!

**Comment by ootbutterfus** [comment] 2022-12-21 18:48
This might be a duplicate issue. See https://github.com/dotnet/maui/issues/9753. I can confirm this is a bug that exists when targeting Windows. I verified using Visual Studio 17.4.3.

**Comment by hartez** [comment] 2022-12-27 23:03
This is a duplicate of #9753 on Windows, and is fixed by #11840, which will be included in an upcoming service release.

**Closed by hartez** 2022-12-27 23:03 UTC
Labels: t/bug, platform/windows 🪟, area/controls 🎮, control-button
