### ISSUE TITLE
The name 'Resources' is reserved and cannot be used.

### ISSUE THREAD

**Issue by EduardoReisDev** [dotnet/maui#10531] opened 2022-10-06 23:55 UTC
### Description

When adding fonts in the Resources/Fonts folder and adding them in MauiProgram, the following error was returned when compiling the project: "The name 'Resources' is reserved and cannot be used".

<img width="1942" alt="image" src="https://user-images.githubusercontent.com/52722526/194438360-a49184e0-20de-4098-83e9-e150b24a3b84.png">

<img width="682" alt="image" src="https://user-images.githubusercontent.com/52722526/194438762-a9126631-2816-4058-b40b-79978c1c2c5b.png">

### Steps to Reproduce

1. Add fonts in Resources/Fonts
2. Adding them in MauiProgram
3. Build project
4. Error: "The name 'Resources' is reserved and cannot be used"

### Link to public reproduction project repository

https://github.com/EduardoReisDev/SpaceXHistory

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 16

**Comment by jfversluis** [comment] 2022-10-07 14:40
Could you try to clean up your csproj file? Visual Studio added a lot of tags that probably mess with this.

You should be able to remove this whole block: https://github.com/EduardoReisDev/SpaceXHistory/blob/main/SpaceXHistory/SpaceXHistory/SpaceXHistory.csproj#L51-L94

Additionally you probably want to add this line back: https://github.com/dotnet/maui/blob/main/src/Templates/src/templates/maui-mobile/MauiApp.1.csproj#L45

Does that help?

**Comment by EduardoReisDev** [comment] 2022-10-07 15:59
@jfversluis 

1. block removed.
2. added line
Commit: https://github.com/EduardoReisDev/SpaceXHistory/commit/32dd2b60d775725ed297546acfa0a910b3942ee2

New problem generated
Crash: 
<img width="811" alt="Screenshot at Oct 07 12-53-02" src="https://user-images.githubusercontent.com/52722526/194597258-9e0a33cd-a804-4850-bf87-d1cb9b3bb2aa.png">

**Comment by julianadormon** [comment] 2022-10-08 18:02
Same issue here after copying an icon from one project to another.

**Comment by julianadormon** [comment] 2022-10-08 18:03
Cleaning the project does not help.

**Comment by frz-ork** [comment] 2022-10-10 20:51
hi, I was getting the same error recently as well. in the csproj file you have the following line; 

<ItemGroup>
   <BundleResource Include="**\*" />
</ItemGroup>

and after changing it to
<ItemGroup>
  <BundleResource Include="Resources/*" />
</ItemGroup>

error was cleared and it run normally. hope it helps.

**Comment by EduardoReisDev** [comment] 2022-10-11 13:34
@frz-ork, Thanks, I'll test it tonight and see if it works for me! Thank you once again!!

**Comment by AloysA** [comment] 2022-10-16 20:09
This bug can also be reproduced by copying a file to the Images directory of a MAUI project. When I drag a file to the the Images folder in Visual Studio for Mac (or copy via the Finder) we get auto-generated, but incorrect, additions to the .csproj file.

Adding the image file to the project:
<img width="219" alt="image" src="https://user-images.githubusercontent.com/2362451/196055724-a9923264-c88f-487d-8cfe-d3acb74cb14b.png">

Incorrect addition to the .csproj file:
```
	<ItemGroup>
	  <None Remove="Resources\Images\main.png" />
	</ItemGroup>
	<ItemGroup>
	  <BundleResource Include="Resources\Images\main.png" />
	</ItemGroup>
```

Yielding this error:
<img width="1109" alt="image" src="https://user-images.githubusercontent.com/2362451/196055808-41699576-e94e-41bb-b102-1b9a43369723.png">

The fix is to remove the incorrect lines from the csproj file as shown above, and instead add this line:
```
		<MauiImage Include="Resources\Images\main.png" />
```

**Comment by rogersm-uwosh** [comment] 2022-10-20 14:31
Thanks, @AloysA , I'm getting that exact same error message, with VSM 17.4 build 2326. 

The line that you mentioned, <MauiImage Include=...> where does it go? After all the other ItemGroups? Inside an ItemGroup? And do I leave the rest of the None's in the first ItemGroup alone (see below)?

And finally, as long as I'm besieging the group with questions here, what's the right way to add images to a project?

Thanks for any insights ... I'm getting tired of only being able to run on Android devices (I can run on macOS, but the icons look *huge*)

<ItemGroup>
	  <None Remove="Resources\Images\info.png" />
	  <None Remove="Resources\Images\new_dog.png" />
	  <None Remove="Resources\Images\rhino.png" />
	  <None Remove="Resources\Images\elephant.png" />
	  <None Remove="Resources\Images\wild_beast.png" />
	  <None Remove="CommunityToolkit.Mvvm" />
	  <None Remove="CommunityToolkit.Maui" />
	  <None Remove="NUnit" />
	  <None Remove="Views\" />
	  <None Remove="Resources\Images\bear.png" />
	</ItemGroup>
	<ItemGroup>
	  <BundleResource Include="Resources\Images\info.png" />
	  <BundleResource Include="Resources\Images\new_dog.png" />
	  <BundleResource Include="Resources\Images\rhino.png" />
	  <BundleResource Include="Resources\Images\elephant.png" />
	  <BundleResource Include="Resources\Images\wild_beast.png" />
	  <BundleResource Include="Resources\Images\bear.png" />
	</ItemGroup>

**Comment by AloysA** [comment] 2022-10-20 15:38
Yes, add that line inside an item group. If you can do them all at once as you can see in this example: https://github.com/dotnet/maui-samples/blob/main/6.0/Navigation/TabbedPage/TabbedPage/TabbedPage.csproj

**Comment by whann0205** [comment] 2022-10-24 07:07
Get the same error only if want to deploy to an IOS local device.
![grafik](https://user-images.githubusercontent.com/71807453/197466808-009f9266-f5af-40bd-a519-ff4749c616c7.png)
In order to use a database i have an extra entry in the itemgroup which 
seems to be the problem.
Dont know if i should open a seperate report, but its quite similar.
Worked with the previous VS 2022 version. I did the upgrade because i didnt get
the menu on the local device. 
Again the simulator works perfectly ...

**Comment by EduardoReisDev** [comment] 2022-10-25 22:28
Guys, I had a new problem:
<img width="761" alt="image" src="https://user-images.githubusercontent.com/52722526/197893349-9dd765a3-1c49-49a8-af3a-1757ac2e098b.png">

Look how the .csproj file is
https://github.com/EduardoReisDev/SpaceXHistory/blob/main/SpaceXHistory/SpaceXHistory/SpaceXHistory.csproj

**Comment by lancecontreras** [comment] 2022-10-26 14:01
@AloysA, I did what you recommend to remove the BundleResource and add MauiImage line. That prevents the error but the image is not showing.

**Comment by whann0205** [comment] 2022-10-27 08:15
Latest Version of VS 2022, deleted obj and bin folder first, no matter what
always resources reserved error.
I dont have any BundledResource in my csproj file.

**Comment by suchithm** [comment] 2022-10-27 09:57
@whann0205  Did you try deleting 
```
<ItemGroup>
      <None Remove="Resources\Images\***.png" />
</ItemGroup>
```

from cs project file

**Comment by whann0205** [comment] 2022-10-27 10:23
I dont have any NONE or Remove Entries:
![grafik](https://user-images.githubusercontent.com/71807453/198260211-c79a2a13-10f3-4ef0-bf0b-b566993ad54e.png)

**Comment by rachelkang** [comment] 2022-11-02 19:31
@EduardoReisDev and any folks still experiencing the Resources issue - could you please [attach a binlog](https://github.com/xamarin/xamarin-macios/wiki/Diagnosis) so that we can investigate further?

@EduardoReisDev as for the XamlParseException, could you please open a separate issue if you're still experiencing it?

Thanks :)

**Comment by mattleibow** [comment] 2022-11-03 22:40
This is a duplicate of https://github.com/dotnet/maui/issues/10975

It is sometimes due to currupted csroj files or due to the fact you may be missing the LogicalName attribute on the MauiAsset.

If the issue of corrupted csproj persists then please open a new issue using the VS feedback as there may be a bug in the IDE.

**Closed** 2022-11-03 22:41 UTC
Labels: t/bug, area/single project ☝️, area/tooling ⚙️, s/move-to-vs-feedback

**Comment by pablo-stelsi** [comment] 2022-11-09 06:12
I solved this problem by using "do remove **Entry** And **Editor** in 'Resources/Styles/style.xaml'".

:)

**Comment by whann0205** [comment] 2022-11-09 06:29
@pablo-stelsi 
Thanks!
Can you explain your solution in detail ?
For example I do not have a Resources/Styles Directory...

**Comment by pablo-stelsi** [comment] 2022-11-09 07:13
This is my solution proccess

1. Check App.xaml file (I found problem in Styles.xaml)
<img width="727" alt="image" src="https://user-images.githubusercontent.com/111423116/200761859-04f963f0-5bdb-49ed-9949-b6ce81b89eca.png">

2. So editted this codes to looks like this. (check foreach styles.. )
<img width="820" alt="image" src="https://user-images.githubusercontent.com/111423116/200762164-14403547-fe04-40f4-919d-31db0527cf53.png">

3. Finally,, I found Problem at this styles (Editor, Entry), and then remove this codes, and move to the local xaml styles ( for example: ContentsPage.Resources)
<img width="871" alt="image" src="https://user-images.githubusercontent.com/111423116/200762419-23880b5e-88b8-498c-8c17-a0676cef5a18.png">

4. Good 👍 

this is my solution
