### ISSUE TITLE
Merging ResourceDictionary from referenced assembly fails to compile

### ISSUE THREAD

**Issue by Luminisc** [dotnet/maui#4398] opened 2022-01-29 14:14 UTC
### Description

I want to create `ResourceDictionary` in separate project, and reuse it in other projects, but when I try to add it to application resources, I getting compilation error.
I've created simple .NET MAUI app (Main app), added another project as MAUI Class Library (Library project) and added reference to it to Main app. In Class Library, created custom `ResourceDictionary` file (CustomDictionary.xaml), added some styles to it.
After that, to App.xaml I've added following to my application:
```
<Application.Resources>
    <ResourceDictionary>
        <ResourceDictionary.MergedDictionaries>
            <ResourceDictionary Source="pack://application:,,,/SharedProject;component/CommonResources.xaml"/>
        </ResourceDictionary.MergedDictionaries>
    </ResourceDictionary>
</Application.Resources>
```
But after compilation, I'm getting error "Invalid URI: Invalid port specified." 
Even after I've changed it to `pack://application:80,,,...` still the same error.
Same if adding this in App constructor: `Resources.MergedDictionaries.Add(new ResourceDictionary() { Source = new Uri("pack://application:,,,/SharedProject;component/CommonResources.xaml") });`

### Steps to Reproduce

1. Create new MAUI app
2. Add new MAUI Class Library and reference of it to App project
3. Add ResourceDictionary.xaml to Class Library project
4. Add this resource dictionary to App.xaml like this
`<ResourceDictionary Source="pack://application:,,,/TRGT.Core.Platform;component/CommonResources.xaml"/>`
5. Try to compile
6. You getting error "Invalid URI: Invalid port specified."

### Version with bug

Preview 12 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows, I was *not* able test on other platforms

### Affected platform versions

All

**Comment by Redth** [comment] 2022-01-30 15:06
I don't believe this notation works in MAUI.  This is a Windows XAML / API feature only.

@PureWeen or @mattleibow or @StephaneDelcroix may have a better answer as far as how to actually accomplish this.

**Comment by mattleibow** [comment] 2022-01-31 04:06
I think you just add it using the type name. For example, assume you have some dictionary `MyResources`, then you can just add it:

```xaml
<Application xmlns:mine="assembly include here">
  <Application.Resources>
    <ResourceDictionary>
      <ResourceDictionary.MergedDictionaries>
        <mine:MyResources />
      </ResourceDictionary.MergedDictionaries>
    </ResourceDictionary>
  </Application.Resources>
</Application>
```

**Comment by StephaneDelcroix** [comment] 2022-01-31 09:04
what @mattleibow suggested works, but that's a workaround.

we support referencing Xaml files in different assembly using ResourceDictionary.Source, but we choose not to follow the mouthful pack uri scheme, and go for a simpler `<ResourceDictionary Source="path/to/rd.xaml:assembly=otherAssembly">`. The source for the conversion is found here (https://github.com/dotnet/maui/blob/main/src/Controls/src/Core/ResourceDictionary.cs#L342) but the history of it is lost, or not easily trackable, and will die with me if I'm unlucky next time I cross a busy road.

**Comment by Luminisc** [comment] 2022-02-01 20:05
For some reason this approach is not working as well. 
Now I getting `XFC0124	Resource "CommonResources.xaml" not found.` when using `<ResourceDictionary Source="CommonResources.xaml;assembly=SharedProject"/>`.
My `CommonResources.xaml` file is in root of SharedProject.

And why this approach is not documented anywhere?

**Comment by StephaneDelcroix** [comment] 2022-02-02 08:14
do you mind sharing the smallest ever project triggering this issue ? thanks

**Comment by Luminisc** [comment] 2022-02-04 21:35
Sure. Just open solution file and run build, your build will fail with error
https://github.com/Luminisc/MAUISharedResources

**Comment by mattleibow** [comment] 2022-02-06 04:44
I just tested this now with preview 13 and it seems to build and run just fine. And I don't believe this code changed since Xamarin.Forms. Let me spin up a new VM with the public preview bits and see what happens.

**Comment by mattleibow** [comment] 2022-02-06 08:17
Just tested in a clean VM with VS 2022 17.1 Preview 5 with MAUI preview 12 and I get this error. My somewhat old version of 17.2 Preview 1 with an old MAUI preview 14.2765 seems to work.

I then took my official public preview VS on my VM and then ran the CLI workload install to install MAUI preview 13.2787 and it worked. So, this means that @StephaneDelcroix is probably doing magic as usual.

**Comment by mattleibow** [comment] 2022-02-06 08:49
I tried locally in VS 17.1 Preview 2 (very old) and MAUI preview 14.2765 and that still works. Basically, it works locally in most of my test cases. It does not work in my clean VM. Weird.

Testing the exact same dotnet SDK version on my VM and the exact same MAUI version locally. I should eventually have the exact same configuration.

**Comment by StephaneDelcroix** [comment] 2022-02-07 11:11
@mattleibow if you can get a 'diagnostic' log of your build, we should have a stack trace for the build failure

**Comment by StephaneDelcroix** [comment] 2022-02-07 11:17
(the sample provided build just fine on mac, using botnet build)

**Comment by mattleibow** [comment] 2022-02-07 16:06
@StephaneDelcroix This is my binlog from my VM: [msbuild.zip](https://github.com/dotnet/maui/files/8016781/msbuild.zip)

**Comment by shimingsg** [comment] 2022-02-16 03:50
Verified Repro with windows, Repro project available in Maui Triage Teams channel:
https://microsoft.sharepoint.com/:u:/t/Mauitriage/ESm3IfoKpj9DnyhKpLM6y8UBFvYFzX7snmwwO9lrPRn-Dw?e=bjV7wx

**Comment by StephaneDelcroix** [comment] 2022-04-22 08:20
@mattleibow I'm still unable to reproduce this, can you try to investigate if, for example, the resource is stripped from the referenced assembly ?

**Comment by cmonto** [comment] 2022-10-08 20:37
`<ResourceDictionary Source="path/to/rd.xaml;assembly=otherAssembly">`
This works... only if you are referencing (in your code/xaml) other classes from the assembly containing the ResourceDictionary. Maybe otherwise, due to optimization, the entire assembly is being kicked out, and the ResourceDictionary references can't be resolved.

**Comment by StephaneDelcroix** [comment] 2022-10-10 10:12
> `<ResourceDictionary Source="path/to/rd.xaml;assembly=otherAssembly">`
> This works... only if you are referencing (in your code/xaml) other classes from the assembly containing the ResourceDictionary. Maybe otherwise, due to optimization, the entire assembly is being kicked out, and the ResourceDictionary references can't be resolved.

you need code assembly, or indeed, the referenced assembly will be trimmed out

**Comment by mattleibow** [comment] 2022-10-11 03:35
Should we have a source generator to generate some code based on the Xaml?

**Comment by a-einstein** [comment] 2022-11-28 14:21
> `<ResourceDictionary Source="path/to/rd.xaml;assembly=otherAssembly">` This works... only if you are referencing (in your code/xaml) other classes from the assembly containing the ResourceDictionary. Maybe otherwise, due to optimization, the entire assembly is being kicked out, and the ResourceDictionary references can't be resolved.

I don't get this.
I think that's what I do, but I am still having the error message.

I have both the styles and various classes in one project.

**Comment by a-einstein** [comment] 2022-12-07 16:59
Update.

I returned to the old style I came from, as described by [mattleibow](https://github.com/mattleibow).

For some reason it just works again.

**Comment by XamlTest** [comment] 2023-04-11 10:38
Verified this issue on Visual Studio Enterprise 17.6.0 Preview 2.0. Repro on Windows with below Project:
[4398.zip](https://github.com/dotnet/maui/files/11199454/4398.zip)

**Comment by ecasasni** [comment] 2023-06-08 02:56
I tried [4398.zip](https://github.com/dotnet/maui/files/11199454/4398.zip) from @XamlTest and was able to reproduce the issue in Visual Studio for Mac 17.5.6 (build 3).
As @cmonto suggested, referencing a class from the `SharedProject1` makes it work, but only if I use 
```
<ResourceDictionary Source="CommonResources.xaml;assembly=SharedProject1" />
```

**Comment by StephaneDelcroix** [comment] 2023-07-28 08:00
closing this, as it seems to work when using the correct syntax

**Closed by StephaneDelcroix** 2023-07-28 08:00 UTC
Labels: t/bug, area/Xaml </>, s/verified, s/triaged

**Comment by Luminisc** [comment] 2023-07-28 10:33
It is working now using correct syntax AND referencing something from `SharedProject`, otherwise even with correct syntax it is not working

**Comment by StephaneDelcroix** [comment] 2023-07-28 11:39
I don't get what you mean by 'SharedProject'

**Comment by Luminisc** [comment] 2023-07-29 06:56
Project with `*.resx` file that I want to use in target project
