### ISSUE TITLE
HybridWebView: browser dev tools not working

### ISSUE THREAD

**Issue by mallibone** [dotnet/maui#24497] opened 2024-08-28 20:06 UTC
### Description

I currently am experiencing an issue in a small Vue app when integrating it into the hybrid web view. According to this issue #22305 the dev tools should be enabled by default. I do not see the app popping up under the Develop Safari Menu. Did see the the app showing when using the latest MAUI Blazor Hybrid template.

### Steps to Reproduce

Create a new MAUI App. Add a HybridWebView with a hello world Vue app (or basic HTML/JS provided in release notes of .NET 9 Preview 7). Check Develop Menu of Safari. No App appears under my current machine.

### Version with bug

9.0.0-preview.7.24407.4

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

macOS Sonoma 14.6.1

### Did you find any workaround?

No

**Comment by drasticactions** [comment] 2024-08-29 16:48
https://github.com/dotnet/maui/pull/19909 I fixed this for BlazorWebView, but AFAIK, WebView, BlazorWebView, and HybridWebView are different controls with different implementations. My fix for the original one was for BlazorWebView. A similar thing would need to be done for HybridWebView.

So AFAIK this wouldn't be a dupe.

**Comment by PureWeen** [comment] 2024-08-29 22:53
@Eilon thoughts?

**Comment by Eilon** [comment] 2024-09-09 16:32
Hmm I'll have to take a look. Pretty sure I used the Safari Dev Tools the other day while debugging HybridWebView. I'll try again.

**Comment by Eilon** [comment] 2024-09-09 16:53
OK I *do* see the Safari Dev Tools showing up, but they're empty. So it knows it's enabled, but it doesn't show any of the contents of the web view being inspected (no elements, no requests, etc.). The code for enabling this in both BlazorWebView and HybridWebView at first glance appears to be identical... so something weird is happening.

**Comment by Eilon** [comment] 2024-09-09 17:09
Alright confirmed that the problem is PEBKAC! Fix will be submitted soon!

**Comment by Eilon** [comment] 2024-09-09 18:09
PR here: #24679

@mallibone thanks for the report on this! It was such a silly bug!

**Comment by mallibone** [comment] 2024-09-09 19:36
Cool - thanks for taking the time. Looking forward to using it in an upcoming .NET release 😃

**Comment by jfversluis** [comment] 2024-09-10 07:07
Fixed by #24679

**Closed by jfversluis** 2024-09-10 07:07 UTC
Labels: t/bug, platform/macOS 🍏, area-controls-hybridwebview
