### ISSUE TITLE
Unable to access local network when using hot restart.  Error: The Internet connection appears to be offline.

### ISSUE THREAD

**Issue by yepeekai** [dotnet/maui#14930] opened 2023-05-04 17:42 UTC
### Description

I get the error "The Internet connection appears to be offline" when I try to access something on my local network with `HttpClient `from my IPhone.

It works when deploying the same app via a connected MAC.  This is probably the same bug as #12731 and #14224 
The sample code is based on those 2 bugs.  I am able to provide the ipa from windows and the .app folder from the MAC if need be, but I would prefer to share those privately since I don't know what personal keys and stuff is in there.

### Steps to Reproduce

1- Create a new MAUI project in visual studio 2022.
2- Replace the code of the method OnCounterClicked in the file MainPage.xaml.cs by :     
```
    private async void OnCounterClicked(object sender, EventArgs e)
    {
        lbl1.Text = "Before ping";
        await PingAsync("192.168.7.1");
        await Task.Delay(1000);
        lbl1.Text = "before connecting";
        await Task.Delay(1000);
        await ConnectAsync("192.168.7.51", 44398);
        await Task.Delay(1000);
        lbl1.Text = "before httpClient";
        await Task.Delay(1000);

        await TestAsync();
    }

    private async Task TestAsync()
    {
#if IOS && DEBUG
                var handler = new NSUrlSessionHandler
                {
                    TrustOverrideForUrl = (a, b, c) => true,
                };
                var httpClient = new HttpClient(handler) ;
#else
        var httpClient = new HttpClient() ;
#endif

        try
        {
            var response = await httpClient.GetAsync("https://192.168.7.51:44398/Mobile/Test");

            if (response.IsSuccessStatusCode)
            {
                var result = await response.Content.ReadFromJsonAsync<string>();
                lbl1.Text = "youhou:" + result;
            }
            else
            {
                lbl1.Text = "fail status code:" + response.StatusCode;
            }
        }
        catch (Exception ex)
        {
            lbl1.Text = $"TestAsync failed: {ex}";
            Debug.WriteLine(ex);
        }
    }

    public async Task PingAsync(string ipAddress)
    {
        try
        {
            Ping ping = new Ping();
            var reply = await ping.SendPingAsync(IPAddress.Parse(ipAddress));
            if(reply.Status == IPStatus.Success) 
            {
                lbl1.Text = $"Ping to {ipAddress} OK";
            }
            else 
            {
                lbl1.Text = $"Ping status {reply.Status.ToString()}";
            }
        }
        catch (Exception ex)
        {
            lbl1.Text = ex.ToString();
            Debug.WriteLine(ex);
        }
    }

    public async Task ConnectAsync(string ipAddr, int port)
    {
        try
        {
            TcpClient client = new TcpClient();
            await client.ConnectAsync(IPAddress.Parse(ipAddr), port);
            client.Close();
            lbl1.Text = $"Connect to {ipAddr} OK";
        }
        catch (Exception ex)
        {
            lbl1.Text = $"Connect to {ipAddr} failed: {ex}";
            Debug.WriteLine(ex);
        }
    }
```
3. Add the following lines to info.plist:
```
  <key>NSAppTransportSecurity</key>
  <dict>
    <key>NSAllowsLocalNetworking</key>
    <true/>
    <key>NSAllowsArbitraryLoads</key>
    <true/>
  </dict>
```

4. Replace the ip, port and url with something accessible for you on your local network.
5. Deploy to local IPhone on windows machine (hot restart).  All 3 tests fail.  The first 2 fail with error "No route to host" and the last one fails with error "The Internet connection appears to be offline."

### Link to public reproduction project repository

The code is pasted in the reproduce steps

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

IOS 16.4

### Did you find any workaround?

When deploying via a mac machine, it works.

### Relevant log output

```shell
[0:] System.Net.NetworkInformation.PingException: An exception occurred during a Ping request.
 ---> System.Net.Sockets.SocketException (65): No route to host
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.CreateException(SocketError error, Boolean forAsyncThrow)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.SendToAsync(Socket socket, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.SendToAsync(ReadOnlyMemory`1 buffer, SocketFlags socketFlags, EndPoint remoteEP, CancellationToken cancellationToken)
   at System.Net.NetworkInformation.Ping.SendIcmpEchoRequestOverRawSocketAsync(IPAddress address, Byte[] buffer, Int32 timeout, PingOptions options)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[<SendIcmpEchoRequestOverRawSocketAsync>d__70](<SendIcmpEchoRequestOverRawSocketAsync>d__70& stateMachine)
   at System.Net.NetworkInformation.Ping.SendIcmpEchoRequestOverRawSocketAsync(IPAddress address, Byte[] buffer, Int32 timeout, PingOptions options)
   at System.Net.NetworkInformation.Ping.SendPingAsyncCore(IPAddress address, Byte[] buffer, Int32 timeout, PingOptions options)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[<SendPingAsyncCore>d__84](<SendPingAsyncCore>d__84& stateMachine)
   at System.Net.NetworkInformation.Ping.SendPingAsyncCore(IPAddress address, Byte[] buffer, Int32 timeout, PingOptions options)
   at System.Net.NetworkInformation.Ping.SendPingAsyncInternal(IPAddress address, Int32 timeout, Byte[] buffer, PingOptions options)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[<SendPingAsyncInternal>d__51](<SendPingAsyncInternal>d__51& stateMachine)
   at System.Net.NetworkInformation.Ping.SendPingAsyncInternal(IPAddress address, Int32 timeout, Byte[] buffer, PingOptions options)
   at System.Net.NetworkInformation.Ping.SendPingAsync(IPAddress address, Int32 timeout, Byte[] buffer, PingOptions options)
   at System.Net.NetworkInformation.Ping.SendPingAsync(IPAddress address)
   at MauiLandryTest.MainPage.PingAsync(String ipAddress) in E:\repos\TestMaui\MauiLandryTest\MauiLandryTest\MainPage.xaml.cs:line 74
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[<PingAsync>d__4](<PingAsync>d__4& stateMachine)
   at MauiLandryTest.MainPage.PingAsync(String ipAddress)
   at MauiLandryTest.MainPage.OnCounterClicked(Object sender, EventArgs e) in E:\repos\TestMaui\MauiLandryTest\MauiLandryTest\MainPage.xaml.cs:line 24
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[<OnCounterClicked>d__2](<OnCounterClicked>d__2& stateMachine)
   at MauiLandryTest.MainPage.OnCounterClicked(Object sender, EventArgs e)
   at Microsoft.Maui.Controls.Button.Microsoft.Maui.Controls.Internals.IButtonElement.PropagateUpClicked()
   at Microsoft.Maui.Controls.ButtonElement.ElementClicked(VisualElement visualElement, IButtonElement ButtonElementManager)
   at Microsoft.Maui.Controls.Button.SendClicked()
   at Microsoft.Maui.Controls.Button.Microsoft.Maui.IButton.Clicked()
   at Microsoft.Maui.Handlers.ButtonHandler.OnButtonTouchUpInside(Object sender, EventArgs e)
   at UIKit.UIControlEventProxy.Activated()
   at UIKit.UIApplication.xamarin_UIApplicationMain(Int32 , String[] , IntPtr , IntPtr , IntPtr& )
   at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName)
   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass)
   at MauiLandryTest.Program.Main(String[] args) in E:\repos\TestMaui\MauiLandryTest\MauiLandryTest\Platforms\iOS\Program.cs:line 13
   at System.Reflection.RuntimeMethodInfo.InternalInvoke(RuntimeMethodInfo , Object , Span`1& , Exception& )
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Xamarin.iOS.HotRestart.Application.Run(String[] args, Action`1 loadFrameworkAction, Action killApplicationAction)
   at Xamarin.PreBuilt.iOS.Applications.Main(String[] args) in /Users/builder/azdo/_work/2/s/xamarin-macios/msbuild/Xamarin.HotRestart.PreBuilt/Xamarin.PreBuilt.iOS/Main.cs:line 12
--- End of stack trace from previous location ---
   at System.Net.NetworkInformation.Ping.SendIcmpEchoRequestOverRawSocketAsync(IPAddress address, Byte[] buffer, Int32 timeout, PingOptions options)
   at System.Net.NetworkInformation.Ping.SendPingAsyncCore(IPAddress address, Byte[] buffer, Int32 timeout, PingOptions options)
   at System.Net.NetworkInformation.Ping.SendPingAsyncInternal(IPAddress address, Int32 timeout, Byte[] buffer, PingOptions options)
   --- End of inner exception stack trace ---
   at System.Net.NetworkInformation.Ping.SendPingAsyncInternal(IPAddress address, Int32 timeout, Byte[] buffer, PingOptions options)
   at MauiLandryTest.MainPage.PingAsync(String ipAddress) in E:\repos\TestMaui\MauiLandryTest\MauiLandryTest\MainPage.xaml.cs:line 74

[0:] System.Net.Sockets.SocketException (65): No route to host
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.CreateException(SocketError error, Boolean forAsyncThrow)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ConnectAsync(Socket socket)
   at System.Net.Sockets.Socket.ConnectAsync(EndPoint remoteEP, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.ConnectAsync(EndPoint remoteEP)
   at System.Net.Sockets.Socket.ConnectAsync(IPAddress address, Int32 port)
   at System.Net.Sockets.TcpClient.ConnectAsync(IPAddress address, Int32 port)
   at MauiLandryTest.MainPage.ConnectAsync(String ipAddr, Int32 port) in E:\repos\TestMaui\MauiLandryTest\MauiLandryTest\MainPage.xaml.cs:line 96
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[<ConnectAsync>d__5](<ConnectAsync>d__5& stateMachine)
   at MauiLandryTest.MainPage.ConnectAsync(String ipAddr, Int32 port)
   at MauiLandryTest.MainPage.OnCounterClicked(Object sender, EventArgs e) in E:\repos\TestMaui\MauiLandryTest\MauiLandryTest\MainPage.xaml.cs:line 28
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[MauiLandryTest.MainPage.<OnCounterClicked>d__2, MauiLandryTest, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].ExecutionContextCallback(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[MauiLandryTest.MainPage.<OnCounterClicked>d__2, MauiLandryTest, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[MauiLandryTest.MainPage.<OnCounterClicked>d__2, MauiLandryTest, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at System.Threading.Tasks.SynchronizationContextAwaitTaskContinuation.<>c.<.cctor>b__8_0(Object state)
   at Foundation.NSAsyncSynchronizationContextDispatcher.Apply()
   at UIKit.UIApplication.xamarin_UIApplicationMain(Int32 , String[] , IntPtr , IntPtr , IntPtr& )
   at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName)
   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass)
   at MauiLandryTest.Program.Main(String[] args) in E:\repos\TestMaui\MauiLandryTest\MauiLandryTest\Platforms\iOS\Program.cs:line 13
   at System.Reflection.RuntimeMethodInfo.InternalInvoke(RuntimeMethodInfo , Object , Span`1& , Exception& )
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Xamarin.iOS.HotRestart.Application.Run(String[] args, Action`1 loadFrameworkAction, Action killApplicationAction)
   at Xamarin.PreBuilt.iOS.Applications.Main(String[] args) in /Users/builder/azdo/_work/2/s/xamarin-macios/msbuild/Xamarin.HotRestart.PreBuilt/Xamarin.PreBuilt.iOS/Main.cs:line 12
--- End of stack trace from previous location ---
   at System.Net.Sockets.TcpClient.CompleteConnectAsync(Task task)
   at MauiLandryTest.MainPage.ConnectAsync(String ipAddr, Int32 port) in E:\repos\TestMaui\MauiLandryTest\MauiLandryTest\MainPage.xaml.cs:line 96

[0:] System.Net.Http.HttpRequestException: The Internet connection appears to be offline.
 ---> Foundation.NSErrorException: Error Domain=NSURLErrorDomain Code=-1009 "The Internet connection appears to be offline." UserInfo={_kCFStreamErrorCodeKey=50, NSUnderlyingError=0x2805b3900 {Error Domain=kCFErrorDomainCFNetwork Code=-1009 "(null)" UserInfo={_NSURLErrorNWPathKey=unsatisfied (Local network prohibited), interface: en0[802.11], ipv4, ipv6, _kCFStreamErrorCodeKey=50, _kCFStreamErrorDomainKey=1}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <57064384-6678-4561-BB42-553D66D9924E>.<1>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <57064384-6678-4561-BB42-553D66D9924E>.<1>"
), NSLocalizedDescription=The Internet connection appears to be offline., NSErrorFailingURLStringKey=https://192.168.7.51:44398/Mobile/Test, NSErrorFailingURLKey=https://192.168.7.51:44398/Mobile/Test, _kCFStreamErrorDomainKey=1}
   --- End of inner exception stack trace ---
   at System.Net.Http.NSUrlSessionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at MauiLandryTest.MainPage.TestAsync() in E:\repos\TestMaui\MauiLandryTest\MauiLandryTest\MainPage.xaml.cs:line 50
```

**Comment by mattleibow** [comment] 2023-05-04 18:18
Duplicate of https://github.com/dotnet/maui/issues/12731

**Closed by mattleibow** 2023-05-04 18:18 UTC
Labels: t/bug
