### ISSUE TITLE
The screen is white on iOS when using Shell

### ISSUE THREAD

**Issue by HobDev** [dotnet/maui#5786] opened 2022-04-04 05:41 UTC
### Description

The maui app shows white screen on iOS when using Shell. Although the same app display the UI on Android. The repro project is default template modified to add Shell. 

### Steps to Reproduce

Run the repro project on remoted iOS simulator from Windows. 
[iOSIssue.zip](https://github.com/dotnet/maui/files/8406974/iOSIssue.zip)

### Version with bug

Preview 14 (current)

### Last version that worked well

Preview 13

### Affected platforms

iOS

### Affected platform versions

iOS 15

### Did you find any workaround?

NO

**Comment by jfversluis** [comment] 2022-04-04 11:58
Duplicate of #5549

**Closed by jfversluis** 2022-04-04 11:58 UTC
Labels: t/bug, platform/iOS 🍎, area/shell 🐢, s/needs-verification
