### ISSUE TITLE
Unable to run MAUI blazor project in Visual Studio 2022 Preview (latest - 11/08/2021)

### ISSUE THREAD

**Issue by Xyncgas** [dotnet/maui#3303] opened 2021-11-08 17:55 UTC
I would expect MAUI blazor to be able to run after creating the project without modification.
I also installed .net 6.01 manually after it didn't work initially.
which according to https://docs.microsoft.com/en-us/dotnet/maui/get-started/installation it shoud.

**Comment by limefrogyank** [comment] 2021-11-08 21:17
I've got the same problem and I've double checked that these workloads are installed.

**Comment by Eilon** [comment] 2021-11-08 21:27
@limefrogyank - understood. I'm not an expert in this area, so I'm just mentioning what's worked for me in the past:

1. Have you tried doing a Repair operation in the VS installer?
2. From a command line can you try to install the workloads from there, such as `dotnet workload install maui` to make sure it has these:
    ```
    Workload ID           Description
    -----------------------------------------------------
    maui                  .NET MAUI SDK for all platforms
    maui-android          .NET MAUI SDK for Android
    maui-desktop          .NET MAUI SDK for Desktop
    maui-ios              .NET MAUI SDK for iOS
    maui-maccatalyst      .NET MAUI SDK for Mac Catalyst
    maui-mobile           .NET MAUI SDK for Mobile
    maui-windows          .NET MAUI SDK for Windows
    ```

**Comment by limefrogyank** [comment] 2021-11-08 21:30
I had the previous preview (when dotnet6 was preview9 I think) and just upgraded to Version 17.1.0 Preview 1.0.  

That seemed to wipe out all my SDKs.  I just did `dotnet --list-sdks` and there's nothing listed.  I'll try out the workloads you suggested though.

**Comment by limefrogyank** [comment] 2021-11-08 23:15
Seems I was hit by this bug:
https://github.com/dotnet/core/blob/main/release-notes/6.0/known-issues.md#2-upgrade-of-visual-studio-or-net-sdk-from-earlier-builds-can-result-in-a-bad-path-configuration-on-windows

Maybe that applies to the OP

**Comment by Eilon** [comment] 2021-11-08 23:40
@limefrogyank - yeah that bug with the SDK PATH getting messed up has hit a lot of people. Good to check that first because it's an easy fix.

**Comment by limefrogyank** [comment] 2021-11-09 00:24
For the record, once I fixed my PATH, I still had to "repair" my VS2022 installations afterwards.

**Comment by ElliottBrand** [comment] 2021-11-09 02:06
I'm running into issues as well. Things worked fine until I performed the upgrade today, then all kinds of things quit working. I ended up uninstalling VS2022 Preview and installed the newly released version (Community Edition).  I also had to remove the contents of the C:\Program Files (x86)\dotnet folder to even get command line to recognize I had any SDKs installed. Now I can't even load a MAUI Blazor app, it just says (incompatible) next to the project, with no explanation as to why it can't load. The rest of my projects seem to work fine, it's just the MAUI Blazor app that won't load.

**Comment by Xyncgas** [comment] 2021-11-09 02:44
> @Xyncgas I think I've seen a similar issue and it turned out I didn't have all the "dotnet workloads" for Android, iOS, etc installed. I think Visual Studio is supposed to warn you if it detects missing workloads. I'm transferring this issue to the .NET MAUI repo so someone there can take a look.
> 
> Can you also confirm in the Visual Studio Installer that you have the `Mobile development with .NET` option enabled, and in the Individual Components tab, all of the MAUI options:
> 
> ![image](https://user-images.githubusercontent.com/202643/140817563-2f447666-74bd-4d08-a77b-b44cc69cf457.png)

I can confirm

**Comment by Xyncgas** [comment] 2021-11-09 02:49
After upgrading to visual studio today all my older project can't opened too, they show as unloaded and when I try to load it's erroring

**Comment by Eilon** [comment] 2021-11-09 05:01
@Xyncgas OK then I'm not sure what it could be. The MAUI experts in this repo can hopefully help.

**Comment by danielbichuetti** [comment] 2021-11-09 10:29
I upgraded to latest Preview and installed all workload's. Double checked paths. This behavior occurs on Windows 11, VS 2022 17.1 and macOS BigSur + Rider 2021.3 EAP7:

Generated APK fails to run when using MAUI Blazor project, if MAUI only it works.  It open default project and when showing "Loading..." on app it halts.

Windows and macOS bin's works fine.

**Comment by vetkaashaas** [comment] 2021-11-09 11:13
> For the record, once I fixed my PATH, I still had to "repair" my VS2022 installations afterwards.

Can confirm this worked for me as well.

**Comment by danielbichuetti** [comment] 2021-11-09 11:23
> > For the record, once I fixed my PATH, I still had to "repair" my VS2022 installations afterwards.
> 
> Can confirm this worked for me as well.

I repaired Preview and I managed to install VS 2022 Current and Rider. Issue is not installation related (at least in my scenario). MAUI workloads points to latest Preview 10, SDK is LTS. A friend just tried MAUI Blazor with latest tools and frameworks, same behavior detected. Windows and Mac editions.

**Comment by danielbichuetti** [comment] 2021-11-09 12:49
> > > For the record, once I fixed my PATH, I still had to "repair" my VS2022 installations afterwards.
> > 
> > 
> > Can confirm this worked for me as well.
> 
> I repaired Preview and I managed to install VS 2022 Current and Rider. Issue is not installation related (at least in my scenario). MAUI workloads points to latest Preview 10, SDK is LTS. A friend just tried MAUI Blazor with latest tools and frameworks, same behavior detected. Windows and Mac editions.

Got it to work removing Windows Machine profile, even if it wasn't selected. Not sure yet what was happenning. I can still reproduce error if Windows Machine launchSettings.json is not removed.

**Comment by Eilon** [comment] 2021-11-09 17:00
@danielbichuetti very interesting regarding the profile. That info should hopefully help us figure out what's causing this.

**Comment by Xyncgas** [comment] 2021-11-09 20:06
did you guys delete C:\Program Files X86\dotnet then move the content to C:\Program Files\dotnet ?
I am not sure if that's what https://github.com/dotnet/core/blob/main/release-notes/6.0/known-issues.md#2-upgrade-of-visual-studio-or-net-sdk-from-earlier-builds-can-result-in-a-bad-path-configuration-on-windows meant

**Comment by davidbuckleyni** [comment] 2021-11-10 00:39
Did u remove all previous previews ran maui check in case sometimes u might forget to tick something

**Comment by Xyncgas** [comment] 2021-11-10 01:50
I am about to install visual studio preview after uninstalling every visual studio + donetsdk
I wanna know if I need to download .net sdk 6.01 manually from the website or does visual studio does that already

**Comment by Xyncgas** [comment] 2021-11-10 02:01
huh I can't find it now 
![image](https://user-images.githubusercontent.com/35312807/141035844-f86bfc5a-daec-4571-a17f-e80baf57551e.png)

**Comment by Xyncgas** [comment] 2021-11-10 02:01
I did make sure to select mobile development and I saw maui checked. I also installed .net desktop and asp.net

**Comment by limefrogyank** [comment] 2021-11-10 02:04
> did you guys delete C:\Program Files X86\dotnet then move the content to C:\Program Files\dotnet ? I am not sure if that's what https://github.com/dotnet/core/blob/main/release-notes/6.0/known-issues.md#2-upgrade-of-visual-studio-or-net-sdk-from-earlier-builds-can-result-in-a-bad-path-configuration-on-windows meant

Try this: https://www.wikihow.com/Change-the-PATH-Environment-Variable-on-Windows#:~:text=How%20to%20Change%20the%20Path%20in%20Windows%2010,options%20titled%20OS%20and%20PATHEXT%20.%20See%20More.

**Comment by juansturla** [comment] 2021-11-10 16:52
I had the same Issue.
In my system PATH the `Program Files (x86)/dotnet` was above the `Program Files/dotnet`
If you just change the order, the dotnet command will work again, but you will still have problems running an app.
You will have to change the order (or delete the x86 variable) and then reinstall VS2022

**Comment by Eilon** [comment] 2022-02-11 00:11
Hi, we think this issue has been fixed in more recent previews of .NET MAUI and Visual Studio. Please try installing the latest preview per the instructions at https://docs.microsoft.com/dotnet/maui/get-started/installation. If you are still experiencing an issue, please file a new issue with updated details.

Regarding some other discussions in this thread, installing Visual Studio with the right workloads (in particular, the one for Mobile Development), should install everything that you need.

**Closed by Eilon** 2022-02-11 00:11 UTC
Labels: area/setup 🪄
