### ISSUE TITLE
Maui Splash Screen  and AppIcon will not update on iOS App ,

### ISSUE THREAD

**Issue by Perryyang1979** [dotnet/maui#19732] opened 2024-01-07 11:26 UTC
### Description

I changed the default splash images  use the same name (splash.svg)in my MAUI solution. The changes were effected on Android device but on iOS device, the default splash images show. Even just changing the Color property in the .csproj file has no effect on iOS device. I am using Visual Studio Version 17.6

### Steps to Reproduce

Create a new MAUI app
Change the splash image. (or just change the Color property of the SplashScreen property in .csproj file.
Run or deploy the app to Android Device - the splash images are updated as expected
Run or deploy the app to iOS device - the changes are not effected. The default .NET splash images still shows,
Try to change the name of the splashscreen svg file, delete app on iOS device, reboot device, clean solution and deploy to iOS device - still splash images not updated.

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Did you find any workaround?

None yet ,the problem is same as https://github.com/dotnet/maui/issues/17940  //
I try to  use the solution from [MouratidisA](https://github.com/MouratidisA) ,but it does not work.

**Comment by mattleibow** [comment] 2024-01-08 15:26
Duplicate of https://github.com/dotnet/maui/issues/19640

**Closed by mattleibow** 2024-01-08 15:26 UTC
Labels: t/bug, area/single project ☝️, platform/iOS 🍎
