### ISSUE TITLE
Second Window Crashes on Close

### ISSUE THREAD

**Issue by mkehoe-Extron** [dotnet/maui#10708] opened 2022-10-16 02:12 UTC
### Description

On Windows when you open a second window with a WebView and then close it, it crashes. Issue exists in latest dotnet 6 and dotnet 7 preview.

### Steps to Reproduce

1. Run the sample project in the debugger
2. Click the button on the mainpage to open a second window.
3. Close the second window and you will see an unhandled exception.

### Link to public reproduction project repository

https://github.com/mkehoe-Extron/MauiSecondWindowCrash

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10

**Comment by jsuarezruiz** [comment] 2022-10-17 08:54
Duplicate of https://github.com/dotnet/maui/issues/8323

**Closed** 2022-10-21 14:29 UTC
Labels: t/bug, s/duplicate 2️⃣, platform/windows 🪟, high
