### ISSUE TITLE
Button BackgroundColor does not change with IsEnabled State on Release to Device Only

### ISSUE THREAD

**Issue by zslocum** [dotnet/maui#8961] opened 2022-07-24 01:22 UTC
### Description

After building for release and sideloading the APK onto a device a button which changes IsEnabled state does not have it's background color change with the state even though that is configured and works in an Emulator.

### Steps to Reproduce

1. Start a new MAUI project in Visual Studio using the default template.
2. Add a button that toggles the state of the default 'Click Me' button that is in the MainPage.xaml:

```xaml
<Button
                Clicked="OnToggleClicked"
                Text="Toggle Other Button"
                />
```
MainPage.xaml.cs :
```cs
private void OnToggleClicked(object sender, EventArgs e)
	{
		CounterBtn.IsEnabled = !CounterBtn.IsEnabled;
	}
```
3. Run the project in an Android emulator and you will see that the "Click Me" button changes background as expected when the "Toggle Other Button" button is pressed. 

4. Build the project using: dotnet build -c Release -f net6.0-android
5. Copy the resulting APK to a device and install it.
6. Run the app and the button does not change background as it did within the emulator but the text color will still change.

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 12

### Did you find any workaround?

Use the Background property instead of BackgroundColor and the button color changes as expected. Just need to make sure to use Brush instead of Color as the values.

**Comment by leoderja** [comment] 2022-07-27 17:28
Thank you for your workaround, zslocum

**Comment by samuelcourtney** [comment] 2022-09-13 19:38
This occurs in iOS as well, zslocum's work around solves for both platforms. Much appreciated.

**Comment by javiercampos** [comment] 2022-10-25 12:05
I have the same problem (in Android), but in addition, my button is not re-enabled (I can see the foreground color change, but not the background, but users can't click it [usinga `Clicked` event, not a MVVM Command], which makes it extremely frustrating). Doesn't happen when debugging from VS, but happens when you sideload the published APK.

As a workaround, I'm just changing the colors and adding a guard clause to the event, but this is extremely annoying and I'm wondering what kind of real-life tests have been done before getting MAUI to a "release" state (I seem to be doing workaround after workaround for bugs that are published here as issues for the most extremely basic things).

Not wanting to bash the MAUI devs, of course, it is what it is, but the fact that MAUI was even considered "final" at any point (probably nothing to do with the actual MAUI devs), is flabbergasting to me

**Comment by Joost1982** [comment] 2022-11-24 23:45
Had the same problem today; based on the IsEnabled value the background color changed on the emulator, but not on my Android device.
Using the Background property instead of BackgroundColor, as @zslocum suggested, fixed it.

**Comment by mattleibow** [comment] 2022-12-08 13:58
What happens if you disable AOT in release mode?

```
<RunAOTCompilation>false</RunAOTCompilation>
```

Might be related to this one: https://github.com/dotnet/maui/issues/11662

**Comment by mattleibow** [comment] 2022-12-08 14:07
Duplicate of #11662

**Closed by mattleibow** 2022-12-08 14:07 UTC
Labels: t/bug, platform/android 🤖, area/controls 🎮, area/publishing 🏁
