### ISSUE TITLE
After microsoft update Visual studio 17.10.1  Mac pair failed  form last night  2024-05-30

### ISSUE THREAD

**Issue by spsuwal** [dotnet/maui#22733] opened 2024-05-30 08:09 UTC
### Description

    DateTime=2024-05-30T07:51:56.8933058Z: 05/30/2024 07:51:56Z
Xamarin.Messaging.Integration.State.ServerStateContext Information: 0 : Server State transition from DisconnectedState to DisconnectedState on Surendra’s MacBook Pro (192.168.1.61): 05/30/2024 07:51:56Z
    DateTime=2024-05-30T07:51:56.8983048Z: 05/30/2024 07:51:56Z
Xamarin.Messaging.Integration.State.ServerStateContext Error: 0 : Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Xamarin.VisualStudio.IOS.Messaging.MonoInstallationConfigurator.<ConfigureAsync>d__13.MoveNext() in D:\a\_work\1\s\src\Core\VisualStudio.IOS\Messaging\MonoInstallationConfigurator.cs:line 103
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Xamarin.Messaging.Integration.State.ConfiguringState.<ExecuteConfiguratorsAsync>d__26.MoveNext() in D:\a\_work\1\s\src\Xamarin.Messaging.Integration\State\ConfiguringState.cs:line 504: 05/30/2024 07:51:56Z
    DateTime=2024-05-30T07:51:56.9264162Z: 05/30/2024 07:51:56Z
Xamarin.Messaging.Integration.State.ServerStateContext Error: 0 : !Object reference not set to an instance of an object.: 05/30/2024 07:51:56Z
    DateTime=2024-05-30T07:51:56.9264162Z: 05/30/2024 07:51:56Z
Xamarin.Messaging.Integration.State.ServerStateContext Information: 0 : Server State transition from DisconnectedState to DisconnectedState on Surendra’s MacBook Pro (192.168.1.61): 05/30/2024 07:51:56Z
    DateTime=2024-05-30T07:51:56.9335049Z: 05/30/2024 07:51:56Z

### Steps to Reproduce

Try to connect existing maui blazor app with working mac  its failed after configuring mono install.

### Version with bug

8.0.40 SR5

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI, Yes, this used to work in Xamarin.Forms

### Last version that worked well

8.0.40 SR5

### Affected platforms

iOS, macOS

**Comment by spsuwal** [comment] 2024-05-30 08:12
this issue is not related to any local environment but its seem like there is issue on server side.

**Comment by drasticactions** [comment] 2024-05-30 09:05
Duplicate of https://github.com/dotnet/maui/issues/22722

A web service used for fetching the versions of .NET / Mono to provision is currently down, which is causing that null reference exception to happen. It's unrelated to MAUI itself nor any release of Visual Studio.

**Closed by drasticactions** 2024-05-30 09:05 UTC
Labels: t/bug, s/triaged
