### ISSUE TITLE
ListView duplicate first item

### ISSUE THREAD

**Issue by Felicity-R** [dotnet/maui#22742] opened 2024-05-30 18:30 UTC
### Description

Same issue as https://github.com/dotnet/maui/issues/10582, which was closed due to inactivity but is still a problem. I couldn't re-open it so I am just creating a new ticket.

If a ListView is initially hidden, then made visible, the first item added appears twice, even though the ItemSource contains only one item. Adding more items causes the second item to display the 2 values overlapping.
MauiListViewDuplicateItem

### Steps to Reproduce

1. Set up a project with a listview that's initially not visible (see demo)
2. Make the list visible, and then add an item (in the demo: click the 'show' button which will set the visibility and then add a first item).
3. At this point you'll see two copies of the first item
4. Optionally add more items and you'll see how they overlap with the 'ghost' of the first item.
![image](https://github.com/dotnet/maui/assets/62772237/70fcb301-dea3-429d-a913-fdd4f16b4f25)

### Link to public reproduction project repository

https://github.com/Felicity-R/ListViewBugDemo

### Version with bug

8.0.14 SR3.1

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Windows 10.0.19043

**Comment by Zhanglirong-Winnie** [comment] 2024-05-31 07:51
Verified this issue with Visual Studio 17.11.0 Preview 1.0(8.0.40 & 8.0.21 & 8.0.3). Can repro on windows platform with sample project.

**Comment by PureWeen** [comment] 2024-05-31 22:29
Duplicate of #21981

**Closed by PureWeen** 2024-05-31 22:29 UTC
Labels: t/bug, platform/windows 🪟, area-controls-listview, s/verified, s/triaged, migration-compatibility
