### ISSUE TITLE
Images 90 degrees rotated in iOS

### ISSUE THREAD

**Issue by williambuchanan2** [dotnet/maui#13978] opened 2023-03-16 09:28 UTC
### Description

Using MediaPicker - CapturePhotoAsync()

On iOS all photos come out in the wrong orientation.

If the phone is portrait then the photos will be 90 degrees out - so will be on their side.
If the phone is landscape then the photos will be 180 degrees out - so upside down.

Seems to be so many issues with the Media Picker. Just trying to take photos in Maui is becoming an utter pain.

Strangely the problem doesn't exist in Android.

### Steps to Reproduce

 FileResult fileResult = await MediaPicker.CapturePhotoAsync();

Look at photos. As described above.

### Link to public reproduction project repository

?

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS16

### Did you find any workaround?

No

**Comment by drasticactions** [comment] 2023-03-16 09:36
Duplicate of https://github.com/dotnet/maui/issues/9535

**Closed by drasticactions** 2023-03-16 09:36 UTC
Labels: t/bug

**Comment by williambuchanan2** [comment] 2023-03-16 09:42
Ugh so it's been there 8 months already!!

**Comment by drasticactions** [comment] 2023-03-16 09:48
Longer, https://github.com/xamarin/Essentials/issues/1514

**Comment by williambuchanan2** [comment] 2023-03-16 09:49
Good grief! That's a joke. Can't see any workarounds either - are you aware of any?

**Comment by drasticactions** [comment] 2023-03-16 09:53
As mentioned on the original bug, this concerns how iOS handles EXIF data for rotation and how Essentials/MAUI processes it, and AFAIK it becomes a rat nest of design review "What should this do in any given situation" that then leaves this hanging.

The Xamarin.MediaGallery library does implement a fix (https://github.com/dimonovdd/Xamarin.MediaGallery) and they are trying to port that back into MAUI (https://github.com/dotnet/maui/pull/13564) which would fix the issue. IMO I rather see MediaPicker deprecated and this code moved into the CommunityToolkit instead, so future fixes could be iterated on faster without the bloat of getting fixes into the framework proper.

**Comment by dimonovdd** [comment] 2023-03-18 16:20
> Hmmm I had played with MediaGallery 

Please  read [FAQ](https://github.com/dimonovdd/Xamarin.MediaGallery#faq)

**Comment by williambuchanan2** [comment] 2023-03-19 04:08
Hi

> You have to understand that each application wants different behaviors. In my application, I need original images without any changes. if the plugin rotate them, the behavior will be incorrect.

I can understand that to a certain extent, however I don't see why ios flips the images upside down. Why would that be of any use to anyone? I would expect that when you take a photo the top stays at the top but it doesn't seem to work like that. If there is some sensible logic behind this, then why would Android not do the same thing?

**Comment by dimonovdd** [comment] 2023-03-19 11:08
> then why would Android not do the same thing?

Android does that too. It depends on the specific device.
