### ISSUE TITLE
On Android only, buttons inside grid stays invisible after grid visibility changes to true

### ISSUE THREAD

**Issue by hbraasch** [dotnet/maui#8574] opened 2022-07-07 02:37 UTC
### Description

Buttons are placed inside a grid. The grids visibility is set to false during startup. The buttons does not display as expected.
When instructing the buttons to appear by setting the IsVisible to true, they stay invisible.

A repro project is provided.

Below is shown how it should work on iOS. Play video...

https://user-images.githubusercontent.com/7484186/177677642-3dfbac9a-4bad-4555-8a3c-2742f5fb4f44.mp4

Below is shown how it should work on Windows. Play video...

https://user-images.githubusercontent.com/7484186/177677687-1e18c264-bf6d-48c2-9fe8-98e23e9c4141.mp4

Below is how it SHOULD not work on Android. Play video...

https://user-images.githubusercontent.com/7484186/177677768-4493a7af-6ab1-4ce0-a759-c2340c39ce64.mp4

### Steps to Reproduce

1. Open the repro project from Github inside Visual Studio: https://github.com/hbraasch/LayoutTester.git
2. Run each project for each platform. Follow the click- steps as demonstrated in the videos above
3. Observe the difference in display behaviour

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 12 API 31

### Did you find any workaround?

No

**Comment by Symbai** [comment] 2022-07-07 05:28
> ### Version with bug
> 6.0.400 (current)

Has a known and already fixed bug with IsVisible not working. I expect this to be a dupe of #8044

**Comment by jsuarezruiz** [comment] 2022-07-07 07:14
This issue have been fixed by https://github.com/dotnet/maui/pull/8136 and will be available in the upcoming release.

**Comment by mattleibow** [comment] 2023-01-16 22:49
Is this still an issue? It has been a while and we have done lots to fix many layout and visibility issues. Hopefully this issue no longer persists.

**Closed** 2023-01-26 01:01 UTC
Labels: t/bug, platform/android 🤖, s/needs-info, area/controls 🎮, s/verified, s/triaged, s/no-recent-activity, s/try-latest-version
