### ISSUE TITLE
RadioButton preselection in xaml with multiple RadioButtonGroups not working

### ISSUE THREAD

**Issue by DavidCarKc** [dotnet/maui#6227] opened 2022-04-19 10:18 UTC
### Description

Creating 3 radio groups with 3 radio buttons in them and selecting one in each group as 
IsChecked="True"
Only the last one is checked (I checked in xaml RADIOONE, RADIOFOUR and RADIOSEVEN)
If I remove IsChecked="True" from RADIOSEVEN then only RADIOFOUR will be selected
I tried removing 
RadioButtonGroup.SelectedValue
from each group declaration but it didn't help I tried removing Labels but it didn't help, also tried to add GroupName option same as StackLayout RadioButtonGroup.GroupName, also not working

Then I tried without StackLayout RadioButtonGroup.GroupName And placing all RadioButtons in StackLayout with
GroupName in each radio buttons declaration but this worked in completley wrong way as system considered them all to be part of one group even though they were not

As someone already reported RadioButtons in Android app are completley dead and unselectable, they worked in last preview but not in RC1.

### Steps to Reproduce

Create new MAUI project mauiRadioButtonTestRC1 in
Microsoft Visual Studio Community 2022 (64-bit) - Preview
Version 17.2.0 Preview 3.0
Copypaste  //1st or 2nd xaml over mainpage and remove counting code from MainPage.xaml.cs

//1st - with RadioButtonGroup
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="mauiRadioButtonTestRC1.MainPage">

    <ScrollView>
        <VerticalStackLayout Spacing="25" Padding="30">

            <StackLayout RadioButtonGroup.GroupName="RADOIGROUPONE"
             RadioButtonGroup.SelectedValue="RADIOONE" >
                <Label Text="RADIO GROUP ONE" FontSize="Large" />
                <RadioButton Content="RADIOONE" IsChecked="True"
                 Value="RADIOONE" />
                <RadioButton Content="RADIOTWO" 
                 Value="RADIOTWO" />
                <RadioButton Content="RADIOTHREE"                             
                 Value="RADIOTHREE" />              
            </StackLayout>

            <StackLayout RadioButtonGroup.GroupName="RADOIGROUPTWO"
             RadioButtonGroup.SelectedValue="RADIOFOUR" >
                <Label Text="RADIO GROUP TWO" FontSize="Large" />
                <RadioButton Content="RADIOFOUR" IsChecked="True"
                 Value="RADIOFOUR" />
                <RadioButton Content="RADIOFIVE" 
                 Value="RADIOFIVE" />
                <RadioButton Content="RADIOSIX"                             
                 Value="RADIOSIX" />
            </StackLayout>

            <StackLayout RadioButtonGroup.GroupName="RADOIGROUPTHREE"
             RadioButtonGroup.SelectedValue="RADIOSEVEN" >
                <Label Text="RADIO GROUP THREE" FontSize="Large" />
                <RadioButton Content="RADIOSEVEN" IsChecked="True"
                 Value="RADIOSEVEN" />
                <RadioButton Content="RADIOEIGHT" 
                 Value="RADIOEIGHT" />
                <RadioButton Content="RADIONINE"                             
                 Value="RADIONINE" />
            </StackLayout>

        </VerticalStackLayout>
    </ScrollView>
</ContentPage>

//2nd with group name

<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="mauiRadioButtonTestRC1.MainPage">

    <ScrollView>
        <VerticalStackLayout Spacing="25" Padding="30">
          
                <RadioButton Content="RADIOONE" IsChecked="True"
                 Value="RADIOONE" GroupName="RADOIGROUPONE"/>
                <RadioButton Content="RADIOTWO" 
                 Value="RADIOTWO" GroupName="RADOIGROUPONE"/>
                <RadioButton Content="RADIOTHREE"                             
                 Value="RADIOTHREE" GroupName="RADOIGROUPONE"/>              
         
                      
                <RadioButton Content="RADIOFOUR" IsChecked="True"
                 Value="RADIOFOUR" GroupName="RADOIGROUPTWO"/>
                <RadioButton Content="RADIOFIVE" 
                 Value="RADIOFIVE" GroupName="RADOIGROUPTWO"/>
                <RadioButton Content="RADIOSIX"                             
                 Value="RADIOSIX" GroupName="RADOIGROUPTWO"/>
           
                       
                <RadioButton Content="RADIOSEVEN" IsChecked="True"
                 Value="RADIOSEVEN" GroupName="RADOIGROUPTHREE"/>
                <RadioButton Content="RADIOEIGHT" 
                 Value="RADIOEIGHT" GroupName="RADOIGROUPTHREE"/>
                <RadioButton Content="RADIONINE"                             
                 Value="RADIONINE" GroupName="RADOIGROUPTHREE"/>
          

        </VerticalStackLayout>
    </ScrollView>
</ContentPage>

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows

### Affected platform versions

windows 10, android 5.0

**Comment by XamlTest** [comment] 2022-04-19 13:00
Verified this issue with Visual Studio Enterprise 17.3.0 Preview 1.0 [32414.199.main]. Repro on Windows. Sample Project: [6227.zip](https://github.com/dotnet/maui/files/8513160/6227.zip)

**Comment by aaquino-ny** [comment] 2022-04-19 14:45
Looks like I am not the only one having this issue.   Hopefully Microsoft team can have a quick patch to solve this issue..  I am getting behind with development.   Yesterday, I updated Visual Studio 2022 Preview to version 17.2.0 Preview 3.0 and Radio buttons are not working when deployed on a mobile device but it works on windows desktop.  ahhhh :(

**Comment by shimingsg** [comment] 2022-05-07 07:29
verified repro on Windows 10 with VS 17.3.0 Preview 2.0 [32506.315.main]
![image](https://user-images.githubusercontent.com/20982341/167243842-7ade9aa3-eca7-4f5b-8f09-25f211b817fe.png)

not repro on Android 11 and Android 5

**Comment by aaquino-ny** [comment] 2022-05-10 16:11
Thanks to the latest release of VS202 Preview, Radio buttons are working again.

**Comment by softlion** [comment] 2022-05-10 16:20
> Thanks to the latest release of VS202 Preview, Radio buttons are working again.

It’s not working for me with the latest preview.

**Comment by samhouts** [comment] 2023-04-03 23:50
Duplicate of #11418

**Closed by samhouts** 2023-04-03 23:50 UTC
Labels: t/bug, area/controls 🎮, s/verified, control-radiobutton, s/triaged
