### ISSUE TITLE
Click goes through solid elements on android

### ISSUE THREAD

**Issue by Quietscheente** [dotnet/maui#12014] opened 2022-12-11 10:04 UTC
### Description

If i place a button underneath an element (a border for example) and click on the element on top the click goes through and reaches the button.
On windows works like expected, on Android button is clicked. 

### Steps to Reproduce

1. Create an empty Maui project
2. Set a button underneath an element for example
```
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MauiApp2.MainPage">

    <Grid>
        <Button Text="Never seen" Clicked="Button_Clicked"/>
        <Border BackgroundColor="Red"/>
    </Grid>
   
</ContentPage>
```
3. Click inside the red border
4. button clicked event is fired

### Link to public reproduction project repository

none

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11 PIxel 5 emulator and Android 12 local phone

**Comment by XamlTest** [comment] 2023-06-12 06:25
Verified this on Visual Studio Enterprise 17.7.0 Preview 1.0. This issue does not repro on Windows 11, repro on Android 13.0-API33 with below Project:
[12014.zip](https://github.com/dotnet/maui/files/11718712/12014.zip)

**Comment by davidortinau** [comment] 2023-07-06 19:13
Verified on .NET 8 Preview 6, API33

**Comment by jfversluis** [comment] 2023-11-22 08:27
Still reproduced with .NET 8. @mattleibow I guess this is part of the input transparent work you have been doing?

**Comment by mattleibow** [comment] 2024-05-30 17:33
Duplicate of https://github.com/dotnet/maui/issues/10252

**Closed by mattleibow** 2024-05-30 17:33 UTC
Labels: t/bug, platform/android 🤖, s/verified, area-controls-button, s/triaged
