### ISSUE TITLE
[iOS, 9.0 Preview 6] SkiaSharp 3.0 Preview 4.1 has a severe memory leak on iOS

### ISSUE THREAD

**Issue by janne-hmp** [dotnet/maui#23728] opened 2024-07-19 21:27 UTC
### Description

On iOS, if one opens successively many pages with bitmaps drawn with SKCanvasView, first SkiaSharp and then the whole test device (in my case, iPad 11,7) crashes in a memory leak. I tested this with the brand new SkiaSharp 3.0 Preview 4.1 and .NET MAUI 9.0 Preview 6. Other platforms work fine. Also Xamarin iOS works fine.

I made a test app based on default MAUI project through which this can be automatically tested. Just press the Click Me button, which starts opening and closing pages. Since pages are always closed after being opened, this should not cause the app to run out of memory.

In my case with an old iPad 11,7, it ran out of memory after opening and closing the same page c. 145 times.

### Steps to Reproduce

1. Download the test app at https://github.com/hyvanmielenpelit/iOSMauiSkiaSharpMemoryLeak
2. Press click me, which start's opening and closing the same page up to 500 times
3. The app crashes after it runs out of memory. My old iPad (11,7) crashed after 145th time.

### Link to public reproduction project repository

https://github.com/hyvanmielenpelit/iOSMauiSkiaSharpMemoryLeak

### Version with bug

9.0.0-preview.6.24327.7

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS17.5.1

### Did you find any workaround?

No, SkiaSharp on iOS in .NET MAUI is unusable for any serious work. You have to use Xamarin instead on iOS with SkiaSharp.

**Comment by mattleibow** [comment] 2024-07-23 22:06
Duplicate of https://github.com/mono/SkiaSharp/issues/2923

**Closed by mattleibow** 2024-07-23 22:06 UTC
Labels: t/bug, area-drawing
