### ISSUE TITLE
The Webview does not display PDF

### ISSUE THREAD

**Issue by umakant-prismhr** [dotnet/maui#26655] opened 2024-12-16 13:42 UTC
### Description

I want to open a pdf from a web resource on WebView. But the WebView does not render the pdf. On the other hand the webpages are displayed on WebView without any problem.

### Steps to Reproduce

I am using MAUI WebView but android web pages are rendering correctly but it fails to launch pdf.

But iOS is able to render pdf.

### Version with bug

8.0.100 SR10

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Affected platforms

Android

### Relevant log output

```shell

```

**Comment by PureWeen** [comment] 2024-12-16 16:40
Duplicate of #7399

**Closed by PureWeen** 2024-12-16 16:40 UTC
Labels: t/bug
