### ISSUE TITLE
Flyout button is visible for a split second when navigating back to home page in Android

### ISSUE THREAD

**Issue by cabauman** [dotnet/maui#22144] opened 2024-05-01 01:16 UTC
### Description

Flyout button is visible for a split second when navigating back to home page in Android when Flyout is disabled with `Shell.FlyoutBehavior="Disabled"`. When `Microsoft.Maui.Controls` version is 8.0.21 it shows the _flyout button_ for a split second. But when `Microsoft.Maui.Controls` version is 8.0.7 it shows the _back button_ for a split second. This happens with both emulator and device.

I tried iOS (device and emulator), and it smoothly transitions.

[maui8.0.7-android-nav.webm](https://github.com/dotnet/maui/assets/6819362/0b150160-dd55-44fd-be93-d5f388c60602)
[maui8.0.21-android-nav.webm](https://github.com/dotnet/maui/assets/6819362/e2cf8d1d-c0b6-4038-a341-b7ec41770df2)

### Steps to Reproduce

1. Create a new Maui app
2. Create a new page and register the route
3. Add a button to the main page to navigate to it , e.g. `Shell.Current.GoToAsync("page2")`
4. Start the app and navigate to the other page
5. Press the back button (either device or ui)

Expected Behavior
nav bar should smoothly transition to the home page version (title with no icon)

Actual Behavior
appears glitchy: flyout button appears for a split second before disappearing, and title jumps to fill the empty space

### Link to public reproduction project repository

https://github.com/cabauman/MauiAndroidNavBug

### Version with bug

8.0.21 SR4.1

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11 and up

### Did you find any workaround?

Haven't found a workaround so far. I tried `NavigationPage` navigation instead of Shell but same result.

**Comment by PureWeen** [comment] 2024-05-01 19:31
@cabauman does this one look like a duplicate of https://github.com/dotnet/maui/issues/18867?

**Comment by cabauman** [comment] 2024-05-02 00:32
Hi @PureWeen 👋 
Ah yes, same issue, except now it's the flyout/hamburger menu icon instead of the arrow. I searched the GitHub issues quite a while for a similar issue before creating this one, but failed to find anything because our choice of keywords was different.

**Comment by PureWeen** [comment] 2024-05-03 18:28
I'm going to close this one as a duplicate for now. 

We have this one linked so we can validate this scenario is also fixed!

**Closed by PureWeen** 2024-05-03 18:28 UTC
Labels: t/bug, platform/android 🤖, s/needs-attention
