### ISSUE TITLE
CollectionView scroll in .NET MAUI Overlaps UI when there are more data.

### ISSUE THREAD

**Issue by divyesh008** [dotnet/maui#15983] opened 2023-07-04 11:36 UTC
### Description

CollectionView control is not correctly calculating height of the items, when there are more data with longer text, the next one overlaps it.

I have tried to remove bounce and animation of CollectionView scroll using Handler like we do in Xamarin.Forms CollectionView using custom renderer:
```c#
[assembly: ExportRenderer(typeof(CollectionView), typeof(NoBounceRenderer))]
namespace CollectionViewBounceSample.iOS
{
    public class NoBounceRenderer : CollectionViewRenderer
    {
        public NoBounceRenderer() { }
        
        protected override void OnElementChanged(ElementChangedEventArgs<GroupableItemsView> e)
        {
            base.OnElementChanged(e);

            if (e.NewElement != null)
                Controller.CollectionView.Bounces = false;
        }
    }
}
```
**Reference:** https://blog.verslu.is/stackoverflow-answers/disable-bounce-collectionview-xamarin-forms/
But **Bounce** property is now available in .NET MAUI CollectionView control. 

### Check the screenshot:
<img width="495" alt="Screenshot 2023-07-04 at 4 43 39 PM" src="https://github.com/dotnet/maui/assets/10617244/82f44abb-a3b3-464c-be10-f73d485ce67f">

### Check the screens recording:

https://github.com/dotnet/maui/assets/10617244/a9005a06-d5a1-4fa4-89ed-9da89f4bc32c

### Steps to Reproduce

1. Create new .net maui app
2. Add CollectionView control to page and design UI like I have shown in the screenshot
3. Add some large data for collection view item source property
4. Run the app and Drag down the scroll quickly, it will make the scroll bounce
5. You'll be able to see the Overlapping of item in collection view 

### Link to public reproduction project repository

https://github.com/divyesh008/MauiLabel_Bug2.git

### Version with bug

7.0.49
6.0.541/6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 16.1

### Did you find any workaround?

Not yet

**Comment by ToolmakerSteve** [comment] 2023-07-04 16:55
Corresponding StackOverflow post: https://stackoverflow.com/q/76604496/199364

**Comment by divyesh008** [comment] 2023-07-05 10:33
> When there is a taller row, the next row overlaps it.
> 
> When a cell is re-used, following cells don’t have position adjusted for new height of reused cell?

@ToolmakerSteve for this I have tried to use DataTemplateSelector as well. I have created two templates one for smaller length text and other one for longer length text and used it with ItemTemplate property of CollectionView but that also not resolves Overlapping text issue.

**Comment by MichaelShapiro** [comment] 2023-08-02 13:48
Happens on iPhones too.

**Comment by sandreas** [comment] 2023-08-19 06:29
+1
Happens on Windows Systems (Windows 11) - Window Resizing 1px seems to rearrange stuff to "fix" the layout. I'll post screenshots after the OK of my company. I'm not sure that there is a `triggerRerender` or something better, window resizing is a VERY dirty hack... but it works in my case.

```c#
// WindowPositioner is a custom class... I can't post the code, but you should get the point
// increase width 1px
// after 500ms decrease width again 1px
WindowPositioner.Resize(App.AppWindow, 1, 0);
await Task.Delay(500).ContinueWith((_) =>
{
    WindowPositioner.Resize(App.AppWindow, -1, 0);
});
```

**Comment by shyn** [comment] 2023-10-30 07:21
Same here. iOS 16 with iPhone 14 Pro simulator.

```commandline
❯ dotnet workload list         
-------------------------------------------------------------------
maui-ios         8.0.0-rc.2.9373/8.0.100-rc.2      SDK 8.0.100-rc.2
maui             8.0.0-rc.2.9373/8.0.100-rc.2      SDK 8.0.100-rc.2
```

**Comment by XamlTest** [comment] 2023-11-27 10:03
Verified this on Visual Studio Enterprise 17.9.0 Preview 1(8.0.3). Repro on iPad Pro, not repro on iOS 17.0 with below Project:
[poc_maui.zip](https://github.com/dotnet/maui/files/13472728/poc_maui.zip)

**Comment by shyn** [comment] 2023-11-28 02:24
@XamlTest I tried your test project on iOS 17 in simulator. reproed with `\n` or `\r\n` in the label text and a little long list. Seems like the bug is related to `\n`?
![image](https://github.com/dotnet/maui/assets/899449/8c0582ab-7e72-4a7b-9cc0-2f0fef2a5d65)

**Comment by XamlTest** [comment] 2023-12-18 03:04
@shyn I only can confirm this issue still repro on the latest version, the root cause maybe needs to wait a further investigation by engineers.

**Comment by shyn** [comment] 2023-12-18 04:47
@XamlTest Thank you for your attention! Maybe we should open a new issue, this issue is really critical and has caused us to delay the development of the MAUI client.

**Comment by divyesh008** [comment] 2023-12-18 05:20
> @XamlTest Thank you for your attention! Maybe we should open a new issue, this issue is really critical and has caused us to delay the development of the MAUI client.
Not getting your point, the issue is the same so why do we need to open a new issue?

**Comment by shyn** [comment] 2023-12-18 08:00
@divyesh008 Since the title of _Happens only in iPad device_ is not very accurate, maybe modify the title. It's a common issue not only on iPad.

**Comment by XamlTest** [comment] 2023-12-19 02:12
@shyn You can update the Title and Affected Platforms in the original report or add additional information in comments.

**Comment by divyesh008** [comment] 2024-01-22 08:33
This still not resolved in .Net8, I'm still facing the same bug. Any updates on this?

**Comment by shyn** [comment] 2024-01-24 01:44
I will not going to try MAUI until this bug resolved.

**Comment by divyesh008** [comment] 2024-01-25 11:41
> I will not going to try MAUI until this bug resolved.

You can use Bindable StackLayout with scrollview as workaround. I have did the same.

**Comment by shyn** [comment] 2024-01-31 00:53
@divyesh008 thanks for the information. I will try it to see the performance. Since no virtualization for Bindable StackLayout after all.

**Comment by evgenyKozlov1996** [comment] 2024-04-30 18:44
The same issue on the latest version and no any comment from Microsoft developers...

**Comment by divyesh008** [comment] 2024-05-20 03:40
Seems like this got resolved.

**Comment by PureWeen** [comment] 2024-10-01 18:25
Closing this based on @divyesh008 confirming this has been fixed

**Closed by PureWeen** 2024-10-01 18:25 UTC
Labels: t/bug, platform/iOS 🍎, area-controls-collectionview
