### ISSUE TITLE
[regression/8.0.0-preview.1.7762] [WinUI] An exception is thrown after removing an item from its close button

### ISSUE THREAD

**Issue by marchev-prgs** [dotnet/maui#16324] opened 2023-07-24 16:07 UTC
### Description

I get the exception with 8.0.0-preview.6.8686, which I don't see listed in the versions list below)

An exception is thrown when an item is removed by clicking a close-button inside the item.
I have a simple item template, just a label and a close-button:

        <DataTemplate x:Key="t1">
            <HorizontalStackLayout>
                <Label Text="{Binding}" Margin="0, 0, 10, 0" />
                <Button Text="X" Clicked="ButtonClose_Clicked" />
            </HorizontalStackLayout>
        </DataTemplate>

When I click the close button an exception is thrown: 
Message: Child collection must not be modified during measure or arrange.

Interestingly, the stack trace is null.

![cv_exc2_app](https://github.com/dotnet/maui/assets/91615935/67951b8b-56c4-48d1-8bfe-2823cfa4639d)

![cv_exc2_exc](https://github.com/dotnet/maui/assets/91615935/0fd72f6e-b470-4b29-bbab-9199e19a68d3)
ee-455020fde0ca)

### Steps to Reproduce

1. Get the repo from the link
2. Go to folder \Maui\CollectionViewThrowsExceptionWhenClosingAnItem
3. Run the app in WinUI
4. Click the X button (the close button of the item in the CollectionVew)

Expected: The item should be removed and the CollectionView should become empty.
Actual: An exception is thrown.

### Link to public reproduction project repository

https://github.com/telerik/ms-samples/tree/main/Maui/CollectionViewThrowsExceptionWhenClosingAnItem

### Version with bug

[8.0.0-preview.1.7762](https://github.com/dotnet/maui/releases/tag/8.0.0-preview.1.7762)

### Last version that worked well

7.0.92

### Affected platforms

Windows

### Did you find any workaround?

https://github.com/dotnet/maui/issues/16324#issuecomment-1758406716

### Depends on 

- [x] https://github.com/microsoft/microsoft-ui-xaml/issues/6350

> VS bug [#1900743](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1900743)

**Comment by XamlTest** [comment] 2023-08-10 08:47
Verified this on Visual Studio Enterprise 17.8.0 Preview 1.0. This issue does not repro on Windows 11(8.0.100-preview.6.23330.14), Android 13.0-API33 and iOS 16.4 with below Project:

[CollectionViewThrowsExc2.zip](https://github.com/dotnet/maui/files/12310776/CollectionViewThrowsExc2.zip)

**Comment by marchev-prgs** [comment] 2023-08-11 15:26
I figured I can give you what I see in the Call Stack window of VS. I doubt it's of much use, but I guess it wouldn't hurt:

>	CollectionViewThrowsExc2.dll!CollectionViewThrowsExc2.WinUI.App.InitializeComponent.AnonymousMethod__3_1(object sender, Microsoft.UI.Xaml.UnhandledExceptionEventArgs e) Line 67	C#
 	Microsoft.WinUI.dll!WinRT._EventSource_global__Microsoft_UI_Xaml_UnhandledExceptionEventHandler.EventState.GetEventInvoke.AnonymousMethod__1_0(object sender, Microsoft.UI.Xaml.UnhandledExceptionEventArgs e)	Unknown
 	Microsoft.WinUI.dll!ABI.Microsoft.UI.Xaml.UnhandledExceptionEventHandler.Do_Abi_Invoke(nint thisPtr, nint sender, nint e)	Unknown
 	[Native to Managed Transition]	
 	[Managed to Native Transition]	
 	Microsoft.WinUI.dll!ABI.Microsoft.UI.Xaml.Controls.IItemsControlOverridesMethods.OnItemsChanged(WinRT.IObjectReference _obj, object e)	Unknown
 	Microsoft.WinUI.dll!Microsoft.UI.Xaml.Controls.ItemsControl.OnItemsChanged(object e)	Unknown
 	Microsoft.WinUI.dll!Microsoft.UI.Xaml.Controls.ItemsControl.Microsoft.UI.Xaml.Controls.IItemsControlOverrides.OnItemsChanged(object e)	Unknown
 	Microsoft.WinUI.dll!ABI.Microsoft.UI.Xaml.Controls.IItemsControlOverrides.Do_Abi_OnItemsChanged_4(nint thisPtr, nint e)	Unknown
 	[Native to Managed Transition]	
 	[Managed to Native Transition]	
 	WinRT.Runtime.dll!ABI.System.Collections.Specialized.NotifyCollectionChangedEventHandler.NativeDelegateWrapper.Invoke(object sender, System.Collections.Specialized.NotifyCollectionChangedEventArgs e)	Unknown
 	System.ObjectModel.dll!System.Collections.ObjectModel.ObservableCollection<Microsoft.Maui.Controls.Platform.ItemTemplateContext>.OnCollectionChanged(System.Collections.Specialized.NotifyCollectionChangedEventArgs e)	Unknown
 	Microsoft.Maui.Controls.dll!Microsoft.Maui.Controls.Platform.ObservableItemTemplateCollection.Remove(System.Collections.Specialized.NotifyCollectionChangedEventArgs args)	Unknown
 	Microsoft.Maui.Controls.dll!Microsoft.Maui.Controls.Platform.ObservableItemTemplateCollection.InnerCollectionChanged(System.Collections.Specialized.NotifyCollectionChangedEventArgs args)	Unknown
 	Microsoft.Maui.Controls.dll!Microsoft.Maui.Controls.Platform.ObservableItemTemplateCollection.InnerCollectionChanged.AnonymousMethod__0()	Unknown
 	Microsoft.Maui.Controls.dll!Microsoft.Maui.Controls.DispatcherExtensions.DispatchIfRequired(Microsoft.Maui.Dispatching.IDispatcher dispatcher, System.Action action)	Unknown
 	Microsoft.Maui.Controls.dll!Microsoft.Maui.Controls.Platform.ObservableItemTemplateCollection.InnerCollectionChanged(object sender, System.Collections.Specialized.NotifyCollectionChangedEventArgs args)	Unknown
 	System.ObjectModel.dll!System.Collections.ObjectModel.ObservableCollection<string>.OnCollectionChanged(System.Collections.Specialized.NotifyCollectionChangedEventArgs e)	Unknown
 	System.Private.CoreLib.dll!System.Collections.ObjectModel.Collection<string>.Remove(string item)	Unknown
 	CollectionViewThrowsExc2.dll!CollectionViewThrowsExc2.MainPage.ButtonClose_Clicked(object sender, System.EventArgs e) Line 21	C#
 	Microsoft.Maui.Controls.dll!Microsoft.Maui.Controls.Button.Microsoft.Maui.Controls.Internals.IButtonElement.PropagateUpClicked()	Unknown
 	Microsoft.Maui.Controls.dll!Microsoft.Maui.Controls.ButtonElement.ElementClicked(Microsoft.Maui.Controls.VisualElement visualElement, Microsoft.Maui.Controls.Internals.IButtonElement ButtonElementManager)	Unknown
 	Microsoft.Maui.Controls.dll!Microsoft.Maui.Controls.Button.SendClicked()	Unknown
 	Microsoft.Maui.Controls.dll!Microsoft.Maui.Controls.Button.Microsoft.Maui.IButton.Clicked()	Unknown
 	Microsoft.Maui.dll!Microsoft.Maui.Handlers.ButtonHandler.OnClick(object sender, Microsoft.UI.Xaml.RoutedEventArgs e)	Unknown
 	Microsoft.WinUI.dll!WinRT._EventSource_global__Microsoft_UI_Xaml_RoutedEventHandler.EventState.GetEventInvoke.AnonymousMethod__1_0(object sender, Microsoft.UI.Xaml.RoutedEventArgs e)	Unknown
 	Microsoft.WinUI.dll!ABI.Microsoft.UI.Xaml.RoutedEventHandler.Do_Abi_Invoke(nint thisPtr, nint sender, nint e)	Unknown
 	[Native to Managed Transition]	
 	[Managed to Native Transition]	
 	Microsoft.WinUI.dll!ABI.Microsoft.UI.Xaml.Controls.IControlOverridesMethods.OnPointerReleased(WinRT.IObjectReference _obj, Microsoft.UI.Xaml.Input.PointerRoutedEventArgs e)	Unknown
 	Microsoft.WinUI.dll!Microsoft.UI.Xaml.Controls.Control.OnPointerReleased(Microsoft.UI.Xaml.Input.PointerRoutedEventArgs e)	Unknown
 	Microsoft.WinUI.dll!Microsoft.UI.Xaml.Controls.Control.Microsoft.UI.Xaml.Controls.IControlOverrides.OnPointerReleased(Microsoft.UI.Xaml.Input.PointerRoutedEventArgs e)	Unknown
 	Microsoft.WinUI.dll!ABI.Microsoft.UI.Xaml.Controls.IControlOverrides.Do_Abi_OnPointerReleased_3(nint thisPtr, nint e)	Unknown
 	[Native to Managed Transition]	
 	[Managed to Native Transition]	
 	Microsoft.WinUI.dll!ABI.Microsoft.UI.Xaml.IApplicationStaticsMethods.Start(WinRT.IObjectReference _obj, Microsoft.UI.Xaml.ApplicationInitializationCallback callback)	Unknown
 	Microsoft.WinUI.dll!Microsoft.UI.Xaml.Application.Start(Microsoft.UI.Xaml.ApplicationInitializationCallback callback)	Unknown
 	CollectionViewThrowsExc2.dll!CollectionViewThrowsExc2.WinUI.Program.Main(string[] args) Line 31	C#

**Comment by mauroa** [comment] 2023-09-06 19:58
The root cause of the bug looks directly related to WinUI core issues with observable collections and collection views (ListView in this case). Bret already linked an existing and related bug in WinUI. I'll try to file a new one specific to this issue and attach a repro solution.

**Comment by samhouts** [comment] 2023-09-08 00:18
Confirmed that this regressed between https://github.com/dotnet/maui/compare/7.0.92...8.0.0-preview.1.7762. https://github.com/dotnet/maui/pull/10999 and https://github.com/dotnet/maui/pull/13146 seem sus, but it could be one of the memory leaks fixes on bindings, too, perhaps?

**Comment by jsuarezruiz** [comment] 2023-09-18 07:03
Cannot reproduce the issue with Windows 10:
![issue-16324](https://github.com/dotnet/maui/assets/6755973/75fefc7e-87be-4cd4-b3d8-6b2e94cf5fd0)
Probably related with latests WinUI versions, will check with Windows 11.

**Comment by emaf** [comment] 2023-10-11 19:35
Unfortunatly this is an issue on WinUI: https://github.com/microsoft/microsoft-ui-xaml/issues/6350. 

We are working with the WinUI team to get this fixed, and as a workaround you can release the button's pointer capture before removing the item from the list. 

For example, the sample code linked on this issue would look like:
```
		private void ButtonClose_Clicked(object sender, EventArgs e)
		{
			Button button = (Button)sender;

#if WINDOWS
			((Microsoft.UI.Xaml.Controls.Button)button.Handler.PlatformView).ReleasePointerCaptures();
#endif

			string item = (string)button.BindingContext;
			this.items.Remove(item);
		}
```

**Comment by PureWeen** [comment] 2023-11-03 21:25
I'm going to backlog this issue for now. We're going to wait for this to be resolved by WinUI

**Comment by busitech** [comment] 2024-04-17 22:38
https://github.com/microsoft/microsoft-ui-xaml/issues/8684

**Closed** 2024-05-11 02:32 UTC
Labels: t/bug, platform/windows 🪟, partner, partner/winui, area-controls-collectionview, blocked, high, s/triaged, external, s/try-latest-version
