### ISSUE TITLE
.Net Maui Preferences.Get Returns Null instead of defaultValue on Windows Machine

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#9499] opened 2022-08-17 17:54 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Net-Maui-PreferencesGet-Returns-Null-i/10114078)._

---
[severity:I'm unable to use this version]
Microsoft Visual Studio Community 2022 (64-bit) - Preview
Version 17.3.0 Preview 6.0
Reproduce: Use the Standard Maui Template, NO Preferences previously set
break anywhere , in watch simply type Preferences.Get("NewKey","TestString");
Expected Result: **TestString**, Actual Result - **null**

This occurs on Windows, Works on Android not tested elsewhere.

It does work on Windows if the key is Set first, but, that defeats the whole value of Get with a defaultValue.

---
#### Feedback Bot on 8/9/2022, 01:15 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by haakonfp** [comment] 2022-08-17 22:40
The problem was introduced with https://github.com/dotnet/maui/commit/8bbb7cb9f0f12e9c0899193a9cc220e7a4d48afb. This issue is a duplicate of https://github.com/dotnet/maui/issues/9210 and https://github.com/dotnet/maui/issues/9338, and fixed with https://github.com/dotnet/maui/pull/9361.

**Closed** 2022-08-18 18:25 UTC
