### ISSUE TITLE
I don't see the curly bars in the status bar

### ISSUE THREAD

**Issue by Gonzaloogm** [dotnet/maui#25594] opened 2024-10-30 09:48 UTC
Problem encountered on https://dotnet.microsoft.com/es-es/learn/maui/first-app-tutorial/run
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I don't see the curly bars in the status bar ("{}"), I trued to follow the steps how the information bellow says but when I try to write the commando .NET MAUI : pick it doen't work, It doesn't even show the command.

**Comment by Gonzaloogm** [comment] 2024-10-30 09:50
The curly bars "{}" do appear in the .cs files but when I click on them, they show this: MauiApp1 (net8.0-ios) - Active file context, and I can't pick a debug plataform.

**Comment by Gonzaloogm** [comment] 2024-10-30 09:53
![Image](https://github.com/user-attachments/assets/3e75be08-c379-4877-a80f-9f32d65b7b8d)

**Comment by jfversluis** [comment] 2024-10-30 09:59
Duplicate of #25566

**Closed by jfversluis** 2024-10-30 09:59 UTC

**Comment by Gonzaloogm** [comment] 2024-10-30 10:29
Thank you for the help, I can't find the Editor language Status in the status bar, It doen't appear and the same for the second one

**Comment by Gonzaloogm** [comment] 2024-10-30 10:30
How do I install these: code --profile ".NET MAUI"
code --install-extension ms-dotnettools.csharp --profile ".NET MAUI" 
code --install-extension ms-dotnettools.csdevkit --profile ".NET MAUI" 
code --install-extension ms-dotnettools.dotnet-maui --profile ".NET MAUI" 
I am in a macOS

**Comment by Gonzaloogm** [comment] 2024-10-30 14:55
It doesn't work, it doesn't recognise the commands

**Comment by Gonzaloogm** [comment] 2024-10-30 15:00
I did install them correctly but it remains the same, nothing has changed
