### ISSUE TITLE
There was a problem that the Entry SoftKeyboard of Collectionview could not be hidden. (Android only)

### ISSUE THREAD

**Issue by pulmuone** [dotnet/maui#16691] opened 2023-08-11 06:21 UTC
### Description

There was a problem that the Entry SoftKeyboard of Collectionview could not be hidden. (Android only)
SoftKeyboard does not hide and does not become UnFocus in the previous activation.
With the same source, no problem occurred in XF.

Xamarin.Forms(Android) CollecitonView Entry(SoftKeyboard)
https://github.com/dotnet/maui/assets/42885949/9eb67964-c147-452f-9cf0-532f2ca5fe64

Maui(net7) Android CollectionView Entry (SoftKeyboard)
https://github.com/dotnet/maui/assets/42885949/c7849ade-a76d-4e27-92f9-ea9d0bd8ae01

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.92

### Affected platforms

Android

**Comment by mattleibow** [comment] 2023-08-11 14:11
This will be fixed by https://github.com/dotnet/maui/pull/16530

**Comment by mattleibow** [comment] 2023-08-11 14:12
Duplicate of https://github.com/dotnet/maui/issues/12002

**Closed by mattleibow** 2023-08-11 14:12 UTC
Labels: t/bug, platform/android 🤖, area/controls 🎮, control-entry, area/keyboard
