### ISSUE TITLE
error 0x80070005

### ISSUE THREAD

**Issue by AP2020C** [dotnet/maui#12666] opened 2023-01-14 13:56 UTC
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/run
Operating System: windows

I have enabled developer mode but still nothing happens when I press the Windows machine button.
I get the error The program '[14532] My first app Maui.exe' is terminated with code 2147942405 (0x80070005).
I have already read https://stackoverflow.com/questions/74557071/c-sharp-maui-registration-of-the-app-failed-error-0x80070005 which led me to https://www.thewindowsclub.com/error-0x80070005-updating-windows-store-apps but the guide does not match my screen. I also find it wrong that one has to follow such a convoluted procedure.

**Comment by idexus** [comment] 2023-01-14 14:27
Try to install SDK [https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/downloads#windows-app-sdk-12](https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/downloads#windows-app-sdk-12)

**Comment by AP2020C** [comment] 2023-01-15 15:06
I downloaded 1.2.2 (1.2.221209.1) "C# Visual Studio 2022 extension".
Result was:
☻ Windows App SDK C# VS2022 Templates: Failed
☻ Single-Project MSIX Packaging Tools for VS 2022: OK

Restart PC
Same error

**Comment by idexus** [comment] 2023-01-15 15:45
Runtime Installer (x64) helped me, I had the same error

**Comment by jsuarezruiz** [comment] 2023-01-16 15:15
Seems to be similar to https://github.com/dotnet/maui/issues/12080
Could you try this workaround? https://github.com/dotnet/maui/issues/12080#issuecomment-1377243186

**Comment by mattleibow** [comment] 2023-01-16 15:32
Duplicate of https://github.com/dotnet/maui/issues/12080

**Closed by mattleibow** 2023-01-16 15:32 UTC
Labels: s/duplicate 2️⃣, s/needs-info, area/setup 🪄

**Comment by AP2020C** [comment] 2023-01-17 14:41
I don't understand.
VS does not show the csproj file. I tried to open it with N++ but there is no line WindowsAppSdkDeploymentManagerInitialize.

**Comment by bfmyr4** [comment] 2023-01-17 20:53
I have this same problem, neither installing SDK 1.2.2 nor adding WindowsAppSdkDeploymentManagerInitialize to the csproj fixes this.

**Comment by mattleibow** [comment] 2023-01-19 08:22
@bfmyr4 you may have a different issue. Can you open a new issue and fill out the issue template so we can have a look.

**Comment by bfmyr4** [comment] 2023-01-19 13:51
Turns out that I had some sort of windows permission issues.
