### ISSUE TITLE
iOS Scrolling is super laggy

### ISSUE THREAD

**Issue by ssbssb-cmd** [dotnet/maui#25753] opened 2024-11-08 15:42 UTC
### Description

Hello, i have recently upgraded .net as per table below. I am finding that the scrolling a collection view has become painfully slow to the point that it can't be released to prod. Previously, at least when i compiled in Release Mode, the performance was sufficient - but now it is way to slow. Surprisingly, Android is working OK, but iOS is not. 

Any ideas of what i can do to investigate? 

Workload version: 8.0.403.1

maui-ios: SDK 8.0.400
maui-android: SDK 8.0.400
maui SDK 8.0.400

xcode - 16.1

Microsoft.Maui.Controls and Essentials is 8.0.93
CommunityToolkit is on 9.1.1

.net8.0, c#12

In the Release config, this is what i have, is anything missing from that or should be added to speed up performance?

`
    
    <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net8.0-ios|AnyCPU'">
	
		<CreatePackage>false</CreatePackage>

		<EnableAOT>true</EnableAOT>

    </PropertyGroup>
`

### Version with bug

8.0.40 SR5

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms, Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Relevant log output

```shell

```

**Comment by jfversluis** [comment] 2024-11-08 17:00
Duplicate of #25369

**Closed by jfversluis** 2024-11-08 17:00 UTC
Labels: t/bug

**Comment by PureWeen** [comment] 2024-11-12 17:16
@ssbssb-cmd 

https://github.com/dotnet/maui/issues/25369#issuecomment-2469981876
