### ISSUE TITLE
[iOS] MediaPicker.Default.CapturePhotoAsync() returns PNG in which the picture's Orientation Data is lost and difficult to obtain

### ISSUE THREAD

**Issue by Vpatel541** [dotnet/maui#11379] opened 2022-11-15 15:04 UTC
### Description

On iOS (Iphone), when using MediaPicker.Default.CapturePhotoAsync() to capture the photo and display it on the screen, the photo is in the incorrect orientation and defaulted to whatever the default orientation iOS has. Since the file is a PNG, the exif data does not contain orientation so it is difficult to solve the problem without having to change the Media Picker itself. 

### Steps to Reproduce

1. Create new .NET MAUI project. 
2. Add empty Image in the XAML with a variable name set
3. Also add a media picker to take a photo
4. In the backend C# for the page, use MediaPicker.Default.CapturePhotoAsync() to display the image on the screen, this is for iOS
5. See that the orientation is wrong and since the file comes as a PNG, unable to determine orientation to display image correctly 

### Link to public reproduction project repository

none

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15 and greater

### Did you find any workaround?

None

**Comment by hector2d2** [comment] 2022-11-15 18:20
i have the same error, and the best thing was to change the library, I used the xam.plugin.media library

**Comment by samhouts** [comment] 2023-04-10 15:57
Duplicate of #9535

**Closed by samhouts** 2023-04-10 15:57 UTC
Labels: t/bug, area/essentials 🍞
