### ISSUE TITLE
[regression/7.0.81] label created dynamically in code doesn't stretch like it should

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#14588] opened 2023-04-14 15:36 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/label-created-dynamicaly-in-code-doesnt/10337821)._

---
[regression] [worked-in:17.5.3]
I am doing an app for android using .NET MAUI.  Everything was fine until I updated VisualStudio to version 17.5.4.
My app populate the screen with a bunch of collectionview to display data, the number of collectionview depend on the number of item in a list, so I have to do it dynamically in code.
Here is my code to set the collectionview and its DataTemplate.  When I was using VisualStudio 17.5.3, the Label in the DataTemplate was stretching to the size of the collectionview and with its property TextAlignment set to center, the text was appearing in the center of the collectionview.
```
                CollectionView leveeAskedCollectionView = new CollectionView();
                string bindPath = nameof(Joueurs) + $"[{i}].LeveeAsked";
                leveeAskedCollectionView.Background = Colors.Orange;
                leveeAskedCollectionView.SetBinding(ItemsView.ItemsSourceProperty, bindPath);
                leveeAskedCollectionView.ItemTemplate = new DataTemplate(() =>
                {
                    Label leveeAskedLabel = new Label();
                    leveeAskedLabel.Background = Brush.Red;
                    leveeAskedLabel.HorizontalTextAlignment = TextAlignment.Center;
                    leveeAskedLabel.SetBinding(Label.TextProperty, ".");
                    Grid.SetColumn(leveeAskedLabel, 0);
                    return leveeAskedLabel;
                });
```
Now since 17.5.4, this exact same code doesn't stretch the label anymore, it makes it the same size of the text and the text is always on the left side of the collectionview now.  the property textalignment doesn't do anything now since the label's width is the same as the text it contain.  I tried to set a collectionview with a label in its datatemplate in XAML and it works fine, the label stretch to the size of the collectionview.  So it looks like it is only a problem when adding the control in code dynamically.
I attached a screen shot of the result.  The orange part is the collectionview's background and the label containing only the text "0" has a red background.  You can see that the label doesn't stretch like it did before.

Thank you.

---
#### Feedback Bot on 4/12/2023, 11:04 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by Sebastian1989101** [comment] 2023-04-15 11:14
+1 this... [M]ulti-Platform [A]pp [U]ser [I]ssues continues to grow

**Comment by samhouts** [comment] 2023-04-17 17:36
Suspect this is a duplicate of #14537

**Comment by Phil11111** [comment] 2023-04-24 19:13
Hello, I'm the one who posted that feedback.  What do you need?

**Comment by Phil11111** [comment] 2023-04-30 03:27
Here is some pictures of the issue and what it should be.  I put some backgrounds colors so we can see.  The orange part is the CollectionView and the red part is the Label in the datatemplate of the CollectionView.
Those 2 images is what happen with the same code above but in different version of visual studio.

Visual Studio V17.5.4.  This is the bug.  See how it doesn't strech to the size of the CollectionView and stick to the left side.
![collectionview_label 17 5 4](https://user-images.githubusercontent.com/131709652/235333925-cc89e4ba-0ac9-470d-8682-f35e49afe3f0.png)

Visual Studio V17.5.3.  Works fine, strech like it should.
![collectionview_label 17 5 3](https://user-images.githubusercontent.com/131709652/235333967-08763fb6-2fb6-44c2-bd63-b6c589c0402f.png)

**Comment by hartez** [comment] 2023-05-03 22:43
@Phil11111 In order to know if it's the same bug as #14537, we would need to know what your Grid code/markup looks like. (I'm assuming there's a Grid involved because your `DataTemplate` includes `Grid.SetColumn(leveeAskedLabel, 0);`.)

**Comment by Phil11111** [comment] 2023-05-03 23:09
> @Phil11111 In order to know if it's the same bug as #14537, we would need to know what your Grid code/markup looks like. (I'm assuming there's a Grid involved because your `DataTemplate` includes `Grid.SetColumn(leveeAskedLabel, 0);`.)

Yes, you are right, the collection views are within a Grid.
By markup I assume you mean the XAML code...
Here is my complete XAML.  The grid in question is the Grid at the complete end of the "main" Grid.
That Grid: <Grid x:Name="GameScoreDisplayGrid" Grid.Column="1"/>

Basically it is an empty Grid at first that I pass as a command parameter for a command, I then populate the Gris in code when the command is fired.

`<Grid>
        <Grid.ColumnDefinitions>
            <ColumnDefinition Width="255"/>
            <ColumnDefinition Width="*"/>
        </Grid.ColumnDefinitions>


        <Grid Grid.Column="0">
            <Grid.RowDefinitions>
                <RowDefinition Height="*"/>
                <RowDefinition Height="Auto"/>
            </Grid.RowDefinitions>
        
            <VerticalStackLayout Grid.Row="0">

                <Grid IsVisible="{Binding isGameStarted, Converter={StaticResource InvertedBoolConverter}}">
                    <Grid.RowDefinitions>
                        <RowDefinition Height="Auto"/>
                        <RowDefinition Height="Auto"/>
                        <RowDefinition Height="Auto"/>
                    </Grid.RowDefinitions>

                    <Grid Margin="0,5" Grid.Row="0">
                        <Grid.RowDefinitions>
                            <RowDefinition Height="Auto"/>
                            <RowDefinition Height="Auto"/>
                        </Grid.RowDefinitions>
                        <Grid.ColumnDefinitions>
                            <ColumnDefinition Width="*"/>
                            <ColumnDefinition Width="Auto"/>
                        </Grid.ColumnDefinitions>
                        <Label Text="{Binding CardsRequired}" Grid.Row="0" Grid.Column="0" Grid.ColumnSpan="2"/>
                        <Entry Text="{Binding Name}" Placeholder="Nom de joueur" Grid.Column="0" Grid.Row="1"/>
                        <Button Text="Ajout Joueur" Command="{Binding AddPlayerCommand}" Grid.Column="1" Grid.Row="1"/>
                    </Grid>

                    <CollectionView ItemsSource="{Binding Joueurs}" Grid.Row="1">
                        <CollectionView.ItemTemplate>
                            <DataTemplate>
                                <SwipeView>
                                    <SwipeView.RightItems>
                                        <SwipeItems>
                                            <SwipeItem Text="Supprime" BackgroundColor="red"
                                                   Command="{Binding Source={RelativeSource AncestorType={x:Type viewmodels:MainPageViewModel}}, Path=DeletePlayerCommand}"
                                                   CommandParameter="{Binding .}"/>
                                        </SwipeItems>
                                    </SwipeView.RightItems>
                                    <SwipeView.LeftItems>
                                        <SwipeItems>
                                            <SwipeItem Text="Modifie" BackgroundColor="Blue"
                                                   Command="{Binding Source={RelativeSource AncestorType={x:Type viewmodels:MainPageViewModel}}, Path=ModifyPlayerCommand}"
                                                   CommandParameter="{Binding .}"/>
                                        </SwipeItems>
                                    </SwipeView.LeftItems>
                                    <Grid Margin="0,1">
                                        <Border>
                                            <Border.StrokeShape>
                                                <RoundRectangle CornerRadius="10" />
                                            </Border.StrokeShape>
                                            <Label Text="{Binding Name}" Margin="5, 10"/>
                                        </Border>
                                    </Grid>

                                </SwipeView>
                            </DataTemplate>
                        </CollectionView.ItemTemplate>
                    </CollectionView>

                    <Button Text="Commencer la partie" Command="{Binding StartGameCommand}" CommandParameter="{Binding Source={x:Reference GameScoreDisplayGrid}}" Grid.Row="2" Margin="0,10,0,0"/>
                </Grid>
               

                <Button Text="Ronde Finie" Command="{Binding RoundFinishedCommand}">
                    <Button.IsVisible>
                        <MultiBinding Converter="{StaticResource BooleanAndConverter}">
                            <Binding Path="isGameStarted"/>
                            <Binding Path="isPlayersPlaying"/>
                            <Binding Path="isPlayersEnteringLevee" Converter="{StaticResource InvertedBoolConverter}"/>
                        </MultiBinding>
                    </Button.IsVisible>
                </Button>

                <Button Text="Passer à la ronde suivante" Command="{Binding NextRoundCommand}">
                    <Button.IsVisible>
                        <MultiBinding Converter="{StaticResource BooleanAndConverter}">
                            <Binding Path="isGameStarted"/>
                            <Binding Path="isPlayersPlaying" Converter="{StaticResource InvertedBoolConverter}"/>
                            <Binding Path="isPlayersChoosingLevee" Converter="{StaticResource InvertedBoolConverter}"/>
                            <Binding Path="isPlayersEnteringLevee" Converter="{StaticResource InvertedBoolConverter}"/>
                        </MultiBinding>
                    </Button.IsVisible>
                </Button>

                <Grid>
                    <Grid.IsVisible>
                        <MultiBinding Converter="{StaticResource BooleanOrConverter}">
                            <Binding Path="isPlayersChoosingLevee"/>
                            <Binding Path="isPlayersEnteringLevee"/>
                        </MultiBinding>
                    </Grid.IsVisible>


                    <Grid.RowDefinitions>
                        <RowDefinition Height="Auto"/>
                        <RowDefinition Height="Auto"/>
                    </Grid.RowDefinitions>

                    <Label Text="{Binding UserInputMessage}" Grid.Row="0"/>

                    <CollectionView ItemsLayout="VerticalGrid, 4" ItemsSource="{Binding ButtonChoices}" IsVisible="{Binding isPlayersChoosingLevee}" Grid.Row="1">
                        <CollectionView.ItemTemplate>
                            <DataTemplate>
                                <Button Text="{Binding .}" Margin="1" Command="{Binding Source={RelativeSource AncestorType={x:Type viewmodels:MainPageViewModel}}, Path=InputAskedLeveeCommand}" CommandParameter="{Binding .}"/>
                            </DataTemplate>
                        </CollectionView.ItemTemplate>
                    </CollectionView>

                    <CollectionView ItemsLayout="VerticalGrid, 4" ItemsSource="{Binding ButtonChoices}" IsVisible="{Binding isPlayersEnteringLevee}" Grid.Row="1">
                        <CollectionView.ItemTemplate>
                            <DataTemplate>
                                <Button Text="{Binding .}" Margin="1" Command="{Binding Source={RelativeSource AncestorType={x:Type viewmodels:MainPageViewModel}}, Path=InputDoneLeveeCommand}" CommandParameter="{Binding .}"/>
                            </DataTemplate>
                        </CollectionView.ItemTemplate>
                    </CollectionView>
                </Grid>
                
                
                
                
                
                
            </VerticalStackLayout>



            <StackLayout Grid.Row="2">
                <Button Text="Aide" Command="{Binding HelpCommand}"/>
                
                <Button Text="Quitter" Command="{Binding QuitAppCommand}" Margin="0,20,0,0"/>
            </StackLayout>
            
        </Grid>

        
        <Grid x:Name="GameScoreDisplayGrid" Grid.Column="1"/>

    </Grid>`

**Closed** 2023-08-13 13:01 UTC
Labels: t/bug, area/layout 🔲, s/needs-attention, i/regression, s/try-latest-version, layout-grid
