### ISSUE TITLE
[regression/8.0.0-rc.1.9171] [MAUI] The App crashes after pulling up and then pulling down the RefreshView C6 page

### ISSUE THREAD

**Issue by QianaJiao** [dotnet/maui#17391] opened 2023-09-15 07:03 UTC
### Description

[MAUI] The App crashes after pulling down and then pulling up the RefreshView C6 page
Note: This bug not repro on iOS target. 

### Steps to Reproduce

1.Deploy https://devdiv.visualstudio.com/Pkgs/_git/VS.TestAssets.Xaml?path=/Assets/Projects/ManualMauiTests to Windows.
2.Click or tap on category 'C' for 'RefreshView'.
3.Click or tap on test 'C6'.
4. Pull up and pull down the page to initiate a refresh.

**Result: App crash** 
![C6](https://github.com/dotnet/maui/assets/91244512/156d8806-1e5f-45f3-b3ae-c404e68b31cf)

### Link to public reproduction project repository

https://devdiv.visualstudio.com/Pkgs/_git/VS.TestAssets.Xaml?path=/Assets/Projects/ManualMauiTests

### Version with bug

[8.0.0-rc.1.9171](https://github.com/dotnet/maui/releases/tag/8.0.0-rc.1.9171)

### Is this a regression from previous behavior?

Yes, this used to work in MAUI

### Last known working version

[8.0.0-preview.7.8842](https://github.com/dotnet/maui/releases/tag/8.0.0-preview.7.8842)

### Affected platforms

Android

### Affected platform versions

Android API33

**Comment by samhouts** [comment] 2023-09-15 21:41
`System.ArgumentException: 'An item with the same key has already been added. Key: Microsoft.Maui.Controls.SetterSpecificity (Parameter 'key')'`

Confirmed regression between [8.0.0-preview.7.8842](https://github.com/dotnet/maui/releases/tag/8.0.0-preview.7.8842) and [8.0.0-rc.1.9171](https://github.com/dotnet/maui/releases/tag/8.0.0-rc.1.9171).

Probably happening now because of https://github.com/dotnet/maui/pull/17062, but I suspect this is actually part of https://github.com/dotnet/maui/issues/11082. Probably already resolved by https://github.com/dotnet/maui/pull/17365.

**Comment by StephaneDelcroix** [comment] 2023-09-19 09:20
looking at the stack trace, it's probably fixed by https://github.com/dotnet/maui/pull/17365

**Comment by mattleibow** [comment] 2023-10-04 21:46
This is happening in RC 2, but I see the PR is only in main...

**Comment by mattleibow** [comment] 2023-10-04 21:51
I see it was merged to net8.0 and is in the RC 2 builds: https://github.com/dotnet/maui/commit/77f0def7508dba25e659f3130d54f14c445d90e7

But, it is crashing still:


```
 	0xFFFFFFFFFFFFFFFF in Android.Runtime.RuntimeNativeMethods.monodroid_debugger_unhandled_exception	C#
 	0x1A in Android.Runtime.JNINativeWrapper._unhandled_exception at /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:13,5	C#
 	0x20 in Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPLI_V at /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:181,26	C#
 	0x48 in System.Collections.Generic.SortedList<Microsoft.Maui.Controls.SetterSpecificity,object>.Add	C#
 	0xBB in Microsoft.Maui.Controls.BindableObject.SetBinding at D:\a\_work\1\s\src\Controls\src\Core\BindableObject.cs:286,5	C#
 	0xBB in Microsoft.Maui.Controls.Setter.Apply at D:\a\_work\1\s\src\Controls\src\Core\Setter.cs:77,5	C#
 	0x11E in Microsoft.Maui.Controls.VisualStateManager.GoToState at D:\a\_work\1\s\src\Controls\src\Core\VisualStateManager.cs:110,6	C#
 	0xE in Microsoft.Maui.Controls.VisualElement.ChangeVisualState at D:\a\_work\1\s\src\Controls\src\Core\VisualElement\VisualElement.cs:1482,5	C#
 	0x1F in Microsoft.Maui.Controls.View.ChangeVisualState at D:\a\_work\1\s\src\Controls\src\Core\View\View.cs:182,4	C#
 	0xC in Microsoft.Maui.Controls.VisualElement.OnIsEnabledPropertyChanged at D:\a\_work\1\s\src\Controls\src\Core\VisualElement\VisualElement.cs:1554,4	C#
 	0x18A in Microsoft.Maui.Controls.BindableObject.SetValueActual at D:\a\_work\1\s\src\Controls\src\Core\BindableObject.cs:611,5	C#
 	0x162 in Microsoft.Maui.Controls.BindableObject.SetValueCore at D:\a\_work\1\s\src\Controls\src\Core\BindableObject.cs:539,5	C#
 	0x5F in Microsoft.Maui.Controls.BindableObject.SetValue at D:\a\_work\1\s\src\Controls\src\Core\BindableObject.cs:444,4	C#
 	0x3E in Microsoft.Maui.Controls.BindableObjectExtensions.RefreshPropertyValue at D:\a\_work\1\s\src\Controls\src\Core\BindableObjectExtensions.cs:23,5	C#
 	0x26 in Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.Controls.IPropertyPropagationController.PropagatePropertyChanged at D:\a\_work\1\s\src\Controls\src\Core\VisualElement\VisualElement.cs:1632,5	C#
 	0xCB in Microsoft.Maui.Controls.Internals.PropertyPropagationExtensions.PropagatePropertyChanged at D:\a\_work\1\s\src\Controls\src\Core\Internals\PropertyPropagationExtensions.cs:32,6	C#
 	0x5E in Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.Controls.IPropertyPropagationController.PropagatePropertyChanged at D:\a\_work\1\s\src\Controls\src\Core\VisualElement\VisualElement.cs:1637,4	C#
 	0x26 in Microsoft.Maui.Controls.VisualElement.OnIsEnabledPropertyChanged at D:\a\_work\1\s\src\Controls\src\Core\VisualElement\VisualElement.cs:1556,4	C#
 	0x18A in Microsoft.Maui.Controls.BindableObject.SetValueActual at D:\a\_work\1\s\src\Controls\src\Core\BindableObject.cs:611,5	C#
 	0x162 in Microsoft.Maui.Controls.BindableObject.SetValueCore at D:\a\_work\1\s\src\Controls\src\Core\BindableObject.cs:539,5	C#
 	0x5F in Microsoft.Maui.Controls.BindableObject.SetValue at D:\a\_work\1\s\src\Controls\src\Core\BindableObject.cs:444,4	C#
 	0x3E in Microsoft.Maui.Controls.BindableObjectExtensions.RefreshPropertyValue at D:\a\_work\1\s\src\Controls\src\Core\BindableObjectExtensions.cs:23,5	C#
 	0x26 in Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.Controls.IPropertyPropagationController.PropagatePropertyChanged at D:\a\_work\1\s\src\Controls\src\Core\VisualElement\VisualElement.cs:1632,5	C#
 	0x29 in Microsoft.Maui.Controls.Element.OnParentSet at D:\a\_work\1\s\src\Controls\src\Core\Element\Element.cs:564,4	C#
 	0x1 in Microsoft.Maui.Controls.NavigableElement.OnParentSet at D:\a\_work\1\s\src\Controls\src\Core\Shell\NavigableElement.cs:75,4	C#
 	0x17E in Microsoft.Maui.Controls.Element.SetParent at D:\a\_work\1\s\src\Controls\src\Core\Element\Element.cs:369,4	C#
 	0x2 in Microsoft.Maui.Controls.Element.OnChildAdded at D:\a\_work\1\s\src\Controls\src\Core\Element\Element.cs:525,4	C#
 	0x2 in Microsoft.Maui.Controls.VisualElement.OnChildAdded at D:\a\_work\1\s\src\Controls\src\Core\VisualElement\VisualElement.cs:1236,4	C#
 	0x18 in Microsoft.Maui.Controls.Element.AddLogicalChild at D:\a\_work\1\s\src\Controls\src\Core\Element\Element.cs:224,4	C#
 	0x8E in Microsoft.Maui.Controls.Handlers.Items.TemplatedItemViewHolder.Bind at D:\a\_work\1\s\src\Controls\src\Core\Handlers\Items\Android\TemplatedItemViewHolder.cs:83,4	C#
 	0x17 in Microsoft.Maui.Controls.Handlers.Items.ItemsViewAdapter<Microsoft.Maui.Controls.ReorderableItemsView,Microsoft.Maui.Controls.Handlers.Items.IGroupableItemsViewSource>.BindTemplatedItemViewHolder at D:\a\_work\1\s\src\Controls\src\Core\Handlers\Items\Android\Adapters\ItemsViewAdapter.cs:154,4	C#
 	0x3B in Microsoft.Maui.Controls.Handlers.Items.StructuredItemsViewAdapter<Microsoft.Maui.Controls.ReorderableItemsView,Microsoft.Maui.Controls.Handlers.Items.IGroupableItemsViewSource>.BindTemplatedItemViewHolder at D:\a\_work\1\s\src\Controls\src\Core\Handlers\Items\Android\Adapters\StructuredItemsViewAdapter.cs:105,5	C#
 	0x4C in Microsoft.Maui.Controls.Handlers.Items.ItemsViewAdapter<Microsoft.Maui.Controls.ReorderableItemsView,Microsoft.Maui.Controls.Handlers.Items.IGroupableItemsViewSource>.OnBindViewHolder at D:\a\_work\1\s\src\Controls\src\Core\Handlers\Items\Android\Adapters\ItemsViewAdapter.cs:71,6	C#
 	0x59 in Microsoft.Maui.Controls.Handlers.Items.StructuredItemsViewAdapter<Microsoft.Maui.Controls.ReorderableItemsView,Microsoft.Maui.Controls.Handlers.Items.IGroupableItemsViewSource>.OnBindViewHolder at D:\a\_work\1\s\src\Controls\src\Core\Handlers\Items\Android\Adapters\StructuredItemsViewAdapter.cs:94,4	C#
 	0x3 in Microsoft.Maui.Controls.Handlers.Items.SelectableItemsViewAdapter<Microsoft.Maui.Controls.ReorderableItemsView,Microsoft.Maui.Controls.Handlers.Items.IGroupableItemsViewSource>.OnBindViewHolder at D:\a\_work\1\s\src\Controls\src\Core\Handlers\Items\Android\Adapters\SelectableItemsViewAdapter.cs:23,4	C#
 	0x4E in Microsoft.Maui.Controls.Handlers.Items.GroupableItemsViewAdapter<Microsoft.Maui.Controls.ReorderableItemsView,Microsoft.Maui.Controls.Handlers.Items.IGroupableItemsViewSource>.OnBindViewHolder at D:\a\_work\1\s\src\Controls\src\Core\Handlers\Items\Android\Adapters\GroupableItemsViewAdapter.cs:65,4	C#
 	0x12 in AndroidX.RecyclerView.Widget.RecyclerView.Adapter.n_OnBindViewHolder_Landroidx_recyclerview_widget_RecyclerView_ViewHolder_I at C:\a\_work\1\s\generated\androidx.recyclerview.recyclerview\obj\Release\net6.0-android\generated\src\AndroidX.RecyclerView.Widget.RecyclerView.cs:581,5	C#
 	0xB in Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPLI_V at /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:180,5	C#
```

**Comment by mattleibow** [comment] 2023-10-04 22:12
Wow. So much pain. My test app had RC 1 in the csproj so I was testing old code. The pain is immeasurable. Someone send a coffee.

**Closed by mattleibow** 2023-10-04 22:12 UTC
Labels: t/bug, platform/android 🤖, area/controls 🎮, high, s/verified, control-refreshview, s/triaged, i/regression, csi-new

**Comment by MetalKid** [comment] 2023-10-25 16:23
We are still getting this crash in rc2
