### ISSUE TITLE
Border bugs entries

### ISSUE THREAD

**Issue by alexskrms** [dotnet/maui#17506] opened 2023-09-20 09:18 UTC
### Description

If you create a border and then inside you have an entry to put stroke and color. No matter what you do the whole border and entry will get a dark background even in Light theme.

### Steps to Reproduce

1. Create a File > New .NET MAUI App
2. Add a Border with an Entry inside: `<Border><Entry/> </Border>`
3. Run the application and see the bug.

### Version with bug

8.0.0-rc.1.9171

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.0-preview.4.8333

### Affected platforms

Android

### Affected platform versions

Android 13, Android 12

### Did you find any workaround?

No workaround for now.

**Comment by moljac** [comment] 2023-09-20 11:59
Can confirm - Android bug

Android:

![Screenshot_1695211036](https://github.com/dotnet/maui/assets/1768576/c2327ad2-ede3-4d53-9a70-db2c9519242a)

MacCatalyst:

<img width="1027" alt="Screenshot 2023-09-20 at 13 53 36" src="https://github.com/dotnet/maui/assets/1768576/02cd3f4a-cc01-486f-9a05-f17de89c668b">


Repro sample:

[17506.zip](https://github.com/dotnet/maui/files/12672729/17506.zip)

**Comment by jstedfast** [comment] 2023-09-21 17:35
Could this be a duplicate of issue #17547?

**Comment by jstedfast** [comment] 2023-09-22 17:11
Confirmed to be a duplicate of issue https://github.com/dotnet/maui/issues/17547

**Closed** 2023-09-24 08:24 UTC
Labels: t/bug, platform/android 🤖, area/controls 🎮, control-border, potential-regression
