### ISSUE TITLE
[Bug] Page crashes with TableView

### ISSUE THREAD

**Issue by mattleibow** [dotnet/maui#2087] opened 2021-08-13 17:18 UTC
### Description

Seems there is a double add or a re-add of the same view when using `TableView`.

```
**Java.Lang.IllegalStateException:**
'The specified child already has a parent. You must call removeView() on the child's parent first.'
```

### Steps to Reproduce

```xaml
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="Maui.Controls.Sample.Pages.TemplatePage">

    <TableView Intent="Settings">
        <TableRoot>
            <TableSection Title="Section">
                <ViewCell>
                    <VerticalStackLayout>
                        <Button Text="Second" />
                    </VerticalStackLayout>
                </ViewCell>
            </TableSection>
        </TableRoot>
    </TableView>

</ContentPage>
```

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Screenshots

![image](https://user-images.githubusercontent.com/1096616/129396341-9afb4194-5eea-417a-a0f4-7e78eb0d6b68.png)

**Comment by hartez** [comment] 2022-01-05 22:26
This is a duplicate of #2123

**Closed by hartez** 2022-01-05 22:26 UTC
Labels: t/bug, area/layout 🔲, platform/android 🤖, fatal
