### ISSUE TITLE
net8 Maui iOS/Android Entry isn't cleared after set bound property value to null

### ISSUE THREAD

**Issue by stoff99** [dotnet/maui#17321] opened 2023-09-12 11:37 UTC
### Description

When you try to set the bound property to null or empty string, the Entry isn't cleared at all. For label or editor its working as expected for example.
This happens on iOS and Android.
Binding is done with CommunityToolKit.MVVM in the example. Also tested with INotifyPropertyChanged implementation = same result.

Example video:
![EntryBindingBug](https://github.com/dotnet/maui/assets/892820/e0c52d26-3c8e-4497-85ce-0ea08910dc60)

### Steps to Reproduce

1. Create a new Maui App
3. Create an entry with binding on a string property. You can do the binding with CommunityToolKit.MVVM or INotifyPropertyChanged.
4. Create a button with a click listener.
5. In the click listener method set the bound property to null or string.empty or ""

Bug: The text stays in the entry

### Link to public reproduction project repository

https://github.com/stoff99/MauiDotNet8EntryBindingBug

### Version with bug

8.0.0-preview.7.8842

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, I was *not* able test on other platforms

**Comment by XamlTest** [comment] 2023-09-13 08:31
Verified this on Visual Studio Enterprise 17.8.0 Preview 1.0. Repro on Android 13.0-API33 and iOS 16.4 .NET 8 with below Project:
[MauiApp1.zip](https://github.com/dotnet/maui/files/12595294/MauiApp1.zip)

**Comment by hansmbakker** [comment] 2023-09-14 13:14
I see you had this issue with .net 8 **preview 7**.
Is this issue related to https://github.com/dotnet/maui/issues/16859? That one is fixed with RC1.

**Comment by stoff99** [comment] 2023-09-14 13:27
Thx for your answer.
I didn't even notice the RC1 to be honest :)
I will install and test it tomorrow if this is fixed.

**Comment by hansmbakker** [comment] 2023-09-14 17:35
Please note that it also seems to differ how you test it - to me it seemed that Visual Studio didn't automatically use the updated dotnet SDK on my computer - I used VS Code + C# dev kit with the preview SDK setting to test it

**Comment by stoff99** [comment] 2023-09-14 18:10
i develop on mac, so i don't know if you know more than me, but there is no Visual Studio for Mac preview which supports any version of dot net 8?

Right now i use JetBrains Rider.

**Comment by stoff99** [comment] 2023-09-14 18:14
![What_s_happening_to_Visual_Studio_for_Mac_-_Visual_Studio_for_Mac___Microsoft_Learn](https://github.com/dotnet/maui/assets/892820/3c8e82ee-ee25-4248-9d2e-4ddf68966f48)

Ok, got it ...

**Comment by samhouts** [comment] 2023-09-19 00:46
Duplicate of #16859

**Closed by samhouts** 2023-09-19 00:46 UTC
Labels: t/bug, area/controls 🎮, s/verified, s/triaged, migration-compatibility
