### ISSUE TITLE
Microsoft.Maui.Controls.Maps control is currently broken on Android

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#20317] opened 2024-02-02 18:35 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/MicrosoftMauiControlsMaps-control-is-/10565427)._

---
Unable to run apps using the MAUI app control.  I receive the following output:

[AndroidRuntime] Shutting down VM
[AndroidRuntime] FATAL EXCEPTION: main
[AndroidRuntime] Process: com.promiles.FuelFinder.Adhoc, PID: 7552
[AndroidRuntime] java.lang.ClassCastException: com.google.maps.api.android.lib6.impl.as cannot be cast to android.view.ViewGroup
[AndroidRuntime] 	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:537)
[AndroidRuntime] 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:272)
[AndroidRuntime] 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1943)
[AndroidRuntime] 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1839)
[AndroidRuntime] 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1782)
[AndroidRuntime] 	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:565)
[AndroidRuntime] 	at android.os.Handler.handleCallback(Handler.java:942)
[AndroidRuntime] 	at android.os.Handler.dispatchMessage(Handler.java:99)
[AndroidRuntime] 	at android.os.Looper.loopOnce(Looper.java:201)
[AndroidRuntime] 	at android.os.Looper.loop(Looper.java:288)
[AndroidRuntime] 	at android.app.ActivityThread.main(ActivityThread.java:7872)
[AndroidRuntime] 	at java.lang.reflect.Method.invoke(Native Method)
[AndroidRuntime] 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
[AndroidRuntime] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

---
#### Feedback Bot on 1/21/2024, 09:59 PM: 

(private comment, text removed)
#### Gerald Versluis [MSFT] on 1/24/2024, 05:38 AM: 

(private comment, text removed)
#### olen on 1/26/2024, 10:01 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by okirkland-promiles** [comment] 2024-02-06 15:05
This issue is now being tracked [here](https://github.com/orgs/dotnet/projects/194/views/21?pane=issue&itemId=51670497).

**Comment by PureWeen** [comment] 2024-02-13 15:24
Duplicate of #20187

**Closed by PureWeen** 2024-02-13 15:24 UTC
Labels: t/bug, platform/android 🤖, s/needs-attention, area/Maps🗺
