### ISSUE TITLE
VerticalStackLayout inside Scrollview: Button at the bottom not clickable on IOS

### ISSUE THREAD

**Issue by FM1973** [dotnet/maui#14257] opened 2023-03-29 07:41 UTC
### Description

When you put a VerticalStackLayout inside a ScrollView and load some data dynamically (i.e. some Text using an async function) and then put a button on the end of the VerticalStackLayout, the Button-Handler never gets called.
This works on Android without any problem.
For me related to: #8820 

### Steps to Reproduce

1. Clone the repo
2. Run the app on IOS
3. Click on the "Button at bottom" Button
4. Scroll to the bottom of the page and try to click the button

### Link to public reproduction project repository

https://github.com/FM1973/RefreshGridRepo.git

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 14.x +

### Did you find any workaround?

Yes, there is a workaround. It´s the same as before having the general ScrollView-problem stated in #8820 
Look there: [https://github.com/dotnet/maui/issues/8820#issuecomment-1352923013](https://github.com/dotnet/maui/issues/8820#issuecomment-1352923013) 

### Relevant log output

```shell
-
```

**Comment by PureWeen** [comment] 2023-03-29 18:16
@hartez FYI

**Comment by softlion** [comment] 2023-03-30 08:06
Thank you !!

the workaround which consits in calling InvalidateMeasure on the ScrollView after you make visible new items does work !

I lost 4 days on trying to find a repro on that, since a full week !

**Comment by fgiacomelli** [comment] 2023-04-05 07:15
Thank you for sharing, it fixes the bug also for me

**Comment by MichaelNovikov** [comment] 2023-05-01 20:14
Workaround with an InvalidateMeasure doesn't work anymore

**Comment by dk-mushiyoke** [comment] 2023-05-03 23:06
can confirm that this issue also exists in our app - we have pages with scroll views going beyond the device screen size, when scrolled to the bottom on iOS none of the elements that were originally cut off can be interacted with. Also tried the InvalidateMeasure() workaround as well and it did not fix the issue.

**Comment by nicjay** [comment] 2023-05-03 23:40
The InvalidateMeasure workaround does still work for me as of 7.0.81 for this particular issue.

To be clear, I use code similar to the following in my code-behind:

```C#
MyVerticalStackLayout.SizeChanged += (object sender, EventArgs e) =>
{
    (MyScrollView as IView).InvalidateMeasure();
}
```

XAML
```XAML
<ScrollView x:Name="MyScrollView">
    <VerticalStackLayout x:Name="MyVerticalStackLayout">
    ...
    </VerticalStackLayout>
</ScrollView>
```


However, it would be ideal if this were not necessary.

**Comment by etienneCGI** [comment] 2023-05-04 16:53
> The InvalidateMeasure workaround does still work for me as of 7.0.81 for this particular issue.
> 
> To be clear, I use code similar to the following in my code-behind:
> 
> ```cs
> MyVerticalStackLayout.SizeChanged += (object sender, EventArgs e) =>
> {
>     (MyScrollView as IView).InvalidateMeasure();
> }
> ```
> 
> XAML
> 
> ```
> <ScrollView x:Name="MyScrollView">
>     <VerticalStackLayout x:Name="MyVerticalStackLayout">
>     ...
>     </VerticalStackLayout>
> </ScrollView>
> ```
> 
> However, it would be ideal if this were not necessary.

Thanks you very much it's work for me

**Comment by dk-mushiyoke** [comment] 2023-05-04 21:01
after reading @nicjay's comment I tried the workaround again in a new maui project and that worked out fine, so maybe it lies somewhere in the complexity of our view hierarchy (bunch of grids and layouts inside a CarouselView inside a ScrollView). Thanks for the info

**Comment by fgiacomelli** [comment] 2023-05-05 08:11
In a more complex solution the workaround suggested didn't work for me: I have a scrollview, that has a verticalstacklayout with a bindablelayout inside. The datatemplate of the bindable use an expander (but I already tried using a button or a tapGestureRecognizer): the problem is that all the elements that was not present when the page appears does not receive the tap event. Calling InvalidateMeausure over the scrollview when PropertyChanged event of the verticalstacklayout is raised does not work

**Comment by fgiacomelli** [comment] 2023-05-05 12:07
In the meantime I discovered what is the problem in my situation: I have a refreshview around the scrollview, and this seems to be the problem that prevent buttons/tapgestures to receive tap/click events if they are not visible when the page appears. Removing it solves the problem, and gave me the possibility to manually implement the pool to refresh behavior using the scrolled event of the scrollview...

**Comment by psdiviso** [comment] 2023-05-08 08:58
@fgiacomelli I have the exact same problem. Scrollview --> verticalstacklayout  --> with a bindablelayout inside. Where because the bindablelayout layout is hidden onAppearing half tabs in the list doesn't work. How did you: "manually implement the pool to refresh behavior"

??

**Comment by iammh93** [comment] 2023-05-19 06:35
> The InvalidateMeasure workaround does still work for me as of 7.0.81 for this particular issue.
> 
> To be clear, I use code similar to the following in my code-behind:
> 
> ```cs
> MyVerticalStackLayout.SizeChanged += (object sender, EventArgs e) =>
> {
>     (MyScrollView as IView).InvalidateMeasure();
> }
> ```
> 
> XAML
> 
> ```
> <ScrollView x:Name="MyScrollView">
>     <VerticalStackLayout x:Name="MyVerticalStackLayout">
>     ...
>     </VerticalStackLayout>
> </ScrollView>
> ```
> 
> However, it would be ideal if this were not necessary.

If this solution does not worked, just add transparent box with fixed height at the bottom of your layout, stupid way but it worked
```
<BoxView BackgroundColor="Transparent" HeightRequest="200" />
```

**Comment by hartez** [comment] 2023-05-19 20:47
This is fixed by #14176.

**Comment by jadenrogers** [comment] 2023-05-31 03:23
@hartez Please correct me if I am wrong but when you say "This is fixed by https://github.com/dotnet/maui/pull/14176." can people on .net 7 expect these fixes? As .net 8 isn't released is it fair to say these are fixed. Running into this a lot where issues are raised in current .net 7 production and fixed for .net 8 which his a little frustrating. 

Maybe we could avoid using "its fixed", until a PR is raised against .net 7. I feel I am going to have to upgrade to .net 8 to get all these fixes but then is it the same again when we encounter problems... Fixed in .net 9 Preview X?

Thanks

**Comment by swetaVanjara** [comment] 2023-06-06 06:19
I'm trying to solve this problem from couple of days. it's took almost week. haha! thank you so much for this solution @FM1973

**Comment by jadenrogers** [comment] 2023-06-06 07:49
Save all the wiring up you can try use this.

```csharp
	public class FixedScrollView : ScrollView
	{
		public new View Content
		{
			get
			{
				return base.Content;
			}
			set
			{
				if (value == null && base.Content != null)
					base.Content.SizeChanged -= Content_SizeChanged;
				else if (value != null)
					value.SizeChanged += Content_SizeChanged;

				base.Content = value;
			}
		}

		void Content_SizeChanged(object sender, EventArgs e)
		{
			#if IOS
			InvalidateMeasure();
			#endif
		}
	}
```

**Comment by hartez** [comment] 2023-06-12 22:31
> @hartez Please correct me if I am wrong but when you say "This is fixed by #14176." can people on .net 7 expect these fixes?

They can, the fix was backported last week: https://github.com/dotnet/maui/pull/15424

> As .net 8 isn't released is it fair to say these are fixed. Running into this a lot where issues are raised in current .net 7 and fixed for .net 8 which is a little frustrating.
> 
> Maybe we could avoid using "its fixed", until a PR is raised against .net 7. I feel I am going to have to upgrade to .net 8 to get all these fixes but then is it the same again when we encounter problems... Fixed in .net 9 Preview X?

This is the current policy - bug fixes are targeted at vNext and then, if there's enough demand (vs the risk of possible regressions), they are backported to the stable version. So you will see the same situation when .NET 8 is released - bugs will be fixed for .NET 9, and then backported to 8 (and possibly 7/6 depending on the support policies for those versions).

**Comment by jadenrogers** [comment] 2023-06-12 23:22
@hartez Thanks for clarifying.

**Comment by softlion** [comment] 2023-06-13 06:36
This policy is amazing. Who decided it ?

**Comment by FM1973** [comment] 2023-06-13 06:47
From the developer point of view I can understand the policy.
As a company, who has to tell it´s customer "Sorry, you will have to wait for a bug fix until november" I can´t.

**Comment by jadenrogers** [comment] 2023-06-13 08:24
@hartez I made a comment that highlights the problem I have with this fix in vNext approach, can you provide some guidance on how people can better hot fix / patch existing handlers without resorting to copying the whole source code? Comment over https://github.com/dotnet/maui/pull/15460

**Comment by davidortinau** [comment] 2023-07-05 20:46
@hartez I'm able to repro this issue on 8.0.0-preview.6.8686, iOS 16.4 simulator. I'm using the provided repro. 

Once I rotate the device, I can interact with the button.

I have another project that is ScrollView > VStack > Expander (3+). When I expand I can see the content but not interact. They are also at the bottom of my layout like this button is.

The `SizeChanged` workaround does work for me.

**Comment by jadenrogers** [comment] 2023-07-08 05:50
Hi @davidortinau 

[.net 8 fix](https://github.com/dotnet/maui/pull/16048)

.net 7 same issue [PR is also here ](https://github.com/dotnet/maui/pull/15460)

Would love some feedback

**Comment by tibuprophen** [comment] 2023-07-21 11:16
Workaround does not work for me on iOS using workloads 7.0.92

**Comment by jadenrogers** [comment] 2023-07-21 17:31
@tibuprophen Do you have an example to check?

**Comment by tibuprophen** [comment] 2023-07-21 18:22
Of course:
```xaml
<?xml version="1.0" encoding="utf-8"?>

<ContentPage
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    x:Class="RefreshScrollButton.MainPage">
    <RefreshView>
        <ScrollView>
            <StackLayout>
                <!-- adding an element with a big height to force the scroll -->
                <BoxView BackgroundColor="Black" HeightRequest="1000" WidthRequest="40" HorizontalOptions="Center" />
                <!-- button is not clickable in the non-visible area / does not execute command or Clicked event -->
                <Button Text="Click me" />
            </StackLayout>
        </ScrollView>
    </RefreshView>
</ContentPage>
```

**Comment by jadenrogers** [comment] 2023-07-21 18:39
@tibuprophen Maybe the code behind as well, are you programmatically hiding showing content? That looks like that should work off the bat. Can you remove the RefreshView, Does that make a difference?

**Comment by tibuprophen** [comment] 2023-07-21 18:41
There is no code behind. Default ContentPage with InitializeComponents - nothing more. 
It works when I remove the RefreshView. 
The issue happens in the combination with RefreshView + ScrollView.

**Comment by jadenrogers** [comment] 2023-07-22 02:48
@tibuprophen Oh yes I see, also mentioned further above too. Challenge accepted.

Its seems no matter what the content size is never calculated correctly, invalidating doesn't adjust the height.

Confirmed it is fixed by https://github.com/dotnet/maui/pull/15460


New work around that fixes **all** the scrolling / button issues

Add this into your MauiProgram.cs 

```csharp
#if IOS

        Microsoft.Maui.Handlers.ScrollViewHandler.Mapper.AppendToMapping(nameof(IScrollView.ContentSize), (h, v) =>
			{
				var contentSize = h.VirtualView.ContentSize;

                if (contentSize.IsZero)
					return;

				UIKit.UIScrollView uiScrollView = h.PlatformView;
				var container = uiScrollView.Subviews.FirstOrDefault(x => x.Tag == 0x845fed);			

				if (container != null && container.Bounds.Height != contentSize.Height)
				{
					container.Bounds = new CoreGraphics.CGRect(
						container.Bounds.X,
						container.Bounds.Y, 
						contentSize.Width, 
						contentSize.Height);

					(h.VirtualView as IView).InvalidateMeasure();
				}
			});
#endif
```

![image](https://github.com/dotnet/maui/assets/8000621/bf2c4455-246f-48b7-8369-cdb8a411b6cc)

**Comment by tibuprophen** [comment] 2023-07-23 15:00
Thank you @jadenrogers, this is working!

**Closed** 2023-07-27 08:53 UTC
Labels: t/bug, area/layout 🔲, platform/iOS 🍎, p/1, layout-stack, layout-scrollview, fixed-in-8.0.0-preview.3.8149

**Comment by MageInt** [comment] 2023-08-02 10:07
The work arround did work for me using workloads 7.0.92 :)

**Comment by PureWeen** [comment] 2023-08-09 15:25
Can y'all validate this fix on .NET8 preview7?

**Comment by jadenrogers** [comment] 2023-08-13 01:06
fixes https://github.com/dotnet/maui/issues/15374
fixes https://github.com/dotnet/maui/issues/14624
fixes https://github.com/dotnet/maui/issues/15288
fixes https://github.com/dotnet/maui/issues/15283
fixes https://github.com/dotnet/maui/issues/14795
