### ISSUE TITLE
iOS issue tabbar having 6 tabs, On the 6th tab, button click having Shell.Current.GoToAsync to show new page, not working

### ISSUE THREAD

**Issue by NeerajRai111** [dotnet/maui#15103] opened 2023-05-16 08:57 UTC
### Description

Maui iOS issue having  tabbar with 6 tabs.
On the 6th tab i have a button click which is opening a new page by Shell.Current.GoToAsync.
It is not showing/opening new page.

### Steps to Reproduce

1. Create a new Maui APP.
2. Add TabBar with Tabs as ShellContent
3. Add 6 tabs
4. 6th tab should  have a button.
5. Button click having the code as "Shell.Current.GoToAsync($"{nameof(NewModelPage)}"); "

Expected: It should open the new page : "NewModelPage"
Actual: It is not doing anything

### Link to public reproduction project repository

https://github.com/NeerajRai111/ShellPresentationModeTest

### Version with bug

7.0 (current)

### Last version that worked well

6.0.312

### Affected platforms

iOS

### Affected platform versions

iOS 16

### Did you find any workaround?

No

**Comment by vr4guid** [comment] 2023-05-16 14:24
This will be an important issue to get resolved quickly.

**Comment by XamlTest** [comment] 2023-07-12 10:13
Verified this on Visual Studio Enterprise 17.7.0 Preview 2.0. Repro on iOS 16.4 with below Project:
[ShellPresentationModeTest.zip](https://github.com/dotnet/maui/files/12026645/ShellPresentationModeTest.zip)

**Comment by durandt** [comment] 2023-08-07 11:58
This is a pretty blocker issue as all navigation breaks on iOS from the 6th tab and upwards. This should be prioritized ASAP. There is not known way to work around this issue yet. ping @hartez

**Comment by durandt** [comment] 2023-08-07 11:58
Navigation.PushAsync does not work either and both Navigation.PushAsync and Shell.Current.GoToAsync just hangs.

**Comment by FelixCEriksson** [comment] 2023-11-20 14:06
Is there any known workaround? For us this is a big stopper and I hope the issue gets prioritized

**Comment by durandt** [comment] 2023-11-20 14:20
@FelixCEriksson we implemented our own "More"-page that will always be the fifth tab and shows the tabs that would otherwise have appeared under "More". Gives you more control on how you want to "More"-page too look like.

**Comment by FelixCEriksson** [comment] 2023-11-20 14:52
Thanks @durandt, not really a quick fix but i guess there is no ther way at the moment.

**Comment by PureWeen** [comment] 2023-12-13 19:23
Duplicate of #18193

**Closed by PureWeen** 2023-12-13 19:23 UTC
Labels: t/bug, area/shell 🐢, s/verified, s/triaged

**Comment by vr4guid** [comment] 2023-12-15 16:17
Amy updates on this. It's a pretty substantial UI issue.
