### ISSUE TITLE
Unintended entry focus change in `ScrollView`

### ISSUE THREAD

**Issue by MartyIX** [dotnet/maui#19733] opened 2024-01-07 12:25 UTC
### Description

I can see an unitended change in focus that can be very bothering because it can move user from filling an entry that is vertically far from the first form's entry.

### Steps to Reproduce

1. Run the sample application
2. Click the `Input 7`'s entry like this: 
    ![image](https://github.com/dotnet/maui/assets/203266/e03a40ea-f1ec-40a9-b2a2-f9c83ff10536)
3. Click the `Input 7` label (!) itself like this:
    ![image](https://github.com/dotnet/maui/assets/203266/cd90ff9d-a93c-4c30-a880-dbc242d18783)
4. Focus moves to the `Input 1`'s entry like this:
    ![image](https://github.com/dotnet/maui/assets/203266/c547d4e2-3877-4bb3-9378-1a22c0a6a25d)

-> The step number 4 should not occur or there should be a way to remove it IMO.

Interestingly, commenting out this line https://github.com/MartyIX/MauiRepro202401ScrollJump/blob/4a0919488bdcbdc5d8bc91e64976f0baf6bb7799/MainPage.xaml#L6 fixes the issue. So it looks like the bug is linked to the `ScrollView` in some way.

Demo: ![Animation](https://github.com/dotnet/maui/assets/203266/7c78ceef-2bfd-4515-9ba1-4fe4c1643785)

### Link to public reproduction project repository

https://github.com/MartyIX/MauiRepro202401ScrollJump

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

I can't reproduce the issue on Mac Catalyst. Not sure about android.

### Affected platform versions

I know that Windows is affected, not sure about other platforms

### Did you find any workaround?

Not yet.

**Comment by PureWeen** [comment] 2024-01-08 16:08
Duplicate of #11472

**Closed by PureWeen** 2024-01-08 16:08 UTC
Labels: t/bug, platform/windows 🪟, area/layout 🔲, layout-scrollview
