### ISSUE TITLE
Span bindings are ignored when properties are changed

### ISSUE THREAD

**Issue by JohnHDev** [dotnet/maui#4901] opened 2022-02-24 20:38 UTC
### Description

When using a binding in a Label FormattedText span, the initial page load is correct, but changing properties bound to the span are not updated. For example the span FontSize, TextColor etc aren't updated.

### Steps to Reproduce

Add a label with a formatted text
Add a span and set a binding to the font size
Add a button that increments the property containing the font size
Run it
The span is the correct initial font size
Tap the button several times, the property is incremented but the font size of the span does not change

### Version with bug

Preview 13 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Windows

### Affected platform versions

iOS 15, Windows

### Did you find any workaround?

No

**Comment by NogginBox** [comment] 2022-02-28 07:41
I think this is caused by the same thing as issue #4765.

**Comment by shimingsg** [comment] 2022-03-01 07:21
verified repro with VS 17.2.0 Preview 2.0 [32228.339.main] in Windows
[4901.zip](https://github.com/dotnet/maui/files/8159526/4901.zip)

**Comment by NogginBox** [comment] 2022-03-04 06:32
@redth is this issue also fixed by PR #5029 like issue #4765 was?

**Comment by cshung** [comment] 2022-03-10 22:27
I confirmed that this issue is fixed by https://github.com/dotnet/maui/pull/5029. The font size won't change without that fix, and it does change with the fix.

**Closed by cshung** 2022-03-10 22:27 UTC
Labels: t/bug, area/controls 🎮, high, s/verified
