### ISSUE TITLE
MenuBar/MenubarItem does not bind to commands

### ISSUE THREAD

**Issue by 420tech** [dotnet/maui#9762] opened 2022-08-29 20:23 UTC
### Description

I am trying to use both MenuBar (for my Desktop versions) and Shell (for desktop navigation and for menuing for mobile apps). When I try to bind a command to a menubaritem, the bound command does not get executed. It appears that menubaritems can only respond to code behind event handlers. See this link for repro: https://github.com/420tech/MauiMulti.

Also - MenuBar ONLY is visible on Windows - not on Mac.

### Steps to Reproduce

See repro attached. 

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, macOS

### Affected platform versions

Windows 10.0.17763.0 

### Did you find any workaround?

No.

**Comment by Eilon** [comment] 2022-08-30 17:26
Duplicate of https://github.com/dotnet/maui/issues/5382.

**Closed by Eilon** 2022-08-30 17:26 UTC
Labels: t/bug, area/desktop 🖥️, control-menubar
