### ISSUE TITLE
grey titlebar on windows when using the content page

### ISSUE THREAD

**Issue by ahmedmohammedfawzy** [dotnet/maui#5067] opened 2022-03-04 20:41 UTC
### Description

Starting a new maui project gives this big grey title bar on windows

![Capture](https://user-images.githubusercontent.com/42243982/156838147-0a272fd9-c1ba-4ab8-9175-35a6073b85cd.PNG)

### Steps to Reproduce

1. Create new maui app

### Version with bug

Preview 13 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

windows 10.0.19041

**Comment by drasticactions** [comment] 2022-03-04 21:07
That's by design, it's an extended title bar.

**Comment by JohnHDev** [comment] 2022-03-04 21:24
How to remove it if you don’t have anything to add to it?

**Comment by ahmedmohammedfawzy** [comment] 2022-03-04 21:55
> That's by design, it's an extended title bar.

Is there an option to make it a normal title bar and change its color

**Comment by Realgigabyte** [comment] 2022-03-05 17:23
> That's by design, it's an extended title bar.

Hi, is there also a way to hide the title bar so the ContentPage occupy the whole window (and consecutively full screen or immersive mode)?

**Comment by PureWeen** [comment] 2022-03-06 20:04
> Is there also a way to hide the title bar so the ContentPage occupy the whole window (and consecutively full screen or immersive mode)? 

If you do this then the window is undraggable and the window caption buttons are unclickable. Don't all desktop apps all have titlebars unless you go into a full screen mode?  If you have a design example you're wanting to match please add some screen shots here so we can see what makes sense. 

We do need to make it shorter. The plan is to make it the same height as the close/min/,ax buttons. 

The eventual plan is to allow you to change the color but currently the APIs for setting the color only work on Windows 11, so we'll have to wait until WinUI makes that work.

**Comment by Realgigabyte** [comment] 2022-03-06 20:50
> > Is there also a way to hide the title bar so the ContentPage occupy the whole window (and consecutively full screen or immersive mode)?
> 
> If you do this then the window is undraggable and the window caption buttons are unclickable. Don't all desktop apps all have titlebars unless you go into a full screen mode? If you have a design example you're wanting to match please add some screen shots here so we can see what makes sense.
> 
> We do need to make it shorter. The plan is to make it the same height as the close/min/max buttons.
> 
> The eventual plan is to allow you to change the color but currently the APIs for setting the color only work on Windows 11, so we'll have to wait until WinUI makes that work.

I am simply looking to make a full screen app. Is there a functionality for that?

**Comment by PureWeen** [comment] 2022-03-06 21:26
> I am simply looking to make a full screen app. Is there a functionality for that?

It looks like you can do it via Win32 APIs at this point
https://github.com/microsoft/microsoft-ui-xaml/issues/4224#issuecomment-1025178714

This would probably be a useful platform specific for us to add but for now you can use the snippet above to make the app full screen

**Comment by PineYi** [comment] 2022-03-07 02:44
Verified Repro with Windows. Repro Project is available:
[#5067.zip](https://github.com/dotnet/maui/files/8194356/5067.zip)

**Comment by ahmedmohammedfawzy** [comment] 2022-03-08 05:08
> > Is there also a way to hide the title bar so the ContentPage occupy the whole window (and consecutively full screen or immersive mode)? 
> 
> If you do this then the window is undraggable and the window caption buttons are unclickable. Don't all desktop apps all have titlebars unless you go into a full screen mode?  If you have a design example you're wanting to match please add some screen shots here so we can see what makes sense. 
> 
> We do need to make it shorter. The plan is to make it the same height as the close/min/max buttons. 
> 
> The eventual plan is to allow you to change the color but currently the APIs for setting the color only work on Windows 11, so we'll have to wait until WinUI makes that work.

I see, but when i tried to make a shell application the title bar was just fine, so i thought that the problem was with the content page, or am I wrong?

**Comment by jfversluis** [comment] 2022-03-23 11:11
As mentioned this is sort of expected or at least functionality of WinUI but we are working to make the default experience better. That work is being tracked in #2190 closing this one for now to not have duplicates.

**Closed by jfversluis** 2022-03-23 11:11 UTC
Labels: t/bug, area/desktop 🖥️, s/verified, s/needs-attention
