### ISSUE TITLE
[Enhancement] Nested c# files

### ISSUE THREAD

**Issue by luismts** [dotnet/maui#91] opened 2020-05-22 21:25 UTC
# Summary (edited)

> I think this is part of visual studio tools. But I leave it here so that it can influence the VS team internally there. 

Now that we are seeing some c# approaches, I think that is time for the nested c# files with partial classes. 

->MyView.cs
-->MyView.logic.cs

Just to split the UI and the UI logic. A lot of people would love that.

**Comment by mrwcjoughin** [comment] 2020-05-23 07:06
you can already (and have always been able to) do this with partial classes - absolutely nothing stopping you

**Comment by GiampaoloGabba** [comment] 2020-05-23 11:50
yepp partial classes are here just for that :)
Plus some IDEs provide the ability to configure nesting as you want! Maybe there is a plugin for VS/VSC, i haven't checked that. But with JetBrains Rider is super easy :)

**Comment by GiampaoloGabba** [comment] 2020-05-23 11:52
oh, also possible duplicate of #83

**Comment by charlesroddie** [comment] 2020-05-23 21:14
You can split up .net code into multiple files, and these files will get compiled when you build a project. In any language, not just those with the concept of partial classes.

**Comment by luismts** [comment] 2020-05-24 17:37
Yes, that was what I mean. I was talking about nested files by default or at least having the option to make that happens. 

I just used the wrong word. Thanks for the comments guys.

cc @GiampaoloGabba @charlesroddie @mrwcjoughin

**Comment by charlesroddie** [comment] 2020-05-24 19:05
@luismts the right place for a request for nested C# files is https://github.com/dotnet/csharplang .

**Comment by Happypig375** [comment] 2020-05-25 01:48
This is a tooling request, not a language request. File at https://github.com/dotnet/roslyn instead.

**Closed** 2020-09-14 20:33 UTC
Labels: proposal-open
