### ISSUE TITLE
dotnet publish not working with dependent projects

### ISSUE THREAD

**Issue by Tardigrade42** [dotnet/maui#9879] opened 2022-09-02 19:46 UTC
### Description

This issue is the same as https://github.com/dotnet/maui/issues/7268 which was closed because of missing information. So I had to make a new one.

The issue might by the way have constrains to multiple other building-issues, but I have not found anything completely similar.

The issue is, that I cannot build a Maui App with `dotnet publish` if it has dependencies to other projects of any kind.

### Steps to Reproduce

1. Create a Maui-App from the template
2. Add another project of any type (`Maui Class Library`, `Class Library > net 6.0` etc.) to the solution
3. Add a dependency in the Maui-App for the other project
4. Try to build it with one of the following commands:
   - For x86
     `dotnet publish TestApp/TestApp.csproj -c Release -f:net6.0-windows10.0.19041.0 /p:GenerateAppxPackageOnBuild=true /p:Platform=x86 /p:AppxPackageSigningEnabled=true /p:PackageCertificateThumbprint="<Your_Cert_Thumbprint>" /p:RuntimeIdentifier=win10-x86`
   - For x64
     `dotnet publish TestApp/TestApp.csproj -c Release -f:net6.0-windows10.0.19041.0 /p:GenerateAppxPackageOnBuild=true /p:Platform=x64 /p:AppxPackageSigningEnabled=true /p:PackageCertificateThumbprint="<Your_Cert_Thumbprint>"`

(Both commands are for the Windows Powershell)

In both cases, the following command is showing up:
`*:\Users\***\.nuget\packages\microsoft.windowsappsdk\1.1.3\buildTransitive\Microsoft.Build.Msix.Packaging.targets(138,5): error : Improper project configuration: WindowsPackageType is set to None, but GenerateAppxPackageOnBuild is set to true. [*:\Users\***\Desktop\
TestApp\TestLib\TestLib.csproj]`  

(`TestLib` is the `NET Maui Classlibrary` I added).

*Note:* After you add the dependency in TestApp, make sure, that the .csproj file has saved. Otherwise, the error is not showing up. (This was an issue I just ran into)

### Link to public reproduction project repository

https://github.com/Tardigrade42/Maui-Issue-9879

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

I guess all Windows versions

### Did you find any workaround?

A 'workaround' was to put everything into one project.

**Comment by AlanGusLive** [comment] 2022-09-03 14:32
Related issue: https://github.com/dotnet/maui/issues/9547
Scheduled: [.NET 7 Planning](https://github.com/dotnet/maui/milestone/27)

**Comment by jfversluis** [comment] 2022-09-05 10:41
As requested by the bug report template: can you please add a reproduction project with how you've set this all up? That will make it most clear what you're trying to do exactly and hopefully it will be easy for us to point out what might not look right or where a potential issue is, thanks!

**Comment by Tardigrade42** [comment] 2022-09-06 11:47
@jfversluis: I added a repository to the original comment. I have also set up two actions to show the issue (yes, they base on your tutorial ;) ). You can find more details on how to reproduce the issue locally in the README of the repo.

**Comment by mattleibow** [comment] 2022-09-06 20:41
After a bunch of things and testing, I think there is a few bugs somewhere in the tooling parts of the system:

 - The docs mentioned a property, but this was only meant to be used INSIDE the app .csproj: https://github.com/dotnet/docs-maui/pull/857
 - Building with a RID causes the app to build incorrectly: https://github.com/microsoft/WindowsAppSDK/issues/2940
 - Also note, using `/p:Platform=*` is not needed as the RID does that and works better in the .NET "Core" world.

There is a workaround for now:

Add this to the bottom of the app .csproj:

```xml
<PropertyGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows' and '$(RuntimeIdentifierOverride)' != ''">
	<RuntimeIdentifier>$(RuntimeIdentifierOverride)</RuntimeIdentifier>
</PropertyGroup>
```

Then when executing, use the new property instead of the RID:

```
dotnet publish MyApp.csproj -c Release -f net6.0-windows10.0.19041.0 /p:RuntimeIdentifierOverride=win10-x86
```

See also my PR: https://github.com/Tardigrade42/Maui-Issue-9879/pull/2

**Comment by mattleibow** [comment] 2022-09-06 22:06
Closing this issue as there is not much we can do for now. Hopefully there is a fix coming soon in the new version of Windows App SDK.

**Comment by Tardigrade42** [comment] 2022-09-07 08:15
Good morning @mattleibow,
thanks for the fast fix :) . It works fine for me. From my point of view, we can close the issue.

**Comment by Tardigrade42** [comment] 2022-09-07 08:27
I have on short question left:
All the time, I build a Maui application with `dotnet publish`, I get the following warning:
```
C:\Users\runneradmin\.nuget\packages\microsoft.windowsappsdk\1.1.3\buildTransitive\Microsoft.Build.Msix.Packaging.targets(341,5): warning : Path to `mspdbcmf.exe` could not be found. A symbols package will not be generated. Review https://aka.ms/windowsappsdkdocs and ensure that all prerequisites for Windows App SDK development have been installed. [D:\a\Maui-Issue-9879\Maui-Issue-9879\TestIssue9879\MauiApplication\MauiApplication.csproj]
```
This warning can also be seen in your last GitHub Actions: 
[x86 run](https://github.com/mattleibow/Maui-Issue-9879/runs/8215556992?check_suite_focus=true)
[x64 run](https://github.com/mattleibow/Maui-Issue-9879/runs/8215556976?check_suite_focus=true)

Is this of any concern / Is `mspdbcmf.exe` important? Or can I ignore this warning?

**Comment by mattleibow** [comment] 2022-09-07 18:23
Awesome!

This warning is just that a special symbols package is not going to be created. This is safe to ignore, but might make debugging issues from the Store harder.

Could you open an issue about this warning on https://github.com/microsoft/WindowsAppSDK?

**Closed by mattleibow** 2022-09-07 18:23 UTC
Labels: t/bug, platform/windows 🪟, area/tooling ⚙️, area/publishing 🏁, s/needs-attention

**Comment by mattleibow** [comment] 2023-01-13 22:56
Moved the WASDK issue to https://github.com/microsoft/WindowsAppSDK/issues/3337

**Comment by mattleibow** [comment] 2023-08-15 16:19
Duplicate of https://github.com/dotnet/maui/issues/9547
