### ISSUE TITLE
Blazor MAUI <select> element - events not occurring

### ISSUE THREAD

**Issue by ajgarciaj** [dotnet/maui#5188] opened 2022-03-10 11:32 UTC
### Description

I see in another question, select control in maui blazor not work properly : (you need use size=2 or the list not show). It's a reported bug with no solution.

But even using size 2, i have found another problem, events not working, i can not see any errors but if i try with @bind or @onchange or @onclick, no events works. The same @bind or @onchange in input control works nicely.

</label><input id="chkCargoIncluido" type="checkbox" @bind="DoStuff" name="chkCargoIncluido"></span>;
works,

<select name="cboPaisDestino"  size="4" id="cboPaisDestino" @onchange="DoStuff  ">
Does nothing.

Any idea?

Thanks.

### Steps to Reproduce

1. Create new Blazor MAui app.
2. Add a select with event 
3. Compile to Windows platform and run it.

### Version with bug

Preview 13 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

All blazor maui windows sdk versions

**Comment by jfversluis** [comment] 2022-03-10 12:21
> I see in another question

What do you mean by this? Has this been reported already? It would be really helpful if you could provide a little sample app reproduction that shows this issue.

**Comment by mkArtakMSFT** [comment] 2022-03-10 17:36
Thanks for contacting us.
The issue with `size="2"` was [just fixed](https://github.com/MicrosoftEdge/WebView2Feedback/issues/1693#issuecomment-1045461543).
We'll look into the issue you've reported related to the events not firing.

**Comment by MackinnonBuck** [comment] 2022-03-10 23:29
I have confirmed that the issue exists specifically in Blazor MAUI (`<select>` works fine in a WinForms/WPF web view).

**Comment by MackinnonBuck** [comment] 2022-03-11 00:01
This seems to be a WebView2 bug specific to WinUI. Even a `<select>` element present in static HTML doesn't fire `onchange` events.

**Comment by MackinnonBuck** [comment] 2022-03-14 21:19
Confirmed to be a WebView2 bug. We should verify that Microsoft.WindowsAppSDK 1.0.1 ends up fixing the issue. See https://github.com/MicrosoftEdge/WebView2Feedback/issues/1693#issuecomment-1061321895

**Comment by MackinnonBuck** [comment] 2022-03-22 18:16
Closing - confirmed that this was fixed with Microsoft.WindowsAppSDK 1.0.1

**Closed by MackinnonBuck** 2022-03-22 18:16 UTC
Labels: t/bug, area/blazor 🕸️, s/verified
