### ISSUE TITLE
[iOS] Margin does not work on Border inside a CollectionView

### ISSUE THREAD

**Issue by Victor-Porter** [dotnet/maui#19365] opened 2023-12-12 14:59 UTC
### Description

I have created a collectionView with a header and footer.
Each section contain a border component (header, body and footer).

I apply a margin to the border component and it doesn't work on iOS.
In Windows and Android works well.

**IPHONE**
![image](https://github.com/dotnet/maui/assets/137196565/6a899ff6-e838-4598-b7bf-a92a52f00c62)

**ANDROID**
![image](https://github.com/dotnet/maui/assets/137196565/5a1486c7-49cd-4c2f-b097-f21e0e23f62f)

**WINDOWS**
![image](https://github.com/dotnet/maui/assets/137196565/14c0ada0-8595-4d94-8a48-a0b017fb78c2)

### Steps to Reproduce

1. Create a new MAUI project.
2. Create a CollectionView with a header and footer.
3. Set a border component in each section.
4. Apply margins to each border.
5. Launch the application and check it.

### Link to public reproduction project repository

[Link to the repository](https://github.com/MADSENSE/MADSENSE.MAUI.Sample.App/tree/border-margin-collectionView-header)

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 16.3

### Did you find any workaround?

If you set the border component inside a ContentView, works fine for me.

**Comment by PureWeen** [comment] 2023-12-12 19:10
Duplicate of #19240

**Closed by PureWeen** 2023-12-12 19:10 UTC
Labels: t/bug
