### ISSUE TITLE
Drag-and-drop problem

### ISSUE THREAD

**Issue by sunnamed434** [dotnet/maui#10701] opened 2022-10-15 11:11 UTC
### Description

First of all, drag-and-drop absolutely is not working, there is a problem with default Maui blazor NavMenu, when Im trying to hold the selected item in navmenu Im getting this problem which Im showing on video, full app is stuck and become too laggy

Small video that describes this: [Google Disk video](https://drive.google.com/file/d/13zxiIg4GkyZ4TPNqXEuiDKNLFPkYG6PL/view?usp=sharing)

### Steps to Reproduce

1. Hold item in NavMenu (drag-and-drop)
2. Start moving mouse
3. Try to click somewhere or move app window position
4. Reproduced

### Link to public reproduction project repository

https://github.com/sunnamed434/BitMono/tree/main/BitMono/BitMono.GUI

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 11

### Did you find any workaround?

No

**Comment by Redth** [comment] 2022-10-18 19:43
I'm not sure what you're trying to achieve here, could you please explain in more detail?

The webview content you are trying to drag and drop is not by default drag and drop enabled to do anything, so this is expected.

**Comment by sunnamed434** [comment] 2022-10-22 08:15
> I'm not sure what you're trying to achieve here, could you please explain in more detail?
> 
> The webview content you are trying to drag and drop is not by default drag and drop enabled to do anything, so this is expected.

As I show in video when Im trying to drag-and-drop something in application it freezes I cant even interact with it after that

**Comment by mkArtakMSFT** [comment] 2022-11-03 17:07
Potentially related: https://github.com/dotnet/maui/issues/7390

**Comment by mkArtakMSFT** [comment] 2024-04-05 20:38
Closing as a dupe of https://github.com/dotnet/maui/issues/2205

**Closed by mkArtakMSFT** 2024-04-05 20:38 UTC
Labels: t/bug, platform/windows 🪟, area/blazor 🕸️, s/triaged, discussed, Priority:1
