### ISSUE TITLE
Facing issue with firebase bitcode:App store denied my app show following error

### ISSUE THREAD

**Issue by vplife1** [dotnet/maui#18162] opened 2023-10-19 18:54 UTC
### Description

ITMS-90482: Invalid Executable - The executable 'TimeClockNow.Mobile.app/Frameworks/FBLPromises.framework/FBLPromises' contains bitcode.

ITMS-90482: Invalid Executable - The executable 'TimeClockNow.Mobile.app/Frameworks/FirebaseCore.framework/FirebaseCore' contains bitcode.

ITMS-90482: Invalid Executable - The executable 'TimeClockNow.Mobile.app/Frameworks/FirebaseCoreDiagnostics.framework/FirebaseCoreDiagnostics' contains bitcode.

ITMS-90482: Invalid Executable - The executable 'TimeClockNow.Mobile.app/Frameworks/FirebaseInstallations.framework/FirebaseInstallations' contains bitcode.

ITMS-90482: Invalid Executable - The executable 'TimeClockNow.Mobile.app/Frameworks/FirebaseMessaging.framework/FirebaseMessaging' contains bitcode.

ITMS-90482: Invalid Executable - The executable 'TimeClockNow.Mobile.app/Frameworks/GTMSessionFetcher.framework/GTMSessionFetcher' contains bitcode.

ITMS-90482: Invalid Executable - The executable 'TimeClockNow.Mobile.app/Frameworks/GoogleAPIClientForREST.framework/GoogleAPIClientForREST' contains bitcode.

ITMS-90482: Invalid Executable - The executable 'TimeClockNow.Mobile.app/Frameworks/GoogleDataTransport.framework/GoogleDataTransport' contains bitcode.

ITMS-90482: Invalid Executable - The executable 'TimeClockNow.Mobile.app/Frameworks/GoogleToolboxForMac.framework/GoogleToolboxForMac' contains bitcode.

ITMS-90482: Invalid Executable - The executable 'TimeClockNow.Mobile.app/Frameworks/GoogleUtilities.framework/GoogleUtilities' contains bitcode.

ITMS-90482: Invalid Executable - The executable 'TimeClockNow.Mobile.app/Frameworks/Protobuf.framework/Protobuf' contains bitcode.

ITMS-90482: Invalid Executable - The executable 'TimeClockNow.Mobile.app/Frameworks/leveldb.framework/leveldb' contains bitcode.

ITMS-90482: Invalid Executable - The executable 'TimeClockNow.Mobile.app/Frameworks/nanopb.framework/nanopb' contains bitcode.

### Version with bug

7.0.96

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

6.0

### Affected platforms

iOS

### Did you find any workaround?

Na

### Relevant log output

```shell
ITMS-90482: Invalid Executable - The executable 'TimeClockNow.Mobile.app/Frameworks/FBLPromises.framework/FBLPromises' contains bitcode.

ITMS-90482: Invalid Executable - The executable 'TimeClockNow.Mobile.app/Frameworks/FirebaseCore.framework/FirebaseCore' contains bitcode.

ITMS-90482: Invalid Executable - The executable 'TimeClockNow.Mobile.app/Frameworks/FirebaseCoreDiagnostics.framework/FirebaseCoreDiagnostics' contains bitcode.

ITMS-90482: Invalid Executable - The executable 'TimeClockNow.Mobile.app/Frameworks/FirebaseInstallations.framework/FirebaseInstallations' contains bitcode.

ITMS-90482: Invalid Executable - The executable 'TimeClockNow.Mobile.app/Frameworks/FirebaseMessaging.framework/FirebaseMessaging' contains bitcode.

ITMS-90482: Invalid Executable - The executable 'TimeClockNow.Mobile.app/Frameworks/GTMSessionFetcher.framework/GTMSessionFetcher' contains bitcode.

ITMS-90482: Invalid Executable - The executable 'TimeClockNow.Mobile.app/Frameworks/GoogleAPIClientForREST.framework/GoogleAPIClientForREST' contains bitcode.

ITMS-90482: Invalid Executable - The executable 'TimeClockNow.Mobile.app/Frameworks/GoogleDataTransport.framework/GoogleDataTransport' contains bitcode.

ITMS-90482: Invalid Executable - The executable 'TimeClockNow.Mobile.app/Frameworks/GoogleToolboxForMac.framework/GoogleToolboxForMac' contains bitcode.

ITMS-90482: Invalid Executable - The executable 'TimeClockNow.Mobile.app/Frameworks/GoogleUtilities.framework/GoogleUtilities' contains bitcode.

ITMS-90482: Invalid Executable - The executable 'TimeClockNow.Mobile.app/Frameworks/Protobuf.framework/Protobuf' contains bitcode.

ITMS-90482: Invalid Executable - The executable 'TimeClockNow.Mobile.app/Frameworks/leveldb.framework/leveldb' contains bitcode.

ITMS-90482: Invalid Executable - The executable 'TimeClockNow.Mobile.app/Frameworks/nanopb.framework/nanopb' contains bitcode.
```

**Comment by vplife1** [comment] 2023-10-23 11:20
@samirgcofficial @SotoiGhost  Can you please help me with the mentioned issue, I have tried your commented solution https://github.com/dotnet/maui/issues/10989#issuecomment-1304317816  but still i am facing the same issue . 
@akimotochan

**Comment by mattleibow** [comment] 2023-10-24 19:53
This appears to be an issue with the way the Firebase binaries are built. Can you reopen this issue on the Firebase bindings repository? https://github.com/xamarin/GoogleApisForiOSComponents

**Comment by TedMobile** [comment] 2023-10-25 04:15
We use Firebase for push notifications and we have not submitted the app yet and this Is very worrying. @vplife1 please submit to the https://github.com/xamarin/GoogleApisForiOSComponents. The chances of getting fixed may be slim but at least we have a chance.

**Comment by rolfbjarne** [comment] 2023-10-25 08:13
It looks like this is a duplicate of https://github.com/dotnet/maui/issues/12863, and it's being handled in the comments there, so I'm closing this.

**Closed by rolfbjarne** 2023-10-25 08:13 UTC
Labels: t/bug, s/duplicate 2️⃣, platform/iOS 🍎, s/needs-attention, partner/macios
