### ISSUE TITLE
[Android] ContentViewHandler is incompatible

### ISSUE THREAD

**Issue by Phenek** [dotnet/maui#7884] opened 2022-06-09 11:08 UTC
### Description

I'm testing MAUI about collection scroll etc...,
When I try to embed a page that contains a CarouselView control with some ContentView in it.

It crashes with the following exception:
Microsoft.Maui.Platform.ToPlatformException: 
'Microsoft.Maui.Handlers.ContentViewHandler found for Microsoft.Maui.Controls.ContentView is incompatible'. 
Only on Android I got this exception.

PS: I have a lot of similar issue about incompatible handlers with Button, Entries, etc...
When it's happen on iOS the page will just not render, but no crash no exception. It's just a guess.

### Steps to Reproduce

You can download my workplace project and run it.
[ScrollConflicts.zip](https://github.com/dotnet/maui/files/8869797/ScrollConflicts.zip)

On Android it will crash instantly, with the related exception.

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android

### Relevant log output
Download the project :)
[ScrollConflicts.zip](https://github.com/dotnet/maui/files/8869797/ScrollConflicts.zip)

**Comment by kristinx0211** [comment] 2022-06-10 01:43
error on android running:
![image](https://user-images.githubusercontent.com/99457000/172973302-043ed5a4-b795-4ad1-a23b-06297cdca659.png)
```
> am start -a "android.intent.action.MAIN" -c "android.intent.category.LAUNCHER" -n "com.companyname.scrollconflicts/crc6423b8bf1c258f833a.MainActivity"
> Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.companyname.scrollconflicts/crc6423b8bf1c258f833a.MainActivity }
Loaded assembly: /data/data/com.companyname.scrollconflicts/files/.__override__/ScrollConflicts.dll
Loaded assembly: /data/data/com.companyname.scrollconflicts/files/.__override__/Mono.Android.dll [External]
Loaded assembly: /data/data/com.companyname.scrollconflicts/files/.__override__/System.Runtime.dll [External]
Loaded assembly: /data/data/com.companyname.scrollconflicts/files/.__override__/Java.Interop.dll [External]
Loaded assembly: /data/data/com.companyname.scrollconflicts/files/.__override__/System.Collections.dll [External]
Resolved pending breakpoint for 'Android.Runtime.JNIEnv.RegisterJniNatives(System.IntPtr, System.Int32, System.IntPtr, System.IntPtr, System.Int32)' to /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNIEnv.cs:124 [0x00000].
Loaded assembly: /data/data/com.companyname.scrollconflicts/files/.__override__/System.Threading.dll [External]
Loaded assembly: /data/data/com.companyname.scrollconflicts/files/.__override__/System.Runtime.InteropServices.dll [External]
Loaded assembly: /data/data/com.companyname.scrollconflicts/files/.__override__/System.Threading.Thread.dll [External]
Loaded assembly: /data/data/com.companyname.scrollconflicts/files/.__override__/System.Diagnostics.StackTrace.dll [External]
Loaded assembly: data-0x7bb7262ae030 [External]
Loaded assembly: data-0x7bb7262ee070 [External]
Loaded assembly: data-0x7bb7d0832660 [External]
Loaded assembly: data-0x7bb7262de060 [External]
Loaded assembly: /data/data/com.companyname.scrollconflicts/files/.__override__/netstandard.dll [External]
Loaded assembly: /data/data/com.companyname.scrollconflicts/files/.__override__/System.Linq.dll [External]
Loaded assembly: /data/data/com.companyname.scrollconflicts/files/.__override__/System.Collections.Concurrent.dll [External]
Resolved pending breakpoint for 'Xamarin.HotReload.HotReloadAgent.BreakpointSendToIde(System.String)' to D:\a\_work\1\s\HotReload\Source\Xamarin.HotReload.Agent\HotReloadAgent.cs:419 [0x00000].
Loaded assembly: /data/data/com.companyname.scrollconflicts/files/.__override__/System.Text.Json.dll [External]
Loaded assembly: /data/data/com.companyname.scrollconflicts/files/.__override__/System.Text.Encodings.Web.dll [External]
Loaded assembly: /data/data/com.companyname.scrollconflicts/files/.__override__/System.ComponentModel.dll [External]
Loaded assembly: /data/data/com.companyname.scrollconflicts/files/.__override__/Microsoft.Maui.Controls.dll [External]
[scrollconflict] Late-enabling -Xcheck:jni
[scrollconflict] Unexpected CPU variant for X86 using defaults: x86_64
[CompatibilityChangeReporter] Compat change id reported: 171979766; UID 10151; state: ENABLED
[GraphicsEnvironment] ANGLE Developer option for 'com.companyname.scrollconflicts' set to: 'default'
[GraphicsEnvironment] Neither updatable production driver nor prerelease driver is supported.
[NetworkSecurityConfig] No Network Security Config specified, using platform default
[NetworkSecurityConfig] No Network Security Config specified, using platform default
[debug-app-helper] Checking if libmonodroid was unpacked to /data/app/~~nTgeW7iWGd9TV-vwGnJ8-Q==/com.companyname.scrollconflicts-FdSVFAkeXcsiTzmrlC9QaA==/lib/x86_64/libmonodroid.so
[debug-app-helper] Native libs extracted to /data/app/~~nTgeW7iWGd9TV-vwGnJ8-Q==/com.companyname.scrollconflicts-FdSVFAkeXcsiTzmrlC9QaA==/lib/x86_64, assuming application/android:extractNativeLibs == true
[debug-app-helper] Setting up for DSO lookup in app data directories
[debug-app-helper] Added filesystem DSO lookup location: /data/app/~~nTgeW7iWGd9TV-vwGnJ8-Q==/com.companyname.scrollconflicts-FdSVFAkeXcsiTzmrlC9QaA==/lib/x86_64
[debug-app-helper] Using runtime path: /data/app/~~nTgeW7iWGd9TV-vwGnJ8-Q==/com.companyname.scrollconflicts-FdSVFAkeXcsiTzmrlC9QaA==/lib/x86_64
[debug-app-helper] checking directory: `/data/user/0/com.companyname.scrollconflicts/files/.__override__/lib`
[debug-app-helper] directory does not exist: `/data/user/0/com.companyname.scrollconflicts/files/.__override__/lib`
[debug-app-helper] Checking whether Mono runtime exists at: /data/user/0/com.companyname.scrollconflicts/files/.__override__/libmonosgen-2.0.so
[debug-app-helper] Checking whether Mono runtime exists at: /data/app/~~nTgeW7iWGd9TV-vwGnJ8-Q==/com.companyname.scrollconflicts-FdSVFAkeXcsiTzmrlC9QaA==/lib/x86_64/libmonosgen-2.0.so
[debug-app-helper] Mono runtime found at: /data/app/~~nTgeW7iWGd9TV-vwGnJ8-Q==/com.companyname.scrollconflicts-FdSVFAkeXcsiTzmrlC9QaA==/lib/x86_64/libmonosgen-2.0.so
[scrollconflict] Attempt to remove non-JNI local reference, dumping thread
[DOTNET] JNI_OnLoad: JNI_OnLoad in pal_jni.c
[monodroid] Creating public update directory: `/data/user/0/com.companyname.scrollconflicts/files/.__override__`
[scrollconflict] Attempt to remove non-JNI local reference, dumping thread
[monodroid-debug] Trying to initialize the debugger with options: --debugger-agent=transport=dt_socket,loglevel=0,address=10.0.2.2:63592,embedding=1
[monodroid-assembly] open_from_bundles: failed to load assembly ScrollConflicts.dll
[monodroid-gc] GREF GC Threshold: 46080
[monodroid-assembly] open_from_bundles: failed to load assembly Mono.Android.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Runtime.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Java.Interop.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Collections.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Threading.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Runtime.InteropServices.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Threading.Thread.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Diagnostics.StackTrace.dll
[scrollconflict] Attempt to remove non-JNI local reference, dumping thread
[monodroid-assembly] open_from_bundles: failed to load assembly netstandard.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Linq.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.VisualStudio.DesignTools.TapContract.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.VisualStudio.DesignTools.TapContract.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.HotReload.Contracts.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.HotReload.Contracts.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Collections.Concurrent.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Text.Json.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Text.Encodings.Web.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.ComponentModel.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Maui.Controls.dll
Loaded assembly: /data/data/com.companyname.scrollconflicts/files/.__override__/System.ObjectModel.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.HotReload.Contracts.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.HotReload.Contracts.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.VisualStudio.DesignTools.TapContract.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.VisualStudio.DesignTools.TapContract.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.ObjectModel.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Maui.dll
Loaded assembly: /data/data/com.companyname.scrollconflicts/files/.__override__/Microsoft.Maui.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Maui.Graphics.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Maui.Essentials.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Extensions.Logging.Abstractions.dll
Loaded assembly: /data/data/com.companyname.scrollconflicts/files/.__override__/Microsoft.Maui.Graphics.dll [External]
Loaded assembly: /data/data/com.companyname.scrollconflicts/files/.__override__/Microsoft.Maui.Essentials.dll [External]
Loaded assembly: /data/data/com.companyname.scrollconflicts/files/.__override__/Microsoft.Extensions.Logging.Abstractions.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly System.ComponentModel.TypeConverter.dll
Loaded assembly: /data/data/com.companyname.scrollconflicts/files/.__override__/System.ComponentModel.TypeConverter.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly System.Private.Uri.dll
Loaded assembly: /data/data/com.companyname.scrollconflicts/files/.__override__/System.Private.Uri.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly System.Runtime.Loader.dll
Loaded assembly: /data/data/com.companyname.scrollconflicts/files/.__override__/System.Runtime.Loader.dll [External]
Resolved pending breakpoint for 'Xamarin.HotReload.HotReloadAgent.BreakpointCheckpoint()' to D:\a\_work\1\s\HotReload\Source\Xamarin.HotReload.Agent\HotReloadAgent.cs:414 [0x00000].
[monodroid-assembly] open_from_bundles: failed to load assembly System.Memory.dll
Loaded assembly: /data/data/com.companyname.scrollconflicts/files/.__override__/System.Memory.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly System.Reflection.Emit.Lightweight.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Reflection.Emit.ILGeneration.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Reflection.Primitives.dll
Loaded assembly: /data/data/com.companyname.scrollconflicts/files/.__override__/System.Reflection.Emit.Lightweight.dll [External]
Loaded assembly: /data/data/com.companyname.scrollconflicts/files/.__override__/System.Reflection.Emit.ILGeneration.dll [External]
Loaded assembly: /data/data/com.companyname.scrollconflicts/files/.__override__/System.Reflection.Primitives.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly System.Runtime.CompilerServices.Unsafe.dll
Loaded assembly: /data/data/com.companyname.scrollconflicts/files/.__override__/System.Runtime.CompilerServices.Unsafe.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.Core.dll
Loaded assembly: /data/data/com.companyname.scrollconflicts/files/.__override__/Xamarin.AndroidX.Core.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Extensions.DependencyInjection.Abstractions.dll
Loaded assembly: /data/data/com.companyname.scrollconflicts/files/.__override__/Microsoft.Extensions.DependencyInjection.Abstractions.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Maui.Controls.Xaml.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Extensions.Configuration.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Extensions.Configuration.Abstractions.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Extensions.Logging.dll
Loaded assembly: /data/data/com.companyname.scrollconflicts/files/.__override__/Microsoft.Maui.Controls.Xaml.dll [External]
Loaded assembly: /data/data/com.companyname.scrollconflicts/files/.__override__/Microsoft.Extensions.Configuration.dll [External]
Loaded assembly: /data/data/com.companyname.scrollconflicts/files/.__override__/Microsoft.Extensions.Configuration.Abstractions.dll [External]
Loaded assembly: /data/data/com.companyname.scrollconflicts/files/.__override__/Microsoft.Extensions.Logging.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.AppCompat.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.Google.Android.Material.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.SwipeRefreshLayout.dll
Loaded assembly: /data/data/com.companyname.scrollconflicts/files/.__override__/Xamarin.AndroidX.AppCompat.dll [External]
Loaded assembly: /data/data/com.companyname.scrollconflicts/files/.__override__/Xamarin.Google.Android.Material.dll [External]
Loaded assembly: /data/data/com.companyname.scrollconflicts/files/.__override__/Xamarin.AndroidX.SwipeRefreshLayout.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.Fragment.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.Activity.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.Lifecycle.ViewModel.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.Lifecycle.Common.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.SavedState.dll
Loaded assembly: /data/data/com.companyname.scrollconflicts/files/.__override__/Xamarin.AndroidX.Fragment.dll [External]
Loaded assembly: /data/data/com.companyname.scrollconflicts/files/.__override__/Xamarin.AndroidX.Activity.dll [External]
Loaded assembly: /data/data/com.companyname.scrollconflicts/files/.__override__/Xamarin.AndroidX.Lifecycle.ViewModel.dll [External]
Loaded assembly: /data/data/com.companyname.scrollconflicts/files/.__override__/Xamarin.AndroidX.Lifecycle.Common.dll [External]
Loaded assembly: /data/data/com.companyname.scrollconflicts/files/.__override__/Xamarin.AndroidX.SavedState.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.DrawerLayout.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.CustomView.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.Navigation.Runtime.dll
Loaded assembly: /data/data/com.companyname.scrollconflicts/files/.__override__/Xamarin.AndroidX.DrawerLayout.dll [External]
Loaded assembly: /data/data/com.companyname.scrollconflicts/files/.__override__/Xamarin.AndroidX.CustomView.dll [External]
Loaded assembly: /data/data/com.companyname.scrollconflicts/files/.__override__/Xamarin.AndroidX.Navigation.Runtime.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly System.Net.Primitives.dll
Loaded assembly: /data/data/com.companyname.scrollconflicts/files/.__override__/System.Net.Primitives.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Extensions.DependencyInjection.dll
Loaded assembly: /data/data/com.companyname.scrollconflicts/files/.__override__/Microsoft.Extensions.DependencyInjection.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly System.Diagnostics.Tracing.dll
Loaded assembly: /data/data/com.companyname.scrollconflicts/files/.__override__/System.Diagnostics.Tracing.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly System.Xml.ReaderWriter.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Private.Xml.dll
Loaded assembly: /data/data/com.companyname.scrollconflicts/files/.__override__/System.Xml.ReaderWriter.dll [External]
Loaded assembly: /data/data/com.companyname.scrollconflicts/files/.__override__/System.Private.Xml.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly System.Text.Encoding.Extensions.dll
Loaded assembly: /data/data/com.companyname.scrollconflicts/files/.__override__/System.Text.Encoding.Extensions.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly System.Text.RegularExpressions.dll
Loaded assembly: /data/data/com.companyname.scrollconflicts/files/.__override__/System.Text.RegularExpressions.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly System.Numerics.Vectors.dll
Loaded assembly: /data/data/com.companyname.scrollconflicts/files/.__override__/System.Numerics.Vectors.dll [External]
[scrollconflict] Explicit concurrent copying GC freed 546(77KB) AllocSpace objects, 0(0B) LOS objects, 24% free, 1969KB/2626KB, paused 411us,69us total 3.924ms
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.RecyclerView.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.CardView.dll
Loaded assembly: /data/data/com.companyname.scrollconflicts/files/.__override__/Xamarin.AndroidX.RecyclerView.dll [External]
Loaded assembly: /data/data/com.companyname.scrollconflicts/files/.__override__/Xamarin.AndroidX.CardView.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.Loader.dll
[libEGL] loaded /vendor/lib64/egl/libEGL_emulation.so
Loaded assembly: /data/data/com.companyname.scrollconflicts/files/.__override__/Xamarin.AndroidX.Loader.dll [External]
[libEGL] loaded /vendor/lib64/egl/libGLESv1_CM_emulation.so
[libEGL] loaded /vendor/lib64/egl/libGLESv2_emulation.so
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Maui.Controls.Compatibility.dll
Loaded assembly: /data/data/com.companyname.scrollconflicts/files/.__override__/Microsoft.Maui.Controls.Compatibility.dll [External]
Thread started:  #2
Thread started:  #3
Thread started:  #4
[monodroid-assembly] open_from_bundles: failed to load assembly System.Runtime.Serialization.Json.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Private.DataContractSerialization.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Runtime.Serialization.Xml.dll
Loaded assembly: /data/data/com.companyname.scrollconflicts/files/.__override__/System.Runtime.Serialization.Json.dll [External]
Loaded assembly: /data/data/com.companyname.scrollconflicts/files/.__override__/System.Private.DataContractSerialization.dll [External]
Loaded assembly: /data/data/com.companyname.scrollconflicts/files/.__override__/System.Runtime.Serialization.Xml.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly System.Runtime.Serialization.Primitives.dll
Loaded assembly: /data/data/com.companyname.scrollconflicts/files/.__override__/System.Runtime.Serialization.Primitives.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.CoordinatorLayout.dll
Loaded assembly: /data/data/com.companyname.scrollconflicts/files/.__override__/Xamarin.AndroidX.CoordinatorLayout.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.Lifecycle.LiveData.Core.dll
Loaded assembly: /data/data/com.companyname.scrollconflicts/files/.__override__/Xamarin.AndroidX.Lifecycle.LiveData.Core.dll [External]
[scrollconflict] Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (unsupported, reflection, allowed)
[scrollconflict] Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (unsupported, reflection, allowed)
Thread started: .NET Timers #5
[scrollconflict] Explicit concurrent copying GC freed 453(90KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 3007KB/6014KB, paused 509us,66us total 6.919ms
[monodroid-assembly] open_from_bundles: failed to load assembly System.Linq.Expressions.dll
Loaded assembly: /data/data/com.companyname.scrollconflicts/files/.__override__/System.Linq.Expressions.dll [External]
[HostConnection] createUnique: call
[HostConnection] HostConnection::get() New Host Connection established 0x7bb5b629dc50, tid 20349
[HostConnection] HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings 
```ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV_Cache ANDROID_EMU_vulkan_ignored_handles ANDROID_EMU_has_shared_slots_host_memory_allocator ANDROID_EMU_vulkan_free_memory_sync ANDROID_EMU_vulkan_shader_float16_int8 ANDROID_EMU_vulkan_async_queue_submit ANDROID_EMU_vulkan_queue_submit_with_commands ANDROID_EMU_sync_buffer_data ANDROID_EMU_read_color_buffer_dma GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_gles_max_version_2 
[OpenGLRenderer] Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
[OpenGLRenderer] Failed to initialize 101010-2 format, error = EGL_SUCCESS
[EGL_emulation] eglCreateContext: 0x7bb5b629d350: maj 2 min 0 rcv 2
[EGL_emulation] eglMakeCurrent: 0x7bb5b629d350: ver 2 0 (tinfo 0x7bb7dcf65080) (first time)
[Gralloc4] mapper 4.x is not supported
[HostConnection] createUnique: call
[HostConnection] HostConnection::get() New Host Connection established 0x7bb5b629f810, tid 20349
[goldfish-address-space] allocate: Ask for block of size 0x100
[goldfish-address-space] allocate: ioctl allocate returned offset 0x3f3ffe000 size 0x2000
[Gralloc4] allocator 4.x is not supported
[HostConnection] HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV_Cache ANDROID_EMU_vulkan_ignored_handles ANDROID_EMU_has_shared_slots_host_memory_allocator ANDROID_EMU_vulkan_free_memory_sync ANDROID_EMU_vulkan_shader_float16_int8 ANDROID_EMU_vulkan_async_queue_submit ANDROID_EMU_vulkan_queue_submit_with_commands ANDROID_EMU_sync_buffer_data ANDROID_EMU_read_color_buffer_dma GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_gles_max_version_2 
**Microsoft.Maui.Platform.ToPlatformException:** 'Microsoft.Maui.Handlers.ContentViewHandler found for Microsoft.Maui.Controls.ContentView is incompatible'

**Comment by RemcoDEV** [comment] 2022-06-15 07:20
We experience the same issue when using the new MAUI workload shipped with the latest VS 2022 preview.

**Comment by Phenek** [comment] 2022-06-15 14:39
@jsuarezruiz Thanks a lot!

PS: But I don't understand why this view has a parent before add it for first time.

**Comment by Phenek** [comment] 2022-06-26 13:44
if the issue is related to CollectionView, 
that could explain why in iOS the CollectionView is not populated rather than trowing the same exception.

**Comment by PureWeen** [comment] 2022-08-30 21:03
This is a duplicate of this issue

https://github.com/dotnet/maui/issues/9744

You can't use another `View` as your ItemSource

What you might want here is a DataTemplateSelector and then based on whatever is bound to your CarouselView you would return the DataTemplate you want to use.

**Comment by KPHIBYE** [comment] 2022-08-30 21:57
@PureWeen I'm not sure if you were referring to me, but I want to use a collection of Views as ItemsSource and not just a single View and all Views are of the same Type and supposed to look the same, so no DataTemplateSelector should be necessary.

**Comment by PureWeen** [comment] 2022-08-30 23:02
@KPHIBYE you can't currently use a collection of views as an ItemSource. Because of how the CarouselView works you might have a scenario where one of the elements inside your ItemSource is bound to two different created DataTemplates. So now that view has to exist two different places. You can't reuse a view two different places otherwise you'll get the exception indicated here. 

The ItemSource is meant to purely be data, and then you bind that data to your DataTemplate. 

So in your scenario you would need to do something like this instead (not sure if the syntax for the array I've done here is 100 percent correct)

```XAML
<CarouselView Loop="True">
    <CarouselView.ItemsSource>
        <x:Array Type="{x:Type string}">
             "Item 1"
            "Item 2"
        </x:Array>
    </CarouselView.ItemsSource>
    <CarouselView.ItemTemplate>
        <DataTemplate>
            <ContentView>
                       <Label Text="{Binding}" />
            </ContentView>
        </DataTemplate>
    </CarouselView.ItemTemplate>
</CarouselView>
```

Pinging @rmarinho  just in case I'm stating anything here incorrectly.

**Comment by Phenek** [comment] 2022-08-31 07:25
Okay thanks @PureWeen, I understand the issue.
I will use TemplateSelector for best practise, 
even if I use to do it like so, with Xamarin and the two popular Carousel librairies on Xamarin.

PS: For a speed workaround making Loop="False", compile and run very well for me.

**Comment by KPHIBYE** [comment] 2022-08-31 07:33
@PureWeen thanks for the clarification and the explanation of the problem. I just want to ask two additional questions:

1. Is the inability to use a collection of Views as ItemsSource a bug since this was possible on Xamarin.Forms?
2. Is `Loop="False"` a viable workaround that will last, or "undefined behavior" that could change with any new release?

**Comment by PureWeen** [comment] 2022-09-01 14:18
> @PureWeen thanks for the clarification and the explanation of the problem. I just want to ask two additional questions:
> 
> 1. Is the inability to use a collection of Views as ItemsSource a bug since this was possible on Xamarin.Forms?

We'll need to investigate this one a bit more. 
FYI  @rmarinho

**Comment by PureWeen** [comment] 2022-09-01 20:14
> I think the issue is we now reuse the handler of the view, and before we were always creating a new Renderer for the view .. https://github.com/xamarin/Xamarin.Forms/blob/5.0.0/Xamarin.Forms.Platform.Android/CollectionView/ItemContentView.cs#L128

@KPHIBYE it's a bit of an unfortunate circumstance. Technically this worked in XF but it really shouldn't have worked :-/ In XF it would create another renderer for the same view, so the same cross platform view would effectively have two renderers. The xplat view would only know about the latest renderer and the older renderer wouldn't really know that it was no longer top dog. 

This usually worked ok but when it stopped working it would fail in really confusing ways where the renderers would effectively start fighting each other.

**Closed** 2024-05-31 21:44 UTC
Labels: t/bug, platform/android 🤖, p/1, legacy-area-controls, migration-compatibility
