### ISSUE TITLE
[Bug] `Layout.ChildAdded` Does Not Fire When a Child is Added to a `Layout`

### ISSUE THREAD

**Issue by brminnick** [dotnet/maui#3309] opened 2021-11-09 04:18 UTC
### Description

In .NET MAUI v6.0.100, the  `Layout.ChildAdded` event does not fire when an `IView` is added to a `Layout` like a `Grid` or a `StackLayout`.

```cs
protected override void OnAppearing()
{
  base.OnAppearing();

  var stackLayout = new StackLayout();
  stackLayout.ChildAdded += HandleChildAdded
    
  stackLayout.Children.Add(new BoxView()); // `ChildAdded` does not fire
}

// This Event Handler Does Not Execute because `ChildAdded` does not fire
async void HandleChildAdded(object sender, ElementEventArgs e) =>
 await DisplayAlert("Child Added", $"Added a {e.Element.GetType().FullName}", "OK");
```

### Steps to Reproduce

0. [Install .NET MAUI](https://docs.microsoft.com/dotnet/maui/get-started/installation?WT.mc_id=mobile-0000-bramin)
1. Download/Clone this repo: https://github.com/brminnick/LayoutChildAddedRepro
2. In `MainPage.xaml`, confirm [`ChildAdded` is subscribed to `HandleChildAdded`](https://github.com/brminnick/LayoutChildAddedRepro/blob/f8447fb97dd1926395ff30821cd76948906f31c0/MainPage.xaml#L8)
3. In `MainPage.xaml.cs`, confirm [`OnAppearing` triggers the following `DisplayAlert`:](https://github.com/brminnick/LayoutChildAddedRepro/blob/5ab4b08f25d7b4f920f751c78ec821e177dabb2c/MainPage.xaml.cs#L22)
   ```cs
   await DisplayAlert("OnAppearing Fired", "Click OK to add a Green Box View", "OK");
   ```
4. In `MainPage.OnAppearing`, confirm a [green `BoxView` is added to the `Grid](https://github.com/brminnick/LayoutChildAddedRepro/blob/5ab4b08f25d7b4f920f751c78ec821e177dabb2c/MainPage.xaml.cs#L28):
   ```cs
   var greenBox = new BoxView { BackgroundColor = Colors.Green };
   GridLayout.SetRow(greenBox, 1);
   GridLayout.SetColumn(greenBox, 0);

   MainGrid.Add(greenBox);
   ```
5. Confirm [`HandleChildAdded` triggers `DisplayAlert`](https://github.com/brminnick/LayoutChildAddedRepro/blob/5ab4b08f25d7b4f920f751c78ec821e177dabb2c/MainPage.xaml.cs#L33):
   ```cs
   async void HandleChildAdded(object sender, ElementEventArgs e)
   {
     await DisplayAlert("Child Added", $"Added a {e.Element.GetType().FullName}", "OK");
   }
   ```
6. In the terminal, navigate to the downloaded `LayoutChildAddedRepro` repo
7. In the terminal, run `LayoutChildAddedRepro.sln` by entering the following command for your specific simulator/device
   - iOS: `dotnet build -t:run -f:net6.0-ios`
   - Android: `dotnet build -t:run -f:net6.0-android`
   - MacCatalyst: `dotnet build -t:run -f:net6.0-maccatalyst`
8. In the simulator/device, confirm the `DisplayAlert` appears
<img width="250" alt="image" src="https://user-images.githubusercontent.com/13558917/140859648-4e4c3ce8-b50a-4d8e-b63b-d51b9c8802c8.png">

9. In the simulator, click **OK**
10. In the simulator, confirm a Green Box is added to `MainPage`
<img width="250" alt="image" src="https://user-images.githubusercontent.com/13558917/140859710-aaa65dbb-8814-4c91-83f2-eba4b2d84c1f.png">

13. In the simulator, confirm the second `DisplayAlert` does _not_ appear
   - If `ChildAdded` fires, a second `DisplayAlert` should appear, but `ChildAdded` does not fire

### Expected Behavior

When an event handler is subscribed to `ChildAdded`, and a child is then added to that `Layout`, the `ChildAdded` event should fire

### Actual Behavior

When an event handler is subscribed to `ChildAdded`, and a child is then added to that `Layout`, the `ChildAdded` does _not_ should fire

### Basic Information

- Version with issue:  .NET MAUI v6.0.100
- Last known good version: Unknown
- IDE: VS Code
- Platform Target Frameworks: 
  - iOS:  14.2
  - Android: 21.0
  - MacCatalyst: 14.0
  - UWP:  10.0.17763.0

### Reproduction Link

https://github.com/brminnick/LayoutChildAddedRepro

### Workaround

None

**Comment by brminnick** [comment] 2021-11-09 04:22
I've also confirmed that `Layout.ChildRemoved` also does not fire when a child is removed from a `Layout`

**Comment by hartez** [comment] 2021-11-09 17:20
Duplicate of #3229

**Closed by hartez** 2021-11-09 17:20 UTC
Labels: t/bug, area/layout 🔲
