### ISSUE TITLE
[Android] BoxView Fails to Block Input Events When InputTransparent is Set to False

### ISSUE THREAD

**Issue by nivetha-nagalingam** [dotnet/maui#26019] opened 2024-11-21 11:22 UTC
### Description

When using a BoxView as an overlay with `InputTransparent` set to `false`, the underlying touch remains fully interactive. Instead of blocking the touch, the button continues to respond to clicks, causing unexpected behavior. 

https://github.com/user-attachments/assets/5e56913f-f1da-4731-b8c2-3a38a273ff77

### Steps to Reproduce

- Launch the application
- Click "Press me" button
- Again click "Blocked" button
- Observe the button's behavior
- Expected : No "Guess Not" text change should occur
- [BoxViewIssue.zip](https://github.com/user-attachments/files/17844814/BoxViewIssue.zip)

### Version with bug

9.0.0 GA

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11 and Up

### Relevant log output

```shell

```

**Comment by kubaflo** [comment] 2024-11-21 18:36
Duplicate of https://github.com/dotnet/maui/issues/26026

**Closed by kubaflo** 2024-11-21 18:36 UTC
Labels: t/bug
