### ISSUE TITLE
FontImage glyphs are clipped on Android

### ISSUE THREAD

**Issue by MV10** [dotnet/maui#16880] opened 2023-08-20 16:29 UTC
### Description

I am using glyphs from the popular mono/icon [BitstromWeraSansMono](https://www.nerdfonts.com/font-downloads) font, which is free from NerdFonts. These work fine on Windows builds, but on Android they're all clipped. This happens regardless of the size. You can see the problem with the "+" icon at the right. It's size 22 in the first image, and size 12 in the second image. The third image is how it appears on Windows. Glyphs are clipped on tabs, buttons, etc. -- everywhere.

![image](https://github.com/dotnet/maui/assets/794270/853b14a4-c642-4ea7-b77f-1023f4f07346)

![image](https://github.com/dotnet/maui/assets/794270/f23d0f2b-630b-46d1-901c-ad3cb772bf6a)

![image](https://github.com/dotnet/maui/assets/794270/22388c53-d076-4417-bb9a-abeb00350136)

Some buttons exhibiting the problem, and the correct Windows equivalent:

![image](https://github.com/dotnet/maui/assets/794270/3b8a173d-1e1b-4ff4-b896-c7e9b7bbf6a9)

![image](https://github.com/dotnet/maui/assets/794270/352d3240-a0b7-46a8-a70a-a40b530520be)

### Steps to Reproduce

Repro is to simply use `FontImage` with a glyph.

```xaml
<ContentPage.ToolbarItems>
    <ToolbarItem Text="Add" 
                  Clicked="Add_Clicked" 
                  IconImageSource="{FontImage FontFamily='MonoGlyph', Glyph='&#xf055;', Color=White, Size=22}" />
</ContentPage.ToolbarItems>
```

### Version with bug

7.0.86

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

**Comment by MV10** [comment] 2023-08-21 08:55
@drastications No. The repro is trivial and it's already in the bug report. I refuse to waste my time creating a repro when all you need to do is cut-and-paste from the bug report.

You folks are closing _legitimate_ bug reports left and right with that s/needs-repro nonsense. It is disrespectful to those of us who go to the trouble to triage and report issues, and it reduces product quality. It is understandable for complex or unclear problems, but, no, this isn't an example of that and I won't create a repro.

**Comment by Transis-Felipe** [comment] 2023-08-22 14:28
@MV10 Agree with you.
Bots are closing bugs without not even take a human look.

**Comment by jfversluis** [comment] 2024-02-21 11:55
> I refuse to waste my time creating a repro when all you need to do is cut-and-paste from the bug report.

Allow me to offer our point of view, I could also argue the other way around: we as he development team are now potentially spending time on trying to figure out what your code looks like, while we could spend that time actually fixing the bug if we would have a reproduction that shows us immediately what is going wrong.

Yes, it is copy and paste, but creating a new project, copying and pasting, downlading the font, having to add the code to register the font, run the app on different platforms and potentially find that whatever you are seeing is not what we are seeing can easily take a couple of minutes and more likely up to 30 minutes all things considered. That amount of minutes times the volume of reports we see coming in here is a lot of time we spend just trying to reproduce problems that you already have the code for on your machine.

To me an open-source project is all about collaboration. We don't expect you to do the work yourself, but if you encounter something it would be super helpful to provide us with all the information necessary to come to a diagnosis quickly and then a fix hopefully shortly after.

Having all that said, it happens a lot that when people actually put together a reproduction they find out that it's actually caused by something in their own code. At the very least it will help identify all the moving parts at work here that influence this behavior and will help us get to the root cause.

All the hows and whys are outlined in a document we have [here](https://github.com/dotnet/maui/blob/main/.github/repro.md).

I hope that will make you understand better from our side of things 😊

But to also offer something of value here, I did spend this time in this case and try to reproduce with the latest available public version. I [attached the project](https://github.com/dotnet/maui/files/14359031/repro16880.zip) for reference. Here is the output, it seems to all work on my end! 

![image](https://github.com/dotnet/maui/assets/939291/e8706100-0a98-43b5-b800-dd6b73711b7a)

Hopefully that means we managed to fix this in the meantime for you. If you still see this behavior, please feel free to open a new issue, take the attached reproduction code and add the things that are specific to your project that will make this behavior show up.

Thanks!

**Closed by jfversluis** 2024-02-21 11:55 UTC
Labels: t/bug, platform/android 🤖, area/fonts 🅰️, s/triaged, s/needs-attention
