### ISSUE TITLE
MacCatalyst: Tooltips are not working properly

### ISSUE THREAD

**Issue by danies8** [dotnet/maui#24671] opened 2024-09-09 10:17 UTC
### Description

I'm in net 8. and i'm using ToolTipProperties.Text
and is work after long time and not work when I change it runtime.

### Steps to Reproduce

Steps to Reproduce

1.Create a new MAUI app
2.Add a tooltip with ToolTipProperties.Text="Hello" on any control
3.Run on MacCatalyst
4.Hover or long click and observe, **tooltip are late.**
5.If you change it's value **in runtime is no effect**.

Main Page
=======
```xaml
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="ToolTipMacSample.MainPage">
 
    <ScrollView>
<VerticalStackLayout
            Padding="30,0"
            Spacing="25">
<Image
                Source="dotnet_bot.png"
                HeightRequest="185"
                Aspect="AspectFit"
                SemanticProperties.Description="dot net bot in a race car number eight" />
 
            <Label
                Text="Hello, World!"
                ToolTipProperties.Text="{Binding MyProperty}"
                Style="{StaticResource Headline}"
                SemanticProperties.HeadingLevel="Level1" />
 
            <Label
                ToolTipProperties.Text="{Binding MyProperty}"
                Text="Welcome to &#10;.NET Multi-platform App UI"
                Style="{StaticResource SubHeadline}"
                SemanticProperties.HeadingLevel="Level2"
                SemanticProperties.Description="Welcome to dot net Multi platform App U I" />
 
            <Button  ToolTipProperties.Text="{Binding MyProperty}"
                x:Name="CounterBtn"
                Text="Click me" 
                SemanticProperties.Hint="Counts the number of times you click"
                Clicked="OnCounterClicked"
                HorizontalOptions="Fill" />
</VerticalStackLayout>
</ScrollView>
 
</ContentPage>
```

```cs
public partial class MainPage : ContentPage
{
	public string MyProperty { get; set; } = "3333333";
 
	public MainPage()
	{
		InitializeComponent();
		this.BindingContext = this;
	}
 
	private void OnCounterClicked(object sender, EventArgs e)
	{
		this.MyProperty = "555555";
	}

```

### Version with bug

9.0.0-preview.6.24327.7

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

.....

### Did you find any workaround?

.....

### Relevant log output

```shell
......
```

**Comment by danies8** [comment] 2024-09-09 10:18
See also:
https://learn.microsoft.com/en-us/answers/questions/2028467/maccatalyst-tooltips-are-not-functional?page=1&orderby=Helpful&comment=answer-1814359#newest-answer-comment

**Comment by danies8** [comment] 2024-09-09 11:53
The workaround not working with DATATEMAPLTE.
Also If you change it's value in runtime is no effect.

**Comment by mattleibow** [comment] 2024-09-12 19:01
duplicate of https://github.com/dotnet/maui/issues/22322

**Closed by mattleibow** 2024-09-12 19:01 UTC
Labels: t/bug, platform/macOS 🍏, s/verified, area-controls-general, s/triaged

**Comment by danies8** [comment] 2024-09-12 19:22
@mattleibow 
Does tooltip not change if it change in runtime
does this was also fixed. 
You can see my sample code. (5)
