### ISSUE TITLE
Pull to refresh on RefreshView does not hide the refresh indicator.

### ISSUE THREAD

**Issue by RonnyRos** [dotnet/maui#8926] opened 2022-07-22 12:32 UTC
### Description

Drag down to refresh in refreshview does not update UI properly.

### Steps to Reproduce

When you pull down to refresh and you instead of releasing, drag up again and let go, the refresh indicator bubble is still showing.

### Version with bug

6.0.408 (current)

### Last version that worked well

6.0.400

### Affected platforms

Android

### Affected platform versions

Android 12

### Did you find any workaround?

No

**Comment by jfversluis** [comment] 2022-07-22 14:52
Does this only happen on Android? Were you able to test any more platforms by any chance? Do you have any relevant code that you are using?

It might seem trivial, but it might help seeing what is the cause of the potential issue here :) Thanks!

**Comment by softlion** [comment] 2022-07-24 09:27
This issue appears when using a OneWay binding mode for the IsRefreshing property like this, to fully control the apparing/disappearing of the refresh control.

```xaml
<RefreshView IsRefreshing="{Binding IsRefreshing, Mode=OneWay}" Command="{Binding RefreshCommand}" RefreshColor="{DynamicResource InvertedErrorForeground}">
...
```

```c#
        public ICommand RefreshCommand => MakeCommand(async () =>
        {
            if (!IsRefreshing)
            {
                IsRefreshing = true;
                try
                {
                    await bs.RefreshDataFromApi();
                }
                finally
                {
                    IsRefreshing = false;
                }
            }
        });
```

This permits the use of a timer which can automatically triggers the refresh control, along with manual refresh.


Using the following code fix the issue and work as expected. It is also better to not display this refreshing indicator when a timer is already refreshing the underlying data.

```xaml
<RefreshView IsRefreshing="{Binding IsRefreshing}" Command="{Binding RefreshCommand}" RefreshColor="{DynamicResource InvertedErrorForeground}">
...
```

```c#
        public ICommand RefreshCommand => MakeCommand(async () =>
        {
                try
                {
                    await bs.RefreshDataFromApi();
                }
                finally
                {
                    IsRefreshing = false;
                }
        });
```

**Comment by RonnyRos** [comment] 2022-07-26 12:18
Source: [refreshview_hanging.zip](https://github.com/dotnet/maui/files/9189655/refreshview_hanging.zip)
Video zipped (10MB limit thats why): [refreshview.zip](https://github.com/dotnet/maui/files/9189663/refreshview.zip)

**Comment by Dreamescaper** [comment] 2022-07-26 21:32
>         public ICommand RefreshCommand => MakeCommand(async () =>
>         {
>             if (!IsRefreshing)
>             {
>                 IsRefreshing = true;
>                 try
>                 {
>                     await bs.RefreshDataFromApi();
>                 }
>                 finally
>                 {
>                     IsRefreshing = false;
>                 }
>             }
>         });


When you pull to refresh, IsRefreshing property is set to `true`. Since it's `true`, it never passes that `if` condition, and therefore `IsRefreshing` is never set to false. That's why it never stops spinning.

**Comment by ultracoolbru** [comment] 2022-10-18 11:11
Good day, this issue definitely still exists in the latest release of the app. When running on Android emulator, the indicator stays and no matter what mode is used, it still does the same thing.

I am using the same sample to that from James' 4 hour tutorial on YouTube (https://www.youtube.com/watch?v=DuNLR_NJv8U&t=253s)

```
<RefreshView Grid.ColumnSpan="2" Command="{Binding GetMonkeysCommand}" IsRefreshing="{Binding IsRefreshing">
            <CollectionView BackgroundColor="Transparent" Grid.ColumnSpan="2" ItemsSource="{Binding Monkeys}" SelectionMode="None">
                <CollectionView.ItemTemplate>
                    <DataTemplate x:DataType="model:Monkey">
                        <Grid Padding="10">
                            <Frame HeightRequest="125" Padding="0" Style="{StaticResource CardView}">
                                <Frame.GestureRecognizers>
                                    <TapGestureRecognizer CommandParameter="{Binding .}" 
                                                          Command="{Binding Source={RelativeSource AncestorType={x:Type viewModel:MonkeysViewModel}}, Path=GoToDetailsCommand}" />
                                </Frame.GestureRecognizers>
                                <Grid Padding="0" ColumnDefinitions="125, *">
                                    <Image Aspect="Fill" Source="{Binding Image}" HeightRequest="125" WidthRequest="125"/>

                                    <VerticalStackLayout Grid.Column="1" Padding="10" VerticalOptions="Start">
                                        <Label Text="{Binding Name}" Style="{StaticResource LargeLabel}"/>
                                        <Label Text="{Binding Location}" Style="{StaticResource MicroLabel}"/>
                                    </VerticalStackLayout>
                                </Grid>
                            </Frame>
                        </Grid>
                    </DataTemplate>
                </CollectionView.ItemTemplate>

                <CollectionView.EmptyView>
                    <StackLayout Padding="100" VerticalOptions="Center" HorizontalOptions="Center" IsVisible="{Binding IsNotBusy}">
                        <Image HorizontalOptions="Center" VerticalOptions="Center" Source="nodata.png" />
                        <Label Text="Your list is currently empty!" Style="{StaticResource BaseLabel}" Margin="5"/>
                    </StackLayout>
                </CollectionView.EmptyView>
            </CollectionView>
        </RefreshView>
```


ViewModel:

```
[ObservableProperty]
 bool isRefreshing = false;

async Task GetMonkeysAsync()
    {
        if (IsBusy) return;

        try
        {
            if (connectivity.NetworkAccess != NetworkAccess.Internet)
            {
                await Shell.Current.DisplayAlert("Internet Error", "Check your internet connection and try again.", "OK");
                return;
            }

            IsBusy = true;

            var monkeys = await monkeyService.GetMonkeysAsync();

            if (Monkeys.Any())
                Monkeys.Clear();

            foreach (var monkey in monkeys)
            {
                Monkeys.Add(monkey);
            }


        }
        catch (Exception ex)
        {
            Debug.WriteLine(ex);

            await Shell.Current.DisplayAlert("Error", "Unable to get monkeys.", "OK");
        }
        finally
        {
            IsBusy = false;
            isRefreshing = false;
        }
    }
```

![Screenshot_1666091402](https://user-images.githubusercontent.com/48436230/196414114-3e1a1c24-5041-4417-9c07-56bec10bb525.png)

**Comment by jerry08** [comment] 2023-01-16 17:00
This issue still exists so I found a workaround by using a custom handler. Here's my code:

```
public class CustomRefreshViewHandler : RefreshViewHandler
{
    protected override void ConnectHandler(MauiSwipeRefreshLayout platformView)
    {
        //You can play around with the offsets
        platformView.SetProgressViewOffset(false, -20, 80);
        base.ConnectHandler(platformView);
    }
}
```

Register the handler in `MauiProgram`:

```
.ConfigureMauiHandlers(handlers =>
            {
#if ANDROID
                handlers.AddHandler<RefreshView, CustomRefreshViewHandler>();
#endif
            })
```

**Comment by janseris** [comment] 2023-04-19 18:19
This isssue appears when there is a control above the refreshview. Then the indicator when "hidden" (moved to relative negative y position), overlays the control above the RefreshView.

**Comment by XamlTest** [comment] 2023-05-24 05:49
Verified this on Visual Studio Enterprise 17.7.0 Preview 1.0. Repro on Android 13.0 with below Project:
[8926.zip](https://github.com/dotnet/maui/files/11550874/8926.zip)

![image](https://github.com/dotnet/maui/assets/97647558/e9377a37-ef03-4f9b-b620-84fddecba63c)

**Comment by NandoLopes** [comment] 2023-05-25 15:23
I've been working with .NET MAUI for the past 2 months, and honestly, it's the worst thing I ever worked with.
Again, I came to check some simple but annoying bug, only to get disappointed but not surprised with the "We've moved this issue to the Backlog milestone" message.

Seems like **NOTHING** is important enough to actually be fixed.

I'm trying to convince my company to abandon MAUI and start from the scratch using something else like Flutter or whatever, even knowing I never used Dart. I'm sure I can learn how to use a new language/framework, but I honestly can't do anything about those millions of bugs.

**Comment by softlion** [comment] 2023-05-26 16:11
> I've been working with .NET MAUI for the past 2 months, and honestly, it's the worst thing I ever worked with. Again, I came to check some simple but annoying bug, only to get disappointed but not surprised with the "We've moved this issue to the Backlog milestone" message.
> 
> Seems like **NOTHING** is important enough to actually be fixed.
> 
> I'm trying to convince my company to abandon MAUI and start from the scratch using something else like Flutter or whatever, even knowing I never used Dart. I'm sure I can learn how to use a new language/framework, but I honestly can't do anything about those millions of bugs.

"Everything" is already fixed in the .net 8 preview (including this bug).
Nothing will be fixed in the .net7 version. Or so late that devs like you will have left the game at that time.
That's what I understood after chatting a lot with ms devs about their .net7/8 release cycle.

**Comment by r-work** [comment] 2023-08-02 15:33
This is definitely **NOT** fixed in 8 preview 6.
And this is NOT a backlog type of issue, this makes the `RefreshView` useless.

**Comment by DaveNatalieTripArc** [comment] 2023-08-09 19:21
I am seeing this issue on Windows after updating to the latest release.  (8.0.0-preview.7.23375.6).

Before updating it wasn't happening for me on Android or Windows (I haven't tried iOS).

On Windows, it doesn't matter if I pull to refresh, or start refreshing via code, the loading indicator is always visible even after setting my `isLoading` ObservableProperty to false.

**Comment by DM-98** [comment] 2023-08-14 14:06
.NET 8 Preview 6 - works
.NET 8 Preview 7 - bugging out like this...

**Comment by tibuprophen** [comment] 2023-08-15 13:25
Same issue on Android

**Comment by r-work** [comment] 2023-08-17 10:05
@samhouts this is definitely is a `p/0 ` type of issue, the ListView itself seems to be affected by the same issue.
This is such a basic functionality, this issue itself is a year old!

**Comment by viettranuk** [comment] 2023-08-19 15:39
I came across this similar issue today when trying to re-render my CollectionView using RefreshView and found out that if you use a backing-field and manually call OnPropertyChanged() on the IsRefreshing property, the refresh indicator will disappear straight away once the refresh command completed and touch released. Below is what I got that works:

```csharp
public ICommand RefreshCommand { get; }

private bool _isRefreshing;

public bool IsRefreshing
{
    get => _isRefreshing;

    set
    {
        if (_isRefreshing == value)
        {
            return;
        }

        _isRefreshing = value;

        OnPropertyChanged();
    }
}

RefreshCommand = new AsyncRelayCommand(RefreshDataViewAsync);

private async Task RefreshDataViewAsync()
{
    // code to refresh collection data

    IsRefreshing = false;
}
```

Hope that helps!

**Comment by DM-98** [comment] 2023-08-19 22:40
@viettranuk That didn't work for me. The indicator stays: 
![image](https://github.com/dotnet/maui/assets/10290906/e51068e1-c2a0-40ff-961d-f863bf27daae)

xaml: 
```
<RefreshView IsRefreshing="{Binding IsRefreshing}" ...>
```
c#: 
```
private bool isRefreshing;

public bool IsRefreshing
{
	get => isRefreshing;
	set 
	{
		if (isRefreshing == value)
		{
			return;
		}

		isRefreshing = value;
		
		OnPropertyChanged();
	}
}
```

**Comment by viettranuk** [comment] 2023-08-20 05:09
@DM-98 That's strange. It works like a charm for me. Did you set IsRefreshing back to false upon the completion of refresh command?

**Comment by softlion** [comment] 2023-08-20 05:34
The correct way to do it is:

```xml
<RefreshView IsRefreshing="{Binding IsPullToRefreshing,Mode=OneWay}"
                     Command="{Binding PullToRefreshCommand}">
   <CollectionView ....
```

```c#
//Add notify property changed (i'm using fody)
public bool IsPullToRefreshing { get ...; set ...; }

public ICommand PullToRefreshCommand {get;}

...

PullToRefreshCommand = new Command(async () =>
        {
            if (!IsPullToRefreshing)
            {
                IsPullToRefreshing = true;
                try
                {
                    //do something lengthy
                }
                finally
                {
                    IsPullToRefreshing = false;
                }
            }
        });
```

**Comment by DM-98** [comment] 2023-08-20 07:09
@viettranuk Yes, I even tried using the try-finally block. Are you using .NET 8 Preview 7?

**Comment by viettranuk** [comment] 2023-08-20 07:19
@DM-98 Sorry I'm using .NET 7 with VS Pro 17.7.1

**Comment by mikelor** [comment] 2023-08-20 19:18
After updating to .NET 8 Preview 7, I am experiencing this issue on Android and Windows.
:(

**Closed** 2023-08-30 10:45 UTC
Labels: t/bug, platform/android 🤖, p/1, area/controls 🎮, s/verified, control-activityindicator, s/triaged
