### ISSUE TITLE
Shell: GoBack on Android shows sandwich menu

### ISSUE THREAD

**Issue by Schinwinkwinsky** [dotnet/maui#24054] opened 2024-08-06 23:31 UTC
### Description

On an application that uses Shell, when GoBack is requested, the sandwich menu button blinks on screen.

https://github.com/user-attachments/assets/6209f1c6-b847-464d-9d68-69d5c72c2411

Shell:
```
<?xml version="1.0" encoding="UTF-8" ?>
<Shell
    x:Class="BaladaCerta.Maui.AppShell"
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:pages="clr-namespace:BaladaCerta.Maui.Views.Pages">

    <TabBar>
        <Tab 
            Title="Events"
            Icon="dotnet_bot.svg">            
            <ShellContent ContentTemplate="{DataTemplate pages:EventsPage}" />
        </Tab>
        <Tab 
            Title="New Events"
            Icon="dotnet_bot.svg">
            <ShellContent ContentTemplate="{DataTemplate pages:NewEventPage}" />
        </Tab>
    </TabBar>
</Shell>
```

EventsPage:
```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="BaladaCerta.Maui.Views.Pages.EventsPage"
             Title="{Binding Title}">
    
    <VerticalStackLayout>
        <Label 
            Text="Events Page"
            VerticalOptions="Center" 
            HorizontalOptions="Center" />
        <Button 
            Text="New Event"
            Command="{Binding GoToNewEventPageCommand}" />

    </VerticalStackLayout>
</ContentPage>
```

EventsPageVM:
```
using CommunityToolkit.Mvvm.Input;

namespace BaladaCerta.Maui.ViewModels;

public partial class EventsPageVM : BaseViewModel
{
    public EventsPageVM()
    {
        Title = "Events";
    }

    [RelayCommand]
    public async Task GoToNewEventPageAsync()
    {
        await Shell.Current.GoToAsync("new-event");
    }
}
```

### Version with bug

8.0.3 GA

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

**Comment by kubaflo** [comment] 2024-08-07 18:30
https://github.com/dotnet/maui/pull/21455

**Comment by kubaflo** [comment] 2024-08-07 18:30
Duplicate of https://github.com/dotnet/maui/issues/18867

**Closed by kubaflo** 2024-08-07 18:30 UTC
Labels: t/bug
