### ISSUE TITLE
Blazor .NET MAUI WPF `MissingMethodException`

### ISSUE THREAD

**Issue by evk200** [dotnet/maui#10199] opened 2022-09-19 05:23 UTC
### Description

The app that used to work doesn't work

### Steps to Reproduce

Android System WebView Latest Updates..

### Link to public reproduction project repository

.

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 12.0 API 31

### Did you find any workaround?

Android System WebView Removal

>> downgrade

105.0.5195.79 x

**Comment by cyberdarius** [comment] 2022-09-19 10:13
Also on windows:

BlazorWebView WPF
Microsoft.AspNetCore.Components.WebView.Wpf

After webview autoupdate i cannot compile anymore my blazorWebView (any version) wpf application

System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task Microsoft.Web.WebView2.Wpf.WebView2.EnsureCoreWebView2Async(Microsoft.Web.WebView2.Core.CoreWebView2Environment)'

It seems a change of signature:
https://github.com/MicrosoftEdge/WebView2Feedback/issues/2775


Method not found: 'System.Threading.Tasks.Task Microsoft.Web.WebView2.Wpf.WebView2.EnsureCoreWebView2Async(Microsoft.Web.WebView2.Core.CoreWebView2Environment)'.
   in Microsoft.AspNetCore.Components.WebView.WebView2.WebView2WebViewManager.<TryInitializeWebView2>d__14.MoveNext()
   in System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   in Microsoft.AspNetCore.Components.WebView.WebView2.WebView2WebViewManager.TryInitializeWebView2()
   in Microsoft.AspNetCore.Components.WebView.WebView2.WebView2WebViewManager..ctor(WebView2 webview, IServiceProvider services, Dispatcher dispatcher, IFileProvider fileProvider, JSComponentConfigurationStore jsComponents, String contentRootRelativeToAppRoot, String hostPagePathWithinFileProvider, Action`1 urlLoading, Action`1 blazorWebViewInitializing, Action`1 blazorWebViewInitialized)
   in Microsoft.AspNetCore.Components.WebView.Wpf.BlazorWebView.StartWebViewCoreIfPossible()
   in System.Windows.FrameworkElement.ApplyTemplate()
   in System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   in System.Windows.UIElement.Measure(Size availableSize)
   in MS.Internal.Helper.MeasureElementWithSingleChild(UIElement element, Size constraint)
   in System.Windows.Controls.ContentPresenter.MeasureOverride(Size constraint)
   in System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   in System.Windows.UIElement.Measure(Size availableSize)
   in System.Windows.Controls.Decorator.MeasureOverride(Size constraint)
   in System.Windows.Documents.AdornerDecorator.MeasureOverride(Size constraint)
   in System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   in System.Windows.UIElement.Measure(Size availableSize)
   in System.Windows.Controls.Border.MeasureOverride(Size constraint)
   in System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   in System.Windows.UIElement.Measure(Size availableSize)
   in System.Windows.Window.MeasureOverrideHelper(Size constraint)
   in System.Windows.Window.MeasureOverride(Size availableSize)
   in System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   in System.Windows.UIElement.Measure(Size availableSize)
   in System.Windows.Interop.HwndSource.SetLayoutSize()
   in System.Windows.Interop.HwndSource.set_RootVisualInternal(Visual value)
   in System.Windows.Interop.HwndSource.set_RootVisual(Visual value)
   in System.Windows.Window.SetRootVisual()
   in System.Windows.Window.SetRootVisualAndUpdateSTC()
   in System.Windows.Window.SetupInitialState(Double requestedTop, Double requestedLeft, Double requestedWidth, Double requestedHeight)
   in System.Windows.Window.CreateSourceWindow(Boolean duringShow)
   in System.Windows.Window.CreateSourceWindowDuringShow()
   in System.Windows.Window.SafeCreateWindowDuringShow()
   in System.Windows.Window.ShowHelper(Object booleanBox)
   in System.Windows.Window.Show()


https://github.com/MicrosoftEdge/WebView2Feedback/issues/2775

**Comment by TanayParikh** [comment] 2022-09-19 17:04
The android issue you're having is a duplicate of https://github.com/dotnet/maui/issues/9882. There was a Chromium issue which has since been resolved (you'll have to update to the latest webview).

The WPF one looks new...

**Comment by Eilon** [comment] 2022-09-19 17:06
Indeed, the Android issue is tracked by https://github.com/dotnet/maui/issues/9882 and already fixed by Google. Users need to update their Android System WebView through the Google Play Store, or whichever store they use on their device.

The WebView2 issue is tracked by https://github.com/MicrosoftEdge/WebView2Feedback/issues/2775, so please up-vote that. It seems to be a breaking change so please use the older version of the NuGet package for now.

**Closed by Eilon** 2022-09-19 17:06 UTC
Labels: t/bug, area/blazor 🕸️
