### ISSUE TITLE
FilePicker on MacOs (MacCatalyst) returns null

### ISSUE THREAD

**Issue by Buyukcaglar** [dotnet/maui#20741] opened 2024-02-21 10:30 UTC
### Description

I am having the exact same issues explained in https://github.com/dotnet/maui/issues/11088. 

First asked question to check that if I am missing something or doing wrong;

[https://learn.microsoft.com/en-us/answers/questions/1538662/filepicker-on-macos-(maccatalyst)-does-not-return](https://learn.microsoft.com/en-us/answers/questions/1538662/filepicker-on-macos-(maccatalyst)-does-not-return)

but confirmed that the bug is reproducible.

and aware of [issue 15126](https://github.com/dotnet/maui/issues/15126).

and checked https://stackoverflow.com/questions/76532956/filepicker-throwing-an-exception-on-mac-os-with-net-maui answer added 

```
    <key>com.apple.security.files.user-selected.read-only</key>
    <true/>
```

to **Entitlements.plist**

Dotnet workloads on development machine (Windows); 

```
    Installed Workload Id Manifest Version Installation Source
    ---------------------------------------------------------------------
    maui-windows 8.0.6/8.0.100 VS 17.10.34607.79
    maccatalyst 17.2.8022/8.0.100 VS 17.10.34607.79
    android 34.0.79/8.0.100 VS 17.10.34607.79
    ios 17.2.8022/8.0.100 VS 17.10.34607.79 
```

and dotnet workloads on publishing machine (Mac); 

```
    Installed Workload Id Manifest Version Installation Source
    ---------------------------------------------------------------------
    wasm-tools 8.0.2/8.0.100 SDK 8.0.200
    macos 14.2.8022/8.0.100 SDK 8.0.200
    maui-maccatalyst 8.0.6/8.0.100 SDK 8.0.200
    maui-ios 8.0.6/8.0.100 SDK 8.0.200
    maui-android 8.0.6/8.0.100 SDK 8.0.200
    ios 17.2.8022/8.0.100 SDK 8.0.200
    maui 8.0.6/8.0.100 SDK 8.0.200 
```

There is a approved and merged PR for this issue; [PR 13814](https://github.com/dotnet/maui/pull/13814) and more over, this issue has been deemed as fixed on Jul 12, 2023 [issue 11088#event-9792279528](https://github.com/dotnet/maui/issues/11088#event-9792279528) Alas, when I lookup the sources of relevant code area from Visual Studio I am not able to see fixed code. (Its just #if/#endif which is not there!) 

The following code is used to pick text files;

Project is open source and repository address is; [https://github.com/Buyukcaglar/UltimateRemote ](https://github.com/Buyukcaglar/UltimateRemote )

https://github.com/Buyukcaglar/UltimateRemote/blob/main/Constants/FilePickerOptions.cs Line 15 & 264 

```
    public static PickOptions TextFileOptions = new()
    {
    PickerTitle = "Select a TXT file",
    FileTypes = TxtFile,
    }; 
    
    private static readonly FilePickerFileType TxtFile = new FilePickerFileType(
    new Dictionary<DevicePlatform, IEnumerable<string>>
    {
    { DevicePlatform.iOS, new[] { "public.text" } },
    { DevicePlatform.Android, new[] { "text/plain" } },
    { DevicePlatform.WinUI, new[] { ".txt" } },
    { DevicePlatform.Tizen, new[] { "*/*" } },
    { DevicePlatform.macOS, new[] { "public.text" } },
    { DevicePlatform.MacCatalyst, new[] { "public.text" } }
    });
```

https://github.com/Buyukcaglar/UltimateRemote/blob/main/Services/StorageContentFileService.cs Line 51: 

`    var pickResult = await FilePicker.PickAsync(FilePickerOptions.TextFileOptions);`

**FilePicker.PickAsync or FilePicker.Default.PickAsync** does not matter, result is null regardless.

Also tried to use [https://github.com/datvm/LukeMauiFilePicker](https://github.com/datvm/LukeMauiFilePicker) but this one also returns PickedFile null.

### Steps to Reproduce

1. Clone the repo on https://github.com/Buyukcaglar/UltimateRemote 
2. Tap top-right gear icon
3. Select Storage Content Manager
4. Tap Import SD Card/USB drive Content List
5. Select a text file under MacOs

### Link to public reproduction project repository

https://github.com/Buyukcaglar/UltimateRemote 

### Version with bug

8.0.6 SR1

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

**Comment by datvm** [comment] 2024-02-21 14:49
@Buyukcaglar that's interesting that my library is returning null as well. Could you try it on a new project and if the problem is still there, could you give a reproducible repo as well please? Thank you.

**Comment by Buyukcaglar** [comment] 2024-02-21 14:55
@datvm Reproducible repo is here; [https://github.com/Buyukcaglar/UltimateRemote](https://github.com/Buyukcaglar/UltimateRemote)

steps denoted on this issue.

I've implemented you library on

[StorageContentFileService.cs](https://github.com/Buyukcaglar/UltimateRemote/blob/main/Services/StorageContentFileService.cs) Line 51:

`var pickResult = await FilePicker.PickAsync(FilePickerOptions.TextFileOptions);`

but did not commit when the result came out null as well.

FYI.

**Comment by jfversluis** [comment] 2024-02-21 19:37
Related to #15126

**Comment by Buyukcaglar** [comment] 2024-02-21 20:04
@datvm I have set up a brand new maui project and tried your library, the result is same IPickFile.File Result returns NULL everytime.

You may find the new repository below;

[https://github.com/Buyukcaglar/MauiFilePickerMacOsBug](https://github.com/Buyukcaglar/MauiFilePickerMacOsBug)

And here is the screenshots;

![image](https://github.com/dotnet/maui/assets/4595315/a4cd2e34-1bd1-402e-a351-71f0f2755162)


![image](https://github.com/dotnet/maui/assets/4595315/804e09cd-1831-477f-a911-e50e6ebebfb0)

**Comment by PureWeen** [comment] 2024-02-22 19:30
Duplicate of #15126

**Closed by PureWeen** 2024-02-22 19:30 UTC
Labels: t/bug, platform/macOS 🍏, area/essentials 🍞
