### ISSUE TITLE
Button IsEnabled does not restore visual state

### ISSUE THREAD

**Issue by ascmt** [dotnet/maui#8932] opened 2022-07-22 15:26 UTC
### Description

MAUI Button does not restore the Normal background color after an IsEnabled state change.  

Reproduceable on Windows 10 using VS17.3p4.

This is trivially reproduceable with any Button ("AnotherButton") with this Clicked handler:
```
        private async void OnButtonClick(object sender, EventArgs e)
	{
		AnotherButton.IsEnabled = false;
		await Task.Delay(3000);
		AnotherButton.IsEnabled = true;
	}
```

No repro project necessary - just apply this code to the default MAUI Template project in VS17.3p4.

Restoring the Normal color after the Delay fails the first timeNo workaround discovered as yet.

This is one of the most basic use cases for Button.IsEnabled to prevent re-entrance.  There is no documented trivial workaround.  This should be treated as a high-severity bug as such.

#7377 sounds similar but has been open for 2 months without assignment or response.

### Steps to Reproduce

1. New .Net MAUI App
2. Replace the Counter button implementation with above
3. Start app.  Click button.

Observed: Button does not restore Normal visual state and stays on Disabled visual state.
Expected: Button reverts to Normal visual state when IsEnabled=true is set.

### Version with bug

6.0.408 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10

### Did you find any workaround?

No

**Comment by jfversluis** [comment] 2022-07-25 12:14
Duplicate of #7377

**Closed by jfversluis** 2022-07-25 12:14 UTC
Labels: t/bug, s/needs-verification
