### ISSUE TITLE
[MAUI] SplashScreen resize=false failed to work on iOS.

### ISSUE THREAD

**Issue by jaosnz-rep** [dotnet/maui#17924] opened 2023-10-10 08:37 UTC
### Description

SplashScreen resize=false failed to work, .NET logo is missing.

### Steps to Reproduce

1.Deploy https://devdiv.visualstudio.com/Pkgs/_git/VS.TestAssets.Xaml?path=/Assets/Projects/ManualMauiTests to iOS simulator or device.
2.Make sure that the following MauiSplashScreen is the only one uncommented in the project file:
`<MauiSplashScreen Include="Resources\Splash\splash.svg" Color="#512BD4" Resize="False" BaseSize="16,16" />`
3.Observe the SplashScreen that displays while the app is loading.

Expected results:
The .NET logo should be very clear (not blurry).
![image](https://github.com/dotnet/maui/assets/82628041/48d32d8e-ac7f-4926-8751-c1cfd40d65db)

Actual result:
.NET logo is missing.
![image](https://github.com/dotnet/maui/assets/82628041/4180db6d-7847-4063-bb77-a2daec07abe1)

### Link to public reproduction project repository

https://devdiv.visualstudio.com/Pkgs/_git/VS.TestAssets.Xaml?path=/Assets/Projects/ManualMauiTests

### Version with bug

Microsoft.Maui.Controls 8.0.0-nightly.9331+sha.6aac924e89-azdo.8456294
.NET SDK: 8.0.100-rc.1.23463.5

### Is this a regression from previous behavior?

Not a regression, The issue also repro on 8.0.0-rc.1.9171

### Affected platforms

iOS

**Comment by mattleibow** [comment] 2023-10-11 14:43
Duplicate of https://github.com/xamarin/xamarin-macios/issues/18469

**Closed** 2023-10-11 14:44 UTC
Labels: t/bug, platform/iOS 🍎, csi-new
