### ISSUE TITLE
Filepicker crashes with error "Value does not fall within the expected range" on  Windows (10) when the app is distributed as exe

### ISSUE THREAD

**Issue by peno64** [dotnet/maui#10577] opened 2022-10-09 18:47 UTC
### Description

The filepicker works just fine when compiled such that the app will be distributed as msix. Both in visual studio in debug mode as when run outsite VS. 
When compiled such that the output is an exe (I followed following  procedure for this: https://blog.verslu.is/maui/dotnet-maui-windows-unpackaged-apps/) then it crashes after selecting a file with the error "Value does not fall within the expected range" after a file is chosen. This both in debug mode from visual studio and when the exe is run.
I am not the  only person having this problem since it is also reported on stackoverflow: https://stackoverflow.com/questions/73282083/net-maui-ifilepicker-error-value-does-not-fall-within-the-expected-range-if-b

Installed Workload Ids      Manifest Version                              Installation Source
---------------------------------------------------------------------------------------------
maui-windows                6.0.536/6.0.400                               VS 17.3.32922.545

### Steps to Reproduce

-

### Link to public reproduction project repository

-

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

maui-windows                6.0.536/6.0.400                               VS 17.3.32922.545

### Did you find any workaround?

No

**Comment by rmarinho** [comment] 2022-10-10 14:24
Duplicate of #10313

**Comment by rmarinho** [comment] 2022-10-10 14:24
This is going to be fixed on 7.0.0-rc2

**Closed by rmarinho** 2022-10-10 14:24 UTC
Labels: t/bug, platform/windows 🪟, area/publishing 🏁, s/needs-repro
