### ISSUE TITLE
Label not respecting Font Family setup if using FormattedText

### ISSUE THREAD

**Issue by albilaga** [dotnet/maui#16193] opened 2023-07-17 12:31 UTC
### Description

When setup `FontFamily` in `Label` who have `FormattedText`, `Label` will not respect `FontFamily` setup in `Label`. But if we setup the `FontFamily` in `Span` then it is worked. This is occuring on MAUI 7.0.92. Not sure if previous version worked or not but in Xamarin.Forms this is worked.

### Steps to Reproduce

1. Open this https://github.com/albilaga/MAUIPlayground/tree/test-font-family
2. Run the app.
3. The second label will have regular font even though I already setup the `FontFamily` to be the same like other label
4. Code all is in this page https://github.com/albilaga/MAUIPlayground/blob/test-font-family/MAUIPlayground/MainPage.xaml

### Link to public reproduction project repository

https://github.com/albilaga/MAUIPlayground/tree/test-font-family

### Version with bug

Unknown/Other

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

iOS and Android

### Did you find any workaround?

Workaround right now is setup the `FontFamily` in the `Span` instead in `Label`

**Comment by AndreasReitberger** [comment] 2023-07-18 05:50
Duplicate of #13977

**Comment by drasticactions** [comment] 2023-07-18 09:39
> Duplicate of #13977

I agree, looking at the root issues, they seem the same. 

Duplicate of https://github.com/dotnet/maui/issues/13977

**Closed by drasticactions** 2023-07-18 09:39 UTC
Labels: t/bug, platform/android 🤖, platform/iOS 🍎, area/controls 🎮, control-label

**Comment by samhouts** [comment] 2023-07-25 16:15
Duplicate of https://github.com/dotnet/maui/issues/13977
