### ISSUE TITLE
CollectionView Selection Issue on Android

### ISSUE THREAD

**Issue by YevhenHal** [dotnet/maui#23402] opened 2024-07-02 15:49 UTC
### Description

When using CollectionView with elements decorated with Frame or Border containers, the selection mechanism doesn’t work on Android. The VisualStateManager inside the frame doesn't change the appearance of the elements.

### Steps to Reproduce

1. Create a MAUI 8 Application using the standard template in Visual Studio 2022.
2. Create a simple model object Case with the field Name.
3. Inside the ViewModel, using the CommunityToolkit.MVVM add the array of Cases, add some elements to it and create the field for selected case. After populating of the Cases array, select second element programmatically by setting SelectedCase property.
4. Create the following XAML in the Page: 
`<ScrollView>
```XAML
    <CollectionView x:Name="ItemsCollectionView"
                    SelectionMode="Single"
                    ItemsSource="{Binding Cases}"
                    SelectedItem="{Binding SelectedCase, Mode=TwoWay}"
                    VerticalScrollBarVisibility="Default"
                    HeightRequest="450"
                    HorizontalOptions="Center">
        <CollectionView.ItemTemplate>
            <DataTemplate>
               <Frame BorderColor="Red">
                   <Label Text="{Binding Name}" Margin="5" TextColor="White"/>
                    <Frame.GestureRecognizers>
                        <TapGestureRecognizer Tapped="TapGestureRecognizer_OnTapped"
                                         NumberOfTapsRequired="1" />
                    </Frame.GestureRecognizers>
                    <VisualStateManager.VisualStateGroups>
                       <VisualStateGroupList>
                           <VisualStateGroup>
                               <VisualState x:Name="Normal">
                                   <VisualState.Setters>
                                       <Setter Property="BackgroundColor" Value="Transparent" />
                                   </VisualState.Setters>
                               </VisualState>
                               <VisualState x:Name="Selected">
                                   <VisualState.Setters>
                                       <Setter Property="BackgroundColor" Value="#C11B17" />
                                   </VisualState.Setters>
                               </VisualState>
                           </VisualStateGroup>
                       </VisualStateGroupList>
                   </VisualStateManager.VisualStateGroups>
               </Frame>
            </DataTemplate>
        </CollectionView.ItemTemplate>
    </CollectionView>
</ScrollView>
``` 
6. Build and run the application, the integrated Android emulator will appear and show the page.
7. Try to select the item via the mouse click. 
**Actual result**: Item won't be selected, the selection remains on the second element which has been selected programmatically. Also, the SelectionChanged event won't fire.
**Expected result**: The selection should change when user clicks within the Frame.

Note: On Windows, no such issue is observed.

### Version with bug

8.0.60

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

At least Android 11 and upper.

### Did you find any workaround?

I've found the workaround: replacing the Frame + Label with the Button control could mitigate this issue. If I use the button, the VisualStateManager works correctly.

**Comment by wagenheimer** [comment] 2024-07-02 17:49
I can confirm that the Frame does not work. However, the Border does work for me.

**Comment by jfversluis** [comment] 2024-07-04 14:24
Duplicate of #15016

**Comment by jfversluis** [comment] 2024-07-04 14:25
This looks similar enough to be a duplicate I think. Please add your findings to the linked issue if the details you describe aren't in there already. Thanks!

**Closed by jfversluis** 2024-07-04 14:24 UTC
Labels: t/bug, platform/android 🤖, area-controls-collectionview, s/triaged
