### ISSUE TITLE
SVG Font-family does not apply after convert to png(Splash screen)

### ISSUE THREAD

**Issue by denhaandrei** [dotnet/maui#16399] opened 2023-07-27 12:18 UTC
### Description

Font 'Poppins' after conversion does not apply to the result PNG files: obj\Debug\net7.0-android\resizetizer\r\drawable (any folders)

I'm using the following SVG file:
```
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="413.852" height="808.197" viewBox="0 0 413.852 808.197">
  <defs>
	<style>
		@import url('https://fonts.googleapis.com/css2?family=Poppins:wght@800');
		.st0{fill:#223F3B;}
		.st1{fill:#5AC87A;}
	</style>
	  <pattern id="pattern" x="0" y="0" width="30" height="31" viewBox="0 0 30 31" patternUnits="userSpaceOnUse" >
		  <rect x="0" y="0" width="30" height="31" fill="#ffffff"/>
		  <path d="M-12.627,0H-21.6a1.07,1.07,0,0,0-1.062,1.075A1.071,1.071,0,0,0-21.6,2.152h7.908v7.975A1.069,1.069,0,0,0-12.627,11.2a1.068,1.068,0,0,0,1.061-1.076V1.075A1.068,1.068,0,0,0-12.627,0" transform="translate(24.996 9.291)" fill="rgba(82,190,41,0.1)"/>
	  </pattern>
  </defs>
	<rect x="0" y="0" width="413.852" height="808.197" opacity="0.999" fill="url(#pattern)"/>
  <g transform="translate(87.526 250) scale(1.5)">
	<g id="Text" transform="translate(77.589 0)">
		<text y="70" font-family="Poppins" font-size="15" fill="#404D3A" text-anchor="middle">Test message with font</text>
		<text y="90" font-size="15" fill="#404D3A" text-anchor="middle">Test message without font</text>
	</g>
  </g>
</svg>
```

### Steps to Reproduce

1. Create a MAUI App solution
2. Paste the following svg to existing splash.svg
3. Change in proj file:  <MauiSplashScreen Include="Resources\Splash\splash.svg" Color="#512BD4" BaseSize="128,128"/>
to <MauiSplashScreen Include="Resources\Splash\splash.svg"/>
4. Clean bin and obj folders if build project previously
5. Run on the Android 10 where full screen splash supported or see result png in folder: \obj\Debug\net7.0-android\resizetizer\r\drawable-xxxhdpi
6. The result png and opened svg are not the same, font-family does not apply

Please note 
1. the same issue for iOS font do not apply after publish to test flight
2. the same when I use  @font-face {
      font-family: 'PoppinsBoldBase64';
      src: url('data:font/truetype;base64,AAEAA...... and font-family="PoppinsBoldBase64"

### Link to public reproduction project repository

https://github.com/denhaandrei/BadSvgConverter.App

### Version with bug

7.0.49

### Last version that worked well

NOT work

### Affected platforms

iOS, Android

### Affected platform versions

I think all Android/IOS, because issue with convert svg

**Comment by PureWeen** [comment] 2023-07-27 18:15
@denhaandrei  did this work in 6.0 ?

**Comment by denhaandrei** [comment] 2023-07-28 07:17
> denhaandrei did this work in 6.0 ?

Previously not tested. Miss question "Last version that worked well"

After the test, it does not work at 6.0 too.

**Comment by moljac** [comment] 2023-07-28 20:32
This is not directly maui issue. namely managed libraries used by `resizetizer` 
have issues converting some (complex) SVG images to PNG.

Workaround would be to convert SVG to PNG using reliable converters.

*   original

    ! OK - github does not render font correctly
    `splash.svg`
     ![splash](https://github.com/dotnet/maui/assets/1768576/e3d7e8c7-f609-44d3-bb19-dbd8e67be7d2)

*   `resizetizer`

    ! OK - font
    `resizetizer-splash.png`
    ![resizetizer-splash](https://github.com/dotnet/maui/assets/1768576/2c703e93-1101-45fe-a35f-1afeeacc9f69)

*   Chrome browser - screenshot MacOSX

    OK
    <img width="407" alt="chrome-browser-splash" src="https://github.com/dotnet/maui/assets/1768576/bfd62ec5-b091-4cc1-b110-48af8605da63">


*   inkscape

    ! OK - font
    ![inkscape-splash](https://github.com/dotnet/maui/assets/1768576/293ff3cf-516d-4f85-aba6-7096c3c4ab95)



## Online Converters

*   https://svgtopng.com/

    OK
    `svgtopng.com-splash.png`
    ![svgtopng com-splash](https://github.com/dotnet/maui/assets/1768576/75c05818-9ada-49c5-8873-dd39cd17d5e0)

*   https://cloudconvert.com/

     ! OK
    `cloudconvert.com-splash.png`
    ![cloudconvert com-splash](https://github.com/dotnet/maui/assets/1768576/8a642141-186b-4833-ac4b-efcf6ed5b7b1)

*   https://convertio.co/svg-png/

    ! OK
    `convertio.co-splash.png`
    ![convertio co-splash](https://github.com/dotnet/maui/assets/1768576/c7b60e00-d54d-438f-9e05-d43d44556c28)


*   https://ezgif.com/svg-to-png

    ! OK
    `ezgif.com-splash.png`
    ![ezgif com-splash](https://github.com/dotnet/maui/assets/1768576/56d69129-5d1e-4479-ad2a-92259df83bc5)


    
I work on collecting reported issues in MAUI repo, so I can open issues on GitHub in relevant repositories.

**Comment by moljac** [comment] 2023-08-14 07:40
> I understand that the issue is not dotnet/maui, but MAUI uses some packages to convert .svg automatically.

I understand you completely.

My suggestion is: please open issue in Svg.Net repo too (with svg that has issue and expected png output).

> Thanks for your help. Wait and check it after the update packages.

You re welcome. This is the reason we are here.

> Unfortunately, we can`t use the converter on the splash screen, because the application can have different resolutions on different devices. So we continue to use .svg without font applying.

I understand. This must be fixed. Only the problem is where and how fast. Rewriting everything could cause more issues. 

> Please note, only "Chrome browser - screenshot MacOSX"(windows the same) is expected.

Thanks for the info. It was quite confusing when I saw several online converters having issues (similar incorrect output)

**Comment by moljac** [comment] 2023-08-22 12:58
Issue created in Svg.Net repo

https://github.com/svg-net/SVG/issues/1068

Closing this issue.

**Closed** 2024-04-03 14:08 UTC
Labels: t/bug, area/single project ☝️, platform/android 🤖, platform/iOS 🍎, s/needs-attention, external
