### ISSUE TITLE
On Android when you add a NavigationPage to the FlyoutPage.Flyout, an exception is thrown

### ISSUE THREAD

**Issue by imuller** [dotnet/maui#21515] opened 2024-03-28 20:39 UTC
### Description

When adding a NavigationPage to the FlyoutPage.Flyout section there is an exception thrown. The following exception is thrown:

```
System.InvalidOperationException: NavGraph cannot be null
   at Microsoft.Maui.Platform.StackNavigationManager.get_NavGraph() in D:\a\_work\1\s\src\Core\src\Platform\Android\Navigation\StackNavigationManager.cs:line 45
   at Microsoft.Maui.Platform.StackNavigationManager.CheckForFragmentChange() in D:\a\_work\1\s\src\Core\src\Platform\Android\Navigation\StackNavigationManager.cs:line 386
   at Microsoft.Maui.Platform.StackNavigationManager.OnNavigationHostViewAdded(Object sender, ChildViewAddedEventArgs e) in D:\a\_work\1\s\src\Core\src\Platform\Android\Navigation\StackNavigationManager.cs:line 353
   at Android.Views.ViewGroup.IOnHierarchyChangeListenerImplementor.OnChildViewAdded(View parent, View child) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net8.0/android-34/mcw/Android.Views.ViewGroup.cs:line 889
   at Android.Views.ViewGroup.IOnHierarchyChangeListenerInvoker.n_OnChildViewAdded_Landroid_view_View_Landroid_view_View_(IntPtr jnienv, IntPtr native__this, IntPtr native_parent, IntPtr native_child) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net8.0/android-34/mcw/Android.Views.ViewGroup.cs:line 775
   at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPLL_V(_JniMarshal_PPLL_V callback, IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:line 202
```

On iOS it just works fine :)

### Steps to Reproduce

1. Create a FlyoutPage (example below)
2. Add a Flyout and a Detail with both NavigationPage as root element
3. An exception was thrown

**❌ Does not work on Android**
```
<?xml version="1.0" encoding="utf-8"?>
<FlyoutPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MauiApp2.FlyoutMainPage">
    <FlyoutPage.Flyout>
        <NavigationPage Title="The Title">
            <x:Arguments>
                <ContentPage/>
            </x:Arguments>
        </NavigationPage>
    </FlyoutPage.Flyout>
    <FlyoutPage.Detail>
        <NavigationPage>
            <x:Arguments>
                <ContentPage/>
            </x:Arguments>
        </NavigationPage>
    </FlyoutPage.Detail>
</FlyoutPage>
```

**✅ Does work on Android**
```
<?xml version="1.0" encoding="utf-8"?>
<FlyoutPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MauiApp2.FlyoutMainPage">
    <FlyoutPage.Flyout>
        <ContentPage Title="The Title"/>
    </FlyoutPage.Flyout>
    <FlyoutPage.Detail>
        <NavigationPage>
            <x:Arguments>
                <ContentPage/>
            </x:Arguments>
        </NavigationPage>
    </FlyoutPage.Detail>
</FlyoutPage>
```

### Version with bug

8.0.10 SR3

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11 and up

### Did you find any workaround?

The only workaround I found was to just set the ContentPage inside the FlyoutPage.Flyout part. And not using a NavigationPage. This results in no TitleView is visible.

**Comment by PureWeen** [comment] 2024-03-29 14:06
Duplicate of #14561

**Closed by PureWeen** 2024-03-29 14:06 UTC
Labels: t/bug, platform/android 🤖, migration-compatibility
