### ISSUE TITLE
TextCell isVisible

### ISSUE THREAD

**Issue by jrahma** [dotnet/maui#11120] opened 2022-11-05 16:32 UTC
### Description

Many times you need to show or hide the TextCell but currently, there is no IsVisible property for it.

### Public API Changes

TextCell .IsVisible = {True | False}

### Intended Use-Case

Show or hide TextCell

**Comment by jfversluis** [comment] 2023-03-18 19:25
Duplicate of #14004

**Closed by jfversluis** 2023-03-18 19:25 UTC
Labels: t/enhancement ☀️, proposal/open, area/ListView
