### ISSUE TITLE
Maui (.net 7) Android (apk) Button behaves differently in Debug and Release.

### ISSUE THREAD

**Issue by pulmuone** [dotnet/maui#16825] opened 2023-08-17 14:23 UTC
### Description

Maui(.net 7) Android In Debug, when the Button is disabled, the background color of the Button changes normally.
However, if you create and run an apk with Release, the background color of the Button does not change when the Button is Disabled.

--Debug
https://github.com/dotnet/maui/assets/42885949/b360c6e3-45be-47e3-b7a3-9879f847a8fa

--Release(apk)
https://github.com/dotnet/maui/assets/42885949/89cba65f-2803-4a8b-9550-95f0689d6f6a

 Release Option

![화면 캡처 2023-08-17 232424](https://github.com/dotnet/maui/assets/42885949/54564afe-b1b8-42f3-8f87-559657594e75)

### Link to public reproduction project repository

c# maui Sample source.
https://github.com/dotnet/maui-samples/blob/main/7.0/Fundamentals/DataBindingDemos/DataBindingDemos/Views/PersonEntryPage.xaml

Debug(Android)
https://github.com/dotnet/maui/assets/42885949/daa33830-c7e4-40c9-b92f-f2f6a800c618

Release (Android apk)
https://github.com/dotnet/maui/assets/42885949/890b7987-55f5-45f5-bae3-122ec4d1dacf

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.92

### Affected platforms

Android

### Affected platform versions

Android 13, VS2022 Ent, Maui(.net 7)

**Comment by pulmuone** [comment] 2023-08-18 00:12
c# maui Sample source.
https://github.com/dotnet/maui-samples/blob/main/7.0/Fundamentals/DataBindingDemos/DataBindingDemos/Views/PersonEntryPage.xaml

Debug(Android)
https://github.com/dotnet/maui/assets/42885949/daa33830-c7e4-40c9-b92f-f2f6a800c618

Release (Android apk)
https://github.com/dotnet/maui/assets/42885949/890b7987-55f5-45f5-bae3-122ec4d1dacf

**Comment by developer9969** [comment] 2023-08-20 05:03
hi if you are refering to the button backgroundcolor not working in release , and there are many issues raised on this one  - the long and short of this is if you set the background rather than backgroundcolor it will work.. cannot find the issue now but one of the team gave the explanation and also issued an handler as a workround... Apologies if is not what you are referring to

**Comment by pulmuone** [comment] 2023-08-20 10:49
> hi if you are refering to the button backgroundcolor not working in release , and there are many issues raised on this one - the long and short of this is if you set the background rather than backgroundcolor it will work.. cannot find the issue now but one of the team gave the explanation and also issued an handler as a workround... Apologies if is not what you are referring to

it's okay. We (me) will try to solve the problem somehow.

**Comment by greg84** [comment] 2023-08-21 12:59
Use `Background` instead of `BackgroundColor`.

**Comment by samhouts** [comment] 2023-08-21 22:44
Duplicate of #11662

**Closed by samhouts** 2023-08-21 22:44 UTC
Labels: t/bug, platform/android 🤖, area/controls 🎮, control-button, s/needs-attention, linker
