### ISSUE TITLE
[Bug] Fix SearchView Accessibility to read out Semantic Hint

### ISSUE THREAD

**Issue by PureWeen** [dotnet/maui#1228] opened 2021-06-09 21:25 UTC
Once this issue is addressed

https://github.com/dotnet/maui/issues/1227

we'll need to fix how accessibility properties get applied to search view

**Comment by rachelkang** [comment] 2021-11-05 19:28
It seems like we're ready for this, and from what I can tell, the description and hint text are not read aloud.

**Comment by v-longmin** [comment] 2022-03-07 06:11
Thank you so much for your bug report! Unfortunately, we cannot reproduce your issue with the information above, could you provide a sample project and screenshots or more details that we can reproduce your issue? That should greatly speed up the process, thanks!

**Comment by PureWeen** [comment] 2022-03-07 17:11
This is an internal tracking issue. Don't worry about validating this @v-longmin

**Comment by rachelkang** [comment] 2022-05-19 19:40
On Android currently:
SearchBar semantics are looking mostly great. However, hint is never read aloud whatsoever

On iOS currently:
Hint seems to be assigned not to the actual editable part of the SearchBar, but the entire control as a whole. As a result, when hint is assigned, hint gets read aloud, but nothing else does and the editable textfield can't be accessed!!!

The root of the problem seems to be the same for both, that the hint is being assigned to the outer / overarching control, as opposed to just the editable text input area

**Closed** 2022-06-08 19:29 UTC
Labels: t/bug, platform/android 🤖, p/2, area/a11y, s/verified, s/triaged
