### ISSUE TITLE
[iOS] Type x:String not found in xmlns http://schemas.microsoft.com/winfx/2009/xaml

### ISSUE THREAD

**Issue by NiladriPadhy** [dotnet/maui#9580] opened 2022-08-22 14:59 UTC
### Description

iOS App causing exception while running the app in physical device. Working fine in iOS simulator.

Tried all the work arounds mentioned in below link.
https://github.com/dotnet/maui/issues/6070

Updated Visual Studio Mac 17.4 Preview and Updated Xcode Version to 13.4.1.

### Steps to Reproduce

Add a string static resoruce into App.xaml file.
 <x:String x:Key="FaceID">face.png</x:String>

### Affected platforms

iOS

### Affected platform versions

iOS 15.5

### Did you find any workaround?

No work around working.

**Comment by jfversluis** [comment] 2022-08-23 18:20
Duplicate of #6070

**Closed by jfversluis** 2022-08-23 18:20 UTC
Labels: t/bug, area/Xaml </>, platform/iOS 🍎
