### ISSUE TITLE
Rendering problem when Image and Label are placed inside StackLayout

### ISSUE THREAD

**Issue by thomasgalliker** [dotnet/maui#25769] opened 2024-11-11 13:48 UTC
### Description

It seems as there is a rendering bug when I place an image and a label inside a StackLayout and align them horizontally. When the StackLayout uses Orientation=Horizontal, the Label's text overruns the layout boundries of the parent StackLayout (as well as the parent Grid) control. 

![Image](https://github.com/user-attachments/assets/181f58d1-8747-4fba-a61c-4ecf120f6b81)
![Image](https://github.com/user-attachments/assets/438b36ba-5b22-4b0b-bf9e-13d29ce4522e)

In our production app, we experience similar issues (sadly not reproducible). If we flip StackLayout.Spacing from "4" to "5" the text is tail truncated even if there is enough horizontal space available.

![Image](https://github.com/user-attachments/assets/c2569b3b-daff-45c4-91d7-9d953d24fda5)
![Image](https://github.com/user-attachments/assets/bdab45d3-db7e-4701-8e8d-10aaa2f3ec5e)

### Steps to Reproduce

1. Create new .NET MAUI app.
2. Update MainPage.xaml: Add ScrollView + Grid + StackLayout (Orientation=Horizontal).
3. Inside the StackLayout, add an Image and a Label.
4. The Label needs to have enough text and LineBreakMode=TailTruncation.
5. Flip between StackLayout=Horizontal and Vertical. Observe what happens with the long text in the Label.

(See MauiApp4 reproduction repository).

### Link to public reproduction project repository

https://github.com/bugsinkhole/MauiApp4

### Version with bug

8.0.92 SR9.2

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Affected platforms

Android

### Affected platform versions

Android 14

### Did you find any workaround?

No.

### Relevant log output

```shell

```

**Comment by mattleibow** [comment] 2024-11-11 15:50
Duplicate of https://github.com/dotnet/maui/issues/18034

**Comment by mattleibow** [comment] 2024-11-11 15:51
Duplicate of https://github.com/dotnet/maui/issues/10568

**Closed** 2024-11-11 15:51 UTC
Labels: t/bug, area-layout, layout-stack
