### ISSUE TITLE
Interface between platforms: UI

### ISSUE THREAD

**Issue by LyVanBong** [dotnet/maui#17370] opened 2023-09-14 11:43 UTC
### Description

Why don't you make the UI uniform across platforms? If that is done then it would be a great thing for developers to just focus on feature development!
I hope you will consider the above issue

### Public API Changes

Why don't you make the UI uniform across platforms? If that is done then it would be a great thing for developers to just focus on feature development!
I hope you will consider the above issue

### Intended Use-Case

Why don't you make the UI uniform across platforms? If that is done then it would be a great thing for developers to just focus on feature development!
I hope you will consider the above issue

**Comment by jfversluis** [comment] 2023-09-14 12:18
Thanks for the suggestion! I think that would be in the category of drawn controls.

We currently have an experiment with Microsoft.Maui.Graphics.Controls, you might want to check that out. There is another issue describing more about this so I will close this as a duplicate of that one.

**Comment by jfversluis** [comment] 2023-09-14 12:18
Duplicate of #2833

**Closed by jfversluis** 2023-09-14 12:18 UTC
Labels: proposal/open
