### ISSUE TITLE
Editor Sizing Options Do Not Work on Android

### ISSUE THREAD

**Issue by speschka** [dotnet/maui#8313] opened 2022-06-24 17:14 UTC
### Description

When using an Editor control, if I set the HeightRequest to a set value, on an iOS device it works as expected - both when starting with no value for the Text property as well as populating the Text property.  On Android, when setting this property, if the Text property of the control is set then it is displayed correctly.  However if the Text property is not set to anything, then when you start typing in the Editor control, it displays the text one character wide only.  So it just scrolls down one character at a time as you type.

If the AutoSize property is set to TextChanges, it works in both cases (Text property set and not set) on iOS.  On Android, it works fine when the Text property is not set.  However if it is set, it doesn't do an initial resize to display all of the contents.  Instead you only see the first line displayed, until you actually click into the control.  On iOS it does an initial resize so you can see all of the text when the page is loaded.

### Steps to Reproduce

1. Add an Editor control.
2. Set the HeightRequest property to 200.
3. Do not set the Text property.
4. Run on an Android device and start typing; you will see it scroll one character at a time.  Do the same test on iOS, you will see it work correctly.

Alternatively:
1. Add an Editor control
2. Set the AutoSize property to TextChanges.
3. Set the Text property to a value that is long enough make multiple lines.
4. Run on an Android device and you will only see the first line of text until you click in the control.  Do the same test on iOS, you will see it do an initial resize so that you can see all of the contents.

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android API 30 is the only one I tested.

### Did you find any workaround?

No.  I tried fooling around with the HeightRequest and AutoSize properties in the code behind but could not get it to work any better.

### Relevant log output

```shell
N/A
```

**Comment by PureWeen** [comment] 2022-06-25 15:31
@speschka can you upload a repro to github or paste your XAML? The container the Editor lives in plays a big roll in how the autosize code works.

**Comment by innomarcoItalia** [comment] 2022-06-26 10:21
if it can help, it also occurs inside the container ScrollView:
 
 <ScrollView> 
        ----
        <Grid RowDefinitions="250,50">
            <Editor  BackgroundColor="Red"  />
     </Grid>
        ---
    </ScrollView>  

In this case AutoSize="TextChanges" does not resolve.

**Comment by hbraasch** [comment] 2022-07-10 03:10
Here is my similar issue (could be the same), hope it can be fixed also...

The Editor component autosize feature only works well on Windows and iOS. On Android autosize does not autosize correctly. On Android, the component with text changes only resizes and display new line results once the keyboard disappears.

In my case the editor components are in a VerticalStackLayout, inside a ScrollView, and before anyone says one should not do it because there is no way the device will know how large the items should be, let me remind you it works fine on Windows and iOS. Can we just repeat that behaviour.

The repro project can be found here.https://github.com/hbraasch/AutoExpandTester.git

For example, here is how it works under iOS

https://user-images.githubusercontent.com/7484186/178129712-f9cbd7b6-bdbb-4aa1-9737-1e921741cefc.mp4


Here is how it works under Android

https://user-images.githubusercontent.com/7484186/178129724-d9d5dc8a-4eff-4fb7-b0b6-fffcbb7aea33.mp4

**Comment by PureWeen** [comment] 2022-07-28 18:29
Closing as a duplicate of https://github.com/dotnet/maui/issues/8232

**Closed by PureWeen** 2022-07-28 18:29 UTC
Labels: t/bug, area/controls 🎮, s/verified, s/triaged, s/needs-attention
