### ISSUE TITLE
.NET MAUI Blazor Not Showing Blazor Views on iOS Simulator

### ISSUE THREAD

**Issue by techncrypt** [dotnet/maui#12304] opened 2022-12-26 23:49 UTC
### Description

I have tried on a physical device and Mac Catalyst and it works great, it just shows nothing on the simulators which is a bit of an inconvenience. Anyone else running into the same issue?

Update: I have found it to be a bug on the newest VS and Xcode. If I start a new Blazor MAUI project and run the app in a simulator it results in the same.

<img width="396" alt="RxufX" src="https://user-images.githubusercontent.com/61132560/209588858-188f9117-ea5f-43bd-990b-a43ce6d5cc7d.png">

### Steps to Reproduce

1. Create a new .NET MAUI Blazor Hybrid App
2. Update to Newest VS and Xcode.
3. Run to any iOS simulator.

### Link to public reproduction project repository

N/A

### Version with bug

7.0 (current)

### Last version that worked well

6.0.424

### Affected platforms

iOS

### Affected platform versions

iOS 16.2 (Tested)

### Did you find any workaround?

None

### Relevant log output

```shell
N/A
```

**Comment by mkArtakMSFT** [comment] 2022-12-27 17:50
Thanks for contacting us, @techncrypt.
Can you try a MAUI app with Web View (non-Blazor) and see if you can repro this with it? Thanks!

**Comment by Eilon** [comment] 2022-12-27 19:20
This looks to be a duplicate of this issue: https://github.com/dotnet/maui/issues/12124#issuecomment-1359346727

@techncrypt can you confirm which version of Xcode you have on your Mac? It seems that Xcode 14.1 is the latest version supported and that Xcode 14.2 is currently known to not work.

**Comment by techncrypt** [comment] 2022-12-27 20:16
> Thanks for contacting us, @techncrypt. Can you try a MAUI app with Web View (non-Blazor) and see if you can repro this with it? Thanks!

Hi! For the non-Blazor it works fine.

**Comment by techncrypt** [comment] 2022-12-27 20:16
> This looks to be a duplicate of this issue: [#12124 (comment)](https://github.com/dotnet/maui/issues/12124#issuecomment-1359346727)
> 
> @techncrypt can you confirm which version of Xcode you have on your Mac? It seems that Xcode 14.1 is the latest version supported and that Xcode 14.2 is currently known to not work.

I have 14.2, Ill work on downgrading to 14.1 sense thats the case. Thank you for the information.

**Closed** 2022-12-27 20:19 UTC
Labels: t/bug, area/blazor 🕸️, s/needs-attention

**Comment by whann0205** [comment] 2023-01-25 20:45
Any news on this? Encountered the same "feature"....
