### ISSUE TITLE
[iOS] TabBar Icons not showing when using FontIconSource for Tab.Icon

### ISSUE THREAD

**Issue by ewerspej** [dotnet/maui#10350] opened 2022-09-27 16:34 UTC
### Description

The icons of the tabs are not showing up on iOS when using _FontIconSource_ on the _Tab.Icon_ property.

### Steps to Reproduce

1. Create a MAUI App using Shell
2. Add the _materialdesignicons-webfont.ttf_ or any other icon font
3. Register the icon font in MauiProgram.cs using AddFont() in the builder
4. Define the Icons as static resources in App.xaml or any other resource dictionary
5. In AppShell.xaml, add a TabBar with Tabs
6. Use the FontIconSource type on the Tab.Icon property and choose the desired static resource as a glyph
7. Debug on iOS

Expected Behavior: The TabBar displays the Icons from the FontIconSource
Actual Behavior: The TabBar does not display the Icons FontIconSource

Hint: This works fine on Android

Example code:

**Resource Dictionary:**
```xml
  <x:String x:Key="SettingsIcon">&#xF0493;</x:String>
  <x:String x:Key="TimerIcon">&#xF0954;</x:String>
```

**Shell:**
```xml
  <TabBar>
    <Tab
      Title="{x:Static strings:Strings.HomeLabel}">
      <Tab.Icon>
        <FontImageSource
          FontFamily="materialdesignicons"
          Glyph="{StaticResource TimerIcon}"/>
      </Tab.Icon>
      <ShellContent
        ContentTemplate="{DataTemplate views:MainPage}"
        Route="MainPage"/>
    </Tab>
    <Tab
      Title="{x:Static strings:Strings.SettingsLabel}">
      <Tab.Icon>
        <FontImageSource
          FontFamily="materialdesignicons"
          Glyph="{StaticResource SettingsIcon}"/>
      </Tab.Icon>
      <ShellContent
        Title="{x:Static strings:Strings.SettingsLabel}"
        ContentTemplate="{DataTemplate views:SettingsPage}"
        Route="SettingsPage"/>
    </Tab>
  </TabBar>
```

### Link to public reproduction project repository

https://github.com/ewerspej/dotnet-maui-bug-repro-ios-tabs-shell/

### Version with bug

7.0.100-rc.1.22431.12

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15.5

### Did you find any workaround?

No

**Comment by ewerspej** [comment] 2022-09-27 18:13
I will provide an example as soon as possible

**Comment by ewerspej** [comment] 2022-09-28 07:26
@PureWeen here is the repo with the bug and screenshot: https://github.com/ewerspej/dotnet-maui-bug-repro-ios-tabs-shell/

**Comment by ewerspej** [comment] 2022-09-28 18:31
@PureWeen What timeframe are we talking about? The TabBar is useless without icons.

**Comment by sthewissen** [comment] 2022-10-19 12:22
I have something similar, and it seems like they are simply set to the same color as my background (white). When I give them a different background they appear.

```
 <TabBar Route="Main"
        Shell.TabBarTitleColor="Red"
        Shell.TabBarBackgroundColor="Orange"
        Shell.TabBarForegroundColor="Red"
        Shell.TabBarDisabledColor="Green"
        Shell.TabBarUnselectedColor="Yellow">
```

Seems a bit like some of these set colors are overridden internally somewhere (iOS16, iPhone14 Pro emulator).

<img width="344" alt="image" src="https://user-images.githubusercontent.com/2419439/196689420-53e5b17b-a3d4-48df-a227-c63e47a1f219.png">

**Comment by sthewissen** [comment] 2022-10-19 12:30
Seemingly a dupe of #8244 fwiw.

**Comment by ewerspej** [comment] 2022-10-19 12:51
> I have something similar, and it seems like they are simply set to the same color as my background (white). When I give them a different background they appear.

Yes, that's what I have observed, too.

**Comment by ewerspej** [comment] 2022-10-19 12:52
> Seemingly a dupe of #8244 fwiw.

All the more reason to fix it, don't you think? The TabBar is just not usable this way on iOS.

**Comment by sthewissen** [comment] 2022-10-19 13:07
> All the more reason to fix it, don't you think? The TabBar is just not usable this way on iOS.

Wholeheartedly agreed :)

**Comment by NunoBem** [comment] 2023-06-30 13:56
Almost a year later and still this issue it seems. I have my Xamarin apps using this with no problem. 

What's the workaround?  Does in SVG work?

**Comment by jinxinjuan** [comment] 2023-07-07 09:25
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 2.0. Can repro on iOS platform with sample project. [dotnet-maui-bug-repro-ios-tabs-shell/](https://github.com/ewerspej/dotnet-maui-bug-repro-ios-tabs-shell/)

**Comment by chathudan** [comment] 2023-09-11 03:40
@ewerspej did you managed to fix this issue ?

**Comment by ewerspej** [comment] 2023-09-11 08:35
@chathudan Do you mean if I found a workaround? None that is useful for my use cases. The alternative is to use images instead of font icons.

**Comment by SliemBeji-FBC** [comment] 2023-11-03 09:42
> @chathudan Do you mean if I found a workaround? None that is useful for my use cases. The alternative is to use images instead of font icons.

Sadly on my case the images come with their own problems like they wont get sized correctly on Ios Tabbar 
SVG causes crashes on Ios or blackscreens

**Comment by bcaceiro** [comment] 2023-12-16 20:50
Still can reproduce it with latest MAUI version. 
This is quite important and essential..

**Comment by alexpm07** [comment] 2024-04-10 16:27
This issue is still present in .net 8 maui. I think this must be a priority to fix. The advantages in use font icons against images/svg as icons are very valuable.

**Comment by 0xc3u** [comment] 2024-04-12 06:53
I was able to resolve the issue by setting the color of the glyph as demonstrated in the code snippet below.
```

<TabBar>
      <Tab Title="Dashboard">
          <Tab.Icon>
              <FontImageSource FontFamily="FontAwesomeSolid" Glyph="&#xf015;" Color="{StaticResource DefaultDarkGray}"  />
          </Tab.Icon>
          <ShellContent Title="Dashboard" ContentTemplate="{DataTemplate views:DashboardPage}" />
      </Tab>
       ...

</TabBar>

```

**Comment by akhilvswoodplc** [comment] 2024-04-24 13:39
Any update on this issue.
While selecting the Tab, Icon color is not changing only on iOS

**Comment by samhouts** [comment] 2024-06-18 23:27
We agree that this is an important issue. As our [roadmap ](https://github.com/dotnet/maui/wiki/Roadmap) indicates, for the near future, we are focused on:

- Issues impacting Xamarin.Forms upgrades to .NET MAUI
- CollectionView
- Layout

I am marking this as a p/2 issue because it does not meet our focus areas _right now_, but we are constantly revisiting the backlog for important issues to address as time allows. Thank you for your patience and understanding!

**Comment by samhouts** [comment] 2024-06-18 23:28
Duplicate of #8244

**Closed by samhouts** 2024-06-18 23:28 UTC
Labels: t/bug, area-single-project, platform/iOS 🍎, p/2, area-controls-shell, s/verified, s/triaged
