### ISSUE TITLE
ScrollView not working when inside a VerticalStackLayout

### ISSUE THREAD

**Issue by pschubert777** [dotnet/maui#14209] opened 2023-03-26 19:39 UTC
### Description

When putting a ScrollView element within a VerticalStackLayout, the ScrollView stops working. It is happening across Android, MacCatalyst, and IOS. However with IOS, nothing is displayed. 

 I saw that #4176 exists, but it seems like the same issue was reported ,but it was closed.

I have linked to two different branches, one with just the ScrollView and one with the ScrollView inside the VerticalStackLayout

"main" branch - ScrollView Only
https://github.com/pschubert777/CellBoutiqueFlexLayout

"scroll-view-inside-vertical-stack-layout" branch - ScrollView inside a VerticalStackLayout

https://github.com/pschubert777/CellBoutiqueFlexLayout/tree/scroll-view-inside-vertical-stack-layout

Android - Pixel 5, API 33.  -  ScrollView Only

https://user-images.githubusercontent.com/44069136/227798251-1391976c-f8ce-45d8-9d34-a6c309850e2c.mov

IOS - IPhone SE 3rd Gen, IOS 15.4 - ScrollView Only

https://user-images.githubusercontent.com/44069136/227798431-9584f0d0-3fa9-402d-b676-27d4e84a981b.mov

MacCatalyst - MacOS 12.5.1 - ScrollView Only

https://user-images.githubusercontent.com/44069136/227798724-f5a83fed-592c-4aad-9ace-62379d4e91da.mov

Android - Pixel 5, API 33.  -  ScrollView inside a VerticalStackLayout

https://user-images.githubusercontent.com/44069136/227799341-7f3882fe-75fb-441b-8898-1550c1e8df29.mov

IOS - IPhone SE 3rd Gen, IOS 15.4 -  ScrollView inside a VerticalStackLayout

https://user-images.githubusercontent.com/44069136/227799678-d8437123-8e94-4f81-be67-f044218ce92d.mov

MacCatalyst - MacOS 12.5.1  -  ScrollView inside a VerticalStackLayout

https://user-images.githubusercontent.com/44069136/227799662-c2ea0238-bb09-4f05-b7bc-a1df1b0e4fde.mov

### Steps to Reproduce

1. Create a File > New Maui App
2. In MainPage.xaml.cs, create an Observable collection
3. Inside MainPage.xaml, create a VerticalStackLayout
4. Inside the VerticalStackLayout, Create a ScrollView. 
5. Within the ScrollView, add a FlexLayout with a BindableLayout.ItemsSource set to the Observable collection in the MainPage.xaml.cs
6. I expected that the ScrollView inside the VerticalStackLayout would still allow me to scroll but it did not

### Link to public reproduction project repository

https://github.com/pschubert777/CellBoutiqueFlexLayout/tree/scroll-view-inside-vertical-stack-layout

### Version with bug

7.0 (current)

### Affected platforms

iOS, Android, macOS

### Affected platform versions

IOS 16.2/15.4, MacOS 12.5.1, Android API 33

### Did you find any workaround?

No

**Comment by samhouts** [comment] 2023-08-04 18:50
Duplicate of #12452

**Closed by samhouts** 2023-08-04 18:50 UTC
Labels: t/bug, area/layout 🔲, platform/iOS 🍎, s/verified, s/triaged, layout-stack, layout-scrollview
