### ISSUE TITLE
Listview Binding Data not display (in Release)

### ISSUE THREAD

**Issue by ssccinng** [dotnet/maui#11617] opened 2022-11-24 15:56 UTC
### Description

```xaml
<ListView ItemsSource="{Binding Aa}"  
                  MaximumWidthRequest="500" ItemSelected="ListView_ItemSelected">
            <ListView.ItemTemplate>
                <DataTemplate x:DataType="model:SVPokemon">
                        <!--<Label>1</Label>-->
                        
                    <ViewCell>
                        
                        <Grid Padding="10">
                            <Grid.RowDefinitions>
                                <RowDefinition Height="Auto" />
                                <RowDefinition Height="Auto" />
                            </Grid.RowDefinitions>
                            <Grid.ColumnDefinitions>
                                <ColumnDefinition Width="Auto" />
                                <ColumnDefinition Width="Auto" />
                            </Grid.ColumnDefinitions>
                            <Image MaximumWidthRequest="{x:OnPlatform WinUI=50, Android=30}"
                                   Margin="0,-8,0,0"
                                   Source="{Binding}" 
                                   IsAnimationPlaying="False">
                                    
                            </Image>
                            <Label Grid.Column="1"
           
                           Text="{Binding .}"
                           FontAttributes="Bold"
                                   VerticalTextAlignment="Center" />
                            

                        </Grid>
                    </ViewCell>
                </DataTemplate>
            </ListView.ItemTemplate>
        </ListView>
```

![WW_@X8OSDEC7_ S1__S(BOC](https://user-images.githubusercontent.com/22047352/203825420-281424a5-19f7-453a-a7da-dda845ea2943.png)

Debug is work norma;

### Steps to Reproduce

like Description

### Link to public reproduction project repository

https://github.com/ssccinng/PokeSci/tree/master/SVPokeDex

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows, I was *not* able test on other platforms

### Affected platform versions

Android11 win11

**Comment by ssccinng** [comment] 2022-11-24 15:57
w11

**Comment by ssccinng** [comment] 2022-11-24 15:58
![)8X~Y9)DP$G$9G6X_(O}A)Y](https://user-images.githubusercontent.com/22047352/203825899-3e0e3c86-924f-4bf0-9b46-674e3ed12509.png)
Debug

**Comment by mattleibow** [comment] 2022-12-08 12:46
Duplicate of https://github.com/dotnet/maui/issues/11806

**Comment by mattleibow** [comment] 2022-12-08 12:48
There is maybe an issue with XamlC for release, but in your specific case you have a DataType of `model:SVPokemon`, but that is incorrect. The DataType should be of the item, or x:DataType="{x:Type x:String}" because the aa field is an `ObservableCollection<string>`.

See XAML:
https://github.com/ssccinng/PokeSci/blob/master/SVPokeDex/View/PokeDexPage.xaml#L44

See VM:
https://github.com/ssccinng/PokeSci/blob/master/SVPokeDex/ViewModel/PokeDexViewModel.cs#L20

**Comment by mattleibow** [comment] 2022-12-08 12:48
https://github.com/ssccinng/PokeSci/blob/master/SVPokeDex/ViewModel/PokeDexViewModel.cs#L19-L20

**Closed** 2022-12-08 12:49 UTC
Labels: t/bug, platform/android 🤖, area/ListView
