### ISSUE TITLE
CarouselView with GestureRecognisers for Tapped or Clicked stop being able to scroll.

### ISSUE THREAD

**Issue by JoeTomkinson** [dotnet/maui#9664] opened 2022-08-25 21:07 UTC
### Description

Looks like there's some issues between gesture recognisers and complex controls that use gestures under the hood already. Tested on Android Emulator Pixel 5 API 32.5554

Example code snippet below

```
<CarouselView x:Name="cvPets" VerticalOptions="Start" Loop="False" ItemsSource="{Binding Path=FilteredPets}" PeekAreaInsets="200" Margin="0,20,0,0" Grid.Row="2" Grid.Column="0" Grid.ColumnSpan="2">
	<CarouselView.ItemsLayout>
		<LinearItemsLayout Orientation="Horizontal" />
	</CarouselView.ItemsLayout>
	<CarouselView.GestureRecognizers>
		<TapGestureRecognizer NumberOfTapsRequired="1" CommandParameter="{x:Reference cvPets}" Command="{Binding PetSelected}" />
	</CarouselView.GestureRecognizers>
	<CarouselView.ItemTemplate>
		<DataTemplate>
			<ContentView>
				<VerticalStackLayout Spacing="10">
					<Frame
						BorderColor="Transparent"
			   BackgroundColor="{Binding Path=ColorHex, Converter={StaticResource hexToColor}}"
			   CornerRadius="30"
			   Margin="10,10,10,0"
						WidthRequest="200"
						HeightRequest="300"
			   HorizontalOptions="Center"
			   VerticalOptions="CenterAndExpand">
						<Frame.Shadow>
							<Shadow Brush="black" Offset="00,40" Radius="40" Opacity="0.7" />
						</Frame.Shadow>
						<Image Source="{Binding PetImageSource}" Aspect="AspectFit" HeightRequest="200" WidthRequest="200" VerticalOptions="Center" HorizontalOptions="Center" />
					</Frame>
					<Label Text="{Binding PetName}" FontAttributes="Bold" FontSize="18" HorizontalOptions="Center" VerticalOptions="Center" />
					<Grid Margin="0,8,0,0" HorizontalOptions="CenterAndExpand">
						<Grid.ColumnDefinitions>
							<ColumnDefinition Width="auto" />
							<ColumnDefinition Width="auto" />
						</Grid.ColumnDefinitions>
						<Image Grid.Column="0" WidthRequest="25" HeightRequest="25" Source="location_marker" >
							<Image.Behaviors>
								<toolkit:IconTintColorBehavior TintColor="{StaticResource Primary}" />
							</Image.Behaviors>
						</Image>
						<Label Margin="8,0,0,0" Grid.Column="1" Text="{Binding PetLocation}" FontSize="18" HorizontalOptions="Start" VerticalOptions="Center" />
					</Grid>
				</VerticalStackLayout>
			</ContentView>
		</DataTemplate>
	</CarouselView.ItemTemplate>
</CarouselView>
```

### Steps to Reproduce

1. Create template MAUI project from Visual Studio 2022 17.3 template.
2. Add CarouselView to page
3. Setup a GestureRecognizer for Tapped or Clicked
4. Carousel fails to scroll

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android API 32.5554

### Did you find any workaround?

Unfortunately not yet.

**Comment by PureWeen** [comment] 2022-11-18 15:27
Duplicate of #10213

**Closed by PureWeen** 2022-11-18 15:27 UTC
Labels: t/bug, area/collectionview 📃, s/needs-repro, area/gestures
