### ISSUE TITLE
Labels do not resize/reflow on Android when text is changed

### ISSUE THREAD

**Issue by NeilMacMullen** [dotnet/maui#8104] opened 2022-06-16 11:21 UTC
### Description

If you run the application below on Windows, it correctly resizes the label showing the count.  On android, the label will display counts up to 9 but when the count reaches 10 it will only display the first digit '1'

Furthermore, if you set the initial text value of the label to the empty string ("") then NO text will ever be displayed.

![image](https://user-images.githubusercontent.com/9131337/174058337-92d9eed4-7397-4fbe-9b82-eda415c99873.png)

### Steps to Reproduce

Run the application from https://github.com/NeilMacMullen/ProgressBarBug on Android.   

Observe that the label showing the count never displays more than one digit.
In contrast, on windows it correctly resizes.

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Only tested on Android 11

### Did you find any workaround?

Use MinimumWidthRequest property to set initial width

**Comment by NeilMacMullen** [comment] 2022-06-16 11:31
Possibly related: https://github.com/dotnet/maui/issues/8071

**Comment by NeilMacMullen** [comment] 2022-06-16 11:46
Posssible dup of https://github.com/dotnet/maui/issues/8028

**Comment by drasticactions** [comment] 2022-06-16 12:27
You can also verify this with XAML Hot Reload. When you edit a text string the label size doesn't update, leaving it the same size as the original string it had when it rendered.

**Comment by NeilMacMullen** [comment] 2022-06-16 12:32
Actually that's an interesting point - MinimumWidthRequest is also ignored in this scenario.  I.e. changing MinimumWidthRequest with Hot Reload is also not enough to force the label to be resized.

**Comment by jfversluis** [comment] 2022-06-16 13:45
Duplicate of #8028

**Closed by jfversluis** 2022-06-16 13:45 UTC
Labels: t/bug, partner/ui-tools, s/needs-verification
