### ISSUE TITLE
The existence of a WebView prohibits the whole page from rendering on Android

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#13376] opened 2023-02-16 01:34 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/The-existence-of-a-WebView-prohibits-the/10254472)._

---
Create a MauiApp1 project and edit MainPage.xaml:
```XAML
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MauiApp1.MainPage">
	<Grid>
		<Grid.RowDefinitions>
			<RowDefinition/>
			<RowDefinition/>
		</Grid.RowDefinitions>
		<Button Grid.Row="0"/>
		<WebView Grid.Row="1"/>
	</Grid>
</ContentPage>
```

MainPage.xaml.cs:

```CSharp
namespace MauiApp1;

public partial class MainPage : ContentPage
{
	public MainPage()
	{
		InitializeComponent();
	}
}
```
Deploy this project to my USB-connected Android phone and the UI renders nothing but he title Home. The Button is missing. However, if I change the WebView with a Label, the Button appears.

---
#### Feedback Bot on 1/17/2023, 01:38 AM: 

(private comment, text removed)
#### Zack Yang [MSFT] on 1/18/2023, 00:09 AM: 

(private comment, text removed)
#### 帕菲菲 on 1/18/2023, 03:21 AM: 

(private comment, text removed)
#### 帕菲菲 on 1/19/2023, 04:15 AM: 

(private comment, text removed)
#### 帕菲菲 on 1/20/2023, 05:40 AM: 

(private comment, text removed)
#### 帕菲菲 on 1/30/2023, 00:30 AM: 

(private comment, text removed)
#### Zack Yang [MSFT] on 1/18/2023, 11:47 PM: 

(private comment, text removed)
#### Zack Yang [MSFT] on 1/20/2023, 00:44 AM: 

(private comment, text removed)
#### Feedback Bot on 1/30/2023, 00:17 AM: 

(private comment, text removed)
#### Feedback Bot on 1/30/2023, 03:40 AM: 

(private comment, text removed)

---
#### 帕菲菲 solved on 1/17/2023, 05:32 AM, 0 votes: 

<p>A workaround is to put the WebView XAML code line before any other visible elements. All other elements before WebView will become blank, and those after WebView will render normally.</p>

**Comment by PureWeen** [comment] 2023-02-16 19:15
Duplicate of #12040

**Closed by PureWeen** 2023-02-16 19:15 UTC
Labels: area/controls 🎮, control-webview
