### ISSUE TITLE
Unable to hide title bar fron window with blazor hybrid on Windows

### ISSUE THREAD

**Issue by franklbt** [dotnet/maui#17181] opened 2023-09-02 11:36 UTC
### Description

I cannot hide the titlebar space on Windows, despite trying different techniques

### Steps to Reproduce

1. Create a new MAUI Blazor hybrid app
2. Add this code in the MauiProgram.cs:

```csharp
#if WINDOWS
        builder.ConfigureLifecycleEvents(events =>
        {
            events.AddWindows(b => b.OnWindowCreated(win =>
            {
                if (win is not MauiWinUIWindow { AppWindow.Presenter: OverlappedPresenter pre })
                    return;
                
                pre.SetBorderAndTitleBar(true, false);
            }));
        });
#endif
```
3. Add this code to the Platforms/Windows/App.xaml

```xaml
 <maui:MauiWinUIApplication.Resources>
        <ResourceDictionary>
              <Style TargetType="platform:WindowRootView">
                <Setter Property="Template">
                    <Setter.Value>
                        <ControlTemplate TargetType="platform:WindowRootView">
                            <Page Margin="0" Padding="0" x:Name="RootPage">
                                <Grid x:Name="RootGrid" RowSpacing="0" ColumnSpacing="0" Margin="0" Padding="0">
                                    <Grid.RowDefinitions>
                                        <RowDefinition Height="*"></RowDefinition>
                                    </Grid.RowDefinitions>
                                    <ContentControl x:Name="AppTitleBarContainer"
                                                    IsTabStop="False"
                                                    VerticalAlignment="Top"
                                                    VerticalContentAlignment="Stretch"
                                                    HorizontalContentAlignment="Stretch"
                                                    Canvas.ZIndex="1"
                                                    Margin="{Binding WindowTitleBarContainerMargin}"
                                                    DataContext="{Binding RelativeSource={RelativeSource TemplatedParent}}"
                                                    ContentTemplateSelector="{StaticResource MauiAppTitleBarContainerTemplateSelector}">
                                    </ContentControl>
                                    <ContentPresenter Canvas.ZIndex="0"></ContentPresenter>
                                </Grid>
                            </Page>
                        </ControlTemplate>
                    </Setter.Value>
                </Setter>
            </Style>
        </ResourceDictionary>
    </maui:MauiWinUIApplication.Resources>
```

4. Notice that the space for the title bar remains

### Version with bug

8.0.0-preview.7.8842

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

WindowsAppSDK 10.0.22621.0

### Did you find any workaround?

No

**Comment by jfversluis** [comment] 2023-09-04 09:17
Could you see if #17041 maybe fixes it or if the linked issue on that PR seems a duplicate of this issue?

**Comment by franklbt** [comment] 2023-09-04 09:30
@jfversluis in fact the linked issue seems to match the one I submitted.

**Comment by jfversluis** [comment] 2023-09-04 09:54
Alright, marking this as duplicate then, please track the PR/issue for progress, thanks!

**Comment by jfversluis** [comment] 2023-09-04 09:54
Duplicate of #15676

**Closed by jfversluis** 2023-09-04 09:54 UTC
Labels: t/bug, platform/windows 🪟, s/needs-attention
