### ISSUE TITLE
Vertical size not working correctly in grid/stack layout

### ISSUE THREAD

**Issue by NicolaZuc** [dotnet/maui#14991] opened 2023-05-09 07:26 UTC
### Description

So i'm trying to put elements in a cell for a list view and i've found that they were hiding informations.
I then tried to reproduce the problem outside the list view andi've found that there are a lot of resizing problem in grid/stack layout that i can't find a way to address. 
As you can see in the image attacched below, i was expecting to see 4 rows: 
"Sistemare
Sistemare
Sistemare
descrizione"
but app only shows "descrizione".
Am i doing something wrong?

N.B. in xamarin forms everything worked fine, i'm now migrating my app on maui and lot's of graphical things happens.
![image](https://user-images.githubusercontent.com/22391760/237024390-3ab2be3a-c5ab-4563-9bf8-07bd2d7c56b6.png)

### Steps to Reproduce

Here is my sample page

```
<ContentPage
    x:Class="repro.MainPage"
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml">
    <StackLayout HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand">
        <StackLayout
            BackgroundColor="Black"
            HorizontalOptions="FillAndExpand"
            VerticalOptions="FillAndExpand" />
        <Grid
            BackgroundColor="Beige"
            ColumnDefinitions="*,Auto"
            HorizontalOptions="FillAndExpand"
            RowDefinitions="*"
            VerticalOptions="Fill">
            <StackLayout
                Grid.Row="0"
                Grid.Column="0"
                BackgroundColor="White"
                HorizontalOptions="FillAndExpand"
                VerticalOptions="FillAndExpand">
                <Label
                    FontAttributes="Bold"
                    HorizontalOptions="FillAndExpand"
                    VerticalOptions="FillAndExpand">
                    <Label.Text>
                        Sistemare
                        Sistemare
                        Sistemare
                    </Label.Text>
                </Label>
                <Label
                    HorizontalOptions="FillAndExpand"
                    Text="descrizione"
                    VerticalOptions="End" />
            </StackLayout>
            <Label
                Grid.Row="0"
                Grid.Column="1"
                BackgroundColor="Gray"
                HorizontalOptions="End"
                HorizontalTextAlignment="Start"
                Text="icona"
                VerticalOptions="CenterAndExpand"
                VerticalTextAlignment="Center" />
        </Grid>
    </StackLayout>
</ContentPage>
```

### Link to public reproduction project repository

-

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows

### Affected platform versions

-

**Comment by hartez** [comment] 2023-05-10 01:27
This is caused by the same bug that causes #14296 - the grid is assuming the innermost StackLayout should have the same height as the "icona" Label. This is fixed by #14315, and should be in the next service release.

**Closed by hartez** 2023-05-10 01:27 UTC
Labels: t/bug, area/layout 🔲, layout-grid, layout-stack
