### ISSUE TITLE
Blazor FileInput is not working on Android

### ISSUE THREAD

**Issue by suxrobGM** [dotnet/maui#4483] opened 2022-02-02 22:33 UTC
### Description

Blazor `FileInput` component is not working correctly on Android platform. Nothing happened after clicking the "choice file" button  thus can not select any file. However, it works well on Windows platform.

### Steps to Reproduce

1. Add `FileInput` component in anywhere in MAUI Blazor project.
2. Select Android platform to run.
3. Click on button "choice file" then can not select any file.

### Version with bug

Preview 12 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

**Comment by mkArtakMSFT** [comment] 2022-02-03 17:40
Thanks for contacting us. This is a dupe of #2678

**Closed by mkArtakMSFT** 2022-02-03 17:40 UTC
Labels: t/bug, area/blazor 🕸️
