### ISSUE TITLE
Binding a Color from a model is broken on Windows

### ISSUE THREAD

**Issue by jeremy-visionaid** [dotnet/maui#17192] opened 2023-09-04 02:46 UTC
### Description

All model bindings appear to break on Windows when attempting to bind a color (e.g. Label.BackgroundColor)

### Steps to Reproduce

A repo is available here based on CollectionViewDemos from maui-samples:

https://github.com/molesmoke/MauiTestApp/tree/binding

Expected outcome: The view dispays the model data displayed with a red label background
Actual outcome: The view displays only placeholders for the model data

This appears to work OK on Android at least, so probably a Windows-specific issue

### Link to public reproduction project repository

https://github.com/molesmoke/MauiTestApp/tree/binding

### Version with bug

8.0.0-preview.7.8842

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.92

### Affected platforms

Windows

### Affected platform versions

Windows 11

**Comment by XamlTest** [comment] 2023-09-07 09:39
Verified this on Visual Studio Enterprise 17.8.0 Preview 1.0. Repro on Windows 11(8.0.0-preview.7.8842), not repro on Android 13.0-API33 and iOS 16.4 with below Project:
[CollectionViewDemos.zip](https://github.com/dotnet/maui/files/12547241/CollectionViewDemos.zip)

![image](https://github.com/dotnet/maui/assets/97647558/89fb5f39-1380-4494-9558-d4a8e4bcae8e)

**Comment by samhouts** [comment] 2023-09-12 01:19
Duplicate of #16787

**Closed by samhouts** 2023-09-12 01:19 UTC
Labels: t/bug, platform/windows 🪟, s/verified, s/triaged, potential-regression

**Comment by samhouts** [comment] 2023-09-12 01:39
Confirmed that this regressed between [7.0.92...8.0.0-preview.1.7762](https://github.com/dotnet/maui/compare/7.0.92...8.0.0-preview.1.7762). Still reproducible on nightly. Because it can't find the binding on the model, I am 90% sure it's a duplicate of #16787.
