### ISSUE TITLE
[Android] App is crashing after closing app via back button on restarting the app

### ISSUE THREAD

**Issue by tsjdev-apps** [dotnet/maui#5922] opened 2022-04-08 18:55 UTC
### Description

I've used the latest Preview 14 and created a completly empty MAUI app. I've started the app on an Android Emulator with Android 11 from Visual Studio and the default MainPage appears. Now I'm pressing the back button to close the app. If I'm now restarting the app by pressing the app icon the application will crash immediatley with an `System.NotImplementendException: Either set MainPage or override CreateWindow.`.

Tested on Android 11 and Android 12.
On Android 11 it is crashing, on Android 12 everything is working.

### Steps to Reproduce

1. Create a File > New .NET MAUI App
2. Run the application in the Android Emulator
3. Close the app via pressing the hardware back button
4. Start the app via pressing the app icon

### Version with bug

Preview 14 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 11

### Relevant log output

```shell
System.NotImplementedException
  Message=Either set MainPage or override CreateWindow.
```

**Comment by kristinx0211** [comment] 2022-04-10 04:14
not repro on Android 11 with using 17.3.0 Preview 1.0 [32408.253.main].

**Comment by jfversluis** [comment] 2022-04-10 19:27
Duplicate of #5873

**Closed by jfversluis** 2022-04-10 19:27 UTC
Labels: t/bug, s/verified
