### ISSUE TITLE
Microsoft.Maui.Controls.Xaml.Diagnostics.BindingDiagnostics warnings are displayed for a grouped CollectionView with an ItemTemplate

### ISSUE THREAD

**Issue by sjorsmiltenburg** [dotnet/maui#15579] opened 2023-06-12 10:44 UTC
### Description

When debugging (targetplatform windows), I see a lot of BindingDiagnostic warnings, on my own app it is outputting so many of these it slows down the execution of the app.

Microsoft.Maui.Controls.Xaml.Diagnostics.BindingDiagnostics: Warning: 'Name' property not found on 'zz_MauiBugs.ViewModels.Bug4ViewModel', target property: 'Microsoft.Maui.Controls.Label.Text'
Microsoft.Maui.Controls.Xaml.Diagnostics.BindingDiagnostics: Warning: 'Text' property not found on 'zz_MauiBugs.ViewModels.Bug4ViewModel', target property: 'Microsoft.Maui.Controls.Label.Text'

It looks like [this problem](https://stackoverflow.com/questions/76245019/what-is-the-source-of-this-c-sharp-maui-listview-warning-microsoft-maui-control) (but there it references a problem while using the listview), but in my case the view has its x:DataType set properly and i'm using the collectionView. Perhaps because i'm using grouping on my collectionview?

I don't know why Maui is looking at the "main" ViewModel for the property.
It does seems to find it's intended target property for the binding.

### Steps to Reproduce

build reference project and click the "bug4" button

### Link to public reproduction project repository

https://github.com/sjorsmiltenburg/maui_bugs

### Version with bug

8.0.0-preview.4.8333

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

windows

### Did you find any workaround?

no

### Relevant log output

```shell
Microsoft.Maui.Controls.Xaml.Diagnostics.BindingDiagnostics: Warning: 'Name' property not found on 'zz_MauiBugs.ViewModels.Bug4ViewModel', target property: 'Microsoft.Maui.Controls.Label.Text'
Microsoft.Maui.Controls.Xaml.Diagnostics.BindingDiagnostics: Warning: 'Name' property not found on 'zz_MauiBugs.ViewModels.Bug4ViewModel', target property: 'Microsoft.Maui.Controls.Label.Text'
Microsoft.Maui.Controls.Xaml.Diagnostics.BindingDiagnostics: Warning: 'Text' property not found on 'zz_MauiBugs.ViewModels.Bug4ViewModel', target property: 'Microsoft.Maui.Controls.Label.Text'
Microsoft.Maui.Controls.Xaml.Diagnostics.BindingDiagnostics: Warning: 'Text' property not found on 'zz_MauiBugs.ViewModels.Bug4ViewModel', target property: 'Microsoft.Maui.Controls.Label.Text'
Microsoft.Maui.Controls.Xaml.Diagnostics.BindingDiagnostics: Warning: 'Text' property not found on 'zz_MauiBugs.ViewModels.Bug4ViewModel', target property: 'Microsoft.Maui.Controls.Label.Text'
Microsoft.Maui.Controls.Xaml.Diagnostics.BindingDiagnostics: Warning: 'Text' property not found on 'zz_MauiBugs.ViewModels.Bug4ViewModel', target property: 'Microsoft.Maui.Controls.Label.Text'
Microsoft.Maui.Controls.Xaml.Diagnostics.BindingDiagnostics: Warning: 'Text' property not found on 'zz_MauiBugs.ViewModels.Bug4ViewModel', target property: 'Microsoft.Maui.Controls.Label.Text'
Microsoft.Maui.Controls.Xaml.Diagnostics.BindingDiagnostics: Warning: 'Name' property not found on 'zz_MauiBugs.ViewModels.Bug4ViewModel', target property: 'Microsoft.Maui.Controls.Label.Text'
Microsoft.Maui.Controls.Xaml.Diagnostics.BindingDiagnostics: Warning: 'Name' property not found on 'zz_MauiBugs.ViewModels.Bug4ViewModel', target property: 'Microsoft.Maui.Controls.Label.Text'
Microsoft.Maui.Controls.Xaml.Diagnostics.BindingDiagnostics: Warning: 'Text' property not found on 'zz_MauiBugs.ViewModels.Bug4ViewModel', target property: 'Microsoft.Maui.Controls.Label.Text'
Microsoft.Maui.Controls.Xaml.Diagnostics.BindingDiagnostics: Warning: 'Text' property not found on 'zz_MauiBugs.ViewModels.Bug4ViewModel', target property: 'Microsoft.Maui.Controls.Label.Text'
Microsoft.Maui.Controls.Xaml.Diagnostics.BindingDiagnostics: Warning: 'Text' property not found on 'zz_MauiBugs.ViewModels.Bug4ViewModel', target property: 'Microsoft.Maui.Controls.Label.Text'
Microsoft.Maui.Controls.Xaml.Diagnostics.BindingDiagnostics: Warning: 'Text' property not found on 'zz_MauiBugs.ViewModels.Bug4ViewModel', target property: 'Microsoft.Maui.Controls.Label.Text'
Microsoft.Maui.Controls.Xaml.Diagnostics.BindingDiagnostics: Warning: 'Text' property not found on 'zz_MauiBugs.ViewModels.Bug4ViewModel', target property: 'Microsoft.Maui.Controls.Label.Text'
```

**Comment by mattleibow** [comment] 2023-06-12 14:21
@drasticactions  thoughts?

**Comment by XamlTest** [comment] 2023-07-20 09:34
Verified this on Visual Studio Enterprise 17.7.0 Preview 4.0. Repro on Windows 11 .NET 8 with below Project:
[maui_bugs.zip](https://github.com/dotnet/maui/files/12104469/maui_bugs.zip)

**Comment by samhouts** [comment] 2023-08-03 19:46
I'm pretty sure this is not a tooling issue and is instead related to https://github.com/dotnet/maui/issues/13754.

**Comment by augustusdevree** [comment] 2023-08-04 17:10
I encounter the same issue with a ListView here, same warning. The DataTemplate has the correct DataType, and in fact, it compiles, works without error but just shows the warnings in the output window.

**Comment by samhouts** [comment] 2023-09-12 18:31
Duplicate of #16787

**Closed by samhouts** 2023-09-12 18:31 UTC
Labels: t/bug, area/collectionview 📃, s/verified, s/triaged
