### ISSUE TITLE
Resizing the window causes rare flickering

### ISSUE THREAD

**Issue by Fydar** [dotnet/maui#16702] opened 2023-08-11 16:31 UTC
### Description

Resizing the window causes a black flickering across the entire window. 

This happens with or without the debugger, and even in installed Release versions of the application.

Sorry that I can't elaborate further. It's not that much complicated than that. I couldn't find any other reports of this issue in GitHub.

My display is 2560 x 1440 @ 120hz, 10-bit depth, SDR, AMD FreeSync.
![image](https://github.com/dotnet/maui/assets/19309165/e6c6788d-5352-4415-8f21-554632e19dc3)

Tested on Windows 11.

### Steps to Reproduce

1. Create an empty MAUI project (tested with both Blazor Hybrid and blank MAUI applications, but Blazor Hybrid applications have a white screen so the flickering is easy to see)
2. Launch the project (with or without the debugger)
3. Resize the window by dragging the corner or the edge around the screen. It typically takes me 3-4 seconds before a noticeable flicker happens. 

### Version with bug

8.0.0-preview.7.8842

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Windows SDK 10.0.19041.0

**Comment by drasticactions** [comment] 2023-08-14 08:02
Possibly fixed by https://github.com/dotnet/maui/pull/16637

**Comment by mattleibow** [comment] 2023-08-16 18:27
Duplicate of https://github.com/dotnet/maui/issues/11777

**Closed by mattleibow** 2023-08-16 18:27 UTC
Labels: t/bug, area/desktop 🖥️
