### ISSUE TITLE
Extend the button class with a 'content' button

### ISSUE THREAD

**Issue by ITD-SKP-Project** [dotnet/maui#24747] opened 2024-09-13 06:27 UTC
### Description

the button clas iss very limited, for instance creating a button where the contents (text/icon) is left justified inside a button that spans the width of the screen, is very painful.
https://learn.microsoft.com/en-us/answers/questions/2041491/net-maui-8-how-to-implement-a-button-that-fills-it?comment=answer-1814235&page=1#comment-1778508

If the Button class was extended so it could take 'content' (grid, stack etc.) then designs would be much more straightforward, also buttons would behave more like other viewelements.

### Public API Changes

            var thisButton = new Button
            {
                Content= myGrid
            };

### Intended Use-Case

any sort of ui designs

**Comment by AndreasReitberger** [comment] 2024-09-13 09:03
Seems to be a duplicate of https://github.com/dotnet/maui/issues/8191

**Comment by jfversluis** [comment] 2024-09-13 09:06
Duplicate of https://github.com/dotnet/maui/issues/8191

**Closed by jfversluis** 2024-09-13 09:06 UTC
Labels: proposal/open
