### ISSUE TITLE
[Android] Blazor hybrid back navigation

### ISSUE THREAD

**Issue by Kebechet** [dotnet/maui#23381] opened 2024-07-01 11:06 UTC
### Description

When I open default template of `.NET MAUI Blazor hybrid app` and I run it on Android 14.0 (API 34) then after performing GO-BACK gesture the app correctly minimize but when I want to reopen it it gets stuck on initial loading

https://github.com/dotnet/maui/assets/37485681/44206117-fa2a-4f2b-b2bf-ac41bbdb8416

### Steps to Reproduce

1) Create empty `.NET MAUI Blazor hybrid app`
2) run it on android device
3) perform a back gesture or click back button
4) try to open the app after it is minimized

### Version with bug

8.0.61 SR6.1

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 14.0 (API 34)

### Did you find any workaround?

no

**Comment by jfversluis** [comment] 2024-07-01 12:47
Duplicate of #22819

**Closed by jfversluis** 2024-07-01 12:47 UTC
Labels: t/bug
