### ISSUE TITLE
Deployment of App in Release mode on local iPhone uses type UIKit.UISceneSessionActivationRequest and therefore breaks with iOS 16.2 

### ISSUE THREAD

**Issue by MAUIoxo** [dotnet/maui#20424] opened 2024-02-07 15:52 UTC
### Description

I wanted to deploy my .NET MAUI App built with the latest .NET MAUI version as Release on my iPhone compiled with the following MAUI Version:

```xaml
<MauiVersion>8.0.7-preview.9929</MauiVersion>
``` 

Unfortunately, I when I try this as **Release** on my local iPhone, I get the message below telling me there is a method and parameter used that is introduced in iOS 17.0. Therefore we break with a 16.2 for instance?

In **Debug** it is just fine and I can run my app on an iPhone 16.2. Simulatoro without any problems. Only in **Release** it leads to an error.

Currently, I don't know the intention of the use of this method and parameter just in **Release**, but I see it as **breaking with 16.2** as this can't then be used anymore. I could not find any information about this breaking change and also not just in **Release** and it is working fine in **Debug**. Therefore, it is a bug for me!

There are also developers that can't update their XCode as recommended in the error message and therefore we will lose compatibility:

`Error   MT4162  The type 'UIKit.UISceneSessionActivationRequest' 
(used as a parameter in UIKit.UIApplication.ActivateSceneSession) 
is not available in iOS 16.2 (it was introduced in iOS 17.0). 
Please build with a newer iOS SDK (usually done by using the most recent
version of Xcode).`

![Ex66h](https://github.com/dotnet/maui/assets/140683727/9fe72225-13c3-48df-b2cd-95244226e970)

### Steps to Reproduce

1. Use `<MauiVersion>8.0.7-preview.9929</MauiVersion>` 
2. Start debugging the app in **Debug** mode on an iPhone Simulator 16.2 with **XCode 14.2** and see it works
3. Try to deploy the same App as **Release** on a local iPhone 16.2 with **XCode 14.2** and you'll get the following error output

`Error   MT4162  The type 'UIKit.UISceneSessionActivationRequest' 
(used as a parameter in UIKit.UIApplication.ActivateSceneSession) 
is not available in iOS 16.2 (it was introduced in iOS 17.0). 
Please build with a newer iOS SDK (usually done by using the most recent
version of Xcode).`

![Ex66h](https://github.com/dotnet/maui/assets/140683727/9fe72225-13c3-48df-b2cd-95244226e970)

4. This is breaking for a lot of developers working on previous versions of XCode and knocks them out. And why only in **Release**? Where can we see that there is a breaking change? Is there a workaround?

### Version with bug

8.0.7-preview.9929

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.0-preview.7.8842

### Affected platforms

iOS

### Affected platform versions

iOS 16.2 on XCode 14.2

### Did you find any workaround?

Unfortunately, no workaround so far. Is there any? Otherwise please try to avoid the method and parameter from the error message

**Comment by drasticactions** [comment] 2024-02-08 02:42
Searching the repo,

https://github.com/dotnet/maui/pull/18384/commits/e735b54426878f0335af910c5fcf835f674fb4f2

There is only one place that calls `UISceneSessionActivationRequest.Create`, and it's wrapped around a version tag so it. It was added in October 2023 and it's in version 8.0.3 and 8.0.6. It's not new and in the currently shipping stable. It's showing up when you build in Release mode because, as shown in the error message, of the Linker. That's run by default on Release builds, and not Debug. 

So I don't think this is a "regression" in the preview builds. Unless I'm missing something, this code has been shipping since 8.0 RTM.

You can still target, deploy and build your app for 16.2, but you need to upgrade Xcode and iOS SDK. The minimum versions of what iOS version you can target is not the same as requirements used to build the app itself. If you wanted to package and release your application, as far as I know, you will need to build on the newest Xcode released. I understand that bumping Xcode isn't trivial (Versions above 14.2 require macOS 13.0+) but it's also a release from December 2022. At some point, you have to upgrade.

@rolfbjarne Am I missing anything? Is there anything else they could do?

**Comment by MAUIoxo** [comment] 2024-02-08 06:13
I don't get it completely, when looking at this Code. I would expect that it still can be compiled with previous Codes and then not using the new Code.

My problem with the behavior and the sentence "At some point, you have to upgrade." is that there are a lot of people that even can't do an upgrade. XCode is bound to a certain version of Mac OS. If you can't upgrade your Mac OS, and therefore XCode, you are done with your current development.

The current behavior is therefore a breaking change when you need higher versions which are bundled like this so extremely. The current MAUI development is still for new 8.x releases and I would not suggest breaking changes at all when the major version is not changed.

If you are not able to upgrade your Mac OS with your Mac you need new Hardware and you know the prices. We are not talking about "bumping Xcode isn't trivial", we are talking about high investments not only for commercial development projects but also for private ones (which do have the least financial possibilities). I would really suggest to have something like a compatibility mode which allows to compile it in Release with older XCode versions than the current which still have been supported up to now.

@rolfbjarne - "Am I missing anything? Is there anything else they could do?" this is the right question for me also right now. My development project is done with that right now unless I spend a thousand dollards for ne Hardware.

**Comment by rolfbjarne** [comment] 2024-02-08 06:32
@drasticactions is correct, the fix is to build using a newer version of Xcode.

I understand that a newer version of Xcode will potentially require a newer macOS version, which in turn may require new hardware, which is expensive.

We could spend a lot of time and effort to make sure that we work on older versions of Xcode, but that won't solve the minimum Xcode requirements in order to publish to the App Store. Currently it's Xcode 14.3, but in May 2024 Apple will start requiring Xcode 15.0 - at which point all our efforts to work with an older version won't mean anything at all (["Please note that as of April 2024 all iOS and iPadOS apps submitted to the App Store must be built with a minimum of Xcode 15 and the iOS 17 SDK"](https://developer.apple.com/ios/submit/))

One alternative would be to use an older version of Maui, .NET and the iOS workload.

**Comment by MAUIoxo** [comment] 2024-02-08 06:51
Does ["Please note that as of April 2024 all iOS and iPadOS apps submitted to the App Store must be built with a minimum of Xcode 15 and the iOS 17 SDK"](https://developer.apple.com/ios/submit/) also mean that .NET 7 Versions can't be brought to the App Store then?

Well, yes what you've said is the bottom line then - what a pitty :(

**Comment by drasticactions** [comment] 2024-02-08 07:27
> Does ["Please note that as of April 2024 all iOS and iPadOS apps submitted to the App Store must be built with a minimum of Xcode 15 and the iOS 17 SDK"](https://developer.apple.com/ios/submit/) also mean that .NET 7 Versions can't be brought to the App Store then?
> 
> Well, yes what you've said is the bottom line then and that's even worse then - what a pitty :(

.NET 7 MAUI support is until May 14th, 2024 
https://dotnet.microsoft.com/en-us /platform/support/policy/maui

So yes, you would need to upgrade to .NET 8 if you wish to submit to the App Store. The tooling itself should still "work" outside of support, and for platforms like Mac Catalyst you could continue to release applications outside of the Store.

I agree with @rolfbjarne here. I totally understand that upgrades can be hard, especially if it requires new hardware or bandwidth to get the Xcode. But there's only so much we can do given that Apple decides which Xcodes and SDKs can be used to release with, and we do our best to match that.

I am closing this issue. There is nothing to fix on our side. If you can, please upgrade your Xcode and SDKs. If you're still having issues once you do so, feel free to open this issue again. And again, I'm sorry.

**Closed by drasticactions** 2024-02-08 07:27 UTC
Labels: t/bug, partner/macios, potential-regression

**Comment by MAUIoxo** [comment] 2024-02-08 07:54
Could you please add a Hint to the **Readme** in the initial page of this project or so, so that this is more obvious also for others that they have to prepare?

**Comment by JORGEGO** [comment] 2024-03-05 16:36
A couple of weeks ago we migrated all our applications to .NET MAUI 8.0. Everything has gone very well for us, except when generating the IOS versions. that gives us a commented error, but that we do not see based on the reading how we should proceed. We have the latest version of xCode on our Mac. We have the latest version of VIsual Studio, but it is impossible for us to generate the version. How can you help us?

1>C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk\17.2.8004\tools\msbuild\iOS\Xamarin.iOS.Common.After.targets(364,3): error IL7000: An error occured while executing the custom linker steps. Please review the build log for more information.
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk\17.2.8004\tools\msbuild\iOS\Xamarin.iOS.Common.After.targets(364,3): error MT4162: The type 'UIKit.UISceneSessionActivationRequest' (used as a parameter in UIKit.UIApplication.ActivateSceneSession) is not available in iOS 16.2 (it was introduced in iOS 17.0). Please build with a newer iOS SDK (usually done by using the most recent version of Xcode).
1>
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk\17.2.8004\tools\msbuild\iOS\Xamarin.iOS.Common.After.targets(364,3): error MT2362: The linker step 'Registrar' failed during processing: The type 'UIKit.UISceneSessionActivationRequest' (used as a parameter in UIKit.UIApplication.ActivateSceneSession) is not available in iOS 16.2 (it was introduced in iOS 17.0). Please build with a newer iOS SDK (usually done by using the most recent version of Xcode).
1>
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk\17.2.8004\tools\msbuild\iOS\Xamarin.iOS.Common.After.targets(406,3): error MSB3371: The file "obj\Release\net8.0-ios\ios-arm64\linked\Link.semaphore" cannot be created. Could not find a part of the path 'C:\gm\greenyng.mobile\greenyng.mobile.citizen\obj\Release\net8.0-ios\ios-arm64\linked\Link.semaphore'.
1>Done building project "greenyng.mobile.citizen.csproj" -- FAILED.

**Comment by rolfbjarne** [comment] 2024-03-05 16:42
@JORGEGO 

> We have the latest version of xCode on our Mac.

The problem is that you're building with some version of Xcode 14 (probably Xcode 14.3), not the latest (Xcode 15.2).

**Comment by JORGEGO** [comment] 2024-03-05 16:47
Thank you, I'm probably asking something very stupid and my IOS team should ask the questions better, sorry for that, but I have installed the latest version of Xcode 15 that appears in the Apple Store, how can I install a later version...?

**Comment by rolfbjarne** [comment] 2024-03-05 16:51
> Thank you, I'm probably asking something very stupid and my IOS team should ask the questions better, sorry for that, but I have installed the latest version of Xcode 15 that appears in the Apple Store, how can I install a later version...?

Which version of macOS itself do you have installed?

**Comment by JORGEGO** [comment] 2024-03-05 16:53
If you allow me, I will answer it tomorrow, now I am not in front of the team. We will see if we have the latest version. Thank you for your support

**Comment by JORGEGO** [comment] 2024-03-06 13:02
Our Mini Mac is 2014, so it cannot be update... we need to buy a new Mini Mac :(

**Comment by MAUIoxo** [comment] 2024-03-06 15:28
Had the same problem recently and had to buy a new one. Real pitty. But seems to be a problem on The Apple side actually :(
