### ISSUE TITLE
R8 : warning : Missing class androidx.window.extensions.WindowExtensions

### ISSUE THREAD

**Issue by tranb3r** [dotnet/maui#10901] opened 2022-10-25 15:23 UTC
### Description

When building a dotnet maui app for net6.0-android with R8 enabled, I get the following warning:
R8 : warning : Missing class androidx.window.extensions.WindowExtensions

Could be related to https://github.com/xamarin/xamarin-android/issues/6809

### Steps to Reproduce

1. Create a Maui app for net6.0-android.
2. Enable R8 (add <AndroidLinkTool>r8</AndroidLinkTool> PropertyGroup to csproj for Release configuration).
3. Build the app for Release configuration.
4. Check the build log

### Link to public reproduction project repository

https://github.com/tranb3r/SecureHttpClient/tree/maui

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

net6.0-android31.0

**Comment by PureWeen** [comment] 2022-10-25 18:06
@jonathanpeppers

**Comment by jonathanpeppers** [comment] 2022-10-25 18:49
This is duplicate of https://github.com/xamarin/xamarin-android/issues/6809, do we just close it?

The gist, is there are some "optional" `.jar` files and r8 warns if it can't find them. OEMs put them on some devices, and we are not sure of the right fix yet. At the time, some of these packages were still listed versioned as `alpha`...

**Comment by angelru** [comment] 2022-12-15 21:05
the same issue:
`R8 : warning : Missing class androidx.window.extensions.WindowExtensions (referenced from: androidx.window.extensions.layout.WindowLayoutComponent androidx.window.layout.SafeWindowLayoutComponentProvider$windowLayoutComponent$2.invoke())`

**Comment by jonathanpeppers** [comment] 2022-12-15 22:03
If you want to suppress these warnings, you can set these in your `.csproj`:
```xml
<AndroidD8ExtraArguments>--map-diagnostics warning info</AndroidD8ExtraArguments>
<AndroidR8ExtraArguments>--map-diagnostics warning info</AndroidR8ExtraArguments>
```

**Comment by jonathanpeppers** [comment] 2022-12-15 22:22
We're going to be able to suppress these warnings in .NET 8: https://github.com/xamarin/xamarin-android/pull/7643

But I would use the workaround above for now.

**Comment by tranb3r** [comment] 2022-12-16 07:33
In xamarin/xamarin-android/issues/6809, I understood that ignoring warnings was not an option.
Why have you changed your mind about that ?
Is there really no other option ?

**Comment by jonathanpeppers** [comment] 2022-12-16 14:46
The problem is these warnings are not actionable, so they are not useful. In my opinion, the purpose of a warning is to say "improve your code by doing this".

For the long-term fix, I installed the AndroidX packages one-by-one that MAUI depends on, and it appears `Xamarin.AndroidX.Legacy.Support.V4` is the cause. I believe this is only for supporting *really* old Android versions? We could stop using this package in MAUI, but I haven't looked into how it's used yet.

**Comment by tranb3r** [comment] 2022-12-16 15:22
> The problem is these warnings are not actionable, so they are not useful. In my opinion, the purpose of a warning is to say "improve your code by doing this".

I disagree.
Maybe this very specific warning is not actionable.
But usually when I get a warning from R8, I need to do something, either fix my code or modify proguard rules.
So, in my opinion, disabling all R8 warnings is not a very good solution.

**Comment by jonathanpeppers** [comment] 2022-12-16 15:57
@tranb3r can you share a sample project that illustrates this?

**Closed** 2023-01-04 17:39 UTC
Labels: t/bug, platform/android 🤖, s/needs-info, area/publishing 🏁, s/no-recent-activity
