### ISSUE TITLE
Key presses and key combinations on inputs and pages

### ISSUE THREAD

**Issue by bwoebi** [dotnet/maui#3858] opened 2021-12-24 18:47 UTC
### Description

On Desktop, and also on mobile with hardware keyboards, one may press key combinations. It should be possible to intercept these key presses with MAUI, on the page and input (basically focussable elements - mainly Entry and Editor) level.

The event is first delivered to focussed elements, then to the page as last resort.

On an Editor, the events would be equivalent to e.g. TextBox.PreviewKeyDown on uwp or AppCompatEditText.KeyPress (with `Android.Views.View.KeyEventArgs.Event?.Action == Android.Views.KeyEventActions.Down`) on Android and `UIResponder.PressesBegan` on iOS/MacCatalyst. Similarly KeyUp can be implemented. For virtual keyboards on iOS, the KeyUp and KeyDown events can be emulated with support from e.g. UITextFieldDelegate.ShouldChangeCharacters, to provide a seamless experience.

Edit: I just found #3739 - which is quite related, but what I'm suggesting here is listening to specific key events in a streamlined way. That issue is only global events and exposing Keyboard State access, which is also desirable, additionally to this feature.

#### Usage example

```csharp
// Similarly possible with KeyUp
MyEditor.KeyDown += (object sender, KeyEventArgs e) {
  if (e.Key == Key.Enter && e.Shift) {
    SubmitText(MyEditor.Text);
    MyEditor.Text = "";
    e.Handled = true;
  }
}; 
```

#### Public API suggestion
```csharp
class KeyEventArgs {
  public bool Handled = false;
  public KeyCode Key { get; }
  public string? Characters { get; } // like Android.Views.KeyEvent.characters or the ToAscii function from user32.dll 
  public bool Shift { get; }
  public bool Ctrl { get; }
  public bool Alt { get; }
  public bool Meta { get; }
  public bool HasModifiers => Shift || Ctrl || Alt || Meta;
  public bool VirtualKeyboard { get; } // to distinguish whether the key was pressed on hardware or on-screen keyboard
}

// this enum contains all KeyCodes possibly present on any OS. There must be a proper mapping for each target.
enum KeyCode {
  A,
  B,
  Enter,
  // etc - with some platform independent numbering
}
```

I'm trying to keep the API minimal for this issue, but there may be more common aspects on all targets which can be included here.

### Intended Use-Case

A trivial shortcut like the ctrl+s key combination could trigger a save.

Pressing a key like shift+enter over a specific selection in an editor could trigger a submission (instead of inserting a new line).

**Comment by Redth** [comment] 2023-01-12 18:54
Related to #3739

**Comment by eidylon** [comment] 2023-04-21 17:01
How in the world, a `UI framework` got out of the gate with no mechanisms for responding to keyboard events baffles me, to put it mildly.

**Comment by Simoneye1011** [comment] 2023-05-06 10:31
excuse,your answer is for maui?but maui we couldnot access keydown,how did you do it?

**Comment by Simoneye1011** [comment] 2023-05-06 10:35
Public API Changes??how to find this API?Public API suggestion,THIS API is write by your self?do you have this project code source in github?

**Comment by ToolmakerSteve** [comment] 2023-05-09 01:52
@Simoneye1011 - it is a suggestion. No code exists.

**Comment by Simoneye1011** [comment] 2023-05-09 07:15
@ToolmakerSteve ohbuddy,your suggestion is a GOOD idea,also i need it,but i really need implement,i know there a way,cutomize control Entry,use mapper,handler,but i dont how to implement it :)

**Comment by faustmet** [comment] 2023-07-10 20:33
Some examples of key combinations we might want are:
- programmable key combinations to send commands in an app
- default key combinations to export to file, save, other frequent operations

**Comment by PureWeen** [comment] 2023-07-18 21:51
Duplicate of #16202
Duplicate of #16217

**Closed by PureWeen** 2023-07-18 21:51 UTC
Labels: proposal/open, partner, partner/cat 😻, area/controls 🎮, control-entry

**Comment by samhouts** [comment] 2023-07-27 16:15
Duplicate of 16202
