### ISSUE TITLE
On Windows - MAUI Label with InputTransparent="true" does still take the click event

### ISSUE THREAD

**Issue by maexsp** [dotnet/maui#26678] opened 2024-12-17 13:55 UTC
### Description

Placing a Label above a Button on MAUI WinUI does not work with setting InputTransparent=true. So always when click/tap on the Label than the event is not sent to the Button! See the attached gif screener.

First Button shows the issue in this sample. The 2nd shows a kind of workaround with ContentView and the last Button shows the default button (which unfortunately cannot have custom mixed content).

```<!-- MAUI issue -->
<Grid Background="Blue">
    <Button Clicked="OnCounterClicked" Opacity="0.3"/>
    <Label Text="Button with Label" InputTransparent="True" TextColor="Black" VerticalOptions="Center" Background="Gray" HorizontalOptions="Center"/>
</Grid>

<!-- MAUI workaround -->
<Grid Background="Green">
    <Button Clicked="OnCounterClicked" Opacity="0.3"/>
    <ContentView InputTransparent="True">
        <Label Text="Button ContentView+Label" TextColor="White" VerticalOptions="Center" Background="Black" HorizontalOptions="Center"  />
    </ContentView>
</Grid>

<!-- MAUI plain button -->
<Grid Background="red">
    <Button  Text="Button only button" TextColor="White" Clicked="OnCounterClicked"/>
</Grid>
```

### Steps to Reproduce

Use the above code in the MAUI default sample. Edit code behind to setup up the counter on the label to see the effect.

![Image](https://github.com/user-attachments/assets/150049ba-a80f-4a15-9703-a32b035347af)

### Version with bug

9.0.21 SR2.1

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Did you find any workaround?

The workaround is also in the sample code. Use a ContentView around the Label.

### Relevant log output

```shell

```

**Comment by jfversluis** [comment] 2024-12-17 14:52
Duplicate of #21384

**Closed by jfversluis** 2024-12-17 14:52 UTC
Labels: t/bug
