### ISSUE TITLE
PushModalAsync method does not respond in OnAppearing method

### ISSUE THREAD

**Issue by cris-m** [dotnet/maui#7478] opened 2022-05-25 15:27 UTC
### Description

Calling `PushModalAsync` does not navigation when it is being called in `OnAppearing `.
```csharp
using MobileApp.Views;

namespace MobileApp;

public partial class MainPage : ContentPage
{
    public MainPage()
    {
        InitializeComponent();
    }
    protected override void OnAppearing()
    {
          base.OnAppearing();
  
          if (OnBoardingPage() )
          {
              Navigation.PushAsync(new OnBoardingPage(), false);
          }
      }
    private bool OnBoardingPage()
    {
        return VersionTracking.IsFirstLaunchEver;
    }
}
```

### Steps to Reproduce

1.  Create a new project and in a new view call override ``OnAppearing`` method
2.  Call `PushModalAsync` to navigate to another page

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, macOS

### Affected platform versions

iOS15, Android 11 and up

**Comment by kristinx0211** [comment] 2022-05-26 03:18
@cris-m thanks for your report, I verify this issue on android 12 and IOS 15.4. but it is not repro. the `OnAppearing` can be called and navigate to `OnBoardingPage `. could you see my attached repro video and let me know if I miss something for this. repro project: [MauiApp6.zip](https://github.com/dotnet/maui/files/8775987/MauiApp6.zip)
![7478](https://user-images.githubusercontent.com/99457000/170409078-66d067f5-5b60-464d-9650-968fdbd3af3e.gif)

**Comment by cris-m** [comment] 2022-05-26 03:44
I have seen the project in zip file and it is working. I was not using Shell. I tried with shell and it responded to the navigation. Without using shell it doesn't respond.

**Comment by kristinx0211** [comment] 2022-05-26 06:01
@cris-m yes. thanks. I can repro this without using shell.

**Comment by PureWeen** [comment] 2022-11-30 19:34
Duplicate of #8157

**Closed by PureWeen** 2022-11-30 19:34 UTC
Labels: t/bug, area/modal, s/verified
