### ISSUE TITLE
WebView HTML5 Games not loading

### ISSUE THREAD

**Issue by Maverick1983** [dotnet/maui#8241] opened 2022-06-22 15:03 UTC
### Description

Add WebView and Source with HTML5 Games public Url. On Desktop browser it's working, on WebView not loading

### Steps to Reproduce

1. Create .Net Maui Application
2. Add WebView
3. Add (for example) this HTML5 public url Games (https://play.famobi.com/smarty-bubbles-2/A-FAMOBI-COM)
4. WebView not load the Game

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 8, Android 9, Android 7

### Did you find any workaround?

No

**Comment by drasticactions** [comment] 2022-06-22 20:53
Did you try running the app in the default Android browser? Does it work there?

Did you try building an Android app without MAUI (Ex. `dotnet new android), adding a webview, and trying it there? did it fail?

**Comment by Maverick1983** [comment] 2022-06-23 06:17
Hi, with Android browser working.
I will test with with Android app without MAUI

**Comment by Maverick1983** [comment] 2022-06-23 20:56
Tested with Android Project (not MAUI) and it's working

**Comment by drasticactions** [comment] 2022-06-24 02:51
Can you upload a repro project of it?

**Comment by Maverick1983** [comment] 2022-06-24 08:18
> Can you upload a repro project of it?

The repo for test it https://github.com/Maverick1983/dotnet-maui-test

**Comment by kristinx0211** [comment] 2022-06-24 09:40
> > Can you upload a repro project of it?
> 
> The repo for test it https://github.com/Maverick1983/dotnet-maui-test

no files in the git path. could you take a look.

**Comment by kristinx0211** [comment] 2022-06-24 10:27
@Maverick1983 run on android 11 and 12, the games can be loaded.
![image](https://user-images.githubusercontent.com/99457000/175516697-9cb36fec-9fc1-44bf-a481-a0926df1f8c7.png)

**Comment by Maverick1983** [comment] 2022-06-24 11:45
> @Maverick1983 run on android 11 and 12, the games can be loaded. is this your expected result? ![image](https://user-images.githubusercontent.com/99457000/175516697-9cb36fec-9fc1-44bf-a481-a0926df1f8c7.png)

.net MAUI?

**Comment by kristinx0211** [comment] 2022-06-27 07:03
@Maverick1983 no, this is the test result with android project, I mean I've verified web view source can be load with android project, but does not work with MAUI.

**Comment by Maverick1983** [comment] 2022-06-27 07:41
> @Maverick1983 no, this is the test result with android project, I mean I've verified web view source can be load with android project, but does not work with MAUI.

So on MAUI it's a bug?

**Comment by jsuarezruiz** [comment] 2022-10-18 15:37
Cannot reproduce the issue using net7 rc1 version.
![issue-8241](https://user-images.githubusercontent.com/6755973/196477136-ecc240d5-4168-4dc1-8d23-d3a40ef7f601.png)

Could you try with latest version?. If still continue having issues, could you attach a small sample where reproduce the problems?

**Comment by MobileDev327** [comment] 2022-10-18 18:48
> Cannot reproduce the issue using net7 rc1 version. ![issue-8241](https://user-images.githubusercontent.com/6755973/196477136-ecc240d5-4168-4dc1-8d23-d3a40ef7f601.png)
> 
> Could you try with latest version?. If still continue having issues, could you attach a small sample where reproduce the problems?

Hello @jsuarezruiz,
Thank you for your response I just tested it on mine and it is working as well. Thank you!

I am working with:
Visual Studio: 
17.4.0 Preview 3.0

.NET SDK:
Version:   7.0.100-rc.2.22477.23

**Comment by Maverick1983** [comment] 2022-10-20 11:31
Sorry I can't test it because now I have another error [https://github.com/dotnet/maui/issues/10802](https://github.com/dotnet/maui/issues/10802)

**Comment by Maverick1983** [comment] 2022-10-25 09:29
Tested.

On real device in debug it's working.
On simulated device on PC it's not working. Example URL [Test URL HTML5 Game](https://bot.botelegram.top/games/candy-bubble/?fg_domain=bot.botelegram.top&fg_aid=A1000-1&fg_uid=c5e12171-a07f-4335-bd2a-8b7e4c3aa8ad&fg_pid=4638e320-4444-4514-81c4-d80a8c662371&fg_beat=630&original_ref=)

**Comment by mattleibow** [comment] 2022-12-12 22:53
OK, so I did some more testing and I think I know what is happening and explains all the things in the comments on this issue:

* The game does not have an intrinsic size, so the webview has a size of 0x0
* If you keep the webview in the stack and give it a height, it works
* If you put the wbview at the root, it works

The main issue is that the game has no basic size at the start so the webview gets a size of 0x0. The, the game boots and starts to play (or not actually) at that 0x0 size - meaning no game is visible.

You can see the webview size in Android Studio: `height = 0dp`

![image](https://user-images.githubusercontent.com/1096616/207172119-3deca715-faa7-442e-9435-07f2f198f52a.png)

I am closing this issue as it is not really a bug but more the systems working as designed - but in a situation in which the designers did not consider.

If you want to "stack" views then it is best to use a `Grid` with a few rows, one of which is `*` so that it fills the space - but not exceeding the phone screen. If you want to scroll as well, then maybe a `MinimumHeightRequest` is best?

**Closed by mattleibow** 2022-12-12 22:53 UTC
Labels: t/bug, area/controls 🎮, s/verified, control-webview, s/triaged, s/needs-attention
