### ISSUE TITLE
Example doesn't work

### ISSUE THREAD

**Issue by dankodima1** [dotnet/maui#12683] opened 2023-01-16 07:19 UTC
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/run#
Operating System: windows

The example doesn't work. 
Why someone from Microsoft can't investigate and fix all the problems? Why everybody should waste itself time to broken example?

I think author of this topic (https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/run#) should not be programmer. It is not professional to public not worked example. 

I just lost my time. Every time than I open microsoft examples - they don't work EVERYTIME. But examples from other websites works. Microsoft Visual Studio examples not professional. That's all

**Comment by dankodima1** [comment] 2023-01-16 07:19
It's just NOT STARTS without errors.

**Comment by drasticactions** [comment] 2023-01-16 07:34
The issue you are having is with the MAUI Template. Do you have any error messages to share? Which platform were you trying to deploy to? Windows? Android? iOS?

**Comment by dankodima1** [comment] 2023-01-16 07:39
there is no ERRORS. The main idea was - If it is not work, why it active on the microsoft example side. 
I made the steps in the example. It's just not started. 

The author developer should test it on the clear windows from start to end and FILL ALL steps to make this project. If I have the problem - this means that example in general doesn't work and doesn't make sense in it. 
The example named as "First steps" - and they should work with any conditions. But they don't.

I don't have an idea what to do because I googled FIRST STEPS to start coding on it.

**Comment by dankodima1** [comment] 2023-01-16 07:44
I will record the video today and will show

**Comment by drasticactions** [comment] 2023-01-16 07:51
I apologize, but it does start for other developers and users here. You're describing the basic template, so this is likely an issue on your machine that I'm trying to get more information about.

As I asked, which platform were you trying to run? Windows? Android? iOS? Can you post the output logs from when you tried to deploy?

**Comment by dankodima1** [comment] 2023-01-16 07:51
video added

https://user-images.githubusercontent.com/51223663/212625054-d7fcb3a6-77c9-4938-9c67-96fb8267e8c4.mp4

**Comment by dankodima1** [comment] 2023-01-16 07:54
> I apologize, but it does start for other developers and users here. You're describing the basic template, so this is likely an issue on your machine that I'm trying to get more information about.
> 
> As I asked, which platform were you trying to run? Windows? Android? iOS? Can you post the output logs from when you tried to deploy?

I use Windows 10. Visual Studio 2022. 
You don't understand me, the main idea is - if it is First Steps - this should work based only on Example https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/run#

**Comment by idexus** [comment] 2023-01-16 08:40
Try to install SDK [https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/downloads#windows-app-sdk-12](https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/downloads#windows-app-sdk-12)
Runtime installer (x64), it helped me.

**Comment by jsuarezruiz** [comment] 2023-01-16 15:07
This seems to be the same as https://github.com/dotnet/maui/issues/12080
Could you try this workaround https://github.com/dotnet/maui/issues/12080#issuecomment-1377243186?

**Comment by mattleibow** [comment] 2023-01-16 15:18
Duplicate of https://github.com/dotnet/maui/issues/12080

**Comment by dankodima1** [comment] 2023-01-16 15:25
You don't understand my question.

FIX the Microsoft example please. And at the begining you said - all work for others. But at the end you send me the other tickets with a lot of comments and questions about this issue.

The main idea - Microsoft example should be EDITED, I will not investigate github 12080 because it waste the time. Thank you.

**Comment by dankodima1** [comment] 2023-01-16 15:26
Why need so a lot of comments only for some 1 issue. bureaucracy (I think, sorry)

**Comment by mattleibow** [comment] 2023-01-16 15:32
Duplicate of https://github.com/dotnet/maui/issues/12080

**Closed** 2023-01-16 15:32 UTC
Labels: s/duplicate 2️⃣, platform/windows 🪟, s/needs-attention
