### ISSUE TITLE
[Windows] DatePicker doesn't update Date property when you don't select date

### ISSUE THREAD

**Issue by jpmm94** [dotnet/maui#22004] opened 2024-04-23 13:57 UTC
### Description

In Maui windows, when you don't choose date, the control does not update the Date property, which continues with the previous value, instead aesthetically it indicates that it does not have a date selected
![image](https://github.com/dotnet/maui/assets/22910139/7634fa9f-b65d-4299-95ab-6d62b793ff19)
![image](https://github.com/dotnet/maui/assets/22910139/12c9a577-8695-47b7-b918-8d587cda714c)

### Version with bug

8.0.14 SR3.1

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

**Comment by PureWeen** [comment] 2024-04-23 18:15
Duplicate of #13156

**Closed by PureWeen** 2024-04-23 18:15 UTC
Labels: t/bug, platform/windows 🪟
