### ISSUE TITLE
Error with Microsoft.EntityFrameworkCore.Sqlite on iOS Release mode

### ISSUE THREAD

**Issue by IndexOutOfLimit** [dotnet/maui#11266] opened 2022-11-10 18:42 UTC
### Description

I want to use Microsoft.EntityFrameworkCore.Sqlite in dotnet maui app. But the app crashes on start on iOS.
It worked fine on Android, Windows and iOS Debug mode.

I have included below nuget packages:
![image](https://user-images.githubusercontent.com/24838606/201178925-468b94c3-71c1-47f7-9279-809937540f40.png)

From log I found below information:

```
*** Terminating app due to uncaught exception 'System.ExecutionEngineException', reason: 'Attempting to JIT compile method '(wrapper delegate-invoke) void <Module>:invoke_callvirt_void_SampleDbContext_DbSet`1<Test> (TestApp.Mobile.Repository.SampleDbContext,Microsoft.EntityFrameworkCore.DbSet`1<TestApp.Mobile.Repository.Entities.Test>)' while running in aot-only mode. See https://docs.microsoft.com/xamarin/ios/internals/limitations for more information. (System.ExecutionEngineException)

at System.Linq.Expressions.Interpreter.ActionCallInstruction`2[[TestApp.Mobile.Repository.SampleDbContext, TestApp.Mobile.Repository, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.EntityFrameworkCore.DbSet`1[[TestApp.Mobile.Repository.Entities.Test, TestApp.Mobile.Repository, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], Microsoft.EntityFrameworkCore, Version=6.0.10.0, Culture=neutral, PublicKeyTo<\M-b\M^@\M-&>'
```

### Steps to Reproduce

1. Create MAUI App
2. Configure EntityFramework and SqlLite
3. Create Release build for iOS
4. Install & Run the the app on iOS Device
5. See the crash

### Link to public reproduction project repository

NA

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15 and above

### Did you find any workaround?

Not yet

**Comment by mattleibow** [comment] 2022-11-10 19:38
Duplicate of https://github.com/dotnet/maui/issues/9176
EF also moved it: https://github.com/dotnet/efcore/issues/28710
Now in https://github.com/dotnet/runtime/issues/74015

**Comment by mattleibow** [comment] 2022-11-10 19:39
EF also moved it: https://github.com/dotnet/efcore/issues/28710
Now in https://github.com/dotnet/runtime/issues/74015

**Closed** 2022-11-10 19:39 UTC
Labels: t/bug, area/publishing 🏁

**Comment by IndexOutOfLimit** [comment] 2022-11-11 03:20
So, MAUI will not be able publish iOS apps with EF integration, is that what you say when marked as not planned? So, when that will be ready to publish to AppStore?

**Comment by mattleibow** [comment] 2022-11-11 06:25
You may be able to use the interpreter on ios, but the conversation moved to the runtime issue linked above.

Something in EF is breaking AOT rules and trying to write code at runtime or it could be that the things EF is doing just happens to use a set of things that the runtime magic is not yet supporting. It could help if you could narrow down the case that causes the crash and add a repro case to the runtime issue.

I am not a runtime expert so I can't even say where or why things are not working. Maybe there is a way to avoid the crash if you do a different thing. But unfortunately the Maui team is not really a EF+runtime expert.

**Comment by IndexOutOfLimit** [comment] 2022-11-11 06:55
Understood, I'll create a ticket EF end then. Thanks for the information.

**Comment by Ghevi** [comment] 2022-11-11 11:34
@IndexOutOfLimit check [#9176](https://github.com/dotnet/maui/issues/9176), as you can see deleting bin and obj fixed this issue.

**Comment by IndexOutOfLimit** [comment] 2022-11-22 04:41
Thanks @Ghevi I checked and it worked.
