### ISSUE TITLE
Fix the slow startup

### ISSUE THREAD

**Issue by YoussofKhawaja** [dotnet/maui#1648] opened 2021-07-12 19:53 UTC
Fix this slow startup for andriod or you just didn't change anything between xamarin.forms and maui

**Comment by lutzroeder** [comment] 2021-07-13 00:38
Duplicate of #1595

**Comment by SagarPanwala** [comment] 2021-08-19 10:17
@lutzroeder 1595 is deleted hence this is still a valid open bug.

**Comment by jfversluis** [comment] 2021-11-05 09:13
There are several issues already describing this problem that we are very much invested in. You can see in the [latest blog post](https://devblogs.microsoft.com/dotnet/announcing-net-maui-preview-9/#quick-android-startup) that we have made great progress here.

Another issue for this is here #822

Closing this one for now, rest assured: this is on our radar and a big priority for us. Thanks!

**Closed by jfversluis** 2021-11-05 09:13 UTC
