### ISSUE TITLE
Application freezes when phone font size (or anything affecting UI) changes while app is running.

### ISSUE THREAD

**Issue by Tangshake** [dotnet/maui#18284] opened 2023-10-24 09:07 UTC
### Description

While working with the app, I minimize it and change UI-affecting setting like font size, resolution etc. When app is brought to the front, it freezes. I cannot tap any button or change its orientation. From time to time instead of application, a black rectangle shape is displayed.
Problem applies to real devices and an emulator (eg. Pixel5 - Api33), both release and debug mode. <br>
Visual Studio 2022 (17.8.0 Preview 4.0)
Default .NET MAUI Blazor Hybrid App, net8.0 (Preview)
**sdk-8.0.100-rc.2.23502.2-win-x64**

### Steps to Reproduce

1. Create default .NET MAUI Blazor Hybrid App with net8.0,
2. Run the App on Android Emulator ex. Pixel5 - Api33,
3. Change phone orientation portrait/landscape. Everything works fine,
4. Minimize application,
5. Open android Settings->Display->Display text and size. Change font size to bigger or smaller,
    - it does not have to be font size. You may set font to bold or change the screen size etc. ,
6. Bring the application to front,
7. Change the orientation or try to tap any button,
8. App and phone freezes. Black rectangle on the screen instead of the app.

### Link to public reproduction project repository

Default .NET MAUI Blazor Hybrid App, net8.0 (Preview)

### Version with bug

Unknown/Other

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.96

### Affected platforms

Android

### Affected platform versions

Android 9, Android 11, Android 13

### Did you find any workaround?

No

**Comment by Redth** [comment] 2023-10-25 16:52
A non-blazor MAUI app does not exhibit this problem.  I also tried mixing in MAUI controls on blazor to see if somehow they were still responsive while the webview was not.  Unfortunately the existence of the webview seems to be the difference in causing this to happen.

**Comment by Redth** [comment] 2023-10-25 17:15
I can't seem to reproduce this within the MAUI Controls Sample app in our repo, even setting the blazor page as the main/start page, things just seem to work fine.

However one thing odd I'm noticing is that the `AppCompatActivity`'s `OnStart` seems to be where things get stuck in the app which does reproduce the issue.

**Comment by Redth** [comment] 2023-10-25 18:18
Another finding.  This seems to not happen if I'm not debugging the app.  @Tangshake can you try launching the app without debugging it (eg: Just launch it clean from the device) and see if you're able to reproduce the results?

**Comment by Tangshake** [comment] 2023-10-25 21:22
I updated VisualStudio 22 to preview 5. Problem still exists.

I did two builds of an app - default .NET MAUI Blazor Hybrid App with net8.0 in release mode without debugging.
The first build was done from Visual Studio 2022(preview 5) and the second from command line as if I were publishing it to google play store. 

I ran both builds on Samsung S8+ with android 9 and on Samsung A70 with android 11. Nothing has changed. After I change font size and bring application to the front it freezes. Tapping "burger menu button" does nothing and changing phone orientation makes the screen go black. Samsung A70 sometimes freezes completely for a few seconds.
Moreover I ran it on two emulators. The first used in Visual Studio 2022(preview5) and the second LDPlayer9.0.43. Both behaved the same way - they froze.

Before reporting the bug here, I posted it on stackoverflow looking for a solution. Someone confirmed reproducing the issue.

**Comment by Zhanglirong-Winnie** [comment] 2024-03-11 07:41
Verified this issue with Visual Studio 17.10.0 Preview 1. Can repro on Android platform.
![image](https://github.com/dotnet/maui/assets/77434865/29eba934-2f34-4816-8030-764f22c22d3c)

**Comment by mkArtakMSFT** [comment] 2024-05-03 20:12
This may also be related to https://github.com/dotnet/maui/issues/20678

**Comment by Eilon** [comment] 2024-05-17 20:19
Confirmed duplicate of #13529

**Closed by Eilon** 2024-05-17 20:19 UTC
Labels: t/bug, platform/android 🤖, area-blazor, s/verified, s/triaged, potential-regression
