### ISSUE TITLE
CarouselView Do Not Work [Bug] 

### ISSUE THREAD

**Issue by nextcodelab** [dotnet/maui#2225] opened 2021-08-24 01:08 UTC
### Description
I need carouselview in my app but does not display any items and sometimes stuck up in splashscreen
### Steps to Reproduce

Test Code
```
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="HelloMauiPreview.MainPage"
             xmlns:converters="clr-namespace:BibleAppMaui.Converters"
             xmlns:static="clr-namespace:BibleAppMaui"
             xmlns:controls="clr-namespace:BibleAppMaui.Controls"
             BackgroundColor="{DynamicResource PageBackgroundColor}">
    <CarouselView x:Name="caroseil">
        <CarouselView.ItemTemplate>
            <DataTemplate>
                <VerticalStackLayout BackgroundColor="{Binding}">
                    
                </VerticalStackLayout>
            </DataTemplate>
        </CarouselView.ItemTemplate>
    </CarouselView>
</ContentPage>

C#
using System;
using BibleAppMaui.Helpers;
using Microsoft.Maui;
using Microsoft.Maui.Controls;
using Microsoft.Maui.Graphics;

namespace HelloMauiPreview
{
	public partial class MainPage : ContentPage
	{
		public MainPage()
		{
			InitializeComponent();
		}

		
        protected override void OnAppearing()
        {
            base.OnAppearing();
			var list = new List<Color>();
			list.Add(ColorList.GetRandomLightColor());
			list.Add(ColorList.GetRandomLightColor());
			list.Add(ColorList.GetRandomLightColor());
			list.Add(ColorList.GetRandomLightColor());
			caroseil.ItemsSource = list;
        }


    }
}

```

### Expected Behavior
It should display carousel colors and not stuck up on splash screen...

Note: I only tried it on android emulator...

**Comment by PaulAnderson02** [comment] 2021-08-24 15:43
https://github.com/dotnet/maui/issues/2118

**Comment by PaulAnderson02** [comment] 2021-09-16 14:32
Any update on this issue?

**Comment by SkeletonJohn** [comment] 2021-11-15 19:26
I have something similar, and I think it may be the same issue while trying to create CarouselView containing ContentView.  I'm receiving the following error: Java.Lang.IllegalStateException
  Message=The specified child already has a parent. You must call removeView() on the child's parent first.

<StackLayout>
        <CarouselView>
            <CarouselView.ItemsSource>
                <x:Array Type="{x:Type ContentView}">
                    <ContentView>
                        <StackLayout BackgroundColor="Blue" />
                    </ContentView>
                    <ContentView>
                        <StackLayout BackgroundColor="Red" />
                    </ContentView>
                </x:Array>
            </CarouselView.ItemsSource>
            <CarouselView.ItemTemplate>
                <DataTemplate>
                    <ContentView Content="{Binding .}" />
                </DataTemplate>
            </CarouselView.ItemTemplate>
        </CarouselView>
    </StackLayout>

**Comment by SkeletonJohn** [comment] 2021-11-29 18:34
Any update on this?

**Comment by shimingsg** [comment] 2022-02-17 06:17
Duplicate of #2118

**Closed by shimingsg** 2022-02-17 06:17 UTC
Labels: t/bug, area/collectionview 📃, s/verified
