### ISSUE TITLE
on Android, VerticalTextAlignement doesn't work with the control : 'Entry'

### ISSUE THREAD

**Issue by themine702** [dotnet/maui#12339] opened 2022-12-29 15:12 UTC
### Description

on Android, the 'VerticalTextAlignement' property doesn't work with the control : 'Entry'

when you use the code snippet i've put in Steps to Reproduce, here is what you'll get : 

on IOS : [ No issues ]
![Capture d’écran 2022-12-29 095506](https://user-images.githubusercontent.com/76855805/209971310-468adfb3-a057-4aa8-b155-bf13997a4c90.png)

on Android : [ Bug : VerticalTextAlignement doesn't work (but HorizentalTextAlignement does work ..) ]
![Capture d’écran 2022-12-29 095320](https://user-images.githubusercontent.com/76855805/209971573-61407d45-67cf-489e-a823-9d31259474e5.png)

### Steps to Reproduce

1. Create default MAUI Project
2. Paste this in the MainPage.xml 's content :
`<Grid RowDefinitions="150">  
    <Entry Grid.Row="0" BackgroundColor="Red" Text="hello there" VerticalTextAlignment="Center" HorizontalTextAlignment="Center" />  
</Grid>`
3. Launch the app on Android to observe the Bug

### Link to public reproduction project repository

no link

### Version with bug

6.0 Release Candidate 2 or older

### Affected platforms

Android

### Affected platform versions

tested it on Android (10), (11), (12.1), (13)

### Did you find any workaround?

i tried changing the size of the 'Entry' dynamically (by changing the parent Grid's Column & Row definitions) so that the layout gets updated hoping the problem only happens on the first control Initialization

=> but No it doesn't change anything, so i currently **don't have any work around for this Bug**

**Comment by TimLariviere** [comment] 2023-02-22 11:18
We encountered the same issue.

This only affects Android.

An Entry inside a Grid will not center its text correctly, despite the Entry taking all the height of the row.
Setting the HeightRequest on the Entry itself will correctly center the text though.

_Broken:_
```xml
<Grid HeightRequest="60">
    <Entry Background="Red" />
</Grid>
```

![image](https://user-images.githubusercontent.com/6429007/220604723-679af990-d38b-462d-9768-8ff8b53180f9.png)

_Workaround:_
```xml
<Grid HeightRequest="60">
    <Entry HeightRequest="60" Background="Red" />
</Grid>
```

![image](https://user-images.githubusercontent.com/6429007/220605216-7a249cca-b8a4-4407-b615-79457c87c36f.png)

**Comment by Zhanglirong-Winnie** [comment] 2023-06-07 06:18
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 1.0. Can repro on android platform with above code.
![Screenshot 2023-06-07 141707](https://github.com/dotnet/maui/assets/77434865/6755ee2e-4352-4ca7-8adc-979d4af7bdc8)

**Comment by mattleibow** [comment] 2024-09-10 16:31
Duplicate of https://github.com/dotnet/maui/issues/21717

**Closed by mattleibow** 2024-09-10 16:31 UTC
Labels: t/bug, platform/android 🤖, s/verified, area-controls-entry, s/triaged
