### ISSUE TITLE
Global MAUI Reference

### ISSUE THREAD

**Issue by jrahma** [dotnet/maui#10345] opened 2022-09-27 14:14 UTC
### Description

Hi,

Currently, we can have a global assembly declaration like this:

`global using DevExpress.Maui;
`

but we need to make the xaml clean as well and move this reference to a separate file.

`xmlns:dxe="clr-namespace:DevExpress.Maui.Editors;assembly=DevExpress.Maui.Editors"
`

### Public API Changes

global.cs:

```
global declare dxe = { namespace=DevExpress.Maui.Editors, assembly=DevExpress.Maui.Editors };
global declare syncfusion = { namespace=Syncfusion.Maui.TabView, assembly=Syncfusion.Maui.TabView };

```

### Intended Use-Case

Clean Coding

**Comment by Eilon** [comment] 2022-09-27 16:41
Is this specifically about having support for a "global using" for XAML? I'm not sure I understand what this new syntax means or does.

**Comment by jrahma** [comment] 2022-09-27 20:49
What I am tryig to achieve here is to get rid of all the xaml declaration from the xaml and move it to a global .cs file which saves a lot of lines because most if the xaml declarations are the same in all the xaml pages

**Comment by jfversluis** [comment] 2022-09-28 08:37
Duplicate of #3376

**Closed by jfversluis** 2022-09-28 08:37 UTC
Labels: proposal/open, s/needs-attention
