### ISSUE TITLE
[regression/8.0.0-preview.7.8842] Entry Numeric keyboard type is not working

### ISSUE THREAD

**Issue by alexskrms** [dotnet/maui#17137] opened 2023-08-31 12:04 UTC
### Description

Hi, since the update to the new version of .NET MAUI preview 7, I have noticed that my entry controls with the numeric keyboard input type set are not working.

### Steps to Reproduce

1. Create a .NET MAUI project.
2. Enter your XAML file and create a .NET MAUI Default Entry.
3. Set the Keyboard property to "Numeric".
4. Run the app and try to input something on the entry.

### Version with bug

8.0.0-preview.7

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.0-preview.4.8333

### Affected platforms

Android

### Affected platform versions

Android 13

### Did you find any workaround?

No

### Relevant log output

No

**Comment by jknaudt21** [comment] 2023-09-05 22:39
Hi @alexskrms could you provide a repro project? I've been unable to repro using the latest in main - though I'm not sure tis because I missed something or because this issue has been fixed. 

I used the code below to create an `Entry` on a blank page and deployed to a Pixel 5 emulator on API lv 33 (Android 13). When clicked, the entry would display a numeric keyboard.
```
    <StackLayout>
        <Entry Keyboard="Numeric"/>
    </StackLayout>
```
<img width="417" alt="image" src="https://github.com/dotnet/maui/assets/32918747/a88c3885-3d0c-4ad5-be30-b56ca153bb91">

**Comment by MsVibe** [comment] 2023-09-09 15:27
I experience the same issue on android phone and in Pixel 5 - API 33 emulator, when keyboard is set to Danish.

The numeric keyboard shows up, but no numbers or decimal point are registered, when tapping them or trying to input via keyboard.

**Comment by stoff99** [comment] 2023-09-11 08:33
Same issue here with a Google Pixel 2 XL real device.
Just put the keyboard type numeric and you cannot write any text inside the entry with the softkeyboard.

**Comment by tranb3r** [comment] 2023-09-15 08:15
If your issue is happening only for non-english cultures, then this is a duplicate of https://github.com/dotnet/maui/issues/15884, and it is fixed in net8-rc1.

**Comment by stoff99** [comment] 2023-09-15 08:35
@tranb3r i can confirm that this bug is solved for me in .net 8 rc1 1.23463.5 and android.

**Comment by alexskrms** [comment] 2023-09-15 10:33
@stoff99 True fixed in the latest update

**Comment by jknaudt21** [comment] 2023-09-18 21:28
Hey @alexskrms, 

I tried reproducing the issue clicking on the numbers in the keyboard, but I was unable to do so. Reading the thread above it seems your issue was fixed with rc1 too. I'm resolving the issue, but feel free to reopen if you hit it again.
 
![repro](https://github.com/dotnet/maui/assets/32918747/33b2b21f-b2e8-4ac1-ad40-4a0fb91bb511)

**Closed by jknaudt21** 2023-09-18 21:28 UTC
Labels: t/bug, platform/android 🤖, area/controls 🎮, control-entry, s/needs-attention, i/regression
