### ISSUE TITLE
Custom ViewCells disappear in TableView

### ISSUE THREAD

**Issue by ewerspej** [dotnet/maui#10322] opened 2022-09-26 13:30 UTC
### Description

When using a `ViewCell` inside a `TableView`, it doesn't show up or disappears during interaction with any of the other controls inside the `TableView`.

I have observed three different behaviors so far:

1. The `ViewCell` does not get rendered at all
2. The `ViewCell` gets rendered for a split second and then disappears
3. The `ViewCell` gets rendered, but disappears when interacting with any of the controls in the `TableView`

### Steps to Reproduce

1. Create a new MAUI App (.NET 6.0)
2. Add a TableView incl. a TableRoot and TableSection to the MainPage (or any other page)
3. Add a ViewCell to the TableSection
4. Add a Grid with a Label and Button to the ViewCell
5. Add a SwitchCell
6. Run on an Android 12.0 device or emulator

**Expected outcome: ViewCell with Label and Button is visible and remains visible**
**Actual outcome: ViewCell and contents disappear/do not show up**

### Link to public reproduction project repository

https://github.com/ewerspej/dotnet-maui-bug-viewcell-disappears

### Version with bug

Unknown/Other (please specify)
*dotnet --version* says *7.0.100-rc.1.22431.12*, but the project was created using .NET 6.0

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 12.0

### Did you find any workaround?

No, so far without any success.

**Comment by YiannisBourkelis** [comment] 2022-12-06 05:20
@jfversluis Having the exact same issue. Using a tableview in a page was very common in Xamarin.Forms. Now, it is impossible to migrate any project that uses a tableview to MAUI. Any page that uses a tableview has these issues with disappearing controls. The issue is very easy reproducible. 
Can someone please fix this so we can migrate our existing Xamarin.Forms code to MAUI when using a tableview without having to rewrite all the layout logic?

Here is a reproducible use case on Android, iOS and MacCatalyst: [https://github.com/YiannisBourkelis/maui_issues/tree/main/src/TableViewDisappearingControlsIssue](https://github.com/YiannisBourkelis/maui_issues/tree/main/src/TableViewDisappearingControlsIssue)

**Comment by mfeingol** [comment] 2023-02-03 17:26
I'm having the same issue. Is TableView deprecated? Should we move on?

**Comment by EgonRasmussen** [comment] 2023-02-06 16:01
I have success with the `HasUnevenRows="True"` on the TableView, see the dokumentation [Size Items](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/controls/tableview?view=net-maui-7.0#size-items):
```xml
<TableView Intent="Settings" HasUnevenRows="True">
    <TableRoot>
        <TableSection Title="Silent">
            <ViewCell>
                <Grid ColumnDefinitions="0.5*,0.5*" RowDefinitions="Auto,Auto">
                    <Label Margin="10,10,0,0" Text="Vibrate" />
                    <Switch Grid.Column="1" HorizontalOptions="End" />
                    <Slider
                        Grid.Row="1"
                        Grid.ColumnSpan="2"
                        Margin="10"
                        Maximum="10"
                        Minimum="0"
                        Value="3" />
                </Grid>
            </ViewCell>
        </TableSection>
    </TableRoot>
</TableView>
```
<img width="200" alt="TableView" src="https://user-images.githubusercontent.com/5080208/217020656-06998e3a-916f-48c0-8f6d-3744940d5411.png">

**Comment by kblondin** [comment] 2023-03-01 16:33
I have this issue too. Any news on a fix and/or work around ?

**Comment by ewerspej** [comment] 2023-03-02 18:33
I've resorted to building my own settings page using a `Grid`. 

@jfversluis Will this be worked on any time soon?

**Comment by hartez** [comment] 2023-03-29 17:59
This might be the same issue as #5924.

**Comment by Realgigabyte** [comment] 2023-04-11 22:16
Same problem. It works fine on Windows.

**Comment by jfversluis** [comment] 2023-07-04 18:45
I see there is #15036 that was merged that might have to do with this. Is there anyone that is already on the .NET 8 preview bits that might confirm if the problem still persists there? This change should be available in .NET 8 preview 5.

**Comment by Zhanglirong-Winnie** [comment] 2023-07-17 08:38
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 3.0(net8). Can repro on android platform with sample project.
[dotnet-maui.zip](https://github.com/dotnet/maui/files/12067398/dotnet-maui.zip)
![10322](https://github.com/dotnet/maui/assets/77434865/692f56f8-1ab9-42cb-9e2d-820f8325a3eb)

**Comment by KeithBoynton** [comment] 2023-07-18 08:08
Also having the same issue on Android. Commenting so it can be seen the scope of people this affects. I see it's confirmed and also looking like noone is looking at fixing it.

**Comment by eabrega** [comment] 2023-07-30 21:39
I have this trouble too.

**Comment by crawshaws** [comment] 2023-09-14 11:47
Same issue here. Only way to get the controls back for me is to navigate away and back to the page. Even switching tab in a TabbedPage and back works but it is strange that this should exist when it did not exist in Xamarin. These needs fixing as it really does hamper the use of Maui. how did this even slip past QC. Considering Xamarin is going out of support next year?

**Comment by ewerspej** [comment] 2023-09-15 09:35
@crawshaws I think they changed/optimized some things in the layout engine. I've already encountered quite a few bugs related to layout updates. Controls aren't rendered correctly upon changes in certain situations. There a lots of improvements and fixes coming in .NET 8.0 🤞

**Comment by bemiller** [comment] 2023-10-31 19:19
There seems to be a lot to overcome in .Net Maui. It's shocking, really, that it was released the way it was, but on this particular topic, the following worked for me:

<TableView Intent="Menu" HeightRequest="1000" VerticalOptions="Start">

**Comment by mfeingol** [comment] 2023-10-31 20:12
Thanks, @bemiller. Setting height to "720" for a larger settings section that scrolls down a bit worked for me.

**Comment by Bennynation** [comment] 2023-11-09 19:45
Hi everyone ! I think i found an interesting workaround for this problem ! 
I took the OnMeasure from the PlatformRenderer : https://github.com/dotnet/maui/blob/8e933a7a7a46fdb586918e7414345d978cb0878d/src/Compatibility/Core/src/Android/PlatformRenderer.cs#L79

This is the workaround i found : 
```
public class MyTableViewHandler : TableViewRenderer
    {
        public MyTableViewHandler(Context context) : base(context)
        {
        }

        //Do not call base.OnMeasure(widthMeasureSpec, heightMeasureSpec); !!!
        protected override void OnMeasure(int widthMeasureSpec, int heightMeasureSpec)
        {
            int width = MeasureSpec.GetSize(widthMeasureSpec);
            int height = MeasureSpec.GetSize(heightMeasureSpec);

            SetMeasuredDimension(width, height);

            for (int i = 0; i < ChildCount; i++)
            {
                Android.Views.View child = GetChildAt(i);
                child.Measure(MeasureSpec.MakeMeasureSpec(width, MeasureSpecMode.Exactly),
                    MeasureSpec.MakeMeasureSpec(height, MeasureSpecMode.Exactly));
            }
        }
    }
```

```
public static class MauiProgram
{
    public static MauiApp CreateMauiApp()
    {
        var builder = MauiApp.CreateBuilder();
        builder
            .UseMauiApp<App>()
            //...
            .ConfigureMauiHandlers((handlers) =>
            {
#if ANDROID
                handlers.AddHandler(typeof(TableView), typeof(MyTableViewHandler));
#endif
            });

        //...

        return builder.Build();
    }
}
```

**Comment by Bennynation** [comment] 2023-11-23 14:50
Did you try the workaround just above your comment ?

**Comment by PureWeen** [comment] 2023-12-12 20:26
Duplicate of #5924

**Closed by PureWeen** 2023-12-12 20:26 UTC
Labels: t/bug, platform/android 🤖, p/1, area/controls 🎮, s/verified, s/triaged, migration-compatibility
