### ISSUE TITLE
AAB-files get signed, but not APK-files

### ISSUE THREAD

**Issue by pekspro** [dotnet/maui#10872] opened 2022-10-24 16:22 UTC
### Description

When I publish a specific project to Android I get two AAB-files, one unsigned and one signed, and an APK-file that should be signed but isn’t. I verify this with the `keytool` command. If I do the same on a new MAUI application the APK will be signed.

I suspect this is a bug. I get same result both in .NET 6 and .NET 7.

### Steps to Reproduce

**Run this to get code and publish:**

```shell
git clone https://github.com/pekspro/RadioStorm.git

cd .\RadioStorm\Source\Pekspro.RadioStorm.MAUI\

keytool -genkey -v -keystore signtest.keystore -alias signtest -keyalg RSA -keysize 2048 -validity 10000
(Enter stuff, use password 1234568)

dotnet publish Pekspro.RadioStorm.MAUI.csproj --framework:net6.0-android --configuration:Release /p:AndroidSigningKeyStore=./signtest.keystore /p:AndroidKeyStore=True  /p:AndroidSigningKeyAlias=signtest /p:PublishTrimmed=False /p:AndroidSigningKeyPass=12345678 /p:AndroidSigningStorePass=12345678  /p:RunAOTCompilation=False --verbosity normal
```

**Run this to verify output:**

```shell
keytool -printcert -jarfile .\bin\Release\net6.0-android\com.pekspro.radiostorm-Signed.aab
```
This outputs the signature.
 
```shell
keytool -printcert -jarfile .\bin\Release\net6.0-android\com.pekspro.radiostorm-Signed.apk
```
This says: “Not a signed jar-file”

### Link to public reproduction project repository

https://github.com/pekspro/RadioStorm

### Version with bug

7.0 Release Candidate 2

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Windows 10.0.17763.0, Android 11

### Relevant log output

It's a lot of logs :-) This is the best I found:
```shell
_Sign:
         C:\Program Files\Microsoft\jdk-11.0.12.7-hotspot\bin\jarsigner.exe -keystore ./signtest.keystore -storepass 12
         345678 -keypass 12345678 -digestalg SHA-256 -sigalg SHA256withRSA -signedjar bin\Release\net6.0-android\com.pe
         kspro.radiostorm-Signed.aab obj\Release\net6.0-android\android\bin\com.pekspro.radiostorm.aab  signtest
         jar signed.
         The signer's certificate is self-signed.
         Signed android package ''
       _CreateUniversalApkFromBundle:
         Deleting file "obj\Release\net6.0-android\android\bin\com.pekspro.radiostorm-Universal.apks".
         C:\Program Files\Microsoft\jdk-11.0.12.7-hotspot\bin\java.exe -Xmx1G -jar "C:\Program Files\dotnet\packs\Micro
         soft.Android.Sdk.Windows\32.0.476\tools\bundletool.jar" build-apks --mode universal --bundle obj\Release\net6.
         0-android\android\bin\com.pekspro.radiostorm.aab --output obj\Release\net6.0-android\android\bin\com.pekspro.r
         adiostorm-Universal.apks --aapt2 "C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.476\tools\a
         apt2.exe" --ks ./signtest.keystore --ks-key-alias signtest --key-pass pass:12345678 --ks-pass pass:12345678
       PrepareForPublish:
         Creating directory "bin\Release\net6.0-android\publish\".
```

**Comment by PureWeen** [comment] 2022-10-25 18:29
@jonathanpeppers thoughts?

**Comment by jonathanpeppers** [comment] 2022-10-25 18:44
@pekspro when you reproduce the issue with `dotnet build`, can you add `-bl` to your command? This will put an `msbuild.binlog` in the current directory. Can you share it here?

**Comment by pekspro** [comment] 2022-10-25 18:52
@jonathanpeppers, enjoy :-)
 
[msbuild.zip](https://github.com/dotnet/maui/files/9863170/msbuild.zip)

**Comment by jonathanpeppers** [comment] 2022-10-25 18:58
So `bundletool` is passed the arguments to sign:

```
C:\Program Files\Microsoft\jdk-11.0.12.7-hotspot\bin\java.exe -Xmx1G -jar "C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.476\tools\bundletool.jar" build-apks --mode universal --bundle obj\Release\net6.0-android\android\bin\com.pekspro.radiostorm.aab --output obj\Release\net6.0-android\android\bin\com.pekspro.radiostorm-Universal.apks --aapt2 "C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.476\tools\aapt2.exe" --ks ./signtest.keystore --ks-key-alias signtest --key-pass pass:**** --ks-pass pass:****
```

Then it outputs a `obj\Release\net6.0-android\android\bin\com.pekspro.radiostorm-Universal.apks`, which is unzipped as `bin\Release\net6.0-android\com.pekspro.radiostorm-Signed.apk`.

If you pass `-p:AndroidPackageFormat=apk` (disable app bundles), does the original `keytool` command report that it is signed? I question if the issue is `keytool` not knowing how to show the signature in this case.

/cc @dellis1972

**Comment by pekspro** [comment] 2022-10-25 19:01
@jonathanpeppers, if I do this on other project `keytool` is able to show the signature.

I'll try with `-p:AndroidPackageFormat=apk` right now.

**Comment by pekspro** [comment] 2022-10-25 19:08
@jonathanpeppers, with `-p:AndroidPackageFormat=apk` the `keytool` says that the apk is signed! I'm surprised and confused :-D

New log:

[msbuild.zip](https://github.com/dotnet/maui/files/9863260/msbuild.zip)

**Comment by pekspro** [comment] 2022-10-25 19:28
Just to summarize. I run this:

```shell
dotnet publish Pekspro.RadioStorm.MAUI.csproj --framework:net6.0-android --configuration:Release /p:AndroidSigningKeyStore=./signtest.keystore /p:AndroidKeyStore=True  /p:AndroidSigningKeyAlias=signtest /p:PublishTrimmed=False /p:AndroidSigningKeyPass=12345678 /p:AndroidSigningStorePass=12345678  /p:RunAOTCompilation=False --verbosity normal -bl
```

and then

```shell
keytool -printcert -jarfile .\bin\Release\net6.0-android\com.pekspro.radiostorm-Signed.apk
```

And `keytool` says again there is to signature. 

Since I starts to belive I'm crazy, I again run the same on the new MAUI application:

```shell
dotnet publish buildtestnew2.csproj --framework:net6.0-android --configuration:Release /p:AndroidSigningKeyStore=./signtest.keystore /p:AndroidKeyStore=True  /p:AndroidSigningKeyAlias=signtest /p:PublishTrimmed=False /p:AndroidSigningKeyPass=12345678 /p:AndroidSigningStorePass=12345678  /p:RunAOTCompilation=False --verbosity normal -bl
```

and then

```shell
keytool -printcert -jarfile .\bin\Release\net6.0-android\com.companyname.buildtestnew2-Signed.apk
```

And now I get a signature. Here is the log when I build a new application:

[msbuild.zip](https://github.com/dotnet/maui/files/9863381/msbuild.zip)

**Comment by janseris** [comment] 2022-10-26 08:53
Should be all possible without command line

**Comment by dellis1972** [comment] 2022-10-26 09:16
We use `bundletool.jar` to do the extraction process when targetting `aab` files. We build the `aab` then bundletool extracts a full `apk` from that `aab`. We are passing the various Signing information. See https://github.com/xamarin/xamarin-android/blob/main/src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets#L2428. 

I wonder if there is a change in behaviour in `bundletool` perhaps its no longer producing a signed apk.

**Comment by dellis1972** [comment] 2022-10-26 09:30
@pekspro 

Can you add the following to the top most PropertyGroup in your csproj please.

```
<AndroidBundleToolExtraArgs>--verbose</AndroidBundleToolExtraArgs>
```

then run the same command you did for  https://github.com/dotnet/maui/issues/10872#issuecomment-1291036075. And upload the resulting binlog please. It should contain additional information on what `bundletool` is doing with that apk.

**Comment by dellis1972** [comment] 2022-10-26 09:57
it also looks like there is a new option in `bundletool` which will skip the `apks` intermediate step and extract the apks directly to a directory. 

```
--output-format: (Optional) Specifies output format for generated APKs. If
        set to 'APK_SET' outputs APKs into the created APK Set archive
        (default). If set to 'DIRECTORY' outputs APKs into the specified
        directory.
```

I'll test this and see if this outputs the signed apks directly.

**Comment by dellis1972** [comment] 2022-10-26 11:51
ok so I just tested this on my Mac and the first command you posted produced a signed apk file. I used `apksigner` to verify this 

```
apksigner verify -v samples/HelloWorld/HelloWorld/bin/Release/net7.0-android/com.xamarin.android.helloworld-Signed.apk
Verifies
Verified using v1 scheme (JAR signing): true
Verified using v2 scheme (APK Signature Scheme v2): true
Verified using v3 scheme (APK Signature Scheme v3): true
Verified using v4 scheme (APK Signature Scheme v4): false
Verified for SourceStamp: false
Number of signers: 1
```

**Comment by pekspro** [comment] 2022-10-26 14:05
Here is the log I get when I run with:

```
<AndroidBundleToolExtraArgs>--verbose</AndroidBundleToolExtraArgs>
```

[msbuild.zip](https://github.com/dotnet/maui/files/9870240/msbuild.zip)

**Comment by pekspro** [comment] 2022-10-26 14:53
I have tried to run `bundletool` manually. One aab-file (new maui app) can be converted to a signed apk, but the other (radiostorm) will be an unsigned apk.

Here it the files I have used (too large for GitHub):
https://pekspro.com/files/aab_to_apk_test.zip

Run this:

```shell
"C:\Program Files\Microsoft\jdk-11.0.12.7-hotspot\bin\java.exe" -Xmx1G -jar "C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.476\tools\bundletool.jar" build-apks --mode universal --bundle buildtestnew-Signed.aab --output buildtestnew-Universal.apks --aapt2 "C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.476\tools\aapt2.exe" --ks ./signtest.keystore --ks-key-alias signtest --key-pass pass:12345678 --ks-pass pass:12345678

ren buildtestnew-Universal.apks buildtestnew-Universal.zip

powershell -command "Expand-Archive buildtestnew-Universal.zip .\buildtestnew"

keytool -printcert -jarfile .\buildtestnew\universal.apk

"C:\Program Files (x86)\Android\android-sdk\build-tools\32.0.0\apksigner.bat" verify -v ./buildtestnew/universal.
```

This outputs that the APK is signed.

But this:

``` shell
"C:\Program Files\Microsoft\jdk-11.0.12.7-hotspot\bin\java.exe" -Xmx1G -jar "C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.476\tools\bundletool.jar" build-apks --mode universal --bundle radiostorm-Signed.aab --output radiostorm-Universal.apks --aapt2 "C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.476\tools\aapt2.exe" --ks ./signtest.keystore --ks-key-alias signtest --key-pass pass:12345678 --ks-pass pass:12345678

ren radiostorm-Universal.apks radiostorm-Universal.zip

powershell -command "Expand-Archive radiostorm-Universal.zip .\radiostorm"

keytool -printcert -jarfile .\radiostorm\universal.apk

"C:\Program Files (x86)\Android\android-sdk\build-tools\32.0.0\apksigner.bat" verify -v ./radiostorm/universal.apk
```

Says that the APK is unsigned. 

I have tried with `--output-format DIRECTORY` too. Nice command, but didn't make a difference.

**Comment by dellis1972** [comment] 2022-10-26 15:55
This is using the same keystore for both calls?
Its very confusing that a default maui template works but your app does not. specially as all the arguments are the same. The only thing I can think of is there is something wrong with the keystore and bundletool is ignoring it but not reporting that during a verbose build.

**Comment by pekspro** [comment] 2022-10-26 16:11
@dellis1972, yes, it is identical keystore. Created with this command:

```shell
keytool -genkey -v -keystore signtest.keystore -alias signtest -keyalg RSA -keysize 2048 -validity 10000
```

This inconsistency is why created this issue from the beginning :-). It's super confusing.

**Comment by jonathanpeppers** [comment] 2022-10-26 16:27
It looks like there are several new releases of bundletool:

https://github.com/google/bundletool/releases

You should be able to download one of these and pass `-p:AndroidBundleToolJarPath=path\to\new\bundletool.jar`, just to see if that helps at all?

**Comment by pekspro** [comment] 2022-10-26 16:29
@jonathanpeppers, I have tried with the latest version of bundletool, there was no difference.

**Comment by jonathanpeppers** [comment] 2022-10-26 16:39
If you have a repro that is command-line, can you file an issue here:

https://github.com/google/bundletool/issues

If you can give them an `.aab` file and an example command showing it's broken, maybe Google will fix it? If they can see the issue without building a C#/.NET app, they might know what is going on.

**Comment by PureWeen** [comment] 2022-10-27 19:12
Closing in favor of the google issue.

**Closed by PureWeen** 2022-10-27 19:12 UTC
Labels: t/bug, area/publishing 🏁, partner/android
