### ISSUE TITLE
Packaged WPF Blazor WebView app crashes when looking for wwwroot in system32

### ISSUE THREAD

**Issue by agc93** [dotnet/maui#3866] opened 2021-12-28 02:02 UTC
### Description

When using a WPF app with a BlazorWebView hosting a component from a Razor class library, the app will run as expected. However, including the WPF app in an MSIX packaging project and running it will instead result in a `DirectoryNotFoundException` when it attempts to locate `wwwroot` in `system32`.

I have created a repro that shows the issue [in this repo](https://github.com/whyareyoudoingthis/BlazorWpfMsix)

### Steps to Reproduce

1. Create a Razor class library with Blazor components
2. Create a WPF app, update the Project SDK and add the required packages/references
3. Add a `BlazorWebView` control, using a component from the RCL
4. Run the WPF app directly (this works!)
5. Add the WPF app to an MSIX packaging project
6. Debug the packaging project to run the packaged app: exception occurs.

### Version with bug

Preview 11

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10

### Did you find any workaround?

None found, but I originally thought this would be fixed by #3582 .

### Relevant log output

```shell
System.IO.DirectoryNotFoundException
  HResult=0x80070003
  Message=C:\WINDOWS\system32\wwwroot\
  Source=Microsoft.Extensions.FileProviders.Physical
  StackTrace:
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root, ExclusionFilters filters)
   at Microsoft.AspNetCore.Components.WebView.Wpf.BlazorWebView.StartWebViewCoreIfPossible()
   at Microsoft.AspNetCore.Components.WebView.Wpf.BlazorWebView.OnApplyTemplate()
   at System.Windows.FrameworkElement.ApplyTemplate()
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at MS.Internal.Helper.MeasureElementWithSingleChild(UIElement element, Size constraint)
   at System.Windows.Controls.ContentPresenter.MeasureOverride(Size constraint)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at System.Windows.Controls.Decorator.MeasureOverride(Size constraint)
   at System.Windows.Documents.AdornerDecorator.MeasureOverride(Size constraint)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at System.Windows.Controls.Border.MeasureOverride(Size constraint)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at System.Windows.Window.MeasureOverrideHelper(Size constraint)
   at System.Windows.Window.MeasureOverride(Size availableSize)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at System.Windows.Interop.HwndSource.SetLayoutSize()
   at System.Windows.Interop.HwndSource.set_RootVisualInternal(Visual value)
   at System.Windows.Interop.HwndSource.set_RootVisual(Visual value)
   at System.Windows.Window.SetRootVisual()
   at System.Windows.Window.SetRootVisualAndUpdateSTC()
   at System.Windows.Window.SetupInitialState(Double requestedTop, Double requestedLeft, Double requestedWidth, Double requestedHeight)
   at System.Windows.Window.CreateSourceWindow(Boolean duringShow)
   at System.Windows.Window.CreateSourceWindowDuringShow()
   at System.Windows.Window.SafeCreateWindowDuringShow()
   at System.Windows.Window.ShowHelper(Object booleanBox)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at WpfHost.App.Main()

  This exception was originally thrown at this call stack:
    [External Code]
```

**Comment by isaacrlevin** [comment] 2022-01-10 21:39
@Eilon looks like others are having this issue we were chatting about on Twitter. My stack trace looks the same.

**Comment by isaacrlevin** [comment] 2022-01-10 21:51
Confirmed there is a wwwroot folder present in the AppX published directory
![image](https://user-images.githubusercontent.com/8878502/148844881-80acfd22-6107-47cb-9341-2eab0a50729f.png)

**Comment by Eilon** [comment] 2022-01-11 06:11
Yeah that's weird! I thought I fixed some stuff around this area recently, but maybe I didn't, or maybe I broke something that was previously working. These are some recent possibly-relevant changes:

* https://github.com/dotnet/maui/pull/3582
* https://github.com/dotnet/maui/pull/3532

**Comment by agc93** [comment] 2022-01-11 08:46
Good to know I'm not the only one hitting this!

I even tried adding a custom `BlazorWebView` implementation with its own `CreateFileProvider` using the correct path, but still got the same error. Seems to be still looking in `Environment.CurrentDirectory` which seems to be `system32` when running from the packaged app.

**Comment by isaacrlevin** [comment] 2022-01-11 16:47
@Eilon is there a way to "easily" build the source for Webview without the MAUI repo? I can test this and maybe open a PR if I can figure it out

**Comment by isaacrlevin** [comment] 2022-01-11 17:14
Ok, so I was able to take your project @agc93 and plug it into the latest from main in the MAUI repo and it works. I guess that means that whenever what is currently is in main is in a preview, this should work. Can you confirm when that will be @Eilon :)

**Comment by isaacrlevin** [comment] 2022-01-13 18:14
@Eilon I assume the latest in main is coming in Preview 12? Looks like the code there this is no longer an issue.

**Comment by agc93** [comment] 2022-01-14 02:55
and if the fix is not coming until Preview 12, is there any ETA on it?

**Comment by isaacrlevin** [comment] 2022-01-18 16:18
@Eilon any insight here?

**Comment by Eilon** [comment] 2022-01-18 16:41
@isaacrlevin I will look at this today.

**Comment by mkArtakMSFT** [comment] 2022-01-19 21:42
Preview12 just shipped today. Can you guys please try it out and confirm whether this is still an issue or not?

**Comment by isaacrlevin** [comment] 2022-01-20 02:02
WORKS FOR ME!!!!!!!!!!!!!!!!!
![image](https://user-images.githubusercontent.com/8878502/150250376-182fce89-f740-40c9-b5f6-55851dde4d1c.png)

**Comment by Eilon** [comment] 2022-01-20 04:40
Beautiful! 😊

So I think it's safe to close this now. If anyone is still running into an issue, please confirm that you've updated to Preview 12 (released today). If that still isn't working, please provide as many details as possible so that we can investigate further.

**Comment by agc93** [comment] 2022-01-20 06:53
I've updated to Preview 12 and still not able to run the application packaged. Should it just be a case of updating the NuGet packages and it should be working?

**Comment by agc93** [comment] 2022-01-20 07:12
I've updated the repro I originally created for this issue @Eilon and it now gives a different error, but still doesn't work.

```
System.Reflection.TargetInvocationException
  HResult=0x80131604
  Message=Exception has been thrown by the target of an invocation.
  Source=System.Private.CoreLib
  StackTrace:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Delegate.DynamicInvoke(Object[] args)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at WpfHost.App.Main()

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
ArgumentException: The parameter is incorrect.

```

**Comment by isaacrlevin** [comment] 2022-01-20 14:25
That is all I did and it worked running from Visual Studio, I have another issue. I packaged my app for the Windows Store and when I run it, I get a blank screen. I have no real idea how to debug this, but looking in the WindowsApp folder the wwwroot folder is there
![image](https://user-images.githubusercontent.com/8878502/150356408-19f22bef-bd2a-46aa-88d2-b1361ea800dc.png)

@Eilon @mkArtakMSFT was Blazor Web View ever tested on a published app (.appxbundle) and is there anyone in App Packaging that can help me out?

**Comment by Eilon** [comment] 2022-01-20 14:49
OK thank you for trying it I'm reopening so we can investigate.

**Comment by isaacrlevin** [comment] 2022-01-20 17:41
I have some "useful" info. Before I had my app running in SingleFile and ReadyToRun Mode. I disabled those things and now it seems to be working.

Not sure if that is supposed to work or not. So a self-contained app not single file packaged and published WILL work. Here is a link of it working

https://presencelight.blob.core.windows.net/nightly/index.html

**Comment by isaacrlevin** [comment] 2022-01-25 17:39
ping @Eilon for update

**Comment by VincentBu** [comment] 2022-03-18 03:47
Hi @agc93 ,  I run [MSIX packaging project](https://github.com/whyareyoudoingthis/BlazorWpfMsix) on my windows and there was no exception. Does the following screenshot show the expected behavior?
![image](https://user-images.githubusercontent.com/44959937/158933332-49792f7b-5e06-4b1b-b07c-cc160ca621ae.png)

**Comment by agc93** [comment] 2022-03-22 03:32
Thanks for checking @VincentBu , let me try the sample again and see if it's working now.

**Comment by javiercn** [comment] 2022-03-30 13:46
This seems to be working correctly with the latest preview.

![image](https://user-images.githubusercontent.com/6995051/160849517-71b66eb4-52b3-4c4b-a1b7-7ecf9c49f95a.png)

**Comment by agc93** [comment] 2022-04-05 03:35
Yep, updated everything to the latest and it seems to run, seems like it's fixed.

**Closed** 2022-04-05 09:09 UTC
Labels: t/bug, area/blazor 🕸️, s/verified
