### ISSUE TITLE
SearchBar does not unfocus and hide keyboard on iOS

### ISSUE THREAD

**Issue by 3steve3** [dotnet/maui#11542] opened 2022-11-21 23:22 UTC
### Description

I'm trying to create a search bar with some results in a list view that appear. When a user taps a result in the list view or presses search in the keyboard I try to unfocus the search bar to hide the keyboard, but the keyboard does not disappear even though the event fires and calls unfocus for the search bar.

### Steps to Reproduce

1. Create a new content page
2. Add a searchbar and a list view
3. Add event handler that unfocuses searchbar when a listview item is tapped
4. Keyboard will not disappear

### Link to public reproduction project repository

https://github.com/3steve3/SearchBarBug

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 16

**Comment by PureWeen** [comment] 2022-11-22 16:45
The problem here is that the `SearchBar` element's "IsFocused" property doesn't toggle to `True` when it's focused.  The `UnFocus()` call inside `VisualElement` checks the value of `IsFocused` before trying to trigger a `focus` call to the platform 

![image](https://user-images.githubusercontent.com/5375137/203371930-b2a4ecf3-156c-47ef-8c20-abb420351765.png)

One workaround is to manually set `IsFocused` yourself.

```C#
(searchBar as IView).IsFocused = true
searchBar.UnFocus()
```

I wonder if inside our `VisualElement` code we should be checking the platform as the ultimate truth if an element is focused. I realize that masks the `IsFocused` property being semi broken and not firing `FocusChanged` but it at least makes `IsFocused` always correct.

**Comment by PureWeen** [comment] 2022-11-22 16:46
This is basically a duplicate of https://github.com/dotnet/maui/issues/6482

**Closed** 2023-03-20 15:36 UTC
Labels: t/bug, platform/iOS 🍎, area/controls 🎮, control-entry
