### ISSUE TITLE
<Image> cannot load image from URL on Android

### ISSUE THREAD

**Issue by 1ffycat** [dotnet/maui#6295] opened 2022-04-20 09:36 UTC
### Description

When setting Image Source to URL it doesn't load on Android, though it does on Windows (iOS / Mac untested)

Windows:
![image](https://user-images.githubusercontent.com/27009596/164193471-12dcae73-2d17-4716-9bd6-8e308eb9ed58.png)

Android:
![image](https://user-images.githubusercontent.com/27009596/164194018-3a8e9382-5f72-45c3-ad2c-a4008dc79b44.png)

Workarounds I've found that didn't help:
1. Changing `android:targetSdkVersion to 26`, adding `android:usesCleartextTraffic="true"` to `<application>`
2. Replacing HTTPS link with HTTP
3. Changing `HttpClient implementation` and `SSL/TLS implementation` in project properties

### Steps to Reproduce

1. Create a new MAUI Preview app
2. Change image's Source to any URL (https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/.NET_Logo.svg/150px-.NET_Logo.svg.png in my case)
3. Run on Android

MainPage.xaml code:
```xml <?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="TestMAUI.MainPage">

    <ScrollView>
        <VerticalStackLayout Spacing="25" Padding="30">

            <Label 
                Text="Hello, World!"
                SemanticProperties.HeadingLevel="Level1"
                FontSize="32"
                HorizontalOptions="Center" />

            <Label 
                Text="Welcome to .NET Multi-platform App UI"
                SemanticProperties.HeadingLevel="Level1"
                SemanticProperties.Description="Welcome to dot net Multi platform App U I"
                FontSize="18"
                HorizontalOptions="Center" />

            <Label 
                Text="Current count: 0"
                FontSize="18"
                FontAttributes="Bold"
                x:Name="CounterLabel"
                HorizontalOptions="Center" />

            <Button 
                Text="Click me"
                FontAttributes="Bold"
                SemanticProperties.Hint="Counts the number of times you click"
                Clicked="OnCounterClicked"
                HorizontalOptions="Center" />

            <Image
                Source="https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/.NET_Logo.svg/150px-.NET_Logo.svg.png"
                SemanticProperties.Description="Cute dot net bot waving hi to you!"
                WidthRequest="250"
                HeightRequest="310"
                HorizontalOptions="Center" />

        </VerticalStackLayout>
    </ScrollView>
</ContentPage>
```

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 10

**Comment by XamlTest** [comment] 2022-04-20 09:52
Verified this issue with Visual Studio Enterprise 17.3.0 Preview 1.0 [32414.199.main]. Repro on Android. Sample Project: [6295.zip](https://github.com/dotnet/maui/files/8520436/6295.zip)

**Comment by Blutchie** [comment] 2022-04-20 09:56
I had the same issue. What I tried instead was creating an ImageService that would download the image to cache folder. Then I tried to set the Source with ImageSource.FromFile(pathToCacheFolder). And also this didn't load show the image.

**Comment by 1ffycat** [comment] 2022-04-20 10:10
I think it's also worth mentioning that I've tried loading image from stream:
```C#
var byteArray = new WebClient().DownloadData(url);
this.myImage.Source = ImageSource.FromStream(() => new MemoryStream(byteArray));
```
Didn't help either. Also, JSON and other text loads fine so I suppose it's either about images or files generally

**Comment by janseris** [comment] 2022-04-20 10:49
@1ffycat  yeah images just don't work on Android
https://github.com/dotnet/maui/issues/6256 - `<Image>` or `<ImageButton>` from byte[] doesn't work
https://github.com/dotnet/maui/issues/6228 - `<Image>` from embedded resource doesn't work

**Comment by jfversluis** [comment] 2022-04-20 11:59
Duplicate of https://github.com/dotnet/maui/issues/6067

**Closed by jfversluis** 2022-04-20 11:59 UTC
Labels: t/bug, platform/android 🤖, s/verified, s/triaged

**Comment by gizmohd** [comment] 2022-04-26 00:40
How can all the issues related to this be closed?

**Comment by gizmohd** [comment] 2022-04-26 00:43
How are all these issues getting closed without fixes?

**Comment by jfversluis** [comment] 2022-04-26 17:47
I think RC2 is about to be released right now. Not sure if the fixes for the images made it for RC2 though. Might be for RC3.

**Comment by limefrogyank** [comment] 2022-04-26 23:52
Nope, didn't make it.
