### ISSUE TITLE
Add better support for Android 12+ Splash Screen APIs

### ISSUE THREAD

**Issue by nguyenvuhoang** [dotnet/maui#23228] opened 2024-06-25 07:37 UTC
### Description

Add better support for Android 12+ Splash Screen APIs

### Steps to Reproduce

Add better support for Android 12+ Splash Screen APIs

### Version with bug

8.0.60 SR6

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.60 SR6

### Affected platforms

Android

### Affected platform versions

Android 14

**Comment by jfversluis** [comment] 2024-06-25 08:31
Duplicate of #10604

**Closed by jfversluis** 2024-06-25 08:31 UTC
Labels: t/bug
