### ISSUE TITLE
Maui .Net 8 iOS MediaPicker.CapturePhotoAsync issue returns null after user presses USE PHOTO on apple device

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#23254] opened 2024-06-25 22:35 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Maui-Net-8-iOS-MediaPickerCapturePhoto/10688814)._

---
[severity:I'm unable to use this version]
Hi,

Maui .Net 8 iOS MediaPicker.CapturePhotoAsync issue returns null after user presses USE PHOTO on apple device.

This does however work perfectly on Windows and Android.

Code snippet:
        public async Task<List<Photo>> TakePic(ContentPage page)
        {
            var Photos = new List<Photo>();

Photo photo = new Photo();

try
            {
                await page. DisplayAlert("Debug", $"IsCaptureSupported {MediaPicker.Default.IsCaptureSupported}", "Ok");
                if (MediaPicker.Default.IsCaptureSupported)
                {
                    await page. DisplayAlert("Debug", $"taking pic", "Ok");

var photoFile = await MediaPicker.Default.CapturePhotoAsync(new MediaPickerOptions { Title = "Please take a photo" });

if (photoFile != null) //iOS returns null here?

Installed Packages:
		<PackageReference Include="CommunityToolkit.Maui" Version="9.0.1" />
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.2" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.4" />
		<PackageReference Include="Microsoft.Maui.Controls" Version="8.0.60" />
		<PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="8.0.60" />
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="8.0.0" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />

I am getting the same results on iPad Air 2 iOS 15.8.2 and iPhone 8 iOS 16.3.1

---
#### Feedback Bot on 6/23/2024, 06:41 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by jfversluis** [comment] 2024-06-26 09:48
Duplicate of #23197

**Closed by jfversluis** 2024-06-26 09:48 UTC
