### ISSUE TITLE
Spurious `XFC0040` errors.

### ISSUE THREAD

**Issue by RobTF** [dotnet/maui#21848] opened 2024-04-15 17:46 UTC
### Description

I have a style in a XAML file which looks like this;

```xaml
    <Style TargetType="{x:Type tctrls:ScrollableTileView}">
        <Setter Property="Padding" Value="2" />
    </Style>
```

When I build I get the following output which points at the `Setter` line;

`XamlC error XFC0040: Cannot convert value "Padding" to "Microsoft.Maui.Controls.BindableProperty".`

The type `tctrls:ScrollableTileView` is a very simple class which inherits from `ContentView` so the `Padding` property is just the normal MAUI property, not some custom property I have defined.

Any ideas why this might be? There are no problems with MAUI 8 SR3.

### Version with bug

8.0.20 SR4

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.10 SR3

### Affected platforms

iOS, Android

### Affected platform versions

All versions of iOS, Android. Probably all others too.

### Did you find any workaround?

Not yet.

### Relevant log output

```shell
XamlC error XFC0040: Cannot convert value "Padding" to "Microsoft.Maui.Controls.BindableProperty".
```

**Comment by nll** [comment] 2024-04-15 18:40
Have a look at #21757 , there is a workaround or you can revert to previous MAUI version

**Comment by ninachen03** [comment] 2024-04-16 03:11
Verified this issue with Visual Studio 17.10.0 Preview 3(8.0.20). Can repro it but not repro in Maui control version:8.0.14
![image](https://github.com/dotnet/maui/assets/128687574/b1290645-53d7-421b-9b30-9bc231b10d38)

**Comment by RobTF** [comment] 2024-04-16 10:14
Thanks guys that's really useful! That said we'll be stepping away from this release as that's too big a problem for us even with the supposed workaround.

**Comment by PureWeen** [comment] 2024-04-16 18:06
Duplicate of #21757

**Closed by PureWeen** 2024-04-16 18:06 UTC
Labels: t/bug, platform/android 🤖, platform/iOS 🍎, s/verified, s/triaged, potential-regression

**Comment by CodingOctocat** [comment] 2024-05-28 06:56
8.0.40 Ran into this issue again.
