### ISSUE TITLE
[Bug] CodeBehind source generator breaks when use the `x:TypeArguments`

### ISSUE THREAD

**Issue by pictos** [dotnet/maui#2304] opened 2021-08-29 17:06 UTC
### Description

IF you have a View that uses the `x:TypeArguments` the Source Generator will generate the generic type wrong.

```xml
<xct:Popup xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
           xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
           xmlns:xct="http://xamarin.com/schemas/2020/toolkit"
           xmlns:local="clr-namespace:Xamarin.CommunityToolkit.Sample.Pages.Views.Popups"
           Size="{x:Static local:PopupSize.Medium}"
           x:Class="Xamarin.CommunityToolkit.Sample.Pages.Views.Popups.ReturnResultPopup"
           x:TypeArguments="x:String">
```
```csharp
//Generated code
[global::Microsoft.Maui.Controls.Xaml.XamlFilePath("C:\\Users\\Jesus\\source\\repos\\MauiBugRepro\\MauiBugRepro\\ReturnResultPopup.xaml")]
	public partial class ReturnResultPopup : global::Xamarin.CommunityToolkit.UI.Views.Popup`1<global::System.String>
```

I believe that   _`1_ shouldn't be there.

### Steps to Reproduce

1. Create new maui app add the XCT.MauiCompat nuget
2. Create a Popup View that declares `x:TypeArguments`
3. Try to build

### Expected Behavior

Right C# code generated.

### Actual Behavior

Wrong C# code generated.

### Basic Information

- Version with issue: 6.0.100-preview.7.1345
- Last known good version: N/A
- IDE: VS 2022 Windows
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages: N/A
- Affected Devices: All

### Reproduction Link

https://github.com/pictos/MauiBugRepro/tree/GenericPageError

I added the nuget package [here](https://github.com/pictos/MauiBugRepro/tree/GenericPageError/MauiBugRepro) this way will be easier to test it.

**Comment by shimingsg** [comment] 2022-03-11 05:44
verified repro with VS 17.2.0 Preview 3.0 [32309.500.main]
![image](https://user-images.githubusercontent.com/20982341/157809312-e7c899ba-888c-41e6-9352-c2d9bbdd7938.png)
demo: 
[MauiApp2304.zip](https://github.com/dotnet/maui/files/8229392/MauiApp2304.zip)

**Comment by StephaneDelcroix** [comment] 2022-03-23 08:07
having a top-level generic wasn't possible with the XamlG task in Xamarin.Forms, but I think it's fixable with Maui SourceGen

**Comment by StephaneDelcroix** [comment] 2022-03-23 12:19
can't repro on macOS

**Comment by pictos** [comment] 2022-03-23 13:35
> having a top-level generic wasn't possible with the XamlG task in Xamarin.Forms, but I think it's fixable with Maui SourceGen

Not sure if I follow your comment here, but this worked on XF, this code is me porting an XF code to .NET MAUI

**Comment by StephaneDelcroix** [comment] 2022-05-04 12:26
We have at least one unit test showing that this works https://github.com/dotnet/maui/blob/main/src/Controls/tests/Xaml.UnitTests/Issues/Gh6176.xaml on all the platforms we run tests on

Anything special about your setup ? locale, toolchain, ...

(I was wrong about my XamlG comment, this was already supported in XF)

**Comment by pictos** [comment] 2022-05-04 14:13
@StephaneDelcroix I don't think I was running something customized...

Windows locale: pt-BR
VS locale: en-US


Your unit tests ran against `Page` type, this issue is related to a control (inherit from `Element`), so could that influenciate? I'll try to reproduce it with RC2 and let you know what I find.

**Comment by StephaneDelcroix** [comment] 2022-05-04 14:18
> Your unit tests ran against `Page`

the CodeGen is agnostic the to the types it runs on

**Comment by homeyf** [comment] 2023-04-10 09:34
Verified this issue on Visual Studio Enterprise 17.6.0 Preview 2.0. Repro with mentioned project.
![image](https://user-images.githubusercontent.com/82450723/230875586-be1c1ccf-79c6-499e-81a4-5b386aa7b6ac.png)

**Comment by jfversluis** [comment] 2023-05-09 12:33
Same thing happens when using it with the .NET MAUI Community Toolkit LazyView with the simplest example that you can find here: https://learn.microsoft.com/dotnet/communitytoolkit/maui/views/lazyview

**Comment by StephaneDelcroix** [comment] 2023-06-14 13:12
@jfversluis the x:Name thing is slightly different, but might be related

**Comment by jonpryor** [comment] 2023-07-31 23:05
[MauiApp2304.zip](https://github.com/dotnet/maui/files/8229392/MauiApp2304.zip) fails to build for me when using main 19649381f4a7d9395f29bc5855d0f190a0b1e168 with the following patch applied:

```diff
diff --git a/MauiApp2304/MauiApp2304.csproj b/MauiApp2304/MauiApp2304.csproj
index b50e3d4..d739867 100644
--- a/MauiApp2304/MauiApp2304.csproj
+++ b/MauiApp2304/MauiApp2304.csproj
@@ -1,8 +1,9 @@
 <Project Sdk="Microsoft.NET.Sdk">
 
 	<PropertyGroup>
-		<TargetFrameworks>net6.0-android;net6.0-ios;net6.0-maccatalyst</TargetFrameworks>
-		<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows')) and '$(MSBuildRuntimeType)' == 'Full'">$(TargetFrameworks);net6.0-windows10.0.19041</TargetFrameworks>
+		<TargetFramework>net7.0-android</TargetFramework>
+		<EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
+		<CompilerGeneratedFilesOutputPath>obj-gs</CompilerGeneratedFilesOutputPath>
 		<OutputType>Exe</OutputType>
 		<RootNamespace>MauiApp2304</RootNamespace>
 		<UseMaui>true</UseMaui>
diff --git a/MauiApp2304/ReturnResultPopup.xaml.cs b/MauiApp2304/ReturnResultPopup.xaml.cs
index 96074de..46e04cb 100644
--- a/MauiApp2304/ReturnResultPopup.xaml.cs
+++ b/MauiApp2304/ReturnResultPopup.xaml.cs
@@ -1,5 +1,4 @@
 namespace MauiApp2304;
-using Microsoft.Maui.Essentials;
 using Microsoft.Maui.Graphics;
 public partial class ReturnResultPopup
 {
```

The build failures include:

```
MauiApp2304/MauiApp2304/Microsoft.Maui.Controls.SourceGen/Microsoft.Maui.Controls.SourceGen.CodeBehindGenerator/ReturnResultPopup.xaml.sg.cs(15,93): error CS1721: Class 'ReturnResultPopup' cannot have multiple base classes: 'Popup' and 'string' […/MauiApp2304/MauiApp2304/MauiApp2304.csproj]
```

If I instead use net8.0 0478e794d103afccad2ee5b35a953e5138433a1f and update `MauiApp2304.csproj` to have `$(TargetFramework)`=net8.0-android, I get the same failure.

To @StephaneDelcroix 's [earlier point](https://github.com/dotnet/maui/issues/2304#issuecomment-1117253042), I don't think that https://github.com/dotnet/maui/blob/main/src/Controls/tests/Xaml.UnitTests/Issues/Gh6176.xaml is in fact a similar test case because it doesn't involve a cross-assembly generic type reference.

By setting `$(EmitCompilerGeneratedFiles)`=true and `$(CompilerGeneratedFilesOutputPath)`=obj-gs, I'm able to easily see what the erroneous generated output contains, which is:

```csharp
public partial class ReturnResultPopup : global::Xamarin.CommunityToolkit.UI.Views.Popup`1<global::System.String>
```

In particular, note ``Popup`1`` in the output; the "generic arity" of the type has not been removed.

**Comment by jonpryor** [comment] 2023-08-01 21:00
[My guess](https://github.com/dotnet/maui/issues/2304#issuecomment-1659309560) that the issue is due to cross-assembly type references is wrong.  (Reasonable, but wrong.)

The *actual* problem is around `XmlnsDefinitionAttribute` support: the "problematic" XAML uses:

```xml
<xct:Popup xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
           xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
           xmlns:xct="http://xamarin.com/schemas/2020/toolkit"
           xmlns:local="clr-namespace:MauiApp2304"
           Size="{x:Static local:PopupSize.Medium}"
           x:Class="MauiApp2304.ReturnResultPopup"
           x:TypeArguments="x:String">
```

In particular, note the `xmlns:xct="http://xamarin.com/schemas/2020/toolkit"`.  If I change this to be`using:namespace` a'la [Gh6176.xaml](https://github.com/dotnet/maui/blob/main/src/Controls/tests/Xaml.UnitTests/Issues/Gh6176.xaml):

```xml
<xct:Popup xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
           xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
           xmlns:xct="using:Xamarin.CommunityToolkit.UI.Views"
           xmlns:local="clr-namespace:MauiApp2304"
           Size="{x:Static local:PopupSize.Medium}"
           x:Class="MauiApp2304.ReturnResultPopup"
           x:TypeArguments="x:String">
```

then the resulting codebehind is valid C#:

```csharp
public partial class ReturnResultPopup : global::Xamarin.CommunityToolkit.UI.Views.Popup<global::System.String>
```

After an *inordinate* amount of hackery to get a new `Microsoft.Maui.Controls.SourceGen.dll` used by the app build with the following patch applied to dotnet/maui:

```diff
diff --git a/src/Controls/src/SourceGen/CodeBehindGenerator.cs b/src/Controls/src/SourceGen/CodeBehindGenerator.cs
index 839f620521..789c87a15f 100644
--- a/src/Controls/src/SourceGen/CodeBehindGenerator.cs
+++ b/src/Controls/src/SourceGen/CodeBehindGenerator.cs
@@ -306,8 +306,8 @@ namespace Microsoft.Maui.Controls.SourceGen
 
 			namedFields = GetNamedFields(root, nsmgr, compilation, caches, cancellationToken);
 			var typeArguments = GetAttributeValue(root, "TypeArguments", XamlParser.X2006Uri, XamlParser.X2009Uri);
-			baseType = GetTypeName(new XmlType(root.NamespaceURI, root.LocalName, typeArguments != null ? TypeArgumentsParser.ParseExpression(typeArguments, nsmgr, null) : null), compilation, caches);
+			baseType = "/* jonp: TryParseXaml */ " + GetTypeName(new XmlType(root.NamespaceURI, root.LocalName, typeArguments != null ? TypeArgumentsParser.ParseExpression(typeArguments, nsmgr, null) : null), compilation, caches);
+			Console.Error.WriteLine ($"# jonp: TryParseXaml: baseType={baseType}");
 
 			// x:ClassModifier attribute
 			var classModifier = GetAttributeValue(root, "ClassModifier", XamlParser.X2006Uri, XamlParser.X2009Uri);
@@ -365,8 +365,8 @@ namespace Microsoft.Maui.Controls.SourceGen
 			string returnType;
 			var ns = GetClrNamespace(xmlType.NamespaceUri);
 			if (ns != null) {
-				returnType = $"{ns}.{xmlType.Name}";
+				Console.Error.WriteLine($"# jonp: GetTypeName: xmlType.Name=`{xmlType.Name}`");
+				returnType = $"/* jonp: GetTypeName */ {ns}.{xmlType.Name}";
 			}
 			else
 			{
@@ -416,9 +416,9 @@ namespace Microsoft.Maui.Controls.SourceGen
 
 					return null;
 				});
+			Console.Error.WriteLine ($"# jonp: GetTypeNameFromCustomNamespace: typeName={typeName}");
 
-			return typeName;
+			return "/* jonp: GetTypeNameFromCustomNamespace */ " + typeName;
 #nullable enable
 		}
 
```

my resulting source generator output contains:

```csharp
public partial class ReturnResultPopup : /* jonp: TryParseXaml */ global::/* jonp: GetTypeNameFromCustomNamespace */ Xamarin.CommunityToolkit.UI.Views.Popup`1<global::/* jonp: GetTypeName */ System.String>
```

suggesting that the "problem" is in: https://github.com/dotnet/maui/blob/ab09cf98bc17f57725e8d088cbf02c3f0723cea3/src/Controls/src/SourceGen/CodeBehindGenerator.cs#L391-L419

Which could be fixed with:

```diff
diff --git a/src/Controls/src/SourceGen/CodeBehindGenerator.cs b/src/Controls/src/SourceGen/CodeBehindGenerator.cs
index 839f620521..c06a7a82ab 100644
--- a/src/Controls/src/SourceGen/CodeBehindGenerator.cs
+++ b/src/Controls/src/SourceGen/CodeBehindGenerator.cs
@@ -307,7 +307,6 @@ namespace Microsoft.Maui.Controls.SourceGen
 			namedFields = GetNamedFields(root, nsmgr, compilation, caches, cancellationToken);
 			var typeArguments = GetAttributeValue(root, "TypeArguments", XamlParser.X2006Uri, XamlParser.X2009Uri);
 			baseType = GetTypeName(new XmlType(root.NamespaceURI, root.LocalName, typeArguments != null ? TypeArgumentsParser.ParseExpression(typeArguments, nsmgr, null) : null), compilation, caches);
-			throw new Exception ($"# jonp: TryParseXaml: baseType={baseType}");
 
 			// x:ClassModifier attribute
 			var classModifier = GetAttributeValue(root, "ClassModifier", XamlParser.X2006Uri, XamlParser.X2009Uri);
@@ -364,10 +363,8 @@ namespace Microsoft.Maui.Controls.SourceGen
 		{
 			string returnType;
 			var ns = GetClrNamespace(xmlType.NamespaceUri);
-			if (ns != null) {
-				throw new Exception($"# jonp: GetTypeName: xmlType.Name=`{xmlType.Name}`");
+			if (ns != null)
 				returnType = $"{ns}.{xmlType.Name}";
-			}
 			else
 			{
 				// It's an external, non-built-in namespace URL.
@@ -410,13 +407,18 @@ namespace Microsoft.Maui.Controls.SourceGen
 						if (type.ContainingAssembly.Identity.Name != typeInfo.assemblyName)
 							continue;
 
-						if (IsPublicOrVisibleInternal(type, caches.InternalsVisible))
-							return fullName;
+						if (!IsPublicOrVisibleInternal(type, caches.InternalsVisible))
+							continue;
+						int i = fullName.IndexOf('`');
+						if (i > 0)
+						{
+							fullName = fullName.Substring(0, i);
+						}
+						return fullName;
 					}
 
 					return null;
 				});
-			throw new Exception ($"# jonp: GetTypeNameFromCustomNamespace: typeName={typeName}");
 
 			return typeName;
 #nullable enable
```

***The Problem***: How do I *unit test* this puppy?  To make it work an `[assembly: XmlnsDefinition(URL, NAMESPACE)]` needs to be used, which *does* require an external assembly reference.  Is there an easy way to set this up?

**Closed** 2023-08-07 08:47 UTC
Labels: t/bug, area/Xaml </>, p/2, high, s/verified, s/triaged
