### ISSUE TITLE
Review the performance implications of using a Concurrent Dictionary inside WrappedServiceProvider

### ISSUE THREAD

**Issue by PureWeen** [dotnet/maui#8128] opened 2022-06-16 21:52 UTC
https://github.com/dotnet/maui/pull/8033#issuecomment-1156594576

Yeah it is `WrappedServiceProvider`:

![image](https://user-images.githubusercontent.com/840039/173858938-eb17a960-b18d-4f6d-8aea-19c99a4330fe.png)

[maui-app_20220614_112919.speedscope.zip](https://github.com/dotnet/maui/files/8910551/maui-app_20220614_112919.speedscope.zip)

But it should just be hitting that `ConcurrentDictionary`. This might only be a problem because `.Context` is called so many times.

- Do we need to use a `ConcurrentDictionary` ? 
- The amount of things that go into `ConcurrentDictionary` is a known quantity so should we just explicitly add all of these into MauiContext like we used to have? Currently all user requests are going to go through the `ConcurrentDictionary` for no useful reason.

**Comment by jonathanpeppers** [comment] 2022-08-18 14:31
I think we should review a newer `.speedscope` file for this, as I may have been testing a .NET 7 build that had a general performance regression in the Mono runtime that is now fixed.

**Comment by jonathanpeppers** [comment] 2022-08-18 20:57
I reviewed this, and there isn't really any time spent in `ConcurrentDictionary`. The time looks like it is actually just the ctor running for these types, like `App`'s ctor.

![image](https://user-images.githubusercontent.com/840039/185493314-7e69221b-765a-4423-9df3-780556f973db.png)

[dotnet-podcasts.zip](https://github.com/dotnet/maui/files/9377612/dotnet-podcasts.zip)

I think the cause of the issue before was the Mono runtime regression. I think we can close this one.

**Closed by jonathanpeppers** 2022-08-18 20:57 UTC
Labels: area/perf 🏎️
