### ISSUE TITLE
Selected item color 'CollectionView' in .NET 7.

### ISSUE THREAD

**Issue by BobAaldering** [dotnet/maui#11393] opened 2022-11-15 20:30 UTC
## Explanation

If you want to select an item in .NET 7 in a `CollectionView`, you can define a color yourself. This is also done in the [tutorial/reference](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/controls/collectionview/selection?view=net-maui-7.0) .
However if you follow this it should change the color of an item when an item is selected in your `CollectionView`, but it doesn't. A selection takes place, but the color is not retained if you move your mouse cursor away from the selected item.
On the other hand, if you build the project with the .NET 6.0 runtime, the color is retained after you move the mouse cursor away from the selected item.

## Images

The image below shows that the color of the first item changes when the mouse cursor **is on the selected item**.

![Color of the selected item, when the mouse cursor is on the item](https://user-images.githubusercontent.com/74597240/202016188-8d745af1-9f45-4c1e-baed-b537338bbb71.png)

The following image shows what the program does when you move the mouse cursor **away from the selected item**. The color that the item should keep is lost.

![The color disappeared when the mouse cursor is not on the selected item anymore.](https://user-images.githubusercontent.com/74597240/202016548-232515f9-bec8-4047-a0fc-e5d1cdc8144c.png)

## Summary

This problem does not occur in .NET 6.0. When an item is selected, the color is retained. Of course the color will be lost if you select different item (the behaviour that you expect).

### Steps to Reproduce

1. Clone the project, which is linked below.
2. Build the project, and run the application.
3. Select an item in the `CollectionView`. The color will change to light blue.
4. Remove the mouse from the already selected item. The color of the selected item will disappear. The light blue color is not retained (as intended).

### Link to public reproduction project repository

https://github.com/BobAaldering/TestApp

### Version with bug

7.0 (current)

### Last version that worked well

6.0.424

### Affected platforms

Windows

### Affected platform versions

Windows SDK 10.0.17763.0

### Did you find any workaround?

I have not found a workaround for this problem.

**Comment by PureWeen** [comment] 2022-11-16 19:31
Duplicate of #11238

**Closed by PureWeen** 2022-11-16 19:31 UTC
Labels: t/bug, area/collectionview 📃
