### ISSUE TITLE
Appshell menu item click, content page changes with glitch

### ISSUE THREAD

**Issue by Muhammadfaizann** [dotnet/maui#12051] opened 2022-12-13 13:07 UTC
### Description

I am using Appshell in my .net Maui app and on flyout menu item click content page changes with a laggy weird white glitch. 

p.s: happening on xamarin forms aswell

https://user-images.githubusercontent.com/40601789/207325862-763da46a-2e6f-4878-adcb-ac5a17b98030.mp4

![WhatsApp Image 2022-12-13 at 05 04 44](https://user-images.githubusercontent.com/40601789/207325893-ac362e6c-0d62-44e3-b480-bce25f9f4aa8.jpg)

### Steps to Reproduce

Create and Appshell in .net maui project and which contains a flyout menu item

### Link to public reproduction project repository

(na)

### Version with bug

6.0 Release Candidate 2 or older

### Last version that worked well

6.0 Release Candidate 2 or older

### Affected platforms

Android

### Affected platform versions

Android 11

**Comment by PureWeen** [comment] 2022-12-13 19:14
@Muhammadfaizann does this look like a duplicate of

https://github.com/dotnet/maui/issues/10713

**Comment by Muhammadfaizann** [comment] 2022-12-14 06:18
@PureWeen true that.

**Comment by angelru** [comment] 2022-12-14 06:20
@Muhammadfaizann 
I think that happens if you have different FlyoutItems, it makes that strange and annoying effect, I think this should pay close attention.

have you tried this?
```
<FlyoutItem FlyoutDisplayOptions="AsMultipleItems"
</FlyoutItem>
```

**Comment by Muhammadfaizann** [comment] 2022-12-14 08:30
@angelru Yes, I do have different FlyoutItems, and trying `FlyoutDisplayOptions="AsMultipleItems"` just adds separators between the flyout items.

**Comment by angelru** [comment] 2022-12-14 09:31
> @angelruSí, tengo diferentes FlyoutItems, y `FlyoutDisplayOptions="AsMultipleItems"`solo intento agregar separadores entre los elementos flotantes.

Try to have 1 grouped, I think the effect does not appear.

**Comment by angelru** [comment] 2022-12-14 10:41
> @angelru True having grouped flyoutItems fixed it for me but now I have flyout items in the bottom tabs bar as well how can I remove them from there?
> 
> ![InkedScreenshot_1671014044_LI](https://user-images.githubusercontent.com/40601789/207573196-4a3b789c-7c36-4ce0-956f-87266862eddc.jpg)

```
<FlyoutItem FlyoutDisplayOptions="AsMultipleItems"  Shell.TabBarIsVisible="False">
</FlyoutItem>
```

**Comment by angelru** [comment] 2022-12-14 10:42
This may be a partial solution, imagine you want another separate flyoutitem with bottom tabs, entering that nasty weird effect would reappear.

**Closed** 2022-12-14 10:53 UTC
Labels: t/bug, area/shell 🐢, s/needs-attention
