### ISSUE TITLE
Failed to mount developer tools on iPhone - Visual Studio Code

### ISSUE THREAD

**Issue by MLB-BIOMETRIC** [dotnet/maui#18040] opened 2023-10-16 09:21 UTC
### Description

Debugger can't be attached when developing .NET MAUI with an iPhone running iOS 17.0.x. 

**iOS Version:** ``17.0.3``
**.NET Workloads:**
```
Installed Workload Id      Manifest Version      Installation Source
--------------------------------------------------------------------
maui-maccatalyst           7.0.96/7.0.100        SDK 7.0.300        
maui-ios                   7.0.96/7.0.100        SDK 7.0.300        
maui-android               7.0.96/7.0.100        SDK 7.0.300 
```
**Target framework:** ``net7.0-ios``

**Error:**
```
2023-10-16 10:11:16.113 mlaunch[2801:60550] Thread Pool Worker DTDKRemoteDeviceConnection: Unable to start com.apple.instruments.remoteserver.DVTSecureSocketProxy on device “00008120-001628D811D8201E”. Falling back to service without proxy.
2023-10-16 10:11:16.139 mlaunch[2801:60562]  DTDKRemoteDeviceConnection: Failed to start remote service "com.apple.instruments.remoteserver" on device. Error: Error Domain=com.apple.dtdevicekit Code=811 "Failed to start remote service "com.apple.instruments.remoteserver" on device." UserInfo={NSUnderlyingError=0x7fd44e8c9440 {Error Domain=com.apple.dt.MobileDeviceErrorDomain Code=-402653150 "The service is invalid." UserInfo={MobileDeviceErrorCode=(0xE8000022), com.apple.dtdevicekit.stacktrace=(
0   DTDeviceKitBase                     0x000000011bcc35fc DTDKCreateNSErrorFromAMDErrorCode + 229
1   DTDeviceKitBase                     0x000000011bcd1595 __63-[DTDKRemoteDeviceConnection startFirstServiceOf:unlockKeybag:]_block_invoke + 612
2   DTDeviceKitBase                     0x000000011bcd0c4f __48-[DTDKRemoteDeviceConnection futureWithSession:]_block_invoke_4 + 22
3   DTDeviceKitBase                     0x000000011bcc596e __DTDKExecuteInSession_block_invoke_2 + 52
4   DTDeviceKitBase                     0x000000011bcc4fa6 __DTDKExecuteWithConnection_block_invoke_2 + 219
5   DTDeviceKitBase                     0x000000011bcc4ea0 __DTDKExecuteWithConnection_block_invoke + 119
6   libdispatch.dylib                   0x00007ff80f8a2033 _dispatch_client_callout + 8
7   libdispatch.dylib                   0x00007ff80f8afba1 _dispatch_lane_barrier_sync_invoke_and_complete + 60
8   DVTFoundation                       0x0000000118b02f24 DVTDispatchBarrierSync + 148
9   DVTFoundation                       0x0000000118ad8d43 -[DVTDispatchLock performLockedBlock:] + 60
10  DTDeviceKitBase                     0x000000011bcc4d96 DTDKExecuteWithConnection + 221
11  DTDeviceKitBase                     0x000000011bcc57f4 DTDKExecuteInSession + 275
12  DTDeviceKitBase                     0x000000011bcd0a22 __48-[DTDKRemoteDeviceConnection futureWithSession:]_block_invoke_2 + 207
13  DVTFoundation                       0x0000000118b02134 __DVT_CALLING_CLIENT_BLOCK__ + 7
14  DVTFoundation                       0x0000000118b02c20 __DVTDispatchAsync_block_invoke + 196
15  libdispatch.dylib                   0x00007ff80f8a0d91 _dispatch_call_block_and_release + 12
16  libdispatch.dylib                   0x00007ff80f8a2033 _dispatch_client_callout + 8
17  libdispatch.dylib                   0x00007ff80f8a8200 _dispatch_lane_serial_drain + 769
18  libdispatch.dylib                   0x00007ff80f8a8d6c _dispatch_lane_invoke + 417
19  libdispatch.dylib                   0x00007ff80f8b33fc _dispatch_workloop_worker_thread + 765
20  libsystem_pthread.dylib             0x00007ff80fa3fc55 _pthread_wqthread + 327
21  libsystem_pthread.dylib             0x00007ff80fa3ebbf start_wqthread + 15
), DVTRadarComponentKey=261622, NSLocalizedDescription=The service is invalid.}}, NSLocalizedRecoverySuggestion=Please check your connection to your device., DVTRadarComponentKey=261622, NSLocalizedDescription=Failed to start remote service "com.apple.instruments.remoteserver" on device.}
warning MT1043: Failed to launch the application using the instruments service. Will try launching the app using gdb service.
Launching 'com.company.app' on the device 'iPhone'
warning HE0030: Could not mount developer tools on 'iPhone': Could not locate device support files
warning HE0031: Failed to mount developer tools on 'iPhone'.
warning HE0030: Could not mount developer tools on 'iPhone': Could not locate device support files
warning HE0031: Failed to mount developer tools on 'iPhone'.
error MT1007: Failed to launch the application '/Users/xxx/Documents/mauiapp/app/bin/Debug/net7.0-ios/ios-arm64/app' on the device 'iPhone': Failed to launch the application 'com.company.app' on the device 'iPhone': Invalid Service Error (error: 0xe8000022)
. You can still launch the application manually by tapping on it.
```

I have another iPhone that works perfectly with iOS 16.6. 

### Steps to Reproduce

1. Create new MAUI App
2. Debug on physical device with iOS 17.0.x installed
3. Debugger fails to connect :( 

### Version with bug

7.0.96

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, I was *not* able test on other platforms

### Affected platform versions

iOS 17.0.x

### Did you find any workaround?

Nope.

**Comment by MLB-BIOMETRIC** [comment] 2023-10-16 09:23
Related to #17718 - but not sure why it was closed. I created this one for it not to be forgotten by the Microsoft Dev Team.

**Comment by drasticactions** [comment] 2023-10-16 09:39
> Related to #17718 - but not sure why it was closed. I created this one for it not to be forgotten by the Microsoft Dev Team.

The original person who opened it closed it, for whatever reason. This issue isn't related to the MAUI UI project (which is what this repo is for), it's probably a tooling or setup issue with [xamarin/xamarin-macios](https://github.com/xamarin/xamarin-macios) or tooling within the [MAUI vscode extension](https://github.com/microsoft/vscode-dotnettools/), not something that can be fixed within this repo.

@rolfbjarne @emaf Is there a good place for this issue to go to?

**Comment by rolfbjarne** [comment] 2023-10-16 10:58
This is a known issue (https://github.com/xamarin/xamarin-macios/issues/19101), which we've already fixed and we hope to release the fix soon.

Closing as duplicate of https://github.com/xamarin/xamarin-macios/issues/19101

**Closed by rolfbjarne** 2023-10-16 10:58 UTC
Labels: t/bug
