### ISSUE TITLE
Object reference not set to instance of an object in ShellToolbarAppearanceTracker.SetColors

### ISSUE THREAD

**Issue by JoacimWall** [dotnet/maui#13861] opened 2023-03-13 08:30 UTC
### Description

On Android have I AppShell and Tab pages. Start app all works as expected but after resume try to navigate I get this error.  All works perfect on iOS.

```
at Microsoft.Maui.Controls.Platform.Compatibility.ShellToolbarAppearanceTracker.SetColors(Toolbar toolbar, IShellToolbarTracker toolbarTracker, Color foreground, Color background, Color title) in D:\a\_work\1\s\src\Controls\src\Core\Compatibility\Handlers\Shell\Android\ShellToolbarAppearanceTracker.cs:line 36
   at Microsoft.Maui.Controls.Platform.Compatibility.ShellToolbarAppearanceTracker.SetAppearance(Toolbar toolbar, IShellToolbarTracker toolbarTracker, ShellAppearance appearance) in D:\a\_work\1\s\src\Controls\src\Core\Compatibility\Handlers\Shell\Android\ShellToolbarAppearanceTracker.cs:line 26
   at Microsoft.Maui.Controls.Platform.Compatibility.ShellSectionRenderer.SetAppearance(ShellAppearance appearance) in D:\a\_work\1\s\src\Controls\src\Core\Compatibility\Handlers\Shell\Android\ShellSectionRenderer.cs:line 320
   at Microsoft.Maui.Controls.Platform.Compatibility.ShellSectionRenderer.Microsoft.Maui.Controls.IAppearanceObserver.OnAppearanceChanged(ShellAppearance appearance) in D:\a\_work\1\s\src\Controls\src\Core\Compatibility\Handlers\Shell\Android\ShellSectionRenderer.cs:line 53
   at Microsoft.Maui.Controls.Shell.Microsoft.Maui.Controls.IShellController.AppearanceChanged(Element source, Boolean appearanceSet) in D:\a\_work\1\s\src\Controls\src\Core\Shell\Shell.cs:line 476
   at Microsoft.Maui.Controls.ShellSection.SendAppearanceChanged() in D:\a\_work\1\s\src\Controls\src\Core\Shell\ShellSection.cs:line 1005
   at Microsoft.Maui.Controls.ShellSection.UpdateDisplayedPage() in D:\a\_work\1\s\src\Controls\src\Core\Shell\ShellSection.cs:line 646
   at Microsoft.Maui.Controls.ShellSection.OnVisibleChildAdded(Element child) in D:\a\_work\1\s\src\Controls\src\Core\Shell\ShellSection.cs:line 689
   at Microsoft.Maui.Controls.ShellSection.OnChildAdded(Element child) in D:\a\_work\1\s\src\Controls\src\Core\Shell\ShellSection.cs:line 661
   at Microsoft.Maui.Controls.BaseShellItem.AddLogicalChild(Element element) in D:\a\_work\1\s\src\Controls\src\Core\Shell\BaseShellItem.cs:line 274
   at Microsoft.Maui.Controls.ShellSection.AddPage(Page page) in D:\a\_work\1\s\src\Controls\src\Core\Shell\ShellSection.cs:line 997
   at Microsoft.Maui.Controls.ShellSection.OnPushAsync(Page page, Boolean animated) in D:\a\_work\1\s\src\Controls\src\Core\Shell\ShellSection.cs:line 854
   at Microsoft.Maui.Controls.ShellSection.PushStackOfPages(List`1 pages, Nullable`1 animate) in D:\a\_work\1\s\src\Controls\src\Core\Shell\ShellSection.cs:line 598  
   ```

### Steps to Reproduce

1. Download sample provided bug repo.

2. Start app test navigate button on tab 1
3.  Navigate back to page 1(Root)
4. Put app in sleep (go to home screen)
5. Resume app
6. Click on navigate = Crash 

### Link to public reproduction project repository

https://github.com/JoacimWall/Joacim_Bug_Report/tree/main/AndroidShell

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android all

### Did you find any workaround?

No

**Comment by mattleibow** [comment] 2023-03-13 15:23
Duplicate of #12460

**Closed by mattleibow** 2023-03-13 15:23 UTC
Labels: t/bug, platform/android 🤖, area/shell 🐢

**Comment by JoacimWall** [comment] 2023-03-14 06:54
Found a workaround
App.xaml.cs
protected async override void OnResume()
    {
        if (DeviceInfo.Platform == DevicePlatform.Android)
        {
            Shell.SetBackgroundColor(this, AppColors.Primary500Color);
            Shell.SetForegroundColor(this, AppColors.WhiteColor);
            Shell.SetTabBarBackgroundColor(this, AppColors.Primary800Color);
            Shell.SetTabBarForegroundColor(this, AppColors.PrimaryAccentColor);
            Shell.SetTabBarUnselectedColor(this, AppColors.WhiteColor);
            Shell.SetTabBarTitleColor(this, AppColors.PrimaryAccentColor);
        }
   }
