### ISSUE TITLE
Control event propagation?

### ISSUE THREAD

**Issue by josipx** [dotnet/maui#7332] opened 2022-05-19 14:14 UTC
### Description

I have simple MAUI app with ContentPage containing Button with **overlaying** Grid control, e.g.: 

```
 <Button VerticalOptions="Start"
            BackgroundColor="red"
            Clicked="Button_OnClicked"
            HeightRequest="100"
            Text="View 4"
            WidthRequest="100" />
<Grid BackgroundColor="#66000000" />
```
I would expect that Grid control overlays Button therefore events (e.g. Button click) are not triggered on underlying control. This is not the case in the latest RC3 version. I tested similar scenario in XF 5 and it works as expected (button click event is not triggered). I also tried all sorts of scenarios with InputTransparent property on controls, with no success.

![image](https://user-images.githubusercontent.com/10289398/169314232-deb2fe86-760b-4c91-9d50-aa362180e458.png)

        

### Steps to Reproduce

1) Create new MAUI app
2) Add simple ContentPage with:

` <Button VerticalOptions="Start"
            BackgroundColor="red"
            Clicked="Button_OnClicked"
            HeightRequest="100"
            Text="View 4"
            WidthRequest="100" />
        <Grid BackgroundColor="#66000000" />`
        
and click eventhandler on Page Cs code, e.g.:

 private async void Button_OnClicked(object sender, EventArgs e)
    {
		await DisplayAlert("Message", "Button click event", "OK");
    }  
    
Because Grid overlays (hides) Button control click event should not trigger.

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 12, API 31, emulator

**Comment by VincentBu** [comment] 2022-05-20 01:33
repro with vs main build(32519.297.main)

**Comment by mattleibow** [comment] 2023-03-28 18:20
Duplicate of #10252

**Comment by mattleibow** [comment] 2023-03-28 18:20
May be fixed in https://github.com/dotnet/maui/pull/13725

**Closed by mattleibow** 2023-03-28 18:20 UTC
Labels: t/bug, area/controls 🎮, s/verified
