### ISSUE TITLE
[Windows]Repeated navigation page crash

### ISSUE THREAD

**Issue by BaY1251** [dotnet/maui#18441] opened 2023-10-31 02:05 UTC
### Description

When there are many page elements, repeatedly navigating the interface can cause a crash

NO exception, Just crash

![ANR_WINDOWS](https://github.com/dotnet/maui/assets/48309205/25a66bd0-86b2-4456-ad5a-91b7654fcf94)

First report on #18331,Android platform.   To prevent misunderstandings, create a new issue for the Windows platform

### Steps to Reproduce

下载 https://github.com/BaY1251/MauiDebug.git
打开 /ANR/ANR.sln 编译生成工程,并运行.
点击 Shell, 反复切换Home和Sec界面,约10次后,问题复现

#translate

Download https://github.com/BaY1251/MauiDebug.git
Open /ANR/ANR.sln to compile and generate a project
Running

Click on Shell and repeatedly switch between the Home and Sec interfaces. After about 10 times, the problem reappear

### Link to public reproduction project repository

https://github.com/BaY1251/MauiDebug.git

### Version with bug

8.0.0-rc.2.9373

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows10-22H2   net8.0-windows10.0.19041.0

**Comment by drasticactions** [comment] 2023-10-31 03:12
I don't think your issue has to do with Navigation. Your App UI (A CollectionView with bindable layouts embedded) is quite intense and, on my machine, uses around 700 MBs just opening it and fully screening it on the main page alone. Scrolling down will cause the same WinUI exception you're seeing by navigation. You're also navigating to the same page instance, but removing and adding your item source. So you're not navigating to anything; it's the same page.

Looking at the debugger tooling (and turning off XAML Hot Reload) and scrolling through the list, it seems that Setter Specificity continually adds items to its list and doesn't remove them. For example, changing your app UI to

```xml
<CollectionView SelectionMode="Single"
				ItemsSource="{Binding ItemList}">
	<CollectionView.ItemTemplate>
		<DataTemplate x:DataType="local:Item">
			<Grid RowSpacing="0"
				  RowDefinitions="Auto,1"
				  ColumnDefinitions="120,*,120,64">
                <Label Text="{Binding Name}"
					   FontSize="24"
					   WidthRequest="120"
					   VerticalOptions="Center"
					   HorizontalTextAlignment="Center" />
            </Grid>
		</DataTemplate>
	</CollectionView.ItemTemplate>
</CollectionView>
```

and scrolling through the list,

<img width="770" alt="image" src="https://github.com/dotnet/maui/assets/898335/2d1be574-8c4d-48f9-8079-b78031897071">

The count and memory size seems to, generally, increase all the time. It could be that your app UI as designed, on top of possible memory issues with things like setter specificity, could be causing the problem.

CC @jonathanpeppers @StephaneDelcroix

**Comment by BaY1251** [comment] 2023-10-31 07:24
@drasticactions 3Q ,yes!, Repeated Invoke Clear and Add can also cause crash

**Comment by XamlTest** [comment] 2023-11-09 10:41
Verified this on Visual Studio Enterprise 17.8.0 Preview 7.0(8.0.0-rc.2.9530). Repro on Windows 11 with below Project:
[ANR.zip](https://github.com/dotnet/maui/files/13307044/ANR.zip)

**Comment by PureWeen** [comment] 2024-11-18 19:13
Duplicate of #22790

**Closed by PureWeen** 2024-11-18 19:13 UTC
Labels: t/bug, platform/windows 🪟, area-navigation, area-controls-collectionview, s/verified, s/triaged
