### ISSUE TITLE
MAUI Blob RollBacks no longer publicly accessible

### ISSUE THREAD

**Issue by ESO-ST** [dotnet/maui#24909] opened 2024-09-24 18:35 UTC
### Description

We are using https://maui.blob.core.windows.net/metadata/rollbacks/8.0.40.json in our azure pipeline as a workaround for an issue, today the link is no longer publicly accessible.

### Version with bug

9.0.0-rc.1.24453.9

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

**Comment by ESO-ST** [comment] 2024-09-24 18:41
@rmarinho just saw that there's a comment that you left on this ticket https://github.com/dotnet/maui/issues/12772
so if we were using `dotnet workload install maui --from-rollback-file https://maui.blob.core.windows.net/metadata/rollbacks/8.0.40.json` how would we do so now?

**Comment by OwenFromAI** [comment] 2024-09-24 19:09
Yeah, I'm confused.

It seems like if I'm using SDK 8.0.400 I should be able to:

> dotnet workload install maui --version 8.0.60

To do what I was doing with rollback files. But when I do this on DevOps I get:

> Workload installation failed: Failed to install workload version 8.0.61: Version 8.61.0 of package microsoft.net.workloads.8.0.0 is not found in NuGet feeds https://api.nuget.org/v3/index.json".

Is there a documented list of versions? Or am I using the command incorrectly?

**Comment by jfversluis** [comment] 2024-09-24 19:28
Duplicate of #24892

**Closed by jfversluis** 2024-09-24 19:28 UTC
Labels: t/bug
