### ISSUE TITLE
ContentView inside Carouselview results in error

### ISSUE THREAD

**Issue by LeiWuLong** [dotnet/maui#10963] opened 2022-10-27 16:49 UTC
### Description

Hi, I have been encountering errors setting up a contentview inside a carouselview in the most basic way, but ends up as below. I would assume this is a bug since there isn't anything else going on in the page besides the code snippet below. 

I did not bother to attach a sample project since this can very much be easily replicated. Please see repro steps

```xaml
<CarouselView>
    <CarouselView.ItemsSource>
        <x:Array Type="{x:Type ContentView}">
            <ContentView>
                <StackLayout BackgroundColor="Blue" />
            </ContentView>
            <ContentView>
                <StackLayout BackgroundColor="Red" />
            </ContentView>
        </x:Array>
    </CarouselView.ItemsSource>
    </CarouselView>
```

![image](https://user-images.githubusercontent.com/6078908/198349454-54c39a34-20a3-48c4-b124-30b3360629f9.png)

![image](https://user-images.githubusercontent.com/6078908/198348959-a614003b-efde-47f9-9ae6-07796aaa8822.png)
 

### Steps to Reproduce

1. Create a maui app.
2. Paste the code snippet in the description. Your code should look like the screenshot provided.

### Link to public reproduction project repository

none

### Version with bug

6.0 Release Candidate 3

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android  > 21

**Comment by PureWeen** [comment] 2022-10-27 18:34
Duplicate of #7884

**Closed by PureWeen** 2022-10-27 18:34 UTC
Labels: t/bug, area/collectionview 📃
