### ISSUE TITLE
RadioButtonGroup view not initializing properly when multiple groups exist in a single page

### ISSUE THREAD

**Issue by stevepeeters** [dotnet/maui#11117] opened 2022-11-05 11:53 UTC
### Description

When a page containing multiple data bound radiobutton groups is initialized, the checked state of only the last group is shown correctly.

![image](https://user-images.githubusercontent.com/96940763/200118404-535c80be-311d-4c75-bb34-a47e207bab2a.png)

The data bindind itself works as expected, only problem seems to be the IsChecked state upon initialization.

### Steps to Reproduce

1. start up application
2. first radiobutton group is databound correctly, but IsChecked for the 'True' radiobutton is incorrect (ViewModel starts off at 'true')

### Link to public reproduction project repository

https://github.com/stevepeeters/RadioButtonGroupBug

### Version with bug

7.0 Release Candidate 2

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Windows 10 and 11

**Comment by softlion** [comment] 2022-11-06 07:47
The return :) It's a bug I reported 9 months ago and was "fixed" 3 times already.

**Comment by samhouts** [comment] 2023-03-02 23:34
Duplicate of #11418

**Closed by samhouts** 2023-03-02 23:34 UTC
Labels: t/bug, platform/windows 🪟, area/controls 🎮, control-radiobutton
