### ISSUE TITLE
Externally hosted images cannot load on native apps

### ISSUE THREAD

**Issue by codeaphex** [dotnet/maui#6067] opened 2022-04-13 14:33 UTC
### Description

Loading an hosted image into an image control doesn't work after upgrading to RC1.
I thought it would be the same as #5986, but I'm using native maui controls, no webview and getting an other error message.

### Steps to Reproduce

1. Create a new MAUI app.
2. Add ```<uses-permission android:name="android.permission.INTERNET" />``` to the android manifest.
3. Change the source of the existing image control to: ```https://devblogs.microsoft.com/dotnet/wp-content/uploads/sites/10/2020/10/dotnet-bot_handybot.png```
4. Image does not show up on android, neither in the emulator, nor directly in an deployed app. Couldn't find an error message either.
5. If I load the image from code-behind ```		img.Source = ImageSource.FromUri(new Uri("https://devblogs.microsoft.com/dotnet/wp-content/uploads/sites/10/2020/10/dotnet-bot_handybot.png"));
```, it breaks with an error message: ```**System.InvalidOperationException:** 'An attempt was made to transition a task to a final state when it had already completed.'```

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Preview 14

### Affected platforms

Android

### Affected platform versions

Android 11+

### Relevant log output

```shell
at System.Threading.Tasks.TaskCompletionSource`1[[Microsoft.Maui.IImageSourceServiceResult, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].SetResult(IImageSourceServiceResult result)
   at Microsoft.Maui.ImageLoaderCallback.OnComplete(Boolean success, Drawable drawable, IRunnable dispose) in D:\a\_work\1\s\src\Core\src\ImageSources\Android\ImageLoaderCallback.cs:line 88
   at Microsoft.Maui.IImageLoaderCallbackInvoker.n_OnComplete_Ljava_lang_Boolean_Landroid_graphics_drawable_Drawable_Ljava_lang_Runnable_(IntPtr jnienv, IntPtr native__this, IntPtr native_p0, IntPtr native_p1, IntPtr native_p2) in D:\a\_work\1\s\src\Core\src\obj\Release\net6.0-android\generated\src\Microsoft.Maui.IImageLoaderCallback.cs:line 87
   at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPLLL_V(_JniMarshal_PPLLL_V callback, IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, IntPtr p2) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:line 297
```

**Comment by emorell96** [comment] 2022-04-13 15:16
I am experiencing this same issue. The collection view with internet images loads but after a while I get the exception above.

**Comment by user1311** [comment] 2022-04-13 20:32
I have the same issue with image displaying in CollectionView, going through workshop [Displaying Data Maui workshop](https://github.com/dotnet-presentations/dotnet-maui-workshop/tree/main/Part%201%20-%20Displaying%20Dat).

**Comment by limefrogyank** [comment] 2022-04-14 00:00
I'm trying to load locally cached images (created from a pdf) and nothing will show up.  No error messages, either.  This was working fine in Preview 14 and now fails in RC1.  I have emailed the generated images to myself to make sure I was creating them properly (using `EmailMessage` and `EmailMessage`) and they look great.  

Something is wrong with the Android `Image` control.

**Comment by codeaphex** [comment] 2022-04-14 00:05
@limefrogyank Local images should work, be sure to reference them like it is shown in the [docs ](https://docs.microsoft.com/en-us/dotnet/maui/user-interface/controls/image), e.x. put them into the images folder and reference them with just the filename.

**Comment by limefrogyank** [comment] 2022-04-14 02:36
@codeaphex I'll have to start a new issue then because I can't get anything to show.  Using `ImageSource.FromStream` and `ImageSource.FromFile` won't work for me.

**Comment by kristinx0211** [comment] 2022-04-14 06:41
Got the same problem with a native android app. demo: [MauiApp9.zip](https://github.com/dotnet/maui/files/8486844/MauiApp9.zip)
on windows it is ok:
![image](https://user-images.githubusercontent.com/99457000/163328228-fb937b6e-a212-4ec0-bc08-13d8e22a70b6.png)
Android 11:
![image](https://user-images.githubusercontent.com/99457000/163328356-083cf407-a862-4a38-9c4d-18a9cfe56b0b.png)

**Comment by kristinx0211** [comment] 2022-04-14 06:41
Duplicate of #5986

**Comment by jfversluis** [comment] 2022-04-14 08:10
Not 100% sure if the linked issue is the exact same issue. Might be related, but let's track them both for now. Good spot though @kristinx0211!

**Comment by davefxy** [comment] 2022-04-15 13:12
I have an app which downloads the image, stores it locally and then displays the image. That app stopped working with RC1. Maybe it has something to do with PNG images being loaded at runtime.

**Comment by Xoben** [comment] 2022-04-15 18:23
In Android I get the following error message

` Load failed for https://aka.ms/campus.jpg with size [999x619]
[Glide] class com.bumptech.glide.load.engine.GlideException: Failed to load resource
[Glide] There was 1 root cause:
[Glide] com.bumptech.glide.load.HttpException(Failed to connect or obtain data, status code: -1)
[Glide]  call GlideException#logRootCauses(String) for more detail
[Glide]   Cause (1 of 2): class com.bumptech.glide.load.engine.GlideException: Fetching data failed, class java.io.InputStream, REMOTE
[Glide] There was 1 root cause:
[Glide] com.bumptech.glide.load.HttpException(Failed to connect or obtain data, status code: -1)
[Glide]  call GlideException#logRootCauses(String) for more detail
[Glide]     Cause (1 of 1): class com.bumptech.glide.load.HttpException: Failed to connect or obtain data, status code: -1
[Glide]   Cause (2 of 2): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{StringUri->Object->Drawable}, LOCAL
[Glide]     Cause (1 of 2): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{StringUri->Drawable->Drawable}
[Glide]     Cause (2 of 2): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{StringUri->Bitmap->Drawable}
[Glide] Root cause (1 of 1)`

**Comment by dharber** [comment] 2022-04-20 19:10
Is there any progress on fixing this or any kind of workaround? This bug basically renders MAUI completely useless to me, and I would guess others who primarily need Android functionality. It's especially irksome since images actually worked fine in the previous preview so somebody went out of their way to break it apparently without bothering to test it.

If I'm going to have to wait weeks for another release candidate to fix this, I'll probably have to bail and reimplement the app in Flutter.

**Comment by emorell96** [comment] 2022-04-20 19:19
> Is there any progress on fixing this or any kind of workaround? This bug basically renders MAUI completely useless to me, and I would guess others who primarily need Android functionality. It's especially irksome since images actually worked fine in the previous preview so somebody went out of their way to break it apparently without bothering to test it.
> 
> If I'm going to have to wait weeks for another release candidate to fix this, I'll probably have to bail and reimplement the app in Flutter.

That's my case where it's unusable because of this issue, but I was able to downgrade to version 14 while they fix it. I wrote how in here: https://github.com/dotnet/maui/discussions/6059#discussioncomment-2562617 in case it would help someone.

**Comment by jfversluis** [comment] 2022-04-21 10:16
@dharber since GA will be within a month you shouldn't have to wait weeks before there is a new RC. Like you say; this is core functionality, we're definitely aware and working on resolving it asap. Unfortunately, there are no known workarounds at this time.

**Comment by emorell96** [comment] 2022-04-21 10:18
@jfversluis is there an ETA on RC3 (the milestone this was assigned to)? Thank you!

**Comment by jfversluis** [comment] 2022-04-21 10:18
If there was something I could say about it right now I would've shared :)

**Comment by dharber** [comment] 2022-04-21 16:58
> @dharber since GA will be within a month you shouldn't have to wait weeks before there is a new RC. Like you say; this is core functionality, we're definitely aware and working on resolving it asap. Unfortunately, there are no known workarounds at this time.

It seems unlikely to me that MAUI will be GA-ready in a month. I don't doubt that it will be released as GA but given the number of issues I'm running into for just basic stuff, I'm not super confident it will be something I can use right away.

Thank you for the update, though.

**Comment by Redth** [comment] 2022-04-22 20:25
Works in main now - fixed by #6394
![Screenshot_1650659119](https://user-images.githubusercontent.com/271950/164788792-a96610d5-3910-45fe-b003-4db797eb2188.png)

**Closed by Redth** 2022-04-22 20:25 UTC
Labels: t/bug, area/image :framed_picture:, s/verified, s/triaged, delighter

**Comment by dharber** [comment] 2022-04-23 23:40
So this does sort of work now but not really. Images do come up but if I update the image source with new ImageSources, it alternates between blanking out the image and displaying one. Also, the images seem to be loading over the network much slower than they were in preview 14.

I guess since this issue is closed I need to file a new one?

**Comment by jamesmontemagno** [comment] 2022-04-26 23:10
@Redth was this fix in RC2? I don't see stuff working in the workshop on ANdroid... https://github.com/dotnet-presentations/dotnet-maui-workshop

**Comment by Redth** [comment] 2022-04-26 23:36
I don’t believe it would have made rc2.

**Comment by KarlSearl** [comment] 2022-04-28 09:20
I am still having issues loading image from URI

**Comment by KarlSearl** [comment] 2022-04-28 09:38
> @Redth was this fix in RC2? I don't see stuff working in the workshop on ANdroid... https://github.com/dotnet-presentations/dotnet-maui-workshop

Ive downloaded the workshop project. Images are not showing .
![image](https://user-images.githubusercontent.com/64684177/165724388-6b12594d-e1ae-48ca-b1d3-0e06d2d3a91f.png)

**Comment by jfversluis** [comment] 2022-04-28 13:49
@KarlSearl as mentioned: this didn't make it for RC2, it should be fixed with RC3

**Comment by icarrenomercado** [comment] 2022-05-08 10:09
Hey,

In case it helps , here is a somewhat ugly workaround until the fix is released:

` ImageHandler.Mapper.AppendToMapping(nameof(ImageView.Drawable), async (handler, view) =>
            {
                if (view.Source is UriImageSource uriImageSource)
                    try
                    {
                        byte[] imageData;
                        using (var response = await _httpClient.GetAsync(uriImageSource.Uri))
                        {
                            imageData = await response.Content.ReadAsByteArrayAsync();
                        }
                        handler.PlatformView.SetImageDrawable(new BitmapDrawable(BitmapFactory.DecodeByteArray(imageData, 0, imageData.Length)));
                    }
                    catch
                    {
                    }
                ;
            });`
