### ISSUE TITLE
TapGestureRecognizer not working on iOS from maui 8.0.80 and onward

### ISSUE THREAD

**Issue by gksharps** [dotnet/maui#25237] opened 2024-10-14 08:50 UTC
### Description

The tapgesturerecognizer stopped working on ios after building with Maui 8.0.80 and higher. 8.0.71 and lower still fine. I am able to do a workaround but we also see other issues with imagebutton and layouts. Android still works fine. Have not been able to try the Maui 9 RC. The native button still seems to respond when pressed however the associated command is not fired

```
<ImageButton
           Source="icon.png"
           Aspect="Center"
           BorderWidth="0">
   <ImageButton.GestureRecognizers>
        <TapGestureRecognizer Command="{Binding TapCommand}" />
    </ImageButton.GestureRecognizers>
 </ImageButton>
```

### Version with bug

8.0.80 SR8

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.71 SR7.1

### Affected platforms

iOS

### Affected platform versions

IOS 17.x and others

**Comment by gksharps** [comment] 2024-10-14 08:57
I do have workarounds and I don't know why the person chose a tapgesturerecognizer instead of binding to the imagebutton command since it has been implemented before my time. But something did break and now the behavior is inconsistent between ios/android

**Comment by alpayclsr1** [comment] 2024-10-14 08:59
I would like to confirm that we are experiencing the same issue with the TapGestureRecognizer not functioning on ImageButton after upgrading to .NET MAUI version 8.0.80 and higher.

As a workaround, you can use the Image control instead of the ImageButton. This allows for the desired tap functionality while avoiding the current limitations with ImageButton.

**Comment by gksharps** [comment] 2024-10-14 09:08
Binding directly to the command of the Imagebutton is also broken.

**Comment by ninachen03** [comment] 2024-10-15 08:40
This issue has been verified using Visual Studio 17.12.0 Preview 2.1(8.0.91 & 8.0.71). Can repro this issue on 8.0.91 and works fine on 8.0.71.

**Comment by PureWeen** [comment] 2024-10-21 17:02
Duplicate of #19099

I realize that one is about button but it's the same reason as was described here
https://github.com/dotnet/maui/issues/19099#issuecomment-1858831784

**Closed by PureWeen** 2024-10-21 17:02 UTC
Labels: t/bug, platform/iOS 🍎, s/verified, s/triaged, i/regression, area-gestures
