### ISSUE TITLE
Stop ignoring naming issue and just fucking rename already

### ISSUE THREAD

**Issue by AlexKurisu** [dotnet/maui#1770] opened 2021-07-22 20:44 UTC
Stop ignoring naming issue between your MAUI and MauiKit and fucking rename already

**Comment by hartez** [comment] 2021-08-03 17:51
Duplicate of #35.

**Closed by hartez** 2021-08-03 17:51 UTC
Labels: s/duplicate 2️⃣

**Comment by davidbuckleyni** [comment] 2021-08-03 21:31
Do not curse in this repo they will ban u !
