### ISSUE TITLE
MAUI runtime way slower than Xamarin.Forms 

### ISSUE THREAD

**Issue by danardelean** [dotnet/maui#11479] opened 2022-11-18 16:18 UTC
### Description

Why porting FractlExplorer sample (Xamarin University) to MAUI I realised that running the same code (that generates the pixels for a Mandelbrot fractal) runs way slower in the MAUI Project than in the Xamarin.Forms Project. Sometimes it is actually 10 times slower and it doesn't really makes because the part that runs slower is the computational part not the UI. Can it be that the  .Net iOS and .Net Android runtimes are slower than Xamarin.iOS and Xamarin.Android? I've tested the code with the same results on:

Tested on:
iPhone 14 Pro Max Emulator
iPhone 14 Pro -device
Android API32 arm64 v8a Emulator

I develop in Visual Studio for Mac (not Preview) on a Mac Studio

### Steps to Reproduce

Run the two projects
See the performance differences

Here are the results in Debug on an iPhone 14 Pro device. The lower value (faster) is Xamarin.Forms

<img src="https://user-images.githubusercontent.com/1352599/202748997-d3997ac8-92ca-49d5-b8eb-ddc65352da73.PNG" width=50% height=50%>

<img src="https://user-images.githubusercontent.com/1352599/202749027-b791e217-3208-499c-9b4b-94d2b9d4b81b.PNG" width=50% height=50%>

### Link to public reproduction project repository

https://github.com/danardelean/XFvsMAUI

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

iOS 16, Android API 32

**Comment by NonameMissingNo** [comment] 2022-11-18 17:37
Hey there! Test it on Release.

**Comment by danardelean** [comment] 2022-11-19 14:13
Hey there It has the same issue 4 sec on Xamarin.Forms 56 seconds on MAUI

**Comment by jsuarezruiz** [comment] 2022-11-21 15:28
cc @jonathanpeppers

**Comment by danardelean** [comment] 2022-11-29 11:40
@jonathanpeppers I would really love to understand the problem. From outside it would seem a problem with the runtime as it slower on both iOS and Android

**Comment by jonathanpeppers** [comment] 2022-11-29 14:29
@jsuarezruiz can someone on the MAUI team profile this, and let me know what you find?

Make it sure it `Release` mode, this comment is basically comparing interpreter vs non-interpreter:

> Here are the results in Debug on an iPhone 14 Pro device. The lower value (faster) is Xamarin.Forms

**Comment by kcrg** [comment] 2022-12-05 17:57
@danardelean @jonathanpeppers I was able to achieve result below 0.5s in MAUI app simply by enabling AOT and LLVM. To be fair I also turned on AOT on Xamarin.Forms version of this app and results seems to be stuck between 4.2s and 4.5s. I wasn't able to run Xamarin.Forms app with both AOT and LLVM because of startup crash, I think LLVM is broken in Xamarin, so single AOT must do.
| MAUI (AOT+LLVM)  | Xamarin.Forms (AOT) |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/7996711/205704936-f8446c9e-51a7-4d23-9335-30d559ed1b22.png)  | ![image](https://user-images.githubusercontent.com/7996711/205705239-b620ad76-0536-492e-b1b1-2675a68d8940.png)  |


There is also huge win in app size for MAUI
| MAUI (AOT+LLVM)  | Xamarin.Forms (AOT) |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/7996711/205708163-5ea7cca8-ac71-4c60-a441-532b36661c21.png) | ![image](https://user-images.githubusercontent.com/7996711/205708090-50294186-2f56-4c10-8cb5-f93c1e7620d7.png) |

Before every build and deploy solution was cleaned and old package was uninstalled from emulator.

**Comment by jonathanpeppers** [comment] 2022-12-05 18:47
@kcrg thank you for the investigation!

@danardelean can you confirm if you see the same? `$(EnableLLVM)` is not the default, to be sure you're comparing the same settings on both Xamarin & .NET 6+, I would do:

```xml
<!-- Only test release -->
<PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
  <AotAssemblies>true</AotAssemblies>
  <RunAOTCompilation>true</RunAOTCompilation>
  <!-- Optional -->
  <!--<EnableLLVM>true</EnableLLVM>-->
</PropertyGroup>
```

These should make sure you're using the same configuration in Xamarin & .NET.

**Comment by kcrg** [comment] 2022-12-05 18:55
@jonathanpeppers I didn't expect that fast response from you. I added some more information to previous comment.

**Comment by danardelean** [comment] 2022-12-06 08:33
> @danardelean I was able to achieve result below 0.5s in MAUI app simply by enabling AOT and LLVM. To be fair I also turned on AOT on Xamarin.Forms version of this app and results seems to be stuck between 4.2s and 4.5s. I wasn't able to run Xamarin.Forms app with both AOT and LLVM because of startup crash, I think LLVM is broken in Xamarin, so single AOT must do.
> 
> | MAUI (release AOT+LLVM)  | Xamarin.Forms (release AOT) |
> 
> | ------------- | ------------- |
> 
> | ![image](https://user-images.githubusercontent.com/7996711/205704936-f8446c9e-51a7-4d23-9335-30d559ed1b22.png)  | ![image](https://user-images.githubusercontent.com/7996711/205705239-b620ad76-0536-492e-b1b1-2675a68d8940.png)  |
> 
> MAUI app with only AOT is the same or little bit faster than XF, I was able to achive <4s.
> 
> 
> 
> There is also huge win in app size for MAUI
> 
> | MAUI (AOT+LLVM)  | Xamarin.Forms (AOT) |
> 
> | ------------- | ------------- |
> 
> | ![image](https://user-images.githubusercontent.com/7996711/205719167-891f0371-db6e-4e9d-bfde-ca0af9555ffb.png) | ![image](https://user-images.githubusercontent.com/7996711/205708090-50294186-2f56-4c10-8cb5-f93c1e7620d7.png) |
> 
> Broken XF app with AOT and LLVM was 90,71MB in size
> 
> 
> 
> There IS issue tho, in debug MAUI is way slower than Xamarin.Forms. 
> 
> | MAUI (debug)  | Xamarin.Forms (debug) |
> 
> | ------------- | ------------- |
> 
> | ![image](https://user-images.githubusercontent.com/7996711/205711572-2be1ef60-9f22-418e-8496-040f21914477.png) | ![image](https://user-images.githubusercontent.com/7996711/205714580-a695f609-a458-4877-bc76-d2021e1dd8b3.png) |
> 
> Both in built in debug mode but without debugger attached.
> 
> 
> 
> Yes, Xamarin.Forms in debug mode, without debugger attached is FASTER than the same app but in release mode with AOT enabled. I don't know why. Maybe @jonathanpeppers knows? I'm very curious, it is mindblowing for me. 🤯
> 
> I've always believed that AOT always increases performance at the expense of application size.
> 
> 
> 
> Xamarin.Forms app in release mode without AOT seems to be the same as debug without debugger attached
> 
> 
> 
> Before every build and deploy, solution was cleaned and old package was uninstalled from emulator.

Have you also tried iOS? I see the same problem in release on iOS

**Comment by danardelean** [comment] 2022-12-06 08:50
> @kcrg thank you for the investigation!
> 
> @danardelean can you confirm if you see the same? `$(EnableLLVM)` is not the default, to be sure you're comparing the same settings on both Xamarin & .NET 6+, I would do:
> 
> ```
> 
> <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
>   <AotAssemblies>true</AotAssemblies>
>   <RunAOTCompilation>true</RunAOTCompilation>
>   
>   
> </PropertyGroup>
> ```
> 
> These should make sure you're using the same configuration in Xamarin & .NET.

I will do the test and let you know Does it  make sense to ignore the fact that both iOS and Android in Releases with default settings are way slower on when running on net7-iOS and net7-android than when running on Mono? The computation of the fractal (the mathematical part) is what seems to be way faster on mono

**Comment by jonathanpeppers** [comment] 2022-12-06 13:58
I think @kcrg is saying .NET 7 was faster. Did I misunderstand?

You would certainly see some difference in a Debug build, because Xamarin didn't have an interpreter -- and you have one in .NET 7 to support hot reload.

**Comment by kcrg** [comment] 2022-12-06 17:54
@jonathanpeppers Yes, .NET 7 is faster than Xamarin.Forms in release mode. 
Btw, is there a way to disable interpreter? I can imagine an app large enough, that the interpreter will slow it down enough that debugging can become irritating.

@danardelean Here my results for iOS, both on default release modes:
| MAUI | Xamarin.Forms |
| ------------- | ------------- |
| <img width="477" alt="Screenshot 2022-12-06 at 18 37 16" src="https://user-images.githubusercontent.com/7996711/205983020-1417e1ab-5365-4f9f-8bd2-8cfc75578981.png"> | <img width="477" alt="Screenshot 2022-12-06 at 18 37 07" src="https://user-images.githubusercontent.com/7996711/205983077-d772887b-e3aa-4197-90af-579cab35a0c0.png"> |

NOTE: Don't compare the previous results from Android with those from iOS, because apps were run on very different machines.

**Comment by jonathanpeppers** [comment] 2022-12-06 18:14
You should be able to put `UseInterpreter=false` in your project file, to turn it off for Debug builds. It will break C# hot reload, though.

For iOS I would also test on a device, as the simulator can be a bit different.

**Comment by LennoxP90** [comment] 2022-12-14 01:34
I tried using AOT compiling and unfortunately the app refuses to start

**Comment by LukasKuchta** [comment] 2023-01-30 07:53
Hi, same problem here https://github.com/dotnet/maui/discussions/12743 when we using db engine.

**Comment by hofipetr** [comment] 2023-01-30 09:01
> 

I had that issue too - took me 4 days to find source of the crash. Some libraries has issues running in AOT, especially libraries using reflection. In my case it was caused by Newtonsoft.Json and LiteDB.

Unfortunately, debugging a release AOT build is complicated. If your app runs normally without AOT, check your code in startup classes - something may throw an exception there, crashing the app on launch. Finally I wrapped all my startup code in try/catch blocks and it revealed this exception: "System.ExecutionEngineException: Attempting to JIT compile method '<method definition>' while running in aot-only mode."

**Comment by Hottemax** [comment] 2023-06-01 09:23
We see exactly the same problem as @LukasKuchta  has reported in #12743 in our own commercial app, which uses [sqlite-net](https://github.com/praeclarum/sqlite-net) for on-device data persistence.

Actually, the magnitude of the slowdown  is exactly the same [as reported](https://github.com/LukasKuchta/XamarinMauiDbTest/wiki), too - about a factor of 4(!!) slower in MAUI vs XAMARIN.

Not sure whether this should be _extracted into a new issue_, as "MAUI runtime way slower" is maybe a too-general description of the issue, and the original post refers to UI rendering performance specifically, which is quite far removed from db operation performance.

On the other hand, I do not want to drown the MAUI team in more duplicate issues.

What do you guys think?

Or if the MAUI team is aware of the performance issues, it would be nice if there would be an acknowledgement that this is being worked on or at least on the radar.

The raw amount of slowdown (400%!) is what is the real pressing issue for us, it renders our app borderline unusable.

**Comment by jonathanpeppers** [comment] 2023-06-01 13:55
@Hottemax are the APIs in https://github.com/dotnet/maui/discussions/12743 even .NET MAUI APIs? It seems like they are writing to a database, which is completely unrelated to MAUI at all?

It seems like you need to find which methods are actually slower than before -- because it may be an issue to file at the dotnet/runtime repo for the Mono team to investigate.

You should get a `.speedscope` file of your app (in Release mode), instructions at: https://aka.ms/profile-maui

**Comment by jonathanpeppers** [comment] 2023-06-01 14:19
@Hottemax those are the docs we have right now. You would use `dotnet-trace` and `dotnet-dsrouter` together for profiling on iOS and Android. You can either get a `.nettrace` (to open in VS or PerfView) or `.speedscope` file -- I think https://speedscope.app is generally easier to use, so I'd recommend that.

**Comment by Hottemax** [comment] 2023-06-01 14:33
@jonathanpeppers One last follow up then I will stop pestering you:

We basically have the same app, and in lots of collection-view type pages we have the idiom in the pages code-behind:

`protected override async void OnAppearing() => await _viewmodel.Initialize();`,

and in the body of `Initialize()` we would Query the SQLite db via a injected service utilizing the sqlite API.

With the switch to Xamarin, we noticed "hickups" of like 1 up to a couple of seconds between navigating to the page, and the appearance of data. (the aforementioned 400% increase in time) - which makes our app feel really slow/stuttering.

 Just a couple of lines, maybe there is a "duh, that's what you are doing wrong" moment here that you can point out. Doesn't hurt to ask ^^

**Comment by jonathanpeppers** [comment] 2023-06-01 15:39
I don't know the design/details of MAUI APIs like `OnAppearing()`. Maybe @PureWeen  or @mattleibow  can comment?

**Comment by homeyf** [comment] 2023-07-11 06:20
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 2.0. Can repro on Android platform with sample project.
https://github.com/danardelean/XFvsMAUI
![image](https://github.com/dotnet/maui/assets/82450723/169692e5-9e61-4337-be90-1720dac47090)

**Comment by danardelean** [comment] 2023-10-05 13:47
Any news on this item?

**Comment by jonathanpeppers** [comment] 2023-10-09 16:44
@kcrg was seeing faster performance in .NET 7 than Xamarin.Forms in `Release` mode: https://github.com/dotnet/maui/issues/11479#issuecomment-1339755850

Is there still an issue here? Reading the comments above, some were comparing the interpreter vs JIT. This sample is pretty much always going to perform slower with interpreter.

**Comment by danardelean** [comment] 2023-10-10 17:14
@jonathanpeppers maybe not related to this issue but a client of mine is migrating an Xamarin.Forms solution to .NET Maui and the same CollectionView on NET8.0 MAUI is not usable. I had a look at the project and it is the same template in XF and .NET MAUI. It scatters so bad that it is unusable. 
I am seeing other projects that have similar issue: X.F. ColelctionView is OK .NET MAUI you cannot use it. This especially on Android. Do you have any idea how to address this?
Is the CollectionView in Android written from ground-up to use Handlers architecture or using the compatibility layer?

Thanks

**Comment by jonathanpeppers** [comment] 2023-10-10 17:15
Can you file a new issue? This seems off-topic to "MAUI runtime way slower than Xamarin.Forms".

**Comment by AnthonyWeirbach** [comment] 2023-10-15 02:24
> @jonathanpeppers maybe not related to this issue but a client of mine is migrating an Xamarin.Forms solution to .NET Maui and the same CollectionView on NET8.0 MAUI is not usable. I had a look at the project and it is the same template in XF and .NET MAUI. It scatters so bad that it is unusable. I am seeing other projects that have similar issue: X.F. ColelctionView is OK .NET MAUI you cannot use it. This especially on Android. Do you have any idea how to address this? Is the CollectionView in Android written from ground-up to use Handlers architecture or using the compatibility layer?
> 
> Thanks

@danardelean did you create a new issue or find a solution for this? I too have an Android app that works perfect in Xamarin but once I converted it to Maui it is super slow and not useable. This is occurring with a CollectionView, I also tried changing it to a list view and got the same results. And I have tried NET6.0 NET7.0 and NET8.0 prerelease.

Thank you,
       Anthony

**Comment by jonathanpeppers** [comment] 2023-10-15 02:29
@AnthonyWeirbach are you testing `Release` builds? It sounds like you either need to do that or disable `UseIntepreter`.

**Comment by AnthonyWeirbach** [comment] 2023-10-15 13:33
> @AnthonyWeirbach are you testing `Release` builds? It sounds like you either need to do that or disable `UseInterpreter`.

I just tried it in Release and it is better but still not great. In Xamarin when the View displays it is seamless. When I open the same View in Maui Release mode it stutters for about 1-3 seconds and then displays. I mean I could deal with it and just ad a loading indicator or something but was hoping to figure out a fix for it so it worked as it did in Xamarin.

Also, I tried to add `<UseInterpreter>false</UseInterpreter>` to my project file for debug and it did not change anything. Was this how you were suggesting to use UseInterpreter?

**Comment by jonathanpeppers** [comment] 2023-10-16 15:35
@AnthonyWeirbach can you file a new issue? This issue is about a Mandelbrot Fractal generator, and the issue with your app is probably related to navigation or a different control? I doubt you are generating fractals.

As for this issue, I think we can close it due to the comment: https://github.com/dotnet/maui/issues/11479#issuecomment-1339755850

The original sample was comparing Debug Xamarin vs Debug .NET 7 with intepreter enabled. I'd recommend just testing Release mode for performance investigations, generally. Thanks!

**Closed by jonathanpeppers** 2023-10-16 15:35 UTC
Labels: t/bug, platform/android 🤖, platform/iOS 🍎, area/perf 🏎️, s/verified, s/triaged, s/needs-attention
