### ISSUE TITLE
Android app icon not displaying

### ISSUE THREAD

**Issue by hbraasch** [dotnet/maui#7017] opened 2022-05-11 08:08 UTC
### Description

After following the simple procedure to add one's own application icon, it does not appear under Android. It does appear under iOS.

![image](https://user-images.githubusercontent.com/7484186/167800023-64f55818-7a29-4708-bade-45d0fcc6810e.png)

I've provided a link to a simple reproduction project here:

https://github.com/hbraasch/AppIconTester.git

### Steps to Reproduce

1. Run the reproduction app sourced from GitHub
2. Observe the icon appears under iOS, not Android

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

All Androids, tried on API 29/30/31

### Did you find any workaround?

None

**Comment by jindal1979** [comment] 2022-05-11 08:55
The Android icon is coming black on Android with RC3. In fact, all svg are converting from any color to black color in RC3. These were working fine in RC2.

**Comment by XamlTest** [comment] 2022-05-11 09:29
Verified this issue with Visual Studio Enterprise 17.3.0 Preview 1.0 [32427.455.main]. Repro on Android 12, not repro on iOS 15.4 with above project.

**Comment by hartez** [comment] 2022-08-04 19:50
Duplicate of https://github.com/dotnet/maui/issues/7786.
(This one is earlier, but that report has accumulated more info so closing this one.)

**Closed by hartez** 2022-08-04 19:50 UTC
Labels: t/bug, area/single project ☝️, platform/android 🤖, s/verified, s/triaged

**Comment by mattleibow** [comment] 2022-08-31 04:01
This was fixed in #8020
