### ISSUE TITLE
Label content alignment is not proper when it has span elements.

### ISSUE THREAD

**Issue by uragonda-rajesh** [dotnet/maui#7131] opened 2022-05-13 09:10 UTC
### Description

When a Label has more number of span elements with **HorizontalTextAlignment=center**, the alignment is not proper.

### Steps to Reproduce

Run this.

```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:local="clr-namespace:VT.Views"
             xmlns:resources="clr-namespace:VT.Resources"
             x:Class="VT.Views.Demo">

    <ContentPage.Content>
        <StackLayout VerticalOptions="Center"
                    HorizontalOptions="Center"
                    BackgroundColor="green"
                    Margin="0,0,0,11">
            <Label LineHeight="1.2"
                   TextColor="White"
                   Margin="20,20,20,20"
                   HorizontalOptions="CenterAndExpand"
                   HorizontalTextAlignment="Center">
                <Label.FormattedText>
                    <FormattedString>
                        <Span Text="By signing in, you agree to our -sample sample sample " />
                        <Span Text="Terms of service" TextDecorations="Underline">
                        </Span>
                        <Span Text=" and " />
                        <Span Text="Privacy policy" TextDecorations="Underline">
                        </Span>
                    </FormattedString>
                </Label.FormattedText>
            </Label>
        </StackLayout>
    </ContentPage.Content>
</ContentPage>
```
```
namespace VT.Views
{
    public partial class Demo : ContentPage
    {
        public Demo()
        {
            InitializeComponent();
        }
    }
}
```

![label spans](https://user-images.githubusercontent.com/11378500/168251414-bfee46c4-5e1d-4c82-930c-35dd3900ce92.jpeg)

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 10

### Did you find any workaround?

Need to set **HorizontalTextAlignment** to **Start**

**Comment by XamlTest** [comment] 2022-05-13 09:25
Verified this issue with Visual Studio Enterprise 17.3.0 Preview 1.0 [32427.455.main]. Repro on Android 12. Sample project: [MauiApp7.zip](https://github.com/dotnet/maui/files/8685866/MauiApp7.zip)

**Comment by mattleibow** [comment] 2022-05-14 04:46
Duplicate of #4838

**Closed by mattleibow** 2022-05-14 04:46 UTC
Labels: t/bug, area/controls 🎮, s/verified, s/triaged
