### ISSUE TITLE
Regression Android: Border in a Frame results in an empty Frame

### ISSUE THREAD

**Issue by Hooterr** [dotnet/maui#18922] opened 2023-11-21 11:38 UTC
### Description

If you put a `Border` inside a `Frame` nothing will be rendered.
```
<Frame Padding="8" Grid.Row="0">
    <Grid RowDefinitions="auto,auto,auto,*" RowSpacing="8">
        
        <Button Grid.Row="0" Text="B1"></Button>
        <Button Grid.Row="1" Text="B2"></Button>
        <Border Stroke="Red">
            <Button Text="B3"></Button>
        </Border>
    </Grid>
</Frame>
```
![Screenshot_1700566638](https://github.com/dotnet/maui/assets/28758721/8383783b-2cfd-401e-a6ff-9e10e4159613)

### Steps to Reproduce

1. Create a frame
2. Put a border inside it

### Link to public reproduction project repository

https://github.com/Hooterr/Net8IssuesMaui

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.101

### Affected platforms

Android

### Affected platform versions

All

### Did you find any workaround?

Don't use border

**Comment by drasticactions** [comment] 2023-11-21 12:21
Duplicate of https://github.com/dotnet/maui/issues/18755

**Closed by drasticactions** 2023-11-21 12:21 UTC
Labels: t/bug
