### ISSUE TITLE
[Android] Shadow not working properly with clipping

### ISSUE THREAD

**Issue by MohamedHasan3644** [dotnet/maui#14786] opened 2023-04-26 14:14 UTC
### Description

When using shadow for view with clipping, the shadow size is not equivalent to the view's size.

Below is the code snippet used,

```c#
        var grid = new Grid();
        grid.BackgroundColor = Colors.Lavender;
        grid.WidthRequest = 200;
        grid.HeightRequest = 200;
        grid.Shadow = new Shadow()
        {
            Radius = 10,
            Brush = Colors.Black,
            Offset = new Point(0, 0),
            Opacity = 10f
        };
        grid.Clip = new RoundRectangleGeometry(new CornerRadius(0, 10, 10, 0), new Rect(0, 0, 200, 200));
```

Android
![screenshot-1682516410810](https://user-images.githubusercontent.com/102596726/234602889-da12e2e5-db38-48c4-8c4d-38ccd50da3f0.png)

### Steps to Reproduce

Create a .NET MAUI application with above code
Run the application in Android

### Link to public reproduction project repository

Mentioned the code snippet

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 10

### Did you find any workaround?

No

**Comment by rachelkang** [comment] 2023-04-26 18:09
Hi, @MohamedHasan3644 - could you let us know what version of .NET MAUI you are seeing this issue on? This may no longer be an issue on the latest version

**Comment by MohamedHasan3644** [comment] 2023-05-02 05:10
Hi @rachelkang I have seen this issue on MAUI version 6.0.552, MAUI project version 6.0 and VS 2022 17.6.0 Preview 1.0

**Comment by MohamedHasan3644** [comment] 2023-05-02 08:49
Hi @rachelkang, I am facing this issue in latest version also.

**Comment by jsuarezruiz** [comment] 2023-05-08 13:41
Cannot reproduce the issue testing on current main branch:
![image](https://user-images.githubusercontent.com/6755973/236839376-4ebf3a23-3d46-4529-a0cb-ee22d4244079.png)

**Comment by Sasikumar3595** [comment] 2023-05-09 06:15
@jsuarezruiz I am facing the same **issue on Android** platform with latest Visual studio 2022 - 17.5.5.
![image](https://user-images.githubusercontent.com/44917578/237009770-47eaf671-7c61-48f5-9c99-fb61c5522656.png)

and also facing issue related to shadow on **windows platform**. Please find the code sample for issue replication.

```
Grid grid;

    public MainPage()
	{
		InitializeComponent();
        grid = new Grid(); 
		grid.BackgroundColor = Colors.Lavender; 
		grid.Margin = new Thickness(10);
		
		this.Content = grid;
    }

    protected override void OnSizeAllocated(double width, double height)
    {
        base.OnSizeAllocated(width, height); 
		grid.Clip = new RoundRectangleGeometry(new CornerRadius(0, 10, 10, 0), new Rect(0, 0, width -20, height-20));
        grid.Shadow = new Shadow() { Radius = 10, Brush = Colors.Black, Offset = new Point(0, 0), Opacity = 10f };
    }
```

**Windows Issue 1: Shadow not rendered correctly initially.**
<img width="707" alt="Shadow windows issue" src="https://user-images.githubusercontent.com/44917578/237009334-4bb1e583-1798-4795-8481-38bafd6e0f7f.png">

**Windows Issue 1: Shadow not rendered correctly while resize**
<img width="389" alt="Shadow windows resize issue" src="https://user-images.githubusercontent.com/44917578/237009451-4661d06b-20e9-441c-a356-fb02159466cf.png">

**Comment by AntunTkalcec** [comment] 2023-05-22 19:32
Bug is still clearly active on Android. 
![image](https://github.com/dotnet/maui/assets/73123522/cdac86a5-f2bc-49a6-8beb-1dc970614bdd)
Sorry for the small size. (incorrect shadow visible top left of image)

![image](https://github.com/dotnet/maui/assets/73123522/3bd746cd-bf9d-42fb-8d0b-e3ebe913ffad)

Plus, refreshing the Source of this Image crashes the application.

**Comment by Alex-Dobrynin** [comment] 2023-07-22 01:29
+1 UP

**Comment by samhouts** [comment] 2023-08-04 19:08
Duplicate of #11578

**Closed by samhouts** 2023-08-04 19:08 UTC
Labels: t/bug, area/drawing ✏️, s/needs-attention

**Comment by Alex-Dobrynin** [comment] 2023-08-04 21:08
ahaha))) Everything you should know about microsoft and their products - they don't have in plans to fix their own bugs
![image](https://github.com/dotnet/maui/assets/23138430/558e3611-f7c6-4307-96b8-57b7ece423cd)
good job

every such case I think more and more about switching to flutter

**Comment by samhouts** [comment] 2023-08-07 16:21
It just means it's a duplicate of another issue we were tracking that appears to be fixed in NET 8. If your issue is not resolved in NET 8 previews, please let me know. Thanks!

**Comment by Alex-Dobrynin** [comment] 2023-08-11 13:13
@samhouts which is closed and obviously not fixed

**Comment by Alex-Dobrynin** [comment] 2023-08-11 13:19
@samhouts so, we need to wait new version of .net just to get bug fixes? for example we have to wait a year for .net 9 to get bug fixes of .net 8? there is no any other way to provide bug fixes for the platform? omg

**Comment by samhouts** [comment] 2023-08-11 15:01
I'm not sure what you mean. We are continuing to release bug fixes in NET 7 as well as NET 8 Previews just about every month. If you would like us to backport the fix to NET 7, you can ask us in the PR that resolves the issue. If the fix is low risk and doesn't introduce breaking changes in the API, we will probably approve it. We review those requests weekly. Thanks!
