### ISSUE TITLE
App assumes dark mode after resume on device with UIAlertController presented

### ISSUE THREAD

**Issue by frankus** [dotnet/maui#21986] opened 2024-04-22 19:34 UTC
### Description

This was discovered when developing our mobile SDK that displays modal view controllers with transparent backgrounds. 

I was able to repro using a plain UIAlertController. This is only reproducible on device (not on simulator). Tested with iOS 17.4.1. 

### Steps to Reproduce

1. Create new .NET Maui app. Replace contents of MainPage.xaml.cs with the following:

```C#
using CoreGraphics;
using UIKit;

namespace dark_mode_quirk;

public partial class MainPage : ContentPage
{
	public MainPage()
	{
		InitializeComponent();
	}

	private void OnCounterClicked(object sender, EventArgs e)
	{
		var rootVC = UIApplication.SharedApplication.KeyWindow.RootViewController;

		if (rootVC != null) {
			var testVC = UIAlertController.Create("Title", "Message", UIAlertControllerStyle.Alert);

			testVC.AddAction(UIAlertAction.Create("OK", UIAlertActionStyle.Cancel, null));

			// Changing this from the default to "FullScreen" is the key to making it crash.
			rootVC.PresentViewController(testVC, true, null);
		}
	}
}
```

2. Run on a device that is *not* in dark mode
3. Tap the "Click Me" button
4. Observe the UIAlertController presenting
5. Click the home button/swipe the home indicator to return to SpringBoard
6. Tap the app icon to relaunch the app
7. Observe the app behind the UIAlertController is now in dark mode

### Version with bug

8.0.6 SR1

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 17.4.1, not reproducible on simulator

### Did you find any workaround?

No

**Comment by frankus** [comment] 2024-04-22 19:37
Not this also occurs with other types of view controllers with `UIModalPresentationStyle.OverCurrentContext` and a transparent `View.BackgroundColor` and `View.isOpaque = true`. The `UIAlertController` was just a more likely/easier to demonstrate reproduction case.

**Comment by ninachen03** [comment] 2024-04-23 03:02
Verified this issue with Visual Studio 17.10.0 Preview 4 (8.0.6 & 8.0.20).I can repro this issue with physical iOS device(17.2.1)So the version of iOS device should not be specific.

**Comment by jfversluis** [comment] 2024-04-23 11:26
Is this reproducible with an iOS app that doesn't use MAUI?

So if you do `dotnet new ios` and add this there, does it show that behavior? I kind of expect it to, then it's a layer deeper and would need to go to https://github.com/xamarin/xamarin-macios

Would you be able to verify that?

**Comment by drasticactions** [comment] 2024-04-24 06:40
Probably a dupe of https://github.com/dotnet/maui/issues/19614. In short, iOS sends multiple UI Trait updates when you restore an app with System UI on screen, first for the users global setting (So most likely your phone has Dark mode enabled, hence why it's dark.), then whatever the app demands. That trips up the underlying themes, but IMO it's hard to tell if it's a regression in MAUI or iOS, since that behavior was not always the case in iOS.

So the app doesn't assume dark mode, it assumes whatever your global preferences are.

**Closed** 2024-05-03 00:31 UTC
Labels: t/bug, platform/iOS 🍎, s/needs-info, s/verified, s/triaged, s/no-recent-activity
