### ISSUE TITLE
Flyout Menu Icon Changes to 'Back' Icon When Flyout Appears

### ISSUE THREAD

**Issue by brett-macisaac** [dotnet/maui#25809] opened 2024-11-13 01:06 UTC
### Description

When the flyout initially appears, the hamburger icon is replaced with a 'back' icon. This can be seen if the flyout menu isn't completely opaque (see below).

![Image](https://github.com/user-attachments/assets/a8c7ea0d-76a7-4cd2-af74-666a44fe4edb)

### Steps to Reproduce

1. Click the hamburger icon.
2. Notice that when the flyout menu appears, the hamburger icon is replaced with a 'back' icon.
3. Interestingly, if you move the flyout menu even just slightly, the hamburger icon reappears.

### Link to public reproduction project repository

https://github.com/brett-macisaac/maui_flyout_bug

### Version with bug

9.0.0-rc.2.24503.2

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 14

### Did you find any workaround?

The issue can't be seen if the flyout menu's background colour is opaque, although this may go against your app's design.

### Relevant log output

```shell

```

**Comment by Zhanglirong-Winnie** [comment] 2024-11-13 03:17
This issue has been verified using Visual Studio 17.12 Preview 5(8.0.93 & 8.0.82 & 9.0.0-rc.2.24503.2). Can repro this issue on android platform.

**Comment by kubaflo** [comment] 2024-11-16 15:14
Hi @brett-macisaac it is the desired behaviour. Currently MAUI doesn't let you place the Flyout below a navigation bar, so the animation for drawer icon has been turned off. Normally, when it is turned on it follows Android native's behaviour of transforming hamburger menu into arrow and vice versa. And because of the fact that Android shows arrow when drawer is opened the issue you pointed out is not a bug. Check this video to see how it works with the animation on:

https://github.com/user-attachments/assets/3b3d1ea4-c83d-46ec-b0af-849a96e89eb5

@jfversluis I think it should be marked as not planned?

**Comment by brett-macisaac** [comment] 2024-11-17 22:42
Thanks @kubaflo that makes sense, I didn't realise that was the native behaviour. It does look a little strange without the animation though. It's a very minor detail though so there's definitely more important areas to focus on.

**Comment by brett-macisaac** [comment] 2024-11-17 23:36
@kubaflo (or anyone else) if you find some time could you please check out the other [issue](https://github.com/dotnet/maui/issues/25547) that I opened?

**Comment by mattleibow** [comment] 2024-11-18 18:03
Closing this as a not an issue.

**Closed by mattleibow** 2024-11-18 18:03 UTC
Labels: t/bug, s/verified, s/triaged
