### ISSUE TITLE
Adaptive Trigger not working NET 7 MacCatalyst

### ISSUE THREAD

**Issue by nauman74** [dotnet/maui#11114] opened 2022-11-05 09:34 UTC
### Description

Tested with net maui samples TriggerDemos solution
The Adaptive Trigger demo works fine on NET 6, retarget for NET 7 and it is no longer working

### Steps to Reproduce

1. retarget official Maui TriggerDemos sample for NET7. 
2. Browse to AdaptiveTrigger demo
3. Observe  StackLayout orientation does not change on window width change

### Link to public reproduction project repository

https://github.com/dotnet/maui-samples/tree/main/6.0/Fundamentals/TriggersDemos

### Version with bug

7.0 Release Candidate 2

### Last version that worked well

6.0.408

### Affected platforms

macOS

### Affected platform versions

macOS Monterey version 12.5.1

### Did you find any workaround?

Use DataTrigger on width of view element

**Comment by jsuarezruiz** [comment] 2022-11-08 09:51
I think this issue have been fixed by https://github.com/dotnet/maui/pull/9984
Tested with current main branch and latest version (net 7 ga, available really soon) and cannot reproduce the issue.

![issue-11114](https://user-images.githubusercontent.com/6755973/200532260-af3042e7-d336-40c1-ae18-6192a2a47b6f.gif)

Could you try with latest version?. If the issue persists, could you attach a small sample where reproduce the issue?

**Closed** 2022-11-17 01:01 UTC
Labels: t/bug, area/Xaml </>, s/needs-info, s/no-recent-activity
