### ISSUE TITLE
Grouped CollectionView fires IndexOutOfBoundsException from MauiRecyclerView after second collapse/expand

### ISSUE THREAD

**Issue by mattkeene** [dotnet/maui#23068] opened 2024-06-14 21:01 UTC
### Description

In an Android / iOS MAUI application, one of my pages implements an expandable/collapsible CollectionView bound to an `ObservableCollection<ProtocolGroup>`. ProtocolGroup is an extension of `ObservableRangeCollection<Protocol>` with properties for IsCollapsed, GroupName, and DropdownText (arrow-icon that changes on collapse). ProtocolGroup also implements INotifyPropertyChanged, for when IsCollapsed and DropdownText change. ObservableRangeCollection handles the notifications for AddRange() and Clear(), the methods I use to collapse/expand each group by removing or adding Protocol objects from the full list. I originally used `List<Protocol>` for the items in each group (more info in workaround section) but this results in the groups not animating on collapse/expand. 

I created a fresh repo (linked below) using only the classes necessary for this single CollectionView, and the issue persists. The primary `ObservableCollection<ProtocolGroup>` does not change after initialization (no groups are added/removed) and therefore I originally had it as a `List<ProtocolGroup>` which resulted in the same exact behavior, so I Ieft it as an ObservableCollection in the attached repo.

All groups begin collapsed and everything works at first. I can expand all the groups, and collapse all the groups. However, when I expand a group that has previously been collapsed (e.g the second expansion) an **Java.Lang.IndexOutOfBoundsException:** is thrown from the MauiRecyclerView (full error pasted below in the log output) and my application crashes. Since everything is in sync for the first expand/collapse, what could be going wrong afterwards?

### Steps to Reproduce

1. Run the repo on an Android simulator or device
2. Tap a few groups to expand
3. Tap them again to collapse
4. Tap any one you manually collapsed

Expected outcome: The group should expand again
Actual outcome: The exception in the log output is thrown and the application crashes

### Link to public reproduction project repository

https://github.com/mattkeene/CollectionViewBugRepro

### Version with bug

8.0.40 SR5

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

Android 14.0 - API 34

### Did you find any workaround?

By changing ProtocolGroup to be an extension of `List<Protocol>` which implements INotifyPropertyChanged and INotifyCollectionChanged, I can manually "new" the Clear() and AddRange() methods of `List<Protocol>` to call the base versions followed by calling RaiseCollectionChanged() and RaisedPropertyChanged() (on Count, Items[], and DropdownText) which invoke them, respectively. This results in functional collapsible/expandable groups without exceptions/crashes, BUT it does not animate the collapsing/expanding which hinders the user experience as the lists simply appear and disappear starkly. By using `ObservableRangeCollection<Protocol>`, the expanding/collapsing is animated as expected, but crashes on second expand.

### Relevant log output

```shell
**Java.Lang.IndexOutOfBoundsException:** 'Inconsistency detected. Invalid view holder adapter positionTemplatedItemViewHolder{cf38be1 position=37 id=-1, oldPos=17, pLpos:17 scrap [attachedScrap] tmpDetached no parent} crc645d80431ce5f73f11.MauiRecyclerView_3{efa7858 VFED..... ......ID 0,0-1080,2054}, adapter:crc645d80431ce5f73f11.ReorderableItemsViewAdapter_2@2f947d2, layout:androidx.recyclerview.widget.LinearLayoutManager@3a8a788, context:crc642c18c1b741c10a87.MainActivity@de5472c'
```

**Comment by PureWeen** [comment] 2024-06-15 22:52
Duplicate of https://github.com/dotnet/maui/issues/20819

**Closed** 2024-06-15 22:52 UTC
Labels: t/bug, platform/android 🤖, p/2, area-controls-collectionview

**Comment by mattkeene** [comment] 2024-06-18 19:01
For anyone that comes to this after the fact, a temporary workaround until the component is fixed is use `RemoveAt(0)` in place of `Clear()` until the group is empty. It slows the application down because of all the extra events, but it avoids crashing.
