### ISSUE TITLE
CollectionView with ItemSpacing => Infinite layout loop Android

### ISSUE THREAD

**Issue by rudyspano** [dotnet/maui#21379] opened 2024-03-22 05:55 UTC
### Description

A CollectionView with an ItemSpacing of 1 i causes infinite changes of Cell content controls Height on Android.
As you can see in video and simple repro project

https://github.com/dotnet/maui/assets/21014908/c1653c49-50de-4f12-a29f-b615e267a378

=> Huge performance Impact.

Reproducible since 8.0.10 then 8.0.14.
Not reproducible in 8.0.6

Simple repro project in attachment.
[reprov2.zip](https://github.com/dotnet/maui/files/14739213/reprov2.zip)

Height values imprecisions, probably due to Android px to MAUI dp conversion..?

### Steps to Reproduce

See repro project.

### Version with bug

8.0.14 and 8.0.10

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI, Yes, this used to work in Xamarin.Forms

### Last version that worked well

8.0.6 SR1

### Affected platforms

Android

### Did you find any workaround?

Not using ItemSpacing

**Comment by PureWeen** [comment] 2024-03-22 07:02
@rudyspano I ran your sample locally and I'm not seeing an infinite loop

The break point inside `GridProblem_PropertyChanged` never fires for me if  I don't scroll the CV

**Comment by rudyspano** [comment] 2024-03-22 07:24
@PureWeen , I have updated the sample with a Console output.
I've tested my zip, if I just do a Retore Nuget package on solution, the project runs on Android.

Don't you see infinite call of propertychanged with values near from 158 (cell HeightRequest) ?

**Comment by PureWeen** [comment] 2024-03-22 16:20
Alright, I was able to reproduce in 8.0.7

**Comment by rudyspano** [comment] 2024-03-22 16:41
@PureWeen , ok good news 🙂.
I will fix the repro monday.
Latest version is 8.0.14? Right? 
Why on Android, we do not have real values ? I know that Android uses pixels but when call stack switches to cross plateforme unit, we should see 158 and not 157,8 or 158,1. I've seen other other properties that results in same behavior and that very confusing for Debug sessions...

Thanks for your investigation.

**Comment by PureWeen** [comment] 2024-03-27 21:12
@rudyspano can you test the latest nightly and see if you are still seeing this issue?

**Comment by rudyspano** [comment] 2024-03-28 04:36
@PureWeen , I confirm that fixes the issue ! (in my repro and more complex project)

Is it also fixed by this PR https://github.com/dotnet/maui/pull/21409/files ?
Still, if I inspect Height value (console output), I see weird Height: 158.1818181818182 for a HeightRequest of 158

Thanks

**Comment by PureWeen** [comment] 2024-03-28 15:37
awesome thank you for testing @rudyspano!!

I think it was this PR that fixed it 
https://github.com/dotnet/maui/pull/18856

I couldn't reproduce the issue when I was working on 21409 so that's my guess. 

Does this issue match what you're curious about with measuring? 
https://github.com/dotnet/maui/issues/21474

My guess is that what's happening with measure is that it's just a result of converting forward and backwards and after taking into account platform paddings/margins. 

Though I don't know for sure. 

I'm going to close this issue for now. 
If the measuring part of this is causing you issues and isn't the same as 21474 can you log a new issue elaborating on your scenario a bit?

**Closed by PureWeen** 2024-03-28 15:37 UTC
Labels: t/bug, platform/android 🤖, area/collectionview 📃, i/regression
