### ISSUE TITLE
RC2 - The BackgroundColor of the BoxView does not work

### ISSUE THREAD

**Issue by HausBJB** [dotnet/maui#6592] opened 2022-04-28 08:33 UTC
### Description

The BoxView BackgroundColor doesn't work, it always stays gray even if you add a different color to it, It happens on Android

`<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             BackgroundColor="White"
             x:Class="MauiCollectionView.MainPage">

    <VerticalStackLayout>
        <BoxView 
            WidthRequest="200"
            HeightRequest="200"
            BackgroundColor="Blue"/>
    </VerticalStackLayout>
</ContentPage>`

Repro
[Repro](https://github.com/dotnet/maui/files/8548848/MauiApp4.zip)

![image](https://user-images.githubusercontent.com/53478848/165711856-d637b319-622f-4bf5-aea5-2a2980a2a9ce.png)

### Steps to Reproduce

Cloning the attached repository and running the application on both Windows and Android, the BoxView will not change the BackgroundColor and will always remain gray.

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 12 API 31

**Comment by XamlTest** [comment] 2022-04-28 08:41
Verified this issue with Visual Studio Enterprise 17.3.0 Preview 1.0 [32427.455.main]. Repro on Windows and Android with above project.

**Comment by jsuarezruiz** [comment] 2022-04-28 14:05
Cannot reproduce the issue on main branch 
![image](https://user-images.githubusercontent.com/6755973/165770616-644a92e3-1d68-4397-968a-4360013bf022.png)

**Comment by HausBJB** [comment] 2022-05-03 08:39
Hello, I found out that it is due to the VerticalStackLayout

I use the VerticalStackLayout
then I have to set Color
` <VerticalStackLayout>
        <Entry x:Name="testEntry" Text="hallo"></Entry>
        <Button Text="test" Clicked="OnCounterClicked"></Button>
        <BoxView WidthRequest="300" HeightRequest="300" Color="Red" BackgroundColor="Aqua">
        </BoxView>
    </VerticalStackLayout>`
![image](https://user-images.githubusercontent.com/53478848/166425232-9eedc501-72c6-4ff9-a437-64ac58db0f3f.png)

use StackLayout does this also work with BackgroundColor
`    <StackLayout>
        <Entry x:Name="testEntry" Text="hallo"></Entry>
        <Button Text="test" Clicked="OnCounterClicked"></Button>
        <BoxView WidthRequest="300" HeightRequest="300"  BackgroundColor="Aqua">
        </BoxView>
    </StackLayout>`

![image](https://user-images.githubusercontent.com/53478848/166425374-f82e3061-a790-4d7c-934e-e4e82005edc0.png)

use StackLayout and Color, then Color overrides BackgroundColor
`    <StackLayout>
        <Entry x:Name="testEntry" Text="hallo"></Entry>
        <Button Text="test" Clicked="OnCounterClicked"></Button>
        <BoxView WidthRequest="300" HeightRequest="300" Color="Red" BackgroundColor="Aqua">
        </BoxView>
    </StackLayout>`

![image](https://user-images.githubusercontent.com/53478848/166425603-5c8e3e6d-4547-40a7-b42c-2d2a5776d1b4.png)

**Comment by Redth** [comment] 2022-05-03 17:09
Please try using Border and avoiding BoxView for now.

**Comment by Redth** [comment] 2022-05-03 17:09
@PureWeen  /cc

**Comment by HausBJB** [comment] 2022-05-27 09:18
Hello
This is how it looks for me as soon as I set the Color property it works.
Background color is ignored

![image](https://user-images.githubusercontent.com/53478848/170670198-6b0e6e14-076e-4c29-9ac6-96f6b3247cab.png)

**Comment by HausBJB** [comment] 2022-05-27 09:20
Hello, is that correct that the color overwrites the background color in test2? it looks the same to them
![image](https://user-images.githubusercontent.com/53478848/170670825-39470441-2baf-42bf-9757-64d53234d6cf.png)

**Comment by MGohil** [comment] 2022-06-17 09:03
I switched to `<Rectangle />` to get this sorted for time being.

![image](https://user-images.githubusercontent.com/16605284/174265338-23b39233-a31a-448d-bfbe-dd066e236ded.png)

**Comment by HausBJB** [comment] 2022-06-17 11:25
Thanks, that's exactly what I did. Nobody here seems to care.
I've already opened a ticket twice with the same problem and the new version doesn't work again
https://github.com/dotnet/maui/issues/7448

so i gave up

**Comment by hartez** [comment] 2022-06-22 23:31
Earlier versions of MAUI.Controls had the "box is always gray" issue, but that should be fixed (if not already in Service Release 1, then definitely in Service Release 2, which should be released in the near future).

BoxView in Xamarin.Forms was weird, because `BackgroundColor` and `Color` were effectively the same property. 

The BoxView in MAUI.Controls keeps both properties for backward compatibility. The actual implementation of BoxView in MAUI.Controls is literally just a `<Rectangle/>` under the hood. We recommend using the Rectangle because it doesn't have the confusing extra property.

If you specify _only_ the `BackgroundColor` (or `Background`) property, then the `Fill` for the Rectangle will use that color. If you specify `Color`, the `Color` property will determine the `Fill` for the Rectangle. In other words, `Color` always wins.

**Closed by hartez** 2022-06-22 23:31 UTC
Labels: t/bug, area/controls 🎮, s/verified, s/triaged
