### ISSUE TITLE
ToolbarItem is not appearing

### ISSUE THREAD

**Issue by RobertoGFilho** [dotnet/maui#4157] opened 2022-01-16 22:51 UTC
### Description

Tool bar item is not appearing, but if you remove IconImageSource property and add again, it will appear
<ToolbarItem Text="{extensions:Translate add}" Command="{Binding NewCommand}" IconImageSource="{StaticResource Add}"/>
  

### Steps to Reproduce

1. Create ContentPage;
2. Add ToolBarItem;

### Version with bug

Preview 11

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 12

**Comment by Phil4121** [comment] 2022-01-17 06:53
This works for me:
https://github.com/dotnet/maui/issues/3593

**Comment by shimingsg** [comment] 2022-02-21 05:30
Duplicate of #3842

**Closed by shimingsg** 2022-02-21 05:30 UTC
Labels: t/bug, area/navigation 🧭, s/verified
