### ISSUE TITLE
Maui api examples are inaccurate, obsolete, and don't compile

### ISSUE THREAD

**Issue by Atezian** [dotnet/maui#15964] opened 2023-07-02 06:57 UTC
### Description

![image](https://github.com/dotnet/maui/assets/73472595/dedfffb9-5722-48be-b366-72dc90590a6f)

### Steps to Reproduce

1) Create a new .net maui app project in VisualStudio 2022.

2) Copy and paste the grid example on the maui api docs.
<https://learn.microsoft.com/en-us/dotnet/api/microsoft.maui.controls.grid?view=net-maui-7.0>

3) Observe how there is obsolete code. Also, Color.White for example that doesn't compile because Microsoft.Maui.Graphics.Color doesn't contain definitions for these properties. Adding anywhere up to 5 arguments into a method signature that only takes 1 argument. An attempt to call a method that doesn't exist (Device.OnPlatform(...)) Microsoft.Maui.Controls.Device.

### Link to public reproduction project repository

https://learn.microsoft.com/en-us/dotnet/api/microsoft.maui.controls.grid?view=net-maui-7.0

### Version with bug

7.0.49

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Windows SDK 10.x

### Did you find any workaround?

No. I am trying to learn Maui and I don't know how to solve these issues and I don't know where to ask or find information that would resolve these problems as a work around.

**Comment by jfversluis** [comment] 2023-07-02 18:44
Thanks, we're aware and working hard to make it better as part of #3960

**Comment by jfversluis** [comment] 2023-07-02 18:45
Duplicate of #3960

**Closed by jfversluis** 2023-07-02 18:45 UTC
Labels: t/bug
