### ISSUE TITLE
Completed event does not fire on Return key on Editor

### ISSUE THREAD

**Issue by HobDev** [dotnet/maui#5130] opened 2022-03-08 11:27 UTC
### Description

The return key Changes line on editor but does not complete the the text input.  The completed event is fired when the editor loose focus. 

### Steps to Reproduce

Debug the repro project and put breakPoint on the completed event of both the editors
[EditorBugSample.zip](https://github.com/dotnet/maui/files/8205688/EditorBugSample.zip)

### Version with bug

Preview 13 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

iOS 15 and Android 11

**Comment by HobDev** [comment] 2022-03-08 13:13
@jsuarezruiz The issue is with editor. But control-entry label is added

**Comment by jsuarezruiz** [comment] 2022-03-08 13:14
Yeah, sorry for the confusion. I know, the label is used for different controls: Editor, Entry and SearchBar.

**Comment by jinxinjuan** [comment] 2023-04-17 09:47
Verified this issue with Visual Studio Enterprise 17.6.0 Preview 2.0. Repro on Android and iOS platform with sample project.

**Comment by mattleibow** [comment] 2023-10-05 00:14
Duplicate of https://github.com/dotnet/maui/issues/9796

**Closed** 2023-10-05 00:21 UTC
Labels: t/bug, area/controls 🎮, s/verified, control-entry, s/triaged
