### ISSUE TITLE
DisplayPromptAsync: introduce a parameter for hiding the entered text (e.g. password)

### ISSUE THREAD

**Issue by GlitchedPolygons** [dotnet/maui#15817] opened 2023-06-23 12:43 UTC
### Description

Introduce a parameter such as `HideText`, `IsPassword` or something like that for hiding text input while the user is typing/pasting into a dialog prompt that was opened with `DisplayPromptAsync`.

https://learn.microsoft.com/en-us/dotnet/maui/user-interface/pop-ups

### Public API Changes

```csharp
string password = await Application.Current!.MainPage!.DisplayPromptAsync
   (
      title: "Enter password", 
      message: "Please enter the password to proceed with authentication", 
      accept: "Login", 
      cancel: "Cancel", 
      hideText: true
   );
```

### Intended Use-Case

The .NET MAUI Blazor modals are awesome! But one thing that's definitively missing in my opinion is a parameter such as `HideText`, `IsPassword` or anything like that for hiding the text input while the user is typing it into the dialog prompt (opened with `DisplayPromptAsync`).

If this feature is implemented, almost anything modal-related can be achieved directly with the default MAUI alerts and custom pages are no longer required, allowing for even more consistency within projects that make rich use of pop-up dialogs.

**Comment by jfversluis** [comment] 2023-06-23 13:23
Duplicate of #9913

**Closed by jfversluis** 2023-06-23 13:23 UTC
Labels: proposal/open
