### ISSUE TITLE
IsVisible Not Render or Update from IsVisible = False to True.

### ISSUE THREAD

**Issue by nextcodelab** [dotnet/maui#8129] opened 2022-06-16 21:53 UTC
I have pre built custom controls that is hidden on start up.. when I click button to show hidden view through isvisible = true;
the view will not render like buttons and any controls just black space... this test is from my real app that already on the store.

It works on WinUI, but android just a black screen no controls shown...
When I clicked the DisplaySheetAlert the view will render and its controls to normal.. in Android.

Adding Custom controls also in C# code dynamically also not rendered.

Sample App
[IsVisibleTest.zip](https://github.com/dotnet/maui/files/8923210/IsVisibleTest.zip)

PLEASE NOTIFY ME IF THERE IS IMPROVEMENT, MY APP IS WAITING UPDATE MY MAUI APP ON STORE.

**Comment by Symbai** [comment] 2022-06-16 22:20
Could be the same as of #8044

**Comment by jfversluis** [comment] 2022-06-18 07:25
Duplicate of #8044

**Closed by jfversluis** 2022-06-18 07:25 UTC
Labels: area/controls 🎮
