### ISSUE TITLE
wwwroot resources in shared/rcl assemly are not served under _contents/{assembly} in hybrid wpf blazor app

### ISSUE THREAD

**Issue by mediabuff** [dotnet/maui#14504] opened 2023-04-11 01:45 UTC
### Description

Normally, please see
https://learn.microsoft.com/en-us/aspnet/core/blazor/components/class-libraries?view=aspnetcore-7.0&tabs=visual-studio

Place static assets in the wwwroot folder of the RCL and reference the static assets with the following path in the app: _content/{PACKAGE ID}/{PATH AND FILE NAME}. The {PACKAGE ID} placeholder is the library's [package ID](https://learn.microsoft.com/en-us/nuget/create-packages/creating-a-package-msbuild#set-properties). The package ID defaults to the project's assembly name if <PackageId> isn't specified in the project file. The {PATH AND FILE NAME} placeholder is path and file name under wwwroot. This path format is also used in the app for static assets supplied by NuGet packages added to the RCL.

Under debug mode, the file are not copies but virtually mapped for normal Blazor apps. This does not seem to be the case for Hybrid WPF.

### Steps to Reproduce

1. Create Hyrbid WPF app
2. Create RCL for to be shared.
3. Located static assets of RCL from WPF app

### Link to public reproduction project repository

none

### Version with bug

6.0.312

### Last version that worked well

6.0.312

### Affected platforms

Windows

### Affected platform versions

Windows

### Did you find any workaround?

Copy over wwwroot from shared projects

### Relevant log output

```shell
Content not available
```

**Comment by mediabuff** [comment] 2023-04-11 11:42
Just another clarification. I am not sure if this is a broader virtual mapping issue, as it seem to work when the resource is referenced in html - either as a script or css asset. The specific problem may be restricted to urls that are set in "HostPath"of BlazorWebView. I have my index.html, the starting HostPath, in the shared RCL.

**Comment by MackinnonBuck** [comment] 2023-04-11 16:47
Thanks for reaching out. This looks like a duplicate of https://github.com/dotnet/maui/issues/11541, given that the host page is in the RCL.

**Closed by MackinnonBuck** 2023-04-11 16:47 UTC
Labels: t/bug, area/blazor 🕸️
