### ISSUE TITLE
Moving BlazorDesktop WinForm by dragging element in BlazorWebView crashes

### ISSUE THREAD

**Issue by AaronAnz** [dotnet/maui#3395] opened 2021-11-11 00:51 UTC
I wanna start by saying i'm not sure if i'm doing this correctly or if this is even an issue with BlazorWebView. It may just be an issue with Edge Runtime in general but wanted to see if there is something could be implemented into BlazorWebView to prevent the bug or assist in accomplishing this without crashing.

### Describe the bug
I created a BlazorDesktop WinForms application that uses FormBorderStyle.None and my "TitleBar" is a NavBar in my Layout razor component. I use the onmousedown ( also tried ondragstart and ondrag ) event on the navbar to call my service that I injected which calls ReleaseCapture and SendMessage to drag the form. Works great but crashes randomly with no error but a generic error in the console / event viewer

### To Reproduce
Inject this service into the BlazorWebView 
```
public interface IDragService
  {
      public void BeginDrag();
      public void EndDrag();
  }
  public class DragService : IDragService
  {
      public const int WM_NCLBUTTONDOWN = 0xA1;
      public const int WM_NCLBUTTONUP = 0xA2;
      public const int HT_CAPTION = 0x2;

      [System.Runtime.InteropServices.DllImport("user32.dll")]
      public static extern int SendMessage(IntPtr hWnd, int Msg, int wParam, int lParam);
      
      [System.Runtime.InteropServices.DllImport("user32.dll")]
      public static extern bool ReleaseCapture();

      private IntPtr MainHandle { get; init; }

      public DragService()
      {
          MainHandle = Application.OpenForms.OfType<Form1>().FirstOrDefault().Handle;
      }
      public void BeginDrag()
      {
          ReleaseCapture();
          SendMessage(MainHandle, WM_NCLBUTTONDOWN, HT_CAPTION, 0); 
      }
      public void EndDrag()
      {
          ////ReleaseCapture();
          //SendMessage(MainHandle, WM_NCLBUTTONUP, HT_CAPTION, 0);
      }
  }
```

and setup your Layout razor component similar to this:
```
@inherits LayoutComponentBase
@inject IDragService dragService

<div @onmousedown="onDragStart">testing</div>

<div>
    @Body
</div>

@code {
    private void onDragStart()
        => dragService.BeginDrag();

    //private void onDragEnd()
     //   => dragService.EndDrag();
}
```

### Exceptions (if any)
Works fine for a while but just randomly it crashes and outputs the following to console:
`The program '[13320] Test.exe' has exited with code 3221226525 (0xc000041d).`

and 
```
Faulting application name: Test.exe, version: 1.0.0.0, time stamp: 0x61735063
Faulting module name: EmbeddedBrowserWebView.dll, version: 95.0.1020.44, time stamp: 0x61827850
Exception code: 0xc000041d
Fault offset: 0x00000000002bea6d
Faulting process id: 0x3408
Faulting application start time: 0x01d7d693ccd7f531
Faulting application path: D:\Code\Test\bin\Debug\net6.0-windows10.0.19041\Test.exe
Faulting module path: C:\Program Files (x86)\Microsoft\EdgeWebView\Application\95.0.1020.44\EBWebView\x64\EmbeddedBrowserWebView.dll
Report Id: 1ab5fd72-94f1-4b86-9b8e-2c255c003da1
Faulting package full name: 
Faulting package-relative application ID: 
```

### Further technical details
ASP.NET Core version: Latest
IDE: VS 2022 Current
```
.NET SDK (reflecting any global.json):
 Version:   6.0.100
 Commit:    9e8b04bbff

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100\

Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa

.NET SDKs installed:
  6.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by RichardWalace** [comment] 2021-11-16 17:14
Same problem occurs using wpf and trying to bind a function using `DragMove()` in an `onmousedown` event

**Comment by AaronAnz** [comment] 2022-01-28 01:13
@Eilon Any suggestions or we just gonna forget this is a thing?

**Comment by Eilon** [comment] 2022-01-28 17:11
Hi @AaronAnz it's not forgotten. We are working on fixing issues in priority order.

**Comment by AaronAnz** [comment] 2022-02-15 04:49
Kinda sucks because I want to be able to use the built in Windows Snapping and that seems to be the only way. I had to workaround this with a timer but its not ideal. Really hope this can be fixed at some point.

**Comment by Eilon** [comment] 2022-02-15 05:12
@AaronAnz understood, and thank you for following up. I know it's not ideal. If you're interested and able to, you could consider sending a PR for this. I have no idea what the fix might be or how complex it might be. Could be some 1-line change for all I know (but seems unlikely). Or it could be some bug in WebView2, also. Or if you're interested/able to debug the crash a bit more and see if maybe it seems like it _is_ a WebView2 issue, in which case we should get a bug logged at https://github.com/MicrosoftEdge/WebView2Feedback/issues (and close this one here).

**Comment by Eilon** [comment] 2022-02-15 05:16
Also to help debugging, I happened to learn some info from this comment in a different WebView2 issue: https://github.com/MicrosoftEdge/WebView2Feedback/issues/2132#issuecomment-1030252527

So maybe the debugging tips there could help narrow down the root cause of this crash.

**Comment by AaronAnz** [comment] 2022-02-16 05:46
Unfortunately "<userDataFolder>\EBWebView\crashpad\reports" contains nothing after the crash and ProcessFailed never triggers.

**Comment by Eilon** [comment] 2022-02-21 06:28
@AaronAnz alright thank you for the update. We don't have a timeline to investigate this because it so far hasn't reached the highest priority. If you do suspect it could be an issue with WebView2 itself, it could be worth logging a bug there too and dropping a link in case another person has some idea.

**Comment by honzapatCZ** [comment] 2022-07-27 11:25
For me this workaround works perfectly. As for WPF the error was made only by the default WPF handling, as the WebView doesn't pass down the MouseButtonDown, etc. events to WPF and as such WPF doesn't know that the mouse is down and freaks out. Iam not entirely sure why we are not passing those events, probably that's up to someone at WebView team.
  ```cs
public class DragService : IDragService
  {
      public const int WM_NCLBUTTONDOWN = 0xA1;
      public const int WM_NCLBUTTONUP = 0xA2;
      public const int HT_CAPTION = 0x2;

      [System.Runtime.InteropServices.DllImport("user32.dll")]
      public static extern int SendMessage(IntPtr hWnd, int Msg, int wParam, int lParam);
      
      [System.Runtime.InteropServices.DllImport("user32.dll")]
      public static extern bool ReleaseCapture();

      private IntPtr MainHandle { get; init; }

      public DragService()
      {
          MainHandle = Application.OpenForms.OfType<Form1>().FirstOrDefault().Handle;
      }
      public void BeginDrag()
      {
          ReleaseCapture();
          SendMessage(MainHandle, WM_NCLBUTTONDOWN, HT_CAPTION, 0); 
      }
      public void EndDrag()
      {
          ////ReleaseCapture();
          //SendMessage(MainHandle, WM_NCLBUTTONUP, HT_CAPTION, 0);
      }
  }
```

**Comment by Eilon** [comment] 2022-11-28 22:23
I tried this in a pure WinForms app with WebView2 and it does _not_ repro. That is, the dragging seems to work just fine. I tried that to see if this could be an underlying WebView2 or WinForms issue, but it doesn't appear to be a problem in the most recent versions of each (.NET 7 WinForms + WebView2 1.0.1418.22).

I'll try in the latest WinForms + BlazorWebView to see if I can repro it there (or not!).

**Comment by Eilon** [comment] 2022-11-28 22:47
Well, that's interesting! It doesn't repro in Blazor + WinForms, either! So maybe since this bug was filed something changed in either Blazor/Blazor Hybrid, WinForms, or WebView2?

**Comment by Eilon** [comment] 2022-11-28 22:56
I put my repro apps here: https://github.com/Eilon/DragDropWinFormsApp2

* The pure WinForms + WebView2 app is here: https://github.com/Eilon/DragDropWinFormsApp2/tree/main/DragDropWinFormsApp2
* The Blazor Hybrid WinForms app is here: https://github.com/Eilon/DragDropWinFormsApp2/tree/main/BlazorDragDropWinFormsApp1

**Comment by Eilon** [comment] 2022-11-28 22:57
Given that I can no longer reproduce this issue, I am closing it. If anyone still sees any issue, please log a new issue with a full app that reproduces the issue so that we can investigate further.

**Closed by Eilon** 2022-11-28 22:57 UTC
Labels: area/blazor 🕸️, feature-blazor-windesktop, investigate
