### ISSUE TITLE
Maui Blazor - SCCM Remote Control freezes any input after connecting

### ISSUE THREAD

**Issue by mtbayley** [dotnet/maui#15481] opened 2023-06-06 16:28 UTC
### Description

Any input is frozen after connecting with SCCM Remote Control. Input stays frozen even after disconnecting.

### Steps to Reproduce

1. Create new MAUI Blazor App
2. Publish windows app and sideload to another machine.
3. Run application.
4. Connect to other machine with SCCM Remote Control.
5. Input is now frozen

### Link to public reproduction project repository

https://github.com/mtbayley/MauiAppTest

### Version with bug

7.0.86

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows SDK 10.0.19041.0

**Comment by Eilon** [comment] 2023-06-06 16:39
Hi @mtbayley , does this also happen with a regular .NET MAUI app (without Blazor)?

What parts of the app are frozen? Can you move the window around? Can you click/scroll within the app? Do the minimize/maximize buttons work on the app?

**Comment by mtbayley** [comment] 2023-06-06 18:21
This does not happen with a regular .NET MAUI app.
I can move around the window, maximize, minimize, but I can't interact with anything inside the Blazor web view. It looks like keyboard input still works ok, just not the mouse or touch input.

**Comment by Eilon** [comment] 2023-06-06 18:48
@mtbayley alright that's good to know. Any idea if it happens with a regular MAUI WebView? You could place something like `<WebView Source="https://learn.microsoft.com/dotnet/maui" />` _instead_ if the BlazorWebView. This is to help rule out whether Blazor itself has any effect, or if it's a more general WebView2 issue (in which case we should file a bug at https://github.com/MicrosoftEdge/WebView2Feedback/issues/).

**Comment by mtbayley** [comment] 2023-06-06 18:56
Confirmed. I also get the same behavior with standard WebView.

**Comment by Eilon** [comment] 2023-06-06 22:31
@mtbayley great, thank you for confirming that too. This leads me to believe that the issue is with the Edge WebView2 component that .NET MAUI uses on Windows for displaying web content. Unfortunately we can't directly move issues to the https://github.com/MicrosoftEdge/WebView2Feedback/issues/ repo, so I ask that you create a new issue in that repo so that it can be investigated by that team.

**Comment by mtbayley** [comment] 2023-06-07 12:49
Thanks. Reported to the WebView2 team.

**Comment by Eilon** [comment] 2023-06-07 17:53
Thanks! I'm closing this issue and folks can use the new issue you created at https://github.com/MicrosoftEdge/WebView2Feedback/issues/3546 to track the progress.

**Closed by Eilon** 2023-06-07 17:53 UTC
Labels: t/bug, area/blazor 🕸️
