### ISSUE TITLE
Keystroke capture support Maui

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#21397] opened 2024-03-22 16:52 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Keystroke-capture-support-Maui/10577285)._

---
I know this is a duplicate but this is really important as we cannot migrate to MAUI without this feature:
We need a way to capture key strokes in MAUI. This would be the equivalent of protected override void OnKeyUp(KeyEventArgs e) in a Windows forms app and public override bool OnKeyUp(Keycode keyCode, KeyEvent e) in an Android activity. Mac and iOS have similar interfaces to these. The key capture should be from ANY view, not just an Entry.

---
#### Feedback Bot on 2/4/2024, 01:14 AM: 

(private comment, text removed)

**Comment by jfversluis** [comment] 2024-03-22 18:49
Duplicate of #16799

**Closed by jfversluis** 2024-03-22 18:49 UTC
