### ISSUE TITLE
Content is not render properly when the 'Don't keep activities' setting is enabled

### ISSUE THREAD

**Issue by AarthiArjunan** [dotnet/maui#26742] opened 2024-12-20 05:46 UTC
### Description

In our custom control, When the 'Don't keep activities' setting is enabled, the custom control content disappears after navigating away from and back to our application. The expected behavior is that it should not disappear and should render properly.

Issue Reproduce Video:
https://github.com/user-attachments/assets/72c8e70d-793f-4733-9d3d-af1e5b567b3a

### Steps to Reproduce

1.Go to the developer options.
2. Enable the don't keep activities option.
3. Run the sample.
4. draw something in screen
5. navigating away from and back to our application.
6. drawn content will disappear.
The Excepted behavior
7. It should not disappear.

### Link to public reproduction project repository

[CustomDrawingPad-Sample](https://github.com/AarthiArjunan/CustomDrawingPad-Sample)

### Version with bug

9.0.0-rc.1.24453.9

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 12

### Did you find any workaround?

No

### Relevant log output

```shell

```

**Comment by jfversluis** [comment] 2024-12-20 09:10
Duplicate of #24967

**Comment by jfversluis** [comment] 2024-12-20 09:10
Please don't keep opening identical issues for the same problem, thanks

**Closed by jfversluis** 2024-12-20 09:10 UTC
Labels: t/bug

**Comment by Zhanglirong-Winnie** [comment] 2024-12-20 09:12
This issue has been verified using Visual Studio 17.13 preview 2 (9.0.12 & 9.0.0 & 8.0.100 & 8.0.83). Can repro this issue on android SM device platform.
