### ISSUE TITLE
This issue still persists with the latest release version

### ISSUE THREAD

**Issue by shameelfazul** [dotnet/maui#13029] opened 2023-01-31 18:49 UTC
> Hey there, thanks for the report! Does it also happen on Windows are you able to test that? Do you also see this happening on Windows or iOS?
> 
> And I see you mention .NET MAUI version 6.0.401, which is not the latest. Are you sure you are using that version? Could you use the latest version of MAUI and see if that helps?

It appears to be fixed on the latest version.

_Originally posted by @shameelfazul in https://github.com/dotnet/maui/issues/10315#issuecomment-1262049795_

**Comment by jfversluis** [comment] 2023-02-01 09:36
I'm a bit confused... It says its fixed but now it's not fixed? 😅

Could you please add a little more information? What version(s) are you using now? Was it indeed fixed in an earlier version but is is back now?

**Comment by shameelfazul** [comment] 2023-02-02 14:57
> I'm a bit confused... It says its fixed but now it's not fixed? sweat_smile
> 
> Could you please add a little more information? What version(s) are you using now? Was it indeed fixed in an earlier version but is is back now?

No idea why but I got it after I updated. Right now I'm using MAUI 7.0.59

**Comment by shameelfazul** [comment] 2023-02-07 09:46
> > > I'm a bit confused... It says its fixed but now it's not fixed? sweat_smile
> > > Could you please add a little more information? What version(s) are you using now? Was it indeed fixed in an earlier version but is is back now?
> > 
> > 
> > No idea why but I got it after I updated. Right now I'm using MAUI 7.0.59
> 
> So, the different NavBar colors issue is back? [#10315 (comment)](https://github.com/dotnet/maui/issues/10315#issuecomment-1262049795)

Yes

**Comment by mattleibow** [comment] 2023-02-07 19:32
Duplicate of #10315

**Closed by mattleibow** 2023-02-07 19:32 UTC
Labels: t/bug, platform/android 🤖, i/regression
