### ISSUE TITLE
Connect To Mac - Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by Richard-Dufour** [dotnet/maui#22722] opened 2024-05-29 21:05 UTC
### Description

I saw a similar bug report that has been marked as "Completed" by David. 
The suggestion was to switch to XCode 15.2 as 15.3 is not fully yet supported. 
Ticket was closed right away. 

1) This is still an issue. 
2) Up until yesterday, using XCode 15.3 worked just fine. 
3) Btw, XCode 15.2 has the same issue so this is not a solution.

I don't think XCode is the culprit, I updated to latest VS and all broke loose.

Could we please stop closing ticket prematurely and calling them done when they are actually fixed.

### Steps to Reproduce

1. Try to Pair to Mac from VS 2022 (Windows). 

### Version with bug

9.0.0-preview.2.10293

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

9.0.0-preview.2.10293

### Affected platforms

iOS, Windows, macOS

### Did you find any workaround?

Add the following to the Windows registry and the product check will be skipped.

```
[HKEY_CURRENT_USER\Software\Xamarin\VisualStudio\MacAgent]
"DisableMonoValidation"="True"
```

**Comment by shuffs** [comment] 2024-05-29 23:37
+1

Was working fine all day yesterday. Come in to work this morning and start receiving the object not set error when connecting to the Mac. 

What's the bet it's this again? - https://github.com/dotnet/maui/issues/11954

![pair-to-mac-error](https://github.com/dotnet/maui/assets/12891801/a3a36cc7-6d54-4621-821a-c17c7f908f91)

Yet another frustrating day with MAUI and iOS fixing the tools and not developing. Yay 👍

**Comment by toddlucas** [comment] 2024-05-29 23:43
There are a number of these reports in the Developer Community area for VS. This one appears to have the most votes.

[VS Pair to mac gives Object reference not set to instance of an object](https://developercommunity.visualstudio.com/t/VS-Pair-to-mac-gives-Object-reference-no/10670625)

I attached a VS log snippet to this report.

**Comment by IsaacHayes1995** [comment] 2024-05-29 23:47
+1 getting same issue.

**Comment by theagodDev** [comment] 2024-05-29 23:47
> There are a number of these reports in the Developer Community area for VS. This one appears to have the most votes.
> 
> [VS Pair to mac gives Object reference not set to instance of an object](https://developercommunity.visualstudio.com/t/VS-Pair-to-mac-gives-Object-reference-no/10670625)
> 
> I attached a VS log snippet to this report.

Thanks for that @toddlucas - from your logs it seems it is indeed the service https://software.xamarin.com/service/products is unavailable. I guess all we can do is wait....

**Comment by IsaacHayes1995** [comment] 2024-05-29 23:51
A cursory search suggests this is not the first time this has happened.
I would be interested in what exactly it is trying to get from the URL, and in what format it expects the response, so we could attempt a locally hosted redirect and avoid a dependency on some random server being up to be able to build.

**Comment by rcarde** [comment] 2024-05-30 01:53
> > There are a number of these reports in the Developer Community area for VS. This one appears to have the most votes.
> > [VS Pair to mac gives Object reference not set to instance of an object](https://developercommunity.visualstudio.com/t/VS-Pair-to-mac-gives-Object-reference-no/10670625)
> > I attached a VS log snippet to this report.
> 
> Thanks for that @toddlucas - from your logs it seems it is indeed the service https://software.xamarin.com/service/products is unavailable. I guess all we can do is wait....

No need to wait...  add the following to the registry and the product check will be skipped.

```
[HKEY_CURRENT_USER\Software\Xamarin\VisualStudio\MacAgent]
"DisableMonoValidation"="True"
```

**Comment by IsaacHayes1995** [comment] 2024-05-30 01:56
> > > There are a number of these reports in the Developer Community area for VS. This one appears to have the most votes.
> > > [VS Pair to mac gives Object reference not set to instance of an object](https://developercommunity.visualstudio.com/t/VS-Pair-to-mac-gives-Object-reference-no/10670625)
> > > I attached a VS log snippet to this report.
> > 
> > 
> > Thanks for that @toddlucas - from your logs it seems it is indeed the service https://software.xamarin.com/service/products is unavailable. I guess all we can do is wait....
> 
> No need to wait... add the following to the registry and the product check will be skipped.
> 
> ```
> [HKEY_CURRENT_USER\Software\Xamarin\VisualStudio\MacAgent]
> "DisableMonoValidation"="True"
> ```

Lifesaver, worked instantly!

**Comment by theagodDev** [comment] 2024-05-30 01:57
> > > There are a number of these reports in the Developer Community area for VS. This one appears to have the most votes.
> > > [VS Pair to mac gives Object reference not set to instance of an object](https://developercommunity.visualstudio.com/t/VS-Pair-to-mac-gives-Object-reference-no/10670625)
> > > I attached a VS log snippet to this report.
> > 
> > 
> > Thanks for that @toddlucas - from your logs it seems it is indeed the service https://software.xamarin.com/service/products is unavailable. I guess all we can do is wait....
> 
> No need to wait... add the following to the registry and the product check will be skipped.
> 
> ```
> [HKEY_CURRENT_USER\Software\Xamarin\VisualStudio\MacAgent]
> "DisableMonoValidation"="True"
> ```

Beat me to it. Just discovered this also. Cheers @rcarde!

**Comment by davishoang96** [comment] 2024-05-30 04:24
Same issue. It worked yesterday.

**Comment by pierre01** [comment] 2024-05-30 04:28
Same issue here!

**Comment by rcarde** [comment] 2024-05-30 04:52
> Same issue. It worked yesterday.

https://github.com/dotnet/maui/issues/22722#issuecomment-2138530097

**Comment by rcarde** [comment] 2024-05-30 04:52
> Same issue here!



> Same issue. It worked yesterday.

https://github.com/dotnet/maui/issues/22722#issuecomment-2138530097

**Comment by drchilds** [comment] 2024-05-30 05:22
Every VS update breaks MAUI. Literally. Get it together.

**Comment by drasticactions** [comment] 2024-05-30 07:29
To be clear: This issue has nothing to do with changes within the MAUI UI Framework nor, as far as I can tell, the Xamarin/.NET iOS SDK itself, it's an issue specifically with the Pair To Mac agent (which is owned by Visual Studio, so  https://developercommunity.visualstudio.com/t/VS-Pair-to-mac-gives-Object-reference-no/10670625 would be the right place to upvote this)

The issue is with getting the Mono/iOS version to provision with. The required string it would fetch from the VSMac Update Server, I believe, is not being returned, so a version string is returning as `null`, which then gets `ToString()`ed, causing the null reference exception. It's a server issue with the VSMac Update Server that's causing this cascading issue.

Again, it's NOT a change in MAUI, or the iOS SDK. Changing Xcodes won't do anything. To workaround it, use the registry setting to turn off Mono Validation, which gets around that check.

**Comment by spsuwal** [comment] 2024-05-30 08:18
this  issue  show up exactly same time while Microsoft release  vs 17.10.1  before that it was working fine and testing on app. but suddenly connection failed and error on mac pair.

**Comment by Zhanglirong-Winnie** [comment] 2024-05-30 08:30
Verified this issue with Visual Studio 17.11.0 Preview 1.0(8.0.40). Can repro on iOS platform. We have created a bug to track this issue.
[Bug 2068365](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2068365): [MAUI] Pair to mac failed with error: 'Object reference not set to an instance of an object'

**Comment by drasticactions** [comment] 2024-05-30 08:45
> this issue show up exactly same time while Microsoft release vs 17.10.1 before that it was working fine and testing on app. but suddenly connection failed and error on mac pair.

I am telling you, 100%, it is unrelated to that release, it's just bad timing. 

I can view the source to pair to Mac and I can see the web service it's trying to call that isn't working. You can view it in the pair to Mac logs yourself if you check.

**Comment by navkumar401** [comment] 2024-05-30 10:34
Same issue here. Workaround is doing the job.

**Comment by mackayn** [comment] 2024-05-30 10:38
Workaround definitely for VS2022 17.0.0 Win11 to macOS (Sonoma 15.5, XCode 15.2)....same can't be said for deploying to iPhone but that's another story.

**Comment by wouteroonk** [comment] 2024-05-30 12:47
> > > There are a number of these reports in the Developer Community area for VS. This one appears to have the most votes.
> > > [VS Pair to mac gives Object reference not set to instance of an object](https://developercommunity.visualstudio.com/t/VS-Pair-to-mac-gives-Object-reference-no/10670625)
> > > I attached a VS log snippet to this report.
> > 
> > 
> > Thanks for that @toddlucas - from your logs it seems it is indeed the service https://software.xamarin.com/service/products is unavailable. I guess all we can do is wait....
> 
> No need to wait... add the following to the registry and the product check will be skipped.
> 
> ```
> [HKEY_CURRENT_USER\Software\Xamarin\VisualStudio\MacAgent]
> "DisableMonoValidation"="True"
> ```
> 
> @jfversluis - can you look at that server? @drasticactions ?

This works..... but what a horrible fix....

**Comment by TonyLugg** [comment] 2024-05-30 13:37
The registry hack worked for me, but hopefully this will be fixed soon.

**Comment by Magic73** [comment] 2024-05-30 13:40
Same here, life saver!

**Comment by TonyLugg** [comment] 2024-05-30 14:41
> Same here, life saver!

Make sure you remove the hack once they have fixed their server.

**Comment by ewerspej** [comment] 2024-05-30 15:00
Same here, thanks @rcarde for the workaround. 

These problems need to stop. I know this is not the right place (technically), but MAUI development is seriously impaired by Visual Studio tooling issues and therefore issues are rightfully raised here.

**Comment by Richard-Dufour** [comment] 2024-05-30 15:15
Same here, thanks @rcarde for the workaround.

Pretty much spent an afternoon trying to figure out what the keck was going on. What a waste of time. 

Quality is going down the drain.

**Comment by anton-yashin** [comment] 2024-05-30 15:47
Server is up with content: ```<UpdateInfo/>```

**Comment by mackayn** [comment] 2024-05-30 16:46
> It appears that `https://software.xamarin.com/` went down for some time. The team that watches that has fixed the issue and should be working again.
> 
> If there is still an issue, please comment on https://developercommunity.visualstudio.com/t/VS-Pair-to-mac-gives-Object-reference-no/10670625

Yep, just reverted my registry setting and all good.

**Closed** 2024-05-30 16:45 UTC
Labels: t/bug, platform/macOS 🍏, platform/windows 🪟, platform/iOS 🍎, s/verified, s/triaged

**Comment by navkumar401** [comment] 2024-06-01 05:48
Back to normal, thanks!!!
