### ISSUE TITLE
Wrong button sizing when using CharacterSpacing - MAC

### ISSUE THREAD

**Issue by stoffemi** [dotnet/maui#11265] opened 2022-11-10 17:44 UTC
### Description

The button doesnt get the width it need so the text gets clipped.

### Steps to Reproduce

Create new MAUI App called BugButton

```xaml
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="BugButton.MainPage">

    <ScrollView>
        <VerticalStackLayout
            Spacing="25"
            Padding="30,0"
            VerticalOptions="Center">

            <Button
                Text="Bugged button"
                HorizontalOptions="Center"
                CharacterSpacing="2"
                Padding="20,6"/>

        </VerticalStackLayout>
    </ScrollView>

</ContentPage>
```

### Link to public reproduction project repository

None

### Version with bug

7.0 Release Candidate 2

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

Ventura

### Did you find any workaround?

No

### Relevant log output

```shell
None
```

**Comment by mattleibow** [comment] 2022-11-10 19:43
@stoffemi  are you able to add a screenshot so we can see what you are seeing so we can also make sure that our behaviour is the same as yours.

May be a duplicate of https://github.com/dotnet/maui/issues/10293 depending on the screenshot. @stoffemi  can you check to see if this issue is the same?

**Closed** 2022-11-17 21:01 UTC
Labels: t/bug, platform/macOS 🍏, s/needs-info, area/controls 🎮, control-button, s/no-recent-activity
