### ISSUE TITLE
Entry stays under the Keyboard when focused on iOS on .Net 8 

### ISSUE THREAD

**Issue by polqnaP** [dotnet/maui#18564] opened 2023-11-07 10:29 UTC
### Description

Entries and other input views (f.e.Editors) are translated when focused, however they still stay under the keyboard on iOS.

![MicrosoftTeams-image (11)](https://github.com/dotnet/maui/assets/61967449/2c1b1d4c-4904-4c2c-ba87-b3817e6bf203)

### Steps to Reproduce

1. Run the app on iOS from the link to reproduction project repo.
2. Focus one of the entries.

**Expected**
The entry should be translated over the keyboard. 

**Actual**
The entry is translated, however still stays under the keyboard on iOS.

### Link to public reproduction project repository

https://github.com/telerik/ms-samples/tree/main/Maui/KeyboardAutoManagerScroll_iOS_issue

### Version with bug

8.0.0-rc.2.9373

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

**Comment by jsuarezruiz** [comment] 2023-11-07 12:42
cc @tj-devel709

**Comment by tj-devel709** [comment] 2023-11-07 16:09
Thank you for reporting this bug! I am marking this a duplicate of #18354. Please follow that issue for progress!

**Closed by tj-devel709** 2023-11-07 16:09 UTC
Labels: t/bug, partner, area/controls 🎮, control-entry, area/keyboard
