### ISSUE TITLE
Missing horizontal scrollbar in `ScrollView`

### ISSUE THREAD

**Issue by MartyIX** [dotnet/maui#15953] opened 2023-06-30 20:43 UTC
### Description

I cannot force `ScrollView` to have a horizontal scrollbar.

### Steps to Reproduce

1. See the repro project and especially have a look at the https://github.com/MartyIX/MauiScrollView202306/commit/30aaa46f93dd564b3e8fd11a1f8ea7f2bc3f2c82 commit.
2. Run the project on Windows
3. There is no horizontal scrollbar for the scroll-view: 
    ![image](https://github.com/dotnet/maui/assets/203266/54a513ff-91e3-4550-99cb-e66d9dcad72e)

### Link to public reproduction project repository

https://github.com/MartyIX/MauiScrollView202306

### Version with bug

7.0.86 (I tested 8.0 Preview 5 as well and it looked the same for me)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 11 but I believe it's the same on Windows 10

### Did you find any workaround?

No.

**Comment by drasticactions** [comment] 2023-07-01 04:00
![image](https://github.com/dotnet/maui/assets/898335/bd9f315e-04f8-4a2e-b491-cecae5f16014)

Looking at the live property explorer view of the ScrollViewer (the underlying panel used for the MAUI View), that's set to Disabled for HorizontalScrollBarVisibility, no matter what the MAUI Virtual View is set to.

**Comment by drasticactions** [comment] 2023-07-01 04:17
@MartyIX Figured it out.

![image](https://github.com/dotnet/maui/assets/898335/638ffa00-73a9-4965-8e55-9b5f34ac2ace)

You need to enable `Orientation="Both"` or `Horizontal` for that setting to be respected. Checking on Android and iOS, they both work the same way. It's kind of a weird idiosyncrasy with the API (You may not think you have to opt into that mode when setting that since it implies it will always be on) but as it stands, IMO, this is not a bug.

@hartez What do you think?

**Comment by drasticactions** [comment] 2023-07-05 08:53
@MartyIX I can close it. I want to make sure we talk about the API at some point since IMO it is not very clear what the expected behavior is if you use the value without changing the orientation setting.

**Closed by drasticactions** 2023-07-05 08:53 UTC
Labels: t/bug, layout-scrollview
