### ISSUE TITLE
[Windows]Clicking on Snackbar should not open a new instance of the application

### ISSUE THREAD

**Issue by BaY1251** [dotnet/maui#19003] opened 2023-11-24 09:16 UTC
### Description

When clicking on Snackbar, a new instance of the application should not be opened
 for example, when using WPF, the notification displayed by calling TaskbarIcon.ShowBalloonTip will not open a new instance

### Steps to Reproduce

None

### Link to public reproduction project repository

None

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

**Comment by drasticactions** [comment] 2023-11-24 11:15
This is the default WinUI 3 behavior. WinUI 3 apps are multiple instances by default, allowing you to launch unique instances of the app. There are [ways to disable that](https://github.com/dotnet/maui/issues/9973), and there could be better ways within MAUI to make that more straightforward for how to do it.

**Comment by BaY1251** [comment] 2023-11-27 03:02
Thank you. This solution is a bit strange , I may use a sample Mutex ?!

**Comment by mattleibow** [comment] 2023-11-29 17:57
I created a small sample showing how to make a MAUI app be a single instance: https://github.com/mattleibow/MauiSingleInstanceApp

**Comment by mattleibow** [comment] 2023-11-29 17:57
Duplicate of https://github.com/dotnet/maui/issues/9973

**Closed by mattleibow** 2023-11-29 17:57 UTC
Labels: t/bug, platform/windows 🪟, area/platform

**Comment by BaY1251** [comment] 2023-11-30 05:04
Thank you, its really  a better way
