### ISSUE TITLE
Warning in log about font 

### ISSUE THREAD

**Issue by danies8** [dotnet/maui#19774] opened 2024-01-09 08:21 UTC
### Description

Hi,
1. log4net.config located in resources row.
2. the target path is c drive.
3. the problem error about register font please see 
![image](https://github.com/dotnet/maui/assets/1079689/60216a4b-f0f9-4c17-9c97-e734297a5348)
4.I assume there is some timing issue in maui because the TelerikFont is properly displayed, and the message is saying that the issue is due to the current state of the object (FontRegistrar). I suspect later the state allows getting the font, and no more errors are shown.
I checked, and we are not using this FontRegistrar, so the issue comes somewhere from maui or perhaps WinUI.
5.I attched demo.
[b1850421-c8ea-4190-b1ce-fdd5b60c5123_fourfontupdate.zip](https://github.com/dotnet/maui/files/13870948/b1850421-c8ea-4190-b1ce-fdd5b60c5123_fourfontupdate.zip)

### Steps to Reproduce

I attched demo

### Version with bug

7.0.101

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

..

### Did you find any workaround?

No

### Relevant log output

```shell
No.
```

**Comment by danies8** [comment] 2024-01-09 08:23
1.Run app in net 7.
2. See the log in c drive include error.
3. Telerik said maybe is problem with WINUI.

**Comment by danies8** [comment] 2024-01-09 19:51
@PureWeen is it error not warning

**Comment by jfversluis** [comment] 2024-08-07 09:31
Can't reproduce with the attached sample 
![image](https://github.com/user-attachments/assets/f61dc465-d465-4f6d-8042-6d687143d05a)

Going to assume this is fixed by now.

**Closed by jfversluis** 2024-08-07 09:31 UTC
Labels: t/bug, platform/windows 🪟, area-fonts
