### ISSUE TITLE
ToolbarItems do not work correctly on Windows

### ISSUE THREAD

**Issue by holecekp** [dotnet/maui#11639] opened 2022-11-24 20:46 UTC
### Description

ToolbarItems are completely wrong on windows.

Consider this example with two primary and two secondary toolbar items:
```xml
    <ContentPage.ToolbarItems>
        <ToolbarItem Text="AAA" Order="Primary" />
        <ToolbarItem Text="BBB" Order="Primary" />
        <ToolbarItem Text="CCC" Order="Secondary" />
        <ToolbarItem Text="DDD" Order="Secondary" />
    </ContentPage.ToolbarItems>
```

The primary items are not displayed. Empty buttons without text are displayed instead (see screenshots). Moreover, there is a three dots button that is always displayed (even if there are no secondary items). After clicking on the three dots button, the texts for the primary items suddenly appear. This weird behavior makes primary toolbar items unusable on Windows.

Moreover, secondary items are also displayed incorrectly. When you click on the tree dots icon, a menu is opened but there are no texts inside! The text becomes only temporarily visible when you move mouse over it. The texts for other secondary items are still hidden. This makes also secondary toolbar items unusable on Windows.

The same project is displayed correctly on Android. This is a Windows-only issue.

**Screenshots**
Image 1: Primary items are not shown on Windows. Only empty buttons and a three dots button are displayed instead.
![mauitoolbarbug1](https://user-images.githubusercontent.com/24872113/203859839-80f40e26-637a-484e-ac04-e78d2b3c8c5d.png)

Image 2: Secondary buttons are not displayed correctly on Windows. The texts are invisible. It becomes visible only if you move the mouse over it.
![mauitoolbarbug2](https://user-images.githubusercontent.com/24872113/203859825-015b0e88-e5db-4c71-916f-d9dfecc08cb2.png)

Image 3: The primary toolbar items are displayed correctly on Android (with a slight exception that the three dots icon has a wrong color). A similar behavior is expected for Windows.
![mauitoolbarbugandroid1](https://user-images.githubusercontent.com/24872113/203859954-4f0199ca-a0d4-49f5-a9b9-8c76c625f646.png)

Image 3: The secondary toolbar items are displayed correctly on Android. The same behavior is expected for Windows.
![mauitoolbarbugandroid2](https://user-images.githubusercontent.com/24872113/203859961-f5a6ae7f-bdf1-4d7c-91ef-dc15dd21b90b.png)

### Steps to Reproduce

1. Create a new empty MAUI app and add a toolbar items to any page (or download the repro project https://github.com/holecekp/MauiBugToolbar)
2. Run the project on Windows.
3. You can see that the primary items not displayed correctly. Click on the three dots icon. You can see that the secondary items are also displayed incorrectly.
4. Run the same project on Android. Everything is displayed correctly there.

### Link to public reproduction project repository

https://github.com/holecekp/MauiBugToolbar

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Windows 10

### Did you find any workaround?

No workaround

**Comment by PureWeen** [comment] 2022-11-29 22:59
Duplicate of #7034

**Closed by PureWeen** 2022-11-29 22:59 UTC
Labels: t/bug, platform/windows 🪟, area/toolbar

**Comment by holecekp** [comment] 2022-11-30 06:25
The issue has been closed as a duplicate to another issue. But they are not exactly the same. They covers only partially. The other issue is a feature request that mentions only primary items being hidden inside the 3 dots menu while this issue is a bug report that besides that describes also other aspects of this bug - buttons with no text for primary items, and unusable secondary items with invisible text that becomes visible only when the mouse is moved over it.

What should I do? Should I ignore it, or should I create a new issue that describes only that parts that are not mentioned in [#7034](https://github.com/dotnet/maui/issues/7034) so that it would not be closed as a duplicate?
