### ISSUE TITLE
EmptyView of CarouselView isn't displayed on Android

### ISSUE THREAD

**Issue by AlexeyStarkov** [dotnet/maui#13069] opened 2023-02-01 21:29 UTC
### Description

EmptyView of CarouselView is not displayed on Android whether ItemsSource is null or empty.

Related issue: https://github.com/dotnet/maui/issues/8934

### Steps to Reproduce

1) Add CarouselView to the page and add any view to the EmptyView (ContentView, Grid, whatever)

### Link to public reproduction project repository

https://github.com/AlexeyStarkov/MAUI_CarouselView_EmptyView_issue

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 13

**Comment by jfversluis** [comment] 2023-02-02 09:44
Duplicate of #8934

**Closed by jfversluis** 2023-02-02 09:44 UTC
Labels: t/bug, area/collectionview 📃
