### ISSUE TITLE
Failed to create release build in iOS due to bitcode issue of Plugin.Firebase in .net MAUI having dotnet 7.

### ISSUE THREAD

**Issue by Priyabaghelgithub** [dotnet/maui#13005] opened 2023-01-30 17:57 UTC
### Description

I am facing below issue for GoogleAppMeasurement in iOS when making release build :
C:\Users\abc.nuget\packages\xamarin.firebase.ios.core\8.10.0.3\buildTransitive\Xamarin.Firebase.iOS.Core.tar
gets(216,5): error MSB3073: The command ""$(xcrun -find bitcode_strip)" C:/Users/abc/AppData/Local/XamarinBui
ldDownloadCache/GAppM-8.9.1/GoogleAppMeasurement-8.9.1/Frameworks/GoogleAppMeasurement.xcframework/ios-arm64_armv7/Goog
leAppMeasurement.framework/GoogleAppMeasurement -r -o C:/Users/abc/AppData/Local/XamarinBuildDownloadCache/GA
ppM-8.9.1/GoogleAppMeasurement-8.9.1/Frameworks/GoogleAppMeasurement.xcframework/ios-arm64_armv7/GoogleAppMeasurement.f
ramework/GoogleAppMeasurement" exited with code 1. [D:\iOSNotification\iOSNotification\iOSNotification.csproj::TargetFr
amework=net7.0-ios]

**I have tried the workaround #10989 but still facing below issue for Google Sign In :**
D:\MauiFirebaseDemo-master\MauiFirebaseDemo\MauiFirebaseDemo.csproj(148,3): error MSB3073: The command ""$(xcrun -find
bitcode_strip)" C:/Users/abcd/AppData/Local/XamarinBuildDownloadCache/GSgnI-5.0.2/Frameworks/GoogleSignIn.fram
ework/GoogleSignIn -r -o C:/Users/abcd/AppData/Local/XamarinBuildDownloadCache/GSgnI-5.0.2/Frameworks/GoogleSi
gnIn.framework/GoogleSignIn" exited with code 1. [TargetFramework=net7.0-ios]

### Steps to Reproduce

Have implemented fcm push notification in MAUI having .net version 7 from the below link : https://cedricgabrang.medium.com/firebase-push-notifications-in-net-maui-ios-2f4388bf1ac

For testing , creating release build On iOS to test on physical device but unable to create build because facing bitcode issue.

### Link to public reproduction project repository

https://github.com/cedricgabrang/MauiFirebaseDemo

### Version with bug

7.0 (current)

### Last version that worked well

6.0.424

### Affected platforms

iOS

### Affected platform versions

iOS16

**Comment by Priyabaghelgithub** [comment] 2023-01-30 18:13
@jfversluis @jamesmontemagno 
#12863 
#12631

**Comment by jfversluis** [comment] 2023-01-30 19:53
Duplicate of #12863

**Closed by jfversluis** 2023-01-30 19:53 UTC
Labels: t/bug
