### ISSUE TITLE
VoiceOver doesn't navigate to items contained in a CollectionView which has a SemanticProperties.Description set

### ISSUE THREAD

**Issue by gbarkerz** [dotnet/maui#7114] opened 2022-05-12 20:39 UTC
### Description

I created a new MAUI app in Visual Studio Community 2022 V 17.2.0 Preview 6.0, and Microsoft.Maui.Dependencies/Extensions 6.0.300-rc.2.5513. I then added a CollectionView based on demo code at https://docs.microsoft.com/en-us/dotnet/maui/user-interface/controls/collectionview/layout. The app code is public at https://github.com/gbarkerz/MyMauiAppAccessibility. 

Both the CollectionView and the item template have SemanticProperties.Description set.

When the app is run, and VoiceOver navigates forward through the UI, it encounters the CollectionView, but does not navigate to the contained items. The image below shows the VoiceOver highlight at the CollectionView, and its caption shows the description of the CollectionView.

IMPORTANT: If the  SemanticProperties.Description is removed from the CollectionView, then VoiceOver can navigate to the contained items. But to fully convey the semantics of the UI, both the CollectionView and items need descriptions.

![BA9A4143-F8E1-4E89-B079-EDDF1B1442BA](https://user-images.githubusercontent.com/77085891/168162989-970936c8-ecce-4560-962f-93b10e10be54.jpeg)

### Steps to Reproduce

1. Create a new MAUI app in Visual Studio Community 2022 V 17.2.0 Preview 6.0, and Microsoft.Maui.Dependencies/Extensions 6.0.300-rc.2.5513.
2. Add a CollectionView based on demo code at https://docs.microsoft.com/en-us/dotnet/maui/user-interface/controls/collectionview/layout, and set SemanticProperties.Description on both the CollectionView and the items.
3. Run the app, navigate VoiceOver through the UI, and note that VoiceOver does not navigate to the items in the CollectionView.

### Version with bug

Release Candidate 2

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15

**Comment by NiharikaTipirishetty** [comment] 2022-09-15 11:43
GitHubTags:
#.NET MAUI; #A11ySev1; #A11yMAS; #A11yTCS; #Benchmark; #DesktopApp; #Win11; #WCAG2.1.1; #GH_.NETMAUI_IOS_Mar2022; #AILimited​; #Win32; #Keyboard;

**Comment by PureWeen** [comment] 2022-09-27 15:19
@gbarkerz this is by design on iOS. With iOS any containers marked with a description won't be internally reachable. 

I've created a new issue to track a different path here
https://github.com/dotnet/maui/issues/10347

Can we close this issue and go an alternative route?

**Closed** 2022-09-27 21:46 UTC
Labels: t/bug, area/a11y
