### ISSUE TITLE
Binding BackgroundColor on Button not propagate when changed in Release .NET MAUI MVVM (Android device)

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#13772] opened 2023-03-08 18:45 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Binding-BackgroundColor-on-Button-not-pr/10288030)._

---
[severity:It's more difficult to complete my work]
Hello,
I have an issue with binding on .NET MAUI Button property BackgroundColor, when I change the value - binding works fine on Debug, but stops working on Release with Android 11 device.

https://aka.ms/dc/file?name=B786b9ef357e645cf982c2f3d42354b45638128283964579267_MauiColorTest.zip&tid=786b9ef357e645cf982c2f3d42354b45638128283964579267

**Comment by mattleibow** [comment] 2023-03-08 19:12
Duplicate of #10181

**Closed by mattleibow** 2023-03-08 19:12 UTC
