### ISSUE TITLE
When checked on, switch in table view button in ViewCell is invisible in Android Platform

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#13006] opened 2023-01-30 18:53 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/When-checked-on-switch-in-table-view-but/10250361)._

---
When checked on switch in table view button in ViewCell is invisible in Android Platform

### Repro

```XAML

<TableView Margin="7" HasUnevenRows="True">
	<TableRoot>
		<TableSection>
			<ImageCell ImageSource="ha.png" Text="Hassouna Academy" />
		</TableSection>
		<TableSection Title="Section 1">
			<EntryCell />
			<SwitchCell/>
			<TextCell x:Name="txt" Text="Hello" />
		</TableSection>
		<TableSection>
			<ViewCell Height="150">
				<Button Text="OK" Clicked="Button_Clicked" Margin="1" />
			</ViewCell>
		</TableSection>
	</TableRoot>
</TableView>
```

| Before | After |
| :-: | :-: |
| ![image](https://user-images.githubusercontent.com/1096616/217632746-2f00ccd3-4188-471f-a669-db15e85f8231.png) | ![image](https://user-images.githubusercontent.com/1096616/217632800-58430461-f0a4-4e62-8f94-cdd720ff7ad1.png) |

**Comment by Zhanglirong-Winnie** [comment] 2023-06-28 08:37
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 2.0. Can repro on android platform with adove cade.
![13006](https://github.com/dotnet/maui/assets/77434865/183a9691-292d-46c6-a574-45ba46d4f043)

**Comment by PureWeen** [comment] 2023-12-12 20:25
Duplicate of #5924

**Closed by PureWeen** 2023-12-12 20:25 UTC
Labels: t/bug, platform/android 🤖, area/ListView, s/verified, s/triaged
