### ISSUE TITLE
Clear data on Android app will remove all DLLs and stops the app from running

### ISSUE THREAD

**Issue by rbakhshi** [dotnet/maui#2749] opened 2021-09-29 06:24 UTC
### clearing storage of a MAUI app will stop it from running

Note: I am assuming this is a bug based on what I expect from "Clear storage" functionality.

### Steps to Reproduce

1. Run the default app
2. close the app and open app info
3. Clear storage (not the cache)
4. Start the app

### Expected Behavior
The app should start normally if compared to other native android apps.

### Actual Behavior
The app gets stuck on splash screen in a restart loop

### Basic Information

- Version with issue: MAUI preview 8
- Last known good version: N/A
- IDE: VS2022
- Platform Target Frameworks: 
  - iOS:  
  - Android: API 29
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Workaround
Not that I know of

**Comment by hartez** [comment] 2022-01-05 23:02
Duplicate of #1787

**Closed by hartez** 2022-01-05 23:02 UTC
Labels: t/bug, platform/android 🤖
