### ISSUE TITLE
[.NET 8 & VS 17.8.0] XAML Live Preview- Showing component boundaries does not work

### ISSUE THREAD

**Issue by cropyai** [dotnet/maui#18873] opened 2023-11-18 18:10 UTC
### Description

[.NET 8 & VS 17.8.0]

Hi, I upgraded my project from .NET 7 to .NET 8 and then XAML Live preview didn't not work as intended. When the mouse is over on a component, the layout of the component is not shown, and no component is clickable. Thus, I cannot select a component or see the layout. However, for new projects in .NET 8, XAML preview works well.

![image](https://github.com/dotnet/maui/assets/122940429/3623969b-0651-4bfd-9c38-e280f3e6c16d)

### Steps to Reproduce

-> Run the existing project
-> XAML preview does not work as intended.

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

**Comment by drasticactions** [comment] 2023-11-18 23:59
Are you using Shell? Because there's a known issue for that, https://github.com/dotnet/maui/issues/17677

**Comment by cropyai** [comment] 2023-11-19 00:32
@drasticactions I am not sure what you mean by shell. However, I can say that I am using navigation like this:

```
await Navigation.PushAsync(new FirstPage(), false);
```

and app shell:
```
<Shell
    x:Class="MauiApp5.AppShell"
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:local="clr-namespace:MauiApp5"
    Shell.FlyoutBehavior="Disabled">
    
    <ShellContent
        ContentTemplate="{DataTemplate local:MainPage}"
        Route="MainPage" />
    

</Shell>
```

**Comment by drasticactions** [comment] 2023-11-19 01:45
Yep, you're using Shell. This is a known issue,

duplicate of https://github.com/dotnet/maui/issues/17677

**Closed by drasticactions** 2023-11-19 01:45 UTC
Labels: t/bug, s/needs-attention
