### ISSUE TITLE
MAUI DatePicker: Event "DateSelected" only triggered when date changes

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#16007] opened 2023-07-05 16:32 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/MAUI-DatePicker:-Event-DateSelected-on/10397782)._

---
[severity:Other]
I have a DatePicker and added the event "DateSelected" but this only works when the user changes the date...
I think there may be a misunderstanding here, because it is supposed to be a DateSelected event and not a DateChanged event.

To reproduce this bug, you just need to create a DatePicker and add the DateSelected event, add a breakpoint and try it out. It only works when the user changes the date.

I need this because the DatePicker doesn't support a nullable DateTime so I created a new component that supports a nullable one.

---
#### Feedback Bot on 6/24/2023, 08:14 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by PureWeen** [comment] 2023-07-05 18:48
Duplicate of #13156

**Closed by PureWeen** 2023-07-05 18:48 UTC
Labels: t/bug, area/controls 🎮
