### ISSUE TITLE
Entry, Date Picker Control Unfocused Event Not Executing

### ISSUE THREAD

**Issue by mistrypragnesh40** [dotnet/maui#8099] opened 2022-06-16 05:55 UTC
### Description

  In Xamarin Forms, Unfocused event is working fine, I am just facing issue with .NET MAUI. 

1. Entry Control Unfocused event is not executing on keyboard dismissal or Tapping on  screen area.
2. Date Picker:  After selecting date from date picker dialog, Unfocused event is not executing.

### Steps to Reproduce

 1)Create New MAUI Project.
 2) Add Entry and DatePicker Control on MainPage.
 ```
<Entry Focused="Entry_Focused" Placeholder="Text" Unfocused="Entry_Unfocused" />
  <DatePicker Focused="DatePicker_Focused" Unfocused="DatePicker_Unfocused" />
```
 4)Add debug point on Unfocused Event of Entry & DatePicker, You will observe It's not triggering.

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

Android, iOS

**Comment by jfversluis** [comment] 2022-06-16 08:49
Duplicate of #6933

**Closed by jfversluis** 2022-06-16 08:49 UTC
Labels: t/bug, s/needs-verification
