### ISSUE TITLE
Building for Android fails because iOS SDK is missing

### ISSUE THREAD

**Issue by hypdeb** [dotnet/maui#16146] opened 2023-07-13 17:03 UTC
### Description

I have a docker container set up to build for Android like below:
```
FROM mcr.microsoft.com/dotnet/sdk:8.0.100-preview.6

RUN apt update && apt install android-sdk gpg -y
ENV ANDROID_SDK_ROOT=/usr/lib/android-sdk
ENV PATH=$PATH:$ANDROID_SDK_ROOT/tools:$ANDROID_SDK_ROOT/platform-tools
RUN wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
RUN unzip commandlinetools-linux-9477386_latest.zip
RUN mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
RUN mv cmdline-tools $ANDROID_SDK_ROOT/cmdline-tools/latest
ENV PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin
RUN yes | sdkmanager --licenses
RUN sdkmanager "platforms;android-33" "build-tools;33.0.0"

RUN wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg
RUN install -o root -g root -m 644 packages.microsoft.gpg /etc/apt/trusted.gpg.d/
RUN wget -q https://packages.microsoft.com/config/debian/9/prod.list -O /etc/apt/sources.list.d/microsoft-prod.list
RUN apt-get install apt-transport-https && apt-get update && apt-get install msopenjdk-11 -y
RUN update-java-alternatives --set msopenjdk-11-amd64

RUN dotnet workload install maui-android
```
But when I try to build a project like this:
```
dotnet publish App.App/App.App.csproj -f net8.0-android -c Release -r android-arm64
```
I get the following:
```
The project depends on the following workload packs that do not exist in any of the workloads available in this installation: Microsoft.ios.Sdk.net8
```

### Steps to Reproduce

1. Build the image from the dockerfile above and name it
```
docker build . -f dockerfile -t builder:latest
```
2. Create the template MAUI project in the container
```
docker run -it builder:latest /bin/sh
dotnet new maui -n Test
```
Try to publish:
```
dotnet publish Test/Test.csproj -f net8.0-android -c Release -r android-arm64
```

### Link to public reproduction project repository

Not needed, uses template

### Version with bug

8.0.0-preview.5.8529

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11 and up

**Comment by akoeplinger** [comment] 2023-07-14 08:57
Can you please try removing the `net8.0-ios` entry from TargetFrameworks in the csproj?

**Comment by hypdeb** [comment] 2023-07-14 12:24
Removing `net8.0-ios` works, but that's only a workaround. Otherwise it means I would need multiple project files for multiple platforms and that defeats the purpose of `MAUI` entirely.

**Comment by mattleibow** [comment] 2023-07-14 12:31
There is always a way with msbuild!

In the template there should be a line to filter windows:

```xml
<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net8.0-windows10.0.19041.0</TargetFrameworks>
```

If you split the android and the rest, you can do

```xml
<TargetFrameworks>net8.0-android</TargetFrameworks>
<TargetFrameworks Condition="!$([MSBuild]::IsOSPlatform('linux'))">$(TargetFrameworks);net8.0-ios;net8.0-maccatalyst</TargetFrameworks>
<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net8.0-windows10.0.19041.0</TargetFrameworks>
```

I did type this on my phone so there may be a typo, but this demos the idea.

**Comment by Ghostbird** [comment] 2023-07-14 12:38
I think this is a duplicate of #14088

**Comment by mattleibow** [comment] 2023-07-14 14:11
Thanks @Ghostbird !

**Comment by mattleibow** [comment] 2023-07-14 14:11
Duplicate of #14088

**Comment by hypdeb** [comment] 2023-07-14 14:12
I would assume passing `-f net8.0-android` to the `publish` should be enough to not required `iOS` SDK. Why does it require changes to the project file ?

**Closed** 2023-07-14 14:12 UTC
Labels: t/bug, platform/android 🤖

**Comment by mattleibow** [comment] 2023-07-14 14:13
I think it is because it can select the target framework it has to parse and evaluate the csproj. And that is the step that is failing.
