### ISSUE TITLE
i am using windows 10 and see me this error (dotnet maui-check)

### ISSUE THREAD

**Issue by Divyeshpatel6073** [dotnet/maui#770] opened 2021-04-17 04:28 UTC
![image](https://user-images.githubusercontent.com/20996843/115101619-574a5500-9f63-11eb-8fa8-cd92f3e30bb4.png)

**Comment by Divyeshpatel6073** [comment] 2021-04-17 04:48
Where can I find a review error?

**Comment by sps014** [comment] 2021-04-17 20:10
Hi, 
This may be possible duplicate of https://github.com/Redth/dotnet-maui-check/issues/16

**Comment by Divyeshpatel6073** [comment] 2021-04-18 10:46
Thank you @sps014

**Comment by hartez** [comment] 2021-04-19 16:34
@Divyeshpatel6073 Since your problem has been solved, I'm closing this issue.

**Closed by hartez** 2021-04-19 16:34 UTC
