### ISSUE TITLE
Permissions.CheckStatusAsync not working first time

### ISSUE THREAD

**Issue by nk-alex** [dotnet/maui#23035] opened 2024-06-13 10:48 UTC
### Description

Unable to ask for permissions first time application starts. I have no problems second time.

### Steps to Reproduce
I'm using Prism environment.

On my PrismStartup:
`builder.RegisterTypes(RegisterTypes).OnAppStart("MainPage");`

On my MainPageViewModel:
```
public async override void OnNavigatedTo(INavigationParameters parameters)
{
 			try
			{
#if ANDROID
				await Platform.WaitForActivityAsync();
#endif

				var status = await Permissions.CheckStatusAsync<Permissions.LocationWhenInUse>();

				if (status != PermissionStatus.Granted)
				{
					await Permissions.RequestAsync<Permissions.LocationWhenInUse>();
				}

				status = await Permissions.CheckStatusAsync<Permissions.PostNotifications>();

				if (status != PermissionStatus.Granted)
				{
					await Permissions.RequestAsync<Permissions.PostNotifications>();
				}
			}

			catch (Exception ex)
			{
				var tmp = ex;
			}
}
```

Returns me:

On Android:
Unable to add window -- token android.os.BinderProxy@419ad6d is not valid; is your activity running?

On iOS:
Working as expected

### Version with bug

8.0.21 SR4.1

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

android 21

**Comment by jonmdev** [comment] 2024-06-17 01:24
This is probably not a bug from the way you are describing it. Maui's page says:

https://learn.microsoft.com/en-us/dotnet/maui/platform-integration/appmodel/permissions?view=net-maui-8.0&tabs=android

>Permissions shouldn't be requested from your MauiProgram or App class, and should only be requested once the first page of the app has appeared.

Your error suggests the app is not up and running yet. Try asking from a loaded page (eg. a button click).

**Comment by Amenti** [comment] 2024-06-26 15:22
@jonmdev @nk-alex I also see this behaviour. On Android a restart of the app is necessary before the permission can be used, on iOS it works as expected.

**Comment by QianaJiao** [comment] 2024-09-13 06:07
Hi @nk-alex, Could you share me a repo, I'd like to verify if that is still repro now.

**Comment by QianaJiao** [comment] 2024-09-13 08:48
@nk-alex Glad to know that your issue has been solved, I will close this bug if there are no other questions.
If you have any further questions, you could submit a new one. 
Thank you for your reply.

**Closed by QianaJiao** 2024-09-13 08:48 UTC
Labels: t/bug, platform/android 🤖, area-essentials
