### ISSUE TITLE
Button is not adapting to theme changes if IsEnabled is changed

### ISSUE THREAD

**Issue by pekspro** [dotnet/maui#9220] opened 2022-08-05 18:18 UTC
### Description

If `IsEnabled` is changed on a button, this button will not adapt to theme changes.

### Steps to Reproduce

1. Create a new MAUI application.
2. Update the MainPage.xaml file: 
``` XAML
    <ScrollView>
        <VerticalStackLayout>
            <HorizontalStackLayout>
                <Button 
                    x:Name="DarkButtom"
                    Text="Dark theme"
                    Clicked="DarkButtom_Clicked"
                    />

                <Button 
                    x:Name="LightButtom"
                    Text="Light theme"
                    Clicked="LightButtom_Clicked"
                    />
            </HorizontalStackLayout>

            <Label Text="Sample buttons:" />
            <Button Text="Button one" />
            <Button Text="Button two" x:Name="ButtonTwo" IsEnabled="False"/>
        </VerticalStackLayout>
    </ScrollView>
```
3. Update MainPage.xaml.cs:

``` C#
	public MainPage()
	{
		InitializeComponent();
	}

	protected async override void OnNavigatedTo(NavigatedToEventArgs args)
	{
		base.OnNavigatedTo(args);

		await Task.Delay(1000);
		ButtonTwo.IsEnabled = true;
    }

	private void DarkButtom_Clicked(object sender, EventArgs e)
	{
		App.Current.UserAppTheme = AppTheme.Dark;
	}

	private void LightButtom_Clicked(object sender, EventArgs e)
	{
		App.Current.UserAppTheme = AppTheme.Light;
	}
```
4. Start the application. It will look like this:

![image](https://user-images.githubusercontent.com/3163293/183137151-319387ce-5197-4b99-b564-181f46641ba2.png)

5. Press the Dark theme button. Now it will look like this:

![image](https://user-images.githubusercontent.com/3163293/183137248-1042477b-b4a2-4165-bf33-7284c9f00f6b.png)

6. Button One and Two should have the same styling, but Button Two hasn't changed the theme.

Full repro: https://github.com/pekspro/MauiIssues/tree/9220_Button_is_not_adapting_to_theme_changes

### Version with bug

6.0.408 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Windows 10.0.17763.0

**Comment by MagicAndre1981** [comment] 2022-08-08 21:02
Duplicate of https://github.com/dotnet/maui/issues/7377

**Comment by pekspro** [comment] 2022-11-11 17:40
I've updated sample application to .NET 7. The same issue remains. It is also an issue on Android.

**Comment by hartez** [comment] 2023-02-03 21:27
This is not a duplicate of #7377. As best as I can tell, the problem is that when the VSM applies the "Normal" state to the Button, it's setting the resolved property values for TextColor/BackgroundColor rather than setting them to the AppThemeBindings. At that point, the links to the theme bindings are lost.

**Comment by Zhanglirong-Winnie** [comment] 2023-05-18 08:39
Verified this issue with Visual Studio Enterprise 17.6.0 Preview 7.0. Not repro on android and windows platform with sample project.
[MauiIssues-9220_Button_is_not_adapting_to_theme_changes.zip](https://github.com/dotnet/maui/files/11506010/MauiIssues-9220_Button_is_not_adapting_to_theme_changes.zip)
![Android](https://github.com/dotnet/maui/assets/77434865/7ba45428-ca90-45de-aee2-9184d324f917)

**Closed** 2023-05-25 13:03 UTC
Labels: t/bug, platform/windows 🪟, area/controls 🎮, control-button, s/triaged, s/try-latest-version, area/theme
