### ISSUE TITLE
Entry/Editor Unfocused event is not triggering

### ISSUE THREAD

**Issue by AarthiArjunan** [dotnet/maui#24028] opened 2024-08-06 07:52 UTC
### Description

The `Entry` unfocused event does not trigger when clicking outside of the `Entry/Editor` on the page itself. Additionally, clicking on another control, such as a button, does not cause the `Entry` to unfocus.

### Steps to Reproduce

1. Create a new .NET MAUI app project
2. Add an Entry or Editor control
3. Add something to handle the Unfocused event
4. Run the app and make sure the Entry or Editor has focus
5. Click the "Count" button 
6. Observe that the method attached to the Unfocused event does not get called

### Link to public reproduction project repository

https://github.com/AarthiArjunan/Entry-Unfocus-Issue

### Version with bug

8.0.71 SR7.1

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Did you find any workaround?

No

**Comment by ninachen03** [comment] 2024-08-06 08:40
I can repro this issue at Maccatalyst platform on the latest VSCode: 1.92.0 (8.0.70 & 8.0.71).

**Comment by jfversluis** [comment] 2024-08-06 10:19
Duplicate of #23901

**Closed by jfversluis** 2024-08-06 10:19 UTC
Labels: t/bug, s/verified, s/triaged
