### ISSUE TITLE
[Bug] Java.Interop version issue in Android

### ISSUE THREAD

**Issue by ElliottBrand** [dotnet/maui#3389] opened 2021-11-15 04:43 UTC
I was working on trying to get push notifications working in a MAUI Blazor Android app, but I'm unable to add the Xamarin.GooglePlayServices.Base NuGet package. When I attempted to build the solution, I received an error that basically states that Xamarin.GooglePlayServices.Base Assembly uses 'Java.Interop, Version=0.1.2.0' and has a higher version than the referenced assembly 'Java.Interop' with identity 'Java.Interop, Version=0.1.0.0' 

When I look up the assembly location that's mentioned in my MAUI Blazor project ```Project > Dependencies > Frameworks > Microsoft.Android > Java.Interop``` and view the Properties, it shows the path as ```C:\Program Files\dotnet\packs\Microsoft.Android.Ref\31.0.101-preview.10.59\ref\net6.0\Java.Interop.dll```.  If I open the directory in File Explorer, it shows the file version as 0.1.0.0. 

I'm assuming Java.Interop should be updated to version ```0.1.2.0``` ?

**Comment by ElliottBrand** [comment] 2021-11-15 22:37
I see a new version of Xamarin.GooglePlayServices.Base was released last night (went from 117.6.0.1 to 117.6.0.2) and it seems to have stopped the build error about the wrong Java.Interop version....however, now I'm receiving 35 errors related to packages not existing.

```error: package com.google.android.gms.common.api.GoogleApiClient does not exist```
```error: package com.google.android.gms.commong.api.internal does not exist```
```error: package com.google.android.gms.common does not exist```
etc...

At this point, I'm not sure if this is still somehow related to the Java.Interop.dll, SDK, or what?  I assume all of these should have been provided in the Xamarin.GooglePlayServices.Base NuGet package?

**Comment by gianox** [comment] 2021-11-25 09:41
Hi Elliott, did you figure out a workaround for this issue? I need this package to setup my google-services.json correctly in the android project and I am getting the same 35 errors.

**Comment by ElliottBrand** [comment] 2021-11-25 20:40
Sorry, I haven't got it working.  I've been dealing with multiple issues in MAUI Blazor and just moved onto others for a while, hoping the bug gets fixed. It seems multiple .java files are running into issues. For example, the error that states ```package com.google.android.gms.common.api.GoogleApiClient does not exist``` is being thrown in GoogleApiClientConnectionCallbacksImpl.java on the 5th line of this code

```java
public class GoogleApiClientConnectionCallbacksImpl
	extends java.lang.Object
	implements
		mono.android.IGCUserPeer,
		com.google.android.gms.common.api.GoogleApiClient.ConnectionCallbacks,
		com.google.android.gms.common.api.internal.ConnectionCallbacks
{
...
}
```

It just seems like it's unable to find GoogleApiClient.

**Comment by ElliottBrand** [comment] 2021-11-25 22:10
I was able to come up with a patch to at least get this to build properly and stop throwing the "does not exist" errors. Here's what I did:

- First, go add a new folder to the Android Platform in your MAUI project and call it "lib".
- Then browse to your local nuget packages folder (where your nuget packages are downloaded to). This will reside in your user folder at ```C:\Users\UserNameHere\.nuget\packages.``` You're likely going to need the following dll files from xamarin.googleplayservices.base, xamarin.googleplayservices.basement, and xamarin.googleplayservices.tasks. Yours may very depending on package version, but here are the paths to mine:
- >C:\Users\steve\.nuget\packages\xamarin.googleplayservices.base\117.6.0.2\lib\monoandroid90\Xamarin.GooglePlayServices.Base.dll
- >C:\Users\steve\.nuget\packages\xamarin.googleplayservices.basement\117.6.0.3\lib\monoandroid90\Xamarin.GooglePlayServices.Basement.dll
- >C:\Users\steve\.nuget\packages\xamarin.googleplayservices.tasks\117.2.1.2\lib\monoandroid90\Xamarin.GooglePlayServices.Tasks.dll
- Copy each of these dll files into the "lib" folder you created in your MAUI project at Platforms > Android > lib
- Now you'll just need to add the reference to the .csproj file and it should build.

```xml
  <ItemGroup Condition="'$(TargetFramework)' == 'net6.0-android'">
	  <Reference Include="Xamarin.GooglePlayServices.Base">
		  <HintPath>Platforms\Android\lib\Xamarin.GooglePlayServices.Base.dll</HintPath>
	  </Reference>
	  <Reference Include="Xamarin.GooglePlayServices.Basement">
		  <HintPath>Platforms\Android\lib\Xamarin.GooglePlayServices.Basement.dll</HintPath>
	  </Reference>
	  <Reference Include="Xamarin.GooglePlayServices.Tasks">
		  <HintPath>Platforms\Android\lib\Xamarin.GooglePlayServices.Tasks.dll</HintPath>
	  </Reference>
  </ItemGroup>
```

**Comment by ElliottBrand** [comment] 2021-11-27 23:25
The temporary solution I've ended up implementing was to revert my nuget packages back to a version that didn't include "net6.0-android31.0" in the package lib folder. So, I ended up going back to version 117.6.0 - [https://www.nuget.org/packages/Xamarin.GooglePlayServices.Base/117.6.0](https://www.nuget.org/packages/Xamarin.GooglePlayServices.Base/117.6.0) If you visit the link, you can view the contents by clicking "Open in NuGet Package Explorer" on the right. 

Starting at 117.6.0.1, the "net6.0-android31.0" .dll is included and my app/Visual Studio 2022 (_17.1.0 Preview 1.1_) isn't able to run it without a bunch of java errors.

I am also using Firebase Messaging and had to revert back to version 122.0.0 for the same reason as I mentioned above.

**Comment by gianox** [comment] 2021-11-29 09:19
> The temporary solution I've ended up implementing was to revert these affected nuget packages back to a version that didn't include "net6.0-android31.0" in the package lib folder. So, I ended up going back to version 117.6.0 - https://www.nuget.org/packages/Xamarin.GooglePlayServices.Base/117.6.0 If you visit the link, you can view the contents by clicking "Open in NuGet Package Explorer" on the right.
> 
> Starting at 117.6.0.1, the "net6.0-android31.0" .dll is included and my app/Visual Studio 2022 (_17.1.0 Preview 1.1_) isn't able to run it without a bunch of java errors.
> 
> I am also using Firebase Messaging and had to revert back to version 122.0.0 for the same reason as I mentioned above.

Workaround confirmed, but with the addition of adding Xamarin.Google.Dagger - nice work.

My next issue is that Plugin.LocalNotification wont actually show the notification in MAUI, but I can confirm that the notifications are received thanks to your discoveries.

**Comment by ionoy** [comment] 2021-12-06 07:58
I also had this problem and the workaround worked in my case. Thanks, @ElliottBrand! Hope this gets fixed officially.

**Comment by erosnemesis** [comment] 2021-12-07 06:01
I had a similar problem but with Xamarin.Firebase.Auth and Xamarin.Firebase.Messaging. I finally got it compiling after downgrading Xamarin.Firebase.Auth to 121.0.1.1 and Xamarin.Firebase.Messaging to 122.0.0. Thanks for the tips :)

**Comment by VincentBu** [comment] 2022-03-09 08:03
verified for android, get the similar error message:
```
Description
 error: package com.google.android.gms.common.api.GoogleApiClient does not exist
 error: package com.google.android.gms.common.api.internal does not exist
 error: package com.google.android.gms.common.api.GoogleApiClient does not exist
 error: package com.google.android.gms.common.api.internal does not exist
 error: package com.google.android.gms.common does not exist
 error: package com.google.android.gms.common does not exist
 error: package com.google.android.gms.common.api does not exist
 error: package com.google.android.gms.common.api does not exist
 error: package com.google.android.gms.common.api does not exist
 error: package com.google.android.gms.common.api does not exist
 error: package com.google.android.gms.common.api does not exist
 error: package com.google.android.gms.common.api does not exist
 error: package com.google.android.gms.tasks does not exist
 error: package com.google.android.gms.tasks does not exist
 error: package com.google.android.gms.tasks does not exist
 error: package com.google.android.gms.common.api.PendingResult does not exist
 error: package com.google.android.gms.common.api does not exist
 error: package com.google.android.gms.common.api does not exist
 error: package com.google.android.gms.common.api.internal.BackgroundDetector does not exist
 error: package com.google.android.gms.common.api.internal does not exist
 error: package com.google.android.gms.common does not exist
 error: package com.google.android.gms.common does not exist
 error: package com.google.android.gms.common.api.internal does not exist
 error: package com.google.android.gms.common.images.ImageManager does not exist
 error: package com.google.android.gms.dynamic does not exist
 error: package com.google.android.gms.dynamic does not exist
 error: package com.google.android.gms.dynamic does not exist
 error: package com.google.android.gms.security.ProviderInstaller does not exist
 error: package com.google.android.gms.tasks does not exist
 error: package com.google.android.gms.tasks does not exist
 error: package com.google.android.gms.tasks does not exist
 error: package com.google.android.gms.tasks does not exist
 error: package com.google.android.gms.tasks does not exist
 error: package com.google.android.gms.tasks does not exist
 error: package com.google.android.gms.tasks does not exist
```

**Comment by jonathanpeppers** [comment] 2022-04-21 13:50
This is duplicate of: https://github.com/dotnet/maui/issues/4276#issuecomment-1104464449

I believe you can install Xamarin.GooglePlayServices.Base 117.6.0.5 or higher and the problem is solved. Let us know otherwise, thanks!

**Closed by jonathanpeppers** 2022-04-21 13:50 UTC
Labels: t/bug, platform/android 🤖, s/verified, area/upstream
