### ISSUE TITLE
[Windows] Shell FlyoutIcon doesn't change the hamburger Icon for Flyout

### ISSUE THREAD

**Issue by DeanFaizal** [dotnet/maui#7667] opened 2022-06-01 15:01 UTC
### Description

Setting FlyoutIcon on Shell doesn't change the hamburger icon based on this [documentation](https://docs.microsoft.com/en-us/dotnet/maui/fundamentals/shell/flyout#flyout-icon)

Code I'm using:
```
<?xml version="1.0" encoding="UTF-8" ?>
<Shell
    x:Class="MauiAppShellJune22.AppShell"
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:local="clr-namespace:MauiAppShellJune22"
    FlyoutIcon="dotnet_bot.png"
    Shell.FlyoutBehavior="Flyout">
    <FlyoutItem Title="One" FlyoutIcon="dotnet_bot.png">
        <ShellContent
            Title="One"
            ContentTemplate="{DataTemplate local:MainPage}"
            Route="OnePage" />
    </FlyoutItem>
    <FlyoutItem Title="Two" FlyoutIcon="dotnet_bot.png">
        <ShellContent
            Title="Two"
            ContentTemplate="{DataTemplate local:MainPage}"
            Route="TwoPage" />
    </FlyoutItem>
</Shell>
```

![image](https://user-images.githubusercontent.com/2334530/171435564-508ee35f-b29d-46cb-bb5c-ce4fe3706f6a.png)

### Steps to Reproduce

1. Create a File > New MAUI app
2. Set FlyoutIcon to dotnet_bot.png

Expected: Flyout icon is set to the dotnet bot
Actual: Flyout icon is still the hamburger

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

net6.0-windows10.0.19041.0

### Did you find any workaround?

No

**Comment by kristinx0211** [comment] 2022-06-02 05:54
verified repro on windows and android 12 using above code with vs 17.3.0 Preview 2.0 [32601.361.main].

**Comment by MisinformedDNA** [comment] 2022-08-01 21:48
I discover this issue while going through [MS Learn content](https://docs.microsoft.com/en-us/learn/modules/create-multi-page-apps/3-exercise-implement-flyout-navigation).

**Comment by UchiTesting** [comment] 2022-08-06 13:14
I confirm I'm going through the MAUI Learning path too and I meet that behaviour.

```xml
<?xml version="1.0" encoding="UTF-8" ?>
<Shell
    x:Class="Astronomy.AppShell"
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:local="clr-namespace:Astronomy.Pages"
    FlyoutIcon="{StaticResource lightMoon}">

    <Shell.Resources>
        <ResourceDictionary>
            <FileImageSource x:Key="darkMoon">moon.png</FileImageSource>
            <FileImageSource x:Key="lightMoon">moon_white.png</FileImageSource>
            
            <OnPlatform x:Key="moonIcon" x:TypeArguments="FileImageSource">
                <On Platform="WinUI" Value="{StaticResource lightMoon}"/>
                <On Platform="Android, iOS" Value="{StaticResource darkMoon}" />
            </OnPlatform>
            
            <Style x:Key="moonPhaseFlyItemStyle" TargetType="FlyoutItem">
                <Setter Property="FlyoutIcon" Value="{StaticResource moonIcon}" />
            </Style>
        </ResourceDictionary>
    </Shell.Resources>

    <FlyoutItem Title="Moon Phase" Style="{StaticResource moonPhaseFlyItemStyle}"> 
        <ShellContent
            ContentTemplate="{DataTemplate local:MoonPhasePage}"/>
    </FlyoutItem>

</Shell>
```

OnPlatform works accordingly
![image](https://user-images.githubusercontent.com/56003633/183250334-f9be880c-761d-45ec-8946-75dbee2589bc.png)

But the `FlyoutIcon` does not work for WinUI

![image](https://user-images.githubusercontent.com/56003633/183250400-7e50abd4-eb08-46fc-9363-0732e314a9ef.png)

**Comment by Cornan** [comment] 2022-08-17 18:49
Still in effect 8/17/22 - in mslearn content, building with VS Preview 17.4 now.

Please advise if there is a "me, too" button / mechanism that I should have used instead of comment.

**Comment by DevDotStudio** [comment] 2022-08-29 20:48
Still not working in vs release edition 17.3.2 also FlyoutBackgroundImage does not work.

**Comment by Ruddy2007** [comment] 2022-10-05 14:52
I am also seeing this issue.

**Comment by obenyaala** [comment] 2022-10-06 07:52
What I also noticed is, setting the Foreground does not work on Android.

**Comment by PureWeen** [comment] 2022-11-30 20:49
Duplicate of #7577

**Closed by PureWeen** 2022-11-30 20:49 UTC
Labels: t/bug, platform/windows 🪟, area/shell 🐢, s/verified
