### ISSUE TITLE
[iOS] Hardware keyboard in FormSheet disturbs content sizing

### ISSUE THREAD

**Issue by Mittchel** [dotnet/maui#19245] opened 2023-12-06 08:46 UTC
### Description

When using a FormSheet on iOS in combination with a hardware keyboard the content gets pushed down upon Entry focus. Seems like the contentsizing doesn't work properly in this situation. Tested on iPad 10th Generation in simulator.

![ReproFormSheet](https://github.com/dotnet/maui/assets/1458641/ffe10650-b9c8-4550-92d3-2576fb749f83)

### Steps to Reproduce

1. Run the reproduction project on iPad 10th Generation in Simulator (landscape)
2. Make sure Hardware keyboard is toggled on in Simulator: (I/O > Keyboard > Connect Hardware Keyboard)
3. Focus the Entry field
4. Notice content gets pushed down

### Link to public reproduction project repository

https://github.com/Mittchel/FormSheetSample

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS17, iOS 16.4

### Did you find any workaround?

Didn't find a workaround yet, scrollview doesn't seem to help. Currently stepped away from FormSheets to mitigate the issue.

**Comment by tj-devel709** [comment] 2023-12-06 19:28
I'll try to repro this! The MCT Popup fix in [this PR](https://github.com/dotnet/maui/pull/17670) may help this issue, but I will check.

**Comment by tj-devel709** [comment] 2023-12-07 19:46
https://github.com/dotnet/maui/assets/50846373/89158772-3a5b-4cca-90ef-4f55b4317f61

I was able to reproduce your issue! I also tested it using the changes in [this PR](https://github.com/dotnet/maui/pull/17670) and it seems to be working well!

**Comment by Mittchel** [comment] 2023-12-08 19:29
> iPadKeyboardPopupDemo.mov 
> I was able to reproduce your issue! I also tested it using the changes in [this PR](https://github.com/dotnet/maui/pull/17670) and it seems to be working well!

Awesome @tj-devel709 thank you for taking the time to dive into this! I wonder how many people are using formsheets since I didn't see a lot of issues or other questions on it. 

@tj-devel709 do you expect the fix would be in the next release or is that too soon? Thanks again!

**Comment by tj-devel709** [comment] 2023-12-12 16:45
Of course! The goal will be to get this fix in for the SR2 release! 

Also in the meantime, you could call something like this to disable the keyboard scrolling for iOS!

```cs
using Microsoft.Maui.Platform;

namespace FormSheetSample;

public partial class App : Application
{
	public App()
	{
		InitializeComponent();

		MainPage = new AppShell();
	}

	override protected void OnStart()
	{
#if __IOS__
		KeyboardAutoManagerScroll.Disconnect();
#endif
	}
}


```

**Comment by tj-devel709** [comment] 2023-12-12 16:46
I'll close this issue for now, but definitely feel free to open it back up if the issue is not fixed in SR2.

**Comment by tj-devel709** [comment] 2023-12-12 16:47
Actually sorry, I'll leave it open until that PR lands!

**Closed** 2024-01-12 13:42 UTC
Labels: t/bug, area/navigation 🧭, platform/iOS 🍎, p/1
