### ISSUE TITLE
Base64 string image source not working on iOS

### ISSUE THREAD

**Issue by vasile135** [dotnet/maui#12379] opened 2023-01-02 16:21 UTC
### Description

The image with base64 string source is displayed on Android, not displayed on iOS.

### Steps to Reproduce

1. Added a property in the view model and assigned a base64 image string to it:
`public string Base64Source { get; set; } = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAbAAAADzCAYAAADn9UNcAAAAAXNSR0IArs4c..."`
2. Added the image in xaml:
`<Image Source="{Binding Base64Source}"/>`
3. Started the application on Android - the image is displayed.
4. Started the same application on iOS - the image isn't displayed.
5. As a walkaround tried to use stream:
`public static string Base64Source { get; set; } = "iVBORw0KGgoAAAANSUhEUgAAAbAAAADzCAYAA..."`
`public ImageSource StreamSource { get; set; } = ImageSource.FromStream(() => new MemoryStream(System.Convert.FromBase64String(Base64Source)));`
In xaml:
`<Image Source="{Binding StreamSource}"/>`
Same thing, working on Android, not working on iOS.
6. Also tried to set the source in code behind- same issue;

### Link to public reproduction project repository

https://github.com/vasile135/MAUI_iOS_Image_Issue.git

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

16.1

**Comment by nebula2** [comment] 2023-01-03 12:46
also does not work on .net 6

**Comment by mattleibow** [comment] 2023-01-03 19:35
Duplicate of #12020

**Closed by mattleibow** 2023-01-03 19:35 UTC
Labels: t/bug, platform/iOS 🍎, area/image :framed_picture:
