### ISSUE TITLE
CollectionView with header template  throw exception on android.

### ISSUE THREAD

**Issue by singhwong** [dotnet/maui#5415] opened 2022-03-18 11:17 UTC
### Description

On Android, if you use CollectionView with header template, when you switch back to the page, the following exception will be thrown.
`Java.Lang.IllegalStateException: 'The specified child already has a parent. You must call removeView() on the child's parent first.'
`
Don't have the exception on WinUI, haven't tested it on ios and maccatalyst.

### Steps to Reproduce

1. Download and run the example.
2. Switch page：FirstPage->SecondPage->FirstPage->SecondPage.
3. When switch back to "SecondPage" for the second time, an exception will be thrown.
[MauiAppTest14.zip](https://github.com/dotnet/maui/files/8303969/MauiAppTest14.zip)

### Version with bug

Preview 14 (current)

### Last version that worked well

Preview 13

### Affected platforms

Android

### Affected platform versions

Android 11

**Comment by jfversluis** [comment] 2022-03-18 11:31
Duplicate of #5332

**Comment by jfversluis** [comment] 2022-03-18 11:31
Please follow the progress of this issue in the linked URL and add any additional details you might have, thanks!

**Closed by jfversluis** 2022-03-18 11:31 UTC
Labels: t/bug, s/needs-verification
