### ISSUE TITLE
Pair to Mac suddenly failing: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by Forestbrook** [dotnet/maui#11957] opened 2022-12-08 11:12 UTC
### Description

This morning Pair to Mac is suddenly not working anymore and fails with the message 'Object reference not set to an instance of an object.'

I did not update the tools or anything on my Mac.
I even get the same error when using another computer AND another Mac
I also tried with a fresh Maui .NET7 and .NET6 project, all the same error.
Restarting Visual Studio, My computer or my Mac does not help.

Tried with:
- VS 2022 enterprise v17.4.2
- VS 2022 enterprise v17.5.0 Preview 1.0

### Steps to Reproduce

1. Open a .NET Maui project
2. Choose Pair to Mac and Connect
3. Logging in to the Mac succeeds
4. Connection fails with error message: Object reference not set to an instance of an object.

### Link to public reproduction project repository

n/a

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

MacOS 12.6.1, XCode v14.1

### Did you find any workaround?

No

### Relevant log output

```shell
Checking host configuration for connecting to 'MacMarcel'...
Checking SSH configuration...
Initializing environment...
Checking available disk space...
Checking Mono installation...
Checking host configuration for connecting to 'MacMarcel'...
Starting disconnection from MacMarcel...
Starting disconnection from MacMarcel...
The connection to 'MacMarcel' has been finished
Object reference not set to an instance of an object.
```

**Comment by jfversluis** [comment] 2022-12-08 11:50
Duplicate of #11954

**Closed by jfversluis** 2022-12-08 11:50 UTC
Labels: t/bug

**Comment by Forestbrook** [comment] 2022-12-08 14:46
Problem solved, turned out to be Xamarin server issue. See https://developercommunity.visualstudio.com/t/Unable-to-connect-to-mac---XamarinMessa/10224702#T-N10225594
