### ISSUE TITLE
error CS0234: The type or namespace name 'Compatibility' does not exist in the namespace 'Microsoft.Maui.Controls.Platform'

### ISSUE THREAD

**Issue by williambuchanan2** [dotnet/maui#20565] opened 2024-02-14 04:45 UTC
### Description

This morning all our Maui builds started failing in Azure Devops build pipelines with the above error.

From what I can see there were no code changes.

Builds fine on local PC and Macbook, so this appears to be only happening in Devops.

Edit: I received an update for VS For Mac today. After installing this update the problem is now happening on there as well. I don't have the 'use prerelease' option checked but for some reason it looks like it is using prerelease versions.

### Steps to Reproduce

Create a build pipeline in devops
Run pipeline

### Link to public reproduction project repository

N/A

### Version with bug

8.0.3 GA

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.3 GA

### Affected platforms

iOS

### Affected platform versions

iOS

### Did you find any workaround?

No

### Relevant log output

```shell
/Users/runner/work/1/s/NetCore/Client/REDSIX/Platforms/iOS/BadgeShellItemRenderer.cs(4,40): error CS0234: The type or namespace name 'Compatibility' does not exist in the namespace 'Microsoft.Maui.Controls.Platform' (are you missing an assembly reference?) [/Users/runner/work/1/s/NetCore/Client/REDSIX/PDS.App.RedSix.csproj::TargetFramework=net8.0-ios]
/Users/runner/work/1/s/NetCore/Client/REDSIX/Platforms/iOS/BadgeShellRenderer.cs(2,40): error CS0234: The type or namespace name 'Compatibility' does not exist in the namespace 'Microsoft.Maui.Controls.Handlers' (are you missing an assembly reference?) [/Users/runner/work/1/s/NetCore/Client/REDSIX/PDS.App.RedSix.csproj::TargetFramework=net8.0-ios]
/Users/runner/work/1/s/NetCore/Client/REDSIX/Platforms/iOS/BadgeShellRenderer.cs(3,40): error CS0234: The type or namespace name 'Compatibility' does not exist in the namespace 'Microsoft.Maui.Controls.Platform' (are you missing an assembly reference?) [/Users/runner/work/1/s/NetCore/Client/REDSIX/PDS.App.RedSix.csproj::TargetFramework=net8.0-ios]
/Users/runner/work/1/s/NetCore/Client/REDSIX/Platforms/iOS/AppDelegate.cs(14,32): error CS0246: The type or namespace name 'MauiUIApplicationDelegate' could not be found (are you missing a using directive or an assembly reference?) [/Users/runner/work/1/s/NetCore/Client/REDSIX/PDS.App.RedSix.csproj::TargetFramework=net8.0-ios]
/Users/runner/work/1/s/NetCore/Client/REDSIX/Platforms/iOS/AppDelegate.cs(14,59): error CS0535: 'AppDelegate' does not implement interface member 'INativeObject.Handle' [/Users/runner/work/1/s/NetCore/Client/REDSIX/PDS.App.RedSix.csproj::TargetFramework=net8.0-ios]
/Users/runner/work/1/s/NetCore/Client/REDSIX/Platforms/iOS/AppDelegate.cs(14,59): error CS0535: 'AppDelegate' does not implement interface member 'IDisposable.Dispose()' [/Users/runner/work/1/s/NetCore/Client/REDSIX/PDS.App.RedSix.csproj::TargetFramework=net8.0-ios]
/Users/runner/work/1/s/NetCore/Client/REDSIX/Platforms/iOS/BadgeShellItemRenderer.cs(16,43): error CS0246: The type or namespace name 'ShellItemRenderer' could not be found (are you missing a using directive or an assembly reference?) [/Users/runner/work/1/s/NetCore/Client/REDSIX/PDS.App.RedSix.csproj::TargetFramework=net8.0-ios]
/Users/runner/work/1/s/NetCore/Client/REDSIX/Platforms/iOS/BadgeShellItemRenderer.cs(43,39): error CS0246: The type or namespace name 'IShellContext' could not be found (are you missing a using directive or an assembly reference?) [/Users/runner/work/1/s/NetCore/Client/REDSIX/PDS.App.RedSix.csproj::TargetFramework=net8.0-ios]
/Users/runner/work/1/s/NetCore/Client/REDSIX/Platforms/iOS/BadgeShellRenderer.cs(7,39): error CS0246: The type or namespace name 'ShellRenderer' could not be found (are you missing a using directive or an assembly reference?) [/Users/runner/work/1/s/NetCore/Client/REDSIX/PDS.App.RedSix.csproj::TargetFramework=net8.0-ios]
/Users/runner/work/1/s/NetCore/Client/REDSIX/Platforms/iOS/BadgeShellRenderer.cs(12,28): error CS0246: The type or namespace name 'IShellItemRenderer' could not be found (are you missing a using directive or an assembly reference?) [/Users/runner/work/1/s/NetCore/Client/REDSIX/PDS.App.RedSix.csproj::TargetFramework=net8.0-ios]
```

**Comment by DDHSchmidt** [comment] 2024-02-14 11:10
We're witnessing the same errors in our iOS pipeline. The same pipeline with unchanged sources built just fine on Monday but is throwing these errors today.

As a further hint: Our build step "Workload install" which consists of the command
`dotnet workload install ios maui --source https://api.nuget.org/v3/index.json`
now produces the following output:

```
Welcome to .NET 8.0!
---------------------
SDK Version: 8.0.200
[...snip...]
Installing pack Microsoft.Maui.Controls.Core version 8.0.0-rc.1.9171...
```

The output on Monday was:

```
Welcome to .NET 8.0!
---------------------
SDK Version: 8.0.101
[...snip...]
Installing pack Microsoft.Maui.Controls.Core version 8.0.3...
```

Looks like .Net 8 workloads are suddenly aligned with RC1 packs?

**Comment by bkaankose** [comment] 2024-02-14 12:18
8.0.200 also broke some stuff in our iOS pipeline since yesterday. We are having message similar to this

```
'GetIconUIImageAsync' returns the preview type 'UIView' and therefore needs to opt into preview features.
'GetIconUIImageAsync' takes in a preview parameter of type 'CGRect' and needs to opt into preview features.
Using 'BackgroundColor' requires opting into preview features.
Using 'BorderColor' requires opting into preview features.
Using 'Layer' requires opting into preview features.
Using 'CGColor' requires opting into preview features.
Using 'ClipsToBounds' requires opting into preview features.
Using 'BorderStyle' requires opting into preview features.
Using 'None' requires opting into preview features.
Using 'CornerRadius' requires opting into preview features.
Using 'Layer' requires opting into preview features.
Using 'MasksToBounds' requires opting into preview features.
Using 'Layer' requires opting into preview features.
Using 'BorderWidth' requires opting into preview features.
Using 'Layer' requires opting into preview features.
Using 'UIView' requires opting into preview features.
Using 'CGRect' requires opting into preview features.
Using 'Height' requires opting into preview features.
Using 'Frame' requires opting into preview features.
Using 'LeftView' requires opting into preview features.
```

It was working fine for **8.0.101**. Putting them here since they might be related the issue you are describing.

**Comment by TiberiusDRAIG** [comment] 2024-02-14 13:39
Same issue here - our MacCatalyst builds suddenly started failing on DevOps following the release of `8.0.200`. For now, I've used the `UseDotNet@2` task to install `8.0.101` (previously we always took latest with `8.0.x` as the version parameter). 

The YAML we were using to install, in case it's useful, is as follows:

```
- task: UseDotNet@2
  displayName: Install .NET 
  inputs:
    packageType: 'sdk'
    version: '8.0.101'
    includePreviewVersions: true

- task: PowerShell@2
  displayName: Install .NET Tools
  inputs: 
    targetType: inline
    script: |
      & dotnet nuget locals all --clear;
      & dotnet workload install maui-maccatalyst;
      & dotnet tool install JetBrains.dotCover.GlobalTool -g; 
```

Where we ask for `8.0.101` we used to ask for `8.0.x`.

**Comment by skha83** [comment] 2024-02-14 14:07
As mentioned previous in this thread, it seems like the MAUI workloads included with the new Visual Studio 2022 17.9 is correct which is why local builds work

```
Installed Workload Id      Manifest Version       Installation Source
-------------------------------------------------------------------------------------
maui-windows               8.0.6/8.0.100          VS 17.9.34321.82, VS 17.9.34607.119
maccatalyst                17.2.8004/8.0.100      VS 17.9.34321.82, VS 17.9.34607.119
ios                        17.2.8004/8.0.100      VS 17.9.34321.82, VS 17.9.34607.119
android                    34.0.52/8.0.100        VS 17.9.34321.82, VS 17.9.34607.119
```

It is only when installing the MAUI workload directly in a command line during a pipeline build the wrong packages are resolved maybe due to wrong manifests somewhere, it is both MAUI, Android and iOS packages where 8.0.0-RC1 packages are being installed. This is the output when a MAUI workload is installed on the following version of the windows-2022 Azure runner image '20240211.1.0' with this command "dotnet workload install maui". Before this the .NET 8.0.2 SDK was installed.
<details>


```
##[section]Starting: Install Maui Workload
==============================================================================
Task         : Command line
Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
Version      : 2.231.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
==============================================================================
Generating script.
Script contents: shell
dotnet workload install maui
========================== Starting Command Output ===========================
##[command]"C:\Windows\system32\cmd.exe" /D /E:ON /V:OFF /S /C "CALL "D:\a\_temp\ac334ca0-d3f9-4e96-a8ab-a08a5da21749.cmd""

Installing workload manifest microsoft.net.sdk.aspire version 8.0.0-preview.3.24105.21...
Installing pack Microsoft.AspNetCore.Components.WebView.Maui version 8.0.0-rc.1.9171...
Writing workload pack installation record for Microsoft.AspNetCore.Components.WebView.Maui version 8.0.0-rc.1.9171...
Installing pack Microsoft.Maui.Sdk version 8.0.0-rc.1.9171...
Writing workload pack installation record for Microsoft.Maui.Sdk.net8 version 8.0.0-rc.1.9171...
Installing pack Microsoft.Maui.Sdk version 7.0.92...
Writing workload pack installation record for Microsoft.Maui.Sdk.net7 version 7.0.92...
Installing pack Microsoft.Maui.Graphics version 8.0.0-rc.1.9171...
Writing workload pack installation record for Microsoft.Maui.Graphics version 8.0.0-rc.1.9171...
Installing pack Microsoft.Maui.Resizetizer version 8.0.0-rc.1.9171...
Writing workload pack installation record for Microsoft.Maui.Resizetizer version 8.0.0-rc.1.9171...
Installing pack Microsoft.Maui.Resizetizer.Sdk version 7.0.92...
Writing workload pack installation record for Microsoft.Maui.Resizetizer.Sdk version 7.0.92...
Installing pack Microsoft.Maui.Templates.net8 version 8.0.0-rc.1.9171...
Writing workload pack installation record for Microsoft.Maui.Templates.net8 version 8.0.0-rc.1.9171...
Installing pack Microsoft.Maui.Templates.net7 version 7.0.92...
Writing workload pack installation record for Microsoft.Maui.Templates.net7 version 7.0.92...
Installing pack Microsoft.Maui.Core version 8.0.0-rc.1.9171...
Writing workload pack installation record for Microsoft.Maui.Core version 8.0.0-rc.1.9171...
Installing pack Microsoft.Maui.Controls version 8.0.0-rc.1.9171...
Writing workload pack installation record for Microsoft.Maui.Controls version 8.0.0-rc.1.9171...
Installing pack Microsoft.Maui.Controls.Build.Tasks version 8.0.0-rc.1.9171...
Writing workload pack installation record for Microsoft.Maui.Controls.Build.Tasks version 8.0.0-rc.1.9171...
Installing pack Microsoft.Maui.Controls.Core version 8.0.0-rc.1.9171...
Writing workload pack installation record for Microsoft.Maui.Controls.Core version 8.0.0-rc.1.9171...
Installing pack Microsoft.Maui.Controls.Xaml version 8.0.0-rc.1.9171...
Writing workload pack installation record for Microsoft.Maui.Controls.Xaml version 8.0.0-rc.1.9171...
Installing pack Microsoft.Maui.Controls.Compatibility version 8.0.0-rc.1.9171...
Writing workload pack installation record for Microsoft.Maui.Controls.Compatibility version 8.0.0-rc.1.9171...
Installing pack Microsoft.Maui.Essentials version 8.0.0-rc.1.9171...
Writing workload pack installation record for Microsoft.Maui.Essentials version 8.0.0-rc.1.9171...
Installing pack Microsoft.Android.Sdk.Windows version 34.0.0-rc.1.432...
Writing workload pack installation record for Microsoft.Android.Sdk.net8 version 34.0.0-rc.1.432...
Installing pack Microsoft.Android.Sdk.Windows version 33.0.68...
Writing workload pack installation record for Microsoft.Android.Sdk.net7 version 33.0.68...
Installing pack Microsoft.Android.Ref.34 version 34.0.0-rc.1.432...
Writing workload pack installation record for Microsoft.Android.Ref.34 version 34.0.0-rc.1.432...
Installing pack Microsoft.Android.Runtime.34.android-arm version 34.0.0-rc.1.432...
Writing workload pack installation record for Microsoft.Android.Runtime.34.android-arm version 34.0.0-rc.1.432...
Installing pack Microsoft.Android.Runtime.34.android-arm64 version 34.0.0-rc.1.432...
Writing workload pack installation record for Microsoft.Android.Runtime.34.android-arm64 version 34.0.0-rc.1.432...
Installing pack Microsoft.Android.Runtime.34.android-x86 version 34.0.0-rc.1.432...
Writing workload pack installation record for Microsoft.Android.Runtime.34.android-x86 version 34.0.0-rc.1.432...
Installing pack Microsoft.Android.Runtime.34.android-x64 version 34.0.0-rc.1.432...
Writing workload pack installation record for Microsoft.Android.Runtime.34.android-x64 version 34.0.0-rc.1.432...
Installing pack Microsoft.Android.Templates version 34.0.0-rc.1.432...
Writing workload pack installation record for Microsoft.Android.Templates version 34.0.0-rc.1.432...
Installing pack Microsoft.NETCore.App.Runtime.Mono.android-arm version 7.0.16...
Writing workload pack installation record for Microsoft.NETCore.App.Runtime.Mono.net7.android-arm version 7.0.16...
Installing pack Microsoft.NETCore.App.Runtime.Mono.android-arm64 version 7.0.16...
Writing workload pack installation record for Microsoft.NETCore.App.Runtime.Mono.net7.android-arm64 version 7.0.16...
Installing pack Microsoft.NETCore.App.Runtime.Mono.android-x64 version 7.0.16...
Writing workload pack installation record for Microsoft.NETCore.App.Runtime.Mono.net7.android-x64 version 7.0.16...
Installing pack Microsoft.NETCore.App.Runtime.Mono.android-x86 version 7.0.16...
Writing workload pack installation record for Microsoft.NETCore.App.Runtime.Mono.net7.android-x86 version 7.0.16...
Installing pack Microsoft.NET.Runtime.MonoAOTCompiler.Task version 7.0.16...
Writing workload pack installation record for Microsoft.NET.Runtime.MonoAOTCompiler.Task.net7 version 7.0.16...
Installing pack Microsoft.NET.Runtime.MonoTargets.Sdk version 7.0.16...
Writing workload pack installation record for Microsoft.NET.Runtime.MonoTargets.Sdk.net7 version 7.0.16...
Installing pack Microsoft.NETCore.App.Runtime.AOT.win-x64.Cross.android-x86 version 7.0.16...
Writing workload pack installation record for Microsoft.NETCore.App.Runtime.AOT.Cross.net7.android-x86 version 7.0.16...
Installing pack Microsoft.NETCore.App.Runtime.AOT.win-x64.Cross.android-x64 version 7.0.16...
Writing workload pack installation record for Microsoft.NETCore.App.Runtime.AOT.Cross.net7.android-x64 version 7.0.16...
Installing pack Microsoft.NETCore.App.Runtime.AOT.win-x64.Cross.android-arm version 7.0.16...
Writing workload pack installation record for Microsoft.NETCore.App.Runtime.AOT.Cross.net7.android-arm version 7.0.16...
Installing pack Microsoft.NETCore.App.Runtime.AOT.win-x64.Cross.android-arm64 version 7.0.16...
Writing workload pack installation record for Microsoft.NETCore.App.Runtime.AOT.Cross.net7.android-arm64 version 7.0.16...
Installing pack Microsoft.NETCore.App.Runtime.Mono.android-arm version 8.0.2...
Writing workload pack installation record for Microsoft.NETCore.App.Runtime.Mono.android-arm version 8.0.2...
Installing pack Microsoft.NETCore.App.Runtime.Mono.android-arm64 version 8.0.2...
Writing workload pack installation record for Microsoft.NETCore.App.Runtime.Mono.android-arm64 version 8.0.2...
Installing pack Microsoft.NETCore.App.Runtime.Mono.android-x64 version 8.0.2...
Writing workload pack installation record for Microsoft.NETCore.App.Runtime.Mono.android-x64 version 8.0.2...
Installing pack Microsoft.NETCore.App.Runtime.Mono.android-x86 version 8.0.2...
Writing workload pack installation record for Microsoft.NETCore.App.Runtime.Mono.android-x86 version 8.0.2...
Installing pack Microsoft.NET.Runtime.MonoAOTCompiler.Task version 8.0.2...
Writing workload pack installation record for Microsoft.NET.Runtime.MonoAOTCompiler.Task version 8.0.2...
Installing pack Microsoft.NET.Runtime.MonoTargets.Sdk version 8.0.2...
Writing workload pack installation record for Microsoft.NET.Runtime.MonoTargets.Sdk version 8.0.2...
Installing pack Microsoft.NETCore.App.Runtime.AOT.win-x64.Cross.android-x86 version 8.0.2...
Writing workload pack installation record for Microsoft.NETCore.App.Runtime.AOT.Cross.android-x86 version 8.0.2...
Installing pack Microsoft.NETCore.App.Runtime.AOT.win-x64.Cross.android-x64 version 8.0.2...
Writing workload pack installation record for Microsoft.NETCore.App.Runtime.AOT.Cross.android-x64 version 8.0.2...
Installing pack Microsoft.NETCore.App.Runtime.AOT.win-x64.Cross.android-arm version 8.0.2...
Writing workload pack installation record for Microsoft.NETCore.App.Runtime.AOT.Cross.android-arm version 8.0.2...
Installing pack Microsoft.NETCore.App.Runtime.AOT.win-x64.Cross.android-arm64 version 8.0.2...
Writing workload pack installation record for Microsoft.NETCore.App.Runtime.AOT.Cross.android-arm64 version 8.0.2...
Installing pack Microsoft.iOS.Sdk version 16.4.8825-net8-rc1...
Writing workload pack installation record for Microsoft.iOS.Sdk.net8 version 16.4.8825-net8-rc1...
Installing pack Microsoft.iOS.Sdk version 16.4.7099...
Writing workload pack installation record for Microsoft.iOS.Sdk.net7 version 16.4.7099...
Installing pack Microsoft.iOS.Windows.Sdk version 16.4.8825-net8-rc1...
Writing workload pack installation record for Microsoft.iOS.Windows.Sdk.Aliased.net8 version 16.4.8825-net8-rc1...
Installing pack Microsoft.iOS.Windows.Sdk version 16.4.7099...
Writing workload pack installation record for Microsoft.iOS.Windows.Sdk.Aliased.net7 version 16.4.7099...
Installing pack Microsoft.iOS.Ref version 16.4.8825-net8-rc1...
Writing workload pack installation record for Microsoft.iOS.Ref version 16.4.8825-net8-rc1...
Installing pack Microsoft.iOS.Runtime.ios-arm64 version 16.4.8825-net8-rc1...
Writing workload pack installation record for Microsoft.iOS.Runtime.ios-arm64 version 16.4.8825-net8-rc1...
Installing pack Microsoft.iOS.Runtime.iossimulator-x64 version 16.4.8825-net8-rc1...
Writing workload pack installation record for Microsoft.iOS.Runtime.iossimulator-x64 version 16.4.8825-net8-rc1...
Installing pack Microsoft.iOS.Runtime.iossimulator-arm64 version 16.4.8825-net8-rc1...
Writing workload pack installation record for Microsoft.iOS.Runtime.iossimulator-arm64 version 16.4.8825-net8-rc1...
Installing pack Microsoft.iOS.Templates version 16.4.8825-net8-rc1...
Writing workload pack installation record for Microsoft.iOS.Templates.net8 version 16.4.8825-net8-rc1...
Installing pack Microsoft.NETCore.App.Runtime.Mono.ios-arm64 version 8.0.2...
Writing workload pack installation record for Microsoft.NETCore.App.Runtime.Mono.ios-arm64 version 8.0.2...
Installing pack Microsoft.NETCore.App.Runtime.Mono.iossimulator-arm64 version 8.0.2...
Writing workload pack installation record for Microsoft.NETCore.App.Runtime.Mono.iossimulator-arm64 version 8.0.2...
Installing pack Microsoft.NETCore.App.Runtime.Mono.iossimulator-x64 version 8.0.2...
Writing workload pack installation record for Microsoft.NETCore.App.Runtime.Mono.iossimulator-x64 version 8.0.2...
Installing pack Microsoft.NETCore.App.Runtime.Mono.ios-arm version 7.0.16...
Writing workload pack installation record for Microsoft.NETCore.App.Runtime.Mono.net7.ios-arm version 7.0.16...
Installing pack Microsoft.NETCore.App.Runtime.Mono.ios-arm64 version 7.0.16...
Writing workload pack installation record for Microsoft.NETCore.App.Runtime.Mono.net7.ios-arm64 version 7.0.16...
Installing pack Microsoft.NETCore.App.Runtime.Mono.iossimulator-arm64 version 7.0.16...
Writing workload pack installation record for Microsoft.NETCore.App.Runtime.Mono.net7.iossimulator-arm64 version 7.0.16...
Installing pack Microsoft.NETCore.App.Runtime.Mono.iossimulator-x64 version 7.0.16...
Writing workload pack installation record for Microsoft.NETCore.App.Runtime.Mono.net7.iossimulator-x64 version 7.0.16...
Installing pack Microsoft.NETCore.App.Runtime.Mono.iossimulator-x86 version 7.0.16...
Writing workload pack installation record for Microsoft.NETCore.App.Runtime.Mono.net7.iossimulator-x86 version 7.0.16...
Installing pack Microsoft.MacCatalyst.Sdk version 16.4.8825-net8-rc1...
Writing workload pack installation record for Microsoft.MacCatalyst.Sdk.net8 version 16.4.8825-net8-rc1...
Installing pack Microsoft.MacCatalyst.Sdk version 16.4.7099...
Writing workload pack installation record for Microsoft.MacCatalyst.Sdk.net7 version 16.4.7099...
Installing pack Microsoft.MacCatalyst.Ref version 16.4.8825-net8-rc1...
Writing workload pack installation record for Microsoft.MacCatalyst.Ref version 16.4.8825-net8-rc1...
Installing pack Microsoft.MacCatalyst.Runtime.maccatalyst-x64 version 16.4.8825-net8-rc1...
Writing workload pack installation record for Microsoft.MacCatalyst.Runtime.maccatalyst-x64 version 16.4.8825-net8-rc1...
Installing pack Microsoft.MacCatalyst.Runtime.maccatalyst-arm64 version 16.4.8825-net8-rc1...
Writing workload pack installation record for Microsoft.MacCatalyst.Runtime.maccatalyst-arm64 version 16.4.8825-net8-rc1...
Installing pack Microsoft.MacCatalyst.Templates version 16.4.8825-net8-rc1...
Writing workload pack installation record for Microsoft.MacCatalyst.Templates.net8 version 16.4.8825-net8-rc1...
Installing pack Microsoft.NETCore.App.Runtime.Mono.maccatalyst-arm64 version 8.0.2...
Writing workload pack installation record for Microsoft.NETCore.App.Runtime.Mono.maccatalyst-arm64 version 8.0.2...
Installing pack Microsoft.NETCore.App.Runtime.Mono.maccatalyst-x64 version 8.0.2...
Writing workload pack installation record for Microsoft.NETCore.App.Runtime.Mono.maccatalyst-x64 version 8.0.2...
Installing pack Microsoft.NETCore.App.Runtime.Mono.maccatalyst-arm64 version 7.0.16...
Writing workload pack installation record for Microsoft.NETCore.App.Runtime.Mono.net7.maccatalyst-arm64 version 7.0.16...
Installing pack Microsoft.NETCore.App.Runtime.Mono.maccatalyst-x64 version 7.0.16...
Writing workload pack installation record for Microsoft.NETCore.App.Runtime.Mono.net7.maccatalyst-x64 version 7.0.16...
Installing pack Microsoft.Maui.Graphics.Win2D.WinUI.Desktop version 8.0.0-rc.1.9171...
Writing workload pack installation record for Microsoft.Maui.Graphics.Windows version 8.0.0-rc.1.9171...
Garbage collecting for SDK feature band(s) 8.0.200...

Successfully installed workload(s) maui.

##[section]Finishing: Install Maui Workload
```
</details>

It would be nice if someone from the .NET team acknowledged they are aware of the problem, so we are not left in the dark as it is pretty critical that all MAUI build pipelines will either fail or build with old .NET versions unless versions are hardcoded in your build pipeline.

**Comment by bengavin** [comment] 2024-02-14 18:23
Looking at my local ~/.dotnet folder, the 8.0.200 'AdvertisedManifestFeatureBand.txt' file in microsoft.dotnet.sdk.maui is still saying 8.0.101 [looks like the same is true for many of the other workloads as well].  Not sure if this is part of the issue or not, but throwing my hat in the ring of people who are now broken after the latest update.  Local builds work just fine, even from the command line, DevOps agent builds fail.  Looking at our build logs, it looks like all three platforms [iOS, Android and Windows] are having the same workload install problem, but only iOS is erroring out.

I've also updated our iOS build to use Xcode 15.2, but that didn't resolve anything either.

**Comment by domneedham** [comment] 2024-02-14 18:35
Just to add that I am seeing this issue locally after updating VS for Mac, dotnet and dotnet workloads. 

For me it's causing a custom handler issue in that it can't find iOS and macOS related handler overrides or color extensions.

**Comment by mattleibow** [comment] 2024-02-14 19:58
I think the issue is that the 8.0.200 SDK has _older_ ios/android/maui workloads... somehow... and as a result, the older iOS cannot load the newer/current maui/ios nugets.

If you use a global.json for now to pin to 8.0.101 or make sure you use that version on CI, it should start working again.

Investigations into why, how, and what happened is still ongoing, and a fix will hopefully be found ASAP.

**Comment by jfversluis** [comment] 2024-02-14 20:21
Can confirm, saw this happening in one of my plugin repositories https://github.com/jfversluis/Plugin.Maui.ScreenRecording/pull/15

**Comment by Redth** [comment] 2024-02-14 21:31
Please see #20600

**Comment by williambuchanan2** [comment] 2024-02-15 00:50
I received an update for VS For Mac today. After installing this update the problem is now happening on there as well. I don't have the 'use prerelease' option checked but for some reason it looks like it is using prerelease versions.

So now no way to develop on Mac until this is fixed.

**Comment by jfversluis** [comment] 2024-02-16 09:52
Duplicate of https://github.com/dotnet/maui/issues/20600 and a fix is available for the hosted build agents without the need for any other changes. Installing .NET 8.0.201 should also fix it for VS for Mac I would assume.

**Closed by jfversluis** 2024-02-16 09:52 UTC
Labels: t/bug, platform/iOS 🍎, potential-regression
