### ISSUE TITLE
FontImageSource renders slow on Android in ImageButton and Image

### ISSUE THREAD

**Issue by davidortinau** [dotnet/maui#22757] opened 2024-05-31 14:08 UTC
### Description

In debug I can see the images paint, initially very slowly and then the second time I navigate they still draw much slower for `ImageButton` and `Image` than for `Label`.

[FontThings.zip](https://github.com/user-attachments/files/15514781/FontThings.zip)

Android:

https://github.com/dotnet/maui/assets/41873/0107607e-3d78-4ab0-9e5e-b7082bdb851b

iOS for comparison is fine.

https://github.com/dotnet/maui/assets/41873/dc494cc2-7223-41a4-b816-0a392c493dfb

9.0.0-preview.4.10690

I tested a release build, and while the first draw is faster, going between pages still has the icons bouncing around as they measure and layout.

### Version with bug

9.0.0-preview.3.10457

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.40 SR5

### Affected platforms

Android

**Comment by kevinxufei** [comment] 2024-06-03 05:24
Verified this issue with Visual Studio 17.11.0 Preview 1(9.0.0-preview.4.10690/9.0.0-preview.2.10293/8.0.40/8.0.21/8.0.3). Can repro on android platform with sample project.

**Comment by mattleibow** [comment] 2024-06-04 14:55
I cannot repro this on the latest 8.0.40 nor the latest nightly nor main.

If this is just net9, then maybe we need to test again after the main branch is merged.

**Comment by mattleibow** [comment] 2024-06-04 17:32
I managed to repro this on net9 using Preview 4 bits. I do get a bit different results, the initial load is like a few ms before the image appears, but then it is fast from then on.

**Comment by mattleibow** [comment] 2024-06-04 17:55
I see I am getting this now on my devbox... 

So on my mac, all net8 versions seem to work. On the Windows devbox, all versions seem to be broken. The devbox seems to have acceleration issues - or that is what it said when I booted but I am not sure. 

However, this all depends now before I start destroying my local machines. What type of machines are you using @davidortinau  and @kevinxufei ? Physical machines? Remote desktops? Dev boxes? VMs?

**Comment by mattleibow** [comment] 2024-06-04 18:32
OK, looking at Windows machine, I see a very very small delay. My M1 mac has no delay, my Surface Laptop Studio is mostly good but there is like a 100-200ms delay, devbox is got a big flash.

I tested on my Samsung A53 and it seemed OK...

Maybe the emulators are making a small issue with the fact that the images are bing generated on the fly become more obvious. Not sure if ayone sees this on a real device or on a real machine - or is this in devoxes/VMs that might not have accelerated hardware?

**Comment by mattleibow** [comment] 2024-06-04 19:19
Testing some more on the slow devbox I found something interesting. I wrote this code:

```cs

// var imageSource = new FileImageSource
// {
// 	File = "dotnet_bot.png"
// };

var imageSource = new FontImageSource
{
	FontFamily = "FontAwesome",
	Color = Colors.Black,
	Glyph = IconFont.FootballBall
};

var sw = new Stopwatch();
sw.Start();

var mauiContext = Handler.MauiContext;
var provider = mauiContext.Services.GetService<IImageSourceServiceProvider>();
var service = provider.GetRequiredImageSourceService(imageSource);

#if ANDROID
var result = await service.GetDrawableAsync(imageSource, mauiContext.Context);
#endif

sw.Stop();

await DisplayAlert("TIME", sw.ElapsedMilliseconds.ToString(), "OK");
```

When using a `FileImageSource`, the first run is about 50-60ms and the subsequent are 0-1ms. However, when using a `FontImageSource`, the first run is a whopping 450-500ms and the next runs are better at 20-50ms.

`FontImageSource` seems to be much slower and on slower devices/emus it looks bad. However, this has been happening since GA (I have been testing with 8.0.3 and 8.0.41)

BUT... I do notice that 8.0.40 is about 100ms slower the inital run (about 550-600ms) and 50ms on subsequent runs (about 30-100ms)

**Comment by mattleibow** [comment] 2024-06-04 20:38
I generated a speedscope of a Release build of 8.0.40 and there is very much a large set of interop happening. I wonder if something in the AOT profile change of we need to add it into the profile.

[dotnet-dsrouter.exe_20240605_043053.speedscope.json](https://github.com/user-attachments/files/15570154/dotnet-dsrouter.exe_20240605_043053.speedscope.json)

**Comment by mattleibow** [comment] 2024-06-05 06:42
8.0.40 times

| accessing service | generating drawable | total |
|-:|-:|-:|
| 12 | 393 | 405 |
| 0 | 81 | 81 |
| 0 | 66 | 66 |
| 0 | 70 | 70 |
| 0 | 79 | 79 |
| 0 | 69 | 69 |
| 0 | 15 | 15 |
| 0 | 14 | 14 |
| 0 | 27 | 27 |

8.0.* times

| accessing service | generating drawable | total |
|-:|-:|-:|

8.0.3 times

| accessing service | generating drawable | total |
|-:|-:|-:|

**Comment by mattleibow** [comment] 2024-06-05 07:16
I did a diff between 40 and 21, and I see this is really the only thing that changed and it looks like it would have changed for the better: https://github.com/dotnet/maui/pull/22040

But maybe it is better, but we did not generate an AOT profile with it so it got worse or something.

**Comment by mattleibow** [comment] 2024-06-05 14:42
A better speedscope with a single load and nothing else: 
[dotnet-dsrouter.exe_20240605_223945.speedscope.json](https://github.com/user-attachments/files/15592397/dotnet-dsrouter.exe_20240605_223945.speedscope.json)

**Comment by mattleibow** [comment] 2024-06-05 18:32
I rebooted my emulator and now all the numbers are the same... So basically, not the proof anymore. Looks like the longer an emu runs the slower it becomes.

**Comment by schinkenwuerfel** [comment] 2024-07-24 07:11
I just verified that the issue still is happening in 8.0.60.
However, I have found a workaround for this issue:  We moslty use the FontImageSources in Buttons for showing icons instead of text. The workaround is to just use the glyphs passed into the FontImageSource as the Text of the Button instead of setting the FontImageSource as the ImageSource of the Button. For the few Images we use in our application a switch to a Label with the desired glyph as text is also possible.
This requires some refactoring of our code base tho which im not so keen in doing right now, so i wanted to check back if there are any further infos about this issue and if this is going to be fixed soon'ish?

**Comment by mattleibow** [comment] 2024-08-05 17:32
I think we found that there was no caching for the font images, so this PR will hopefully fix it a fair bit: https://github.com/dotnet/maui/pull/24021

**Comment by albyrock87** [comment] 2024-08-06 10:55
This is a benchmark from #24021 

```csharp
[Benchmark]
public async Task ImageHelperFromFont()
{
	var callback = new Callback();

	handler!.Post(() =>
	{
		Microsoft.Maui.PlatformInterop.LoadImageFromFont(
			context,
			Android.Graphics.Color.Aquamarine,
			"A",
			Typeface.Default,
			24,
			callback);
	});

	await callback.SuccessTask;
}
```

**Before**

| Method              | Mean         | Error        | StdDev        | Gen0   | Allocated |
|-------------------- |-------------:|-------------:|--------------:|-------:|----------:|
| ImageHelperFromFont | 408,206.3 ns | 54,119.83 ns | 153,528.95 ns | 0.4883 |    2427 B |

**After**

| Method              | Mean        | Error       | StdDev      | Gen0   | Allocated |
|-------------------- |------------:|------------:|------------:|-------:|----------:|
| ImageHelperFromFont | 58,737.1 ns | 1,222.72 ns | 3,221.13 ns | 0.4883 |    2327 B |

**Comment by gautambjain** [comment] 2024-08-12 08:59
I took latest Visual Studio Version 17.10.5 and MAUI 8.0.80. I have a MAUI project that uses .Net 8.0. 

The issue described above still exists. Please check the below link (few seconds video). 

https://github.com/user-attachments/assets/70087f6e-4b12-4506-8188-78142cdd3da3

I am using <Image/> in xaml with FontImageSource. It draws the ListView once and after a second or so, shows the images.

How can I avoid/fix this? I cannot fix the grid row height as I want to make it compatible with different scaled display sizes (scaled text).

**Comment by albyrock87** [comment] 2024-08-12 09:04
@gautambjain I think this might be a different issue.
Have you tried to set a fixed size on the image/image button with the star icon?

**Comment by gautambjain** [comment] 2024-08-12 09:23
Thanks @albyrock87 . I already had a fixed size of 28 on Image. The RowDefinition on the grid is set to Auto. So the row shows smaller and then larger as shown in video.

But I kind of fixed the row height by fixing the surrounding StackLayout MinimumHeightRequest to 28. Now the ListView rows show a bigger initial size but still the fonts appear little later. And there are more font icons I am using in the same list row (folder icon, alarm icon, contact icon) and I want them to show bigger when the user changes the default display/text size (scaled text and display). 

But don't you think the actual issue of delayed FontImageSource loading still is shown in my video? What I did above is only a work around. But it will not work for all font icons and all scaled displays. It will still show a flicker like in the video.

**Comment by albyrock87** [comment] 2024-08-12 10:36
@gautambjain use `adb` and enable `Glide`-related logging as follows (before starting the app):

```
adb shell setprop log.tag.CustomViewTarget VERBOSE
adb shell setprop log.tag.GlideRequest VERBOSE    
adb shell setprop log.tag.Glide VERBOSE          
adb shell setprop log.tag.Engine VERBOSE 
adb shell setprop log.tag.HttpUrlFetcher VERBOSE 
```

Then start the app and reach you page and look at logs.

A sample load not from cache, see `Started new load in 0.162708ms`:
```
08-12 12:17:46.935 V/GlideRequest( 9801): Got onSizeReady in 0.024709 this: 47856178
08-12 12:17:46.936 V/GlideRequest( 9801): finished setup for calling load in 0.801292 this: 47856178
08-12 12:17:46.937 V/Engine  ( 9801): Started new load in 0.162708ms, key: EngineKey{model=com.microsoft.maui.glide.font.FontModel@756ffea1, width=-2147483648, height=-2147483648, resourceClass=class java.lang.Object, transcodeClass=class android.graphics.drawable.Drawable, signature=EmptySignature, hashCode=1275066720, transformations={}, options=Options{values={}}}
08-12 12:17:46.939 V/GlideRequest( 9801): finished onSizeReady in 3.9862919999999997 this: 47856178
08-12 12:17:46.939 V/GlideRequest( 9801): finished run method in 4.4395 this: 47856178
```

A sample load from cache, see `Loaded resource from cache in 0.20099999999999998ms`
```
08-12 12:17:50.390 V/GlideRequest( 9801): Got onSizeReady in 0.021374999999999998 this: 252343517
08-12 12:17:50.390 V/GlideRequest( 9801): finished setup for calling load in 0.6669579999999999 this: 252343517
08-12 12:17:50.391 V/Engine  ( 9801): Loaded resource from cache in 0.20099999999999998ms, key: EngineKey{model=com.microsoft.maui.glide.font.FontModel@756ffea1, width=-2147483648, height=-2147483648, resourceClass=class java.lang.Object, transcodeClass=class android.graphics.drawable.Drawable, signature=EmptySignature, hashCode=1275066720, transformations={}, options=Options{values={}}}
08-12 12:17:50.392 V/GlideRequest( 9801): finished onSizeReady in 2.222667 this: 252343517
08-12 12:17:50.393 V/GlideRequest( 9801): finished run method in 2.780042 this: 252343517
```

Now I would expect lots of them being loaded from cache.

Talking about MAUI internals, to load images we're using https://github.com/bumptech/glide library.
The nature of this library's image loading process is *asynchronous* which means there's always a chance to see (for example) a flicker while changing image source.
There's only one situation which appears to do a synchronous loading, which is when the image of the same size is in the memory cache (not disk cache).

In your case all images are appearing in the same moment for the first time, so maybe that means that none of them will find the image in cache.

I cannot understand what you're doing in the app from the video, but it seems you're suddenly displaying a collection view with some items.
Something like:

1. Page shows a loading indicator
2. Data has been loaded and set to a bound `ItemsSource` in a collection view

Now, on step 1, may you try to display all the icons somewhere in the page (with the same `Size` and `Color` you use inside the collection view)?

This should bring them into the memory cache and load should be immediate.

Let me know how it goes, and anyway, it'd be useful to have a simple `how to reproduce` code sample so we can include it into MAUI test cases and work on it.

**Closed** 2024-08-19 16:36 UTC
Labels: t/bug, platform/android 🤖, area-image, p/1, s/verified, s/triaged, s/try-latest-version, potential-regression, t/perf, delighter-sc
