### ISSUE TITLE
Error when building MAUI project in visual studio: WMC0001 Unknown type 'xxx' in XML namespace 'http://schemas.microsoft.com/dotnet/2021/maui'

### ISSUE THREAD

**Issue by Kas-code** [dotnet/maui#19896] opened 2024-01-15 10:26 UTC
### Description

When building a MAUI project in Visual studio, I get thousands of similar errors thrown from xaml files like the following:
```
Error	WMC0001	Unknown type 'ActivityIndicator' in XML namespace 'http://schemas.microsoft.com/dotnet/2021/maui'	
Error	WMC0001	Unknown type 'Application' in XML namespace 'http://schemas.microsoft.com/dotnet/2021/maui'	
Error	WMC0001	Unknown type 'Binding' in XML namespace 'http://schemas.microsoft.com/dotnet/2021/maui'	
Error	WMC0001	Unknown type 'Border' in XML namespace 'http://schemas.microsoft.com/dotnet/2021/maui'	
Error	WMC0001	Unknown type 'CollectionView' in XML namespace 'http://schemas.microsoft.com/dotnet/2021/maui'	
Error	WMC0001	Unknown type 'Color' in XML namespace 'http://schemas.microsoft.com/dotnet/2021/maui'
Error	WMC0001	Unknown type 'ColumnDefinition' in XML namespace 'http://schemas.microsoft.com/dotnet/2021/maui'	
Error	WMC0001	Unknown type 'ColumnDefinition' in XML namespace 'http://schemas.microsoft.com/dotnet/2021/maui'
Error	WMC0001	Unknown type 'DataTemplate' in XML namespace 'http://schemas.microsoft.com/dotnet/2021/maui'
Error	WMC0001	Unknown type 'DataTemplate' in XML namespace 'http://schemas.microsoft.com/dotnet/2021/maui'	
Error	WMC0001	Unknown type 'Entry' in XML namespace 'http://schemas.microsoft.com/dotnet/2021/maui'
Error	WMC0001	Unknown type 'FlexLayout' in XML namespace 'http://schemas.microsoft.com/dotnet/2021/maui'
Error	WMC0001	Unknown type 'FlyoutItem' in XML namespace 'http://schemas.microsoft.com/dotnet/2021/maui'
Error	WMC0001	Unknown type 'FontImageSource' in XML namespace 'http://schemas.microsoft.com/dotnet/2021/maui'	
Error	WMC0001	Unknown type 'FormattedString' in XML namespace 'http://schemas.microsoft.com/dotnet/2021/maui'
Error	WMC0001	Unknown type 'Frame' in XML namespace 'http://schemas.microsoft.com/dotnet/2021/maui'
Error	WMC0001	Unknown type 'Grid' in XML namespace 'http://schemas.microsoft.com/dotnet/2021/maui'
```

When building the project in an azure devops pipeline, via the `DotNetCoreCLI@2` task, the project builds with no problems.
As a result, I cannot build the project locally, only via devops pipelines.

Visual studio screenshot:
![image](https://github.com/dotnet/maui/assets/16824378/eab293b9-d72e-48e6-8aad-225a32d03c65)

Building via the following command in azure devops pipelines works fine:
![image](https://github.com/dotnet/maui/assets/16824378/e7790c62-8e34-4394-80c4-4e14bfd9e6ea)

### Steps to Reproduce

Using visual studio community 2022 17.9.0 Preview 2.1

### Version with bug

8.0.3

### Is this a regression from previous behavior?

The build worked fine in Xamarin, but following a project upgrade from Xamarin to Maui, the issue appears. However, the application builds successfully on an azure pipeline, deploys to google play, and runs fine on an android device.

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Did you find any workaround?

None

**Comment by jsuarezruiz** [comment] 2024-01-15 15:06
Are you building the solution or the Android project?. To package, you need to use the Android csproj.

**Comment by Kas-code** [comment] 2024-01-15 15:46
I was building a class library that contained xaml files, not the Android project. Removing the following line from the class library .csproj has resolved the issue:
```        
<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net8.0-windows10.0.19041.0</TargetFrameworks>
```

**Comment by ngieske-MSI** [comment] 2024-03-26 20:57
I am having the same issue on VS2022 Pro 17.9.2. I have tried Kas-code's solution of removing the Windows target platform from the class library, and I can confirm that this does remove the compile errors. However, this class library needs to target WinUI so unfortunately this solution is not viable.

**Comment by jfversluis** [comment] 2024-06-25 11:09
I would think this is a local environment setup issue which is hard to diagnose unfortunately without more detail and even harder to solve asynchronous with posting comments here back and forth. It seems the author has solved their issue and I hope the last commenter as well since it has been a while. As such, I'll be closing this one here for now. If you run into this issue, please open a new issue with a reproduction or at the very least much more details about the versions of Visual Studio, .NET MAUI installed, what it shows under the projects dependencies nodes etc. 

Or reach out to me directly and we will hopefully figure things out there.

**Closed by jfversluis** 2024-06-25 11:09 UTC
Labels: t/bug, platform/android 🤖, area-tooling, s/triaged, s/needs-attention
