### ISSUE TITLE
Adding datepicker crashes app iOS 17.4?

### ISSUE THREAD

**Issue by AnthonyDewhirst** [dotnet/maui#21312] opened 2024-03-19 16:15 UTC
### Description

I have a datepicker on a content screen:
``` xaml
        <DatePicker />
```
this crashes the app

### Steps to Reproduce

1. New maui app
2. add datepicker to mainpage.xaml
3.  run app in ios simulator iphone 15 ios 17.4

### Version with bug

8.0.7 SR2

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iphone 15 ios 17.4

### Did you find any workaround?

New to maui and not looked yet

### Relevant log output

```shell
I tried pasting the content of the crash report but the validation failure in github was comment too long.
Where should I put it and is there anything that needs obfuscating?
```

**Comment by drasticactions** [comment] 2024-03-19 16:17
FYI See https://github.com/dotnet/maui/issues/21057

Running iOS 17.4/Xcode 15.3 is unsupported until the SDKs are updated.

**Comment by PureWeen** [comment] 2024-03-19 17:30
Duplicate of #21057

**Closed by PureWeen** 2024-03-19 17:30 UTC
Labels: t/bug
