### ISSUE TITLE
Unable to build .NET MAUI application after upgrade to Visual Studio 17.3.5

### ISSUE THREAD

**Issue by tsjdev-apps** [dotnet/maui#10448] opened 2022-10-02 05:43 UTC
### Description

I'm unable to build a .NET MAUI application, even the empty template after upgrading to VIsual Studio 17.3.5.

`NU1012	Platform version is not present for one or more target frameworks, even though they have specified a platform: net6.0-ios, net6.0-maccatalyst`

I've tried to uninstall Visual Studio and install Visual Studio again without any difference. I've tried to `restore` the worloads without any difference.

### Steps to Reproduce

1. Create a new .NET MAUI application
2. Try to build the application

### Link to public reproduction project repository

https://github.com/tsjdev-apps/maui-sample

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS, Other (Tizen, Linux, etc. not supported by Microsoft directly)

### Affected platform versions

All platform versions

### Did you find any workaround?

-

### Relevant log output

```shell
dotnet --list-sdks

6.0.401 [C:\Program Files\dotnet\sdk]

---

dotnet --list-runtimes

Microsoft.AspNetCore.App 6.0.0-rc.2.21480.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 6.0.0-rc.2.21480.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 6.0.0-rc.2.21501.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

---

dotnet workload list

Installed Workload Ids      Manifest Version      Installation Source
---------------------------------------------------------------------
tizen                       7.0.400/6.0.400       SDK 6.0.400
maui-windows                6.0.540/6.0.400       VS 17.3.32922.545
maui-maccatalyst            6.0.540/6.0.400       VS 17.3.32922.545
maccatalyst                 15.4.447/6.0.400      VS 17.3.32922.545
maui-ios                    6.0.540/6.0.400       VS 17.3.32922.545
ios                         15.4.447/6.0.400      VS 17.3.32922.545
maui-android                6.0.540/6.0.400       VS 17.3.32922.545
android                     32.0.465/6.0.400      VS 17.3.32922.545

---

dotnet workload restore

Installing workloads: maui-tizen maui-ios maui-maccatalyst

Advertising manifest not updated. Manifest package for samsung.net.sdk.tizen doesn't exist.
Installing Microsoft.Maui.Core.Ref.tizen.6.0.540.0-x64.msi ........... Done
Installing Microsoft.Maui.Core.Runtime.tizen.6.0.540.0-x64.msi .... Done
Installing Microsoft.Maui.Controls.Ref.tizen.6.0.540.0-x64.msi .... Done
Installing Microsoft.Maui.Controls.Runtime.tizen.6.0.540.0-x64.msi .... Done
Installing Microsoft.Maui.Essentials.Ref.tizen.6.0.540.0-x64.msi .... Done
Installing Microsoft.Maui.Essentials.Runtime.tizen.6.0.540.0-x64.msi .... Done
Installing Microsoft.AspNetCore.Components.WebView.Maui.6.0.540.0-x64.msi .... Done
Installing Microsoft.Maui.Dependencies.6.0.540.0-x64.msi .... Done
Installing Microsoft.Maui.Extensions.6.0.540.0-x64.msi .... Done
Installing Microsoft.Maui.Graphics.6.0.501-x64.msi .... Done
Installing Microsoft.Maui.Resizetizer.Sdk.6.0.540.0-x64.msi ...... Done
Installing Microsoft.Maui.Core.Ref.any.6.0.540.0-x64.msi .... Done
Installing Microsoft.Maui.Core.Runtime.any.6.0.540.0-x64.msi .... Done
Installing Microsoft.Maui.Controls.Ref.any.6.0.540.0-x64.msi .... Done
Installing Microsoft.Maui.Controls.Runtime.any.6.0.540.0-x64.msi .... Done
Installing Microsoft.Maui.Essentials.Ref.any.6.0.540.0-x64.msi .... Done
Installing Microsoft.Maui.Essentials.Runtime.any.6.0.540.0-x64.msi .... Done
Installing Microsoft.Maui.Core.Ref.ios.6.0.540.0-x64.msi .... Done
Installing Microsoft.Maui.Core.Runtime.ios.6.0.540.0-x64.msi .... Done
Installing Microsoft.Maui.Controls.Ref.ios.6.0.540.0-x64.msi .... Done
Installing Microsoft.Maui.Controls.Runtime.ios.6.0.540.0-x64.msi .... Done
Installing Microsoft.Maui.Essentials.Ref.ios.6.0.540.0-x64.msi .... Done
Installing Microsoft.Maui.Essentials.Runtime.ios.6.0.540.0-x64.msi .... Done
Installing Microsoft.iOS.Sdk.15.4.447.447-x64.msi ..... Done
Installing Microsoft.iOS.Windows.Sdk.15.4.447.447-x64.msi ...... Done
Installing Microsoft.iOS.Ref.15.4.447.447-x64.msi .... Done
Installing Microsoft.iOS.Runtime.ios-arm.15.4.447.447-x64.msi ..... Done
Installing Microsoft.iOS.Runtime.ios-arm64.15.4.447.447-x64.msi ..... Done
Installing Microsoft.iOS.Runtime.iossimulator-x86.15.4.447.447-x64.msi ..... Done
Installing Microsoft.iOS.Runtime.iossimulator-x64.15.4.447.447.msi ..... Done
Installing Microsoft.iOS.Runtime.iossimulator-arm64.15.4.447.447-x64.msi ..... Done
Installing Microsoft.iOS.Templates.15.4.447.447-x64.msi .... Done
Installing Microsoft.Maui.Core.Ref.maccatalyst.6.0.540.0-x64.msi .... Done
Installing Microsoft.Maui.Core.Runtime.maccatalyst.6.0.540.0-x64.msi .... Done
Installing Microsoft.Maui.Controls.Ref.maccatalyst.6.0.540.0-x64.msi .... Done
Installing Microsoft.Maui.Controls.Runtime.maccatalyst.6.0.540.0-x64.msi .... Done
Installing Microsoft.Maui.Essentials.Ref.maccatalyst.6.0.540.0-x64.msi .... Done
Installing Microsoft.Maui.Essentials.Runtime.maccatalyst.6.0.540.0-x64.msi .... Done
Installing Microsoft.MacCatalyst.Sdk.15.4.447.447-x64.msi .... Done
Installing Microsoft.MacCatalyst.Ref.15.4.447.447-x64.msi .... Done
Installing Microsoft.MacCatalyst.Runtime-arm64.15.4.447.447-x64.msi ..... Done
Installing Microsoft.MacCatalyst.Runtime-x64.15.4.447.447.msi ..... Done
Installing Microsoft.MacCatalyst.Templates.15.4.447.447-x64.msi .... Done
Downloading Samsung.Tizen.Sdk.Msi.x64 (7.0.400)
Workload installation failed. Rolling back installed packs...
Removing Microsoft.MacCatalyst.Templates.15.4.447.447-x64.msi .... Done
Removing Microsoft.MacCatalyst.Runtime-x64.15.4.447.447.msi .... Done
Removing Microsoft.MacCatalyst.Runtime-arm64.15.4.447.447-x64.msi .... Done
Removing Microsoft.MacCatalyst.Ref.15.4.447.447-x64.msi .... Done
Removing Microsoft.MacCatalyst.Sdk.15.4.447.447-x64.msi ..... Done
Removing Microsoft.Maui.Essentials.Runtime.maccatalyst.6.0.540.0-x64.msi .... Done
Removing Microsoft.Maui.Essentials.Ref.maccatalyst.6.0.540.0-x64.msi .... Done
Removing Microsoft.Maui.Controls.Runtime.maccatalyst.6.0.540.0-x64.msi .... Done
Removing Microsoft.Maui.Controls.Ref.maccatalyst.6.0.540.0-x64.msi .... Done
Removing Microsoft.Maui.Core.Runtime.maccatalyst.6.0.540.0-x64.msi .... Done
Removing Microsoft.Maui.Core.Ref.maccatalyst.6.0.540.0-x64.msi .... Done
Removing Microsoft.iOS.Templates.15.4.447.447-x64.msi .... Done
Removing Microsoft.iOS.Runtime.iossimulator-arm64.15.4.447.447-x64.msi .... Done
Removing Microsoft.iOS.Runtime.iossimulator-x64.15.4.447.447.msi .... Done
Removing Microsoft.iOS.Runtime.iossimulator-x86.15.4.447.447-x64.msi .... Done
Removing Microsoft.iOS.Runtime.ios-arm64.15.4.447.447-x64.msi .... Done
Removing Microsoft.iOS.Runtime.ios-arm.15.4.447.447-x64.msi .... Done
Removing Microsoft.iOS.Ref.15.4.447.447-x64.msi .... Done
Removing Microsoft.iOS.Windows.Sdk.15.4.447.447-x64.msi ....... Done
Removing Microsoft.iOS.Sdk.15.4.447.447-x64.msi ...... Done
Removing Microsoft.Maui.Essentials.Runtime.ios.6.0.540.0-x64.msi .... Done
Removing Microsoft.Maui.Essentials.Ref.ios.6.0.540.0-x64.msi .... Done
Removing Microsoft.Maui.Controls.Runtime.ios.6.0.540.0-x64.msi .... Done
Removing Microsoft.Maui.Controls.Ref.ios.6.0.540.0-x64.msi .... Done
Removing Microsoft.Maui.Core.Runtime.ios.6.0.540.0-x64.msi .... Done
Removing Microsoft.Maui.Core.Ref.ios.6.0.540.0-x64.msi .... Done
Removing Microsoft.Maui.Essentials.Runtime.any.6.0.540.0-x64.msi .... Done
Removing Microsoft.Maui.Essentials.Ref.any.6.0.540.0-x64.msi .... Done
Removing Microsoft.Maui.Controls.Runtime.any.6.0.540.0-x64.msi .... Done
Removing Microsoft.Maui.Controls.Ref.any.6.0.540.0-x64.msi .... Done
Removing Microsoft.Maui.Core.Runtime.any.6.0.540.0-x64.msi .... Done
Removing Microsoft.Maui.Core.Ref.any.6.0.540.0-x64.msi .... Done
Removing Microsoft.Maui.Resizetizer.Sdk.6.0.540.0-x64.msi ..... Done
Removing Microsoft.Maui.Graphics.6.0.501-x64.msi .... Done
Removing Microsoft.Maui.Extensions.6.0.540.0-x64.msi .... Done
Removing Microsoft.Maui.Dependencies.6.0.540.0-x64.msi .... Done
Removing Microsoft.AspNetCore.Components.WebView.Maui.6.0.540.0-x64.msi .... Done
Removing Microsoft.Maui.Essentials.Runtime.tizen.6.0.540.0-x64.msi .... Done
Removing Microsoft.Maui.Essentials.Ref.tizen.6.0.540.0-x64.msi .... Done
Removing Microsoft.Maui.Controls.Runtime.tizen.6.0.540.0-x64.msi .... Done
Removing Microsoft.Maui.Controls.Ref.tizen.6.0.540.0-x64.msi .... Done
Removing Microsoft.Maui.Core.Runtime.tizen.6.0.540.0-x64.msi .... Done
Removing Microsoft.Maui.Core.Ref.tizen.6.0.540.0-x64.msi .... Done
Workload installation failed: One or more errors occurred. (samsung.tizen.sdk.msi.x64::7.0.400 is not found in NuGet feeds https://api.nuget.org/v3/index.json;C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\".)
```

**Comment by PureWeen** [comment] 2022-10-04 18:26
Duplicate of #10234

**Closed by PureWeen** 2022-10-04 18:26 UTC
Labels: t/bug, area/tooling ⚙️, s/move-to-vs-feedback

**Comment by janduldhardt** [comment] 2022-10-06 05:25
Any workarounds?
