### ISSUE TITLE
[Bug] Label text alignment doesn't work

### ISSUE THREAD

**Issue by davidortinau** [dotnet/maui#2019] opened 2021-08-10 13:28 UTC
### Description

```
<Grid RowSpacing="4" ColumnSpacing="4" 
        ColumnDefinitions="*,*"
        RowDefinitions="*,*,*,*,*">

        <Label Text="Row 0, ColumnSpan=2"
            Grid.ColumnSpan="2"
            VerticalOptions="Fill" HorizontalOptions="Fill"
            VerticalTextAlignment="Center" HorizontalTextAlignment="Center"
            Background="#333333" TextColor="White"/>
            

    </Grid>
```

![Screenshot_1628601978](https://user-images.githubusercontent.com/41873/128875318-88fd7188-9c6c-4970-853f-dcb2125a8177.png)

### Basic Information

- Version with issue: 6.0.100-preview.7.1307

**Comment by hartez** [comment] 2021-08-10 18:07
This appears to be a duplicate of #1509

**Closed** 2021-08-13 09:55 UTC
Labels: platform/android 🤖
