### ISSUE TITLE
DisplayActionSheet crashes on MacCatalyst

### ISSUE THREAD

**Issue by daltzctr** [dotnet/maui#23288] opened 2024-06-26 21:24 UTC
### Description

Any usage of DispalyActionSheet seems to crash on MacCatalyst

### Steps to Reproduce

1. Create a new MAUI project.
2. Create a button, have the clicked event invoke `DisplayActionSheet`
3. Observe crash

### Version with bug

8.0.61 SR6.1

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Did you find any workaround?

Invoke `UIAlertController` directly

### Relevant log output

```shell
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Maui.Controls.Platform.AlertManager.AlertRequestHelper.PresentPopUp(Page sender, Window virtualView, UIWindow platformView, UIAlertController alert, ActionSheetArguments arguments)
   at Microsoft.Maui.Controls.Platform.AlertManager.AlertRequestHelper.PresentActionSheet(Page sender, ActionSheetArguments arguments)
   at Microsoft.Maui.Controls.Platform.AlertManager.AlertRequestHelper.OnActionSheetRequested(Page sender, ActionSheetArguments arguments)
```
```

**Comment by PureWeen** [comment] 2024-06-26 23:41
Can you test with the latest nightly build? 
https://github.com/dotnet/maui/wiki/Nightly-Builds

**Comment by ninachen03** [comment] 2024-06-27 10:17
I cannot repro this issue on the latest Visual Studio 17.6.12(build410) (8.0.60 & 8.0.61)
![image](https://github.com/dotnet/maui/assets/128687574/711c318e-a963-473f-bedc-3fc3b8c9b52b)

**Comment by mattleibow** [comment] 2024-07-02 12:20
Duplicate of https://github.com/dotnet/maui/issues/18156

**Closed by mattleibow** 2024-07-02 12:20 UTC
Labels: t/bug, platform/macOS 🍏, s/needs-info, area-controls-dialogalert, s/triaged, s/try-latest-version
