### ISSUE TITLE
StringFormat='{0:c}' doesn't show dollar sign in .NET MAUI 9

### ISSUE THREAD

**Issue by imsam67** [dotnet/maui#26183] opened 2024-11-28 04:55 UTC
### Description

The following code does not display a dollar symbol. Instead, it display some other symbol -- see image below:

```
<Label
   Text={Binding Amount, StringFormat='{0:c}'}
   TextColor="Black" />
```

Here's what it shows instead:
![Image](https://github.com/user-attachments/assets/8550554a-49f4-48c9-b07f-7ca37d7439b9)

This was working perfectly in .NET 8.

### Steps to Reproduce

In a .NET MAUI app targeting .NET 9, just add a `Label` and bind it to a numeric value e.g. decimal and use `StringFormat='{0:c}' in the label to format it as currency.

### Link to public reproduction project repository
https://github.com/iQuestLLC/maui-9-issues

_No response_

### Version with bug

9.0.0 GA

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.100 SR10

### Affected platforms

iOS

### Did you find any workaround?

Not yet

### Relevant log output

```shell

```

**Comment by Ying-6** [comment] 2024-11-28 07:09
Hi @imsam67 I added the label code you provided to the MainPage.xaml file, but it does not display any value after being deployed to the iOS simulator. Could you provide us with a sample project so we can investigate it further? Looking forward to your reply!

**Comment by imsam67** [comment] 2024-11-28 07:19
@Ying-6 Here's the repo with sample code. You'll see what I'm talking about on `MainPage.xaml`.

https://github.com/iQuestLLC/maui-9-issues

**Comment by Ying-6** [comment] 2024-11-28 07:46
This issue has been verified using Visual Studio 17.13 Preview 1(9.0.10 & 9.0.00). Can repro this issue on iOS platforms. And 8.0.100 works fine.

**Comment by jfversluis** [comment] 2024-11-28 10:15
I don't think this is on us: https://github.com/dotnet/runtime/issues/108958

**Comment by tj-devel709** [comment] 2024-12-04 18:16
I will close this issue for now as @jfversluis posted the root cause of this issue in the runtime repro. There is a listed workaround there for now as well. Please feel free to re-open this issue though or create a new one and link this one if needed!

**Closed by tj-devel709** 2024-12-04 18:16 UTC
Labels: t/bug, area-xaml, platform/iOS 🍎, s/verified, s/triaged, i/regression
