### ISSUE TITLE
.net maui builder. Services (Quartz Service won't start)

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#4028] opened 2022-01-10 18:17 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/net-maui-builderServices-Quartz-Servi/1604167)._

---

```
       <ItemGroup>
		<PackageReference Include="Quartz.Extensions.Hosting" Version="3.3.3" />
	</ItemGroup>
```

```c#
public static class MauiProgram
{
    public static MauiApp CreateMauiApp()
    {
        var builder = MauiApp.CreateBuilder();
        builder
            . UseMauiApp<App>()
            . ConfigureFonts(fonts => fonts. AddFont("OpenSans-Regular.ttf", "OpenSansRegular"))
            . Services.AddQuartz(options =>
            {
                options. UseMicrosoftDependencyInjectionJobFactory();
                options. AddScheduledJob<QuotesJob>("0/30 * * ? * * *"); //Every 30 seconds starting at :00 second after the minute
            });
        builder. Services.AddQuartzHostedService();

return builder. Build();
    }
}
  public static class QuartzExtensions
    {
        public static IServiceCollectionQuartzConfigurator AddScheduledJob<T>(
            this IServiceCollectionQuartzConfigurator quartzConfigurator, string cronSchedule) where T : IJob
        {
            var jobName = typeof(T). Name;
            quartzConfigurator.AddJob<QuotesJob>(opt => opt. WithIdentity(jobName));
            quartzConfigurator.AddTrigger(opt => opt. ForJob(jobName)
                . WithIdentity($"{jobName}-trigger")
                . WithCronSchedule(cronSchedule));
            return quartzConfigurator;
        }
    }

[DisallowConcurrentExecution]
public class QuotesJob : IJob
{
    public Task Execute(IJobExecutionContext context)
    {
     //DoSomething()
        return Task.CompletedTask;
    }
}
```

The Quartz Service doesn't start at all, while the app starts fine and everything else works as expected

---
#### Feedback Bot on 12/6/2021, 00:16 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by Eilon** [comment] 2022-01-19 22:22
I'm guessing this would be fixed by https://github.com/dotnet/maui/issues/2244, if Quartz is in fact trying to use Hosted Service (which right now don't work in .NET MAUI).

**Comment by jfversluis** [comment] 2023-03-14 08:57
Duplicate of #2244

**Closed by jfversluis** 2023-03-14 08:57 UTC
Labels: area/hosting 🧩
