### ISSUE TITLE
ListView/CollectionView memory leak under Windows

### ISSUE THREAD

**Issue by hbraasch** [dotnet/maui#9162] opened 2022-08-03 07:58 UTC
### Description

A simple repro  (see link below) demonstrates a ListView/CollectionView memory leak under Windows. 
Each time the ItemSource gets updated with the exact same list, the app memory usage increases.
The repro is a simplification, normally the ListView/CollectionView  gets filled through a binding. However the repro still demonstrates the same problem.

See this video for a demonstration:

https://user-images.githubusercontent.com/7484186/182551821-e686710b-300f-4dbc-b1e0-7650f187216b.mp4

I'm a VS Community user so do not have access to the Xamarin Profiler to see if the problem also exists in Android and iOS. 

### Steps to Reproduce

1. Open the app from the repro in VS: https://github.com/hbraasch/ListViewMemoryTester.git
2. Set the platform to [Windows] and run
3. Click on the refresh button in the toolbar, see how the memory usage increases
4. Click on the [Click to launch [CollectionView] page] button, which launches the page based on a CollectionView
5.  Click on the refresh button in the toolbar, see how the memory usage also increases

### Version with bug

6.0.408 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

net6.0-windows10.0.19041.0

### Did you find any workaround?

No

**Comment by jfversluis** [comment] 2022-08-03 12:39
Thanks for the report and investigation on this!

I'm not necessarily the expert on performance testing, but what happens if you try calling the garbage collector? I can imagine that memory might still be growing depending on the memory that is available on the system and only flushed whenever necessary?

Besides this repro do you have any real-world scenarios where you had this happening? What made you start investigating this?

**Comment by hbraasch** [comment] 2022-08-03 23:58
Hi @jfversluis 

When add the following code to the [Refresh] event, it now tries to force a GC before updating the ImageSource.

```
ToolbarItems.Add(new ToolbarItem("Refresh", "ic_refresh.png", () => {
    GC.Collect();
    listView.ItemsSource = GenerateDisplayItems();
}));
```
The small yellow dots on the memory graph shows where the GC's occurs. They do happen where expected. Unfortunately it still shows the memory growth

![image](https://user-images.githubusercontent.com/7484186/182730895-95dbbe4c-248e-470f-a4a4-2e4786623817.png)

My real-world application... I'm developing  a custom TreeView which inherits from a ListView. It appears to work well when running under Android and iOS (but I must admit I did not check for memory leaks as I do not have the tools - I think). But when I started testing for Windows, the Windows app crashes with an out-of-memory exception. Since VS shows a memory graph while running a Windows app, I quickly noticed the continuous increase in memory each time e.g. a row gets expanded/collapsed, which is done by simply replacing the listview's ItemSource with a newly calculated (but mostly similar sized) one.

To investigating this further I started with a simple app (the repro), and found that it shows the same disconcerning effect.

I might be barking at the wrong tree, but I though I need to raise this before wasting an enormous amount of time searching for bugs elsewhere.

Regards

**Comment by xtuzy** [comment] 2022-09-01 01:44
I also feel ListView have memory leak, it recycle item?
I make a example show 500 TextCell, i don't know why TextCell will have 1500 in Memory Snapshot after i scroll ListView.

https://user-images.githubusercontent.com/17793881/187813724-c6c8e588-fbd7-4cfd-be53-20c0f756f59a.mp4

**Comment by xtuzy** [comment] 2022-09-01 03:45
I add a static int to show count of new itemview, the count still grow.

https://user-images.githubusercontent.com/17793881/187827023-92ff1118-3375-451b-9699-e4d9cf975de2.mp4

**Comment by xtuzy** [comment] 2022-09-01 10:59
Change some code of ViewCell, ListView will recycle Cell at Android, but still have bug at Windows, still create new Cell, not only 500.

At Android also have bug, scroll only very very slow.

![image](https://user-images.githubusercontent.com/17793881/187897253-33a94d20-dfe9-430e-b1b1-d49290f2998a.png)

Example source code:
[MauiAppListViewMemoryLeakBug1.zip](https://github.com/dotnet/maui/files/9469234/MauiAppListViewMemoryLeakBug1.zip)

**Comment by RealGregor** [comment] 2022-09-03 21:58
This bug should be a high priority to fix. The application is literally useless without the ability to scroll through content. And memory leak inside such a structure is a deterrent from even using .NET MAUI to develop anything.

**Comment by Keflon** [comment] 2022-09-12 08:41
I too have written a TreeView and also tried composing it using a CollectionView and a ListView and ran into the same problem here: https://github.com/dotnet/maui/issues/8151 as well as a layout problem: https://github.com/dotnet/maui/issues/4520  
As a workaround I wrote a virtualizing ListView I'm using until the CollectionView is fixed.  
@hbraasch you may benefit from a similar approach, or you could save yourself some time and use my ListView, or the TreeView it was written for. Both are here: https://github.com/Keflon/FunctionZero.Maui.Controls  
@jfversluis this and https://github.com/dotnet/maui/issues/8151 appear to be duplicates so you may want to close one?

**Comment by hbraasch** [comment] 2022-09-12 21:39
@Keflon Thanks

**Comment by ggutschi** [comment] 2022-10-21 09:22
This also happens in a FlexLayout with a BindableLayout.ItemsSource set (see sample attached).
[MauiApp1.zip](https://github.com/dotnet/maui/files/9837617/MauiApp1.zip)

**Comment by feal87** [comment] 2022-12-17 11:46
Can confirm the issue is still here. Application memory usage just keeps going up endlessly as items are added/removed.

**Comment by Odaronil** [comment] 2022-12-19 09:45
+1, It really annoys me when it takes up a lot of memory, especially if you add pictures there, the application already takes up more than 1 GB in less than 10 minutes!

PS: I also found a temporary solution, as the **Feal87** on top wrote this - ObservableCollection - Clear + Add But it only helps half.

**Comment by lucas-magalhaes-BTG** [comment] 2022-12-29 13:32
Same issue here, any update or workaround?

**Comment by lolnoob1234** [comment] 2023-01-06 19:34
hello,
sorry im a noob programmer
only very little experience with C# but im making my first app
i too stumbled upon this problem
my app has a page that holds a collectionview that was connected to a List at first
there is functionality on the page to filter items by category, i did this by clearing the list and then adding in a loop (no idea if this is the proper way to do it but visually it works)
i would refresh the list by reassigning the ItemsSource property constantly
this led to memory leak, memory usage would just keep climbing endlessly everytime i did this

earlier in the week started using ObservableCollection, a little better on the memory usage it seems but still the leak is there. also OC has no AddRange function which i kinda need. adding items to OC can only be done 1 at a time, which apparently raises 3 events, this is unnecessary for my needs bc i continually clear and add multiple items. the point is OC does not serve my needs

i have no experience with this so this may look silly or not, but i tried today implementing a custom type which inherits from List<T> and INotifyCollectionChanged. i used "public new void" keywords to hide the inherited member and make it use my versions, which really just base version and then raising the CollectionChanged event so that the CollectionView refreshes. i did this for Add and AddRange. works perfectly. 

as for Clear(), raising the event is not necessary but i noticed that calling Clear() did not do anything to keep memory usage down. .NET uses automatic garbage collection which is nice i guess but i think it's bad practice for ppl new to programming. i recently started learning C++ as well, which makes you learn about memory management. im missing that control over memory management here...anyway what fixed the memory leak issue for me here is to just call 

        public new void Clear()
        {
            base.Clear();
            GC.Collect();
            GC.WaitForPendingFinalizers();
        }

im not sure if that last function call is needed, i just happen to see it everywhere in conjunction with GC.Collect(); and from doing a lot of reading ive been discouraged from forcing a GC.Collect() manually. but here i do it anyway. the result being that now my CollectionView, despite constantly removing and adding items to my custom type as mentioned above, is behaving as i want it to. memory usage only climbs up to a certain point (a few MB) where it then stops increasing

i hope this helps others. i have no idea if what i did above is good coding practice (most likely not) but no more memory leak. ive been struggling with this issue now for months and was convinced i had to retire my application but now i can continue

**Comment by feal87** [comment] 2023-01-07 11:17
Adding/removing items from the collection isn't the problem of this ticket (that is, in fact, the workaround). The problem is related to the way MAUI uses the components underneath (WinUI) to render the collection if the binding changes (you assign a new one).
As long as you stay with a single observablecollection and keep refreshing it it's fine and it doesn't break.

Also you don't need to do a whole new class to have an AddRange. Just inherit from ObservableCollection and add the method 

```
        public void AddRange(IEnumerable<T> items)
        {
            this.CheckReentrancy();
            foreach (var item in items)
                this.Items.Add(item);
            this.OnCollectionChanged(new NotifyCollectionChangedEventArgs(NotifyCollectionChangedAction.Reset));
        }
```

Like this and you're done without triggering multiple events.

**Comment by symbiogenesis** [comment] 2023-01-26 01:54
> Adding/removing items from the collection isn't the problem of this ticket (that is, in fact, the workaround). The problem is related to the way MAUI uses the components underneath (WinUI) to render the collection if the binding changes (you assign a new one). As long as you stay with a single observablecollection and keep refreshing it it's fine and it doesn't break.
> 
> Also you don't need to do a whole new class to have an AddRange. Just inherit from ObservableCollection and add the method
> 
> ```csharp
>         public void AddRange(IEnumerable<T> items)
>         {
>             this.CheckReentrancy();
>             foreach (var item in items)
>                 this.Items.Add(item);
>             this.OnCollectionChanged(new NotifyCollectionChangedEventArgs(NotifyCollectionChangedAction.Reset));
>         }
> ```
> 
> Like this and you're done without triggering multiple events.

I like your code. I've been using something similar that I found on StackOverflow which does the same thing via extensions without needing to inherit.

```csharp
public static class ObservableCollectionExtensions
{
    public static void AddRange<T>(this ObservableCollection<T> collection, IEnumerable<T> items)
    {
        if (collection is null || items?.Any() != true)
        {
            return;
        }

        var type = collection.GetType();

        if (type.BaseType is null)
        {
            return;
        }

        _ = type.InvokeMember("CheckReentrancy", BindingFlags.Instance | BindingFlags.InvokeMethod | BindingFlags.NonPublic, null, collection, null, CultureInfo.InvariantCulture);

        var itemsProp = type.BaseType.GetProperty("Items", BindingFlags.NonPublic | BindingFlags.FlattenHierarchy | BindingFlags.Instance);

        if (itemsProp == null)
        {
            return;
        }

        var privateItems = (IList<T>)(itemsProp.GetValue(collection) ?? throw new FieldAccessException("list has no Items"));
        foreach (var item in items)
        {
            privateItems.Add(item);
        }

        _ = type.InvokeMember(
            "OnPropertyChanged",
            BindingFlags.Instance | BindingFlags.InvokeMethod | BindingFlags.NonPublic,
            null,
            collection,
            new object[] { new PropertyChangedEventArgs("Count") },
            CultureInfo.InvariantCulture);

        _ = type.InvokeMember(
            "OnPropertyChanged",
            BindingFlags.Instance | BindingFlags.InvokeMethod | BindingFlags.NonPublic,
            null,
            collection,
            new object[] { new PropertyChangedEventArgs("Item[]") },
            CultureInfo.InvariantCulture);

        _ = type.InvokeMember(
            "OnCollectionChanged",
            BindingFlags.Instance | BindingFlags.InvokeMethod | BindingFlags.NonPublic,
            null,
            collection,
            new object[] { new NotifyCollectionChangedEventArgs(NotifyCollectionChangedAction.Replace, newItems: items.ToList(), oldItems: Array.Empty<T>()) },
            CultureInfo.InvariantCulture);
    }

    public static void RemoveRange<T>(this ObservableCollection<T> collection, IEnumerable<T> items)
    {
        if (collection is null || items?.Any() != true)
        {
            return;
        }

        var type = collection.GetType();

        if (type.BaseType is null)
        {
            return;
        }

        _ = type.InvokeMember("CheckReentrancy", BindingFlags.Instance | BindingFlags.InvokeMethod | BindingFlags.NonPublic, null, collection, null, CultureInfo.InvariantCulture);

        var itemsProp = type.BaseType.GetProperty("Items", BindingFlags.NonPublic | BindingFlags.FlattenHierarchy | BindingFlags.Instance);

        if (itemsProp == null)
        {
            return;
        }

        var privateItems = (IList<T>)(itemsProp.GetValue(collection) ?? throw new FieldAccessException("list has no Items"));
        foreach (var item in items)
        {
            _ = privateItems.Remove(item);
        }

        _ = type.InvokeMember(
            "OnPropertyChanged",
            BindingFlags.Instance | BindingFlags.InvokeMethod | BindingFlags.NonPublic,
            null,
            collection,
            new object[] { new PropertyChangedEventArgs("Count") },
            CultureInfo.InvariantCulture);

        _ = type.InvokeMember(
            "OnPropertyChanged",
            BindingFlags.Instance | BindingFlags.InvokeMethod | BindingFlags.NonPublic,
            null,
            collection,
            new object[] { new PropertyChangedEventArgs("Item[]") },
            CultureInfo.InvariantCulture);

        _ = type.InvokeMember(
            "OnCollectionChanged",
            BindingFlags.Instance | BindingFlags.InvokeMethod | BindingFlags.NonPublic,
            null,
            collection,
            new object[] { new NotifyCollectionChangedEventArgs(NotifyCollectionChangedAction.Replace, newItems: Array.Empty<T>(), oldItems: items.ToList()) },
            CultureInfo.InvariantCulture);
    }
}
```

**Comment by DamianSuess** [comment] 2023-02-19 22:57
This issue does happen with Adding and Removing items from the ListView.

The simple example below inserts an item to the top of the ListView and removes the bottom-most item from the list. As you can see from the screenshot, there is a strong amount of GC pressure and it never goes down. Even after stopping this test loop (_not pictured_), the memory is still spiked.

Unfortunately, this cripples our application where we are presenting a live data stream of the most recent items. When the flow is coming in every 50ms, it takes only a mere 30 seconds for the application to become unusable.

```cs
  public ObservableCollection<string> PacketCache
  {
    get => _packetCache;
    set => SetProperty(ref _packetCache, value);
  }

  public DelegateCommand<string> CmdTest => new((string _) =>
  {
    int x = 0;
    for (;;)
    {
      PacketCache.Insert(0, x.ToString());
      if (PacketCache.Count >= 100)
        PacketCache.RemoveAt(99);
      x++;
    }
  });
```

```xml
    <ListView ItemsSource="{Binding PacketCache}"
              SelectedItem="{Binding PacketSelected}"
              SelectionMode="Single">
      <ListView.ItemTemplate>
        <DataTemplate x:DataType="x:String">
          <ViewCell>
            <Label Text="{Binding .}" FontFamily="Consolas" />
          </ViewCell>
        </DataTemplate>
      </ListView.ItemTemplate>
    </ListView>
```

![image](https://user-images.githubusercontent.com/1216684/219980029-b5ba2e7d-919f-4662-aee8-497230aa3d31.png)

**Comment by jonathanpeppers** [comment] 2023-04-18 18:01
At first, I thought this one might be fixed by these:

* https://github.com/dotnet/maui/pull/13260
* https://github.com/dotnet/maui/pull/13304
* https://github.com/dotnet/maui/pull/13327
* https://github.com/dotnet/maui/pull/13333
* https://github.com/dotnet/maui/pull/13400
* https://github.com/dotnet/maui/pull/13530
* https://github.com/dotnet/maui/pull/13550
* https://github.com/dotnet/maui/pull/13656
* https://github.com/dotnet/maui/pull/13806
* https://github.com/dotnet/maui/pull/13833

But it is it is *nearly* fixed. It appears to leak around 28 objects as you navigate to the new page and back.

I found if I commented out the code in two pages:
```
ToolbarItems.Add(new ToolbarItem("Refresh", "ic_refresh.png", () => {
    listView.ItemsSource = GenerateDisplayItems();
}));
```

Then it is *completely* solved as memory goes up and down a small amount:

![image](https://user-images.githubusercontent.com/840039/232863530-06390a28-732f-43fc-81e8-dbd3b65bb4cf.png)

I will investigate further, as it points to a potential memory leak in `Page.ToolbarItems`.

**Comment by jonathanpeppers** [comment] 2023-04-19 18:39
After further investigation for this sample today:

1. Tested latest dotnet/maui/main.
1. I put `GC.Collect(); GC.WaitForPendingFinalizers();` in the sample.
1. Tested a `Release` build of the app on Windows.

I *believe* the problems here are now fixed in dotnet/maui/main. Likely #13260 and #14329 specifically.

I can see the memory go up by a very small amount, and then goes down:

![image](https://user-images.githubusercontent.com/840039/233167877-258536ae-667e-4168-9a9b-35f55f3d8746.png)

When it goes down, it appears to hit the threshold established in `WeakList<T>` in #13260.

I also tried adding `ToolbarItem` in this unit test (which passes successfully):

https://github.com/dotnet/maui/blob/ee6677a0940977ddc8a54092ae6afa1fc9ad6131/src/Controls/tests/DeviceTests/Elements/NavigationPage/NavigationPageTests.cs#L295-L296

I believe this problem is solved, but I'm always willing to try other sample projects to see if I find anything wrong. You should be able to test these changes in upcoming .NET 8 previews.

Thanks!

**Closed by jonathanpeppers** 2023-04-19 18:39 UTC
Labels: t/bug, platform/windows 🪟, p/1, area/perf 🏎️, area/collectionview 📃, area/ListView

**Comment by DamianSuess** [comment] 2023-04-20 05:10
@jonathanpeppers Thank you, sir! Always appreciate you taking care of Xamarin/MAUI and providing your magical touch of precision 👍
