### ISSUE TITLE
Remaining Todo items in Android WebKitWebViewClient

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/maui#6002] opened 2022-04-12 16:32 UTC
There are a couple of potentially important "todo" comments left in `WebKitWebViewClient.cs`:

```cs
// TODO: How do we know this runs only once?
```

```cs
// TODO: we need to protect against double initialization because the
// OnPageFinished event refires after the app is brought back from the 
// foreground and the webview is brought back into view, without it actually
// getting reloaded.
```

**Comment by TanayParikh** [comment] 2022-04-14 23:22
@Eilon, just to confirm my understanding, is the goal here to restrict `RunBlazorStartupScripts` initialization to once per URL?

Ex. once for `/`, another time for `/other` but if the user navigates back to `/` then the `RunBlazorStartupScripts` does **not** re-run, likewise for a subsequent navigation to `/other` the script isn't re-run.

If so, thinking of just doing a HashSet or initialized uris.

**Comment by SteveSandersonMS** [comment] 2022-04-15 08:50
My guess is that the current logic is actually correct already. We're attaching the scripts each time a page-within-our-app-origin finishes loading (underlying event appears to be [Android WebViewClient's onPageFinished](https://developer.android.com/reference/android/webkit/WebViewClient#onPageFinished(android.webkit.WebView,%20java.lang.String))).

I think that's what should happen because:

 * For client-side navigations (ones managed by Blazor), the page isn't considered to have loaded, so we wouldn't be reattaching the scripts
 * For full-page reloads, e.g., after an error or after coming back from an external page, we do want to reattach the scripts

So unless anyone's able to find a problem, and given that we haven't seen any problems with double-events or similar, I expect we can just remove the "todo" comments.

**Comment by Eilon** [comment] 2022-04-15 15:55
Didn't we see some issue recently about reloading on Android? You'd see an F12 console warning from Blazor saying that Blazor was already started. I can't seem to find that issue anymore. I don't remember what the issue was or what the root cause was.

**Comment by Eilon** [comment] 2022-04-15 16:11
OK these are the issues I was probably thinking about:

* https://github.com/dotnet/maui/pull/5212 (merged PR)
* https://github.com/dotnet/maui/issues/5850 (bug still open)

Not sure how/if these are relevant or related.

**Comment by TanayParikh** [comment] 2022-04-15 21:54
Thanks folks for the details. Confirmed, this issue is directly related to https://github.com/dotnet/maui/issues/5850. 

Created https://github.com/dotnet/maui/pull/6143

**Closed** 2022-04-15 23:07 UTC
Labels: platform/android 🤖, area/blazor 🕸️, investigate
