### ISSUE TITLE
Databinding errors on ListView - What am I doing wrong?

### ISSUE THREAD

**Issue by enjoysmath** [dotnet/maui#19873] opened 2024-01-12 23:59 UTC
ListView ItemTemplate Data-binding currently gets these Errors at run-time and also the styling looks way off:

https://stackoverflow.com/q/77809597/7076615

I can't switch to CollectionView for unrelated / independent other error(s).

### Discussed in https://github.com/dotnet/maui/discussions/10277

<div type='discussions-op-text'>

<sup>Originally posted by **danielcooper-hk** September 22, 2022</sup>
Hi everyone,

I am pulling what little hair I have left out over this - if someone can point me in the right direction I would be very grateful.

When the application runs there are no binding errors but when I click on the button to run the AddItemCommand the item appears in the list view but I get data binding errors on both Name and Description.  What am I doing wrong in the ListView to cause this?

Thanks,

Dan.

I've written the following sample:

My MainPageModel:

```
namespace ListViewMVVM.Models;

public class MainPageModel
{
    public string Name { get; set; } = string.Empty;

    public string Description { get; set; } = string.Empty;
}
```

My MainPageViewModel:

```
namespace ListViewMVVM.ViewModels;

public class MainPageViewModel 
{
    public ICommand AddItemCommand { get; private set; }

    private ObservableCollection<MainPageModel> myItems;
    public ObservableCollection<MainPageModel> MyItems
    {
        get { return myItems; }
        set
        {
            if (myItems == value) return;

            myItems = value;
        }
    }

    public MainPageViewModel()
    {
        myItems = new()
        {
            new Models.MainPageModel { Name = "Item 1", Description = "Description 1" },
            new Models.MainPageModel { Name = "Item 2", Description = "Description 2" },
            new Models.MainPageModel { Name = "Item 3", Description = "Description 3" }
        };

        AddItemCommand = new Command(AddRecord);
    }

    public void AddRecord()
    {
        myItems.Add(new Models.MainPageModel
        {
            Name = "Item" + (myItems.Count + 1).ToString(), Description = "Description " + (myItems.Count + 1).ToString()
        }) ;

    }
}
```

My MainPage.xaml:

```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:viewmodels="clr-namespace:ListViewMVVM.ViewModels"
             xmlns:models="clr-namespace:ListViewMVVM.Models"
             x:Class="ListViewMVVM.MainPage">

   <ContentPage.BindingContext>
        <viewmodels:MainPageViewModel/>
    </ContentPage.BindingContext>
    
    <ScrollView>
        <VerticalStackLayout>

            <ListView x:Name="ListViewItems"
                      ItemsSource="{Binding MyItems}">
                <ListView.ItemTemplate>
                    <DataTemplate x:DataType="models:MainPageModel">
                        <TextCell Text="{Binding Name}"
                      Detail="{Binding Description}" />
                    </DataTemplate>
                </ListView.ItemTemplate>


            </ListView>

            <Button
                Text="Add Next"
                Command="{Binding AddItemCommand}"
                HorizontalOptions="Center" />

        </VerticalStackLayout>
    </ScrollView>

</ContentPage>

```

And finally the MainPage.xaml.cs:

```
namespace ListViewMVVM;

public partial class MainPage : ContentPage
{
	public MainPage()
	{
		InitializeComponent();
	}
}
```
</div>

**Comment by drasticactions** [comment] 2024-01-15 05:10
If you're seeing errors in the Visual Studio UI but the actual MAUI UI looks fine, it could be an issue with the tooling. @spadapet What do you think?

**Comment by enjoysmath** [comment] 2024-01-15 06:54
Well the whole structure of my app just got amended in design.  So now we're doing everything with static pages, and a link to the parent view model is precisely what I need.    So you can either fix or close this :)

**Comment by spadapet** [comment] 2024-01-16 22:16
> If you're seeing errors in the Visual Studio UI but the actual MAUI UI looks fine, it could be an issue with the tooling. @spadapet What do you think?

I think this is the same bug as:
* https://github.com/dotnet/maui/issues/8433

The binding failures UI in VS shows that MAUI's ListView is temporarily using the wrong data context when new items are added. The data context is supposed to be `MainPageModel`, not `MainPageViewModel`.

![image](https://github.com/dotnet/maui/assets/2523431/860dd637-c3ee-4bc3-ad0c-bbc386bee383)

The correct data context will get set on the new items, but the initial error is still logged in the binding failures UI in VS. I'd guess it's a bug in ListView and not a problem with Visual Studio. Using the VS feedback tool isn't going to help more than the [main MAUI issue](https://github.com/dotnet/maui/issues/8433).

cc: @drasticactions

**Comment by drasticactions** [comment] 2024-01-17 00:44
Okay, I wasn't sure of the context. We can close this as a duplicate of https://github.com/dotnet/maui/issues/8433.

**Closed by drasticactions** 2024-01-17 00:44 UTC
Labels: area/Xaml </>, area/tooling ⚙️, area/ListView, s/move-to-vs-feedback
