### ISSUE TITLE
Getting object reference error while implement localization 

### ISSUE THREAD

**Issue by zeus2nawaz** [dotnet/maui#2379] opened 2021-09-03 03:40 UTC
I want to perform localization MAUI
I had added three resources, en, ta, fr and adding picker to pick language 
But when I pick the language it gives me error object reference error, I had handle try catch block every possible in code, still not found from where it gives me error

Please help me to resolve this one
I am using .Net version RC1 
![image](https://user-images.githubusercontent.com/53426219/131947145-cf8c21a6-5e9c-4e13-98aa-263e8dba62d5.png)

NOTE:
Same code is working fine in Xamarin form project

**Comment by jsuarezruiz** [comment] 2021-11-05 11:15
Could you attach a small sample where reproduce the issue?

**Comment by hartez** [comment] 2022-01-05 22:35
Duplicate of #2345

**Closed by hartez** 2022-01-05 22:35 UTC
Labels: t/bug, s/needs info ❓, area/controls 🎮
