### ISSUE TITLE
Microsoft.UI.Xaml does not exist in the namespace 'Microsoft'

### ISSUE THREAD

**Issue by SenexTech** [dotnet/maui#4931] opened 2022-02-25 18:33 UTC
### Description

I created new project using the .NET MAUI App (Preview) template. Open Platforms/Windows/App.xaml.cs. Build the project.  You get 5 errors.

Error CS0234 The type or namespace name 'UI' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) 

Error CS0246 The type or namespace name 'MauiWinUIApplication' could not be found (are you missing a using directive or an assembly reference?) 

Error CS0115 'App.CreateMauiApp()': no suitable method found to override Calezoo (net6.0-android), Calezoo (net6.0-ios), 

Error XLS0414 The type 'maui:MauiWinUIApplication' was not found. Verify that you are not missing an assembly reference and that all referenced assemblies have been built. 

Error CS1061 'App' does not contain a definition for 'InitializeComponent' and no accessible extension method 'InitializeComponent' accepting a first argument of type 'App' could be found (are you missing a using directive or an assembly reference?) 

The using Microsoft.UI.Xaml; statement has a red sqiggle under the UI and says UI is not found in namespace.

I tried adding Microsoft.UI.Xaml with Nuget and no difference.
![maui](https://user-images.githubusercontent.com/45659887/155768188-cac6f4df-a2ec-481e-b4f8-0eb91aeea80d.jpg)

Using Microsoft Visual Studio Community 2022 (64-bit) - Preview
Version 17.2.0 Preview 1.0

### Steps to Reproduce

1. I created new project using the .NET MAUI App (Preview) template. 
2. Open Platforms/Windows/App.xaml.cs. 
3. Build the project.  You get 5 errors.

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

net6.0-windows 10.0.19041

### Did you find any workaround?

No

[AB#1489285](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1489285)

**Comment by Redth** [comment] 2022-02-25 19:06
What version of MAUI are you using (what version of Visual Studio)?

Also, in your .csproj, what version of the Windows App SDK package is listed?

**Comment by SenexTech** [comment] 2022-02-25 23:55
Using Microsoft Visual Studio Community 2022 (64-bit) - Preview Version 17.2.0 Preview 1.0
<PackageReference Include="Microsoft.WindowsAppSDK" Version="1.0.0" />

**Comment by SenexTech** [comment] 2022-02-25 23:56
Microsoft.WindowsAppSDK" Version="1.0.0"

**Comment by YuqinSong** [comment] 2022-02-28 01:35
Verified Repro. Repro project is available:
[#4931.zip](https://github.com/dotnet/maui/files/8149926/4931.zip)

**Comment by nextfool** [comment] 2022-02-28 07:11
I can also confirm this as a bug, please see the screenshot bellow:
![image](https://user-images.githubusercontent.com/2167369/155939367-95e86d70-201d-4493-9ea5-25fae21bd623.png)

In fact I even had some trouble installing/uninstalling the package "Microsoft.WindowsAppSDK" with both nuget GUI and package console.  If I install it with ```dotnet add package Microsoft.WindowsAppSDK --version 1.0.0``` , the whole project won't load.

**Comment by drasticactions** [comment] 2022-03-04 01:08
![image](https://user-images.githubusercontent.com/898335/156679630-f67712e5-5b05-4b9e-834f-11e45d5598e6.png)

In the dropdown, the TFM is "net6.0-android", so it won't show Windows APIs. You need to make sure that this code, specific for WinUI, is _only_ in net6.0-windows (By using the Platform folders in MAUI, `ifdef`s, or using a targets file.

**Comment by egvijayanand** [comment] 2022-03-04 10:42
Seems like some logic is developed based on the first `TargetFrameworks` that is available in the list.

And something is done on that in 17.2 Preview 1.0 resulting in Platforms folder files working this way.

**Comment by drasticactions** [comment] 2022-03-04 14:03
@egvijayanand The Platform folder works by a MultiTargetting Targets file that's loaded for all MAUI projects, https://github.com/dotnet/maui/blob/main/.nuspec/Microsoft.Maui.Controls.MultiTargeting.targets

It has nothing to do with Visual Studio.

The dropdown menu, I believe, is either Alphabetical or controlled by the list order in the csproj. When you switch it and open a new file, it will use the last one you had selected. But the point here is that if you select net6.0-windows, and make a change that's _only_ for Windows, it will show that it's all correct, but will fail again if you select the android TFM, or try to build. That's by design and very much intentional since the point is that you can have multiple targets.

So you, the developer, need to either block off the platform-specific code inside of platform specific files, or with ifdefs.

**Comment by egvijayanand** [comment] 2022-03-04 15:12
@drasticactions, Prior to VS 17.2 Preview 1.0, when working inside the Platforms folder, the platform switcher drop-down worked fine without any issues.

For example, when opening a file under the `Platforms\Android` folder, the platform switcher would automatically detect and set it to <ProjectName> (net6.0-android) and similarly for others too.

But in this version, referring to the below screenshot, have opened a file (AppDelegate.cs) from the `Platforms\iOS` folder, the platforms drop-down still pointing to `Pre13App (net6.0-android)`, and hence showing red squiggles all over the file (In fact it's an OOB definition and not even a single edit from the developer).

Being a single project multi-targeted solution, it's the minimum expectation that the platform switcher should point to the right platform.

![image](https://user-images.githubusercontent.com/81947404/156786549-28d6442c-02bc-48fe-afb1-43bd312c3b46.png)

The point to note here is the first listed TargetFrameworks alone is working fine (Have modified the project file to have `net6.0-ios` as first in the list).

<img width="587" alt="image" src="https://user-images.githubusercontent.com/81947404/156788386-4347a47b-db11-47a7-83f0-811d51c172b7.png">

![image](https://user-images.githubusercontent.com/81947404/156788630-4b5893ba-f9dd-4f20-94b7-4f0eb17a5383.png)

**Comment by drasticactions** [comment] 2022-03-04 21:04
@egvijayanand The platform switcher "Automatically switches" because of the targets file I linked to, that's what's doing it. It's saying to the project system "Any file put inside this directory is only for net6.0-android" hence why it's the only one in the list.

If you're putting files into the iOS folder and seeing "Android" TFMs, then there's either a problem with that targets file, or an issue with Visual Studio not recognizing it correctly (in which case, you can test it by doing a build from CLI. If it works there, but fails in VS, it's a VS issue.

**Comment by egvijayanand** [comment] 2022-03-05 07:34
> If you're putting files into the iOS folder and seeing "Android" TFMs, then there's either a problem with that targets file, or an issue with Visual Studio not recognizing it correctly (in which case, you can test it by doing a build from CLI. If it works there, but fails in VS, it's a VS issue.

@drasticactions That's my concern also, opening a file from the `iOS` folder but showing it as `net6.0-android`. It worked previously and is now broken in 17.2 Preview 1.0

And as far as build is concerned, it works without any issues in both .NET CLI and VS.

**Comment by domingoladron** [comment] 2022-03-07 20:02
I'm encountering this very same issue, but it wasn't from the very start of creating a project.  

I actually had a working version of Maui Blazor app running in Windows / iOS / Android.  

I'd added a number of pages to it, customised it with custom razor nuget packages, and it was working fine (or so I thought).

Then, without any change which would have impacted the reference to Microsoft.UI.Xaml or MauiWinUIApplication, the android and iOS platforms just stopped compiling with the errors mentioned above.

I rolled back my minor change (though I was 99% sure it was unrelated), but nope.  Nothing I tried would fix it.  For now, I've been forced to comment out the android / iOS platforms until a fix is determined.  I'll keep seeing if I can work out what it might be.

For now, here are the details of my system and am happy to provide more.

**Visual Studio**
Microsoft Visual Studio Community 2022 (64-bit) - Preview
Version 17.2.0 Preview 1.0


**Microsoft.Maui Packages**
6.0.200-preview.13.2865

**Comment by nextfool** [comment] 2022-03-09 01:25
Hi, do we have an ETA of fixing for this issue, apparently this is a blocker for multi-targeting. It would be great if this can be fixed in next preview. Thank you.

**Comment by mdimai666** [comment] 2022-03-14 11:58
I have after using the command `maui-check  --pre`. The problem is gone. (after this app crash on start)
and run `dotnet workload update` 
VS2022 community preview Version 17.2.0 Preview 1.0
And works fine! =)

**Comment by Redth** [comment] 2022-03-24 19:10
Closing as a duplicate of #4726

**Closed by Redth** 2022-03-24 19:10 UTC
Labels: t/bug, s/verified, area/ide
