### ISSUE TITLE
mono_aot_corlib_init_method_gshared_mrgctx

### ISSUE THREAD

**Issue by tnmp83** [dotnet/maui#18425] opened 2023-10-30 04:34 UTC
### Description

Hi friends, I had migrate MyProject from Xamarin to Maui (net7.0). After release and receive message from crashlytics

Crashed: .NET ThreadPool Worker
0  MyProject.MAUI                  0x43737f0 mono_aot_corlib_init_method_gshared_mrgctx + 56553296
1  MyProject.MAUI                  0x4633274 corlib_System_Runtime_InteropServices_MemoryMarshal_TryGetArray_T_BYTE_System_ReadOnlyMemory_1_T_BYTE_System_ArraySegment_1_T_BYTE_ + 59435476
2  MyProject.MAUI                  0x2920d98 wrapper_runtime_invoke_object_runtime_invoke_dynamic_intptr_intptr_intptr_intptr + 28951800
3  MyProject.MAUI                  0x4e3d250 mono_jit_runtime_invoke + 3526 (mini-runtime.c:3526)
4  MyProject.MAUI                  0x4d7c124 mono_runtime_invoke_checked + 2415 (object.c:2415)
5  MyProject.MAUI                  0x4e41864 mono_gsharedvt_constrained_call + 1477 (jit-icalls.c:1477)
6  MyProject.MAUI                  0x29255d8 wrapper_managed_to_native_object___icall_wrapper_mono_gsharedvt_constrained_call_intptr_intptr_intptr_intptr_intptr + 28970296
7  MyProject.MAUI                  0x28d9ee4 System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_TStateMachine_GSHAREDVT_TStateMachine_GSHAREDVT_ + 28661316
8  MyProject.MAUI                  0x45ccad4 corlib_System_IO_Stream__CopyToAsyncg__Core_27_0_System_IO_Stream_System_IO_Stream_int_System_Threading_CancellationToken + 59015732
9  MyProject.MAUI                  0x2606078 System.Net.Http.HttpClient/<<SendAsync>g__Core_83_0>d:MoveNext + 1 (<unknown>:1)
10 MyProject.MAUI                  0x3810394 System_Net_Http_System_Runtime_CompilerServices_AsyncTaskMethodBuilder_1_AsyncStateMachineBox_1_System_Net_Http_HttpResponseMessage_System_Net_Http_HttpClient___SendAsyncg__Core_83_0d_ExecutionContextCallback_object + 44612340
11 MyProject.MAUI                  0x45144a4 corlib_System_Threading_Thread_StartCallback + 58260484
12 MyProject.MAUI                  0x4e3d250 mono_jit_runtime_invoke + 3526 (mini-runtime.c:3526)
13 MyProject.MAUI                  0x4d7c124 mono_runtime_invoke_checked + 2415 (object.c:2415)
14 MyProject.MAUI                  0x4d95c78 start_wrapper_internal + 1215 (threads.c:1215)
15 MyProject.MAUI                  0x4d95a08 start_wrapper + 1266 (threads.c:1266)
16 libsystem_pthread.dylib        0x24d4 _pthread_start + 136
17 libsystem_pthread.dylib        0x1a10 thread_start + 8

### Version with bug

7.0.96

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

7.0.96

### Affected platforms

iOS

### Affected platform versions

iOS 17.0.3

### Did you find any workaround?

`<PropertyGroup Condition="$(TargetFramework.Contains('-ios')) and '$(Configuration)' == 'Release'">
   <MtouchLink>SdkOnly</MtouchLink>
   <UseInterpreter>true</UseInterpreter>
</PropertyGroup>`

**Comment by tnmp83** [comment] 2023-11-14 07:02
[issues_18425.txt](https://github.com/dotnet/maui/files/13345507/issues_18425.txt)
This is full message from Crashlytics
I added the following config to build
`<PropertyGroup Condition="$(TargetFramework.Contains('-ios')) and '$(Configuration)' == 'Release'">
   <UseInterpreter>true</UseInterpreter>
</PropertyGroup>`
I'm not sure it will be fixed if added.
If anyone has tried it and got results, please let me know
Thanks friends

**Comment by ThinhKVT** [comment] 2023-11-28 03:12
We added above config but result still not good, crash still happen with same frequent. Anyone have other solution for the issue ? Please help us !!!!

**Comment by PureWeen** [comment] 2024-05-31 17:06
> [issues_18425.txt](https://github.com/dotnet/maui/files/13345507/issues_18425.txt) This is full message from Crashlytics I added the following config to build `<PropertyGroup Condition="$(TargetFramework.Contains('-ios')) and '$(Configuration)' == 'Release'"> <UseInterpreter>true</UseInterpreter> </PropertyGroup>` I'm not sure it will be fixed if added. If anyone has tried it and got results, please let me know Thanks friends

@rolfbjarne ?

**Comment by PureWeen** [comment] 2024-05-31 17:06
Duplicate of #18424

We'll keep 18424 for tracking your sets of crashes

**Closed by PureWeen** 2024-05-31 17:06 UTC
Labels: t/bug, platform/iOS 🍎, area-infrastructure, s/needs-attention, migration-compatibility

**Comment by rolfbjarne** [comment] 2024-05-31 17:15
It looks like the native symbols were stripped, which can make the crash report somewhat misleading.

I would suggest building without stripping native symbols:

```xml
<PropertyGroup>
    <NoSymbolStrip>true</NoSymbolStrip>
</PropertyGroup>
```

and then trigger the crash again and getting a new crash report.
