### ISSUE TITLE
Maui deploy on Android corrupted System

### ISSUE THREAD

**Issue by THoferSchmitz** [dotnet/maui#3528] opened 2021-11-23 16:26 UTC
### Description

Hello,

I started testing the .Net Maui Preview 10 and encountered a bug on Windows (see [#3524](https://github.com/dotnet/maui/issues/3524)). I wanted to see, if this would also happen on my Android tablet. I didn't install the emulator and didn't worry much as this was basically the default template app created by Visual Studio. I started the app from Visual Studio on my device via wifi and saw the same bug, so I stopped the app.

Once the app was stopped I got a black screen. I am now unable to access anything or get to the Home Screen. I can restart the device, but that doesn't change anything. After entering my password I only have a few second before I get the black screen again. Therefore I couldn't try removing the app as I can't reach it via screen or settings.

Connecting to adb isn't working either. After connecting via usb I got a few seconds more and sometimes I can get back to the Home Screen from that black screen for a few seconds before everything freezes again. That way, after several attempts, I was able to try disabling the developer mode, which also didn't help.

I am still trying to find a way to get it to work again without a hard reset, but for more than an hour I wasn't able to make any considerable progress.

### Steps to Reproduce

see [#3524](https://github.com/dotnet/maui/issues/3524) on Android

### Version with bug

Preview 10 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Version unknown due to the Problems, I think 9

**Comment by THoferSchmitz** [comment] 2021-12-01 13:59
Hi. I did not install the Microsoft Launcher. The app itself didn't crash either. In the end, I had to do a factory reset to be able to use the tablet again.

**Comment by LeGone** [comment] 2022-02-04 14:56
You can connect to your phone (adb shell) and uninstall the app:
pm uninstall -k --user 0 com.companyname.mauiapp1

That worked for me. Hope it might help someone.

**Comment by PineYi** [comment] 2022-02-28 06:52
Duplicate of #3524

**Comment by Redth** [comment] 2022-04-25 15:30
If you are able to repro this in the future and attach a project with the repro, please open a new issue.

**Closed by Redth** 2022-04-25 15:30 UTC
Labels: t/bug, platform/android 🤖, area/publishing 🏁, s/verified
