### ISSUE TITLE
PushModalAsync ignored at application startup

### ISSUE THREAD

**Issue by YiannisBourkelis** [dotnet/maui#11745] opened 2022-11-29 23:13 UTC
### Description

At application startup, if I push a modal page, it is placed on the modal pages stack of the Navigation controller, but it never shows.

### Steps to Reproduce

Run the attached sample code.

Look inside the App.xaml.cs:

```
public App()
{
      InitializeComponent();

      MainPage = new NavigationPage(new MainPage());

      Application.Current.MainPage.Navigation.PushModalAsync(new NavigationPage(new LoginPage()));

      Console.WriteLine($"ModalStack count: {Application.Current.MainPage.Navigation.ModalStack.Count}");

  }
```

I am calling PushModalAsync to display the LoginPage, however the MainPage is shown.

I tried to simplify the code as much as I can. It is from a Xamarin.Forms app I am trying to migrate to MAUI. The above code works fine on Xamarin.Forms. The issue is on MAUI.

### Link to public reproduction project repository

https://github.com/YiannisBourkelis/maui_issues/tree/main/src/MauiPushModalAsyncIssue

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

All. On Windows it also raises an unhandled win32 exception

### Did you find any workaround?

No

**Comment by PureWeen** [comment] 2022-11-30 19:34
Duplicate of #8157

**Closed by PureWeen** 2022-11-30 19:34 UTC
Labels: t/bug, area/navigation 🧭, area/modal
