### ISSUE TITLE
MAUI project iOS simulator startup failed MT7091

### ISSUE THREAD

**Issue by jason-apj** [dotnet/maui#16886] opened 2023-08-21 07:50 UTC
I have a MAUI project. When I tried to start using the iOS emulator, an error occurred. VS was able to connect to the MAC machine normally, but the emulator failed to start. The error is as follows
![image](https://github.com/dotnet/maui/assets/106130308/01af5e89-af42-4436-ad0f-8e0e5779c1b7)
onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/onnxruntime File format not recognized

I tried to search for related errors on the internet, but I couldn't find a similar situation, and I couldn't find any relevant information about MT7091 either。
My VS version is 2022 17.7.1

I tried to clear up the Nuget cache, but it didn't work.

I am very distressed and don't know how to solve it. I hope someone can help me.

**Comment by drasticactions** [comment] 2023-08-22 05:20
https://github.com/xamarin/xamarin-macios/issues/18348

@rolfbjarne Could it be this issue?

**Comment by jason-apj** [comment] 2023-08-22 06:06
> [xamarin/xamarin-macios#18348](https://github.com/xamarin/xamarin-macios/issues/18348)
> 
> @rolfbjarne Could it be this issue?
> 
> @jason-apj Most likely, this issue isn't related to the MAUI UI project or code inside this repo. It's probably in the [SDK tooling](https://github.com/xamarin/xamarin-macios), Visual Studio tooling, or potentially that nuget.
I have seen this issue and I have tried to clear the Nuget cache multiple times, but it seems to have no effect.

The latest discovery is that I have created a blank MAUI project that can successfully load the emulator, but the project that reported an error still does not work. Some of my colleagues can successfully start the emulator by running this project, but I cannot

**Comment by jason-apj** [comment] 2023-08-22 06:07
> [xamarin/xamarin-macios#18348](https://github.com/xamarin/xamarin-macios/issues/18348)
> 
> @rolfbjarne Could it be this issue?
> 
> @jason-apj Most likely, this issue isn't related to the MAUI UI project or code inside this repo. It's probably in the [SDK tooling](https://github.com/xamarin/xamarin-macios), Visual Studio tooling, or potentially that nuget.

@drasticactions I have seen this issue and I have tried to clear the Nuget cache multiple times, but it seems to have no effect.
The latest discovery is that I have created a blank MAUI project that can successfully load the emulator, but the project that reported an error still does not work. Some of my colleagues can successfully start the emulator by running this project, but I cannot

**Comment by rolfbjarne** [comment] 2023-08-22 09:26
> @rolfbjarne Could it be this issue?

Yes, this is a dup of https://github.com/xamarin/xamarin-macios/issues/18348.

> The latest discovery is that I have created a blank MAUI project that can successfully load the emulator

That's because a blank project doesn't reference any NuGets with native frameworks.

> I have seen this issue and I have tried to clear the Nuget cache multiple times, but it seems to have no effect.

Can you try:

1. Close Visual Studio.
2. Delete the directory `C:/Users/daizhimin/.nuget` on your Windows machine.
3. Delete the directory `~/Library/Caches/Xamarin/XMA` on your Mac.
4. Setup binlog capture for Visual Studio as described here: https://github.com/xamarin/xamarin-macios/wiki/Diagnosis#binary-build-logs
5. Launch Visual Studio and connect to the Mac (this will take a little while since everything will have to be reinstalled on the Mac)
6. Build your project once to reproduce the error.
7. Upload the binlog from the build here.

**Comment by rmarinho** [comment] 2023-08-25 14:28
Closing for now we can follow up https://github.com/xamarin/xamarin-macios/issues/18348.

**Closed by rmarinho** 2023-08-25 14:28 UTC
Labels: area/tooling ⚙️
