### ISSUE TITLE
Screenshot (Essentials API) not working in Windows platform

### ISSUE THREAD

**Issue by egvijayanand** [dotnet/maui#5378] opened 2022-03-17 11:38 UTC
### Description

Screenshot (Essentials API) not working on Windows platform.

Though Screenshot.IsCaptureSupported returns true, on invoking the CaptureAsync() method, it is failing with the error message `Unable to find main window content.`

### Steps to Reproduce

1. Create a new .NET MAUI App
2. Add the Screenshot, Essentials API, in any of the button click event handler (or command method)
3. Use the code snippet from this official documentation page https://docs.microsoft.com/en-us/xamarin/essentials/screenshot?context=xamarin/xamarin-forms (ignore the Xamarin.Essentials namespace snippet)
4. Set Windows as the target platform, run the project, and invoke the action
5. Fails with the message `Unable to find main window content.`

### Version with bug

Preview 14 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows SDK 10.0.19041

### Did you find any workaround?

Nope

### Relevant log output

```shell
System.InvalidOperationException
  HResult=0x80131509
  Message=Unable to find main window content.
  Source=Microsoft.Maui.Essentials
  StackTrace:
   at Microsoft.Maui.Essentials.Implementations.ScreenshotImplementation.<CaptureAsync>d__2.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at MenuApp.ViewModels.MainViewModel.<ShareScreenshotAsync>d__4.MoveNext() in E:\MenuApp\MenuApp\ViewModels\MainViewModel.cs:line 26
```

**Comment by shimingsg** [comment] 2022-03-18 06:12
verified repro with vs 17.2.0 Preview 3.0 [32317.292.main]  on windows:
```
System.InvalidOperationException
  HResult=0x80131509
  Message=Unable to find main window content.
  Source=Microsoft.Maui.Essentials
  StackTrace:
   at Microsoft.Maui.Essentials.Implementations.ScreenshotImplementation.<CaptureAsync>d__2.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at MauiApp5378.MainPage.<OnCounterClicked>d__2.MoveNext() in C:\Users\Administrator\source\repos\MauiApp5378\MauiApp5378\MainPage.xaml.cs:line 19

  This exception was originally thrown at this call stack:
    [External Code]
    MauiApp5378.MainPage.OnCounterClicked(object, System.EventArgs) in MainPage.xaml.cs
```
repro demo:
[MauiApp5378.zip](https://github.com/dotnet/maui/files/8302021/MauiApp5378.zip)

**Comment by jsuarezruiz** [comment] 2022-03-28 12:40
Cannot reproduce the issue on main branch. @mattleibow You updated the ScreenshotImplementation on Windows recently, could you confirm?

**Comment by mattleibow** [comment] 2022-03-28 13:16
I think this is fixed in rc 1.

**Closed** 2022-03-28 13:17 UTC
Labels: t/bug, area/essentials 🍞, fatal, s/verified

**Comment by egvijayanand** [comment] 2022-03-28 13:23
There should be an intermediate status as `Resolved`. Since there's no option for the creator to reopen the issue, issues that are addressed but not yet released should be marked as `Resolved` and not `Closed`.
