### ISSUE TITLE
ScrollView within ScrollView, outer partly stops working after scrolling inner

### ISSUE THREAD

**Issue by tolgraven** [dotnet/maui#19323] opened 2023-12-10 11:23 UTC
### Description

I have a ScrollView containing a map up top, a Grid which gets dynamically populated with a bunch of views, some of which themselves have (horizontal) ScrollViews, and further views below, some also dynamically inserted.

Scrolling works fine until I scroll one of the inner horizontal ones, upon which the outer will no longer scroll page _when swiping vertically_ on any views. The margin space between the views still works fine for scrolling.

The only way to restore vertical scrolling is to vertically scroll one of the inner horizontal ScrollViews, which obviously does nothing to the inner but somehow releases capture and restores scrolling on the outer.

So it's as if the inner keeps capturing scroll events even when scrolling has finished and even though those events originate outside its bounding box.

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 34, Emulator, Pixel 7 Pro

### Did you find any workaround?

Tell users to scroll horizontal scrollviews vertically once they're done. Not exactly a proper workaround though...

**Comment by Phenek** [comment] 2023-12-20 13:34
#9827

**Comment by PureWeen** [comment] 2023-12-21 19:22
Duplicate of #9827

**Closed by PureWeen** 2023-12-21 19:22 UTC
Labels: t/bug, area/layout 🔲, platform/android 🤖, s/needs-attention, migration-compatibility, layout-scrollview
