### ISSUE TITLE
UdpClient on IOS: No route to host

### ISSUE THREAD

**Issue by illuminat3** [dotnet/maui#21451] opened 2024-03-26 11:40 UTC
### Description

When creating a UPD client on and broadcasting with UDP it will thow the No route to host (65) exception.

``` csharp
private readonly UdpClient _outgoingClient = new UdpClient();
private const int _outgoingPort = 8523;

byte[] bytes = Encoding.UTF8.GetBytes("test message");
_outgoingClient.Send(bytes, bytes.Length, "255.255.255.255", _outgoingPort);
```

### Steps to Reproduce

Create a new maui project in .Net8 and add a content page
in this page include the following code 

``` csharp
private readonly UdpClient _outgoingClient = new UdpClient();
private const int _outgoingPort = 8523;

private void SendMessage() {
byte[] bytes = Encoding.UTF8.GetBytes("test message");
_outgoingClient.Send(bytes, bytes.Length, "255.255.255.255", _outgoingPort);
}
```

Add a button which calls the SendMessage button.

### Version with bug

Unknown/Other

### Is this a regression from previous behavior?

No, this is something new, Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

IOS 16+

### Did you find any workaround?

The workaround appears to be using an IPEndpoint object instead of giving the upd client a hostname and port

``` csharp
_outgoingClient.Send(bytes, bytes.Length, new IPEndPoint(IPAddress.Any, _outgoingPort));
```

**Comment by jfversluis** [comment] 2024-03-26 11:43
This is something that is not specific to .NET MAUI but rather a layer deeper. I suspect this to be the runtime. I think I found an issue that describes this and I will link that here as I close this one on our repo.

**Comment by jfversluis** [comment] 2024-03-26 11:43
Duplicate of https://github.com/dotnet/runtime/issues/53767

**Closed by jfversluis** 2024-03-26 11:43 UTC
Labels: t/bug
