### ISSUE TITLE
Auto [Routing] add

### ISSUE THREAD

**Issue by jrahma** [dotnet/maui#9885] opened 2022-09-03 10:14 UTC
### Description

For MAUI, why do we need to add the Routing everytime and if not then it will throw an error.

Please let MAUI add the Routing automatically once the Page is add and remove or comment if the Page is deleted.

### Public API Changes

MAUi will automatically add:

`Routing.RegisterRoute(nameof(NewClient), typeof(NewClient));
`
when I add a new Page called NewClient

### Intended Use-Case

Make developers' life easier.

**Comment by jfversluis** [comment] 2022-09-05 10:38
Duplicate of #5312

**Closed by jfversluis** 2022-09-05 10:38 UTC
Labels: t/enhancement ☀️, proposal/open, area/navigation 🧭, area/shell 🐢
