### ISSUE TITLE
ImageButton border wrongly rendered (positioning and being clipped)

### ISSUE THREAD

**Issue by inimirpaz** [dotnet/maui#22738] opened 2024-05-30 14:10 UTC
### Description

See repro (providing both .NET MAUI and Xamarin.Forms) and the following side-by-side comparisons:

![Screenshot 2024-05-30 alle 15 58 38](https://github.com/dotnet/maui/assets/56956625/4ce27b79-f913-434c-bcd5-a4f518e75a3c)

![Screenshot 2024-05-30 alle 15 58 38 2](https://github.com/dotnet/maui/assets/56956625/fbc2bb02-dc16-484c-a222-3849abec1624)

### Link to public reproduction project repository

https://github.com/inimirpaz/maui_issues/tree/border_issue

### Version with bug

8.0.40 SR5

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

**Comment by mattleibow** [comment] 2024-05-30 16:33
I wonder if this PR that fixed a lot of Android issues with image button backgrounds will fix this one: https://github.com/dotnet/maui/pull/22298

@inimirpaz are you able to test the nightly builds and see if the issue is fixed?

**Comment by mattleibow** [comment] 2024-05-30 17:07
Duplicate of https://github.com/dotnet/maui/issues/20801

**Closed by mattleibow** 2024-05-30 17:07 UTC
Labels: t/bug, platform/android 🤖, platform/iOS 🍎, s/try-latest-version
