### ISSUE TITLE
[Android] DatePicker popup shows empty view

### ISSUE THREAD

**Issue by karthikraja-arumugam** [dotnet/maui#4254] opened 2022-01-21 11:17 UTC
### Description

The DatePicker popup shows empty month dates after two forward or backward swipes. Please refer the replication procedure and attached video

### Steps to Reproduce

1. Run sample with a DataPicker.
2. Open picker popup. Initially, it works fine.
3. Move 2 months forward or backward.
4. Click Ok or Cancel button at the bottom, without selecting any date. Now the popup will be closed.
5. Again open the popup by tapping the selected date.
6. The popup is empty now.

https://user-images.githubusercontent.com/92788387/150517694-a5829f9e-38c2-4030-849a-9290e4a54abb.mp4

### Version with bug

Preview 12 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 10.0

### Did you find any workaround?

No

### Relevant log output

```shell
NA
```

**Comment by jsuarezruiz** [comment] 2022-01-21 11:46
Seems to be the same as https://github.com/dotnet/maui/issues/3749

**Comment by zhouwangyang** [comment] 2022-02-10 04:39
Duplicate of #3749

**Comment by zhouwangyang** [comment] 2022-02-10 04:43
Duplicate of #3749

**Comment by shimingsg** [comment] 2022-02-16 06:40
Duplicate of https://github.com/dotnet/maui/issues/3749

**Closed by shimingsg** 2022-02-16 06:40 UTC
Labels: t/bug, s/duplicate 2️⃣, platform/android 🤖, area/controls 🎮, control-datetimepicker
