### ISSUE TITLE
Runtime error when using class library with render modes

### ISSUE THREAD

**Issue by musictopia2** [dotnet/maui#18812] opened 2023-11-16 18:11 UTC
### Description

I have a repository that shows the runtime error here.
https://github.com/musictopia2/RenderModeBug 

What happens is says rendermode is not supported.
What should happen is for native to ignore.
RenderMode is necessary in order to support the rendermodes if the component is used for the new blazor web app.

### Steps to Reproduce

1.   Run the project shown
2.   Go to the counter page.
3.  You will see the runtime error.

### Link to public reproduction project repository

https://github.com/musictopia2/RenderModeBug

### Version with bug

8.0.3

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Did you find any workaround?

The only workaround was to not use render modes.
However, if I don't use render modes, then I lose all the benefits to the new features to blazor in .net 8.

**Comment by XamlTest** [comment] 2023-12-01 09:43
Verified this on Visual Studio Enterprise 17.9.0 Preview 1(8.0.3). Repro on Windows 11, Android 14.0-API34, iOS 17.0 and MacCatalyst with below Project:
[RenderModeBug.zip](https://github.com/dotnet/maui/files/13523594/RenderModeBug.zip)

![image](https://github.com/dotnet/maui/assets/97647558/7437a607-5e56-4ddb-b43e-98883909d3c9)

**Comment by musictopia2** [comment] 2023-12-02 13:00
I was able to upgrade maui blazor apps from 7.0 to 8.0.
The workaround was the razor class libraries cannot use render modes.

**Comment by mkArtakMSFT** [comment] 2024-04-19 20:49
Closing as a dupe of https://github.com/dotnet/aspnetcore/issues/51235

**Closed by mkArtakMSFT** 2024-04-19 20:49 UTC
Labels: t/bug, platform/windows 🪟, area/blazor 🕸️, s/verified, s/triaged
