### ISSUE TITLE
Border does not clip when stroke shape is provided in iOS

### ISSUE THREAD

**Issue by DuckScapePhilip** [dotnet/maui#11950] opened 2022-12-08 02:27 UTC
### Description

This issue was originally reported here but never fixed: https://github.com/dotnet/maui/issues/7475

Border does not clip and the child gets overlapped.

![IMG_4256](https://user-images.githubusercontent.com/59456945/206341294-ab9ea640-bf66-40b1-ace1-ba5beaea59ad.PNG)

```
<Border StrokeShape="RoundRectangle 200" VerticalOptions="Center" HorizontalOptions="Center">
	<Image Source="{Binding Profile.PhotoURL}" HeightRequest="200" WidthRequest="200"></Image>
</Border>
```

### Steps to Reproduce

1. Create a border.
2. Place image inside of border.
3. Add border radius.
4. Launch in iPhone Debug with iOS 16
5. Observer child element overflowing the border.

### Link to public reproduction project repository

https://github.com/DuckScapePhilip/Bugs/tree/main/MauiBorderNotClipping

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 16

### Did you find any workaround?

Not yet...

**Comment by Tframe** [comment] 2022-12-08 17:29
Having same issue .net 7. Using a Frame does work for clipping, but has an issue with shadows not casting for Android, but works for iOS. #7209

**Comment by PureWeen** [comment] 2022-12-08 19:19
Duplicate of #10724

**Closed by PureWeen** 2022-12-08 19:19 UTC
Labels: t/bug
