### ISSUE TITLE
[Only Windows] InputTransparent=True makes view transparent

### ISSUE THREAD

**Issue by JTOne123** [dotnet/maui#23436] opened 2024-07-04 14:40 UTC
### Description

I want to put background on my view with InputTransparent=True, and it doesn't work on Windows. Android works well.

```xml
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MauiApp1.MainPage"
             xmlns:c="clr-namespace:MauiApp1"
             BackgroundColor="Red">

    <StackLayout Background="Blue" 
                 Margin="20"
                 
                 
                 InputTransparent="True"/>

</ContentPage>
```

![image](https://github.com/dotnet/maui/assets/3457140/f8314fbc-ad72-4226-a574-4d4a2f78b5b5)

### Steps to Reproduce

```xml
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MauiApp1.MainPage"
             xmlns:c="clr-namespace:MauiApp1"
             BackgroundColor="Red">

    <StackLayout Background="Blue" 
                 Margin="20"
                 
                 
                 InputTransparent="True"/>

</ContentPage>
```

### Version with bug

8.0.40 SR5

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI, Yes, this used to work in Xamarin.Forms, No, this is something new, Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

net8.0-windows10.0.19041.0

**Comment by RoiChen001** [comment] 2024-07-05 07:37
I can repro this issue at Windows platform on the latest 17.11.0 Preview 2.1 (8.0.40&8.0.61).

**Comment by PureWeen** [comment] 2024-07-09 18:56
@mattleibow do your PRs on inputtransparent resolve this?

**Comment by mattleibow** [comment] 2024-07-10 05:12
They do and this is a duplicate.

**Comment by mattleibow** [comment] 2024-07-10 05:12
Duplicate of https://github.com/dotnet/maui/issues/17389

**Closed** 2024-07-10 05:13 UTC
Labels: t/bug, platform/windows 🪟, s/verified, s/triaged, area-gestures

**Comment by mattleibow** [comment] 2024-07-10 05:21
This will be fixed in https://github.com/dotnet/maui/pull/23526 or maybe if I split out the changes. The issue is InputTransparent and Background use the same underlying Background property as there is no native support for input transparency with a background on Windows.
