### ISSUE TITLE
Navigation.PopModalAsync fails on Android if page is a NavigationView [.Net7]

### ISSUE THREAD

**Issue by hbraasch** [dotnet/maui#10513] opened 2022-10-06 06:53 UTC
### Description

I am forced to develop using .NET7 because somehow the current review (2.1) VS only runs iOS code developed using .NET7. So, when pushing pages onto the stack, and the page is a NavigationView, the pop operation fails for Android. It works fine for iOS and Windows.

It thows the exception [System.InvalidOperationException: 'NavigationView cannot be null']

https://user-images.githubusercontent.com/7484186/194233423-0dbf061f-516e-4673-b00b-0a0634a0b1b8.mp4

Workload List:
Installed Workload Id      Manifest Version                  Installation Source
--------------------------------------------------------------------------------
runtimes-windows           7.0.0-rc.1.22426.10/7.0.100       VS 17.4.32916.344  
maui-windows               7.0.0-rc.1.6683/7.0.100-rc.1      VS 17.4.32916.344  
maui-maccatalyst           7.0.0-rc.1.6683/7.0.100-rc.1      VS 17.4.32916.344  
maccatalyst                15.4.1029-rc.1/7.0.100-rc.1       VS 17.4.32916.344  
maui-ios                   7.0.0-rc.1.6683/7.0.100-rc.1      VS 17.4.32916.344  
ios                        15.4.1029-rc.1/7.0.100-rc.1       VS 17.4.32916.344  
maui-android               7.0.0-rc.1.6683/7.0.100-rc.1      VS 17.4.32916.344  
android                    33.0.0-rc.1.151/7.0.100-rc.1      VS 17.4.32916.344  

### Steps to Reproduce

1. Open the Github repro project under VS.
2. Run for WIN, Android and iOS platforms.
3. Click on the [Navigate away with NavPage] button.
4. Then click the [Navigate back] button.
5. Notice it fails under Android

### Link to public reproduction project repository

https://github.com/hbraasch/BasicNavigationUsingNavPageTester.git

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 12 - API 31 (Only one tested)

### Did you find any workaround?

No

**Comment by jenscski** [comment] 2022-10-06 08:40
Same as this one?
https://github.com/dotnet/maui/issues/10235

**Comment by hartez** [comment] 2022-10-06 18:15
Duplicate of #10235

**Closed by hartez** 2022-10-06 18:15 UTC
Labels: t/bug
