### ISSUE TITLE
Image from byte[] source doesn't work on Android

### ISSUE THREAD

**Issue by janseris** [dotnet/maui#6256] opened 2022-04-19 21:40 UTC
### Description

both Image and ImageButton images loaded from .resx byte[] source don't work on Android.
They work on Windows
[EmbeddedImageAndroidResx.zip](https://github.com/dotnet/maui/files/8516630/EmbeddedImageAndroidResx.zip)

![image](https://user-images.githubusercontent.com/64279914/164106676-9f170e63-f9e5-4448-9fe6-f02c93155203.png)

Related to https://github.com/dotnet/maui/issues/6228 (attempted workaround for that issue)

### Steps to Reproduce

Open attached project
Run on Android

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11 (API 30)

### Did you find any workaround?

No

**Comment by XamlTest** [comment] 2022-04-20 00:09
Verified this issue with Visual Studio Enterprise 17.3.0 Preview 1.0 [32414.199.main]. Repro on Android with above project.

**Comment by Redth** [comment] 2022-04-20 13:48
Duplicate of #6231

**Closed by Redth** 2022-04-20 13:48 UTC
Labels: t/bug, platform/android 🤖, s/verified, s/triaged
