### ISSUE TITLE
xamarin_find_protocol_wrapper_type

### ISSUE THREAD

**Issue by tnmp83** [dotnet/maui#18426] opened 2023-10-30 04:39 UTC
### Description
I had migrate My Project from Xamarin to Maui (net7.0). After release and receive message from crashlytics
This is full message from Crashlytics: 
[issues_18426.txt](https://github.com/dotnet/maui/files/13345561/issues_18426.txt)

Crashed: .NET ThreadPool Worker
0  libsystem_kernel.dylib         0x7578 __pthread_kill + 8
1  libsystem_pthread.dylib        0x7118 pthread_kill + 268
2  libsystem_c.dylib              0x1d178 abort + 180
3  MyPro.MAUI                  0x4b5ec60 xamarin_find_protocol_wrapper_type + 1194 (runtime.m:1194)
4  MyPro.MAUI                  0x4d38478 mono_invoke_unhandled_exception_hook + 1253 (exception.c:1253)
5  MyPro.MAUI                  0x4d95cbc start_wrapper_internal + 1223 (threads.c:1223)
6  MyPro.MAUI                  0x4d95a08 start_wrapper + 1266 (threads.c:1266)
7  libsystem_pthread.dylib        0x16b8 _pthread_start + 148
8  libsystem_pthread.dylib        0xb88 thread_start + 8

### Version with bug

7.0.96

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

7.0.96

### Affected platforms

iOS

### Affected platform versions

iOS 16.6.1, iPhone 14 Pro Max

**Comment by mattleibow** [comment] 2023-11-11 12:28
@rolfbjarne thoughts?

**Comment by mattleibow** [comment] 2023-11-11 12:30
@tnmp83 this will require more information, logs, a repro or a stack trace - or all of it. Please add more information so we can look closer. This appears to be a native crash report because of some sort of exception.

**Comment by rolfbjarne** [comment] 2023-11-13 07:10
Try adding this to the csproj, it might make the native stack trace a little more helpful:

```xml
<PropertyGroup>
    <NoSymbolStrip>true</NoSymbolStrip>
</PropertyGroup>
```

**Comment by tnmp83** [comment] 2023-11-14 07:12
> Try adding this to the csproj, it might make the native stack trace a little more helpful:
> 
> ```
> <PropertyGroup>
>     <NoSymbolStrip>true</NoSymbolStrip>
> </PropertyGroup>
> ```

Thanks [rolfbjarne](https://github.com/rolfbjarne)
I will add this config. Hopefully this error will no longer occur.

**Comment by ThinhKVT** [comment] 2023-11-21 03:03
Hello, have any other solution for the issue ? It's a long time from latest comment ~

**Comment by ThinhKVT** [comment] 2023-11-28 03:11
We added above config that Mr. Rolfbjarne recommended but result still not good, crash still happen with same frequent. Anyone have other solution for the issue ? Please help us !!!!

**Comment by ThinhKVT** [comment] 2023-12-08 03:41
We are trying to reproduce the issue again, it may take more time. We will share crash report if happen the issue.

**Comment by ThinhKVT** [comment] 2023-12-18 09:23
We can not re-produce the issue again on IOS, it may be re-produced by end-user only. We need more time to get support. Anyone have any solution ?

**Comment by rolfbjarne** [comment] 2023-12-18 10:34
One idea would be to add event handlers to the exception marshaling events listed here: https://learn.microsoft.com/en-us/xamarin/ios/platform/exception-marshaling, and then use some sort of telemetry to collect those exceptions from your customer's devices.

You could also do the same for the [AppDomain.UnhandledException](https://learn.microsoft.com/en-us/dotnet/api/system.appdomain.unhandledexception?view=net-8.0) event to ensure no fatal events escape you.

**Comment by ThinhKVT** [comment] 2023-12-25 03:28
Thank you @rolfbjarne . I appreciated your suggestion, we will try it, too.

**Comment by ThinhKVT** [comment] 2024-01-04 08:43
We added event handlers as your suggestion. But the issue is only on PROD, so it may take more time to get feedback from customer. Let us wait new information.

**Comment by PureWeen** [comment] 2024-05-31 17:05
Closing for now. 
Open a new issue if you get additional details

**Closed by PureWeen** 2024-05-31 17:05 UTC
Labels: t/bug, platform/iOS 🍎, s/needs-attention, migration-compatibility
