### ISSUE TITLE
ListView IsVisible Strange Behavior

### ISSUE THREAD

**Issue by matthericks** [dotnet/maui#13095] opened 2023-02-02 21:26 UTC
### Description

The ListView IsVisible Property is exhibiting strange behavior.

I have created a project where a button toggles a boolean property bound to the the IsVisible property of a ListView, but the listview visibility is not toggling as intended.

However, when I add a label and also bind it's visibility to the same property, everything works as intended.

Furthermore, when I create two sets of these, one with a label and one without, the first set of button + listview exhibits very strange behavior as shown in the attached video.

https://user-images.githubusercontent.com/19779550/216445965-f2e6d0e2-24a5-4978-bf44-9ca17a9d825e.mov

### Steps to Reproduce

1. Create new .Net MAUI App
2. Clear out MainPage contents except for the ScrollView and VerticalStackLayout
3. Set MainPage `x:Name="This"`
4. Add this code inside the verticalStackLayout:
```
            <Button
                Text="Button 1"
                Clicked="Button1Clicked" />
            <ListView
                ItemsSource="{Binding Items1, Source={x:Reference This}}"
                IsVisible="{Binding Visible1, Source={x:Reference This}}" />
           
            <Button
                Text="Button 2"
                Clicked="Button2Clicked" />
            <Label
                Text="This makes things work for some reason"
                IsVisible="{Binding Visible2, Source={x:Reference This}}" />
            <ListView
                ItemsSource="{Binding Items2, Source={x:Reference This}}"
                IsVisible="{Binding Visible2, Source={x:Reference This}}" />
```

5. Set MainPage C# code to:

```
    public static readonly BindableProperty Visible1Property = BindableProperty.Create(nameof(Visible1), typeof(bool), typeof(MainPage));
    public static readonly BindableProperty Visible2Property = BindableProperty.Create(nameof(Visible2), typeof(bool), typeof(MainPage));

    public bool Visible1 { get => (bool)GetValue(Visible1Property); set => SetValue(Visible1Property, value); }
    public bool Visible2 { get => (bool)GetValue(Visible2Property); set => SetValue(Visible2Property, value); }

    public List<int> Items1 { get; } = new() { 1, 2, 3 };
    public List<int> Items2 { get; } = new() { 4, 5, 6 };
    
    public MainPage() => InitializeComponent();

    private void Button1Clicked(object sender, EventArgs e) => Visible1 = !Visible1;
    private void Button2Clicked(object sender, EventArgs e) => Visible2 = !Visible2;
```
6. Run app.
7. Click buttons on main screen and observe that lists are not appearing and disappearing as expected

Expected: Clicking the buttons toggles the visibility of each list independently.
Actual: Strange behavior. See attached video or run code to see.

version notes: 
```
Installed Workload Ids      Manifest Version      Installation Source
---------------------------------------------------------------------
maui-maccatalyst            6.0.550/6.0.400       SDK 6.0.400        
maui-ios                    6.0.550/6.0.400       SDK 6.0.400        
maui-android                6.0.550/6.0.400       SDK 6.0.400     
```

### Link to public reproduction project repository

https://github.com/matthericks/ubiquitous-fishstick

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, I was *not* able test on other platforms

### Affected platform versions

iOS 16.2

### Did you find any workaround?

adding the label makes visibility functional for a single list, but I have no solve for the situation with multiple lists.

**Comment by drasticactions** [comment] 2023-02-06 11:52
Some notes:

- It's not just Label. If you link other Views (like Grid) there it will do the same behavior.
- My _guess_ right now is that, if you look at what `IsVisible` does, it both
 - Makes the ListView "Hidden"
 - Removes the rendered items from its list.
- When you click on Button1, it does "unhide" the list, but no items are added to it, so it looks invisible. That may explain the weird behavior when you click on the other button and then items start showing up. That suggests a binding issue where it should be rendering items when it's not.

**Comment by XamlTest** [comment] 2023-06-19 08:11
Verified this on Visual Studio Enterprise 17.7.0 Preview 2.0. Repro on iOS 16.4 with below Project:
[MauiApp1.zip](https://github.com/dotnet/maui/files/11785843/MauiApp1.zip)

**Comment by samhouts** [comment] 2023-08-04 19:40
Duplicate of #10303

**Closed by samhouts** 2023-08-04 19:40 UTC
Labels: t/bug, area/layout 🔲, platform/iOS 🍎, p/1, partner/cat 😻, area/controls 🎮, area/ListView, s/verified, s/triaged
