### ISSUE TITLE
Java.Lang.IllegalArgumentException: 'You cannot start a load for a destroyed activity'

### ISSUE THREAD

**Issue by kofanov** [dotnet/maui#13105] opened 2023-02-03 14:10 UTC
### Description

My app receives push messages from FCM and also I'm using FontImageSource for setting icons.

The problem:
If the application has not been started yet (or deleted from memory), then when you click on the push message, everything starts and works fine. But if you launch the application and just collapse it and then click on the push message, then it opens first, but crashes after a second with a following error - Java.Lang.IllegalArgumentException: 'You cannot start a load for a destroyed activity'.

Stack trace:

[MonoDroid] java.lang.IllegalArgumentException: You cannot start a load for a destroyed activity
[MonoDroid] 	at com.bumptech.glide.manager.RequestManagerRetriever.assertNotDestroyed(RequestManagerRetriever.java:353)
[MonoDroid] 	at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:153)
[MonoDroid] 	at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:133)
[MonoDroid] 	at com.bumptech.glide.Glide.with(Glide.java:818)
[MonoDroid] 	at com.microsoft.maui.glide.MauiCustomTarget.lambda$clear$2$com-microsoft-maui-glide-MauiCustomTarget(MauiCustomTarget.java:61)
[MonoDroid] 	at com.microsoft.maui.glide.MauiCustomTarget$$ExternalSyntheticLambda2.run(Unknown Source:2)
[MonoDroid] 	at android.os.Handler.handleCallback(Handler.java:938)
[MonoDroid] 	at android.os.Handler.dispatchMessage(Handler.java:99)
[MonoDroid] 	at android.os.Looper.loop(Looper.java:223)
[MonoDroid] 	at android.app.ActivityThread.main(ActivityThread.java:7656)
[MonoDroid] 	at java.lang.reflect.Method.invoke(Native Method)
[MonoDroid] 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
[MonoDroid] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

### Steps to Reproduce

1. Create MAUI app
2. Implement push message receiving
3. Add any image with FontImageSource on the starting page
4. Start app, then collapse it
5. Send push message via FCM console
6. Click on message

Sorry, I can't make a public repository because too many specific steps are required to implement push messages, including registering with Firebase and obtaining keys.

### Link to public reproduction project repository

https://github.com/dotnet/maui

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android API level 33

### Did you find any workaround?

I found some information here
https://stackoverflow.com/questions/49515407/error-of-glide-library-you-cannot-start-a-load-from-a-destroyed-activity

if (!activity.isFinishing()) {
    Glide.with(...
}

**Comment by jfversluis** [comment] 2023-02-03 15:00
Duplicate of #12513

**Closed by jfversluis** 2023-02-03 15:00 UTC
Labels: t/bug
