### ISSUE TITLE
Shell Absolute Navigation Crashes when a title view is set to each shell page.

### ISSUE THREAD

**Issue by DamienDoumer** [dotnet/maui#5944] opened 2022-04-09 12:33 UTC
### Description

If you add a title view to the pages inside a shell as I did in the reproduction sample, then you perform absolute navigation, you're going to face a crash. With the following stack trace errors, I pasted in the log output below.

### Steps to Reproduce

1- Create a new MAUI app
2- Add a shell and two pages inside a tabbar
3- Add a title view using Shell.SetTitleView
4- Perform absolute navigation from one page to the other, and the app will crash.

Here is a link to [the reproduction of this bug](https://github.com/DamienDoumer/MAUIBugs/tree/master/MAUIBugs/ShellNavBugOne).

### Version with bug

Preview 14 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android

### Did you find any workaround?

The work around is to not use Shell.SetTitleView, and code the title view directly in the page's view hierarchy

### Relevant log output

```shell
`[mono-rt] [ERROR] FATAL UNHANDLED EXCEPTION: Java.Lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
[mono-rt]    at Java.Interop.JniEnvironment.InstanceMethods.CallNonvirtualVoidMethod(JniObjectReference instance, JniObjectReference type, JniMethodInfo method, JniArgumentValue* args) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniEnvironment.g.cs:line 12324
[mono-rt]    at Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeVirtualVoidMethod(String encodedMember, IJavaPeerable self, JniArgumentValue* parameters) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods_Invoke.cs:line 35
[mono-rt]    at Android.Views.ViewGroup.AddView(View child) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net6.0/android-32/mcw/Android.Views.ViewGroup.cs:line 1999
[mono-rt]    at Microsoft.Maui.Handlers.LayoutHandler.SetVirtualView(IView view) in D:\a\_work\1\s\src\Core\src\Handlers\Layout\LayoutHandler.Android.cs:line 43
[mono-rt]    at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.ILayout, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Platform.LayoutViewGroup, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].SetVirtualView(IElement view) in D:\a\_work\1\s\src\Core\src\Handlers\View\ViewHandlerOfT.cs:line 54
[mono-rt]    at Microsoft.Maui.Controls.Element.SetHandler(IElementHandler newHandler) in D:\a\_work\1\s\src\Controls\src\Core\HandlerImpl\Element\Element.Impl.cs:line 64
[mono-rt]    at Microsoft.Maui.Controls.Element.set_Handler(IElementHandler value) in D:\a\_work\1\s\src\Controls\src\Core\HandlerImpl\Element\Element.Impl.cs:line 20
[mono-rt]    at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IElement.set_Handler(IElementHandler value) in D:\a\_work\1\s\src\Controls\src\Core\HandlerImpl\VisualElement\VisualElement.Impl.cs:line 291
[mono-rt]    at Microsoft.Maui.Platform.ElementExtensions.ToHandler(IElement view, IMauiContext context) in D:\a\_work\1\s\src\Core\src\Platform\ElementExtensions.cs:line 91
[mono-rt]    at Microsoft.Maui.Platform.ElementExtensions.ToPlatform(IElement view, IMauiContext context) in D:\a\_work\1\s\src\Core\src\Platform\ElementExtensions.cs:line 127
[mono-rt]    at Microsoft.Maui.Controls.Platform.Compatibility.ShellViewRenderer.OnViewSet(View view) in D:\a\_work\1\s\src\Compatibility\Core\src\Handlers\Shell\Android\ShellContentView.cs:line 207
[mono-rt]    at Microsoft.Maui.Controls.Platform.Compatibility.ShellViewRenderer.set_View(View value) in D:\a\_work\1\s\src\Compatibility\Core\src\Handlers\Shell\Android\ShellContentView.cs:line 46
[mono-rt]    at Microsoft.Maui.Controls.Platform.Compatibility.ShellViewRenderer..ctor(Context context, View view, IMauiContext mauiContext) in D:\a\_work\1\s\src\Compatibility\Core\src\Handlers\Shell\Android\ShellContentView.cs:line 38
[mono-rt]    at Microsoft.Maui.Controls.Platform.Compatibility.ContainerView.OnViewSet(View view) in D:\a\_work\1\s\src\Compatibility\Core\src\Handlers\Shell\Android\ContainerView.cs:line 117
[mono-rt]    at Microsoft.Maui.Controls.Platform.Compatibility.ContainerView.set_View(View value) in D:\a\_work\1\s\src\Compatibility\Core\src\Handlers\Shell\Android\ContainerView.cs:line 38
[mono-rt]    at Microsoft.Maui.Controls.Platform.Compatibility.ContainerView..ctor(Context context, View view, IMauiContext mauiContext) in D:\a\_work\1\s\src\Compatibility\Core\src\Handlers\Shell\Android\ContainerView.cs:line 20
[mono-rt]    at Microsoft.Maui.Controls.Platform.Compatibility.ShellToolbarTracker.UpdateTitleView(Context context, Toolbar toolbar, View titleView) in D:\a\_work\1\s\src\Compatibility\Core\src\Handlers\Shell\Android\ShellToolbarTracker.cs:line 539
[mono-rt]    at Microsoft.Maui.Controls.Platform.Compatibility.ShellToolbarTracker.UpdateTitleView() in D:\a\_work\1\s\src\Compatibility\Core\src\Handlers\Shell\Android\ShellToolbarTracker.cs:line 656
[mono-rt]    at Microsoft.Maui.Controls.Platform.Compatibility.ShellToolbarTracker.OnPageChanged(Page oldPage, Page newPage) in D:\a\_work\1\s\src\Compatibility\Core\src\Handlers\Shell\Android\ShellToolbarTracker.cs:line 249
[mono-rt]    at Microsoft.Maui.Controls.Platform.Compatibility.ShellToolbarTracker.set_Page(Page value) in D:\a\_work\1\s\src\Compatibility\Core\src\Handlers\Shell\Android\ShellToolbarTracker.cs:line 105
[mono-rt]    at Microsoft.Maui.Controls.Platform.Compatibility.ShellSectionRenderer.OnCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) in D:\a\_work\1\s\src\Compatibility\Core\src\Handlers\Shell\Android\ShellSectionRenderer.cs:line 174
[mono-rt]    at AndroidX.Fragment.App.Fragment.n_OnCreateView_Landroid_view_LayoutInflater_Landroid_view_ViewGroup_Landroid_os_Bundle_(IntPtr jnienv, IntPtr native__this, IntPtr native_inflater, IntPtr native_container, IntPtr native_savedInstanceState) in D:\a\1\s\generated\androidx.fragment.fragment\obj\Release
et6.0-android\generated\src\AndroidX.Fragment.App.Fragment.cs:line 1977
[mono-rt]    at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPLLL_L(_JniMarshal_PPLLL_L callback, IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, IntPtr p2) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:line 231
[mono-rt]   --- End of managed Java.Lang.IllegalStateException stack trace ---
[mono-rt] java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
[mono-rt] 	at android.view.ViewGroup.addViewInner(ViewGroup.java:5319)
[mono-rt] 	at android.view.ViewGroup.addView(ViewGroup.java:5140)
[mono-rt] 	at android.view.ViewGroup.addView(ViewGroup.java:5080)
[mono-rt] 	at android.view.ViewGroup.addView(ViewGroup.java:5052)
[mono-rt] 	at crc648677f43942f779a4.ShellSectionRenderer.n_onCreateView(Native Method)
[mono-rt] 	at crc648677f43942f779a4.ShellSectionRenderer.onCreateView(ShellSectionRenderer.java:42)
[mono-rt] 	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2963)
[mono-rt] 	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:518)
[mono-rt] 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
[mono-rt] 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
[mono-rt] 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
[mono-rt] 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
[mono-rt] 	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524)
[mono-rt] 	at android.os.Handler.handleCallback(Handler.java:938)
[mono-rt] 	at android.os.Handler.dispatchMessage(Handler.java:99)
[mono-rt] 	at android.os.Looper.loopOnce(Looper.java:233)
[mono-rt] 	at android.os.Looper.loop(Looper.java:344)
[mono-rt] 	at android.app.ActivityThread.main(ActivityThread.java:8184)
[mono-rt] 	at java.lang.reflect.Method.invoke(Native Method)
[mono-rt] 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
[mono-rt] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
[mono-rt] 
[mono-rt]   --- End of managed Java.Lang.IllegalStateException stack trace ---
[mono-rt] java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
[mono-rt] 	at android.view.ViewGroup.addViewInner(ViewGroup.java:5319)
[mono-rt] 	at android.view.ViewGroup.addView(ViewGroup.java:5140)
[mono-rt] 	at android.view.ViewGroup.addView(ViewGroup.java:5080)
[mono-rt] 	at android.view.ViewGroup.addView(ViewGroup.java:5052)
[mono-rt] 	at crc648677f43942f779a4.ShellSectionRenderer.n_onCreateView(Native Method)
[mono-rt] 	at crc648677f43942f779a4.ShellSectionRenderer.onCreateView(ShellSectionRenderer.java:42)
[mono-rt] 	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2963)
[mono-rt] 	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:518)
[mono-rt] 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
[mono-rt] 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
[mono-rt] 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
[mono-rt] 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
[mono-rt] 	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524)
[mono-rt] 	at android.os.Handler.handleCallback(Handler.java:938)
[mono-rt] 	at android.os.Handler.dispatchMessage(Handler.java:99)
[mono-rt] 	at android.os.Looper.loopOnce(Looper.java:233)
[mono-rt] 	at android.os.Looper.loop(Looper.java:344)
[mono-rt] 	at android.app.ActivityThread.main(ActivityThread.java:8184)
[mono-rt] 	at java.lang.reflect.Method.invoke(Native Method)
[mono-rt] 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
[mono-rt] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
[mono-rt] 
`
```

**Comment by XamlTest** [comment] 2022-04-11 01:48
Verified this issue with Visual Studio Enterprise 17.2.0 Preview 2.1 [32317.152]. Repro on Android. Sample Project: [5944.zip](https://github.com/dotnet/maui/files/8460462/5944.zip)

**Comment by AstrNexus** [comment] 2022-04-13 22:09
Same issue with Android 12

### Version with bug
RC 1

### Affected platform versions
Android 

### Steps to Reproduce
Create new project and replace MainPage.cs with
**MainPage.cs**
```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="Sample.MainPage">
    <Shell.TitleView>
        <Label
            Text="Hello, World!"
            SemanticProperties.HeadingLevel="Level1"
            FontSize="32"/>
    </Shell.TitleView>
</ContentPage>
```

### Environment
Visual Studio Community 17.2.0 Preview 3.0
Android 12 (API 31) x86_64 Emulator


### Stacktrace 
```
Java.Lang.IllegalStateException: 'The specified child already has a parent. You must call removeView() on the child's parent first.'

0xFFFFFFFFFFFFFFFF in Android.Runtime.JNIEnv.monodroid_debugger_unhandled_exception	C#
0x14 in Android.Runtime.JNINativeWrapper._unhandled_exception at /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:12,5	C#
0x23 in Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPLLL_L at /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:309,26	C#
0x17 in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw	C#
0x8E in Java.Interop.JniEnvironment.InstanceMethods.CallNonvirtualVoidMethod at /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniEnvironment.g.cs:12324,5	C#
0x65 in Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeVirtualVoidMethod at /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods_Invoke.cs:35,5	C#
0x38 in Android.Views.ViewGroup.AddView at /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net6.0/android-32/mcw/Android.Views.ViewGroup.cs:1999,5	C#
0x47 in Microsoft.Maui.Controls.Platform.Compatibility.ContainerView.OnViewSet at D:\a\_work\1\s\src\Controls\src\Core\Compatibility\Handlers\Shell\Android\ContainerView.cs:122,5	C#
0x13 in Microsoft.Maui.Controls.Platform.Compatibility.ContainerView.set_View at D:\a\_work\1\s\src\Controls\src\Core\Compatibility\Handlers\Shell\Android\ContainerView.cs:38,5	C#
0x1F in Microsoft.Maui.Controls.Platform.Compatibility.ContainerView..ctor at D:\a\_work\1\s\src\Controls\src\Core\Compatibility\Handlers\Shell\Android\ContainerView.cs:20,4	C#
0x40 in Microsoft.Maui.Controls.Platform.Compatibility.ShellToolbarTracker.UpdateTitleView at D:\a\_work\1\s\src\Controls\src\Core\Compatibility\Handlers\Shell\Android\ShellToolbarTracker.cs:549,5	C#
0x1D in Microsoft.Maui.Controls.Platform.Compatibility.ShellToolbarTracker.UpdateTitleView at D:\a\_work\1\s\src\Controls\src\Core\Compatibility\Handlers\Shell\Android\ShellToolbarTracker.cs:666,4	C#
0xE1 in Microsoft.Maui.Controls.Platform.Compatibility.ShellToolbarTracker.OnPageChanged at D:\a\_work\1\s\src\Controls\src\Core\Compatibility\Handlers\Shell\Android\ShellToolbarTracker.cs:253,5	C#
0x20 in Microsoft.Maui.Controls.Platform.Compatibility.ShellToolbarTracker.set_Page at D:\a\_work\1\s\src\Controls\src\Core\Compatibility\Handlers\Shell\Android\ShellToolbarTracker.cs:106,5	C#
0x186 in Microsoft.Maui.Controls.Platform.Compatibility.ShellSectionRenderer.OnCreateView at D:\a\_work\1\s\src\Controls\src\Core\Compatibility\Handlers\Shell\Android\ShellSectionRenderer.cs:126,4	C#
0x24 in AndroidX.Fragment.App.Fragment.n_OnCreateView_Landroid_view_LayoutInflater_Landroid_view_ViewGroup_Landroid_os_Bundle_ at C:\a\_work\1\s\generated\androidx.fragment.fragment\obj\Release\net6.0-android\generated\src\AndroidX.Fragment.App.Fragment.cs:1999,4	C#
0xD in Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPLLL_L at /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:308,5	C#

```

**Comment by drasticactions** [comment] 2022-04-16 15:38
@PureWeen I set the milestone and assigned it to you, I hope that's okay with you. If not, you can change it.

If you have a TitleView set and use a TabBar view, it makes navigating shell unusable since it'll crash on this every time. IMO that seems important enough to fix for RC2.

**Closed** 2022-04-18 21:43 UTC
Labels: t/bug, area/shell 🐢, fatal, s/verified, s/triaged
