### ISSUE TITLE
RadioButton ControlTemplate not indicating selected button

### ISSUE THREAD

**Issue by Akinnagbe** [dotnet/maui#9370] opened 2022-08-12 07:55 UTC
### Description

I followed the documentation in this link [https://docs.microsoft.com/en-us/dotnet/maui/user-interface/controls/radiobutton#redefine-radiobutton-appearance](url), after carefully copying and pasting the sample code blocks, the radiobutton is not indicating the selected button. Feels like they are all disabled.

### Steps to Reproduce

Create a new file > .Net Maui App,
copy the code block in this link [https://docs.microsoft.com/en-us/dotnet/maui/user-interface/controls/radiobutton#redefine-radiobutton-appearance](url)
run the app
select any radiobutton

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 12

### Did you find any workaround?

No

**Comment by Darlingtone** [comment] 2022-09-23 11:12
I can confirm that I can reproduce this bug. 

The only way I can get to select the RadioButtons is to click just out side to the right of the RadioButton, In the picture below, if you clicking (running in an Emmunlator and using a mouse pointer) the yellow highlighted area will select the RadioButton to the left of it

![image](https://user-images.githubusercontent.com/1232669/191947642-a6d111d6-aaed-4a79-af28-f59d5d04733f.png)

**Comment by hartez** [comment] 2023-01-31 00:06
Duplicate of #6938

**Closed by hartez** 2023-01-31 00:06 UTC
Labels: t/bug, area/controls 🎮, control-radiobutton
