### ISSUE TITLE
[regression/7.0.0] Connectivity.ConnectivityChanged Event throws exception at network change

### ISSUE THREAD

**Issue by mrherkar** [dotnet/maui#15843] opened 2023-06-25 11:29 UTC
### Description

This exception is thrown at network connection change after I subscribe to Connectivity.ConnectivityChanged event

**"The application called an interface that was marshalled for a different thread. (0x8001010E (RPC_E_WRONG_THREAD))"**

### Steps to Reproduce

1. Create a new . NET MAUI App, framework .NET 7.0 
2. Subscribe to Connectivity.ConnectivityChanged event
3. `Connectivity.ConnectivityChanged += (sender, e) => 
		{ 
			// never reach this point
		};`
4. start the app in Debug mode and change network connection to see the exception. This exception does not crash the app. 

**"The application called an interface that was marshalled for a different thread. (0x8001010E (RPC_E_WRONG_THREAD))"**
![Screenshot (213)](https://github.com/dotnet/maui/assets/65870165/b33e4249-de3d-40c4-a415-9f3d982537e6)

In Release mode it seems the only problem is if the event never get called.

If I change Windows target framework to .NET 6.0, event is called and it seems fine, but exception message is there

![Screenshot (215)](https://github.com/dotnet/maui/assets/65870165/49891bcb-13dd-47ec-b4c5-03c774459d17)

It works fine on Android.

### Link to public reproduction project repository

https://github.com/mrherkar/MauiAppWithConnectivityChangedIssue

### Version with bug

7.0.86

### Last version that worked well

6.0

### Affected platforms

Windows

### Affected platform versions

Windows SDK 10.0.19041.0

### Did you find any workaround?

no

### Relevant log output

```shell
C:\Windows\system32>dotnet workload list

Installed Workload Id      Manifest Version       Installation Source
---------------------------------------------------------------------
maui-windows               7.0.86/7.0.100         VS 17.6.33815.320
maui-maccatalyst           7.0.86/7.0.100         VS 17.6.33815.320
maccatalyst                16.4.7067/7.0.100      VS 17.6.33815.320
maui-ios                   7.0.86/7.0.100         VS 17.6.33815.320
ios                        16.4.7067/7.0.100      VS 17.6.33815.320
maui-android               7.0.86/7.0.100         VS 17.6.33815.320
android                    33.0.46/7.0.100        VS 17.6.33815.320
```

**Comment by mattleibow** [comment] 2023-09-06 15:58
Potentially a duplicate of: https://github.com/dotnet/maui/issues/7393

**Comment by Brosten** [comment] 2023-11-20 12:16
I get this issue when calling 
Connectivity.ConnectionProfiles.Any()
regardless what thread I'm on.

**Comment by Brosten** [comment] 2023-11-20 13:00
I get this whenever I try access Connectivity.NetworkAccess on WinUI

**Closed** 2024-01-23 21:07 UTC
Labels: t/bug, platform/windows 🪟, p/1, area/essentials 🍞, partner/cat 😻, potential-regression
