### ISSUE TITLE
Maui Blazor Release Config App Throws Error

### ISSUE THREAD

**Issue by ft9788501** [dotnet/maui#5301] opened 2022-03-15 12:24 UTC
### Description

Here is my project CI, and can not open this app on my macos.
https://github.com/ft9788501/VisualLogger/actions/workflows/macos.yml

I do error step?

### Steps to Reproduce

download app on https://github.com/ft9788501/VisualLogger/actions/runs/1976427865

### Version with bug

Preview 13 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

macos 12

**Comment by jfversluis** [comment] 2022-03-15 13:19
Would you be able to try and creating a debug build and confirm that works?

**Comment by mkArtakMSFT** [comment] 2022-03-15 16:33
Thanks for contacting us.
@Redth do you know who would be best to look at this, as this doesn't seem blazor related. Blazor doesn't load the `Microsoft.Extensions.Options` at all.

**Comment by TanayParikh** [comment] 2022-03-15 18:35
Potentially related to https://github.com/dotnet/maui/issues/5197. @jfversluis was able to repro however I didn't encounter the same error.

**Comment by ft9788501** [comment] 2022-03-16 02:17
> Would you be able to try and creating a debug build and confirm that works?
> 
> I tried to reproduce this and see the same for .NET MAUI Blazor apps built in release mode, error:
> 
> ```
> *** Terminating app due to uncaught exception 'System.IO.FileNotFoundException', reason: 'Could not load file or assembly 'Microsoft.Extensions.Options, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. (System.IO.FileNotFoundException)
> at Microsoft.Extensions.DependencyInjection.LoggingServiceCollectionExtensions.AddLogging(IServiceCollection )
> at Microsoft.Extensions.DependencyInjection.ComponentsWebViewServiceCollectionExtensions.AddBlazorWebView(IServiceCollection services)
> at mauitesting.MauiProgram.CreateMauiApp()
> at mauitesting.AppDelegate.CreateMauiApp()
> at Microsoft.Maui.MauiUIApplicationDelegate.WillFinishLaunching(UIApplication application, NSDictionary launchOptions)
> ```
> 
> But **not** for a build in debug config and also **not** happening for .NET MAUI regular apps (in release mode)

I use debug config and try again, But got same result :
https://github.com/ft9788501/VisualLogger/actions/runs/1990279314
Can not open this app on my macos

**Comment by jfversluis** [comment] 2022-03-16 13:23
Could you clarify "can not open this app" do you mean because of this? 
![image](https://user-images.githubusercontent.com/939291/158599440-268a7dc6-e04f-4f28-9b84-24c90c4467ca.png)

In that case open a Terminal window and run: `chmod -x VisualLogger.app/Contents/MacOS/VisualLogger`

**Comment by ft9788501** [comment] 2022-03-17 02:47
> Could you clarify "can not open this app" do you mean because of this? ![image](https://user-images.githubusercontent.com/939291/158599440-268a7dc6-e04f-4f28-9b84-24c90c4467ca.png)
> 
> In that case open a Terminal window and run: `chmod -x VisualLogger.app/Contents/MacOS/VisualLogger` after that right-click and choose Open. Then click Open. This is all part of the macOS protection :)
> 
> This also seems to work for your release build

Yes, This is the problem I meet, Is this a bug?

**Comment by TanayParikh** [comment] 2022-03-17 03:45
> > Could you clarify "can not open this app" do you mean because of this? ![image](https://user-images.githubusercontent.com/939291/158599440-268a7dc6-e04f-4f28-9b84-24c90c4467ca.png)
> 
> > 
> 
> > In that case open a Terminal window and run: `chmod -x VisualLogger.app/Contents/MacOS/VisualLogger` after that right-click and choose Open. Then click Open. This is all part of the macOS protection :)
> 
> > 
> 
> > This also seems to work for your release build
> 
> 
> 
> Yes, This is the problem I meet, Is this a bug?

Ah thanks for the clarification. This is expected behavior for unsigned applications. Please see https://support.apple.com/guide/mac-help/open-a-mac-app-from-an-unidentified-developer-mh40616/12.0/mac/12.0

**Comment by jfversluis** [comment] 2022-03-17 08:19
As mentioned by @TanayParikh this is not a bug, this is just how macOS handles these types of situations. I think there is a couple of things going on here: 

1. You're distributing an app outside of the App Store, ideally Apple doesn't want that
2. That in itself is not a problem, but it also downloaded from the internet. When doing that, it seems they automatically disable the ability to run the app straight-away as a precaution so the downloaded app can't do damage

In either case, the app works and everything on "our side" seems to work fine, so closing this for now.

Thanks for this issue though! This helped clarify some thing :)

**Closed by jfversluis** 2022-03-17 08:19 UTC
Labels: t/bug, platform/macOS 🍏, area/publishing 🏁, s/verified, s/triaged

**Comment by jfversluis** [comment] 2022-03-23 09:25
So sorry! I just notice that I wrote `-x` while it should be `+x` so the full command is `chmod +x VisualLogger.app/Contents/MacOS/VisualLogger`

The `x` is the execute flag. With `-x` you remove the flag and thus it can't be executed, with `+x` you add the execute flag and it can be executed. After that the instructions should work. Sorry about that!

**Comment by ft9788501** [comment] 2022-03-23 14:36
> 

It works, Thank you very very very much.
