### ISSUE TITLE
[regression/8.0.0] MAUI custom control/mapper not working android

### ISSUE THREAD

**Issue by npostma** [dotnet/maui#17483] opened 2023-09-19 12:42 UTC
### Description

I am presently engaged in the task of transitioning my application to MAUI within the .NET 8 framework. Unfortunately, I've encountered some roadblocks primarily related to crashes, which have been reported in detail on the GitHub issue tracker: https://github.com/dotnet/maui/issues/17396. While I've managed to get certain aspects of the app working on Android, I've noticed a few issues that were absent in the .NET 7 build. Regrettably, I'm unable to ascertain if these issues also affect the iOS version since I'm unable to test it due to a crash occurring during the boot process.

One specific issue I've encountered pertains to a 'CleanEntry' control with an associated mapper. Below is the relevant code snippet for reference.

This line in the entry should not be visible:
![image](https://github.com/dotnet/maui/assets/1578820/1f11a569-43fd-4efd-8504-b0e67eec5125)

This Mapper code is called in the constructor for the ContentPage's that make use of this mapper/control

```c#
Microsoft.Maui.Handlers.EntryHandler.Mapper.AppendToMapping("SetCleanStyle", (handler, view) =>
{
        if (view is CleanEntry)
        {
#if IOS || MACCATALYST
            handler.PlatformView.BorderStyle = UITextBorderStyle.None;
#elif ANDROID
            handler.PlatformView.Background = null;
            handler.PlatformView.SetHintTextColor(ColorStateList.ValueOf(Android.Graphics.Color.White));
            handler.PlatformView.SetPadding(0, 0, 0, 0);
#endif
                }
});
 ```        

   

### Version with bug

8.0.0-rc.1.9171

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.92

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android API 31

**Comment by samhouts** [comment] 2023-09-19 22:19
Duplicate of #17448

**Closed by samhouts** 2023-09-19 22:19 UTC
Labels: t/bug, platform/android 🤖, area/controls 🎮, custom-handler, potential-regression
