### ISSUE TITLE
[Android] ScrollOrientation.Neither not disable scroll

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#19213] opened 2023-12-05 09:06 UTC
### Description

` ScrollOrientation.Neither` not disable scroll on Android.

### Steps to Reproduce

1. Launch the .NET MAUI sln.
2. Launch Issue2680Test_ScrollDisabled (src\Compatibility\ControlGallery\src\Issues.Shared\Issue2680ScrollView.cs).
3. Tap the button to disable the scroll.
4. Try to scroll. Must not be possible.

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

8.0.3

### Affected platforms

Android

**Comment by riccardominato** [comment] 2023-12-15 08:14
https://github.com/dotnet/maui/issues/18418

**Comment by PureWeen** [comment] 2023-12-21 19:24
Duplicate of #18418

**Closed by PureWeen** 2023-12-21 19:24 UTC
Labels: t/bug, area/layout 🔲, platform/android 🤖, layout-scrollview
