### ISSUE TITLE
RadioButton TextColor not applying on MacOS and iOS in MAUI

### ISSUE THREAD

**Issue by VidyalakshmiMani** [dotnet/maui#19520] opened 2023-12-20 12:34 UTC
### Description

Setting the `TextColor` property on the RadioButton control in MAUI does not work as expected on MacOS and iOS. The text color does not change. However, it is working fine on the Windows platform.

**MacOS:**
![Screenshot 2023-12-20 at 17 46 50](https://github.com/dotnet/maui/assets/104206735/9691b522-6d47-42e5-9cc2-6f8819de99cf)

**Windows:**
<img width="725" alt="image" src="https://github.com/dotnet/maui/assets/104206735/89d7a1dc-1357-425c-9942-f0e0a1e311cc">

### Steps to Reproduce

1. Create a simple MAUI project.
2. Add a RadioButton control.
3. Set the `TextColor` property to a specific color.
4. Run the project on MacOS or iOS.
5. Observe that the text color of the RadioButton does not change.

### Version with bug

Unknown/Other

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, macOS

**Comment by riccardominato** [comment] 2023-12-21 10:08
Duplicate. @PureWeen You can find here the repro https://github.com/dotnet/maui/issues/19081

**Comment by PureWeen** [comment] 2023-12-21 19:13
Duplicate of #19081

**Closed by PureWeen** 2023-12-21 19:13 UTC
Labels: t/bug, platform/macOS 🍏, platform/iOS 🍎, area/controls 🎮, control-radiobutton, s/needs-attention
