### ISSUE TITLE
Give a possibility to disable overscroll in AppShell/ShellContent

### ISSUE THREAD

**Issue by MissedSte4k** [dotnet/maui#6662] opened 2022-04-29 11:45 UTC
### Description

I've been workeing on my app for some time now. It uses a lot of SwipeView's with SwipeItems. The problem I'm encountering is that half of the time I use them - the interaction is captured and used by overscroll. 
![image](https://user-images.githubusercontent.com/36638029/165934120-a39bbb1e-8c42-4fff-a598-8f1ccdf57fed.png)
Enable the possibility to Disable/Enable it would make the UI 10x more enjoyable

### Public API Changes

``` csharp
var shellContent = new ShellContent();
shellContent.OverScroll = false; //new API

```

```
<ShellContent ContentTemplate="{DataTemplate page:MainPage}" Route="MainPage" OverScroll="False" />
```
This would disable overscroll in ShellContent

### Intended Use-Case

It would be used in situations where OverScroll interferes with some of the other UI elements like SwipeView.

[StackOverflow question](https://stackoverflow.com/questions/72009853/xamarin-maui-shell-remove-overscroll-from-the-sides?noredirect=1#comment127241612_72009853)

**Comment by romanov** [comment] 2022-05-05 16:10
Yes, overscroll is causing troubles with CarouselView (horizontal) and some gestures inside my app.

**Comment by cbaer-extron** [comment] 2022-05-12 23:25
I believe this to be a bug.  Not a Proposal.  The carousel performs differently when part of Shell.  It is very difficult to scroll a carousel inside of Shell.  Without Shell, a finger flick easily advances the view of the carousel.  But with Shell, you need to hold your finger in place over the Carousel item for a second before swiping.

**Comment by jfversluis** [comment] 2022-08-24 12:19
Yeah I would also consider this a bug, not a feature. Thanks for the input!

**Comment by jfversluis** [comment] 2022-08-24 12:19
Duplicate of #6659

**Closed by jfversluis** 2022-08-24 12:19 UTC
Labels: t/enhancement ☀️, proposal/open, area/shell 🐢
