### ISSUE TITLE
CarouselView its not working on Android

### ISSUE THREAD

**Issue by ederbond** [dotnet/maui#6877] opened 2022-05-06 02:09 UTC
### Description

I'm unable to use the swipe gesture to switch between items of the `CarouselView` on Android.

Follows the Reproduction sample to verify the bug:
https://github.com/ederbond/CarouselViewSwipeNotWorking

I'm on VS 2022 Preview 5 
SDK 6.0.300-preview.22204.3
Tested on Android 11

### Steps to Reproduce

1. Clone this sample  https://github.com/ederbond/CarouselViewSwipeNotWorking
2. Run the app on Android (I didn't tested on iOS so please very that also).
3. The Carousel Viewl will be displayed on the MainPage
4. Try to Swipe and see the bug.

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

Android 11 and probably iOS

### Did you find any workaround?

No, it's implossible to use the control on the current state.

**Comment by XamlTest** [comment] 2022-05-06 02:34
Verified this issue with Visual Studio Enterprise 17.3.0 Preview 1.0 [32427.455.main]. Repro on Android, not repro on iOS. Sample Project: [MauiApp9.zip](https://github.com/dotnet/maui/files/8637182/MauiApp9.zip)

**Comment by samhouts** [comment] 2022-05-06 22:05
Duplicate of #6062

**Closed by samhouts** 2022-05-06 22:05 UTC
Labels: t/bug, s/duplicate 2️⃣, p/1, area/controls 🎮, s/verified, s/triaged
