### ISSUE TITLE
Status bar overlays on BlazorWebView in Blazor Hybrid app

### ISSUE THREAD

**Issue by danroth27** [dotnet/maui#25477] opened 2024-10-23 16:28 UTC
### Description

I'm seeing a styling issue in Blazor Hybrid apps where the status bar is overlayed on the BlazorWebView:

![Image](https://github.com/user-attachments/assets/453dd483-3ec8-45fc-95a7-72bd3a87c88b)

### Steps to Reproduce

1. Create a new .NET MAUI Blazor Hybrid App with .NET 9 RC2
2. Run the Blazor Hybrid app in a Pixel 7 Android emulator

### Version with bug

9.0.0-rc.2.24503.2

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.3 GA

### Affected platforms

Android

### Affected platform versions

Pixel 7

### Did you find any workaround?

I'm guessing it's a CSS styling issue in the template.

**Comment by Eilon** [comment] 2024-10-23 17:26
Duplicate of https://github.com/dotnet/maui/issues/14894

**Closed by Eilon** 2024-10-23 17:26 UTC
Labels: t/bug, area-blazor

**Comment by Redth** [comment] 2024-10-24 19:46
Tracking in #24742
