### ISSUE TITLE
Don't run

### ISSUE THREAD

**Issue by AP2020C** [dotnet/maui#12665] opened 2023-01-14 13:47 UTC
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/run
Operating System: windows

I have enabled developer mode but still nothing happens when I press the Windows machine button

**Comment by mattleibow** [comment] 2023-01-16 15:34
Duplicate of https://github.com/dotnet/maui/issues/12080

**Closed by mattleibow** 2023-01-16 15:34 UTC
Labels: s/duplicate 2️⃣, platform/windows 🪟, s/needs-info, area/setup 🪄
