### ISSUE TITLE
Maui Blazor for iOS works on macbook from command line but fails to start when installed on Iphone using TestFlight. Using IConnectivity, IGeolocation, IMediaPicker

### ISSUE THREAD

**Issue by myndfire** [dotnet/maui#7945] opened 2022-06-11 06:38 UTC
### Description

I have added 3 pages to the default Maui Blazor template app (files attached).
Build IDE: 
Visual Studio Professional 2022 for Mac Preview
Version 17.3 Preview (17.3 build 198)

Build Host: Macbook Air (M1)

When I run from vs2022 in debug mode all works, however in release mode nothing happens. 

### Steps to Reproduce

1. Create a new Maui Blazor app
2. add platform capabilities in DI container
```cs
		builder.Services.AddSingleton<IConnectivity>(Connectivity.Current);
		builder.Services.AddSingleton<IGeolocation>(Geolocation.Default);
		builder.Services.AddSingleton<IMediaPicker>(MediaPicker.Default);
```
4. Added 3 buttons for each of the services
5. Added code to access these services that are called from the button callbacks:
```cs
public bool IsThereConnectivity()
        {
            if (connectivity.NetworkAccess != NetworkAccess.Internet)
            {
                return false;
            }
            else
            {
                return true;
            }
        }
```
----

```cs
                Location location;
                await CheckAndRequestLocationPermission();
                location = await geolocation.GetLastKnownLocationAsync();
                if (location == null)
                {
                    location = await geolocation.GetLocationAsync(
                        new GeolocationRequest
                        {
                            DesiredAccuracy = GeolocationAccuracy.Medium,
                            Timeout = TimeSpan.FromSeconds(30)
                        }
                            );
                }
                return location;
```
----
```cs
if (mediaPicker.IsCaptureSupported)
                {
                    FileResult photo = await MediaPicker.Default.CapturePhotoAsync();

                    if (photo != null)
                    {
                        // save the file into local storage
                        string localFilePath = Path.Combine(FileSystem.CacheDirectory, photo.FileName);

                        using Stream sourceStream = await photo.OpenReadAsync();
                        using FileStream localFileStream = File.OpenWrite(localFilePath);
                        Result = localFilePath;
                        await sourceStream.CopyToAsync(localFileStream);
                        return Result;
                    }
                }
```

6. Updated info.plist:
```xml
        <key>NSLocationWhenInUseUsageDescription</key>
	<string>This app needs access to location services</string>
	<key>NSCameraUsageDescription</key>
	<string>This app needs access to the camera to take photos.</string>
	<key>NSMicrophoneUsageDescription</key>
	<string>This app needs access to microphone for taking videos.</string>
	<key>NSPhotoLibraryAddUsageDescription</key>
	<string>This app needs access to the photo gallery for picking photos and videos.</string>
	<key>NSPhotoLibraryUsageDescription</key>
	<string>This app needs access to photos gallery for picking photos and videos.</string>
```

7. Ran local release on my macboor air (M1)
`dotnet build -t:Run -c:Release -f net6.0-maccatalyst  MyMauiBlazorApp.csproj`
ALL WORKS FINE IN THE APP !

8. Created archive for iOS

```
dotnet publish MyMauiBlazorApp.csproj -f:net6.0-ios -c:Release /p:ServerAddress=<my macbook ip address> p:ServerUser=<username> /p:TcpPort=58181 /p:ArchiveOnBuild=true /p:_DotNetRootRemoteDirectory=/Users/<username>/Library/Caches/Xamarin/XMA/SDKs/dotnet/ /p:EnableAssemblyILStripping=false /p:ServerPassword=<macbook user password>
```

10. Used transporter/testflight to publish
11. Installed the app on my iphone 12 pro max using TestFlight

==============. FAILS ===========
12. When I try to open the app, the app flashes the screen and then closes
13. If I undo all my changes and install the default Maui Blazor app all works fine.

Kindly advice.

### Version with bug

7.0 Release Candidate 1 or older

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, macOS

### Affected platform versions

macOS 12.3.1 (21E258)

### Did you find any workaround?

No

**Comment by arthastheking113** [comment] 2022-06-19 02:39
I have the same issue even thought I don't have builder.Services.AddSingleton<IConnectivity>(Connectivity.Current); in program.cs

Working fine is Android both in simulator and physical devices. 

On iOS, work fine in simulator, got error in TestFlight. 

Get rejected from Apple Review team since it could not pass the flash screen.

I could not reproduce the error in the simulator.

I wonder if this is because of I published the app using my m1 Mac. 

My publish settings

<PropertyGroup Condition="$(TargetFramework.Contains('-ios')) and '$(Configuration)' == 'Release'">
		<RuntimeIdentifier>ios-arm64</RuntimeIdentifier>
		<MtouchUseLlvm>False</MtouchUseLlvm>
		
		
		<CodesignKey>Apple Distribution: {My Name} ({My Code})</CodesignKey>
		<CodesignProvision>{My App Code}</CodesignProvision>
		<ServerAddress>{My Server Address}</ServerAddress>
		<ServerUser>{My Server User}</ServerUser>
		<ServerPassword>{My Server Password}</ServerPassword>
		<TcpPort>58181</TcpPort>
		<ArchiveOnBuild>true</ArchiveOnBuild>
		<BuildIpa>true</BuildIpa>
    <_DotNetRootRemoteDirectory>/Users/{My Server User}/Library/Caches/Xamarin/XMA/SDKs/dotnet/</_DotNetRootRemoteDirectory>
    
</PropertyGroup>

My publish command:
sudo dotnet publish -c:Release -f:net6.0-ios

I sent my .ipa file to Apple using Transporter.

**Comment by myndfire** [comment] 2022-06-20 23:50
1. dotnet new maui-blazor
2. Just added:         builder.Services.AddSingleton<IConnectivity>(Connectivity.Current);
Splash screen on actual iphone 12 pro max appears and then app dies.

**Comment by myndfire** [comment] 2022-06-20 23:52
any workaround?

**Comment by sencagri** [comment] 2022-08-13 16:50
Same here not working on real device

**Comment by JawadJaber** [comment] 2022-08-22 07:38
Same issue here, after sending to TestFlight then every thing crashes

**Comment by JawadJaber** [comment] 2022-08-30 18:22
Hello
Try using interpreter as discussed and confirmed here

https://github.com/dotnet/maui/issues/9597

**Comment by myndfire** [comment] 2022-09-06 13:37
Thanks @JawadJaber. Will try and post the results.

**Comment by myndfire** [comment] 2022-10-17 04:42
Confirmed that it works. Appreciate it @JawadJaber

**Comment by mattleibow** [comment] 2022-12-08 12:56
Duplicate of #9597

**Closed** 2022-12-08 12:56 UTC
Labels: t/bug, platform/iOS 🍎, area/essentials 🍞

**Comment by christallire** [comment] 2022-12-30 07:20
@mattleibow please reopen this issue since referring issue is closed and locked or create a real issue not working on iOS since this is very urgent and blocking. 
The interpreter is not a solution, you know. it crashes everywhere we use linq, serialization.
It basically breaks the MULTIPLATFORM 'M' part of MAUI.

**Comment by christallire** [comment] 2022-12-30 07:28
I created https://github.com/dotnet/maui/issues/12353 for your convenience
