### ISSUE TITLE
[WinUI] CollectionView GridItemsLayout Shows 6 Columns Even When Span is Set to 7, When Display Scale is Set to 125% or 150%

### ISSUE THREAD

**Issue by turdmaggot** [dotnet/maui#23684] opened 2024-07-18 16:26 UTC
### Description

In Windows, when display scale is set to 125% or 150%, _CollectionView_ shows 6 columns even though the _GridItemsLayout_'s span attribute is set to 7. It behaves properly when display scale is set back 100%.

### Steps to Reproduce

1. Create a CollectionView.
2. Add GridItemsLayout as ItemsLayout. Set the following attributes:
- Orientation="Vertical"
- HorizontalItemSpacing="5"
- VerticalItemSpacing="5"
- Span="7"
3. Add a DataTemplate as ItemTemplate, with any control. Preferrably a box with borders with 145x100 in size.
4. Bind it to an itemsource, with about 35 items.
5. Run the Project in Windows.
6. Assuming that your display scale is set to 100% (by default), it should display a 7 columns and 5 rows.
7. Change display scale by going to System/Display/Scale & Layout and look for the scale dropdown. Set it to either 125% or 150%.

**Actual Result:** A Grid with 6 Columns
![image](https://github.com/user-attachments/assets/19f6e6f1-9c1a-4fee-a259-2f7e09015c65)

**Expected Result:** A Grid with 7 Columns
![image](https://github.com/user-attachments/assets/f625c046-9e01-448e-bbc4-89ee32e529b3)

### Version with bug

8.0.60 SR6

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows SDK 10.0.22621.0

### Did you find any workaround?

No

**Comment by Damus765** [comment] 2024-07-20 20:02
This appears to be a duplicate of #23233.

**Comment by ninachen03** [comment] 2024-08-01 07:11
@turdmaggot 
Could you provide a sample project for us to investigate it further?
Looking forward to your reply!

**Comment by jfversluis** [comment] 2024-08-13 11:59
Duplicate of #23233

**Closed by jfversluis** 2024-08-13 11:59 UTC
Labels: t/bug, platform/windows 🪟, area-controls-collectionview, s/triaged, s/needs-attention, migration-compatibility
