### ISSUE TITLE
Grid Background spill outside of the background

### ISSUE THREAD

**Issue by albilaga** [dotnet/maui#23755] opened 2024-07-22 14:01 UTC
### Description

When setting Grid.Background with `LinearGradientBrush` it works fine if that is just the element and no element is changing state from `IsVisible=true` to `IsVisible=False`. But if we have a view top of the grid that have background then the `Background.LinearGradientBrush` will be spilled outside the grid
Let's say we have xaml like this
```xaml
<Grid BackgroundColor="White">
        <AbsoluteLayout HeightRequest="200" VerticalOptions="Start">
            <Image
                AbsoluteLayout.LayoutBounds="0,0,1,200"
                AbsoluteLayout.LayoutFlags="WidthProportional"
                Source="https://picsum.photos/500/200" />
            <Grid
                AbsoluteLayout.LayoutBounds="0,112,1,88"
                AbsoluteLayout.LayoutFlags="WidthProportional"
                HeightRequest="88">
                <Grid.Background>
                    <LinearGradientBrush>
                        <GradientStop Color="Transparent" />
                        <GradientStop Offset="1" Color=" Black" />
                    </LinearGradientBrush>
                </Grid.Background>
                <Label FontSize="Large" Text="Hello" />
            </Grid>
        </AbsoluteLayout>
        <Grid
            x:Name="Popup"
            BackgroundColor="White"
            RowDefinitions="*,Auto"
            VerticalOptions="Fill">
            <BoxView BackgroundColor="White">
                <BoxView.GestureRecognizers>
                    <TapGestureRecognizer Tapped="BoxViewTapped" />
                </BoxView.GestureRecognizers>
            </BoxView>
            <VerticalStackLayout
                Grid.Row="1"
                Padding="20"
                Spacing="8">
                <Label
                    FontAttributes="Bold"
                    FontSize="Large"
                    HorizontalTextAlignment="Center"
                    Text="This is popup" />
                <Button Clicked="Button_OnClicked" Text="Dismiss" />
            </VerticalStackLayout>
        </Grid>
    </Grid>
```
   
and then then when `BoxViewTapped` or `Button_Onclicked` we set `Popup.IsVisible=false` then then `Grid.Background` will be full page. Quite possible related to this https://github.com/dotnet/maui/issues/18664
    
What happen right now:
![CleanShot 2024-07-22 at 20 43 03@2x](https://github.com/user-attachments/assets/4c438dd9-3d6c-47eb-b9a1-8424f0d0a535)

Expected:
![CleanShot 2024-07-22 at 20 44 50@2x](https://github.com/user-attachments/assets/fd88f81a-6225-4be8-8966-e72352e18166)

### Steps to Reproduce

1. Clone https://github.com/albilaga/MauiIssues
2. Run the project on iOS simulator
3. Click `GridBackground`
4. Tap anywhere in white background or click `Dismiss`. It will show the issue
5. Now comment this https://github.com/albilaga/MauiIssues/blob/main/MauiIssues/GridBackground.xaml#L26-L37 and uncomment this line https://github.com/albilaga/MauiIssues/blob/main/MauiIssues/GridBackground.xaml#L13-L25 and restart number 2-4. It will fix the issue

### Link to public reproduction project repository

https://github.com/albilaga/MauiIssues

### Version with bug

8.0.70 SR7

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Did you find any workaround?

Based on @redth answer on [here](https://github.com/dotnet/maui/issues/18664#issuecomment-2096564233) the workaround is wrap around it with `Border`. which is working for now

**Comment by RoiChen001** [comment] 2024-07-23 05:12
This problem cannot be reproduced at iOS platform on the latest 17.11.0 Preview 4(8.0.61&8.0.70).
![image](https://github.com/user-attachments/assets/ba548b4e-9392-49e4-9ab4-c1d90791e870)

**Comment by albilaga** [comment] 2024-07-23 05:16
@RoiChen001 sorry. I am pushed the reproduction project with workaround. Please try again now with latest from my reproduction project in here https://github.com/albilaga/MauiIssues/tree/main . It will show the issue

**Comment by RoiChen001** [comment] 2024-07-23 06:01
I can repro this issue at iOS platform on the latest 17.11.0 Preview 4.0 (8.0.61&8.0.70).
Reproduction project:
https://github.com/albilaga/MauiIssues/tree/main
![image](https://github.com/user-attachments/assets/a1b89593-1a34-44b2-994a-d713e03ec936)

**Comment by mattleibow** [comment] 2024-07-23 22:53
Duplicate of https://github.com/dotnet/maui/issues/18664

**Closed by mattleibow** 2024-07-23 22:53 UTC
Labels: t/bug, platform/iOS 🍎, s/verified, s/triaged, migration-compatibility
