### ISSUE TITLE
MAUI Hot Reload Not Working in VS 2022 17.2.0 Preview 3

### ISSUE THREAD

**Issue by sjbthfc2** [dotnet/maui#6403] opened 2022-04-22 07:39 UTC
### Description

Trying to create a simple MAUI Blazor project and when running it and making changes to a Blazor component HTML Visual Studio up to 42 compiler errors and the following dialog box is displayed:

![image](https://user-images.githubusercontent.com/3796984/164629078-f8a8ea3a-5ed3-4274-b713-cd3f0f59e149.png)

Errors in VS:
![image](https://user-images.githubusercontent.com/3796984/164629541-0048f141-34cd-46a6-96e9-a6aae450530d.png)

### Steps to Reproduce

1. Create a MAUI Blazor app.
2. Run the project with out without debugging.
3. Attempt to change any component Razor mark-up and Hot Reload fails with numerous compiler errors.

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Preview 12

### Affected platforms

Android, Windows

### Affected platform versions

Android Oreo 8.1 and Windows

### Did you find any workaround?

None

### Relevant log output

```shell
Hot Reload output in VS:
Checking for updates...
Invalid changes were found. Please refer to the Error List window to fix those issues.
Checking for updates...
Invalid changes were found. Please refer to the Error List window to fix those issues.
Checking for updates...
No changes were found.
Checking for updates...
No changes were found.
Checking for updates...
Invalid changes were found. Please refer to the Error List window to fix those issues.
Checking for updates...
Invalid changes were found. Please refer to the Error List window to fix those issues.
Checking for updates...
Invalid changes were found. Please refer to the Error List window to fix those issues.
```

**Comment by drasticactions** [comment] 2022-04-22 20:04
Duplicate of https://github.com/dotnet/maui/issues/4989

This is a Rosyln issue, it's unrelated to MAUI.

**Closed by drasticactions** 2022-04-22 20:04 UTC
Labels: t/bug, s/needs-verification
