### ISSUE TITLE
Button with ImageSource that's too big for button renders incorrectly

### ISSUE THREAD

**Issue by jknaudt21** [dotnet/maui#15004] opened 2023-05-09 19:26 UTC
### Description

Creating a button that uses an ImageSource but constrained dimensions (i.e the WidthRequest is too small for the image) will render a button that, depending on the platform will display incorrectly. The image will either be improperly aligned or simply display entirely. Windows seems to be working fine, the other platforms seem to be affected. 

Sample code: 
```xaml
    <StackLayout>
            <Button Text="Some random text that I've typed to occupy space"
                    BackgroundColor="AliceBlue"
                    ImageSource="dotnet_bot.png"
                    WidthRequest="100"
                    TextColor="Black"
                    />
    </StackLayout>
```

On iOS and Mac, the button should have text to repro this bug. On Android the button doesn't need text

iOS
<img width="439" alt="image" src="https://github.com/dotnet/maui/assets/32918747/57453876-74fd-4f57-8e27-4b3e5098d147">

Mac 
<img width="559" alt="image" src="https://github.com/dotnet/maui/assets/32918747/acababd7-9173-4922-b577-3e290aa5effc">

Android
<img width="406" alt="image" src="https://github.com/dotnet/maui/assets/32918747/45622da6-3799-43a9-8f87-b0e2043705cf">

### Steps to Reproduce

1. Build MAUI using the latest in main
2. On the sandbox project, add this to the main page:
```xaml
    <StackLayout>
            <Button Text="Some random text that I've typed to occupy space"
                    BackgroundColor="AliceBlue"
                    ImageSource="dotnet_bot.png"
                    WidthRequest="100"
                    TextColor="Black"
                    />
    </StackLayout>
```
3. Build and deploy 

### Link to public reproduction project repository

(see description)

### Version with bug

8.0 previews

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, macOS

### Affected platform versions

Mac, Android, iOS

**Comment by XamlTest** [comment] 2023-09-14 10:04
Verified this on Visual Studio Enterprise 17.8.0 Preview 1.0. Repro on Android 13.0-API33 and iOS 16.4(8.0.0-preview.7.8842), not repro on Windows 11 with below Project:
[15004.zip](https://github.com/dotnet/maui/files/12607492/15004.zip)

**Comment by PureWeen** [comment] 2024-05-09 01:12
Duplicate of #22306

**Closed by PureWeen** 2024-05-09 01:12 UTC
Labels: t/bug, platform/macOS 🍏, platform/android 🤖, platform/iOS 🍎, area/controls 🎮, s/verified, control-button, s/triaged
