### ISSUE TITLE
Initial Launch of Shell, the FlyoutIsPresented doesn't work code-behind until user taps it

### ISSUE THREAD

**Issue by logikonline** [dotnet/maui#10037] opened 2022-09-10 19:32 UTC
### Description

Launch a shell, the FlyoutIsPresented = true will not open the Flyout in code-behind until the user taps it in the interface.  I need to force it to open with a button on the page before the user taps the drawer.

### Steps to Reproduce

1. Create New Maui App
2. Add Shell Page, set as MainPage
3. Add a button to the initial ShellContent
4. In button click logic, set the FlyoutIsPresented = true (either on the MainThread or not)

Observe it not opening.  Click the drawer yourself, then click the button to see it function

### Link to public reproduction project repository

https://github.com/logikonline/MauiFlyoutPresentedBug

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11 - using a Surface Duo 2

### Did you find any workaround?

Only if the user first taps it, but this defeats the purpose of the button I need

**Comment by PureWeen** [comment] 2022-09-13 18:22
Closing as duplicate of https://github.com/dotnet/maui/issues/8226

**Closed by PureWeen** 2022-09-13 18:22 UTC
Labels: t/bug, platform/android 🤖, area/shell 🐢
