### ISSUE TITLE
Orientation Layout  Background not working on iOS with LinearGradientBrush

### ISSUE THREAD

**Issue by hannah-dev92** [dotnet/maui#23763] opened 2024-07-22 18:43 UTC
### Description

<img width="362" alt="image" src="https://github.com/user-attachments/assets/61a41f49-d982-470a-8034-8ce5161a9398">
Background color not covering the screen when changing device orientation

### Steps to Reproduce

Create a LinearGradientBrush Style
`    <LinearGradientBrush x:Key="Gradient_L0"
                         EndPoint="0,1">
        <GradientStop Color="{DynamicResource Primary}"
                      Offset="0" />
        <GradientStop Color="{DynamicResource Tertiary}"
                      Offset="1" />
    </LinearGradientBrush>`
Set the background property to the LinearGradient Brush
`<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MauiApp3.MainPage"
             Background="{DynamicResource Gradient_L0}">`
change Device Orientation on iPad or iPhone
-> only part of the screen is covered with expected background color

### Link to public reproduction project repository

https://github.com/hannah-dev92/Maui-Background-Example/tree/master

### Version with bug

8.0.7 SR2

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 17.0

**Comment by PureWeen** [comment] 2024-07-22 22:15
Duplicate of #23501

**Closed by PureWeen** 2024-07-22 22:15 UTC
Labels: t/bug
