### ISSUE TITLE
Flyout items can vanish when arrowing down through a flyout

### ISSUE THREAD

**Issue by gbarkerz** [dotnet/maui#8834] opened 2022-07-19 14:25 UTC
### Description

When arrowing down through a Maui Flyout, items below the 2nd item in the flyout can visually vanish, leaving only space where they once were.

**Before**. Alt: A test .NET Maui app running on Windows. Its flyout is open, showing items of "First", "Second", "Third", "Fourth", and "Fifth". Keyboard focus feedback is shown at the first item in the flyout.

<img width="291" alt="Flyout1" src="https://user-images.githubusercontent.com/77085891/179773760-4c44dfd3-2d4f-4807-baa4-edb103a383dc.png">

**After**. Alt: A test .NET Maui app running on Windows. Its flyout is open, showing items of "First" and "Second", with keyboard focus feedback showing on the second item. No other items are shown, yet the flyout is large enough to contain multiple other items.

<img width="268" alt="Flyout2" src="https://user-images.githubusercontent.com/77085891/179773795-bda11135-b87c-4648-977c-d03890d43bb0.png">

### Steps to Reproduce

1. Build and run this test app for Windows, https://github.com/gbarkerz/MyVeryFirstMauiApp.
2. Tab to move keyboard focus to the Open Navigation button at the top left corner of the app.
3. Press Space to invoke the flyout.
4. Press DownArrow to move keyboard focus to the first item in the flyout.
5. Press DownArrow again to move keyboard focus to the second item in the flyout.

Result: Following the second DownArrow press, all items following the second item visually vanish.

Note: If I then Alt+Tab away and back to the app, press Escape to close the flyout, re-open the flyout, the issue doesn't seem to happen after that until I restart the app.

My version of dotnet is 6.0.400-preview.22330.6.

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

net6.0-windows10.0.19041.0

**Comment by keerthiduvvuri** [comment] 2022-09-16 11:27
#.NET MAUI; #A11ySev1; #A11yMAS; #A11yTCS; #Benchmark; #DesktopApp; #Win11; #WCAG2.1.1; #GH_.NETMAUI_Win32_Apr2022; #AILimited; #Win32; #Keyboard;

**Comment by merriemcgaw** [comment] 2022-09-29 20:50
@PureWeen this should likely be marked as an accessibility issue.

**Comment by merriemcgaw** [comment] 2022-10-13 00:43
@gbarkerz @PureWeen do you know if the flyout items are still available in the UIA tree?

**Comment by gbarkerz** [comment] 2022-10-13 11:33
Hi @merriemcgaw, I'm not set up to test it just at the moment, but looking at this, https://twitter.com/gbarkerZ/status/1551965741284573184?s=20&t=OMFyiEoaIT-7MIiVIfvumQ, it seems I ran Accessibility Insights after the visuals vanished, and the contents of the list items had gone from UIA too. All that was left from the item was the item itself, and given that the item's name was meaningless to the user, there was no way for anyone to access the original helpful text on the item.

**Comment by PureWeen** [comment] 2022-10-13 20:06
> Hi @merriemcgaw, I'm not set up to test it just at the moment, but looking at this, https://twitter.com/gbarkerZ/status/1551965741284573184?s=20&t=OMFyiEoaIT-7MIiVIfvumQ, it seems I ran Accessibility Insights after the visuals vanished, and the contents of the list items had gone from UIA too. All that was left from the item was the item itself, and given that the item's name was meaningless to the user, there was no way for anyone to access the original helpful text on the item.

 I think this part of it has been resolved. Now that we propagate the correct description values to the flyout items the UIA info is still present. I've also noticed if you close and reopen the flyout everything reappears and then never vanishes again. It's only the initial open/navigation that's buggy :-/ 
 
![image](https://user-images.githubusercontent.com/5375137/195698379-d183136f-8ccb-4e8f-9d5f-380b44aaddfb.png)

**Comment by merriemcgaw** [comment] 2022-10-13 20:31
That's awesome! You will be moving in .NET 8?

**Comment by PureWeen** [comment] 2022-10-13 20:53
> That's awesome! You will be moving in .NET 8?

Once WinAppSDK 1.2 goes stable we'll bump .NET 7 up to 1.2 in a SR

**Comment by merriemcgaw** [comment] 2022-10-13 21:11
Great news!

**Comment by PureWeen** [comment] 2022-10-20 20:53
### WinAppSDK 1.1.5

![2022-10-20_15-50-54](https://user-images.githubusercontent.com/5375137/197055692-f5491616-3d45-4c0b-b246-36b640d064f9.gif)

### WinAppSDK 1.2.220930.4-preview2
![2022-10-20_15-51-03](https://user-images.githubusercontent.com/5375137/197055674-8ce3aca3-c879-49d6-80f2-7743eb0580b3.gif)


### Project you can test

You will need to use Visual Studio 17.4 P4 to run this project

[ShellFlyoutKeyboard.zip](https://github.com/dotnet/maui/files/9833806/ShellFlyoutKeyboard.zip)

**Comment by PureWeen** [comment] 2022-11-21 19:59
Duplicate of #11522

**Closed by PureWeen** 2022-11-21 19:59 UTC
Labels: t/bug, platform/windows 🪟, area/desktop 🖥️, area/FlyoutPage
