### ISSUE TITLE
iOS .Net 9 TapGestureRecognizer not working anymore on Button

### ISSUE THREAD

**Issue by SchittkowskiMS** [dotnet/maui#26668] opened 2024-12-17 08:51 UTC
### Description

On iOS .Net 9 TapGestureRecognizer doesnt trigger anymore on buttons. On Android works as expected.

I selected "unknown" on "Last version that worked well" as im not sure which version of .Net 8 it worked but after upgrading to .Net 9 it didnt work anymore.

### Steps to Reproduce

1. Add following code to some page
```
            var bt = new Button()
            {
                Text = "TestButton"
            };
            bt.GestureRecognizers.Add(new TapGestureRecognizer()
            {
                NumberOfTapsRequired = 1,
                Command = new Command(() =>
                {
                    DisplayAlert("Alert", "Button clicked", "OK");
                })
            });
            stk.Add(bt);


            var lbl = new Label()
            {
                Text = "TestLabel",
            };
            lbl.GestureRecognizers.Add(new TapGestureRecognizer()
            {
                NumberOfTapsRequired = 1,
                Command = new Command(() =>
                {
                    DisplayAlert("Alert", "Label clicked", "OK");
                })
            });
            stk.Add(lbl);
```
2. Debug on iOS device.
3. Press button -> no alert shown
4. Press label -> alert shown

### Link to public reproduction project repository

Sample provided in "Steps to Reproduce"

### Version with bug

9.0.10 SR1

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 17.6.1

### Did you find any workaround?

No

### Relevant log output

```shell

```

**Comment by jfversluis** [comment] 2024-12-17 09:13
Duplicate of #19099

**Closed by jfversluis** 2024-12-17 09:13 UTC
Labels: t/bug
