### ISSUE TITLE
Impossible to run any UnitTest on MAUI

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#17914] opened 2023-10-09 16:06 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Impossible-to-run-any-UnitTest-on-MAUI/10482714)._

---
[severity:It's more difficult to complete my work]
Hello everyone,
I didn't know <UseMaui>true</UseMaui> before and it solved my problem with my class library.

On my UI .csproject I defined:
```
<PropertyGroup>
  <UseMaui>true</UseMaui>
  <TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net7.0-windows10.0.19041.0;net7.0-  android33.0</TargetFrameworks>
</PropertyGroup>
```

And on my Interface .csproject (which is a Class library), I defined:
```
<PropertyGroup>
  <TargetFramework>net7.0</TargetFramework>
</PropertyGroup>
```

---
Unfortunately, now I have a problem with my MsTest UnitTest project which references my UI project!

I receive the error:
```
"Framework: 'Microsoft.Maui.Core', version '7.0.92' (x64). .NET location: C:\Program Files\dotnet? No frameworks were found."
```
Desperately, the message is incorrect and directed in the wrong direction!
Because, I installed all MAUI workloads and especially as explained above the problem comes from a configuration to be applied...
Could you please help me to find this configuration?

I thank you in advance!
Best regards

Davy

---
#### Feedback Bot on 10/6/2023, 06:57 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by drasticactions** [comment] 2023-10-10 10:11
This is the same as https://github.com/dotnet/maui/issues/17791

They are referencing a generic class project (`net7.0`) into the UI Project (which are all platform specific). The error is correct. If you want to test UI specific code, you would need a test runner and do it on device. If there is code beyond UI that is generic, but inside of that project, it would need to be moved out into a class library that did target `net7.0` specifically.

**Comment by jsiemensLatitudegeo** [comment] 2023-10-23 16:56
I have the same problem.

**Comment by mattleibow** [comment] 2023-11-11 12:34
Duplicate of https://github.com/dotnet/maui/issues/11575

**Closed by mattleibow** 2023-11-11 12:34 UTC
Labels: t/bug, area/testing
