### ISSUE TITLE
Radius feature on Shadow not working

### ISSUE THREAD

**Issue by AlexanderSCK** [dotnet/maui#10586] opened 2022-10-10 13:03 UTC
### Description

adjusting the Shadow property Radius on the newest .NET MAUI build doesnt affect the visual of the shadow

### Steps to Reproduce

Create a shadow for an element, 
Set the radius to a float

 <Shadow  Brush="Red"
                             Offset="1,8"
                             Opacity="0.3"
                             Radius="207"/>

### Link to public reproduction project repository

easily reproducable by adjusting Radius of the Shadow

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 13

### Did you find any workaround?

No workaround

**Comment by rmarinho** [comment] 2022-10-10 14:09
Duplicated #10401

**Comment by rmarinho** [comment] 2022-10-10 14:10
Duplicate of #10401

**Closed** 2022-10-10 14:10 UTC
Labels: t/bug, platform/android 🤖
