### ISSUE TITLE
MAUI Blazor in .NET 9 does not run on Android API level 31 and below

### ISSUE THREAD

**Issue by thomasbach-dk** [dotnet/maui#25862] opened 2024-11-14 12:46 UTC
### Description

I am currently playing with an upgrade from .NET 8 to .NET 9. We have a .NET MAUI Blazor (Hybrid) app, and when we run the app on Android (emulator) API level 31 we get the following console error:

```shell
11-14 13:12:32.688 I/chromium(12480): [INFO:CONSOLE(1)] "Uncaught SyntaxError: Unexpected token '{'", source: https://0.0.0.0/_framework/blazor.webview.js (1)
[INFO:CONSOLE(1)] "Uncaught SyntaxError: Unexpected token '{'", source: https://0.0.0.0/_framework/blazor.webview.js (1)
```

This error prevents the app from loading.

Running the app on Android API level 32 and above the issue does not occur.

In terms of the [documentation of .NET 9](https://learn.microsoft.com/en-us/dotnet/maui/supported-platforms?view=net-maui-9.0) Android API level 24 should be supported.

**UPDATE:**
I figured out that updating the Android System WebView in the emulator fixed this issue.

### Version with bug

9.0.0 GA

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.402

### Affected platforms

Android

### Affected platform versions

Android API level 31 and below (Android 12 and below)

### Did you find any workaround?

No

### Relevant log output

```shell
11-14 13:12:32.688 I/chromium(12480): [INFO:CONSOLE(1)] "Uncaught SyntaxError: Unexpected token '{'", source: https://0.0.0.0/_framework/blazor.webview.js (1)
[INFO:CONSOLE(1)] "Uncaught SyntaxError: Unexpected token '{'", source: https://0.0.0.0/_framework/blazor.webview.js (1)
```

**Comment by Ying-6** [comment] 2024-11-15 05:49
Hi @thomasbach-dk, your Android emulator API level is 31. Could you provide the specific information of your Base Device and Processor? Because I did not reproduce your problem on the following version of Android emulator: Base Device: Pixel 7 (+ Store), Processor: x86_64, OS: Android 12.0 - API 31.
And could you provide us with a sample project so we can investigate it further? Looking forward to your reply!

**Comment by Eilon** [comment] 2024-11-15 18:09
Possible dupe: https://github.com/dotnet/aspnetcore/issues/53699 (the error in the other issue is slightly different, but possibly same root cause)

**Comment by danroth27** [comment] 2024-11-18 17:27
Closing as a duplicate of dotnet/aspnetcore#53699

**Closed by danroth27** 2024-11-18 17:27 UTC
Labels: t/bug, area-blazor, s/verified, s/triaged, i/regression

**Comment by capdiem** [comment] 2024-11-19 01:50
So this is a BREAKING CHANGE and cannot be avoided 👎

**Comment by danroth27** [comment] 2024-11-19 22:55
> So this is a BREAKING CHANGE and cannot be avoided 👎

@capdiem Are you seeing your app end users impacted by this change? Or are you only hitting this during development with the Android emulator? Our theory here is that most app users will have an up-to-date web view on Android.

**Comment by capdiem** [comment] 2024-11-20 01:53
@danroth27 We have various testing phones with different versions and models to ensure that users do not encounter issues on their devices. A phone running Android 11 with WebView version 90.0.4430.210 is not functioning properly after the upgrade.

This [link](https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Win_x64/856944/) points to a Chrome version 90.0.4427.0, which also encounters this error. The error points to the [static](https://github.com/dotnet/aspnetcore/blame/091e35e3ae113e79b8d973ebdcd96404ba4f9758/src/Components/Web.JS/src/Rendering/Events/EventDelegator.ts#L66) keyword. Perhaps abandoning the use of the static keyword is a good approach, as ES5 does not support static.

**Comment by capdiem** [comment] 2024-11-20 03:15
@danroth27 I found that the issue is not with TypeScript, but rather that the generated release file contains the code `static{this.nextEventDelegatorId=0}`. Normally, it should generate `static nextEventDelegatorId = 0`. You can find in https://github.com/dotnet/aspnetcore/blob/main/src/Components/Web.JS/dist/Release/blazor.webassembly.js

**Comment by danroth27** [comment] 2024-11-21 20:29
> A phone running Android 11 with WebView version 90.0.4430.210 is not functioning properly after the upgrade.

@capdiem That WebView version is very old. Is this a physical device that just hasn't had it's WebView updated? Or is this an emulated device with the default WebView version that came with Android 11?

To be clear our official [support policy](https://learn.microsoft.com/aspnet/core/blazor/supported-platforms) is that we only support the latest browser versions. Since most users have browsers that automatically update, we find this generally isn't an issue for deployed apps. I'd like to understand if your end users are actually impacted by this limitation or if this is just a test infrastructure issue.
