### ISSUE TITLE
[iOS] Warning due to implementation of "performFetchWithCompletionHandler" although "PerformFetch" was not implemented

### ISSUE THREAD

**Issue by Ktastic93** [dotnet/maui#26462] opened 2024-12-08 14:35 UTC
### Description

When I run a .NET MAUI project (.NET 9) for iOS 18.1 on a simulator or on a real device, I always get the following warning:
_You've implemented -[<UIApplicationDelegate> application:performFetchWithCompletionHandler:], but you still need to add "fetch" to the list of your supported UIBackgroundModes in your Info.plist._

The "PerformFetch" method was not implemented in "AppDelegate".

I don't want to add "fetch" to the background modes as it is not used.

### Steps to Reproduce

Just create a new MAUI project in .NET 9 with the default main page and debug it on a iOS 18.1 simulator or real device.
The warning is displayed in the Debug output.

### Version with bug

9.0.10 SR1

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 18.1, Xcode 16.1

### Did you find any workaround?

Not yet

### Relevant log output

```shell
2024-12-08 15:25:10.666122+0100 MauiApp2[56839:5828594] You've implemented -[<UIApplicationDelegate> application:performFetchWithCompletionHandler:], but you still need to add "fetch" to the list of your supported UIBackgroundModes in your Info.plist.
```

**Comment by jfversluis** [comment] 2024-12-09 10:17
Duplicate of #17960

**Comment by jfversluis** [comment] 2024-12-09 10:17
Not exact duplicate, but its mentioned there in a comment. Its only a warning, of course one we want to fix, but should not be blocking you in any way.

**Closed by jfversluis** 2024-12-09 10:17 UTC
Labels: t/bug
