### ISSUE TITLE
Can't submit a MacCatalyst app to AppStore.

### ISSUE THREAD

**Issue by petervaradi** [dotnet/maui#15011] opened 2023-05-10 12:29 UTC
I have a simple MAUI App for Windows and Mac Catalyst. (No blazor just XAML)
My Mac is running the latest version of macOS (Ventura 13.3.1), latest version of Xcode 14.3.
![062FBCFA-6A50-4AC9-9876-BA9284857BDA](https://github.com/dotnet/maui/assets/2270218/56ca1c13-0265-4969-ab1d-aed824837400)

I build the App with "dotnet build -f net7.0-maccatalyst -c Release". It builds a pkg file fine. I can upload it to AppStore, the AppStore upload verification goes through fine, but as soon as I try to release it to TestFlight, it fails with "This build is using a beta version of Xcode and can't be submitted."

![9E4CD674-BDAD-4180-A62D-E965A95FE9BD](https://github.com/dotnet/maui/assets/2270218/2eaadd08-8103-478d-aa78-c969ff879cd4)

I'm not using any beta version of Xcode as far as I'm aware.  

What did I do wrong?
Thank you for the help!

**Comment by symbiogenesis** [comment] 2023-05-10 13:29
Are you running the latest service release from yesterday? Everything prior to that is incompatible with XCode 14.3

**Comment by petervaradi** [comment] 2023-05-10 14:07
Hi Edward, 

Not sure how to get the latest service release apart from doing "sudo dotnet workload update". 
I did do a workload update today but that's probably not what you are referring to. 

How do you update your framework to include the service release change?

Thank you!
Peter

**Comment by mattleibow** [comment] 2023-05-10 18:15
@rolfbjarne  @dalexsoto thoughts?

**Comment by rolfbjarne** [comment] 2023-05-10 18:28
This looks like a duplicate of https://github.com/xamarin/xamarin-macios/issues/13300 - please look at that for a workaround until the fix has been released.

**Comment by mattleibow** [comment] 2023-05-10 18:56
Duplicate of https://github.com/xamarin/xamarin-macios/issues/13300

**Comment by mattleibow** [comment] 2023-05-10 18:58
@rolfbjarne  how would one get the correct values for mac catalyst for xcode 14.3?

**Comment by rolfbjarne** [comment] 2023-05-10 19:02
> @rolfbjarne how would one get the correct values for mac catalyst for xcode 14.3?

Build a Mac Catalyst app in Xcode 14.3 and look at the Info.plist in the resulting app bundle.

**Comment by petervaradi** [comment] 2023-05-11 06:32
This issue is solved after inserting the values into info.plist. I used the ones for 14.2 from here:
https://github.com/xamarin/xamarin-macios/issues/13300#issuecomment-1404702036

Thank you for the help.

**Closed** 2023-05-12 14:51 UTC
Labels: platform/macOS 🍏, area/publishing 🏁, partner/macios, external

**Comment by rmarinho** [comment] 2023-12-15 16:46
I m hitting this with Xcode 15 and stable net8 iOS workload. shouldn't this be fixed there @rolfbjarne  ?

**Comment by rolfbjarne** [comment] 2023-12-15 17:33
@rmarinho this is fixed in .NET 8. Can you attach your .ipa/.pkg and state which Xcode version you're using?
