### ISSUE TITLE
MAUI Picker Control fails to show items in .NET 7 on Mac Catalyst Desktop

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#19273] opened 2023-12-06 22:52 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/MAUI-Picker-Control-fails-to-show-items-/10516250)._

---
In .NET 7 applications running on Mac Desktop, the Picker Control fails to show ItemsSource options when the window is narrowed only a little. This behavior does not exist in .NET 6, where the items are always shown.

It is very easy to recreate this - and I have done it on both my Macs.

1.  In VS2022, File->New Project->.NET MAUI App.
2.  Select Target Framework .NET 7
3.  Continue Button in bottom right.
4.  Project Name and Solution Name are your choice
5.  In MainPage.xaml which appears in Solution Explore, replace the Hello World Label with the Picker example XAMLat [https://learn.microsoft.com/en-us/dotnet/maui/user-interface/controls/picker?view=net-maui-7.0](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/controls/picker?view=net-maui-7.0)

The example Picker is copied here - and again - it is as simple as pasting over the Hello World label in MainPage.xaml. 
(Our QA teem noted that removal of the **Title="Select a monkey"** from the Picker XAML, an unacceptable compromise of course, restores the list in the UI.  I've bolded that in your example XAML below to be clear.  Hope that helps)

<Picker x:Name=“picker”  
Title=“Select a monkey”>  
<Picker.ItemsSource>  
<x:Array Type=“{x:Type x:String}”>  
<x:String>Baboon</x:String>  
<x:String>Capuchin Monkey</x:String>  
<x:String>Blue Monkey</x:String>  
<x:String>Squirrel Monkey</x:String>  
<x:String>Golden Lion Tamarin</x:String>  
<x:String>Howler Monkey</x:String>  
<x:String>Japanese Macaque</x:String>  
</x:Array>  
</Picker.ItemsSource>  
</Picker>

Run the application. You will see that when you narrow the window, the list of monkeys disappear and a .NET icon appears at top. I clicked around that icon and it is clear that the list is gone.

in .NET 6 the Window cannot be narrowed to the point that the list disappears.

---
#### Feedback Bot on 11/15/2023, 07:01 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by drasticactions** [comment] 2023-12-07 01:47
Duplicate of https://github.com/dotnet/maui/issues/18015

**Closed by drasticactions** 2023-12-07 01:47 UTC
Labels: t/bug
