### ISSUE TITLE
Builds are significantly slower with Internet access

### ISSUE THREAD

**Issue by BlueRaja** [dotnet/maui#21532] opened 2024-03-30 01:44 UTC
### Description

When I start VS + Android Emulator with my internet cord unplugged, my builds are almost 10x faster.

Here are some actual timings I took:

|| No Internet  | With Internet |
|---| ------------- | ------------- |
Launch on Android Emulator with no changes: | 18.1s | 137.5s  |
...with a simple change to a .cs file:| 26.4s  | 156.0s  |
...with a simple change to a .xaml file| 21.3s | 139.3s |

I tried this multiple times, and was able to reproduce every time.

### Steps to Reproduce

1. Run VS like normal, with Internet connected, and pre-launch the emulator.
2. Choose "Debug" mode, with the Android project selected.
3. Hit the "play" button to build +deploy the project.
4. Close VS + the emulator
5. Disconnect your internet cable
6. Relaunch VS + the emulator
7. Hit the "play" button again

Expected results:
Build + Deploy take the same amount of time

Actual results:
Build is 6x slower with Internet connected.  Sometimes the _first_ build after disconnecting the Internet is still slow, but subsequent builds are fast. No build is _ever_ fast with Internet connected - my 20s build was the first time MAUI _ever_ took me under 2 minutes to build+deploy.

Interestingly, when the builds are slow, the status bar says "Building..." for a long time, even when you didn't make any changes.  However when builds are being fast, it never says "Building..." and goes straight to "Deploying"

### Version with bug

8.0.7 SR2

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Visual Studio Version 17.10.0 Preview 1.0
Emulator is Android 13 - API 33 - Pixel 5

### Did you find any workaround?

If you launch VS + the emulator while the Internet is disconnected and build the app once, builds will continue to be fast even after reconnecting the Internet until you restart VS.

**Comment by jfversluis** [comment] 2024-03-30 09:51
Does this also happen when you do builds from the command-line? Is this specific to .NET MAUI or also for other projects?

This might be something that is caused by Visual Studio and needs to be reported there.

**Comment by BlueRaja** [comment] 2024-03-31 01:55
This problem is specific to MAUI. Non-MAUI projects do not attempt to do a full rebuild _(which I assume is what's happening here)_ when no changes have occurred, with or without Internet.

I'm not sure how to do the equivalent of the VS "play" button from the command-line. How do I tell it "build the project, but only the parts in need of a rebuild; then publish to the device, run the program, and attach the debugger"?

**Comment by BlueRaja** [comment] 2024-03-31 06:29
I played around with it some more:

_(No Internet)_ → Start VS → _(Connect Internet)_ → Launch Emulator → Hit 'play' button → **Builds are slow**  
_(No Internet)_ → Start VS → Build solution → _(Connect Internet)_ → Launch Emulator → Hit 'play' button → **Builds are fast**

So apparently the issue happens when you have Internet during the first build after launching VS.

**Comment by ewerspej** [comment] 2024-04-04 07:32
Could this be related to restoring nuget packages?

**Comment by asi-evin** [comment] 2024-04-04 14:56
Wow this was quiet the journey... 

So I've been having problems with terribly slow build times and Android, both emulator and real device. It's forced me to do most of my development on iOS locally. 

Andthen i saw this, so I tried disabling my wifi. Here's my sequence

1. Disable Wifi
2. Clean Solution
3. Build + Deploy (hit "play" for my device)
![build + deploy from clean (no wifi)](https://github.com/dotnet/maui/assets/136844306/feada7a4-8bdf-4b06-afca-45cce5a304f5)

4. Make One Small Change
5. Build + Deploy
![build + deploy one small change (no wifi)](https://github.com/dotnet/maui/assets/136844306/156b5f30-b629-42f6-9749-204122e8a630)

Holy SH*** that's WAY BETTER. I usually have debug build times of like 2 minutes, even on small changes!!! So then I tried enabling my wifi and trying again.

1. Enable Wifi, confirm I have internet connection.
2. Clean Solution
3. Build + Deploy
![build + deploy from clean (wifi enable)](https://github.com/dotnet/maui/assets/136844306/1ef3aa8d-7b37-4ba7-a6a9-d704f7f2620a)

4. Make One Small Change
5. Build + Deploy
![build + deploy one small change (wifi enable)](https://github.com/dotnet/maui/assets/136844306/35b13c44-6d6c-41f0-8eab-8b067a22d2e6)

Welll WTF??? It's simply fixed now? So I decided to see if I could break it. Again. First thing I tried:

1. Clean Solution.
2. Close Visual Studio
3. Re-Open Visual Studio, give it a few minutes to settle.
4. Build + Deploy

And unfortunately, this was causing errors. Retried cleaning and building a few times. Then I...

5. Clean Solution.
6. Delete bin/obj files in the MAUI project
7. Build + Deploy (still failed)
8. Cleaned Solution
9. Delete bin/obj files in the MAUI project
10. Did a "Rebuild" instead (took 1:05)
11. Build + Deploy
![image](https://github.com/dotnet/maui/assets/136844306/cf136d6a-9321-4c10-a4ba-76b235e0e2c1)
12. Make One Small Change
13. Build + Deploy
![image](https://github.com/dotnet/maui/assets/136844306/eff89472-8f4c-4620-808c-68eab9c3a5ef)

Now we're getting somehwere. And just to be sure, I did re-do steps 13 & 14 a few more times. So now we have effectively gone from ~11 seconds build + deploy to ~100 seconds, nearly a 10x difference!!!

So then I tried disabling my wifi, cleaning solution, build + deploy, etc...
![image](https://github.com/dotnet/maui/assets/136844306/2019d701-f6fa-47e5-8c90-6751b6de8797)

Man, I just can't catch a break... I will re-comment, I'm going torch my git-repo offline, but thought I'd should post the saga before I disable my wifi again.

Relevant logs so far:

[build + deploy from clean (no wifi).txt](https://github.com/dotnet/maui/files/14872824/build.%2B.deploy.from.clean.no.wifi.txt)
[build + deploy one small change (no wifi).txt](https://github.com/dotnet/maui/files/14872827/build.%2B.deploy.one.small.change.no.wifi.txt)
[build + deploy from clean (wifi enable).txt](https://github.com/dotnet/maui/files/14872825/build.%2B.deploy.from.clean.wifi.enable.txt)
[build + deploy one small change (wifi enable).txt](https://github.com/dotnet/maui/files/14872828/build.%2B.deploy.one.small.change.wifi.enable.txt)
[build + deploy from clean (after VS restart)(failure).txt](https://github.com/dotnet/maui/files/14872823/build.%2B.deploy.from.clean.after.VS.restart.failure.txt)
[rebuild + build + deploy from clean (after VS restart).txt](https://github.com/dotnet/maui/files/14872830/rebuild.%2B.build.%2B.deploy.from.clean.after.VS.restart.txt)
[build + deploy one small change (after VS restart).txt](https://github.com/dotnet/maui/files/14872826/build.%2B.deploy.one.small.change.after.VS.restart.txt)
[build + deploy one smalle change (no wifi second time).txt](https://github.com/dotnet/maui/files/14872829/build.%2B.deploy.one.smalle.change.no.wifi.second.time.txt)

**Comment by asi-evin** [comment] 2024-04-04 16:15
Whelp, so I couldn't fix the issue. It now builds slowly, no matter what. I feel Like Icarus flying too close to the sun...

I did do a compare of the small change logs between the builds with one small change: no wifi vs wifi enable. Here is what I noticed:

- "NuGet package restore failed." in build without internet
- Near the end, it appears the internet build is deleting files and the non-internet version is not.
Internet version:
> Skipping target "_BuildApkFastDev" because all output files are up-to-date with respect to the input files.
> Skipping target "_CopyPackage" because all output files are up-to-date with respect to the input files.
> Touching "obj\Debug
> et8.0-android\android_debug_keystore.flag".
> Skipping target "_Sign" because all output files are up-to-date with respect to the input files. 

Internet Version:

> Deleting file "bin\Debug
> et8.0-android\com.silverwolf.maui.user.apk".
> Copying file from "C:\Forks\silverwolf-user-app\Source\SilverWolfUserApp\SilverWolfUserApp.MAUI\obj\Debug
> et8.0-android\android\bin\com.silverwolf.maui.user.apk" to "C:\Forks\silverwolf-user-app\Source\SilverWolfUserApp\SilverWolfUserApp.MAUI\bin\Debug
> et8.0-android\com.silverwolf.maui.user.apk".
> Creating "obj\Debug
> et8.0-android\android_debug_keystore.flag" because "AlwaysCreate" was specified.
> Touching "obj\Debug
> et8.0-android\android_debug_keystore.flag".
> Deleting file "C:\Forks\silverwolf-user-app\Source\SilverWolfUserApp\SilverWolfUserApp.MAUI\bin\Debug
> et8.0-android\com.silverwolf.maui.user-Signed.apk".
> C:\Program Files (x86)\Android\android-sdk\build-tools\34.0.0\zipalign.exe -p 4 "obj\Debug
> et8.0-android\android\bin\com.silverwolf.maui.user.apk" "bin\Debug
> et8.0-android\\com.silverwolf.maui.user-Signed.apk" 
> C:\Program Files (x86)\Android\openjdk\jdk-17.0.8.101-hotspot\bin\java.exe -jar "C:\Program Files (x86)\Android\android-sdk\build-tools\34.0.0\lib\apksigner.jar" sign --ks "C:\Users\EBallantyne\AppData\Local\Xamarin\Mono for Android\debug.keystore" --ks-pass pass:android --ks-key-alias androiddebugkey --key-pass pass:android --min-sdk-version 21 --max-sdk-version 28  bin\Debug
> et8.0-android\com.silverwolf.maui.user-Signed.apk 
> Signed android package 'bin\Debug
> et8.0-android\com.silverwolf.maui.user-Signed.apk'

Hopefully this can possibly give SOME insight on the slow build times, because Development on Android is very painful at the moment.

**Comment by jpobst** [comment] 2024-04-05 02:47
If you build using [`Diagnostic` verbosity](https://docs.microsoft.com/en-us/xamarin/android/troubleshooting/troubleshooting#diagnostic-msbuild-output) or creating a [`binlog`](https://github.com/dotnet/msbuild/blob/main/documentation/wiki/Providing-Binary-Logs.md) it will provide a lot more information telling you exactly what is running.

It should also end with a build performance summary to see how long each step takes, eg:

```
1>Task Performance Summary:
1>     1010 ms  LinkApplicationSharedLibraries             1 calls
1>     1252 ms  GenerateJavaStubs                          1 calls
1>     1315 ms  CompileNativeAssembly                      1 calls
1>     1443 ms  CallTarget                                 6 calls
1>     1701 ms  ManifestMerger                             1 calls
1>     1852 ms  ResolveLibraryProjectImports               1 calls
1>     1982 ms  LinkAssembliesNoShrink                     1 calls
1>     2111 ms  Csc                                        1 calls
1>     3744 ms  ProcessAssemblies                          1 calls
1>     4591 ms  Javac                                      1 calls
1>    17043 ms  D8                                         1 calls
```

**Comment by elparasite** [comment] 2024-04-05 07:45
Just an idea reading the thread, maybe an online verification of some CRL or OCSP during the signing process can cause this issue.
If the OCSP server doesn't respond or is very slow it may provoke this kind of issue.

**Comment by swlasse** [comment] 2024-04-20 17:43
FWIW, following the proposed workaround on the linked [ReSharper issue](https://youtrack.jetbrains.com/issue/RSRP-495224) worked for me:

> WORKAROUND: disable ReSharper | Options | Environment | General | Read solution model directly.. option.

Now, the solution no longer rebuilds on every build which naturally speeds up development a lot.

**Comment by paulohloblin** [comment] 2024-05-04 14:11
I think in case of Visual Studio it's related to NuGet package restore. This significantly slows down my builds, so I went **Tools > Options > NuGet Package Manager > General** and disabled **Automatically check for missing packages during build**

**Comment by mattleibow** [comment] 2024-05-13 18:24
Are things working faster now? Is this issue safe to close?

**Closed** 2024-05-24 00:09 UTC
Labels: t/bug, platform/android 🤖, area-tooling, s/needs-info, s/no-recent-activity, migration-compatibility
