### ISSUE TITLE
[Windows] - Publish on store failed with Payload contains two or more files with the same destination path 'LibMobile.pdb'

### ISSUE THREAD

**Issue by MattePozzy** [dotnet/maui#19367] opened 2023-12-12 15:38 UTC
### Description

Hi,
I have a MAUI app that inclue a C# Class Library named LibMobile.
When I try to follow the windows guide to publish the app in the Windows Store, this issue occurs:

```
1>Payload contains two or more files with the same destination path 'LibMobile.pdb'. Source files: 
1>C:\Users\pozzy\Documents\Progetti\LibMobile\bin\Release\net8.0-windows10.0.19041.0\LibMobile.pdb
1>C:\Users\pozzy\Documents\Progetti\LibMobile\bin\Release\net8.0-windows10.0.19041.0\win10-x64\LibMobile.pdb
```

How can I solve this?

### Steps to Reproduce

**You must have an app reserved name on Microsoft Partner Center**
In the repo open MauiApp2/MauiApp2.sln.
Edit the node Identity in the file Package.appxmanifest with your data
```
	<Identity
		Name="from partner center"
		Publisher="from partner center"
		Version="1.1.4.0" />
```

Build LibMobile in release mode.
Right click on MauiApp2 project.
Click Publish
Select Microsoft store under a new name app then click next
Select the app name from the list then click next
Input version and use a publish profile like this one:
![image](https://github.com/dotnet/maui/assets/7420345/6872cffc-2a0e-4707-aee5-570556a9c8b4)
then click Create.
After a few moment, in the output window you'll see this message and the publish will fail
```
1>Payload contains two or more files with the same destination path 'LibMobile.pdb'. Source files: 
1>C:\Users\pozzy\Documents\Progetti\LibMobile2\bin\Release\net8.0-windows10.0.19041.0\LibMobile.pdb
1>C:\Users\pozzy\Documents\Progetti\LibMobile2\bin\Release\net8.0-windows10.0.19041.0\win10-x64\LibMobile.pdb
========== Publish: 0 succeeded, 1 failed, 0 skipped ==========
========== Publish completed at 09:53 and took 15,268 seconds ==========
========== Package: 0 succeeded, 1 failed ===========
```

### Link to public reproduction project repository

[Link](https://github.com/MattePozzy/MauiLibWinStoreIssue)

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Did you find any workaround?

No

**Comment by MattePozzy** [comment] 2023-12-13 08:56
Added repository and steps to reproduce the issue.

**Comment by mattleibow** [comment] 2023-12-13 19:16
Duplicate of https://github.com/dotnet/maui/issues/17187

**Closed by mattleibow** 2023-12-13 19:16 UTC
Labels: t/bug, platform/windows 🪟, area/publishing 🏁
