### ISSUE TITLE
Entry ReturnType="Next" doesn't work with SfTextInputLayout

### ISSUE THREAD

**Issue by Riccardo11** [dotnet/maui#26383] opened 2024-12-05 09:14 UTC
### Description

Setting the property `ReturnType` to `Next` on an `Entry` seems not to work correctly if the Entries are placed inside the `SfTextInputLayout` component from `Syncfusion.Maui.Toolkit`.

The behavior you can notice is that when you press the Next button, the focus on the next entry is correctly set only if the following entry has some valid text inside.
Otherwise, the focus doesn't change or it changes not correctly, going on the first Entry which has some text inside.

I can reproduce the issue on iOS, not sure if the same problem verifies on Android, because of this other issue: https://github.com/dotnet/maui/issues/23086, so please **consider checking this issue also in other platforms**, regardless of the repro name or OS specified below.

I attach a video for clarity.

https://github.com/user-attachments/assets/63cba915-229a-4ccc-b41a-fd7e73b4aac5

### Steps to Reproduce

1. Create a .NET MAUI app configuring the Syncfusion MAUI Toolkit.
2. Draw some Entries contained inside a `SfTextInputLayout` with the `ReturnType` set to `Next`.
3. Observe the behavior shown in the video.

### Link to public reproduction project repository

https://github.com/Riccardo11/MauiIssues/tree/main/EntryNextiOS

### Version with bug

9.0.12 SR1.2

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 18.1, couldn't test Android because of another issue

### Relevant log output

```shell

```

**Comment by jfversluis** [comment] 2024-12-05 09:35
I don't see much value in report this again. I see there is an issue on the Syncfusion repository and it might indeed be a duplicate of what we already have.

**Comment by jfversluis** [comment] 2024-12-05 09:35
Duplicate of #23086

**Closed by jfversluis** 2024-12-05 09:35 UTC
Labels: t/bug

**Comment by riccardominato** [comment] 2024-12-05 10:06
@jfversluis Thank you for your answer.

If you look at the two issues (this one and the one your marked as duplicate) you'll see that they are completely different.

The only reason why i quoted https://github.com/dotnet/maui/issues/23086 is that because of it, I can't test if _this_ issue verifies on Android, too.

I am the one who opened the issue on Syncfusion (unfortunately I was logged on a different account, so the authors of the two issues seem to be different, but it's always me).
I simply didn't know whether this is a MAUI or Syncfusion problem, so I let both know about it.
