### ISSUE TITLE
Sometimes it's a blank space in Maui Blazor APP when open the program

### ISSUE THREAD

**Issue by milklike** [dotnet/maui#15522] opened 2023-06-08 08:38 UTC
### Description

Sometimes it's a blank space in Maui Blazor APP when open the program. 
Not always happended.
I can press F12 to open DevTool, but it just have:

```html
<html>
    <head></head>
    <body></body>
</html>
```

### Steps to Reproduce

open your maui blazor app,you would have a 5% chance of encountering this problem.

### Link to public reproduction project repository

dotnet / maui

### Version with bug

7.0.49

### Last version that worked well

6.0

### Affected platforms

Windows

### Affected platform versions

win10 all win11

**Comment by samhouts** [comment] 2023-08-08 17:58
Duplicate of #15533

**Closed by samhouts** 2023-08-08 17:58 UTC
Labels: t/bug, area/blazor 🕸️
