### ISSUE TITLE
iOS/Windows touch inputs sent to controls behind

### ISSUE THREAD

**Issue by Saurbaum** [dotnet/maui#24608] opened 2024-09-05 13:52 UTC
### Description

Similar to this https://github.com/dotnet/maui/issues/22938 and https://github.com/dotnet/maui/issues/19105

When you open a modal page with an Entry on it touching the page causes focus to shift to the underlying object.

### Steps to Reproduce

Steps to Reproduce

    On Windows and iOS
    In the standard sample app
    Create a ModalPage with and Entry control.
    Execute Navigation.PushModalAsync(new ModalPage())

Click or touch in the entry control. On Android this will bring up the keyboard. On iOS and Windows it will switch focus to the page behind. In windows you can then use the tab key to switch focus eventually back to the modal control and provided you do not use the mouse you can at least continue. on iOS you are stuck.

### Version with bug

8.0.82 SR8.2

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Windows

### Affected platform versions

All versions of iOA and Windows

### Did you find any workaround?

on iOS there is nothing I've found that works it is unusable

**Comment by mattleibow** [comment] 2024-09-10 19:32
Duplicate of https://github.com/dotnet/maui/issues/22938

**Closed by mattleibow** 2024-09-10 19:32 UTC
Labels: t/bug, platform/windows 🪟, platform/iOS 🍎

**Comment by PureWeen** [comment] 2024-09-10 19:36
@Saurbaum can you attach a repro and possibly a video to #22938 ?

**Comment by Saurbaum** [comment] 2024-09-11 08:14
Take a look at #19105 that one show's it perfectly
