### ISSUE TITLE
CollectionView does not update column when changing ItemsLayout span

### ISSUE THREAD

**Issue by amosekr** [dotnet/maui#23266] opened 2024-06-26 09:01 UTC
### Description

I have a CollectionView with several items and I want to make a 2 or more columns layout on wide screens and a 1 column layout on tall screens.

I tried setting a GridItemsLayout and changing the Span in sizechanged event and set the same in button click event, but that did not work and then I tried changing the entire ItemsLayout, but still no updates in the app.

Restarting the app works, so this is just the result of changing at runtime.

### Steps to Reproduce

Add a CollectionView with items, and then say write this code to toggle the layout on page size changes:

private void OnSizeChanged(object? sender, EventArgs e) =>
    collectionView.ItemsLayout = Width > 600
        ? new GridItemsLayout(2, ItemsLayoutOrientation.Vertical)
        : new LinearItemsLayout(ItemsLayoutOrientation.Vertical);

### Version with bug

8.0.3 GA

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

All

**Comment by MitchBomcanhao** [comment] 2024-06-26 09:45
there is a bug where the layout of grid items is broken on windows, ie you ask for 3 columns, and it renders items in the first 2 columns, leaving the last one always empty. this could be related?

**Comment by amosekr** [comment] 2024-06-26 09:49
Yes this is also a bug, i have fixed by setting heightrequest and widthrequest in sizechanged event. The problem i am facing is, ie, initially i am asking 3 columns it is working, then if i maximize it should increase the column and if i minimize it should decrease the column. I have modified the span values based on the screen size, but it was not updating in the collectionview runtime.

**Comment by jfversluis** [comment] 2024-06-26 09:53
Duplicate of #14228

**Closed by jfversluis** 2024-06-26 09:53 UTC
Labels: t/bug
