### ISSUE TITLE
StackLayout.IsEnabled = FALSE does not Disable the Child Components within it

### ISSUE THREAD

**Issue by cbaer-extron** [dotnet/maui#6008] opened 2022-04-12 19:22 UTC
### Description

In Maui App, if a StackLayout is disabled with IsEnabled = FALSE, all the child controls within it, should be disabled also.  But Maui ignores StackLayout.IsEnabaled = FALSE, and all child controls are still enabled.  In comparison, Xamarin.Forms will disable all child controls.  (See both attached videos)
In Maui:

https://user-images.githubusercontent.com/101732760/163034237-700fa184-8855-440c-9ac1-c114622e8ecb.mp4

In Xamarin.Forms:

https://user-images.githubusercontent.com/101732760/163034272-207cc8df-ea89-49c0-afee-7dbbb7ef1bac.mp4

Source Code:
XAML:
https://github.com/cbradbaer/BugReports/blob/main/StackLayoutIsEnabled/DisableTestPage.xaml

Code Behind:
https://github.com/cbradbaer/BugReports/blob/main/StackLayoutIsEnabled/DisableTestPage.xaml.cs

### Steps to Reproduce

1.  Create new Maui App
2.  Add a StackLayout and set IsEnabled = FALSE in the Xaml
3.  Add Entry View and Button to the StackLayout
4.  Run the program
5.  Note that the Entry can still get focus and text can be entered
6.  Note that the Button can still be pressed

### Version with bug

Preview 14 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 11

### Did you find any workaround?

I used Triggers to individually set IsEnabled to false on all the child controls.  Ugly, but it worked.

**Comment by XamlTest** [comment] 2022-04-13 03:23
Verified this issue with Visual Studio Enterprise 17.3.0 Preview 1.0 [32409.46.main]. Repro on Android. Sample Project: [MauiApp13.zip](https://github.com/dotnet/maui/files/8477951/MauiApp13.zip)

**Comment by mfe-** [comment] 2022-04-19 16:17
Occurs also on the Windows platform for me.

**Comment by hartez** [comment] 2022-04-19 16:20
Duplicate of #5287

**Closed by hartez** 2022-04-19 16:20 UTC
Labels: t/bug, area/layout 🔲, s/verified, s/triaged
