### ISSUE TITLE
[Bug] Hot reload on Blazor: StateHasChanged may not being executed 

### ISSUE THREAD

**Issue by 3DSX** [dotnet/maui#2503] opened 2021-09-15 21:13 UTC
The title says it all. The hot reload is applied, and the component is generated and loaded again, but you can't see those changes until you instance that component again from Blazor.
.NET 6 RC1

Execution of the **StateHasChanged** method after the hot-reload tasks may solve that issue, just as we can do with Wasm or Server.

**Comment by 3DSX** [comment] 2021-09-18 16:21
This issue is related with this one opened a day later: https://github.com/dotnet/maui/issues/2527

**Comment by mkArtakMSFT** [comment] 2021-12-13 18:43
Closing this as a dupe of https://github.com/dotnet/maui/issues/2527

**Closed** 2021-12-13 18:43 UTC
Labels: t/bug, area/blazor 🕸️
