### ISSUE TITLE
clang++ exited with code 1

### ISSUE THREAD

**Issue by jitendrajadav** [dotnet/maui#20282] opened 2024-02-01 08:09 UTC
### Description

Having .net 8 MAUI project while publishing archive build for Android failing here please check error logs here

/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/17.2.8004/targets/Xamarin.Shared.Sdk.targets(1559,3): error : clang++ exited with code 1: [/Users/2000109296/Projects/vixxolink-mobile-maui/Vixxo.Mobile/Vixxo.Mobile.csproj::TargetFramework=net8.0-ios]
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/17.2.8004/targets/Xamarin.Shared.Sdk.targets(1559,3): error : ld: in /Users/2000109296/Projects/vixxolink-mobile-maui/Vixxo.Mobile/obj/Debug/net8.0-ios/iossimulator-arm64/linker-cache/AppCenterDistribute.a(MSACDistributionGroup.o), building for iOS Simulator, but linking in object file built for iOS, file '/Users/2000109296/Projects/vixxolink-mobile-maui/Vixxo.Mobile/obj/Debug/net8.0-ios/iossimulator-arm64/linker-cache/AppCenterDistribute.a' [/Users/2000109296/Projects/vixxolink-mobile-maui/Vixxo.Mobile/Vixxo.Mobile.csproj::TargetFramework=net8.0-ios]
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/17.2.8004/targets/Xamarin.Shared.Sdk.targets(1559,3): error : clang: error: linker command failed with exit code 1 (use -v to see invocation) [/Users/2000109296/Projects/vixxolink-mobile-maui/Vixxo.Mobile/Vixxo.Mobile.csproj::TargetFramework=net8.0-ios]

I have added code as per some community post
` <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net8.0-ios|AnyCPU'">
		  <ForceSimulatorX64ArchitectureInIDE>true</ForceSimulatorX64ArchitectureInIDE>
	  </PropertyGroup>`
	  
	  
Still I am not able to Release build in android only

I have MACBook Pro M3 18 RAM
which ARM64 base

could you please help me to figure out this issue

### Steps to Reproduce

1. create .net MAUI project
2. Add AppCenter Nuget Packages perticular AppCenterCrashes
3. Try to publish build for android in Release mode 
4. you well get error here

### Version with bug

8.0.6

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.6

### Affected platforms

Android

### Affected platform versions

Android 13

### Did you find any workaround?

Yes 
```
 <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net8.0-ios|AnyCPU'">
		  <ForceSimulatorX64ArchitectureInIDE>true</ForceSimulatorX64ArchitectureInIDE>
	  </PropertyGroup>
``` 
	  but this is not working

### Relevant log output

```shell
roject file, or add a 'CFBundleIdentifier' entry in the project's Info.plist file. [/Users/2000109296/Projects/vixxolink-mobile-maui/Vixxo.Mobile.Tests/Vixxo.Mobile.Tests.csproj::TargetFramework=net8.0-ios]
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/17.2.8004/targets/Xamarin.Shared.Sdk.targets(1559,3): error : clang++ exited with code 1: [/Users/2000109296/Projects/vixxolink-mobile-maui/Vixxo.Mobile/Vixxo.Mobile.csproj::TargetFramework=net8.0-ios]
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/17.2.8004/targets/Xamarin.Shared.Sdk.targets(1559,3): error : ld: in /Users/2000109296/Projects/vixxolink-mobile-maui/Vixxo.Mobile/obj/Debug/net8.0-ios/iossimulator-arm64/linker-cache/AppCenterDistribute.a(MSACDistributionGroup.o), building for iOS Simulator, but linking in object file built for iOS, file '/Users/2000109296/Projects/vixxolink-mobile-maui/Vixxo.Mobile/obj/Debug/net8.0-ios/iossimulator-arm64/linker-cache/AppCenterDistribute.a' [/Users/2000109296/Projects/vixxolink-mobile-maui/Vixxo.Mobile/Vixxo.Mobile.csproj::TargetFramework=net8.0-ios]
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/17.2.8004/targets/Xamarin.Shared.Sdk.targets(1559,3): error : clang: error: linker command failed with exit code 1 (use -v to see invocation) [/Users/2000109296/Projects/vixxolink-mobile-maui/Vixxo.Mobile/Vixxo.Mobile.csproj::TargetFramework=net8.0-ios]
```

**Comment by bcaceiro** [comment] 2024-02-01 08:41
add a 'CFBundleIdentifier' entry in the project's Info.plist file, despite building the android solution, you have in your output an error regarding iOS

**Comment by rmarinho** [comment] 2024-02-02 16:00
Hi @jitendrajadav are you using the command line or some IDE on macOS ?

**Comment by KevinJalais** [comment] 2024-02-06 14:50
Hi,

I have the exact same issue here.
I am on MacBookPro M2 Max 64GB RAM, run Windows 11 on Parallels Desktop Business Edition and use VS2022 on the Windows VM.

I am migrating a Xamarin.Forms application to MAUI but, since then, it's impossible to build and deploy either on iOS Simulator or on physical iPhone device.

I have a 'CFBundleIdentifier' entry in the project's Info.plist and tried multiple things found over the internet, unfortunately nothing worked at the moment.

Please, help.

**Comment by tompi** [comment] 2024-02-07 07:47
Same problem here, mac m1, fails when building for simulator:
```log
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/17.2.8004/targets/Xamarin.Shared.Sdk.targets(1559,3): error : ld: in /Users/tompi/src/sr-tcprlink/App/TCPRLink/obj/Debug/net8.0-ios/iossimulator-arm64/linker-cache/AppCenterAnalytics.a(MSACAnalytics.o), building for iOS Simulator, but linking in object file built for iOS, file '/Users/tompi/src/sr-tcprlink/App/TCPRLink/obj/Debug/net8.0-ios/iossimulator-arm64/linker-cache/AppCenterAnalytics.a' [/Users/tompi/src/sr-tcprlink/App/TCPRLink/TCPRLink.csproj::TargetFramework=net8.0-ios]
```

This works fine:
```sh 
dotnet build -f net8.0-ios -p:RuntimeIdentifier=ios-arm64
```

This seems to be an issue with appcenter not supporting ios simulator?

**Comment by KevinJalais** [comment] 2024-02-07 09:37
Hi @tompi, many thanks for your solution.
Unfortunately, it does not work on my side.

**Comment by KevinJalais** [comment] 2024-02-07 10:10
@tompi, yes I tested with the command line and it works.
But it does not resolve my problem, which is that I am in a debug phase and I need to deploy the application either on simulator or physical device through Visual Studio to get all the support like breakpoints, live crashes, etc.
Moreover, the hot reload is a must-have now, especially to not waste too much time on interfaces details.

I added `<RuntimeIdentifier>ios-arm64</RuntimeIdentifier>` inside the following property group
`<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net8.0-ios|AnyCPU'">
	<ApplicationVersion>1</ApplicationVersion>
	<MtouchLink>None</MtouchLink>
	<MtouchFloat32>False</MtouchFloat32>
	<CodesignEntitlements>Platforms\iOS\Entitlements.development.plist</CodesignEntitlements>
	<OptimizePNGs>False</OptimizePNGs>
	<RuntimeIdentifier>ios-arm64</RuntimeIdentifier>
</PropertyGroup>`

But it still does not build or deploy, even for a physical device.

**Comment by jitendrajadav** [comment] 2024-02-07 10:12
> add a 'CFBundleIdentifier' entry in the project's Info.plist file, despite building the android solution, you have in your output an error regarding iOS

Yes I have already adedd CFBundleIdentifier still get error

**Comment by jitendrajadav** [comment] 2024-02-07 10:13
> add a 'CFBundleIdentifier' entry in the project's Info.plist file, despite building the android solution, you have in your output an error regarding iOS

Yes I have already adedd

**Comment by KevinJalais** [comment] 2024-02-09 14:34
Thank you @kamdut, you made my day !

Some days ago, I found a [StackOverflow](https://stackoverflow.com/questions/77901341/net8-maui-ios-error-with-appcenter-crashes) mentionning what you suggest (adding `<ForceSimulatorX64ArchitectureInIDE>true</ForceSimulatorX64ArchitectureInIDE>`).
And it did not work at all.

But at the time, I did not have the following `<RuntimeIdentifier>ios-arm64</RuntimeIdentifier>` suggested by @tompi.

So, following your comment, I added the line again in addition to the runtime identifier.
Then I got the following error:

> NETSDK1047	Assets file '{my _project_path}\obj\project.assets.json' doesn't have a target for 'net8.0-ios/iossimulator-x64'. Ensure that restore has run and that you have included 'net8.0-ios' in the TargetFrameworks for your project. You may also need to include 'iossimulator-x64' in your project's RuntimeIdentifiers.

Then I replaced `<RuntimeIdentifier>ios-arm64</RuntimeIdentifier>` by `<RuntimeIdentifier>iossimulator-x64</RuntimeIdentifier>` and everything started to work everywhere (simulator AND real device).

Here is my full debug conf in the .csproj
`<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net8.0-ios|AnyCPU'">
    <ApplicationVersion>1</ApplicationVersion>
    <MtouchLink>None</MtouchLink>
    <MtouchFloat32>False</MtouchFloat32>
    <CodesignEntitlements>Platforms\iOS\Entitlements.development.plist</CodesignEntitlements>
    <OptimizePNGs>False</OptimizePNGs>
   <RuntimeIdentifier>iossimulator-x64</RuntimeIdentifier>
   <ForceSimulatorX64ArchitectureInIDE>true</ForceSimulatorX64ArchitectureInIDE>
</PropertyGroup>`

**Comment by jitendrajadav** [comment] 2024-02-22 08:19
> I had the same issue, in my case adding `<ForceSimulatorX64ArchitectureInIDE>true</ForceSimulatorX64ArchitectureInIDE>` helped with running the app on the iPhone simulator, but the only way to run the Android version was to remove `net8.0-ios` from the target frameworks in the .csproj file

Thank you this really help me to create build!

**Comment by kevinxufei** [comment] 2024-03-05 08:54
This issue has been verified and reproduced in Visual Studio for Mac 17.6.9 build 415 (maui version: 8.0.7).

**Comment by taublast** [comment] 2024-03-31 12:37
> Thank you @kamdut, you made my day !
> 
> Some days ago, I found a [StackOverflow](https://stackoverflow.com/questions/77901341/net8-maui-ios-error-with-appcenter-crashes) mentionning what you suggest (adding `<ForceSimulatorX64ArchitectureInIDE>true</ForceSimulatorX64ArchitectureInIDE>`). And it did not work at all.
> 
> But at the time, I did not have the following `<RuntimeIdentifier>ios-arm64</RuntimeIdentifier>` suggested by @tompi.
> 
> So, following your comment, I added the line again in addition to the runtime identifier. Then I got the following error:
> 
> > NETSDK1047	Assets file '{my _project_path}\obj\project.assets.json' doesn't have a target for 'net8.0-ios/iossimulator-x64'. Ensure that restore has run and that you have included 'net8.0-ios' in the TargetFrameworks for your project. You may also need to include 'iossimulator-x64' in your project's RuntimeIdentifiers.
> 
> Then I replaced `<RuntimeIdentifier>ios-arm64</RuntimeIdentifier>` by `<RuntimeIdentifier>iossimulator-x64</RuntimeIdentifier>` and everything started to work everywhere (simulator AND real device).
> 
> Here is my full debug conf in the .csproj `<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net8.0-ios|AnyCPU'"> <ApplicationVersion>1</ApplicationVersion> <MtouchLink>None</MtouchLink> <MtouchFloat32>False</MtouchFloat32> <CodesignEntitlements>Platforms\iOS\Entitlements.development.plist</CodesignEntitlements> <OptimizePNGs>False</OptimizePNGs> <RuntimeIdentifier>iossimulator-x64</RuntimeIdentifier> <ForceSimulatorX64ArchitectureInIDE>true</ForceSimulatorX64ArchitectureInIDE> </PropertyGroup>`

A huge thanks you for this! Was never able to build without using command line for iOS on mac m1 until that 

<RuntimeIdentifier>iossimulator-x64</RuntimeIdentifier> <ForceSimulatorX64ArchitectureInIDE>true</ForceSimulatorX64ArchitectureInIDE>

My guess is that deserves to be pinned/blogged somewhere

**Comment by MouratidisA** [comment] 2024-05-27 09:40
@tompi @KevinJalais 
Thank you!! 

I just added:
`<RuntimeIdentifier>iossimulator-x64</RuntimeIdentifier>`
for the iOS Property Group and execute the command:
`dotnet build -f net8.0-ios `

Archive works for both iOS and Android platforms!

**Comment by danieltharris** [comment] 2024-08-16 01:05
Has anybody determined the root cause of this? I've started to get these errors only after I tried debugging a Mac Catalyst version of the app. Reverting my branch will hopefully fix it, but it would be nice to know what is causing it.

I've been working on this project for days and had no issues - Changed nothing significant in my code and didn't touch my config.

**Comment by jfversluis** [comment] 2024-09-21 09:19
I think this has to do with something on the App Center plugin side unfortunately. Since that is being retired as of March I'm not sure if they will be doing much about it. There seems to be a clear workaround in here for the people that need it until then.

Closing this here as there is not much we can do about this on our end.

**Closed by jfversluis** 2024-09-21 09:19 UTC
Labels: t/bug, platform/android 🤖, area-tooling, s/verified, s/triaged, s/needs-attention, partner/macios, potential-regression

**Comment by jvondermarck** [comment] 2024-09-25 07:12
### What solved the issue for me was to setup like this my `csproj` file

```csproj
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>net8.0-android;net8.0-ios</TargetFrameworks>
		<OutputType>Exe</OutputType>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">11.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">21.0</SupportedOSPlatformVersion>
                  ...
	</PropertyGroup>

	<!-- ⚠️ Workaround on mac to be able to run the project on Android and iOS -->
	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net8.0-ios|AnyCPU'">
		<RuntimeIdentifier>iossimulator-x64</RuntimeIdentifier>
		<ForceSimulatorX64ArchitectureInIDE>true</ForceSimulatorX64ArchitectureInIDE>
	</PropertyGroup>

        <ItemGroup Condition="'$(TargetFramework)' == 'net8.0-android'">
		<ProjectReference Include="..\<Android lib>\<Android lib>.csproj" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net8.0-ios'">
	        <ProjectReference Include="..\<iOS lib>\<iOS lib>.csproj" />
	</ItemGroup>

         ...

</Project>
```

-----

> [!NOTE] 
> The weird part is that I got the `clang` Simulator error when I was running my project on Android, while building on iOS worked amazingly, but anyway thanks for the workaround !
