### ISSUE TITLE
The Webview does not display PDF

### ISSUE THREAD

**Issue by HobDev** [dotnet/maui#7399] opened 2022-05-22 07:01 UTC
### Description

I want to open a pdf from a web resource on WebView. But the WebView does not render the pdf. On the other hand the webpages are displayed on WebView without any problem.

### Steps to Reproduce

Run the repro project with source of the WebView as Pdf. The pdf will not render on the Page. Now comment out the Xaml tag where the Source of the WebView is Pdf and  Uncomment the Xaml tag where the Source of the WebView is a WebPage. This time the page will display the content. 
[MauRepro.zip](https://github.com/dotnet/maui/files/8748955/MauRepro.zip)

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Release Candidate 2

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 11

**Comment by kristinx0211** [comment] 2022-05-23 02:26
can be reproduced on window with above project.;

**Comment by jsuarezruiz** [comment] 2022-10-20 09:18
The .NET MAUI WebView control use the native WebView. To view PDFs with the WebView, just like with Xamarin.Forms, you have several options:
- Use  the Google Drive Viewer, PDF.js or similar. Example: `"https://drive.google.com/viewerng/viewer?url={0}"`
- Use HttpClient to download the file, Essentials to save the file and launch another App to open the PDF.

**Comment by GnanaPriyaNamasivayam** [comment] 2022-12-20 08:02
I'm also facing the same issue in .net 7.0 not sure about 6.0.
Noticed one this, if I render WebView without any parent in XAML it works fine.
WebView displays blank only when it has a parent element.
UI Structure:
Success case:
MAUI toolkit popup -> WebView
Failure case:
MAUI toolkit popup -> StackLayout/Grid/ any parent-> WebView
 It will be helpful if we got the issue fixed.

**Comment by hartez** [comment] 2023-01-27 18:02
> The .NET MAUI WebView control use the native WebView. To view PDFs with the WebView, just like with Xamarin.Forms, you have several options:
> 
> * Use  the Google Drive Viewer, PDF.js or similar. Example: `"https://drive.google.com/viewerng/viewer?url={0}"`
> * Use HttpClient to download the file, Essentials to save the file and launch another App to open the PDF.

@jsuarezruiz or @jfversluis Do we have any videos/posts/write-ups on how to do this with PDF.js and/or Google Drive?

**Comment by hartez** [comment] 2023-01-27 20:02
Apparently there's this, but it would need to be updated for .NET MAUI: https://blog.verslu.is/xamarin/xamarin-forms-xamarin/showing-pdf-files-xamarin-forms/

**Comment by HobDev** [comment] 2023-02-15 13:11
The pdf is displaying on webview from the remote source on iOS but not on Android.

**Comment by ravacho** [comment] 2023-02-15 19:05
Same problem here

**Comment by moljac** [comment] 2023-02-23 18:51
> Will it work on iOS?

It works partially. My investigation/research notes coming in few minutes.

> The pdf is displaying on webview from the remote source on iOS but not on Android.

iOS is misleading it does render only 1 page (1st page).

**Comment by moljac** [comment] 2023-02-24 16:21
To MAUI team for labeling:

This is not a bug in MAUI. Underlying platforms do not support PDF or other proprietary [complex] format rendering (Excel, etc).

**Comment by moljac** [comment] 2023-02-24 16:26
closing this issue

This feature will not be implemented and maintained as part of MAUI (it was not part of Xamarin.Forms either), so I will try to implement several workarounds/[re]solutions mostly because I am selfish and want to learn.

NOTE: I will need some time to get deeper into MAUI (Handlers vs Custom Renderers and Migration from Xamarin.Forms)

You can track progress here (my samples-playgrounds repo for MAUI):

https://github.com/Samples-Playgrounds/Samples.MAUI/tree/main/samples/issues-repro-samples/7399

**Closed by moljac** 2023-02-24 16:26 UTC
Labels: t/bug, platform/android 🤖, p/1, partner/webview2, area/controls 🎮, s/verified, control-webview, s/needs-attention
