### ISSUE TITLE
[Bug] SVG file with elements using "fill=rgb()" for the app icon will cause APT2259 error at build

### ISSUE THREAD

**Issue by anotherlab** [dotnet/maui#3194] opened 2021-10-29 21:00 UTC
### Description
If the .svg file used for the app icon has an element using the fill attribute, the build will fail if the fill is defined using the rgb() function. Using rgb(), rgba(), hsl(), and hsla() are valid for the fill attribute.

If a hex string literal is used for the fill attribute, the build will succeed and an app icon will be rendered.

This only occurs for the app icon.  If the same image is used elsewhere in the application, it renders correctly.

This was tested on Android, no other platforms were tested.
### Steps to Reproduce

1. Create new app with "dotnet new maui -n YourAppName"
2. Add a SVG file that uses rgb() for the fill attribute of at least one element in the image.
3. Make that SVG file the foreground file for the app icon

### Expected Behavior
App rendered with the correct icon

### Actual Behavior
Build fails with APT2259 error for each occurrence of fill=rgb(), followed by a final APT2061 error

### Basic Information

- Version with issue: Visual Studio 2022 Preview 7
- Last known good version: None
- IDE: Visual Studio 2022 Preview 7
- Platform Target Frameworks: 
  - Android: 21.0

### Reproduction Link

With the Maui AppIcon defined in the .csprofile with

```xml
<MauiImage Include="Resources\appicon.svg" ForegroundFile="Resources\Images\usesrgb.svg" IsAppIcon="true" Color="#512BD4" />
```
Use the following for the usesrgb.svg

```xml
<?xml version="1.0" encoding="UTF-8"?>
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="240" height="240"  xml:space="preserve" id="hasCircles">
    <circle id="c1" stroke="none" fill="rgb(0, 0, 0)" cx="120" cy="120" r="100" />
</svg>
```

A full example containing working and non-working versions of the SVG file can be found at https://github.com/anotherlab/SvgCircle

### Workaround

Replace any occurrence of fill=rgb(x,y,z) with fill=#XXYYZZ.  For example, a working version of the usesrgb.svg file would look like
```xml
<?xml version="1.0" encoding="UTF-8"?>
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="240" height="240"  xml:space="preserve" id="hasCircles">
    <circle id="c1" stroke="none" fill="#000000" cx="120" cy="120" r="100" />
</svg>
```

**Comment by vannomad** [comment] 2021-12-09 13:09
This might be caused by the compilation (resizetizer?) to android vector not using indifferent culture

I had to change my Decimal from "," to "." in windows settings to get my SVGs to compile

**Comment by shimingsg** [comment] 2022-03-04 06:45
verified not repro with vs 17.2.0 Preview 2.0 [32303.288.main], build successfully without any error.

**Comment by mattleibow** [comment] 2022-03-22 20:51
This should be fixed in Preview 14. Please open another issue if there are still problems.

**Closed by mattleibow** 2022-03-22 20:51 UTC
Labels: t/bug, area/single project ☝️, fatal, s/verified
