### ISSUE TITLE
[MacCatalyst] ScrollView scroll bar is misplaced after window resize

### ISSUE THREAD

**Issue by ivan-todorov-progress** [dotnet/maui#9349] opened 2022-08-11 14:07 UTC
### Description

This is a pretty annoying visual glitch that occurs only on MacCatalyst. After resizing the window the scroll bar of the ScrollView is misplaced. The following screenshot demonstrates the problem:

![Screenshot](https://user-images.githubusercontent.com/98032058/184152014-02ef4b96-c5ab-4d47-befb-51e08427dea7.png)

### Steps to Reproduce

1. Run the attached sample application on MacCatalyst
2. Resize the window so that not all controls are visible
3. Scroll the content vertically to see the scroll bar
4. Resize the window - the scroll bar is misplaced
5. Scroll vertically again - the scroll bar is now positioned correctly

[TestApp.zip](https://github.com/dotnet/maui/files/9309302/TestApp.zip)

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

N/A

**Comment by jfversluis** [comment] 2022-08-11 18:11
Duplicate of #8370

**Comment by PureWeen** [comment] 2022-08-11 18:12
Reopening this one so we can mark it with partner

And let this one be the duplicate https://github.com/dotnet/maui/issues/9349

**Comment by hartez** [comment] 2023-02-01 17:02
Just tested this against the latest stable and it's working correctly.

**Closed by hartez** 2023-02-01 17:02 UTC
Labels: t/bug, area/layout 🔲, partner, layout-scrollview
