### ISSUE TITLE
Shell Flyout Occasionally Missing Items

### ISSUE THREAD

**Issue by david-maw** [dotnet/maui#9396] opened 2022-08-13 05:52 UTC
### Description

Under some circumstances a Shell Flyout does not initially display all the ShellContent items in its list.

### Steps to Reproduce

1. Unzip the project from
[MauiShell-shortflyout.zip](https://github.com/dotnet/maui/files/9330889/MauiShell-shortflyout.zip)
2. Build and run it on Windows, after a few seconds you'll see this:
![mauishell-shortflyout-1](https://user-images.githubusercontent.com/12423046/184470054-b32d39e9-1553-4ab9-b511-19726bdf8c1d.jpg)
3. Click on the hamburger menu to pull out the flyout and you'll see this:
![mauishell-shortflyout-2](https://user-images.githubusercontent.com/12423046/184470067-fda86bb6-cd82-4f80-8f43-8f9899605105.jpg)
4. Click again to close the flyout and again to reopen it and you'll see the correct display:
![mauishell-shortflyout-3](https://user-images.githubusercontent.com/12423046/184470091-cb746185-8f64-43d2-bcfb-ea4948116c49.jpg)
From then on it will work fine until the Shell is recreated.

The key to reproducing the problem seems to be the initialization/splash page startup mechanism that's used here. 

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Windows 10

### Did you find any workaround?

It's a transient problem that goes away the second time the flyout is used

**Comment by rsbepvb** [comment] 2022-08-13 22:13
We have encountered the same issue only on Windows (not iOS, Mac Catalyst or Android)

**Comment by AndreasReitberger** [comment] 2022-08-15 04:41
Facing the same issue on windows.
Mostly right after the start if the flyout bar is opened the first time.
After reopening, it works.

Also the Header is not shown in the windows shell flyout bar.

**Comment by PureWeen** [comment] 2022-11-02 19:39
Duplicate of #https://github.com/dotnet/maui/issues/8834

**Closed by PureWeen** 2022-11-02 19:39 UTC
Labels: t/bug, area/shell 🐢
