### ISSUE TITLE
.Net Maui UI issues on release apk (Text disappear on buttons)

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#13919] opened 2023-03-14 16:31 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Net-Maui-UI-issues-on-release-apk-Text/10294091)._

---
my .net maui app works fine in debug mode but when i release it as apk file the text on buttons disappear during working of app,like if im using app first everything goes fine but after some time text on buttons will disappear like shown in image 

![image](https://user-images.githubusercontent.com/1096616/225089983-e75ef984-63a0-4707-9ee0-5b2d0b5e5107.png)

**Comment by mattleibow** [comment] 2023-03-14 17:36
@anmol776 is this your issue?

Can you reproduce this with a blank app? Are you able to attach a repro case so we can have a look?

**Comment by mattleibow** [comment] 2023-03-14 17:37
This _may_ be a duplicate of #11662 and fixed in #13836

**Closed** 2023-03-23 01:01 UTC
Labels: t/bug, platform/android 🤖, area/controls 🎮, area/publishing 🏁, control-button, s/no-recent-activity, s/needs-repro
