### ISSUE TITLE
Android build compiles fine:Xaml Parser fails to understand the expression when placed wrongly and compiles in release 

### ISSUE THREAD

**Issue by liveinvarun** [dotnet/maui#10982] opened 2022-10-28 21:38 UTC
### Description

The sample contains a parser mistake that runs the app in release mode for android. The binding fails expression was typed mistakenly and the binding expression is shown in UI rather than the stopping the compliation with error. The solution compiles in Release mode. I have seen this working in android. 

The sample demostrates this with the help of collection but not sure this happens in other scenarios also.

### Steps to Reproduce

 <HorizontalStackLayout Spacing="25"
                                     Padding="30,0"
                                     VerticalOptions="Center">
                    <Label Text="{Binding Name}"
                            SemanticProperties.HeadingLevel="Level1"
                            FontSize="32"
                            HorizontalOptions="Center" />

                    <Label Text="{Binding Location}">  
                          Style="{StaticResource locationStyle}" >
                        </Label>

                </HorizontalStackLayout>

This should have been an error but expressions runs in a release build and does create style/binding expression as text label.

### Link to public reproduction project repository

https://github.com/liveinvarun/MauiRepo

### Version with bug

7.0 Release Candidate 2

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11 and up ios also

### Did you find any workaround?

No 

### Relevant log output

```shell
The issue is noticed in android but not sure this may also fail in ios.
```
<img width="433" alt="Screenshot 2022-10-28 at 23 39 39" src="https://user-images.githubusercontent.com/8180770/198737460-61140693-fc42-4dc7-ba2d-9e2589bd2741.png">

**Comment by mattleibow** [comment] 2022-12-08 13:09
Closing this as not a bug because that is valid. In this case, there is a string that just happens to be similar to XAML code.

Maybe the IDE should be smarter and detect something and pop up a paperclip that says "You seem to be doing XAML here, do you mean to have this in the element brackets?" :)

**Closed by mattleibow** 2022-12-08 13:09 UTC
Labels: t/bug, area/tooling ⚙️
