### ISSUE TITLE
[Android] CollectionView ScrollTo methods not working

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#4110] opened 2022-01-13 09:02 UTC
### Description

CollectionView ScrollTo methods not working. Could be related with https://github.com/dotnet/maui/issues/4107

### Steps to Reproduce

1. Download [CollectionViewDemos.zip](https://github.com/dotnet/maui/files/7861241/CollectionViewDemos.zip)
2. Launch the App and navigate to the sample "Scroll by index".

### Version with bug

Preview 11

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

**Comment by shimingsg** [comment] 2022-02-21 08:15
Verified repro with Android 11 and the above project.

**Comment by rmarinho** [comment] 2022-03-23 12:30
duplicate of #2891

**Closed by rmarinho** 2022-03-23 12:30 UTC
Labels: t/bug, platform/android 🤖, area/collectionview 📃, s/verified
