### ISSUE TITLE
Unable to set BoxViews  BackgroundColor in XAML

### ISSUE THREAD

**Issue by ZeProgFactory** [dotnet/maui#8503] opened 2022-07-03 12:08 UTC
### Description

Unable to set BoxViews  BackgroundColor neither in XAML nor in code behind.

### Steps to Reproduce

The following XAML
```
         <BoxView 
               HeightRequest="24" WidthRequest="24" 
               BackgroundColor="Yellow" />
```
gives a black square.

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows, I was *not* able test on other platforms

### Affected platform versions

Android API28

**Comment by jsuarezruiz** [comment] 2022-07-04 10:21
Can reproduce the issue.

[Issue8503.zip](https://github.com/dotnet/maui/files/9038561/Issue8503.zip)

![image](https://user-images.githubusercontent.com/6755973/177135173-e31005b7-38b7-4e55-b7db-9e28c55855fb.png)

**Comment by HausBJB** [comment] 2022-07-04 10:23
https://github.com/dotnet/maui/issues/6592#issue-1218388037

**Comment by jsuarezruiz** [comment] 2022-07-04 10:46
Cannot reproduce the issue on current .net6-0 branch. This should be fixed in the upcoming Service Release.

![image](https://user-images.githubusercontent.com/6755973/177139352-b6dab233-f053-43ce-b180-f070662faeec.png)

**Comment by jsuarezruiz** [comment] 2022-07-04 10:47
I'm going to close the issue, although I'll do a revision when we release SR2. Let me know if you find any details and we can open it again.

**Closed by jsuarezruiz** 2022-07-04 10:47 UTC
Labels: t/bug, platform/windows 🪟, platform/android 🤖, area/controls 🎮, s/verified, s/triaged
