### ISSUE TITLE
Black splash screen on iOS device and simulator

### ISSUE THREAD

**Issue by existcodev** [dotnet/maui#16945] opened 2023-08-23 02:29 UTC
### Description

Debug app on device or simulator and the splash screen is blacked out on app startup. The app displays as expected once the splash screen has disappeared. 

Splash screen displays as expected on Android.

### Steps to Reproduce

1. Debug app on local device (iOS 16.6).
2. App starts up and displays a black splash screen
3. App displays as expected

1. Debug app on simulator (iOS16.4)
2. App starts up and displays a black splash screen
3. App displays as expected

### Version with bug

MAUI 8.0.0-preview.7.8842
8.0.0-preview.3.8149

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 16.4, iOS 16.6, macOS 13.4, Visual Studio 17.7.0, Windows 11 Pro 22H2 build 22621.2134

### Did you find any workaround?

No.

### Relevant log output

```shell
N/A
```

**Comment by existcodev** [comment] 2023-08-23 03:15
Also occurs on MAUI 8.0.0-preview.7.8842

**Comment by jfversluis** [comment] 2023-08-24 07:23
Duplicate of https://github.com/xamarin/xamarin-macios/issues/18777

**Closed by jfversluis** 2023-08-24 07:23 UTC
Labels: t/bug
