### ISSUE TITLE
[regression/8.0.0-preview.4.8333] The launch screen of the app is not correct on android and iOS target. 

### ISSUE THREAD

**Issue by QianaJiao** [dotnet/maui#15593] opened 2023-06-13 02:49 UTC
### Description

The launch screen of the app is not correct on android and iOS target. 

### Steps to Reproduce

Note: for android target, repro on API-33, not repro on API-31

**Steps to reproduce:**
Download the project https://github.com/rachelkang/recipeSearch and Locate it.
Execute: dotnet build -t:Run -f net7.0-ios -p:DeviceName=: v2:udid=***** (iPhone 14 Pro Max)
Check the launch screen.
**Actual results:**
The launch screen of the app is not correct on android and iOS target.
1. iOS (Mac): the launch screen shows black screen.
![image](https://github.com/dotnet/maui/assets/91244512/b800bd78-bb62-4a8a-99dc-03a0786f0313)
2. Android (XVS): the launch screen displays incomplete.
![image](https://github.com/dotnet/maui/assets/91244512/4523f16c-076a-42fb-89cd-31a1de572a49)

**Expected Result:**
The launch screen of the app matches the below screen shots.
![image](https://github.com/dotnet/maui/assets/91244512/3fce16ff-2b42-4a9d-81d6-568c342f6e56)

### Link to public reproduction project repository

https://github.com/rachelkang/recipeSearch

### Version with bug

8.0.0-preview.4.8333

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

Android(API33) iOS16

**Comment by mattleibow** [comment] 2023-08-21 14:10
I think there are few things here:

For iOS, what version of Xcode is in use? Are you able to try on another iOS version on the simulator?
There is also this issue which has bit of more info: https://github.com/dotnet/maui/issues/14421

I think for iOS, the black splash is an issue with something in the iOS SDK: https://github.com/xamarin/xamarin-macios/issues/18777

For the clipping on Android, this is Google's design and you have to work around it. In newer versions of Android, you are limited to a circle in the middle of the screen, so you have to ensure your image is circle-supporting: https://github.com/dotnet/maui/issues/10604

**Comment by mattleibow** [comment] 2023-08-21 14:10
Duplicate of https://github.com/dotnet/maui/issues/14421

**Comment by mattleibow** [comment] 2023-08-21 14:10
Duplicate of https://github.com/xamarin/xamarin-macios/issues/18777

**Comment by mattleibow** [comment] 2023-08-21 14:20
Closing the issue here as this seems to be related to the iOS SDK or something outside the .NET MAUI workflow: https://github.com/xamarin/xamarin-macios/issues/18777

The Android issue is as designed and requires a new splash screen design

**Closed by mattleibow** 2023-08-21 14:20 UTC
Labels: t/bug, area/single project ☝️, platform/android 🤖, platform/iOS 🍎, i/regression
