### ISSUE TITLE
[Bug] Doesn't work when I try to debug in Release mode 

### ISSUE THREAD

**Issue by MuratTopcu** [dotnet/maui#3007] opened 2021-10-18 10:40 UTC
### Description
When I try to debug in Release mode it gives the "The "Exec" task returned false but did not log an error." 

Same on both simulator and physical device.

That's why my apps that I publish on google play don't work either. 

I formatted windows 10 and windows 11 but the error did not change 
 
### Steps to Reproduce

1. Install Win10 Pro
2. Install Visual Studio 2022 Preview 5 and check .NET MAUI (preview) under the Mobile Development with .NET workload, and check the Universal Windows Platform development workload.
3. Install the Windows App SDK Single-project MSIX extension
4. Create Maui **Blazor** App project
5. Change Debug to Release
6. Start debugging

### Expected Behavior
Application work
### Actual Behavior
Warning		MSB4181: The "Exec" task returned false but did not log an error.		 	0	
Warning		MSB3073: The command ""C:\Program Files (x86)\Android\android-sdk\platform-tools\adb" -s emulator-5554 uninstall -k "com.companyname.MauiApp1"" exited with code 1.		 	0	
### Basic Information

- Version with issue: .NET MAUI Preview 9
- Last known good version: -
- IDE: Microsoft Visual Studio Enterprise 2022 Preview (64-bit) Version 17.0.0 Preview 5.0
- Platform Target Frameworks:
  - Android: 12
- Nuget Packages: Microsoft.Maui.Controls.Build.Tasks 6.0.101-preview.9.1843, Microsoft.Maui.Dependencies 6.0.101-preview.9.1843, Microsoft.Maui.Extensions 6.0.101-preview.9.1843, Microsoft.Maui.Resizetizer.Sdk 6.0.101-preview.9.1843
- Affected Devices: Pixel 2 Api 28, Mi 10T Lite (Xiaomi M2007J17G Android 11 - API 30)

### Workaround
`<AndroidLinkMode>None</AndroidLinkMode>` add this line to project file

**Comment by jfversluis** [comment] 2022-01-26 16:08
Closing this as a duplicate of the others to not have too many issues about the same thing. Thanks!

**Comment by jfversluis** [comment] 2022-01-26 16:08
Duplicate of #2246

**Closed by jfversluis** 2022-01-26 16:08 UTC
Labels: t/bug, area/tooling ⚙️
