### ISSUE TITLE
Moving MAUI Window between monitors with different scalling has issues

### ISSUE THREAD

**Issue by salarcode** [dotnet/maui#14597] opened 2023-04-15 21:44 UTC
### Description

Moving MAUI window between monitors that have different scaling causes some weird behaviour like window shifting to an unexpected location or moving away from cursors original position and etc..

Here is a video of the behaviour :

https://user-images.githubusercontent.com/1272095/232254330-3c593ced-a8bf-4c62-a848-f6f16a73c3f7.mp4

### Steps to Reproduce

1. Have two monitors
2. Set one monitor to 100% scaling and the other one to 150% scaling
3. Try to move MAUI window slowly between monitors
4. Now try moving the window faster between monitors. 

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows

### Did you find any workaround?

No

**Comment by salarcode** [comment] 2023-04-15 21:53
I think the problem lies in these lines:
https://github.com/dotnet/maui/blob/48d02949c511bd979f061343f90ea63cd227558e/src/Controls/src/Core/HandlerImpl/Window/Window.Impl.cs#L209-L212


I know this is not a solution but if I comment out these line the problem doesn't happen:


![image](https://user-images.githubusercontent.com/1272095/232254686-09361ba2-958b-4deb-8262-88d9337dfa7f.png)

**Comment by drasticactions** [comment] 2023-04-17 06:01
Duplicate of https://github.com/dotnet/maui/issues/11777

**Comment by rmarinho** [comment] 2023-08-04 15:13
Sorry but we have to [revert the PR](https://github.com/dotnet/maui/pull/16541) that fixes this issue. We are working in improving the related fix to be merged on main.
Thanks.

**Closed** 2023-08-11 15:47 UTC
Labels: t/bug
