### ISSUE TITLE
RadioButton not selected/checked despite IsChecked=True being set in two column grid layout with two sets of radio button groups

### ISSUE THREAD

**Issue by martin-honnen** [dotnet/maui#13631] opened 2023-03-02 06:52 UTC
### Description

I am trying to use various radio buttons in a layout like 

```
<Grid ColumnDefinitions="*,*" RowDefinitions="45, *, *">

        <HorizontalStackLayout Grid.Row="0" Grid.Column="0" HorizontalOptions="CenterAndExpand">
            <RadioButton x:Name="xmlInput" GroupName="inputType" IsChecked="True" Content="XML input"/>
            <RadioButton x:Name="jsonInput" GroupName="inputType" IsChecked="False" Content="JSON input"/>
            <RadioButton x:Name="noInput" GroupName="inputType" IsChecked="False" Content="No input"/>
            <Button x:Name="newBtn" Text="New"/>
        </HorizontalStackLayout>

        <HorizontalStackLayout Grid.Row="0" Grid.Column="1" HorizontalOptions="CenterAndExpand">
            <RadioButton x:Name="xsltCode" GroupName="codeType" IsChecked="True" Content="XSLT code"/>
            <RadioButton x:Name="xqueryCode" GroupName="codeType" IsChecked="False" Content="XQuery code"/>
            <RadioButton x:Name="xpathCode" GroupName="codeType" IsChecked="False" Content="XPath code"/>
            <Button x:Name="evaluateBtn" Text="Evaluate"/>
        </HorizontalStackLayout>
```

On Windows I find that in the left column the radio button with IsChecked=True is not visually selected/checked while the one in the right column is. On WSA it works fine. I think the Windows display is a bug.

Windows:

![radio-button-groups-in-grid-windows](https://user-images.githubusercontent.com/8466401/222350993-b8863c5a-f7b0-401c-85ae-3ae2d1dd22f4.png)
WSA:

![radio-button-groups-in-grid-wsa](https://user-images.githubusercontent.com/8466401/222351022-9e64b102-b55a-410a-bfd4-1ac60b33b614.png)

### Steps to Reproduce

1. Clone repository https://github.com/martin-honnen/RadioButtonGroupInGrid.App
2. Run under Windows and check whether RadioButton with IsChecked=True in left column is visually selected/checked.
3. Compare to running under WSA where in both columns the first RadioButton is both columns is visually selected/checked.

### Link to public reproduction project repository

https://github.com/martin-honnen/RadioButtonGroupInGrid.App

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 11 22H2 (22621.1265), net7.0-windows10.0.19041.0

### Did you find any workaround?

No.

**Comment by samhouts** [comment] 2023-03-02 23:33
Duplicate of #11418

**Closed by samhouts** 2023-03-02 23:33 UTC
Labels: t/bug, platform/windows 🪟, area/controls 🎮, control-radiobutton
