### ISSUE TITLE
Memory leak when Windows multiple window get closed

### ISSUE THREAD

**Issue by jingliancui** [dotnet/maui#24140] opened 2024-08-11 13:32 UTC
### Description

The memory doesn't get released after the windows get closed.

### Steps to Reproduce

1. Open the .sln by using vs2022
2. F5 to start debug the project
3. Input a number 50 to the Entry Control
4. Click the button "new windows"
5. Observe the "Process Memory" part of the VS tool "Diagnostic Tools", the memory increase
6. Click the button "Close all windows"
7. Continue repeat step 4 to step 6

Actually Result:
"Process Memory" doesn't get reduce

Expect Result:
"Process Memory" get reduce

### Link to public reproduction project repository

https://github.com/jingliancui/MAUIWinUIWinMemoryLeakIssue

### Version with bug

8.0.80 SR8

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

10.0.19041.0

### Did you find any workaround?

No

### Relevant log output

```shell
No
```

**Comment by jfversluis** [comment] 2024-08-11 20:26
Duplicate of #24102

**Closed by jfversluis** 2024-08-11 20:26 UTC
Labels: t/bug
