### ISSUE TITLE
Baidu Push SDK: No implementation found for void crc6488302ad6e9e4df1a.MauiApplication.n_onCreate() 

### ISSUE THREAD

**Issue by busec0** [dotnet/maui#16142] opened 2023-07-13 13:46 UTC
### Description

I'm getting a `No implementation found for void crc6488302ad6e9e4df1a.MauiApplication.n_onCreate()` error trying to start the Baidu push notification service. 

**Context**: I'm trying to create a .NET 6 binding library for Android, based on the BAIU Push SDK: https://push.baidu.com/doc/android/api 

Source code is here (https://github.com/busec0/Baidu.Push.Android) and it includes:
1. The binding project 
2. A sample for Android Native (.net 7)
3. A sample for MAUI (.net 7) 

While the Android Native sample works perfectly, on MAUI it's impossible to start the push notification service. When the method to start it is called: 

```csharp
PushManager.StartWork(crtActivity.ApplicationContext, PushConstants.LoginTypeApiKey, _baiduApiKey);
```

It automatically fails with the error below: 

```
2023-07-13 16:36:26.120 23202-23202/com.abb.aaaa E/aa:bdservice_v: No implementation found for void crc6488302ad6e9e4df1a.MauiApplication.n_onCreate() (tried Java_crc6488302ad6e9e4df1a_MauiApplication_n_1onCreate and Java_crc6488302ad6e9e4df1a_MauiApplication_n_1onCreate__)
2023-07-13 16:36:26.120 23202-23202/com.abb.aaaa D/AndroidRuntime: Shutting down VM
2023-07-13 16:36:26.121 23202-23202/com.abb.aaaa E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.abb.aaaa:bdservice_v1, PID: 23202
    java.lang.UnsatisfiedLinkError: No implementation found for void crc6488302ad6e9e4df1a.MauiApplication.n_onCreate() (tried Java_crc6488302ad6e9e4df1a_MauiApplication_n_1onCreate and Java_crc6488302ad6e9e4df1a_MauiApplication_n_1onCreate__)
        at crc6488302ad6e9e4df1a.MauiApplication.n_onCreate(Native Method)
        at crc6488302ad6e9e4df1a.MauiApplication.onCreate(MauiApplication.java:28)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1211)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6725)
        at android.app.ActivityThread.access$1500(ActivityThread.java:247)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2053)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7839)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

**Note:** The error comes from Baidu's external service responsible for receiving notifications. It'll not show up under the Visual Studio logs, you must use `adb logcat`. 

### Steps to Reproduce

1. Check out https://github.com/busec0/Baidu.Push.Android/blob/main/BaiduAndroidSampleMaui/MainPage.xaml.cs 
2. Build and deploy on Android the `BaiduAndroidSampleMaui` target 
3. Tap on "Start Push" 
4. Notice the failure 

```
2023-07-13 16:36:26.120 23202-23202/com.abb.aaaa E/aa:bdservice_v: No implementation found for void crc6488302ad6e9e4df1a.MauiApplication.n_onCreate() (tried Java_crc6488302ad6e9e4df1a_MauiApplication_n_1onCreate and Java_crc6488302ad6e9e4df1a_MauiApplication_n_1onCreate__)
2023-07-13 16:36:26.120 23202-23202/com.abb.aaaa D/AndroidRuntime: Shutting down VM
2023-07-13 16:36:26.121 23202-23202/com.abb.aaaa E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.abb.aaaa:bdservice_v1, PID: 23202
    java.lang.UnsatisfiedLinkError: No implementation found for void crc6488302ad6e9e4df1a.MauiApplication.n_onCreate() (tried Java_crc6488302ad6e9e4df1a_MauiApplication_n_1onCreate and Java_crc6488302ad6e9e4df1a_MauiApplication_n_1onCreate__)
        at crc6488302ad6e9e4df1a.MauiApplication.n_onCreate(Native Method)
        at crc6488302ad6e9e4df1a.MauiApplication.onCreate(MauiApplication.java:28)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1211)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6725)
        at android.app.ActivityThread.access$1500(ActivityThread.java:247)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2053)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7839)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

### Link to public reproduction project repository

https://github.com/busec0/Baidu.Push.Android/tree/main

### Version with bug

7.0.86

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

All

### Did you find any workaround?

Nope. 

Tried with different things: 

1. Real device / simulator 
2. Disable/enable linking 
3. Debug/Release configuration 
4. Made sure to manually clean bin and obj. 

Nothing worked. 

### Relevant log output

```shell
2023-07-13 16:37:25.866 314-314/? D/Zygote: Forked child process 23618
2023-07-13 16:37:25.867 819-1036/? I/ActivityManager: Start proc 23618:com.abb.aaaa:bdservice_v1/u0a151 for service {com.abb.aaaa/com.baidu.android.pushservice.job.PushJobService}
2023-07-13 16:37:25.872 23618-23618/? I/aa:bdservice_v: Late-enabling -Xcheck:jni
2023-07-13 16:37:25.886 387-435/? I/adbd: jdwp connection from 23618
2023-07-13 16:37:25.900 23618-23618/com.abb.aaaa D/CompatibilityChangeReporter: Compat change id reported: 171979766; UID 10151; state: ENABLED
2023-07-13 16:37:25.987 23618-23618/? D/NetworkSecurityConfig: No Network Security Config specified, using platform default
2023-07-13 16:37:25.987 23618-23618/? D/NetworkSecurityConfig: No Network Security Config specified, using platform default
2023-07-13 16:37:25.991 23618-23618/? E/aa:bdservice_v: No implementation found for void crc6488302ad6e9e4df1a.MauiApplication.n_onCreate() (tried Java_crc6488302ad6e9e4df1a_MauiApplication_n_1onCreate and Java_crc6488302ad6e9e4df1a_MauiApplication_n_1onCreate__)
2023-07-13 16:37:25.991 23618-23618/? D/AndroidRuntime: Shutting down VM
2023-07-13 16:37:25.993 23618-23618/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.abb.aaaa:bdservice_v1, PID: 23618
    java.lang.UnsatisfiedLinkError: No implementation found for void crc6488302ad6e9e4df1a.MauiApplication.n_onCreate() (tried Java_crc6488302ad6e9e4df1a_MauiApplication_n_1onCreate and Java_crc6488302ad6e9e4df1a_MauiApplication_n_1onCreate__)
        at crc6488302ad6e9e4df1a.MauiApplication.n_onCreate(Native Method)
        at crc6488302ad6e9e4df1a.MauiApplication.onCreate(MauiApplication.java:28)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1211)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6725)
        at android.app.ActivityThread.access$1500(ActivityThread.java:247)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2053)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7839)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
2023-07-13 16:37:25.994 819-23637/? I/DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
2023-07-13 16:37:25.994 23618-23618/? I/Process: Sending signal. PID: 23618 SIG: 9
2023-07-13 16:37:25.994 819-1035/? W/BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
2023-07-13 16:37:25.994 819-1035/? W/BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
2023-07-13 16:37:25.998 819-1337/? I/ActivityManager: Process com.abb.aaaa:bdservice_v1 (pid 23618) has died: fg  TRNB
2023-07-13 16:37:25.999 819-1337/? W/ActivityManager: Scheduling restart of crashed service com.abb.aaaa/com.baidu.android.pushservice.job.PushJobService in 1800000ms for connection
2023-07-13 16:37:25.999 819-1038/? I/libprocessgroup: Successfully killed process cgroup uid 10151 pid 23618 in 0ms
2023-07-13 16:37:25.999 314-314/? I/Zygote: Process 23618 exited due to signal 9 (Killed)
```
```

**Comment by rachelkang** [comment] 2023-07-13 18:09
@jonathanpeppers any thoughts on this one?

**Comment by jonathanpeppers** [comment] 2023-07-13 19:51
> java.lang.UnsatisfiedLinkError: No implementation found for...

https://stackoverflow.com/questions/43048166/java-lang-unsatisfiedlinkerror-no-implementation-found-for-int

This normally means the JVM was unable to load the native library (`.so` file). Are the required native libraries in the MAUI application? Inside the `.apk`?

You might also try a `dotnet new android` project -- taking .NET MAUI out of the equation. Does a plain Android project work?

**Comment by busec0** [comment] 2023-07-13 20:01
> You might also try a dotnet new android project -- taking .NET MAUI out of the equation. Does a plain Android project work?

@jonathanpeppers Yes, a plain .NET 7 Android project works fine  - I included this detail in the description, and the android native project is also in the repro repository I shared in the description. 

> This normally means the JVM was unable to load the native library (.so file).  

@jonathanpeppers In the Stackoverflow link it says: 

```
java.lang.UnsatisfiedLinkError: No implementation found for int com.ephronsystem.mobilizerapp.Ffmpeg.encodeVideoFrame(byte[]) 
``` 

The missing implementation is in the third library itself. In this case, the missing implementation seems to be part of MauiApplication. 

```
java.lang.UnsatisfiedLinkError: No implementation found for void crc6488302ad6e9e4df1a.MauiApplication.n_onCreate() (tried Java_crc6488302ad6e9e4df1a_MauiApplication_n_1onCreate and Java_crc6488302ad6e9e4df1a_MauiApplication_n_1onCreate__)
```

**Comment by jonathanpeppers** [comment] 2023-07-13 20:05
@busec0 does the problem only happen because MAUI apps *have* to use a `Android.App.Application` subclass?

If you set one of those up in a plain Android app, does it also break?

```csharp
[Android.App.Application]
public class MyApplication : Android.App.Application
{
    public MyApplication(IntPtr handle, Android.Runtime.JniHandleOwnership owner) : base(handle, owner) { }

    public override void OnCreate()
    {
        base.OnCreate();
        Console.WriteLine("Just log something here, to make sure it prints");
    }
}
```

**Comment by busec0** [comment] 2023-07-13 20:12
@jonathanpeppers looks like so. Doing the change in the plain Android app, I'm ending up with the same error: 

```
2023-07-13 23:11:03.742 6067-6067/com.abb.aa E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.abb.aa:bdservice_v1, PID: 6067
    java.lang.UnsatisfiedLinkError: No implementation found for void crc64c0e3dc4476436a10.MyApplication.n_onCreate() (tried Java_crc64c0e3dc4476436a10_MyApplication_n_1onCreate and Java_crc64c0e3dc4476436a10_MyApplication_n_1onCreate__)
        at crc64c0e3dc4476436a10.MyApplication.n_onCreate(Native Method)
        at crc64c0e3dc4476436a10.MyApplication.onCreate(MyApplication.java:25)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1211)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6725)
        at android.app.ActivityThread.access$1500(ActivityThread.java:247)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2053)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7839)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

**Comment by busec0** [comment] 2023-07-14 06:08
@jonathanpeppers Should this be moved to `xamarin-android`? Any idea why would this be happening? Subclassing `Android.App.Application`  in an Android Native app (java) works fine.

**Comment by busec0** [comment] 2023-07-14 17:36
This seems to be related https://github.com/xamarin/xamarin-android/issues/3378 😞 Since the Baidu external service cannot load Xamarin.Android. 

>  it's nearly impossible to implement support for this, at least with the way Xamarin.Android currently works. 

@jonathanpeppers can you please confirm?

**Comment by jonathanpeppers** [comment] 2023-07-17 13:16
I looked at the `.aar` file:

https://github.com/busec0/Baidu.Push.Android/blob/main/Baidu.Push.Android.Binding/baidu-push-sdk-8.2.9.3.aar

The `AndroidManifest.xml` has entries like:

![image](https://github.com/dotnet/maui/assets/840039/f9b0160b-c3b9-4f30-bc0e-9a3bdcdd72ca)

https://developer.android.com/guide/topics/manifest/service-element

There are actually several services in here, and they all specify `android:process=":bdservice_v1"`.

The only workaround I could think of is to use the [`manifest-merger` feature](https://developer.android.com/build/manage-manifests) to remove these attributes, but they probably specify `android:process` for a reason...

This does seem the same as: https://github.com/xamarin/xamarin-android/issues/3378

**Comment by jonathanpeppers** [comment] 2023-07-17 13:17
Duplicate of https://github.com/xamarin/xamarin-android/issues/3378

**Closed by jonathanpeppers** 2023-07-17 13:17 UTC
Labels: t/bug, platform/android 🤖
