### ISSUE TITLE
In iOS, calling .Clear() on an ObservableCollection bound to a listview causes a nullref

### ISSUE THREAD

**Issue by edgiardina** [dotnet/maui#9302] opened 2022-08-10 01:27 UTC
### Description

I receive the following exception which appears to be thrown from the iOS internals (Android is fine) when clearing a listview's ObserableCollection binding

```
[0:] System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Maui.Controls.Handlers.Compatibility.ListViewRenderer.UnevenListViewDataSource.ClearPrototype()
   at Microsoft.Maui.Controls.Handlers.Compatibility.ListViewRenderer.UnevenListViewDataSource.InvalidatingPrototypicalCellCache()
   at Microsoft.Maui.Controls.Handlers.Compatibility.ListViewRenderer.ListViewDataSource.InvalidatePrototypicalCellCache()
   at Microsoft.Maui.Controls.Handlers.Compatibility.ListViewRenderer.InvalidateCellCache()
   at Microsoft.Maui.Controls.Handlers.Compatibility.ListViewRenderer.UpdateItems(NotifyCollectionChangedEventArgs e, Int32 section, Boolean resetWhenGrouped)
   at Microsoft.Maui.Controls.Handlers.Compatibility.ListViewRenderer.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
   at Microsoft.Maui.Controls.Internals.TemplatedItemsList`2[[Microsoft.Maui.Controls.ItemsView`1[[Microsoft.Maui.Controls.Cell, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Controls.Cell, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at Microsoft.Maui.Controls.Internals.TemplatedItemsList`2[[Microsoft.Maui.Controls.ItemsView`1[[Microsoft.Maui.Controls.Cell, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Controls.Cell, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].OnProxyCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
   at Microsoft.Maui.Controls.ListProxy.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at Microsoft.Maui.Controls.ListProxy.<>c__DisplayClass34_0.<OnCollectionChanged>b__0()
   at Microsoft.Maui.Controls.DispatcherExtensions.DispatchIfRequired(IDispatcher dispatcher, Action action)
   at Microsoft.Maui.Controls.ListProxy.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
   at Microsoft.Maui.Controls.ListProxy.WeakNotifyProxy.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1[[Ifpa.Models.RankingWithFormattedLocation, IfpaMaui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1[[Ifpa.Models.RankingWithFormattedLocation, IfpaMaui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].OnCollectionReset()
   at System.Collections.ObjectModel.ObservableCollection`1[[Ifpa.Models.RankingWithFormattedLocation, IfpaMaui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].ClearItems()
   at System.Collections.ObjectModel.Collection`1[[Ifpa.Models.RankingWithFormattedLocation, IfpaMaui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].Clear()
   at Ifpa.ViewModels.RankingsViewModel.ExecuteLoadItemsCommand() in C:\Users\ed_gi\source\repos\IfpaMaui\ViewModels\RankingsViewModel.cs:line 95
**System.ArgumentOutOfRangeException:** 'Specified argument was out of the range of valid values. (Parameter 'index')'
```

I receive a few exceptions like `**System.ArgumentOutOfRangeException:** 'Specified argument was out of the range of valid values. (Parameter 'index')'` in this as well. 

### Steps to Reproduce

1. Create file -> new .net maui app
2. Add a Simple listview to the mainpage xaml
3. in the codebehind create a simple ObservableCollection list
4. Bind the Listview to the observable collection
5. Clear the observablecollection with .Clear() via a button event handler or the like.
6. Run project on an iOS Sim and click the button
7. Witness a crash. 

(attached is a project that reproduces this)

https://github.com/edgiardina/crashing-clearing-listview-maui

[crashing clearing listview maui.zip](https://github.com/dotnet/maui/files/9295714/crashing.clearing.listview.maui.zip)
 

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15.4

### Did you find any workaround?

Not yet no

### Relevant log output

```shell
[0:] System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Maui.Controls.Handlers.Compatibility.ListViewRenderer.UnevenListViewDataSource.ClearPrototype()
   at Microsoft.Maui.Controls.Handlers.Compatibility.ListViewRenderer.UnevenListViewDataSource.InvalidatingPrototypicalCellCache()
   at Microsoft.Maui.Controls.Handlers.Compatibility.ListViewRenderer.ListViewDataSource.InvalidatePrototypicalCellCache()
   at Microsoft.Maui.Controls.Handlers.Compatibility.ListViewRenderer.InvalidateCellCache()
   at Microsoft.Maui.Controls.Handlers.Compatibility.ListViewRenderer.UpdateItems(NotifyCollectionChangedEventArgs e, Int32 section, Boolean resetWhenGrouped)
   at Microsoft.Maui.Controls.Handlers.Compatibility.ListViewRenderer.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
   at Microsoft.Maui.Controls.Internals.TemplatedItemsList`2[[Microsoft.Maui.Controls.ItemsView`1[[Microsoft.Maui.Controls.Cell, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Controls.Cell, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at Microsoft.Maui.Controls.Internals.TemplatedItemsList`2[[Microsoft.Maui.Controls.ItemsView`1[[Microsoft.Maui.Controls.Cell, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Controls.Cell, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].OnProxyCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
   at Microsoft.Maui.Controls.ListProxy.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at Microsoft.Maui.Controls.ListProxy.<>c__DisplayClass34_0.<OnCollectionChanged>b__0()
   at Microsoft.Maui.Controls.DispatcherExtensions.DispatchIfRequired(IDispatcher dispatcher, Action action)
   at Microsoft.Maui.Controls.ListProxy.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
   at Microsoft.Maui.Controls.ListProxy.WeakNotifyProxy.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1[[Ifpa.Models.RankingWithFormattedLocation, IfpaMaui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1[[Ifpa.Models.RankingWithFormattedLocation, IfpaMaui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].OnCollectionReset()
   at System.Collections.ObjectModel.ObservableCollection`1[[Ifpa.Models.RankingWithFormattedLocation, IfpaMaui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].ClearItems()
   at System.Collections.ObjectModel.Collection`1[[Ifpa.Models.RankingWithFormattedLocation, IfpaMaui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].Clear()
   at Ifpa.ViewModels.RankingsViewModel.ExecuteLoadItemsCommand() in C:\Users\ed_gi\source\repos\IfpaMaui\ViewModels\RankingsViewModel.cs:line 95
[0:] System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Maui.Controls.Handlers.Compatibility.ListViewRenderer.UnevenListViewDataSource.ClearPrototype()
   at Microsoft.Maui.Controls.Handlers.Compatibility.ListViewRenderer.UnevenListViewDataSource.InvalidatingPrototypicalCellCache()
   at Microsoft.Maui.Controls.Handlers.Compatibility.ListViewRenderer.ListViewDataSource.InvalidatePrototypicalCellCache()
   at Microsoft.Maui.Controls.Handlers.Compatibility.ListViewRenderer.InvalidateCellCache()
   at Microsoft.Maui.Controls.Handlers.Compatibility.ListViewRenderer.UpdateItems(NotifyCollectionChangedEventArgs e, Int32 section, Boolean resetWhenGrouped)
   at Microsoft.Maui.Controls.Handlers.Compatibility.ListViewRenderer.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
   at Microsoft.Maui.Controls.Internals.TemplatedItemsList`2[[Microsoft.Maui.Controls.ItemsView`1[[Microsoft.Maui.Controls.Cell, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Controls.Cell, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at Microsoft.Maui.Controls.Internals.TemplatedItemsList`2[[Microsoft.Maui.Controls.ItemsView`1[[Microsoft.Maui.Controls.Cell, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Controls.Cell, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].OnProxyCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
   at Microsoft.Maui.Controls.ListProxy.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at Microsoft.Maui.Controls.ListProxy.<>c__DisplayClass34_0.<OnCollectionChanged>b__0()
   at Microsoft.Maui.Controls.DispatcherExtensions.DispatchIfRequired(IDispatcher dispatcher, Action action)
   at Microsoft.Maui.Controls.ListProxy.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
   at Microsoft.Maui.Controls.ListProxy.WeakNotifyProxy.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1[[Ifpa.Models.RankingWithFormattedLocation, IfpaMaui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1[[Ifpa.Models.RankingWithFormattedLocation, IfpaMaui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].OnCollectionReset()
   at System.Collections.ObjectModel.ObservableCollection`1[[Ifpa.Models.RankingWithFormattedLocation, IfpaMaui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].ClearItems()
   at System.Collections.ObjectModel.Collection`1[[Ifpa.Models.RankingWithFormattedLocation, IfpaMaui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].Clear()
   at Ifpa.ViewModels.RankingsViewModel.ExecuteLoadItemsCommand() in C:\Users\ed_gi\source\repos\IfpaMaui\ViewModels\RankingsViewModel.cs:line 95
[0:] System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Maui.Controls.Handlers.Compatibility.ListViewRenderer.UnevenListViewDataSource.ClearPrototype()
   at Microsoft.Maui.Controls.Handlers.Compatibility.ListViewRenderer.UnevenListViewDataSource.InvalidatingPrototypicalCellCache()
   at Microsoft.Maui.Controls.Handlers.Compatibility.ListViewRenderer.ListViewDataSource.InvalidatePrototypicalCellCache()
   at Microsoft.Maui.Controls.Handlers.Compatibility.ListViewRenderer.InvalidateCellCache()
   at Microsoft.Maui.Controls.Handlers.Compatibility.ListViewRenderer.UpdateItems(NotifyCollectionChangedEventArgs e, Int32 section, Boolean resetWhenGrouped)
   at Microsoft.Maui.Controls.Handlers.Compatibility.ListViewRenderer.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
   at Microsoft.Maui.Controls.Internals.TemplatedItemsList`2[[Microsoft.Maui.Controls.ItemsView`1[[Microsoft.Maui.Controls.Cell, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Controls.Cell, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at Microsoft.Maui.Controls.Internals.TemplatedItemsList`2[[Microsoft.Maui.Controls.ItemsView`1[[Microsoft.Maui.Controls.Cell, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Controls.Cell, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].OnProxyCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
   at Microsoft.Maui.Controls.ListProxy.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at Microsoft.Maui.Controls.ListProxy.<>c__DisplayClass34_0.<OnCollectionChanged>b__0()
   at Microsoft.Maui.Controls.DispatcherExtensions.DispatchIfRequired(IDispatcher dispatcher, Action action)
   at Microsoft.Maui.Controls.ListProxy.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
   at Microsoft.Maui.Controls.ListProxy.WeakNotifyProxy.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1[[Ifpa.Models.RankingWithFormattedLocation, IfpaMaui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1[[Ifpa.Models.RankingWithFormattedLocation, IfpaMaui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].OnCollectionReset()
   at System.Collections.ObjectModel.ObservableCollection`1[[Ifpa.Models.RankingWithFormattedLocation, IfpaMaui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].ClearItems()
   at System.Collections.ObjectModel.Collection`1[[Ifpa.Models.RankingWithFormattedLocation, IfpaMaui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].Clear()
   at Ifpa.ViewModels.RankingsViewModel.ExecuteLoadItemsCommand() in C:\Users\ed_gi\source\repos\IfpaMaui\ViewModels\RankingsViewModel.cs:line 95
The thread 0x3 has exited with code 0 (0x0).
Thread finished: <Thread Pool> #3
[0:] System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Maui.Controls.Handlers.Compatibility.ListViewRenderer.UnevenListViewDataSource.ClearPrototype()
   at Microsoft.Maui.Controls.Handlers.Compatibility.ListViewRenderer.UnevenListViewDataSource.InvalidatingPrototypicalCellCache()
   at Microsoft.Maui.Controls.Handlers.Compatibility.ListViewRenderer.ListViewDataSource.InvalidatePrototypicalCellCache()
   at Microsoft.Maui.Controls.Handlers.Compatibility.ListViewRenderer.InvalidateCellCache()
   at Microsoft.Maui.Controls.Handlers.Compatibility.ListViewRenderer.UpdateItems(NotifyCollectionChangedEventArgs e, Int32 section, Boolean resetWhenGrouped)
   at Microsoft.Maui.Controls.Handlers.Compatibility.ListViewRenderer.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
   at Microsoft.Maui.Controls.Internals.TemplatedItemsList`2[[Microsoft.Maui.Controls.ItemsView`1[[Microsoft.Maui.Controls.Cell, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Controls.Cell, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at Microsoft.Maui.Controls.Internals.TemplatedItemsList`2[[Microsoft.Maui.Controls.ItemsView`1[[Microsoft.Maui.Controls.Cell, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Controls.Cell, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].OnProxyCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
   at Microsoft.Maui.Controls.ListProxy.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at Microsoft.Maui.Controls.ListProxy.<>c__DisplayClass34_0.<OnCollectionChanged>b__0()
   at Microsoft.Maui.Controls.DispatcherExtensions.DispatchIfRequired(IDispatcher dispatcher, Action action)
   at Microsoft.Maui.Controls.ListProxy.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
   at Microsoft.Maui.Controls.ListProxy.WeakNotifyProxy.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1[[Ifpa.Models.RankingWithFormattedLocation, IfpaMaui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1[[Ifpa.Models.RankingWithFormattedLocation, IfpaMaui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].OnCollectionReset()
   at System.Collections.ObjectModel.ObservableCollection`1[[Ifpa.Models.RankingWithFormattedLocation, IfpaMaui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].ClearItems()
   at System.Collections.ObjectModel.Collection`1[[Ifpa.Models.RankingWithFormattedLocation, IfpaMaui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].Clear()
   at Ifpa.ViewModels.RankingsViewModel.ExecuteLoadItemsCommand() in C:\Users\ed_gi\source\repos\IfpaMaui\ViewModels\RankingsViewModel.cs:line 95
**System.ArgumentOutOfRangeException:** 'Specified argument was out of the range of valid values. (Parameter 'index')'

2022-08-09 21:06:29.852803-0400 IfpaMaui[77148:92270294] 
Unhandled Exception:
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'index')
   at Microsoft.Maui.Controls.ListProxy.get_Item(Int32 index)
   at Microsoft.Maui.Controls.ListProxy.System.Collections.IList.get_Item(Int32 index)
   at Microsoft.Maui.Controls.Internals.TemplatedItemsList`2[[Microsoft.Maui.Controls.ItemsView`1[[Microsoft.Maui.Controls.Cell, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Controls.Cell, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].UpdateContent(Cell content, Int32 index)
   at Microsoft.Maui.Controls.Internals.TemplatedItemsList`2[[Microsoft.Maui.Controls.ItemsView`1[[Microsoft.Maui.Controls.Cell, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], Microsoft.Maui.Controls, Ver
sion=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Controls.Cell, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].Microsoft.Maui.Controls.ITemplatedItemsList<TItem>.UpdateContent(Cell content, Int32 index)
   at Microsoft.Maui.Controls.Handlers.Compatibility.ListViewRenderer.ListViewDataSource.GetCell(UITableView tableView, NSIndexPath indexPath)
   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass)
   at Ifpa.Program.Main(String[] args) in C:\Users\ed_gi\source\repos\IfpaMaui\Platforms\iOS\Program.cs:line 13
2022-08-09 21:06:29.858090-0400 IfpaMaui[77148:92270294] Unhandled managed exception: Specified argument was out of the range of valid values. (Parameter 'index') (System.ArgumentOutOfRangeException)
   at Microsoft.Maui.Controls.ListProxy.get_Item(Int32 index)
   at Microsoft.Maui.Controls.ListProxy.System.Collections.IList.get_Item(Int32 index)
   at Microsoft.Maui.Controls.Internals.TemplatedItemsList`2[[Microsoft.Maui.Controls.ItemsView`1[[Microsoft.Maui.Controls.Cell, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Controls.Cell, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].UpdateContent(Cell content, Int32 index)
   at Microsoft.Maui.Controls.Internals.TemplatedItemsList`2[[Microsoft.Maui.Controls.ItemsView`1[[Microsoft.Maui.Controls.Cell, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], Microsoft.Maui.Contr
ols, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Controls.Cell, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].Microsoft.Maui.Controls.ITemplatedItemsList<TItem>.UpdateContent(Cell content, Int32 index)
   at Microsoft.Maui.Controls.Handlers.Compatibility.ListViewRenderer.ListViewDataSource.GetCell(UITableView tableView, NSIndexPath indexPath)
   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass)
   at Ifpa.Program.Main(String[] args) in C:\Users\ed_gi\source\repos\IfpaMaui\Platforms\iOS\Program.cs:line 13

=================================================================
	Native Crash Reporting
=================================================================
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

=================================================================
	Native stacktrace:
=================================================================
	0x10dc309d5 - /Users/edgiardina/Library/Developer/CoreSimulator/Devices/DCA3F0B4-7F0E-4D94-82C1-840D0ABF09B1/data/Containers/Bundle/Application/61F75A47-04C4-4C86-98AE-F12712EB478F/IfpaMaui.app/libmonosgen-2.0.dylib : mono_dump_native_crash_info
	0x10dbd067e - /Users/edgiardina/Library/Developer/CoreSimulator/Devices/DCA3F0B4-7F0E-4D94-82C1-840D0ABF09B1/data/Containers/Bundle/Application/61F75A47-04C4-4C86-98AE-F12712EB478F/IfpaMaui.app/libmonosgen-2.0.dylib : mono_handle_native_crash
	0x10dc302e2 - /Users/edgiardina/Library/Developer/CoreSimulator/Devices/DCA3F0B4-7F0E-4D94-82C1-840D0ABF09B1/data/Containers/Bundle/Application/61F75A47-04C4-4C86-98AE-F12712EB478F/IfpaMaui.app/libmonosgen-2.0.dylib : sigabrt_signal_handler
	0x11e9f3e2d - /usr/lib/system/libsystem_platform.dylib : _sigtramp
	0x8e3a018e38018e37 - Unknown
	0x11f34c6b7 - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/system/libsystem_c.dylib : abort
	0x10d455047 - /Users/edgiardina/Library/Developer/CoreSimulator/Devices/DCA3F0B4-7F0E-4D94-82C1-840D0ABF09B1/data/Containers/Bundle/Application/61F75A47-04C4-4C86-98AE-F12712EB478F/IfpaMaui.app/libxamarin-dotnet-debug.dylib : xamarin_unhandled_exception_handler
	0x10da04375 - /Users/edgiardina/Library/Developer/CoreSimulator/Devices/DCA3F0B4-7F0E-4D94-82C1-840D0ABF09B1/data/Containers/Bundle/Application/61F75A47-04C4-4C86-98AE-F12712EB478F/IfpaMaui.app/libmonosgen-2.0.dylib : mono_invoke_unhandled_exception_hook
	0x10db8c072 - /Users/edgiardina/Library/Developer/CoreSimulator/Devices/DCA3F0B4-7F0E-4D94-82C1-840D0ABF09B1/data/Containers/Bundle/Application/61F75A47-04C4-4C86-98AE-F12712EB478F/IfpaMaui.app/libmonosgen-2.0.dylib : mono_jit_exec
	0x10d468f0d - /Users/edgiardina/Library/Developer/CoreSimulator/Devices/DCA3F0B4-7F0E-4D94-82C1-840D0ABF09B1/data/Containers/Bundle/Application/61F75A47-04C4-4C86-98AE-F12712EB478F/IfpaMaui.app/libxamarin-dotnet-debug.dylib : xamarin_main
	0x1044c2824 - /Users/edgiardina/Library/Developer/CoreSimulator/Devices/DCA3F0B4-7F0E-4D94-82C1-840D0ABF09B1/data/Containers/Bundle/Application/61F75A47-04C4-4C86-98AE-F12712EB478F/IfpaMaui.app/IfpaMaui : main
	0x10d03bf21 - Unknown
	0x20493d4fe - Unknown
	0x204938000 - Unknown

=================================================================
	Basic Fault Address Reporting
=================================================================
Memory around native instruction pointer (0x11f3b6112):
0x11f3b6102  
ff ff c3 90 90 90 b8 48 01 00 02 49 89 
ca 
0f 05  .......H...I...
.
0x11f3b6112  73 08 48 89 c7 e9 d5 a1 ff ff c3 90 90 
90 b8 53  s.H............S

0x11f3b6122  00 00 02 49 89 ca 0f 05 73 08 48 89 c7 e9 bd a1  ...I....s.H.
....
0x11f3b6132  ff ff c3 90 90 90 b8 83 01 00 02 49 89 ca 0f 05  .......
....I....

=================================================================
	Managed Stacktrace:
=================================================================
=================================================================
The app has been terminated.
```

**Comment by PureWeen** [comment] 2022-08-11 18:38
Code here needs a `?` https://github.com/dotnet/maui/blob/64432c450080efa99084f040c933c9011b066989/src/Controls/src/Core/Compatibility/Handlers/ListView/iOS/ListViewRenderer.cs#L964

**Comment by jfversluis** [comment] 2022-08-12 11:18
Duplicate of #8734

But since both have a good amount of info I'll just link the two for now like this and leave them open

**Closed** 2022-09-28 14:22 UTC
Labels: t/bug, area/ListView

**Comment by jadenrogers** [comment] 2022-10-09 03:45
Whats the work around for people not wanting to jump to .net 7?
