### ISSUE TITLE
Image’s Animation

### ISSUE THREAD

**Issue by jrahma** [dotnet/maui#2017] opened 2021-08-10 10:02 UTC
Hi

Please add Animation property to the Image control like this:

`<Image Animation="Zoom" AnimationSpeed="4000" />`

This will zoom the image once loaded and it will complete in 4 seconds.

It will easier to have it as a property than applying Animation to the Image

**Comment by jfversluis** [comment] 2021-11-05 11:17
Duplicate of #3207

**Closed by jfversluis** 2021-11-05 11:17 UTC
Labels: t/enhancement ☀️, area/animation 🎬
