### ISSUE TITLE
SwipeView  SwipeItemView Layout error

### ISSUE THREAD

**Issue by HenJigg** [dotnet/maui#8343] opened 2022-06-27 08:30 UTC
### Description

Using SwipeItemView custom layout in SwipeView, the element cannot be rendered, works fine in Xamarin.Forms.

MAUI
![image](https://user-images.githubusercontent.com/42528522/175894779-51114a98-12f1-43ca-9e00-92085f4dfdc8.png)

Xamarin.Forms
![image](https://user-images.githubusercontent.com/42528522/175895139-9ce1958f-1702-42ad-9812-3417774fec55.png)

Demo:

Steps to Reproduce

### Steps to Reproduce

[MauiApp3.zip](https://github.com/dotnet/maui/files/8990048/MauiApp3.zip)

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows

### Affected platform versions

Windows 10.0.19041.0

**Comment by janseris** [comment] 2022-06-27 12:39
Reported 2.5 months ago
https://github.com/dotnet/maui/issues/6018

**Comment by rachelkang** [comment] 2022-06-27 19:47
Hi, @HenJigg - thank you for opening this issue. Please reattach your sample as a GitHub repository so that we may invetigate further. Thank you!

**Comment by HenJigg** [comment] 2022-06-28 00:23
[MauiApp3.zip](https://github.com/dotnet/maui/files/8996543/MauiApp3.zip)

**Comment by kristinx0211** [comment] 2022-06-28 06:45
using attached repro project can verified repro this issue on android 12.

**Comment by samhouts** [comment] 2022-07-21 21:24
Duplicate of #6018

**Closed** 2022-07-21 21:36 UTC
Labels: t/bug, s/duplicate 2️⃣, platform/windows 🪟, platform/android 🤖, area/SwipeView, s/verified, s/triaged, s/needs-attention
