### ISSUE TITLE
Clicked event don't fire inside of Shell.TitleView in IOS

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#11168] opened 2022-11-07 22:33 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Clicked-event-dont-fire-inside-of-Shell/10172500)._

---
[severity:I'm unable to use this version]
When i add a button inside of Shell.TitleView the Clicked Event will don’t fire.
Steps to reproduce:

Create a MAUI App in Visual Studio 2022 17.3.6 with Net 6.0

Modify code like this:
Mainpage.xaml:
```xaml
<?xml version=“1.0” encoding=“utf-8” ?>
<ContentPage xmlns=“http://schemas.microsoft.com/dotnet/2021/maui”
xmlns:x=“http://schemas.microsoft.com/winfx/2009/xaml”
x:Class=“MauiApp8.MainPage”>

<Shell.TitleView>
<Grid>
<Grid.ColumnDefinitions>
<ColumnDefinition Width=“*”/>
<ColumnDefinition Width=“Auto”/>
</Grid.ColumnDefinitions>
<Grid.RowDefinitions>
<RowDefinition Height=“{OnPlatform Android=Auto, UWP=Auto, iOS=40, MacCatalyst=Auto}”></RowDefinition>
</Grid.RowDefinitions>
<Label Text=“MAUI” FontAttributes=“Bold” Grid.Column=“0” VerticalOptions=“Center” Margin=“{OnPlatform Android=0, UWP=20, iOS=0, MacCatalyst=0}”></Label>
<StackLayout Grid.Column=“1” HorizontalOptions=“EndAndExpand” Orientation=“Horizontal” VerticalOptions=“Center” Margin=“0,0,5,0”>
<Button
Text=“Click me”
SemanticProperties.Hint=“Counts the number of times you click”
Clicked=“CounterBtn_Clicked”
HorizontalOptions=“Center” />
</StackLayout>
</Grid>
</Shell.TitleView>

<ScrollView>
<VerticalStackLayout
Spacing=“25”
Padding=“30,0”
VerticalOptions=“Center”>

     <Image
         Source="dotnet_bot.png"
         SemanticProperties.Description="Cute dot net bot waving hi to you!"
         HeightRequest="200"
         HorizontalOptions="Center" />

     <Label
         Text="Hello, World!"
         SemanticProperties.HeadingLevel="Level1"
         FontSize="32"
         HorizontalOptions="Center" />

     <Label
         Text="Welcome to .NET Multi-platform App UI"
         SemanticProperties.HeadingLevel="Level2"
         SemanticProperties.Description="Welcome to dot net Multi platform App U I"
         FontSize="18"
         HorizontalOptions="Center" />

     <Button
         x:Name="CounterBtn"
         Text="Click me"
         SemanticProperties.Hint="Counts the number of times you click"
         Clicked="OnCounterClicked"
         HorizontalOptions="Center" />

 </VerticalStackLayout>
</ScrollView>

</ContentPage>
```

Mainpage.xaml.cs:

```cs
namespace MauiApp8;

public partial class MainPage : ContentPage
{
int count = 0;

public MainPage()
{
	InitializeComponent();
}

private void OnCounterClicked(object sender, EventArgs e)
{
	count++;

	if (count == 1)
		CounterBtn.Text = $"Clicked {count} time";
	else
		CounterBtn.Text = $"Clicked {count} times";

	SemanticScreenReader.Announce(CounterBtn.Text);
}


private void CounterBtn_Clicked(object sender, EventArgs e)
{
    count++;

    if (count == 1)
        CounterBtn.Text = $"Clicked {count} time";
    else
        CounterBtn.Text = $"Clicked {count} times";

    SemanticScreenReader.Announce(CounterBtn.Text);
}
```

---
#### Feedback Bot on 10/13/2022, 06:55 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by bmclane** [comment] 2022-11-30 01:30
A Temporary Solution add negative margin: -50

`<Grid Margin="0,0,0,-50">
            <Grid.ColumnDefinitions>
                <ColumnDefinition Width="*"/>
                <ColumnDefinition Width="Auto"/>
            </Grid.ColumnDefinitions>
            <Grid.RowDefinitions>
                <RowDefinition Height="{OnPlatform Android=Auto, UWP=Auto, iOS=40, MacCatalyst=Auto}"/>
            </Grid.RowDefinitions>
            <Label Text="MAUI"
                   FontAttributes="Bold"
                   Grid.Column="0"
                   VerticalOptions="Center"
                   Margin="{OnPlatform Android=0, UWP=20, iOS=0, MacCatalyst=0}"/>
            <StackLayout Grid.Column="1"
                         HorizontalOptions="EndAndExpand"
                         Orientation="Horizontal"
                         VerticalOptions="Center"
                         Margin="0,0,5,0">
                <Button Text="Click me"
                    SemanticProperties.Hint="Counts the number of times you click"
                    Clicked="OnCounterClicked"
                    HorizontalOptions="Center" />
            </StackLayout>
        </Grid>`

**Comment by pledi** [comment] 2023-01-02 11:31
I'm also having the same problem on iOS 16.1. TapGestureRecognizer won't fire if I put them into the Shell.TitleView

**Comment by Lucasvor** [comment] 2023-02-05 18:32
I'm also having the same problem on iOS 16.2 too

**Comment by sstahurski** [comment] 2023-02-15 18:39
Same issue...Also when setting the a button in the shell.titleview, it persists to other views.
In my mind the appshell should be handling events if it is across pages...

**Comment by andrea-gavioli** [comment] 2023-04-20 11:20
Buttons on iOS are also not working on Grid and Stack layout using the Navigation page.

**Comment by AnnYang01** [comment] 2023-06-02 07:20
Verified this on Visual Studio Enterprise 17.6.0 Preview 6.0.  Repro on iOS 16.4 with below Project:
[MauiApp3.zip](https://github.com/dotnet/maui/files/11632928/MauiApp3.zip)

**Comment by MateuszLas421** [comment] 2023-06-13 21:54
same error

**Comment by rthanga1** [comment] 2023-06-14 07:11
Same thing is happening to me. I have a button in the TitleView and it works fine in Android, but in iOS click action is not firing up

**Comment by DDHSchmidt** [comment] 2023-08-23 16:33
> A Temporary Solution add negative margin to bottom: Margin="0,0,0,-50"

In my case that somewhat made the dispositioned TitleView on iOS better but didn't help with the Click event.

What I also observed:

This works
```
<Shell.TitleView>
	<Label Text="Click me">
		<Label.GestureRecognizers>
			<TapGestureRecognizer Command="{Binding SomeClickCommand}" />
		</Label.GestureRecognizers>
	</Label>
</Shell.TitleView>
````

This doesn't:
```
<Shell.TitleView>
	<HorizontalStackLayout> <!-- Can be anything: Grid, VerticalStackLayout, etc. All GestureRecognizers on child elements will now be forsaken -->
		<Label Text="Click me">
			<Label.GestureRecognizers>
				<TapGestureRecognizer Command="{Binding SomeClickCommand}" />
			</Label.GestureRecognizers>
		</Label>
	</HorizontalStackLayout>
</Shell.TitleView>
```

This is very grim, considering there's not much time left for .Net 8 GA 😕

**Comment by samhouts** [comment] 2023-09-13 18:50
Duplicate of #14931

**Closed by samhouts** 2023-09-13 18:50 UTC
Labels: t/bug, platform/iOS 🍎, area/shell 🐢, area/controls 🎮, s/verified, control-button, s/triaged
