### ISSUE TITLE
SearchBar not expanding horizontally

### ISSUE THREAD

**Issue by owl-guy** [dotnet/maui#10823] opened 2022-10-21 10:19 UTC
### Description

![image](https://user-images.githubusercontent.com/114725843/197173239-16a331e1-500c-40f0-833a-d73d5c40ce74.png)
![image](https://user-images.githubusercontent.com/114725843/197173259-b9623696-b328-4bda-a0dc-dabdefb50e94.png)
As can be seen, the SearchBar does not expand to fit its parent.

### Steps to Reproduce

1. Create a new .NET MAUI project
2. Add a SearchBar, either directly on the ContentPage or inside a Layout
3. The SearchBar will not adjust its size when no width is specified

### Link to public reproduction project repository

https://github.com/owl-guy/SearchBarExample

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11 and up

**Comment by owl-guy** [comment] 2023-01-24 13:18
Any progress here?

**Comment by Laim** [comment] 2023-02-12 11:31
Would be interesting to know if there has been any progress on this as I'm having the exact same issue.  What's odder is that the BackgroundColor does expand to fit the parent, it's just the actual SearchBar elements that don't and the only way to fix it is to hardcode a value into WidthRequest.

![oH18ngR](https://user-images.githubusercontent.com/14845036/218308284-db784db4-61b8-4a45-85b0-f089b6535664.png)

```
<StackLayout>
  <Grid RowDefinitions="*,*" ColumnDefinitions="*,*">
    <SearchBar BackgroundColor="#FBCBF3" Grid.RowSpan="2" Grid.ColumnSpan="2" HorizontalOptions="FillAndExpand"/>
  </Grid>
</StackLayout>
```

and

```
<StackLayout>
  <SearchBar BackgroundColor="#FBCBF3" HorizontalOptions="FillAndExpand"/>
</StackLayout>
```

Both have the same result - inconsistent weird padding on both sides, no expanding.  I've tried every layout possible.

**Comment by vaidotasstrazdas** [comment] 2023-05-22 08:15
One workaround is the following.
1. Put this to your view model:
```
public double ScreenWidth
{
  get
  {
    return DeviceDisplay.Current.MainDisplayInfo.Width / DeviceDisplay.Current.MainDisplayInfo.Density;
  }
}
```
It calculates the current screen width, so it is not some random value. Why division by density? Probably, more experienced users of the .NET MAUI can explain this, but it seems that logical pixels here are deduced through the relation of the pixels and density of the device. Of course, it would be much better that these relations would be encapsulated like it is done in Flutter. And finally, when the orientation of the device changes, you would need to recalculate this value again. Or you can just do not allow users changing the orientation which in my opinion would result in a quite poor UI/UX.

2. Then, use it like this:
`<SearchBar WidthRequest="{Binding ScreenWidth}" <... etc ...> />`

It is a hack, but it is more hackish for the HorizontalOptions not to work in this case as the developer would expect. Hopefully, the team fill fix it soon, and this or similar hacks will no longer be needed for us. 😀

**Comment by PramodMAUI** [comment] 2023-05-23 05:45
Hi @vaidotasstrazdas , This workaround will work if only Searchbar is used in a row. 
If we need to use a button placed with Searchbar in a row then it will not work as we are setting the entire width to SearchBar and the button will not fit in a single row with Searchbar.

Pls check attached screenshot for the design where this workaround will not work.

![Searchbar with button](https://github.com/dotnet/maui/assets/129383974/c5f819ab-2656-4e40-b7ab-e8216f8add84)

**Comment by jinxinjuan** [comment] 2023-05-30 07:12
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 1.0. Can repro on Android API-33 with sample project. 
[SearchBarExample](https://github.com/owl-guy/SearchBarExample).

**Comment by jsuarezruiz** [comment] 2023-07-12 10:30
> <StackLayout>
>   <SearchBar BackgroundColor="#FBCBF3" HorizontalOptions="FillAndExpand"/>
> </StackLayout>

Could you try again with the latest version?
<img width="504" alt="Captura de pantalla 2023-07-12 a las 12 30 05" src="https://github.com/dotnet/maui/assets/6755973/8ff4a574-3eaa-4308-b034-c329399ded13">

**Comment by tibuprophen** [comment] 2023-08-15 15:42
Not working for me with latest .NET and .NET Workloads

**Comment by nonoc** [comment] 2024-01-22 20:37
Yes I'm using NET 8 and same persistence not growing when It should be.

**Comment by alexsmi-noveo** [comment] 2024-04-11 16:53
In NET8 searchbar width issue remains

**Comment by jfversluis** [comment] 2024-04-12 07:43
@alexsmi-noveo this won't be fixed for .NET 7 so that is expected. You can indeed use the workaround.

@nonoc @FreakyAli would you be able to put together a small reproduction sample for this? The original problem should be fixed by #13716 so I'm curious why it is still not working for you.

**Comment by naxoscompact** [comment] 2024-04-26 10:54
Another solution is to bind the width of the search bar to that of another control that is resizing as it should. typically our search bar relates to another item on screen  - eg ListView or similar. Seems to be working for me
   <SearchBar HorizontalOptions="Start"
   Placeholder="Search"
   Text="{Binding SearchText, Mode=TwoWay}"
   WidthRequest="{Binding Width, Source={x:Reference ListView1}}" 
   />

**Comment by FreakyAli** [comment] 2024-04-28 10:15
@jfversluis Just saw this let me see what i can do

**Comment by FreakyAli** [comment] 2024-04-29 07:51
So I checked this and it is working now but it adds a cancel button in iOS is this the intended behavior?

You can checkout this for reproduction: https://github.com/FreakyAli/Maui.FreakyEffects/tree/grahpicsViewBug


<img src="https://github.com/dotnet/maui/assets/31090457/27bf1ab2-934e-45cb-87d7-036ae12ee966" width="250" height="550"/>

**Comment by jfversluis** [comment] 2024-05-01 19:28
@FreakyAli would you be able to check if it adds the Cancel button on Xamarin.Forms? 

Looking at [the docs](https://learn.microsoft.com/dotnet/maui/user-interface/controls/searchbar) the Cancel button is expected.

I'm leaning towards this seems to be fixed 😄

**Comment by FreakyAli** [comment] 2024-05-03 10:12
@jfversluis  As long as it matches the docs it works for me :)

**Comment by jfversluis** [comment] 2024-05-03 10:51
OK assuming this is fixed in the latest .NET MAUI versions. If you think otherwise, please open a new issue with all the details. Thanks!

**Closed by jfversluis** 2024-05-03 10:51 UTC
Labels: t/bug, platform/windows 🪟, area/layout 🔲, area/controls 🎮, s/verified, control-entry, s/triaged
