### ISSUE TITLE
Debugging/Deployment in iOS with net7.0 is broken

### ISSUE THREAD

**Issue by MaximG1234** [dotnet/maui#13340] opened 2023-02-15 02:57 UTC
### Description

Debugging/deployment of net7.0 iOS applications is currently broken. I have now replicated this bug on multiple computers with multiple devices and I believe my issues are related to the bug #11392.

I have tested using Windows 11 and Windows 10 and using an iPhone 6s and iPhone SE.

It is trivial to replicate this problem, creating a new Maui project targeting net7.0 using Visual Studio 2022 simply fails to start, if I change the exact same project to net6.0 the project starts and runs successfully.

I note that even if I don't attach the debugger the net7.0 version of the application will still not load, while the 6.0 version loads successfully.

[device log output.txt](https://github.com/dotnet/maui/files/10738856/device.log.output.txt)

Installed Workload Id      Manifest Version       Installation Source
---------------------------------------------------------------------
maui-windows               7.0.59/7.0.100         VS 17.4.33403.182  
maui-maccatalyst           7.0.59/7.0.100         VS 17.4.33403.182  
maccatalyst                16.2.1007/7.0.100      VS 17.4.33403.182  
maui-ios                   7.0.59/7.0.100         VS 17.4.33403.182  
android                    33.0.4/7.0.100         VS 17.4.33403.182  
ios                        16.2.1007/7.0.100      VS 17.4.33403.182  
maui-android               7.0.59/7.0.100         VS 17.4.33403.182  

Example of bug from VS:

https://user-images.githubusercontent.com/32756170/218912661-27fbc17c-f471-42a3-b1b1-dec341700983.mp4

Example of bug from iPhone:

https://user-images.githubusercontent.com/32756170/218914106-4dbd509c-c12b-4cfa-8f4e-d51a6b4dfef6.MP4

Example of bug resolved after changing target to net6.0 iPhone:

https://user-images.githubusercontent.com/32756170/218923665-41893695-bd3f-4546-81b2-fc1b0fdbaba0.MP4

### Steps to Reproduce

1. Create new Maui project using Visual Studio 2022 targeting net7.0. Project fails.
2. Retarget the same project to net6.0. Project starts successfully.

### Link to public reproduction project repository

https://github.com/MaximG1234/MauiBug

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

Primary test device iOS version 15.7.3

### Did you find any workaround?

NO

### Relevant log output

```shell
Log output attached
```

> VS bug [#1748012](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1748012)

**Comment by MaximG1234** [comment] 2023-02-15 23:43
I have created a VS feedback as requested: https://developercommunity.visualstudio.com/t/Maui-DebuggingDeployment-in-iOS-with-ne/10281332?port=1031&fsid=06dc898f-8fde-4b3c-a3a5-7f9ef51aaf47

**Comment by vassiliospallis** [comment] 2023-02-22 10:31
Same issue here. Not able to debug with .NET 7 on a local device/iPad. Not even able to run it without debugger. Splash screen starts and after 8 seconds watchdog kicks in and kills application.

**Comment by NousPratITPC** [comment] 2023-02-24 09:09
Any progress with this issue? This is a show stopper, we cannot even run an empty .NET 7 MAUI app on iOS devices.

**Comment by mariaghiondea** [comment] 2023-03-09 19:37
This is now tracked by https://developercommunity.visualstudio.com/t/The-app-has-been-terminated-on-local-i/10215157

**Comment by vassiliospallis** [comment] 2023-03-09 19:49
No it's not because this ticket has been closed by bots.

**Comment by mariaghiondea** [comment] 2023-03-09 19:53
Feedback item ["The app has been terminated" on local iOS device](https://developercommunity.visualstudio.com/t/The-app-has-been-terminated-on-local-i/10215157) is in an active state.

**Comment by vassiliospallis** [comment] 2023-03-09 19:55
Yes but the last bot answer is:
"I detected that this issue hasn’t received a lot of activity, votes, or comments in the past 90 days. Based on this, the issues severity and affected area, it’s my experience that this issue is unlikely to get fixed. To improve the situation, consider following best practices for quality problem reports, and giving us more details on how this issue is impacting you."
So it is like closed.

**Comment by MaximG1234** [comment] 2023-03-10 08:18
Yeah just to chime in here, I've got to say that this is wildly disappointing. I mean I get that Microsoft is a huge company and has a ton of things its got to focus on, but you literally have a new fancy framework that you're selling to everyone as the future of .NET mobile development and it currently doesn't work on iOS, meanwhile your response to the problem is 'maybe at some point we'll get to it.'

**Comment by cdavidyoung** [comment] 2023-03-27 00:59
As another data point, I just uploaded the latest version of my iOS app to the App Store and it is under review.  This is after recreating my project from scratch today starting with the standard Maui app.  I then copied and merged all my project files.  This fixed 2 other problems that I was having with the Mac version.  Now my app seems to be working perfectly in iOS, Android, and Windows.  It also works perfectly in MacCatalyst except that there is some kind of provisioning problem when I try to upload the release version to the Apple Store.

So, yes, there is still a problem uploading the Mac version but I have successfully deployed several versions of my iOS app to the App Store.  CacheAll is the name of the app if you want to check it out.

**Comment by Redth** [comment] 2023-03-29 19:14
As mentioned above, this is currently being tracked through the feedback ticket: https://developercommunity.visualstudio.com/t/The-app-has-been-terminated-on-local-i/10215157

**Closed by Redth** 2023-03-29 19:14 UTC
Labels: t/bug, area/tooling ⚙️, platform/iOS 🍎, s/move-to-vs-feedback, Area: Platform\Xamarin VS\iOS

**Comment by MaximG1234** [comment] 2023-03-30 15:15
Hi @Redth, could you please clarify? You have marked this task as complete, does that mean that it has actually been resolved? If so, is there an ETA on when it will be released? I am now running into this problem in version 6.0 also and it is a complete showstopper.

**Comment by vassiliospallis** [comment] 2023-03-30 15:19
No it's not resolved. It's being tracked in another ticket as Redth says.

**Comment by cdavidyoung** [comment] 2023-03-30 22:54
@MaximG1234 Are you using Microsoft Visual Studio Community 2022 (64-bit) - **Preview**?  I have not used the normal VS 2022 for a long time.  I have no problem creating and running the standard Maui app targeting .net 7.0 using VS2022 preview.  I can run it on all platforms, including iOS iPhone and iPad and simulations.

**Comment by MaximG1234** [comment] 2023-03-31 02:56
I am using VS 2022 Enterprise 64

**Comment by vassiliospallis** [comment] 2023-03-31 07:53
@cdavidyoung you have to try to run in to an older iOS device, such as iPad 6th gen to reproduce the problem.

**Comment by cdavidyoung** [comment] 2023-03-31 12:40
@vassiliospallis Yes.  I just ran both my app and a fresh Maui app on the iPad Pro 6th gen iOS 16.2 simulation.

**Comment by vassiliospallis** [comment] 2023-03-31 12:44
@cdavidyoung the problem lies to the physical devices and not simulator.

**Comment by cdavidyoung** [comment] 2023-03-31 13:02
@vassiliospallis @MaximG1234 I did not see that this is referring to physical devices.  I also now see that this is using Windows for debugging.  My previous app was Xamarin so I had long gotten used to testing and deploying iOS (and now MacCatalyst) from my mac.  So I can only testify that this problem does not exist on the mac side.

To be clear, I initially develop on Windows with VS2022 pre and test on Windows and Android.  I publish both from VS2022 pre.  To test and publish iOS and MacCatalyst I use VSMac.

**Comment by cdavidyoung** [comment] 2023-03-31 13:12
@vassiliospallis @MaximG1234 So I guess that begs the question as to why I don't see this problem on the mac side. My Maui app CacheAll for iPhone has been on the App Store for some time.  I am still working on getting the MacCatalyst published to the App Store but it runs fine locally on my mac.  Perhaps it is because I don't have an older iPhone to test on.  Would you like to download my CacheAll app on your older device to see if it runs?

**Comment by vassiliospallis** [comment] 2023-03-31 13:16
@cdavidyoung yes sure! I will download it, run it and let you know.

**Comment by cdavidyoung** [comment] 2023-03-31 13:31
Here is the beginning of my .csproj file.  Does that answer your question and Maui 7?  I am not doing anything with the splash screen other than enable it.  The splash screen appears on iOS and Android but not on Windows or Mac.
```
<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net7.0-maccatalyst;net7.0-ios;net7.0-android</TargetFrameworks>
		<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net7.0-windows10.0.19041.0</TargetFrameworks>
		<!-- Uncomment to also build the tizen app. You will need to install tizen by following this: https://github.com/Samsung/Tizen.NET -->
		<!-- <TargetFrameworks>$(TargetFrameworks);net7.0-tizen</TargetFrameworks> -->
		<OutputType>Exe</OutputType>
		<RootNamespace>jiffyLog</RootNamespace>
		<UseMaui>true</UseMaui>

```

**Comment by cdavidyoung** [comment] 2023-03-31 14:16
@vassiliospallis @MaximG1234 I do all my coding and initial testing on VS 2022 pre (Windows) before switching to my mac for iOS and MacCatalyst testing.  I have not tested the empty template of MAUI 7 (I assume the button click app) on my iPhone 12 Pro because that requires the hassle of provisioning the app to run on that phone.  I have friends who have installed CacheAll on their iPhones so I will ask them if they have an older model.

**Comment by vassiliospallis** [comment] 2023-03-31 14:21
@cdavidyoung no hassle, you open .csproj and you set the name of the company the same with your other provisioning project eg com.COMPANYNAME.mauitest. Then you go to properties and you press the link "Configure automatic provisioning" and it will do the necessary actions to deploy it to the device. It's very simple and straightforward. Your app can't help because it runs everywhere even in older iPhones so this info will not help to solve the problem imho.

**Comment by MaximG1234** [comment] 2023-03-31 16:11
@cdavidyoung Hey mate, just for your info I can confirm that your application functions fine on my dev device which is an iPhone 6s running 15.7.3 (a very old device)

**Comment by cdavidyoung** [comment] 2023-03-31 16:20
@vassiliospallis By company do you mean the ApplicationId?

`<ApplicationId>com.companyname.mauiapp_ffmpegcore_test</ApplicationId>`

**Comment by vassiliospallis** [comment] 2023-03-31 16:39
@cdavidyoung yes exactly!

**Comment by vassiliospallis** [comment] 2023-03-31 16:40
> @vassiliospallis I'll be happy to help out if I can. Are you referring to attaching my iPhone to my Windows machine and deploying from VS 2022 pre? And does it matter that I don't have an older device to test with?

No it matters, I thought that you have access to an old iOS device. Never mind, thanks a lot for your kind intentions to help, I appreciate that!

**Comment by angelru** [comment] 2023-04-11 10:05
My app just stops after the splash screen, I'm not getting any exceptions or anything, I'm using iOS hot reload without a connected mac. it's a mistake right?

**Comment by MrThree3** [comment] 2023-05-11 07:54
Hi, I have the same problem, does anyone have an update??

**Comment by vassiliospallis** [comment] 2023-05-11 08:02
> Hi, I have the same problem, does anyone have an update??

No, MS doesn't care at all.
