### ISSUE TITLE
CSS hot reload fails in .NET MAUI Blazor app after 2nd edit

### ISSUE THREAD

**Issue by danroth27** [dotnet/maui#9197] opened 2022-08-04 18:52 UTC
Repro steps:

- VS: 17.3 P6
- Create a new .NET MAUI Blazor app
- Edit app.css
- Save to hot reload the change
- Edit app.css again

Expected result: 2nd edit is successfully applied

Actual result:

- No UI update
- Error in Hot Reload output window: "Applying changes to app.css failed. The process cannot access the file 'C:\Users\user\source\repos\MauiApp1\MauiApp1\wwwroot\css\app.css' because it is being used by another process."

Process Explorer shows that the app is holding onto the file:
![image](https://user-images.githubusercontent.com/1874516/182930370-5336a764-5a8d-47fd-a0d0-a51394dc75b5.png)

@TanayParikh @mkArtakMSFT @mcumming 

This issue is similar to the [CSS hot reload issue with WinForms](https://github.com/dotnet/maui/issues/7479), but the behavior is different and the way Blazor handles the file stream is different on .NET MAUI which should avoid the [WebView2 locking issue](https://github.com/MicrosoftEdge/WebView2Feedback/issues/2513). In this case it seems like Blazor or .NET MAUI may be the culprit.

**Comment by TanayParikh** [comment] 2022-08-04 19:28
This may just require closing out the `content` stream after it's been copied:

https://github.com/dotnet/maui/blob/d94a1ad7d8d8d8e2b2bf1a46009955f20762a638/src/BlazorWebView/src/Maui/Windows/WinUIWebViewManager.cs#L86-L91

**Comment by TanayParikh** [comment] 2022-08-04 22:20
@danroth27 I'm unable to repro this, did you have any other steps you'd recommend trying?

<img width="849" alt="image" src="https://user-images.githubusercontent.com/14852843/182962522-df54cd85-fc2a-4be3-bccd-74662bc0526f.png">

**Comment by TanayParikh** [comment] 2022-08-04 23:11
I ended up being able to repro using a clean `maui-blazor` app. Above screenshot is using the MAUI sample app in the `maui` repo. 

I think this'll be resolved if we can resolve https://github.com/dotnet/maui/issues/9206, at which point, we'll likely end up running into https://github.com/MicrosoftEdge/WebView2Feedback/issues/2513 as we'd no longer be copying the content stream into a separate memory stream. Not the ideal resolution, but it would be good to get these related but different issues into the same "base" issue.

**Comment by TanayParikh** [comment] 2022-08-08 21:19
https://github.com/dotnet/maui/pull/9254 has been merged. Once the builds for that are available, it would be good to revalidate this.

**Comment by TanayParikh** [comment] 2022-08-15 23:30
> it would be good to revalidate this.

Things should've now propagated. I've requested revalidation for this scenario using the latest (internal) builds.

**Comment by anirugu** [comment] 2022-08-16 05:45
I tried to build a project in maui-blazor in 17.4 Preview 1. Changing CSS doesn't reflect in the running app. I am not sure if it's happening after the 2nd exit.

This is the stack track I receive from VS

StreamJsonRpc.RemoteInvocationException: The solution does not contain the specified document.
   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__143`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.CodeAnalysis.Remote.BrokeredServiceConnection`1.<TryInvokeAsync>d__20`1.MoveNext()
RPC server exception:
System.InvalidOperationException: The solution does not contain the specified document.
      at Microsoft.CodeAnalysis.Shared.Extensions.ISolutionExtensions.<GetRequiredDocumentAsync>d__9.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.EditAndContinue.RemoteEditAndContinueService.<>c__DisplayClass9_0.<<GetDocumentDiagnosticsAsync>b__0>d.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at System.Threading.Tasks.ValueTask`1.get_Result()
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.<>c__DisplayClass10_0`1.<<RunWithSolutionAsync>g__TryFastGetSolutionAndRunAsync|0>d.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at System.Threading.Tasks.ValueTask`1.get_Result()
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.<RunWithSolutionAsync>d__10`1.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at System.Threading.Tasks.ValueTask`1.get_Result()
      at Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.<RunWithSolutionAsync>d__11`1.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at System.Threading.Tasks.ValueTask`1.get_Result()
      at Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.<RunServiceImplAsync>d__14`1.MoveNext()

**Comment by TanayParikh** [comment] 2022-08-16 15:21
@anirugu that appears to be a different issue. The issue we're discussing here doesn't explicitly throw an exception as far as I know. Based on the stack trace you provided, I suspect you may be running into https://github.com/dotnet/sdk/issues/26762 which we're in the middle of patching.

**Comment by TanayParikh** [comment] 2022-08-16 23:40
> > it would be good to revalidate this.
> 
> Things should've now propagated. I've requested revalidation for this scenario using the latest (internal) builds.

Unfortunately, the issue seems to continue to reproduce despite the recent changes.

fyi/ @javiercn

**Comment by TanayParikh** [comment] 2022-08-16 23:40
Adding to RC2 milestone.

**Comment by TanayParikh** [comment] 2022-08-16 23:47
@javiercn could this have any relation to https://github.com/dotnet/sdk/issues/26762 / https://github.com/dotnet/sdk/pull/26765 / https://github.com/dotnet/sdk/pull/27102?

@danroth27 just confirming your issue here was on .NET 6?

**Comment by TanayParikh** [comment] 2022-08-31 21:41
Reopening as @jinzhao1127 is still repro'ing this issue. https://github.com/dotnet/maui/pull/9645 should've resolved this. Specifically:

https://github.com/dotnet/maui/pull/9645/files#diff-5cf51db2a43b59a7b8ce04f82cc5e21e2e57a2eeba4b02b5aae132f1dc086820R70

**Comment by TanayParikh** [comment] 2022-08-31 21:43
I haven't been able to repro this given I'm running into https://github.com/aspnet/AspNetCore-ManualTests/issues/1525 first. Will have to hold off on further investigation here till https://github.com/aspnet/AspNetCore-ManualTests/issues/1525 is resolved.

**Comment by TanayParikh** [comment] 2022-10-13 21:05
@mcumming pointed out the following discrepency:

<img width="922" alt="image" src="https://user-images.githubusercontent.com/14852843/195710123-168dab50-4441-4183-a419-4c29036e6977.png">

vs. in the VS Hot reload output:

```log
14:01 46.51 MauiApp14: [Warning] Endpoint has unsupported platform WinUI for .NET Hot Reload, skipping.
14:01 46.57 MauiApp14: Hot Reload session started
14:01 55.73 MauiApp14: Applying the changes to app.css to the running application
14:02 00.63 MauiApp14: Applying the changes to app.css to the running application
14:02 03.57 MauiApp14: Applying changes to app.css failed. The process cannot access the file 'C:\Users\taparik\source\repos\MauiApp14\MauiApp14\wwwroot\css\app.css' because it is being used by another process.
```

Notice the difference in path.

**Comment by TanayParikh** [comment] 2022-10-13 23:34
Making this change:

<img width="922" alt="image" src="https://user-images.githubusercontent.com/14852843/195728783-eae97c51-ce26-499e-a134-802b0ca26773.png">

here:

https://github.com/dotnet/maui/blob/8a9088f1e433f3f35915bf5debf0426fe21c42d0/src/BlazorWebView/src/Maui/Windows/WinUIWebViewManager.cs#L105-L113

results in Process Explorer reporting no processes holding the `app.css` handle:

<img width="922" alt="image" src="https://user-images.githubusercontent.com/14852843/195728893-28774f92-a469-44d0-8243-82ae2007933c.png">

However, hot reload still fails on:

```
16:27 36.93 MauiApp14: Applying changes to app.css failed. The process cannot access the file 'C:\Users\taparik\source\repos\MauiApp14\MauiApp14\wwwroot\css\app.css' because it is being used by another process.
```

Given this is a distinctly different file from what was being reported by Process Explorer (see above post), I think we may actually have two separate bugs here. One would be resolved by the code change above, while there appears to be another bug that's resulting in the underlying failed hot reload issue persisting.

Note, @MackinnonBuck was able to confirm, it does in fact repro on Android (thanks Mackinnon!). So this definitely doesn't appear to be platform specific. 

@mcumming why is [this](https://github.com/xamarin/UITools/blob/a856cfc4d9c9cc546722ab4ad1d4e7bc601bfa53/HotReload/Source/Microsoft.VisualStudio.HotReload/MauiHotReloadStaticAssetApplier.cs#L71) reading from the project folder, whereas we're performing hot reload from the packaged app (screenshot below). (cc/ @javiercn as I believe he may have worked with packaging in this context).

<img width="1607" alt="image" src="https://user-images.githubusercontent.com/14852843/195729536-0d802433-fb15-40a3-b6ec-e069f974547b.png">

**Comment by mcumming** [comment] 2022-10-14 03:50
@TanayParikh For MAUI we read from the project folder because that is the file that the user is modifying. The instance of that file in the packaged folder is not updated that I know of after the initial build. That is why for content files HotReload sends the entire contents of the file to the agent in the running application.

**Comment by TanayParikh** [comment] 2022-10-14 07:31
Thanks for clarifying. What's unclear in that case is what is actually holding on to the file handle. Nothing shows up in process explorer. 

Did you have a chance to experiment with alternatives to the current File.ReadAllBytes in UITools? Perhaps we could try to open a file stream (with file sharing explicitly configured) and then copy to a memory stream to see if that potentially results in different behavior?

**Comment by mcumming** [comment] 2022-10-14 13:55
Yes, I switched the `File.ReadAllBytes` to explicitly openening the file with `using var stream = new (fullPathToCssFile, FileMode.Open, FileAccess.ReadWrite, FileShare.Read);`, unfortunately it hasn't had an effect on this issue.

**Comment by TanayParikh** [comment] 2022-10-26 23:54
We're trying out a temporary mitigation of this within VS at the moment.

**Comment by mkArtakMSFT** [comment] 2023-02-02 19:13
Closing this, as a mitigation from @mcumming has landed already.
Basically, the mitigation is a retry on the VS side, which seems to work. we still don't know why exactly this was happening, but to timebox the investigation going to move forward with the mitigation for now. Michael will file a follow-up backlog issue to track the underlying issue for future resolution.

**Closed by mkArtakMSFT** 2023-02-02 19:13 UTC
Labels: t/bug, area/blazor 🕸️, discussed
