### ISSUE TITLE
Cursor jumps to start when writing on Entry (Android, TextTransform)

### ISSUE THREAD

**Issue by jsendra-verin** [dotnet/maui#12411] opened 2023-01-04 16:22 UTC
### Description

When applying a TextTransform=Uppercase modifier to entries, the cursor jumps to the start after each lowercase letter is typed.

When writing with a physical keyboard in Windows, it works just fine.

I have tried multiple Android devices and keyboards.

Haven't tried on Apple devices.

Similar issues:

https://github.com/dotnet/maui/issues/2798
https://github.com/dotnet/maui/issues/5401

### Steps to Reproduce

1. Create .NET MAUI (.net 7.0) project in Visual Studio
2. Add Entry with the Uppercase TextTransform
3. Run in Android device or emulator
4. Type in the entry

### Link to public reproduction project repository

https://github.com/jsendra-verin/MauiBugDemo

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Apparently every Android version

### Did you find any workaround?

Transforming the entry input via code after confirmation

**Comment by rachelkang** [comment] 2023-01-04 19:08
Duplicate of #11313

**Closed by rachelkang** 2023-01-04 19:08 UTC
Labels: t/bug, area/controls 🎮
