### ISSUE TITLE
Editor in .Net MAUI does not take full width when inside a stack/grid layout

### ISSUE THREAD

**Issue by Awesomer9561** [dotnet/maui#8232] opened 2022-06-22 12:39 UTC
### Description

I am creating a notes app where I have an editor.
But whenever I am trying to use the editor it does not take full width even after specifying the width request.
`<Frame
                                Margin="0,0,0,60"
                                HeightRequest="120"
Padding="0">
                                <Editor
                                    HorizontalOptions="Start"
                                    WidthRequest="200"
                                    Placeholder="Notes"/>
                            </Frame>`  

This frame is inside a vertical stack layout.

### Steps to Reproduce

1. Create a vertical stack layout and insert a frame, inside that place an editor and specify the height request. 
2. It will automatically take the cursor to the next line without even filling the whole line.

### Version with bug

6.0.400 (current)

### Last version that worked well

6.0.312

### Affected platforms

iOS, Android

### Affected platform versions

iOS 15, Android API 30, 31

**Comment by kristinx0211** [comment] 2022-06-23 07:33
@Awesomer9561 hi, I am not repro this issue, Entered characters can fill the entire editor(`WidthRequest="200"`) and then wrap in the video. let me know if I miss something from my code and video. 
```
    <VerticalStackLayout>
        <Frame Margin="0,0,0,60" HeightRequest="120" Padding="0">
            <Editor HorizontalOptions="Start" WidthRequest="200" Placeholder="Notes" BackgroundColor="Green"/>
        </Frame>
    </VerticalStackLayout>
```

**Comment by kristinx0211** [comment] 2022-06-23 08:10
@Awesomer9561 yes, remove it and see the video:
https://user-images.githubusercontent.com/99457000/175249634-c0b34d91-ead3-4eb0-a3f3-4db711e09f35.mp4

**Comment by Awesomer9561** [comment] 2022-06-25 10:34
> @Awesomer9561 yes, remove it and see the video, so you mean when the editor doesn't set the height it doesn't fill the entire frame? https://user-images.githubusercontent.com/99457000/175249634-c0b34d91-ead3-4eb0-a3f3-4db711e09f35.mp4

Hi I am saying that if I put the editor inside a frame it does not automatically take up width of the parent.

**Comment by kristinx0211** [comment] 2022-06-29 09:43
> > @Awesomer9561 yes, remove it and see the video, so you mean when the editor doesn't set the height it doesn't fill the entire frame? https://user-images.githubusercontent.com/99457000/175249634-c0b34d91-ead3-4eb0-a3f3-4db711e09f35.mp4
> 
> Hi I am saying that if I put the editor inside a frame it does not automatically take up width of the parent.

yes, that's true.

**Comment by kristinx0211** [comment] 2022-06-29 09:46
re-verified this issue on android. the editor inside a frame does not automatically take up width of the parent.

**Comment by mobycorp** [comment] 2022-06-29 16:09
I don't understand why this is so difficult to reproduce. I am trying to do the same thing in a Windows app and the Editor simply will not size according to wishes. I have found the width of the control does conform to the width of the placeholder text, but if you set the width to 100, 1000 or not at all, the size of the control does not change. I am expecting the width of the control to consume whatever horizontal space it can, and it simply isn't.

**Comment by mobycorp** [comment] 2022-06-29 16:12
Also, I have reported content inside of a frame (which I am not doing in my use of the editor control).  The frame is broken and has been since I've tried to use it. I am convinced the issue is a bug in the way it does its layout calculations.

**Comment by ShiiikK** [comment] 2022-08-06 06:51
please fix this. Entry just dont take full width

**Comment by jaworekplay** [comment] 2022-10-10 14:36
For anyone else looking for a solution to this. If you set `AutoSize="TextChanges"` then editor stretches all across the screen. It will not help if your UI is customised but at least its a starting point.

**Comment by radiolondra** [comment] 2022-10-13 13:51
I can confirm that Entry control (and whatever else control) seems to be unable to stretch to the full width.
Things get tragic (and comical) when you want to place, for example, an Entry control and a button on the same row of a grid, as in the following XAML code:

_MainPage.xaml_
```
......
<Grid
        x:Name="MainGrid"
        Margin="0,0,0,0"
        RowDefinitions="Auto,*">
        ColumnDefinitions="*,100"
        
        <Entry
            Grid.Row="0"
            Grid.Column="0"            
            x:Name="searchbox"            
            Placeholder="Paste a link or type items to search"
            Text="{Binding SearchText}"/>

        <Button    
            Grid.Row="0"
            Grid.Column="1"
            Margin="5,0,0,0"
            x:Name="StartSearchBtn"
            Text="Search"
            WidthRequest="100"
            SemanticProperties.Hint="Start the search"
            Clicked="StartSearchBtn_Clicked"/>
      ....
</Grid>
```
**The result will be:** an Entry control that takes on the initial width needed to show the defined Placeholder text (immediately reset by typing the first character) followed by a button that will go back and forth as you write/delete something in the text box. 

Frankly unacceptable. 
And it is not important what control you use to group the 2 controls (Grid, some kind of stack layout..) the result will be always the same. 
I don't understand how simple and basic things like these have to become complicated in MAUI.

**The only way I found to overcome this empasse** was to use the `SizeChanged `event in the `MainPage`, take the width of the page at that instant and assign it to a property (`PageWidth`) defined in the view model of the MainPage. In XAML, I used this property, decremented by the horizontal space occupied by the button and margins, and assigned it to the grid column containing the Entry control (and all the other controls).

```
<Grid
        x:Name="MainGrid"
        Margin="0,0,0,0"
        RowDefinitions="Auto,*">
        <Grid.ColumnDefinitions>
            <ColumnDefinition Width="{Binding PageWidth}"/>
            <ColumnDefinition Width="100"/>
        </Grid.ColumnDefinitions>
                
        <Entry
            Grid.Row="0"
            Grid.Column="0"            
            x:Name="searchbox"            
            Placeholder="Paste a link or type items to search"
            Text="{Binding SearchText}"/>

        <Button    
            Grid.Row="0"
            Grid.Column="1"
            Margin="5,0,0,0"
            x:Name="StartSearchBtn"
            Text="Search"
            WidthRequest="100"
            SemanticProperties.Hint="Start the search"
            Clicked="StartSearchBtn_Clicked"/>
      
        <CollectionView
            Margin="0,0,0,0"
            Grid.Row="1"
            Grid.ColumnSpan="2"            
            Scrolled="List_Scrolled"
            x:Name="ListResults"            
            ItemsSource="{Binding Results}">
.....
```
In _MainPageViewModel.cs_:

```
....
private double _pageWidth;
.....
public double PageWidth
{
    get => _pageWidth;
    set => SetProperty(ref _pageWidth, value);
}
```

In _MainPage.xaml.cs_:
```
.....
public MainPage()
{
  InitializeComponent();
  BindingContext = new MainPageViewModel();
  SizeChanged += MainPage_SizeChanged;
}

private void MainPage_SizeChanged(object sender, EventArgs e)
{
  Debug.WriteLine($"Page width: {this.Width}");
  var vm = BindingContext as MainPageViewModel;
  vm.PageWidth = this.Width - 120; // 120 here is the width of the button (100) + margins. TODO: find a not so static way.
 }

```
[As shown in this video](https://www.screencast.com/t/NDmfBwvzB), now the result is at least acceptable.

**Comment by tednyberg** [comment] 2022-10-15 15:02
As a workaround, I set `AutoSize="TextChanges"`. Although the `Editor` itself will be no wider than its content, I can "fix" that visually by surrounding it with a `Frame` or `Border` element.

**Closed** 2022-11-16 19:21 UTC
Labels: t/bug, area/layout 🔲, area/controls 🎮, s/verified, control-entry, s/triaged
