### ISSUE TITLE
OnIdiom issue with Windows

### ISSUE THREAD

**Issue by davidortinau** [dotnet/maui#5014] opened 2022-03-02 15:52 UTC
### Description

When running this on Windows I get a RTE stating the Span value is invalid. 

https://github.com/microsoft/dotnet-podcasts/blob/main/src/Mobile/Pages/DiscoverPage.xaml#L34

```xaml
<CollectionView.ItemsLayout>
                <GridItemsLayout Orientation="Vertical"
                                 Span="{OnIdiom Phone=2, Tablet=3, Desktop=3}"
                                 HorizontalItemSpacing="5"
                                 VerticalItemSpacing="5" />
            </CollectionView.ItemsLayout>
```

Android works fine.

### Steps to Reproduce

Run the podcast app on Windows. The first page is that one and will RTE

### Version with bug

Release Candidate 1

### Last version that worked well

Preview 13 (current)

### Affected platforms

Windows

### Affected platform versions

Win11

### Did you find any workaround?

Either hardcode a value in the Span or add a Default so it falls through.

**Comment by Amir-Care** [comment] 2022-03-03 02:32
Thank you so much for your bug report! Unfortunately, we cannot reproduce your issue with the information above, What means about "RTE" ? could you provide  issue  screenshots  or  more details that we can reproduce your issue? That should greatly speed up the process, thanks!

**Comment by shimingsg** [comment] 2022-03-03 10:44
verified repro with 17.2.0 Preview 2.0 [32302.601.main] on Windows

**Comment by StephaneDelcroix** [comment] 2022-03-23 07:39
what's the DeviceIdiom of the targetedPlatform at runtime ?

**Comment by mattleibow** [comment] 2022-05-02 15:19
I cannot reproduce this on main, and probably was fixed in https://github.com/dotnet/maui/commit/78647901e969de5c948cb9e87eacd055ad4b9604 on main, but really in https://github.com/dotnet/maui/pull/4982 

```xaml
<ContentPage
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    x:Class="Maui.Controls.Sample.MainPage"
    xmlns:local="clr-namespace:Maui.Controls.Sample"
    Title="Gallery">
    <CollectionView ItemsSource="{Binding PodcastsGroup}"
                    Margin="10,50,10,0"
                    SelectionMode="None"
                    IsGrouped="True">
        <CollectionView.ItemsLayout>
            <GridItemsLayout Orientation="Vertical"
                             Span="{OnIdiom Phone=2, Tablet=3, Desktop=3}"
                             HorizontalItemSpacing="5"
                             VerticalItemSpacing="5" />
        </CollectionView.ItemsLayout>
        <CollectionView.ItemTemplate>
            <DataTemplate>
                <Label Text="{Binding .}" />
            </DataTemplate>
        </CollectionView.ItemTemplate>
        <CollectionView.GroupHeaderTemplate>
            <DataTemplate x:DataType="{x:Null}">
                <Label Text="{Binding Name}" FontSize="32" />
            </DataTemplate>
        </CollectionView.GroupHeaderTemplate>
    </CollectionView>
</ContentPage>
```

```cs
using System.Collections.Generic;

namespace Maui.Controls.Sample;

public partial class MainPage
{
	public MainPage()
	{
		InitializeComponent();
		BindingContext = this;
	}
	public Items[] PodcastsGroup => new[]
	{
		new Items
		{
			Name = "Small",
			Children={ "Rat", "Mouse", "Bird", "Fish", "Carrot"}
		},
		new Items
		{
			Name = "Big",
			Children={ "Cat", "Dog", "Rabbit", "Car", "Jet" }
		},
		new Items
		{
			Name = "Awesome",
			Children={ "Code", "School", "Not doing drugs" }
		},
	};
}
public class Items : List<string> {
	public string Name { get; set; }
	public List<string> Children => this;
}
```

**Comment by mattleibow** [comment] 2022-05-02 16:27
Tested the dotnet podcasts app and it no longer crashes.

**Closed by mattleibow** 2022-05-02 16:27 UTC
Labels: t/bug, area/Xaml </>, platform/windows 🪟, p/1, s/verified
