### ISSUE TITLE
[Bug] Using hyphens in your 'dotnet new maui' folder generates incorrect path within solution

### ISSUE THREAD

**Issue by mattkenefick** [dotnet/maui#1799] opened 2021-07-24 15:06 UTC
### Description

My solution for project `test-project` failed to load correctly because the generated path by `dotnet new maui` was incorrect. The folders generated were `test-project`, but the solution was looking for `test_project`.

Visual  Studio 2022 Error:

```
D:\Development\Technologies\MAUI\test-project\test_project\test_project.csproj : error  : The project file cannot be found.

D:\Development\Technologies\MAUI\test-project\test_project.WinUI\test_project.WinUI.csproj : error  : The project file cannot be found.
```

Actual path:

```
PS D:\Development\Technologies\MAUI\test-project\test-project> ls

    Directory: D:\Development\Technologies\MAUI\test-project\test-project

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----           7/24/2021 10:52 AM                Platforms
d----           7/24/2021 10:52 AM                Resources
-a---           7/24/2021 10:52 AM           1290 App.xaml
-a---           7/24/2021 10:52 AM            353 App.xaml.cs
-a---           7/24/2021 10:52 AM           1948 MainPage.xaml
-a---           7/24/2021 10:52 AM            349 MainPage.xaml.cs
-a---           7/24/2021 10:52 AM            536 Startup.cs
-a---           7/24/2021 10:52 AM           1543 test-project.csproj
```

`test-project.sln` (truncated)

```
Microsoft Visual Studio Solution File, Format Version 12.00
# Visual Studio Version 16
VisualStudioVersion = 16.0.31220.234
MinimumVisualStudioVersion = 10.0.40219.1
Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "test_project", "test_project\test_project.csproj", "{69EFB762-AAB1-48D9-B4A1-7D0E620BC4D5}"
EndProject
Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "test_project.WinUI", "test_project.WinUI\test_project.WinUI.csproj", "{CE8D7017-0FEC-4939-93F5-E42553509AF0}"
EndProject
```

The issue goes beyond just filenames such that it affects files like `App.xaml` for instance:

```
<maui:MauiWinUIApplication
    x:Class="test_project.WinUI.App"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:maui="using:Microsoft.Maui"
    xmlns:local="using:test_project.WinUI">
 ```

### Steps to Reproduce

1. Create a path with hyphens on a Windows 11 machine
2. Run `dotnet new maui`
3. Attempt to open solution in Visual Studio 2022 Preview

### Expected Behavior

Project launches as expected.

### Actual Behavior

Dialog prompt saying:

"One or more projects in the solution were not loaded correctly.
Please see the Output Window for details."

### Basic Information

- Version with issue:

```
 dotnet --version
6.0.100-preview.6.21355.2
```
- Last known good version: Unknown
- IDE: Visual Studio 2022

### Workaround

A. Do not use hyphens in your folder name
B. Change your subfolder + *.csproj names to match underscore

**Comment by jfversluis** [comment] 2021-08-30 14:40
Duplicate of #1187

**Closed by jfversluis** 2021-08-30 14:40 UTC
