### ISSUE TITLE
Tabbar limits number of pages in stack when 1st page is launched from "more" part of Tabbar (more than 4 menu items in a tabbar)

### ISSUE THREAD

**Issue by SorenBech2** [dotnet/maui#24521] opened 2024-08-29 19:38 UTC
### Description

When a page is pushed to the stack from a 5th menu point (or more) in a Tabbar, it is not possible to add another page to the stack. No exceptions, no errors - execution just stops! If the same page is pushed (GotoAsync()) from a menu point 1-4 on the tabbar no issue. The issue exist on IOS, not on Android nor Windows. 
In addition, when "go back" is pushed, the label in tabbar is overwritten with the name of the page when returned to mainpage!

### Steps to Reproduce

Use attached repro. Deploy on IOS and select a Tab "Working 1".  Press "Go to second page"., then press "Go back". Everything works fine.
Select Tab "Not working 1". Press "Go to second page" Nothing happens. The press < More. Observer Tab label has changed from "not working 1" to SecondPage.

### Link to public reproduction project repository

https://github.com/SorenBech2/TestPage

### Version with bug

8.0.82 SR8.2

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

IOS 17.6.1

**Comment by PureWeen** [comment] 2024-08-29 22:35
Duplicate of #18193

**Closed by PureWeen** 2024-08-29 22:35 UTC
Labels: t/bug, platform/iOS 🍎

**Comment by SorenBech2** [comment] 2024-08-30 04:20
I fail to see thst hese are dublicates. 18193 does not contain the issue of bot being able til push more than one oage to the stack!

Med venlig hilsen / Best regards

Søren Bech

________________________________
