### ISSUE TITLE
[iOS] Button FontAttributes not working 

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#12053] opened 2022-12-13 13:27 UTC
### Description

Setting the Button FontAttributes property is not working.

```
<Button
    FontAttributes="None"
    Text="B13 (None)"/>
<Button
    FontAttributes="Italic"
    Text="B13 (Italic)"/>
<Button
    FontAttributes="Bold"
    Text="B13 (Bold)"/>
```

![image](https://user-images.githubusercontent.com/6755973/207331042-64d35e21-1ac9-4d70-b961-f13d89b4a1f6.png)

### Steps to Reproduce

1. Download or sync https://github.com/jsuarezruiz/dotnet-maui-testing-playground
2. Launch the App and navigate to the Button test cases.
3. The B13 test case validating the FontAttributes property is failing.

### Link to public reproduction project repository

https://github.com/jsuarezruiz/dotnet-maui-testing-playground

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 16, Catalyst with macOS Ventura

**Comment by mattleibow** [comment] 2022-12-13 19:39
@jsuarezruiz is that repo public? I get a 404.

**Comment by mattleibow** [comment] 2022-12-13 19:40
Also, is the font the default OS or a custom font. I think iOS is limited in that it can "force" italic like android and windows.

**Comment by jinxinjuan** [comment] 2023-06-02 07:28
Verified this issue with Visual Studio 17.7.0 Preview 1.0. Can repro on iOS platform with sample project.
[dotnet-maui-testing-playground](https://github.com/jsuarezruiz/dotnet-maui-testing-playground)

**Comment by mattleibow** [comment] 2023-10-09 14:43
Duplicate of https://github.com/dotnet/maui/issues/1018

**Comment by mattleibow** [comment] 2023-10-09 14:45
The font is the OpenSans fond from a resource which does not have "bold" support. We need #1018 to switch the font when we set bold and iOS can't "force bold" in fonts.

**Closed** 2023-10-09 14:45 UTC
Labels: t/bug, platform/iOS 🍎, area/controls 🎮, s/verified, control-button, s/triaged, scenario-day
