### ISSUE TITLE
Blazor App Menu not rendered in IOS

### ISSUE THREAD

**Issue by ltemimi** [dotnet/maui#7600] opened 2022-05-30 08:14 UTC
### Description

I have created a MAUI blazor app it renders OK on android, windows and IOS Simulators. on IOS Devices however, the web page renders but not the menu.

### Steps to Reproduce

1 - Create a blazor MAUI app
2 - deploy to Androind and Windows, IOS Simulators and observe all works OK
3 - Deploy to IOS (iPhone or iPad observe the page diplays but the menu is missing

### Version with bug

6.0 (current)

### Last version that worked well

Preview 13

### Affected platforms

iOS

### Affected platform versions

Windows server 2022

### Did you find any workaround?

No

**Comment by ToolmakerSteve** [comment] 2022-05-31 01:05
* The devices: what iPhone/iPad models, and iOS versions, did you test?
* On a phone (portrait orientation), is the "hamburger icon" for the menu there? If it is, and you click on it, menu does not appear?

**Comment by mkArtakMSFT** [comment] 2022-05-31 16:45
@ltemimi can you share a screenshot of how it shows up on your iPhone and share?
Also, just to confirm something, we assume that you're using the default Blazor MAUI application without any changes, haven't you?

**Comment by ltemimi** [comment] 2022-05-31 18:46
Hi, 
Thanks for the help, I have now uninstalled and reinstalled visual studio 2022 latest and create a defaul dot net MAUI Blazor app and the issue remains
 Summary: Devices Android OK , Windows OK and IOS Simulators OK
device Iphone and IPad no menu on protrait or landscape
Pictures attached
Thanks
<img width="693" alt="IOSSimulator" src="https://user-images.githubusercontent.com/5493492/171262072-bc676a8b-8fd2-4aa7-b37e-12cd1875fe89.png">
![Iphone7](https://user-images.
<img width="885" alt="Windows" src="https://user-images.githubusercontent.com/5493492/171262113-90c5b31b-16f2-4da6-84f3-371bbf27e0f1.png">
<img width="212" alt="defaultMaui-Project" src="https://user-images.githubusercontent.com/5493492/171262530-89907a75-edb7-4f94-a312-3b573fc5c29b.png">

githubusercontent.com/5493492/171262095-bb1ebeea-a92a-46b9-8b1d-b4273701ff16.JPG)

**Comment by ltemimi** [comment] 2022-06-25 21:54
I still have the issue, is it going to be actioned?

**Comment by wilcot1989** [comment] 2022-08-06 23:24
Does anyone already have a solution for this problem? Same problem here.

**Comment by MackinnonBuck** [comment] 2022-08-24 23:50
Would anyone in this thread experiencing this bug be able to produce a binlog for us to investigate? See [this comment](https://github.com/dotnet/maui/issues/8701#issuecomment-1203603510) as an example for how to do this.

If you're having trouble getting things to work from the command line, you can use this [this VS extension](https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.ProjectSystemTools2022) to generate binlogs.

 Thanks!

**Comment by coffeymatt** [comment] 2022-10-05 16:02
Same for me

**Comment by MackinnonBuck** [comment] 2022-10-06 17:54
Dupe of https://github.com/dotnet/maui/issues/7468

**Closed by MackinnonBuck** 2022-10-06 17:54 UTC
Labels: t/bug, area/blazor 🕸️, s/needs-attention, investigate
