### ISSUE TITLE
Can't connect Visual Studio with Mac due to microsoft.net.sdk.ios.manifest v16.4.7098 missing from nuget.org

### ISSUE THREAD

**Issue by andyzukunft** [dotnet/maui#17077] opened 2023-08-29 19:42 UTC
### Description

Using the newest Visual Studio v17.7.3 it is not possible to connect Visual Studio to Mac. Trying to install the iOS workoads failed as microsoft.net.sdk.ios.manifest v16.4.7098 is missing from nuget.org (https://www.nuget.org/packages/microsoft.net.sdk.ios.manifest-7.0.100/). At the time of this writing version is v16.4.7090 is the most up to date nuget package.

I was running Visual Studio v17.7.2 earlier without error.

![grafik](https://github.com/dotnet/maui/assets/26144024/29407054-d570-446b-8e1d-3e33311a89aa)

### Steps to Reproduce

1. Install Visual Studio v17.7.3
2. Open MAUI iOS project
3. Connect Visual Studio to macOS
4. Connection fails during package installation due to missing nuget package

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Relevant log output

```shell
Successfully started Broker in-process
Connecting to Local Broker...
Successfully connected to Local Broker
Starting IDB Local Agent...
Successfully started IDB Local Agent
Checking xma 17.7.0.216 installation...
Checking host configuration for connecting to 'name_MacMini'...
Checking SSH configuration...
Current SSH Key File: C:\Users\andyz\AppData\Local\Xamarin\MonoTouch\id_xma.pub
Initializing environment...
Checking available disk space...
Checking if Rosetta is installed...
Checking Mono installation...
Checking host configuration for connecting to 'name_MacMini'...
Host 'name_MacMini' is configured correctly
Starting connection to 'name_MacMini'...
Checking Broker 17.7.0.216 installation...
Starting Broker 17.7.0.216 in port 57054...
Broker 17.7.0.216 started successfully
Starting connection to 'name_MacMini'...
SSH connection to 'name_MacMini' has been established...
Starting registered Agents: IDB 17.7.0.216...
Starting IDB 17.7.0.216...
Checking IDB 17.7.0.216 installation...
Starting IDB 17.7.0.216 in port 57054...
IDB 17.7.0.216 started successfully
IDB 17.7.0.216 started
Starting registered Agents: ...
The Agents have been started successfully
Performing server validations against 'name_MacMini'...
The dotnet SDK is already installed. Version: '7.0.400-rtm.23369.16'
dotnet validation completed
Installing workloads using rollback file:
{
  "microsoft.net.sdk.ios": "16.4.7098/7.0.100",
  "microsoft.net.workload.mono.toolchain.net6": "7.0.10/7.0.100",
  "microsoft.net.workload.mono.toolchain.net7": "7.0.10/7.0.100",
  "microsoft.net.workload.emscripten.net6": "7.0.10/7.0.100",
  "microsoft.net.workload.emscripten.net7": "7.0.10/7.0.100"
}
NuGet sources by default: https://api.nuget.org/v3/index.json
NuGet sources from project: https://api.nuget.org/v3/index.json
Installing workload 'ios'...
workload install ios --from-rollback-file /var/folders/_4/24yc2wnd7m3_jbprp5057j5m0000gn/T/84610503-4b48-4283-b312-6cc20e9c22a9/rollback.json --source "https://api.nuget.org/v3/index.json" --source "https://api.nuget.org/v3/index.json"
Workload(s) 'ios' are already installed.
Skipping NuGet package signature verification.
Installing workload manifest microsoft.net.sdk.ios version 16.4.7098???
Workload installation failed. Rolling back installed packs...

Performing server validations against 'name_MacMini'...
Starting disconnection from name_MacMini...
Starting disconnection from name_MacMini...
The connection to 'name_MacMini' has been finished
Could not install workload 'ios'. Details: Workload installation failed: Failed to install manifest microsoft.net.sdk.ios version 16.4.7098: microsoft.net.sdk.ios.manifest-7.0.100::16.4.7098 is not found in NuGet feeds https://api.nuget.org/v3/index.json;https://api.nuget.org/v3/index.json"..
```

**Comment by schlaman** [comment] 2023-08-30 05:54
I had this same problem and rolled back 17.7.3 to 17.7.2 and I can connect fine again.

**Comment by drasticactions** [comment] 2023-08-30 05:57
Duplicate of https://github.com/dotnet/maui/issues/17077

The is a Visual Studio tooling issue and unrelated to the Maui UI code in this repo.

**Closed by drasticactions** 2023-08-30 05:57 UTC
Labels: t/bug

**Comment by andyzukunft** [comment] 2023-08-30 07:28
@schlaman 
I was not aware that this is an option. Thanks for mentioning it.

**Comment by edwardm** [comment] 2023-08-30 18:57
Confirmed, rolling VS back to 17.7.2 works. Thanks @schlaman

**Comment by omghb** [comment] 2023-08-31 08:47
Visual Studio bug entry: 
- https://developercommunity.visualstudio.com/t/Pair-to-Mac:-Could-not-install-workload/10453595
