### ISSUE TITLE
Entry Focus is not cleared in Android

### ISSUE THREAD

**Issue by JayashreeRavishankar** [dotnet/maui#13928] opened 2023-03-14 17:55 UTC
### Description

Focus of an entry is not cleared, when interact with other views in screen.
Focus an entry by clicking an entry , then click the button in view, still focus is not cleared for entry in Android

### Steps to Reproduce

1. Run the sample
2. Click Enter here and focus the entry.
3. Now click the button (Display)
4. see focus of an entry is not cleared and keyboard is also not closed.

### Link to public reproduction project repository

[MauiEntryFocus.zip](https://github.com/dotnet/maui/files/10972153/MauiEntryFocus.zip)

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android

**Comment by rachelkang** [comment] 2023-03-14 19:14
Duplicate of https://github.com/dotnet/maui/issues/12002

Also related https://github.com/dotnet/maui/issues/11703

Please feel free to elaborate more about your use case on these issues

**Closed by rachelkang** 2023-03-14 19:14 UTC
Labels: t/bug, area/controls 🎮, control-entry
