### ISSUE TITLE
[MAUI] D11 text should be displayed as 'bold'/'italic'

### ISSUE THREAD

**Issue by kevinxufei** [dotnet/maui#17896] opened 2023-10-09 09:07 UTC
### Description

D11 text should be displayed as 'bold'/'italic'

### Steps to Reproduce

1. Deploy https://devdiv.visualstudio.com/Pkgs/_git/VS.TestAssets.Xaml?path=/Assets/Projects/ManualMauiTests to MacCatalyst/iOS.
2. Click or tap on category 'D' for 'Editor'.
3. Click or tap on test 'D11'.
4. Observe page text display.

Actual Behavior:
iOS:
![image](https://github.com/dotnet/maui/assets/86938401/1867f06e-ee1d-4980-834d-d4408cfe6f2d)
MacCatalyst:
![image](https://github.com/dotnet/maui/assets/86938401/945ff16f-32d1-414f-868b-0d7f57e17d8f)

Expected Behavior:
![image](https://github.com/dotnet/maui/assets/86938401/7fb7330c-ed70-4664-aff4-de3482e35582)

### Link to public reproduction project repository

https://devdiv.visualstudio.com/Pkgs/_git/VS.TestAssets.Xaml?path=/Assets/Projects/ManualMauiTests

### Version with bug
Microsoft.Maui.Controls 8.0.0-nightly.9331+sha.6aac924e89-azdo.8456294
.NET SDK: 8.0.100-rc.2.23502.2

### Is this a regression from previous behavior?

Not a regression, The issue also repro on 8.0.0-rc.1.9171

### Affected platforms

iOS, MacCatalyst

**Comment by mattleibow** [comment] 2023-10-09 14:43
Duplicate of https://github.com/dotnet/maui/issues/1018

**Comment by mattleibow** [comment] 2023-10-09 14:48
Yeah, Entry has a global style:

```xaml
<Setter Property="FontFamily" Value="OpenSansRegular"/>
```

This is not supported today and you need to switch to a bold font. #1018 will; make this all much better.

**Closed by mattleibow** 2023-10-09 14:48 UTC
Labels: t/bug, platform/macOS 🍏, platform/iOS 🍎, csi-new
