### ISSUE TITLE
Change name, maui is taken 

### ISSUE THREAD

**Issue by crnisamuraj** [dotnet/maui#9385] opened 2022-08-12 17:46 UTC
### Description

Motherfuckers it's me again. Change te fucking name, MAUI is TAKEN.

### Steps to Reproduce

Lose IQ by a lot

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Windows, macOS, Other (Tizen, Linux, etc. not supported by Microsoft directly)

### Affected platform versions

All

### Did you find any workaround?

Workaround is u change the name of the projects fucktards

### Relevant log output

```shell
Yo mama
```

**Comment by NonameMissingNo** [comment] 2022-08-12 17:56
Yeah sure... it's taken by an island next to Honolulu

**Comment by hartez** [comment] 2022-08-12 20:50
Duplicate of #34

**Closed by hartez** 2022-08-12 20:50 UTC
Labels: t/bug
