### ISSUE TITLE
Add missing MAUI API docs

### ISSUE THREAD

**Issue by Eagle3386** [dotnet/maui#7463] opened 2022-05-25 09:54 UTC
### Description

Plenty of MAUI's API documentation is missing within VS IntelliSense, e. g. after typing
```csharp
MauiApp.CreateBuilder().
```
none of the `MauiAppBuilder` extensions, e. g. `UseMauiApp<T>()` or even `ConfigureFonts()`, provide _any_ information besides their method signature due to missing XML docs within their source code:
https://github.com/dotnet/maui/blob/0ace122b75382a43ae8ff7dbbdf1cb4d55703cc8/src/Controls/src/Xaml/Hosting/AppHostBuilderExtensions.cs#L29-L33
https://github.com/dotnet/maui/blob/0ace122b75382a43ae8ff7dbbdf1cb4d55703cc8/src/Core/src/Hosting/Fonts/FontsMauiAppBuilderExtensions.cs#L16-L20

### Steps to Reproduce

1. Create a File > New .NET MAUI App
2. Go to `CreateMauiApp()` inside `MauiProgram.cs`.
3. At the line with `MauiApp.CreateBuilder()`, type a `.` after the closing parenthesis.

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS, Other (Tizen, Linux, etc. not supported by Microsoft directly)

### Affected platform versions

Any supported platform version up to now

### Did you find any workaround?

Nope. 😢

### Relevant log output

```shell
None available. 😢
```

**Comment by janseris** [comment] 2022-05-25 10:28
Good point. A lot of MAUI API misses documentation. For example MAUI Graphics code as well. I had to look up the source code on GitHub to be able to find out how it works for every function I use. (`IImage` API)

**Comment by Eilon** [comment] 2022-05-25 17:09
BTW in .NET MAUI 6 GA (that we released this week) you should see a TON more documentation for APIs. It's certainly not complete, but prior to that, there were ZERO docs visible for the main MAUI APIs.

**Comment by Eagle3386** [comment] 2022-05-26 20:01
@Eilon Neither is the case - I had some (very few, but still) prior to GA release, yet still after its release essential docs (e. g. both methods in my OP are part of any new MAUI project) remain missing.

**Comment by Eilon** [comment] 2022-05-26 21:34
> @Eilon Neither is the case - I had some (very few, but still) prior to GA release, yet still after its release essential docs (e. g. both methods in my OP are part of any new MAUI project) remain missing.

Understood, and I agree that many API docs are still missing. My comment was that prior to GA there were essentially _ZERO_ API docs visible in VS, and starting with GA (released this week) there are many thousands of API docs available. Unfortunately, the APIs you mentioned are still not available.

**Comment by VincentBu** [comment] 2022-06-06 05:34
repro with vs main build (32605.41.main)

**Comment by samhouts** [comment] 2022-08-22 23:25
Duplicate of #3960

**Comment by jfversluis** [comment] 2022-08-25 08:06
Duplicate of #3960

**Closed by jfversluis** 2022-08-25 08:06 UTC
Labels: t/bug, area/docs 📓, p/2, t/docs 📝, s/verified

**Comment by jfversluis** [comment] 2022-11-03 15:48
For anyone stumbling on this, the API docs are now published here: https://learn.microsoft.com/dotnet/api/?view=net-maui-6.0

While all the APIs are there, not all have a complete/accurate description yet, we're working hard on making that happen. Of course you are welcome to contribute to that. Thanks!
