### ISSUE TITLE
MAUI Need recipe on android when uncomment windows project

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#3242] opened 2021-11-03 00:48 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/MAUI-Need-receipe-on-android-when-uncomm/1551567)._

---
VS2022 Version 17 Preview 5, I created a new MAUI project. I can run it on a android emulator, but if I uncomment the line:
<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows')) and '$(MSBuildRuntimeType)' == 'Full'">$(TargetFrameworks);net6.0-windows10.0.19041</TargetFrameworks>

in the .csproj to also have a Windows Destination I can't run Android anymore. I chosse androdi-sdk as target an it gave me:
Need receipe file

As sonn as I added the comment back in the csproj file , I can run the android part  with no problems.

---
#### Feedback Bot on 10/13/2021, 00:21 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by hartez** [comment] 2021-11-16 17:07
Duplicate of #2942 - I've linked this from that issue so we can keep track of them together.

**Closed by hartez** 2021-11-16 17:07 UTC
Labels: platform/windows 🪟, platform/android 🤖, area/tooling ⚙️
