### ISSUE TITLE
Button control's BackgroundColor property not update properly with Trigger.

### ISSUE THREAD

**Issue by divyesh008** [dotnet/maui#16693] opened 2023-08-11 07:22 UTC
### Description

I'm trying to set the Button's BackgroundColor and TextColor based on its IsEnabled property using Trigger. This works fine in debug mode in app. 

But when we create release build in that Button's text color property updates properly but the BackgroundColor property is not updating to Primary color, it stays Gray. 

### Output in the debug mode: 
https://github.com/dotnet/maui/assets/10617244/663eae4f-1095-46f2-9da7-0a52a6b9186e

### Steps to Reproduce

1. Create new project 
2. Add button control and set logic for it's IsEnabled property
3. Based on IsEnabled add a trigger to change Button's TextColor and BackGroundColor properties value. 

### Link to public reproduction project repository

https://github.com/divyesh008/Button_BGColor_Bug

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

iOS 16.1, Android 11

### Did you find any workaround?

Yes, I have used Opacity property with trigger instead of BackGroundColor and TextColor properties.

**Comment by mattleibow** [comment] 2023-08-11 15:12
Duplicate of: https://github.com/dotnet/maui/issues/11662
This was fixed in .NET 8: https://github.com/dotnet/maui/pull/13836

There are 2 workarounds for .NET 7:

1. Use `Background` instead of the older `BackgroundColor`

2. Remap the BackgroundColor to Background mapper:

```cs
.ConfigureMauiHandlers(_ => 
{
	LabelHandler.Mapper.AppendToMapping(
		nameof(View.BackgroundColor),
		(handler, View) => handler.UpdateValue(nameof(IView.Background)));
	ButtonHandler.Mapper.AppendToMapping(
		nameof(View.BackgroundColor),
		(handler, View) => handler.UpdateValue(nameof(IView.Background)));
})
``` 

See more info in https://github.com/dotnet/maui/issues/11662

**Closed by mattleibow** 2023-08-11 15:12 UTC
Labels: t/bug, s/try-latest-version

**Comment by samhouts** [comment] 2023-08-11 18:04
Duplicate of #11662
