### ISSUE TITLE
OnAppearing not called if returning from a modal page to a modal page

### ISSUE THREAD

**Issue by AndreasReitberger** [dotnet/maui#11498] opened 2022-11-19 09:41 UTC
### Description

I'm not sure if this is by design, so if not, please let me know. Please see the attached repro.

```cs
protected override async void OnAppearing()
    {
       // Set breakpoint here for both modals
        base.OnAppearing(); 
        try
        {
            await ((WatchlistDetailsModalPageViewModel)BindingContext).OnAppearing();
        }
        catch (Exception) { }
    }
```

### Steps to Reproduce

1. Create a new maui app and add two modals pages to it
2. Override the OnAppearing and set a break point
3. Use Shell to navigate to the first modal and see, that the breakpoint is hit. 
4. Navigate to the next modal page, also this breakpoint is hit
5. Navigate back using Shell, and see that the breakpoint of modal number 1 is not hit on appearing

### Link to public reproduction project repository

https://github.com/AndreasReitberger/ReproScrollingIssueModal

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, I was *not* able test on other platforms

### Affected platform versions

iOS 16.1, but also could be not relevant to version

**Comment by marcmognol** [comment] 2022-11-19 12:56
Hi,
Duplicate of #8513?

Marc

**Comment by SailDev** [comment] 2023-02-04 09:28
Cross reference, to draw more attention to the problem:
[Link](https://github.com/dotnet/maui/issues/8513#issuecomment-1416706201)

**Closed** 2023-02-08 17:52 UTC
Labels: t/bug, s/duplicate 2️⃣, area/lifecycle 🔁, area/modal
