### ISSUE TITLE
Vertical ScrollBar is not visible until scrolled in Android platform.

### ISSUE THREAD

**Issue by SethupathyD** [dotnet/maui#24894] opened 2024-09-24 09:36 UTC
### Description

Despite setting VerticalScrollBarVisibility="Always" in the ScrollView, the vertical scrollbar is not visible in Android until the user starts scrolling. I had shared the video demo for your reference.

https://github.com/user-attachments/assets/ed26807e-80d6-4693-8ccc-6161481f5fb1

### Steps to Reproduce

1. Run the attached sample in android platform.
2. You could notice initially vertical scroll Bar not visible.
3. On performing scrolling it is visible.

Actual Behavior : Vertical scrollbar is not visible.
Expected Behavior: Vertical scrollbar should be visible.

### Link to public reproduction project repository

https://github.com/SethupathyD/AndroidScrollBarIssue

### Version with bug

8.0.90 SR9

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Did you find any workaround?

No

**Comment by Zhanglirong-Winnie** [comment] 2024-09-24 09:47
This issue has been verified using  Visual Studio 17.12.0 Preview 2.0(8.0.82 & 8.0.90). Can repro this issue on Android platform.

**Comment by PureWeen** [comment] 2024-09-25 22:21
Duplicate of #12760

**Closed by PureWeen** 2024-09-25 22:21 UTC
Labels: t/bug, platform/android 🤖, s/verified, s/triaged
