### ISSUE TITLE
ResourceDictionary.ContainsKey method is not working correctly

### ISSUE THREAD

**Issue by DancesWithDingo** [dotnet/maui#15110] opened 2023-05-16 14:44 UTC
### Description

The function ResourceDictionary.ContainsKey(string) is not working. It never returns true, despite the key existing in the dictionary Keys collection. However, the method ResourceDictionary.Keys.Contains(string) DOES work, although interestingly enough, this method puts up a "CA1841: Prefer Dictionary Contains methods" warning.

### Steps to Reproduce

Create a new .NET MAUI project. In the MainPage.xaml.cs file, add the following to the MainPage constructor:

``` csharp
var dictionary = Application.Current.Resources.MergedDictionaries.FirstOrDefault();
if ( dictionary is not null ) {
    Debug.WriteLine($"dict.ContainsKey(\"Primary\")   => {dictionary.ContainsKey("Primary")}");
    Debug.WriteLine($"dict.Keys.Contains(\"Primary\") => {dictionary.Keys.Contains("Primary")}");

    Debug.WriteLine("Keys in dictionary:");
    dictionary.Keys.ToList().ForEach(k => Debug.WriteLine($"-> {k}"));
}
```

Run, and note the following output:

dict.ContainsKey("Primary")   => False
dict.Keys.Contains("Primary") => True
Keys in dictionary:
-> Primary
-> Secondary
-> Tertiary
-> White
-> Black
...

Despite "Primary" being in ResourceDictionary dict, the ContainsKey method returns false. The Key.Contains method correctly returns true, and the key appears in the list of keys in the dictionary.

### Link to public reproduction project repository

https://github.com/DancesWithDingo/MAUI_ContainsKeySample.git

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, macOS, I was *not* able test on other platforms

### Affected platform versions

macOS 12.6.5, iOS 16.4.1

### Did you find any workaround?

We can use ResourceDictionary.Keys.Contains(string), although it gives a "CA1841: Prefer Dictionary Contains methods" message telling us otherwise.

**Comment by XamlTest** [comment] 2023-09-15 10:09
Verified this on Visual Studio Enterprise 17.8.0 Preview 2.0. Repro on Windows 11(8.0.0-rc.1), Android 13.0-API33 and iOS 16.4 with below Project:
[ContainsKeySample.zip](https://github.com/dotnet/maui/files/12618214/ContainsKeySample.zip)

**Comment by hartez** [comment] 2023-09-15 20:18
Duplicate of #13268.

See also: https://github.com/dotnet/maui/pull/11214#issuecomment-1498922649

**Closed by hartez** 2023-09-15 20:18 UTC
Labels: t/bug, area/Xaml </>, s/verified, s/triaged
