### ISSUE TITLE
IOS Xcode 16 Strip exited with code 139 error

### ISSUE THREAD

**Issue by TheSundayDev** [dotnet/maui#25162] opened 2024-10-09 21:40 UTC
### Description

Last version of VS 17.11.5 requires Xcode 16. After Xcode update now I have this error when i compile: Strip exited with code 139
thanks

### Steps to Reproduce

Build IOS app

### Version with bug

8.0.82 SR8.2

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

8.0.82 SR8.2

### Affected platforms

iOS

### Affected platform versions

ios

**Comment by gwise-vision** [comment] 2024-10-10 10:27
same issue.
This error makes the app too big. When will it be fixed?

**Comment by jfversluis** [comment] 2024-10-14 07:51
Duplicate of https://github.com/xamarin/xamarin-macios/issues/19157

**Closed by jfversluis** 2024-10-14 07:51 UTC
Labels: t/bug, platform/iOS 🍎, s/triaged
