### ISSUE TITLE
Image taken by Binding and IValueConverter is not shown

### ISSUE THREAD

**Issue by StanislavIlchenko** [dotnet/maui#17272] opened 2023-09-08 13:07 UTC
### Description

Image has taken it's Height/Width requests but image itself isn't shown.
![image](https://github.com/dotnet/maui/assets/141010748/f8096bc2-a1bf-41df-9942-96b50f5df7ce)

### Steps to Reproduce

1. Use https://github.com/StanislavIlchenko/MauiIosFrameContentBug repository
2. Switch to LanguageChangeTest branch
3. Run application on Windows/Android/iOS (haven't tested on other platforms)
4. Note images are absent

### Link to public reproduction project repository

https://github.com/StanislavIlchenko/MauiIosFrameContentBug

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, I was *not* able test on other platforms

### Affected platform versions

Windows10.0.19041.0, Android 11 API 30, iOS 16.1.2

### Did you find any workaround?

No

**Comment by jfversluis** [comment] 2023-09-11 07:53
What image do you expect to see there? Because a quick look through your reproduction project doesn't really show me any lead on what images you expect to see there?

**Comment by XamlTest** [comment] 2023-09-11 09:36
Verified this on Visual Studio Enterprise 17.8.0 Preview 1.0. Repro on Windows 11(8.0.0-preview.7.8842), Android 13.0-API33 and iOS 16.4 with below Project:
[CollectionViewPopupTest.zip](https://github.com/dotnet/maui/files/12574487/CollectionViewPopupTest.zip)

**Comment by drasticactions** [comment] 2023-09-11 13:06
@jfversluis question is valid and needs to be answered for us to keep working on this: The images referenced in the XAML , as far as I can tell, are not in the repro project, so I also am not sure what's intended to be there.

**Comment by StanislavIlchenko** [comment] 2023-09-11 13:11
Image in repo: https://github.com/StanislavIlchenko/MauiIosFrameContentBug/tree/LanguageChangeTest/CollectionViewPopupTest/Resources/LanguageIcons

**Comment by jfversluis** [comment] 2023-09-11 13:21
Yeah on second look I noticed the different branch that had the changes we were looking for. This probably has to do with the build actions as your images are in a separate folder that are not known by the single-project build system.

You probably want to have a look at this [docs page](https://learn.microsoft.com/dotnet/maui/user-interface/images/images).

What you could try:
* Remove [these entries](https://github.com/StanislavIlchenko/MauiIosFrameContentBug/blob/LanguageChangeTest/CollectionViewPopupTest/CollectionViewPopupTest.csproj#L52-L64), they are probably added by Visual Studio and not needed, keep on the look out if entries like these are added back.
* Add a similar entry to [this](https://github.com/StanislavIlchenko/MauiIosFrameContentBug/blob/LanguageChangeTest/CollectionViewPopupTest/CollectionViewPopupTest.csproj#L49), but then for your language icons. For example: `<MauiImage Include="LanguageIcons\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />`
* Another option would be to not put them in a separate folder in the `Resources` folder, but to make a subfolder under `Resoures/Images` and add [this entry](https://github.com/dotnet/maui/blob/main/src/Templates/src/templates/maui-mobile/MauiApp.1.csproj#L48) back to your csproj file. It seems [you have removed it](https://github.com/StanislavIlchenko/MauiIosFrameContentBug/blob/LanguageChangeTest/CollectionViewPopupTest/CollectionViewPopupTest.csproj#L43), but this is typically part of the new .NET MAUI project.

If you want to do more with resources like this then you'll have to add filters in your csproj to make sure the processing goes correctly. Or, another way is to set the right Build Action for each of the files through Visual Studio which will make the correct entries in your csproj file as well..

Does that help?

**Comment by StanislavIlchenko** [comment] 2023-09-12 06:30
I tried to use MauiImage but result the same. I get ImageSource it's not null, it's not empty, it has stream. I assign this image source to Image element and Image element shows nothing

**Comment by jfversluis** [comment] 2023-09-25 08:45
Ah so it's actually not a resource, it should be treated as a file so if you change [your converter](https://github.com/StanislavIlchenko/MauiIosFrameContentBug/blob/LanguageChangeTest/CollectionViewPopupTest/Converters/StringToImageSourceConverter.cs#L15) to use this: `var source = ImageSource.FromFile(sourceIdentifier);` it all starts working as expected.

I did still remove some clutter from your csproj file. [This](https://github.com/StanislavIlchenko/MauiIosFrameContentBug/blob/LanguageChangeTest/CollectionViewPopupTest/CollectionViewPopupTest.csproj#L53-L65) should not be needed: 

```xml
	<ItemGroup>
	  <None Remove="Resources\Images\LanguageIcons\de.png" />
	  <None Remove="Resources\Images\LanguageIcons\en.png" />
	  <None Remove="Resources\Images\LanguageIcons\fr.png" />
	  <None Remove="Resources\Images\LanguageIcons\it.png" />
	</ItemGroup>

	<ItemGroup>
	  <MauiImage Include="Resources\Images\LanguageIcons\de.png" />
	  <MauiImage Include="Resources\Images\LanguageIcons\en.png" />
	  <MauiImage Include="Resources\Images\LanguageIcons\fr.png" />
	  <MauiImage Include="Resources\Images\LanguageIcons\it.png" />
	</ItemGroup>
```

[This line](https://github.com/StanislavIlchenko/MauiIosFrameContentBug/blob/LanguageChangeTest/CollectionViewPopupTest/CollectionViewPopupTest.csproj#L44) should take care of all the files under the Resources\Images folder: `<MauiImage Include="Resources\Images\*" />`

Closing this for now as it works on my end and I don't really see a potential bug here. Let us know if you feel differently.

**Closed by jfversluis** 2023-09-25 08:45 UTC
Labels: t/bug, area/image :framed_picture:, s/verified, s/triaged, s/needs-attention
