### ISSUE TITLE
The type or namespace name 'Shared' does not exist in the namespace 

### ISSUE THREAD

**Issue by whann0205** [dotnet/maui#2359] opened 2021-09-02 05:21 UTC
Its impossible to create a new project with the name Asset or AssetQuery as the name without
getting this Error:

CS0234	The type or namespace name 'Shared' does not exist in the namespace 'AssetQueryApp' (are you missing an assembly reference?)	AssetQueryApp.WinUI (net6.0-windows10.0.19041)	Z:\VCSource\AssetQueryApp\AssetQueryApp\AssetQueryApp\_Imports.razor	8	

### Steps to Reproduce

1. Create a new project
2. Select net maui blazor
3. Use Asset or AssetQuery as the name

- Version with issue: Visual Studio 2022
- Last known good version: Dont know if it would work with VS 2019 since i dont have a net maui blazor template for it
- IDE:
- Platform Target Frameworks: n/a
- Nuget Packages:
- Affected Devices:

### Workaround
Rename the project.... :-(

**Comment by Eilon** [comment] 2021-09-02 17:26
Ah, there's probably already a sub-namespace in the app named `Asset` or `AssetQuery`. We'll need to see if this is a problem in something that is code-gen'ed or some regular template content. There will almost always be _some_ names that don't work well by default because they use some sort of reserved word or accidentally conflicting term. I bet something weird happens if you call your project `System` or something too 😄 But we should see if there's something we can improve here.

**Comment by whann0205** [comment] 2021-09-03 07:03
I have ported as you know since you told me to try it :-) from MBB/.net 3.1/VS Prof 2019.16.11 to .net maui/.net6/Visual studio 2022 and in mbb there is no such problem.
Its hard for me to avoid that name since the apps name should be assetquery.

**Comment by Eilon** [comment] 2021-09-03 16:09
@whann0205 there will always be _some_ names that don't work automatically when you create a new project, but it _should_ be the case that you can update the project manually afterwards to work. If that is not true, then there is likely a bug in .NET MAUI (or somewhere else in .NET).

Can you show the line of code that is causing the error?

**Comment by whann0205** [comment] 2021-09-03 21:04
![grafik](https://user-images.githubusercontent.com/71807453/132065031-df600430-6db7-4a6a-8de4-c7c8ec247032.png)

Hope you can see all important things from the screenshot above...

**Comment by Eilon** [comment] 2021-09-03 21:44
I think you can fix this in your project by changing it to say:

```
...
@using global::Asset
@using global::Asset.Shared
```

**Comment by whann0205** [comment] 2021-09-04 05:42
![grafik](https://user-images.githubusercontent.com/71807453/132083964-c36de21c-58c9-4ef9-8647-80fcc3276f2d.png)

i fear that doesn´t change anything ...

**Comment by Eilon** [comment] 2021-09-08 17:22
@whann0205 OK maybe the problem is something else. Can you show the contents of the Asset.WinUI.csproj? And also does the main Asset project compile & run fine (say, on an Android Emulator)?

**Comment by Eilon** [comment] 2021-09-08 17:26
BTW I tried this on the upcoming preview and the names `Asset` and `AssetQuery` both work fine without any changes or errors. In the next preview we've merged the WinUI project into the main project, which fixes a bunch of issues, and maybe it fixes the problem you're running into as well.

**Comment by Eilon** [comment] 2021-09-20 21:09
Closing because I think this issue is already fixed in preview 8 from earlier this month.

**Closed by Eilon** 2021-09-20 21:09 UTC

**Comment by whann0205** [comment] 2021-09-21 17:50
Can confirm the problem is fixed. I begin to continue testing.
This issue is solved, lets see if there are others.
Thanks a lot!
