### ISSUE TITLE
#elif WINDOWS doesn't work

### ISSUE THREAD

**Issue by nk54** [dotnet/maui#6815] opened 2022-05-04 14:15 UTC
### Description

I want to create a service and use dependency injection.

It works on each platform except windows.
First, `#elif __WINDOWS__` wasn't taken into account by Visual Studio (see screenshot below)
![image](https://user-images.githubusercontent.com/13755220/166698677-b38a6467-16ea-4573-befe-943d314ecf28.png)

Next, `#elif WINDOWS` was recognized by Visual Studio but not by the compiler as it tells me it can't find the implementation of my service.

_It should work and the documentation MUST (just my opinion, you're the boss haha) be updated to tell to developpers what's the difference between `#if __ANDROID__` and `#if ANDROID`
On the Microsoft documentation I saw both, it's quite confusing. Even more when `#if __WINDOWS__` doesn't work while `#if WINDOWS` does._
Edit: [answer given here](https://github.com/dotnet/docs-maui/issues/501#issuecomment-1117540974) don't use the double underscore.

### Steps to Reproduce

- create an interface inside the MAUI project
- create an implementation of that interface inside each platforms folder
- try to register the service inside MauiProgram.cs

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows (I'm using Visual Studio  17.2.0 Preview 6.0)

### Affected platform versions

net6.0-windows10.0.19041

### Did you find any workaround?

Yes !

I handle each platform and handle WINDOWS in the `#else`

But it's a dirty hack because if the problem occurs on Tizen too, it cannot work

**Comment by Eilon** [comment] 2022-05-04 16:38
In my experience, the underscore versions of the define's are never used. Only the "text" defines, such as `#if WINDOWS`, etc. There are also version-specific defines, such as `WINDOWS10_0_19041_0`, but those are rarely used, because most code differs only by platform, and not specific version of the platform.

Can you show a code sample that doesn't work if you use only the "text" defines?

**Comment by Eilon** [comment] 2022-05-04 16:40
For example, with this code:

```c#
#if WINDOWS
// Windows
#elif ANDROID
// Android
#elif IOS
// iOS
#elif MACCATALYST
// MacCatalyst
#endif
```

I get this result, which is what I expected (note that the IOS platform is selected, and the iOS comment is "green", meaning it is included in the compilation:

![image](https://user-images.githubusercontent.com/202643/166729284-6f161425-c3aa-4ff0-8a3a-314152532663.png)

**Comment by jfversluis** [comment] 2022-05-05 08:21
We're using this in various places in our own code and is described in the docs [here](https://docs.microsoft.com/dotnet/maui/fundamentals/single-project#platform-specific-code) as being `#if WINDOWS`. 

I don't think there is an issue here. Have a look in our codebase here to see how we're using it to guide you as an example.

**Comment by Nk54** [comment] 2022-05-05 13:49
Hi @Eilon thank you for your time.

[In this thread on the maui documentation](https://github.com/dotnet/docs-maui/issues/501#issuecomment-1117540974), it seems we have to use `#if PLATFORMNAME` instead of `#if __PLATFORMNAME__`

If I set `#if WINDOWS` the compiler doesn't find my class whereas the overview of the type in Visual Studio indicates it's found on each platform

**Comment by Nk54** [comment] 2022-05-05 13:51
@jfversluis you may missed the following part

**Next, #elif WINDOWS is recognized by Visual Studio but not by the compiler as it tells me it can't find the implementation of my service.**

There is a bug. Don't close this yet please

**Comment by jfversluis** [comment] 2022-05-05 13:57
As I said: we have this in multiple places in our codebase, it works fine there.

If it says that there is still something wrong, I would think it is something else. It would greatly help if you provide a reproduction sample that shows this behavior or at the very least specify what "tells me it can't find the implementation of my service." is exactly. What is the exact error message and the code that triggers it?

**Comment by jfversluis** [comment] 2022-05-05 15:28
That indeed seems weird!

Not to be rude here or anything just want to point it out, but I feel this would have all saved us a lot of time if there was a reproduction attached in the first place. That's why we ask for it. It can be the subtle differences.

**Comment by Nk54** [comment] 2022-05-05 15:40
Yeah I know but trust me those last few days I've been submitting severals bugs (you saw some of them)

I do what I can to help the community but if found  several bugs a day on MAUI (XAML crash or weird rendering compared to the same code on Xamarin Forms) so if I spend 1 or 2 hour by bug to create the project, the repro step, to publish on github, to fill the issue here, I bet my boss would ask me to stop reporting new issues with something stupid like "other people will do it for you. Microsoft isn't the one who pays you anymore (I worked 2 years at Microsoft France) so start working for me instead of them" or he would ask me to migrate from Xamarin Forms to Flutter instead of MAUI haha.

Anyway, I'll do what I can in the future to provide a github repro project in the future ;)

I wish you a good evening!

**Comment by Nk54** [comment] 2022-05-05 15:41
LOL I didn't notice it was you Gerald!!!! I post some messages on your Youtube channel few days ago (Nicolas)

Glad to meet you here too, an honor ;)

**Comment by VincentBu** [comment] 2022-05-24 06:17
@jfversluis, just curious, can we use the sample in #7423 to repro this issue?

**Comment by Eilon** [comment] 2022-05-24 16:33
I was able to repro https://github.com/dotnet/maui/issues/7423 (closed as dup of this bug). I used latest VS with .NET MAUI 6 GA.

**Comment by salarcode** [comment] 2022-07-31 13:12
Adding this to .csproj file fixes the issue for me. Looks like `WINDOWS` is not defined
```
	<PropertyGroup Condition="$(TargetFramework.Contains('-windows'))">
	  <DefineConstants>WINDOWS</DefineConstants>
	</PropertyGroup>
```

**Comment by Eilon** [comment] 2022-08-01 16:01
@salarcode yeah that's quite odd. The MAUI targets are supposed to add that automatically...

**Comment by joshmclean** [comment] 2022-08-09 02:43
@salarcode I tried your solution, but it doesn't work for me. None of the Windows platform specific methods or #if WINDOWS work for me.

Did you put that in your MAUI class library project file? Can you show us your .csproj xml file?

**Comment by joshmclean** [comment] 2022-08-09 03:10
Okay I was able to figure out why it wasn't working for me.

My solution looks like this

Console App with Target framework of NET 6.0, **but Target OS is set to (None) under project settings.**
.NET MAUI 6.0 class library with platform specific code, and this library is linked to the NET 6.0 Console app.

If I change my Target OS to 'Windows' for the .NET 6.0 Console App then the platform specific code in the NET 6.0 class library for Windows works.

So the solution (for now) would be to have multiple .NET 6.0 Console App projects with each project targeting a specific platform (macOS, Windows) by setting the target OS.

**Comment by MagicAndre1981** [comment] 2022-08-15 22:08
> Adding this to .csproj file fixes the issue for me. Looks like `WINDOWS` is not defined
> 
> ```
> 	<PropertyGroup Condition="$(TargetFramework.Contains('-windows'))">
> 	  <DefineConstants>WINDOWS</DefineConstants>
> 	</PropertyGroup>
> ```

thanks, this fixed my issue, too with `#if !WINDOWS` which worked in text editor of VS2022, here the code was grayed out, but the compiler still tried to compile the code which failed as I use code that only compiles for the Android part.

**Comment by RobertLinak** [comment] 2022-10-18 06:34
What is the status on this getting fixed?

**Comment by MagicAndre1981** [comment] 2022-10-18 07:04
> What is the status on this getting fixed?

no ETA, you [still need to use the workaround](https://github.com/dotnet/maui/issues/6815#issuecomment-1200422726)

**Comment by mattleibow** [comment] 2022-11-03 23:27
I have been investigating this and it appears that there is a bug somewhere in the WindowsAppSDK or msbuild or somewhere that runs a "pre compile" before defining the values... The real build works because the .NET SDK adds things.

https://github.com/microsoft/WindowsAppSDK/issues/3108

I will see what we can do in MAUI to avoid this, but there are many missing defines so I am worried we add 1 and then we need to add the rest.

**Comment by MrDeej** [comment] 2022-12-05 19:48
Hmm... 
![image](https://user-images.githubusercontent.com/16320446/205729471-f72b756e-94be-4849-afe0-cafe389ddbff.png)
![image](https://user-images.githubusercontent.com/16320446/205729518-c61958c0-9a18-49cb-a2eb-de0547d6e61c.png)
![image](https://user-images.githubusercontent.com/16320446/205729495-3ee8024e-4169-4ea8-85ee-15375d5022f6.png)


Probably something I miss here, but this does not work as intended

**Comment by MagicAndre1981** [comment] 2022-12-05 20:41
this whole #if concept is crap, I [liked the old XF way much more to write platform specific code](https://learn.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/dependency-service/introduction).

**Comment by MagicAndre1981** [comment] 2022-12-06 08:47
> In .NET MAUI you can also place C# code files in "platform" folders and avoid using preprocessor directives such as `#if`. Learn more here: https://learn.microsoft.com/dotnet/maui/platform-integration/invoke-platform-code?view=net-maui-7.0#partial-classes-and-methods

yes, I know this and already use it

> However, I find in my own code that if I only need to special case one or two lines of code, `#if` is easier. I use platform folders when I have entire classes that are almost entirely different.

I use [DeviceInfo.Current.Platform](https://learn.microsoft.com/en-us/dotnet/maui/platform-integration/device/information?view=net-maui-7.0&tabs=windows#get-the-device-platform) for this.

**Closed** 2023-01-16 19:52 UTC
Labels: t/bug, area/single project ☝️, s/verified

**Comment by SF-Simon** [comment] 2023-03-06 23:54
https://github.com/dotnet/maui/issues/6815#issuecomment-1338070753
