### ISSUE TITLE
Blazor startup not working on Android

### ISSUE THREAD

**Issue by fairking** [dotnet/maui#7965] opened 2022-06-12 12:22 UTC
### Description

Based on the [documentation](https://docs.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/?view=aspnetcore-6.0#inject-a-script-after-blazor-starts) in order to call C# backend from BlazorWebView we must wait for Blazor initialization.
On Windows mode it is working as expected. But on Android the following exception is thrown: 
```
[chromium] [INFO:CONSOLE(1)] "Uncaught (in promise) TypeError: window.external.receiveMessage is not a function", source: https://0.0.0.0/_framework/blazor.webview.js (1)
[chromium] [INFO:CONSOLE(1)] "Uncaught (in promise) Error: Blazor has already started.", source: https://0.0.0.0/_framework/blazor.webview.js (1)
```

Please fix it as the MAUI is not working on Android. So at least I am not able to start the app as in my case a call to backend is required on startup.

### Steps to Reproduce

1. Clone the repo: https://github.com/fairking/MauiApp1.git
2. Open the project in VS
3. Run in Windows Mode, you will see the following message: "Hello World OK!"
4. Now run in Android Mode, you will see the following message: "Loading..." and VS output will log the errors mentioned in the description above. 

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 9.0

### Did you find any workaround?

No :-(

### Relevant log output

```shell
[chromium] [INFO:CONSOLE(1)] "Uncaught (in promise) TypeError: window.external.receiveMessage is not a function", source: https://0.0.0.0/_framework/blazor.webview.js (1)
[chromium] [INFO:CONSOLE(1)] "Uncaught (in promise) Error: Blazor has already started.", source: https://0.0.0.0/_framework/blazor.webview.js (1)
```

**Comment by fairking** [comment] 2022-06-12 12:23
Related issue which has not been solved but was closed by the support team: https://github.com/dotnet/maui/issues/7392

**Comment by kristinx0211** [comment] 2022-06-13 08:34
verified repro on android 12 with above project.
![image](https://user-images.githubusercontent.com/99457000/173313385-75512a56-bfb7-46cd-929d-a31e7f476903.png)

**Comment by fairking** [comment] 2022-06-13 10:31
> verified repro on android 12 with above project.

Thank you.

**Comment by TanayParikh** [comment] 2022-06-14 20:44
This is happening because `Blazor.start()` is being called twice.

In your code [here](https://github.com/fairking/MauiApp1/blob/52462c340a4b380727e74a52c15aec1384cdf762/MauiApp1/wwwroot/index.html#L20-L22) as well as from within the [MAUI Android Blazor `WebKitWebViewClient`](https://github.com/dotnet/maui/blob/a6ecf6f2d41b0fe10d810fe4d9ba4b5a912160a7/src/BlazorWebView/src/Maui/Android/WebKitWebViewClient.cs#L169-L170).

Remove the call in your code to `Blazor.start()` and wait till `window.__BlazorStarted == true` before [calling into dotnet](https://github.com/fairking/MauiApp1/blob/52462c340a4b380727e74a52c15aec1384cdf762/MauiApp1/wwwroot/index.html#L29-L35).

**Comment by Eilon** [comment] 2022-06-14 20:47
I think you can probably use JS initializers, which @javiercn knows all about. Learn more here: https://docs.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/?view=aspnetcore-6.0#javascript-initializers

**Comment by fairking** [comment] 2022-06-14 20:47
> This is happening because `Blazor.start()` is being called twice.
> 
> In your code [here](https://github.com/fairking/MauiApp1/blob/52462c340a4b380727e74a52c15aec1384cdf762/MauiApp1/wwwroot/index.html#L20-L22) as well as from within the [MAUI Android Blazor `WebKitWebViewClient`](https://github.com/dotnet/maui/blob/a6ecf6f2d41b0fe10d810fe4d9ba4b5a912160a7/src/BlazorWebView/src/Maui/Android/WebKitWebViewClient.cs#L169-L170).
> 
> Remove the call in your code to `Blazor.start()` and wait till `window.__BlazorStarted == true` before [calling into dotnet](https://github.com/fairking/MauiApp1/blob/52462c340a4b380727e74a52c15aec1384cdf762/MauiApp1/wwwroot/index.html#L29-L35).

But the `autostart=false` was set. I cannot understand why it is not a bug.

**Comment by TanayParikh** [comment] 2022-06-14 21:07
> But the `autostart=false` was set. I cannot understand why it is not a bug.

Ah I see what you mean, and it's definitely a bit confusing. The `autostart=false` specifically [prevents the boot logic](https://github.com/dotnet/aspnetcore/blob/36cca06fd6806e0a6f62377364f7622090678b9c/src/Components/Web.JS/src/Boot.WebView.ts#L39-L41) from being executed when the script is first referenced. We need to have this set to `false` so we can do Android specific setup and subsequently run the start within the [MAUI Android Blazor `WebKitWebViewClient`](https://github.com/dotnet/maui/blob/a6ecf6f2d41b0fe10d810fe4d9ba4b5a912160a7/src/BlazorWebView/src/Maui/Android/WebKitWebViewClient.cs#L169-L170).

**Comment by fairking** [comment] 2022-06-14 22:10
Thank you guys for the help and the explanation. Please allow me to look a the docs and to the homework first. Ones I got it running I will close the ticket. I believe I won't have any more questuions. FYI @Eilon @TanayParikh

**Comment by fairking** [comment] 2022-06-17 16:12
Ok. I tried `{MyProject}.lib.module.js` and it's not working. The method `afterStarted` is not called (tested on windows). `autostart=false` is set. Things become overcomplicated. I am not sure if this is the right approach. If android version could behave in the same way as windows one, it would be very cool. In my opinion there is some bug in android version which in my case occurs only after I deploy and install the app on the physical device. On emulator looks like it is working.

I will be updating the thread ones I have any news.

**Comment by Eilon** [comment] 2022-06-17 16:24
Hi @fairking , can you make sure that the repro project at https://github.com/fairking/MauiApp1.git is up-to-date with the latest code, and then we will investigate? I want to make sure we see whatever you are seeing.

**Comment by fairking** [comment] 2022-06-17 16:28
> Hi @fairking , can you make sure that the repro project at https://github.com/fairking/MauiApp1.git is up-to-date with the latest code, and then we will investigate? I want to make sure we see whatever you are seeing.

done

**Comment by Eilon** [comment] 2022-06-17 17:25
@fairking thank you, understood. I'll take a look and hopefully we can come up with a clean solution to this.

**Comment by Eilon** [comment] 2022-06-21 21:34
Hi @fairking , I cloned your repo and it seems to work fine on Android and Windows. When I click the button, the time updates:

<img width="407" alt="image" src="https://user-images.githubusercontent.com/202643/174901083-6643a150-7762-47b0-90dd-ed09d32e4a05.png">

Can you point me to where in the repro project the problem is?

**Comment by fairking** [comment] 2022-06-21 21:36
It should show the time on startup, not when you click the button.

**Comment by Eilon** [comment] 2022-06-21 23:36
Ah so it's the first load specifically. I'll dive in again.

**Comment by Eilon** [comment] 2022-06-21 23:40
Indeed, in my emulator it seems to show the time on first load without any interaction, though it does briefly flash an error first.

**Comment by Eilon** [comment] 2022-06-21 23:42
I made it always append the text and here's what I'm seeing:

<img width="379" alt="image" src="https://user-images.githubusercontent.com/202643/174914137-9f802db8-4b99-451a-a0c7-9af1d56d696a.png">

So you're saying that you want to avoid that first error entirely. That is, you want a way to "guarantee" that the first call will succeed without doing the heartbeat loop?

**Comment by fairking** [comment] 2022-06-22 05:03
Yes, exactly.

**Comment by Eilon** [comment] 2022-06-22 19:07
In _theory_, the "best" way to make this work is to use Blazor JS module initializers, but unfortunately there is currently a bug that prevents them from working as intended. For completeness, I'll show how it _should_ work.

In `index.html` you would just define whatever methods you want, such as:

```html
	<script type="text/javascript">
		async function CallCSharp() {
            document.getElementById("app").innerHTML += "<br>";
            document.getElementById("app").innerHTML += await window.DotNet.invokeMethodAsync('MauiApp1', 'CallMeFromJs', "Hello World");
        };
	</script>
```

And in your app you would add a new file `wwwroot/MauiApp1.lib.module.js` (but change `MauiApp1` to whatever the project name is) with content like this:

```js
export async function afterStarted(blazor) {
    console.log("afterStarted - begin");
    await CallCSharp();
    console.log("afterStarted - end");
}
```

And then when you run the app, Blazor will detect the initializer code and run it _after_ Blazor is done initializing - which, I believe, is exactly what you wanted.

Here's what it should look like in the app (notice that there are no errors):
<img width="377" alt="image" src="https://user-images.githubusercontent.com/202643/175116367-11c69fe4-96d2-46fa-8ae9-10aca2f6d054.png">

And the console log also showing the before/after:
<img width="317" alt="image" src="https://user-images.githubusercontent.com/202643/175116523-b7e3a5ce-78cc-49ae-b540-a49f1b556267.png">

But, there is a bug right now that prevents the JS initializers from working properly.

I talked to @javiercn today and he will file bugs for that and we will get those on track to be fixed.

So, in the meantime, I think the best we can do is to use a workaround such as what you have come up with. Either in JS or C# code wait until the app appears to be ready, and then invoke the function(s) you want.

**Comment by fairking** [comment] 2022-06-23 15:25
> In _theory_, the "best" way to make this work is to use Blazor JS module initializers, but unfortunately there is currently a bug that prevents them from working as intended. For completeness, I'll show how it _should_ work.
> And in your app you would add a new file `wwwroot/MauiApp1.lib.module.js` (but change `MauiApp1` to whatever the project name is) with content like this:

For me the solution you provided is not possible:
Answer number 1: https://github.com/dotnet/maui/issues/7965#issuecomment-1159040537
Answer number 2: https://github.com/quasarframework/quasar/discussions/13725

**Comment by Eilon** [comment] 2022-06-23 16:39
@fairking unfortunately, calling `Blazor.start()` is not supported here due to how BlazorWebView initializes the JS code. If JS initializers were working, you don't have to load any scipt/JS manually - you just put the startup code in a file called `MyApp.lib.module.js` and it gets loaded automatically and it also runs the startup code in there automatically once Blazor has been started by .NET MAUI BlazorWebView.

So, in the meantime, I think using code like what you already wrote is fine. Handle the document load event and then wait until the function call succeeds.

BTW these are the two bugs that we will try to patch for .NET 6.x that are preventing JS initializers from working in .NET MAUI:

1. https://github.com/dotnet/aspnetcore/issues/42349
1. https://github.com/dotnet/aspnetcore/issues/42348

**Comment by fairking** [comment] 2022-06-23 17:07
> you just put the startup code in a file called `MyApp.lib.module.js`

The problem is I don't have any startup code: https://github.com/quasarframework/quasar/discussions/13725
The only think I can do is to inject the `index.js` file into the DOM.

**Comment by Eilon** [comment] 2022-06-23 18:36
Hi @fairking , I think there's something here that I'm not understanding. Can you explain the order of events that need to happen? Something like:


1. MAUI Blazor app is loaded
2. Blazor starts
3. Customer app startup code in XYZ.js is loaded
4. Quasar method `something()` is called
5. App's JS code has to call .NET code

I'm not familiar with Quasar so I'm not sure what the connection is between Blazor, the app, and Quasar.

**Comment by fairking** [comment] 2022-06-24 08:58
> @Eilon  Can you explain the order of events that need to happen?

1. UI Framework loaded by `index.xxxxxx.js` and `ui_app.boot()` function called (splash screen shown) (Please note: I have no control of this boot).
2. Inside the `boot()` function, start the Blazor and wait.
3. After the Blazor is started, call the backend to get the app settings.
4. Continue with starting the app, load/show the UI based on the settings.

BTW, settings are stored in sqlite database on the device.

**Comment by Eilon** [comment] 2022-06-24 17:50
I'm starting to wonder if there is simply some other solution that doesn't depend on this. Is there a reason that the app can't just let Blazor start whenever it wants, and let that other framework start whenever it wants, but everything is in a "loading...." state, and then once the settings are loaded, all the frameworks are told "here's your settings!" and then they process that data to do whatever they want? I think it's just unusual to have such a strict requirement on ordering things when everything is async anyway?

**Comment by fairking** [comment] 2022-06-24 18:28
The simple solution is to make `await Blazor.start()` working properly (windows platform has it working). If it's a problem with fixing this bug then I can try to workaround it somehow. I know it's going to be ugly but it's not the end of the world. Thanks.

**Comment by Eilon** [comment] 2022-06-24 18:36
Right, it's only on Android where `Blazor.start()` is special. Hopefully one day we can change that. But I think changing to a model where each framework/component/view is in a "loading..." state until its data is ready (such as settings) would be ideal, because that would continue to work no matter what else changes.

**Comment by javiercn** [comment] 2022-06-24 19:27
An initializer should work here. `afterStarted` runs after Blazor has started and the initial render has been triggered.

**Comment by javiercn** [comment] 2022-07-04 09:33
@Eilon is there anything else we need to do as a result of this issue?

**Comment by Eilon** [comment] 2022-07-05 15:39
@javiercn not from my perspective. As long as we do what we said in the comment https://github.com/dotnet/maui/issues/7965#issuecomment-1164635637 and fix the two issues in Blazor core, I think that is the correct long-term solution.

In the meantime, using various suggestions based on earlier discussions in this thread is the best workaround.

As such, I am closing this issue.

**Closed by Eilon** 2022-07-05 15:39 UTC
Labels: area/blazor 🕸️, s/verified

**Comment by fairking** [comment] 2022-07-05 16:45
Thank you guys for all your help and support 👍
