### ISSUE TITLE
ObjCRuntime.RuntimeException has been thrown

### ISSUE THREAD

**Issue by rohanmpalan** [dotnet/maui#13476] opened 2023-02-21 12:27 UTC
Failed to marshal the Objective-C object 0x60000297c000 (type: NSBundle). Could not find an existing managed instance for this object, nor was it possible to create a new managed instance (because the type 'Foundation.You_Should_Not_Call_base_In_This_Method' does not have a constructor that takes one NativeHandle argument).

**Comment by ramonB1996** [comment] 2023-02-21 12:42
Duplicate of #13748

**Comment by jsuarezruiz** [comment] 2023-02-21 15:45
Let's focus on https://github.com/dotnet/maui/issues/13478 Close this duplicate.

**Closed by jsuarezruiz** 2023-02-21 15:45 UTC
