### ISSUE TITLE
CollectionView shows no ScrollBar

### ISSUE THREAD

**Issue by SokoFromNZ** [dotnet/maui#11369] opened 2022-11-15 12:49 UTC
### Description

When filling a CollectionView with more data than fits on the screen I can scroll CollectionView, but no ScrollBar is shown. Not even if I set the `*ScrollBarVisibility` to `Always` or just do this with the `VerticalScrollBarVisibility` only.

### Steps to Reproduce

Create a new .NET MAUI .NET7 App in VS2022 and change those to files to the following (or load my reproduction repository):

MainPage.xaml
```xaml
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage
    x:Class="CollectionViewScrollBar.MainPage"
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:collectionViewScrollBar="clr-namespace:CollectionViewScrollBar"
    x:DataType="collectionViewScrollBar:MainPage">

    <CollectionView
        HorizontalScrollBarVisibility="Always"
        ItemsSource="{Binding Rows}"
        VerticalScrollBarVisibility="Always">
        <CollectionView.ItemTemplate>
            <DataTemplate x:DataType="collectionViewScrollBar:Row">
                <Grid RowDefinitions="Auto, Auto">
                    <Label
                        Grid.Row="0"
                        FontAttributes="Bold"
                        Text="{Binding Title}" />
                    <Label
                        Grid.Row="1"
                        FontAttributes="Italic"
                        Text="{Binding Detail}" />
                </Grid>
            </DataTemplate>
        </CollectionView.ItemTemplate>
    </CollectionView>

</ContentPage>
```

MainPage.xaml.cs
```csharp
using System.Collections.ObjectModel;

namespace CollectionViewScrollBar;

public partial class MainPage : ContentPage
{
	public MainPage()
	{
		InitializeComponent();
        BindingContext = this;

        for (var i = 0; i < 50; i++)
        {
            Rows.Add(new Row($"Title-{i}", $"Detail-{i}"));
        }
	}

    public ObservableCollection<Row>  Rows { get; } = new ();
}

public record Row(string Title, string Detail);
```
![image](https://user-images.githubusercontent.com/33326277/201924708-87acc03e-f430-452c-ad89-dd09476095d9.png)

With a ListView it works:
MainPage.xaml
```xaml
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage
    x:Class="CollectionViewScrollBar.MainPage"
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:collectionViewScrollBar="clr-namespace:CollectionViewScrollBar"
    x:DataType="collectionViewScrollBar:MainPage">

    <ListView ItemsSource="{Binding Rows}">
        <ListView.ItemTemplate>
            <DataTemplate x:DataType="collectionViewScrollBar:Row">
                <TextCell Detail="{Binding Detail}" Text="{Binding Title}" />
            </DataTemplate>
        </ListView.ItemTemplate>
    </ListView>

</ContentPage>
```
![image](https://user-images.githubusercontent.com/33326277/201924999-930d384c-bb9b-4827-b0cc-c54a29e9e054.png)

### Link to public reproduction project repository

https://github.com/SokoFromNZ/MauiCollectionViewScrollBar

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 11

### Did you find any workaround?

No

**Comment by SokoFromNZ** [comment] 2022-11-16 07:21
@Eilon @jsuarezruiz 
I was kinda schocked to see this go to the backlog!!

The official MAUI doc (https://learn.microsoft.com/en-us/dotnet/maui/user-interface/controls/collectionview/?view=net-maui-7.0) to CollectionView clearly stated to use the CollectionView over all other views!
It even says "It aims to provide a more flexible, and performant alternative to ListView." and even "CollectionView automatically utilizes the virtualization provided by the underlying native controls".

But I cannot use any CollectionView in my whole app if the user cannot see if there is more data to scroll. So this should be a Prio-A bug.

I am feeling the pain MAUI puts on developers since day one (also see https://github.com/dotnet/maui/issues/8602). In Mai we had plans to release our product in January, But instead of implementing our business logic, all we do is try to find workarounds for MAUI bugs to get even the simpliest things done...
We even cut back from releasing an Android, iOS and Windows version to just Android, but not even the rudimental things in Android work! And now you moving this to the backlog?!

I am frustrated...

**Comment by EmberLynn** [comment] 2022-11-18 21:09
> @Eilon @jsuarezruiz I was kinda schocked to see this go to the backlog!!
> 
> The official MAUI doc (https://learn.microsoft.com/en-us/dotnet/maui/user-interface/controls/collectionview/?view=net-maui-7.0) to CollectionView clearly stated to use the CollectionView over all other views! It even says "It aims to provide a more flexible, and performant alternative to ListView." and even "CollectionView automatically utilizes the virtualization provided by the underlying native controls".
> 
> But I cannot use any CollectionView in my whole app if the user cannot see if there is more data to scroll. So this should be a Prio-A bug.
> 
> I am feeling the pain MAUI puts on developers since day one (also see #8602). In Mai we had plans to release our product in January, But instead of implementing our business logic, all we do is try to find workarounds for MAUI bugs to get even the simpliest things done... We even cut back from releasing an Android, iOS and Windows version to just Android, but not even the rudimental things in Android work! And now you moving this to the backlog?!
> 
> I am frustrated...

As a person building an app in MAUI for the first time (first time building an app ever), I assumed that what was written in the documentation was what is actually currently working in MAUI. It's frustrating when the answer is plain as day in the documentation, you follow it, only for it to perform in an unpredictable manner.

I have tried and tried to use the "recommend" CollectionView only for it to never perform as the documentation states. The newest issue I have encountered is not being able to scroll through the CollectioView (thus, how I found this issue!).

Anyway, I too am frustrated and surprised that every issue I encounter (including this) is put on the backlog.

**Comment by drasticactions** [comment] 2022-12-07 15:43
<img width="425" alt="スクリーンショット 2022-12-08 0 42 38" src="https://user-images.githubusercontent.com/898335/206224110-a5650794-23a8-4879-926c-744ffee8c4b5.png">

Checking this against Xamarin.Forms, Forms doesn't seem to respect the Always Visible setting either for Android, but it does show the bar when scrolling. MAUI does show nothing in main.

**Comment by SokoFromNZ** [comment] 2023-05-11 18:14
Any update on this guys? Unbelievable nothing happend here in half a year!
I really need a list in MAUI where I can select multiple rows... ListView cannot do this... CollectionView is not usable...
Any suggestions?

**Comment by HobDev** [comment] 2023-06-07 06:14
Facing this issue on Windows. The scrollbar is only visible when user clicks below the CollectionView. Although I set the ScollBarVisibility to always.

**Comment by mtarros** [comment] 2023-08-22 00:24
Here is the work around that I used to resolve this issue.

Create a handler and add the following into the ConnectHandler
platformView.VerticalScrollBarEnabled = true;
platformView.ScrollBarStyle = Android.Views.ScrollbarStyles.InsideOverlay;
platformView.VerticalScrollbarThumbDrawable = AppCompatResources.GetDrawable(this.Context, Resource.Drawable.scrollview_thumb);
platformView.ScrollbarFadingEnabled = true;


Create resource file in Android Drawables - scrollview_thumb.xml
<?xml version="1.0" encoding="utf-8"?>
<shape xmlns:android="http://schemas.android.com/apk/res/android">
	<gradient android:startColor="#B8B8B8" android:endColor="#B8B8B8"
        android:angle="45" />
	<corners android:radius="6dp" />
</shape>

**Comment by sergeykonar** [comment] 2023-09-15 10:28
I have the same issue with CollcetionView

**Comment by scriptBoris** [comment] 2023-12-11 04:52
OMG

**Comment by gubhit1s** [comment] 2023-12-23 06:29
This is still not fixed in MAUI 8

**Comment by zeldomar** [comment] 2023-12-27 15:27
> Here is the work around that I used to resolve this issue.
> 
> Create a handler and add the following into the ConnectHandler platformView.VerticalScrollBarEnabled = true; platformView.ScrollBarStyle = Android.Views.ScrollbarStyles.InsideOverlay; platformView.VerticalScrollbarThumbDrawable = AppCompatResources.GetDrawable(this.Context, Resource.Drawable.scrollview_thumb); platformView.ScrollbarFadingEnabled = true;
> 
> Create resource file in Android Drawables - scrollview_thumb.xml

Hello,

Can you give us more details about your workaround, please?
I'm very interesting!

Thanks!

**Comment by axeldietz** [comment] 2024-01-14 09:06
We are in 2024 now...

**Comment by owik100** [comment] 2024-01-14 12:31
I found a nice workaround. Instead of CollectionView i use [DevExpress CollectionView](https://docs.devexpress.com/MAUI/403324/collection-view/index)  Scrollbar is visible, also performance is better in scrolling

**Comment by zeldomar** [comment] 2024-01-14 12:36
> I found a nice workaround. Instead of CollectionView i use [DevExpress CollectionView](https://docs.devexpress.com/MAUI/403324/collection-view/index) Scrollbar is visible, also performance is better in scrolling

Are you sure that DevExpress.CollectionView offers fast scrolling?

**Comment by owik100** [comment] 2024-01-14 14:01
> > I found a nice workaround. Instead of CollectionView i use [DevExpress CollectionView](https://docs.devexpress.com/MAUI/403324/collection-view/index) Scrollbar is visible, also performance is better in scrolling
> 
> Are you sure that DevExpress.CollectionView offers fast scrolling?

If you means "no lags" then yes, i achieved better performance when scrolling in a view with grid and images.

**Comment by zeldomar** [comment] 2024-01-14 14:18
> > Are you sure that DevExpress.CollectionView offers fast scrolling?
> 
> If you means "no lags" then yes, i achieved better performance when scrolling in a view with grid and images.

No, here is the fast scrolling :

![image](https://github.com/dotnet/maui/assets/4940892/b7488244-4ff4-41e3-aa01-d82dee438fd3)

**Comment by zeldomar** [comment] 2024-01-14 14:21
> > > I found a nice workaround. Instead of CollectionView i use [DevExpress CollectionView](https://docs.devexpress.com/MAUI/403324/collection-view/index) Scrollbar is visible, also performance is better in scrolling
> > 
> > 
> > Are you sure that DevExpress.CollectionView offers fast scrolling?
> 
> If you means "no lags" then yes, i achieved better performance when scrolling in a view with grid and images.

No, here is fast scrolling :

![Uploading 1_HliXJE2zpLAXWmXusOFSSA.gif…]()

**Comment by scriptBoris** [comment] 2024-01-14 18:44
2024 year...

**Comment by vvoois** [comment] 2024-01-24 08:08
Depending on which platforms you aim for...
For Windows, this is a crucial property:
VerticalOptions="FillAndExpand"

              <CollectionView x:Name="myCollectionView" VerticalOptions="FillAndExpand"
                              RemainingItemsThreshold="5" 
                              RemainingItemsThresholdReached="OnRemainingItemsThresholdReached" 
                              RemainingItemsThresholdReachedCommand="{Binding LoadMoreDataCommand}">
                  <CollectionView.ItemTemplate>
                  
FillAndExpand sets the constraints of the CollectionView so that room for the scrollbar(s) can be calculated.

I can understand the generic struggle because it is not mentioned on the Microsoft documentation page, but they actually should have amplified this matter somewhere there.
https://learn.microsoft.com/en-us/dotnet/maui/user-interface/controls/collectionview/scrolling?view=net-maui-8.0

**Comment by shushu789** [comment] 2024-02-21 08:39
I also found the same issue, originally my question was related to this #8888 , but it was closed because they thought it was normal design

**Comment by SlavomirDev** [comment] 2024-04-10 15:39
Still not fixed...
It would also be better if we could change the color of the scrollbar...

**Comment by TalionOak** [comment] 2024-05-07 15:34
still not fixed, changed to listview to fix my problem, sad

**Comment by TalionOak** [comment] 2024-05-07 16:10
What I've discovered is that this won't be fixed as it was done by design. Stacklayout or ContentPage will expand and have an infinite height or the height for all items of the CollectionView. You will need to use a Grid if you want to size to screen and get the scroll.

How to fix:
```xaml
<ContentPage
    x:Class="Wallet.Views.Transactions.TransactionList"
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml">
    
    <Grid ColumnDefinitions="*" RowDefinitions="auto,*">
  <!-- Other code Grid.Row="0".. -->
        <CollectionView
            x:Name="Collection"
            Grid.Row="1">
        </CollectionView>
    </Grid>
</ContentPage>
```

**Comment by Thx1010saascas** [comment] 2024-05-19 03:57
Is the CollectionView supposed to scroll just its items or is whole header/footer supposed to scroll too? It is crazy if the header/footer are in the scroll area. In every other framework ever, they are static and just the items scroll.

The above is using a Grid and using a fixed or "*" row height doesn't change anything. So, it is either a bug, or very poor design.  

I thought Maui was supposed to be the latest and greatest, but clearly not for Windows apps anyway given how backwards it seems to be. Blazor is far nicer. I lost days trying to convert my WPF to make it work at least as well as in WPF but that just isn't possible. Hell, out of the box, in "light" mode even the Picker and Editor glyphs are white on a white background with no way to fix it AFAICS except to make the background, not white!

**Comment by anotherlab** [comment] 2024-06-14 13:29
I'm seeing this on a page that only uses grids to layout the controls.  I'm migrating a Xamarin.Forms app to .NET MAUI and I had to replace a ListView because I couldn't set the selected item background color.  Which is documented as issue #13812 

This is a regression from Xamarin.Forms, will it be addressed in .NET 9?

**Comment by OliveInto** [comment] 2024-08-09 03:53
> > Here is the work around that I used to resolve this issue.
> > Create a handler and add the following into the ConnectHandler platformView.VerticalScrollBarEnabled = true; platformView.ScrollBarStyle = Android.Views.ScrollbarStyles.InsideOverlay; platformView.VerticalScrollbarThumbDrawable = AppCompatResources.GetDrawable(this.Context, Resource.Drawable.scrollview_thumb); platformView.ScrollbarFadingEnabled = true;
> > Create resource file in Android Drawables - scrollview_thumb.xml
> 
> Hello,
> 
> Can you give us more details about your workaround, please? I'm very interesting!
> 
> Thanks!



![image](https://github.com/user-attachments/assets/450c13f0-7d33-4303-9829-5ff762ecf004)
![image](https://github.com/user-attachments/assets/73eedfeb-3c4b-43bd-a807-58bb845657cb)
![image](https://github.com/user-attachments/assets/c5859233-190b-477d-a777-2f2e52ecf314)

Prepare resources first, and Call the below Funtion when program start. You can change colors in scrollview_thumb or something else, just refer to android develop documents.
😭There are so many bugs in maui.

```
        private void ModifyCollectionView()
        {

            Microsoft.Maui.Controls.Handlers.Items.CollectionViewHandler.Mapper.AppendToMapping("MyCustomization", (handler, view) =>
            {
#if ANDROID
                handler.PlatformView.VerticalScrollBarEnabled = true;
                handler.PlatformView.ScrollBarStyle = Android.Views.ScrollbarStyles.OutsideOverlay;
                handler.PlatformView.VerticalScrollbarThumbDrawable = AppCompatResources.GetDrawable(Microsoft.Maui.ApplicationModel.Platform.AppContext, Resource.Drawable.scrollview_thumb);
                handler.PlatformView.ScrollbarFadingEnabled = true;
                handler.PlatformView.ScrollBarSize = 50;
#elif IOS || MACCATALYST
           
#elif WINDOWS
          
#endif
            });
        }
```

**Comment by smardine** [comment] 2024-08-22 16:03
Could you, by any chance share your scrollview_thumb file?

Your workaround work well, thanks for that 😁

**Comment by OliveInto** [comment] 2024-08-24 11:31
> Could you, by any chance share your scrollview_thumb file?
> 
> Your workaround work well, thanks for that 😁

I made a simple one, please change the color value to fixed before using it, since the color value in my xml is stored in colors.xml
```

<?xml version="1.0" encoding="utf-8"?>
<shape xmlns:android="http://schemas.android.com/apk/res/android"
    android:shape="rectangle" >
  <corners android:radius="4dp" />
  <solid android:color="@color/customColorScrollbar"/>
</shape>
```

**Comment by smardine** [comment] 2024-08-24 12:43
Super thanks for that 😁

**Comment by mtarros** [comment] 2024-08-24 21:46
Thanks for sharing the thumb file.  

I don't have access code anymore but was going to say you could probably use Googles Material design to get the icon.

**Comment by kubaflo** [comment] 2024-10-23 12:54
Hi all! Here's a fix: https://github.com/dotnet/maui/pull/25471

**Closed** 2024-12-18 07:52 UTC
Labels: t/bug, platform/android 🤖, p/2, area-controls-collectionview, s/verified, s/triaged, delighter-sc
