### ISSUE TITLE
XamlC error XFC0000 when building migrated MAUI app in VS

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#13912] opened 2023-03-14 16:22 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/XamlC-error-XFC0000-when-building-migrat/10308568)._

---
We’ve been working on migrating our Xamarin.Forms app over to .NET MAUI for a few weeks now. After running the upgrade assistant on the solution, I’ve been fixing build errors in the Portabl project. We also have iOS and Android head projects. Apart from the other build errirs, we’ve been plauged with 170 mysterious XamlC errors like these:

ridecommand-app/Portable/App.xaml: Error:  : XamlC error XFC0000 : Cannot resolve type &quot;Application&quot;.
ridecommand-app/Portable/Controls/ActivityItemDetailsView.xaml: Error:  : XamlC error XFC0000 : Cannot resolve type &quot;StackLayout&quot;.
ridecommand-app/Portable/Pages/MoreTab/MorePage.xaml: Error:  : XamlC error XFC0000 : Cannot resolve type &quot;ContentPage&quot;.
ridecommand-app/Portable/Pages/Settings/NotificationSettingsPage.xaml: Error:  : XamlC error XFC0000 : Cannot resolve type &quot;Switch&quot;.

I’ve focuessed on fixing the other build errors hoping the XamlC ones would go away, but now that we’ve fixed all other build errors in the Portable project, they’re still here

---
#### Feedback Bot on 3/13/2023, 08:14 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by mattleibow** [comment] 2023-03-14 19:28
Duplicate of #13666

**Closed by mattleibow** 2023-03-14 19:28 UTC
Labels: t/bug, area/Xaml </>, p/1, area/migration 🚚, partner/cat 😻
