### ISSUE TITLE
TabbedPage + Data Template will crash on switching tab

### ISSUE THREAD

**Issue by ReneeGA2020** [dotnet/maui#26811] opened 2024-12-25 14:37 UTC
### Description

I failed to make TabbedPage work with Data Template.
This thing worked in an earlier version of MAUI years ago.

### Steps to Reproduce

1. Create New MAUI app
2. Use Page Window instead of shell.
3. Add a simple TabbedPage with data Template 

>     <TabbedPage.ItemsSource>
>         <x:Array Type="{x:Type x:String}">
>             <x:String>Home</x:String>
>             <x:String>Settings</x:String>
>         </x:Array>
>     </TabbedPage.ItemsSource>
>     <TabbedPage.ItemTemplate>
>         <DataTemplate>
>             <ContentPage Title="{Binding}">
>                 <Label Text="{Binding}"/>
>             </ContentPage>
>         </DataTemplate>
>     </TabbedPage.ItemTemplate>

4. Run the app
5. Switch to another tab
Result->Crash

### Link to public reproduction project repository

https://github.com/ReneeGA2020/TabbedPageDataTemplateBug

### Version with bug

9.0.21 SR2.1

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Affected platforms

Windows

### Relevant log output

```shell

```

**Comment by jfversluis** [comment] 2024-12-25 15:30
Duplicate of #14572

**Closed by jfversluis** 2024-12-25 15:30 UTC
Labels: t/bug
