### ISSUE TITLE
Partial Classes in Platform Folders Causing Ambiguity Errors

### ISSUE THREAD

**Issue by cbaer-extron** [dotnet/maui#6198] opened 2022-04-18 18:39 UTC
### Description

The last few Previews and RC1 are not handling Maui platform folders correctly.  When compiling I receive multiple CS0111 errors and CS0121 errors (as shown in the screen capture).  This occurs in a Maui App and a Maui Library.  

The app does build and deploy, but the errors make it very difficult to debug because for every cross platform class and methods, I receive 4 errors.  This was not the case in earlier previews.
![image](https://user-images.githubusercontent.com/101732760/163856069-121d0a4e-6d34-4a93-b85c-37fe5147e666.png)

### Steps to Reproduce

1.  Create a new Maui app
2.  Add a class and make it a public partial class, and give it an appropriate namespace.  This is the shared class.
3.  Add to the class one public property that gets its value from method not contained within this part of the partial class.
4.  add the same partial class to each platform folder
5.  Use the same namespace that was used in the shared class
6.  Add the method to be used to provide the value for the property that was defined in the shared class.
7.  Compile the app and notice that you get the ambiguity errors.

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Preview 12

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

Android 11, Windows 10, iOS, Mac Monterey

### Did you find any workaround?

Yes.  You can add this to the project file.  The errors go away.  But then you can only view one platform folder at a time.

<ItemGroup>
		<Compile Remove="Platforms\Android\*.cs" />
		<Compile Remove="Platforms\iOS\*.cs" />
		<Compile Remove="Platforms\MacCatalyst\*.cs" />
		<Compile Remove="Platforms\Windows\*.cs" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net6.0-android'">
		<Compile Include="Platforms\Android\*.cs" />
		<Compile Remove="Platforms\iOS\*.cs" />
		<Compile Remove="Platforms\MacCatalyst\*.cs" />
		<Compile Remove="Platforms\Windows\*.cs" />
	</ItemGroup>

	<ItemGroup Condition="$(TargetFramework.Contains('-windows'))">
		<Compile Remove="Platforms\Android\*.cs" />
		<Compile Remove="Platforms\iOS\*.cs" />
		<Compile Remove="Platforms\MacCatalyst\*.cs" />
		<Compile Include="Platforms\Windows\*.cs" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net6.0-ios'">
		<Compile Remove="Platforms\Android\*.cs" />
		<Compile Include="Platforms\iOS\*.cs" />
		<Compile Remove="Platforms\MacCatalyst\*.cs" />
		<Compile Remove="Platforms\Windows\*.cs" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net6.0-maccatalyst'">
		<Compile Remove="Platforms\Android\*.cs" />
		<Compile Remove="Platforms\iOS\*.cs" />
		<Compile Include="Platforms\MacCatalyst\*.cs" />
		<Compile Remove="Platforms\Windows\*.cs" />
	</ItemGroup>

**Comment by cbaer-extron** [comment] 2022-04-18 18:48
Here is a link to the project:
https://github.com/cbradbaer/BugReports/tree/main/PlatformFolders

**Comment by kristinx0211** [comment] 2022-04-19 01:01
@cbaer-extron thanks for your report. I've verified your repro project on vs 17.3.0 Preview 1.0 [32415.490.main], but not repro this issue, the project can be build and run with no errors. see:
![image](https://user-images.githubusercontent.com/99457000/163899641-3ac80f3b-23b6-4843-bbe5-bf59af2add83.png)

**Comment by cbaer-extron** [comment] 2022-04-20 15:37
Yes, as I mentioned in my description, "The app does build and deploy, but the errors make it very difficult to debug because for every cross platform class and methods, I receive 4 errors. This was not the case in earlier previews."

Even though it built, look in the Error Window and you will probably see the same errors I got.  So in a real project, I am going to get dozens and dozens of errors for all of the platform specific implementations I have written.

**Comment by Redth** [comment] 2022-04-20 18:03
Duplicate of #4726

**Closed by Redth** 2022-04-20 18:03 UTC
Labels: t/bug, s/verified, area/ide
