### ISSUE TITLE
.NET 8 Preview 6 MAUI project fails to build for Android in the command line as it's unable to detect the Android SDK path

### ISSUE THREAD

**Issue by egvijayanand** [dotnet/maui#16091] opened 2023-07-11 21:54 UTC
### Description

.NET 8 Preview 6 MAUI project fails to build for Android in the command line as it's unable to detect the Android SDK path.

Android SDK is installed in the `%LocalAppData%\Android\Sdk` folder on my machine.

And .NET CLI is repeatedly looking for the SDK from the **Program Files** folder.

After installing the latest preview version of VS2022 (17.7 Preview 3.0), found that the Android SDK path is reset to Program Files, have manually modified the setting to rightly point it to the Local AppData folder.

VS Setting:
Xamarin -> Android Settings -> Android SDK Location

Post update of this setting, it is working inside VS IDE.

But it fails to build on the CLI.

Have tried setting the ANDROID_HOME and ANDROID_SDK_ROOT environment variables and even added the path to the PATH environment variable. But ended in vain as it always looks for the Android SDK from the Program Files folder (refer to the log section).

~~Note: Have selected the **Version with bug** field as **Unknown/Other** as the **.NET 8 Preview 6** is not yet added.~~

### Steps to Reproduce

1. Create a new .NET MAUI project (dotnet new maui)
2. Build the project targeting the Android platform (dotnet build -f net8.0-android)

### Link to public reproduction project repository

Default template itself is suffice, no authored code

### Version with bug

8.0.0-preview.6.8686

### Last version that worked well

8.0.0-preview.5.8529

### Affected platforms

Android

### Affected platform versions

Android 34.0

### Did you find any workaround?

Validate and Update, if necessary, the value of Android SDK location within VS IDE. That's the only option for now.

Refer to the comments for a workaround.

### Relevant log output

```shell
C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.0-preview.6.359\tools\Xamarin.Android.Tooling.targets(100,5): error
 XA5207: Could not find android.jar for API level 34. This means the Android SDK platform for API level 34 is not installed. Either
install it in the Android SDK Manager (Tools > Android > Android SDK Manager...), or change the Xamarin.Android project to target an
 API version that is installed. (C:\Program Files (x86)\Android\android-sdk\platforms\android-34\android.jar missing.) [E:\MAUI\NET_8\Preview_6\MauiApp2\MauiApp2.csproj::TargetFramework=net8.0-android]
```

**Comment by egvijayanand** [comment] 2023-07-12 22:06
For the time being, have found a workaround for building the project for the Android platform from CLI.

The Android SDK path is controlled by the MSBuild project property named `AndroidSdkDirectory`.

Pass the correct SDK path as a value for this property while executing the `dotnet build` command as mentioned below.

```shell
dotnet build -f net8.0-android -p:AndroidSdkDirectory=%LocalAppData%\Android\Sdk
```
As usual for running the project, add the `-t:Run` property in addition.

Ideally, dotnet CLI should refer to the location from somewhere in a hierarchy, but it failed to do so in this preview version. This needs to be looked into as builds on CI solely rely on these commands.

**Pro Tip:** This can be written as a batch file to automate the process so that it need not be typed again and again.

_%LocalAppData% is an OS environment variable that will automatically point to the current user's local application data directory._

**Comment by egvijayanand** [comment] 2023-07-12 22:08
Reference links:

https://learn.microsoft.com/en-us/xamarin/android/errors-and-warnings/xa5300

https://learn.microsoft.com/en-us/xamarin/android/troubleshooting/questions/android-sdk-location?tabs=windows

**Comment by egvijayanand** [comment] 2023-07-13 23:51
Seems like I found the core problem, .NET CLI is proactively making use of a single quote (`'`) assuming that there would be a space in the path of the Android SDK directory (maybe due to the influence of the Program Files folder). But when a single quote is used within the CLI, it is complaining. This could be due to the way MSBuild parameters are being parsed.

The below command with the value within the single quotes is failing with the same error as like without the `AndroidSdkDirectory` property mentioned.

```shell
dotnet build -f net8.0-android -p:AndroidSdkDirectory='%LocalAppData%\Android\Sdk'
```

Whereas the value within the double quotes works perfectly fine.

```shell
dotnet build -f net8.0-android -p:AndroidSdkDirectory="%LocalAppData%\Android\Sdk"
```

**Comment by maddymontaquila** [comment] 2023-07-14 18:05
cc @jonathanpeppers @jonpryor

**Comment by egvijayanand** [comment] 2023-07-16 10:31
Referencing this comment as it describes this issue in simple terms.

https://github.com/microsoft/vscode-dotnettools/issues/250#issuecomment-1636275498

**Comment by jonathanpeppers** [comment] 2023-07-17 14:38
If the issue is indeed changing JavaScript code to use double quotes (instead of single). We can probably close the issue here.

@egvijayanand did you notice a problem in ordering of finding the Android SDK? (code for this is [here](https://github.com/xamarin/xamarin-android-tools))

I wonder if the logic is always going to prefer the value set in Visual Studio, and this would prevent you from using environment variables like `$ANDROID_HOME`, `$ANDROID_SDK_ROOT`, etc. This logic has been here since Xamarin, and there was no VS Code support back then.

**Closed** 2023-11-16 01:01 UTC
Labels: t/bug, s/needs-info, s/no-recent-activity

**Comment by SoumyadipYT-OSS** [comment] 2023-11-22 07:50
I am facing another issue when I run the command dotnet build in the dotnetMAUI App project in visual studio 2022


![Screenshot (2)](https://github.com/dotnet/maui/assets/94290293/310bf8e1-12c5-4d15-a35e-de47d911380d)

Unable to understand this issue.

**Comment by egvijayanand** [comment] 2023-11-22 09:39
Hi @SoumyadipYT-OSS,

If you're running .NET MAUI on .NET 8, you need to have **Android SDK 34**.

First check the location where Android SDK is pointing to: VS2022 -> Tools -> Options -> Xamarin -> SDK Location

Then check whether this folder `...\android-sdk\platforms\android-34` exists over there.

If not, install and then try.

**Comment by SoumyadipYT-OSS** [comment] 2023-11-22 17:58
Hi @egvijayanand,
I am using .NET MAUI on .NET 8 framework, and already have Android SDK 34. But still after running the command "dotnet build" in the output it shows an error.

**Comment by egvijayanand** [comment] 2023-11-22 18:02
Try this:
```shell
dotnet build -f net8.0-android -p:AndroidSdkDirectory=<path_here>
```
You need to pass the location of the SDK directory as the value to the MSBuild property. If the path contains space, surround it with quotes.

**Comment by SoumyadipYT-OSS** [comment] 2023-11-22 18:08
After implementing this code 
I have written in the powershell developer terminal:                                                                                  
 dotnet build -f net8.0-android -p:AndroidSdkDirectory=E:\Android\android-sdk\platforms\android-34


C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.43\tools\Xamarin.Android.Toolin
g.targets(100,5): error XA5207: Could not find android.jar for API level 34. This means the Andr
oid SDK platform for API level 34 is not installed. Either install it in the Android SDK Manager
 (Tools > Android > Android SDK Manager...), or change the Xamarin.Android project to target an
API version that is installed. (E:\Android\android-sdk\platforms\android-34\platforms\android-34
\android.jar missing.) [D:\dotnet MAUI practice\ToDo_app\MauiApp2\MauiApp2.csproj::TargetFramewo
rk=net8.0-android]

Build FAILED.

C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.43\tools\Xamarin.Android.Toolin
g.targets(100,5): error XA5207: Could not find android.jar for API level 34. This means the Andr
oid SDK platform for API level 34 is not installed. Either install it in the Android SDK Manager
 (Tools > Android > Android SDK Manager...), or change the Xamarin.Android project to target an
API version that is installed. (E:\Android\android-sdk\platforms\android-34\platforms\android-34
\android.jar missing.) [D:\dotnet MAUI practice\ToDo_app\MauiApp2\MauiApp2.csproj::TargetFramewo
rk=net8.0-android]
    0 Warning(s)
    1 Error(s)

**Comment by egvijayanand** [comment] 2023-11-22 18:10
> dotnet build -f net8.0-android -p:AndroidSdkDirectory=E:\Android\android-sdk\platforms\android-34

AndroidSdkDirectory should point only to the root directory.

dotnet build -f net8.0-android -p:AndroidSdkDirectory=E:\Android\android-sdk

**Comment by egvijayanand** [comment] 2023-11-22 18:12
And what's your **Xamarin** Setting has inside VS2022 @SoumyadipYT-OSS , if it's the same path. Then @jonathanpeppers kindly reopen the issue. It's not yet resolved.

**Comment by SoumyadipYT-OSS** [comment] 2023-11-22 18:21
@egvijayanand how to find the path of Xamarin Setting has inside VisualStudio2022?

**Comment by egvijayanand** [comment] 2023-11-22 18:22
Check earlier comment👆

**Comment by SoumyadipYT-OSS** [comment] 2023-11-26 05:36
@egvijayanand Thank you issue solved. Have a great day
