### ISSUE TITLE
System.InvalidOperationException: NavHost cannot be null

### ISSUE THREAD

**Issue by ac-lap** [dotnet/maui#19809] opened 2024-01-10 18:07 UTC
### Description

I have a .net MAUI app published to Play Store, from the Microsoft Appcenter diagnostics I am seeing this exception resulting into crashes in production. I need help to understand why this could be happening and how to fix it.

It has only the following stack trace for all crashes, no other events. Would really appreciate some help to understand this issue.

```
System.InvalidOperationException: NavHost cannot be null

Microsoft.Maui.Platform.StackNavigationManager.get_NavHost()
Microsoft.Maui.Platform.NavigationViewFragment.OnResume()
AndroidX.Fragment.App.Fragment.n_OnResume(IntPtr , IntPtr )
Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V(_JniMarshal_PP_V , IntPtr , IntPtr )
```

### Version with bug

8.0.5

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

**Comment by mattleibow** [comment] 2024-01-10 19:04
Duplicate of https://github.com/dotnet/maui/issues/15788

**Closed** 2024-01-10 19:04 UTC
Labels: t/bug
