### ISSUE TITLE
[regression/8.0.0-preview.7.8842] System.TypeLoadException with .NET 8

### ISSUE THREAD

**Issue by williambuchanan2** [dotnet/maui#17136] opened 2023-08-31 11:24 UTC
### Description

Getting the below errors when trying to run the Hello Maui app in .NET 8 on Mac.

This is just the basic Hello Maui click counter app with no modifications other than changing it to .NET 8.

Could not resolve type with token 0100001c from typeref (expected class 'System.Runtime.CompilerServices.NullableAttribute' in assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')

StackTrace	System.TypeLoadException: Could not resolve type with token 0100001a from typeref (expected class 'System.Runtime.CompilerServices.NullableContextAttribute' in assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')	string

![Screenshot 2023-08-31 at 9 25 34 pm](https://github.com/dotnet/maui/assets/32165641/8cd98f47-65c2-4f89-bd1a-297f6b64f824)
<img width="1728" alt="Screenshot 2023-08-31 at 9 25 34 pm (2)" src="https://github.com/dotnet/maui/assets/32165641/0bb92273-7e13-4c9a-8210-3ad39b9a044a">

### Steps to Reproduce

Create new Maui app.
Change TargetFramework to net8.0-ios
Run
Boom

### Version with bug

8.0.0-preview.7.8842

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.92

### Affected platforms

iOS

### Affected platform versions

iOS 15

### Did you find any workaround?

No

### Relevant log output

```shell
System.TypeLoadException: Could not resolve type with token 0100001c from typeref (expected class 'System.Runtime.CompilerServices.NullableAttribute' in assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
```

**Comment by williambuchanan2** [comment] 2023-08-31 12:01
> Does the same happen if you build and deploy from the command line? If you clean the bin/obj folders and rebuild, does it still happen?

Yep, went through the usual cleaning rituals and command line deploy but still happens. Happening on both iPhone simulator and physical device.

**Comment by williambuchanan2** [comment] 2023-09-01 01:11
I have more information on this now. It looks like something to do with the prerelease nuget updates.

When I create a new project and just click run without doing anything else it works ok. But looking in the solution explorer shows 3 updates:

![Screenshot 2023-09-01 at 10 58 43 am](https://github.com/dotnet/maui/assets/32165641/0520e9ea-a484-455e-8ad4-62a998b9d4dd)

when I update any 1 of these I get the error:

![Screenshot 2023-09-01 at 10 59 22 am](https://github.com/dotnet/maui/assets/32165641/125c7a26-c91a-4c7a-be0e-6c91d09eb114)

I have tried doing them 1 at a time in 3 different new projects and updating any 1 of them causes the problem.

**Comment by PureWeen** [comment] 2023-09-06 14:26
@williambuchanan2 can you attach your app that's crashing?

**Comment by gabsamples6** [comment] 2023-09-07 06:23
We are getting it this too - in our real app - works in .net 7 but crashes the app when loading the main page - trying to isolate the issue but tricky - 
![image](https://github.com/dotnet/maui/assets/109357537/2419bd6e-0375-4055-a1ea-01dc890ba53f)

**Comment by williambuchanan2** [comment] 2023-09-07 22:10
[MauiTestAppNotWorking.zip](https://github.com/dotnet/maui/files/12553751/MauiTestAppNotWorking.zip)
[MauiTestAppWorking.zip](https://github.com/dotnet/maui/files/12553752/MauiTestAppWorking.zip)

**Comment by williambuchanan2** [comment] 2023-09-07 22:11
I just uploaded 2 zip files.

The one named Working is the one which works - as I said it's just a new Maui project then click run and it works.

The one named not working is the same project but after I did the nuget updates.

**Comment by williambuchanan2** [comment] 2023-09-10 00:23
Is there any way to uninstall the .NET 8 SDK from my mac? I stupidly followed the instructions here:

https://devblogs.microsoft.com/dotnet/announcing-dotnet-maui-in-dotnet-8-preview-6/ 

And now VS on my mac is compeltely screwed.

**Comment by williambuchanan2** [comment] 2023-09-10 03:45
Had to do a complete uninstall of VS, Maui, and my workspace, then reinstall everything to get it working again...

**Comment by gabsamples6** [comment] 2023-09-10 08:12
@williambuchanan2 hi just for clarity are you saying that by reinstalling everything from scratch you dont get the typeloader exception?

if that is the case and I hope you are right does this work for you https://github.com/dotnet/maui/issues/17265?  I am using syncfusion controls too and my app is getting this error.

Thanks

**Comment by williambuchanan2** [comment] 2023-09-10 08:15
> @williambuchanan2 hi just for clarity are you saying that by reinstalling everything from scratch you dont get the typeloader exception?
> 

Sorry no I just meant I am now able to get net7 code working again.

**Comment by gabsamples6** [comment] 2023-09-10 09:45
@williambuchanan2  thanks for replying. I see... We are stuck with .net 7 when most of the fixes are in .net 8 and we cannot even launch the app and RC1 will be made available this week and you cannot even load a real world app... 

@samhouts  any hope to have this fixed in a night build soon?

**Comment by williambuchanan2** [comment] 2023-09-10 10:09
> @williambuchanan2 thanks for replying. I see... We are stuck with .net 7 when most of the fixes are in .net 8 and we cannot even launch (net 8 RC1) and RC1 will be made available this week and you cannot even load a real world app...

Pretty much sums it up. Great isn't it. BTW, don't get your hopes up about .NET 8 being any better.

**Comment by PureWeen** [comment] 2023-09-11 01:51
> [MauiTestAppNotWorking.zip](https://github.com/dotnet/maui/files/12553751/MauiTestAppNotWorking.zip) [MauiTestAppWorking.zip](https://github.com/dotnet/maui/files/12553752/MauiTestAppWorking.zip)

Does it work if you try and deploy via the CLI or use C# Dev Kit?

**Comment by williambuchanan2** [comment] 2023-09-11 01:54
Building it in Azure Devops pipeline seems to work ok.

dotnet publish MauiTestApp.sln -f net8.0-ios -c Release

**Comment by samhouts** [comment] 2023-09-13 00:57
@gabsamples6 Please see the latest comment on #17265 for the issue with SyncFusion.

**Comment by williambuchanan2** [comment] 2023-09-13 01:01
What even is SyncFusion? It's not something I have used or put into the project. As I said - this was an un-edited version of the click counter app (File -> New Project -> Maui Application -> Run), so whatever is in there was put in by someone at Microsoft...

**Comment by samhouts** [comment] 2023-09-13 01:03
@williambuchanan2 I wonder if you had .NET SDK preview 6 installed when you updated MAUI to preview 7. That should be possible, but it looks like there's a bug with VS Mac that allows you to update the NuGets for the MAUI workloads independent from the .NET SDK.

BTW, SyncFusion is a third party vendor that create nifty controls for .NET MAUI. For your case, you can ignore it. I mistakenly marked the SyncFusion issue as a duplicate of this one.

**Comment by williambuchanan2** [comment] 2023-09-13 01:06
This is a brand new macbook. I installed VS for Mac and used it for a few days with our other .NET 7 app. The only other thing I did was install .NET 8 in line with the instructions here:

https://devblogs.microsoft.com/dotnet/announcing-dotnet-maui-in-dotnet-8-preview-6/ 

Note that it's not just happening to me... Also note, there are a lot of issues with VS for Mac. It's almost impossible to get it to build and run (also not just happening to me)...

**Comment by samhouts** [comment] 2023-09-13 01:10
I understand your frustration, and I'm very sorry you're experiencing these issues! You may want to try VS Code C# Dev Kit for .NET MAUI to see if you have an improved experience on the Mac. As it is in preview, we would appreciate your feedback.

**Comment by williambuchanan2** [comment] 2023-09-13 01:19
Thank you. Yes it is, but I will try VS Code...

**Comment by samhouts** [comment] 2023-09-14 00:01
Thanks! If you're able to get a clean install working with VSCode, let us know if you're still seeing this issue. We're having trouble reproducing it.

**Comment by AllenD-MSFT** [comment] 2023-10-03 16:54
@samhouts We've released a couple of Prerelease channel updates of the MAUI DevKit recently so I suspect this issue has been cleared up, but we'll keep an eye out. Thanks.

**Comment by williambuchanan2** [comment] 2023-10-03 21:24
Honest question.... How is VS Code a valid option for Maui work? Our solutions are made up of multiple projects in different locations. I can't see how VS Code is going to help me. Opening the solution file just opens it as text - so it's not soluton based. I can open the folder which has the app in it - but then I can't see the code in all the other projects. I guess I must be missing something...?

**Comment by samhouts** [comment] 2023-10-03 23:03
If you install the [MAUI extension](https://devblogs.microsoft.com/visualstudio/announcing-the-dotnet-maui-extension-for-visual-studio-code/), you'll get the C# Dev Kit extension, too. This does add a solution explorer view! It's pretty nifty.

**Comment by williambuchanan2** [comment] 2023-10-03 23:35
Ok, that's not what I am experiencing. This is what happens when I try to open a .sln file.

![Screenshot 2023-10-04 at 10 31 41 am](https://github.com/dotnet/maui/assets/32165641/42608050-ea6b-4e8a-8fd2-5780c732b1d9)

**Comment by samhouts** [comment] 2023-10-03 23:45
What you want to do is open the folder that contains the solution

<img width="241" alt="image" src="https://github.com/dotnet/maui/assets/7827070/74c77961-e91c-4954-a296-f10267017520">

Give it a second to process, and a Solution Explorer tab will pop up (probably below the explorer)

<img width="203" alt="image" src="https://github.com/dotnet/maui/assets/7827070/9a79846a-5483-4662-9fda-6ba74fac7d1e">

Then you can use the Solution Explorer instead!

**Comment by williambuchanan2** [comment] 2023-10-03 23:49
That isn't what I see. I just see a list of files. 

Could this be related to the fact that we have multiple solutions in the same folder?

![Screenshot 2023-10-04 at 10 47 58 am](https://github.com/dotnet/maui/assets/32165641/0d822a85-ee27-4cd7-a198-06c0dfc47639)

**Comment by samhouts** [comment] 2023-10-05 23:23
Ooh, possibly. @AllenD-MSFT multiple solutions in the same folder should be supported, right?

**Comment by AllenD-MSFT** [comment] 2023-10-06 16:50
@samhouts @williambuchanan2 , looks like you've found a bug in the C# DevKit. VSCode with the C# extension should open a folder with multiple .sln files and prompt to pick a solution to use. (This is documented behavior.) This behavior appears to not work with the C# DevKit extension. I've inquired with the C# DevKit owners to see if they are aware of this and get their input. Will get back to you when I have more info.

**Comment by AllenD-MSFT** [comment] 2023-10-06 21:09
@williambuchanan2 , the bug is that this solution picker isn't very obvious. When opening a folder that contains multiple solution files, there's a notification in the lower right corner of the VSCode window: 
![image](https://github.com/dotnet/maui/assets/49214121/144a92be-4b2d-4b76-bc00-ad035a96094c)
If you click "Choose to open" then a list is presented in the top center of the VS Code window with the solution files to choose from. If you pick one of those, then that solution will be the active one. If you dismiss that picker, then the Solution Explorer will be activated and it will contain a big button:
![image](https://github.com/dotnet/maui/assets/49214121/b10f860b-9ae4-481a-a6cc-07fcf073f16c)
Clicking that button shows the same pick list as before. That's what you'll need to use to choose one of your solution files. 

Please let us know if this is working for you as indicated.

The bug, in my opinion is that the Solution Explorer should activate with the big button regardless of invoking the button in the notification. That would make this more obvious. For me, the notification was appearing so far away from the activity center of the UI in my multi-mon setup that I couldn't see the notification popping up. I will file a bug on that behavior soon.

**Comment by AllenD-MSFT** [comment] 2023-10-06 21:20
I filed https://github.com/microsoft/vscode-dotnettools/issues/586 for this VSCode C# DevKit behavior.

**Comment by williambuchanan2** [comment] 2023-10-07 00:02
@AllenD-MSFT I can categorically state that I don't get any notification. I choose Open Folder - all that happens is I get a listing of the sln files in that folder.

I have the latest version of VS Code (3 days old apparently), and all the plugins are up to date as well.

Just to confirm - this is VS Code on a Mac - not PC...

**Comment by williambuchanan2** [comment] 2023-10-07 00:09
Just to provide an update on this... I tried to create a new solution file inside the folder where the Maui app is located. When I open this folder I get a bunch of errors (see below).

".NET Maui SDK not found" - strange because I am using Visual Studio and it seems to be able to find it. Just to be sure I downloaded it again - same problem.
I also get a slew of errors in the output (other screenshot).
I tried to press the Debug button just on the off chance, but just got another error.




![Screenshot 2023-10-07 at 11 03 26 am](https://github.com/dotnet/maui/assets/32165641/fd0801f5-51d2-4c8c-9ab1-35f7f3cae812)

![Screenshot 2023-10-07 at 11 06 32 am](https://github.com/dotnet/maui/assets/32165641/0be31013-0e35-4070-b49a-63a051788874)

**Comment by mattleibow** [comment] 2023-10-12 16:01
@williambuchanan2 Sorry this took so long, but I just wanted to confirm whether the OG issue about the type load exceptions are still happening or not. I think this may have been related to a change in .NET 8 preview 7 SDK where they moved some attributes from being generated in each assembly to the corlib. Depending on when particular dlls were built, they may or may not have the generated attributes or reference the corlib attributes. You may have had a mismatching setup of SDK, MAUI and/or third party assemblies.

 - https://github.com/dotnet/runtime/pull/87857

**Comment by williambuchanan2** [comment] 2023-10-16 20:39
I had to reset my macbook and unfortunately the visual studio installer doesn't work now. It stops at the stage where it tries to install Maui. So I can't even get to the point to start looking at this again.

**Comment by mattleibow** [comment] 2023-10-16 20:42
You could try installing via the command line:

```
dotnet workload install maui --source https://api.nuget.org/v3/index.json
```

That might update the workload past the fact of the sdk, or is this the actual IDE installer and not the updater?

**Comment by AndreasReitberger** [comment] 2023-10-28 10:47
Just updated my app project to `net8`. Also seeing this issue on Android now.
All is up to date using the latest versions of VS 2022 Preview and Net8.

![image](https://github.com/dotnet/maui/assets/2952443/8739cac9-42d1-4ac0-99e5-367ec55c41ec)

Windows seems to start fine though. Trying now to launch it on iOS and report back.

**Comment by williambuchanan2** [comment] 2023-10-28 10:50
> Just updated my app project to `net8`. Also seeing this issue on Android now. All is up to date using the latest versions of VS 2022 Preview and Net8.
> 

Yeah I don't see us being able to use .NET 8 for a while yet. If we still can't even get the basic click counter to work there is little chance of getting a real app to work.

**Comment by AndreasReitberger** [comment] 2023-10-29 07:26
@mattleibow 
iOS and Windows seem to work fine, only while using Android I keep getting this exception.

**Comment by samhouts** [comment] 2023-10-31 16:22
@AndreasReitberger I believe you're seeing [a different issue. ](https://github.com/dotnet/maui/issues/17265)

**Comment by AndreasReitberger** [comment] 2023-10-31 16:25
@samhouts 
Ok I see. This issue is closed already, but I guess not shipped right? Do you know when this one will be available in the latest net8 nugets? So that I can test if this fixed my issue.
I'm using the `Syncfusion.SfListView` indeed on that page. Thanks for the clarification.

**Comment by samhouts** [comment] 2023-10-31 17:18
@AndreasReitberger I believe it released just minutes ago. 🤞

**Comment by AndreasReitberger** [comment] 2023-11-01 04:53
@samhouts 
Can confirm, the last released fixed the issue for me. Thanks!

**Closed** 2023-11-01 20:48 UTC
Labels: t/bug, area/tooling ⚙️, platform/iOS 🍎, s/needs-attention, potential-regression
