### ISSUE TITLE
[MAUI8] [iOS] Star Height of Grid.Row with CollectionView isn't correct

### ISSUE THREAD

**Issue by sasharp** [dotnet/maui#18348] opened 2023-10-25 14:00 UTC
### Description

After adding more Grid.Rows and one of them CollectionView with Height="*", the height will calculated incorrectly.

On the screenshot is shown, that the scroll bar is bottom, but there is still invisible items in CollectionView.

![image](https://github.com/dotnet/maui/assets/7774486/e15b8919-914e-4922-948b-807abdfb414b)

### Steps to Reproduce

1. Add 3 rows to a grid
2. One of them with Height="*" must contain CollectionView
3. Add more vertical items, till you have to scroll

### Link to public reproduction project repository

https://github.com/sasharp/MAUI8Bugs

### Version with bug

8.0.0-rc.2.9373

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.96

### Affected platforms

iOS

### Did you find any workaround?

Exactly define rows height

**Comment by arahmancsd** [comment] 2023-10-25 15:32
Seems similar to #17581

**Comment by mattleibow** [comment] 2023-10-25 18:12
Duplicate of https://github.com/dotnet/maui/issues/17581

**Closed by mattleibow** 2023-10-25 18:12 UTC
Labels: t/bug, area/layout 🔲
