### ISSUE TITLE
7.0.81 Service Release 4 Serious Layout Problem

### ISSUE THREAD

**Issue by gnibloop** [dotnet/maui#14849] opened 2023-04-30 00:19 UTC
### Description

After update to this new server release, many old code's layout messed up. I found out all problems were related to a Grid with Column definition of "*,Auto",  the first column 's height wont be calculated correctly and cause the whole grid row's height shrink to the "Auto" column's content's height.

NOTE: last service release has no problem.

![screenbug](https://user-images.githubusercontent.com/32973591/235329250-51973923-33b5-46fe-aaf9-d4dec6ac058e.png)

### Steps to Reproduce

1, Create Maui Demo Project
2, Use Grid create 3 rows, the second row use Auto definition,
3, on the 2nd row, create a grid with columndefinition of "*,Auto", 
4, for each column, create some controls, but for the first column, create a vertical layout (or grid) with higher height than the 2nd column's content, 
5, Now the 2nd row height will auto shrink to fit the 2nd column's content (ignore the first column)

### Link to public reproduction project repository

https://github.com/gnibloop/MauiAppReportError.App

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

IOS 15 Simulator and Physical Device

### Did you find any workaround?

Yes, has to create a "Auto, Auto" column definition, but this will make the alignment very difficult. The point is to let first column used up remaining space, the 2nd column will tightly aligned to end.

**Comment by JohnHDev** [comment] 2023-04-30 08:31
I believe there are several other threads on this issue as well. Imo it is severe enough for a hot fix, but I don't think they can do that with workloads. Another reason why moving from nugets to workloads was a poorly considered idea.

**Comment by RobTF** [comment] 2023-05-03 15:14
I think the workload thing works well if it is the reason we don't get swamped with loads of `AndroidX` packages which were an absolute nightmare with Xamarin, I had loads of them fighting out with differing versions etc. That seems to have gone, or at least been abstracted away from me as a developer, and I'm thankful for that.

But it does feel like this approach relies on each release being more stable than it clearly is, if you think back to when Microsoft were producing VB5, VB6 etc. those runtimes were fairly static with periodic service releases but they tended to be solid workhorses people could rely on, but they had to be as there was no internet to just throw updates around. People now laugh at those days, and there were a lot of negatives too - but at least we could rely on the basics.

The concept of update fast and often has come about as a side effect of online updating and seems on the surface to offer some benefits, but tends to strongly favour features over stability. MAUI isn't the only victim of this mindset - a lot of the web UI stuff (usually npm based) is even worse than the situation with MAUI, with APIs breaking all over the place and not always adhering to semver semantics because some new maintainer thought their way was just "better".

It hasn't gone unnoticed in our place that on the current MAUI sprint is stuff for .NET 8, yet basic fixes in the currently supported 6 and 7 releases remain on the backlog.

**Comment by hartez** [comment] 2023-05-03 22:32
Duplicate of #14537.

**Closed by hartez** 2023-05-03 22:32 UTC
Labels: t/bug, area/layout 🔲
