### ISSUE TITLE
iOS and Android AppIcon generate icons with different sizes.

### ISSUE THREAD

**Issue by KSemenenko** [dotnet/maui#10572] opened 2022-10-09 10:05 UTC
### Description

I can't use the same app icon for ios and android.

<img width="405" alt="ETI0x6jQ png-medium" src="https://user-images.githubusercontent.com/4385716/194750521-4c87a6a4-deda-42a3-93c3-b04960b20a00.png">
<img width="418" alt="upB4l0eD png-medium" src="https://user-images.githubusercontent.com/4385716/194750525-a22ff89f-538c-4408-b90f-b5ff099ba17b.png">

so to achieve the same size I should use two different images.
Seems android is reqired bigger margins.

### Steps to Reproduce

you can try with my icons

android:
![android](https://user-images.githubusercontent.com/4385716/194750468-4e410bac-d30a-4d4b-a41b-006806ee081a.svg)
iOS:
![ios](https://user-images.githubusercontent.com/4385716/194750469-1d0e1bce-c234-4d62-a104-7771d389562f.svg)

If you will use iOS icon for android it will looks bad.

### Link to public reproduction project repository

N/A

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

maui

**Comment by KSemenenko** [comment] 2022-10-09 10:05
@mattleibow I created this issue, as we discussed.

**Comment by KSemenenko** [comment] 2022-10-09 16:34
Maybe we can use some grid system

https://minoraxis.medium.com/icon-grids-keylines-demystified-5a228fe08cfd

it will works for icons with transparent background.
But if we would like to have fully designed icon in png will it works?

**Comment by KSemenenko** [comment] 2022-10-16 10:35
I have idea, lets create svg file with grid for andorid and iOs and then we can see how it will genereate.
I will try to create right svg

**Comment by KSemenenko** [comment] 2022-10-19 09:21
![ios+andoird](https://user-images.githubusercontent.com/4385716/196651507-9f1155e7-3b99-48f9-a71c-b67ee1df4c11.svg)
this is SVG with mix of Grids

**Comment by mattleibow** [comment] 2022-11-11 22:02
I know you did it first, but as I was investigating I created this one: https://github.com/dotnet/maui/issues/11295

I am going to close this as a duplicate mainly because I think my issue has a bit more info.

But at the end of the day, you were right: Android clips off the first 1/6 of the border all round (18dp of 108dp) because it uses that for effects. Basically, your icon needs to really be in the middle 2/3 since you lose a total of 1/3 image size.

**Comment by mattleibow** [comment] 2022-11-11 22:03
Duplicate of https://github.com/dotnet/maui/issues/11295

**Closed by mattleibow** 2022-11-11 22:03 UTC
Labels: area/single project ☝️
