### ISSUE TITLE
Can't Access Raw Asset Path

### ISSUE THREAD

**Issue by BinaryAssault** [dotnet/maui#7943] opened 2022-06-11 02:48 UTC
Say I have an asset called `livefree.ogg` that is located in `Raw/Songs`
```
Application
  |-Resources
    |-Raw
      |-Songs
        |-livefree.ogg -> Build Action: Maui Asset
```

If I need to say, loop over all the files in Raw/Songs, how do I do so? Using `FileSystem.OpenAppPackageFileAsync` doesn't get me access to the path of the item, just a stream. Which in my case, I need a path and not a stream. Is this possible with MAUI?

None of the following return any files:
``````
Directory.GetFiles("Songs"); 
Directory.GetFiles("/Songs"); 
Directory.GetFiles("Resources/Songs");
Directory.GetFiles("/Resources/Songs");
Directory.GetFiles("Raw/Songs");
Directory.GetFiles("/Raw/Songs"); 
Directory.GetFiles("Resources/Raw/Songs"); 
Directory.GetFiles("/Resources/Raw/Songs"); 
Directory.GetFiles(Path.Combine(FileSystem.AppDataDirectory, "Songs")); 
Directory.GetFiles(Path.Combine(FileSystem.AppDataDirectory, "Raw", "Songs"));
Directory.GetFiles(Path.Combine(FileSystem.AppDataDirectory, "Resource", "Raw", "Songs"));
``````

**Comment by janseris** [comment] 2022-06-11 09:09
Need this as well. Any way to print all assets to let user choose one without knowing how many there are or their names in advance?

**Comment by xtuzy** [comment] 2022-06-12 10:33
these asset store in "app package", you can get path by read them and save them to your [app folder ](https://docs.microsoft.com/en-us/dotnet/maui/platform-integration/storage/file-system-helpers?tabs=windows)

**Comment by xtuzy** [comment] 2022-06-12 10:38
get all files maybe you can try https://stackoverflow.com/questions/47179234/in-xamarin-forms-how-to-read-a-list-of-assets-from-a-projects-folder

**Comment by BinaryAssault** [comment] 2022-06-12 21:36
@xtuzy, so you're saying the only possible way would be to copy all resources to the apps local data folder, then accessing them that way? I personally don't like this as it would double the size of the resources.

**Comment by janseris** [comment] 2022-06-12 21:52
> @xtuzy, so you're saying the only possible way would be to copy all resources to the apps local data folder, then accessing them that way? I personally don't like this as it would double the size of the resources.

It seems like the chosen response on the stackoverflow link shows a function for Android which returns the paths of all resources. Isn't that what you needed?

**Comment by BinaryAssault** [comment] 2022-06-12 22:13
> > @xtuzy, so you're saying the only possible way would be to copy all resources to the apps local data folder, then accessing them that way? I personally don't like this as it would double the size of the resources.
> 
> It seems like the chosen answer on the stackoverflow link shows a function for Android `assembly.GetManifestResourceNames` which returns the paths of all resources. Isn't that what you needed?

That particular function is related to C# reflection and not specific to Android. It can work if you set the build action to 'Embedded Resource' instead of a 'MauiAsset'. 

Although a workaround, it would be nice to have direct access to MauiAssets. I'm going to guess there is some lower level OS limitations with direct access and maybe that is why it isn't available.

**Comment by berhir** [comment] 2022-09-14 06:41
I need access to the assets directory too. I looked at the MAUI code and currently the `IFileSystem` has only these properties/methods:
```csharp
public interface IFileSystem
{
	string CacheDirectory { get; }
	string AppDataDirectory { get; }
	Task<Stream> OpenAppPackageFileAsync(string filename);
	Task<bool> AppPackageFileExistsAsync(string filename);
}
```

It would be great to add a `string AppPackageDirectory` or `string AssetsDirectory` property. The `OpenAppPackageFileAsync` and `AppPackageFileExistsAsync` methods calculate this path anyway, so why hide this information?

**Comment by mattleibow** [comment] 2023-02-04 01:38
One thing that we can do is provide a way it enumerate the items.

Duplicate of #10816

**Comment by mattleibow** [comment] 2023-02-04 01:38
Duplicate of #10816

**Closed by mattleibow** 2023-02-04 01:38 UTC
Labels: t/enhancement ☀️, area/single project ☝️
