### ISSUE TITLE
[M1] 7.0 Maui Blazor app displays blank on iOS 16.2 simulator.

### ISSUE THREAD

**Issue by LuckyKang79** [dotnet/maui#13077] opened 2023-02-02 10:48 UTC
### Description

1. Run 7.0 Maui Blazor app displays blank on iOS 16.2 simulator.
1. The download NuGet.Config file need to add the below internal feed.
https://pkgs.dev.azure.com/dnceng/internal/_packaging/6.0.406-servicing.23074.33-shipping/nuget/v3/index.json
https://pkgs.dev.azure.com/dnceng/internal/_packaging/7.0.200-rtm.23080.6-shipping/nuget/v3/index.json 

### Steps to Reproduce

1. Install the .NET 7.0 SDK.
1. Download the rollback.json file from [here](https://maui.blob.core.windows.net/dogfooding/7.0.1xx-sr3/rollback.json).
1. Download the NuGet.Config file from [here](https://maui.blob.core.windows.net/dogfooding/7.0.1xx-sr3/NuGet.Config).
1. Place the NuGet.Config and rollback.json files in the same directory (make sure there's no global.json file in the directory or directory tree above).
1. Open a terminal and cd into the directory with the NuGet.Config and rollback.json files.
1. Run the workload install command:
`sudo dotnet workload install maui ios maccatalyst android macos tvos --from-rollback-file ./rollback.json`
1. Run the project & ensure you see the application.
`dotnet build -t:Run -f net7.0-ios`
1. The error is as shown below：
    ![image](https://user-images.githubusercontent.com/93763301/216303022-2a1d4d69-9767-426e-bdd0-de6d797120ed.png)

### Link to public reproduction project repository

No

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

MacOS SDK 7.0.300-preview.23101.11

### Did you find any workaround?

No

### Relevant log output

```shell
admin@11098542-04 maui-blazor-cti % dotnet build -t:Run -f net7.0-iosMSBuild version 17.6.0-preview-23101-01+7cfb36cb9 for .NET  Determining projects to restore...  All projects are up-to-date for restore./usr/local/share/dotnet/sdk/7.0.300-preview.23101.13/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.RuntimeIdentifierInference.targets(287,5): message NETSDK1057: You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy [/Users/admin/.nuget/NuGet/maui_from_mac/maui-blazor-cti/maui-blazor-cti.csproj::TargetFramework=net7.0-ios]  Detected signing identity:              Bundle Id: com.companyname.maui_blazor_cti    App Id: com.companyname.maui_blazor_cti  maui-blazor-cti -> /Users/admin/.nuget/NuGet/maui_from_mac/maui-blazor-cti/bin/Debug/net7.0-ios/iossimulator-x64/maui-blazor-cti.dll  Optimizing assemblies for size may change the behavior of the app. Be sure to test after publishing. See: https://aka.ms/dotnet-illink  xcrun simctl launch --stdout=/dev/ttys002 --stderr=/dev/ttys003 --terminate-running-process F0A4F495-4FA3-40A7-9CAF-4F1D1F8839B7 com.companyname.maui_blazor_cti  com.companyname.maui_blazor_cti: 39523objc[39523]: Class CDPCAReporter is implemented in both /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/CoreCDPInternal.framework/CoreCDPInternal (0x160c631d8) and /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/CoreCDP.framework/CoreCDP (0x15bef4eb0). One of the two will be used. Which one is undefined.objc[39523]: Class CDPCABackupRecoveryReporter is implemented in both /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/CoreCDPInternal.framework/CoreCDPInternal (0x160c63ef8) and /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/CoreCDP.framework/CoreCDP (0x15bef50e0). One of the two will be used. Which one is undefined.2023-02-02 02:39:56.732038-0800 maui-blazor-cti[39523:787342] Microsoft.iOS: Socket error while connecting to IDE on 127.0.0.1:10000: Connection refused2023-02-02 02:39:59.246706-0800 maui-blazor-cti[39523:787165] SecTaskLoadEntitlements failed error=22 cs_flags=200, pid=395232023-02-02 02:39:59.249188-0800 maui-blazor-cti[39523:787165] SecTaskCopyDebugDescription: maui-blazor-cti[39523]/0#-1 LF=02023-02-02 02:39:59.316967-0800 maui-blazor-cti[39523:787165] SecTaskLoadEntitlements failed error=22 cs_flags=200, pid=395232023-02-02 02:39:59.318155-0800 maui-blazor-cti[39523:787165] SecTaskCopyDebugDescription: maui-blazor-cti[39523]/0#-1 LF=02023-02-02 02:39:59.370799-0800 maui-blazor-cti[39523:787165] [SceneConfiguration] Info.plist contained no UIScene configuration dictionary (looking for configuration named "(no name)")2023-02-02 02:39:59.371483-0800 maui-blazor-cti[39523:787165] [SceneConfiguration] Info.plist contained no UIScene configuration dictionary (looking for configuration named "(no name)")2023-02-02 02:39:59.631399-0800 maui-blazor-cti[39523:787527] SecTaskLoadEntitlements failed error=22 cs_flags=200, pid=395232023-02-02 02:39:59.632173-0800 maui-blazor-cti[39523:787527] SecTaskCopyDebugDescription: maui-blazor-cti[39523]/0#-1 LF=02023-02-02 02:39:59.731863-0800 maui-blazor-cti[39523:787165] [unspecified] container_query_get_single_result: error = 2→(98) NOT_CODESIGNED2023-02-02 02:39:59.732149-0800 maui-blazor-cti[39523:787165] [unspecified] container_system_group_path_for_identifier: error = ((container_error_t)98) NOT_CODESIGNED2023-02-02 02:39:59.732232-0800 maui-blazor-cti[39523:787165] [MC] Error getting system group container for systemgroup.com.apple.configurationprofiles: 982023-02-02 02:39:59.733147-0800 maui-blazor-cti[39523:787165] [MC] Failed to get profile system group container path. Overriding with expected path: /Users/admin/Library/Developer/CoreSimulator/Devices/F0A4F495-4FA3-40A7-9CAF-4F1D1F8839B7/data/Containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles2023-02-02 02:39:59.761163-0800 maui-blazor-cti[39523:787527] SecTaskLoadEntitlements failed error=22 cs_flags=200, pid=395232023-02-02 02:39:59.762484-0800 maui-blazor-cti[39523:787527] SecTaskCopyDebugDescription: maui-blazor-cti[39523]/0#-1 LF=02023-02-02 02:39:59.765718-0800 maui-blazor-cti[39523:787165] SecTaskLoadEntitlements failed error=22 cs_flags=200, pid=395232023-02-02 02:39:59.766517-0800 maui-blazor-cti[39523:787165] SecTaskCopyDebugDescription: maui-blazor-cti[39523]/0#-1 LF=02023-02-02 02:39:59.766687-0800 maui-blazor-cti[39523:787165] SecTaskLoadEntitlements failed error=22 cs_flags=200, pid=395232023-02-02 02:39:59.767151-0800 maui-blazor-cti[39523:787165] SecTaskCopyDebugDescription: maui-blazor-cti[39523]/0#-1 LF=02023-02-02 02:40:00.045974-0800 maui-blazor-cti[39523:787165] SecTaskLoadEntitlements failed error=22 cs_flags=200, pid=395232023-02-02 02:40:00.047138-0800 maui-blazor-cti[39523:787165] SecTaskCopyDebugDescription: maui-blazor-cti[39523]/0#-1 LF=02023-02-02 02:40:00.745740-0800 maui-blazor-cti[39523:787165] [Process] 0x17306c100 - [PID=39549] WebProcessProxy::didClose: (web process 0 crash)2023-02-02 02:40:00.746005-0800 maui-blazor-cti[39523:787165] [Process] 0x17306c100 - [PID=39549] WebProcessProxy::processDidTerminateOrFailedToLaunch: reason=Crash2023-02-02 02:40:00.746283-0800 maui-blazor-cti[39523:787165] [ProcessSuspension] 0x173020540 - ProcessAssertion: Failed to acquire RBS Background assertion 'ConnectionTerminationWatchdog' for process because PID 0 is invalid2023-02-02 02:40:00.746396-0800 maui-blazor-cti[39523:787528] [ProcessSuspension] 0x173020540 - ProcessAssertion::acquireSync Failed to acquire RBS assertion 'ConnectionTerminationWatchdog' for process with PID=0, error: (null)2023-02-02 02:40:00.747175-0800 maui-blazor-cti[39523:787165] [Process] 0x7f9ab2c8c420 - [pageProxyID=7, webPageID=8, PID=39549] WebPageProxy::processDidTerminate: (pid 39549), reason=Crash2023-02-02 02:40:00.755084-0800 maui-blazor-cti[39523:787165] [Loading] 0x7f9ab2c8c420 - [pageProxyID=7, webPageID=8, PID=39549] WebPageProxy::dispatchProcessDidTerminate: reason=Crash2023-02-02 02:40:00.762160-0800 maui-blazor-cti[39523:787165] [ProcessSuspension] ProcessAssertion::remainingRunTimeInSeconds failed to get handle for process with PID=395492023-02-02 02:40:00.763151-0800 maui-blazor-cti[39523:787530] [assertion] Error acquiring assertion: <Error Domain=RBSAssertionErrorDomain Code=2 "Specified target process does not exist" UserInfo={NSLocalizedFailureReason=Specified target process does not exist}>2023-02-02 02:40:00.763220-0800 maui-blazor-cti[39523:787530] [ProcessSuspension] 0x1730203c0 - ProcessAssertion::acquireSync Failed to acquire RBS assertion 'WebProcess Background Assertion' for process with PID=39549, error: Error Domain=RBSAssertionErrorDomain Code=2 "Specified target process does not exist" UserInfo={NSLocalizedFailureReason=Specified target process does not exist}2023-02-02 02:40:00.765686-0800 maui-blazor-cti[39523:787530] [assertion] Error acquiring assertion: <Error Domain=RBSAssertionErrorDomain Code=2 "Specified target process does not exist" UserInfo={NSLocalizedFailureReason=Specified target process does not exist}>2023-02-02 02:40:00.765776-0800 maui-blazor-cti[39523:787530] [ProcessSuspension] 0x1730205a0 - ProcessAssertion::acquireSync Failed to acquire RBS assertion 'WebProcess Suspended Assertion' for process with PID=39549, error: Error Domain=RBSAssertionErrorDomain Code=2 "Specified target process does not exist" UserInfo={NSLocalizedFailureReason=Specified target process does not exist}2023-02-02 02:40:29.931039-0800 maui-blazor-cti[39523:787165] [ProcessSuspension] 0x7f9ab1bf76b0 - TimedActivity::activityTimedOut:2023-02-02 02:40:30.748040-0800 maui-blazor-cti[39523:787165] Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified serviceBuild succeeded.    0 Warning(s)    0 Error(s)
```
```

**Comment by MuhammadUmarqulov** [comment] 2023-02-02 11:14
me too

**Comment by mkArtakMSFT** [comment] 2023-02-06 17:30
Thanks for contacting us. Can you try this scenario with a MAUI app (non-Blazor) and share whether you see similar issue or not?

**Comment by Eilon** [comment] 2023-02-06 20:20
Apparently there are no further Ventura-related issues, so as long as everything is up-to-date, it should be fine. Check updates for Xcode, Visual Studio, and .NET.

**Comment by MuhammadUmarqulov** [comment] 2023-02-06 20:31
> Thanks for contacting us. Can you try this scenario with a MAUI app (non-Blazor) and share whether you see similar issue or not?

I already try this. If I use MAUI without Hybrid it's work clean. Have a problem with Blazor hybrid.

**Comment by MukhammadUmarqulov** [comment] 2023-02-07 12:46
@Eilon in which social network we can talk to you to explain the issues

**Comment by MuhammadUmarqulov** [comment] 2023-02-07 12:48
@Eilon in which social network we can talk to you to explain the issues

**Comment by jasonsturges** [comment] 2023-02-26 06:58
Likewise, same socket error for iOS simulator while other targets of Android and Mac Catalyst work.

Create a new MAUI Blazor App, and launching the template fails with white screen and mirrors the socket error of the original post here in this issue.

.NET Version: 7.0.101
macOS Monterey 12.6.3 (21G419)

```
objc[5009]: Class CDPCAReporter is implemented in both /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/CoreCDPInternal.framework/CoreCDPInternal (0x160edf1d8) and /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/CoreCDP.framework/CoreCDP (0x15c170eb0). One of the two will be used. Which one is undefined.
objc[5009]: Class CDPCABackupRecoveryReporter is implemented in both /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/CoreCDPInternal.framework/CoreCDPInternal (0x160edfef8) and /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/CoreCDP.framework/CoreCDP (0x15c1710e0). One of the two will be used. Which one is undefined.
2023-02-26 00:55:34.285352-0600 MauiApp1[5009:37390] Microsoft.iOS: Socket error while connecting to IDE on 127.0.0.1:10000: Connection refused
2023-02-26 00:55:35.871038-0600 MauiApp1[5009:37282] SecTaskLoadEntitlements failed error=22 cs_flags=200, pid=5009
2023-02-26 00:55:35.873490-0600 MauiApp1[5009:37282] SecTaskCopyDebugDescription: MauiApp1[5009]/0#-1 LF=0
2023-02-26 00:55:35.941774-0600 MauiApp1[5009:37282] SecTaskLoadEntitlements failed error=22 cs_flags=200, pid=5009
2023-02-26 00:55:35.942825-0600 MauiApp1[5009:37282] SecTaskCopyDebugDescription: MauiApp1[5009]/0#-1 LF=0
2023-02-26 00:55:35.990692-0600 MauiApp1[5009:37282] [SceneConfiguration] Info.plist contained no UIScene configuration dictionary (looking for configuration named "(no name)")
2023-02-26 00:55:35.991324-0600 MauiApp1[5009:37282] [SceneConfiguration] Info.plist contained no UIScene configuration dictionary (looking for configuration named "(no name)")
2023-02-26 00:55:36.220521-0600 MauiApp1[5009:37389] SecTaskLoadEntitlements failed error=22 cs_flags=200, pid=5009
2023-02-26 00:55:36.221216-0600 MauiApp1[5009:37389] SecTaskCopyDebugDescription: MauiApp1[5009]/0#-1 LF=0
2023-02-26 00:55:36.299340-0600 MauiApp1[5009:37282] [unspecified] container_query_get_single_result: error = 2→(98) NOT_CODESIGNED
2023-02-26 00:55:36.299607-0600 MauiApp1[5009:37282] [unspecified] container_system_group_path_for_identifier: error = ((container_error_t)98) NOT_CODESIGNED
2023-02-26 00:55:36.299683-0600 MauiApp1[5009:37282] [MC] Error getting system group container for systemgroup.com.apple.configurationprofiles: 98
2023-02-26 00:55:36.300382-0600 MauiApp1[5009:37282] [MC] Failed to get profile system group container path. Overriding with expected path: /Users/jasonsturges/Library/Developer/CoreSimulator/Devices/9B68E8C6-299A-4110-B892-1B9F1294C068/data/Containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles
2023-02-26 00:55:36.325292-0600 MauiApp1[5009:37453] SecTaskLoadEntitlements failed error=22 cs_flags=200, pid=5009
2023-02-26 00:55:36.326071-0600 MauiApp1[5009:37453] SecTaskCopyDebugDescription: MauiApp1[5009]/0#-1 LF=0
2023-02-26 00:55:36.329970-0600 MauiApp1[5009:37282] SecTaskLoadEntitlements failed error=22 cs_flags=200, pid=5009
2023-02-26 00:55:36.330421-0600 MauiApp1[5009:37282] SecTaskCopyDebugDescription: MauiApp1[5009]/0#-1 LF=0
2023-02-26 00:55:36.330563-0600 MauiApp1[5009:37282] SecTaskLoadEntitlements failed error=22 cs_flags=200, pid=5009
2023-02-26 00:55:36.330975-0600 MauiApp1[5009:37282] SecTaskCopyDebugDescription: MauiApp1[5009]/0#-1 LF=0
2023-02-26 00:55:36.569434-0600 MauiApp1[5009:37282] SecTaskLoadEntitlements failed error=22 cs_flags=200, pid=5009
2023-02-26 00:55:36.570354-0600 MauiApp1[5009:37282] SecTaskCopyDebugDescription: MauiApp1[5009]/0#-1 LF=0
2023-02-26 00:55:37.020705-0600 MauiApp1[5009:37282] [Process] 0x17306c100 - [PID=5026] WebProcessProxy::didClose: (web process 0 crash)
2023-02-26 00:55:37.021000-0600 MauiApp1[5009:37282] [Process] 0x17306c100 - [PID=5026] WebProcessProxy::processDidTerminateOrFailedToLaunch: reason=Crash
2023-02-26 00:55:37.021281-0600 MauiApp1[5009:37282] [ProcessSuspension] 0x173020300 - ProcessAssertion: Failed to acquire RBS Background assertion 'ConnectionTerminationWatchdog' for process because PID 0 is invalid
2023-02-26 00:55:37.021585-0600 MauiApp1[5009:37453] [ProcessSuspension] 0x173020300 - ProcessAssertion::acquireSync Failed to acquire RBS assertion 'ConnectionTerminationWatchdog' for process with PID=0, error: (null)
2023-02-26 00:55:37.022420-0600 MauiApp1[5009:37282] [Process] 0x7f9e97e10220 - [pageProxyID=7, webPageID=8, PID=5026] WebPageProxy::processDidTerminate: (pid 5026), reason=Crash
2023-02-26 00:55:37.029158-0600 MauiApp1[5009:37282] [Loading] 0x7f9e97e10220 - [pageProxyID=7, webPageID=8, PID=5026] WebPageProxy::dispatchProcessDidTerminate: reason=Crash
2023-02-26 00:55:37.035221-0600 MauiApp1[5009:37282] [ProcessSuspension] ProcessAssertion::remainingRunTimeInSeconds failed to get handle for process with PID=5026
2023-02-26 00:55:37.036302-0600 MauiApp1[5009:37453] [assertion] Error acquiring assertion: <Error Domain=RBSAssertionErrorDomain Code=2 "Specified target process does not exist" UserInfo={NSLocalizedFailureReason=Specified target process does not exist}>
2023-02-26 00:55:37.036395-0600 MauiApp1[5009:37453] [ProcessSuspension] 0x173020420 - ProcessAssertion::acquireSync Failed to acquire RBS assertion 'WebProcess Background Assertion' for process with PID=5026, error: Error Domain=RBSAssertionErrorDomain Code=2 "Specified target process does not exist" UserInfo={NSLocalizedFailureReason=Specified target process does not exist}
2023-02-26 00:55:37.038813-0600 MauiApp1[5009:37453] [assertion] Error acquiring assertion: <Error Domain=RBSAssertionErrorDomain Code=2 "Specified target process does not exist" UserInfo={NSLocalizedFailureReason=Specified target process does not exist}>
2023-02-26 00:55:37.038928-0600 MauiApp1[5009:37453] [ProcessSuspension] 0x173020540 - ProcessAssertion::acquireSync Failed to acquire RBS assertion 'WebProcess Suspended Assertion' for process with PID=5026, error: Error Domain=RBSAssertionErrorDomain Code=2 "Specified target process does not exist" UserInfo={NSLocalizedFailureReason=Specified target process does not exist}
2023-02-26 00:56:06.466250-0600 MauiApp1[5009:37282] [ProcessSuspension] 0x7f9e97e5cab0 - TimedActivity::activityTimedOut:
2023-02-26 00:56:07.024220-0600 MauiApp1[5009:37282] Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service
```

**Comment by Arslan007** [comment] 2023-03-01 06:58
Facing same issue with 16.2 Simulator on M1. UI shows blank and I am stuck in limbo with new VS for mac update it requires newer Xcode 14.2 because Microsoft.iOS is upgraded and not compatible with Xcode 14.0 or 14.1 and there is no way to downgrade Visual Studio for Mac. And new VS donot deploy on physical device too.

**Comment by jasonsturges** [comment] 2023-03-01 19:59
@Arslan007 Interesting - I'm on Xcode 4.2 and experiencing the issue.

**Comment by Arslan007** [comment] 2023-03-01 20:05
@jasonsturges If i am not mistaken you meant Xcode 14.2. Yes its mainly Xcode 14.2 and new VS for mac 17.5 issue which is not supporting MAUI for Blazor Hybrid apps

**Comment by lanedirt** [comment] 2023-03-01 22:40
I am having the same issue. MAUI Blazor app gives a white screen in iOS simulator.

Xcode 14.2
iOS 16.2
Visual Studio for mac 17.5.
Macbook Pro M2

When I debug the same app on my iPhone it works normally. It also works with Android simulator. So it seems to be something with the iOS simulator in specific.

**Comment by Arslan007** [comment] 2023-03-01 22:58
For me its failing with device too
<img width="378" alt="Screenshot 2023-03-01 at 3 57 17 PM" src="https://user-images.githubusercontent.com/1511567/222285772-1ecc412a-9bf6-4a02-9031-c7aa665813dc.png">

**Comment by e012345678** [comment] 2023-03-10 23:53
Did anyone found a solution to this? I am having blank app on both real iPhone and simulator.

**Comment by Arslan007** [comment] 2023-03-10 23:56
No solutions so far. And still waiting for any response from MSFT

**Comment by Thepriestdude** [comment] 2023-03-15 06:55
Having the same issue. (create a new MAUI blazor app) run the application in the iOS simulator, the application is just a blank screen. I have tried downgrading to Xcode 14.1 which did not work either. 

@mkArtakMSFT Is it possible to assign a new developer to this since it is blocking the creation of new .net MAUI blazor applications for iOS?

**Comment by docelmo** [comment] 2023-03-16 19:02
ya stressing here.  I have a MAUI go-live on the 1st and supposed to be going into UAT monday.  sweating bullets here....

**Comment by Thepriestdude** [comment] 2023-03-16 21:40
Specifying the `RunTimeIdentifier` as `iossimulator` when debugging (provided release is done on the phone) you can add the following code to your .csproj file:

```
<PropertyGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios' and $(Configuration) == 'Release'">
    <RuntimeIdentifier>ios-arm64</RuntimeIdentifier>
    <CodesignEntitlement>Entitlements.plist</CodesignEntitlement>
    <ArchiveOnBuild>true</ArchiveOnBuild>
</PropertyGroup>

<PropertyGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios' and $(Configuration) == 'Debug'">
    <RuntimeIdentifier>ios-arm64</RuntimeIdentifier>
    <RuntimeIdentifier>iossimulator-arm64</RuntimeIdentifier>
</PropertyGroup>
```

There seems to be some weird interaction happening when using M1 or M2 macs and running the simulator.

**Comment by phvhao** [comment] 2023-03-18 02:42
thank you,
I added the following 2 lines to the project file and it worked

       <RuntimeIdentifier>ios-arm64</RuntimeIdentifier>
       <RuntimeIdentifier>iossimulator-arm64</RuntimeIdentifier> </PropertyGroup>

   ```
 <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net7.0-ios|AnyCPU'">
      <CreatePackage>false</CreatePackage>
      <RuntimeIdentifier>ios-arm64</RuntimeIdentifier>
      <RuntimeIdentifier>iossimulator-arm64</RuntimeIdentifier>    </PropertyGroup>
    <ItemGroup>
```

**Comment by Arslan007** [comment] 2023-03-20 08:01
For me its still not working for simulator even specifying the runtime for simulator

```
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/16.2.1040/targets/Xamarin.Shared.Sdk.targets(3,3): Error: clang++ exited with code 1:
ld: in /App/obj/Debug/net7.0-ios/iossimulator-arm64/linker-cache/AppCenterAnalytics.a(MSACAnalytics.o), building for iOS Simulator, but linking in object file built for iOS, file '/App/obj/Debug/net7.0-ios/iossimulator-arm64/linker-cache/AppCenterAnalytics.a'
clang: error: linker command failed with exit code 1 (use -v to see invocation) (App)
```

It might be because my app uses AppCenter MAUI package and that lib doesn't have .a file slice for simulator

**Comment by Thepriestdude** [comment] 2023-03-22 16:52
Creating a new MAUI application (without Blazor) from the standard MAUI template seems to work as intended without the aforementioned fix.
<img src="https://user-images.githubusercontent.com/6491283/226977865-dea92281-6073-4322-9c7c-430ebdfc0708.png" height="500">

**Comment by jasonsturges** [comment] 2023-03-23 03:47
@mkArtakMSFT Issue seems isolated to Blazor - as @Thepriestdude indicated, MAUI App (without Blazor) functions perfectly.

**Comment by Eilon** [comment] 2023-03-27 18:24
Some folks looked into this and apparently it's an issue due to arm64/x64 differences in various binaries used in such projects. You can read more here, including a workaround that you can use right now: https://github.com/xamarin/xamarin-macios/issues/17841

**Comment by xthepoet** [comment] 2023-04-29 19:29
> Hi all! I was facing the same issue, but when I tried with Xcode 14.3 it started to work again! I guess 14.3 is not supported yet, but hey. The application starts at least 😅 Sorry, was forgetting: I'm using VS Preview Version 17.6.0 Preview 2.0

This solution worked!! Had been struggling with ios simulator for months and I think the latest update just fixed it. 

Had all the same issues mentioned above (including AppCenter MAUI / Blazor issues) causing app in simulator to crash. 
Just deleting <RuntimeIdentifier>ios-arm64</RuntimeIdentifier> or 
adding <RuntimeIdentifier>iossimulator-arm64</RuntimeIdentifier> to .csproj
got app to load in iOS simulator, but the app was still crashing after some login/appcenter interactions.

After the upgrade to XCode 14.3 and the latest MAUI and .Net 7.0 (whatever the defaults in "Check for Updates" were), all the app crashing issues in the simulator have been resolved! I am running VS 17.5.4, and didn't have to upgrade that.

**Comment by v-Lily** [comment] 2023-05-25 06:10
I tried with Xcode 14.3 it started to work again, maybe this issue has been fixed.
I'll keep tracking this issue and close it if it doesn't reproduce.

**Comment by dalexsoto** [comment] 2023-05-31 19:49
I can't repro this issue anymore with Xcode 14.3 update, it seems Apple fixed this on their side.

**Closed** 2023-05-31 19:50 UTC
Labels: t/bug, area/blazor 🕸️, platform/iOS 🍎
