### ISSUE TITLE
[Android] Performance issues with CollectionView using grouping and variable sizes

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#22192] opened 2024-05-03 10:15 UTC
### Description

Performance issues with CollectionView using grouping and variable sizes.
![perf-groups-variable-size](https://github.com/dotnet/maui/assets/6755973/281dde36-8f66-46f6-8b99-a8a8c8db6900)

### Steps to Reproduce

1. Sync or download https://github.com/dotnet/maui-samples/tree/main/8.0/UserInterface/Views/CollectionViewDemos
2. Launch the App on Android.
3. Navigate to Grouping with variable sized items.

### Link to public reproduction project repository

 https://github.com/dotnet/maui-samples/tree/main/8.0/UserInterface/Views/CollectionViewDemos

### Version with bug

8.0.21 SR4.1

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 14

**Comment by jsuarezruiz** [comment] 2024-05-03 16:56
The issue is because use the following hierarchy:

StackLayout > CollectionView

Changing it by:

Grid > CollectionView

Fixes the performance. However, after the changes and scrolling:
![image](https://github.com/dotnet/maui/assets/6755973/a381d520-ec21-40fb-b55d-493468b4ea43)
![image](https://github.com/dotnet/maui/assets/6755973/df5944d7-f695-48e6-93cf-6d81d5cb82cb)

**Comment by PureWeen** [comment] 2024-05-03 21:06
Duplicate of #18834

**Closed by PureWeen** 2024-05-03 21:06 UTC
Labels: t/bug, platform/android 🤖, area/collectionview 📃, s/triaged
