### ISSUE TITLE
Splash Screen does not update iOS

### ISSUE THREAD

**Issue by camgra** [dotnet/maui#8685] opened 2022-07-12 17:13 UTC
### Description

When changing the splashscreen (or icon), the changes are visible on both Android and iOS simulators, but when deployed to a physical device, it shows the original purple background with .NET in the centre.

I believe with the android device, there is another issue related to the icon being displayed instead of the splash screen, so the reproduction code was more for testing iOS then android. This is a known issue with the android version, so it was not tested

.NET Version: 6.0.400-preview22301.10
VS Pro Version: 17.3.0 Preview 2.0

Repro Code: https://github.com/camgra/maui-test-app

### Steps to Reproduce

1. Create a new .NET MAUI Blazor application
2. Replace the content of `splash.svg` with another image. (I used a text editor to do this)
3. Update the .csproj file, replacing the `BaseSize` value with `256,64`
4. Run the project on a simulator. I used an iPhone 13 Pro, 15.5.
5. Note the splash screen has been changed
6. Run the project on a device - I am using an iPhone 12 Pro, 15.5 for this. It is directly connected to Windows with Hot Reload, but it is paired to a Mac
7. Note the splash screen remains with the stock ".NET" item.

Not sure if it is related or not, but I found that in order to run the app on a physical iOS device, I had to add an `Entitlements.plist` to the project. I didn't see this documented anywhere, but I am only noting it here as it is different from the template

In another project, the same thing is happening with the icon which works with the simulator, but not with the physical device. I believe this has already been reported.... but I assume they are related. The repro code does not have the icon changed

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15.5

### Did you find any workaround?

No workaround at this time

**Comment by janseris** [comment] 2022-07-12 18:17
For me it happened that if I had an old app with the same name, it keeps running the old app or some of its parts

**Comment by jfversluis** [comment] 2022-07-14 13:23
Definitely there is some caching going on with this sometimes. Would you be able to confirm if you do a clean, rebuild, maybe delete your bin & obj folders and delete the app from the device if it was installed before? Does that help at all?

**Comment by camgra** [comment] 2022-07-15 11:47
@jfversluis, I tried several combinations of this before with no success. I also remove the solution from my PC and pulled it down from source control as well (since the bin and obj files are not included in the repo).
I ran it again on the simulator and confirmed that the splash screen was updated, and then tried on the physical device (iPhone) and it showed the original .NET splash screen. 
It also crashed with the following (on the physical device only):
`**System.Exception:** 'Could not find a .content folder in the app directory: /var/containers/Bundle/Application/6C321DA5-B789-41AD-8BE6-3E1922918ED2/MauiApp1.app'`. I don't know if that is related or not, but it is new since pulling and rebuilding it.

Just to rule out the iPhone I use for testing, I also provisioned an iPad that has not been used before for development and deployed the app to that. This test produced the same result as the iPhone, with the old splash screen and same system exception.

**Comment by SenexTech** [comment] 2022-07-19 22:24
I have the same issue.  No matter what I tried the Splash and App icon will not update on the directly connected iPhone.  Android works fine.  I have deleted the bin/Obj folders, did a solution clean, removed app from iPhone and reset iPhone.  Still the .NET logo and background are shown.

**Comment by kajetan-kazimierczak** [comment] 2022-08-13 23:46
I have the same issue. Here is what I found out
* I have this issue on both ios emulator and iPhone. Not android (or at least it fixes itself much faster so i didn’t notice)
* It could be relared to this old issue on Apple forum https://developer.apple.com/forums/thread/68244
* I uninstalled Visual Studio, all versions of dotnet. Deleted all the temp directoreis i could find, reinstalled all from scratch and still no luck.
 
**Workaround** that i found that usually works is this
* delete app from device/emulator and clear all data
* clean solution
* reboot device/emulator (this step is important)
* build and deploy app

The workaround works while developing but will probably not work on customers devices if the splash screen gets updated between versions. Unless they delete their app and data from the phone and reboot.

I run VS 17.3 on Windows 11 with the version of maui that came with it. Didn’t test on other dev setups

**Comment by mattleibow** [comment] 2022-10-07 11:17
Not sure what we can do here. The OS seems to not want to update the images. The obj and app package has the new images.

@dalexsoto is there any special thing that maybe the deployment can do? Like a `--reset-icon-cache-baby-please`? :)

**Comment by KSemenenko** [comment] 2022-10-07 12:42
if you will change name for svg file it will be changed

**Comment by mattleibow** [comment] 2022-10-09 07:18
Interesting... I wonder if it is caching the storyboard file and detect no change when changing the image. And the filename happens to update the xml.

I can try adding a dynamic comment to the storyboard to see...

Or maybe the renamed image invalidates the image cache...

**Comment by KSemenenko** [comment] 2022-10-09 10:06
Also if you will change svg file and will not chage the name, you will have mess with old and new icons.
also this is happend for Azure Pipline, so it's soooo strange.

**Comment by mattleibow** [comment] 2022-10-09 10:40
Is this on the same device? If you install the app onto a new device is the icon correct?

**Comment by KSemenenko** [comment] 2022-10-09 11:05
@mattleibow nope.
Old iPad 7 generation and iPhone 13 max pro have different images.

sometimes on iPad all is ok, but on iPhone I see old icon.
Or iPad is broken but iPhone is fine.

**Comment by mattleibow** [comment] 2022-10-09 11:32
Does it give the correct values if you uninstall and then reboot the device?

**Comment by KSemenenko** [comment] 2022-10-09 12:20
> Does it give the correct values if you uninstall and then reboot the device?

I build it on Azure Devon’s pipeline and install it from TestFlight, but when I will change name of file then all gone be fine.

so I will try it

**Comment by mattleibow** [comment] 2022-10-11 12:57
okays... so after a time that is too long to be happy about, I suddenly saw something... the OP was saying that they are using iOS hot restart (ios device attached to windows) and unfortunately the special app we use for that does not support changing the icon and splash screen. This is because the app is actually pre-built and using default assets.

I have started a discussion to either get dynamic asset support or at least change the default icon/splash to be different to the default template app so everyone knows it is special.

**Comment by mattleibow** [comment] 2022-10-11 18:54
Now I got some interesting things with the icon, it does not change on the device... but it does actually. I have the old image on the start screen, but when you open/close it, the zoom animation uses the new image:


https://user-images.githubusercontent.com/1096616/195175538-fab7ee28-01d8-4aa2-a3fc-439a9b76a4b7.mov

**Comment by mattleibow** [comment] 2022-10-11 20:29
Doing some more testing on my simulator now and things are not looking great. When you change the image name it seems to work because it has a new image to cache. I had an app that had splash1 and splash2, but I used splash1. When I switched to splash2 AND changed the color, it seemed to switch to splash2, but used the OLD color of splash2.

Something is being cached. If I reset the sim then it worked.

I bet when you say "but when I will change name of file then all gone be fine." you are using a totally new filename? I wonder what happens if you you a slightly older filename?

**Comment by janseris** [comment] 2022-10-11 20:45
@mattleibow these stuff used to happen for me also when the android package name was the same,  the phone might have cached it as well or something I was thinking (android)

**Comment by ebaldwin1** [comment] 2022-10-12 15:56
I'm also having this issue. I've renamed the svg's and uninstalled and reinstalled with no luck. When I hold the icon down it doesn't update. My splash screen is also the .NET default despite having changed it in code. Everything works fine when I deploy to both my android phone and the android simulator.

**Comment by mattleibow** [comment] 2022-10-12 18:03
Have you tried ubinstalling the app and rebooting the iPhone. Or resetting the simulator?

**Comment by ebaldwin1** [comment] 2022-10-12 23:37
I did try uninstalling, then rebooting. I can try it again, I'm using the hot reload function from windows with the iPhone directly connected to my computer. I've also updated to the newest non-preview release and updated to the newest windows 11 public release as well in the event it was something weird with either of those. I'll try uninstalling and rebooting then redeploying again and report back. When I changed the name, I just put the developer name in-front of the SVG names assuming that was enough as well.

**Comment by ebaldwin1** [comment] 2022-10-12 23:45
Ok, I just uninstalled, rebooted and redeployed and had the same issue. I also did an uninstall, reboot, clean solution, rebuild solution, redeploy with the same issue as well. This is on IOS 16.0.2 and 16.0.3 (I've upgraded to the latest security release since first attempting to resolve) on an Iphone 12 pro, if that makes any difference at all.

**Comment by mattleibow** [comment] 2022-10-13 00:39
Ah, this issue has devolved into so many side issues... But, the direct ios on windows feature does not support cuson splash screens and icons at the moment due to the way things are handled in the iOS-windows system

https://github.com/dotnet/maui/issues/8685#issuecomment-1274647794

**Comment by mattleibow** [comment] 2022-10-13 00:40
If you are using the iPhone on windows, this seems to be some caching issue and we are trying to see what is causing this as it appears xcode somehow invalidates the cache.

**Comment by ebaldwin1** [comment] 2022-10-13 12:59
good to know, thank you!

**Comment by KSemenenko** [comment] 2022-10-13 13:38
finally I can test it :)

**Comment by KSemenenko** [comment] 2022-10-13 14:33
now I can confirm.
1 - iPad after install app from TestFlight displayed right icon
2- iPhone is not.
2.1 After update app from TEstFlight I saw old icon.
2.2 I delet app and install it again - old icon.
2.3 I deleted app, restart phone, install app from TestFlight  and then I will have new icon

**Comment by KSemenenko** [comment] 2022-10-13 20:39
So, maybe we can generate unique name every build time? Like guid?

**Comment by mattleibow** [comment] 2022-10-14 18:38
I will test on xcode and see. I hear rumors that it does not have this issue and this makes me very scared.

If this still is the case, I will investigate some guid thing.

**Comment by mattleibow** [comment] 2022-10-17 22:42
I can reproduce this in Xcode as well. @davidortinau what did you do to get it to work? If I uninstall the app, it remains the old one.


https://user-images.githubusercontent.com/1096616/196296878-3710d2f1-d9d5-4845-a79b-af8114728e06.mov

**Comment by AathifMahir** [comment] 2022-10-18 00:47
Does this issue happen .Net 7 version of Maui?

**Comment by KSemenenko** [comment] 2022-10-18 05:44
Maybe this is some how connected with option to change icon from app?
https://medium.com/swlh/change-programmatically-your-app-icon-ios-swift-guide-3a8ee4f01649

**Comment by mattleibow** [comment] 2022-10-18 13:48
> Does this issue happen .Net 7 version of Maui?

This happens in net6, net7 and in objc/swift using xcode from apple. This is not an app thing I think, just the iPhone os.

**Comment by KSemenenko** [comment] 2022-10-18 17:58
lets generate random image name every time?

**Comment by mattleibow** [comment] 2022-10-18 18:44
That might be the only way - and luckily we generate so this is no work for you :)

**Comment by wagenheimer** [comment] 2022-10-18 22:21
I think this is a Apple Bug "by design"... Even Unity has this problem when updating Splash Screens. You need do restart the device or delete the App before updating it.

**Comment by mattleibow** [comment] 2022-10-20 19:30
I am trying to get a workaround (fix apple [il]logic), but this seems to work when swapping out the "filename" if the file changes.

Just add this to your .csproj:

```xml

	<Target Name="_FixMauiSplashScreens" BeforeTargets="ResizetizeCollectItems" Condition="'$(_ResizetizerIsiOSApp)' == 'True'">

		<!-- add a hash to each file -->
        <GetFileHash Files="@(MauiSplashScreen)" HashEncoding="base64">
            <Output TaskParameter="Items" ItemName="_MauiSplashScreensWithHashes" />
        </GetFileHash>

		<!-- update the splahs items and set the filename to be the 'splash_<hash>' -->
        <ItemGroup>
			<MauiSplashScreen
				Update="@(MauiSplashScreen)"
				Link="splash_$([MSBuild]::ValueOrDefault('%(_MauiSplashScreensWithHashes.FileHash)', '').Replace('+','').Replace('/','').Replace('=',''))" />
        </ItemGroup>

    </Target>
```

**Comment by bobwhitten** [comment] 2022-10-20 23:21
While scrolling through all this, I found something telling:   I could not get this splash screen to update to my image (purple .NET box) on my iPad with iOS 16. I did a lot of CLEAN, delete bin/obj, delete the App, then did a power-cycle. All no help.

Pulled out a different iPad (ios 15, if it matters).   Well, now I see the right splash screen.  

So, I don't know what's going on, but starting to look like it is NOT related to MAUI (which, I think others have deduced...).  

Finally, on iPad Air with iOS 16, deleted App, power-cycled, then run debug from VS (windows).  NOW it works.

I can't say if it's an iOS 16 thing, but if it is -- OK, THAT'S WEIRD.  Cache the Splash, but it hangs around even if app deleted?

**Comment by ZitaRR** [comment] 2022-10-21 10:35
Just to clarify, does this only happen when you run it in the debugger or would the default splash screen persist in the published iOS app even though one have modified the `MauiSplashScreen` tag in .csproj?

**Comment by KSemenenko** [comment] 2022-10-21 11:19
it happend every time, each instalation.
so if you will change icon - also change name of it

**Comment by mattleibow** [comment] 2022-10-21 15:19
or use the workaround in the comment above: https://github.com/dotnet/maui/issues/8685#issuecomment-1286038152

Let me know if this fixes things. I will be doing this for officials here: https://github.com/dotnet/maui/pull/10812

**Comment by KSemenenko** [comment] 2022-10-21 19:46
I will wait for it

**Comment by ZitaRR** [comment] 2022-10-25 13:01
I've changed the name as well as copy pasted the work around commented above but to no avail. Still the default icon and splash screen even though they've been deleted. Works fine on Android, which you already know but I'm just saying...

**Comment by mattleibow** [comment] 2022-10-26 08:07
@ZitaRR , are you on windows trying to deploy to ios? If so, this is a known issue

https://github.com/dotnet/maui/issues/8685#issuecomment-1274647794

**Comment by ZitaRR** [comment] 2022-10-26 08:22
@mattleibow Oh I must have missed that one, well then that explains it. English is not my native language so please correct me if I'm wrong but if I were to publish the app with the workaround you posted earlier, the app icon as well as the splash screen *should* be there for the end user?

**Comment by mattleibow** [comment] 2022-10-26 14:24
@ZitaRR it should be there. DO you have access to a build from something like Hockey App or another CI and distribution system to confirm?

If you have a mac machine, you can also test using the mack build agent. That hould be working.

**Comment by ZitaRR** [comment] 2022-10-27 07:18
@mattleibow I will give it a go with apples testflight. Hopefully it will have the correct assets, thanks for responding! :)

**Comment by KamelDj37** [comment] 2022-11-02 19:04
Hello, the problem persists for me. The application always generates a default start screen and icon on ios (physical).

**Comment by mattleibow** [comment] 2022-11-03 23:56
@KamelDj37  the current workaround is to rename the icon file each time it changes.

There is a draft PR #10812 where we are looking to automatically generate the new image name for you.

**Comment by ZitaRR** [comment] 2022-11-07 14:07
Just wanted to let you know that everything works fine. Thank you very much @mattleibow for your assistance! :)

**Comment by KamelDj37** [comment] 2022-11-08 07:36
@ZitaRR Could you describe me the steps you have done to successfully change the icon and the start screen on ios (physical device) please?

**Comment by KSemenenko** [comment] 2022-11-08 08:10
1. delete app
2. restart device
3. if you use old workload - change name for splashscren file to new one.
4. build and deploy
5. repeat 3-5 steps

**Comment by ZitaRR** [comment] 2022-11-09 09:46
@KamelDj37 Use the workaround from [this comment](https://github.com/dotnet/maui/issues/8685#issuecomment-1286038152). Note: It won't work on iOS physical devices when you're running it with the debugger. It will only work when you've published the app as an IPA file.

**Comment by ZitaRR** [comment] 2022-11-09 10:09
@mattleibow I seem to have run into another issue now, though I'm not entirely sure if this is something with MAUI or if it's on my end. Basically, on iOS once the splash screen finishes the screen flashes purple (MAUI default color). I've attached a video showing what happens though on the simulator the 'flash' has a noticeable duration. On a physical device it's more of real flash, it's really quick but you can easily notice it.

https://user-images.githubusercontent.com/28029645/200801686-9b1fa1e2-7403-403e-914d-e34d5b6f6074.mov

**Comment by KamelDj37** [comment] 2022-11-09 10:32
@ZitaRR @KSemenenko Thank you for your feedback

**Comment by faceoffers28** [comment] 2022-12-01 19:24
I made a change to the splash page on a Saturday. The page never updated, so I moved on to something else. On Thursday evening, I noticed that the splash page had finally updated. I never deleted the app, but I did many, many installs over the same time period. Not sure why it finally updated, but it did. I'm sure there is a logical explanation for the timing.

**Comment by bobwhitten** [comment] 2022-12-01 21:06
@faceoffers28  -- logical explanation:  Apple shenanigans.  It appears they cache this, so maybe their alg decided the cache was stale.  Maybe cuz date 5 days ago?

**Comment by npostma** [comment] 2023-01-15 11:44
I've run this also. This worked for me (mentioned by @kajetan-kazimierczak )

- delete app from device/emulator and clear all data
- clean solution
- reboot device/emulator (this step is important)
- build and deploy app

Before i tried to delete bin/obj and clean the solution. This alone was not enough. Rebooting the emulator after de-installation did the trick.

**Closed** 2023-01-20 10:46 UTC
Labels: t/bug, area/single project ☝️, platform/iOS 🍎, p/1
