### ISSUE TITLE
[Feature ]Tag property Item on Buttons and other elements

### ISSUE THREAD

**Issue by davidbuckleyni** [dotnet/maui#2818] opened 2021-10-03 10:48 UTC
## Summary
Please  add in a tag element on buttons and various others than can be used to pass small amounts of information.

## API Changes

While james gave me an excellent example of how to accomplish this here in SO   https://stackoverflow.com/questions/69421588/xamarin-forms-retrieve-student-details-id-on-button-click-event-handler/69422158#69422158

In the old days we would have had the Tag attribute to be able to send small forms of information around the page if building thing dynamically such as buttons, While he did offer AutomateId as an option. He in end showed me how to use the bindcontext while that is great for various reasons.

Being able to do.

ButtonName.Tag = piece of info number string even data object was so handy.

e.g.

A new api var will need to be added to MauiButton to add the facility of Tag, or else this could be called Record or something simliar. So its not a more common name.

    var button = new Button ();
    button.Tag= student.Id;

This should be available in all platforms that have a button.

**Comment by jfversluis** [comment] 2021-10-05 17:59
I'm confused. You mention the `BindingContext` but I don't really understand why you can't use that for this scenario? Personally I don't see much added value in adding this.

**Comment by jfversluis** [comment] 2021-10-05 18:29
Also duplicate of #2098 

_If_ we were to add this, I think it would make more sense to do it on a higher level than `Button`. I will close the other issue as this contains a bit more detail though.

**Comment by jfversluis** [comment] 2022-06-15 10:23
Closing this for now as I don't see a lot of traction for this enhancement.

Personally I feel this is also not really promoting clean coding as it can cause for hidden features in your code. If you were to follow the MVVM pattern all can be done with databinding and such.

A big thanks for the suggestion and the write-up!

**Closed by jfversluis** 2022-06-15 10:23 UTC
Labels: t/enhancement ☀️, area/controls 🎮, control-general

**Comment by jfversluis** [comment] 2022-06-20 14:24
That is now 9 months ago. As mentioned: I don't see a lot of traction, ergo not a lot of people seem to want this and as mentioned earlier, I don't see much added value in adding this. Therefore I decided to close it for now and not keep things like these open for eternity. 

Maybe it's not the right time and it will resurface somewhere later on and peoples opinions have changed, or maybe not.
