### ISSUE TITLE
AppThemeBinding doesn't work on .NET7

### ISSUE THREAD

**Issue by BlyZeYT** [dotnet/maui#13627] opened 2023-03-01 22:20 UTC
### Description

When I use AppThemeBinding in .NET7 the Theme just not changes when I change between light and dark theme. I copied the exact same project in .NET6 and everything works just fine.

### Steps to Reproduce

1. Create the sample .NET Maui project and set any color with an AppThemeBinding.
2. Start the app and see how it doesn't change when switching themes.

Expected outcome: Switches between the 2 themes
Actual outcome: It doesn't switch anything

### Link to public reproduction project repository

The template project

### Version with bug

7.0 (current)

### Last version that worked well

6.0.424

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 12

### Did you find any workaround?

No workaround found.

I could use Dynamic Resource but than the AppThemeBinding is useless.

**Comment by jfversluis** [comment] 2023-03-02 10:41
Could you elaborate a bit more about "set any color with an AppThemeBinding."?

How are you doing that exactly? On what element?

I guess in this case we might not need a full-blown GitHub repo to show it, but at least please give some relevant concrete code that we can try to reproduce this issue.

**Comment by Cybrosys** [comment] 2023-03-02 16:26
Perhaps related to:
https://github.com/dotnet/maui/issues/11299
and
https://github.com/dotnet/maui/issues/13619

There seems to be several issues related to DynamicResource bindings, even I created one when used with MCT StatusBarBehavior, but it's in the MCT repo.

**Comment by BlyZeYT** [comment] 2023-03-02 16:38
> Could you elaborate a bit more about "set any color with an AppThemeBinding."?
> 
> How are you doing that exactly? On what element?
> 
> I guess in this case we might not need a full-blown GitHub repo to show it, but at least please give some relevant concrete code that we can try to reproduce this issue.

I will send the Code soon I'm not Home yet :)

**Comment by BlyZeYT** [comment] 2023-03-02 20:18
> Could you elaborate a bit more about "set any color with an AppThemeBinding."?
> 
> How are you doing that exactly? On what element?
> 
> I guess in this case we might not need a full-blown GitHub repo to show it, but at least please give some relevant concrete code that we can try to reproduce this issue.

MainPage.xaml code:

```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="LoginManager.MainPage"
             BackgroundColor="{AppThemeBinding Light={StaticResource LightBackground}, Dark={StaticResource DarkBackground}}">

    <ScrollView>
        <VerticalStackLayout
            Spacing="10"
            Padding="25,0"
            VerticalOptions="Center">

            <Border StrokeThickness="5"
                    StrokeShape="RoundRectangle 50,5,5,50"
                    Padding="25"
                    Margin="0,0,0,10"
                    Stroke="{AppThemeBinding Light={StaticResource LightSecondary}, Dark={StaticResource DarkSecondary}}"
                    BackgroundColor="{AppThemeBinding Light={StaticResource LightAccent}, Dark={StaticResource DarkAccent}}"
                    Style="{StaticResource Border}">
                <Label Text="Login Manager"
                       HorizontalTextAlignment="Center"
                       VerticalTextAlignment="Center"
                       FontSize="50"
                       FontAttributes="Bold"
                       Style="{StaticResource Label}"/>
            </Border>

            <Button Text="Leon"
                    FontSize="50"
                    Padding="10,25,10,25"
                    Margin="25,0,25,0"
                    Style="{StaticResource Button}"/>

            <Button Text="Alexandra"
                    FontSize="50"
                    Padding="10,25,10,25"
                    Margin="25,0,25,0"
                    Style="{StaticResource Button}"/>

            <Button Text="Wolfgang"
                    FontSize="50"
                    Padding="10,25,10,25"
                    Margin="25,0,25,0"
                    Style="{StaticResource Button}"/>

        </VerticalStackLayout>
    </ScrollView>

</ContentPage>
```

App.xaml code:

```
<?xml version = "1.0" encoding = "UTF-8" ?>
<Application xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:local="clr-namespace:LoginManager"
             x:Class="LoginManager.App">
    <Application.Resources>
        <Color x:Key="DarkPrimary">#009688</Color>
        <Color x:Key="LightPrimary">#0277BD</Color>
        <Color x:Key="DarkSecondary">#26A69A</Color>
        <Color x:Key="LightSecondary">#03A9F4</Color>
        <Color x:Key="DarkBackground">#212121</Color>
        <Color x:Key="LightBackground">#F5F5F5</Color>
        <Color x:Key="DarkText">#ECEFF1</Color>
        <Color x:Key="LightText">#F1F1F1</Color>
        <Color x:Key="DarkAccent">#FFC107</Color>
        <Color x:Key="LightAccent">#FF5722</Color>

        <Style TargetType="Button" x:Key="Button">
            <Setter Property="BackgroundColor" Value="{AppThemeBinding Light={StaticResource LightPrimary}, Dark={StaticResource DarkPrimary}}"/>
            <Setter Property="CornerRadius" Value="20"/>
            <Setter Property="BorderWidth" Value="5"/>
            <Setter Property="BorderColor" Value="{AppThemeBinding Light={StaticResource LightAccent}, Dark={StaticResource DarkAccent}}"/>
            <Setter Property="TextColor" Value="{AppThemeBinding Light={StaticResource LightText}, Dark={StaticResource DarkText}}"/>
        </Style>

        <Style TargetType="Label" x:Key="Label">
            <Setter Property="TextColor" Value="{AppThemeBinding Light={StaticResource LightText}, Dark={StaticResource DarkText}}"/>
        </Style>

        <Style TargetType="Border" x:Key="Border">
            <Setter Property="Stroke" Value="{AppThemeBinding Light={StaticResource LightAccent}, Dark={StaticResource DarkAccent}}"/>
            <Setter Property="BackgroundColor" Value="{AppThemeBinding Light={StaticResource LightPrimary}, Dark={StaticResource DarkPrimary}}"/>
        </Style>
    </Application.Resources>
</Application>
```

**Comment by BlyZeYT** [comment] 2023-03-04 20:25
I tried this too but this doesn't work either, the event isn't even fired.

```
public App()
{
	InitializeComponent();

        Current.RequestedThemeChanged += SystemThemeChanged;

	MainPage = new AppShell();
}

private void SystemThemeChanged(object sender, AppThemeChangedEventArgs e)
	=> Current.UserAppTheme = e.RequestedTheme == AppTheme.Unspecified ? AppTheme.Light : e.RequestedTheme;
```

**Comment by mattleibow** [comment] 2023-03-07 22:20
Duplicate of https://github.com/dotnet/maui/issues/8236

**Closed by mattleibow** 2023-03-07 22:20 UTC
Labels: t/bug, platform/android 🤖, s/needs-attention, i/regression, area/theme
