### ISSUE TITLE
CollectionView has default spacing between items on Windows which I cannot remove

### ISSUE THREAD

**Issue by samuelradford** [dotnet/maui#12495] opened 2023-01-07 22:36 UTC
### Description

The documentation says that a CollectionView has no default spacing between items. However, when adding a simple Label element, there is clear spacing between the items. I have tried multiple ways to remove this but cannot seem to find a way. 

This happens on Windows. MacCatalyst seems OK.

### Steps to Reproduce

1) Create a new .NET MAUI project
2) Remove the default MainPage.xaml content and replace with the following:

```csharp
    <Grid RowDefinitions="*"
          ColumnDefinitions="*">
        <CollectionView Grid.Row="0" Grid.Column="0" 
                        ItemsSource="{Binding Strings}"
                        BackgroundColor="Red">
            <CollectionView.ItemTemplate>
                <DataTemplate x:DataType="local:MainPage">
                    <Label Text="{Binding .}"
                           TextColor="Black"
                           FontSize="14"
                           BackgroundColor="Yellow"/>
                </DataTemplate>
            </CollectionView.ItemTemplate>
        </CollectionView>
    </Grid>
```
3) Remove the default MainPage.xaml.cs code behind and replace with the following:
```csharp
public partial class MainPage : ContentPage
{
    public List<string> Strings { get; set; }
    public MainPage()
	  {
               InitializeComponent();
               Strings = new();
               AddStrings();
	       BindingContext = this;
	  }
    void AddStrings()
    {
        for (var i = 0; i < 10; i++)
        {
            Strings.Add("CollectionView shouldn't have spacing between items");
        }
    }
}
```

4) Run the application

In my example I have set the CollectionView background to Red and the Label's to Yellow to clearly show where the spacing occurs.

You can see in this example that the Labels have space between then, even though in the documentation it says:

![image](https://user-images.githubusercontent.com/19474685/211172691-5d3beaa3-e579-458c-88c9-e52854634ecc.png)

Source - https://learn.microsoft.com/en-us/dotnet/maui/user-interface/controls/collectionview/layout?view=net-maui-7.0

Example of application running

![image](https://user-images.githubusercontent.com/19474685/211172703-99eb1446-6ebd-4068-9eb9-2677cd32b78a.png)

### Link to public reproduction project repository

https://github.com/samuelradford/Reproduction.MAUICollectionViewSpacing

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 11 (OS Build: 22000.1335)

**Comment by Vroomer** [comment] 2023-01-08 00:37
Duplicate of https://github.com/dotnet/maui/issues/4520

It's indeed annyoing bug and so far I didn't see any workaround for this.

**Comment by PureWeen** [comment] 2023-09-07 22:35
This was rebroken by

https://github.com/dotnet/maui/pull/14532

Once this is fixed please verify
- https://github.com/dotnet/maui/issues/4520
- https://github.com/dotnet/maui/issues/15241
- https://github.com/dotnet/maui/issues/15529

**Closed** 2023-09-08 02:22 UTC
Labels: t/bug, platform/windows 🪟, area/collectionview 📃, i/regression
