### ISSUE TITLE
Web Development

### ISSUE THREAD

**Issue by dgxhubbard** [dotnet/maui#8144] opened 2022-06-17 21:35 UTC
### Description

I started looking at .net maui, because I wanted to do web development with xaml.
Then I realized .net maui does not have that capability. Is this always going to be the case
or will .net maui bring xaml to the web?

### Public API Changes

none

### Intended Use-Case

To be able to use xaml for web development like I used to with silverlight

**Comment by PirasathLuxchumykanthan** [comment] 2022-06-18 06:53
why you want to use xaml to web development ?

Well there are templeted for .net maui blazor pretty cool

**Comment by jfversluis** [comment] 2022-06-18 07:27
Duplicate of #4528

**Closed by jfversluis** 2022-06-18 07:27 UTC
Labels: proposal/open
