### ISSUE TITLE
Editor CursorPosition goes to start after adding any character to text

### ISSUE THREAD

**Issue by HobDev** [dotnet/maui#5803] opened 2022-04-04 15:40 UTC
### Description

I need to add a "-" in the Editor after every 8 characters. I am doing so using `TextChanged` Event. The issue on Android is that the Cursor goes back to start after each insertion of "-". 

### Steps to Reproduce

Run the app and insert any characters in the editor. 
[Issueproject.zip](https://github.com/dotnet/maui/files/8411083/Issueproject.zip)

### Version with bug

Preview 14 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

**Comment by kristinx0211** [comment] 2022-04-05 10:44
repro on Android 12.

**Comment by samhouts** [comment] 2022-04-27 02:21
This has the same root cause as #5401, so I am closing as a duplicate. Thanks!!!!

**Comment by samhouts** [comment] 2022-04-27 02:21
Duplicate of #5401

**Closed by samhouts** 2022-04-27 02:21 UTC
Labels: t/bug, s/duplicate 2️⃣, area/controls 🎮, s/verified, control-entry

**Comment by HobDev** [comment] 2022-04-27 05:19
@samhouts  the difference between the two issues is #5401 is about the user input. while this one #5803 is about programmatic  input.  Still if the cause is same than it's fine to close this one.

**Comment by samhouts** [comment] 2022-04-28 00:20
When the Entry is in password mode on Android, we programmatically replace the characters with asterisks (*) to hide the user's input. So while it looks like the bug is with user input, it's actually the programmatic input. 😄
