### ISSUE TITLE
Removing the entire ContentPage.Resources element does not trigger the UI updates

### ISSUE THREAD

**Issue by mattleibow** [dotnet/maui#11877] opened 2022-12-05 18:09 UTC
### Description

I am using XAML Hot Reload...

Using the default maui template, I can add/remove/change properties in resource dictionaries - and even remove the whole dictionary.

But, if I remove the entire `<ContentPage.Resources>` node, then the controls are not updated.

### Steps to Reproduce

1. File | New | Maui app
2. Run
3. Add this xaml
    ```xaml
    <ContentPage.Resources>
        <ResourceDictionary>
            <Style TargetType="Button">
                <Setter Property="Background" Value="Red" />
            </Style>
        </ResourceDictionary>
    </ContentPage.Resources>
    ```
4. Observe the button background is now red
5. Change the value to "Blue"
6. Observe the button is now blue
7. Delete the `<ResourceDictionary>`
8. Observe the button is now the default purple again
9. Undo the change (add the `<RD>` back)
10. Observe the button is blue/red agan
11. Delete the entire `<ContentPage.Resources>` node
12. Observe the *color is not purple*

### Link to public reproduction project repository

File | New | Maui app and use the snippet

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, Android, I was *not* able test on other platforms

### Affected platform versions

Tested on Windows 11

**Comment by jonathanpeppers** [comment] 2023-02-07 17:07
This is duplicate of: https://github.com/dotnet/maui/issues/11082

When you remove a `<Setter Property="Background" Value="Red" />`, then it doesn't know the original value of what `Background` should be.

**Closed by jonathanpeppers** 2023-02-07 17:07 UTC
Labels: t/bug, area/Xaml </>, area/tooling ⚙️, partner/hot-reload-xaml, scenario-day

**Comment by samhouts** [comment] 2023-02-09 19:37
Duplicate of #11082
