### ISSUE TITLE
Button text not updating after button click

### ISSUE THREAD

**Issue by webrift** [dotnet/maui#8332] opened 2022-06-26 14:55 UTC
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/device-setup
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I am using a dual boot Macbook and have windows 10 installed and MacOS.
I am working in the windows partition not the mac one.
I can build the adroidproject but when I click on the button, the text of the button is not updated like it did for the windows build.
Hyper-P has been enabled as per the instructions.

**Comment by jfversluis** [comment] 2022-06-27 07:59
Hey @webrift thanks so much for reporting this! So if I understand correctly, you can run the project on both Windows and Android. On Windows it works as intended, but for Android the text in the button does not update when you click it?

Does it show any change at all? If you put a breakpoint in the code that is triggered for the button does it actually hit that?

Could you maybe inside of Visual Studio go to the Help menu, then click About Microsoft Visual Studio and on the right click the Copy Info button and paste that info here so we know the exact versions of the tools you're working with? Thanks!

**Comment by hartez** [comment] 2022-06-28 14:58
Guessing this is another manifestation of the problems fixed by #8136.

**Comment by jfversluis** [comment] 2022-06-28 18:30
I would say so! Thanks for the report @webrift we believe this issue has been reported and is fixed but pending release. Please check if this is still an issue whenever we release our next version. If so, feel free to open a new issue refering to this one. Thanks!

**Closed by jfversluis** 2022-06-28 18:30 UTC
Labels: s/needs-attention, area/tutorials
