### ISSUE TITLE
Allow to set a custom MauiWinUIWindow

### ISSUE THREAD

**Issue by bdovaz** [dotnet/maui#19192] opened 2023-12-04 17:05 UTC
### Description

I am trying to do a complex customization that involves being able to interact with controls in the header of the screen following this tutorial:

https://learn.microsoft.com/en-us/windows/apps/develop/title-bar?tabs=winui3

As you can see in the complete code example, it requires to be able to have a custom window to be able to define the `InputNonClientPointerSource`:

https://learn.microsoft.com/en-us/windows/apps/develop/title-bar?tabs=winui3#full-customization-example

It would require this instantiation to be customizable in some way....

https://github.com/dotnet/maui/blob/babeeb28a828721cca9dc4bc16b5997c44e63138/src/Core/src/Platform/Windows/ApplicationExtensions.cs#L16

I tried to overwrite the `ApplicationHandler` type handler via `ConfigureMauiHandlers` but when trying to overwrite it I encountered several internal APIs that require me to have to use reflectivity... Several methods here (MakeWindowScope, InvokeLifecycleEvents and CreateWindow):

https://github.com/dotnet/maui/blob/babeeb28a828721cca9dc4bc16b5997c44e63138/src/Core/src/Platform/Windows/ApplicationExtensions.cs#L11

### Public API Changes

Expose a Func<Microsoft.UI.Xaml.Window> somewhere to allow default Window inheriting.

### Intended Use-Case

Make a complex title bar customization

**Comment by PureWeen** [comment] 2023-12-15 06:35
Duplicate of #16512

**Closed by PureWeen** 2023-12-15 06:35 UTC
Labels: proposal/open, area/desktop 🖥️
