### ISSUE TITLE
Missing sourceLocation metadata in assemblies when debug on iOS Platform

### ISSUE THREAD

**Issue by JaneySprings** [dotnet/maui#13548] opened 2023-02-24 19:55 UTC
### Description

Hello! I noticed that in Android in the MAUI Libraries there is a data about the location of the source codes
<img width="660" alt="Screenshot 2023-02-24 at 23 40 02" src="https://user-images.githubusercontent.com/48021947/221276734-058c5536-5165-4699-b254-aaac5ac374a2.png">

But if you run an iOS MAUI application, the sourceLocation section will be empty.
![image](https://user-images.githubusercontent.com/48021947/221277446-6d556401-c81a-40a0-a1d2-bc9256e24d41.png)

It would be nice if there was also an embedded link to the GitHub repo for debugging MAUI.

### Steps to Reproduce

null

### Link to public reproduction project repository

null

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 

### Did you find any workaround?

Workaround: https://github.com/xamarin/xamarin-macios/issues/11879

**Comment by JaneySprings** [comment] 2023-02-24 20:21
It looks like `dotnet` is not copying pdb files to the application:

<img width="427" alt="image" src="https://user-images.githubusercontent.com/48021947/221282791-40a47979-b06c-4334-8e99-a3c45d1b7b51.png">

But for android `dotnet` does it:

<img width="696" alt="image" src="https://user-images.githubusercontent.com/48021947/221282895-30dc3ef7-3734-4ca6-b58b-8ee4be401d87.png">

**Comment by rachelkang** [comment] 2023-02-28 19:19
Duplicate of https://github.com/xamarin/xamarin-macios/issues/11879

fyi @rolfbjarne

**Closed by rachelkang** 2023-02-28 19:19 UTC
Labels: t/bug
