### ISSUE TITLE
Image in Radio Button Not Displayed in Android Platform

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#12645] opened 2023-01-13 18:51 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Image-in-Radio-Button-Not-Displayed-in-A/10242311)._

---
Image in Radio Button Not Displayed in Android Platform

Look this Code:

```xaml
        <RadioButton>
            <RadioButton.Content>
                <Image Source="cat.png"/>
            </RadioButton.Content>
        </RadioButton>
```
And this result:

image.png
![image](https://user-images.githubusercontent.com/21988533/212993827-1ba07ebe-0c4a-4c6e-8d4c-c57e4a353182.png)

---
#### Feedback Bot on 1/2/2023, 06:22 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by rachelkang** [comment] 2023-01-17 19:29
Duplicate of #7881

**Closed by rachelkang** 2023-01-17 19:29 UTC
Labels: t/bug, platform/android 🤖, area/controls 🎮, control-radiobutton
