### ISSUE TITLE
Can't open Picker/DatePicker Programatically with .Focus() like i used to do in Xamarin.Forms.

### ISSUE THREAD

**Issue by kelputoo123** [dotnet/maui#20913] opened 2024-02-29 12:02 UTC
### Description

Hi everyone, i don't know if there is other way to do this, but i used to do it in Xamarin.Forms.
Now im trying to upgrade my app from Xamarin.Forms to MAUI.NET and it doesn't work the **.Focus()**.
Is there any way to do it programatically? I really need to, because i personally dont like the default design that it comes, so i want to create a gesture to open it programatically. 

### Steps to Reproduce

1. Create a MAUI.NET Project
2. Add the followin in a XAML:
```
        <Button Text="Open Time Picker" Clicked="Button_Clicked_1" ></Button>
        <DatePicker x:Name="date_picker"></DatePicker>
```
3. Add the following code in code:
```
    private void Button_Clicked_1(object sender, EventArgs e)
    {
        date_picker.Focus();
    }
```
4. Run the app, it won't work, but it used to work in Xamarin.Forms.

### Version with bug

8.0.7 SR2

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

Android 12.0 (API 31) using .NET 8.

### Did you find any workaround?

No.

**Comment by PureWeen** [comment] 2024-02-29 16:21
Duplicate of #8946

**Closed by PureWeen** 2024-02-29 16:21 UTC
Labels: t/bug, area/controls 🎮, control-datetimepicker, control-picker, migration-compatibility

**Comment by kelputoo123** [comment] 2024-03-01 09:48
It's duplicated but however still without a fix. Tried that thread and doesn't work either.
