### ISSUE TITLE
[Windows 10] Feature for allowing to expand Shell.TitleView without clicking See more button

### ISSUE THREAD

**Issue by Laradius** [dotnet/maui#8597] opened 2022-07-07 16:00 UTC
### Description

I would love to have this feature, so I could make more use of built in customizable Shell.TitleView without being worried about controls gettings clipped and being forced to press "See more button" (those 3 dots)
![Screenshot_4](https://user-images.githubusercontent.com/31272990/177818937-6a785c2d-f006-49d9-b286-a6180f40cb1e.png)

```xaml
<Shell.TitleView>
    <Entry />
</Shell.TitleView>
    
<ContentPage.ToolbarItems>
    <ToolbarItem Text="An Item" />
</ContentPage.ToolbarItems>
```

### Public API Changes

Shell.ExpandTitleView()

Expands title view automatically without needing to press "See more button"

### Intended Use-Case

Customizing Shell.TitleView for more enjoyable user experience.

**Comment by Cywizz** [comment] 2022-07-08 07:13
I agree, would be great to have this functionality

**Comment by mattleibow** [comment] 2023-04-26 17:31
Duplicate of #12063

**Closed by mattleibow** 2023-04-26 17:32 UTC
Labels: proposal/open, platform/windows 🪟, area/shell 🐢, s/needs-repro
