### ISSUE TITLE
Java.Lang.IllegalStateException: The specified child already has a parent. Easy to repro

### ISSUE THREAD

**Issue by AlleSchonWeg** [dotnet/maui#20310] opened 2024-02-02 14:44 UTC
### Description

If you remove a control from a layouts child collection the native parents are not set to null. This results in a crash, if you try to add it again.
Reprocode:
```c#
            LayoutGrid.Children.Remove(scroller);
            scroller.Content = null; //new Label(); //In XF this line sets the native parent from the "stack" to null. Not in MAUI
            Grid.SetRow(stack, 0);
            Grid.SetColumn(stack, 0);
            var platform = stack.Handler.PlatformView;
            LayoutGrid.Children.Add(stack);
```
`scroller.Content` sets the VirtualViews Parent to null, but not the PlatformViews Parent. 

### Steps to Reproduce

Click button in repro

### Link to public reproduction project repository
[MauiApp5.zip](https://github.com/dotnet/maui/files/14141539/MauiApp5.zip)

_No response_

### Version with bug

8.0.6

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows

**Comment by mattleibow** [comment] 2024-02-02 15:30
Duplicate of https://github.com/dotnet/maui/issues/15920

**Closed by mattleibow** 2024-02-02 15:30 UTC
Labels: t/bug, area/layout 🔲, platform/android 🤖

**Comment by AlleSchonWeg** [comment] 2024-02-02 16:00
@mattleibow Why is this by design? 
Sometimes if you rotate the device you need to layout the UI completely different. So you have to rearrange the controls or need an additional scroll view. depending on your layout complexity.
Just setting scroller.Content = new Label () works. Setting to null causes the exception. 🤪
