### ISSUE TITLE
On ios, the editor's placeholder position does not match the value of VerticalTextAlignment.

### ISSUE THREAD

**Issue by singhwong** [dotnet/maui#19497] opened 2023-12-19 15:43 UTC
### Description

For example, if you set the `VerticalTextAlignment` value to Start, the cursor will be in the correct position, but the `Placeholder` will be vertically centered.

https://github.com/dotnet/maui/assets/39898152/192085ee-ff08-43cc-aad3-77681c8e44ea

### Steps to Reproduce

1. Run sample
[placeholder_issue.zip](https://github.com/dotnet/maui/files/13717453/placeholder_issue.zip)
2. Click button, change the value of `VerticalTextAlignment` and observe the position change of `Placeholder`.

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.101

### Affected platforms

iOS

### Affected platform versions

iOS 15

**Comment by PureWeen** [comment] 2023-12-19 19:11
Duplicate of #19121

**Closed by PureWeen** 2023-12-19 19:11 UTC
Labels: t/bug
