### ISSUE TITLE
MacCatalyst Picker not working

### ISSUE THREAD

**Issue by cdavidyoung** [dotnet/maui#18363] opened 2023-10-26 00:26 UTC
### Description

I am having problems with my app on MacCatalyst that runs fine of Windows/Android/iPhone.  Menus and DisplayActionSheet are not showing up as they should.  I decided to check out the maui-samples to see if I could find something similar that was not working.  I found that neither the ControlGallery Picker nor TimePicker do work.  Is anyone else having the same problem with MacCatalyst?

![image](https://github.com/dotnet/maui/assets/937899/f72ac808-70a9-455d-9425-8f5a086cffa7)

### Steps to Reproduce

Install the code at [maui-samples ](https://github.com/dotnet/maui-samples) and run the ControlGallery solution.  Select either the Picker or TimePicker.  Neither work for me building on a Mac M1.

### Link to public reproduction project repository

https://github.com/dotnet/maui-samples

### Version with bug

7.0.96

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

**Comment by drasticactions** [comment] 2023-10-26 11:06
Duplicate of https://github.com/dotnet/maui/issues/18015

**Closed by drasticactions** 2023-10-26 11:06 UTC
Labels: t/bug, platform/macOS 🍏, area/controls 🎮, control-picker
