### ISSUE TITLE
[Windows] Webview memory leak

### ISSUE THREAD

**Issue by bronteq** [dotnet/maui#21194] opened 2024-03-13 22:39 UTC
### Description

Ram memory increases every time a page containing a WebView control is shown.

The bug was tested in Maui 8.0.3, 8.0.6, 8.0.7, 8.0.10 (the last version is not available in "Version with bug" list template), every version is affected.

The same problem seems to be present in Maui Android, as described in this issue: https://github.com/dotnet/maui/issues/18021

### Steps to Reproduce

-Execute the reproduction project in release mode (debug mode has the same behaviour)
-Move to New Page and go back 4-5 times by clicking on button "Go to New Page - Event": Task Manager will show a WebView2 entry for every time that New Page is visited, and a consequent high ram usage, potentially infinite
-Manual call to Garbage Collector can be done by clicking the button "Garbage Collector", but the WebViews are not destroyed

![image](https://github.com/dotnet/maui/assets/159045969/16928a04-6d20-45cb-950e-0d01632ed8b9)

### Link to public reproduction project repository

https://github.com/bronteq/maui_webview_issue

### Version with bug

8.0.7 SR2

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 11 23H2, Edge 122.0.2365.80

### Did you find any workaround?

None

**Comment by bronteq** [comment] 2024-03-13 22:50
This is the result of a release execution after 12 page changes

![image](https://github.com/dotnet/maui/assets/159045969/cbc46f5d-855f-47de-93e3-2399320d9331)

**Comment by Zhanglirong-Winnie** [comment] 2024-03-14 03:29
Verified this issue with Visual Studio 17.10.0 Preview 2. Can repro on windows platform with sample project.
https://github.com/bronteq/maui_webview_issue

**Comment by drasticactions** [comment] 2024-03-15 03:13
https://github.com/bronteq/maui_webview_issue/blob/253a71653624ab3dd6921e7ae264cf3bcf65d382/MauiAppWebview/MainPage.xaml.cs#L26

I'm not sure this is a memory leak, this feels more like a implementation issue with Shell.

If I understand this right, this is creating a new page every time you navigate. Navigating back doesn't necessarily dispose the page you were on (I am not sure if it does, or if it's a thing handled by general garbage collection) so that web view will still exist since the page isn't removed, and you're creating new ones every time.

@PureWeen What do you think?

**Comment by bronteq** [comment] 2024-03-15 09:12
This is the result with WebView, the destructor is never called with explicit GC request
![WebViewDestructor](https://github.com/dotnet/maui/assets/159045969/7e5ec45b-d67c-4624-815b-3fb5218de30e)

This instead is what happens by using a Label
![LabelDestructor](https://github.com/dotnet/maui/assets/159045969/72aa1b29-2446-47db-a28d-28b1af963d48)

I tried to write the most basic working code able to reproduce the bug, the Shell documentation seems to describe the navigation pattern used in this program, if something is wrong I am open to suggestions

**Comment by drasticactions** [comment] 2024-03-15 12:30
I apologize; I wasn't trying to imply that you were doing something wrong, but that Shell's operation was at fault and either not clearing pages when it should be, or forcing you to have to handle elements where you shouldn't have to dispose.

Looking at this outside of Shell, you can repro it, and there's already an issue filed for it. 

Duplicate of https://github.com/dotnet/maui/issues/20283

**Closed by drasticactions** 2024-03-15 12:30 UTC
Labels: t/bug, platform/windows 🪟, s/verified, control-webview, s/triaged
