### ISSUE TITLE
Windows - Entry does not horizontally fill in 8.0.90

### ISSUE THREAD

**Issue by sbloomztf** [dotnet/maui#24910] opened 2024-09-24 18:39 UTC
### Description

Entry control for windows has been quite severely broken from 8.0.82 to 8.0.90.   The entry no longer fills horizontally, even with HorizonatalOptions = Fill.  It seems to want to take the width of the text or placeholder text for the overall width of the entry.  It's quite useable in this state.

### Steps to Reproduce

Add an entry to a view and run in windows.  Here's is an example of just one entry in my app.

```
<Entry Placeholder="Enter user name or email"
       IsSpellCheckEnabled="False"
       Text="{Binding UserNameOrEmail}">
    <Entry.Keyboard>
        <Keyboard x:FactoryMethod="Create">
            <x:Arguments>
                <KeyboardFlags>CapitalizeNone</KeyboardFlags>
            </x:Arguments>
        </Keyboard>
    </Entry.Keyboard>
</Entry>
```

### Version with bug

8.0.90 SR9

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.82 SR8.2

### Affected platforms

Windows

### Did you find any workaround?

No workaround found

**Comment by Foda** [comment] 2024-09-24 22:11
Dupe of: https://github.com/dotnet/maui/issues/24783

**Closed by Foda** 2024-09-24 22:11 UTC
Labels: t/bug, platform/windows 🪟, potential-regression
