### ISSUE TITLE
XA1018 on visual studio 2022 0 release 17.8.0

### ISSUE THREAD

**Issue by JedhaDev** [dotnet/maui#18827] opened 2023-11-17 07:00 UTC
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/create
Operating System: windows

XA1018 android manifest file does not exist as soon as the project is created

**Comment by mattleibow** [comment] 2023-11-17 19:31
Thanks for reporting this issue. 

Does it still build? 

I believe this is a few things happening together that result in this error for a few seconds until the nugets restore.

**Comment by JedhaDev** [comment] 2023-11-18 07:57
hello

it doesn’t builds, nugets indicates restored also at vstudio status
indicates ready

kind regards

**Comment by jfversluis** [comment] 2024-03-27 08:56
Duplicate of #21406

**Closed by jfversluis** 2024-03-27 08:56 UTC
Labels: area/single project ☝️, s/needs-attention, tutorials
