### ISSUE TITLE
[iOS16] Crash when tapped on text in Entry

### ISSUE THREAD

**Issue by michalpr** [dotnet/maui#10727] opened 2022-10-17 08:03 UTC
### Description

App crashes on iOS 16.x when user taps on text in Entry. On lower versions of iOS (i.e. 15.x or 14.x) works well.

**dotnet --list-sdks**
2.1.4 [C:\Program Files\dotnet\sdk]
2.1.202 [C:\Program Files\dotnet\sdk]
2.1.526 [C:\Program Files\dotnet\sdk]
3.1.424 [C:\Program Files\dotnet\sdk]
5.0.100 [C:\Program Files\dotnet\sdk]
5.0.401 [C:\Program Files\dotnet\sdk]
5.0.408 [C:\Program Files\dotnet\sdk]
5.0.412 [C:\Program Files\dotnet\sdk]
6.0.200 [C:\Program Files\dotnet\sdk]
6.0.202 [C:\Program Files\dotnet\sdk]
6.0.203 [C:\Program Files\dotnet\sdk]
6.0.402 [C:\Program Files\dotnet\sdk]

**dotnet workload list**
android-33 | 32.0.476/6.0.400 | SDK 6.0.400
maui | 6.0.541/6.0.400 | SDK 6.0.400
maui-android | 6.0.541/6.0.400 | SDK 6.0.400, VS 17.3.32929.385
maui-desktop | 6.0.541/6.0.400 | SDK 6.0.400
maui-ios | 6.0.541/6.0.400 | SDK 6.0.400, VS 17.3.32929.385
maui-mobile | 6.0.541/6.0.400 | SDK 6.0.400
maui-tizen | 6.0.541/6.0.400 | SDK 6.0.400
maui-windows | 6.0.541/6.0.400 | VS 17.3.32929.385
maui-maccatalyst | 6.0.541/6.0.400 | VS 17.3.32929.385
maccatalyst | 15.4.465/6.0.400 | VS 17.3.32929.385
ios | 16.0.517/6.0.400 | VS 17.3.32929.385
android | 32.0.476/6.0.400 | VS 17.3.32929.385
wasm-tools | 6.0.10/6.0.400 | VS 17.3.32929.385

Xamarin.iOS and Xamarin.Mac SDK   16.0.0.75 (e4f48bed7)

Microsoft Visual Studio Community 2022 (64-bit), Version 17.3.6

Remote build on macOS Monterey 12.6
with
XCode 14.0.1

### Steps to Reproduce

1. Create a new project using ".NET MAUI App" template
2. Add new Entry to MainPage.xaml with some default text (i.e. add attribute Text="some default text")
3. Change "Target iOS Framework" project property to highest value ("net6.0-ios15.4" in my case), but you can leave default "net6.0-ios"
4. Adjust Provisioning if needed
5. Run the project on iOS 16.x (does not matter if on Local Device or Simulator)
6. Tap onto text in Entry
7. and app immediately crashes/disapears

### Link to public reproduction project repository

https://github.com/michalpr/MauiEntryTest

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 16.x

### Did you find any workaround?

No

### Relevant log output

```shell
2022-10-17 09:15:02.268 Xamarin.PreBuilt.iOS[904:226798] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[<_UIObscurableTextContentStorage: 0x282b01ef0> offsetFromLocation:toLocation:] received invalid locations 0 (null)'
*** First throw call stack:
(0x1cd8be248 0x1c6c8ba68 0x1cd9ade04 0x1d7b1f6a0 0x1d03cc904 0x1cfd8fce4 0x1cfd8fc7c 0x1cfd8fc10 0x104f1b610 0x104ed932c 0x1051f7fc8 0x1051eded0 0x1051ec37c 0x1051be390 0x10510a96c 0x10510e250 0x104f14620 0x104f1a730 0x104f1b3d4 0x1cfb96238 0x1d065fd70 0x1d0661570 0x1d0914054 0x1d0913e4c 0x1d09145e0 0x1cfc916d8 0x1d0383728 0x1cfb01164 0x1cfe6edfc 0x1cfbe8b94 0x1cfac91dc 0x1cfb75358 0x1d03f61d8 0x1cfb39d18 0x1cfb3e674 0x1cfb3d944 0x1cfb3d000 0x1cfb84d64 0x1d07cba30 0x1d0093678 0x1d06d2904 0x1d06d1ad0 0x1cd98a22c 0x1cd996614 0x1cd91a51c 0x1cd92feb8 0x1cd9351e4 0x206755368 0x1cfde4d88 0x1cfde49ec 0x104ef05a4 0x1051f8b50 0x1051f7cb0 0x1051edde4 0x1051ec37c 0x1051be390 0x10510a96c 0x105111854 0x1050d2328 0x1050dca30 0x1051f8b1c 0x1
051f7cb0 0x1051edde4 0x1051ec37c 0x1051be390 0x10510a96c 0x105111234 0x1051c3174 0x104f1a55c 0x1052299c4 0x1ebc59948)
```

**Comment by michalpr** [comment] 2022-10-17 10:52
> Please check this one for the workaround: #10194

**WORKS** like charm!

Thank you, @RonnyRos! Didn't find this when searching...

**Comment by rmarinho** [comment] 2022-10-17 14:22
Duplicate of #10194

**Closed by rmarinho** 2022-10-17 14:22 UTC
Labels: t/bug, s/duplicate 2️⃣, version/ios-16
