### ISSUE TITLE
Maui FilePicker : On Android, the pick files are disabled. 

### ISSUE THREAD

**Issue by true-perfect-code** [dotnet/maui#13294] opened 2023-02-13 10:46 UTC
### Description

I refer to the already created post two weeks ago describing this behavior:

https://github.com/dotnet/maui/issues/9394#issuecomment-1364938908

About the problem: If you want to restrict file extension via options (e.g. XLSX) then it works on Android, but the listed Excel files are all disabled and you can't select any file. 
Workaround is (as described in the given post) that one passes only NULL instead of options, then all file types are displayed, but one can select the required file then.  

I'm interested if this problem is officially known, or is there a post about it here? I searched for FilePicker and Android, but could not find anything. My fear is that this important point is forgotten.

Thanks

### Steps to Reproduce

Use Microsoft Example from: https://learn.microsoft.com/en-us/dotnet/maui/platform-integration/storage/file-picker?view=net-maui-7.0&tabs=android

### Link to public reproduction project repository

https://github.com/dotnet/maui/issues/9394#issuecomment-1364938908

### Version with bug

6.0.312

### Last version that worked well

6.0.312

### Affected platforms

Android

### Affected platform versions

Android 11

### Did you find any workaround?

If I do not mention any file types (filePicker.PickAsync(null)) , it woks good, but shows all files.

**Comment by drasticactions** [comment] 2023-02-13 11:16
Duplicate of https://github.com/dotnet/maui/issues/9394.

**Closed by drasticactions** 2023-02-13 11:16 UTC
Labels: t/bug, s/duplicate 2️⃣
