### ISSUE TITLE
Moving the cursor in an Entry field causes crash in iOS 16

### ISSUE THREAD

**Issue by stanger** [dotnet/maui#10427] opened 2022-09-30 18:23 UTC
### Description

When editing text in an Entry field, if you attempt to move the cursor to a non-end-of-line position the application will crash. Additionally pasting text in to the Entry field will cause a crash with the same stack trace. This bug appears to be unique to iOS 16, reproducing in iOS 15 does not produce the same crash. 

The stack trace is included below.

### Steps to Reproduce

1. Create a New .Net Maui App targeting .NET 6
2. Add a simple `Entry` field like: `<Entry x:Name="TextEntry" Text="Test Value" /> `
3. Launch the App on an iOS 16 device or and iOS 16 emulator
4. Touch, hold, and drag in the Entry field to move the cursor (or equivalent in Emulator i.e. left arrow from end of line)
_Alternatively_
4. Paste value into Entry field.

### Link to public reproduction project repository

https://github.com/stanger/iOSMauiTextCursorBug

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 16 (on device and emulator)

### Relevant log output

```shell
Objective-C exception thrown.  Name: NSInvalidArgumentException Reason: -[<_UIObscurableTextContentStorage: 0x6000035ec870> offsetFromLocation:toLocation:] received invalid locations 0 (null)
Native stack trace:
	0   CoreFoundation                      0x00000001131d5378 __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00000001231bbbaf objc_exception_throw + 48
	2   CoreFoundation                      0x00000001131d5256 -[NSException initWithCoder:] + 0
	3   UIFoundation                        0x0000000127eb3608 -[NSTextContentStorage offsetFromLocation:toLocation:] + 287
	4   UIKitCore                           0x000000012e403434 -[_UITextKit2LayoutController offsetFromPosition:toPosition:] + 234
	5   UIKitCore                           0x000000012ee34b18 -[UITextInputController offsetFromPosition:toPosition:] + 85
	6   UIKitCore                           0x000000012ee03de9 -[UIFieldEditor offsetFromPosition:toPosition:] + 93
	7   UIKitCore                           0x000000012ee1f6bc -[UITextField offsetFromPosition:toPosition:] + 93
	8   libxamarin-dotnet-debug.dylib       0x00000001105aa4cc xamarin_dyn_objc_msgSendSuper + 220
	9   TextSelectionTest                   0x000000010fb20727 interp_to_native_trampoline + 167
	10  libmonosgen-2.0.dylib               0x0000000110d81f62 ves_pinvoke_method + 482
	11  libmonosgen-2.0.dylib               0x0000000110d73fb4 interp_exec_method + 3284
	12  libmonosgen-2.0.dylib               0x0000000110d720ff interp_runtime_invoke + 239
	13  libmonosgen-2.0.dylib               0x0000000110c69d3b mono_jit_runtime_invoke + 1227
	14  libmonosgen-2.0.dylib               0x0000000110b8c328 mono_runtime_invoke_checked + 136
	15  libmonosgen-2.0.dylib               0x0000000110b9018e mono_runtime_invoke + 142
	16  libxamarin-dotnet-debug.dylib       0x00000001105a0fe0 xamarin_invoke_trampoline + 6320
	17  libxamarin-dotnet-debug.dylib       0x00000001105a9049 xamarin_arch_trampoline + 105
	18  libxamarin-dotnet-debug.dylib       0x00000001105aa22e xamarin_x86_64_common_trampoline + 118
	19  UIKitCore                           0x000000012edcddd1 -[UITextSelection commit] + 243
	20  UIKitCore                           0x000000012edc14e9 -[UITextInteractionAssistant(UITextInteractionAssistant_Internal) _updateSelectionInViewIfNeeded:toRange:] + 435
	21  UIKitCore                           0x000000012edc3105 -[UITextInteractionAssistant(UITextInteractionAssistant_Internal) scheduleReplacementsForRange:withOptions:] + 319
	22  UIKitCore                           0x000000012ed92b04 -[UITextSelectionInteraction tappedToPositionCursorWithGesture:atPoint:granularity:completionHandler:] + 580
	23  UIKitCore                           0x000000012ed92793 -[UITextSelectionInteraction _checkForRepeatedTap:gestureLocationOut:] + 1277
	24  UIKitCore                           0x000000012ed93235 -[UITextSelectionInteraction _handleMultiTapGesture:] + 1123
	25  UIKitCore                           0x000000012ea51abf -[UIApplication sendAction:to:from:forEvent:] + 95
	26  UIKitCore                           0x000000012e3895f6 -[UITextMultiTapRecognizer onStateUpdate:] + 169
	27  UIKitCore                           0x000000012e459d0e -[UIGestureRecognizerTarget _sendActionWithGestureRecognizer:] + 72
	28  UIKitCore                           0x000000012e4636e0 _UIGestureRecognizerSendTargetActions + 100
	29  UIKitCore                           0x000000012e4604fe _UIGestureRecognizerSendActions + 303
	30  UIKitCore                           0x000000012e45f8ba -[UIGestureRecognizer _updateGestureForActiveEvents] + 633
	31  UIKitCore                           0x000000012e44e508 _UIGestureEnvironmentUpdate + 3840
	32  UIKitCore                           0x000000012e44d1ae -[UIGestureEnvironment _updateForEvent:window:] + 844
	33  UIKitCore                           0x000000012ea98d53 -[UIWindow sendEvent:] + 5282
	34  UIKitCore                           0x000000012ea6c526 -[UIApplication sendEvent:] + 898
	35  UIKitCore                           0x000000012eb13444 __dispatchPreprocessedEventFromEventQueue + 9383
	36  UIKitCore                           0x000000012eb15b61 __processEventQueue + 8355
	37  UIKitCore                           0x000000012eb0bfc4 __eventFetcherSourceCallback + 272
	38  CoreFoundation                      0x0000000113134ebd __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	39  CoreFoundation                      0x0000000113134dfc __CFRunLoopDoSource0 + 157
	40  CoreFoundation                      0x00000001131345f9 __CFRunLoopDoSources0 + 212
	41  CoreFoundation                      0x000000011312edb3 __CFRunLoopRun + 927
	42  CoreFoundation                      0x000000011312e637 CFRunLoopRunSpecific + 560
	43  GraphicsServices                    0x000000012637e28a GSEventRunModal + 139
	44  UIKitCore                           0x000000012ea4b425 -[UIApplication _run] + 994
	45  UIKitCore                           0x000000012ea50301 UIApplicationMain + 123
	46  libmonosgen-2.0.dylib               0x0000000110d82c42 do_icall + 194
	47  libmonosgen-2.0.dylib               0x0000000110d81c5d do_icall_wrapper + 253
	48  libmonosgen-2.0.dylib               0x0000000110d73e7a interp_exec_method + 2970
	49  libmonosgen-2.0.dylib               0x0000000110d720ff interp_runtime_invoke + 239
	50  libmonosgen-2.0.dylib               0x0000000110c69d3b mono_jit_runtime_invoke + 1227
	51  libmonosgen-2.0.dylib               0x0000000110b8c328 mono_runtime_invoke_checked + 136
	52  libmonosgen-2.0.dylib               0x0000000110b930cb mono_runtime_exec_main_checked + 107
	53  libmonosgen-2.0.dylib               0x0000000110ccc1e2 mono_jit_exec + 354
	54  libxamarin-dotnet-debug.dylib       0x00000001105a8e9d xamarin_main + 1949
	55  TextSelectionTest                   0x000000010fbd5744 main + 52
	56  dyld                                0x00000001102422bf start_sim + 10
	57  ???                                 0x000000011b4cb52e 0x0 + 4752979246
```

**Comment by fabEps** [comment] 2022-10-01 15:48
I can reproduce this too... this is really annoying, I planned our release on Monday (postponed already 4 weeks), now these iOS 16 bugs come in, and I have to work now the 3rd weekend in a row for free to fix MAUI bugs since no customer could understand what happens here. How can this be titled as "ready for production" with 1700+ bugs? Sorry, but it's getting hard to stay objective, this is so disappointing. 
Does anyone have a workaround for this?

**Comment by drasticactions** [comment] 2022-10-03 04:44
I think this is a duplicate of https://github.com/dotnet/maui/issues/10194.

**Closed by drasticactions** 2022-10-03 04:44 UTC
Labels: t/bug
