### ISSUE TITLE
Text drawing has lot of bugs in android

### ISSUE THREAD

**Issue by Ali-YousefiTelori** [dotnet/maui#8043] opened 2022-06-15 10:04 UTC
### Description

In the windows machine you can see the image everything works fine:
![image](https://user-images.githubusercontent.com/5262218/173799729-ecb9a89e-7f58-41a2-9768-6d107698961e.png)
![image](https://user-images.githubusercontent.com/5262218/173799798-56bbe780-c9ac-4851-80e1-d187b99d3477.png)
![image](https://user-images.githubusercontent.com/5262218/173799838-7608b3c5-e2c2-4fd8-a1a7-0660618bd28b.png)

But in the android app everything has wrong drawing:
![image](https://user-images.githubusercontent.com/5262218/173800676-50c43f89-d16b-4af3-871a-9c83769b0968.png)
![image](https://user-images.githubusercontent.com/5262218/173800696-cc8d4ec8-a778-4f5b-897a-489f297baa49.png)
![image](https://user-images.githubusercontent.com/5262218/173800710-e4e5f61c-b01d-431f-9f08-913c678ee4a2.png)

### Steps to Reproduce

clone the source from GitHub and run UI.
1. clone from https://github.com/Ali-YousefiTelori/WordProjectTranslators
2. run UI source from here:
https://github.com/Ali-YousefiTelori/WordProjectTranslators/tree/master/src/UI/Translators

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 9.0

**Comment by jfversluis** [comment] 2022-06-15 12:56
I think this is a duplicate of #8028

**Closed by jfversluis** 2022-06-15 12:56 UTC
Labels: t/bug, s/needs-verification
