### ISSUE TITLE
Use of FlyoutHeaderBehavior="CollapseOnScroll" causes an exceptio

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#9699] opened 2022-08-26 22:42 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Use-of-FlyoutHeaderBehaviorCollapseOnS/10125922)._

---
I compiled and ran the following app on Windows 11 :
[https://github.com/dotnet/maui-samples/tree/main/6.0/Fundamentals/Shell]
I selected the flyout menu. The hamburger icon cant be seen because the icon is white on a white background. Click where it should be, the flyout menu will appear. The flyout menu has a scroll bar. Try to scroll down and you will get an exception. I am including a screen capture. If you edit the Xaminals code, specifically AppShell.xaml. Remove the line "FlyoutHeaderBehavior="CollapseOnScroll" and repeat the previous steps, it will work as expected.

---
#### Feedback Bot on 8/22/2022, 01:58 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by jsuarezruiz** [comment] 2022-09-02 10:33
Could we get an attached sample where reproduce the exception?
![issue-9699](https://user-images.githubusercontent.com/6755973/188121333-354f4cbb-5a57-4c63-bc3f-0e6a617b45d5.gif)
Cannot reproduce it.

**Comment by jsuarezruiz** [comment] 2022-09-08 18:27
> Could we get an attached sample where reproduce the exception? ![issue-9699](https://user-images.githubusercontent.com/6755973/188121333-354f4cbb-5a57-4c63-bc3f-0e6a617b45d5.gif) [ ![issue-9699](https://user-images.githubusercontent.com/6755973/188121333-354f4cbb-5a57-4c63-bc3f-0e6a617b45d5.gif) ](https://user-images.githubusercontent.com/6755973/188121333-354f4cbb-5a57-4c63-bc3f-0e6a617b45d5.gif) [ ](https://user-images.githubusercontent.com/6755973/188121333-354f4cbb-5a57-4c63-bc3f-0e6a617b45d5.gif) Cannot reproduce it.

Reproduced, and will be fixed by https://github.com/dotnet/maui/pull/9962

**Closed** 2022-09-29 00:37 UTC
Labels: t/bug, platform/windows 🪟, area/shell 🐢, high
