### ISSUE TITLE
[Android] [Regression] NavigationPage.TitleView with ScrollView causes: (1) crashes, and (2) blank pages with stuck ToolbarItems

### ISSUE THREAD

**Issue by mfeingol** [dotnet/maui#13185] opened 2023-02-08 00:33 UTC
### Description

I'm using this issue to report two related but distinct bugs that appear when one uses a NavigationPage.TitleView with a horizontal ScrollView.

Scenario: MainPage inside NavigationPage -> Page1 -> Page2. If Page1 contains a TitleView, then:

1. Going back from Page2 to Page1 using the top left NavigationPage button succeeds, but Page1 will suddenly and unexpectedly be blank. Further, the ToolbarItems at the top of the screen will be stuck with Page1's ToolbarItems even when going back to the MainPage.

2. Going back from Page2 to Page1 programmatically (by calling `INavigation.PopAsync()`) results in the following unhandled exception:

```
Java.Lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
   at Java.Interop.JniEnvironment.InstanceMethods.CallNonvirtualVoidMethod(JniObjectReference instance, JniObjectReference type, JniMethodInfo method, JniArgumentValue* args) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/obj/Release/net7.0/JniEnvironment.g.cs:line 12324
   at Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeVirtualVoidMethod(String encodedMember, IJavaPeerable self, JniArgumentValue* parameters) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods_Invoke.cs:line 75
   at Android.Views.ViewGroup.AddView(View child) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net7.0/android-33/mcw/Android.Views.ViewGroup.cs:line 1999
   at Microsoft.Maui.Handlers.ScrollViewHandler.InsertInsetView(IScrollViewHandler handler, IScrollView scrollView, View nativeContent) in D:\a\_work\1\s\src\Core\src\Handlers\ScrollView\ScrollViewHandler.Android.cs:line 205
   at Microsoft.Maui.Handlers.ScrollViewHandler.UpdateInsetView(IScrollView scrollView, IScrollViewHandler handler) in D:\a\_work\1\s\src\Core\src\Handlers\ScrollView\ScrollViewHandler.Android.cs:line 187
   at Microsoft.Maui.Handlers.ScrollViewHandler.MapContent(IScrollViewHandler handler, IScrollView scrollView) in D:\a\_work\1\s\src\Core\src\Handlers\ScrollView\ScrollViewHandler.Android.cs:line 109
   at Microsoft.Maui.PropertyMapper`2.<>c__DisplayClass5_0[[Microsoft.Maui.IScrollView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Handlers.IScrollViewHandler, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<Add>b__0(IElementHandler h, IElement v) in D:\a\_work\1\s\src\Core\src\PropertyMapper.cs:line 172
   at Microsoft.Maui.PropertyMapper.UpdatePropertyCore(String key, IElementHandler viewHandler, IElement virtualView) in D:\a\_work\1\s\src\Core\src\PropertyMapper.cs:line 47
   at Microsoft.Maui.PropertyMapper.UpdateProperties(IElementHandler viewHandler, IElement virtualView) in D:\a\_work\1\s\src\Core\src\PropertyMapper.cs:line 82
   at Microsoft.Maui.Handlers.ElementHandler.SetVirtualView(IElement view) in D:\a\_work\1\s\src\Core\src\Handlers\Element\ElementHandler.cs:line 79
   at Microsoft.Maui.Handlers.ViewHandler.SetVirtualView(IElement element) in D:\a\_work\1\s\src\Core\src\Handlers\View\ViewHandler.cs:line 129
   at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.IScrollView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Platform.MauiScrollView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].SetVirtualView(IView view) in D:\a\_work\1\s\src\Core\src\Handlers\View\ViewHandlerOfT.cs:line 53
   at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.IScrollView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Platform.MauiScrollView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].SetVirtualView(IElement view) in D:\a\_work\1\s\src\Core\src\Handlers\View\ViewHandlerOfT.cs:line 56
   at Microsoft.Maui.Controls.Element.SetHandler(IElementHandler newHandler) in D:\a\_work\1\s\src\Controls\src\Core\HandlerImpl\Element\Element.Impl.cs:line 69
   at Microsoft.Maui.Controls.Element.set_Handler(IElementHandler value) in D:\a\_work\1\s\src\Controls\src\Core\HandlerImpl\Element\Element.Impl.cs:line 19
   at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IElement.set_Handler(IElementHandler value) in D:\a\_work\1\s\src\Controls\src\Core\HandlerImpl\VisualElement\VisualElement.Impl.cs:line 308
   at Microsoft.Maui.Platform.ElementExtensions.ToHandler(IElement view, IMauiContext context) in D:\a\_work\1\s\src\Core\src\Platform\ElementExtensions.cs:line 96
   at Microsoft.Maui.Platform.ElementExtensions.ToPlatform(IElement view, IMauiContext context) in D:\a\_work\1\s\src\Core\src\Platform\ElementExtensions.cs:line 127
   at Microsoft.Maui.Controls.Toolbar.UpdateTitleView() in D:\a\_work\1\s\src\Controls\src\Core\HandlerImpl\Toolbar\Toolbar.Android.cs:line 104
   at Microsoft.Maui.Controls.Toolbar.MapTitleView(IToolbarHandler arg1, Toolbar arg2) in D:\a\_work\1\s\src\Controls\src\Core\HandlerImpl\Toolbar\Toolbar.Android.cs:line 184
   at Microsoft.Maui.Controls.Toolbar.MapTitleView(ToolbarHandler arg1, Toolbar arg2) in D:\a\_work\1\s\src\Controls\src\Core\HandlerImpl\Toolbar\Toolbar.Android.cs:line 139
   at Microsoft.Maui.PropertyMapper`2.<>c__DisplayClass5_0[[Microsoft.Maui.Controls.Toolbar, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Handlers.ToolbarHandler, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<Add>b__0(IElementHandler h, IElement v) in D:\a\_work\1\s\src\Core\src\PropertyMapper.cs:line 172
   at Microsoft.Maui.PropertyMapper.UpdatePropertyCore(String key, IElementHandler viewHandler, IElement virtualView) in D:\a\_work\1\s\src\Core\src\PropertyMapper.cs:line 47
   at Microsoft.Maui.PropertyMapper.UpdateProperty(IElementHandler viewHandler, IElement virtualView, String property) in D:\a\_work\1\s\src\Core\src\PropertyMapper.cs:line 72
   at Microsoft.Maui.Handlers.ElementHandler.UpdateValue(String property) in D:\a\_work\1\s\src\Core\src\Handlers\Element\ElementHandler.cs:line 87
   at Microsoft.Maui.Controls.Toolbar.SetProperty[VisualElement](VisualElement& backingStore, VisualElement value, String propertyName) in D:\a\_work\1\s\src\Controls\src\Core\Toolbar.cs:line 77
   at Microsoft.Maui.Controls.NavigationPageToolbar.set_TitleView(VisualElement value) in D:\a\_work\1\s\src\Controls\src\Core\NavigationPageToolbar.cs:line 25
   at Microsoft.Maui.Controls.NavigationPageToolbar.ApplyChanges(NavigationPage navigationPage) in D:\a\_work\1\s\src\Controls\src\Core\NavigationPageToolbar.cs:line 241
   at Microsoft.Maui.Controls.NavigationPageToolbar.OnPageAppearing(Object sender, EventArgs e) in D:\a\_work\1\s\src\Controls\src\Core\NavigationPageToolbar.cs:line 90
   at Microsoft.Maui.Controls.MenuItemTracker`1[[Microsoft.Maui.Controls.ToolbarItem, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].OnPageAppearing(Object sender, EventArgs e) in D:\a\_work\1\s\src\Controls\src\Core\MenuItemTracker.cs:line 172
   at Microsoft.Maui.Controls.Page.SendAppearing() in D:\a\_work\1\s\src\Controls\src\Core\Page.cs:line 494
   at Microsoft.Maui.Controls.NavigationPage.OnCurrentPageChanged(BindableObject bindable, Object oldValue, Object newValue) in D:\a\_work\1\s\src\Controls\src\Core\HandlerImpl\NavigationPage\NavigationPage.Impl.cs:line 105
   at Microsoft.Maui.Controls.BindableObject.SetValueActual(BindableProperty property, BindablePropertyContext context, Object value, Boolean currentlyApplying, SetValueFlags attributes, Boolean silent) in D:\a\_work\1\s\src\Controls\src\Core\BindableObject.cs:line 535
   at Microsoft.Maui.Controls.BindableObject.SetValueCore(BindableProperty property, Object value, SetValueFlags attributes, SetValuePrivateFlags privateAttributes) in D:\a\_work\1\s\src\Controls\src\Core\BindableObject.cs:line 469
   at Microsoft.Maui.Controls.BindableObject.SetValue(BindableProperty property, Object value, Boolean fromStyle, Boolean checkAccess) in D:\a\_work\1\s\src\Controls\src\Core\BindableObject.cs:line 391
   at Microsoft.Maui.Controls.BindableObject.SetValue(BindablePropertyKey propertyKey, Object value) in D:\a\_work\1\s\src\Controls\src\Core\BindableObject.cs:line 373
   at Microsoft.Maui.Controls.NavigationPage.set_CurrentPage(Page value) in D:\a\_work\1\s\src\Controls\src\Core\NavigationPage.cs:line 140
   at Microsoft.Maui.Controls.NavigationPage.MauiNavigationImpl.<>c__DisplayClass7_0.<OnPopAsync>b__0() in D:\a\_work\1\s\src\Controls\src\Core\HandlerImpl\NavigationPage\NavigationPage.Impl.cs:line 320
   at Microsoft.Maui.Controls.NavigationPage.SendHandlerUpdateAsync(Boolean animated, Action processStackChanges, Action firePostNavigatingEvents, Action fireNavigatedEvents) in D:\a\_work\1\s\src\Controls\src\Core\HandlerImpl\NavigationPage\NavigationPage.Impl.cs:line 169
   at Microsoft.Maui.Controls.NavigationPage.MauiNavigationImpl.OnPopAsync(Boolean animated) in D:\a\_work\1\s\src\Controls\src\Core\HandlerImpl\NavigationPage\NavigationPage.Impl.cs:line 316
   at NavigationPageRepro.Page2.OnCounterClicked(Object sender, EventArgs e) in C:\Users\mfeingol\source\repos\NavigationPageRepro\NavigationPageRepro\Page2.xaml.cs:line 18
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Android.App.SyncContext.<>c__DisplayClass2_0.<Post>b__0() in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.App/SyncContext.cs:line 36
   at Java.Lang.Thread.RunnableImplementor.Run() in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Java.Lang/Thread.cs:line 36
   at Java.Lang.IRunnableInvoker.n_Run(IntPtr jnienv, IntPtr native__this) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net7.0/android-33/mcw/Java.Lang.IRunnable.cs:line 84
   at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V(_JniMarshal_PP_V callback, IntPtr jnienv, IntPtr klazz) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:line 22
  --- End of managed Java.Lang.IllegalStateException stack trace ---
```

### Steps to Reproduce

See above.

### Link to public reproduction project repository

https://github.com/mfeingol/repros/tree/master/NavigationPageRepro

### Version with bug

7.0 (current)

### Last version that worked well

7.0 (current)

### Affected platforms

Android

### Affected platform versions

11 and 13

### Did you find any workaround?

Remove the ScrollView from the TitleView and everything works. Unfortunately, in my real app a ScrollView is needed.

**Comment by PureWeen** [comment] 2023-02-08 22:51
@mfeingol do you know what version of 7.0 this was working for you in?

**Comment by mfeingol** [comment] 2023-02-08 22:58
@PureWeen: apologies; I filled the form out incorrectly. There is no version I'm aware of in which this worked.

**Comment by PureWeen** [comment] 2023-02-09 19:17
Duplicate of #13185

**Comment by mfeingol** [comment] 2023-02-09 19:20
@PureWeen: you just marked this issue as a duplicate of itself. Can you please clarify? Thanks.

**Comment by acaliaro** [comment] 2023-02-09 19:22
> @PureWeen: you just marked this issue as a duplicate of itself. Can you please clarify? Thanks.

an infinite loop

**Comment by jsuarezruiz** [comment] 2023-02-09 19:33
Should be a mistake with the duplicated reference here, reopen the issue for now.

**Comment by rmarinho** [comment] 2023-03-27 22:15
this should be fixed on net8. just tried on main and works fine.

**Closed by rmarinho** 2023-03-27 22:15 UTC
Labels: t/bug, platform/android 🤖, area/navigation 🧭, layout-scrollview
