### ISSUE TITLE
Splash screen is displayed incorrectly in dark mode

### ISSUE THREAD

**Issue by intellimedhu** [dotnet/maui#19775] opened 2024-01-09 08:56 UTC
### Description

The splash screen is displayed incorrectly on a physical device(Android),
if the device is set to dark mode. 

![IMG_20240109_092619](https://github.com/dotnet/maui/assets/65296389/a76e62f7-a2b2-43f0-9a7d-91bf6687c499)

### Steps to Reproduce

1. Create new MAUI application
2. Install on physical device (Android)
3. Set device mode to dark
4. Run application on physical device (Android)
5. Splash screen is displayed incorrectly

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 13 and up

### Did you find any workaround?

No

**Comment by PureWeen** [comment] 2024-01-09 19:24
@intellimedhu does it work correctly on versions older than Android 13? 
Just confirming if you tested that scenario

**Comment by intellimedhu** [comment] 2024-01-10 07:26
I don't know, I only tested with android 13 and 14.

**Comment by xarlammm** [comment] 2024-07-12 14:20
Hello! I'm joining you. Android 14 has this problem. iOS works well

**Comment by mycroes** [comment] 2024-11-06 20:44
> [@intellimedhu](https://github.com/intellimedhu) does it work correctly on versions older than Android 13? Just confirming if you tested that scenario

This issue doesn't happen on the emulated Pixel 5 with Android 14, so I'm not sure if it's related to the Android version. In my case it happens on a Xiaomi Android 14 device, #23018 also happens to be on a Xiaomi device (but with Android 13, according to the screenshots).

**Comment by jfversluis** [comment] 2024-11-08 14:38
Duplicate of #25693

**Closed by jfversluis** 2024-11-08 14:38 UTC
Labels: t/bug, area-single-project, platform/android 🤖, version/android-13

**Comment by mycroes** [comment] 2024-11-13 23:10
> If it is a Xiaomi problem, you might want to try and disable the forced dark mode: [#24837 (comment)](https://github.com/dotnet/maui/issues/24837#issuecomment-2367927718)

I've followed the steps outlined, but unfortunately the result is still the same. I've cleaned in VS and removed the app from my phone to be sure to have a freshly built version, but to no avail. I've now set both `<MauiSplashScreen Color="#..." />` and added `<item name="android:windowSplashScreenBackground">@color/background</item>` to `styles.xml`, however this doesn't work with white because the splash screen background will still be dark.

Would appreciate if this could be reopened, because this doesn't seem to be a dupe of the appointed issue and all issues that might be dupes have already been closed.
