### ISSUE TITLE
DEP0700 ERROR - Registration of the app failed. App manifest validation error...

### ISSUE THREAD

**Issue by DavorBeg** [dotnet/maui#19364] opened 2023-12-12 14:32 UTC
### Description

Hello, after I created new MAUI blazor hybrid project in .NET 8, I am not able to build and start the app.

### Steps to Reproduce

1. `Create a file > New .NET MAUI APP`
2. `Press start (F5) Button with Windows Machine.`
Visual studio give me this error:

```
DEP0700: Registration of the app failed. [0x80080204] error 0xC00CE169: App manifest validation error: The app manifest must be valid as per schema: Line 10, Column 13, Reason: 'com.companyname.nis_tt' violates pattern constraint of '[-.A-Za-z0-9]+'.
The attribute 'Name' with value 'com.companyname.nis_tt' failed to parse.		
```	

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.49

### Affected platforms

Windows

**Comment by mattleibow** [comment] 2023-12-12 20:23
As per the error message, the only accepted charactors are  those that match `[-.A-Za-z0-9]+`
- hyphen/dash `-`
- UPPERCASE letters
- lowercase letters
- numbers
- periods/dots `.`

You may have had a space in the filename, and this is converted into an underscore.

Duplicate of https://github.com/dotnet/maui/issues/19325

**Comment by mattleibow** [comment] 2023-12-12 20:24
However, I see this is an issue in our updated template processing. @jknaudt21 not sure when you did https://github.com/dotnet/maui/pull/18322 if you found that spaces created an underscore that failed to build on Windows?

**Comment by Eilon** [comment] 2023-12-12 20:53
@DavorBeg also just to check, does the same thing happen with a regular MAUI project (non-Blazor)?

**Comment by DavorBeg** [comment] 2023-12-12 20:55
@Eilon same issue. I just checked now.
@mattleibow 
`You may have had a space in the filename, and this is converted into an underscore.`
Now I tried with different name like `NISTT`, same issue..

I tried using .NET 7 and not 8, working without any error on start.

**Comment by mattleibow** [comment] 2023-12-12 20:57
What is your error messsage when you have no space in the filename? Can you attach a binlog of your build without a space?

**Comment by mattleibow** [comment] 2023-12-12 21:00
I believe for .NET 7 we always just used a GUID for Application ID which then would not work once you published your app.

**Comment by DavorBeg** [comment] 2023-12-12 21:03
Working now, I didnt turn on "developer mode" on my private PC. Must check on laptop tomorrow if it is same issue.
On laptop I used `NIS-TT` for project name. Will try also with `NISTT` and if everything is working I will close topic.
I think primary problem was naming of project!
Thank you for support!

**Comment by DavorBeg** [comment] 2023-12-13 08:34
Conclusion: 
1. On my laptop problem was naming `NIS-TT`
2. On my private PC problem was developer mode and naming.

Solution: 
Turned on developer mode and removed `-` from my naming.

Thank you all for support!

**Comment by Eilon** [comment] 2023-12-13 19:47
I think this is still supposed to work automatically because the 'invalid characters' should have been converted to valid characters or removed. So there _could_ still be a bug here that we should consider fixing.

I'm glad the workaround worked for you though!

**Comment by mattleibow** [comment] 2023-12-13 21:43
I am working on a fix here: https://github.com/dotnet/maui/pull/19377 Just writing the tests now as the fix is quite easy, but hopefully will be fixed very soon.

**Closed** 2024-01-23 18:44 UTC
Labels: t/bug, platform/windows 🪟, area/templates 📄, not-regression, potential-regression

**Comment by Ralms** [comment] 2024-02-22 00:48
This seems to still be affecting new projects, even with .NET 8.0.200 and VS 2022 17.9.1.

I've searched all the files where this ID or manifest is, but having no luck. 
Would it be possible to share how a manual fix could be? 

Thanks

**Comment by mattleibow** [comment] 2024-02-22 14:30
This could be in applicationid in the csproj.

What is the value that you have there?
