### ISSUE TITLE
Android setting Image.Source to null does not remove previous image. 

### ISSUE THREAD

**Issue by philipag** [dotnet/maui#10210] opened 2022-09-19 20:25 UTC
### Description

In the attached sample below you should see the image appearing and disappearing every 1 second.  However, under Android the image is always visible in spite of the fact that we set "image.Source = null" in code-behind.  This is a regression from XF. It appears that the image does not re-render itself when Source is nulled.

[layoutbug2.zip](https://github.com/dotnet/maui/files/9602135/layoutbug2.zip)

### Steps to Reproduce

1. Compile and run the sample on an Android emulator.
2. The Android robot image is visible all the time even when code-behind sets "image.Source = null" 
3. Running on iOS emulator no image shows at all even though it should.

### Link to public reproduction project repository

attachment

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

Android 12, iOS 15

### Did you find any workaround?

no

**Comment by janseris** [comment] 2022-09-20 09:08
https://github.com/dotnet/maui/issues/10165

**Comment by rachelkang** [comment] 2022-09-23 14:31
Closing, as it's a duplicate of #10165 as @janseris mentioned

**Closed by rachelkang** 2022-09-23 14:31 UTC
Labels: t/bug, area/image :framed_picture:

**Comment by samhouts** [comment] 2022-09-23 16:05
Duplicate of #10165
