### ISSUE TITLE
[Android] SplashScreen Scalingproblem

### ISSUE THREAD

**Issue by deepx** [dotnet/maui#7768] opened 2022-06-05 10:14 UTC
### Description

If you do a Blank Maui-App on Android Emulator (even on Local Device) the Splashscreen looks as it is not scaled correctly.
This is Emulator with API 21 - Android 5.0
![api_21](https://user-images.githubusercontent.com/3179474/172045616-117fd2db-eedc-4415-b45f-d8d15e8f868b.png)
This is the Emulator with API 28 - Android 9.0
![api_28](https://user-images.githubusercontent.com/3179474/172045618-0d4b8424-09b9-4e29-91ce-d0d7f3bdc502.png)

I dont know if this is a Bug, but maybe someone can take a look over that :-) 

### Steps to Reproduce

1.) Create a new Maui-App
2.) Start Emulator using API21 
3.) Just run
4.) Compare to Android-Emulator using API28 or later

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

API21, API28

### Did you find any workaround?

Found no Workaround

**Comment by kristinx0211** [comment] 2022-06-06 03:20
verified repro on API21 with 17.3.0 Preview 3.0 [32604.83.main].

**Comment by mattleibow** [comment] 2022-08-31 03:45
Duplicate of #5676

**Closed by mattleibow** 2022-08-31 03:45 UTC
Labels: t/bug, area/single project ☝️, platform/android 🤖, s/verified
