### ISSUE TITLE
[iOS] Shell Back Button Label 

### ISSUE THREAD

**Issue by ThatJammyDodger** [dotnet/maui#8335] opened 2022-06-26 20:47 UTC
### Description

When using navigation pages with Shell-based navigation on an iOS .NET MAUI app, the back button label will set itself to the same as the page title if the title is short enough, otherwise it will do the expected behaviours (when page title is longer) and have a label of 'Back' (see images below).

I do not believe that this is intended behaviour as that would not make much sense. I should also add that this does not happen on Windows or on an Android emulator (12.0 - API 31), but I was unable to test the behaviour on MacCatalyst.

### Steps to Reproduce

1. Create a new dotnet MAUI project.
2. Create the MainPage and another page, e.g. DemoPage, and register pages and routes on AppShell.xaml.cs
3. Insert a button with command `Shell.Current.GoToAsync(nameof(DemoPage));` on the MainPage
4. Run the app on an iOS iPhone 15.5 simulator with Hot Reload enabled.
5. Navigate to DemoPage
6. Edit the title parameter in ContentPage there by making it longer and shorter to see the back button's unexpected behaviors on simulator live.

Alternatively clone [this repo](https://github.com/ThatJammyDodger/iOSNav) (https://github.com/ThatJammyDodger/iOSNav) and run it in iOS simulator, using the buttons to see what happens.

**Results:**
<img width="491" alt="Short" src="https://user-images.githubusercontent.com/91419873/175833047-8e3bfac0-07d9-429e-86bc-a23f3c5f8e4e.png">
<img width="466" alt="Long" src="https://user-images.githubusercontent.com/91419873/175833048-707d0414-4ae2-41bc-a67d-52767fa8a17f.png">

Dotnet version: 6.0.400-preview.22301.10

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15.5

### Did you find any workaround?
https://github.com/PureWeen/ShanedlerSamples/blob/main/ShanedlerSamples/Library/Workarounds/ShellWorkarounds.iOS.cs
Edit: Yes, see comment below

**Comment by warpedgeoid** [comment] 2022-06-27 18:53
I'm sorry, but how is setting the back button text to "Back" when the page title is too long a bug? This would seem to be the expected behavior. Are you asking for this behavior to be added to non-iOS platforms?

**Comment by ThatJammyDodger** [comment] 2022-06-27 19:37
> I'm sorry, but how is setting the back button text to "Back" when the page title is too long a bug? This would seem to be the expected behavior. Are you asking for this behavior to be added to non-iOS platforms?

No, that is not the problem. So that it is more clear to you, I have made a screen recording.
The first page's title is 'The Main Page', not 'Short', therefore what I have shown in this recording and the screenshots above demonstrates the wrong behaviour.

https://user-images.githubusercontent.com/91419873/176021457-71d040a8-1ad0-4fa2-b109-a4f65a7a7631.mov

**Comment by kristinx0211** [comment] 2022-06-28 09:25
verified repro on IOS with above project.

**Comment by JamesRoche** [comment] 2022-07-03 14:54
This is a real issue for me too. Is there a workaround?

**Comment by EthanHipps** [comment] 2022-07-05 17:26
Also experiencing this issue in my own project

**Comment by ThatJammyDodger** [comment] 2022-07-16 18:06
Found workaround: in the code behind for the affected page(s), add this in the constructor:

`Shell.SetBackButtonBehavior(this, new BackButtonBehavior()
		{
			TextOverride = "Back",
		});`

You can also add any icons or stuff like that you want to override if you want to but this text override works for now as I have tested. Let me know if not.

**Comment by AdamBebko** [comment] 2022-10-09 04:26
I am also experiencing this issue

![Screen Shot 2022-10-09 at 12 26 44 AM](https://user-images.githubusercontent.com/43276915/194738052-5ec5f1ee-6fb7-4593-bf75-6d03e3f4f8d3.png)

**Comment by derek-willis** [comment] 2022-10-12 22:29
How do these fundamental things get released, app looks and feels unprofessional. Using Shell, there is a big delay in page titles changing too, really bad!

**Comment by 3steve3** [comment] 2022-11-28 01:32
This is seems like one of those issues that should be fixed by now, but it's still present in the .Net 7 version.

**Comment by jamesmontemagno** [comment] 2022-12-07 23:56
@PureWeen  I thought that we could set `NavigationPage.BackButtonTitle=“Back"` for example on the page? No? could this be applied to shell if not?

**Comment by PureWeen** [comment] 2022-12-08 17:03
@jamesmontemagno The `NP` attached properties don't currently propagate to shell, they should, but they don't :-/ 

I need to dig a little deeper on this one. The long/short string is interesting and feels like an iOS "feature" 

The delay is an issue with timing. The `Title` is propagated after `ViewDidAppear` opposed to `WillAppear`

**Comment by jamesmontemagno** [comment] 2022-12-08 22:01
Yeah... it is a weird one because only iOS actually has back button text, so I feel like it could be an actual Property on the Page itself.... I guess you could set the title before you navigate, but that feels odd.

**Comment by PureWeen** [comment] 2022-12-08 22:17
> Yeah... it is a weird one because only iOS actually has back button text, so I feel like it could be an actual Property on the Page itself.... I guess you could set the title before you navigate, but that feels odd.

If I'm remembering this all correctly the other weird thing here :-/ is that the `NP.BackButtonTitle` behavior is different than the `Shell.BackButtonBehavior.Title` behavior

`NP.BackbuttonTitle` has to be set on the previous page whereas `Shell.BackButtonBehavior.Title` you set on the current page.

**Comment by jamesmontemagno** [comment] 2022-12-08 22:58
Yeah... very interesting....

I really like that this will set it on the current page, it makes sense
```xml

    <Shell.BackButtonBehavior>
        <BackButtonBehavior TextOverride="Back"/>
    </Shell.BackButtonBehavior>
```

However if I set "Back" here then it gets rid of the < chev. Ideally I would set it to:
```xml

    <Shell.BackButtonBehavior>
        <BackButtonBehavior TextOverride=""/>
    </Shell.BackButtonBehavior>
```

This is what I used to use for NavigationPage stuff for NP.BackButtonTitle.

I think ideally the behavior works as it does today which is a complete override of the entire back button that you can do anything with, but then a new **ios:Shell.BackButtonText=""** maybe is introduced right? hmmmm

**Comment by vhugogarcia** [comment] 2022-12-09 00:05
> Shell.SetBackButtonBehavior(this, new BackButtonBehavior() { TextOverride = "Back", });

Thanks @jamesmontemagno and @PureWeen for looking into. I'm right now developing a new app in MAUI using App Shell and I'm facing this exact issue. 

I am also experiencing the big delay in page titles changing too on iOS, also I'm blocked since I cannot set a custom font family to the Shell Title label.

If there is anything else I can help by sharing code or anything, let me know.

Thanks in advance :)

**Comment by jamesmontemagno** [comment] 2022-12-09 19:14
Seems like a workaround here would be:
```xml
    protected override void OnNavigatingFrom(NavigatingFromEventArgs args)
    {
        base.OnNavigatingFrom(args);
        Title = string.Empty;
    }

    protected override void OnAppearing()
    {
        base.OnAppearing();
        Title = "this is a long title";
    }
```

there is a bit of pop in, but allows you to set things up.

**Comment by vhugogarcia** [comment] 2022-12-13 23:24
> @vhugogarcia is the issue with this:
> 
> ```
>  <Shell.TitleView>
>         <Label Text="Custom Font"
>                FontFamily="OpenSansSemibold"
>                TextColor="White"
>                HorizontalOptions="Center"
>                FontSize="18"/>
>     </Shell.TitleView>
> ```
> 
> this should work... i dont' see it coming up on iOS for some reason @PureWeen is that another issue?

That is correct @jamesmontemagno . If I set the custom font as you just shared it on iOS and macOS the title is not being rendered at all. It worked on Android from my tests.

**Comment by HobDev** [comment] 2022-12-20 19:09
I am facing this issue on iOS only when Navigating from ContentView and not when navigating from Content Page. When Navigating from ContentPage the target page don't have any back text.

**Comment by ThatJammyDodger** [comment] 2023-01-19 20:26
I reckon this has probably been fixed by #12363 which fixed #11691 which is basically this bug.

**Comment by SurkusGH** [comment] 2023-01-22 06:49
> I reckon this has probably been fixed by #12363 which fixed #11691 which is basically this bug.

Is there a way to implement this now? Or Į must wait for a release?

**Comment by gclap** [comment] 2023-01-26 12:39
This problem is very easy to reproduce using the Xanimals sample, https://github.com/dotnet/maui-samples/tree/main/6.0/Fundamentals/Shell/Xaminals. The navigation and customisation of the backbutton in shell seems broken and very much not production ready.

**Comment by Visual-IT-2021** [comment] 2023-02-09 16:49
I have the same problem (on iOS). 
If I use a short title (up to 14 characters without spaces - spaces probably don't take as much space as letters), the back text is the same as the page title. With a title longer than 14 characters the behavior is as expected and the back text is displayed correctly.
It does not make the Ui look very professional. Productive use is out of the question.

**Comment by PureWeen** [comment] 2023-02-16 17:56
I have a workaround renderer that I've put here

https://github.com/PureWeen/ShanedlerSamples/blob/main/ShanedlerSamples/Library/Workarounds/ShellWorkarounds.iOS.cs

Let me know if you hit any issues and I'll fix

**Closed** 2023-02-16 17:58 UTC
Labels: t/bug, area/navigation 🧭, platform/iOS 🍎, p/1, area/shell 🐢, s/verified, s/triaged
