### ISSUE TITLE
The DataTrigger in the CollectionView inside the Popup doesn't work correctly when scrolling

### ISSUE THREAD

**Issue by StephanArnas** [dotnet/maui#24655] opened 2024-09-08 14:41 UTC
### Description

I define a DataTrigger on a ContentView for a ItemTemplate on a CollectionView. 
My goal is to change the background color on the row where the SelectedItem is matching the value.

```cs
contentView.Triggers.Add(new DataTrigger(typeof(ContentView))
{
    Binding = new Binding("."),
    Value = SelectedItem,
    Setters =
    {
        new Setter
        {
            Property = VisualElement.BackgroundColorProperty,
            Value = ResourceHelper.GetThemeColor("PrimaryDark", "Primary")
        }
    }
});
```

![CleanShot 2024-09-08 at 16 25 59](https://github.com/user-attachments/assets/2dedca03-7287-479f-9cf1-5017182bc532)

When I select a value like United States, I open again the picker I can see United States is selected but if I scroll, many row will have a background. It's should not be possible with my Triggers.
If I scroll down very fast and I scroll up, I have more background appearing on my rows coming from nowhere. 

### Steps to Reproduce

1. Clone the project and restore it.
2. Uncomment the line 76-88 in CollectionPopup.xaml.cs file
3. Run the application on Android.
4. Go on the page 'Picker with popup demo'.
5. Open the Country picker and select United States.
6. Open again the Country picker, the United State is selected, but every items, matching the height size of the device is selected. 

### Link to public reproduction project repository

https://github.com/StephanArnas/Blog_MAUI_ComponentLibrary/tree/articles/part_4

### Version with bug

8.0.82 SR8.2

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

Android 14, iOS 15

### Did you find any workaround?

No workaround for now, I desactivate the trigger to not confuse my users.

**Comment by QianaJiao** [comment] 2024-09-09 05:00
This issue has been verified using latest Visual Studio 17.12.0 Preview 1.0 (8.0.82 &8.0.3), Can repro it on Android /iOS platforms.

**Comment by mattleibow** [comment] 2024-09-13 09:43
A simpler repro case:

```xaml

<CollectionView ItemsSource="{Binding Items}">
    <CollectionView.ItemTemplate>
        <DataTemplate>
            <ContentView>
                <ContentView.Triggers>
                    <DataTrigger TargetType="ContentView" Binding="{Binding .}" Value="Second">
                        <Setter Property="BackgroundColor" Value="LightBlue"/>
                    </DataTrigger>
                </ContentView.Triggers>
                <Label Text="{Binding .}" FontSize="20"/>
            </ContentView>
        </DataTemplate>
    </CollectionView.ItemTemplate>
</CollectionView>
```

[Archive.zip](https://github.com/user-attachments/files/16991983/Archive.zip)

**Comment by mattleibow** [comment] 2024-09-13 09:58
Duplicate of https://github.com/dotnet/maui/issues/22914

**Comment by mattleibow** [comment] 2024-09-13 10:00
@StephanArnas this is a duplicate of the other issue as everything is working from your code, except that for some cases, we are not removing the background of the unselected content view.

A workaround would be to set the Background of the content view to transparent - so the data trigger has a non-null value to return to. Right now, it is going from null to purple, and then back to null which has this issue. But transparent, purple, transparent is working fine.

**Closed by mattleibow** 2024-09-13 10:00 UTC
Labels: t/bug, platform/android 🤖, platform/iOS 🍎, area-controls-collectionview, s/verified, s/triaged
