### ISSUE TITLE
Better design time error handling on static resources

### ISSUE THREAD

**Issue by Yahya0007** [dotnet/maui#17377] opened 2023-09-14 15:45 UTC
### Description

a. If a static resource is not defined but is assigned to an element then it should give a design time error. 

b. If a static resource is defined with a target type then if it is assigned to an element of a different type then it should give a design time error. 

c. If a static resource is defined with properties that are not supported by the target type for the static resource then it should give a design time error. 

At present these issues are not coming up even in debug mode in either the iPhone simulator or the iPhone physical device. Only upon release publishing iOS app via TestFlight these issues crash the app which is a big waste of time to find the issue.

### Public API Changes

---

### Intended Use-Case

Speeds up debugging of faulty code.

**Comment by samhouts** [comment] 2023-09-14 17:45
Duplicate of #15602

**Closed by samhouts** 2023-09-14 17:45 UTC
Labels: proposal/open, area/Xaml </>
