### ISSUE TITLE
[Bug] Debug for Windows App Fails Deployment: Need recipe file

### ISSUE THREAD

**Issue by MichaelPeter** [dotnet/maui#2493] opened 2021-09-15 13:27 UTC
### Steps to Reproduce
1. Install the MSI Packaging Tools (https://marketplace.visualstudio.com/items?itemName=ProjectReunion.MicrosoftSingleProjectMSIXPackagingToolsDev17)
2. Create a new MAUI Project
3. Goto the configuration manager and activate Deploy since it is not activated by default

![grafik](https://user-images.githubusercontent.com/4217002/133441404-a7804bd2-33ac-487f-a6bf-f22e372b8e04.png)

4. Inline the Windows project type in the .csproj
5. Switch start configuration to Windows Maschine 

I also tried to install Project Reunion but did not fix the problem.

### Expected Behavior

The Windows App Starts

### Actual Behavior

A Error appears that Deployment Failed and the output only says Need recipe file

![grafik](https://user-images.githubusercontent.com/4217002/133440907-7ba4252a-e83b-4631-8f12-86ed47a5c71e.png)

### Basic Information

- Version with issue:
- Last known good version:
- IDE: VS 2022 Preview 4
- Platform Target Frameworks: 
 - Windows Maschine
- Affected Devices: Windows 10 PC

**Comment by MarcusKnuth** [comment] 2021-09-15 13:41
Got the same issue

**Comment by doggyde** [comment] 2021-09-15 13:44
Same issue here - tried everything, nothing worked so far

**Comment by MartyIX** [comment] 2021-09-15 13:52
I experience the same issue. Also I can see this in error log:

![image](https://user-images.githubusercontent.com/203266/133446085-04518b6c-c410-42ef-b810-d933ce838b87.png)

**Comment by markrendle** [comment] 2021-09-15 14:12
Oddly, if you comment out both the lines from the template and add a single `TargetFramework` element for Windows the Deploy works correctly.

```xml
<PropertyGroup>
    <TargetFramework>net6.0-windows10.0.19041</TargetFramework>
    <!-- <TargetFrameworks>net6.0-ios;net6.0-android;net6.0-maccatalyst</TargetFrameworks> -->
    <!-- <TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows')) and '$(MSBuildRuntimeType)' == 'Full'">$(TargetFrameworks);net6.0-windows10.0.19041</TargetFrameworks> -->
    <OutputType>Exe</OutputType>
    <RootNamespace>MauiArgh3</RootNamespace>
    <UseMaui>true</UseMaui>
    <SingleProject>true</SingleProject>
    <EnablePreviewMsixTooling>true</EnablePreviewMsixTooling>

    <!-- Display name -->
    <ApplicationTitle>MauiArgh3</ApplicationTitle>

    <!-- App Identifier -->
    <ApplicationId>com.companyname.MauiArgh3</ApplicationId>

    <!-- Versions -->
    <ApplicationVersion>1.0</ApplicationVersion>
    <AndroidVersionCode>1</AndroidVersionCode>

    <!-- Required for C# Hot Reload -->
    <UseInterpreter Condition="'$(Configuration)' == 'Debug'">True</UseInterpreter>
</PropertyGroup>
```

**Comment by MichaelPeter** [comment] 2021-09-15 14:18
@markrendle: Haha, first thought no, that is too weird, but could reproduce it, also works for me.

So maybe a bug in csproj processing?

**Comment by drasticactions** [comment] 2021-09-15 14:23
This is a bug in Visual Studio. While you have either Android or iOS selected as the device to deploy to, it still has "Windows Machine" (The WinUI project) internally selected and tries to deploy to it. Since the Framework is still net6-ios or net6-android, MAUI can't generate the needed recipe files for it to deploy, hence "Need recipe file". This can happen even if you have the windows TFM added as well.

If you select "Windows Machine" and then select the Android or iOS device again, it should fix itself. You can also remove the launchProfile.json in Settings as well.

**Comment by MichaelPeter** [comment] 2021-09-15 15:33
@drasticactions: Thanks for the answer, took me a bit to understand it so for others you need to select windows in two places.

![grafik](https://user-images.githubusercontent.com/4217002/133463789-89662428-cada-43d0-bc2e-f1a5fdfa7997.png)

Should I close this now, or when it is fixed in visual studio?

**Comment by 3DSX** [comment] 2021-09-15 20:00
Hello. I was going on with the same issue. The solution works, but in the examples templates, the EnablePreviewMsixTooling was removed, which keeps producing the "need receipt."

To fix that if it's case of anyone just add
`<EnablePreviewMsixTooling>true</EnablePreviewMsixTooling>`

in the first property group

**Comment by BillyMartin1964** [comment] 2021-09-23 12:21
My csproj didn't have net6 for windows, so I added it to target frameworks and everything works fine.

<TargetFrameworks>net6.0-ios;net6.0-android;net6.0-maccatalyst;net6.0-windows10.0.19041</TargetFrameworks>

**Comment by Rarisma** [comment] 2021-09-27 16:22
As @BillyMartin1964 said this works fine, just update the target frameworks in your csproj to this
`<TargetFrameworks>net6.0-ios;net6.0-android;net6.0-maccatalyst;net6.0-windows10.0.19041</TargetFrameworks>`

and make sure the framework is set to windows and it should work

**Comment by abhidotnet** [comment] 2021-10-14 00:30
Yes. I am facing it as well. I am using preview 5.0

**Comment by metalblade34** [comment] 2021-10-18 14:21
> Yes. I am facing it as well. I am using preview 5.0

You have to Edit project file and Uncomment this line
		<TargetFrameworks>net6.0-ios;net6.0-android;net6.0-maccatalyst1</TargetFrameworks>
		<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows')) and '$(MSBuildRuntimeType)' == 'Full'">$(TargetFrameworks);net6.0-windows10.0.19041</TargetFrameworks>

it's working for me (Dont forgot to activate Developper Mode)

**Comment by Redth** [comment] 2022-01-19 15:25
Could anyone please confirm if they are still able to reproduce this with the latest VS 17.1 Preview 2.0 or 3.0 and MAUI Preview 11 or Preview 12? 

We believe this is fixed.

**Comment by Eilon** [comment] 2022-02-10 23:49
Hi, we think this issue has been fixed in more recent previews of .NET MAUI and Visual Studio. Please try installing the latest preview per the instructions at https://docs.microsoft.com/dotnet/maui/get-started/installation. If you are still experiencing an issue, please file a new issue with updated details.

**Closed by Eilon** 2022-02-10 23:49 UTC
Labels: t/bug, area/tooling ⚙️, s/needs info ❓, area/setup 🪄
