### ISSUE TITLE
Month name is shown by computer region option not by computer language

### ISSUE THREAD

**Issue by dzuris** [dotnet/maui#14589] opened 2023-04-14 16:18 UTC
### Description

When I use `DateTime.Now.ToString("MMMM yyyy");` and I display result on page, it shows me month in my domestic language despite I have computer in english. Whole application is working good and is showing text resources in english and only this is in my domestic language (slovak). 

The language for this is taken probably from region and not from windows language. Which is not expected behavior. This makes inconsistency in application when some text is in windows language and this is by region. Date formats are not problem to be in slovak format but whole month names should be in computer language.

![image](https://user-images.githubusercontent.com/45236796/232098533-47ed70e4-3b14-4509-a088-2a682ee7c1c8.png)

![image](https://user-images.githubusercontent.com/45236796/232098741-66258d28-2f53-41ee-9969-7d39aadb78ff.png)

### Steps to Reproduce

Start reproduction app, change region on your computer and let computer language in something else. Then you should be able to see it.

### Link to public reproduction project repository

https://github.com/dzuris/BugMonthNameMaui.git

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Windows 11

### Did you find any workaround?

Change region in settings

**Comment by drasticactions** [comment] 2023-04-17 06:48
What happens if you make a default WinUI 3 template app, does it exhibit the same behavior?

My guess would be it has to do with the `Platform.appxmanifest`.

<img width="380" alt="スクリーンショット 2023-04-17 15 46 53" src="https://user-images.githubusercontent.com/898335/232405584-31fdbbaf-87ca-4e57-a124-9a7496e82bb8.png">

This is the MAUI and WinUI 3 default, and maybe that is causing the behavior you're seeing. If you write a WinUI 3 application and try using the formatting there, you may see the same behavior.

**Comment by dzuris** [comment] 2023-04-23 18:49
I am not really sure what you want to say with that, but still if the behavior is same when I use MAUI or when I use WinUI 3, the behavior is wrong, and in my opinion the month name should be translated by computer language and not by computer region

**Comment by Eilon** [comment] 2023-06-20 21:37
@dzuris you can pass in a specific culture when calling `DateTime.ToString()` like this:

```c#
var frenchFranceDateTimeString = DateTime.Now.ToString(new CultureInfo("fr-FR"));
```

Or you can tell it to generate an invariant formatting that is independent of any computer setting:

```c#
var invariantDateTimeString = DateTime.Now.ToString(CultureInfo.InvariantCulture);
```

And there are several other variations of this depending on what you want.

Does this help you find a solution?

**Comment by drasticactions** [comment] 2023-06-21 06:54
> I am not really sure what you want to say with that, but still if the behavior is same when I use MAUI or when I use WinUI 3, the behavior is wrong, and in my opinion the month name should be translated by computer language and not by computer region

If the issue is due to the default WinUI3 implementation, then it's something that would need to be addressed in WinUI, by addressing its default "Platform.appxmanifest" values, which MAUI shares.

**Closed** 2023-06-29 01:01 UTC
Labels: t/bug, s/needs-info, area/localization, s/no-recent-activity
