### ISSUE TITLE
Cannot swipe on Windows (mouse or touch)

### ISSUE THREAD

**Issue by sinsedrix** [dotnet/maui#16287] opened 2023-07-21 14:32 UTC
### Description

I built a test app with `SwipeView`s.
On WSA or Android emulator, they behave well.
On Windows it's meant to work with touch interaction but it still doesn't (cf [this issue](https://github.com/dotnet/maui/issues/6152)).

So for Windows, I tried workarounds with Tap, Drag and Click events to call the Open method of the SwipeView.
Tap and Drag events are triggered, but the Open method has no effect neither with mouse or touchscreen.
![SwipeTest](https://github.com/dotnet/maui/assets/596459/b3fa79c8-f546-445e-9ed8-a54ed2aac948)

### Steps to Reproduce

Run the Swipe project on Windows Machine.
Try each gesture on the provided lists.

Runtime: Microsoft.AspNetCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
SDK: 7.0.400-preview.23274.1 [C:\Program Files\dotnet\sdk]

### Link to public reproduction project repository

https://github.com/sinsedrix/MauiTests/tree/main/Swipe

### Version with bug

7.0.49

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10, Windows 11

### Did you find any workaround?

NA

### Relevant log output

```shell
NA
```

**Comment by mattleibow** [comment] 2023-07-21 14:54
I had a quick look and I see that the WinUI does not have a way to programmatically open a swipe view... And as you linked, neither does it support mouse.

Not the best news, but the official guidance we get is to use a context menu as well. If that happens, a user could swipe with touch or right-click with mouse.

**Comment by mattleibow** [comment] 2023-07-21 14:54
Duplicate of #6152

**Closed by mattleibow** 2023-07-21 14:54 UTC
Labels: t/bug

**Comment by sinsedrix** [comment] 2023-07-23 20:41
@mattleibow You have an explanation for the Open method (even if it's not satisfying).
What about the touch gesture on windows, it still doesn't work.
