### ISSUE TITLE
Dropdown menu on html select item not at correct position in Blazor

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#26007] opened 2024-11-21 02:12 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Dropdown-menu-on-html-select-item-not-at/10791249)._

---
I have a select html item in my Blazor hybrid app.
If I open the drop down menu before moving the window it displays at the correct position.
![Dropdown issue 1.jpg](https://aka.ms/dc/image?name=B94e2a1fdcccc410aa611d5104cc952c9638672567539057368_Dropdown_issue_1.jpg&tid=94e2a1fdcccc410aa611d5104cc952c9638672567539057368)
But if I move the window the dorp down is opened at a bad location
![Dropdown issue 2.jpg](https://aka.ms/dc/image?name=Be933822fac07403d803688f583e61a7f638672568309418918_Dropdown_issue_2.jpg&tid=e933822fac07403d803688f583e61a7f638672568309418918)

---
#### Feedback Bot on 11/15/2024, 00:52 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Bertrand Spitz on 11/16/2024, 03:00 AM: 

<p>I have update to the latest version of Visual Studio and to .NET 9 and the issue has gone.<br>
I don’t know which update solved the issue.</p>

**Comment by danroth27** [comment] 2024-11-25 18:08
@Eilon @BethMassi Is this due to https://github.com/MicrosoftEdge/WebView2Feedback/issues/2290? Did we do something in .NET 9 to workaround this issue?

**Comment by Eilon** [comment] 2024-11-25 18:09
@danroth27 yes same issue. It's all within WebView2, so closing this as dupe of https://github.com/MicrosoftEdge/WebView2Feedback/issues/2290. I'm not aware of anything that can be done aside from some workarounds mentioned in the linked issue (which might not always work).

**Closed by Eilon** 2024-11-25 18:09 UTC
Labels: area-blazor, external
