### ISSUE TITLE
Entry control with IsPassword="true" broken under Windows 

### ISSUE THREAD

**Issue by paratype-fonts** [dotnet/maui#6977] opened 2022-05-10 05:27 UTC
### Description

1. When an Entry control has IsPassword="true", the caret jumps back to the start position after each character entered.
2. The Text property of the control has the entered string reversed

### Steps to Reproduce

1. Use Visual Studio 2022 preview
2. Create a new project using the Maui template
3. Convert any Label on the page into Entry
4. Observe the issues presented in the Description section above 

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Visual Studio Community 2022 for Mac Preview Version 17.2.0 Preview 6.0(17.0 build 8754)

### Did you find any workaround?

No

**Comment by XamlTest** [comment] 2022-05-10 06:16
Verified this issue with Visual Studio Enterprise 17.3.0 Preview 1.0 [32427.455.main]. Repro on Windows. Sample Project: [6977.zip](https://github.com/dotnet/maui/files/8658706/6977.zip)

**Comment by christophbrunner** [comment] 2022-05-10 07:00
Duplicate of #5401

**Closed** 2022-05-12 05:50 UTC
Labels: t/bug, area/controls 🎮, s/verified, control-entry, s/triaged
