### ISSUE TITLE
[ANDROID] ScrollView not increasing in height when its child ListView or CollectionView are getting more items

### ISSUE THREAD

**Issue by DavidCarKc** [dotnet/maui#6959] opened 2022-05-09 16:42 UTC
### Description

At first it looked like scrolling isn't working any more, then I realised lager pages are scrolling fine, made some testing and realised height of ScrollView on Android is always the same as when the page is rendered first time. If you add more items into ListView or CollectionView they will push elements bellow them into invisibility.  Going to next page and returning back did not help.

### Steps to Reproduce

Microsoft Visual Studio Community 2022 (64-bit) - Preview
Version 17.2.0 Preview 6.0
create MauiCollectionViewTestV172P6 project
[MauiCollectionViewTestV172P6-scrollviewnotincreasingheightonandroid.zip](https://github.com/dotnet/maui/files/8653527/MauiCollectionViewTestV172P6-scrollviewnotincreasingheightonandroid.zip)

There are both CollectionView and ListView in XAML, uncomment the one you want to use. Buttons are added to make the page bigger than one screen to make it scrollable on first rendering. 
In c#  you can uncomment code to add 30 objects to either list or ObservableCollection
also different possibilites of populating the view are possible - just uncomment the one you want. 
await DisplayAlert("ScrollViewSize", ScrollView1.ContentSize.ToString(), "OK"); will display message with size of the scrollview after eack click. On WINDOWS he height option changes when new objects are displayed, on Android it always stays the same number.  
ALSO it won't decrease in size either try: add 30 objects by uncommenting code after InitializeComponent()
Change NextPage Button so it will delete all collection elements

```c#
private async void ClickedButtonNextPage(object sender, EventArgs e)
	{
		while (collection.Count > 0)
		{
			collection.RemoveAt(0);
		}
	}
```

On WINDOWS size will decrease but on ANDROID ScrollView height will remain large and there will be a large white area after the last element at the end of the page when you scroll down. 

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Tested on Android 5 and 9

**Comment by philipag** [comment] 2022-05-23 09:41
I have a similar issue still with RC3.  It seems the ScrollView's child does resize after initial sizing regardless of what is done (I tried Grid and ContentView).

For me this bug is a show stopper for porting from XF to MAUI.  I tried everything including manually settings the child size but nothing works.  I can change the child's size briefly but then it just returns to the original value.  Very strange.  Does anyone have a workaround?

**Comment by philipag** [comment] 2022-05-23 15:42
Here is another repro which shows the problem happening both with Android and iOS: "parent" never becomes larger than the ScrollView and therefore it is not possible to scroll the contents that are added.  So this is a bug with Android and iOS.

[layoutbug16.zip](https://github.com/dotnet/maui/files/8756033/layoutbug16.zip)

**Comment by kristinx0211** [comment] 2022-05-24 03:20
verified repro on android 12 with 17.3.0 Preview 2.0 [32522.62.main] using the [layoutbug16.zip](https://github.com/dotnet/maui/files/8756033/layoutbug16.zip)

**Comment by CobaltGoldCS** [comment] 2022-05-26 23:35
I'm having the same issue when manually updating the contents of the Scrollview in any way that changes their size. 

There are a few issues that seem to be addressing the same issue, such as #7374

**Comment by Realinspirer** [comment] 2022-06-04 18:56
Okay, after trying to figure out the problem in my app for about a whole day, I finally found this. Oh my, I am exhausted.
So, if I am right, this bug can be reproduced by `CollectionView `only (maybe also `ListView`). And not by other controls, right? But also - it happens only when items are added to them (so does that mean that adding other controls through code can also break the `ScrollView`?)
I have also discovered that you cannot put a `Collectioniew `inside a `StackLayout`, as it just 'expands' the `StackLayout`, thus making the `CollectionView` scroll 'bug' out, or something like that, but that is not considered a bug though.

So, I have got a little workaround. Okay, so you got yourself a `ScrollView` and now you put a `Grid` inside it. Just don't use a `StackLayout`, as it probably 'bugs' out the scroll behavior of `CollectionView`. You see, since this bug is caused only (or mostly, reply if I am wrong) by `CollectionView `or `ListView`, you can just add a height property to the control. Just add `HeightRequest=200` or something, and it will be fixed on place, but also note that `CollectionView` can be scrolled on its own, so all of the `CollectionView` items can be seen. And if you add more controls in the `Grid`, the `ScrollView` will take care of the scrolling of the rest of those controls.
Don't know if that's helpful or not, but somewhat helpful for me. I wish this bug gets patched quick.

**Comment by philipag** [comment] 2022-06-17 10:26
In the latest 6.400 preview ScrollView also no longer adjusts ScrollView.ContentSize when the content is resized (e.g. via HeightRequest or Arrange(rect)).

**Comment by jfversluis** [comment] 2022-07-06 11:39
Verified this is fixed in our current codebase. Should be released as part of the next service release. Thanks everyone for the help and input here!

**Closed by jfversluis** 2022-07-06 11:39 UTC
Labels: t/bug, area/layout 🔲, platform/android 🤖, s/verified
