### ISSUE TITLE
ResourceDictionary.ContainsKey method never returns true

### ISSUE THREAD

**Issue by tjbarrott** [dotnet/maui#13268] opened 2023-02-11 02:47 UTC
### Description

ResourceDictionary.ContainsKey method never returns true

### Steps to Reproduce

```
var mergedDictionaries = Application.Current.Resources.MergedDictionaries;
foreach(var dictionary in mergedDictionaries)
{
    foreach(var key in dictionary.Keys)
    {
        bool containsKey = dictionary.ContainsKey(key);
    }
}
```

`containsKey` is always false. I originally just tried `dictionary.ContainsKey("myKey")` and it always returned false, which led me to use the above code which should always return true.

                   

### Link to public reproduction project repository

https://github.com/tjbarrott/MergedDictionariesTest

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS, I was *not* able test on other platforms

### Affected platform versions

c# problem

### Did you find any workaround?

Yes. run through the keys in foreach loop and see if the key equals the string

**Comment by tjbarrott** [comment] 2023-02-14 01:34
https://github.com/tjbarrott/MergedDictionariesTest

I put the code in `MainPage.xaml.cs`

**Comment by hartez** [comment] 2023-02-14 20:22
This is happening because ResourceDictionary's `ContainsKey` method only checks the inner dictionary, and ignores the merged dictionaries: https://github.com/dotnet/maui/blob/main/src/Controls/src/Core/ResourceDictionary.cs#L179

The method needs to be updated, and the unit tests need to be updated to test for this.

**Comment by tjbarrott** [comment] 2023-02-24 23:10
> > Did you find any workaround?
> > Yes. run through the keys in foreach loop and see if the key equals the string
> 
> You could also use `if(dictionary.TryGetValue(key, out _))`

Unfortunately that did not work 100% of the time.
Maybe that is another bug.
It did return true when the key was in the set, but I had a situation where it returned true when the key was not in the set.

**Comment by hartez** [comment] 2023-02-25 00:57
> > You could also use `if(dictionary.TryGetValue(key, out _))`
> 
> Unfortunately that did not work 100% of the time. Maybe that is another bug. It did return true when the key was in the set, but I had a situation where it returned true when the key was not in the set.

When that happens, what's the value in the `out` parameter?

**Comment by tjbarrott** [comment] 2023-02-25 15:17
I figured out, it's not a bug. I get the value that is associated with the key out. The dictionary I am getting it from does not have the key, but it references the dictionary that does in `ResourceDictionary.MergedDictionaries`.

**Comment by Cybrosys** [comment] 2023-03-01 09:05
I just encountered this yesterday when writing some code to be able to change the colors based on user choice. My initial native approach was to do:
`Resources["Primary"] = <color>`

... which worked great as to just assign a color to a page's Resources dictionary which was completely empty. It obviously did not result in what I was expecting 🤣 

Long story short. Various methods and attempts led me to find `TryGetValue` and the list of merged resource dictionaries in `App.Current.Resources`.

What I quickly found out was that regardless of which instance I was working with, the method `ContainsKey` always returned `false`. Inspecting the `Keys` property I could clearly see that the value I was looking for was there, so I merely replaced all my `ContainsKey` calls with `Keys.Contains`.

I ended up with this extension method named "TryUpdateValue" following the "TryGetValue" method:
```
public static class ResourceDictionaryExtensions
{
    public static bool TryUpdateValue(this ResourceDictionary dictionary, string name, object value)
    {
        if (dictionary is null)
            return false;

        if (dictionary.Keys.Contains(name))
        {
            dictionary[name] = value;
            return true;
        }

        foreach (var mergedDictionary in dictionary.MergedDictionaries)
        {
            if (mergedDictionary.Keys.Contains(name))
            {
                mergedDictionary[name] = value;
                return true;
            }
        }

        return false;
    }
}
```

**Comment by hartez** [comment] 2023-03-02 19:04
Unfortunately, it turns out that the unexpected behavior of ResourceDictionary is required for Hot Reload to work. So we won't be modifying it, but we will update the documentation for `ContainsKey` to make it clear that it only looks at the immediate dictionary and ignores any merged dictionaries.

**Comment by Ghostbird** [comment] 2023-03-16 09:47
> Unfortunately, it turns out that the unexpected behavior of ResourceDictionary is required for Hot Reload to work. So we won't be modifying it, but we will update the documentation for `ContainsKey` to make it clear that it only looks at the immediate dictionary and ignores any merged dictionaries.

To me having the code break conventional interface contracts and common sense, because a _specific_ tool's functionality is dependent on it, is _extremely weird_. Shouldn't the hot reload functionality of .NET CLI Hot Reload be fixed to not rely on this wrong interface behaviour?
If it were up to me, I'd talk to those devs and tell them to fix it. If they refuse, I'd let it break, and let them deal with the consequences.

**Comment by Ghostbird** [comment] 2023-03-16 10:42
@Cybrosys How does that code work for you? This whole mechanism seems a terrible mess. If I try that, the dictionary now contains two identical keys, with different values:

```log
> x
{Microsoft.Maui.Controls.ResourceDictionary}
Count: 27
IsReadOnly: false
Keys: Count = 27
[0]: "Primary"
[1]: "Primary"
[2]: "Secondary"
[3]: "White"
…
> x.Keys.First()
"Primary"
> x.Keys.Skip(1).First()
"Primary"
> x.Keys.Skip(1).First() == x.Keys.First()
true
```

This is a _direct violation_ of the .NET `IDictionary` interface contract that `ResourceDictionary` claims to implement. If behaviour of implementations completely ignores the contracts it is built upon, what use is it to a developer? It would _quite literally_ be better if it didn't exist. It would be less work to write this yourself, than to have to figure out these obscure details, _then_ write it yourself.

**Comment by Ghostbird** [comment] 2023-03-16 12:24
@Cybrosys I guess I did something wrong when first trying your extension method. It's working now.

**Comment by Cybrosys** [comment] 2023-03-16 20:25
> @Cybrosys I guess I did something wrong when first trying your extension method. It's working now.

It was a quickly cobbled together method that achieved what I was trying to do when testing something. I wouldn't be surprised if there are some quirks or odd behaviors due to how ResourceDictionary behaves.

**Comment by jfversluis** [comment] 2023-04-06 11:39
Looking at the discussion and linked, closed PR, I think this is a variation of: https://github.com/dotnet/maui/pull/11214#issuecomment-1498922649

As such, closing this for now.

**Closed by jfversluis** 2023-04-06 11:39 UTC
Labels: t/bug, area/Xaml </>
