### ISSUE TITLE
Handles CoreWebView2.ProcessFailed in BlazorWebView

### ISSUE THREAD

**Issue by jairbubbles** [dotnet/maui#6481] opened 2022-04-25 13:00 UTC
### Description

Hi there,

We're using more and more `BlazorWebView` and we're seing more and more the exception:

```
The WebView control is no longer valid because the browser process crashed.To work around this, please listen for the CoreWebView2.ProcessFailed event to explicitly manage the lifetime of the WebView2 control in the event of a browser failure.https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.processfailed
```

Our application is also using the `WebView2` to display web pages and we did subscribe to the event by taking inspiration from
https://github.com/MicrosoftEdge/WebView2Feedback/blob/master/specs/ExtendedProcessFailed.md

However on the  `BlazorWebView`  we can't acces the internal  `WebView2` to subscribe to the event and even if we did I'm not sure we could react accordingly like reloading the view.

I would say it should be handled by the  `WebView2`  control.

### Public API Changes

none

### Intended Use-Case

make the control more robust

**Comment by Eilon** [comment] 2022-04-28 18:42
I believe that as of the most recent preview, this event is accessible. But, as you say, I'm not sure what meaningful thing can be done by handling this event unless it's BlazorWebView itself handling it, but I don't know exactly what you can do with it. Perhaps it's all that's needed for now?

**Comment by jairbubbles** [comment] 2022-04-30 15:56
@Eilon Oh yes you're right but there's not much you can do on the `WebView`.

**Comment by Eilon** [comment] 2022-05-02 16:04
BTW I've been playing around with this and I think we can make it work except for one thing: I hit some issue with disposing the BlazorWebView in an attempt to re-create it after process failure. I'm trying to see what that issue is. I think once we're past that issue, this can be handled entirely by an app.

**Comment by jairbubbles** [comment] 2022-05-02 16:18
Cool, but does it really need to be managed entirely by app?

It I take our personal example (on the vanillia `WebView`), it takes us some time to understand what to do with the `ProcessFailed` event. We ended up with something like that:
```csharp
private void WebViewOnProcessFailed(object sender, CoreWebView2ProcessFailedEventArgs e)
    {
        // Inspired from https://github.com/MicrosoftEdge/WebView2Feedback/blob/master/specs/ExtendedProcessFailed.md
        switch (e.ProcessFailedKind)
        {
            case CoreWebView2ProcessFailedKind.BrowserProcessExited:
                RecreateWebView();
                _notificationManager.ShowTopMessage("WebView exited unexpectedly. The control was automatically reloaded.");
                break;
            case CoreWebView2ProcessFailedKind.RenderProcessUnresponsive:
                RecreateWebView();
                _notificationManager.ShowTopMessage("WebView became unresponsive. The control was automatically reloaded.");
                break;
            case CoreWebView2ProcessFailedKind.RenderProcessExited:
            case CoreWebView2ProcessFailedKind.FrameRenderProcessExited:
                _webView.Reload();
                _notificationManager.ShowTopMessage("WebView exited unexpectedly. The page was automatically reloaded.");
                break;
        }

        void RecreateWebView()
        {
            var uri = _webView.Source;
            DestroyWebView();
            CreateWebView();
            _webView.Source = uri;
        }
    }
 ```

Appart from the ability to notify properly in the app the user, the logic for reloading / recreating seems universal. 
On a `BlazorWebView` I didn't know to recreate the web view so I stopped there and I felt like it wasn't my repsonsibility.

**Comment by Eilon** [comment] 2022-05-02 16:21
@jairbubbles I think the entire BlazorWebView needs to be re-created. I think it's an app decision how to handle it because if the WebView2 process crashes, there is no generic way to know what state the app was in and where to "resume" the app after trying to re-create the web view. So the pattern I was trying to do was similar to what you show in that code sample, but it re-creates the BlazorWebView instead of just the WebView2.

**Comment by Eilon** [comment] 2022-05-04 19:58
Here's how I was able to handle WebView2 ProcessFailed and recover from it:

I created a new default .NET MAUI Blazor app using the latest preview of Visual Studio.

I changed `MainPage.xaml` to a slightly different UI that doesn't have the BlazorWebView defined in the XAML source:

```xaml
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:local="clr-namespace:MauiBlazorApp3"
             x:Class="MauiBlazorApp3.MainPage"
             BackgroundColor="{DynamicResource PageBackgroundColor}">

    <Grid x:Name="MainLayout" RowDefinitions="Auto, *">
        <HorizontalStackLayout Grid.Row="0">
            <Label Text="Status:" />
            <Label x:Name="StatusLabel" Text="Unknown" />
            <Button Text="Reload BlazorWebView" Pressed="ReloadButtonPressed" />
        </HorizontalStackLayout>

    </Grid>

</ContentPage>
```

And I changed `MainPage.xaml.cs` to have a new method that makes sure there is a valid BlazorWebView on the page. It also has a label to show the WebView2 status (e.g. 'ready' or 'crashed'), and a button that re-creates the BlazorWebView. I used `#if WINDOWS` in several places because this code is specific to WebView2.

```c#
using Microsoft.AspNetCore.Components.WebView;
using Microsoft.AspNetCore.Components.WebView.Maui;

namespace MauiBlazorApp3;


public partial class MainPage : ContentPage
{
    private BlazorWebView _bwv;

    public MainPage()
    {
        InitializeComponent();

        CreateOrReplaceBlazorWebView();
    }

    private void CreateOrReplaceBlazorWebView()
    {
        // Fully destroy any existing BlazorWebView
        if (_bwv != null)
        {
            StatusLabel.Text = "Destroying old BlazorWebView";
            _bwv.BlazorWebViewInitialized -= OnBlazorWebViewInitialized;
            MainLayout.Children.Remove(_bwv);
        }

        StatusLabel.Text = "Creating new BlazorWebView";

        // Create a new BlazorWebView, initialize it, and add to the page
        _bwv = new BlazorWebView()
        {
            HostPage = "wwwroot/index.html",
        };
        _bwv.RootComponents.Add(new RootComponent
        {
            Selector = "#app",
            ComponentType = typeof(Main),
        });

        _bwv.BlazorWebViewInitialized += OnBlazorWebViewInitialized;

        MainLayout.Add(_bwv, row: 1);

        StatusLabel.Text = "BlazorWebView ready";
    }

    private void OnBlazorWebViewInitialized(object sender, BlazorWebViewInitializedEventArgs e)
    {
#if WINDOWS
        var webView2Control = e.WebView;
        webView2Control.CoreProcessFailed += WebView2_CoreProcessFailed;
#endif
    }

#if WINDOWS
    private void WebView2_CoreProcessFailed(Microsoft.UI.Xaml.Controls.WebView2 sender, Microsoft.Web.WebView2.Core.CoreWebView2ProcessFailedEventArgs args)
    {
        StatusLabel.Text = "WebView2 crashed! Reason: " + args.Reason;
    }
#endif

    private void ReloadButtonPressed(object sender, EventArgs e)
    {
        CreateOrReplaceBlazorWebView();
    }
}
```

When I first run the app, here's what it looks like:
![image](https://user-images.githubusercontent.com/202643/166814628-7d915cfa-a279-428d-bd56-6db858c25aee.png)

And then I went to Task Manager and killed various WebView2 processes:
![image](https://user-images.githubusercontent.com/202643/166814800-ca2ce59f-bf86-4729-ad11-1a8ee935d6a8.png)

Until eventually my app looks like this:
![image](https://user-images.githubusercontent.com/202643/166815129-7338b913-90b9-4ceb-b40f-1f740b7aabdf.png)

And then I press the **Reload BlazorWebView** button in the app and I get the app back:
![image](https://user-images.githubusercontent.com/202643/166815194-2d8d9422-ce94-49f6-9257-0e396d595b1e.png)

As far as application state goes: as long as the app's state is not _inside_ the WebView (which it shouldn't be), the app will see whatever services are registered in the app because it'll just be part of the UI that is reloading, whereas the app state is just some .NET objects in the app.

Of course, the exact manner in which an app wants to detect such failures and recover from it could vary significantly. It might do it automatically, it might wait a few seconds before trying. It might try a maximum of, say, 5 reloads, before giving up.

And as far as whether BlazorWebView should do this automatically: Right now I feel strongly that it should not be handled automatically. Components such as BlazorWebView are generally written with the assumption that "every other components in the world is perfect". Of course that isn't true, and there are certainly workarounds in many cases to work around _specific_ bugs or limitations. But this particular case is not any specific bug, but rather "an unknown issue happened for an unknown reason." I might even be tempted to make an even stronger suggestion that BlazorWebView _should_ handle this event, and throw its own exception to cause the outer app to fail! (Yeah not really, but why not?)

Anyway, I think that for right now there is enough functionality in BlazorWebView that enables apps to handle this scenario in a variety of ways, which is I think all we need for now. If we get significant feedback on this we can certainly revisit this in the future.

**Comment by jairbubbles** [comment] 2022-05-04 20:38
That's interesting!

You couldn't recreate the `WebView` so you're wrapping it in another one which is responsible of recreating the whole `BlazorWebView`.

As much as I agree that app should have control of the behavior, I feel like it's a lot plumbery to add and most importantly to guess by just looking at the error message:
```
The WebView control is no longer valid because the browser process crashed.To work around this, please listen for the CoreWebView2.ProcessFailed event to explicitly manage the lifetime of the WebView2 control in the event of a browser failure.https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.processfailed
```

I feel like:
- `BlazorWebView` should send its own event (that would wrap corewebview2.processfailed)
-  The error should link to a documentation that explains how to handle this properly in a `BlazorWebView` context

Anyway, thanks for investigating. I'll do the same technique.

**Comment by Eilon** [comment] 2022-05-04 21:39
The WebView is an internal implementation detail of the BlazorWebView. It's exposed only to enable some advanced scenarios such as modifying custom settings, or handling platform-specific events such as WebView2's ProcessFailed event. Other than that, apps don't generally get access to that implementation detail.

Exposing that event on BlazorWebView itself and offering some sort of behavioral options is worth considering, but I suspect it's unlikely to be a high priority. In general, if WebView2 crashes, I think it's always one of these root causes:

1. 99.98%: It's a bug in WebView2 itself. In this case a bug report should be submitted for WebView2 and that way it can get fixed in the future, thus avoiding the crash to begin with.
2. 0.01%: It's a bug in the app, such as some JavaScript/WASM code that's using too many resources, causing some instability in WebView2. Then it's a bug in the app itself and should be fixed.
3. 0.01%: It's a bug in BlazorWebView. Let us know and we'll try to get a fix out!

Now, even if one of these hopefully unlikely events happens, the manner of recovery is very app-dependent. When a single component in an app _crashes_, that means the app is now in a fundamentally undefined state (if it _was_ defined, then why did it crash??). Just restarting part of the app could lead to even further instability and crashes. As mentioned earlier, it could even lead to infinite loops of crashing: the app first loads, then later crashes, restart part of it, it immediately crashes again (due to the same bug probably), and does that forever, consuming tons of CPU and power. So, really, an app needs to decide if it's even worth handling this in any meaningful way at all, aside from reporting the defect via some system such as Application Insights, and then terminating the app. Or perhaps restarting the entire app (hopefully avoiding the infinite loop mentioned already). To restart only _part_ of the app in any non-trivial app requires an app architecture that support thats, and I don't think that's trivial.

One way or another, I think it's fine to keep this issue open and see how much people overall care about this. I'd wager most people don't even know about this yet! 😄

**Comment by Eilon** [comment] 2022-05-04 21:44
BTW also regarding this:

> I feel like it's a lot plumbery to add

I agree it's not entirely trivial, but I consider that it's not "a lot" in relation to how _rare_ I would expect this should be. That is, I think it's OK for rare things to be more complicated (and conversely, of course, common things should be easy!). I think for many apps, aside from their app architecture considerations to handle partial restarts (for which there's little we can do in the framework), the "boiler plate code" is on the order of ~20-30 lines as seen in my sample.

I think it's important to consider that this feature is about how to recover from a bug in a system component. Like, what should an app do if a random button in the app stops working? Really, you don't do anything. The user gets confused and restarts the app or computer. Hopefully they file a bug for you to repro and investigate. Now, WebViews are _far_, **far**, _**far**_ more complex than a mere button, hence this failure event exists on WebViews but not on the poor old Button control. But still hopefully it is rare that it would ever come into play.

**Comment by jairbubbles** [comment] 2022-05-05 06:32
> I agree it's not entirely trivial, but I consider that it's not "a lot" in relation to how rare I would expect this should be

It's hard for me to tell, we only migrated some views in our WPF application (and it's not enabled by default), so my gut feeling indicates me that we'll probably see it more and more. We love Blazor so much that we want to get rid of WPF in the long run.

Would there be a way to give more information why the `WebView2` crashed? Does Edge provide some logs/dumps that would be worth sending as attachements of the crash report? It's really hard to diagnose the issue righ now. The callstack gives no clue at all.

**Comment by mkArtakMSFT** [comment] 2022-11-03 17:32
Closing as there is too much app-specific logic to be included in any handler to help here.

**Closed by mkArtakMSFT** 2022-11-03 17:32 UTC
Labels: proposal/open, area/blazor 🕸️
