### ISSUE TITLE
Problem with MAX_PATH

### ISSUE THREAD

**Issue by Kebechet** [dotnet/maui#15042] opened 2023-05-11 22:05 UTC
### Description

I am on Windows and I build my iOS application through connected Mac M1 mini.

I have spotted an error on package [MauiMTAdmob](https://github.com/marcojak/MauiMTAdmob) that provides Google ads. It uses bindings around native libraries and the xcframework folder structure is quite deep.
The package name is [xamarin.firebase.ios.core](https://github.com/xamarin/GoogleApisForiOSComponents/releases) `v8.10.0.3`

When I want to build my app with this package and run in in iOS simulator it ends with error. Basically the content of this package cant be moved to the remote MAC. The cause is probably the long path but even after setting up
```
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem]
"LongPathsEnabled"=dword:00000001
```
in my registries, nothing changed.

I have googled possible workarounds and all of them just tries to shorten the final path. Either by specifying nuget folder to:
`C:\nuget\` by specifying environment variables `NUGET_PACKAGES` and `NUGET_PATH`, moving whole project closer to the root directory or other similar things.

Issues related to this problem:
- https://github.com/marcojak/MauiMTAdmob/issues/1#issuecomment-1208001881 by @jfversluis 
- https://github.com/marcojak/MauiMTAdmob/issues/5#issuecomment-1210526910
- https://github.com/xamarin/GoogleApisForiOSComponents/issues/555
- https://github.com/dotnet/maui/issues/10068
- https://stackoverflow.com/questions/72473203/how-to-resolve-xamarin-firebase-ios-core-8-10-0-1-nuget-installation-error

### Steps to Reproduce

Run on Windows and have connected remote MAC

1. restore all packages
2. connect to MAC
3. Press Run in simulator
4. Program fail with errors

### Link to public reproduction project repository

https://github.com/Kebechet/MauiPathProblem/commits/main

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

I was *not* able test on other platforms

### Affected platform versions

Windows 11 Pro - 10.0.22621

### Did you find any workaround?

No, none of mentioned workarounds worked for me

### Relevant log output

```shell
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.4.7054\targets\Xamarin.Shared.Sdk.targets(2014,3): error : MessagingRemoteException: An error occurred on client Build1647054 while executing a reply for topic xvs/build/16.4.7054/execute-task/PathMauiApp/8b5ca10002fGetFileSystemEntries

1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.4.7054\targets\Xamarin.Shared.Sdk.targets(2014,3): error : DirectoryNotFoundException: Could not find a part of the path '/Users/marcopoloooo/Library/Caches/Xamarin/mtbs/builds/PathMauiApp/8b5ca1011c9ff81f5d26fa18099764f025c8f0bc3da589484bd28c7653d3e937/C:/nuget/xamarin.firebase.ios.core/8.10.0.3/lib/net6.0-ios15.4/Firebase.Core.resources'.

1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.4.7054\targets\Xamarin.Shared.Sdk.targets(2014,3): error :

1>Done building project "PathMauiApp.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

**Comment by mattleibow** [comment] 2023-05-12 14:32
@rolfbjarne @dalexsoto thoughts?

**Comment by rolfbjarne** [comment] 2023-05-12 14:38
This is for XMA, CC @emaf

**Comment by scriptBoris** [comment] 2023-05-19 06:30
Need to find fix on maximum path length for Windows 11

**Comment by mattleibow** [comment] 2023-05-19 06:54
I do not think it is max path as this path is 220 and is an invalid path entirely:

> /Users/marcopoloooo/Library/Caches/Xamarin/mtbs/builds/PathMauiApp/8b5ca1011c9ff81f5d26fa18099764f025c8f0bc3da589484bd28c7653d3e937/C:/nuget/xamarin.firebase.ios.core/8.10.0.3/lib/net6.0-ios15.4/Firebase.Core.resources'

Take not of the `C:/` right in the middle of the path on mac - and the `:` means a path splitter. So this path is basically 2 paths in one. It is wrong in all forms of the error.

There is probably a bug in XMA or in the nuget targets file.

**Comment by scriptBoris** [comment] 2023-05-19 07:12
> I do not think it is max path as this path is 220 and is an invalid path entirely:
> 
> > /Users/marcopoloooo/Library/Caches/Xamarin/mtbs/builds/PathMauiApp/8b5ca1011c9ff81f5d26fa18099764f025c8f0bc3da589484bd28c7653d3e937/C:/nuget/xamarin.firebase.ios.core/8.10.0.3/lib/net6.0-ios15.4/Firebase.Core.resources'
> 
> Take not of the `C:/` right in the middle of the path on mac - and the `:` means a path splitter. So this path is basically 2 paths in one. It is wrong in all forms of the error.
> 
> There is probably a bug in XMA or in the nuget targets file.

![image](https://github.com/dotnet/maui/assets/29772096/85eaa8e3-1869-440f-8003-d587136e212c)

I don't think this is a problem since the test project runs just fine.
1. Folder C:\ and all dependencies are created
2. Folder C:\ is created, but folders with dependencies cannot be installed

**Comment by scriptBoris** [comment] 2023-05-19 16:24
> @scriptBoris @Kebechet Could you share a build binary log with us? You can get one using the [Project System Tools](https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.ProjectSystemTools2022) extension for Visual Studio. You can find more information about thow to use it [here](https://github.com/dotnet/project-system-tools#features). With this log we should be able to find out why the file was not copied over to the Mac.
> 
> Some comments about the path:
> 
> * The length should not be an issue because that path is built on macOS, so Windows should never hit that problem
> * `C:/` is valid, or at least 
it's something we've been using for a long time already

Take it
[TipTronicMaui_Debug_AnyCPU_Build_2023-05-19T22_21_25.4669383+06_00.zip](https://github.com/dotnet/maui/files/11518726/TipTronicMaui_Debug_AnyCPU_Build_2023-05-19T22_21_25.4669383%2B06_00.zip)

**Comment by scriptBoris** [comment] 2023-05-21 10:14
@emaf is there a solution to the problem?

**Comment by rolfbjarne** [comment] 2023-05-24 20:05
Can you try removing the SessionId property in your local file `Xamarin.Shared.Sdk.targets` file for the GetFileSystemEntries task and see if that works around the problem?

So remove this line:

https://github.com/rolfbjarne/xamarin-macios/blob/7e3297578111dedbf4f7041f8a40bc4285b49fd8/dotnet/targets/Xamarin.Shared.Sdk.targets#L1902

So that the task looks like this:

```xml
<GetFileSystemEntries
	DirectoryPath="@(_BindingPackagesFromReferencedAssembliesDirectoriesExists)"
	Pattern="*"
	Recursive="true"
	IncludeDirectories="false"
	>
	<Output TaskParameter="Entries" ItemName="_BindingPackagesFromReferencedAssemblies" />
</GetFileSystemEntries>
```

Note that you might have to restart Visual Studio for the change to take effect.

**Comment by rolfbjarne** [comment] 2023-05-25 17:13
Closing as duplicate of https://github.com/xamarin/xamarin-macios/issues/18308.

**Closed by rolfbjarne** 2023-05-25 17:13 UTC
Labels: t/bug, area/tooling ⚙️, partner/platform-tools
