### ISSUE TITLE
Soft Keyboard Input Mode doesn't work on .NET MAUI Blazor 8.0.3 (Android)

### ISSUE THREAD

**Issue by TommasoScalici** [dotnet/maui#19066] opened 2023-11-27 21:35 UTC
### Description

The keyboard always covers the view despite setting a different SoftInputMode, the property seems to be ignored.

![image](https://github.com/dotnet/maui/assets/6296587/6abcb31a-7b7e-4130-a4e1-d101fb699231)

### Steps to Reproduce

1) Create a new .NET MAUI Blazor project
2) Set WindowSoftInputModeAdjust to Pan or Resize via XAML android:Application.WindowSoftInputModeAdjust or via C# App.Current.On<Android>().UseWindowSoftInputModeAdjust([...])
3) Put lot of entry/input controls
4) When you focus an input control the keyboard covers all the controls and no resize/pan happens

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 14

### Did you find any workaround?

No workaround found.

**Comment by drasticactions** [comment] 2023-11-28 00:05
Duplicate of https://github.com/dotnet/maui/issues/18041

**Closed by drasticactions** 2023-11-28 00:05 UTC
Labels: t/bug
