### ISSUE TITLE
 IsPassword Property of Entry control does not work for the numeric keyboard when set dynamically.

### ISSUE THREAD

**Issue by VijayakumarViswanathan** [dotnet/maui#12332] opened 2022-12-29 09:29 UTC
### Description

The IsPassword Property of Entry control does not work for the numeric keyboard when set dynamically using the button click.

### Steps to Reproduce

1. Deploy the sample in the repository.
2. On the main page, an entry and a button were displayed.
3. Click the button to change the value of the IsPassword Property.
4. Visibility of the text/numbers in the entry was not changed. (issue).

### Link to public reproduction project repository

https://github.com/VijayakumarViswanathan/PasswordVisibilityIssueEntry

### Version with bug

6.0.486

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 9

**Comment by rachelkang** [comment] 2023-03-30 20:54
Duplicate of #10407

**Closed by rachelkang** 2023-03-30 20:54 UTC
Labels: t/bug, platform/android 🤖, area/controls 🎮, keyboard
