### ISSUE TITLE
.NET MAUI Blazor NavigationManager.Refresh() causes a flicker of a white page

### ISSUE THREAD

**Issue by mattleibow** [dotnet/maui#18993] opened 2023-11-23 18:57 UTC
### Description

While testing out Blazor things, I noticed that a `NavigationManager.Refresh()` works nicely in a browser, but on mobile it flashes white for half a second or so.

### Steps to Reproduce

1. File | New | Maui Hybrid App
2. Inject the navigation manager in the Counter.razor page: `@inject NavigationManager Nav`
3. In the click event, replace the increment with: `Nav.Refresh();`
4. Observe the flashing white page

### Link to public reproduction project repository

N/A

### Version with bug

8.0.3

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

**Comment by mattleibow** [comment] 2023-11-27 17:38
Hmm, why does hybrid not have enhanced nav then? Seems like it should?

**Comment by Eilon** [comment] 2023-11-27 23:57
Paging @SteveSandersonMS and @javiercn who I think know a lot more about enhanced navigation and what it would mean in Blazor Hybrid.

@mattleibow - can you share why the app is calling Refresh() to begin with? There could be other ways to get what you want without any refresh at all, such as by simply invalidating a component with `StateHasChanged()`.

**Comment by Eilon** [comment] 2023-12-12 21:06
Closing as by design because that Refresh API is designed to refresh the whole page, which most apps shouldn't need, and indeed could cause a white flash (or whatever color the default background of the control is).

**Closed by Eilon** 2023-12-12 21:06 UTC
Labels: t/bug, platform/windows 🪟, area/blazor 🕸️
