### ISSUE TITLE
FlyoutItem text disappears in Release mode, but not in Debug mode

### ISSUE THREAD

**Issue by DM-98** [dotnet/maui#16490] opened 2023-08-02 03:37 UTC
### Description

The issue is when you apply x:DataType="local:AppShell" in AppShell.xaml, the text in LayoutItem completely disappears when running in Release mode. Everything works fine in Debug mode.

The issue is also described in #14865. After many hours of testing due to having to test only in Release mode, I found the bug. 
It happens when you apply x:DataType="local:AppShell" on it.. Which is unfortunate since I'd like compiled bindings on it for improved data binding performance...

### Steps to Reproduce

1. Create a new .NET MAUI App
2. Open AppShell.xaml
3. Make a wrap the ShellContent with a Flyoutitem
4. Write <Shell x:DataType="local:AppShell" ...>
5. Run in Debug to see that the text is visible, and then run in Release, and it's invisible.

### Link to public reproduction project repository

https://github.com/shadowfoxish/Temp-CollectionViewFormattedStringSlowness

### Version with bug

8.0.0-preview.6.8686

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 13.0 - API 33

### Did you find any workaround?

To remove the x:DataType="local:AppShell" in <Shell...>, which is not a good workaround since we lose compiled databindings.

**Comment by rachelkang** [comment] 2023-08-02 18:26
Duplicate of #11956

**Closed by rachelkang** 2023-08-02 18:26 UTC
Labels: t/bug, area/controls 🎮, control-flyout

**Comment by mattleibow** [comment] 2023-08-02 18:34
Looking at your code, I see the `x:DataType="local:AppShell"` in `<Shell>`, but there is no data binding on that object so the binding context will never be `AppShell`.

**Comment by DM-98** [comment] 2023-08-02 19:57
> Looking at your code, I see the `x:DataType="local:AppShell"` in `<Shell>`, but there is no data binding on that object so the binding context will never be `AppShell`.

Doesn't matter, this is simply a reproduction repo. Either way, it will still bug out with the text disappearance in release (tested with our product at another private repo).
