### ISSUE TITLE
SVG extension Image does not work on ImageButton/Button

### ISSUE THREAD

**Issue by AllenMiaoFil** [dotnet/maui#7066] opened 2022-05-12 06:18 UTC
### Description

When I created a ImageButton or Button, set Source/ImageSource property with a svg extension like below:

`<Button ImageSource="button.svg"/>` 

The button would show nothing.  But it works on MacOS

### Steps to Reproduce

1. Create a maui project 
2. Add ImageButton or Button
3. Set Source or ImageSource with a svg extension image

### Version with bug

Release Candidate 2

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10

**Comment by jfversluis** [comment] 2022-05-12 09:00
As pointed out, did you try the png extension? Does that resolve the issue (for now)?

**Comment by AllenMiaoFil** [comment] 2022-05-12 09:25
> As pointed out, did you try the png extension? Does that resolve the issue (for now)?

@jfversluis Yes, I've tested with png, it works, only SVG on windows does not work. Actually we want to use svg opacity.  PNG is converted. it can't resolve issue

**Comment by mattleibow** [comment] 2022-05-14 04:16
> we want to use svg opacity

I am not sure what you mean by this? When the svg is converted to a png, the values in the svg are used on a transparent image.

Also, the svg is just a build input and never reaches the final app.

**Comment by AllenMiaoFil** [comment] 2022-05-16 01:50
@mattleibow I see, I just want to modify some properties of SVG based on different State in VSM, Not sure I can do that or not, for right now we use PNG instead SVG in windows as a work around and I modified button's Opacity, It would affect full button color. 
And another issue is SVG works on MacOS, but does not work on Windows.

**Comment by DeanFaizal** [comment] 2022-05-27 12:36
I can confirm svg works on Windows in GA using it as ".png"

**Comment by DeanFaizal** [comment] 2022-05-27 12:38
@AllenMiaoFil would you mind opening a new feature request for adding an ImageOpacity property to ImageButton? 

https://github.com/dotnet/maui/issues/new?assignees=&labels=proposal%2Fopen%2Ct%2Fenhancement&template=feature-request.yml

**Comment by AllenMiaoFil** [comment] 2022-05-30 00:59
https://github.com/dotnet/maui/issues/7597 link is the new feature for adding Opacity to ImageButton and Button.

**Comment by kristinx0211** [comment] 2022-06-21 08:22
@AllenMiaoFil So can this issue be closed? track with https://github.com/dotnet/maui/issues/7597?

**Comment by AllenMiaoFil** [comment] 2022-06-27 02:19
Hey @kristinx0211, I don't think they are same issue, https://github.com/dotnet/maui/issues/7597 is about button-opacity, And This is about SVG as a Source doesn't work on Button/Image Button, but it is working on Mac.

**Comment by richardlalancetteyoui** [comment] 2022-08-29 20:47
I hit the same issue. I had to remove the .svg extension to make it work.

**Comment by mattleibow** [comment] 2022-11-10 20:37
Just trying to recap the issue here...

The issue is that using `myimage.svg` does not work - even though you added that to your project. But, if you use `myimage.png` it does - and this is unexpected (and potentially confusing if you do not know the secrets of the inner workings of the build process).

Unless we are all missing something?

**Comment by jonathanpeppers** [comment] 2023-02-21 15:16
Closing this in favor of: https://github.com/dotnet/maui/issues/13368

We should create some kind of code analyzer that warns against the usage of `button.svg`. Upvote if this is important to you, thanks!

**Closed by jonathanpeppers** 2023-02-21 15:16 UTC
Labels: t/bug, platform/windows 🪟, area/image :framed_picture:, p/1, partner/cat 😻, s/triaged

**Comment by samhouts** [comment] 2023-03-02 01:04
Duplicate of #13368
