### ISSUE TITLE
NET MAUI iOS, the background color is always gray when the CollectionView is selected

### ISSUE THREAD

**Issue by pomeraniman** [dotnet/maui#11991] opened 2022-12-09 10:25 UTC
### Description

I am trying to create a UI like the image below.

[![android][1]][1]

As you can see, it works fine on Android, but when I run this on iOS, it shows a gray rectangle.

[![ios][2]][2]

How can I make this gray rectangle transparent?

  [1]: https://i.stack.imgur.com/qGAqK.png
  [2]: https://i.stack.imgur.com/NuWuT.png

### Steps to Reproduce

Here is the actual code.

```
<CollectionView SelectionMode="Single"
                HeightRequest="50"
                WidthRequest="250"
                ItemsLayout="HorizontalList"
                BackgroundColor="White">
    <CollectionView.ItemTemplate>
        <DataTemplate>
            <Border StrokeThickness="0"
                    WidthRequest="50"
                    HeightRequest="50"
                    StrokeShape="RoundRectangle 25">
                <Border StrokeThickness="0" BackgroundColor="Transparent">
                    <Label Text="{Binding}" HorizontalOptions="Center" VerticalOptions="Center"/>
                </Border>
                <VisualStateManager.VisualStateGroups>
                    <VisualStateGroup Name="CommonStates">
                        <VisualState Name="Normal"/>
                        <VisualState Name="Selected">
                            <VisualState.Setters>
                                <Setter Property="BackgroundColor" Value="yellow"/>
                            </VisualState.Setters>
                        </VisualState>
                    </VisualStateGroup>
                </VisualStateManager.VisualStateGroups>
            </Border>
        </DataTemplate>
    </CollectionView.ItemTemplate>

    <CollectionView.ItemsSource>
        <x:Array Type="{x:Type x:String}">
            <x:String>1</x:String>
            <x:String>2</x:String>
            <x:String>3</x:String>
            <x:String>4</x:String>
            <x:String>5</x:String>
        </x:Array>
    </CollectionView.ItemsSource>
</CollectionView>

```

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS16

**Comment by tsquillario** [comment] 2022-12-14 19:23
Experiencing same issue, just on iOS as well.

**Comment by stemper0123** [comment] 2022-12-16 10:15
Same problem as well

**Comment by himanshudwd765** [comment] 2023-01-31 14:05
Any update on this problem, I am still facing this issue.

**Comment by thaveeshakannangara** [comment] 2023-03-15 05:24
I recently faced this on android as well

**Comment by jinxinjuan** [comment] 2023-06-05 09:18
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 1.0. Can repro on iOS platform with sample project. [11991Test](https://microsoft-my.sharepoint.com/:u:/p/v-annajinjin/EehfLhFo0_FCpSq74aKnMkMBraaqx_Jo5QkffQIUxwLW7g)

**Comment by Axemasta** [comment] 2023-09-18 17:05
This behaviour can be reproduced in the maui controls sample project on the `SingleBoundSelectionPage`. The selected color should be blue but this background color appears across the whole cell:

![image](https://github.com/dotnet/maui/assets/33064621/b03a1079-5def-4129-afe3-5c46aed49ffe)

Diving into the implementation of `TemplatedCell`, I believe I've found the cause of this issue.

There is a check to see if the cell uses visual state manager, but also to see if its background color is set to the default Gray ([see code](https://github.com/dotnet/maui/blob/71b820612e6419cfae3665ce04bbd4be3084789c/src/Controls/src/Core/Handlers/Items/iOS/TemplatedCell.cs#L159)). This check always fails because of how the colors are being compared, using `==` or `NSObject.IsEqual` fails however comparing the RGBA values will confirm whether the colors match.

I don't know what the reason is for checking the default color, the answer will be in the forms codebase. Assuming that check is neccessary to prevent other bugs I'll update it to correctly check for the colors matching:

```csharp
bool ColorsMatch(UIColor a, UIColor b)
{
	a.GetRGBA(out nfloat aRed, out nfloat aGreen, out nfloat aBlue, out nfloat aAlpha);
	b.GetRGBA(out nfloat bRed, out nfloat bGreen, out nfloat bBlue, out nfloat bAlpha);

	var redMatches = aRed == bRed;
	var greenMatches = aGreen == bGreen;
	var blueMatches = aBlue == bBlue;
	var alphaMatches = aAlpha == bAlpha;

	return redMatches && greenMatches && blueMatches && alphaMatches;
}
```

Then updating the initial selected color check to use this new method:
```csharp
var backgroundColorIsDefault = ColorsMatch(SelectedBackgroundView.BackgroundColor, Maui.Platform.ColorExtensions.Gray);

var usingVsm = IsUsingVSMForSelectionColor(view);

if (backgroundColorIsDefault && usingVsm)
{
	SelectedBackgroundView = new UIView
	{
		BackgroundColor = UIColor.Clear
	};
}
```

I am testing this change out and will submit a PR because this is a trivial fix which has massive impact on the general usability of maui :)

**Closed** 2023-12-12 00:51 UTC
Labels: t/bug, platform/iOS 🍎, area/collectionview 📃, s/verified, s/triaged
