### ISSUE TITLE
Object.GetType returns Null

### ISSUE THREAD

**Issue by AndreasReitberger** [dotnet/maui#7401] opened 2022-05-22 07:54 UTC
### Description

I'm not sure if this is a bug in VS, my code or in .NET MAUI.
However, I always get `Null` when I use `GetType()` on an object.

![image](https://user-images.githubusercontent.com/2952443/169684710-6672afb1-ffbc-41ef-a08f-cd220cbbe9af.png)

Even the string object returns me Null.

```cs
string Test = "";
var t2 = Test.GetType();
```

### Steps to Reproduce

1. Create a string object
2. Call GetType()

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, I was *not* able test on other platforms

### Affected platform versions

15

### Did you find any workaround?

Not net

**Comment by jfversluis** [comment] 2022-05-23 07:29
This does work on Android or Windows correctly?

I think there have been some weird things with iOS debugging. This is definitely not something that is caused by .NET MAUI at least :) @dalexsoto ?

**Comment by AndreasReitberger** [comment] 2022-05-23 09:21
@jfversluis 
Thanks for your reply. Not yet, but I will do once I'm back on my computer.
I'll keep you posted.

**Comment by AndreasReitberger** [comment] 2022-05-23 14:27
@jfversluis 
Yes, Android works fine. Not tested on Windows, though, but I guess it will work there too.

![image](https://user-images.githubusercontent.com/2952443/169841945-7fb95117-1864-4c2c-9e59-02837bc15407.png)

**Comment by VincentBu** [comment] 2022-05-24 06:26
repro with vs main build(32523.339.main) on IOS. works fine on Windows and Android.

**Comment by beeradmoore** [comment] 2022-06-08 03:49
Can you output the variable to console with `System.Diagnostic.Debug.WriteLine( );` and see it as not null? If so it could be duplicate of #7009

**Comment by AndreasReitberger** [comment] 2022-06-10 11:15
@beeradmoore 
Yes, can confirm this. If I output the variable, it's accurate.

![image](https://user-images.githubusercontent.com/2952443/173053364-d52959c1-c9a5-4803-bfb7-8b7fd56d8fa8.png)

Type output is fine:
![image](https://user-images.githubusercontent.com/2952443/173053396-3f4625c8-f83f-41df-801a-bd148beb90d9.png)

**Comment by jfversluis** [comment] 2022-06-15 07:00
Duplicate of #7009

**Closed by jfversluis** 2022-06-15 07:00 UTC
Labels: t/bug, s/verified, s/needs-attention, partner/macios
