### ISSUE TITLE
[regression/8.0.0-preview.4.8333] [Android] Setting the background property of AppCompatEditText in a handler mapping does not work

### ISSUE THREAD

**Issue by matt-goldman** [dotnet/maui#18720] opened 2023-11-13 21:45 UTC
### Description

In a .NET MAUI project using the latest .NET 8 RC, setting the background property of a `AppCompatEditText` doesn't seem to work.

Using this code:

```csharp
Microsoft.Maui.Handlers.EntryHandler.Mapper.AppendToMapping("TestEntry", (handler, view) =>
{
    handler.PlatformView.Background = null;
    handler.PlatformView.SetBackgroundColor(Android.Graphics.Color.Pink);
    handler.PlatformView.SetTextColor(Android.Graphics.Color.Aqua);
});
```

Has the following results:

<img width="326" alt="image" src="https://github.com/dotnet/maui/assets/19944129/12436011-1d88-499c-af63-57ad9fe28e9e">

**❌ Figure: PlatformView background properties not applied, but other mappings are applied**

<img width="325" alt="image" src="https://github.com/dotnet/maui/assets/19944129/8c666b15-e1a0-4c05-903b-8a9d69a41288">

**✅ Figure: The same code in .NET 7**

Repro is linked below. Repo with working version in .NET 7: https://github.com/matt-goldman/Net7AndroidHandlers

### Steps to Reproduce

1. Create a .NET MAUI app in .NET 8
2. Create a handler mapping to set the background of the `PlatformView` for `Entry`
3. Add an `Entry` to your UI
4. Run the app, observe bug 🐞

### Link to public reproduction project repository

https://github.com/matt-goldman/Net8AndroidHandlers

### Version with bug

8.0.0-preview.4.8333

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.0-preview.3.8149

### Affected platforms

Android

### Affected platform versions

Android - all versions

### Did you find any workaround?

I could not find a workaround

**Comment by ieuangriffiths97** [comment] 2023-11-14 18:27
Came across the same issue just commenting to keep track of this issue.

**Comment by borrmann** [comment] 2023-11-15 00:48
also applies to Picker and Editors

**Comment by borrmann** [comment] 2023-11-15 00:49
anyone have a workaround?

**Comment by matt-goldman** [comment] 2023-11-15 00:51
@borrmann I expect the team will fix this pretty quickly as it will affect everyone. And probably the controls vendors too.

**Comment by XamlTest** [comment] 2023-11-16 07:26
Verified this on Visual Studio Enterprise 17.9.0 Preview 1. Repro on Android 14.0-API34(**8.0.3**), not repro on Android 14.0-API34(**7.0.101**) with below Project:
[Net8AndroidHandlers.zip](https://github.com/dotnet/maui/files/13373487/Net8AndroidHandlers.zip)

**Comment by vhugogarcia** [comment] 2023-11-24 17:37
Hello @matt-goldman , it appears this is not a .NET MAUI 8/7 issue.  On this [post](https://stackoverflow.com/questions/24677414/how-to-change-line-color-in-edittext) found in StackOverflow, the Android developers shared that to change the edit text line color we must use **BackgroundTint**, and we should not use **BackgroundColor**.

Honestly, I was like you, I have been using the background color to remove the line color on Android in .NET MAUI 7, but after reviewing I was able to remove the bottom line of the edit text on android in my .NET MAUI 8 projects, by using the following code line on my handler:
`handler.PlatformView.BackgroundTintList = Android.Content.Res.ColorStateList.ValueOf(Colors.Transparent.ToAndroid());`

I updated [my article](https://dev.to/vhugogarcia/remove-entry-and-picker-borders-in-net-maui-2pk2 ) on my blog, reflecting this change: So, based on the findings, I believe this **is not** a bug of .NET MAUI and instead we were setting wrong the code to hide the Entry form control border in Android. I just wanted to share my grain of salt @jsuarezruiz .

I hope this helps other developers!

Reference of the official Android documentation: https://developer.android.com/reference/androidx/core/view/TintableBackgroundView

Thanks in advance.

cc: @XamlTest @borrmann @ieuangriffiths97

**Comment by matt-goldman** [comment] 2023-11-24 19:33
Nice catch @vhugogarcia! Thanks for this, and the write-up too!

**Comment by vhugogarcia** [comment] 2023-11-25 13:25
> Nice catch @vhugogarcia! Thanks for this, and the write-up too!

Happy to help. Please feel free to close this issue if you believe it has been solved.

**Comment by matt-goldman** [comment] 2023-11-26 18:40
Do we know what changed between .NET 8 and .NET 7?

**Comment by vitalbit** [comment] 2023-11-28 07:07
@vhugogarcia, @matt-goldman 

I believe there is still **handler.PlatformView.Background** setter, that is required to be fixed. Meanwhile we have ability to remove line for entry with **Colors.Transparent** appraoch, we still not able to update Background with any native **Android.Graphics.Drawables.Drawable** in .NET8.

**Comment by samhouts** [comment] 2023-12-07 19:23
Hey friends! From reading the comments, it looks like this can be closed. Is there further action required from the MAUI team? Thanks!

**Comment by vitalbit** [comment] 2023-12-08 08:55
Hello @samhouts, 
I prepared sample to show that Background property of AppCompatEditText does not apply changes. In the project you can find **CustomEntryHandler.cs** which change Background to round violet border and usage of **CustomEntry.cs** in **MainPage.xaml**.

[https://github.com/vitalbit/AndroidEntryBackgroundChangeSample/](url)

_master_ branch - provides .NET 7 project, which works fine.
![Screenshot_1702025338](https://github.com/dotnet/maui/assets/5405827/11979a61-522b-455c-95b4-d92c1f1d610f)

_net8-migration_ branch - provides .NET 8 project, with background issue.
![Screenshot_1702025575](https://github.com/dotnet/maui/assets/5405827/c92c3e09-3dda-498f-9619-a4abb2a12319)

The workaround mentioned above provides possibility to remove underline for Android, meanwhile we still can not fully control Background natively for Android, that's why I believe this bug should still be in Open state.

**Comment by zh0018** [comment] 2024-01-30 02:57
I have tested it in version 8.06 and still have this issue

> Hello @samhouts, I prepared sample to show that Background property of AppCompatEditText does not apply changes. In the project you can find **CustomEntryHandler.cs** which change Background to round violet border and usage of **CustomEntry.cs** in **MainPage.xaml**.
> 
> https://github.com/vitalbit/AndroidEntryBackgroundChangeSample/
> 
> _master_ branch - provides .NET 7 project, which works fine. ![Screenshot_1702025338](https://private-user-images.githubusercontent.com/5405827/289015770-11979a61-522b-455c-95b4-d92c1f1d610f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1MjExNDUsIm5iZiI6MTcwNjUyMDg0NSwicGF0aCI6Ii81NDA1ODI3LzI4OTAxNTc3MC0xMTk3OWE2MS01MjJiLTQ1NWMtOTViNC1kOTJjMWYxZDYxMGYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjlUMDkzNDA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGI1YzY1NjkxYTQ0NzBlNDE3MGY3ZTYyY2NkMTNkZTA2YTQ4YmNlYTRjMGY2ZjE1YTYwYTI0MzllZTNmYTY2NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ._igEsAzuzsgOIhJZ4puIlB6ZHG7cxdf_p0gXphOvPAU)
> 
> _net8-migration_ branch - provides .NET 8 project, with background issue. ![Screenshot_1702025575](https://private-user-images.githubusercontent.com/5405827/289016894-c92c3e09-3dda-498f-9619-a4abb2a12319.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1MjExNDUsIm5iZiI6MTcwNjUyMDg0NSwicGF0aCI6Ii81NDA1ODI3LzI4OTAxNjg5NC1jOTJjM2UwOS0zZGRhLTQ5OGYtOTYxOS1hNGFiYjJhMTIzMTkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjlUMDkzNDA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDM4NThmOTEwZjFkOWE5Nzc4MGRmODg5Zjg0YWViMGU4NWY2MmE2YWE4NTFmNTBiZjQyNmVhODI0MDMzZjBmZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.eXZb04HC2gd0pvge3jo5G1pioExDAtXfuuzX7MIRXO8)
> 
> The workaround mentioned above provides possibility to remove underline for Android, meanwhile we still can not fully control Background natively for Android, that's why I believe this bug should still be in Open state.

**Comment by ALJASAC** [comment] 2024-02-11 01:52
I came here with the same issue, please this needs attention.

**Comment by ieuangriffiths97** [comment] 2024-02-28 11:41
Any update from the MAUI team on when this will be fixed? This is stopping me from using .NET 8 Android in production. .NET 7 end of life is in May.

**Comment by Kirill-Novozhilov** [comment] 2024-03-21 11:25
Are there any workarounds, on how to change the line color in EditTextand setting a background color in so that it works?

If set the BackgroundColor and set the BackgroundTintList in handler, then the whole view gets the color of the tintlist.

**Comment by samhouts** [comment] 2024-04-10 19:05
Confirmed that this regressed between 8.0.0-preview.3.8149 and 8.0.0-preview.4.8333. #12227 looks sus. A similar issue was resolved by https://github.com/dotnet/maui/pull/17778, but this particular issue is still outstanding as of 8.0.14.

**Comment by MPoels** [comment] 2024-04-11 08:21
Having the same problem. The workaround for android I used was to set a customhandler and in that customhandler set the BackgroundTintlist. Then make a customcontrol consisting of a Border component and embed the customEntry into that border so that you can customize your border in the customcontrol. Very frustrating because this involves a lot of code to write, why not fix that background stuff. 

```csharp
	public sealed partial class CustomEntryHandler : EntryHandler
	{
		protected override AppCompatEditText CreatePlatformView()
		{
			var native = base.CreatePlatformView();
			native.BackgroundTintList = Android.Content.Res.ColorStateList.ValueOf(Colors.Transparent.ToAndroid());
			return native;
		}
        }
```

**Comment by TimurVa** [comment] 2024-06-08 08:56
Still dont working at 8.0.40

**Comment by knasher** [comment] 2024-07-13 23:31
I can confirm this is still happening in 8.0.70

**Comment by mackayn** [comment] 2024-07-29 14:12
Just ran into this too, applying a gradient has no effect in the handler in Android.

```
 public class AndroidBorderedEntryHandler : EntryHandler
 {
     protected override AppCompatEditText CreatePlatformView()
     {
         var nativeView =  base.CreatePlatformView();
         if (VirtualView is BorderedEntry entry)
         {
             // Remove underline
             nativeView.BackgroundTintList = ColorStateList.ValueOf(Color.Transparent);

             GradientDrawable gd = new GradientDrawable();
             gd.SetCornerRadius(3);
             gd.SetStroke(1, entry.BorderColor.ToAndroid());
             nativeView.Background = gd;
             return nativeView;
         }
         return nativeView;
     }
 }
```

**Comment by tbaggett** [comment] 2024-08-03 17:52
+1

**Comment by mattleibow** [comment] 2024-08-19 14:14
This all looks very complicated with the append mapper and/or custom handler. It appears you want to replace the background? We have a feature for that since net6:

```cs
builder.ConfigureMauiHandlers(handlers =>
{
#if ANDROID
    EntryHandler.Mapper.ReplaceMapping<IEntry, IEntryHandler>("Background", (handler, view) =>
    {
        var platformView = handler.PlatformView;

        // Android will reset the padding when setting a Background drawable	
        // So we need to reapply the padding after
        var padLeft = platformView.PaddingLeft;
        var padTop = platformView.PaddingTop;
        var padRight = platformView.PaddingRight;
        var padBottom = platformView.PaddingBottom;

        // Set the custom background
        var gd = new Android.Graphics.Drawables.GradientDrawable();
        gd.SetCornerRadius(3);
        gd.SetStroke(1, Android.Graphics.Color.Red);
        gd.SetColor(Android.Graphics.Color.Pink);
        platformView.Background = gd;

        // Apply previous padding
        platformView.SetPadding(padLeft, padTop, padRight, padBottom);
    });
#endif
});
```

This results in:

![Screenshot_1724076838](https://github.com/user-attachments/assets/dc5c4681-a7d0-463d-b6f9-88bc09b5e8c6)

**Comment by pmahend1** [comment] 2024-08-19 15:32
Thank you! @mattleibow . This is really helpful.
Looks like we need more documentation on when to use AppendMapping and when to use ReplaceMapping.

**Comment by mackayn** [comment] 2024-08-19 15:49
> This all looks very complicated with the append mapper and/or custom handler. It appears you want to replace the background? We have a feature for that since net6:
> 
> ```cs
> builder.ConfigureMauiHandlers(handlers =>
> {
> #if ANDROID
>     EntryHandler.Mapper.ReplaceMapping<IEntry, IEntryHandler>("Background", (handler, view) =>
>     {
>         var platformView = handler.PlatformView;
> 
>         // Android will reset the padding when setting a Background drawable, so we need to reapply the padding after
>         var padLeft = platformView.PaddingLeft;
>         var padTop = platformView.PaddingTop;
>         var padRight = platformView.PaddingRight;
>         var padBottom = platformView.PaddingBottom;
> 
>         // Set the custom background
>         var gd = new Android.Graphics.Drawables.GradientDrawable();
>         gd.SetCornerRadius(3);
>         gd.SetStroke(1, Android.Graphics.Color.Red);
>         gd.SetColor(Android.Graphics.Color.Pink);
>         platformView.Background = gd;
> 
>         // Apply previous padding
>         platformView.SetPadding(padLeft, padTop, padRight, padBottom);
>     });
> #endif
> });
> ```
> 
> This results in:
> 
> ![Screenshot_1724076838](https://private-user-images.githubusercontent.com/1096616/359133099-dc5c4681-a7d0-463d-b6f9-88bc09b5e8c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwODIxODIsIm5iZiI6MTcyNDA4MTg4MiwicGF0aCI6Ii8xMDk2NjE2LzM1OTEzMzA5OS1kYzVjNDY4MS1hN2QwLTQ2M2QtYjZmOS04OGJjMDliNWU4YzYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTlUMTUzODAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDFjZDU0NGNiMmRiYjFiNmIyMDRiOGI3Y2JkZjNkMGQxMjBhMGI2ZmY4ZWYxYWYxMzI4NjNiMWFmMTI2MzRlYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.kIjQ_5viSCbmwQhctb5KokHk05ARaIUFC_jQX7Qwlzo)

Thanks but not really what I was trying to achieve, is there a way to apply using this approach to a subclassed control ? this would apply to all entries in the app.

**Comment by pmahend1** [comment] 2024-08-19 15:53
@mackayn I was able to apply it for sub-classed control 
Here is how I did it.

MauiProgram.cs
```csharp
 MauiApp.CreateBuilder().ConfigureMauiHandlers(handlers =>
 {
     handlers.AddHandler(typeof(BorderedEntry), typeof(BorderedEntryHandler));
 });
```

Created BorderedEntryHandler in Platforms/Android namespace has to be same as of MauiProgram
```csharp
public partial class BorderedEntryHandler : EntryHandler
{
    public BorderedEntryHandler()
    {
        Mapper.ReplaceMapping<IEntry, IEntryHandler>("Background", BorderedEntryMapper);
    }

    private void BorderedEntryMapper(IEntryHandler handler, IEntry entry)
    {
        var platformView = handler.PlatformView;

        // Android will reset the padding when setting a Background drawable, so we need to reapply the padding after
        var padLeft = platformView.PaddingLeft;
        var padTop = platformView.PaddingTop;
        var padRight = platformView.PaddingRight;
        var padBottom = platformView.PaddingBottom;

        // Set the custom background
        var gd = new Android.Graphics.Drawables.GradientDrawable();
        gd.SetCornerRadius(3);
        gd.SetStroke(1, Android.Graphics.Color.Red);
        gd.SetColor(Android.Graphics.Color.Pink);
        platformView.Background = gd;

        // Apply previous padding
        platformView.SetPadding(padLeft, padTop, padRight, padBottom);
}
```

**Comment by mackayn** [comment] 2024-08-19 15:59
> @mackayn I was able to apply it for sub-classed control Here is how I did it.
> 
> MauiProgram.cs
> 
> ```cs
>  MauiApp.CreateBuilder().ConfigureMauiHandlers(handlers =>
>  {
>      handlers.AddHandler(typeof(BorderedEntry), typeof(BorderedEntryHandler));
>  });
> ```
> 
> Created BorderedEntryHandler in Platforms/Android, namespace has to be same as of MauiProgram
> 
> ```cs
> public partial class BorderedEntryHandler : EntryHandler
> {
>     public BorderedEntryHandler()
>     {
>         Mapper.ReplaceMapping<IEntry, IEntryHandler>("Background", BorderedEntryMapper);
>     }
> 
>     private void BorderedEntryMapper(IEntryHandler handler, IEntry entry)
>     {
>         var platformView = handler.PlatformView;
> 
>         // Android will reset the padding when setting a Background drawable, so we need to reapply the padding after
>         var padLeft = platformView.PaddingLeft;
>         var padTop = platformView.PaddingTop;
>         var padRight = platformView.PaddingRight;
>         var padBottom = platformView.PaddingBottom;
> 
>         // Set the custom background
>         var gd = new Android.Graphics.Drawables.GradientDrawable();
>         gd.SetCornerRadius(3);
>         gd.SetStroke(1, Android.Graphics.Color.Red);
>         gd.SetColor(Android.Graphics.Color.Pink);
>         platformView.Background = gd;
> 
>         // Apply previous padding
>         platformView.SetPadding(padLeft, padTop, padRight, padBottom);
>    }
> }
> ```

I never thought of consuming the API that way, your 100% right about needing more documentation on mappers, I'm guessing some of these 3.5K open issues are this type of thing, a misunderstanding of the mappers API. That's working very nicely, thanks.

**Comment by mattleibow** [comment] 2024-08-19 16:09
You should be able to override the behaviour using the generics (note the use of `BorderedEntry` instead of `IEntry`:

```cs
EntryHandler.Mapper.ReplaceMapping<BorderedEntry, IEntryHandler>("Background", (handler, view) =>
```

**Comment by mackayn** [comment] 2024-08-19 18:09
> You should be able to override the behaviour using the generics (note the use of `BorderedEntry` instead of `IEntry`:
> 
> ```cs
> EntryHandler.Mapper.ReplaceMapping<BorderedEntry, IEntryHandler>("Background", (handler, view) =>
> {
>     // your code here
> });
> ```
> 
> ```cs
> public class BorderedEntry : Entry
> {
> }
> ```
> 
> With this XAML where once is a normal entry and the other is a custom one, the mapper only applies to the custom one - without requiring a new handler and new handler registration. We basically register the mapper as a smaller unit.
> 
> ```
> <Entry
>     Text="Hello, World!"
>     Background="Orange" />
> 
> <local:BorderedEntry
>     Text="Hello, World!"
>     Background="Orange" />
> ```
> 
> <img alt="" width="300" src="https://private-user-images.githubusercontent.com/1096616/359173111-563880b5-d0fe-4d0f-af05-8ca310037036.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwODU2MjMsIm5iZiI6MTcyNDA4NTMyMywicGF0aCI6Ii8xMDk2NjE2LzM1OTE3MzExMS01NjM4ODBiNS1kMGZlLTRkMGYtYWYwNS04Y2EzMTAwMzcwMzYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTlUMTYzNTIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzY3ZjlkZjM2YTliMDEzZjExNTViNjYzMjE1ODg5MTkyY2RlNDQ5MmZkODVkNzU0Y2M2OTJlNWZkNGZkM2YwMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.yzIgLb7ywy5GBMlIU5dkWgls9-ePwpz2UlLh-lNz-84">

Nice, worked well for the Editor too.

**Closed** 2024-08-21 11:13 UTC
Labels: t/bug, platform/android 🤖, p/1, s/verified, area-controls-entry, s/triaged, i/regression

**Comment by borrmann** [comment] 2024-09-19 20:08
@pmahend1 
I use this:
```
public partial class MyEditorHandler : Microsoft.Maui.Handlers.EditorHandler
{
    protected override void ConnectHandler(AppCompatEditText platformView)
    {
        base.ConnectHandler(platformView);

        if(platformView != null)
        {
            // remove the line below text
            platformView.SetBackgroundColor(Color.Transparent);
            platformView.BackgroundTintList = Android.Content.Res.ColorStateList.ValueOf(Color.Transparent);
        }
    }
```

**Comment by pmahend1** [comment] 2024-09-19 21:27
@borrmann Thanks but I had tried the same logic. I am on Android 34 if that matters.

**Comment by mackayn** [comment] 2024-09-19 21:46
> @mackayn how were you able to make it work for Editor. As soon as I set `Background` or `BackgroundTintList` the background color is getting reset to white. It is annoyingly evident in Dark theme mode. I tried replace and append mapper both

Sorry, on vacation, not near a dev env but if you setup the correct handler type it works for editor in iOS and Android, don't override ConnectHandler.

https://learn.microsoft.com/en-us/dotnet/maui/user-interface/handlers/?view=net-maui-8.0#view-handlers. Use the approach recommended by @mattleibow
