### ISSUE TITLE
[WinUI] Image with FontImageSource is not displayed properly when using a custom font in an unpackaged app

### ISSUE THREAD

**Issue by marchev-prgs** [dotnet/maui#19608] opened 2023-12-28 15:00 UTC
### Description

I have an Image with a FontImageSource, and the Glyph is not displayed properly when a custom font is used:

`
<Image x:Name="i3" WidthRequest="100" HeightRequest="100" Background="#33EE22AA">
`
`
  <Image.Source>
`
`
    <FontImageSource Glyph="&#xe85b;" FontFamily="my_custom_font" />
`

Please see the repro project.
Note that this happens only in an unpackaged winui app:
<WindowsPackageType>None</WindowsPackageType>

Here is an image of what is shown:
![fontimagesource_unpack_img](https://github.com/dotnet/maui/assets/91615935/01d5034d-1b53-4f7f-a55a-97ae7aa3a90e)

And here is an image of what is expected:
![fontimagesource_pack_img](https://github.com/dotnet/maui/assets/91615935/7a883106-a7a4-45e3-830b-3cd2d4fe08f4)

### Steps to Reproduce

1. Get the repo from [the link](https://github.com/telerik/ms-samples/tree/main/Maui/FontImageSourceNotDisplayedInUnpackagedWinUIApp) 
2. Go to folder Maui\FontImageSourceNotDisplayedInUnpackagedWinUIApp
3. Run the sample application in WinUI

**Expected Behavior**
The `Image` should display the glyph from the custom font, it should look like a little house.

**Actual Behavior**
The `Image` does not display the glyph properly, just some rectangle is drawn.

### Link to public reproduction project repository

https://github.com/telerik/ms-samples/tree/main/Maui/FontImageSourceNotDisplayedInUnpackagedWinUIApp

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Did you find any workaround?

I did not find a workaround.

**Comment by marchev-prgs** [comment] 2023-12-28 15:03
This issue is most likely the one Matthew mentions [here](https://github.com/dotnet/maui/issues/15802#issuecomment-1831848494).

**Comment by BrunoVersa** [comment] 2024-01-03 13:56
I have the same trouble

**Comment by rmarinho** [comment] 2024-01-11 20:10
Duplicate of #15802

**Closed by rmarinho** 2024-01-11 20:10 UTC
Labels: t/bug, platform/windows 🪟, area/image :framed_picture:, partner, area/fonts 🅰️
