### ISSUE TITLE
[macOS] [8.0] Hybrid app crashed after launch on macOS 12.4

### ISSUE THREAD

**Issue by Ocrosoft** [dotnet/maui#19904] opened 2024-01-15 15:10 UTC
### Description

[MauiBlazorApp1-2024-01-15-225035.zip](https://github.com/dotnet/maui/files/13940196/MauiBlazorApp1-2024-01-15-225035.zip)
View the ips file for detail stack.

`-f:net7.0-maccatalyst` works fine, but I can't build net7.0 with macOS 14.1.1...

### Steps to Reproduce

1. Create new HybridApp in VsCode.
2. Publish an app using: `dotnet publish -f:net8.0-mcacatalyst -c:Release -p:CreatePackage=false`
3. Copy the generated app to another mac which running macOS 12.4
4. Run the app

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.49

### Affected platforms

macOS

### Did you find any workaround?

I found this issue with same stack: https://github.com/dotnet/maui/issues/18419
But `AddBlazorWebViewDeveloperTools` is wrapped with `#if DEBUG` in the template project.

**Comment by jsuarezruiz** [comment] 2024-01-15 15:24
@Eilon Thoughts?

**Comment by drasticactions** [comment] 2024-01-15 15:42
Duplicate of https://github.com/dotnet/maui/issues/19613

The numbers used in the check are wrong and need to be updated.

**Closed by drasticactions** 2024-01-15 15:42 UTC
Labels: t/bug, platform/macOS 🍏, area/blazor 🕸️, area/publishing 🏁

**Comment by Ocrosoft** [comment] 2024-01-15 16:06
emm... So I should find a mac with an older version to build with .Net7.0 😥

**Comment by drasticactions** [comment] 2024-01-15 16:27
https://github.com/dotnet/maui/pull/19909

This PR should fix it

**Comment by Eilon** [comment] 2024-02-09 17:48
For anyone running into this issue, I might have figured out a workaround that you can apply to affected apps: https://github.com/dotnet/maui/issues/19613#issuecomment-1936338880

(Or, we will have a patch for .NET 8 that will go out, if you are able to wait.)
