### ISSUE TITLE
Grid sizes do not update with bindings (regression)

### ISSUE THREAD

**Issue by boarder2** [dotnet/maui#8730] opened 2022-07-14 05:43 UTC
### Description

When defining a grid with sizes that use binding:
```
<Grid>
    <Grid.ColumnDefinitions>
        <ColumnDefinition Width="{Binding ColumnSize}" />
        <ColumnDefinition Width="*" />
    </Grid.ColumnDefinitions>
    <Rectangle Fill="Green" Grid.Column="0" />
    ...
</Grid>
```

The grid sizing should respect the binding. Instead, it appears to treat it as a `*`

This worked in the version that came with VS22 Preview 2 but broke with Preview 3

I tested on macOS 12.4, iOS Simulator 15.5, Android Emulator, and Windows 11.

Functionality works as expected on Android and Windows.
It is broken on iOS and macOS.

### Steps to Reproduce

Run the project:
[GridSizeBinding.zip](https://github.com/dotnet/maui/files/9108528/GridSizeBinding.zip)

Click the button.
The grid columns should resize, but they don't.

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

I was *not* able test on other platforms

### Affected platform versions

Tested on: macOS 12.4, iOS 15.5 simulator

**Comment by hartez** [comment] 2022-07-14 18:22
> Does this have to do with #7499?

Seems doubtful, since #7499 affects all platforms and this is iOS/Catalyst only.

**Comment by hartez** [comment] 2022-07-14 19:36
The attached repro project works fine with the latest workloads, so if there _was_ a regression it's now fixed, and the fix will be available in an upcoming service release.

**Closed by hartez** 2022-07-14 19:36 UTC
Labels: t/bug, area/layout 🔲, i/regression
