### ISSUE TITLE
CollectionView strange load behavior for WinUI

### ISSUE THREAD

**Issue by enkaradag** [dotnet/maui#18913] opened 2023-11-21 01:43 UTC
### Description

Hi,

I moved one of my MAUI projects from .net7 to .net8

I am using CollectionView with some complex itemtemplates. It worked good for .net7. But for .net8; collectionview has a strange load behavior (for winui only);

I have 1000 rows of data for collectionview. When ItemSource is set, CollectionView loads count of rows that fits the vertical size of the collectionview as expected (for my sample it is 13 rows here). But after loading 13 rows, in 2 (or 3) seconds it starts to load all 1000 rows

My Test Code is simple;

Here is the xaml:

```
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="CollectionViewTest.MainPage">

    <StackLayout Padding="10" Spacing="10">
        <Button x:Name="btn_fill" Text="Fill With 1000 Rows of Data" Clicked="btn_fill_Clicked"/>
        <CollectionView x:Name="view" HeightRequest="500"/>
    </StackLayout>

</ContentPage>
```

and here is the c# part

```
        public class ROWDATA
        {
            public int ID = 0;
            public string FIELD1 { get; set; }
        }

        int CreatedRowCount = 0;

        private void btn_fill_Clicked(object sender, EventArgs e)
        {

            ObservableCollection<ROWDATA> ROWS = new ObservableCollection<ROWDATA>();

            for (int i = 0; i < 1000; i++)
                ROWS.Add(new ROWDATA() { ID = i, FIELD1 = Guid.NewGuid().ToString() });

            view.ItemTemplate = new DataTemplate(() =>
            {
                CreatedRowCount++;
                Debug.WriteLine("CreatedRowCount=" + CreatedRowCount);

                Grid g = new Grid();
                g.RowDefinitions.Add(new RowDefinition(new GridLength(40)));

                Label label_ID = new Label() { VerticalTextAlignment = TextAlignment.Center };
                label_ID.SetBinding(Label.TextProperty, "FIELD1");
                g.Children.Add(label_ID);

                return g;
            });

            view.ItemsSource = ROWS;
        }
```

And here is the debug result:

![collectionview_load](https://github.com/dotnet/maui/assets/57816471/e47292e0-2490-451a-97e2-366aeed13143)

CollectionView height is constant, i am not scrolling or even moving the mouse.

This wont be a problem if one label is used. But if a complex itemtemplate is used this behavior locks ui until all data is loaded.

This is not working like this for ios, android and maccatalyst. Enough number of rows are loaded when scrolled or horizontally resized only for them as expected

Any idea on how to control that behavior?

Thanks & Regards

Ender

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.101

### Affected platforms

Windows

### Did you find any workaround?

No

**Comment by drasticactions** [comment] 2023-11-21 02:19
Duplicate of https://github.com/dotnet/maui/issues/18639

**Closed by drasticactions** 2023-11-21 02:19 UTC
Labels: t/bug
