### ISSUE TITLE
CarouselView Shows All Items at Once in Windows

### ISSUE THREAD

**Issue by cbaer-extron** [dotnet/maui#7180] opened 2022-05-13 20:12 UTC
### Description

When running a Maui app on Windows, a page containing a CarouselView shows all items at once instead of having to swipe with the mouse to reveal each consecutive item.   This happens the same way whether the Page is within Shell or called directly.

CarouselView demo in Windows compared to Android:
https://user-images.githubusercontent.com/101732760/168382296-6cb5518f-9cef-46f4-a4d8-4906cd85df7a.mp4

Demo Project:
https://github.com/cbaer-extron/BugReports/tree/main/CarouselViewTestApp

### Steps to Reproduce

1. Create a new Maui App
2. Add a CarouselView to the MainPage
3. Create a List of strings to use as the source for the CarouselView and assign it to the CarouselView's ItemsSource.
4. In Xaml, define an ItemTemplate that defines the size and attributes of the CarouselView item, and that contains a Label bound to the content of the string list.
5. Run the app on Windows.
6. Notice that the CarouselView shows all items from left to right on the screen.
7. Hover over the CarouselView and a horizontal scrollbar appears.
8.  Notice how dragging the scrollbar creates an endless stream of items that continue to scroll

.

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10

### Did you find any workaround?

No.

**Comment by cbaer-extron** [comment] 2022-06-08 17:15
Are these connected? https://github.com/dotnet/maui/issues/7749

**Comment by cbaer-extron** [comment] 2022-09-26 23:25
Tested the same test project with Microsoft Visual Studio Professional 2022 (2) (64-bit) - Preview
Version 17.4.0 Preview 2.1.

No change.  The same results in Windows.

**Comment by cbaer-extron** [comment] 2022-10-04 15:42
Can someone post a demo of Carousel working on Windows?  Because, I just tested with the latest build 17.4.0 Preview 2.1, and it is still malfunctioning for me.  I'm not sure why the issue was closed.

**Comment by mlancione** [comment] 2022-10-06 02:43
I have the same issues in Windows. The CarouselView appears to be completely broken due to this issue. Please reopen the issue.

**Comment by cbaer-extron** [comment] 2022-10-06 15:45
Looks like msftbot just closed it automatically. But why?  The bot stated above "This issue will be closed automatically in 7 days if we do not hear back from you by then..."  I got back to them immediately with my response.  But they closed it anyway.

**Comment by mattleibow** [comment] 2023-01-11 19:11
Duplicate of #12567

**Closed by mattleibow** 2023-01-11 19:11 UTC
Labels: t/bug, area/collectionview 📃, high, s/verified, s/try-latest-version
