### ISSUE TITLE
[Android] AOT not working, app crashes after start

### ISSUE THREAD

**Issue by MartinRothschink** [dotnet/maui#9163] opened 2022-08-03 08:42 UTC
### Description

I try to make use of AOT but the app crashes immediately after start.
Physical device Nokia X10 on Android 12.

ADB says:
08-03 10:24:31.592	HMD Global Nokia X10	Error	17068	.<app_name>	* Assertion at /__w/1/s/src/mono/mono/mini/aot-runtime.c:3678, condition `is_ok (error)' not met, function:decode_patch, module 'Microsoft.Maui.dll.so' is unusable (GUID of dependent assembly Xamarin.AndroidX.AppCompat doesn't match (expected '1FC81757-8A70-4D56-93E6-8A635E2C23DE', got 'FD3821D1-CBF4-4956-B930-EA2A5379E18D')).

### Steps to Reproduce

Does not happen with a simple new Maui app.

I have enabled these options for release builds
- AOT (not using LLVM)
- Startup tracing

### Version with bug

6.0.408 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Observed on Android 12

### Did you find any workaround?

Not using AOT

### Relevant log output

```shell
08-03 10:24:31.592	HMD Global Nokia X10	Error	17068	.<appname>	* Assertion at /__w/1/s/src/mono/mono/mini/aot-runtime.c:3678, condition `is_ok (error)' not met, function:decode_patch, module 'Microsoft.Maui.dll.so' is unusable (GUID of dependent assembly Xamarin.AndroidX.AppCompat doesn't match (expected '1FC81757-8A70-4D56-93E6-8A635E2C23DE', got 'FD3821D1-CBF4-4956-B930-EA2A5379E18D')).
08-03 10:24:32.486	HMD Global Nokia X10	Error	671	tombstoned	Tombstone written to: tombstone_11
  Force finishing activity <appname>/crc64dc9be6c7000262f1.MainActivity
08-03 10:24:32.434	HMD Global Nokia X10	Error	17110	DEBUG	backtrace:
      #00 pc 00000000000516cc  /apex/com.android.runtime/lib64/bionic/libc.so (abort+168) (BuildId: ee6d5e9de5525e0fa64bf23cb7ba1f96)
      #01 pc 0000000000029b1c  /data/app/~~v2NJ036lZ2vdG5iaWRdYvg==/<appname>-NHFiBPGLjhtQKRYAKqQqPw==/lib/arm64/libmonodroid.so (xamarin::android::internal::MonodroidRuntime::mono_log_handler(char const*, char const*, char const*, int, void*)+144) (BuildId: 29c5a3805a0bedee1eede9b6668d7c676aa63371)
      #02 pc 0000000000264074  /data/app/~~v2NJ036lZ2vdG5iaWRdYvg==/<appname>-NHFiBPGLjhtQKRYAKqQqPw==/lib/arm64/libmonosgen-2.0.so (BuildId: 7126846382da0d3e3df8b79b9e84b9aa48aaaf36)
      #03 pc 00000000002641a0  /data/app/~~v2NJ036lZ2vdG5iaWRdYvg==/<appname>-NHFiBPGLjhtQKRYAKqQqPw==/lib/arm64/libmonosgen-2.0.so (BuildId: 7126846382da0d3e3df8b79b9e84b9aa48aaaf36)
      #04 pc 00000000001dab14  /data/app/~~v2NJ036lZ2vdG5iaWRdYvg==/<appname>-NHFiBPGLjhtQKRYAKqQqPw==/lib/arm64/libmonosgen-2.0.so (BuildId: 7126846382da0d3e3df8b79b9e84b9aa48aaaf36)
      #05 pc 00000000001d94a4  /data/app/~~v2NJ036lZ2vdG5iaWRdYvg==/<appname>-NHFiBPGLjhtQKRYAKqQqPw==/lib/arm64/libmonosgen-2.0.so (BuildId: 7126846382da0d3e3df8b79b9e84b9aa48aaaf36)
      #06 pc 00000000001eb558  /data/app/~~v2NJ036lZ2vdG5iaWRdYvg==/<appname>-NHFiBPGLjhtQKRYAKqQqPw==/lib/arm64/libmonosgen-2.0.so (BuildId: 7126846382da0d3e3df8b79b9e84b9aa48aaaf36)
      #07 pc 0000000000004ef8  <anonymous:6fce935000>
08-03 10:24:32.433	HMD Global Nokia X10	Error	17110	DEBUG	signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
    x0  0000000000000000  x1  00000000000042ac  x2  0000000000000006  x3  0000007ff3832400
    x4  6e6d6e6c2e627172  x5  6e6d6e6c2e627172  x6  6e6d6e6c2e627172  x7  7f7f7f7f7f7f7f7f
    x8  00000000000000f0  x9  719088a034f5fa82  x10 0000000000000000  x11 ffffff80fffffbdf
    x12 0000000000000001  x13 000000000000014a  x14 0000007ff38312a0  x15 0000000034155555
    x16 0000006fb6861050  x17 0000006fb683e0e0  x18 0000006fdc378000  x19 00000000000042ac
    x20 00000000000042ac  x21 00000000ffffffff  x22 0000006c07062498  x23 b400006e240510b0
    x24 b400006d8362e9b0  x25 0000006c07062498  x26 0000006c0d439e30  x27 0000006c1f9b6000
    x28 0000006fdb2bb000  x29 0000007ff3832480
    lr  0000006fb67ef6a0  sp  0000007ff38323e0  pc  0000006fb67ef6cc  pst 0000000000001000
08-03 10:24:32.433	HMD Global Nokia X10	Error	17110	DEBUG	uid: 10262
08-03 10:24:32.433	HMD Global Nokia X10	Error	17110	DEBUG	pid: 17068, tid: 17068, name: .<appname>  >>> <appname> <<<
08-03 10:24:32.433	HMD Global Nokia X10	Error	17110	DEBUG	Cmdline: <appname>
08-03 10:24:32.433	HMD Global Nokia X10	Error	17110	DEBUG	Process uptime: 0s
08-03 10:24:32.433	HMD Global Nokia X10	Error	17110	DEBUG	Timestamp: 2022-08-03 10:24:31.660578292+0200
08-03 10:24:32.433	HMD Global Nokia X10	Error	17110	DEBUG	ABI: 'arm64'
08-03 10:24:32.433	HMD Global Nokia X10	Error	17110	DEBUG	Revision: '0'
08-03 10:24:32.433	HMD Global Nokia X10	Error	17110	DEBUG	Build fingerprint: 'Nokia/ScarletWitch_00EEA/SCW_sprout:12/SKQ1.210821.001/00WW_2_400:user/release-keys'
08-03 10:24:32.433	HMD Global Nokia X10	Error	17110	DEBUG	*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
08-03 10:24:31.661	HMD Global Nokia X10	Error	17110	DEBUG	failed to read /proc/uptime: Permission denied
08-03 10:24:31.653	HMD Global Nokia X10	Info	17110	crash_dump64	performing dump of process 17068 (target tid = 17068)
08-03 10:24:31.652	HMD Global Nokia X10	Info	671	tombstoned	received crash request for pid 17068
08-03 10:24:31.649	HMD Global Nokia X10	Info	17110	crash_dump64	obtaining output fd from tombstoned, type: kDebuggerdTombstoneProto
08-03 10:24:31.592	HMD Global Nokia X10	Error	17068	libc	Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 17068 (.<appname>), pid 17068 (.<appname>)
```

**Comment by Symbai** [comment] 2022-08-03 09:35
I had exactly the same issue with AOT = crash right after splashscreen and without AOT it worked fine. I fixed it by creating a new project (same name) and copy all code over (opening files, CTRL+A, CTRL+C and then CTRL+V. I have NOT copied files or folders) so it's pretty much 100% identical. Then the app no longer crashes with AOT on. Sounds weird? It is weird. But you may try the same, because I've wasted a lot of time waiting for a reply or fix.

**Comment by jfversluis** [comment] 2022-08-03 12:07
Duplicate of #8928

**Closed by jfversluis** 2022-08-03 12:07 UTC
Labels: t/bug, s/needs-verification
