### ISSUE TITLE
Exception using <Frame> in a databound ListView on Android

### ISSUE THREAD

**Issue by Warnestam** [dotnet/maui#22568] opened 2024-05-22 08:47 UTC
### Description

When having a ListView that is bound to an ObservableCollection, and where the first element after the DataTemplate, ViewCell is a Frame, the application crashes with the error "System.ObjectDisposedException Message=Cannot access a disposed object. Object name: 'Microsoft.Maui.Controls.Handlers.Compatibility.FrameRenderer'."

This happens on Android, but on Windows it's fine

### Link to public reproduction project repository

https://github.com/Warnestam/Repro-MauiObservableCollection

### Version with bug

8.0.7 SR2

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 13

### Did you find any workaround?

If the <Frame> element is encapsulated in a layout control, such as a <VerticalStackLayout>, then the application does not  crash.

**Comment by atabaksahraei** [comment] 2024-05-22 11:01
same

**Comment by PureWeen** [comment] 2024-05-22 17:26
Duplicate of #11323

**Closed by PureWeen** 2024-05-22 17:26 UTC
Labels: t/bug
