### ISSUE TITLE
[IOS] Cannot build release version : the AOT compiler exited with code 139.

### ISSUE THREAD

**Issue by Migoked** [dotnet/maui#26276] opened 2024-11-29 13:37 UTC
### Description

When I try to build an iOS Release version, i have this error : 

```
--notrimwarn --custom-data "LinkerOptionsFile=obj/Release/net9.0-ios/ios-arm64/custom-linker-options.txt" --verbose -b --disable-opt unusedtypechecks --enable-opt sealer --enable-serialization-discovery --notrimwarn
2>IL stripping assemblies
2>Tool /Users/usr/Library/Caches/Xamarin/XMA/SDKs/dotnet/packs/Microsoft.NETCore.App.Runtime.AOT.osx-arm64.Cross.ios-arm64/9.0.0/Sdk/../tools/mono-aot-cross execution finished (exit code = 139).
2>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net9.0_18.1\18.1.9163\targets\Xamarin.Shared.Sdk.targets(1279,3): error : Failed to AOT compile aot-instances.dll, the AOT compiler exited with code 139.
```

**Workloads**
```
android                    35.0.7/9.0.100         SDK 9.0.100, VS 17.12.35521.163
ios                        18.1.9163/9.0.100      SDK 9.0.100, VS 17.12.35521.163
maccatalyst                18.1.9163/9.0.100      SDK 9.0.100, VS 17.12.35521.163
maui-windows               9.0.0/9.0.100          SDK 9.0.100, VS 17.12.35521.163
```
**XCode**
Version 16.1

### Version with bug

9.0.10 SR1

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.100 SR10

### Affected platforms

iOS

### Did you find any workaround?

**No workaround**. I tried to add this, like mentionned [here](https://github.com/dotnet/runtime/issues/109966#issuecomment-2486161265) but its not working
```
<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net9.0-ios|AnyCPU'">
    <EnableSGenConc>True</EnableSGenConc>
    <MtouchInterpreter>-all,System.Private.Windows.Core</MtouchInterpreter>
</PropertyGroup>
```

### Relevant log output

```shell

```

**Comment by StephaneDelcroix** [comment] 2024-11-29 14:27
see https://github.com/dotnet/maui/issues/26276
duplicate of #25890

**Closed by StephaneDelcroix** 2024-11-29 14:27 UTC
Labels: t/bug, platform/iOS 🍎
