### ISSUE TITLE
Directory.GetFiles/CreateDirectory/Exists..etc throw System.UnauthorizedAccessException when only a folder is specified

### ISSUE THREAD

**Issue by magals** [dotnet/maui#9898] opened 2022-09-04 03:09 UTC
### Description

want to use MAUI for windows application.
in the project, I need to specify that there are files that need to be loaded from an additional folder, which is located with the exe file. 
but code Directory.CreateDirectory("my folder"); throw System.UnauthorizedAccessException becouse base path set to 'C:\WINDOWS\system32\'

"System.UnauthorizedAccessException: 'Access to the path 'C:\WINDOWS\system32\myfolder' is denied.'"
I checked in the console application and in WPF, there is no such problem

### Steps to Reproduce

1. Create a file > New .NET MAUI App
2. add code: protected override MauiApp CreateMauiApp()
	{
		var app = MauiProgram.CreateMauiApp();
		Directory.CreateDirectory("my folder");
		return app;
	}
in public partial class App : MauiWinUIApplication
3. Run Project

### Link to public reproduction project repository

default project

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

windows sdk

### Did you find any workaround?

no

**Comment by MagicAndre1981** [comment] 2022-09-04 05:11
Use [FileSystem.Current.AppDataDirectory](https://docs.microsoft.com/en-us/dotnet/maui/platform-integration/storage/file-system-helpers?tabs=windows#app-data-directory) to get a safe location to store user/app data

**Comment by magals** [comment] 2022-09-04 06:26
> Use [FileSystem.Current.AppDataDirectory](https://docs.microsoft.com/en-us/dotnet/maui/platform-integration/storage/file-system-helpers?tabs=windows#app-data-directory) to get a safe location to store user/app data

this is a little problematic since directory creation is used in another project of mine that is packaged with nuget. The nuget package is used in the wpf project and for the console application. remake under FileSystem.Current.CacheDirectory which only for MAUI seems to me not a very good idea

**Comment by MagicAndre1981** [comment] 2022-09-04 06:31
If you can't use the suggested way you have to [run the app as admin](https://blog.verslu.is/maui/net-maui-windows-app-as-administrator-elevated/) to be able to create folders in System32. BUT only do this if there is really no other way.

**Comment by magals** [comment] 2022-09-04 06:38
> If you can't use the suggested way you have to [run the app as admin](https://blog.verslu.is/maui/net-maui-windows-app-as-administrator-elevated/) to be able to create folders in System32. BUT only do this if there is really no other way.

I don't want to touch System32. I need the folder to be created in the same path where the program is launched.

the library uses such a constructor. it assumes that if the parameter is not given an explicit path to another folder where the files for reading are located, then a default folder is created next to the program

``` C#
public InstanceLogicDevices(string pathfolderdrivers = "drivers",  ILogger<InstanceLogicDevices>? logger = null)
{
   try
   {
	if (!Directory.Exists(pathfolderdrivers))
	{
	   Directory.CreateDirectory(pathfolderdrivers);
	}
```

**Comment by jfversluis** [comment] 2022-09-05 10:55
I think this is due to how WinUI apps work as sort of containerized. It seems the working folder is set to System32 by default. 

You probably want to test how it behaves when the app is actually deployed. I believe there is also options to set the current working directory from Visual Studio.

Personally, I think assuming that creating a directory without specifying any root is a bad idea, as you can see, the behavior is not consistent across frameworks or platforms. 

The FileSystem helpers might be of help here: https://docs.microsoft.com/xamarin/essentials/file-system-helpers?tabs=ios

Closing this as not a bug.

**Closed by jfversluis** 2022-09-05 10:55 UTC
Labels: t/bug
