### ISSUE TITLE
Margin presented as Padding on iOS inside a CollectionView

### ISSUE THREAD

**Issue by RsZoli** [dotnet/maui#25144] opened 2024-10-09 08:55 UTC
### Description

When presenting content in a CollectionView, setting its Margin property presented as Padding on iOS!

![Image](https://github.com/user-attachments/assets/3159fd9f-58d2-4c8f-929f-6d1f85093625)

<CollectionView ItemsSource="{Binding TestDatas}"
                BackgroundColor="PaleGoldenrod"
                Margin="10">

    <CollectionView.ItemTemplate>

        <DataTemplate>

            <Border StrokeShape="RoundRectangle"
                    StrokeThickness="1"
                    Stroke="Black"
                    BackgroundColor="LightGray"
                    HeightRequest="50"
                    Margin="0, 0, 0, 10">

                <Label Text="{Binding}"
                        HorizontalOptions="Center"
                        VerticalOptions="Center" />

            </Border>

        </DataTemplate>

    </CollectionView.ItemTemplate>

</CollectionView>

### Link to public reproduction project repository

https://github.com/RsZoli/GitHubRepros

### Version with bug

8.0.91 SR9.1

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

**Comment by drasticactions** [comment] 2024-10-09 09:50
Duplicate of https://github.com/dotnet/maui/issues/23211

The border as padding was listed there as one of the issues presented.

**Closed by drasticactions** 2024-10-09 09:50 UTC
Labels: t/bug
