### ISSUE TITLE
[net7.0 / net8.0] [iOS] Memory leak when CollectionView.ItemsSource changes

### ISSUE THREAD

**Issue by nacompllo** [dotnet/maui#14664] opened 2023-04-19 15:14 UTC
### Description

I am aware of the existence of the following bug [#13530](https://github.com/dotnet/maui/pull/13530) but only mention is made of Windows, however in iOS the same memory leak problem also occurs when updating the ItemsSource of a CollectionView several times and the RAM memory is not released even by browsing backwards:

<img width="691" alt="issue1" src="https://user-images.githubusercontent.com/20904914/233118920-5553a150-707d-4c1d-811c-d1ff390ed136.png">

I leave a video playing an example repository where I can reproduce this problem in iOS until the application crashes due to lack of memory:
https://www.youtube.com/watch?v=_UTEGbE4-ug

I leave the repository that I show in the video so you can do the test:
https://github.com/nacompllo/MemoryLeakEverywhere/tree/bugfix/memoryLeakItemsSource

### Steps to Reproduce

- Clone the following repository:
https://github.com/nacompllo/MemoryLeakEverywhere/tree/bugfix/memoryLeakItemsSource
- Run the app on an iOS device.
- Have Xcode Instruments open to see how the RAM increases.
- Follow the same steps as in the attached video.

### Link to public reproduction project repository

https://github.com/nacompllo/MemoryLeakEverywhere/tree/bugfix/memoryLeakItemsSource

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 16

### Depends on
- [x] https://github.com/dotnet/maui/pull/15062
- [x] https://github.com/dotnet/maui/pull/15303
- [x] https://github.com/dotnet/maui/pull/15831
- [x] https://github.com/dotnet/maui/pull/15946

**Comment by nacompllo** [comment] 2023-04-19 15:38
> How is this different from #14654, which is not closed?

The [#14654](https://github.com/dotnet/maui/issues/14654) is about a memory leak when repeatedly navigating between pages and [#14664](https://github.com/dotnet/maui/issues/14664) is a memory leak when the ItemsSource from CollectionView changes.

**Comment by jonathanpeppers** [comment] 2023-05-09 14:36
@nacompllo and you were testing this on .NET 7?

It might be fixed by this one, which is only in main/.NET 8 currently:

* https://github.com/dotnet/maui/pull/14329

I will test your above sample, though, thanks.

**Comment by jonathanpeppers** [comment] 2023-05-09 14:39
Note that my comment here:

![image](https://github.com/dotnet/maui/assets/840039/6bd0ccfe-c531-4419-a792-2711839d18e9)

Is specifically talking about a list of "logical children" that grew indefinitely on Windows.

**Comment by jonathanpeppers** [comment] 2023-05-09 16:37
There appears to be an issue with images on iOS, a failing test:
```csharp
[Fact("Image Does Not Leak")]
public async Task DoesNotLeak()
{
	SetupBuilder();
	WeakReference reference = null;

	await InvokeOnMainThreadAsync(async () =>
	{
		var layout = new VerticalStackLayout();
		var image = new Image
		{
			Background = Colors.Black,
			Source = "red.png",
		};
		layout.Add(image);

		var handler = CreateHandler<LayoutHandler>(layout);
		await image.Wait();
		reference = new WeakReference(image.Handler.PlatformView);
	});

	await Task.Yield();
	GC.Collect();
	GC.WaitForPendingFinalizers();
	
	Assert.NotNull(reference);
	Assert.False(reference.IsAlive, "PlatformView should not be alive!");
}
```
Still investigating what the fix would be.

**Comment by QuiqueLargachaGil** [comment] 2023-05-29 14:05
Hi everyone,

I can see that the issue is still in an Open status, but I am writing to provide some feedback just in case it helps.
I have forked the repository indicated by @nacompllo and I have tested the same application compiling with the version released a few days ago of .Net 8 preview 4. The changes to make the compilation are isolated in two independent branches (one for https://github.com/dotnet/maui/issues/14654 and another for https://github.com/dotnet/maui/issues/14664). Here is a link to the repository:


https://github.com/QuiqueLargachaGil/MAUI-POC.MemoryLeakEverywhere/tree/bugfix/updated-to-Net-8-preview-4-in-memoryLeakItemsSource-branch

And the result for the case of this incident is the same. There are still memory leaks when reproducing the issue. I share with you a youtube link to watch the video that shows it.


https://www.youtube.com/watch?v=EAxcUQE6wLE

Many thanks!

**Comment by jonathanpeppers** [comment] 2023-05-30 14:41
Yes, this is not fixed until we get these merged:
* https://github.com/dotnet/maui/pull/15062
* https://github.com/dotnet/maui/pull/15193

But then we'll need to retest the above sample app, to see if there are further issues.

**Comment by jonathanpeppers** [comment] 2023-07-07 14:11
The list of linked PRs above address various memory issues found the in above sample. However, the memory still appears to grow in the sample with dotnet/maui/main at this time.

### Latest Issue ###

I found the "logical children" grow indefinitely on iOS/Catalyst, after adding some logging the sample above quickly got up to 71 items:

    2023-07-06 09:04:27.745 MemoryLeakEverywhere[93127:7440192] Microsoft.Maui.Controls.CollectionView added child -> Microsoft.Maui.Controls.Image, count: 71

I can illustrate the issue in this test:

https://github.com/jonathanpeppers/maui/commit/bbea0597cd0d90e4f0a84445f4ae35445f553bb4

It passes on Windows & Android, but on iOS & Catalyst the list of logical children grows.

It appears to be due to this pattern:
```csharp
var newCollection = new ObservableCollection<string>();
collectionView.ItemsSource = newCollection;
foreach (var item in data)
{
    newCollection.Add(item);
}
```

If I change it to set `ItemsSource` *last*, it also works around this issue:
```csharp
var newCollection = new ObservableCollection<string>();
foreach (var item in data)
{
    newCollection.Add(item);
}
collectionView.ItemsSource = newCollection;
```

This version is *faster* anyway, but the issue seems to be related to the `CollectionChanged` event firing.

### Workarounds for Above Sample ###

* Set `ItemsSource` or data-bound properties last and do not rely as much on `CollectionChanged`
  * Example:
https://github.com/jonathanpeppers/nacompllo-MemoryLeakEverywhere/commit/117e3af065ee4b0c8c6245bb649a53680018180f
* We noticed the images in each row were quite large: larger than the area they occupy on screen. We recommend setting `BaseSize`, so that less memory is used for these images.
  * Example (I just chose a number):
https://github.com/jonathanpeppers/nacompllo-MemoryLeakEverywhere/commit/00a57aab9335b7bfdfaaa2839a19df3cfec1a747

**Comment by homeyf** [comment] 2024-01-04 08:54
This is a Memory leak issue, we tried to reproduce it with a user-provided project, and it took over an hour to run. But the memory
consumption is still less than 1GB, so it is marked as not reproduce.

**Closed** 2024-01-11 13:02 UTC
Labels: t/bug, p/1, area/perf 🏎️, partner/cat 😻, area/collectionview 📃, s/triaged, s/try-latest-version, memory-leak 💦
