### ISSUE TITLE
[iOS] Exception when adding Pin to Map control.

### ISSUE THREAD

**Issue by Robbert-jansen** [dotnet/maui#26459] opened 2024-12-07 19:07 UTC
### Description

When adding pins to the map control it throws an exception, this happens in my own code and also the sample code [here](https://github.com/dotnet/maui-samples/tree/main/9.0/UserInterface/Views/Map)
> System.ArgumentException: Pin must have a Label to be added to a map

### Steps to Reproduce

1. Run MapDemo sample on iOS
2. Select "Pins" or "Pins with data binding"
3. Immediate crash

### Version with bug

9.0.0 GA

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Affected platforms

I was *not* able test on other platforms

### Affected platform versions

iOS 18.1.1

### Did you find any workaround?

No

### Relevant log output

```shell
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk.net9.0_18.1/18.1.9163/tools/bin/mlaunch --devname "iPhone 15 Pro van UserName" --killdev com.companyname.workingwithmaps --launchdev /Users/UserName/Downloads/maui-samples-main/9.0/UserInterface/Views/Map/MapDemo/WorkingWithMaps/bin/Debug/net9.0-ios/ios-arm64/WorkingWithMaps.app --wait-for-unlock --argument=-connection-mode --argument=usb -sdk 15.0 --argument=-monodevelop-port --argument=10000 --setenv=__XAMARIN_DEBUG_PORT__=10000 --sdkroot /Applications/Xcode.app/Contents/Developer
The app 'com.companyname.workingwithmaps' launched with pid 39151
2024-12-07 19:59:27.927 WorkingWithMaps[39151:11728492] You've implemented -[<UIApplicationDelegate> application:performFetchWithCompletionHandler:], but you still need to add "fetch" to the list of your supported UIBackgroundModes in your Info.plist.
2024-12-07 19:59:33.570 WorkingWithMaps[39151:11728492] 
Unhandled Exception:
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentException: Pin must have a Label to be added to a map
   at Microsoft.Maui.Controls.Maps.Map.PinsOnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1[[Microsoft.Maui.Controls.Maps.Pin, Microsoft.Maui.Controls.Maps, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1[[Microsoft.Maui.Controls.Maps.Pin, Microsoft.Maui.Controls.Maps, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].OnCollectionChanged(NotifyCollectionChangedAction action, Object item, Int32 index)
   at System.Collections.ObjectModel.ObservableCollection`1[[Microsoft.Maui.Controls.Maps.Pin, Microsoft.Maui.Controls.Maps, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].InsertItem(Int32 index, Pin item)
   at System.Collections.ObjectModel.Collection`1[[Microsoft.Maui.Controls.Maps.Pin, Microsoft.Maui.Controls.Maps, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].Add(Pin item)
   at System.Object.InvokeStub_Collection`1.Add(Object , Span`1 )
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   --- End of inner exception stack trace ---
   at Microsoft.Maui.Controls.Xaml.ApplyPropertiesVisitor.SetPropertyValue(Object xamlelement, XmlName propertyName, Object value, Object rootElement, INode node, HydrationContext context, IXmlLineInfo lineInfo)
   at Microsoft.Maui.Controls.Xaml.ApplyPropertiesVisitor.Visit(ElementNode node, INode parentNode)
   at Microsoft.Maui.Controls.Xaml.ElementNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
   at Microsoft.Maui.Controls.Xaml.ElementNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
   at Microsoft.Maui.Controls.Xaml.ElementNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
   at Microsoft.Maui.Controls.Xaml.RootNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
   at Microsoft.Maui.Controls.Xaml.XamlLoader.Visit(RootNode rootnode, HydrationContext visitorContext, Boolean useDesignProperties)
   at Microsoft.Maui.Controls.Xaml.XamlLoader.Load(Object view, String xaml, Assembly rootAssembly, Boolean useDesignProperties)
   at Microsoft.Maui.Controls.Xaml.XamlLoade.rLoad(Object view, String xaml, Boolean useDesignProperties)
   at Microsoft.Maui.Controls.Xaml.XamlLoader.Load(Object view, Type callingType)
   at Microsoft.Maui.Controls.Xaml.Extensions.LoadFromXaml[PinPage](PinPage view, Type callingType)
   at WorkingWithMaps.Views.PinPage.InitializeComponent() in /Users/Username/Downloads/maui-samples-main/9.0/UserInterface/Views/Map/MapDemo/WorkingWithMaps/obj/Debug/net9.0-ios/ios-arm64/Microsoft.Maui.Controls.SourceGen/Microsoft.Maui.Controls.SourceGen.CodeBehindGenerator/Views_PinPage.xaml.sg.cs:line 27
   at WorkingWithMaps.Views.PinPage..ctor() in /Users/Username/Downloads/maui-samples-main/9.0/UserInterface/Views/Map/MapDemo/WorkingWithMaps/Views/PinPage.xaml.cs:line 9
   at System.Object.InvokeStub_PinPage..ctor(Object , Object , IntPtr* )
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   at System.RuntimeType.CreateInstanceMono(Boolean nonPublic, Boolean wrapExceptions)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at WorkingWithMaps.Views.MainPage.<.ctor>b__4_0(Type pageType) in /Users/Username/Downloads/maui-samples-main/9.0/UserInterface/Views/Map/MapDemo/WorkingWithMaps/Views/MainPage.xaml.cs:line 15
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Foundation.NSAsyncSynchronizationContextDispatcher.Apply() in /Users/builder/azdo/_work/5/s/xamarin-macios/src/Foundation/NSAction.cs:line 179
   at Foundation.NSAsyncSynchronizationContextDispatcher.__Registrar_Callbacks__.callback_953_Foundation_NSAsyncSynchronizationContextDispatcher_Apply(IntPtr pobj, IntPtr sel, IntPtr* exception_gchandle)
--- End of stack trace from previous location ---
   at ObjCRuntime.Runtime.ThrowException(IntPtr gchandle) in /Users/builder/azdo/_work/5/s/xamarin-macios/src/ObjCRuntime/Runtime.cs:line 2719
   at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName) in /Users/builder/azdo/_work/5/s/xamarin-macios/src/UIKit/UIApplication.cs:line 64
   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass) in /Users/builder/azdo/_work/5/s/xamarin-macios/src/UIKit/UIApplication.cs:line 96
   at WorkingWithMaps.Program.Main(String[] args) in /Users/Username/Downloads/maui-samples-main/9.0/UserInterface/Views/Map/MapDemo/WorkingWithMaps/Platforms/iOS/Program.cs:line 13
2024-12-07 19:59:33.573 WorkingWithMaps[39151:11728492] Unhandled managed exception: Exception has been thrown by the target of an invocation. (System.Reflection.TargetInvocationException)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   at System.RuntimeType.CreateInstanceMono(Boolean nonPublic, Boolean wrapExceptions)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at WorkingWithMaps.Views.MainPage.<.ctor>b__4_0(Type pageType) in /Users/Username/Downloads/maui-samples-main/9.0/UserInterface/Views/Map/MapDemo/WorkingWithMaps/Views/MainPage.xaml.cs:line 15
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Foundation.NSAsyncSynchronizationContextDispatcher.Apply() in /Users/builder/azdo/_work/5/s/xamarin-macios/src/Foundation/NSAction.cs:line 179
   at Foundation.NSAsyncSynchronizationContextDispatcher.__Registrar_Callbacks__.callback_953_Foundation_NSAsyncSynchronizationContextDispatcher_Apply(IntPtr pobj, IntPtr sel, IntPtr* exception_gchandle)
--- End of stack trace from previous location ---
   at ObjCRuntime.Runtime.ThrowException(IntPtr gchandle) in /Users/builder/azdo/_work/5/s/xamarin-macios/src/ObjCRuntime/Runtime.cs:line 2719
   at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName) in /Users/builder/azdo/_work/5/s/xamarin-macios/src/UIKit/UIApplication.cs:line 64
   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass) in /Users/builder/azdo/_work/5/s/xamarin-macios/src/UIKit/UIApplication.cs:line 96
   at WorkingWithMaps.Program.Main(String[] args) in /Users/Username/Downloads/maui-samples-main/9.0/UserInterface/Views/Map/MapDemo/WorkingWithMaps/Platforms/iOS/Program.cs:line 13
Exception has been thrown by the target of an invocation. (System.Reflection.TargetInvocationException)
   at Microsoft.Maui.Controls.Xaml.ApplyPropertiesVisitor.SetPropertyValue(Object xamlelement, XmlName propertyName, Object value, Object rootElement, INode node, HydrationContext context, IXmlLineInfo lineInfo)
   at Microsoft.Maui.Controls.Xaml.ApplyPropertiesVisitor.Visit(ElementNode node, INode parentNode)
   at Microsoft.Maui.Controls.Xaml.ElementNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
   at Microsoft.Maui.Controls.Xaml.ElementNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
   at Microsoft.Maui.Controls.Xaml.ElementNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
   at Microsoft.Maui.Controls.Xaml.RootNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
   at Microsoft.Maui.Controls.Xaml.XamlLoader.Visit(RootNode rootnode, HydrationContext visitorContext, Boolean useDesignProperties)
   at Microsoft.Maui.Controls.Xaml.XamlLoader.Load(Object view, String xaml, Assembly rootAssembly, Boolean useDesignProperties)
   at Microsoft.Maui.Controls.Xaml.XamlLoader.Load(Object view, String xaml, Boolean useDesignProperties)
   at Microsoft.Maui.Controls.Xaml.XamlLoader.Load(Object view, Type callingType)
   at Microsoft.Maui.Controls.Xaml.Extensions.LoadFromXaml[PinPage](PinPage view, Type callingType)
   at WorkingWithMaps.Views.PinPage.InitializeComponent() in /Users/Username/Downloads/maui-samples-main/9.0/UserInterface/Views/Map/MapDemo/WorkingWithMaps/obj/Debug/net9.0-ios/ios-arm64/Microsoft.Maui.Controls.SourceGen/Microsoft.Maui.Controls.SourceGen.CodeBehindGenerator/Views_PinPage.xaml.sg.cs:line 27
   at WorkingWithMaps.Views.PinPage..ctor() in /Users/Username/Downloads/maui-samples-main/9.0/UserInterface/Views/Map/MapDemo/WorkingWithMaps/Views/PinPage.xaml.cs:line 9
   at System.Object.InvokeStub_PinPage..ctor(Object , Object , IntPtr* )
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
Pin must have a Label to be added to a map (System.ArgumentException)
   at Microsoft.Maui.Controls.Maps.Map.PinsOnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1[[Microsoft.Maui.Controls.Maps.Pin, Microsoft.Maui.Controls.Maps, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1[[Microsoft.Maui.Controls.Maps.Pin, Microsoft.Maui.Controls.Maps, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].OnCollectionChanged(NotifyCollectionChangedAction action, Object item, Int32 index)
   at System.Collections.ObjectModel.ObservableCollection`1[[Microsoft.Maui.Controls.Maps.Pin, Microsoft.Maui.Controls.Maps, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].InsertItem(Int32 index, Pin item)
   at System.Collections.ObjectModel.Collection`1[[Microsoft.Maui.Controls.Maps.Pin, Microsoft.Maui.Controls.Maps, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].Add(Pin item)
   at System.Object.InvokeStub_Collection`1.Add(Object , Span`1 )
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)

=================================================================
	Native Crash Reporting
=================================================================
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

=================================================================
	Native stacktrace:
=================================================================
	0x103988c08 - /private/var/containers/Bundle/Application/748F40A0-8595-4010-B1BD-661790DF7265/WorkingWithMaps.app/WorkingWithMaps : mono_dump_native_crash_info
	0x1039731e4 - /private/var/containers/Bundle/Application/748F40A0-8595-4010-B1BD-661790DF7265/WorkingWithMaps.app/WorkingWithMaps : mono_handle_native_crash
	0x103ab1fa4 - /private/var/containers/Bundle/Application/748F40A0-8595-4010-B1BD-661790DF7265/WorkingWithMaps.app/WorkingWithMaps : sigabrt_signal_handler.cold.1
	0x10398851c - /private/var/containers/Bundle/Application/748F40A0-8595-4010-B1BD-661790DF7265/WorkingWithMaps.app/WorkingWithMaps : mono_runtime_setup_stat_profiler
	0x220850afc - /usr/lib/system/libsystem_platform.dylib : <redacted>
	0x220a1aef8 - /usr/lib/system/libsystem_pthread.dylib : pthread_kill
	0x1a029fad8 - /usr/lib/system/libsystem_c.dylib : abort
	0x10375fdbc - /private/var/containers/Bundle/Application/748F40A0-8595-4010-B1BD-661790DF7265/WorkingWithMaps.app/WorkingWithMaps : xamarin_find_protocol_wrapper_type
	0x1038bb540 - /private/var/containers/Bundle/Application/748F40A0-8595-4010-B1BD-661790DF7265/WorkingWithMaps.app/WorkingWithMaps : mono_invoke_unhandled_exception_hook
	0x10395d7bc - /private/var/containers/Bundle/Application/748F40A0-8595-4010-B1BD-661790DF7265/WorkingWithMaps.app/WorkingWithMaps : mono_jit_exec
	0x1037731fc - /private/var/containers/Bundle/Application/748F40A0-8595-4010-B1BD-661790DF7265/WorkingWithMaps.app/WorkingWithMaps : xamarin_main
	0x1039d1330 - /private/var/containers/Bundle/Application/748F40A0-8595-4010-B1BD-661790DF7265/WorkingWithMaps.app/WorkingWithMaps : main
	0x1bdeceec8 - /usr/lib/dyld : <redacted>

=================================================================
	Basic Fault Address Reporting
=================================================================
Memory around native instruction pointer (0x1e88ad1d4):0x1e88ad1c4  ff 0f 5f d6 c0 03 5f d6 10 29 80 d2 01 10 00 d4  .._..._..)......
0x1e88ad1d4  03 01 00 54 7f 23 03 d5 fd 7b bf a9 fd 03 00 91  ...T.#...{......
0x1e88ad1e4  31 ec ff 97 bf 03 00 91 fd 7b c1 a8 ff 0f 5f d6  1........{...._.
0x1e88ad1f4  c0 03 5f d6 10 27 80 d2 01 10 00 d4 03 01 00 54  .._..'.........T

=================================================================
	Managed Stacktrace:
=================================================================
=================================================================
```

**Comment by jfversluis** [comment] 2024-12-09 10:15
Can't reproduce with the sample app, so I'm going to need some more info or some reproduction

<img src="https://github.com/user-attachments/assets/21eef3ae-a93a-4750-984a-4740bd809881" width="300px"/>

**Comment by Robbert-jansen** [comment] 2024-12-09 11:02
Okay this is weird, yesterday both "Pins" and "Pins with data binding" but now only "Pins" crashes?
I've just tried it on multiple simulators (both iOS 18.0 and 18.1) and it does the same thing.

![Image](https://github.com/user-attachments/assets/33628419-97f8-495b-b573-f2781172dbf0)

https://github.com/user-attachments/assets/1aef67fd-7a14-42e2-9a50-ec7351f0fe20
https://github.com/user-attachments/assets/e13ec17a-9385-425b-9f96-ad0681bf5acd

**Comment by jfversluis** [comment] 2024-12-09 14:38
Hm I thought I tried the Pins page one but that is crashing for me now too. 
In the `PinPage.xaml` could you add a `Label` property with a value in the XAML there? Because that seems to fix it for me, which mostly means an error in the sample and not so much the Maps SDK

**Comment by Robbert-jansen** [comment] 2024-12-09 15:40
Okay that change does fix this issue, but seems like there still is something to fix, because that same code worked just fine in .NET 8?

As to the other page also crashing yesterday, that just seems to have magically fixed itself, this also includes my own project which I had to downgrade to .NET 8 but works fine in .NET 9 now.

**Comment by jfversluis** [comment] 2024-12-09 18:40
> Okay that change does fix this issue, but seems like there still is something to fix, because that same code worked just fine in .NET 8?
> 
> As to the other page also crashing yesterday, that just seems to have magically fixed itself, this also includes my own project which I had to downgrade to .NET 8 but works fine in .NET 9 now.

For as far as I know this has always been the case. Even in Xamarin.Forms this [exception was thrown](https://github.com/xamarin/Xamarin.Forms/blob/2f8f4864a4d289dc89a6228e2ca9d6a49993e365/Xamarin.Forms.Maps/Map.cs#L160). So not sure why it has worked earlier for you, but until you can give me a reproduction, I'm leaning towards: works as intended :)

**Comment by MichelePannacciTerex** [comment] 2024-12-09 22:16
> > Okay that change does fix this issue, but seems like there still is something to fix, because that same code worked just fine in .NET 8?
> > As to the other page also crashing yesterday, that just seems to have magically fixed itself, this also includes my own project which I had to downgrade to .NET 8 but works fine in .NET 9 now.
> 
> For as far as I know this has always been the case. Even in Xamarin.Forms this [exception was thrown](https://github.com/xamarin/Xamarin.Forms/blob/2f8f4864a4d289dc89a6228e2ca9d6a49993e365/Xamarin.Forms.Maps/Map.cs#L160). So not sure why it has worked earlier for you, but until you can give me a reproduction, I'm leaning towards: works as intended :)

If I may butt in on the conversation maybe a more logical solution would be to throw a System.ArgumentException inside the Pin's  constructor instead of in the map control. Or on both.

**Comment by MichelePannacciTerex** [comment] 2024-12-09 22:20
> > Okay that change does fix this issue, but seems like there still is something to fix, because that same code worked just fine in .NET 8?
> > As to the other page also crashing yesterday, that just seems to have magically fixed itself, this also includes my own project which I had to downgrade to .NET 8 but works fine in .NET 9 now.
> 
> For as far as I know this has always been the case. Even in Xamarin.Forms this [exception was thrown](https://github.com/xamarin/Xamarin.Forms/blob/2f8f4864a4d289dc89a6228e2ca9d6a49993e365/Xamarin.Forms.Maps/Map.cs#L160). So not sure why it has worked earlier for you, but until you can give me a reproduction, I'm leaning towards: works as intended :)

`		public string Label
		{
			get { return (string)GetValue(LabelProperty); }
			set 
                       { 
                               // (if value is null) throw 
                               SetValue(LabelProperty, value); 
                               // or
                               SetValue(LabelProperty, value ?? "Unknown");
                       }
		}`

**Comment by jfversluis** [comment] 2024-12-10 09:25
> or give a fall back value, just to not crash the entire app...

If I remember correctly, iOS will crash if there is a empty string (or null value) in there. So if we don't crash the app, iOS will and with a much less clear error message.

Maybe it would be better to do it in the Pin itself, maybe there is a reason we didn't do that. It's been like this for so long I can't remember and I don't think it matters that much though because that will only make the crash happen slightly earlier.

I'm closing this one for now. If you come up with a reproduction where a Pin has a Label and it still crashes I'd be happy to see it and work on it. Let me know when you get it :)

Thanks all!

**Closed by jfversluis** 2024-12-10 09:25 UTC
Labels: t/bug, platform/iOS 🍎, area-controls-map, s/needs-attention
