### ISSUE TITLE
After updating Windows 10, Windows can no longer manage any appx packages, and I can't deploy WinUI 3 apps from VS

### ISSUE THREAD

**Issue by Transis-Felipe** [dotnet/maui#25832] opened 2024-11-13 14:35 UTC
### .NET MAUI Team notes

This issue isn't related to .NET MAUI or .NET9. 

You can follow the WinUI issue [here](https://github.com/microsoft/WindowsAppSDK/issues/4881)

Workaround posted here

https://github.com/microsoft/WindowsAppSDK/issues/4881#issuecomment-2480939942

One thing to clarify here is that .NET 9 MAUI does depend on a 1.6.2 version of WinAppSDK but the version of WinAppSDK we are using for .NET9 depends on the 1.6.1 runtime which doesn't have this issue. Once the 1.6.3 version of the WinAppSDK is released, updating to that will not fix anything.

### Original Description

Can't deploy MAUI projects to windows after upgrade to .net 9

DEP0900: Failed to unregister application "0acbd622-c89e-4564-8e05-7fcba762c402_1.0.0.64_x64__9zz4h110yvjzm". [0x80073CFA]

### Steps to Reproduce

1) Create a project
2) Build the project
3) Deploy to Windows Machine (Windows 10 in my case)
![Image](https://github.com/user-attachments/assets/ceb3af29-de10-480c-b2db-949e5eb28c4e)

4) Error
![Image](https://github.com/user-attachments/assets/7a345b98-e28e-428a-aaef-d6cb2b69816e)

Powershell can't also remove the windows store app

![Image](https://github.com/user-attachments/assets/f141cf08-d3ae-4397-9108-74ddc1328162)

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Affected platforms

Windows

### Did you find any workaround?

https://github.com/microsoft/WindowsAppSDK/issues/4881#issuecomment-2480939942

### Relevant log output

```shell

```

### Depends on
- [ ] https://github.com/microsoft/WindowsAppSDK/issues/4881

**Comment by sbwalker** [comment] 2024-11-14 00:20
I am experiencing the same problem with the official .NET 9 release - whereas the application worked fine on the .NET 9 RC2 release (which I thought was the point of testing with the RC releases ie. to identify any potential issues).
 
Running the application results in:

![Image](https://github.com/user-attachments/assets/a157939f-e00d-4c2d-9959-613d79620d3f)

However the Configuration is already set to Deploy:

![Image](https://github.com/user-attachments/assets/bc0d8593-1fc5-4bc1-a29b-4f201ca38fad)

Build / Deploy Solution results in: 
DEP0900: Failed to unregister application "0E29FC31-1B83-48ED-B6E0-9F3C67B775D4_6.0.0.1_x64__9zz4h110yvjzm". [0x80073CFA]

**Comment by sbwalker** [comment] 2024-11-14 01:40
@Transis-Felipe I was able to resolve my problem by modifying my *.csproj and adding to PropertyGroup: 

```
 <!-- To develop, package, and publish an app to the Microsoft Store, see: https://aka.ms/MauiTemplateUnpackaged -->
    <WindowsPackageType>None</WindowsPackageType>
```

and modifying launchSettings.json to:

```
{
  "profiles": {
    "Windows Machine": {
      "commandName": "Project",
      "nativeDebugging": false
    }
  }
```

I then did a Solution Clean and Solution Rebuild.

**Comment by mwilson25** [comment] 2024-11-14 03:12
Thank you - this seemed to do the trick for me also. However, I still have the version of the app installed before this problem occurred and i cannot remove the package (Powershell: Remove-AppXPackage) or uninstall the app. I tried my project on another "clean" development computer and all is well without your changes, so this points to the "jammed package" being the problem.

**Comment by ehoward0018** [comment] 2024-11-14 04:49
This is happening to us as well. It appears to only be a problem for Windows 10 as far as I can tell, and most likely comes from the latest Windows update as we did not update our Visual Studio Version but it still doesn't allow us to uninstall those packages.

**Comment by Xo3-ToBapbl** [comment] 2024-11-14 09:01
Can confirm @ehoward0018 message. All our devs with win10 22H2 machines faced with this issue. No problems for devs with win11 23H2 and above.

Important note: we did not update our app to .NET9.

Potential workaround might be to run System File Checker tool from CMD: _sfc /scannow_, then restart your machine and debugging will be fixed.

**Comment by TobiasJoergensen** [comment] 2024-11-14 12:51
Same issue. 22H2 and 19060.1000.0.

**Comment by sbwalker** [comment] 2024-11-14 12:51
I can confirm I am running Windows 10 as well

**Comment by ivanjx** [comment] 2024-11-14 13:26
@Xo3-ToBapbl `sfc /scannow` and restarting does not work. i guess im going to need to install win11.

**Comment by Mzazvor** [comment] 2024-11-14 13:56
I did manage to upgrade my project to .net 9. It worked for a while and then got stucked  with DEP0900. I cant even uninstall the old maui programs that i still have in my PC using windows remove program feature. I have win 10.

**Comment by S4nt1ag0** [comment] 2024-11-14 15:05
> [@Transis-Felipe](https://github.com/Transis-Felipe) I was able to resolve my problem by modifying PropertyGroup in my *.csproj
> 
> removing:
> 
> ```
> <ApplicationIdGuid>0E29FC31-1B83-48ED-B6E0-9F3C67B775D4</ApplicationIdGuid>
> ```
> 
> adding :
> 
> ```
>  
>     <WindowsPackageType>None</WindowsPackageType>
> ```
> 
> and modifying launchSettings.json to:
> 
> ```
> {
>   "profiles": {
>     "Windows Machine": {
>       "commandName": "Project",
>       "nativeDebugging": false
>     }
>   }
> }
> ```
> 
> I then did a Solution Clean and Solution Rebuild.
> 
> (I identified these changes after reviewing a new .NET MAUI project that I created in .NET 9)

Same problem here, when i apply this changes i got this error: 
O programa "[2760] MyProgram.exe" foi fechado com o código 3221226356 (0xc0000374).

**Comment by robertbrestle** [comment] 2024-11-14 19:06
I'm also seeing the same issue for both .NET 8 and .NET 9 on Windows 10. Below is some of my troubleshooting.

When attempting to uninstall through settings, we get the following error:
![Image](https://github.com/user-attachments/assets/4f9e798b-097c-477a-abee-2d0e2026783a)

When attempting to debug, we get the same error with more details:
```
Unregistering application EAEA399A-B96B-4688-A8A8-2925B58E11FF_2.4.3.7_x64__0p9bedgggxnzg, architecture 9...
Registering UWP app with manifest: C:\Users\rbrestle\RiderProjects\PROJECT\PROJECT\bin\Debug\net8.0-windows10.0.19041.0\win10-x64\AppX\AppxManifest.xml arch X64...
Register application failed return code is 1.
STDERR: ERROR: The asynchronous operation was failed: Install failed. Please contact your software vendor (hresult_error:80073CF9)[location] = Z:\BuildAgent\work\efa2be849acae02a\dotnet\Rider\Native\Solution\winrt_launcher\src\utility.hpp(41)[function] = void __cdecl jbrs::wait_for_finished(const struct winrt::com_ptr<struct IAsyncInfo> &)[uri] = C:\Users\rbrestle\RiderProjects\PROJECT\PROJECT\bin\Debug\net8.0-windows10.0.19041.0\win10-x64\AppX\AppxManifest.xml
```

Trying to uninstall with AppX powershell module results in the same error:
```
PS C:\Windows\System32> Remove-AppxPackage -Package EAEA399A-B96B-4688-A8A8-2925B58E11FF_2.4.3.7_x64__0p9bedgggxnzg
Remove-AppxPackage: Deployment failed with HRESULT: 0x80073CFA, Removal failed. Please contact your software vendor. (Exception from HRESULT: 0x80073CFA)

NOTE: For additional information, look for [ActivityId] 6d0e6d58-35ec-000c-e207-276dec35db01 in the Event Log or use the command line Get-AppPackageLog -ActivityID 6d0e6d58-35ec-000c-e207-276dec35db01
```

With the Activity log output returning nothing:
```
PS C:\Windows\System32> Get-AppPackageLog -ActivityID 6d0e6d58-35ec-000c-e207-276dec35db01

Time                      ID           Message
----                      --           -------


PS C:\Windows\System32>
```

But the event viewer is showing a crash:
```
Fault bucket , type 0
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: svchost.exe_AppXSvc
P2: 10.0.19041.4355
P3: 9ce47784
P4: appxdeploymentserver.dll
P5: 10.0.19041.5007
P6: 738541ef
P7: c0000005
P8: 00000000001fcceb
P9: 
P10: 
```

&nbsp;

The suggested changes from @sbwalker result in the following error when building, though this may be due to legacy settings and other project configurations.
`Could not load appxrecipe from $C:\Users\rbrestle\RiderProjects\PROJECT\PROJECT\bin\Debug\net8.0-windows10.0.19041.0\win10-x64\PROJECT.build.appxrecipe`

&nbsp;

Running `sfc /scannow` and restarting has also not helped. Checking the logs, it looks like there are issues with AppX:
```
2024-11-14 12:46:39, Info                  CSI    00000058 [SR] Beginning Verify and Repair transaction
2024-11-14 12:46:40, Info                  CSI    00000059 Hashes for file member [l:12]'settings.dat' do not match.
 Expected: {l:32 ml:33 b:7fbb3e503ed8a4a8e5d5fab601883cbb31d2e06d6b598460e570fb7a763ee555}.
 Actual: {l:32 b:d20b3374b66ac063c7554139d9addfee89ae1c7e739827f0b47f5a0edec43303}.
2024-11-14 12:46:40, Info                  CSI    0000005a [SR] Cannot repair member file [l:12]'settings.dat' of Microsoft-Windows-AppX-Deployment-Server, version 10.0.19041.5007, arch amd64, nonSxS, pkt {l:8 b:31bf3856ad364e35} in the store, hash mismatch
2024-11-14 12:46:40, Info                  CSI    0000005b Hashes for file member [l:12]'settings.dat' do not match.
 Expected: {l:32 ml:33 b:7fbb3e503ed8a4a8e5d5fab601883cbb31d2e06d6b598460e570fb7a763ee555}.
 Actual: {l:32 b:d20b3374b66ac063c7554139d9addfee89ae1c7e739827f0b47f5a0edec43303}.
2024-11-14 12:46:40, Info                  CSI    0000005c [SR] Cannot repair member file [l:12]'settings.dat' of Microsoft-Windows-AppX-Deployment-Server, version 10.0.19041.5007, arch amd64, nonSxS, pkt {l:8 b:31bf3856ad364e35} in the store, hash mismatch
2024-11-14 12:46:40, Info                  CSI    0000005d [SR] This component was referenced by [l:159]'Microsoft-Windows-Client-Desktop-Required-Package05110~31bf3856ad364e35~amd64~~10.0.19041.5007.1B99FCA95115E653F7DCDF5AC5D370CDEDBD0E3471303C0BF42B8199A6BDAF29'
2024-11-14 12:46:40, Info                  CSI    0000005e Hashes for file member [l:12]'settings.dat' do not match.
 Expected: {l:32 ml:33 b:7fbb3e503ed8a4a8e5d5fab601883cbb31d2e06d6b598460e570fb7a763ee555}.
 Actual: {l:32 b:d20b3374b66ac063c7554139d9addfee89ae1c7e739827f0b47f5a0edec43303}.
2024-11-14 12:46:40, Info                  CSI    0000005f Hashes for file member [l:12]'settings.dat' do not match.
 Expected: {l:32 ml:33 b:7fbb3e503ed8a4a8e5d5fab601883cbb31d2e06d6b598460e570fb7a763ee555}.
 Actual: {l:32 b:d20b3374b66ac063c7554139d9addfee89ae1c7e739827f0b47f5a0edec43303}.
2024-11-14 12:46:40, Info                  CSI    00000060 [SR] Could not reproject corrupted file \??\C:\Windows\System32\\settings.dat; source file in store is also corrupted
```

&nbsp;

I'm doing some testing with Windows 11, but any other information to fix this on Windows 10 would be extremely helpful.

**Comment by mwilson25** [comment] 2024-11-14 23:47
I am on Win 10 also and have had the same experience as all of you. I would say Microsoft owes us a fix as MAUI should work on WIN 10. Do we have to report it directly to them?

**Comment by elTRexx** [comment] 2024-11-15 00:25
Same issue since yesterday. Made me a little mad. 
And it happen from "nowwhere". I mean I was coding my testing MAUI app, running some test switching between android emulator and windows machine, and then hit this issue while it was working just few minutes ago ! 
For the record here is what I tried, without any success.

So I suspected I broke something by switching on and off from android to windows platform, finally end up saw that it was related with the Microsoft app store, and also removing application from settings failed too, and also with powershell as admin.

Trying toubleshooter wizard from Settings for app store. 
I end up re enabling Microsoft store running in background and as the troubleshooter told me that it was related to the BITS service I re enabled from services to run automatically. But it didn't work out.

I also decided to uninstall completely Visual Studio, reinstall it, creating a new default MAUI project. 
It was targeting .Net 9 and it worked this time. So I tried to create yet another default MAUI project, but targeting .Net 8 instead. And I came back to the same issue again !

I finally tried to edit Package.appxmanifest in Visual Studio : Changing the package Name as I saw on internet maybe the error is related to the name of the package and / or it version detected to be a downgrade (so I increased the version number). But none worked out.

**Comment by TobiasJoergensen** [comment] 2024-11-15 08:38
Just to further confirm it is a win10 related issue. I was lucky to be in my win11 enrollment process, and after upgrading last night I can now build again.

**Comment by TobiasJoergensen** [comment] 2024-11-15 09:28
> _"Just to further confirm it is a win10 related issue. I was lucky to be in my win11 enrollment process, and after upgrading last night I can now build again."_
> 
> Hi Tobias, does that mean that updating a "broken" system to Windows 11 "fixes" the problem? Thanks, Henrik

Hi Henrik,
Yes, that was the case for me. I was seeing the DEP0900 yesterday before updating to Windows 11. Now today I have had no issues after upgrading to windows 11.
Does not seem like a good fix, but at least it is a work around for those able.

**Comment by Xo3-ToBapbl** [comment] 2024-11-15 11:10
> We have a similar problem when deploying our apps to W10 clients. As a workaround we are doing tests by adding a `global.json` in the root of the project (next to the solution file) with the following content:
> 
> {
>     "sdk": {
>         "version": "8.0.306"
>     }
> }
> Currently we are assuming that the bug in regard to W10 seems introduced on the 12th of November in the latest .NET 8.0 release (8.0.11) with in our case SDK 8.0.307. The `global.json` forces a specific SDK version to be used (in our case; the build server), with which we had no problems in the past. I will update my comment with our findings, might be worth a try.
> 
> **EDIT:** It seems that when we build our app using the older SDK (8.0.306) we are no longer facing problems when uninstalling/unregistering/updating on freshly installed W10 clients.

Thank for your investigation! I want to clarify: are you sure that your clients with freshly installed win10 have latest updates (KB5046613)? We have no issues with users on win10 without latest updates.

**Comment by R-zr** [comment] 2024-11-15 11:21
> > We have a similar problem when deploying our apps to W10 clients. As a workaround we are doing tests by adding a `global.json` in the root of the project (next to the solution file) with the following content:
> > {
> > "sdk": {
> > "version": "8.0.306"
> > }
> > }
> > Currently we are assuming that the bug in regard to W10 seems introduced on the 12th of November in the latest .NET 8.0 release (8.0.11) with in our case SDK 8.0.307. The `global.json` forces a specific SDK version to be used (in our case; the build server), with which we had no problems in the past. I will update my comment with our findings, might be worth a try.
> > **EDIT:** It seems that when we build our app using the older SDK (8.0.306) we are no longer facing problems when uninstalling/unregistering/updating on freshly installed W10 clients.
> 
> Thank for your investigation! I want to clarify: are you sure that your clients with freshly installed win10 have latest updates (KB5046613)? We have no issues with users on win10 without latest updates.

I can confirm that KB5046613 is installed via Windows Update earlier this week (12th November). Our clients are running a up-to-date `Windows 10 IoT Enterprise LTSC 2021` (21H2) for what it's worth.

**Comment by skyclasher** [comment] 2024-11-15 12:20
We encounter a similar issue when trying to update or remove our application, regardless of whether we use the `.msix` installer or the PowerShell script `install.ps1`.

Building with SDK version `8.0.306` did not resolve the issue for us.
We are using Windows 10 with `KB5046613` installed.

Error log excerpt:
```
11/15/2024 8:05:46 PM     605          The last successful state reached was MachineRegisterRemove. Failure occurred
                                       before reaching the next state De-Indexed. hr: 0x8007139F
11/15/2024 8:05:46 PM     300          error 0x8007139F: Cannot register the
                                       CentricSoftTechSdn.Bhd.Centric-POS_69aszxhse8awm package due to the following
                                       error: The group or resource is not in the correct state to perform the
                                       requested operation.
```

**Comment by truecrimson** [comment] 2024-11-15 14:19
Same issue for us using .NET 8 and Windows 10. Removing the latest Windows updates has been a temporary fix for us.

**Comment by dillonricketts** [comment] 2024-11-15 18:52
I had this issue with .NET 8 and Windows 10 22H2 19060.1000.0. Upgrading to Windows 11 was unfortunately the only thing that worked. No code/config changes.

**Comment by SubdudedCrane651** [comment] 2024-11-15 19:11
Fix frustrating bug with visual studio in Windows 10 after update

 
    <WindowsPackageType>None</WindowsPackageType>
and modifying launchSettings.json to:

{
  "profiles": {
    "Windows Machine": {
      "commandName": "Project",
      "nativeDebugging": false
    }
  }
}
I then did a Solution Clean and Solution Rebuild.

Worked for me after reinstalling Visual Studio. Another thing I did was clone my git before for each project. After which I was able to run windows, and create Android and iOS apps with ease. I can use NET 8 which suites me fine.

**Comment by robertbrestle** [comment] 2024-11-15 19:51
As with @skyclasher, changing the SDK version to anything older than `8.0.404` did not change the result.

With my troubleshooting from yesterday, I was on the following version, which did not include `KB5046613`:
```
Windows 10 Pro 22H2 Build 19045.5011
Windows Feature Experience Pack 1000.19060.1000.0
```

After updating to build 19045.5131 (with `KB5046613`), the error persists.

Thank you @davidortinau for linking the WindowsAppSDK issue!

**Comment by Dopamax** [comment] 2024-11-15 20:45
> [@Transis-Felipe](https://github.com/Transis-Felipe) I was able to resolve my problem by modifying PropertyGroup in my *.csproj
> 
> removing:
> 
> ```
> <ApplicationIdGuid>0E29FC31-1B83-48ED-B6E0-9F3C67B775D4</ApplicationIdGuid>
> ```
> 
> adding :
> 
> ```
>  
>     <WindowsPackageType>None</WindowsPackageType>
> ```
> 
> and modifying launchSettings.json to:
> 
> ```
> {
>   "profiles": {
>     "Windows Machine": {
>       "commandName": "Project",
>       "nativeDebugging": false
>     }
>   }
> }
> ```
> 
> I then did a Solution Clean and Solution Rebuild.
> 
> (I identified these changes after reviewing a new .NET MAUI project that I created in .NET 9)

This solution doen't allow debugging

**Comment by sbwalker** [comment] 2024-11-15 20:48
@Dopamax interesting... as those are the configurations which are specified in the new .NET MAUI Blazor Hybrid Project template in .NET 9:

![Image](https://github.com/user-attachments/assets/09980ff2-dd10-4a4a-9d53-8ef543d0da9e)

**Comment by Dopamax** [comment] 2024-11-15 21:04
> [@Dopamax](https://github.com/Dopamax) interesting... as those are the configurations which are specified in the new .NET MAUI Blazor Hybrid App project template in .NET 9:
> 
> ![Image](https://github.com/user-attachments/assets/09980ff2-dd10-4a4a-9d53-8ef543d0da9e)

I'm on .NET 8, but I suppose it's the same problem, because of it depends on uninstalling the app

![Image](https://github.com/user-attachments/assets/811814fd-10fc-4a27-be66-92313dd54f38)

**Comment by manada02** [comment] 2024-11-15 21:06
and I thought that I am only one I cant uninstall that fck app and I tried every method

**Comment by King-Taz** [comment] 2024-11-15 23:44
Put me down for "having the same issues". Can't uninstall any app created before update either. Not wanting to update to Win11 but may have to.

**Comment by scheenkbgates87** [comment] 2024-11-16 00:56
Can confirm: 
- Rolling back update does not fix
- - SFC /scannow and restart does not work

**Comment by simon-rossmann-minesservice** [comment] 2024-11-16 01:23
Same problem, no way to start my project either. 3rd Party Installers don't work either, since they do not even list the maui app as installed ...
This needs a fix asap imho

**Comment by TPLindley** [comment] 2024-11-16 05:49
Having same issue, wondering if there are any updates?

**Comment by King-Taz** [comment] 2024-11-16 06:10
> Having same issue, wondering if there are any updates?

Installing/updating to Win11 appears to be the only fix for now.

**Comment by DvoracekMartin** [comment] 2024-11-16 08:36
Can confirm that updating to Win11 fixes the issue.

**Comment by simon-rossmann-minesservice** [comment] 2024-11-16 11:53
Sorry, but changing Operating Systems can hardly be called a fix. Since i updated both, visual Studio and Windows at the same time, i am not sure which update broke the system. But i can't work right now and i doubt, any other maui developer can

**Comment by King-Taz** [comment] 2024-11-16 17:29
Can also confirm that updating to Win11 fixes issue

**Comment by PureWeen** [comment] 2024-11-17 18:35
Workaround posted here

https://github.com/microsoft/WindowsAppSDK/issues/4881#issuecomment-2480939942

One thing to clarify here is that .NET 9 MAUI does depend on a 1.6.2 version of WinAppSDK but the version of WinAppSDK we are using for .NET9 depends on the 1.6.1 runtime which doesn't have this issue. Once the 1.6.3 version of the WinAppSDK is released, updating to that will not fix anything.

**Comment by lbegue** [comment] 2024-11-18 00:35
I can confirm that that workaround [https://github.com/microsoft/WindowsAppSDK/issues/4881#issuecomment-2480939942](url) worked for me in Windows 10.
I had tried everything and I was desperate. Thank you.
Now my MAUI application is deploying without problems and I have been able to uninstall the old applications that were impossible to remove before appliying the workaround.

**Comment by King-Taz** [comment] 2024-11-18 09:45
I upgraded to win11 and that allowed me to unregister older apps and continue coding. However, I'm now unable to deploy new Maui projects. The Deploy checkbox in VS configuration manager is grayed out. Can anyone duplicate this? I simply used either of the default maui demos (button clicker and task manager). I don't think I missed any settings anywhere, but am unsure.

**Comment by mattleibow** [comment] 2024-11-18 12:27
Adding the issue to the "backlog" simply because the system demands that I put it somewhere. We are most likely not able to action on this and will have to wait for a fix to roll out to the OS/update/Store.

**Comment by King-Taz** [comment] 2024-11-18 18:09
I'm not sure what causes this error. I can create new maui apps using net8 which can be deployed.
![Image](https://github.com/user-attachments/assets/5a9d537e-e9cb-4bc7-bdc9-2c9f7fd6d9b6)

Doing the exact same using net9, app cannot be deployed (deploy box grayed out).
![Image](https://github.com/user-attachments/assets/1dd73ff1-1695-4a1e-8659-93335972c010)

**Comment by SubdudedCrane651** [comment] 2024-11-18 21:11
Don’t use Regedit could cause some problems with the system use 

 

First upgrade Visual Studio then

 

Add this to the .csproj of the project

<WindowsPackageType>None</WindowsPackageType>

 

In the 

and modifying launchSettings.json to:

 

{

  "profiles": {

    "Windows Machine": {

      "commandName": "Project",

      "nativeDebugging": false

    }

  }

}

 

Works like a charm for all projects where I can run Windows and compile in Android and iOS with ease.

**Comment by King-Taz** [comment] 2024-11-19 00:28
> and compile in Android and iOS with ease

Compiling in Android and iOS was never the issue though.

**Comment by amosekr** [comment] 2024-11-19 11:36
> {
>   "profiles": {
>     "Windows Machine": {
>       "commandName": "Project",
>       "nativeDebugging": false
>     }
>   }
> }

I am also facing the same problem, It works. Thanks

**Comment by DrJim106** [comment] 2024-11-20 23:44
Facing the same issue with my machine with Windows 22H2 /Win 10. I think the latest update is the root cause of this problem. All I can say is "what a goddamn problem is this" .lmao

**Comment by GeoSaffer** [comment] 2024-11-21 10:59
I can Confirm that the following link work perfectly for me

https://github.com/microsoft/WindowsAppSDK/issues/4881#issuecomment-2489961411

then reboot and BONUS !!!!, I was able to deploy again

**Comment by Dopamax** [comment] 2024-11-21 16:01
> I can Confirm that the following link work perfectly for me
> 
> [microsoft/WindowsAppSDK#4881 (comment)](https://github.com/microsoft/WindowsAppSDK/issues/4881#issuecomment-2489961411)
> 
> then reboot and BONUS !!!!, I was able to deploy again

@GeoSaffer Thanks, it worked for me too.

**Comment by PureWeen** [comment] 2024-11-21 21:49
https://learn.microsoft.com/en-us/windows/release-health/resolved-issues-windows-10-22h2#3447msgdesc

**Closed by PureWeen** 2024-11-21 21:49 UTC
Labels: t/bug, platform/windows 🪟, partner/winui, partner/cat 😻, area-setup, blocked, s/triaged, external

**Comment by King-Taz** [comment] 2024-11-21 21:51
This did not work for me


> I can Confirm that the following link work perfectly for me
> 
> [microsoft/WindowsAppSDK#4881 (comment)](https://github.com/microsoft/WindowsAppSDK/issues/4881#issuecomment-2489961411)
> 
> then reboot and BONUS !!!!, I was able to deploy again

**Comment by ehoward0018** [comment] 2024-11-22 20:33
While I understand that the post at the top is stating that this is not a .net Maui issue, and clearly it WAS a WinUI issue, if 
the entire Windows .net Maui ecosystem can be taken down by utilizing the .msix packages (including live apps) then perhaps having .msix as the default build and publishing mode could be considered to be changed.

That lack of instability made us instantly move to other options than MSIX as Windows apps completely ceased to function for almost a week.

**Comment by King-Taz** [comment] 2024-11-22 20:50
> That lack of instability made us instantly move to other options than MSIX as Windows apps completely ceased to function for almost a week.

In principle, MSIX has certain benefits. The only work-around I could find was to create the maui app using net8 and manually upgrade to net9 in the project file. Doing that, the deploy option was no longer grayed out in VS configuration manager and everything apparently works, at least locally anyway. I have not tried store deployment though and that may not work at all. What a mess!

**Comment by twojnarowski** [comment] 2024-11-27 20:40
I had the same issue, tried updating VS, doing all things suggested here and other places, somehow change that I could uninstall the apps without error, but then I couldn't launch MAUI app from VS. Finally downloading WinAppSDK and installing helped:
https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/downloads
