### ISSUE TITLE
Debugger not debugging some variables correctly

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#7009] opened 2022-05-10 23:28 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Debugger-not-debugging-some-variables-co/10033553)._

---
Testing with a MAUI RC2 project in VS4Mac 2022 Preview (build 8754)

Simply in the MainPage class I am trying to debug the result of `bleService.GetPlatform()`. This should be a string of android, ios or windows.

If I hover over this variable to have the IDE tell me what it is it says it is null. This is also confirmed in the locals pane. However when I output the variable (as I do in the line above) I can see from the output panel that the variable is ios as expected.

Screenshot of it not working:  
![Screen Shot 2022-05-07 at 5.41.54 pm.png](https://aka.ms/dc/image?name=B43771d622e254adf8fa84e618f305bcb637875065690238954_Screen_Shot_2022-05-07_at_5.41.54_pm.png&tid=43771d622e254adf8fa84e618f305bcb637875065690238954)

Sample project I was using.  
[OpenOWDiag.zip](https://aka.ms/dc/file?name=B9c5feeae8a61475a9a9eac74a9389c2e637875065316111750_OpenOWDiag.zip&tid=9c5feeae8a61475a9a9eac74a9389c2e637875065316111750)

In this sample I was targeting a macOS build. In this specific case I am expecting my result to be ios even though this is macOS. However I don’t expect this to be the cause of the problem. I also tested to iOS simulator (I did need to delete iOS/BLEService.cs to build). Debugging on an Android phone worked as expected.

---
#### Feedback Bot on 5/7/2022, 02:04 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by beeradmoore** [comment] 2022-05-10 23:34
I don't know why this was moved here, I thought it was a IDE bug but I guess not. 

That missing screenshot is this: 
![Screen Shot 2022-05-07 at 5 41 54 pm](https://user-images.githubusercontent.com/904737/167741187-d41fb6f2-67cf-4392-a346-f12ed709372a.png)

**Comment by PureWeen** [comment] 2022-05-11 18:04
@mauroa

**Comment by drasticactions** [comment] 2022-05-12 01:17
I would be surprised if this was specific to MAUI. It really does feel like a Platform bug. We should be able to reproduce this in a new iOS or Android app and just break in there.

**Comment by beeradmoore** [comment] 2022-05-12 02:26
I tried to repro it with new Xamarin.iOS and Xamarin.Mac projects and it works fine. However these projects are not running net6.0-ios and net6.0-maccatalyst. I don't know if we can make dedicated iOS and macOS projects that target these to try repro it that way.

[WillItDebugiOS.zip](https://github.com/dotnet/maui/files/8674541/WillItDebugiOS.zip)

[WillItDebugMacOS.zip](https://github.com/dotnet/maui/files/8674542/WillItDebugMacOS.zip)

**Comment by drasticactions** [comment] 2022-05-12 13:46
@beeradmoore You can create net6.0-ios and net6.0-maccatalyst apps separately of MAUI. They should appear in the Visual Studio template list, or you can make them in CLI with

`dotnet new ios` or `dotnet new maccatalyst`

You may need to install the workloads for them with `dotnet workload install ios maccatalyst`

**Comment by beeradmoore** [comment] 2022-05-12 23:02
I re-did the test with `dotnet new` , and I also changed `MyService` to be a partial class made up of files from 2 files. Unable to reproduce with it.

[WillItDebugiOSNet6.zip](https://github.com/dotnet/maui/files/8682997/WillItDebugiOSNet6.zip)

[WillItDebugMacOSNet6.zip](https://github.com/dotnet/maui/files/8682999/WillItDebugMacOSNet6.zip)

**Comment by beeradmoore** [comment] 2022-05-24 01:43
Just quietly bumping this and confirming with latest MAUI and VS Preview that shipped today (both GA) this is still broken. Is there any way we can either confirm its a MAUI problem so it can be handled at some point or reject that theory and send it back to the IDE (or dotnet) team?

I don't want it to sit here with issue rot and not getting looked at when the people who need to look at it are unaware that the problem exists all while its impacting development. It's already hard enough to develop MAUI apps when I need to use application output to debug but the text size of that panel [can't change and is unreadable](https://developercommunity.visualstudio.com/t/Font-size-small/1512248#T-N10050710).

**Comment by edgedj** [comment] 2022-06-01 08:39
I was kindly pointed here by another user, I've found this problem to occur with number of object types as well as string. What's slightly odd is that some objects appear to have non null values when debugging and some don't - I can't spot a pattern yet. I'm going to check out the same solution on my windows laptop and see if the same problem exists there. The ref for my issue is #7647

**Comment by beeradmoore** [comment] 2022-06-01 09:27
I have found something to add. Class variables work, member level variables do not. I guess until this can get fixed everything is going to be private class variable -_- 

![Screen Shot 2022-06-01 at 7 26 29 pm](https://user-images.githubusercontent.com/904737/171372747-226f1b23-8251-4003-9dd3-67ed1b240b87.png)

**Comment by beeradmoore** [comment] 2022-06-08 04:11
@drasticactions I re-created project as a macOS, iOS and macCatalyst with Visual Studio 17.3 (build 198), added the following lines and am for some reason unable to replicate outside of a MAUI project.

```
var test = Path.Combine("test", "path");
System.Diagnostics.Debug.WriteLine($"test: {test}");
System.Diagnostics.Debugger.Break();
```

[IsValueNull_iOS.zip](https://github.com/dotnet/maui/files/8858225/IsValueNull_iOS.zip)
[IsValueNull_MacCatalyst.zip](https://github.com/dotnet/maui/files/8858226/IsValueNull_MacCatalyst.zip)
[IsValueNull_macOS.zip](https://github.com/dotnet/maui/files/8858228/IsValueNull_macOS.zip)

**Comment by xtuzy** [comment] 2022-06-08 04:51
I also get this bug, when i try to explicit call of member of struct, debug infor is correct.

https://user-images.githubusercontent.com/17793881/172532139-0dba7a30-8111-4319-818f-3004e57e29dc.mp4

Example:
[MauiApp1.zip](https://github.com/dotnet/maui/files/8858322/MauiApp1.zip)

**Comment by jfversluis** [comment] 2022-06-15 07:09
@xtuzy are you sure this is the same thing? Because I think all the rest of the people is using Visual Studio for Mac, right? Can any other person confirm that this behavior is also shown on Visual Studio for Windows?

**Comment by AndreasReitberger** [comment] 2022-06-15 07:14
@jfversluis 
I'm using VS on Windows and facing the same issue.

**Comment by beeradmoore** [comment] 2022-06-15 07:20
@jfversluis , using variable type explicitly does not fix the issue.
![Screen Shot 2022-06-15 at 5 17 23 pm](https://user-images.githubusercontent.com/904737/173766635-81c699af-1ad6-4cf9-8eea-4bfa5e6dfa2a.png)

Also to keep this as updated as possible this is still happening on both VS4Mac Version 17.0.3 (build 21) and VS4Mac Version 17.3 Preview (17.3 build 1028) which both came out in the past 48h.

**Comment by jfversluis** [comment] 2022-06-15 07:21
Thanks for the additional info here! We're starting to investigate internally to see where the root cause might be exactly. To be continued...

**Comment by beeradmoore** [comment] 2022-06-15 07:45
@jfversluis regarding what you mentioned to @xtuzy, I ran this exact same code on VS Windows Version 17.3.0 Preview 2.0 and did not have the same outcome as I did on macOS. The code worked fine.

However this is when building for Windows, I do not have remote build setup on my Mac. On macOS I only had the issue when building MAUI app for iOS or macOS, not when I was building for Android.

<img width="574" alt="image" src="https://user-images.githubusercontent.com/904737/173771566-85a177d1-79ee-4d91-988f-dac42e8f1451.png">

**Comment by jfversluis** [comment] 2022-06-15 08:03
@beeradmoore right, so just to be very clear: what you are showing is debugging on VS Windows, running a .NET MAUI Windows target.

And as @xtuzy and @andreas-nesheim are saying; when you connect your VS Windows to a Mac build host and then run a .NET MAUI iOS target, this issue also shows.

@beeradmoore not asking you to confirm this last part since you probably can't just want to try and get a clear overview of all the scenarios that do and don't work 😄

**Comment by beeradmoore** [comment] 2022-06-15 08:24
Correct. Last screenshot was VS Windows MAUI app targeting Windows and it working. (I did not test targeting Android from Windows as I don't have Android SDK setup but I can if needed)

Previous was VS on macOS MAUI app targeting both iOS and Mac Catalyst and it not working.

I also did VS on macOS MAUI targeting Android and it worked fine.

I do not have any remote deploy setup but if you want extra test data I can do that. Computers are right next to each other and I have KVM for input/display switching so I never bothered ever setting that up :p

**Comment by beeradmoore** [comment] 2022-06-19 12:23
Not sure if you need any other info on this but I just got it on a new computer. The above issues I had was on my 2020 MacMini running macOS Monterey. The below is my mid 2014 MacBook Pro which I just did a fresh install with macOS Monterey which isn't officially supported on this hardware.

After install I did the following:
- brew (which installs Xcode command line tools)
- Xcodes (via brew)
- Xcode 13.4.1
- VSCode
- VS4Mac Stable (all install frameworks ticked)
- VS4Mac Preview (all install frameworks ticked)
- Did a `sudo dotnet workload update` to get any MAUI updates but VS4Mac Preview got the latest.
- Fork git client
- Setup ssh for GitHub and BitBucket
- Cloned my ezedit repo which contains the same code as I was testing above

I would have liked to test on macOS Big Sur but it does not support the later versions of Xcode (hence the unofficial update to Monterey :P).

And with that I was able to replicate the same issue. I am glad it isn't some wonky setup I had on my last machine after years of installing/uninstalling different dev tools leaving something bad behind.

**Comment by beeradmoore** [comment] 2022-07-23 02:53
Update: This is still happening with MAUI Service Release 4 (419) with Visual Studio for Mac v17.3 Preview 4 (build 2012)

**Comment by drasticactions** [comment] 2022-07-23 03:34
Because the issue hasn't been fixed, and it's still being worked on.

It's not an issue that will be fixed by code in this repo. It's a runtime/IDE issue at its core.

**Comment by beeradmoore** [comment] 2022-07-23 14:16
Understood, was just adding as much additional info as I can.

If it's IDE issue should it be moved back to VS Dev community where it came from originally, or keep it here for visibly for people who come across the same issue?

As I can't see the internal ticket is there any ETA, rough idea what is wrong (more of a curiosity thing, like why do some people not get it but I get it across 2 machines, is it not widespread), or any possible workarounds? 

It's been months where I've wanted to get started on MAUI but cant as this is a blocker. Aside from Gerald's acknowledgement above it felt like both departments were playing hot potato trying to not take ownership of the issue and then went completely cold and maybe put on the backlog.

**Comment by beeradmoore** [comment] 2022-07-26 09:54
Another update: Still on Visual Studio for Mac v17.3 Preview 4 (build 2012). Just installed MAUI 6.0.424 and the problem seems to have gone away.

Again, I have no info of the internal ticket so not sure what it mentions as possible solutions. There is also no release notes for 424 yet. Does anyone know if this just fixed with this MAUI update or did something else change?

![Screen Shot 2022-07-26 at 7 50 25 pm](https://user-images.githubusercontent.com/904737/180978465-ded4741c-2b51-45a2-ab6a-a9b99d92b843.png)

**Comment by Eilon** [comment] 2022-08-01 21:18
This looks like it was recently fixed by https://github.com/dotnet/runtime/pull/71436.

Best is to update .NET MAUI, but if you need a workaround right now, please refer to this comment:

https://github.com/dotnet/maui/issues/8231#issuecomment-1170374020

**Closed by Eilon** 2022-08-01 21:18 UTC
Labels: area/tooling ⚙️, platform/iOS 🍎

**Comment by Kylar182** [comment] 2022-08-07 15:13
So, is “sudo dotnet workload update” the official fix?
