### ISSUE TITLE
[Android] DisplayAlert accept and cancel action color in light and dark theme

### ISSUE THREAD

**Issue by ioiooi** [dotnet/maui#9005] opened 2022-07-26 14:28 UTC
### Description

https://github.com/ioiooi/MAUIDisplayAlertDarkTheme
    
After deleting all styles and themes I thought the application would behave similar to Xamarin.Forms or use system defaults.

When the light theme is active in the android system settings: the alert background is white, the title, message and actions all use a dark textcolor. When the dark theme is activated in the android system settings: the alert background changes to darkgrey, the title and message use a white textcolor but the actions remain using the dark textcolor and thus are barely visible.
  
Shouldn't the accept and cancel actions be a pink/red-ish color in light and dark mode when no custom stylings are present? The documentation has screenshots of Alerts with this red-ish color. https://docs.microsoft.com/en-us/dotnet/maui/user-interface/pop-ups
  
A Xamarin.Forms Project displays alert actions with this pink/red-ish color after deleting all styles/themes. Even when setting the android system theme to dark, the actions remain red and visible even on a Popup with a dark background color.

![Screenshot_20220726-152934](https://user-images.githubusercontent.com/11210607/181028047-507d92c5-5883-4eb5-8456-1ea7db1a89a0.png)
  

![Screenshot_20220726-153006](https://user-images.githubusercontent.com/11210607/181028095-b0f70b87-d0be-4895-9806-26158d5ebb4e.png)
  

### Steps to Reproduce

1. https://github.com/ioiooi/MAUIDisplayAlertDarkTheme
2. Click the "Click me" Button
3. The Alert has a white background and black/darkgrey headline, description and actions buttons
4. Go into android system settings and change the theming to dark
5. Go back into the App
6. Click the "Click me" Button
7. The Alert has a dark background and white headline and description. The action buttons are black.

### Version with bug

MAUI 6.0.419

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

**Comment by jfversluis** [comment] 2022-07-28 18:31
Duplicate of #6092

**Closed by jfversluis** 2022-07-28 18:31 UTC
Labels: t/bug, s/needs-verification
