### ISSUE TITLE
The RealParent on Microsoft.Maui.Controls.Button has been Garbage Collected

### ISSUE THREAD

**Issue by ThysBrits** [dotnet/maui#23886] opened 2024-07-29 10:24 UTC
### Description

We are developing an app on .Net 8 and today this exception popped up:

The RealParent on Microsoft.Maui.Controls.Button has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui

The issue was only reported by Raygun and we don't have any stack trace of it. It happened on a deployed version of our app on a Android 9 device.

### Steps to Reproduce

We will have to investigate what caused this, as it has only happened on a production device.

### Version with bug

8.0.70 SR7

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 9

**Comment by ThysBrits** [comment] 2024-07-29 15:07
Thanks for the feedback, will keep an eye on it. It has only happened twice, so very random.

**Comment by mattleibow** [comment] 2024-07-30 18:47
Do you happen to have a repro or able to reproduce easily in a simple project?

**Comment by mattleibow** [comment] 2024-07-30 18:47
Duplicate of https://github.com/dotnet/maui/issues/23050

**Closed by mattleibow** 2024-07-30 18:47 UTC
Labels: t/bug, platform/android 🤖
