### ISSUE TITLE
Android platform press back button crash

### ISSUE THREAD

**Issue by Snsaiu** [dotnet/maui#4712] opened 2022-02-16 10:06 UTC
### Description

for android platform ,when you app on root page, you press back button ,the app will be exited ,then you click app icon will crash!

### Steps to Reproduce

1.create maui project
2.run maui project.and you will see home page
3.press back button, the app will be exited
4.click app icon 
5.crash ,throw exception :System.NotImplementedException
Message=Either set MainPage or override CreateWindow.

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

android 10

**Comment by Redth** [comment] 2022-02-16 17:07
Duplicate of #4169

**Closed by Redth** 2022-02-16 17:07 UTC
Labels: t/bug, s/duplicate 2️⃣, platform/android 🤖, fatal
