### ISSUE TITLE
DatePicker: Clear

### ISSUE THREAD

**Issue by JkPersson** [dotnet/maui#17299] opened 2023-09-11 11:58 UTC
### Description

I am missing functionality for having an 'empty' DatePicker as well as being able to clear selection made by the user.

### Public API Changes

The Date property should be nullable.
A 'ShowClearButton' property (Values: Always, Never, WhenFocused) should be added. 

### Intended Use-Case

In our UI, the user must setup some criterias for filtering data. Some of these are dates. A date criteria is only used for filtering if the user selects a date. 

With the current functionality, the UI gets cluttered by some fields (DatePickers) being filled even if they do not contain relevant data.

I would prefer to be able to present these fields as empty until the user selects a date.

This could be done by adding a clear button to the DatePicker like the one in the Entry control.

**Comment by jfversluis** [comment] 2023-09-11 13:12
Thanks @JkPersson ! This is definitely a good one and was raised before so closing this one as a duplicate.

**Comment by jfversluis** [comment] 2023-09-11 13:12
Duplicate of #1100

**Closed by jfversluis** 2023-09-11 13:12 UTC
Labels: proposal/open
