### ISSUE TITLE
First .NET MAUI demo does not display on screen

### ISSUE THREAD

**Issue by twainiqolo** [dotnet/maui#12277] opened 2022-12-23 05:07 UTC
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
OS : Windows 10 build 19041, developer mode enabled,
VS 2022 vs 17.4.3
Build first demo but did not show the display screen when run

**Comment by MagicAndre1981** [comment] 2022-12-23 15:11
install latest [runtime files for WinApp SDK 1.2](https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/downloads#windows-app-sdk-12)

**Comment by mattleibow** [comment] 2023-02-04 01:50
Duplicate of #12080

**Closed by mattleibow** 2023-02-04 01:50 UTC
Labels: tutorials
