### ISSUE TITLE
The EvenOdd FillRule  failed in the wraping space

### ISSUE THREAD

**Issue by jevonsflash** [dotnet/maui#15431] opened 2023-06-03 09:37 UTC
### Description

I use the official example and run the code as it is. Draw several nested circle paths and set the `FillRule` to `EvenOdd`  get a rendering of a whole circle  like this

![image](https://github.com/dotnet/maui/assets/11273359/b7342b4e-e2f5-4e56-b34d-1c37da9493ee)

The official example is here:
https://learn.microsoft.com/en-us/dotnet/maui/user-interface/controls/shapes/fillrules?view=net-maui-7.0

### Steps to Reproduce

1. Clone the repository to local (https://github.com/dotnet/maui-samples/)

2. Open the ShapesDemos solution  and run to an Android device

3. check the `path geometry demos` page, it's

### Link to public reproduction project repository

https://github.com/dotnet/maui-samples/

### Version with bug

7.0.49

### Last version that worked well

6.0

### Affected platforms

Android, Windows

### Affected platform versions

Android 11 ， windows sdk 10.19041

**Comment by jsuarezruiz** [comment] 2023-06-05 08:36
Tested with main branch and cannot reproduce the issue.
![image](https://github.com/dotnet/maui/assets/6755973/307d0795-2c9d-41e9-99aa-56ef2a573159)

The issue should have been fixed by https://github.com/dotnet/maui/pull/14493

**Comment by jevonsflash** [comment] 2023-06-12 06:18
> Tested with main branch and cannot reproduce the issue. ![image](https://user-images.githubusercontent.com/6755973/243298244-307d0795-2c9d-41e9-99aa-56ef2a573159.png)
> 
> The issue should have been fixed by #14493
I submitted this issue after upgrading to the latest version of .net 7.0, I just read the release log and realized that this bug was fixed in 8.0.0-preview.4.8333, so in 7.0 it hasn't been updated yet right?  I'm not using the preview channel, I'm waiting for the stable release.  That is fine.

It's very kind of you. Thanks

**Comment by jsuarezruiz** [comment] 2023-07-05 14:14
Fixed by #14493

**Closed by jsuarezruiz** 2023-07-05 14:14 UTC
Labels: t/bug, platform/android 🤖, area/drawing ✏️
