### ISSUE TITLE
Android TableView's ViewCell won't calculate height correctly

### ISSUE THREAD

**Issue by edgiardina** [dotnet/maui#12989] opened 2023-01-30 00:31 UTC
### Description

When using a custom ViewCell in a TableView in Android, the viewcell's contents won't size correctly in a scenario where the topmost element of a ViewCell is an image, or a Stacklayout. (possibly others as well). 

In this image, 'My Stats' should have an Image visible, but appears instead to render a zero height. 

![image](https://user-images.githubusercontent.com/3627193/215365240-e7eae92d-a9bd-43bc-9f18-02e64a246df6.png)

### Steps to Reproduce

1. File -> New Maui app
2. Create TableView with custom ViewCell
3. Child of the VIewCell shoul dbe a stacklayout, or a sole image
4. height of the ViewCell will be zero and not visibly render child components

```
            <TableSection Title="My Stats" TextColor="{StaticResource SecondaryTextColor}">
                <ViewCell>
                    <Image Source="https://s.gravatar.com/avatar/a34661252ff93712b82ec51d5ca96bed?s=80" HeightRequest="50" />
                </ViewCell>
            </TableSection>
```     

### Link to public reproduction project repository

https://github.com/edgiardina/MauiBug_ViewCellsMissingInAndroid

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 13 Pixel 5

**Comment by homeyf** [comment] 2023-06-13 03:14
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 1.0. Can repro on Android platform with sample project.
https://github.com/edgiardina/MauiBug_ViewCellsMissingInAndroid
![image](https://github.com/dotnet/maui/assets/82450723/66218a3d-ac1a-4101-8bd7-970ed9f64960)

**Comment by PureWeen** [comment] 2023-12-12 20:26
Duplicate of #5924

**Closed by PureWeen** 2023-12-12 20:26 UTC
Labels: t/bug, platform/android 🤖, area/ListView, s/verified, s/triaged
