### ISSUE TITLE
Page Scrolls Up When Clicking Entry Positioned at Bottom

### ISSUE THREAD

**Issue by msandikli** [dotnet/maui#24723] opened 2024-09-11 21:15 UTC
### Description

When an Entry element is positioned at the bottom of the page in a .NET MAUI application, clicking on the Entry causes the page to scroll up. This behavior affects the user experience as it disrupts the intended layout and interaction.

<img src="https://github.com/user-attachments/assets/cca62208-ad90-4959-a500-c3853638ca7a" width="300" />

### Steps to Reproduce

1. Create a .NET MAUI page and add an Entry element at the bottom of the page.
2. Run the application.
3. Click on the Entry element.

### Version with bug

9.0.0-rc.1.24453.9

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Android

**Comment by mattleibow** [comment] 2024-09-12 19:08
Duplicate of https://github.com/dotnet/maui/issues/20548

**Closed by mattleibow** 2024-09-12 19:08 UTC
Labels: t/bug, platform/android 🤖, area-controls-entry, s/triaged, migration-compatibility
