### ISSUE TITLE
Blazor Desktop tenets: Performance

### ISSUE THREAD

**Issue by Eilon** [dotnet/maui#2531] opened 2021-02-27 00:29 UTC
- Define perf goals and scenarios w/ specific #'s that we will target
- Build scenarios on main competitors and ours
- Automate measurements on relevant platforms
- Need to review guidance from docs of each native WebView component for any best practices

A feature to consider:
- Enable pooling of WebViews and/or enable external creation of WebViews (from some externally-existing pool). This technique is used in major apps that often have multiple web views but only a subset of them are visible at one time.

**Comment by Eilon** [comment] 2021-12-13 18:35
We need to measure the basics in comparison to similar non-Blazor MAUI scenarios:

* Size on disk for installers and in deployed apps
* Memory usage
* Startup time to an interactive app

**Comment by MichaelPeter** [comment] 2022-02-15 18:06
Could you also consider JSInterop Performance? In Blazor Webassembly there is the IJsUnmarshalled Runtime, which allows up to 250.000 calls per second. Since in Blazor Hybrid, the communication goes over IPC (At Least in WPF), the number of javascript calls is limited arround 1000 calls per seconds in our tests.

**Comment by darianmiller** [comment] 2022-02-22 03:46
"Responsiveness" is a key metric but can be difficult to quantitate. Perhaps screen redraw speed of a moderately complex UI.

**Comment by mkArtakMSFT** [comment] 2022-03-24 17:52
## Summary
Below is the list that we are going to measure for GA release.
- Startup time / Time to first component UI render (within WebView)
- Size of the installer for new Blazor MAUI app (per-platform)
- Memory usage of a running default app (per-platform)

## Delayed until .NET 7
- Metrics for WPF and WinForms
- Rendering performance (to be comparable with the WASM UI rendering?)

**Comment by radderz** [comment] 2022-05-02 21:20
I was quite surprised after getting our blazor wasm app working in Maui.NET that the performance was actually significantly worse. Is this expected? Is it due to the rendering performance mentioned that is delayed till .NET 7?

**Comment by SteveSandersonMS** [comment] 2022-05-03 08:22
@radderz If you're able to provide a minimal repro we can definitely take a look. Otherwise, this is very unexpected.

**Comment by radderz** [comment] 2022-05-03 08:24
@SteveSandersonMS I'll try to put together a repro, its not clear what is the exact cause of the slowness as I haven't delved into it deeply yet but I was expecting the speed to be an improvement. Its always possible we are just doing something wrong, so will try to reproduce it in a simple example.

**Comment by radderz** [comment] 2022-05-03 20:24
@Eilon - It was on both windows and running on windows subsystem for android. They were debug builds but so was the webapp. I am using the mudblazor UI library and the slow down is when deserialising data from OData and updating a grid UI with large amounts of data (the grids are virtualized though).

I probably cant setup the example today but I'll try to do it tomorrow.

**Comment by Eilon** [comment] 2022-05-03 23:01
@radderz thank you for the extra info. If you can provide a repro for it that will be very helpful so we can try to reproduce exactly what you're seeing.

**Comment by TanayParikh** [comment] 2022-07-21 04:05
Just a bit of an update on where things stand currently. We have added automated coverage for iOS, Mac Catalyst and Android. We're collecting stats on size on disk, size of the unpackaged application, as well as time to first render for Blazor (using the `OnAfterRender` hook). 

[Performance dashboard (requires appropriate permissions)](https://msit.powerbi.com/groups/9ae0c009-7b27-44c9-8360-4452ec48cef3/reports/82d2f9ca-5f84-4775-bf11-501c21b195fc/ReportSectionc6d3e2c09b9adee234d0)

We're working on onboarding the Windows scenario presently. Currently, we can't directly Console log on Windows (https://github.com/dotnet/maui/issues/7821#issuecomment-1154261957), which is preventing us from marking the render event [like we do on the other platforms](https://github.com/dotnet/runtime/pull/68685/files#diff-58d65effbc166c8c040b8e44f90ce3504a61b52916dca244c60b91ed8b547a41R239).

**Comment by TanayParikh** [comment] 2022-08-11 04:33
> We're working on onboarding the Windows scenario presently. Currently, we can't directly Console log on Windows ([#7821 (comment)](https://github.com/dotnet/maui/issues/7821#issuecomment-1154261957)), which is preventing us from marking the render event [like we do on the other platforms](https://github.com/dotnet/runtime/pull/68685/files#diff-58d65effbc166c8c040b8e44f90ce3504a61b52916dca244c60b91ed8b547a41R239).

https://github.com/dotnet/performance/pull/2526 was just merged earlier this week. That PR handles setting up the Windows environment (installing the WebView), as well as logging the Windows Blazor render event. The data hasn't been reflected on the [performance dashboard](https://msit.powerbi.com/groups/9ae0c009-7b27-44c9-8360-4452ec48cef3/reports/82d2f9ca-5f84-4775-bf11-501c21b195fc/ReportSectionc6d3e2c09b9adee234d0) yet, so we're still ironing some things out to figure out what the missing piece is.

**Comment by TanayParikh** [comment] 2022-08-11 17:58
[Performance dashboard (requires appropriate permissions)](https://msit.powerbi.com/groups/9ae0c009-7b27-44c9-8360-4452ec48cef3/reports/82d2f9ca-5f84-4775-bf11-501c21b195fc/ReportSectionc6d3e2c09b9adee234d0)

The .NET MAUI Windows benchmarks are now available for:
- Size on disk
- Startup time

**Comment by TanayParikh** [comment] 2022-08-11 18:01
Closing this out now as completed! 😄

**Closed by TanayParikh** 2022-08-11 18:01 UTC
Labels: platform/macOS 🍏, platform/windows 🪟, platform/android 🤖, area/blazor 🕸️, platform/iOS 🍎, area/perf 🏎️, discussed
