### ISSUE TITLE
TableView cells disappear when cells are updated on Android

### ISSUE THREAD

**Issue by jstedfast** [dotnet/maui#16533] opened 2023-08-03 22:11 UTC
### Description

As you can see in the video below, when my app updates the labels in the StockSymbolView (a custom ViewCell class that is used by the MAUI TableView control), all of the cells vanish!

https://github.com/dotnet/maui/assets/338984/5805e6f4-6e51-42d9-b530-5b0f7854d886

Note: This may or may not be a duplicate of issue #10064

Tested on:
* WinUI (works fine)
* Android (cells disappear)

### Steps to Reproduce

1. git clone git@github.com:jstedfast/Stocks
2. cd Stocks
3. git reset --hard 59c1c48d5a1ee63c35e9f345ba04b4b41bc5ff24
4. Open the Stocks.sln in Visual Studio
5. Select an Android emulator (or device?) to run the Stocks app on
6. Build & Run
7. Within a few seconds of the Stocks app launching on Android, the stock quote data should be fetched from the web and at this point, it will attempt to update the stock quote info in each cell and you will see all of the cells vanish in the TableView.

To verify that these changes are happening on the main UI thread, you can set breakpoints in StockSymbolView.xaml.cs in the OnQuoteChanged() and/or OnSparkChanged() methods.

Since the UpdateSpark() method does some stuff with rendering a chart to an off-screen image buffer, I also tried commenting out calls to this method just to see if this was the root cause. This leaves only the UpdateQuote() method being called which only sets label values. Even after doing this, the results are the same - the TableView cells all disappear.

### Link to public reproduction project repository

https://github.com/jstedfast/Stocks

### Version with bug

8.0.0-preview.6.8686

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android API 33

### Did you find any workaround?

Working on trying to migrate this UI to CollectionView but that seems to have other issues (that I will report momentarily).

### Relevant log output

```shell
I did not see any logging that would be related.
```

**Comment by harry-cpp** [comment] 2023-08-04 00:01
What a silly bug, any update to the table will cause all the `ViewCell` to vanish, here is a simple repro Xaml code:
```xaml
<TableView>
    <TableSection>
        <ViewCell>
            <Label Text="THIS CELL WILL VANISH!" />
        </ViewCell>
        <SwitchCell Text="Toggle Me to cause the bug" On="False" />
    </TableSection>
</TableView>
```

**Comment by XamlTest** [comment] 2023-08-17 08:59
Verified this on Visual Studio Enterprise 17.8.0 Preview 1.0. Repro on Android 13.0-API33 .NET 8, not repro on Windows 11 and iOS 16.4 with below Project:
[Stocks.zip](https://github.com/dotnet/maui/files/12367376/Stocks.zip)

**Comment by PureWeen** [comment] 2023-12-12 20:25
Duplicate of #5924

**Closed by PureWeen** 2023-12-12 20:25 UTC
Labels: t/bug, platform/android 🤖, area/controls 🎮, area/ListView, s/verified, s/triaged, scenario-day
