### ISSUE TITLE
FlexLayout Memory leak

### ISSUE THREAD

**Issue by xzidez** [dotnet/maui#10904] opened 2022-10-25 16:32 UTC
### Description

A flexlayout with ObservableCollection as BindableLayout.ItemsSource will never  release any resources that has been in the collection.

### Steps to Reproduce

Use public reproduction repo. 
Start and click the button. See how instance counter keeps increasing and never decrease.

This is how the layout looks. Nothing strange just a flexlayout with a itemssource.
```
<FlexLayout WidthRequest="300" Direction="Column" BindableLayout.ItemsSource="{Binding Items}">
 <BindableLayout.ItemTemplate>
  <DataTemplate x:DataType="tmp:Item">
   <Label Text="{Binding Text}" HeightRequest="40" MinimumWidthRequest="100" BackgroundColor="LightGray"/>
  </DataTemplate>
 </BindableLayout.ItemTemplate>
</FlexLayout>
```

Viewmodel looks like this
```
public partial class ViewModel : ObservableObject
{
    [ObservableProperty]
    private ObservableCollection<Item> _items;

    public string InstanceCounterText => $"InstanceCount: {Item.InstanceCounter}";

    public ViewModel()
    {
        Items = new ObservableCollection<Item>();
    }

    public void Update()
    {
        Items.Add(new Item());
        if(Items.Count > 1)
        {
            Items.RemoveAt(0);
        }

        GC.Collect();
        OnPropertyChanged(nameof(Items));
        OnPropertyChanged(nameof(InstanceCounterText));
    }
}
```

And then the item in question
```
public class Item 
{
    public static int InstanceCounter = 0;
    public string Text { get; }
    public Item()
    {
        Text = $"Item number: {InstanceCounter++}";
    }
    ~Item()
    {
        InstanceCounter--;
    }
}
```

### Link to public reproduction project repository

https://github.com/xzidez/MauiFlexLayoutLeak

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows

### Affected platform versions

Any Android or Windows version

**Comment by ggutschi** [comment] 2022-11-02 08:45
Also references to https://github.com/dotnet/maui/issues/9162#issuecomment-1286693847

**Comment by XamlTest** [comment] 2023-06-01 06:21
Verified this on Visual Studio Enterprise 17.7.0 Preview 1.0. Repro on Windows 11 and Android 13.0-API33 with provided Project:
[10904.zip](https://github.com/dotnet/maui/files/11621708/10904.zip)

Windows:
![image](https://github.com/dotnet/maui/assets/97647558/5a68e01c-cdec-438c-9355-f6bdc3a49734)

Android:
![image](https://github.com/dotnet/maui/assets/97647558/2839941d-4843-4c64-bb05-9f659ceebf3b)

**Comment by albyrock87** [comment] 2023-09-14 08:52
The problem is in your code.

This should be your `Update` method in order to trigger and wait for the GC correctly.

```cs
    public async Task Update()
    {
        Items.Add(new Item());
        if(Items.Count > 1)
        {
            Items.RemoveAt(0);
        }

        await Task.Yield();
        GC.Collect();
        GC.WaitForPendingFinalizers();
        OnPropertyChanged(nameof(Items));
        OnPropertyChanged(nameof(InstanceCounterText));
    }
```
![image](https://github.com/dotnet/maui/assets/1423005/162ab387-29ce-4505-87be-5233fe9d7264)

That said, I think there are more complex use cases where `BindableLayout` leaks.
This is why I've opened https://github.com/dotnet/maui/pull/17290

**Comment by jonathanpeppers** [comment] 2023-09-14 15:48
I'm asking the MAUI team about https://github.com/dotnet/maui/pull/17290.

I don't think it actually solves a leak, but there may be some behavior around `BindingContext` that you're fixing that seems good. 👍 

I do think we can close it, as you've shown in the screenshot. Thanks!

**Closed by jonathanpeppers** 2023-09-14 15:48 UTC
Labels: t/bug, platform/windows 🪟, platform/android 🤖, area/perf 🏎️, s/verified, s/triaged, s/try-latest-version, memory-leak 💦
