### ISSUE TITLE
Secondary Order ToolbarItems not displayed correctly on iOS

### ISSUE THREAD

**Issue by ewerspej** [dotnet/maui#14559] opened 2023-04-13 09:27 UTC
### Description

On iOS, `ToolbarItem`s that have their `Order="Secondary"` are not displayed in the secondary level menu bar. Instead, they appear in line with the `Primary` items.

I have the following XAML setup:

```xml
<ContentPage.ToolbarItems>
  <ToolbarItem Command="{Binding SetLowBrightnessCommand}">
    <ToolbarItem.IconImageSource>
      <FontImageSource
        FontFamily="MaterialIconsOutlined-Regular"
        Glyph="&#xe51c;"
        Color="LightBlue"
        Size="20"/>
    </ToolbarItem.IconImageSource>
  </ToolbarItem>
  <ToolbarItem Command="{Binding SetHighBrightnessCommand}">
    <ToolbarItem.IconImageSource>
      <FontImageSource
        FontFamily="MaterialIconsOutlined-Regular"
        Glyph="&#xe518;"
        Color="LightPink"
        Size="32"/>
    </ToolbarItem.IconImageSource>
  </ToolbarItem>
  <ToolbarItem
    Order="Secondary"
    Text="Item 3" />
  <ToolbarItem
    Order="Secondary"
    Text="Item 4" />
</ContentPage.ToolbarItems>
```

On iOS the secondary items _(Item 3, Item 4)_ are incorrectly displayed in the same level as the icons, which shouldn't be the case:

<img src="https://github.com/ewerspej/maui-samples/blob/main/issues/titleview_ios/ios_bug_toolbaritems.PNG?raw=true" width="500" />

On Android it works as expected:

<img src="https://github.com/ewerspej/maui-samples/blob/main/issues/titleview_ios/android_secondarymenu.PNG?raw=true" width="500" />

### Steps to Reproduce

1. Create new MAUI project
2. On MainPage, set `<ContentPage.ToolbarItems>` 
3. Add some instances of `ToolbarItem` with default setting or `Order="Primary"`
4. Add one or more instances of `ToolbarItem` with `Order="Secondary"`
5. Observe the incorrect behavior on iOS

### Link to public reproduction project repository

https://github.com/ewerspej/maui-samples/

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 16 (and possibly earlier versions)

### Did you find any workaround?

No

### Relevant log output

```shell
n/a
```

**Comment by frogcrush** [comment] 2023-05-16 03:39
I am also having this issue, and have not found a workaround. This is blocking our app from going live.

**Comment by MichaelSL** [comment] 2023-05-20 02:02
I have the same issue, no workaround yet.

**Comment by ooikengsiang** [comment] 2023-05-20 04:24
The primary reason is iOS doesn't support drop-down menu from title bar by default. I look into the source code, no flyout menu implemented, so this feature is not broken in iOS, but more like unsupported.

**Comment by ewerspej** [comment] 2023-05-20 08:36
> The primary reason is iOS doesn't support drop-down menu from title bar by default. I look into the source code, no flyout menu implemented, so this feature is not broken in iOS, but more like unsupported.

That's unlikely, because it works in Xamarin.Forms AFAIK, it just looks different on iOS than it does on Android, which is fine. *Not implemented* doesn't mean *not supported*. In any case, the current behavior appears broken, no matter whether it's because of a bug or because of a lack of implementation, it cannot stay like this, because otherwise the `Order` property is rendered useless.

**Comment by thatkidyousaw1** [comment] 2023-06-21 04:52
Hi @ewerspej ,
Do you happen to know any workaround for this? I looked some online and they used a custom renderer. I cannot somehow make it work with MAUI.

**Comment by ewerspej** [comment] 2023-06-26 08:32
@thatkidyousaw1 No, I am not aware of a working workaround. However, I have also not invested much time into finding one, because this needs to work out-of-the-box. It's clearly broken and I am categorically against workarounds for fundamental things. Workarounds for smaller bugs and issues are fine, but this is a showstopper for this feature and renders it utterly useless.

**Comment by XamlTest** [comment] 2023-06-28 06:33
Verified this on Visual Studio Enterprise 17.7.0 Preview 2.0. Repro on iOS 16.4 with below Project:
https://github.com/ewerspej/maui-samples/

**Comment by ewerspej** [comment] 2023-06-28 08:07
> Verified this on Visual Studio Enterprise 17.7.0 Preview 2.0. Repro on iOS 16.4 with below Project: https://github.com/ewerspej/maui-samples/

Yes, it should still be reproducible there. However, note that I've recently added Shane's [Workarounds NuGet package](https://www.nuget.org/packages/PureWeen.Maui.FixesAndWorkarounds), which fixes a couple of things temporarily. The issue described here is not affected by that, though.

**Comment by malsabi** [comment] 2023-10-12 11:12
This issue is still active in .NET 8 Core RC1

**Comment by andreas-spindler-mw** [comment] 2023-12-15 19:53
Still active in .NET 8.0.100

**Comment by pandaloupe** [comment] 2024-01-04 10:16
I'm pretty sure this wasn't supported in XamForms either. There are workarounds which make use of a custom page renderer like this one [https://github.com/AmitManchanda/iOSSecondaryToolbarMenubar].
I haven't seen a proper implementation of that for MAUI though...

**Comment by AlleSchonWeg** [comment] 2024-01-04 11:19
There is a request open for a long time: https://github.com/dotnet/maui/issues/815
Starting with iOS 14.1 something similar is possible: https://developer.apple.com/documentation/uikit/uinavigationcontroller/customizing_your_app_s_navigation_bar#3950610
It looks a lot better as the maui/xf secondary toolbar items: https://nemecek.be/blog/85/how-to-show-uimenu-from-uibutton-or-uibarbuttonitem

**Comment by ewerspej** [comment] 2024-01-05 11:55
> I'm pretty sure this wasn't supported in XamForms either. There are workarounds which make use of a custom page renderer like this one [https://github.com/AmitManchanda/iOSSecondaryToolbarMenubar](https://github.com/AmitManchanda/iOSSecondaryToolbarMenubar)
> I haven't seen a proper implementation of that for MAUI so far which would be a Handler rather than a Renderer as I understand it.
> 

Indeed, in Xamarin.Forms it wasn't the same on iOS and Android. However, the secondary items were displayed in a proper fashion on iOS, not like it's now with MAUI. In either case, the secondary items shouldn't just be added to the navigation bar like in the screenshot, because they will eventually fill up the entire navigation bar with text.

**Comment by bzd3y** [comment] 2024-04-25 23:30
I can confirm that this did work in Xamarin. And in MAUI they are actually displayed correctly when using a `FlyoutPage` with `Detail` set to a `NavigationPage`.

**Comment by tataelm** [comment] 2024-06-23 16:56
this is still an issue. Is there any progress with this?

**Comment by samhouts** [comment] 2024-06-27 16:00
We recognize that this is an omission from Xamarin.Forms, so it takes a high priority. As some have noted, this functionality didn't really exist in iOS at the time, so the manner in which we implemented it in Xamarin.Forms was not ideal; that's why it wasn't brought over to .NET MAUI. Now that iOS has provided us with APIs that we can use, we believe that you'll be much happier if we do _not_ bring over the same functionality from Xamarin.Forms and instead implement #815. 

I'm going to mark this as a duplicate of #815, and we'll work to get it prioritized.

Thanks for your patience!

**Closed** 2024-06-27 16:00 UTC
Labels: t/bug, platform/iOS 🍎, s/verified, s/triaged, migration-compatibility, area-controls-toolbar

**Comment by ewerspej** [comment] 2024-07-01 09:53
@samhouts Thanks for taking time to figure out the best option for iOS. I agree that the proposed approach in #815 is indeed better compared to the XF solution.
