### ISSUE TITLE
Grid row not sizing correctly with * when the content is a collectionview on iOS

### ISSUE THREAD

**Issue by WebGoose** [dotnet/maui#15092] opened 2023-05-15 15:04 UTC
### Description

I have a grid with 2 rows (*, 50), with some buttons in the bottom row. As per the [Docs](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/layouts/grid), this layout should mean that the button is anchored to the bottom of the page and the * uses the rest of the available space for whatever is in that row. However, if the first row contains a collectionview, it is not constrained to the available space, but expands the page and actually overlaps / hides the bottom row entirely making the buttons unusable. This only happens on iOS and only started happening with [Service Release 6](https://github.com/dotnet/maui/releases/tag/7.0.86), which contained a fix for grid sizing but seems to have now broken something else. 

Any other control uses the available space correctly, but collectionview does not. 

ANDROID:

https://github.com/dotnet/maui/assets/5024960/3e382d6b-7ab8-4ac8-a030-2a0cc721a035

IOS:
![image](https://github.com/dotnet/maui/assets/5024960/735d6c35-a8a6-4623-be74-153a14e235aa)

If I replace the collectionview with a stacklayout and some labels, the spacing on iOS is correct as below. 
![image](https://github.com/dotnet/maui/assets/5024960/450e027a-0d19-4882-b1b5-fc2bce5e8239)

This was working fine in the previous release. 

I have attached a basic sample project to demonstrate

### Steps to Reproduce

See attached example project. 

Create a grid with 2 rows with the top row being a * and the bottom row being either fixed value of say 50 or auto. 

Place a collectionview in the top row with enough items that it will scroll. Place anything else in the bottom row. 

The collectionview is not constrained to the available space that the * should be using (screen height - bottom row) and overlaps / hides it. 

### Link to public reproduction project repository

https://gooseza.visualstudio.com/MauiBugs/_git/GridCollectionView

### Version with bug

7.0 (current)

### Last version that worked well

7.0 (current)

### Affected platforms

iOS

### Affected platform versions

iOS 16.4.1

**Comment by drasticactions** [comment] 2023-05-16 03:46
I think that's being fixed with https://github.com/dotnet/maui/pull/14951

**Comment by drasticactions** [comment] 2023-05-16 03:47
Duplicate of https://github.com/dotnet/maui/pull/14951

**Closed** 2023-05-16 03:48 UTC
Labels: t/bug, area/layout 🔲
