### ISSUE TITLE
.Net 7 Android Maui FlayoutPage Crashes on  Release Mode When Enable Trimming Selected

### ISSUE THREAD

**Issue by planyazilim** [dotnet/maui#11514] opened 2022-11-20 22:04 UTC
### Description

.Net 7 Android Maui Basic FlayoutPage Crashes on  Release Mode, When Enable Trimming = True.
OnDebug mode it workds.
On Release mode If Trimming = False it works.

### Steps to Reproduce

1. Create a New Project in .Net 7 Maui
2. Put a simple FlyoutPage 
3. Check  Enable Trimming on Android Release Mode 
4. Run and App crashes :(

### Link to public reproduction project repository

none

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android

**Comment by jsuarezruiz** [comment] 2022-11-21 15:15
Could you share the exception logs?

cc @jonathanpeppers

**Comment by jonathanpeppers** [comment] 2022-11-21 15:24
This is probably fixed by: https://github.com/dotnet/maui/pull/11096

`AndroidLinkResources=false` in your `.csproj` fix it?

**Comment by planyazilim** [comment] 2022-11-21 17:23
@jonathanpeppers @jsuarezruiz
thank you, AndroidLinkResources=false solved my problem.
is this temporary solution?

**Comment by jonathanpeppers** [comment] 2022-11-21 20:41
In the next service release, you shouldn't need `AndroidLinkResources=false` anymore as it won't be turned on anymore.

Closing this as duplicate of https://github.com/dotnet/sdk/issues/28880. Thanks!

**Closed by jonathanpeppers** 2022-11-21 20:41 UTC
Labels: t/bug, platform/android 🤖, area/FlyoutPage, s/needs-attention
