### ISSUE TITLE
.net MAUI Blazor App Lambda expressions in @for loop capturing incorrect index value

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#24181] opened 2024-08-12 22:23 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/net-MAUI-Blazor-App-Lambda-expressions-/10705324)._

---
I am encountering an issue in my .NET MAUI Blazor app where lambda expressions inside an @for loop capture the incorrect index value. The index value passed to the HandlePageChange method is always the last value of the loop, instead of the current value at each iteration.

Steps to Reproduce:

Create a .NET MAUI Blazor app.
Add a pagination component with the following code:

@for (int index = 1; index <= TotalPages; index++)
{
    <li class="page-item @(CurrentPage == index ? "active" : "")">
        <button class="page-link" @onclick="() => HandlePageChange(index)">@index</button>
    </li>
}
Implement the HandlePageChange method in the code-behind:

private void HandlePageChange(int pageIndex)
{
    // Handle page change logic here
}
Run the application and click on any pagination button.
Expected Behavior:

The pageIndex parameter in the HandlePageChange method should reflect the correct index value of the button clicked.

Actual Behavior:

The pageIndex parameter always reflects the last value of the loop, regardless of which button is clicked.

Workaround:

A local variable can be used to capture the correct index value within the loop:

@for (int index = 1; index <= TotalPages; index++)
{
    int pageIndex = index;
    <li class="page-item @(CurrentPage == pageIndex ? "active" : "")">
        <button class="page-link" @onclick="() => HandlePageChange(pageIndex)">@pageIndex</button>
    </li>
}
Environment:

.NET MAUI Blazor app
.NET version: [Specify the version]
Blazor version: [Specify the version]
Operating System: [Specify the OS]
Additional Context:

Any additional information or context about the issue.

This structure provides a clear and detailed description of the issue, along with steps to reproduce, expected and actual behavior, a workaround, and relevant environment details.

---
#### Feedback Bot on 7/17/2024, 06:17 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by jfversluis** [comment] 2024-08-13 08:44
This is not a bug in .NET MAUI, if anything it would be in Blazor or the C# language, but I highly doubt that. I think this might be something of a misunderstanding of how this works.

Nothing for us to do here unfortunately, so closing this here.

**Closed by jfversluis** 2024-08-13 08:44 UTC
Labels: t/bug
