### ISSUE TITLE
Random images shown in Image class on Android

### ISSUE THREAD

**Issue by ParkerzSoft** [dotnet/maui#12923] opened 2023-01-26 12:56 UTC
### Description

On Android, creating bitmap images in a byte[] buffer and then using an ImageSource to display them in an Image object causes random images to be displayed. This seems to be linked to the Android application cache because emptying the application cache allows the application to run correctly for a time.

This is a rather random error so it is not possible to show it directly, but repeatedly showing images will eventually cause it to manifest itself.

The exemple application in the linked repository shows the error.
It should show six rectangles in the order of the rainbow (red, orange,yellow,green,blue,violet).

![OK](https://user-images.githubusercontent.com/54439758/214837874-50d2faa3-99c7-42cf-8a15-aa60d40ee2ce.png)

But if you leave it running long enough some rectangles will show up in the wrong places.
Each rectangle has the date it was created stamped on it and you can see that sometimes (when the colour is wrong) the time corresponds to a previous run.

Example of error 👍 

![Bad](https://user-images.githubusercontent.com/54439758/214838204-c1eb67db-f468-4706-b47a-d32e6c78eacb.png)

### Steps to Reproduce

The linked repository shows the problem. Download the solution, compile and run it on an Android device.
It will keep updating the rectangles just watch it until rectangles appear in the wrong places.
If everything seems OK. Close down the app and start it again. the problem is often most apparent just after a restart (not the first run because there is nothing in the cache).

As an extra problem, under .NET 7 this program (or even the bare NET MAUI app without modification) will not run under Windows (it won't even get to the debugger and stops before).
Under .NET 6 the image problem is still there under Android, but the app works correctly on Windows.
This is new for NET MAUI, Xamarin worked fine, but it does make MAUI completly unusable for image based applications.

### Link to public reproduction project repository

https://github.com/ParkerzSoft/Imagebug

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Tested on Android 10.

### Did you find any workaround?

No. I have found no way to alleviate this, except emptying the Android cache, which I cannot expect users to do.

**Comment by DannyHorswell** [comment] 2023-01-26 13:06
I was going to raise a bug but this seem to be the same.

Video here
https://danny-smilecomputersolutions.tinytake.com/msc/NzgyMzM4OF8yMDg4NDM4Ng

And example project here 
https://github.com/DannyHorswell/MauiImageIssue

**Comment by homeyf** [comment] 2023-06-07 08:55
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 1.0. Can repro on Android platform with sample project.
https://github.com/ParkerzSoft/Imagebug
![image](https://github.com/dotnet/maui/assets/82450723/d4f53c5e-39d2-43e8-a60e-f757a0243d29)

**Comment by hartez** [comment] 2023-06-07 23:02
This is a duplicate of #8676, and is fixed by #13111 / #15274.

**Closed** 2023-06-07 23:02 UTC
Labels: t/bug, platform/android 🤖, area/controls 🎮, s/verified, control-image, s/triaged
