### ISSUE TITLE
Input Transparent not working properly (Android Simulator) when BoxView has InputTransparent set to true and then set to false in backend code. 

### ISSUE THREAD

**Issue by Vpatel541** [dotnet/maui#7498] opened 2022-05-26 13:07 UTC
### Description

I had a Box View on an Android App I am developing. I initially get the BoxView InputTransparent to true. Then when I click a button, it should set that same BoxView InputTransparent to false. But when I try to tap on the BoxView after clicking the button, the Tap Gesture is not being detected. 

### Steps to Reproduce

1. Make new .NET MAUI project 
2. Create BoxView item with InputTransparent set to true
3. Add Tap Gesture for BoxView for testing
4. Create separate button with Click Function
5. In the Click event for button, set BoxView's Input Transparent to false
6. Attempt to click BoxView to see if Tap Gesture is hit

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 10 and up

### Did you find any workaround?

No

**Comment by jfversluis** [comment] 2022-06-09 14:01
Were you also able to test on other platforms? Does this also happen on iOS, Windows?

**Comment by samhouts** [comment] 2022-08-31 17:01
Duplicate of #7498

**Closed by samhouts** 2022-08-31 17:01 UTC
Labels: t/bug, platform/android 🤖, area/controls 🎮, s/needs-attention
