### ISSUE TITLE
image size calculation

### ISSUE THREAD

**Issue by ialbert-AUT** [dotnet/maui#5565] opened 2022-03-25 08:28 UTC
### Description

I set only WidthRequest and the height of the control is not resized with the default AspectFit

### Steps to Reproduce

	<Image Source="dotnet_bot.png" BackgroundColor="Black"
		   WidthRequest="100"
		   Aspect="AspectFit"
		   VerticalOptions="Start"
		    />
	
The black background shows that the size of the image control is not around the image itself as it IMHO should

### Version with bug

Preview 14 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 31

**Comment by VincentBu** [comment] 2022-03-25 09:42
Hi @ialbert-AUT , is this the expected behavior?
![image](https://user-images.githubusercontent.com/44959937/160095479-eb580aee-030d-4244-9f11-4ca5ab08a4c3.png)

**Comment by ialbert-AUT** [comment] 2022-03-25 10:01
> Hi @ialbert-AUT , is this the expected behavior? ![image](https://user-images.githubusercontent.com/44959937/160095479-eb580aee-030d-4244-9f11-4ca5ab08a4c3.png)

not sure as I don't see the actual control in your example.
Here is what I see on Android: 
![Screenshot_1648202319](https://user-images.githubusercontent.com/61751571/160098819-0a177480-6b64-4385-9ceb-ad1d5f91fc32.png)

And this is Windows which is according to my expectations:
![image](https://user-images.githubusercontent.com/61751571/160098955-783234fd-4d7d-4af0-8907-a600a6666191.png)

As I see the ViewHandler.GetDesiredSize returns (100, 0) on Windows and (100, 249) on Android. I don't remember the exact numbers, but the Height on Windows is 0 and non-zero on Android.

**Comment by Dreamescaper** [comment] 2022-03-28 20:18
Probably same as:
https://github.com/dotnet/maui/issues/5438

**Comment by samhouts** [comment] 2022-04-29 02:00
Duplicate of #5438

**Closed by samhouts** 2022-04-29 02:00 UTC
Labels: t/bug, area/layout 🔲, area/image :framed_picture:, area/controls 🎮, s/verified, control-image
