### ISSUE TITLE
AppDomain.CurrentDomain.UnhandledException is not invoked on iOS

### ISSUE THREAD

**Issue by busec0** [dotnet/maui#8463] opened 2022-07-01 11:57 UTC
### Description

`AppDomain.CurrentDomain.UnhandledException` is not invoked on iOS after an exception. 

**On Android it works**. 

Attached a Sample App: 
[TabbedPage.zip](https://github.com/dotnet/maui/files/9028638/TabbedPage.zip)

iOS Recording: 
https://user-images.githubusercontent.com/26183235/176889421-f19f517f-690f-45c7-aa61-e8775b18ed49.mov

Android Recording: 
https://user-images.githubusercontent.com/26183235/176889906-e953378d-3ad5-4519-8ea2-7628bb058982.mov

### Steps to Reproduce

1. On a MAUI sample app, add the following code (in App.xaml.cs, within the constructor) 

```csharp
        AppDomain.CurrentDomain.UnhandledException += (s, e) =>
        {
            Console.WriteLine(" > > ON UnhandledException < < ");
            Console.WriteLine((e.ExceptionObject as Exception)?.ToString());
            Console.WriteLine(" - - - - - - ");
        };
```

2. On the main page, add a simple button, with the following action: 

```csharp
    private void OnButtonClicked(object sender, EventArgs e)
    {
        Console.WriteLine("+ + Crashing Application ");
        Console.WriteLine("+ + Crashing Application ");
        throw new Exception("Random exception");
    }
```

3. Build the application, load it on a device, make sure the debugger is not attached
4. Bring up the Console app (for iOS logs) or adb logcat for Android. 
5. Open the application and click the button that will lead to the crash 
6. Inspect the logs. Notice on iOS the `UnhandledException` event is not raised and there are no logs except `+ + Crashing Application`

### Version with bug

Using dotnet 6.0.301 on a Mac, with Visual Studio for Mac 17.3 Preview (17.3 build 1038). 

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15.4

### Did you find any workaround?

No. I noticed it sometimes works if **with the debugger attached.**

**Comment by jsuarezruiz** [comment] 2022-07-04 10:37
Verified with the attached sample.

**Comment by rolfbjarne** [comment] 2022-09-20 05:43
This is a duplicate of https://github.com/xamarin/xamarin-macios/issues/15252.

**Closed by rolfbjarne** 2022-09-20 05:43 UTC
Labels: t/bug, platform/iOS 🍎, s/verified, s/triaged
