### ISSUE TITLE
Error in the manifest when I try to register ActionBootCompleted (MAUI Android)

### ISSUE THREAD

**Issue by ComptonAlvaro** [dotnet/maui#15009] opened 2023-05-10 09:05 UTC
### Description

I am trying to create BroadcastReceiver to allow the application to start when the device starts. For that, I am following this documentation: https://learn.microsoft.com/es-es/xamarin/android/app-fundamentals/broadcast-receivers

In this documentation, I am trying to follow this code:

```cs
[BroadcastReceiver(Enabled = true)]
[IntentFilter(new[] { Android.Content.Intent.ActionBootCompleted })]
public class MyBootReceiver : BroadcastReceiver
{
    public override void OnReceive(Context context, Intent intent)
    {
        // Work that should be done when the device boots.     
    }
}
```

In my code, I have this class in Platforms\Android:

```cs
using Android.App;
using Android.Content;


namespace ForegroundService;


[BroadcastReceiver(Enabled = true)]
[IntentFilter(new[] { Android.Content.Intent.ActionBootCompleted })]
public class BootReceiver : BroadcastReceiver
{
    public override void OnReceive(Context context, Intent intent)
    {
        //HACER ALGO
        string hola = "";
        hola = " ";
    }
}
```

But when I compile, I get the error AMM000. En error in the AndroidManifes.xml file. This is autogenerated code and the error is this:

```xml
    <receiver android:enabled="true" android:name="crc6472e0abee7db34fed.BootReceiver">
      <intent-filter>
        <action android:name="android.intent.action.BOOT_COMPLETED" />
      </intent-filter>
    </receiver>
```

If I comment the attribute [IntentFilter(new[] { Android.Content.Intent.ActionBootCompleted })] then I can compile.

How could I configure my receiver to can starts my application when the devices starts?

Thanks.

### Steps to Reproduce

1.- Create a new MAUI project
2.- In Platforms\Android, create a new class
3.- Copy the code of the class that I indicate in the post
4.- Try to compile

### Link to public reproduction project repository

I think it is not needed in this case. Just create a class and compile.

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 8.1 API 27

### Did you find any workaround?

I can't found a solution.

**Comment by jenscski** [comment] 2023-05-10 10:06
In my working code, I also have added Exported=true to the BroadcastReceiver
`[BroadcastReceiver(Enabled = true, Exported = true)]`

And I have added the following to the AndroidManifest.xml
`<uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />`

**Comment by ComptonAlvaro** [comment] 2023-05-10 11:00
It works, thank you so much,

**Comment by mattleibow** [comment] 2023-05-10 18:18
@davidbritch

**Comment by mattleibow** [comment] 2023-11-03 17:56
Duplicate of https://github.com/MicrosoftDocs/xamarin-docs/issues/3571

**Closed by mattleibow** 2023-11-03 17:56 UTC
Labels: t/bug, platform/android 🤖, t/docs 📝, area/platform
