### ISSUE TITLE
NullPointer from ShellPageRendererTracker on iOS

### ISSUE THREAD

**Issue by Larhei** [dotnet/maui#19505] opened 2023-12-19 18:48 UTC
### Description

When navigating to a Page containing a
`Shell.SearchHandler>`
With a custom QueryIcon I get the following Exception

`Unhandled Exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Maui.ImageSourceExtensions.GetPlatformImageAsync(IImageSource imageSource, IMauiContext mauiContext)
   at Microsoft.Maui.ImageSourceExtensions.LoadImage(IImageSource source, IMauiContext mauiContext, Action`1 finished)
   at Microsoft.Maui.Controls.Platform.Compatibility.ShellPageRendererTracker.SetSearchBarIcon(UISearchBar searchBar, ImageSource source, UISearchBarIcon icon)
   at Microsoft.Maui.Controls.Platform.Compatibility.ShellPageRendererTracker.AttachSearchController()
   at Microsoft.Maui.Controls.Platform.Compatibility.ShellPageRendererTracker.set_SearchHandler(SearchHandler value)
   at Microsoft.Maui.Controls.Platform.Compatibility.ShellPageRendererTracker.UpdateShellToMyPage()
   at Microsoft.Maui.Controls.Platform.Compatibility.ShellPageRendererTracker.SetAppeared()
   at Microsoft.Maui.Controls.Platform.Compatibility.ShellPageRendererTracker.CheckAppeared()
   at Microsoft.Maui.Controls.Platform.Compatibility.ShellPageRendererTracker.OnPageSet(Page oldPage, Page newPage)
   at Microsoft.Maui.Controls.Platform.Compatibility.ShellPageRendererTracker.set_Page(Page value)
   at Microsoft.Maui.Controls.Platform.Compatibility.ShellSectionRootRenderer.ViewDidLoad()
`

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

8.0.3

### Affected platforms

iOS

### Affected platform versions

iOS

**Comment by PureWeen** [comment] 2023-12-19 19:09
Duplicate of #14442

**Closed by PureWeen** 2023-12-19 19:09 UTC
Labels: t/bug
