### ISSUE TITLE
[Blazor,WebView2] HTML <select> dropdown Display In Wrong Position When Moving Window  

### ISSUE THREAD

**Issue by Brosinski** [dotnet/maui#10158] opened 2022-09-16 09:15 UTC
### Description

When using an HTML **select** within a Webview, after moving the MUAI window, the drop-down menu will remain where the **select**  was before the MUAI screen was moved, not under the **select**  in the new position. 
 
Maui Blazor projects simply do not update the select options position unless the screen is unfocused then refocused on, or if the screen is resized. Other than that if you move the Maui Window around without resizing, the select options will not update their position and hover inexplicably in the middle of the screen.

I've tried using Vanilla Microsoft.Web.WebView2 within a Maui XAML project, and that at least updates the new position of the element and displays in the correct spot after a couple of seconds, but the issue can still be recreated within that 3-4 second Timeframe.

### Steps to Reproduce

- Create a new MAUI project and set up some HTML to be rendered with either Blazor or Microsoft.Web.WebView2.

- In the HTML delcare a **select** with some options

- Start the App click the **select** , move the Maui Window (**WITHOUT RESIZING OR CLICKING OUT OF SCREEN**) and click the **select**  again

-  Observe the erroneous menu placement

### Link to public reproduction project repository

https://github.com/Brosinski/BrokenSelectMauiWebView2

### Version with bug

6.0.486 (current)

### Last version that worked well

6.0 Release Candidate 2 or older

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

WIN10

### Did you find any workaround?

No

**Comment by mkArtakMSFT** [comment] 2022-09-20 16:52
@Eilon can you please pass this to the WebView folks? Thanks!

**Comment by mkArtakMSFT** [comment] 2022-09-20 16:53
Looks like this a dupe of https://github.com/MicrosoftEdge/WebView2Feedback/issues/2290

**Closed by mkArtakMSFT** 2022-09-20 16:53 UTC
Labels: t/bug, area/blazor 🕸️, external

**Comment by Eilon** [comment] 2022-09-21 22:05
Hi, for anyone running into this issue, we think we found a _workaround_, which should help you with your existing apps. Please read this comment for how to work around this issue: https://github.com/MicrosoftEdge/WebView2Feedback/issues/2290#issuecomment-1254273563

**Comment by Brosinski** [comment] 2022-09-26 07:31
The above wokaround does not work.

This is a working workaround. Worked for me running .NET MAUI Blazor.

https://github.com/MicrosoftEdge/WebView2Feedback/issues/2290#issuecomment-1257595816
