### ISSUE TITLE
Off color Switch bar

### ISSUE THREAD

**Issue by Remusqs1** [dotnet/maui#17939] opened 2023-10-10 19:12 UTC
### Description

The color of the Switch bar in the off state doesn't look good when the background color is dark. Currently, you can style the Switch bar for the On state with the OnColor property, but there is no similar property for the off state (the background property creates a rectangle around the entire Switch, so it's not useful in most cases).

I searched in the official Microsoft and .Net Maui documentation, but it doesn't seem like there's a way to style the bar in the off state. There is a post on StackOverflow that says that there is currently no way to do this: (https://stackoverflow.com/questions/74712389/net-maui-change-off-color-of-switch).

Also, as mentioned @davidbritch [here](https://github.com/dotnet/docs-maui/issues/1709), there's no way to currently do this.

Would it be possible to add a property to the Switch in the future to handle this case (something similar to OnColor, maybe "OffColor")?

Thank you in advance for your help.

### (Public) API Changes

Add an OffColor property on the Switch Control

### Usage Scenarios

I want to have an OffColor property on the Switch Control that allow the developers to set the color of the switch bar when the status is off.

# XAML Example
```xaml
`<Switch OnColor="Green" OffColor="Grey" ThumbColor="White" >`
```

### Backward Compatibility

There should be no breaking changes as fas as I understand

### Difficulty

Low

**Comment by PureWeen** [comment] 2024-05-07 07:55
Duplicate of #21863

**Closed by PureWeen** 2024-05-07 07:55 UTC
Labels: t/enhancement ☀️, proposal/open, area/controls 🎮, control-switch
