### ISSUE TITLE
Running on windows 11 doesn't live up to expectations, but Android is right

### ISSUE THREAD

**Issue by caoyiliang** [dotnet/maui#11547] opened 2022-11-22 08:57 UTC
### Description

[Calc.zip](https://github.com/dotnet/maui/files/10065643/Calc.zip)
Running on windows 11 doesn't live up to expectations, but Android is right

### Steps to Reproduce

[Calc.zip](https://github.com/dotnet/maui/files/10065653/Calc.zip)
Running on windows 11 doesn't live up to expectations, but Android is right

### Link to public reproduction project repository

https://github.com/dotnet/maui/files/10065653/Calc.zip

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

windows

**Comment by caoyiliang** [comment] 2022-11-22 16:41
Thank you for your letter, I will reply as soon as possible

**Comment by PureWeen** [comment] 2022-11-22 19:17
Can you include some screen shots with expectations?

**Comment by caoyiliang** [comment] 2022-11-23 00:42
windows: The first input deletion is normal; After the second delete, the delete button is still gray, but it can be used.
Normal on android

**Comment by caoyiliang** [comment] 2022-11-23 01:08
https://user-images.githubusercontent.com/67636300/203451234-be823bff-f9ba-4321-b645-941da6c0cbb2.mp4

**Comment by caoyiliang** [comment] 2022-11-23 01:21
Left:windows: The first input deletion is normal; After the second delete, the delete button is still gray, but it can be used.
Normal on android

**Comment by Providenceee** [comment] 2022-11-23 18:17
> https://user-images.githubusercontent.com/67636300/203451234-be823bff-f9ba-4321-b645-941da6c0cbb2.mp4 Left:windows: The first input deletion is normal; After the second delete, the delete button is still gray, but it can be used. Normal on android

Encountered this visual bug too.

**Comment by mattleibow** [comment] 2022-11-24 19:29
Duplicate of #7377

**Comment by mattleibow** [comment] 2022-11-24 19:30
I also see CanExecute in the code, so a duplicate of #9753

**Comment by mattleibow** [comment] 2022-11-24 19:30
Duplicate of #9753

**Closed** 2022-11-24 19:30 UTC
Labels: t/bug, area/Xaml </>, platform/windows 🪟, area/controls 🎮, control-button
