### ISSUE TITLE
Rendering with MaximumHeightRequest is inconsistent across platforms

### ISSUE THREAD

**Issue by billreiss** [dotnet/maui#16953] opened 2023-08-23 16:01 UTC
### Description

When specifying MaximumHeightRequest on a ScrollView, the size of the ScrollView is inconsistent across platforms. On Windows and iOS, the ScrollView only takes up as much space as is needed for the content of the label. On Android, the ScrollView is the height of the value specified in the MaximumHeightRequest always. Here is a shot of iOS vs Windows vs Android.

<img width="833" alt="image" src="https://github.com/dotnet/maui/assets/1813417/fb9597e3-472a-4151-ba29-74bfd0a685a2">

This is on the latest Preview using .NET 8 but this happens on 7 as well.

### Steps to Reproduce

1. Create a new .NET MAUI App
2. Replace the contents of the MainPage.xaml with the following and remove the event handler:

```
    <Grid RowDefinitions="auto,*">
        <ScrollView MaximumHeightRequest="400" BackgroundColor="Yellow">
            <Label BackgroundColor="Green" TextColor="White">This is some text</Label>
        </ScrollView>
    </Grid>
```

3. Run on Windows, iOS, and Android and see that Android ScrollView is 400 pixels tall while the other platforms only take as much space as necessary.

### Version with bug

8.0.0-preview.7.8842

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android API 33

### Did you find any workaround?

No

**Comment by hartez** [comment] 2023-08-23 18:11
Duplicate of #16464

**Closed by hartez** 2023-08-23 18:11 UTC
Labels: t/bug
