### ISSUE TITLE
Symbol packages are not generated

### ISSUE THREAD

**Issue by jtheisen** [dotnet/maui#11408] opened 2022-11-16 12:51 UTC
### Description

Symbol packages are required to get crash reports in the Microsoft Store.

A freshly created MAUI app says, during publishing,

    Path to `mspdbcmf.exe` could not be found. A symbols package will not be generated.

There are indeed no pdbs in the package.

I've never seen this work in previous versions either.

### Steps to Reproduce

Create a new MAUI Project.

Click Publish and tell the Wizard to include public symbol files.
I used sideloading, no signing, and this is the publish profile:

```xml
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <PublishDir>bin\Debug\net6.0-android\publish\</PublishDir>
    <PublishProtocol>FileSystem</PublishProtocol>
    <RuntimeIdentifier>win10-x86</RuntimeIdentifier>
    <Platform>Any CPU</Platform>
    <Configuration>Debug</Configuration>
    <TargetFramework>net6.0-windows10.0.19041.0</TargetFramework>
    <PublishSingleFile>false</PublishSingleFile>
    <PublishReadyToRun>false</PublishReadyToRun>
    <SelfContained>True</SelfContained>
    <PublishAppxPackage>true</PublishAppxPackage>
    <AppxPackageDir>bin\Debug\net6.0-windows10.0.19041.0\win10-x64\AppPackages\</AppxPackageDir>
  </PropertyGroup>
</Project>
```

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

net6.0-windows10.0.19041.0

### Did you find any workaround?

There's a possibility to tell the MAUI build targets where the tool is by adding this to the project file:

```xml
<PropertyGroup>
  <MsPdbCmfExeFullpath>..\tools\MsPdbCmf.exe</MsPdbCmfExeFullpath>
</PropertyGroup>
```

That makes the warning go away, although increasing verbosity shows more issues, including that if the tool isn't found at the location, the issue is just silently ignored.

If it is found, it says the pdbs are added (under debug verbosity logs). But looking into the packages shows they are not - so I doubt this would have any effect on the crash reports.

I also posted [this question on SO](https://stackoverflow.com/questions/74446401/crash-reports-from-microsoft-store-for-net-maui-apps) earlier.

**Comment by mattleibow** [comment] 2022-11-16 19:14
Duplicate of https://github.com/microsoft/WindowsAppSDK/issues/2963

**Closed by mattleibow** 2022-11-16 19:14 UTC
Labels: t/bug, platform/windows 🪟, area/publishing 🏁

**Comment by jtheisen** [comment] 2022-11-16 19:45
Well, is there a workaround in the meantime?
