### ISSUE TITLE
HttpClient in AndroidApp crash again

### ISSUE THREAD

**Issue by ssccinng** [dotnet/maui#6460] opened 2022-04-25 00:51 UTC
### Description

Crash occurs when httpclient is used to access the API，No crash in previous versions。

### Steps to Reproduce

use
`dotnet publish -f net6.0-android -c Release`
build apk, Then run the app on your phone
If httpclient is used, it will crash and try catch will not catch errors

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android11

### Did you find any workaround?

I found a strange step to solve this problem.
1, pack apk.
2, remove `<uses-permission android:name="android.permission.INTERNET" />` in AndroidManifest.xml (Maybe any other setting)
3, pack apk again
4. add `<uses-permission android:name="android.permission.INTERNET" />` in AndroidManifest.xml 
5. pack apk again
6. if the packaged apk becomes smaller, the bug may be fixed

**Comment by VincentBu** [comment] 2022-04-25 01:41
not repro on 17.3.0 preview 1.0 [32420.421.main]. @ssccinng,  would you like to verify the attached project? 
[MauiApp6460.zip](https://github.com/dotnet/maui/files/8551029/MauiApp6460.zip)

**Comment by RedChops** [comment] 2022-04-25 01:48
I was just about to post a bug for this myself. I can't get any iteration of HttpClient working (managed or native). Native crashes the app immediately on launch, Managed acts incredibly strangely. It appears to crash from a NullReferenceException, but sometimes it crashes silently, causing all code that would otherwise use the result of SendAsync to be skipped.

For example:

1. var result = await client.SendAsync(...);
2. var content = await result.Content.ReadAsStringAsync()
3. [something else]

If I set a breakpoint on line 2, that breakpoint will get skipped and code will continue to execute on line 3, causing both result and content to be null.

I spent a large part of the day uninstalling all VS versions, clearing out the dotnet folder of all SDKs, reinstalling everything, etc, so everything should be clean and at the latest version.

I've attached here a small reproduction project. 

[NetworkTest.zip](https://github.com/dotnet/maui/files/8551024/NetworkTest.zip)

@VincentBu I tried your example and it appears to work through the debugger, even though the UI state doesn't update.

**Comment by RedChops** [comment] 2022-04-25 01:54
Though, I can't find this VS 17.3.0 preview 1.0 that's mentioned in many comments on tickets here, so who knows if it's fixed there.

**Comment by drasticactions** [comment] 2022-04-25 03:31
VS 17.3 P1 isn't out yet, but it doesn't really matter in this case. It's going to be an SDK issue, not an IDE one.
[AndroidNetworkTest.zip](https://github.com/dotnet/maui/files/8551378/AndroidNetworkTest.zip)

Trying this on my Mac with Android SDK 32.0.300-rc.2.18 
and MAUI 6.0.300-rc.2.5470, @RedChops's app crashed when I clicked on it. Wanting to try it on Android without MAUI,  [AndroidNetworkTest.zip](https://github.com/dotnet/maui/files/8551380/AndroidNetworkTest.zip)

Surprisingly, it worked. Same code. I'm not sure how MAUI is influencing this, but something weird is going on. @jonathanpeppers  any ideas?

**Comment by VincentBu** [comment] 2022-04-25 05:35
@drasticactions, you are right. Additionally, [RedChops](https://github.com/RedChops)'s code works on windows but fails on Android.

**Comment by MagicAndre1981** [comment] 2022-04-25 13:33
> not repro on 17.3.0 preview 1.0 [32420.421.main]. 

you use a version [that includes the fix](https://github.com/xamarin/xamarin-android/pull/6923), so you can't repro it.

**Comment by jonathanpeppers** [comment] 2022-04-25 13:47
I think this is the same as:
https://github.com/dotnet/runtime/issues/67402

Fixed by:
https://github.com/dotnet/runtime/pull/67746

Which will be in MAUI RC 2. Does the crash go away if you diable AOT for your Release build `<RunAOTCompilation>false</RunAotCompilation>`?

**Comment by RedChops** [comment] 2022-04-25 14:19
@jonathanpeppers  Well, I had an initial bit of hope. In the app that I'm developing, explicitly disabling AOT did let one request go through, but not another one. In the project I had uploaded a couple comments up, disabling AOT doesn't do anything for the sample request that it makes.

This is all using System.Net.Http.HttpClientHandler, Managed, as the HttpClient. I'm not sure if it's at all related, but if I set the HttpClient to use Xamarin.Android.Net.AndroidClientHandler, Android, instead the app crashes on launch instantly with a SIGSEGV SEGV_ACCERR.

**Comment by ssccinng** [comment] 2022-04-25 14:29
<RunAOTCompilation>false</RunAOTCompilation>

**Comment by RedChops** [comment] 2022-04-25 15:19
@jonathanpeppers  I have two logs here, both generated from my NetworkTest project uploaded above.

The first is [AndroidClientHandler.adb.txt](https://github.com/dotnet/maui/files/8555811/AndroidClientHandler.adb.txt) which is the output from using the Android HttpClient. 

The second is [HttpClientHandler.adb.txt](https://github.com/dotnet/maui/files/8555832/HttpClientHandler.adb.txt). This of course includes the output from the AndroidClientHandler log since it's the same emulator boot.

Both of these logs were generated off that sample project which I created fresh specifically for this bug, so there shouldn't be anything else weird going on there. They also both were run in Debug mode with <RunAOTCompilation>False</RunAOTCompilation> set in the csproj.

**Comment by jonathanpeppers** [comment] 2022-04-25 15:52
@RedChops so if you're seeing this in a Debug build, then `RunAOTCompilation=false` won't help, because it is only enabled during Release builds by default.

I filed a new issue to track this here: https://github.com/xamarin/xamarin-android/issues/6961

@ssccinng seems to be the problem we solved. So closing for now, thanks! MAUI RC 2 should hopefully work for you, and I'd use the workaround for now.

**Closed by jonathanpeppers** 2022-04-25 15:52 UTC
Labels: t/bug, platform/android 🤖, fatal, s/verified, s/needs-attention

**Comment by PieEatingNinjas** [comment] 2022-05-10 12:18
> I think this is the same as: [dotnet/runtime#67402](https://github.com/dotnet/runtime/issues/67402)
> 
> Fixed by: [dotnet/runtime#67746](https://github.com/dotnet/runtime/pull/67746)
> 
> Which will be in MAUI RC 2. Does the crash go away if you diable AOT for your Release build `<RunAOTCompilation>false</RunAotCompilation>`?

To me it seems like it's not fixed in RC 2...

Using RC 2, I'm  getting the APK working, only when adding the above ( `<RunAOTCompilation>False</RunAOTCompilation>` ). Without it, the app crashes as soon as I'm making an API/web call. 


[Repro](https://github.com/dotnet/maui/files/8661339/MauiApp53.zip)

When I publish this app (`dotnet publish -f:net6.0-android --configuration Release --output "c:/temp"`), and install the resulting APK on Android, I get the following behavior:

- Crash when clicking the button
- No Crash when clicking the button when `<RunAOTCompilation>False</RunAOTCompilation>` was added to csproj.

I'm on RC 2:
![image](https://user-images.githubusercontent.com/13808075/167626198-d3493a5d-bfd1-46c4-aa0a-29418ace6750.png)

**Comment by jonathanpeppers** [comment] 2022-05-10 20:07
@PieEatingNinjas can you try MAUI RC 3 that just shipped? dotnet/runtime 6.0.5 did not ship until today as well.

**Comment by PieEatingNinjas** [comment] 2022-05-10 20:37
> @PieEatingNinjas can you try MAUI RC 3 that just shipped? dotnet/runtime 6.0.5 did not ship until today as well.

I’ll give it a try tomorrow and will let you know the results.

**Comment by PieEatingNinjas** [comment] 2022-05-13 16:34
Sorry for the delay. 
But I can confirm that it seems to be working just fine in RC 3. No need to add `<RunAOTCompilation>False</RunAOTCompilation>`

**Comment by sharpninja** [comment] 2022-05-19 14:44
Just to be clear, using SDK `6.0.300` fixes this?

**Comment by jonathanpeppers** [comment] 2022-05-19 16:16
If you have `C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Runtime.Mono.android-*\6.0.5`, then you have the fix.

**Comment by sharpninja** [comment] 2022-05-19 17:19
OK, I have verified I am on the correct version, but I am still seeing this error in Uno Platform.  Here is the [discussion](https://github.com/unoplatform/uno/discussions/8823)

**Comment by jonathanpeppers** [comment] 2022-05-19 17:25
I mean your error is different? `NullReferenceException`? I would try to make a repro in a `dotnet new android` project and file an issue here:

https://github.com/xamarin/xamarin-android/issues

Thanks!
