### ISSUE TITLE
LineBreakMode cannot be used on a button on Windows

### ISSUE THREAD

**Issue by pekspro** [dotnet/maui#10553] opened 2022-10-07 20:16 UTC
### Description

It looks like the `LineBreakMode` value on buttons is ignored on Windows. Here I have two identical buttons where the text doesn't fit, but the lower on has set `LineBreakMode` to `TailTruncation`:

![image](https://user-images.githubusercontent.com/3163293/194645323-d628700c-b69e-4668-830f-b2433b78edf5.png)

But it does work on Android:

![image](https://user-images.githubusercontent.com/3163293/194645670-dccbee79-a798-4179-b3ee-6f07f80932a2.png)

Also, note that you cannot see the beginning of the text on Windows.

### Steps to Reproduce

1. Create a new MAUI app.
2. Update MainPage.xaml:

``` XAML
<ScrollView>
    <VerticalStackLayout 
        Spacing="25" 
        Padding="30,0" 
        Margin="0,20,0,0"
        >

        <Button 
            Text="one two three four five six seven eight nine ten"
            MaximumWidthRequest="300"
            HorizontalOptions="Center" />

        <Button 
            Text="one two three four five six seven eight nine ten"
            MaximumWidthRequest="300"
            LineBreakMode="TailTruncation"
            HorizontalOptions="Center" />

    </VerticalStackLayout>
</ScrollView>
```

### Link to public reproduction project repository

https://github.com/pekspro/MauiIssues/tree/10553_LineBreakMode_cannot_be_used_on_a_button_on_Windows

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows, I was *not* able test on other platforms

### Affected platform versions

Windows 10.0.17763.0, Android 11

**Comment by jsuarezruiz** [comment] 2022-10-11 10:19
Duplicated https://github.com/dotnet/maui/issues/9277

**Comment by pekspro** [comment] 2022-11-11 17:20
I've updated sample application to .NET 7. The same issue remains.

**Comment by hartez** [comment] 2023-01-27 22:20
Duplicate of #9277

**Closed by hartez** 2023-01-27 22:20 UTC
Labels: t/bug, s/duplicate 2️⃣, platform/windows 🪟, area/controls 🎮, control-button
