### ISSUE TITLE
Rendering after IsVisible flip is messed up

### ISSUE THREAD

**Issue by mike3sullivan** [dotnet/maui#6069] opened 2022-04-13 15:12 UTC
### Description

When using IsVisible for complex components, portions of some of the components are not rendered properly.

### Steps to Reproduce

1. create a new Maui App
2. add backgroundcolor to the image
3. change the button code behind to toggle visibility of the image
4. note that the background color does not disappear (Android, Windows) but the image does
5. Second example: Grid (with backgroundcolor and margin) inside a frame [Windows]. 
6. when toggling visibility off/on, margins are ignored when it appears
![visibility-bug](https://user-images.githubusercontent.com/26934129/163210792-543e6da6-8b01-47af-9d70-69199a62badc.png)
![visibility-bug2](https://user-images.githubusercontent.com/26934129/163212189-ec07627b-cf0c-4579-a71f-dd214e0db739.png)
d

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows, I was *not* able test on other platforms

### Affected platform versions

Windows 10

### Did you find any workaround?

resizing the window on Windows fixes things

**Comment by kristinx0211** [comment] 2022-04-14 01:08
@mike3sullivan Thank you so much for your bug report! Unfortunately, we cannot reproduce your issue with the information above, could you provide a sample project/screenshots or more details that we can reproduce your issue? That should greatly speed up the process, thanks!

**Comment by mike3sullivan** [comment] 2022-04-14 01:30
For the second problem, starting with a templated new Maui App, replace content of MainPage.xaml:
`
    <Grid >
        <Grid.RowDefinitions>
            <RowDefinition Height="Auto"/>
            <RowDefinition Height="*"/>
            <RowDefinition Height="*"/>
        </Grid.RowDefinitions>
        <Grid.ColumnDefinitions>
            <ColumnDefinition Width="*"/>
            <ColumnDefinition Width="*"/>
            <ColumnDefinition Width="*"/>
        </Grid.ColumnDefinitions>
        <Button Grid.Row="0"
                Text="Click me"
                Clicked="OnCounterClicked"
                HorizontalOptions="Center" />
        <Frame x:Name="grid1"
                Grid.Row="1" BorderColor="Orange" Margin="15" >
            <Grid BackgroundColor="Blue" Margin="10" />
        </Frame>
        <Frame x:Name="grid2"
                Grid.Row="2" BorderColor="Orange" Margin="15" >
            <Grid BackgroundColor="Blue" Margin="10" />
        </Frame>
    </Grid>`

and in code behind , replace OnCounterClicked with:
`
	private void OnCounterClicked(object sender, EventArgs e)
	{
		bool vis = grid1.IsVisible;
		grid1.IsVisible = !vis;
	}

The problem is that the top grid/frame does not render properly when toggling IsVisible off/on. Bottom grid/frame is for reference. Per blue box image above. 

In further testing, this appears to be the Frame that is causing the problems. If the Page is opened with the Frame not visible, it cannot be made visible without resizing the Window. If the Frame is not visible and the Window is resized, when the frame is made visible it still has the old dimensions - it does not resize to the new layout. 

===

For the image background problem, starting with the new Maui App template, replace image in MainPage.xaml with:
`
                <Image IsVisible="{Binding visible}"
                Source="dotnet_bot.png" BackgroundColor="Red"
                SemanticProperties.Description="Cute dot net bot waving hi to you!"
                WidthRequest="250"
                HeightRequest="310"
                HorizontalOptions="Center" />   

and in code behind , replace OnCounterClicked with:
`
	private void OnCounterClicked(object sender, EventArgs e)
	{
		image.IsVisible = !image.IsVisible;
	}

The image will appear and disappear but the background block (red in image above) remains.

This becomes a problem if 2 images share the same space - when toggling one visible and one not, the remaining background can cover the other image.
`

**Comment by v-longmin** [comment] 2022-04-14 02:32
Verified repro on Windows10 & Android 12.0 - API31 with VS 17.2.0 preview 2.1 [32317.152]. Repro project:
[MauiApp9.zip](https://github.com/dotnet/maui/files/8485801/MauiApp9.zip)
[MauiApp10.zip](https://github.com/dotnet/maui/files/8485810/MauiApp10.zip)

**Comment by jsuarezruiz** [comment] 2022-04-21 07:33
Could be related with https://github.com/dotnet/maui/issues/5600

**Comment by davidortinau** [comment] 2022-04-30 13:38
I've observed this behavior testing #4849 as well

**Comment by Redth** [comment] 2022-05-04 14:31
#6794 might fix this

**Comment by mattleibow** [comment] 2022-05-04 18:45
Tested on Android now (without #6794) and the first example with 2 frames is working it seems.

**Comment by mattleibow** [comment] 2022-05-04 19:03
The example with the background sticking around is fixed in this PR: #6828

**Comment by mattleibow** [comment] 2022-05-04 19:37
Actually, my PR seems to have fixed both issues.

**Closed** 2022-05-05 07:05 UTC
Labels: t/bug, area/layout 🔲, p/0, area/controls 🎮, high, s/verified, s/triaged, delighter
