### ISSUE TITLE
[MacCatalyst] Content in ScrollView does not resize when the Window resize.

### ISSUE THREAD

**Issue by drasticactions** [dotnet/maui#8370] opened 2022-06-28 01:27 UTC
### Description

https://user-images.githubusercontent.com/898335/176067235-378d21a5-8ba0-4d55-a5a6-88660ed75929.mov

If you have content within a ScrollView, it does not resize when you resize the Window. It does work on Android, WinUI, and iOS.

### Steps to Reproduce

1. Create content within a scrollview
2. Resize it.

### Version with bug

6.0.400 (current)

### Last version that worked well

6.0.312

### Affected platforms

macOS

### Affected platform versions

MacCatalyst

**Comment by PureWeen** [comment] 2022-08-11 18:12
Closing in favor of partner issue for tracking https://github.com/dotnet/maui/issues/9349

**Closed by PureWeen** 2022-08-11 18:12 UTC
Labels: t/bug, platform/macOS 🍏, area/layout 🔲, partner, p/0, s/verified, s/triaged, i/regression

**Comment by samhouts** [comment] 2023-01-09 20:05
Duplicate of #9349
