### ISSUE TITLE
#if WINDOWS not working correctly when referencing code in a separate Maui project

### ISSUE THREAD

**Issue by JohnHDev** [dotnet/maui#6919] opened 2022-05-07 07:29 UTC
### Description

When setting the build device to Windows Machine and attempting to build, the above #if appears to be ignored.

### Steps to Reproduce

Modify MauiProgram.cs to include platform specific uses:

#if WINDOWS
using MyAppTest.Platforms.Windows;
#elif IOS
using MyAppTest.Platforms.iOS;
#elif ANDROID
using MyAppTest.Platforms.Android;
#endif

Add a service that is available in all 3 platform folders like so **but in a different Maui library project**:
            builder.Services.AddSingleton<IMyRepository, MyRepository>();

Select Windows Machine and then build, it fails as it tries to build all the platforms.
Select an iOS simulator and then build, it builds fine.

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows

### Did you find any workaround?

Yes, when working on windows specifically, comment out all the other elifs and uses so the #if isn't used.
Uncomment those when I want to work on iOS or Android.

Another, better work around. In the Maui startup project, add WINDOWS to the Build => General => net6.0-windowsxxx section. I don't know if that would add other complications though.

**Comment by drasticactions** [comment] 2022-05-07 14:57
A few things:

- I can't replicate what you're seeing with VS 17.2 Preview or 17.3 P1. I can switch my TFMs and those directives are switched correctly in the IDE. The build also works.
- Removing the MSBuild conditional from the default MAUI templates and using `dotnet build`, it also worked.
- This also, I believe, would not be an MAUI issue. MAUI doesn't control those identifiers, the runtime does. So if one of those directives is not working, I think it would need to go to https://github.com/dotnet/runtime 

Could you create a reproduction project showing this?

**Comment by drasticactions** [comment] 2022-05-07 15:16
Also, is your issue similar to https://github.com/dotnet/maui/issues/6815?

They put their files into nested folders and that wasn't picked up by the MAUI targets, which _would_ be an MAUI issue.

**Comment by JohnHDev** [comment] 2022-05-07 16:27
@drasticactions No, they are in the Platforms/Windows etc folders, no sub folders. 1 thing to note is that this is in a Maui library, not in the startup project.

Interestingly, I managed to 'fix' it by adding WINDOWS to the net6.0-windows-10.0.19041 section in General => Build, in the startup project.

If that doesn't help, I'll take a look at knocking together an example.

**Comment by JohnHDev** [comment] 2022-05-09 15:48
@mattleibow as I mentioned it is a Maui library, so yes it has platform folders with iOS, Android, Mac and Windows folders.
Unless I have misunderstood your comment?

**Comment by Eilon** [comment] 2022-05-09 16:39
@JohnHDev can you post your app to a GitHub repo so that we can investigate? There are a bunch of things that need to line up for this to work: both the MAUI app and the MAUI lib must have the various platform-specific Target Framework Monikers (TFM), such as net6.0-windows, net6.0-android, etc. And the correct `#if`'s must be used.

**Comment by jfversluis** [comment] 2022-05-10 08:20
Probably related to/duplicate of #6815

**Closed** 2022-05-19 01:00 UTC
Labels: t/bug, s/no-recent-activity, s/needs-repro
