### ISSUE TITLE
[regression/8.0.0-rc.1.9171] APP crashes when "minimized" at android

### ISSUE THREAD

**Issue by sarsey-walker** [dotnet/maui#17477] opened 2023-09-19 09:57 UTC
### Description

When running at android(I'm using android 13) if i click at "Home" button or "Overview" end try to come back to the app, it stuck at splash screen.  I have do close and open it again. 

This also happened when build at `release` mode ate preview 7, but now even at `debug` node is happens. 

### Steps to Reproduce

Create a .net MAUI blazor hybrid app with .net 8 
At `Platforms\Android\MainActivity.cs` add `NoHistory = true` after `MainLauncher = true, ` and run at android emulator or even a physical device 

### Link to public reproduction project repository

https://github.com/sarsey-walker/TodoApp

### Version with bug

8.0.0-rc.1.9171

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.92

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 13, android 11

**Comment by XamlTest** [comment] 2023-09-22 06:26
Verified this on Visual Studio Enterprise 17.8.0 Preview 2.0(8.0.0-rc.1.9171). Repro on Android 13.0-API33 with below Project:
[TodoApp.zip](https://github.com/dotnet/maui/files/12697481/TodoApp.zip)

![Android13](https://github.com/dotnet/maui/assets/97647558/c736e296-d5b3-402d-b88f-8872562c865d)

**Comment by sarsey-walker** [comment] 2023-09-24 23:43
Hi @moljac , sorry, my bad, I couldn't do the proper tests. I updated the Steps to Reproduce.
I can't tell if the promem is the `NoHistory` or the `Activity` attribute

**Comment by PureWeen** [comment] 2023-09-27 16:40
```
[System] Uncaught exception thrown by finalizer
[System] java.lang.IllegalStateException: Warning: Router objects should be explicitly closed when no longer required otherwise you may leak handles.
[System] 	at TM.finalize(chromium-TrichromeWebViewGoogle.apk-stable-410410681:4)
[System] 	at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:291)
[System] 	at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:278)
[System] 	at java.lang.Daemons$Daemon.run(Daemons.java:139)
[System] 	at java.lang.Thread.run(Thread.java:923)
[System] Caused by: java.lang.Exception: AutocloseableRouter allocated at:
[System] 	at TM.<init>(chromium-TrichromeWebViewGoogle.apk-stable-410410681:7)
[System] 	at DP.<init>(chromium-TrichromeWebViewGoogle.apk-stable-410410681:6)
[System] 	at org.chromium.content.browser.framehost.RenderFrameHostImpl.<init>(chromium-TrichromeWebViewGoogle.apk-stable-410410681:10)
[System] 	at org.chromium.content.browser.framehost.RenderFrameHostImpl.create(chromium-TrichromeWebViewGoogle.apk-stable-410410681:1)
[System] 	at J.N.MjidYpBx(Native Method)
[System] 	at org.chromium.content.browser.webcontents.WebContentsImpl.r0(chromium-TrichromeWebViewGoogle.apk-stable-410410681:3)
[System] 	at K7.g(chromium-TrichromeWebViewGoogle.apk-stable-410410681:5)
[System] 	at com.android.webview.chromium.WebViewChromium.postMessageToMainFrame(chromium-TrichromeWebViewGoogle.apk-stable-410410681:4)
[System] 	at android.webkit.WebView.postWebMessage(WebView.java:1971)
[System] 	at crc64d693e2d9159537db.WebKitWebViewClient_JavaScriptValueCallback.n_onReceiveValue(Native Method)
[System] 	at crc64d693e2d9159537db.WebKitWebViewClient_JavaScriptValueCallback.onReceiveValue(WebKitWebViewClient_JavaScriptValueCallback.java:31)
[System] 	at X6.a(chromium-TrichromeWebViewGoogle.apk-stable-410410681:1)
[System] 	at org.chromium.android_webview.AwContents.w(chromium-TrichromeWebViewGoogle.apk-stable-410410681:1)
[System] 	at xr.run(Unknown Source:4)
[System] 	at android.os.MessageQueue.nativePollOnce(Native Method)
[System] 	at android.os.MessageQueue.next(MessageQueue.java:335)
[System] 	at android.os.Looper.loop(Looper.java:183)
[System] 	at android.app.ActivityThread.main(ActivityThread.java:7656)
[System] 	at java.lang.reflect.Method.invoke(Native Method)
[System] 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
[System] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by PureWeen** [comment] 2023-11-03 20:37
@Eilon

**Comment by mattleibow** [comment] 2023-11-09 14:45
@PureWeen how did you get that log? I get the hang but it never crashes.

**Comment by mattleibow** [comment] 2023-11-09 14:57
I had a suspicion and I think the issue is with the fact that the activity is stopped/destroyed. I removed the `NoHistory` but then used the developer options to destroy activities. This made the issue happen again where this usually would work.

<img width="343" alt="image" src="https://github.com/dotnet/maui/assets/1096616/707b8752-d2d2-4f23-9394-3017a47a86ea">

**Comment by mattleibow** [comment] 2023-11-09 15:31
Just tested with a plain maui app and even tried with a webview. I used both `NoHistory` and destroy activities. All seemed fine. Looks to be blazor webview related.

**Comment by wyliang2023** [comment] 2023-11-22 08:35
I encountered the same issue with my MAUI Blazor App installed on a real Android phone. When I launch the app and switch it to the background by swiping up from the bottom of the screen, there is no problem when I click the app icon to launch it again. However, if I exit the app by swiping from the left to the right or from the right to the left of the screen, the app will get stuck at the splash screen when I click the app icon to launch it again.

**Comment by tonyyip1969** [comment] 2023-11-25 01:39
I encountered the same issue as well.

**Comment by Eilon** [comment] 2023-12-06 23:24
I can repro this too. After the app gets stuck back at the splash screen it appears to be hung. When I pause the app, one of the threads (Thread 1 in my case) seems stuck at this tack:

```
 	0x0 in System.Threading.Monitor.Monitor_wait	C#
 	0x24 in System.Threading.Monitor.ObjWait	C#
 	0xD in System.Threading.Monitor.Wait	C#
 	0x112 in System.Threading.ManualResetEventSlim.Wait	C#
 	0x37 in System.Threading.Tasks.Task.SpinThenBlockingWait	C#
 	0x7F in System.Threading.Tasks.Task.InternalWaitCore	C#
 	0x3 in System.Threading.Tasks.Task.InternalWait	C#
 	0x13 in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification	C#
 	0xA in System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd	C#
 	0x7 in System.Runtime.CompilerServices.TaskAwaiter.GetResult	C#
 	0x2F in Microsoft.AspNetCore.Components.WebView.Maui.BlazorWebViewHandler.DisconnectHandler at D:\a\_work\1\s\src\BlazorWebView\src\Maui\Android\BlazorWebViewHandler.Android.cs:70,5	C#
 	0x7 in Microsoft.Maui.Handlers.ViewHandler<Microsoft.AspNetCore.Components.WebView.Maui.IBlazorWebView,Android.Webkit.WebView>.OnDisconnectHandler at D:\a\_work\1\s\src\Core\src\Handlers\View\ViewHandlerOfT.cs:79,4	C#
 	0x13 in Microsoft.Maui.Handlers.ViewHandler.OnDisconnectHandler at D:\a\_work\1\s\src\Core\src\Handlers\View\ViewHandler.cs:214,4	C#
 	0x2 in Microsoft.Maui.Handlers.ElementHandler.DisconnectHandler at D:\a\_work\1\s\src\Core\src\Handlers\Element\ElementHandler.cs:112,4	C#
 	0x20 in Microsoft.Maui.Handlers.ElementHandler.Microsoft.Maui.IElementHandler.DisconnectHandler at D:\a\_work\1\s\src\Core\src\Handlers\Element\ElementHandler.cs:130,5	C#
 	0x64 in Microsoft.Maui.Controls.Element.SetHandler at D:\a\_work\1\s\src\Controls\src\Core\Element\Element.cs:918,6	C#
 	0x2 in Microsoft.Maui.Controls.Element.set_Handler at D:\a\_work\1\s\src\Controls\src\Core\Element\Element.cs:863,11	C#
 	0x18 in Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IElement.set_Handler at D:\a\_work\1\s\src\Controls\src\Core\VisualElement\VisualElement.cs:2031,5	C#
 	0xB0 in Microsoft.Maui.Platform.ElementExtensions.ToHandler at D:\a\_work\1\s\src\Core\src\Platform\ElementExtensions.cs:96,4	C#
 	0x2 in Microsoft.Maui.Platform.ElementExtensions.ToPlatform at D:\a\_work\1\s\src\Core\src\Platform\ElementExtensions.cs:127,4	C#
 	0x60 in Microsoft.Maui.Handlers.ContentViewHandler.UpdateContent at D:\a\_work\1\s\src\Core\src\Handlers\ContentView\ContentViewHandler.Android.cs:42,5	C#
 	0x1 in Microsoft.Maui.Handlers.ContentViewHandler.MapContent at D:\a\_work\1\s\src\Core\src\Handlers\ContentView\ContentViewHandler.Android.cs:47,4	C#
 	0x21 in Microsoft.Maui.PropertyMapper<Microsoft.Maui.IContentView,Microsoft.Maui.Handlers.IContentViewHandler>. at D:\a\_work\1\s\src\Core\src\PropertyMapper.cs:172,6	C#
 	0x17 in Microsoft.Maui.PropertyMapper.UpdatePropertyCore at D:\a\_work\1\s\src\Core\src\PropertyMapper.cs:47,4	C#
 	0x1D in Microsoft.Maui.PropertyMapper.UpdateProperties at D:\a\_work\1\s\src\Core\src\PropertyMapper.cs:82,5	C#
 	0xCB in Microsoft.Maui.Handlers.ElementHandler.SetVirtualView at D:\a\_work\1\s\src\Core\src\Handlers\Element\ElementHandler.cs:79,4	C#
 	0x2 in Microsoft.Maui.Handlers.ViewHandler<Microsoft.Maui.IContentView,Microsoft.Maui.Platform.ContentViewGroup>.SetVirtualView at D:\a\_work\1\s\src\Core\src\Handlers\View\ViewHandlerOfT.cs:53,4	C#
 	0x2 in Microsoft.Maui.Handlers.ContentViewHandler.SetVirtualView at D:\a\_work\1\s\src\Core\src\Handlers\ContentView\ContentViewHandler.Android.cs:26,4	C#
 	0x7 in Microsoft.Maui.Handlers.ViewHandler<Microsoft.Maui.IContentView,Microsoft.Maui.Platform.ContentViewGroup>.SetVirtualView at D:\a\_work\1\s\src\Core\src\Handlers\View\ViewHandlerOfT.cs:56,4	C#
 	0x8B in Microsoft.Maui.Controls.Element.SetHandler at D:\a\_work\1\s\src\Controls\src\Core\Element\Element.cs:921,6	C#
 	0x2 in Microsoft.Maui.Controls.Element.set_Handler at D:\a\_work\1\s\src\Controls\src\Core\Element\Element.cs:863,11	C#
 	0x18 in Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IElement.set_Handler at D:\a\_work\1\s\src\Controls\src\Core\VisualElement\VisualElement.cs:2031,5	C#
 	0xB0 in Microsoft.Maui.Platform.ElementExtensions.ToHandler at D:\a\_work\1\s\src\Core\src\Platform\ElementExtensions.cs:96,4	C#
 	0x2 in Microsoft.Maui.Platform.ElementExtensions.ToPlatform at D:\a\_work\1\s\src\Core\src\Platform\ElementExtensions.cs:127,4	C#
 	0x5A in Microsoft.Maui.Platform.MauiContextExtensions.ToPlatform at D:\a\_work\1\s\src\Core\src\Platform\Android\MauiContextExtensions.cs:96,4	C#
 	0x38 in Microsoft.Maui.Platform.NavigationViewFragment.OnCreateView at D:\a\_work\1\s\src\Core\src\Platform\Android\Navigation\NavigationViewFragment.cs:56,4	C#
 	0x24 in AndroidX.Fragment.App.Fragment.n_OnCreateView_Landroid_view_LayoutInflater_Landroid_view_ViewGroup_Landroid_os_Bundle_ at C:\a\_work\1\s\generated\androidx.fragment.fragment\obj\Release\net6.0-android\generated\src\AndroidX.Fragment.App.Fragment.cs:2031,4	C#
 	0xD in Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPLLL_L at /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:367,5	C#
```

And I wonder if it's a deadlock because it's trying to [block on an async call from a sync method](https://github.com/dotnet/maui/blob/main/src/BlazorWebView/src/Maui/Android/BlazorWebViewHandler.Android.cs#L62-L81). I'm not sure _why_ it would deadlock, but this pattern is known to be risky regarding deadlocks.

**Comment by Eilon** [comment] 2023-12-08 00:14
I go the MAUI Controls.Sample app to repro the same problem by simply taking nearly everything out of it until it was trivial. This also let me debug things more easily, and it definitely looks like a deadlock during disposal of the WebViewManager.

When I change the code in https://github.com/dotnet/maui/blob/main/src/BlazorWebView/src/Maui/Android/BlazorWebViewHandler.Android.cs#L62-L81 to be non-blocking by doing a "fire and forget" on the disposal, then everything works: after dismissing the app and coming back in, it starts from the beginning of the app.

As far as why thing are deadlocking during disposal, I'm still not sure. The only apparent culprits seem to be the WebViewJSRuntime and a query provider:
![image](https://github.com/dotnet/maui/assets/202643/50112399-97ea-4e93-a9aa-71011271e52d)

But I'm still not sure which of these (if any) are the cause.

**Comment by Eilon** [comment] 2023-12-13 17:34
Here are the options I see:

1. Do nothing. We could tell people to simply not use NoHistory on Android when using BlazorWebView on the main page. Obviously, not an ideal choice.
2. We could switch Android to do "fire and forget" for the disposal. This is safe from a deadlock perspective, but could have other unknown behaviors.
3. We could change to not dispose anything async at all and leave that "as an exercise to the reader." That is, if you _really_ care about disposal in your app, you have to hook it up yourself and call it "at an appropriate time." For apps that entirely consist of a BlazorWebView this might not be so bad because usually there's no disposal at all (the app just ends eventually, at which point disposal doesn't matter much).

**Comment by Eilon** [comment] 2023-12-13 18:42
This looks suspiciously similar to this issue (possibly a dup): https://github.com/dotnet/maui/issues/13529

**Comment by mkArtakMSFT** [comment] 2024-04-19 20:33
Closing as a dupe of the linked issue above.

**Closed by mkArtakMSFT** 2024-04-19 20:33 UTC
Labels: t/bug, platform/android 🤖, area/blazor 🕸️, s/verified, s/triaged, i/regression
