### ISSUE TITLE
Splashscreen not showing in Windows

### ISSUE THREAD

**Issue by GiannKarlo** [dotnet/maui#7602] opened 2022-05-30 08:47 UTC
### Description

I have implemented a splashscreen on my app . And I am not seeing my splashscreen on windows. Only on android/ios.

### Steps to Reproduce

1. Open ng project/ projectName.csproj
2. Add this line 
 MauiSplashScreen Include="Resources\appiconfg.sv"
3. Run the app

Expected Result : No splashscreen on windows

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows

### Did you find any workaround?

No

**Comment by VincentBu** [comment] 2022-06-01 03:13
repro with vs main build 32531.271.main

**Comment by deviprasad987** [comment] 2022-08-08 09:46
Any update in the issue

**Comment by mattleibow** [comment] 2022-11-03 23:00
Duplicate of #3870

Splash screens are not supported by Windows APP SDK / WinUI 3

There is an open issue in WinUI tracking this bug/feature: https://github.com/microsoft/microsoft-ui-xaml/issues/4055

Please let them know your feedback.

**Closed by mattleibow** 2022-11-03 23:00 UTC
Labels: t/bug, area/single project ☝️, s/verified
