### ISSUE TITLE
wrong splash screen shown under Android 12 (API 31), but is correct with Android 11

### ISSUE THREAD

**Issue by philipag** [dotnet/maui#6937] opened 2022-05-08 10:52 UTC
### Description

If you install and run the provided repro sample on Android 11 and 12 you will see that the wrong splash screen is shown under Android 12).  Note that on first run from VS no splash screen is shown at all so you need to restart the app.

### Steps to Reproduce

1. Compile and run the repro app under Android 11 and Android 12
2. Note the splash screen is shown correctly under Android 11 (robot), but under Android 12 appiconfg.svg is shown even though that is not what the splash screen is set to in csproj.

[layoutbug10.zip](https://github.com/dotnet/maui/files/8646846/layoutbug10.zip)

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 12 (Android 11 words OK)

### Did you find any workaround?

no

**Comment by v-longmin** [comment] 2022-05-09 02:02
Verified repro on Android 12.0 with VS 17.3.0 Preview 1.0 [32427.505.main]. Repro project:
[layoutbug10.zip](https://github.com/dotnet/maui/files/8648321/layoutbug10.zip)

**Comment by rachelkang** [comment] 2022-05-09 15:38
Yep, this is a duplicate of https://github.com/dotnet/maui/issues/3306 which was also closed

As I mentioned in https://github.com/dotnet/maui/issues/3306#issuecomment-1100304889:

> The splash screen does technically work on API 31+. The issue is that the splash screen icon does not render when the app is launched for the first time (i.e. from the IDE, from a launcher, etc). It does render properly when the app is terminated and restarted by clicking on the app icon. I've experimented with the new SplashScreen API that was introduced in API 31, and while there are changes, this issue at hand remains the same.
> 
> Moreover, this is consistent with the current behavior on the Android platform, and Android is aware of this issue. They're saying [this behavior is intended](https://issuetracker.google.com/issues/199776339#comment3), so it is unclear whether it will be changed. However, their new SplashScreen API is in beta, and there is some hope that they might [change this in a future stable release (1.1)](https://issuetracker.google.com/issues/216136037#comment4).
> 
> For the curious, here are some links to issues I've tracked down in the Android world:
> 
> https://issuetracker.google.com/issues/199776339
> https://issuetracker.google.com/issues/205021357
> https://issuetracker.google.com/issues/206630113
> https://issuetracker.google.com/issues/207386164
> https://issuetracker.google.com/issues/216136037
> We'll keep an eye out for any updates and revisit when they release a stable version of the SplashScreen API. In the meantime, if anyone has additional findings or discovers a workaround, you're always welcome to share!

**Closed by rachelkang** 2022-05-09 15:38 UTC
Labels: t/bug, area/single project ☝️, s/verified, s/triaged
