### ISSUE TITLE
ListView sets Cell's BindingContext to self, causing multiple warnings and/or InvalidCastExceptions

### ISSUE THREAD

**Issue by DanTravison** [dotnet/maui#13754] opened 2023-03-08 00:04 UTC
### Description

When ListView has an ItemsSource and ItemTemplate defined, the ViewCell.BindingContext for the ItemTemplate is initially set the BindingContext of the ListView itself instead of the associated ItemsSource value.

The problem occurs in Maui when the Element.SetParent  is called on the Cell. This calls BindableObject.SetInheritedBindingContext which ends up setting the ListView's BindingContext on the ViewCell instead of the intended value from the ItemsSource. This propogates down the contained View's ItemsSource which, in the StackLayout case, expects an IEnumerable. Since the ListView's BindingContext is not an IEnumerable, an InvalidCastException(Object must implement IConvertible) is raised by Convert.ChangeType. If the ListView's BindingContext does implement IEnumerable, a flood of BindingDiagnostics: Warnings occur for each Cell also due to the incorrect value.

I see this sequence occur twice for each cell as the ListView is populated causing a user noticeable delay in displaying the associated page.

With the simpler case of an ItemTemplate that does not bind to an IEnumerable, numerous warnings are output as each View binding is resolved.  For a large list, this is prohibitive.

The view eventually populates after multiple binding failures. In the InvalidCastException case, at least 2 failures per ItemsSource value occur before success.  I have not determined the number of failures for the 'simpler' case.

I can repro this on Windows but do not see it on iOS, macOS, or Android.

### Steps to Reproduce

See the referenced sample project.

### Link to public reproduction project repository

https://github.com/DanTravison/ListViewBinding

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

10.0.19041.0

### Did you find any workaround?

No.
The only way I've found to avoid the issue is to not use ListView.  However, I have not found a viable alternative that provides item-level scrolling.

**Comment by daltzctr** [comment] 2023-05-25 20:19
This makes ListView completely broken on WinUI, as you are not able to present views based on the binding

**Comment by homeyf** [comment] 2023-07-18 03:17
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 3.0(net8). Not repro on windows platform with sample project.
https://github.com/DanTravison/ListViewBinding
![image](https://github.com/dotnet/maui/assets/82450723/6d2074fe-a000-4c2b-ab9b-20fa40bf862b)

**Comment by daltzctr** [comment] 2023-07-18 04:18
Still occurs in .NET 8 Preview 6

**Comment by DanTravison** [comment] 2023-07-18 17:48
I've updated the sample to add a .Net 8 and Maui 8.0.0-preview.6.8686 solution and csproj.

**Comment by nor0x** [comment] 2023-09-05 17:51
still a critical issue with version 8.0.0-preview.7.8842 which completely breaks `CollectionView` and `ListView` (haven't tested with other collection controls) on Windows. I have the usecase of a `Button` inside a `CollectionView` that has a `Command` binding to the `ViewModel` and passes the current Item (`MyItem` class) as a `CommandParameter`.

Executing this command fails of course because the Type of the `CommandParameter` is `ViewModel` instead of `MyItem`
Error Message:
`Parameter "parameter" (object) cannot be of type MauiApp1.MainViewModel, as the command type requires an argument of type MauiApp1.MyItem. (Parameter 'parameter')`



StackTrace:
```
   at CommunityToolkit.Mvvm.Input.RelayCommand`1.ThrowArgumentExceptionForInvalidCommandArgument(Object parameter)
   at CommunityToolkit.Mvvm.Input.RelayCommand`1.Execute(Object parameter)
   at Microsoft.Maui.Controls.ButtonElement.ElementClicked(VisualElement visualElement, IButtonElement ButtonElementManager)
   at Microsoft.Maui.Controls.Button.SendClicked()
   at Microsoft.Maui.Controls.Button.Microsoft.Maui.IButton.Clicked()
   at Microsoft.Maui.Handlers.ButtonHandler.OnClick(Object sender, RoutedEventArgs e)
   at WinRT._EventSource_global__Microsoft_UI_Xaml_RoutedEventHandler.EventState.<GetEventInvoke>b__1_0(Object sender, RoutedEventArgs e)
   at ABI.Microsoft.UI.Xaml.RoutedEventHandler.Do_Abi_Invoke(IntPtr thisPtr, IntPtr sender, IntPtr e)
--- End of stack trace from previous location ---
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at ABI.Microsoft.UI.Xaml.Controls.IControlOverridesMethods.OnPointerReleased(IObjectReference _obj, PointerRoutedEventArgs e)
   at Microsoft.UI.Xaml.Controls.Control.OnPointerReleased(PointerRoutedEventArgs e)
   at Microsoft.UI.Xaml.Controls.Control.Microsoft.UI.Xaml.Controls.IControlOverrides.OnPointerReleased(PointerRoutedEventArgs e)
   at ABI.Microsoft.UI.Xaml.Controls.IControlOverrides.Do_Abi_OnPointerReleased_3(IntPtr thisPtr, IntPtr e)

```





And of course the output log is filled with Binding Diagnostic Errors:

```
Microsoft.Maui.Controls.Xaml.Diagnostics.BindingDiagnostics: Warning: 'ClickCommand' property not found on 'MauiApp1.MainViewModel', target property: 'Microsoft.Maui.Controls.Button.Command'
Microsoft.Maui.Controls.Xaml.Diagnostics.BindingDiagnostics: Warning: 'Name' property not found on 'MauiApp1.MainViewModel', target property: 'Microsoft.Maui.Controls.Label.Text'
Microsoft.Maui.Controls.Xaml.Diagnostics.BindingDiagnostics: Warning: 'Description' property not found on 'MauiApp1.MainViewModel', target property: 'Microsoft.Maui.Controls.Label.Text'
```
![image](https://github.com/dotnet/maui/assets/3210391/b130c038-989d-4edb-a7f3-18a2ee343195)



My Repro:

[MauiApp1.zip](https://github.com/dotnet/maui/files/12526644/MauiApp1.zip)

Related Issues:
https://github.com/dotnet/maui/issues/8433
https://github.com/dotnet/maui/issues/15579
https://github.com/dotnet/maui/issues/13754
https://github.com/dotnet/maui/issues/11956

anyone found a workaround yet? this used to be fine with .NET 7!

**Comment by samhouts** [comment] 2023-09-12 22:50
The ListVIew and CollectionView issues look similar, but they are very different, as far as I can tell. They do not share the same code that was changed in 8.0.0-preview1. The CollectionView issue is a regression in 8.0.0, but this ListView issue presents identically in both 7.0.0 and 8.0.0. 

Both are important, although the CollectionView issue takes priority as it is actually preventing the bindings from resolving and thus the application is broken entirely. From my testing, the ListView bindings do resolve, despite the many irritating warnings.

**Comment by samhouts** [comment] 2023-09-12 22:54
Duplicate of #8433

**Closed by samhouts** 2023-09-12 22:54 UTC
Labels: t/bug, area/ListView, s/triaged

**Comment by samhouts** [comment] 2023-09-12 22:58
If you're using a DataType on your DataTemplate and you find that the items are not showing up at all, you may be hitting this issue instead: https://github.com/dotnet/maui/issues/11956
