### ISSUE TITLE
[iOs] MAUI Blazor Hybrid '//' urls not treated as secure

### ISSUE THREAD

**Issue by Buyukcaglar** [dotnet/maui#19297] opened 2023-12-07 19:47 UTC
### Description

On my MAUI Blazor Hybrid Application I have to play some youtube videos on certain pages. But when Youtube's iframe embed url starts with 'https://' OS immediately switches to Youtube App to play relevant video (as soon as page renders), furthermore when I delete the Youtube App from iOs device, this time OS tries to open Safari to redirect Youtube website. In my research I've seen that to prevent OS to handover urls to their respective registred apps, only '//' url notation used, such that intead of using 'https://www.youtube.com/embed/aqz-KE-bpKQ', '//www.youtube.com/embed/aqz-KE-bpKQ' is being used. When I use '//' urls for embed iframe, this time I can see the iframes taking up space on page but nothing happens or loads. I tracked down the issue by inspecting app under desktop safari on a mac to '//' urls treated as unsecure, so webkit seems to refuse load content from the remote source. This behaviour is most likely due to Blazor WASM app itself resides inside an unsecured location (blazor resources, such as scripts and styles denoted as 'app://' url also deemed as unsecure in the inspection.

I can canfirm that '//' urls in the Windows port/target of app indeed works properly and does not have any kind of issues.

This behaviour effectively makes impossible to insert and play Youtube video embeds in MAUI Blazor App on iOs within the application.

Are there any workarounds to resolve this behaviour?

Note: For all tests I have deployed App to my iOS device using Visual Studio Hot Restart feature.

Edit: I can now confirm that problem does NOT exists on Android platform too, along with Windows.

Thanks,

### Steps to Reproduce

Put the following html snippet in any MUAI Blazor app to experience the 'automatic app switch' behaviour in iOs;

<iframe width="560" height="315" src="https://www.youtube.com/embed/aqz-KE-bpKQ?si=tS56Thymm_bzuknf" title="YouTube video player" frameborder="0" allowfullscreen></iframe>

and put the following html snippet to in any MAU Blazor app to see basically nothing happens (but indeed one can see the iframes created when inspected);

<iframe width="560" height="315" src="//www.youtube.com/embed/aqz-KE-bpKQ?si=tS56Thymm_bzuknf" title="YouTube video player" frameborder="0" allowfullscreen></iframe>

### Version with bug

8.0.3

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

**Comment by timmac-qmc** [comment] 2024-04-18 10:14
Encountering this issue too, can we get an update or solution?

**Comment by timmac-qmc** [comment] 2024-04-18 11:28
Worked out a fix:

MainPage.xaml.cs
`    public partial class MainPage : ContentPage
    {
        public MainPage()
        {
            On<iOS>().SetUseSafeArea(true);
            InitializeComponent();

            _blazorWebView.BlazorWebViewInitialized += BlazorWebViewInitialized;
            _blazorWebView.BlazorWebViewInitializing += BlazorWebViewInitializing;
            _blazorWebView.UrlLoading += BlazorUrlLoading;
        }

        private void BlazorUrlLoading(object? sender, UrlLoadingEventArgs e)
        {
#if IOS
            if (e.Url.Host == "www.youtube.com")
                e.UrlLoadingStrategy = UrlLoadingStrategy.OpenInWebView;
#endif
        }

        private void BlazorWebViewInitialized(object? sender, BlazorWebViewInitializedEventArgs e)
        {
#if ANDROID
            e.WebView.Settings.MediaPlaybackRequiresUserGesture = false;
#endif
        }

        private void BlazorWebViewInitializing(object? sender, BlazorWebViewInitializingEventArgs e)
        {
#if IOS
            e.Configuration.AllowsInlineMediaPlayback = true;
            e.Configuration.MediaPlaybackRequiresUserAction = false;
            e.Configuration.MediaTypesRequiringUserActionForPlayback = WebKit.WKAudiovisualMediaTypes.None;
#endif
        }
    }`

MainPage.xaml
`<BlazorWebView x:Name="_blazorWebView" HostPage="wwwroot/index.html">
    <BlazorWebView.RootComponents>
        <RootComponent Selector="#app" ComponentType="{x:Type local:Main}" />
    </BlazorWebView.RootComponents>
</BlazorWebView>`

**Comment by mkArtakMSFT** [comment] 2024-04-19 21:12
Closing as a dupe of https://github.com/dotnet/maui/issues/20887

**Closed by mkArtakMSFT** 2024-04-19 21:12 UTC
Labels: t/bug, area/blazor 🕸️, platform/iOS 🍎
