### ISSUE TITLE
Custom font cannot work for Android on RC2

### ISSUE THREAD

**Issue by shugaoye** [dotnet/maui#6712] opened 2022-05-01 02:50 UTC
### Description

I use FontAwesome in my test app. It works on all platforms before RC1. In RC2, it seems it does not work on Android build, but it works well on Windows and iOS/macOS. I tested on both Android emulator and phone.

```
Microsoft Visual Studio Community 2022
Version 17.2.0 Preview 5.0
VisualStudio.17.Preview/17.2.0-pre.5.0+32422.2
Microsoft .NET Framework
Version 4.8.04084
```

### Steps to Reproduce

1. Create a New MAUI App
2. Added custom font, such as fontawesome
3. Test it on all platforms

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Release Candidate 1

### Affected platforms

Android

### Affected platform versions

Android 9 - 11 tested

### Did you find any workaround?

I cannot find any workaround so far.

### Relevant log output

```shell
[AudioManager] playSoundEffect   effectType: 0
[AudioManager] querySoundEffectsEnabled...
[FLTAG_FM] loadFeature class:com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
[FLTAG_SFM] getRequireClassLoader() succ ! className: com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
[FeatureFactory] loadFeature() : com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
[FeatureFactory] loadFeature() new IHwSplineOverScrollerEx()
[HwSplineOverScrollerExImpl] initSplineOverScrollerImpl paras: android.widget.OverScroller$SplineOverScroller@8cf9351,crc64e4f94e2eb9c3336c.MainActivity@61e1655
[HwSplineOverScrollerExImpl] initSplineOverScrollerImpl: mScrollerVelocity is 0, value is 0
[FLTAG_FM] loadFeature class:com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
[FLTAG_SFM] getRequireClassLoader() succ ! className: com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
[FeatureFactory] loadFeature() : com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
[FeatureFactory] loadFeature() new IHwSplineOverScrollerEx()
[HwSplineOverScrollerExImpl] initSplineOverScrollerImpl paras: android.widget.OverScroller$SplineOverScroller@829138d,crc64e4f94e2eb9c3336c.MainActivity@61e1655
[HwSplineOverScrollerExImpl] initSplineOverScrollerImpl: mScrollerVelocity is 0, value is 0
[ViewRootImpl] jank_removeInvalidNode jank list is null
[AudioManager] playSoundEffect   effectType: 0
[AudioManager] querySoundEffectsEnabled...
[0:] AppShell: source=//AboutPage, target=//RootPage
[FLTAG_FM] loadFeature class:com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
[FLTAG_SFM] getRequireClassLoader() succ ! className: com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
[FeatureFactory] loadFeature() : com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
[FeatureFactory] loadFeature() new IHwSplineOverScrollerEx()
[HwSplineOverScrollerExImpl] initSplineOverScrollerImpl paras: android.widget.OverScroller$SplineOverScroller@2574918,crc64e4f94e2eb9c3336c.MainActivity@61e1655
[HwSplineOverScrollerExImpl] initSplineOverScrollerImpl: mScrollerVelocity is 0, value is 0
[FLTAG_FM] loadFeature class:com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
[FLTAG_SFM] getRequireClassLoader() succ ! className: com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
[FeatureFactory] loadFeature() : com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
[FeatureFactory] loadFeature() new IHwSplineOverScrollerEx()
[HwSplineOverScrollerExImpl] initSplineOverScrollerImpl paras: android.widget.OverScroller$SplineOverScroller@cd18156,crc64e4f94e2eb9c3336c.MainActivity@61e1655
[HwSplineOverScrollerExImpl] initSplineOverScrollerImpl: mScrollerVelocity is 0, value is 0
[TabLayout] MODE_SCROLLABLE + GRAVITY_FILL is not supported, GRAVITY_START will be used instead
[FLTAG_FM] loadFeature class:com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
[FLTAG_SFM] getRequireClassLoader() succ ! className: com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
[FeatureFactory] loadFeature() : com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
[FeatureFactory] loadFeature() new IHwSplineOverScrollerEx()
[HwSplineOverScrollerExImpl] initSplineOverScrollerImpl paras: android.widget.OverScroller$SplineOverScroller@48e48cf,crc64e4f94e2eb9c3336c.MainActivity@61e1655
[HwSplineOverScrollerExImpl] initSplineOverScrollerImpl: mScrollerVelocity is 0, value is 0
[FLTAG_FM] loadFeature class:com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
[FLTAG_SFM] getRequireClassLoader() succ ! className: com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
[FeatureFactory] loadFeature() : com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
[FeatureFactory] loadFeature() new IHwSplineOverScrollerEx()
[HwSplineOverScrollerExImpl] initSplineOverScrollerImpl paras: android.widget.OverScroller$SplineOverScroller@d0a2eb,crc64e4f94e2eb9c3336c.MainActivity@61e1655
[HwSplineOverScrollerExImpl] initSplineOverScrollerImpl: mScrollerVelocity is 0, value is 0
[monodroid-assembly] open_from_bundles: failed to load assembly KeePassLib.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Drawing.Primitives.dll
[monodroid-assembly] open_from_bundles: failed to load assembly PureOtp.dll
Loaded assembly: /data/data/com.passxyz.vault2/files/.__override__/KeePassLib.dll
Loaded assembly: /data/data/com.passxyz.vault2/files/.__override__/System.Drawing.Primitives.dll [External]
Loaded assembly: /data/data/com.passxyz.vault2/files/.__override__/PureOtp.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Newtonsoft.Json.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Security.Cryptography.Algorithms.dll
Loaded assembly: /data/data/com.passxyz.vault2/files/.__override__/Newtonsoft.Json.dll [External]
Loaded assembly: /data/data/com.passxyz.vault2/files/.__override__/System.Security.Cryptography.Algorithms.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly System.Runtime.Serialization.Formatters.dll
Loaded assembly: /data/data/com.passxyz.vault2/files/.__override__/System.Runtime.Serialization.Formatters.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly System.Diagnostics.TraceSource.dll
Loaded assembly: /data/data/com.passxyz.vault2/files/.__override__/System.Diagnostics.TraceSource.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly System.Linq.Expressions.dll
Loaded assembly: /data/data/com.passxyz.vault2/files/.__override__/System.Linq.Expressions.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly System.Runtime.Numerics.dll
Loaded assembly: /data/data/com.passxyz.vault2/files/.__override__/System.Runtime.Numerics.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly System.Data.Common.dll
Loaded assembly: /data/data/com.passxyz.vault2/files/.__override__/System.Data.Common.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly System.ComponentModel.Primitives.dll
Loaded assembly: /data/data/com.passxyz.vault2/files/.__override__/System.ComponentModel.Primitives.dll [External]
Loaded assembly: Anonymously Hosted DynamicMethods Assembly [External]
[0:] ItemsViewModel: Facebook, PxEntry | 2022-05-01 | Social Media
[0:] ItemsViewModel: Twitter, PxEntry | 2022-05-01 | Social media
[0:] ItemsViewModel: Google, PassXYZLib.PxEntry | 2022-05-01 | Search Engine
[.passxyz.vault] Explicit concurrent copying GC freed 8164(626KB) AllocSpace objects, 0(0B) LOS objects, 82% free, 2MB/14MB, paused 73us total 32.462ms
[0:] ItemsViewModel: GitHub, PassXYZLib.PxEntry | 2022-05-01 | Programming
[0:] ItemsViewModel: Amazon, PxEntry | 2022-05-01 | Shopping
[Choreographer] Skipped 110 frames!  The application may be doing too much work on its main thread.
[HwWechatOptimizeImpl] mIsEffect:false
[HwGalleryCacheManagerImpl] mIsEffect:false
[Choreographer] Skipped 52 frames!  The application may be doing too much work on its main thread.
[OpenGLRenderer] Davey! duration=2735ms; Flags=0, IntendedVsync=1580382770709, Vsync=1582216103969, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=1582223633090, AnimationStart=1582223742986, PerformTraversalsStart=1582224792986, DrawStart=1583081139340, SyncQueued=1583108518507, SyncStart=1583108636215, IssueDrawCommandsStart=1583109543507, SwapBuffers=1583116182569, FrameCompleted=1583118635173, DequeueBufferDuration=602000, QueueBufferDuration=517000, 
[ViewRootImpl] jank_removeInvalidNode jank list is null
[OpenGLRenderer] Davey! duration=926ms; Flags=0, IntendedVsync=1582246505941, Vsync=1583113172573, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=1583114372153, AnimationStart=1583114549757, PerformTraversalsStart=1583153716944, DrawStart=1583155754965, SyncQueued=1583159973194, SyncStart=1583160164340, IssueDrawCommandsStart=1583160938819, SwapBuffers=1583170262257, FrameCompleted=1583172821632, DequeueBufferDuration=359000, QueueBufferDuration=426000,
```

**Comment by Redth** [comment] 2022-05-02 15:09
Duplicate of https://github.com/dotnet/maui/issues/6551

This is fixed in main, will be in the next release...

![image](https://user-images.githubusercontent.com/271950/166258286-58199a9a-6843-4562-a7be-be33715f419b.png)

**Closed by Redth** 2022-05-02 15:09 UTC
Labels: t/bug, platform/android 🤖, area/fonts 🅰️
