### ISSUE TITLE
Unwanted Top and Bottom Spacing in .NET MAUI iOS Simulator

### ISSUE THREAD

**Issue by Piyush1430** [dotnet/maui#26080] opened 2024-11-23 12:10 UTC
### Description

**Problem**
When running my .NET MAUI application on an iOS simulator (connected through Mac pairing), the app displays with unexpected blank spaces at the top and bottom of the screen. This issue occurs specifically on the iOS simulator despite successful connection and running of the simulator.
Environment

.NET MAUI (targeting net8.0)
macOS with Windows pairing
iOS Simulator
Visual Studio

**What I've Tried**

Set Shell.NavBarIsVisible="False" and NavigationPage.HasNavigationBar="False"
Added UIRequiresFullScreen in Info.plist
Confirmed proper simulator connection and running state

Expected Behavior
The app should fill the entire screen without any unwanted spacing at the top or bottom.
Actual Behavior
The app displays with unnecessary blank spaces at the top and bottom of the screen in the iOS simulator.
Relevant Code

**##AppScreen Short**
![Image](https://github.com/user-attachments/assets/b4a599db-8883-4b79-b404-39a5388b8d88)

Project File (Relevant Parts)
```
<PropertyGroup>
    <TargetFrameworks>net8.0-ios;net8.0-maccatalyst;net8.0-android34.0</TargetFrameworks>
    <OutputType>Exe</OutputType>
    <UseMaui>true</UseMaui>
    <SingleProject>true</SingleProject>
    <ImplicitUsings>enable</ImplicitUsings>
    <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">11.0</SupportedOSPlatformVersion>
</PropertyGroup>
```
**Info.plist**
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>LSRequiresIPhoneOS</key>
    <true/>
    <key>UIDeviceFamily</key>
    <array>
        <integer>1</integer>
        <integer>2</integer>
    </array>
    <key>UISupportedInterfaceOrientations</key>
    <array>
        <string>UIInterfaceOrientationPortrait</string>
    </array>
    <key>UIRequiresFullScreen</key>
    <true/>
</dict>
</plist>

> ```

Visual Studio 2022 latest version
.Net Version:- 9.0.100-rc.2.24474.11
latest net maui workload both ios and windows

**Comment by jfversluis** [comment] 2024-11-25 07:48
This looks like the "display zoom" or compatibility mode which happens if you don't include a proper launch screen. Make sure that you have set up a launch screen and its shown properly when you start the app.

You will need a line like this: https://github.com/dotnet/maui/blob/main/src/Templates/src/templates/maui-mobile/MauiApp.1.csproj#L60

And then of course the image mentioned there needs to be present in your project.

I'll close this one here since I'm pretty confident this is not a bug in the .NET MAUI SDK.

**Closed by jfversluis** 2024-11-25 07:48 UTC
Labels: t/bug

**Comment by Piyush1430** [comment] 2024-11-25 07:52
Hey @jfversluis, I wanted to inform you that I have successfully resolved this issue. I am posting to close the ticket. Thank you for your attention to this matter.
