### ISSUE TITLE
.NET MAUI Blazor: Android Status Bar Covers Top Portion of App

### ISSUE THREAD

**Issue by steve3p0** [dotnet/maui#26839] opened 2024-12-27 09:34 UTC
### Description

Right out of the box, the example "Hello, World!" code for .NET MAUI Blazor Hybrid (.NET 9.0) has a navigation menu that works when running on Windows. You can clearly see and click menu items and all is well.  

It looks like this: Windows 10

[![enter image description here][1]][1]

However, when I attempt to run it on an Android emulator on Windows 10, this navigation menu at the top of the screen is behind the Android status bar. The Android status bar appears over the top part of my app like a watermark.  I can see the app navigation menu at the top with a button that has 3 bars, but the Android Wi-fi, phone network, and battery life icons appear over it rendering the button unclickable. 

It looks like this: Pixel 7 - Android API 35

[![enter image description here][2]][2]

I haven't tried it yet with an Android device connected to my dev computer via USB due to security at my company.  I will get authorization soon, but I would like to also debug on an emulator.  I haven't changed a single line of code yet.

Any ideas?

  [1]: https://i.sstatic.net/VhWCwDth.png
  [2]: https://i.sstatic.net/pzsCHgjf.png

### Steps to Reproduce

1. Create a .NET MAUI Blazor Hybrid App (.NET 9.0) with sample code provided by template
2. Run this "Hello, World!" app on Windows.
3. Confirm that navigation menu is visible and components work 
4. Run this "Hello, World!" app on  Android
5. The Android Status Bar appears over the app navigation menu like a watermark and renders the menu unclickable

### Version with bug

9.0.21 SR2.1

### Is this a regression from previous behavior?

No, this is something new

### Affected platforms

Android

### Relevant log output

```shell

```

**Comment by jfversluis** [comment] 2024-12-27 13:26
Duplicate of #25477

**Closed by jfversluis** 2024-12-27 13:26 UTC
Labels: t/bug
