### ISSUE TITLE
Accessing string resource throws a false FileNotFoundException in Android

### ISSUE THREAD

**Issue by jlbilh** [dotnet/maui#7443] opened 2022-05-24 15:04 UTC
### Description

The first time any string resource is accessed in Android, this exception is thrown by the resource manager:
System.IO.FileNotFoundException: ''

This does not break any functionality and can be ignored, but creates a developer experience problem. Developers who rely on exception trapping to detect runtime issues will find the feed to be polluted and may ignore real issues.

### Steps to Reproduce

New MAUI App
Enable Break When Thrown (Ctrl+Alt+E) ->All Common Language Runtime Exceptions
Project properties->Resources->General->Create or open assembly resources
New String resource {"Name":"AResource", "Value":"A resource"}
![image](https://user-images.githubusercontent.com/102621630/170061877-a2d17f7e-a896-4826-b754-9094357bcd94.png)

Open MainPage.xaml.cs
Add this line to OnCounterClicked:
`System.Diagnostics.Debug.WriteLine(Properties.Resources.AResource);`

Build and run on Android. Tap the button, and the exception described above will be thrown.

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 12

### Did you find any workaround?

Disable Break When Thrown->[System.Exception, System.IO.FileNotFoundException, System.IO.IOException, System.SystemException].

**Comment by VincentBu** [comment] 2022-05-25 07:39
repro with vs main build(32524.329.main)

**Comment by PureWeen** [comment] 2022-06-28 20:11
@VincentBu can you try again and attach a repro please?

**Comment by VincentBu** [comment] 2022-07-01 06:54
not repro with vs main build 32630.352, here is an example
[MauiApp7443.zip](https://github.com/dotnet/maui/files/9026742/MauiApp7443.zip)

**Comment by Wynadorn** [comment] 2022-07-18 10:00
I have the issue described by @[jlbilh](https://github.com/jlbilh) in my current project as well.
However, initially I hadn't been able to recreate it in an example/debug project either.

Wonder if the exception is related to these log entries:
```
[monodroid-assembly] open_from_bundles: failed to load assembly en-US/MyLibrary.resources.dll
[monodroid-assembly] open_from_bundles: failed to load assembly en-US/MyLibrary.resources.dll
[monodroid-assembly] open_from_bundles: failed to load assembly en/MyLibrary.resources.dll
[monodroid-assembly] open_from_bundles: failed to load assembly en/MyLibrary.resources.dll
**System.IO.FileNotFoundException:** ''
```
My library is called `MyLibrary.dll`, so I don't expect `MyLibrary.resources.dll` to exist.

When continuing, after the breakpoint has been thrown, the strings seem to be displayed correctly.
I have had a look in my `/data/data/<project name>/files/__override__/` directory and found that only `MyLibrary.dll` exists.
(and no `MyLibrary.resources.dll`)

My `Microsoft.Maui.*` libraries are on `v6.0.408`.
`Microsoft.Android` is on `32.0.424`.
I'm debugging on a physical device `Android 10 (SDK 29)`
The issue is not present when targeting `Windows 10 OS Build 19044.1766`

Finally I've tested the code provided by @VincentBu.
And was able to reproduce the issue, key is that you have to set your exception settings to break on `System.IO.FileNotFoundException` or you'll miss it.

**Comment by snoova** [comment] 2022-08-02 10:17
Get the error too, just sporadically - that's weird

Workaround that worked for me:
- creating a copy of my fallback resource file and renaming it to "AppResources.en-us.resx" (AppResources.resx is my fallback filename).
- Clean up and redeploy.

**Comment by pierre01** [comment] 2022-08-09 04:46
I have the same issue.

**Comment by izabelalaiancu** [comment] 2022-08-11 12:43
Same issue on Android 11.

**Comment by DRAirey1** [comment] 2022-08-27 19:32
Same issue with iOS. The first attempt to access resources that are not in the main project fail. This is a huge problem because I don't want to ignore a 'file not found' exception.

**Comment by mattleibow** [comment] 2022-11-10 21:12
@jonathanpeppers  is this a limitation of Android or some build process is doing some work?

**Comment by jonathanpeppers** [comment] 2022-11-10 22:12
What is the stack trace of the exception being thrown? I would guess this is BCL library code in dotnet/runtime.

**Comment by Larhei** [comment] 2022-11-11 23:29
The stack trace is:
XXX.App.InitializeComponent() in XXX/Microsoft.Maui.Controls.SourceGen/Microsoft.Maui.Controls.SourceGen.CodeBehindGenerator/App.xaml.sg.cs:22
XXX.App..ctor(Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope provider, XXX.PreferenceService preferenceService, XXX.Services.SessionService sessionService) in XXX.App.xaml.cs:23
XXX.Program.Main(string[] args) in XXX/Platforms/iOS/Program.cs:14

Inner Exception:
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext)
   at System.Reflection.RuntimeAssembly.InternalGetSatelliteAssembly(Assembly assembly, CultureInfo culture, Version version, Boolean throwOnFileNotFound)
   
Caused by setting MainPage
 MainPage = new NavigationPage(Routing.GetOrCreateContent(Routes.MyView, _serviceProvider) as Page);

MyView contains a Label: 
<Label Text="{x:Static strings:Resource.MyString}" />

This results in:
ResourceManager.GetString("MyString", resourceCulture);

Here resourceCulture is null.

My App specifies in .plist
 <key>CFBundleLocalizations</key>
  <array>
    <string>de</string>
  </array>

and in .csproj
<NeutralLanguage>de</NeutralLanguage>

System language on osx is en
iOS-Simulator language is en.

So the exception is correct. It can not find a SatelliteAssembly for Resource.resx because there is no SatelliteAssembly. But getting this exception every time I start debugging... is annoying.

**Comment by jonathanpeppers** [comment] 2022-11-15 20:28
> because there is no SatelliteAssembly.

@Larhei does a similar thing happen in a .NET 6 console app? This might be a general .NET thing.

**Comment by hlavli** [comment] 2023-01-25 08:31
Is there any progress (at least workaround) with this issue? I am facing it in my project as well...

**Comment by jonathanpeppers** [comment] 2023-01-26 15:15
@hlavli I think the workaround is to prevent the debugger from breaking on certain exceptions:

> Disable Break When Thrown->[System.Exception, System.IO.FileNotFoundException, System.IO.IOException, System.SystemException].

> This does not break any functionality and can be ignored, but creates a developer experience problem. Developers who rely on exception trapping to detect runtime issues will find the feed to be polluted and may ignore real issues.

Is this issue crashing your app? That sounds different.

**Comment by hlavli** [comment] 2023-01-27 07:54
It doesn't lead to breakdown of my app, but it is disrupting my development a lot and it is very annoying. Although the breaking of this kind of exception has been disabled, the app is not running smoothly and stopping every time until continue button is pressed...
For the first time the issue appears somewhere in InitializeComponent method in AppShell constructor. I had even tried to put this in try-catch block but the catch section is not reached in any time this exception is raised also further in other parts of code...
![image](https://user-images.githubusercontent.com/67420159/215034749-b2c576fb-5979-4ddd-9a38-676811033cd6.png)

**Comment by DRAirey1** [comment] 2023-01-27 12:25
> @hlavli I think the workaround is to prevent the debugger from breaking on certain exceptions:

1.) Disabling the exception doesn't work and 2.) this is a terrible exception to disable.

**Comment by jonathanpeppers** [comment] 2023-01-27 16:04
There is a problem with Fast Deployment, where files like `en-US/MyLibrary.resources.dll` aren't deployed properly.

Should be fixed in:
* (private repo) https://github.com/xamarin/monodroid/pull/1276
* https://github.com/xamarin/xamarin-android/pull/7741

**Comment by jonathanpeppers** [comment] 2023-04-10 17:08
Another example of this is: https://github.com/TonyHenrique/bug-2023-03-21

**Comment by jstedfast** [comment] 2023-05-09 18:28
@jonathanpeppers can this be closed, then?

**Closed by jstedfast** 2023-05-09 18:28 UTC
Labels: t/bug, area/localization, s/needs-attention
