### ISSUE TITLE
Sample counter app is broken on macOS Monterey 12.3.1  (Xcode version 13.2.1 )

### ISSUE THREAD

**Issue by sbhamad** [dotnet/maui#6914] opened 2022-05-06 23:36 UTC
### Description

following this tutorial by David Ortinau https://dev.to/davidortinau/installing-net-maui-on-macos-4mmc

```bash
dotnet --version

6.0.202
```

after running this: "dotnet build -t:Run -f net6.0-maccatalyst", it builds successfully and the counter app launches but it looks broken:

<img width="811" alt="Screen Shot 2022-05-07 at 2 24 34 AM" src="https://user-images.githubusercontent.com/18968640/167227471-7757bf37-44aa-4444-a22e-7f8496793ff1.png">

I am on macOS Monterey 12.3.1  (Xcode version 13.2.1 ) and 

when dark mode is enabled i get this instead:

<img width="801" alt="Screen Shot 2022-05-07 at 2 26 11 AM" src="https://user-images.githubusercontent.com/18968640/167227525-4ebcc715-5d23-48f6-a1d3-13167ef2e4d7.png">

the build output is:

```bash
dotnet build -t:Run -f net6.0-maccatalyst

Microsoft (R) Build Engine version 17.1.1+a02f73656 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
  Detected signing identity:
          
    Bundle Id: com.companyname.mauidesktop
    App Id: com.companyname.mauidesktop
  MauiDesktop -> /Users/sbhamad/github.com/sbhamad/MauiDesktop/bin/Debug/net6.0-maccatalyst/maccatalyst-x64/MauiDesktop.dll
  Optimizing assemblies for size, which may change the behavior of the app. Be sure to test after publishing. See: https://aka.ms/dotnet-illink

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:04.04

```

### Steps to Reproduce

following this tutorial by David Ortinau https://dev.to/davidortinau/installing-net-maui-on-macos-4mmc

```bash
dotnet --version

6.0.202
```

```bash
sudo dotnet workload install maui
```

```bash
dotnet new maui -n "MauiDesktop"
```

```bash
dotnet build -t:Run -f net6.0-maccatalyst
```

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

macOS Monterey 12.3.1

### Did you find any workaround?

No

### Relevant log output

```shell
sbhamad@sbhamads-MacBook-Air MauiDesktop % dotnet build -t:Run -f net6.0-maccatalyst

Microsoft (R) Build Engine version 17.1.1+a02f73656 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
  Detected signing identity:
          
    Bundle Id: com.companyname.mauidesktop
    App Id: com.companyname.mauidesktop
  MauiDesktop -> /Users/sbhamad/github.com/sbhamad/MauiDesktop/bin/Debug/net6.0-maccatalyst/maccatalyst-x64/MauiDesktop.dll
  Optimizing assemblies for size, which may change the behavior of the app. Be sure to test after publishing. See: https://aka.ms/dotnet-illink

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:03.86
```

**Comment by drasticactions** [comment] 2022-05-07 15:03
Duplicate of https://github.com/dotnet/maui/issues/6082

You need to update your dotnet workloads to 6.0.300 and install the newest workloads. https://github.com/dotnet/maui/issues/6082#issuecomment-1098567372

**Closed by drasticactions** 2022-05-07 15:03 UTC
Labels: t/bug, s/needs-verification

**Comment by sbhamad** [comment] 2022-05-07 17:13
@drasticactions Thank you for the suggestion. However, when i ```dotnet workload update``` the most recent update is 6.0.200

Do you know how to force update to 6.0.300?

sbhamad@sbhamads-MacBook-Air sbhamad % sudo dotnet workload update
Password:

Skip NuGet package signing validation. NuGet signing validation is not available on Linux or macOS https://aka.ms/workloadskippackagevalidation .
Skip NuGet package signing validation. NuGet signing validation is not available on Linux or macOS https://aka.ms/workloadskippackagevalidation .
Skip NuGet package signing validation. NuGet signing validation is not available on Linux or macOS https://aka.ms/workloadskippackagevalidation .
Skip NuGet package signing validation. NuGet signing validation is not available on Linux or macOS https://aka.ms/workloadskippackagevalidation .
Updated advertising manifest microsoft.net.sdk.android.
Updated advertising manifest microsoft.net.sdk.tvos.
Updated advertising manifest microsoft.net.sdk.ios.
Updated advertising manifest microsoft.net.sdk.maui.
Updated advertising manifest microsoft.net.sdk.maccatalyst.
Updated advertising manifest microsoft.net.sdk.macos.
Updated advertising manifest microsoft.net.workload.emscripten.
Updated advertising manifest microsoft.net.workload.mono.toolchain.
Garbage collecting for SDK feature band(s) 6.0.200...

Successfully updated workload(s): maui-maccatalyst maui.

**Comment by drasticactions** [comment] 2022-05-07 21:34
You need to install 6.0.300. It's a separate SDK.

https://aka.ms/dotnet/6.0.3xx/daily/dotnet-sdk-osx-x64.pkg

or

https://aka.ms/dotnet/6.0.3xx/daily/dotnet-sdk-osx-arm64.pkg

Depending on what Mac you're installing this on.
