### ISSUE TITLE
CollectionView inside ScrollView is more performant while scrolling?

### ISSUE THREAD

**Issue by BFuchshofer** [dotnet/maui#23895] opened 2024-07-29 15:20 UTC
### Description

In one of my projects, I noticed that the CollectionView is not very performant. There are frequent sudden stops while scrolling. Smooth scrolling is not possible here.

From Xamarin.Forms, I know that scrollable elements should not be nested. As a test, I still placed the CollectionView inside a ScrollView. I noticed that the scrolling is significantly more performant this way!

Does the rule that scrollable elements should not be nested no longer apply?

I have attached a test project where you can compare both cases.

I tested in both, debug and release mode but only on Android so far.

https://github.com/user-attachments/assets/06467006-e9dc-48d7-8217-d2a50a4e4fec

### Link to public reproduction project repository

https://github.com/BFuchshofer/MauiAppCollectionViewAndScrollView

### Version with bug

8.0.61 SR6.1

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 14

**Comment by Vroomer** [comment] 2024-07-29 18:46
The reason why you shouldn't wrap CollectionView inside ScrollView is because it gives CollectionView infinite constraint and forces all Items to be loaded upfront. This should cause worse performance for page loading speed but it can improve scrolling as the items are already loaded.

**Comment by RoiChen001** [comment] 2024-07-30 06:01
I can repro this issue at Android platform on the latest 17.11.0 Preview 5.0 (8.0.61&8.0.60).

**Comment by mattleibow** [comment] 2024-07-30 18:31
Duplicate of https://github.com/dotnet/maui/issues/23715

**Closed by mattleibow** 2024-07-30 18:31 UTC
Labels: t/bug, platform/android 🤖, s/verified, s/triaged, migration-compatibility
