### ISSUE TITLE
Imagesource problem when page reload

### ISSUE THREAD

**Issue by rodrigoavots** [dotnet/maui#14811] opened 2023-04-27 18:22 UTC
### Description

Hi!

I need help with this probable bug.
The problem only occurs when it is a database image and you refresh the page.
The directly assigned image does not have the problem.

### Steps to Reproduce

In the example:
1 - click on the NewPage button;
2 - Pull down to refresh, or click Update button, both will refresh the screen. Do it a few times and you will see that the image will disappear
3 - When navigating through the TAB screens below or returning to the initial screen, the blank screen problem will occur.

### Link to public reproduction project repository

https://github.com/rodrigoavots/MauiApp1

### Version with bug

7.0 (current)

### Last version that worked well

7.0 (current)

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 11, Android 12

**Comment by drasticactions** [comment] 2023-05-08 03:13
Duplicate of https://github.com/dotnet/maui/issues/14471

**Closed by drasticactions** 2023-05-08 03:13 UTC
Labels: t/bug, platform/android 🤖, area/controls 🎮, control-image
