### ISSUE TITLE
MAUI template is missing in VS Version 17.6.0 Preview 2.0

### ISSUE THREAD

**Issue by hamiddd1980** [dotnet/maui#14008] opened 2023-03-17 10:35 UTC
### Description

After updating to VS Version 17.6.0 Preview 2.0, **the MAUI template is missing from New Project windows**.
also the template is not shown in output of `dotnet new --list` command.
it is noticeable that  **.NET MAUI-Platform App UI Development** is checked Visual Studio Installer.

![MAUI_missing1](https://user-images.githubusercontent.com/57061231/225879179-c4f937bb-8076-4f97-bb2b-1af89df9bd9a.png)

![MAUI_missing2](https://user-images.githubusercontent.com/57061231/225879853-7e9c2a65-d08c-4f69-9090-f8f3fae5b20b.png)

### Steps to Reproduce

1.File->New Project

### Link to public reproduction project repository

https://github.com/hamiddd1980/Maui_Page_Title

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

I was *not* able test on other platforms

### Affected platform versions

Windows 10

**Comment by drasticactions** [comment] 2023-03-17 10:43
Duplicate of https://github.com/dotnet/maui/issues/14001

The VS version doesn't matter more likely than not, it's most likely whatever version of dotnet is installed with VS, along with any versions of dotnet you may have installed already. If the VS install is not installing the workload, or whatever version of dotnet VS is calling to get those templates is not working, then it's (probably) a VS issue more than MAUI, or something that could be fixed there.

**Closed by drasticactions** 2023-03-17 10:43 UTC
Labels: t/bug
