### ISSUE TITLE
Color button DisplayAlert box in dark theme on android not readable.

### ISSUE THREAD

**Issue by geertgeerits** [dotnet/maui#7601] opened 2022-05-30 08:38 UTC
### Description

Not only for the DisplayAlert box but also the color of the circle of the selected radio button is to dark in a dark theme.
.
![DisplayAlert-Dark-Android](https://user-images.githubusercontent.com/101981581/170950336-2d524954-538c-4063-9cd8-846493d74b7b.jpg)

![DisplayAlert-Dark-Windows](https://user-images.githubusercontent.com/101981581/170950393-2b663238-c2c3-4c3d-b2e7-a7f5e6dead8b.jpg)

### Steps to Reproduce

1. Create a displayalert box.
2. Open the box on the Android emulator in the dark theme.

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Pixel 5 API 30 Android 11.0

### Did you find any workaround?

No

**Comment by jfversluis** [comment] 2022-07-28 18:31
Duplicate of #6092

**Closed by jfversluis** 2022-07-28 18:31 UTC
Labels: t/bug, area/controls 🎮, s/verified
