### ISSUE TITLE
App not open when app storage usage clear data 

### ISSUE THREAD

**Issue by rahulsalokhe** [dotnet/maui#5963] opened 2022-04-10 14:19 UTC
### Description

Hi
If I go to settings>app management>myApp>storage usage>
And click on clear data and then start app it's not working
![Screenshot_2022-04-10-19-37-14-16](https://user-images.githubusercontent.com/6134194/162623687-5df19e62-9249-4c45-8c05-222555f1a633.png)

### Steps to Reproduce

settings>app management>myApp>storage usage>

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 9

**Comment by jfversluis** [comment] 2022-04-10 18:31
Duplicate of #1787

**Comment by jfversluis** [comment] 2022-04-10 18:31
This only happens for debugs builds, not for release builds

**Closed by jfversluis** 2022-04-10 18:31 UTC
Labels: t/bug, s/needs-verification
