### ISSUE TITLE
When publishing a DotNet 7 MAUI app, files are recompiled multiple times

### ISSUE THREAD

**Issue by genifycom** [dotnet/maui#17021] opened 2023-08-27 18:58 UTC
### Description

When building a MAUI application for Android, files are recompiled multiple times making the process much longer than it needs to be.

For example for my latest publish,

1>[24/188] Microsoft.Extensions.FileProviders.Embedded.dll -> Microsoft.Extensions.FileProviders.Embedded.dll.so

happened 8 times! Why recompile the same file (unchanged) multiple times?

### Public API Changes

Compiler changes only

### Intended Use-Case

Please can we cache and not recompile the same files over and over. This makes release testing and publishing a length process.

**Comment by drasticactions** [comment] 2023-08-28 09:58
You already have an item on this (https://github.com/dotnet/maui/issues/17005), closing as a duplicate.

**Closed by drasticactions** 2023-08-28 09:58 UTC
Labels: proposal/open

**Comment by samhouts** [comment] 2023-08-28 20:33
Duplicate of #17005
