### ISSUE TITLE
Vertical Text Alignment Not Working in Entry Control on Android Platform

### ISSUE THREAD

**Issue by surya3655** [dotnet/maui#24682] opened 2024-09-10 05:52 UTC
### Description

The vertical text alignment in the Entry control is not functioning correctly when the HeightRequest property is not explicitly set. Under normal circumstances, the Entry control should vertically align the text based on the specified alignment settings (e.g., VerticalTextAlignment = TextAlignment.Center). However, when the height is left unspecified or relies on the default layout behavior, the vertical alignment does not behave as expected.

Without setting the HeightRequest, the Entry control appears to ignore the vertical alignment setting, causing the text to remain aligned at the top by default. This issue becomes especially noticeable in scenarios where the Entry control is placed inside containers like Horizontal Stack layout on Andorid platform it's work fine in winodws.
## Output 

**Android**
![image](https://github.com/user-attachments/assets/260f68c1-3b5d-4af7-a191-6cde6ab1b4f9)
**Windows**
![image](https://github.com/user-attachments/assets/44a21cc9-3086-4eda-ad0c-cc76484365f9)

### Steps to Reproduce

1. Create a custom view that inherits from the HorizontalLayout.
2. Add the Entry control and a bindable property for vertical text alignment.
3. Load the custom view inside the HorizontalLayout and set the vertical text alignment to End.
4. Once the app is loaded on Android, focus on the Entry and observe that the cursor remains at the top.

### Link to public reproduction project repository

https://github.com/surya3655/TextAlignmentIssue

### Version with bug

8.0.82 SR8.2

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 13

### Did you find any workaround?

No

**Comment by Zhanglirong-Winnie** [comment] 2024-09-10 08:43
This issue has been verified using  Visual Studio 17.12.0 Preview 1.0(8.0.72 & 8.0.82 & 8.0.80). Can repro on Android platform.

**Comment by mattleibow** [comment] 2024-09-10 16:30
Duplicate of https://github.com/dotnet/maui/issues/21717

**Closed by mattleibow** 2024-09-10 16:30 UTC
Labels: t/bug, s/verified, s/triaged
