### ISSUE TITLE
[iOS] NullReferenceException in TemplatedCell

### ISSUE THREAD

**Issue by naaeef** [dotnet/maui#20606] opened 2024-02-15 09:56 UTC
### Description

CollectionView crashes on iOS with the SR 2 release.
```
2024-02-15 10:44:10.513912+0100 AppName[14329:382545] System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Maui.Controls.Handlers.Items.TemplatedCell.UpdateSelectionColor()
   at Microsoft.Maui.Controls.Handlers.Items.TemplatedCell.set_Selected(Boolean value)
2024-02-15 10:44:10.513983+0100 AppName[14329:382545]    at UIKit.UICollectionView.DequeueReusableCell(NSString reuseIdentifier, NSIndexPath indexPath) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/build/dotnet/ios/generated-sources/UIKit/UICollectionView.g.cs:line 232
2024-02-15 10:44:10.514065+0100 AppName[14329:382545]    at UIKit.UICollectionView.DequeueReusableCell(String reuseIdentifier, NSIndexPath indexPath) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UICollectionView.cs:line 23
2024-02-15 10:44:10.514142+0100 AppName[14329:382545]    at Microsoft.Maui.Controls.Handlers.Items.ItemsViewController`1[[Microsoft.Maui.Controls.ReorderableItemsView, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].GetCell(UICollectionView collectionView, NSIndexPath indexPath)
2024-02-15 10:44:10.514208+0100 AppName[14329:382545]    at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:line 58
2024-02-15 10:44:10.514260+0100 AppName[14329:382545]    at UIKit.UIApplication.Main(String[] args, String principalClassName, String delegateClassName) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:line 84
   at AppName.iOS.Application.Main(String[] args) in /Users/UserName/Documents/workspaces/zak-app/src/Zak/Platforms/iOS/Main.cs:line 17
```

### Steps to Reproduce

I'm currently working on a reproduction sample, but I could reproduce the issue in a blank application yet.

### Version with bug

8.0.7 SR2

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.6 SR1

### Affected platforms

iOS

### Did you find any workaround?

Use 8.0.6 SR1

**Comment by jsuarezruiz** [comment] 2024-02-15 15:38
Will be fixed by https://github.com/dotnet/maui/tree/fix-20606

**Comment by PureWeen** [comment] 2024-02-22 01:01
@naaeef can you try the latest nightly?

https://github.com/dotnet/maui/wiki/Nightly-Builds

**Comment by czmirek** [comment] 2024-02-28 13:11
@jsuarezruiz I created a reproduction repo!

https://github.com/czmirek/mauiiOScollectionviewbug

Steps to repro:
- Run app on iPhone or on iPhone Simulator 15 17.2

<img width="232" alt="image" src="https://github.com/dotnet/maui/assets/18615545/69ba5880-ec28-44b4-a37d-be123f6a3f65">

- Click on Clear & Load items --- everything works.
- If you click now on Load items and select --- everything works.

Close the app and start debuggin again.

- Now click directly on "Load items and select"
- Boom.

**Comment by czmirek** [comment] 2024-02-28 13:43
Workaroud for this is:

```csharp
#IF IOS
await Task.Delay(500);
#endif
```

Apparently it is some kind of racing condition bug, I was not able to find a better workaround.

**Comment by PureWeen** [comment] 2024-02-28 17:57
This looks specific to being nested in a VSL

For now, do you need to nest your CollectionView inside a VerticalStackLayout?

**Comment by czmirek** [comment] 2024-02-28 20:35
Of course not, if the problem is CollectionView being inside VeritcalStackLayout I can use something else instead to position different UI elements under the CollectionView...like a Grid or CollectionView's footer.

Is placing CollectionView inside VeritcalStackLayout bad practice?

**Closed** 2024-02-28 21:08 UTC
Labels: t/bug, platform/iOS 🍎, area/collectionview 📃, high, s/needs-attention, potential-regression
