### ISSUE TITLE
[IOS bug] string.Replace always returns null

### ISSUE THREAD

**Issue by danielftz** [dotnet/maui#7555] opened 2022-05-27 23:12 UTC
### Description

`string.Replace` always returns null when run on IOS, while it returns correctly when running on Android.

### Steps to Reproduce

```
    string test = "1 2 3 4 ";
    string t1 = test.Replace(" ", @",");
```
t1 should return "1,2,3,4,", and it does on Android, however t1 is null on IOS.

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15

**Comment by kristinx0211** [comment] 2022-05-30 08:16
verified repro on IOS15.4.

**Comment by danielftz** [comment] 2022-05-31 15:22
> @danielftz Are you seeing this in the debugger, or is the actual result in code `null`? If you call `System.Diagnostics.Debug.WriteLine(t1);`, does it output `null` or `1,2,3,4,` to the console?
> 
> We've been having some debugger issues in VS, I'm wondering if this is what you're seeing.

You are correct, Debug.WriteLine() shows the correct output. I was checking the variable value by hovering over it when setting a breakpoint, and the bug shows up.

**Comment by hartez** [comment] 2022-05-31 17:22
See also: #7009

**Comment by jfversluis** [comment] 2022-06-15 06:57
Going to close this as a duplicate for now so we don't have multiple bugs describing the same thing

**Comment by jfversluis** [comment] 2022-06-15 06:57
Duplicate of #7009

**Closed by jfversluis** 2022-06-15 06:57 UTC
Labels: t/bug, area/tooling ⚙️, s/verified
