### ISSUE TITLE
Android Overview Page and the iOS App Switcher page icon problem maui

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#16005] opened 2023-07-05 16:26 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Android-Overview-Page-and-the-iOS-App-Sw/10388724)._

---
[severity:It bothers me. A fix would be nice]
Microsoft Visual Studio Community 2022 (64-bit) - Current
Version 17.6.2

Problem:
Changing the MauiIcon doesn't change the icon on the Android Overview Page and the iOS App Switcher Page.

The Icon should look like this:
![image](https://github.com/dotnet/maui/assets/5375137/8c326c32-daad-4fc5-ab8e-9bf765ceaf89)

But looks like this:

Android
![image](https://github.com/dotnet/maui/assets/5375137/232b9143-bfda-42ba-b836-7a4879d1b83f)

iOS
![image](https://github.com/dotnet/maui/assets/5375137/3ed4636e-b1d6-4274-828d-b8820f4ebc94)

In the .csproj the Image defs. are:

```
	<ItemGroup>
		<!-- App Icon -->
		<MauiIcon Include="Resources\AppIcon\appicon.svg" ForegroundFile="Resources\AppIcon\appiconfg.svg" Color="#512BD4" />

<!-- Splash Screen -->
		<MauiSplashScreen Include="Resources\Splash\splashscreen.svg" BaseSize="256,256" />

<!-- Images -->
		<MauiImage Include="Resources\Images\*" />
		<MauiImage Update="Resources\Images\initimage.svg" BaseSize="168,208" />

<!-- Custom Fonts -->
		<MauiFont Include="Resources\Fonts\*" />

<!-- Raw Assets (also remove the "Resources\Raw" prefix) -->
		<MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
	</ItemGroup>

```

Only if I change the MauiIcon to a single .jpg have I seen the right icons on the Android Overview and the iOS App Switcher pages.

---
#### Eigil Krogh Sorensen on 6/10/2023, 03:42 PM: 

(private comment, text removed)
#### Feedback Bot on 6/11/2023, 06:58 PM: 

(private comment, text removed)
#### Eigil Krogh Sorensen on 6/13/2023, 04:22 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by mattleibow** [comment] 2023-07-05 18:36
For iOS this is a duplicate of https://github.com/dotnet/maui/issues/8685#issuecomment-1275239160

**Closed** 2023-07-13 10:01 UTC
Labels: t/bug, area/single project ☝️, s/no-recent-activity, s/needs-repro
