### ISSUE TITLE
[Bug] [Android] Title of Shell initially not set to correct value

### ISSUE THREAD

**Issue by LarsBehl** [dotnet/maui#3382] opened 2021-11-13 14:41 UTC
### Description
The initial value of the `Shell`s title is not set to the title of the `ShellContent`. Instead it displays the name of the application. When navigating to another page, the toolbar displays the title of the new page.

### Steps to Reproduce

1. Create a `Shell`
2. Add two `FlyoutItem`s with some pages where the title is set
3. Start the application (the text in the toolbar does not match the pages title)
4. Navigate to another page
5. The toolbar displays the correct title

### Expected Behavior
The title displayed in the toolbar does match the title of the initial page.

### Actual Behavior
The title displayed in the toolbar does not match the title of the initial page. Instead the name of the application gets displayed

### Basic Information

- Version with issue: 6.0.101-preview.10.2068
- Last known good version: -
- IDE: Visual Studio 2022 Version 17.1.0 Preview 1.0
- Platform Target Frameworks: 
  - Android: 28

#### Expected
![image](https://user-images.githubusercontent.com/26459044/141647698-b06981f4-22aa-4388-8f6a-1208ff35d13e.png)

#### Actual
![image](https://user-images.githubusercontent.com/26459044/141647693-1207ae6a-5758-4bdf-a5da-982968cd6cd5.png)

### Reproduction Link
[Here](https://github.com/LarsBehl/StatusApp/blob/9554fb14bc9aa497eb4697c2f790b4bb87b45c9b/SideNav.xaml) is the link to a `Shell` where the issue is present. The used pages can also be found in this repository.

**Comment by DiogoSemedo** [comment] 2021-12-08 12:28
I also detected the same problem, it display the ApplicationTitle of the .csproj and then if you comment the AplicationTitle it goes for the ApplicationId...

**Comment by kristinx0211** [comment] 2022-03-02 02:11
Duplicate of #4310

**Closed** 2022-03-10 23:10 UTC
Labels: t/bug, area/shell 🐢, s/verified
