### ISSUE TITLE
Can't release the C# object referenced by razor component in BlazorWebView

### ISSUE THREAD

**Issue by bycreal** [dotnet/maui#23654] opened 2024-07-17 12:52 UTC
### Description

There are 2 simple Page in the project:
MianPage (Root page)
NewPage (showed after click the button in MainPage)
But the object(My test object: ViewMode Vm) can't be released after the NewPage popped.

When I use:
BlazorWebView.Handler.DisconnectHandler();
The app will be freezing.

### Steps to Reproduce

1. Clicked "New Page"
2. Press Back
3. Clicked "New Page" again
4. Press Back again

Vm2 in NewPage released, but Vm referenced by razor component not released.

### Link to public reproduction project repository

https://github.com/bycreal/MauiBlazorFreezing

### Version with bug

8.0.40 SR5

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

iOS17, macOS 14, windows 10/11

**Comment by QianaJiao** [comment] 2024-07-22 07:51
This issue has been verified and repro on Visual Studio 17.11.0 Preview 4.0 (8.0.70 & 8.0.40).

**Comment by mkArtakMSFT** [comment] 2024-09-25 20:51
This is a dupe of https://github.com/dotnet/maui/issues/24407

**Closed by mkArtakMSFT** 2024-09-25 20:51 UTC
Labels: t/bug, platform/macOS 🍏, platform/windows 🪟, platform/android 🤖, area-blazor, platform/iOS 🍎, s/verified, s/triaged, memory-leak 💦

**Comment by malsabi** [comment] 2024-10-07 05:37
Is there any workaround for this issue?
