### ISSUE TITLE
Touchscreen Functionality Crashing on Rapid Touch in .NET Maui Hybrid App

### ISSUE THREAD

**Issue by arsalan16-web** [dotnet/maui#25791] opened 2024-11-12 07:59 UTC
### Description

Just like the video shows, if I rapidly click anywhere inside the app while starting up and loading, the touch screen will be broken but the mouse & Keyboard is still working. 

### Steps to Reproduce

1. Create a new Maui Blazor Project
2. Deploy it on windows tablet
3. Repeatly touch the screen inside the app window as quickly as you can

### Link to public reproduction project repository

https://github.com/arsalan16-web/MauiTouchTest.git

### Version with bug

Unknown/Other

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Affected platforms

Windows

### Affected platform versions

net8.0-windows10.0.19041.0

### Relevant log output

```shell

```

**Comment by arsalan16-web** [comment] 2024-11-12 08:00
https://github.com/user-attachments/assets/7aa56db9-9747-4088-9114-50cae8974ae2

**Comment by ninachen03** [comment] 2024-11-12 10:17
This issue has been verified using latest Visual Studio 17.12.0 Preview 5.0 (8.0.92 & 8.0.82 & 9.0.0-rc.2.24503.2). Can repro on windows platform.

**Comment by arsalan16-web** [comment] 2024-11-12 10:37
@ninachen03 any already solution for this?

**Comment by AArnott** [comment] 2024-11-12 12:58
@arsalan16-web Please don't randomly mention folks hoping to get traction. I don't even work on this repo.

**Comment by mattleibow** [comment] 2024-11-12 22:13
duplicate of #16251

**Comment by mattleibow** [comment] 2024-11-12 22:13
Please see https://github.com/MicrosoftEdge/WebView2Feedback/issues/3685

**Closed by mattleibow** 2024-11-12 22:13 UTC
Labels: t/bug, platform/windows 🪟, area-blazor, s/verified, s/triaged
