### ISSUE TITLE
Button.BorderColor not working on some platforms

### ISSUE THREAD

**Issue by andrewstellman** [dotnet/maui#18261] opened 2023-10-23 15:11 UTC
### Description

The Button.BorderColor property does not seem to work on some platforms. Adding `BorderColor="Black"` to the XAML for a Button control seems to have no effect on macOS or Android.

### Steps to Reproduce

Create a new .NET MAUI app and replace the contents of MainPage.xaml with this:

```
    <HorizontalStackLayout>
        <Button BackgroundColor="LightBlue" BorderColor="Black" HeightRequest="100" WidthRequest="100" />
        <Button BackgroundColor="LightBlue" HeightRequest="100" WidthRequest="100" />
        <Button BackgroundColor="LightBlue" BorderColor="Black" HeightRequest="100" WidthRequest="100" />
    </HorizontalStackLayout>
```

and remove the OnCounterClicked method from MainPage.xaml.cs. 

Run the app on macOS:

`dotnet build -t:Run -f net8.0-maccatalyst`

The borders do not show up on the buttons with `BorderColor="Black"`:

<img width="658" alt="image" src="https://github.com/dotnet/maui/assets/7516297/89e110a1-2af1-4fee-b240-bc7bdda41ceb">

They don't show up on Android either:

![image](https://github.com/dotnet/maui/assets/7516297/3f660045-d121-48ba-b31f-cb0ca7e3ed5a)

Here's the same XAML rendered in Windows—it works correctly:

<img width="609" alt="image" src="https://github.com/dotnet/maui/assets/7516297/1e522920-3c05-49fa-8600-0c32d0cc2370">

### Link to public reproduction project repository

https://github.com/andrewstellman/reproduce-maui-button-border-bug

### Version with bug

8.0.0-rc.2.9373

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android, macOS

**Comment by Kaiffa** [comment] 2023-10-23 15:51
I believe a duplicate of https://github.com/dotnet/maui/issues/18103

**Comment by PureWeen** [comment] 2023-10-24 18:17
@andrewstellman if you test our nightly do you still see the issue?

https://github.com/dotnet/maui/wiki/Nightly-Builds

**Comment by andrewstellman** [comment] 2023-10-25 20:29
Hey @PureWeen, great to hear from you again 😀

I tried the nightly build, but I'm not seeing any difference. Maybe I did something wrong? (I added `Spacing="25"` to make it easier to see in the screenshots.)

First I tried on my Mac. I added NuGet.config:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="maui-nightly" value="https://pkgs.dev.azure.com/xamarin/public/_packaging/maui-nightly/nuget/v3/index.json" />
  </packageSources>
</configuration>
```

Then ran it like this:

`
dotnet build /p:MauiVersion=8.0.0-nightly.9483 -t:Run -f net8.0-maccatalyst
`

but I didn't see any difference:

<img width="919" alt="image" src="https://github.com/dotnet/maui/assets/7516297/88a2d43b-ff3b-4705-bf95-b1e3fe8d7c4e">

I also tried with Android. I updated Microsoft.Maui.Controls and Microsoft.Maui.Controls.Compatibility to 8.0.0-nightly.9483 in Visual Studio:

<img width="549" alt="image" src="https://github.com/dotnet/maui/assets/7516297/91fd1391-7408-4d03-b409-6850b615c170">

Still not seeing them on Android:

<img width="1532" alt="image" src="https://github.com/dotnet/maui/assets/7516297/bebd36de-e591-4757-93ea-074fabe4852e">

and weirdly the border color disappeared on Windows too:

<img width="1290" alt="image" src="https://github.com/dotnet/maui/assets/7516297/80b41ecd-c6b8-429f-9359-6b50883bfc89">

Did I do something weird? Do I need to update anything else to make it work?

**Closed** 2023-10-26 13:00 UTC
Labels: t/bug, area/Xaml </>, control-button, s/needs-attention
