### ISSUE TITLE
Alert not shown in OnAppearing method

### ISSUE THREAD

**Issue by Legends** [dotnet/maui#19369] opened 2023-12-12 17:22 UTC
### Description

I have overriden the `OnAppearing` method in MainPage.xaml.cs:

```
protected override async void OnAppearing()
{
	try
	{
		await this.DisplayAlert("Title", "Message", "OK");
		...
		..
		.
		}
	catch (Exception ex)
	{
		throw;
	}
}
```
Two things:
1.) The alert is not shown
2.) Perhaps 1.) is ok, because probably called too early in the page lifecycle? But shouldn't there be a way to inform the user, that it is too early to call the `DisplayAlert` method at this stage?

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

8.0.3

### Affected platforms

Windows

### Affected platform versions

Android 11, Win 10.0.19045 Build 19045

**Comment by PureWeen** [comment] 2023-12-12 19:06
Duplicate of #12970

**Closed by PureWeen** 2023-12-12 19:06 UTC
Labels: t/bug
