### ISSUE TITLE
.NET MAUI GestureRecognizers not working on certain controls

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#8895] opened 2022-07-21 20:20 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/NET-MAUI-GestureRecognizers-not-working/10097032)._

---
\[severity:It’s more difficult to complete my work\]  
The following is working perfectly fine:

```  
<Frame>
  <Frame.GestureRecognizers>
    <TapGestureRecognizer Command="{Binding ExecuteCommand}" />
  </Frame.GestureRecognizers>
</Frame>
```

While this is not working:

```  
<CheckBox>
  <CheckBox.GestureRecognizers >
    <TapGestureRecognizer Command="{Binding ExecuteCommand}"/>
  </CheckBox.GestureRecognizers>
</CheckBox>

```

The command is not executed.

The same goes for the Switch.

If this is intentional, what would be the proper way to bind a command to the Checkbox or Switch?

---
#### Feedback Bot on 7/17/2022, 08:01 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by rmarinho** [comment] 2022-07-22 12:47
What platform is this? I tested on Windows, Android and iOS and is working as expected the TapGestures is called, the problem is if you add the ta gesture on iOS and Android the 

Windows -  works fine 
Android - The checkbox doesn't get check if you add the TapGesture
iOS -  The checkbox doesn't get check if you add the TapGesture

**Comment by rmarinho** [comment] 2022-07-22 12:48
Code use to test:

```
 <StackLayout>
        <Frame WidthRequest="100" HeightRequest="100" BackgroundColor="Red">
            <Frame.GestureRecognizers>
                <TapGestureRecognizer Command="{Binding ExecuteCommand}" />
            </Frame.GestureRecognizers>
        </Frame>
        <CheckBox Background="Yellow">
            <CheckBox.GestureRecognizers >
                <TapGestureRecognizer Command="{Binding ExecuteCommand}"/>
            </CheckBox.GestureRecognizers>
        </CheckBox>
    </StackLayout>
```
```
 ExecuteCommand = new Command(() =>
 {
        System.Diagnostics.Debug.WriteLine($"{ExecuteCommand} Called");
 });
```

**Comment by otium99** [comment] 2022-07-22 13:41
@rmarinho If the TapGestureRecognizer blocks the state change of the control, what would be the correct way of attaching a command to the Switch or the Checkbox?

**Comment by Symbai** [comment] 2022-08-29 11:07
Doesn't work on `ListView` as well. The `Tapped` event is never raised.


```XAML
            <ListView.GestureRecognizers>
                <TapGestureRecognizer Tapped="OnTapGestureRecognizerTapped"
                              NumberOfTapsRequired="2" />
            </ListView.GestureRecognizers>
```

**Comment by SunshineSpring666** [comment] 2022-11-03 04:13
Bug: Putting Frame inside ListView's ItemTemplate blocks tap action to trigger on a ListView item.

**Comment by BenderNK** [comment] 2022-11-09 02:31
Embedding the gesture in a CollectionView also doesn't work.
```
<CollectionView>
  ...
  <CollectionView.EmptyView>
    <ContentView>
       <Frame>
         <Frame.GestureRecognizers>
           <!-- Nothing ever happens -->
           <TapGestureRecognizer Tapped="DidClickAdd" />
         </Frame.GestureRecognizers>
      </Frame>
    </ContentView>
  <CollectionView.EmptyView>
<CollectionView>
```

But take the ContentView outside of the CollectionView and make it the only descendant of a page for example, then it works:
```
<ContentView>
   <Frame>
     <Frame.GestureRecognizers>
       <!-- This is fine, working as expected -->
       <TapGestureRecognizer Tapped="DidClickAdd" />
     </Frame.GestureRecognizers>
  </Frame>
</ContentView>
```

**Comment by BenderNK** [comment] 2022-11-17 19:42
Hello @abcox, 
Unfortunately, I didn't discover a work-around. My strategy was for it get addressed in a future release. However, the app started to recognize the tap gesture all of a sudden. I didn't change my MAUI version or anything like that. I honestly don't know what caused the sudden change in behavior. The only thing I can think of is that I cleaned the build and rebuilt-it from scratch. Perhaps some caching issue in the intermediary files?

**Comment by vorba** [comment] 2022-11-17 20:18
@BenderNK what i am doing for now is using a transparent rectangle

**Comment by PankajIATOCS** [comment] 2022-11-30 13:06
### **Command event not working for Span.GestureRecognizers.**

<Label HorizontalTextAlignment="Center">
                                <Label.FormattedText>
                                    <FormattedString>
                                        <FormattedString.Spans>
                                            <Span Text="By continuing, you agree to our"/>
                                            <Span Text=" Terms of services," TextDecorations="Underline">
                                                <Span.GestureRecognizers>
                                                    <TapGestureRecognizer Command="{Binding NavigateToTermsofServicesCommand}"/>
                                                </Span.GestureRecognizers>
                                            </Span>
                                            <Span Text=" Privacy Policy" TextDecorations="Underline">
                                                <Span.GestureRecognizers>
                                                    <TapGestureRecognizer Command="{Binding NavigateToPrivacyPolicyCommand}"/>
                                                </Span.GestureRecognizers>
                                            </Span>
                                        </FormattedString.Spans>
                                    </FormattedString>
                                </Label.FormattedText>
                            </Label>

**Code of ViewModel.**
[RelayCommand]
        async Task NavigateToTermsofServices()
        {

        }

**Comment by PankajIATOCS** [comment] 2022-11-30 14:53
**### Tapped event not working for Span.GestureRecognizers.**

```
                         <Label HorizontalTextAlignment="Center">
                                <Label.FormattedText>
                                    <FormattedString>
                                        <FormattedString.Spans>
                                            <Span Text="By continuing, you agree to our"/>
                                            <Span Text=" Terms of services," TextDecorations="Underline">
                                                <Span.GestureRecognizers>
                                                    <TapGestureRecognizer Tapped="TapGestureRecognizer_Tapped"  />
                                                </Span.GestureRecognizers>
                                            </Span>
                                            <Span Text=" Privacy Policy" TextDecorations="Underline">
                                                <Span.GestureRecognizers>
                                                    <TapGestureRecognizer Tapped="TapGestureRecognizer_Tapped_1"/>
                                                </Span.GestureRecognizers>
                                            </Span>
                                        </FormattedString.Spans>
                                    </FormattedString>
                                </Label.FormattedText>
                        </Label>

 **###Code Behind**

    private void TapGestureRecognizer_Tapped(object sender, TappedEventArgs e)
    {

    }

    private void TapGestureRecognizer_Tapped_1(object sender, TappedEventArgs e)
    {

    }
```

**Comment by tatee13** [comment] 2022-12-19 15:21
<CollectionView Grid.Row="2" Grid.ColumnSpan="2"
                            ItemsSource="{Binding Items}">
                <CollectionView.ItemTemplate>
                    <DataTemplate x:DataType="{x:Type x:String}">
                        <SwipeView>
                            <SwipeView.RightItems>
                                <SwipeItems>
                                    <SwipeItem Text="Delte"
                                               BackgroundColor="Red"
                                                Command="{Binding Source={RelativeSource AncestorType={x:Type xx:MainViewModel}}, Path=DeleteCommand}"
                                                CommandParameter="{Binding .}"/>
                                </SwipeItems>

                            </SwipeView.RightItems>
                            <Grid Padding="0,5">
                                <ListView>
                                    <ListView.GestureRecognizers>
                                        <TapGestureRecognizer 
                                       Command="{Binding Source={RelativeSource AncestorType={x:Type xx:MainViewModel}}, Path=MMMCommand}"
                                       CommandParameter="{Binding .}"/>
                                    </ListView.GestureRecognizers>
                                </ListView>
                                <Frame>
                                    <Label Text="{Binding .}"
                                       FontSize="24"/>
                                </Frame>
                            </Grid>
                        </SwipeView>
                    </DataTemplate>
                </CollectionView.ItemTemplate>
            </CollectionView>

**Comment by danheinz** [comment] 2022-12-29 14:21
No gestures work on the Map control either.

```
<Map x:Name="LocationsMap" 
	IsShowingUser="True" 
	IsZoomEnabled="True"                                   
	IsEnabled="True" 
	IsScrollEnabled="True" 
	MapType="Street"
	ItemsSource="{Binding MapPins}"
	IsVisible="{Binding IsMapVisible}"
	Loaded="OnMapLoaded">
	<Map.GestureRecognizers>
		<TapGestureRecognizer Tapped="TapGestureRecognizer_Tapped" />
	</Map.GestureRecognizers>
	<Map.ItemTemplate>
		<DataTemplate x:DataType="Pin">
			<Pin Location="{Binding Location}"
				Address="{Binding Address}"
				Label="{Binding Label}"
				InfoWindowClicked="Pin_InfoWindowClicked"/>
		</DataTemplate>
	</Map.ItemTemplate>
</Map>
```

**Comment by Laim** [comment] 2023-02-04 16:10
Just to add to this issue.  I'm seeing the same issue when using Tap Gesture's inside of a Frame that is inside of a CollectionView.

**XAML**
```xaml
<CollectionView ItemsSource="{Binding TaskList, Mode=TwoWay}">
    <CollectionView.ItemTemplate>
        <DataTemplate>
            <Grid HeightRequest="120" Margin="0" Padding="0" RowSpacing="0">

                <Grid.RowDefinitions>
                    <RowDefinition Height="*"/>
                    <RowDefinition Height="8"/>
                </Grid.RowDefinitions>

                <Frame BackgroundColor="#FAFAFA" CornerRadius="10">
                    <Frame.GestureRecognizers>
                        <TapGestureRecognizer Command="{Binding TaskClickedCommand}" CommandParameter="{Binding .}"/>
                    </Frame.GestureRecognizers>
                                
                    <StackLayout Orientation="Vertical">
                        <Label ... /> <!-- removed for space saving on gh -->

                        <Label ... /> <!-- removed for space saving on gh -->

                        <Label ... /> <!-- removed for space saving on gh -->
                    </StackLayout>
                </Frame>
            </Grid>
        </DataTemplate>
    </CollectionView.ItemTemplate>
</CollectionView>
```

**csharp**

```csharp
[RelayCommand]
private void TaskClicked(TaskModel task)
{
    Console.WriteLine(task.Name);
    Console.WriteLine("Task Clicked");
    System.Diagnostics.Debug.WriteLine("Task Clicked");
}
```

I'm using the CommunityToolkit.MVVM, in case it's important.

**Comment by sangyuxiaowu** [comment] 2023-02-17 14:35
> ### **Command event not working for Span.GestureRecognizers.**
> ```
>                           <Label HorizontalTextAlignment="Center">
>                                 <Label.FormattedText>
>                                     <FormattedString>
>                                         <FormattedString.Spans>
>                                             <Span Text="By continuing, you agree to our"/>
>                                             <Span Text=" Terms of services," TextDecorations="Underline">
>                                                 <Span.GestureRecognizers>
>                                                     <TapGestureRecognizer Command="{Binding NavigateToTermsofServicesCommand}"/>
>                                                 </Span.GestureRecognizers>
>                                             </Span>
>                                             <Span Text=" Privacy Policy" TextDecorations="Underline">
>                                                 <Span.GestureRecognizers>
>                                                     <TapGestureRecognizer Command="{Binding NavigateToPrivacyPolicyCommand}"/>
>                                                 </Span.GestureRecognizers>
>                                             </Span>
>                                         </FormattedString.Spans>
>                                     </FormattedString>
>                                 </Label.FormattedText>
>                             </Label>
> 
> **Code of ViewModel.**
> [RelayCommand]
>         async Task NavigateToTermsofServices()
>         {
> 
>         }
> ```

I have the same need as yours, Span.GestureRecognizers does not work, did you find another solution?

**Comment by Laim** [comment] 2023-02-17 14:51
Is your repo public? Can have a look.  Seems to be very hit or miss sadly.

**Comment by sangyuxiaowu** [comment] 2023-02-17 14:53
> Is your repo public? Can have a look. Seems to be very hit or miss sadly.

It is public, and it is a small application for practice.

**Comment by Greg-Bates-Trimble** [comment] 2023-02-23 02:21
Is this any idea when this is going to get looked at or resolved? This is a serious issue which blocks any iOS releases.

**Comment by npostma** [comment] 2023-02-23 14:48
Same issue with the carousel view. I wanted to use the tapGesture instead of custom gestures (I come from Xamarin, and do not want to use the custom renders anymore, which i would need for custom gestures). So for now i hoped i could use the `GestureRecognizers` `TapGestureRecognizer`. What i found out is that ```Tapped="Method"``` gets called. But then i don't know what element is tapped.  So i want to use ```Command="{Binding MyCommand, Source={x:Reference this}}"``` it compiles fine, but the command in my ViewModel does not get called.

As a workaround I tried to create a custom control for the Image, which has a reference to the viewmodel but for some reason if the Method is called defined in `Tapped="Method"` the param object is the image but `object.RefToViewModel` is always `null` and i am sure that the references are set when inserted in the collection.

**Comment by arahmancsd** [comment] 2023-03-26 15:31
Same here with Image inside a Grid in CollectionView DataTemplate.

<DataTemplate x:Key="ItemTemplate" x:DataType="models:MyModel">

            <Grid RowDefinitions="*,Auto"
                IsClippedToBounds="True"
                RowSpacing="10"
                Background="Transparent"
                CompressedLayout.IsHeadless="True"
                >

                <Image Grid.Row="0" WidthRequest="80" HeightRequest="80"
                       Source="{Binding ImageName}"
                       InputTransparent="True">
                    <Image.Clip>
                        <EllipseGeometry Center="40,40" RadiusX="40" RadiusY="40"/>
                    </Image.Clip>
                    <Image.GestureRecognizers>
                        <TapGestureRecognizer 
                            Command="{Binding BindingContext.NavigateToPageCommand, Source={Reference this}}"
                            CommandParameter="{Binding .}"/>
                    </Image.GestureRecognizers>
                </Image>

                <Label Grid.Row="1" Text="{Binding Name}"
                       InputTransparent="True"
                       FontSize="15"
                       HorizontalTextAlignment="Center"
                       />
            </Grid>
        </DataTemplate>

**Comment by Greg-Bates-Trimble** [comment] 2023-03-28 01:48
@PureWeen I've just had a look at the current source code and it seems that the changes you made here https://github.com/dotnet/maui/pull/3623 have been overwritten/further updated.
As a result the UserInteractionEnabled is never getting set.
Is there a way this can be reenabled easily?
Thanks

**Comment by aschuhardt** [comment] 2023-04-08 01:32
Adding a SwipeGestureRecognizer to a Button also prevents the button from being pressed, though the gesture triggers.

**Comment by imsam67** [comment] 2023-04-21 03:46
I'm also having this truly strange behavior in my .NET MAUI app targeting .NET 7 using the latest service release.

I use it with `Border`'s and the weird thing is it works on one `Border` but not the second one. It also worked a few times in the second `Border` then it stopped. There's no telling when it may work.

I'm discouraged to see that this issue is also falling on deaf ears! It's been open since July 22 and it's still there.

**Comment by Greg-Bates-Trimble** [comment] 2023-04-21 05:02
I was finding an issue with content registering gestures if after a visibility change the view rendered it below the size of the screen (scroll down to view it).
My workaround was to call InvalidateMeasure() on the view. Afterwards, all the gestures seem to be responding correctly.
Hope this workaround solves some peoples problems in here.

**Comment by imsam67** [comment] 2023-04-21 19:22
@Greg-Bates-Trimble I think you're right about this. I'm trying to understand exactly what you were doing to fix the behavior. FIrst, are you invoking `InvalidateMeasure()` only on the affected element or, say, the whole `Grid` or `VerticalStackLayout`. In my case, the `Border` is a child of `VerticalStackLayout`. Second, when do you invoke `InvalidateMeasure()` -- meaning, do you detect a particular event to invoke it?

**Comment by Greg-Bates-Trimble** [comment] 2023-04-24 03:39
Hi @imsam67 I call it on the entire page, in the code behind it looks like this: 
`this.InvalidateMeasure();`
I am then invoking this whenever the visibility of any of the content changes.
Hope that this helps.

**Comment by imsam67** [comment] 2023-04-24 15:24
@Greg-Bates-Trimble Thank you! This workaround does work.

**Comment by Symbai** [comment] 2023-04-29 06:24
I've tried the workaround of @Greg-Bates-Trimble and it doesn't work. My page looks like this:

```XAML
<ContentPage
        ...>
    <Grid ...>
        ...
        <ListView
                ....>
            <ListView.ItemTemplate>
                <DataTemplate>
                    <ViewCell>
                        ...
                    </ViewCell>
                </DataTemplate>
            </ListView.ItemTemplate>
            <ListView.GestureRecognizers>
                <TapGestureRecognizer NumberOfTapsRequired="2" Tapped="OnTapGestureRecognizerTapped" />
            </ListView.GestureRecognizers>
        </ListView>
....

```

I've tried calling `InvalidateMeasure` in `Appearing` event. I've tried calling it in listview selection event. Still I can double tap as much as I want, the event `OnTapGestureRecognizerTapped` is never raised.

I've actually even not got it working on something simple like a Label or a Button. Its a shame this problem has such a low priority from Maui team. Because it breaks a whole feature set which is especially on mobile development extremely important. Swiping and tapping is a key part of mobile navigation.

**Comment by SalimiHabib** [comment] 2023-04-29 17:55
Same problem in DataTemplate  .
Not working in any way .
```

<DataTemplate x:Key="Template1">
        <Border Margin="2" StrokeThickness="0">
            <Border.StrokeShape>
                <RoundRectangle CornerRadius="5" />
            </Border.StrokeShape>
            <Grid HandlerChanged="Grid_HandlerChanged">
                <Grid.GestureRecognizers>
                    <TapGestureRecognizer CommandParameter="{Binding Path=BindingContext, Source={RelativeSource AncestorType={x:Type Border}}}" Tapped="TapGestureRecognizer_Tapped" />
                </Grid.GestureRecognizers>
                <Grid.ColumnDefinitions>
                    <ColumnDefinition Width="Auto" />
                    <ColumnDefinition Width="*" />
                </Grid.ColumnDefinitions>
                
```

**Comment by simonDev2021** [comment] 2023-04-30 19:48
I have just created a new MAUI app and added a Carousel control. It works absolutely fine until I try adding a tap gesture to it. When I start it the left right scrolling is completely unresponsive in the android phone emulator, but the tap gesture works fine both in code and xml. Can any one tell me if MAUI simply doesn't support adding gestures to some controls? If so shouldn't Microsoft state that in the documentation. Alternatively perhaps the tap gesture overrides the built in left/right scroll of the control. I tried scroll gesture with the same result. I am new to MAUI, so any advice would be appreciated.

**Comment by Symbai** [comment] 2023-05-01 05:38
The issue here is about gestures not working. In your case where gestures are working but a control isn't, you should create a new issue.

**Comment by kojini** [comment] 2023-05-03 05:41
I have the same issue. As @Greg-Bates-Trimble said, when the visibility of control(s) (not necessarily the control that has the tap gesture) is changed, gesture stops working.  
For now I stopped chaging the visibility of a control as a workaround, but this bug could be a real pain.

**Comment by mosessaur** [comment] 2023-05-08 04:02
Thought to share my workaround on this issue.
Create TapGestureRecognizer as low as possible in your view hierarchy. It resulted in the command being triggered as expected
They may result in duplicating/copying TapGestureRecognizer to multiple controls. 
Not Ideal, but for the time being it work for me.
I didn't test all possible scenarios for this. But I managed to get TapGestureRecognizer working on one of my custom controls by replicating TapGestureRecognizer 3 times on 3 controls

**Comment by maslewandowski** [comment] 2023-05-15 13:07
I use the tapgesturerecognizer nested in a collectionview and the command does not execute, if the item is not visible at loading time.
So when i add many items to the bound observablecollection, the command is only executed for those items that are visible after that process.

**Comment by thoys** [comment] 2023-07-05 19:27
Why is this issue not getting attention? This seems like a very basic feature that Maui needs to support. I keep on fighting with workarounds for Maui, it's annoying.

**Comment by Laim** [comment] 2023-07-05 20:04
> Why is this issue not getting attention? This seems like a very basic feature that Maui needs to support. I keep on fighting with workarounds for Maui, it's annoying.

Because unfortunately MAUI doesn’t have nearly enough resource assigned to it at Microsoft.

**Comment by Vroomer** [comment] 2023-08-04 08:24
```
    <Border>
        <Border.GestureRecognizers>
            <!--<TapGestureRecognizer Tapped="Item_Selected" />-->
        </Border.GestureRecognizers>
    </Border>
```
This code as a DataTemplate for CollectionView caused items to be invisible. Took some time to find the issue, which is very frustrating. I tried to change the event to command - items are now visible, but the command doesn't fire. Tried switching Border to HorizontalStackLayout, but it has the same issue. I have no workaround. This definitely doesn't get the attention it should be getting!

**Comment by npostma** [comment] 2023-08-04 09:35
@Vroomer I have it working on an image (Android and iOS). This code works for me, note i am on .NET7. Would be helpfull if you add more information about what you are using and for what platform.

```
<CarouselView.ItemTemplate>
    <DataTemplate
        x:DataType="vme:TestViewModel"
    >
        <Border 
            BackgroundColor="Transparent"
            Margin="20,0,20,0"
            Padding="0,0,0,0"
        >
            <Grid 
                Margin="0"
                Padding="0"
                VerticalOptions="Center"
                HorizontalOptions="Center"
            >
                <Grid.RowDefinitions>
                    <RowDefinition Height="*" />
                </Grid.RowDefinitions>
                <Grid.ColumnDefinitions>
                    <ColumnDefinition Width="*" />
                </Grid.ColumnDefinitions>

                <ActivityIndicator 
                    Grid.Column="0"
                    Grid.Row="0"
                    IsRunning="{Binding IsLoading}" 
                    IsVisible="{Binding IsLoading}" 
                    Scale="1.5"
                    VerticalOptions="Center"
                    HorizontalOptions="Center"
                />

                <Border 
                    Grid.Column="0"
                    Grid.Row="0"
                    Margin="0" 
                    Padding="0" 
                    BackgroundColor="Transparent"
                >
                    <Image 
                        Source="{Binding Image.Source}"
                        Aspect="AspectFill"
                        HeightRequest="{Binding Image.HeightRequest}"
                        BackgroundColor="Transparent"
                        VerticalOptions="Center"
                        >
                        <Image.GestureRecognizers>
                            <TapGestureRecognizer Command="{Binding ClickGestureCarouselOnlyCommand}" />
                        </Image.GestureRecognizers>
                    </Image>
                </Border>
            </Grid>
        </Border>
    </DataTemplate>
</CarouselView.ItemTemplate>
```

So maybe u could use this image tap workaround for your case.

**Comment by Vroomer** [comment] 2023-08-07 10:38
@npostma I'm using 7.0.0-ci.net7.19653 on Windows right now. .NET 8 is crashing for me altogether. Your code is not a workaround for me.

**Comment by npostma** [comment] 2023-08-07 11:29
Not even when you overlay you carousel card with an invisible transparant image that holds the TapGesture? (Like a 1x1 px stretched image). I know, no one wants that, but we need to creative for now 🤔

**Comment by Vroomer** [comment] 2023-08-07 18:11
@npostma I can't overlay my CollectionView items because they contain buttons and entry fields.

**Comment by hartez** [comment] 2023-08-08 16:53
This issue is an agglomeration of about half a dozen different issues, so I'm going to do my best to address them all.

First off - if you've seen issues on iOS where some tap gestures on a page fire and others further down do not, and your items are inside of a ScrollView: you _might_ have been hitting a variation of #14257. It's not a gesture issue, it's a ScrollView issue. It's been addressed in .NET 8, and it's on the consideration list for backporting to .NET 7.  

We've also addressed some issues on iOS in .NET 7 and 8 with layouts on iOS not having user interaction enabled; you may have run into these, and now they're fixed. If you had problems with TapGestures on Grids, StackLayouts, ContentViews, Borders, Frames, etc., this may have been your actual issue. 

We've fixed some problems with Frame on Android which may have been preventing TapGesture from firing reliably.

We've also addressed some interaction issues with Frames as parts of DataTemplates, so if you've had a problem with DataTemplates containing Frames not honoring your TapGestures, that's likely been fixed.

If you're having problems with gestures on Spans, we're tracking that issue at https://github.com/dotnet/maui/issues/4734.

Because this issue has become so large and contains so many sub-issues unrelated to the original problem, we're asking that anyone who is _still_ experiencing problems with TapGesture on controls to open an issue _specific to their situation_ so that we can address them appropriately. We will be closing this issue.

**Closed** 2023-08-08 16:54 UTC
Labels: t/bug, platform/android 🤖, platform/iOS 🍎, p/1, partner/cat 😻, delighter, area/gestures
