### ISSUE TITLE
Publish as unpackage file the publish folder is missing static resource references at runtime.

### ISSUE THREAD

**Issue by danies8** [dotnet/maui#19244] opened 2023-12-06 08:38 UTC
### Description

Hello,

After testing, the two exe files are exactly equivalent, but the exe file inside the publish folder is missing static resource references at runtime.

Therefore, I  used the exe file from an external folder.

### Steps to Reproduce

1.Create maui app.
2.Add a class library A.
3.Add reference for static dll D and use it.
4.Add reference  from maui app to class library.
5. Publish maui app as exe using this cli command:
dotnet publish -f net8.0-windows10.0.19041.0 -c Release -p:WindowsPackageType=None -p:WindowsAppSDKSelfContained=true  -p:RuntimeIdentifierOverride=win10-x64
7. After testing, the two exe files are exactly equivalent, but the exe file inside the publish folder is missing static resource references at runtime.

### Link to public reproduction project repository

...

### Version with bug

8.0.3

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

7.0.101

### Affected platforms

Windows

### Affected platform versions

....

### Did you find any workaround?

Using  the exe file from an external folder

### Relevant log output

```shell
.....
```

**Comment by jfversluis** [comment] 2023-12-06 09:17
Duplicate of #19220

**Closed by jfversluis** 2023-12-06 09:17 UTC
Labels: t/bug
