### ISSUE TITLE
Add true SVG support

### ISSUE THREAD

**Issue by rimex-bkimmett** [dotnet/maui#26597] opened 2024-12-13 01:11 UTC
### Description

At present, if you add a .svg image to a .NET MAUI application, it is converted to a PNG before being added to each platform's resources. It would be nice if SVG images could be kept and displayed as vectors in the resulting app - this would resolve issues with sharpness of images on HiDPI displays, and the like.

### Public API Changes

No API changes would be necessary. Ideally, you could simply reference an .svg file in any `ImageSource` XAML attribute, and during compilation, the compiler would transform the SVG file appropriately (ex. into Android Vector Drawables on Android, etc.) so that they could be displayed as vectors.

### Intended Use-Case

The use-case is: anywhere images are displayed where you want the result to be crisp, regardless of how dense the end user's display is. And it would remove having to measure and set custom base sizes for each .SVG image.

**Comment by jfversluis** [comment] 2024-12-13 14:42
Duplicate of

**Closed by jfversluis** 2024-12-13 14:42 UTC
Labels: proposal/open, area-controls-image
