### ISSUE TITLE
Toggle buttons

### ISSUE THREAD

**Issue by LukeDunkley2005** [dotnet/maui#5236] opened 2022-03-11 16:37 UTC
### Description

I'm in the process of re-wrtiting a WPF app in .NET MAUI in order to support Mac OS. The only issue is the lack of toggle buttons, which would be nice to see, as MAUI will support windows, which is likely to use this feauture.

### Public API Changes

N/A

### Intended Use-Case

The feauture would be helpful to windows/mac os developers.

**Comment by davidbuckleyni** [comment] 2022-03-11 17:03
In Xamarin forms and maui their is a switch control with on and off

**Comment by LukeDunkley2005** [comment] 2022-03-16 11:57
> In Xamarin forms and maui their is a switch control with on and off 

Thanks for the suggestion. Toggle buttons would be buttons which can be checked, in the same way as check boxes, in the same way they work in WPF.

**Comment by davidbuckleyni** [comment] 2022-03-20 21:17
Yes but dont get ur needing something that says on and off still same thing. U can do a custom render I suspect

**Comment by jfversluis** [comment] 2022-08-12 13:00
Duplicate of #3893

**Closed by jfversluis** 2022-08-12 13:00 UTC
Labels: t/enhancement ☀️, proposal/open, area/controls 🎮, control-button
