### ISSUE TITLE
Delay in BackgroundColor update for Button in Release mode

### ISSUE THREAD

**Issue by barnasoba** [dotnet/maui#17056] opened 2023-08-29 09:41 UTC
### Description

In a minimal .NET MAUI project, when attempting to change the BackgroundColor of a Button in Release mode, there's a noticeable delay (around 30 seconds) before the change is reflected on the UI. This delay is not present in Debug mode. This behavior is consistent on both Android and iOS platforms.

### Steps to Reproduce

1. Create a minimal .NET MAUI project.
2.Use the provided XAML to create two buttons:
```xaml
<VerticalStackLayout Spacing="25" Padding="30,0" VerticalOptions="Center">
    <Button  x:Name="btn_test" Text="Hola" TextColor="White" BackgroundColor="Blue"/>
    <Button  x:Name="btn_change" Text="Change Color" Clicked="btn_change_Clicked" />
</VerticalStackLayout>
```
    

In the code-behind, add the click event for the btn_change button:
```cs
void btn_change_Clicked(System.Object sender, System.EventArgs e)
{
    btn_test.BackgroundColor = Colors.Aqua;
}
```
     

3. Compile and run the app in Release mode.
4. Click on the "Change Color" button and observe the delay before the "Hola" button's background color changes.

Expected Behavior

The BackgroundColor should update almost instantly, similar to the behavior in Debug mode.

Actual Behavior

There's a delay of around 30 seconds before the background color updates in Release mode.
Tested in virtual and real devices.

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

**Comment by mattleibow** [comment] 2023-08-30 17:52
Duplicate of https://github.com/dotnet/maui/issues/11662

**Comment by mattleibow** [comment] 2023-08-30 17:52
I found a workaround for now that is quite simple:


Remapping the property from BackgroundColor to Background fixed the issue. This is easy to do in the maui program app builder:

```cs
.ConfigureMauiHandlers(_ => 
{
	LabelHandler.Mapper.AppendToMapping(
		nameof(View.BackgroundColor),
		(handler, View) => handler.UpdateValue(nameof(IView.Background)));
	ButtonHandler.Mapper.AppendToMapping(
		nameof(View.BackgroundColor),
		(handler, View) => handler.UpdateValue(nameof(IView.Background)));
})
```

**Closed by mattleibow** 2023-08-30 17:52 UTC
Labels: t/bug, area/controls 🎮, control-button
