### ISSUE TITLE
MAUI  When clicking blank and the keyboard is hidden, Entry does not have corresponding processing events  And Xamarin can handle.

### ISSUE THREAD

**Issue by BaY1251** [dotnet/maui#18125] opened 2023-10-19 01:37 UTC
@PureWeen  In Xamarin, Entry did ultimately capture the focus, but after the soft keyboard disappeared, Unfocused was triggered for verification

The point is not the focus, but Entry needs to know that the soft keyboard is turned off in order to verify the data.

The core issue is that Entry needs to know that the keyboard has been turned off.
The handling event in Xamarin happens to be unfocused.
MAUI can have other events

Version with bug
8.0.0-rc.2.9373

Is this a regression from previous behavior?
Yes, this used to work in Xamarin.Forms

Affected platforms
Android

The image is a demonstration by Xamarin, and MAUI is currently **unable** to achieve this effect
![Keyboard](https://github.com/dotnet/maui/assets/48309205/352f14f4-8e7a-4fcf-bf53-2f20964cc9b3)
![assert](https://github.com/dotnet/maui/assets/48309205/b1e84598-fc32-4fba-a12a-525e284494a8)

_Originally posted by @BaY1251 in https://github.com/dotnet/maui/issues/16530#issuecomment-1765608201_

**Comment by mattleibow** [comment] 2023-10-19 18:24
@PureWeen  thoughts?

**Comment by mattleibow** [comment] 2023-10-19 18:25
@BaY1251 what platform is this?

**Comment by BaY1251** [comment] 2023-10-20 00:17
@mattleibow 
Version with bug
8.0.0-rc.2.9373

Is this a regression from previous behavior?
Yes, this used to work in Xamarin.Forms

Affected platforms
Android

**Comment by maonaoda** [comment] 2023-10-20 08:20
https://github.com/PureWeen/ShanedlerSamples/blob/0d4c4f4916fb765e0e7a37da85e42820b4e663af/ShanedlerSamples/Library/TapToCloseBehavior/TapToCloseBehavior.Android.cs#L145C1-L157C14
````C#
            public bool OnSingleTapUp(MotionEvent e)
            {
                var location = GetBoundingBox(_platformView);
                var point = new Point(e.RawX, e.RawY);

                if (location.Contains(point))
                    return true;

                if (KeyboardManager.IsSoftKeyboardVisible(_view))
                    KeyboardManager.HideKeyboard(_view);

               ```
                // Custom here: alawys clear focus
                if (_platformView.HasFocus && _view.IsFocused)                
                {
                    _platformView.ClearFocus();
                }
              ```

                return true;
            }
````

Based on TapToCloseBehavior , I have added my Custom  for  keeping Android with iOS that can clear focus after Hiding Keyboard.

**Comment by PureWeen** [comment] 2023-11-06 18:58
Duplicate of #16357

We can't have unfocusing an entry be a side effect of closing the SoftKeyboard for various a11y reasons, but we do need to supply an API that will let users fill in what they were using the unfocused event for. Which is what the issue linked above should do.

**Closed by PureWeen** 2023-11-06 18:58 UTC
Labels: area/controls 🎮, control-entry, s/triaged, s/needs-attention, migration-compatibility
