### ISSUE TITLE
[Windows] <CollectionView.Footer> in connection with <SearchBar>

### ISSUE THREAD

**Issue by xxjnaxx** [dotnet/maui#6672] opened 2022-04-29 13:20 UTC
### Description

<CollectionView.Footer> in connection with <SearchBar> will crash the app.

Close to #6671.

### Steps to Reproduce

1. https://github.com/xxjnaxx/Test2
2. Open Project
3. Open MainPage.xaml
4. debug
5. <SearchBar> is working
6. stop debug
7. remove  from <CollectionView.Footer>
8. Debug
9. Input in Searchbar
10. Crash

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10

**Comment by Redth** [comment] 2022-05-02 17:34
Not able to reproduce with MAUI's main code - there were some recent fixes to crashes with CollectionView that I believe fixed this and will be released in the next version.

**Closed by Redth** 2022-05-02 17:34 UTC
Labels: t/bug, area/collectionview 📃, s/needs-verification
