### ISSUE TITLE
Text alignment not respected in migrated project

### ISSUE THREAD

**Issue by owl-guy** [dotnet/maui#11251] opened 2022-11-10 09:45 UTC
### Description

In a project that was migrated from Xamarin.Forms, the TextAlignments (HorizontalTextAlignment and VerticalTextAlignment) are not respected. 
![image](https://user-images.githubusercontent.com/114725843/196125024-a9013e34-7864-43d2-b812-16fb52b366cf.png)
![image](https://user-images.githubusercontent.com/114725843/196125157-d8abeba7-e065-40f6-ac5a-6e2b222e90ba.png)

This kind of bug has already been reported (https://github.com/dotnet/maui/issues/1509), and it does not happen in an empty MAUI Project, but it still seems to happen in migrated projects. I also encountered this bug in a project I migrated to MAUI by dragging the old files into a fresh MAUI project (I cannot share code, as it's enterprise code).

### Steps to Reproduce

1. Migrate a Xamarin.Forms project as described here: https://github.com/dotnet/maui/wiki/Migrating-from-Xamarin.Forms-(Preview)
2. Create a Label with HorizontalOptions = Fill and HorizontalTextAlignment = "Center" or "End"
3. The Label will still be leftaligned (as with HorizontalTextAlignment = "Start")

### Link to public reproduction project repository

https://github.com/owl-guy/LabelAlignmentExample

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 30 and up

### Relevant log output

See also https://github.com/dotnet/maui/issues/10728

**Comment by mattleibow** [comment] 2022-11-10 19:14
Duplicate of #10728

**Comment by owl-guy** [comment] 2022-11-30 08:39
@flaviusmrn I love you man :) Works perfectly after adding the property. I'm curious though: why do we need to support rtl for the text alignment to work properly? Weird...

**Comment by Ghostbird** [comment] 2023-01-12 16:06
Oh man, this is SO WEIRD! Clearly there's something wrong in the implementation, because we DO NOT support RTL layout, yet without claiming we do, the labels don't align.

**Comment by hartez** [comment] 2023-01-12 17:30
> Oh man, this is SO WEIRD! Clearly there's something wrong in the implementation, because we DO NOT support RTL layout, yet we must lie and say that we do, otherwise the label text won't align properly.

The text alignment code has different logic paths in situations where RTL is taken into consideration. So it sounds like the branch for "supportsRTL" is working correctly and the other branch is busted. Which is why it works fine in new projects (RTL support probably defaults to `true`), and why it doesn't work in migrated projects.

**Comment by hartez** [comment] 2023-01-12 17:34
So the problem might be here, where we convert the alignment to a horizontal gravity: https://github.com/dotnet/maui/blob/main/src/Core/src/Platform/Android/TextViewExtensions.cs#L52

Or it might be that another property is also trying to set the horizontal gravity, and is blowing away the value set by `UpdateHorizontalTextAlignment()`.

**Comment by Ghostbird** [comment] 2023-01-13 07:08
> > Oh man, this is SO WEIRD! Clearly there's something wrong in the implementation, because we DO NOT support RTL layout, yet we must lie and say that we do, otherwise the label text won't align properly.
> 
> The text alignment code has different logic paths in situations where RTL is taken into consideration. So it sounds like the branch for "supportsRTL" is working correctly and the other branch is busted. Which is why it works fine in new projects (RTL support probably defaults to `true`), and why it doesn't work in migrated projects.

Well, I made a new project, and then I removed the added `android:supportsRtl` label because we don't support it. I normally wouldn't add such a label until:

1. We support at least one culture that writes RTL
2. The app has been thoroughly tested in that culture

**Comment by FM1973** [comment] 2023-03-29 14:29
This is still an issue.
A Label inside a Border doesn´t respect HorizontalTextAlignment in Android.
Setting android:supportsRtl="true" helps, though we don´t support it. :(

**Comment by jstedfast** [comment] 2023-05-04 18:42
Confirmed still an issue.

**Comment by AdamDiament** [comment] 2023-06-29 11:30
Still an issue

**Comment by Zhanglirong-Winnie** [comment] 2023-07-13 05:57
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 2.0. Not repro on android platform with sample project.
[LabelAlignmentExample.zip](https://github.com/dotnet/maui/files/12035860/LabelAlignmentExample.zip)
![Screenshot 2023-07-13 112742](https://github.com/dotnet/maui/assets/77434865/3327e342-4bb4-4e9a-9761-f66725fb8178)

**Comment by albilaga** [comment] 2023-08-03 11:40
this is still happening in our project and `android:supportsRtl="true"`  helps but we don't supportsRtl actually. tested in 7.0.92. Do you mind share how to run your sample @Zhanglirong-Winnie ? Because in `LabelAlignmentExample` there is still `android:supportsRtl="true"` and testing `LabelAlignmentExampleMigrated.Android` still make text not respecting `HorizontalTextAlignment`
<img width="369" alt="CleanShot 2023-08-03 at 18 36 32@2x" src="https://github.com/dotnet/maui/assets/2399099/0e044e37-4748-49d2-a137-3f8a4a99c01b">

Tested both in Rider 2023.2 and Visual Studio for Mac 17.6.2 (build 405) with dotnet maui 7.0.92
<img width="789" alt="CleanShot 2023-08-03 at 18 37 45@2x" src="https://github.com/dotnet/maui/assets/2399099/c1afe185-4e01-4854-b4d3-decbed07ffe4">

**Comment by hartez** [comment] 2023-08-07 19:41
When RTL support is not enabled (or on lower API versions), the horizontal text alignment is handled via the Gravity property. But all the places which map VerticalTextAlignment are blindly settings the vertical gravity without paying attention to the horizontal gravity, so the horizontal setting is simply blown away. 

The VerticalTextAlignment mappings need to be OR'ed with the HorizontalTextAlignment gravity values.

**Comment by hartez** [comment] 2023-08-07 19:42
Also, whoever fixes this and adds tests for Label should probably check Entry (EditText) to see if the same problem is occurring there.

**Closed** 2023-08-27 21:21 UTC
Labels: t/bug, good first issue, platform/android 🤖, partner/cat 😻, area/controls 🎮, area/localization, control-label, s/triaged, migration-compatibility
