### ISSUE TITLE
Build fails due to problems with Android manifest generation.

### ISSUE THREAD

**Issue by voroninp** [dotnet/maui#21545] opened 2024-03-31 15:09 UTC
### Description

Very often but randomly my build fails with this error:
![image](https://github.com/dotnet/maui/assets/9202028/8f0be314-e0e5-4d93-995a-59bd28dc972b)

I have to remove `bin` and `obj` folders every time this happens.

### Steps to Reproduce

I have no idea how to reproduce it and what causes the issue.

### Version with bug

Unknown/Other

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Did you find any workaround?

Deleting `bin` and `obj` folders.

### Relevant log output

```shell
Will attach as a separate comment...
```

**Comment by voroninp** [comment] 2024-03-31 15:13
Build log: [Failing Build Log.txt](https://github.com/dotnet/maui/files/14816452/Failing.Build.Log.txt)

**Comment by developer9969** [comment] 2024-03-31 16:13
This is a bug since .net 7 that the team has never addressed and still present in 8.0.14.
Just remove app icon in Android manifest 
Rebuild 
Re-add it 

Pity it's has never been fixed

**Comment by QianaJiao** [comment] 2024-04-01 05:16
This bug has been around for a long time and we have many related FeedBack and known bugs, such as: 
https://github.com/dotnet/maui/issues/21084 Debug start doesn't run the app, getting some errors 
[FeedbackTicket 2004811:](https://dev.azure.com/devdiv/DevDiv/_workitems/edit/2004811) Android mipmap/appicon failing with "APT2260 resource mipmap/appicon (aka xxx:mipmap/appicon) not found."

This bug still unstable repro now. (17.10.0 preview2 (8.0.14))

**Comment by HuaFangYun** [comment] 2024-04-01 07:18
The first build and compilation of the open program will report this error, is it the same as the above problem?
严重性	代码	说明	项目	文件	行	禁止显示状态	详细信息
错误	APT2067	failed processing manifest.
	MAUI8Example	C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.85\tools\Xamarin.Android.Aapt2.targets	214		

严重性	代码	说明	项目	文件	行	禁止显示状态	详细信息
错误	APT2260	resource mipmap/appicon (aka com.companyname.maui8example:mipmap/appicon) not found.

This error is likely caused by an issue with the AndroidManifest.xml file or an Android manifest generation attribute in a source code file.	MAUI8Example	D:\temp2\MAUI8Example-master\MAUI8Example-master\MAUI8Example\Platforms\Android\AndroidManifest.xml	1		
严重性	代码	说明	项目	文件	行	禁止显示状态	详细信息
错误	APT2260	resource mipmap/appicon_round (aka com.companyname.maui8example:mipmap/appicon_round) not found.

This error is likely caused by an issue with the AndroidManifest.xml file or an Android manifest generation attribute in a source code file.	MAUI8Example	D:\temp2\MAUI8Example-master\MAUI8Example-master\MAUI8Example\Platforms\Android\AndroidManifest.xml	1

**Comment by samhouts** [comment] 2024-04-02 17:51
Duplicate of #21084

**Closed by samhouts** 2024-04-02 17:51 UTC
Labels: t/bug, platform/android 🤖, s/verified, s/triaged
