### ISSUE TITLE
[MAUI] An error 'XAPRAS7004 :System.ArgumentException: must not be null or emptyParameter name: abi ...'will happen when building the existing Projects recipeSearch & ManualMauiTests

### ISSUE THREAD

**Issue by ninachen03** [dotnet/maui#26056] opened 2024-11-22 10:31 UTC
### Description

1. Build the existing Projects recipeSearch & ManualMauiTests project. will meet the error
System.ArgumentException: must not be null or emptyParameter name: abi   at Xamarin.Android.Tasks.ProcessAssemblies.SetAssemblyAbiMetadata(String abi, ITaskItem assembly, ITaskItem symbol) in /Users/runner/work/1/s/xamarin-android/src/Xamarin.Android.Build.Tasks/Tasks/ProcessAssemblies.cs:line 99   at Xamarin.Android.Tasks.ProcessAssemblies.SetMetadataForAssemblies(List`1 output, Dictionary`2 symbols) in /Users/runner/work/1/s/xamarin-android/src/Xamarin.Android.Build.Tasks/Tasks/ProcessAssemblies.cs:line 124   at Xamarin.Android.Tasks.ProcessAssemblies.RunTask() in /Users/runner/work/1/s/xamarin-android/src/Xamarin.Android.Build.Tasks/Tasks/ProcessAssemblies.cs:line 62   at Microsoft.Android.Build.Tasks.AndroidTask.Execute() in /Users/runner/work/1/s/xamarin-android/external/xamarin-android-tools/src/Microsoft.Android.Build.BaseTasks/AndroidTask.cs:line 25

### Steps to Reproduce

1. Download the project https://github.com/rachelkang/recipeSearch or https://devdiv.visualstudio.com/Pkgs/_git/VS.TestAssets.Xaml?path=/Assets/Projects/ManualMauiTests and open it in Visual Studio.
2. Change the NET Framework to Net 9
3. Build the project.
4. Observed the error List
![Image](https://github.com/user-attachments/assets/2d7c91ac-1fa6-4a06-a0b1-9b14a3ce2e1d)

### Link to public reproduction project repository

https://github.com/rachelkang/recipeSearch

### Version with bug

· VS Version: 17.13.0 Preview 2.0 [35520.232.main]
· Microsoft.Maui.Controls: 9.0.0
· .NET SDK: 9.0.200-preview.0.24529.19
· Sdk-manifest: 9.0.100
· microsoft.net.sdk.android: 35.0.7
· microsoft.net.sdk.maui: 9.0.0
· microsoft.net.sdk.ios:18.0.9617
· microsoft.net.sdk.Maccatalyst:18.0.9617
microsoft.net.workload.mono.toolchain.current: 9.0.0

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

· VS Version: 17.13.0 Preview 2.0 [35519.241.main]
· Microsoft.Maui.Controls: 9.0.0
· .NET SDK: 9.0.200-preview.0.24529.19
· Sdk-manifest: 8.0.100 & 9.0.100
· microsoft.net.sdk.android: 35.0.7
· microsoft.net.sdk.maui: 9.0.0
It seems to have nothing to do with Maui control. I haven't investigated the specific cause of the impact, but I can give you the previous working version.

### Affected platforms

Android

**Comment by jfversluis** [comment] 2024-11-25 11:01
Duplicate of #26092

**Closed by jfversluis** 2024-11-25 11:01 UTC
Labels: t/bug, platform/android 🤖, area-testing, s/verified, s/triaged, csi-new
