### ISSUE TITLE
Can not launch app after adding Entitlements.plist for MacCataylst

### ISSUE THREAD

**Issue by Onotseike** [dotnet/maui#23548] opened 2024-07-10 20:47 UTC
### Description

Hello,
I added an Entitlements.plist in accordance with the directions in this [Add Entitlement to MacCatalyst](https://learn.microsoft.com/en-us/dotnet/maui/mac-catalyst/entitlements?view=net-maui-8.0). 
However, I could not use the VS for Mac since it is deprecated. I added the following code to my csproj file

```
 <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net8.0-maccatalyst|AnyCPU'">
      <EnableCodeSigning>True</EnableCodeSigning>
      <CodesignKey>Apple Development: onotseike@outlook.com (6SQ97WKYTS)</CodesignKey>
      <CodesignProvision>Automatic</CodesignProvision>
      <CodesignEntitlements>Platforms\MacCatalyst\Entitlements.plist</CodesignEntitlements>
 </PropertyGroup>
```

But when I try to run my code I get the following error:

> MAUI/bin/Debug/net8.0-maccatalyst/maccatalyst-arm64/MoonLight.MAUI.app
The application cannot be opened for an unexpected reason, error=Error Domain=RBSRequestErrorDomain Code=5 "Launch failed." UserInfo={NSLocalizedFailureReason=Launch failed., NSUnderlyingError=0x6000016b4450 {Error Domain=NSPOSIXErrorDomain Code=153 "Unknown error: 153" UserInfo={NSLocalizedDescription=Launchd job spawn failed}}}

I am unsure of how to proceed and could the documentation for MacCatalyst be updated to reflect the current state of how to add a custom entitlement for maccatalyst?

I have attached my csproj in zipped file
[MoonLight.MAUI.csproj.zip](https://github.com/user-attachments/files/16168815/MoonLight.MAUI.csproj.zip)

### Version with bug

8.0.40 SR5

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

**Comment by kevinxufei** [comment] 2024-08-16 01:26
Hi,@Onotseike
I'm sorry that I can't repeat your question according to this operation. Could you please upload a sample project for our investigation? Looking forward to your reply. Thank you!

**Comment by jfversluis** [comment] 2024-09-02 11:09
Yeah these docs still need updating, see [here](https://github.com/dotnet/docs-maui/issues/2341).

Could you try to make the path just `<CodesignEntitlements>Entitlements.plist</CodesignEntitlements>`?

**Comment by Onotseike** [comment] 2024-09-06 08:26
> Yeah these docs still need updating, see [here](https://github.com/dotnet/docs-maui/issues/2341).
> 
> 
> 
> Could you try to make the path just `<CodesignEntitlements>Entitlements.plist</CodesignEntitlements>`? 

Thank you, that worked.

**Comment by mattleibow** [comment] 2024-11-22 19:05
Closing the issue as the issue is fixed.

**Closed by mattleibow** 2024-11-22 19:05 UTC
Labels: t/bug, platform/macOS 🍏, s/triaged, s/needs-attention
