### ISSUE TITLE
AccessViolationException in Release Mode when Adding Custom Resource Dictionary

### ISSUE THREAD

**Issue by Kamalesh-Periyasamy** [dotnet/maui#19999] opened 2024-01-19 09:40 UTC
### Description

I created a custom resource dictionary in the application file to support themes. Subsequently, I added the custom resource dictionary to the merged dictionaries, as shown below. I encounter an AccessViolationException when running the application in release mode only. However, the example deploys successfully in debug mode. I have attached a runnable example. Please check it and let me know if you have any concerns.

```
<?xml version = "1.0" encoding = "UTF-8" ?>
	<Application xmlns="[http://schemas.microsoft.com/dotnet/2021/maui"](http://schemas.microsoft.com/dotnet/2021/maui%22)
	             xmlns:x="[http://schemas.microsoft.com/winfx/2009/xaml"](http://schemas.microsoft.com/winfx/2009/xaml%22)
	             xmlns:local="clr-namespace:CustomThemeTesting"
	             x:Class="CustomThemeTesting.App">
	
	<Application.Resources>
		<ResourceDictionary>
			<ResourceDictionary.MergedDictionaries>
				<ResourceDictionary Source="Resources/Styles/Colors.xaml" />
				<ResourceDictionary Source="Resources/Styles/Styles.xaml" />
				<local:CustomThemeResourceDictionary VisualTheme="LightDefault" />
			</ResourceDictionary.MergedDictionaries>
		</ResourceDictionary>
	</Application.Resources>
</Application>
```

### Steps to Reproduce

1. Download and extract the attached example file.
2. Run the example in release mode.
3. Observe the access violation exception.
[CustomThemeTesting.zip](https://github.com/dotnet/maui/files/13987165/CustomThemeTesting.zip)

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

**Comment by PaulAndersonS** [comment] 2024-01-23 10:27
Any timeline for this issue @jsuarezruiz

**Comment by Ahamed-Ali** [comment] 2024-02-02 10:35
Please prioritize this with high urgency and address the issue as soon as possible. Any workarounds or suggestions to resolve this issue promptly would be greatly appreciated

**Comment by Choza-rajan** [comment] 2024-02-05 03:12
Very hard issue in release mode. It's any timeline to fix this issue @samhouts

**Comment by StephaneDelcroix** [comment] 2024-02-08 15:20
duplicate of @19535

**Closed by StephaneDelcroix** 2024-02-08 15:20 UTC
Labels: t/bug, platform/macOS 🍏, area/Xaml </>, platform/windows 🪟, platform/android 🤖, platform/iOS 🍎, high, i/regression
