### ISSUE TITLE
[Bug] BoxView loses background color when its parent is removed and re-added to the container

### ISSUE THREAD

**Issue by alexeystrakh** [dotnet/maui#3214] opened 2021-11-01 21:02 UTC
### Description

BoxView loses background color when its parent is removed and re-added to the container. Rearrange is added in order to change the control's (target) z-index to move on top of other items.

### Steps to Reproduce

1. Create an AbsoluteLayout, Grid inside with BoxView 
2. Remove and re-add the Grid from/to AbosoluteLayout container

### Expected Behavior

BoxView keeps the background color

### Actual Behavior

BoxView has no background after the step 2

### Basic Information

- Version with issue: 6.0.100-rc.2.21505.57
- Last known good version: NA
- IDE: VS2022 - Preview 5
- Platform Target Frameworks: iOS, Android, Windows

### Screenshots

the target in its original state:
![image](https://user-images.githubusercontent.com/3697084/139740817-bee9d617-4067-41b0-aa5d-8bc435efe4a7.png)

the target after being removed and readded to the container
![image](https://user-images.githubusercontent.com/3697084/139740853-4cbabba6-df9a-41dc-87e4-1acdc6777025.png)

### Reproduction Link

```
<Grid x:Name="target">
    <BoxView BackgroundColor="Red" WidthRequest="50" HeightRequest="50" />
</Grid>

var targetContainer = target.Parent as Layout;
targetContainer.Children.Remove(target);
targetContainer.Children.Add(target);
```

### Workaround

None is found

**Comment by hartez** [comment] 2021-11-02 14:56
@alexeystrakh Do you have the same issue if you use a Rectangle?

**Comment by alexeystrakh** [comment] 2021-11-03 23:17
I have reproduced this issue after adding a few more controls to the layout, the underlying issue is not with the color but with the Grid layout which is not properly resized after the control is being added back to the layout in runtime.

**Comment by hartez** [comment] 2021-11-04 20:01
@alexeystrakh How are you positioning the Grid inside the AbsoluteLayout?

**Comment by hartez** [comment] 2021-11-04 20:08
@alexeystrakh I'm attaching my effort at reproducing this - can you take a look and tell me what I'm missing? Removing and re-adding the Grid, it seems to be sized fine and contain the expected BoxViews.

[ReparentRepro.zip](https://github.com/dotnet/maui/files/7478181/ReparentRepro.zip)

**Comment by hartez** [comment] 2021-11-06 02:32
This is not limited to BoxView - any Shape we remove and re-add has this issue.

**Comment by jsuarezruiz** [comment] 2021-11-08 12:13
@hartez  I can't reproduce it in main branch, could you attach an example or share more details?. Thanks!

**Comment by hartez** [comment] 2021-11-13 00:25
Fix is merged in MAUI.Graphics - once we get the new version pulled into MAUI we can test again and possibly close this.

**Closed** 2022-02-22 09:08 UTC
Labels: t/bug, area/layout 🔲, partner, partner/winui, area/desktop 🖥️, s/verified
