### ISSUE TITLE
[regression/8.0.0-rc.1.9171] Build error in .NET 8 RC1 - "XamlC error XFC0126: Resources in ResourceDictionary require a x:Key attribute" for resources that have a key 

### ISSUE THREAD

**Issue by brunck** [dotnet/maui#17461] opened 2023-09-18 17:37 UTC
### Description

Using version `8.0.100-rc.1.23455.8` 
Building a .NET MAUI app created using RC1 and VS 2022 preview via File -> New Project and adding the given lines errors with `XamlC error XFC0126: Resources in ResourceDictionary require a x:Key attribute.`

This appears to be a regression; the same code worked in .NET 8 preview 7.

### Steps to Reproduce

1. Create a File -> New .NET MAUI app
2. Add these lines to the `App.xaml` file:
```
<Color x:Key="LightSmoke">#4FFFFFFF</Color>

<OnPlatform x:Key="EntryBackgroundColor" x:TypeArguments="Color">
    <On Platform="iOS" Value="{StaticResource LightSmoke}" />
    <On Platform="Android" Value="Transparent" />
</OnPlatform>
```
3. Build fails with the given error message.

Or, use the solution in the given reproduction repository in the `MauiResourceDictionaryBuildError` folder.

### Link to public reproduction project repository

https://github.com/brunck/reproductions.git

### Version with bug

[8.0.0-rc.1.9171](https://github.com/dotnet/maui/releases/tag/8.0.0-rc.1.9171)

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.0-preview.7.8842

### Affected platforms

I was *not* able test on other platforms

### Affected platform versions

n/a

### Did you find any workaround?

Removing the related lines causes the build to pass.

**Comment by tentom** [comment] 2023-09-19 14:10
I get this same issue if I try to use <OnPlatform> in my App.Xaml file. 
`Error XFC0126: Resources in ResourceDictionary require a x:Key attribute. (XFC0126) (Overskudd) XamlC`

But it seems to work if I do use a static resource as the value as the following works:
```
<OnPlatform x:Key="MediumFontFamily"
                    x:TypeArguments="x:String"
                    >
            <On Platform="Android" Value="sans-serif-medium"/>
            <On Platform="iOS" Value="Arial"/>
</OnPlatform>
```

While this does not work and gives the error mentioned before.
```
<OnPlatform x:Key="RegularFontFamily"
                    x:TypeArguments="x:String"
                    >
    <On Platform="Android" Value="{StaticResource AppFontFamily}"/>
    <On Platform="iOS" Value="{StaticResource AppFontFamily}"/>
</OnPlatform>
```

Another side note that might be related is that when using a merged resource dictionary another error appears when using <OnPlatform> namely:
`Error: Collection was modified; enumeration operation may not execute. XamlC`

So in my App.xaml file I have
```
<ResourceDictionary.MergedDictionaries>
    <local:MyAppTheme />
</ResourceDictionary.MergedDictionaries>
 ```
 
 and in a separate file MyAppTheme 
 
 ```
 <ResourceDictionary>
     <OnPlatform x:Key="ImageHighlightedColor" x:TypeArguments="Color" Default="{ StaticResource AccentColor }" />
 </ResourceDictionary>
 ```
 
 Im Running on a Mac and compiling for iOS

**Comment by samhouts** [comment] 2023-09-19 20:42
I was not able to reproduce this with the given project. It builds and runs with RC1. Is there more required?

**Comment by brunck** [comment] 2023-09-19 20:51
@samhouts It definitely does not build for me using the latest VS 2022 preview. Just open and try to build the solution in the `MauiResourceDictionaryBuildError` folder.  No other action is required.
What other info do you need from me?

**Comment by XamlTest** [comment] 2023-09-21 06:25
Verified this on Visual Studio Enterprise 17.8.0 Preview 2.0(8.0.0-rc.1.9171). Repro with the given project:
[MauiRc1App.zip](https://github.com/dotnet/maui/files/12681001/MauiRc1App.zip)

![image](https://github.com/dotnet/maui/assets/97647558/be3a4f3b-a59d-4ee1-8d6e-62ad32a23717)

**Comment by StephaneDelcroix** [comment] 2023-09-22 09:09
the `Collection was modified error is fixed`. this might be related to OnPlatform optimisation, checking if I can repro and unit test

**Comment by StephaneDelcroix** [comment] 2023-09-22 10:03
I can not reproduce this. which platform are you compiling for ?

**Comment by brunck** [comment] 2023-09-22 10:06
This is single-project MAUI…how do you compile for just one platform? Android I guess?

**Comment by samhouts** [comment] 2023-09-28 23:44
Oh, that's strange. If I hit F5, it builds and runs successfully. If I just do Build, it fails.

Confirmed that this regressed between [8.0.0-preview.7.8842](https://github.com/dotnet/maui/releases/tag/8.0.0-preview.7.8842) and [8.0.0-rc.1.9171](https://github.com/dotnet/maui/releases/tag/8.0.0-rc.1.9171). https://github.com/dotnet/maui/pull/5611 looks sus, @StephaneDelcroix

**Comment by brunck** [comment] 2023-09-28 23:46
That’s very strange! I don’t think I’ve ever seen or heard of this type of thing happening before.

**Comment by StephaneDelcroix** [comment] 2023-09-29 07:00
trying again to produce a unit test...

**Comment by StephaneDelcroix** [comment] 2023-09-29 07:35
I think I understand what's going on. SimplifyOnPlatform was meant to simplify code generation, but using it as a Resource was never a use case. I might need to rethink this. Depending on the deadlines, we might have to revert #5611

**Closed** 2023-10-23 16:05 UTC
Labels: t/bug, area/Xaml </>, s/verified, s/triaged, i/regression
