### ISSUE TITLE
[Android] Content wrapped in NavigationPage objects in Tabbed Page disappears after tabs navigating

### ISSUE THREAD

**Issue by neordi** [dotnet/maui#9743] opened 2022-08-29 13:22 UTC
### Description

While navigating between 4 or more tabs that are wrapped in a 'NavigationPage' objects in 'TabbedPage', some tabs disappear. Instead of them blank Navigation Page is displayed and no errors are provided. OnAppearing() method is invoked but no contents are displayed.

On IOS 'TabbedPage' with 'NavigationPage' objects as children behaves as expected.

Reproduction project is [here](https://github.com/neordi/maui_tabbedpage_bug).

<img src="https://user-images.githubusercontent.com/108667905/187200759-ac849c39-c540-4574-9794-c85bea4064ad.gif" width="400"/>

### Steps to Reproduce

1. Create a File > New .Net MAUI App
2. Replace 'ContentPage' with 'TabbedPage'
3. Add to 'TabbedPage' 4 children that are wrapped in a 'NavigationPage' objects
4. Launch Project on Android
5. Navigate from 1st tab to 4th and than to 1st again.

Content of 1st tab has disappeared.

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11 and up

**Comment by 0mpurdy** [comment] 2022-11-01 11:05
I have a temporary workaround for this, where you can increase the OffscreenPageLimit. The [Xamarin.Forms property](https://learn.microsoft.com/en-us/xamarin/xamarin-forms/platform/android/tabbedpage-page-swiping) works, it looks like it's not hooked up properly in MAUI. This obviously is a tradeoff, and ideally the reload when it goes out of scope would also work.

```csharp
private void ModifyTabbedPageHandler()
{
    Microsoft.Maui.Handlers.TabbedViewHandler.Mapper.AppendToMapping("FixMultiTab", (handler, view) =>
    {
#if ANDROID
        var viewPager = (AndroidX.ViewPager2.Widget.ViewPager2)handler.PlatformView;
        viewPager.OffscreenPageLimit = 5;
#endif
    });
}
```

[This issue from Xamarin](https://github.com/xamarin/Xamarin.Forms/issues/10783) is similar, except that it's doing what I'd expect (where the page is reloaded if it goes out of scope), whereas in MAUI at the moment it just stays blank.

**Comment by jbe2277** [comment] 2022-11-15 18:54
**https://github.com/dotnet/maui/issues/10108 Android: UI elements disappear when showing page, the 2nd time**
seems to be resolved with .NET7/MAUI7.

The issue is categorized as duplicate of this one. Maybe this is resolved as well.

**Comment by tranb3r** [comment] 2022-12-05 12:44
I'm still having this issue, even with the latest version of maui, net7, VS.

**Comment by tranb3r** [comment] 2022-12-05 12:50
Could you please re-open this issue or mark it as duplicate of #7558, and then fix it ?

**Comment by drasticactions** [comment] 2023-01-19 08:39
The bot closed this bug prematurely, https://github.com/dotnet/maui/pull/11530 should be resolved first.

**Comment by tranb3r** [comment] 2023-01-26 20:14
@drasticactions 
The bot has closed this issue again, could you please reopen it one more time, since the PR is sitll open?
Thanks

**Comment by PureWeen** [comment] 2023-01-27 16:08
@tranb3r Can you try this work around and see how it goes? 


Copy the files from here to your project

https://github.com/PureWeen/ShanedlerSamples/tree/main/ShanedlerSamples/Library

Then in your builder you can call

```C#

builder
            .UseMauiApp<App>()
            .ConfigureTabbedPageWorkarounds()
```

**Comment by tranb3r** [comment] 2023-01-27 20:59
@PureWeen 
I've done some tests of your fix, both on my repro project and then on my app.
I confirm that the tabs work now as expected: no more blank page.

However, sometimes, the navigation (push page) does not work. I'm prettry sure it's linked to your fix.
Here is the log message when the navigation does not work:
`[FragmentNavigator] Ignoring navigate() call: FragmentManager has already saved its state`
Any idea what's happening?

**Comment by tranb3r** [comment] 2023-01-31 11:46
@PureWeen How can I help?

**Comment by PureWeen** [comment] 2023-01-31 17:42
> @PureWeen How can I help?

I might have missed it but can you point me to your repro project with this workaround applied? 
working inside that space will help.

**Comment by tranb3r** [comment] 2023-01-31 19:21
> I might have missed it but can you point me to your repro project with this workaround applied? working inside that space will help.

https://github.com/tranb3r/Issues/tree/main/MauiAppTabbedPageBlank

**Comment by PureWeen** [comment] 2023-02-03 17:34
> > I might have missed it but can you point me to your repro project with this workaround applied? working inside that space will help.
> 
> https://github.com/tranb3r/Issues/tree/main/MauiAppTabbedPageBlank

I updated my samples.
let me know how that works.

**Comment by tranb3r** [comment] 2023-02-03 20:34
Looks good to me. Thank you!!

**Closed** 2023-02-06 22:14 UTC
Labels: t/bug, platform/android 🤖, area/migration 🚚, area/TabbedPage

**Comment by tranb3r** [comment] 2023-03-03 14:21
@PureWeen 
I'm having one more issue with your code.
Here is an exception I get when programmatically adding a new Tab to the TabbedPage:
```
System.InvalidCastException: Specified cast is not valid.
    at Microsoft.Maui.Controls.Handlers.TabbedPageManager.OnChildrenCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e) in D:\a\_work\1\s\src\Controls\src\Core\Platform\Android\TabbedPageManager.cs:line 274
    at System.Collections.ObjectModel.ObservableCollection`1[[Microsoft.Maui.Controls.Element, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].OnCollectionChanged(NotifyCollectionChangedEventArgs e)
    at System.Collections.ObjectModel.ObservableCollection`1[[Microsoft.Maui.Controls.Element, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].OnCollectionChanged(NotifyCollectionChangedAction action, Object item, Int32 index)
    at System.Collections.ObjectModel.ObservableCollection`1[[Microsoft.Maui.Controls.Element, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].InsertItem(Int32 index, Element item)
    at System.Collections.ObjectModel.Collection`1[[Microsoft.Maui.Controls.Element, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].Insert(Int32 index, Element item)
    at Microsoft.Maui.Controls.ObservableWrapper`2[[Microsoft.Maui.Controls.Element, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Controls.Page, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].Insert(Int32 index, Page item) in D:\a\_work\1\s\src\Controls\src\Core\ObservableWrapper.cs:line 137
```
Is this something that can be fixed in your code?
Thanks!

**Comment by PureWeen** [comment] 2023-03-03 15:27
> @PureWeen I'm having one more issue with your code. Here is an exception I get when programmatically adding a new Tab to the TabbedPage:
> 
> ```
> System.InvalidCastException: Specified cast is not valid.
>     at Microsoft.Maui.Controls.Handlers.TabbedPageManager.OnChildrenCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e) in D:\a\_work\1\s\src\Controls\src\Core\Platform\Android\TabbedPageManager.cs:line 274
>     at System.Collections.ObjectModel.ObservableCollection`1[[Microsoft.Maui.Controls.Element, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].OnCollectionChanged(NotifyCollectionChangedEventArgs e)
>     at System.Collections.ObjectModel.ObservableCollection`1[[Microsoft.Maui.Controls.Element, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].OnCollectionChanged(NotifyCollectionChangedAction action, Object item, Int32 index)
>     at System.Collections.ObjectModel.ObservableCollection`1[[Microsoft.Maui.Controls.Element, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].InsertItem(Int32 index, Element item)
>     at System.Collections.ObjectModel.Collection`1[[Microsoft.Maui.Controls.Element, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].Insert(Int32 index, Element item)
>     at Microsoft.Maui.Controls.ObservableWrapper`2[[Microsoft.Maui.Controls.Element, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Controls.Page, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].Insert(Int32 index, Page item) in D:\a\_work\1\s\src\Controls\src\Core\ObservableWrapper.cs:line 137
> ```
> 
> Is this something that can be fixed in your code? Thanks!

Hmmmmm let me think on that. I'll push something up over on my repository :-/

**Comment by PureWeen** [comment] 2023-03-03 16:40
@tranb3r I pushed some changes over here
https://github.com/PureWeen/ShanedlerSamples

it's a bit weird :-) so we'll see

if you hit another issue just log it on that Repository.

**Comment by breenbob** [comment] 2023-03-10 17:02
@PureWeen Can this fix be backported to .Net 7?

**Comment by tranb3r** [comment] 2023-04-12 10:49
The bug is still here in maui SR 7.0.81.
