### ISSUE TITLE
editor Small problem

### ISSUE THREAD

**Issue by itldg** [dotnet/maui#11815] opened 2022-12-02 08:14 UTC
### Description

If a shorter Placeholder is set, the input will wrap early.
![22cb03a4aa659672138c23271f59e5e](https://user-images.githubusercontent.com/13432299/205247064-ffcabf6e-d40f-44ce-ba62-110f81026cee.jpg)

If TextTransform = "Uppercase" is set, the cursor will precede the first character each time you enter.

### Steps to Reproduce

<Editor MaxLength="24" x:Name="code" Placeholder="请输入代码" FontSize="15" HorizontalTextAlignment="Center" Keyboard="Email" TextTransform="Uppercase"></Editor> 

### Link to public reproduction project repository

no

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

android12

**Comment by PureWeen** [comment] 2022-12-08 19:28
Duplicate of #11313

Your other issue should be fixed with the upcoming SR of .NET 7.0
If the next release doesn't fix your issue, please let us know.

**Closed by PureWeen** 2022-12-08 19:28 UTC
Labels: t/bug, platform/android 🤖, area/controls 🎮, control-entry
