### ISSUE TITLE
PointerGestureRecognizer Does not work on android

### ISSUE THREAD

**Issue by ASiNet-ASiDev** [dotnet/maui#22199] opened 2024-05-03 15:04 UTC
### Description

My code:
```xml
<?xml version="1.0" encoding="utf-8" ?>
<Border xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
        xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
        x:Class="WCPApp.Viewe.Joystick"
        WidthRequest="400" HeightRequest="400" Background="#444444">
    <Border.StrokeShape>
        <RoundRectangle CornerRadius="50"/>
    </Border.StrokeShape>
    <Border.GestureRecognizers>
        <PointerGestureRecognizer PointerMoved="PointerGestureRecognizer_PointerMoved" 
                                  PointerPressed="PointerGestureRecognizer_PointerPressed"
                                  PointerReleased="PointerGestureRecognizer_PointerReleased"
                                  PointerExited="PointerGestureRecognizer_PointerExited"/>
    </Border.GestureRecognizers>
    <Path x:Name="PointerHandler" Fill="#FFFFFF" 
      WidthRequest="40"
      HeightRequest="40">
        <Path.Data>
            <EllipseGeometry RadiusX="20" RadiusY="20" Center="20, 20"/>
        </Path.Data>
    </Path>
</Border>
```
Outputs this to the console:
```
[AutofillManager] requestHideFillUi(null): anchor = null
[AutofillManager] requestHideFillUi(null): anchor = null
[AutofillManager] requestHideFillUi(null): anchor = null
```
Events are not triggered, while if you run on Windows everything works fine

### Steps to Reproduce

Try to get gesture events by creating similar code like mine

### Version with bug

8.0.7, 8.0.14, 8.0.21

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 13

### Did you find any workaround?

No, I didn't find it.

**Comment by ASiNet-ASiDev** [comment] 2024-05-04 18:10
Hello, here is a link to the project where I am having problems with PointerGestureRecognizer on Android:
https://github.com/ASiNet-ASiDev/Issue22199.PointerGestureRecognizerExample

**Comment by ASiNet-ASiDev** [comment] 2024-05-04 18:18
Wndows output:
```
PointerExited
PointerPressed
PointerMoved
PointerMoved
PointerMoved
PointerMoved
PointerMoved
PointerReleased
PointerExited
```
Android output:
```
[AutofillManager] requestHideFillUi(null): anchor = null
[AutofillManager] requestHideFillUi(null): anchor = null
[ScrollIdentify] on fling
[AutofillManager] requestHideFillUi(null): anchor = null
[ScrollIdentify] on fling
[AutofillManager] requestHideFillUi(null): anchor = null
[AutofillManager] requestHideFillUi(null): anchor = null
[ScrollIdentify] on fling
[AutofillManager] requestHideFillUi(null): anchor = null
```

**Comment by ASiNet-ASiDev** [comment] 2024-05-05 07:08
I tested my project on different versions of maui 8.0.x, the result is the same everywhere.

**Comment by Zhanglirong-Winnie** [comment] 2024-05-06 08:53
Verified this issue with Visual Studio 17.10 Preview 6.0 (8.0.21). Can repro on android platform.

**Comment by PureWeen** [comment] 2024-05-07 07:19
Duplicate of #20849

**Closed by PureWeen** 2024-05-07 07:19 UTC
Labels: t/bug, s/verified, s/triaged, s/needs-attention, area/gestures
