### ISSUE TITLE
AVCaptureSession.isMultitaskingCameraAccessEnabled Not exposed/accessible

### ISSUE THREAD

**Issue by saamerm** [dotnet/maui#14789] opened 2023-04-26 22:53 UTC
### Description

AVCaptureSession has a property .isMultitaskingCameraAccessEnabled that was introduced in iOS 16 but it’s not accessible for MAUI or Xamarin app developers 

### Steps to Reproduce

In the iOS platform specific code, Create a new AVCaptureSession instance and try to update the .isMultitaskingCameraAccessEnabled property

### Link to public reproduction project repository

There is none

### Version with bug

6.0.312

### Last version that worked well

6.0.312

### Affected platforms

iOS

### Affected platform versions

iOS 16 and up

### Did you find any workaround?

No

### Relevant log output

```shell
None
```

Apple documentation 
https://developer.apple.com/documentation/avkit/adopting_picture_in_picture_for_video_calls

**Comment by drasticactions** [comment] 2023-04-27 08:06
I believe this is not bound in the SDK, https://github.com/search?q=repo%3Axamarin%2Fxamarin-macios%20isMultitaskingCameraAccessEnabled&type=code

@rolfbjarne This would need to be bound in the SDK, correct?

**Comment by rolfbjarne** [comment] 2023-04-27 08:09
This is a duplicate of https://github.com/xamarin/xamarin-macios/issues/18155.

**Closed by rolfbjarne** 2023-04-27 08:09 UTC
Labels: t/bug, platform/iOS 🍎

**Comment by drasticactions** [comment] 2023-04-27 08:12
Awesome, thanks Rolf!
