### ISSUE TITLE
Blazor UI Freezes entirely on .NET 7

### ISSUE THREAD

**Issue by nathanjeynes** [dotnet/maui#12262] opened 2022-12-22 09:46 UTC
### Description

I'm having an issue where the entire blazor UI freezes on Windows and does not accept any mouse clicks.  

This specifically happens when holding a key on the keyboard for an excessive amount of time - and seems to happen regardless of the key.  The time varies but usually happens after 10-15 seconds.

This has only happened since .NET 7 , and when targeting .NET 6 this is not a problem.

Unfortunately there are no console warnings or other logs that help point to the cause, but it is easy to replicate as below.

This is affecting all UI components from simple buttons to 3rd party components like the syncfusion datatable, and was picked up because a user was attempting to multi select rows in a data table by holding control key.

### Steps to Reproduce

1. Create a new .NET MAUI Blazor App (using the default project)
2. Ensure the project is set to target .NET 7 
3. Run on windows
4. Go to the counter page and hold CTRL (or any key) whilst clicking the increment counter button
5. After 10-15 seconds the UI will freeze and you will no longer be able to interact with the app

Expected outcome:
The UI does not freeze and continues to respond as in .NET 6

Actual outcome
The UI freezes causing the user to have to force quit and re-launch the app

### Link to public reproduction project repository

https://github.com/nathanjeynes/ExampleUIFreezeBug

### Version with bug

7.0 (current)

### Last version that worked well

6.0 Release Candidate 2 or older

### Affected platforms

Windows

### Affected platform versions

10.0.19041.0

**Comment by NetherGranite** [comment] 2022-12-23 16:10
I have this happen when I horizontally scroll too fast/erratically (a degree a normal user would try to scroll).

A very simple repro is to make a Maui Blazor app from the template, make an element that can horizontally scroll, and then scroll left and right quickly and erratically by dragging the scrollbar back and forth or hold Shift and use the scroll wheel to scroll up and down.

You can consistently avoid the freeze by slowing scrolling using the arrows on the scrollbar. I don't know if speed is the cause, but it's the only correlation I can think of.

**Comment by javiercn** [comment] 2022-12-23 16:59
@nathanjeynes thanks for contacting us.

Does this happen on a regular webui without blazor?

**Comment by nathanjeynes** [comment] 2022-12-24 13:05
Hi @javiercn  yes this seems to be a problem with the built in MAUI WebView also.  
I added 
`<WebView Source="https://learn.microsoft.com/dotnet/maui" />`
to a new maui content page and then held the ALT key for a while after launch - the UI then became completely unresponsive as in the blazor example.

Thanks

**Comment by rusfield** [comment] 2023-01-02 10:16
I can confirm that the example repository is freezing the UI. 
Thanks for narrowing down and reproducing the issue so easily, it has really been bugging me that my program is just "randomly" freezing without me having a clue whats going on. Now I guess it is from tabbing between inputs.

Hope someone can check it out and figure out whats going on; I'm really having a blast with MAUI and Blazor :)

**Comment by KieranDevvs** [comment] 2023-01-03 11:39
This should be a priority 1 bug as its stopping customers progressing on production, there just seems to be zero urgency.

**Comment by nathanjeynes** [comment] 2023-01-03 11:45
> This should be a priority 1 bug as its stopping customers progressing on production, there just seems to be zero urgency.

Agree - we are unable to release our apps to customers as it happens so frequently, I hope this gets resolved soon.

**Comment by KieranDevvs** [comment] 2023-01-18 16:12
> Is there any solution/workaround/progress on this?
> 
> it's erratic but i could narrow it down to when the windows loses focus. it hangs.

Only way to get around it is to downgrade the runtime, but for some of us, that's not an option.

I wouldn't expect this to be looked at any time soon, Its already been an issue since November and not a single member from the WebView team has replied.

**Comment by JuanchiBruzzone** [comment] 2023-01-18 16:19
> > Is there any solution/workaround/progress on this?
> > it's erratic but i could narrow it down to when the windows loses focus. it hangs.
> 
> Only way to get around it is to downgrade the runtime to 6, but for some of us, that's not an option.
> 
> I wouldn't expect this to be looked at any time soon, Its already been an issue since November and not a single member from the WebView team has replied. Its genuinely mind boggling...

That's unfortunate, thanks for your reply.

**Comment by danroth27** [comment] 2023-01-18 17:42
> Hi @javiercn yes this seems to be a problem with the built in MAUI WebView also. I added `<WebView Source="https://learn.microsoft.com/dotnet/maui" />` to a new maui content page and then held the ALT key for a while after launch - the UI then became completely unresponsive as in the blazor example.
> 
> Thanks

This appears to be an issue with WebView2. I'm able to reproduce with a WinUI3 app and WebView2. As reported the mouse stops working but keyboard inputs still seem to work. 

This appears to a known WebView2 issue tracked by https://github.com/MicrosoftEdge/WebView2Feedback/issues/3003. Please comment and upvote as appropriate.

**Comment by Eilon** [comment] 2023-01-23 19:23
Indeed, this is a duplicate of https://github.com/MicrosoftEdge/WebView2Feedback/issues/3003.

**Closed by Eilon** 2023-01-23 19:23 UTC
Labels: t/bug, area/blazor 🕸️, area/controls 🎮, control-webview, s/needs-attention, external
