### ISSUE TITLE
[Bug] Localization with Humanizer (on Android)

### ISSUE THREAD

**Issue by codeaphex** [dotnet/maui#3992] opened 2022-01-07 16:01 UTC
### Description

This bug seems to exist since ~2018 see https://github.com/xamarin/xamarin-android/issues/2012.
I can confirm that this is still an issue on android devices (dont have an iOS device for testing), even with .NET6.

This workaround still works https://stackoverflow.com/questions/66387512/humanizer-localization-issue-in-xamarin-forms/70623711. Would still be awesome if this would be fixed, since it could affect other libraries too?

I can also confirm that this bug is not happening on Windows devices, and according to the Xamarin Bug thread it was fixed on iOS.

### Steps to Reproduce

1. Create new Maui app
2. Add Humanizer via Nuget <https://www.nuget.org/packages/Humanizer/>
3. Add a Label to display a DateTime
4. Add a converter to display the DateTime in humanized format <https://humanizr.net/#humanize-datetime>
```csharp       
public object Convert(object value, Type targetType, object parameter, CultureInfo culture)
{
    if (value is DateTime dateTimeValue)
    {
        return dateTimeValue.Humanize(culture: culture);
    }
    else return value.ToString();
}
```
5. Build and Deploy to an Android device with the language set to something other than english
6. See the humanized string still displayed in english

### Version with bug

Preview 11

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 11+

### Did you find any workaround?

See <https://stackoverflow.com/a/70623711/1835125>
![image](https://user-images.githubusercontent.com/39407721/148570528-c1ac21c3-02a5-4cf5-8670-93d90be34e36.png)

**Comment by kristinx0211** [comment] 2022-03-03 08:30
sees like  Duplicate of #4470

**Comment by rmarinho** [comment] 2022-03-23 12:52
Seems a Duplicate , please reopen if it's not

**Closed by rmarinho** 2022-03-23 12:52 UTC
Labels: t/bug, platform/android 🤖, area/localization, s/verified
