### ISSUE TITLE
[Regression] [Android] [Maps] Map locks up after adding ~200-300 locations to Polyline

### ISSUE THREAD

**Issue by mfeingol** [dotnet/maui#20532] opened 2024-02-12 21:17 UTC
### Description

Adding 200-300 locations to a Polyline causes the app to freeze. This is likely related to https://github.com/dotnet/maui/issues/20502

### Steps to Reproduce

Run the repro. Inside the app, click on the `Growing Polylines` option at the bottom of the menu.

The page will gradually render a track line from one pin to another. If the line reaches the second pin, then the test succeeded and there is no bug.

If the app hangs with unhappy GC messages, then the bug has been reproduced.

Change the `steps` value in the `GrowingPolylinePage` class to change the number of locations added to the Polyline. The app falls over at around 212 points.

### Link to public reproduction project repository

https://github.com/mfeingol/repros/tree/master/GrowingPolylineRepro

### Version with bug

8.0.6

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

14

### Did you find any workaround?

No workaround found

### Relevant log output

```shell
[monodroid-gc] 46112 outstanding GREFs. Performing a full GC!
[workingwithmaps] Explicit concurrent copying GC freed 3(31KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 8586KB/16MB, paused 263us,39us total 11.844ms
[monodroid-gc] 46113 outstanding GREFs. Performing a full GC!
[workingwithmaps] Explicit concurrent copying GC freed 3(31KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 8586KB/16MB, paused 277us,43us total 12.250ms
```
```

**Comment by drasticactions** [comment] 2024-02-13 01:45
Most likely this will be the same issue as https://github.com/dotnet/maui/issues/20502, seeing as it's a similar error message, so when that issue gets addressed if this is still happening, we can reopen it. 

Duplicate of https://github.com/dotnet/maui/issues/20502

**Closed by drasticactions** 2024-02-13 01:45 UTC
Labels: t/bug

**Comment by samhouts** [comment] 2024-05-23 23:54
Duplicate of https://github.com/dotnet/maui/issues/20502
