### ISSUE TITLE
Unable to debug on iOS 18 DEVICE, Xcode 16, lots of warnings, won't hit breakpoints

### ISSUE THREAD

**Issue by rezamohamed** [dotnet/maui#25395] opened 2024-10-19 16:03 UTC
### Description

When debugging on a physical iOS 18 device, breakpoints are not being hit. The following message is what is shown:

![Image](https://github.com/user-attachments/assets/c227ca01-5c60-4f8d-a892-5f01fd0bf13c)

"Didn't find the associated module for the breakpoint ..."

Further, on app start, seeing the following warnings on the debug console - unclear if they are related:

2024-09-19 19:50:13.086 mlaunch[11426:341414] Requested but did not find extension point with identifier Xcode.IDEDebugger.VariablesViewQuickLookProvider for extension Xcode.IDEDebugger.SpriteKitQuickLookProvider of plug-in com.apple.IDESpriteKitParticleEditor
2024-09-19 19:50:13.086 mlaunch[11426:341414] Requested but did not find extension point with identifier Xcode.IDEDebugger.VariablesViewQuickLookProvider for extension Xcode.SpriteKit.GKStateMachineQuickLookProvider of plug-in com.apple.IDESpriteKitParticleEditor
2024-09-19 19:50:13.091 mlaunch[11426:341414] Requested but did not find extension point with identifier Xcode.IDEPlaygroundsKit.PlaygroundBottomBarExecutionAdaptor for extension Xcode.IDEPlaygroundEditor.IDEPlaygroundBottomBarExecutionAdaptor of plug-in com.apple.dt.IDEPlaygroundEditorPlugin
2024-09-19 19:50:13.092 mlaunch[11426:341414] Requested but did not find extension point with identifier Xcode.DebuggerFoundation.DataSourceConnection for extension Xcode.DebuggerFoundation.watchOSSimulator.DataSourceConnectionTargetHub of plug-in com.apple.dt.IDEWatchSupportUI
2024-09-19 19:50:13.092 mlaunch[11426:341414] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.TargetSummaryEditor for extension Xcode.Xcode3ProjectSupport.TargetSummaryEditor.WatchOS.ExtensionKitAppExtension of plug-in com.apple.dt.IDEWatchSupportUI
2024-09-19 19:50:13.092 mlaunch[11426:341414] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.TargetSummaryEditor for extension Xcode.Xcode3ProjectSupport.TargetSummaryEditor.WatchOS.AppExtension of plug-in com.apple.dt.IDEWatchSupportUI
2024-09-19 19:50:13.092 mlaunch[11426:341414] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.TargetSummaryEditor for extension Xcode.Xcode3ProjectSupport.TargetSummaryEditor.WatchOS.WatchApplication of plug-in com.apple.dt.IDEWatchSupportUI
2024-09-19 19:50:13.092 mlaunch[11426:341414] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.TargetSummaryEditor for extension Xcode.Xcode3ProjectSupport.TargetSummaryEditor.WatchOS.IntentsService-AppExtension of plug-in com.apple.dt.IDEWatchSupportUI
2024-09-19 19:50:13.092 mlaunch[11426:341414] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.InfoEditorSlice for extension Xcode.Xcode3ProjectSupport.InfoEditorSlice.WatchOS.BundleInfo of plug-in com.apple.dt.IDEWatchSupportUI
2024-09-19 19:50:13.092 mlaunch[11426:341414] Requested but did not find extension point with identifier Xcode.DebuggerFoundation.ViewDescriber for extension Xcode.DebuggerFoundation.watchOS.ViewDescriber of plug-in com.apple.dt.IDEWatchSupportUI
2024-09-19 19:50:13.092 mlaunch[11426:341414] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.TargetSummaryEditor for extension Xcode.Xcode3ProjectSupport.TargetSummaryEditor.WatchOS.WatchKit2-AppExtension of plug-in com.apple.dt.IDEWatchSupportUI
2024-09-19 19:50:13.092 mlaunch[11426:341414] Requested but did not find extension point with identifier Xcode.IDEiPhoneSupport.TargetEditor for extension Xcode.IDEiPhoneSupport.TargetEditor.WatchOS.Application of plug-in com.apple.dt.IDEWatchSupportUI
2024-09-19 19:50:13.092 mlaunch[11426:341414] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.InfoEditorType for extension Xcode.Xcode3ProjectSupport.InfoEditorType.WatchOS.Bundle of plug-in com.apple.dt.IDEWatchSupportUI
2024-09-19 19:50:13.092 mlaunch[11426:341414] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.TargetSummaryEditor for extension Xcode.Xcode3ProjectSupport.TargetSummaryEditor.WatchOS.Tool of plug-in com.apple.dt.IDEWatchSupportUI
2024-09-19 19:50:13.092 mlaunch[11426:341414] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.TargetSummaryEditor for extension Xcode.Xcode3ProjectSupport.TargetSummaryEditor.WatchOS.Application of plug-in com.apple.dt.IDEWatchSupportUI
2024-09-19 19:50:13.092 mlaunch[11426:341414] Requested but did not find extension point with identifier Xcode.DebuggerFoundation.ViewDescriber for extension Xcode.DebuggerFoundation.watchOSSimulator.ViewDescriber of plug-in com.apple.dt.IDEWatchSupportUI
2024-09-19 19:50:13.092 mlaunch[11426:341414] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.TargetSummaryEditor for extension Xcode.Xcode3ProjectSupport.TargetSummaryEditor.WatchOS.Framework of plug-in com.apple.dt.IDEWatchSupportUI
2024-09-19 19:50:13.092 mlaunch[11426:341414] Requested but did not find extension point with identifier Xcode.Xcode3UI.Xcode3SupportedDestinations for extension IDEWatchSupportUI:IDEWatchSupportUI.plugindata/plug-in[1]/extension[20] of plug-in com.apple.dt.IDEWatchSupportUI
2024-09-19 19:50:13.092 mlaunch[11426:341414] Requested but did not find extension point with identifier Xcode.DebuggerFoundation.DataSourceConnection for extension Xcode.DebuggerFoundation.watchOS.DataSourceConnectionTargetHub of plug-in com.apple.dt.IDEWatchSupportUI
2024-09-19 19:50:13.092 mlaunch[11426:341414] Requested but did not find extension point with identifier Xcode.IDEiOSSupportCore.iOSDeviceLocatorMapping for extension Xcode.IDEiOSSupportCore.iOSDeviceLocatorMapping.driverkit of plug-in com.apple.dt.IDEDriverKitSupportCore
2024-09-19 19:50:13.092 mlaunch[11426:341414] Requested but did not find extension point with identifier Xcode.Xcode3UI.Xcode3SupportedDestinations for extension IDEOSXSupportUI:IDEOSXSupportUI.plugindata/plug-in[1]/extension[5] of plug-in com.apple.dt.IDE.IDEOSXSupportUI
2024-09-19 19:50:13.093 mlaunch[11426:341414] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.TargetSummaryEditor for extension Xcode.Xcode3ProjectSupport.TargetSummaryEditor.XROS.Framework of plug-in com.apple.dt.IDE.IDESupportUI-xrOS
2024-09-19 19:50:13.093 mlaunch[11426:341414] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.TargetSummaryEditor for extension Xcode.Xcode3ProjectSupport.TargetSummaryEditor.XROS.DynamicLibrary of plug-in com.apple.dt.IDE.IDESupportUI-xrOS
2024-09-19 19:50:13.093 mlaunch[11426:341414] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.TargetSummaryEditor for extension Xcode.Xcode3ProjectSupport.TargetSummaryEditor.XROS.ExtensionKitAppExtension of plug-in com.apple.dt.IDE.IDESupportUI-xrOS
2024-09-19 19:50:13.093 mlaunch[11426:341414] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.TargetSummaryEditor for extension Xcode.Xcode3ProjectSupport.TargetSummaryEditor.XROS.XPC of plug-in com.apple.dt.IDE.IDESupportUI-xrOS
2024-09-19 19:50:13.093 mlaunch[11426:341414] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.InfoEditorType for extension Xcode.Xcode3ProjectSupport.InfoEditorType.Reality.Application of plug-in com.apple.dt.IDE.IDESupportUI-xrOS
2024-09-19 19:50:13.093 mlaunch[11426:341414] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.TargetSummaryEditor for extension Xcode.Xcode3ProjectSupport.TargetSummaryEditor.XROS.Bundle of plug-in com.apple.dt.IDE.IDESupportUI-xrOS
2024-09-19 19:50:13.093 mlaunch[11426:341414] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.InfoEditorType for extension Xcode.Xcode3ProjectSupport.InfoEditorType.Reality.Framework of plug-in com.apple.dt.IDE.IDESupportUI-xrOS
2024-09-19 19:50:13.093 mlaunch[11426:341414] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.TargetSummaryEditor for extension Xcode.Xcode3ProjectSupport.TargetSummaryEditor.XROS.Application of plug-in com.apple.dt.IDE.IDESupportUI-xrOS
2024-09-19 19:50:13.093 mlaunch[11426:341414] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.TargetSummaryEditor for extension Xcode.Xcode3ProjectSupport.TargetSummaryEditor.XROS.Tool of plug-in com.apple.dt.IDE.IDESupportUI-xrOS
2024-09-19 19:50:13.093 mlaunch[11426:341414] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.InfoEditorType for extension Xcode.Xcode3ProjectSupport.InfoEditorType.Reality.Bundle of plug-in com.apple.dt.IDE.IDESupportUI-xrOS
2024-09-19 19:50:13.093 mlaunch[11426:341414] Requested but did not find extension point with identifier Xcode.Xcode3UI.Xcode3SupportedDestinations for extension IDESupportUI_xrOS:IDESupportUI_xrOS.plugindata/plug-in[1]/extension[13] of plug-in com.apple.dt.IDE.IDESupportUI-xrOS
2024-09-19 19:50:13.093 mlaunch[11426:341414] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.TargetSummaryEditor for extension Xcode.Xcode3ProjectSupport.TargetSummaryEditor.XROS.AppExtension of plug-in com.apple.dt.IDE.IDESupportUI-xrOS
2024-09-19 19:50:13.093 mlaunch[11426:341414] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.InfoEditorSlice for extension Xcode.Xcode3ProjectSupport.InfoEditorSlice.appletvos.BundleTargetInfo of plug-in com.apple.dt.IDEAppleTVSupportUI
2024-09-19 19:50:13.093 mlaunch[11426:341414] Requested but did not find extension point with identifier Xcode.DebuggerFoundation.DataSourceConnection for extension Xcode.DebuggerFoundation.tvOS.DataSourceConnectionTargetHub of plug-in com.apple.dt.IDEAppleTVSupportUI
2024-09-19 19:50:13.093 mlaunch[11426:341414] Requested but did not find extension point with identifier Xcode.DebuggerFoundation.ViewDescriber for extension Xcode.DebuggerFoundation.ATV.ViewDescriber of plug-in com.apple.dt.IDEAppleTVSupportUI
2024-09-19 19:50:13.093 mlaunch[11426:341414] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.InfoEditorType for extension Xcode.Xcode3ProjectSupport.InfoEditorType.appletvos.Bundle of plug-in com.apple.dt.IDEAppleTVSupportUI
2024-09-19 19:50:13.093 mlaunch[11426:341414] Requested but did not find extension point with identifier Xcode.DebuggerFoundation.DataSourceConnection for extension Xcode.DebuggerFoundation.tvOSSimulator.DataSourceConnectionTargetHub of plug-in com.apple.dt.IDEAppleTVSupportUI
2024-09-19 19:50:13.093 mlaunch[11426:341414] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.TargetSummaryEditor for extension Xcode.Xcode3ProjectSupport.TargetSummaryEditor.IDEAppleTVSupportUI.Application of plug-in com.apple.dt.IDEAppleTVSupportUI
2024-09-19 19:50:13.093 mlaunch[11426:341414] Requested but did not find extension point with identifier Xcode.Xcode3UI.Xcode3SupportedDestinations for extension IDEAppleTVSupportUI:IDEAppleTVSupportUI.plugindata/plug-in[1]/extension[16] of plug-in com.apple.dt.IDEAppleTVSupportUI
2024-09-19 19:50:13.093 mlaunch[11426:341414] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.TargetSummaryEditor for extension Xcode.Xcode3ProjectSupport.TargetSummaryEditor.IDEAppleTVSupportUI.XPC of plug-in com.apple.dt.IDEAppleTVSupportUI
2024-09-19 19:50:13.093 mlaunch[11426:341414] Requested but did not find extension point with identifier Xcode.DebuggerFoundation.DeviceIconProvider for extension Xcode.DebuggerFoundation.DeviceIconProvider.AppleTV of plug-in com.apple.dt.IDEAppleTVSupportUI
2024-09-19 19:50:13.093 mlaunch[11426:341414] Requested but did not find extension point with identifier Xcode.DebuggerFoundation.ViewDescriber for extension Xcode.DebuggerFoundation.ATVSimulator.ViewDescriber of plug-in com.apple.dt.IDEAppleTVSupportUI
2024-09-19 19:50:13.093 mlaunch[11426:341414] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.TargetSummaryEditor for extension Xcode.Xcode3ProjectSupport.TargetSummaryEditor.IDEAppleTVSupportUI.ExtensionKitAppExtension of plug-in com.apple.dt.IDEAppleTVSupportUI
2024-09-19 19:50:13.093 mlaunch[11426:341414] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.TargetSummaryEditor for extension Xcode.Xcode3ProjectSupport.TargetSummaryEditor.IDEAppleTVSupportUI.AppExtension of plug-in com.apple.dt.IDEAppleTVSupportUI
2024-09-19 19:50:13.093 mlaunch[11426:341414] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.TargetSummaryEditor for extension Xcode.Xcode3ProjectSupport.TargetSummaryEditor.IDEAppleTVSupportUIFramework of plug-in com.apple.dt.IDEAppleTVSupportUI

### Steps to Reproduce

1. Create a new Maui app
2. Set a breakpoint anywhere
3. Debug on **physical iPhone** with iOS 18

### Version with bug

8.0.82 SR8.2

### Is this a regression from previous behavior?

No, this is something new

### Affected platforms

iOS

### Affected platform versions

iOS 18, Xcode 16

**Comment by rezamohamed** [comment] 2024-10-19 16:09
this is a similar thread of this issue https://github.com/dotnet/maui/issues/25228

**Comment by PureWeen** [comment] 2024-10-20 14:58
Duplicate of #25228

**Closed by PureWeen** 2024-10-20 14:58 UTC
Labels: t/bug

**Comment by PureWeen** [comment] 2024-10-20 15:00
https://github.com/xamarin/xamarin-macios/issues/21479
