### ISSUE TITLE
bad grid layout

### ISSUE THREAD

**Issue by ialbert-AUT** [dotnet/maui#5343] opened 2022-03-16 16:55 UTC
### Description

I have this markup:

				new Grid()
				{
					ColumnDefinitions = Columns.Define(GridLength.Star, GridLength.Auto),
					RowDefinitions = Rows.Define(30),

					Children =
					{
						new Label() {Text = "hello" }.Column(0),
						new Image() {Source="drink.png"}.Column(1)
					}
				}

and I get this layout:
![image](https://user-images.githubusercontent.com/61751571/158643587-c77b100f-caf1-4b23-b9e0-c6dabd24be89.png)

I expect the image to be at the right-hand side.
Seems that the column size calculation happens with original size of the image.

### Steps to Reproduce

create a maui app and add a simple grid with an image 128x128:

new Grid()
				{
					ColumnDefinitions = Columns.Define(GridLength.Star, GridLength.Auto),
					RowDefinitions = Rows.Define(30),

					Children =
					{
						new Label() {Text = "hello" }.Column(0),
						new Image() {Source="drink.png"}.Column(1)
					}
				},

### Version with bug

Preview 13 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows

### Affected platform versions

Android api 31, Windows 11

**Comment by jfversluis** [comment] 2022-03-17 10:21
Duplicate of #5344 or probably at least related to, so let's centralize there

**Closed by jfversluis** 2022-03-17 10:21 UTC
Labels: t/bug, area/layout 🔲, s/needs-verification
