### ISSUE TITLE
Android compilation broken again

### ISSUE THREAD

**Issue by arivoir** [dotnet/maui#10148] opened 2022-09-15 16:53 UTC
### Description

Android projects referencing a lib don't compile in dotnet 6.0.401.

### Steps to Reproduce

Create an empty Android Application
Create a Android Class Lib project
Add a reference to the project
Press F5

Error	XAPRAS7023	System.IO.DirectoryNotFoundException: Could not find a part of the path

### Link to public reproduction project repository

No link

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

6.0.400

### Affected platforms

Android

### Affected platform versions

Version 17.4.0 Preview 2.0

### Did you find any workaround?

No

### Relevant log output

```shell
Severity	Code	Description	Project	File	Line	Suppression State
Error	XAPRAS7023	System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\arivo\source\repos\AndroidApp10\AndroidLib1\bin\Debug\net6.0-android\android-arm\AndroidLib1.dll'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Xamarin.Android.Tasks.MonoAndroidHelper.HasMonoAndroidReference(ITaskItem assembly)
   at Xamarin.Android.Tasks.ProcessAssemblies.SetMetadataForAssemblies(List`1 output, Dictionary`2 symbols)
   at Xamarin.Android.Tasks.ProcessAssemblies.RunTask()
   at Microsoft.Android.Build.Tasks.AndroidTask.Execute() in /Users/runner/work/1/s/xamarin-android/external/xamarin-android-tools/src/Microsoft.Android.Build.BaseTasks/AndroidTask.cs:line 17	AndroidApp10	C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.448\targets\Microsoft.Android.Sdk.AssemblyResolution.targets	98
```

**Comment by arivoir** [comment] 2022-09-15 17:29
Attached the sample just in case it gets useful. Anyway it is easily reproducible in vs
[AndroidApp10.zip](https://github.com/dotnet/maui/files/9577639/AndroidApp10.zip)

**Comment by hartez** [comment] 2022-09-15 18:08
Duplicate of #10150

**Closed by hartez** 2022-09-15 18:08 UTC
Labels: t/bug, platform/android 🤖

**Comment by PureWeen** [comment] 2022-09-15 22:04
@arivoir if you add
```XAML
<IsRidAgnostic Condition="'$(TargetPlatformIdentifier)' == 'android' and '$(OutputType)' == 'Library'">true</IsRidAgnostic>
```

to your csproj file does that fix?
