### ISSUE TITLE
Transporter validation failing on .ipa file. 

### ISSUE THREAD

**Issue by anupam99** [dotnet/maui#9133] opened 2022-08-02 10:38 UTC
### Description

I got past the .ipa creation (Thanks to Geralds video and MS docs), but now i am stuck at the transporter validations trying to upload to appstoreconnect.
Any ideas how to get past this?
(Seems like some stuff, i need to exclude out of .ipa )

Asset validation failed (90171)
Invalid Bundle Structure - The binary file 'RapidsApp.app/libmonosgen-2.0.dylib' is not permitted. Your app can’t contain standalone executables or libraries, other than a valid CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide at https://developer.apple.com/go/?id=bundle-structure for information on the iOS app bundle structure. (ID: 22a21e94-a2ee-4e72-a1d8-51f571effafc)

Asset validation failed (90171)
Invalid Bundle Structure - The binary file 'RapidsApp.app/libSystem.Native.dylib' is not permitted. Your app can’t contain standalone executables or libraries, other than a valid CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide at https://developer.apple.com/go/?id=bundle-structure for information on the iOS app bundle structure. (ID: cca3e695-cab8-4081-aa65-d80b9f8b930a)

Asset validation failed (90171)
Invalid Bundle Structure - The binary file 'RapidsApp.app/libSystem.IO.Compression.Native.dylib' is not permitted. Your app can’t contain standalone executables or libraries, other than a valid CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide at https://developer.apple.com/go/?id=bundle-structure for information on the iOS app bundle structure. (ID: ae554411-fcec-4a26-a025-ac0aa99b1460)

Asset validation failed (90171)
Invalid Bundle Structure - The binary file 'RapidsApp.app/libmono-component-debugger.dylib' is not permitted. Your app can’t contain standalone executables or libraries, other than a valid CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide at https://developer.apple.com/go/?id=bundle-structure for information on the iOS app bundle structure. (ID: 69418f04-3b24-4384-92cb-43d155814bb3)

Asset validation failed (90171)
Invalid Bundle Structure - The binary file 'RapidsApp.app/libSystem.Net.Security.Native.dylib' is not permitted. Your app can’t contain standalone executables or libraries, other than a valid CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide at https://developer.apple.com/go/?id=bundle-structure for information on the iOS app bundle structure. (ID: 4db1ff91-1f3d-4181-b092-bc1272f28de2)

Asset validation failed (90171)
Invalid Bundle Structure - The binary file 'RapidsApp.app/libmono-component-hot_reload.dylib' is not permitted. Your app can’t contain standalone executables or libraries, other than a valid CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide at https://developer.apple.com/go/?id=bundle-structure for information on the iOS app bundle structure. (ID: e3783e98-9e92-4515-894f-44d2c438440a)

Asset validation failed (90171)
Invalid Bundle Structure - The binary file 'RapidsApp.app/libxamarin-dotnet.dylib' is not permitted. Your app can’t contain standalone executables or libraries, other than a valid CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide at https://developer.apple.com/go/?id=bundle-structure for information on the iOS app bundle structure. (ID: 74972d82-d13f-414b-8e80-3fc463e780d3)

Asset validation failed (90171)
Invalid Bundle Structure - The binary file 'RapidsApp.app/libSystem.Security.Cryptography.Native.Apple.dylib' is not permitted. Your app can’t contain standalone executables or libraries, other than a valid CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide at https://developer.apple.com/go/?id=bundle-structure for information on the iOS app bundle structure. (ID: 3296130b-2b56-4f0d-9d5d-907b5d8ef8cb)

Asset validation failed (90171)
Invalid Bundle Structure - The binary file 'RapidsApp.app/libmono-component-diagnostics_tracing.dylib' is not permitted. Your app can’t contain standalone executables or libraries, other than a valid CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide at https://developer.apple.com/go/?id=bundle-structure for information on the iOS app bundle structure. (ID: 3ab1d3a0-e6d8-4eac-ac48-80ec6f3db79b)

I am using VS2022 17.3.0 Preview 4.0 

### Steps to Reproduce

1. Create .ipa file using paired mac host.
2. Use transporter app on mac to upload the .ipa file.
3. transporter lists issues as above and fails to upload.

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

IOS

**Comment by jfversluis** [comment] 2022-08-02 11:58
Thanks for the kind words! This is a duplicate issue though, please add your details and follow progress there.

**Comment by jfversluis** [comment] 2022-08-02 11:58
Duplicate of #8701

**Closed by jfversluis** 2022-08-02 11:58 UTC
Labels: t/bug, s/needs-verification
