### ISSUE TITLE
.NET MAUI SplashScreen PNG Resizing Incorrectly to Circular Shape

### ISSUE THREAD

**Issue by zubair1995** [dotnet/maui#25500] opened 2024-10-24 13:07 UTC
### Description

`	<MauiSplashScreen Include="Resources\splashlogo.png" Resize="True" BaseSize="210,260" Color="#FFFFFF"/>`

I'm encountering an issue with the splash screen in a .NET MAUI application. When I provide a PNG file for the splash screen, it gets resized automatically into a circular shape, which is not the intended behavior. I want the splash screen to maintain the original aspect ratio and only increase height and width , but .NET MAUI seems to be enforcing a circular crop or resize.

### Steps to Reproduce

	<MauiSplashScreen Include="Resources\splashlogo.png" Resize="True" BaseSize="210,260" Color="#FFFFFF"/>

### Version with bug

8.0.82 SR8.2

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 13

### Did you find any workaround?

Not yet

**Comment by bcaceiro** [comment] 2024-10-24 13:45
I am also seeing this, when using .svgs

**Comment by JonathanStefanov** [comment] 2024-10-25 09:16
This is the expected behavior. A splash screen is composed of a circular image and a background. Please read the documentation for more details.


![Android SplashScreen](https://github.com/user-attachments/assets/e2fc33c7-053b-45e9-92c4-40aa647c4af0)

[Android Docs](https://developer.android.com/develop/ui/views/launch/splash-screen )
[MAUI Docs](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/images/splashscreen?view=net-maui-8.0&tabs=android)

**Comment by jfversluis** [comment] 2024-10-29 10:21
Duplicate of #20605

**Closed by jfversluis** 2024-10-29 10:21 UTC
Labels: t/bug, s/triaged, s/needs-attention
