### ISSUE TITLE
iOS - Shell - SetTabBarIsVisible does not resize the page to take up the space left by the tab bar

### ISSUE THREAD

**Issue by mattdreiss** [dotnet/maui#21135] opened 2024-03-11 15:30 UTC
### Description

On iOS, hiding the Shell tab bar does not resize the page to take up the space left by the tab bar. I noticed that this worked as intended on Xamarin Forms. I am in the process of upgrading an app from Xamarin Forms to MAUI. I have not tested this in previous versions of MAUI.

Here is a video of the bug on iOS

https://github.com/dotnet/maui/assets/18075909/4a856063-bc39-4dd7-a46a-972e1c0035e9

It works as expected on Android

https://github.com/dotnet/maui/assets/18075909/aac582bb-6ca8-47f7-aa44-da52c6fcf5d5

If the action also toggles the visibility of the NavBar, then the TabBar space will be reclaimed as expected on iOS

https://github.com/dotnet/maui/assets/18075909/17634380-41d8-42e1-9846-ac6ae001ced0

Here is a screenshot of my dotnet workloads
![Screenshot 2024-03-11 at 10 27 49 AM](https://github.com/dotnet/maui/assets/18075909/128b3ce8-946c-4dfb-bde8-14e28775563e)

### Steps to Reproduce

I added a basic test app that has a button that will toggle the visibility of the tab bar.
Tap the button and observe that the bug on iOS but works on Android.

### Link to public reproduction project repository

https://github.com/mattdreiss/maui-tab-bar-bug

### Version with bug

8.0.6 SR1

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Did you find any workaround?

I have not found a workaround yet.

**Comment by PureWeen** [comment] 2024-03-11 15:43
Can you test with the latest nightly build? 
https://github.com/dotnet/maui/wiki/Nightly-Builds

**Comment by mattdreiss** [comment] 2024-03-11 16:18
@PureWeen Thank you for your quick response! I updated the repo to use the nightly build and I still see the issue.

**Comment by PureWeen** [comment] 2024-03-11 19:22
Duplicate of #17390

**Closed by PureWeen** 2024-03-11 19:22 UTC
Labels: t/bug, platform/iOS 🍎, migration-compatibility
