### ISSUE TITLE
MAUI - binding native iOS Swift library

### ISSUE THREAD

**Issue by Kebechet** [dotnet/maui#14982] opened 2023-05-08 18:32 UTC
### Description

I have .NET MAUI app where I want to use 3rd party payment processing library RevenueCat. There are 2 Xamarin bindings already for this lib:

android: https://github.com/thisisthekap/Xamarin.RevenueCat.Android
ios: https://github.com/thisisthekap/Xamarin.RevenueCat.iOS
The Android one when referenced to .NET MAUI project works correctly, but the iOS one seems not to be supported by MAUI.

So I have decided to port it from original iOS Binding library (Xamarin) to iOS binding library on .NET7.

I have copied all binding-related files as well as native .framework folder to the MAUI
I have adjusted attributes that werent supported by MAUI e.g. Watch, Mac, iOS or AutoGeneratedName  -> [commit](https://github.com/Kebechet/Maui.RevenueCat.iOS/commit/5796f045bf6d8c591f8c5bc2afbb9535abd97bda)
I have added necessary things to .csproj
and I was able to build it on my connected MAC M1 mini.

----------------

But the output Nuget package was only a few KBs and the original nuget was [~7MB](https://github.com/thisisthekap/Xamarin.RevenueCat.iOS/releases/tag/release-bindings-v4.9.0.2). After closer look I found out that my MAUI nuget doesnt contain the native .framework resource and I have no idea why.

I suspect there is either something wrong with the basic iOS binding project template or with the MAUI itself.

### Steps to Reproduce

- Build the project
- Pack it to nuget
- the final nuget wont have `.framework` included in it and it's size is just around 31kb

### Link to public reproduction project repository

https://github.com/Kebechet/Maui.RevenueCat.iOS

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS all

### Did you find any workaround?

nope

**Comment by drasticactions** [comment] 2023-05-10 23:06
I think this issue would be more appropriate in [xamairn/xamarin-macios](https://github.com/xamarin/xamarin-macios). You're building a NuGet package of a binding, and that tooling would belong there, not in this repo.

That said, I compiled your project on my Mac with

`dotnet build --configuration Release`
`dotnet pack --configuration Release` 

and it built the nuget with the framework, at 7 MBs.

If you're trying to build and package this on a Windows computer through XMA, that won't work, you need to build it on your Mac.

**Comment by Kebechet** [comment] 2023-05-11 22:29
I have remotely connected Mac M1 mini and I build all ios-related stuff through that, but in this case it simply didnt build the ~7MB nuget like when I directly did it from Mac. So I think there is some kind of bug in building iOS binding project through remotely connected Mac.

**Comment by drasticactions** [comment] 2023-05-12 01:28
@Kebechet As far as I'm aware, this is not a bug, it's not supported. As I said, you would need to build this on your Mac in order to build the binding correctly, it is not supported on Windows. Likewise, this issue would belong under [xamarin-macios](https://github.com/xamarin/xamarin-macios) repo, as they maintain that tooling.

Since it did work for you under Mac, I am closing this issue. If you need more help, I would go to the xamarin-macios repo.

**Closed by drasticactions** 2023-05-12 01:28 UTC
Labels: t/bug, s/needs-attention, area/platform
