### ISSUE TITLE
.net blazor maui Microsoft.JSInterop.JSException "Byte array index ... does not exist" using DotNetStreamReference

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#7865] opened 2022-06-08 18:17 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/net-blazor-maui-MicrosoftJSInteropJSE/10062879)._

---
[severity:I'm unable to use this version]
An application that uses DotNetStreamReference to transfer image data to the webview fails periodically with JSException. It looks like the marshal/unmarshall fails in the blazor.webview.js code.
The moment of failure is random in time, does not happen as specific moment, but always eventually.
Attaching full example code that triggers it.

---
#### Feedback Bot on 6/6/2022, 08:00 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by TanayParikh** [comment] 2022-06-08 18:18
Can you please provide a minimal, public, github repository which reproduces this issue?

**Comment by Eilon** [comment] 2022-06-08 18:19
@TanayParikh the person who opened this issue isn't notified here because it's from vsfeedback, so this bug will just get auto-closed in a week no matter what.

**Comment by TanayParikh** [comment] 2022-06-08 21:15
Removed the s/needs lables to prevent auto-close. I'm going to reach out to them on the original issue for a github repro.

**Comment by michal-puczynski** [comment] 2022-06-09 07:24
see here:
https://github.com/michal-puczynski/repro_dotnet_maui_issue_7865

**Comment by TanayParikh** [comment] 2022-06-29 22:12
Hey @michal-puczynski, I took a look, and haven't been able to repro the issue. I've had this running for a few minutes now. When does it eventually end up failing for you?


https://user-images.githubusercontent.com/14852843/176554519-24bbd759-5b6f-48be-b718-267e985f7b01.mov

**Comment by michal-puczynski** [comment] 2022-07-04 09:51
Hi,
Well, on my side problem still exists. When you keep observing the application, first I notice is that one of "displays" stops refreshing, while in the debug output I see message:
`Exception thrown: 'Microsoft.JSInterop.JSException' in System.Private.CoreLib.dll`
So, I stop the application and added Microsoft.JSInterop.JSException to the exception list with option to stop on throw.
Then, once I run the application again, I get:
![image](https://user-images.githubusercontent.com/107173344/177130103-1d9a75bb-7dd2-4b6f-89fb-f7f507c3ca5f.png)

**Comment by TanayParikh** [comment] 2022-07-07 18:03
Hey @michal-puczynski, after further consideration @javiercn pointed out [this call](https://github.com/michal-puczynski/repro_dotnet_maui_issue_7865/blob/f556f7e712955fb00e65157a27b50c81760c6d2b/ImagePeriodicRefresh/ImagePeriodicRefresh/Components/Display.razor#L62) should actually be made using the Blazor synchronization context (using `InvokeAsync`). However, we should be able to add an exception detecting this type of behavior (calling JSInterop from the incorrect thread), will look into that.

**Closed by TanayParikh** 2022-07-07 18:03 UTC
Labels: t/bug, area/blazor 🕸️, feature-blazor-maui, discussed
