### ISSUE TITLE
Flyout shown for a moment when interacting with a backbutton in Android Shell

### ISSUE THREAD

**Issue by Cr15Denis** [dotnet/maui#22649] opened 2024-05-25 16:28 UTC
### Description

Visual studio communi5y 2022 17.10.0
.Net Maui 8
Android
Shell

When you go back from Page2 you can see that the Mainpage flyout icon is displayed for a moment.

Flyout is disabled in the AppShell.
 Shell.FlyoutBehavior="Disabled"

This behavior occurs when the Mainpage has a defined title.

1. The bug originates from the back button.
![4](https://github.com/dotnet/maui/assets/70722700/5871a148-8a0b-4b7f-a262-2007ace75743)

2. When you return to the Mainpage you see the flyout icon, meaning the flyout is deactivated.
![1](https://github.com/dotnet/maui/assets/70722700/48f76690-822e-4b4b-a6cc-f4c2ef408a52)

3. Here I return to 100% Mainpage view and you can see the flyout icon for a thousandths of seconds it is displayed.

![2](https://github.com/dotnet/maui/assets/70722700/552a5baf-59ed-449a-b8ba-650c157835f8)

4. And after a few thousandths of a second the flyout icon disappears, which means that the flyout in the shell is disabled.

![3](https://github.com/dotnet/maui/assets/70722700/aee2b4e2-33cf-4ef3-bee9-86a88c5bca00)

5. I am attaching a video with 0.5x speed so you can observe the behavior.

https://github.com/dotnet/maui/assets/70722700/876c11ff-169a-4610-ba3c-8a28c7742f57

### Link to public reproduction project repository

https://github.com/Cr15Denis/BugFlyoutBackbutton

### Version with bug

8.0.40 SR5

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

Android

**Comment by kubaflo** [comment] 2024-05-25 18:54
https://github.com/dotnet/maui/pull/21455

**Comment by PureWeen** [comment] 2024-05-30 16:14
Duplicate of #18867

**Closed by PureWeen** 2024-05-30 16:14 UTC
Labels: t/bug, platform/android 🤖, area-controls-flyout
