### ISSUE TITLE
Disable MenuFlyoutItem

### ISSUE THREAD

**Issue by CCB67** [dotnet/maui#15896] opened 2023-06-28 05:43 UTC
### Description

I am writing a maui desktop app for Mac and Windows.
I have a MenuBarItem with  MenuFlyoutItem for the main menu.
I need to disable single MenuFlyoutItems if they are not accesible at the moment. 
And enable them again when the functionality behind is accesible.

I have a context menu too in my app.
FlyoutBase.ContextFlyout
There I need the same enable and disable of single MenuFlyoutItem

### Public API Changes

MenuFlyoutItem

### Intended Use-Case

I think this is  a very common and standard use case for desktop apps.

**Comment by Redth** [comment] 2023-07-07 18:06
Duplicate of #9583

**Closed by Redth** 2023-07-07 18:06 UTC
Labels: proposal/open, area/desktop 🖥️
