### ISSUE TITLE
Opening a second window results in fatal errors

### ISSUE THREAD

**Issue by stevepeeters** [dotnet/maui#11452] opened 2022-11-17 16:31 UTC
### Description

After a second window has been opened and closed in an application, the application crashes when displaying an alert.

### Steps to Reproduce

The app shows 2 buttons. Button 1 opens a new window, button 2 shows an alert.
* Case 1: open app, press open window and close it (multiple times) > no issue
* Case 2: open app, press show alert multiple times > no issue
* Case 3: open app, press open window and close it, subsequently show alert => App crashes

### Link to public reproduction project repository

https://github.com/stevepeeters/MultiWindowBug

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Windows 10 and 11

**Comment by PureWeen** [comment] 2022-11-17 19:09
Duplicate of #10026

**Closed by PureWeen** 2022-11-17 19:09 UTC
Labels: t/bug, platform/windows 🪟, area/desktop 🖥️

**Comment by stevepeeters** [comment] 2022-11-17 20:39
@PureWeen : I'm not entirely sure this is the same issue. In my case I close the second window so only the original one is open upon calling the alert method. Also, in my case, the app crashes.

**Comment by PureWeen** [comment] 2022-11-17 23:07
@stevepeeters It's the same root cause of a global subscription sticking around. 

If you leave all the windows open, then you see an alert in every window
if you close one window then it tries to display an alert in the closed window and crashes
