### ISSUE TITLE
Entry is not unfocus when hide or close softkeyboard

### ISSUE THREAD

**Issue by xyeie** [dotnet/maui#16897] opened 2023-08-21 17:55 UTC
### Description

Entry is not unfocus when hide or close softkeyboard.I need to make the editor lose focus when manually closing the keyboard. But no suitable method was found. I don't know if this is my method error or if there is a bug in it

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

7.0.92

### Affected platforms

Android

**Comment by PureWeen** [comment] 2023-08-21 19:18
> I need to make the editor lose focus when manually closing the keyboard.

Why? What should gain focus after the editor has lost focus?

**Comment by xyeie** [comment] 2023-08-22 17:15
> > I need to make the editor lose focus when manually closing the keyboard.
> 
> Why? What should gain focus after the editor has lost focus?

Usually, when click entry Control, the softkeyboard will automatically pop up, and if you close the softkeyboard, the unfocused event of entry should be triggered, but it is not work

**Comment by SarthakB26** [comment] 2023-08-23 05:54
yes somtimes we do required unfocusevent to fire when keyboard closed or picker popup close through cancel button.So that we can perform some validation or some other logic. This used to work just fine in Xamarin forms.
I don't see any complain about old behaviour then why these changes

**Comment by PureWeen** [comment] 2023-08-25 14:34
> > > I need to make the editor lose focus when manually closing the keyboard.
> > 
> > 
> > Why? What should gain focus after the editor has lost focus?
> 
> Usually, when click entry Control, the softkeyboard will automatically pop up, and if you close the softkeyboard, the unfocused event of entry should be triggered, but it is not work

Can you set the ReturnType="done"

> yes somtimes we do required unfocusevent to fire when keyboard closed or picker popup close through cancel button.So that we can perform some validation or some other logic. This used to work just fine in Xamarin forms. I don't see any complain about old behaviour then why these changes.
> 
> I am seeing at least one person opening new issue about this every month from past year.

The implementation in XF made every single app in XF completely broken from an accessibility standpoint. The way XF achieved this was by giving focus to the Page layout which makes all apps impossible to use if you have any accessibility features on. Using focus to indicate "done" is kind of a hack. If setting the ReturnType doesn't quite work, then we probably need to add some additional APIs that are more intentional for the desired behavior.

**Comment by XamlTest** [comment] 2023-08-29 05:48
Verified this on Visual Studio Enterprise 17.8.0 Preview 1.0. Repro on Android 13.0-API33 .NET 8, not repo on Windows 11 and iOS 16.4 with below Project:
[16897.zip](https://github.com/dotnet/maui/files/12460711/16897.zip)

**Comment by xyeie** [comment] 2023-08-31 16:09
Sometimes, in Android or iOS, when you click on an Entry or Editor, the soft keyboard pops up automatically. However, if the user manually closes the keyboard, we need to execute some logic based on this event, such as updating the placeholder content and so on.
     According to my understanding, the Unfocused event should be triggered when the keyboard is manually closed so that the App knows what happened and can decide what to do next. However, the current implementation is that neither Entry nor Editor supports this scenario. If this is a bug, please fix it as soon as possible because our project is stuck here. If this is not a bug, how can I subscribe to the events of showing and hiding the soft keyboard?

**Comment by PureWeen** [comment] 2023-11-06 18:57
Duplicate of #16357

We can't have unfocusing an entry be a side effect of closing the SoftKeyboard for various a11y reasons, but we do need to supply an API that will let users fill in what they were using the unfocused event for. Which is what the issue linked above should do.

**Closed by PureWeen** 2023-11-06 18:57 UTC
Labels: t/bug, platform/android 🤖, area/controls 🎮, s/verified, control-entry, s/triaged, s/needs-attention
