### ISSUE TITLE
Problem display a page on Android and IOS

### ISSUE THREAD

**Issue by Essama-Official** [dotnet/maui#17242] opened 2023-09-06 20:52 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The first page after login displays nothing. I have a page which allows you to display the published data (name, description, image) by retrieving them from the database, on Windows machine it works but on IOS it displays but I can't do anything about it (the buttons don't work) and on Android it doesn't even display.

### Expected Behavior

1. Login
2. Must display item (contains name, description, image)
3. On Android display nothing, on IOS display but button and scrollview don't work

### Steps To Reproduce

[GitOrbisDemo.txt](https://github.com/dotnet/aspnetcore/files/12542448/GitOrbisDemo.txt)

### Exceptions (if any)

No exception display

### .NET Version

7

### Anything else?

Supposed to show :
![Screenshot (579)](https://github.com/dotnet/aspnetcore/assets/107614355/4ecbdc2c-8dd9-4e67-962f-0f17e6d7e5f2)

**Comment by Eilon** [comment] 2023-09-06 21:59
@Essama-Official are you able to simplify the repro app? Currently it appears to be a fairly large app so it will take us a long time to narrow down the problem. Please remove any unnecessary code and projects from the app so that we can isolate where the problem is. Thanks!

**Comment by Essama-Official** [comment] 2023-09-07 07:30
I did the best I could : https://github.com/Essama-Official/OrbisDemoTest

**Comment by drasticactions** [comment] 2023-09-07 08:55
https://github.com/Essama-Official/OrbisDemoTest/blob/main/OrbisDemoTest/ActivitiePage.xaml#L27

When running on .NET 7 (What you're running), the `RefreshView` frame is not updated to reflect the underlying content, not allowing taps to go through. This was fixed in https://github.com/dotnet/maui/pull/14302 but it is only in net8.0 and not backported to 7.0.

CC @rmarinho @hartez

**Comment by Essama-Official** [comment] 2023-09-08 07:39
For Android I solved it by adding this <StackLayout Grid.Row="4" HeightRequest="600" HorizontalOptions="FillAndExpand" >
      <RefreshView Command="{Binding LoadItemsCommand}" IsRefreshing="{Binding IsBusy, Mode=TwoWay}">. For Android it's good it works, but IOS it's buggy, the application even crashes, the page works at first, but after that I can't scroll anymore and the buttons don't work anymore

**Closed** 2023-09-12 16:13 UTC
Labels: area/layout 🔲, s/needs-attention
