### ISSUE TITLE
ScrollView not working, not reacting to when keyboard is opened

### ISSUE THREAD

**Issue by ultimategrandson** [dotnet/maui#9450] opened 2022-08-16 03:26 UTC
### Description

I cannot get ScrollView to work like it did with Xamarin.Forms. I am using MAUI embedded into a native app, so maybe this has something to do with it. Maybe I am doing something wrong here? I have looked at all the documentation and haven't been able to work out what I could do differently.

Reproduction (iOS Simulator): https://github.com/ultimategrandson/MAUI-ScrollView-Broken-in-Native

### Steps to Reproduce

https://github.com/ultimategrandson/MAUI-ScrollView-Broken-in-Native

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15+

### Did you find any workaround?

Unable to find a workaround.

**Comment by PureWeen** [comment] 2022-08-16 18:23
@ultimategrandson can you include what behavior you're seeing vs what behavior you're expecting please?

**Comment by ultimategrandson** [comment] 2022-08-16 23:08
> @ultimategrandson can you include what behavior you're seeing vs what behavior you're expecting please?

If you run the example github repo linked, when you click on the Entry field at the bottom of the form and the keyboard opens, I expect the form to be able to scroll. The ScrollView which is the root view of the Content Page is not doing anything.

**Comment by ultimategrandson** [comment] 2022-08-17 07:37
I updated my initial bug report to remove references to Android. I have tested it on Android and the ScrollView seems to work. iOS it does not seem to scroll when the keyboard pops up.

**Comment by hartez** [comment] 2022-09-30 17:04
Duplicate of #4792

**Comment by hartez** [comment] 2022-12-16 19:24
Looks like the robots forgot to close this as a duplicate.

**Closed by hartez** 2022-12-16 19:24 UTC
Labels: t/bug, area/layout 🔲, area/native-embedding, s/needs-attention, layout-scrollview
