### ISSUE TITLE
[WinUI] Adding Toolbar item to ContentPage has unusual drop shadow on menu.

### ISSUE THREAD

**Issue by michaelrinderle** [dotnet/maui#19166] opened 2023-12-01 22:53 UTC
### Description

Adding a toolbar item in WinUI has an unusual drop shadow on a new vanilla project.

Adding 
```xml
<ContentPage.ToolbarItems>
    <ToolbarItem Text="test" Order="Secondary" Priority="0" />
</ContentPage.ToolbarItems>    
``` 
to MainPage.Xaml results in the following.

![Screenshot 2023-12-01 164243](https://github.com/dotnet/maui/assets/11905488/6cfa9d1e-afbf-4726-ab7d-a23ee18c6958)

### Steps to Reproduce

1. Create new MAUI App.
2. Add toolbar item to MainPage.Xaml

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

8.0.3

### Affected platforms

Windows

### Did you find any workaround?

No

**Comment by Auto72** [comment] 2023-12-04 15:19
Related to #18258

**Comment by XamlTest** [comment] 2024-01-05 06:30
Verified this on Visual Studio Enterprise 17.9.0 Preview 2(8.0.3). Repro on Windows 11, not repro on Android 14.0-API34, iOS 16.4 and MacCatalyst with below Project:
[19166.zip](https://github.com/dotnet/maui/files/13838723/19166.zip)

**Comment by PureWeen** [comment] 2024-12-06 21:51
Duplicate of #7156

**Closed by PureWeen** 2024-12-06 21:51 UTC
Labels: t/bug, platform/windows 🪟, s/verified, s/triaged, migration-compatibility, area-controls-toolbar
