### ISSUE TITLE
Button with rectangle above get Clicked event

### ISSUE THREAD

**Issue by AlanGusLive** [dotnet/maui#9341] opened 2022-08-11 09:34 UTC
### Description

When a rectangle is above a button and the button is pressed, the Clicked event is received in Android (Bug):

![image](https://user-images.githubusercontent.com/15076413/184103138-30d7bc00-7813-47aa-90fc-ca83a0f9c69d.png)

When a rectangle is above a button and the button is pressed, the Clicked event is NOT received in Windows (OK):
![image](https://user-images.githubusercontent.com/15076413/184103343-4b7dba9e-2bf9-4d62-a65c-e6f18525872b.png)

### Steps to Reproduce

1. Create a New .Net MAUI App
2. In the MainPage.xaml add the ScrollView in a grid
3. Add a Rectangle in the grid after the ScrollView (here a black rectangle with opacity set to 0.6)
4. Click on the button

Sample app:
[RectangleAboveButton.zip](https://github.com/dotnet/maui/files/9307582/RectangleAboveButton.zip)

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

### Did you find any workaround?

No

**Comment by jfversluis** [comment] 2022-08-11 18:16
Duplicate of #7498

**Closed by jfversluis** 2022-08-11 18:16 UTC
Labels: t/bug

**Comment by samhouts** [comment] 2022-08-31 17:02
Duplicate of #9069
