### ISSUE TITLE
Request to add TabIndex, IsTabStop and Focusable

### ISSUE THREAD

**Issue by AwsomeCode** [dotnet/maui#19539] opened 2023-12-21 12:29 UTC
### Description

I am trying to migrate our Xamarin Forms Application to Maui.
The application has an Accounting feature that uses TabIndex, IsTabStop, and Focusable as well.
This is very important for accounting and billing applications.

I request you to kindly add it again. 
https://github.com/dotnet/maui/issues/1646
https://github.com/dotnet/maui/pull/1777

### Public API Changes

TabIndex
IsTabStop
Focusable

### Intended Use-Case

Accounting and billing applications with keyboard.

**Comment by jfversluis** [comment] 2023-12-21 13:36
Duplicate of #16218

**Closed by jfversluis** 2023-12-21 13:36 UTC
Labels: proposal/open
