### ISSUE TITLE
REOPEN [iOS] Type x:Double not found in xmlns http://schemas.microsoft.com/winfx/2009/xaml

### ISSUE THREAD

**Issue by awattar** [dotnet/maui#16519] opened 2023-08-03 09:43 UTC
### Description

Bug still occurs and needs a further investigation.

Refer to:
https://github.com/dotnet/maui/issues/5531
https://github.com/dotnet/maui/issues/6070

Version info:

Visual Studio Enterprise 2022 for Mac
Version 17.6.2 (build 405)

### Steps to Reproduce

Follow the steps from the referred bugs.

### Version with bug

7.0.92

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

**Comment by nll** [comment] 2023-08-03 17:36
This is still happening to me:
```
Microsoft.Maui.Controls.Xaml.XamlParseException: Position 9:6. Type x:String not found in xmlns http://schemas.microsoft.com/winfx/2009/xaml
```
Using:
- .NET SDK 7.0.302
- MAUI workload 7.0.86
- iOS workload 16.4.7054
- macOS 12.6.7
- Debug configuration
- `<MtouchLink>SdkOnly</MtouchLink>` (as I still didn't update macOS/XCode)

Nothing seems to help:
- `<?xaml-comp compile="true" ?>`
- `<ResourceDictionary Source="..." />`
-  `<MtouchExtraArgs>--linkskip=System --linkskip=mscorlib --nolinkaway</MtouchExtraArgs>`
- Remove all `obj` and `bin` directories

**Comment by mattleibow** [comment] 2023-08-16 18:50
@StephaneDelcroix thoughts?

**Comment by samhouts** [comment] 2024-02-01 00:42
Duplicate of #5531

**Closed by samhouts** 2024-02-01 00:42 UTC
Labels: t/bug, area/Xaml </>, platform/iOS 🍎
