### ISSUE TITLE
RadioButton visual does not update properly when enabled/disabled on Android

### ISSUE THREAD

**Issue by davepruitt** [dotnet/maui#14195] opened 2023-03-24 18:33 UTC
### Description

I am developing an Android app with MAUI. I have created a custom template and style for RadioButton in my app. When the user "checks" the radio button, it becomes green. Then, at some point in the app the radio button can become disabled (at which point the color becomes gray so it looks disabled). Then, at a later point in the application the radio button becomes re-enabled. While the radio button is still "checked", it no longer looks "checked".

This is a summary of the states of the RadioButton in my app:

![maui_behavior](https://user-images.githubusercontent.com/15479248/227609739-8d10f58e-6dd0-4a19-b3cd-44df85fd2f98.png)

I am using the following content template and style for my RadioButton:

```
<ControlTemplate x:Key="RadioButtonTemplate">
    <Border Stroke="Transparent" BackgroundColor="{TemplateBinding BackgroundColor}" StrokeShape="RoundRectangle 5,5,5,5" StrokeThickness="3">
        <VisualStateManager.VisualStateGroups>
            <VisualStateGroupList>
                <VisualStateGroup x:Name="CheckedStates">
                    <VisualState x:Name="Checked">
                        <VisualState.Setters>
                            <Setter Property="Stroke" Value="#49851c" />
                        </VisualState.Setters>
                    </VisualState>
                    <VisualState x:Name="Unchecked">
                        <VisualState.Setters>
                            <Setter Property="Stroke" Value="Transparent" />
                        </VisualState.Setters>
                    </VisualState>
                </VisualStateGroup>
            </VisualStateGroupList>
        </VisualStateManager.VisualStateGroups>
        <Grid>
            <Label x:Name="check" Margin="20,5" HorizontalOptions="Center" VerticalOptions="Center" VerticalTextAlignment="Center" TextColor="White" Text="{TemplateBinding Content}" />
        </Grid>
    </Border>            
</ControlTemplate>

<Style TargetType="RadioButton" x:Key="RadioButtonStyle">
    <Setter Property="ControlTemplate" Value="{StaticResource RadioButtonTemplate}" />
    <Style.Triggers>
        <Trigger TargetType="RadioButton" Property="IsEnabled" Value="True">
            <Setter Property="BackgroundColor" Value="DarkBlue" />
        </Trigger>
        <Trigger TargetType="RadioButton" Property="IsEnabled" Value="False">
            <Setter Property="BackgroundColor" Value="LightGray" />
        </Trigger>
        <Trigger TargetType="RadioButton" Property="IsChecked" Value="True">
            <Setter Property="BackgroundColor" Value="#69BE28" />
        </Trigger>
        <Trigger TargetType="RadioButton" Property="IsChecked" Value="False">
            <Setter Property="BackgroundColor" Value="DarkBlue" />
        </Trigger>
    </Style.Triggers>
</Style>
```

I have written a basic example that reproduces the bug, and I have uploaded it to Github. The repository is linked below.

### Steps to Reproduce

1. Run the app in the example repository linked below.
2. In the running app: Select a radio button so it is in the "checked" state
3. In the running app: Disable the radio buttons by pressing the button on the right side of the screen
4. In the running app: Re-enable the radio buttons by pressing the button on the right side of the screen
5. In the running app: Check to see the visual appearance of the radio buttons on the screen

### Link to public reproduction project repository

https://github.com/davepruitt/bug_reproduction_repository_03_maui_radiobutton

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 13 (Samsung Galaxy Tab A7 Lite)

### Did you find any workaround?

None found yet

### Relevant log output

```shell
N/A
```

**Comment by Zhanglirong-Winnie** [comment] 2023-06-15 08:41
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 1.0. Can repro on android platform with sample project.
[bug_reproduction.zip](https://github.com/dotnet/maui/files/11755118/bug_reproduction.zip)
![14195](https://github.com/dotnet/maui/assets/77434865/ceec40bb-de03-4368-9f60-46930aa962f0)

**Comment by dustin-wojciechowski** [comment] 2024-05-15 22:08
@davepruitt So it looks like the issue of the color not being correct in the last portion of your state diagram has been fixed in our current branch, but when I tested your example, there was still some ambiguity with background color. I would recommend using multi-triggers to explicitly define if you have multiple property conditions:

 ```
<Style TargetType="RadioButton" x:Key="RadioButtonStyle">
            <Setter Property="ControlTemplate" Value="{StaticResource RadioButtonTemplate}" />
            <Style.Triggers>
            <MultiTrigger TargetType="RadioButton">
                <MultiTrigger.Conditions>
                    <PropertyCondition Property="IsChecked" Value="True" />
                    <PropertyCondition Property="IsEnabled" Value="False" />
                </MultiTrigger.Conditions>
                <Setter Property="BackgroundColor" Value="LightGray" />
            </MultiTrigger>
            <MultiTrigger TargetType="RadioButton">
                <MultiTrigger.Conditions>
                    <PropertyCondition Property="IsChecked" Value="False" />
                    <PropertyCondition Property="IsEnabled" Value="False" />
                </MultiTrigger.Conditions>
                <Setter Property="BackgroundColor" Value="LightGray" />
            </MultiTrigger>
            <MultiTrigger TargetType="RadioButton">
                <MultiTrigger.Conditions>
                    <PropertyCondition Property="IsChecked" Value="True" />
                    <PropertyCondition Property="IsEnabled" Value="True" />
                </MultiTrigger.Conditions>
                <Setter Property="BackgroundColor" Value="Green" />
            </MultiTrigger>
            <MultiTrigger TargetType="RadioButton">
                <MultiTrigger.Conditions>
                    <PropertyCondition Property="IsChecked" Value="False" />
                    <PropertyCondition Property="IsEnabled" Value="True" />
                </MultiTrigger.Conditions>
                <Setter Property="BackgroundColor" Value="DarkBlue" />
            </MultiTrigger>
            </Style.Triggers>
        </Style>
    </ContentPage.Resources>
```

which will produce this on Android:

https://github.com/dotnet/maui/assets/89540402/5cad44e0-f594-430e-ae8e-cc14bc6d85c2

**Closed by dustin-wojciechowski** 2024-05-15 22:08 UTC
Labels: t/bug, platform/android 🤖, s/verified, area-controls-radiobutton, s/triaged
