### ISSUE TITLE
FlyoutPage issues on iOS Tablets

### ISSUE THREAD

**Issue by dirivero** [dotnet/maui#7520] opened 2022-05-27 01:22 UTC
### Description

FlyoutPage in tablets doesn't work as expected with default `FlyoutLayoutBehavior`.

In Android:
- [the detail is not changed when the property is changed](https://github.com/dotnet/maui/issues/10274)

In iOS:
- if the app starts in landscape it throws the exception pasted at the end of this bug report

In Both platforms:
- rotating the device doesn't refresh the rendered rectangle

![image](https://user-images.githubusercontent.com/7670773/170608868-ee1dbd19-9be8-4804-90c4-13bc9a9f14d6.png)

### Steps to Reproduce

All the behaviors can be reproduced with this project:
[Sample.zip](https://github.com/dotnet/maui/files/8783171/Sample.zip)

The only relevant code is this:
```
public App()
{
    InitializeComponent();

    var flyout = new FlyoutPage
    {
        Detail = new NavigationPage(new ContentPage { Background = Colors.Red })
    };

    var button = new Button { Text = "Open Green Page" };
    button.Clicked += (s, e) => flyout.Detail =
        new NavigationPage(new ContentPage { Background = Colors.Green });

    flyout.Flyout = new ContentPage { Content = button, Title = "Title" };

    MainPage = flyout;
}
``` 

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

All

### Did you find any workaround?

Using `Popover` as the flyout behavior that is not the best approach for landscape. Also, this leads to a very wide menu in iPads:

![image](https://user-images.githubusercontent.com/7670773/170609479-82b3d54d-986d-4aef-910b-94f79701e0f4.png)

### Relevant log output

```shell
Microsoft.Maui.Platform.ToPlatformException: <Microsoft_Maui_Controls_Handlers_Compatibility_PhoneFlyoutPageRenderer: 0x7f8a5d153670> found for Microsoft.Maui.Controls.FlyoutPage is incompatible ---> System.NullReferenceException: Object reference not set to an instance of an object.
  at at Microsoft.Maui.Controls.Handlers.Compatibility.PhoneFlyoutPageRenderer.LayoutChildren(Boolean animated)
  at at Microsoft.Maui.Controls.Handlers.Compatibility.PhoneFlyoutPageRenderer.set_Presented(Boolean value)
  at at Microsoft.Maui.Controls.Handlers.Compatibility.PhoneFlyoutPageRenderer.SetElement(VisualElement element)
  at at Microsoft.Maui.Controls.Handlers.Compatibility.PhoneFlyoutPageRenderer.Microsoft.Maui.IElementHandler.SetVirtualView(IElement view)
  at at Microsoft.Maui.Controls.Element.SetHandler(IElementHandler newHandler)
  at at Microsoft.Maui.Controls.Element.set_Handler(IElementHandler value)
  at at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IElement.set_Handler(IElementHandler value)
  at at Microsoft.Maui.Platform.ElementExtensions.ToHandler(IElement view, IMauiContext context)
  --- End of inner exception stack trace ---
  at at Microsoft.Maui.Platform.ElementExtensions.ToHandler(IElement view, IMauiContext context)
  at at Microsoft.Maui.Platform.ElementExtensions.ToPlatform(IElement view, IMauiContext context)
  at at Microsoft.Maui.Platform.ElementExtensions.ToUIViewController(IElement view, IMauiContext context)
  at at Microsoft.Maui.Handlers.WindowHandler.MapContent(IWindowHandler handler, IWindow window)
  at at Microsoft.Maui.PropertyMapper`2.<>c__DisplayClass5_0[[Microsoft.Maui.IWindow, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Handlers.IWindowHandler, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<Add>b__0(IElementHandler h, IElement v)
  at at Microsoft.Maui.PropertyMapper.UpdatePropertyCore(String key, IElementHandler viewHandler, IElement virtualView)
  at at Microsoft.Maui.PropertyMapper.UpdateProperties(IElementHandler viewHandler, IElement virtualView)
  at at Microsoft.Maui.Handlers.ElementHandler.SetVirtualView(IElement view)
  at at Microsoft.Maui.Controls.Element.SetHandler(IElementHandler newHandler)
  at at Microsoft.Maui.Controls.Element.set_Handler(IElementHandler value)
  at at Microsoft.Maui.Platform.ElementExtensions.SetHandler(INativeObject nativeElement, IElement element, IMauiContext context)
  at at Microsoft.Maui.Platform.ElementExtensions.SetWindowHandler(UIWindow platformWindow, IWindow window, IMauiContext context)
  at at Microsoft.Maui.Platform.ApplicationExtensions.CreatePlatformWindow(IApplication application, UIWindowScene windowScene, NSDictionary[] states)
  at at Microsoft.Maui.Platform.ApplicationExtensions.CreatePlatformWindow(IUIApplicationDelegate platformApplication, IApplication application, UIApplication uiApplication, NSDictionary launchOptions)
  at at Microsoft.Maui.MauiUIApplicationDelegate.FinishedLaunching(UIApplication application, NSDictionary launchOptions)
  at at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass)
  at MauiApp2.Program.Main(String[] args) in /Users/diego/Downloads/MauiApp2/MauiApp2/Platforms/iOS/Program.cs:13
```

**Comment by VincentBu** [comment] 2022-05-27 05:16
I verified your project with with vs main (32526.500.main)
the detail changed on Android:
![image](https://user-images.githubusercontent.com/44959937/170633729-c4890f72-87d8-4095-bdd2-ef600f7c7a6e.png)

and on IOS:
![image](https://user-images.githubusercontent.com/44959937/170634129-c7d787b0-545b-4518-af72-eb6b3e54bcd9.png)

**Comment by bilelmnasser** [comment] 2022-10-21 08:25
Hi everyone, this bug still exist on landscape mode on android, Content page don't get refreshed.

**Comment by breenbob** [comment] 2023-01-18 19:06
This bug affecting me badly on an ongoing project. I created a branch new Maui solution in VS2022 17.5.0 Preview 2 with Maui workload 7.0.52/7.0.100. When I run _my_ app, I see this issue. Notice how the page title updates but the page content does not. It's as if the fragment is not committed. When debugging my app the page is always constructed fine, pushes with no exceptions or errors, and even behaves as though it is in the UI tree:

![qemu-system-x86_64_fEgAkn4kTR](https://user-images.githubusercontent.com/6000851/213270628-80090911-6650-49a7-88ac-e53ac8b0aad4.gif)

However when I pulled down the Maui source code and run the samples app, there is a section under modals where they have a Flyout page with some buttons that allow you to push a new Detail page in the same manner (i.e. with Navigation and not Shell) and this seems to work fine:

![qemu-system-x86_64_tfRPPpfDtp](https://user-images.githubusercontent.com/6000851/213270813-6a414365-bc6d-4ee4-b1ce-8d99f129853f.gif)

This seems a pretty serious bug, not to be able to push a page at all on Android tablets in what is probably the most common of all navigation supporting page layouts.

The workaround of setting flyout behaviour to popover does allow the page to be pushed, but it's not an appropriate fix for me as the side-by-side master/detail view is crucial for our application.

**Comment by breenbob** [comment] 2023-01-18 19:24
I tried putting the pages from my repro app into the Maui samples app and adding a new menu item to test directly. When I navigate to it I can reproduce this issue. Title changes but page never shows. That suggests perhaps it works in the modals section because the initial page is being navigated to modally?

![qemu-system-x86_64_8w5L7p0one](https://user-images.githubusercontent.com/6000851/213275033-dfaedd81-6c2a-4bf6-9112-50d9d0b0ba59.gif)

At least now I have something I can debug in Maui source code.

**Comment by drasticactions** [comment] 2023-02-15 17:07
Hey folks, I talked with @PureWeen about this bug and I'm going to try and give a hand to help out here.

@dirivero Checking your sample against .NET 7, I believe your issues are fixed. I could not repro it on Android, Catalyst, nor iOS on iPad, and I think the linked issues in this PR took care of it. If you could verify it on your end with the newest .NET 7 MAUI build, that would be great, and thank you!

For @breenbob, you fixed your Android issue and @PureWeen started working on the iOS fix. I believe your issue is different from the original issue on this bug, so if it's okay with you, I would like to move it to a new bug that we can track and close this one (Pending that it is fixed).

**Comment by breenbob** [comment] 2023-02-15 17:30
Hi @drasticactions. Fantastic news that you are looking into this 😄  

Yeah the original issue posted by OP (not me) related to Android and iOS. Though similar at first it transpired they were 2 different issues with different causes and different side effects. My PR fixed the Android issue only. That's been merged and a separate issue closed for that. 

After doing some investigation and work on the iOS side @PureWeen updated this issue accordingly to remove any reference to the Android issue (bar my now defunct comments above) to keep it open, so it now relates to the iOS issue only, which is also affecting my team.

So IMO this issue now relates solely to iOS so my comments above re Android could just be marked off-topic if you wish. Up to you whether you want to leave open or create a new issue...

**Comment by breenbob** [comment] 2023-02-15 17:52
I was mainly having this specific issue on iOS. I wasn't aware it was fixed in order to retest as expecting this issue to be updated so will retest now in latest Maui build and update this thread. As for the other part of the issue @PureWeen is working on a fix to, I can only assume it relates to navigation within the Flyout page in split layout mode, as this was my issue with Android. I will test this also in latest Maui and update this thread as it's possible there is nothing to do here for me.

**Comment by breenbob** [comment] 2023-02-15 22:15
@drasticactions OK did some testing on latest & greatest VS4Mac/.Net SDK/Maui workload and definitely still a few issues here.

I am running latest VS preview:
![image](https://user-images.githubusercontent.com/6000851/219173521-8345b174-65e3-483e-9299-4e763e71d861.png)

Have latest Maui workloads (7.0.59 Service Release 3):
![image](https://user-images.githubusercontent.com/6000851/219174140-0ad3afd5-fc31-4e4c-8715-303d300d2bc0.png)

Deleted existing app build from device, did clean/rebuild etc.

When I run on iPad in landscape mode, Default flyout behaviour is still Popover mode as per the original screenshot above. The detail page appears clipped/does not fully resize to fit:
![image](https://user-images.githubusercontent.com/6000851/219175569-c9f1207e-8d93-4adb-9f9d-cad08fe3ef50.png)

Rotating the page to portrait changes to a closed Popover. Rotating back to landscape stays as closed popover.

I tried to force split screen behaviour by setting `FlyoutLayoutBehavior = FlyoutLayoutBehavior.SplitOnLandscape;` in the code behind, but it had no effect.

So I am a little confused as to what from the original reported issue is actually fixed? Also, the only linked issues on this issue is the Android issue, and @PureWeen's partial fix for this that is still a draft PR?

@dirivero have you tested your original issue to see if it is resolved for you?

**Comment by drasticactions** [comment] 2023-02-16 02:53
- "if the app starts in landscape it throws the exception pasted at the end of this bug report" Starting an iPad (Simulator and device) I could not reproduce that exception in net7.0. 
- The popover default is indeed still the case, but I wasn't sure if that _was_ an issue, or if it was a workaround the prevent the exception from being thrown, since it was listed under "Did you find any workaround?" I do agree it's pretty weird looking, but that could be something that can be changed with a handler while we work on a longer term solution. 
- The "the detail is not changed when the property is changed" for Android should have been fixed with your PR, as the linked issue says it was fixed by it. If it wasn't, then I'm not sure what's broken.

So I'm trying to distill the list of issues down so I can make new ones that are separated, rather than one uber issue. For example, while trying to repro the crash issue in the first comment, I saw this crash as well (https://github.com/dotnet/maui/issues/11785), and it could be interlinked with this issue.

**Comment by breenbob** [comment] 2023-02-27 21:53
@drasticactions yes of the original issues you are correct, the exception is fixed and my PR fixes the Android issue. 

The issues I'm seeing with iOS are:

1. Maui ignores explicit values set in xaml/code behind for FlyoutBehaviour, at least in landscape on iPad it always appears as popover, and as popover also appears open by default, the RHS/end of the detail page initially appears clipped (probably normal for popover appearance, just looks odd in landscape).
2. Flyout layout is weirdly sized, proportions are closer to 50/50 than 30/70.

I didn't report this issue originally but have raised it with CAT team, so I'm happy for these to be split out into separate issues, as long as they link back to this one.

Can you give any quick pointers on what a handler workaround would need to do to force split screen view on the Flyout page on iOS, and set the widths of flyout/detail to something more akin to Android layout?

**Comment by PureWeen** [comment] 2023-03-23 19:03
> @drasticactions yes of the original issues you are correct, the exception is fixed and my PR fixes the Android issue.
> 
> The issues I'm seeing with iOS are:
> 
> 1. Maui ignores explicit values set in xaml/code behind for FlyoutBehaviour, at least in landscape on iPad it always appears as popover, and as popover also appears open by default, the RHS/end of the detail page initially appears clipped (probably normal for popover appearance, just looks odd in landscape).

@breenbob can you clarify this one a bit (possibly in a new issue) with screen shots and a repro? 

I tested this a bit and it seems to be obeying these values on launch. I think the issue here is that it doesn't switch between the modes correctly when you rotate. 

Here's the behavior I'm seeing on launch

1) If FlyoutBehavior is set to Default it will basically be set to "SplitOnLandscape" when you are on an iPAD. You currently can't validate this via rotating the device because it seems like there's a bug on rotation . I tested by launching the app to the iPAD and on portrait it starts out as popover and landscape it starts out as split
2) I tested all the variations of FlyoutBehavior

```C#
PopOver
SplitOnPortrait
SplitOnLandscape
Split
```

And in each case the app always launched in the mode that I expected it to. 


Here's the basic code I'm using to test this

```C#

MainPage = new FlyoutPage()
{
	FlyoutLayoutBehavior = FlyoutLayoutBehavior.Popover, // replace this accordingly 
	Detail = new NavigationPage(new MainPage()),
	Flyout = new ContentPage()
	{
		Title = "Flyout page",
		Content = new VerticalStackLayout()
		{
			Children =
			{
				new Label()
				{
					Text = "flyout page"
				}
			}
		}
    }
};
```

I'm thinking what you're seeing here is the rotation bug. If that's not true can you please open a new issue and link to it here?

**Comment by PureWeen** [comment] 2023-03-28 01:26
I pushed up a version of the fixed renderer [here](https://github.com/PureWeen/ShanedlerSamples) if anyone wants to install the nuget, test, and give me feedback.

**Closed** 2023-05-08 22:52 UTC
Labels: t/bug, p/1, partner/cat 😻, area/FlyoutPage

**Comment by breenbob** [comment] 2023-05-15 19:06
Thanks for the fantastic fix on this @PureWeen - it resolves all the issues I've been having, and relieved that it now works as per XF as had been having bugs raised internally about that as well!
