### ISSUE TITLE
Maui Blazor App Add service exception

### ISSUE THREAD

**Issue by HenJigg** [dotnet/maui#1167] opened 2021-06-03 13:53 UTC
### Description
Unable to register for service

### Steps to Reproduce
1.  Create Maui Blazor App
2.  Add AntDesign Blazor UI library

- Version with issue:
- IDE: Visual Studio 2019 Preview 16.11.0 
- Android: 10
- Nuget Packages: AntDesign

### Screenshots
![image](https://user-images.githubusercontent.com/42528522/120737528-d0f0cf00-c520-11eb-85b1-a6b61787eb17.png)

**Comment by HenJigg** [comment] 2021-06-03 13:55
![image](https://user-images.githubusercontent.com/42528522/120656692-6b67f880-c4b6-11eb-966a-9000e91a1f84.png)

**Comment by HenJigg** [comment] 2021-06-03 13:56
![image](https://user-images.githubusercontent.com/42528522/120656875-905c6b80-c4b6-11eb-9345-b47069231dcf.png)

**Comment by nanrod** [comment] 2021-06-03 17:06
I think you misspelled "Ant" in the first screenshot.

**Comment by hw72869951** [comment] 2021-06-17 14:02
这个没有写错，这个问题我发现所有的web版本的blazor组件好像都不能使用，还有web版本的bootstrap blazor如果用在MAUI中一样也会出现同样的问题

**Comment by hw72869951** [comment] 2021-06-17 14:03
只要是第三方的web    blazor组件都不能正常使用

**Comment by Eilon** [comment] 2021-07-07 22:40
In general you should be able to use any Blazor library in Blazor Desktop apps, such as .NET MAUI. I don't see any errors in any of the screenshots. Are you getting an exception? Do you have a stack trace?

**Comment by Eilon** [comment] 2021-08-03 17:50
Closing because it's not clear what the issue is.

**Closed by Eilon** 2021-08-03 17:50 UTC
Labels: area/blazor, t/bug
