### ISSUE TITLE
Checkbox Not Checked When Using Gesture Recognizer

### ISSUE THREAD

**Issue by RiyashameedM** [dotnet/maui#16397] opened 2023-07-27 10:00 UTC
### Description

Hi, I am using a checkbox with a gesture recognizer. When tapping on the checkbox, it is not getting checked, and the IsChecked value remains the same.i have attached the sample below for your reference.

### Steps to Reproduce

1.Run the attached sample.
2.Tap on the check box

### Link to public reproduction project repository

https://github.com/RiyashameedM/CheckBoxIssue

### Version with bug

7.0.49

### Last version that worked well

7.0.49

### Affected platforms

iOS, Android, macOS

### Affected platform versions

Android 9.0,IOS 14 Pro 16.4

### Did you find any workaround?

No

**Comment by XamlTest** [comment] 2023-08-11 09:24
Verified this on Visual Studio Enterprise 17.8.0 Preview 1.0. Repro on Android 13.0-API33 and iOS 16.4(8.0.100-preview.7.23376.3), not repro on Windows 11 with below Project:
[CheckboxSample.zip](https://github.com/dotnet/maui/files/12320134/CheckboxSample.zip)

**Comment by samhouts** [comment] 2023-08-17 22:41
Please see https://github.com/dotnet/maui/issues/8895#issuecomment-1669980667

**Comment by samhouts** [comment] 2023-08-17 22:41
Duplicate of #8895

**Closed by samhouts** 2023-08-17 22:41 UTC
Labels: t/bug, area/controls 🎮, s/verified, control-checkbox, s/triaged, area/gestures
