### ISSUE TITLE
RadioButton colors doesn't work

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#13771] opened 2023-03-08 18:44 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/RadioButton-colors-doesnt-work/10299627)._

---
When using a MAUI RadioButton, there is no way to change the color of it. The if the Content is set to a string it does not respect the TextColor setting. Additionally there is no way to change the color of the radio button’s circular button.

---
#### Rainer Mager on 3/4/2023, 05:45 AM: 

(private comment, text removed)
#### Feedback Bot on 3/5/2023, 10:55 PM: 

(private comment, text removed)
#### v-annajinjin [MSFT] on 3/6/2023, 11:38 PM: 

(private comment, text removed)
#### Rainer Mager on 3/7/2023, 04:24 AM: 

(private comment, text removed)
#### Feedback Bot on 3/7/2023, 06:31 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by mattleibow** [comment] 2023-03-08 19:15
Duplicate of #13670

**Closed** 2023-03-08 19:16 UTC
