### ISSUE TITLE
Images not appearing on Android App with RC1

### ISSUE THREAD

**Issue by davefxy** [dotnet/maui#6116] opened 2022-04-15 00:11 UTC
### Description

Downloaded images are not appearing on the Android with RC 1. The display of images was not a problem in preview 14.
I have not tried any other versions of the app.

### Steps to Reproduce

I originally discovered this on one of my apps. Then went looking for one of your apps to reproduce it.
Build and run  james montemagno MonkeyFinder app ( .NET Maui workshop, dotnet-maui-workshop\Part 6). The app downloads monkey images. The images appear on the app's Windows  version. But don't appear on the Android version. This was working on preview 14. 

https://github.com/dotnet-presentations/dotnet-maui-workshop

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Preview 14

### Affected platforms

Android

### Affected platform versions

Android 12.0 - API 31

### Did you find any workaround?

NO

### Relevant log output

[](url
[MonkeyFinder.zip](https://github.com/dotnet/maui/files/8492993/MonkeyFinder.zip)
)

**Comment by kristinx0211** [comment] 2022-04-15 00:42
verified repro on Android 11.
![image](https://user-images.githubusercontent.com/99457000/163498539-fadad2c5-72bc-44d6-851a-cde659188c61.png)

**Comment by jfversluis** [comment] 2022-04-15 08:17
Duplicate of #6067

**Closed by jfversluis** 2022-04-15 08:17 UTC
Labels: t/bug, s/verified
