### ISSUE TITLE
Initial value for the SearchHandler background color ignored on page first appearance

### ISSUE THREAD

**Issue by andy-cox** [dotnet/maui#24100] opened 2024-08-08 13:01 UTC
### Description

The SearchHandler background color property, for the search input field, is ignored when a shell page is initially loaded. Navigating away from the page and returning then displays the correct color.

Given the following markup:
```
<Shell.SearchHandler>
    <SearchHandler Placeholder="Enter search term" BackgroundColor="Red">
    </SearchHandler>
</Shell.SearchHandler>
```
You would expect the search input to have a background color of Red but this property is ignored...
![initial-page-load](https://github.com/user-attachments/assets/e7168dde-1056-4a43-a829-2966a6556e44)

After navigating away from the page and returning the background color is rendered correctly...
![after-navigating-back](https://github.com/user-attachments/assets/be665a24-dfef-4fcf-82c0-0d093c08a8c3)

### Steps to Reproduce

1. Create a File > New .NET MAUI App
2. Add a 'SearchHandler' to a page like so:
```
<Shell.SearchHandler>
    <SearchHandler Placeholder="Enter search term" BackgroundColor="Red">
    </SearchHandler>
</Shell.SearchHandler>
```
3. Add another page and a means to navigate between the two, such as tabs.
4. Launch app and observe the background color is ignored.
5. Navigate to the second page.
6. Return to the original page and observe the background color is now applied.

Expected outcome:
The background color should be applied to the search input on initial load.

Actual outcome:
The background color is ignored until returning to the page after it's initial load.

### Link to public reproduction project repository

https://github.com/andy-cox/maui-searchhandler-background-color/tree/net9.0

### Version with bug

9.0.0-preview.6.24327.7

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 17.5

### Did you find any workaround?

No

**Comment by kubaflo** [comment] 2024-08-09 23:56
Duplicate of https://github.com/dotnet/maui/issues/23325

**Closed by kubaflo** 2024-08-09 23:56 UTC
Labels: t/bug, good first issue, platform/iOS 🍎, p/2, area-controls-searchbar
