### ISSUE TITLE
Deployment error 0700 when building as Windows app 

### ISSUE THREAD

**Issue by marwalsch** [dotnet/maui#3542] opened 2021-11-24 08:08 UTC
### Description

When using the Blazor bindings template, attempting to run the app on a windows machine throws an error complaining about a missing splash screen. The package name is a cryptic string.
[Possibly related issue](https://github.com/dotnet/maui/issues/2100#issuecomment-914984677). 		

### Steps to Reproduce

1. Create a Blazor project in the VS 2022 17.1 preview.
2. Try to deply on windows machine.

### Version with bug

Preview 10 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10.0.17763.0

### Did you find any workaround?

No.

### Relevant log output

```shell
DEP0700: Registration of the app failed. [0x80073CF6] AppxManifest.xml(33,27): error 0x80070002: Cannot install or update package D1EABA91-12B1-4A84-AF36-***************** because the splash screen image [appiconfgSplashScreen.png] cannot be located. Verify that the package contains an image that can be used as a splash screen for the application, and that the package manifest points to the correct location in the package where this splash screen image can be found.
```

**Comment by Eilon** [comment] 2021-11-29 20:32
@marwalsch does this work with the non-Blazor MAUI template?

**Comment by dos-ise** [comment] 2021-11-30 09:40
I have the same problem with the non-Blazor MAUI template.

**Comment by marwalsch** [comment] 2021-11-30 10:20
@Eilon I can't seem to be able to reproduce with the Blazor template any more. Might this have been silently fixed in the latest patch release of the VS2022 preview?

**Comment by marwalsch** [comment] 2021-11-30 10:20
@Eilon I can't seem to be able to reproduce with the Blazor template any more. Might this have been silently fixed in the latest patch release of the VS2022 preview?

**Comment by Eilon** [comment] 2021-11-30 17:43
If it's just the splash screen, I happened to see what I think was the exact same error in another app, and this was the workaround:

> It compiles fine for Android. But on Windows it builds, then can't deploy the app because it can't find the specified splash screen file.
> 
> To fix this, in the .../mauiapp/Platforms/Windows/Package.appxmanifest, I changed:
> 
> ```
>         <uap:SplashScreen Image="Assets\appiconfgSplashScreen.png" />
> ```
> 
> To:
> 
> ```
>         <uap:SplashScreen Image="Assets\splashSplashScreen.png" />
> ```
> 
> Because that file seems to be the one configured as the `MauiSplashScreen` asset in the project in the CSPROJ:
> 
> ```
> 		
> 		<MauiImage Include="Resources\appicon.svg" ForegroundFile="Resources\appiconfg.svg" IsAppIcon="true" Color="#C00CC0" />
> 
> 		
> 		<MauiSplashScreen Include="Resources\splash.svg" Color="#C00CC0" />
> ```

And so maybe this was a bug in some version of the templates, that has since been fixed? Can anyone reproduce this in the latest templates? I've done a lot of publishing tests with the latest templates and haven't seen this issue at all.

**Comment by marwalsch** [comment] 2021-12-01 07:20
Can't reproduce anymore on neither the Blazor nor XAML template; tested on Android Simulator on windows. I'll leave the issue open in case @dos-ise has additional feedback.

**Comment by dos-ise** [comment] 2021-12-02 06:22
You are correct. Fixing the file name in the Package.appxmanifest solved the problem for me. Thanks alot

**Comment by Eilon** [comment] 2021-12-02 06:23
OK, closing this. This might have been a bug in the template at some point but it looks like it's fixed for everyone!

**Closed by Eilon** 2021-12-02 06:23 UTC
Labels: t/bug, area/publishing 🏁

**Comment by ColonelDuddits** [comment] 2021-12-04 12:11
This error still occurs for me. As far as I know, I'm using the latest preview (or at least it says it's up to date when I try to update it).
For what it's worth, the error does not occur when I create the Maui Blazor project as part of a new solution. It only occurs when I add a Maui project to an existing solution.

**Comment by Eilon** [comment] 2021-12-05 05:56
@ColonelDuddits does the error go away if you do the [workaround mentioned above](https://github.com/dotnet/maui/issues/3542#issuecomment-982869629) in the appxmanifest file?

**Comment by Eilon** [comment] 2022-02-10 17:14
@mikegoatly - that definitely doesn't look right and shouldn't happen. Can you file that in a new issue so that we can track it?

**Comment by Mephisztoe** [comment] 2022-02-18 10:24
Same problem here. 

My .csproj contains these lines:
`
 
  <MauiSplashScreen Include="Resources\appiconfg.svg" Color="#3064CE" />
`

While my Package.appxmanifest file contains this:
`
<uap:SplashScreen Image="Assets\appiconfgSplashScreen.png" />
`

When I try to deploy the app on my Windows Machine, I get this:

"DEP0700: Fehler beim Registrieren der App. [0x80073CF6] AppxManifest.xml(33,27): Fehler 0x80070003: Das Paket "8496B0C3-46D4-4C37-8FEF-A012F717C268_9zz4h110yvjzm" kann nicht installiert oder aktualisiert werden, da das Begrüßungsbildschirmbild [appiconfgSplashScreen.png] nicht geladen werden kann. Überprüfen Sie, ob das Paket ein Bild enthält, das als Begrüßungsbildschirm für die Anwendung verwendet werden kann, und ob das Paketmanifest auf den richtigen Speicherort des Begrüßungsbildschirmbilds im Paket verweist." (sorry for german translation)

I did a search for *splash*.png within the bin/Debug folder and found a couple of appiconfgSplashScreen images right within the root folder that also contains all compiled DLLs.

They follow this naming-scheme:

appiconfgSplashScreen.scale-[nnn].png

There are 5 of them:

- appiconfgSplashScreen.scale-[100].png
- appiconfgSplashScreen.scale-[125].png
- appiconfgSplashScreen.scale-[150].png
- appiconfgSplashScreen.scale-[200].png
- appiconfgSplashScreen.scale-[400].png

For testing purposes, I edited the Package.appxmanifest file and removed the folder from the file reference:

`
<uap:SplashScreen Image="appiconfgSplashScreen.png" />
`

Now the app gets deployed and executed. However, no splash screen rendered.

Also I noted, that every other appearance of any image such as the Logo or the Tile also reference respective generated PNGs within the Assets folder that does not seem to exist. Thus, when executed, the apps' icon in the taskbar is also empty. When I remove the "Assets\" folder reference in the properties, the taskbar shows the correct image.

Also, I didn't find out, what setting is responsible for the windows' titlebar icon on the top left. 
This one is always set to default.

**Comment by MichaelLant** [comment] 2022-02-20 04:59
I have also been experiencing this problem. I am on the latest preview build. I relocated an included project to a different folder and that is when the problem started. I was able to resolve the issue in the same way that @[Mephisztoe](https://github.com/Mephisztoe) resolved the problem - by removing the reference to the Assets/ folder.

**Comment by Dbquity** [comment] 2022-02-20 12:29
I found the same issue and workaround as @Mephisztoe and @MichaelLant after upgrading to VS 2022 17.2.0 preview 1 / MAUI preview 13 from the latest preview of VS 2022 17.1.0 and MAUI preview 12.
It seems the Assets folder is referred to for all .png files in the ```Package.appxmanifest```:
```xml
  <Applications>
    <Application Id="App"
      Executable="$targetnametoken$.exe"
      EntryPoint="$targetentrypoint$">
      <uap:VisualElements
        DisplayName="MauiApp1"
        Description="MauiApp1"
        BackgroundColor="transparent"
        Square150x150Logo="Assets\appiconMediumTile.png"
        Square44x44Logo="Assets\appiconLogo.png">
        <uap:DefaultTile
          Wide310x150Logo="Assets\appiconWideTile.png"
          Square71x71Logo="Assets\appiconSmallTile.png"
          Square310x310Logo="Assets\appiconLargeTile.png"
          ShortName="MauiApp1">
          <uap:ShowNameOnTiles>
            <uap:ShowOn Tile="square150x150Logo"/>
            <uap:ShowOn Tile="wide310x150Logo"/>
          </uap:ShowNameOnTiles>
        </uap:DefaultTile >
        <uap:SplashScreen Image="Assets\appiconfgSplashScreen.png" />
      </uap:VisualElements>
    </Application>
  </Applications>
```
As far as I can see, the Assets folder has been mentioned here for several preview releases, so while removing the folder works there must be more to the issue.
Having removed the Assets folder, the Maui App deploys and runs, but the nice and friendly .net bot image is no longer rendered - perhaps that is related...
![image](https://user-images.githubusercontent.com/25459675/154842517-5740b1c2-8c72-4370-815b-8048abca17e7.png)

**Comment by Eilon** [comment] 2022-02-21 06:03
Folks - if you're having any issues please make sure there is an open issue tracking it. This issue is closed and is unlikely to get a response from the dev team.
