### ISSUE TITLE
[macOS] `PointerEventArgs.GetPosition(relativeTo: view)` does not give correct values (absolute instead of relative ones?)

### ISSUE THREAD

**Issue by MartyIX** [dotnet/maui#19329] opened 2023-12-11 07:47 UTC
### Description

Pointer events provide `PointerEventArgs` which are [documented](https://learn.microsoft.com/en-gb/dotnet/maui/fundamentals/gestures/pointer?view=net-maui-8.0&tabs=windows#get-the-gesture-position) to allow to get relative position to a visual element - e.g.

```cs
// Position relative to an Image
Point? relativeToImagePosition = e.GetPosition(image);
```

for `PointerMoved` event. Not even new `PointerPressed` and `PointerReleased` (#16925; not yet released)

I created a sample project and the behavior works as expected on Windows but not on Mac Catalyst for me.

### Steps to Reproduce

Run the [sample app](https://github.com/MartyIX/MauiRepro202312PointerPressedRelative) ([commit](https://github.com/MartyIX/MauiRepro202312PointerPressedRelative/commit/24e98668) is important).

Start the app and you should see `Position { ... }` string that shows relative position to the car image.

#### Windows

This is what I observe on Windows:

![Animation](https://github.com/dotnet/maui/assets/203266/fa978222-3b32-4545-9cb8-ef3cc9ced411)

#### macOS

Now run the app using `dotnet build -t:run -c Debug -f net8.0-maccatalyst` and the behavior is like this:
 
https://github.com/dotnet/maui/assets/203266/eb4d46e4-ffea-45d4-a318-73bed0658124

-> The behavior is different on Windows and macOS platform.

### Link to public reproduction project repository

https://github.com/MartyIX/MauiRepro202312PointerPressedRelative

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

macOS Sonoma 14.1.2

### Did you find any workaround?

No.

**Comment by PureWeen** [comment] 2024-01-04 17:51
Duplicate of #19327

**Closed by PureWeen** 2024-01-04 17:51 UTC
Labels: t/bug, platform/macOS 🍏, delighter, i/great-reporter, area/gestures
