### ISSUE TITLE
[MAUI] The "XamlCTask" task failed unexpectedly

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#22378] opened 2024-05-13 18:58 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/MAUI-The-XamlCTask-task-failed-unexp/10640618)._

---
I have custom ContentView as VirtualizeListViewCell in my app and I use it in xaml in DataTemplate, but maui's xaml parser cannot parse it. Look at the screenshot

---
#### Feedback Bot on 4/17/2024, 06:51 PM: 

(private comment, text removed)
#### Александр on 4/18/2024, 10:21 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by PureWeen** [comment] 2024-05-13 19:01
@StephaneDelcroix thoughts?

**Comment by StephaneDelcroix** [comment] 2024-05-13 19:27
@PureWeen no. no repro, no screenshot, but the OP reported it as related to a closed issue

**Comment by jfversluis** [comment] 2024-05-14 07:59
Author indicates its related to #21910 which seems to be a bug in an external library.

Without any more information there is not much actionable here, therefore closing this. If this is still an issue for you, please make sure to open a new issue including relevant code, ideally a reproduction project so we can look at it more easily.

Thanks!

**Closed by jfversluis** 2024-05-14 07:59 UTC
Labels: area-xaml
