### ISSUE TITLE
. UseFormsCompatibility() Error in MAUI Startup.cs after updating Nuget Packages to newest Version

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#1397] opened 2021-06-18 22:56 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/UseFormsCompatibility-Error-in-Blazor/1452043)._

---
[severity:I'm unable to use this version] [regression] [worked-in:16.11.0 Preview 1]
Hello there!

After updating all Nuget Packages to the newest version 

! [image.png] (https://aka.ms/dc/image?name=B4d6f43c0469349fa973eaabc43d0de0c637594552200961195_20210616-174659-image.png&tid=4d6f43c0469349fa973eaabc43d0de0c637594552200961195)

I get following errors:
! [image.png] (https://aka.ms/dc/image?name=B635ed8ae709d4f03858c1c67d58fb3e1637594552564373700_20210616-174735-image.png&tid=635ed8ae709d4f03858c1c67d58fb3e1637594552564373700)

I'm looking forward to your help!

---
#### Feedback Bot on 6/16/2021, 06:52 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by Eilon** [comment] 2021-06-21 16:49
![image](https://user-images.githubusercontent.com/202643/122798863-ec284200-d275-11eb-8cf5-2f0540d1407c.png)

* CS1061 'IAppHostBuiIder' does not contain a definition for 'UseFormsCompatibiIity' and no accessible extension method 'UseFormsCompatibiIity' accepting a first argument of type 'IAppHostBuiIder' could be found (are you missing a using  directive or an assembly reference?) 
* CS0103 The name 'InitializeComponent' does not exist in the current context 
* This version of WinUI does not suppot AnyCPU. Either set Platform or PlatformTarget to one of the following: x86, x64, or arm64.

**Comment by Eilon** [comment] 2021-06-21 17:00
I think this was just a breaking change from .NET MAUI preview 4 to preview 5.

**Comment by Eilon** [comment] 2021-06-21 17:20
To fix this, remove the line `.UseFormsCompatibility()` from `Startup.cs`. I think after that the rest of the errors go away.

**Comment by Darkatek7** [comment] 2021-06-21 20:01
nope after that you get following error:

![image](https://user-images.githubusercontent.com/50767771/122820678-29bfb600-d2dc-11eb-9d74-2e31c41ffa73.png)

**Comment by Eilon** [comment] 2021-06-21 20:39
@Darkatek7 can you show the stack trace of this exception?

**Comment by Darkatek7** [comment] 2021-06-22 11:13
@Eilon 

System.Reflection.TargetInvocationException
HResult=0x80131604
Message=Exception has been thrown by the target of an invocation.
Source=System.Private.CoreLib
StackTrace:
at System.RuntimeType.CreateInstanceOfT()
at System.Activator.CreateInstanceT
at WinRT.WeakLazy`1.get_Value()
at Microsoft.UI.Xaml.Application._IApplicationStatics.get_Instance()
at Microsoft.UI.Xaml.Application.Start(ApplicationInitializationCallback callback)
at AmazonBot.UI.WinUI.Program.Main(String[] args) in C:\Users\2108\Documents\Repos\AmazonBot-code\AmazonBot-Code\AmazonBot\AmazonBot.UI\AmazonBot.UI.WinUI\obj\Debug\net6.0-windows10.0.19041\Windows\App.g.i.cs:line 26

This exception was originally thrown at this call stack:
[External Code]

Inner Exception 1:
COMException: Class not registered (0x80040154 (REGDB_E_CLASSNOTREG))

**Comment by Eilon** [comment] 2021-06-22 18:06
@Darkatek7 ok that no longer looks related to Blazor Desktop. If you create a new .NET MAUI Blazor app (`dotnet new maui-blazor`) using Preview 5, are you able to run that? There are many changes between Preview 4 and Preview 5 and it could be that you're missing some of those changes in the templates.

**Comment by Eilon** [comment] 2021-06-22 20:43
@PureWeen - could this error be caused by not having some Project Reunion extensions installed?

**Comment by Eilon** [comment] 2021-06-22 20:44
@Darkatek7 can you confirm that you've installed the various dev tools for Project Reunion (that's where WinUI comes from): https://docs.microsoft.com/en-us/windows/apps/project-reunion/set-up-your-development-environment

**Comment by PureWeen** [comment] 2021-06-22 23:03
@Eilon  it could be

@Darkatek7  here are some MAUI specific instructions
https://github.com/dotnet/maui-samples#winui3

You'll need to install the preview 0.8 VSIX's and uninstall any other WinUI/Reunion VSIX's that you already have installed

**Comment by Eilon** [comment] 2021-07-08 18:47
Closing this because I think the issue is likely resolved.

**Closed by Eilon** 2021-07-08 18:47 UTC
