### ISSUE TITLE
OnAppearing gets called numerous times before page appears on Windows version of app

### ISSUE THREAD

**Issue by davefxy** [dotnet/maui#9473] opened 2022-08-16 18:45 UTC
### Description

1. When I run the windows version of an app and set a breakpoint on the OnAppearing() method, the app breaks numerous times before the new page appears. The Android version of the app breaks once at OnAppearing() before the page appears.

### Steps to Reproduce

1. Get app at : https://github.com/dotnet/maui-samples/tree/main/6.0/Apps/WeatherTwentyOne
2. Place a breakpoint at OnAppearing() in FavoritesPage.xaml.cs
3. Compile and run on Windows
4. Continue pressing continue until the new page appears
I am using VS 2022 preview Version 17.4.0 Preview 1.0 on windows 11

### Version with bug

6.0.312

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 11 and VS 2022 Version 17.4.0 Preview 1.0

### Did you find any workaround?

no

**Comment by MagicAndre1981** [comment] 2022-08-19 13:35
Duplicate of https://github.com/dotnet/maui/issues/9246 

According to @PureWeen it is [by design](https://github.com/dotnet/maui/issues/9246#issuecomment-1208195006):

> `OnAppearing` fires whenever the window is made inactive and then re-activated. The same thing happens on android if a permission dialog pops up (which is consistent with how it worked in XF).

**Comment by PureWeen** [comment] 2022-08-19 15:08
When the break point hits your app goes into the background so it has now `Disappeared` then when you activate it it reappears. 

if you try to debug a WinUI App and add a break point to `window.Activated` the same thing happens

**Comment by PureWeen** [comment] 2022-08-19 15:55
https://github.com/dotnet/maui/issues/9497

**Closed** 2022-10-11 21:22 UTC
Labels: t/bug, platform/windows 🪟, area/lifecycle 🔁
