### ISSUE TITLE
Label.LineBreakMode = TailTruncation not working properly on iOS & macOS

### ISSUE THREAD

**Issue by F-Goncalves** [dotnet/maui#10633] opened 2022-10-12 09:23 UTC
### Description

Hi,

in my app I observed that a Label with LineBreakMode = TailTruncation is not working properly on iOS and macOS.
As you can see in the screenshots below Label still takes to much space and is cut off.

iOS:
![Simulator Screen Shot - iPhone 13 Pro Max - 2022-10-12 at 11 17 46](https://user-images.githubusercontent.com/62646221/195304101-b3d0ff06-f408-44f2-aa1f-8ea899d7bacd.png)

On Android it works as expected:
![Screenshot_1665566232](https://user-images.githubusercontent.com/62646221/195304236-55433ee5-2115-482d-aa1c-2ce83485a44a.png)

### Steps to Reproduce

1. Clone the attached repository and run on iOS or macOS
2. Observe Label not truncating properly

### Link to public reproduction project repository

https://github.com/F-Goncalves/.NET-MAUI-Workshop

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, macOS

### Affected platform versions

iOS 15.5, MacOS 12.5.1

**Comment by PureWeen** [comment] 2022-10-12 18:14
Duplicate of #10494

**Closed by PureWeen** 2022-10-12 18:14 UTC
Labels: t/bug
