### ISSUE TITLE
Border width not updated if device was rotated [Regression]

### ISSUE THREAD

**Issue by AlleSchonWeg** [dotnet/maui#22639] opened 2024-05-24 11:32 UTC
### Description

Starting with 8.0.60-ci.net8.24266.1 the borders horizontal space is not updated if device rotated.
Portrait (OK):
![image](https://github.com/dotnet/maui/assets/6727366/fdc101f8-429e-49e9-872c-c8ab72230f87)

Landscape (NOK):
![image](https://github.com/dotnet/maui/assets/6727366/65eb21ec-0475-43bc-bc2e-bbd73f7bc992)

### Steps to Reproduce

Open Repro.
Rotate device from portrait to landscape.

Latest working version: 8.0.60-ci.net8.10665

[MauiApp8.zip](https://github.com/dotnet/maui/files/15433585/MauiApp8.zip)

Edit:
This could be a similar issue: https://github.com/dotnet/maui/issues/22606

### Version with bug

Nightly / CI build (Please specify exact version)

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

Android

**Comment by jfversluis** [comment] 2024-05-24 13:11
I appreciate the report, however the version you mention seems to be of a CI build, was it merged yet? If not, it seems a bit premature to report it here as its not part of the codebase yet and this might put some people to work trying to track this down only to find out that the code they're looking for is in a PR somewhere, and they now wasted time trying to figure that out.

At the very least please link the place where you got this version from. If it is still an open PR, report those findings there instead of in a new issue.

Can you please confirm where this version comes from?

**Comment by AlleSchonWeg** [comment] 2024-05-24 13:20
Hi @jfversluis 
this version comes from the nightly feed: https://pkgs.dev.azure.com/xamarin/public/_packaging/maui-nightly/nuget/v3/index.json

![image](https://github.com/dotnet/maui/assets/6727366/79358488-1b25-4758-952d-d4c4f0a46b59)

**Comment by jfversluis** [comment] 2024-05-24 14:23
Ah ok, thanks! That's interesting because I thought those were supposed to say `nightly` and not `ci` @rmarinho ?

**Comment by PureWeen** [comment] 2024-05-24 21:42
Duplicate of #22606

**Closed by PureWeen** 2024-05-24 21:42 UTC
Labels: t/bug, platform/android 🤖, area-controls-border, i/regression
