### ISSUE TITLE
plugin firebase dll block ios app building

### ISSUE THREAD

**Issue by sasupallisantosh** [dotnet/maui#26455] opened 2024-12-07 14:45 UTC
Hi, 
I am new to the MAUI multi-platform. i have started without push notifications the app was run successful on Android and IOS devices.
I implemented to handle push notification on Android devices and IOS devices Android working, but IOS app block the building not showing any error.
i attached my .csproj code below.
I am using 
**.net9.0
Plugin.Firebase 3.1.2**
please hel
```c#
<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0-ios</TargetFramework>
		<SupportedOSPlatformVersion>12.2</SupportedOSPlatformVersion>
		<OutputType>Exe</OutputType>
		<RootNamespace>UrbanParking</RootNamespace>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseMaui>true</UseMaui>
		<Platforms>AnyCPU;ARM64;ARM32</Platforms>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
	  <MtouchLink>None</MtouchLink>
	  <MtouchUseLlvm>False</MtouchUseLlvm>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|ARM32'">
	  <MtouchLink>None</MtouchLink>
	  <MtouchUseLlvm>False</MtouchUseLlvm>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|ARM64'">
	  <MtouchLink>None</MtouchLink>
	  <MtouchUseLlvm>False</MtouchUseLlvm>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
	  <MtouchLink>None</MtouchLink>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|ARM32'">
	  <MtouchLink>None</MtouchLink>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|ARM64'">
	  <MtouchLink>None</MtouchLink>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="AppleSignInService2.cs" />
	</ItemGroup>

	<ItemGroup>
 
	  <None Remove="GoogleService-Info.plist" />
 
	  <None Remove="iTunesArtwork" />
 
	  <None Remove="iTunesArtwork%402x" />
 
	  <None Remove="Resources\appstore.png" />
	  <None Remove="Resources\appstore@2x.png" />
	  <None Remove="Resources\splashscreen-568h@2x.png" />
	  <None Remove="Resources\splashscreen-portrait.png" />
	  <None Remove="Resources\splashscreen-portrait@2x.png" />
	  <None Remove="Resources\splashscreen.png" />
	  <None Remove="Resources\splashscreen@2x.png" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Maui" Version="9.1.1" />
		<PackageReference Include="Microsoft.Maui.Controls" Version="9.0.12" />
		<PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="9.0.12" />
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="9.0.0" />
		<PackageReference Include="Plugin.Firebase" Version="3.1.2" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.2.1" />
		<PackageReference Include="System.Reflection" Version="4.3.0" />
		<PackageReference Include="Xamarin.Build.Download" Version="0.11.4" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\S\EyegateMobileApp.csproj" />
	</ItemGroup>
  <ItemGroup>
    <BundleResource Include="GoogleService-Info.plist">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </BundleResource>
  </ItemGroup>
  <ItemGroup>
    <ITunesArtwork Include="iTunesArtwork">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </ITunesArtwork>
    <ITunesArtwork Include="iTunesArtwork@2x" />
  </ItemGroup>
	<!--<ProjectExtensions><VisualStudio><UserProperties XamarinHotReloadWrongLinkerErrorInfoBarUrbanParkingiOSHideInfoBar="True" /></VisualStudio></ProjectExtensions>-->

</Project>

```  

![Image](https://github.com/user-attachments/assets/fe4f6f42-2602-4137-a560-e816f409f087)
After that step build was showing under process will not complete and no error showing, how can we resolve this issue

**Comment by jfversluis** [comment] 2024-12-09 10:49
Without any log output or relevant code it will be very hard to say something useful unfortunately. Ideally you can provide a [reproduction](https://aka.ms/maui-repro) project.

How long did you let this run for? Maybe also try to change your [build log verbosity](https://learn.microsoft.com/visualstudio/ide/how-to-view-save-and-configure-build-log-files?view=vs-2022#specify-data-verbosity-for-build-logs) to see if that shows you a bit more information.

What makes you think it is the implementing of push notifications that maks this happen?

**Comment by sasupallisantosh** [comment] 2024-12-10 01:27
Hi @jfversluis,  

I have started migrating my Xamarin multi-platform project to .NET MAUI. While the Android project is working fine, I am facing issues with the iOS project when trying to integrate push notifications using `Plugin.Firebase`.  

Initially, I encountered problems installing the Firebase DLL for iOS. To resolve this, I moved my project to a shorter file path. However, the issue persisted. I then installed the Firebase DLL via the command line, and while the installation was successful, Visual Studio would hang during the process.  

After a recent Visual Studio update, I was able to install the Firebase DLL without experiencing any hangs. However, when I attempt to build the iOS project, the build process gets stuck indefinitely. If I remove the Firebase DLL, the iOS project builds and runs successfully on the macOS simulator.  

![Image](https://github.com/user-attachments/assets/98d704b7-a301-4248-aaf8-82a42a0eaa75)

This my Repo : 
https://github.com/sasupallisantosh/EyegateMobileApp/tree/ios_plugin_dev
Branch : ios_plugin_dev

**Comment by jfversluis** [comment] 2024-12-10 07:37
Unfortunately we're not able to look at private repositories, so I cannot accept that invitation and look at that, sorry.

Can you try if this also is reproduced on a new project and installing the plugin on that? Additionally, it might still be helpful to see if it works through the command-line and also produce a [binlog file](https://github.com/xamarin/xamarin-macios/wiki/Diagnosis#binary-build-logs).

Thanks!

**Comment by sasupallisantosh** [comment] 2024-12-11 01:36
Hi @jfversluis  I have created basic template proj and in that project installed plugin.firebase.dll I am not implemented any notification related code just i installed that dll after that i am facing the same issue.
this is public repo.
https://github.com/sasupallisantosh/PushTest.git

**Comment by AdamEssenmacher** [comment] 2024-12-11 23:31
Most likely this: https://github.com/dotnet/android-libraries/issues/1047

**Comment by jfversluis** [comment] 2024-12-12 11:57
Thanks @AdamEssenmacher that seems indeed it. I'll ping someone to get that merged soon hopefully! Nothing we can do from our side unfortunately.

**Closed by jfversluis** 2024-12-12 11:57 UTC
Labels: t/bug, platform/iOS 🍎, s/needs-attention

**Comment by VideoSystems** [comment] 2024-12-12 21:33
For any stumbling across this issue, there's a manual workaround that allows me to build my project again:

1. Navigate in Windows to the following directory:  C:\Users\[USER]\AppData\Local\XamarinBuildDownloadCache
2. Look for GAppM-10.28.0.tgz and extract it.  If it doesn't exist, you can download it from here:  https://dl.google.com/firebase/ios/analytics/4d5ec9a36b6d4fd4/GoogleAppMeasurement-10.28.0.tar.gz.  Make sure to extract it to the folder name "GAppM-10.28.0".
3. You should see a file called "GAppM-8.9.1.unpacked" in the XamarinBuildDownloadCache directory.  Make a copy of that and rename the file to "GAppM-10.28.0.unpacked".  
4. VS should now recognize that the folder now exists and shouldn't prompt for the Overwrite of the folder in the background, which was the cause of the build hang.

**Comment by sasupallisantosh** [comment] 2024-12-13 03:01
That issue was resolved but i got one error.
`clang++ exited with code 1:
Undefined symbols for architecture arm64:
  "_APMAnalyticsConfiguration", referenced from:
      +[FIRAnalytics startWithConfiguration:options:] in FirebaseAnalytics[arm64][10](FIRAnalytics.o)
  "_APMAppMeasurementOriginFirebase", referenced from:
      +[FIRAnalytics startWithConfiguration:options:] in FirebaseAnalytics[arm64][10](FIRAnalytics.o)
  "_APMConsentSettings3P", referenced from:
      +[FIRAnalytics setConsent:] in FirebaseAnalytics[arm64][10](FIRAnalytics.o)
  "_APMFormattedEventName", referenced from:
      +[FIRAnalytics logEventWithOrigin:name:parameters:] in FirebaseAnalytics[arm64][10](FIRAnalytics.o)
  "_APMFormattedUserPropertyName", referenced from:
      +[FIRAnalytics setUserPropertyString:forName:] in FirebaseAnalytics[arm64][10](FIRAnalytics.o)
  "_APMIsAnalyticsCollectionDeactivated", referenced from:
      +[FIRAnalytics startWithConfiguration:options:] in FirebaseAnalytics[arm64][10](FIRAnalytics.o)
  "_APMIsAnalyticsCollectionEnabled", referenced from:
      +[FIRAnalytics startWithConfiguration:options:] in FirebaseAnalytics[arm64][10](FIRAnalytics.o)
  "_APMMonitorLogTagOptionKey", referenced from:
      +[FIRAnalytics startWithConfiguration:options:] in FirebaseAnalytics[arm64][10](FIRAnalytics.o)
  "_APMUserDataFieldEmailAddress", referenced from:
      +[FIRAnalytics initiateOnDeviceConversionMeasurementWithEmailAddress:] in FirebaseAnalytics[arm64][10](FIRAnalytics.o)
  "_APMUserDataFieldHashedEmailAddress", referenced from:
      +[FIRAnalytics initiateOnDeviceConversionMeasurementWithHashedEmailAddress:] in FirebaseAnalytics[arm64][10](FIRAnalytics.o)
  "_APMUserDataFieldHashedPhoneNumber", referenced from:
      +[FIRAnalytics initiateOnDeviceConversionMeasurementWithHashedPhoneNumber:] in FirebaseAnalytics[arm64][10](FIRAnalytics.o)
  "_APMUserDataFieldPhoneNumber", referenced from:
      +[FIRAnalytics initiateOnDeviceConversionMeasurementWithPhoneNumber:] in FirebaseAnalytics[arm64][10](FIRAnalytics.o)`
how can we resolved
