### ISSUE TITLE
Initially selected item in CollectionView isn't highlighted on iOS

### ISSUE THREAD

**Issue by fischberg** [dotnet/maui#14730] opened 2023-04-24 00:12 UTC
### Description

When the SelectedItem property in a CollectionView is defined before it is rendered, the SelectedItem isn't highlighted in the CollectionView in iOS when the CollectionView is first rendered. If I create a List of items, define a "Selected" property to point to one of those items then, bind the CollectionView's "SelectedItem" property to the "Selected" property, the item contained in "SelectedItem" is not highlighted when the List of items is rendered in the CollectionView. If I click on any item in the CollectionView, it becomes highlighted.

The code referenced in this report shows that the Selected property is set prior to the initial rendering of the the CollectionView, however, the SelectedItem isn't highlighted on iOS (it works on Android).

I attached a screenshot of an iPhone emulator demonstrating the problem.

![Screenshot 2023-04-23 at 7 10 32 PM](https://user-images.githubusercontent.com/16581942/233874409-1b7049cf-f6f8-4d4c-9d4a-adc988ad7604.png)

### Steps to Reproduce

When the app is started, item "2", is selected programmatically as shown in the text "This is he selected item: 2". However, item "2" isn't highlighted in the rendered CollectionView of items "1 2 3". If you click on any item, you'll see it is highlighted and the text below it shows the correct highlighted item.

### Link to public reproduction project repository

https://github.com/fischberg/CollectionViewRepro

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 16.2

### Did you find any workaround?

No

**Comment by drasticactions** [comment] 2023-04-24 04:57
Duplicate of https://github.com/dotnet/maui/issues/14730

The way of interacting with it is different, but the underlying cause, IMO, is the same.

**Closed by drasticactions** 2023-04-24 04:57 UTC
Labels: t/bug

**Comment by samhouts** [comment] 2023-05-10 18:28
Duplicate of #14535
