### ISSUE TITLE
Error with Microsoft.EntityFrameworkCore.Sqlite 

### ISSUE THREAD

**Issue by HobDev** [dotnet/maui#6050] opened 2022-04-13 10:07 UTC
### Description

I want to use `Microsoft.EntityFrameworkCore.Sqlite ` in dotnet maui app. But the app crashes on start on iOS. The error message is:

`System.DllNotFoundException
  Message=e_sqlite3
`

### Steps to Reproduce

Run the repro project on iOS

[MauiApp1.zip](https://github.com/dotnet/maui/files/8480418/MauiApp1.zip)

### Version with bug

Release Candidate 1

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15.4

**Comment by drasticactions** [comment] 2022-04-13 16:26
I don't think you're hitting a MAUI bug here. The problem is EFCore can't find a SQLite library bundled with your application nor on the OS, so it can't load. You, most likely, need to bundle that yourself (https://www.nuget.org/packages?q=SQLitePCLRaw), most likely using https://www.nuget.org/packages/SQLitePCLRaw.bundle_green/2.1.0-pre20220318192836, since it will use the native iOS / Mac libraries on the system.

I would bring this up to https://github.com/dotnet/efcore/

**Comment by HobDev** [comment] 2022-04-13 16:43
@drasticactions  I thought this is due to linker. I will try out our suggestion. Thank you

**Comment by Eilon** [comment] 2022-04-13 18:25
Tagging @bricelam and @ajcvickers

**Comment by VladislavAntonyuk** [comment] 2022-04-13 19:21
Working example: https://github.com/VladislavAntonyuk/MauiSamples/tree/main/KanbanBoard

**Comment by bricelam** [comment] 2022-04-13 19:55
Duplicate of https://github.com/ericsink/SQLitePCL.raw/issues/468?

Have you tried with the latest preview of SQLitePCLRaw? Add this to your project:

```xml
<PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="2.1.0-pre20220318192836" />
```

**Closed** 2022-04-13 20:32 UTC
Labels: t/bug, s/needs-verification
