### ISSUE TITLE
Java.Lang.IndexOutOfBoundsException: setSpan (12 ... 12) ends beyond length 10

### ISSUE THREAD

**Issue by NetCSDev** [dotnet/maui#21944] opened 2024-04-19 12:50 UTC
### Description

The max length set for entry field throws error when try to scan data with more than max length value. eg. if entry field has maxlenght as 10 and try to scan data with length as 12, results into error.

```
Xamarin Exception Stack:
Java.Lang.IndexOutOfBoundsException: setSpan (11 ... 11) ends beyond length 10
  at Java.Interop.JniEnvironment.InstanceMethods.CallNonvirtualVoidMethod(JniObjectReference , JniObjectReference , JniMethodInfo , JniArgumentValue* )
  at Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeVirtualVoidMethod(String , IJavaPeerable , JniArgumentValue* )
  at Android.Widget.EditText.SetSelection(Int32 )
  at Microsoft.Maui.Controls.Platform.EditTextExtensions.UpdateText(EditText editText, InputView inputView)
  at Microsoft.Maui.Controls.Entry.MapText(IEntryHandler handler, Entry entry)
  at Microsoft.Maui.PropertyMapperExtensions.<>c__DisplayClass2_0`2[[Microsoft.Maui.Controls.Entry, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Handlers.IEntryHandler, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<ReplaceMapping>b__0(IEntryHandler h, Entry v, Action`2 p)
  at Microsoft.Maui.PropertyMapperExtensions.<>c__DisplayClass1_0`2[[Microsoft.Maui.Controls.Entry, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Handlers.IEntryHandler, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<ModifyMapping>g__newMethod|0(IElementHandler handler, IElement view)
  at Microsoft.Maui.PropertyMapper`2.<>c__DisplayClass5_0[[Microsoft.Maui.IEntry, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Handlers.IEntryHandler, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<Add>b__0(IElementHandler h, IElement v)
  at Microsoft.Maui.PropertyMapper.UpdatePropertyCore(String key, IElementHandler viewHandler, IElement virtualView)
  at Microsoft.Maui.PropertyMapper.UpdateProperty(IElementHandler viewHandler, IElement virtualView, String property)
  at Microsoft.Maui.Handlers.ElementHandler.UpdateValue(String property)
  at Microsoft.Maui.Controls.Element.OnPropertyChanged(String propertyName)
  at Microsoft.Maui.Controls.BindableObject.SetValueActual(BindableProperty property, BindablePropertyContext context, Object value, Boolean currentlyApplying, SetValueFlags attributes, SetterSpecificity specificity, Boolean silent)
  at Microsoft.Maui.Controls.BindableObject.SetValueCore(BindableProperty property, Object value, SetValueFlags attributes, SetValuePrivateFlags privateAttributes, SetterSpecificity specificity)
  at Microsoft.Maui.Controls.BindingExpression.ApplyCore(Object sourceObject, BindableObject target, BindableProperty property, Boolean fromTarget, SetterSpecificity specificity)
  at Microsoft.Maui.Controls.BindingExpression.Apply(Boolean fromTarget)
  at Microsoft.Maui.Controls.BindingExpression.BindingExpressionPart.<PropertyChanged>b__50_0()
  at Microsoft.Maui.Controls.DispatcherExtensions.DispatchIfRequired(IDispatcher dispatcher, Action action)
  at Microsoft.Maui.Controls.BindingExpression.BindingExpressionPart.PropertyChanged(Object sender, PropertyChangedEventArgs args)
  at Microsoft.Maui.Controls.BindingExpression.WeakPropertyChangedProxy.OnPropertyChanged(Object sender, PropertyChangedEventArgs e)
  at Microsoft.Maui.Controls.BindableObject.OnPropertyChanged(String propertyName)
  at Microsoft.Maui.Controls.Element.OnPropertyChanged(String propertyName)
  at Microsoft.Maui.Controls.BindableObject.SetValueActual(BindableProperty property, BindablePropertyContext context, Object value, Boolean currentlyApplying, SetValueFlags attributes, SetterSpecificity specificity, Boolean silent)
  at Microsoft.Maui.Controls.BindableObject.SetValueCore(BindableProperty property, Object value, SetValueFlags attributes, SetValuePrivateFlags privateAttributes, SetterSpecificity specificity)
  at Microsoft.Maui.Controls.BindingExpression.ApplyCore(Object sourceObject, BindableObject target, BindableProperty property, Boolean fromTarget, SetterSpecificity specificity)
  at Microsoft.Maui.Controls.BindingExpression.Apply(Boolean fromTarget)
  at Microsoft.Maui.Controls.BindingExpression.BindingExpressionPart.<PropertyChanged>b__50_0()
  at Microsoft.Maui.Dispatching.Dispatcher.<>c__DisplayClass4_0.<DispatchImplementation>b__0()
  at Java.Lang.Thread.RunnableImplementor.Run()
  at Java.Lang.IRunnableInvoker.n_Run(IntPtr jnienv, IntPtr native__this)
  at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V(_JniMarshal_PP_V callback, IntPtr jnienv, IntPtr klazz)
  at java.lang.IndexOutOfBoundsException: setSpan (11 ... 11) ends beyond length 10
  at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1325)
  at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:684)
  at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:676)
  at androidx.emoji2.text.SpannableBuilder.setSpan(SpannableBuilder.java:140)
  at android.text.Selection.setSelection(Selection.java:94)
  at android.text.Selection.setSelection(Selection.java:78)
  at android.text.Selection.setSelection(Selection.java:153)
  at android.widget.EditText.setSelection(EditText.java:136)
  at mono.java.lang.RunnableImplementor.n_run(Native Method)
  at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:31)
  at android.os.Handler.handleCallback(Handler.java:883)
  at android.os.Handler.dispatchMessage(Handler.java:100)
  at android.os.Looper.loop(Looper.java:214)
  at android.app.ActivityThread.main(ActivityThread.java:7397)
  at java.lang.reflect.Method.invoke(Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
```

### Steps to Reproduce

1. add entry field 
2. set max length for entry field
3. launch application and use scanner to scan data into the field
4. the error will occur when the scanned data violate max length set

### Version with bug

8.0.20 SR4

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 10 11

**Comment by Zhanglirong-Winnie** [comment] 2024-05-15 09:29
Verified this issue with Visual Studio 17.10 Preview 7.0 (8.0.21&8.0.20). Can repro on android platform.
![image](https://github.com/dotnet/maui/assets/77434865/2987537d-cf0a-488c-a19f-9a4a73b52951)

**Comment by samhouts** [comment] 2024-05-23 23:52
Duplicate of #19689

**Closed by samhouts** 2024-05-23 23:52 UTC
Labels: t/bug, platform/android 🤖, s/verified, area-controls-entry, s/triaged, migration-compatibility
