### ISSUE TITLE
.NET MAUI -  Button IsVisibble property does not function with Value Converter on Android platform

### ISSUE THREAD

**Issue by AndreduToit** [dotnet/maui#8373] opened 2022-06-28 04:36 UTC
### Description

IsVisible property of buttons  bound to observable property, with value converter, does not operate as expected on Android platform - works on Windows Machine platform.
Please refer to the project 'MauiApp1' in Solution Folder 'AndroidButtonVisible' of the solution at the following https://github.com/AndreduToit/NetMauiReproductions (reproduction sample code) - run and click the button several times.

### Steps to Reproduce

1.  Run the project 'MauiApp1' in Solution Folder 'AndroidButtonVisible' of the solution in reproduction sample code on github on Windows platform then Android platform.
2. Click the button several times.
3.  Visibility of buttons are set as expected on Windows platform but not so on Android platform.
4.  NOTE: this is not a <ScrollView> issue - behavior is the same wit or without <ScrollView>.

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11.0

### Did you find any workaround?

No workaround found.

**Comment by Symbai** [comment] 2022-06-28 05:25
Dupe of #8044

**Comment by rachelkang** [comment] 2022-06-28 14:16
Hi, @AndreduToit - thanks for opening this issue. As @Symbai mentioned, it is a duplicate of #8044 which has since been resolved! You should see this fix in the next release :)

**Closed by rachelkang** 2022-06-28 14:16 UTC
Labels: t/bug, s/needs-verification

**Comment by AndreduToit** [comment] 2022-06-29 06:42
@rachelkang  - OK, thanks - I wait for the next release then.
