### ISSUE TITLE
SearchBar: Inconsistent behavior - Confusion and request to reopen issue 9092

### ISSUE THREAD

**Issue by ajvanlaningham** [dotnet/maui#23588] opened 2024-07-12 19:04 UTC
### Description

I don't understand why issue [9092](https://github.com/dotnet/maui/issues/9092) was marked as closed. In the screen shot provided by @Zhanglirong-Winnie (attatched) there is no obvious means for the end-user to execute the search command on iOS
![Screenshot 2024-07-12 at 2 28 49 PM](https://github.com/user-attachments/assets/20444bc7-c7b8-4da2-b22d-a0631524d42e)

### Steps to Reproduce

1.  Create a new Dotnet MAUI app
2. add a SearchBar Keyboard="Numeric" component
3. deploy to any iOS iphone device, struggle to execute any search command

### Link to public reproduction project repository

https://github.com/ajvanlaningham/MAUI-SearchBar-Numeric-iOS-Bug

### Version with bug

8.0.70 SR7

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Did you find any workaround?

Option 1: Created a custom renderer that inherited from search bar that included a "done" or a "search" botton based on @moraismateus' repo [MAUI-iOS-Keyboard-Done-Button](https://github.com/moraismateus/MAUI-iOS-Keyboard-Done-Button)
Option 2: created an event listener that fired the search command after the desired numer of digits were input, case specific as mine were a question of "zip codes"

**Comment by Zhanglirong-Winnie** [comment] 2024-07-15 05:38
This issue has been verified using Visual Studio 17.11.0 Preview 3.0(8.0.70). Can repro on iOS platform.

**Comment by samhouts** [comment] 2024-07-16 17:29
Duplicate of #9092

**Closed** 2024-07-16 17:29 UTC
Labels: t/bug, platform/iOS 🍎, s/verified, s/triaged
