### ISSUE TITLE
Button is clickable even if the IsEnable property of the container control is false.

### ISSUE THREAD

**Issue by usausa** [dotnet/maui#8169] opened 2022-06-20 06:55 UTC
### Description

Even if the IsEnabled property of the container control is set to false, the button is still clickable.
Xamarin.Forms does not have this behavior, and Button clicks are disabled while the container control's IsEnabled is false.

### Steps to Reproduce

The following is the code for verification and the results of the operation.

* MainPage.xaml
```xaml
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage
    x:Class="MauiApp1.MainPage"
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml">

    <StackLayout>
        <Button Clicked="Button_OnClicked" Text="Click" />
    </StackLayout>

</ContentPage>
```

* MainPage.xaml.cs
```cs
public partial class MainPage : ContentPage
{
    public MainPage()
    {
        InitializeComponent();
    }

    private async void Button_OnClicked(object sender, EventArgs e)
    {
        System.Diagnostics.Debug.WriteLine("**** Click start");
        IsEnabled = false;
        
        await Task.Delay(3000);

        IsEnabled = true;
        System.Diagnostics.Debug.WriteLine("**** Click End");
    }
}
```

* Output when a button is pressed repeatedly(MAUI)
```
**** Click start
**** Click start
**** Click start
**** Click End
**** Click End
**** Click End
```

* Output when a button is pressed repeatedly(Xamarin.Forms)
```
**** Click start
**** Click End
**** Click start
**** Click End
**** Click start
**** Click End
```

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows

### Affected platform versions

Android 12, Windows SDK 10.0.19041.0

**Comment by jsuarezruiz** [comment] 2022-06-20 08:47
This issue will be fixed with https://github.com/dotnet/maui/pull/6892

**Comment by jfversluis** [comment] 2022-06-20 13:44
Duplicate of #4755

**Closed by jfversluis** 2022-06-20 13:44 UTC
Labels: t/bug, area/layout 🔲, s/needs-verification
