### ISSUE TITLE
Adding injected Pages to a TabbedView

### ISSUE THREAD

**Issue by sinsedrix** [dotnet/maui#9551] opened 2022-08-19 15:58 UTC
### Description

TabbedView expects the children pages to have default constructor.

When a page constructor has an injected view model, it doesn't seem possible to add it to a TabbedPage.

### Steps to Reproduce

1. Create a MAUI app
2. Switch MainPage to be a TabbedPage
3. Create a Page1Vm view model class and a Page1 page class
4. Add Page1Vm and Page1 as singletons.
5. Add <Page1 /> as a child of MainPage
6. You'll get an error message at compile time

https://github.com/sinsedrix/MauiTests/tree/main/MauiTabbedDI

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows SDK 19041

### Did you find any workaround?

No

I tried to add a default constructor, but then the view model is not injected.

### Relevant log output

```shell
Erreur	XFC0004	Missing default constructor for "MauiApp1.MainPage".	MauiApp1
```

**Comment by matt-goldman** [comment] 2022-08-19 23:01
@ramonB1996 can you help here?

**Comment by Vroomer** [comment] 2022-08-21 10:12
You can work around this by using static ServiceProvider class and calling GetService in the TabbedPage constructor:
```
public static class ServiceProvider
{
    public static TService GetService<TService>()
        => Current.GetService<TService>();

    public static IServiceProvider Current
        =>
#if WINDOWS10_0_17763_0_OR_GREATER
		MauiWinUIApplication.Current.Services;
#elif ANDROID
		MauiApplication.Current.Services;
#elif IOS || MACCATALYST
		MauiUIApplicationDelegate.Current.Services;
#else
		null;
#endif
}
```

TabbedPage constructor:
```
Children.Add(Services.ServiceProvider.GetService<FirstPage>());
Children.Add(Services.ServiceProvider.GetService<SecondPage>());
```

**Comment by sinsedrix** [comment] 2022-08-22 07:30
In my case, I have a MainVm that holds an ObservableCollection of Page1Vm. 

I would expect each view model to be applied to a page.

So this workaround won't work. :/

```
    public ObservableCollection<Page1Vm> Pages { get; } = new();
```

```
<TabbedPage ItemsSource="{Binding Pages}">
    <TabbedPage.ItemTemplate>
        <DataTemplate>
            <Page1 />
        </DataTemplate>
    </TabbedPage.ItemTemplate>
</TabbedPage>
```

**Comment by ramonB1996** [comment] 2022-08-22 08:58
@matt-goldman  Would love to help. I am only using Android at the moment in my own project with your library.

@sinsedrix Does this issue also occur on Android for your reproduction? If so, do you use standard .NET MAUI DI or do you use the package @matt-goldman provided?

**Comment by sinsedrix** [comment] 2022-08-22 09:46
@ramonB1996 
1. With an empty constructor, the app also crashes on Android.
2. It's standard, which one is @matt-goldman DI?
3. It prevents compilation error, but leads to a runtime error (uncaught exception)

Here is a sample project:
- [sinsedrix/MauiTabbedDI](https://github.com/sinsedrix/MauiTabbedDI)

**Comment by ramonB1996** [comment] 2022-08-22 10:00
@sinsedrix Okay good to know. I will try this with your reproduction sample this week. Will get back to you. 

You could try the Page Resolver package by @matt-goldman in the meantime; https://github.com/matt-goldman/Maui.Plugins.PageResolver

Follow the instructions and try if this resolves your problem :)
I know you might not want to install a package to get it to work, but this might at least help you continue in your project.

**Comment by sinsedrix** [comment] 2022-08-23 12:42
An update was made on [sinsedrix/MauiTabbedDI](https://github.com/sinsedrix/MauiTabbedDI) to land on a simple page.
Then a button navigates to the tabbed page.

The default page displays well.

The refresh manages to load tabs and the first displays.

When trying to select another tab, I get again the previous error:

> ArgumentException: Value does not fall within the expected range.

**Comment by PureWeen** [comment] 2022-11-18 15:31
Duplicate of #6389

**Closed by PureWeen** 2022-11-18 15:31 UTC
Labels: t/bug, area/TabbedPage
