### ISSUE TITLE
[BUG] Memory Leak using SkiaBitmapExportContext

### ISSUE THREAD

**Issue by dcaponetti** [dotnet/maui#25881] opened 2024-11-15 09:14 UTC
### Description

Description
Good morning everyone,
We use Microsoft.Maui.Graphics and Microsoft.Maui.Graphics.Skia (ver 9.0.0) to generate images containing text and black and white graphics.

Unfortunately a serious memory leak problem causes the pods running on Kubernetes to restart every 3/4 hours.
I have included all the usings I could:

 using (SkiaBitmapExportContext page = new SkiaBitmapExportContext(

     (int)HelperGraphic.PixelFromMillimeters(Convert.ToSingle(p.Width, System.Globalization.CultureInfo.InvariantCulture), _dpi),
     (int)HelperGraphic.PixelFromMillimeters(Convert.ToSingle(p.Height, System.Globalization.CultureInfo.InvariantCulture), _dpi),
     1.0f,disposeBitmap:true))
 {
     ICanvas g = page.Canvas;
     
     g.FillRectangle(0, 0,
         HelperGraphic.PixelFromMillimeters(Convert.ToSingle(p.Width, System.Globalization.CultureInfo.InvariantCulture), _dpi),
         HelperGraphic.PixelFromMillimeters(Convert.ToSingle(p.Height, System.Globalization.CultureInfo.InvariantCulture), _dpi));
     g.FillColor = Colors.White;
[.....]
 using (IImage image = SkiaImage.FromStream(ms))
 {
[....]

But the problem is not solved.
I attach the dump file of
[MemoryDump.zip](https://github.com/user-attachments/files/17244983/MemoryDump.zip)
the memory executed directly on the K8 pod.

Any ideas?
Thanks a lot.

### Link to public reproduction project repository

https://github.com/dcaponetti/TestImageAPI

### Version with bug

9.0.10 SR1

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Affected platforms

Other (Tizen, Linux, etc. not supported by Microsoft directly), Windows

### Affected platform versions

Kubernetes cluster with net8 windows image

### Did you find any workaround?

no

### Relevant log output

```shell

```

**Comment by jfversluis** [comment] 2024-11-18 16:02
Duplicate of #25079

**Closed by jfversluis** 2024-11-18 16:02 UTC
Labels: t/bug, area-drawing, s/triaged
