### ISSUE TITLE
VS 2022: deploy to Android issue

### ISSUE THREAD

**Issue by edikaufmann** [dotnet/maui#11848] opened 2022-12-03 13:59 UTC
### Description

environment: VS2022 17.4.2, S21 Android 13, .net 7

To test deploying onto my S21 ultra I'm using a (very) simple Maui app (J.M. 'MS Beginners guide').

In VS2022 17.4.2:
'debug' mode: all works fine: i.e. running as 'windows machine' AND 'Android 33 emulator'.
'release' mode:  'windows machine' all ok. However: 'release mode' with 'android 33 emulator', entered 'text' does NOT show up!

Deploying:
.apk file (from above) installs ok on my S21 (no errors). However, entered 'text' does also NOT show up!

What I'm missing? doing wrong!

Thanks for your time and help
ed
PS: I already reported this on below link!

https://learn.microsoft.com/en-us/answers/questions/1105685/deploy-onto-android-13.html

| Expected | Open | Enter & Add |
| :-: | :-: | :-: |
| ![](https://learn.microsoft.com/answers/storage/attachments/264457-maui-vsandroid.png) | ![](https://learn.microsoft.com/answers/storage/attachments/264388-maui-s21-open.jpg) | ![](https://learn.microsoft.com/answers/storage/attachments/264437-maui-s21-enteradd.jpg) |

### Steps to Reproduce

deploying a Maui app to Android 13

### Link to public reproduction project repository

https://github.com/edikaufmann/MauiApp1

### Version with bug

7.0 (current)

### Last version that worked well

7.0 Release Candidate 2

### Affected platforms

Android

### Affected platform versions

Android 13.0, VS 2022 17.4.2 net 7.0

### Did you find any workaround?

NO, not yet

**Comment by edikaufmann** [comment] 2022-12-07 07:10
Hi, as I'm doing this the first time; thank you for letting me know if you need more info!
My repo: https://github.com/edikaufmann/MauiApp1

**Comment by jsuarezruiz** [comment] 2022-12-07 19:11
> https://github.com/edikaufmann/MauiApp1

The links is not working, maybe the repro repository is not public?

**Comment by edikaufmann** [comment] 2022-12-07 19:57
Hi, thanks for info ... as a 1st time user but all should be ok now -> repo public!

**Comment by mattleibow** [comment] 2022-12-08 11:08
Duplicate of #11956

**Comment by mattleibow** [comment] 2022-12-08 11:10
There is maybe an issue with XamlC for release, but in your specific case you have a DataType on the ItemTemplate, but that is incorrect. The DataType should be of the _item_ on the DataTemplate, or `<DataTemplate x:DataType="{x:Type x:String}">`

See: https://github.com/edikaufmann/MauiApp1/blob/master/MainPage.xaml#L31

**Closed by mattleibow** 2022-12-08 11:10 UTC
Labels: t/bug, platform/android 🤖, area/publishing 🏁, s/needs-attention

**Comment by edikaufmann** [comment] 2022-12-09 07:55
thanks a million
