### ISSUE TITLE
[Regression] - Grid Columns Not Resizing Correctly (WinUI/MacCatalyst)

### ISSUE THREAD

**Issue by TiberiusDRAIG** [dotnet/maui#15905] opened 2023-06-28 11:38 UTC
### Description

Grid column resizing is not behaving as expected in .NET8 Preview 5 - I'm finding that things spanning multiple columns can get pushed off the screen at certain sizes, then seem to slide back into view:

[weirdGrid.webm](https://github.com/dotnet/maui/assets/59740414/16075552-7349-4d24-88eb-3614d08a8515)

This doesn't seem to be view-dependent - in our actual app (the above is a simpler repro) we're having the issue using a DockLayout as the multi-column spanning layout. 

### Steps to Reproduce

1. Create default MAUI template app
2. Update MainPage.xaml to:

```
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MauiApp1.MainPage">

    <Grid ColumnDefinitions="3*,*"
          RowDefinitions="*,Auto">
        <VerticalStackLayout
            Spacing="25"
            Padding="30,0"
            VerticalOptions="Center"
            Grid.Column="0"
            Grid.Row="0">

            <Image
                Source="dotnet_bot.png"
                SemanticProperties.Description="Cute dot net bot waving hi to you!"
                HeightRequest="200"
                HorizontalOptions="Center" />

            <Label
                Text="Hello, World!"
                SemanticProperties.HeadingLevel="Level1"
                FontSize="32"
                HorizontalOptions="Center" />

            <Label
                Text="Welcome to .NET Multi-platform App UI"
                SemanticProperties.HeadingLevel="Level2"
                SemanticProperties.Description="Welcome to dot net Multi platform App U I"
                FontSize="18"
                HorizontalOptions="Center" />

            <Button
                x:Name="CounterBtn"
                Text="Click me"
                SemanticProperties.Hint="Counts the number of times you click"
                Clicked="OnCounterClicked"
                HorizontalOptions="Center" />

        </VerticalStackLayout>
        <HorizontalStackLayout Grid.Row="1"
                               Grid.Column="0"
                               Grid.ColumnSpan="2"
                               HeightRequest="80"
                               HorizontalOptions="End"
                               Padding="10"
                               Background="Red">
            <Button/>
            <Button/>
            <Button/>
            <Button/>
        </HorizontalStackLayout>
    </Grid>

</ContentPage>
```

3. Resize window horizontally and observe weird clipping. 

### Link to public reproduction project repository

https://github.com/TiberiusDRAIG/MauiGridResizeBug

### Version with bug

8.0.0-preview.5.8529

### Last version that worked well

7.0.86

### Affected platforms

I was *not* able test on other platforms

### Affected platform versions

net8.0-windows10.0.19041.0

### Did you find any workaround?

No workarounds other than completely redesigning views.

**Comment by TiberiusDRAIG** [comment] 2023-06-28 14:37
Reproduced on Catalyst:

https://github.com/dotnet/maui/assets/59740414/89548528-9b2c-47b0-bdb7-c039da4fa1f4

**Comment by PureWeen** [comment] 2023-06-28 20:05
Duplicate of #15793

**Closed by PureWeen** 2023-06-28 20:05 UTC
Labels: t/bug, area/layout 🔲
