### ISSUE TITLE
Error running default Maui/NET8 win10 solution

### ISSUE THREAD

**Issue by uncmd** [dotnet/maui#20721] opened 2024-02-20 08:12 UTC
Operating System: Windows 10 Pro
Visual Studio Community 2022 17.9

Application builds successfully, but when trying to debug @ Windows Machine, I get an error:
Updating the layout...
Copying files with a total size of less than 1 MB into the layout...
DEP0840:  Project "BlankMauiBlazor need version" > = "3000.934.1904.0" package "MicrosoftCorporationII. WinAppRuntime. Main. 1.3 _8wekyb3d8bbwe" and "MicrosoftCorporationII. WinAppRuntime. Singleton_8wekyb3d8bbwe". The packages should be installed in the first run, if not installed, please visit http://go.microsoft.com/fwlink/?linkid=2222757 for installation instructions.

and net7 no problem

**Comment by mattleibow** [comment] 2024-02-20 19:17
Duplicate of https://github.com/microsoft/WindowsAppSDK/issues/2741

**Closed** 2024-02-20 19:18 UTC
