### ISSUE TITLE
WinUI Shell does not consistently react to shell structure changes 

### ISSUE THREAD

**Issue by PureWeen** [dotnet/maui#7171] opened 2022-05-13 17:08 UTC
You can reproduce this by modifying shell while using hot reload. 

Android/iOS react fine but WinUI does not

I marked this issue as p/1 because it means that WinUI isn't updating as the user makes modifications at runtime

**Comment by samhouts** [comment] 2023-07-14 20:11
Duplicate of #15659

**Closed by samhouts** 2023-07-14 20:11 UTC
Labels: platform/windows 🪟, p/1, area/shell 🐢, delighter, partner/hot-reload-xaml
