### ISSUE TITLE
.NET Maui DisplayAlert action button colours do not work properly for multiple themes

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#16112] opened 2023-07-12 14:17 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/NET-Maui-DisplayAlert-action-button-col/10412597)._

---
\[severity:I’m unable to use this version\]  
When using Shell.Current.DisplayAlert to show an alert dialog to the user the default colour of the buttons is not suitable when in device dark mode (dark gray background with dark purple text). The text colour can be changed in the android colours.xml (I’m not sure how to do it in iOS) , but then the text colour will not work for the light theme properly as it’s difficult to find a single colour that works in both themes. It’s also not ideal having to set colours in platform specific code.

Furthermore, the title and message text changes colour along with the theme automatically (dark has light text and light has dark text). Why don’t the buttons do the same? That would be a simple solution to solve the problem that currently makes it impractical to have in a project.

Please also advise if there is a way to change these text colours that I’m unaware of. I’ve been unable to find much from Google searches.

Thanks,

![Light theme.png](https://aka.ms/dc/image?name=Bb342848208dc43688aac9693c341beee638246911471727168_Light_theme.png&tid=b342848208dc43688aac9693c341beee638246911471727168)

![Dark theme.png](https://aka.ms/dc/image?name=B594c56fa53814de0bfb050999b2b9963638246911570599056_Dark_theme.png&tid=594c56fa53814de0bfb050999b2b9963638246911570599056)  

---
#### Feedback Bot on 7/11/2023, 05:50 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by jfversluis** [comment] 2023-07-13 11:51
Duplicate of #15088

**Closed by jfversluis** 2023-07-13 11:51 UTC
