### ISSUE TITLE
Unable to build and run an Android .NET 7 application with the latest MAUI .NET 9 / Visual Studio 17.12 installed

### ISSUE THREAD

**Issue by davepruitt** [dotnet/maui#25845] opened 2024-11-13 23:32 UTC
### Description

I updated to Visual Studio 17.12 to get the latest .NET 9 and MAUI 9 features, etc. I still have one project that is sitting back on .NET 7, and it currently is unable to be updated to .NET 8 or .NET 9. But I can't compile it/run it/deploy it for Android with the latest .NET 9 installation. It doesn't even give me the option to do so.

I reverted my install to Visual Studio 17.10.5, which allows me to build and deploy this project again. Kind of annoying that I can't even build/deploy this project with the newest MAUI/.NET.

### Steps to Reproduce

See description above

### Version with bug

9.0.0 GA

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.100 SR10

### Affected platforms

Android

### Affected platform versions

Android

### Did you find any workaround?

Reverted the install

### Relevant log output

```shell

```

**Comment by Ying-6** [comment] 2024-11-15 04:49
Hi @davepruitt, regarding the "can't compile it/run it/deploy it for Android" you mentioned, could you provide the specific error information? And could you provide us with a sample project so we can investigate it further? Looking forward to your reply!

**Comment by davepruitt** [comment] 2024-11-15 16:21
There is no error to give you. It literally won't even let me select Android as a build option.

**Comment by davepruitt** [comment] 2024-11-15 16:23
Also, since I reverted my installation, it's difficult for me to give you an sample project. I don't have an extra computer where I can do a new install and create a sample project, and I need this working, so I'll likely be remaining on the previous version for a little while.

**Comment by davepruitt** [comment] 2024-11-15 16:25
My assumption, however, is that if you open up _any_ .NET 7 MAUI project in Visual Studio 17.12 it will likely exhibit this behavior.

**Comment by swagdkau** [comment] 2024-11-17 11:50
Same with .NET 8 Android apps

**Comment by mattleibow** [comment] 2024-11-18 12:18
You will have to pin to .NET 8 with a global.json file. The support cycle of .NET MAUI is Current and Current - 1. This is because of the underlying tooling that we depend on making things really complicated - Xcode, Android SDKs, etc.

```
dotnet new globaljson --sdk-version 8.0.404
```

Replace the version number with whatever .NET 8 SDK you have on your machine.

Or you can edit the file to be any .NET 8:

```
{
  "sdk": {
    "version": "8.0.100",
    "rollForward": "latestMinor"
  }
}
```

Make sure you also install the maui workload for .NET 8 as well.

**Comment by mattleibow** [comment] 2024-11-20 06:05
@samhouts bot or human, this is not a regression as it is as designed. We don't support net7 in net9 and net8 in net10

**Comment by davepruitt** [comment] 2024-11-20 07:20
I understand you don't "support" net7, but to remove the option for a net7 app to even compile seems ridiculous. I can still compile old WPF apps from 2011, why can't I compile a net7 app from the past 2 years. Not "supporting" net7 is not the same as removing the complete ability to compile for it. Of course you want companies/developers using the latest .net, I get it. But to not even be able to compile something from 2 release cycles ago?

**Comment by davepruitt** [comment] 2024-11-20 19:17
> [@davepruitt](https://github.com/davepruitt) I use Visual Studio 17.12 with the latest .NET 9.0 installed to open the .NET 7 MAUI template project, the following errors appear: ![Image](https://github.com/user-attachments/assets/2d4e2fa2-e4e8-4c77-9653-bf4582200700) And I cannot switch to the Android/iOS platform. Is this the issue you are facing? And I can update the .NET 7 MAUI template project to .NET8. Could you provide your .NET 7 project so we can investigate it further?

I didn't see the same error message you see, but I did see the same behavior or it not allowing me to switch to the Android platform.

As I mentioned in my previous comment: I think this is unwise behavior. I understand that .NET 7 Android is no longer supported, but to take that further and say "we won't even let you select the platform and build for it anymore" is a horrible decision.

Whenever I start a new .NET MAUI project, I always use the latest .NET (so up until .NET 9 was recently release, I was using .NET 8 every time I started a new project). Now that .NET 9 is released, I would love to start using .NET 9 for all my new .NET MAUI projects. However, that is for _new_ projects. 

For _old_ projects, they cannot always be updated to the latest .NET immediately. Sometimes I need a keep running one of my old projects on .NET 7 even while I am developing other newer projects on .NET 8 and .NET 9. This could be due to a variety of reasons which don't all need to be listed here.

But now I am forced to choose. Because Visual Studio 17.12 doesn't allow me to build _any_ .NET 7 Android projects, I am forced to _not_ upgrade to Visual Studio 17.12 and .NET 9 at this time, because I have projects that I _need_ to work on right now that _cannot_ go to .NET 8/9 at this time. 

So, once again, this is horrible behavior. Just because you don't "support" something doesn't mean that the behavior should regress like this.

**Comment by paulfarr0w** [comment] 2024-11-21 03:38
We are having the same issue but with an iOS .net 7 solution.  No iOS dropdown at all as per Daves comment.  Do we really have to rewind visual studio if we want to work on a clients project that was targeting .net 7 while we upgrade it?

**Comment by mattleibow** [comment] 2024-11-21 05:01
You can still use a global json to set the sdk used to be the dotnet 8 sdk, which will give you net7 support.

I will let the SDK teams comment on the actual support requirements and reasoning.

**Comment by paulfarr0w** [comment] 2024-11-21 15:27
I have tried to do that but you still don't get the iOS drop down for building and deploying against iOS using that sdk version.

**Comment by Fanantthi** [comment] 2024-11-21 16:39
There is an upgrade tool: https://developercommunity.visualstudio.com/t/VS-17120-dosent-build-net-7/10790210?45y=

**Comment by paulfarr0w** [comment] 2024-11-21 16:52
Customer can't just upgrade overnight.

**Comment by davidortinau** [comment] 2024-11-22 14:34
As Matthew said, to pin any project to a specific version of .NET you should [use a `global.json`](https://learn.microsoft.com/dotnet/core/tools/global-json).  

@paulfarr0w @davepruitt Have you done that? If you have that on top of an existing net7/8 install, then you should be able to continue building and debugging, albeit in an officially unsupported scenario. 

As you may also know, you can also [install versions of VS side by side](https://learn.microsoft.com/en-us/visualstudio/install/install-visual-studio-versions-side-by-side?view=vs-2022) so as not to disrupt your working environment. This works for even multiple versions of stable releases.

![Image](https://github.com/user-attachments/assets/95cb4af9-8dae-45a8-8dc3-63270f55feaa)

**Comment by mattleibow** [comment] 2024-12-05 10:35
Closing this issue because @paulfarr0w's comment is the issue. To build with the old iOS SDK, you need an old Xcode, which needs an old macOS install. The only way to build is to use a global.json and also downgrade you macOS or use a VM that has an older macOS and Xcode.

Apple does not permit you to install older tooling on new OS versions, and they do not allow you to use new tooling on older OS versions.

For Android, this is less of an issue and you can just pin the global.json.

The only way to make this process work is for the iOS team to ship all SDK versions of the tooling with all later versions, so .NET 9 will have all .NET 6, 7 and 8 as well as the base 9. This will require very large installs and overly complex builds. The simpler alternative is for you to just use older SDKs with a global.json on older OS versions and face the likely issue of Apple and Google rejecting your app from the App Stores.

**Closed by mattleibow** 2024-12-05 10:35 UTC
Labels: t/bug, platform/android 🤖, area-setup, s/needs-attention, not-regression
