### ISSUE TITLE
Shapes rendered incorrectly unless both width and height are specified

### ISSUE THREAD

**Issue by billreiss** [dotnet/maui#19427] opened 2023-12-14 17:34 UTC
### Description

On all Platforms, if a Shape doesn't have both a WidthRequest and a HeightRequest, the shape is rendered incorrectly. 

### Steps to Reproduce

1. Create a new .NET MAUI app.
2. Add the following to the start of the VerticalStackLayout:

            <Ellipse Fill="DarkBlue"
                 Stroke="Red"
                 StrokeThickness="4"
                 HeightRequest="50"
                 WidthRequest="200" />
            <Ellipse Fill="DarkBlue"
                 Stroke="Red"
                 StrokeThickness="4"
                 HeightRequest="50"
                 HorizontalOptions="Fill" />

3. Run the app. I would expect both Ellipses to be the same height, with one being 200 wide and the other filling the width of the VerticalStackLayout. Same happens with Grid if not specifying both parameters. Same also happens with Rectangle, and I would assume other shapes.

![image](https://github.com/dotnet/maui/assets/1813417/e5ed190e-1e58-47f9-aa9f-185e70fd22db)

 

### Link to public reproduction project repository

https://github.com/billreiss/ShapeHeightRequest

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows

**Comment by mattleibow** [comment] 2023-12-14 19:15
Duplicate of #16492

**Closed by mattleibow** 2023-12-14 19:15 UTC
Labels: t/bug
