### ISSUE TITLE
Sign In with Apple Web Authenticator for Mac Catalyst

### ISSUE THREAD

**Issue by tekmun** [dotnet/maui#9021] opened 2022-07-27 07:55 UTC
### Description

Based on documentation at https://docs.microsoft.com/en-us/dotnet/maui/platform-integration/communication/authentication, Sign In With Apple is done easily with the following code:
result = await AppleSignInAuthenticator.AuthenticateAsync();
This works on iOS but not on Mac Catalyst. The app crashes at this line.

### Steps to Reproduce

1. Create a Mac Catalyst app and try out this code.
2. result = await AppleSignInAuthenticator.AuthenticateAsync();

Code: https://github.com/dotnet/maui/files/9276592/SignInWithAppleMacCatalyst.zip

### Version with bug

6.0.408 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

Mac OS Monterey

### Did you find any workaround?

No workaround.

**Comment by jfversluis** [comment] 2022-08-01 17:42
Thanks for the report @tekmun! Unfortunately, there is not enough information here to effectively diagnose this issue. Could you add more about what error you're seeing? What's the message? Is there a stack trace? Or ideally, please add a reproduction project that we can run so we can see the issue immediately. Thanks!

**Comment by tekmun** [comment] 2022-08-07 10:25
Hi,
Click on the "SignInWithApple" button on Mac. (Need to change the provisioning profile in .csproj)
Nothing happens.
When I put breakpoints at Lines 13 and 14 in MainPage.xaml.cs, the program stops at Line 13 but never hit Line 14 after clicking the "Step Over".
Perhaps, there are missing codes. Kindly help because this code works well on iOS. Thanks.

[SignInWithAppleMacCatalyst.zip](https://github.com/dotnet/maui/files/9276592/SignInWithAppleMacCatalyst.zip)

**Comment by tekmun** [comment] 2022-08-18 05:38
Any update on this? Are you able to duplicate the error?

**Comment by jfversluis** [comment] 2024-04-08 07:09
Looks like this was fixed by #15188 but it didn't close this issue

**Closed by jfversluis** 2024-04-08 07:09 UTC
Labels: t/bug, platform/macOS 🍏, area/essentials 🍞, s/triaged

**Comment by tekmun** [comment] 2024-04-17 01:19
Verified this issue is solved. Thanks.
