### ISSUE TITLE
The theme of the application changes if you open the file picker dialog and hide/open app

### ISSUE THREAD

**Issue by JaneySprings** [dotnet/maui#20095] opened 2024-01-23 07:53 UTC
### Description

This bug does not reproduces if you do not open the file picker dialog (but the application theme will switched twice)

### Steps to Reproduce

https://github.com/dotnet/maui/assets/48021947/2277bd5c-2525-4112-98c4-f98cc7d284ef

### Link to public reproduction project repository

https://github.com/JaneySprings/SheetViewControllerBug

### Version with bug

8.0.6

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15 (Device / Simulator)

### Did you find any workaround?

no

**Comment by drasticactions** [comment] 2024-01-23 08:18
Duplicate of https://github.com/dotnet/maui/issues/19614

**Closed by drasticactions** 2024-01-23 08:18 UTC
Labels: t/bug
