### ISSUE TITLE
Unable to create XUnit Project referencing .NET 8 MAUI

### ISSUE THREAD

**Issue by owenashurst** [dotnet/maui#21138] opened 2024-03-11 18:55 UTC
### Description

Whenever I try and create an XUnit project targeting my .NET 8 MAUI project, the IDE shows the following error:

Severity	Code	Description	Project	File	Line	Suppression State	Details
Error	NU1201	Project MyMauiApp is not compatible with net8.0 (.NETCoreApp,Version=v8.0). Project MyMauiApp  supports:
  - net8.0-android34.0 (.NETCoreApp,Version=v8.0)
  - net8.0-ios17.2 (.NETCoreApp,Version=v8.0)
  - net8.0-maccatalyst17.2 (.NETCoreApp,Version=v8.0)
  - net8.0-windows10.0.19041 (.NETCoreApp,Version=v8.0)	MyMauiApp.UnitTests	C:\dev\MyMauiApp\MyMauiApp .UnitTests\MyMauiApp.UnitTests.csproj	1		

### Steps to Reproduce

1.) Create a .NET 8 MAUI project
2.) Create an XUnit test project
3.) Reference the .NET MAUI project from the XUnit Project
4.) Observe the error

### Version with bug

8.0.6 SR1

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS, Other (Tizen, Linux, etc. not supported by Microsoft directly)

**Comment by drasticactions** [comment] 2024-03-12 05:49
This is not a bug with MAUI, the error you're getting is correct for what you're doing. See https://github.com/dotnet/maui/issues/17791#issuecomment-1744908157

The XUnit project is `net8.0`. MAUI Projects are platform projects (`net8.0-android;net8.0-ios...`). This is unrelated to MAUI, you would see the same error if you tried referencing other platform-specific .NET projects to a non platform specific project. This isn't a bug, it has always and will always do this.

If you want to test platform specific code, you would need an XUnit test runner that would run the code on the platform in question. If you want to test generic cross-platform code and don't need it running on the platform, then you would need to move that into another class library so you could reference it inside the generic XUnit (or whatever .NET Test framework) you have.

@PureWeen @BretJohnson Do you have any other advice?

**Comment by RoiChen001** [comment] 2024-03-13 09:47
Can repro this issue on the latest 17.10 Preview 2. 
![NU1201](https://github.com/dotnet/maui/assets/143168639/8ecc1c6a-6e13-4a6f-9b40-94e6d6303e33)

**Comment by owenashurst** [comment] 2024-03-13 13:23
> This is not a bug with MAUI, the error you're getting is correct for what you're doing. See https://github.com/dotnet/maui/issues/17791#issuecomment-1744908157
> 
> The XUnit project is `net8.0`. MAUI Projects are platform projects (`net8.0-android;net8.0-ios...`). This is unrelated to MAUI, you would see the same error if you tried referencing other platform-specific .NET projects to a non platform specific project. This isn't a bug, it has always and will always do this.
> 
> If you want to test platform specific code, you would need an XUnit test runner that would run the code on the platform in question. If you want to test generic cross-platform code and don't need it running on the platform, then you would need to move that into another class library so you could reference it inside the generic XUnit (or whatever .NET Test framework) you have. 
> 
> You could also change your MAUI csproj to add the target framework
> 
> ```xml
> <TargetFrameworks>net8.0;net8.0-android;net8.0-ios;net8.0-maccatalyst</TargetFrameworks>
> <TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net8.0-windows10.0.19041.0</TargetFrameworks>
> 
> 
> <OutputType Condition="'$(TargetFramework)' != 'net8.0'">Exe</OutputType>
> ```
> 
> The key is making sure that the generic code doesn't have the output type of an exe, since it can't be run that way.
> 
> @PureWeen @BretJohnson Do you have any other advice? 
> 

Thank you. Adding net8.0 to the target frameworks does indeed work and adding a conditional output, however it then breaks visual studio for me. If I use Rider, I'm able to compile successfully and run my tests. The downside is I obviously lose visual studio and its UI for publishing ad hoc builds. 

I have however found the command line to publish, so it's a bit of a manual task which I'm willing to do if I can actually test my business logic which is more important.

**Comment by PureWeen** [comment] 2024-03-13 14:31
Can you elaborate on "breaks visual studio"?

**Comment by owenashurst** [comment] 2024-03-13 19:07
> Can you elaborate on "breaks visual studio"?

Sorry, was a rushed reply.

I get the following errors in the Errors tab which prevents me from building, however Rider is fine.

`Project MyProject is not compatible with net8.0 (.NETCoreApp,Version=v8.0). Project MyProject does not support any target frameworks.	MyProject .UnitTests	C:\dev\MyProject\MyProject .UnitTests\MyProject .UnitTests.csproj`

And then several errors which are the same:

`Unable to read project information for 'MyProject': The property PackageVersion was expected to have a single value across all target frameworks, but instead had the following values: 0.23, 1.0.0	MyProject 	C:\dev\MyProject\MyProject\MyProject.csproj`

**Comment by mattleibow** [comment] 2024-03-15 15:51
Duplicate of https://github.com/dotnet/maui/issues/17791

**Closed by mattleibow** 2024-03-15 15:51 UTC
Labels: t/bug, s/needs-info, area/testing, s/verified, s/triaged

**Comment by PureWeen** [comment] 2024-03-15 15:52
@owenashurst if you use devkit with vscode do you get the same exception?

**Comment by mattleibow** [comment] 2024-03-15 15:55
This is because the app TFMs are setting a project version property using the ApplicationVersion, however, plain .net 8 does not have this concept. You need to also add a `<Version Condition="'$(TargetFramework)' == 'net8.0">0.23</Version>` 

However, this still does not mean that this is the best way to do testing. It is much better to create a shared project that just has testable items in it - pages, VMs and models. Then make that be multi-targeted. 

Both the app and unit test project can then reference this singe shared project.
