### ISSUE TITLE
[Bug] Naming problem - name is in use

### ISSUE THREAD

**Issue by adojck** [dotnet/maui#58] opened 2020-05-20 11:30 UTC
### Description

Could not find any open issue on this topic. Others are closed, but still not solved. That is why I open a new issue.

MAUI is a registered trademark in European Union. It is registered by Blue Systems which also employes KDE developers.

Here is a link about trademark status: https://euipo.europa.eu/eSearch/#details/trademarks/013410601

These news struck me like a lightning in early morning when I was drinking my coffee. This happening again? It was similar issue that Microsoft made in the past, I think it was GVfs (GNOME Virtual file system), and now this MAUI, which for the past idk maybe 6-8 years was a KDE project for front-end UI framework based on QQC2 and Kirigami. It is really nice project, free and open-source. How can someone just come and take the name of the project for some another project? Maybe my next project should be called .NET or Microsoft? I don't get it...

Solution to the problem would be simple: rename your project, as it is already registered trademark and these actions are illegal.

Oh, and one more thing. Stealing is bad. Microsoft should be ashamed of themselves.

**Comment by AmyrAhmady** [comment] 2020-05-20 11:37
You probably should be ashamed of yourself too for not searching in this repository to see if people already discussed about this or not.

duplicate of #34 #35 #51

**Comment by adojck** [comment] 2020-05-20 11:38
@AmyrAhmady 
Maybe you did not read my issue clearly. I wrote "Others are closed, but still not solved." that is the reason I open a new issue. It should be closed when there is a solution made.

**Comment by AmyrAhmady** [comment] 2020-05-20 11:41
Yes, and they've literally said what you can do instead of opening issues on github:

https://github.com/dotnet/maui/issues/35#issuecomment-631057219

**Comment by dhindrik** [comment] 2020-05-20 11:41
The legal name is ".NET Multi-platform App UI" as @davidortinau stated, https://github.com/dotnet/maui/issues/35#issuecomment-631056170

I don't think naming discussions should be on GitHub.

**Comment by liketechnik** [comment] 2020-05-20 11:44
If the legal name is ".NET Multi-platform App UI", why is this repository at "/dotnet/MAUI"? It's called "MAUI" literally EVERYWHERE in this repository. You can't really be serious here...

**Comment by adojck** [comment] 2020-05-20 11:48
@dhindrik
You wrote "_The legal name is ".NET Multi-platform App UI"_" and that is ok. But MAUI is a registered trademark by Blue Systems and scope is world-wide. All over the place you use naming MAUI, and not long version ".NET Multi-platform App UI". Note that using MAUI name has legal rights and you can't use it.

I think naming discussions should be on GitHub and should be public.

**Comment by samiq** [comment] 2020-05-20 12:05
aside of this religious conversations, I am sure the team can come up with something much better, I love the new approach, I've been waiting for it for 20 years, or let's say 15 if we think Silverlight was the first glance at something like this. 

the new MUV approach looks mint, specially in light of SwiftUI and Flutter, great work team and lets give it a better, lets not be Microsoft for once ;)

**Comment by dhindrik** [comment] 2020-05-20 12:05
I think GitHub should be for technical discussions related to the code. 

The reason I linked to the comment is that he said that he wanted to take naming discussions via email. Probably to point them to the right persons on Microsoft. I guess it is not the developers that are responsible for the legal aspect of the naming. And I don't defend them I just want to help to share the information that are available. And I don't understand how a big company like Microsoft missed that Maui is a registered trademark. I don't think that is good for the product. So hopefully there will be an easy solution to this, that all will be happy with!

**Comment by scherenhaenden** [comment] 2020-05-20 12:09
ppl, be kind... I don't like it either. It can make think ppl that the name was taken like that in a malicious way... But maybe they even didn't know the MAUIKIT... but still, there is no need begin a gihub war ;)

we are all developers ;)

**Comment by adojck** [comment] 2020-05-20 12:10
@dhindrik well yeah, I can agree on that. I can't understand that too. It's the first result when you enter in Google or DuckDuckGo query "Maui Framework" -> https://mauikit.org/

And such company as Microsoft really could do a small research before picking a name for a product.

**Comment by rmarinho** [comment] 2020-05-20 12:11
duplicate of #35

**Comment by adojck** [comment] 2020-05-20 12:12
@rmarinho but the issue is not solved yet. #35 is already closed. Why did you close this issue too?

**Closed by rmarinho** 2020-05-20 12:11 UTC

**Comment by adojck** [comment] 2020-05-20 12:13
@rmarinho also #35 is locked "This conversation has been locked as too heated and limited to collaborators." so we can not have discussion there. Should I open a new issue, or will you re-open this one?

**Comment by rmarinho** [comment] 2020-05-20 12:16
@adojck can i please ask you to read this [comment ](https://github.com/dotnet/maui/issues/35#issuecomment-631056170) 

We belive this is not the forum for this discussion. If there are ongoing concerns, please email david.ortinau@microsoft.com  and we can loop in the appropriate teams.

Also please don't create a new issue. 

Thanks

**Comment by Hual** [comment] 2020-05-20 12:18
This is why Linux products are the way they are, and why noone had ever heard of KDE MAUI until now -- you lot just argue about inane stuff instead of getting work done.
