### ISSUE TITLE
[iOS] Label has incorrect size

### ISSUE THREAD

**Issue by JaneySprings** [dotnet/maui#23943] opened 2024-07-31 12:14 UTC
### Description

<img width="411" alt="image" src="https://github.com/user-attachments/assets/fc4e1d80-829d-4a4a-9b07-aed2218873ec">

### Steps to Reproduce

Run the following code on iOS:
```xml
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MauiSizeBug.MainPage">

    <VerticalStackLayout BackgroundColor="Red">
        <Label
            BackgroundColor="Aqua" WidthRequest="100" MaxLines="5"
            Text="This is a label to show a bug - Test, Test, Test, Test, Test, Test, Test, Test, Test!!!!"  />
    </VerticalStackLayout>

</ContentPage>
```

You can see only first two lines of the text.

### Version with bug

9.0.0-preview.6.24327.7

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 17.5 / iOS 17.2

### Did you find any workaround?

no

**Comment by samhouts** [comment] 2024-07-31 16:40
Duplicate of #23159

**Closed by samhouts** 2024-07-31 16:40 UTC
Labels: t/bug
