### ISSUE TITLE
RadioButton can't be selected when it has TapGesture on Android

### ISSUE THREAD

**Issue by Laradius** [dotnet/maui#9130] opened 2022-08-02 08:13 UTC
### Description

Hello

Here is an easily reproducable code:

`

<RadioButton>
                <RadioButton.GestureRecognizers>
                    <TapGestureRecognizer ></TapGestureRecognizer>
                </RadioButton.GestureRecognizers>
            </RadioButton>

            <RadioButton>
                <RadioButton.GestureRecognizers>

                    <ClickGestureRecognizer></ClickGestureRecognizer>
                </RadioButton.GestureRecognizers>
            </RadioButton>`
`

It doesn't really matter if it's click or tap gesture recognizer. On Android, it just cannot get selected.

### Steps to Reproduce

1. Create new maui app
2. add radio button with TapGestureRecognizer/ClickGestureRecognizer
3. Open Android app and try to click the button

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 10 API 29

### Did you find any workaround?

No., although version is 6.0419

**Comment by jfversluis** [comment] 2022-08-02 18:21
Duplicate of #8895

**Closed by jfversluis** 2022-08-02 18:21 UTC
Labels: t/bug, s/needs-verification
