### ISSUE TITLE
[Enhancement] RequestReview API

### ISSUE THREAD

**Issue by jrahma** [dotnet/maui#2827] opened 2021-10-04 14:59 UTC
Please add RequestReview API so app can request (inApp) review using the store review api, e.g. AppStore, Google Play, Microsoft Store, etc..

This will make it easier to have an inApp review Instead of leaving the app and redirecting the user to external

**Comment by jfversluis** [comment] 2021-11-05 11:22
Duplicate of #3263

**Closed by jfversluis** 2021-11-05 11:22 UTC
Labels: t/enhancement ☀️, area/essentials 🍞
