### ISSUE TITLE
MauiImage resource not work with TintColor

### ISSUE THREAD

**Issue by arkadym** [dotnet/maui#8527] opened 2022-07-05 05:04 UTC
### Description

I have svg image which supposed to use different stroke color for light and dark theme.

Side note: For me is reasonable to allow use same SVG 2 times in csproj file, but give different TintColor and different Resource name, but what have already is also works, so let's continue.

I created 2 copies of the same svg with 2 different names: close_icon.svg and close_icon_gray.svg and put to separate folder 'Resources\CustomImages' 
Then added to csproj as
`<MauiImage Include="Resources\CustomImages\close_icon.svg" TintColor="#FFF" />
<MauiImage Include="Resources\CustomImages\close_icon_gray.svg" TintColor="#BCBCBC" />`

SVG is very simple - cross diagonal lines
`<svg width="12" height="12" viewBox="0 0 12 12" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M11 11L1 1" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
<path d="M11 1L1 11" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
</svg>`

Beacuse of using TintColor i removed stroke attribute from SVG

I've expected to get 2 resources of the same image but different color. But project totally cannot builld with error 
`/usr/local/share/dotnet/packs/Microsoft.Maui.Resizetizer.Sdk/6.0.400/targets/Microsoft.Maui.Resizetizer.targets(9,9): Error MAUI0000: System.ArgumentNullException: Value cannot be null. (Parameter 'image')
   at SkiaSharp.SKCanvas.DrawImage(SKImage image, Single x, Single y, SKPaint paint) in D:\a\1\s\binding\Binding\SKCanvas.cs:line 455
   at SkiaSharp.SKCanvas.DrawBitmap(SKBitmap bitmap, Single x, Single y, SKPaint paint) in D:\a\1\s\binding\Binding\SKCanvas.cs:line 537
   at Microsoft.Maui.Resizetizer.SkiaSharpSvgTools.DrawUnscaled(SKCanvas canvas, Single scale) in D:\a\_work\1\s\src\SingleProject\Resizetizer\src\SkiaSharpSvgTools.cs:line 62
   at Microsoft.Maui.Resizetizer.SkiaSharpTools.Resize(DpiPath dpi, String destination) in D:\a\_work\1\s\src\SingleProject\Resizetizer\src\SkiaSharpTools.cs:line 62
   at Microsoft.Maui.Resizetizer.Resizer.Resize(DpiPath dpi, String inputsFile) in D:\a\_work\1\s\src\SingleProject\Resizetizer\src\Resizer.cs:line 101
   at Microsoft.Maui.Resizetizer.ResizetizeImages.ProcessImageResize(ResizeImageInfo img, DpiPath[] dpis, ConcurrentBag`1 resizedImages) in D:\a\_work\1\s\src\SingleProject\Resizetizer\src\ResizetizeImages.cs:line 189
   at Microsoft.Maui.Resizetizer.ResizetizeImages.<>c__DisplayClass27_0.<ExecuteAsync>b__0(ResizeImageInfo img) in D:\a\_work\1\s\src\SingleProject\Resizetizer\src\ResizetizeImages.cs:line 67
   at Microsoft.Maui.Resizetizer.AsyncTaskExtensions.<>c__DisplayClass0_0`1.<ParallelForEach>b__0(TSource s) in D:\a\_work\1\s\src\SingleProject\Resizetizer\src\AsyncTaskExtensions.cs:line 21 (MAUI0000) (MauiResourceImages1)`

### Steps to Reproduce

1. Create empty NET MAUI App
2. Create folder Resources\CustomImages
3. Put there 2 attached images (SVG)
4. Click build/run

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

Windows 11, Macbook Air M1 with latest MacOS

### Did you find any workaround?

Only workaround is use stroke attribute inside SVG, which totally kill idea of reusing same SVG.
[MauiResourceImages1.zip](https://github.com/dotnet/maui/files/9043378/MauiResourceImages1.zip)
![close_icon_gray](https://user-images.githubusercontent.com/7422012/177253201-a6d51d39-3607-4e03-b343-a9228e1935b4.svg)
![close_icon](https://user-images.githubusercontent.com/7422012/177253206-02fde73f-5ae5-4bf3-8d26-02d65cf40766.svg)

**Comment by mattleibow** [comment] 2022-11-03 22:53
Duplicate of #7207 and fixed in #8020

**Closed by mattleibow** 2022-11-03 22:53 UTC
Labels: t/bug, area/single project ☝️, area/controls 🎮, s/verified, control-image, s/triaged
