### ISSUE TITLE
Error while using SecureStorage in MAUI application

### ISSUE THREAD

**Issue by UwpDev** [dotnet/maui#3855] opened 2021-12-24 12:33 UTC
### Description

Application crashes with the below error when using SecureStorage:
System.IO.FileNotFoundException: 'Could not load file or assembly 'Xamarin.AndroidX.Security.SecurityCrypto, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.'

### Steps to Reproduce

1. Create a new project using template ".NET MAUI App (Preview)"
2. Open MainPage.xaml.cs and add the following line to OnCounterClicked mehtod: string testValue = await SecureStorage.GetAsync("Test");
3. Run application > Click on the "Click me" button. The application crashes with the exception: System.IO.FileNotFoundException: 'Could not load file or assembly 'Xamarin.AndroidX.Security.SecurityCrypto, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.'

### Version with bug

Preview 11

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 11

### Did you find any workaround?
Add Xamarin.AndroidX.Security.SecurityCrypto (Version: 1.1.0-alpha03) NuGet package to project

### Relevant log output

```shell
Resolved pending breakpoint at 'MainPage.xaml.cs:19,1' to void MauiTestApp.MainPage.<OnCounterClicked>d__2.MoveNext () [0x000e7].
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.Security.SecurityCrypto.dll
**System.IO.FileNotFoundException:** 'Could not load file or assembly 'Xamarin.AndroidX.Security.SecurityCrypto, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.'

[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.Security.SecurityCrypto.dll
```

**Comment by canperk** [comment] 2021-12-29 07:30
It is not working in IOS as well.

**Comment by carlosmunozrodriguez** [comment] 2022-01-06 00:41
I had `SecureStorage` working well on Preview10

**Comment by tahaipek** [comment] 2022-01-07 05:46
@carlosmunozrodriguez, It worked with the workaround method by @UwpDev for Android. How did you fix it for iOS?

**Comment by carlosmunozrodriguez** [comment] 2022-01-07 14:22
> @carlosmunozrodriguez, It worked with the workaround method by @UwpDev for Android. How did you fix it for iOS?

I haven't tested in iOS yet. I can live without the workaround for the moment until this bug is fixed

**Comment by mterhorst** [comment] 2022-01-10 16:07
I can confirm for Android as well since preview 11.
![image](https://user-images.githubusercontent.com/24865628/148788901-fbfb0b3f-d776-4dfe-98fd-ef63cd7a1388.png)

The described workaround does seem to fix it.

**Comment by rachelkang** [comment] 2022-01-10 17:42
Hi, all - thanks for discovering this issue and sharing! It looks like the relevant dependencies weren't wired up properly in our current structure - this will be fixed soon.

For those who mentioned having issues on iOS - are you seeing the same exact error?

**Closed** 2022-01-10 20:01 UTC
Labels: t/bug, fatal

**Comment by RaspeR87** [comment] 2022-02-03 10:38
@rachelkang  @Redth is bug https://github.com/dotnet/maui/issues/4490 related with this bug here?
