### ISSUE TITLE
[regression/8.0.3] DataTrigger do not restore the original value anymore

### ISSUE THREAD

**Issue by omghb** [dotnet/maui#18976] opened 2023-11-23 10:52 UTC
### Description

DataTrigger does not restore the original value when the condition is becoming false.

This worked in MAUI 7. After migration to MAUI 8 we see new bugs in our App because of this issue.

### Steps to Reproduce

1. Create MAUI App and select 8.0
2. Open `MainPage.xaml` and replace content with

```xml
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MauiDataTriggerIssue.MainPage">

    <ScrollView>
        <VerticalStackLayout Padding="30,0" Spacing="25">
            <Label Text="Disable button:"/>
            <CheckBox x:Name="testCheck"/>

            <Button x:Name="CounterBtn" Text="Click me" Clicked="OnCounterClicked">
                <Button.Triggers>
                    <DataTrigger Binding="{Binding IsChecked, Source={x:Reference testCheck}}" Value="True" TargetType="Button">
                        <Setter Property="IsEnabled" Value="False"/>
                    </DataTrigger>
                </Button.Triggers>
            </Button>
        </VerticalStackLayout>
    </ScrollView>

</ContentPage>
```

3. Run the App on Windows
4. See that Button is enabled and works
5. Click on CheckBox -> Button get disabled
6. Click again on CheckBox

Expected behavior: Button should get enabled again.
Actual behavior: Button stays disabled.

---
![DataTriggerIssue](https://github.com/dotnet/maui/assets/47421673/bb450832-88a7-4a84-a566-0975ce6ce2e3)
---

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.96

### Affected platforms

iOS, Android, Windows

**Comment by omghb** [comment] 2023-11-27 09:55
This issue might be related to this one:
- https://github.com/dotnet/maui/issues/17597

**Comment by mattleibow** [comment] 2023-11-29 22:10
@StephaneDelcroix thoughts?

**Comment by XamlTest** [comment] 2023-12-28 03:13
Verified this on Visual Studio Enterprise 17.9.0 Preview 2(8.0.3). Repro on Windows 11, Android 14.0-API34, iOS 17.0 and MacCatalyst with below Project:
[18976.zip](https://github.com/dotnet/maui/files/13782986/18976.zip)

**Comment by ShariatPanah** [comment] 2024-01-07 20:09
i'm facing the exact same problem

**Comment by StephaneDelcroix** [comment] 2024-01-09 14:48
I can not reproduce this on top of (today's) main branch. Looks like it was fixed already. I'm pushing a pr with a unit test nd closing this

**Closed** 2024-01-10 17:48 UTC
Labels: t/bug, area/Xaml </>, s/verified, s/triaged, potential-regression

**Comment by ShariatPanah** [comment] 2024-01-12 16:02
@MartyIX Sorry i'm not familiar with Nightly Builds, do i need to add some configuration in my project or something?

**Comment by ShariatPanah** [comment] 2024-01-14 15:58
> > @MartyIX Sorry i'm not familiar with Nightly Builds, do i need to add some configuration in my project or something?
> 
> Hey, it's described in the link I posted.
> 
> Basically, there are nuget packages [here](https://dev.azure.com/xamarin/public/_artifacts/feed/maui-nightly) and you need to link it in your project so that you can test the latest MAUI version from git `main` branch.

I tried searching these packages through Nuget Package Manager, but couldn't find them i even turned on the Include Prerelease checkbox, but with no luck.

then tried editing my .csproj file and replaced the:
```
<PackageReference Include="Microsoft.Maui.Controls" Version="$(MauiVersion)" />
<PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="$(MauiVersion)" />
```

with these two lines:
```
<PackageReference Include="Microsoft.Maui.Controls" Version="8.0.6-nightly.9863" />
<PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="8.0.6-nightly.9863" />
```

but the compiler gives me errors and is complaining about couldn't find these packages and about AndroidManifest file, here's a screenshot:
![image](https://github.com/dotnet/maui/assets/32509267/310d4cd6-5f8c-452b-8615-3e23060d3db5)

so am i doing something wrong?

**Comment by ShariatPanah** [comment] 2024-01-14 21:45
@MartyIX Thanks for your help, i added the PackageSource you pointed out to my Nuget.Config file and everything works fine and my project now gets compiled.
I tested the DataTrigger and yes i can confirm that it works as expected. ✌️
