### ISSUE TITLE
.NET MAUI Shell - FlyoutItem - Icon displays on Windows platform but not on Android platform

### ISSUE THREAD

**Issue by AndreduToit** [dotnet/maui#6924] opened 2022-05-07 09:04 UTC
### Description

Flyout Icons do not display on Android platform but do display on Windows platform.
Please refer to the project 'MauiApp1' in Solution Folder 'FlyoutIcons' of the solution at the following https://github.com/AndreduToit/NetMauiReproductions (reproduction sample code).

### Steps to Reproduce

1. Run the project 'MauiApp1' in Solution Folder 'FlyoutIcons' of the solution in reproduction sample code on github on Windows platform then Android platform.
2. Icons display in the flyout on Windows platform but not so on Android platform.
3. Uncomment the <Shell.ItemTemplate> in 'AppShell.xaml'.
4. Run the project 'MauiApp1'.
5. Icons display in the flyout on Windows platform but not so on Android platform.

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11.0

### Did you find any workaround?

No workaround found.

**Comment by XamlTest** [comment] 2022-05-07 09:11
Verified this issue with Visual Studio Enterprise 17.3.0 Preview 1.0 [32427.455.main]. Repro on Android, not repo on Windows with above project.

**Comment by Redth** [comment] 2022-05-09 13:59
I suspect this is a bug that was fixed with some recent image source fixes and needs to be tested against latest MAUI main again.

**Comment by jfversluis** [comment] 2022-05-23 07:10
@XamlTest could you please test this again with the latest main?

**Comment by dhindrik** [comment] 2022-05-27 11:16
With the released version it works on Mac, but doesn't on iOS. Using FontImageSource works.

**Comment by dgerding** [comment] 2022-07-14 17:22
Think I'm seeing a similar problem. Will see if I can reproduce.

**Comment by PureWeen** [comment] 2022-11-30 20:56
I tested this with net7.0 and it looks like it's working now?

![image](https://user-images.githubusercontent.com/5375137/204906369-fc6bf105-7e65-4fa8-8f07-9625032cf842.png)

**Closed** 2022-12-08 01:02 UTC
Labels: t/bug, area/shell 🐢, s/try-latest-version
