### ISSUE TITLE
Backgroundcolor of Radiobutton is wrong in .net MAUI.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#8083] opened 2022-06-15 18:31 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Backgroundcolor-of-Radiobutton-is-wrong-/10056354)._

---
I'm creating an apprication with .NET MAUI.
I put a radiobutton and set its backgroundcolor not to default color,
but the color is white, which I do not select whenever I debug it.
Plese check and fix this trouble.
I use Visual Studio Community 2022 preview 1.1.

---
#### Feedback Bot on 5/29/2022, 11:36 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by jfversluis** [comment] 2022-06-16 09:39
Duplicate of #5931

**Closed by jfversluis** 2022-06-16 09:39 UTC
