### ISSUE TITLE
Label text overlap in HorizontalStackLayout

### ISSUE THREAD

**Issue by MarMarIV** [dotnet/maui#22130] opened 2024-04-30 04:39 UTC
### Description

Label text is overlaping in HorizontalStackLayout

![image](https://github.com/dotnet/maui/assets/10964247/2a9283b9-2a94-4715-98e0-cf1d07507ee8)

### Steps to Reproduce

1. Clone repo
2. Run app

### Link to public reproduction project repository

https://github.com/MarMarIV/MAUI-Issue-16658

### Version with bug

8.0.21 SR4.1

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

**Comment by Zhanglirong-Winnie** [comment] 2024-04-30 04:53
Verified this issue with Visual Studio 17.10 Preview 5 (8.0.21&8.0.14&8.0.3). Can repro on android platform with sample project.

**Comment by MarMarIV** [comment] 2024-04-30 07:38
This (similar) problem has already been mentioned under https://github.com/dotnet/maui/issues/16658#issuecomment-1682613972

According to the attached screen shot you can see the parent "blue" element which is aligned on the page fine

However, the "red" element overlaps the parent

I don't think this is the correct behavior for HorizontalStackLayout

If I wanted to achieve this, I would use AbsoluteLayout/FlexLayout

Translated with DeepL.com (free version)

**Comment by PureWeen** [comment] 2024-08-07 20:08
Duplicate of #23448

**Closed by PureWeen** 2024-08-07 20:08 UTC
Labels: t/bug, area-layout, platform/android 🤖, platform/iOS 🍎, legacy-area-controls, s/verified, s/triaged
