### ISSUE TITLE
Displaying badge on shell tabbar icon 

### ISSUE THREAD

**Issue by MohammdaSalah** [dotnet/maui#12525] opened 2023-01-09 18:04 UTC
### Description

We would love to  have number badge appear on shell tab bar, this is informative that shows to user any new items.

### Public API Changes

No api

### Intended Use-Case

No api

**Comment by jfversluis** [comment] 2023-01-09 19:06
Duplicate of #8305

**Closed by jfversluis** 2023-01-09 19:06 UTC
Labels: proposal/open

**Comment by victordscott** [comment] 2023-01-22 03:48
I would like to know why this is not planned.  This is obviously needed.
