### ISSUE TITLE
Wear OS/WatchOS support

### ISSUE THREAD

**Issue by Laftek** [dotnet/maui#4852] opened 2022-02-23 12:46 UTC
### Description

Do you plan to support Wear OS and WatchOS with MAUI?

### Public API Changes

N/A

### Intended Use-Case

To be able to create apps with MAUI for smartwatch.

**Comment by jfversluis** [comment] 2022-02-23 13:47
Duplicate of https://github.com/dotnet/maui/discussions/1144

We have no immediately plans to support that any more than we do today. Upvote the discussion to show your interest in this!

**Closed by jfversluis** 2022-02-23 13:47 UTC
Labels: proposal/open
