### ISSUE TITLE
Making previously hidden Border visible has a "jelly effect" on iOS

### ISSUE THREAD

**Issue by RsZoli** [dotnet/maui#24311] opened 2024-08-19 15:39 UTC
### Description

When making a Border visible, using binding to the IsVisible property makes the Border not just appear as it should, but appear in a huge size and resizing to the desired size with some kind of "jelly effect"!

At the moment of setting the property to true, it has 0 height with thicker border than the set value, then its height will grow to an unknown value and then as its height starts slowly decrese to its content, the border get thinner as well!

It is really wierd, here is a breakdown of what i described:

![image](https://github.com/user-attachments/assets/21beb83a-203f-4083-9b37-88529c40596d)

Also, here is a video of the effect:

https://github.com/user-attachments/assets/09097c1c-2b4c-4cf1-b4f7-86f7e2a0371c

I'm absolutely sure it wasn't like this before!

### Steps to Reproduce

1. Create a new .NET MAUI application
2. Add a Border control with some content inside it to the MainPage
3. Bind the border's IsVisible property and set it to False initially
4. Set the property to True after some event

### Version with bug

8.0.80 SR8

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 17.6.1

### Did you find any workaround?

Sadly, no!

**Comment by PureWeen** [comment] 2024-08-19 17:18
@RsZoli is this the same issue as seen here?
https://github.com/dotnet/maui/issues/21643

**Comment by RsZoli** [comment] 2024-08-19 17:21
@PureWeen no, it is this one: https://github.com/dotnet/maui/issues/24104

**Comment by PureWeen** [comment] 2024-08-23 18:21
Duplicate of #24104

**Closed by PureWeen** 2024-08-23 18:21 UTC
Labels: t/bug, platform/iOS 🍎, s/triaged, s/needs-attention, potential-regression
