### ISSUE TITLE
Error on Visual Studio Mac (Latest Version)

### ISSUE THREAD

**Issue by raselldev** [dotnet/maui#15181] opened 2023-05-19 14:29 UTC
### Description

I have visual studio mac 2022 on latest version. The problem is i can't build iOS because my XCode version is 14.2 (visual studio need version of XCode on 14.3)

Visual studio can't provide Microsoft.iOS while XCode version is 14.2

### Steps to Reproduce

1. Create file
2. Check TargetFrameworks
3. NET Framework is 6.0
4. Debugger can't show iOS Device on 16.2
5. My MacOS is MacOS Monterey -> Macbook Pro Touchbar 13 2016

![Screen Shot 2023-05-19 at 21 24 21](https://github.com/dotnet/maui/assets/29136223/814eed6b-d2a3-4fb9-bd8f-cc4dfff4c0da)
![Screen Shot 2023-05-19 at 21 24 07](https://github.com/dotnet/maui/assets/29136223/530b006e-652a-4339-842b-9aa4242cd763)
![Screen Shot 2023-05-19 at 21 23 58](https://github.com/dotnet/maui/assets/29136223/013e9732-3b5a-47ac-b920-6d8bea30aacf)

The Platform keep using NET 7 while i using NET 6 on my project

### Link to public reproduction project repository

No Project link

### Version with bug

7.0.86

### Last version that worked well

6.0

### Affected platforms

iOS

### Affected platform versions

iOS 16.4

**Comment by jfversluis** [comment] 2023-07-05 12:55
I'm sorry but I'm not really sure what the issue is. It's also already a bit older by now. I'm going to be optimistic and assume you found a resolution for now and close this. If that's not the case, please feel free to open something new. Thanks!

**Closed by jfversluis** 2023-07-05 12:55 UTC
Labels: t/bug, area/tooling ⚙️, s/move-to-vs-feedback
