### ISSUE TITLE
Shell and TabbedPage

### ISSUE THREAD

**Issue by ismlsmile** [dotnet/maui#18974] opened 2023-11-23 09:34 UTC
### Description

According to the document (https://learn.microsoft.com/en-us/dotnet/maui/user-interface/pages/tabbedpage?view=net-maui-8.0), TabbedPage is incompatible with .NET MAUI Shell apps, and an exception will be thrown if you attempt to use TabbedPage in a Shell app. But if there is a requirement: click a button in a content page, then navigate to a tabbed page, how to do this? Now any project created by VS is default to Shell apps.

### Public API Changes

no

### Intended Use-Case

let Shell and TabbedPage work together

**Comment by PureWeen** [comment] 2023-12-07 20:43
Duplicate of #6389

**Closed by PureWeen** 2023-12-07 20:43 UTC
Labels: proposal/open, area/shell 🐢
