### ISSUE TITLE
Maui.Storage.Preferences.Get when supplied with default value still returns null

### ISSUE THREAD

**Issue by srqdevg** [dotnet/maui#9945] opened 2022-09-06 13:04 UTC
### Description

If I try to fetch a preference value using the GET method, where I supply a default string value but I know the key does not yet exist I would expect the default value to be returned, instead I get a null value.

### Steps to Reproduce

1. In a Maui App add 'var test = Preferences.Get("keyname", "defaultValue");
2. Run the code and check the value of test, it should be defaultValue but instead it is null.

### Link to public reproduction project repository

.

### Version with bug

6.0 Release Candidate 3

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows SDK for Windows 11 (10.0.22621.1)

### Did you find any workaround?

I will use an old style db driven preferences store

**Comment by jfversluis** [comment] 2022-09-06 13:14
Duplicate of #9338

**Closed by jfversluis** 2022-09-06 13:14 UTC
Labels: t/bug
