### ISSUE TITLE
SearchHandler in Shell on iOS Crashes 

### ISSUE THREAD

**Issue by bwinklesky** [dotnet/maui#16550] opened 2023-08-04 17:51 UTC
Using the "Xaminals" project from the "maui-samples" repository you can reproduce the error by Searching for an animal.  Same code works fine on Android.  

It's also reproducable in projects other than "Xaminals" project using the same implementation.  

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Maui.Controls.ViewExtensions.GetParentsPath(Element self)+MoveNext()
   at Microsoft.Maui.Controls.ViewExtensions.FindMauiContext(Element element, Boolean fallbackToAppMauiContext)
   at Microsoft.Maui.Controls.Platform.Compatibility.UIContainerCell..ctor(String cellId, View view, Shell shell, Object context)
   at Microsoft.Maui.Controls.Platform.Compatibility.UIContainerCell..ctor(String cellId, View view)
   at Microsoft.Maui.Controls.Platform.Compatibility.ShellSearchResultsRenderer.GetCell(UITableView tableView, NSIndexPath indexPath)
   at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName)
   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass)
   at Xaminals.Program.Main(String[] args) in /Volumes/SSD/Projects/maui-samples/7.0/Fundamentals/Shell/Xaminals/Platforms/iOS/Program.cs:line 13
```

**Comment by samhouts** [comment] 2023-08-28 20:49
Duplicate of #16297

**Closed by samhouts** 2023-08-28 20:49 UTC
Labels: t/bug, platform/iOS 🍎, area/shell 🐢, high
