### ISSUE TITLE
.Net 8P4 WPF/Maiu can't load Blazor Router

### ISSUE THREAD

**Issue by IvanJosipovic** [dotnet/maui#15287] opened 2023-05-26 00:35 UTC
### Description

Since .Net 8 Preview 4, Maui and WPF/Forms can not load a Blazor Router

It looks like the package loads the wrong transitive dependency
![image](https://github.com/dotnet/maui/assets/9521987/2bfc758a-9a76-449a-bc88-ccb066f61db3)

### Steps to Reproduce

Check out the repo repository, attempt to run the WpfApp1

### Link to public reproduction project repository

https://github.com/IvanJosipovic/Net8P4BlazorBug

### Version with bug

8.0.0-preview.4.8333

### Last version that worked well

8.0.0-preview.3.8149

### Affected platforms

Windows

### Affected platform versions

WPF and MAUI

### Did you find any workaround?

adding the following package to the project fixes the issue, 

    <PackageReference Include="Microsoft.AspNetCore.Components.WebView" Version="8.0.0-preview.4.23260.4" />

### Relevant log output

```shell
InvalidOperationException: Cannot provide a value for property 'ScrollToLocationHash' on type 'Microsoft.AspNetCore.Components.Routing.Router'. There is no registered service of type 'Microsoft.AspNetCore.Components.Routing.IScrollToLocationHash'.
```
```

**Comment by mkArtakMSFT** [comment] 2023-05-31 16:56
Looks like a broken dependency in the package: https://www.nuget.org/packages/Microsoft.AspNetCore.Components.WebView.Wpf/8.0.0-preview.4.8333#dependencies-body-tab

**Comment by Eilon** [comment] 2023-06-07 17:52
@IvanJosipovic thank you for the report, I can confirm that this is a problem. It seems that all the 8.0 preview packages for Blazor Hybrid for WPF and Windows Forms have similar problems. Fortunately, the workaround is exactly as you've discovered: add an explicit reference to the correct `Microsoft.AspNetCore.Components.WebView` package version.

I'm trying to figure out what caused the problem originally and whether it's already fixed for upcoming releases.

**Comment by Eilon** [comment] 2023-06-07 21:38
It looks like this has since been fixed.

* **[BAD]** Blazor WebView WPF/WinForms Preview3 was referencing Blazor Preview2: https://github.com/dotnet/maui/blob/release/8.0.1xx-preview3/eng/Versions.props#L38
* **[BAD]** Blazor WebView WPF/WinForms Preview4 was referencing Blazor Preview2: https://github.com/dotnet/maui/blob/release/8.0.1xx-preview4/eng/Versions.props#L38
* **[GOOD]** Blazor WebView WPF/WinForms Preview5 was referencing Blazor Preview5: https://github.com/dotnet/maui/blob/release/8.0.1xx-preview5/eng/Versions.props#L38
* **[GOOD]** Blazor WebView WPF/WinForms Current (Preview6) is referencing Blazor Preview6: https://github.com/dotnet/maui/blob/net8.0/eng/Versions.props#L38

So, I'm closing this issue because going forwards it looks like we're in good shape. Thanks for the great bug report!

**Closed by Eilon** 2023-06-07 21:38 UTC
Labels: t/bug, area/blazor 🕸️
