### ISSUE TITLE
MAUI Permission for Write Storage is always Denied in Android

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#24173] opened 2024-08-12 22:19 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/MAUI-Permission-for-Write-Storage-is-alw/10710827)._

---
MAUI Permission for Write Storage is always Denied in Android . I M using  a  android device with android 14 and API-34. May Anybody suggest what might be issue related to it

---
#### Feedback Bot on 7/28/2024, 06:24 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by jfversluis** [comment] 2024-08-13 08:37
Duplicate of #14729

**Closed by jfversluis** 2024-08-13 08:37 UTC
Labels: t/bug
