### ISSUE TITLE
FlyoutPage.IsPresented=false throws InvalidOperationException: 'Can't change IsPresented when setting Default'

### ISSUE THREAD

**Issue by rmotta01** [dotnet/maui#11785] opened 2022-12-01 11:39 UTC
### Description

Actually, it depends on the window width. When FlyoutLayoutBehavior="Default", but the window is narrow, the flyout behaves as Popover and IsPresented=false works, when the window is wide, throws the exception.

### Steps to Reproduce

Run your FlyoutPage sample on Windows, select an item on the flyout.
https://github.com/dotnet/maui-samples/tree/main/6.0/Navigation/FlyoutPageSample

### Link to public reproduction project repository

https://github.com/dotnet/maui-samples/tree/main/6.0/Navigation/FlyoutPageSample

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

windows10.0.19041.0

**Comment by breenbob** [comment] 2023-02-23 14:21
Can this fix be backported to .Net 7 when approved? It's affecting an ongoing project of ours. Thanks.

**Comment by mnxamdev** [comment] 2023-06-14 21:01
This is happening for me on iPads in Landscape mode. Do we know when it will be fixed?

**Comment by kyurkchyan** [comment] 2023-06-19 06:49
I bumped across this same issue when migrating Xamarin.Forms to .NET MAUI.

**Comment by DanTravison** [comment] 2023-06-24 14:11
Is there any workaround for this issue?  I'm also seeing it when building https://github.com/dotnet/maui-samples/tree/main/7.0/Navigation/FlyoutPageSample on Windows with no changes.

I would expect a basic demo of a feature to work with the current version; otherwise, what's the point of the demo?

**Comment by kyurkchyan** [comment] 2023-08-09 05:46
This issue is a dealbreaker for us. We were migrating to .NET MAUI from Xamarin.Forms and our app, while running on iPad makes heavy use of a Flyout Page. Because of this bug (and many others), we abandoned the idea of .NET MAUI migration until a better day came.

**Comment by axa88** [comment] 2023-09-04 04:10
Also fwiw, ive found this odd behavior.

On WinUI, `FlyoutPage.FlyoutLayoutBehavior` always reports as `Default` regardless what it is set to, and regardless of how the Flyout page actually behaves.
Regardless of windows size. Regardless when only the `Detail` page is displayed and `IsPresented` is `false` which behavior is obviously `Popover`, it reports `Default`.
Regardless when both `Flyout `and `Detail` pages are displayed and `IsPresented` is `true`, which behavior is obviously one of the `Split` modes, it always reports `Default`.

Where on Android `FlyoutLayoutBehavior` reflects whatever `FlyoutLayoutBehavior` it was set to.  But again actual behavior might be something else entirely.

So while restrictive behavior may well make sense for any individual platform, `FlyoutLayoutBehavior` should not be reporting current behavior it is not.  And imho unless maintainers are prepared to document exactly what default is on every hardware/platform, `Default` should not even be a reported behavior.  Set = Default, yes. Get = Default, never.
 
Of course i have no specific description of `FlyoutLayoutBehavior` was designed to work on each platform, as the [official Documentation](https://learn.microsoft.com/en-us/dotnet/api/microsoft.maui.controls.flyoutpage?view=net-maui-7.0) makes no mention of that. But the objective description above demonstrates how it appears to _not work_ or rather work inconsistent and poorly.

**Comment by imuller** [comment] 2023-10-09 14:36
Microsoft why don't fix this in .NET 7? Now we need to wait for .NET 8 release and hope there is nothing wrong there...

**Closed** 2023-12-08 01:01 UTC
Labels: t/bug, platform/windows 🪟, p/1, area/FlyoutPage, control-flyout, s/try-latest-version, migration-compatibility

**Comment by axa88** [comment] 2023-12-09 23:02
> Also fwiw, ive found other aspects of this Flyout page broken.
> 
> On Android while `FlyoutPage.FlyoutLayoutBehavior` always reports to what it is _set_ to, regardless of properties such as window orientation or split screen, _actual_ behavior is only ever `Popover`.
> 
> Where on WinUI, `FlyoutPage.FlyoutLayoutBehavior` also always reports as what it is set to, but only behaves as `Popover` or `Split`. And while in `Popover`, `IsPresented` is always `true`... even when `FlyoutPage.Flyout `is NOT presented, which is just broken.
> 
> So while it may make sense for the framework to restrict behaviors on individual platforms, `FlyoutLayoutBehavior` should always report the actual behavior. And IMHO unless maintainers are prepared to document exactly what default is on every hardware/platform, `Default` should not even be a reported behavior. Set = `Default`, ok maybe. Get = `Default`, never, it should reflect the _actual_ behavior whatever it is.
> 
> Of course i have no specific description of how `FlyoutLayoutBehavior` was designed to work on any platform, as the [official Documentation](https://learn.microsoft.com/en-us/dotnet/api/microsoft.maui.controls.flyoutpage?view=net-maui-7.0) makes no mention of it. But the objective description above demonstrates how it appears to very much _not_ work, or rather, work inconsistent/poorly.

Each of these issues is fixed with .NET 8
