### ISSUE TITLE
[Feature Request] Windows Toolbar items Remove the 3 dots to access the toolbar item

### ISSUE THREAD

**Issue by davidbuckleyni** [dotnet/maui#7034] opened 2022-05-11 16:20 UTC
### Description

In Maui as it stands at present when you declare a toolbar item you have to declare it as such

```
<ContentPage.ToolbarItems>
    <ToolbarItem Text="Add Sales Order"
                           IsEnabled="True"
                           Order="Primary"
                           Priority="0" />
</ContentPage.ToolbarItems>
```

Which is fine but the issue is that you must click the 3 dots before the toolbar item is visible 

![image](https://user-images.githubusercontent.com/5619229/167898772-8287fda3-08ff-41e5-9a2d-c6e46b5fd442.png)

This is not very user friendly

### Public API Changes

```
<ContentPage.ToolbarItems>
        <ToolbarItem Text="Add Sales Order"
                               IsEnabled="True"
                               IsOpened="True" // New feature here would get rid of the three dots
                               Order="Primary"
                               Priority="0" />
</ContentPage.ToolbarItems>
```

I am suggesting a IsOpened="True" to remove the three dots and thus showing the item without having to click the three dots to make is visible.

### Intended Use-Case

This improves the user experience not having to hunt where is the function

**Comment by SunshineSpring666** [comment] 2022-11-16 05:16
Hi there, 
Similar situation encountered here. The 3-dots button is always shown on Windows, even if the page's title bar layout doesn't need it.
Note that I arrange the title bar region using NavigationPage.TitleView instead of ContentPage.ToolbarItems. But these 3-dot menu button actually moves the title region downward/upward a little bit when the drop down menu initially is closed.
Thanks.

**Comment by holecekp** [comment] 2022-11-30 05:10
I have the same problem. The toolbar is unusable in MAUI on Windows in its current form. This bug manifests itself in even more ways than described in the issue description:

- Not only that the primary items are accessible inside the 3 dots menu as described in this issue, the other problem is that empty buttons are also created for them next to the three dots icon. So you can access them by clicking next to the 3 dots icon (but the text is inivisible). See https://github.com/dotnet/maui/issues/11639 for screenshots. This can be actually dangerous because the users could click on them by mistake (when they cannot see them) and activate a function that they did not wanted.
 
- Moreover, secondary items are also displayed incorrectly. When you click on the tree dots icon, a menu is opened but there are no texts inside! The text becomes only temporarily visible when you move mouse over it. The texts for other secondary items are still hidden. This makes also secondary toolbar items unusable on Windows. Again you can look at https://github.com/dotnet/maui/issues/11639 for screenshots. That issue describes bugs in toolbar in more detail with a repro project (things that used to work in Xamarin.Forms but do not work in MAUI) but it was closed as a duplicate to this one.

**Comment by PureWeen** [comment] 2022-12-13 21:06
Duplicate of #12063

**Closed by PureWeen** 2022-12-13 21:06 UTC
Labels: proposal/open, area/controls 🎮, control-menubar
