### ISSUE TITLE
Photo orientation

### ISSUE THREAD

**Issue by williambuchanan2** [dotnet/maui#14607] opened 2023-04-17 01:56 UTC
### Description

Taking a photo seems to result in random orientation. Sometimes the top is at the bottom. Sometimes it is on the side.

Need some way to get a photo with the top at the top - either it comes out that way or we have some method to flip it as required.

### Steps to Reproduce

Use either ImagePicker or ImageGallery to take a photo.
Try this with the phone in the 4 different orientations - i.e. portrait, landscape, portrait upside down, landscape upside down.

Notice how you end up with photos in the wrong orientation and no way to know how to get it the right way up.

### Link to public reproduction project repository

?

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

Android 11 - 13, iOS 16

### Did you find any workaround?

No

**Comment by drasticactions** [comment] 2023-04-17 05:42
Duplicate of https://github.com/dotnet/maui/issues/9535

**Closed by drasticactions** 2023-04-17 05:42 UTC
Labels: t/bug, s/duplicate 2️⃣

**Comment by drasticactions** [comment] 2023-04-17 05:43
You can read that issue for more information, but in short, you may want to use [MediaGallery](https://github.com/dimonovdd/Xamarin.MediaGallery) instead.

**Comment by williambuchanan2** [comment] 2023-04-17 05:55
> You can read that issue for more information, but in short, you may want to use [MediaGallery](https://github.com/dimonovdd/Xamarin.MediaGallery) instead.

MediaGallery has the same problem so unfortunately that isn't an option either.

**Comment by drasticactions** [comment] 2023-04-17 06:00
https://github.com/dotnet/maui/pull/14568

**Comment by williambuchanan2** [comment] 2023-04-17 06:08
> This directly adds normalization, and it's attached to the other issue. #14568

Sorry - i'm not sure I follow. That link is for MediaPicker - so looks like when that is released it will work (providing the other problem with MediaPicker permissions is also addressed). Are you saying MediaGallery currently works? That's not what I am seeing right now. Do I need to do something to make it work?
Thanks
