### ISSUE TITLE
The prompts displayed by DisplayAlert do not follow the theme set

### ISSUE THREAD

**Issue by emorell96** [dotnet/maui#6092] opened 2022-04-14 08:55 UTC
### Description

The prompts displayed by DisplayAlert do not adhere to the theme set by using `Application.Current.UserAppTheme`.

![image](https://user-images.githubusercontent.com/20151415/163350196-fe90a09f-1531-4c2f-a9ba-5ea60b22a0d7.png)

### Steps to Reproduce

1. Set the theme to dark using `Application.Current.UserAppTheme = AppTheme.Dark;`
2. Send a DisplayAlert on the main page on Android. The theme will not be respected and it will use the default light theme.

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

API 30, Android 11

**Comment by kristinx0211** [comment] 2022-04-18 05:42
@emorell96 Thank you so much for your bug report! Unfortunately, we cannot reproduce your issue with the information above, could you provide a sample project/screenshots or more details that we can reproduce your issue? That should greatly speed up the process, thanks!

**Comment by mtanml** [comment] 2022-10-13 21:57
Hi, I'm not sure I understand why #7601 was closed as a duplicate of this issue... it is a completely separate issue that I am experiencing as well.   On a device set to dark mode, DisplayAlert is presented with a dark gray background and dark (purple?) text that is barely readable.   Has a workaround been identified for that issue?   Thanks

**Comment by LaraSQP** [comment] 2022-12-09 23:59
THIS IS A BIG PROBLEM.

**Comment by jerry08** [comment] 2023-01-04 13:56
`Application.Current.UserAppTheme` only applys for the theme defined with `AppThemeBinding` as mentioned in [this post](https://stackoverflow.com/a/69128632). That means `DisplayAlert`, `Picker`, etc. don't inherit the specified theme. To fix this problem, make sure to call this method when switching themes:

```
#if ANDROID
            AndroidX.AppCompat.App.AppCompatDelegate.DefaultNightMode = Current.UserAppTheme switch
            {
                AppTheme.Light => AndroidX.AppCompat.App.AppCompatDelegate.ModeNightNo,
                AppTheme.Dark => AndroidX.AppCompat.App.AppCompatDelegate.ModeNightYes,
                _ => AndroidX.AppCompat.App.AppCompatDelegate.ModeNightFollowSystem
            };
#elif IOS
            Platform.GetCurrentUIViewController().OverrideUserInterfaceStyle = Current.UserAppTheme switch
            {
                AppTheme.Light => UIKit.UIUserInterfaceStyle.Light,
                AppTheme.Dark => UIKit.UIUserInterfaceStyle.Dark,
                _ => UIKit.UIUserInterfaceStyle.Unspecified
            };
#endif
```

I haven't tested on iOS but it should work.

**Comment by LaraSQP** [comment] 2023-01-04 20:33
Much appreciated. You rock, sir.

**Comment by SurkusGH** [comment] 2023-01-21 10:35
So is there any solution for this? Since the one above is for xamarin forms?

**Comment by SurkusGH** [comment] 2023-01-21 11:45
Okay, so just go:

$"[YourProject]"/Platforms/Android/Resources/values/colors. Change it there. That is it.

**Comment by jerry08** [comment] 2023-01-21 14:06
The solution I mentioned is for both xamarin and MAUI. It works fine for me. From my knowledge, changing the values in `Platforms/Android/Resources/values/colors.xml` only changes the default button color in the dialog and in a few other areas. It doesn't change the dialog color.

I created a plugin that handles some workarounds (maui).  If you want, you can check it out [here](https://github.com/jerry08/Woka).

**Closed** 2023-03-14 09:40 UTC
Labels: t/bug, area/controls 🎮, s/verified, control-dialogalert
