### ISSUE TITLE
[regression/8.0.3] Navigation Toolbar broken

### ISSUE THREAD

**Issue by SergTomcat** [dotnet/maui#18902] opened 2023-11-20 13:58 UTC
### Description

In Android, Navigation toolbar stuck and not change, or change erratically:
- Navigation.SetTitleView not working second time
- ToolbarItems not changing
- Toolbar not hide when Detail of FlyoutPage is set to non NavigationPage page.
- "Back" button in navigation stack page behaves like "hamburger" button

[Showcase](https://github.com/dotnet/maui/assets/24654961/79b50d12-d574-4b14-8ee3-31a58fa96918)

iOS works fine.

### Steps to Reproduce

1. Create FlyoutPage with few pages
2. Add different ToolbarItems to pages
3. Use Navigation.SetTitleView to customize toolbar
4. Set NavigationPage and ContentPage to FlyoutPage Detail
5. Push page to NavigationStack and try to return back via "←" button

Expected outcome: Navigation Toolbar works like in .net7
Actual outcome: see description

### Link to public reproduction project repository

https://github.com/SergTomcat/MAUI8_BugDemo2

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.101

### Affected platforms

Android

### Affected platform versions

Android 9.0 and up to 14.0

### Did you find any workaround?

No workaround was found

**Comment by SmartmanApps** [comment] 2023-11-21 05:33
Can confirm I have same/similar issue with SetTitleView and Flyout pages on both Android and Windows. I have each page in a NavigationPage, and further to that I use the ellipsis menu (ToolBatItems) menu too, but in that case what I do with my pages is PushModalAsync. When I do that the TitleBar works as expected, but when I switch pages using Flyout menu then the second page has the same TitleBar as the first page I was on, even though they are each in a separate NavigationPage. In fact, when I first checked this out, the second page I hadn't even implemented SetTitleView yet on it, I still had it using Title, and yet despite that it didn't show the Title, it showed the TitleView from the first page. Then I did implement SetTitleView on that page too, but same behaviour - shows  the TitleView from the first page, instead of it's own.

**Comment by SmartmanApps** [comment] 2023-11-22 05:37
Further info: I decided to change my approach to try and work around this (apparent) SetTitleView bug, only to find it's not specific to SetTitleView, so apparently no workaround. First I removed the SetTitleView from the page I was going to experiment with, and ran the app to check I had a blank TitleBar - yep - and then I switched via the Flyout menu to my unchanged page, which ALSO had a blank TitleBar! (should've had it's own Title showing) So regardless of how you set the Title, whatever the Title is on the first page you open, every other page will have that same Title (even, as I said before, if they're in individual NavigationPages). So the bug is specific to Flyout pages (my ellipsis menu pages, which I use PushModalAsync with, are fine).

**Comment by berhir** [comment] 2023-11-22 07:10
looks like the same issue as #18830 (it's already fixed in nightly builds)

**Comment by SmartmanApps** [comment] 2023-11-22 07:16
Thanks for that @berhir - do we have an idea of roughly how long before that comes through to a service release?

**Comment by OfficialNoFocus** [comment] 2023-11-29 11:19
Its nice to see that i am not the only one with this problem inside of .NET8.

Is there a time line on when this fix will be released?

**Comment by Todd102030** [comment] 2024-03-26 20:38
This seems to still be broken on Maui 8.0.14. My first page has two ToolbarItems set, both with an IconImageSource. The second page also has two ToolbarItems, one with an IconImageSource set, and one with just Text. When switching to the second page in the Flyout menu, the icon from the first page remains. It appears to call the correct Command from the second page still, but it shows an incorrect icon while doing so

**Comment by PureWeen** [comment] 2024-03-27 20:11
@Todd102030 

Can you test with the latest nightly build? 
https://github.com/dotnet/maui/wiki/Nightly-Builds

If it's still not working for you can you attach a repro?

I've tested the repro attached to this issue and I can't reproduce this.

**Closed** 2024-05-18 09:06 UTC
Labels: t/bug, platform/android 🤖, area-navigation, partner/cat 😻, s/try-latest-version, area-controls-toolbar, potential-regression
