### ISSUE TITLE
HotReload not working for changes to VerticalOptions

### ISSUE THREAD

**Issue by BenBtg** [dotnet/maui#10122] opened 2022-09-14 13:39 UTC
### Description

UI does not update when changing VerticalOptions of a VerticalStackLayout.

### Steps to Reproduce

1. Create new MAUI Temaplate App
2. Run in debug Targeting Windows
3. Confirm HotReload works for Text change
4. Change VerticalOptions to Start

Expected : Layout is Aligned to Top
Actual: Nothing happens

Workaround: Change VerticalStackLayout to HorizontalStackLayout and back. HotReload is then forced.

### Link to public reproduction project repository

New MAUI Template App

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

10.0.1904

### Did you find any workaround?

Change VerticalStackLayout to HorizontalStackLayout and back. HotReload is then forced.

**Comment by drasticactions** [comment] 2022-09-14 14:44
I believe the same thing happens if you try making the change via changing the property values directly via C# Code Behind, and not just through XAML Hot Reload. The value is changing, but the view is not being reloaded.

I don't think this is a tooling issue, it's a MAUI one.

**Comment by jinxinjuan** [comment] 2023-05-25 07:35
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 1.0. Can repro on Windows platform with above project. [MauiApp10.zip](https://github.com/dotnet/maui/files/11560787/MauiApp10.zip)
![image](https://github.com/dotnet/maui/assets/37974803/d25a06f2-cac6-4ea5-b7fb-9bdcb39d0c5f)

**Comment by drasticactions** [comment] 2023-05-25 11:08
I believe this is a duplicate of https://github.com/dotnet/maui/issues/14377

Layouts inside of ScrollView's, on WinUI, are not updated until forced via a redraw on the screen. This is not a Hot Reload issue, you can reproduce this via code-behind.

**Comment by spadapet** [comment] 2023-08-18 22:20
@chabiss I verified that this is a dupe of #14377, just like Tim said. Without the ScrollViewer, this bug doesn't repro. Another workaround is to resize the window to force layout.
So Charles, you can resolve this is a dupe, give this one to Tim too, or take his ScrollViewer bug... so many options!

**Comment by chabiss** [comment] 2023-08-29 17:45
Dupe of #14377

**Closed by chabiss** 2023-08-29 17:45 UTC
Labels: t/bug, area/Xaml </>, area/layout 🔲, area/tooling ⚙️, partner, partner/ui-tools, p/2, s/verified, s/triaged, partner/hot-reload-xaml
