### ISSUE TITLE
IImage.ResizeImage() always disposes of bitmap on Android

### ISSUE THREAD

**Issue by dharber** [dotnet/maui#7125] opened 2022-05-13 04:27 UTC
### Description

`IImage image = PlatformImage.FromStream(someStreamAcquiredFromHttpClient);
var newImage = image.Resize(width, height, ResizeMode.Fit, false);'

newImage is already disposed. I can't examine its contents in the debugger (it says it's been disposed) and if I try to use it in a DrawImage() method, an exception is thrown.

It appears that on Android, PlatformImage.Resize() creates a PlatformBitmapExportContext which has a dispose parameter that defaults to true but Resize() doesn't pass in any value to override that. I'm not 100% certain about the flow of things but it seems like that's the problem.

### Steps to Reproduce

See above

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11 (I think)

### Did you find any workaround?

Not yet

**Comment by janseris** [comment] 2022-05-13 06:39
https://github.com/dotnet/maui/issues/6909

**Comment by jfversluis** [comment] 2022-05-13 14:48
Duplicate of #6909

**Closed by jfversluis** 2022-05-13 14:48 UTC
Labels: t/bug, s/needs-verification

**Comment by dharber** [comment] 2022-05-13 19:31
Odd, I searched for any similar issues but nothing came up. Sorry about that. I tried, though :-)
