### ISSUE TITLE
.NET MAUI Picker ItemsSource binding failed

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#9496] opened 2022-08-17 17:39 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/NET-MAUI-Picker-ItemsSource-binding-fai/10116249)._

---
[severity:It's more difficult to complete my work] [regression] [worked-in:17.3.0 Preview 5]
After update Picker in .NET MAUI stopped binding ItemsSource. I tried with List and ObservableCollection. Before update binding was working fine.

---
#### Feedback Bot on 8/10/2022, 11:05 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by MagicAndre1981** [comment] 2022-08-19 13:29
(Possible) Duplicate of https://github.com/dotnet/maui/issues/9239

**Closed** 2022-08-23 10:52 UTC
Labels: t/bug, s/duplicate 2️⃣, area/controls 🎮, control-picker
