### ISSUE TITLE
Magic error

### ISSUE THREAD

**Issue by scriptBoris** [dotnet/maui#21810] opened 2024-04-13 05:24 UTC
### Description

Any MAUI ios develpers here? I pair my windows 11 PC to MAC, trying to debug and i see:

A bundle identifier is required. Either add an 'ApplicationId' property in the project file, or add a 'CFBundleIdentifier' entry in the project's Info.plist file.	Sample	C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\17.2.8004\tools\msbuild\iOS\Xamarin.Shared.targets	612 

The problem disappeared randomly after I restarted ALL but it's not disappearing now. I'm tired of these errors. NET MAUI has been around for a long time. But it's still a beta test. 

### Steps to Reproduce

1 create any project net maui 1
2 starting debug
3 end debug
4 create any project net maui 2
5 starting debug
6 ERROR
7 or random error in steps 1-7

### Version with bug

Unknown/Other

### Is this a regression from previous behavior?

No, this is something new, Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

**Comment by jfversluis** [comment] 2024-04-15 07:38
While I'd love to look into this more without any reproducible steps it will be very hard to do. I tried going through what you have described and it works for me every time, I have never noticed this before.

Additionally, not specific .NET MAUI version or Visual Studio version is mentioned which makes it very hard to tell what might be going on here.

Thank you so much for the report, I'll be closing this for now assuming this is something that accidentally happened. If you run into it again please let us know and try to provide us with more details. Thanks!

**Closed by jfversluis** 2024-04-15 07:38 UTC
Labels: t/bug
