### ISSUE TITLE
Navigating to Page which is using DI with DataTemplate causes error

### ISSUE THREAD

**Issue by Jeremiad** [dotnet/maui#9565] opened 2022-08-20 19:46 UTC
### Description

According to issue https://github.com/dotnet/maui/issues/4072 this was supposed to be fixed in P12, but issue still seems to be in current version.

### Steps to Reproduce

**Steps to Reproduce**

1. Create a new Maui application.
2. Tailor it to support Shell with one or more Tab pages whose ShellContent DataTemplate references a view model in the constructor.
3. Register the view model in MauiProgram.cs.
4. Build and run the app.
5. See stack trace below for the resulting crash.

Reproduce example: 
[DIissue.zip](https://github.com/dotnet/maui/files/9387933/DIissue.zip)

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Windows SDK 10.0.22621

**Comment by mattleibow** [comment] 2022-08-22 15:02
I believe this is a duplicate of #5398:

> In order to use constructor injection with ContentPages in the context of Shell, you'll need to register them [pages] with DI just like you have your view models.

**Closed by mattleibow** 2022-08-22 15:02 UTC
Labels: t/bug, platform/windows 🪟, area/navigation 🧭

**Comment by Jeremiad** [comment] 2022-08-22 16:46
@mattleibow Thanks that was the issue. Somehow missed that :)
