### ISSUE TITLE
Error strip 139 with build net maui IOS vs 2022 net 9.0

### ISSUE THREAD

**Issue by skyangel78** [dotnet/maui#26430] opened 2024-12-06 14:40 UTC
### Description

Hi,
i've vs2022 installed on window pc and from here must o build project net maui with net 9.0.
Now my win pc is connect in remote to mac where is installed xcode version 16. But when start to build project before to end i see the error  number strip 139. (C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net9.0_18.1\18.1.9163\tools\msbuild\iOS\Xamarin.Shared.targets(2923,3)). Now i've disabled LLVM but nothing. How can i to resolve this error?

Thank you

### Version with bug

9.0.10 SR1

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

9.0.10 SR1

### Affected platforms

iOS

### Affected platform versions

IOS 18

### Relevant log output

```shell

```

**Comment by jfversluis** [comment] 2024-12-06 15:11
Duplicate of #26369

**Closed by jfversluis** 2024-12-06 15:11 UTC
Labels: t/bug
