### ISSUE TITLE
Adding rows and columns programmatically in .NET MAUI Grid Types does not work

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#13923] opened 2023-03-14 16:44 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Adding-rows-and-columns-programmatically/10284044)._

---
[severity:It's more difficult to complete my work]
.NET MAUI allowed for adding rows and columns within c# code. The latest release of, .NET MAUI Microsoft Visual Studio Community 2022 (64-bit) - Current Version 17.4.3 causes an error:
Error CS1501 No overload for method 'Add' takes 3 arguments CollecttionViewExample (net7.0-windows10.0.19041.0) .

It works fine in Mobile App (Xamarin Forms).

---
#### Feedback Bot on 2/19/2023, 06:17 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by samhouts** [comment] 2023-03-14 16:53
Duplicate of #780

**Closed by samhouts** 2023-03-14 16:53 UTC
Labels: t/bug
