### ISSUE TITLE
Maui templates not visible when Dotnet 7.0 SDK installed

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#8903] opened 2022-07-21 20:29 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Maui-templates-not-visible-when-Dotnet-7/10052683)._

---
Maui templates not visible when Dotnet 7.0 SDK preview installed, when I uninstall the Dotnet 7 preview sdk then it all works  again.  please fix.

---
#### Feedback Bot on 5/25/2022, 02:13 AM: 

(private comment, text removed)
#### Feedback Bot on 5/25/2022, 08:08 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by samhouts** [comment] 2022-07-21 20:58
Duplicate of #8076

**Closed by samhouts** 2022-07-21 20:58 UTC
Labels: s/needs-verification
