### ISSUE TITLE
Maui Blazor App (new template) will not build for iOS after update to latest VS Version 17.2.0 Preview 3.0

### ISSUE THREAD

**Issue by Andrew-lll** [dotnet/maui#6017] opened 2022-04-12 21:58 UTC
### Description

After updating from a previous VS, and also after uninstalling VS preview and fresh reinstalling the latest VS preview:

See build errors when application is created on C:\

![image](https://user-images.githubusercontent.com/19860489/163045218-b18e6ebf-e4af-4517-995f-ad7fd88506c0.png)

See build errors when application is created on D:\

![image](https://user-images.githubusercontent.com/19860489/163045048-692d0324-a500-452a-8499-76f94adb5abc.png)

### Maui Check:

![image](https://user-images.githubusercontent.com/19860489/163046682-6fb84474-6382-4682-a319-e46890f192a4.png)

### SDK Versions:

![image](https://user-images.githubusercontent.com/19860489/163053516-3271c56d-471e-4b0c-b40a-15ab46dbfa3d.png)

### Steps to Reproduce

1. Install latest VS Version 17.2.0 Preview 3.0

![image](https://user-images.githubusercontent.com/19860489/163045741-ed64ef7c-f236-4df7-9526-72f0cf5badc4.png)

2. Create a new maui blazor template application

![image](https://user-images.githubusercontent.com/19860489/163045472-5935e56d-fa80-4f7b-a58c-82be9602a78b.png)

3. Run/build for iOS local device

![image](https://user-images.githubusercontent.com/19860489/163045609-1085ccca-7ef5-4fa5-8bb1-9079ec3e9d54.png)

4. Get errors for MainLayout.razor.css & NavMenu.razor.css

### Version with bug

Release Candidate 1

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS15

**Comment by TanayParikh** [comment] 2022-04-13 20:40
Thanks for reaching us @Andrew-lll. This looks like it's a duplicate of https://github.com/dotnet/maui/issues/4061.

**Comment by jfversluis** [comment] 2022-04-14 08:54
Duplicate of #4061

**Closed by jfversluis** 2022-04-14 08:54 UTC
Labels: t/bug, area/blazor 🕸️, s/needs-verification
