### ISSUE TITLE
CollectionView Header & Footer not showing

### ISSUE THREAD

**Issue by sesitosvdx** [dotnet/maui#14557] opened 2023-04-13 07:35 UTC
### Description

When trying to add any content inside a Header/Footer to a CollectionView, it is not being displayed. Only happens in Windows. Works well for Android and iOS.

### Steps to Reproduce

Create new project
Add CollectionView with a ItemsSource
Add a Header/Footer to the CollectionView

        <CollectionView x:Name="collectionview"
                        ItemsSource="{Binding Monkeys}">            
            <CollectionView.Header>
            <VerticalStackLayout BackgroundColor="LightGray">
                    <Label Margin="10,0,0,0"
                           Text="Monkeys"
                           FontSize="12"
                           FontAttributes="Bold" />
                </VerticalStackLayout>
            </CollectionView.Header>
            <CollectionView.Footer>
                <VerticalStackLayout BackgroundColor="LightGray">
                    <Label Margin="10,0,0,0"
                           Text="Friends of Xamarin Monkey"
                           FontSize="12"
                           FontAttributes="Bold" />
                </VerticalStackLayout>
            </CollectionView.Footer>
            <CollectionView.ItemTemplate>
                <DataTemplate>
                    ...
                </DataTemplate>
            </CollectionView.ItemTemplate>
        </CollectionView>

<img width="946" alt="image" src="https://user-images.githubusercontent.com/47418326/231688582-6a0e26b5-a913-4f76-a09b-867d28e6c8b7.png">

### Link to public reproduction project repository

https://github.com/sesitosvdx/CollectionViewHeaderFooterWindowsBug

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows10.0.19041.0

### Did you find any workaround?

https://github.com/dotnet/maui/issues/14557#issuecomment-1650647976

**Comment by drasticactions** [comment] 2023-04-13 08:29
I can reproduce this.

<img width="1562" alt="スクリーンショット 2023-04-13 17 26 51" src="https://user-images.githubusercontent.com/898335/231700921-1cb40fde-3125-420b-af71-6a8d50ca96be.png">

If you look at the raw Live Visual Tree for WinUI (Not MAUIs, but the WinUI Controls that MAUI creates) you can see the header and footer for the view. There's nothing rendered in them. If I hack them with Live Property Explorer, you can force them to appear, but whatever is there when compiled doesn't work.

**Comment by HobDev** [comment] 2023-04-15 08:48
facing same issue on windows after updating visual studio to Version 17.5.4

**Comment by drasticactions** [comment] 2023-04-17 05:55
https://github.com/dotnet/maui/issues/14603

This seems to be happening on Android too. Checking this sample on Android, I believe something similar is happening there.

**Comment by pwisk** [comment] 2023-04-19 11:20
The same is happening in my project on Windows. On Android view is generated but events are firing incorrectly when I have sublist with CollectionView.
I suspect it's caused by Windows App SDK 1.3.
I use Visual Studio 17.6.0 Preview 2.0. Preview 3.0 i broken for .NET MAUI.

**Comment by alizorlu** [comment] 2023-04-28 18:59
Hello to everyone,

I ran into the same problem a while ago. The problem is, when we assign a value to the "**EmptyView**" property as a _template, the header template in the collectionview gets corrupted_. You can try it in Android environment.

Example;
![emptyview_code](https://user-images.githubusercontent.com/24724027/235231016-27b6b3c8-849a-47d6-8f12-f6245ce9ca68.png)


With (Set emptyview property)
![emptyview_1](https://user-images.githubusercontent.com/24724027/235230602-386d670e-2532-422a-bb77-0f1a5180afff.png)

Without(not set emptyview property)
![emptyview_2](https://user-images.githubusercontent.com/24724027/235230681-72dfa650-3e66-4d88-8da4-a80e8a9a1168.png)

**Comment by nephesh** [comment] 2023-05-03 11:31
I have the same issue only in Windows. I'm using Visual Studio 17.5.5, and it was working on the previous VS version 17.5.2.

**Comment by williambohrmann3** [comment] 2023-05-05 17:57
Able to repro missing header on Windows with VS 17.5.4. Same control displays header just fine when deploying to Android, iOS, and MacCatalyst.

**Comment by dimustriz** [comment] 2023-05-07 07:08
As a workaround, it is possible to subscribe to Scrolled event of a CollectionView and then show/hide separately placed header/fooler views based on a scroll direction.

Though I am looking forward the issue fix. :-)

**Comment by jsuarezruiz** [comment] 2023-05-08 10:15
Tried https://github.com/sesitosvdx/CollectionViewHeaderFooterWindowsBug on main branch and cannot reproduce the issue on Windows.

![issue-14557](https://user-images.githubusercontent.com/6755973/236798497-4ea69c33-23dd-4f03-b214-fc7066c0d54d.gif)
Could someone attach a sample where reproduce the issue? @drasticactions Maybe I am missing something?

**Comment by AathifMahir** [comment] 2023-05-18 12:57
Noticing Same Issue in Windows, Not Sure about Other Platforms. Therefore, Going with Custom Header and Footer for Now

**Comment by drossoft** [comment] 2023-05-19 11:04
Same issue after updating VS to version 17.6.0

**Comment by SteveMaier-IRT** [comment] 2023-05-26 18:51
Same issue.

**Comment by ne0rrmatrix** [comment] 2023-06-07 06:37
I am having the same issue. If anyone has a work around I would love to know about it. I use a header for when loading data and I am unable to use it on windows atm. It works fine on android and ios.

**Comment by GerhardMauerberger** [comment] 2023-06-12 08:33
Same issue on VS 17.6.2 on Windows. No problem on Android.

**Comment by ne0rrmatrix** [comment] 2023-06-13 05:33
I was using a header as a way to show loading screen for web request of data. I switched to using an empty collection view. This fixed my issue. It is in fact a better way for me at least. But this issue of headers and footers is still not working for me in Windows. Still not problems with android or IOS.

**Comment by GerhardMauerberger** [comment] 2023-06-13 11:34
Hi James,

Yes, there are 2 problems:


  1.  It just does not work on Windows. It works on Android and IOS.
This is known as bug #14557 as you know.
  2.  Do not use ViewCell for a CollectionView.

***@***.***

Hope you are successful using NET MAUI.

  *   Gerhard

Von: James Crutchley ***@***.***>
Gesendet: Dienstag, 13. Juni 2023 07:33
An: dotnet/maui ***@***.***>
Cc: GerhardMauerberger ***@***.***>; Comment ***@***.***>
Betreff: Re: [dotnet/maui] CollectionView Header & Footer not showing (Issue #14557)


I was using a header as a way to show loading screen for web request of data. I switched to using an empty collection view. This fixed my issue. It is in fact a better way for me at least. But this issue of headers and footers is still not working for me in Windows. Still not problems with android or IOS.

-

**Comment by NunoBem** [comment] 2023-06-21 18:25
Is this only gonna be fixed in .NET 8? Have a production app that needs this...

**Comment by dimustriz** [comment] 2023-06-29 03:34
As a workaround it is possible to use ItemTemplateSelector and move Header/Footer to the first/last element.

**Comment by samhouts** [comment] 2023-07-17 20:06
Still a problem as of 8.0-preview 6.

**Comment by enisn** [comment] 2023-07-18 11:03
Still continues on Windows

**Comment by MegaEgorik** [comment] 2023-07-25 22:28
To make the CollectionView.Header work on Windows, you need to write this code in **App.xaml.cs**:
`CollectionViewHandler.Mapper.AppendToMapping("Header", (handler, _) => _.AddLogicalChild(handler.PlatformView.Header as Element));`

**Comment by MegaEgorik** [comment] 2023-07-26 11:13
I thought my the code above only works for header, but it works for footer too:
`Microsoft.Maui.Controls.Handlers.Items.CollectionViewHandler.Mapper.AppendToMapping("HeaderAndFooterFix", (handler, _) =>`
`{`
`    _.AddLogicalChild(handler.PlatformView.Header as Element);`
`    _.AddLogicalChild(handler.PlatformView.Footer as Element);`
`});`

**Comment by Blinchik91** [comment] 2023-07-26 13:56
same on android, collectionview header not visible, iOS is fine

**Comment by CarlosGod** [comment] 2023-08-03 01:29
> 

I write this code in my app.xaml.cs,but it still not work.Can u show me code

**Comment by ne0rrmatrix** [comment] 2023-08-03 03:09
> > 
> 
> I write this code in my app.xaml.cs,but it still not work.Can u show me code

Sample app with fix to help you. Look in  Platforms/Windows/App.xaml.cs
[https://github.com/ne0rrmatrix/HeaderSample](https://github.com/ne0rrmatrix/HeaderSample)

Or just copy past this into constructor for App.xaml.cs
```
 // Below is code to make Headers work for CollectionView for windows. Also works for footers.
        // All credit is due to MegaEgorik https://github.com/dotnet/maui/issues/14557#issuecomment-1651575327
        CollectionViewHandler.Mapper.AppendToMapping("HeaderAndFooterFix", (_, collectionView) =>
        {
            collectionView.AddLogicalChild(collectionView.Header as Element);
            collectionView.AddLogicalChild(collectionView.Footer as Element);
        });
```

**Comment by WithoutAnAce** [comment] 2023-08-08 02:21
Hmm, I tried @MegaEgorik's fix and it worked for my header but not my footer. Can work around it for now, but interesting nonetheless

**Comment by MegaEgorik** [comment] 2023-08-08 09:57
> Hmm, I tried @MegaEgorik's fix and it worked for my header but not my footer. Can work around it for now, but interesting nonetheless

Maybe you just didn't set a HeightRequest for the footer and that's why it's not showing up. 
This code works fine for me and all headers and footers for each CollectionView are displayed.

**Comment by WithoutAnAce** [comment] 2023-08-08 14:43
> > Hmm, I tried @MegaEgorik's fix and it worked for my header but not my footer. Can work around it for now, but interesting nonetheless
> 
> Maybe you just didn't set a HeightRequest for the footer and that's why it's not showing up. This code works fine for me and all headers and footers for each CollectionView are displayed.

Entirely possible! I'm a relatively new dev - would this be an OK place to ask where I'm going wrong here implementing this workaround?
```
...
        <CollectionView
            Grid.Row="1"
            Grid.Column="0"
            Grid.ColumnSpan="2"
            Margin="1"
            ItemsSource="{Binding AgendaItems}"
            VerticalScrollBarVisibility="Always">
            <CollectionView.Header>
                <Grid>
                    <Grid.ColumnDefinitions>
                        <ColumnDefinition x:Name="NameColumn" Width="*" />
                        <ColumnDefinition x:Name="LocationColumn" Width="*" />
                        <ColumnDefinition x:Name="StartTimeColumn" Width="*" />
                        <ColumnDefinition x:Name="EndTimeColumn" Width="*" />
                        <ColumnDefinition x:Name="RecurrenceColumn" Width="*" />
                    </Grid.ColumnDefinitions>
                    <Label Grid.Column="0" Text="Event Name" />
                    <Label Grid.Column="1" Text="Location" />
                    <Label Grid.Column="2" Text="StartTime" />
                    <Label Grid.Column="3" Text="EndTime" />
                    <Label Grid.Column="4" Text="Recurs?" />
                </Grid>
            </CollectionView.Header>
            <CollectionView.Footer>
                <Label Text="TestMessage" HeightRequest="24" MinimumHeightRequest="16"/>
            </CollectionView.Footer>
       ...
```
but this only shows the header, not the footer
![image](https://github.com/dotnet/maui/assets/32964968/65a1595d-b4f9-47f8-b95a-81d837d86c44)

**Comment by MegaEgorik** [comment] 2023-08-08 17:07
> 
> ```
> ...
>         <CollectionView
>             Margin="1"
>             ItemsSource="{Binding AgendaItems}"
>             VerticalScrollBarVisibility="Always">
>             <CollectionView.Header>
>                 <Grid>
>                     <Grid.ColumnDefinitions>
>                         <ColumnDefinition x:Name="NameColumn" Width="*" />
>                         <ColumnDefinition x:Name="LocationColumn" Width="*" />
>                         <ColumnDefinition x:Name="StartTimeColumn" Width="*" />
>                         <ColumnDefinition x:Name="EndTimeColumn" Width="*" />
>                         <ColumnDefinition x:Name="RecurrenceColumn" Width="*" />
>                     </Grid.ColumnDefinitions>
>                     <Label Grid.Column="0" Text="Event Name" />
>                     <Label Grid.Column="1" Text="Location" />
>                     <Label Grid.Column="2" Text="StartTime" />
>                     <Label Grid.Column="3" Text="EndTime" />
>                     <Label Grid.Column="4" Text="Recurs?" />
>                 </Grid>
>             </CollectionView.Header>
>             <CollectionView.Footer>
>                 <Label Text="TestMessage" HeightRequest="24" MinimumHeightRequest="16"/>
>             </CollectionView.Footer>
> ...
> ```
> 
> but this only shows the header, not the footer ![image](https://user-images.githubusercontent.com/32964968/259136930-65a1595d-b4f9-47f8-b95a-81d837d86c44.png)

Try updating .NET MAUI to the latest version.
I have the latest version and the fix works fine.
![image](https://github.com/dotnet/maui/assets/97403611/d6ff2713-f227-48a3-8e75-0619241c091e)
![image](https://github.com/dotnet/maui/assets/97403611/70bcba3a-f706-41fd-abd3-d7288c177f68)
![image](https://github.com/dotnet/maui/assets/97403611/e174d135-0bda-46b2-82e5-51395e64d2a0)

**Comment by WithoutAnAce** [comment] 2023-08-08 20:11
@MegaEgorik Thank you for the assistance. Working forwards from your example, I was able to figure out that the footer wasn't displaying because I had added an `Init()` event listener listening to the `Loaded` event of the view, and in that event listener I was updating `AgendaItems` without being on the main thread. My init method now looks like this:
```
        public override void Init()
        {
            Application.Current?.Dispatcher.Dispatch(()=>
            AgendaItems = new ObservableCollection<IAgendaItem>()
            );
            _timeService.StartTimer();
            ResetInputFields();
            base.Init();
        }
```

and your workaround in App.xaml is working correctly (though I will note for MSFT's sake that it is still a workaround, and the underlying issue is not fixed) Thank you so much!

**Comment by samhouts** [comment] 2023-08-08 22:03
Woohoo! Thanks for the team effort finding workarounds, friends! I assure you this is still a top priority to fix!

**Comment by xx7Ahmed7xx** [comment] 2023-08-21 11:26
> I thought the code above only works for header, but it works for footer too:
> 
> ```cs
> CollectionViewHandler.Mapper.AppendToMapping("HeaderAndFooterFix", (_, collectionView) =>
> {
>     collectionView.AddLogicalChild(collectionView.Header as Element);
>     collectionView.AddLogicalChild(collectionView.Footer as Element);
> });
> ```

This code works, I put it in the main App.xaml.cs (Under App.xaml) and immediately saw the header.
I'm super sad that MAUI has alot of design issues although it is kinda more than 2 years old ..

**Comment by drossoft** [comment] 2023-08-24 08:03
The solution proposed by @MegaEgorik works, but in my case, the footer is only shown the second time you navigate to the page, the first time only the header appears.

Also, the first time you navigate to the page, neither the header nor the footer have the BindingContext set, I had to set it in the OnAppearing method of the page.

**Closed** 2023-09-06 15:23 UTC
Labels: t/bug, platform/windows 🪟, p/1, area/collectionview 📃, s/verified, delighter
