### ISSUE TITLE
Android Unfocused Entry Behavior only gets called when leaving the page

### ISSUE THREAD

**Issue by faceoffers28** [dotnet/maui#11881] opened 2022-12-05 19:34 UTC
### Description

This works as expected in iOS. In Android, Unfocused only gets called when leaving the page. It does not get called when you leave the Entry field.

### Steps to Reproduce

Create an Entry in Xaml.

 ```xaml
<Entry Grid.Row="1" x:Name="nameEntry" Grid.Column="0" Placeholder="Enter a screen name." 
       HorizontalOptions="Center" Style="{StaticResource Label_ProfileViewName}"
       Text="{Binding SelectedPlayer.ScreenNameEntry}" TextChanged="entry_name_TextChanged" IsTextPredictionEnabled="false">
      <Entry.Behaviors>
          <local:CheckNameBehavior x:Name="checkScreenName"/>
      </Entry.Behaviors>
</Entry>
```

Create a Behavior like so.

```cs
    public class CheckNameBehavior : Behavior<Entry>
    {
        static readonly BindablePropertyKey IsValidPropertyKey = BindableProperty.CreateReadOnly("IsValid", typeof(bool), typeof(CheckNameBehavior), false);
        static readonly BindableProperty IsValidProperty = IsValidPropertyKey.BindableProperty;

        public bool IsValid
        {
            get { return (bool)base.GetValue(IsValidProperty); }
            private set { base.SetValue(IsValidPropertyKey, value); }
        }

protected override void OnAttachedTo(Entry bindable)
        {
            bindable.Unfocused += HandleFocusChanged;
        }

protected override void OnDetachingFrom(Entry bindable)
        {
            bindable.Unfocused -= HandleFocusChanged;
        }

async void HandleFocusChanged(object sender, FocusEventArgs e)
        {
            Entry entry = sender as Entry;
        }
}
```

### Link to public reproduction project repository

https://github.com/dotnet/maui/

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 31 with a target of 33

### Did you find any workaround?

Nope, there is no workaround.

**Comment by PureWeen** [comment] 2022-12-05 21:08
@faceoffers28 this behavior is most likely controlled by the underlying platform. We don't automatically unfocus/focus things when navigation happens. 

Can you expand on your use case here?

**Comment by faceoffers28** [comment] 2022-12-05 21:52
> @faceoffers28 this behavior is most likely controlled by the underlying platform. We don't automatically unfocus/focus things when navigation happens.
> 
> Can you expand on your use case here?

@PureWeen The use case would be checking some text that was entered against a database to see if there is a match. If there is a match, changing the text to red and updating an icon image to indicate an unsuccessful outcome. The Unfocus event works as expected on iOS. It does not work as expected on Android.

**Comment by PureWeen** [comment] 2022-12-05 22:14
@faceoffers28 why use focus/unfocus for this? Instead of TextChanged?

**Comment by faceoffers28** [comment] 2022-12-06 16:57
Hello @PureWeen TextChanged fires every time the text changes. It's extremely inefficient. It would result in many API calls to a rest API to check for a result. Is this really the only way to do this?

**Comment by RsZoli** [comment] 2023-02-14 15:08
@PureWeen please, don't ignore this, it is a serious problem, and not even the shell navigation closes the keyboard!

at least on 7,0 the keyboard can be closed by tapping on the "Done key", on 6.0 that is not possible!

here is a video of the problem: https://imgur.com/a/DxG7pTW

thank you!

**Comment by Gekidoku** [comment] 2023-08-21 11:15
Still an issue. 
https://github.com/Gekidoku/UnfocusTest
Start typing in the editor, 

Clicking on any other part of the page should trigger Unfocused as it did in xamarin, but it doesnt.

**Comment by Gekidoku** [comment] 2023-08-21 11:34
@PureWeen updated repo, added a page with a viewmodel. where i bind IsFocused. showing same behavior. only unfocusing when i change page through the flyout menu

**Comment by AramMar** [comment] 2023-08-21 11:39
@PureWeen i can also confirm the issue is still existed. and its very important for my app also

**Comment by sockstar85** [comment] 2023-08-29 19:16
I'll also confirm this still still an issue. Makes it really hard to make custom entries or use what we built in Xamarin.Forms in .NET Maui.

**Comment by Gekidoku** [comment] 2023-08-31 07:37
Small note on my unfocus test. 
I found that with the viewmodel method and binding to the isfocusedproperty it does trigger if you select a different focusable element.

**Comment by NijishaN** [comment] 2023-09-11 11:06
We are facing the same issue.If Any workaround,kindly inform.

**Comment by kkawormald** [comment] 2023-09-25 01:37
unfocused is being called on scrolling sometimes with template selectors

**Comment by HaimoHeymann** [comment] 2023-09-30 09:12
Has anybody found a workaround to this issue? (Android only)

**Comment by mattleibow** [comment] 2023-11-17 22:13
This may be a way to listen to text changes and wait for them to stop:

```
// used to schedule an update
Timer? timer;

// the buffer
const int TextChangedBuffer = 500; // half a second from the last character to sending the message

async void textEntry_TextChanged(object sender, TextChangedEventArgs e)
{
    var entry = (Entry)sender;

    // create a timer to trigger after the delay
    // the dispatcher is used as the timer returns on a background thread - but may be correct if this is a request to the web
    timer ??= new(_ => Dispatcher.Dispatch(() => UnFocusedLbl.Text = entry.Text));

    // move the timeout forward on each update
    timer.Change(TextChangedBuffer, Timeout.Infinite);
}
```

**Comment by 0XDE57** [comment] 2023-12-22 00:56
We require a (working) Unfocused event too.  TextChanged fires too many events, we only need to know then the user is finished. If the user taps on a different entry cell it does not fire Completed(), only when user closes keyboard.

This seems like such a basic functionality, its absence is surprising and application-breaking.

**Comment by Gekidoku** [comment] 2024-01-12 10:18
I have a small workaround for my case.
I bound the value of the editor to a variable in my viewmodel like so.
```CSharp
 public string Remark
 {
     get
     {
         return MyModel.Remark;
     }
     set
     {
         MyModel.Remark = value;
         RestartTimer();

     }
 }
``` 

Then on top of the viewmodel i also have  private Timer timer;
Then restart timer is as follows
```CSharp
private void RestartTimer()
{
    // Cancel the previous timer if it exists
    timer?.Dispose();

    // Start a new timer to check for inactivity after 5 seconds
    timer = new Timer(_ =>
    {
        MainThread.BeginInvokeOnMainThread(() =>
        {
            Update();
        });

        // Dispose of the timer after executing the UpdateCommand
        timer?.Dispose();
    }, null, 1000, Timeout.Infinite);
}
```

then update is just a function that sends my remark to the backend.
this works as a workaround for me since im only interested in limiting how many times the update function gets called.
when its directly on textchanged it triggers on every letter and due to the async nature and server hiccups this can mean that an earlier call finishes later than a later call thus overwriting the value of Remark to an earlier value.
this function triggers similarly to textchanged whenever any letter of character gets added to Remarks, but instead of immediately updating it waits a second. if within this second another change happens the timer gets disposed and re set.

**Comment by rachelkang** [comment] 2024-01-23 20:51
Hi All,

In developing .NET MAUI, we learned that it is not possible on earlier versions of Android to unfocus an entry. Some control _must_ always be focused. In Xamarin.Forms, this was approached by setting focus on the page layout; unfortunately, this approach created major accessibility issues. For these reasons, .NET MAUI no longer allows for this behavior by default.

If this antipattern can be avoided, we highly recommend using a different approach. If it cannot be avoided, we'd love to learn more about your scenario so that we can better understand your development needs! That being said, we do understand the needs from a migration compatibility standpoint, so for those scenarios, there is a [new property that was introduced in .NET 8](https://github.com/dotnet/maui/pull/16530). Using `HideSoftInputOnTapped` should do the trick.

**Closed by rachelkang** 2024-01-23 20:51 UTC
Labels: t/bug, platform/android 🤖, area/controls 🎮, s/verified, s/triaged
