### ISSUE TITLE
Navigation menu not showing in Blazor app if project name has space between

### ISSUE THREAD

**Issue by kevytmaito11** [dotnet/maui#13735] opened 2023-03-07 12:23 UTC
In Visual Studio 2022, if you use space in Project name (f.ex "Test Project" instead of "TestProject"), navigation menu does not show up when using Blazor app template.

**Comment by Zhanglirong-Winnie** [comment] 2023-06-25 09:29
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 2.0. Can repro on windows platform.
![Screenshot 2023-06-25 172507](https://github.com/dotnet/maui/assets/77434865/e8d0d77d-492e-40de-bcd7-25b0c7b2fefb)

**Comment by Eilon** [comment] 2024-01-13 00:01
Confirmed this is a bug. It's effectively a duplicate of #10780 because the problem is that URL-encoded path components are not decoded, so the path cannot be found on disk. That is, BlazorWebView sees a path like `my%20file.jpg` and actually tries to find a file on disk (or wherever) using the exact name of `my%20file.jpg` instead of applying a URL decode operation and looking for a file `my file.jpg`.

**Closed by Eilon** 2024-01-13 00:01 UTC
Labels: t/bug, area/blazor 🕸️, area/templates 📄, s/verified, s/triaged
