### ISSUE TITLE
[iOS] Focus on Entry is craching the default app

### ISSUE THREAD

**Issue by Phenek** [dotnet/maui#21541] opened 2024-03-31 10:06 UTC
### Description

It appears that the default application is crashing when attempting to focus on an entry field in an iOS simulator. The crash report indicates that the crash is happening due to a signal 6 abort trap.
````
Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Termination Reason: SIGNAL 6 Abort trap: 6
Terminating Process: MauiApp1 [4503]
````

### Steps to Reproduce

    1. Open the default .NET MAUI application project.
    2. Navigate to the MainPage.xaml file.
    3. Add an <Entry/> element inside the XAML markup.
    4. Build/Run the project in an iOS simulator.
    5. Once the application is launched in the simulator,
    interact with the user interface to bring focus to the <Entry/> element.
    Attempt to touch or tap on the <Entry/> element.

### Link to public reproduction project repository

[branch issue/21541](https://github.com/Phenek/Maui-Issue/tree/issue/21541)

### Version with bug

8.0.10 SR3

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

unknown, I just come back to see how .Net MAUI is doing.

### Affected platforms

iOS

### Did you find any workaround?

No

### Relevant log output

The stack trace provided in the crash report indicates that the crash occurs while updating the keyboard layout in response to focusing on the entry field. The crash seems to be related to handling keyboard input and formatting numbers using ICU (International Components for Unicode), specifically when attempting to create a number formatter.

Here's a breakdown of the relevant parts of the stack trace:

1. The crash occurs in the main thread (Thread 0) while updating the keyboard layout.
2. The crash happens within the UIKeyboardGetNumbersStringForActiveInputMode function, which suggests it's related to handling keyboard input.
3. The crash trace then goes into formatting number-related operations using ICU (libicucore.A.dylib), where it eventually results in an abort trap.

Given this information, it seems that there might be an issue with number formatting or handling keyboard input in your .NET MAUI application, possibly related to the ICU library.

```shell
024-03-31 11:48:49.704438+0200 MauiApp1[3156:56555] [unspecified] container_query_get_single_result: error = 2→(98) NOT_CODESIGNED
2024-03-31 11:48:49.704627+0200 MauiApp1[3156:56555] [unspecified] container_system_group_path_for_identifier: error = ((container_error_t)98) NOT_CODESIGNED
Thread started: .NET TP Gate #4
2024-03-31 11:48:49.704833+0200 MauiApp1[3156:56555] [MC] Error getting system group container for systemgroup.com.apple.configurationprofiles: 98
2024-03-31 11:48:49.705275+0200 MauiApp1[3156:56555] [MC] Failed to get profile system group container path. Overriding with expected path: /Users/vice/Library/Developer/CoreSimulator/Devices/8DFB9D52-0B60-48AA-A933-C800DE73D152/data/Containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles
Thread started: <Thread Pool> #5

=================================================================
	Native Crash Reporting
=================================================================
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

=================================================================
	Native stacktrace:
=================================================================
	0x109d81af5 - /Users/vice/Library/Developer/CoreSimulator/Devices/8DFB9D52-0B60-48AA-A933-C800DE73D152/data/Containers/Bundle/Application/C9481EF2-DEDF-42D6-9050-8E1938E109F2/MauiApp1.app/libmonosgen-2.0.dylib : mono_dump_native_crash_info
	0x109d204fe - /Users/vice/Library/Developer/CoreSimulator/Devices/8DFB9D52-0B60-48AA-A933-C800DE73D152/data/Containers/Bundle/Application/C9481EF2-DEDF-42D6-9050-8E1938E109F2/MauiApp1.app/libmonosgen-2.0.dylib : mono_handle_native_crash
	0x10a078b58 - /Users/vice/Library/Developer/CoreSimulator/Devices/8DFB9D52-0B60-48AA-A933-C800DE73D152/data/Containers/Bundle/Application/C9481EF2-DEDF-42D6-9050-8E1938E109F2/MauiApp1.app/libmonosgen-2.0.dylib : sigabrt_signal_handler.cold.1
	0x109d81430 - /Users/vice/Library/Developer/CoreSimulator/Devices/8DFB9D52-0B60-48AA-A933-C800DE73D152/data/Containers/Bundle/Application/C9481EF2-DEDF-42D6-9050-8E1938E109F2/MauiApp1.app/libmonosgen-2.0.dylib : mono_runtime_setup_stat_profiler
	0x10865237d - /usr/lib/system/libsystem_platform.dylib : _sigtramp
	0x600002c5b881 - Unknown
	0x7ff80016dd1c - /Library/Developer/CoreSimulator/Volumes/iOS_21E213/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.4.simruntime/Contents/Resources/RuntimeRoot/usr/lib/system/libsystem_c.dylib : abort
	0x7ff8001f28b0 - /Library/Developer/CoreSimulator/Volumes/iOS_21E213/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.4.simruntime/Contents/Resources/RuntimeRoot/usr/lib/system/libsystem_malloc.dylib : malloc_vreport
	0x7ff8001f2ab2 - /Library/Developer/CoreSimulator/Volumes/iOS_21E213/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.4.simruntime/Contents/Resources/RuntimeRoot/usr/lib/system/libsystem_malloc.dylib : malloc_report
	0x7ff801f42d88 - /Library/Developer/CoreSimulator/Volumes/iOS_21E213/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.4.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libicucore.A.dylib : _ZN3icu6Locale10setToBogusEv
	0x7ff801f4484a - /Library/Developer/CoreSimulator/Volumes/iOS_21E213/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.4.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libicucore.A.dylib : _ZN3icu6LocaleaSERKS0_
	0x7ff8020b0590 - /Library/Developer/CoreSimulator/Volumes/iOS_21E213/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.4.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libicucore.A.dylib : _ZNO3icu6number26UnlocalizedNumberFormatter6localeERKNS_6LocaleE
	0x7ff80205eeb7 - /Library/Developer/CoreSimulator/Volumes/iOS_21E213/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.4.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libicucore.A.dylib : _ZN3icu13DecimalFormat5touchER10UErrorCode
	0x7ff801f44265 - /Library/Developer/CoreSimulator/Volumes/iOS_21E213/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.4.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libicucore.A.dylib : unum_open
	0x7ff8004bff9a - /Library/Developer/CoreSimulator/Volumes/iOS_21E213/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.4.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : __cficu_unum_open
	0x7ff8003fc399 - /Library/Developer/CoreSimulator/Volumes/iOS_21E213/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.4.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : CFNumberFormatterCreate
	0x7ff800e5d833 - /Library/Developer/CoreSimulator/Volumes/iOS_21E213/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.4.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/Foundation.framework/Foundation : -[NSNumberFormatter _regenerateFormatter]
	0x7ff800e5eaa7 - /Library/Developer/CoreSimulator/Volumes/iOS_21E213/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.4.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/Foundation.framework/Foundation : -[NSNumberFormatter stringForObjectValue:]
	0x7ff8057cbebd - /Library/Developer/CoreSimulator/Volumes/iOS_21E213/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.4.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : UIKeyboardGetNumbersStringForActiveInputMode
	0x7ff805847471 - /Library/Developer/CoreSimulator/Volumes/iOS_21E213/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.4.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : UIKBMoreKeyStringForActiveInputMode
	0x7ff8058d248d - /Library/Developer/CoreSimulator/Volumes/iOS_21E213/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.4.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : -[UIKeyboardLayoutStar updateLocalizedKeysOnKeyplane:]
	0x7ff8058d4659 - /Library/Developer/CoreSimulator/Volumes/iOS_21E213/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.4.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : -[UIKeyboardLayoutStar updateLocalizedKeysForKeyplane:updateAllKeyplanes:]
	0x7ff8058dc596 - /Library/Developer/CoreSimulator/Volumes/iOS_21E213/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.4.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : -[UIKeyboardLayoutStar setKeyplaneName:]
	0x7ff8058e54e2 - /Library/Developer/CoreSimulator/Volumes/iOS_21E213/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.4.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : -[UIKeyboardLayoutStar setToInitialKeyplane]
	0x7ff8058e5367 - /Library/Developer/CoreSimulator/Volumes/iOS_21E213/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.4.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : -[UIKeyboardLayoutStar showKeyboardWithInputMode:renderConfig:inputTraits:screenTraits:splitTraits:reload:]
	0x7ff8058e547c - /Library/Developer/CoreSimulator/Volumes/iOS_21E213/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.4.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : -[UIKeyboardLayoutStar showKeyboardWithInputTraits:screenTraits:splitTraits:]
	0x7ff805a1dfc7 - /Library/Developer/CoreSimulator/Volumes/iOS_21E213/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.4.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : -[UIKeyboardImpl finishLayoutChangeWithArguments:]
	0x7ff805a1ea1e - /Library/Developer/CoreSimulator/Volumes/iOS_21E213/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.4.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : -[UIKeyboardImpl updateLayout]
	0x7ff805a0c75b - /Library/Developer/CoreSimulator/Volumes/iOS_21E213/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.4.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : -[UIKeyboardImpl _setupDelegate:delegateSame:hardwareKeyboardStateChanged:endingInputSessionIdentifier:force:delayEndInputSession:]
	0x7ff805a09633 - /Library/Developer/CoreSimulator/Volumes/iOS_21E213/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.4.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : -[UIKeyboardImpl setDelegate:force:delayEndInputSession:]
	0x7ff8054bde35 - /Library/Developer/CoreSimulator/Volumes/iOS_21E213/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.4.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : -[UIKeyboardSceneDelegate _reloadInputViewsForKeyWindowSceneResponder:force:fromBecomeFirstResponder:]
	0x7ff8054bc76a - /Library/Developer/CoreSimulator/Volumes/iOS_21E213/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.4.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : -[UIKeyboardSceneDelegate _reloadInputViewsForResponder:force:fromBecomeFirstResponder:]
	0x7ff805d1d22a - /Library/Developer/CoreSimulator/Volumes/iOS_21E213/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.4.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : -[UIResponder(UIResponderInputViewAdditions) _reloadInputViewsFromFirstResponder:]
	0x7ff805d16258 - /Library/Developer/CoreSimulator/Volumes/iOS_21E213/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.4.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : -[UIResponder becomeFirstResponder]
	0x7ff8063a8696 - /Library/Developer/CoreSimulator/Volumes/iOS_21E213/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.4.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : -[UIView(Hierarchy) becomeFirstResponder]
	0x7ff806118558 - /Library/Developer/CoreSimulator/Volumes/iOS_21E213/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.4.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : -[UITextField becomeFirstResponder]
	0x7ff8060c6c58 - /Library/Developer/CoreSimulator/Volumes/iOS_21E213/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.4.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : -[UITextInteractionAssistant(UITextInteractionAssistant_Internal) setFirstResponderIfNecessaryActivatingSelection:]
	0x7ff806094d63 - /Library/Developer/CoreSimulator/Volumes/iOS_21E213/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.4.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : -[UITextSelectionInteraction _checkForRepeatedTap:gestureLocationOut:]
	0x7ff8060961dc - /Library/Developer/CoreSimulator/Volumes/iOS_21E213/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.4.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : -[UITextSelectionInteraction _handleMultiTapGesture:]
	0x7ff805ce5824 - /Library/Developer/CoreSimulator/Volumes/iOS_21E213/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.4.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : -[UIApplication sendAction:to:from:forEvent:]
	0x7ff805547938 - /Library/Developer/CoreSimulator/Volumes/iOS_21E213/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.4.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : -[UITextMultiTapRecognizer onStateUpdate:]
	0x7ff805651875 - /Library/Developer/CoreSimulator/Volumes/iOS_21E213/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.4.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : -[UIGestureRecognizerTarget _sendActionWithGestureRecognizer:]
	0x7ff80565b43a - /Library/Developer/CoreSimulator/Volumes/iOS_21E213/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.4.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : _UIGestureRecognizerSendTargetActions
	0x7ff80565822a - /Library/Developer/CoreSimulator/Volumes/iOS_21E213/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.4.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : _UIGestureRecognizerSendActions
	0x7ff8056575d7 - /Library/Developer/CoreSimulator/Volumes/iOS_21E213/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.4.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : -[UIGestureRecognizer _updateGestureForActiveEvents]
	0x7ff805644b9d - /Library/Developer/CoreSimulator/Volumes/iOS_21E213/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.4.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : _UIGestureEnvironmentUpdate
	0x7ff8056437d9 - /Library/Developer/CoreSimulator/Volumes/iOS_21E213/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.4.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : -[UIGestureEnvironment _updateForEvent:window:]
	0x7ff805d2b396 - /Library/Developer/CoreSimulator/Volumes/iOS_21E213/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.4.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : -[UIWindow sendEvent:]
	0x7ff805d0028e - /Library/Developer/CoreSimulator/Volumes/iOS_21E213/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.4.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : -[UIApplication sendEvent:]
	0x7ff805db102b - /Library/Developer/CoreSimulator/Volumes/iOS_21E213/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.4.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : __dispatchPreprocessedEventFromEventQueue
	0x7ff805db4154 - /Library/Developer/CoreSimulator/Volumes/iOS_21E213/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.4.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : __processEventQueue
	0x7ff805da9d34 - /Library/Developer/CoreSimulator/Volumes/iOS_21E213/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.4.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : __eventFetcherSourceCallback
	0x7ff800429ff3 - /Library/Developer/CoreSimulator/Volumes/iOS_21E213/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.4.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__
	0x7ff800429f35 - /Library/Developer/CoreSimulator/Volumes/iOS_21E213/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.4.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : __CFRunLoopDoSource0
	0x7ff800429732 - /Library/Developer/CoreSimulator/Volumes/iOS_21E213/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.4.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : __CFRunLoopDoSources0
	0x7ff800423e67 - /Library/Developer/CoreSimulator/Volumes/iOS_21E213/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.4.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : __CFRunLoopRun
	0x7ff8004236ed - /Library/Developer/CoreSimulator/Volumes/iOS_21E213/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.4.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : CFRunLoopRunSpecific
	0x7ff8103ba08f - /Library/Developer/CoreSimulator/Volumes/iOS_21E213/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.4.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/GraphicsServices.framework/GraphicsServices : GSEventRunModal
	0x7ff805cdf6ee - /Library/Developer/CoreSimulator/Volumes/iOS_21E213/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.4.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : -[UIApplication _run]
	0x7ff805ce416e - /Library/Developer/CoreSimulator/Volumes/iOS_21E213/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.4.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : UIApplicationMain
	0x1091f150a - /Users/vice/Library/Developer/CoreSimulator/Devices/8DFB9D52-0B60-48AA-A933-C800DE73D152/data/Containers/Bundle/Application/C9481EF2-DEDF-42D6-9050-8E1938E109F2/MauiApp1.app/libxamarin-dotnet-debug.dylib : xamarin_UIApplicationMain
	0x109d96765 - /Users/vice/Library/Developer/CoreSimulator/Devices/8DFB9D52-0B60-48AA-A933-C800DE73D152/data/Containers/Bundle/Application/C9481EF2-DEDF-42D6-9050-8E1938E109F2/MauiApp1.app/libmonosgen-2.0.dylib : do_icall
	0x109d94ef7 - /Users/vice/Library/Developer/CoreSimulator/Devices/8DFB9D52-0B60-48AA-A933-C800DE73D152/data/Containers/Bundle/Application/C9481EF2-DEDF-42D6-9050-8E1938E109F2/MauiApp1.app/libmonosgen-2.0.dylib : do_icall_wrapper
	0x109d85c16 - /Users/vice/Library/Developer/CoreSimulator/Devices/8DFB9D52-0B60-48AA-A933-C800DE73D152/data/Containers/Bundle/Application/C9481EF2-DEDF-42D6-9050-8E1938E109F2/MauiApp1.app/libmonosgen-2.0.dylib : mono_interp_exec_method
	0x109d83383 - /Users/vice/Library/Developer/CoreSimulator/Devices/8DFB9D52-0B60-48AA-A933-C800DE73D152/data/Containers/Bundle/Application/C9481EF2-DEDF-42D6-9050-8E1938E109F2/MauiApp1.app/libmonosgen-2.0.dylib : interp_runtime_invoke
	0x109e696f8 - /Users/vice/Library/Developer/CoreSimulator/Devices/8DFB9D52-0B60-48AA-A933-C800DE73D152/data/Containers/Bundle/Application/C9481EF2-DEDF-42D6-9050-8E1938E109F2/MauiApp1.app/libmonosgen-2.0.dylib : mono_runtime_invoke_checked
	0x109e7103b - /Users/vice/Library/Developer/CoreSimulator/Devices/8DFB9D52-0B60-48AA-A933-C800DE73D152/data/Containers/Bundle/Application/C9481EF2-DEDF-42D6-9050-8E1938E109F2/MauiApp1.app/libmonosgen-2.0.dylib : mono_runtime_exec_main_checked
	0x109cd5b62 - /Users/vice/Library/Developer/CoreSimulator/Devices/8DFB9D52-0B60-48AA-A933-C800DE73D152/data/Containers/Bundle/Application/C9481EF2-DEDF-42D6-9050-8E1938E109F2/MauiApp1.app/libmonosgen-2.0.dylib : mono_jit_exec
	0x109235bea - /Users/vice/Library/Developer/CoreSimulator/Devices/8DFB9D52-0B60-48AA-A933-C800DE73D152/data/Containers/Bundle/Application/C9481EF2-DEDF-42D6-9050-8E1938E109F2/MauiApp1.app/libxamarin-dotnet-debug.dylib : xamarin_main
	0x107bfba14 - /Users/vice/Library/Developer/CoreSimulator/Devices/8DFB9D52-0B60-48AA-A933-C800DE73D152/data/Containers/Bundle/Application/C9481EF2-DEDF-42D6-9050-8E1938E109F2/MauiApp1.app/MauiApp1 : main
	0x1081043e0 - Unknown
	0x116a7d386 - Unknown

=================================================================
	Basic Fault Address Reporting
=================================================================
Memory around native instruction pointer (0x1091667a2):0x109166792  ff ff c3 90 90 90 b8 48 01 00 02 49 89 ca 0f 05 
 ...
....H...I....

0x1091667a2  73 08 48 89 c7 e9 d8 99 ff ff c3 90 90 90 b8 53  s.H......
......S
0x1091667b2  00 00 02 
49 89 ca 0f 05 73 08 48 89 c7 
e9 c0 99  ...I....s.H..
...
0x1091667c2  ff ff c3 90 90 
90 b8 83 01 00 02 49 89 ca 0f 05  ...
........I....
=================================================================
	Managed Stacktrace:
=================================================================
	  at <unknown> <0xffffffff>
	  at UIKit.UIApplication:xamarin_UIApplicationMain <0x000b8>
	  at UIKit.UIApplication:UIApplicationMain <0x0006e>
	  at UIKit.UIApplication:Main <0x0015a>
	  at MauiApp1.Program:Main <0x0002c>
	  at <Module>:runtime_invoke_direct_void_string[] <0x00118>
	  at <unknown> <0x00000>
=================================================================
```

**Comment by marcosgerene** [comment] 2024-03-31 15:15
Same!

**Comment by jfversluis** [comment] 2024-03-31 18:12
Duplicate of #21057

**Closed by jfversluis** 2024-03-31 18:12 UTC
Labels: t/bug
