### ISSUE TITLE
Default value of a Preferences.Get returns a null value in Windows

### ISSUE THREAD

**Issue by geertgeerits** [dotnet/maui#9306] opened 2022-08-10 12:27 UTC
### Description

Default value of a Preferences.Get returns a NULL value in Windows, works correct in Android.
Not tested on Apple products.

### Steps to Reproduce

1. Open the attached file
2. Run it in Android and you will see the text: Preference OK
3. Run it in Windows and the text will be: Preference NOT OK

[MauiAppTestPreferencesGet.zip](https://github.com/dotnet/maui/files/9299929/MauiAppTestPreferencesGet.zip)

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 11

### Did you find any workaround?

No

**Comment by jfversluis** [comment] 2022-08-11 09:07
Seems a duplicate/related to #9338 can I please ask you to upload the reproduction to a GitHub repository instead of adding it here as a zip file? Thanks!

**Comment by geertgeerits** [comment] 2022-08-11 12:22
Hi, here is the link to the GitHub repository:
https://github.com/geertgeerits/MauiAppTestPreferencesGet

**Comment by mattleibow** [comment] 2022-08-11 19:19
Thanks for the repro! I managed to see that it is a duplicate of #9338

**Closed by mattleibow** 2022-08-11 19:19 UTC
Labels: t/bug, platform/windows 🪟, area/essentials 🍞
