### ISSUE TITLE
Xamarin.UITest “iOSDeviceManager” will damage your computer. You should move it to the Bin

### ISSUE THREAD

**Issue by ESO-ST** [dotnet/maui#20364] opened 2024-02-05 17:28 UTC
### Description

Xamarin.UITest 4.3.2
macOS Sonoma 14.1.2 (and 14.2)
VS Mac 17.6.8

Cannot run UITests because this message appears when I start a UI test:
![image](https://github.com/dotnet/maui/assets/140424692/96c687f6-2732-48b3-b702-064e1450456a)

original ticket  https://github.com/microsoft/appcenter/issues/2605 

### Version with bug

8.0.6

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, macOS

**Comment by drasticactions** [comment] 2024-02-06 02:33
This is not a MAUI bug. It's a specific issue with AppCenter and Xamarin.UITest/calabash and however it's bundling that program used for testing. It's not something that can be fixed in this repo.

**Comment by jfversluis** [comment] 2024-02-06 12:49
Indeed this is not us. Duplicate of https://github.com/microsoft/appcenter/issues/2605

**Closed by jfversluis** 2024-02-06 12:49 UTC
Labels: t/bug, platform/macOS 🍏, platform/iOS 🍎
