### ISSUE TITLE
Grid no longer adds implicit rows/columns

### ISSUE THREAD

**Issue by mattleibow** [dotnet/maui#10338] opened 2022-09-27 07:39 UTC
### Description

Previously in Xamarin.Forms, I could add controls to a Grid and then just set Grid.Row="x" and it would automatically add rows. In MAUI now, I have to manually add all the row definitions of Auto/*.

### Steps to Reproduce

1. Add a Grid
2. Add multiple controls with Grid.Row="n+1"
3. Observe all the controls are in the same row

### Link to public reproduction project repository

:)

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS, Other (Tizen, Linux, etc. not supported by Microsoft directly)

### Affected platform versions

All

**Comment by PureWeen** [comment] 2022-09-27 15:11
https://github.com/dotnet/maui/wiki/Xamarin.Forms----MAUI.Controls-Layout-Differences#general-changes

**Comment by hartez** [comment] 2022-09-27 16:38
Duplicate of #8958

**Closed by hartez** 2022-09-27 16:38 UTC
Labels: t/bug, area/layout 🔲, area/migration 🚚
