### ISSUE TITLE
[regression/8.0.0-preview.3.8149] Result of "WidthRequest="{Binding Width, Source={x:Reference input}}" is different to each platforms

### ISSUE THREAD

**Issue by Sunday5214** [dotnet/maui#18039] opened 2023-10-16 09:20 UTC
### Description

I migrating our xamarin.forms application,  I found this bug.
![image](https://github.com/dotnet/maui/assets/38588097/f163f243-a315-4954-ab35-3e751983d2f8)
```xml
<Grid HorizontalOptions="FillAndExpand" x:Name="container" HeightRequest="80">
     <Grid.ColumnDefinitions>
         <ColumnDefinition Width="*"/>
         <ColumnDefinition Width="auto"/>
     </Grid.ColumnDefinitions>
     <Entry Placeholder="Test PlaceHolder" 
          Keyboard="Numeric" Margin="0" 
          HorizontalOptions="FillAndExpand" Grid.Column="0"/>
     <Button x:Name="btnSendCode" Text="123" Grid.Column="1"
           WidthRequest="{Binding Width, Source={x:Reference container}, Mode=Default}"
           LineBreakMode="NoWrap"
           HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand">
     </Button>
 </Grid>
```
MainPage.xaml

![image](https://github.com/dotnet/maui/assets/38588097/3975ae7a-e467-4f3e-9362-7740733fec26)
```xml
public partial class MainPage : ContentPage
{
    public MainPage()
    {
        InitializeComponent();
        btnSendCode.PropertyChanged += BtnSendCode_PropertyChanged;
        container.PropertyChanged += Input_PropertyChanged;
    }
    private void Input_PropertyChanged(object sender, System.ComponentModel.PropertyChangedEventArgs e)
    {
        if(e.PropertyName == "Width")
        {
            Debug.WriteLine(container.Width);
        }
    }
    private void BtnSendCode_PropertyChanged(object sender, System.ComponentModel.PropertyChangedEventArgs e)
    {
        if (e.PropertyName == "Width")
        {
            Debug.WriteLine(btnSendCode.Width);
        }
    }
}
```
MainPage.xaml.cs

![image](https://github.com/dotnet/maui/assets/38588097/a3cb4118-2646-4ad2-9c0c-f195d4870b37)

1904
1904
Debug Output

![image](https://github.com/dotnet/maui/assets/38588097/f7d9599c-c685-478e-921b-133c9ce3ebed)

[0:] 384
[0:] 51.91111111111111
Debug Output

I think the above code's result should same as btnSendCode's width to the container's width
but In Android, it was not the same and In Windows it was the same
iOS and Mac need testing

I don't know much about MAUI rendering, 
Shouldn't the above code's result for each platform be the same?

### Steps to Reproduce

1. https://github.com/Sunday5214/MAUITest just run sample in each platforms
2. Check Debug output and rendered UI

### Link to public reproduction project repository

https://github.com/Sunday5214/MAUITest

### Version with bug

[8.0.0-preview.3.8149](https://github.com/dotnet/maui/releases/tag/8.0.0-preview.3.8149)

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

[8.0.0-preview.2.7871](https://github.com/dotnet/maui/releases/tag/8.0.0-preview.2.7871)

### Affected platforms

Android, Windows

### Affected platform versions

Android 13, Windows 11 Enterprise 22H2 22621.2428

**Comment by samhouts** [comment] 2023-10-17 01:44
Confirmed that there was a change in behavior between [8.0.0-preview.2.7871](https://github.com/dotnet/maui/releases/tag/8.0.0-preview.2.7871) and [8.0.0-preview.3.8149](https://github.com/dotnet/maui/releases/tag/8.0.0-preview.3.8149), likely due to https://github.com/dotnet/maui/pull/14114. 

In preview 2, both Windows and Android display the Button next to the Entry, although in Windows the Button is still much larger than it is in Android.

However, I'm not fully sure what you're expecting out of this configuration. Setting the Button width to the same width as the Grid when you expect there to be two columns is bound to produce unexpected results.

**Comment by Sunday5214** [comment] 2023-10-17 06:00
My intention is to put the button in the second column and the entry in the first column.
And when a particular value changes using TriggerAction, ex) IsLoading -> false to true
It was to reduce the size of the button so that the entry came out naturally.

If the width of the parent container grid and the width of the button are the same, the entry is not displayed on the UI and the user can only see the button.

If using Grid like this is not intended, is there a better way?

**Comment by hartez** [comment] 2023-12-11 23:08
We're working on a fix for this, so that the Android behavior fits with the other platforms and matches what worked on Forms.

That said, it's generally not a good idea to do this. Because you are binding a value which affects layout to another value which affects layout, you are guaranteeing that the layout takes at least 2 layout passes to fully resolve. This will affect the performance of the application. 

If I understand the layout you are trying to achieve, you could accomplish it by doing this:

```xaml
<Grid HeightRequest="80" ColumnDefinitions="*,Auto">
    <Entry Placeholder="Test PlaceHolder"
            x:Name="txtEntry"
            IsVisible="False" />
    <Button x:Name="btnSendCode"
            Text="123"
            Grid.Column="0"
            Grid.ColumnSpan="2"
            LineBreakMode="NoWrap" />
</Grid>
```

And in your code, doing something like this when you want to toggle the visibility of the Entry:

```charp
btnSendCode.Clicked += (sender, args) =>
{
	if (Grid.GetColumnSpan(btnSendCode) == 2)
	{
		Grid.SetColumnSpan(btnSendCode, 1);
		Grid.SetColumn(btnSendCode, 1);
	}
	else
	{
		Grid.SetColumnSpan(btnSendCode, 2);
		Grid.SetColumn(btnSendCode, 0);
	}

	txtEntry.IsVisible = Grid.GetColumnSpan(btnSendCode) == 1;
};
```

This only requires a single layout pass to resolve.

**Closed** 2023-12-13 22:28 UTC
Labels: t/bug, area/layout 🔲, i/regression, migration-compatibility, layout-grid
