### ISSUE TITLE
Windows Desktop App fails to run in administrator mode

### ISSUE THREAD

**Issue by LoopedBard3** [dotnet/maui#6208] opened 2022-04-18 22:38 UTC
### Description

After publishing the maui new app as a windows desktop exe, I am unable to run the exe in administrator mode. The app starts when not trying to run in administrator mode. I have tried running in administrator mode both from explorer by right clicking the exe and clicking run as admin, and from an administrator console. Neither of these approaches result in anything useful being surfaced directly (no console exception or windows exception dialog), but some error info is included below in the relevant logs.

### Steps to Reproduce

Generally:
- May need to install packages in '~\.nuget\packages\microsoft.windowsappsdk\1.0.2\tools\MSIX\win10-x64'
- Install the latest dotnet 6.0.3xx and  maui workload
- Generate new maui app
- Publish the app to exe
- Run the app as administrator (or from admin console)

Specific commands:
\# install latest dotnet 6.0.3xx
\# install MSIXs in '~\.nuget\packages\microsoft.windowsappsdk\1.0.2\tools\MSIX\win10-x64\Microsoft.WindowsAppRuntime.1.0.msix'
curl https://raw.githubusercontent.com/dotnet/maui/main/NuGet.config -o Nuget.config
dotnet workload install maui `
   --from-rollback-file https://aka.ms/dotnet/maui/main.json `
   --configfile .\Nuget.config
dotnet new maui --name MauiTesting
cd MauiTesting
dotnet publish -f net6.0-windows10.0.19041.0 -c Release -p:WindowsPackageType=None -p:WinUISDKReferences=false
\# Run the exe as admin
.\bin\Release\net6.0-windows10.0.19041.0\win10-x64\publish\MauiTest.exe

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Maui Main branch; Windows 10 and Windows 11 (Target Frameworks: net6.0-windows10.0.19041.0 and net6.0-windows10.0.22000.0)

### Relevant log output

```shell
With a debugger:
Unhandled exception at 0x00007FFAFF6EB10D (Microsoft.WindowsAppRuntime.Bootstrap.dll) in MauiTest.exe: Fatal program exit requested.

From Event Viewer:
Faulting application name: MauiDesktopTesting.exe, version: 1.0.0.0, time stamp: 0x622f78e0
Faulting module name: Microsoft.WindowsAppRuntime.Bootstrap.dll, version: 0.0.0.0, time stamp: 0x622fc69c
Exception code: 0xc0000409
Fault offset: 0x000000000000124d
Faulting process id: 0x76c0
Faulting application start time: 0x01d8536aac455ae6
Faulting application path: {DIR}\MauiDesktopTesting.exe
Faulting module path: {DIR}\Microsoft.WindowsAppRuntime.Bootstrap.dll
Report Id: 1f24fa9d-b25e-4899-ab81-8bc2c50f6869
Faulting package full name: 
Faulting package-relative application ID:
```

**Comment by eerhardt** [comment] 2022-04-18 22:49
@mattleibow - this is affecting automating startup performance of windows apps, since the perf infrastructure needs to run as admin in order to capture the ETW events from the app.

I attached a debugger, and the code pointed me to this issue: https://github.com/microsoft/WindowsAppSDK/issues/567. The code in `Microsoft.WindowsAppRuntime.Bootstrap` explicitly calls a method named `FailFastIfElevated()`. See https://github.com/microsoft/WindowsAppSDK/pull/617.

**Comment by mattleibow** [comment] 2022-04-19 03:20
We have a sync later today with the WinUI team, so I will check to see where this is and how far along this is - if at all.

**Comment by mattleibow** [comment] 2022-04-20 16:33
This should be fixed in the 1.1-preview2 on nuget.

**Comment by Redth** [comment] 2022-05-02 14:57
@jfversluis could you validate that 1.1-preview2 fixes this?

**Comment by jfversluis** [comment] 2022-05-02 18:29
Confirmed that this is fixed with Microsoft.WindowsAppSDK version 1.1-preview2

**Comment by jfversluis** [comment] 2022-06-28 08:19
1.1 stable is now out and with the latest .NET MAUI bits this now works as expected.

**Closed by jfversluis** 2022-06-28 08:19 UTC
Labels: t/bug, platform/windows 🪟, p/2, area/desktop 🖥️
