### ISSUE TITLE
CollectionView taps not being processed

### ISSUE THREAD

**Issue by eamonn-alphin** [dotnet/maui#6075] opened 2022-04-13 17:01 UTC
### Description

I have a collectionView that gets populated. 
When i tap on a row item (with correct bindings and/or event handlers set on the collectionview), the debug console shows: 

```
[ViewRootImpl@fa21d74[MainActivity]] ViewPostImeInputStage processPointer 0
[ViewRootImpl@fa21d74[MainActivity]] ViewPostImeInputStage processPointer 1
[InputMethodManager] HSI from window - flag : 0 Pid : 30889
[SEM_CLIP_SemClipboardManager] isCocktailBarDisplayed : false
[art] Do partial code cache collection, code=58KB, data=60KB
[art] After code cache collection, code=54KB, data=58KB
[art] Increasing code cache capacity to 256KB
[SEM_CLIP_SemClipboardManager] isCocktailBarDisplayed : false
```

and nothing happens; the "selectionchangedcommand" doesn't fire. 

### Steps to Reproduce

1. Create a maui app
2. Create a collectionView, bind it to some data and give it an item template
3. set the SelectionChanged event handler
4. Run the app and try tapping on an item in the collectionView. 

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Preview 14

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 7.0

### Did you find any workaround?

Adding a tapgesturerecognizer to the itemtemplate works; as in the tap will be recognized, but I'd have to go about figuring out how to differentiate which row was tapped. 

### Relevant log output

```shell
[ViewRootImpl@fa21d74[MainActivity]] ViewPostImeInputStage processPointer 0
[ViewRootImpl@fa21d74[MainActivity]] ViewPostImeInputStage processPointer 1
[InputMethodManager] HSI from window - flag : 0 Pid : 30889
[SEM_CLIP_SemClipboardManager] isCocktailBarDisplayed : false
[art] Do partial code cache collection, code=58KB, data=60KB
[art] After code cache collection, code=54KB, data=58KB
[art] Increasing code cache capacity to 256KB
[SEM_CLIP_SemClipboardManager] isCocktailBarDisplayed : false
```

**Comment by VladislavAntonyuk** [comment] 2022-04-13 19:13
It works on Windows, but doesn't work on Android

**Comment by kristinx0211** [comment] 2022-04-14 08:31
@eamonn-alphin Thank you so much for your bug report! Unfortunately, we cannot reproduce your issue with the information above, could you provide a sample project/screenshots or more details that we can reproduce your issue? That should greatly speed up the process, thanks!

**Comment by VladislavAntonyuk** [comment] 2022-04-14 12:08
@kristinx0211 Please try the sample: https://github.com/CommunityToolkit/Maui. It is reproduced on Android

**Comment by eamonn-alphin** [comment] 2022-04-14 15:15
> @kristinx0211 Please try the sample: https://github.com/CommunityToolkit/Maui. It is reproduced on Android

Thanks, ValdislavAntonyuk!

**Comment by kristinx0211** [comment] 2022-04-15 06:07
thanks, verified repro on Android 11.

**Comment by jamesmontemagno** [comment] 2022-04-15 17:31
See https://github.com/dotnet-presentations/dotnet-maui-workshop for repro as well

**Comment by profimedica** [comment] 2022-04-21 19:59
> I can reproduce this too, tried it with the MAUI Workshop App: https://github.com/dotnet-presentations/dotnet-maui-workshop/tree/main/Part%206%20-%20AppThemes. It seems to sometimes respond if I tab all the way on the right side of a item.

Even when I try to use TapGestureRecognizer inside CollectionView.ItemTemplate, the issue is the same. Only on left side of the window and few pixels over the first label the click is captured. Elseware is ignored.

**Comment by kristinx0211** [comment] 2022-05-09 04:37
verified on android with 17.3.0 Preview 2.0 [32507.29.main], not repro. close it. feel free to open new issue if you still hit this failure with same/newer environment.

**Closed by kristinx0211** 2022-05-09 04:37 UTC
Labels: t/bug, p/1, area/collectionview 📃, s/verified
