### ISSUE TITLE
CollectionView not showing correctly inside AbsoluteLayout in iOS 

### ISSUE THREAD

**Issue by alfarajali** [dotnet/maui#15808] opened 2023-06-23 06:35 UTC
### Description

When placing a CollectionView control inside an AbsoluteLayout, the control gets shifted off screen. See below picture. 
![Screenshot 2023-06-23 at 09 25 58](https://github.com/dotnet/maui/assets/110019848/5bda0be0-bc50-420c-9e84-c72c1e87b7b1)

### Steps to Reproduce

1. Create new .NET MAUI app
2. Paste below code in XAML file
```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MauiApp4.MainPage" BackgroundColor="White"
             FlowDirection="RightToLeft">

    <StackLayout>

        <AbsoluteLayout VerticalOptions="FillAndExpand">

            <Grid x:Name="GridOverLay" 
      IsVisible="true"
      AbsoluteLayout.LayoutBounds="0,0,1,1"
     AbsoluteLayout.LayoutFlags="All"
      VerticalOptions="FillAndExpand"
      >

                <CollectionView x:Name="touristCollectionList"
                   SelectionMode="Single"
                 
                   Margin="15">
                    <CollectionView.ItemsLayout>
                        <LinearItemsLayout Orientation="Vertical"/>
                    </CollectionView.ItemsLayout>
                    <CollectionView.ItemTemplate>
                        <DataTemplate>

                            <Border Stroke="#009688" Padding="15">
                                <Border.StrokeShape>
                                    <RoundRectangle CornerRadius="20"/>
                                </Border.StrokeShape>
                                <StackLayout Spacing="10" VerticalOptions="Center" Orientation="Horizontal">


                                    <Label Text="{Binding tourist_name}" VerticalOptions="Center"/>



                                </StackLayout>
                            </Border>

                        </DataTemplate>
                    </CollectionView.ItemTemplate>
                </CollectionView>
            </Grid>
        </AbsoluteLayout>
    </StackLayout>

</ContentPage>
```

3. Paste below code in the code behind

```
using Microsoft.Win32;
using Newtonsoft.Json;
using System.Collections.ObjectModel;
using System.Text;

namespace MauiApp4;

public partial class MainPage : ContentPage
{
    public ObservableCollection<Tourist> TouristCollection; 

	public MainPage()
	{
		InitializeComponent();
        TouristCollection = new ObservableCollection<Tourist>();
        GetTouristInfo(); 
	}

    private void GetTouristInfo()
    {
        var tourist = new Tourist
        {
            tourist_name = "Ali",
            tourist_email = "ali@hotmail.com",
            tourist_location = "KSA"
        };

        TouristCollection.Add(tourist);

        touristCollectionList.ItemsSource = TouristCollection;
    }

    public class Tourist
    {
        public string tourist_name { get; set; }
        public string tourist_email { get; set; }
        public string tourist_location { get; set; }
    }

   
}


```

4. Run the app on iOS

### Link to public reproduction project repository

[link](https://github.com/alfarajali/AbsoluteLayout-Bug-iOS)

### Version with bug

7.0.49

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 16.6

**Comment by drasticactions** [comment] 2023-06-23 08:18
My guess is this is the same as https://github.com/dotnet/maui/issues/15809, which should be fixed with should be fixed with https://github.com/dotnet/maui/pull/14951, with a backport to net7.0 (https://github.com/dotnet/maui/pull/15652) coming.

You could create a reproduction project to show this though, so we can both verify it with the same codebase on both ends that it is working? I understand that it can be a pain (especially when it's copy and pasting text) but this helps make verification consistent for everyone, to try and limit a "works on my machine" situation.

**Comment by alfarajali** [comment] 2023-06-23 10:51
I already provided the steps to reproduce the issue.

**Comment by alfarajali** [comment] 2023-06-23 10:51
I already provided the steps to reproduce the issue.

**Comment by drasticactions** [comment] 2023-06-23 13:22
@alfarajali I understand this, but I would like a complete reproduction project for the reasons I stated.

**Comment by alfarajali** [comment] 2023-06-26 09:43
Link to repro added.

**Comment by alfarajali** [comment] 2023-07-22 18:40
Is there any update or work around?

**Comment by XamlTest** [comment] 2023-07-27 03:15
Verified this on Visual Studio Enterprise 17.7.0 Preview 5.0. This issue does not repro on iOS 16.4 .NET 8, Android 13.0-API33 and Windows 11 with below Project:
[15808.zip](https://github.com/dotnet/maui/files/12178982/15808.zip)

![image](https://github.com/dotnet/maui/assets/97647558/df2ae285-8b14-45e0-8959-a6e61dec069f)

**Closed** 2023-08-03 13:01 UTC
Labels: t/bug, platform/iOS 🍎, area/collectionview 📃, s/triaged, s/needs-attention, s/try-latest-version, layout-absolute
