### ISSUE TITLE
Button and ImageButton command doesn't work on ContentPage shown using PushModalAsync

### ISSUE THREAD

**Issue by TarkusT** [dotnet/maui#17176] opened 2023-09-01 22:46 UTC
### Description

Button command doesn't work on ContentPage shown using PushModalAsync

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Did you find any workaround?

No I haven't yet

**Comment by jfversluis** [comment] 2024-02-27 11:40
Since this is an older issue already with no traction I am going to close this one. For future issues, please add more information than this. Having more information, screenshots, relevant code and ideally a reproduction project will help us to diagnose a potential issue quicker and also fix it sooner. 

If this is something that is still something you're hitting in more recent versions, please feel free to open a new issue with all the details requested. Thank you!

**Closed by jfversluis** 2024-02-27 11:40 UTC
Labels: t/bug, platform/android 🤖, s/needs-info, area/controls 🎮, s/needs-repro
