### ISSUE TITLE
SkiaSharp (or LiveCharts) causes crash in release mode

### ISSUE THREAD

**Issue by IgorKravchenko10** [dotnet/maui#11069] opened 2022-11-02 18:42 UTC
### Description

Hello!
I have a trouble with LiveCharts (LiveChartsCore.SkiaSharpView.Maui in NuGet).
First, it can't compile in release mode.
It says 
```
NETSDK1144 Optimizing assemblies for size failed. Optimization can be disabled by setting the PublishTrimmed property to false.
IL1011 Failed to write 'obj\Release\net7.0-android\android-arm64\linked\SkiaSharp.Views.Android.dll'.
```

After adding `<AndroidLinkMode>None</AndroidLinkMode>` to project file it compiles successfully but crashes after start.

```
<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net7.0-android|AnyCPU'">
		<AndroidLinkMode>None</AndroidLinkMode>
		<AndroidPackageFormat>aab</AndroidPackageFormat>
		<AndroidUseAapt2>True</AndroidUseAapt2>
		<AndroidCreatePackagePerAbi>False</AndroidCreatePackagePerAbi>
	</PropertyGroup>
```
I don't know whose issue is it (Mono, MAUI or LiveCharts), so tell me please if I posting issue in wrong project.

### Steps to Reproduce

1. Create a new MAUI project (I use .NET 7, didn't test on .NET 6).
2. Add LiveChartsCore.SkiaSharpView.Maui from NuGet.
3. Call .UseSkiaSharp(true) from builder in MauiProgram.
4. Try to compile in release mode. 
5. Ensure you have errors (Optimizing assemblies for size failed)
6. Add `<AndroidLinkMode>None</AndroidLinkMode>` to project and try to run again.
7. Ensure it compiles successfully but crashes after start.

### Link to public reproduction project repository

https://github.com/IgorKravchenko10/LiveChartsOrSkiaCrash

### Version with bug

7.0 Release Candidate 2

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 7, Android 12

### Relevant log output

```shell
Build started...
1>------ Build started: Project: LiveChartsOrSkiaCrash, Configuration: Release Any CPU ------
1>C:\Program Files\dotnet\sdk\7.0.100-rc.2.22477.23\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInference.targets(257,5): message NETSDK1057: You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy
1>C:\Users\Igor\source\repos\LiveChartsOrSkiaCrash\LiveChartsOrSkiaCrash\LiveChartsOrSkiaCrash.csproj : warning NU1603: LiveChartsOrSkiaCrash depends on Microsoft.Extensions.Configuration (>= 7.0.0-rc.2.22430.11) but Microsoft.Extensions.Configuration 7.0.0-rc.2.22430.11 was not found. An approximate best match of Microsoft.Extensions.Configuration 7.0.0-rc.2.22472.3 was resolved.
1>C:\Users\Igor\source\repos\LiveChartsOrSkiaCrash\LiveChartsOrSkiaCrash\LiveChartsOrSkiaCrash.csproj : warning NU1603: LiveChartsOrSkiaCrash depends on Microsoft.Extensions.DependencyInjection (>= 7.0.0-rc.2.22430.11) but Microsoft.Extensions.DependencyInjection 7.0.0-rc.2.22430.11 was not found. An approximate best match of Microsoft.Extensions.DependencyInjection 7.0.0-rc.2.22472.3 was resolved.
1>C:\Users\Igor\source\repos\LiveChartsOrSkiaCrash\LiveChartsOrSkiaCrash\LiveChartsOrSkiaCrash.csproj : warning NU1603: LiveChartsOrSkiaCrash depends on Microsoft.Extensions.Logging (>= 7.0.0-rc.2.22430.11) but Microsoft.Extensions.Logging 7.0.0-rc.2.22430.11 was not found. An approximate best match of Microsoft.Extensions.Logging 7.0.0-rc.2.22472.3 was resolved.
1>C:\Users\Igor\source\repos\LiveChartsOrSkiaCrash\LiveChartsOrSkiaCrash\LiveChartsOrSkiaCrash.csproj : warning NU1603: LiveChartsOrSkiaCrash depends on Microsoft.Extensions.Logging.Abstractions (>= 7.0.0-rc.2.22430.11) but Microsoft.Extensions.Logging.Abstractions 7.0.0-rc.2.22430.11 was not found. An approximate best match of Microsoft.Extensions.Logging.Abstractions 7.0.0-rc.2.22472.3 was resolved.
1>C:\Users\Igor\source\repos\LiveChartsOrSkiaCrash\LiveChartsOrSkiaCrash\LiveChartsOrSkiaCrash.csproj : warning NU1603: LiveChartsOrSkiaCrash depends on Microsoft.Extensions.Logging.Debug (>= 7.0.0-rc.2.22430.11) but Microsoft.Extensions.Logging.Debug 7.0.0-rc.2.22430.11 was not found. An approximate best match of Microsoft.Extensions.Logging.Debug 7.0.0-rc.2.22472.3 was resolved.
1>Skipping analyzers to speed up the build. You can execute 'Build' or 'Rebuild' command to run analyzers.
1>LiveChartsOrSkiaCrash -> C:\Users\Igor\source\repos\LiveChartsOrSkiaCrash\LiveChartsOrSkiaCrash\bin\Release\net7.0-android\LiveChartsOrSkiaCrash.dll
1>C:\Users\Igor\source\repos\LiveChartsOrSkiaCrash\LiveChartsOrSkiaCrash\LiveChartsOrSkiaCrash.csproj : warning NU1603: LiveChartsOrSkiaCrash depends on Microsoft.Extensions.Configuration (>= 7.0.0-rc.2.22430.11) but Microsoft.Extensions.Configuration 7.0.0-rc.2.22430.11 was not found. An approximate best match of Microsoft.Extensions.Configuration 7.0.0-rc.2.22472.3 was resolved.
1>C:\Users\Igor\source\repos\LiveChartsOrSkiaCrash\LiveChartsOrSkiaCrash\LiveChartsOrSkiaCrash.csproj : warning NU1603: LiveChartsOrSkiaCrash depends on Microsoft.Extensions.DependencyInjection (>= 7.0.0-rc.2.22430.11) but Microsoft.Extensions.DependencyInjection 7.0.0-rc.2.22430.11 was not found. An approximate best match of Microsoft.Extensions.DependencyInjection 7.0.0-rc.2.22472.3 was resolved.
1>C:\Users\Igor\source\repos\LiveChartsOrSkiaCrash\LiveChartsOrSkiaCrash\LiveChartsOrSkiaCrash.csproj : warning NU1603: LiveChartsOrSkiaCrash depends on Microsoft.Extensions.Logging (>= 7.0.0-rc.2.22430.11) but Microsoft.Extensions.Logging 7.0.0-rc.2.22430.11 was not found. An approximate best match of Microsoft.Extensions.Logging 7.0.0-rc.2.22472.3 was resolved.
1>C:\Users\Igor\source\repos\LiveChartsOrSkiaCrash\LiveChartsOrSkiaCrash\LiveChartsOrSkiaCrash.csproj : warning NU1603: LiveChartsOrSkiaCrash depends on Microsoft.Extensions.Logging.Abstractions (>= 7.0.0-rc.2.22430.11) but Microsoft.Extensions.Logging.Abstractions 7.0.0-rc.2.22430.11 was not found. An approximate best match of Microsoft.Extensions.Logging.Abstractions 7.0.0-rc.2.22472.3 was resolved.
1>C:\Users\Igor\source\repos\LiveChartsOrSkiaCrash\LiveChartsOrSkiaCrash\LiveChartsOrSkiaCrash.csproj : warning NU1603: LiveChartsOrSkiaCrash depends on Microsoft.Extensions.Logging.Debug (>= 7.0.0-rc.2.22430.11) but Microsoft.Extensions.Logging.Debug 7.0.0-rc.2.22430.11 was not found. An approximate best match of Microsoft.Extensions.Logging.Debug 7.0.0-rc.2.22472.3 was resolved.
1>C:\Users\Igor\source\repos\LiveChartsOrSkiaCrash\LiveChartsOrSkiaCrash\LiveChartsOrSkiaCrash.csproj : warning NU1603: LiveChartsOrSkiaCrash depends on Microsoft.Extensions.Configuration (>= 7.0.0-rc.2.22430.11) but Microsoft.Extensions.Configuration 7.0.0-rc.2.22430.11 was not found. An approximate best match of Microsoft.Extensions.Configuration 7.0.0-rc.2.22472.3 was resolved.
1>C:\Users\Igor\source\repos\LiveChartsOrSkiaCrash\LiveChartsOrSkiaCrash\LiveChartsOrSkiaCrash.csproj : warning NU1603: LiveChartsOrSkiaCrash depends on Microsoft.Extensions.DependencyInjection (>= 7.0.0-rc.2.22430.11) but Microsoft.Extensions.DependencyInjection 7.0.0-rc.2.22430.11 was not found. An approximate best match of Microsoft.Extensions.DependencyInjection 7.0.0-rc.2.22472.3 was resolved.
1>C:\Users\Igor\source\repos\LiveChartsOrSkiaCrash\LiveChartsOrSkiaCrash\LiveChartsOrSkiaCrash.csproj : warning NU1603: LiveChartsOrSkiaCrash depends on Microsoft.Extensions.Logging (>= 7.0.0-rc.2.22430.11) but Microsoft.Extensions.Logging 7.0.0-rc.2.22430.11 was not found. An approximate best match of Microsoft.Extensions.Logging 7.0.0-rc.2.22472.3 was resolved.
1>C:\Users\Igor\source\repos\LiveChartsOrSkiaCrash\LiveChartsOrSkiaCrash\LiveChartsOrSkiaCrash.csproj : warning NU1603: LiveChartsOrSkiaCrash depends on Microsoft.Extensions.Logging.Abstractions (>= 7.0.0-rc.2.22430.11) but Microsoft.Extensions.Logging.Abstractions 7.0.0-rc.2.22430.11 was not found. An approximate best match of Microsoft.Extensions.Logging.Abstractions 7.0.0-rc.2.22472.3 was resolved.
1>C:\Users\Igor\source\repos\LiveChartsOrSkiaCrash\LiveChartsOrSkiaCrash\LiveChartsOrSkiaCrash.csproj : warning NU1603: LiveChartsOrSkiaCrash depends on Microsoft.Extensions.Logging.Debug (>= 7.0.0-rc.2.22430.11) but Microsoft.Extensions.Logging.Debug 7.0.0-rc.2.22430.11 was not found. An approximate best match of Microsoft.Extensions.Logging.Debug 7.0.0-rc.2.22472.3 was resolved.
1>Optimizing assemblies for size may change the behavior of the app. Be sure to test after publishing. See: https://aka.ms/dotnet-illink
1>Optimizing assemblies for size may change the behavior of the app. Be sure to test after publishing. See: https://aka.ms/dotnet-illink
1>Optimizing assemblies for size. This process might take a while.
1>Optimizing assemblies for size. This process might take a while.
1>C:\Users\Igor\source\repos\LiveChartsOrSkiaCrash\LiveChartsOrSkiaCrash\LiveChartsOrSkiaCrash.csproj : warning NU1603: LiveChartsOrSkiaCrash depends on Microsoft.Extensions.Configuration (>= 7.0.0-rc.2.22430.11) but Microsoft.Extensions.Configuration 7.0.0-rc.2.22430.11 was not found. An approximate best match of Microsoft.Extensions.Configuration 7.0.0-rc.2.22472.3 was resolved.
1>C:\Users\Igor\source\repos\LiveChartsOrSkiaCrash\LiveChartsOrSkiaCrash\LiveChartsOrSkiaCrash.csproj : warning NU1603: LiveChartsOrSkiaCrash depends on Microsoft.Extensions.DependencyInjection (>= 7.0.0-rc.2.22430.11) but Microsoft.Extensions.DependencyInjection 7.0.0-rc.2.22430.11 was not found. An approximate best match of Microsoft.Extensions.DependencyInjection 7.0.0-rc.2.22472.3 was resolved.
1>C:\Users\Igor\source\repos\LiveChartsOrSkiaCrash\LiveChartsOrSkiaCrash\LiveChartsOrSkiaCrash.csproj : warning NU1603: LiveChartsOrSkiaCrash depends on Microsoft.Extensions.Logging (>= 7.0.0-rc.2.22430.11) but Microsoft.Extensions.Logging 7.0.0-rc.2.22430.11 was not found. An approximate best match of Microsoft.Extensions.Logging 7.0.0-rc.2.22472.3 was resolved.
1>C:\Users\Igor\source\repos\LiveChartsOrSkiaCrash\LiveChartsOrSkiaCrash\LiveChartsOrSkiaCrash.csproj : warning NU1603: LiveChartsOrSkiaCrash depends on Microsoft.Extensions.Logging.Abstractions (>= 7.0.0-rc.2.22430.11) but Microsoft.Extensions.Logging.Abstractions 7.0.0-rc.2.22430.11 was not found. An approximate best match of Microsoft.Extensions.Logging.Abstractions 7.0.0-rc.2.22472.3 was resolved.
1>C:\Users\Igor\source\repos\LiveChartsOrSkiaCrash\LiveChartsOrSkiaCrash\LiveChartsOrSkiaCrash.csproj : warning NU1603: LiveChartsOrSkiaCrash depends on Microsoft.Extensions.Logging.Debug (>= 7.0.0-rc.2.22430.11) but Microsoft.Extensions.Logging.Debug 7.0.0-rc.2.22430.11 was not found. An approximate best match of Microsoft.Extensions.Logging.Debug 7.0.0-rc.2.22472.3 was resolved.
1>C:\Users\Igor\source\repos\LiveChartsOrSkiaCrash\LiveChartsOrSkiaCrash\LiveChartsOrSkiaCrash.csproj : warning NU1603: LiveChartsOrSkiaCrash depends on Microsoft.Extensions.Configuration (>= 7.0.0-rc.2.22430.11) but Microsoft.Extensions.Configuration 7.0.0-rc.2.22430.11 was not found. An approximate best match of Microsoft.Extensions.Configuration 7.0.0-rc.2.22472.3 was resolved.
1>C:\Users\Igor\source\repos\LiveChartsOrSkiaCrash\LiveChartsOrSkiaCrash\LiveChartsOrSkiaCrash.csproj : warning NU1603: LiveChartsOrSkiaCrash depends on Microsoft.Extensions.DependencyInjection (>= 7.0.0-rc.2.22430.11) but Microsoft.Extensions.DependencyInjection 7.0.0-rc.2.22430.11 was not found. An approximate best match of Microsoft.Extensions.DependencyInjection 7.0.0-rc.2.22472.3 was resolved.
1>C:\Users\Igor\source\repos\LiveChartsOrSkiaCrash\LiveChartsOrSkiaCrash\LiveChartsOrSkiaCrash.csproj : warning NU1603: LiveChartsOrSkiaCrash depends on Microsoft.Extensions.Logging (>= 7.0.0-rc.2.22430.11) but Microsoft.Extensions.Logging 7.0.0-rc.2.22430.11 was not found. An approximate best match of Microsoft.Extensions.Logging 7.0.0-rc.2.22472.3 was resolved.
1>C:\Users\Igor\source\repos\LiveChartsOrSkiaCrash\LiveChartsOrSkiaCrash\LiveChartsOrSkiaCrash.csproj : warning NU1603: LiveChartsOrSkiaCrash depends on Microsoft.Extensions.Logging.Abstractions (>= 7.0.0-rc.2.22430.11) but Microsoft.Extensions.Logging.Abstractions 7.0.0-rc.2.22430.11 was not found. An approximate best match of Microsoft.Extensions.Logging.Abstractions 7.0.0-rc.2.22472.3 was resolved.
1>C:\Users\Igor\source\repos\LiveChartsOrSkiaCrash\LiveChartsOrSkiaCrash\LiveChartsOrSkiaCrash.csproj : warning NU1603: LiveChartsOrSkiaCrash depends on Microsoft.Extensions.Logging.Debug (>= 7.0.0-rc.2.22430.11) but Microsoft.Extensions.Logging.Debug 7.0.0-rc.2.22430.11 was not found. An approximate best match of Microsoft.Extensions.Logging.Debug 7.0.0-rc.2.22472.3 was resolved.
1>Optimizing assemblies for size may change the behavior of the app. Be sure to test after publishing. See: https://aka.ms/dotnet-illink
1>Optimizing assemblies for size. This process might take a while.
1>Optimizing assemblies for size may change the behavior of the app. Be sure to test after publishing. See: https://aka.ms/dotnet-illink
1>Optimizing assemblies for size. This process might take a while.
1>ILLink : error IL1011: Failed to write 'obj\Release\net7.0-android\android-arm\linked\SkiaSharp.Views.Android.dll'.
1>Fatal error in IL Linker
1>Unhandled exception. Mono.Linker.LinkerFatalErrorException: ILLink: error IL1011: Failed to write 'obj\Release\net7.0-android\android-arm\linked\SkiaSharp.Views.Android.dll'.
1> ---> System.ArgumentException: Member 'System.Int32 SKCanvasView_ignorePixelScaling' is declared in another module and needs to be imported
1>   at Mono.Cecil.MetadataBuilder.LookupToken(IMetadataTokenProvider provider)
1>   at Mono.Cecil.Cil.CodeWriter.WriteOperand(Instruction instruction)
1>   at Mono.Cecil.Cil.CodeWriter.WriteInstructions()
1>   at Mono.Cecil.Cil.CodeWriter.WriteResolvedMethodBody(MethodDefinition method)
1>   at Mono.Cecil.Cil.CodeWriter.WriteMethodBody(MethodDefinition method)
1>   at Mono.Cecil.MetadataBuilder.AddMethod(MethodDefinition method)
1>   at Mono.Cecil.MetadataBuilder.AddMethods(TypeDefinition type)
1>   at Mono.Cecil.MetadataBuilder.AddType(TypeDefinition type)
1>   at Mono.Cecil.MetadataBuilder.AddTypes()
1>   at Mono.Cecil.MetadataBuilder.BuildTypes()
1>   at Mono.Cecil.MetadataBuilder.BuildModule()
1>   at Mono.Cecil.MetadataBuilder.BuildMetadata()
1>   at Mono.Cecil.ModuleWriter.<>c.<BuildMetadata>b__2_0(MetadataBuilder builder, MetadataReader _)
1>   at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TItem item, Func`3 read)
1>   at Mono.Cecil.ModuleWriter.BuildMetadata(ModuleDefinition module, MetadataBuilder metadata)
1>   at Mono.Cecil.ModuleWriter.Write(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
1>   at Mono.Cecil.ModuleWriter.WriteModule(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
1>   at Mono.Cecil.ModuleDefinition.Write(String fileName, WriterParameters parameters)
1>   at Mono.Cecil.AssemblyDefinition.Write(String fileName, WriterParameters parameters)
1>   at Mono.Linker.Steps.OutputStep.WriteAssembly(AssemblyDefinition assembly, String directory, WriterParameters writerParameters)
1>   --- End of inner exception stack trace ---
1>   at Mono.Linker.Steps.OutputStep.WriteAssembly(AssemblyDefinition assembly, String directory, WriterParameters writerParameters)
1>   at Mono.Linker.Steps.OutputStep.WriteAssembly(AssemblyDefinition assembly, String directory)
1>   at Mono.Linker.Steps.OutputStep.OutputAssembly(AssemblyDefinition assembly)
1>   at Mono.Linker.Steps.OutputStep.ProcessAssembly(AssemblyDefinition assembly)
1>   at Mono.Linker.Steps.BaseStep.Process(LinkContext context)
1>   at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
1>   at Mono.Linker.Pipeline.Process(LinkContext context)
1>   at Mono.Linker.Driver.Run(ILogger customLogger)
1>   at Mono.Linker.Driver.Main(String[] args)
1>ILLink : error IL1011: Failed to write 'obj\Release\net7.0-android\android-arm64\linked\SkiaSharp.Views.Android.dll'.
1>Fatal error in IL Linker
1>Unhandled exception. Mono.Linker.LinkerFatalErrorException: ILLink: error IL1011: Failed to write 'obj\Release\net7.0-android\android-arm64\linked\SkiaSharp.Views.Android.dll'.
1> ---> System.ArgumentException: Member 'System.Int32 SKCanvasView_ignorePixelScaling' is declared in another module and needs to be imported
1>   at Mono.Cecil.MetadataBuilder.LookupToken(IMetadataTokenProvider provider)
1>   at Mono.Cecil.Cil.CodeWriter.WriteOperand(Instruction instruction)
1>   at Mono.Cecil.Cil.CodeWriter.WriteInstructions()
1>   at Mono.Cecil.Cil.CodeWriter.WriteResolvedMethodBody(MethodDefinition method)
1>   at Mono.Cecil.Cil.CodeWriter.WriteMethodBody(MethodDefinition method)
1>   at Mono.Cecil.MetadataBuilder.AddMethod(MethodDefinition method)
1>   at Mono.Cecil.MetadataBuilder.AddMethods(TypeDefinition type)
1>   at Mono.Cecil.MetadataBuilder.AddType(TypeDefinition type)
1>   at Mono.Cecil.MetadataBuilder.AddTypes()
1>   at Mono.Cecil.MetadataBuilder.BuildTypes()
1>   at Mono.Cecil.MetadataBuilder.BuildModule()
1>   at Mono.Cecil.MetadataBuilder.BuildMetadata()
1>   at Mono.Cecil.ModuleWriter.<>c.<BuildMetadata>b__2_0(MetadataBuilder builder, MetadataReader _)
1>   at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TItem item, Func`3 read)
1>   at Mono.Cecil.ModuleWriter.BuildMetadata(ModuleDefinition module, MetadataBuilder metadata)
1>   at Mono.Cecil.ModuleWriter.Write(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
1>   at Mono.Cecil.ModuleWriter.WriteModule(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
1>   at Mono.Cecil.ModuleDefinition.Write(String fileName, WriterParameters parameters)
1>   at Mono.Cecil.AssemblyDefinition.Write(String fileName, WriterParameters parameters)
1>   at Mono.Linker.Steps.OutputStep.WriteAssembly(AssemblyDefinition assembly, String directory, WriterParameters writerParameters)
1>   --- End of inner exception stack trace ---
1>   at Mono.Linker.Steps.OutputStep.WriteAssembly(AssemblyDefinition assembly, String directory, WriterParameters writerParameters)
1>   at Mono.Linker.Steps.OutputStep.WriteAssembly(AssemblyDefinition assembly, String directory)
1>   at Mono.Linker.Steps.OutputStep.OutputAssembly(AssemblyDefinition assembly)
1>   at Mono.Linker.Steps.OutputStep.ProcessAssembly(AssemblyDefinition assembly)
1>   at Mono.Linker.Steps.BaseStep.Process(LinkContext context)
1>   at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
1>   at Mono.Linker.Pipeline.Process(LinkContext context)
1>   at Mono.Linker.Driver.Run(ILogger customLogger)
1>   at Mono.Linker.Driver.Main(String[] args)
1>ILLink : error IL1011: Failed to write 'obj\Release\net7.0-android\android-x64\linked\SkiaSharp.Views.Android.dll'.
1>Fatal error in IL Linker
1>Unhandled exception. Mono.Linker.LinkerFatalErrorException: ILLink: error IL1011: Failed to write 'obj\Release\net7.0-android\android-x64\linked\SkiaSharp.Views.Android.dll'.
1> ---> System.ArgumentException: Member 'System.Int32 SKCanvasView_ignorePixelScaling' is declared in another module and needs to be imported
1>   at Mono.Cecil.MetadataBuilder.LookupToken(IMetadataTokenProvider provider)
1>   at Mono.Cecil.Cil.CodeWriter.WriteOperand(Instruction instruction)
1>   at Mono.Cecil.Cil.CodeWriter.WriteInstructions()
1>   at Mono.Cecil.Cil.CodeWriter.WriteResolvedMethodBody(MethodDefinition method)
1>   at Mono.Cecil.Cil.CodeWriter.WriteMethodBody(MethodDefinition method)
1>   at Mono.Cecil.MetadataBuilder.AddMethod(MethodDefinition method)
1>   at Mono.Cecil.MetadataBuilder.AddMethods(TypeDefinition type)
1>   at Mono.Cecil.MetadataBuilder.AddType(TypeDefinition type)
1>   at Mono.Cecil.MetadataBuilder.AddTypes()
1>   at Mono.Cecil.MetadataBuilder.BuildTypes()
1>   at Mono.Cecil.MetadataBuilder.BuildModule()
1>   at Mono.Cecil.MetadataBuilder.BuildMetadata()
1>   at Mono.Cecil.ModuleWriter.<>c.<BuildMetadata>b__2_0(MetadataBuilder builder, MetadataReader _)
1>   at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TItem item, Func`3 read)
1>   at Mono.Cecil.ModuleWriter.BuildMetadata(ModuleDefinition module, MetadataBuilder metadata)
1>   at Mono.Cecil.ModuleWriter.Write(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
1>   at Mono.Cecil.ModuleWriter.WriteModule(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
1>   at Mono.Cecil.ModuleDefinition.Write(String fileName, WriterParameters parameters)
1>   at Mono.Cecil.AssemblyDefinition.Write(String fileName, WriterParameters parameters)
1>   at Mono.Linker.Steps.OutputStep.WriteAssembly(AssemblyDefinition assembly, String directory, WriterParameters writerParameters)
1>   --- End of inner exception stack trace ---
1>   at Mono.Linker.Steps.OutputStep.WriteAssembly(AssemblyDefinition assembly, String directory, WriterParameters writerParameters)
1>   at Mono.Linker.Steps.OutputStep.WriteAssembly(AssemblyDefinition assembly, String directory)
1>   at Mono.Linker.Steps.OutputStep.OutputAssembly(AssemblyDefinition assembly)
1>   at Mono.Linker.Steps.OutputStep.ProcessAssembly(AssemblyDefinition assembly)
1>   at Mono.Linker.Steps.BaseStep.Process(LinkContext context)
1>   at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
1>   at Mono.Linker.Pipeline.Process(LinkContext context)
1>   at Mono.Linker.Driver.Run(ILogger customLogger)
1>   at Mono.Linker.Driver.Main(String[] args)
1>ILLink : error IL1011: Failed to write 'obj\Release\net7.0-android\android-x86\linked\SkiaSharp.Views.Android.dll'.
1>Fatal error in IL Linker
1>Unhandled exception. Mono.Linker.LinkerFatalErrorException: ILLink: error IL1011: Failed to write 'obj\Release\net7.0-android\android-x86\linked\SkiaSharp.Views.Android.dll'.
1> ---> System.ArgumentException: Member 'System.Int32 SKCanvasView_ignorePixelScaling' is declared in another module and needs to be imported
1>   at Mono.Cecil.MetadataBuilder.LookupToken(IMetadataTokenProvider provider)
1>   at Mono.Cecil.Cil.CodeWriter.WriteOperand(Instruction instruction)
1>   at Mono.Cecil.Cil.CodeWriter.WriteInstructions()
1>   at Mono.Cecil.Cil.CodeWriter.WriteResolvedMethodBody(MethodDefinition method)
1>   at Mono.Cecil.Cil.CodeWriter.WriteMethodBody(MethodDefinition method)
1>   at Mono.Cecil.MetadataBuilder.AddMethod(MethodDefinition method)
1>   at Mono.Cecil.MetadataBuilder.AddMethods(TypeDefinition type)
1>   at Mono.Cecil.MetadataBuilder.AddType(TypeDefinition type)
1>   at Mono.Cecil.MetadataBuilder.AddTypes()
1>   at Mono.Cecil.MetadataBuilder.BuildTypes()
1>   at Mono.Cecil.MetadataBuilder.BuildModule()
1>   at Mono.Cecil.MetadataBuilder.BuildMetadata()
1>   at Mono.Cecil.ModuleWriter.<>c.<BuildMetadata>b__2_0(MetadataBuilder builder, MetadataReader _)
1>   at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TItem item, Func`3 read)
1>   at Mono.Cecil.ModuleWriter.BuildMetadata(ModuleDefinition module, MetadataBuilder metadata)
1>   at Mono.Cecil.ModuleWriter.Write(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
1>   at Mono.Cecil.ModuleWriter.WriteModule(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
1>   at Mono.Cecil.ModuleDefinition.Write(String fileName, WriterParameters parameters)
1>   at Mono.Cecil.AssemblyDefinition.Write(String fileName, WriterParameters parameters)
1>   at Mono.Linker.Steps.OutputStep.WriteAssembly(AssemblyDefinition assembly, String directory, WriterParameters writerParameters)
1>   --- End of inner exception stack trace ---
1>   at Mono.Linker.Steps.OutputStep.WriteAssembly(AssemblyDefinition assembly, String directory, WriterParameters writerParameters)
1>   at Mono.Linker.Steps.OutputStep.WriteAssembly(AssemblyDefinition assembly, String directory)
1>   at Mono.Linker.Steps.OutputStep.OutputAssembly(AssemblyDefinition assembly)
1>   at Mono.Linker.Steps.OutputStep.ProcessAssembly(AssemblyDefinition assembly)
1>   at Mono.Linker.Steps.BaseStep.Process(LinkContext context)
1>   at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
1>   at Mono.Linker.Pipeline.Process(LinkContext context)
1>   at Mono.Linker.Driver.Run(ILogger customLogger)
1>   at Mono.Linker.Driver.Main(String[] args)
1>C:\Program Files\dotnet\sdk\7.0.100-rc.2.22477.23\Sdks\Microsoft.NET.ILLink.Tasks\build\Microsoft.NET.ILLink.targets(86,5): error NETSDK1144: Optimizing assemblies for size failed. Optimization can be disabled by setting the PublishTrimmed property to false.
1>Done building project "LiveChartsOrSkiaCrash.csproj" -- FAILED.
1>C:\Program Files\dotnet\sdk\7.0.100-rc.2.22477.23\Sdks\Microsoft.NET.ILLink.Tasks\build\Microsoft.NET.ILLink.targets(86,5): error NETSDK1144: Optimizing assemblies for size failed. Optimization can be disabled by setting the PublishTrimmed property to false.
1>Done building project "LiveChartsOrSkiaCrash.csproj" -- FAILED.
1>C:\Program Files\dotnet\sdk\7.0.100-rc.2.22477.23\Sdks\Microsoft.NET.ILLink.Tasks\build\Microsoft.NET.ILLink.targets(86,5): error NETSDK1144: Optimizing assemblies for size failed. Optimization can be disabled by setting the PublishTrimmed property to false.
1>Done building project "LiveChartsOrSkiaCrash.csproj" -- FAILED.
1>C:\Program Files\dotnet\sdk\7.0.100-rc.2.22477.23\Sdks\Microsoft.NET.ILLink.Tasks\build\Microsoft.NET.ILLink.targets(86,5): error NETSDK1144: Optimizing assemblies for size failed. Optimization can be disabled by setting the PublishTrimmed property to false.
1>Done building project "LiveChartsOrSkiaCrash.csproj" -- FAILED.
1>Done building project "LiveChartsOrSkiaCrash.csproj" -- FAILED.
```

**Comment by rachelkang** [comment] 2022-11-02 19:05
Hi, @IgorKravchenko10 - Are you able to reproduce this issue with only SkiaSharp (without LiveCharts)? If so, could you post an updated repro? Thanks :)

**Comment by IgorKravchenko10** [comment] 2022-11-02 19:11
> Hi, @IgorKravchenko10 - Are you able to reproduce this issue with only SkiaSharp (without LiveCharts)? If so, could you post an updated repro? Thanks :)

Hi, Rachel.
I didn't tested it with SkiaSharp only. Because I really don't know what exact package should I use =)
I mean I don't know exact name of package in NuGet.

**Comment by IgorKravchenko10** [comment] 2022-11-03 17:49
Hi!
I just want to say I updated repo.
Thanks.

**Comment by PureWeen** [comment] 2022-11-03 19:14
Duplicate of https://github.com/dotnet/sdk/issues/28880

**Closed by PureWeen** 2022-11-03 19:14 UTC
Labels: t/bug, s/needs-attention

**Comment by IgorKravchenko10** [comment] 2022-11-03 20:43
Update: adding `<AndroidLinkResources>false</AndroidLinkResources>` to project file helped. Thanks, @jonathanpeppers 
Note, `<AndroidLinkMode>None</AndroidLinkMode>` must be removed because it is still crashes after start.
So, the solution or workaround for now is to add `<AndroidLinkResources>false</AndroidLinkResources>` and remove  `<AndroidLinkMode>None</AndroidLinkMode>`.
P. S. My issue cannot be duplicate of https://github.com/dotnet/sdk/issues/28880 because I created this earlier but it's OK =)
