### ISSUE TITLE
Layout failure - children overflowing their bounding boxes in 7.0.86

### ISSUE THREAD

**Issue by BioTurboNick** [dotnet/maui#15195] opened 2023-05-20 12:52 UTC
### Description

My controls started resizing improperly in 7.0.86. They worked fine in 7.0.81.

But due to the state of the layout system (#15078) I don't know whether I was doing something wrong before that just happened to work, or if what's happening now is broken.

I'm ending up with children that overflow their parent bounding boxes.
![Screenshot_20230520_085542](https://github.com/dotnet/maui/assets/1438610/8d8198ec-615c-4e9a-ba1e-38130d1345db)
![Screenshot_20230520_085601](https://github.com/dotnet/maui/assets/1438610/0805e8ee-26db-4448-8a4b-be182d98f7ff)

The latter occurs when I start with one grid and press the "+" button that add a child. The width of the first one adjusts correctly but the height of the first expands for some reason.

The former occurs when I have two grids up and press the "-" button to remove the second child. I don't have a good explanation for why the height is correct but the width is expanded.

I'm guessing #14667 or #14165 are responsible.

Someone really needs to go through the layout system with a fine-toothed comb because something is rotten here.

### Steps to Reproduce

later

### Link to public reproduction project repository

not available

### Version with bug

7.0.86

### Last version that worked well

7.0.81

### Affected platforms

Android

### Affected platform versions

Android 12

**Comment by omghb** [comment] 2023-05-24 08:00
We see similar layout issues after upgrade from MAUI version **7.0.59** to **7.0.86**.

- Android 13: Layout failure 
   - children overflowing their bounding boxes
   - element size (width) is wrong
- iOS 16: Layout works correct

We are using a `Grid` / `ScrollView` / `FlexLayout` / `Grid` in one of the cases. Most new layouting issues seems to be when we are using the `FlexLayout` within the layout hierarchy.

**Comment by omghb** [comment] 2023-05-24 11:32
### Steps to Reproduce
1. Create new MAUI App (I used VS 2022 17.6.1 with target .NET 7.0)
2. Replace `MainPage.xaml` with:

```XML
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MauiApp1.MainPage">

    <ScrollView>
        <FlexLayout Wrap="Wrap" AlignItems="Start" AlignContent="Start">
            <VerticalStackLayout FlexLayout.Grow="1" Margin="10">
                <Grid RowDefinitions="47,3" BackgroundColor="Gray">
                    <Label Text="Some title" HorizontalOptions="Center" VerticalOptions="Center"/>
                    <BoxView Grid.Row="1" Color="Blue"/>
                </Grid>

                <Grid BackgroundColor="Red" Margin="0,5">
                    <Button x:Name="CounterBtn" HeightRequest="50" Text="Test Button" BackgroundColor="Green"/>
                    <BoxView Color="Blue" HeightRequest="1" VerticalOptions="Start"/>
                </Grid>
            </VerticalStackLayout>
        </FlexLayout>
    </ScrollView>

</ContentPage>
```

### Result
![image](https://github.com/dotnet/maui/assets/47421673/9b2661bf-7fcf-483b-9da9-34c4611d3ccd)
- Most left image: Android: The set `Margin="10"` is ignored on the right side for some elements.
- Next images: iOS and Windows: Layout looks correct.

Note:
- By removing the `BoxView` elements the layout issue does not occur.

**Comment by mobilewares** [comment] 2023-05-28 00:58
I'm seeing exact same problem with Grid control and * row/column values in Android and it's somewhat broken my App. It seems like when initial layout pass is done the host grid has a height/width of -1 (not IsNAN) and for some reason it decides the final height/width is around ~10% or so larger than what it should be resulting in the overflow issue.

A temporary workaround I'm experimenting with is to eventually go through the Row & Column definitions and using the final rendered height/width reapply Absolute values to the Row/Column Gridlength definitions . This seems to work (eventually), but trying to catch exactly when the actual height & width decides to return a non -1 value is difficult as the controls aren't throwing a SizeChanged events at appropriate time.

It's very frustrating to keep seeing regression issues on such fundamental parts of the layout system.  Due to using some 3rd party controls (Syncfusion) I'm also pretty much locked into the NET7.0 releases for immediate future too as NET8.0 is not supported yet.

**Comment by mobilewares** [comment] 2023-06-06 03:25
> Thanks for the sample @omghb! If you or the OP could turn this into a reproduction project, that would be great! I know it's frustrating to create projects for bugs, but it helps us have an accurate sample from all that we can test against that we know for sure doesn't work for you, so that if/when we can fix it, we can write tests against that exact code and you can validate it against your sample.

Hi @drasticactions or anyone else on the team. I can't seem to find any backlog items or pull requests (open/closed) etc for fixing the various reported .NET 7 MAUI Grid issues (introduced after NET7 SR3) & getting quite concerned it's not going to be fixed for next SR. Right now I still can't upgrade VS22 to latest 17.6 versions due to having to hold back at SR3 - apart from wanting MAUI fixes I need new VS22 versions for other dev too. 

Can someone please advise on what is going on with this? 

Thanks

**Comment by BobSammers** [comment] 2023-06-06 17:24
> Right now I still can't upgrade VS22 to latest 17.6 versions due to having to hold back at SR3

I've been having layout issues with Grid calculations changing in recent releases (I think it's this issue: Grid is suddenly calculating layouts larger than the screen).

In my case, the problem occurred starting with 7.0.86. VS is at the (current) latest, 15.6.2, but I have successfully downgraded Maui by putting the following line in the `PropertyGroup` at the top of the relevant csproj files:

``` xml
        ...
            <MauiVersion>7.0.81</MauiVersion>
        ...

**Comment by Hooterr** [comment] 2023-06-09 15:27
Similar issue: #15328

There's even more wrong with this. On iOS Grid seems to be completely broken. We're seeing that those bugs occur even if you don't use `BoxView` which seems to cause it at first.

I'm baffled that this got passed any QA. Did you even test what you released?

Oh, and, NO. The answer that it's fixed in .NET 8 is NOT an answer. This must be fixed IMMEDIATELY otherwise it's UNACCEPTABLE to wait until .net8 in Novermber.

**Comment by tylerwilson** [comment] 2023-06-13 21:34
Same issue here. I was focused on Android target, which works fine. Now I need to make iOS work, and as mentioned it appears the Grid is not doing what it is supposed to do. I have an AbsoluteLayout with an embedded Grid and VerticalStackLayout (for a popup menu like UI). 

I was hoping the just released 7.0.7 SDK would fix things, but I guess that does not include an updated MAUI. I used the suggestion above to go back to 7.0.81 version of MAUI, and that fixes it for me for now. 

I also agree saying 'try .NET 8' is an unacceptable answer. Even if it were to work, you can't expect us to ship a production app with that.

**Comment by XamlTest** [comment] 2023-07-18 03:05
Verified this on Visual Studio Enterprise 17.7.0 Preview 3.0. This issue repro on Android 13.0-API33 .NET 7, but not repro on Android 13.0-API33 .NET 8, Windows 11 and iOS 16.4 with below Project:
[MauiApp1.zip](https://github.com/dotnet/maui/files/12075470/MauiApp1.zip)

**.NET 7**:
![image](https://github.com/dotnet/maui/assets/97647558/c5f30323-cf74-41f8-9262-9fbe3e7f637c)
**.NET 8**:
![image](https://github.com/dotnet/maui/assets/97647558/c2fac31d-e5e0-4567-bb54-ae2d6ef5f818)

**Closed** 2023-07-25 13:01 UTC
Labels: t/bug, area/layout 🔲, s/triaged, s/needs-attention, s/try-latest-version

**Comment by BioTurboNick** [comment] 2023-07-30 04:20
Tested on 8.0.0-preview.6, still present.
