### ISSUE TITLE
GraphicsView Select Path.

### ISSUE THREAD

**Issue by essamce** [dotnet/maui#9451] opened 2022-08-16 07:07 UTC
### Description

It would be helpful to allow user select a path by tab from GraphicsView.

### Public API Changes

var gv = new GraphicsView();
var hitRes = gv.HitTestResult(); // new api

### Intended Use-Case

In my drawing app I want to let user edit drawing objects graphically.

**Comment by PureWeen** [comment] 2022-08-16 18:22
@essamce can you provide a bit more information. We're not quite clear on what you're asking for

**Comment by janseris** [comment] 2022-08-16 19:17
I suppose it's this:
https://github.com/dotnet/maui/issues/8235

**Comment by jfversluis** [comment] 2022-08-24 12:12
Duplicate of #8235

**Closed by jfversluis** 2022-08-24 12:12 UTC
Labels: t/enhancement ☀️, proposal/open, area/drawing ✏️, s/needs-attention
