### ISSUE TITLE
Navigation freeze the UI when clicking the [Back] button.

### ISSUE THREAD

**Issue by rwecho** [dotnet/maui#25597] opened 2024-10-30 10:59 UTC
### Description

https://github.com/user-attachments/assets/fa6410f3-1e4e-476b-8625-d480a30fbcee

It's just the blazor project default code. I move the blazor code to the second page.

### Steps to Reproduce

1. create a default MAUI blazor project and change the new MainPage() to new NavigationPage(new MainPage())
2. Create a second MAUI xaml Page.
3. Move the blazor code to the second page.
4. in the Main page, add a click button and navigate to the second page.
5. and Go back from second page.

### Version with bug

9.0.0-rc.2.24503.2

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.40 SR5

### Affected platforms

Windows

### Affected platform versions

windows10.0.19041.0

**Comment by jfversluis** [comment] 2024-10-30 11:16
Would you be able to provide us with the code of that project please?

**Comment by rwecho** [comment] 2024-10-30 12:31
[MauiApp21](https://github.com/rwecho/MauiApp21) the issue project. @jfversluis  thanks.

**Comment by PureWeen** [comment] 2024-10-31 19:28
Can you test with the latest nightly build? 
https://github.com/dotnet/maui/wiki/Nightly-Builds

**Comment by CathyZhu0110** [comment] 2024-11-01 08:38
> Can you test with the latest nightly build? https://github.com/dotnet/maui/wiki/Nightly-Builds

I tried the latest nightly build 9.0.10-ci.net9.24531.1, it works fine on it.

**Comment by Eilon** [comment] 2024-11-04 22:43
Sounds like a dupe of https://github.com/dotnet/maui/issues/24407, which was just fixed.

**Closed by Eilon** 2024-11-04 22:43 UTC
Labels: t/bug, platform/windows 🪟, area-blazor, s/triaged, s/needs-attention, s/try-latest-version, potential-regression

**Comment by SqueakyBed** [comment] 2024-11-12 23:51
On windows, I traced this all the way to `await Dispatcher.InvokeAsync(Dispose);` inside the Renderer.cs 
It hangs indefinitely trying to dispose the BlazorWebView renderer so the navigation never completes.
