### ISSUE TITLE
Click event fired even when button has views on top of it

### ISSUE THREAD

**Issue by nk-alex** [dotnet/maui#22442] opened 2024-05-16 08:21 UTC
### Description

- Having two views (A and B), view A on top of B. 
- Place in view B a button or whatever control with gesture recognizer. 
- When you click on screen, the tap or click event from view B is still raised.
- Since view A is on top, view B shouldn't be raising the click event.
- Even if view A is an ActivityIndicator, click still goes through it.

### Steps to Reproduce

```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             Title="{Binding Title}"
             x:Class="MyApp.Views.MainPage">

	<Grid>
		<Button Text="Click me" Clicked="Button_Clicked"/>

		<Grid BackgroundColor="Red">
			<Grid.RowDefinitions>
				<RowDefinition Height="*"/>
				<RowDefinition Height="200"/>
				<RowDefinition Height="*"/>
			</Grid.RowDefinitions>

			<Grid.ColumnDefinitions>
				<ColumnDefinition Width="*"/>
				<ColumnDefinition Width="200"/>
				<ColumnDefinition Width="*"/>
			</Grid.ColumnDefinitions>
		</Grid>
	</Grid>
</ContentPage>
```

### Version with bug

8.0.21 SR4.1

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

android 21

### Did you find any workaround?

Make the view on top have any type of gesture recognizer itself. In this sample it's a tap gesture, but also works with swipe gesture. Although I don't think this workaround is really viable.

```
<Grid>
	<Button Text="Click me" Clicked="Button_Clicked"/>

	<Grid BackgroundColor="Red">
		<Grid.GestureRecognizers>
			<TapGestureRecognizer NumberOfTapsRequired="1" Tapped="TapGestureRecognizer_Tapped"/>
		</Grid.GestureRecognizers>
		<Grid.RowDefinitions>
			<RowDefinition Height="*"/>
			<RowDefinition Height="200"/>
			<RowDefinition Height="*"/>
		</Grid.RowDefinitions>

		<Grid.ColumnDefinitions>
			<ColumnDefinition Width="*"/>
			<ColumnDefinition Width="200"/>
			<ColumnDefinition Width="*"/>
		</Grid.ColumnDefinitions>
	</Grid>
</Grid>
```

**Comment by kevinxufei** [comment] 2024-05-16 09:34
Can repro this issue at Android platform on the latest 17.10 Preview 7(8.0.21/8.0.40).

**Comment by mattleibow** [comment] 2024-05-30 17:33
Duplicate of https://github.com/dotnet/maui/issues/10252

**Closed by mattleibow** 2024-05-30 17:33 UTC
Labels: t/bug, platform/android 🤖, s/verified, area-controls-button, s/triaged
