### ISSUE TITLE
Background Color for Label and entry does not update when removing the existing color

### ISSUE THREAD

**Issue by drasticactions** [dotnet/maui#10177] opened 2022-09-16 23:28 UTC
### Description

This was found by internal testers working on XAML Hot Reload. Checking the underlying issue, I think is this a MAUI bug or regression. If you try and do the same actions from code behind, you get the same results. The color values seem to be set correctly but are not updated to reflect their true value.

![ed41fb2f-2830-4844-976c-1c0734678f70](https://user-images.githubusercontent.com/898335/190830197-79a16b45-3660-47c8-9c6c-40f31df336e8.gif)

### Steps to Reproduce

1. Create a MAUI or MAUI Blazor App
2. Choose Android emulator from device list
3. Debug
4. Add BackgroundColor='red' to <Label> or<Entry>
The BackgroundColor of <Label> or<Entry> changes to red (Currently, it is found that only these two controls have problems, and the rest have no problems)
5. Delete BackgroundColor='red'
6. Observe Android emulator

### Link to public reproduction project repository

Use a template project with the steps from above.

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

N/A

**Comment by PureWeen** [comment] 2022-09-16 23:39
This is basically a duplicate of

https://github.com/dotnet/maui/issues/8210
https://github.com/dotnet/maui/issues/6350

**Comment by PureWeen** [comment] 2022-09-16 23:43
For now we need to define the BGColor for Label in our templates so there's a color to revert to

https://github.com/dotnet/maui/blob/main/src/Templates/src/templates/maui-mobile/Resources/Styles/Styles.xaml#L148-L164

**Comment by drasticactions** [comment] 2022-09-17 00:00
I'm happy to dupe it to the general one. Right now my mode is "File first, triage later" ;)

**Comment by PureWeen** [comment] 2022-09-17 00:45
@drasticactions yea, the fix for this one is to see if we can update our template to make this case work. Which is hopefully an easy path.

**Closed** 2022-09-19 10:15 UTC
Labels: t/bug, partner/ui-tools
