### ISSUE TITLE
MAUI_splashscreen: How to set Splash screen for Light and Dark mode for iOS and Android

### ISSUE THREAD

**Issue by muffadal53** [dotnet/maui#12944] opened 2023-01-26 17:19 UTC
### Description

Can someone please guide details with snippet on how to set Splash screen for Light and Dark mode for iOS and Android as we are migrating from Xamarin Forms to MAUI and I am not able to find documentation mentioning details for both mode. The documentation we are referring currently is at this link "https://learn.microsoft.com/en-us/dotnet/maui/user-interface/images/splashscreen?view=net-maui-7.0&tabs=android"

Thanks.

### Steps to Reproduce

Splash screen for Light and Dark mode for iOS and Android.

### Link to public reproduction project repository

https://learn.microsoft.com/en-us/dotnet/maui/user-interface/images/splashscreen?view=net-maui-7.0&tabs=android

### Version with bug

7.0 (current)

### Last version that worked well

7.0 (current)

### Affected platforms

iOS, Android

### Affected platform versions

iOS, Android

**Comment by muffadal53** [comment] 2023-09-13 15:34
@jfversluis: Can you please tell us when the fix for this will be available. Will it be part of .Net 8 release?

**Comment by muffadal53** [comment] 2023-09-27 14:00
> Hi @muffadal53 this is not a bug at this time and will not be included in .NET 8. This is something that we could make easier to work with, but that is an enhancement. If you want to do this today you should be able to by leveraging the platform functionalities for this.
> 
> For more information have a look at these blog posts:
> 
> * https://blog.ewers-peters.de/lets-customize-the-splash-screen-of-a-maui-app
> * https://codetraveler.io/2019/10/11/creating-a-dark-mode-splash-screen/

@jfversluis : I went through the blog posts and below are my observations and queries:

1. https://blog.ewers-peters.de/lets-customize-the-splash-screen-of-a-maui-app:

       a. This approach which is based on "MauiSplashScreen" doesn't work on my side and its only for Android.


3. https://codetraveler.io/2019/10/11/creating-a-dark-mode-splash-screen/:

a.  Do you mean this we should refer for iOS?
b.  As this is not based on MAUI "MauiSplashScreen", so should we remove the "MauiSplashScreen" entry from .csproj?
c. As, we don't have the things like "Assets" and "Asset Catalog" for iOS in MAUI skeleton, then shall we create the same in the MAUI application to get the splash screen for Light and dark modes?

I still strongly feel that even if it has to be done natively there should be proper documentation of how to achieve the same in .Net MAUI.

Awaiting your reply.

**Comment by muffadal53** [comment] 2023-11-04 12:10
@jsuarezruiz Awaiting reply on detail explanation on how to achieve this in MAUI as there is no documentation related to this.

**Comment by kramer-e** [comment] 2024-01-04 14:58
In the first blogpost he states that the background (within circle) cannot be changed, but that is not correct. You can use a png with transparant background and define `maui_splash_color` color in the respective `/values/colors.xml`  and `/values-night/colors.xml` files.

See the full explanation here: https://github.com/dotnet/maui/issues/9578#issuecomment-1666592448

**Comment by muffadal53** [comment] 2024-01-08 07:24
Hi @jfversluis / @jsuarezruiz / @kramer-e 

> In the first blogpost is stated that the background (within circle) cannot be changed, but that is not correct. You can use a png with transparant background and define `maui_splash_color` color in the respective `/values/colors.xml` and `/values-night/colors.xml` files.
> 
> See the full explanation here: [#9578 (comment)](https://github.com/dotnet/maui/issues/9578#issuecomment-1666592448)

Thanks @kramer-e  for your input will check the comment you shared.

**Comment by muffadal53** [comment] 2024-01-08 07:24
> > In the first blogpost is stated that the background (within circle) cannot be changed, but that is not correct. You can use a png with transparant background and define `maui_splash_color` color in the respective `/values/colors.xml` and `/values-night/colors.xml` files.
> > See the full explanation here: [#9578 (comment)](https://github.com/dotnet/maui/issues/9578#issuecomment-1666592448)
> 
> Thanks @kramer-e for your input will check the comment you shared.

**Comment by muffadal53** [comment] 2024-01-08 07:26
Hi @jfversluis / @jsuarezruiz : Can we have a sample application explaining on how to add Splash screen for Light and Dark mode for iOS and Android in .Net MAUI using .Net 7. This will really be appreciated and helpful for everyone.

Thanks.

**Comment by e1T** [comment] 2024-03-21 10:54
I have been able to use a single image and added a transparent background.

For Android I simply managed to get it working by adding this to the csproj file:
`<MauiSplashScreen Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) != 'ios'" Include="Resources\Splash\splashscreen.svg" Color="#00000000" BaseSize="128,128" />`

For iOS it worked using a native storyboard as explained by @jfversluis in this [Youtube video](https://www.youtube.com/watch?v=xkHNbrpi3ZQ).

**Comment by breyed** [comment] 2024-06-03 11:52
I ended up conditioning `MauiSplashScreen` to only apply to Android and adding code to `Info.plist` for a blank splash screen that matches light appearance or Dark Mode.

``` xml
<key>UILaunchScreen</key>
<dict>
</dict>
```

The app startup time (with MAUI and `<TrimMode>full</TrimMode>`) is fast enough that this approach is probably better than an image that doesn’t align with the subsequent UI.

**Comment by jfversluis** [comment] 2024-08-12 08:14
Duplicate of #9578

**Closed by jfversluis** 2024-08-12 08:14 UTC
Labels: t/enhancement ☀️, area-single-project, platform/android 🤖, platform/iOS 🍎
