### ISSUE TITLE
[MAUI][.NET8] Search for a recipe with "fries" first result is not "Alpine fries".

### ISSUE THREAD

**Issue by Zhanglirong-Winnie** [dotnet/maui#21005] opened 2024-03-05 07:16 UTC
### Description

1.Deploy https://github.com/rachelkang/recipeSearch to Windows/Android/iOS/MacOS
2.Type "fries" into the search recipe bar.
3.Click the search button to search (hit Enter)

**Actual results:**
“Alpine fries” was not the first result, Search results are out of order.
![image](https://github.com/dotnet/maui/assets/77434865/ec25a98e-35d6-4190-b00b-b03e1774af2d)

**Expected results:**
"Alpine fries" is the first results

### Link to public reproduction project repository

https://github.com/rachelkang/recipeSearch

### Version with bug

9.0.0-preview.1.9973

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

**Comment by PureWeen** [comment] 2024-03-05 19:29
Duplicate of #21006

**Closed by PureWeen** 2024-03-05 19:29 UTC
Labels: t/bug, platform/macOS 🍏, platform/windows 🪟, platform/android 🤖, platform/iOS 🍎, area/testing, csi-new, testing-manual
