### ISSUE TITLE
.NET Maui Secondary ToolbarItem Issue on Windows

### ISSUE THREAD

**Issue by Auto72** [dotnet/maui#18258] opened 2023-10-23 13:48 UTC
### Description

The secondary toolbar items text color on Windows are displayed with the white color on a white background. 
The text color should be black on white background, or the background should be the same as the title bar.
In one way or another, the text must be readable.
In addiction it seems on the bottom there is a room for another item that it is not present, I don't know if it is an attempt to be the shadow of the menu.

### Steps to Reproduce

See the linked example.

    <ContentPage.ToolbarItems>
        <ToolbarItem Text="Opt#1" Order="Primary"/>
        <ToolbarItem Text="Opt#2" Order="Primary"/>
        <ToolbarItem Text="Option #3" Order="Secondary" />
        <ToolbarItem Text="Option #4" Order="Secondary" />
        <ToolbarItem Text="Option #5" Order="Secondary" />
        <ToolbarItem Text="Option #6" Order="Secondary" />
    </ContentPage.ToolbarItems>

### Link to public reproduction project repository

https://github.com/Auto72/TestToolbarItem

### Version with bug

8.0.0-rc.2.9373

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 11

### Did you find any workaround?

No.

![1](https://github.com/dotnet/maui/assets/52780377/22b67b66-8419-41e8-ae8f-6936eb4aee54)

**Comment by XamlTest** [comment] 2023-10-26 06:47
Verified this on Visual Studio Enterprise 17.8.0 Preview 5.0(8.0.0-rc.2.9373). Repro on Windows 11, not repro on Android 14.0-API34 and iOS 16.4 with below Project:
[TestToolbarItem.zip](https://github.com/dotnet/maui/files/13173826/TestToolbarItem.zip)

**Comment by david-maw** [comment] 2024-06-27 21:58
I'd add the ellipsis on the primary toolbar looks like it's always black so it can collide with user selected icon colors in light mode and is invisible in dark mode.

**Comment by Auto72** [comment] 2024-07-03 14:40
Any workaround ?

**Comment by Auto72** [comment] 2024-07-10 11:55
I made an attempt, but with no luck.

`#if WINDOWS
        Microsoft.Maui.Handlers.ToolbarHandler.Mapper.AppendToMapping("MyToolbarCustomization", (handler, view) =>
        {
            if (handler.PlatformView is Microsoft.UI.Xaml.Controls.AppBar appBar) 
            { 
                appBar.Background = new Microsoft.UI.Xaml.Media.SolidColorBrush(Microsoft.UI.Colors.Red);
            }
            if (handler.PlatformView is Microsoft.UI.Xaml.Controls.CommandBar cb)
            {
                cb.Background = new Microsoft.UI.Xaml.Media.SolidColorBrush(Microsoft.UI.Colors.Red);

                // NOTE: This loop doesn't work but cb.SecondaryCommands has some native handles.
                foreach (var item in cb.SecondaryCommands)
                {
                    Debug.WriteLine($"Type: {item.GetType()}");

                    if (item is AppBarButton appBarButton)
                    {
                        appBarButton.Background = new Microsoft.UI.Xaml.Media.SolidColorBrush(Microsoft.UI.Colors.Red);
                    }
                    else if (item is AppBarToggleButton appBarToggleButton)
                    {
                        appBarToggleButton.Background = new Microsoft.UI.Xaml.Media.SolidColorBrush(Microsoft.UI.Colors.Red);
                    }
                }
            }

        });
#endif`

**Comment by mdelgadov** [comment] 2024-07-31 21:28
to add Insult to injury, the container shows a weird second section "below" the first as so:
<img width="124" alt="image" src="https://github.com/user-attachments/assets/8e7bf366-a6c2-4925-95ef-20d0e140315d">
Also, there is no way to style the toolbar and or the toolbaritems...
Also, this is happening with .net 9 prev 6 and has been happening at least since .net 6

**Comment by mtanksl** [comment] 2024-08-04 19:17
I know this is a Windows bug report, but it looks like the same problem still occurs in Android. I am not using Shell.

I cannot, for heaven's sake, change the color to white of the overflow icon (3 dots, ellipsis, or whatever it's called) that is used for secondary items on toolbar on the MAUI Android platform:

![image](https://github.com/user-attachments/assets/f51047f3-bd16-4640-8f63-3131024e6ace)

It completely ignores any Android **styles.xml**, for example the **Theme.MaterialComponents.Light.DarkActionBar** parent theme or the **android:actionOverflowMenuStyle** property.

The only way I found to change the toolbar background and text color is to use the Application.Resources's Style, like so:

```xml
<Style TargetType="NavigationPage">
  <Setter Property="BarBackgroundColor" Value="{StaticResource ColorPrimary}" />
  <Setter Property="BarTextColor" Value="{StaticResource White}" />
  <Setter Property="IconColor" Value="{StaticResource White}" />
</Style>
```

...but the overflow icon does not change, it always stays black.

**Comment by OliveInto** [comment] 2024-08-11 06:10
I find a bad workaground by testing for nearly 5 hours.
![image](https://github.com/user-attachments/assets/d668b83e-0fd1-4fde-93a1-eab90686593f)


```

 Microsoft.Maui.Handlers.ToolbarHandler.Mapper.AppendToMapping("MyCustomization", (handler, view) =>
 {

     handler.PlatformView.FontSize = 14;
     handler.PlatformView.SizeChanged += (f, o) =>
     {
         var toolbar = f as Microsoft.Maui.Platform.MauiToolbar;                 
         var grid = toolbar.Content as Microsoft.UI.Xaml.Controls.Grid;
         dynamic k = grid.Children[grid.Children.Count - 2];
         k.Child.FontSize = 28;                    
     };
     //handler.PlatformView.BackgroundSizing= Microsoft.UI.Xaml.Controls.BackgroundSizing.InnerBorderEdge;
 });
```

The Maui toolbar uses winui, it is made by a grid that is composed by 4 units. I firstly change the them at all, and try to get the Tile property back to normal, since it is make of Winui Textblock. Why not try to find the Secondary ToolbarItems? They are not loaded until page needs them. Thus if there are no secondary toolbaritems in the shell page, using dynamic will cause errors.

**Comment by Auto72** [comment] 2024-08-27 07:57
> I find a bad workaground by testing for nearly 5 hours. ![image](https://private-user-images.githubusercontent.com/51261010/356854300-d668b83e-0fd1-4fde-93a1-eab90686593f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3NDUzNDcsIm5iZiI6MTcyNDc0NTA0NywicGF0aCI6Ii81MTI2MTAxMC8zNTY4NTQzMDAtZDY2OGI4M2UtMGZkMS00ZmRlLTkzYTEtZWFiOTA2ODY1OTNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDA3NTA0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzZDBjMTc1OTZlYTdlNmUyNzc2MTBjMzdlMzkwZjgyNzRhYmRjNzUzNjNiYzU2MDQxY2VkNTQ3ZmU5NTM0ZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nOX7qrhdT-RwYcqQQg9lETnxr6l1hCFYwESEOhaHeZE)
> 
> ```
> 
>  Microsoft.Maui.Handlers.ToolbarHandler.Mapper.AppendToMapping("MyCustomization", (handler, view) =>
>  {
> 
>      handler.PlatformView.FontSize = 14;
>      handler.PlatformView.SizeChanged += (f, o) =>
>      {
>          var toolbar = f as Microsoft.Maui.Platform.MauiToolbar;                 
>          var grid = toolbar.Content as Microsoft.UI.Xaml.Controls.Grid;
>          dynamic k = grid.Children[grid.Children.Count - 2];
>          k.Child.FontSize = 28;                    
>      };
>      //handler.PlatformView.BackgroundSizing= Microsoft.UI.Xaml.Controls.BackgroundSizing.InnerBorderEdge;
>  });
> ```
> 
> The Maui toolbar uses winui, it is made by a grid that is composed by 4 units. I firstly change the them at all, and try to get the Tile property back to normal, since it is make of Winui Textblock. Why not try to find the Secondary ToolbarItems? They are not loaded until page needs them. Thus if there are no secondary toolbaritems in the shell page, using dynamic will cause errors.

This works great about resizing the secondary menu, but it doesn't work for the colour of secondary menu. 
I still get the text white on a almost white background  (light grey) as reported in the picture at the beginning of this thread.
I can't figure out how to change it, but for a WinUI 3 expert should be easy enough.

**Comment by OliveInto** [comment] 2024-09-08 10:07
> > I find a bad workaground by testing for nearly 5 hours. ![image](https://private-user-images.githubusercontent.com/51261010/356854300-d668b83e-0fd1-4fde-93a1-eab90686593f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3NDUzNDcsIm5iZiI6MTcyNDc0NTA0NywicGF0aCI6Ii81MTI2MTAxMC8zNTY4NTQzMDAtZDY2OGI4M2UtMGZkMS00ZmRlLTkzYTEtZWFiOTA2ODY1OTNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDA3NTA0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzZDBjMTc1OTZlYTdlNmUyNzc2MTBjMzdlMzkwZjgyNzRhYmRjNzUzNjNiYzU2MDQxY2VkNTQ3ZmU5NTM0ZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nOX7qrhdT-RwYcqQQg9lETnxr6l1hCFYwESEOhaHeZE)
> > ```
> > 
> >  Microsoft.Maui.Handlers.ToolbarHandler.Mapper.AppendToMapping("MyCustomization", (handler, view) =>
> >  {
> > 
> >      handler.PlatformView.FontSize = 14;
> >      handler.PlatformView.SizeChanged += (f, o) =>
> >      {
> >          var toolbar = f as Microsoft.Maui.Platform.MauiToolbar;                 
> >          var grid = toolbar.Content as Microsoft.UI.Xaml.Controls.Grid;
> >          dynamic k = grid.Children[grid.Children.Count - 2];
> >          k.Child.FontSize = 28;                    
> >      };
> >      //handler.PlatformView.BackgroundSizing= Microsoft.UI.Xaml.Controls.BackgroundSizing.InnerBorderEdge;
> >  });
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The Maui toolbar uses winui, it is made by a grid that is composed by 4 units. I firstly change the them at all, and try to get the Tile property back to normal, since it is make of Winui Textblock. Why not try to find the Secondary ToolbarItems? They are not loaded until page needs them. Thus if there are no secondary toolbaritems in the shell page, using dynamic will cause errors.
> 
> This works great about resizing the secondary menu, but it doesn't work for the colour of secondary menu. I still get the text white on an almost white background (light grey) as reported in the picture at the beginning of this thread. I can't figure out how to change it, but for a WinUI 3 expert should be easy enough. The text should always be black whether the item is selected or not. Not black only when it is selected.

Sorry for not checking it, the handlers do not have property to change the color, but I got a new way using reflection. I get the Winui3 AppbarButton and change them when commandbar get focused. 

As for the strange padding, I guess this is caused by Winui3 bugs, I cannot deal with it.

```
            Microsoft.Maui.Handlers.ToolbarHandler.Mapper.AppendToMapping("MyCustomization", (handler, view) =>
            {
#if WINDOWS
               // handler.PlatformView.FontSize = 14;
                handler.PlatformView.GotFocus += (f, o) =>
                {
                    var toolbar = f as Microsoft.Maui.Platform.MauiToolbar;
                    var commandBarInfo = toolbar!.GetType().GetProperty("CommandBar", BindingFlags.NonPublic | BindingFlags.Instance);
                    var commandbar = commandBarInfo.GetValue(toolbar);
                    foreach (AppBarButton button in (commandbar as Microsoft.UI.Xaml.Controls.CommandBar).SecondaryCommands)
                    {
                        button.UpdateTextColor(Color.FromArgb("#512BD4"));
                        button.FontSize = 14;
                    }
                };
#endif

            });
```
![image](https://github.com/user-attachments/assets/50935397-bbd6-4eef-84f7-6535073b31b9)

**Comment by Auto72** [comment] 2024-09-09 07:34
Thank you @OliveInto it does work!

using Microsoft.Maui.Platform;

#if WINDOWS
        Microsoft.Maui.Handlers.ToolbarHandler.Mapper.AppendToMapping("MyCustomizationTB", (handler, view) =>
        {
            // FIX x Menu size
            handler.PlatformView.FontSize = 14;
            handler.PlatformView.SizeChanged += (f, o) =>
            {
                var toolbar = f as Microsoft.Maui.Platform.MauiToolbar;
                //toolbar.Background = new Microsoft.UI.Xaml.Media.SolidColorBrush(Windows.UI.Color.FromArgb(50, 230, 230, 250));

                var grid = toolbar?.Content as Microsoft.UI.Xaml.Controls.Grid;
                if (grid != null)
                {                    
                    dynamic k = grid.Children[^2];
                    k.Child.FontSize = 28;
                }
            };

            // FIX x Menu items color
            handler.PlatformView.GotFocus += (f, o) =>
            {
                var toolbar = f as Microsoft.Maui.Platform.MauiToolbar;
                var commandBarInfo = toolbar!.GetType().GetProperty("CommandBar", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance);
                var commandbar = commandBarInfo.GetValue(toolbar);
                foreach (Microsoft.UI.Xaml.Controls.AppBarButton button in (commandbar as Microsoft.UI.Xaml.Controls.CommandBar).SecondaryCommands.Cast<Microsoft.UI.Xaml.Controls.AppBarButton>())
                {
                    button.UpdateTextColor(Color.FromArgb("#512BD4"));
                    button.FontSize = 14;
                }
            };
        });
#endif

**Comment by PureWeen** [comment] 2024-12-06 21:51
Duplicate of #7156

**Closed by PureWeen** 2024-12-06 21:51 UTC
Labels: t/bug, platform/windows 🪟, s/verified, s/triaged, area-controls-toolbar
