### ISSUE TITLE
Crashes in apps built with visual studio 17.6.*

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#16001] opened 2023-07-05 16:22 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Crashes-in-apps-built-with-visual-studio/10398225)._

---
[severity:I'm unable to use this version] [regression] [worked-in:17.5.*]
After updating to 17.6.3 our maui project has been unstable. I recreated the issue in the sample project attached. This is very stable in 17.5.0 +17.5.3.
I have confirmed the crash in 17.6.2, 17.6.3, 17.6.4

If you change the Text of all Labels in the test example to "test" it will not crash.
Also changing the ColumnDefinition from *,*,*,* to 135,135,135,135 it will work.
I guess it is a size calculation issue.

---
#### Feedback Bot on 6/24/2023, 11:20 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by gorkhadk** [comment] 2023-08-09 11:08
https://github.com/gorkhadk/maui_crash_reproduction

**Comment by gorkhadk** [comment] 2023-08-15 12:07
Bump

**Comment by samhouts** [comment] 2023-08-17 16:49
Duplicate of #16475

**Closed by samhouts** 2023-08-17 16:49 UTC
Labels: t/bug, area/layout 🔲, control-label, s/needs-attention, i/regression, s/try-latest-version
