### ISSUE TITLE
CollectionView on windows no longer resizes width when resizing window

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#13924] opened 2023-03-14 16:44 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/collectionview-on-windows-no-longer-resi/10282554)._

---
[severity:I'm unable to use this version] [regression] [worked-in:17.4.4]
.net 7, collectionview would resize it's width when resizing the window.   It also doesn't always display initially until the window is resized a bit.  Works in 17.4.4.  Stops working if I install the preview 17.5 alongside it or the just new 17.4.5.
I guess the preview upgrades MAUI caused the problem even if I use 17.4.4 on that machine.

---
#### Feedback Bot on 2/16/2023, 06:44 PM: 

(private comment, text removed)
#### bill.hamshire on 2/16/2023, 07:27 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by mdbill** [comment] 2023-03-21 15:22
I've been on vacation. Once Maui upgrades beyond 7.0.59 I'll test it again. It may have been fixed by another resolved issue.

**Comment by mdbill** [comment] 2023-04-25 21:42
I tried again on the latest Maui 7.0.81. still broken. The main collectionView in a refreshview, the width will not resize at all. Another collecitonview I have: the width will get smaller and then stretch back wider, but still stops at the original size, in other words, it can never get wider than when the window first draws.  
works with
		<MauiVersion>7.0.52</MauiVersion>
but I can't stay on that version forever.
personal side note: After 5 years of Xamarin/Maui, I'm now a dedicated Flutter developer and could not be happier.  Github Copilot or ChatGPT is the secret that will let you make the leap easily.

**Comment by samhouts** [comment] 2023-08-11 16:49
Duplicate of #15519

**Closed by samhouts** 2023-08-11 16:49 UTC
Labels: t/bug, platform/windows 🪟, area/collectionview 📃, s/needs-attention, i/regression
