### ISSUE TITLE
ImageButton with FontImageSource becomes invisible on ContentPage (but can still be clicked) if you move away from the tab and come back to the tab

### ISSUE THREAD

**Issue by pentagramme** [dotnet/maui#14587] opened 2023-04-14 15:34 UTC
### Description

I have a small app with two Tabs. On the second Tab there is a ContentPage with a Grid and inside one cell of the Grid, I have positioned an ImageButton with a Source set to FontImageSource. The ImageSource contains simply the letter "A". in the code behind Clicked event I change the color to a different color. The letter A gets a new color. Until now everything works fine.
In the app I change to a different Tab and then come back to the Tab with the ImageIcon. The ImageIcon has become invisible (but it is still there because the Clicked event gets executed if I click on the now blank spot).

### Steps to Reproduce

1. Create a Maui App in Visual Studio 2022
2. Add a TabBar to AppShell.xaml
3. In the TabBar, the first Tab routes to MainPage (as is not modified)
4. Create a new ContentPage called HomePage
5. In HomePage add a ImageButton with FontImageSource
6. 
```xaml
<ImageButton Grid.Row="0" 
                                 Grid.Column="0"
                                Clicked="OnLikeButtonClicked"
                                Margin="5" 
                                HorizontalOptions="Center"
                                VerticalOptions="Center" >
                            <ImageButton.Source>
                        <FontImageSource x:Name="myLikeImage" FontFamily="OpenSansRegular" Glyph="A" Color="Black"/>
                            </ImageButton.Source>
                        </ImageButton>
```
7. Code behind of OnLikeButtonClicked
8.
```cs
private void OnLikeButtonClicked(object sender, EventArgs e)
    {
        myLikeImage.Color = Colors.Blue;
    }
```
7. In the TabBar of AppShell set the second Tab route to HomePage
9. I compile and run the application on Android Emulator (Android 13 - API 33)
10. When I click on the second Tab I do see the ImageButton with the letter "A". If I click on it the color changes to Blue (works as designed"
11. I then click on Tab 1 and the then back to Tab 2.
12. The ImageButton with the blue letter A has disappeared

### Link to public reproduction project repository

https://github.com/pentagramme/ReproduceFontImageSourceBug

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 13

### Did you find any workaround?

No

**Comment by pentagramme** [comment] 2023-04-14 16:36
I tested the issue on Windows. On Windows, it works correctly. So Windows is not affected by this bug.

**Comment by pentagramme** [comment] 2023-04-14 20:50
I tested the issue on IOS 16 (simulator). On IOS, it works correctly. So IOS is not affected by this bug.

**Comment by melixor** [comment] 2023-06-22 15:39
I'm having the same problem on android.

**Comment by Shaunz0r** [comment] 2023-08-22 10:21
Sounds like I'm having the same issue, also on Android, have a collectionView of ImageButtons, each imageButton switches image source on click. When I navigate to another tab and back, the imageButtons have vanished, but will reappear if I click around on the blank page

**Comment by techartdev** [comment] 2023-09-13 15:24
Similar thing happens on my side. I have a image (profile image of user) loaded from internet. When I navigate between tabs the image disappears. It's visible only on the first visit of the tab, but once I click on another tab and go back it's gone. I'm not changing the source or anything. I also added RefreshView there but even after refresh it's still blank.

![image](https://github.com/dotnet/maui/assets/10697327/a08358ea-5a3f-4c6c-8834-daa457172c24)


Similar thing is noticed when I use images as button. For example a favorite button. When I click the favorite button works like a charm. When I change tab the clicked image disappears. When I reload the RefreshView it appears back. 

`<Image>
                <Image.Source>
                    <FontImageSource
                        FontFamily="Material"
                        Glyph="{Binding Recipe.IsFavorite, Converter={StaticResource FavoriteConverter}}"
                        Size="24"
                        Color="{AppThemeBinding Light={StaticResource PrimaryColorLight},
                                                Dark={StaticResource PrimaryColorDark}}" />
                </Image.Source>

                <Image.GestureRecognizers>
                    <TapGestureRecognizer
                        Command="{Binding FavoriteCommand}"
                        CommandParameter="{Binding .}"
                        NumberOfTapsRequired="1" />
                </Image.GestureRecognizers>
            </Image>`

**Comment by MarianoVilla** [comment] 2023-09-29 19:49
Hey! I'm getting similar/the same behavior, on Android. I have a Grid, with a bunch of ImageButton elements. Everytime I go out and back in, some of the images aren't there. I have to click them, and then they appear.

![image](https://github.com/dotnet/maui/assets/44660612/f2ff25e7-6548-424a-b787-19263aebf433)

**Comment by homeyf** [comment] 2024-01-04 08:39
The user-provided sample project could no longer be found. We reproduced this issue by https://github.com/dotnet/maui-samples project on android platform with Visual Studio Enterprise 17.9.0 Preview 2.Sometimes it happens that some images just don't exist and I have to click on them and they appear.

**Comment by mavispuford** [comment] 2024-03-13 19:33
I'm experiencing the same thing.  My icon font images disappear when switching tabs.  They are `ImageButtons` contained in a `CollectionView` which change color based on the Selected/Normal states using `VisualStateGroups`.  In my case, only the ones that have been interacted with (Selected/Unselected) disappear. Here's my dotnet workload:

```
Installed Workload Id      Manifest Version       Installation Source
-------------------------------------------------------------------------------------
maui                       8.0.7/8.0.100          SDK 8.0.200
maui-windows               8.0.7/8.0.100          VS 17.9.34701.34, VS 17.9.34310.174
maccatalyst                17.2.8043/8.0.100      VS 17.9.34701.34, VS 17.9.34310.174
ios                        17.2.8043/8.0.100      VS 17.9.34701.34, VS 17.9.34310.174
android                    34.0.85/8.0.100        VS 17.9.34701.34, VS 17.9.34310.174
```

**Comment by mavispuford** [comment] 2024-03-14 17:25
[I've created a new repo to reproduce this in Android](https://github.com/mavispuford/DisappearingFontIcons)

Here's a video:

https://github.com/dotnet/maui/assets/2214272/f6ca54f7-f69d-4c3f-a1da-6535b529febe

**Comment by mikebikerider** [comment] 2024-03-16 03:49
I encountered the same issue on Android. FontImageSource graphic once changed at runtime will disappear after navigating to another page and back, or after changing the image several times while staying on the same page. It does not matter whether the Glyph Unicode string changed directly in FontImageSource.Glyph property or through ViewModel. There is another rendering issue that might be related. The ImageButton FontImageSource graphic rendered as disabled while the button is enabled. Randomly happens when graphic is changed. Easy to replicate, difficult not to notice. 
VS2022 17.9.3 Maui.Controls 8.0.10
iOS is not affected.

**Comment by cmhofmeister** [comment] 2024-03-21 15:46
I am encountering this issue with VS2022 17.10.0 Preview 2 with Maui Control 8.0.10.
I found a workaround that I'm not crazy about, but I'm trying to make a production-quality release for the company I work for and can't have images disappearing. 

I bound the image color
```
<Image.Source>
    <FontImageSource FontFamily="GoogleFontIcons" Glyph="{Binding ImageSiteStatusId}" Color="{Binding ColorSiteStatusImage}"/>
</Image.Source>
```

Then in my View Model I save the color, change it, and set it back.
```
#if ANDROID
            Color oldColor = ColorSiteStatusImage;
            ColorSiteStatusImage = Colors.Transparent;
            ColorSiteStatusImage = oldColor;
#endif

```

**Comment by mikebikerider** [comment] 2024-03-21 16:34
That workaround would be awkward to implement along with FontImageSource.Color AppThemeBinding .
Similar trick is setting GLyph propery to an empty string or null and restoring it back in the next line. It works better from the View Model. I found that enabling/disabling a button with FontImageSource from code behind can have complications like disabled image is rendered while the button is enabled. It does not happen when the button is enabled/disabled from the View Model.

**Comment by rezamohamed** [comment] 2024-11-11 22:56
I am on v8.0.93 of Maui and this is still an issue on Android only. Per the last update on this Issue, https://github.com/dotnet/maui/issues/23780 it is said to be fixed in 8.0.90 but it doesn't seem to be the case.

**Comment by mattleibow** [comment] 2024-11-12 22:24
Probably related: 
* https://github.com/dotnet/maui/issues/22427
* https://github.com/dotnet/maui/issues/25783

**Comment by albyrock87** [comment] 2024-11-12 22:35
I wonder if there's a problem with the caching we enabled with https://github.com/dotnet/maui/pull/24021
Maybe a race condition within glide or the way we're using it.

Or it may be something similar to https://github.com/dotnet/maui/pull/24023

**Comment by albyrock87** [comment] 2024-11-13 10:28
> [I've created a new repo to reproduce this in Android](https://github.com/mavispuford/DisappearingFontIcons)
> 
> Here's a video:
> screen-20240314-112125.2.mp4

I tried to reproduce with an UI test but I couldn't reproduce.
https://gist.github.com/albyrock87/f60d07e06dc61dfbdf54eff6f6b1a080

**Closed** 2024-12-26 16:39 UTC
Labels: t/bug, platform/android 🤖, area-image, s/verified, s/triaged
