### ISSUE TITLE
Bindings in a CollectionView are evaluated far too often

### ISSUE THREAD

**Issue by bill-reiss** [dotnet/maui#20797] opened 2024-02-23 01:56 UTC
### Description

On CollectionView on all platforms, if I set an ItemsSource via Binding and never change it, the Bindings in the ItemTemplate are evaluated 3 times per item. It should only be once. This is significant extra overhead that is unnecessary.

Even worse, the first time the Binding is evaluated, the BindingContext is null. This should never happen for a CollectionView item bound to an ItemsSource unless there was a null item in the ItemsSource list. This forces developers to check for null in their ValueConverters when it shouldn't be possible.

This happens on all platforms. On iOS for some reason there is even an extra 3 times that the Binding is evaluated on the CollectionView. I was able to count the number of times the Binding is evaluated by inserting a ValueConverter that keeps count.

Expected result: there should only be one Binding evaluation per item, not 3.

### Steps to Reproduce

1. Create a new .NET MAUI app.
2. In MainPage, add a CollectionView that has an ItemTemplate containing a label, and bind its ItemSource to a list of strings. Bind the Label's Text to the item.
3. Create a ValueConverter that just returns the value passed in, and add this Converter to the Label Text binding.
4. Count how many times the ValueConverter executes. Each time this executes, that's a time that the binding is being evaluated.
5. Note that the first time for each item when it executes the value passed in is null. Also note that the binding is evaluated 3 times for each item.

### Link to public reproduction project repository

https://github.com/billreiss/CollectionViewNullBindingContext

### Version with bug

8.0.7 SR2

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows

### Affected platform versions

iOS 17.2, Android 34, Windows net8.0-windows10.0.19041.0

### Did you find any workaround?

No workaround found

**Comment by Vroomer** [comment] 2024-02-23 18:42
The team already knows about this: https://github.com/dotnet/maui/issues/17349 Sadly nobody seems to care, which is surprising given how costly Bindings are for CollectionView. I would expect this to be high priority issue.

**Comment by jfversluis** [comment] 2024-03-22 09:51
Duplicate of #17349

**Closed by jfversluis** 2024-03-22 09:51 UTC
Labels: t/bug, platform/windows 🪟, platform/android 🤖, platform/iOS 🍎, area/perf 🏎️, area/collectionview 📃, s/triaged
