### ISSUE TITLE
Connecting or Disconnecting Physical Barcode Reader is triggering App Return to Initial Index Page in Blazor Hybrid

### ISSUE THREAD

**Issue by lasithalankajeewa** [dotnet/maui#20263] opened 2024-01-31 10:00 UTC
### Description

When using a physical barcode reader on the Android version of the .NET MAUI Blazor app, the application unexpectedly returns to the initial index page when attempting to connect or disconnect the barcode reader to the android device. This behavior occurs consistently, disrupting the expected flow of the application and causing inconvenience to the user experience. I already created an issue #18618 in regarding this previously. But didn't get a proper solution. Do you have any solution for this?

### Steps to Reproduce

When Connecting the Barcode Reader

1. Open the .NET MAUI Blazor app on an Android device.
2. Navigate from the initial index page to another page within the app.
3. Connect a physical barcode reader via Bluetooth or wired connection.
4. Observe that the app returns to the initial index page instead of staying on the intended page.

When Disconnecting the Barcode Reader

1. Open the .NET MAUI Blazor app on an Android device.
2. Navigate from the initial index page to another page within the app.
3. Disconnect the physical barcode reader.
4. Observe that the app returns to the initial index page instead of staying on the intended page.

### Version with bug

7.0.86

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 13

**Comment by drasticactions** [comment] 2024-01-31 10:56
Duplicate of https://github.com/dotnet/maui/issues/18618

**Closed by drasticactions** 2024-01-31 10:56 UTC
Labels: t/bug
