### ISSUE TITLE
CollectionView pushed off the screen iOS & Android

### ISSUE THREAD

**Issue by SamuelJames101** [dotnet/maui#16783] opened 2023-08-16 12:36 UTC
### Description

When the keyboard is opened due to an editor being clicked the CollectionView above it is pushed off the screen.
I believe a scrollbar should become present.

### Steps to Reproduce

1) Have an editor/ entry towards the bottom of the page
2) Have a CollectionView with some data in it.

3)Click on the editor

Expected results:
The keyboard is shown and the editor is placed above the keyboard.
The CollectionView items can be seen on the page and if required a scroll bar is added.

Actual results:
The keyboard is shown and the editor is placed above the keyboard.
CollectionView is partially pushed off of the page and I can't scroll up.

### Link to public reproduction project repository

https://github.com/SamuelJames101/KeyboardCollectionViewIssues

### Version with bug

8.0.0-preview.7.8842

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, I was *not* able test on other platforms

**Comment by tj-devel709** [comment] 2023-08-16 16:43
Hi @SamuelJames101 thank you for the feedback on this as well! Similar thing here, would you be able to upload the code to your repo (and maybe an image or video) so that I can try to see exactly what you are seeing?

**Comment by samhouts** [comment] 2023-08-17 21:49
Probably related to/same as #15838

**Comment by samhouts** [comment] 2023-08-17 21:50
whoops, didn't mean to add that label

**Comment by XamlTest** [comment] 2023-08-24 06:47
Verified this on Visual Studio Enterprise 17.8.0 Preview 1.0. Repro on Android 13.0-API33 and iOS 16.4 .NET 8 with below Project:
[GridContainerIssueWithCollectionView.zip](https://github.com/dotnet/maui/files/12426259/GridContainerIssueWithCollectionView.zip)

![Scroll-Android](https://github.com/dotnet/maui/assets/97647558/7e8a001f-5ed0-4463-a129-131a90867d7c)

**Comment by PureWeen** [comment] 2023-09-03 22:47
@SamuelJames101 is this the behavior you're wanting?

https://github.com/dotnet/maui/issues/11979

**Comment by SamuelJames101** [comment] 2023-09-04 11:08
> #11979

I believe it is yes, thank you

**Comment by samhouts** [comment] 2023-09-12 18:07
Duplicate of #11979

**Closed by samhouts** 2023-09-12 18:07 UTC
Labels: t/bug, area/collectionview 📃, s/verified, s/triaged, s/needs-attention, area/keyboard
