### ISSUE TITLE
[iOS] ZIndex + ScrollView issue

### ISSUE THREAD

**Issue by ptittof57** [dotnet/maui#19423] opened 2023-12-14 14:58 UTC
### Description

If ZIndex of ScrollView is in lower layer then I can't scroll or select item anymore. Only in IOS, works fine with Android.

Check testing project to reproduce.

```
﻿<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="Maui_ZIndexScrollView.MainPage">

    <Grid>
        <!-- #region ZIndex 0  -->
        <Grid ZIndex="0">
            <Grid.RowDefinitions>
                <RowDefinition Height="*" />
            </Grid.RowDefinitions>
            <ScrollView  x:Name="scrollView"
                         VerticalOptions="StartAndExpand"
                         HorizontalOptions="CenterAndExpand"
                         VerticalScrollBarVisibility="Never">
                <StackLayout BindableLayout.ItemsSource="{Binding Items}">
                    <BindableLayout.ItemTemplate>
                        <DataTemplate>
                            <Grid>
                                <Label Text="{Binding Text}" />
                            </Grid>
                        </DataTemplate>
                    </BindableLayout.ItemTemplate>
                </StackLayout>
            </ScrollView>
        </Grid>

        <!--#endregion-->

        <!--#region ZIndex 1  -->
        <AbsoluteLayout ZIndex="1">
            <Grid AbsoluteLayout.LayoutBounds="0.5,1,200,80"
                  AbsoluteLayout.LayoutFlags="PositionProportional">
                <Border Stroke="{StaticResource Primary}">
                    <Grid BackgroundColor="{StaticResource Primary}">
                        <Label Text="ZIndex 1 - List can't scroll" TextColor="White" HorizontalOptions="Center" VerticalOptions="Center" />
                    </Grid>
                </Border>
            </Grid>
        </AbsoluteLayout>
    </Grid>

</ContentPage>
```

### Steps to Reproduce

1 - Open the reproduction project
2 - Select iOS physical device
3 - Let ZIndex = 0 for ScrollView to reproduce
4 - Change ZIndex of ScrollView for 10 to reactivate scroll and select

### Link to public reproduction project repository

https://github.com/ptittof57/Maui-ZIndexScrollView

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 17

### Did you find any workaround?

No

**Comment by mattleibow** [comment] 2023-12-14 19:26
Can you try adding InputTransparent="true" to the AbsoluteLayout? I think the issue is that Android should _not_ allow taps to pass through and is actually a bug: https://github.com/dotnet/maui/issues/10252

**Comment by ptittof57** [comment] 2023-12-14 20:00
Hi @mattleibow, yes with InputTransparent="true" it works ! Thanks

**Comment by PureWeen** [comment] 2023-12-16 01:28
Duplicate of #10252

**Closed by PureWeen** 2023-12-16 01:28 UTC
Labels: t/bug, area/layout 🔲, s/needs-attention
