### ISSUE TITLE
[Bug] Alerts currently don't work if you call them from the constructor

### ISSUE THREAD

**Issue by PureWeen** [dotnet/maui#1514] opened 2021-07-01 14:15 UTC
### Description

If you call DisplayAlert from the constructor of a page it currently does not work on WinUI

Go to the alerts page and add a call to DisplayAlert from the ctor

```C#
public AlertsPage()
{
      DisplayFromCtor();
}

async void DisplayFromCtor() =>  await DisplayAlert();
```

**Comment by hartez** [comment] 2021-11-05 22:14
In Forms calling alerts from the constructor would put them in a queue that would be processed after Appearing; maybe the queue stuff didn't get ported?

**Comment by jamesmontemagno** [comment] 2022-02-11 22:27
IMHO this should not be a supported scenario that could be documented. The UI isn't visible yet, you basically shouldn't do anything in your constructor.

**Comment by Eilon** [comment] 2022-02-11 22:43
I'm guessing people do it because it's the logical equivalent of `printf` debugging. No strong opinion on whether it should be allowed.

**Comment by PureWeen** [comment] 2022-02-11 23:49
Another use case here is that the ctor is easiest place for an alert you only want to show on the first load of a page. In theory you could check for this case in "Appearing" but it's a bit more code and since the ctor works then why not just put it there.

**Comment by shimingsg** [comment] 2022-02-17 09:48
Not reproducible with Android 11.

**Comment by Eilon** [comment] 2022-02-18 06:01
Re-opening because I'm not sure if this is the right behavior on _all_ platforms, even if perhaps it works on Android.

**Comment by jsuarezruiz** [comment] 2022-05-12 09:29
Testing with RC3 and main branch, this is now working:
![image](https://user-images.githubusercontent.com/6755973/168038957-fe1c15d7-98a8-43fd-a1e7-942f60cb6c42.png)

Reviewing the history have been fixed by the commit fffaae1eaa33db6eeced93f0a85fc00cd155be19.

**Closed by jsuarezruiz** 2022-05-12 09:29 UTC
Labels: t/bug, area/controls 🎮, s/verified, control-dialogalert
