### ISSUE TITLE
Program does not start .NET MAUI Tutorial 

### ISSUE THREAD

**Issue by ukengland** [dotnet/maui#13286] opened 2023-02-12 17:57 UTC
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
The program '[16400] MyFirstMauiApp1.exe' has exited with code 2147942405 (0x80070005).

**Comment by holecekp** [comment] 2023-02-12 20:14
Probably duplicate of https://github.com/dotnet/maui/issues/12080. You can try one of the workarounds from that issue.

**Closed** 2023-02-24 19:02 UTC
Labels: platform/windows 🪟, s/needs-info, area/setup 🪄, s/no-recent-activity
