### ISSUE TITLE
[Bug] Using Maui Essentials in a non-MAUI app throws an error on launch

### ISSUE THREAD

**Issue by egvijayanand** [dotnet/maui#1779] opened 2021-07-23 05:13 UTC
### Description
Using Maui Essentials in a non-MAUI app throws an error on launch though the build succeeded

### Steps to Reproduce

1. Create a new WPF project (non-MAUI) and set the target framework as net6.0-windows10.0.18362 (Windows 10 1903)
2. Configure Maui Essentials with `<UseMauiEssentials>true</UseMauiEssentials>` in the project file
3. Use the Essentials Connectivity feature in the main window
4. Build and run the project, displays an error dialog on launch as in below screenshot
<img width="298" alt="Maui-Essentials" src="https://user-images.githubusercontent.com/81947404/126739265-9dc2f053-9d57-4a7d-827f-bd9cd1f9ee36.png">

Note: NuGet package source is configured with Maui Preview repo (https://aka.ms/maui-preview/index.json)

### Expected Behavior
The application is expected to run without any issues.

### Actual Behavior
Displays a dialog to download the .NET since Microsoft.Maui.Essentials could not be found.
The .NET 6 Preview 6 SDK itself is installed on the machine.

### Basic Information

- Version with issue: **.NET 6 Preview 6**
- Last known good version: **.NET 6 Preview 5 (with Microsoft.Maui.Essentials NuGet package reference ver. 6.0.100-preview.5.*)**
- IDE: **VS2022 17.0.0 Preview 2.1**
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:  
  - WPF: **Target Framework net6.0-windows10.0.18362**
- Android Support Library Version: 
- Nuget Packages: 
- Affected Devices:

**Comment by Daniellled** [comment] 2021-07-26 17:04
I am also seeing the same type of error when running unit test.

> Microsoft.VisualStudio.TestPlatform.ObjectModel.TestPlatformException: Testhost process exited with error: It was not possible to find any compatible framework version
> The framework 'Microsoft.Maui.Extensions', version '6.0.100-preview.6.1003+sha.5c159aabf-azdo.4977641' was not found.
>   - No frameworks were found.
> You can resolve the problem by installing the specified framework and/or SDK.
> The specified framework can be found at:
>   - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.Maui.Extensions&framework_version=6.0.100-preview.6.1003+sha.5c159aabf-azdo.4977641&arch=x64&rid=win10-x64
> . Please check the diagnostic logs for more information.
>    at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.ThrowOnTestHostExited(Boolean testHostExited)
>    at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources, String runSettings)
>    at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyDiscoveryManager.DiscoverTests(DiscoveryCriteria discoveryCriteria, ITestDiscoveryEventsHandler2 eventHandler)

Except it is related to the Microsoft.Maui.Extensions dll. 

Like you it worked on Preview 5 and now with the new WorkLoad stuff it no longer works. I am able to run MAUI applications fine.

**Comment by egvijayanand** [comment] 2021-07-27 04:21
Yes, the issue is only with a non-MAUI app in .NET 6 Preview 6. MAUI app works fine.

**Comment by egvijayanand** [comment] 2021-08-17 06:02
Issue still persists in .NET 6 Preview 7.
<img width="269" alt="Maui-Essentials-1" src="https://user-images.githubusercontent.com/81947404/129671880-b0f23e6a-0f6e-4d49-9c95-99096e503777.png">

**Comment by jsuarezruiz** [comment] 2021-11-12 09:06
There is not an WPF target in Essentials: https://github.com/dotnet/maui/blob/main/src/Essentials/src/Essentials-net6.csproj#L3

We are going to review this scenario.

**Comment by egvijayanand** [comment] 2021-11-12 10:05
> There is not an WPF target in Essentials: https://github.com/dotnet/maui/blob/main/src/Essentials/src/Essentials-net6.csproj#L3
> 
> We are going to review this scenario.

Same is the case with a WinForms application too. Kindly include that scenario as well.

**Comment by Eilon** [comment] 2022-02-11 19:54
@jsuarezruiz / @Redth / @davidortinau - is MAUI Essentials support for WPF something we can postpone to a later release?

**Comment by shimingsg** [comment] 2022-03-03 05:33
verified repro with VS 17.2.0 Preview 2.0 [32302.528.main]

**Comment by mattleibow** [comment] 2022-03-22 20:38
This is a duplicate of #4779

**Closed by mattleibow** 2022-03-22 20:38 UTC
Labels: t/bug, area/essentials 🍞, s/verified

**Comment by egvijayanand** [comment] 2022-03-24 08:40
Hi @mattleibow,

I'm not sure whether you've gone through the issue details or conservation pertaining to that.

> @jsuarezruiz / @Redth / @davidortinau - is MAUI Essentials support for WPF something we can postpone to a later release?

But it's definitely not a duplicate of #4779, that is about referencing the Maui Essentials in a Razor Class Library (RCL) whereas this is about an issue that occurs during the launch of the application that uses Maui Essentials in other Windows Client applications like WinForms / WPF.

The issue is still simulating with the attached project, hence kindly reopen this issue.

[MyApp.zip](https://github.com/dotnet/maui/files/8339763/MyApp.zip)

Regards,
 Vijay Anand E G

**Comment by egvijayanand** [comment] 2022-03-24 08:41
![image](https://user-images.githubusercontent.com/81947404/159876468-fe14a31b-7902-44c2-ae76-321ee44a37cb.png)

This is the error that is still showing on launching the application.

**Comment by Redth** [comment] 2022-03-24 12:26
Essentials is not currently supported and there are no plans at this time to add support in WPF
