### ISSUE TITLE
Release throws exception with local styles since last VS update

### ISSUE THREAD

**Issue by eli191** [dotnet/maui#12316] opened 2022-12-28 11:47 UTC
### Description

Hi,

Styles set like this
```
 <ContentPage.Resources>
         <ResourceDictionary>
             <Style x:Key="InvalidEntryStyle" TargetType="Editor">
                <Setter Property="TextColor" Value="Red" />
             </Style>
             <Style x:Key="ValidEntryStyle" TargetType="Editor">
                <Setter Property="TextColor" Value="Black" />
             </Style>
         </ResourceDictionary>
    </ContentPage.Resources>
```

or like this
```
<BoxView.Triggers>
                        <DataTrigger TargetType="BoxView"
                                     Binding="{Binding Source={x:Reference _codeLabel},Path=Text.Length}"
                                     Value="0"  >
                            <Setter Property="IsVisible" Value="False" />
                            </DataTrigger>
                    </BoxView.Triggers>
```
compile in Release mode but crashes the app, with exception in device console :
```
Cannot assign property "Property": Property does not exist or is not assignable, or mismatching type between value and property.
```
In `InitializeComponent()`

Debug still fine.

Release was working before update.

Build uses Don't link option.

Please Help as this is blocking!

### Steps to Reproduce

1. Create a new .Net MAUI app
2. Add some local styles

### Link to public reproduction project repository

[https://github.com/fgiacomelli/iosBug](https://github.com/fgiacomelli/iosBug)

### Version with bug

7.0 (current)

### Last version that worked well

6.0 Release Candidate 2 or older

### Affected platforms

iOS, I was *not* able test on other platforms

### Affected platform versions

iOS 16.2

### Did you find any workaround?

No

### Relevant log output

```shell
Cannot assign property "Property": Property does not exist or is not assignable, or mismatching type between value and property.
```

**Comment by eli191** [comment] 2022-12-29 15:30
Found workarounds:

- Move local styles to global styles

- For triggers, do a `Binding` with a `Converter`.

I have so many problems each time I want to release my application with .Net MAUI and spend a lot of time searching why.
Who can imagine styles and triggers stopped working in release?
I work as a professional, I am not a hobbyist so please, ensure things do work properly.

**Comment by AbstractionsAs** [comment] 2023-01-09 15:10
I started getting this problem as well with the latest version. Only affects iOS in release

**Comment by AbstractionsAs** [comment] 2023-01-09 15:11
I should point out that this has worked well in .net7 as well as .net6, but not after the latest update (first service release?)

**Comment by fgiacomelli** [comment] 2023-01-12 11:07
I have the same problem as described from @eli191 , and I perfectly agree with her point of view about MAUI because I'm also a professional developer.

In my case I have triggers that didn't work only in release mode and only on iOS: the difference is that in my situation I can build without problem and I can only see the app crash runtime (and without other info because I'm in release).

@eli191 how do you solve using a converter with the trigger?

Does anybody found a solution to make it work in release? I suspect it could be related to some compiler option, I tried to build in release with "Don't link" option enabled but it doesn't solve.

**Comment by fgiacomelli** [comment] 2023-01-12 14:48
I totally agree with @eli191 in any point of view: for a person that writes code as professional it's not reasonable spending so much time to look for workarounds for platform bugs, and to work with a so unaffordable situation.

I have the same problem using datatriggers only in iOS only in release mode and only with physical device.

I created a repo that crashes if launched on physical ios in release mode here: https://github.com/fgiacomelli/iosBug

I found that on this simple repo the problem is solved replacing the StaticResource property inside the dataTrigger with its value.

p.s. @eli191 how do you solved with converters?

**Comment by fgiacomelli** [comment] 2023-01-12 15:42
it's weird, but I found that if I remove the StaticResource both from app.xaml and from the trigger, it works. If I only remove from the trigger leaving the declaration in app.xaml the app still crashes.

**Comment by fgiacomelli** [comment] 2023-01-13 08:22
In the meantime I created a sample that crashes only in release mode on physical device on iOS, here: https://github.com/fgiacomelli/iosBug

**Comment by eli191** [comment] 2023-01-16 13:44
Hi @fgiacomelli 

Yes, it is the same problem for me. Release is building without errors, but when executing the app on the device, the app crashes, and built with the previous VS version, it was working.

For exemple, a trigger like this
```
<DataTrigger TargetType="Label" Binding="{Binding ImagesCount}" Value="0">
<Setter Property="IsVisible" Value="False"/>
</DataTrigger>
```
can be changed to a `Binding` with a `Converter` like this
```
IsVisible="{Binding ImagesCount, Converter={toolkit:IntToBoolConverter}}"
```

**Comment by AbstractionsAs** [comment] 2023-01-16 13:47
It'sbeen three weeks, for a major bug that effectively renders the entire framework unusable, and there still hasn't been a single response from the team...

**Comment by AbstractionsAs** [comment] 2023-01-16 13:49
@eli191 Perhaps if you update the bufæg description with the repro link from @fgiacomelli someone will take notice?

**Comment by eli191** [comment] 2023-01-16 13:54
> @eli191 Perhaps if you update the bufæg description with the repro link from @fgiacomelli someone will take notice?

Done

**Comment by fgiacomelli** [comment] 2023-01-17 15:10
> Hi @fgiacomelli
> 
> Yes, it is the same problem for me. Release is building without errors, but when executing the app on the device, the app crashes, and built with the previous VS version, it was working.
> 
> For exemple, a trigger like this
> 
> ```
> <DataTrigger TargetType="Label" Binding="{Binding ImagesCount}" Value="0">
> <Setter Property="IsVisible" Value="False"/>
> </DataTrigger>
> ```
> 
> can be changed to a `Binding` with a `Converter` like this
> 
> ```
> IsVisible="{Binding ImagesCount, Converter={toolkit:IntToBoolConverter}}"
> ```
> 
> Thank you for the sample!

Welcome, hoping the fix will be quick. Thank you for the suggestion, in my situation I drive more than one property on each trigger, so it would be a lot of work translate all of them with converters. So I want to be trustful on MAUI, trying to use the previous sdk only for build the release version for iOS and hoping that we can found this and a lot of critical bugs fixed in next releases

**Comment by PureWeen** [comment] 2023-02-16 19:31
Duplicate of #12316

**Closed by PureWeen** 2023-02-16 19:31 UTC
Labels: t/bug, area/Xaml </>, s/needs-attention

**Comment by eli191** [comment] 2023-02-22 09:11
@PureWeen 
I am sorry, **this IS NOT the same issue**, as it happens with the linker behaviour set to None.

**Comment by fgiacomelli** [comment] 2023-03-16 14:27
news about this? I currently can't get the release version usable on ios physical device, this is a big issue

**Comment by fgiacomelli** [comment] 2023-03-16 16:56
in the meantime I found a workaround, as suggested [here](https://github.com/dotnet/maui/issues/12519#issuecomment-1409099527) by @rolfbjarne , setting the interpreter in the csproj:

```
<PropertyGroup>
<UseInterpreter Condition="$(TargetFramework.EndsWith('-ios'))">true</UseInterpreter>
</PropertyGroup>
```

solve the problem for me
