### ISSUE TITLE
Add position to DragGestureRecognizer and DropGestureRecognizer events

### ISSUE THREAD

**Issue by Eltypo** [dotnet/maui#11256] opened 2022-11-10 11:50 UTC
### Description

I would love to have possibility to obtain position of drag\drop events.

### Public API Changes

```
private void DropGestureRecognizer_Drop(object sender, DropEventArgs e)
{
    var position = e.GetPosition(this);
}
```
```
private void DropGestureRecognizer_DragOver(object sender, DragEventArgs e)
{
    var position = e.GetPosition(this);
}
```

### Intended Use-Case

My target is to drag control and drop to AbsoluteLayout with position binding.

Until DropGestureRecognizer contains drop position, only workaround is to use PointerGestureRecognizer to obtain drop point.

But PointerGestureRecognizer stops firing PointerMoved event once drag was started.

**Comment by PureWeen** [comment] 2022-11-10 17:10
Duplicate of #2793

**Closed by PureWeen** 2022-11-10 17:10 UTC
Labels: proposal/open
