### ISSUE TITLE
Button on a CollectionView's EmptyView is not clickable on Windows

### ISSUE THREAD

**Issue by KeithBoynton** [dotnet/maui#21935] opened 2024-04-18 20:20 UTC
### Description

If you put a Button on an EmptyView within a CollectionView it is not Clickable on Windows. It works fine in iOS and MacCatalyst. I haven't tested it on Android but I imagine it probably works there too.

### Steps to Reproduce

1. Clone the attached demo repository and run it on Windows.
2. Try to click the button that is inside the EmptyView (it will not work)
3. Try to click the button below the view (it will work)
4. Run it on iOS, MacCatalyst
5. Try to click the button that is inside the EmptyView (it WILL work)

### Link to public reproduction project repository

https://bitbucket.org/KeithBoynton/non-clickable-button/src/master/

### Version with bug

8.0.20 SR4

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

net8.0-windows10.0.19041.0

### Did you find any workaround?

No

**Comment by jaosnz-rep** [comment] 2024-04-19 08:11
Verified this issue with Visual Studio17.10.0 Preview4(8.0.20 & 8.0.14), can repro on Windows platform.

**Comment by josephlugo** [comment] 2024-06-30 19:45
Also, try adding:

```
<Label.FormattedText>
                <FormattedString>
                    <Span Text="Nothing to show here... " />
                    <Span Text="yet" TextColor="Blue">
                        <Span.GestureRecognizers>
                            <TapGestureRecognizer
                                Tapped="OnYetLabelTapped" />
                        </Span.GestureRecognizers>
                    </Span>
                </FormattedString>
            </Label.FormattedText>
```

The Tapped event won’t happen either…

**Comment by rmarinho** [comment] 2024-09-07 00:02
Yap just hitted this.

**Comment by rodolfo-sousa** [comment] 2024-09-28 00:07
Happening with me too.. even tried to use GestureRecognizers and Behaviors on ContentView of the EmptyView but no luck...

**Comment by rmarinho** [comment] 2024-11-20 23:50
Duplicate of #19609

**Closed by rmarinho** 2024-11-20 23:50 UTC
Labels: t/bug, platform/windows 🪟, area-controls-collectionview, s/verified, s/triaged
