### ISSUE TITLE
[regression/7.0] RefreshView issue

### ISSUE THREAD

**Issue by Javierflo95** [dotnet/maui#14585] opened 2023-04-14 13:51 UTC
### Description

![Screenshot_20230414-084732_LinkedIn](https://user-images.githubusercontent.com/11860518/232061299-465c314c-55ed-4c0a-bb96-78e12b45d415.jpg)

So, if I remove the refreshview the collectionview data appeqrw correctly, but if I put the RefreshView the data is not showing up 

![Screenshot_20230414-082531](https://user-images.githubusercontent.com/11860518/232061796-13786628-54ed-4b78-87d0-e66ba27054c8.jpg)

### Steps to Reproduce

Put your refreshview as father of collectionview

### Link to public reproduction project repository

https://github.com/Javierflo95/GenaratioonApp

### Version with bug

7.0 (current)

### Last version that worked well

6.0.424

### Affected platforms

iOS, Android

### Affected platform versions

Android 30 31 33

### Did you find any workaround?

Not yet

**Comment by janseris** [comment] 2023-04-16 16:33
repo link dead

**Comment by jsuarezruiz** [comment] 2023-04-17 14:11
Could be the same or related with #14479

**Comment by Javierflo95** [comment] 2023-05-11 03:40
Antes updates?..

**Comment by japarson** [comment] 2023-06-15 06:10
Hi @Javierflo95 ,

Can you provide a new link to a repro project? The existing one is dead.

Thank you,
James

**Comment by r-work** [comment] 2023-06-21 16:16
Same issue here on `8.0.100-preview.5`

**Comment by Javierflo95** [comment] 2023-06-27 00:02
The sample is in the image pls fix it asap.

**Comment by haavamoa** [comment] 2023-06-27 17:47
Can you provide the entire xaml? I just had this issue as well, but fixed it by making sure: 

1. the refreshview+collectionview is either the only content or the page 
or: 
2. the refreshview+collectionview is in a grid row that has height=* 


My problem was that it was inside a VerticalStacklayout.

**Comment by janseris** [comment] 2023-06-27 18:38
Converted using https://www.imagetotext.info/

```
﻿
<Border BackgroundColor="#e5be88" Stroke="Transparent" IsVisible="{Binding DataLoaded, Mode=OneWay}" Grid.Row="2" Grid.ColumnSpan="2" Margin="20,24,20,130">
<Border.StrokeShape>
<RoundRectangle CornerRadius="12" />
</Border.StrokeShape>
<RefreshView Command="{Binding GetAlProductsCommand}" IsRefreshing="{Binding IsRefreshing}">
<CollectionView BackgroundColor="Transparent" ItemsSource="{Binding listProduct}" SelectionMode="None"
VerticalScrollBarVisibility="Default">
<CollectionView.EmptyView>
<VerticalStackLayout Padding="80" VerticalOptions="Center" HorizontalOptions="Center" Spacing="10"> <Image HorizontalOptions="CenterAndExpand" VerticalOptions="CenterAndExpand" HeightRequest="80"
WidthRequest="80" Source="bag_icon"/>
<Label Text="{x:Static res: AppResources. No Products FoundText}" TextColor="White"/>
</VerticalStackLayout>
</CollectionView.EmptyView>
|
<CollectionView.ItemTemplate>
<DataTemplate x:DataType="model: ProductModel">
<Grid
Margin="12,24"
ColumnDefinitions="Auto,
RowSpacing="0">
<toolkit: AvatarView BorderWidth="4" CornerRadius="80" HeightRequest="80" ImageSource="{Binding Image}" WidthRequest="80" /> <Grid Grid.Column="1" ColumnDefinitions="*, Auto">
<StackLayout>
<Label Margin="10, -18,0,0" Style="{StaticResource ProductTitle}" Text="{Binding Name}" /> <Label Margin="20,-24,0,0" Padding="-10, 20,0,0" Style="{StaticResource Product Description}" Text="{Binding Tokens Needed, StringFormat='{0} tokens'}" />
<Label Margin="22,-10,0,0" Padding="-10, 8,0,0" Style="{StaticResource Product Description}" Text="{Binding Price, StringFormat='{0:c}'}" />
</StackLayout>
<Button Grid.Column="1" BackgroundColor="#e69434"
</Grid>
</Grid>
</DataTemplate>
Command="{Binding Source={RelativeSource AncestorType={x:Type viewModels: Rewards ViewModel}}, Path=ShowDetailProductCommand}" CommandParameter="{Binding .}" HeightRequest="40" HorizontalOptions="End" Text="Add" TextColor="{StaticResource White}" WidthRequest="80" />
</CollectionView.ItemTemplate>
</CollectionView>
</RefreshView>
</Border>
```

**Comment by jsuarezruiz** [comment] 2023-08-07 13:59
Some useful logs:

```
2023-08-07 15:58:18.112 Maui.Controls.Sample[19646:691028] The behavior of the UICollectionViewFlowLayout is not defined because:
2023-08-07 15:58:18.112 Maui.Controls.Sample[19646:691028] the item width must be less than the width of the UICollectionView minus the section insets left and right values, minus the content insets left and right values.
2023-08-07 15:58:18.112 Maui.Controls.Sample[19646:691028] Please check the values returned by the delegate.
2023-08-07 15:58:18.112 Maui.Controls.Sample[19646:691028] The relevant UICollectionViewFlowLayout instance is <Microsoft_Maui_Controls_Handlers_Items_ListViewLayout: 0x7f9dc5734f90>, and it is attached to <UICollectionView: 0x7f9dc5aac600; frame = (0 0; 463 633); clipsToBounds = YES; autoresize = W+H; gestureRecognizers = <NSArray: 0x600003c1f420>; backgroundColor = UIExtendedGrayColorSpace 0 0; layer = <CALayer: 0x600003971ee0>; contentOffset: {0, 0}; contentSize: {463, 26000}; adjustedContentInset: {0, 0, 0, 0}; layout: <Microsoft_Maui_Controls_Handlers_Items_ListViewLayout: 0x7f9dc5734f90>; dataSource: <Microsoft_Maui_Controls_Handlers_Items_ReorderableItemsViewController_1: 0x7f9dc572d2c0>>.
2023-08-07 15:58:18.112 Maui.Controls.Sample[19646:691028] Make a symbolic breakpoint at UICollectionViewFlowLayoutBreakForInvalidSizes to catch this in the debugger.

```

**Comment by samhouts** [comment] 2023-08-11 16:59
Duplicate of #16492

**Closed by samhouts** 2023-08-11 16:59 UTC
Labels: t/bug, platform/android 🤖, p/1, area/controls 🎮, control-refreshview, s/needs-attention, i/regression
