### ISSUE TITLE
Adding resx file for additional language gives an error while trying to build iOS project

### ISSUE THREAD

**Issue by trevortirrell** [dotnet/maui#6076] opened 2022-04-13 17:08 UTC
### Description

When I add a second language resource file (i.e. AppResources.es.resx) I can no longer build the iOS project. If I remove it from the project then it builds and deploys just fine.

### Steps to Reproduce

1. Create a File > New .NET MAUI App
2. Add a resx Resource file (i.e. AppResources.resx)
3. Add a second resx Resource file (i.e. AppResources.es.resx)
4. Try to build iOS project.

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15

### Did you find any workaround?

Remove all resx files other than the default from the project

### Relevant log output

```shell
This is the error:
ALINK : error AL1012: 'arm64' is not a valid setting for option 'platform'
```

**Comment by SailDev** [comment] 2022-04-13 18:29
This "self explaining" error message did cost me quite some time.
Add the following line to the .csproj file:

`
<GenerateSatelliteAssembliesForCore>true</GenerateSatelliteAssembliesForCore>	
`

**Comment by trevortirrell** [comment] 2022-04-13 19:26
> This "self explaining" error message did cost me quite some time. Add the following line to the .csproj file:
> 
> `<GenerateSatelliteAssembliesForCore>true</GenerateSatelliteAssembliesForCore> `

After adding that I get the following error:

`ILStrip failed`

**Comment by SailDev** [comment] 2022-04-13 19:52
Same behaviour for Debug and Release build?

**Comment by jfversluis** [comment] 2022-04-14 08:45
Where exactly are you adding the resx file? I haven't seen this behavior in my .NET MAUI Blazor app.

Could you maybe go through the reproduction steps to create a sample project and put that on GitHub for us to look at? That would be a great help! :)

**Comment by SailDev** [comment] 2022-04-14 10:01
Maybe i can step in and add some infos.

In the app, i am working on, i use a large domain model which currently consists of 50 projects and fast growing. 

Some of them do have their own embedded translations in addition to the translations in the client (Maui) app.

Example project structure:

```
Domain.Services (.NET 6.0 class library)
  ...
	TheService (App folder)
   		TheService.cs
   		TheServiceTranslations.en.resx
   		TheServiceTranslations.resx
  ...
  
```
Having had the same error message , after quite some research and time, i found and added 

`<GenerateSatelliteAssembliesForCore>true</GenerateSatelliteAssembliesForCore>
`

to the Maui App project file. It fixed this specific problem.

Is this scenario totally unusal?

I wish, there would be a more complex (or realistic?) app public available (i.e. via Testflight), for integration testing, before each new Maui release.

Maybe with topics like (from my own experience):
- App-Shell with deep hierarchies
- Local Sqlite via EF
- Pages with more complex vertical scrolling scenarios (i.e. CollectionView with rich ContentViews in Header or Footer.
- Scrollable (editor) pages with nested picker / lookup scenarios including passing data back.
- Inline data entry in scrollable pages while changing device orientation and/or device keyboard types (normal, emoji,...)
- ....

I, and i think other people also, would be more than happy, to test each version and give feedback.

**Comment by trevortirrell** [comment] 2022-04-14 16:41
I was able to get it to build by adding `<GenerateSatelliteAssembliesForCore>true</GenerateSatelliteAssembliesForCore>` to the csproj. And then I had to use the command line from @jfversluis YouTube video here: https://www.youtube.com/watch?v=kpZi5xAvpZA&t=1460s. I wasn't able to build from VS unless I remove any additional language resx files. 

Here's the repo:
https://github.com/trevortirrell/MauiApp2

**Comment by v-longmin** [comment] 2022-04-26 03:21
Verified not repro on iOS 15.4. Not repro project:
[MauiApp2-master.zip](https://github.com/dotnet/maui/files/8559497/MauiApp2-master.zip)

**Comment by GiselleTGomes** [comment] 2022-05-31 17:38
same error

**Comment by GiselleTGomes** [comment] 2022-05-31 17:45
my resource files was on resources\translations folder, when i remove this folder th issue disapear..

**Comment by GiselleTGomes** [comment] 2022-05-31 18:22
hey guys ! this error happen when you put your *.resx file diferent folder from Resources

**Comment by Rabosa616** [comment] 2022-06-03 06:23
I have my resx files inside of the resources
![image](https://user-images.githubusercontent.com/12774781/171798616-d3b6eb6b-fdc5-4783-9b67-f9809e084af1.png)
and I get the same error. Also I've tried to create a folder Strings inside the Resources and I have the same issue

**Comment by RobertoGFilho** [comment] 2022-07-22 23:11
if i remove *.resx files this issue will dissapear

**Comment by Rabosa616** [comment] 2022-08-16 21:03
Any news @Redth @jfversluis?

**Comment by Rabosa616** [comment] 2022-08-17 09:26
Professional applications now a days are multilanguage.
Any news beside moving to backlog of when will this be pick up?
@jfversluis @Redth

**Comment by jfversluis** [comment] 2022-08-17 12:08
Hey everyone! I just had a quick look at this and with the latest versions I don't seem to be able to reproduce the build error anymore. It all builds find for me (also using the reproduction linked in this issue), however, unfortunately, the localization doesn't seem to work on iOS. I think that is due to a (already fixed) bug in the runtime, I'm asking around about that now.

Can someone confirm that the build error is gone?

**Comment by jfversluis** [comment] 2022-08-17 15:49
As for the localization not working, see my write-up here: https://github.com/dotnet/maui/issues/7362#issuecomment-1218201040

**Comment by Rabosa616** [comment] 2022-08-17 16:15
Hi @jfversluis Thanks so much for the quick response!
I've created a repo to reproduce the error: https://github.com/Rabosa616/MauiMultilanguageApp

The AL1012 is gone using the latest version of MAUI and by adding this into the csproj file
```
<GenerateSatelliteAssembliesForCore>true</GenerateSatelliteAssembliesForCore>
```
Now as you mention there is a issue with the localization not working
### Android
![Android](https://user-images.githubusercontent.com/12774781/185185600-4fb88fa0-4937-4303-b462-9d66e84e8751.png)

### Windows
![Windows](https://user-images.githubusercontent.com/12774781/185185630-29ba40f2-91d5-492e-b81f-053f8b5750d0.png)

### iPhone (Not working)
![iPhone](https://user-images.githubusercontent.com/12774781/185185619-81871397-8a6d-4818-85da-2bd4ff904867.PNG)

you suggest to have the global.json to a lower version, this will make not compiling again, right?

**Comment by jfversluis** [comment] 2022-08-17 17:58
With the global.json on a lower version it both compiled and the localization worked for me :)

I did not need the `<GenerateSatelliteAssembliesForCore>true</GenerateSatelliteAssembliesForCore>` as well. Let me know how that goes for you!

**Comment by Rabosa616** [comment] 2022-08-18 11:24
Hi @jfversluis
I´ve installed the .net 6.0.303 sdks
![image](https://user-images.githubusercontent.com/12774781/185376735-1144e570-e424-41fb-84bf-58d27a048fe7.png)

![image](https://user-images.githubusercontent.com/12774781/185377100-ddb04773-2fe4-45e4-9929-816dffb293a4.png)


then I´ve followed your instructions:

1. Run dotnet --list-sdks
2. Find a version that starts with 3, the version needs to be at least 6.0.303 (which is the highest at the time of writing)
3. In your project root run dotnet new --globaljson --sdk-version=6.0.303
4. Run dotnet workload update NOTE: this will update your entire MAUI workload for all projects
5. Restart Visual Studio to be sure it uses 6.0.303 and aggressively rebuild your project

I still was not able to build the app without the 

```
<GenerateSatelliteAssembliesForCore>true</GenerateSatelliteAssembliesForCore>
```

Still the issue with the language:

![image](https://user-images.githubusercontent.com/12774781/185377658-dff91c57-aac8-4bf1-a76f-720c68aa5ef1.png)


I´m using the repo: https://github.com/Rabosa616/MauiMultilanguageApp

To clean up my local repo I use this ps:
```ps
Get-ChildItem .\ -include bin,obj -Recurse | foreach ($_) { remove-item $_.fullname -Force -Recurse }
````

**Comment by jfversluis** [comment] 2022-08-18 18:34
@Rabosa616 your `global.json` is set to 6.0.300 not 6.0.303

**Comment by VladislavAntonyuk** [comment] 2022-08-18 19:01
You can read how to localize .NET MAUI application here: https://vladislavantonyuk.azurewebsites.net/articles/Localize-.NET-MAUI-application

**Comment by Rabosa616** [comment] 2022-08-29 07:12
First of all thanks @jfversluis for your correction on my test repo.
If I do not set the <GenerateSatelliteAssembliesForCore>true</GenerateSatelliteAssembliesForCore> I get the error of AL1012 when I press F5 without rebuilding the project.

Inspecting the output at the C:\Users\vaos\AppData\Local\Temp\Xamarin\HotRestart\Signing\MauiApp1.app\out\Payload\MauiApp1.app\MauiApp1.content I do see MauiApp1.dll, opening it with the Jetbrains dotPeek I can only see the english resource but not the spanish one

![image](https://user-images.githubusercontent.com/12774781/187143206-7c321501-f331-47fd-95f6-d6c0827cc44c.png)

If I create a Xamarin app with multilingual support in the same temp folder I see the language folders:
![image](https://user-images.githubusercontent.com/12774781/187143806-53630265-0a65-4340-b069-cfd27f913f9f.png)
![image](https://user-images.githubusercontent.com/12774781/187144313-bb38b285-7a7f-4631-9155-d13f1fabc788.png)

May be there is something on my machine´s configuration?

**Comment by Rabosa616** [comment] 2022-08-29 08:11
> You can read how to localize .NET MAUI application here: https://vladislavantonyuk.azurewebsites.net/articles/Localize-.NET-MAUI-application

Thanks for your article, I´ve checked your source code in [github](https://github.com/VladislavAntonyuk/MauiSamples/tree/main/MauiLocalization) and I´ve notice that your are creating a Window application. Using Maui on Windows and Android Works fine but when you build the app for iOS it´s not working.

**Comment by VladislavAntonyuk** [comment] 2022-08-30 16:23
> > You can read how to localize .NET MAUI application here: https://vladislavantonyuk.azurewebsites.net/articles/Localize-.NET-MAUI-application
> 
> Thanks for your article, I´ve checked your source code in [github](https://github.com/VladislavAntonyuk/MauiSamples/tree/main/MauiLocalization) and I´ve notice that your are creating a Window application. Using Maui on Windows and Android Works fine but when you build the app for iOS it´s not working.

it works on iOS

https://user-images.githubusercontent.com/33021114/187489518-5d1f26ba-bb07-4d5e-b52c-b6e833497d49.mov

**Comment by Rabosa616** [comment] 2022-08-31 06:35
After reviewing the artifacts that are produced by my repo [https://github.com/Rabosa616/MauiMultilanguageApp/actions/runs/2887616872](https://github.com/Rabosa616/MauiMultilanguageApp/actions/runs/2887616872) , I do see that the iOS one has the spanish resources.
![image](https://user-images.githubusercontent.com/12774781/187609388-5451ab9e-dc46-4cc6-b490-bcaea9a4785a.png)
![image](https://user-images.githubusercontent.com/12774781/187609629-f48c9a39-e053-4e16-95fd-72d5761e9e68.png)
That artifact is produced by a Mac Agent.

When I try to compile on my windows developer machine does not produce it. I´m wondering if is a machine configuration or a bug in Visual Studio 2022 on windows machine not connected to any mac
![image](https://user-images.githubusercontent.com/12774781/187609915-a55c585e-bba1-41ab-a41b-3acabc6cb8a0.png)

**Comment by jfversluis** [comment] 2022-08-31 08:47
Duplicate of #5595

**Closed by jfversluis** 2022-08-31 08:47 UTC
Labels: t/bug, area/single project ☝️, platform/iOS 🍎
