### ISSUE TITLE
Can't find global resource dictionary

### ISSUE THREAD

**Issue by NicolasOnateR** [dotnet/maui#8799] opened 2022-07-18 07:06 UTC
### Description

I was trying to get by code behind a key in a ResourceDictionary, when I couldn't, I asked about on [StackOverflow](https://stackoverflow.com/questions/72977744/the-resource-is-not-present-in-the-dictionary) and there get a comment to write my problem here.

### Steps to Reproduce

1. New default proyect.
2. In MainPage.xaml.cs try to get the key like:

```
//Get Colors.xaml
var rd = App.Current.Resources.MergedDictionaries.First(); //Get the elements but null inside
//or
var rd1 = Resources["Secondary"] as Color; //null
//or
var rd2 = Application.Current.Resources["Secondary"]; //null
```

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows

**Comment by ExtSolTech** [comment] 2022-08-01 12:54
Here is an example:
[https://github.com/ExtSolTech/MAUIExamplesForIssues](url)

Description:
When the resource is implemented in place in App.xaml file work az expected.
When the resource is in separated file and referenced by URI in source, key value pairs not added to resources.
Very interest, the item count is visible/changed, but everything is null.
Another interest thing, in xaml working fine, but the code behind throw an exception: key not found

**Comment by arkadym** [comment] 2022-08-18 06:57
I face this issue many times! Today tried workaround by creating ResourceLocator class which will iterate over MergedDictionaries of the Application.Current.Resources and still it return null.

```
public interface IResourceLocator
{
    object this[string name] { get; }
}

```
```
public class ResourceLocator : IResourceLocator
{
	private ResourceDictionary _resourceDictionary = new ResourceDictionary();

	public ResourceLocator(ResourceDictionary rootResourceDictionary)
	{
		Add(rootResourceDictionary);
	}

	public void Add(ResourceDictionary resourceDictionary)
	{
        _resourceDictionary.Add(resourceDictionary);
        foreach (var rd in resourceDictionary.MergedDictionaries)
        {
            _resourceDictionary.Add(rd);
        }
    }

	public object this[string name]
	{
		get
		{
			object result = null;
			foreach (var rd in _resourceDictionary.MergedDictionaries)
			{
				if (rd.ContainsKey(name))
				{
					result = rd[name];
					break;
				}
			}
			return result;
		}
	}
}
```
I do register it with Autofac (dont think it matter)
```
builder.Register(c => new ResourceLocator(Resources)).As<IResourceLocator>();
```
When i try to use it - it returns null, i tried debug and found all the ResourceDictionaries are shows Count = XX (valid number) but Keys field is empty somehow...

**Comment by Martinedo** [comment] 2022-09-09 21:26
a workaround is to make a local Resource which has a BasedOn property on the global style 

```xaml
<ContentPage.Resources>
        <Style x:Key="button_icons_style_LOCAL" TargetType="Button" BasedOn="{x:StaticResource button_icons_style}"/>
</ContentPage.Resources>
```

and then to use the local one in the code.

```c#
new Button() { Style = (Style)Resources["button_icons_style_LOCAL"] }
```

**Comment by michaelrinderle** [comment] 2022-11-02 17:38
How is not being able to get global styles not on the front burner? We use this ALL the time.

**Comment by mrlacey** [comment] 2022-11-02 19:10
This is blocking us on a port from Xamarin.Forms. 
The workaround isn't practical based on the number and complexity of resource files we use.

**Comment by mrlacey** [comment] 2022-11-09 11:29
The issue is that resource dictionaries that are loaded from a separate file (as below) are treated differently internally (I think so they can be handled appropriately by XAML Hot Reload) but the lookup for individual resources wasn't accounting for this.

```xml
            <ResourceDictionary.MergedDictionaries>
                <ResourceDictionary Source="/Resources/MyOtherResourceDictionary.xaml" />
            </ResourceDictionary.MergedDictionaries>
````

PR coming soon

**Comment by sandeshkarki55** [comment] 2023-02-13 09:46
Using TryGetValue worked for me.
https://github.com/xamarin/Xamarin.Forms/issues/12592

**Comment by jfversluis** [comment] 2023-04-06 11:36
Besides the workaround mentioned a few comments above, the way to do this is indeed through `TryGetValue`. Also see the explanation here: https://github.com/dotnet/maui/pull/11214#issuecomment-1498922649

This is by design and we probably won't be fixing this any time soon.

**Closed by jfversluis** 2023-04-06 11:36 UTC
Labels: t/bug, area/Xaml </>
