### ISSUE TITLE
[MAUI]Enabling Remove Animations won't make both labels (Label 1, Label 2) fully visible immediately.

### ISSUE THREAD

**Issue by RoiChen001** [dotnet/maui#18644] opened 2023-11-09 09:28 UTC
### Description

【MAUI 】Enabling Remove Animations won't make both labels (Label 1, Label 2) fully visible immediately.

### Steps to Reproduce

1.Deploy https://devdiv.visualstudio.com/Pkgs/_git/VS.TestAssets.Xaml?path=/Assets/Projects/ManualMauiTests to Android.
2.Turn on developer mode of the emulator.
3.Click 'F'.
4.Click or tap on test 'F2'.
5.Enable Remove Animations. (Settings -> Accessibility -> Color and motion -> Remove animations.
6.View F2.

Actual result:
Label 1, Label 2 will not appear on the F2. (Sometimes only Label1 appears on the page.)

Expected result:
![image](https://github.com/dotnet/maui/assets/143168639/4a13ef78-1b2a-494c-aaeb-a872de447663)

### Link to public reproduction project repository

https://devdiv.visualstudio.com/Pkgs/_git/VS.TestAssets.Xaml?path=/Assets/Projects/ManualMauiTests

### Version with bug

Microsoft.Maui.Controls 8.0.0-nightly.9577+sha.baa86b2078-azdo.8654829

.NET SDK: 8.0.100

### Is this a regression from previous behavior?

Not a regression, this issue also repro on 8.0.0-rc.2.9530.

### Affected platforms

Android

**Comment by PureWeen** [comment] 2023-11-10 17:12
@RoiChen001 this should be fixed with the latest nightlies

It looks like the build you used here was before the fix for that test.

**Comment by jsuarezruiz** [comment] 2023-11-14 15:24
Cannot reproduce the issue in the current main branch (.NET 8 GA):
![image](https://github.com/dotnet/maui/assets/6755973/0cb46932-5b83-4166-8a7f-01a108fb86af)

**Comment by RoiChen001** [comment] 2023-11-15 02:24
@PureWeen  I verified it at the latest 8.0.0-nightly.9606+sha.275dd6d24f-azdo.8673829, this issue doesn't repro anymore.

**Closed** 2023-11-15 20:55 UTC
Labels: t/bug, area/animation 🎬, platform/android 🤖, s/needs-attention, potential-regression, csi-new
