### ISSUE TITLE
MAUI Navigation Stack null item bug

### ISSUE THREAD

**Issue by SunshineSpring666** [dotnet/maui#15101] opened 2023-05-16 06:13 UTC
### Description

The content of index 0 of NavigationStack is always null.

### Steps to Reproduce

1. Create a MAUI project
2. Run it and check the content of NavigationStack, see if it contains all the correct pages.

### Link to public reproduction project repository

https://github.com/SunshineSpring666/MAUI_NavigationStack_Null_Item_Bug.git

### Version with bug

8.0 previews

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Windows SDK 10.0.22000+

### Did you find any workaround?

Not yet.

**Comment by itsmuntadhar** [comment] 2023-05-16 08:37
same on iOS and Android too.

as a workaround you can wrap removing the page in a try-catch or check for null

**Comment by PureWeen** [comment] 2023-05-16 14:54
Duplicate of #https://github.com/dotnet/maui/issues/12162

**Closed by PureWeen** 2023-05-16 14:54 UTC
Labels: t/bug
