### ISSUE TITLE
SetSoftInputMode does not work

### ISSUE THREAD

**Issue by OrangeKeks** [dotnet/maui#22653] opened 2024-05-26 14:52 UTC
### Description

```cs
    protected override void OnAppearing()
    {
        try
        {
            base.OnAppearing();
#if ANDROID
    Platform.CurrentActivity?.Window?.SetSoftInputMode(Android.Views.SoftInput.AdjustResize);
#endif
            Debug.WriteLine("GOOOOOOOOOOOOOOOOD");
        }
        catch (Exception e)
        {
            Debug.WriteLine("Exception:>>" + e);
        }
    }

    protected override void OnDisappearing()
    {
        try
        {
            base.OnDisappearing();
#if ANDROID
    Platform.CurrentActivity?.Window?.SetSoftInputMode(Android.Views.SoftInput.AdjustPan);
#endif
            Debug.WriteLine("GOOOOOOOOOOOOOOOOD");
        }
        catch (Exception e)
        {
            Debug.WriteLine("Exception:>>" + e);
        }
    }
```

The console says "GOOOO....D", but when you open the keyboard, the window size does not change at all

video:

https://github.com/dotnet/maui/assets/129010142/303330ac-0c76-41dd-b07a-28d96ce0c44c

what should i do?

### Steps to Reproduce

1.  Create an entry
2. Add methods to your page:  

```cs
   protected override void OnAppearing()
    {
        try
        {
            base.OnAppearing();
#if ANDROID
    Platform.CurrentActivity?.Window?.SetSoftInputMode(Android.Views.SoftInput.AdjustResize);
#endif
            Debug.WriteLine("GOOOOOOOOOOOOOOOOD");
        }
        catch (Exception e)
        {
            Debug.WriteLine("Exception:>>" + e);
        }
    }

    protected override void OnDisappearing()
    {
        try
        {
            base.OnDisappearing();
#if ANDROID
    Platform.CurrentActivity?.Window?.SetSoftInputMode(Android.Views.SoftInput.AdjustPan);
#endif
            Debug.WriteLine("GOOOOOOOOOOOOOOOOD");
        }
        catch (Exception e)
        {
            Debug.WriteLine("Exception:>>" + e);
        }
    }
```

4. Nothing works

### Version with bug

8.0.7 SR2

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 13

**Comment by mattleibow** [comment] 2024-05-27 14:58
Duplicate of #14281

**Closed by mattleibow** 2024-05-27 14:58 UTC
Labels: t/bug, platform/android 🤖
