### ISSUE TITLE
[BUG] Grid is always InputTransparent (.NET MAUI 9.0 Preview 2)

### ISSUE THREAD

**Issue by janne-hmp** [dotnet/maui#21553] opened 2024-04-01 10:34 UTC
### Description

It seems that all grids are InputTransparent even when InputTransparent is set to false.

### Steps to Reproduce

1. Create an default .NET MAUI project
2. Add a Grid on the top of the existing default XAML (by making a root grid and putting the new Grid and ScrollView into it). Set the Grid's InputTransparent to false (and Horizontal and Vertical Options to FillAndExpand so it covers the Button for sure)

XAML is then:

```xaml
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="Net9MauiTest.MainPage">

    <Grid HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand">
        <ScrollView>
            <VerticalStackLayout
                Padding="30,0"
                Spacing="25">
                <Image
                    Source="dotnet_bot.png"
                    HeightRequest="185"
                    Aspect="AspectFit"
                    SemanticProperties.Description="dot net bot in a race car number eight" />

                <Label
                    Text="Hello, World!"
                    Style="{StaticResource Headline}"
                    SemanticProperties.HeadingLevel="Level1" />

                <Label
                    Text="Welcome to &#10;.NET Multi-platform App UI"
                    Style="{StaticResource SubHeadline}"
                    SemanticProperties.HeadingLevel="Level2"
                    SemanticProperties.Description="Welcome to dot net Multi platform App U I" />

                <Button
                    x:Name="CounterBtn"
                    Text="Click me" 
                    SemanticProperties.Hint="Counts the number of times you click"
                    Clicked="OnCounterClicked"
                    HorizontalOptions="Fill" />
            </VerticalStackLayout>
        </ScrollView>
        <Grid HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand" InputTransparent="False" />
    </Grid>
</ContentPage>
```

4. Build the project
5. You can still press the button

### Version with bug

9.0.0-preview.1.9973

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 14, perhaps all others as well, did not test

### Did you find any workaround?

Yes, I added an empty TapGestureRecognizer to the Grid, but the point is that InputTransparent does not work for the Grid. If it is intended, InputTransparent should be marked deprecated for Grid.

**Comment by jaosnz-rep** [comment] 2024-04-02 09:20
Verified on 9.0.0-preview.2.10293 & 9.0.0-preview.1.9973 & 8.0.14, cannot repro on Android platform, after replacing the code I can still click the button.

**Comment by janne-hmp** [comment] 2024-04-02 10:27
What is the latest version? I'm using the following (.NET MAUI Preview 2 / Visual Studio 17.10.0 Preview 2.0)

`
Microsoft Visual Studio Community 2022
Version 17.10.0 Preview 2.0
VisualStudio.17.Preview/17.10.0-pre.2.0+34707.107
Microsoft .NET Framework
Version 4.8.09032

Installed Version: Community

Visual C++ 2022   00482-90000-00000-AA350
Microsoft Visual C++ 2022

ASP.NET and Web Tools   17.10.173.6507
ASP.NET and Web Tools

Azure App Service Tools v3.0.0   17.10.173.6507
Azure App Service Tools v3.0.0

C# Tools   4.10.0-3.24127.5+e3d617bc46b0f92c2d2438188b35e009b942d0d1
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Extensibility Message Bus   1.4.39 (main@e8108eb)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Linux Core Dump Debugging   1.0.9.34707
Enables debugging of Linux core dumps.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Mono Debugging for Visual Studio   17.10.4 (67e63f0)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   6.10.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Razor (ASP.NET Core)   17.10.2.2415507+c5753a9c23d8422e24ed842c0ddad71e84d900d1
Provides languages services for ASP.NET Core Razor.

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

TypeScript Tools   17.0.30221.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.10.0-3.24127.5+e3d617bc46b0f92c2d2438188b35e009b942d0d1
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual C++ for Cross Platform Mobile Development (Android)   15.0.34707.36
Visual C++ for Cross Platform Mobile Development (Android)

Visual C++ for Cross Platform Mobile Development (iOS)   15.0.34707.36
Visual C++ for Cross Platform Mobile Development (iOS)

Visual C++ for Linux Development   1.0.9.34707
Visual C++ for Linux Development

Visual F# Tools   17.10.0-beta.24127.3+b57dee7cec971021547a7b8a36a46d7271fea99e
Microsoft Visual F# Tools

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

VSPackage Extension   1.0
VSPackage Visual Studio Extension Detailed Info

Xamarin   17.10.0.81 (main@b6ae522)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   17.10.1.36 (remotes/origin/d17-10@cf22639d5c)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   17.9.0 (38e87ba)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   13.2.2.0 (d17-5/45b0e14)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: d9a6e87
    Java.Interop: xamarin/java.interop/d17-5@149d70fe
    SQLite: xamarin/sqlite/3.40.1@68c69d8
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d17-5@ca1552d


Xamarin.iOS and Xamarin.Mac SDK   16.4.0.23 (9defd91b3)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
`

**Comment by mattleibow** [comment] 2024-06-20 12:50
Duplicate of https://github.com/dotnet/maui/issues/10252

**Comment by mattleibow** [comment] 2024-06-20 12:55
There was a workaround found in https://github.com/dotnet/maui/issues/9153#issuecomment-1295699420

> Simplest workaround for me was adding an empty TapGestureRecognizer to the view that's over top.

**Closed by mattleibow** 2024-06-20 12:55 UTC
Labels: t/bug, area-layout, platform/android 🤖, s/verified, s/triaged, migration-compatibility
