### ISSUE TITLE
Multi Columns Grid Height wrong on iOS / Android

### ISSUE THREAD

**Issue by muak** [dotnet/maui#14792] opened 2023-04-27 03:50 UTC
### Description

Height is not calculated correctly in Grid when two or more columns contain Label as a child.

On iOS, it displays correctly by not specifying RowHeight, but if Auto is specified for RowHeight, it will not display correctly.
On Android, only one line is displayed if RowHeight is not specified, and multiple lines are displayed if RowHeight is set to Auto, but not all the way to the end.

In the case of a single column, it is displayed correctly on both iOS and Android.

```xml
<Grid Padding="16" ColumnDefinitions="*,Auto">
    <Label
        Grid.Column="0"
        SemanticProperties.HeadingLevel="Level1"
        FontSize="18"
        Text="some long text..."/>
    <Image Grid.Column="1" Source="dotnet_bot" WidthRequest="24" HeightRequest="24" VerticalOptions="Center" />
</Grid>


<Grid Padding="16" ColumnDefinitions="*,Auto" RowDefinitions="Auto">
    <Label
        Grid.Column="0"
        SemanticProperties.HeadingLevel="Level1"
        FontSize="18"
        Text="some long text..."/>
    <Image Grid.Column="1" Source="dotnet_bot" WidthRequest="24" HeightRequest="24" VerticalOptions="Center" />
</Grid>
```

<img src="https://user-images.githubusercontent.com/16084475/234753566-dac730d2-0c9d-48f5-a2e5-4f1b95d148b9.png" width="200" /> <img src="https://user-images.githubusercontent.com/16084475/234753588-38932783-4510-46b5-b6fc-8cf04c21a0cc.png" width="200" />

### Steps to Reproduce

1. Put a Grid with multi colums
2. Put a Label in the Grid
3. Put any control in the Grid

```xml
<Grid Padding="16" ColumnDefinitions="*,Auto">
    <Label
        Grid.Column="0"
        FontSize="18"
        Text="some long text"/>
    <Image Grid.Column="1" Source="dotnet_bot" WidthRequest="24" HeightRequest="24" VerticalOptions="Center" />
</Grid>
```

### Link to public reproduction project repository

https://github.com/muak/Maui.GridIssue

### Version with bug

7.0 (current)

### Last version that worked well

7.0 (current)

### Affected platforms

iOS, Android

### Affected platform versions

Android11 / iOS14.7.1 / iOS16.4.1

### Did you find any workaround?

I can't find it.

**Comment by drasticactions** [comment] 2023-04-27 07:44
I believe @hartez PR for Grid fixed this, https://github.com/dotnet/maui/pull/14648

Checking against net7.0-SR4, I can replicate your issue

<img width="493" alt="stable-android" src="https://user-images.githubusercontent.com/898335/234794094-c73dfe11-4cda-406b-8eea-66e400cee3af.png">
<img width="493" alt="stable-ios" src="https://user-images.githubusercontent.com/898335/234794117-59b4be9a-e4ea-4b4f-8288-bb2119036131.png">

Checking in Main (In the MAUI Repo) and net7.0-SR5, it works.

<img width="492" alt="Main-Android" src="https://user-images.githubusercontent.com/898335/234794420-e58b96f2-906d-459d-929b-fdea3cfa66f1.png">
<img width="482" alt="Main-iOS" src="https://user-images.githubusercontent.com/898335/234794433-1819fba3-def4-4ef2-8202-6b14af4ce989.png">

I recommend updating to net7.0-SR5 or testing against Main to see if it works correctly for you.

**Comment by muak** [comment] 2023-04-27 08:14
@drasticactions 
Thank for your reply.

What version is net7.0-SR5?

My install verion is
```bash
dotnet --version
7.0.203
```
```bash
dotnet workload list             

インストール済みワークロードの ID      マニフェストのバージョン        インストール ソース 
-------------------------------------------------------
wasm-tools              7.0.5/7.0.100       SDK 7.0.200
maui-tizen              7.0.81/7.0.100      SDK 7.0.200
maui-ios                7.0.81/7.0.100      SDK 7.0.200
maui                    7.0.81/7.0.100      SDK 7.0.200

```

**Comment by drasticactions** [comment] 2023-04-27 08:43
7.0.84, https://github.com/dotnet/maui/releases/tag/untagged-31badb40bea3071ab585.
I don't know if it has been released yet.

**Comment by muak** [comment] 2023-04-27 08:48
@drasticactions 

Thanks.
I wait for release.

**Comment by hartez** [comment] 2023-05-03 22:35
Duplicate of #14537

**Closed by hartez** 2023-05-03 22:35 UTC
Labels: t/bug, area/layout 🔲, s/needs-attention, layout-grid
