### ISSUE TITLE
ToolbarItem's IconImageSource : Dynamic source change from embedded image resource bug. 

### ISSUE THREAD

**Issue by BalachandarSelvam** [dotnet/maui#10648] opened 2022-10-12 15:49 UTC
### Description

While using the embedded source image for dynamically updating the ToolbarItem's IconImageSource by a toolbar item clicked event, the image doesn't gets changed unless the toolbar item  was clicked 3 or 4 times.

### Steps to Reproduce

1. Open and run the attached sample
2. Click on "Open" text on top right corner of tool bar item
3. Click the image until the next image is changed dynamically. 

### Link to public reproduction project repository

https://github.com/BalachandarSelvam/ToolbarBug

### Version with bug

6.0.536

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 9

**Comment by PureWeen** [comment] 2022-10-12 18:08
Duplicate of #8295

**Closed by PureWeen** 2022-10-12 18:08 UTC
Labels: t/bug, platform/android 🤖, area/navigation 🧭
