### ISSUE TITLE
Images do not layout correctly in iOS

### ISSUE THREAD

**Issue by williambuchanan2** [dotnet/maui#13893] opened 2023-03-13 21:16 UTC
### Description

I have noticed that in iOS, images do not display in the proper location. I have created pages which appear perfect in Android and follow the layout rules as you would expect, but the same pages are messed up in iOS.

What happens is any images seem to get displayed relative to the top left of the page, regardless of their container. They also seem to resize to some crazy sizes. So for example, if you have an image inside a grid or a border somewhere on the page, rather than being inside that container the image will appear outside the container and will be a random size.

I have noticed the same issue with ImageButton, and the problem happens when you have the images inside a listview and other places.

The only way to get them to appear in the right place is to specify a height an/or width which is undesirable if you want your images to fill the space which is given to them.

### Steps to Reproduce

Run app from repository below. On the main page choose:
"Image Problem 2" - this shows the problem with images not sizing or positioning properly.
"Image problem 3" - this shows the problem with the ImageButtons not sizing properly.

### Link to public reproduction project repository

https://github.com/williambuchanan2/MauiNavigation

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 16

### Did you find any workaround?

Have to specify fixed height or width to all images

**Comment by williambuchanan2** [comment] 2023-04-10 10:36
Just wondering if there is an update on this one. This is a critical issue. Basically any app with an image in it cannot be deployed as a result of this bug. 

The images are not placed where you need them to be. They do not size automatically to fit their parent, and they do not size accurately even if you give them a size. It affects image and imagebutton.

Would be good to know if there is a fix for this coming soon...

**Comment by hartez** [comment] 2023-04-10 18:37
@williambuchanan2 Could you please post a repro project? Because it's an image-related issue, it helps if we have actual images which reproduce this issue for the investigation. That way we can determine whether the problem is related to specific image aspect ratios, sizes, etc. on the platform in question. Thanks!

**Comment by williambuchanan2** [comment] 2023-04-10 22:33
I have updated the details above with a link to a repository with a demo app to reproduce the problems. Below is what I see.

"Image problem 2"
iPhone:

![image](https://user-images.githubusercontent.com/32165641/231011372-730ade46-5e0c-4ccf-a9c7-76c104b7c281.png)

Android (same screen):

![image](https://user-images.githubusercontent.com/32165641/231011417-375686c9-4065-4c1f-a16a-1bff324ff411.png)

"Image problem 3"
iPhone (notice how images always remain the same size no matter what size you request):

![image](https://user-images.githubusercontent.com/32165641/231011500-a270cc15-26cd-4430-81d4-1745b3ab6d23.png)

Android (notice how in Android the images actually resize as requested):

![image](https://user-images.githubusercontent.com/32165641/231011610-cf69aaf4-e1a8-4b6c-bf59-986a2ec76adc.png)

**Comment by williambuchanan2** [comment] 2023-04-11 01:16
In fact, if you tap the "Image Error" button you will also see another problem (might be related but might not).

iPhone looks like this:

![image](https://user-images.githubusercontent.com/32165641/231030055-ce587123-e292-4c7c-87d8-c79ee03b5b93.png)


Android looks like this:

![image](https://user-images.githubusercontent.com/32165641/231030085-d62ed0dc-d675-4d83-aaeb-c7841a1bc936.png)


Notice how in Android the image just fills the space nicely without the need to specify a size. In iOS however this doesn't happen. The image gets chopped off, and the container is expanded off the bottom of the screen. The only way to get it to fit in iOS is to specify a size, but this results in poor sizing on different screen sizes.

**Comment by williambuchanan2** [comment] 2023-04-17 01:51
Just checking if there is any update on this, or some kind of workaround?

**Comment by Xyncgas** [comment] 2023-05-03 21:40
one alternative is using webview to fix everything you can't fix for now, in the future developing for IOS then see if it works in android is a better way, it's weird but hey it's apple and it's what people developing xamarin app do and it's the way

**Comment by MichaelShapiro** [comment] 2023-05-19 20:15
@williambuchanan2 Are you seeing this behavior in both - debug and deploy (TestFLight) - modes? Asking becasue I see this weird image resizing, not fitting in the container, issue only when I compile and deploy to TestFlight and install on a device. However, when I just debug in Visual Studio on a connected device - all images are sized correctly. One thing I must note is that I compile and deploy through Azure pipeline, which means the app ipa file is being build on the mac OS hosted on Azure servers. When I debug locally then the app is built by my local Mac.

**Comment by williambuchanan2** [comment] 2023-05-20 00:56
> @williambuchanan2 Are you seeing this behavior in both - debug and deploy (TestFLight) - modes? 

Hi @MichaelShapiro I am seeing this on all devices (simulator and physical devices). We are also using Azure pipelines and TestFlight and I see it whether I deploy through Azure, or deploy straight to device from VS for Mac. 

On the version you see which does work - are you deploying from a PC or Mac? I could never get the deploy direct from PC to work so I have been using a Mac.

**Comment by MichaelShapiro** [comment] 2023-05-20 01:48
@williambuchanan2 I have Visual Studio installed on WIndows PC, but, of course, I do have MAC on the same network that is just  build server for the iOS app. So, whenever I am in debug configuration and deploy either to physical device (via MAC) or to a simulator (also MAC) - all images are appropriately sized and respect the AspectFit value of the Aspect property.

**Comment by williambuchanan2** [comment] 2023-05-20 02:02
> @williambuchanan2 I have Visual Studio installed on WIndows PC, but, of course, I do have MAC on the same network that is just build server for the iOS app. So, whenever I am in debug configuration and deploy either to physical device (via MAC) or to a simulator (also MAC) - all images are appropriately sized and respect the AspectFit value of the Aspect property.

Strange - so it sounds like the problem is related to the 'mac only' scenario. When a PC is involved it sounds like it works ok - which doesn't make sense since it is still a mac generating the binaries. It's a huge issue considering how most apps contain a lot of images.

**Comment by MichaelShapiro** [comment] 2023-05-20 02:08
" It's a huge issue" .. is an understatement:)  I suspect.. I might be wrong, but... what if whatever xcode version I use to build here locally is different than the Azure pipeline server has? I might try to publish to TestFlight directly from my local MAC (where the app is built during the debug sessions) and see if the app behaves different once I download it on one of my test phones. I jsut have to remember how to deploy from a local mac :)

**Comment by williambuchanan2** [comment] 2023-05-20 02:10
> I jsut have to remember how to deploy from a local mac :)

It's an easy 50 step badly documented process which only works if you don't follow the published instructions - i'm sure you'll work it out given a few months :)

**Comment by MichaelShapiro** [comment] 2023-05-22 15:50
@williambuchanan2 I might have some positive news. Not sure how they might apply or help in your specific situation, but let me share.

Firstly, I updated VS to version 17.6.0. Then I checked and confirmed that compiling and deploying via local MAC and Azure pipeline produce the same result and reflect whatever behavior I'm seeing while in debug mode. Yes, that goes against what I mentioned in my previous post - perhaps it was some inaccurate testing i did before or becasue I was stating that prior to updating to VS 17.6.0. At any rate - right now deploying in debug mode, or deploying via Azure yields the same result (whatever the result might be.)

I think I found what works to keep the image within the constrains on iOS.  In my numerous tests I used "Fill" for vertical and horizontal options and I set values for max width and height requests. It looks (again, according to my tests) that any value will work as long as there is some value. Even a value of "one" is ok and image is properly fitted and resized within n container - in my case a grid's row. 

Feels like a hack, but nothing else works with the exception of specifying an exact width and height for the image. Hope it will be fixed soon. By the way - deploying on Android (in debug configuration) with these MaximumWidthRequest and MaximumHeightRequest values doesn't break the way the image is sized and positioned. 

If you care to test this - it would be interesting to know your results.
```

<Grid
    RowDefinitons="0.25*, 0.75*">

  <Image
    Source = "....."
    Grid.Row=0

    Aspect="AspectFit" 
    MaximumWidthRequest="1"
    MaximumHeightRequest="1"  
    VerticalOptions="Fill"
    HorizontalOptions="Fill" />

  <other elements .... />
</Grid>
```

**Comment by williambuchanan2** [comment] 2023-05-23 11:56
> @williambuchanan2 I might have some positive news. Not sure how they might apply or help in your specific situation, but let me share.
> 

Hi @MichaelShapiro thanks for the tip.

Really strange. It shouldn't work - but it does... At least for one of my scenarios. I have a couple of other scenarios and it doesn't work for them. So, thanks - that's another problem fixed with a temporary workaround!

I guess on the negative side, this does mean the MaximumHeightRequest and MaximumWidthRequest are buggy, but hey i'm way beyond caring. Let's just hope they fix the image size problem before they fix the MaximumWidthRequest problem, otherwise we will be back to square 1 :)

Cheers

**Comment by jinxinjuan** [comment] 2023-06-15 02:47
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 1.0. Can repro on iOS platform with sample project.
https://github.com/williambuchanan2/MauiNavigation

**Comment by Blinchik91** [comment] 2023-06-30 10:16
@MichaelShapiro this workaround is not working in my case.
Even a grid is not able to fit an image on ios correctly

**Comment by dpozimski** [comment] 2023-07-23 12:52
what is the status of this issue?

**Comment by luis95gr** [comment] 2023-08-19 15:24
Is there any update on this?

**Comment by Richard-Dufour** [comment] 2023-08-23 15:59
Can someone PLEASE provide an update. 

Listen, I get it, we are all busy, but this (like many other, I know) is a critical issue. Unacceptable that this post started in March, and here we are now (August) still wondering what to do to display an image in iOS.

**Comment by dpozimski** [comment] 2023-08-23 17:49
is it planned to be fixed in .net 8 ?

**Comment by jknaudt21** [comment] 2023-09-01 19:13
Linked to: #16120

**Closed** 2023-10-23 16:46 UTC
Labels: t/bug, area/layout 🔲, platform/iOS 🍎, area/controls 🎮, s/verified, control-image, s/triaged, s/needs-attention
