### ISSUE TITLE
[Android]Entry is not unfocus when click in the button

### ISSUE THREAD

**Issue by saiganesh-sakthivel** [dotnet/maui#15681] opened 2023-06-15 13:15 UTC
### Description

I have two entries and one button in the view. In Android, when we enter the entry and click on the button. The focus on the entry is still maintained. In UWP, the entry automatically unfocuses when we click on the button.

### Steps to Reproduce

1. Run the sample in the android platform.
2. Click the entry in the view.
3. Click the button in the view and previous select the entry will remain in the focus.

### Link to public reproduction project repository

https://github.com/dotnet/maui/files/11757911/MauiApp1.zip

### Version with bug

7.0.49

### Last version that worked well

6.0

### Affected platforms

Android

### Affected platform versions

Android 11

**Comment by PureWeen** [comment] 2023-06-15 16:07
@saiganesh-sakthivel why do you want it to unfocus on android? Are you wanting the keyboard to close? Is there something else you are wanting to happen? It's not default behavior on `android` for the entry to unfocus so we don't unfocus it. Which is largely due to accessibility reasons.

**Comment by saiganesh-sakthivel** [comment] 2023-06-16 04:35
Hi @PureWeen,

We are committing the value of the entry in the data, when we are changing the focus of the control(entry). For example, two entries (email, password) and a button (password). when the user clicks the email (entry) type and click the password (entry), focus changed from the email to the password(entry). After the password type and click to the login (button), the password (entry) is not unfocused. Due to this behavior, the commit value after lostfocus scenario breaks.

**Comment by Starchm** [comment] 2023-07-06 14:42
Hi @PureWeen , 
We have the same problem as saiganesh-sakthivel, we want to commit the value to the API when the entry is unfocused. But i think we dont need the entry to be unfocused, just get some event which will be triggered if the entry is completed or somebody tapped out of it. What do you think, is it possible to implement some event like that?

**Comment by XamlTest** [comment] 2023-07-24 10:05
Verified this on Visual Studio Enterprise 17.7.0 Preview 4.0. Repro on Android 13.0-API33 .NET 8, not repro on Windows 11 and iOS 16.4 with below Project:
[15681.zip](https://github.com/dotnet/maui/files/12144548/15681.zip)

**Comment by Gekidoku** [comment] 2023-10-13 09:12
In our case we have an editor where we dont want every text update to trigger a call to our api to save the text. we want this to happen when the user is done. IE unfocus / click another element on the page.

**Comment by mattleibow** [comment] 2023-11-17 21:50
Duplicate of https://github.com/dotnet/maui/issues/11881

**Closed by mattleibow** 2023-11-17 21:50 UTC
Labels: t/bug, platform/android 🤖, area/a11y, s/verified, s/triaged, s/needs-attention
