### ISSUE TITLE
Java.Lang.RuntimeException: Unable to instantiate activity 

### ISSUE THREAD

**Issue by Muhammadfaizann** [dotnet/maui#18523] opened 2023-11-04 18:38 UTC
### Description

I am trying to instantiate an activity but getting this exception

```
Java.Lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.companyname.maui/com.companyname.maui.UnityActivity}: java.lang.ClassNotFoundException: Didn't find class "com.companyname.maui.UnityActivity" on path: DexPathList[[zip file "/data/app/~~SC-ifPLoehL-YwKYQy1aAA==/com.companyname.maui-Av9v5tzB8D3ddZVOgP5gPg==/base.apk"],nativeLibraryDirectories=[/data/app/~~SC-ifPLoehL-YwKYQy1aAA==/com.companyname.maui-Av9v5tzB8D3ddZVOgP5gPg==/lib/arm64, /data/app/~~SC-ifPLoehL-YwKYQy1aAA==/com.companyname.maui-Av9v5tzB8D3ddZVOgP5gPg==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]] ---> Java.Lang.ClassNotFoundException: Didn't find class "com.companyname.maui.UnityActivity" on path: DexPathList[[zip file "/data/app/~~SC-ifPLoehL-YwKYQy1aAA==/com.companyname.maui-Av9v5tzB8D3ddZVOgP5gPg==/base.apk"],nativeLibraryDirectories=[/data/app/~~SC-ifPLoehL-YwKYQy1aAA==/com.companyname.maui-Av9v5tzB8D3ddZVOgP5gPg==/lib/arm64, /data/app/~~SC-ifPLoehL-YwKYQy1aAA==/com.companyname.maui-Av9v5tzB8D3ddZVOgP5gPg==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
  at java.lang.ClassNotFoundException: Didn't find class "com.companyname.maui.UnityActivity" on path: DexPathList[[zip file "/data/app/~~SC-ifPLoehL-YwKYQy1aAA==/com.companyname.maui-Av9v5tzB8D3ddZVOgP5gPg==/base.apk"],nativeLibraryDirectories=[/data/app/~~SC-ifPLoehL-YwKYQy1aAA==/com.companyname.maui-Av9v5tzB8D3ddZVOgP5gPg==/lib/arm64, /data/app/~~SC-ifPLoehL-YwKYQy1aAA==/com.companyname.maui-Av9v5tzB8D3ddZVOgP5gPg==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
  at at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
  at at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
  at at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
  at at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
  at at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:45)
  at at android.app.Instrumentation.newActivity(Instrumentation.java:1339)
  at at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3538)
  at at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3782)
  at at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
  at at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
  at at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
  at at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
  at at android.os.Handler.dispatchMessage(Handler.java:106)
  at at android.os.Looper.loopOnce(Looper.java:201)
  at at android.os.Looper.loop(Looper.java:288)
  at at android.app.ActivityThread.main(ActivityThread.java:7872)
  at at java.lang.reflect.Method.invoke(Native Method)
  at at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
  at at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
  --- End of inner exception stack trace ---
  at java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.companyname.maui/com.companyname.maui.UnityActivity}: java.lang.ClassNotFoundException: Didn't find class "com.companyname.maui.UnityActivity" on path: DexPathList[[zip file "/data/app/~~SC-ifPLoehL-YwKYQy1aAA==/com.companyname.maui-Av9v5tzB8D3ddZVOgP5gPg==/base.apk"],nativeLibraryDirectories=[/data/app/~~SC-ifPLoehL-YwKYQy1aAA==/com.companyname.maui-Av9v5tzB8D3ddZVOgP5gPg==/lib/arm64, /data/app/~~SC-ifPLoehL-YwKYQy1aAA==/com.companyname.maui-Av9v5tzB8D3ddZVOgP5gPg==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
  at at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3551)
  at at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3782)
  at at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
  at at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
  at at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
  at at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
  at at android.os.Handler.dispatchMessage(Handler.java:106)
  at at android.os.Looper.loopOnce(Looper.java:201)
  at at android.os.Looper.loop(Looper.java:288)
  at at android.app.ActivityThread.main(ActivityThread.java:7872)
  at at java.lang.reflect.Method.invoke(Native Method)
  at at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
  at at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
  at Caused by: java.lang.ClassNotFoundException: Didn't find class "com.companyname.maui.UnityActivity" on path: DexPathList[[zip file "/data/app/~~SC-ifPLoehL-YwKYQy1aAA==/com.companyname.maui-Av9v5tzB8D3ddZVOgP5gPg==/base.apk"],nativeLibraryDirectories=[/data/app/~~SC-ifPLoehL-YwKYQy1aAA==/com.companyname.maui-Av9v5tzB8D3ddZVOgP5gPg==/lib/arm64, /data/app/~~SC-ifPLoehL-YwKYQy1aAA==/com.companyname.maui-Av9v5tzB8D3ddZVOgP5gPg==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
  at at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
  at at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
  at at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
  at at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
  at at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:45)
  at at android.app.Instrumentation.newActivity(Instrumentation.java:1339)
  at at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3538)
  at ... 12 more
```
My AndroudMenfest.xml: 

```xml
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.companyname.maui" android:versionCode="1" android:versionName="1.0">
	<application android:allowBackup="true" android:icon="@mipmap/appicon" android:supportsRtl="true" android:label="maui">
		<activity android:name=".UnityActivity" android:exported="true">
			<intent-filter>
				<action android:name="android.intent.action.MAIN" />
				<category android:name="android.intent.category.LAUNCHER" />
			</intent-filter>
		</activity>
	</application>
	<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
	<uses-permission android:name="android.permission.INTERNET" />
	<uses-sdk android:minSdkVersion="22" android:targetSdkVersion="33" />
</manifest>
```

UnityActivity: 

```cs
using Android.App;
using Android.Content.PM;
using Android.OS;
using Com.Unity3d.Player;

namespace maui
{
    [Activity(
        Label = "UnityActivity",
        ConfigurationChanges = ConfigChanges.ScreenSize | ConfigChanges.Orientation,
        ScreenOrientation = ScreenOrientation.FullUser,
        Theme = "@android:style/Theme.NoTitleBar")]
    public class UnityActivity : Activity
    {
        private UnityPlayer unityPlayer;

        public UnityActivity()
        {

        }

        protected override void OnCreate(Bundle savedInstanceState)
        {
            base.OnCreate(savedInstanceState);

            unityPlayer = new UnityPlayer(this);
            SetContentView(unityPlayer);
        }

        protected override void OnPause()
        {
            base.OnPause();
            unityPlayer.Pause();
        }

        protected override void OnResume()
        {
            base.OnResume();
            unityPlayer.Resume();
        }

        protected override void OnDestroy()
        {
            base.OnDestroy();
            unityPlayer.Quit();
        }

    }
}
```

### Link to public reproduction project repository

(https://github.com/Muhammadfaizann/maui)

### Version with bug

7.0.96

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

**Comment by mattleibow** [comment] 2023-11-06 15:16
@jonathanpeppers is there supposed to be a constructor provided on android? Does the generator automatically do this and should not actually be explicitly implemented?

**Comment by Muhammadfaizann** [comment] 2023-11-06 15:26
I have attached a public repository of the sample project. Basically, I am trying to run the Unity app in a .NET MAUI project.

**Comment by jonathanpeppers** [comment] 2023-11-06 16:30
The problem is:
```
java.lang.ClassNotFoundException: Didn't find class "com.companyname.maui.UnityActivity" on path: 
```

There is no `com.companyname.maui.UnityActivity` Java class in your app. Unless you use `[Register("com.companyname.maui.UnityActivity")]` on your activity, it will have an auto-generated package name like `crc1234...`.

What you _should_ actually do, is delete the `<activity>` block in your manifest and just set `MainLauncher=true` as well as any other settings on the `[Activity]` custom attribute.

**Comment by Muhammadfaizann** [comment] 2023-11-06 16:58
It shows the following pop up

![Screenshot_1699289780](https://github.com/dotnet/maui/assets/40601789/c7de0ed3-86fe-4b37-98a1-13478be36ebf)

**Comment by Muhammadfaizann** [comment] 2023-11-06 17:06
Thanks @jonathanpeppers it is no longer through the exception but two things are happening 
1) For some reason the project created two instances on the app
![image](https://github.com/dotnet/maui/assets/40601789/05d9323e-7fc3-44be-8788-66489bdfc2e3)
2) The following pop-up is showing
![Screenshot_1699209593](https://github.com/dotnet/maui/assets/40601789/75b07b50-5a8d-40df-9124-33955a317298)

I would greatly appreciate your assistance.

**Comment by Muhammadfaizann** [comment] 2023-11-06 17:40
Yes, I have removed the `activity` tag from the `AndroidManifest.xml` now I am just starting the `UnityActivity` from `OnCreate` function from `MainActivity` using an `Intent`.

The project refers to a DLL file created with Android Java Binding Library, containing a .aar file generated from an Android Native project exported from Unity using Android Studio.

**Comment by jonathanpeppers** [comment] 2023-11-07 17:30
If you inspect `adb logcat` output, Android should say why `libmain.so` cannot be loaded. It may be another `.so` file is not found, this is commonly what would go wrong here.

@Muhammadfaizann I don't believe the issues you are seeing here are related to .NET MAUI. Closing for now, thanks! If you have further questions about the Android workload you can file issues here:

* https://github.com/xamarin/xamarin-android/issues

**Closed by jonathanpeppers** 2023-11-07 17:30 UTC
Labels: t/bug, platform/android 🤖, s/needs-attention, partner/android
