### ISSUE TITLE
string assignment is everytime null

### ISSUE THREAD

**Issue by lk-code** [dotnet/maui#7688] opened 2022-06-02 11:06 UTC
### Description

In my .NET MAUI project, a string assignment is always NULL (iOS target only).

### Steps to Reproduce

Ich habe eine Methode, welche den AppCenter-Secret String erstellt:

```c#
StringBuilder stringBuilder = new StringBuilder();
if (!string.IsNullOrEmpty(appCenterSettings.UWP))
{
    stringBuilder.AppendFormat("uwp={0};", appCenterSettings.UWP);
}
if (!string.IsNullOrEmpty(appCenterSettings.iOS))
{
    stringBuilder.AppendFormat("ios={0};", appCenterSettings.iOS);
}
if (!string.IsNullOrEmpty(appCenterSettings.macOS))
{
    stringBuilder.AppendFormat("macos={0};", appCenterSettings.macOS);
}
if (!string.IsNullOrEmpty(appCenterSettings.Android))
{
    stringBuilder.AppendFormat("android={0};", appCenterSettings.Android);
}
string secret = stringBuilder.ToString();
return secret;
```

`string secret` is NULL every time (iOS Target). On android and Windows the string is not null and contains a correct value.

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15

**Comment by drasticactions** [comment] 2022-06-02 15:11
`appCenterSettings`

Is this a library you're using?

**Comment by lk-code** [comment] 2022-06-02 15:31
> Sorry, I forgot that line :)

This is the variable for the .NET MAUI Config class:
`Settings.AppCenter appCenterSettings = this._configuration.GetRequiredSection("AppCenter").Get<Settings.AppCenter>();`

When I look at the content in Visual Studio, it is correct:
<img width="798" alt="image" src="https://user-images.githubusercontent.com/1656571/171665153-c6ca5880-8087-4304-9254-40a1bf7e26e8.png">

PS: I have created the .NET MAUI project in the latest Visual Studio Preview version (17.3.0 Preview 1.1).

**Comment by xtuzy** [comment] 2022-06-03 03:30
Do you set break point to run it every step?

**Comment by lk-code** [comment] 2022-06-03 09:27
> Do you set break point to run it every step?

yes

**Comment by hartez** [comment] 2022-06-06 23:52
I think this may be another instance of #7009. If you output the string variable to the console (`System.Diagnostics.Debug.WriteLine()`), does the correct value display?

**Comment by beeradmoore** [comment] 2022-06-08 03:47
Also if you make the variable a private class variable (as a test) does it then display correctly in the debugger?

**Comment by lk-code** [comment] 2022-06-08 09:28
> I think this may be another instance of #7009. If you output the string variable to the console (`System.Diagnostics.Debug.WriteLine()`), does the correct value display?

That's right. The correct value is given in the output.

I was now wondering why the MAUI app crashes on iOS and I put a try-catch around the following code:
```c#
string appCenterId = this.GetAppCenterId();

if (string.IsNullOrEmpty(appCenterId))
{
    return;
}

try
{
    AppCenter.Start(appCenterId,
        typeof(Analytics),
        typeof(Crashes));
}
catch (Exception err)
{
    System.Diagnostics.Debug.WriteLine($"err: {err.ToString()} {err.Message}");
}
```

this is the exception output:

```
err: System.TypeInitializationException: The type initializer for 'Microsoft.AppCenter.Utils.ApplicationLifecycleHelperDesktop' threw an exception.
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies.
File name: 'System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
```

I don't think 'System.Windows.Forms' is needed under AppCenter (iOS), is it? 😅

**Comment by lk-code** [comment] 2022-06-08 09:34
I think it is this issue: https://github.com/dotnet/maui/issues/7175

**Comment by jfversluis** [comment] 2022-06-15 06:59
Duplicate of #7009

**Closed by jfversluis** 2022-06-15 06:59 UTC
Labels: t/bug, area/tooling ⚙️, platform/iOS 🍎
