### ISSUE TITLE
.NET MAUI Button on Android

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#8139] opened 2022-06-17 16:19 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/NET-MAUI-Button-on-Android/10072090)._

---
[severity:It's more difficult to complete my work] [regression] [worked-in:17.3.0 Preview 2.0]
While testing a .NET MAUI application the button does not expand when new text is added for an Android application.

The button does expand for Windows and IOS applications.

For example, the initial text for a button is Click Me. After the button is clicked the text expands to Clicked X times. On Windows and IOS the button expands to display the full text. But on Android, the button clips the text and is only displaying the word Clicked.

---
#### Feedback Bot on 6/15/2022, 10:57 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by Symbai** [comment] 2022-06-17 21:47
Dupe of #8071

**Comment by jfversluis** [comment] 2022-06-18 07:30
Thanks @Symbai !

**Comment by jfversluis** [comment] 2022-06-18 07:31
Duplicate of #8071

**Closed by jfversluis** 2022-06-18 07:31 UTC
Labels: area/controls 🎮, control-button
