### ISSUE TITLE
RC2 Border.Stroke Shape is not fully displayed

### ISSUE THREAD

**Issue by HausBJB** [dotnet/maui#6804] opened 2022-05-04 10:08 UTC
### Description

Hello, I have a border with EllipseGeometry that is not fully displayed

`<Grid BackgroundColor="Black">
        <Border 
                WidthRequest="150"
                HeightRequest="150"
                Stroke="#C49B33"
                StrokeThickness="4"
                Background="#2B0B98"
                HorizontalOptions="Center">
            <Border.StrokeShape>
                <EllipseGeometry RadiusX="50" RadiusY="50" Center="50,50"/>
            </Border.StrokeShape>
            <Label Text=".N"
                   VerticalOptions="Center"
                   HorizontalOptions="Center"
                   TextColor="White"
                   FontSize="18"
                   FontAttributes="Bold" />
        </Border>
    </Grid>`

Repro
https://github.com/HausBJB/MauiApp2.git

![image](https://user-images.githubusercontent.com/53478848/166662026-b70e807b-42e8-4a0e-b4e1-b393581f45cd.png)

### Steps to Reproduce

1. Create new MauiApp
2. Add XAML code in MainPage 
3. Run App

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 12 (API 31)

### Did you find any workaround?

NO

**Comment by jfversluis** [comment] 2022-05-04 11:26
Wow did you time this?! 😄 closing this as duplicate of #6804

**Closed by jfversluis** 2022-05-04 11:26 UTC
Labels: t/bug, s/needs-verification

**Comment by HausBJB** [comment] 2022-05-04 11:40
Do you mean ticket # 6805? No we didn't time this, my was first ;)

[6805](https://github.com/dotnet/maui/issues/6805)

**Comment by HausBJB** [comment] 2022-05-24 15:46
Hello the problem is still there

Version GA (6.0.312)

https://github.com/dotnet/maui/issues/6804
