### ISSUE TITLE
Suggestion: Incorporating Animated Full Image Splash Screen in .NET MAUI

### ISSUE THREAD

**Issue by mdazhar780** [dotnet/maui#21171] opened 2024-03-13 04:35 UTC
### Description

Splash screens are an essential component of modern mobile applications, offering an opportunity to engage users while the app loads in the background. Other platforms like React Native and Flutter provide developers with the ability to create dynamic and visually appealing splash screens, often featuring full-image animations that captivate the user's attention from the moment they launch the app.

Integrating a similar feature into .NET MAUI would not only align it more closely with industry standards but also enhance the overall aesthetics and user experience of applications built with the framework. By allowing developers to create splash screens with animated full images, .NET MAUI could provide an even more immersive and polished experience for end-users.

I understand that implementing such a feature may require careful consideration and development resources. However, I believe the benefits it would bring to the .NET MAUI ecosystem would be significant. Not only would it empower developers to create more visually stunning applications, but it would also contribute to the platform's competitiveness in the rapidly evolving landscape of cross-platform app development.

I encourage you to consider this suggestion as you continue to enhance and refine .NET MAUI. Thank you for your dedication to advancing the .NET ecosystem, and I look forward to seeing the continued evolution of this fantastic framework.

### Public API Changes

Splash Screen

### Intended Use-Case

And Make some component for appshell menu tab stylish

**Comment by jfversluis** [comment] 2024-03-13 10:15
Duplicate of #3300

**Closed by jfversluis** 2024-03-13 10:15 UTC
Labels: proposal/open
