### ISSUE TITLE
Frame Property "IsVisible" not being properly displayed when changing Boolean value to true in backend C# when initialized False in XAML

### ISSUE THREAD

**Issue by Vpatel541** [dotnet/maui#8084] opened 2022-06-15 18:41 UTC
### Description

I have a frame item in the XAML code that is initially set to IsVisible = False. Then I have a button that when you click on the button, it should set the IsVisible property to True. But the property is being set to true but the frame is not visible on the Android emulator. This works normally on the Windows Machine debugger. I cannot test this on IOS but I am assuming the same issue applies there. 

### Steps to Reproduce

1. Create a new .NET MAUI project.
2. Add this frame to the MainPage.xaml file: 
```
<Frame x:Name="frameTest"  VerticalOptions="Start"  Margin="0,0,0,0" BackgroundColor="Green" IsVisible="False"
</Frame>
```

3. In the CounterBtn (Which is part of the example code when you first create a .NET MAUI app), replace the contents of the OnCounterClicked function with:

```
private void OnCounterClicked(object sender, EventArgs e)
	{
		frameTest.IsVisible = true;
	}
```

4. Now run the program on the Android Emulator, any version should work, I used the Pixel 5 (Android 11.0 - API 30)
5. Click on the button, the Green Frame should come into view but it is not. 

### Version with bug

6.0.400 (current)

### Last version that worked well

6.0 Release Candidate 3

### Affected platforms

Android

### Affected platform versions

Android 10 and up

### Did you find any workaround?

No

**Comment by kristinx0211** [comment] 2022-06-16 01:28
verified repro on android 12 with above project. it works on windows.

**Comment by RonnyRos** [comment] 2022-06-16 07:51
Probably linked to #8044

**Comment by jfversluis** [comment] 2022-06-16 09:37
Duplicate of #8044

**Closed by jfversluis** 2022-06-16 09:37 UTC
Labels: t/bug, s/verified

**Comment by PaulAnderson02** [comment] 2022-06-22 06:44
@jfversluis  Will the fix be released today
