### ISSUE TITLE
Windows .NET MAUI App throws Exception when closing second window

### ISSUE THREAD

**Issue by mprattinger** [dotnet/maui#12956] opened 2023-01-27 12:43 UTC
### Description

I have an app, where multiple windows can be opened. In the window, there is an WebView showing a company website. When i have only one window open, i can close it normally.
But if i have opened a second window, with the same page i get the following error message "The group or resource is not in the correct state to perform the requested operation. (0x8007139F)" when closing one of the windows.

r Michael

### Steps to Reproduce

1. Create a new .Net Maui App.
2. On the MainPage add a button and a WebView
3. Set the source of the webview to a webpage
4. Add the code, to open a new window when clicking the button -> Application.Current.OpenWindow(new Window(new MainPage()));
5. When now closing the new page for example, the mentioned exception gets thrown.

### Link to public reproduction project repository

https://github.com/mprattinger/MauiMultiWindow

### Version with bug

6.0.312

### Last version that worked well

7.0 (current)

### Affected platforms

Windows

### Affected platform versions

net7.0-windows10.0.19041.0

### Did you find any workaround?

No

**Comment by jfversluis** [comment] 2023-01-27 15:53
There might be a fix for this in the latest WindowsAppSDK version. Could you please try to manually (and explicitly) adding the latest version of the WindowsAppSDK NuGet and see if that fixes it or changes anything?

**Comment by mprattinger** [comment] 2023-01-27 23:01
Thanks for the answer. I was not sure how to update the WindowsAppSDK, because it didn't work via the nuget package manager. I installed the Windows 11 SDK 10.0.22621.0 via Visual Studio Updater. I hope this was the correct way. In csproj i changed the windows target framework to net7.0-windows10.0.22621.0.
But the error remains the same.
I have also updated the repo https://github.com/mprattinger/MauiMultiWindow

r michael

**Comment by symbiogenesis** [comment] 2023-02-03 03:36
I am experiencing this. I tried to force the latest WindowsAppsSDK through a PackageReference, but it doesn't seem to have fixed the problem.

```xaml
  <ItemGroup Condition="$(TargetFramework.Contains('-windows'))">
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.2.230118.102" />
  </ItemGroup>
```

**Comment by symbiogenesis** [comment] 2023-02-03 20:15
I noticed that after updating to the latest Windows Apps runtime and rebooting, the problem isn't happening. Even without that package reference.

**Closed** 2023-02-09 11:02 UTC
Labels: t/bug, platform/windows 🪟, area/desktop 🖥️

**Comment by Enigma205** [comment] 2023-02-23 23:42
same issue but different cause, when the main window or the second window is not active, trying to close it by the close button cause the error "Access violation".
The program '[23152] appName' has exited with code 3221225477 (0xc0000005) 'Access violation'
same error in 2 different apps.
Windows version: 10.0.22621.0 (net7.0)

**Comment by MarkBQE** [comment] 2023-02-27 05:52
Same issue when closing the  second window with an embedded WebView causes the Maui Hybrid app to crash with the following error. Works fine and there is no exception thrown if the WebView is removed
The group or resource is not in the correct state to perform the requested operation. (0x8007139F)
