### ISSUE TITLE
Shell: Navigation within a tab causes an error

### ISSUE THREAD

**Issue by Ernie23** [dotnet/maui#5275] opened 2022-03-14 07:51 UTC
### Description

I have a tabbar with two bottom tabs TabA and TabB. In TabA there are three top tabs (Country, Category, Newspapers) that I want to navigate.

For the reproduction of the error, I have included a button "Country > Category".
Every Time navigation within TabA from Country to Category an exception occured.
![image](https://user-images.githubusercontent.com/5499652/158126959-8a869f5f-5815-4cd6-89c8-b2c3bf08dacd.png)

I have tried to navigate from "Country" to the "Category" page, but every time I get the following error.
**System.ArgumentNullException:** 'Shell Content Page is Null (Parameter 'page')'

Navigating same Uri (described in Steps to Reproduce) from TabB to TabA/Category works fine.
![image](https://user-images.githubusercontent.com/5499652/158126624-01996471-46a8-4c00-8051-8311680db8d2.png)

### Steps to Reproduce

1. Create emptry Maui App
2. Integrate shell - Create AppShell.xaml with following content 
 ```
<Shell xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:local="clr-namespace:Zeitungen"
             x:Class="Zeitungen.AppShell"
             Title="AppShell"
             BackgroundColor="White">

    <TabBar Route="Newspapers">
        <Tab Title="Tab A" Route="Data">
            <ShellContent Title="Country" ContentTemplate="{DataTemplate local:CountryPage}" Route="Country" />
            <ShellContent Title="Category" ContentTemplate="{DataTemplate local:CategoryPage}" Route="Category" />
            <ShellContent Title="Newspapers" ContentTemplate="{DataTemplate local:NewspaperPage}" Route="Newspaper" />
        </Tab>
        <Tab Title="Tab B" Route="Test">
            <ShellContent Title="tab 3" ContentTemplate="{DataTemplate local:CategoryPage}" Route="tab3" />
            <ShellContent Title="tab 4" ContentTemplate="{DataTemplate local:MainPage}" Route="tab4" />
        </Tab>
    </TabBar>
```

</Shell>
3. Insert Button on CountryPage
<Button Text="Country > Category" Clicked="Button_Clicked"></Button>

<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="Zeitungen.CountryPage"
             xmlns:xct="http://schemas.microsoft.com/dotnet/2022/maui/toolkit"
             Title="CountryPage"
             BackgroundColor="White">

    <ContentPage.Content>
        <StackLayout>
            <Button Text="Country > Category" Clicked="Button_Clicked"></Button>
        </StackLayout>
    </ContentPage.Content>
</ContentPage>

4. Register Button-Clicked-Handler with following Code. Shell.Current.GoToAsync(route); throws the exception

``` C#
    private async void Button_Clicked(object sender, EventArgs e)
    {
	var route = $"//Newspapers/Data/Category";
	await Shell.Current.GoToAsync(route);
    }
```  

### Version with bug

Preview 13 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Emulator Pixel 5 - API 30 (Android 11.0)

### Did you find any workaround?

no - no workaround was found

### Relevant log output

```shell
**System.ArgumentNullException:** 'Shell Content Page is Null (Parameter 'page')'

{System.ArgumentNullException: Shell Content Page is Null (Parameter 'page')   at Microsoft.Maui.Controls.Platform.ShellSectionView.UpdateCurrentItem(ShellContent content) in D:\a\_work\1\s\src\Controls\src\Core\Platform\Android\Shell\ShellSectionView.cs:line 75   at Microsoft.Maui.Controls.Platform.ShellSectionView.Google.Android.Material.Tabs.TabLayoutMediator.ITabConfigurationStrategy.OnConfigureTab(Tab tab, Int32 position) in D:\a\_work\1\s\src\Controls\src\Core\Platform\Android\Shell\ShellSectionView.cs:line 44   at Google.Android.Material.Tabs.TabLayoutMediator.ITabConfigurationStrategyInvoker.n_OnConfigureTab_Lcom_google_android_material_tabs_TabLayout_Tab_I(IntPtr jnienv, IntPtr native__this, IntPtr native_p0, Int32 p1) in D:\a\1\s\generated\com.google.android.material.material\obj\Release\net6.0-android\generated\src\Google.Android.Material.Tabs.TabLayoutMediator.cs:line 88}
```

**Comment by Amir-Care** [comment] 2022-03-14 08:20
Thank you so much for your bug report! Unfortunately, we cannot reproduce your issue with the information above, could you provide a sample project  ? That should greatly speed up the process, thanks!

**Comment by PureWeen** [comment] 2022-03-30 14:38
This looks like it's fixed with RC1

**Closed by PureWeen** 2022-03-30 14:38 UTC
Labels: t/bug, area/shell 🐢, high, s/verified
