### ISSUE TITLE
[MAUI]Adding 7 to D10 and continue clicking a few more times, then click ‘-’, the page will get stuck.

### ISSUE THREAD

**Issue by RoiChen001** [dotnet/maui#22478] opened 2024-05-17 07:49 UTC
### Description

Adding 7 to D10 and continue clicking a few more times, then click ‘-’, the page will get stuck.

Note: This problem currently only occurs on the Windows platform.

### Steps to Reproduce

1.Deploy https://devdiv.visualstudio.com/Pkgs/_git/VS.TestAssets.Xaml?path=/Assets/Projects/ManualMauiTests to Windows.
2.Click 'D10'.
3.Click '+' until 7.
4.Continue clicking a few more times.
5.Click '-'.

Actual result:
The page will get stuck.
![aa](https://github.com/dotnet/maui/assets/143168639/cfc1f8c0-5685-4949-9961-eed7ea96beb6)

 Expected result:
Clicking multiple times has no effect, the page won't get stuck.

### Link to public reproduction project repository

https://devdiv.visualstudio.com/Pkgs/_git/VS.TestAssets.Xaml?path=/Assets/Projects/ManualMauiTests

### Version with bug

8.0.60-ci.net8.24267.1

### Is this a regression from previous behavior?

Not a regression. It can be reproduced on 8.0.3 & 8.0.40 & 8.0.40-nightly.10612+sha.752eed7129-azdo.9538080.

### Affected platforms

Windows

**Comment by PureWeen** [comment] 2024-05-17 14:37
Duplicate of #19966

**Closed by PureWeen** 2024-05-17 14:37 UTC
Labels: t/bug, platform/windows 🪟, area-controls-stepper, s/triaged, csi-new

**Comment by RoiChen001** [comment] 2024-05-20 04:58
@PureWeen  I'm a little confused.[ #19966](https://github.com/dotnet/maui/issues/19966l) got stuck because of typing text into the editor, but this bug got stuck because of continuing to click multiple times. I noticed you closed this problem as a duplicate, could you explain it further to help me understand it better? Thanks!

**Comment by PureWeen** [comment] 2024-05-21 21:02
@RoiChen001 the underlying reason for the same page freezing up is most likely the same, so, I just want to make sure that this issue and the other one are referencing each other. It's a little tricky to know if they are 100 percent the same issue, it's more that they both fail in the same way on the same screen. 

Once #19966 is resolved (which it might be on the latest nightly), if this issue still isn't fixed, then we can reopen this one. 

For tracking reasons, if you'd prefer to leave both of these open. We can leave both of these open.

**Comment by RoiChen001** [comment] 2024-05-22 02:17
@PureWeen Thanks for your attention and reply. I will continue to track the fix status of https://github.com/dotnet/maui/issues/19966. If this issue is still not fixed, I will continue to contact you to reopen it.
