### ISSUE TITLE
Splash screen on Samsung S20 Android 12

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#7645] opened 2022-05-31 19:03 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Splash-screen-on-Samsung-S20-Android-12/10056212)._

---
[severity:It bothers me. A fix would be nice]
The splash screen of the maui app I am developing has problems.
The screen is a simple png file (attached). It shows correctly on a Motorola G5 (Android 9) and on a Mi Note 8 (Android 10) but does not show correctly on a Samsung S20 Ultra (Android 12).
On the Samsung the screen is filled with the background color for the splash screen (COLOR="#FFFFFFFF" but no image is displayed.
I have tried changing the background color and the theme, but still no image except the background color.
[splash_logo.png](https://aka.ms/dc/file?name=B8daf3ce5269440c9baa0810d73e57620637893262344807834_splash_logo.png&tid=8daf3ce5269440c9baa0810d73e57620637893262344807834)

---
#### Feedback Bot on 5/29/2022, 05:48 PM: 

(private comment, text removed)
#### JASON Zhao [MSFT] on 5/30/2022, 11:57 PM: 

(private comment, text removed)
#### Paul G Mariotti on 5/31/2022, 01:31 AM: 

(private comment, text removed)
#### JASON Zhao [MSFT] on 5/31/2022, 01:47 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by Symbai** [comment] 2022-06-01 05:55
I can confirm, but this has been reported already #7404 and it also doesn't work on Android 11. I believe it was introduced with a MAUI update as it has worked before on the same device.

**Comment by marcelbeeker** [comment] 2022-07-10 18:01
I have a simple splashscreen containing a backgroundcolor and a png image working on Android 11 (API 30). But in Android 12 with API 31 it doesn't work. It only display the background color. Does anybody know how to fix that?

**Comment by romantitov** [comment] 2022-07-29 14:08
I have the same issue with .svg splash screen Android 12 API 31 and Samsung S10e.

**Comment by zzorba** [comment] 2022-08-25 21:40
This might be an a Samsung vs Google issue -- it seems like the splash screen library android added in Android 12 decided it would be smart to only shows the "icon" if it was launched from the main launcher (i.e. not from a notification or search bar).  That decision makes no sense, but is made even worse that this 'rule' applies to Custom Launcher also (i.e. Samsung).  

Not 100% sure, but there are lots of discussions on the forums, it doesn't sound like Google is implement a workaround but maybe Samsung will: https://issuetracker.google.com/issues/243364421

**Comment by jfversluis** [comment] 2022-08-29 18:02
Looks like this should be fixed in #8394 if not, please open a new issue, thanks!

**Closed by jfversluis** 2022-08-29 18:02 UTC
Labels: area/single project ☝️
