### ISSUE TITLE
Radiobutton Content is not Displayed in Right To Left Flow Direction when ControlTemplate is applied

### ISSUE THREAD

**Issue by hamiddd1980** [dotnet/maui#6939] opened 2022-05-08 15:42 UTC
### Description

When **Radiobutton** visual structure is redefined with a **ControlTemplate** and Page **FlowDirection** is **RightToLeft** , the **Radiobutton** content is not displayed.
Also,the reported issue with  number #6938 exists in this condition.

![RAdioButton-RTL](https://user-images.githubusercontent.com/57061231/167303731-c57e2861-f4d3-4679-bf2c-df2f6fd9f06a.gif)

### Steps to Reproduce

1-Create a New MAUI Project
2-Android Manifest :android:supportsRtl="true"
3-Add new Page **( FlowDirection="RightToLeft")**
4-Code:

```
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             FlowDirection="RightToLeft"
             x:Class="MauiApp29.Page1"
             IconImageSource="edit.png"
             Title="page1"
             BackgroundColor="GreenYellow"
             Padding="16">
    <ContentPage.Resources>
        <ControlTemplate x:Key="RadioButtonTemplate">
            <Frame BorderColor="#F3F2F1"
                   BackgroundColor="#F3F2F1"
                   HasShadow="False"
                   HeightRequest="100"
                   WidthRequest="100"
                   HorizontalOptions="Start"
                   VerticalOptions="Start"
                   Padding="0">
                <VisualStateManager.VisualStateGroups>
                    <VisualStateGroupList>
                        <VisualStateGroup x:Name="CheckedStates">
                            <VisualState x:Name="Checked">
                                <VisualState.Setters>
                                    <Setter Property="BorderColor"
                                            Value="#FF3300" />
                                    <Setter TargetName="check"
                                            Property="Opacity"
                                            Value="1" />
                                </VisualState.Setters>
                            </VisualState>
                            <VisualState x:Name="Unchecked">
                                <VisualState.Setters>
                                    <Setter Property="BackgroundColor"
                                            Value="#F3F2F1" />
                                    <Setter Property="BorderColor"
                                            Value="#F3F2F1" />
                                    <Setter TargetName="check"
                                            Property="Opacity"
                                            Value="0" />
                                </VisualState.Setters>
                            </VisualState>
                        </VisualStateGroup>
                    </VisualStateGroupList>
                </VisualStateManager.VisualStateGroups>
                <Grid Margin="4"
                      WidthRequest="100">
                    <Grid WidthRequest="18"
                          HeightRequest="18"
                          HorizontalOptions="End"
                          VerticalOptions="Start">
                        <Ellipse Stroke="Blue"
                                 Fill="White"
                                 WidthRequest="16"
                                 HeightRequest="16"
                                 HorizontalOptions="Center"
                                 VerticalOptions="Center" />
                        <Ellipse x:Name="check"
                                 Fill="Blue"
                                 WidthRequest="8"
                                 HeightRequest="8"
                                 HorizontalOptions="Center"
                                 VerticalOptions="Center" />
                    </Grid>
                    <ContentPresenter />
                </Grid>
            </Frame>
        </ControlTemplate>

        <Style TargetType="RadioButton">
            <Setter Property="ControlTemplate"
                    Value="{StaticResource RadioButtonTemplate}" />
        </Style>
    </ContentPage.Resources>
    <ContentPage.Content>

        <StackLayout>
            <Label Text="What's your favorite mode of transport?" />
            <RadioButton Content="Car" />
            <RadioButton Content="Bike" />
            <RadioButton Content="Train" />
            <RadioButton Content="Walking" />

            <Button Clicked="Button_Clicked" Text="Change Direction"></Button>
            <Label x:Name="flowDir" BackgroundColor="Red" TextColor="White" FontAttributes="Bold" FontSize="24" HorizontalTextAlignment="Center"></Label>
        </StackLayout>

    </ContentPage.Content>
</ContentPage>
```

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 8-Android 9

**Comment by kristinx0211** [comment] 2022-05-24 02:47
verified repro on android 12 with 17.3.0 Preview 2.0 [32522.62.main].

**Comment by kristinx0211** [comment] 2022-05-24 02:49
verified repro on android 12 with 17.3.0 Preview 2.0 [32522.62.main]. repro project:
[MauiApp6.zip](https://github.com/dotnet/maui/files/8759200/MauiApp6.zip)

**Comment by hartez** [comment] 2023-02-01 22:50
Duplicate of #6708

**Comment by hartez** [comment] 2023-02-02 20:03
Very similar to #6708, and may actually be the same solution.

**Comment by dustin-wojciechowski** [comment] 2023-03-01 18:33
[RTL_RadioButtonControlTemplate.webm](https://user-images.githubusercontent.com/89540402/222231915-80b90e51-9201-4da4-bec2-d40674b44545.webm)

Tested this repro project on latest version of main, looks like it is now fixed.

**Comment by dustin-wojciechowski** [comment] 2023-03-09 21:19
With previous fix done and this PR https://github.com/dotnet/maui/pull/13610, the issue appears to have been resolved.

**Closed by dustin-wojciechowski** 2023-03-09 21:19 UTC
Labels: t/bug, good first issue, platform/android 🤖, area/controls 🎮, s/verified, control-radiobutton
