### ISSUE TITLE
.NET Maui RC1 On Click counter not show Android

### ISSUE THREAD

**Issue by eramrit78** [dotnet/maui#6073] opened 2022-04-13 16:17 UTC
### Description

I have clean installed vs 2022 17.2 Prev. 3 and create a new project with .NET MAUI APP. on windows system. It work fine on windows app when click on Click me button and show counter in Current count Label. But on andoid when click on Click me button it does not show current count on screen. but counter inrement (when debug Clicked Event) . I dont know this is a bug and any wrokground to run a fresh project.

Thanks

### Steps to Reproduce

1. Create a new fresh Project .NET MAUI APP
2. Run with android simulator API Level 30 Google Pixel 5
3. Click on Clikc me button
4. It must show current count on screen but it failed to show current count on screen. android device.

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

NA

### Affected platforms

Android

### Affected platform versions

Android 11, 12

### Did you find any workaround?

No

### Relevant log output

```shell
No
```

**Comment by PureWeen** [comment] 2022-04-13 18:04
Duplicate of https://github.com/dotnet/maui/issues/5717

**Closed by PureWeen** 2022-04-13 18:04 UTC
Labels: t/bug, platform/android 🤖, area/controls 🎮, s/needs-verification
