### ISSUE TITLE
[BUG] FontImageSource will not use Color of Parent Button

### ISSUE THREAD

**Issue by glatzert** [dotnet/maui#8826] opened 2022-07-19 06:42 UTC
### Description

Using a FontImageSource inside a button, the color won't bind to the parent button.
```xaml
<Button Text="{x:Static res:LR.LoginButtonText}" Command="{Binding LoginCommand}">
  <Button.ImageSource>
    <FontImageSource FontFamily="LineAwesome-Solid" Glyph="{x:Static res:LA_Solid.AlternateSignIn}" />
  </Button.ImageSource>
</Button>
```

Using the default MAUI-Template with `Styles.xaml` and `Colors.xaml`, so the background of the button is white and the text is of primary color, the FontImageSource, will not use the defined color

```xaml
    <Style TargetType="Button">
        <Setter Property="TextColor" Value="{AppThemeBinding Light={StaticResource White}, Dark={StaticResource Primary}}" />
        <Setter Property="BackgroundColor" Value="{AppThemeBinding Light={StaticResource Primary}, Dark={StaticResource White}}" />
<!-- more rules -->
</Style>
```

Instead it will show up white until the color is defined directly.

### Steps to Reproduce

1. Create a MAUI App from the default template,
2. Add a icon font
3. Add a button as described above
4. Try to find icon.

### Version with bug

6.0.408 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

### Did you find any workaround?

Defining the color directly `Color="#FF0000"` will work.

**Comment by jvakos** [comment] 2022-07-23 07:01
Here is a repo. 
https://github.com/jvakos/FontmageSourceBug8826

**Comment by KieranMaclagan** [comment] 2022-11-09 19:47
Still seeing this behaviour today. I came across it on iOS with Tabs. Android works great in that the icon changes colour with the text on the selected/unselected item. iOS only the text changes colour and the icon is just white.

**Comment by homeyf** [comment] 2023-08-01 03:09
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 5.0. Can repro on android platform with sample code.
https://github.com/jvakos/FontmageSourceBug8826
![image](https://github.com/dotnet/maui/assets/82450723/39cae6af-464a-4ba7-90fe-7ca04dc5c52f)

**Comment by MV10** [comment] 2023-08-19 15:31
It's a problem targeting Windows as well.

**Comment by mattleibow** [comment] 2023-11-30 10:44
I don't think the `TextColor` propagates to the Image component of the button. Even though the `FontImageSource` _looks_ like text, it is just an image source that is not part of any text formatting.

For that you can set the `Color` property of the `FontImageSource`. You could also use control binding:

```cs
<Button Text="Hello World!" TextColor="Red">
    <Button.ImageSource>
    <FontImageSource FontFamily="OpenSansSemibold" Glyph="A"
                        Color="{Binding TextColor, Source={RelativeSource AncestorType={x:Type Element}}}" />
    </Button.ImageSource>
</Button>
```

**Comment by MV10** [comment] 2023-11-30 11:26
> I don't think the TextColor propagates to the Image component

> This issue will be closed automatically in 7 days if we do not hear back from you by then

What "additional info" could the author possibly provide in response to what appears to be an _opinion_ from MS? You know, to prevent closure of another legitimate issue? These bots are terrible.

But ... since the default image color changes on light / dark themes to match the text color, it sure _looks like_ a bug to the people actually trying to use MAUI.

Perhaps some kind of inherit-style property could be added which is true by default?

**Comment by glatzert** [comment] 2023-11-30 12:19
> You could also use control binding
Or that bug could be fixed, to meet expectations, that a FONT thingy will have the FONT color by default.

On a personal note: we don't care anymore - we lost trust in MAUI and moved on.

**Comment by mattleibow** [comment] 2023-11-30 16:03
The `needs-info` label and comment is just the bot doing things. Basically, marks the issue as we need more opinions and comments. And a comment will trigger more things to notify us.

**Comment by mattleibow** [comment] 2023-11-30 19:09
Closing this now as it is working as designed.

**Closed by mattleibow** 2023-11-30 19:09 UTC
Labels: t/bug, platform/android 🤖, area/fonts 🅰️, s/verified, s/triaged, s/needs-attention
