### ISSUE TITLE
Entry does not lose focus and keyboard does not hide 

### ISSUE THREAD

**Issue by HobDev** [dotnet/maui#4781] opened 2022-02-18 16:18 UTC
### Description

On Android:
The Entry does not loose focus and keyboard does not close if I click on some other control or if I set entry.Unfocus().  It also does not loose focus and keyboard does not close if I click on return.

On iOS:
The Entry does not loose focus and keyboard does not close if I click on some other control or if I set entry.Unfocus().  But it does  loose focus and keyboard closes if I click on return.

[BugSample.zip](https://github.com/dotnet/maui/files/8098674/BugSample.zip)

### Steps to Reproduce

Run the repro project and set focus on Entry by clicking on it. This will open the keyboard. Now try to close the keyboard by clicking on button or clicking  on return key.

### Version with bug

Preview 13 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

iOS 15.2 and Android 11

### Did you find any workaround?

Whenever I need to remove focus from Entry I just call these two methods.

entry.IsEnabled=false; // This removes the focus and close the keyboard
entry.IsEnabled=true; // This re-enabled the Entry for interaction

**Comment by danielftz** [comment] 2022-02-18 19:01
I believe Focus is coming in preview14
https://github.com/dotnet/maui/issues/3380

**Comment by HobDev** [comment] 2022-02-19 04:33
But the logic is partially implemeted in iOS as return key dismisses the keyboard on iOS.

**Comment by PineYi** [comment] 2022-02-25 05:42
Duplicate of #3380

**Comment by PineYi** [comment] 2022-02-25 05:53
close #4781

**Comment by PineYi** [comment] 2022-02-25 05:55
`close` #4781

**Comment by HobDev** [comment] 2022-02-25 06:09
@PineYi  @wenwen60  This issue have few differences than the #3380. First this issue also include iOS. Second this issue also includes the return key.

**Comment by PineYi** [comment] 2022-03-01 03:14
Reproduce in Android with above project.

**Comment by Redth** [comment] 2022-03-22 20:30
Will be fixed in #4914

**Closed** 2022-03-23 19:02 UTC
Labels: t/bug, area/controls 🎮, s/verified, control-entry
