### ISSUE TITLE
.NET MAUI Button stays gray after enabling on start on Android Emulator in Release configuration

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#12072] opened 2022-12-13 23:34 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/NET-MAUI-Button-stays-gray-after-enabli/10226962)._

---
[severity:I'm unable to use this version]
.NET MAUI Button does not get back to "enabled" appearance after setting IsEnabled = true on start on Android Emulator for Release configuration

Steps to reproduce:

1. Create new .NET MAUI C# project called "EnableButtons"

2. Replace MainPage.xaml and MainPage.xaml.cs with the attached

3. Run in Release on Android Emulator

4. Note how all buttons are grey but enabled

P. S. in Debug configuration is works as expected

[MainPage.xaml](https://aka.ms/dc/file?name=B2ca2bf4bc7df409792b89d6b5c657b65638062710628030246_MainPage.xaml&tid=2ca2bf4bc7df409792b89d6b5c657b65638062710628030246)
[MainPage.xaml.cs](https://aka.ms/dc/file?name=B4271d4b3c9f04effb1cac61a8d714897638062710708080082_MainPage.xaml.cs&tid=4271d4b3c9f04effb1cac61a8d714897638062710708080082)

---
#### Feedback Bot on 12/11/2022, 06:26 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by jvakos** [comment] 2022-12-14 13:48
possible duplicate of https://github.com/dotnet/maui/issues/10181

**Comment by jsuarezruiz** [comment] 2022-12-14 19:24
Looks like the same or similar to https://github.com/dotnet/maui/issues/10181

**Comment by jfversluis** [comment] 2024-04-08 09:17
This is old by now and possibly a duplicate. The possible duplicate has been closed so this might already be fixed. I'm closing this one, if you still experience this, please open a new issue with the updated details.

**Closed by jfversluis** 2024-04-08 09:17 UTC
Labels: t/bug, s/duplicate 2️⃣, platform/android 🤖, area/controls 🎮, control-button, s/triaged
