### ISSUE TITLE
HasBackButton not removing back button

### ISSUE THREAD

**Issue by itsliamprowse** [dotnet/maui#7604] opened 2022-05-30 11:55 UTC
### Description

![image](https://user-images.githubusercontent.com/6665840/170986104-9e5632da-c10e-4683-8462-0515f50ec93c.png)
I have added the "NavigationPage.HasBackButton" property to the xaml and set it to false, however the back button still shows up. It happens on Windows and Android (all I am able to test).

I have also tried NavigationPage.SetHasBackButton(this, false); and it did not work either.

### Steps to Reproduce

Create a content page, 
Set NavigationPage.HasBackButton="False" in the xaml
Navigate to the page using App.Current.MainPage.Navigation.PushAsync()
The back button will be there

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows

### Affected platform versions

Android 11

### Did you find any workaround?

N/A

**Comment by tekmun** [comment] 2022-05-30 18:48
You need to remove AppShell routing navigation.
In App.xaml.cs, use this: MainPage = new NavigationPage(new MainPage());

**Comment by VincentBu** [comment] 2022-05-31 07:51
repro with vs main build 32530.96.main

**Comment by veikkoeeva** [comment] 2023-02-04 21:23
Indeed, this would be useful for a login case where one wants to show a login screen but make it so it's not possible to navigate back to it from the main screen/shell once logged in (and probably also neither using the physical button from somewhere else).

**Comment by homeyf** [comment] 2023-09-01 07:49
Verified this issue with Visual Studio Enterprise 17.8.0 Preview 1.0. Can repro on android platform with sample code.
![image](https://github.com/dotnet/maui/assets/82450723/3d1bf0ec-f9f9-4739-83f6-364f8f09483d)

**Comment by konradzuse** [comment] 2024-01-26 14:43
I have updated my Maui workloads to the latest 8.0.3 but this issue still remains..

Installed Workload Id      Manifest Version       Installation Source
---------------------------------------------------------------------
maui                       8.0.3/8.0.100          SDK 8.0.100
android                    34.0.52/8.0.100        VS 17.8.34511.84
maccatalyst                17.2.8004/8.0.100      VS 17.8.34511.84
ios                        17.2.8004/8.0.100      VS 17.8.34511.84
maui-windows               8.0.3/8.0.100          VS 17.8.34511.84

Are there any workarounds for Android/iOS?

**Comment by ToastinYou** [comment] 2024-01-29 15:43
If you are utilizing Shell you can do something like this in your code-behind (Page.xaml.cs):
```csharp
Shell.SetBackButtonBehavior(this, new BackButtonBehavior
{
    IsVisible = false
});
```

**Comment by konradzuse** [comment] 2024-01-29 16:38
we're using FreshMVVM so Shell isn't an option

**Comment by markusroessler** [comment] 2024-04-15 14:30
Works for me on Android using MAUI 8.0.20

**Comment by konradzuse** [comment] 2024-04-21 22:07
Seems to work intermittently on 8.0.20

Maybe 1 in 5 times the page is displayed, the back button is wrongly shown

**Comment by markusroessler** [comment] 2024-04-21 22:16
@konradzuse I had the same issue, because I was pushing multiple pages using PushAsync without awaiting the returned Task. The problem was resolved after I changed the code to await each Task. Maybe it's the same problem in your case?

**Comment by konradzuse** [comment] 2024-04-22 12:03
no, the page is displayed using an AsyncCommand connected to a button. The PushAsync is awaited.

**Comment by karthikraja-arumugam** [comment] 2024-09-30 08:31
It looks the issue is resolved with Net8.
![backbutton](https://github.com/user-attachments/assets/6f1313f1-1ab8-4600-ba21-301c361bf1f3)

![backbuttonfalse](https://github.com/user-attachments/assets/d01cab8e-0f14-4625-b049-6cece1fd295d)

**Closed** 2024-10-07 09:35 UTC
Labels: t/bug, platform/windows 🪟, platform/android 🤖, area-navigation, s/verified, s/triaged, s/try-latest-version
