### ISSUE TITLE
[Bug] StackLayout Horizontal is blank

### ISSUE THREAD

**Issue by davidortinau** [dotnet/maui#1921] opened 2021-08-03 14:17 UTC
### Description

```
using System;
using Microsoft.Maui;
using Microsoft.Maui.Controls;
using Microsoft.Maui.Graphics;

namespace LayoutLab
{	public class HorizontalStackPage : ContentPage
	{
		public HorizontalStackPage()
		{
			this.Content = new ScrollView()
            {
                Content = new StackLayout
                {
                    Margin = new Thickness(20),
                    Orientation = StackOrientation.Horizontal,
                    Children =
                    {
                        new BoxView { Color = Colors.Red },
                        new BoxView { Color = Colors.Yellow },
                        new BoxView { Color = Colors.Blue },
                        new BoxView { Color = Colors.Green },
                        new BoxView { Color = Colors.Orange },
                        new BoxView { Color = Colors.Purple }
                    }
                }
            };
		}
	}
}
```

### Expected Behavior

![Screen Shot 2021-04-15 at 1 30](https://user-images.githubusercontent.com/41873/128030929-13624d7f-d06f-4446-ba45-e96982390166.png)

### Actual Behavior

![Screen Shot 2021-08-03 at 9 08 18 AM](https://user-images.githubusercontent.com/41873/128030984-a9d7f249-a425-4538-b148-581ad3d1a6ea.png)

### Basic Information

- Version with issue: pre7

### Reproduction Link

https://github.com/davidortinau/ControlGallery/blob/main/src/ControlGallery/Pages/Stack/HorizontalStackPage.cs

**Comment by hartez** [comment] 2021-08-03 16:42
Duplicate of #1922, fixed by #1923.

**Closed by hartez** 2021-08-03 16:42 UTC
