### ISSUE TITLE
Can't publish BlazorWinFormsApp or BlazorWpfApp BlazorWebView samples with ClickOnce

### ISSUE THREAD

**Issue by Jinjinov** [dotnet/maui#8967] opened 2022-07-24 20:55 UTC
### Description

When trying to publish a BlazorWebView app with ClickOnce it fails with:

        Manifest file at 'obj\Release\net6.0-windows\staticwebassets.build.json' not found.
        ========== Build: 2 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
        ========== Publish: 0 succeeded, 1 failed, 0 skipped ==========

### Steps to Reproduce

1. a) try to publish https://github.com/dotnet/maui/tree/main/src/BlazorWebView/samples/BlazorWinFormsApp with ClickOnce
1. b) try to publish https://github.com/dotnet/maui/tree/main/src/BlazorWebView/samples/BlazorWpfApp with ClickOnce
2. see error:

        Manifest file at 'obj\Release\net6.0-windows\staticwebassets.build.json' not found.
        ========== Build: 2 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
        ========== Publish: 0 succeeded, 1 failed, 0 skipped ==========

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows SDK 10.1.19041.685

**Comment by javiercn** [comment] 2022-07-25 15:57
@Jinjinov thanks for contacting us.

There is a lot going on with the code in our repo, we would recommend you try with an app from the template, as we need to do all sorts of adjustments to the MSBuild inside the repo and we likely didn't do anything for publish.

**Comment by Jinjinov** [comment] 2022-07-25 17:59
@javiercn I have tried it with two different projects:

first: https://github.com/Jinjinov/TheLastTime

second: https://github.com/Jinjinov/Ididit

I also made a solution from your samples: https://github.com/Jinjinov/BlazorWebViewApp

**Comment by javiercn** [comment] 2022-07-26 12:27
@Jinjinov is the failing project the class library one?

**Comment by Jinjinov** [comment] 2022-07-26 12:31
@javiercn no, I have to intentions to publish a class library with ClickOnce.

The projects that fail to publish with ClickOnce are either WPF or WinForms.

They work without problems when running them from Visual Studio in either debug or release mode.

**Comment by TanayParikh** [comment] 2022-07-26 19:08
@Jinjinov can you please update the `TargetFramework` here:

https://github.com/Jinjinov/BlazorWebViewApp/blob/d7c066e67fc30f21ede538334e188e385a2627d0/WebViewAppShared/WebViewAppShared.csproj#L4

to be `net6.0-windows`. Does that resolve the issue for you?

**Comment by Jinjinov** [comment] 2022-07-26 19:22
@TanayParikh yes, that resolves the issue in the minimal example project, thank you.

But, in my real project, the razor class library is also shared with a MAUI project that targets Android.

How can I solve this problem in my real project?

**Comment by TanayParikh** [comment] 2022-07-26 20:28
Thanks for confirming @Jinjinov! 

This is a known issue. For now, you'll have to manually change the razor class library's (RCL) Target Framework (TFM) manually depending on if you're trying to publish on WinForms/WPF or Android. There _may_ be some variables you can declare in the WPF/WinForms CSProj, and then you may be able to use a `Condition` statement in the RCL to set the TFM. However, we don't have any official guidance on this. 

We're working with the appropriate teams to get this resolved so the single `net6.0` TFM is sufficient regardless of the deployment target. This'll be coming in an upcoming release (TBD).

**Comment by TanayParikh** [comment] 2022-07-26 20:30
Closing out as a duplicate of (internal) issue: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1539200

**Closed by TanayParikh** 2022-07-26 20:30 UTC
Labels: s/duplicate 2️⃣, area/blazor 🕸️, investigate

**Comment by TanayParikh** [comment] 2022-07-27 16:31
@Jinjinov can you please try updating the target framework to 

`net6.0;net6.0-windows`

here: https://github.com/Jinjinov/BlazorWebViewApp/blob/d7c066e67fc30f21ede538334e188e385a2627d0/WebViewAppShared/WebViewAppShared.csproj#L4

Does that work for you across WPF/WinForms/Android?

**Comment by Jinjinov** [comment] 2022-07-27 18:57
@TanayParikh yes, it works for Wpf and WinForms.

I am still working on the Android version - first I wrote the app for WASM, then I tried to make it work for Wpf / WinForms.

I will test it on Android when it is ready.

**Comment by TanayParikh** [comment] 2022-08-01 23:49
> please try updating the target framework to
> 
> `net6.0;net6.0-windows`

@guardrex, can we please document this workaround somewhere (not sure what location would be appropriate). Essentially, currently to publish a WPF/WinForms project with an RCL, the RCL must have the TFM set to `net6.0;net6.0-windows` instead of the default `net6.0`.

**Comment by guardrex** [comment] 2022-08-01 23:57
It will be for the upcoming Blazor Hybrid RCL topic in review now ...

https://github.com/dotnet/AspNetCore.Docs/pull/26331

I'll add it Tuesday morning.

**Comment by guardrex** [comment] 2022-08-02 09:38
@TanayParikh ... You can review this here without looking at the PR. I added the following immediately after the opening remarks. Does it require updates? ...

> :::moniker range="= aspnetcore-6.0"
>
> \#\# Target framework
>
> To publish a WPF or Windows Forms project with a Razor class library (RCL) in ASP.NET Core 6.0, the RCL must have the \[Target Framework Moniker (TFM)](/dotnet/standard/frameworks) set to \`net6.0;net6.0-windows\`.
>
> In the RCL's project file:
>
> \`\`\`diff
> \- \<TargetFramework>net6.0\</TargetFramework>
> \+ \<TargetFrameworks>net6.0;net6.0-windows\</TargetFrameworks>
> \`\`\`
>
> :::moniker-end

**Comment by TanayParikh** [comment] 2022-08-02 15:54
Looks good to me, thanks @guardrex!
