### ISSUE TITLE
MAUI Blazor: System.IO.FileNotFoundException: '' on InitializeComponent()

### ISSUE THREAD

**Issue by TonyHenrique** [dotnet/maui#14111] opened 2023-03-21 23:00 UTC
### Description

My Maui Blazor App on InitializeComponent() is throwing System.IO.FileNotFoundException: '' on 
Visual Studio, even if I uncheck "Break when this exception type is thrown"

![image](https://user-images.githubusercontent.com/6307623/226759112-2d6bb7f6-6a4f-4b3e-954e-c64f8640826a.png)

```
dotnet workload list

ID da carga de trabalho instalada      Versão do Manifesto      Origem da Instalação
------------------------------------------------------------------------------------
wasm-tools-net6                        7.0.3/7.0.100            VS 17.6.33513.286
maccatalyst                            16.2.1030/7.0.100        VS 17.6.33513.286
ios                                    16.2.1030/7.0.100        VS 17.6.33513.286
wasm-tools                             7.0.3/7.0.100            VS 17.6.33513.286
maui-android                           7.0.59/7.0.100           VS 17.6.33513.286
maui-windows                           7.0.59/7.0.100           VS 17.6.33513.286
maui-maccatalyst                       7.0.59/7.0.100           VS 17.6.33513.286
android                                33.0.26/7.0.100          VS 17.6.33513.286
maui-ios                               7.0.59/7.0.100           VS 17.6.33513.286

Use `dotnet workload search` para encontrar cargas de trabalho adicionais a serem instaladas.

```

### Steps to Reproduce

Open the project in repository, run Debugging on Android device.

### Link to public reproduction project repository

https://github.com/TonyHenrique/bug-2023-03-21

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 11.0 - API 30

### Did you find any workaround?

No, because even if I uncheck "Break when this exception type is thrown" Visual Studio still stops at that line and I have to click the Continue button a few times.

**Comment by Eilon** [comment] 2023-04-03 22:20
Hi @TonyHenrique I cloned your app and ran it and did not see any exceptions at all. I ran the `MauiBlazorApp1` project in the Android Emulator and it worked fine:

<img width="721" alt="image" src="https://user-images.githubusercontent.com/202643/229639676-ae94fb81-0d2a-4037-b029-aa160177ba57.png">

If you're still seeing the exception, can you click "Show Call Stack" so that we can see more details about the exception you're seeing?

**Comment by TonyHenrique** [comment] 2023-04-03 22:49
This only happens when I Run (Debug) on the physical Android device:
System.IO.FileNotFoundException

This is what appears when I click Show Call Stack:

```
 	[External Code]	
 	0xC in MauiBlazorApp1.App.InitializeComponent at C:\Users\tonyv\source\repos\MauiBlazorApp1\MauiBlazorApp1\Microsoft.Maui.Controls.SourceGen\Microsoft.Maui.Controls.SourceGen.CodeBehindGenerator\App.xaml.sg.cs:22,4	C#
>	0x9 in MauiBlazorApp1.App..ctor at C:\Users\tonyv\source\repos\MauiBlazorApp1\MauiBlazorApp1\App.xaml.cs:7,13	C#
```

![image](https://user-images.githubusercontent.com/6307623/229640996-2850014e-c644-4218-9a87-9f3b28ee31fc.png)

Can you please try this on an Android phone?
If I run the App on the emulator (Nexus 5X - API 31), the error does not occur. 

![image](https://user-images.githubusercontent.com/6307623/229642656-cd3f6f19-ee15-4206-be86-05a276055f1f.png)

**Comment by Eilon** [comment] 2023-04-03 23:10
Very interesting, thank you for posting that. I don't see anything Blazor-related in the call stack at all. The call stack seems to indicate that something to do with XAML can't be loaded.

Are you seeing any issues like this with a non-Blazor MAUI app? Does a regular File / New Project / MAUI App have the same issue for you on a physical device?

**Comment by TonyHenrique** [comment] 2023-04-03 23:46
OK, right now, I have just created two new projects: 
A MAUI
and a MAUI Blazor
and Run, none of them give error on the Physical Android device.

Perhaps there is some combination of factors that happens on the repro that causes that error only on the physical device.

**Can you try to run the repro on an physical Android device?**

https://github.com/TonyHenrique/bug-2023-03-21

**Comment by Eilon** [comment] 2023-04-04 00:07
I don't have a physical Android device but I'm paging Mr. @jonathanpeppers to see if perhaps this is familiar.

@jonathanpeppers - does anything in [this call stack](https://github.com/dotnet/maui/issues/14111#issuecomment-1495085590) look like any known issue with XAML on a physical Android device? (Doesn't repro on emulator, and a trivial app does not repro anywhere.)

Full repro app here: https://github.com/TonyHenrique/bug-2023-03-21

**Comment by TonyHenrique** [comment] 2023-04-08 12:49
Today I run again and could see more details:
The exception is being raised on XamlLoader.cs
>	0xF9 in Microsoft.Maui.Controls.Xaml.XamlLoader.Load at C:\Users\tonyv\AppData\Local\SourceServer\b8d82a6a238382fded816d4ccb149e6e6cf6abd54f11376301554fd139ac2d82\XamlLoader.cs:61,5	C#


![image](https://user-images.githubusercontent.com/6307623/230721949-e8d387f4-b9c6-4cc5-9b93-f6ee836ea090.png)

the xaml string variable is:

```
<?xml version="1.0" encoding="UTF-8" ?>
<Application xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:local="clr-namespace:MauiBlazorApp1"
             x:Class="MauiBlazorApp1.App">

</Application>
```
and the exception happens here:

```
		public static void Load(object view, string xaml, Assembly rootAssembly, bool useDesignProperties)
		{
			using (var textReader = new StringReader(xaml))
			using (var reader = XmlReader.Create(textReader))
			{
				while (reader.Read()) // <- exception 

```

**Comment by Eilon** [comment] 2023-04-10 16:07
@TonyHenrique is there any hint in the exception details about what file it's looking for? Does the debugger show any details in the Watch window about the exception's properties, which might also include the file name?

**Comment by jonathanpeppers** [comment] 2023-04-10 16:27
If it happens on this line:
```csharp
		public static void Load(object view, string xaml, Assembly rootAssembly, bool useDesignProperties)
		{
			using (var textReader = new StringReader(xaml))
			using (var reader = XmlReader.Create(textReader))
			{
				while (reader.Read()) // <- exception 
```
What are the contents of `string xaml`?

**Comment by TonyHenrique** [comment] 2023-04-10 16:37
Yes, the xaml is just that string containing that empty Application XAML
@jonathanpeppers can you run that Repro in an Android device and see if the exception happens?
One curious fact is that the exception only happens when I deploy to my Android phone (HMD Global Nokia 5.3 (Android 12.0 - API 31) )   
When I deploy to the Emulator it runs with no exception.

**Comment by jonathanpeppers** [comment] 2023-04-10 17:07
So I think the issue is related to satellite assemblies:
```
0x26 in System.Reflection.Assembly.Load
0x55 in System.Reflection.RuntimeAssembly.InternalGetSatelliteAssembly
0x4 in System.Resources.ManifestBasedResourceGroveler.InternalGetSatelliteAssembly
0x4D in System.Resources.ManifestBasedResourceGroveler.GetSatelliteAssembly
0x31 in System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet
0xA4 in System.Resources.ResourceManager.InternalGetResourceSet
0x5A in System.Resources.ResourceManager.GetString
0x12B in System.SR.InternalGetResourceString
0xC in System.SR.GetResourceString
0x11 in System.Text.EncodingTable.GetDisplayName
0x30 in System.Text.EncodingTable.InternalGetCodePageDataItem
0xB9 in System.Text.EncodingTable.GetCodePageDataItem
0xF in System.Text.Encoding.GetDataItem
0x9 in System.Text.Encoding.get_WebName
0x1 in System.Xml.XmlTextReaderImpl.SwitchEncoding
0x235 in System.Xml.XmlTextReaderImpl.ParseXmlDeclaration
0xC8 in System.Xml.XmlTextReaderImpl.Read
```
In this case, the `XmlReader` just happens to hit the same problem as: https://github.com/dotnet/maui/issues/7443

Let me close this as duplicate, I'll link to your example.

**Comment by jonathanpeppers** [comment] 2023-04-10 17:08
Duplicate of #7443

**Closed by jonathanpeppers** 2023-04-10 17:08 UTC
Labels: t/bug, area/blazor 🕸️, s/needs-attention
