### ISSUE TITLE
Pairing to Mac not working in Visual Studio 2022 1.17.3 Preview 2

### ISSUE THREAD

**Issue by yairp03** [dotnet/maui#8026] opened 2022-06-14 20:03 UTC
### Description

Until I updated Visual Studio I successfully connected my PC to my MacBook and debugged using the iOS Simulator, but since I updated Visual Studio 2022 1.17.3 from Preview 1.1 to Preview 2 I can't connect to the Mac.

### Steps to Reproduce

1. Create a File > New .NET Maui application.
2. Try to pair a mac.
3. Observe the error.

### Version with bug

6.0 (current)

### Last version that worked well

Release Candidate 3 (current)

### Affected platforms

iOS

### Affected platform versions

iOS

### Relevant log output

```shell
Error
Could not install workload 'ios'. Details: Workload installation failed: Access to the path '/var/folders/91/dkt5d6vj02l3h3y7xw9jxm6w0000gp/T/dotnet-sdk-advertising-temp/microsoft.ios.sdk/15.4.414' is denied.
```

**Comment by drasticactions** [comment] 2022-06-15 00:47
This is IDE tooling that can't be fixed in this repo, nor by this team. If possible, could you file that issue to VS Feedback (https://developercommunity.visualstudio.com/home)?

For trying to fix it, since there could be a lock on that folder caused by either DotNet or the Xamarin Mac Agent, you can try and delete it or restart your computer and try connecting again. It can't update the iOS workloads, so it can't build and deploy the app.

**Closed by drasticactions** 2022-06-15 00:47 UTC
Labels: t/bug, area/tooling ⚙️, s/needs-verification

**Comment by yairp03** [comment] 2022-06-15 09:07
Found the solution, I just needed to **restart my MacBook**.

Source: https://developercommunity.visualstudio.com/t/Pair-to-Mac-fails-with-Could-not-instal/10056196?space=8&ftype=problem&preview2=true&q=could+not+install+workload+ios
