### ISSUE TITLE
iOS CollectionView items overlap when their content is resized

### ISSUE THREAD

**Issue by claytonone** [dotnet/maui#21337] opened 2024-03-20 15:45 UTC
### Description

If the size of an iOS CollectionView item increases then it will overlap the item below it. This issue does not occur on Android.

![Simulator Screenshot - iPhone SE (3rd generation) - 2024-03-20 at 15 29 55](https://github.com/dotnet/maui/assets/25326306/a570abaf-1a18-4bdf-b61e-c5ea4ebaf295)

### Steps to Reproduce

1) Add a CollectionView with a DataTemplate
2) Increase the size of any item in the list
3) See that the it overlaps the item below it

### Link to public reproduction project repository

https://github.com/claytonone/MauiCollectionViewResizeBug/tree/main/iOSCollectionViewBug

### Version with bug

8.0.10 SR3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Did you find any workaround?

No

**Comment by Redth** [comment] 2024-03-20 19:24
Seems like when a control causes the layout (I tested both with the VerticalStackLayout as well as a Grid wrapping the Label in the item template) to grow, the layout isn't notifying the platform view or the cell to be resized.

If you remove the layout from the item template and just have the Label:

```xml
<DataTemplate x:DataType="local:Item">
  <Label Text="{Binding Content}" FontSize="16" Padding="10" TextColor="Grey" />
</DataTemplate>
```

Then the content seems to adjust properly.

**Comment by Redth** [comment] 2024-03-20 19:30
Duplicate of #21141

**Closed by Redth** 2024-03-20 19:30 UTC
Labels: t/bug, platform/iOS 🍎, area/collectionview 📃
