### ISSUE TITLE
[regression/8.0.3] MauiImage Build action not working properly

### ISSUE THREAD

**Issue by Wandtket** [dotnet/maui#18765] opened 2023-11-15 17:44 UTC
### Description

Embedded Images such as pngs and svgs are not being shown in images source.

![image](https://github.com/dotnet/maui/assets/13137508/f9d732db-4191-47be-83ff-d5cde69c86e2)

### Steps to Reproduce

1. Create a new MAUI app using .Net 8
2. Launch app using Android Emulator
3.  Default dotnet_bot.png file does not load in main project.

### Version with bug

Unknown/Other

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 8.0 and up

### Did you find any workaround?

No

**Comment by PureWeen** [comment] 2023-11-15 18:37
@Wandtket I tested this locally and for me it's showing up without any issues

Can you generate a binlog?

https://github.com/xamarin/xamarin-macios/wiki/Diagnosis

**Comment by Wandtket** [comment] 2023-11-15 18:46
> @Wandtket I tested this locally and for me it's showing up without any issues
> 
> Can you generate a binlog?
> 
> https://github.com/xamarin/xamarin-macios/wiki/Diagnosis

As Requested: 
[msbuild.zip](https://github.com/dotnet/maui/files/13368491/msbuild.zip)

**Comment by Stedy59** [comment] 2023-11-15 21:05
On first build after clean... If you rebuild again, it will show.

**Comment by Wandtket** [comment] 2023-11-15 21:38
> Remove app from device OS. On first build after removing .vs, bin, and obj folders, it fails to add resources. If you rebuild again, it will show.

Issue still persists.. even when creating a new project.

**Comment by Hrishikesh46779** [comment] 2023-12-17 17:39
Same issue for me. All the svgs on my project are displayed as blank.

**Comment by m1dst** [comment] 2024-02-12 12:41
I found this too with 8.0.6.  Build just breaks and then things like app icons don't compile and embedded images are not visible either.  Rolled to 8.0.3 and compiled and magically everything works again.  I tried all the usual tricks first, deleting .vs, obj and bin and nothing fixed it.   I haven't been able to nail down the problem here but I've spent 3 days testing things to suddenly end up at the same point again, a broken build if I am using appicon or no images if I delete it from the manifest.

**Comment by ninachen03** [comment] 2024-03-08 06:26
Verified this issue with Visual Studio 17.10.0 Preview 1, not repro on .NET 8 Android platform.

**Comment by Wandtket** [comment] 2024-03-08 15:04
I want to add that MAUI .net 8 and Visual Studio 17.9.2 have resolved this issue at least for me.

@ninachen03 try the non preview version, that might not have the particular fix for MAUI.

**Comment by ninachen03** [comment] 2024-03-11 08:07
@Wandtket If you still have this problem in a specific version, please share it with us. If not, could you close this issue?

**Comment by jfversluis** [comment] 2024-03-11 10:33
@Hrishikesh46779 @m1dst I want to make really sure that this is not an issue anymore. Could you update to the latest version of .NET MAUI which is [8.0.7](https://github.com/dotnet/maui/releases/tag/8.0.7), you can install it through updating just the NuGet package on your .NET MAUI project and let me know if the issue persists?

If it does, could you please also provide a reproduction project? Even if it's just a File > New MAUI project, that would already be helpful.

Thanks!

**Comment by m1dst** [comment] 2024-03-11 12:27
@jfversluis I confirm with 8.0.7 and VS17.10.0 Preview 1.0, it works for me.  Thanks for the quick turnaround.

**Comment by jfversluis** [comment] 2024-03-11 12:35
OK 2 people confirm this as fixed so I'm going to assume that's the case. If there is still someone finding this and it's not fixed in your case, please feel free to let me know!

Thanks everyone!

**Closed by jfversluis** 2024-03-11 12:35 UTC
Labels: t/bug, area/single project ☝️, platform/android 🤖, s/needs-info, s/triaged, s/try-latest-version, potential-regression
