### ISSUE TITLE
Border has an almost animated resizing effect when first loaded. (IOS) 

### ISSUE THREAD

**Issue by Bnjbel97** [dotnet/maui#21103] opened 2024-03-08 15:52 UTC
### Description

The first time a Border is visible. You can visually see the Border resizing based on parent grid.  This effect almost appears as a choppy animation. Maybe 3-5 resizes before displaying properly. After first time shown, this does not appear to happen again.  The issue appears to be IOS(17+) only.  Below are three code chunks. One is the Content Page, one is Content View which is container for the content view in question, one is the Content View which has the Border in question.  This experience happens on other similar content views contained within the CenterMenus ContentView below. Removing the Border, this issue no longer happens.  Only the Border -> Grid element appear to resize. Other Controls within the Grid seem fine.  There is no code behind Content Page, Content View so only posted the xaml. 

View
`<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MARVLIS_Client_M.Views.SubViews.Simple.MainPageViews.MapView"
             xmlns:c="clr-namespace:MARVLIS_Client_M.Converters" 
             xmlns:marvlis_client_m="clr-namespace:MARVLIS_Client_M"
             xmlns:mapcontroller="clr-namespace:MARVLIS_Client_Shared.ViewModel" 
             xmlns:esri="http://schemas.esri.com/arcgis/runtime/2013"
             xmlns:controls="clr-namespace:MARVLIS_Client_M.Views.SubViews.Simple.Controls"
             xmlns:uiconstant="clr-namespace:MARVLIS_Client_M.Views">

    <ContentPage.Background>
        <LinearGradientBrush EndPoint="0.5,1" StartPoint="0.5,0">
            <GradientStop Color="Black" Offset="0"/>
            <GradientStop Color="#FF383838" Offset="1"/>
        </LinearGradientBrush>
    </ContentPage.Background>

    <ContentPage.Resources>
        <c:ConvertVisToSize x:Key="myConvertVisToSize"/>
        <c:CenterMenuVis x:Key="myCenterMenuVis"/>
    </ContentPage.Resources>

    <Grid BackgroundColor="Transparent">
        <Grid.RowDefinitions>
            <RowDefinition Height="100"/>
            <RowDefinition Height="*"/>
            <RowDefinition Height="40"/>
        </Grid.RowDefinitions>
        <Grid.ColumnDefinitions>
            <ColumnDefinition Width="92"></ColumnDefinition>
            <ColumnDefinition Width="*"></ColumnDefinition>
            <ColumnDefinition Width="92"></ColumnDefinition>
        </Grid.ColumnDefinitions>

        <Grid ZIndex="0" Grid.Row="0" Grid.RowSpan="2" Grid.Column="0" Grid.ColumnSpan="3" HorizontalOptions="Fill" VerticalOptions="Fill">
            <esri:MapView x:Name="MyMapView" GraphicsOverlays="{Binding myGraphicOverlays}" mapcontroller:MapController.Controller="{Binding Controller}"></esri:MapView>
        </Grid>

        <controls:StatusBar Grid.Row="0" Grid.Column="0" ZIndex="0" Grid.ColumnSpan="3" ></controls:StatusBar>
        <controls:FeatureSelectionPanel Grid.Row="1" Grid.Column="0" Grid.ColumnSpan="2" ZIndex="1" IsVisible="{Binding SideFeatureSelectionVis}" VerticalOptions="Start" HeightRequest="340" HorizontalOptions="Start" WidthRequest="300" Margin="0,0,0,220"></controls:FeatureSelectionPanel>
        <controls:LeftBar Grid.Row="1" Grid.Column="0" ZIndex="0" ></controls:LeftBar>

        <controls:DrivingDirectionsBar Grid.Row="1" Grid.Column="1" ZIndex="0" HeightRequest="150" HorizontalOptions="Fill" VerticalOptions="End" IsVisible="{Binding myDirections.CompleteDirections}"></controls:DrivingDirectionsBar>
        <controls:CenterMenus Grid.Row="1" Grid.Column="1" ZIndex="99">
            <controls:CenterMenus.IsVisible>
                <MultiBinding Converter="{StaticResource myCenterMenuVis}">
                    <Binding Path="MapControlToggle"/>
                    <Binding Path="OptionsMapDataToggle" />
                    <Binding Path="OptionsToggle" />
                    <Binding Path="OptionsAddressToggle" />
                    <Binding Path="OptionsPredefinedDestinationsToggle" />
                    <Binding Path="OptionsCurrentDestinationGroupToggle" />
                    <Binding Path="OptionsPreviousRoutedLocationToggle" />
                    <Binding Path="SideTextDirections" />
                    <Binding Path="OptionsSettingsToggle" />
                    <Binding Path="SettingsServerToggle" />
                    <Binding Path="SettingsGPSToggle" />
                    <Binding Path="SettingsDownloadsToggle" />
                    <Binding Path="ProgressionToggle" />
                    <Binding Path="SortViewToggle" />
                    <Binding Path="SettingsAboutToggle" />
                </MultiBinding>
            </controls:CenterMenus.IsVisible>
        </controls:CenterMenus>
        <controls:NotificationsBar Grid.Row="1" Grid.Column="1" Grid.ColumnSpan="2" ZIndex="1" VerticalOptions="StartAndExpand" HeightRequest="60" Margin="215,0,0,0" IsVisible="{Binding NotificationToggle}"></controls:NotificationsBar>
        <controls:RightBar Grid.Row="1" Grid.Column="2" ZIndex="0"></controls:RightBar>
        <controls:BottomBar Grid.Row="2" Grid.Column="0" Grid.ColumnSpan="3" ZIndex="0"></controls:BottomBar>
        <controls:IncidentPanel Grid.Row="0" Grid.RowSpan="2" Grid.Column="0" Grid.ColumnSpan="3" ZIndex="2" IsVisible="{Binding MIncidentInfo}"></controls:IncidentPanel>
        <controls:SupervisorIncidentPanel Grid.Row="0"  Grid.RowSpan="2" Grid.Column="0" Grid.ColumnSpan="3" ZIndex="2"  IsVisible="{Binding SideSIncidents}"></controls:SupervisorIncidentPanel>
        <controls:SupervisorVehiclePanel Grid.Row="0" Grid.RowSpan="2" Grid.Column="0" Grid.ColumnSpan="3" ZIndex="2" IsVisible="{Binding SideSVehicles}"></controls:SupervisorVehiclePanel>
        <controls:Options_History Grid.Row="0" Grid.RowSpan="2" Grid.Column="0" Grid.ColumnSpan="3" ZIndex="2" IsVisible="{Binding OptionsHistoryToggle}"></controls:Options_History>
        <controls:BrowserPanel Grid.Row="0" Grid.RowSpan="2" Grid.Column="0" Grid.ColumnSpan="3" ZIndex="2" IsVisible="{Binding WebVis}"></controls:BrowserPanel>
    </Grid>
</ContentPage>`

ContentView(Container)
`<?xml version="1.0" encoding="utf-8" ?>
<ContentView xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MARVLIS_Client_M.Views.SubViews.Simple.Controls.CenterMenus"
             xmlns:controls="clr-namespace:MARVLIS_Client_M.Views.SubViews.Simple.Controls"
             xmlns:uiconstant="clr-namespace:MARVLIS_Client_M.Views">

    <Grid>
        <Grid.ColumnDefinitions>
            
            <ColumnDefinition Width="1*"></ColumnDefinition>
            <ColumnDefinition Width="1*"></ColumnDefinition>
            <ColumnDefinition Width="1*"></ColumnDefinition>
            <ColumnDefinition Width="1*"></ColumnDefinition>
            <ColumnDefinition Width="1*"></ColumnDefinition>
            <ColumnDefinition Width="1*"></ColumnDefinition>
            <ColumnDefinition Width="1*"></ColumnDefinition>
            <ColumnDefinition Width="1*"></ColumnDefinition>
            <ColumnDefinition Width="1*"></ColumnDefinition>
            <ColumnDefinition Width="1*"></ColumnDefinition>
        </Grid.ColumnDefinitions>
        <Grid.RowDefinitions>
            
            <RowDefinition Height="1*"></RowDefinition>
            <RowDefinition Height="1*"></RowDefinition>
            <RowDefinition Height="1*"></RowDefinition>
            <RowDefinition Height="1*"></RowDefinition>
            <RowDefinition Height="1*"></RowDefinition>
            <RowDefinition Height="1*"></RowDefinition>
            <RowDefinition Height="1*"></RowDefinition>
            <RowDefinition Height="1*"></RowDefinition>
            <RowDefinition Height="1*"></RowDefinition>
            <RowDefinition Height="1*"></RowDefinition>
        </Grid.RowDefinitions>

        <controls:MapMenu Grid.Row="1" Grid.RowSpan="8" Grid.Column="1" Grid.ColumnSpan="8" IsVisible="{Binding MapControlToggle}"></controls:MapMenu>
        <controls:MapSelection Grid.Row="1" Grid.RowSpan="8" Grid.Column="1" Grid.ColumnSpan="8" IsVisible="{Binding OptionsMapDataToggle}"></controls:MapSelection>

        <controls:OptionsPanel Grid.Row="1" Grid.RowSpan="8" Grid.Column="1" Grid.ColumnSpan="8" IsVisible="{Binding OptionsToggle}"></controls:OptionsPanel>
        <controls:Options_AddressRoute Grid.Row="1" Grid.RowSpan="8" Grid.Column="1" Grid.ColumnSpan="8" IsVisible="{Binding OptionsAddressToggle}"></controls:Options_AddressRoute>
        <controls:Options_DestinationsRoute Grid.Row="1" Grid.RowSpan="8" Grid.Column="1" Grid.ColumnSpan="8" IsVisible="{Binding OptionsPredefinedDestinationsToggle}"></controls:Options_DestinationsRoute>
        <controls:Options_DestinationsRoute Grid.Row="1" Grid.RowSpan="8" Grid.Column="1" Grid.ColumnSpan="8" IsVisible="{Binding OptionsCurrentDestinationGroupToggle}"></controls:Options_DestinationsRoute>
        <controls:Options_PreviousRoute Grid.Row="1" Grid.RowSpan="8" Grid.Column="1" Grid.ColumnSpan="8" IsVisible="{Binding OptionsPreviousRoutedLocationToggle}"></controls:Options_PreviousRoute>

        <controls:TextDirectionsPanel Grid.Row="1" Grid.RowSpan="8" Grid.Column="1" Grid.ColumnSpan="8" IsVisible="{Binding SideTextDirections}"></controls:TextDirectionsPanel>

        <controls:SettingsMenu Grid.Row="1" Grid.RowSpan="8" Grid.Column="1" Grid.ColumnSpan="8" IsVisible="{Binding OptionsSettingsToggle}"></controls:SettingsMenu>
        <controls:Settings_Server Grid.Row="1" Grid.RowSpan="8" Grid.Column="1" Grid.ColumnSpan="8" IsVisible="{Binding SettingsServerToggle}"></controls:Settings_Server>
        <controls:Settings_GPS Grid.Row="1" Grid.RowSpan="8" Grid.Column="1" Grid.ColumnSpan="8" IsVisible="{Binding SettingsGPSToggle}"></controls:Settings_GPS>
        <controls:Settings_Downloads Grid.Row="1" Grid.RowSpan="8" Grid.Column="1" Grid.ColumnSpan="8" IsVisible="{Binding SettingsDownloadsToggle}"></controls:Settings_Downloads>
        <controls:Settings_About Grid.Row="1" Grid.RowSpan="8" Grid.Column="1" Grid.ColumnSpan="8" IsVisible="{Binding SettingsAboutToggle}"></controls:Settings_About>
        
        <controls:TriggersMenu Grid.Row="0" Grid.RowSpan="10" Grid.Column="1" Grid.ColumnSpan="8" IsVisible="{Binding ProgressionToggle}"></controls:TriggersMenu>

        <controls:SortPanel Grid.Row="1" Grid.RowSpan="8" Grid.Column="1" Grid.ColumnSpan="8" IsVisible="{Binding SortViewToggle}"></controls:SortPanel>
    </Grid>
</ContentView>`

ContentView(Border in question)
`<?xml version="1.0" encoding="utf-8" ?>
<ContentView xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MARVLIS_Client_M.Views.SubViews.Simple.Controls.OptionsPanel"
             xmlns:uiconstant="clr-namespace:MARVLIS_Client_M.Views">

    <ContentView.Resources>

    </ContentView.Resources>

    
    
        <Border Stroke="White" StrokeThickness="3" BackgroundColor="#FF4C4C4F" HorizontalOptions="Fill" VerticalOptions="Fill">
            <Border.StrokeShape>
                <RoundRectangle CornerRadius="5,5,5,5"></RoundRectangle>
            </Border.StrokeShape>
            <Grid BackgroundColor="#FF4C4C4F">
                <Grid.RowDefinitions>
                    <RowDefinition Height="*"></RowDefinition>
                    <RowDefinition Height="96"></RowDefinition>
                </Grid.RowDefinitions>

                <Grid Grid.Row="0">
                    <Grid.RowDefinitions>
                        <RowDefinition Height="1*"></RowDefinition>
                        <RowDefinition Height="1*"></RowDefinition>
                    </Grid.RowDefinitions>
                    <Grid Grid.Row="0">
                        <Grid.RowDefinitions>
                            <RowDefinition Height="42"></RowDefinition>
                            <RowDefinition Height="*"></RowDefinition>
                        </Grid.RowDefinitions>
                        <Grid.ColumnDefinitions>
                            <ColumnDefinition Width="1*"></ColumnDefinition>
                            <ColumnDefinition Width="1*"></ColumnDefinition>
                            <ColumnDefinition Width="1*"></ColumnDefinition>
                        </Grid.ColumnDefinitions>

                        <Grid Grid.Row="0" Grid.Column="0" Grid.ColumnSpan="1">
                            <Label Text="Routing" HorizontalOptions="Start" Margin="10,5,5,5" VerticalOptions="Center" TextColor="Orange" FontSize="{x:Static uiconstant:UIConstant.MediumFont}"/>
                        </Grid>
                        <Grid Grid.Row="1" Grid.Column="0">
                            <Button Command="{Binding optionsPredefinedDestinations}" CommandParameter="" Text="Facility" Margin="5,5,5,5" VerticalOptions="Fill" HorizontalOptions="Fill" FontSize="{x:Static uiconstant:UIConstant.MediumFont}" Background="#FF4F4B4B" ></Button>
                        </Grid>
                        <Grid Grid.Row="1" Grid.Column="1">
                            <Button Command="{Binding optionsAddress}" CommandParameter="" Text="Address" Margin="5,5,5,5" VerticalOptions="Fill" HorizontalOptions="Fill" FontSize="{x:Static uiconstant:UIConstant.MediumFont}" Background="#FF4F4B4B" ></Button>
                        </Grid>
                        <Grid Grid.Row="1" Grid.Column="2">
                            <Button Command="{Binding optionsRouteIncident}" CommandParameter="" Text="Route History" Margin="5,5,5,5" VerticalOptions="Fill" HorizontalOptions="Fill" FontSize="{x:Static uiconstant:UIConstant.MediumFont}" Background="#FF4F4B4B" ></Button>
                        </Grid>
                    </Grid>
                    <Grid Grid.Row="1">
                        <Grid.RowDefinitions>
                            <RowDefinition Height="42"></RowDefinition>
                            <RowDefinition Height="*"></RowDefinition>
                        </Grid.RowDefinitions>
                        <Grid.ColumnDefinitions>
                            <ColumnDefinition Width="1*"></ColumnDefinition>
                            <ColumnDefinition Width="1*"></ColumnDefinition>
                            <ColumnDefinition Width="1*"></ColumnDefinition>
                        </Grid.ColumnDefinitions>

                        <Grid Grid.Row="0" Grid.Column="0" Grid.ColumnSpan="1">
                            <Label Text="Report" HorizontalOptions="Start" Margin="10,5,5,5" VerticalOptions="Center" TextColor="Orange" FontSize="{x:Static uiconstant:UIConstant.MediumFont}"/>
                        </Grid>
                        <Grid Grid.Row="1" Grid.Column="0">
                            <Button Command="{Binding mHistoryInfoCommand}" Text="History" Margin="5,5,5,5" VerticalOptions="Fill" HorizontalOptions="Fill" FontSize="{x:Static uiconstant:UIConstant.MediumFont}" Background="#FF4F4B4B" ></Button>
                        </Grid>
                        <Grid Grid.Row="0" Grid.Column="1" Grid.ColumnSpan="1">
                            <Label Text="Application" HorizontalOptions="Start" Margin="10,5,5,5" VerticalOptions="Center" TextColor="Orange" FontSize="{x:Static uiconstant:UIConstant.MediumFont}"/>
                        </Grid>
                        <Grid Grid.Row="1" Grid.Column="1">
                            <Button Command="{Binding optionsSettings}" CommandParameter="" Text="System" Margin="5,5,5,5" VerticalOptions="Fill" HorizontalOptions="Fill" FontSize="{x:Static uiconstant:UIConstant.MediumFont}" Background="#FF4F4B4B" ></Button>
                        </Grid>
                        <Grid Grid.Row="1" Grid.Column="2">
                            <Button Command="{Binding optionsLogout}" CommandParameter="" Text="Logout" Margin="5,5,5,5" VerticalOptions="Fill" HorizontalOptions="Fill" FontSize="{x:Static uiconstant:UIConstant.MediumFont}" Background="#FF4F4B4B" ></Button>
                        </Grid>
                    </Grid>
                </Grid>

                <Grid x:Name="ClosingGrid" Grid.Row="1" Margin="10,10,10,10" VerticalOptions="Fill" HorizontalOptions="Fill">
                    <Grid.RowDefinitions>
                        <RowDefinition Height="3"></RowDefinition>
                        <RowDefinition Height="*"></RowDefinition>
                    </Grid.RowDefinitions>
                    <Grid.ColumnDefinitions>
                        <ColumnDefinition Width="1*"></ColumnDefinition>
                        <ColumnDefinition Width="1*"></ColumnDefinition>
                        <ColumnDefinition Width="1*"></ColumnDefinition>
                        <ColumnDefinition Width="1*"></ColumnDefinition>
                        <ColumnDefinition Width="1*"></ColumnDefinition>
                        <ColumnDefinition Width="1*"></ColumnDefinition>
                    </Grid.ColumnDefinitions>

                    <BoxView Grid.Row="0" Grid.Column="0" Grid.ColumnSpan="6" Color="White" HorizontalOptions= "Fill" VerticalOptions="Fill"></BoxView>
                    <Button Grid.Row="1" Grid.Column="1" Grid.ColumnSpan="4" Command="{Binding closeOptions}" CommandParameter="" Text="Close"  FontSize="{x:Static uiconstant:UIConstant.MediumFont}" Margin="0,10,0,0" Background="#FF4F4B4B"  HorizontalOptions="Fill" VerticalOptions="Fill"></Button>
                </Grid>
            </Grid>
        </Border>
    
</ContentView>`

### Steps to Reproduce

Just a breakdown to be more specific -> 

Content Page - 
`        <controls:CenterMenus Grid.Row="1" Grid.Column="1" ZIndex="99">
            <controls:CenterMenus.IsVisible>
                <MultiBinding Converter="{StaticResource myCenterMenuVis}">
                    <Binding Path="MapControlToggle"/>
                    <Binding Path="OptionsMapDataToggle" />
                    <Binding Path="OptionsToggle" />
                    <Binding Path="OptionsAddressToggle" />
                    <Binding Path="OptionsPredefinedDestinationsToggle" />
                    <Binding Path="OptionsCurrentDestinationGroupToggle" />
                    <Binding Path="OptionsPreviousRoutedLocationToggle" />
                    <Binding Path="SideTextDirections" />
                    <Binding Path="OptionsSettingsToggle" />
                    <Binding Path="SettingsServerToggle" />
                    <Binding Path="SettingsGPSToggle" />
                    <Binding Path="SettingsDownloadsToggle" />
                    <Binding Path="ProgressionToggle" />
                    <Binding Path="SortViewToggle" />
                    <Binding Path="SettingsAboutToggle" />
                </MultiBinding>
            </controls:CenterMenus.IsVisible>
        </controls:CenterMenus>`

User clicks button to open an options menu. That button exist on the ContentPage.  That option menu is part of the CenterMenu Content View. 

Center Menu - 
`        <controls:OptionsPanel Grid.Row="1" Grid.RowSpan="8" Grid.Column="1" Grid.ColumnSpan="8" IsVisible="{Binding OptionsToggle}"></controls:OptionsPanel>`

The option menu becomes visible and has an animated effect as if it is resizing to the parent grid. 

Option Menu - 
`        <Border Stroke="White" StrokeThickness="3" BackgroundColor="#FF4C4C4F" HorizontalOptions="Fill" VerticalOptions="Fill">
            <Border.StrokeShape>
                <RoundRectangle CornerRadius="5,5,5,5"></RoundRectangle>
            </Border.StrokeShape>
            <Grid BackgroundColor="#FF4C4C4F">
                <Grid.RowDefinitions>
                    <RowDefinition Height="*"></RowDefinition>
                    <RowDefinition Height="96"></RowDefinition>
                </Grid.RowDefinitions>`
ContentPage -> (Grid Cell of Content Page) ContentView "Menus" -> (Grid Cell of ContentView "Menus") ContentView "Border".

### Version with bug

8.0.7 SR2

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.101

### Affected platforms

iOS

### Affected platform versions

IOS 17+

### Did you find any workaround?

Have not found a workaround other than removing the Border.

**Comment by jonmdev** [comment] 2024-03-09 09:25
This is likely another manifestation of this issue:

https://github.com/dotnet/maui/issues/18204

**Comment by jfversluis** [comment] 2024-03-22 09:56
Duplicate of #18204

**Closed by jfversluis** 2024-03-22 09:56 UTC
Labels: t/bug, platform/iOS 🍎, control-border, s/triaged, potential-regression
