### ISSUE TITLE
Maui Windows Button Images do not display

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#6570] opened 2022-04-27 21:49 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Maui-Windows-Button-Images-do-not-displa/10018708)._

---
In Maui RC1 on VS 2022 17.2.0 Preview 4, Images appear in Buttons on Android but not in Windows.
(I do not know if Windows did display them in earlier VS Preview releases.)

---
#### Feedback Bot on 4/20/2022, 07:48 PM: 

(private comment, text removed)
#### Nina Chen [MSFT] on 4/21/2022, 08:17 PM: 

(private comment, text removed)
#### David Pressman on 4/22/2022, 04:39 AM: 

(private comment, text removed)
#### Nina Chen [MSFT] on 4/25/2022, 07:58 PM: 

(private comment, text removed)
#### David Pressman on 4/26/2022, 04:10 AM: 

(private comment, text removed)
#### David Pressman on 4/26/2022, 04:31 AM: 

(private comment, text removed)
#### David Pressman on 4/26/2022, 04:53 AM: 

(private comment, text removed)
#### Nina Chen [MSFT] on 4/27/2022, 03:06 AM: 

(private comment, text removed)
#### Feedback Bot on 4/27/2022, 03:16 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by hartez** [comment] 2022-04-28 23:08
When you say they don't display - do they not display at all, ever? Or do they start to show up if you resize the window? What layout are you using in the app - a Grid? A StackLayout? Something else?

**Comment by mattleibow** [comment] 2022-11-10 20:29
Duplicate of #7066

**Closed by mattleibow** 2022-11-10 20:29 UTC
Labels: area/controls 🎮
