### ISSUE TITLE
DisplayPromptAsync : Keyboard.Numeric broken in release mode

### ISSUE THREAD

**Issue by nk54** [dotnet/maui#11865] opened 2022-12-05 12:49 UTC
### Description

DisplayPromptAsync doesn't work at all in release mode when using numeric keyboard.
- Works in DEBUG : when tapping on virtual keyboard, the inputs is set : works well
- Doesn't work in RELEASE : when tapping on virtual keyboard, nothing happens

What is weird is that the Telephone keyboard type works.

See github repo to reproduce.

### Steps to Reproduce

Don't forget to set the configuration to RELEASE !

![image](https://user-images.githubusercontent.com/13755220/205642643-ad01e535-27df-4f46-9996-1847c09566aa.png)
### Link to public reproduction project repository

https://github.com/nk54/maui_bug_prompt

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11 and up

### Did you find any workaround?

I'm using Telephone keyboard instead until it is fixed

**Comment by mattleibow** [comment] 2022-12-07 16:19
Unable to reproduce on an emulator, but I did get this in both debug and release on my Samsung Galaxy A53 5G device (Android 12, API 31, One UI 4.1).

I do also notice this in the code around they keyboard types:
https://github.com/dotnet/maui/blob/1f2a6ae564824e65c238750e4046940499623250/src/Controls/src/Core/Platform/AlertManager/AlertManager.Android.cs#L267-L268

**Comment by nk54** [comment] 2022-12-13 12:42
@mattleibow the error comes from DisplayPromptAsync. Not An entry : numeric keyboard works everywhere except the display prompt async

**Comment by marcmognol** [comment] 2022-12-13 20:00
Duplicate of #7470 ?

**Comment by nk54** [comment] 2022-12-14 09:16
@marcmognol yes it is

**Comment by tranb3r** [comment] 2023-03-01 13:45
Any update?

**Comment by shadowfoxish** [comment] 2023-03-22 18:11
I'm seeing the same problem, but sporadically. Sometimes the soft keyboard popups up with the Prompt, sometimes it doesn't. Observations:
1) The Prompt can be typed into when the keyboard shows at the same time as the prompt.
2) The Prompt can not be typed into when the keyboard doesnt show automatically, and you open it by tapping the Entry box.
2.b) The keyboard that is shown in this case is the regular, non Numeric keyboard.
2.c) The physical android device I'm using has a hardware keyboard, and it can also not interact with the Entry box in the Prompt.

Things I tried: 
1) I thought maybe it was an issue with calling display thread off of the MainThread, but I changed the code around to prevent that, or Invoke when necessary. Still sporadic functionality
2) Perhaps trying .ConfigureAwait(false) on the method. No change to behavior.

The nature of whats going on being sort of "random" leads me to think race condition.

**Comment by shadowfoxish** [comment] 2023-03-22 18:31
Follow up: Digging through the debug log for the app, when I try to type on the soft or hardware keyboard when the prompt is in this weird disconnected state, I see the following: (Need 250 is the prompt text, which is interesting because what I actually set it to was "Need 250/EA"... removing the slash doesnt seem to affect anything but the log messages though)

[ViewRootImpl[Need 250] Dropping event due to no window focus: KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_2, scanCode=3, metaState=0, flags=0x8, repeatCount=0, eventTime=1336178955, downTime=1336178955, deviceId=5, source=0x101 }

**Comment by acaliaro** [comment] 2023-03-29 05:11
I have the same problem on various Zebra Devices, with different Android versions

**Comment by shadowfoxish** [comment] 2023-04-05 14:39
Could this be brought on by the Page being interacted with not having any focusable elements? In my particular case, I'm just showing a collection view with some data in it, and there are no Entry controls on the screen to receive focus generally.

**Comment by comptoiragricole** [comment] 2023-06-14 15:03
to reproduced the bug in the emulator you need just to change os language to french instead english

**Comment by tranb3r** [comment] 2023-06-27 13:58
Any update? This is quite serious for non-english apps.

**Comment by jsuarezruiz** [comment] 2023-07-10 13:56
The issue will be fixed by https://github.com/dotnet/maui/tree/fix-11865

**Comment by Xyncgas** [comment] 2023-08-12 17:04
I am interested why it happened

**Closed** 2023-08-25 18:23 UTC
Labels: t/bug, platform/android 🤖, p/1, area/controls 🎮, control-dialogalert
