### ISSUE TITLE
Issues AMM0000 error in the AndroidManifest 

### ISSUE THREAD

**Issue by LaurenWholey** [dotnet/maui#9118] opened 2022-08-01 19:30 UTC
### Description

This error is coming from the generated Android Manifest for a sample app for a library I've been migrating to Maui from Xamarin. The error code is AMM0000 with no description that is happening in my AndroidManifest.xml. The file pulls up a generated AndroidManifest and not the Manifest in my platform specific code folders. I'm not sure what is causing this error, as there is no information provided with the error. 
<img width="508" alt="AMM0000" src="https://user-images.githubusercontent.com/103149052/182230305-890b7f34-b6fb-4b20-9e73-c94283fd1841.PNG">

### Steps to Reproduce

This repo is not public so I provided the affected files:
Below is the Android Manifest I made (modeled after the Android Manifest from the Maui Sample App):
<img width="720" alt="MauiSampleAppAndroidManifest" src="https://user-images.githubusercontent.com/103149052/182220071-6c879543-78ab-4fb2-a2fb-bdfc5be599ce.PNG">
Generated Android Manifest that error references (With provider information excluded):
<img width="828" alt="Genereated android manifest 2" src="https://user-images.githubusercontent.com/103149052/182230111-891a9367-d4a0-4eb5-8a27-cfc97670c3cb.PNG">

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android Target Sdk Version: 31 

### Did you find any workaround?

No work around

**Comment by jfversluis** [comment] 2022-08-02 18:34
Duplicate of #9120

**Closed by jfversluis** 2022-08-02 18:34 UTC
Labels: t/bug, s/needs-verification
