### ISSUE TITLE
Hamburger menu remains visible in Android while Shell.FlyoutBehavior is set to Disabled

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#25959] opened 2024-11-19 19:33 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Hamburger-menu-remains-visible-in-Androi/10792713)._

---
Click the icon in the title bar, then click the arrow on te new page.
You will see the hamburger menu flash by on the left in the title view.
The Shell.FlyoutBehavior is set to Disabled.
This happens only in Android, not in iOS and Windows.

Visual Studio 17.12.0
.NET 9
Microsoft.Maui.Controls Version 9.0.10

Sample repository: https://github.com/geertgeerits/MauiBugShellAndroid

---
#### Feedback Bot on 11/18/2024, 06:20 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

**Comment by PureWeen** [comment] 2024-11-20 00:05
Duplicate of #21455

**Closed by PureWeen** 2024-11-20 00:05 UTC
