### ISSUE TITLE
Windows TabBar Icons do not use the correct color

### ISSUE THREAD

**Issue by unombun** [dotnet/maui#16575] opened 2023-08-07 08:28 UTC
### Description

On Windows the icons in tab bar are not initially in the correct color. (on Android and iOS works fine)
After I change tab, they are in the correct color.

Before changing tab:  (icons are black even if they should be white)
![image](https://github.com/dotnet/maui/assets/11754566/9e8c8441-75b0-42ce-b24e-8871397f5e3b)

After changing tab: (icons are white as they should)
![image](https://github.com/dotnet/maui/assets/11754566/7ce1d02b-1020-4cf1-a1df-f2c651ed9715)

### Steps to Reproduce

1. Create MAUI App
2. Set some tabs with icons and texts
3. The icons are not in the correct color at the beginning
4. After changing a tab, the icons are in the correct color.

### Link to public reproduction project repository

https://github.com/flesarradu/WindowsTabBarColorsIssue

### Version with bug

7.0.86

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Did you find any workaround?

This happens only in LightMode theme, using DarkTheme seems to be fine

**Comment by jsuarezruiz** [comment] 2023-08-07 14:15
This have been fixed on .NET 8 here https://github.com/dotnet/maui/pull/15690

**Comment by XamlTest** [comment] 2023-08-18 10:12
Verified this on Visual Studio Enterprise 17.8.0 Preview 1.0. This issue does not repro on Windows 11 .NET 8, Android 13.0-API33 and iOS 16.4 with below Project:
[WindowsTabBarColorsIssue.zip](https://github.com/dotnet/maui/files/12378189/WindowsTabBarColorsIssue.zip)

![TabColor](https://github.com/dotnet/maui/assets/97647558/8deedd3d-8b40-4ee3-962b-f17e25ed345d)

**Comment by samhouts** [comment] 2023-08-21 19:32
Duplicate of #12386

**Closed by samhouts** 2023-08-21 19:32 UTC
Labels: t/bug, platform/windows 🪟, area/shell 🐢, s/triaged, s/try-latest-version
