### ISSUE TITLE
Is there anything similar to Xamarin.Forms.Platform.WPF for developing WPF using MAUI

### ISSUE THREAD

**Issue by BaY1251** [dotnet/maui#21477] opened 2024-03-27 08:32 UTC
### Description

WPF is still widely used and should not be abandoned

### Public API Changes

None

### Intended Use-Case

None

**Comment by jfversluis** [comment] 2024-03-27 08:43
Duplicate of #1789

**Closed by jfversluis** 2024-03-27 08:43 UTC
Labels: proposal/open
