### ISSUE TITLE
[BUG} PlatformImage.FromStream doesn't create an IImage, returns null

### ISSUE THREAD

**Issue by AlexanderSCK** [dotnet/maui#11992] opened 2022-12-09 12:15 UTC
### Description

I am trying to draw images using MAUI.Graphics, but using the stream returns null. I have inserted my svg image into the resources folder and have specified it as Embedded Resource and Do not Copy. I checked if the namespace and path to image is correct from GetManifestResourceStream, the stream finds the image but then when casting it is always null. The behavioir is on both Android and iOS. The namespace is correct, I even checked it by returning an array of strings from the resource. The object reference is not set to an instance of an object when calling canvas.DrawImage.

```cs
IImage image;
Assembly assembly = GetType().GetTypeInfo().Assembly;
using (Stream stream = assembly.GetManifestResourceStream("ControlMAUI.Resources.Images.dotnet_bot.png"))
{
    image = PlatformImage.FromStream(stream);
}

if (image != null)
{
    canvas.DrawImage(image, 10, 10, image.Width, image.Height);
}
```

### Steps to Reproduce

Try to get an image as an embedded resource from a stream and then call canvas.DrawImage.

### Link to public reproduction project repository

No link

### Version with bug

6.0.486

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

iOS 16 Android 13

### Did you find any workaround?

No workaround

**Comment by mattleibow** [comment] 2023-02-04 02:04
Just want to check, you have a SVG file that you have marked as an embedded resource? I see in your code you are loading a png.

I think maybe this is not exactly possible. The embedded resource just adds the raw svg content into your app dll. It is not really the location that does things, but the build action.

The magical one that converts svg into png is the `<MauiImage>`, however, this does not make it available to load directly.

**Comment by mattleibow** [comment] 2023-02-04 02:05
Duplicate of #12556

**Closed** 2023-02-04 02:05 UTC
Labels: t/bug, area/image :framed_picture:
