### ISSUE TITLE
Another problem Occurs in Release Mode, Dynamic Color or Programmatically C# not Changed... [RELEASE MODE ONLY]

### ISSUE THREAD

**Issue by nextcodelab** [dotnet/maui#10181] opened 2022-09-17 16:41 UTC
### Description

In debug mode my App buttons and text update fine. But on  RELEASE MODE the color not changing...
```cs
//Sample Dynamic color change on tapped...

//this label will not change (TAPPED AND APPLY) background color in C# on RELEASE MODE.
 this.titleTxt.BackgroundColor = App.CurrentMarkingColor;  

//this Button will not change background color on Clicked (Clicked AND APPLY)  C# code on RELEASE MODE.
button. BackgroundColor = Colors.Green; 
```

### Steps to Reproduce

It seems only android always have issues..

### Link to public reproduction project repository

I dont have sample

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android

**Comment by jvakos** [comment] 2022-10-14 13:17
This is a **major** bug in my opinion.
### Steps to reproduce :
-  File->New Project -> Maui 
- Navigate to OnCounterClicked  and add the following line
`CounterBtn.BackgroundColor = Colors.Red;`
- Deploy on **RELEASE**

### Expected behavior
After clicking the "Click me" button , the color of the buttin must turn to red.

### Actual behavior
Background of button don't change.

### Tip
On Debug mode it works as expected


### git repo to test (on release mode)
https://github.com/jvakos/maui_color_in_release_problem

**Comment by jvakos** [comment] 2022-10-14 13:59
Found a workaround for android.
After setting the background insert this line
`CounterBtn.Handler.UpdateValue("Background");`

**Comment by jvakos** [comment] 2022-11-16 13:59
This bug remains on dotnet 7.0. 
Any news?  It's been 2 months that a developer cannot change the background color of elements by c#.

**Comment by HopInTheCloud** [comment] 2022-12-10 09:03
MAUI is still full of basic bugs. I cannot believe that it was released this way

**Comment by HopInTheCloud** [comment] 2022-12-11 07:45
Changing the backgroundcolor on entry control in runtime does not work on Android

**Comment by fgiacomelli** [comment] 2022-12-20 09:07
Same problem for me, I have a style in binding with a property that activate a trigger when a value change, in debug is all ok, but not in release.
I also tried to replace the trigger with a converter, but the background color doesn't change only in release.

This is very annoying because the app it's not presentable with bugs like these, and the customer can't accept that is another platform bug (the question should be: why don't you choose another platform?),

We need to know when it will be fixed

**Comment by goztopuz** [comment] 2022-12-29 20:15
Had same problem solved by changing backgroundcolor to background property on my button

**Comment by hartez** [comment] 2023-02-01 17:06
See also #11662 (with a possible workaround).

**Comment by DanTravison** [comment] 2023-02-10 22:35
I am seeing the same problem with Button when setting background via a DataTriggers.  Using Background versus BackgroundColor also solves it.  This is only occurring with Android/Release builds in both the simulator and my Note 10+ device.

FWIW:  I am using the same DataTriggers with Border and do not see this problem. Additionally, I don't see the issue with Button on iOS (iPad Pro) or Windows builds.

**Comment by Anioz** [comment] 2023-02-11 07:47
Same problem here with the Button element, no scrollview tough, here its inside a listview.header - stacklayout - grid (in that order), setting the Color with the background instead of the broken BackgroundColor is a nice enough work around for now

**Comment by Synthaxe42** [comment] 2023-02-11 23:59
I am seeing the same, with a Button element in AbsoluteLayout within a Grid, and only on Android Release mode, (ie it does not occur in Debug mode.) Using "Background" instead of "BackgroundColor" also works for me too.

**Comment by mattleibow** [comment] 2023-03-08 19:12
Duplicate of #11662

**Closed** 2023-03-08 19:13 UTC
Labels: t/bug, platform/android 🤖, p/1, partner/cat 😻, area/controls 🎮, control-button, external, partner/mono
