### ISSUE TITLE
VS2022 .NET 8 MAUI iOS only Shell navigation issue when more than five tab items used

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#19271] opened 2023-12-06 22:50 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/VS2022-NET-8-MAUI-iOS-only-Shell-naviga/10524716)._

---
[severity:Other]
With iOS only (Windows and Android are working as expected), in <TabBar> when more than five <ShellContent> items are configured and the first item contains a Button that "await Shell.Current.GoToAsync(sixth item)" the "More" menu appears instead of the sixth item.   If the Button that "await Shell.Current.GoToAsync()" point to the second, third, or forth item, all works as expected (the second, third, or fourth item appear).

The impact of this issue, if not resolved, will force a redesign of the User Experience for iOS based devices.

---
#### Feedback Bot on 11/23/2023, 06:48 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by jppois** [comment] 2023-12-07 23:12
Project Uploaded with information in the Readme file
See https://github.com/jppois/iOSShellNavIssue

PS: Thank you for helping!

**Comment by PureWeen** [comment] 2023-12-13 19:23
Duplicate of #18193

**Closed by PureWeen** 2023-12-13 19:23 UTC
Labels: t/bug, area/shell 🐢
