### ISSUE TITLE
[MAUI] Recipe App build failed with error: One or more duplicate file names were detected

### ISSUE THREAD

**Issue by QianaJiao** [dotnet/maui#17213] opened 2023-09-05 10:58 UTC
### Description

.NET SDK version: 8.0.100-rc.1.23423.3
Recipe App build failed with error: One or more duplicate file names were detected. 

### Steps to Reproduce

1.Download the project https://github.com/rachelkang/recipeSearch and locate it.
2.Build project. 

**Actual result:**
Build failed with error: One or more duplicate file names were detected. All image output filenames must be unique: search (Resources\Images\search.png), cookbook (Resources\Images\cookbook.png) 
![image](https://github.com/dotnet/maui/assets/91244512/56e1ebc3-f6be-4983-93c9-4a6aeec47213)

### Link to public reproduction project repository

https://github.com/rachelkang/recipeSearch

### Version with bug

Microsoft.Maui.Controls 8.0.0-nightly.9158+sha.cad4279216-azdo.8352477

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.0-preview.7.8842

### Affected platforms

iOS

### Did you find any workaround?

**Workaround 1:** 
For iOS Testing: Copy the image to a new folder and change the path to MauiImage
![image](https://github.com/dotnet/maui/assets/91244512/e0fd7bfd-f0f8-429b-a1d2-17cce3ad4e69)

**Workaround 2:** 
This error will only cause iOS debug to fail, so it can be used for other projects
For Mac/Android/Windows:  Comment out this line: 
![image](https://github.com/dotnet/maui/assets/91244512/fa573ddf-c98b-4368-8f93-0c1b8ef203ef)

**Comment by QianaJiao** [comment] 2023-09-05 11:11
We are not sure if this bug related to https://github.com/dotnet/maui/issues/17213
Here is the Xamarin logs and binlog: 
[17.0.zip](https://github.com/dotnet/maui/files/12522677/17.0.zip)
[binlog.zip](https://github.com/dotnet/maui/files/12522685/binlog.zip)

**Comment by mattleibow** [comment] 2023-09-05 15:47
This is because you are including the images twice. Once with `Resources\Images\*` and then again with `Resources\Images\search.png`. You need to use `Update`:

```cs
<MauiImage Update="Resources\Images\search.png" ... />
```

**Comment by QianaJiao** [comment] 2023-09-07 02:32
Hi @mattleibow, thanks for your reply. Yes, I updated it to `Update `and built it successfully.

**Comment by mattleibow** [comment] 2023-09-07 16:11
Great! I'll close this now as it is not a bug but rather the error of including the same image more than once.

**Closed by mattleibow** 2023-09-07 16:11 UTC
Labels: s/not-a-bug, area/single project ☝️, s/needs-attention, potential-regression

**Comment by vallgrenerik** [comment] 2023-09-14 07:50
> This is because you are including the images twice. Once with `Resources\Images\*` and then again with `Resources\Images\search.png`. You need to use `Update`:
> 
> ```
> <MauiImage Update="Resources\Images\search.png" ... />
> ```

Chipping in for possibly future headache 😊
This is also true for MauiIcon
