### ISSUE TITLE
Statusbar color changes when opening a modal page on Android

### ISSUE THREAD

**Issue by MikaelStalvik** [dotnet/maui#26867] opened 2024-12-30 15:33 UTC
### Description

When displaying a modal page using PushModalAsync, the statusbar color is overriden with Android's colorPrimaryDark value.
The statusbar color has previously been set on the shell page level using the StatusBarBehavior.

![Image](https://github.com/user-attachments/assets/4fdd9c3e-b405-497c-b905-e529cafb5978)

![Image](https://github.com/user-attachments/assets/5f34b410-af3e-4305-bcbd-b17b9874e752)

### Steps to Reproduce

1. Create a File > New .NET MAUI app using .NET9
2. Upgrade required Nuget packages
3. Add the CommunityToolkit.Maui Nuget package
4. In AppShell.xaml, add the following code to force the statusbar to be red:
    <Shell.Behaviors>
        <toolkit:StatusBarBehavior StatusBarColor="Red" StatusBarStyle="LightContent" />
    </Shell.Behaviors>
5. In Platforms > Android > Resources > values > colors.xml, change the value of colorPrimaryDark to #00ff00
6. Create a new MAUI ContentPage, DetailsPage
7. In MainPage.xaml.cs, change the code in OnCounterClicked to open a modal page:
        private async void OnCounterClicked(object sender, EventArgs e)
        {
            await Navigation.PushModalAsync(new DetailsPage());
        }
8. Run the application and click the Click me button

Actual result: 
When the modal DetailsPage is opened, the statusbar color changes from red to green.

Expected result:
When the modal DetailsPage is opened, the statusbar color should remain red.

### Version with bug

9.0.21 SR2.1

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Tested with Android 15, API 35

### Did you find any workaround?

No

### Relevant log output

```shell

```

**Comment by jfversluis** [comment] 2024-12-30 15:43
Duplicate of #26388

**Closed by jfversluis** 2024-12-30 15:43 UTC
Labels: t/bug
