### ISSUE TITLE
Binding Content Not Showing in SwipeView (Used Inside CollectionView) 

### ISSUE THREAD

**Issue by mistrypragnesh40** [dotnet/maui#16567] opened 2023-08-05 12:48 UTC
### Description

When I tried to use swipe view inside CollectionView DataTemplate. It's only showing static content not the binding content.

### Steps to Reproduce

![image](https://github.com/dotnet/maui/assets/47309472/5f7482ea-53e0-4496-b00e-d97d8278cfe0)
Here is the UI Code.

```
        <CollectionView ItemsSource="{Binding AnyItemSource}">
            <CollectionView.ItemTemplate>
                <DataTemplate x:DataType="DataType">
                    <SwipeView Threshold="100" >
                        <SwipeView.RightItems>
                            <SwipeItem BackgroundColor="{x:StaticResource Primary}" Text="Setting" CommandParameter="{Binding .}" />
                        </SwipeView.RightItems>

                                                       <Grid RowSpacing="0" RowDefinitions="10,Auto,10,1" ColumnDefinitions="*,30">
                                    <VerticalStackLayout Grid.Row="1" Spacing="5">
                                        <Label  Text="{Binding Name}" Style="{x:StaticResource SubTitle}" />
                                        <Label Text="{Binding Created,StringFormat='Created: {0:dd MMM yyyy}'}" Style="{x:StaticResource MediumMinusTitle}" />
                                        <Label Text="{Binding Updated,StringFormat='Updated: {0:dd MMM yyyy}'}" Style="{x:StaticResource MediumMinusTitle}" />
                                    </VerticalStackLayout>


                                    <Label VerticalTextAlignment="Center" FontSize="20"
Text="{x:Static icons:Icons.NavigateNext}"  Style="{x:StaticResource MaterialLabel}" Grid.Row="1" Grid.Column="1" />

                                    <BoxView Grid.Row="3" Grid.ColumnSpan="2" />
                                </Grid>
                    </SwipeView>
                </DataTemplate>
            </CollectionView.ItemTemplate>
        </CollectionView>
```

### Version with bug

8.0.0-preview.6.8686

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

**Comment by harry-cpp** [comment] 2023-08-05 17:45
Sounds like a duplicate of: https://github.com/dotnet/maui/issues/16345

**Comment by HKLM** [comment] 2023-08-07 01:31
I have been having this same issue. The only way I can continue development is that I have to keep rolling back VS and uninstall any SDK/workload and make sure, at most I am using SDK 8.0.100-preview.3. Anything newer gives that same issue

**Comment by drasticactions** [comment] 2023-08-07 10:37
Duplicate of https://github.com/dotnet/maui/issues/16345

**Closed by drasticactions** 2023-08-07 10:37 UTC
Labels: t/bug, s/duplicate 2️⃣, platform/android 🤖, control-swipeview
