### ISSUE TITLE
[Blazor Hybrid] `UseMaui` in Razor Class Library breaks wwwroot paths

### ISSUE THREAD

**Issue by nor0x** [dotnet/maui#23270] opened 2024-06-26 10:07 UTC
### Description

I have a razor class libary project with `<UseMaui>true</UseMaui>` in the csproj. 
This breaks the paths for assets in the `wwwroot`. Which can usually be accessed in the `index.html` via `<link rel="stylesheet" href="_content/RazorClassLibrary1/main.css" />` but in case of `<UseMaui>true</UseMaui>` the `main.css` ends up directly in `wwwroot` - no subfolder is created at all for the library (i have checked `bin\Debug\net8.0-windows10.0.19041.0\win10-x64\AppX\wwwroot`)

for regular content in wwwroot this is can be fixed by changing the paths in the index.html from 
``<link rel="stylesheet" href="_content/RazorClassLibrary1/main.css" />``
to 
``<link rel="stylesheet" href="main.css" />``

but I cannot make scoped css work - I expected a `RazorClassLibrary1.styles.css` file in the output folder, but it's not present.

Here is a diagram to better visual the scenario:
![image](https://github.com/dotnet/maui/assets/3210391/c4db66ac-18e8-4930-8c58-77012ffc0d7d)

### Steps to Reproduce

1. Create new MAUI Blazor Hybrid App
2. Add Razor Class Libary Project with `<UseMaui>true</UseMaui>`
3. Use Component from RCL in MAUI App

### Link to public reproduction project repository
https://github.com/nor0x/maui-repro-23270

### Version with bug

8.0.60 SR6

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Did you find any workaround?

for non scoped css one can just use the direct path within the resulting wwwroot (be careful with naming). No workaround so far for scoped css files

**Comment by jfversluis** [comment] 2024-06-26 11:38
@nor0x I see the bot detected #3288 as a duplicate and it seems indeed pretty similar, could you confirm?

**Comment by nor0x** [comment] 2024-06-26 12:35
oh yes, the bot got it right - it is the same as #3288

**Comment by jfversluis** [comment] 2024-07-04 14:29
Thanks for confirming and adding the extra details!

**Comment by jfversluis** [comment] 2024-07-04 14:29
Duplicate of #3288

**Closed by jfversluis** 2024-07-04 14:29 UTC
Labels: t/bug, platform/windows 🪟, area-blazor
