### ISSUE TITLE
FontFamily is not recognized in Unpackaged application in net 8

### ISSUE THREAD

**Issue by danies8** [dotnet/maui#19061] opened 2023-11-27 15:40 UTC
### Description

This link not solved in NET 8.
[WinUI] FontFamily is not recognized in Unpackaged application
https://github.com/dotnet/maui/issues/9104

### Version with bug

8.0.3

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

**Comment by mattleibow** [comment] 2023-11-28 19:32
Did you have a different font to the old issue? Or is that sample not working still?

**Comment by danies8** [comment] 2023-11-28 19:57
It is not working.
All icons that use fonts are not working.
Also I'm using telerik controls and they said this Microsoft bug.

**Comment by danies8** [comment] 2023-11-28 19:59
In additions the controls not lóok good in unpackaged deployment.

**Comment by danies8** [comment] 2023-11-28 20:01
![image](https://github.com/dotnet/maui/assets/1079689/affea875-3c5a-46c1-8f7b-5de31ce42fb2)

**Comment by mattleibow** [comment] 2023-11-28 22:45
I'll try get a copy of Windows Server 2019 up here, but, do the controls look correct if you make a plain WinUI app and run that on the server?

All the icons you point to here and the in other issue are OS icons, not maui icons. This may be an issue in Windows Server fonts/support.

**Comment by mattleibow** [comment] 2023-11-28 22:49
You also have comments here: https://github.com/microsoft/microsoft-ui-xaml/issues/7866

The comments from brad says: "This app is not MAUI but it is WinUI3."

**Comment by jeremy-visionaid** [comment] 2023-11-28 22:52
Maybe a dupe of #15802 ?

**Comment by mattleibow** [comment] 2023-11-28 23:17
Hmmm, could be. @danies8 are you using fonts on Label/Button or are using FontImageSource on Image/ImageButton?

**Comment by mattleibow** [comment] 2023-11-29 00:11
@danies8 I did some tests now on my new Windows Server 2019 VS (with Desktop Experience) and I am not able to repro the dropdowns missing arrows and other text not rendering.

I _was_ able to repro #15802 with FontImageSource not working.

[MauiApp190.zip](https://github.com/dotnet/maui/files/13494653/MauiApp190.zip)

This was my publish command:

> dotnet publish -f net8.0-windows10.0.19041.0 -c Release -p:RuntimeIdentifierOverride=win10-x64 -p:WindowsPackageType=None -p:WindowsAppSDKSelfContained=true -p:SelfContained=true

**Comment by mattleibow** [comment] 2023-11-29 00:13
Unless those are all Telerik controls? I think I need to see a repro at this point as I am not sure of exactly what you have.

**Comment by danies8** [comment] 2023-11-29 11:32
I used :
`dotnet publish -f net8.0-windows10.0.19041.0 -c Release -p:WindowsPackageType=None  -p:WindowsAppSDKSelfContained=true /p:PackageCertificateThumbprint="c01ba45666762f3615cf6813aeb4dc4b1919541d" -p:RuntimeIdentifierOverride=win10-x64`

**Comment by danies8** [comment] 2023-11-29 12:19
Please see : https://app.screencast.com/H2vDCa2jmYxCf

**Comment by danies8** [comment] 2023-11-29 12:21
I also asked from Manager support  of TELERIK (Lance) to answer here.

**Comment by LanceMcCarthy** [comment] 2023-11-29 14:23
Hi Daniel,

I don't see how this is related to the Telerik UI for Maui components, as the problem is presented in a normal Maui `Button` or  in another UI control.  Let's take a step back and align on some ideas:

- You are using our custom font in parts of your application
- That custom font is not registered correctly, so in unpackaged app, the font is missing
- We're not sure why it's missing, but it seems a workaround is to use the file path to the package assets in a custom Handler Loaded override. This fixes any relative paths to the resource's file.

That seems like you have a couple steps to do so that when your app is running unpackaged, you need to address this use case. Here are the fonts we use:

- https://github.com/telerik/maui-samples/tree/main/Samples/ControlsSamples/Resources/Fonts

If you have the demos installed locally, you will find them here:

![image](https://github.com/dotnet/maui/assets/3520532/fa8151bb-485f-4911-b3b8-00685e80d1b4)

If you open the font file, you will find all the information you need to register them separately (font family name, etc).

![image](https://github.com/dotnet/maui/assets/3520532/b53d0492-fe38-4eb1-bc63-961d178388f0)

You did share a code snippet with me, all I can say about that is it is incorrect and looks like you copy/pasted a FontAwesome example without updating it to match the font file's actual FontFamilyName?

![image](https://github.com/dotnet/maui/assets/3520532/9fbde187-45f5-4036-a780-941e5a0226e1)

Some challenges for you:

- Shouldn't that be `telerikcontrolsicons.ttf#telerikcontrolsicons` instead?
- Did you include the font file in your project's Resources/Fonts directory? 
    - If yes, did you confirm the file is being build as MauiIcon?
- Try using a different font file, if the issue only happens with telerikcontrolsicons.ttf, then I can open a separate case and escalate for you.

## Continued Assistance

Since this issue is flagged with needs-info/needs-repo, you will need to do the following:

1. Create a new .NET MAUI project
2. Add the font files we use in our demos/control to `Resources/Fonts`
3. Update **MainPage** with a `Button` that uses a `FontImageSource`
4. Build and publish the demo app
5. Verify the problem exists on Windows Server 2019
6. Apply the recommended solution to the project, build/package/run again on Windows Server 2019 and check again

If the problem still exists, you can share the reproducible project with me and Matthew for further investigation.

Tips:
- Do not add a reference to Telerik controls to the demo/repo project. if the issue is related to missing font family/file/resources in an unpackaged app, adding the 3rd party library is an unnecessary complication
- If the problem does only exist for icons within the Telerik controls, I can open an issue with the Telerik UI for Maui dev team. If the Handler.Loaded workaround is a solution, we can write a KB article instructing how to handle this case.


## Side Note
@mattleibow Telerik UI for Maui uses the telerikcontrolsicons.ttf as the source of icons throughout the controls. This usually doesn't require that the developer also include the fonts file in their project. I think this is the genesis of Daniel's motive ot open this Issue.

Although this time it affects RadButton for example, but it should affect any 3rd party library that has font assets in it (or anything that points to the appx package URI). I haven't dug into the WinUI threads on this topic, but I'm guessing when published unpackacked, the file paths to the package are incorrect?

**Comment by LanceMcCarthy** [comment] 2023-11-29 15:03
As a side thought, @danies8 what happens if you actually install the missing fonts into Windows Server 2019 instead of relying on the app to use in-package assets? This could be a temporary workaround until the fundamental issue is resolved.

1. Download the file to the Windows Server 2019 machine and install it for **All Users** (if you don't know how, see [this tutorial](https://borncity.com/win/2020/05/15/windows-server-2019-font-install-per-user-or-system-wide/))
    - You can get `telerikcontrolsicons.ttf` from [here](https://github.com/telerik/maui-samples/tree/main/Samples/ControlsSamples/Resources/Fonts)
    - Check your project's `Resources/Fonts` folder for any other font files you might want to add
2. This should be repeated for any other custom fonts you are using (FontAwesome, etc)
3. Finally, run the unpackaged app again as see if the previously affected items are rendered

**Comment by danies8** [comment] 2023-11-29 15:56
Hi,
1.Create a new .NET MAUI project
2.Add the font files we use in our demos/control to Resources/Fonts
3.Update MainPage with a Button that uses a FontImageSource
4.Build the app and there is error:
![Font](https://github.com/dotnet/maui/assets/1079689/379bd3c4-5f67-413c-8a9e-ac9a1b4980be)
5.Sample:
[FontsMauiApp.zip](https://github.com/dotnet/maui/files/13502669/FontsMauiApp.zip)

**Comment by LanceMcCarthy** [comment] 2023-11-29 16:04
> there is error

Did you try building a couple times, or did you immediately post here after getting the error once? The reaosn I ask is the Resizitizer is a process that creates the correct assets for each platform (e.g. MauiIcon files).

This happens in a background thread and can lock the files it is working with. Sometimes, if you try to build too fast, or there's a different order of operations, you can encounter issues. Just Clean and Rebuild the app again, try it a couple times until it works. Be patient between attempts, or even close and restart Visual Studio if the lock isn't going away.

**Comment by LanceMcCarthy** [comment] 2023-11-29 16:27
Daniel, I've reviewed the project and it is not what we asked for. 

You did not complete the process if registering the fonts and there is nothing in MainPage that attempts to use the font. 

Please do the following:

1. Update MauiProgram and finish registering the added font file. If you forgot how to do this, please see https://learn.microsoft.com/en-us/dotnet/maui/user-interface/fonts?view=net-maui-8.0
2. I do not see any changes to MainPage.xaml with anything that will try to use the custom font.
3. MOST IMPORTANT OF ALL: Publish and run the app on Windows Server and verify it is broken

Once you've confirmed the behavior, get a screenshot, then come back here with the project and the evidence of the behavior.

## Important Advice when Working With Community

Daniel, this isn't the first time you've rushed your replies before completing any tasks, which is wasting everyone's time. It is a frequent behavior I've experienced with you over the past 2 years:

1. You ask for help, but give the bare minimum or incomplete information for other to assist
2. When you're forced to give more details, it is also minimal/incomplete/non-functional and want the community to finish your work.

If you expect other people to help you, you need to at least put in the effort on your side. If you do not, then you will find that people are less willing to assist you and many posts will go unanswered. This is why I am offering this advice to you because I am starting to see your posts on Q&A get ignored because they assume that you have not provided enough information and expect others to do the research for you.

This is a grim fate for a developer and I don't want to you have to experience that. Please be considerate of the people who are willing to assist you.

**Comment by danies8** [comment] 2023-11-29 19:32
Hi Matthew,
I've finished preparing the repro project that you can use the verify the problem with a normal Microsoft Label.

1.Here is the repro project, you can use the following command to build it unpackaged
[665cebdb-64b9-44c0-89f8-d25c5f159313_UnpackackedFontsTest-Issue19061.zip](https://github.com/dotnet/maui/files/13504419/665cebdb-64b9-44c0-89f8-d25c5f159313_UnpackackedFontsTest-Issue19061.zip)
`dotnet publish -f net8.0-windows10.0.19041.0 -c Release -p:WindowsPackageType=None  -p:WindowsAppSDKSelfContained=true  -p:RuntimeIdentifierOverride=win10-x64
`
2.Notice MainPage has two Labels.
3.Both Labels use an external font, a separate one for each
4.This works in a packaged app
5.It does not work in an unpacked app.
<img width="705" alt="window_10" src="https://github.com/dotnet/maui/assets/1079689/57b62895-7bb1-4dfa-88fa-cad7cfda26f6">
![2019](https://github.com/dotnet/maui/assets/1079689/0cd27656-8196-4f3f-8606-6d18708a77b0)

Let me know if you need anything else.

Thank you for your time and effort,

Dani

**Comment by mattleibow** [comment] 2023-11-29 19:54
| Packaged App | Unpackaged App |
|:-:|:-:|
|![image](https://github.com/dotnet/maui/assets/1096616/e25f2d44-9660-46ca-821d-a9086a3f9763)|![image](https://github.com/dotnet/maui/assets/1096616/2111a8b4-6df5-482e-a63d-1d23b76f82b7)|

I believe this is because you have invalid XAML:

```xaml
<Label Text="&amp;#xe85b;" ... />
```

This should be (note the `&amp;` is now just `&`):

```xaml
<Label Text="&#xe03a;" ... />
```

![image](https://github.com/dotnet/maui/assets/1096616/6c8edaed-6328-4c89-8cc6-a0cc44aa4fc1)


The reason for the first label being incorrect is a spelling error in the font name. It is registered as `telerikcontrolsfonts` but used as `telerikcontrolsfont`. But even this is incorrect, the font name is `telerikcontrolsicons`:

```cs
fonts.AddFont("telerikcontrolsicons.ttf", "telerikcontrolsicons");
```

```xaml
<Label Text="&#xe03a;"
        FontFamily="telerikcontrolsicons" />
```



![image](https://github.com/dotnet/maui/assets/1096616/30adb3a9-3290-441e-9730-a576a7451876)

**Comment by LanceMcCarthy** [comment] 2023-11-29 20:07
@mattleibow  thank you for helping Daniel with the unrelated clean up. Were you able to check if this works in unpackaged on Windows Server 2019? I'm still trying to get Azure to spin up a new one for me.

I have an idea, that if the unpackaged app isn't including font files which are embedded in the external assemblies, Daniel can workaround this by including the font file in _his_ project code, registering them in MauiProgram and using CopyAlways as the Build Action (looking at the workaround for microsoft-ui-xaml/issues/7866, I feel that should also work here, too).

**Comment by danies8** [comment] 2023-11-29 20:39
Thanks for info.
I tested your fix project on window 10 + server 2019 works correctly as exe!
<img width="334" alt="window_10" src="https://github.com/dotnet/maui/assets/1079689/9f550a76-82e3-4141-a69b-cae63c684155">
![2019](https://github.com/dotnet/maui/assets/1079689/6ccc4a89-17ab-46c0-8107-3963ff6b3824)
Thnaks a lot for you and Lance.

**Comment by LanceMcCarthy** [comment] 2023-11-29 20:50
@danies8 That's great news! 


As you go to implement this on your real app, don't forget there are two parts to the solution:

1. Registering the fonts in your app code

![image](https://github.com/dotnet/maui/assets/3520532/46ca1959-f9ab-4599-89c2-f41017b2e88d)

2. Using `CopyAlways` for the font's TTF file's BuildAction

![image](https://github.com/dotnet/maui/assets/3520532/edf6d1be-2c3d-4bb7-b2be-642d3984a8c0)


I don't know if you still need to use the handler, but just in case, this is the full code from MauiProgram.cs:

```csharp
public static class MauiProgram
{
    public static MauiApp CreateMauiApp()
    {
        var builder = MauiApp.CreateBuilder();
        builder
            .UseMauiApp<App>()
            .ConfigureFonts(fonts =>
            {
                fonts.AddFont("OpenSans-Regular.ttf", "OpenSansRegular");
                fonts.AddFont("OpenSans-Semibold.ttf", "OpenSansSemibold");
                fonts.AddFont("telerikcontrolsicons.ttf", "telerikcontrolsicons");
                fonts.AddFont("telerikfontexamples.ttf", "telerikfontexamples");
            });

#if DEBUG
        builder.Logging.AddDebug();
#endif

#if WINDOWS
        Microsoft.Maui.Handlers.LabelHandler.Mapper.AppendToMapping("FontFamily", (handler, element) =>
        {
            if (element.Font.Family == "telerikcontrolsicons")
            {
                const string FontTelerikControlsIconsFamily = "telerikcontrolsicons.ttf#telerikcontrolsicons";
                handler.PlatformView.FontFamily = new Microsoft.UI.Xaml.Media.FontFamily(FontTelerikControlsIconsFamily);
            }

            if (element.Font.Family == "telerikfontexamples")
            {
                const string FontTelerikControlsIconsFamily = "telerikfontexamples.ttf#telerikfontexamples";
                handler.PlatformView.FontFamily = new Microsoft.UI.Xaml.Media.FontFamily(FontTelerikControlsIconsFamily);
            }
        });
#endif

        return builder.Build();
    }
}
```

**Comment by mattleibow** [comment] 2023-11-29 22:05
Awesome! Windows Server is cool again!

Can we close this issue as all fixed?

**Comment by danies8** [comment] 2023-11-29 22:37
I didn't test it, does we need the handler  as Lance
Wonder ?

**Comment by LanceMcCarthy** [comment] 2023-11-29 23:13
@mattleibow yeah, it's confirmed working, so I would consider this closed.

@danies8 you have a 50/50 chance, it either works with it or not... but you know it's working with one of them 😁

**Comment by danies8** [comment] 2023-11-29 23:28
Tomorrow morning I will check if handler is needed or not and let you know on both machines:
Window 10 +server 2019.

**Closed** 2023-11-30 15:39 UTC
Labels: t/bug, platform/windows 🪟, area/fonts 🅰️, s/needs-attention
