### ISSUE TITLE
8.0.82 to 8.0.90 causes slow down on iOS

### ISSUE THREAD

**Issue by tpitman** [dotnet/maui#25578] opened 2024-10-29 16:36 UTC
### Description

I have a MAUI app that was ported from Xamarin. When I change these 2 lines from version 82 to 90 the app suddenly gets really slow.

```
<PackageReference Include="Microsoft.Maui.Controls" Version="8.0.82" />
<PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="8.0.82" />

to

<PackageReference Include="Microsoft.Maui.Controls" Version="8.0.90" />
<PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="8.0.90" />
```

I originally changed it all the way to 8.0.92 (the latest) because I was told that would solve a totally different issue, but the slow down starts when going from 82 to 90.

I looked through the bug fixes and notes and could not really see anything that seemed directly related.

You can see the slow down between these 2 screen recordings:

Normal using 8.0.82:
https://github.com/user-attachments/assets/87a80daa-dc69-4bb6-9390-1b11c629d534

Slow using 8.0.90:
https://github.com/user-attachments/assets/3962e3d8-8336-4218-a240-40ce81cd9ae8

The "gauges" you see are in a collectionview with the following XAML:

```
<CollectionView Grid.Row="1" x:Name="GaugeListView" MaximumWidthRequest="{Binding ScreenWidth}" ItemTemplate="{StaticResource GaugeDataTemplateSelector}" IsVisible="{Binding GaugeListIsVisible}" SelectionMode="None" Margin="0" ItemsSource="{Binding GaugeList}" BackgroundColor="Transparent" VerticalOptions="FillAndExpand">
	<CollectionView.ItemsLayout>
		<GridItemsLayout Orientation="Vertical" Span="{Binding GaugeCollectionViewSpan}"/>
	</CollectionView.ItemsLayout>
</CollectionView>
```

The ItemTemplate that is visible is this template:

```
<DataTemplate x:Key="DigitalTemplate">
	<Grid IsEnabled="{Binding Source={RelativeSource AncestorType={x:Type vm:GaugeViewModel}}, Path=EditModeIsVisible}" Margin="0" Padding="0" BackgroundColor="Transparent" HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand">
		<Grid BackgroundColor="Transparent" IsVisible="{Binding IsDigital}" Margin="0,10,0,10" HeightRequest="200" HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand">
			<Image Aspect="AspectFit" Source="gauge_rectangle.png" HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand"/>
			<Grid Margin="0" Padding="0" BackgroundColor="Transparent" HorizontalOptions="FillAndExpand" VerticalOptions="Center">
				<Grid.RowDefinitions>
					<RowDefinition Height="Auto"/>
					<RowDefinition Height="Auto"/>
					<RowDefinition Height="Auto"/>
				</Grid.RowDefinitions>
				<Label Grid.Row="0" TextColor="{Binding LabelColor}" Text="{Binding ShortName}" HorizontalOptions="Center" VerticalOptions="End" FontSize="30"/>
				<Label Grid.Row="1" TextColor="{Binding DataColor}" Text="{Binding CurrentValueFormated}" HorizontalOptions="Center" VerticalOptions="Start" FontSize="40"/>
				<Label Grid.Row="2" TextColor="{Binding DataColor}" Text="{Binding UnitsText}" HorizontalOptions="Center" VerticalOptions="Start" FontSize="32"/>
			</Grid>
		</Grid>
		<controls:GaugeEditView BindingContext="{Binding}" BackgroundColor="Transparent" VerticalOptions="End"/>
	</Grid>
</DataTemplate>
```
The value that you see changing is CurrentValueFormated. This property looks like this:

```
        private double _currentValue;
        [XmlIgnore]
        [JsonIgnore]
        public double CurrentValue
        {
            get { return _currentValue; }
            set
            {
                if (_currentValue != value)
                {
                    _currentValue = value;

                    if (_currentValue < MinimumValue)
                        _currentValue = MinimumValue;
                    else if (_currentValue > MaximumValue)
                        _currentValue = MaximumValue;

                    SafePropertyChanged("CurrentValue");
                    SafePropertyChanged("CurrentValueFormated");
                    SafePropertyChanged("Progress");
                }
            }
        }
        [XmlIgnore]
        [JsonIgnore]
        public string CurrentValueFormated { get { return string.Format(FormatString, CurrentValue); } }
```

Kind of old school, but it has worked well and works fine under 8.0.82 so I am hoping I don't have to redo all of my bound properties.

SafePropertyChanged is implemented like this for UI thread safety:

```
        protected void SafePropertyChanged(string name)
        {
            MainThread.InvokeOnMainThreadAsync(() =>
            {
                OnPropertyChanged(name);
            });
        }
```

The app is running in what I call demo mode, so the values are just being randomly generated to exercise the UI using this code:

```
Random.Shared.NextSingle() * (gauge.MaximumValue - gauge.MinimumValue);
```

I know it isn't just the values being generated slower because the whole app is sluggish. If I scroll the CollectionView, for example, it responds very slowly.

There are NO differences in my app or the way I build it besides going from 8.0.82 to 8.0.90 or 92.

This runs at normal speed on Android. It only slows down on iOS.

Any ideas what would cause this and how to fix it?

### Steps to Reproduce

1. Set maui version to 8.0.82
2. Build and run the app on iOS real iPhone
3. Notice the app runs at normal speed
4. Set the maui version to 8.0.90 or 8.0.92
5. Build and run the app on iOS real iPhone
6. Notice the app runs slowly and is sluggish

### Version with bug

8.0.92 SR9.2

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.82 SR8.2

### Affected platforms

iOS

### Affected platform versions

iOS 12 and later

### Did you find any workaround?

Revert to 8.0.82

**Comment by tpitman** [comment] 2024-10-30 13:31
That does seem like it could be a potential cause. Once a release with a fix comes out, I will test it.

**Comment by PureWeen** [comment] 2024-10-30 14:28
Duplicate of #25264

**Closed by PureWeen** 2024-10-30 14:28 UTC
Labels: t/bug, platform/iOS 🍎, potential-regression

**Comment by PureWeen** [comment] 2024-10-30 17:11
@tpitman do you have a repro that I can test?

**Comment by PureWeen** [comment] 2024-11-10 17:25
@tpitman can you test the following nightly build version 

8.0.100-ci.net8.24556.5

**Comment by tpitman** [comment] 2024-11-11 15:33
8.0.100-ci.net8.24556.5 has fixed my issue.

I suspect this will go out with the 8.0.100 release. Any ETA on that release? This is a production app and obviously I don't want to release a new build with unreleased code, right?

**Comment by PureWeen** [comment] 2024-11-12 09:13
@tpitman I'm hoping to push it out this week
