### ISSUE TITLE
If you could I do like to ask you to give it a bit more thought. Are you using this today with another control? What properties would you like to see to influence the clustering behavior? How do you like annotations to work?

### ISSUE THREAD

**Issue by nnikos123** [dotnet/maui#12544] opened 2023-01-10 12:21 UTC
If you could I do like to ask you to give it a bit more thought. Are you using this today with another control? What properties would you like to see to influence the clustering behavior? How do you like annotations to work? 

We want to make sure that we're building the thing you want, please imagine that the feature is already implemented and you're working with it. What does the code that you're writing look like in the ideal case?

_Originally posted by @jfversluis in https://github.com/dotnet/maui/issues/5735#issuecomment-1085680676_

**Comment by nnikos123** [comment] 2023-01-10 12:27
Hi @jfversluis
we are back to the future I presume. 
Since it is very difficult to describe what is needed to have the ability to do clustering (yes in 2023) you could be inspired from 
https://pub.dev/packages/google_maps_cluster_manager, Published [Aug 10, 2021]. 
simply copy that and you done!

**Comment by jfversluis** [comment] 2023-01-10 12:43
Duplicate of #11811

**Closed by jfversluis** 2023-01-10 12:43 UTC
