### ISSUE TITLE
Shell.Set Presentation Mode bug - Android 

### ISSUE THREAD

**Issue by KarlSearl** [dotnet/maui#8110] opened 2022-06-16 12:31 UTC
### Description

Unable to navigate to Modal Pages on Android. 

Tested on Windows and this works as expected. 

IMPORTANT NOTE - Issue is resolved when removing the Shell.PresentationMode="Modal" 

### Steps to Reproduce

1. Create a brand new Maui project.
2. Add a second page and set presentation mode to modal.
3. Register route.
4. Add a button and set the clicked event to   Shell.Current.GoToAsync

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Tested on Android 11 API 30

### Did you find any workaround?

Not yet.

**Comment by dm-pr** [comment] 2022-06-16 12:39
@KarlSearl repo not found, 404

**Comment by KarlSearl** [comment] 2022-06-16 12:44
> 

Sorry, repo set to public.

**Comment by jfversluis** [comment] 2022-06-16 13:17
Duplicate of #8062

**Closed by jfversluis** 2022-06-16 13:17 UTC
Labels: t/bug, s/needs-verification
