### ISSUE TITLE
Windows does not raise Tapped event while Android does.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#24175] opened 2024-08-12 22:20 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Windows-does-not-raise-Tapped-event-whil/10707174)._

---
[severity:It bothers me. A fix would be nice]
When I run this program on Android the Tapped event is triggered but when I run it on Windows it does not.

<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="LarsApp.MainPage">

    <Grid>
        <Grid.ColumnDefinitions>
            <ColumnDefinition Width="100" />
            <ColumnDefinition Width="*"/>
        </Grid.ColumnDefinitions>
        <Grid.RowDefinitions>
            <RowDefinition Height="100" />
            <RowDefinition Height="*" />
        </Grid.RowDefinitions>

        <Rectangle Fill="Green">
            <Rectangle.GestureRecognizers>
                <TapGestureRecognizer Tapped="TapGestureRecognizer_Tapped" />
            </Rectangle.GestureRecognizers>
        </Rectangle>

        <Line X2="100" Y2="100" Stroke="Blue" StrokeThickness="2" />
    </Grid>

</ContentPage>

---
#### Feedback Bot on 7/21/2024, 06:56 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by jfversluis** [comment] 2024-08-13 08:50
Duplicate of #15810

**Closed by jfversluis** 2024-08-13 08:50 UTC
Labels: t/bug
