### ISSUE TITLE
[Windows] New CarouselView item doesn't render unless Window is resized

### ISSUE THREAD

**Issue by rachelkang** [dotnet/maui#17830] opened 2023-10-04 18:27 UTC
### Description

When a new item is added to a CarouselView, the CarouselView does not reflect the updated collection until the window is resized.

### Steps to Reproduce

1. Run recipeSearch repo on rc2
2. Deploy to Windows machine
3. Click on "My Recipes" tab
4. Click "New" button in upper right corner
5. Type anything into Recipe Name field
6. Click "Save"
7. Scroll CarouselView and notice new item is not present
8. Resize window
9. Scroll CarouselView again and notice new item now appears

### Link to public reproduction project repository

https://github.com/rachelkang/recipeSearch

### Version with bug

Unknown/Other

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

**Comment by rachelkang** [comment] 2023-10-04 18:54
reproducible in net7, but even worse on net7 - resizing doesn't render the item either. item doesn't render at all when newly created. It's possible that this is a product of bad code, but the inconsistency in behavior, however both bad, between net7 and net8, is still reason for concern

**Comment by Vroomer** [comment] 2023-10-05 21:56
I suppose this is a duplicate of this: https://github.com/dotnet/maui/issues/17727

**Comment by XamlTest** [comment] 2023-10-10 06:25
Verified this on Visual Studio Enterprise 17.8.0 Preview 2.0(8.0.0-rc.1.9171). Repro on Windows 11 rc1 and rc2 with below Project:
[WhatToEat.zip](https://github.com/dotnet/maui/files/12853479/WhatToEat.zip)

**Closed** 2024-08-06 10:56 UTC
Labels: t/bug, s/duplicate 2️⃣, platform/windows 🪟, area-controls-collectionview, s/verified, s/triaged
