### ISSUE TITLE
Can't center CollectionView within a VerticalLayout or StackLayout on iOS

### ISSUE THREAD

**Issue by fischberg** [dotnet/maui#14731] opened 2023-04-24 01:13 UTC
### Description

If I try to render a horizontally oriented CollectionView within a VerticalStackLayout or StackLayout and set the HorizontalOptions to "Center" for both the CollectionView and the Layouts the CollectionView is left-aligned on iOS. On Android, the CollectionView is properly centered.

I also see that the CollectionView is left-aligned to the edge of the screen even though the left Margin of the VerticalStackLayout is set to 10 on iOS. I note this because it may be related to the issue of non-centering.

I attached screen shots of iPhone and Android emulators demonstrating the issue.

![image](https://user-images.githubusercontent.com/16581942/233875118-7b96d3b0-543e-4b51-9e18-1d56c60df173.png)

### Steps to Reproduce

Build and run the attached application to see the bug as described above.

### Link to public reproduction project repository

https://github.com/fischberg/CollectionViewRepro

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 16.2

### Did you find any workaround?

No

**Comment by fischberg** [comment] 2023-04-24 01:15
Here is the snapshot from an Android emulator:

![Screenshot 2023-04-23 at 8 14 33 PM](https://user-images.githubusercontent.com/16581942/233878568-c77069e8-3e80-4bcb-8f75-4af5b2fc888b.png)

**Comment by fischberg** [comment] 2023-04-24 13:37
One additional point to note...the text "This is the selected item: 2" on Android is centered in the VerticalStackLayout and is not on iOS. It seems the Label object on Android obeys the HorizontalOptions="Center" of the VerticalStackLayout that contains it, but on iOS, the Label ignores the HorizontalOptions="Center" request.

**Comment by hartez** [comment] 2023-05-03 22:40
This is a duplicate of #9135.

The CollectionView is not centering on iOS because it's attempting to take up the entire screen, rather than sizing to just its content.

**Closed by hartez** 2023-05-03 22:40 UTC
Labels: t/bug, area/layout 🔲, platform/iOS 🍎, area/collectionview 📃

**Comment by samhouts** [comment] 2023-05-03 23:46
Duplicate of #9135
