### ISSUE TITLE
iOS and Android in releasemode does not change background color on button when changing states.

### ISSUE THREAD

**Issue by RonnyRos** [dotnet/maui#10335] opened 2022-09-26 21:31 UTC
### Description

   When disabling and enabling a button the buttonbackground color does not change.
   This works fine in debug. .NET 7 RC1.

### Steps to Reproduce

Create a new app project from MAUI template, add a button, use the following style.
Run in release mode, notice background on the button does not update when you toggle IsEnabled property.
To toggle the button i use MVVM community toolkit and [RelayCommand] with CanExecute.

```XAML
<Style x:Key="TestButtonStyle" TargetType="Button">
                <Setter Property="FontSize" Value="18" />
                <Setter Property="BackgroundColor" Value="Lime" />
                <Setter Property="VisualStateManager.VisualStateGroups">
                    <VisualStateGroupList>
                        <VisualStateGroup x:Name="CommonStates">
                            <VisualState x:Name="Normal">
                                <VisualState.Setters>
                                    <Setter Property="FontSize" Value="20" />
                                    <Setter Property="BackgroundColor" Value="Blue" />
                                </VisualState.Setters>
                            </VisualState>
                            <VisualState x:Name="Focused">
                                <VisualState.Setters>
                                    <Setter Property="FontSize" Value="36" />
                                    <Setter Property="BackgroundColor" Value="Red" />
                                </VisualState.Setters>
                            </VisualState>
                            <VisualState x:Name="Disabled">
                                <VisualState.Setters>
                                    <Setter Property="FontSize" Value="10" />
                                    <Setter Property="BackgroundColor" Value="Pink" />
                                </VisualState.Setters>
                            </VisualState>
                        </VisualStateGroup>
                    </VisualStateGroupList>
                </Setter>
            </Style>
```
------
```<Button Style={StaticResource TestButtonStyle}" />```
### Link to public reproduction project repository

none

### Version with bug

.NET 7 RC1.

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

Android 12.1, iOS16.

**Comment by DelphinRP** [comment] 2022-09-27 07:51
Is this the same as #9753?

**Comment by RonnyRos** [comment] 2022-09-27 08:26
Yes seems so.

**Comment by PureWeen** [comment] 2022-09-27 18:21
Duplicate of #9753

**Closed by PureWeen** 2022-09-27 18:21 UTC
Labels: t/bug, area/controls 🎮, control-button
