### ISSUE TITLE
TabBar displays icons incorrectly on iOS.

### ISSUE THREAD

**Issue by ToaRuGakusei** [dotnet/maui#13463] opened 2023-02-21 02:48 UTC
### Description

TabBar displays icons incorrectly on iOS.
This does not happen on Android or Windows.

The code is extracted from the tabbed portion of AppShell.xaml.

```
<TabBar x:Name="tab">
        <ShellContent  Title="ローカルファイル" Icon="folder.png"
                       ContentTemplate="{DataTemplate local:MainPage}"
                       >

        </ShellContent>
        <ShellContent Title="samba" Icon="smb.png" 
                      ContentTemplate="{DataTemplate local:SetSMB}"
                      >

        </ShellContent>
        <ShellContent x:Name="hisotry" Title="履歴" Icon="history.png"
                      ContentTemplate="{DataTemplate local:History}"
                      >

        </ShellContent>
    </TabBar>
```
iOS
<img width="240" alt="image" src="https://user-images.githubusercontent.com/79046275/220232645-786f426c-d70d-4b3a-bfe6-fe59e555b3e6.png">
Android
<img width="324" alt="image" src="https://user-images.githubusercontent.com/79046275/220234201-7649c0e8-f472-4658-b203-a7f62dbc5202.png">
Windows
<img width="710" alt="image" src="https://user-images.githubusercontent.com/79046275/220234284-c0d9c126-f0ab-459a-a3de-2e8e1a56c788.png">

### Steps to Reproduce

```
<?xml version="1.0" encoding="UTF-8" ?>
<Shell
    x:Class="TGReaderGX.AppShell"
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:local="clr-namespace:TGReaderGX"
    FlyoutBehavior="Disabled"
    >
    <Shell.FlyoutHeader>
        <Image Source="flyoutcover"></Image>
    </Shell.FlyoutHeader>

    <TabBar x:Name="tab">
        <ShellContent  Title="ローカルファイル" Icon="folder.png"
                       ContentTemplate="{DataTemplate local:MainPage}"
                       >

        </ShellContent>
        <ShellContent Title="samba" Icon="smb.png" 
                      ContentTemplate="{DataTemplate local:SetSMB}"
                      >

        </ShellContent>
        <ShellContent x:Name="hisotry" Title="履歴" Icon="history.png"
                      ContentTemplate="{DataTemplate local:History}"
                      >

        </ShellContent>
    </TabBar>
</Shell>

```

### Link to public reproduction project repository

https://github.com/ToaRuGakusei/Github_MAUI_TabBar

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS16.2,16.3

**Comment by drasticactions** [comment] 2023-02-21 05:23
Duplicate of https://github.com/dotnet/maui/issues/11984

The iOS/Catalyst TabBar does not set default values for its UIImages contained within it. MAUI doesn't set it either, which is why the icons explode out of the view. If you set the size of the icons, then it should work.

**Closed by drasticactions** 2023-02-21 05:23 UTC
Labels: t/bug, s/duplicate 2️⃣
