### ISSUE TITLE
[iOS/Mac Catalyst] ApplicationTitle is not setting correctly

### ISSUE THREAD

**Issue by mhrastegari** [dotnet/maui#15717] opened 2023-06-18 18:27 UTC
### Summary 
We have several .NET MAUI Blazor projects and we're going to be publish them in Apple store but the `<ApplicationTitle>Bit BlazorUI Demo</ApplicationTitle>` is not setting correctly!
- In `iOS`'s home screen spaces of title ignored and shows `BitBlazorUIDemo` but like in the remove app popup or applications list it shows fine.
- In `Mac Catalyst` it uses the `csproj` name for execute file which is `Bit.BlazorUI.Demo.Client.App` and because the end of it has `App` word it won't show up in `Launchpad`.

### Screenshots
iOS:
![Screenshot 2023-06-18 at 21 35 42](https://github.com/dotnet/maui/assets/42671084/0f18105d-a625-438a-88d8-9565456f413b)

macOS: 
![Screenshot 2023-06-18 at 21 37 59](https://github.com/dotnet/maui/assets/42671084/c303a057-b4ee-41a2-8661-51b82613b914)

### Infos
 .NET: 7.0.304
 macOS: 13.4
 iOS: 16.4
 
 ### Sample repo

[MauiAppTitleIssue.zip](https://github.com/dotnet/maui/files/11789874/MauiAppTitleIssue.zip)

**Comment by drasticactions** [comment] 2023-06-19 03:50
Can you create a project with what values you tried to change and where to reproduce what your screenshots show? It'll help so we can know exactly what you tried to change.

**Comment by mkArtakMSFT** [comment] 2023-06-19 16:33
@drasticactions which area should I move this issue to? Doesn't seem to be Blazor specific.

**Comment by mhrastegari** [comment] 2023-06-19 18:48
Yeah, it's not related to Blazor @jsuarezruiz @mkArtakMSFT

**Comment by mhrastegari** [comment] 2023-10-02 20:35
@drasticactions  Will it be fixed in .NET 8?

**Comment by axylophon** [comment] 2023-10-10 05:42
We have the same issue when setting the <ApplicationTitle> in the csproj file with a space between two words. On iOS the space is then missing.

**Comment by jaosnz-rep** [comment] 2024-01-26 06:58
Verified this issue with Visual Studio for mac 17.6.8 (build 400). Can repro on Android platforms with sample project.
[MauiAppTitleIssue.zip](https://github.com/dotnet/maui/files/11789874/MauiAppTitleIssue.zip)

**Comment by daltzctr** [comment] 2024-05-09 15:41
This is still an issue.

**Comment by daltzctr** [comment] 2024-05-09 16:40
Workaround: https://github.com/dotnet/docs-maui/issues/1843

**Comment by daltzctr** [comment] 2024-05-09 17:17
Another fun tidbit. If the assembly name has spaces in it, it breaks debugging. A simple condition to the property fixes that.

**Comment by daltzctr** [comment] 2024-05-10 16:54
For iOS, the removal of spaces is intended behavior per https://stackoverflow.com/questions/44275567/how-can-i-add-spaces-to-the-app-name

**Comment by rolfbjarne** [comment] 2024-05-20 08:46
This is kind of interesting, on iOS the name of the app bundle isn't visible anywhere for the end user, while for Mac Catalyst it's apparently quite visible.

> Should we come up with a public MSBuild property for this? And then .NET MAUI's `$(ApplicationTitle)` could also set it?

Seems like just making `_AppBundleName` default to `$(ApplicationTitle)` for Mac Catalyst (and macOS as well I suppose) in our props file would do it.

Moving to xamarin/xamarin-macios, because that's where this should be fixed.

**Comment by rolfbjarne** [comment] 2024-05-20 08:47
This issue was moved to xamarin/xamarin-macios#20615

**Closed by rolfbjarne** 2024-05-20 08:47 UTC
Labels: t/bug, platform/macOS 🍏, area-single-project, platform/iOS 🍎, s/verified, s/triaged
