### ISSUE TITLE
RadioButtons are not properly styled in MAUI RC3

### ISSUE THREAD

**Issue by emorell96** [dotnet/maui#7248] opened 2022-05-17 10:31 UTC
### Description

When creating a RadioButton in the MAUI template using the light theme, the radio buttons are not properly shown:

Here you can find a reproduction repo: https://github.com/emorell96/RadioButtonsIosStyle

![radio buttons](https://user-images.githubusercontent.com/20151415/168791087-739dff54-fe3b-4d53-9b48-c94b48675722.jpg)

### Steps to Reproduce

1. Create a new MAUI app in RC3.
2. Add a radio button.
3. Set the theme to light.
4. Launch, see the buttons not appear correctly.
5. The same happens in dark mode, but the text is visible, but not the buttons.

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

ios 15

### Did you find any workaround?

Styling the button, but then there's no margin between the content and the button.

**Comment by jfversluis** [comment] 2022-05-17 11:20
Thanks for the report! I am going to close this one as a duplicate of #7248 just so we don't have the same kind of issues everywhere :)

**Comment by jfversluis** [comment] 2022-05-17 11:21
Duplicate of #7248

**Closed by jfversluis** 2022-05-17 11:21 UTC
Labels: t/bug, s/needs-verification
