### ISSUE TITLE
Scroll view content not rendered properly while dynamically adding the layout on view (iOS and Mac).

### ISSUE THREAD

**Issue by MohanrajSF3559** [dotnet/maui#18750] opened 2023-11-15 11:37 UTC
### Description

Scrollview:

- I had set a width is 300 height is 400 for the custom view.

- While dynamically add the stack layout on view then got a custom view width and height is full screen width and height.

- So that content of the picker scroll view rendered based on the parent width(Example: Full screen width = 1000, Height = 700). 

- So that the scrolling did not work properly in Mac and iOS platforms.

### Steps to Reproduce

1. Run the sample.
2. Check the width and height of the custom view and PickerScrollView.
3.Check the PickerContentView width and height.
4.Click the button to add the stack layout on the view.
5.Check the width and height of the PickerContentView(We got the full screen size instead of custom view width and height).

### Link to public reproduction project repository

https://github.com/dotnet/maui/files/13364011/MacPickerCusIssue.zip

### Version with bug

8.0.0-rc.1.9171

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, macOS

### Affected platform versions

iOS 16.2, Mac OS 12.6.3

### Did you find any workaround?

No

**Comment by e1T** [comment] 2023-11-15 12:01
Could this be similar to this issue https://github.com/dotnet/maui/issues/18207 ?

**Comment by MohanrajSF3559** [comment] 2023-11-24 09:06
Hi @e1T ,
It slightly different.

I had set a parent width is 500. The child (here child is scroll view) width is 200.
The scroll view renderd based on its width(200) properly.
Now content of main page is above.

Dynamically add the stacklayout for the main page. Now the scroll view rendered based on the the parent width(500) instead of scroll view width (200).

**Comment by PureWeen** [comment] 2023-12-19 19:30
Duplicate of #18207

**Closed by PureWeen** 2023-12-19 19:30 UTC
Labels: t/bug, area/layout 🔲

**Comment by MohanrajSF3559** [comment] 2023-12-29 05:10
Reopen
