### ISSUE TITLE
Editor does not resize to full width in a ContentPage.

### ISSUE THREAD

**Issue by RonnyRos** [dotnet/maui#7810] opened 2022-06-07 07:12 UTC
### Description

![image](https://user-images.githubusercontent.com/592363/172318230-c2aae6bb-267e-49a5-89fc-254fcd45e1d7.png)

<Editor
        Grid.Row="1"
        Margin="20,0"
        HorizontalOptions="FillAndExpand"
        Placeholder="Description"
        PlaceholderColor="White"
        Style="{StaticResource EditorBase}"
        Text="{Binding DataModel.Description}">
        <Editor.Behaviors>
            <behaviors:TextValidationBehavior
                Flags="ValidateOnAttaching, ValidateOnValueChanged"
                InvalidStyle="{StaticResource EntryInvalidStyle}"
                IsValid="{Binding IsValidDescription}"
                MinimumLength="4"
                ValidStyle="{StaticResource EditorBase}" />
        </Editor.Behaviors>
    </Editor>
    

### Steps to Reproduce

Contentpage:
<ContentPage
    x:Class="Survey.Pages.PageAddOrUpdateNotes"
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:behaviors="clr-namespace:CommunityToolkit.Maui.Behaviors;assembly=CommunityToolkit.Maui"
    BackgroundColor="Transparent"
    Shell.NavBarIsVisible="False">
    <Grid RowDefinitions="60, *,60">
    
        <Editor
            Grid.Row="1"
            Margin="20,0"
            BackgroundColor="Red"
            HorizontalOptions="FillAndExpand"
            Placeholder="Beskrivelse"
            PlaceholderColor="White"
            Style="{StaticResource EditorBase}"
            Text="{Binding DataModel.Description}">
            <Editor.Behaviors>
                <behaviors:TextValidationBehavior
                    Flags="ValidateOnAttaching, ValidateOnValueChanged"
                    InvalidStyle="{StaticResource EntryInvalidStyle}"
                    IsValid="{Binding IsValidDescription}"
                    MinimumLength="4"
                    ValidStyle="{StaticResource EditorBase}" />
            </Editor.Behaviors>
        </Editor>
</Grid>
</ContentPage>    

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Pixel5-API32,Android12.1

### Did you find any workaround?

No

**Comment by VincentBu** [comment] 2022-06-10 06:49
repro with vs main build 32609.239.
I bind label text with editor input and that is what I get:
![image](https://user-images.githubusercontent.com/44959937/173007384-14db7583-b144-40b9-ac90-ecc73557b59d.png)

**Comment by PureWeen** [comment] 2022-07-28 18:28
Closing as a duplicate of https://github.com/dotnet/maui/issues/8232

**Closed by PureWeen** 2022-07-28 18:28 UTC
Labels: t/bug, area/controls 🎮, s/verified, control-entry
