### ISSUE TITLE
New Item Template for XAML ContentView creates a Resource Dictionary

### ISSUE THREAD

**Issue by codeaphex** [dotnet/maui#6125] opened 2022-04-15 11:30 UTC
### Description

Adding a new .NET MAUI ContentView (XAML) (Preview) creates a ResourceDictionary.
![image](https://user-images.githubusercontent.com/39407721/163565163-7fa7db58-244a-412e-aa89-8623681f3fed.png)
![image](https://user-images.githubusercontent.com/39407721/163565246-cb5653f6-9827-49be-b0b3-3ca405d1fc09.png)

### Steps to Reproduce

1. Right-Click in Solution Explorer
2. Add new item -> .NET MAUI (in C# Items) -> .NET MAUI ContentView (XAML) (Preview) 
3. Add
4. ResourceDictionary gets created.

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS, Other (Tizen, Linux, etc. not supported by Microsoft directly)

### Affected platform versions

Microsoft Visual Studio Community 2022 (64-bit) - Preview Version 17.2.0 Preview 3.0

### Did you find any workaround?

Copy Paste from previous ContentViews
![SparkleSocietyCyrissaGIF](https://user-images.githubusercontent.com/39407721/163565740-5601e091-f818-47f7-b458-128fc8125761.gif)

**Comment by jfversluis** [comment] 2022-04-15 12:12
Hm we should've fixed that... If you go to a terminal window and do `dotnet new maui` does that tell you there is an update available for the templates?

**Comment by codeaphex** [comment] 2022-04-15 13:53
Nope...
![image](https://user-images.githubusercontent.com/39407721/163579171-bc075198-5a9a-4759-b8a5-7ed6a66a9e2a.png)

**Comment by jfversluis** [comment] 2022-04-15 18:47
Could you do `dotnet new -u` that will list all the installed templates. What version does it say for .NET MAUI?

**Comment by codeaphex** [comment] 2022-04-15 18:52
Sure, it shows no items sadly
![image](https://user-images.githubusercontent.com/39407721/163613079-a3b82841-3093-4b3c-bf6d-19ff9413906f.png)

**Comment by drasticactions** [comment] 2022-04-15 20:51
Are there inserted templates in VS that are different from the ones you can install through the workloads? Maybe those were not in sync?

**Comment by codeaphex** [comment] 2022-04-16 08:05
Hmm tried several things yesterday, including repair VS, manually installing workloads^^ and reinstalling VS, now it doesn't work at at all.

**Comment by kristinx0211** [comment] 2022-04-18 05:03
verified not repro on vs 17.3.0 Preview 1.0 [32415.490.main].
![image](https://user-images.githubusercontent.com/99457000/163757281-e1ec06da-e9ca-4135-a34a-1df2ef7fc3ba.png)
![image](https://user-images.githubusercontent.com/99457000/163757294-1956ed06-4c63-431b-8590-fbd4b363bf0f.png)

**Comment by codeaphex** [comment] 2022-04-18 19:56
@kristinx0211 Sry for the dumb question? This means it is already fixed in an internal available VS Preview (vs 17.3.0 Preview 1.0)?
Also nice Font Selection you got there 😱

**Comment by jfversluis** [comment] 2022-04-19 19:22
Sorry for the confusion here! This was already fixed for RC1 but unfortunately it didn't make the release. It will be fixed for the next release and that's also the reason why we can't reproduce it on our latest main version.

When the next release happened and you still have issues, please let us know. Thanks!

**Closed by jfversluis** 2022-04-19 19:22 UTC
Labels: t/bug, area/templates 📄, s/verified

**Comment by janseris** [comment] 2022-04-23 22:09
@jfversluis when can we expect the next release?
