### ISSUE TITLE
[Bug] FilePicker throws COMException on Windows

### ISSUE THREAD

**Issue by orryverducci** [dotnet/maui#2194] opened 2021-08-21 08:28 UTC
### Description

On WinUI projects on the Windows platform, using the `PickAsync` and `PickMultipleAsync` methods from the FilePicker class in Essentials results in a `System.Runtime.InteropServices.COMException` being thrown. The error message returned in the exception is "Invalid window handle. (0x80070578)".

I'm not sure if the issue lies within MAUI or WinUI itself.

### Steps to Reproduce

1. Create a new MAUI project and add a button to the main page
2. Add a clicked event to the button with the following handler method:
    ```csharp
    async private void ButtonClicked(object sender, EventArgs args)
    {
        FileResult file = await FilePicker.PickAsync();
    }
    ```
3. Run the app on Windows and click the button

### Expected Behavior

The file open dialog should appear.

### Actual Behavior

An exception is thrown and the application crashes. 

### Basic Information

- Version with issue: MAUI Preview 7
- Last known good version: Not known
- IDE: Visual Studio 2022 Preview 3.1

**Comment by josephatkuvio** [comment] 2021-08-21 13:27
This appears to be a duplicate of #2102 (an Android bug), but it's interesting that it's also presenting in Windows. 

I wonder if the internals of FilePicker try to store a reference to the parent window? My issue happened with the MSAL authentication library, but only on Android, which needs a parent window reference to properly open the system browser. It did _not_ show up on iOS, which doesn't need that reference. So I'm wondering if the MAUI Parent Window logic is the common thread here.

**Comment by Crauzer** [comment] 2021-09-19 14:34
This also happens for me on .NET 6 RC1 and VS2022 preview.
I have a MAUI Razor app and I'm trying to use the FolderPicker and FilePicker classes from `Windows.Storage.Pickers` but they always throw an exception when you try to call their pick methods.

I've also made sure to initialize the pickers with the HWND of the app window - https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/winrt-com-interop-csharp

**Comment by joshfourbadideas** [comment] 2021-12-02 18:48
Where is this at?  Do we have a timeline for when the fix to these will drop?

**Comment by aokocax** [comment] 2022-01-01 18:32
Hello, I am getting similar error on Windows platform. 
![filepicker](https://user-images.githubusercontent.com/1059475/147857656-90a9e595-3909-429c-98b6-828d6ebb6be5.jpg)
.
When I add this code to Mainactivity on the Android side, the error disappears.
Microsoft.Maui.Essentials.Platform.Init(this, savedInstanceState)
![maaa](https://user-images.githubusercontent.com/1059475/147857688-ff0532e8-f7d6-4897-8f27-8697ba21c8a8.jpg)
;

**Comment by aokocax** [comment] 2022-01-02 20:48
For windows envrionment I was able to run it this way. It works flawlessly with both MAUI and MAUI-Blazor.
<pre>
using Windows.Storage.Pickers;
using WinRT;
using System.Runtime.InteropServices;
public async void File()
{
using var process = Process.GetCurrentProcess();

  var hwnd = process.MainWindowHandle;

  var filePicker = new FileOpenPicker();

  var initializeWithWindow = filePicker.As<IInitializeWithWindow>();
  initializeWithWindow.Initialize(hwnd);
  filePicker.FileTypeFilter.Add("*");

  var folder = await filePicker.PickSingleFileAsync();
}
 [ComImport]
    [Guid("3E68D4BD-7135-4D10-8018-9FB6D9F33FA1")]
    [InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
    public interface IInitializeWithWindow
    {
        void Initialize(IntPtr hwnd);
    }
</pre>
![Ekran görüntüsü 2022-01-02 234523](https://user-images.githubusercontent.com/1059475/147889029-588a65e4-a2cd-4649-a242-7d2ae7a16ff0.jpg)

**Comment by jamesmontemagno** [comment] 2022-01-03 22:14
This should have been fixed with -> https://github.com/dotnet/maui/pull/3232

**Comment by dharber** [comment] 2022-01-07 00:22
I can't tell if Preview 11 got #3232 or not. However, my windows app _is_ throwing a different exception now but that could be other changes in .NET MAUI...who knows?

FilePicker.PickAsync() is now throwing "Source object type is not a projected type and does not inherit from a projected type. (Parameter 'value')"

Is there a way to confirm whether #3232 made it into Preview 11? If not, is there a way to obtain a build of MAUI that does have it? Some kind of nightly build or something?

**Comment by aokocax** [comment] 2022-01-09 07:48
> This should have been fixed with -> #3232
> 
> ```
> var picker = new FileOpenPicker();
> 
> var hwnd = Platform.CurrentWindowHandle;
> WinRT.Interop.InitializeWithWindow.Initialize(picker, hwnd);
> ```
> 
> Should work... You need to add the OnActivated lifecycle event though: https://github.com/jamesmontemagno/maui/blob/b8674a83bac2ee394ff984587e4cfde2c6185bf2/src/Essentials/samples/Samples/Startup.cs
> 
> I tried your code and got an exception though.. maybe something changed in v1 of the app sdk.
> 
> Looking at https://github.com/microsoft/CsWinRT/blob/master/docs/interop.md#windows-sdk this is what we do.... so just not sure if this got merged into P11

I tried but I can't reach the CurrentWindowHandle in my Application. When I look at the source codes, I see that this property is internal. Is there any method to get this property (I added lifecycle event )

**Comment by jamesmontemagno** [comment] 2022-01-14 17:55
Testing with P11 getting, will look as the fix should be in there...:

System.Runtime.InteropServices.COMException: 'Invalid window handle. (0x80070578)
Consider WindowNative, InitializeWithWindow
See https://aka.ms/cswinrt/interop#windows-sdk'

**Comment by AdamBraden** [comment] 2022-01-18 21:24
WinUI3 supports the IWindowNative interface, support is built into the C# WinRT runtime, eg:

var window = new Microsoft.UI.Xaml.Window();
// ...
var hwnd = WinRT.Interop.WindowNative.GetWindowHandle(window);
var folderPicker = new Windows.Storage.Pickers.FolderPicker();
folderPicker.FileTypeFilter.Add("*");
WinRT.Interop.InitializeWithWindow.Initialize(folderPicker, hwnd);
var folder = await folderPicker.PickSingleFolderAsync();

**Comment by jamesmontemagno** [comment] 2022-01-19 18:24
I don't think we want to create a new Window... we would want to use the current Active Window correct....


```csharp
var hwnd = Platform.CurrentWindowHandle;
WinRT.Interop.InitializeWithWindow.Initialize(picker, hwnd);

SetFileTypes(options, picker);

var resultList = new List<StorageFile>();

if (allowMultiple)
{
var fileList = await picker.PickMultipleFilesAsync();
if (fileList != null)
	resultList.AddRange(fileList);
}
else
{
var file = await picker.PickSingleFileAsync();
if (file != null)
	resultList.Add(file);
}
```

And for the `CurrentWindowHandle` we do

```csharp
internal static IntPtr CurrentWindowHandle
			=> WinRT.Interop.WindowNative.GetWindowHandle(CurrentWindow);
```

This is what I do today...

@redth thoughts?

**Comment by AdamBraden** [comment] 2022-01-19 18:41
Yes, if the MAUI code is already tracking the current active window, that should work fine.

**Comment by jamesmontemagno** [comment] 2022-01-19 18:50
@redth just tested on mainline and it was working so doing some debugging around to see if somethign else is going on.

**Comment by orryverducci** [comment] 2022-01-26 07:46
Just tried this again with MAUI Preview 12 / Visual Studio 17.1 Preview 4 and I am now getting a different exception:

`System.ArgumentException: 'Source object type is not a projected type and does not inherit from a projected type. (Parameter 'value')'`

Unfortunately the call stack doesn't provide anything useful, it only shows the method I called `PickMultipleAsync` from marked as external code.

**Comment by shimingsg** [comment] 2022-02-18 09:37
Not reproducible with windows 10.0.19041.

**Closed by shimingsg** 2022-02-18 09:37 UTC
Labels: t/bug, platform/windows 🪟, area/essentials 🍞, s/verified

**Comment by mattleibow** [comment] 2022-11-22 19:33
This is the issue: https://github.com/microsoft/WindowsAppSDK/issues/1063
