### ISSUE TITLE
[Bug] HttpClient crashes on Android

### ISSUE THREAD

**Issue by gviddy** [dotnet/maui#1260] opened 2021-06-11 12:00 UTC
### Description

The app crashes on Android when I try to make an HttpClient call. It works fine on Windows.

### Steps to Reproduce
1,  private readonly HttpClient _httpClient = new HttpClient();
2.  var response = await _httpClient.GetAsync("https://www.google.com.au");
3.  The above line causes the app to crash with no exceptions/errors. Just a clean crash.
4.  Nothing interesting can be seen in the logs.

### Expected Behavior

Expect it to work like it does for Windows. The same code works fine on WinUI3.

### Actual Behavior

Crashes on Android Emulator.

### Basic Information

.NET MAUI Preview 4
maui-check (Everything is OK)

Please note I created the project from Visual Studio 2019 Preview. No other code/xml has been changed.

**Comment by GaryGormley** [comment] 2021-06-14 06:42
I can also confirm this behaviour, but I can't get it to work on WinUI3 either though.
.Net MAUI Preview 4

**Comment by gviddy** [comment] 2021-06-16 09:46
My hope is that preview #5 will support being able to use and access remote APIs. I saw that they demonstrated a weather app at Build 2021, however when I looked at the code I discovered it was all fake. They were not making http client calls either so for whatever reason it appears network functionality is yet to exist. Odd that after 4 previews this isn't something that can be done.

**Comment by GaryGormley** [comment] 2021-06-20 00:34
So, good news and bad news.

Good news is that I successfully downloaded and installed .net maui preview 5, so maui-check reports all is well.
Updated VS 2019 to 16.11.0 preview 2

Bad news is that the same behaviour is observed when trying to make a call to a remote API using HttpClient(checked and it's from .net 6).

**Comment by steaward** [comment] 2021-08-24 02:44
My work around to HttpClient in MAUI right now, is to use `WebRequest`. 

To access internet through Android, you need to set the permissions within your android manifest file:
` <uses-permission android:name="android.permission.INTERNET"></uses-permission>`

After implementing both of these, I can hit 3rd party APIs.

**Comment by titarenko-alexander** [comment] 2021-09-13 18:08
Any updates here?

**Comment by scheidtdav** [comment] 2021-11-10 08:46
Unfortunately the release of preview 10 does not seem to fix this.
Since the debug mode is working fine, my best guess is that there is something wrong with linking.

I found a corresponding issue in dotnet/runtime#60896 which suggests (https://github.com/dotnet/runtime/issues/60896#issuecomment-963376326) to instantiate your HttpClient like this as a workaround: `new HttpClient(new Xamarin.Android.Net.AndroidMessageHandler())`.

I can confirm that this works (make sure to have the `INTERNET` permission set in your manifest)!

This should be fixed by [this commit](https://github.com/xamarin/xamarin-android/commit/ff202f257876912e7151116b350b4d9cef7b694b), but I am not sure when it will be available.

**Comment by jsuarezruiz** [comment] 2021-11-12 07:08
@jonathanpeppers Would https://github.com/xamarin/xamarin-android/commit/ff202f257876912e7151116b350b4d9cef7b694b fix this issue?. Can include a related sample test in the .NET MAUI Gallery to validate it.

**Comment by jonathanpeppers** [comment] 2021-11-12 15:43
Yes, that commit should fix this -- looks like the same issue.

@jsuarezruiz if you added a test that loads an image from a URL on the web -- and then validate it is displayed? Maybe it could just assert there wasn't an error coming through the log.

You'd also need to build the app in `Release` mode.

**Comment by wuyuansushen** [comment] 2021-12-03 12:51
> Unfortunately the release of preview 10 does not seem to fix this. Since the debug mode is working fine, my best guess is that there is something wrong with linking.
> 
> I found a corresponding issue in [dotnet/runtime#60896](https://github.com/dotnet/runtime/issues/60896) which suggests ([dotnet/runtime#60896 (comment)](https://github.com/dotnet/runtime/issues/60896#issuecomment-963376326)) to instantiate your HttpClient like this as a workaround: `new HttpClient(new Xamarin.Android.Net.AndroidMessageHandler())`.
> 
> I can confirm that this works (make sure to have the `INTERNET` permission set in your manifest)!
> 
> This should be fixed by [this commit](https://github.com/xamarin/xamarin-android/commit/ff202f257876912e7151116b350b4d9cef7b694b), but I am not sure when it will be available.

@scheidtdav Could you illustrate how to import the reference to `Xamarin.Android.Net.AndroidMessageHandler` Class? 
I try to use it directly but MAUI said Xamarin is not found...

**Comment by scheidtdav** [comment] 2021-12-03 12:59
@wuyuansushen For me it was simply just a matter of calling the constructor of the message handler.
Since this is Android specific you will need to wrap it in a condition, like so:

```csharp
public HttpClient CreateClient() 
{
#if __ANDROID__
  return new HttpClient(new Xamarin.Android.Net.AndroidMessageHandler());
#else
  return new HttpClient();
#endif
}
```

Hope that helps!

**Comment by wuyuansushen** [comment] 2021-12-04 07:13
> @wuyuansushen For me it was simply just a matter of calling the constructor of the message handler. Since this is Android specific you will need to wrap it in a condition, like so:
> 
> ```cs
> public HttpClient CreateClient() 
> {
> #if __ANDROID__
>   return new HttpClient(new Xamarin.Android.Net.AndroidMessageHandler());
> #else
>   return new HttpClient();
> #endif
> }
> ```
> 
> Hope that helps!

Thanks, Does `Xamarin.Android.Net.AndroidMessageHandler` class need to add addtional `using` statement to refer some addtional assembly ?
I can't find `Xamarin.Android.Net` namespace and `Mono.Android` assembly in **MAUI**.

**Comment by scheidtdav** [comment] 2021-12-06 07:46
No, I don't think it needs additional `using` statements..
Do note though that my project, although being a MAUI project, only targets Android.
Currently I have set `<TargetFramework>net6.0-android</TargetFramework>` in my `.csproj` file. Maybe thats the reason 🤷 

Hope you find a solution!

**Comment by wuyuansushen** [comment] 2021-12-07 07:37
> No, I don't think it needs additional `using` statements.. Do note though that my project, although being a MAUI project, only targets Android. Currently I have set `<TargetFramework>net6.0-android</TargetFramework>` in my `.csproj` file. Maybe thats the reason 🤷
> 
> Hope you find a solution!

@scheidtdav Problem had been resolved. Thanks.

**Closed** 2022-02-10 22:24 UTC
Labels: t/bug, platform/android 🤖, s/needs info ❓, fatal
