### ISSUE TITLE
Issue with VisualStateManager on Windows Platform

### ISSUE THREAD

**Issue by phmeek** [dotnet/maui#12393] opened 2023-01-03 16:28 UTC
### Description

When using the VisualStateManager to specify the colour of selected rows, the colour reverts to the background colour as soon as the mouse cursor is moved away from the control.  I.e. the selected row only shows the selected colour while the mouse cursor is hovering over the selected row.  The background colour selection works as expected on the Android platform (probably because it doesn't have a mouse cursor), but on the Windows platform the selected colour does not remain selected. 

### Steps to Reproduce

1. Create a File > New .NET MAUI App
2. Create a VisualStateGroupList and CollectionView in MainPage.xaml that changes the background colour of a selected item.
3. Run the project under the Windows environment.
4. Select one of the array strings in the list by clicking with the mouse to change the colour to the selection colour.
5. Move the mouse cursor away from the selected item.

### Link to public reproduction project repository

https://github.com/phmeek/VisualStateManagerTest.git

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 11

### Did you find any workaround?

No known workaround.

**Comment by PureWeen** [comment] 2023-01-03 19:08
Duplicate of #11238

**Closed by PureWeen** 2023-01-03 19:08 UTC
Labels: t/bug
