### ISSUE TITLE
System.AccessViolationException when using SwipeView in a CollectionView on Windows - back again

### ISSUE THREAD

**Issue by codemonkey85** [dotnet/maui#9540] opened 2022-08-19 04:18 UTC
### Description

I'm again getting the error 'Attempted to read or write protected memory. This is often an indication that other memory is corrupt.' when using .NET MAUI, targeting Windows, when there is a `<SwipeView>` within a `<CollectionView>`.

I see a number of related issues - it's definitely to do with the `<SwipeView>` control, as commenting it out resolves the issue.

https://github.com/dotnet/maui/issues/6153
https://github.com/dotnet/maui/issues/6401
https://github.com/dotnet/maui/issues/8168

![image](https://user-images.githubusercontent.com/1414036/185541212-99a4e7fa-fa60-4956-93a5-c15993556e61.png)

### Steps to Reproduce

1. Create a File > New .NET MAUI App
2. Add a `<CollectionView>` with a `<SwipeView>` inside of it.
3. Attempt to run the application targeting Windows.

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

net6.0-windows10.0.19041.0

### Did you find any workaround?

Don't use `<SwipeView>` when compiling / running for Windows.

### Relevant log output

```shell
System.AccessViolationException
  HResult=0x80004003
  Message=Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>
```

**Comment by jsuarezruiz** [comment] 2022-08-22 15:11
Same as https://github.com/dotnet/maui/issues/8870

**Comment by jfversluis** [comment] 2022-08-24 12:56
Duplicate of #8870

**Closed by jfversluis** 2022-08-24 12:56 UTC
Labels: t/bug, s/duplicate 2️⃣, platform/windows 🪟, area/SwipeView, high
