### ISSUE TITLE
.Net MAUI WebView inconsistent between iOS and Android

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#21590] opened 2024-04-02 18:05 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Net-MAUI-WebView-inconsistent-between-i/10606424)._

---
[severity:It bothers me. A fix would be nice]
I want to display a particular website via a WebView control. This site displays well in iOS (both physical device and simulator) and in Windows, but in Android (both physical device and emulator) the page appears way too wide so one has to scroll the device to get required data. The website displays fine in Chrome on Android device.

Other sites display OK, so it must be both site-related and WebView-related, as the display is different between Chrome and WebView, and also it works fine under iOS.

Is there something I'm missing? I've simply set the source parameter of the webview in code-behind. I understand that there are Handler.PlatformView.Settings which I can access via a custom webview, which may help, but I can't find any documentation on which settings are actually accessible.

Any hints greatly appreciated.

---
#### Adrian Lewis on 3/3/2024, 09:17 AM: 

(private comment, text removed)
#### Feedback Bot on 3/3/2024, 06:12 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by jfversluis** [comment] 2024-04-03 08:47
From the original feedback issue I see the issue is resolved using:

```csharp
Microsoft.Maui.Handlers.WebViewHandler.Mapper.AppendToMapping("MyCustomization", (Handler, View) =>
        {
            if (View is CustomWebView)
            {
#if ANDROID
              Handler.PlatformView.Settings.UseWideViewPort = true;
              Handler.PlatformView.Settings.LoadWithOverviewMode= true;
              Handler.PlatformView.Settings.BuiltInZoomControls=true;
              Handler.PlatformView.Settings.SetSupportZoom(true);
#endif
            }
}
```

Since we don't have many reports about this I'm going to assume this is an edge case and close this for now.

**Closed by jfversluis** 2024-04-03 08:47 UTC
