### ISSUE TITLE
CarouselView not getting displayed properly with ContentPresenter and ContentView

### ISSUE THREAD

**Issue by mknotzer** [dotnet/maui#23539] opened 2024-07-10 14:58 UTC
### Description

```
<CarouselView.ItemTemplate>
    <DataTemplate>
        <ContentPresenter Content="{Binding .}" />
    </DataTemplate>
</CarouselView.ItemTemplate>
```

[CarouselViewBug.zip](https://github.com/user-attachments/files/16164055/CarouselViewBug.zip)

### Version with bug

8.0.61 SR6.1

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

**Comment by PureWeen** [comment] 2024-07-10 23:54
Duplicate of #18334

**Closed by PureWeen** 2024-07-10 23:54 UTC
Labels: t/bug, platform/windows 🪟
