### ISSUE TITLE
[MAUI] An error NETSDK1082 will happen when opening the existing Projects recipeSearch & ManualMauiTests

### ISSUE THREAD

**Issue by ninachen03** [dotnet/maui#26054] opened 2024-11-22 09:42 UTC
### Description
NETSDK1082:There was no runtime pack for Microsoft.NETCore.App available for the specified RuntimeIdentifier 'iossimulator-x64'. at C:\Program Files\dotnet\sdk\9.0.200-preview.0.24529.19\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targetsfile:
NETSDK1082There was no runtime pack for Microsoft.NETCore.App available for the specified RuntimeIdentifier 'maccatalyst-x64'. af file C:\Program Files\dotnet\sdk\9.0.200-preview.0.24529.19\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets

### Steps to Reproduce

1.Download the project https://github.com/rachelkang/recipeSearch  or https://devdiv.visualstudio.com/Pkgs/_git/VS.TestAssets.Xaml?path=/Assets/Projects/ManualMauiTests and open it in Visual Studio.
2.Observed the Error List.
![Image](https://github.com/user-attachments/assets/91ea0fd9-dad1-4995-8d2f-f551802bdea7)

### Version with bug
· VS Version: 17.13.0 Preview 2.0 [35520.232.main]
· Microsoft.Maui.Controls:  9.0.0
· .NET SDK:   9.0.200-preview.0.24529.19
· Sdk-manifest:  9.0.100
· microsoft.net.sdk.android: 35.0.7
· microsoft.net.sdk.maui: 9.0.0
· microsoft.net.sdk.ios:18.0.9617
· microsoft.net.sdk.Maccatalyst:18.0.9617
microsoft.net.workload.mono.toolchain.current: 9.0.0

### Link to public reproduction project repository

 https://github.com/rachelkang/recipeSearch

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

· VS Version: 17.13.0 Preview 2.0 [35519.241.main]
	· Microsoft.Maui.Controls: 9.0.0
	· .NET SDK:   9.0.200-preview.0.24529.19
	· Sdk-manifest: 8.0.100 & 9.0.100
	· microsoft.net.sdk.android: 35.0.7
	· microsoft.net.sdk.maui: 9.0.0

It seems to have nothing to do with Maui control. I haven't investigated the specific cause of the impact, but I can give you the previous working version.

### Affected platforms

iOS, Android, Windows, macOS

**Comment by jfversluis** [comment] 2024-11-25 11:01
Duplicate of #26092

**Closed by jfversluis** 2024-11-25 11:01 UTC
Labels: t/bug, platform/windows 🪟, platform/android 🤖, platform/iOS 🍎, area-testing, s/verified, s/triaged, csi-new
