### ISSUE TITLE
Many Controls end up preventing Garbage Collection

### ISSUE THREAD

**Issue by michaelstonis** [dotnet/maui#19606] opened 2023-12-28 02:45 UTC
### Description

We have noticed across multiple applications that memory pressure consistently increases until crashing. It appears that this is, in part, related to certain controls not allowing a page to be garbage collected which then has rippling effects (view models, data models, etc.) that prevent any additional objects on that page to be collected.

I've tested this against Android and iOS and the controls that consistently seem to not allow GC are the following:
* ActivityIndicator
* Border
* BoxView
* ImageButton
* Slider
* Stepper
* Switch
* TableView
* ListView (Not in Example)
* CollectionView (Not in Example)

https://github.com/dotnet/maui/assets/120685/95c201d3-83be-4fcc-a7f0-caebc09dd297

Video shows examples of creating controls adding them as the only control on a page, navigating from the page and invoking the GC.

### Steps to Reproduce

1. Click "Go to Page"
2. Select one of the controls listed
3. Navigate back to the home page
4. Click "Cleanup"
5. Observe the console output window for messages like _`GCed page with {Name of View}`_

### Link to public reproduction project repository

[Reproduction Repository](https://github.com/michaelstonis/MauiCleanTest)

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, I was *not* able test on other platforms

**Comment by drasticactions** [comment] 2023-12-28 03:51
You listed an example but didn't link it. Could you link it please?

**Comment by drasticactions** [comment] 2023-12-28 03:53
Also, my guess is that this is a duplicate of https://github.com/dotnet/maui/issues/18365, which covers the same topic.

**Comment by michaelstonis** [comment] 2023-12-28 16:07
@drasticactions sorry about that. Link updated and provided here https://github.com/michaelstonis/MauiCleanTest.

I think that this is the same/similar as #18365 I had not found that one when searching before posting this though. The only difference, if anything, is that I am seeing it on iOS, Mac Catalyst, and Android.

**Comment by Zhanglirong-Winnie** [comment] 2024-04-03 08:28
Verified this issue with Visual Studio 17.6.10(build428) (8.0.14). Not repro this issue with sample project. 
![image](https://github.com/dotnet/maui/assets/77434865/819ca252-5762-49d6-81db-e46fa6b331c2)

**Closed** 2024-04-10 09:45 UTC
Labels: t/bug, platform/android 🤖, platform/iOS 🍎, s/triaged, s/needs-attention, s/try-latest-version, migration-compatibility, potential-regression
