### ISSUE TITLE
DatePicker and TimePicker Focused and Unfocused events do not fire

### ISSUE THREAD

**Issue by bzd3y** [dotnet/maui#21221] opened 2024-03-14 22:53 UTC
### Description

The `Focused` and `Unfocused` events for `TimePicker` and `DatePicker` do not fire when the controls get and lose focus.

I have tested this in Android, but not iOS, so it may work in iOS.

### Steps to Reproduce

1. Clone the reproduction repository.
2. Set a breakpoint on the events in Focused/MainPage.xaml.cs
3. Run the Focused project
4. Click in the controls at the bottom of the page to give them focus. Select a value or cancel out of the dialog. Click the button above them so they lose focus.

### Link to public reproduction project repository

https://github.com/bzd3y/ReproductionProject

### Version with bug

8.0.7 SR2

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 14

### Did you find any workaround?

No.

**Comment by Zhanglirong-Winnie** [comment] 2024-03-15 04:44
Verified this issue with Visual Studio 17.10.0 Preview 2. Can repro on Android platform with sample project. Windows works fine.
https://github.com/bzd3y/ReproductionProject

**Comment by PureWeen** [comment] 2024-03-15 15:46
Duplicate of #18797

**Closed by PureWeen** 2024-03-15 15:46 UTC
Labels: t/bug, s/verified, s/triaged

**Comment by bzd3y** [comment] 2024-03-18 12:47
@PureWeen Sorry, I searched, but apparently not well enough. Thanks!
