### ISSUE TITLE
.NET 8 RC1 - Native AOT does not work with startup Blazor MAUI App

### ISSUE THREAD

**Issue by strich** [dotnet/maui#17715] opened 2023-09-28 12:57 UTC
### Description

I wanted to see if Blazor MAUI works well with native AOT and almost immediate ran into a showstopper when trying with the start up project after adding:
	<PropertyGroup>
		<PublishAot>true</PublishAot>
	</PropertyGroup>

This is the compile error after running `dotnet publish -f net8.0-windows10.0.19041.0`:

```
error NU1101: Unable to find package runtime.linux-arm.Microsoft.DotNet.ILCompiler. No packages exist with this id in source(s): C:\Program Files\dotnet\library-packs, Microsoft Visual Studio Offline Packages, nuget.org
```

UPDATE 1:
I removed all the framework platform support in the csproj except for Windows (but why was it trying to compile for linux??) and now get this error at a later build stage:
```
EXEC : error : Specified cast is not valid. [D:\Programming\NET8MAUIBlazorApp\NET8MAUIBlazorApp\NET8MAUIBlazorApp.csproj::TargetFramework=net8.0-windows10.0.19041.0]
  System.InvalidCastException: Specified cast is not valid.
     at System.Runtime.TypeCast.ThrowInvalidCastException(MethodTable*) + 0x16
     at ILCompiler.MetadataManager.IsReflectionBlocked(TypeDesc) + 0x132
     at ILCompiler.MetadataManager.IsReflectionBlocked(Instantiation) + 0x3d
     at ILCompiler.MetadataManager.IsReflectionBlocked(TypeDesc) + 0xfc
     at ILCompiler.UsageBasedMetadataManager.HasConditionalDependenciesDueToEETypePresence(TypeDesc) + 0xee
     at ILCompiler.DependencyAnalysis.EETypeNode..ctor(NodeFactory, TypeDesc) + 0xff
     at ILCompiler.DependencyAnalysis.NodeFactory.CreateNecessaryTypeNode(TypeDesc) + 0xfa
     at Internal.TypeSystem.LockFreeReaderHashtable`2.CreateValueAndEnsureValueIsInTable(TKey) + 0x11
     at ILCompiler.DependencyAnalysis.NodeFactory.NecessaryTypeSymbol(TypeDesc) + 0xe7
     at ILCompiler.DependencyAnalysis.NonGCStaticsNode.GetConditionalStaticDependencies(NodeFactory) + 0x32
     at ILCompiler.DependencyAnalysisFramework.DependencyAnalyzer`2.GetStaticDependenciesImpl(DependencyNodeCore`1) + 0xf3
     at ILCompiler.DependencyAnalysisFramework.DependencyAnalyzer`2.GetStaticDependencies(DependencyNodeCore`1) + 0x2b
     at ILCompiler.DependencyAnalysisFramework.DependencyAnalyzer`2.ProcessMarkStack() + 0xb5
     at ILCompiler.DependencyAnalysisFramework.DependencyAnalyzer`2.ComputeMarkedNodes() + 0x50
     at ILCompiler.ILScanner.ILCompiler.IILScanner.Scan() + 0x14
     at ILCompiler.Program.<Run>g__RunScanner|4_0(Program.<>c__DisplayClass4_0&) + 0x191
     at ILCompiler.Program.Run() + 0x2444
     at ILCompiler.ILCompilerRootCommand.<>c__DisplayClass221_0.<.ctor>b__0(ParseResult result) + 0x315
```

### Steps to Reproduce

1. Create a new Blazor MAUI app in VS Preview
2. Add this to csproj:
```
	<PropertyGroup>
		<PublishAot>true</PublishAot>
	</PropertyGroup>
```

4. Run `dotnet publish -f net8.0-windows10.0.19041.0`

### Version with bug

8.0.0-rc.1.9171

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

**Comment by drasticactions** [comment] 2023-09-28 14:09
Duplicate of https://github.com/dotnet/maui/issues/17713, same error happens in both.

**Closed by drasticactions** 2023-09-28 14:09 UTC
Labels: t/bug
