### ISSUE TITLE
[iOS] Shell ignores FlyoutBehavior property.

### ISSUE THREAD

**Issue by AidarNurmukhametov** [dotnet/maui#5663] opened 2022-03-30 11:32 UTC
### Description

Setting FlyoutBehavior to Disabled does no impact on iOS platform, so FlyoutContent is showing on entire screen as it described in #5550

### Steps to Reproduce

1. Clone repository https://github.com/AidarNurmukhametov/shellBug
2. Build and deploy for net6.0-ios target. I used _dotnet build -t:Run -f:net6.0-ios_ command.

### Version with bug

Preview 14 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15.2

### Did you find any workaround?

I can't find any workaround at all

**Comment by jfversluis** [comment] 2022-03-30 12:11
As you already mentioned in the linked issue there was a problem with Shell in that regard. This is already fixed and will be released as part of the next preview. Closing this for now assuming that the problem is related to that.

If you have updated to the next release and this is still an issue, please let us know. Thanks!

**Closed by jfversluis** 2022-03-30 12:11 UTC
Labels: t/bug, s/needs-verification
