### ISSUE TITLE
Xaml for MAUI tvOS and Android TV

### ISSUE THREAD

**Issue by jrahma** [dotnet/maui#9829] opened 2022-08-31 21:29 UTC
### Description

Hi,

Currently the tvOS development is between the Visual Studio and the Xcode's storyboard

I would suggest we should be able to have Xaml files in tvOS with Maui controls so we can use the Visual Studio without the Xcode just like the iOS apps.

Same thing for the Android TV.

### Public API Changes

File Suggestion.

### Intended Use-Case

Sugestion

**Comment by jfversluis** [comment] 2022-09-01 08:01
Duplicate of #2974

**Closed by jfversluis** 2022-09-01 08:01 UTC
Labels: t/enhancement ☀️, proposal/open
