### ISSUE TITLE
Custom Font is not fully supported on real Android Device

### ISSUE THREAD

**Issue by ShariatPanah** [dotnet/maui#20744] opened 2024-02-21 11:12 UTC
### Description

so i have added my fonts to resources, the font includes Farsi Numbers.
on an android emulator (Android 12.0) the font applies to all letters and numbers as expected, but on a real device (Huawei Mate 10 Lite with Android 8.0) it just applies to letters and not to numbers. i attach some screenshot:

![image](https://github.com/dotnet/maui/assets/32509267/6ae6895b-a2f9-4d86-b903-d1111a6949e6)

i have already opened an issue similar to this one, [#19935](https://github.com/dotnet/maui/issues/19935) so maybe related?

### Version with bug

8.0.6 SR1

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 8.0 and 12.0

**Comment by drasticactions** [comment] 2024-02-21 14:23
Yeah, I think it will most likely be the same issue. When that gets addressed, if this is still an issue, you can reopen it.

Duplicate of https://github.com/dotnet/maui/issues/19935

**Closed by drasticactions** 2024-02-21 14:23 UTC
Labels: t/bug
