### ISSUE TITLE
[Windows] App Icon behaves randomly

### ISSUE THREAD

**Issue by janseris** [dotnet/maui#7200] opened 2022-05-15 14:47 UTC
### Description

![image](https://user-images.githubusercontent.com/64279914/168478823-c837f68e-9ac0-43f3-b459-890d62a4f4e6.png)

Edit: the issue might be that for the same project, the app icon is cached somewhere in Windows and I cannot change it. I am changing the image and it keeps showing the old image. I am deleting `bin` and `obj` folders upon each try.

Edit2:
It broke even more (see that there is blue background behind the red "background" and **the image is wrong** (or more precisely, I might have been using a .png until a few days ago, that would explain the image working in colors at the first try (while being cached from previous days))!:
![image](https://user-images.githubusercontent.com/64279914/168479337-dabc9c5f-78ce-4b54-98b4-c4a67bd771e1.png)

Edit3:
_**The colors don't match at all.**_
I am deleting `bin` and `obj` folders upon each try.
![image](https://user-images.githubusercontent.com/64279914/168479576-11bd7ad9-066c-4490-9b53-e195c664cbbb.png)

This does not fix after VS restart and yet another `bin` and `obj` folders deleting.

Edit4:
This doesn't fix after uninstalling the application package manually through Windows 10 Settings -> Applications.
The icon is broken in taskbar and background color is different in the Windows 10 Settings -> Applications menu.
![image](https://user-images.githubusercontent.com/64279914/168479806-5ba15608-9f1e-468b-ab16-8d59e078d01f.png)

Edit5: while svg turns black on Android, it works on Windows (got back the colorful image on blue background).

### Steps to Reproduce

Try define Color or TintColor on MauiIcon tag

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

latest

**Comment by VincentBu** [comment] 2022-06-27 06:36
Hi [janseris](https://github.com/janseris), would you like to share your svg file?

**Comment by janseris** [comment] 2022-06-27 06:59
Hi, it's here: https://github.com/dotnet/maui/issues/7204

**Comment by VincentBu** [comment] 2022-06-28 01:21
Verified with vs main build
On taskbar:
![image](https://user-images.githubusercontent.com/44959937/176066355-46af8dee-abc9-4aac-acaa-62248bc66c46.png)

In Apps & features:
![image](https://user-images.githubusercontent.com/44959937/176066453-5871ce89-6bce-4c19-90be-c4701a050bc7.png)

**Comment by designtechemanuel** [comment] 2022-07-04 17:23
Seems related to #5162.

**Comment by mattleibow** [comment] 2022-08-31 03:59
Thanks @designtechemanuel! This is indeed a duplicate of https://github.com/dotnet/maui/issues/5162.

**Closed by mattleibow** 2022-08-31 03:59 UTC
Labels: t/bug, area/single project ☝️, platform/windows 🪟, s/verified, s/triaged
