### ISSUE TITLE
MAUI fails to hide keyboard in android when text view control closes the input 

### ISSUE THREAD

**Issue by liveinvarun** [dotnet/maui#11047] opened 2022-11-01 20:12 UTC
https://user-images.githubusercontent.com/8180770/199331803-4c456a38-08b6-469c-96b2-f6164790ca9a.mov

### Description

The application backstack page is shown when the keyboard collapses and the background page interaction is active.

please see the video attached.

https://user-images.githubusercontent.com/8180770/199331803-4c456a38-08b6-469c-96b2-f6164790ca9a.mov

### Steps to Reproduce

Sample demos the issue in detail

### Link to public reproduction project repository

https://github.com/liveinvarun/MauiRepo/tree/main/TabbedPageIssue

### Version with bug

7.0 Release Candidate 2

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

ios 15, android 11 +

### Did you find any workaround?

No

### Relevant log output

```shell
NO
```

**Comment by AndreasReitberger** [comment] 2022-11-02 05:11
Seems to be a duplicate of https://github.com/dotnet/maui/issues/10978

**Comment by PureWeen** [comment] 2022-11-02 19:15
Duplicate of #10978

**Closed by PureWeen** 2022-11-02 19:15 UTC
Labels: t/bug, s/duplicate 2️⃣, area/layout 🔲, area/controls 🎮, control-entry
