### ISSUE TITLE
Updating to .NET MAUI 6.0.486 clears Preferences to Type Defaults on WinUI

### ISSUE THREAD

**Issue by dg2k** [dotnet/maui#9210] opened 2022-08-05 05:53 UTC
### Description

As described in the title, and more [details here](https://docs.microsoft.com/en-us/answers/questions/954187/is-the-clearing-of-microsoftmauistoragepreferences.html).

This is also confirmed (in same link provided) by a Microsoft employee who answered a question relating to the issue.

### Steps to Reproduce

No coding steps are relevant here for reproduction.

Simply update to Maui 6.0.486 with Visual Studio ver 17.3.0 Preview 6.0.

No similar issues with version 6.0.419 and previous.

### Version with bug

6.0.408 (current)

### Last version that worked well

6.0.400

### Affected platforms

Windows

### Affected platform versions

Windows 10 SDK

### Did you find any workaround?

Yes, but would be messy. The issue is that of settings supposed to be persisted  being not persisted which can have serious consequences.

This may also affect?? SecureStorage secrets based on Preferences??  but I  haven't checked this one.

**Comment by KMRH47** [comment] 2022-08-05 11:35
I'm facing the same issue after upgrading Visual Studio from `17.3.0 Preview 5` to `17.3.0 Preview 6`.

[I've a simple created a repro.](https://github.com/KMRH47/PreferencesGetDefaultValueNull)

**Comment by jfversluis** [comment] 2022-08-12 09:44
Duplicate of #9338 and fixed with #9361

**Closed by jfversluis** 2022-08-12 09:44 UTC
Labels: t/bug, s/needs-verification
