### ISSUE TITLE
Shell.Toolbaritems don't appear on iOS

### ISSUE THREAD

**Issue by ArchangelWTF** [dotnet/maui#13198] opened 2023-02-08 12:50 UTC
### Description

I've ran into an issue which I believe to be a bug, on Android my code seems to work completely fine however on iOS the items in the toolbar simply dont show up.

### Steps to Reproduce

1. Create a new MAUI solution
2. Modify AppShell to include toolbar items
3. Toolbar items don't show on iOS but do on Android (Screenshots below)

| Android | iOS |
| :-: | :-: |
| ![Screenshot_1675859894](https://user-images.githubusercontent.com/5050464/217534066-8b05bd68-4cdf-4c86-b1c2-52a5b7158537.png) | ![IMG_0008](https://user-images.githubusercontent.com/5050464/217534256-5c38e0a3-d85c-4425-8e05-4debb1fb315f.PNG) |

### Link to public reproduction project repository

https://github.com/ArchangelWTF/ToolbarItemsSample

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

Observed on iOS 16.3

**Comment by mattleibow** [comment] 2023-02-08 16:49
Duplicate of https://github.com/dotnet/maui/issues/7328

**Closed** 2023-02-08 16:50 UTC
Labels: t/bug
