### ISSUE TITLE
Ran out of trampolines of type 0 running on iPhone iOS 15.5 simulator

### ISSUE THREAD

**Issue by SimenCTan** [dotnet/maui#8970] opened 2022-07-25 05:16 UTC
### Description

After I launch my app and run it in debug mode on iPhone iOS 15.5 simulator for a while, the app crashes when I click on other tab. 

The error log shows that
`Ran out of trampolines of type 0 in
 '*/CoreSimulator/Devices/F06D2CC0-2EEA-4C06-B672-721C0A277327/
data/Containers/Bundle/Application/C9EA73F5-9801-4F0C-93D3-302108B93249/
*.app/System.Private.CoreLib.dll'  (limit 4096). See http://docs.xamarin.com/ios/troubleshooting for instructions on how to fix this condition.`
I didn't find any useful information based on this tip link.

In Debug mode on Android Emulator work well.

### Steps to Reproduce

1.Build and run a large app with the iOS simulator

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15

### Did you find any workaround?

[Ran out of trampolines of type 1 running on x64 simulator](https://github.com/dotnet/runtime/issues/68808)

### Relevant log output

```shell
error: Ran out of trampolines of type 0 in 
'/.../Devices/DD30D958-E148-429A-851A-2F0D22491F4A/data/Containers/Bundle/Application/842C0600-8A67-4EF8-9860-F33D35E9F80C/ApprovalMars.App.app/System.Private.CoreLib.dll' (limit 4096). 
See http://docs.xamarin.com/ios/troubleshooting for instructions on how to fix this condition.

=================================================================
	Native Crash Reporting
=================================================================
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

=================================================================
	Native stacktrace:
=================================================================

=================================================================
	Basic Fault Address Reporting
=================================================================
Memory around native instruction pointer (0x7fff7017300e):0x7fff70172ffe  ff ff c3 90 90 90 b8 48 01 00 02 49 89 ca 0f 05  .......H...I....
0x7fff7017300e  73 08 48 89 c7 e9 ad a1 ff ff c3 90 90 90 b8 53  s.H............S
0x7fff7017301e  00 00 02 49 89 ca 0f 05 73 08 48 89 c7 e9 95 a1  ...I....s.H.....
0x7fff7017302e  ff ff c3 90 90 90 b8 83 01 00 02 49 89 ca 0f 05  ...........I....

=================================================================
	Managed Stacktrace:
=================================================================
	  at <unknown> <0xffffffff>
	  at System.Delegate:CreateDelegate_internal <0x0002e>
	  at System.Delegate:CreateDelegate <0x001bc>
	  at System.Delegate:CreateDelegate <0x00022>
	  at System.Delegate:CreateDelegate <0x0001c>
	  at System.Reflection.RuntimeMethodInfo:CreateDelegate <0x00018>
	  at Microsoft.AspNetCore.Components.Reflection.PropertySetter:.ctor <0x0069a>
	  at Microsoft.AspNetCore.Components.ComponentFactory:CreateInitializer <0x00102>
	  at Microsoft.AspNetCore.Components.ComponentFactory:PerformPropertyInjection <0x0004c>
	  at Microsoft.AspNetCore.Components.ComponentFactory:InstantiateComponent <0x000de>
	  at Microsoft.AspNetCore.Components.RenderTree.Renderer:InstantiateComponent <0x00026>
	  at Microsoft.AspNetCore.Components.RenderTree.WebRenderer:AddRootComponent <0x0001a>
	  at Microsoft.AspNetCore.Components.WebView.Services.WebViewRenderer:AddRootComponent <0x00018>
	  at <AttachToPageAsync>d__20:MoveNext <0x00282>
	  at System.Runtime.CompilerServices.AsyncMethodBuilderCore:Start <0x00062>
	  at Microsoft.AspNetCore.Components.WebView.WebViewManager:AttachToPageAsync <0x00090>
	  at <OnMessageReceivedAsync>d__2:MoveNext <0x000c6>
	  at System.Runtime.CompilerServices.AsyncMethodBuilderCore:Start <0x00062>
	  at Microsoft.AspNetCore.Components.WebView.IpcReceiver:OnMessageReceivedAsync <0x00090>
	  at <<MessageReceived>b__0>d:MoveNext <0x00064>
	  at System.Runtime.CompilerServices.AsyncMethodBuilderCore:Start <0x00062>
	  at <>c__DisplayClass18_0:<MessageReceived>b__0 <0x00070>
	  at <<DispatchAsync>b__0>d:MoveNext <0x00040>
	  at System.Runtime.CompilerServices.AsyncMethodBuilderCore:Start <0x00062>
	  at <>c__DisplayClass3_0:<DispatchAsync>b__0 <0x00070>
	  at <<DispatchAsync>b__0>d:MoveNext <0x00046>
	  at System.Runtime.CompilerServices.AsyncMethodBuilderCore:Start <0x00062>
	  at <>c__DisplayClass2_0`1:<DispatchAsync>b__0 <0x0006c>
	  at <>c__DisplayClass9_0:<DispatchImplementation>b__0 <0x0001a>
	  at CoreFoundation.DispatchQueue:static_dispatcher_to_managed <0x000e4>
	  at CoreFoundation.DispatchQueue:static_dispatcher_to_managed <0x00054>
	  at <unknown> <0x00000>
	  at <unknown> <0xffffffff>
	  at UIKit.UIApplication:UIApplicationMain <0x0011e>
	  at UIKit.UIApplication:Main <0x0010e>
	  at ApprovalMars.App.Program:Main <0x0001e>
	  at <Module>:runtime_invoke_direct_void_string[] <0x0004a>
	  at <unknown> <0x00000>
=================================================================
```

**Comment by jfversluis** [comment] 2022-07-25 14:52
Looks like a duplicate of: https://github.com/xamarin/xamarin-macios/issues/14855

This is not specific to .NET MAUI and it seems a fix might be underway already :)

**Closed by jfversluis** 2022-07-25 14:52 UTC
Labels: t/bug, s/needs-verification

**Comment by SimenCTan** [comment] 2022-07-26 05:04
> Looks like a duplicate of: [xamarin/xamarin-macios#14855](https://github.com/xamarin/xamarin-macios/issues/14855)
> 
> This is not specific to .NET MAUI and it seems a fix might be underway already :)

* It looks like the bug has been fixed, but the patch hasn't been released
