### ISSUE TITLE
Input in Entry filed with Keyboard="Numeric" does not accept "," input

### ISSUE THREAD

**Issue by FrankPohl** [dotnet/maui#12424] opened 2023-01-05 09:08 UTC
### Description

On Android, input of decimals in an entry field is not possible for culture that use a "," as the decimal separator if the Keyboard "Numeric" is used.
The "," button on the input panel is not accepted as an input.

### Steps to Reproduce

1. Create a new MAUI project
2. Add an Entry field with the Keyboard set to "Numeric"
3. Start it on a German Android version.
4. Open the input keyboard and try to enter 2,57
5. The comma is ignored.

### Link to public reproduction project repository

https://github.com/FrankPohl/InputTest.git

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android Framework 29

### Did you find any workaround?

No workaround with "Numeric" keyboard found. Can use Default keyboard and enter number with that.

**Comment by FM1973** [comment] 2023-01-07 08:01
I can confirm this.

**Comment by UkeHa** [comment] 2023-01-25 13:41
Yup, this also affects us.

**Comment by rachelkang** [comment] 2023-03-30 20:53
Duplicate of #7582

**Closed by rachelkang** 2023-03-30 20:53 UTC
Labels: t/bug, platform/android 🤖, area/controls 🎮, keyboard
