### ISSUE TITLE
[WinUI] FlyoutHeader displays no image (svg)

### ISSUE THREAD

**Issue by FroggieFrog** [dotnet/maui#13242] opened 2023-02-10 09:48 UTC
#### Update

I just found out that you have to reference the image as `.png` instead of `.svg`.
This is mentioned in docs: https://learn.microsoft.com/en-us/dotnet/maui/user-interface/images/images

So with `.png` it is also working on WinUI. But the image is kind of blurry.
Not sure if this is still a bug or can be closed. Maybe an analyzer or so could check for this type of (user/developer) error.

---

### Description

The Flyout Header shows no image on `WinUI` but does on `Android`.

### Steps to Reproduce

1. Create new MAUI app
2. adjust `AppShell.xaml` [according to the docs](https://learn.microsoft.com/en-us/dotnet/maui/fundamentals/shell/flyout?view=net-maui-7.0#flyout-header)
3. run on Android Emulator -> image is shown
4. run on Windows -> no image is shown

edits on `AppShell.xaml`:
```diff
<?xml version="1.0" encoding="UTF-8" ?>
<Shell
    x:Class="MauiApp2.AppShell"
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:local="clr-namespace:MauiApp2"
+    Shell.FlyoutBehavior="Flyout">
+
+    <Shell.FlyoutHeaderTemplate>
+        <DataTemplate>
+            <Grid BackgroundColor="Black"
+                  HeightRequest="200">
+                <Image Aspect="AspectFill"
+                       Source="dotnet_bot.svg"
+                       Opacity="0.6" />
+                <Label Text="Animals"
+                       TextColor="White"
+                       FontAttributes="Bold"
+                       HorizontalTextAlignment="Center"
+                       VerticalTextAlignment="Center" />
+            </Grid>
+        </DataTemplate>
+    </Shell.FlyoutHeaderTemplate>

    <ShellContent
        Title="Home"
        ContentTemplate="{DataTemplate local:MainPage}"
        Route="MainPage" />

</Shell>
```

### Link to public reproduction project repository

https://github.com/FroggieFrog/bug-maui-flyout-header-no-image

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

microsoft.windowsappsdk: 1.2.221109.1

### Did you find any workaround?

No

**Comment by ne0rrmatrix** [comment] 2023-02-10 17:11
You need to use .png when loading svg images. Can you try changing file extension to png in xaml and see if that resolves your issue?

**Comment by FroggieFrog** [comment] 2023-02-10 18:24
As noted in the Update above this solves the problem, but I'm not sure if it is an issue, because on Android it is working.

> So with .png it is also working on WinUI. But the image is kind of blurry.
> Not sure if this is still a bug or can be closed. Maybe an analyzer or so could check for this type of (user/developer) error.

**Comment by ne0rrmatrix** [comment] 2023-02-10 19:04
The fact specifying a SVG instead of using the extension PNG is an accident and not intended behavior. It works intermittently and was not intended to work. The SVG is in fact converted to PNG during compile. This is unintended behavior in MAUI and I don't know when or if they will fix it.

Again I will reiterate it is unintended that this works at all with SVG being specified.

**Comment by PureWeen** [comment] 2023-02-16 19:19
Duplicate of #7066

**Closed by PureWeen** 2023-02-16 19:19 UTC
Labels: t/bug, platform/windows 🪟, area/shell 🐢, control-flyout
