### ISSUE TITLE
MenuBarItems Command is not executed. (Verified on Windows)

### ISSUE THREAD

**Issue by VladislavAntonyuk** [dotnet/maui#7024] opened 2022-05-11 10:10 UTC
### Description

MenuBarItems Command is not executed. (Verified on Windows)

### Steps to Reproduce

1. Create default .NET MAUI application
2. On MainPage set MenuBarItems:
```
<ContentPage.MenuBarItems>
		<MenuBarItem Text="File">
			<MenuFlyoutItem Text="New" Command="{Binding NewCommand}"/>			
		</MenuBarItem>
	</ContentPage.MenuBarItems>
```

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 19041

### Did you find any workaround?

Set Clicked event and call command

**Comment by VladislavAntonyuk** [comment] 2022-05-11 10:13
Sample: https://github.com/VladislavAntonyuk/MauiSamples/blob/main/MauiPaint/MainPage.xaml#L12

**Comment by mattleibow** [comment] 2022-05-11 10:15
Duplicate of #5382

**Closed by mattleibow** 2022-05-11 10:15 UTC
Labels: t/bug, s/needs-verification

**Comment by IndexOutOfLimit** [comment] 2022-05-20 05:19
Can anyone please let me know when we can get permanent fix for this as this is violating MVVM pattern.

**Comment by mattleibow** [comment] 2022-05-20 05:55
You can follow the linked issue for updates.
