### ISSUE TITLE
iOS not show splash screen 

### ISSUE THREAD

**Issue by Hardikzinzala** [dotnet/maui#20171] opened 2024-01-26 07:20 UTC
### Description

- I am working with .net maui 8 .
- when i try to launch my app on iOS so that not show splash screen only show black screen.
- But android work properly

### Version with bug

8.0.6

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.101

### Affected platforms

iOS

**Comment by jfversluis** [comment] 2024-01-26 09:29
What version of Visual Studio are you using? What have you already tried and didn't work? Have you tried on the Simulator or also a physical device? What version of iOS? If you want us to diagnose this properly and help you we're going to need a bit more detail I'm afraid 😄 

Thanks!

**Comment by Cr15Denis** [comment] 2024-01-31 02:17
Hello, I also have the same problem with the iOS splash screen, now I am using vs code but it also gives the problem in visual studio mac. I have everything updated to .net 8, I have done clean installations but nothing.


https://github.com/dotnet/maui/assets/70722700/37b00ab8-a3c2-44d3-a897-a1787373535e

**Comment by Baraiboapex** [comment] 2024-03-05 21:01
@Hardikzinzala I was following this tutorial video:

 https://www.youtube.com/watch?v=xkHNbrpi3ZQ 

and from it I learned that as of iOS 16.4 (probably) you will NOT be able to see your splash screen on an IOS simulator. Therefore, the code containing your splash screen must be codesigned first before you can view it (for some reason). If you have access to a physical device for testing, that would be your best bet to view it.

**Comment by QianaJiao** [comment] 2024-03-06 07:40
We already have a similar issue: https://github.com/xamarin/xamarin-macios/issues/18469.  And below is the workaround: 
You could add the following to the csproj: 
```
<PropertyGroup>
    <EnableCodeSigning>true</EnableCodeSigning>
    <CodesignRequireProvisioningProfile>true</CodesignRequireProvisioningProfile>
    <DisableCodesignVerification>true</DisableCodesignVerification>
</PropertyGroup>
```
Hope it helps you.

**Comment by Cr15Denis** [comment] 2024-03-06 15:06
@QianaJiao  
Thank you for your comments, it is only in emulators that the problem is not on physical devices. I'm going to try the solution you shared with me.

**Comment by jfversluis** [comment] 2024-03-06 18:53
@Cr15Denis that sounds right because running on the Simulator by default you app is not signed. On a device it is. So this is the same thing and the proposed workaround should be sufficient for now.

**Comment by jfversluis** [comment] 2024-03-06 18:54
Duplicate of https://github.com/xamarin/xamarin-macios/issues/18469

**Closed by jfversluis** 2024-03-06 18:54 UTC
Labels: t/bug, area/single project ☝️, platform/iOS 🍎, s/triaged, s/needs-attention, potential-regression
