### ISSUE TITLE
why MAUI does not support watch face till now.

### ISSUE THREAD

**Issue by jayantasarkar1** [dotnet/maui#15084] opened 2023-05-15 04:32 UTC
### Description

why MAUI does not support watch face till now?
any plan to to come in Soon from Microsoft?

if Xamarin support going to stop by Microsoft after MAUI.
then they have to build all api in MAUI.

### Public API Changes

CanvasWatchFaceService api not supported in MAUI

### Intended Use-Case

we would need to create watch face for out project. which was in Xamarin.
now we need to migrate to MAUI.
but MAUI does not support CanvasWatchFaceService.

**Comment by acaliaro** [comment] 2023-05-15 04:55
I think you can installa some nuget packages like  xamarin.androidx.wear.....

**Comment by jayantasarkar1** [comment] 2023-05-15 14:09
That does not work. after adding xamarin.androidx.wear packages, it's internally can't compile the solution due to conflict with the some internal classes. error shows like :- can't load it's already declare more than once.

**Comment by acaliaro** [comment] 2023-05-15 14:32
I think you can take a look to https://learn.microsoft.com/en-us/xamarin/android/wear/platform/creating-a-watchface?tabs=windows for "android.support", or to this for androidx
https://developer.android.com/training/wearables/watch-faces/service

I have installet these nugets and I have no problem when I recompile the project

Xamarin.AndroidX.Wear
Xamarin.AndroidX.Wear.WatchFace

this is the service I have created in Android Platform

using Android.Views;
using AndroidX.Wear.WatchFace;
using AndroidX.Wear.WatchFace.Style;
using Kotlin.Coroutines;
namespace MauiAppICommandProblem.Platforms.Android
{
    public class CustomWatchFaceService : WatchFaceService
    {
        protected override Java.Lang.Object CreateWatchFace(ISurfaceHolder surfaceHolder, WatchState watchState, ComplicationSlotsManager complicationSlotsManager, CurrentUserStyleRepository currentUserStyleRepository, IContinuation p4)
        {
            throw new NotImplementedException();
        }
    }
}

this is the manifest

<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android">
	<application android:allowBackup="true" android:icon="@mipmap/appicon" android:roundIcon="@mipmap/appicon_round" android:supportsRtl="true">
		<service android:name=".CustomMyWatchFaceService" android:label="My Watch Face" android:permission="android.permission.BIND_WALLPAPER">
			...
			<meta-data android:name="android.service.wallpaper.square_mode" android:value="false" />
			...
		</service>
	</application>
	<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
	<uses-permission android:name="android.permission.INTERNET" />
	<uses-permission android:name="android.permission.WAKE_LOCK" />
	
	<uses-permission android:name="com.google.android.wearable.permission.RECEIVE_COMPLICATION_DATA" />
	<uses-sdk android:minSdkVersion="26" android:targetSdkVersion="33" />
</manifest>

**Comment by jfversluis** [comment] 2023-05-15 19:16
Duplicate of #1144 and #4852

We have no immediately plans to support that any more than we do today. Upvote the discussion to show your interest in this!

You might be able to make something work today, but it will require some exploring on your part 😄

**Closed by jfversluis** 2023-05-15 19:16 UTC
Labels: proposal/open, area/setup 🪄, partner/android
