### ISSUE TITLE
[Bug] Binding value to IsVisible of FlexLayout raises System.Runtime.InteropServices.COMException on Windows

### ISSUE THREAD

**Issue by SunshineSpring666** [dotnet/maui#10198] opened 2022-09-19 03:05 UTC
### Description

Setting value to FlexLayout's IsVisible property raises following exception on Windows.

```
<FlexLayout IsVisible="{Binding IsLayoutVisible}">
......
</FlexLayout>
```

### Steps to Reproduce

Run the attached demo project.
[maapp.zip](https://github.com/dotnet/maui/files/9595928/maapp.zip)

### Link to public reproduction project repository

https://github.com/SunshineSpring666/MAUI_FlexLayout_IsVisible_Bug.git

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows SDK 10.0.22000+

### Did you find any workaround?

no

### Relevant log output

```shell
System.Runtime.InteropServices.COMException
  HResult=0x88000FA8
  Message=0x88000FA8
  Source=WinRT.Runtime
  StackTrace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at ABI.Microsoft.UI.Xaml.IDependencyObjectMethods.SetValue(IObjectReference _obj, DependencyProperty dp, Object value)
   at Microsoft.Maui.Controls.Platform.ToolbarExtensions.UpdateBackButton(MauiToolbar platformToolbar, Toolbar toolbar)
   at Microsoft.Maui.Controls.Toolbar.SetProperty[T](T& backingStore, T value, String propertyName)
   at Microsoft.Maui.Controls.NavigationPageToolbar.UpdateBackButton()
   at Microsoft.Maui.Controls.NavigationPageToolbar.ApplyChanges(NavigationPage navigationPage)
   at Microsoft.Maui.Controls.Element.OnPropertyChanged(String propertyName)
   at Microsoft.Maui.Controls.BindableObject.SetValueActual(BindableProperty property, BindablePropertyContext context, Object value, Boolean currentlyApplying, SetValueFlags attributes, Boolean silent)
   at Microsoft.Maui.Controls.BindableObject.SetValueCore(BindableProperty property, Object value, SetValueFlags attributes, SetValuePrivateFlags privateAttributes)
   at Microsoft.Maui.Controls.BindableObject.SetValue(BindableProperty property, Object value, Boolean fromStyle, Boolean checkAccess)
   at Microsoft.Maui.Controls.NavigationPage.SetHasBackButton(Page page, Boolean value)
```

**Comment by mattleibow** [comment] 2022-09-30 14:38
If you remove the binding, is everything working?

The error stack trace has lots of toolbar things, so I am wondering if there is a mix of issues?

**Comment by hartez** [comment] 2022-10-04 15:18
This _may_ be a duplicate of #9377.

**Closed** 2022-10-17 00:02 UTC
Labels: t/bug, area/layout 🔲, s/needs-info, s/no-recent-activity, layout-flex
