### ISSUE TITLE
[Bug] Can't build an application with Resx files

### ISSUE THREAD

**Issue by pictos** [dotnet/maui#2300] opened 2021-08-29 15:58 UTC
### Description

If you add Resx files to your project the iOS and mac-catalyst builds will fail.

### Steps to Reproduce

1. Create a new maui project
2. Add Resx files to your project
3. Rebuild the project

### Expected Behavior

Build without issues.

### Actual Behavior
This error

`C:\Program Files\dotnet\sdk\6.0.100-preview.7.21379.14\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ConflictResolution.targets(112,5): error NETSDK1152: Found multiple publish output files with the same relative path: obj\Debug\net6.0-ios\iossimulator-x64\en\MauiBugRepro.resources.dll, obj\Debug\net6.0-ios\iossimulator-x64\es\MauiBugRepro.resources.dll.`

### Basic Information

- Version with issue: 6.0.100-preview.7.1345
- Last known good version: N/A
- IDE: VS 2022 Windows
- Platform Target Frameworks: 
  - iOS:  
- Nuget Packages: N/A
- Affected Devices: All

### Reproduction Link

https://github.com/pictos/MauiBugRepro

resx-error branch

**Comment by hartez** [comment] 2022-01-05 22:32
Duplicate of #1855

**Closed by hartez** 2022-01-05 22:32 UTC
Labels: t/bug, area/tooling ⚙️
