### ISSUE TITLE
[regression/7.0.0] [Android] - DataBinding not working inside ScrollView with nested elements

### ISSUE THREAD

**Issue by MAUIoxo** [dotnet/maui#17211] opened 2023-09-05 10:50 UTC
### Description

In my .NET MAUI App I use a nested structure of Elements inside a `ScrollView`. In this nested scenario `DataBinding` does not work anymore and Updates after `OnPropertyChanged(...)` of bound element does not work anymore on Android (but does without any problems on iOS) .

```xaml
<ContentView.Resources>
    <ResourceDictionary>
        <Style x:Key="BorderStyleView" TargetType="Border">
            <Setter Property="Background" Value="{StaticResource White}"/>
            <Setter Property="StrokeShape" Value="RoundRectangle 10, 10, 10, 10"/>
            <Setter Property="Margin" Value="15"/>
            <Setter Property="Opacity" Value="0.9"/>
            <Setter Property="Padding" Value="0"/>
        </Style>
        <Style x:Key="BorderHeadline" TargetType="Label">
            <Setter Property="FontSize" Value="16"/>
            <Setter Property="FontAttributes" Value="Bold"/>
            <Setter Property="TextColor" Value="{StaticResource DarkOrange1}"/>
        </Style>

        <DataTemplate x:Key="VerticalItemTemplate" x:DataType="{x:Type databaseModels:Selection}">
            <sho:DraggableViewCell>
                <ContentView>
                    <SwipeView>
                        
                        <Border Padding="15, 0, 15, 0" Style="{StaticResource BorderStyle}">
                            <Grid RowDefinitions="*, 20" ColumnDefinitions="120, Auto, Auto, Auto, Auto, 70, Auto">
                                <Label Grid.Row="0" Grid.Column="0" Text="{Binding FoodItem.Name}" VerticalOptions="CenterAndExpand" Margin="5, 0, 0, 0"/>
                                <Entry Placeholder="Abc"/>
                                <Label Grid.Row="0" Grid.Column="2" Text="g" VerticalOptions="Center" Margin="0, 0, 5, 0"/>
                            </Grid>
                        </Border>

                        <SwipeView.RightItems>
                            <SwipeItems>
                                <SwipeItem Text="{loc:Translate CalculateText}" BackgroundColor="{StaticResource DarkOrange1}"
                                           Command="{Binding Source={RelativeSource AncestorType={x:Type viewModels:CalculateViewModel}}, Path=ExcludeItemCommand}"
                                           CommandParameter="{Binding .}"/>

                            </SwipeItems>
                        </SwipeView.RightItems>
                    </SwipeView>
                </ContentView>
            </sho:DraggableViewCell>
        </DataTemplate>

        <toolkit:IntToBoolConverter x:Key="IntToBoolConverter"/>
    
    </ResourceDictionary>
</ContentView.Resources>

<Grid RowDefinitions="*">

    <!--Just the Background Image and the LinearGradient-->
    <views:BackgroundImageView x:Name="BackgroundImage" VerticalOptions="Start"/>

    <ScrollView Grid.Row="0" VerticalScrollBarVisibility="Always" VerticalOptions="FillAndExpand">
        <Grid RowDefinitions="Auto">
            <Border Grid.Row="0" Style="{StaticResource BorderStyleView}" Opacity="0.85" VerticalOptions="FillAndExpand" Margin="15, 0, 15, -10" MinimumHeightRequest="300">

                <StackLayout Background="Red">

                    <!-- Heading -->
                    <Label Text="{loc:Translate MealHeaderText, StringFormat='{0}:'}" Style="{StaticResource BorderHeadline}" Padding="15, 15, 15, 5"/>

                    <!-- Min, Amount-->
                    <HorizontalStackLayout Margin="0, 10, 0, -5" IsVisible="{Binding SelectedItems.Count, Converter={StaticResource IntToBoolConverter}}">
                        <VerticalStackLayout Margin="150, 0, 10, 0">
                            <Label Text="Min"/>
                            <Label Text="{loc:Translate AmountColumnString}"/>
                        </VerticalStackLayout>
                    </HorizontalStackLayout>


                    <!-- CollectionView to display the Selected Items -->
                    <Grid RowDefinitions="*" Margin="0, 10, 0, 0" HeightRequest="500">
                        
                        <sho:CollectionView CollectionPadding="10, 10, 10, 10"
                                            EnableDragAndDrop="True"
                                            DragAndDropDirection="VerticalOnly"
                                            DragAndDropTrigger="LongTap"
                                            ItemHeight="80"
                                            ItemsSource="{Binding SelectedItems, Mode=OneWay}"
                                            ItemTemplate="{StaticResource VerticalItemTemplate}"
                                            MinimumHeightRequest="250"
                                            AnimateScroll="True"
                                            DisableScroll="False"
                                            CollectionLayout="Vertical"/>
                    </Grid>

                </StackLayout>
            </Border>
        </Grid>
    </ScrollView>

</Grid>
```

**ViewModel**:

```cs
public ObservableRangeCollection<SelectionItem> SelectedFoodItems { get; set; }

public CalculateViewModel()
{    
    SelectedItems = new ObservableRangeCollection<SelectionItem>();
}

private async Task FilterSelectedItems()
{
    var selectedItems = GroupedSelectionItems.SelectMany(groupedSelectionItem => groupedSelectionItem).Where(selectionItem => selectionItem.IsSelected == true).ToList();

    SelectedItems.Clear();
    SelectedItems.AddRange(selectedItems);

    OnPropertyChanged(nameof(SelectedItems));

    await Task.CompletedTask;
}
```

When updating the SelectedItems so that the SelectedItems.Count changes and calling `OnPropertyChanged(nameof(SelectedItems))` the part bound to `IsVisible="{Binding SelectedItems.Count, ...}"` does not get updated.

Also the `<sho:CollectionView ... />` below does not show its elements until you scroll the `CollectionView`. The `IsVisible`-Element is not updated.

Replacing the `ScrollView` by a `StackLayout` or a `VerticalStackLayout` worked regarding `DataBinding` without any problems (yes, no scrolling then possible, but just to show what does not work or works regarding `DataBinding`)

Changing the XAML code with `ScrollView` wrapped around the `Grid` does not have any issues with `DataBinding` and all the Updates are done correctly and as expected after `OnPropertyChanged(nameof(SelectedItems))`:

```xaml
<ContentView.Resources>
    <ResourceDictionary>
        <Style x:Key="BorderStyleView" TargetType="Border">
            <Setter Property="Background" Value="{StaticResource White}"/>
            <Setter Property="StrokeShape" Value="RoundRectangle 10, 10, 10, 10"/>
            <Setter Property="Margin" Value="15"/>
            <Setter Property="Opacity" Value="0.9"/>
            <Setter Property="Padding" Value="0"/>
        </Style>
        <Style x:Key="BorderHeadline" TargetType="Label">
            <Setter Property="FontSize" Value="16"/>
            <Setter Property="FontAttributes" Value="Bold"/>
            <Setter Property="TextColor" Value="{StaticResource DarkOrange1}"/>
        </Style>

        <DataTemplate x:Key="VerticalItemTemplate" x:DataType="{x:Type databaseModels:Selection}">
            <sho:DraggableViewCell>
                <ContentView>
                    <SwipeView>
                        
                        <Border Padding="15, 0, 15, 0" Style="{StaticResource BorderStyle}">
                            <Grid RowDefinitions="*, 20" ColumnDefinitions="120, Auto, Auto, Auto, Auto, 70, Auto">
                                <Label Grid.Row="0" Grid.Column="0" Text="{Binding FoodItem.Name}" VerticalOptions="CenterAndExpand" Margin="5, 0, 0, 0"/>
                                <Entry Placeholder="Abc"/>
                                <Label Grid.Row="0" Grid.Column="2" Text="g" VerticalOptions="Center" Margin="0, 0, 5, 0"/>
                            </Grid>
                        </Border>

                        <SwipeView.RightItems>
                            <SwipeItems>
                                <SwipeItem Text="{loc:Translate CalculateText}" BackgroundColor="{StaticResource DarkOrange1}"
                                           Command="{Binding Source={RelativeSource AncestorType={x:Type viewModels:CalculateViewModel}}, Path=ExcludeItemCommand}"
                                           CommandParameter="{Binding .}"/>

                            </SwipeItems>
                        </SwipeView.RightItems>
                    </SwipeView>
                </ContentView>
            </sho:DraggableViewCell>
        </DataTemplate>

        <toolkit:IntToBoolConverter x:Key="IntToBoolConverter"/>
    
    </ResourceDictionary>
</ContentView.Resources>

<ScrollView>
    <Grid RowDefinitions="*">

        <!--Just the Background Image and the LinearGradient-->
        <views:BackgroundImageView x:Name="BackgroundImage" VerticalOptions="Start"/>

        <!--<ScrollView Grid.Row="0" VerticalScrollBarVisibility="Always" VerticalOptions="FillAndExpand"> -->
        <Grid RowDefinitions="Auto">
            <Border Grid.Row="0" Style="{StaticResource BorderStyleView}" Opacity="0.85" VerticalOptions="FillAndExpand" Margin="15, 0, 15, -10" MinimumHeightRequest="300">

                <StackLayout Background="Red">

                    <!-- Heading -->
                    <Label Text="{loc:Translate MealHeaderText, StringFormat='{0}:'}" Style="{StaticResource BorderHeadline}" Padding="15, 15, 15, 5"/>

                    <!-- Min, Amount-->
                    <HorizontalStackLayout Margin="0, 10, 0, -5" IsVisible="{Binding SelectedItems.Count, Converter={StaticResource IntToBoolConverter}}">
                        <VerticalStackLayout Margin="150, 0, 10, 0">
                            <Label Text="Min"/>
                            <Label Text="{loc:Translate AmountColumnString}"/>
                        </VerticalStackLayout>
                    </HorizontalStackLayout>


                    <!-- CollectionView to display the Selected Items -->
                    <Grid RowDefinitions="*" Margin="0, 10, 0, 0" HeightRequest="500">
							
                        <sho:CollectionView CollectionPadding="10, 10, 10, 10"
                                            EnableDragAndDrop="True"
                                            DragAndDropDirection="VerticalOnly"
                                            DragAndDropTrigger="LongTap"
                                            ItemHeight="80"
                                            ItemsSource="{Binding SelectedItems, Mode=OneWay}"
                                            ItemTemplate="{StaticResource VerticalItemTemplate}"
                                            MinimumHeightRequest="250"
                                            AnimateScroll="True"
                                            DisableScroll="False"
                                            CollectionLayout="Vertical"/>
                    </Grid>

                </StackLayout>
            </Border>
        </Grid>
        <!--</ScrollView>-->

    </Grid>
</ScrollView>
```

Unfortunately, it was not possible to create a reproducible example. But, I think as with this the `ScrollView` can't be used anymore and scrolling is not possible. To me this is a severe Bug/Issue and needs to be looked at also without a minimal explample. Please just don't close it!

Please, also have a close look at the `DataBinding` and updates in such nested `ScrollView` structures in general where the problem could be.

### Steps to Reproduce

See Code examples above. Wrapping the `ScrollView` around the outer `Grid` and `DataBinding` of the `IsVisible`-Property works and `ScrollView` inside as in the 1st example it loses `DataBinding` updates completely on Android

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Working with VS 17.7.2 and corresponding Android release inside Google Pixel 5 Emulator (API 33 Android 13.0 - API 33)

### Did you find any workaround?

Yes, a bad one:

I could wrap the ScrollView around my outer Grid and DataBiding worked again. But, doing this and you have a closer look at my Code above, this means my ScrollView also scrolls my BackgroundImageView which I did not want. But at least DataBinding could get up and running doing it like this.

```xaml
<ContentView.Resources>
    <ResourceDictionary>
        <Style x:Key="BorderStyleView" TargetType="Border">
            <Setter Property="Background" Value="{StaticResource White}"/>
            <Setter Property="StrokeShape" Value="RoundRectangle 10, 10, 10, 10"/>
            <Setter Property="Margin" Value="15"/>
            <Setter Property="Opacity" Value="0.9"/>
            <Setter Property="Padding" Value="0"/>
        </Style>
        <Style x:Key="BorderHeadline" TargetType="Label">
            <Setter Property="FontSize" Value="16"/>
            <Setter Property="FontAttributes" Value="Bold"/>
            <Setter Property="TextColor" Value="{StaticResource DarkOrange1}"/>
        </Style>

        <DataTemplate x:Key="VerticalItemTemplate" x:DataType="{x:Type databaseModels:Selection}">
            <sho:DraggableViewCell>
                <ContentView>
                    <SwipeView>                        
                        <Border Padding="15, 0, 15, 0" Style="{StaticResource BorderStyle}">
                            <Grid RowDefinitions="*, 20" ColumnDefinitions="120, Auto, Auto, Auto, Auto, 70, Auto">
                                <Label Grid.Row="0" Grid.Column="0" Text="{Binding FoodItem.Name}" VerticalOptions="CenterAndExpand" Margin="5, 0, 0, 0"/>
                                <Entry Placeholder="Abc"/>
                                <Label Grid.Row="0" Grid.Column="2" Text="g" VerticalOptions="Center" Margin="0, 0, 5, 0"/>
                            </Grid>
                        </Border>

                        <SwipeView.RightItems>
                            <SwipeItems>
                                <SwipeItem Text="{loc:Translate CalculateText}" BackgroundColor="{StaticResource DarkOrange1}"
                                           Command="{Binding Source={RelativeSource AncestorType={x:Type viewModels:CalculateViewModel}}, Path=ExcludeItemCommand}"
                                           CommandParameter="{Binding .}"/>

                            </SwipeItems>
                        </SwipeView.RightItems>
                    </SwipeView>
                </ContentView>
            </sho:DraggableViewCell>
        </DataTemplate>

        <toolkit:IntToBoolConverter x:Key="IntToBoolConverter"/>
    
    </ResourceDictionary>
</ContentView.Resources>

<ScrollView>
    <Grid RowDefinitions="*">

        <!--Just the Background Image and the LinearGradient-->
        <views:BackgroundImageView x:Name="BackgroundImage" VerticalOptions="Start"/>

        <!--<ScrollView Grid.Row="0" VerticalScrollBarVisibility="Always" VerticalOptions="FillAndExpand"> -->
        <Grid RowDefinitions="Auto">
            <Border Grid.Row="0" Style="{StaticResource BorderStyleView}" Opacity="0.85" VerticalOptions="FillAndExpand" Margin="15, 0, 15, -10" MinimumHeightRequest="300">
                <StackLayout Background="Red">

                    <!-- Heading -->
                    <Label Text="{loc:Translate MealHeaderText, StringFormat='{0}:'}" Style="{StaticResource BorderHeadline}" Padding="15, 15, 15, 5"/>

                    <!-- Min, Amount-->
                    <HorizontalStackLayout Margin="0, 10, 0, -5" IsVisible="{Binding SelectedItems.Count, Converter={StaticResource IntToBoolConverter}}">
                        <VerticalStackLayout Margin="150, 0, 10, 0">
                            <Label Text="Min"/>
                            <Label Text="{loc:Translate AmountColumnString}"/>
                        </VerticalStackLayout>
                    </HorizontalStackLayout>


                    <!-- CollectionView to display the Selected Items -->
                    <Grid RowDefinitions="*" Margin="0, 10, 0, 0" HeightRequest="500">
							
                        <sho:CollectionView CollectionPadding="10, 10, 10, 10"
                                            EnableDragAndDrop="True"
                                            DragAndDropDirection="VerticalOnly"
                                            DragAndDropTrigger="LongTap"
                                            ItemHeight="80"
                                            ItemsSource="{Binding SelectedItems, Mode=OneWay}"
                                            ItemTemplate="{StaticResource VerticalItemTemplate}"
                                            MinimumHeightRequest="250"
                                            AnimateScroll="True"
                                            DisableScroll="False"
                                            CollectionLayout="Vertical"/>
                    </Grid>

                </StackLayout>
            </Border>
        </Grid>
        <!--</ScrollView>-->

    </Grid>
</ScrollView>
```

**Comment by hugebug4ever** [comment] 2023-09-06 12:31
For my case , It is the SwipteView bloks the databinding inside the it. 
The binding works as expected with the SwipeView commented out as shown in the code sample bellow.

`
			<CollectionView
				Style="{StaticResource LobbyContentCollection}"
                VerticalOptions="Start"
                HorizontalOptions="Center"
				ItemsSource="{Binding PlayerStates}">
				<CollectionView.ItemsLayout>
					<LinearItemsLayout
						Orientation="Vertical"
						ItemSpacing="5" />
				</CollectionView.ItemsLayout>
				<CollectionView.ItemTemplate>
					<DataTemplate 
                        x:DataType="room:UGameRoomPlayerState">
						  
							<Frame
								Margin="5"
								Style="{StaticResource LobbyContentFrame}">
								<Frame.GestureRecognizers>
									<TapGestureRecognizer
										Command="{Binding Source={RelativeSource AncestorType={x:Type viewmodel:RoomPageViewModel}}, Path=TapCommand}"
										CommandParameter="{Binding .}" />
								</Frame.GestureRecognizers>
								<Grid ColumnDefinitions="40, *, 20, 60"
									Style="{StaticResource LobbyContentGrid}">
									<Image
										Grid.Column="0"
										Margin="0"
										IsVisible="{Binding IsHost}">
										<Image.Source>
											<FontImageSource
												Glyph="{x:Static helpers:IconMaterial.Support_agent}"
												FontFamily="Google"
												Color="Green"
												Size="40" />
										</Image.Source>
									</Image>
									<Label 
										Style="{StaticResource LobbyContentText}" 
										Grid.Column="1" Margin="10, 0, 0, 0" 
										Text="{Binding PlayerName}"  
										VerticalOptions="Center" />
									<Label Style="{StaticResource LobbyContentText}" Grid.Column="2" Text="{Binding SeatId}"  VerticalOptions="Center" />
									<Label Style="{StaticResource LobbyContentText}" Grid.Column="3" Text="{Binding PlayerState}"  VerticalOptions="Center" />
								</Grid>
							</Frame>
						 
					</DataTemplate>
				</CollectionView.ItemTemplate>
			</CollectionView>
`

**Comment by primozcerar** [comment] 2023-11-08 11:06
Another ugly way to work around this until it is fixed is to reapply the BindingContext to any element that needs it using a reference for example or RelativeSource.

BindingContext="{Binding Source={Reference rootView}, Path=BindingContext}"

**Comment by jfversluis** [comment] 2024-04-03 13:24
Can anyone confirm this is still an issue? It is a bit older by now and to be honest I'm not super clear on what the issue is especially since the original author claims that it is not reproducible? While you ask to not close the issue, I hope you understand its hard to keep something open if we don't have a clear problem to look at.

It would be super helpful if someone can provide us with a simple(r) reproduction that shows this behavior and can confirm that this is still ongoing in the latest version of .NET MAUI at this time.

**Comment by MAUIoxo** [comment] 2024-04-03 19:14
As you mentioned, I wrote this long time ago and had to find a solution in the App. I can try and check on the weekend if I can find this scenario again.

The App in which I detected this back then moved on and now, I am already on .NET 8 and working with the nightly builds.

Are you interested in the status with .NET 8 or still a reproducible example with .NET 7?

**Comment by primozcerar** [comment] 2024-04-04 09:42
Not reproducible on 8.0.6. But that is only in the specific case I had an issue with before. Can't confirm 100% due to many different layout patterns.

**Comment by MAUIoxo** [comment] 2024-04-04 11:49
@primozcerar - Do you have a minimal reproducible example for that where I don’t? My problem back then was, that I wasn’t able to get it stripped out due to code restrictions. In the meantime, I used a workaround that worked obviously and so I can’t probably get one

**Comment by MAUIoxo** [comment] 2024-04-11 06:14
Hello @jfversluis ,
I tried to reproduce the scenario from this example with `<MauiVersion>8.0.20-nightly.10450</MauiVersion>` in the original project that went wrong and I couldn't anymore with the above version. So, in case it is fine with @primozcerar and you, I would suggest to close this issue. In case I get a similar scenario later on, I would write a new issue for that. Hope, this is okay and we therefore get more time for other issues

**Comment by jfversluis** [comment] 2024-04-11 14:14
Sounds good, thanks for letting us know @MAUIoxo !

**Closed by jfversluis** 2024-04-11 14:14 UTC
Labels: t/bug, area/layout 🔲, platform/android 🤖, s/triaged, layout-scrollview, potential-regression
