### ISSUE TITLE
The FlyoutPage toolbar icon does not work in Android and iOS

### ISSUE THREAD

**Issue by bzd3y** [dotnet/maui#24480] opened 2024-08-27 23:54 UTC
### Description

In an app upgraded from Xamarin.Forms that uses a `FlyoutPage`, the toolbar icon does not work on both platforms, with each behaving differently.

On Android, setting `FlyoutPage.IconImageSource` appears to do nothing. The icon seems to always be the default "hamburger" icon.

On iOS the app throws an exception saying that it is unable to find the image. This issue may have to do with using an SVG image, since the app previously used a PNG image for the icon and no exception was thrown.

Currently I am unable to provide a reproduction project because some Visual Studio/macOS updates have broken iOS development for new projects. I have been able to get it to work with my real project, but it doesn't work with the project I created to try to reproduce this.

### Version with bug

8.0.80 SR8

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

**Comment by bzd3y** [comment] 2024-08-28 16:46
I have reverted to using a PNG for the menu icon and that does work in iOS. But none of the other SVGs show up in iOS, but no exception is thrown.

That lead me to discover that it looks like it is an issue with the file extension. So it looks like SVG doesn't work because Maui rasterizes SVGs to a PNG and on iOS the extensions cause problems.

That does seem like a bug, but maybe one that is more easily worked around.

**Comment by PureWeen** [comment] 2024-08-29 22:41
Duplicate of #13368

**Closed by PureWeen** 2024-08-29 22:41 UTC
Labels: t/bug, platform/android 🤖, platform/iOS 🍎, area-controls-flyout, migration-compatibility

**Comment by bzd3y** [comment] 2024-08-30 03:28
@PureWeen I think this might have been marked as a duplicate for the wrong issue. That issue about analyzers doesn't really seem like the same issue.

After further testing, it looks like SVGs in iOS just don't work. For example, I set `Color="red"` on my toolbar icons in the project file and they get a white background. The hamburger menu icon does not look right and appears to be translated to the right some or not resized correctly. All this works on Android.

Are SVGs just not supported on iOS right now and I need to switch back to PNGs?
