### ISSUE TITLE
Let WebView receive messages from the WebSite

### ISSUE THREAD

**Issue by SF-Simon** [dotnet/maui#14325] opened 2023-03-31 17:10 UTC
### Description

This is a very important interaction requirement, so that we can execute some scripts from the web and notify C# to execute certain processes. We can also receive data from the Web and store it in the current database.

### Public API Changes

Should just send a command name and an object like WKWebView?

The actual running code should still be completed by C# itself, which is the safest.
Just inject a JS script to implement the command function before the webpage initialization is completed.

https://developer.apple.com/documentation/webkit/wkscriptmessagehandler

### Intended Use-Case

For example, send some events from the WebEditor to the MAUI client, and then the MAUI client responds to the events.

**Comment by Eilon** [comment] 2023-03-31 17:21
Hi, check out the HybridWebView prototype I wrote a while ago. I think it handles the exact scenario that you are looking for.

* Discussion thread: https://github.com/dotnet/maui/discussions/12009
* Project repo: https://github.com/Eilon/MauiCSharpInteropWebView

**Comment by Eilon** [comment] 2023-03-31 17:22
Also, even if it isn't exactly what you need, if you do check it out, I'd love to hear your feedback. And also it might have sample code that could be useful to you in the meantime if you need to build something custom.

**Comment by SF-Simon** [comment] 2023-03-31 17:41
> Also, even if it isn't exactly what you need, if you do check it out, I'd love to hear your feedback. And also it might have sample code that could be useful to you in the meantime if you need to build something custom.

Hello, @Eilon 

I think it should be very suitable for me.

I've seen this project at Leuan Walker, but I didn't know it was yours. I think his simplified version is also very informative.
[https://github.com/Eilon/MauiCSharpInteropWebView/pull/1](https://github.com/Eilon/MauiCSharpInteropWebView/pull/1)

So...When can I use it? Or is it suitable for me to add it to my project now? 

Can this represent the official development direction of MAUI? Or is it a try?

Thank you for your time. You have saved me time more than once. thank you very much.

**Comment by rachelkang** [comment] 2023-04-04 18:19
@Eilon

**Comment by mattleibow** [comment] 2023-11-03 14:38
Duplicate of #6446

**Comment by mattleibow** [comment] 2023-11-03 14:39
Closing this one as the other one is much more active. See you all on that one!

**Closed by mattleibow** 2023-11-03 14:39 UTC
Labels: proposal/open, area/controls 🎮, control-webview, s/needs-attention
