### ISSUE TITLE
Entry Unfocus not working on Android

### ISSUE THREAD

**Issue by SOliasS** [dotnet/maui#11606] opened 2022-11-24 12:29 UTC
### Description

I have issues with Entry and Editor on Android 
1. The unfocus Option does not work (tapping outside the control and calling the Function manually does nothing)
2. When pressing the back Button the Keyboard disapears but leaves the view on the size with the keyboard so the old View becomes visiable....

Edit:
When using an non Modal Page the Editor and entry still do not unfocus when pressing somewhere else on the page, but when pressing the back button the keyboard disappears as expected.

| . | . | . | . |
|:-:|:-:|:-:|:-:|
|![1](https://user-images.githubusercontent.com/14180046/203784145-56644cf2-3b2b-4c26-9c3b-89c4f615d0ca.png)|![2](https://user-images.githubusercontent.com/14180046/203784135-590cb3d6-10bd-4dce-98c2-45c4f1f40514.png)|![3](https://user-images.githubusercontent.com/14180046/203784139-73fbe319-7006-45ed-ae56-3a6d372f9adc.png)|![4](https://user-images.githubusercontent.com/14180046/203784141-fa774ec8-a15c-48d4-92c1-ea7f0ad04f03.png)|

### Steps to Reproduce

1. Create new .Net Maui Project
2. Create a new View
4. Add Change Page to MainPage
`Application.Current.MainPage.Navigation.PushModalAsync(new TestPage());`
5. Add Entry to View

### Link to public reproduction project repository

https://github.com/SOliasS/MauiTest.git

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

**Comment by mattleibow** [comment] 2022-11-24 19:23
@PureWeen  @rachelkang I think this is a duplicate?

**Comment by PureWeen** [comment] 2022-11-27 17:26
Duplicate of #5983

**Closed by PureWeen** 2022-11-27 17:26 UTC
Labels: t/bug, platform/android 🤖, area/controls 🎮, control-entry

**Comment by PureWeen** [comment] 2022-11-27 17:27
> When pressing the back Button the Keyboard disapears but leaves the view on the size with the keyboard so the old View becomes visiable....

Is fixed by https://github.com/dotnet/maui/pull/11356
