### ISSUE TITLE
The scrolled event does not fire when ScrollView Orientation is Horizontal

### ISSUE THREAD

**Issue by HobDev** [dotnet/maui#5090] opened 2022-03-07 10:22 UTC
### Description

The repro attached is default template. I added two Grids in HorizontalStackLayout. The whole UI is within ScrollView.  The ScrollView Oreientation is set to Horizontal.The scrolled event does not fire when ScrollView Oreientation is Horizontal. It works fine with default Vertical orientation.
[MauiBugSample.zip](https://github.com/dotnet/maui/files/8196786/MauiBugSample.zip)
 

### Steps to Reproduce

 When the UI is scrooled Horizontally the Scrolled event in the code behind does not fire. The scroll event pf the ScrollView does fire if the orientation of the ScrollView is set to vertical. 

### Version with bug

Preview 13 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

iOS 15 and Android 11

### Did you find any workaround?

No

**Comment by PineYi** [comment] 2022-03-08 05:20
Not reproducible with Android 11 and 17.2.0 Preview 2.0 [32301.636.main] with above project.
![image](https://user-images.githubusercontent.com/99375367/157171108-361b8bff-6101-4a11-97d0-5793686ec0a8.png)

**Comment by persiabudi28** [comment] 2022-04-16 19:56
yes scrolling event not working

**Comment by persiabudi28** [comment] 2022-05-04 06:17
xaml:
<ScrollView x:Name="scrollView"
               VerticalOptions="FillAndExpand"
                    orientation="hoizontal" Scrolled="OnScrollViewScrolled">
            <StackLayout>
                ---any control--
            </StackLayout>
        </ScrollView>

or

xaml:
<ScrollView x:Name="scrollView"
               VerticalOptions="FillAndExpand"
                    orientation="both" Scrolled="OnScrollViewScrolled">
            <StackLayout>
                ---any control--
            </StackLayout>
        </ScrollView>


the OnScrollViewScrolled event handler is not executed when the Scrolled event fires:

void OnScrollViewScrolled(object sender, ScrolledEventArgs e)
{
    Console.WriteLine($"ScrollX: {e.ScrollX}, ScrollY: {e.ScrollY}"); -->error and not detect
}

**Comment by VincentBu** [comment] 2022-05-09 07:00
repro with vs main build(32507.29.main)

**Comment by karthikraja-arumugam** [comment] 2022-05-11 12:34
Hi Team, Can you please include a fix for this in near releases. Due to this issue, we can't implement a major use case in our project.

**Comment by rmarinho** [comment] 2022-06-20 16:38
fixed #8021 8021

**Closed by rmarinho** 2022-06-20 16:38 UTC
Labels: t/bug, area/layout 🔲, p/1, s/verified
