### ISSUE TITLE
Error CS0246: The type or namespace name 'MauiUIApplicationDelegate' could not be found (are you missing a using directive or an assembly reference?)

### ISSUE THREAD

**Issue by ssbssb-cmd** [dotnet/maui#20638] opened 2024-02-16 10:31 UTC
### Description

Please help.. My project has stopped compiling after upgrading to the latest Visual Studio Mac with this error message

Error CS0246: The type or namespace name 'MauiUIApplicationDelegate' could not be found (are you missing a using directive or an assembly reference?)

I have already deleted the bin and obj folders, clean solution and restarted my Mac, but still getting this error.

- maui-ios 8.0.0-rc.2.9530/8.0.100-rc.2 
- visual studio 17.6.9 build 415

### Version with bug

Unknown/Other

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

**Comment by jfversluis** [comment] 2024-02-16 10:51
Duplicate of #20600 please install .NET 8.0.201 that should fix the issues!

**Closed by jfversluis** 2024-02-16 10:51 UTC
Labels: t/bug

**Comment by ssbssb-cmd** [comment] 2024-02-16 11:37
Hi I have installed 8.0.201, but i'm still getting the error, what other steps are needed? As i am still facing this issue

```
8.0.100-rc.2.23502.2 [/usr/local/share/dotnet/sdk]
8.0.201 [/usr/local/share/dotnet/sdk]
```
