### ISSUE TITLE
Label FormattedText causes text miss-alignment and clipping

### ISSUE THREAD

**Issue by philipag** [dotnet/maui#6585] opened 2022-04-28 04:48 UTC
### Description

Under some conditions label text is clipped and shifted.  See the attached repro to see the issue.

### Steps to Reproduce

1. Compile and run repro with Android 11 emulator
2. The red label is shifted and clipped and the green label is correct.  These labels should look the same.  The only difference is that the sample sets FormattedText  for the red label and Text for the green label.

[layoutbug4.zip](https://github.com/dotnet/maui/files/8579557/layoutbug4.zip)

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 11

### Did you find any workaround?

no

**Comment by kristinx0211** [comment] 2022-04-28 05:14
verified repro on android 11 using vs 17.3.0 Preview 1.0 [32426.537.main] with above project.

**Comment by mattleibow** [comment] 2022-05-14 04:45
I believe this is a duplicate of #4838

**Closed by mattleibow** 2022-05-14 04:45 UTC
Labels: t/bug, platform/android 🤖, area/controls 🎮, s/verified
