### ISSUE TITLE
ContentPage.ToolbarItem not rendering

### ISSUE THREAD

**Issue by 4Forcas** [dotnet/maui#3842] opened 2021-12-23 08:59 UTC
### Description

Visible
![github1](https://user-images.githubusercontent.com/72259197/147214432-65dce3bf-9f0b-4e53-904a-61e260e652a4.png)

Not visible
![github2](https://user-images.githubusercontent.com/72259197/147214454-2e043097-b789-4c8f-a452-35d1dbf673fd.png)

### Steps to Reproduce

Create new MAUI project
Add new dummy contentpage
Add ContentPage.ToolbarItems to dummy page
Change MainPage typeof Shell
Add Routing to Shell MainPage

[ReProduction.zip](https://github.com/dotnet/maui/files/7767993/ReProduction.zip)

### Version with bug

Preview 10 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 11 - 9

### Did you find any workaround?

Yes, you can render the item by changing the text value in the toolbaritem while the application is running.

**Comment by Phil4121** [comment] 2021-12-29 20:12
@4Forcas Could you please post a snipped of your workaround? I also tried to edit the text but with no success.
Thanks!

**Comment by 4Forcas** [comment] 2021-12-29 21:47
> @4Forcas Please post a snipped of your workaround! I also tried to edit the text when the page is appiering but with no success. Thanks!

I can't acces the File for a while, but il try my best to explain.

So first of all, you need to have hot reload enabled.
Then download the reproduction zip, run the application and while the application is running just any value in content.toolbaritem, i would advise just change the text value repeatedly like 4 - 5 times should do the trick. 

I hope this can help you.

**Comment by ecastelli** [comment] 2021-12-29 23:13
Seeing the same issue on IOS.  ContentPage.ToolbarItem is not rendering at all.  Didn't try changing the text to see if this fixes the issue.

**Comment by Phil4121** [comment] 2021-12-30 12:52
> > @4Forcas Please post a snipped of your workaround! I also tried to edit the text when the page is appiering but with no success. Thanks!
> 
> I can't acces the File for a while, but il try my best to explain.
> 
> So first of all, you need to have hot reload enabled. Then download the reproduction zip, run the application and while the application is running just change any value in content.toolbaritem, i would advise just change the text value repeatedly like 4 - 5 times should do the trick.
> 
> I hope this can help you.
> 
> Edit: The workaround also works on my personal pc

Thank you for your quick reply! Okay, I see what you are doing... So I have to change the text multiple times and everytime I start debugging my project. It's fine thank you but for me this workaround doesn't suit. I thought maybe I can change the text once in code an then the toolbaritems are displayed every time I start my application.

**Comment by Epictek** [comment] 2022-01-04 14:58
Duplicate of #3593 and #3079?
Also posted a workaround here https://github.com/dotnet/maui/issues/3593#issuecomment-1004647406

**Comment by shimingsg** [comment] 2022-02-21 05:27
Verified repro with Android 11 and the above project.

**Comment by Redth** [comment] 2022-03-22 17:23
Closed as duplicate

**Closed by Redth** 2022-03-22 17:23 UTC
Labels: t/bug, high, s/verified
