### ISSUE TITLE
Entry cursor position return to start

### ISSUE THREAD

**Issue by Nimeryon** [dotnet/maui#6675] opened 2022-04-29 16:02 UTC
### Description

I have a simple entry where my users can enter a license key.
When the text change i execute a function to add dash at certain position of the text.

When i modify the entry text with a longer text and move the cursor position de the end of the new text size the cursor position goes back the beginning of the entry.

When create the steps to reproduce i discovered that it completely freeze the entry.
Maybe i do something wrong.
Have a great day.

### Steps to Reproduce

- Create a new dot net MAUI app.
- Inside your main page add an entry with a callback attached to TextChanged
```XAML
<Entry  TextChanged="HandleTextChange" />
```
- Inside you main page cs file create a new function with the name you gave you callback
```C#
private void HandleTextChange(object sender, TextChangedEventArgs e)
{
    string newText = e.NewTextValue;
    string finalText = newText + "something";

    Entry entry = (Entry)sender;
    entry.Text = finalText ;
    entry.CursorPosition = finalText.Length;
}
```

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Windows 10 19044.1645

### Did you find any workaround?

No.

**Comment by samhouts** [comment] 2022-04-29 17:26
Thank you for the report! This has the same root cause as #5401.

**Comment by samhouts** [comment] 2022-04-29 17:26
Duplicate of #5401

**Closed by samhouts** 2022-04-29 17:26 UTC
Labels: t/bug, s/duplicate 2️⃣, s/needs-verification

**Comment by VWilcox2000** [comment] 2022-05-25 01:39
This issue also occurs on Android.  I see it in templated entry and with password entry.
To make the app usable in the meantime, I've worked around it with:

               this.entryPhoneNumber.TextChanged += this.EntryPhoneNumber_TextChanged;

                 private void EntryPhoneNumber_TextChanged(
                    object? sender,
                    TextChangedEventArgs e)
                 {
                    this.entryPhoneNumber.CursorPosition = this.entryPhoneNumber.Text?.Length ?? 0;
                 }

This is obviously a bad experience if they have moved cursor back to left to make a correction, but the alternative is they are mostly typing backwards.
