### ISSUE TITLE
ContentView Touch Interaction works inappropriately when placing one above another ContentView.

### ISSUE THREAD

**Issue by VijayakumarViswanathan** [dotnet/maui#11555] opened 2022-11-22 11:00 UTC
### Description

I have placed two ContentView in a Grid layout and used a button in the first content view. If I click on the empty second content view, the button in the First ContentView gets clicked, and the event is triggered.

### Steps to Reproduce

1. Deploy the attached sample in android and windows.
2. Click the SecondContentView with BackGroundColor Aqua.
3. Button Click event was triggered from the FirstContentView(Issue)

### Link to public reproduction project repository

https://github.com/VijayakumarViswanathan/ContentViewTouchInteraction

### Version with bug

6.0.486

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows

### Affected platform versions

Android 9, windows10.0.19041.0

### Did you find any workaround?

No

**Comment by PureWeen** [comment] 2022-11-22 19:15
@VijayakumarViswanathan if you try 7.0 and set `InputTransparent` to false does that help?

**Comment by jinxinjuan** [comment] 2023-08-11 08:33
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 6.0. Can repro on Android platform with sample project. [ContentViewTouchInteraction](https://github.com/VijayakumarViswanathan/ContentViewTouchInteraction)

Note: On Windows, Button Click event was not triggered.

**Comment by mattleibow** [comment] 2024-06-20 12:40
Duplicate of #10252

**Closed by mattleibow** 2024-06-20 12:40 UTC
Labels: t/bug, platform/windows 🪟, area-layout, platform/android 🤖, s/verified, s/triaged, area-gestures
