### ISSUE TITLE
CarouselView current item isn't changing

### ISSUE THREAD

**Issue by vladPanasiuk** [dotnet/maui#12113] opened 2022-12-14 18:19 UTC
### Description

In my case, I need to change position of the current element using a button. When the button is pressed, the position should simply increment. The problem is that when I press the button, nothing happens. But after swiping to change the position, pressing the button works fine as expected.

I tried only on Android

### Steps to Reproduce

1. Run project that is in reproduction project repository.
2. After starting app press button 'Next' without swiping items in cariusel before clicking button.
3. Observe the bug.

Expected outcome: current item of carousel is changings after button click
Actual outcome: current iten isn't changing

### Link to public reproduction project repository

https://github.com/vladPanasiuk/CarouselViewLoopBugReproduction

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 13

### Did you find any workaround?

After hours of experiments, I noticed that it only is reproducing when `Loop="False"`. So `Loop="True"` fixes it, but this workaround isn't fine because I need to disable looping.

**Comment by vladPanasiuk** [comment] 2022-12-21 09:44
Hi! I added reproduction project url and updated reproduction steps

**Comment by justcivah** [comment] 2022-12-28 11:07
I have the same error here

**Comment by busec0** [comment] 2023-01-03 15:42
Looks related to https://github.com/dotnet/maui/issues/9749

**Comment by jsuarezruiz** [comment] 2023-02-20 15:10
Same or similar to https://github.com/dotnet/maui/issues/9749

**Comment by homeyf** [comment] 2023-06-06 09:07
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 1.0. Can repro on Android platform with sample project.
https://github.com/vladPanasiuk/CarouselViewLoopBugReproduction
![image](https://github.com/dotnet/maui/assets/82450723/98950a65-e3d2-486b-8b7f-773ec4bcc0de)

**Comment by jfversluis** [comment] 2024-08-12 11:51
From the linked issue I can see it's resolved there and we can't reproduce anymore with the latest changes. Since this issue is quite older by now I will close this. 

If there is still something not right according to you, please open a new issue with all the details. Thanks!

**Closed by jfversluis** 2024-08-12 11:51 UTC
Labels: t/bug, s/duplicate 2️⃣, platform/android 🤖, area-controls-collectionview, s/verified, s/triaged
