### ISSUE TITLE
Maui Android app icon does not scale - Workaround required

### ISSUE THREAD

**Issue by gabsamples6** [dotnet/maui#22166] opened 2024-05-02 14:04 UTC
### Description

Android Icon looks totally stretched out and despite all the effort I cannot make it work. Below does not work - open to any suggestions

         <MauiIcon
             Include="Resources\AppIcon\appicon.svg"
             ForegroundFile="Resources\AppIcon\appiconfg.svg"
             BaseSize="64,64"
             Color="#FFFFFF"
             ForegroundScale="0.65"/>

### Steps to Reproduce

- Create or use an appIcon 
- look in android and you will see that what is displayed is totally stretched out .

### Version with bug

8.0.21 SR4.1

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Did you find any workaround?

No . Looking for a workaround

**Comment by abbemu** [comment] 2024-05-03 08:57
Any updates on this?

**Comment by jfversluis** [comment] 2024-05-14 10:04
Duplicate of #22052

**Closed by jfversluis** 2024-05-14 10:04 UTC
Labels: t/bug, area-single-project, platform/android 🤖, s/triaged
