### ISSUE TITLE
Label with multispan formatted text breaks on Android when using HorizontalTextAlignment

### ISSUE THREAD

**Issue by jlbilh** [dotnet/maui#7365] opened 2022-05-20 14:13 UTC
### Description

On Windows this looks fine:
![image](https://user-images.githubusercontent.com/102621630/169543356-dd339427-74e4-41e2-be0a-7fd45ffb9faa.png)

On Android this is broken:
![image](https://user-images.githubusercontent.com/102621630/169543148-23d62c40-3b4c-4c94-badb-1dbe834eeb56.png)

### Steps to Reproduce

Create a new project.

Add the following XAML to the VerticalStackLayout:
```
            <Label HorizontalTextAlignment="Center">
                <Label.FormattedText>
                    <FormattedString>
                        <Span Text="For technical support please dial "/>
                        <Span Text="(555)-555-5555"/>
                    </FormattedString>
                </Label.FormattedText>
            </Label>
```

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 12

### Did you find any workaround?

The label renders correctly when HorizontalTextAlignment is "Start" or if it is unused.

**Comment by kristinx0211** [comment] 2022-05-23 06:19
verified not repro on android 12 with 17.3.0 Preview 2.0 [32522.62.main].
![image](https://user-images.githubusercontent.com/99457000/169755740-e6940a46-41f0-4f9e-a3ee-58d8f6ceccba.png)

**Comment by rmarinho** [comment] 2022-08-01 14:18
Since it seems was not reproducible we are going to close this use for now. Please reopen if it's still a issue.

**Closed by rmarinho** 2022-08-01 14:18 UTC
Labels: t/bug, area/controls 🎮, s/verified
