### ISSUE TITLE
[iOS] Wrong default left/right margin in the navigation bar on iOS

### ISSUE THREAD

**Issue by Victor-Porter** [dotnet/maui#19231] opened 2023-12-05 16:27 UTC
### Description

When I use a navigation bar on a screen on iOS, it shows as a "left and right margin" by default.

I attach image of the error:
![image](https://github.com/dotnet/maui/assets/137196565/ac95e9ca-c0ef-4e56-8834-9f1e6dcb6c97)

On Windows it does not set this left/right margin by default:
![image](https://github.com/dotnet/maui/assets/137196565/77ba70f0-7211-4b1f-836a-110eb1d7158c)

On Android just set the left margin by default.
I created another issue for the left margin in Android: #18843 
![image](https://github.com/dotnet/maui/assets/137196565/e1df2bdd-d8d0-426b-bd64-878c9e1528c4)

### Steps to Reproduce

1. Create a new MAUI project.
2. Change the creation of the MainPage as NavigationPage on App.xaml.cs (If it is created as AppShell).
3. Register MainPage view in MauiProgram.cs
4. Add NavigationPage.TitleView in MainPage.xaml.
5. Launch the application and see the error.

### Link to public reproduction project repository

[Link to the repository](https://github.com/MADSENSE/MADSENSE.MAUI.Sample.App/tree/default-margin-navigationBar-ios)

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 16.3

### Did you find any workaround?

I couldn't find anything.

**Comment by PureWeen** [comment] 2023-12-05 19:21
Duplicate of #5063

**Closed by PureWeen** 2023-12-05 19:21 UTC
Labels: t/bug
