### ISSUE TITLE
iOS: App Crashes when ObservableCollection is modified inside a Task

### ISSUE THREAD

**Issue by sreiss** [dotnet/maui#21452] opened 2024-03-26 11:41 UTC
### Description

On iOS, When deleting and inserting items of a `ObservableCollection ` that is bound to a MAUI `CollectionView`, the following exception is thrown: `Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')`.

### Steps to Reproduce

1. Launch the app provided in the repro sample.
2. Follow the steps provided in the app.

What is expected: the collection view should be updated with the 26 additions, 2 deletions and the 1 insertion.

What happens: the exception `Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')` is thrown.

### Link to public reproduction project repository

https://github.com/flesarradu/CollectionViewCrashAddRemoveItems

### Version with bug

8.0.3 GA

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 16.4

**Comment by Toomas75** [comment] 2024-03-26 13:13
@sreiss  You can load data on threadpool thread, but must update UI in UI thread (thread where view is created).
Items should be modified in UI thread.

**Comment by BenBtg** [comment] 2024-03-26 15:47
I am able to reproduce this crash using the provided repro when using iOS Simulator but interestingly could not repro the issue when running as a Mac OS Catalyst app.

**Comment by RoiChen001** [comment] 2024-03-27 03:13
Can repro this issue at iOS platform on the latest 17.10 preview 2(8.0.14).
![exception](https://github.com/dotnet/maui/assets/143168639/52213070-ead1-4024-80cf-58ef8128afdb)

**Comment by IsmailHassani** [comment] 2024-04-02 05:40
This is probably because your trying to change the observable collection from another thread than the UI thread.
If you're using the onappearing without Task.Run it will work.
Frankly, i don't understand why you're running it inside a task.run. You're just saying run this code in a separate thread.
To overcome this you'll need the dispatcher to run this code.

The OnAppearing (bad name btw, should be more like LoadItems for example) should be a Task that should be awaited inside your CollectionPage
 
What's also is strange, you only instantiate a new Observable Collection if parameter == null. If not items = null, and adding new items to it will result in a null reference exception. As far as i can see, this is actually the case. 
The only possible way to be able to use this, is if the viewmodel is an singleton instance throughout the application, but as far as i can tell it isn't.

**Comment by BenBtg** [comment] 2024-04-08 15:31
Confirmed that dispatching all the Collection changes to the UIThread avoids the crash. e.g.
`          MainThread.BeginInvokeOnMainThread(() =>
            {
                //When we get a parameter means we are coming back to the page
                for (int i = 0; i < 26; i++)
                {
                    Items.Add(new EmptyItem { Width = 50 });
                }

                Items.RemoveAt(0);
                Items.RemoveAt(0);

                Items.Insert(0, new RealItem { Width = 100 });        
            });`

**Comment by IsmailHassani** [comment] 2024-04-08 15:49
if the app is a single window app, than this is ok.
If you're using a multi-window app you probably should avoid using this mainthread dispatcher.
instead use the following and call the dispatcher on the active window/view you want to touch.

```
public bool Invoke(Action action)
{
    if (Application.Current.MainPage is not null && Application.Current.MainPage.Dispatcher is IDispatcher dispatcher)
        return dispatcher.Dispatch(action);
    else
        return Application.Current.Dispatcher.Dispatch(action);
}
```

**Comment by BenBtg** [comment] 2024-04-17 13:12
As you correctly point out, the documentation states that updates to property bindings are automatically dispatched to the Main thread. 
However, note this is only for changes to the bound property itself and not to changes that affect any sub-properties within a complex type assigned to that property. For example, if you had a binding to an address property which was a complex type that contained properties such as house number and postcode. 
Changes to those “sub-properties" would not be automatically dispatched to the Main thread. even if you implemented INotifyPropertyChanged. Only changes to the address property itself (i.e. reassigning a new address class) would be automatically dispatched to the main thread.
In the same way the ObservableCollection view is a complex type which provides a helper for change notifications to its list of items. However, it does not include support for dispatching these changes to the main thread. If that is required, you would need to implement your own version of ObservableCollection.

Hope that clears up any confusion.

**Comment by PureWeen** [comment] 2024-04-29 15:51
Based on @BenBtg 's findings I'm going to close this issue

**Closed by PureWeen** 2024-04-29 15:51 UTC
Labels: t/bug, platform/iOS 🍎, partner/cat 😻, area/collectionview 📃, s/verified, s/triaged
