### ISSUE TITLE
MAUI project not able to compile - Although .Net 6 workload with MAUI installed - MAUI templates installed

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#3651] opened 2021-12-03 17:50 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/MAUI-project-not-able-to-compile---Altho/1591076)._

---
[severity:I'm unable to use this version]
If I create a brand new MAUI app with based on the installed MAUI templates VS 2022 17.1.0 Preview 1.1 does not recognize the installation of the .Net 6 SDK and the MAUI preview installation within the Mobile workload of the installer.

On of the instant error messages after the MAUI project was created is:

**==> Error CS0234	The type or namespace name 'Maui' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)	MauiApp8 (net6.0-ios), MauiApp8 (net6.0-maccatalyst), MauiApp8 (net6.0-windows10.0.19041)**

I updated and run the MAUI check tool (v 0.10.0.0) on the command line. I get the following messages:

**.NET SDK - Workloads (6.0.100) Checkup...
  × android-aot (Microsoft.NET.Sdk.Android.Manifest-6.0.100 : 31.0.101-preview.10.59) not installed.
  × ios (Microsoft.NET.Sdk.iOS.Manifest-6.0.100 : 15.0.101-preview.10.251) not installed.
  × maccatalyst (Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.100 : 15.0.101-preview.10.251) not installed.
  × tvos (Microsoft.NET.Sdk.tvOS.Manifest-6.0.100 : 15.0.101-preview.10.251) not installed.
  × macos (Microsoft.NET.Sdk.macOS.Manifest-6.0.100 : 12.0.101-preview.10.251) not installed.
  × maui (Microsoft.NET.Sdk.Maui.Manifest-6.0.100 : 6.0.101-preview.10.2068) not installed.
  - wasm-tools (microsoft.net.workload.mono.toolchain.manifest-6.0.100 : 6.0.0) installed.
  - microsoft-net-sdk-emscripten (microsoft.net.workload.emscripten.manifest-6.0.100 : 6.0.0) installed.
! Managing Workload installation from the CLI is NOT recommended.  Instead you should install the latest Visual Studio
preview to automatically get the newest release of .NET MAUI workloads installed.**

As written in the messages I tried to manage the problem NOT in the command line but instead in the VS 2022 Preview installer.

BUT in the installer all look correct.

I have also installed the release VS 2022 using the normal Xamarin Forms templates. This all looks good and based on its .Net framework (5.x) I can run my mobile app on Android, Windows and iOS (connected to my MacBook).

The Start drop down list does not show any Android simulators in the preview version or any iOS simulators although they are properly installed and useable with the release Version. (and connected to my MacBook).

It seems that the preview version does not find or recognize the .Net 6 installation.

During the several preview version of MAUI / VS 2022 I was able to run the sample MAUI app but as I installed the VS 2022 Release Version along with the Preview Version I was not able to do so in the Preview version.

One other error in the error list of VisualStudio is:

**Error	NETSDK1147	To build this project, the following workloads must be installed: maui-android
To install these workloads, run the following command: dotnet workload install maui-android**

If I try to run this command I got the following error:

Error during installation rollback: One or more errors occurred. ("microsoft.net.sdk.maui.manifest-6.0.100.msi.x64::6.0.101-preview.9.1805" in NuGet-Feeds "https://api.nuget.org/v3/index.json;C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\" not found.)
Fehler bei der Workloadinstallation: One or more errors occurred. ("microsoft.maui.core.ref.android.msi.x64::6.0.101-preview.9.1805" in NuGet-Feeds "https://api.nuget.org/v3/index.json;C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\" not found.)

Any tips or hints ?

Thanx

Marco

---
#### Feedback Bot on 11/21/2021, 08:28 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Marco Seraphin on 11/21/2021, 11:26 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by KirillPom** [comment] 2021-12-21 13:44
Same for me(
![image](https://user-images.githubusercontent.com/65759581/146940055-602be349-650e-44e4-a023-88bf5e179439.png)

**Comment by marcoseraphin** [comment] 2021-12-26 09:33
it seems, that we have to wait for VS 2022 Preview 2

**Comment by adaptPerception** [comment] 2021-12-28 14:23
Same issue

```
dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.101
 Commit:    ef49f6213a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.101\

Host (useful for support):
  Version: 6.0.1
  Commit:  3a25a7f1cc

.NET SDKs installed:
  1.0.0 [C:\Program Files\dotnet\sdk]
  1.0.3 [C:\Program Files\dotnet\sdk]
  1.0.4 [C:\Program Files\dotnet\sdk]
  2.1.2 [C:\Program Files\dotnet\sdk]
  2.1.4 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.505 [C:\Program Files\dotnet\sdk]
  2.1.507 [C:\Program Files\dotnet\sdk]
  2.1.700 [C:\Program Files\dotnet\sdk]
  3.1.201 [C:\Program Files\dotnet\sdk]
  5.0.404 [C:\Program Files\dotnet\sdk]
  6.0.100 [C:\Program Files\dotnet\sdk]
  6.0.101 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

relevant section from maui-check
```
> .NET SDK - Workloads (6.0.100) Checkup...
  x android-aot (Microsoft.NET.Sdk.Android.Manifest-6.0.100 : 31.0.101-preview.10.59) not installed.
  x ios (Microsoft.NET.Sdk.iOS.Manifest-6.0.100 : 15.0.101-preview.10.251) not installed.
  x maccatalyst (Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.100 : 15.0.101-preview.10.251) not installed.
  x tvos (Microsoft.NET.Sdk.tvOS.Manifest-6.0.100 : 15.0.101-preview.10.251) not installed.
  x macos (Microsoft.NET.Sdk.macOS.Manifest-6.0.100 : 12.0.101-preview.10.251) not installed.
  x maui (Microsoft.NET.Sdk.Maui.Manifest-6.0.100 : 6.0.101-preview.10.2068) not installed.
  x wasm-tools (microsoft.net.workload.mono.toolchain.manifest-6.0.100 : 6.0.0) not installed.
  - microsoft-net-sdk-emscripten (microsoft.net.workload.emscripten.manifest-6.0.100 : 6.0.0) installed.
! Managing Workload installation from the CLI is NOT recommended.  Instead you should install the latest Visual Studio preview to automatically get the newest release of .NET MAUI workloads installed.
Are you sure you would like to continue the CLI workload installation? [y/n] (n): n

─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
☼ Recommendation: Install the latest Visual Studio Preview
To install or update to the latest workloads for .NET MAUI, install the latest Visual Studio Preview and choose .NET MAUI in the list of features to install under the .NET Mobile Workload: https://visualstudio.microsoft.com/vs/preview/
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────


! There were one or more problems detected.
Please review the errors and correct them and run maui-check again.

Press enter to exit...
```

```
Microsoft Visual Studio Community 2022
Version 17.1.0 Preview 1.1
VisualStudio.17.Preview/17.1.0-pre.1.1+31911.260
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Community

ASP.NET and Web Tools 2019   17.1.126.26097
ASP.NET and Web Tools 2019

Azure App Service Tools v3.0.0   17.1.126.26097
Azure App Service Tools v3.0.0

C# Tools   4.1.0-1.21551.6+e4419d6f6792da7011c8589ba118f59d830ca72f
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Mono Debugging for Visual Studio   17.1.4 (dc2a48c)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   6.1.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Razor (ASP.NET Core)   17.0.0.2152601+724154d925d7d9d26ebf8a73a66d5219aa320400
Provides languages services for ASP.NET Core Razor.

TypeScript Tools   17.0.1029.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.1.0-1.21551.6+e4419d6f6792da7011c8589ba118f59d830ca72f
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.1.0-beta.21525.2+46af4a248255f4af2284883f48983fe7dd07a760
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   17.1.0.163 (d17-1-p1@42933de)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   17.1.0.43 (remotes/origin/main@931878527)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   17.1.8 (590388a)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   12.1.99.56 (main/43243b4)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: c633fe9
    Java.Interop: xamarin/java.interop/main@79744f61
    ProGuard: Guardsquare/proguard/v7.0.1@912d149
    SQLite: xamarin/sqlite/3.36.0@a575761
    Xamarin.Android Tools: xamarin/xamarin-android-tools/main@a5194e9


Xamarin.iOS and Xamarin.Mac SDK   15.3.0.41 (7b786db64)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```

**Comment by adaptPerception** [comment] 2021-12-28 14:31
I've tried to repair the _Visual Studio 2022 Preview_ installation, uninstalled/reinstalled and removed/added again the Xamarin/.NET MAUI (preview) options. None of the steps installed the workloads.

**Comment by marcoseraphin** [comment] 2021-12-28 15:04
As I wrote, wait for Preview 2...see here:

**Comment by adaptPerception** [comment] 2021-12-29 00:41
> As I wrote, wait for Preview 2...see here:
> 
> #3781

@marcoseraphin Isn't that only related to hot reload issues?

**Comment by adaptPerception** [comment] 2021-12-29 00:50
These are the errors returned from the default _.NET MAUI App (Preview)_ template upon creation

```
NuGet package restore failed. Please see Error List window for detailed warnings and errors.

Error	NETSDK1109	Runtime list file 'C:\Program Files\dotnet\packs\Microsoft.Maui.Core.Runtime.win\6.0.101-preview.11.2349\data\RuntimeList.xml' was not found. Report this error to the .NET team here: https://aka.ms/dotnet-sdk-issue.
Error	CS0103	The name 'InitializeComponent' does not exist in the current context
Error	CS0103	The name 'CounterLabel' does not exist in the current context
Error	CS0103	The name 'CounterLabel' does not exist in the current context
Error		Project "C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.0.101-preview.11.551\Sdk\Sdk.props" was not imported by "C:\Program Files\dotnet\sdk-manifests\6.0.100\microsoft.net.sdk.ios\WorkloadManifest.targets" at (2,2), due to the file not existing.
Error		Project "C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk\15.0.101-preview.11.551\Sdk\Sdk.props" was not imported by "C:\Program Files\dotnet\sdk-manifests\6.0.100\microsoft.net.sdk.ios\WorkloadManifest.targets" at (3,2), due to the file not existing.
Error		Project "C:\Program Files\dotnet\packs\Microsoft.MacCatalyst.Sdk\15.0.101-preview.11.551\Sdk\Sdk.props" was not imported by "C:\Program Files\dotnet\sdk-manifests\6.0.100\microsoft.net.sdk.maccatalyst\WorkloadManifest.targets" at (2,2), due to the file not existing.
Error	NU1012	Platform version is not present for one or more target frameworks, even though they have specified a platform: net6.0-ios, net6.0-maccatalyst
Error	NU1012	Platform version is not present for one or more target frameworks, even though they have specified a platform: net6.0-ios, net6.0-maccatalyst
Error	NU1012	Platform version is not present for one or more target frameworks, even though they have specified a platform: net6.0-ios, net6.0-maccatalyst
Error	NU1012	Platform version is not present for one or more target frameworks, even though they have specified a platform: net6.0-ios, net6.0-maccatalyst
Error	NETSDK1139	The target platform identifier ios was not recognized.
Error	NETSDK1139	The target platform identifier maccatalyst was not recognized.

1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\31.0.101-preview.11.117\tools\Xamarin.Android.Aapt2.targets(157,3): error APT2260: resource style/Theme.MaterialComponents.DayNight (aka com.companyname.gettingstartedwithmaui:style/Theme.MaterialComponents.DayNight) not found.
1>\obj\Debug\net6.0-android\lp\9\jl\res\values\styles.xml(2): error APT2260: style attribute 'attr/colorPrimary (aka com.companyname.gettingstartedwithmaui:attr/colorPrimary)' not found.
1>\obj\Debug\net6.0-android\lp\9\jl\res\values\styles.xml(2): error APT2260: style attribute 'attr/colorPrimaryDark (aka com.companyname.gettingstartedwithmaui:attr/colorPrimaryDark)' not found.
1>\obj\Debug\net6.0-android\lp\9\jl\res\values\styles.xml(2): error APT2260: style attribute 'attr/colorAccent (aka com.companyname.gettingstartedwithmaui:attr/colorAccent)' not found.
1>\obj\Debug\net6.0-android\lp\9\jl\res\values\styles.xml(2): error APT2260: style attribute 'attr/materialButtonStyle (aka com.companyname.gettingstartedwithmaui:attr/materialButtonStyle)' not found.
1>\obj\Debug\net6.0-android\lp\9\jl\res\values\styles.xml(2): error APT2260: style attribute 'attr/windowActionBar (aka com.companyname.gettingstartedwithmaui:attr/windowActionBar)' not found.
1>\obj\Debug\net6.0-android\lp\9\jl\res\values\styles.xml(2): error APT2260: style attribute 'attr/windowNoTitle (aka com.companyname.gettingstartedwithmaui:attr/windowNoTitle)' not found.
1>\obj\Debug\net6.0-android\lp\9\jl\res\values\styles.xml(2): error APT2260: style attribute 'attr/windowActionModeOverlay (aka com.companyname.gettingstartedwithmaui:attr/windowActionModeOverlay)' not found.
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\31.0.101-preview.11.117\tools\Xamarin.Android.Aapt2.targets(157,3): error APT2260: resource style/Widget.MaterialComponents.Button.Icon (aka com.companyname.gettingstartedwithmaui:style/Widget.MaterialComponents.Button.Icon) not found.
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\31.0.101-preview.11.117\tools\Xamarin.Android.Aapt2.targets(157,3): error APT2062: failed linking references.
```

**Comment by marcoseraphin** [comment] 2021-12-29 08:24
No, the Workload Update is NOT out yet as Gerald described here in this video:

https://www.youtube.com/watch?v=LgBA9Iebhq8

**Comment by adaptPerception** [comment] 2021-12-30 01:00
> No, the Workload Update is NOT out yet as Gerald described here in this video:
> 
> https://www.youtube.com/watch?v=LgBA9Iebhq8

@marcoseraphin thank you for your reply. The video still seems to indicate, if you upgrade to preview 11, everything should function except the hot reload. However, I haven't tried to upgrade to preview 11. I have not installed/upgraded any additional workloads other than those that were installed with Visual Studio 2022 17.1.0 Preview 1.1. I believe this should have only installed the preview 10 workloads. So, I don't see how the workload update would be relevant in my case.

```
dotnet workload list

This command lists only workloads that were installed via `dotnet workload install` in this version of the SDK and not those that were installed via Visual Studio.

Installed Workload Ids
----------------------

Use `dotnet workload search` to find additional workloads to install.
```

**Comment by marcoseraphin** [comment] 2021-12-30 09:25
Here is a good description, but I would wait til Preview 2:

https://blog.taranissoftware.com/upgrading-to-net-maui-preview-11

**Comment by adaptPerception** [comment] 2021-12-30 15:25
> Here is a good description, but I would wait til Preview 2:
> 
> https://blog.taranissoftware.com/upgrading-to-net-maui-preview-11

@marcoseraphin thank you again for your reply. I think there is some confusion. I am not trying to upgrade to preview 11. I am still using preview 10. So, with Visual Studio 2022 17.1.0 Preview 1.1 and the preview 10 tools for MAUI (including workloads and templates) I am getting the above errors.

Templates
`Microsoft.Maui.Templates::6.0.101-preview.10.2068`

**Comment by marcoseraphin** [comment] 2021-12-30 15:32
Yep....same as me. I am also getting these errors,because 10 has these errors that will got away with version 11 included in the preview 2....BUT this is not released due to the circumstances described by Gerald.
There is a manual path for upgrading to version 11, but this is not recommended and has these manual steps described in my last link.

Marco

**Comment by adaptPerception** [comment] 2021-12-30 15:46
> Yep....same as me. I am also getting these errors,because 10 has these errors that will got away with version 11 included in the preview 2....BUT this is not released due to the circumstances described by Gerald. There is a manual path for upgrading to version 11, but this is not recommended and has these manual steps described in my last link.
> 
> Marco

Ah, I understand what you meant now. Thank you. Do you have any references to documentation stating workload 10 is broken (as the previous links only speak to the issues of upgrading to workload 11)?

**Comment by marcoseraphin** [comment] 2021-12-30 15:51
upgrading would be the only solution or wait...
as far as I understand all these infos

**Comment by marcoseraphin** [comment] 2022-01-03 12:45
Hi @jfversluis thanx for answering to this thread. I also have a problem starting a MAUI project with .Net VS 2022 17.1 Preview 1.1

After creating a blank MAUI project I am getting lots of errors, like I reported already this problem here BEFORE I saw your video on your channel:

https://github.com/dotnet/maui/issues/3651 

So, currently no chance to create a MAUI project....so I will wait for Preview 2.

Marco

**Comment by jfversluis** [comment] 2022-01-03 13:47
Thanks for being patient! Most people have been off the better part of December and during the holidays, but at least I'm back! Refreshed and ready to rock 2022!

If you can wait that's good, but I'd love to see if we can unblock people so you can start playing now! :D

The problem is that my environment is probably very different from a typical user and it's hard to reproduce this. I haven't really seen anything like this. I do have one other machine that doesn't have all my regular development bits on it, so I'll see if I can install all the latest public versions on there and see if I get something similar.

Any additional information the meantime would help!

**Comment by marcoseraphin** [comment] 2022-01-03 13:59
No problem, my productive environment is since 2013 my Macbook with the current VS for Mac version.
VS 2022 for Mac will be available at the end of the first half year...so around June 2022.

I will start new Xamarin project still with Xamarin Forms until it is releases at the end of Q1 2022.
I do not plan to upgrade my "old" Forms projects to MAUI although I am looking your videos concerning DIP, handlers and so on.

Yep...as I saw in your videos I saw a special Preview demo version on windows, that seems to be very different and not the reality out there.

I have documented my problems in the GitHub issue. The VS 2022 Preview installer show "everything ok". But the maui-check tool (current version) brings up the error (version 101 installed) and ultimately refers to the installer.

All MAUI namespaces are not recognized, no simulator found and so on. With the VS 2022 Release version installed all Xamarin Forms projects for both iOS and Android are running smoothly....but of course not with MAUI.

We can do a Teams (desktop sharing) session if you want.

**Comment by jfversluis** [comment] 2022-01-03 14:12
While the recommended way right now is to go through Visual Studio, did you run the workload commands to see what that brings you?

What do you see when you run `dotnet workload list` I guess that's empty? Did you try installing through that way with `dotnet workload install maui`?

Only do this if you're comfortable with potentially breaking your environment (even more). I would hate to make things even worse 😬

I just tried on my secondary machine which seems to have .NET 6.0.101 (I noticed you have .100, maybe that's something?) and (public) Visual Studio 2022 17.1 Preview 1 or 1.1, whatever, the latest at least :) and .NET MAUI preview 10 and it works fine.

It seems like I did install the workloads through the CLI though initially. I'm updating to .NET MAUI preview 11 now to see if that changes anything.

**Comment by marcoseraphin** [comment] 2022-01-03 14:17
Hi Gerald,

yes it is empty because the workloads were installed from the installer. Yes I also read about the problems and breaks concerning the HotReload problem.

I found this blog article here : https://blog.taranissoftware.com/upgrading-to-net-maui-preview-11 

But the are two many manual steps and recommendations and problem. I personally ca what for the Preview 2 an install everything correctly using the Installer because as described the windows machine is NOT my productive environment.

But thanx for you great explanation videos around MAUI and also for this topic.

**Comment by jfversluis** [comment] 2022-01-03 14:19
Yeah I just tried updating the workload (through the command-line) to preview 11 and it still works fine. So if you have a machine that is just for experimenting you might want to try doing that if you can't wait. I'm kind of sad that I can't reproduce it, that would've made it easier to come up with a fix for you all!

**Comment by marcoseraphin** [comment] 2022-01-03 14:48
I am currently installing using 

dotnet workload install maui

and.....it works. 

I could start the MAUI App on the Android simulator and the Windows Desktop version. (except HotReload)
During the connection to my MacBook I am getting currently an error => Could not install workload maifest for 'ios'

The MacBook connection works with VS 2022 Release version without any problems.

Thanx for your help. We will see how the update works when Preview 2 will be released.

**Comment by jfversluis** [comment] 2022-01-03 14:50
> During the connection to my MacBook I am getting currently an error => Could not install workload maifest for 'ios'

Yeah I'm seeing that one as well. Not sure what that is all about. That worked earlier, so maybe something with preview 2 of VS indeed.

Glad you got _something_ working! :D

@adaptPerception let me know if this helps you in any way. 

Closing this for now as I'm assuming this is something that will be fixed with all the bits lining up again with preview 12. Please feel free to ping me if that isn't the case so we can get to the bottom!

**Closed by jfversluis** 2022-01-03 14:50 UTC
Labels: area/setup 🪄

**Comment by adaptPerception** [comment] 2022-01-09 03:22
> Hey everyone! Sorry this experience is a bit rough right now. To summarize all that has been said so far, it seems that building preview 10, with VS 2022 17.1 preview 1 is also not working @adaptPerception?
> 
> I see a couple of logs, but also a variation in version numbers. Some version numbers mention preview 10, later logs mention preview 11, did you try to upgrade in the meantime?

@jfversluis, sorry for the late reply. Yes, I tried three variations.

- Fresh install of VS 2022 Preview with no manually installed workloads
- Then I updated to preview 11 using the `dotnet workload install maui`
- Then I uninstalled/reinstalled the preview 11 workloads and VS 2022 Preview and repaired VS 2022 (thinking it might be an issue having them installed side by side).

**Comment by samifahmy** [comment] 2022-01-16 01:43
i still have same issue
i have visual Studio 2022 Enterprise Preview 2,
any suggestion? 
![image](https://user-images.githubusercontent.com/29284836/149644048-423aec29-63c9-4c9b-88a5-f5ca2f7f9de6.png)

> .NET SDK Checkup...
  - 3.1.415 - C:\Program Files\dotnet\sdk\3.1.415
  - 5.0.301 - C:\Program Files\dotnet\sdk\5.0.301
  - 5.0.303 - C:\Program Files\dotnet\sdk\5.0.303
  - 6.0.101 - C:\Program Files\dotnet\sdk\6.0.101
  - 6.0.200-preview.21617.4 - C:\Program Files\dotnet\sdk\6.0.200-preview.21617.4

> .NET SDK - Workload Deduplication Checkup...

> Edge WebView2 Checkup...
  - Found Edge WebView2 version 97.0.1072.55

> .NET SDK - Workloads (6.0.100) Checkup...
  × android-aot (Microsoft.NET.Sdk.Android.Manifest-6.0.100 : 31.0.101-preview.10.59) not installed.
  × ios (Microsoft.NET.Sdk.iOS.Manifest-6.0.100 : 15.0.101-preview.10.251) not installed.
  × maccatalyst (Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.100 : 15.0.101-preview.10.251) not installed.
  × tvos (Microsoft.NET.Sdk.tvOS.Manifest-6.0.100 : 15.0.101-preview.10.251) not installed.
  × macos (Microsoft.NET.Sdk.macOS.Manifest-6.0.100 : 12.0.101-preview.10.251) not installed.
  × maui (Microsoft.NET.Sdk.Maui.Manifest-6.0.100 : 6.0.101-preview.10.2068) not installed.
  × wasm-tools (microsoft.net.workload.mono.toolchain.manifest-6.0.100 : 6.0.0) not installed.
  - microsoft-net-sdk-emscripten (microsoft.net.workload.emscripten.manifest-6.0.100 : 6.0.0) installed.
! Managing Workload installation from the CLI is NOT recommended.  Instead you should install the latest Visual Studio
preview to automatically get the newest release of .NET MAUI workloads installed.
Are you sure you would like to continue the CLI workload installation? [y/n] (n): y

─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
¤ Recommendation: Install or Update SDK Workloads
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

! Attempt to fix? [y/n] (y): y
» Attempting to fix: .NET SDK - Workloads (6.0.100)
SHELL: C:\Program Files\dotnet\dotnet.exe workload install --from-rollback-file "C:\Users\xxxx\AppData\Local\Temp\maui-check-8f545a96\workload.json" android-aot ios maccatalyst tvos macos maui wasm-tools --source "https://api.nuget.org/v3/index.json"

Workload(s) 'maui' are already installed.
Failed to update the advertising manifest microsoft.net.sdk.android: microsoft.net.sdk.android.manifest-6.0.200 is not found in NuGet feeds https://api.nuget.org/v3/index.json"..
Failed to update the advertising manifest microsoft.net.sdk.ios: microsoft.net.sdk.ios.manifest-6.0.200 is not found in NuGet feeds https://api.nuget.org/v3/index.json"..
Failed to update the advertising manifest microsoft.net.sdk.macos: microsoft.net.sdk.macos.manifest-6.0.200 is not found in NuGet feeds https://api.nuget.org/v3/index.json"..
Failed to update the advertising manifest microsoft.net.sdk.tvos: microsoft.net.sdk.tvos.manifest-6.0.200 is not found in NuGet feeds https://api.nuget.org/v3/index.json"..
Failed to update the advertising manifest microsoft.net.sdk.maui: microsoft.net.sdk.maui.manifest-6.0.200 is not found in NuGet feeds https://api.nuget.org/v3/index.json"..
Failed to update the advertising manifest microsoft.net.workload.emscripten: microsoft.net.workload.emscripten.manifest-6.0.200 is not found in NuGet feeds https://api.nuget.org/v3/index.json"..
Failed to update the advertising manifest microsoft.net.workload.mono.toolchain: microsoft.net.workload.mono.toolchain.manifest-6.0.200 is not found in NuGet feeds https://api.nuget.org/v3/index.json"..
Failed to update the advertising manifest microsoft.net.sdk.maccatalyst: microsoft.net.sdk.maccatalyst.manifest-6.0.200 is not found in NuGet feeds https://api.nuget.org/v3/index.json"..

**Comment by adaptPerception** [comment] 2022-01-16 03:05
I upgraded to Version 17.1.0 Preview 2.0, and I also am getting the same errors.

**Comment by Ghevi** [comment] 2022-01-19 15:21
While using Version.17.1.0 Preview 2.0, with a Maui Blazor project I get these errors
![Screenshot 2022-01-19 162022](https://user-images.githubusercontent.com/39503352/150160489-99193264-6008-4ef7-aefb-c60782d3424c.png)
Launching the app with windows machine works but no the android emulator, nor deploying to an android device.

**Comment by pierre01** [comment] 2022-01-27 00:47
I have preview 4 and I  have the same issues:
 dotnet : Workload installation failed: One or more errors occurred. (microsoft.maui.core.ref.android.msi.x64::6.0.200-preview.13.2465 is not found in NuGet feeds 
https://api.nuget.org/v3/index.json;https://aka.ms/maui-preview/index.json;C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\".)

**Comment by jfversluis** [comment] 2022-01-27 08:33
Hey all, you shouldn't have to use `maui-check` anymore for the workloads. In fact, we recommend uninstalling all the earlier preview bits and reinstall the latest Visual Studio 2022 preview, it should be good then.

If you still need to install the workloads manually try this command `dotnet workload install maui --source https://api.nuget.org/v3/index.json`.

The `dotnet workload install` command uses any local nuget feeds it might find on your system, that's why it's important to only use the public NuGet one to get the latest, publicly available version. Another option is to explicitly specify a version like: `dotnet workload install maui --from-rollback-file https://aka.ms/dotnet/maui/preview.12.json --source https://aka.ms/dotnet6/nuget/index.json --source https://api.nuget.org/v3/index.json`

Preview 12 is the latest one at the time of this comment.

**Comment by pierre01** [comment] 2022-01-27 09:15
@jfversluis  Thank you! your first option didn't work but   the other option with the specific version did work .

**Comment by IrinaDoroshenkoXamarin** [comment] 2022-02-06 14:07
> Hey all, you shouldn't have to use `maui-check` anymore for the workloads. In fact, we recommend uninstalling all the earlier preview bits and reinstall the latest Visual Studio 2022 preview, it should be good then.
> 
> If you still need to install the workloads manually try this command `dotnet workload install maui --source https://api.nuget.org/v3/index.json`.
> 
> The `dotnet workload install` command uses any local nuget feeds it might find on your system, that's why it's important to only use the public NuGet one to get the latest, publicly available version. Another option is to explicitly specify a version like: `dotnet workload install maui --from-rollback-file https://aka.ms/dotnet/maui/preview.12.json --source https://aka.ms/dotnet6/nuget/index.json --source https://api.nuget.org/v3/index.json`
> 
> Preview 12 is the latest one at the time of this comment.

I tried 
dotnet workload install maui --from-rollback-file https://aka.ms/dotnet/maui/preview.12.json --source https://aka.ms/dotnet6/nuget/index.json --source https://api.nuget.org/v3/index.json

but I have an issue "Inadequate permissions. Run the command with elevated privileges."  What I missed?

**Comment by adaptPerception** [comment] 2022-02-07 01:53
Uninstalling 17.1.0 Preview 2.0 and installing version 17.1.0 Preview 5.0 fixed it for me.
