### ISSUE TITLE
[Enhancement] Web support!

### ISSUE THREAD

**Issue by Suriman** [dotnet/maui#143] opened 2020-06-06 17:24 UTC
For all those companies that for years have developed native applications it would be very useful to take advantage of knowledge and experience, to be able to generate a Web application from MAUI, using XAML, the MVVM pattern and C #. Blazor forces you to use Razor syntax and the component model is not reusable, so it is not the ideal choice.

**Comment by Rand-Random** [comment] 2020-06-06 19:16
Duplicate of https://github.com/dotnet/maui/issues/62

**Closed** 2020-09-14 20:13 UTC
Labels: proposal-open
