### ISSUE TITLE
Project naming issue

### ISSUE THREAD

**Issue by handicraftsman** [dotnet/maui#113] opened 2020-05-26 10:22 UTC
I don't know if you already noticed this, but there is already a GUI toolkit called `maui` - it is based over Qt5 and KDE's Kirigami and can be found at https://mauikit.org/

**Comment by shanranm** [comment] 2020-05-26 10:26
duplicate of #34, #35

**Comment by Happypig375** [comment] 2020-05-26 10:26
Stop reposting the same content as #34

**Comment by Happypig375** [comment] 2020-05-26 10:26
We already have
dotnet/maui#34
dotnet/maui#35
dotnet/maui#51
dotnet/maui#58
dotnet/maui#67
dotnet/maui#74
dotnet/maui#87

**Comment by jsuarezruiz** [comment] 2020-05-26 11:09
Duplicate of #34.

**Closed by jsuarezruiz** 2020-05-26 11:09 UTC
Labels: duplicate
