### ISSUE TITLE
x:Array as resource with key crashes app on device launch

### ISSUE THREAD

**Issue by davidortinau** [dotnet/maui#9422] opened 2022-08-14 21:31 UTC
### Description

This works in the iOS simulator and on desktop. The goal is to have an array of data I can reuse by key.

```
<?xml version="1.0" encoding="UTF-8" ?>
<?xaml-comp compile="true" ?>
<ResourceDictionary 
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml">

    <x:Array Type="{x:Type x:String}" x:Key="CategoriesArray">
        <x:String>Noodles</x:String>
        <x:String>Rice</x:String>
        <x:String>Appetizers</x:String>
        <x:String>Desserts</x:String>
        <x:String>Beverages</x:String>
    </x:Array>

</ResourceDictionary>
```

This initially was in the Styles.xaml which I split apart for troubleshooting and used merged dictionaries.

That doesn't work on an iOS device. I get an error about the type converter failing.

The below however **does** work on the `ContentPage`s:

```
<BindableLayout.ItemsSource>
    <x:Array Type="{x:Type x:String}" >
        <x:String>Noodles</x:String>
        <x:String>Rice</x:String>
        <x:String>Appetizers</x:String>
        <x:String>Desserts</x:String>
        <x:String>Beverages</x:String>
    </x:Array>
</BindableLayout.ItemsSource>
```

### Steps to Reproduce

Add an array with key to your styles, bind to a BindableLayout, and then run on an iOS device.

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15

### Did you find any workaround?

don't use a resource

**Comment by AlexanderEgorov** [comment] 2022-12-16 10:44
maui-ios                       7.0.52/7.0.100        SDK 7.0.100
maui-android               7.0.52/7.0.100        SDK 7.0.100

Related issues: 
* https://github.com/dotnet/maui/issues/6070
* https://github.com/dotnet/maui/issues/5531


```csharp
        string GetXaml(string resource, string content) {
            return $@"
<ContentPage xmlns=""http://schemas.microsoft.com/dotnet/2021/maui"" xmlns:x=""http://schemas.microsoft.com/winfx/2009/xaml"">
    <ContentPage.Resources>
        {resource}
    </ContentPage.Resources>
    {content}
</ContentPage>";
        }

        //Throws a XamlParseException on real device (iOS and Android) when app is build in Release configuration 
        //Works fine in Debug configuration or on simulators.
        [Test]
        public async Task LoadXamlTest1() {
            var xaml = GetXaml(
                @"<x:String x:Key=""text"">TEST</x:String>",
                @"<Button Text=""{StaticResource text}""/>");
            var cp = new ContentPage().LoadFromXaml(xaml);
            var bt = (Button)cp.Content;
            Assert.AreEqual("TEST", bt.Text);
        }

        //Throws a XamlParseException on real device (iOS and Android) when app is build in Release configuration 
        //Works fine in Debug configuration or on simulators.
        [Test]
        public async Task LoadXamlTest2() {
            var xaml = GetXaml(
                @"<x:Double x:Key=""borderWidth"">3</x:Double>",
                @"<Button BorderWidth=""{StaticResource borderWidth}""/>");
            var cp = new ContentPage().LoadFromXaml(xaml);
            var bt = (Button)cp.Content;
            Assert.AreEqual(3, bt.BorderWidth);
        }

        //Throws a XamlParseException on real device (iOS and Android) when app is build in Release configuration 
        //Works fine in Debug configuration or on simulators. 
        [Test]
        public async Task LoadXamlTest3() {
            var xaml = GetXaml(
                @"<x:Int32 x:Key=""borderWidth"">3</x:Int32>",
                @"<Button CornerRadius=""{StaticResource borderWidth}""/>");
            var cp = new ContentPage().LoadFromXaml(xaml);
            var bt = (Button)cp.Content;
            Assert.AreEqual(3, bt.CornerRadius);
        }

         //Works file
        [Test]
        public async Task LoadXamlTest4() {
            var xaml = GetXaml(
                @"<Color x:Key=""borderColor"">#FF0000</Color>",
                @"<Button BorderColor=""{StaticResource borderColor}""/>");
            var cp = new ContentPage().LoadFromXaml(xaml);
            var bt = (Button)cp.Content;
            Assert.AreEqual(Colors.Red, bt.BorderColor);
        }
         //Works file
        [Test]
        public async Task LoadXamlTest5() {
            var xaml = GetXaml(
                @"<Thickness x:Key=""margin"">4</Thickness>",
                @"<Button Margin=""{StaticResource margin}""/>");
            var cp = new ContentPage().LoadFromXaml(xaml);
            var bt = (Button)cp.Content;
            Assert.AreEqual(new Thickness(4), bt.Margin);
        }
         //Works file
        [Test]
        public async Task LoadXamlTest6() {
            var xaml = GetXaml(
                @"<FontAttributes x:Key=""fontAttributes"">Italic</FontAttributes>",
                @"<Button FontAttributes=""{StaticResource fontAttributes}""/>");
            var cp = new ContentPage().LoadFromXaml(xaml);
            var bt = (Button)cp.Content;
            Assert.AreEqual(FontAttributes.Italic, bt.FontAttributes);
        }
         //Works file
        [Test]
        public async Task LoadXamlTest7() {
            var xaml = GetXaml(
                @"<x:Array x:Key=""source"" Type=""{x:Type Color}"">
                    <Color>#FF0000</Color>
                </x:Array>",
                @"<ListView ItemsSource=""{StaticResource source}"" />");
            var cp = new ContentPage().LoadFromXaml(xaml);
            var l = (ListView)cp.Content;
            Assert.AreEqual(1, l.ItemsSource.OfType<object>().Count());
        }
```

**Comment by vhugogarcia** [comment] 2023-01-19 18:29
Hello friends,

This issue is still happening and it forced me to remove any reference to x:Double and x:String on my styles resource dictionary, so I could be able to run the application on DEBUG mode + Link SDK Assemblies only selected on iOS, just to figure out an issue on release mode only was facing.

> Visual Studio Community 2022 for Mac
> Version 17.4.3 (build 21)
> maui-ios                   7.0.58/7.0.100        SDK 7.0.100  

If you need anything from me =), please let me know I will be happy to share anything you need to reproduce the issue, however our friend @davidortinau I believe he explained it very simple and how to reproduce it.

Thanks in advance 👍🏻

**Comment by Nibby** [comment] 2023-02-05 04:55
I can also attest that this issue is still happening. On a blank MAUI template project, adding `x:String` entries to the `Styles.xaml` resource dictionary causes iOS device deployment to fail (when `<MtouchLink>` is set to `SdkOnly` in the csproj file). This is a serious blocker to a project I am working on. 

My workload version are as follows:
```
Installed Workload Id      Manifest Version       Installation Source
---------------------------------------------------------------------
wasm-tools                 7.0.2/7.0.100          SDK 7.0.100        
macos                      13.1.1007/7.0.100      SDK 7.0.100        
maui-maccatalyst           7.0.59/7.0.100         SDK 7.0.100        
maui-ios                   7.0.59/7.0.100         SDK 7.0.100        
maui-android               7.0.59/7.0.100         SDK 7.0.100        
ios                        16.2.1007/7.0.100      SDK 7.0.100        
maccatalyst                16.2.1007/7.0.100      SDK 7.0.100        
maui                       7.0.59/7.0.100         SDK 7.0.100        
android                    33.0.26/7.0.100        SDK 7.0.100   
```

Hope this issue can be fixed in the near future.

**Comment by Eskissimo** [comment] 2023-02-11 16:07
Hi,

The issue happens also when we publish Android app with AOT enable.

Regards.

**Comment by jonathanpeppers** [comment] 2023-04-11 22:27
I can repro this in `Release` mode (but works fine `Debug`):

![image](https://user-images.githubusercontent.com/840039/231302327-3f583926-a71e-4f30-95e6-37383da59fa6.png)

One thing to note is that compiled `.xaml` appears to work fine for me. So, you can use XamlCompilation for now, and avoid things like `LoadFromXaml("your xaml string")`?

**Comment by vhugogarcia** [comment] 2023-04-12 04:24
Hello @jonathanpeppers ,

Thanks for looking into this issue. 

It is also easy to reproduce it on DEBUG mode. Just enable: Link SDKs frameworks only and try it. 😎👍🏻

If there is anything else I can do to reproduce the issue let me know. I am happy to help 👍🏻🙂

**Comment by jonathanpeppers** [comment] 2023-04-12 13:21
@vhugogarcia is there a reason you're not using compiled XAML?

From my testing, the defaults work:

* Debug mode works: parsed xaml + no trimming
* Release mode works: compiled xaml + trimming

The only place you hit this issue is trimming + parsed xaml.

**Comment by vhugogarcia** [comment] 2023-04-12 17:29
> Note that I only tried Android so far, perhaps this fails on iOS with Debug defaults?

You are correct @jonathanpeppers . When you set DEBUG mode and set Link SDK Assemblies only it fails as well f**or iOS emulators or physical devices.**

<img width="1580" alt="image" src="https://user-images.githubusercontent.com/1047398/231536629-bebc20c7-fc6b-4ad6-9d59-7d6f3049364f.png">

I'm sharing here a repository in case you need it. https://github.com/vhugogarcia/MauiStylesDemo

**Comment by jonathanpeppers** [comment] 2023-04-12 17:30
> Link SDK Assemblies only

But you had to turn this on for iOS? It wasn't the default setting?

**Comment by vhugogarcia** [comment] 2023-04-12 17:32
Yes, I had to set Link SDK Assemblies only setting on DEBUG mode, because I faced an issue when the app was in the stores and several clients reported an issue and I was unable to reproduce the issue because when I debug locally simulators or physical devices the Linker is set to NONE, which works fine for development. However, in order for me to reproduce the issue the customers and users are facing I have to mimic the release mode but with the ability to set breakpoints on VS for macOS.

**Comment by jonathanpeppers** [comment] 2023-04-12 17:40
So, you'd probably want to also enable `<MauiXamlCValidateOnly>false</MauiXamlCValidateOnly>` if you are testing in this way:

https://github.com/dotnet/maui/blob/13e66e0d0409f8b0ef179e6804a3500515b7fdbe/src/Controls/src/Build.Tasks/nuget/buildTransitive/netstandard2.0/Microsoft.Maui.Controls.targets#L150-L151

**Comment by vhugogarcia** [comment] 2023-04-12 17:47
> So, you'd probably want to also enable `<MauiXamlCValidateOnly>false</MauiXamlCValidateOnly>` if you are testing in this way:
> 
> https://github.com/dotnet/maui/blob/13e66e0d0409f8b0ef179e6804a3500515b7fdbe/src/Controls/src/Build.Tasks/nuget/buildTransitive/netstandard2.0/Microsoft.Maui.Controls.targets#L150-L151

I tried adding those and they did not work @jonathanpeppers . See screenshot below. Even adding those settings on the .csproj file

<img width="1784" alt="image" src="https://user-images.githubusercontent.com/1047398/231541056-96f63edf-7905-4611-8550-6442930b69c1.png">

<img width="1415" alt="image" src="https://user-images.githubusercontent.com/1047398/231541155-23f8cd8e-0aca-4a23-ae78-f37f3e13aacc.png">

**Comment by jonathanpeppers** [comment] 2023-04-12 17:50
Actually, I'm reading it wrong, it would be `<_MauiForceXamlCForDebug>true</_MauiForceXamlCForDebug>`.

I'm not a fan of the MSBuild logic is here... It might be something I can fix for them.

**Comment by vhugogarcia** [comment] 2023-04-12 18:03
Thanks @jonathanpeppers for the feedback. I remember I tried that in the past without luck. However, I tried it again just to double check and this is the result. It worked OK 👍🏻 .

So the results are below (iOS):

Using `<_MauiForceXamlCForDebug>true</_MauiForceXamlCForDebug>` in the .csproj file
- **DEBUG** + **Linker None** = Error
- **DEBUG** + **Linker SDK Assemblies Only** = OK
- **DEBUG** + **Linker All** = OK

Not using `<_MauiForceXamlCForDebug>true</_MauiForceXamlCForDebug>` in the .csproj file
- **DEBUG** + **Linker None** = OK
- **DEBUG** + **Linker SDK Assemblies Only** = Error
- **DEBUG** + **Linker All** = Error _(Position 9:37. Cannot assign property "Source": Property does not exist, or is not assignable, or mismatching type between value and property)_

So, what makes this interesting is why I should add that property in the .csproj file if I'm already declaring this on the Styles.xaml file <?xaml-comp compile="true" ?>
<img width="591" alt="image" src="https://user-images.githubusercontent.com/1047398/231544580-4a58217a-9d52-4d75-bab2-a46e1e24c2e1.png">

**Closed** 2023-04-17 13:37 UTC
Labels: t/bug, area/Xaml </>, platform/iOS 🍎, p/1, partner/cat 😻
