### ISSUE TITLE
Improve AppVersion single project manifest support

### ISSUE THREAD

**Issue by Redth** [dotnet/maui#1662] opened 2021-07-13 17:31 UTC
We need to update the targets/logic to this spec:

## Application Version
 - `<ApplicationVersion>1</ApplicationVersion>`
 - iOS: `CFBundleVersion`
 - Android: `android:versionCode`
 - WinUI: `//Package/Identity[@Version]` Only if ApplicationDisplayVersion not set
 - Must be validated as an integer (iOS supports x.y.z but we are forcing a lowest common denominator here)

## Application Display Version
- `<ApplicationDisplayVersion>1.0.0</ApplicationDisplayVersion>`
- iOS: `CFBundleShortVersionString`
- Android: android:versionName
- WinUI:  `//Package/Identity[@Version]` (supercedes ApplicationVersion)
- Must be validated as a x.y.z version string

**Comment by jonathanpeppers** [comment] 2021-07-13 20:38
Related changes in Android/iOS:
* https://github.com/xamarin/xamarin-android/commit/4f74bab0ab7be4627bd4588909ffb35da9a9653b
* https://github.com/xamarin/xamarin-macios/commit/a9c21ef79170d08b6d4542dcd36ca92a41a5f5e5

**Comment by jonathanpeppers** [comment] 2021-07-14 20:27
The changes above seem great for Android, but I wonder about iOS.

So considering the changes above were in place, if I was building an app I might take the "lazy" approach of:
```xml
<ApplicationVersion>$(BUILD_BUILDNUMBER)</ApplicationVersion>
<!-- Or for local dev -->
<ApplicationVersion Condition="'$(ApplicationVersion)' ==''">1</ApplicationVersion>
<ApplicationDisplayVersion>1.0.$(ApplicationVersion)</ApplicationDisplayVersion>
```
Using the Azure DevOps (ADO) vars: https://docs.microsoft.com/azure/devops/pipelines/build/variables

Then I'd increment `$(ApplicationDisplayVersion)` on each release like 1.1, 1.2, 2.0, 2.1, etc. I'd push builds directly to Google Play alpha/beta channel and Test Flight from ADO.

A small company's ADO instance might have build numbers less than 10000, but DevDiv has numbers like 4977899.

So would values like this be OK?
```xml
<key>CFBundleVersion</key>
<string>4977899</string>
<key>CFBundleShortVersionString</key>
<string>1.1.4977899</string>
```
@rolfbjarne what do you think? At what point would a large integer break the App Store? Or would it be fine?

**Comment by rolfbjarne** [comment] 2021-07-15 06:08
> @rolfbjarne what do you think? At what point would a large integer break the App Store? Or would it be fine?

The [documentation](https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html#//apple_ref/doc/uid/20001431-102364) about `CFBundleVersion` says: "The first number represents the most recent major release and is limited to a maximum length of four digits."

So you're basically limited to 10k versions with this scheme.

**Comment by jonathanpeppers** [comment] 2021-07-15 22:00
So the only way for that a number higher than 10000 to work would be:
```xml
<BuildNumber>$(BUILD_BUILDNUMBER)</BuildNumber>
<!-- Or for local dev -->
<BuildNumber Condition="'$(BuildNumber)' ==''">1</BuildNumber>
<ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
<ApplicationVersion Condition="$(TargetFramework.Contains('android')">$(BuildNumber)</ApplicationVersion>
<ApplicationVersion Condition="!$(TargetFramework.Contains('android')">$(ApplicationDisplayVersion).$(BuildNumber)</ApplicationVersion>
```

So you'd have `1.0.4977899` on iOS and `4977899` for the versionCode on Android.

**Comment by rolfbjarne** [comment] 2021-07-16 10:00
> So you'd have `1.0.4977899` on iOS

Apple says: "The third number represents the most recent minor bug fix and is limited to a maximum length of two digits."

And the same thing about the second number: "The second number represents the most recent significant revision and is limited to a maximum length of two digits."

**Comment by jonathanpeppers** [comment] 2021-07-16 14:01
Yeah, I'm not seeing how iOS can use large numbers at all after reading this document...

When I did something like this in the past, our Azure DevOps must have had build numbers less than 10000.

**Comment by jonathanpeppers** [comment] 2021-07-16 14:02
Or maybe we used some "git commit distance" value.

**Comment by jonathanpeppers** [comment] 2021-07-23 15:22
@rolfbjarne did you have any objections to the suggested change here? If not, I can look into implementing this after Preview 7.

**Comment by rolfbjarne** [comment] 2021-07-23 15:28
No objections.

But if we're doing this:

> * Must be validated as an integer (iOS supports x.y.z but we are forcing a lowest common denominator here)

we might also validate that the integer is <= 9999 (to not break iOS).

**Comment by vhugogarcia** [comment] 2021-07-23 18:34
I like it. However, what is the idea to separate them in case we need it? Because maybe at launch they be the same, but at some point they will be different when updating apps for bug fixes, etc.

**Comment by jonathanpeppers** [comment] 2021-07-23 20:42
@vhugogarcia you can use `Condition` to do whatever you need on different TFMs. For example:

```xml
<ApplicationVersion Condition="$(TargetFramework.Contains('android'))">1</ApplicationVersion>
<ApplicationVersion Condition="$(TargetFramework.Contains('ios'))">1.0.0</ApplicationVersion>
```

**Comment by vhugogarcia** [comment] 2021-07-24 00:57
> @vhugogarcia you can use `Condition` to do whatever you need on different TFMs. For example:
> 
> 
> 
> ```xml
> 
> <ApplicationVersion Condition="$(TargetFramework.Contains('android'))">1</ApplicationVersion>
> 
> <ApplicationVersion Condition="$(TargetFramework.Contains('ios'))">1.0.0</ApplicationVersion>
> 
> ```

That is sooo cool!! Perfect then 💪🏻. Thanks for sharing it.

**Comment by bramborman** [comment] 2021-07-28 20:07
I also like it, but there is already a bunch of version properties like `AssemblyVersion`, `FileVersion`, `InformationalVersion`, `PackageVersion` etc. By default they all use a value of `Version`, so it's a one-stop-shop for all your versioning needs...
See [MSBuild Version Properties Cheatsheet](https://jonlabelle.com/snippets/view/markdown/msbuild-version-properties-cheatsheet).

I think these versions should use its value, too. The `ApplicationVersion` is a problem as it has to be an integer on Android, but at least the `ApplicationDisplayVersion` should somehow use/set its value.

Consider a `Directory.Build.props` file where you set the common version of all projects in your solution, which are libraries and a client app. You'd like to set the versions just once. It would be nice if we could just set `Version` and `ApplicationVersion` and have them set the rest.

**Comment by jonathanpeppers** [comment] 2021-07-30 16:46
See the spec on this: https://github.com/xamarin/xamarin-android/blob/main/Documentation/guides/OneDotNetSingleProject.md

Looks like the appropriate code is in: https://github.com/dotnet/sdk/blob/c2087c5adc9a31982afbc901a242ba38199bad3a/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.GenerateAssemblyInfo.targets#L186-L214

We can add `$(Version)` so it also influences `$(ApplicationVersion)`.

I started on: https://github.com/xamarin/xamarin-android/pull/6139

So all I think I need to add here is support for `$(Version)`.

**Comment by jonathanpeppers** [comment] 2021-08-04 18:43
I did some testing with `$(Version)`, and I think the defaults would be:
```xml
<PropertyGroup>
  <Version Condition=" '$(ApplicationVersion)' != '' ">$(ApplicationVersion)</Version>
  <ApplicationVersion Condition=" '$(ApplicationVersion)' == '' ">$(Version)</ApplicationVersion>
  <ApplicationVersion Condition=" '$(ApplicationVersion)' == '' ">1</ApplicationVersion>
  <ApplicationDisplayVersion Condition=" '$(ApplicationDisplayVersion)' == '' ">$(ApplicationVersion)</ApplicationDisplayVersion>
</PropertyGroup>
```
See: https://github.com/xamarin/xamarin-android/pull/6139

Our templates will just use `$(ApplicationVersion)`, which will override `$(Version)` and set *all* the values we need like `$(AssemblyVersion)`, `$(FileVersion)`, and `$(InformationalVersion)`.

If you used `$(Version)` instead, it would also work as expected.

**Comment by mattleibow** [comment] 2021-08-06 14:04
Maybe Version needs a condition to make sure you don't overwrite the value if the user set it? Version='' and AppVersion!=''

**Comment by jonathanpeppers** [comment] 2021-08-06 14:16
The problem is `Version` defaults to `1.0.0` from the .NET SDK, so there isn't a way to tell if the user sets it or not...

**Comment by mattleibow** [comment] 2021-08-06 17:53
Will this cause issues if I set version to 1.3.55? I may want my assembly version to be that.

AppVersion is just a single integer, so these concepts are not really compatible

**Comment by jonathanpeppers** [comment] 2021-08-09 20:44
So @mattleibow do you think this is a better idea?
```xml
<PropertyGroup>
  <ApplicationVersion Condition=" '$(ApplicationVersion)' == '' ">1</ApplicationVersion>
  <Version Condition=" '$(ApplicationDisplayVersion)' != '' ">$(ApplicationDisplayVersion)</Version>
  <ApplicationDisplayVersion Condition=" '$(ApplicationDisplayVersion)' == '' ">$(ApplicationVersion)</ApplicationDisplayVersion>
</PropertyGroup>
```

This way:
1. If `$(ApplicationDisplayVersion)` is specified in your project, it will be used for `$(Version)`.
1. If `$(ApplicationDisplayVersion)` is blank in your project, we'll have the .NET SDK's default value of `$(Version)`.

It doesn't seem like we can use the value of `$(Version)` to do anything here because the .NET SDK defaults it to `1.0.0`? We expect mobile apps to set `$(ApplicationVersion)` and `$(ApplicationDisplayVersion)`?

**Comment by mattleibow** [comment] 2021-08-10 17:54
Maybe the other way around? We use version in appdisplayversion. Doesn't matter if it is 1.0.0 since we can override with ADV.

Just like we do with PackagwVersion and AssemblyInfoVeraion.

So I would write my csproj to be AppVersion and Version? Might be a bit weird, so what you have. But, it always overrides so I have no way to set Version now.

**Comment by mattleibow** [comment] 2021-09-28 10:57
This is now merged and all working.

**Closed by mattleibow** 2021-09-28 10:57 UTC
