### ISSUE TITLE
Toolbar items are affected from previous page on Android

### ISSUE THREAD

**Issue by pekspro** [dotnet/maui#10452] opened 2022-10-02 18:34 UTC
### Description

I have a page with three primary items and three secondary items:

![image](https://user-images.githubusercontent.com/3163293/193469814-13ebd063-14e9-4cdd-930c-ecb98035f342.png)

This page is correct. But when navigating to second page, there should be two primary and two secondaries, but instead there is three primaries:

![image](https://user-images.githubusercontent.com/3163293/193469826-f4463673-2f3b-4de6-bc55-c6e2e922c2bc.png)

And the third page should have one primary and one secondary items, but both are shown as primary:

![image](https://user-images.githubusercontent.com/3163293/193469872-c67e0fee-8248-48e8-98df-8f8be965e449.png)

My guess is that the new page will have always has the same amount as primary items as the previous page. 

This issue is only on Android. It works as expected on Windows at least.

### Steps to Reproduce

1. Create a new MAUI app.
2. Update the main page:

``` XAML
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MauiIssues.MainPage">

    <ContentPage.ToolbarItems>
        <ToolbarItem Text="Primary 1" />
        <ToolbarItem Text="Primary 2" />
        <ToolbarItem Text="Primary 3" />
        <ToolbarItem Text="Secondary 1"
                     Order="Secondary" />
        <ToolbarItem Text="Secondary 2"
                     Order="Secondary" />
        <ToolbarItem Text="Secondary 3"
                     Order="Secondary" />
    </ContentPage.ToolbarItems>

    <VerticalStackLayout>
        <Label 
            Text="First page. Three primary, and three secondary."
            VerticalOptions="Center" 
            HorizontalOptions="Center" />

        <Button 
            x:Name="ButtonNavigate"
            Text="Go to second page"
            Clicked="ButtonNavigate_Clicked"
            HorizontalOptions="Center" />

    </VerticalStackLayout>
</ContentPage>
```

``` CS
public partial class MainPage : ContentPage
{
	public MainPage()
	{
		InitializeComponent();
	}

	private async void ButtonNavigate_Clicked(object sender, EventArgs e)
	{
        await Shell.Current.GoToAsync(nameof(SecondaryPage));
	}
}
```

3. Add second page:

``` XAML
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MauiIssues.SecondaryPage"
             Title="Second">
    <ContentPage.ToolbarItems>
        <ToolbarItem Text="Primary 1" />
        <ToolbarItem Text="Primary 2" />
        <ToolbarItem Text="Secondary 1"
                     Order="Secondary" />
        <ToolbarItem Text="Secondary 2"
                     Order="Secondary" />
    </ContentPage.ToolbarItems>
    
    <VerticalStackLayout>
        <Label 
            Text="Second page. Two primary, and two secondary."
            VerticalOptions="Center" 
            HorizontalOptions="Center" />

        <Button 
            x:Name="ButtonNavigate"
            Text="Go to third page"
            Clicked="ButtonNavigate_Clicked"
            HorizontalOptions="Center" />

    </VerticalStackLayout>
</ContentPage>
``` 

``` CS
public partial class SecondaryPage : ContentPage
{
	public SecondaryPage()
	{
		InitializeComponent();
	}

	private async void ButtonNavigate_Clicked(object sender, EventArgs e)
	{
		await Shell.Current.GoToAsync(nameof(ThirdPage));
	}
}
``` 

4. Add third page:

``` XAML
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MauiIssues.ThirdPage"
             Title="Third">
    <ContentPage.ToolbarItems>
        <ToolbarItem Text="Primary 1" />
        <ToolbarItem Text="Secondary 1"
                     Order="Secondary" />
    </ContentPage.ToolbarItems>

    <VerticalStackLayout>
        <Label 
            Text="Third page. One primary, and one secondary."
            VerticalOptions="Center" 
            HorizontalOptions="Center" />
    </VerticalStackLayout>
</ContentPage>
```

``` CS
public partial class ThirdPage : ContentPage
{
	public ThirdPage()
	{
		InitializeComponent();
	}
}
```

### Link to public reproduction project repository

https://github.com/pekspro/MauiIssues/tree/10452_Toolbar_items_are_affected_from_previous_page

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

### Did you find any workaround?

Adding the code below to an affected page does solve the problem. But there will be some flickering on navigation.

``` CS
#if ANDROID
    protected override void OnNavigatedTo(NavigatedToEventArgs args)
    {
        base.OnNavigatedTo(args);

        var secondayToolBarItems = ToolbarItems.Where(x => x.Order == ToolbarItemOrder.Secondary).ToList();

        foreach (var item in secondayToolBarItems)
        {
            ToolbarItems.Remove(item);
        }

        Application.Current.Dispatcher.Dispatch(() =>
        {
            foreach (var item in secondayToolBarItems)
            {
                ToolbarItems.Add(item);
            }
        });
    }
#endif

```

**Comment by pekspro** [comment] 2022-11-11 17:27
I've updated sample application to .NET 7. The same issue remains.

**Comment by justcivah** [comment] 2022-12-22 12:07
I understand the desire to prioritize certain issues, but this bug is causing significant inconvenience. Is there any way we can move this issue to a higher priority in the roadmap so it can be addressed as soon as possible?

**Comment by pekspro** [comment] 2022-12-22 21:37
@justcivah, I share your pain. If you upvote this issue might get more attention :-).

For me `ToolbarItems` is one of the hardest issues. For some days ago I tried to dynamically add and remove toolbar items. In debugging, the `ToolbarItems` list looked right but the UI wasn’t always in sync. Unfortunately, I haven’t found an easy way to solve this despite spending hours on that problem.

**Comment by eamonnalphin** [comment] 2023-01-27 02:26
Just came across this issue too. Page 1 has a "+" sign (good), navigate to page 2 where it's supposed to be "edit" and it's still a "+" even though it uses the "edit" command I gave it.

**Comment by nicop85** [comment] 2023-03-01 13:15
Same here, hope it gets more attention and goes up in the priority list!

**Comment by NabodevMats** [comment] 2023-03-05 13:56
Same problem! +1 on upvoting priority list

**Comment by tataelm** [comment] 2023-03-21 15:54
This issue exists for more than a year. https://github.com/dotnet/maui/issues/7823 and still no patch. A production ready code can't be fully ready because of this. Please take this issue in the priority list.

**Comment by jsuarezruiz** [comment] 2023-04-13 08:49
Have been doing some tests with the current main branch where cannot reproduce the issue.
![issue-10452](https://user-images.githubusercontent.com/6755973/231706190-0c544c53-51a4-473d-ae42-7f78df4bd28a.gif)

@PureWeen I've seen some changes in some recent related PRs, could we go through this together?

**Comment by PureWeen** [comment] 2023-04-16 22:47
I tested this on main/net8 as well and I'm not seeing it reproduced.

Fairly sure this was fixed by the changes made on this [PR](https://github.com/dotnet/maui/pull/12888).

I've marked that PR as backport suggested so we can review the risks to backporting.

**Closed by PureWeen** 2023-04-16 22:47 UTC
Labels: t/bug, platform/android 🤖, area/navigation 🧭, p/1, partner/cat 😻
