### ISSUE TITLE
.NET 8 MAUI.Blazor keyboard event doesn't work anymore

### ISSUE THREAD

**Issue by Xyncgas** [dotnet/maui#16730] opened 2023-08-14 01:20 UTC
### Description

After updating to newest Visual Studio 2022 preview, I created MAUI.Blazor project
I have one single component that has one single div I set contenteditable to true and binded ```@onkeydown``` to a function
The function isn't getting called when I press my keyboard after running the app, it was working fine in .NET 7

### Steps to Reproduce

Create a component with a single ```div```

<div contenteditable="true"  @onkeydown="YourFunction"/>

### Version with bug

8.0.0-preview.7.8842

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.92

### Affected platforms

Windows

**Comment by Xyncgas** [comment] 2023-08-14 01:32
also in browser
![image](https://github.com/dotnet/maui/assets/35312807/7bd15cf0-7dad-4846-9f7e-dd5782cfe3a4)

**Comment by drasticactions** [comment] 2023-08-14 01:39
Duplicate of https://github.com/dotnet/maui/issues/16609

There is a workaround: https://github.com/dotnet/maui/issues/16609#issuecomment-1672166849

**Closed by drasticactions** 2023-08-14 01:39 UTC
Labels: t/bug

**Comment by samhouts** [comment] 2023-09-19 00:46
Duplicate of #16609
