### ISSUE TITLE
Mac Catalyst CMD+Q doesn't close application

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/maui#5026] opened 2022-03-02 22:45 UTC
Expected CMD+Q to quit application

https://user-images.githubusercontent.com/14852843/156462507-b4d5cbcf-d43c-4a71-86dd-ac7a58a453d3.mov

.

**Comment by jfversluis** [comment] 2022-03-03 10:03
I've tried to reproduce but I'm not able to with the current bits. Both pressing CMD + Q and going through the menu work for me on a File > New > .NET MAUI Blazor app. Would you happen to have a repro project somewhere?

**Comment by TanayParikh** [comment] 2022-03-03 17:54
> I've tried to reproduce but I'm not able to with the current bits. Both pressing CMD + Q and going through the menu work for me on a File > New > .NET MAUI Blazor app. Would you happen to have a repro project somewhere?

Should be a pretty vanilla app:

https://github.com/TanayParikh/maui-blazor-issue-5026

Running via: `dotnet build maui-blazor2.csproj -t:Run -f net6.0-maccatalyst`

Intel Mac on Monterey 12.2.1 (21D62).

**Comment by jfversluis** [comment] 2022-03-03 19:36
Downloaded your exact code, ran it and closed it successfully :)

https://user-images.githubusercontent.com/939291/156639671-0de5b709-04fa-49cc-a210-52978ea33d9c.mov

**Comment by TanayParikh** [comment] 2022-03-03 19:41
Just out of curiosity, what dotnet & mac catalyst workload are you on? I'm on main from early this week (I wonder if I may be seeing a recent regression).

dotnet --version: 6.0.201
Mac Catalyst Workload (from WorkloadManifest.json): 15.2.302-preview.14.56

**Comment by jfversluis** [comment] 2022-03-04 09:03
Ah should've included that, sorry. I'm on preview 13 15.2.301-preview.13.7

**Comment by Redth** [comment] 2022-03-08 16:14
I've seen this as well... I suspect it could be related to the menu code recently introduced... @PureWeen any thoughts?

**Comment by Redth** [comment] 2022-03-11 03:49
I think I found the culprit....

In this override: https://github.com/dotnet/maui/blob/main/src/Core/src/Platform/iOS/MauiUIApplicationDelegate.Menu.cs#L32

We are being too generous and always returning true.  There are other selectors that get passed into this method, one of which is `terminate:`.  

If we use this instead:

```
public override bool CanPerform(Selector action, NSObject? withSender)
{
	if (action.Name == "terminate:")
		return base.CanPerform(action, withSender);
		
	return true;
}
```

The application exits fine.

Probably we need to collect the names of selectors we know we can respond to based on how we built the menu, and then only return true for the ones we're sure of, and call into the base for the rest, since we don't know what else we are returning true for that we should not be.

/cc @PureWeen

**Closed** 2022-03-17 02:03 UTC
Labels: t/bug, area/desktop 🖥️, s/triaged, s/needs-attention
