### ISSUE TITLE
Shell navigation bar flickering during refresh (animation transition) after the menu/flyout item selection

### ISSUE THREAD

**Issue by ivanzakharov** [dotnet/maui#20035] opened 2024-01-21 09:41 UTC
### Description

Out-of-the-box code sample with Shell navigation has a silly issue - when the flyout/menu item has been selected to jump to another content page, the navigation bar refreshes (or does the animation transition) completely with flickering and shows the white background for a fraction of a second. 
It blocks us from using Shell for our Office-class business app.

### Steps to Reproduce

1) Take _ShellFlyoutSample_ from [.NET MAUI Samples](https://github.com/dotnet/maui-samples/tree/main/8.0/Navigation/ShellFlyoutSample)
2) Build it and run it on an Android emulator (Pixel 5, Android 13, API 33)
3) Switch between flyout items to see the flickering issue

### Link to public reproduction project repository

https://github.com/dotnet/maui-samples

### Version with bug

8.0.6

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 13

### Did you find any workaround?

No, tried to fix it by adding _Shell.PresentationMode="NotAnimated"_ (into _AppShell.xaml_, _MainPage.xaml_), but it didn't help

Recorded video with the animation transition issue:
https://github.com/dotnet/maui/assets/4208052/ea145382-e254-4143-b74e-bf6a726de7cd

**Comment by ivanzakharov** [comment] 2024-01-21 10:00
Added another video that shows the issue with a white background underlying.
https://github.com/dotnet/maui/assets/4208052/cd9ddf35-ff69-4562-b2ee-42d6f2c466e5

BTW, the same white background appears in the dark theme.

**Comment by PureWeen** [comment] 2024-01-22 16:05
Duplicate of #6389

Yea, unfortunately when Shell was originally implemented the second page gets pushed as a completely new coordinator layout with its own toolbar so you get a flash as the entire screen is swapped out (toolbar and everything). NavigationPage used to also do this in XF, but with MAUI we simplified it all down so there's now just a universal ToolBar for the entire app and you don't get any flickering. Ideally we can get shell pivoted to all the same backend code as NavigationPage which will fix this issue and make all our lives simpler.

**Closed by PureWeen** 2024-01-22 16:05 UTC
Labels: t/bug, platform/android 🤖, area/shell 🐢
