### ISSUE TITLE
:NET MAUI displays a list wrong on IOS, when the app was shortly in the background

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#13916] opened 2023-03-14 16:28 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/:NET-MAUI-displays-a-list-wrong-on-IOS-/10297894)._

---
Hi, in the attached file, you can find a detailed description about the error and a sample app, to debug it.

1. The app displays a list of images. It works well. If the app is in background and then back, it displays the list wrong (tested on iOS 16.2 and in the emulator).

2.	The Shell.TitleView is not displayed on iOS.

3.	The margins in the Shell-Menu are ignored

[dotnet_maui_errors.zip](https://aka.ms/dc/file?name=Bd9166cd77a9d4808bd3301c6cc0a55d9638133838658288827_dotnet_maui_errors.zip&tid=d9166cd77a9d4808bd3301c6cc0a55d9638133838658288827)

---
#### Feedback Bot on 3/2/2023, 05:02 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by Grzesik** [comment] 2023-04-15 10:15
Hi, I'd like to ask if there is any progress with this issue. Because of this and the issue https://github.com/dotnet/maui/issues/14139 I can't update/release my App in the store.

**Comment by marcoseraphin** [comment] 2023-04-18 05:39
Hi all,

yes I am also experience the same behavior in my project, so please fix the problem.

**Comment by Grzesik** [comment] 2023-07-19 20:19
[dotnet_maui_errors_1.zip](https://github.com/dotnet/maui/files/12099800/dotnet_maui_errors_1.zip)
I uploaded the project once again

**Comment by davidortinau** [comment] 2023-07-19 22:53
I can repro on .NET 7, but it doesn't repro in .NET 8 Preview 6. Looks like it's fixed.

**Comment by Grzesik** [comment] 2023-07-20 05:24
I switch to .Net 8 Preview, to go forward with my app.

Thanks

Marian Grzesik
Geschäftsführer

_________________________________


Software2Business GmbH
Walther-Rathenau-Strasse 18B
D-53842 Troisdorf
Tel          +49 (2241) 395359
Mobil    +49(177)  8408685
E-Mail    ***@***.******@***.***>
***@***.******@***.******@***.******@***.***>Web       www.software2business.de/<http://www.software2business.de/>

Von: David Ortinau ***@***.***>
Gesendet: Donnerstag, 20. Juli 2023 00:54
An: dotnet/maui ***@***.***>
Cc: Marian Grzesik ***@***.***>; Manual ***@***.***>
Betreff: Re: [dotnet/maui] :NET MAUI displays a list wrong on IOS, when the app was shortly in the background (Issue #13916)


I can repro on .NET 7, but it doesn't repro in .NET 8 Preview 6. Looks like it's fixed.

**Comment by Grzesik** [comment] 2023-07-23 18:53
Hi David, I tested it on my Mac, and the app works on .Net 8 preview 6 better. The Shell has only the problem, that the custom TitleView is wrong displayed and ignores the Margins like the Menu title too. Also when I switch to all views and then back to the home view, the app crashes.

**Comment by jinxinjuan** [comment] 2023-07-24 06:21
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 3.0(net8.0). Can repro on iOS platform with sample project. [dotnet_maui_errors.zip](https://aka.ms/dc/file?name=Bd9166cd77a9d4808bd3301c6cc0a55d9638133838658288827_dotnet_maui_errors.zip&tid=d9166cd77a9d4808bd3301c6cc0a55d9638133838658288827)

Note: The seem behavior: "The Shell has only the problem, that the custom TitleView is wrong displayed and ignores the Margins like the Menu title too. Also when I switch to all views and then back to the home view, the app crashes."

**Comment by samhouts** [comment] 2023-09-13 19:20
It looks like the remaining issue here is the same as #16015, so I will close this one for clarity. Thanks!

**Comment by samhouts** [comment] 2023-09-13 19:20
Duplicate of #16015

**Closed by samhouts** 2023-09-13 19:20 UTC
Labels: t/bug, platform/iOS 🍎, area/shell 🐢, area/controls 🎮, s/verified, control-image, s/triaged
