### ISSUE TITLE
Set Focus to a DatePicker scroll the view to bottom on iOS

### ISSUE THREAD

**Issue by acaliaro** [dotnet/maui#20494] opened 2024-02-10 14:46 UTC
### Description

I have a ContentPage with a DatePicker with isVisible=false. If I set datepicker.Focus() on codebehind, the datepicker appears but the view scroll to bottom. Same situation but with Opacity="0" instead of isvisible=false, the datepicker appears and the view does not scroll

### Steps to Reproduce

Execute the sample. There are two button with different behaviours

### Link to public reproduction project repository

https://github.com/acaliaro/MauiAppPopupAndDatePickerProblem

### Version with bug

8.0.6

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 17 Iphone 13

### Did you find any workaround?

set datepicker opacity=0 instead of isvisible=false

**Comment by PureWeen** [comment] 2024-02-12 15:40
Duplicate of #20380

**Closed by PureWeen** 2024-02-12 15:40 UTC
Labels: t/bug, platform/iOS 🍎, area/controls 🎮, control-datetimepicker
