### ISSUE TITLE
Items in CollectionView using GridItemsLayout not sized correctly (content gets clipped)  

### ISSUE THREAD

**Issue by s-beltz** [dotnet/maui#16115] opened 2023-07-12 15:04 UTC
### Description

Items inside a GridItemsLayout with Span=1 will grow when the containing window is resized. 
But they won't shrink when window gets smaller. Thus the items in the CollectionView are clipped.

Remarks: 

- In our full app we will change GridItemsLayout.Span according to the available space for our CollectionView. 
- When GridItemsLayout.Span is at least set to 2 items will not be clipped.

Initial layout:

![image](https://github.com/dotnet/maui/assets/57802605/1fe199e6-297e-4903-aebc-a04772df40ae)

Resized window (wider):
![image](https://github.com/dotnet/maui/assets/57802605/bae150a7-f4b3-45df-b83b-d3be16a6f8ab)

Resized window (smaller -> clipped items):

![image](https://github.com/dotnet/maui/assets/57802605/3d0bf352-d654-4f9e-b711-eaacc633875c)

### Steps to Reproduce

Please clone the attached repro repository and start the application: [https://github.com/s-beltz/CollectionViewRepro](url)

Basically this is the XAML producing the error:

```
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MauiCollectionViewApp.MainPage"
             x:Name="thisPage">
    <ContentPage.Resources>
        <!-- Changing Span to anything greater than 1 will work -->
        <GridItemsLayout x:Key="TilesLayout"
                         Span="1"
                         Orientation="Vertical"
                         HorizontalItemSpacing="10"
                         VerticalItemSpacing="10" />
        <DataTemplate x:Key="TileTemplate">
            <Grid Margin="20"
                  BackgroundColor="Gainsboro"
                  VerticalOptions="Fill"
                  HeightRequest="100">
                <Label HorizontalOptions="Center"
                       VerticalOptions="Center"
                       Text="{Binding Mode=OneWay}" 
                       FontSize="Large"/>
            </Grid>
        </DataTemplate>
    </ContentPage.Resources>
    <Grid>
        <CollectionView BackgroundColor="LightBlue"
                        HorizontalOptions="Fill"
                        VerticalOptions="Fill"
                        ItemsSource="{Binding Path=Tiles, Mode=OneWay, Source={x:Reference thisPage}, TargetNullValue={x:Null}, FallbackValue={x:Null}}"
                        ItemTemplate="{StaticResource TileTemplate}"
                        ItemsLayout="{StaticResource TilesLayout}"
                        ItemSizingStrategy="MeasureAllItems"
                        SelectionMode="Single" />
    </Grid>
</ContentPage>
```

### Link to public reproduction project repository

https://github.com/s-beltz/CollectionViewRepro

### Version with bug

7.0.92/7.0.100

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Windows 11

### Did you find any workaround?

Unfortunately not. 
In our full app we already handle SizeChanged-events and will change the Span-property according to the available space. 
Trying to manipulate the CollectionView or GridItemsLayout instance did not help.
But we are willing to implement any known workaround available... ;-)

**Comment by damidhagor** [comment] 2023-07-29 13:51
I'm having the exact same issue where the CollectionView item container will only grow when resizing the window but will clip the content when resizing to a smaller window width.
The issue exists also for the LinearItemsLayout no matter the orientation.
But I can confirm that setting the Span property of the GridItemsLayout the container will resize correctly.

Tested this on Windows with version 8.0.0-preview.6.8686.

**Comment by XamlTest** [comment] 2023-08-04 08:28
Verified this on Visual Studio Enterprise 17.7.0 Preview 6.0. Repro on Windows 11(8.0.100-preview.6.23330.14) with below Project:
[MauiCollectionViewApp.zip](https://github.com/dotnet/maui/files/12258774/MauiCollectionViewApp.zip)

**Comment by samhouts** [comment] 2023-08-11 16:47
Duplicate of #15519

**Closed by samhouts** 2023-08-11 16:47 UTC
Labels: t/bug, platform/windows 🪟, area/layout 🔲, area/collectionview 📃, s/verified, s/triaged
