### ISSUE TITLE
The type or namespace name 'MauiUIApplicationDelegate' could not be found Microsoft.AspNetCore.Components.WebView.Maui 8.0.7

### ISSUE THREAD

**Issue by garcia252** [dotnet/maui#20591] opened 2024-02-14 16:48 UTC
### Description

We just upgraded Microsoft.AspNetCore.Components.WebView.Maui and Microsoft.Maui.Controls to 8.0.7. When compiling it gives us the error:

`/Platforms/iOS/AppDelegate.cs(6,32): error CS0246: The type or namespace name 'MauiUIApplicationDelegate' could not be found (are you missing a using directive or an assembly reference?)`

No other code changes were made whatsoever. Recently we used 8.0.6 and it compiled fine.

### Steps to Reproduce

Upgrade Microsoft.AspNetCore.Components.WebView.Maui and Microsoft.Maui.Controls to 8.0.7

### Version with bug

8.0.7 SR2

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.6 SR1

### Affected platforms

iOS

**Comment by bengavin** [comment] 2024-02-14 18:26
I think this is tied in with #20565 , this is the actual error I'm getting on my Azure DevOps build agents, with the behavior described in the other issue when installing workloads.  Local builds are all working fine after force-cleaning and restore/rebuild after updating to the latest nuget packages.

**Comment by garcia252** [comment] 2024-02-14 21:24
@PureWeen this is in Azure DevOps Pipeline. We are using SDK Task to use .NET 8.x, we also check "Include Preview Versions"

@bengavin the workloads we are installing are "install ios maccatalyst tvos macos maui wasm-tools". This has worked great before.

**Comment by Redth** [comment] 2024-02-14 21:31
Please see #20600

**Comment by jfversluis** [comment] 2024-02-16 09:51
Duplicate of https://github.com/dotnet/maui/issues/20600 and a fix is available for the hosted build agents without the need for any other changes.

**Closed by jfversluis** 2024-02-16 09:51 UTC
Labels: t/bug, platform/iOS 🍎, s/needs-attention, potential-regression
