### ISSUE TITLE
Entry with IsPassword="True" does not work correctly

### ISSUE THREAD

**Issue by Fabiano-Rezende** [dotnet/maui#7334] opened 2022-05-19 14:24 UTC
### Description

When Entry.IsPassword="True" each typed char moves the cursor to position 0 (zero), so the Entry.Text value is reversed

### Steps to Reproduce

1. Create a new Net Maui App
2. Modify the MainPage.xaml to look like:
3.<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MauiApp2.MainPage">
			 
    <ScrollView>
        <VerticalStackLayout 
            Spacing="25" 
            Padding="30,0" 
            VerticalOptions="Center">

            <Entry IsPassword="True" Placeholder="Enter password" x:Name="passEntry"/>
            <Label Text="{Binding Source={x:Reference passEntry}, Path=Text}"/>
            <Button 
                x:Name="CounterBtn"
                Text="Click me"
                SemanticProperties.Hint="Counts the number of times you click"
                Clicked="OnCounterClicked"
                HorizontalOptions="Center" />

        </VerticalStackLayout>
    </ScrollView>
 
4: Type the password
5: Label will show the text reversed

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows

**Comment by NonameMissingNo** [comment] 2022-05-19 14:28
Reproducible on RC3 VS 17.3.0 Preview 1.0

**Comment by Michal-MK** [comment] 2022-05-19 15:55
Duplicate of #5401

**Closed** 2022-05-19 22:07 UTC
Labels: t/bug, area/controls 🎮, s/needs-verification
