### ISSUE TITLE
CollectionView does not display data on Windows

### ISSUE THREAD

**Issue by HobDev** [dotnet/maui#17682] opened 2023-09-27 05:12 UTC
### Description

I want to display data on CollectionView. The CollectionView is bound to an observableCollection. But only the layout is visible for each item without any data. 

### Steps to Reproduce

Run the repro project and see the empty items in collectionview.

### Link to public reproduction project repository

https://github.com/HobDev/DotNet8MauiBugs/tree/CollectionViewDataIssue

### Version with bug

8.0.0-rc.1.9171

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.92

### Affected platforms

Windows

### Affected platform versions

Windows SDK 10.0.19041.0

### Did you find any workaround?

No

**Comment by jfversluis** [comment] 2023-09-27 07:21
Pretty sure this is a duplicate of #17515 please check the nightly feed to see if it's resolved there, if not please let us know

**Comment by jfversluis** [comment] 2023-09-27 07:21
Duplicate of #17515

**Closed by jfversluis** 2023-09-27 07:21 UTC
Labels: t/bug

**Comment by HobDev** [comment] 2023-10-03 04:35
@jfversluis I added https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet8/nuget/v3/index.json in the Package Sources and Package Source Mapping of the Visual Studio 17.8.0 Preview 2.0. What should I do next to work with the nightly builds.
