### ISSUE TITLE
[Spec]  Implement Device class functionality to Core

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#1305] opened 2021-06-14 15:52 UTC
# [The feature] 

The Device class contains a number of properties and methods to help developers customize layout and functionality on a per-platform basis.

- **Flags** - Used to use experimental APIs in Xamarin.Forms. Obsolete.
- **SetFlags** - Remove.
- **FlowDirection** -Move to Window.
- **SetFlowDirection** - Remove.
- **Idiom** - Move to MauiContext and make it use essentials.
- **Info** - Obsolete.
- **SetIdiom** - Remove.
- **SetTargetIdiom** - Remove.
- **IsInvokeRequired** - obsolete (hidden)
- **PlatformInvalidator** - Try to remove.
- **Invalidate** - Try to remove.
- **RuntimePlatform** - Make it use essentials and move these to Window, use Application.Windows.First() to back these.
- **BeginInvokeOnMainThread**(Action)
- **GetNamedColor**(string) - Move to .NET MAUI Graphics.
- **GetNamedSize** (multiple overloads) - TODO find the 'current' way to do this.
- **StartTimer** - Move to Application or Window? Maybe this goes away and is handled by animation stuffPlatformServices
- **RequestedTheme** - Move to Window, use Essentials implementation.
- **RuntimePlatform** - Remove.
- **GetHash** - Remove.
- **GetMD5Hash** - Remove.
- **GetNamedColor** - Remove.
- **GetNamedSize** - Remove.
- **GetNativeSize** - Gets renderer or handler and calls GetDesiredSize - remove.
- **GetStreamAsync** - Remove.
- **GetUserStoreForApplication** - Remove.
- **OpenUriAction** - Obsolete, use essentials.
- **QuitApplication** - Move to Application.
- **StartTimer** - Move to window? Maybe this goes away and is handled by animation stuff
- **Dispatcher** - find window of mainpage and use that dispatcher.
- **MainPage** / CreateWindowMake CreateWindow return MainPage, if no mainpage is set throwSet MainPage, go through windows to find window with current mainpage, and replace mainpage.

# Difficulty : [medium]

**Comment by mattleibow** [comment] 2021-09-21 21:42
Duplicate of https://github.com/dotnet/maui/issues/1965

**Closed by mattleibow** 2021-09-21 21:42 UTC
