### ISSUE TITLE
Gradient not appearing on iOS

### ISSUE THREAD

**Issue by Javierflo95** [dotnet/maui#8402] opened 2022-06-29 04:33 UTC
### Description

I implemented my own design on XAML using Android, with normal background and LinearGradientBrush, and when I tested on iOS I get this visual inconsistency 
![image](https://user-images.githubusercontent.com/11860518/176352253-014ad224-24fe-44bc-9fd8-4ae69c5829cf.png)

### Steps to Reproduce

1. Create NET MAUI App 
2. Replace MainPage to this XAML 
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:ios="clr-namespace:Microsoft.Maui.Controls.PlatformConfiguration.iOSSpecific;assembly=Microsoft.Maui.Controls"
             ios:Page.UseSafeArea="True"
             Shell.NavBarIsVisible="False"
             x:Class="GenerationApp.MainPage">

    <Grid RowDefinitions="Auto,3*,*,*">
        <Grid Margin="{OnPlatform Android='-20,-20,0,0', iOS='-40,-20,0,0'}">
            <Image Source="deporte" HeightRequest="{OnPlatform Android='600', iOS='600'}"/>
        </Grid>
        <Grid Grid.Row="1" HorizontalOptions="FillAndExpand" BackgroundColor="Transparent"
              Margin="{OnPlatform Android='0,-180,0,-100', iOS='0,-80,0,-1'}">
            <Frame BorderColor="transparent">
                <Frame.Background>
                    <LinearGradientBrush StartPoint="1,0" EndPoint="1,1">
                        <GradientStop Offset=".5" Color="Transparent"/>
                        <GradientStop Offset=".1" Color="{StaticResource GenOrange}"/>
                        <GradientStop Offset=".1" Color="{StaticResource GenOrange}"/>
                        <GradientStop Offset=".1" Color="{StaticResource GenOrange}"/>
                        <GradientStop Offset=".1" Color="{StaticResource GenOrange}"/>
                        <GradientStop Offset=".1" Color="{StaticResource GenOrange}"/>
                    </LinearGradientBrush>
                </Frame.Background>
            </Frame>
            <Grid HeightRequest="210" WidthRequest="210" HorizontalOptions="Center">
                <Image x:Name="logo_gen" Source="logo_generations_bluedark" HeightRequest="200"  
                       WidthRequest="200" HorizontalOptions="Center" VerticalOptions="Center"
                       Margin="0,-180,0,0"/>
            </Grid>
        </Grid>
        <StackLayout Grid.Row="3" Margin="0,-200,0,10" VerticalOptions="CenterAndExpand"
                     HorizontalOptions="FillAndExpand" Spacing="10">
            <Label Text="Lorem Ipsum dolor" TextColor="White" HorizontalOptions="CenterAndExpand" />
            <Label Text="consectetuer adlplsicing ellit." TextColor="White" HorizontalOptions="CenterAndExpand" />
            <Border StrokeThickness="2" StrokeShape="Rectangle" Margin="30,0,30,0" BackgroundColor="{StaticResource GenDark}" >
                <Button Text="SIGN UP NOW" TextColor="White" BorderWidth="0" HorizontalOptions="FillAndExpand" 
                        BackgroundColor="Transparent" BorderColor="Transparent" Command="{Binding GoToRegisterPage}"/>
            </Border>
        </StackLayout>
        <StackLayout Grid.Row="4" VerticalOptions="FillAndExpand">
            <FlexLayout Direction="Column">
                <BoxView HorizontalOptions="FillAndExpand" HeightRequest=".1" Color="White"/>
            </FlexLayout>
            <Button Text="LOGIN" TextColor="White" BackgroundColor="Transparent" BorderColor="Transparent" 
                    BorderWidth="0" Command="{Binding GoToLoginPage}"/>
        </StackLayout>
    </Grid>
</ContentPage>
3. Run App

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

Android  12, iOS 15

**Comment by Ahmadmansoor** [comment] 2022-06-29 05:20
This is normal, I think u have to make a check for the system ( Andriod or iOS) depending on this u have to design a separate theme for each system and then load this Theme according to that system.
this is the fast idea I try to fix this issue.

**Comment by NonameMissingNo** [comment] 2022-06-29 06:20
@Ahmadmansoor The problem here is that the gradient isn't shown on iOS

**Comment by NonameMissingNo** [comment] 2022-06-29 06:26
@Javierflo95 There is a problem with GradientBrushes on iOS and MacOS

**Comment by NonameMissingNo** [comment] 2022-06-29 06:34
Yes, but the purpose of Maui would be to make those annoying quirks of iOS disappear, and have 1 unified system where everything looks how it should

**Comment by Ahmadmansoor** [comment] 2022-06-29 06:36
Sorry but as always nothing perfect , this is the life 😉

**Comment by NonameMissingNo** [comment] 2022-06-29 06:40
Huh, if I put the app in the background, and then come back, the gradient appears... (main branch)
![image](https://user-images.githubusercontent.com/40233496/176368669-a823f0e5-56be-44cc-ac73-69f641f15e8f.png)

**Comment by Javierflo95** [comment] 2022-06-29 12:06
@NonameMissingNo , whatbdo you mean, with if you put the appcin background...

**Comment by NonameMissingNo** [comment] 2022-06-30 08:13
@rachelkang Are you sure that the iOS issue requires an android tag?

**Comment by jsuarezruiz** [comment] 2022-06-30 10:35
The problem is the Frame not rendering the gradient on iOS. The issue should be fixed by https://github.com/dotnet/maui/pull/7925

**Comment by Javierflo95** [comment] 2022-06-30 11:41
> The problem is the Frame not rendering the gradient on iOS. The issue should be fixed by https://github.com/dotnet/maui/pull/7925

Thanks @jsuarezruiz

**Comment by Javierflo95** [comment] 2022-07-16 00:15
@jsuarezruiz 

another difference that I see is with the textbox (editors) see bellow 
![image](https://user-images.githubusercontent.com/11860518/179326413-32fe8ae5-90bd-479d-8bce-ab0978459a62.png)


And when I use my app and go to login page, and then click on LOG IN in Android work well in API 31 but when I click on thiis iOS or Android API 28 the button doesn't work well :( 


Any suggestions?

**Comment by jsuarezruiz** [comment] 2022-08-31 11:53
> he button doesn't work well

Could you describe with more details the problem?, cannot click the button?

**Comment by hermben** [comment] 2022-09-19 20:25
As a workaround, you can replace Frame with ContentView to see if it also works for you:
Example code:

```
<ContentView
                HeightRequest="120"
                HorizontalOptions="FillAndExpand"
                Margin="-2"
                Padding="20, 45, 20, 0">
            <ContentView.Background>
                <LinearGradientBrush>
                    <GradientStop Color="#00A7B5" Offset="0.1" />
                    <GradientStop Color="#721474" Offset="1.0" />
                </LinearGradientBrush>
            </ContentView.Background>
</ContentView>
```

If you need border, border radius and shadow, you can combine **ContentView** with **Border** and **Shadow** MAUI elements.

**Comment by Javierflo95** [comment] 2022-09-20 16:49
> button

The Button appear well, but when you click on it, the button on iOS it does not anything

**Closed** 2022-11-23 17:48 UTC
Labels: t/bug, area/drawing ✏️, platform/iOS 🍎
