### ISSUE TITLE
MAUI Blazor Win App Crashes when installed

### ISSUE THREAD

**Issue by travis-pettry1** [dotnet/maui#5417] opened 2022-03-18 11:59 UTC
### Description

Hi All,

I have been working on a MAUI Blazor app. I have recently tried deploying the app (via giving the file out for testing, aka the sneaker-net) to another computer in the office. Every time I launch the app on the target computer the app crashes silently. The target computer has .net 6 installed and I have signed the .msix with a self signed key (I cannot get my EV Code signing keys to work, but that's a different issue). I have installed the cert on the target machine (this was needed to be able to install the .msix). When I look into event viewer I see the following errors:

Faulting application name: AppName.exe, version: 1.0.0.0, time stamp: 0x61e1d8d9
Faulting module name: KERNELBASE.dll, version: 10.0.19041.1503, time stamp: 0xb2acaea9
Exception code: 0xc000027b
Fault offset: 0x000000000010b382
Faulting process id: 0x2994
Faulting application start time: 0x01d82a7597434545
Faulting application path: C:\Program Files\WindowsApps\CB8D8769-86C0-4D70-BE7B-35E690EEF8D8_1.0.0.0_neutral__sk4q8x27dz5nr\appName.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: dacbe7fe-12c9-455d-b4b9-f55bb6128b93
Faulting package full name: CB8D8769-86C0-4D70-BE7B-35E690EEF8D8_1.0.0.0_neutral__sk4q8x27dz5nr
Faulting package-relative application ID: App 

Fault bucket 1306902137409986628, type 5
Event Name: MoAppCrash
Response: Not available
Cab Id: 0

Problem signature:
P1: CB8D8769-86C0-4D70-BE7B-35E690EEF8D8_1.0.0.0_neutral__sk4q8x27dz5nr
P2: praid:App
P3: 1.0.0.0
P4: 61e1d8d9
P5: combase.dll
P6: 10.0.19041.1348
P7: baf10630
P8: 80070003
P9: 00000000000862a6
P10:

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER1346.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER154A.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER156A.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER1568.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER1598.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_CB8D8769-86C0-4D_da3fd7fc7a36e25ba7db4c744dedc5abf46ba23_daf7a6cd_334b3e7d-e843-4629-aacc-f5bb81d4c600

Analysis symbol:
Rechecking for solution: 0
Report Id: dacbe7fe-12c9-455d-b4b9-f55bb6128b93
Report Status: 268435456
Hashed bucket: b20af24c851c0b1b92230c91d8856044
Cab Guid: 0

If I install the .msix on any dev machine everything works correctly. 

Thank you,
Travis Pettry

### Steps to Reproduce

1. Create a new .net Maui Blazor app
2. Create package via the command line
2a. change directories to the Maui Blazor app dir
2b. "C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\msbuild" /restore /t:Publish /p:TargetFramework=net6.0-windows10.0.19041 /p:configuration=debug /p:GenerateAppxPackageOnBuild=true /p:AppxPackageSigningEnabled=true /p:PackageCertificateThumbprint="thumbprint" /p:PackageCertificatePassword="password"
3. Copy the resulting .msix to a non dev machine
4. Install the cert if not a EV signing cert
5. Install the .msix
6. launch the app

### Version with bug

Preview 13

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10

### Did you find any workaround?

Not yet

**Comment by jfversluis** [comment] 2022-03-18 14:36
Duplicate of #5024

**Closed by jfversluis** 2022-03-18 14:36 UTC
Labels: t/bug, area/blazor 🕸️, s/needs-verification
