### ISSUE TITLE
[Feature Request] Word/Pdf document print dialog

### ISSUE THREAD

**Issue by HimanshuBansal112** [dotnet/maui#13569] opened 2023-02-26 15:52 UTC
### Description

I would like to have an option for word or pdf document print dialog in which user chooses what properties they want for word document to print. In that, we will also define default settings for print which user can change. This feature is already available in windows forms but I tried to use it in net maui and it did not found library since both are different.

### Public API Changes

It will be defined like
```PrintDialog printDialog = new PrintDialog();``` similar to windos forms application. with some changes to name of function.

For dialog, it might be similar to:
```
if (printDialog.ShowDialog() == DialogResult.OK)
			{
				Microsoft.Office.Interop.Word.Document doc = wordApp.Documents.Add(@"c:\temp.docx");
				wordApp.ActivePrinter = printDialog.PrinterSettings.PrinterName;
				wordApp.ActiveDocument.PrintOut(); //this will also work: doc.PrintOut();
				doc.Close(SaveChanges: false);
				doc = null;
			}
```
Though it need to be changed for "dialogresult.OK"

### Intended Use-Case

I was making an app, which I needed to print a bill. So I choose word document to be the file, but I was not able to find any option to print it with dialog so that I do not have to change settings every time.

**Comment by jfversluis** [comment] 2023-02-27 10:34
Duplicate of #4795

**Closed by jfversluis** 2023-02-27 10:34 UTC
Labels: proposal/open
