### ISSUE TITLE
Visual Studio 17.7.0 Pre2 / Dotnet 8 8.0.100-preview.5.23303.2 / Maui 8.0.0-preview.5.8529 AvoidConstArraysAnalyzer NullReferenceException

### ISSUE THREAD

**Issue by rogerbriggen-securiton** [dotnet/maui#15948] opened 2023-06-30 16:22 UTC
### Description

"C:\Program Files\dotnet\dotnet.exe" build C:\BuildAgent\work\ef497e914ee5fdcb\MyProject.sln --configuration Release

creates the warning 
CSC : warning AD0001: Analyzer 'Microsoft.NetCore.Analyzers.Runtime.AvoidConstArraysAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'. [C:\BuildAgent\work\ef497e914ee5fdcb\MyProject.Communication\MyProject.Communication.csproj::TargetFramework=net8.0-android]
17:26:08     [WRN] CSC : warning AD0001: Analyzer 'Microsoft.NetCore.Analyzers.Runtime.AvoidConstArraysAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'. [C:\BuildAgent\work\ef497e914ee5fdcb\MyProject.Communication\MyProject.Communication.csproj::TargetFramework=net8.0-android]

### Steps to Reproduce

- Install latest dotnet 8 preview with MAUI
- Create a maui project
- Enable ipa and apk during build
- build release mode

### Link to public reproduction project repository

-

### Version with bug

Unknown/Other

### Last version that worked well

7.0.49

### Affected platforms

Windows

### Affected platform versions

-

### Did you find any workaround?

No

### Relevant log output

```shell
CSC : warning AD0001: Analyzer 'Microsoft.NetCore.Analyzers.Runtime.AvoidConstArraysAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'. [C:\BuildAgent\work\ef497e914ee5fdcb\MyProject.Communication\MyProject.Communication.csproj::TargetFramework=net8.0-android]
17:26:08     [WRN] CSC : warning AD0001: Analyzer 'Microsoft.NetCore.Analyzers.Runtime.AvoidConstArraysAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'. [C:\BuildAgent\work\ef497e914ee5fdcb\MyProject.Communication\MyProject.Communication.csproj::TargetFramework=net8.0-android]
```

**Comment by bgrainger** [comment] 2023-07-02 19:03
Possibly a duplicate of https://github.com/dotnet/roslyn-analyzers/issues/6686.

**Comment by Eilon** [comment] 2023-08-03 16:40
Indeed, this seems to exactly correlate with https://github.com/dotnet/roslyn-analyzers/issues/6686. If this still happens after updating to the latest packages, please log a new issue at https://github.com/dotnet/roslyn-analyzers/issues/.

**Closed by Eilon** 2023-08-03 16:40 UTC
Labels: t/bug, s/needs-attention
