### ISSUE TITLE
Cascading memory leak when StrokeShape is set via a global style on Border control

### ISSUE THREAD

**Issue by AdamEssenmacher** [dotnet/maui#20163] opened 2024-01-25 21:02 UTC
### Description

Setting the `StrokeShape` property on a Border control via a global style results in the control and its containing page to leak.

Page-level leaks are serious, as they prevent child elements from being collected as well.

It's also noteworthy that the OOTB MAUI template creates a global Border style with the StrokeShape set, so all MAUI apps created with the standard solution template will have this page-level cascading leak unless the global style is removed or StrokeShape is explicitly set.

I recommend the area/perf label for the issue.

Also, I'm _guessing_ this applies to iOS as well as Android. However, iOS currently leaks no matter how the StrokeShape property is set, so it can't be properly tested.

### Steps to Reproduce

1. Create MAUI app using standard template
2. Push/pop page containing a Border control
3. Force GC
4. Observe leak
5. Push/pop page containing a Border control with StrokeShape property explicitly set
6. Force GC
7. Observe no leak

### Link to public reproduction project repository

https://github.com/AdamEssenmacher/BorderStyleLeak.Maui

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

**Comment by albyrock87** [comment] 2024-01-26 16:42
This is probably a kind-of duplicate of this: #18925

**Comment by Larhei** [comment] 2024-03-22 15:01
Seeing the same issue on 8.0.14. Any timeline for a fix?

@AdamEssenmacher 
Thanks for MemoryToolkit ;-) Helped a lot to identify issues

**Comment by AdamEssenmacher** [comment] 2024-04-09 15:27
Appears to be fixed in `8.0.40-nightly.10455`

**Comment by jonathanpeppers** [comment] 2024-04-09 17:04
Thanks! Fix was:
* https://github.com/dotnet/maui/pull/21151

**Closed by jonathanpeppers** 2024-04-09 17:04 UTC
Labels: t/bug, platform/android 🤖, platform/iOS 🍎, area/perf 🏎️, area/controls 🎮, control-border

**Comment by albyrock87** [comment] 2024-04-09 18:43
@jonathanpeppers please also look at my comment here:
https://github.com/dotnet/maui/issues/18925#issuecomment-1824058832

Number 1 is still an issue even if the leak has been fixed.
