### ISSUE TITLE
Error to include reference to MAUI Tookit

### ISSUE THREAD

**Issue by lperezj** [dotnet/maui#25937] opened 2024-11-19 07:10 UTC
### Description

I can´t build if add in XAML the reference to  xmlns:xct="http://schemas.microsoft.com/dotnet/2022/maui/toolkit" and include a Behavior

<Frame.Behaviors>
    <xct:TouchBehavior DefaultAnimationDuration="250"
                       DefaultAnimationEasing="{x:Static Easing.CubicInOut}"
                       PressedOpacity="0.6"
                       PressedScale="0.8" />
</Frame.Behaviors>

![Image](https://github.com/user-attachments/assets/cb4b964f-04cd-4b2d-b241-67faeda9be13)

### Steps to Reproduce

Hi, im trying to migrate from Xamarin.Forms to MAUI my current proyect and i have a problem to migrate the TouchEvents.

I did all the steps in https://learn.microsoft.com/en-us/dotnet/communitytoolkit/maui/
1. I add the NuGet package
2. I add the code line in CreateBuilder

```
.UseMauiApp<App>()
.UseMauiCommunityToolkit(options =>
{
    options.SetShouldSuppressExceptionsInConverters(false);
    options.SetShouldSuppressExceptionsInBehaviors(true);
    options.SetShouldSuppressExceptionsInAnimations(false);
}) 
```

3. I included the reference in XAML

```
<Frame xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
       xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
       xmlns:xct="http://schemas.microsoft.com/dotnet/2022/maui/toolkit"
```

4 And the TouchBehavior

```
<Frame.Behaviors>
    <xct:TouchBehavior DefaultAnimationDuration="250"
                       DefaultAnimationEasing="{x:Static Easing.CubicInOut}"
                       PressedOpacity="0.6"
                       PressedScale="0.8" />
</Frame.Behaviors>
```

But visual studio not display any exception, error or warning in code, but when i try to build the project/solution, throw the exception

### Version with bug

9.0.10 SR1

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Affected platforms

Android, Windows

### Relevant log output

```shell

```

**Comment by jfversluis** [comment] 2024-11-19 09:52
Duplicate of one of these: https://github.com/CommunityToolkit/Maui/issues?q=is%3Aissue%20state%3Aclosed%20XFC0000

This is a Toolkit issue, I think one of the issues in the above query should help you resolve it. If not, please open something on that repository.

**Closed by jfversluis** 2024-11-19 09:52 UTC
Labels: t/bug

**Comment by jfversluis** [comment] 2024-11-19 10:04
Additionally: https://github.com/dotnet/maui/issues/9781
