### ISSUE TITLE
[Bug] Recipes Search Results currently can't be opened via keyboard

### ISSUE THREAD

**Issue by PureWeen** [dotnet/maui#3145] opened 2021-10-27 15:21 UTC
## Description
Recipes in the search recipes list can't be opened via keyboard

## Steps to Reproduce
- click on any of the Meal Types on the initial page (For example Breakfast)
- hit the tab key until you've selected an item in the list of recipes
- hit the enter key

## Expected Behavior
The Item should navigate to the recipe info (click with your finger to see intended behavior)

## Actual Behavior
Nothing Happens

**Comment by rachelkang** [comment] 2023-02-28 21:37
Duplicate of #3144, but keeping both open for accessibility tracking purposes

Here to note this is also an issue on Windows.

**Comment by rachelkang** [comment] 2023-02-28 21:41
My thinking is that we should:
1. Make keyboard focus behavior for controls w/ TGR behave as it would for a button (just as we made items w/ TGR take controltype=button on Android so that it gets processed as a button for screen reader accessibility)
2. We should implement #1 and also the parenthetical point (pertaining to what we did in Android) in Windows and also iOS (if it hasn't been already)

**Comment by rachelkang** [comment] 2023-09-20 20:19
Fixed in https://github.com/rachelkang/recipeSearch/commit/19f9ba280b3106767fb81e5056acc2bdd6214052

**Closed by rachelkang** 2023-09-20 20:19 UTC
Labels: t/bug, platform/windows 🪟, platform/android 🤖, area/a11y, area/collectionview 📃, a11y/recipes-app, s/triaged, area/gestures
