### ISSUE TITLE
Random black screen in MAUI Blazor.

### ISSUE THREAD

**Issue by KieranDevvs** [dotnet/maui#19588] opened 2023-12-25 23:03 UTC
### Description

I'm having the exact same issue as filed here: https://github.com/dotnet/maui/issues/13291
As the issue is closed due to lack of response from the original poster, and the fact that I'm also experiencing this issue, I'm opening a new issue.

Note: this isn't a new issue, I've experienced this in previous versions of MAUI. I'm only now reporting this due to encountering it so often.

This may be an issue with WebView2 not initializing in MAUI correctly.
This also **appears** to only be an issue when debugging as I've not yet come across is when running the application without the debugger attached.

Screenshot (note how the debugging session has been active for 3+ minutes):
![image](https://github.com/dotnet/maui/assets/21192520/e1299b99-c7c1-49ea-87e5-92c05839a0a2)

### Steps to Reproduce

1) Create a new MAUI Blazor hybrid application.
2) Run the application.
3) Randomly encounter a black screen and the application never responds.

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10.0.19041.0

### Did you find any workaround?

Restart the application several times until the application successfully launches.

### Relevant log output

```shell
Nothing relevant.
```

**Comment by drasticactions** [comment] 2023-12-26 16:02
Going by the original issue you linked to, it seemed like it was a WinUI 3 issue and unrelated to MAUI UI stuff specifically. Specially as they said they also tried it without a web view and it also did the same thing.

Can you try making a WinUI 3 app that doesn't use MAUI and see if you can reproduce this?

**Comment by KieranDevvs** [comment] 2023-12-26 16:43
> Going by the original issue you linked to, it seemed like it was a WinUI 3 issue and unrelated to MAUI UI stuff specifically. Specially as they said they also tried it without a web view and it also did the same thing.
> 
> Can you try making a WinUI 3 app that doesn't use MAUI and see if you can reproduce this?

No unfortunately I cannot for two reasons:
1) I have no experience with WinUI 3 apps.
2) This issue is very sporadic and thus the only way that I have found to encounter it is to constantly work on a MAUI application. This would entail me creating a WinUI 3 application and working on it consistently until I encountered the issue (if at all). I don't have this kind of spare time to diagnose if this problem stems from WinUI 3 or MAUI. 

The fact of the matter is, people that are using MAUI are experiencing this issue and if MAUI happens to rely upon a dependency that is having issues, that's still an issue with MAUI because MAUI depends on that library to function properly. If you have suspicions that this is a WinUI 3 problem, then the MAUI team should raise this problem with the WinUI team rather than relying on your consumers to go on a wild goose chase.

**Comment by drasticactions** [comment] 2023-12-27 07:48
@KieranDevvs That's the issue here: is MAUI the dependency at fault. My suspicion is "no", based on the original issue. That user tried using a regular MAUI WebView in WinUI 3 (Which is also something you could try to verify it's not MAUI Blazor related) and it also failed there the same way, making it unlikely it's related to Blazor.

Likewise, the MAUI WebView is wrapping around WebView 2, with minimal changes. That doesn't mean there couldn't be something else within MAUI that could cause it to fail in the way you see, but it's extremely slim.

As you said:

"This may be an issue with WebView2 not initializing in MAUI correctly."

My guess is it's failing to initialize in WinUI 3, and using MAUI is unrelated. That's why I asked you to try it there without the MAUI UI framework. 

Beyond that other issue, it seems few others have hit it, meaning it could be specific to hardware or some other combination of things on your system that are causing it, making it extremely difficult if not impossible for any MAUI member to debug if we can't also replicate it. So I'm trying to help you out by helping isolate the issue on your machine, or it would be an issue that would end up in the backlog and not looked at for much later. 

@mattleibow do you have thoughts on this?

**Comment by tonicaceres** [comment] 2024-01-02 07:41
I'm getting the random black screen too when debugging a Maui Blazor app. Stopping the debug session and launching again fixes it, sometimes need to try this 2 or 3 times. I'm launching the debugger for Windows Machine. I deleted all the other platforms from the solution (iOS, Android, etc).

**Comment by Eilon** [comment] 2024-01-25 19:30
Duplicate of #15533

**Closed by Eilon** 2024-01-25 19:30 UTC
Labels: t/bug, area/blazor 🕸️, s/needs-attention
