### ISSUE TITLE
Selectbox is not visible when MAUI window is running on Windows 11.

### ISSUE THREAD

**Issue by nameofSEOKWONHONG** [dotnet/maui#10756] opened 2022-10-18 11:34 UTC
### Description

Windows 11, text disappears when select box is selected.

### Steps to Reproduce

Create a new ".NET MAUI App" project in Visual Studio 2022 (17.4.0 Preview 3.0)

No problems running Android.

Windows 11 only problem.

```xaml
<StackLayout Padding="5">
    <Label Text="회차" TextColor="{StaticResource Gray500}"
       FontSize="16"/>
    <Picker x:Name="picker"
        Title="회차를 선택하세요.">
        <Picker.ItemsSource>
            <x:Array Type="{x:Type x:String}">
                <x:String>1회차 10월 24일 촬영</x:String>
                <x:String>2회차 10월 25일 촬영</x:String>
                <x:String>3회차 10월 26일 촬영</x:String>
                <x:String>4회차 10월 27일 촬영</x:String>
                <x:String>5회차 10월 28일 촬영</x:String>
                <x:String>6회차 10월 29일 촬영</x:String>
                <x:String>7회차 10월 30일 촬영</x:String>
            </x:Array>
        </Picker.ItemsSource>
    </Picker>
</StackLayout>
```

[
![ezgif-2-4d8c8c7546](https://user-images.githubusercontent.com/24273022/196417837-d24b7167-7b1e-4587-94ee-cad709e70ae2.gif)
](url)

### Link to public reproduction project repository

https://github.com/nameofSEOKWONHONG/maui-tech-demo.git

### Version with bug

7.0 Release Candidate 2

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows SDK 10.0.19041.0

**Comment by nameofSEOKWONHONG** [comment] 2022-10-18 11:35
![ezgif-2-4d8c8c7546](https://user-images.githubusercontent.com/24273022/196418732-4b30b06a-7a69-442f-bc7e-37e0e1868002.gif)

**Comment by nameofSEOKWONHONG** [comment] 2022-10-18 11:52
Occurs when the system theme and the app theme do not match.
(SYSTEM : DARK)
(APP : LIGHT)

![ezgif-2-4d8c8c7546](https://user-images.githubusercontent.com/24273022/196421984-d6a8bcb6-fed6-4657-b180-cbd5fd5e06fc.gif)

**Comment by PureWeen** [comment] 2022-10-18 18:10
@nameofSEOKWONHONG if you change the page background or text color can you see the text?

**Comment by nameofSEOKWONHONG** [comment] 2022-10-19 03:57
> @nameofSEOKWONHONG if you change the page background or text color can you see the text?

When it loses focus, the text color changes to white.

The current text color is black.

**Comment by Zhanglirong-Winnie** [comment] 2023-05-30 05:53
Verified this issue with Visual Studio 17.7.0 Preview 1.0. Can repro on windows platform with sample project. 
[maui-tech-demo-main.zip](https://github.com/dotnet/maui/files/11596391/maui-tech-demo-main.zip)
![10756](https://github.com/dotnet/maui/assets/77434865/1a43b1e2-8abd-435f-a394-cf902bcc777e)

**Comment by TheoBrd** [comment] 2024-03-25 12:47
Did you find a way to solve your issue ?

**Comment by Cfun1** [comment] 2024-03-25 17:41
As a workaround you can apply the below style in your "Platforms/Windows/App.xaml":

```xaml
<maui:MauiWinUIApplication.Resources>
     <SolidColorBrush x:Key="ComboBoxForeground" Color="{StaticResource ComboBoxDropDownGlyphForeground}" />
     <Color x:Key="ComboBoxDropDownGlyphForeground">Black</Color>

     <Thickness x:Key="ComboBoxDropdownBorderThickness">5</Thickness>
     <SolidColorBrush x:Key="ComboBoxBorderBrush" Color="LightGray" />
     <SolidColorBrush x:Key="ComboBoxBorderBrushPointerOver" Color="{StaticResource ComboBoxDropDownGlyphForeground}" />

     <SolidColorBrush x:Key="ComboBoxForegroundPointerOver" Color="{StaticResource ComboBoxDropDownGlyphForeground}" />
    <SolidColorBrush x:Key="ComboBoxForegroundPressed" Color="{StaticResource ComboBoxDropDownGlyphForeground}" />
</maui:MauiWinUIApplication.Resources>
```

**Comment by nameofSEOKWONHONG** [comment] 2024-03-28 16:27
The above solution has been resolved. Thank you for your support. Closing the issue.

**Comment by MitchBomcanhao** [comment] 2024-03-28 16:47
well, the bug still exists. that you can apply a workaround doesn't mean the bug should be closed...

**Comment by nameofSEOKWONHONG** [comment] 2024-03-28 17:25
@MitchBomcanhao Reopened in response to MitchBomcanhaod's feedback. Thank you for your confirmation..

**Comment by jfversluis** [comment] 2024-10-02 07:27
Can't reproduce anymore with the latest .NET 8 stable version so I think this is fixed now, thanks everyone!

**Closed by jfversluis** 2024-10-02 07:27 UTC
Labels: t/bug, platform/windows 🪟, s/verified, area-controls-picker, s/triaged, s/needs-attention
