### ISSUE TITLE
(Windows) RC1 - RefreshView does not appear when swiping down with mouse

### ISSUE THREAD

**Issue by nacompllo** [dotnet/maui#6404] opened 2022-04-22 07:52 UTC
### Description

In Windows the RefreshView does not appear when you swipe down with the mouse, however in Android it does, as can be seen in this image:

<img width="413" alt="Issue07" src="https://user-images.githubusercontent.com/20904914/164642537-4710bbed-5d1e-48ba-a297-1863460e3bd6.png">

Repository:
https://github.com/nacompllo/MauiCollectionView/tree/test/WindowsRefreshView

### Steps to Reproduce

Cloning the attached repository and trying to Swipe down on the CollectionView on Windows the RefreshView will not appear.

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Windows 11

> VS bug [#1779664](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1779664)

**Comment by v-longmin** [comment] 2022-04-22 08:17
Verified repro on windows & Android with VS 17.3.0 Preview 1.0 [32414.199.main].Repro project:
[MauiCollectionView-test-WindowsRefreshView.zip](https://github.com/dotnet/maui/files/8538565/MauiCollectionView-test-WindowsRefreshView.zip)

**Comment by samhouts** [comment] 2022-05-05 00:13
This is another symptom of the root cause of #6152, which is basically that the mouse drag events are not captured. The swipe does work with touch.

**Comment by taublast** [comment] 2022-10-11 09:31
Any official guideline on how to use the RefreshView on windows for users with mice?

**Comment by shivagurunatha** [comment] 2022-12-13 17:43
In Windows I couldn't able to see the refresh icon on both swiping and dragging with mouse. 
Visual studio version - 17.5.0 Preview 1.0. 
Any workaround suggestions please?

**Comment by shivagurunatha** [comment] 2022-12-16 09:32
> In Windows I couldn't able to see the refresh icon on both swiping and dragging with mouse. Visual studio version - 17.5.0 Preview 1.0. Any workaround suggestions please?

As of now I had resolved it with a Handler. Not so best but convincing so far now. 


     public class CustomRefreshViewHandler : RefreshViewHandler
      {
        public CustomRefreshViewHandler()
        {

        }

        protected override void ConnectHandler(RefreshContainer nativeView)
        {
            if (PlatformView != null)
            {
                PlatformView.ManipulationMode = Microsoft.UI.Xaml.Input.ManipulationModes.All;
                PlatformView.ManipulationDelta += PlatformView_ManipulationDelta;
            }

            base.ConnectHandler(nativeView);
        }

        protected override void DisconnectHandler(RefreshContainer nativeView)
        {
            if (PlatformView != null)
            {
                PlatformView.ManipulationDelta -= PlatformView_ManipulationDelta;
            }

            base.DisconnectHandler(nativeView);
        }

        private void PlatformView_ManipulationDelta(object sender, Microsoft.UI.Xaml.Input.ManipulationDeltaRoutedEventArgs e)
        {
            double cumulativeY = e.Cumulative.Translation.Y;
            if (cumulativeY > 100)
            {
                if (!VirtualView.IsRefreshing)
                {
                    VirtualView.IsRefreshing = true;
                }
            }
        }
    }

**Comment by danardelean** [comment] 2023-02-17 14:16
This issue was opened almost a year ago and it is still not fixed On Windows if you use the mouse the RefreshView is not usable You cannot fire the event

**Comment by Markodirtyboy** [comment] 2023-03-28 22:52
Any updates to the workaround?

**Comment by jsuarezruiz** [comment] 2023-07-12 14:17
This issue have been fixed by https://github.com/dotnet/maui/pull/14261/files

**Closed** 2023-07-12 14:17 UTC
Labels: t/bug, platform/windows 🪟, p/1, p/2, partner/winui, partner/cat 😻, area/controls 🎮, s/verified, control-refreshview, s/triaged, fixed-in-8.0.0-preview.3.8149

**Comment by hartez** [comment] 2023-07-12 20:11
From the [design guidelines for Windows UI](https://learn.microsoft.com/en-us/windows/apps/design/controls/pull-to-refresh#refresh-controls): "RefreshContainer works only with touch, so we recommend that you also have a refresh button available for users who don't have a touch interface. You can position the refresh button at a suitable location in the app, either on a command bar or at a location close to the surface being refreshed."

The control is not designed to work with a mouse pointer; if you're building a desktop application with the intent of using mouse input, you should provide an appropriate refresh mechanism.
