### ISSUE TITLE
Image disappears after navigating back to page

### ISSUE THREAD

**Issue by owl-guy** [dotnet/maui#18895] opened 2023-11-20 08:43 UTC
### Description

I have an AppShell with two pages as FlyoutItems. The first page has an image that is loaded as embedded resource and bound to the page's ViewModel. At app start, the image displays properly, however, when i switch to the other page and then go back again, the image is not visible anymore. This does not happen when I set the source in XAML.

Tested with the newest release Version of .NET 8

### Steps to Reproduce

1. Create a new .NET MAUI app
2. Add a shell with two flyout items
3. Add an image to the first flyout page and bind its source to a viewmodel property which returns an embedded resource image
4. The image is displayed at app start
5. Navigate to the second flyout item and then back again to the first one
6. The image is not visible anymore

### Link to public reproduction project repository

https://github.com/owl-guy/ImageExample

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Android

**Comment by AnnYang01** [comment] 2023-12-21 08:47
Verified this on Visual Studio Enterprise 17.9.0 Preview 2 (.Net8.0). Repro on Android 14.0-API34. Not repro on Windows 11, iOS(OS:17.0) and MacCatalyst 13.6.1 with below Project:
[ImageExample.zip](https://github.com/dotnet/maui/files/13739205/ImageExample.zip)
Repro on Android 14.0-API34.
![18895-1](https://github.com/dotnet/maui/assets/131441429/1437c388-65a5-4e5b-95fd-a6d758c7a1cd)
Not repro on Windows 11, iOS(OS:17.0) and MacCatalyst 13.6.1.
https://github.com/dotnet/maui/assets/131441429/8887251a-02bf-40b0-8157-a9f44cfd03ee

**Comment by owl-guy** [comment] 2024-03-28 06:51
Will someone work on this?

**Comment by devhls** [comment] 2024-05-17 14:24
FYI, this can relate to a bug in rendering of a cached page on Android. Unfortunately, I have not solved this yet. All versions including 8.0.3 - 8.0.20 have the same issue: 
use image or label with fontimagesource,
navigate forward and back, 
and then the element in some cases becomes blank, 
especially when it is a button with the icon which is changed on a click.

**Comment by PureWeen** [comment] 2024-07-21 22:46
Duplicate of #14471

**Closed by PureWeen** 2024-07-21 22:46 UTC
Labels: t/bug, platform/android 🤖, area-navigation, area-controls-shell, s/verified, area-controls-image, s/triaged, migration-compatibility
