### ISSUE TITLE
[MAUI]Entering some text by PC keyboard or On-Screen Keyboard won't make the label turn green for API33 emulator.

### ISSUE THREAD

**Issue by RoiChen001** [dotnet/maui#18370] opened 2023-10-26 08:45 UTC
### Description

[MAUI]Entering some text by PC keyboard or On-Screen Keyboard won't make the label turn green for API33 emulator.

Note:
If we use API 34 emulator and enter some text by PC keyboard or On-Screen Keyboard, it will make the label turn green.

### Steps to Reproduce

1.Deploy https://devdiv.visualstudio.com/Pkgs/_git/VS.TestAssets.Xaml?path=/Assets/Projects/ManualMauiTests to API33 emulator.
2.Click G2.
3.Enter some text and the press enter on PC keyboard to complete the input.
4.View the color.
5.Enter some text and then tap 'Enter' on the 'On-Screen Keyboard' to  complete the input.
6.View the color.

Actual result:
Entering some text by PC keyboard or On-Screen Keyboard won't make the label turn green for API33 emulator.
![image](https://github.com/dotnet/maui/assets/143168639/37cc6dd4-954c-430a-a2e5-443d876c4128)

Expected result:
Entering some text by PC keyboard or On-Screen Keyboard, it will make the label turn green.

### Link to public reproduction project repository

https://devdiv.visualstudio.com/Pkgs/_git/VS.TestAssets.Xaml?path=/Assets/Projects/ManualMauiTests

### Version with bug

Microsoft.Maui.Controls 8.0.0-nightly.9509+sha.783db2459c-azdo.8589888
.NET SDK: 8.0.100-rc.23502.2

### Last version that worked well

Not a regression, The issue also repro on 8.0.0-rc.1.9171.

### Affected platforms

Android

**Comment by jsuarezruiz** [comment] 2023-11-06 16:55
Verified, can reproduce with Android API32, 33.

**Comment by PureWeen** [comment] 2024-01-10 20:51
Duplicate of #13921

**Closed by PureWeen** 2024-01-10 20:51 UTC
Labels: t/bug, platform/android 🤖, area/controls 🎮, csi-new, testing-manual
