### ISSUE TITLE
UIDevice.CurrentDevice.Orientation return Unknown in 8.0.20 works in 8.0.6

### ISSUE THREAD

**Issue by JoacimWall** [dotnet/maui#21922] opened 2024-04-18 15:48 UTC
### Description

The photos get some meta data wrong or something the start to rotate image left. After update to 8.0.20 no code changes in the app.

MAUI 8.0.6

the phone is held in the standard position charging socket downwards and takes a photo. UIDevice.CurrentDevice.Orientation = portrait
<img width="452" alt="image" src="https://github.com/dotnet/maui/assets/9278908/cbb74130-6b37-44d7-9dce-af0d480428a1">
<img width="540" alt="image" src="https://github.com/dotnet/maui/assets/9278908/08144d26-5e74-4c0c-8813-a8482b0472d4">

MAUI 8.0.20

the phone is held in the standard position charging socket downwards and takes a photo. UIDevice.CurrentDevice.Orientation = Unknown

<img width="452" alt="image" src="https://github.com/dotnet/maui/assets/9278908/8b00dd76-e2c1-4e81-b795-45427d163f57">
<img width="541" alt="image" src="https://github.com/dotnet/maui/assets/9278908/8e03cf3d-e26f-40f0-a028-0ee9282fb625">

the UIImage Photo.Orientation = Right both for 8.0.6 and 8.0.20

### Steps to Reproduce

Have a working app and update to MAUI 8.0.20 from 8.0.6. 
I have just spent 3 hours trying to solve this bug before I realized that it is probably a MAUI framework problem. You may know if you have been inside and changed something in this code.

### Link to public reproduction project repository

Not yet sorry

### Version with bug

8.0.20 SR4

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.6 SR1

### Affected platforms

iOS

### Did you find any workaround?

revert to MAUI 8.0.6

**Comment by zippo227** [comment] 2024-04-19 21:27
I can confirm that this is happening to me as well. I refrained from updating from 8.0.6 to 8.0.7 and 8.0.10 because images in my application became strangely rotated. I updated to 8.0.20 and that particular issue with images in list views went away. However,  photos taken with my app camera suddenly have the same issue as reported here.

**Comment by zippo227** [comment] 2024-04-20 18:20
I downgraded from 8.0.20 to 8.0.6 to temporarily resolve the issue. I would like to use 8.0.20 to support the android ripple fix updates. Anyone know if this rotation issue is being looked at?

**Comment by RoiChen001** [comment] 2024-04-23 06:17
Can repro this issue at iOS device on the latest 17.10 preview 4(8.0.10&8.0.20).
[MauiImageRegression-main (1).zip](https://github.com/dotnet/maui/files/15072158/MauiImageRegression-main.1.zip)
BTW,there is a similar issue https://github.com/dotnet/maui/issues/21314 but it has been closed.

**Comment by JoacimWall** [comment] 2024-04-29 06:06
Still in 8.0.21 so we are still on version 8.0.6 as new bugs come in during stabilisation of MAUI.

**Comment by zippo227** [comment] 2024-05-01 22:22
Is someone actively looking into this issue? @jsuarezruiz

**Comment by jfversluis** [comment] 2024-05-06 08:51
Looks like a duplicate of #21314 and fixed with #21458 which is currently only in the nightly feed. Would you be able to test that out and see if that fixes the issue? If yes, this should be fixed in an upcoming service release soon.

**Comment by JoacimWall** [comment] 2024-05-06 11:21
Same code  running MAUI 8.0.40-nightly.10602.   
As you can se the image get rotated on 17.4.1 devices. As Visual studio for mc don't work with debug on devices that are higher then 17.2 I can't debug this error. so the 17.4.1 device is installed from TestFlight and the 16.6 is debug.    

Physical device iPhone 11  running iOS 16.6 correct rotation. 
<img width="561" alt="image" src="https://github.com/dotnet/maui/assets/9278908/198b1df4-e98e-4114-81cd-d8365a5efd5b">

Physical device iPhone 14 Pro  running IOS 17.4.1
![Skärmavbild 2024-05-06 kl  13 16 26](https://github.com/dotnet/maui/assets/9278908/e2ed217e-a2a6-4cf5-909c-900b4fe4d6c7)

**Comment by JoacimWall** [comment] 2024-05-06 11:23
For your info we have the same issue on 17.4.1 devices running MAUI 8.0.6 reported from the TestFlight users.

**Comment by zippo227** [comment] 2024-05-06 20:18
@jfversluis I tested the nightly build. I went from version 8.0.6 to 8.0.40-nightly.10602 and the image rotation issues were fixed. I will wait for the release of 8.0.40 before putting it into my production apps. Do you know when that might be released?

**Comment by jfversluis** [comment] 2024-05-07 07:25
Perfect, thanks for letting us know! I'll be closing this one then.

We never really comment on release dates so I don't have an exact date for you unfortunately, but releases happen pretty frequent so it should arrive soon.

**Closed by jfversluis** 2024-05-07 07:25 UTC
Labels: t/bug, platform/iOS 🍎, area/essentials 🍞, s/verified, s/triaged, s/needs-attention, potential-regression
