### ISSUE TITLE
.Net MAUI , change the color of Back Button icon in Shell

### ISSUE THREAD

**Issue by adelmurad24** [dotnet/maui#20569] opened 2024-02-14 08:41 UTC
### Description

1 year later for this closed issue:
https://github.com/dotnet/maui/issues/11127
and still we're unable to change the back button color, which is fixed to be 'white' ... 
even if we use 'Back button behavior'
https://learn.microsoft.com/en-us/dotnet/maui/fundamentals/shell/navigation?view=net-maui-8.0&viewFallbackFrom=net-maui-6.0#back-button-behavior

we cant not set the new icon globally in AppShell.xaml for example, we've to use 'Back button behavior' in every page !

Please find a solution

### Public API Changes

..

### Intended Use-Case

..

**Comment by drasticactions** [comment] 2024-02-14 11:23
@adelmurad24 I tried out the repro project linked in that issue and I could not get the color of the cursor to change either. Based on that, I reopened it. I am going to close this issue since that one has a workaround step. It's not an ideal workaround, but it did work trying it for me. Thanks for reporting it again.

Duplicate of https://github.com/dotnet/maui/issues/11127

**Closed by drasticactions** 2024-02-14 11:23 UTC
Labels: proposal/open

**Comment by adelmurad24** [comment] 2024-02-14 11:45
> @adelmurad24 I tried out the repro project linked in that issue and I could not get the color of the cursor to change either. Based on that, I reopened it. I am going to close this issue since that one has a workaround step. It's not an ideal workaround, but it did work trying it for me. Thanks for reporting it again.
> 
> Duplicate of #11127

- that issue is locked, no body can comment.
- note that the issue is with .net 8. I tried to build the project with .net 7 and the icon is shown in dark and light mode but still no option to change its color

**Comment by drasticactions** [comment] 2024-02-14 11:47
Oops, sorry. I unlocked it.
