### ISSUE TITLE
iOS CollectionView size calculation

### ISSUE THREAD

**Issue by ViktorArbuzov** [dotnet/maui#6605] opened 2022-04-28 12:21 UTC
### Description

CollectionView taking more space than it's children's require.
Maui, iOS

### Steps to Reproduce

here is code example

```
<ScrollView>
                        <StackLayout>
                            <CollectionView
                                BackgroundColor="Green"
                                ItemsSource="{Binding Collection1}">
                                <CollectionView.ItemTemplate>
                                    <DataTemplate>
                                        <ContentView>
                                            <Label
                                                FontSize="20"
                                                Text="Test"
                                                TextColor="Black" />
                                        </ContentView>
                                    </DataTemplate>
                                </CollectionView.ItemTemplate>
                            </CollectionView>

                            <Label Text="text" />

                            <CollectionView
                                BackgroundColor="Red"
                                ItemsSource="{Binding Collection2}">
                                <CollectionView.ItemTemplate>
                                    <DataTemplate>
                                        <ContentView>
                                            <Label
                                                FontSize="20"
                                                Text="Test"
                                                TextColor="Black" />
                                        </ContentView>
                                    </DataTemplate>
                                </CollectionView.ItemTemplate>
                            </CollectionView>
                        </StackLayout>
                    </ScrollView>
```

and here is result 
![collectionview](https://user-images.githubusercontent.com/54932228/165750195-e63d486d-9aca-4582-b619-ab20101f1e7a.jpg)

as you can see - first collection view expanded, and second is not visible. 
looks like CollectionView on iOS calculation own size in a wrong way, on the Android it works correctly

### Version with bug

Preview 14

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

at list iOS 14.5

### Did you find any workaround?

as workaround I'm using StackLayout with BindableLayout

**Comment by kristinx0211** [comment] 2022-05-06 05:12
verified repro on IOS, repro project:
[MauiApp12.zip](https://github.com/dotnet/maui/files/8637653/MauiApp12.zip)

**Comment by espenrl** [comment] 2022-10-19 21:49
This code solves the problem for now.

``` xml
<CollectionView.Behaviors>
    <views:IOSFixInfiniteHeightCollectionView />
</CollectionView.Behaviors>
```

``` CSharp
    /// <summary>
    /// iOS CollectionView size calculation
    /// https://github.com/dotnet/maui/issues/6605
    /// </summary>
    public sealed class IOSFixInfiniteHeightCollectionView : Behavior<CollectionView>
    {
        private void CollectionViewOnSizeChanged(object? sender, EventArgs e)
        {
#if IOS
            if (sender is not CollectionView collectionView)
            {
                throw new InvalidOperationException();
            }
            if (collectionView.Handler?.PlatformView is not UIKit.UIView uiView)
            {
                throw new InvalidOperationException();
            }

            var uiCollectionView = uiView.Subviews
                .OfType<UIKit.UICollectionView>()
                .Single();

            const double emptyViewRequiredHeight = 50;
            const double additionalHeight = 20; // this is needed or else the collection view will be truncated
            var calculatedHeight = (double)uiCollectionView.CollectionViewLayout.CollectionViewContentSize.Height;
            var height = additionalHeight + calculatedHeight;
            collectionView.MaximumHeightRequest = Math.Max(emptyViewRequiredHeight, height);
#endif
        }

        protected override void OnAttachedTo(CollectionView bindable) => bindable.SizeChanged += CollectionViewOnSizeChanged;
        protected override void OnDetachingFrom(CollectionView bindable) => bindable.SizeChanged -= CollectionViewOnSizeChanged;
    }
```

**Comment by espenrl** [comment] 2022-10-23 01:12
This problem stems from using a CollectionView within a ScrollView. You may want to use `BindableLayout` instead.

https://learn.microsoft.com/en-us/dotnet/maui/user-interface/layouts/bindablelayout

**Comment by hartez** [comment] 2022-12-14 20:53
Duplicate of #9135

**Closed by hartez** 2022-12-14 20:53 UTC
Labels: t/bug, platform/iOS 🍎, p/2, area/collectionview 📃, s/verified
