### ISSUE TITLE
[Android] Runtime update of IsVisible Property is not working

### ISSUE THREAD

**Issue by bhuvan94** [dotnet/maui#8804] opened 2022-07-18 10:12 UTC
### Description

In Android, When updating the IsVisible property at runtime is not working.

### Steps to Reproduce

1. Run the attached sample [MauiApp7.zip](https://github.com/dotnet/maui/files/9131116/MauiApp7.zip)
2. Press **Click Here!** button.
3. Now you can see the issue.

# Android 

https://user-images.githubusercontent.com/20217737/179490722-85026589-d627-4a67-8bdc-06ab257d5c0a.mp4

## iOS

https://user-images.githubusercontent.com/20217737/179491123-44622572-6181-417f-ba76-bbe8dd85136a.mov

### Version with bug

6.0.400

### Last version that worked well

6.0.400

### Affected platforms

Android

### Affected platform versions

Android 11

### Did you find any workaround?

Not yet!

**Comment by Symbai** [comment] 2022-07-18 10:56
Dupe of #8044 wait for next update or use a nightly build.

**Comment by rmarinho** [comment] 2022-07-18 16:31
Duplicate of #8044

**Closed by rmarinho** 2022-07-18 16:31 UTC
Labels: t/bug, area/controls 🎮, s/needs-verification
