### ISSUE TITLE
[Bug] Layout issue

### ISSUE THREAD

**Issue by BaddyBy** [dotnet/maui#1112] opened 2021-05-28 04:51 UTC
### Description
Neither Labels nor Images are visible in GridLayout Sandple.Droid application
### Steps to Reproduce

1. Visual Studio 2019 Professional 16.10
2. Android emulator
3. Run Sample.Droid

### Expected Behavior
Grid with pictures is visible

### Actual Behavior
Empty space allocated for grid [see](https://prnt.sc/13i39w2)

**Comment by ncarandini** [comment] 2021-05-30 10:49
Hi @BaddyBy,
To run the MAUI demos, you need to follow the instructions found in the blog post [Announcing .NET MAUI Preview 4 - Get Started Today](https://devblogs.microsoft.com/dotnet/announcing-net-maui-preview-4/#get-started-today) and in the readme of [dotnet/maui-samples](https://github.com/dotnet/maui-samples).
The first requirement is to use [Visual Studio 2019 16.11 Preview 1](https://visualstudio.microsoft.com/vs/preview), so it won't work with Visual Studio 2019 Professional 16.10, so this is not a bug.

**Comment by jsuarezruiz** [comment] 2021-05-31 16:42
What .NET MAUI version are you using?

**Comment by BaddyBy** [comment] 2021-05-31 17:43
The latest on the issue date31 мая 2021 г. 7:42 ПП пользователь Javier Suárez ***@***.***> написал:
What .NET MAUI version are you using?

**Comment by BaddyBy** [comment] 2021-06-01 20:18
> Hi @BaddyBy,
> To run the MAUI demos, you need to follow the instructions found in the blog post [Announcing .NET MAUI Preview 4 - Get Started Today](https://devblogs.microsoft.com/dotnet/announcing-net-maui-preview-4/#get-started-today) and in the readme of [dotnet/maui-samples](https://github.com/dotnet/maui-samples).
> The first requirement is to use [Visual Studio 2019 16.11 Preview 1](https://visualstudio.microsoft.com/vs/preview), so it won't work with Visual Studio 2019 Professional 16.10 and this is not a bug.

Visual Studio
Currently, you can use Visual Studio 2019 16.10 on Windows (with the Xamarin workload installed). .NET 6 Preview 4 requires MSBuild 16.10, so .NET 6 projects will not be able to load in older versions of Visual Studio.

**Comment by BaddyBy** [comment] 2021-06-11 14:32
if I need to use only preview versions of Visual Studio than I have to leave

**Comment by hartez** [comment] 2021-08-13 16:23
This should be fixed in Preview 7. If not, tag me in this issue and I will re-open it.

**Closed by hartez** 2021-08-13 16:23 UTC
Labels: t/bug
