### ISSUE TITLE
Editor field OnCompleted on Android soft keyboard

### ISSUE THREAD

**Issue by david-maw** [dotnet/maui#5730] opened 2022-04-01 00:18 UTC
### Description

It's not clear how to mark an `Editor` field complete using a soft keyboard, on the Android one the enter key is shown by default but it acts as a newline marker which is reasonable but leaves nothing to signal 'Completed'. If you have a keyboard with distinct enter and tab keys it's easy, just use tab to signal completion.

Also the default 'VerticalTextAlignment' of an `Editor` field seems to be `Center`, it should be `Start` for compatibility with Xamarin (and because it looks better).. 

### Steps to Reproduce

1. Unzip the project from [Simple-Editor.zip](https://github.com/dotnet/maui/files/8393744/Simple-Editor.zip)
2. Compile and run it on Android
3. Select the Editor field (the bottom one)
4. Type some text, note that it is vertically aligned in the center of the field.
5. Try to use the soft keyboard to exit the field.

You should see something like this:
![Simple-Editor](https://user-images.githubusercontent.com/12423046/161170554-2cbcd712-d987-42d6-b9c1-930ab4a34fbc.png)

Note the blue button, it needs to be used for both `Enter` (to create a new line) and `Tab` (to signal the end of input in that field), which is tricky
 

### Version with bug

Preview 14 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 11

### Did you find any workaround?

No

**Comment by jinxinjuan** [comment] 2023-04-23 08:57
Verified this issue with Visual Studio Enterprise 17.6.0 Preview 3.0. Still Repro with above project [Simple-Editor.zip](https://github.com/dotnet/maui/files/8393744/Simple-Editor.zip).
![image](https://user-images.githubusercontent.com/37974803/233829993-7c435ece-9d80-4c19-9f88-785556142d26.png)

**Comment by mattleibow** [comment] 2023-10-05 00:13
Duplicate of https://github.com/dotnet/maui/issues/9796

**Closed by mattleibow** 2023-10-05 00:13 UTC
Labels: t/bug, platform/android 🤖, area/controls 🎮, s/verified, control-entry, s/triaged
