### ISSUE TITLE
Tapped event in TapGestureRecognizer is not raised up when add span dynamically

### ISSUE THREAD

**Issue by hrshfa** [dotnet/maui#17113] opened 2023-08-30 17:11 UTC
### Description

I want to show messages same as Whatsapp.Links and Phone Numer be clickable.Location and order of these is dynamic.by thanks ChatGPT i use this codes:

MessagePage.xml:

```xaml
       <?xml version="1.0" encoding="utf-8" ?>
        <ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
                     xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
                     x:Class="MauiChatApp.ClientApp.Views.MessagePage"
                     xmlns:local="clr-namespace:MauiChatApp.ClientApp.Utils"
                     Title="MessagePage">
            <ContentPage.Resources>
                <ResourceDictionary>
                    <local:MessageToFormattedStringConverter x:Key="MessageToFormattedStringConverter" />
                </ResourceDictionary>
            </ContentPage.Resources>
            <CollectionView x:Name="contactsCollection"
                                ItemsSource="{Binding Chats}"
                                Margin="20"
                                SelectionMode="None"
                                ItemsUpdatingScrollMode="KeepLastItemInView"
                HeightRequest="500"
                               >
        
                    <!-- Designate how the collection of items are laid out -->
                    <CollectionView.ItemsLayout>
                        <LinearItemsLayout Orientation="Vertical" ItemSpacing="10" />
                    </CollectionView.ItemsLayout>
        
                    <!-- Define the appearance of each item in the list -->
                    <CollectionView.ItemTemplate>
                        <DataTemplate>
                            <StackLayout>
                                <Label FontSize="14">
                                    <Label.FormattedText>
                                        <Binding Converter="{StaticResource MessageToFormattedStringConverter}" Path="TextMessage" />
                                    </Label.FormattedText>
                                </Label>
                            </StackLayout>
                        </DataTemplate>
                    </CollectionView.ItemTemplate>
                </CollectionView>
                
        </ContentPage>
```

MessageToFormattedStringConverter.cs:

```cs
    public class MessageToFormattedStringConverter : IValueConverter
      {
        public object Convert(object value, Type targetType, object parameter, CultureInfo culture)
        {
            //    MessageViewModel vm = new ();
            if (value is string message && !string.IsNullOrEmpty(message))
            {


                #region NewCode
                FormattedString formattedMessage = new FormattedString();
                // Split message into words
                var words = message.Split(' ');
                bool isFirstInteration = true;
                foreach (var word in words)
                {
                    if (isFirstInteration)
                    {
                        isFirstInteration = false;
                    }
                    else
                    {
                        formattedMessage.Spans.Add(new Span() { Text = " " });
                    }
                    if (IsUrl(word, out var uriResult) || IsPhoneNumber(word))
                    {
                        Span linkSpan = new Span()
                        {
                            Text = word,
                            TextColor = Colors.Blue,
                            TextDecorations = TextDecorations.Underline
                        };
                        var link_tap = new TapGestureRecognizer();
                        link_tap.NumberOfTapsRequired = 1;
                        link_tap.Tapped += async (s, e) =>
                        {
                            string url = string.Empty;

                            if (s is Label label && label.Text != null)
                            {
                                url = label.Text;
                            }
                            else if (s is Span span && span.Text != null)
                            {
                                url = span.Text;
                            }
                            if (IsUrl(url, out var uriResult))
                            {
                                await Launcher.OpenAsync(uriResult);
                            }
                            else
                            {
                                await Launcher.OpenAsync($"tel:{url}");
                            }
                        };
                        linkSpan.GestureRecognizers.Add(link_tap);// new TapGestureRecognizer { Command = OpenLinkCommand, CommandParameter = word });
                        formattedMessage.Spans.Add(linkSpan);
                    }
                    else
                    {
                        // Create a span for regular text
                        formattedMessage.Spans.Add(new Span() { Text = word });
                    }
                }
                return formattedMessage;
                #endregion
                //    return vm.CreateMessageWithLinks(message);
            }
            return new FormattedString();
        }
        public object ConvertBack(object value, Type targetType, object parameter, CultureInfo culture)
        {
            throw new NotImplementedException();
        }
        private bool IsUrl(string word,out Uri uriResult)
        {
            // Use a simple check or regex to verify if the word is a URL
            var result= Uri.TryCreate(word, UriKind.Absolute, out  uriResult) && (uriResult.Scheme == Uri.UriSchemeHttp || uriResult.Scheme == Uri.UriSchemeHttps);
            return result;
        }
        public static bool IsPhoneNumber(string number)
        {
            return Regex.Match(number, @"^\+?(\d+\-?\d+)+$").Success;
        }
    }
```

all code is ok and show messages same as Whatsapp but when click on links is not raised tapped event.

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

Android

**Comment by mattleibow** [comment] 2023-08-30 17:37
Duplicate of https://github.com/dotnet/maui/issues/4734

**Closed** 2023-08-30 17:37 UTC
Labels: t/bug
