### ISSUE TITLE
FilePicker Does not show in Mac Catalyst

### ISSUE THREAD

**Issue by mcferry** [dotnet/maui#20994] opened 2024-03-04 15:39 UTC
### Description

File Picker does not show up at all on mac catalyst. and application stays on the await of PickAsync command.

Version 17.6.9 (build 415)
Runtime
.NET 8.0.201 (64-bit)
Architecture: maccatalyst-x64

        var file = await FilePicker.PickAsync(new PickOptions
        {
            PickerTitle = "Pick your Image",
            FileTypes = FilePickerFileType.Images
        });
		if(file==null)
		{
			return;
		}
		else
		{
			...
		}

### Steps to Reproduce

Create a new .NET Maui App
Use code above inside the counter button to select a file.

### Link to public reproduction project repository

na

### Version with bug

8.0.6 SR1

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

Sonoma 14.1

### Did you find any workaround?

No

**Comment by mattleibow** [comment] 2024-03-04 15:42
Duplicate of https://github.com/dotnet/maui/issues/15126

**Closed by mattleibow** 2024-03-04 15:42 UTC
Labels: t/bug, platform/macOS 🍏, area/essentials 🍞

**Comment by mcferry** [comment] 2024-03-04 16:16
it's not a duplicate. it returns null after showing the open file dialog. but I cannot even see the open file dialog.

**Comment by mcferry** [comment] 2024-03-22 06:20
> ```
> <key>com.apple.security.assets.movies.read-only</key>
> <true/>
> <key>com.apple.security.assets.music.read-only</key>
> <true/>
> <key>com.apple.security.assets.pictures.read-only</key>
> <true/>
> <key>com.apple.security.files.downloads.read-only</key>
> <true/>
> <key>com.apple.security.files.user-selected.read-only</key>
> <true/>
> <key>com.apple.security.personal-information.photos-library</key>
> <true/>
> ```

Mate Thanks a lot. now It is working and you also are right it returns null.
