### ISSUE TITLE
CollectionView Footer disappears when modifying the collection [Android]

### ISSUE THREAD

**Issue by owl-guy** [dotnet/maui#21478] opened 2024-03-27 08:33 UTC
### Description

I have a CollectionView with an "Add" Button in the footer. When I click the button, a new element gets added to the underlying ObservableCollection. After the second tap on the button, it just disappears.

![col_view_footer](https://github.com/dotnet/maui/assets/114725843/eab7ab61-c18f-4c65-8865-6a46d07d5a58)

### Steps to Reproduce

1. Create a new MAUI project
2. Add a CollectionView with a footer containing a button
3. Add an ObservableCollection and bind it to the CollectionView as ItemsSource
4. Bind a clicked event to the button which adds an element to the ObservableCollection
5. Click the button once. The footer will still be visible, the new element will be added
6. Click a second time. The footer will disappear

### Link to public reproduction project repository

https://github.com/owl-guy/CollectionViewFooterExample

### Version with bug

8.0.10 SR3

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Android

**Comment by jfversluis** [comment] 2024-03-27 08:49
Duplicate of #8761

**Closed by jfversluis** 2024-03-27 08:49 UTC
Labels: t/bug
