### ISSUE TITLE
CaptureVideoAsync always returning null when using Windows Machine

### ISSUE THREAD

**Issue by efonsecab** [dotnet/maui#7616] opened 2022-05-30 23:14 UTC
### Description

When trying to capture video running the app as Windows Machine,
the video capture method does not show the webcam, and immediately returns null.
```
private async Task OnCaptureVideoClickedAsync()
        {
            if (await Permissions.CheckStatusAsync<Camera>() != PermissionStatus.Granted)
            {
                var result = await Permissions.RequestAsync<Camera>();
                if (result != PermissionStatus.Granted)
                {
                    ToastService.ShowError("You need to grant the camera permission to use this feature");
                    return;
                }
            }
            var video = await MediaPicker.Default.CaptureVideoAsync();
        }
```

Permissions are set like this

```
<Capabilities>
    <rescap:Capability Name="runFullTrust" />
    <DeviceCapability Name="location"></DeviceCapability>
	<DeviceCapability Name="webcam" />
    <DeviceCapability Name="microphone" />
  </Capabilities>
```

### Steps to Reproduce

1. Create a MAUI Blazor app
2. Add a button and invoke a method containing. 
var video = await MediaPicker.Default.CaptureVideoAsync();
3. Configure the permissions as in the description
4. Run the app as Windows Machine.

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

net6.0-windows10.0.19041.0

### Did you find any workaround?

No, haven't found a workaround.

**Comment by Xyncgas** [comment] 2022-05-31 00:11
Are you saying the application works on other machines aside from Windows Machine?

**Comment by uuggghhhJay** [comment] 2022-05-31 14:07
Hi getting the same result on MediaPicker.Default.CapturePhotoAsync() on a windows machine.

Capabilities set "webcam, microphone"

**Comment by VincentBu** [comment] 2022-06-07 08:08
run into same error when running MAUI App and MAUI Blazor app with vs main build(32606.310.main)

**Comment by efonsecab** [comment] 2022-06-10 15:34
Seems it is related to this issue and that it's not a MAUI issue, but instead a WinUI/platform issue
https://github.com/dotnet/maui/issues/5849

**Comment by janseris** [comment] 2022-06-10 17:44
> Seems it is related to this issue and that it's not a MAUI issue, but instead a WinUI/platform issue #5849

https://github.com/microsoft/WindowsAppSDK/issues/1034 since July 2021

**Comment by jfversluis** [comment] 2022-07-26 09:28
There are multiple duplicates for this and closing some of them including this one. I'd like to keep #7660 open as it has a workaround for now. Internally I am seeing if we can get the WinAppSDK team to prioritize that bug or if we should move forward for .NET MAUI to implement the workaround in the linked issue. Thanks everyone!

**Comment by jfversluis** [comment] 2022-07-26 09:28
Duplicate of #7660

**Closed by jfversluis** 2022-07-26 09:28 UTC
Labels: t/bug, area/essentials 🍞, s/verified
