### ISSUE TITLE
Cannot add Mica backdrop to Maui Blazor hybrid app

### ISSUE THREAD

**Issue by franklbt** [dotnet/maui#16874] opened 2023-08-19 06:20 UTC
### Description

I cannot use a mica backdrop for the full window size in a MAUI blazor hybrid app.

All attempts tried failed or not produced the exact result I wanted

### Version with bug

8.0.0-preview.7.8842

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

WindowsAppSDK 10.0.19041.0

### Did you find any workaround?

No

**Comment by drasticactions** [comment] 2023-08-20 16:03
If you create a WinUI3 app with a webview and try setting a Mica backdrop on it, does it work?

I will guess that it will do the same behavior since that's the underlying MAUI Blazor Webview, and there shouldn't be any difference between how it functions in this case. 

If it does do the same thing, then this issue should be moved to https://github.com/microsoft/microsoft-ui-xaml.

**Comment by drasticactions** [comment] 2023-08-20 16:05
Likewise, you could make a repro project showing how you're adding the Mica backdrop to the webview.

**Comment by franklbt** [comment] 2023-08-20 18:23
@drasticactions here is the repro https://github.com/franklbt/MicaBackdropBlazorHybridRepro

![Screen capture](https://github.com/dotnet/maui/assets/2249368/e01f82a4-1e5d-418f-9cfa-87e3169e8606)

**Comment by drasticactions** [comment] 2023-08-21 00:40
Did you try it with a WinUI3 app and its webview? Does it perform the same behavior?

**Comment by franklbt** [comment] 2023-08-22 21:48
In fact a similar behavior is present on winui3 app

**Comment by XamlTest** [comment] 2023-08-28 07:07
Verified this on Visual Studio Enterprise 17.8.0 Preview 1.0. Repro on Windows 11 .NET 8 with below Project:
[MicaBackdropBlazorHybridRepro.zip](https://github.com/dotnet/maui/files/12451303/MicaBackdropBlazorHybridRepro.zip)

**Comment by Eilon** [comment] 2023-08-30 17:36
Looks like a dupe of https://github.com/dotnet/maui/issues/14185, but it's ultimately most likely an issue with [WebView2](https://github.com/MicrosoftEdge/WebView2Feedback/issues) itself or with the [WindowsAppSDK/WinUI](https://github.com/microsoft/microsoft-ui-xaml).

**Closed by Eilon** 2023-08-30 17:36 UTC
Labels: t/bug, s/verified, s/triaged, s/needs-attention
