### ISSUE TITLE
MAUI program crash upon startup

### ISSUE THREAD

**Issue by ourweb4** [dotnet/maui#12355] opened 2022-12-30 15:50 UTC
### Description

```
'MyVoiceApp3.exe' (CoreCLR: DefaultDomain): Loaded 'D:\vsprojects\MyVoiceApp3\MyVoiceApp3\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\System.Private.CoreLib.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MyVoiceApp3.exe' (CoreCLR: clrhost): Loaded 'D:\vsprojects\MyVoiceApp3\MyVoiceApp3\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\MyVoiceApp3.dll'. Symbols loaded.
'MyVoiceApp3.exe' (CoreCLR: clrhost): Loaded 'D:\vsprojects\MyVoiceApp3\MyVoiceApp3\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\System.Runtime.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MyVoiceApp3.exe' (CoreCLR: clrhost): Loaded 'D:\vsprojects\MyVoiceApp3\MyVoiceApp3\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\Microsoft.Windows.ApplicationModel.WindowsAppRuntime.Projection.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MyVoiceApp3.exe' (CoreCLR: clrhost): Loaded 'D:\vsprojects\MyVoiceApp3\MyVoiceApp3\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\System.Runtime.InteropServices.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MyVoiceApp3.exe' (CoreCLR: clrhost): Loaded 'D:\vsprojects\MyVoiceApp3\MyVoiceApp3\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\WinRT.Runtime.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MyVoiceApp3.exe' (CoreCLR: clrhost): Loaded 'D:\vsprojects\MyVoiceApp3\MyVoiceApp3\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\System.Collections.Concurrent.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MyVoiceApp3.exe' (CoreCLR: clrhost): Loaded 'D:\vsprojects\MyVoiceApp3\MyVoiceApp3\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\System.Collections.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MyVoiceApp3.exe' (CoreCLR: clrhost): Loaded 'D:\vsprojects\MyVoiceApp3\MyVoiceApp3\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\System.Threading.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MyVoiceApp3.exe' (CoreCLR: clrhost): Loaded 'D:\vsprojects\MyVoiceApp3\MyVoiceApp3\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\System.Runtime.CompilerServices.Unsafe.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MyVoiceApp3.exe' (CoreCLR: clrhost): Loaded 'D:\vsprojects\MyVoiceApp3\MyVoiceApp3\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\System.Private.Uri.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MyVoiceApp3.exe' (CoreCLR: clrhost): Loaded 'D:\vsprojects\MyVoiceApp3\MyVoiceApp3\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\System.ObjectModel.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MyVoiceApp3.exe' (CoreCLR: clrhost): Loaded 'D:\vsprojects\MyVoiceApp3\MyVoiceApp3\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\System.ComponentModel.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MyVoiceApp3.exe' (CoreCLR: clrhost): Loaded 'D:\vsprojects\MyVoiceApp3\MyVoiceApp3\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\System.Numerics.Vectors.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
The program '[23180] MyVoiceApp3.exe' has exited with code 2147942405 (0x80070005).
```

### Steps to Reproduce

Run the program

### Link to public reproduction project repository

https://github.com/ourweb4/MyVoiceApp3a.git

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

All

**Comment by Eilon** [comment] 2022-12-30 17:39
@ourweb4 the repo you pointed to either doesn't exist or is not public. Can you please check that?

Also, it could help if you check if there are exceptions being thrown during app startup. Here's how you can do that:

1. In Visual Studio go to Debug / Windows / Exception Settings:<br><img width="365" alt="image" src="https://user-images.githubusercontent.com/202643/210097955-4d7ba134-139f-402c-a5c8-8b866414ef3d.png">
2. Ensure that Common Language Runtime Exceptions is fully checked:,br><img width="190" alt="image" src="https://user-images.githubusercontent.com/202643/210098022-4a3ffd85-6c78-48d6-bbea-864a259dad13.png">

And then run the app with the debugger (either press <kbd>F5</kbd>, or start debugging from the menu), and then see which exception(s), if any, you are seeing.

**Comment by ourweb4** [comment] 2022-12-31 20:46
https://github.com/ourweb4/MyVoiceApp3a

**Comment by Eilon** [comment] 2022-12-31 22:23
@ourweb4 that repo does not appear to be public as I get an HTTP 404 message when I go there. To verify if it is public, try opening the repo in a "Private Browsing" window and see if you can access it.

**Comment by ourweb4** [comment] 2022-12-31 23:01
how  do i open it

**Comment by Eilon** [comment] 2023-01-01 00:18
@ourweb4 if you use GitHub for Windows, you can publish your local app repo to your GitHub account. Then in GitHub go to that repo's settings and make sure it's set to public.

**Comment by ourweb4** [comment] 2023-01-03 16:00
https://github.com/ourweb4/MyVoiceApp3

**Comment by ourweb4** [comment] 2023-01-03 20:08
Help

**Comment by joeangry** [comment] 2023-01-04 00:01
I'm seeing something similar with a clean project. It only happens for Windows builds, it runs just fine in an Android emulator simulating a Pixel 5 device.
I've tested with another project which have worked fine previously but stopped working for Windows build after updating Visual Studio (Community) 2022 to 17.4.3 - previously 17.4.1

I'm wondering if its the latest service release that's causing problems? I'm experiencing the same symptoms on both my personal desktop and my work laptop both using same version of Visual Studio.

**Comment by Eilon** [comment] 2023-01-04 00:23
@ourweb4 in the app you shared this is what I see:

1. I first see this exception when the app starts:
   * > Microsoft.Maui.Controls.Xaml.XamlParseException: 'Position 28:17. StaticResource not found for key Mybutton'
   * And in the `Pages\LoginPage.xaml` file I see several elements using a non-existent `Mybutton` static resource: https://github.com/ourweb4/MyVoiceApp3/blob/main/MyVoiceApp3/Pages/LoginPage.xaml#L28
2. After removing that, I end up with this native exception:
   * > Exception thrown at 0x00007FFEC74A06BC (KernelBase.dll) in MyVoiceApp3.exe: WinRT originate error - 0x80131509 : 'Pending Navigations still processing'.
3. And then this:
   * > Exception thrown at 0x00007FFEC74A06BC (KernelBase.dll) in MyVoiceApp3.exe: WinRT originate error - 0x80131509 : 'A failure occurred in Application::OnLaunched, the application is unable to start.'.
4. And then several of these:
   * > Exception thrown at 0x00007FFEC74A06BC (KernelBase.dll) in MyVoiceApp3.exe: WinRT originate error - 0x80070057 : 'MauiStepperStyle.xaml is not a valid absolute URI.'.

And then the app crashes.

I suspect that (2) is the cause of the crash because I worked around (1), and other exceptions/errors seem spurious or only caused by previous errors.

I'll need to let other .NET MAUI experts look into this because it's not an area of .NET MAUI that I'm familiar with.

**Comment by Eilon** [comment] 2023-01-04 00:31
Definitely seems to do with navigation. If I comment out the navigation call in LoginPgae.xaml.cs then the app loads without any errors.

I commented out these lines: https://github.com/ourweb4/MyVoiceApp3/blob/main/MyVoiceApp3/Pages/LoginPage.xaml.cs#L32-L33

**Comment by bteamsoftware** [comment] 2023-01-04 00:32
![Screenshot 2023-01-03 182621](https://user-images.githubusercontent.com/50671522/210463121-d00dd977-740d-4e13-92c0-cbd942f6cfa4.png)

I've tracked my problem down to the above. What's interesting is I'm seeing this warning as well
![Screenshot 2023-01-03 182808](https://user-images.githubusercontent.com/50671522/210463236-d5535b4e-3549-4db1-b0c0-aa7bb98ad1d5.png)

I ended up changing the app GUID.

**Comment by Eilon** [comment] 2023-01-04 00:34
> I'm seeing something similar with a clean project. It only happens for Windows builds, it runs just fine in an Android emulator simulating a Pixel 5 device. I've tested with another project which have worked fine previously but stopped working for Windows build after updating Visual Studio (Community) 2022 to 17.4.3 - previously 17.4.0
> 
> I'm wondering if its the latest service release that's causing problems? I'm experiencing the same symptoms on both my personal desktop and my work laptop both using same version of Visual Studio.

@joeangry I'm not sure it's clear to me that this is the same root cause. Unless you're sure of that, can you log a new issue with detailed steps how to reproduce the issue?

**Comment by Eilon** [comment] 2023-01-04 00:34
> ![Screenshot 2023-01-03 182621](https://user-images.githubusercontent.com/50671522/210463121-d00dd977-740d-4e13-92c0-cbd942f6cfa4.png)
> 
> I've tracked my problem down to the above. What's interesting is I'm seeing this warning as well ![Screenshot 2023-01-03 182808](https://user-images.githubusercontent.com/50671522/210463236-d5535b4e-3549-4db1-b0c0-aa7bb98ad1d5.png)
> 
> I ended up changing the app GUID.

@bteamsoftware that seems like a different issue?

**Comment by bteamsoftware** [comment] 2023-01-04 00:36
It does. The new guid didn't help. It works perfectly fine on a different machine.

**Comment by rachelkang** [comment] 2023-01-04 19:29
Duplicate of #12313

**Closed by rachelkang** 2023-01-04 19:29 UTC
Labels: t/bug, platform/windows 🪟, area/shell 🐢, s/needs-attention

**Comment by ourweb4** [comment] 2023-01-04 19:48
Can someone push a working copy

**Comment by ourweb4** [comment] 2023-01-04 20:04
How do I get a new GUID?

**Comment by Eilon** [comment] 2023-01-04 22:13
> How do I get a new GUID?

The GUID thing was probably unrelated and was a different issue. The main issue you reported is a duplicate of https://github.com/dotnet/maui/issues/12313. I think a key cause is that in your app the LoginPage is navigating in OnAppearing, which is not the right event to handle such things. Perhaps you could change the app to not go to the "wrong" page at start and avoid the extra navigation, or find a different event from where you can do the additional navigation.

**Comment by ourweb4** [comment] 2023-01-05 20:34
now what?

**Comment by Eilon** [comment] 2023-01-05 20:50
@ourweb4 follow the linked issue https://github.com/dotnet/maui/issues/12313 to see what changes might be made in the future for your error, or try out the suggestion I mentioned in my previous comment.

**Comment by ourweb4** [comment] 2023-01-05 21:25
same problem

**Comment by Eilon** [comment] 2023-01-05 21:46
> same problem

What is the same problem? We need to know what you tried and what happened. This issue was closed as a duplicate of https://github.com/dotnet/maui/issues/12313 so please discuss on that open issue. Thanks!

**Comment by ourweb4** [comment] 2023-01-05 22:00
'MyVoiceApp3.exe' (CoreCLR: DefaultDomain): Loaded 'D:\vsprojects\MyVoiceApp3\MyVoiceApp3\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\System.Private.CoreLib.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MyVoiceApp3.exe' (CoreCLR: clrhost): Loaded 'D:\vsprojects\MyVoiceApp3\MyVoiceApp3\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\MyVoiceApp3.dll'. Symbols loaded.
'MyVoiceApp3.exe' (CoreCLR: clrhost): Loaded 'D:\vsprojects\MyVoiceApp3\MyVoiceApp3\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\System.Runtime.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MyVoiceApp3.exe' (CoreCLR: clrhost): Loaded 'D:\vsprojects\MyVoiceApp3\MyVoiceApp3\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\Microsoft.Windows.ApplicationModel.WindowsAppRuntime.Projection.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MyVoiceApp3.exe' (CoreCLR: clrhost): Loaded 'D:\vsprojects\MyVoiceApp3\MyVoiceApp3\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\System.Runtime.InteropServices.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MyVoiceApp3.exe' (CoreCLR: clrhost): Loaded 'D:\vsprojects\MyVoiceApp3\MyVoiceApp3\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\WinRT.Runtime.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MyVoiceApp3.exe' (CoreCLR: clrhost): Loaded 'D:\vsprojects\MyVoiceApp3\MyVoiceApp3\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\System.Collections.Concurrent.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MyVoiceApp3.exe' (CoreCLR: clrhost): Loaded 'D:\vsprojects\MyVoiceApp3\MyVoiceApp3\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\System.Collections.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MyVoiceApp3.exe' (CoreCLR: clrhost): Loaded 'D:\vsprojects\MyVoiceApp3\MyVoiceApp3\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\System.Threading.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MyVoiceApp3.exe' (CoreCLR: clrhost): Loaded 'D:\vsprojects\MyVoiceApp3\MyVoiceApp3\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\System.Runtime.CompilerServices.Unsafe.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MyVoiceApp3.exe' (CoreCLR: clrhost): Loaded 'D:\vsprojects\MyVoiceApp3\MyVoiceApp3\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\System.Private.Uri.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MyVoiceApp3.exe' (CoreCLR: clrhost): Loaded 'D:\vsprojects\MyVoiceApp3\MyVoiceApp3\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\System.ObjectModel.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MyVoiceApp3.exe' (CoreCLR: clrhost): Loaded 'D:\vsprojects\MyVoiceApp3\MyVoiceApp3\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\System.ComponentModel.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MyVoiceApp3.exe' (CoreCLR: clrhost): Loaded 'D:\vsprojects\MyVoiceApp3\MyVoiceApp3\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\System.Numerics.Vectors.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
The program '[13648] MyVoiceApp3.exe' has exited with code 2147942405 (0x80070005).

**Comment by ourweb4** [comment] 2023-01-05 22:18
MyVoiceApp3.exe' (CoreCLR: DefaultDomain): Loaded 'D:\vsprojects\MyVoiceApp3\MyVoiceApp3\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\System.Private.CoreLib.dll'. 
'MyVoiceApp3.exe' (CoreCLR: clrhost): Loaded 'D:\vsprojects\MyVoiceApp3\MyVoiceApp3\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\MyVoiceApp3.dll'. Symbols loaded.
'MyVoiceApp3.exe' (CoreCLR: clrhost): Loaded 'D:\vsprojects\MyVoiceApp3\MyVoiceApp3\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\System.Runtime.dll'. 
'MyVoiceApp3.exe' (CoreCLR: clrhost): Loaded 'D:\vsprojects\MyVoiceApp3\MyVoiceApp3\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\Microsoft.Windows.ApplicationModel.WindowsAppRuntime.Projection.dll'. 
'MyVoiceApp3.exe' (CoreCLR: clrhost): Loaded 'D:\vsprojects\MyVoiceApp3\MyVoiceApp3\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\System.Runtime.InteropServices.dll'. 
'MyVoiceApp3.exe' (CoreCLR: clrhost): Loaded 'D:\vsprojects\MyVoiceApp3\MyVoiceApp3\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\WinRT.Runtime.dll'. 
'MyVoiceApp3.exe' (CoreCLR: clrhost): Loaded 'D:\vsprojects\MyVoiceApp3\MyVoiceApp3\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\System.Collections.Concurrent.dll'. 
'MyVoiceApp3.exe' (CoreCLR: clrhost): Loaded 'D:\vsprojects\MyVoiceApp3\MyVoiceApp3\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\System.Collections.dll'. 
'MyVoiceApp3.exe' (CoreCLR: clrhost): Loaded 'D:\vsprojects\MyVoiceApp3\MyVoiceApp3\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\System.Threading.dll'. 
'MyVoiceApp3.exe' (CoreCLR: clrhost): Loaded 'D:\vsprojects\MyVoiceApp3\MyVoiceApp3\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\System.Runtime.CompilerServices.Unsafe.dll'. 
'MyVoiceApp3.exe' (CoreCLR: clrhost): Loaded 'D:\vsprojects\MyVoiceApp3\MyVoiceApp3\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\System.Private.Uri.dll'. 
'MyVoiceApp3.exe' (CoreCLR: clrhost): Loaded 'D:\vsprojects\MyVoiceApp3\MyVoiceApp3\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\System.ObjectModel.dll'. 
'MyVoiceApp3.exe' (CoreCLR: clrhost): Loaded 'D:\vsprojects\MyVoiceApp3\MyVoiceApp3\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\System.ComponentModel.dll'. 
'MyVoiceApp3.exe' (CoreCLR: clrhost): Loaded 'D:\vsprojects\MyVoiceApp3\MyVoiceApp3\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\System.Numerics.Vectors.dll'. 
The program '[22672] MyVoiceApp3.exe' has exited with code 2147942405 (0x80070005).

**Comment by joeangry** [comment] 2023-01-08 13:30
> @joeangry I'm not sure it's clear to me that this is the same root cause. Unless you're sure of that, can you log a new issue with detailed steps how to reproduce the issue?

Seems my problem was fixed with a simple reinstall and reboot. Thanks anyway.
