### ISSUE TITLE
[WinUI] First Entry gets focused when page appears

### ISSUE THREAD

**Issue by Sofiya-kumar** [dotnet/maui#23911] opened 2024-07-30 10:57 UTC
### Description

The entry gets focused when the page appears and any click action like dropdown item selected or navigating from any page to this page entry gets focused.

![image](https://github.com/user-attachments/assets/6572fa80-3f6c-4a99-b8e5-7c332553714c)

### Steps to Reproduce

1) When a Page appears or any click action is triggered.

### Link to public reproduction project repository

[here](https://github.com/Sofiya-kumar/EntryFocus)

### Version with bug

8.0.3 GA

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows

**Comment by Sofiya-kumar** [comment] 2024-08-01 05:26
Please refer the repository below 

[here](https://github.com/Sofiya-kumar/EntryFocus)

**Comment by Zhanglirong-Winnie** [comment] 2024-08-01 05:36
This issue has been verified using Visual Studio 17.11.0 Preview 6.0(8.0.71&8.0.3). Can repro on Windows platform.

**Comment by Sofiya-kumar** [comment] 2024-08-03 17:14
Thanks @MartyIX , I tried with [#11472 (button with HeightRequest as 0)](https://github.com/dotnet/maui/issues/11472#issuecomment-1898318085). That helps

**Comment by PureWeen** [comment] 2024-08-09 23:03
Duplicate of #11472

**Closed by PureWeen** 2024-08-09 23:03 UTC
Labels: t/bug, platform/windows 🪟, s/verified, area-controls-entry, s/triaged, s/needs-attention
