### ISSUE TITLE
Content inside frame not visible

### ISSUE THREAD

**Issue by nielscup** [dotnet/maui#12099] opened 2022-12-14 12:27 UTC
### Description

The label is not visible:

```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MauiApp10.MainPage">
    <ContentPage.Content>
        <Frame HeightRequest="200" WidthRequest="400">
            <Label Text="TEST" TextColor="Red" />
        </Frame>
    </ContentPage.Content>
</ContentPage>
```

Same bug as this which was closed: https://github.com/dotnet/maui/issues/7139

### Steps to Reproduce

Copy paste the above xaml in to an app and run. The Label is not visible

### Link to public reproduction project repository

do-it-yourself.ms

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

ios

### Did you find any workaround?

Use a border instead, but this is not the same as a Frame

**Comment by jsuarezruiz** [comment] 2022-12-15 12:09
Could you share a sample where reproduce the issue?. Cannot reproduce it.

![image](https://user-images.githubusercontent.com/6755973/207855756-082f133a-8675-4ec2-8ee4-e38e036a73ae.png)

**Comment by nielscup** [comment] 2022-12-15 16:47
@jsuarezruiz Thanks for taking a look at this. I did another test and it looks like Hot Reload does not like `Frame`: 

1. comment out the label and the screen does not update.
2. If you replace `Frame` with `Border`  it works as expected.
3. Restarting the project displays the label within the frame correctly.

**Comment by XamlTest** [comment] 2023-06-12 09:25
Verified this on Visual Studio Enterprise 17.7.0 Preview 1.0. This issue does not repro on Android 13.0-API33, repro on Windows 11 and iOS 16.4 with below Project:
[12099.zip](https://github.com/dotnet/maui/files/11720749/12099.zip)

Comment out the label in Frame during deploying, application does not update.
![image](https://github.com/dotnet/maui/assets/97647558/e1c5843f-768d-46f2-9cf1-48a04640a7bb)

**Comment by jfversluis** [comment] 2024-08-12 07:55
Frame will become [obsolete in .NET 9](#23184) in favor of `Border`. So I don't think this will be fixed anymore, if it hasn't been fixed in the meantime 😄 

Together with not a lot of traction in this issue, closing this for now.

**Closed by jfversluis** 2024-08-12 07:55 UTC
Labels: t/bug, platform/iOS 🍎, s/verified, area-controls-frame, s/triaged, s/needs-attention
