### ISSUE TITLE
Specify Front or Back Camera - MediaPicker CapturePhotoAsync()

### ISSUE THREAD

**Issue by ricavir11** [dotnet/maui#26371] opened 2024-12-04 16:33 UTC
### Discussed in https://github.com/dotnet/maui/discussions/9520

<div type='discussions-op-text'>

<sup>Originally posted by **rossatkinson265** August 18, 2022</sup>
When opening the device's camera I would like to specify that the camera should open on the front camera.

I am using MediaPicker.Default.CapturePhotoAsync() to open the device's camera and capture a photo. 

I am developing a tablet application and the behaviour I have observed on test devices is as follows:

**Behaviour on Android Samsung tablet:**
Camera remembers previous settings, therefore if the user changes to front camera on first open, the subsequent open will also be front camera. This is good because the user only has to switch to front camera once.

**Behaviour on iOS iPad:**
Camera always defaults to rear camera, regardless of previous camera settings. This is frustrating because the user has to switch to front camera each time they clock in.

**Suggestion:**
I notice that the CapturePhotoAsync method can accept MediaPickerOptions as a parameter. If feasible, it would be nice to be able to specify which camera the device should open with, as part of the MediaPickerOptions parameter, or potentially overload the method and add a CameraOptions parameter, which would enable us to specify front or rear camera. 
</div>

**Comment by jfversluis** [comment] 2024-12-05 09:33
Duplicate of #23596

**Closed by jfversluis** 2024-12-05 09:33 UTC
