### ISSUE TITLE
Entry is not triggering the UnFocused event in Android and IOS  after upgrading to .NET 8 

### ISSUE THREAD

**Issue by AlejandroHV** [dotnet/maui#18854] opened 2023-11-17 20:59 UTC
### Description

The Entry control is not triggering the UnFocused event on Android and IOS after upgrading to .NET 8.

We have an official APP we are creating with MAUI that has multiple functionalities and the Entry was working before upgrading to .NET 8 it was working as expected on .NET 7 (When clicking on any control with FOCUS) it will called the UnFocused event. That behavior worked for us as we are calling an API after the user finishes typing in the field, we cannot use the "OnChange" event of the entry. 

I created a basic MAUI project with the example template   I additionally added an Entry with an UnFocused Event ,a Button and a Label.

 Expected behavior : 

The behavior should be when I update the Entry the text of the entry should be shown on the Label below when the UnFocused event is called. For example:  when the button is clicked. 

Current behavior: 

When I update the Entry and then click on the button it does not call the "UnFocused" event from the Entry. 

Project version
.NET 8.0 SDK Version: 8.0.100
MAUI .NET 8
IOS: 17 
ANDROID 14. 
```
Installed Workload Id      Manifest Version      Installation Source
--------------------------------------------------------------------
maui-ios                            8.0.3/8.0.100         SDK 8.0.100        
maui-android                    8.0.3/8.0.100         SDK 8.0.100        
maui                                   8.0.3/8.0.100         SDK 8.0.100        
```

### Steps to Reproduce

1. Create a new MAUI project with .NET 8. 
2. Add an Entry, Button and a Label.  
3. Add a UnFocused event which will update a Label. 
4. Add an Onclick event to the button that updates a count. 

Expected behavior : 
When I update the entry, the text  should be shown on the Label below when the UnFocused event is called. For example:  when the button is clicked. 

Current behavior: 

When I update the Entry and then click on the button it does not call the "UnFocused" event from the Entry. 
The label does not display the text. 

Code: 

MainPage.xaml.cs 
```cs
public partial class MainPage : ContentPage
{
	int count = 0;

	public MainPage()
	{
		InitializeComponent();
	}

	private void OnCounterClicked(object sender, EventArgs e)
	{
		count++;

		if (count == 1)
			CounterBtn.Text = $"Clicked {count} time";
		else
			CounterBtn.Text = $"Clicked {count} times";


        SemanticScreenReader.Announce(CounterBtn.Text);
	}

    private void OnResetClicked(object sender, EventArgs e)
    {
        UnFocusedLbl.Text = "";
    }

    private void EntryUnfocused(System.Object sender, Microsoft.Maui.Controls.FocusEventArgs e)
    {

		var entry = (Entry)sender;
        UnFocusedLbl.Text = entry.Text;
    }
}
```

MainPage.xaml 

```xaml
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="TestFieldsFocus.MainPage">

    <ScrollView>
        <VerticalStackLayout
            Padding="30,0"
            Spacing="25">
            <Image
                Source="dotnet_bot.png"
                HeightRequest="300"
                Aspect="AspectFit"
                Margin="-30,0"
                SemanticProperties.Description="dot net bot in a race car number eight" />

            <Label
                Text="Hello, World!"
                Style="{StaticResource Headline}"
                SemanticProperties.HeadingLevel="Level1" />

            <Label
                Text="Welcome to &#10;.NET Multi-platform App UI"
                Style="{StaticResource SubHeadline}"
                SemanticProperties.HeadingLevel="Level2"
                SemanticProperties.Description="Welcome to dot net Multi platform App U I" />

            <Entry x:Name="textEntry" Unfocused="EntryUnfocused" Text="Hello"> </Entry>
             <Label
                x:Name="UnFocusedLbl"
                Style="{StaticResource SubHeadline}" Text=""/>
            <Button
                x:Name="CounterBtn"
                Text="Click me" 
                SemanticProperties.Hint="Counts the number of times you click"
                Clicked="OnCounterClicked"
                HorizontalOptions="Fill" />

            <Button
                x:Name="ResetBtn"
                Text="Reset Label" 
                SemanticProperties.Hint="Counts the number of times you click"
                Clicked="OnResetClicked"
                HorizontalOptions="Fill" />
        </VerticalStackLayout>
    </ScrollView>

</ContentPage>
```

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.101

### Affected platforms

iOS, Android

### Affected platform versions

IOS 15, Android  14

### Did you find any workaround?

No

### Relevant log output

```shell
No
```

**Comment by mattleibow** [comment] 2023-11-17 21:41
I did a test and tapping outside the text box is not really unfocusing the entry so that is why it never fires. And tapping the button is not actually focusing the button. Android does not work like that.

However, if you TAB to the button, then the entry unfocuses and the button focuses.

@PureWeen is this correct behaviour or is there an issue where tapping buttons is supposed to focus the button?

**Comment by mattleibow** [comment] 2023-11-17 21:49
Duplicate of https://github.com/dotnet/maui/issues/11881

**Closed** 2023-11-17 21:50 UTC
Labels: t/bug, area/keyboard

**Comment by AlejandroHV** [comment] 2023-11-17 21:53
The other issue is for Android only. This issued to work on IOS as mentioned in .NET7 @mattleibow

**Comment by AlejandroHV** [comment] 2023-11-17 21:59
This was introduced for IOS on .NET 8. @mattleibow

**Comment by PureWeen** [comment] 2023-11-18 00:04
@AlejandroHV try this new property
https://github.com/dotnet/maui/pull/16530

**Comment by AlejandroHV** [comment] 2023-11-20 18:33
Thank you. It helped.

**Comment by pulmuone** [comment] 2023-11-28 00:15
This is a temporary solution to this bug.
I used the Maui code.
In Xamarin, Unfocus of Entry is automatically called when another control is clicked, but in Maui, the developer has to do it.

my source 
https://github.com/pulmuone/SimpleMVVM4Maui

test movie
https://github.com/dotnet/maui/assets/42885949/758a4c0c-3ab9-4cd1-bf49-85d0cd7d1290
