### ISSUE TITLE
Toggle visibility ok when start as IsVisible="True", but not when starting IsVisible="False"

### ISSUE THREAD

**Issue by gfmoore** [dotnet/maui#8185] opened 2022-06-20 21:24 UTC
### Description

Please see repo at https://github.com/gfmoore/TestIsVisible.App

Using MVVM and community toolkit mvvm

So created two buttons in a grid and in viewmodel have ObservableProperty set to true
Second button's IsVisible bound to this property
First button bound to a command and toggles the property.

Works fine when property starts as true, but not when starts false

Suspect that the grid is not taking note of second button when IsVisible set false and therefore cannot render it when set true.

Here's code
MainPage.xaml
```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:local="clr-namespace:TestIsVisible"
             x:Class="TestIsVisible.MainPage">

  <Grid RowDefinitions="100, 100">
    
    <Button Grid.Row="0" 
            Text="Toggle Button2 Visibility"
            Command="{Binding ToggleVisibilityCommand}"/>
    
    <Button Grid.Row="1" 
            IsVisible="{Binding ButtonVisible}"
            Text="Button2"/>
    
  </Grid>
  
</ContentPage>
```

MainPage.xaml.cs
```
namespace TestIsVisible;

public partial class MainPage : ContentPage
{
	public MainPage()
	{
		InitializeComponent();
    BindingContext = new MainPageViewModel();
  }

}
```

and MainPageViewModel.cs
```
using CommunityToolkit.Mvvm.ComponentModel;
using System.Windows.Input;

namespace TestIsVisible;

public partial class MainPageViewModel : ObservableObject 
{

  [ObservableProperty]
  public bool buttonVisible = true;  //<--- Chnage this to false, cannot toggle button2

  public ICommand ToggleVisibilityCommand => new Command(() =>
  {
    Console.WriteLine("Toggle visibility");
    ButtonVisible = !ButtonVisible;
  });

}
```

Would welcome any idea at what point I could set the button to invisible.

### Steps to Reproduce

Grab repo (Note it won't be here for ever :) )

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Visual Studio, real android phone

### Did you find any workaround?

Not yet, need a life cycle event where I can set property to false before people notice it

**Comment by Symbai** [comment] 2022-06-20 22:46
Looks like a dupe of #8044 so it should get fixed when #8136 is merged.

**Closed** 2022-06-22 19:05 UTC
Labels: t/bug, area/controls 🎮, s/needs-verification
