### ISSUE TITLE
Blue window background in maui application

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#15366] opened 2023-05-31 18:14 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Blue-window-background-in-maui-applicati/10225572)._

---
[severity:I'm unable to use this version] [regression]
On a new visual studio 2022 installation, I create a new .net maui blazor app. The first time I run the project, it opens fine. The second time however, the window remains with a blue background. Sometimes it is back ok after closing and restarting visual studio, but this is not always the case.

---
#### Feedback Bot on 12/8/2022, 05:59 PM: 

(private comment, text removed)
#### Roi Chen [MSFT] on 12/8/2022, 11:22 PM: 

(private comment, text removed)
#### Bart Wynants on 12/12/2022, 00:41 AM: 

(private comment, text removed)
#### Feedback Bot on 12/13/2022, 02:56 AM: 

(private comment, text removed)
#### Feedback Bot on 12/13/2022, 08:44 AM: 

(private comment, text removed)
#### Feedback Bot on 4/3/2023, 07:23 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment] 2023-06-01 16:41
Thanks for contacting us. Can you try to run the app from the command line (using `dotnet run`) and see if it behaves the same way?

**Comment by Eilon** [comment] 2023-12-13 19:44
This looks like a dupe of https://github.com/dotnet/maui/issues/15533.

**Closed by Eilon** 2023-12-13 19:44 UTC
Labels: t/bug, area/blazor 🕸️
