### ISSUE TITLE
[Android] Icon not found if called something else than appicon

### ISSUE THREAD

**Issue by janseris** [dotnet/maui#7202] opened 2022-05-15 15:31 UTC
### Description

Icon not found if called something else than appicon

### Steps to Reproduce

change icon file name

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

**Comment by jfversluis** [comment] 2022-05-16 11:36
Duplicate of #5652

**Closed by jfversluis** 2022-05-16 11:36 UTC
Labels: t/bug, s/needs-verification
