### ISSUE TITLE
ListView WinUI Group Header renderers incorrect string for first group header

### ISSUE THREAD

**Issue by PureWeen** [dotnet/maui#4166] opened 2022-01-17 18:31 UTC
### Description

Go to the ListRefreshView sample in the gallery on WinUI

### Steps to Reproduce

Go to the ListRefreshView sample in the gallery on WinUI

### Version with bug

Preview 13

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

WinUI

**Comment by v-longmin** [comment] 2022-03-04 07:17
Thank you so much for your bug report! Unfortunately, we cannot reproduce your issue with the information above, could you provide a sample project and screenshots or more details that we can reproduce your issue? That should greatly speed up the process, thanks!

**Comment by PureWeen** [comment] 2022-03-04 16:41
@v-longmin This issue is reproduceable using our the samples gallery that's part of this repository.

Don't worry about validating this one. Thank you!!

**Comment by jsuarezruiz** [comment] 2022-03-30 09:59
This issue is already fixed by https://github.com/dotnet/maui/pull/5510

**Closed by jsuarezruiz** 2022-03-30 09:59 UTC
Labels: t/bug, area/ListView, s/verified, s/triaged
