### ISSUE TITLE
[Windows] ContentPage BackgroundColor Transparent not working

### ISSUE THREAD

**Issue by dabbinavo** [dotnet/maui#12926] opened 2023-01-26 13:50 UTC
### Description

Setting a `ContentPage`'s `BackgroundColor` to `Transparent` and pushing it with `Navigation.PushModalAsync` displays a white background instead of letting the content of the `ContentPage` below "shining through".

There was the exact same bugreport for iOS (#8526) which was solved and closed.  https://github.com/dotnet/maui/issues/8526#issuecomment-1299398480 stated that this also affects WinUI, but there was no response to this.

The reproduction repository has one commit that shows all changes that were made to the C# MAUI startup project.

Actual (Windows):
![windows](https://user-images.githubusercontent.com/14122508/214846200-9a99514b-ebab-4c9d-9652-038a9aa4ebd0.gif)

Expected (Android):
![android](https://user-images.githubusercontent.com/14122508/214846767-1c0816ad-4e33-48e6-96f0-0d80b4de2ac4.gif)

### Steps to Reproduce

1. Checkout the reproduction project repository
2. Build and run the project (`Windows Machine`)

### Link to public reproduction project repository

https://github.com/dabbinavo/repro_winui-contentpage-not-transparent

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Windows 10 Enterprise 19044.2486

### Did you find any workaround?

No

**Comment by PureWeen** [comment] 2023-01-26 19:11
Duplicate of #7450

**Closed by PureWeen** 2023-01-26 19:11 UTC
Labels: t/bug, platform/windows 🪟, area/navigation 🧭
