### ISSUE TITLE
Android MauiWebView Layout issue

### ISSUE THREAD

**Issue by jichulu** [dotnet/maui#9517] opened 2022-08-18 09:55 UTC
### Description

Using webview to load some page will not work

### Steps to Reproduce

1. Add webview control to ContentPage
2. Set the source as https://cn.bing.com/
```
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:local="clr-namespace:MauiMailApp">
    <WebView Source="https://cn.bing.com/"></WebView>
</ContentPage>
```
3. Run on Android, the webview can't see normal page
4. Use edge browser tool inspect the webview page, will found that html/body element's height are zero.
```
edge://inspect/#devices
```

But when set the source as https://cn.bing.com/search?q=maui 
webview will show success

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 10

### Did you find any workaround?

It may be a bug on this code, LayoutParameters  should be new ViewGroup.LayoutParams(-1, -1)

```csharp
Microsoft.Maui.Handlers.WebViewHandler
protected override WebView CreatePlatformView()
{
	MauiWebView mauiWebView = new MauiWebView(this, base.Context);
	mauiWebView.LayoutParameters = new ViewGroup.LayoutParams(-1, -2);
	mauiWebView.Settings.JavaScriptEnabled = true;
	mauiWebView.Settings.DomStorageEnabled = true;
	mauiWebView.Settings.SetSupportMultipleWindows(support: true);
	return mauiWebView;
}
```
Create a customer WebViewHandler will resolve
```csharp
internal partial class MyWebViewHandler : WebViewHandler
{
    protected override global::Android.Webkit.WebView CreatePlatformView()
    {
        var webview = base.CreatePlatformView();
        webview.LayoutParameters = new Android.Views.ViewGroup.LayoutParams(-1, -1);
        return webview;
    }
}
```
 but the Bing search page no backgroup image
 It seems like some html5 feature not support, link bing home page, the header preload link are not work
```
<link rel="preload" href="xxx" as="image">
```

**Comment by PureWeen** [comment] 2022-08-18 18:26
Closing as a duplicate of #8738

**Closed by PureWeen** 2022-08-18 18:26 UTC
Labels: t/bug

**Comment by Gypsy-H-Takumi** [comment] 2022-08-28 11:53
I am having this issue as well. 
Yes. I worked as using below code. 
`webview.LayoutParameters = new Android.Views.ViewGroup.LayoutParams(-1, -1);`
