### ISSUE TITLE
Navigating between the ShellContent tabs by swiping right-left

### ISSUE THREAD

**Issue by LeoKhariton** [dotnet/maui#16011] opened 2023-07-05 16:39 UTC
### Description

On Android, you can move between the ShellContent tabs by swiping right-left. How do I disable this behavior?
for example, in this
```csharp
<Tab>
    <ShellContent ContentTemplate="{DataTemplate local:Page1}"/>
    <ShellContent ContentTemplate="{DataTemplate local:Page2}"/>
    <ShellContent ContentTemplate="{DataTemplate local:Page3}"/>
</Tab>
```
I can navigate between Page1, Page2 and Page3 by swiping.
what happens is that I want to scroll the page down, but I do it carelessly and end up on the next tab!

### Public API Changes

```csharp
<Tab SwipeEnabled="False"/>
```

### Intended Use-Case

in the Android version of the application, the user will not accidentally switch between ShellContent tabs. such navigation will be available only by clicking on the tab title.

**Comment by PureWeen** [comment] 2023-07-05 18:13
Duplicate of #10182

**Closed by PureWeen** 2023-07-05 18:13 UTC
Labels: proposal/open, area/shell 🐢
