### ISSUE TITLE
AppThemeBinding not working (p11/p12)

### ISSUE THREAD

**Issue by jamesmontemagno** [dotnet/maui#4335] opened 2022-01-26 19:32 UTC
### Description

See -> https://github.com/microsoft/dotnet-podcasts/issues/36

Basically the app theme doesn't seem to apply the theme across the board.

### Steps to Reproduce

1.) Download .net podcast app and run on any platform and see

### Version with bug

Preview 11

### Last version that worked well

Preview 10

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

All

### Did you find any workaround?

Nope

**Comment by jamesmontemagno** [comment] 2022-02-06 05:51
I have uploaded a sample project both shell and non-shell appear broken.:

MauiApp1 -> Notice that both background color does not adjust on the content page:

```xaml
BackgroundColor="{AppThemeBinding Light={StaticResource LightColor}, Dark={StaticResource DarkColor}}"
```

MauiApp2 in the sln is not Shell, and notice that it doesn't work either.

Tested this out on Android emulators by toggling the Light/Dark mode

**Comment by jamesmontemagno** [comment] 2022-02-06 05:52
@Redth @Eilon I have updated this as it is broken in both shell and non-shell apps.

**Comment by IeuanWalker** [comment] 2022-02-06 13:30
@jamesmontemagno not sure if its possibly related to another bug i reported #4143

**Comment by jamesmontemagno** [comment] 2022-02-06 17:13
@IeuanWalker could be similar.. however I also tried:

```
BackgroundColor="{AppThemeBinding Light=White, Dark=Black}"
```

And this didn't work either... so maybe because AppThemeBinding is dynamic and that broke perhaps...

**Comment by Eilon** [comment] 2022-02-08 04:20
@jamesmontemagno when you say non-Shell apps, do you mean the Blazor MAUI template?

**Comment by jamesmontemagno** [comment] 2022-02-08 04:58
Just a file-new is what I mean. I assume the same with a hybrid app effecting native controls

**Comment by shimingsg** [comment] 2022-02-16 03:57
Verified repro with Android 11 and the above project.

**Comment by PureWeen** [comment] 2022-03-22 22:05
I'm going to assume this is a duplicate of this issue
https://github.com/dotnet/maui/issues/5044

**Comment by jamesmontemagno** [comment] 2022-03-23 04:49
I think so :)

**Comment by PureWeen** [comment] 2022-04-20 18:39
Possibly related
https://github.com/dotnet/maui/issues/6251

**Comment by jamesmontemagno** [comment] 2022-04-20 20:34
@PureWeen  i have foudn it to be on the Page Background, you can experience this in the default templates. if you add it to the main content item it will work

**Closed** 2022-04-22 21:21 UTC
Labels: t/bug, area/Xaml </>, s/verified
