### ISSUE TITLE
Using FlyoutPage with NavigationPage not working on dotnet 8

### ISSUE THREAD

**Issue by filipemelo** [dotnet/maui#19243] opened 2023-12-06 07:04 UTC
### Description

Using combo with FlyoutPage and NavigationPage is not changing the title.

### Steps to Reproduce

This is happening on dotnet 8.0.0.3
1. I have the error happening on this project. ([link](https://github.com/filipemelo/MauiStudy/tree/master/AppFlyoutPage))
2. Create a FlyoutPage, add an NavigationPage inside and control the detail using C# button. ([link](https://github.com/filipemelo/MauiStudy/blob/master/AppFlyoutPage/FlyoutPageMenu.xaml.cs))
3. On button click handler try to point Detail to a new NavigationPage. 
4. ((FlyoutPage)App.Current.MainPage).Detail = new NavigationPage(new Page2()); ([link](https://github.com/filipemelo/MauiStudy/blob/master/AppFlyoutPage/Menu.xaml.cs))
5. When you run the project on Android and click to the button Page 2 or Page 3, you notice the title is not changed.
![image](https://github.com/dotnet/maui/assets/4982040/b498fe54-b1e1-4a0c-8fcc-ee79cd7e340b)

### Link to public reproduction project repository

https://github.com/filipemelo/MauiStudy/tree/master/AppFlyoutPage

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android S22

### Did you find any workaround?

I tried several, but I was able to do it.
The only thing that changed the tile was using a Navigation.PushAsync(), but I don't want this behavior, because I want to change to point to a new NavigationPage with a new Page inside.

**Comment by Brosten** [comment] 2023-12-06 08:29
I'm suffering from the same issue. The complete navigationbar seems unchanged

**Comment by SmartmanApps** [comment] 2023-12-06 09:44
This is a duplicate issue - not sure what the number was. There's already a fix awaiting GA. The issue is/was with NavigationPage titles, not Flyout menu.

**Comment by SmartmanApps** [comment] 2023-12-06 09:46
Here it is https://github.com/dotnet/maui/issues/18902#issuecomment-1831704181

**Comment by mattleibow** [comment] 2023-12-06 19:24
We think this was fixed in the upcoming SR1, and you can verify this by using the nightly builds: https://github.com/dotnet/maui/wiki/Nightly-Builds

Please try it out and let us know.

**Comment by mattleibow** [comment] 2023-12-06 19:25
Duplicate of https://github.com/dotnet/maui/issues/18050

**Closed** 2023-12-07 03:01 UTC
Labels: t/bug, platform/android 🤖, s/needs-info
