### ISSUE TITLE
On Windows (WinUI) Minimize, Normal, Maximize buttons behave strangely

### ISSUE THREAD

**Issue by uSafi** [dotnet/maui#7751] opened 2022-06-04 06:29 UTC
### Description

On Windows (WinUI) Minimize, Normal, and Maximize buttons show as usual on the top-right corner, 
but they react only when the mouse goes to the counterpart, the top-left corner.
Same strange behavior on MAUI Blazor apps.
I'm at Visual Studio Community 2022 (64-bit) - Preview Version 17.3.0 Preview 1.1 previous preview versions behaved the same awkward way,
Note: this machine had some previase expermantal workloads of MAUI from before RC,
the same apps work fine as expected on another machine.

### Steps to Reproduce

Nothing in particular, any MAUI project template will behave the same awkward on just this one machine, but not on other machines.

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 11 SDK (10.0.22000.0)

### Did you find any workaround?

I've looked for a way to clear whatever MAUI workload I've installed before RC, but so far no luck.

### Relevant log output

```shell
-- Installed Products --
Microsoft Visual Studio Community 2022
Version 17.3.0 Preview 1.1
VisualStudio.17.Preview/17.3.0-pre.1.1+32519.111
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Community

ASP.NET and Web Tools 2019   17.3.122.33185
ASP.NET and Web Tools 2019

Azure App Service Tools v3.0.0   17.3.122.33185
Azure App Service Tools v3.0.0

C# Tools   4.3.0-1.22254.1+9919d7e7bd753404a5d2328e5e3fb2de635169f3
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

CreateLayoutWizard   1.0
Create layout wizard.

DevExpress Reporting Extension   1.4
A Visual Studio extension that invokes the Report Designer editor for report definition VSREPX files.

DevExpress.DeploymentTool   1.0
A useful tool for deploying DevExpress assemblies.

DevExpress.Win.LayoutAssistant Extension   1.0
DevExpress.Win.LayoutAssistant Visual Studio Extension Detailed Info

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Mono Debugging for Visual Studio   17.3.11 (4f73250)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   6.3.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Razor (ASP.NET Core)   17.0.0.2222701+751db1ebea5e6a9ecc7fa57fe447180422afa610
Provides languages services for ASP.NET Core Razor.

StylerPackage Extension   1.0
StylerPackage Visual Stuido Extension Detailed Info

TypeScript Tools   17.0.10420.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.3.0-1.22254.1+9919d7e7bd753404a5d2328e5e3fb2de635169f3
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.1.0-beta.22178.3+6da0245a7ce4bb8483b8d1f2993c8ecaea967ad9
Microsoft Visual F# Tools

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

VSPackage Extension   1.0
VSPackage Visual Studio Extension Detailed Info

Xamarin   17.3.0.151 (d17-3-p1.1@5a59bfa)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   17.3.0.33 (remotes/origin/d17-3-1@9c0d11a29)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin.Android SDK   12.3.99.58 (main/64b22fc)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: adf1bc4
    Java.Interop: xamarin/java.interop/release/6.0.3xx@2a882d2d
    ProGuard: Guardsquare/proguard/v7.0.1@912d149
    SQLite: xamarin/sqlite/3.38.2@7b1e016
    Xamarin.Android Tools: xamarin/xamarin-android-tools/main@fc3c2ac
```
Video:
https://user-images.githubusercontent.com/43465134/172440198-e29e264c-edf7-4da3-8469-9a558c35bfce.mp4

**Comment by deepx** [comment] 2022-06-05 10:54
Can't verifiy with actual Windows 11 and actual Workload. Maybe you can do a small Video or Screenshot?

**Comment by uSafi** [comment] 2022-06-07 17:10
> Can't verifiy with actual Windows 11 and actual Workload. Maybe you can do a small Video or Screenshot?

Edited: I now attached a video you can see
showing 2 apps running, one MAUI, the other is MAUI Blazor.
OS Name: Microsoft windows 10 pro
Version: 10.0.19044 Build 19044

**Comment by jfversluis** [comment] 2022-06-10 13:13
Is this just a File > New Project? Could you maybe placec the code on GitHub so we can see?

Also 

> Note: this machine had some previase expermantal workloads of MAUI from before RC,
the same apps work fine as expected on another machine.

This means this only happens on this particular machine? Do you maybe have some different DPI or other display settings on this machine that is other than the other machine?

If we can't reproduce this or have any actionable information this will be hard to diagnose.

**Comment by uSafi** [comment] 2022-06-11 15:25
> Is this just a File > New Project? Could you maybe placec the code on GitHub so we can see?
> 
> Also
> 
> > Note: this machine had some previase expermantal workloads of MAUI from before RC,
> > the same apps work fine as expected on another machine.
> 
> This means this only happens on this particular machine? Do you maybe have some different DPI or other display settings on this machine that is other than the other machine?
> 
> If we can't reproduce this or have any actionable information this will be hard to diagnose.

As shown in the Video I Attached down here.
Monitor DPI: 96 x 96 
Resolution: 1920 x 1080 
WorkingArea: {X=0,Y=0,Width=1920,Height=1040} 

https://user-images.githubusercontent.com/43465134/173193691-9f4b7fed-29b8-4d1c-a271-c83ce5b1c278.mp4

The video shows WinForms, WPF, WinUI, all behave normally as intended, then an app for Maui, and Maui Blazor both behave the same strange way.

Before the version of MAUI that comes with Visual studio preview, I installed this bad experience called (maui-check),
and I also Installed (Project Reunion v5 and above) to test WinUI.

Absolutely no new code to share on Github,
The code is the same project template scaffold that comes with MAUI,
if I took it and run it on my laptop it'll work just fine.
I like MAUI and I'm as puzzled as you guys and ready for any suggestions to figure this out and solve it So it doesn't happen to others on production.

**Comment by deepx** [comment] 2022-06-11 17:24
can you show what cmd say: "dotnet workload list"

**Comment by uSafi** [comment] 2022-06-11 18:01
> can you show what cmd say: "dotnet workload list"

Installed Workload Ids      Installation Source
-----------------------------------------------
android                     VS 17.3.32519.111
maui-windows                VS 17.3.32519.111
maui-maccatalyst            VS 17.3.32519.111
maccatalyst                 VS 17.3.32519.111
maui-ios                    VS 17.3.32519.111
ios                         VS 17.3.32519.111
maui-android                VS 17.3.32519.111

**Comment by hartez** [comment] 2022-06-13 17:37
@uSafi What are the language/region settings on that machine? I wonder if we've got an RTL bug.

**Comment by uSafi** [comment] 2022-06-15 18:06
> @uSafi What are the language/region settings on that machine? I wonder if we've got an RTL bug.

Good thinking, it's as you thought an RTL Bug, thank you.

Note: I'll leave this issue open until a member of MAUI team notices and address this RTL bug.

https://user-images.githubusercontent.com/43465134/173894989-c8ec8cb7-c34b-4cc6-937b-e19480dbec3b.mp4

**Comment by uSafi** [comment] 2022-06-15 18:16
Closed: waiting for a member of MAUI team to notice and address this bug.

**Comment by uSafi** [comment] 2022-06-15 18:17
Closed: waiting for a member of MAUI team to notice and address this bug.

**Comment by uSafi** [comment] 2022-06-15 18:23
It's Done.
Waiting for a member of MAUI team to notice and address this as an RTL bug.

**Comment by uSafi** [comment] 2023-01-25 09:03
This issue returned again, this time setting language/region have no effect. 
I'm on this versions

![Screenshot 2023-01-25 120113](https://user-images.githubusercontent.com/43465134/214521471-f4177f58-20b1-4ef1-9253-f73c9498f700.png)

**Comment by uSafi** [comment] 2023-02-04 07:23
Good news, it seems they fix it and it's working.
MAUI v7.0.59 Service Release 3
On Visual Studio 2022 version 17.5 Preview 5.
I hope it stays fixed.

**Comment by hartez** [comment] 2023-02-08 23:19
@uSafi In that case, I'm going to close this for now. Let us know if this happens again.

**Comment by asafgo** [comment] 2023-02-21 19:11
This bug is still here as I have just created a new File -> new -> project... .NET MAUI App.
My workloads
![maui](https://user-images.githubusercontent.com/12719112/220436897-f565deb9-bf62-4745-8743-014067b711e8.png)

my windows 11 region
![region](https://user-images.githubusercontent.com/12719112/220437130-0aa89ded-0986-4d71-9089-1aa072d28143.png)

**Comment by Eilon** [comment] 2023-02-21 20:10
Re-opening because apparently this is still happening.

@asafgo can you confirm that you're seeing the exact same behavior as @uSafi originally reported, where the "min/max/close" buttons are behaving as though they are mirrored right-to-left? It seems your machine is also using a right-to-left language (Hebrew), as was @uSafi (Arabic), so maybe there's more to this issue...

**Comment by asafgo** [comment] 2023-02-22 09:45
I can confirm that the problem on my PC is the same as @uSafi.

The only workaround for now is using a Windows specific code from this issue https://github.com/dotnet/maui/discussions/8228
at MauiProgram.cs

```
#if WINDOWS
        
        builder.ConfigureLifecycleEvents(events =>
        {
            events.AddWindows(wndLifeCycleBuilder =>
            {
                wndLifeCycleBuilder.OnWindowCreated(window =>
                {

                    IntPtr nativeWindowHandle = WinRT.Interop.WindowNative.GetWindowHandle(window);
                    WindowId win32WindowsId = Win32Interop.GetWindowIdFromWindow(nativeWindowHandle);
                    AppWindow winuiAppWindow = AppWindow.GetFromWindowId(win32WindowsId);

                    window.ExtendsContentIntoTitleBar = false; // must be false or else you see some of the buttons
                    winuiAppWindow.SetPresenter(AppWindowPresenterKind.Default);

                });
            });
        });
#endif

        return builder.Build();
```

**Closed** 2023-05-02 17:58 UTC
Labels: t/bug, platform/windows 🪟, area/desktop 🖥️

**Comment by asafgo** [comment] 2023-05-24 18:45
https://github.com/dotnet/maui/assets/12719112/4f9713c3-860b-46c4-8238-ac6daf58131d

This bug is still here with version 7.0.86 Service Release 6.
