### ISSUE TITLE
.NET MAUI Issue with coding Xamarin form <Grid> Type

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#12649] opened 2023-01-13 18:59 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/NET-MAUI-Issue-with-coding-Xamarin-form/10242430)._

---
[severity:It's more difficult to complete my work]
I have a Xamarin Content page that contains a . I have created the following code in two separate Solutions - 1) Mobile App (Xamarin Forms) and 2) .NET MAUI App. When this code is compiled in Solution 1, the compile is clean and executes flawlessly. When the same code is compiled in Solution 2, the compile fails with CS1501	No overload for method 'Add' takes 3 arguments...

I have added the code below for review and duplication. Please advise as to why Solution 2) .NET MAUI App fails.

The reference to GridCol is the x:Name of the Grid ----- 

private void Button_Clicked(object sender, EventArgs e)
        {
            GridCol.RowDefinitions.Add(new RowDefinition());
            GridCol.RowDefinitions.Add(new RowDefinition());
            GridCol.RowDefinitions.Add(new RowDefinition());
            GridCol.ColumnDefinitions.Add(new ColumnDefinition());
            GridCol.ColumnDefinitions.Add(new ColumnDefinition());

            for (int rowIndex = 0; rowIndex < 3; rowIndex++)
            {
                for (int columnIndex = 0; columnIndex < 2; columnIndex++)
                {

                    var label = new Label
                    {
                        Text = "Hello",
                        VerticalOptions = LayoutOptions.Center,
                        HorizontalOptions = LayoutOptions.Center
                    };
                    **GridCol.Children.Add(label, columnIndex, rowIndex);**  ====>this line fails
                }
            }
        }

---
#### Feedback Bot on 1/2/2023, 06:17 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by hartez** [comment] 2023-01-13 20:07
Duplicate of #780.

Those overloads of Grid.Add() don't exist yet in MAUI.

**Comment by mattleibow** [comment] 2023-01-16 18:48
Duplicate of https://github.com/dotnet/maui/issues/780

**Closed** 2023-01-16 18:49 UTC
Labels: t/bug, s/duplicate 2️⃣, area/layout 🔲
