### ISSUE TITLE
The ResourceDictionary has duplicate template options

### ISSUE THREAD

**Issue by ZackYangyang** [dotnet/maui#10202] opened 2022-09-19 10:19 UTC
### Description

The Resource Dictionary has duplicate template options, the issue occurs when there is both .net6 and .net7.
Maui version: 7.0.100-rc.1.22431.12
![image](https://user-images.githubusercontent.com/82210619/190987420-91a412ba-d1b0-4962-9ce7-9bc291046411.png)

### Steps to Reproduce

1. Create a Maui or Maui Blazor app
2. Right click project file - Add - New File
3. Observe the Item window

### Link to public reproduction project repository

https://github.com/ZackYangyang/maui.git

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

I was *not* able test on other platforms

### Affected platform versions

17.4 preview build 1987

**Comment by mrward** [comment] 2022-09-19 10:24
The problem is the resource dictionary item template's template.json file does not specify a group id.

https://github.com/dotnet/maui/blob/main/src/Templates/src/templates/maui-resourcedictionary-xaml/.template.config/template.json

The other item templates do have a group id so VS Mac can combine them:

https://github.com/dotnet/maui/blob/3595cb1eccc96e0e7b7eed754957dd1afcf717d5/src/Templates/src/templates/maui-contentpage-xaml/.template.config/template.json#L6

**Comment by mattleibow** [comment] 2022-10-04 22:45
Does this group id also need to exist in net 6 templates?

**Comment by mrward** [comment] 2022-10-05 08:20
Yes I think it needs to be in the net6 templates otherwise with both installed you would get duplicate items in the New File dialog.

**Comment by Redth** [comment] 2022-10-12 15:14
This is merged into net6.0 branch and will be picked up in the next 6.0 servicing release + 7.0 GA

**Closed by Redth** 2022-10-12 15:14 UTC
Labels: t/bug, area/templates 📄
