### ISSUE TITLE
Maui custom namespace not working when in current project

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#20326] opened 2024-02-02 19:11 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Maui-custom-namespace-not-working-when-i/10546507)._

---
Trying to use a custom namespace for custom controls that are part of the maui app does not work.
It results in the compiler error: 
XFC0000	Cannot resolve type "http://schemas.mauicustomnamespace.com/test:test:CustomControl1".

Using a custom namespace from a library project does work.

Another problem report (XAML Schemas Namespace Customization Not Supported Without 'x:Name' Declaration [#16466]() ) states that adding the x:Name to the control solves the problem. But if I do that, this error is thrown for the control, page, shell and app: CS0103 The name 'InitializeComponent' does not exist in the current context.

I have tried with and without a prefix definition.
I have tried setting the definition in a class in the base folder of the app.
I have tried setting the definition in a class in the same folder as the control.

[MauiCustomNamespace.zip](https://aka.ms/dc/file?name=Bfd9e5d0ab91e4cfd95e033bf786932dd638387691807518178_MauiCustomNamespace.zip&tid=fd9e5d0ab91e4cfd95e033bf786932dd638387691807518178)

---
#### Feedback Bot on 12/21/2023, 06:13 PM: 

(private comment, text removed)
#### saskia on 12/22/2023, 02:54 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by XamlTest** [comment] 2024-03-13 09:09
Verified this on VS 17.10.0 Preview 2.0(8.0.7). 
[MauiCustomNamespace.zip](https://github.com/dotnet/maui/files/14585156/MauiCustomNamespace.zip)

![image](https://github.com/dotnet/maui/assets/97647558/51f71694-5a6b-44c8-a22c-597f66a0aee4)

**Comment by jfversluis** [comment] 2024-03-30 17:46
Duplicate of #9781

**Closed by jfversluis** 2024-03-30 17:46 UTC
Labels: t/bug, area/tooling ⚙️, s/verified, s/triaged
