### ISSUE TITLE
[XC] DataType Not Inherited By MultiBinding

### ISSUE THREAD

**Issue by david-maw** [dotnet/maui#25306] opened 2024-10-16 04:34 UTC
### Description

A piece of XAML like this:

```XAML
            <Label Text="{Binding Text}">
                <Label.IsVisible>
                    <MultiBinding Converter="{StaticResource All}" ConverterParameter="{Binding Text}">
                        <Binding Path="TrueBool"/>
                    </MultiBinding>
                </Label.IsVisible>
            </Label>
```
Will generate several warnings when built:

```
PS C:\...> dotnet build -f:net9.0-windows10.0.19041.0
...
  ItemSelfRef net9.0-windows10.0.19041.0 succeeded with 3 warning(s) (1.6s) ...temSelfRef.dll
    C:\...\MainPage.xaml(12,14): XamlC warning XC0103: Consider attributing the markup extension "CommunityToolkit.Maui.Converters.VariableMultiValueConverter" with [RequireService] or [AcceptEmptyServiceProvider] if it doesn't require any.
    C:\...\MainPage.xaml(21,68): XamlC warning XC0022: Binding could be compiled to improve runtime performance if x:DataType is specified. See https://learn.microsoft.com/dotnet/maui/fundamentals/data-binding/compiled-bindings for more information.
    C:\...\MainPage.xaml(22,26): XamlC warning XC0022: Binding could be compiled to improve runtime performance if x:DataType is specified. See https://learn.microsoft.com/dotnet/maui/fundamentals/data-binding/compiled-bindings for more information.
```
I assume there's nothing I can do about the first one (XC0103), it's a request to add an attribute to some code I do not control.

It's the other two (XC0022), the inhertance seems to stop at the Label, the MultiBinding and each individual Binding seem to require their own explicit setting of DataType rather than inheriting it from the Label they are attached or anywhere else in the visual tree.

### Steps to Reproduce

1 Clone the repository and build the app
2 observe the warnings

### Link to public reproduction project repository

https://github.com/david-maw/ItemSelfRef.git

### Version with bug

9.0.0-rc.2.24503.2

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Affected platforms

I was *not* able test on other platforms

### Did you find any workaround?

Put an explicit DataType wherever there's a Binding or MultiBinding.

**Comment by jaosnz-rep** [comment] 2024-10-16 07:49
I can repro this issue at Windows platform on the latest 17.12.0 Preview 2.1(9.0.0-rc.2.24503.2 & 9.0.0-rc.1.24453.9).

**Comment by StephaneDelcroix** [comment] 2024-10-16 10:02
duplicate of #25141

**Closed by StephaneDelcroix** 2024-10-16 10:02 UTC
Labels: t/bug, area-xaml, s/verified, s/triaged
