### ISSUE TITLE
Custom CollectionView footer disappears when adding items

### ISSUE THREAD

**Issue by hannesschulze** [dotnet/maui#8761] opened 2022-07-15 14:13 UTC
### Description

When items are added to a collection view using a custom view as its footer, the footer sometimes disappears. When more items are added, it reappears.

I was able to reproduce this bug on Android (emulator), not on Windows. Other platforms were not tested.

https://user-images.githubusercontent.com/43932053/179233794-5a32b62e-0858-429a-80a7-d26b8019ce8b.mp4

### Steps to Reproduce

1. Clone https://github.com/hannesschulze/MauiCollectionViewFooterBug
2. Launch the app on Android
3. Click the "Add Item" button

**Expected behavior:** The footer remains visible when new items are added
**Actual behavior:** The footer sometimes disappears

### Version with bug

6.0.408 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 12

**Comment by tranb3r** [comment] 2023-02-15 10:03
I'm also having this issue.
Is this going to be fixed? Any workaround?

**Comment by Zhanglirong-Winnie** [comment] 2023-05-17 03:29
Verified this issue with Visual Studio Enterprise 17.6.0 Preview 7.0. Repro on android platform with project.
[MauiCollectionViewFooterBug-main.zip](https://github.com/dotnet/maui/files/11493906/MauiCollectionViewFooterBug-main.zip)
![Android](https://github.com/dotnet/maui/assets/77434865/590f1c24-941c-4eac-bab9-669c24b6b196)

**Comment by MegaEgorik** [comment] 2023-07-26 16:39
To fix this problem, you need to add this code after adding a new item:
```C#
(collection.Footer, collection.Footer) = (null, collection.Footer);
```
or
```C#
object footer = collection.Footer;
collection.Footer = null;
collection.Footer = footer;

**Comment by tranb3r** [comment] 2024-02-20 19:58
Is this going to be fixed?

**Comment by tranb3r** [comment] 2024-04-26 07:23
The workaround now seems to cause an undesired scrolling of the collectionview.

**Comment by gchapeaux** [comment] 2024-05-09 14:42
As mentionned in #20666 , the footer only disappears when the collectionview happens to have an even number of items, I was able to reproduce it as well on Visual Studio Community 2022 - 17.9.5

**Comment by nshtinkov** [comment] 2024-05-29 17:26
I have the same issue with MAUI 8.0.40 and VS 17.10.0. It seems that #20666 is a duplicate.
It is quite unfortunate that almost for two years this remains not fixed.

**Comment by PureWeen** [comment] 2024-06-06 16:23
Duplicate of #20666

**Closed by PureWeen** 2024-06-06 16:23 UTC
Labels: t/bug, platform/android 🤖, p/2, area-controls-collectionview, s/verified, s/triaged
