### ISSUE TITLE
CollectionView on Android, SelectionChangedCommand does not get called

### ISSUE THREAD

**Issue by davefxy** [dotnet/maui#7035] opened 2022-05-11 16:44 UTC
### Description

CollectionView on Android, SelectionChangedCommand does not get called when  a Frame is used in the ItemTemplate. This works fine on Windows.

### Steps to Reproduce

Run the uploaded app on an Android device. On the initial screen, select the "Get Monkeys" button. This will populate the display. Then select any entry. Nothing happens. the app should route the request to another screen display details about the entry. Try app on Windows to see how it is supposed to work.
I took the Finished version of the Dotnet Maui Workshop app and edited it to use CollectionView SelectionChangedCommand.
[Finish.zip](https://github.com/dotnet/maui/files/8671883/Finish.zip)

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 12

### Did you find any workaround?

Yes, don't use a Frame.

**Comment by jfversluis** [comment] 2022-05-12 08:53
Duplicate of #6075

**Comment by jfversluis** [comment] 2022-05-12 08:53
This seems fixed for GA, please let us know if that's not the case when that is released :)

**Closed by jfversluis** 2022-05-12 08:53 UTC
Labels: t/bug, area/collectionview 📃, s/needs-verification
