### ISSUE TITLE
Page switching is slow, especially when the page has many controls

### ISSUE THREAD

**Issue by quan0zhou** [dotnet/maui#1534] opened 2021-07-03 01:25 UTC
Can the page switch be made more silky smooth, especially in the case of many controls in the page, asynchronous loading controls it

**Comment by jfversluis** [comment] 2021-10-05 18:12
Hey @quan0zhou thanks for being an early adopter! There is still a lot of development going on and performance is definitely top of mind. I would like to ask you to keep testing for sure, but maybe hold off on reporting performance issues like these until we are closer to releasing.

Additionally, this issue doesn't give us much detail. It would really help track down the cause of issues if you could include version information on the bits that you are using as well as a reproducible sample of the thing that you are seeing. At the very least: how many controls are we talking about? What kind of controls? Are you executing any other code while switching pages?

Closing this one for now, but if you still run into issues in a couple of months, please feel free to open something new with the bug report template.

Thanks!

**Closed by jfversluis** 2021-10-05 18:12 UTC
