### ISSUE TITLE
MapHandler not found exception (iOS)

### ISSUE THREAD

**Issue by faheys** [dotnet/maui#12203] opened 2022-12-18 23:12 UTC
### Description

When using the built in map feature in a fresh project the application crashes upon launch of the page containing the map control with the following error:
`"**Microsoft.Maui.Platform.HandlerNotFoundException:** 'Handler not found for view Microsoft.Maui.Controls.Maps.Map.'`

<img width="569" alt="maui_map_error" src="https://user-images.githubusercontent.com/28056243/208323510-9b9c323b-3175-4e41-9964-3c5edfac3038.png">

I can only reproduce this issue when running the application on iOS devices while using the latest version of the "**Microsoft.Maui.Controls.Maps**" NuGet package (**7.0.52**). The issue does not occur when using version **7.0.49** of the package. The crash occurs on all iPhone simulators.

**Dev Environment:**
Visual Studio Community 2022 (64-bit) (Windows)
Version 17.4.1

**Runtime:**
.NET 7.0.0 (64-bit)

### Steps to Reproduce

1. Create a new MAUI app with .NET 7
2. Add NuGet package Microsoft.Maui.Controls.Maps with version 7.0.52
3. Add UseMauiMaps() to the builder in MauiProgram.cs
4. Add Map-Control into MainPage.xaml
5. Run the project on iPhone simulator (iOS 16.1)

### Link to public reproduction project repository

https://github.com/faheys/MauiMapsTest

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 16.1

### Did you find any workaround?

Install version **7.0.49** of NuGet package "Microsoft.Maui.Controls.Maps" instead of latest version (7.0.52)

### Relevant log output

```shell
Microsoft.Maui.Platform.HandlerNotFoundException
  Message=Handler not found for view Microsoft.Maui.Controls.Maps.Map.
  Source=Microsoft.Maui
  StackTrace:
   at Microsoft.Maui.Platform.ElementExtensions.ToHandler(IElement view, IMauiContext context)
   at Microsoft.Maui.Platform.ElementExtensions.ToPlatform(IElement view, IMauiContext context)
   at Microsoft.Maui.Handlers.LayoutHandler.SetVirtualView(IView view)
   at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.ILayout, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Platform.LayoutView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].SetVirtualView(IElement view)
   at Microsoft.Maui.Controls.Element.SetHandler(IElementHandler newHandler)
   at Microsoft.Maui.Controls.Element.set_Handler(IElementHandler value)
   at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IElement.set_Handler(IElementHandler value)
   at Microsoft.Maui.Platform.ElementExtensions.ToHandler(IElement view, IMauiContext context)
   at Microsoft.Maui.Platform.ElementExtensions.ToPlatform(IElement view, IMauiContext context)
   at Microsoft.Maui.Handlers.ContentViewHandler.UpdateContent(IContentViewHandler handler)
   at Microsoft.Maui.Handlers.ContentViewHandler.MapContent(IContentViewHandler handler, IContentView page)
   at Microsoft.Maui.PropertyMapper`2.<>c__DisplayClass5_0[[Microsoft.Maui.IContentView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Handlers.IContentViewHandler, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<Add>b__0(IElementHandler h, IElement v)
   at Microsoft.Maui.PropertyMapper.UpdatePropertyCore(String key, IElementHandler viewHandler, IElement virtualView)
   at Microsoft.Maui.PropertyMapper.UpdateProperties(IElementHandler viewHandler, IElement virtualView)
   at Microsoft.Maui.Handlers.ElementHandler.SetVirtualView(IElement view)
   at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.IContentView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Platform.ContentView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].SetVirtualView(IView view)
   at Microsoft.Maui.Handlers.ContentViewHandler.SetVirtualView(IView view)
   at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.IContentView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Platform.ContentView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].SetVirtualView(IElement view)
   at Microsoft.Maui.Controls.Element.SetHandler(IElementHandler newHandler)
   at Microsoft.Maui.Controls.Element.set_Handler(IElementHandler value)
   at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IElement.set_Handler(IElementHandler value)
   at Microsoft.Maui.Platform.ElementExtensions.ToHandler(IElement view, IMauiContext context)
   at Microsoft.Maui.Platform.ViewExtensions.ToHandler(IView view, IMauiContext context)
   at Microsoft.Maui.Controls.Platform.Compatibility.ShellSectionRootRenderer.SetPageRenderer(Page page, ShellContent shellContent)
   at Microsoft.Maui.Controls.Platform.Compatibility.ShellSectionRootRenderer.LoadRenderers()
   at Microsoft.Maui.Controls.Platform.Compatibility.ShellSectionRootRenderer.ViewDidLoad()
   at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName)
   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass)
   at MauiMapsTest.Program.Main(String[] args) in C:\Users\username\source\repos\MauiMapsTest\MauiMapsTest\Platforms\iOS\Program.cs:line 13
```

**Comment by jfversluis** [comment] 2022-12-19 10:09
Duplicate of #12088

**Closed by jfversluis** 2022-12-19 10:09 UTC
Labels: t/bug, platform/iOS 🍎, area/controls 🎮, control-map
