### ISSUE TITLE
MeasureFirstItem makes items disappear on Android

### ISSUE THREAD

**Issue by pekspro** [dotnet/maui#7562] opened 2022-05-28 10:25 UTC
### Description

I have a `CollectionView` where `ItemSizingStrategy` is set to `MeasureFirstItem`. The properties of the times are changed some time of the `CollectionView` is loaded. Somehow, this makes some items become invisible on Android. It works fine on Windows.

Originally, my list looks like this:

![image](https://user-images.githubusercontent.com/3163293/170821073-64a04e70-b06c-4da0-94c4-00ed4a45f478.png)

Then, the two first items should be changed to green. But the second one just disappears:

![image](https://user-images.githubusercontent.com/3163293/170820997-f1255c26-b29c-4fed-a1d3-ae533632f863.png)

In Windows it's works fine:

![image](https://user-images.githubusercontent.com/3163293/170821189-02a92acd-75da-4383-96b3-27f77ea528a9.png)

It's very strange :-)

### Steps to Reproduce

1. Create a new Maui app.
2. Change `MainPage.xaml` to:

``` XAML
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:v="clr-namespace:MauiIssues"
             x:Class="MauiIssues.MainPage"
             >
    <Grid>
        <CollectionView ItemsSource="{Binding Issues}" ItemSizingStrategy="MeasureFirstItem">
            <CollectionView.ItemTemplate>
                <DataTemplate>
                    <Grid>
                        <Label Text="{Binding Title, Mode=OneWay}"
                            TextColor="Red"
                            IsVisible="{Binding IsRed}"
                                />

                        <Label Text="{Binding Title, Mode=OneWay}"
                            TextColor="Green"
                            IsVisible="{Binding IsGreen}}"
                                />
                    </Grid>
                </DataTemplate>
            </CollectionView.ItemTemplate>
        </CollectionView>
    </Grid>
</ContentPage>
```

3. Change `MainPage.cs` to:

``` C#
using System.Collections.ObjectModel;

namespace MauiIssues;

public partial class MainPage : ContentPage
{
    public MainPage()
    {
        InitializeComponent();

        BindingContext = this;
    }

    public class Issue : BindableObject
    {
        public string Title { get; set; }
        public bool IsRed { get; set; } = true;
        public bool IsGreen => !IsRed;

        public void MakeGreen()
        {
            IsRed = false;
            OnPropertyChanged(nameof(IsGreen));
            OnPropertyChanged(nameof(IsRed));
        }
    }

    public ObservableCollection<Issue> Issues { get; } = new ObservableCollection<Issue>();

    protected async override void OnAppearing()
    {
        base.OnAppearing();

        Issues.Add(new Issue { Title = "Issue 1" });
        Issues.Add(new Issue { Title = "Issue 2" });
        Issues.Add(new Issue { Title = "Issue 3" });

        await Task.Delay(4000);

        Issues[0].MakeGreen();
        Issues[1].MakeGreen();
    }
}
```
Run the project in Android.

Full sample code: https://github.com/pekspro/MauiIssues/tree/7562_MeasureFirstItem_makes_items_disappear

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Windows 10.0.17763.0, Android 11

### Did you find any workaround?

Removing `ItemSizingStrategy="MeasureFirstItem"` solves the problem.

**Comment by kristinx0211** [comment] 2022-05-30 06:46
can be reproduced on android 12 with above project.

**Comment by ToolmakerSteve** [comment] 2022-05-31 03:36
Certain UI changes in OnAppearing have always been unreliable in Xamarin.Forms. Perhaps the improvements for Maui have not helped avoid this "twilight zone".

Here, its those `OnPropertyChanged` calls that can't be relied on to take effect.

It would be great to see this kind of issue fixed.

-------------------------
FWIW (work-around):

The 4 second delay shown there is useless; all that does is suspend maui's processing of the page. If you instead do

    Dispatcher.DispatchDelayed(TimeSpan.FromSeconds(0.5), () =>
    {
        Issues[0].MakeGreen();
        Issues[1].MakeGreen();
    });

I'm sure it will work.

**Comment by pekspro** [comment] 2022-11-11 18:25
I've updated sample application to .NET 7. The same issue remains. I have also tried the work around from @ToolmakerSteve, but it didn't helped.

**Comment by davidverriere** [comment] 2023-02-07 08:01
Same issue here in .Net 7.0
 - collection view with measurefirst item on android
 - no issue except poor performance with measure all items

**Comment by symbiogenesis** [comment] 2023-02-08 05:06
I'm seeing the same on Android, only. Using .NET 7 with the latest workloads.

**Comment by XamlTest** [comment] 2023-05-10 10:07
Verified this on Visual Studio Enterprise 17.6.0 Preview 7.0. Repro on Android 13.0, with below Project:
[7562.zip](https://github.com/dotnet/maui/files/11440611/7562.zip)

Android:
![image](https://github.com/dotnet/maui/assets/97647558/8426b07b-f4c0-44b7-afb6-8e882df8f2e3)

**Comment by thomaskaelin** [comment] 2023-06-07 12:55
I also noticed this issue while migrating an Xamarin.Forms-app to .NET MAUI. Any news on this?

**Comment by Scordo** [comment] 2023-06-12 17:23
I also noticed this :-(

**Comment by jvakos** [comment] 2023-07-19 12:39
Bug remains in dotnet 8.0.0-preview.6.8686.

**Comment by giannisk79** [comment] 2023-07-19 12:56
Please fix this already!

**Comment by OliverDevsCodex** [comment] 2023-08-11 19:07
No fix till this day still...

**Comment by waseem852** [comment] 2023-10-21 10:56
Same exists on Dotnet 8 RC2

**Comment by andrew-barlit** [comment] 2024-01-25 09:24
Still not working with .NET 8 GA. Setting "measure first item" making almost all items except first invisible. And performance with the default setting "measure all items" is terrible. Maybe there's some workaround via custom handlers?

**Comment by Alex-111** [comment] 2024-01-30 21:06
We also would appreciate a fix for this.

For iOS ist working and we see a approvment for scroll performance.
Unfortunately this cannot  be used for Android

**Comment by kyurkchyan** [comment] 2024-02-10 11:50
Spoiled about an hour to understand why on Android we see only the first item from a collection just to bump over this bug.

**Comment by andrew-barlit** [comment] 2024-02-27 19:11
I've had to replace Collection View with Vertical Stack Layout, since List View isn't working properly, too. While with collection view all items except first disappear if we set "measure first item", with list view they disappear randomly while scrolling and we don't even have "measure all" option.
In my case there's about 10-50 items in the list, and 8-10 fits on the screen. Adding items manually from code-behind to stack layout (and doing a reordering for drag and drop) is reinventing the wheel, but this configuration is somehow way faster than collection view. All items are the same height, have height request set...

**Comment by Zerachiel01** [comment] 2024-03-08 22:21
Please fix this. I'm even thinking of leaving MAUI and choosing another framework because of this and the performance loss without it.

**Closed** 2024-03-26 11:35 UTC
Labels: t/bug, platform/android 🤖, p/1, area/collectionview 📃, s/verified, s/triaged, delighter

**Comment by PureWeen** [comment] 2024-03-27 21:19
This should be fixed our nightlies

If anyone can test and let me know your results that would be super!
Can you test with the latest nightly build? 
https://github.com/dotnet/maui/wiki/Nightly-Builds

**Comment by filipleifer** [comment] 2024-04-18 11:14
@PureWeen  No still not working.
