### ISSUE TITLE
[Android] ImageButton CornerRadius has nothing to do with Xamarin.Forms CornerRadius

### ISSUE THREAD

**Issue by RubenBonillaLluch** [dotnet/maui#24939] opened 2024-09-26 09:21 UTC
### Description

I'm migrating my app from Xamarin.Forms to MAUI and I found out that the CornerRadius property is very differnt from the one in Xamarin.Forms.

I have this control:
`<ImageButton WidthRequest="150" HeightRequest="150" CornerRadius="75" Source="{Binding UserPhoto}" Aspect="AspectFill" HorizontalOptions="Center" Style="{StaticResource ImageButton}" />`
![Screenshot_20240926_104651](https://github.com/user-attachments/assets/72224965-c5b3-4e60-aecd-900f8c2cb9f7)

The exact same code in Maui looks like this:
![Screenshot_20240926_111650_AppMasatsAndroid](https://github.com/user-attachments/assets/6047327f-2312-43e8-8336-b8ea0f9435d1)

Migrating my app I'm finding a lot of things like this, I don't want to be mean, but almost everything in Maui feels like a donwgrade from its predecessor.

### Version with bug

9.0.0-rc.1.24453.9

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

I was *not* able test on other platforms

### Did you find any workaround?

Using clip or creating a custom control does the job.

**Comment by jfversluis** [comment] 2024-09-26 17:56
Duplicate of #23854

**Comment by jfversluis** [comment] 2024-09-26 17:57
In the linked issue a workaround is mentioned for the time being with using a `Border`

**Closed by jfversluis** 2024-09-26 17:56 UTC
Labels: t/bug, area-controls-button, migration-compatibility
