### ISSUE TITLE
[Bug] Scollview scrolled event not triggered

### ISSUE THREAD

**Issue by Sasikumar3595** [dotnet/maui#2181] opened 2021-08-20 12:04 UTC
### Description

I was created the custom layout holds the two scroll views and synchronous the both scrollviews horizontal scroll by detect the scroll changed. Scroll view have scrolled event but it was not triggered while scrolling. Guide us to archive the requirement

### Steps to Reproduce

1. Create the custom layout with scroll view
2. Trigger scroll view scrolled event
3. scrolled event not trigged while scroll view scrolling

### Expected Behavior

- Scroll view triggers the scrolled event while scrolling

### Actual Behavior

- Scroll view does not triggers the scrolled event while scrolling

**Comment by vanka78bg** [comment] 2021-11-26 08:42
This is affecting us as well. My current workaround is to subscribe to the `PropertyChanged` event and observe the `ScrollX` and `ScrollY` properties. This is suboptimal however, as the `PropertyChanged` event is fired for every single property of the control.

**Comment by rctec-at** [comment] 2022-02-10 09:27
Is this problem already in the works or is there any way we can help fix this?

**Comment by kristinx0211** [comment] 2022-03-08 07:05
Duplicate of #3655

**Comment by rctec-at** [comment] 2022-03-08 07:27
@kristinx0211  where is this a duplicate? 
the scrollview in this case does scroll, but the "Scrolled" event is not raised and the ScrollX/Y property doesnt change.

The issue you mentioned that the scrollview does not scroll.

Looks like 2 different problems to me or am i wrong?

**Comment by kristinx0211** [comment] 2022-03-10 10:17
@rctec-at ah, you mean can scroll but the event is not triggered. thanks for the update.

**Comment by rctec-at** [comment] 2022-03-10 11:31
@kristinx0211 the event and also the Property is not updated.
sadly i am not familliar enough to tackle this problem myself (gave it a look last weekend)

**Comment by VincentBu** [comment] 2022-03-11 02:06
Hi @rctec-at , where do you run into this issue? Windows or Android/IOS? The scrolled event can be triggered on Android emulator. However, on Windows, it fails.

**Comment by kristinx0211** [comment] 2022-03-11 02:47
@rctec-at I made a project to repro this issue, Unfortunately the scrollview  doesn't  scroll and the scroll event is not triggered on windows, android and IOS, repro sample:
[MauiApp1.zip](https://github.com/dotnet/maui/files/8228578/MauiApp1.zip)

**Comment by rctec-at** [comment] 2022-03-11 05:44
@VincentBu i ran into this in Preview 12 (13 not confirmed yet, since my comany shifted my priorities for a while) on Android Device and Windows.

@kristinx0211 i try to make a repo this weekend in my private time, due to the reasons above.

**Comment by rctec-at** [comment] 2022-03-28 06:02
Sorry, a quick information: Due to Covid and a lack of power i am at the moment unable to provide a repo.

**Comment by Redth** [comment] 2022-03-31 18:24
This is fixed in the upcoming RC1 release:

![2022-03-31_14-23-35](https://user-images.githubusercontent.com/271950/161124154-dc03ad28-cbd1-438d-a34e-91ffe478e252.gif)

**Closed by Redth** 2022-03-31 18:24 UTC
Labels: t/bug, area/layout 🔲, s/verified, s/triaged

**Comment by rctec-at** [comment] 2022-04-01 04:13
@Redth could you link (send) me the commit? i want to learn from so i maybe can later contribute myself.

**Comment by Sasikumar3595** [comment] 2022-04-01 05:01
@Redth ,

Is scrolled event working correctly on the horizontal scroll view? because the issue was raised for us on horizontal scroll view.
