### ISSUE TITLE
AppIcon shows a border on windows taskbar

### ISSUE THREAD

**Issue by PaulAndersonS** [dotnet/maui#5162] opened 2022-03-09 10:50 UTC
### Description

Adding a custom image as appicon not shown correctly in Windows taskbar. A Blue border or padding gets applied.

[MauiApp4.zip](https://github.com/dotnet/maui/files/8213941/MauiApp4.zip)

Issue screenshot:

![icon](https://user-images.githubusercontent.com/42271912/157427037-11ea4201-2fe8-493b-9633-593fbe140ee0.PNG)

### Steps to Reproduce

1. Create a MAUI project.
2. Add a image named as appicon.png and set as MauiIcon.

Run the app in windows.

### Version with bug

Preview 13 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 19041

### Did you find any workaround?

No

**Comment by emorell96** [comment] 2022-04-08 19:10
I saw this when I packaged the app. It seems like there's a hard coded .NET image which goes under the icon set through `<MauiIcon>`
![image](https://user-images.githubusercontent.com/20151415/162508782-0e589617-7dcd-4d20-bc8f-ea100b546217.png)

**Comment by designtechemanuel** [comment] 2022-07-04 17:22
I'm also having this issue. It doesn't matter whatever I change the icon to, the blue border remains as long as there is an icon at all.

**Comment by DRAirey1** [comment] 2022-09-02 17:19
You can't possibly expect us to release a product to customers when the icon looks like that. It screams that this product is unstable. Why bother with the rest of your backlog when we can't give this Maui stuff to our customers?

**Comment by Jarek300** [comment] 2022-09-11 14:41
Agreed. The more I try to use maui, the more it seems not ready for production. 

New maui/blazor project, default icon. Application icon on taskbar has ugly gray border.

![image](https://user-images.githubusercontent.com/10242002/189533558-152af636-9d2b-4dca-a59e-9fc9ad2d80cb.png)

**Comment by DiagProf** [comment] 2022-09-16 17:06
Customers usually have no idea about software. But when it comes to style, everyone thinks they can have a say. That's why it's important that it fits so that you don't have to deal with such marginal discussions.

**Comment by SimonORorke** [comment] 2022-09-20 08:45
I have the same problem.  For me the icon's border on the taskbar is brown.  This applies not only to the icon I supplied to my application but also to the the default icon in the default application.
![Maui Taskbase Icon](https://user-images.githubusercontent.com/79874679/191211412-9f31aa8f-e0ad-4800-ba3a-64fa696eb27e.png)

**Comment by DavidTynewyddBI** [comment] 2022-09-21 10:53
> I have the same problem. For me the icon's border on the taskbar is brown. This applies not only to the icon I supplied to my application but also to the the default icon in the default application. ![Maui Taskbase Icon](https://user-images.githubusercontent.com/79874679/191211412-9f31aa8f-e0ad-4800-ba3a-64fa696eb27e.png)

It looks like it is using the user's accent color, presumably why yours is brown and it will be different for each user - not amazing functionality...

**Comment by angelru** [comment] 2022-09-29 08:17
any solution?

**Comment by mattleibow** [comment] 2022-10-06 07:42
I finally figured it out! There is new app icon types. It used to be one set that was everywhere, and then more were added so the generated ones now only work properly for the start menu.

There is a new set for the general windows shell. I'll fix this ASAP.

**Comment by mattleibow** [comment] 2022-10-06 08:00
Duplicate of #6164

**Closed by mattleibow** 2022-10-06 08:00 UTC
Labels: t/bug, area/single project ☝️, platform/windows 🪟, p/1, area/desktop 🖥️, s/verified

**Comment by mattleibow** [comment] 2022-10-06 13:52
Fixed in https://github.com/dotnet/maui/pull/10515

**Comment by manuelesvi** [comment] 2022-10-27 01:59
Same issue here. 

![image](https://user-images.githubusercontent.com/106558272/198172980-35ab1a47-36f2-4db0-b10b-22e7e11ee3db.png)

MAUI version is 6.0.541
.NET SDK version is 6.0.400
Visual Studio version is 17.3.32922.545
