### ISSUE TITLE
[Android] Border not clipping correctly content Image w/ Margin & custom Clip

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#17571] opened 2023-09-22 11:32 UTC
### Description

The Border on Android is not clipping correctly content Image.
![image](https://github.com/dotnet/maui/assets/6755973/a9dfb0ef-50b1-4d27-af19-3056b7f4af11)

### Steps to Reproduce

1. Download or sync https://github.com/jsuarezruiz/netmaui-surfing-app-challenge
2. Launch the App on Android

### Link to public reproduction project repository

https://github.com/jsuarezruiz/netmaui-surfing-app-challenge

### Version with bug

8.0.0-rc.1.9171

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

Android

**Comment by jstedfast** [comment] 2023-09-22 18:00
There are 2 problems:

1. The Image has a Margin of 1, this pushes the image down and to the right.
2. The Image has a custom Ellipse Clip which seems to miscalculate the center (and maybe the radius as well)

Currently, the Clip is an Ellipse w/ Center="25, 25" and each radius=25, but if I change them all to 24 and remove the Margin, then it renders correctly.

Alternatively, if I comment out the custom Clip and remove the Margin, it also works.

**Comment by jstedfast** [comment] 2023-09-27 18:50
LayoutExtensions.ComputeDesiredSize() returns a size of `{ 0, 0 }` + margin width & margin height for Paths which means that the effective size of the Path stroke is 0x0px, hence why nothing is drawn.

**Comment by jstedfast** [comment] 2023-09-28 19:33
The Play button is also affected by the Marin value. If you set a Margin=0 (or just unset it), it renders.

The PR above fixes the Path size calculation afaict, but unfortunately, it still doesn't render because of the Margin.

Stepping thru things in the debugger reveals that Margin.Left/Top/etc are all `0` for the Path Shape even tho it is defined in the XAML to have `Margin="6"`.

If the Margin value gets set on something else and not the Path itself, where does it get set? Or is the problem that the Path *isn't* getting the Margin?

Seems more likely that *something* is getting the Margin, just not what I would expect.

This is driving me crazy.

**Comment by jstedfast** [comment] 2023-09-28 20:21
This is a duplicate of issue #14239

**Comment by samhouts** [comment] 2023-09-28 22:22
Duplicate of #14239

**Closed by samhouts** 2023-09-28 22:22 UTC
Labels: t/bug, platform/android 🤖, area/controls 🎮, control-border, potential-regression
