### ISSUE TITLE
MacCatalyst - Menu items are lost when creating new windows and returning to previous windows.

### ISSUE THREAD

**Issue by matthewrdev** [dotnet/maui#14178] opened 2023-03-24 05:20 UTC
### Description

In MacCatalyst for .NET MAUI, when I am working with [multi-window](https://learn.microsoft.com/en-us/dotnet/maui/fundamentals/windows?view=net-maui-7.0#ipados-and-macos-configuration) apps, windows will lose their defined `MenuItem`'s when creating and closing windows.

### Steps to Reproduce

1. Create a new MAUI app and configure the MacCatalyst platform to support [multiple windows](https://learn.microsoft.com/en-us/dotnet/maui/fundamentals/windows?view=net-maui-7.0#ipados-and-macos-configuration).
2. Define several menu items on the MainPage under an `Actions` labelled item.
3. Create a new ContentPage class file named `EmptyPage`; this page can be completely empty.
4. Create a button labelled "Create Window" with a click event to create an instance of `EmptyPage`, create an instance of `Window` with empty page supplied as the page and then calls `App.Current.OpenWindow`.
5. Run the solution.
6. When the app starts, notices that the custom `Actions` menu item is included into the menu bar.
7. Click the "Create Window" button.
8. Observe that the new window does not have the actions menu bar item.
9. Close the window.
10. When the focus returns to the main app window, notice that the `Actions` menu items are gone.

**Expected Result**
When I define menu items for a page, and a new window is created then dismissed, returning focus to the page, the menu items for the focused page should return onto the menu bar.

**Actual Result**
When I define menu items for a page, and a new window is created then dismissed,  when the focus returns to the page the menu items are not returned into the menu bar and are lost.

### Link to public reproduction project repository

https://github.com/matthewrdev/maui-mac-catalyst-bugs

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

MauiMacCatalyst 16.2.1040. MacCatalyst: Target 16.1, min 13.1, .NET 7.0. Visual Studio Mac 17.5.2

### Did you find any workaround?

No work around identified apart from not using multi-window applications in MacCatalyst.

**Comment by ooikengsiang** [comment] 2023-03-24 09:37
I think this is a duplicate of #10702

**Comment by PureWeen** [comment] 2023-05-05 16:25
This should be fixed by https://github.com/dotnet/maui/pull/13709

**Closed by PureWeen** 2023-05-05 16:25 UTC
Labels: t/bug, s/duplicate 2️⃣, platform/macOS 🍏, area/controls 🎮, control-menubar

**Comment by matthewrdev** [comment] 2023-05-20 05:45
@PureWeen Thanks for getting the fixed merged in!
