### ISSUE TITLE
Unable to change/set App Icon and Splash Screen for IOS

### ISSUE THREAD

**Issue by canperk** [dotnet/maui#11654] opened 2022-11-25 12:51 UTC
### Description

We are unable to change App Icon and Splash Screen image. It has only .NET icon with purple background. Even background color is not affected by change

### Steps to Reproduce

1. Create MAUI Project with XAML
2. Change App ICon and Splash Screen with a random svg
3. Deploy to IOS device

Actual Result:
App Icon and Splash Screen not updated

Expected Result:
App Icon and Splash Screen changes

.csproj file sample for regarding lines

```
<!-- App Icon -->
<MauiIcon Include="Resources\AppIcon\appicon.svg" ForegroundFile="Resources\AppIcon\appiconfg.svg" Color="#FFC64B" />

<!-- Splash Screen -->
<MauiSplashScreen Include="Resources\Splash\splash.svg" Color="#EDEDED" BaseSize="1200,400" />
```

Android devices are working like a charm but IOS has this problem to sum up.

### Link to public reproduction project repository

https://github.com/canperk/maui-issue-repository

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

https://github.com/canperk/maui-issue-repository

**Comment by KSemenenko** [comment] 2022-11-25 13:25
related to #11295

**Comment by ultra133** [comment] 2022-11-25 14:53
To update the splash screen on the device, you need to
1. delete the app on the device
2. reboot the device (this is important!)
3. deploy and start the app
This sounds silly, but there is some kind of caching mechanism in iOS.

To update the app icon try to delete bin and obj folders and rebuild the app.

**Comment by KSemenenko** [comment] 2022-11-25 16:18
or just chage file name for icon

**Comment by canperk** [comment] 2022-11-25 16:30
Changing file name did not change the issue. Should I ignore development behavior and check it when I publish app to Test Flight?

**Comment by KSemenenko** [comment] 2022-11-25 21:59
Yes, try test flight, for local development it’s relay required to delete the app and restarts the phone

**Comment by mattleibow** [comment] 2022-11-28 15:43
Closing as a duplicate of #8685

Thanks @ultra133 for the comment right away. Still having a look at this and what we can do.

**Comment by mattleibow** [comment] 2022-11-28 15:43
duplicate of #8685

**Comment by mattleibow** [comment] 2022-11-28 15:43
Duplicate of #8685

**Closed** 2022-11-28 15:43 UTC
Labels: t/bug, area/single project ☝️, platform/iOS 🍎
