### ISSUE TITLE
[regression/not fixed in 8.0.0-rc.1.9012] Binding Issue: Multiple platform CheckBox control 'IsChecked'

### ISSUE THREAD

**Issue by Stedy59** [dotnet/maui#16926] opened 2023-08-22 16:23 UTC
### Description

CheckBox control IsCheckedProperty will not update using a bound property.

This is not fixed in the nightly build: 8.0.0-rc.1.9012

### Steps to Reproduce

Create a Checkbox
Bind its IsChecked property to a BindableProperty
Checkbox IsChecked remains at initial value

### Link to public reproduction project repository

https://github.com/Stedy59/StedySoft.BindingIssues.4

### Version with bug

8.0.0-preview.7.8842

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.0-preview.6.8686

### Affected platforms

Android, Windows

### Affected platform versions

Windows SDK - all, Android API 34

### Did you find any workaround?

No

**Comment by samhouts** [comment] 2023-08-23 00:14
Nice catch!! It looks like this is another instance of https://github.com/dotnet/maui/issues/16849. I'll mark this one as a duplicate, if you don't mind. Thanks, @Stedy59 !!

**Comment by samhouts** [comment] 2023-08-23 00:14
Duplicate of #16849

**Closed by samhouts** 2023-08-23 00:14 UTC
Labels: t/bug, area/controls 🎮, control-checkbox, i/regression
