### ISSUE TITLE
System.IndexOutOfRangeException: IItemsViewSource is empty

### ISSUE THREAD

**Issue by LeoJHarris** [dotnet/maui#25357] opened 2024-10-17 20:29 UTC
### Description

iOS issue whereby the `ItemsSource` seems to be empty from the UI but I have added a few checks against empty `ItemsSource` from the MVVM when trying to access indexes of the `ItemsSource`. For the same source code Android never has the issue.

### Version with bug

8.0.92 SR9.2

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15

### Did you find any workaround?

No

### Relevant log output

System.IndexOutOfRangeException: IItemsViewSource is empty
   at Microsoft.Maui.Controls.Handlers.Items.EmptySource.get_Item(NSIndexPath indexPath)
   at Microsoft.Maui.Controls.Handlers.Items.ItemsViewController`1[[Microsoft.Maui.Controls.ReorderableItemsView, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].UpdateTemplatedCell(TemplatedCell cell, NSIndexPath indexPath)
   at Microsoft.Maui.Controls.Handlers.Items.ItemsViewController`1[[Microsoft.Maui.Controls.ReorderableItemsView, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].GetCell(UICollectionView collectionView, NSIndexPath indexPath)
   at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:line 61

**Comment by LeoJHarris** [comment] 2024-10-17 20:29
Seems to be similar to https://github.com/dotnet/maui/issues/11666

**Comment by Zhanglirong-Winnie** [comment] 2024-10-18 09:36
Could you provide us with a sample project so we can investigate it further? Looking forward to your reply!

**Comment by PureWeen** [comment] 2024-10-21 17:39
Duplicate of #25224

**Closed by PureWeen** 2024-10-21 17:39 UTC
Labels: t/bug, platform/iOS 🍎, s/triaged, s/needs-repro
