### ISSUE TITLE
[Catalyst] Reusing Modal Page causes inner page contents to resize incorrectly, breaking page.

### ISSUE THREAD

**Issue by drasticactions** [dotnet/maui#13697] opened 2023-03-04 08:52 UTC
### Description

https://user-images.githubusercontent.com/898335/222886259-0b3f21c6-f8b6-4a62-b4a7-01e5be273048.mp4

I have a function to [show or hide a modal page on a window](https://github.com/drasticactions/MAUImgur/blob/MauiBug-ModalLayout/src/Mauimgur/MainWindow.cs#L21-L47). The page is kept in memory so I can attach a view model under it and update that page with events firing in the background, and dynamically show or hide it based on what is going on.

For Android, WinUI, and iOS, this works. For Catalyst, the inner contents of the page seem to resize every time I reuse the page. This breaks the page, rendering it useless.

### Steps to Reproduce

1. Checkout attached repo.
2. Run app on Catalyst, click "Show Results Screen"

### Link to public reproduction project repository

https://github.com/drasticactions/MAUImgur/tree/MauiBug-ModalLayout/src/Mauimgur

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

All Catalyst Versions.

### Did you find any workaround?

Creating a new page every time "fixes" the layout. However, this would make my current use-case impossible unless I refactor my approach.

**Comment by PureWeen** [comment] 2023-03-07 18:52
@drasticactions is this a duplicate of https://github.com/dotnet/maui/issues/6994 ?

**Closed** 2023-03-16 01:01 UTC
Labels: t/bug, platform/macOS 🍏, area/layout 🔲, area/navigation 🧭, s/needs-info, area/modal, s/no-recent-activity
