### ISSUE TITLE
[regression/8.0.0-preview.5.8529] CollectionView doesn't automatically expand anymore

### ISSUE THREAD

**Issue by NonameMissingNo** [dotnet/maui#15697] opened 2023-06-16 09:29 UTC
### Description

If you the first element expands, all of them does, if the first doesn't, none of them.
First element open:
![image](https://github.com/dotnet/maui/assets/40233496/a5f9a514-9ecd-4b1c-93f6-ecf8d0504b46)

Any other element open:
![image](https://github.com/dotnet/maui/assets/40233496/43b7d851-f6bf-4cf1-a435-2f3af7e9e685)

### Steps to Reproduce

Create a new project.
Make a CollectionView.
Make a Grid inside it.
Change the Grid's RowDefinitions.
Obvserve the issue.

### Link to public reproduction project repository

https://github.com/NonameMissingNo/CollectionView-Expansion-Issue

### Version with bug

8.0.0-preview.5.8529

### Last version that worked well

7.0.86

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Windows 11

**Comment by NonameMissingNo** [comment] 2023-06-16 10:32
(For reference, ListView is working just fine)

**Comment by NonameMissingNo** [comment] 2023-07-11 18:07
Preview 6, still a bug

**Comment by samhouts** [comment] 2023-08-03 19:35
Duplicate of #16234

**Closed by samhouts** 2023-08-03 19:35 UTC
Labels: t/bug, platform/windows 🪟, area/collectionview 📃, i/regression, layout-grid
