### ISSUE TITLE
MAUI 9 Shell Tabbar does not work on iOS with more than 5 tabs

### ISSUE THREAD

**Issue by SorenBech2** [dotnet/maui#26164] opened 2024-11-27 15:10 UTC
### Description

When a page is pushed to the stack from a 5th menu point (or more) in a Tabbar with more than 5 tabs, it is not possible to add another page to the stack. No exceptions, no errors - execution just stops! If the same page is pushed (GotoAsync()) from a menu point 1-4 on the tabbar no issue. The issue exist on IOS, not on Android nor Windows.

The issue exist on NET MAUI 8, but 9 has made no difference.
issue 24529#

### Steps to Reproduce

Use attached repro. Deploy on IOS and select a Tab "Working 1". Press "Go to second page"., then press "Go back". Everything works fine.
Select Tab "Not working 1". Press "Go to second page" Nothing happens. The press < More.

### Link to public reproduction project repository

https://github.com/SorenBech2/ShellTestMAUI9

### Version with bug

9.0.10 SR1

### Is this a regression from previous behavior?

No, this is something new

### Affected platforms

iOS

### Affected platform versions

iOS 17, 18

### Did you find any workaround?

No

### Relevant log output

```shell
No log output, no error messages - execution just stops!
```

**Comment by jfversluis** [comment] 2024-11-28 08:04
Duplicate of #24529

**Closed by jfversluis** 2024-11-28 08:04 UTC
Labels: t/bug

**Comment by SorenBech2** [comment] 2024-11-28 08:30
Could you please elaborate on "as not planned". What does this mean? That the issue is ignore and will not be corrected??



Med venlig hilsen / Best regards


Søren Bech

Marmorvej 35

DK-2100 København Ø

+45 4076 5050

***@***.***



________________________________

**Comment by jfversluis** [comment] 2024-11-28 12:32
The important part is in the comment: its a duplicate. So the actual status for this issue can be found in the original issue. In this case: it will be worked on, but we don't have it planned currently.
