### ISSUE TITLE
Dynamic Resources Doesn't Work with AppThemeBinding on ResourceDictionaries

### ISSUE THREAD

**Issue by AathifMahir** [dotnet/maui#14855] opened 2023-05-01 03:13 UTC
### Description

Dynamic Resources Doesn't Work with AppThemeBinding on Resource Dictionaries, Making it StaticResource Does Fix the Issue

### Steps to Reproduce

1. Create Maui Project
2. Create Resource Dictionary
3. Add Couple of Colors to the Dictionary
4. Merge that Dictionary in App.xaml
5. Add Style to Any Built Control on App.xaml
6. Add Color to that Style using AppThemeBinding and DynamicResources

### Link to public reproduction project repository

https://github.com/AathifMahir/MauiBlazorStyleTest

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows, I was *not* able test on other platforms

### Affected platform versions

Android 12, Windows 11 22H2

### Did you find any workaround?

1. Create Maui Project
2. Create Resource Dictionary
3. Add Couple of Colors to the Dictionary
4. Merge that Dictionary in App.xaml
5. Add Style To Any Built Control on App.xaml

**Comment by drasticactions** [comment] 2023-05-01 08:21
Does this work on Xamarin.Forms? I'm interested if this is a regression or if it doesn't work there either.

**Comment by AathifMahir** [comment] 2023-05-01 09:00
> Does this work on Xamarin.Forms? I'm interested if this is a regression or if it doesn't work there either.

Not sure about Xamarin forms, didn't had the chance to test there, if you really want that I could test there within the next few days

**Comment by PureWeen** [comment] 2023-05-02 18:26
Duplicate of #13619

**Closed by PureWeen** 2023-05-02 18:26 UTC
Labels: t/bug, s/needs-attention
