### ISSUE TITLE
Mono.Debugging.Soft.DisconnectedException on Hotreload Crashes On Android

### ISSUE THREAD

**Issue by ozersenol** [dotnet/maui#17227] opened 2023-09-06 06:00 UTC
### Description

I get Windows Error When I make changes on VS 2022 while debugging Dotnet Maui Blazor app . When Save of file and push hotreload it gives error.: "Mono.Debugging.Soft.DisconnectedException" . I cannot copy error from windows error and you can fin it here: 

https://drive.google.com/file/d/10DGUostS3jbuSAhMPie31VblTGZrfmne/view?usp=sharing

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android Emulator and Local Devices

**Comment by drasticactions** [comment] 2023-09-06 11:45
Duplicate of https://github.com/dotnet/maui/issues/17178

**Closed by drasticactions** 2023-09-06 11:45 UTC
Labels: t/bug
