### ISSUE TITLE
Spaces in static files (CSS, JS, images, etc.) not working in MAUI Blazor for Windows

### ISSUE THREAD

**Issue by VolkumDev** [dotnet/maui#9181] opened 2022-08-04 02:57 UTC
### Description

The problem is almost identical to #8103. I create a project based on the MAUI Blazor Template, i run the app, and what i get is this:

![imagen](https://user-images.githubusercontent.com/58671061/182752571-8c8309ff-7dd5-414e-9c18-b6d15a13a88a.png)

![imagen](https://user-images.githubusercontent.com/58671061/182762037-595e10b9-97cd-4bcd-9f8e-71910d7e2a48.png)

I have already cleaned the solution, deleted the obj/bin folders, i did it on different orders, i rebuild, clean rebuild, etc. Nothing worked.

No errors are showing up on Visual Studio.

I have the latest available Visual Studio Preview version from "Tools and Features" installer.

### Steps to Reproduce

1. Create a project with the MAUI Blazor template 
2. Build and run the project.

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, Android

### Affected platform versions

Windows 10.0.19041.0

**Comment by Eilon** [comment] 2022-08-26 00:00
More repro info here: https://github.com/dotnet/maui/issues/9481. Per the other issue, we likely need to do some UrlDecode on the "URL"-ish path to fix up spaces and perhaps other path-unfriendly characters.

**Comment by Eilon** [comment] 2022-08-26 00:04
The repro is actually quite simple: `dotnet new maui-blazor -o "Test With Spaces"` and you get this broken app:

![image](https://user-images.githubusercontent.com/202643/186789629-24415521-6595-4db8-9b98-001c8c281984.png)

**Comment by TcNobo** [comment] 2022-09-10 16:11
Just to be clear, the normal Blazor server has absolutely no issue handling `%20`. It seems to only be MAUI Blazor. A little annoying to change how my programs work to get around this (swap ' ' with '_' for example, and rename all the files) but not the end of the world.

**Comment by Eilon** [comment] 2022-09-11 22:28
@TcNobo , yup, this bug is entirely specific to Blazor Hybrid. It needs to un-escape data that comes from the native webview (e.g. WebView2) so that it can use that as a file system path.

**Comment by mkArtakMSFT** [comment] 2022-11-16 18:44
This is a dupe of https://github.com/dotnet/maui/issues/10780

**Closed by mkArtakMSFT** 2022-11-16 18:44 UTC
Labels: t/bug, area/blazor 🕸️
