### ISSUE TITLE
SearchBar crashes App on IOS by click on it to type

### ISSUE THREAD

**Issue by enny1170** [dotnet/maui#21139] opened 2024-03-11 19:24 UTC
### Description

When i create a Page that has a SearchBar on it. The Page will be displayed. Is a User try to type something into the SearchBar the App is closed. 
This is only on IOS for example Simulator with IOS 17.4. MacCatalyst and Windows and Android is working as expected.

### Steps to Reproduce

- Create a new Maui App
- Inserd <SearchBar /> Tag into MainPage.xaml
- Build and debug it on a Ios Device or Simulator
- Click on the SearchBar the app will chrash

### Link to public reproduction project repository

https://github.com/enny1170/MauiSearchBarDemo

### Version with bug

8.0.7 SR2

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.3 GA

### Affected platforms

iOS

### Affected platform versions

IOS 17.4

**Comment by enny1170** [comment] 2024-03-11 19:40
additional Info, looks like a OS related issue. I'm try this with a IPad having IOS 17.2 this works works with 8.0.3 and 8.0.7 Version

**Comment by PureWeen** [comment] 2024-03-11 21:16
Duplicate of #21057

**Closed by PureWeen** 2024-03-11 21:16 UTC
Labels: t/bug
