### ISSUE TITLE
[Android] App crashes when start from background

### ISSUE THREAD

**Issue by brzezinol** [dotnet/maui#4169] opened 2022-01-17 18:51 UTC
### Description

I have created new app after update to VS 2022 17.1.0 Preview 2.0.
Clean app crashes when is started from background with error:
System.NotImplementedException: 'Either set MainPage or override CreateWindow.'

### Steps to Reproduce

1. start app
2. tap backbutton for exit app
3. tap on app icon for start app
4. app craches with error System.NotImplementedException: 'Either set MainPage or override CreateWindow.'

### Version with bug

Preview 11

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

### Relevant log output

```shell
> am start -a "android.intent.action.MAIN" -c "android.intent.category.LAUNCHER" -n "com.companyname.checknewtemplate/crc64d27ca43a711fc7df.MainActivity"
> Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.companyname.checknewtemplate/crc64d27ca43a711fc7df.MainActivity }
Loaded assembly: /data/data/com.companyname.checknewtemplate/files/.__override__/CheckNewTemplate.dll
Loaded assembly: /data/data/com.companyname.checknewtemplate/files/.__override__/Mono.Android.dll [External]
Loaded assembly: /data/data/com.companyname.checknewtemplate/files/.__override__/System.Runtime.dll [External]
Loaded assembly: /data/data/com.companyname.checknewtemplate/files/.__override__/Java.Interop.dll [External]
Loaded assembly: /data/data/com.companyname.checknewtemplate/files/.__override__/System.Collections.dll [External]
Resolved pending breakpoint for 'Android.Runtime.JNIEnv.RegisterJniNatives(System.IntPtr, System.Int32, System.IntPtr, System.IntPtr, System.Int32)' to /Users/builder/azdo/_work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNIEnv.cs:124 [0x00000].
Loaded assembly: /data/data/com.companyname.checknewtemplate/files/.__override__/System.Threading.dll [External]
Loaded assembly: /data/data/com.companyname.checknewtemplate/files/.__override__/System.Runtime.InteropServices.dll [External]
Loaded assembly: /data/data/com.companyname.checknewtemplate/files/.__override__/System.Threading.Thread.dll [External]
Loaded assembly: /data/data/com.companyname.checknewtemplate/files/.__override__/System.Diagnostics.StackTrace.dll [External]
Loaded assembly: data-0x70d60808d030 [External]
Loaded assembly: data-0x70d60809d040 [External]
Loaded assembly: data-0x70d69c28c040 [External]
Loaded assembly: data-0x70d6080cd070 [External]
Loaded assembly: /data/data/com.companyname.checknewtemplate/files/.__override__/netstandard.dll [External]
Loaded assembly: /data/data/com.companyname.checknewtemplate/files/.__override__/System.Linq.dll [External]
Loaded assembly: /data/data/com.companyname.checknewtemplate/files/.__override__/System.Collections.Concurrent.dll [External]
Resolved pending breakpoint for 'Xamarin.HotReload.HotReloadAgent.BreakpointSendToIde(System.String)' to D:\a\_work\1\s\HotReload\Source\Xamarin.HotReload.Agent\HotReloadAgent.cs:410 [0x00000].
Loaded assembly: /data/data/com.companyname.checknewtemplate/files/.__override__/System.Text.Json.dll [External]
Loaded assembly: /data/data/com.companyname.checknewtemplate/files/.__override__/System.Text.Encodings.Web.dll [External]
Loaded assembly: /data/data/com.companyname.checknewtemplate/files/.__override__/System.ComponentModel.dll [External]
Loaded assembly: /data/data/com.companyname.checknewtemplate/files/.__override__/Microsoft.Maui.Controls.dll [External]
Loaded assembly: /data/data/com.companyname.checknewtemplate/files/.__override__/System.ObjectModel.dll [External]
Loaded assembly: /data/data/com.companyname.checknewtemplate/files/.__override__/Microsoft.Maui.dll [External]
Loaded assembly: /data/data/com.companyname.checknewtemplate/files/.__override__/Microsoft.Maui.Graphics.dll [External]
Loaded assembly: /data/data/com.companyname.checknewtemplate/files/.__override__/Microsoft.Extensions.Logging.Abstractions.dll [External]
Loaded assembly: /data/data/com.companyname.checknewtemplate/files/.__override__/System.Runtime.Loader.dll [External]
Resolved pending breakpoint for 'Xamarin.HotReload.HotReloadAgent.BreakpointCheckpoint()' to D:\a\_work\1\s\HotReload\Source\Xamarin.HotReload.Agent\HotReloadAgent.cs:405 [0x00000].
Loaded assembly: /data/data/com.companyname.checknewtemplate/files/.__override__/System.Reflection.Emit.Lightweight.dll [External]
Loaded assembly: /data/data/com.companyname.checknewtemplate/files/.__override__/System.Reflection.Emit.ILGeneration.dll [External]
Loaded assembly: /data/data/com.companyname.checknewtemplate/files/.__override__/System.Reflection.Primitives.dll [External]
Loaded assembly: /data/data/com.companyname.checknewtemplate/files/.__override__/Microsoft.Maui.Essentials.dll [External]
Loaded assembly: /data/data/com.companyname.checknewtemplate/files/.__override__/Xamarin.AndroidX.Core.dll [External]
Loaded assembly: /data/data/com.companyname.checknewtemplate/files/.__override__/Microsoft.Extensions.Hosting.Abstractions.dll [External]
Loaded assembly: /data/data/com.companyname.checknewtemplate/files/.__override__/Microsoft.Extensions.DependencyInjection.Abstractions.dll [External]
Loaded assembly: /data/data/com.companyname.checknewtemplate/files/.__override__/Microsoft.Maui.Controls.Compatibility.dll [External]
Loaded assembly: /data/data/com.companyname.checknewtemplate/files/.__override__/Microsoft.Extensions.Hosting.dll [External]
Loaded assembly: /data/data/com.companyname.checknewtemplate/files/.__override__/Microsoft.Extensions.Logging.dll [External]
Loaded assembly: /data/data/com.companyname.checknewtemplate/files/.__override__/Microsoft.Extensions.Configuration.dll [External]
Loaded assembly: /data/data/com.companyname.checknewtemplate/files/.__override__/Microsoft.Extensions.Configuration.Abstractions.dll [External]
Loaded assembly: /data/data/com.companyname.checknewtemplate/files/.__override__/Microsoft.Extensions.FileProviders.Physical.dll [External]
Loaded assembly: /data/data/com.companyname.checknewtemplate/files/.__override__/Microsoft.Extensions.FileProviders.Abstractions.dll [External]
Loaded assembly: /data/data/com.companyname.checknewtemplate/files/.__override__/Microsoft.Extensions.Primitives.dll [External]
Loaded assembly: /data/data/com.companyname.checknewtemplate/files/.__override__/Microsoft.Extensions.DependencyInjection.dll [External]
Loaded assembly: /data/data/com.companyname.checknewtemplate/files/.__override__/Microsoft.Extensions.Configuration.FileExtensions.dll [External]
Loaded assembly: /data/data/com.companyname.checknewtemplate/files/.__override__/Microsoft.Extensions.Options.dll [External]
Loaded assembly: /data/data/com.companyname.checknewtemplate/files/.__override__/Microsoft.Extensions.Logging.EventLog.dll [External]
Loaded assembly: /data/data/com.companyname.checknewtemplate/files/.__override__/Microsoft.Extensions.Logging.Configuration.dll [External]
Loaded assembly: /data/data/com.companyname.checknewtemplate/files/.__override__/Microsoft.Extensions.Logging.Debug.dll [External]
Loaded assembly: /data/data/com.companyname.checknewtemplate/files/.__override__/Microsoft.Extensions.Logging.Console.dll [External]
Loaded assembly: /data/data/com.companyname.checknewtemplate/files/.__override__/Microsoft.Extensions.Logging.EventSource.dll [External]
Loaded assembly: /data/data/com.companyname.checknewtemplate/files/.__override__/Microsoft.Extensions.Options.ConfigurationExtensions.dll [External]
Loaded assembly: /data/data/com.companyname.checknewtemplate/files/.__override__/Xamarin.AndroidX.RecyclerView.dll [External]
Loaded assembly: /data/data/com.companyname.checknewtemplate/files/.__override__/Xamarin.AndroidX.DrawerLayout.dll [External]
Loaded assembly: /data/data/com.companyname.checknewtemplate/files/.__override__/Xamarin.AndroidX.CustomView.dll [External]
Loaded assembly: /data/data/com.companyname.checknewtemplate/files/.__override__/Xamarin.Google.Android.Material.dll [External]
Loaded assembly: /data/data/com.companyname.checknewtemplate/files/.__override__/Xamarin.AndroidX.AppCompat.dll [External]
Loaded assembly: /data/data/com.companyname.checknewtemplate/files/.__override__/Xamarin.AndroidX.SwipeRefreshLayout.dll [External]
Loaded assembly: /data/data/com.companyname.checknewtemplate/files/.__override__/Xamarin.AndroidX.ViewPager2.dll [External]
Loaded assembly: /data/data/com.companyname.checknewtemplate/files/.__override__/System.ComponentModel.TypeConverter.dll [External]
Loaded assembly: /data/data/com.companyname.checknewtemplate/files/.__override__/System.Private.Uri.dll [External]
Loaded assembly: /data/data/com.companyname.checknewtemplate/files/.__override__/System.Diagnostics.DiagnosticSource.dll [External]
Loaded assembly: /data/data/com.companyname.checknewtemplate/files/.__override__/System.Diagnostics.Tracing.dll [External]
Loaded assembly: /data/data/com.companyname.checknewtemplate/files/.__override__/Microsoft.Extensions.Configuration.Binder.dll [External]
[hecknewtemplat] Late-enabling -Xcheck:jni
[hecknewtemplat] Unquickening 12 vdex files!
[hecknewtemplat] Unexpected CPU variant for X86 using defaults: x86_64
[NetworkSecurityConfig] No Network Security Config specified, using platform default
[NetworkSecurityConfig] No Network Security Config specified, using platform default
[debug-app-helper] Checking if libmonodroid was unpacked to /data/app/~~jMP0uwFGBytzwVkpuucVhg==/com.companyname.checknewtemplate-m803XLLW9rDErxU3KsgLkw==/lib/x86_64/libmonodroid.so
[debug-app-helper] Native libs extracted to /data/app/~~jMP0uwFGBytzwVkpuucVhg==/com.companyname.checknewtemplate-m803XLLW9rDErxU3KsgLkw==/lib/x86_64, assuming application/android:extractNativeLibs == true
[debug-app-helper] Setting up for DSO lookup in app data directories
[debug-app-helper] Added filesystem DSO lookup location: /data/app/~~jMP0uwFGBytzwVkpuucVhg==/com.companyname.checknewtemplate-m803XLLW9rDErxU3KsgLkw==/lib/x86_64
[debug-app-helper] Using runtime path: /data/app/~~jMP0uwFGBytzwVkpuucVhg==/com.companyname.checknewtemplate-m803XLLW9rDErxU3KsgLkw==/lib/x86_64
[debug-app-helper] checking directory: `/data/user/0/com.companyname.checknewtemplate/files/.__override__/lib`
[debug-app-helper] directory does not exist: `/data/user/0/com.companyname.checknewtemplate/files/.__override__/lib`
[debug-app-helper] Checking whether Mono runtime exists at: /data/user/0/com.companyname.checknewtemplate/files/.__override__/libmonosgen-2.0.so
[debug-app-helper] Checking whether Mono runtime exists at: /data/app/~~jMP0uwFGBytzwVkpuucVhg==/com.companyname.checknewtemplate-m803XLLW9rDErxU3KsgLkw==/lib/x86_64/libmonosgen-2.0.so
[debug-app-helper] Mono runtime found at: /data/app/~~jMP0uwFGBytzwVkpuucVhg==/com.companyname.checknewtemplate-m803XLLW9rDErxU3KsgLkw==/lib/x86_64/libmonosgen-2.0.so
[hecknewtemplat] Attempt to remove non-JNI local reference, dumping thread
[DOTNET] JNI_OnLoad: JNI_OnLoad in pal_jni.c
[monodroid] Creating public update directory: `/data/user/0/com.companyname.checknewtemplate/files/.__override__`
[hecknewtemplat] Attempt to remove non-JNI local reference, dumping thread
[monodroid-debug] Trying to initialize the debugger with options: --debugger-agent=transport=dt_socket,loglevel=0,address=10.0.2.2:57525,embedding=1
[monodroid-assembly] open_from_bundles: failed to load assembly CheckNewTemplate.dll
[monodroid-gc] GREF GC Threshold: 46080
[monodroid-assembly] open_from_bundles: failed to load assembly Mono.Android.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Runtime.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Java.Interop.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Collections.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Threading.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Runtime.InteropServices.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Threading.Thread.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Diagnostics.StackTrace.dll
[hecknewtemplat] Attempt to remove non-JNI local reference, dumping thread
[monodroid-assembly] open_from_bundles: failed to load assembly netstandard.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Linq.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.VisualStudio.DesignTools.TapContract.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.VisualStudio.DesignTools.TapContract.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.HotReload.Contracts.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.HotReload.Contracts.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Collections.Concurrent.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Text.Json.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Text.Encodings.Web.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.ComponentModel.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Maui.Controls.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.HotReload.Contracts.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.HotReload.Contracts.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.VisualStudio.DesignTools.TapContract.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.VisualStudio.DesignTools.TapContract.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.ObjectModel.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Maui.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Maui.Graphics.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Extensions.Logging.Abstractions.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Runtime.Loader.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Reflection.Emit.Lightweight.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Reflection.Emit.ILGeneration.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Reflection.Primitives.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Maui.Essentials.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.Core.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Extensions.Hosting.Abstractions.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Extensions.DependencyInjection.Abstractions.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Maui.Controls.Compatibility.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Extensions.Hosting.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Extensions.Logging.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Extensions.Configuration.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Extensions.Configuration.Abstractions.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Extensions.FileProviders.Physical.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Extensions.FileProviders.Abstractions.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Extensions.Primitives.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Extensions.DependencyInjection.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Extensions.Configuration.FileExtensions.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Extensions.Options.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Extensions.Logging.EventLog.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Extensions.Logging.Configuration.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Extensions.Logging.Debug.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Extensions.Logging.Console.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Extensions.Logging.EventSource.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Extensions.Options.ConfigurationExtensions.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.RecyclerView.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.DrawerLayout.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.CustomView.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.Google.Android.Material.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.AppCompat.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.SwipeRefreshLayout.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.ViewPager2.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.ComponentModel.TypeConverter.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Private.Uri.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Diagnostics.DiagnosticSource.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Diagnostics.Tracing.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Extensions.Configuration.Binder.dll
[0:] Microsoft.Maui.Dispatching.Dispatcher: Warning: Replaced an existing DispatcherProvider with one from the service provider.
[monodroid-assembly] open_from_bundles: failed to load assembly System.Linq.Expressions.dll
Loaded assembly: /data/data/com.companyname.checknewtemplate/files/.__override__/System.Linq.Expressions.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Maui.Controls.Xaml.dll
Loaded assembly: /data/data/com.companyname.checknewtemplate/files/.__override__/Microsoft.Maui.Controls.Xaml.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly System.Xml.ReaderWriter.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Private.Xml.dll
Loaded assembly: /data/data/com.companyname.checknewtemplate/files/.__override__/System.Xml.ReaderWriter.dll [External]
Loaded assembly: /data/data/com.companyname.checknewtemplate/files/.__override__/System.Private.Xml.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly System.Text.Encoding.Extensions.dll
Loaded assembly: /data/data/com.companyname.checknewtemplate/files/.__override__/System.Text.Encoding.Extensions.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly System.Memory.dll
Loaded assembly: /data/data/com.companyname.checknewtemplate/files/.__override__/System.Memory.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly System.Text.RegularExpressions.dll
Loaded assembly: /data/data/com.companyname.checknewtemplate/files/.__override__/System.Text.RegularExpressions.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly System.Runtime.CompilerServices.Unsafe.dll
Loaded assembly: /data/data/com.companyname.checknewtemplate/files/.__override__/System.Runtime.CompilerServices.Unsafe.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly System.Numerics.Vectors.dll
Loaded assembly: /data/data/com.companyname.checknewtemplate/files/.__override__/System.Numerics.Vectors.dll [External]
Thread started:  #2
Thread started:  #3
Thread started:  #4
[monodroid-assembly] open_from_bundles: failed to load assembly System.Runtime.Serialization.Json.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Private.DataContractSerialization.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Runtime.Serialization.Xml.dll
Loaded assembly: /data/data/com.companyname.checknewtemplate/files/.__override__/System.Runtime.Serialization.Json.dll [External]
Loaded assembly: /data/data/com.companyname.checknewtemplate/files/.__override__/System.Private.DataContractSerialization.dll [External]
Loaded assembly: /data/data/com.companyname.checknewtemplate/files/.__override__/System.Runtime.Serialization.Xml.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly pl-PL/System.Private.CoreLib.resources.dll
[monodroid-assembly] open_from_bundles: failed to load assembly pl-PL/System.Private.CoreLib.resources.dll
[monodroid-assembly] open_from_bundles: failed to load assembly pl/System.Private.CoreLib.resources.dll
[monodroid-assembly] open_from_bundles: failed to load assembly pl/System.Private.CoreLib.resources.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Runtime.Serialization.Primitives.dll
Loaded assembly: /data/data/com.companyname.checknewtemplate/files/.__override__/System.Runtime.Serialization.Primitives.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly pl-PL/System.Private.DataContractSerialization.resources.dll
[monodroid-assembly] open_from_bundles: failed to load assembly pl-PL/System.Private.DataContractSerialization.resources.dll
[monodroid-assembly] open_from_bundles: failed to load assembly pl/System.Private.DataContractSerialization.resources.dll
[monodroid-assembly] open_from_bundles: failed to load assembly pl/System.Private.DataContractSerialization.resources.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.CardView.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Maui.Controls.Compatibility.Android.FormsViewGroup.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.ViewPager.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.Fragment.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.Activity.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.Lifecycle.ViewModel.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.Lifecycle.Common.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.SavedState.dll
Loaded assembly: /data/data/com.companyname.checknewtemplate/files/.__override__/Xamarin.AndroidX.CardView.dll [External]
Loaded assembly: /data/data/com.companyname.checknewtemplate/files/.__override__/Microsoft.Maui.Controls.Compatibility.Android.FormsViewGroup.dll [External]
Loaded assembly: /data/data/com.companyname.checknewtemplate/files/.__override__/Xamarin.AndroidX.ViewPager.dll [External]
Loaded assembly: /data/data/com.companyname.checknewtemplate/files/.__override__/Xamarin.AndroidX.Fragment.dll [External]
Loaded assembly: /data/data/com.companyname.checknewtemplate/files/.__override__/Xamarin.AndroidX.Activity.dll [External]
Loaded assembly: /data/data/com.companyname.checknewtemplate/files/.__override__/Xamarin.AndroidX.Lifecycle.ViewModel.dll [External]
Loaded assembly: /data/data/com.companyname.checknewtemplate/files/.__override__/Xamarin.AndroidX.Lifecycle.Common.dll [External]
Loaded assembly: /data/data/com.companyname.checknewtemplate/files/.__override__/Xamarin.AndroidX.SavedState.dll [External]
[libEGL] loaded /vendor/lib64/egl/libEGL_emulation.so
[libEGL] loaded /vendor/lib64/egl/libGLESv1_CM_emulation.so
[libEGL] loaded /vendor/lib64/egl/libGLESv2_emulation.so
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.Loader.dll
Loaded assembly: /data/data/com.companyname.checknewtemplate/files/.__override__/Xamarin.AndroidX.Loader.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.CoordinatorLayout.dll
Loaded assembly: /data/data/com.companyname.checknewtemplate/files/.__override__/Xamarin.AndroidX.CoordinatorLayout.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.Android.Glide.dll
Loaded assembly: /data/data/com.companyname.checknewtemplate/files/.__override__/Xamarin.Android.Glide.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.Lifecycle.LiveData.Core.dll
Loaded assembly: /data/data/com.companyname.checknewtemplate/files/.__override__/Xamarin.AndroidX.Lifecycle.LiveData.Core.dll [External]
[hecknewtemplat] Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (greylist, reflection, allowed)
[hecknewtemplat] Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (greylist, reflection, allowed)
Thread started: .NET Timers #5
[HostConnection] HostConnection::get() New Host Connection established 0x70d49806d850, tid 8838
[HostConnection] HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_YUV_Cache ANDROID_EMU_has_shared_slots_host_memory_allocator ANDROID_EMU_sync_buffer_data ANDROID_EMU_read_color_buffer_dma GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_gles_max_version_3_0 
[OpenGLRenderer] Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
[EGL_emulation] eglCreateContext: 0x70d488094b90: maj 3 min 0 rcv 3
[EGL_emulation] eglMakeCurrent: 0x70d488094b90: ver 3 0 (tinfo 0x70d4286fd950) (first time)
[Gralloc4] mapper 4.x is not supported
[HostConnection] createUnique: call
[HostConnection] HostConnection::get() New Host Connection established 0x70d498065c90, tid 8838
[goldfish-address-space] allocate: Ask for block of size 0x100
[goldfish-address-space] allocate: ioctl allocate returned offset 0x3f7ffe000 size 0x2000
[HostConnection] HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_YUV_Cache ANDROID_EMU_has_shared_slots_host_memory_allocator ANDROID_EMU_sync_buffer_data ANDROID_EMU_read_color_buffer_dma GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_gles_max_version_3_0 
Thread started: <Thread Pool> #6
Thread started: .NET ThreadPool Gate #7
Thread started: <Thread Pool> #8
[monodroid-assembly] open_from_bundles: failed to load assembly System.Runtime.Intrinsics.dll
Loaded assembly: /data/data/com.companyname.checknewtemplate/files/.__override__/System.Runtime.Intrinsics.dll [External]
**System.NotImplementedException:** 'Either set MainPage or override CreateWindow.'
```

**Comment by zhouwangyang** [comment] 2022-02-10 05:40
not repro on the latest build, please try on the latest build and tell us if any problems.

**Comment by brzezinol** [comment] 2022-02-10 07:43
@zhouwangyang what exactly build version?

**Comment by zhouwangyang** [comment] 2022-02-10 09:26
@brzezinol I reproduced on vs latest build 17.2.0 Preview 2.0.

**Comment by vamsitp** [comment] 2022-02-13 14:38
FWIW...

```cs
// App.xaml.cs
protected override Window CreateWindow(IActivationState activationState)
{
    // Workaround for: 'Either set MainPage or override CreateWindow.'??
    if (this.MainPage == null)
    {
        this.MainPage = new MainPage();
    }

    return base.CreateWindow(activationState);
}
```

**Comment by shimingsg** [comment] 2022-02-16 07:14
Not reproducible with android 11. app can be start.

**Comment by julienGrd** [comment] 2022-02-16 07:58
@shimingsg can you explain why you consider this issue closed ? for me there is still a problem (im on android 11, maui-check say everything is up to date). The workaround of @vamsitp in not enough because we have to recreate all the MainPage so we lost the state the app when she was putted in background.

thanks !

**Comment by shimingsg** [comment] 2022-02-16 08:55
@julienGrd I  repro this by the repro steps on Android 11 with vs 32214.398.main, app can be start, not crashes, so I  close it, if you can repro this issue, can you upload your repro project, or provide some repro video? it is helpful, thanks.

**Comment by julienGrd** [comment] 2022-02-16 09:55
@shimingsg is it the same behavior than us ?
- first launch OK
- then put the app in background with back button
- then put back the app in first plan (with the button to show all opened app) => at this moment the app crash

I reproduce this with the starter project on my side so no need to upload one specific

**Comment by julienGrd** [comment] 2022-02-16 13:40
actually i just made update to visual studio 17.2.0 preview 1.0, with fresh install of .net maui workload preview 13, and i still encounter the problem on a fresh startup project.

**Comment by rachelkang** [comment] 2022-02-16 15:12
I can confirm this is still an issue, and am working on it! Thanks for the patience everyone. In the meantime, I can also confirm that @vamsitp's [workaround](https://github.com/dotnet/maui/pull/4599#event-6083487770) is valid

**Closed** 2022-03-24 14:53 UTC
Labels: t/bug, platform/android 🤖, fatal, s/verified

**Comment by southsideringo** [comment] 2022-03-24 18:38
[zhouwangyang](https://github.com/zhouwangyang) same here. Is there a temporary workaround?  I mean the main page is already set to AppShell.xaml.cs. And wth happens when you override the launch? I'm guessing nothing good.

**Comment by jayveedee** [comment] 2022-04-17 18:13
I haven't updated to the RC Maui version yet (still on Version 17.2.0 Preview 2.1) but the error did still persist on that version

**Comment by BinaryAssault** [comment] 2022-04-19 02:55
I was able to verify I no longer have this issue (with the workaround removed) using RC1. I used the steps in OP to verify.
