### ISSUE TITLE
[NETSDKE2E][VS64][Loc].NET MAUI Multi-Project App template on "Create a new dialog" is not localized.

### ISSUE THREAD

**Issue by samhouts** [dotnet/maui#25218] opened 2024-10-11 21:04 UTC
<div><b>Affected Branch: main</b><br> </div> <b>Affected Build:&nbsp;17.11.0
preview 1.0 [34816.208.main] from&nbsp;<span><span dir=ltr><a href="https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=9428132&amp;view=results" rel="noreferrer noopener" target=_blank title="https://devdiv.visualstudio.com/devdiv/_build/results?buildid=9428132&amp;view=results">Pipelines - Run main-34816.208 (visualstudio.com)</a>&nbsp;+ <span lang=en-US>net </span><span lang=zh-CN>9.0.100-preview.4.24216.10(runtime-9.0.0-preview.4.24215.5)
</span><span lang=en-US>sdk</span>&nbsp;from&nbsp;<span><span dir=ltr><a href="https://github.com/dotnet/installer" rel="noreferrer noopener" target=_blank title="https://github.com/dotnet/installer">dotnet/installer: .NET SDK Installer (github.com)</a></span></span></span></span></b><br> <b>Affected Product Language:</b> <br> <span style="display:inline !important;">All local languages</span><br><b>Steps to reproduce:</b><br> <br><div> 1. Install maui workload using blew command in CLI </div><div>&nbsp;dotnet workload install maui </div><div>2.&nbsp;<span style="display:inline !important;">File -&gt; New -&gt; Project</span> </div><div><span style="display:inline !important;">3.&nbsp;<span style="display:inline !important;">Check if &quot;.NET MAUI Multi-Project App&quot; template is localized.</span></span> </div><div><span style="display:inline !important;"><span style="display:inline !important;"><br></span></span> </div><div><span style="display:inline !important;"><span style="display:inline !important;"><div style="box-sizing:border-box;"><span style="box-sizing:border-box;display:inline !important;"><b style="box-sizing:border-box;">Expected Result</b>:</span> </div><div style="box-sizing:border-box;"><span style="box-sizing:border-box;display:inline !important;">The project template should be localized well.</span> </div><div style="box-sizing:border-box;"><span style="box-sizing:border-box;display:inline !important;"><br style="box-sizing:border-box;"></span> </div><div style="box-sizing:border-box;"><span style="box-sizing:border-box;display:inline !important;"><b style="box-sizing:border-box;">Actual Result:</b></span> </div><div style="box-sizing:border-box;"><span style="box-sizing:border-box;display:inline !important;"><span style="box-sizing:border-box;display:inline !important;">&quot;<span style="display:inline !important;">.NET MAUI Multi-Project App</span>&quot; template is not localized.</span></span> </div><div style="box-sizing:border-box;"><span style="box-sizing:border-box;display:inline !important;"><span style="box-sizing:border-box;display:inline !important;"><br></span></span> </div><div style="box-sizing:border-box;"><span style="box-sizing:border-box;display:inline !important;"><span style="box-sizing:border-box;display:inline !important;">EN:</span></span> </div><div style="box-sizing:border-box;"><span style="box-sizing:border-box;display:inline !important;"><span style="box-sizing:border-box;display:inline !important;"><img src="https://dev.azure.com/devdiv/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_apis/wit/attachments/b0cfa1ab-f1a6-43f6-bb39-a3c847a170ae?fileName=image.png" alt=Image><br></span></span> </div>SC:</span></span> </div><div><span style="display:inline !important;"><span style="display:inline !important;"><img src="https://dev.azure.com/devdiv/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_apis/wit/attachments/f426ab81-28eb-49f9-9595-82639491b430?fileName=image.png" alt=Image><br></span></span> </div><div><span style="display:inline !important;"><span style="display:inline !important;">DE:</span></span> </div><div><span style="display:inline !important;"><span style="display:inline !important;"><img src="https://dev.azure.com/devdiv/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_apis/wit/attachments/de5d8c58-9856-41e1-9c30-5996045fe25e?fileName=image.png" alt=Image><br></span></span> </div><div><span style="display:inline !important;"><span style="display:inline !important;"><br></span></span> </div><div><span style="display:inline !important;"><span style="display:inline !important;">dotnet --info:</span></span> </div><div><span style="display:inline !important;"><span style="display:inline !important;"><span><br></span><div>.NET SDK:<br> </div><div>&nbsp;Version: &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 9.0.100-preview.4.24216.10<br> </div><div>&nbsp;Commit: &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;93213b2642<br> </div><div>&nbsp;Workload version: &nbsp;9.0.100-manifests.1ba1bb78<br> </div><div>&nbsp;MSBuild version: &nbsp; 17.11.0-preview-24216-02+367149434<br> </div><div><br> </div><div>Runtime Environment:<br> </div><div>&nbsp;OS Name: &nbsp; &nbsp; Windows<br> </div><div>&nbsp;OS Version: &nbsp;10.0.22631<br> </div><div>&nbsp;OS Platform: Windows<br> </div><div>&nbsp;RID: &nbsp; &nbsp; &nbsp; &nbsp; win-x64<br> </div><div>&nbsp;Base Path: &nbsp; C:\Program Files\dotnet\sdk\9.0.100-preview.4.24216.10\<br> </div><div><br> </div><div>.NET workloads installed:<br> </div><div>&nbsp;[android]<br> </div><div>&nbsp; &nbsp;Installation Source: SDK 9.0.100-preview.4, VS 17.11.34816.208<br> </div><div>&nbsp; &nbsp;Manifest Version: &nbsp; &nbsp;34.99.0-preview.4.250/9.0.100-preview.4<br> </div><div>&nbsp; &nbsp;Manifest Path: &nbsp; &nbsp; &nbsp; C:\Program Files\dotnet\sdk-manifests\9.0.100-preview.4\microsoft.net.sdk.android\34.99.0-preview.4.250\WorkloadManifest.json<br> </div><div>&nbsp; &nbsp;Install Type: &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Msi<br> </div><div><br> </div><div>&nbsp;[aspire]<br> </div><div>&nbsp; &nbsp;Installation Source: SDK 9.0.100-preview.4, VS 17.11.34816.208<br> </div><div>&nbsp; &nbsp;Manifest Version: &nbsp; &nbsp;9.0.0-preview.4.24216.5/9.0.100-preview.1<br> </div><div>&nbsp; &nbsp;Manifest Path: &nbsp; &nbsp; &nbsp; C:\Program Files\dotnet\sdk-manifests\9.0.100-preview.1\microsoft.net.sdk.aspire\9.0.0-preview.4.24216.5\WorkloadManifest.json<br> </div><div>&nbsp; &nbsp;Install Type: &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Msi<br> </div><div><br> </div><div>&nbsp;[ios]<br> </div><div>&nbsp; &nbsp;Installation Source: SDK 9.0.100-preview.4, VS 17.11.34816.208<br> </div><div>&nbsp; &nbsp;Manifest Version: &nbsp; &nbsp;17.2.9473-net9-p4/9.0.100-preview.4<br> </div><div>&nbsp; &nbsp;Manifest Path: &nbsp; &nbsp; &nbsp; C:\Program Files\dotnet\sdk-manifests\9.0.100-preview.4\microsoft.net.sdk.ios\17.2.9473-net9-p4\WorkloadManifest.json<br> </div><div>&nbsp; &nbsp;Install Type: &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Msi<br> </div><div><br> </div><div>&nbsp;[maccatalyst]<br> </div><div>&nbsp; &nbsp;Installation Source: SDK 9.0.100-preview.4, VS 17.11.34816.208<br> </div><div>&nbsp; &nbsp;Manifest Version: &nbsp; &nbsp;17.2.9473-net9-p4/9.0.100-preview.4<br> </div><div>&nbsp; &nbsp;Manifest Path: &nbsp; &nbsp; &nbsp; C:\Program Files\dotnet\sdk-manifests\9.0.100-preview.4\microsoft.net.sdk.maccatalyst\17.2.9473-net9-p4\WorkloadManifest.json<br> </div><div>&nbsp; &nbsp;Install Type: &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Msi<br> </div><div><br> </div><div>&nbsp;[maui]<br> </div><div>&nbsp; &nbsp;Installation Source: SDK 9.0.100-preview.4<br> </div><div>&nbsp; &nbsp;Manifest Version: &nbsp; &nbsp;9.0.0-ci.net9.preview4.10504/9.0.100-preview.4<br> </div><div>&nbsp; &nbsp;Manifest Path: &nbsp; &nbsp; &nbsp; C:\Program Files\dotnet\sdk-manifests\9.0.100-preview.4\microsoft.net.sdk.maui\9.0.0-ci.net9.preview4.10504\WorkloadManifest.json<br> </div><div>&nbsp; &nbsp;Install Type: &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Msi<br> </div><div><br> </div><div>&nbsp;[maui-windows]<br> </div><div>&nbsp; &nbsp;Installation Source: SDK 9.0.100-preview.4, VS 17.11.34816.208<br> </div><div>&nbsp; &nbsp;Manifest Version: &nbsp; &nbsp;9.0.0-ci.net9.preview4.10504/9.0.100-preview.4<br> </div><div>&nbsp; &nbsp;Manifest Path: &nbsp; &nbsp; &nbsp; C:\Program Files\dotnet\sdk-manifests\9.0.100-preview.4\microsoft.net.sdk.maui\9.0.0-ci.net9.preview4.10504\WorkloadManifest.json<br> </div><div>&nbsp; &nbsp;Install Type: &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Msi<br> </div><div><br> </div><div><br> </div><div>Host:<br> </div><div>&nbsp; Version: &nbsp; &nbsp; &nbsp;9.0.0-preview.4.24215.5<br> </div><div>&nbsp; Architecture: x64<br> </div><div>&nbsp; Commit: &nbsp; &nbsp; &nbsp; 86a1911d7c<br> </div><div><br> </div><div>.NET SDKs installed:<br> </div><div>&nbsp; 8.0.300-preview.24203.14 [C:\Program Files\dotnet\sdk]<br> </div><div>&nbsp; 9.0.100-preview.4.24216.10 [C:\Program Files\dotnet\sdk]<br> </div><div><br> </div><div>.NET runtimes installed:<br> </div><div>&nbsp; Microsoft.AspNetCore.App 6.0.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]<br> </div><div>&nbsp; Microsoft.AspNetCore.App 7.0.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]<br> </div><div>&nbsp; Microsoft.AspNetCore.App 8.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]<br> </div><div>&nbsp; Microsoft.AspNetCore.App 9.0.0-preview.4.24215.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]<br> </div><div>&nbsp; Microsoft.NETCore.App 6.0.27 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]<br> </div><div>&nbsp; Microsoft.NETCore.App 7.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]<br> </div><div>&nbsp; Microsoft.NETCore.App 8.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]<br> </div><div>&nbsp; Microsoft.NETCore.App 9.0.0-preview.4.24215.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]<br> </div><div>&nbsp; Microsoft.WindowsDesktop.App 6.0.27 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]<br> </div><div>&nbsp; Microsoft.WindowsDesktop.App 7.0.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]<br> </div><div>&nbsp; Microsoft.WindowsDesktop.App 8.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]<br> </div><div>&nbsp; Microsoft.WindowsDesktop.App 9.0.0-preview.4.24213.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]<br> </div><div><br> </div><div>Other architectures found:<br> </div><div>&nbsp; x86 &nbsp; [C:\Program Files (x86)\dotnet]<br> </div><div>&nbsp; &nbsp; registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]<br> </div><div><br> </div><div>Environment variables:<br> </div><div>&nbsp; Not set<br> </div><div><br> </div><div>global.json file:<br> </div><div>&nbsp; Not found<br> </div><div><br> </div><div>Learn more:<br> </div><div>&nbsp; https://aka.ms/dotnet/info<br> </div><div><br> </div><div>Download .NET:<br> </div><span>&nbsp; <a href="https://aka.ms/dotnet/download">https://aka.ms/dotnet/download</a></span><br></span></span> </div>
	
[View on AzDO](https://dev.azure.com/DevDiv/DevDiv/_workitems/edit/2034610)

**Comment by jfversluis** [comment] 2024-10-14 07:49
Duplicate of #25216

**Closed by jfversluis** 2024-10-14 07:49 UTC
Labels: t/bug, area-templates, s/triaged
