### ISSUE TITLE
RelativeLayout Crashes on Android

### ISSUE THREAD

**Issue by DeanFaizal** [dotnet/maui#3648] opened 2021-12-03 17:34 UTC
### Description

Not sure if it's not implemented yet, but RelativeLayout crashes on Android

### Steps to Reproduce

1. Create a new maui app
2. Use this XAML in a page:
`<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:cmp="clr-namespace:Microsoft.Maui.Controls.Compatibility;assembly=Microsoft.Maui.Controls"
             x:Class="MauiTestRelativeLayout.MainPage"
             BackgroundColor="{DynamicResource SecondaryColor}">    
    <cmp:RelativeLayout/>
</ContentPage>`
3. App crashes

### Version with bug

Preview 10 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android Pixel4 API30

### Did you find any workaround?

Don't use relative layout

### Relevant log output

```shell
12-03 12:31:51.992  7532  7532 D AndroidRuntime: Shutting down VM
12-03 12:31:51.995  7532  7532 E AndroidRuntime: FATAL EXCEPTION: main
12-03 12:31:51.995  7532  7532 E AndroidRuntime: Process: com.companyname.MauiTestRelativeLayout, PID: 7532
12-03 12:31:51.995  7532  7532 E AndroidRuntime: android.runtime.JavaProxyThrowable: System.Exception: Handler not found for view Microsoft.Maui.Controls.Compatibility.RelativeLayout.
12-03 12:31:51.995  7532  7532 E AndroidRuntime:    at Microsoft.Maui.HandlerExtensions.ToHandler(IElement view, IMauiContext context)
12-03 12:31:51.995  7532  7532 E AndroidRuntime:    at Microsoft.Maui.HandlerExtensions.ToNative(IElement view, IMauiContext context)
12-03 12:31:51.995  7532  7532 E AndroidRuntime:    at Microsoft.Maui.Handlers.ContentViewHandler.UpdateContent()
12-03 12:31:51.995  7532  7532 E AndroidRuntime:    at Microsoft.Maui.Handlers.ContentViewHandler.MapContent(ContentViewHandler handler, IContentView page)
12-03 12:31:51.995  7532  7532 E AndroidRuntime:    at Microsoft.Maui.PropertyMapper`2.<>c__DisplayClass5_0[[Microsoft.Maui.IContentView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Handlers.ContentViewHandler, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<Add>b__0(IElementHandler h, IElement v)
12-03 12:31:51.995  7532  7532 E AndroidRuntime:    at Microsoft.Maui.PropertyMapper.UpdatePropertyCore(String key, IElementHandler viewHandler, IElement virtualView)
12-03 12:31:51.995  7532  7532 E AndroidRuntime:    at Microsoft.Maui.PropertyMapper.UpdateProperties(IElementHandler viewHandler, IElement virtualView)
12-03 12:31:51.995  7532  7532 E AndroidRuntime:    at Microsoft.Maui.Handlers.ElementHandler.SetVirtualView(IElement view)
12-03 12:31:51.995  7532  7532 E AndroidRuntime:    at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.IContentView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Handlers.ContentViewGroup, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].SetVirtualView(IView view)
12-03 12:31:51.995  7532  7532 E AndroidRuntime:    at Microsoft.Maui.Handlers.ContentViewHandler.SetVirtualView(IView view)
12-03 12:31:51.995  7532  7532 E AndroidRuntime:    at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.IContentView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Handlers.ContentViewGroup, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].SetVirtualView(IElement view)
12-03 12:31:51.995  7532  7532 E AndroidRuntime:    at Microsoft.Maui.Controls.Element.SetHandler(IElementHandler newHandler)
12-03 12:31:51.995  7532  7532 E AndroidRuntime:    at Microsoft.Maui.Controls.Element.set_Handler(IElementHandler value)
12-03 12:31:51.995  7532  7532 E AndroidRuntime:    at Microsoft.Maui.HandlerExtensions.ToHandler(IElement view, IMauiContext context)
12-03 12:31:51.995  7532  7532 E AndroidRuntime:    at Microsoft.Maui.HandlerExtensions.ToNative(IElement view, IMauiContext context)
12-03 12:31:51.995  7532  7532 E AndroidRuntime:    at Microsoft.Maui.ContainerView.SetView(IElement view, Boolean forceRefresh)
12-03 12:31:51.995  7532  7532 E AndroidRuntime:    at Microsoft.Maui.ContainerView.set_CurrentView(IElement value)
12-03 12:31:51.995  7532  7532 E AndroidRuntime:    at Microsoft.Maui.HandlerExtensions.ToContainerView(IElement view, IMauiContext context)
12-03 12:31:51.995  7532  7532 E AndroidRuntime:    at Microsoft.Maui.Handlers.WindowHandler.MapContent(WindowHandler handler, IWindow window)
12-03 12:31:51.995  7532  7532 E AndroidRuntime:    at Microsoft.Maui.Controls.Window.MapContent(WindowHandler handler, IWindow view)
12-03 12:31:51.995  7532  7532 E AndroidRuntime:    at Microsoft.Maui.PropertyMapper`2.<>c__DisplayClass5_0[[Microsoft.Maui.IWindow, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Handlers.WindowHandler, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<Add>b__0(IElementHandler h, IElement v)
12-03 12:31:51.995  7532  7532 E AndroidRuntime:    at Microsoft.Maui.PropertyMapper.UpdatePropertyCore(String key, IElementHandler viewHandler, IElement virtualView)
12-03 12:31:51.995  7532  7532 E AndroidRuntime:    at Microsoft.Maui.PropertyMapper.UpdateProperties(IElementHandler viewHandler, IElement virtualView)
12-03 12:31:51.995  7532  7532 E AndroidRuntime:    at Microsoft.Maui.Handlers.ElementHandler.SetVirtualView(IElement view)
12-03 12:31:51.995  7532  7532 E AndroidRuntime:    at Microsoft.Maui.Controls.Element.SetHandler(IElementHandler newHandler)
12-03 12:31:51.995  7532  7532 E AndroidRuntime:    at Microsoft.Maui.Controls.Element.set_Handler(IElementHandler value)
12-03 12:31:51.995  7532  7532 E AndroidRuntime:    at Microsoft.Maui.HandlerExtensions.SetHandler(Context nativeElement, IElement element, IMauiContext context)
12-03 12:31:51.995  7532  7532 E AndroidRuntime:    at Microsoft.Maui.HandlerExtensions.SetWindowHandler(Activity activity, IWindow window, IMauiContext context)
12-03 12:31:51.995  7532  7532 E AndroidRuntime:    at Microsoft.Maui.Platform.ApplicationExtensions.CreateNativeWindow(Activity activity, IApplication application, Bundle savedInstanceState)
12-03 12:31:51.995  7532  7532 E AndroidRuntime:    at Microsoft.Maui.MauiAppCompatActivity.OnCreate(Bundle savedInstanceState)
12-03 12:31:51.995  7532  7532 E AndroidRuntime:    at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_(IntPtr jnienv, IntPtr native__this, IntPtr native_savedInstanceState)
12-03 12:31:51.995  7532  7532 E AndroidRuntime:        at crc6488302ad6e9e4df1a.MauiAppCompatActivity.n_onCreate(Native Method)
12-03 12:31:51.996  7532  7532 E AndroidRuntime:        at crc6488302ad6e9e4df1a.MauiAppCompatActivity.onCreate(MauiAppCompatActivity.java:46)
12-03 12:31:51.996  7532  7532 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:7994)
12-03 12:31:51.996  7532  7532 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:7978)
12-03 12:31:51.996  7532  7532 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
12-03 12:31:51.996  7532  7532 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
12-03 12:31:51.996  7532  7532 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
12-03 12:31:51.996  7532  7532 E AndroidRuntime:        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
12-03 12:31:51.996  7532  7532 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
12-03 12:31:51.996  7532  7532 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
12-03 12:31:51.996  7532  7532 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
12-03 12:31:51.996  7532  7532 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
12-03 12:31:51.996  7532  7532 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:223)
12-03 12:31:51.996  7532  7532 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7656)
12-03 12:31:51.996  7532  7532 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
12-03 12:31:51.996  7532  7532 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
12-03 12:31:51.996  7532  7532 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
12-03 12:31:51.998  7532  7532 W monodroid-assembly: Shared library 'liblog' not loaded, p/invoke '__android_log_print' may fail
12-03 12:31:52.000  7532  7532 I MonoDroid: UNHANDLED EXCEPTION:
12-03 12:31:52.006  7532  7532 I MonoDroid: Android.Runtime.JavaProxyThrowable: Exception of type 'Android.Runtime.JavaProxyThrowable' was thrown.
12-03 12:31:52.006  7532  7532 I MonoDroid:
12-03 12:31:52.006  7532  7532 I MonoDroid:   --- End of managed Android.Runtime.JavaProxyThrowable stack trace ---
12-03 12:31:52.006  7532  7532 I MonoDroid: android.runtime.JavaProxyThrowable: System.Exception: Handler not found for view Microsoft.Maui.Controls.Compatibility.RelativeLayout.
12-03 12:31:52.006  7532  7532 I MonoDroid:    at Microsoft.Maui.HandlerExtensions.ToHandler(IElement view, IMauiContext context)
12-03 12:31:52.006  7532  7532 I MonoDroid:    at Microsoft.Maui.HandlerExtensions.ToNative(IElement view, IMauiContext context)
12-03 12:31:52.007  7532  7532 I MonoDroid:    at Microsoft.Maui.Handlers.ContentViewHandler.UpdateContent()
12-03 12:31:52.007  7532  7532 I MonoDroid:    at Microsoft.Maui.Handlers.ContentViewHandler.MapContent(ContentViewHandler handler, IContentView page)
12-03 12:31:52.007  7532  7532 I MonoDroid:    at Microsoft.Maui.PropertyMapper`2.<>c__DisplayClass5_0[[Microsoft.Maui.IContentView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Handlers.ContentViewHandler, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<Add>b__0(IElementHandler h, IElement v)
12-03 12:31:52.007  7532  7532 I MonoDroid:    at Microsoft.Maui.PropertyMapper.UpdatePropertyCore(String key, IElementHandler viewHandler, IElement virtualView)
12-03 12:31:52.007  7532  7532 I MonoDroid:    at Microsoft.Maui.PropertyMapper.UpdateProperties(IElementHandler viewHandler, IElement virtualView)
12-03 12:31:52.007  7532  7532 I MonoDroid:    at Microsoft.Maui.Handlers.ElementHandler.SetVirtualView(IElement view)
12-03 12:31:52.007  7532  7532 I MonoDroid:    at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.IContentView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Handlers.ContentViewGroup, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].SetVirtualView(IView view)
12-03 12:31:52.007  7532  7532 I MonoDroid:    at Microsoft.Maui.Handlers.ContentViewHandler.SetVirtualView(IView view)
12-03 12:31:52.007  7532  7532 I MonoDroid:    at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.IContentView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Handlers.ContentViewGroup, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].SetVirtualView(IElement view)
12-03 12:31:52.007  7532  7532 I MonoDroid:    at Microsoft.Maui.Controls.Element.SetHandler(IElementHandler newHandler)
12-03 12:31:52.007  7532  7532 I MonoDroid:    at Microsoft.Maui.Controls.Element.set_Handler(IElementHandler value)
12-03 12:31:52.007  7532  7532 I MonoDroid:    at Microsoft.Maui.HandlerExtensions.ToHandler(IElement view, IMauiContext context)
12-03 12:31:52.007  7532  7532 I MonoDroid:    at Microsoft.Maui.HandlerExtensions.ToNative(IElement view, IMauiContext context)
12-03 12:31:52.007  7532  7532 I MonoDroid:    at Microsoft.Maui.ContainerView.SetView(IElement view, Boolean forceRefresh)
12-03 12:31:52.007  7532  7532 I MonoDroid:    at Microsoft.Maui.ContainerView.set_CurrentView(IElement value)
12-03 12:31:52.007  7532  7532 I MonoDroid:    at Microsoft.Maui.HandlerExtensions.ToContainerView(IElement view, IMauiContext context)
12-03 12:31:52.007  7532  7532 I MonoDroid:    at Microsoft.Maui.Handlers.WindowHandler.MapContent(WindowHandler handler, IWindow window)
12-03 12:31:52.007  7532  7532 I MonoDroid:    at Microsoft.Maui.Controls.Window.MapContent(WindowHandler handler, IWindow view)
12-03 12:31:52.007  7532  7532 I MonoDroid:    at Microsoft.Maui.PropertyMapper`2.<>c__DisplayClass5_0[[Microsoft.Maui.IWindow, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Handlers.WindowHandler, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<Add>b__0(IElementHandler h, IElement v)
12-03 12:31:52.007  7532  7532 I MonoDroid:    at Microsoft.Maui.PropertyMapper.UpdatePropertyCore(String key, IElementHandler viewHandler, IElement virtualView)
12-03 12:31:52.007  7532  7532 I MonoDroid:    at Microsoft.Maui.PropertyMapper.UpdateProperties(IElementHandler viewHandler, IElement virtualView)
12-03 12:31:52.007  7532  7532 I MonoDroid:    at Microsoft.Maui.Handlers.ElementHandler.SetVirtualView(IElement view)
12-03 12:31:52.008  7532  7532 I MonoDroid:    at Microsoft.Maui.Controls.Element.SetHandler(IElementHandler newHandler)
12-03 12:31:52.008  7532  7532 I MonoDroid:    at Microsoft.Maui.Controls.Element.set_Handler(IElementHandler value)
12-03 12:31:52.008  7532  7532 I MonoDroid:    at Microsoft.Maui.HandlerExtensions.SetHandler(Context nativeElement, IElement element, IMauiContext context)
12-03 12:31:52.008  7532  7532 I MonoDroid:    at Microsoft.Maui.HandlerExtensions.SetWindowHandler(Activity activity, IWindow window, IMauiContext context)
12-03 12:31:52.008  7532  7532 I MonoDroid:    at Microsoft.Maui.Platform.ApplicationExtensions.CreateNativeWindow(Activity activity, IApplication application, Bundle savedInstanceState)
12-03 12:31:52.008  7532  7532 I MonoDroid:    at Microsoft.Maui.MauiAppCompatActivity.OnCreate(Bundle savedInstanceState)
12-03 12:31:52.008  7532  7532 I MonoDroid:    at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_(IntPtr jnienv, IntPtr native__this, IntPtr native_savedInstanceState)
12-03 12:31:52.008  7532  7532 I MonoDroid:     at crc6488302ad6e9e4df1a.MauiAppCompatActivity.n_onCreate(Native Method)
12-03 12:31:52.008  7532  7532 I MonoDroid:     at crc6488302ad6e9e4df1a.MauiAppCompatActivity.onCreate(MauiAppCompatActivity.java:46)
12-03 12:31:52.008  7532  7532 I MonoDroid:     at android.app.Activity.performCreate(Activity.java:7994)
12-03 12:31:52.008  7532  7532 I MonoDroid:     at android.app.Activity.performCreate(Activity.java:7978)
12-03 12:31:52.008  7532  7532 I MonoDroid:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
12-03 12:31:52.008  7532  7532 I MonoDroid:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
12-03 12:31:52.008  7532  7532 I MonoDroid:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
12-03 12:31:52.008  7532  7532 I MonoDroid:     at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
12-03 12:31:52.009  7532  7532 I MonoDroid:     at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
12-03 12:31:52.009  7532  7532 I MonoDroid:     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
12-03 12:31:52.009  7532  7532 I MonoDroid:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
12-03 12:31:52.009  7532  7532 I MonoDroid:     at android.os.Handler.dispatchMessage(Handler.java:106)
12-03 12:31:52.009  7532  7532 I MonoDroid:     at android.os.Looper.loop(Looper.java:223)
12-03 12:31:52.009  7532  7532 I MonoDroid:     at android.app.ActivityThread.main(ActivityThread.java:7656)
12-03 12:31:52.009  7532  7532 I MonoDroid:     at java.lang.reflect.Method.invoke(Native Method)
12-03 12:31:52.009  7532  7532 I MonoDroid:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
12-03 12:31:52.009  7532  7532 I MonoDroid:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
12-03 12:31:52.009  7532  7532 I MonoDroid:
12-03 12:31:52.009  7532  7532 I MonoDroid:   --- End of managed Android.Runtime.JavaProxyThrowable stack trace ---
12-03 12:31:52.010  7532  7532 I MonoDroid: android.runtime.JavaProxyThrowable: System.Exception: Handler not found for view Microsoft.Maui.Controls.Compatibility.RelativeLayout.
12-03 12:31:52.010  7532  7532 I MonoDroid:    at Microsoft.Maui.HandlerExtensions.ToHandler(IElement view, IMauiContext context)
12-03 12:31:52.010  7532  7532 I MonoDroid:    at Microsoft.Maui.HandlerExtensions.ToNative(IElement view, IMauiContext context)
12-03 12:31:52.010  7532  7532 I MonoDroid:    at Microsoft.Maui.Handlers.ContentViewHandler.UpdateContent()
12-03 12:31:52.010  7532  7532 I MonoDroid:    at Microsoft.Maui.Handlers.ContentViewHandler.MapContent(ContentViewHandler handler, IContentView page)
12-03 12:31:52.010  7532  7532 I MonoDroid:    at Microsoft.Maui.PropertyMapper`2.<>c__DisplayClass5_0[[Microsoft.Maui.IContentView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Handlers.ContentViewHandler, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<Add>b__0(IElementHandler h, IElement v)
12-03 12:31:52.010  7532  7532 I MonoDroid:    at Microsoft.Maui.PropertyMapper.UpdatePropertyCore(String key, IElementHandler viewHandler, IElement virtualView)
12-03 12:31:52.010  7532  7532 I MonoDroid:    at Microsoft.Maui.PropertyMapper.UpdateProperties(IElementHandler viewHandler, IElement virtualView)
12-03 12:31:52.010  7532  7532 I MonoDroid:    at Microsoft.Maui.Handlers.ElementHandler.SetVirtualView(IElement view)
12-03 12:31:52.011  7532  7532 I MonoDroid:    at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.IContentView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Handlers.ContentViewGroup, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].SetVirtualView(IView view)
12-03 12:31:52.011  7532  7532 I MonoDroid:    at Microsoft.Maui.Handlers.ContentViewHandler.SetVirtualView(IView view)
12-03 12:31:52.011  7532  7532 I MonoDroid:    at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.IContentView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Handlers.ContentViewGroup, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].SetVirtualView(IElement view)
12-03 12:31:52.011  7532  7532 I MonoDroid:    at Microsoft.Maui.Controls.Element.SetHandler(IElementHandler newHandler)
12-03 12:31:52.011  7532  7532 I MonoDroid:    at Microsoft.Maui.Controls.Element.set_Handler(IElementHandler value)
12-03 12:31:52.011  7532  7532 I MonoDroid:    at Microsoft.Maui.HandlerExtensions.ToHandler(IElement view, IMauiContext context)
12-03 12:31:52.011  7532  7532 I MonoDroid:    at Microsoft.Maui.HandlerExtensions.ToNative(IElement view, IMauiContext context)
12-03 12:31:52.011  7532  7532 I MonoDroid:    at Microsoft.Maui.ContainerView.SetView(IElement view, Boolean forceRefresh)
12-03 12:31:52.011  7532  7532 I MonoDroid:    at Microsoft.Maui.ContainerView.set_CurrentView(IElement value)
12-03 12:31:52.011  7532  7532 I MonoDroid:    at Microsoft.Maui.HandlerExtensions.ToContainerView(IElement view, IMauiContext context)
12-03 12:31:52.011  7532  7532 I MonoDroid:    at Microsoft.Maui.Handlers.WindowHandler.MapContent(WindowHandler handler, IWindow window)
12-03 12:31:52.012  7532  7532 I MonoDroid:    at Microsoft.Maui.Controls.Window.MapContent(WindowHandler handler, IWindow view)
12-03 12:31:52.012  7532  7532 I MonoDroid:    at Microsoft.Maui.PropertyMapper`2.<>c__DisplayClass5_0[[Microsoft.Maui.IWindow, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Handlers.WindowHandler, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<Add>b__0(IElementHandler h, IElement v)
12-03 12:31:52.012  7532  7532 I MonoDroid:    at Microsoft.Maui.PropertyMapper.UpdatePropertyCore(String key, IElementHandler viewHandler, IElement virtualView)
12-03 12:31:52.012  7532  7532 I MonoDroid:    at Microsoft.Maui.PropertyMapper.UpdateProperties(IElementHandler viewHandler, IElement virtualView)
12-03 12:31:52.012  7532  7532 I MonoDroid:    at Microsoft.Maui.Handlers.ElementHandler.SetVirtualView(IElement view)
12-03 12:31:52.012  7532  7532 I MonoDroid:    at Microsoft.Maui.Controls.Element.SetHandler(IElementHandler newHandler)
12-03 12:31:52.012  7532  7532 I MonoDroid:    at Microsoft.Maui.Controls.Element.set_Handler(IElementHandler value)
12-03 12:31:52.012  7532  7532 I MonoDroid:    at Microsoft.Maui.HandlerExtensions.SetHandler(Context nativeElement, IElement element, IMauiContext context)
12-03 12:31:52.013  7532  7532 I MonoDroid:    at Microsoft.Maui.HandlerExtensions.SetWindowHandler(Activity activity, IWindow window, IMauiContext context)
12-03 12:31:52.013  7532  7532 I MonoDroid:    at Microsoft.Maui.Platform.ApplicationExtensions.CreateNativeWindow(Activity activity, IApplication application, Bundle savedInstanceState)
12-03 12:31:52.013  7532  7532 I MonoDroid:    at Microsoft.Maui.MauiAppCompatActivity.OnCreate(Bundle savedInstanceState)
12-03 12:31:52.013  7532  7532 I MonoDroid:    at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_(IntPtr jnienv, IntPtr native__this, IntPtr native_savedInstanceState)
12-03 12:31:52.013  7532  7532 I MonoDroid:     at crc6488302ad6e9e4df1a.MauiAppCompatActivity.n_onCreate(Native Method)
12-03 12:31:52.013  7532  7532 I MonoDroid:     at crc6488302ad6e9e4df1a.MauiAppCompatActivity.onCreate(MauiAppCompatActivity.java:46)
12-03 12:31:52.013  7532  7532 I MonoDroid:     at android.app.Activity.performCreate(Activity.java:7994)
12-03 12:31:52.013  7532  7532 I MonoDroid:     at android.app.Activity.performCreate(Activity.java:7978)
12-03 12:31:52.013  7532  7532 I MonoDroid:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
12-03 12:31:52.014  7532  7532 I MonoDroid:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
12-03 12:31:52.014  7532  7532 I MonoDroid:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
12-03 12:31:52.014  7532  7532 I MonoDroid:     at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
12-03 12:31:52.014  7532  7532 I MonoDroid:     at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
12-03 12:31:52.014  7532  7532 I MonoDroid:     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
12-03 12:31:52.014  7532  7532 I MonoDroid:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
12-03 12:31:52.014  7532  7532 I MonoDroid:     at android.os.Handler.dispatchMessage(Handler.java:106)
12-03 12:31:52.014  7532  7532 I MonoDroid:     at android.os.Looper.loop(Looper.java:223)
12-03 12:31:52.014  7532  7532 I MonoDroid:     at android.app.ActivityThread.main(ActivityThread.java:7656)
12-03 12:31:52.014  7532  7532 I MonoDroid:     at java.lang.reflect.Method.invoke(Native Method)
12-03 12:31:52.014  7532  7532 I MonoDroid:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
12-03 12:31:52.014  7532  7532 I MonoDroid:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
12-03 12:31:52.014  7532  7532 I MonoDroid:
```

**Comment by hartez** [comment] 2021-12-03 18:41
Duplicate of #3006

**Closed by hartez** 2021-12-03 18:41 UTC
Labels: t/bug, area/layout 🔲
