### ISSUE TITLE
OOTB MSIX packaging fails to include Windows SDK

### ISSUE THREAD

**Issue by jeremy-bridges** [dotnet/maui#22838] opened 2024-06-04 21:06 UTC
### Description

Our MAUI app, migrated from Xamarin.Forms cannot be installed (using MSIX) on a clean Windows 11 machine. An error about a missing package dependency is reported. The package name is not listed in the error:

![Screenshot 2024-06-04 at 2 59 06 PM](https://github.com/dotnet/maui/assets/3229453/3b93d387-f65a-47d5-a914-11f09a19db3d)

After installing the Windows SDK from the following site, our app installs correctly. 

https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/downloads

Should we specify the Windows SDK in our AppX manifest dependency list? If so, what is the package name and version? Or is this an OS or VS tooling bug as is described in prior bugs:

https://github.com/dotnet/maui/issues/21744
https://github.com/dotnet/maui/issues/17810

### Steps to Reproduce

1. Create MAUI app
2. Build MSIX package using the OOTB app manifest
3. Install on clean Windows 11 machine that doesn't have the Windows SDK tooling installed

### Version with bug

8.0.40 SR5

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Did you find any workaround?

Install Windows SDK. But, this isn't a great option for our customers.

**Comment by PureWeen** [comment] 2024-06-15 22:46
Duplicate of https://github.com/dotnet/maui/issues/21744

**Closed** 2024-06-15 22:46 UTC
Labels: t/bug, platform/windows 🪟, area-publishing
