### ISSUE TITLE
TableView: ViewCell with Picker disappears when updated (on Android)

### ISSUE THREAD

**Issue by janusw** [dotnet/maui#19321] opened 2023-12-10 10:31 UTC
### Description

When updating the `ItemsSource` of a `Picker` in a `TableView`, several cells disappear (apparently only the custom `ViewCell`s; the predefined cell types like `SwitchCell` and `EntryCell` are still visible). I only see the problem on Android, on iOS it works fine. Happens both with .NET 7 (SDK 7.0.311) and .NET 8 (SDK 8.0.100).

This is probably only one example of a whole pile of similar problems with the `TableView` on Android. I suspect that most or all of the following issues are related: #5924, #10064, #10322, #12989, #13006, #16533

Before             |  After
:-------------:|:-------------------------:
![Screenshot_20231210_105919](https://github.com/dotnet/maui/assets/484108/4da54bb7-2d20-4d24-a3b4-03179b975f0d)  |  ![Screenshot_20231210_105927](https://github.com/dotnet/maui/assets/484108/3674b7e1-ff80-4504-bc6e-7874eb6d6c6f)

### Steps to Reproduce

1. Clone the repo below (a fork of dotnet/maui-samples).
2. Check out the branch "TableView_bug_repro".
3. Open 8.0/UserInterface/Views/TableViewDemos/TableViewDemos.sln
4. Run it on an Android device (I tried it on a Samsung Galaxy S21+ with Android 14).
5. Select "Settings page".
6. Tap the button ("Click me!").
7. Observe that several cells disappear (the `Picker`, the `Button` and the custom cell in the section "Silent").

### Link to public reproduction project repository

https://github.com/janusw/maui-samples/tree/TableView_bug_repro

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 13/14

### Did you find any workaround?

explicitly setting a `HeightRequest` on the TableView seems to help

**Comment by janusw** [comment] 2023-12-10 20:15
A slight variation of the reproducer (even simpler) ...

https://github.com/janusw/maui-samples/tree/TableView_bug_repro_2

Picker with predefined items. Selecting an item makes the picker cell and the other custom cell disappear on Android (as in the original reproducer).

**Comment by PureWeen** [comment] 2023-12-12 20:27
Duplicate of #5924

**Closed by PureWeen** 2023-12-12 20:27 UTC
Labels: t/bug, platform/android 🤖, area/ListView, migration-compatibility
