### ISSUE TITLE
MAUI iOS - DrawingView inside ScrollView does not draw. Attempted drawing trigger scrolling instead of drawing. (works fine on android)

### ISSUE THREAD

**Issue by mahesh139** [dotnet/maui#21745] opened 2024-04-10 06:53 UTC
### Description

 When DrawingView is used inside scroll view, attempt to draw triggers scrolling on iOS and drawing does not work.  this works fine on android.

I am trying to migrate Xamarin Forms app to MAUI and need to replace signature pad on the form with drawing view. this is a blocker for my migration.

### Steps to Reproduce

I have provided link to reproduction repository and video with demo app.

Steps: (problem only on iOS, android works fine)
- Create Default MAUI App
-  Add community toolkit to use drawing view
- Updated MauiProgram.cs and add .UseMauiCommunityToolkit()  to builder.
- Update main page xaml to have drawing view inside scroll view, make sure there is enough content before and after drawing view to have scroll bar on the page 
- try to draw on drawing view (vertically), page scrolls instead of drawing on drawing view.

https://github.com/dotnet/maui/assets/11797119/1b451606-f780-4cb0-890d-de3ae5576de3

### Link to public reproduction project repository

https://github.com/mahesh139/MAUIDrawingView

### Version with bug

8.0.7 SR2

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Did you find any workaround?

having drawing view outside scroll view works fine but this does not solve my problem. i don't have any other work around. i would like to have one to make my Xamarin forms to MAUI migration possible.

**Comment by RoiChen001** [comment] 2024-04-10 07:29
Can repro this issue on the latest 17.10.0 Preview 3 (8.0.20).

**Comment by jfversluis** [comment] 2024-04-10 07:30
Duplicate of https://github.com/CommunityToolkit/Maui/issues/1807

**Closed by jfversluis** 2024-04-10 07:30 UTC
Labels: t/bug, s/verified, s/triaged
