### ISSUE TITLE
Keyboard prevents user from accessing bottom of page

### ISSUE THREAD

**Issue by williambuchanan2** [dotnet/maui#13380] opened 2023-02-16 04:49 UTC
### Description

When the keyboard is showing the user is unable to access the area of the page which is behind the keyboard.

For example, a page containing 10 Entry fields stacked, with a Submit button at the bottom - the user is unable to access the lower fields and the button because the keyboard is in the way and the page doesn't scroll enough to bring them into view.

The only way it is possible to fill out these fields is for the user to know that they need to minimise the keyboard each time they want to move to the next field.

Expectation is that the page scrolls to allow access to the full page when the keyboard is showing.

### Steps to Reproduce

Add the below code to a page and try to access the bottom fields:

```
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui" xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml" x:Class="PDS.App.RedSix.Views.DomTestPage" Title="DomTestPage"
             NavigationPage.HasNavigationBar="False" Shell.FlyoutBehavior="Disabled">
    <ScrollView >
        <VerticalStackLayout VerticalOptions="End">
            <Label  HorizontalOptions="Center"  Text="Add Your Team"  />
            <Label HorizontalOptions="Center" Text="Add your three emergency contacts." Margin="10"/>
            <Label  HorizontalOptions="Start"  Text="Contact 1" Margin="10"/>
            <Grid ColumnDefinitions="55,*" RowDefinitions="*" Margin="10">
                <AbsoluteLayout Grid.Row="0" Grid.Column="0">
                    <Ellipse HorizontalOptions="Start" VerticalOptions="Start" WidthRequest="45" HeightRequest="45" Margin="0, 10" StrokeThickness="2"/>
                    <Label Text="1" WidthRequest="45" HeightRequest="45" Margin="0, 10" HorizontalTextAlignment="Center"
                        VerticalTextAlignment="Center" TextColor="White"/>
                </AbsoluteLayout>
                <StackLayout Grid.Row="0" Grid.Column="1">
                    <Entry Text="{Binding Contact1Name}"  />
                    <Entry Text="{Binding Contact1Mobile}"  />
                </StackLayout>
            </Grid>
            <Label HorizontalOptions="Start"  Text="Contact 2" Margin="10"/>
            <Grid   Padding="0">
                <Grid.RowDefinitions>
                    <RowDefinition Height="*" />
                </Grid.RowDefinitions>
                <Grid.ColumnDefinitions>
                    <ColumnDefinition Width="55" />
                    <ColumnDefinition Width="*" />
                </Grid.ColumnDefinitions>
                <AbsoluteLayout Grid.Row="0" Grid.Column="0">
                    <Ellipse HorizontalOptions="Start" VerticalOptions="Start" WidthRequest="45" HeightRequest="45"
                        Margin="0, 10" StrokeThickness="2"/>
                    <Label Text="2" WidthRequest="45" HeightRequest="45" Margin="0, 10" HorizontalTextAlignment="Center"
                        VerticalTextAlignment="Center" TextColor="LightGray"/>
                </AbsoluteLayout>
                <StackLayout Grid.Row="0" Grid.Column="1">
                    <Entry Text="{Binding Contact2Name}"  />
                    <Entry Text="{Binding Contact2Mobile}"  />
                </StackLayout>
            </Grid>
            <Label  HorizontalOptions="Start"   Text="Contact 3" Margin="10"/>
            <Grid Padding="0">
                <Grid.RowDefinitions>
                    <RowDefinition Height="*" />
                </Grid.RowDefinitions>
                <Grid.ColumnDefinitions>
                    <ColumnDefinition Width="55" />
                    <ColumnDefinition Width="*" />
                </Grid.ColumnDefinitions>
                <AbsoluteLayout Grid.Row="0" Grid.Column="0">
                    <Ellipse HorizontalOptions="Start" VerticalOptions="Start" WidthRequest="45" HeightRequest="45"
                        Margin="0, 10" StrokeThickness="2"/>
                    <Label Text="3" WidthRequest="45" HeightRequest="45" Margin="0, 10"
                        HorizontalTextAlignment="Center" VerticalTextAlignment="Center" TextColor="LightGray"/>
                </AbsoluteLayout>
                <StackLayout Grid.Row="0" Grid.Column="1">
                    <Entry Text="{Binding Contact3Name}" />
                    <Entry Text="{Binding Contact3Mobile}" />
                </StackLayout>
            </Grid>
            <Button  VerticalOptions="End" Margin="0, 20" HeightRequest="50" Text="Continue" 
                Command="{Binding NextButtonPressedCommand}"/>
        </VerticalStackLayout >
    </ScrollView>
</ContentPage>
```

### Link to public reproduction project repository

?

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

Android 11 - 13, iOS 16

### Did you find any workaround?

Add a transparent frame to the bottom of the page which is the same height as the keyboard. Not great but it works.

**Comment by PureWeen** [comment] 2023-02-16 19:13
Duplicate of #4792

**Closed by PureWeen** 2023-02-16 19:13 UTC
Labels: t/bug, keyboard
