### ISSUE TITLE
Hot Reload Performance

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#13051] opened 2023-02-01 13:48 UTC
### Description

After applying quite a few changes on a detail page, navigating between pages with Hot Reload becomes slower and slower. You can get to see how your changes are applied step by step.

![issue-hotreload-layout](https://user-images.githubusercontent.com/6755973/216059480-1b024b60-9e47-42af-913b-432c3e661f56.gif)

After stop and recompile:
![issue-hotreload-layout-restart](https://user-images.githubusercontent.com/6755973/216059490-e3d307c0-6b2b-4f8b-978c-9c2a9a3ac500.gif)

If you use Hot Reload for a long time (well, around 30-45 min changing all the time is enough), in addition to deteriorating performance, it may become slower and slower until it freeze the entire UI.
![freeze](https://user-images.githubusercontent.com/6755973/216059537-51b62e79-0df2-4ca9-98b0-305ae2bf1bd9.PNG)

### Steps to Reproduce

1. Download or sync https://github.com/jsuarezruiz/netmaui-movies-app-challenge
2. Clear the detail page.
3. Copy and apply changes step by step during some time.

### Link to public reproduction project repository

https://github.com/jsuarezruiz/netmaui-movies-app-challenge

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 13

> VS bug [#1760671](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1760671)

**Comment by jsuarezruiz** [comment] 2023-03-07 13:21
Still can reproduce it with the current latest version using this sample https://github.com/jsuarezruiz/netmaui-finance-app-challenge

![xaml-reload-delay-perf](https://user-images.githubusercontent.com/6755973/223434228-8606c53c-c0f6-47e7-8274-c42699ffbaa8.gif)

Reopened issue.

**Comment by jonathanpeppers** [comment] 2023-03-14 15:56
@jsuarezruiz I found there is a memory leak unless you turn this off:

![image](https://user-images.githubusercontent.com/840039/225060941-4c3f14a3-3836-43ea-84d0-fd52c7b2b9fc.png)

It just holds onto every view forever.

I will investigate this (probably next), but I wanted to be sure it happens after we've fixed most leaks in MAUI.

**Comment by jonathanpeppers** [comment] 2023-03-14 20:02
I filed an issue for the UI Tools team: https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1772908

**Comment by jonathanpeppers** [comment] 2023-03-15 17:23
Ok, they do actually recommend turning off XAML hot reload when looking at performance/memory:

https://learn.microsoft.com/visualstudio/xaml-tools/xaml-hot-reload-impact-performance

**Comment by drasticactions** [comment] 2023-04-04 06:19
> @jsuarezruiz I found there is a memory leak unless you turn this off:
> 
> ![image](https://user-images.githubusercontent.com/840039/225060941-4c3f14a3-3836-43ea-84d0-fd52c7b2b9fc.png)
> 
> It just holds onto every view forever.
> 
> I will investigate this (probably next), but I wanted to be sure it happens after we've fixed most leaks in MAUI.

I would love to know if you could point to where you think that's happening.

As it stands right now, I'm still determining how actionable this issue is. Is there a way to create something consistently reproducible? @etvorun Is there anything you could consider as places in XET that could cause problems like this?

**Comment by jonathanpeppers** [comment] 2023-04-10 04:40
> I filed an issue for the UI Tools team: https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1772908

The work item has discussion. Just looking at memory snapshots, it showed this line holds references to views:

https://github.com/xamarin/UITools/blob/efe6bcfcf7028f26685e4b49adf84e085185a01d/HotReload/Source/Xamarin.HotReload.Xaml/VisualTreeService/VisualTree/DispatcherVisualTreeContext.cs#L86

Which would appear that this line isn't called in many situations:

https://github.com/xamarin/UITools/blob/efe6bcfcf7028f26685e4b49adf84e085185a01d/HotReload/Source/Xamarin.HotReload.Xaml/VisualTreeService/VisualTree/DispatcherVisualTreeContext.cs#L174

So, one idea might be to make it an `ISet<WeakReference>` instead of `ISet<object>` and see if that fixes it.

**Comment by drasticactions** [comment] 2023-04-10 08:50
> > I filed an issue for the UI Tools team: https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1772908
> 
> The work item has discussion. Just looking at memory snapshots, it showed this line holds references to views:

If I'm following that conversation, @etvorun says we should remove objects when MAUI removes them from its visual tree. That should be happening in the methods you linked to. If we are not removing them from that set, it's because MAUI should be sending mutation events through VisualDiagnostics. Those are either not happening or need to be reported as the same objects initially set to. 

I am debugging this now, but I'm not sure setting it to a weak reference would fix the issue, rather than mask something more fundamental with MAUI and VisualDiagnostics.

**Comment by drasticactions** [comment] 2023-04-10 09:29
Debugging your example, we're not getting the correct VisualDignostics events from MAUI to remove those items.

<img width="796" alt="スクリーンショット 2023-04-10 18 13 54" src="https://user-images.githubusercontent.com/898335/230872325-449e9eb9-795f-4c6a-9d46-0a7d1228d341.png">

When you click on "GetMonkeys", the underlying code removes and replaces the existing collectionview. We are getting VisualDignostics events to remove the items, but one of the items being called to "remove" is one of the items that was added, so it goes into a noop. Now, that item shouldn't be removed from our LVT, but it means one item in the collection is hanging around in our set. That is reflected in LVT, hence why the list keeps going up when it shouldn't...

So, yes, that is a "memory leak", but it's because MAUI is not sending the right information of when items are being loaded and unloaded, we need to fix that.

**Comment by jonathanpeppers** [comment] 2023-04-10 13:29
@drasticactions is there documentation on how this is supposed to work?

Can you point me to the existing unit tests for `VisualDignostics`? It sounds like we are missing test cases.

**Comment by drasticactions** [comment] 2023-04-10 14:00
AFAIK I don't believe so. VisualDiagnostics itself is public. The original implementation in Forms was [internal](https://github.com/xamarin/Xamarin.Forms/blob/1247c3a7383cbbaf3378e46091ae5591b3986cee/Xamarin.Forms.Core/Xaml/Diagnostics/VisualDiagnostics.cs#L32-L53) but MAUIs is public. VisualDiagnostics was written for Xamarin.Forms, before XAML Hot Reload existed.

https://github.com/dotnet/maui/blob/20e629379fea5a422e1287742b0505af8602c8be/src/Core/src/VisualDiagnostics/VisualDiagnostics.cs#L39-L69

Of note is "OnChildAdded" and "OnChildRemoved". These are, generally, invoked when items are inserted or removed from MAUIs visual tree. OnVisualTreeChanged is what XAML Hot Reload attaches to and should give us the correct additions and removals. One of the issues with this though is that it depends on us being[ dilligant and making sure items are correctly passed through these methods. ](https://github.com/search?q=repo%3Adotnet%2Fmaui%20VisualDiagnostics.OnChildAdded&type=code)

I need to debug it more, but IMO this is the source of the issue. The object being passed into VisualDiagnostics.OnChildRemoved is actually an object that, it appears, was just created. Hence the discrepancy. 

For tests, they are at: https://github.com/dotnet/maui/blob/20e629379fea5a422e1287742b0505af8602c8be/src/Controls/tests/Core.UnitTests/VisualTreeHelperTests.cs#L11

**Comment by drasticactions** [comment] 2023-04-10 14:10
FWIW, I am unsure if this is @jsuarezruiz's issue. Although there could be other places where mutations are not being sent from MAUI, and I still can't reproduce his original issue as shown in his video, based on his video my current theory is that our method of sending XAML Actions through the debugger is more at fault. Every time you navigation to and from pages, if you're going to a fresh instance of a page where you've made XAML changes, we will replay those changes back to the new instance of the page. Those changes we make via XAML Hot Reload are not "permanent" on the page. They get rerun as needed. 

You can see this if you make a change in a CollectionView or ListView with a lot of items. As you scroll and new items are added to the list, changes "pop" onto those items; Those are the XAML Actions we've stored being replayed onto those items.

Every time we communicate between the IDE and Device (for iOS and Android), that's through the Debugger. If there are a ton of actions being deployed or chatter between the IDE and device, that will slow down the app since that invokes the debugger. That could explain why it stops with time. But that's my theory right now, I can't verify nor reproduce it at the moment.

**Comment by jonathanpeppers** [comment] 2023-04-10 14:35
@drasticactions can you turn the above info into an `.md` file we can put in here somewhere:

https://github.com/dotnet/maui/tree/main/docs

I will try adding a test around changing `ItemsSource` on things -- and see if `OnVisualTreeChanged` is being called.

**Comment by drasticactions** [comment] 2023-04-11 08:28
@jonathanpeppers filed two bugs for this so far, at least for CollectionView but this is probably happening in more places that have binded item lists.

https://github.com/dotnet/maui/issues/14506
https://github.com/dotnet/maui/issues/14507

**Comment by jonathanpeppers** [comment] 2023-04-11 15:33
@drasticactions why are there different issues on each platform? Should the "Visual Diagnostics" features be implemented at the cross-platform layer for every control?

**Comment by drasticactions** [comment] 2023-04-12 02:38
> @drasticactions why are there different issues on each platform? Should the "Visual Diagnostics" features be implemented at the cross-platform layer for every control?

Great question; that's what we need to figure out, lol.

Ideally, yes. It goes in line with the work being done here; https://github.com/dotnet/maui/pull/14132. The VisualDiagnostics API is intended to announce the existence or removal of items from MAUIs Visual Tree. Still, it can be done ad-hoc, and just because something is called from, it doesn't mean it's actually tracked anywhere internally in MAUIs visual tree. Or, as the bugs I created suggest, the LogicalChildren list itself needs to be corrected too: Items are present in MAUIs Child controls that are not on screen, or are referencing objects that should have been removed.

In line with correcting how LogicalChildren are handled, we could consolidate how VisualDiagnostics is called to happen only when items are added or removed from a parent element.

**Comment by homeyf** [comment] 2023-06-12 09:28
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 1.0. Can repro on Android platform.
https://github.com/jsuarezruiz/netmaui-movies-app-challenge

**Comment by samhouts** [comment] 2023-11-09 00:44
Has this improved, or is this still an open issue?

**Comment by jonathanpeppers** [comment] 2023-11-09 03:19
From what I've still seen today (VS 17.8 previews), https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1772908 is not really solved:

* https://learn.microsoft.com/en-us/visualstudio/xaml-tools/xaml-hot-reload-impact-performance?view=vs-2022

They added a little banner/warning message if you collect a memory dump while XAML hot reload is enabled. XAML Hot Reload still has a memory leak while using it, so the performance will degrade with each Hot Reload.

**Comment by drasticactions** [comment] 2023-11-09 16:56
> From what I've still seen today (VS 17.8 previews), https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1772908 is not really solved:
> 
> * https://learn.microsoft.com/en-us/visualstudio/xaml-tools/xaml-hot-reload-impact-performance?view=vs-2022
> 
> They added a little banner/warning message if you collect a memory dump while XAML hot reload is enabled. XAML Hot Reload still has a memory leak while using it, so the performance will degrade with each Hot Reload.

Referring to your Azdo bug, I just filed a MAUI bug for the issue you found: https://github.com/dotnet/maui/issues/18657. EmptyView is not being properly cleared from a WinUI CollectionView, causing the VisualDiagnostics data sent from MAUI to be incorrect. What you saw as a memory leak was, I believe, MAUIs Visual Tree being corrupt.

**Comment by jonathanpeppers** [comment] 2023-11-09 17:31
@drasticactions if you look at the work item, I attached a `.gcdump` file and linked to problematic code in xamarin/UITools.

Would you like a pull request to fix it?

**Comment by drasticactions** [comment] 2023-11-09 18:14
> @drasticactions if you look at the work item, I attached a `.gcdump` file and linked to problematic code in xamarin/UITools.
> 
> Would you like a pull request to fix it?

You can, but it won't fix the issue.

The code you linked to in the bug was a HashSet of `elementsInVisualTree`. That is the list of items that appear in the Live Visual Tree in Visual Studio. If you looked at the UI in Visual Studio, you would have saw that the list of items inside of the collection view was always increasing when you added new items to it. What you saw as a memory leak was actually UI being used in Visual Studio. It's not leaking, that's the UI.

The reason the list is always increasing and not being freed is, I believe, the bug I just created. That leads to the wrong VisualDiagnostic information being sent to clear the items, meaning they don't get removed property. That was mentioned as a possible issue in the item.

**Comment by jonathanpeppers** [comment] 2023-11-09 18:44
@drasticactions they can *both* leak. I didn't say there are not leaks left to fix in MAUI.

I can take an application that doesn't leak, turn on XAML Hot Reload, and then it leaks. An example could be as simple as navigating back and forth with a page with only 1 `Label`.

**Comment by drasticactions** [comment] 2023-11-09 18:56
> @drasticactions they can _both_ leak. I didn't say there are not leaks left to fix in MAUI.
> 
> I can take an application that doesn't leak, turn on XAML Hot Reload, and then it leaks. An example could be as simple as navigating back and forth with a page with only 1 `Label`.

I'm not sure I follow:

`elementsInVisualTree` is the Live Visual Tree representation in the injected Hot Reload Agent code, as shown in Visual Studio in the Live Visual Tree. If you compare that list of items in that object to the list as shown in Visual Studio, it's the same. Because that's the UI of the LVT. If they don't match (As in, objects represented in Visual Studio in the Live Visual Tree are not represented in that internal app list) then that would be a leak, but your example doesn't show that. If you use items in the Live Visual Tree in VS, they are coming from that list. As my bug shows, I believe MAUI is not returning problem Visual Diagnostic information, causing items to not be pruned from that list.

Turning it into a weak set and trying to dispose items from `elementsInVisualTree` without MAUI calling for it doesn't solve the problem. That's masking issues in MAUI.

**Comment by jonathanpeppers** [comment] 2023-11-09 19:00
It sounds like there is an undocumented feature in MAUI that no one owns? Is that correct?

If there is some pattern here that controls aren't following, who knows what needs to be done and how to fix it?

We need unit tests at minimum that verify the visual tree is kept up to date correctly for every control?

**Comment by drasticactions** [comment] 2023-11-09 19:33
> It sounds like there is an undocumented feature in MAUI that no one owns? Is that correct?
> 
> If there is some pattern here that controls aren't following, who knows what needs to be done and how to fix it?
> 
> We need unit tests at minimum that verify the visual tree is kept up to date correctly for every control?

[VisualDiagnostics](https://github.com/dotnet/maui/blob/main/src/Core/src/VisualDiagnostics/VisualDiagnostics.cs#L13-L113)

This is the main API that drives sending information. It was originally introduced in [Xamarin.Forms](https://github.com/xamarin/Xamarin.Forms/pull/7474) for the original implementations of XAML Hot Reload and introduced by @StephaneDelcroix. I don't know if there is a direct "owner" over this code, but I would assume it would be him.

For this specific issue (as in, what you saw in your issue) it's not the API itself at fault I believe, but a cascading bug elsewhere. Due to the EmptyView in WinUI itself not actually being removed from the view, I think that's causing the wrong child indexes to be sent by the WinUI CollectionView to be contained. That then causes more items within the collection view to be mishandled with their indexes being wrong. That leads to items not being removed from `elementsInVisualTree` (since VisualDiagnostics is both sending wrong child indexes or not sending "ChildRemove" values at all), hence the heap number going up. If you can get similar heap values from Android and iOS running your example, that should show a consistant value that doesn't ever increase.

In terms of Unit Tests around that API, https://github.com/search?q=repo%3Adotnet%2Fmaui+VisualDiagnostics.OnChildAdded&type=code. AFAIK while it is used in some other controls like ListView and TableView for some parts of UI (due to some structure issues with how those controls work), the vast majorty should fall under Element.  IMO based on what I've seen so far, I think the issue you saw is specific to this control running on Windows.

For tests in general, I believe UITools has Component Tests around LVT items already

Also, with all this said, the handling of this API within the Hot Reload codebase could also be wrong. In general, items are added and removed from the LVT holding based strictly on the values returned from MAUI, but it's not impossible that this internal list couldn't be corrupted through other means. For your specific case listed in your Azdo item, I think my new MAUI Bug explains why it's happening, but it's not impossible for that code to not have other issues.

**Comment by jonathanpeppers** [comment] 2023-11-09 19:44
The part that is concerning to me, is you can have `NavigationPage` -> `ContentPage` -> `Label` and this also leaks when XAML Hot Reload is on.

It feels like every control on a core level hasn't implemented the pattern correctly.

**Comment by drasticactions** [comment] 2023-11-14 22:51
> The part that is concerning to me, is you can have `NavigationPage` -> `ContentPage` -> `Label` and this also leaks when XAML Hot Reload is on.
> 
> It feels like every control on a core level hasn't implemented the pattern correctly.

I would need to do more testing, but for that example, I don't believe that should be the case today. For the internal UITools `elementsInVisualTree`, so long as MAUI is sending the correct elements and their locations to the MAUI VisualDiagnostics API, the list should be pruning it correctly. At least with running NavigationPage -> ContentPage -> Label and navigating back and forth, the items are removed/added from LVT correctly and reflect that list in the app. The heap size seemed consistent for that specific object (or within the margin of error, you probably won't have a byte-for-byte consistency for adding or removing items, but it wasn't growing consistently with new LVT items as your bug does show. It was consistent with what I would expect and kept the same-ish size between navigation.)

That said, more could be done within UI Tools to expose these inconsistencies. There is code that sends debug information if the LVT list is inconsistent (Ex. You try removing an item that doesn't exist with LVT, or inside the internal XET list) that is used for debugging purposes, but could be exposed as an end user message somewhere saying something is wrong.

**Closed** 2023-11-23 01:01 UTC
Labels: t/bug, area/tooling ⚙️, s/needs-info, s/verified, s/triaged, s/no-recent-activity, s/move-to-vs-feedback, partner/hot-reload-xaml, Area: UI\Runtime\Hot Reload
