### ISSUE TITLE
Gifs not working in .NET MAUI

### ISSUE THREAD

**Issue by Vpatel541** [dotnet/maui#9186] opened 2022-08-04 13:04 UTC
### Description

When I put a gif as a source in the Image tag, the gif is not playing properly on the Android or IOS simulators. The IsAnimationPlaying set to true is not working.

### Steps to Reproduce

1. Create a new .NET MAUI project.
2. Add gif to images folder
3. Create an image tag with Source as the gif, set IsAnimationPlaying to true
4. Run simulator, gif is not playing

### Version with bug

6.0.408 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

Android 12.1 - API 32

### Did you find any workaround?

None

**Comment by jfversluis** [comment] 2022-08-04 18:11
Duplicate of #7021

**Closed by jfversluis** 2022-08-04 18:11 UTC
Labels: t/bug, area/image :framed_picture:, s/needs-verification
