### ISSUE TITLE
Application.Current.RequestedThemeChanged has not be triggered on Mac

### ISSUE THREAD

**Issue by AndrewDerain** [dotnet/maui#10055] opened 2022-09-12 05:43 UTC
### Description

Event Application.Current.RequestedThemeChanged is not be triggered on mac after I changed my mac theme.

### Steps to Reproduce

```c#
public partial class App : Application
{
    ILogger<App> Logger;  
    
      
    public App()
    {
        InitializeComponent();
        
        MainPage = new AppShell();
    
        var loggerFactory = LoggerFactory.Create(
            builder => builder
                        // add console as logging target
                        .AddConsole()
                        // add debug output as logging target
                        .AddDebug()
                        // set minimum level to log
                        .SetMinimumLevel(LogLevel.Debug)
        );
  
        Logger = loggerFactory.CreateLogger<App>();
  
        Current.RequestedThemeChanged += Current_RequestedThemeChanged;
    }

    private void Current_RequestedThemeChanged(object sender, AppThemeChangedEventArgs e)
    {
        Console.WriteLine("Hi");
        Logger.LogInformation("Info message");
    }
}

```

The method has never been called after i changed my mac's theme.
I Debug with my MAC.

### Link to public reproduction project repository

NA

### Version with bug

6.0.408

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

macOS 12.5.1

**Comment by mattleibow** [comment] 2022-10-31 16:54
Is this a duplicate of #10310

**Comment by jsuarezruiz** [comment] 2022-11-08 10:37
Tested with the latest version (net7 rc2) cannot reproduce the issue. Could you attach a small sample where reproduce the issue?
![issue-themes-macos](https://user-images.githubusercontent.com/6755973/200542985-9240fc27-7cbe-4644-be37-290e9ac0fb3d.gif)

**Comment by jsuarezruiz** [comment] 2022-11-08 10:55
Found how to reproduce it!

**Closed** 2023-03-16 21:15 UTC
Labels: t/bug, platform/macOS 🍏, area/theme
