### ISSUE TITLE
Can't get BackgroundImage of ContentPage

### ISSUE THREAD

**Issue by HobDev** [dotnet/maui#4773] opened 2022-02-18 11:03 UTC
### Description

Can't Get BackgroundImage of ContentPage, although I set it in XAML  `BackgroundImageSource="background.svg"` and C# `BackgroundImageSource = "background.svg";`.  background.svg is an svg image in the `Resources\Images\` folder. 

[BugSample.zip](https://github.com/dotnet/maui/files/8096334/BugSample.zip)

### Steps to Reproduce

Run the repo project. 

### Version with bug

Preview 13 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

iOS 15.2, Android 11

### Did you find any workaround?

There was a workaround in Xamarin.Forms by settings First Child of a top level Grid as an Image.  But this does not work in Maui.

**Comment by jsuarezruiz** [comment] 2022-02-21 09:06
Will be implemented in P14: https://github.com/dotnet/maui/pull/3396

**Comment by v-xiaofchen** [comment] 2022-02-25 06:21
Verified repro with Android 11 and the above project. Also can not get BackgroundImage of ContentPage;
![Picture11](https://user-images.githubusercontent.com/99376012/155664828-61d51a0e-ff2f-4839-9e1c-40cef5a181ea.png)

**Comment by kristinx0211** [comment] 2022-04-21 08:16
Thank you for your report. We have determined that this issue is the same as or very similar to issue #2966.

**Comment by samhouts** [comment] 2022-04-29 01:14
Duplicate of #2966

**Closed by samhouts** 2022-04-29 01:14 UTC
Labels: t/bug, area/controls 🎮, s/verified, control-pages
