### ISSUE TITLE
[Windows] Images are not rendered if the extension is not specified

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#3459] opened 2021-11-19 11:27 UTC
### Description

In .NET MAUI the images are not rendered if the extension is not specified while the same works on Xamarin.Forms.

### Steps to Reproduce

1. Create a .NET MAUI App
2. Add an image. For example: icon.png
3. <Image Source="icon" /> will not render. The same works on Windows.

### Version with bug

Preview 10 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows App SDK 17134

### Did you find any workaround?

Set the image extension

**Comment by Amir-Care** [comment] 2022-03-01 03:02
Repro on VS 17.2.0 Preview 2.0 [32208.484.main]
Sample project
[MauiApp8.zip](https://github.com/dotnet/maui/files/8158469/MauiApp8.zip)

**Comment by mattleibow** [comment] 2022-03-22 20:48
This is because our checks to detect the image on windows assumes the full filename was specified.

We can potentially do a fuzzy search for common extensions to try locate the image.

**Comment by Redth** [comment] 2022-04-25 15:29
I think specifying the extension is the expected behavior for now, the only thing we might want to consider in NET7 is that .svg's will be .png's and that might not be obvious to everyone.

**Comment by mattleibow** [comment] 2022-11-10 20:29
Closing this as we don't really want to do this as it may cause confusion. Extensions are important and using them reduces issues later on. The only platform that does not is Android and that is 1 of 4.

**Closed by mattleibow** 2022-11-10 20:29 UTC
Labels: t/enhancement ☀️, platform/windows 🪟, area/image :framed_picture:, s/verified
