### ISSUE TITLE
[iOS] Border often has wrong initial bounds

### ISSUE THREAD

**Issue by borrmann** [dotnet/maui#23494] opened 2024-07-09 07:45 UTC
### Description

reopening issue https://github.com/dotnet/maui/issues/20381

### Link to public reproduction project repository

https://github.com/borrmann/BorderDrawingIssue

### Version with bug

8.0.61 SR6.1

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.14

### Affected platforms

iOS

### Did you find any workaround?

no

**Comment by jonmdev** [comment] 2024-07-10 03:38
What you are seeing is a combination of these two bugs:

https://github.com/dotnet/maui/issues/18204

https://github.com/dotnet/maui/issues/23070

You can solve the animation which is the main problem with the NotAnimatedBorderHandler implementation in the first bug thread.

The other has no solution yet.

**Comment by albyrock87** [comment] 2024-07-13 16:06
@borrmann the animation issue fix has been released in the latest SR

**Comment by IeuanWalker** [comment] 2024-07-15 18:37
@albyrock87 I'm experiencing this in the latest version, 8.0.70

**Comment by jonmdev** [comment] 2024-07-16 02:04
@albyrock87  re: the animation bug I think you should have used the approach I wrote here rather than just removing it from one layer:

```
using Microsoft.Maui.Handlers;
using Microsoft.Maui.Platform;

#if IOS
using UIKit;
using ContentView = Microsoft.Maui.Platform.ContentView;
using Foundation;
using CoreAnimation;
#endif 

namespace iOSBorderShadowAnimationBug {

    //TEMP BUG FIX FOR: https://github.com/dotnet/maui/issues/18204
    public class NotAnimatedBorderHandler : BorderHandler {

#if IOS
        private class BorderContentView : ContentView {
            public override void LayoutSubviews() {

                Layer.RemoveAllAnimations();

                if (Layer.Sublayers != null) {

                    for (int i=0; i < Layer.Sublayers.Count(); i++) {
                        Layer.Sublayers[i].RemoveAllAnimations();
                    }
                }
                
                base.LayoutSubviews();
            }

        }

        protected override ContentView CreatePlatformView() {
            _ = VirtualView ?? throw new InvalidOperationException($"{nameof(VirtualView)} must be set to create a {nameof(ContentView)}");
            _ = MauiContext ?? throw new InvalidOperationException($"{nameof(MauiContext)} cannot be null");

            return new BorderContentView {
                CrossPlatformLayout = VirtualView
            };
        }
#endif
    }
}
```

I don't know much about iOS animations and my hat is off to you for coming up with the solution, but this removes animations from everything in case it is a multilayer element. I would be suprprised if anyone had any more animations after that.

**Comment by maonaoda** [comment] 2024-07-16 09:27
@jonmdev 
Nice ideal, It fixed #23620 
This means that https://github.com/dotnet/maui/pull/23156 is ​​still insufficient.

**Comment by albyrock87** [comment] 2024-07-17 07:01
@jonmdev my understanding is that the remaining 1 frame issue is due to the change on `IsVisible`.

I think it might be due to the order of changes.
Probably the visibility of the layer is changing before applying the changes to the background.

**Comment by maonaoda** [comment] 2024-07-17 07:04
Yes, that is `IsVisible` like #23620

**Comment by jonmdev** [comment] 2024-07-17 07:12
> @jonmdev my understanding is that the remaining 1 frame issue is due to the change on `IsVisible`.
> 
> I think it might be due to the order of changes. Probably the visibility of the layer is changing before applying the changes to the background.

Unfortunately it occurs not just when isVisible is toggled. It happens constantly in my real app all over the place. Using IsVisible is just the easiest way I found to reproduce it.

**Comment by PureWeen** [comment] 2024-08-09 22:20
@Zhanglirong-Winnie can you verify which .NET 8 version of MAUI this broke on

**Comment by Zhanglirong-Winnie** [comment] 2024-08-12 10:32
> @Zhanglirong-Winnie can you verify which .NET 8 version of MAUI this broke on

Hi, @PureWeen 
This issue started to occur with 8.0.20, and worked fine with 8.0.14.

**Comment by karthikraja-arumugam** [comment] 2024-09-19 14:30
The issue is not replicated with 8.0.90, can you test with latest version?

**Closed** 2024-09-27 00:18 UTC
Labels: t/bug, platform/iOS 🍎, p/2, s/verified, area-controls-border, s/triaged, i/regression, s/try-latest-version
