### ISSUE TITLE
Could not find Android Resource..

### ISSUE THREAD

**Issue by South2AK** [dotnet/maui#19645] opened 2024-01-02 10:42 UTC
### Description

`Could not find Android Resource '@styleable/SKCanvasView'. Please update to add the missing resource.`

`Could not find Android Resource '@styleable/SKCanvasView_ignorePixelScaling'. Please update @(AndroidResource) to add the missing resource.`

Debugging works every second time (when the error occurs and I Debug again it works 
Building a project works also
Rebuilding doesn´t work anymore at all

I already deleted the Bin / Obj Folders, cleaned the project but nothing worked.

I also did uninstsall SkiaSharp from Nuget Packager to see if there is any difference but to no avail.
 

### Version with bug

8.0.3

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

Android

**Comment by arsovskim** [comment] 2024-01-08 14:26
I have update target framework from net6.0-android33.0 to net8.0-android34.0 and I have the same issue.
The error is: Could not find Android Resource '@styleable/SKCanvasView'. Please update @(AndroidResource) to add the missing resource.

**Comment by guypld** [comment] 2024-01-09 19:34
Also happens here.

Steps to Reproduce:
1. Create new Maui project (.net 8)
2. Add "Particle.Maui" nuget

nothing further.

**Comment by netstart188** [comment] 2024-01-16 09:09
<assembly fullname="SkiaSharp.Views.Android">
		<namespace fullname="SkiaSharp.Views.Android" />
	</assembly>

**Comment by kennykanp** [comment] 2024-02-01 16:50
I have the same error 😞:

```
Severity	Code	Description	Project	File	Line	Suppression State	Details
Error	XA8000	Could not find Android Resource '@styleable/SKCanvasView_ignorePixelScaling'. Please update @(AndroidResource) to add the missing resource.	DigSig.AppVerifier	C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.52\tools\Xamarin.Android.Common.targets	1458		
```
```
Severity	Code	Description	Project	File	Line	Suppression State	Details
Error	XA8000	Could not find Android Resource '@styleable/SKCanvasView'. Please update @(AndroidResource) to add the missing resource.	DigSig.AppVerifier	C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.52\tools\Xamarin.Android.Common.targets	1458		
```
```
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.52\tools\Xamarin.Android.Common.targets(1458,3): error XA8000: Could not find Android Resource '@styleable/SKCanvasView'. Please update @(AndroidResource) to add the missing resource.
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.52\tools\Xamarin.Android.Common.targets(1458,3): error XA8000: Could not find Android Resource '@styleable/SKCanvasView_ignorePixelScaling'. Please update @(AndroidResource) to add the missing resource.
```

**Comment by milesring** [comment] 2024-02-02 16:36
When upgrading from .NET 6 to .NET 8 on my project using outdated packages. I had to add

`<declare-styleable name='SKCanvasView'>
     <attr name='ignorePixelScaling' format='boolean'/>
</declare-styleable>`

to Platforms/Android/Resources/values/attrs.xml to get the project to build and deploy.

After updating all packages, I was getting the issue mentioned in OP. I removed this from attrs.xml and stopped getting the error.

**Comment by jbtdevgit** [comment] 2024-02-25 06:32
Still exists with 8.07 Maui..

**Comment by Ghostbird** [comment] 2024-03-11 10:25
I have this intermittently. If it happens, my solution won't build for an hour or so, and then it will start building again. There must be some caching involved, but it isn't related to the `obj` or `bin` folder, because removing those entirely doesn't change it.

**Comment by ninachen03** [comment] 2024-04-01 09:45
Verified this issue with Visual Studio 17.10.0 Preview 2 (8.0.14 &8.0.0-rc.2.9530). Can repro it
![image](https://github.com/dotnet/maui/assets/128687574/75fc8ddb-fe54-4a21-96a3-a7d8be63695a)

**Comment by RandyPJ** [comment] 2024-04-06 15:39
It still happening. I restored all nuget packages, deleted bin and obj, restared VS and the app is working.

**Comment by Ghostbird** [comment] 2024-04-10 07:15
Sometimes running `dotnet clean` (which doesn't clean everything) helps me resolve this error when it occurs.

**Comment by samirgcofficial** [comment] 2024-04-29 11:02
Updating the <PackageReference Include="LiveChartsCore.SkiaSharpView.Maui" Version="2.0.0-rc2" />fixed the issue

**Comment by Flaszlo1** [comment] 2024-05-10 22:46
It seems, if you install this package:
SkiaSharp.Views.Maui.Controls.Compatibility, solves the problem.

**Comment by Code-King** [comment] 2024-07-03 09:41
Install All SkiaSharp Packages 
![image](https://github.com/dotnet/maui/assets/5694263/2f63d9da-84c3-4362-8e6f-10431905cc58)

**Comment by samhouts** [comment] 2024-07-16 17:21
@dellis1972 Can you please take a look? Thanks!

**Comment by dellis1972** [comment] 2024-07-16 18:28
So this error is occuring because we are trying to upgrade assemblies which used the old (pre .net 8) resource designer system to the newer system. It seems the SkiaSharp.Views 2.88.x packages still use the old system. the newer preview versions have been upgraded it seems which is why adding a PackageReference to the newer SkiaSharp.Views package fixes the issue. 

I will investigate this issue to see if I can figure out why our upgrade system is not working. I do remember there were some corner cases where this would happen. 

This kind of error will disappear as the eco system moves towards .net 8+.

If people are interested in the new Resource system for android please take a look at https://devblogs.microsoft.com/dotnet/android-resource-designer-dotnet-8/.

**Comment by dellis1972** [comment] 2024-07-16 22:49
So SkiaSharp.Views 2.88.3 is missing the .aar file which contains the resources required. Users should be using the 2.88.8 or above verison which does contain it.

```
ls .nuget/packages/skiasharp.views/2.88.3/lib/net6.0-android30.0/
SkiaSharp.Views.Android.dll	SkiaSharp.Views.Android.pdb	SkiaSharp.Views.Android.xml
dean@deans-MacBook-Pro maui19645 % ls .nuget/packages/skiasharp.views/2.88.8/lib/net6.0-android30.0/
SkiaSharp.Views.Android.aar	SkiaSharp.Views.Android.pdb
SkiaSharp.Views.Android.dll	SkiaSharp.Views.Android.xml
```

There isn't much we can do if the .aar file is not there. The old system of embedding resources (which 2.88.3 uses) is no longer supported in .net 8.

**Comment by dellis1972** [comment] 2024-07-17 00:02
The work around is to add

`<PackageReference Include="SkiaSharp.Views" Version="2.88.8" />`

This package contains the .aar file

**Comment by dellis1972** [comment] 2024-07-17 07:43
For people maintaining (or using) third party NuGet packages. Raise issues with the maintainers to bump their dependencies to SkiaSharp.views 288.8 in order to maintain compatability with .net 8 and beyond.

**Comment by dellis1972** [comment] 2024-07-17 08:04
For those that cannot upgrade you can add the following to `Platforms/Android/Resources/values/attrs.xml` 

```xml
<resources>
    <declare-styleable name='SKCanvasView'>
        <attr name='ignorePixelScaling' format='boolean'/>
    </declare-styleable>
</resources>
```

**Comment by dellis1972** [comment] 2024-07-17 18:14
@samhouts this is an issue upstream with an older SkiaSharp.Views. I'm not sure what the best thing to do is here, should we close this issue as I'm not sure its something we can fix, since SkiaSharp.Views 2.88.3 shipped without the required .aar file.

**Comment by samhouts** [comment] 2024-07-18 00:44
Thanks, @dellis1972! Yes, we will close this issue, as there is a suitable workaround and no further work for this team to do.

**Closed by samhouts** 2024-07-18 00:44 UTC
Labels: t/bug, area-single-project, platform/android 🤖, s/verified, s/triaged, partner/android, external

**Comment by Ghostbird** [comment] 2024-07-18 12:21
How does any of this relate to my issue where the build _sometimes_ fails?

**Comment by dellis1972** [comment] 2024-07-18 12:32
@Ghostbird are you getting the exact same error message when it does fail? Specifically the "Please update @(AndroidResource) to add the missing resource." message? 

There is a different issue where resources are missing that does occur on intemental builds for maui.

**Comment by Ghostbird** [comment] 2024-07-18 12:43
Thanks! Since it occurs occasionally I can't check the exact error message, but I'll assume that my issue is different from this one. It is however not on an incremental build, but on a clean build. However, once I found out that a partial clean, using `dotnet clean` allows me to bypass it, I haven't paid that much attention to the issue any more. Before I knew that, it was a big problem, as I'd be stuck for a while. It didn't disappear by itself once triggered.

**Comment by dellis1972** [comment] 2024-07-18 13:18
@Ghostbird ok its good you have a work around. If you can capture a build log and if you see it again please file and issue report. 
I tend to run with "Project System Tools" installed (https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.ProjectSystemTools2022). This allows me to just turn on build logging at the start of my day and leave it running. Then when things like this come up I have the logs available.

**Comment by Ghostbird** [comment] 2024-07-18 15:39
@dellis1972 Thanks for the advice. In my case, since I'm not running Visual Studio, the equivalent would be to add the `/flp:v=diag` argument to my build. I can imagine that extension supplies Visual Studio with a GUI option to set that build argument.

**Comment by dellis1972** [comment] 2024-07-18 15:58
> @dellis1972 Thanks for the advice. In my case, since I'm not running Visual Studio, the equivalent would be to add the `/flp:v=diag` argument to my build. I can imagine that extension supplies Visual Studio with a GUI option to set that build argument.

`-bl` is better. Since it produces a .binlog will all the diaagnostic data.

**Comment by Ghostbird** [comment] 2024-07-18 16:09
Ah, thanks!

**Comment by NabeelIQ** [comment] 2024-07-26 17:30
> It seems, if you install this package: SkiaSharp.Views.Maui.Controls.Compatibility, solves the problem.
It works, thanks
