### ISSUE TITLE
https://github.com/gorkhadk/maui_crash_reproduction

### ISSUE THREAD

**Issue by gorkhadk** [dotnet/maui#16630] opened 2023-08-09 11:16 UTC
https://github.com/gorkhadk/maui_crash_reproduction

_Originally posted by @gorkhadk in https://github.com/dotnet/maui/issues/16001#issuecomment-1671124485_

**Comment by gorkhadk** [comment] 2023-08-09 11:17
Reproduction added on original issue

**Comment by Eilon** [comment] 2023-08-09 16:20
Hi @gorkhadk , what issue is this referring to? Can you edit the original issue to add this link?

**Comment by samhouts** [comment] 2023-08-10 00:53
Duplicate of #16001

**Closed by samhouts** 2023-08-10 00:53 UTC
Labels: s/needs-info
