### ISSUE TITLE
Publish IOS App Error ZipArchive.framework/ZipArchive' contains bitcode.

### ISSUE THREAD

**Issue by rajeshsws** [dotnet/maui#18920] opened 2023-11-21 11:04 UTC
### Description

App is delivered by Transporter but get reject later on by App Store
Any help would be appreciated, Using 17.8.0 VS 2022

TMS-90482: Invalid Executable - The executable 'ProX.app/Frameworks/ZipArchive.framework/ZipArchive' contains bitcode.
Thank you 

### Version with bug

7.0.101

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.101

### Affected platforms

iOS

**Comment by jfversluis** [comment] 2023-11-22 09:28
Duplicate of #12863

**Closed by jfversluis** 2023-11-22 09:28 UTC
Labels: t/bug, platform/iOS 🍎, area/publishing 🏁
