### ISSUE TITLE
In Blazor webview after viewing image I can't delete it

### ISSUE THREAD

**Issue by MG1376** [dotnet/maui#8776] opened 2022-07-07 08:13 UTC
I use a radzen Blazor datagrid to show some image links, when user clicks the link and Image shows, then deleting the image or record fails and says 'The process cannot access the file because it is being used by another process.' 
I tested showing the image with a built in new window and also a radzen dialog service, with the same error. I also tested this with audio and video.

Only if I don't see the image or the audio/video preload='none' and I don't play the media, the file is deletable. 
I use .Net 6 with windows forms and Blazor and Microsoft.AspNetCore.Components.WebView.WindowsForms webview package.
Is this a webview problem or there is a solution?

**Comment by javiercn** [comment] 2022-07-16 16:11
@Eilon we have seen this in a different form (with CSS) I believe this is due to the way webview2 accesses the files that locks them in place.

**Comment by Eilon** [comment] 2022-07-18 16:08
@javiercn oh that issue? Certainly could be. Do you have a link?

**Comment by mkArtakMSFT** [comment] 2022-07-18 16:22
Thanks for contacting us. This is a dupe of https://github.com/dotnet/maui/issues/7479

**Closed by mkArtakMSFT** 2022-07-18 16:22 UTC
Labels: area/blazor 🕸️, s/needs-repro
