### ISSUE TITLE
Shell: Flyout menu items are missing in MAUI windows

### ISSUE THREAD

**Issue by deviprasad987** [dotnet/maui#9103] opened 2022-08-01 09:52 UTC
### Description

I am working with App Shell Menu Flyout to display menu items, but the menu items are missing when open flyout in Windows

### Steps to Reproduce

Step 1: Created the .NET MAUI application and Create a page with Shell to display the menu flyout below is the code.

`<FlyoutItem FlyoutDisplayOptions="AsMultipleItems">
<ShellContent Title="Home" 
                  Icon="icon_home.png">
        <views:HomePage/>
    </ShellContent>
    <ShellContent Title="System Status" 
                  Icon="menu_icon_sysstatus.png">
        <views:SystemStatusPage/>
    </ShellContent>
    <ShellContent Title="System Setup" 
                  Icon="menu_icon_syssetup.png">
        <views:SystemSetupPage/>
    </ShellContent>
    <ShellContent Title="Settings" 
                  Icon="menu_icon_settings.png">
        <views:SettingsPage/>
    </ShellContent>
</FlyoutItem>`

Step 2: When I run the application in windows For the first time when flyout menu it is showing all the menu items and Home Page as selected one as below Image.
<img width="186" alt="menu1" src="https://user-images.githubusercontent.com/105635699/182121227-2ace2e7a-ed8b-40b5-8856-4c187f6736ef.PNG">

Step 3: After that when I select System Status Menu Item it is not showing Settings and About Menu Items
<img width="187" alt="menu2" src="https://user-images.githubusercontent.com/105635699/182121284-21389229-d514-4c66-9a16-887074808067.PNG">

Or please follow the below

1. Clone the repro project https://github.com/deviprasad987/ShellPOC.git
2. The repro project is basically a new project MAUI created by VS2022 preview.
3. Run it on Windows and click on Menu Button then Flyout will open with all the menu items and the first page as selected.
4. Click on the menu icon and select second menu item from the menu list and agin click on menu icon to open flyout all the menu item are not showing.

### Version with bug

6.0.408 (current)

### Last version that worked well

6.0.400

### Affected platforms

Windows

### Affected platform versions

Windows 10 Pro 19043.1826

### Did you find any workaround?

No

**Comment by pierre01** [comment] 2022-08-02 07:53
I looked at your code sample, all the flyout items ShellContent are pointing to the MainPage.
The Shell might get confused because you have many menu items pointing to the same route.
Can you make sure all the shell menu items have a unique path?
In your example with the screenshots, are the pages all different?

**Comment by deviprasad987** [comment] 2022-08-08 09:53
@pierre01 Yes, If I am pointing to different pages with routes also getting the same problem.

**Comment by deviprasad987** [comment] 2022-11-18 12:53
Any update on this issue

**Comment by PureWeen** [comment] 2022-11-30 20:33
Duplicate of #11522

**Comment by PureWeen** [comment] 2022-11-30 20:34
@deviprasad987 this should be fixed once we bump to 1.2 of WinAppSDK (next service release)

You can find a project here where you can update yourself to test
https://github.com/dotnet/maui/issues/8834#issuecomment-1286137524

**Closed by PureWeen** 2022-11-30 20:33 UTC
Labels: t/bug, area/shell 🐢
