### ISSUE TITLE
Keyboard covers the editor Still exist

### ISSUE THREAD

**Issue by xwang-888** [dotnet/maui#9171] opened 2022-08-03 16:15 UTC
### Description

Keyboard covers the editor. The editor does not scroll above the keyboard when in focus.
I have updated to the latest version, but this problem still exists.

This is the video when an error occurs
https://user-images.githubusercontent.com/56998197/182655627-3198facf-eec8-402b-94c9-590b799262a3.mp4

<img width="1424" alt="截屏2022-08-04 上午12 03 38" src="https://user-images.githubusercontent.com/56998197/182655980-76061e73-1534-49aa-834a-632b4b1232c8.png">

### Steps to Reproduce

This is my debugging video.

https://user-images.githubusercontent.com/56998197/182658010-1a4f0fff-0561-42f6-b18e-6f221b231b51.mp4

### Version with bug

6.0.408 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

ios15.5

**Comment by valdetero** [comment] 2022-08-03 20:27
I also have this issue too.

**Comment by EricChenZW** [comment] 2022-08-04 09:12
I also have this issue too. This problem has a serious impact on me.

**Comment by HobDev** [comment] 2022-08-04 11:42
Duplicate of  #4792

**Comment by angelru** [comment] 2022-08-04 12:31
I also have this issue too

**Comment by jfversluis** [comment] 2022-08-04 18:18
Duplicate of #4792

**Closed by jfversluis** 2022-08-04 18:18 UTC
Labels: t/bug, s/needs-verification

**Comment by xwang-888** [comment] 2022-08-05 00:36
> Duplicate of #4792

Is this fixed in the next release?
