### ISSUE TITLE
Cannot Upload MAUI Archive to Apple App Store

### ISSUE THREAD

**Issue by speschka** [dotnet/maui#9507] opened 2022-08-17 22:26 UTC
### Description

I've been following the documentation here: https://docs.microsoft.com/en-us/dotnet/maui/ios/deployment/overview to create an archive of my MAUI app for iOS.  That part worked.  When it was done, I opened Xcode on my Mac and the archive it created shows up in the Xcode Organizer window.  That part is all good.

I went through the process to upload the file using App Connect as described here:  https://help.apple.com/xcode/mac/current/#/dev442d7f2ca.  I get through the process and start the upload, and the upload ends up failing with the error message "Invalid Bundle Structure".  Hopefully you can see the image pasted here:

![AppStoreUploadError2](https://user-images.githubusercontent.com/6234543/185253527-4795cdcf-2fa1-4234-abf2-cd5f805c7ca0.png)

When I got this error the first time, I tried doing the upload again and unchecked the option to include symbols.  I still get the same error message. Between this error, and the other bug I previously opened here:  https://github.com/dotnet/maui/issues/9029, MAUI is completely dead and a non-starter for building apps.  At all.  I would like to get some sort of statement from someone on the PM team regarding how these issues are going to be addressed.  We've invested a lot of time and energy building our app using MAUI and now are completely dead in the water because we did, with no apparent interest from Microsoft in getting things fixed anytime soon.

### Steps to Reproduce

I think the description is self-explanatory.  Of course, if someone had actually built a project, deployed it to a physical device, and tried uploading it to the Apple App Store at least once I would think that they would have seen these issues already.

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, I was *not* able test on other platforms

### Affected platform versions

iOS ALL

### Did you find any workaround?

Not yet.

### Relevant log output

```shell
The only "logging" can be seen in the screenshot of the error above.
```

**Comment by tom-b-iodigital** [comment] 2022-08-18 11:26
Are you sure you made a release build? I have published several maui apps to the ios app store without any problem. Also, if you use visual studio 2022 for mac the entire process is much simpler.

**Comment by speschka** [comment] 2022-08-18 16:40
Thanks, yes, I built it using a release build with the following command line:  dotnet publish -f:net6.0-ios -c:Release.  That is what was described in the online documentation here:  https://docs.microsoft.com/en-us/dotnet/maui/ios/deployment/overview, which is what I followed to get this far.

**Comment by speschka** [comment] 2022-08-18 17:10
To expand on this further...instead of trying to upload the file, I did a Validate file from Xcode.  It flagged the same error shown above for every single .DYLIB file in the archive.  I opened the .ipa file (by renaming it to .zip) and found 9 DYLIB files.  So how are we supposed to handle those types of files when distributing to the Apple app store/

**Comment by speschka** [comment] 2022-08-18 17:16
Further comment...I just found the same exact issue on github here: https://github.com/dotnet/maui/issues/8701.  Based on the comments in there and Tom's above, I'm guessing @tom-b-iodigital that you are building your archive on a Mac?  I launch the build command from Windows and it seems that might be the difference.

**Comment by tom-b-iodigital** [comment] 2022-08-18 17:23
Yes I build on Mac, and I added /p:EnableAssemblyILStripping=false to the command

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

Tom Bruyneel
Software architect
iO - Campus Antwerpen
Grotesteenweg 214 bus 9 - 2600 Berchem
T: +3232161660 - M: +32498590995
www.iodigital.com

**Comment by jfversluis** [comment] 2022-08-18 18:27
Hi there, thanks for the report! All the info is indeed in the issue you've linked (#8701) and the workaround right now is to archive the app on the Mac directly, that will make this error go away. The issue on Windows is being investigated and fixed hopefully sooner than later, thanks!

**Comment by jfversluis** [comment] 2022-08-18 18:27
Duplicate of #8701

**Closed by jfversluis** 2022-08-18 18:27 UTC
Labels: t/bug, platform/iOS 🍎, area/publishing 🏁
