### ISSUE TITLE
Items in CollectionView overlaying each other on Windows

### ISSUE THREAD

**Issue by a-einstein** [dotnet/maui#12118] opened 2022-12-14 20:27 UTC
### Description

Migrating from XamarinForms I moved to a CollectionView after having problems with the former ListView.
(Maybe more on that later.)
I also replaced a control by Stepper.

Now I have some odd behaviour with that, but only on Windows.
Items in the list are overlaying each other partially .
But that disappears as soon as I resize the window.
See the images.
![Capture1](https://user-images.githubusercontent.com/11852421/207706461-230f71ad-4198-4721-8437-34f415864609.JPG)
![Capture2](https://user-images.githubusercontent.com/11852421/207706485-66bc0ade-7d4e-4dfb-b43c-162de8f57dcd.JPG)

This does not occur on Android, so this does seem a bug.

There are numerous possible influences, as it is part of an already elaborate context.
Trying to reduce it to a smaller example is hard, so I hope you can look at it in context.
I am currently at the mentioned commit.

### Steps to Reproduce

See description.

### Link to public reproduction project repository

https://github.com/a-einstein/PortableShop/commit/bc5a5a9fc37b0b6163261ce972ac6ca1af67e4bd

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10.0.17763.0

### Did you find any workaround?

No.

### Relevant log output

```shell
N.A.
```

**Comment by samhouts** [comment] 2023-08-04 15:15
Duplicate of #10398

**Closed by samhouts** 2023-08-04 15:15 UTC
Labels: t/bug, platform/windows 🪟, area/layout 🔲, area/collectionview 📃, control-window
