### ISSUE TITLE
RightToLeft in .NET MAUI is completely messed and not functioning the same on iOS and Android

### ISSUE THREAD

**Issue by asafgo** [dotnet/maui#17096] opened 2023-08-30 07:15 UTC
### Description

Just playing around with RadekVyM  [https://github.com/RadekVyM/HamburgerMenuApp](url) and trying to convert it to RightToLeft.

On Android the GUI is working fine but on iOS it is a mess.

On debug when deleting `FlowDirection="RightToLeft"` from the root of AppShell.xaml  and set it back again then some RightToLeft is working but not for the flyout as without debug `FlowDirection="RightToLeft"` is complexly ignore.
 

### Link to public reproduction project repository

https://github.com/asafgo/HamburgerMenuApp

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Did you find any workaround?

No workaround and I have many problems with RightToLeft with .NET MAUI not functioning at all or does function on iOS and not on Android an vice versa.

**Comment by drasticactions** [comment] 2023-08-30 07:30
You have already filed the flyout issue: https://github.com/dotnet/maui/issues/17057

For the other issues you have, please make them individual issues rather than lumping them into one overall issue. The solution to your issue may end up being one PR, but making them individual issues makes it easier to keep track.

Closing as a duplicate of https://github.com/dotnet/maui/issues/17057

**Closed by drasticactions** 2023-08-30 07:30 UTC
Labels: t/bug

**Comment by asafgo** [comment] 2023-08-30 08:22
This is not duplicate as this project does not include the built in flyout.
It is based on Animations and pure RightToLeft related to views.
please reopen it.

**Comment by XamlTest** [comment] 2024-02-05 10:10
Verified on Visual Studio Enterprise 17.9 Preview 5(8.0.3). Repro on iOS 17.2, not repro on Android 14.0-API34 with below project:


iOS:
<img width="332" alt="Screenshot 2024-02-05 at 5 56 20 PM" src="https://github.com/dotnet/maui/assets/97647558/e02e139e-1916-4b07-b879-1be715cb9215">

Android:
<img width="332" alt="Screenshot 2024-02-05 at 6 02 27 PM" src="https://github.com/dotnet/maui/assets/97647558/03b77519-de91-4a83-8307-153900b4e925">
