### ISSUE TITLE
Suggest alternative actions when MAUI Templates are not installed with VS 2022 Preview 6.0

### ISSUE THREAD

**Issue by Tonur** [dotnet/maui#7185] opened 2022-05-14 12:33 UTC
### Description

Originally requested in dotnet/AspNetCore.Docs as issue [#25794](https://github.com/dotnet/AspNetCore.Docs/issues/25794).

During the [MAUI Blazor docs tutorial](https://docs.microsoft.com/en-us/aspnet/core/blazor/hybrid/tutorials/maui?view=aspnetcore-6.0), I could not follow the steps, as I did not have the templates installed in Visual Studio 2022 Preview 6.0.

![image](https://user-images.githubusercontent.com/15033328/166658401-22b1e5c4-66a2-4e9c-8b02-78fe124feaa3.png)

After several installations and uninstallations of Visual Studio 2022 Preview 6.0 the MAUI templates still did not show up in the "New Project" screen, and I was totally lost.

![image](https://user-images.githubusercontent.com/15033328/166658531-f20faf20-7ebd-42df-8f99-6e31a30a0e70.png)

I found a solution where I queried the `dotnet new --search MAUI`, and found a dotnet template package that included these templates mentioned in the tutorial.
![image](https://user-images.githubusercontent.com/15033328/166657145-8b29923e-49ec-4c1a-9352-b39be0c92289.png)

My suggestion is that the tutorial could mention that the MAUI Templates are aquireable with the `dotnet new -i Microsoft.Maui.Templates` command.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e66171ce-7dca-bf91-36be-f02e38c00678
* Version Independent ID: e66171ce-7dca-bf91-36be-f02e38c00678
* Content: [Build a .NET MAUI Blazor app](https://docs.microsoft.com/en-us/aspnet/core/blazor/hybrid/tutorials/maui?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/hybrid/tutorials/maui.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/hybrid/tutorials/maui.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

### Public API Changes

Not an API request

### Intended Use-Case
I want to be able to follow the tutorial outlined in the following docs: https://docs.microsoft.com/en-us/aspnet/core/blazor/hybrid/tutorials/maui?view=aspnetcore-6.0
My suggestion is that the tutorial could mention that the MAUI Templates are aquireable with the `dotnet new -i Microsoft.Maui.Templates` command.

**Comment by Tonur** [comment] 2022-05-14 12:33
cc: @guardrex https://github.com/dotnet/AspNetCore.Docs/issues/25794

**Comment by guardrex** [comment] 2022-05-14 14:09
Thanks for opening here @Tonur. The PU will remark on what may have happened and how to fix it or investigate further.

> My suggestion is that the tutorial could mention that ...

That's not the best approach given that the tutorial is entirely based on VS, and the project templates should be present. I think after the root cause is known and resolved that the tutorial won't require an update.

**Comment by tomrus88** [comment] 2022-05-14 22:12
> I think after the root cause is known and resolved that the tutorial won't require an update.
My MAUI templates disappear from VS after I install any of .NET 7 SDK previews.

**Comment by bitobrian** [comment] 2022-05-24 02:13
Same issue on latest preview. Running mentioned templates install on dotnet cli brings them back in VS. 

VS Version 17.3.0 Preview 1.1
I also have .NET 7 sdk preview installed.

**Comment by LoRdPMN** [comment] 2022-05-25 15:16
I had to do the same when upgraded to VS 17.3.0 Preview 1.1

**Comment by jfversluis** [comment] 2022-06-16 07:33
You might want to check it .NET 7 preview is installed (run `dotnet --version`), if that's the case the templates are installed but they won't show up. More info on that [here](https://github.com/dotnet/maui/wiki/Known-Issues#net-maui-templates-do-not-appear-in-visual-studio).

If the templates are not installed you can run `dotnet new -i Microsoft.Maui.Templates` to still get them. Please do not use the version that is at the end, especially not the one as advertized here because that is an older version. If you do not specify a version the newest ones will be installed.

We're investigating why the templates are not installed in some instances and will fix that. Since we have multiple issues about this I'm closing this one. Please let us know if you still can't get the templates to show up.

I think the original issue is a Docs issue actually. The author asks for alternatives when they hit a snag in the tutorial. While this of course should just work, I think we can also have something in the Docs for this to unblock people just in case.

**Closed by jfversluis** 2022-06-16 07:33 UTC
Labels: area/docs 📓, proposal/open

**Comment by Tonur** [comment] 2022-06-17 05:47
> I think the original issue is a Docs issue actually. The author asks for alternatives when they hit a snag in the tutorial. While this of course should just work, I think we can also have something in the Docs for this to unblock people just in case.

That is why I suggested it in the dotnet/AspNetCore.Docs as issue [#25794](https://github.com/dotnet/AspNetCore.Docs/issues/25794)! 
Perhaps you could talk with @guardrex to resolve this internal dispute 😅

**Comment by guardrex** [comment] 2022-06-17 07:52
@Tonur ... During preview, we typically only document workarounds for known bugs if the product unit isn't able to resolve the problem quickly. Since it's now known that this may linger for a little while, I'll add a note to the doc and remove it at GA.

**Comment by Tonur** [comment] 2022-06-17 08:04
Thank you guardrex, I appreciate you adding it. 
Sorry for comming across harsh, I meant no disrespect.
