### ISSUE TITLE
Video Splash Screen

### ISSUE THREAD

**Issue by jrahma** [dotnet/maui#2645] opened 2021-09-22 19:51 UTC
Hi,

Please provide a UI to pick and set a video file as splash screen for both iOS and Android apps.

Thanks,
Jassim

**Comment by maxkoshevoi** [comment] 2022-01-20 22:10
Starting Android 12 you can do animated splash screens: https://developer.android.com/guide/topics/ui/splash-screen#set-theme
Before that, they can only be static

**Comment by jfversluis** [comment] 2022-05-04 07:23
Duplicate of #3300

**Comment by jfversluis** [comment] 2022-05-04 07:24
Please make sure you don't open the same suggestion more than once as it will only add noise

**Closed by jfversluis** 2022-05-04 07:23 UTC
Labels: t/enhancement ☀️, area/single project ☝️
