### ISSUE TITLE
[iOS] Entry not allow to scroll when keyboard is open

### ISSUE THREAD

**Issue by BrnPer** [dotnet/maui#23580] opened 2024-07-12 13:29 UTC
### Description

Hi everyone,

I'm having an issue on iOS that when a entry is focused and the keyboard is open, I cannot scroll on the page if the entry is the first element on the UI (because it's already visible in the page).

But if I scroll to get to the last entry and click to open the keyboard, I can easily scroll through the whole page. 

If I go to the last entry and then **without closing the keyboard** go to the first entry in the page, then I can scroll.

So I really think the issue is that entries that are visible without scrolling don't allow to scroll in the page while the keyboard is open.

I attached a video showing this behavior.

https://github.com/user-attachments/assets/5f9df4e0-b4ba-4c50-b79c-5734e91577a5

### Steps to Reproduce

1. Get the repo provided and get the main branch.
2. Start the app on iOS.
3. On the main page, try to click in the first entry and try to scroll.
4. Try on the last entry and try to scroll

### Link to public reproduction project repository

https://github.com/BrnPer/maui-ios-keyboard-scroll

### Version with bug

8.0.61 SR6.1

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Did you find any workaround?

No

### Relevant log output

```shell
Don't have
```

**Comment by kevinxufei** [comment] 2024-07-15 07:22
This issue has been verified using Visual Studio 17.11.0 Preview 3.0(8.0.70 & 8.0.61 & 8.0.40). Can repro on iOS platform.

**Comment by tj-devel709** [comment] 2024-07-23 21:46
Duplicate of #19214. Issue is being worked on now! Thanks for your feedback.

**Closed by tj-devel709** 2024-07-23 21:46 UTC
Labels: t/bug, platform/iOS 🍎, s/verified, area-controls-entry, s/triaged
