### ISSUE TITLE
Brand New MAUI app will not compile or run (android) - invalid filename

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#21596] opened 2024-04-02 18:48 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Brand-New-MAUI-app-will-not-compile-or-r/10596403)._

---
\[severity:It’s more difficult to complete my work\]  
so using a template from file> new project for .net maui project, by default the OpenSans-Regular.ttf is created, but the filename is not compatible with android. so no worky. need to update the template in the next hotfix and just remove the dash out of there.

```  
Severity	Code	Description	Project	File	Line	Suppression State	Details
Error	APT0003	Invalid file name: It must contain only [^a-zA-Z0-9_.] +.	xxxMobile2	C:\dev\xxx\Resources\Fonts\OpenSans-Regular.ttf	1		

```

---
#### Feedback Bot on 2/21/2024, 10:52 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by jfversluis** [comment] 2024-04-03 08:55
Duplicate of #19489

**Closed by jfversluis** 2024-04-03 08:55 UTC
