### ISSUE TITLE
Buttons behind "Pop-Up" are handling taps in Android, which is different than Windows behavior (and Xamarin)

### ISSUE THREAD

**Issue by DP-Technology-LLC** [dotnet/maui#11663] opened 2022-11-25 17:19 UTC
### Description

I have created a "Pop-up" using a grid that takes up the entire screen with the pop-up content being in the cell that is in the middle column and middle row.  The outside columns and rows contain nothing and have a background color of #99000000.

In Xamarin Windows, Xamarin Android and Maui Windows the behavior acts as I expect.  The only objects that handle taps or clicks would be the content in the middle cell.  In Maui Android, when I tap on the cells in the outside parts of the grid the controls behind the "Pop-up" still handle the taps.

### Steps to Reproduce

In the MainPage of a new Maui App, wrap the ScrollView with a Grid, then below the ScrollView add a grid with a background color of #99000000 (to visually confirm it is there).

Run on Windows, you **will not** be able to click on the "Click Me" Counter button, as expected.

Run on Android, you **will** be able to tap on the "Click Me" Counter button.

### Link to public reproduction project repository

refer to Steps to Reproduce

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 7.1.2, Android 8.0

### Did you find any workaround?

No

**Comment by mattleibow** [comment] 2022-11-28 15:48
May be related to #9069?

**Comment by rachelkang** [comment] 2022-11-29 19:34
Duplicate of https://github.com/dotnet/maui/issues/9069

**Closed by rachelkang** 2022-11-29 19:34 UTC
Labels: t/bug, platform/android 🤖, area/controls 🎮, control-button, s/needs-repro
