### ISSUE TITLE
Entry Control in Secondary Layout Shows Text in Single Column when Keyboard Showing

### ISSUE THREAD

**Issue by BaldeGH** [dotnet/maui#9106] opened 2022-08-01 14:25 UTC
### Description

When adding an entry control on the page that is in a secondary layout, the typed text is displayed in a single column instead of across the entry control region.

See Attached [Repo](https://github.com/BaldeGH/MauiAndroidEntryKeyboardUIIssue)

### Steps to Reproduce

1. Create a default maui project
2. Add entry control under <stacklayout><stacklayout><entry /></stacklayout></stacklayout>
3. Type text with pop up default keyboard
![Screenshot_1659363624](https://user-images.githubusercontent.com/8539709/182168757-31616dd9-4339-4eda-9191-77ecafe5d6a4.png)

Attached [Repo](https://github.com/BaldeGH/MauiAndroidEntryKeyboardUIIssue)

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android simulator ( Android 11 - API30 ) / Pixel 5 (Android 12.1 - API 32)

### Did you find any workaround?

Do not add into a secondary layout control. Preventing any layout options with control

**Comment by jfversluis** [comment] 2022-08-04 18:31
You forgot to publish the code on the repo it seems :)

**Comment by BaldeGH** [comment] 2022-08-04 19:22
Doh! Sorry about that, seems like there's an issue with my environment. I manually uploaded the project in the link

**Comment by jfversluis** [comment] 2022-08-04 19:27
Yep that's what I thought, thank you! This seems a duplicate so I'll mark it like that, but thank for adding the info here. Really appreciated!

**Comment by jfversluis** [comment] 2022-08-04 19:27
Duplicate of #8232

**Closed by jfversluis** 2022-08-04 19:27 UTC
Labels: t/bug, area/controls 🎮, s/needs-attention, s/needs-verification
