### ISSUE TITLE
MauiIcon or MauiSplashScreen generated wrong color.

### ISSUE THREAD

**Issue by KSemenenko** [dotnet/maui#9443] opened 2022-08-15 16:15 UTC
### Description

I make settings like this:
```
<!-- App Icon -->
<MauiIcon Include="Resources\AppIcon\appicon.svg" ForegroundFile="Resources\AppIcon\appiconfg.svg" Color="#ED2C65" />

<!-- Splash Screen -->
<MauiSplashScreen Include="Resources\Splash\splash.svg" Color="#ED2C65" BaseSize="128,128" />
```
but as a result, the icon background color is #DA4167
<img width="332" alt="Screenshot 2022-08-15 at 18 04 25" src="https://user-images.githubusercontent.com/4385716/184673096-0b28ee01-05f8-4cc8-a9b9-fe013e6006b0.png">

Next I added screenshots, so as you can notice, the icons work strangely.

### Steps to Reproduce

use the icon background color Color="#ED2C65"
and the same color for the SplashScreen background
and use another svg that .NET for logo

### Version with bug

6.0.312

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

iOS 15

**Comment by AndreasReitberger** [comment] 2022-08-15 17:48
Following, seeing the same issue on iOS.

**Comment by KSemenenko** [comment] 2022-08-15 17:54
iPhone 13 Pro Max
![IMG_4702](https://user-images.githubusercontent.com/4385716/184688982-084e5371-4899-440d-ae44-a9636cd278d2.PNG)

**Comment by KSemenenko** [comment] 2022-08-15 17:54
iPad
![IMG_0612](https://user-images.githubusercontent.com/4385716/184689082-8c369140-e50e-413d-8a56-364e92cd066d.PNG)
![IMG_0613](https://user-images.githubusercontent.com/4385716/184689085-a88eb389-8b44-4d29-ae50-c1f3f26c265b.PNG)

**Comment by KSemenenko** [comment] 2022-08-15 17:54
Simulator
<img width="332" alt="Screenshot 2022-08-15 at 18 04 25" src="https://user-images.githubusercontent.com/4385716/184689113-192cd25a-92f2-4bd7-9925-2c01320d1dfe.png">

**Comment by KSemenenko** [comment] 2022-08-15 17:55
iPhone app icon
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/4385716/184689254-a6e26612-9793-4142-af1c-e64701ff38ec.png)

**Comment by KSemenenko** [comment] 2022-08-15 17:56
Android app icon 
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/4385716/184689305-71ec0be6-8dce-49d8-86ab-7a4167740999.png)

**Comment by jfversluis** [comment] 2022-08-16 07:50
Duplicate of #9405

**Closed by jfversluis** 2022-08-16 07:50 UTC
Labels: t/bug

**Comment by KSemenenko** [comment] 2022-08-16 14:09
@jfversluis As you can see, there are more issues than just color of icon on splash screen.
 Also app icons for android, also different icons for splash screen for iPhone and iPad and simulator. Sometimes old logo appear. Should I create separate issues or merge it into one?
