### ISSUE TITLE
[Android] Entry and KeyPress event on Enter key (hardware keyboard)

### ISSUE THREAD

**Issue by LeDahu22** [dotnet/maui#19072] opened 2023-11-28 08:42 UTC
### Description

I'm using a Honeywell handheld device which has a physical keyboard.
As MAUI Entry doesn't provide KeyPress (nor KeyUp or KeyDown) event, I'm trying to intercept these events using Android internal methods.

I lost time trying to figure out why the KeyPress event on native view wasn't firing at all, and I finally discovered I was using the wrong event). The right one that fires properly is UnhandledKeyEvent (the reason of this isn't clear either).

I have a custom NDCEntry inheriting directly from MAUI's Entry :

```cs
public NDCEntry() : base()
{
    InitializeComponent();
    
    Loaded += (s, e) =>
    {
        if (Handler?.PlatformView is TextInputLayout nativeView)
        {
            nativeView.UnhandledKeyEvent += (s, e) =>
            {
                Console.WriteLine(e.Event.KeyCode);
            };
        }
    };
}

```

Evrything is working the way I want, except for the Enter key that doesn't trigger this event.
My guess is that MAUI Entry control has a **e.Handled = true** for this specific key (allowing to trigger the navigation mechanism on the ContentPage). Thus, the event isn't propagated for this key (maybe I'm wrong though).

Could it be possible to propagate it so that we could be able to handle this specific key like others ?

I've tested this on .NET 7 and 8 with the same result.

### Steps to Reproduce

Create a MAUI Android application with .NET 7 or .NET 8

Add a ContentPage with a custom Entry with the code I provided

Use a device that has a physical keyboard and try several key, including the Enter key

No string should be shown for this specific key on the debug output.

### Version with bug

8.0.3

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 11

### Did you find any workaround?

Not yet.

**Comment by mattleibow** [comment] 2023-11-28 19:22
You can maybe try this: https://github.com/davidortinau/Plugin.Maui.KeyListener

**Comment by LeDahu22** [comment] 2023-11-29 08:42
Hi @mattleibow, I just tried it on my .NET 8 Android project with the code, and nothing seems to happen with any key 😞

**Comment by mattleibow** [comment] 2023-11-29 10:27
I see... @davidortinau where is Android? 😉 Are you anti-green bubble or whatever the words are? @PureWeen David said he used your code, are you also anti-green? 🤔

**Comment by sunilsolanki-alight** [comment] 2023-11-29 12:28
Same issue faced by me when we use Tap gesture on Stack layout and used keyboard event did not get trigger I tried AY11 tool but result is same

**Comment by kidmar** [comment] 2024-01-09 13:04
Duplicate of #13921 ??

**Comment by PureWeen** [comment] 2024-01-10 20:51
Duplicate of #13921

**Closed by PureWeen** 2024-01-10 20:51 UTC
Labels: t/enhancement ☀️, area/controls 🎮, control-entry

**Comment by LeDahu22** [comment] 2024-02-14 10:25
I can confirm that this issue has been resolved with MAUI 8 SR2, Completed event fires correctly with hardware Enter key now !
Thank you.
