### ISSUE TITLE
Incorrect layout when using a Grid with Star and Auto and a child has HeightRequest

### ISSUE THREAD

**Issue by marchev-prgs** [dotnet/maui#14494] opened 2023-04-10 15:28 UTC
### Description

I am working with maui SDK 7.0.200-preview.22628, from branch release/7.0.2xx-sr4

A Grid that has two elements inside is not getting laid our properly. The two elements are: an Entry in a Star column, and a Button in an Auto column. The Button has a HeightRequest smaller than the intrinsic size of the Entry. The end result is that the Entry is getting clipped at the bottom.

    <VerticalStackLayout>
        <Grid ColumnDefinitions="*, Auto">
            <Entry Text="qwerty" />
            <Button Grid.Column="1" HeightRequest="26" />
        </Grid>
    </VerticalStackLayout>

### Steps to Reproduce

1. Go to the repo from the link
2. Make sure you have navigated to the folder Maui\GridStarAutoIncorrectLayout
3. Run the project

Expected: 
The Entry should be fully visible, as in the picture below:
![Expected](https://user-images.githubusercontent.com/91615935/230930803-18e9ddbc-a6b5-4bb0-87aa-8b249981db1b.png)

Actual:
The Entry is not given enough height and is getting clipped at the bottom, as in the picture below:
![Actual](https://user-images.githubusercontent.com/91615935/230930931-42e9d30f-0b8f-412b-916f-4ec62f6640b7.png)

### Link to public reproduction project repository

https://github.com/telerik/ms-samples/tree/main/Maui/GridStarAutoIncorrectLayout

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

7.0 (current)

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

current versions

### Did you find any workaround?

I was not able to find any workarounds.

**Comment by hartez** [comment] 2023-04-10 17:48
Duplicate of #14296

**Comment by hartez** [comment] 2023-04-10 17:56
This is fixed in .NET 8, and is in the process of being [backported to .NET 7](https://github.com/dotnet/maui/pull/14369).

**Closed** 2023-07-26 12:23 UTC
Labels: t/bug, area/layout 🔲, partner, i/regression, layout-stack
