### ISSUE TITLE
.NET MAUI button backgroundcolor dosen't work

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#10172] opened 2022-09-16 17:52 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/NET-MAUI-bottun-backgroundcolor-dosent/10132710)._

---
As a reference example, in a new project of .NET MAUI  
Added change color of counter button.

```  
private void OnCounterClicked(object sender, EventArgs e)
{
	count++;

	if (count == 1)
		CounterBtn.Text = $"Clicked {count} time";
	else
		CounterBtn.Text = $"Clicked {count} times";

	_**CounterBtn.BackgroundColor = Colors.Green;**_　　　　

	SemanticScreenReader.Announce(CounterBtn.Text);
}
  
```

The button color changes to green when debugging.  
But it doesn't work when released on android.

---
#### Feedback Bot on 8/28/2022, 08:15 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by jfversluis** [comment] 2022-10-07 14:29
Duplicate of #10181

**Closed by jfversluis** 2022-10-07 14:29 UTC
Labels: t/bug, area/controls 🎮, control-button
