### ISSUE TITLE
Unable to find IAnimationManager for 'Microsoft.Maui.Controls [Bug] 

### ISSUE THREAD

**Issue by cakmak-serkan** [dotnet/maui#2900] opened 2021-10-10 03:10 UTC
### Steps to Reproduce
project .Net MAUI
 
1. MainPage.xaml.cs has one or more frames  
2.  Call method from MaınPage.xaml.cs constructor .
3. This method has one Animation call like ".ScaleTo"

### Expected Behavior
Move the Grid Element 
### Actual Behavior
Crush
### Basic Information
System.ArgumentException: 'Unable to find IAnimationManager for 'Microsoft.Maui.Controls.Grid'. (Parameter 'animatable')'

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by jsuarezruiz** [comment] 2021-11-08 11:53
Cannot reproduce the issue with the latest Preview, could you attach a small sample where reproduce the issue?
![issue2900](https://user-images.githubusercontent.com/6755973/140737484-1ed4461a-20ac-4047-8fac-90022e966ff9.gif)

**Comment by jsuarezruiz** [comment] 2021-11-12 10:26
Duplicated #3353. I am going to close this one to concentrate the comments and effort in 3353.

**Closed by jsuarezruiz** 2021-11-12 10:26 UTC
Labels: t/bug, area/animation 🎬, s/needs info ❓

**Comment by cakmak-serkan** [comment] 2021-11-12 10:28
> Duplicated #3353. I am going to close this one to concentrate the comments and effort in 3353.

so sorry jsuarezruiz, for my late replay. Please close this its work ok now
