### ISSUE TITLE
CollectionView EmptyView Not Displaying on Android in .NET 8

### ISSUE THREAD

**Issue by bhavanesh2001** [dotnet/maui#26741] opened 2024-12-20 05:41 UTC
### Description

The issue described in [#10819](https://github.com/dotnet/maui/issues/10819), where the EmptyView of a CollectionView does not display on Android unless a HeightRequest is set, persists in the latest stable version of .NET 8. Although this was marked as fixed in .NET 8 previews, the bug remains reproducible.

### Steps to Reproduce

1. Create a CollectionView in a .NET MAUI project.
2. Bind the ItemsSource to an empty or null collection.
3. Define an EmptyView.

Run the app on an Android device or emulator .
```xaml
 <CollectionView.EmptyView>
     <Grid>
         <Image Source="dotnet_bot.png" />
     </Grid>
 </CollectionView.EmptyView>
```

![Image](https://github.com/user-attachments/assets/c64627e3-ef9c-4360-b6f1-7662b8c78638)

```xaml
<CollectionView.EmptyView>
    <Grid Margin="0,50,0,0">
        <Image Source="dotnet_bot.png" />
    </Grid>
</CollectionView.EmptyView>
```
![Image](https://github.com/user-attachments/assets/82ef800f-5b24-415b-8da5-a2537ad8a9e4)

### Link to public reproduction project repository

https://github.com/bhavanesh2001/EmptyViewIssue

### Version with bug

8.0.93 SR9.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 14

### Did you find any workaround?

Same work around mentioned in [#10819](https://github.com/dotnet/maui/issues/10819)

### Relevant log output

```shell

```

**Comment by Ying-6** [comment] 2024-12-20 06:24
This issue has been verified using Visual Studio 17.13 preview 2 (9.0.21 & 8.0.100 & 8.0.93 & 8.0.92). Can repro this issue on Android platform.

**Comment by jfversluis** [comment] 2024-12-20 08:10
Duplicate of #22191

**Closed by jfversluis** 2024-12-20 08:10 UTC
Labels: t/bug, platform/android 🤖, s/verified, s/triaged
