### ISSUE TITLE
Implementation of multiple stack layout issue in dotnet 8 LTS MAUI

### ISSUE THREAD

**Issue by SoumyadipYT-OSS** [dotnet/maui#20947] opened 2024-03-01 17:46 UTC
### Description
![IMG_20240301_231729996](https://github.com/dotnet/maui/assets/94290293/06e4f08e-1dc0-43c8-906f-8686d1d6ec3b)

I am unable to implement two stack layouts in MAUI dotnet 8 LTS version.
The compiler shows that the property content is used more than once. What is the solution of this problem?

### Public API Changes

There is no API relation with this topic.

### Intended Use-Case

In my application I want to use a searchbar under the Stack layout design content.

**Comment by acaliaro** [comment] 2024-03-01 17:50
Add an external stacklayout, or grid

**Comment by SoumyadipYT-OSS** [comment] 2024-03-01 17:55
> Add an external stacklayout, or grid 

Is external stack layout another property?

**Comment by SoumyadipYT-OSS** [comment] 2024-03-01 18:00
> Add an external stacklayout, or grid 

Mr. Acaliaro can we implement Row definitions in Grid property?

**Comment by acaliaro** [comment] 2024-03-01 18:11
> > Add an external stacklayout, or grid
> 
> Is external stack layout another property?

You mast have only a single content as keoot content so you must use a container like a Stacklayout o r grid or a contentview that contains your two layouts

**Comment by acaliaro** [comment] 2024-03-01 18:11
> > Add an external stacklayout, or grid
> 
> Mr. Acaliaro can we implement Row definitions in Grid property?

Yes, rowdefinition is a grid’s property

**Comment by jfversluis** [comment] 2024-03-01 20:05
Duplicate of #20948

**Closed by jfversluis** 2024-03-01 20:05 UTC
Labels: proposal/open
