### ISSUE TITLE
Upgrade from 8.0.70 to 8.0.82 Apple reports apple push notifications are being used.

### ISSUE THREAD

**Issue by tpitman** [dotnet/maui#24880] opened 2024-09-23 18:46 UTC
### Description

I have a MAUI app that I have been building for iOS for some time. I have had these lines in my project file for a while now:

```
    <PackageReference Include="Microsoft.MAUI.Controls" Version="8.0.70" />
    <PackageReference Include="Microsoft.MAUI.Controls.Compatibility" Version="8.0.70" />
```
Today I changed that to:

```
    <PackageReference Include="Microsoft.MAUI.Controls" Version="8.0.82" />
    <PackageReference Include="Microsoft.MAUI.Controls.Compatibility" Version="8.0.82" />
```

When I did my build for iOS and uploaded it to Apple I got an email saying that I was now using the Apple Push Notifications functionality and didn't have the entitlement.

I am not using APN nor will I. Why would updating that version cause this? As far as I can tell nothing else changed.

### Steps to Reproduce

Upgrade from 8.0.70 to 8.0.82 and notice new APN requirement.

### Version with bug

8.0.82 SR8.2

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.70 SR7

### Affected platforms

iOS

**Comment by Timoosterbroek** [comment] 2024-09-23 19:19
I experience the same problems with my app (that doesn't use APN), only in a net8.0-ios app. It seems that the problem has been happening since the Xcode version in the pipeline was updated to 15.4.

**Comment by tpitman** [comment] 2024-09-23 19:26
I don't think mine is due to xcode 15.4 because I have been using that with 8.0.70 for a while. Mine started when I updated to 8.0.82 specifically.

**Comment by tpitman** [comment] 2024-09-23 19:37
Looks like I might be wrong about what is causing that new error. I reverted my changes back to 8.0.70, removed the obj and bin folders and built a new version for iOS. When I uploaded it I get the same warning from apple.

I realized I also added a nuget package, but that didn't register for me because that nuget package has NO dependancies and doesn't have anything to do with push notifications.

It is the Steema TeeChart nuget library.

Can someone tell me what to tell the developer so they can resolve this? As I said they don't have any dependancies, so I am not sure why it would cause this.

**Comment by jfversluis** [comment] 2024-09-24 06:58
I think its indeed unlikely that this is something that happened on our side, we probably should have heard more about this if that were the case. Try to retrace the steps that you did around the time that this error popped up. Installed any new NuGets, changed any project settings, made changes to your publishing profiles?

Looking at Steema TeeChart I wouldn't necessarily think they added this, but it's not 100% impossible. Seems like they can be found here: https://www.steema.com/product/forms

Do you have a list of plugins you're using? Or maybe post the contents of your csproj file (make sure to remove any potential sensitive data) so we can get some idea of what is going on.

**Comment by maurictg** [comment] 2024-09-24 11:42
@jfversluis We encounter this issue too at a .NET for iOS project without any NuGet or MAUI dependencies at all. We have this issue since we updated xCode in our build pipeline

**Comment by jfversluis** [comment] 2024-09-24 11:44
@maurictg can you share your csproj contents and exact version numbers of Visual Studio, workloads and Xcode you are using?

cc: @rolfbjarne does this mean anything to you?

**Comment by maurictg** [comment] 2024-09-24 12:01
> @maurictg can you share your csproj contents and exact version numbers of Visual Studio, workloads and Xcode you are using?

Workloads: `ios`, `maui-android`, `maui-ios`, `maui-tizen`
Visual Studio: I don't use VS, also not in build pipeline
XCode: `15.4`
vmImage in pipeline: `macos-14`
.NET version: `8.0.201`

App.iOS.csproj
```xml
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0-ios</TargetFramework>
		<OutputType>Exe</OutputType>
		<Nullable>enable</Nullable>
		<ImplicitUsings>true</ImplicitUsings>
		<SupportedOSPlatformVersion>11.0</SupportedOSPlatformVersion>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<IpaMetadata>Info.plist</IpaMetadata>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
	  <BuildIpa>True</BuildIpa>
	  <IpaPackageName>App.iOS</IpaPackageName>
	  <IpaIncludeArtwork>True</IpaIncludeArtwork>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
	  <BuildIpa>True</BuildIpa>
	  <IpaPackageName>App.iOS</IpaPackageName>
	  <IpaIncludeArtwork>True</IpaIncludeArtwork>
	</PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="..\App.Shared\App.Shared.csproj" />
	</ItemGroup>
	<ItemGroup>
	  <AvailableItemName Remove="iTunesArtwork" />
	</ItemGroup>
	<ItemGroup>
	  <ITunesArtwork Include="iTunesArtwork" />
	  <ITunesArtwork Include="iTunesArtwork@2x" />
	</ItemGroup>
</Project>
```

App.Shared.csproj
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFramework>net8.0</TargetFramework>
	  <LangVersion>latest</LangVersion>

	  <!-- Nuspec -->
	  <PackageId>App.Shared</PackageId>
	  <PackageTags>App Shared</PackageTags>
	  <PackageProjectUrl>...omitted...</PackageProjectUrl>

	  <AssemblyName>App.Shared</AssemblyName>
	  <Title>App Shared</Title>
	  <Description>...omitted...</Description>
	  <Company>...omitted...</Company>
	  <Authors>...omitted...</Authors>

	  <!-- SourceLink -->
	  <!-- Publish the repository URL in the built .nupkg (in the NuSpec <Repository> element) -->
	  <PublishRepositoryUrl>true</PublishRepositoryUrl>
	  <!-- Embed source files that are not tracked by the source control manager in the PDB -->
	  <EmbedUntrackedSources>true</EmbedUntrackedSources>
	  <!-- Build symbol package (.snupkg) to distribute the PDB containing Source Link -->
	  <IncludeSymbols>true</IncludeSymbols>
	  <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>
</Project>
```

**Comment by jfversluis** [comment] 2024-09-24 14:18
@tpitman am I correct to think that this is a .NET for iOS app not even using MAUI?

Do you have an entitlements.plist file at all? Could you share what is in there?

(Or other people suffering from this)

Might be https://github.com/xamarin/xamarin-macios/issues/21002?

**Comment by maictoa** [comment] 2024-09-24 15:14
Our app is built with Maui .Net 8 and VS 2022 and we am receiving the same email from Apple every time we submit a new version. We don't have an entitlements.plist on the project and the app doesn't use APN. 

The only recent changes made was to update all NuGet Packages listed below to the latest version with the exception of Microsoft.Maui.Controls which was upgrade from 8.0.40 to 8.0.82

<ItemGroup>
  <PackageReference Include="BarcodeScanning.Native.Maui" Version="1.5.7" />
  <PackageReference Include="Microsoft.Maui.Controls" Version="8.0.82" />
  <PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="8.0.82" />
	<PackageReference Include="CommunityToolkit.Maui" Version="9.0.3" />
	<PackageReference Include="CommunityToolkit.Maui.Core" Version="9.0.3" />
	<PackageReference Include="CommunityToolkit.Mvvm" Version="8.3.2" />
	<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="8.0.0" />
	<PackageReference Include="sqlite-net-pcl" Version="1.9.172" />
	<PackageReference Include="SQLitePCLRaw.bundle_green" Version="2.1.10" />
	<PackageReference Include="SQLitePCLRaw.provider.dynamic_cdecl" Version="2.1.10" />        
  <PackageReference Include="SQLitePCLRaw.core" Version="2.1.10" />    
  <PackageReference Include="SQLitePCLRaw.provider.sqlite3" Version="2.1.10" />
</ItemGroup>

**Comment by tpitman** [comment] 2024-09-24 15:32
@jfversluis Ours is also MAUI. I have been working on a building new versions for the last many months.

I never had this issue until just the other day.

I am reverting my project using GIT and trying to narrow down what changed.

I know at a high level I quit using VS for Mac and started using VSCode and the MAUI extension.

Hopefully I can get back to the working version and move forward from there to determine what was the trigger.

**Comment by rolfbjarne** [comment] 2024-09-24 15:37
> cc: @rolfbjarne does this mean anything to you?

This is a duplicate of https://github.com/xamarin/xamarin-macios/issues/21002.

It'll be fixed in the next service update for the iOS workload.

**Comment by tpitman** [comment] 2024-09-24 15:52
I just verified this has nothing to do with my own code. I reverted my entire solution back to a version that I know did not get this entitlement warning and still got the warning when I uploaded it to apple.

The only thing that is different at this point from that time is that I updated the SDK and workloads. Before I was on 8.0.301 and now I am on 8.0.402.

Will this be fixed in a new release to the 8.x stream or will I have to upgrade to 9.x to get the fix?

**Comment by rolfbjarne** [comment] 2024-09-24 15:53
It will be fixed in .NET 8.

**Comment by rolfbjarne** [comment] 2024-09-24 16:16
As far as I know, the App Store message is a warning, and doesn't prevent you from publishing your app.

**Comment by drasticactions** [comment] 2024-09-25 09:06
> If I am using MAUI am I using that iOS workload? I do not have any references to microsoft.net.sdk.ios anywhere that I can find.

For others confused by this, hopefully this can answer it:

MAUI (The UI framework) and MAUI (The runtime SDKs) are not the same. In this case, the issue is with MAUI (The runtime SDK) so anyone who is building with that version of .NET, with that iOS Runtime Workload, would hit that. It's unrelated to MAUI (The UI Framework).

**Comment by tpitman** [comment] 2024-09-25 12:58
> > If I am using MAUI am I using that iOS workload? I do not have any references to microsoft.net.sdk.ios anywhere that I can find.
> 
> For others confused by this, hopefully this can answer it:
> 
> MAUI (The UI framework) and MAUI (The runtime SDKs) are not the same. In this case, the issue is with MAUI (The runtime SDK) so anyone who is building with that version of .NET, with that iOS Runtime Workload, would hit that. It's unrelated to MAUI (The UI Framework). So it would need to be fixed in MAUI (The runtime SDK), which, as Rolf linked to, is fixed and should roll out soon in the runtime.

Thank you for the clarification.

**Closed** 2024-09-25 21:56 UTC
Labels: t/bug, platform/iOS 🍎, s/needs-attention, potential-regression
