### ISSUE TITLE
ListView inside ContentView inside StackLayout: scrolling does not work

### ISSUE THREAD

**Issue by janusw** [dotnet/maui#24455] opened 2024-08-27 08:57 UTC
### Description

The scrolling of ListViews (and similar controls) seems to be broken under certain circumstances. I observed this in several cases (mostly with ListViews and TableViews) and could trace it down to the condition that the `ListView` is inside a `ContentView`, which itself is inside a `StackLayout`. See reproducer below, which is derived from the ListViewDemos in the maui-samples repo (and also contains a workaround for #24308).

I see the problem both on Android (v14), where almost no scrolling is possible, and on iOS (v16.7), where it seems to work a bit better, but still one cannot scroll all the way down to the bottom of the list.

Probably the root cause of the issue is a problem with the sizing of the ListView (which does not seem to be constrained probably)?

### Steps to Reproduce

1. Build and run the ListViewDemos project on this branch of my maui-samples fork: https://github.com/janusw/maui-samples/tree/ListView_bug_repro/8.0/UserInterface/Views/ListViewDemos
2. Select "ListView with DataTemplate".
3. Observe that scrolling is broken. The last item in the list is the "Gelada", which cannot be made visible at all (Android) or only shortly when dragging the view, but then snaps back (iOS).

### Link to public reproduction project repository

https://github.com/janusw/maui-samples/tree/ListView_bug_repro/8.0/UserInterface/Views/ListViewDemos

### Version with bug

8.0.80 SR8

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

seen on Android 14, iOS 16

### Did you find any workaround?

* Remove the StackLayout completely.
* Use a different layout (e.g. a Grid).
* Remove the ContentView and place the ListView directly in the StackLayout (as it is the case in the original ListViewDemos).

**Comment by drasticactions** [comment] 2024-08-28 05:44
https://github.com/dotnet/maui/issues/12452#issuecomment-1683054644

I believe you're seeing this. In short, you shouldn't put a ListView inside a StackLayout as the controls inside of the StackLayout are not constrained unless you specifically set up the heights/widths.

So, unless you specifically set constraints for the ListView, it's going to render the entire List (breaking Virtualization) and generally won't be scrollable. So the right thing to do here is use a Grid, since then it should have proper constraints for the heights.

@PureWeen is my reading on this correct?

**Comment by Zhanglirong-Winnie** [comment] 2024-08-29 08:55
This issue has been verified using  Visual Studio 17.12.0 Preview 1.0(8.0.80 & 8.0.72). Can repro on iOS and Android platforms.

**Comment by PureWeen** [comment] 2024-08-29 23:03
Duplicate of #24078

https://github.com/dotnet/maui-samples/issues/507

**Closed by PureWeen** 2024-08-29 23:03 UTC
Labels: t/bug, platform/android 🤖, platform/iOS 🍎, area-controls-listview, s/verified, s/triaged
