### ISSUE TITLE
.NET 7 MAUI unable to change CollectionView's ItemsLayout.GridItemsLayout.Span while app's running 

### ISSUE THREAD

**Issue by gbarkerz** [dotnet/maui#12866] opened 2023-01-23 21:04 UTC
### Description

Run the demo app listed in the Steps to Reproduce section below. The app shows a CollectionView with 9 items, and is created such that it shows 3 rows and 3 columns. An attempt to change the CollectionView such that it then shows 4 columns results in no change to the displayed CollectionView, and it continues to show 3 rows and 3 columns.

### Steps to Reproduce

Run the demo app at https://github.com/gbarkerz/MauiAppTest2. Note that the CollectionView shows 3 rows and 3 columns. Click the button below the CollectionView which changes the number of columns to be shown by the CollectionView.

Expected: The CollectionView shows 4 columns.
Result: The CollectionView continues to show 3 columns.

Note, I did wonder if I misunderstood the meaning of ItemsLayoutOrientation, so I tried using both ItemsLayoutOrientation.Vertical and ItemsLayoutOrientation.Horizontal and neither resulted in the column count changing.

### Link to public reproduction project repository

https://github.com/gbarkerz/MauiAppTest2

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

net7.0-windows10.0.19041.0

### Did you find any workaround?

No.

**Comment by hartez** [comment] 2023-01-23 22:36
Duplicate of #10144.

**Closed by hartez** 2023-01-23 22:36 UTC
Labels: t/bug
