### ISSUE TITLE
Triggers doesn't work on appearing

### ISSUE THREAD

**Issue by criss02-cs** [dotnet/maui#17355] opened 2023-09-13 19:06 UTC
### Description

when I open my page in the xaml code I inserted a data trigger to disable a button if the text of an Entry is empty, however when opened the trigger does not work and the button is enabled, but if I modify the entry and make it empty again the trigger works

`<?xml version="1.0" encoding="utf-8" ?>
<ContentPage
    x:Class="AudioButtons.Views.ButtonPage"
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:components="clr-namespace:CA.Maui.Components;assembly=CA.Maui"
    xmlns:converters="clr-namespace:AudioButtons.Converters"
    xmlns:viewModels="clr-namespace:AudioButtons.ViewModels"
    xmlns:views="clr-namespace:AudioButtons.Views"
    Title="Nuovo bottone"
    x:DataType="viewModels:ButtonViewModel">
    <ContentPage.Resources>
        <ResourceDictionary>
            <Style ApplyToDerivedTypes="True" TargetType="Label">
                <Setter Property="TextColor" Value="{StaticResource Text}" />
            </Style>

            <Style ApplyToDerivedTypes="True" TargetType="ContentPage">
                <Setter Property="BackgroundColor" Value="{StaticResource Background}" />
            </Style>
        </ResourceDictionary>
    </ContentPage.Resources>
    <VerticalStackLayout Margin="10">
        <Label Text="Nome" />
        <Entry
            x:Name="NameEntry"
            Placeholder="Inserisci il nome"
            Text="{Binding Button.Name}" />
        <Label Text="Percorso" />
        <Grid ColumnDefinitions="7.5*, *">
            <Entry
                x:Name="PathEntry"
                Grid.Column="0"
                IsReadOnly="True"
                Text="{Binding FilePath, Mode=TwoWay}" />
            <Button
                Grid.Column="1"
                Command="{Binding OpenAudioFromFileCommand}"
                Text="..." />
        </Grid>
        <Label Text="Seleziona il colore del bottone" />
        <components:RgbColorPicker Rgb="{Binding Button.Color, Mode=TwoWay}" />
        <Button Command="{Binding SaveFileCommand}" Text="Salva">
            <Button.Triggers>
                <DataTrigger Binding="{Binding Source={x:Reference NameEntry}, Path=Text.Length}"
                             TargetType="Button" Value="0">
                    <Setter Property="IsEnabled" Value="False" />
                </DataTrigger>
                
            </Button.Triggers>
        </Button>
    </VerticalStackLayout>
</ContentPage>`

### Version with bug

7.0.92

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 13

**Comment by StephaneDelcroix** [comment] 2023-09-26 10:22
I believe this is a dupe of #17597 and fixed by #17648

**Closed by StephaneDelcroix** 2023-09-26 10:22 UTC
Labels: t/bug, area/Xaml </>, platform/android 🤖, area/controls 🎮, control-entry, s/needs-repro
