### ISSUE TITLE
Navigation data is retained and also presented to IQueryAttributable on Back navigation.

### ISSUE THREAD

**Issue by bakerhillpins** [dotnet/maui#10294] opened 2022-09-23 20:41 UTC
### Description

I'm using Shell with my MAUI app and am passing parameters during navigation with `Shell.GoToAsync()` using the `Dictionary<string, object>` and the `IQueryAttributable` interface as discussed in the [MS docs](https://learn.microsoft.com/en-us/dotnet/maui/fundamentals/shell/navigation#pass-data). 

```csharp
var navigationParameter = new Dictionary<string, object>
    {
        { "Bear", animal }
    };
await Shell.Current.GoToAsync($"beardetails", navigationParameter);
```

```csharp
public class BearDetailViewModel : IQueryAttributable, INotifyPropertyChanged
{
    public Animal Bear{ get; private set; }

    public void ApplyQueryAttributes(IDictionary<string, object> query)
    {
        Bear= query["Bear"] as Animal;
        OnPropertyChanged("Bear");
    }
    ...
}
```

I noted that my bindings and initialization code for the ViewModel kept being re-executed when I would Navigate Back to the parent page. It appears that any data that's passed as navigation parameters is retained in memory for the life of the page and is subsequently returned to that page during a "Navigate Back" operation. Overriding the back button operation with code that doesn't pass any parameters didn't change the result. Such as this:
```csharp
    <Shell.BackButtonBehavior>
        <BackButtonBehavior
            Command="{Binding BackCommand, Mode=OneTime, Source={x:Reference self}}"/>
    </Shell.BackButtonBehavior>
```

```csharp
        }
            this.BackCommand = new Command( this.OnBackPressed );
        }

        private async void OnBackPressed()
        {
            await Shell.Current.GoToAsync( ".." );
        }
```

Any attempt to clear or supply a different set of data via the method call simply serves to add to the already stored query data. Thus:
```csharp
Shell.Current.GoToAsync( "..", new Dictionary<string, object> { {"w", new object()}  });
```
results in the "w" parameter being added to the current store of parameters. And now "w" and "Bear" are retained until the page is removed from the stack. 

Maybe I'm used to external navigation paradigms but my presumption was that the data was transient for the life of the navigation operation only. Thus the retention of data was not expected. The docs fail to mention anything about the data being retained for the life for the page as well.  Off the cuff this seems like a poor model as it increases memory footprint and possibly has unintended consequences if any system resources were shuttled as parameters.

### Steps to Reproduce

Pass parameters to any page as you navigate down a hierarchy. When the back button is pressed the query data that was passed to any particular page on the initial navigation TO that page is returned via the IQueryAttributable interface.

### Link to public reproduction project repository

https://github.com/bakerhillpins/Issues/tree/NetMauiIssue10294

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

Android 9.0, API 28

### Did you find any workaround?

As the Query parameters are passed via `IDictionary<string, object> query` the author would need to manually cleanup individual resources with `IDictionary<string, object>.Remove()` or `IDictionary<string, object>.Clear()` in an implementation of the `IQueryAttributable` interface:

```csharp
public class BearDetailViewModel : IQueryAttributable, INotifyPropertyChanged
{
    public Animal Bear{ get; private set; }

    public void ApplyQueryAttributes(IDictionary<string, object> query)
    {
        Bear= query["Bear"] as Animal;
        OnPropertyChanged("Bear");

        query.Clear();
    }
    ...
}
```

If one was using the Attribute:
```csharp
[QueryProperty(nameof(Name), "name")]
[QueryProperty(nameof(Location), "location")]
```
they'd be forced to implement the interface to remove the data.  Or, I suppose their property setters must qualify any update with a test for != or their bindings would re-execute when they returned to the page.

**Comment by bakerhillpins** [comment] 2022-09-26 19:03
@PureWeen  - I can't make sense of what you've written, sorry.  I'll try to expand on what I'm reporting.

First:
Any objects added to the IDictionary `parameters` parameter of the `GoToAsync` calls, such as:
```csharp
public Task GoToAsync(ShellNavigationState state, bool animate, IDictionary<string, object> parameters);`
```
are retained in memory with the page after the navigation operation completes. They are first wrapped in `ShellRouteParameters` and [then eventually saved](https://github.com/dotnet/maui/blob/bcaea570dd469404fce699c9bf38cf8a18a65897/src/Controls/src/Core/Shell/ShellNavigationManager.cs#L324) to the attached `ShellContent.QueryAttributesProperty` where they are retained until that page is removed.  Therefore, the `IDictionary` object, and it's contents, share the lifetime of the page that you've navigated to.  These parameters are not released until you pop that page from the nav stack.  I don't think MAUI should assume that an author wants their business objects retained, what's the goal behind that?

Second:
As a result of the previous, performing back navigation results in the page receiving the same query parameters again.  So:

1.  Page1 calls GoToAsync(Page2) with query parameter "MyBufferOfData".
2.  Page2 will receive "MyBufferOfData" in query parameter of IQueryAttributable implementation.
3.  Page2 calls GoToAsync(Page3) with NO query parameters
4.  Page3 will receive no items in the query parameter of IQueryAttributable implementation.
5.  Page3 pops of stack by call to GoToAsync("..")
6.  Page2 **will receive "MyBufferOfData" in query parameter of IQueryAttributable implementation**.
7.  Page2 pops of stack by call to GoToAsync("..")
8.  **Only now can the data associated with "MyBufferOfData" be garbage collected because the original Dictionary is released.**
9.  Page1 will receive no items in the query parameter of IQueryAttributable implementation.

**Comment by bakerhillpins** [comment] 2022-09-26 19:42
@PureWeen I've added code in the repro example to show the data being retained in the navigation hierarchy.  As you navigate down it creates objects. You can force the GC to run but the objects are not released until you pop the page (navigate back).

**Comment by mavispuford** [comment] 2022-09-29 05:50
I've also been experiencing this issue. When I navigate to a page with a query dictionary, I expect it to pass those params a single time so I can consume them and throw them away.  However, when I push a new page on the stack and then navigate back, those same params that I've already consumed are passed into ApplyQueryAttributes() as if I had just created them again.  It's very confusing.

**Comment by PureWeen** [comment] 2022-09-29 16:37
I'm probably still missing something obvious here

Page1 -> Page2?ContactId=3 => Page3

If I'm on Page3 and hit the physical back button what query parameters should Page2 get?

**Comment by bakerhillpins** [comment] 2022-09-29 16:44
> If I'm on Page3 and hit the physical back button what query parameters should Page2 get?
Nothing... 

But it get's ContactId=3

@PureWeen  Have you tried the example project?

**Comment by Kaiffa** [comment] 2022-10-06 11:03
Same issue.
I agree with @bakerhillpins. The query parameters should be used only for the navigation where they are set explicitly and not for later back navigations.

**Comment by bakerhillpins** [comment] 2022-10-07 13:49
@Kaiffa  Don't forget to remove/clear any passed objects at the end of the navigation ApplyQueryAttributes method (The workaround) if you are using it.  MAUI is retaining them in the query dictionary and therefor your business object will NOT be garbage collected until after the page is popped from the stack.

**Comment by bilelmnasser** [comment] 2022-10-21 09:55
Any work around this issue ?, I have a slave page that return a bar code value to main page, if I scan code bar once and return that value to my main, that value still in the query, when I open my slave and close without scanning a bar code, the old value still in the memory, this behaviour is weird, main and slave are transient pages.

**Comment by bilelmnasser** [comment] 2022-10-21 12:05
A workaround for me : clear query dictionary after receiving it, I am able to do it in view model class that implement IQueryAttributable : 
` public void ApplyQueryAttributes(IDictionary<string, object> query)
        {
            if (query.ContainsKey("queryDataKey"))
            {
                queryData= query["queryDataKey"].ToString();

            }

//this will delete the query data after processing it only once 
            query.Clear();
        }`


IQueryAttributable work nicely with ObservableObject of Community toolkit MAUI  mvvm 
hope this helps some that tries to send data througth appShell page navigation !

**Comment by ToolmakerSteve** [comment] 2023-01-11 02:36
@PureWeen 
>If the user hits the back button then they want to return to page2 with the state that page2 was at when they navigated away.

True, but what this issue shows is that "re-applying query parameters" does not restore that state (when navigated away), it restores the page's initial state.

Can a page on nav stack retain its "current" state, so it can show it again?

**Comment by Ghostbird** [comment] 2023-01-13 09:08
Personally I wasn't very surprised by this. It makes perfect sense if you're used to web development, and the MAUI AppShell navigation makes it abundantly clear.

If on the web I:

1. Navigate to https://example.org/page?foo=bar
2. Navigate to https://example.org/otherpage
3. Navigate to the previous page, which is https://example.org/page?foo=bar

It makes perfect sense to me that if I navigate back, I navigate to the exact page I requested, including the query.
MAUI AppShell navigation clearly lets you register and navigate to pages as routes, which matches the style of routing used on the web.

What actually baffled me, is that the same also happens when you use `PopModalAsync`, which breaks the metaphor, and was unexpected to me. In my opinion the whole point of pushing a **modal** rather than a page is that you _don't_ navigate _away_ from the underlying page, hence I did not expect any navigation events to fire when I popped the modal. But that's going too far off on a tangent.

**Comment by Ghostbird** [comment] 2023-01-13 09:12
> Any work around this issue ?, I have a slave page that return a bar code value to main page, if I scan code bar once and return that value to my main, that value still in the query, when I open my slave and close without scanning a bar code, the old value still in the memory, this behaviour is weird, main and slave are transient pages.

I have this exact issue, but put the barcode scanner in a modal, for reasons explained above. However I'm not willing to clear my query attributes, because having them there makes perfect sense to me. I think `ApplyQueryAttributes` should not fire when I pop a modal.

**Comment by Ghostbird** [comment] 2023-01-13 09:36
I've made #12630 to talk about the modal specific use case.

**Comment by bakerhillpins** [comment] 2023-01-13 13:00
> Personally I wasn't very surprised by this. It makes perfect sense if you're used to web development, and the MAUI AppShell navigation makes it abundantly clear.
> 
> If on the web I:
> 
>     1. Navigate to https://example.org/page?foo=bar
> 
>     2. Navigate to https://example.org/otherpage
> 
>     3. Navigate to the previous page, which is https://example.org/page?foo=bar
> 
> 
> It makes perfect sense to me that if I navigate back, I navigate to the exact page I requested, including the query. MAUI AppShell navigation clearly lets you register and navigate to pages as routes, which matches the style of routing used on the web.

I hear you but I don't agree because I'm not actually "navigating" to a new page as you describe above. The Pop/Back operation doesn't take in a `Uri,` It simply removes a `View` from the z-order and returns us to the same page (same instance) we were viewing previously. Nothing new was created. I'm popping a view off the stack and I didn't apply any navigation parameters to that action.  In your example you show navigation to `page` twice.  There's 2 specific actions you've requested in there.

- You're navigating to a new Page and thus new instance of the `Page` object. In MAUI this would result in a stack of /Page/OtherPage/Page. This issue discusses going from /Page/OtherPage back to /Page, so we're not increasing the z-order. 
- In both navigation steps you've supplied in the URL data to be sent into the page (`?foo=bar`). In this situation you've actually requested a **different** instance of the `Bar` object to be supplied to that navigation operation and that's not what's happening here. The pop action results in the same instances of data being delivered to the return operation that was applied when the view was initially navigated to.

**Comment by bakerhillpins** [comment] 2023-01-13 14:28
> Personally I wasn't very surprised by this. It makes perfect sense if you're used to web development, and the MAUI AppShell navigation makes it abundantly clear.

So I'm following up here because technically the my 1st bullet isn't drawing a proper analogy between the web example and MAUI. Though I used a navigation stack with multiple pages because that's what this issue is rooted in.  Specifically, the web navigation pointed out by @Ghostbird would result in the following navigation stack changes on MAUI.

/Page to /OtherPage and then /Page.   At no point in that web example is a [Navigation Stack](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/pages/navigationpage?view=net-maui-7.0#perform-modeless-navigation) built up. It's simply one page at a time at the root. And in that regard MAUI does work as he mentions. But the issue isn't about new pages at the root, it's when we move backwards through the navigation stack and so the web example isn't demonstrating the issue situation.

And this brings up an important point. MAUI and Web applications are different tech stacks and they behave differently because of that. Outwardly they may use some of the same concepts like Uri based navigation but effectively the similarities end there. To my knowledge (which is limited in web) web applications don't remember/retain previous views and in that regard are stateless. Each request is completely new and thus each new page served up as the only one in existence. In fact the web app isn't rendering the view, the browser is. Thus, we shouldn't confuse navigation between webpages and browser back button behavior. The browser after all isn't the web application, it's what we use to view state. The Back button is a feature of the browser and is simply saving the previous view (the actual instance) on a stack and pushing/popping those saved LOCAL states back to the user. 

> I've made #12630 to talk about the modal specific use case.

It's unfortunate that you've splintered the conversation to #12630 because the situation you describe there IS in fact identical to this issue in that the user is navigating backwards through the [navigation stack](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/pages/navigationpage?view=net-maui-7.0#perform-modal-navigation).

The modal web example you provide is actually better aligned to what we have occurring in device based apps since the navigation is happening within the root view (it's instance isn't lost).

**Comment by ToolmakerSteve** [comment] 2023-01-14 04:06
> MAUI and Web applications are different tech stacks and they behave differently because of that. 

Lets be clear here. It isn't  "MAUI" (in general) that is behaving this way. It is specifically "AppShell".

The behavior we see is specific to AppShell's design, which seems to me to be different than the mobile platform's native navigation paradigms. Its also different than Xamarin.Forms older navigation mechanism, NavigationPage.

**begin rant**

My view of AppShell is that its navigation paradigm is out in left field, for no good reason.

I'm not a fan. This unexpected behavior is one of many that can be seen by searching StackOverflow for questions tagged Xamarin.Forms or Xamarin, and mention Shell or AppShell. MANY app devs have struggled to get this to behave the way they need.

By contrast, NavigationPage is a straightforward design. Never caused anybody serious problems. Still works great today in Maui.

**end rant**

**Comment by PureWeen** [comment] 2023-01-14 21:46
> Of course you then don't have any of AppShell's features. Its a tradeoff.

You can interact with `Shell` like it's a `NavigationPage`

All `GotoAsync` does is translates "GotoAsync" to `INavigation` calls.

**Comment by shadowfoxish** [comment] 2023-01-27 16:34
It kinda makes sense to me that the query parameters would be retained, at least in some cases. In the MVC world, this gets avoided by the PRG pattern (post-redirect-get), wherein you post data to a page, the server does something with it, then its response is to redirect you somewhere else so the back-button doesn't resubmit the same data again. 

I ran into this with my app, I have one page that has a few sub-pages it calls out to.
/home -> [Load some thing! with params] -> /thing -> /thing/action1 -> [Go Back! with params] -> /thing -> /thing/action2 -> [Go Back! with params]
The second [Go Back!] /thing page visit's ApplyQueryAttributes dictionary contains the parameters from the previous navigations to /thing. 

I'm just going to add a `Clear()` to the end of `ApplyQueryAttributes(..)` to indicate I have "consumed" the parameters and don't need them again. Since the same instance of the class is being reused, there's no need to start over.

**Comment by Ghostbird** [comment] 2023-01-30 12:30
I think that would've worked for my use case too. I used a different mechanism, but I like this one better as it is simpler yet perfectly explicit.

**Comment by acaliaro** [comment] 2023-02-09 14:34
after five months it is still not clear to me if this is a mistake or if it is intended behavior. Is there anyone on the MAUI team who can give feedback @PureWeen @jfversluis @hartez ? If it's a desired behavior, you can close the issue, otherwise I think it's a problem to be solved asap

**Comment by Ghostbird** [comment] 2023-02-09 18:39
I'm not MAUI team at all, but from what I've seen in this discussion, and in #12630, it's definitely not a mistake. In a sense this issue can be closed. The discussion on how the mechanism can be improved however is not finished yet. For now the logic as I understand it is fairly simple:

- Parameters are passed to a route in a _mutable_ form.
- If you only want to use them once, consume them by mutation of the dictionary.

The advantage of this mechanism is in my eyes is:

- It gives the developer full control. You want a use-once mechanism, that can be done with very little code.
- You need the route data to remain stable? Just don't do anything.

The disadvantage of this mechanism for me was:

- The behaviour is not self-explanatory, nor very explicitly documented.

The biggest argument to not remove route data in my opinion is: Can you guarantee that for each use case, you remove it exactly at the right moment? If not, leave it to the application developer. We're not talking about whole frameworks that they must rebuild. Just that they write the right line of code at the right time for their use-case.

The documentation could use some could use a message like:

> **Warning**
>  The route parameters for a given route are _mutable_ and not changed unless you explicitly navigate to that route. In some cases you might want to pass route data only once. For example when you have pushed an additional page on a navigation stack and you pop it to go back to a routed page. To do this you can remove all one-time route parameters from the dictionary immediately after you have used that data.

Although I'm sure there are more comprehensible ways to describe this behaviour.

**Comment by bakerhillpins** [comment] 2023-02-09 19:15
Have to disagree here, It is **unexpected** to have the routing stack maintain references to the developers business objects. It didn't create them and wasn't explicitly given control of them. Why is it injecting itself into the lifecycle of the developers object model? It's was simply asked to pass them to another page, nothing more.

> The advantage of this mechanism is in my eyes is:
> 
>     * It gives the developer full control. You want a use-once mechanism, that can be done with very little code.
> 
>     * You need the route data to remain stable? Just don't do anything.

As far as it supporting the developers needs, TBH both paradigms would support the developers needs in either regard. It simply boils down to expectations. I don't expect the platform's (MAUI) navigation operations to force its self into my business logic. In fact I don't recall any other navigation paradigm that I've used in desktop/mobile development scenarios behaves this way.  If I want to maintain objects between pages, I'll be explicit about that code and or implementation.  

> The biggest argument to not remove route data in my opinion is: Can you guarantee that for each use case, you remove it exactly at the right moment? If not, leave it to the application developer. We're not talking about whole frameworks that they must rebuild. Just that they write the right line of code at the right time for their use-case.

I'd be interested to understand this better because I've been using this app based navigation paradigm for quite some time and never encountered a situation where the bounds on a navigation operation were not clearly defined and objects were not removed "exactly at the right moment". Can you describe a specific situation to help me understand?

**Comment by Ghostbird** [comment] 2023-02-09 19:44
I think in a way we're agreeing in philosophy, and seem to disagree where the boundaries lie.

> …was simply asked to pass them to another page, nothing more.

In a way the current approach can be described as such. The developer created and passed the attribute dictionary when routing, and MAUI simply passes it on, to where the code enters the `ApplyQueryAttributes`. In a way MAUI doesn't meddle with what the developer does. It just provides a way for the dev to expose the object to the page when routing.

> …TBH both paradigms would support the developers needs in either regard. …. If I want to maintain objects between pages, I'll be explicit about that code and or implementation.

I think that's an excellent approach. I completely agree that the behaviour was unexpected. I too filed a bug report about the behaviour. Only after more reading and discussion, I came to see that there are reasons for the current  behaviour.

> …Can you describe a specific situation to help me understand?

I don't think I can any more. I had one which involved navigation to the same `Page` with different data, but I think that one won't work anyway without additional state management code, regardless of which approach is used. I'm not 100% sure.

All in all I'm not opposed to the current mechanism, it has some sensible reasons. I think it in a way boils down to how conceptualise “passing routing data to the page”. The current implementation takes an approach that provides the developer with a mechanism to _expose_ a dictionary of data to the `Page` instance.

I too initially expected a more immutable approach where data is produced and passed upon routing, and read and consumed once the page load.

One argument for the mutable approach is that the arguments are an `IDictionary<string, object>`. Given that the objects can be reference types, full immutability cannot be guaranteed, therefore instead take a fully mutable approach.

I think I'd rather see the behaviour you describe, but I would not ask for a breaking change to be introduced to facilitate it.

**Comment by iSeiryu** [comment] 2023-03-21 13:54
Looks like its this now
```csharp
public class BearDetailViewModel : IQueryAttributable, INotifyPropertyChanged
{
    public Animal Bear{ get; private set; }

    public event PropertyChangedEventHandler PropertyChanged;

    public void ApplyQueryAttributes(IDictionary<string, object> query)
    {
        Bear= query["Bear"] as Animal;
        PropertyChanged(this, new PropertyChangedEventArgs("Bear"));
    }
    ...
}
```

`INotifyPropertyChanged` interface has changed.

**Comment by Quaybe** [comment] 2023-03-21 18:11
In my case, I have a logout button in my app shell nav menu. If the user clicks it in the nav shell and confirms logout, I send them to the landing page with Logout=true : 
   `await Shell.Current.GoToAsync($"//{nameof(LandingPage)}?Logout=True");`

Landing page queries it like this, as documentation specifies:
   `[QueryProperty(nameof(Logout), nameof(Logout))]`

This triggers my logout process which is housed there in the landing page.

However, now anytime I navigate back to the landing page from anywhere in my app, the navigation somehow still sends Logout=true each time, forcing a logout. This is unexpected and makes absolutely no sense. This Logout=true attribute should only be sent the one time I hit logout button, not every time thereafter.

**Comment by iSeiryu** [comment] 2023-03-22 02:19
@Quaybe did you register your landing page as a singleton by any chance?

**Comment by cenkgunay** [comment] 2023-03-25 20:23
I overcome this problem by overrideing Back command, and passing empty arguments in AppShell.Current.GoToAsync method.
Page:
<ContentPage ...
    <Shell.BackButtonBehavior>
        <BackButtonBehavior Command="{Binding BackCommand}" />
    </Shell.BackButtonBehavior>
View Model:
        [RelayCommand]
        public async void Back()
        {
            await AppShell.Current.GoToAsync("..?Reload=false");
        }

**Comment by PureWeen** [comment] 2023-04-18 14:45
Capturing a few key points and areas we can improve. I'd like to break this out in specs/docs/issues. 

1) docs for navigating and how to manipulate parameters given the current structure would be helpful (i.e. `query.clear()` )
2) Looking at the original repro, I noticed that the back navigation is replaced using a `BackCommand` that passes in a `new dict`

```C#
await Shell.Current.GoToAsync("..",
                new Dictionary<string, object>
                {
                    { nameof(Issue10294ViewModel.BackCommand), $"Back Depth {this.Depth}" }
                });
```

That does feel a bit awkward. Given the above `GotoAsync`, I feel like your query parameters should only have the one parameter.

One hack-around you can use here is to just pass something into the string. For example,

```C#
await Shell.Current.GoToAsync("..?goaway=1",
                new Dictionary<string, object>
                {
                    { nameof(Issue10294ViewModel.BackCommand), $"Back Depth {this.Depth}" }
                });
```

That will cause the previous data to clear out. But it seems like if this clears the data out so should the first example. 

3) Better use of transient registration. Right now, when you register pages as transient, those pages aren't recreated at the `ShellContent`  level. They should just get recreated, and the query parameters cleared out. 
https://github.com/dotnet/maui/issues/5686
https://github.com/dotnet/maui/issues/9300

4) Additional APIs. This part will need more thought but some quick thoughts are
- If we want to buy into `IQueryAttributable` we need to add more interfaces. One interface you can add to the VM doesn't really give enough context to be useful. Yea, you can dive down to the events on the pages but then why even have an interface you can add to the VM? `IQueryAttributable` is awkward by itself. I think the solution here would be more interfaces that map to what's actually happening. `IInitialActivate`, `IViewAppearing`, `INavigationHappening`, etc... 

- Add some navigation args to `GotoAsync` that would allow users to modify the result. Possibly some flags (clear query string, clear stack, etc...)

5) this would also help give a bit more power to the developers https://github.com/dotnet/maui/issues/3868


#### Open questions
> When we navigate to page 2 we present INITIAL data via the query dictionary. That state may be altered or deleted, or whatnot before we navigate to page3. So returning to page2 and being presented with the INITIAL query data again, doesn't retain page2's state when we navigated away, it changes it back to INITIAL conditions.

@bakerhillpins  I don't quite follow this statement. What data is being mutated and how should/would shell know about the mutated data?

> Can a page on nav stack retain its "current" state, so it can show it again?
@ToolmakerSteve you made a similar statement can you clarify?

I don't quite follow what is meant by "current state". Shell doesn't serialize/deserialize the dict and then recreate it. Where would shell get this current state from?

**Comment by espenrl** [comment] 2023-04-19 14:20
This issue has become a lot of reading for what seems (to me) to be a simple case. I'll add to this discussion how I expect `IQueryAttributable` to behave, and I'll do that because I think that is how most developers expect this API to behave. Maybe I'm wrong, but please upvote if you agree.

Here is all the relevant code for my thinking.

``` CSharp
await Shell.Current.GoToAsync("..",
                new Dictionary<string, object>
                {
                    { nameof(Issue10294ViewModel.BackCommand), $"Back Depth {this.Depth}" }
                });

public void ApplyQueryAttributes(IDictionary<string, object> query)
{
}
```

What I expect is that the `query` parameter is the actual dictionary `instance` created when calling `GoToAsync`. And without any additional entries added. It should be as I as a developer created it. Nothing more, nothing less.

As of MAUI 7.0.59 it somehow contains additional entries from previous navigations. And that leads to unexpected behavior in apps.

**Comment by PureWeen** [comment] 2023-04-19 14:33
What if someone does this?

``` CSharp
await Shell.Current.GoToAsync("..?field=1",
                new Dictionary<string, object>
                {
                    { nameof(Issue10294ViewModel.BackCommand), $"Back Depth {this.Depth}" }
                });

public void ApplyQueryAttributes(IDictionary<string, object> query)
{
}
```


> This issue has become a lot of reading for what seems (to me) to be a simple case. I'll add to this discussion how I expect `IQueryAttributable` to behave, and I'll do that because I think that is how most developers expect this API to behave. Maybe I'm wrong, but please upvote if you agree.
> 
> Here is all the relevant code for my thinking.
> 
> ```cs
> await Shell.Current.GoToAsync("..",
>                 new Dictionary<string, object>
>                 {
>                     { nameof(Issue10294ViewModel.BackCommand), $"Back Depth {this.Depth}" }
>                 });
> 
> public void ApplyQueryAttributes(IDictionary<string, object> query)
> {
> }
> ```
> 
> What I expect is that the `query` parameter is the actual dictionary `instance` created when calling `GoToAsync`. And without any additional entries added. It should be as I as a developer created it. Nothing more, nothing less.
> 
> As of MAUI 7.0.59 it somehow contains additional entries from previous navigations. And that leads to unexpected behavior in apps.


@ToolmakerSteve @bakerhillpins is this what you mean by `current state`? The dictionary should always be the same instance. If it wasn't going to be then we should have made it a `Readonly` dictionary?

**Comment by espenrl** [comment] 2023-04-19 14:51
That's a valid point Shane. I can see a scenario where one would mix and match if the route and parameters are defined at different points in the application. Especially when mixing XAML and C# - strings are easier in XAML, a dictionary is natural in C#. So yes, parameters from the route string would be expected to be added to the parameters dictionary.

``` cs
var route = "..?field=1";

...
...
...

var parameters = new Dictionary<string, object>
                {
                    { nameof(Issue10294ViewModel.BackCommand), $"Back Depth {this.Depth}" }
                };

...
...
...

await Shell.Current.GoToAsync(route, parameters);
```
---
Over to the main problem. As of MAUI 7.0.59 the parameters dictionary contains additional entries from `previous navigations`. That is for me a very unexpected behavior.

**Comment by espenrl** [comment] 2023-04-19 15:08
> > Over to the main problem. As of MAUI 7.0.59 the parameters dictionary contains additional entries from `previous navigations` (plural) to the same page. That is for me a very unexpected behavior.
> 
> Interesting. I'll need to test this one. So you're saying the behavior changed between 7.0.52 and 7.0.59?

I think it has been for a long time.

I do this:

``` cs
Shell.Current.GoToAsync("../");
```

And I get this:

![image](https://user-images.githubusercontent.com/4621581/233118857-77d6e429-2e7a-45ce-86f9-614f58012c07.png)

The parameter `Viewpoint` is from a previous navigation to the page. The page is the page of a tab in the shell, and it's alive for the whole liftetime of the application.

**Comment by PureWeen** [comment] 2023-04-19 15:18
Cool, just making sure it's not a regression. 

yea, I can see the point where retaining the dictionary of additional data is a bit weird. The parameters that make up the Uri, debatable, I see cases for both. For example, we have a couple issues where when you navigate between tabs and `ApplyQueryAttributes` isn't called with the original data which is messing people up. 

The dictionary itself is a bit weird since you have to actively clear it. I feel like that's a scenario that might be worth breaking for net8 or at least adding some flag/setting/other to change that behavior.

**Comment by williambuchanan2** [comment] 2023-04-26 00:31
>The MAUI/AppShell (whatever) navigation subsystem cant, and should not (IMHO), make any lifetime or state decisions about my business objects. It's my job as the Application developer to manage my data against the requirements.

Totally agree. I've got a valid use case where this has become a problem. I need to be able to clear the arguments being passed when I navigate back, but at the moment it seems impossible, and the result is I can't make the pages behave how I want them to behave when they load.

**Comment by bakerhillpins** [comment] 2023-04-26 12:13
@williambuchanan2  Have you looked at the workaround?  You can call clear() on the dictionary passed in via IQueryAttributable

**Comment by williambuchanan2** [comment] 2023-04-26 22:03
> @williambuchanan2 Have you looked at the workaround? You can call clear() on the dictionary passed in via IQueryAttributable

Hi, yes I looked at that, but then I had another strange problem. It looks like the ApplyQueryAttributes method was only ever being called once. This is a problem for me because the issue is on the way back. I.e. :
Page 1 - calls page 2
Page 2 - ApplyQueryAttributes
Page 2 - calls page 3
Page 3 - go back to page 2 - ApplyQueryAttributes not called.

So when page 3 goes back to page 2, I am unable to get the query attributes.

**Comment by bakerhillpins** [comment] 2023-04-28 11:09
It's difficult to say what's going on without seeing how your navigation code is setup. Do you have a repo/code you can point to?

**Comment by williambuchanan2** [comment] 2023-05-01 01:19
> It's difficult to say what's going on without seeing how your navigation code is setup. Do you have a repo/code you can point to?

I don't have one for this. To be honest i've reached the stage where i'm just looking for workarounds for all the problems now rather than reporting them.

**Comment by PureWeen** [comment] 2023-05-07 20:10
Here's my first go at addressing some of the complaints here.

https://github.com/dotnet/maui/pull/14965

Let me know if you have any thoughts/suggestions/questions.
I think this will give the option to pivot between query parameters vs navigation only parameters depending on your scenario.

Ultimately, I'd like to add a richer set of interfaces, but I think this is a useful modification for NET8

**Comment by bakerhillpins** [comment] 2023-05-11 13:46
@PureWeen 
As I can't comment in the PR-
What you have seems clear enough to me as far as the proposal goes. 

For my part in all of this it still seems odd to retain any parameters since the uri that's being applied to navigate back via `GotoAsync` in your examples, specifically `"..",` doesn't actually contain any parameters. I guess I never felt comfortable with my understanding of what is/was the intended feature design to begin with. Was it to represent the application page Z-order within a URI or was it to behave like a browser back button combined with URIs.

**Comment by PureWeen** [comment] 2023-05-11 17:55
@bakerhillpins 
> behave like a browser back button combined with URIs.

Basically this. 

We're still discussing some other approaches for that PR. Possibly just adding a configuration property so you can disable the current behavior. We have to be careful about not breaking users that depend on aspects of this behavior (as confusing as it might be). The current PR was primarily proposing an approach with minimal breaking.

**Comment by TWTIC** [comment] 2023-06-25 07:56
It drove me crazy. Here is my solution:



`
// ViewModel:
[QueryProperty(nameof(Prop1), "Prop1")]
[QueryProperty(nameof(Prop2), "Prop2")]

[ObservableProperty]
item prop1;
item _LastProp1;

[ObservableProperty]
item prop2;
item _LastProp2;
...

protected override void OnPropertyChanged(PropertyChangedEventArgs e)
{
        base.OnPropertyChanged(e);
	if (e.PropertyName == "Prop1" && Prop1 != null && Prop1 != _LastProp1)
	{
		...
		_LastProp1 = Prop1;
	}  
	else if (e.PropertyName == "Prop2" && Prop2 != null && Prop2 != _LastProp2)
	{
		...
		_LastProp2 = Prop2;
	}  
	...
}
`

**Comment by Ghostbird** [comment] 2023-06-25 21:47
I think you mean that the ellipses inside the `if`s stand for the code you want executed _only_ on change? Then that implementation would make sense.
Would the [approach I took](https://github.com/dotnet/maui/issues/10294#issuecomment-1489779147) (clear the dictionary on every navigation) have worked for you too?
An advantage of that approach is that you can omit the change detection code. A disadvantage is that you have to add more property set code.

You'd get something like this:
```
public void ApplyQueryAttributes(IDictionary<string, object> query)
{
  if (query.TryGetValue(nameof(Prop1), out var newProp1) {
    Prop1 = newProp1;
  }
  // To clear all route attributes
  query.Clear();
}
```

**Comment by TWTIC** [comment] 2023-06-26 05:57
Yes, you are right, the effect would be the same.
The problem occurs with views where I call other views to select something and return it as a query property. 
Since the query property survives, I have to mark it as used somehow, otherwise it will be processed again on each back navigation. 
Since I always use the PropertyChanged method anyway, my solution is the best for me. I also hope that maybe in the future there will be a solution to mark Query Properties for a single use ...
```

// Some pseudo code
[QueryProperty(nameof(SelectedItem), "SelectedItem")]
public partial class OrderViewViewModel : BaseViewModel
{
        [ObservableProperty]
        Item selectedItem;
        Item _LastSelectedItem;
...
        [RelayCommand]
        async Task SelectItem()
        {
            await Shell.Current.GoToAsync(nameof(SelectItemView));
        }
...
        protected override void OnPropertyChanged(PropertyChangedEventArgs e)
        {
        base.OnPropertyChanged(e);
        if (e.PropertyName == "SelectedItem" && SelectedItem != null && SelectedItem != _LastSelectedItem)
        {
           doSomethingWithSelectedItem (SelectedItem);
          _LastSelectedItem = SelectedItem;
        }
...
}
...
public partial class SelectItemViewModel : BaseViewModel
{
...
        [RelayCommand]
        async Task OK()
        {
            await Shell.Current.GoToAsync("../", true,
                new Dictionary<string, object>
                {
                   {"SelectedItem",CollectionViewSelectedItem}
                }
                ); 
        }

        [RelayCommand]
        async Task Cancel()
        {
            await Shell.Current.GoToAsync("../");
        }


}

```

**Closed** 2023-07-13 01:59 UTC
Labels: t/bug, area/navigation 🧭, p/1, area/shell 🐢, partner/cat 😻, s/needs-attention
