### ISSUE TITLE
[Bug] Setting InputType on android entry fires the text watcher internally

### ISSUE THREAD

**Issue by mattleibow** [dotnet/maui#451] opened 2021-03-08 01:59 UTC
### Description

Just observed that changing the `InputType` on the Android `EditText` fires the `ITextWatcher` for each update. In the current implementation, this is about 7 times. 

It does not propagate to the even because there are checks to see if the string has changed, but this is still 6 times too many. We need to build up the `InputType` value beforehand, and then set just once.

### Steps to Reproduce

1. Add `Entry` to UI
2. Add a breakpoint/logging in the watcher
3. Observe 7 messages - all from `set_InputType`

### Expected Behavior

1 event

### Actual Behavior

7 events

**Comment by bkaankose** [comment] 2021-03-20 01:22
This might've been fixed with #507 already.

**Comment by mattleibow** [comment] 2021-03-20 12:38
Might need to confirm I believe it is a OS action as setting that property on the native view automatically triggers the event.

**Comment by shimingsg** [comment] 2022-03-03 11:25
@mattleibow , we cannot reproduce your issue with the information above, could you provide a sample project/screenshots or more details that we can reproduce your issue?

**Closed** 2022-03-22 20:46 UTC
Labels: t/bug, area/controls 🎮, s/verified, control-entry
