### ISSUE TITLE
[Bug] StackLayout.VerticalOptions FillAndExpand ignored

### ISSUE THREAD

**Issue by JohnHDev** [dotnet/maui#2587] opened 2021-09-19 13:07 UTC
### Description
StackLayout.VerticalOptions FillAndExpand ignored (at least on WinUI)

### Steps to Reproduce

Given the following code in a MainPage.cs
            Content = new StackLayout()
            {
                VerticalOptions = LayoutOptions.FillAndExpand,
                BackgroundColor = Color.Blue,
                Children =
                {
                    new Label()
                    {
                        Text = "hello"
                    }
                }
            };

### Expected Behavior
The entire page should be blue with hello displayed top left.

### Actual Behavior
The stack layout is displayed vertically centred, only big enough to show the label

### Basic Information

- Version with issue: MAUI preview 8
- Last known good version:
- IDE: VS2022 preview 4
- Platform Target Frameworks: Windows, haven't tried others.

**Comment by hartez** [comment] 2021-11-05 18:10
Duplicate of #1702. We know this doesn't work as it did in Forms; we still haven't determined how exactly we want to handle it.

**Closed by hartez** 2021-11-05 18:10 UTC
Labels: t/bug, area/layout 🔲

**Comment by eestein** [comment] 2021-11-05 18:17
@hartez thanks, but are there any alternatives in place to get the same behavior?
