### ISSUE TITLE
RootComponentCollectionExtensions.cs is included in WinForms but missing in Wpf.

### ISSUE THREAD

**Issue by budcribar** [dotnet/maui#4057] opened 2022-01-11 14:23 UTC
### Description

RootComponentCollectionExtensions.cs is included in WinForms but missing in Wpf. It should be added to Wpf

### Steps to Reproduce

Notice file is missing in maui/src/BlazorWebView/src/Wpf/

### Version with bug

Preview 10 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows

### Did you find any workaround?

Workaround is to write your own.

**Comment by Eilon** [comment] 2022-01-20 04:53
You know, this does look odd, but I wonder if it was done on purpose? I kind of recall it being deliberate but I'm fuzzy on the details.

We have 3 sets of this stuff:

1. In WinForms there's no syntax/markup for adding root components, so we added a nicer API for devs to call in their Form constructor, such as `myBlazorWebView.RootComponents.Add<FooComponent>(...)`
2. In WPF there is a XAML syntax for adding root components so we follow the API pattern that enables that. It's also callable imperatively.
3. In MAUI it's the same story as WPF with XAML and code based ways to add root components.

So, WinForms is the "odd man out" here so it gets some extra APIs. We could probably unify all the APIs to look like what WPF/XAML have (and thus delete the [WinForms RootComponentCollectionExtensions](https://github.com/dotnet/maui/blob/main/src/BlazorWebView/src/WindowsForms/RootComponentCollectionExtensions.cs).

I think that what we have now is fully functional as is "by design" but we could consider changing it if it was worthwhile.

**Comment by Eilon** [comment] 2022-01-20 04:56
For reference:

|  WinForms | WPF  | .NET MAUI  |
|---|---|---|
| [RootComponent](https://github.com/dotnet/maui/blob/main/src/BlazorWebView/src/WindowsForms/RootComponent.cs)  | [RootComponent](https://github.com/dotnet/maui/blob/main/src/BlazorWebView/src/Wpf/RootComponent.cs)  | [RootComponent](https://github.com/dotnet/maui/blob/main/src/BlazorWebView/src/Maui/RootComponent.cs)  |
| [RootComponentsCollection](https://github.com/dotnet/maui/blob/main/src/BlazorWebView/src/WindowsForms/RootComponentsCollection.cs)  | [RootComponentsCollection](https://github.com/dotnet/maui/blob/main/src/BlazorWebView/src/Wpf/RootComponentsCollection.cs)  | [RootComponentsCollection](https://github.com/dotnet/maui/blob/main/src/BlazorWebView/src/Maui/RootComponentsCollection.cs)  |
| [RootComponentCollectionExtensions](https://github.com/dotnet/maui/blob/main/src/BlazorWebView/src/WindowsForms/RootComponentCollectionExtensions.cs)  |   |   |

**Comment by budcribar** [comment] 2022-01-27 19:51
I would vote for having  RootComponentCollectionExtensions for all 3 for consistency and ease of use, but it is trivial to create your own so not a big deal either way.

**Comment by wenwen60** [comment] 2022-03-14 02:12
Reproduce it.

**Comment by mkArtakMSFT** [comment] 2022-11-03 17:38
Thanks for contacting us.
We couldn't prioritize this investigation given the number of customers are affected. Hence closing this issue.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.

**Closed by mkArtakMSFT** 2022-11-03 17:38 UTC
Labels: t/bug, area/blazor 🕸️, s/verified
