### ISSUE TITLE
[IOS] Maui .NET 8 (VS 2022 17.9.6) The app has been terminated when start debugging

### ISSUE THREAD

**Issue by MaheshTFS** [dotnet/maui#22330] opened 2024-05-10 12:02 UTC
### Description

Default template MAUI app debug is crashing after splash screen on iPhone (iOS 15.8.2)
"The app has been terminated."

### Steps to Reproduce

1. Default MAUI app.
2. Debug it on iOS device.

### Version with bug

8.0.21 SR4.1

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15.8.2

### Did you find any workaround?

No

### Relevant log output

```shell
The app has been terminated.
```

**Comment by bzd3y** [comment] 2024-05-15 20:21
This seems like a duplicate of #11392.

@MaheshTFS @alex-dubatov I listed some things that might be able to help get around this here: https://github.com/dotnet/maui/issues/11392#issuecomment-2069827471

**Comment by alex-dubatov** [comment] 2024-05-16 09:02
@bzd3y Thanks for the advice! Nothing helps.

Build log:
```
11:50:52:600	1>------ Deploy started: Project: MauiExample, Configuration: Debug Any CPU ------
11:50:52:654	1>Starting deploy 'MauiExample' into the device 'iPad (Pro) - real'...
11:50:52:717	1>Deploying 'MauiExample.app' into the device 'iPad (Pro) - real'...
11:51:12:591	1>Deploy succeeded. The app 'MauiExample.app' has been successfully deployed on iPad (Pro) - real.
11:51:12:601	========== Deploy: 1 succeeded, 0 failed, 0 skipped ==========
11:51:12:601	========== Deploy completed at 11:51 AM and took 20.027 seconds ==========
11:51:12:865	Launching 'MauiExample' on 'iPad (Pro) - real'...
11:51:12:946	Connecting iOS Debugger to 'iPad (Pro) - real' over USB on port 10000...
11:51:15:493	Connected iOS Debugger to 'iPad (Pro) - real' over USB on port 10000
11:51:15:493	Connecting iOS Debugger to 'iPad (Pro) - real' over USB on port 10000...
11:51:15:493	Connecting iOS Debugger to 'iPad (Pro) - real' over USB on port 10000...
11:51:15:493	Connected iOS Debugger to 'iPad (Pro) - real' over USB on port 10000
11:51:15:493	Reading from debug console stream...
11:51:15:493	Reading from device stream...
11:51:15:493	Reading from machine (TCP) stream...
11:51:15:493	Connected iOS Debugger to 'iPad (Pro) - real' over USB on port 10000
11:51:15:493	Connected IDB.Local to Debugger port 55968
11:51:15:493	Please launch the application 'MauiExample' on the device 'iPad (Pro) - real' to continue. For the first launch, if the application does not show up, please reboot your device.
11:51:35:805	Closing debug communication from device stream
11:51:35:819	Error writting to debug stream. Details: Cannot access a disposed object.
11:51:35:819	Object name: 'AppleDeviceUsbStream'.
11:51:35:907	Closing debug communication from machine (TCP)
11:51:35:907	Cannot read from machine (TCP) stream anymore...
```

**Comment by emaf** [comment] 2024-05-17 16:21
@alex-dubatov from the build output I see you are using Hot Restart (iOS device connected directly to Windows). As this is a tooling issue, could you report it from inside VS -> Help -> Send Feedback -> Report a problem

@MaheshTFS Are you also trying to debug using Hot Restart by plugging your device to your Windows PC?

**Comment by alex-dubatov** [comment] 2024-05-18 08:39
@emaf looks like issue is already exists https://developercommunity.visualstudio.com/t/cant-debug-with-Maui--iOS-iPad-physical/10632315?q=maui+ios+debug&ref=native&refTime=1716021583535&refUserId=5dd9c650-854b-62f7-8920-d90490483bd9

**Comment by emaf** [comment] 2024-05-20 13:55
@alex-dubatov If you haven't done already, could you please upvote it? 

I'm closing this in favor of the issue you linked.

**Closed by emaf** 2024-05-20 13:55 UTC
Labels: t/bug, area-tooling, platform/iOS 🍎, s/move-to-vs-feedback
