### ISSUE TITLE
[regression/8.0.0-preview.7.8842] MAUI ios and maccatalyst don't build

### ISSUE THREAD

**Issue by harry-cpp** [dotnet/maui#16612] opened 2023-08-08 20:57 UTC
### Description

MAUI projects targeting iOS and macOS don't build with preview 7

### Steps to Reproduce

Install .NET 8 and MAUI preview 7 then run:

```sh
dotnet new maui
dotnet build
```

### Version with bug

8.0.0-preview.7.8842

### Last version that worked well

8.0.0-preview.6.8686

### Affected platforms

iOS, macOS

### Relevant log output

```shell
ILLink : unknown error IL7000: An error occured while executing the custom linker steps. Please review the build log for more information. [/Users/harry/test/test.csproj::TargetFramework=net8.0-maccatalyst]
ILLINK : error MT2301: The linker step 'Setup' failed during processing: Failed to parse PList data type: dict [/Users/harry/test/test.csproj::TargetFramework=net8.0-maccatalyst]
/Users/harry/.nuget/packages/microsoft.net.illink.tasks/8.0.0-preview.7.23375.6/build/Microsoft.NET.ILLink.targets(84,5): error NETSDK1144: Optimizing assemblies for size failed. Optimization can be disabled by setting the PublishTrimmed property to false. [/Users/harry/test/test.csproj::TargetFramework=net8.0-maccatalyst]
ILLink : unknown error IL7000: An error occured while executing the custom linker steps. Please review the build log for more information. [/Users/harry/test/test.csproj::TargetFramework=net8.0-ios]
ILLINK : error MT2301: The linker step 'Setup' failed during processing: Failed to parse PList data type: dict [/Users/harry/test/test.csproj::TargetFramework=net8.0-ios]
/Users/harry/.nuget/packages/microsoft.net.illink.tasks/8.0.0-preview.7.23375.6/build/Microsoft.NET.ILLink.targets(84,5): error NETSDK1144: Optimizing assemblies for size failed. Optimization can be disabled by setting the PublishTrimmed property to false. [/Users/harry/test/test.csproj::TargetFramework=net8.0-ios]
```

**Comment by samhouts** [comment] 2023-08-08 21:43
@rolfbjarne Any ideas?

**Comment by btrdurfee** [comment] 2023-08-08 22:32
I am seeing the same error after upgrading to preview 7.

**Comment by drasticactions** [comment] 2023-08-09 04:34
This is a duplicate of https://github.com/dotnet/runtime/issues/90015

**Closed by drasticactions** 2023-08-09 04:34 UTC
Labels: t/bug, platform/macOS 🍏, platform/iOS 🍎, partner/macios, i/regression, linker

**Comment by rolfbjarne** [comment] 2023-08-09 08:02
FWIW this is covered in the release notes: https://github.com/xamarin/xamarin-macios/releases/tag/dotnet-8.0.1xx-preview7-8694
