### ISSUE TITLE
Shell TabBar displays huge images (ios/macos)

### ISSUE THREAD

**Issue by MaksimAdamenko** [dotnet/maui#10993] opened 2022-10-29 16:56 UTC
### Description

Default project with only TabBar added displays huge images.
The error is on both ios and macos

![shell](https://user-images.githubusercontent.com/63460828/198843436-d6068e91-014c-46ec-a23d-969f0acb2d4c.png)

### Steps to Reproduce

1. Create a new MAUI 
2. Add TabBar
3. Start Debug

### Link to public reproduction project repository

https://github.com/MaksimAdamenko/ProblemShellTabBar

### Version with bug

Dotnet version 6.0.402
Dotnet version 7.0.100-rc.2.2247.23

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, macOS

### Affected platform versions

iOS 16.0, macos 12.6.1

**Comment by hartez** [comment] 2022-10-31 15:24
Duplicate of #8609

**Closed by hartez** 2022-10-31 15:24 UTC
Labels: t/bug
