### ISSUE TITLE
.Net Maui ImageButton Problem

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#11163] opened 2022-11-07 22:19 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Net-Maui-ImageButton-Problem/10184952)._

---
[severity:It bothers me. A fix would be nice]
Hello.

I'm learning .Net Maui these days. Similar to a tutorial, I recently made a demo project.
I tried this project on Android and Windows.

However, when the ImageButton I created in the xml file has Source svg, it works on Android but not on Windows. Although the original file version of the picture is svg, it works when you make png from xml code. Already in my research I found that this way is the solution. However, I wanted to let you know, since it still sounds wrong.

Also ImageButton renders properly on Android. However, in Windows, the bottom and right parts are erased. I checked the necessary spaces. There seems to be an error in the render.

I wanted to share them with you so that .Net Maui can get better.

I wish you good work.

[1.PNG](https://aka.ms/dc/file?name=B494c654b551b4cc08f5da1f62f24cd12638025710553353825_1.PNG&tid=494c654b551b4cc08f5da1f62f24cd12638025710553353825)
[2.PNG](https://aka.ms/dc/file?name=B2334edd33917442e85932d1ac4aca41a638025710744772322_2.PNG&tid=2334edd33917442e85932d1ac4aca41a638025710744772322)

---
#### Feedback Bot on 10/30/2022, 07:15 PM: 

(private comment, text removed)
#### Roi Chen -MSFT [MSFT] on 10/31/2022, 03:56 AM: 

(private comment, text removed)
#### Burak ERHANDI on 11/3/2022, 06:50 AM: 

(private comment, text removed)
#### Burak ERHANDI on 11/3/2022, 06:51 AM: 

(private comment, text removed)
#### Roi Chen -MSFT [MSFT] on 11/3/2022, 07:55 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by rachelkang** [comment] 2022-11-08 19:36
Hi, Burak - thank you for opening this issue. Could you please share a repro in the form of a GitHub repo so that we can investigate further? Thank you.

**Comment by mattleibow** [comment] 2022-11-10 20:29
Duplicate of #7066

**Closed by mattleibow** 2022-11-10 20:29 UTC
Labels: t/bug, area/controls 🎮, control-button, s/needs-repro
