### ISSUE TITLE
"More" Items on Tabbar with > 5 tabs doesn't load Shell styles or functionality (iOS)

### ISSUE THREAD

**Issue by edgiardina** [dotnet/maui#9834] opened 2022-09-01 00:42 UTC
### Description

Creating a Shell App in .NET MAUI, the items loaded from a "More" menu in iOS don't seem to load as Shell pages. this means any Shell.Current.GoToAsync calls launched from handlers in ContentPages navigated to via the More menu fail, and the styles assigned to Shell Titlebar and other elements are not applied. See repro repository here: https://github.com/edgiardina/MoreMenu-ShellBug-NetMaui

### Steps to Reproduce

1. Create a File -> New .NET MAUI app
2. Create a tabbar with 6 or more pages
3. Navigate to a page via the More menu on the tabbar
4. the page loaded will not respect/render styles for tabbar declared like so:

`<Style TargetType="TabBar">
    
    <Setter Property="Shell.ForegroundColor" ...
    <Setter Property="Shell.BackgroundColor" ...
    <Setter Property="Shell.TitleColor"  ...
`
5. Any Shell.Current.GoToAsync calls from a ContentPage launched from a More menu will fail. 
I believe what's happening is that the More items do not build a Shell page even if they're in a shell page, that they build a straight up navigation page.

### Link to public reproduction project repository

https://github.com/edgiardina/MoreMenu-ShellBug-NetMaui

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

tested on iOS 15.5

### Did you find any workaround?

No workaround detected other than hand-styling the pages at the ContentPage level (and using Page navigation not shell navigation).

**Comment by PureWeen** [comment] 2022-09-01 19:12
Closing this one as  duplicate of https://github.com/dotnet/maui/issues/6740
I know they aren't exact but the fix will be the same for both and it's easier to track overall with one issue

**Closed by PureWeen** 2022-09-01 19:12 UTC
Labels: t/bug, platform/iOS 🍎, area/shell 🐢

**Comment by edgiardina** [comment] 2022-09-01 19:48
Sad to see that the other issue is relegated to the backlog.
