### ISSUE TITLE
Windows app gets a unknown win32 error on exit

### ISSUE THREAD

**Issue by davefxy** [dotnet/maui#7317] opened 2022-05-19 01:47 UTC
### Description

[WebViewDemos.zip](https://github.com/dotnet/maui/files/8722841/WebViewDemos.zip)

Start the ap WebVideoDemos app on Windows. Select the last 2 entries, entering and exits. Then exit the app. Upon exiting this windows app there is an unidentified win32 error.

### Steps to Reproduce

Start the ap WebVideoDemos app on Windows. Select the last 2 entries, entering and exits. Then exit the app. Upon exiting this windows app there is an unidentified win32 error.

Included video of sequence of steps to create the error.

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

net6.0-windows 10.0.19041

### Did you find any workaround?

https://user-images.githubusercontent.com/2566250/169185987-63494b05-315a-48ac-a6aa-914837f4d35d.mp4

**Comment by XamlTest** [comment] 2022-05-19 01:55
Verified this issue with Visual Studio Enterprise **17.3.0 Preview 2.0 [32515.61.main]**. Not repro on Windows with above project.

**Comment by davefxy** [comment] 2022-05-19 13:30
Is there a procedure I can perform to help eliminate problems (clean up) from having installed all the VS previews? Sent from Mail for Windows From: Javier SuárezSent: Thursday, May 19, 2022 3:00 AMTo: dotnet/mauiCc: Davefxy; AuthorSubject: Re: [dotnet/maui] Windows app gets a unknown win32 error on exit (Issue #7317) Cannot reproduce the issue on Windows 10. I will test on Windows 11.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by jsuarezruiz** [comment] 2022-05-30 08:25
> Cannot reproduce the issue on Windows 10. I will test on Windows 11.

Tested on Windows 11 and cannot reproduce. Could you share some logs or or the exception trace?
![image](https://user-images.githubusercontent.com/6755973/170948175-36219a7a-801e-4ec3-a847-6448d7975a54.png)

**Comment by namazso** [comment] 2022-08-30 03:15
Related: https://github.com/microsoft/terminal/issues/11724 https://github.com/microsoft/microsoft-ui-xaml/issues/7260

I find it amusing that apparently WebViews have been broken for almost a year at least and no one at Microsoft seems to care about it.

**Comment by namazso** [comment] 2022-08-30 17:10
I wrote a long explanation on the bug here: https://github.com/microsoft/microsoft-ui-xaml/issues/7260#issuecomment-1231314776

A workaround I found is that leaking exactly 3 references to `Windows.System.Threading.ThreadPoolTimer` should be working now, and even when Microsoft fixes this issue, as the issue is triggered when a late decremented reference results in a reference count of 1. After this fix I can't reproduce the issue anymore.

Code:

```cs
public partial class App : MauiWinUIApplication
{
    [DllImport("api-ms-win-core-winrt-l1-1-0.dll")]
    private static extern int RoGetActivationFactory(
        IntPtr activatableClassId,
        ref Guid iid,
        out IntPtr factory);

    [DllImport("api-ms-win-core-winrt-string-l1-1-0.dll")]
    private static extern int WindowsCreateString(
        [MarshalAs(UnmanagedType.LPWStr)] string sourceString,
        int length,
        out IntPtr str);


    /// <summary>
    /// Initializes the singleton application object.  This is the first line of authored code
    /// executed, and as such is the logical equivalent of main() or WinMain().
    /// </summary>
    public App()
    {
        string name = "Windows.System.Threading.ThreadPoolTimer";
        WindowsCreateString(name, name.Length, out var str);
        var guid = new Guid(0x1a8a9d02, 0xe482, 0x461b, 0xB8, 0xC7, 0x8E, 0xFA, 0xD1, 0xCC, 0xE5, 0x90);
        RoGetActivationFactory(
            str,
            ref guid,
            out _
        );
        RoGetActivationFactory(
            str,
            ref guid,
            out _
        );
        RoGetActivationFactory(
            str,
            ref guid,
            out _
        );
        this.InitializeComponent();
	}

	protected override MauiApp CreateMauiApp() => MauiProgram.CreateMauiApp();
}
```

**Comment by u1-kino** [comment] 2022-08-31 10:53
Thank you @namazso 
After trying the suggested workaround, I no longer get a Win32 exception when closing the app. I was at a loss as to what to do as I thought it would take over a year for Microsoft to fix it, but it helped. Thank you very much.

**Comment by davefxy** [comment] 2022-10-11 09:26
You might want to retry the last weeks bug reports I submitted you were not able to reproduce on windows 10 and retry them on windows 11. Sent from Mail for Windows From: Javier SuárezSent: Thursday, May 19, 2022 3:00 AMTo: dotnet/mauiCc: Davefxy; AuthorSubject: Re: [dotnet/maui] Windows app gets a unknown win32 error on exit (Issue #7317) Cannot reproduce the issue on Windows 10. I will test on Windows 11.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by mattleibow** [comment] 2023-02-01 23:41
Thiis now fixed, YAY!

https://github.com/microsoft/microsoft-ui-xaml/issues/7260#issuecomment-1404393441

> @namazso, your analysis is spot-on, thank you. The fix is simply to let the global threadpool factory objects "leak" at app shutdown (which of course, the OS will clean up) - as also recommended by Raymond Chen.

> Fix is now available: https://www.nuget.org/packages/Microsoft.WindowsAppSDK/1.2.230118.102

**Closed** 2023-02-01 23:41 UTC
Labels: t/bug, platform/windows 🪟, area/controls 🎮, s/verified, control-webview, s/triaged
