### ISSUE TITLE
The text enters in reverse when "TextTransform = TextTransform.Uppercase"  in Entry and Editor

### ISSUE THREAD

**Issue by HobDev** [dotnet/maui#11416] opened 2022-11-16 15:29 UTC
### Description

The text enters in reverse when "TextTransform = TextTransform.Uppercase"  in Entry and Editor. Tested on Android. Unable to test on iOS due to [this](https://github.com/dotnet/maui/issues/11406) bug.

### Steps to Reproduce

Run the repro project and enter text in the Entry and Editor.

### Link to public reproduction project repository

https://github.com/HobDev/MauiBugs/tree/ReverseTextEntry

### Version with bug

7.0 (current)

### Last version that worked well

6.0.424

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 13

### Did you find any workaround?

Instead of "TextTransform = TextTransform.Uppercase" convert text to Uppercase in code.

**Comment by PureWeen** [comment] 2022-11-16 19:09
Duplicate of #11313

**Closed by PureWeen** 2022-11-16 19:09 UTC
Labels: t/bug, platform/android 🤖, area/controls 🎮, control-entry
