### ISSUE TITLE
Resource not found in .NET 9 when xaml-comp is false

### ISSUE THREAD

**Issue by davidortinau** [dotnet/maui#22536] opened 2024-05-20 20:14 UTC
### Description

Using .NET 9 Preview 4, I'm getting errors when my xaml RDs opt-out of compilation

```console
App.xaml(20,37): XamlC error XFC0124: Resource "Resources/Styles/DefaultStyles.xaml" not found.
```

And the file starts with

```xml
<?xml version="1.0" encoding="UTF-8" ?>
<?xaml-comp compile="false" ?>
<ResourceDictionary 
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml">   
```

I don't recall why I had set them to false. Changing them to true gets me past those errors.

### Version with bug

9.0.0-preview.3.10457

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.40 SR5

### Affected platforms

iOS, macOS, I was *not* able test on other platforms

**Comment by simonrozsival** [comment] 2024-05-27 09:23
This is likely a regression due to https://github.com/dotnet/maui/pull/20776

**Comment by simonrozsival** [comment] 2024-05-30 07:55
A fix was merged into the net9.0 branch

**Closed by simonrozsival** 2024-05-30 07:55 UTC
Labels: t/bug, platform/macOS 🍏, area-xaml, platform/iOS 🍎, s/verified, s/triaged, i/regression
