### ISSUE TITLE
BlazorWebView on Windows Forms locks CSS files while the app is running

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/maui#7479] opened 2022-05-25 16:34 UTC
Hot reload for CSS doesn't work for WinForms apps because the files are locked while the app is running, so you can't save changes to them.

### Repro

1.	Run a WinForms blazor app
2.	Open wwwroot\css\app.css
3.	Try to save the file. It will prompt to save as since the file is locked.

**Comment by javiercn** [comment] 2022-05-25 17:48
@SteveSandersonMS do we know why/how the file is locked?

**Comment by TanayParikh** [comment] 2022-05-26 17:08
Confirmed the bug. It's the running winforms app which is holding onto the lock:

<img width="959" alt="image" src="https://user-images.githubusercontent.com/14852843/170538996-c1b16ec6-8b0b-4b32-992c-e16acdb6ba0f.png">

Filing bug with VS (just need to update to latest first, the above was on 17.2 Preview 6).

**Comment by TanayParikh** [comment] 2022-05-26 17:13
On second thought though, why is the running app using the `wwwroot/app.css`. Shouldn't it be making a copy in the `bin` folder? Thoughts @javiercn?

**Comment by javiercn** [comment] 2022-05-28 18:04
Yep, not sure what or why it is being blocked, but during development it must stay in the original wwwroot folder.

**Comment by TanayParikh** [comment] 2022-06-07 00:20
I believe this is likely a bug in Visual Studio, specifically related to how it handles file sharing for write (save) operations. 

On the Blazor Hybrid WebView end, we request the file from the assembly here:

https://github.com/dotnet/aspnetcore/blob/4aa4ec39894cb9ca4bc5cf50460ded9c46846e23/src/Components/WebView/WebView/src/StaticContentProvider.cs#L75

This in turn goes through the file provider which uses the PhysicalFileInfo to open a read stream to the asset **with `FileShare.ReadWrite`** here:

https://github.com/dotnet/runtime/blob/757a1918c7f65183c4e727561dd9962a3afc0566/src/libraries/Microsoft.Extensions.FileProviders.Physical/src/PhysicalFileInfo.cs#L51-L57

So VS shouldn't have any trouble saving the file, unless it's trying to write to the file **without `FileShare.ReadWrite`**. If I try to save the file using notepad / notepad++ then I'm able to save it successfully. It is only VS which is having trouble saving the file. This makes me suspect this is a VS file sharing issue during the write/save stage. 

Bug has been reported to VS/WinForms team here: https://developercommunity.visualstudio.com/t/Resource-Files-Locked-in-Blazor-Hybrid-P/10055002?viewtype=all

**Comment by SteveSandersonMS** [comment] 2022-07-18 12:14
@TanayParikh Does this mean we need to work around it by loading the content into memory and then passing a different stream into WebView2? (Or more efficiently, creating some stream that maps the file data into WebView2 without WebView2 knowing that it comes from a file)

**Comment by TanayParikh** [comment] 2022-07-21 04:19
The CoreWebView2 team mentions this issue _should_ be resolved in Edge 104. I'm attempting to validate, and hopefully we're able to close this issue out shortly. 😄 

The additional stream specifically for the WebView is definitely an option if the issue isn't resolved in CoreWebView2. I've confirmed it does resolve the issue, ideally however we can avoid it, and the additional associated overhead.

**Comment by TanayParikh** [comment] 2022-07-22 17:48
Looks like the CoreWebView2 issue hasn't been resolved unfortunately. They're planning on investigating appropriately.

**Comment by TanayParikh** [comment] 2022-08-08 22:34
Just an update on this issue; we've engaged with `CoreWebView2`, and this does seem to be a bug on their end in which they're not able to close the stream after consumption. Discussing next steps...

**Comment by TanayParikh** [comment] 2022-08-17 15:18
Just an update for those tuning into this issue; continuing to engage with the `CoreWebView2` team. They currently have a (internal) PR which attempts to resolve this issue.

**Closed** 2022-08-27 01:54 UTC
Labels: t/bug, area/blazor 🕸️, blocked, s/verified, external

**Comment by TanayParikh** [comment] 2022-08-30 18:35
This has been confirmed to be resolved via https://github.com/dotnet/maui/pull/9645.

Backporting to 6.0: https://github.com/dotnet/maui/pull/9787
