### ISSUE TITLE
[Bug][Template] Add AssemblyInfo.cs to the template

### ISSUE THREAD

**Issue by davidbritch** [dotnet/maui#2207] opened 2021-08-23 10:35 UTC
### Description

At the moment, the `XamlCompilation` attribute is in the `Startup` class (https://github.com/dotnet/maui/blob/main/src/Templates/src/templates/maui-mobile/MauiApp1/Startup.cs). Can an *AssemblyInfo.cs* file be added to the template, and the assembly-level `XamlCompilation` attribute moved to it?

**Comment by Eilon** [comment] 2021-09-02 17:27
Well, there's no more `Startup` class at all now... 😄

**Comment by Eilon** [comment] 2021-09-03 17:17
I confirmed the following:

1. The current project templates don't have any `[assembly: XamlCompilationAttribute(...)]` at all.
2. When I build the current project templates in **Release** mode:
   a. With no `XamlCompilationAttribute` (the default), there are no XAML resources in the DLL
   b. When I add `[assembly: XamlCompilationAttribute(XamlCompilationOptions.Compile)]` to the project, I see the same behavior as (a) (because it's the default!)
   c. When I add `[assembly: XamlCompilationAttribute(XamlCompilationOptions.Skip)]` to the project, I _do_ see XAML resources in the DLL:
       ![image](https://user-images.githubusercontent.com/202643/132042271-ce64ae57-ef01-4d4e-9ab6-118a10ed882e.png)
3. When I build the current project templates in **Debug** mode:
   a. With no `XamlCompilationAttribute` (the default), , there *are* XAML resources in the DLL
   b. When I add `[assembly: XamlCompilationAttribute(XamlCompilationOptions.Compile)]` to the project, I **still** see the same behavior as (a) (**Is this expected?**)
   c. When I add `[assembly: XamlCompilationAttribute(XamlCompilationOptions.Skip)]` to the project, I _do_ see XAML resources in the DLL

If someone can confirm that (3).(b) is expected, then I think this issue can be closed. It seems that in Debug mode that `XamlCompilationAttribute` is ignored.

**Comment by jfversluis** [comment] 2022-02-17 13:28
@StephaneDelcroix would you be able to verify Eilons comment above and hopefully close this one?

**Comment by StephaneDelcroix** [comment] 2022-02-17 14:08
Here are the defaults for MAUI:
- XamlCompilation.Compile is the new default, and not required, or included in the templates anymore. You can override this at assembly, module, or type level
- We execute XamlC on **Debug** builds, BUT DO NOT produce a modified assembly. The purpose of running it is to get compilation time validation of the Xaml, and the purpose of not producing a modified assembly is to shorten the dev loop. So in Debug, Xaml files are included as EmbeddedResources, and evaluated at runtime
- for the files on which XamlCompilation.Compile is set (default), on **Release** builds, we run XamlC, produce and write IL to the assembly, then prune the corresponding Xaml EmbeddedResources (KeepXamlResources = false)

more info in the .targets file here https://github.com/dotnet/maui/blob/main/.nuspec/Microsoft.Maui.Controls.targets#L138-L161

So @Eilon observation are correct, and that's the expected behaviour. There's no need to add an AssemblyInfo and the attribute can be removed from `Startup.cs`

**Closed** 2022-02-17 14:17 UTC
Labels: t/bug, area/templates 📄
