### ISSUE TITLE
Centralized Permissions

### ISSUE THREAD

**Issue by aritchie** [dotnet/maui#8881] opened 2022-07-21 14:26 UTC
### Description

An easy & effective way to push proper permissions to each of the MAUI platforms within a user project.  

In the user's MAUI single project (csproj), the user would specify the following:

```xml
<ItemGroup>
    <MauiPermission Include="LocationAlways" />
</ItemGroup>
```

Which would generate

#### Info.plist
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <key>NSLocationAlwaysAndWhenInUseUsageDescription</key>
    <string>...</string>
    <key>NSLocationWhenInUseUsageDescription</key>
    <string>...</string>
    <key>UIBackgroundModes</key>
    <array>
        <string>location</string>
    </array>
</dict>
</plist>
```

#### AndroidManifest.xml
```xml
<?xml version="1.0" encoding="utf-8"?>
<manifest>
  <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
  <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
  <uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION" />
  <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
</manifest>
```

@Redth was very product manager-ish on this to the point where he kept scope creeping it ;)  The work has already been done here: https://github.com/shinyorg/buildtasks - This would be changed to MauiPermission and have all of the essentials permissions configured.

A few notes:

* We discussed localization of the descriptions, however, this only applies to iOS & MacCatalyst.  It would also bloat csproj badly.    We looked at making it use resource files but it quickly became "big" with very little value prop.  If the user wants localization on iOS app level stuff, they would need to create their own InfoPList.strings like they would with the current MAUI ApplicationTitle
* AppleBaseDescription attribute is needed for Info.plist initial values.  It is not shown in the sample above.
* I have looked at how to use this in the Shiny project.  I would like to include permissions like Jobs & BluetoothLE.  These are external to MAUI obviously. 
* This could expand into android uses-feature and iOS entitlements in the future
* Windows & Tizen are not factored into the initial project yet.

### Public API Changes

None - this would be a build script that would read the csproj

### Intended Use-Case

This would make it easy to push the proper permissions to all included MAUI platforms.

**Comment by jfversluis** [comment] 2024-07-31 09:34
Duplicate of #1661

**Closed by jfversluis** 2024-07-31 09:34 UTC
Labels: proposal/open, area-single-project
