### ISSUE TITLE
[IOS] The Border control has undesired animation.

### ISSUE THREAD

**Issue by taenito** [dotnet/maui#22329] opened 2024-05-10 10:48 UTC
### Description

The `Border` control has undesired animation.

I tried recreating my FAB control and a page with a complex layout like my application.

Video extract:

![image](https://github.com/dotnet/maui/assets/6932633/d628988d-87bc-4550-9e33-d13208299afc)

Video:

https://github.com/dotnet/maui/assets/6932633/11c4b30f-3363-4313-8192-7731d2a30f7d

### Link to public reproduction project repository

https://github.com/taenito/border-animation-ios

### Version with bug

8.0.21 SR4.1

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

**Comment by PureWeen** [comment] 2024-05-10 14:57
Duplicate of #18204

**Closed by PureWeen** 2024-05-10 14:57 UTC
Labels: t/bug

**Comment by Phenek** [comment] 2024-05-23 09:54
Border within a CollectionView appears to have a default BackgroundColor animation. 
This seems to be related to this issue.

This can be observed at the bottom of the CollectionView, where recycled view with different colors are use.
<img src="https://github.com/dotnet/maui/assets/4518686/a03095b0-575c-410e-b9d5-76f4c596987c" width="200" height="428" />
