### ISSUE TITLE
ObservableCollection changing after page with ListView it was bound to closed with  PopModalAsync

### ISSUE THREAD

**Issue by Mark-NC001** [dotnet/maui#26577] opened 2024-12-12 16:35 UTC
### Description

I have a viewmodel with an ObservableCollection of people.
I have a page that has a ListView on it that uses the ObservableCollection as it's ItemSource.
The page displays as it should.
If I then close the page by calling Navication.PopModalAsync, the page closes as expected.

If after that the viewmodel's ObservableCollection changes, it results in a NullReferenceException in Microsoft.Maui.Controls.Handlers.Compatibility.ListViewRenderer.ClearSizeEstimate()

This appears to be an issue in Windows, but Android works ok.

### Steps to Reproduce

See the related repository for sample code, and it has on-screen instructions to replicate.

### Link to public reproduction project repository

https://github.com/Mark-NC001/BindingAfterClosedPage

### Version with bug

9.0.14 SR1.4

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Relevant log output

```shell

```

**Comment by kevinxufei** [comment] 2024-12-13 08:24
I can repro this issue at Windows platform on the latest 17.13.0 preview 2.0(9.0.21 & 9.0.14 & 9.0.12).

**Comment by jfversluis** [comment] 2024-12-13 14:45
Duplicate of #26498

**Closed by jfversluis** 2024-12-13 14:45 UTC
Labels: t/bug, platform/windows 🪟, area-controls-modal, area-controls-listview, s/verified, s/triaged, migration-compatibility
