### ISSUE TITLE
[iOS] CollectionView multi-select pre-selected item VisualState error

### ISSUE THREAD

**Issue by minglu** [dotnet/maui#13072] opened 2023-02-02 03:22 UTC
### Description

I think this is a similar issue to [Xamarin.Forms #9511](https://github.com/xamarin/Xamarin.Forms/issues/9511), CollectionView [SelectedItems] initially receives/contains correct pre-selected items passed from ViewModel, selected item visual state is "Selected" but still shows "normal" style until the user selects an item, Suddenly all selected items show correct "Selected" style, but you still have to select it twice to deselect it, and it only happens to iOS, macOS.

I tried the behavior workaround suggested in the xamarin.forms issue above, it's better but somehow all pre-selected items are correctly showing "Selected" background color except the first item, also if you scroll away from the list, the style changes back to "normal" when you scroll back. so it doesn't work for me (i commented out in the testing repo)

### Steps to Reproduce

1. Checkout https://github.com/minglu/iOSCollectionViewPreselectedTest
2. Build and Run, Click the [Open Pre-selected Popup] button on the main page
3. It will popup a CollectionView that is supposed to show 3 pre-selected states from the list with Primary BackgroundColor (but not)
4. You can select any item to observe the bug
5. If you click [Apply] it will return to the main page and alert actual selected items in string list

```xml

 <VisualStateManager.VisualStateGroups>
      <VisualStateGroupList>
                 <VisualStateGroup x:Name="CommonStates">
                        <VisualState x:Name="Normal" />
                        <VisualState x:Name="Selected">
                                 <VisualState.Setters>
                                         <Setter Property="BackgroundColor" Value="{StaticResource Primary}" />
                                  </VisualState.Setters>
                        </VisualState>
                 </VisualStateGroup>
      </VisualStateGroupList>
 </VisualStateManager.VisualStateGroups>
```

```
            List<string> s = new List<string>()
            {
                "FL",
                "CA",
                "IN",
                "PA",
                "TX",
                "CO",
                "DE",
                "GA",
                "ID",
                "IL"
            };

            List<string> ss = new List<string>()
            {
                "FL",
                "PA",
                "GA"
            };

            States = new ObservableCollection<object>(s);
            SelectedStates = new ObservableCollection<object>(ss);
```

### Link to public reproduction project repository

https://github.com/minglu/iOSCollectionViewPreselectedTest

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, macOS

### Affected platform versions

iOS 16.3, macOS 12.6.3

### Did you find any workaround?

No

**Comment by PureWeen** [comment] 2023-02-02 19:19
@minglu this is mostly likely fixed with the next SR of MAUI

You can test on the preview builds of MAUI or you can wait for it to reach stable.

**Comment by Glorfindel83** [comment] 2023-03-01 07:44
As a workaround, you could try setting them with a small delay, as I did [here](https://stackoverflow.com/q/75593079/4751173):
```
    _ = Task.Run(async () => {
        await Task.Delay(100);
        Dispatcher.Dispatch(() => {
            SelectedStates = new ObservableCollection<object>(ss);
            OnPropertyChanged(nameof(SelectedStates));
        });
    });
```

**Comment by pierre01** [comment] 2023-03-11 02:24
I have a similar issue... any fixes?

**Comment by Vroomer** [comment] 2023-04-03 18:39
The same issue is happening on Windows as well.

**Comment by jinxinjuan** [comment] 2023-06-27 06:08
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 2.0. Can repro on iOS platform with sample project.
[iOSCollectionViewPreselectedTest](https://github.com/minglu/iOSCollectionViewPreselectedTest).

**Comment by beeradmoore** [comment] 2023-12-13 01:45
Confirmed it is still happening on macOS using .NET 8 (MAUI 8.0.3). Workaround by @Glorfindel83 seems to do the trick.

**Comment by PureWeen** [comment] 2024-01-22 15:50
Duplicate of #18933

**Closed by PureWeen** 2024-01-22 15:50 UTC
Labels: t/bug, platform/iOS 🍎, area/collectionview 📃, s/verified, s/triaged
