### ISSUE TITLE
RequestedThemeChanged fires at Home button press event and shows wrong RequestedTheme in iOS

### ISSUE THREAD

**Issue by arahmancsd** [dotnet/maui#15962] opened 2023-07-01 18:33 UTC
### Description

`RequestedThemeChanged` event occurs when clicking on the Home button in iOS and `AppThemeChangedEventArgs` show a wrong `RequestedTheme`.

```
public partial class App : Application
{
    public App()
    {
           InitializeComponent();
          
           // This event fires when you press the Home button on iOS
           Current.RequestedThemeChanged += Current_RequestedThemeChanged;

           MainPage = new AppShell();
    }

    private void Current_RequestedThemeChanged(object sender, AppThemeChangedEventArgs e)
    {
        // Don't handle events fired for old application instances
        // and clean up the old instance's event handler
        if (Current != this && Current is App app)
        {
            Current.RequestedThemeChanged -= Current_RequestedThemeChanged;
            return;
        }

        // Shows a different theme

        Console.WriteLine($"{e.RequestedTheme}");

        UserAppTheme = e.RequestedTheme;
    }
}
```

https://github.com/dotnet/maui/assets/7424078/856d41dd-4e93-41ee-abf2-b37e9d4a210a

### Steps to Reproduce

1. Download the repo.
2. Run the application on iOS
3. Set a breakpoint in 
`Current_RequestedThemeChanged` event in the App.cs
4. Click the Home button in the simulator to minimize the app.
5. Observe the `e.RequestedTheme` which shows a different or wrong theme.

### Link to public reproduction project repository

https://github.com/arahmancsd/MauiTestApp1

### Version with bug

7.0.49

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS

### Did you find any workaround?

No

**Comment by drasticactions** [comment] 2023-07-05 08:42
I can validate that this is happening, and the reason is... complicated.

https://github.com/dotnet/maui/blob/700944b2ac65c4807c657336b49c72c30e4da1da/src/Core/src/Platform/iOS/PageViewController.cs#L24-L35

https://github.com/dotnet/maui/blob/700944b2ac65c4807c657336b49c72c30e4da1da/src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellSectionRootRenderer.cs#L144-L150

[TraitCollectionDidChange](https://developer.apple.com/documentation/uikit/uitraitenvironment/1623516-traitcollectiondidchange) is an event that UIKit sends whenever it detects an iOS interface change. When you leave the application and go to another app or back to the home screen, iOS, for some reason, sends a `TraitCollectionDidChange` event saying that the platform theme is inverted from whatever your current set is. (If your theme is set to Light on iOS, it will send an event saying the theme is now dark). It then sends another event with the correct theme you have.


MAUI handles this event to detect platform theme changes (which it should), so it is going with what iOS is sending, inverting and reverting the theme in the background. If you did not have the code you have in place for setting the `UserAppTheme`, you would not notice anything wrong. The app will look correct when you return. Because you are setting `UserAppTheme` inside of this event, that sets the `UserAppTheme` setting to the opposite theme, so MAUI is now going "The user wants the app to be X theme, ignore the platform settings" so when iOS sends the correct theme setting again, your app will ignore it because you just told MAUI to ignore it. `UserAppTheme` is a per-app theme setting that is separate from the OS. You don't need to handle it unless you specifically want to allow different theme settings away from the platform theme, and if you want to do that, you shouldn't do that inside of the RequestedThemeChange event. If the user changes their platform theme on an OS level, and you don't have a UserAppTheme set, your app should automatically change to whatever theme they selected, you don't need to set UserAppTheme yourself.

It's hard to tell where the issue is: MAUI is responding to iOS events and iOS is sending bogus information. It could be an underlying iOS issue, a .NET iOS Binding issue (@rolfbjarne, @dalexsoto?), or somewhere else in MAUI that's causing a platform event to fire when it shouldn't (Although IMO that doesn't seem likely).

@PureWeen I'm not sure would be the right person

**Comment by arahmancsd** [comment] 2023-07-05 09:03
@drasticactions thanks for the explanation. 

If you remove/comment `UserAppTheme` in the event. iOS would behave as expected, however, in Android, you have to run the app twice to see the effect.

Steps: 
1. Comment the line mentioned.
2. Run the app on both Android and iOS
3. Press the Home button or minimize the App.
4. Change the theme from settings in the emulator/simulator to Dark/Light (both Android/iOS) 
5. Switch to the App
6. iOS theme will change, however, Android doesn't
7. For Android, you have to run the App twice to see the right theme.

` UserAppTheme = e.RequestedTheme;`

**Comment by drasticactions** [comment] 2023-07-05 09:06
AFAIK, you should never have to set UserAppTheme yourself if you are changing the theme on an OS level. If you have to do that, file a new bug.

**Comment by AnnYang01** [comment] 2023-08-01 07:07
Verified this on Visual Studio Enterprise 17.7.0 Preview 5.0 in iOS 16.4. This issue repro on .NET 8.0 with below Project:
[MauiApp12.zip](https://github.com/dotnet/maui/files/12225503/MauiApp12.zip)
Screenshot in iOS 16.4
![image](https://github.com/dotnet/maui/assets/131441429/c0e7eb37-b03d-4913-9937-87fd1e87bb25)

**Comment by rolfbjarne** [comment] 2023-08-01 08:13
> MAUI is responding to iOS events and iOS is sending bogus information. It could be an underlying iOS issue, a .NET iOS Binding issue (@rolfbjarne, @dalexsoto?)

This is unlikely to be an issue with the bindings, it sounds like something iOS does just because (testing an Xcode project would confirm this).

**Comment by hwsmo** [comment] 2023-11-16 08:55
Hi. I have now noticed the bug in my app.

Anyone have an idea for a workaround?

**Comment by rkops-bd** [comment] 2023-11-17 19:22
I'm experience this problem also, so hopefully this will be fixed asap.

**Closed** 2024-06-13 13:29 UTC
Labels: t/bug, platform/iOS 🍎, s/verified, s/triaged, s/try-latest-version, area-theme
