### ISSUE TITLE
exited with code 2147942405 (0x80070005)

### ISSUE THREAD

**Issue by dovoosh** [dotnet/maui#12984] opened 2023-01-29 09:08 UTC
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/run
Operating System: windows

window 10 pro
visual studio community 2022
Net 7

Trying new project with .NET 6 and it works :)

also in csproj file I don't have the tag. should I Add it? and if so where? <WindowsAppSdkDeploymentManagerInitialize>false</WindowsAppSdkDeploymentManagerInitialize>

**Comment by holecekp** [comment] 2023-01-29 11:12
This is a duplicate of https://github.com/dotnet/maui/issues/12080. Please, see the other issue for workarounds. Running the crashing app as Administrator first, worked for me (https://github.com/dotnet/maui/issues/12080#issuecomment-1351322492).

**Comment by dovoosh** [comment] 2023-01-29 23:50
Run as administrator does not work.

בתאריך יום א׳, 29 בינו׳ 2023, 13:12, מאת holecekp ***@***.***

**Comment by jsuarezruiz** [comment] 2023-01-30 07:56
Update to the latest [Windows 10 OS January 19](https://support.microsoft.com/en-us/topic/january-19-2023-kb5019275-os-builds-19042-2546-19044-2546-and-19045-2546-preview-8ae1b678-d38c-4249-848d-06b722e7c0ad) update
Manually install the runtime with the [Windows App SDK Runtime Installer](https://aka.ms/windowsappsdk/1.2/latest/windowsappruntimeinstall-x64.exe)
Set the project property in your MAUI app project: <PropertyGroup><WindowsAppSdkDeploymentManagerInitialize>false</WindowsAppSdkDeploymentManagerInitialize></PropertyGroup>
Update to MAUI 7.0.59 (when it is released)

**Comment by dovoosh** [comment] 2023-01-30 16:51
It is working :)

thanks alot


I updated windows and ran the SDK install.

Windows details:
  Edition: Windows 10 Pro
  version: 22H2
  OS build19045.2486
  Experience: Windows Feature Experience Pack 120.2212.4190.0







‫בתאריך יום ב׳, 30 בינו׳ 2023 ב-9:57 מאת ‪Javier Suárez‬‏ <‪
***@***.***‬‏>:‬

**Comment by dovoosh** [comment] 2023-01-30 16:54
I respond harlier in previous email.

it is working fine.

updating windows and running the window sdk install seems to work.


thanks


‫בתאריך יום ב׳, 30 בינו׳ 2023 ב-17:09 מאת ‪msftbot[bot]‬‏ <‪
***@***.***‬‏>:‬

**Comment by mattleibow** [comment] 2023-02-04 01:10
Duplicate of https://github.com/dotnet/maui/issues/12080

**Closed by mattleibow** 2023-02-04 01:10 UTC
Labels: t/bug, platform/windows 🪟, s/needs-attention
