### ISSUE TITLE
Issue Building the simplest of Repos

### ISSUE THREAD

**Issue by davidbuckleyni** [dotnet/maui#10340] opened 2022-09-27 08:10 UTC
### Description

Take a brand new empty maui app in preview and it fails to build at all with a bunch of errors even though the full work loads are installed

![image](https://user-images.githubusercontent.com/5619229/192470054-02abc1b6-3e93-43ab-ae88-21d77b52ec1d.png)

### Steps to Reproduce

1 Create brand new Maui Repo
2. Compile said Maui Repo
3. Fails to build said Repo ded
 
A fresh install of the visual studio preview was installed and uninstall

![image](https://user-images.githubusercontent.com/5619229/192471394-5709a86f-ab22-449b-9b68-1c34c407f7b0.png)

### Link to public reproduction project repository

https://github.com/davidbuckleyni/MauiApp4

### Version with bug

6.0.486 (current)

### Last version that worked well

6.0 Release Candidate 3

### Affected platforms

I was *not* able test on other platforms

### Affected platform versions

Maui Previews

### Did you find any workaround?

I persume below is the correct log as its from xamrian log menu and not a dedicated maui one 

### Relevant log output

```shell
Xamarin Information: 0 : Xamarin - 17.4.0.171-d17-4-net7+4d0f4c0: 09/27/2022 08:04:06Z
    DateTime=2022-09-27T08:04:06.7690216Z: 09/27/2022 08:04:06Z
Xamarin Information: 0 : !Xamarin - 17.4.0.171-d17-4-net7+4d0f4c0: 09/27/2022 08:04:06Z
    DateTime=2022-09-27T08:04:06.7690216Z: 09/27/2022 08:04:06Z
Xamarin.VisualStudio.TastyPackage Information: 0 : Hooked up SDB tracing adapter: 09/27/2022 08:04:06Z
    DateTime=2022-09-27T08:04:06.9670655Z: 09/27/2022 08:04:06Z
Xamarin.VisualStudio.TastyPackage Information: 0 : Initialization finished: 09/27/2022 08:04:06Z
    DateTime=2022-09-27T08:04:06.9790668Z: 09/27/2022 08:04:06Z
Xamarin.VisualStudio.Android.XamarinAndroidPackage Warning: 0 : Initializing Xamarin.VisualStudio.Android.XamarinAndroidPackage: 09/27/2022 08:04:06Z
    DateTime=2022-09-27T08:04:06.9800674Z: 09/27/2022 08:04:06Z
Xamarin.VisualStudio.IOS.Messaging.LocalMessagingInitializer Information: 0 : Connecting to Local Broker...: 09/27/2022 08:04:07Z
    DateTime=2022-09-27T08:04:07.1225955Z: 09/27/2022 08:04:07Z
Xamarin.VisualStudio.IOS.Messaging.LocalMessagingInitializer Information: 0 : !Connecting to Local Broker...: 09/27/2022 08:04:07Z
    DateTime=2022-09-27T08:04:07.1225955Z: 09/27/2022 08:04:07Z
Xamarin.VisualStudio.Android.Setup.AndroidSdkSetup Information: 0 : androidsdksetup: processing AndroidStarted event: 09/27/2022 08:04:07Z
    DateTime=2022-09-27T08:04:07.1236830Z: 09/27/2022 08:04:07Z
Xamarin.VisualStudio.Android.Setup.AndroidSdkSetup Information: 0 : androidsdksetup: verify mustCheckIfSolutionIsReady:True delay:00:00:02: 09/27/2022 08:04:07Z
    DateTime=2022-09-27T08:04:07.1256832Z: 09/27/2022 08:04:07Z
Xamarin.Messaging.Ssh.MessagingCommands Information: 0 : Checking Broker 17.4.0.171 installation...: 09/27/2022 08:04:07Z
    DateTime=2022-09-27T08:04:07.1786839Z: 09/27/2022 08:04:07Z
Xamarin.Messaging.Ssh.MessagingCommands Information: 0 : !Checking Broker 17.4.0.171 installation...: 09/27/2022 08:04:07Z
    DateTime=2022-09-27T08:04:07.1786839Z: 09/27/2022 08:04:07Z
Xamarin.Messaging.Ssh.MessagingCommands Information: 0 : Starting Broker 17.4.0.171 in port 53349...: 09/27/2022 08:04:07Z
    DateTime=2022-09-27T08:04:07.3032131Z: 09/27/2022 08:04:07Z
Xamarin.Messaging.Ssh.MessagingCommands Information: 0 : !Starting Broker 17.4.0.171 in port 53349...: 09/27/2022 08:04:07Z
    DateTime=2022-09-27T08:04:07.3032131Z: 09/27/2022 08:04:07Z
Xamarin.Messaging.Ssh.MessagingCommands Information: 0 : Broker 17.4.0.171 started successfully: 09/27/2022 08:04:07Z
    DateTime=2022-09-27T08:04:07.7238839Z: 09/27/2022 08:04:07Z
Xamarin.Messaging.Ssh.MessagingCommands Information: 0 : !Broker 17.4.0.171 started successfully: 09/27/2022 08:04:07Z
    DateTime=2022-09-27T08:04:07.7238839Z: 09/27/2022 08:04:07Z
Xamarin.VisualStudio.TastyPackage Information: 0 : Hooked up SDB tracing adapter: 09/27/2022 08:04:08Z
    DateTime=2022-09-27T08:04:08.0229084Z: 09/27/2022 08:04:08Z
Xamarin.VisualStudio.TastyPackage Information: 0 : Initialization finished: 09/27/2022 08:04:08Z
    DateTime=2022-09-27T08:04:08.0370102Z: 09/27/2022 08:04:08Z
Xamarin.VisualStudio.IOS.XamarinIOSPackage Warning: 0 : Initializing Xamarin.VisualStudio.IOS.XamarinIOSPackage.: 09/27/2022 08:04:08Z
    DateTime=2022-09-27T08:04:08.0400104Z: 09/27/2022 08:04:08Z
Xamarin.Messaging.Ssh.MessagingService Information: 0 : Agent Broker 17.4.0.171 is running: 09/27/2022 08:04:08Z
    DateTime=2022-09-27T08:04:08.2720742Z: 09/27/2022 08:04:08Z
Xamarin.VisualStudio.IOS.Messaging.LocalMessagingInitializer Information: 0 : Successfully connected to Local Broker: 09/27/2022 08:04:08Z
    DateTime=2022-09-27T08:04:08.2910749Z: 09/27/2022 08:04:08Z
Xamarin.VisualStudio.IOS.Messaging.LocalMessagingInitializer Information: 0 : !Successfully connected to Local Broker: 09/27/2022 08:04:08Z
    DateTime=2022-09-27T08:04:08.2910749Z: 09/27/2022 08:04:08Z
Xamarin.VisualStudio.IOS.Messaging.LocalMessagingInitializer Information: 0 : Starting IDB Local Agent...: 09/27/2022 08:04:08Z
    DateTime=2022-09-27T08:04:08.3190520Z: 09/27/2022 08:04:08Z
Xamarin.VisualStudio.IOS.Messaging.LocalMessagingInitializer Information: 0 : !Starting IDB Local Agent...: 09/27/2022 08:04:08Z
    DateTime=2022-09-27T08:04:08.3190520Z: 09/27/2022 08:04:08Z
Xamarin.Messaging.Ssh.MessagingCommands Information: 0 : Checking IDB.Local 17.4.0.171 installation...: 09/27/2022 08:04:08Z
    DateTime=2022-09-27T08:04:08.3265616Z: 09/27/2022 08:04:08Z
Xamarin.Messaging.Ssh.MessagingCommands Information: 0 : !Checking IDB.Local 17.4.0.171 installation...: 09/27/2022 08:04:08Z
    DateTime=2022-09-27T08:04:08.3265616Z: 09/27/2022 08:04:08Z
Xamarin.VisualStudio.Android.Setup.AndroidSdkValidation Information: 0 : androidsdksetup: verify android sdk installed: 09/27/2022 08:04:09Z
    DateTime=2022-09-27T08:04:09.1294226Z: 09/27/2022 08:04:09Z
Xamarin.VisualStudio.Android.Setup.AndroidSdkValidation Information: 0 : androidsdksetup: removing android sdk errors: 09/27/2022 08:04:09Z
    DateTime=2022-09-27T08:04:09.1304281Z: 09/27/2022 08:04:09Z
Xamarin.VisualStudio.Android.Setup.AutoSdk Information: 0 : androidsdksetup: running auto sdk on all android projects: 09/27/2022 08:04:09Z
    DateTime=2022-09-27T08:04:09.1374278Z: 09/27/2022 08:04:09Z
Xamarin.VisualStudio.Devices.DeviceManager Error: 0 : lastDebugActiveProfile: : 09/27/2022 08:04:09Z
    DateTime=2022-09-27T08:04:09.2279129Z: 09/27/2022 08:04:09Z
Xamarin.VisualStudio.ProjectSystem.ProjectPropertiesBase Information: 0 : SetSelectedDeviceAsync BEST Pixel 4 XL API 30 (Android 11.0 - API 30): 09/27/2022 08:04:09Z
    DateTime=2022-09-27T08:04:09.2349140Z: 09/27/2022 08:04:09Z
Xamarin.VisualStudio.ProjectSystem.ProjectPropertiesBase Information: 0 : !SetSelectedDeviceAsync BEST Pixel 4 XL API 30 (Android 11.0 - API 30): 09/27/2022 08:04:09Z
    DateTime=2022-09-27T08:04:09.2349140Z: 09/27/2022 08:04:09Z
Xamarin.Messaging.Ssh.MessagingService Information: 0 : Starting Agent IDB.Local 17.4.0.171...: 09/27/2022 08:04:09Z
    DateTime=2022-09-27T08:04:09.3544359Z: 09/27/2022 08:04:09Z
Xamarin.Messaging.Ssh.MessagingCommands Information: 0 : Starting IDB.Local 17.4.0.171 in port 53349...: 09/27/2022 08:04:09Z
    DateTime=2022-09-27T08:04:09.3544359Z: 09/27/2022 08:04:09Z
Xamarin.Messaging.Ssh.MessagingCommands Information: 0 : !Starting IDB.Local 17.4.0.171 in port 53349...: 09/27/2022 08:04:09Z
    DateTime=2022-09-27T08:04:09.3544359Z: 09/27/2022 08:04:09Z
Xamarin.Designer Information: 0 : 
[2022-09-27 09:04:09.4] ERROR: : Couldn't update deploy enabled state
System.AggregateException: One or more errors occurred. ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:5037
   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at Mono.AndroidTools.Adb.AdbClient.EndConnect(IAsyncResult asyncResult) in D:\a\_work\1\s\External\androidtools\Mono.AndroidTools\Adb\AdbClient.cs:line 141
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Mono.AndroidTools.AdbServer.<>c__DisplayClass9_0.<RunCommandWithMessage>b__0(Task t) in D:\a\_work\1\s\External\androidtools\Mono.AndroidTools\AdbServer.cs:line 83
   at System.Threading.Tasks.ContinuationResultTaskFromTask`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Mono.AndroidTools.AdbServer.<GetDevices>d__17.MoveNext() in D:\a\_work\1\s\External\androidtools\Mono.AndroidTools\AdbServer.cs:line 136
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.Android.Deploy.DeployService.<CanDeployAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.VisualStudio.Android.Deploy.Commands.DeployCommand.<UpdateDeployEnabledAsync>d__36.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.Designer.Tasks.<IgnoreIfFaulted>d__2.MoveNext()
---> (Inner Exception #0) System.Net.Sockets.SocketException (0x80004005): No connection could be made because the target machine actively refused it 127.0.0.1:5037
   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at Mono.AndroidTools.Adb.AdbClient.EndConnect(IAsyncResult asyncResult) in D:\a\_work\1\s\External\androidtools\Mono.AndroidTools\Adb\AdbClient.cs:line 141
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)<---
: 09/27/2022 08:04:09Z
    DateTime=2022-09-27T08:04:09.4799616Z: 09/27/2022 08:04:09Z
Xamarin.Messaging.Ssh.MessagingCommands Information: 0 : IDB.Local 17.4.0.171 started successfully: 09/27/2022 08:04:09Z
    DateTime=2022-09-27T08:04:09.7602139Z: 09/27/2022 08:04:09Z
Xamarin.Messaging.Ssh.MessagingCommands Information: 0 : !IDB.Local 17.4.0.171 started successfully: 09/27/2022 08:04:09Z
    DateTime=2022-09-27T08:04:09.7602139Z: 09/27/2022 08:04:09Z
Xamarin.Messaging.Ssh.MessagingService Information: 0 : Agent IDB.Local 17.4.0.171 is running: 09/27/2022 08:04:09Z
    DateTime=2022-09-27T08:04:09.7602139Z: 09/27/2022 08:04:09Z
Xamarin.VisualStudio.Android.Setup.AndroidSdkValidation Information: 0 : androidsdksetup: verify android sdk installed: 09/27/2022 08:04:09Z
    DateTime=2022-09-27T08:04:09.7612171Z: 09/27/2022 08:04:09Z
Xamarin.VisualStudio.Android.Setup.AndroidSdkValidation Information: 0 : androidsdksetup: removing android sdk errors: 09/27/2022 08:04:09Z
    DateTime=2022-09-27T08:04:09.7612171Z: 09/27/2022 08:04:09Z
Xamarin.VisualStudio.IOS.Messaging.LocalMessagingInitializer Information: 0 : Successfully started IDB Local Agent: 09/27/2022 08:04:09Z
    DateTime=2022-09-27T08:04:09.7642146Z: 09/27/2022 08:04:09Z
Xamarin.VisualStudio.IOS.Messaging.LocalMessagingInitializer Information: 0 : !Successfully started IDB Local Agent: 09/27/2022 08:04:09Z
    DateTime=2022-09-27T08:04:09.7642146Z: 09/27/2022 08:04:09Z
Xamarin.Messaging.Ssh.MessagingService Information: 0 : Agent IDB.Local 17.4.0.171 is running: 09/27/2022 08:04:09Z
    DateTime=2022-09-27T08:04:09.7642146Z: 09/27/2022 08:04:09Z
Xamarin.Messaging.Ssh.MessagingCommands Information: 0 : Checking xma 17.4.0.171 installation...: 09/27/2022 08:04:09Z
    DateTime=2022-09-27T08:04:09.8297283Z: 09/27/2022 08:04:09Z
Xamarin.Messaging.Ssh.MessagingCommands Information: 0 : !Checking xma 17.4.0.171 installation...: 09/27/2022 08:04:09Z
    DateTime=2022-09-27T08:04:09.8297283Z: 09/27/2022 08:04:09Z
Xamarin.VisualStudio.Android.Setup.AutoSdk Information: 0 : androidsdksetup: auto sdk check Android licenses: 09/27/2022 08:04:11Z
    DateTime=2022-09-27T08:04:11.1362246Z: 09/27/2022 08:04:11Z
Xamarin.VisualStudio.Devices.DeviceManager Error: 0 : lastDebugActiveProfile: : 09/27/2022 08:04:42Z
    DateTime=2022-09-27T08:04:42.7981381Z: 09/27/2022 08:04:42Z
Xamarin.VisualStudio.ProjectSystem.ProjectPropertiesBase Information: 0 : SetSelectedDeviceAsync BEST Simulator: 09/27/2022 08:04:42Z
    DateTime=2022-09-27T08:04:42.8091386Z: 09/27/2022 08:04:42Z
Xamarin.VisualStudio.ProjectSystem.ProjectPropertiesBase Information: 0 : !SetSelectedDeviceAsync BEST Simulator: 09/27/2022 08:04:42Z
    DateTime=2022-09-27T08:04:42.8091386Z: 09/27/2022 08:04:42Z
```

**Comment by PureWeen** [comment] 2022-09-27 18:16
Duplicate of #10234

**Closed by PureWeen** 2022-09-27 18:16 UTC
Labels: t/bug, area/setup 🪄
