### ISSUE TITLE
Unable to activate Windows Store app - The parameter is incorrect

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#9500] opened 2022-08-17 17:57 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Unable-to-activate-Windows-Store-app---T/10099465)._

---
When launching a blank MAUI template project in Visual Studio 2022 17.3 Preview 4, we get the error "Unable to activate Windows Store app ‘…’. The activation request failed with error ‘The parameter is incorrect’".

It's mentioned [here](https://developercommunity.visualstudio.com/t/unable-to-activate-windows-store-app-the-parameter/1679203#T-N10022052) that the issue is resolved in the latest Visual Studio 2022 release.
It's not in my case, so I asked there whether the fix is simply not yet included in the preview versions.
I'm creating this new ticket because my question is not answered there.

BR

---
#### Feedback Bot on 7/20/2022, 06:56 PM: 

(private comment, text removed)
#### Feedback Bot on 7/26/2022, 00:41 PM: 

(private comment, text removed)
#### Joyce Fan [MSFT] on 8/12/2022, 00:34 AM: 

(private comment, text removed)
#### Liang Ge on 8/12/2022, 03:39 AM: 

(private comment, text removed)
#### Liang Ge on 8/16/2022, 01:43 AM: 

(private comment, text removed)
#### Feedback Bot on 8/15/2022, 01:37 AM: 

(private comment, text removed)
#### Nina Chen [MSFT] on 8/15/2022, 10:53 PM: 

(private comment, text removed)
#### Feedback Bot on 8/17/2022, 01:11 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by jfversluis** [comment] 2022-08-18 12:36
Duplicate of #9324

**Closed by jfversluis** 2022-08-18 12:36 UTC
