### ISSUE TITLE
Maui platform symbols still broken in Vstudio 2022 

### ISSUE THREAD

**Issue by mariolerma** [dotnet/maui#24366] opened 2024-08-21 21:49 UTC
### Description

if you use #if ANDROID OR __ANDROID__ the code not highlight correctly neither compiles.

### Steps to Reproduce

![image](https://github.com/user-attachments/assets/f662b126-5f28-4ed5-9230-b380d48abeb5)

### Version with bug

Unknown/Other

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

API30

### Did you find any workaround?

Not yet

**Comment by Zhanglirong-Winnie** [comment] 2024-08-22 07:15
This issue has been verified using  Visual Studio 17.12 Preview 1 (8.0.80 & 8.0.72). Can repro on android platform.

**Comment by jfversluis** [comment] 2024-08-22 07:41
@mariolerma can you share a bit more about your situation? Because the dropdown doesn't seem to indicate that you are targeting Android? And we are using these directives all over our code and they work fine there. Could you maybe put together a reproduction project that shows this behavior and share the Visual Studio version that you're working with?

**Comment by mariolerma** [comment] 2024-08-22 12:41
the problem occurs when you use the vstudio 2022 Maui MultiProject.. i will
test  it on Single Maui MultiPlatform to see what happends

**Comment by mariolerma** [comment] 2024-08-22 13:54
I just tested it on single Maui multiplatform single project the ANDROID
symbol is defined however, if you select android target, looks gray out,
but the code is evaluated correctly, i mean, it checked for errors.
the debugger breakpoint skips other platforms correctly, so is something in
the code highlighting.

In the MultiProject Maui, the debug symbols are completely broken.

Regards

**Comment by drasticactions** [comment] 2024-08-26 08:15
@mariolerma For your "MultiProject" MAUI application, where is this code you have written above? Is it in a class project? A shared project? If it's a class library, does it include the Android Target Framework (`net8.0-android`)?

The `ANDROID` symbol doesn't come from MAUI UI. It's a runtime preprocessor definition that gets added when you reference an Android TFM (`net8.0-android`, for example) in your class project, unless you are defining this yourself somewhere (which you probably shouldn't, if so)

I agree with @jfversluis, I think we need to see a project repro to know exactly what you're doing. I created a new template MAUI Single project.

**Comment by mariolerma** [comment] 2024-08-26 12:56
Very simple to reproduce.
Try this
[image: image.png]
on this
[image: image.png]
an in the onclick event of the sample try to add some code that works only
for android using the #if ANDROID directive.

Regards,
ML

**Comment by jfversluis** [comment] 2024-08-26 13:00
The images are missing

**Comment by mariolerma** [comment] 2024-08-26 13:12
I'm attaching the images..

**Comment by mrstrong79** [comment] 2024-09-04 23:57
Broken for me also

**Comment by mariolerma** [comment] 2024-09-05 13:11
Latest update, they fix the symbols, but the #IF ANDROID directive is not
highlighted correctly in code

**Comment by PureWeen** [comment] 2024-09-07 01:06
Can we close this one @mariolerma ?

**Comment by mariolerma** [comment] 2024-09-07 11:19
Nope,
The symbols are good now but the highlighting is not, when you set #IF
DEBUG, is not highlighted correctly

**Comment by mattleibow** [comment] 2024-09-12 18:04
Are you able to attach repro project using GitHub?

**Comment by mariolerma** [comment] 2024-09-13 00:21
Hi there, i will , too busy these days

**Closed** 2024-10-11 00:51 UTC
Labels: t/bug, area-single-project, platform/android 🤖, s/verified, s/triaged, s/no-recent-activity, s/needs-repro
