### ISSUE TITLE
Content not rendered when setting FlowDirection as RightToLeft for ContentView in iOS and MacCatalyst

### ISSUE THREAD

**Issue by EwaldJebaraj** [dotnet/maui#13342] opened 2023-02-15 06:55 UTC
### Description

Content is not rendered when setting FlowDirection as RightToLeft for ContentView, however, it works fine in Android and Windows 

**iOS**

<img width="218" alt="iOS issue" src="https://user-images.githubusercontent.com/97146356/218954200-5f47b9dc-6aa6-49a8-ab12-ee39423a073e.png">

**Android**
<img width="197" alt="Android" src="https://user-images.githubusercontent.com/97146356/218954075-02f61bc0-fb20-4a0a-bc1b-933911cbc0ed.png">

### Steps to Reproduce

1. Run the sample in iOS
2. Note the content is not rendered in the view

### Link to public reproduction project repository

https://github.com/EwaldJebaraj/FlowDirectionIssue

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, macOS

### Affected platform versions

net7.0

**Comment by Choza-rajan** [comment] 2023-02-20 15:55
I am also faced the same issue, provide high priority to this issue

**Comment by jinxinjuan** [comment] 2023-06-09 09:09
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 1.0. Can repro on iOS platform with sample project. 
[FlowDirectionIssue](https://github.com/EwaldJebaraj/FlowDirectionIssue)

**Comment by hartez** [comment] 2023-06-09 13:39
Duplicate of #15095.

**Closed by hartez** 2023-06-09 13:39 UTC
Labels: t/bug, platform/iOS 🍎, area/localization, s/verified, s/triaged
