### ISSUE TITLE
[.NET MAUI] Application Crashes on Windows when Scaling Window which Contains Nested FlexLayout

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#19265] opened 2023-12-06 22:44 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/NET-MAUI-Application-Crashes-on-Windo/10533681)._

---
[severity:I'm unable to use this version]
Only crashes on Windows. But contents are not correctly rendered on other platforms (resizable WSA)
.NET 8 + Visual Studio 2022 v17.8.2
Sample code:
```xml
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:tk="http://schemas.microsoft.com/dotnet/2022/maui/toolkit"
             x:Class="Poster.MainPage"
             Title="Poster">

        <tk:DockLayout
            Margin="0,10"
            Padding="30,0">

            <VerticalStackLayout tk:DockLayout.DockPosition="Top"
                                 Margin="10" Padding="10">
                <FlexLayout Direction="Row"
                            JustifyContent="SpaceBetween">
                    <Label VerticalTextAlignment="Center" Margin="2,0"
                           Text="URL: " />
                    <Entry x:Name="urlInput"
                           FlexLayout.Grow="1" Margin="2,0"
                           TextChanged="OnUrlChanged"
                           Completed="StartSend"
                           Placeholder="Enter URL" />
                    <Button x:Name="sendButton"
                            HorizontalOptions="End" Margin="2,0"
                            Clicked="StartSend"
                            Text="Send" />
                </FlexLayout>
                <Label x:Name="urlHintLabel"
                       Margin="50,10,0,0"
                       TextColor="Gray" FontSize="12"
                       Text="URL" />
            </VerticalStackLayout>

            <FlexLayout
                x:Name="body"
                MinimumWidthRequest="300"
                Wrap="Wrap"
                SizeChanged="OnBodySizeChanged"
                Margin="2" Padding="2">
                <tk:DockLayout
                    Margin="5"
                    FlexLayout.Grow=".6">
                    <Label tk:DockLayout.DockPosition="Top"
                           Text="Request"/>
                    <tk:DockLayout Margin="2,0,0,0">
                        <Label VerticalTextAlignment="Center"
                               tk:DockLayout.DockPosition="Left"
                               Text="Content-Type: " />
                        <Entry x:Name="contentTypeInput"
                               FlexLayout.Grow="1"
                               Margin="2,0"
                               Text="application/x-www-from-urlencoded" />
                    </tk:DockLayout>
                    <Editor x:Name="requestBodyInput"
                            FlexLayout.Grow="1"
                            Margin="2"
                            VerticalTextAlignment="Start"
                            FontFamily="monospace"
                            Placeholder="Request body" />
                </tk:DockLayout>
                <tk:DockLayout
                    Margin="5"
                    MinimumWidthRequest="200"
                    FlexLayout.Grow=".4">
                    <Label tk:DockLayout.DockPosition="Top"
                           Text="Response" />
                    <Editor x:Name="responseStatusBox"
                            HeightRequest="80"
                            Margin="2"
                            IsReadOnly="True"
                            TextColor="Gray"
                            Text="Status" />
                    <Editor x:Name="responseBodyBox"
                            Margin="2"
                            VerticalTextAlignment="Start"
                            IsReadOnly="True"
                            FontFamily="monospace"
                            Text="Response body" />
                </tk:DockLayout>
            </FlexLayout>

        </tk:DockLayout>

</ContentPage>
```
Exception interrupt:
![image.png](https://aka.ms/dc/image?name=B8d477c4b7e094f1cae1bdbbccaf9df85638373573568114352_20231205-151554-image.png&tid=8d477c4b7e094f1cae1bdbbccaf9df85638373573568114352)
where `e` is
```log
{Microsoft.UI.Xaml.UnhandledExceptionEventArgs}
    Exception: {"The text associated with this error code could not be found.\r\n\r\nLayout cycle detected.  Layout could not complete."}
    Handled: false
    Message: "Layout cycle detected.  Layout could not complete."
    ThisPtr: 0x0000017060eef070
    WinRT.IWinRTObject.AdditionalTypeData: Count = 0
    WinRT.IWinRTObject.HasUnwrappableNativeObject: true
    WinRT.IWinRTObject.NativeObject: {WinRT.ObjectReference<WinRT.Interop.IUnknownVftbl>}
    WinRT.IWinRTObject.QueryInterfaceCache: Count = 0
    _additionalTypeData: Count = 0
    _default: null
    _inner: {WinRT.ObjectReference<WinRT.Interop.IUnknownVftbl>}
    _objRef_global__Microsoft_UI_Xaml_IUnhandledExceptionEventArgs: {WinRT.ObjectReference<WinRT.Interop.IUnknownVftbl>}
    _queryInterfaceCache: Count = 0
```

---
#### brandonstudio on 12/4/2023, 11:24 PM: 

(private comment, text removed)
#### Feedback Bot on 12/4/2023, 11:42 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by mattleibow** [comment] 2023-12-07 19:24
Duplicate of https://github.com/dotnet/maui/issues/9075

**Closed by mattleibow** 2023-12-07 19:24 UTC
Labels: t/bug
